### ISSUE TITLE
zwave issue with z-stick gen5?

### ISSUE THREAD

**Issue by TroisSix** [domoticz/domoticz#1005]
Hi,
I have a z-stick gen5 from Aeotec, and I have serious problems for a a week now:
- either I loose a few devices (with red banner) = no more refresh of values, dead device, ...
- or Domoticz completly loose the connexion with my usb z-stick --> in Setup/Hardware, the button "Setup" of my zstick is red = no more device ! 

I had a few problems for more than a month, but a reboot of pi2 was enough to make it work properly (only a few one in a week)

But for a week now, either a reboot or a shutdown and boot again are unsuccessful.
I really don't know what to do, I need advice to find a solution: domoticz bug or zstick bug ?

My configuration is : 
- Pi2 with Domoticz beta v3.5985 (I used version stable v3.5877 until yesterday, and same problems), that's why I tried 

beta version.
- Aeotec ZW090 Z-Stick Gen5
- OpenZWave USB Version: 1.4-2247-g5046b13-dirty

My zwave devices:
1 x Aeotec DSD37 Range Extender
1 x Fibaro System FGS212 Switch 3kW
2 x Aeotec ZW075 Smart Switch Gen5	Aeotec
1 x Vision ZG8101 Garage Door Detector

Thanks for your advice ;-)

**Comment by RicardP** [comment]
I have also a Aeotec Z-Stick Gen5 (but win7 host) and I have the similar issues with Philio PAN04-1B relays, if they have a power outage and becomes dead they never comeback active after power restored. Before I had an Pi2 installation with z-wave.me Razberry controller if I rebooted the Pi2 all nodes came alive, but not with the Aeotec Gen5 controller! It could be because it's battery powered, so a reboot never reboots the controller as battery kicks in.

I am also concerned about Aeotec poor RF parameters, it seems very bad in RX/TX performance, I think that is your first issue. I have ordered a 868MHz dipole antenna, and I will open my Aeotec Gen5 stick and connect external antenna and remove the battery in order to hopefully get better reception and transmission plus possibility to reboot the Controller by power on/off reset.

If I dont get better function on my Aeotec I will buy the z-wave.me UZB controller instead...

**Comment by TroisSix** [comment]
Thank you for sharing your experience. 

It's a shame that such a key have these kind of problems. 
For a test, I bought a pi3 with 3000ma ac adapter, and it works fine for a few days now. 

I was thinking about perhaps a problem with the ac adapter of the raspberry which could have a problem to provide energy for two devices: rfxcom and aeotec (chinese product...).
Perhaps this aeotec key needs a few more usb power, and the raspberry cannot all the time provide a stable energy to the usb devices?

For now, I'm waiting for other people to share their experience like you did, then I'll see if I bought a razberry or the usb key from z-wave.
I would be interested to have your feedback after changing antennas, good luck ;-)

**Comment by gizmocuz** [comment]
You have to build your mesh network.
Next or close to the usb stick (without external antenna), install for instance a fibaro wall plug that will relay the RF

**Comment by TroisSix** [comment]
Yes you're right gizmocuz, I could build my own mesh network, the problem is I have searched information on the web, and I am lost now...
1/ In fact, I have an extender (node 7), and I would like all my nodes (2 3 5 6) to pass through this extender (node 7), I don't know how to do it with domoticz? 
![zwave map - unamed](https://cloud.githubusercontent.com/assets/9765218/20672073/43f07af6-b580-11e6-9965-eedf557af909.png)
2/ And I don't know if that's normal node 4 doesn't exists anymore?
I would be very grateful if you could help me ;-)

**Comment by gizmocuz** [comment]
It seems it already does, i see 1 line from node 1 (your usb controller) to node 7

**Comment by TroisSix** [comment]
Not sure to understand, it doesn't mean nodes 2 3 5 6 are using my "zwave repeater" (node 7) ? it seems they all use directly my controller without using my extender?

For my node 4, an idea? :-)

**Comment by gizmocuz** [comment]
it seems all your nodes are talking to node 7, node 7 has one line to node 1

**Comment by gizmocuz** [comment]
You do not have a node 4

**Comment by TroisSix** [comment]
Nodes 2 and 5 doesn't seem to talk with node 7 ?
Is that a problem for my network that node4 doesn't exist anymore?
I'm lost... :-(

I know that zwave can build himself his network, so is it useful to build routes manually?
I mean, here is what I would like to do with my mesh network:
![mesh network](https://cloud.githubusercontent.com/assets/9765218/20714758/49d6d992-b64d-11e6-92df-1a5a44fa157c.png)

**Comment by gizmocuz** [comment]
zwave would find out the best way to build your network
no, it does not matter if node 4 is not available anymore, if you exclude and include a node, you always get a shift
battery powered nodes will not route traffic, probably 2 and 5 are battery powered sensors ?
There is a good book on amazon that you can buy about zwave

**Comment by jrich523** [comment]
what book is that?

**Comment by gizmocuz** [comment]
https://www.amazon.com/Z-Wave-Basics-Remote-Control-Smart/dp/1490537368
