### ISSUE TITLE
LimitlessLED Wifi Bridge v6.0 Support ?

### ISSUE THREAD

**Issue by deennoo** [domoticz/domoticz#1006]
Hello,

There is a new Limitless LED Wifi Bridge : v6 http://www.limitlessled.com/shop/wifi-bridge-v6/

This new wifi bridge introduce a Bulb on the gateway  (reconize as a 5th zone, dimmable, rgb + cold white + 10 disco scenes) and compatibility with new rgbwwwc bulb.

It introduce a new API : http://www.limitlessled.com/dev/

Do you plan to add it ?

How can we help? (got one of this new bridge), of course can try to develop a limitlessv6 hardware myself to match with this, but will need lot of help from dev.

**Comment by gizmocuz** [comment]
Cross posting, continue on the forum
