### ISSUE TITLE
Fibaro Door Sensor not working after update

### ISSUE THREAD

**Issue by jonferreira** [domoticz/domoticz#1007]
Hi,

After updating Domoticz to latest beta all my Fibaro Door Sensors (non-GEN5) seem to have stopped working. I can see in OZW Panel and Hardware - Devices that LastHeard Timestamp gets updated but the Door Sensor device doesn't get any update.

Am I the only one facing this?

**Comment by gizmocuz** [comment]
Use our forum please, also state your previous version there
