### ISSUE TITLE
impossible to save events

### ISSUE THREAD

**Issue by pihomecloud** [domoticz/domoticz#1009]
Hello, 

A significant change have been done in https://github.com/domoticz/domoticz/commit/dcae296dfabbe71c15769da9c9754057aa7b1879#diff-166e8e930e633d644e346dcb0f749a05
The url for saving events was json.html but is now event_create.wbem and a POST method implementation have been added.
But when posting event_create.wbem : Status Code:404 Not Found
Error: Webserver: File '/event_create.webem': No such file or directory (2)
Domoticz events is now read only.

I reverted the www/eventsframe.html back to the old request method and now it works.

Why the new POST method doesn't work ?

**Comment by gizmocuz** [comment]
works here... this was done because some users had very large events that where to big to transfer via a GET
try another browser like chrome, refresh your browser cache AND appcache (two different things)

**Comment by gizmocuz** [comment]
Please use our forum!
