### ISSUE TITLE
User without admin rights unable to update user variables

### ISSUE THREAD

**Issue by tomhur** [domoticz/domoticz#1012]
It's not possible to giva a normal user rights to update user variables.

This option would be useful to be able to automate things from Tasker in Android, for example.

**Comment by gizmocuz** [comment]
you can configure a local network in domoticz, does this help ?
Recently the support for this was removed because that was requested, before any user (viewer) could update things, which is no good of  course

**Comment by gizmocuz** [comment]
Should be fixed now
