### ISSUE TITLE
NetAtmo SetPoint device suggestion

### ISSUE THREAD

**Issue by apazga** [domoticz/domoticz#1015]
Hi,

From Floorplan, when you click "Thermostat SetPoint device" it takes you to the Temperature log (history of temperatures set by the user), instead of showing a selector popup like it does if you click it from "Utilities" tab.
It's ok to have the log, but it will be much more useful to have the possibility to change the temperature from the floorplan without having to go to "Utilities".

Best regards,
Abel.

**Comment by gizmocuz** [comment]
Please use our forum!
