### ISSUE TITLE
Virt counter graph fails

### ISSUE THREAD

**Issue by ikkemaniac** [domoticz/domoticz#1017]
I'm having trouble with one (of several) virtual counters: the graph won't update.

- domoticz 3.5989 compiled on *nix
- domoticz started with `-nocache` flag
- firefox cache disabled

![tn_screenshot from 2016-12-02 00 12 12](https://cloud.githubusercontent.com/assets/845292/20818643/4733b8de-b82f-11e6-9440-d2ccd07fb13a.png)

There is correct data in the db:
> sqlite> select * from Meter where DeviceRowID=18 limit 1000;
> DeviceRowID|Value|Usage|Date
> 18|15952|0|2016-12-01 00:10:00
> 18|15952|0|2016-12-01 00:15:01
> 18|15952|0|2016-12-01 00:20:00
> 18|15952|0|2016-12-01 00:25:00
> ....
> ....
> 18|15952|0|2016-12-01 23:40:00
> 18|15952|0|2016-12-01 23:45:01
> 18|15952|0|2016-12-01 23:50:00
> 18|15952|0|2016-12-01 23:55:00
> 18|15952|0|2016-12-02
> 18|15952|0|2016-12-02 00:00:01
> 18|15952|0|2016-12-02 00:05:00
> 18|15952|0|2016-12-02 00:10:00
> sqlite> 

I don't understand though why there are two records for 'midnight':
> DeviceRowID|Value|Usage|Date
> 18|15952|0|2016-12-02
> 18|15952|0|2016-12-02 00:00:01

But it is working for my other virtual counters
![tn_screenshot from 2016-12-02 00 18 45](https://cloud.githubusercontent.com/assets/845292/20818657/5a4b1af2-b82f-11e6-8f81-3d5d2c5a2adf.png)

> DeviceRowID|Value|Usage|Date
> 16|412835319|0|2016-12-02
> 16|412837901|0|2016-12-02 00:00:01

I'm still investigating but it looks like not all data is passed 'from the db' to `CWebServer::RType_HandleGraph`.

ps. Any best practices on debugging? It's a realy pita right now because
- `CMAKE_BUILD_TYPE=Debug` doesn't seem to be implemented
- `-loglevel` flag does not provide debugging info (doesn't really seem to do much?)
- `-verbose` flag shows more info about device info received but doesn't seem to do a lot more?

I'm just inserting `_log.Log(LOG_STATUS,....` trying to track stuff....

**Comment by ikkemaniac** [comment]
ok i might have misinterpreted the 'counter' definition.

I think counter cannot handle data that doesn't have any delta, 

In [WebServer.cpp line 12969 in the 3.5877 release commit](https://github.com/domoticz/domoticz/blob/15b013ce8fdbf30d7f988cb2c6d9e94a2b2cf97c/main/WebServer.cpp#L12696)
> float TotalValue = float(actValue - ulFirstValue);
> if (TotalValue != 0)
> {
>  ..... add data to array = add data to graph
> }

- get delta between last hour and this hour value
- if delta != 0 add value to graph

So no zeros will be added, this probably is the same as issue #958 . 
I understand that i cannot use counter in that case for my purposes but i still think this behaviour is wrong: zeros should be displayed.
I've pushed a commit that I think will fix this.

I'm trying to trend the Domo memory usage so this might be stable over time.. Each stored value should be displayed 'as is' for this purpose, like the `%` graphs.
My other virtual counters do work because they just don't have any delta = 0.

**Comment by gizmocuz** [comment]
a counter should always increment
you should not have a second entry for midnight, unless you played with your date/time on the system
You can build a debug build with:

> cmake -DCMAKE_BUILD_TYPE=Debug CMakeLists.txt

**Comment by ikkemaniac** [comment]
I have those midnight values on all virtual/dummy devices [13-19], physical devices [0-13] do not have them:
> DeviceRowID|Value|Usage|Date
> 
> 2|0|0|2016-12-01 23:55:00
> 2|0|0|2016-12-02 00:00:01
> 2|0|0|2016-12-02 00:05:00
> 
> 6|376020|0|2016-12-01 23:55:00
> 6|376020|0|2016-12-02 00:00:01
> 6|376020|0|2016-12-02 00:05:00
> 
> 14|0|0|2016-12-01 23:55:00
> 14|0|0|2016-12-02
> 14|0|0|2016-12-02 00:00:01
> 14|0|0|2016-12-02 00:05:00
> 
> 15|6010253133|0|2016-12-01 23:55:00
> 15|6010253133|0|2016-12-02
> 15|6010261073|0|2016-12-02 00:00:01
> 15|6010270915|0|2016-12-02 00:05:00
> 
> 16|412835319|0|2016-12-01 23:55:00
> 16|412835319|0|2016-12-02
> 16|412837901|0|2016-12-02 00:00:01
> 16|412845804|0|2016-12-02 00:05:00
> 
> 18|15952|0|2016-12-01 23:55:00
> 18|15952|0|2016-12-02
> 18|15952|0|2016-12-02 00:00:01
> 18|15952|0|2016-12-02 00:05:00
> 

I found that `CMAKE_BUILD_TYPE=Debug` changes some names and arguments for the compiler to compile MQTT, i don't see any other change happening, it doesn't provide additional logging; what am i missing?
I've seen a couple of your post where you refer to `gdb` debugging, I wasn't familiar with that. I'll look into that.

I understand i can't use 'counter' for my purpose but i still believe my fix is relevant and should be implemented to make bar graphs show zeros.

**Comment by gizmocuz** [comment]
in the debug build, the preprocessor _DEBUG is used, and of course all source information is inside incase you have a crash etc

**Comment by ikkemaniac** [comment]
I searched for both `NDEBUG` (as this was referenced in MQTT cmake files) and `_DEBUG` but i couldn't find any reference in the source. 

I'll create a pull req for the fix so you can decide whether or not to implement it.

**Comment by gizmocuz** [comment]
i would use another search tool.
For example, AccuWeather.cpp , line 15

**Comment by ikkemaniac** [comment]
I'm sorry, you are right!

**Comment by gizmocuz** [comment]
fixed in 1033
