### ISSUE TITLE
Adding Xiaomi Gateway

### ISSUE THREAD

**Issue by apazga** [domoticz/domoticz#1034]
Hi,

Tried to add "Xiaomi Gateway" new hardware item after @corbinmunce  contribution (Thanks for your work!), but after naming it and clicking Add, no hardware is added. Only happens with this new Hardware (just added mi Yeelight and it's working).

Nothing appears in log. 
Domoticz latest version (V3.6081 - 777cb17)

Regards,
Abel.

**Comment by gizmocuz** [comment]
Please use our forum, or comment on the pull request that added this
