### ISSUE TITLE
Crash on malformed MQTT input

### ISSUE THREAD

**Issue by mikeclueby4** [domoticz/domoticz#1038]
![image](https://cloud.githubusercontent.com/assets/16208265/21200441/7d7c51a4-c247-11e6-9096-3ec349c8f215.png)

Sending "foo:bar" or "foo":"bar" as MQTT message instantly crashes Domoticz. 

Trying "AAAA:BBBBBB" with DebugDiag (sorry, no dev env installed on that box) has this to say:
"access violation exception (0xc0000005) when trying to read from memory location 0x41414145" 
That's AAA followed by A+4 you're seeing there. Reading raw memory locations based on user input is generally a security no-no ;-)

I should mention that this is likely not a platform-specific vulnerability. (But I haven't looked at the code)

**Comment by gizmocuz** [comment]
Thanks for reporting, hope you can build domoticz in visual studio and see what is going on.
Coz... i can not seem to get mosquito to run under windows... pfff it keeps crashing, seems a pthreads dll issue

**Comment by mikeclueby4** [comment]
I'm 99% sure you can do this with any MQTT broker anywhere on the Internet. You won't meed Mosquitto nor Windows to test it.

It's quite likely this will happen with Domoticz on Linux, as well.

**Comment by gizmocuz** [comment]
is does not... maybe it is your client/tools or domoticz version:
![image](https://cloud.githubusercontent.com/assets/2265299/21255074/f411bdea-c369-11e6-9964-2eafcc1500cf.png)

**Comment by gizmocuz** [comment]
Maybe you could try to explain me how to get the broker/tools working under windows 10 (64bit) and i can try it on there

**Comment by mikeclueby4** [comment]
You have a clue in the MQTT -sub window: you're not getting the quotes to be sent in the messages.

Bash has different quoting rules from windows cmd. Try this:
`-m '"foo:bar"'`
or
`-m \"foo:bar\"`

![image](https://cloud.githubusercontent.com/assets/16208265/21263751/b986171e-c398-11e6-8287-686d786f7a78.png)

As for the problem with Mosquitto, you want to keep in mind that Mosquitto is a 32-bit process, and built for OpenSSL 1.0 rather than 1.1.
You want pthreadVC2.dll from
ftp://sources.redhat.com/pub/pthreads-win32/dll-latest/dll/x86/pthreadVC2.dll
and ssleay.dll + libeay.dll from 
http://slproweb.com/download/Win32OpenSSL_Light-1_0_1u.exe

But try the bash quoting first to see if Linux is also vulnerable - it's a good idea to know.

**Comment by gizmocuz** [comment]
I will test with the slashes
Please do not change the subject again, unless you can do a demonstration that you can do something actually!

**Comment by gizmocuz** [comment]
It was (just) an JSonCPP exception that stopped the application
Fixed in:
https://github.com/domoticz/domoticz/commit/6077bfa95f42b2145a7867ab8e9b39cc531ae0c7

Thanks for reporting, next time please create a topic title like i did
