### ISSUE TITLE
Lua script nolonger executing kodi plugin

### ISSUE THREAD

**Issue by cherowley** [domoticz/domoticz#1039]
Since the last few betas the following command in my lua script no longer seems to work:

 if otherdevices['Study (Kodi)'] ~= "Off" then commandArray['Study (Kodi)']='Execute script.securitycam' end

The script is run but does not show any errors in the log and the kodi boxes do not popup the cctv. Nothing has changed besides the domoticz version...

Debugging shows the command not being seen by the plugin at all.

Reverting to version: 3.5877 and it works as expected.

**Comment by gizmocuz** [comment]
Please use our forum
