### ISSUE TITLE
OpenZwave Control Panel does not reflect al zwave devices

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#1048]
Domoticz V3.6169
Synology nas 112+ latest dsm

FGWPF-102-ZW5 version

device is properly aded to domoticz and functions well
device does appear in de OpenZwave control panel when using STATISTICS
device DOES NOT appear in thre list of active devices on the bottom.
Therefor no commands can be given to these devices.

here are the screenshots
Also control panel seems  slow.
normally al devices appear at once, now they appear one by one over a 5 minute time period
the 2x fgwpf modules doe not appear

![modules](https://cloud.githubusercontent.com/assets/16853535/21288636/ce34cebc-c488-11e6-9bd0-44d714d6689d.jpg)

![openzwave2](https://cloud.githubusercontent.com/assets/16853535/21288638/d7b88f46-c488-11e6-8247-46a6c86dcb7e.jpg)

![openzwave](https://cloud.githubusercontent.com/assets/16853535/21288641/de95f0d8-c488-11e6-8c8f-151e2e58ca21.jpg)

**Comment by gizmocuz** [comment]
No idea, and please use our forum.
If you exclude the node, does all seem to be fast again ?
Any search on the openzwave forum ?
