### ISSUE TITLE
One of image file is missing or bug in code 

### ISSUE THREAD

**Issue by houk001** [domoticz/domoticz#1050]
In log file after build from github
"Error: Webserver: File '/images/Custom48.png': No such file or directory (2)"

Because file exist as Custom.png also Custom48_On.png and Custom48_Off.png exist  I think that error is in code.

**Comment by gizmocuz** [comment]
This is no bug, also please use our forum.
Maybe you use custom icons ?
Create a forum topic with this, with screenshots and the pages that request this file
