### ISSUE TITLE
Error: Webserver: File '/media/disconnect.mp3': No such file or directory (2)

### ISSUE THREAD

**Issue by Kees-V** [domoticz/domoticz#1057]
Version: 3.5877
When I was configuring domoticz (I am a second week user) there were a lot of error messages "Error: Webserver: File '/media/disconnect.mp3': No such file or directory (2)" in the log.
I found out that the error messages appeared when I was editing Blockly events.

Solution:
In the folder "domoticz/www/media" there is a "disconnect.wav" but no "disconnect.mp3".
Now that I have added a "disconnect.mp3" to the folder the error message no longer appears in the log.

**Comment by gizmocuz** [comment]
What were you configuring ?

**Comment by Kees-V** [comment]
I was changing the sequence of blocks in a Blockly event.

**Comment by ReneDW** [comment]
V3.5877 same error / same solution

**Comment by gizmocuz** [comment]
What browser are you using ?

**Comment by gizmocuz** [comment]
Try beta # 6603
Did not had any issues with the Chrome browser here

**Comment by Kees-V** [comment]
I normally use Internet Explorer 11 (on Windows 10).
Indeed the issue seems to be browser related, the error messages do not appear when I use Edge (Windows 10) or Web (Raspberry Pi).

Thanks for taking the change onboard!

**Comment by gizmocuz** [comment]
I would not recommend using IE11 , Chrome or Edge are much better/faster browsers
