### ISSUE TITLE
HttpLink for switch only showing option to send nvalue

### ISSUE THREAD

**Issue by gjdv** [domoticz/domoticz#106]
When selecting a switch to send the status of via httplink, the only selectable "value to send" from the selectionbox is "Status", with value 0:
`<select id="combosendvalue" class="combobox ui-corner-all" style="width:160px">
<option value="0">Status</option>
</select>`
This translate to the nvalue of the device. My (Fibaro) switch, however, stores its current status (on/off) in the svalue, as I found out by checking the domoticz.db DeviceStatus table.

The following fragment of www/views/dphttp.html, which does not show endtag of `<select>`, might be the cause of the problem? The comment also suggests that an `<option value="1">`, to represent the svalue, is missing in the generated page:
`<tr id="variabletosend">
            <td align="right" style="width:110px"><label for="name"><span data-i18n="Value to send"></span>:</label></td>
            
            <td><select id="combosendvalue" style="width:160px" class="combobox ui-corner-all">
        </tr>`

Thanks in advance for looking into this.

**Comment by gizmocuz** [comment]
I will add the select and td end tag in the next commit, hope this solves the problem

**Comment by gjdv** [comment]
Thanks for your quick reaction. I had some more time to look into it. The addition of `</select></td>` did not solve the problem.

I found that there is a call being made to `DPHttpController.js/ValueSelectorUpdate()`, which calls `json.htm?type=command&param=getdevicevalueoptions&idx=<device id>` and gets the following json message in return:
`{
   "result" : [
      {
         "Value" : 0,
         "Wording" : "Status"
      }
   ],
   "status" : "OK",
   "title" : "GetDeviceValueOptions"
}`

So, clearly "getdevicevalueoptions" does not return a full list for this type of device. Unfortunately I could not detail out further where the source of the problem lies as I cannot find json.htm in the source.
If you could point me to the source file where the json-call is handled, I'm happy to investigate further.

**Comment by gizmocuz** [comment]
json.htm is a virtual function, see Webserver.cpp

**Comment by gjdv** [comment]
Thanks. Managed to track it further down to `CPush::DropdownOptions`, where the domoticz database is queried.

This gives: 

```
sqlite> select * from DeviceStatus where ID=11;
ID|HardwareID|DeviceID|Unit|Name|Used|Type|SubType|SwitchType|Favorite|SignalLevel|BatteryLevel|nValue|sValue|LastUpdate|Order|AddjValue|AddjMulti|AddjValue2|AddjMulti2|StrParam1|StrParam2|LastLevel|Protected|CustomImage|Description
11|2|0000401|1|SchakelaarVitrinekast|1|17|161|0|1|7|255|0|0|2015-09-28 21:11:41|11|0.0|1.0|0.0|1.0|||0|0|0|
```

So I find Type=17=0x11 and Subtype=161=0xA1. Btw, same values are found for another type of switch (Aeon labs).

These values are used in `std::string sOptions = RFX_Type_SubType_Values(dType,dSubType);`, which is defined in RFXNames.cpp, making use of definitions found in RFXtrx.h. Here I find that pTypeLighting2 = 0x11, however there is no subtype 0xA1.
Anyhow, all Lighting 2 type switches are defined to only show "Status":

```
        { pTypeLighting2, sTypeAC, "Status" },
        { pTypeLighting2, sTypeHEU, "Status" },
        { pTypeLighting2, sTypeANSLUT, "Status" },
        { pTypeLighting2, sTypeZWaveSwitch, "Status" },
```

I haven't been able yet to pinpoint where the word "Status" is apparently linked to nvalue rather than svalue. It looks like there should be a function similar to CPush::ProcessSendValue, though.

**Comment by gizmocuz** [comment]
Is this still an issue ? Do you have a tested patch?

**Comment by gjdv** [comment]
Thanks for checking. Unfortunately I have not been able to find the source of the issue. The whole search also made me reconsider whether to go for a pull or push approach, and I think I arrived at the conclusion that a pull-architecture might be more appropriate for my case. By querying the database directly, I will circumvent the issue completely.

**Comment by gizmocuz** [comment]
Ok, then i close this issue
