### ISSUE TITLE
Domoticz release versioning incorrect

### ISSUE THREAD

**Issue by TimelessNL** [domoticz/domoticz#1060]
Hi,

Since my comments on the latest release are removed. I don't understand why though. The commit is clearly wrong, it was even a known issue but was not mentioned anywhere. How could it even be accepted? It should be rejected and re-do. But atleast it should be visible for the user that the commit is wrong.  I put this here for history purposes.

The versioning at git is inconsistent. APPVERSION is not always updated and has a offset from the created tag when it was created. The release notes are also inconsistent.

I understand and know that development is a large part of making an application. But versioning is atleast as important. Otherwise it's unclear for other users which version they run and bug reports cannot be verified since a version does not mean anything.

I'm trying to get Domoticz in the OpenWRT/LEDE package feed. But with this kind of inconsistency it would be a impossible job.

**Comment by gizmocuz** [comment]
Your comments are removed because they target the c++ code, you should have created a normal issue
As said, we know this, and can not change it for now on the current release
Not sure what you want to do about this, but maybe you could suggest a patch for the next stable release?
I think we should make a script to retrieve the next build number

**Comment by TimelessNL** [comment]
I think creating a patch is to soon. We first need to find out what we want. A script inserting the next build number could be an option. But why not detecting the tag during buildtime?

For example, on the latest release we could use:

`git clone https://github.com/domoticz/domoticz.git`
then checkout the tag:
`git checkout 3.5877`
and then do:
`git describe --tags`
which will return
`3.5877`
which can be parsed to appversion.default as a pre-build step.

Doing so will always use the tag-name as version number. But I have to admit that I do not know where the 5877 number actually comes from and why that should be in the tag. So maybe my idea is not complete yet.

**Comment by gizmocuz** [comment]
Please have a look in the makebeta and makerelease script, i think the makerelease should be changed
But next to the tag, we also have the history.txt file including a build number
so when committing the latest changes and also tagging  a release, all has to be in sync

**Comment by TimelessNL** [comment]
Yeah I was looking around and I noticed the auto generated appversion.h.txt
Because was building in a LEDE/OpenWRT buildroot environment the commands like `git rev-list HEAD --count` failed and therefor the appversion.default was used.

Mmh. Need to find another solution then. Just like issue #957 git tags are not always the usable.

**Comment by gizmocuz** [comment]
We could name the releases 3.1, 4.1, 5.1 .... and leave the debug builds with build numbers...

**Comment by TimelessNL** [comment]
Yeah I think that would be a great approach.
