### ISSUE TITLE
image FollowSchedule.png missing

### ISSUE THREAD

**Issue by gordonb3** [domoticz/domoticz#1066]
I'm seeing this error in the log since upgrading the web root from ancient

`Error: Webserver: File '/images/evohome/FollowSchedule.png': No such file or directory`

Seems related to the changes performed by gaeljw last June. Probably some generic code since the literal FollowSchedule does not appear to be part of the web content.

**Comment by gizmocuz** [comment]
Dont know how this filename is generated, somewhere in mainworker.cpp it seems
would this be the same as the 'auto' icon ?

**Comment by gordonb3** [comment]
Don't know what the intention was. My guess would be that the name is constructed on the fly in www/app/TemperatureController.js, something along the line of `'/images/evohome/'+ctrl.item.mode+'.png'`. Seems to me gaeljw either forgot to add an exception or the image. I suppose the quick and dirty fix would be to add a transparent pixel image, because I don't think there ever used to be an icon for the FollowSchedule state.

**Comment by gizmocuz** [comment]
Hmmm but following the mode looks like 'auto' ?

**Comment by gizmocuz** [comment]
You can add the image if you look, dont forget to add it also in the appcache file

**Comment by gordonb3** [comment]
> Hmmm but following the mode looks like 'auto' ?

That is such a good point you made there without even realizing it. Pull request submitted.
