### ISSUE TITLE
Add POST option fields to HTTP/HTTPS poller

### ISSUE THREAD

**Issue by dynasticorpheus** [domoticz/domoticz#1068]
Would be great if we could also add the below option fields to the HTTP/HTTPS poller allowing more devices who need this to be exposed to domoticz. (similar to Custom HTTP/Action notification)

- POST Data
- POST Content-Type
- POST Headers

cc: @sbouchex  :)

**Comment by sbouchex** [comment]
I think you are mixing 2 features:
- HTTP/HTTPS poller : domoticz is doing queries to a remote server
- Data inserting with lua scripts (see https://www.domoticz.com/wiki/Inserting_raw_data_lua_parsers) : domoticz is receiving HTTP query from a remote agent

From your request, I understand that you need to have the ability to get access to the fields with a lua_script, right ?

**Comment by dynasticorpheus** [comment]
Thanks for your quick reply

No really would like to customize those fields when to doing the actual http(s) request to the server. For example adding a token to the header when requesting data from the server storing my gas usage.

**Comment by sbouchex** [comment]
Sounds a good idea, another option will be needed : HTTP method (GET or POST)

**Comment by dynasticorpheus** [comment]
Correct, thanks for considering this because I think a lot more people would benefit from this as well.

**Comment by sbouchex** [comment]
Would you be ready to do some testing if a branch is available ?

**Comment by dynasticorpheus** [comment]
Ofcourse!

**Comment by sbouchex** [comment]
@gizmocuz I would need extra fields in the hardware table (to store "post data", "headers" & "content type"), any recommendation ? extra1, extra2, extra3 as VARCHAR (200) ?

**Comment by gizmocuz** [comment]
We gave an extra field... is that not working ?

**Comment by sbouchex** [comment]
HTTP poller hardware is already using the "extra" field to store the parsing script.

**Comment by gizmocuz** [comment]
Yes, this can be extended with the optional fields ? (split them with a special character(s))
param1[/]param2[/]param3, or a simple semicon (;)

**Comment by sbouchex** [comment]
ok I will check that

**Comment by sbouchex** [comment]
@dynasticorpheus how large would be the data your would like to post ? Could you give us a sample ?
@gizmocuz I have some doubts that all fields will feat into the 200 VAR CHAR and I may need to extend the width

**Comment by gizmocuz** [comment]
you could make it a TEXT field if you like, still 200 characters is a lot, most of the URL will be in the Address field anyway i suppose ?
@dynasticorpheus, could you give us an example what you need to post, why you need it (to what are you trying to post)
At the moment i never got this request, if it is to special, you could do it with a script of course

**Comment by dynasticorpheus** [comment]
@sbouchex  @gizmocuz  I already have this up and running in python however prefer native domoticz solution if possible.

In this case I am retrieving gas usage from my Remeha CV. (MITM session gave me insight in what the actual API was in the Etwist android app including the token it is using linked to my account)

The POST header in this case is 400 chars due to a very long token.

Below data is for one day however the API allows to set a start and end date so could potentially be more however I personally will just need daily figures. (58 = 5.8 m3 gas)

[{"start":"2016-12-23","value":58,"prediction":false,"temperature":0.0}]`

**Comment by sbouchex** [comment]
@dynasticorpheus Work in progress...

![capture](https://cloud.githubusercontent.com/assets/2684878/21531393/0c9f5088-cd48-11e6-89b7-9e54aa0020d8.PNG)

**Comment by dynasticorpheus** [comment]
@sbouchex  Cool!

**Comment by sbouchex** [comment]
@gizmocuz shall I continue considering that your proposal will not allow to store the required fields into a single table column ? Am I adding new fields ?

**Comment by gizmocuz** [comment]
No new fields please, this is not needed

**Comment by sbouchex** [comment]
ok, I will change the "extra" field to TEXT (to have a larger fields) and I will split the fields and use some encoding (like base64 for example). Not that nice...

**Comment by gizmocuz** [comment]
nothing wrong with base64

**Comment by sbouchex** [comment]
@dynasticorpheus under https://github.com/sbouchex/domoticz/tree/http_post, you will find a 'v1' of this implementation.
BEWARE : Database upgrade in place, so please backup your database

**Comment by dynasticorpheus** [comment]
@sbouchex  I am getting below error when I try to compile

```
[ 29%] Building CXX object CMakeFiles/domoticz.dir/main/WebServer.cpp.o
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp: In member function ‘void http::server::CWebServer::Cmd_AddHardware(http::server::WebEmSession&, const http::server::request&, Json::Value&)’:
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp:1271:5: error: ‘string’ was not declared in this scope
     string mode2Str = CURLEncode::URLDecode(request::findValue(&req, "Mode2"));
     ^~~~~~
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp:1271:5: note: suggested alternatives:
In file included from /usr/include/c++/6/string:39:0,
                 from /home/dynasticorpheus/domoticz-x64.http_post/main/stdafx.h:17:
/usr/include/c++/6/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
   typedef basic_string<char>    string;
                                 ^~~~~~
/usr/include/c++/6/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp:1272:12: error: expected ‘;’ before ‘mode3Str’
     string mode3Str = CURLEncode::URLDecode(request::findValue(&req, "Mode3"));
            ^~~~~~~~
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp:1273:12: error: expected ‘;’ before ‘mode4Str’
     string mode4Str = CURLEncode::URLDecode(request::findValue(&req, "Mode4"));
            ^~~~~~~~
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp:1274:12: error: expected ‘;’ before ‘mode5Str’
     string mode5Str = CURLEncode::URLDecode(request::findValue(&req, "Mode5"));
            ^~~~~~~~
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp:1275:12: error: expected ‘;’ before ‘mode6Str’
     string mode6Str = CURLEncode::URLDecode(request::findValue(&req, "Mode6"));
            ^~~~~~~~
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp: In member function ‘void http::server::CWebServer::RType_Hardware(http::server::WebEmSession&, const http::server::request&, Json::Value&)’:
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp:10284:8: error: ‘string’ was not declared in this scope
        string script;
        ^~~~~~
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp:10284:8: note: suggested alternatives:
In file included from /usr/include/c++/6/string:39:0,
                 from /home/dynasticorpheus/domoticz-x64.http_post/main/stdafx.h:17:
/usr/include/c++/6/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
   typedef basic_string<char>    string;
                                 ^~~~~~
/usr/include/c++/6/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
CMakeFiles/domoticz.dir/build.make:398: recipe for target 'CMakeFiles/domoticz.dir/main/WebServer.cpp.o' failed
make[2]: *** [CMakeFiles/domoticz.dir/main/WebServer.cpp.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sbouchex** [comment]
@dynasticorpheus Oups... fixed !

**Comment by dynasticorpheus** [comment]
@sbouchex  Still no joy I am afraid ...

```
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp: In member function ‘void http::server::CWebServer::RType_Hardware(http::server::WebEmSession&, const http::server::request&, Json::Value&)’:
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp:10284:8: error: ‘string’ was not declared in this scope
        string script;
        ^~~~~~
/home/dynasticorpheus/domoticz-x64.http_post/main/WebServer.cpp:10284:8: note: suggested alternatives:
In file included from /usr/include/c++/6/string:39:0,
                 from /home/dynasticorpheus/domoticz-x64.http_post/main/stdafx.h:17:
/usr/include/c++/6/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
   typedef basic_string<char>    string;
                                 ^~~~~~
/usr/include/c++/6/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
CMakeFiles/domoticz.dir/build.make:398: recipe for target 'CMakeFiles/domoticz.dir/main/WebServer.cpp.o' failed
make[2]: *** [CMakeFiles/domoticz.dir/main/WebServer.cpp.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sbouchex** [comment]
@dynasticorpheus  Fixed !

**Comment by dynasticorpheus** [comment]
@sbouchex  Will resume testing asap.

**Comment by gerard33** [comment]
@sbouchex 
The refresh field in the HTTP poller is always showing the value 300 even if you update the value.
The value which I have updated to (30 in this case) is being used, but in the field it still shows 300.

I am on Domoticz v3.6745.
