### ISSUE TITLE
Broken miLight LimitlessLED or not supported

### ISSUE THREAD

**Issue by Strontvlieg** [domoticz/domoticz#1072]
The miLight iBox v6 doesn't work or are not supported. Add some explain to the comment how to talk with the box. Open it in Notepad++ for a good view.
`
Startup the session
UDP.Send(20 00 00 00 16 02 62 3A D5 ED A3 01 AE 08 2D 46 61 41 A7 F6 DC AF D3 E6 00 00 1E)

sendStr:  80 00 00 00 11 00 00 00 00 00 31 00 00 00 00 00 00 00 00 00 00 00 
          ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^
Position: 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21

Position 00 till 04 - v6 iBox identification, start every request with it
Position 05         - Session ID1, stripe it from the response data UDP.Send(20 00 00 00 16 02 62 3A D5 ED A3 01 AE 08 2D 46 61 41 A7 F6 DC AF D3 E6 00 00 1E)
Position 06         - Session ID2, stripe it from the response data UDP.Send(20 00 00 00 16 02 62 3A D5 ED A3 01 AE 08 2D 46 61 41 A7 F6 DC AF D3 E6 00 00 1E)
Position 07         - 00 Splitter
Position 08         - Cycle number, rase this number every request to max 255 afther that it's 0 and starts over
Position 09         - 00 Splitter
Position 10 till 18  - The command to change the bulb settings (color/brightness/etc etc)
Position 19         - The miLight zone 00 t/m 04 00 for all zones
Position 20         - 00 Splitter
Position 21         - Checksum Position 10 t/m 20, convert to bytes

Command for position 10 till 18 to change the bulb settings
Command:   31 00 00 00 00 00 00 00 00
           ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^
Position : 00 01 02 03 04 05 06 07 08

Position 00 - Packet format convert to bytes
Position 01 - Password byte1 normal 00
Position 02 - Password byte2 normal 00
Position 03 - miLights version (00 = Wifi Bridge iBox LED Light) (08 = RGBW/WW/CW)
Position 04 - Light command1
Position 05 - Light command2
Position 06 - Light command3 Not required then 00
Position 07 - Light command4 Not required then 00
Position 08 - Light command5 Not required then 00
`

[http://www.limitlessled.com/dev/](url)

**Comment by gizmocuz** [comment]
I am not accepting things from someone with a handle like this
