### ISSUE TITLE
Faulty ID with ARC protocol

### ISSUE THREAD

**Issue by timk95** [domoticz/domoticz#1079]
While connecting my ARC switch I noticed a bug, the switch won't turn on in Domoticz but the switch itself turns on just fine. The status stays off in Domoticz.

After some searching I found the issue. Domoticz sends an on signal with the ID 00004f and immediately in the unused devices tab a ARC switch shows up with the ID 00004F (notice the capital F). I think my RFLINK capitalised the ID. (Could also be a RFLINK bug, not sure.)

With some more fiddling it turned out that house & unit combinations which results in ID's with letters in them don't work. They just stay off in the GUI.

Domoticz is on version 3.6235 compiled on 24th of december 2016 from source. I'm unfortunately not able to recompile it till next week so I'm not sure if this bug is squashed yet.

RFLINK is on version 45.9

Example House / unit combination that doesn't work: House O unit 1 (00004f)

```
2016-12-28 16:43:20.986 User: Admin initiated a switch command (56/router_meterkast/On)
2016-12-28 16:43:20.986 RFLink Sending: 10;Kaku;00004f;1;ON
2016-12-28 16:43:21.428 (RFLINK) Light/Switch (Unknown)
```

**Comment by gizmocuz** [comment]
Good find, could you propose a patch

**Comment by timk95** [comment]
Well, I'm not familiar with the code / C++ in general but I guess it would be fixed by saving the ID in uppercase when a manual switch is added to Domoticz using RFLINK (/ ARC).

**Comment by gizmocuz** [comment]
Please post this under the RFLink section in the forum
