### ISSUE TITLE
New Version of FGWPE

### ISSUE THREAD

**Issue by UnleashSpirit** [domoticz/domoticz#1080]
Hello,

I recently bought a Fibaro Wall Plug FGWPE-102.
I was able to add it but it's not correctly recognized by Domoticz : 

> FIBARO System Unknown: type=0602, id=1001

I checked the manufacturer_specific.xml and the fgwpe.xml but it seems that it's not the same configuration compared to the manual : [http://manuals.fibaro.com/content/manuals/en/FGWPEF-102/FGWPEF-102-EN-A-**v2.0**.pdf](http://manuals.fibaro.com/content/manuals/en/FGWPEF-102/FGWPEF-102-EN-A-v2.0.pdf) than the FGWPE v1

Am i wrong ?
Any ideas ?

`Running Domoticz v3.5877 on Raspberry Pi with Razberry 2`

**Comment by gizmocuz** [comment]
Please use our forum
Try the latest beta, because the configuration is there
<Product type="0602" id="1001" name="FGWPE Wall Plug" config="fibaro/fgwpe.xml" />
