### ISSUE TITLE
Blockly Events stopped working

### ISSUE THREAD

**Issue by LeonJansen** [domoticz/domoticz#1082]
Hello,

I updated to the latest BETA version (Version: 3.6265 Build Hash: b8b8e91), and now my blockly events don't work anymore. I also found out that here is thread about this on the domoticz forum:

http://www.domoticz.com/forum/viewtopic.php?f=15&t=15108&p=110992&hilit=blockly#p110992

It looks like the blockly doesn't recognise the State changes.

**Comment by sweetpants** [comment]
confirmed in v3.6266 also but only if Log 'event script triggers' are disabled

**Comment by gizmocuz** [comment]
Please use your forum, it's fixed bdw
