### ISSUE TITLE
Action path inconsistency on Windows?

### ISSUE THREAD

**Issue by gordonb3** [domoticz/domoticz#1089]
I've been informed by a beta tester of my evohome client that it appears to be impossible on Windows to set a single script path that works both for temperature devices and switches. It has been stated that the temperature devices will work with relative paths as described in the wiki, but switches don't. When setting an absolute path the switch (e.g. the evotouch device) will work but the temperature devices show logging entries stating that /c:/somepath can't be accessed.

It would be very much appreciated if this could be fixed.

**Comment by gizmocuz** [comment]
could you be a bit more specific how to test this ? We should create a switch, and specify a script for the on/off actions ?
I also think that a path should look like this script://C:\Temp\MyScript.bat under windows
(see the slash difference)

You probably have to look into
CSQLHelper::HandleOnOffAction

For windows, you need to specify the full path

**Comment by gordonb3** [comment]
The following log entries were shared with me:

Zone (temperature device)
`Error: evohome: Error script not found '/c:/Domoticz/evoclient/evo-client.exe'`
(note the additional slash at the front)

Controller (switch)
`Executing script: c:/Domoticz/evoclient/evo-client.ex`

Both action script values are loaded with the same executable, just different parameters
`script://c:/Domoticz/evoclient/evo-client.exe  <params>`

There is a [wiki page](http://www.domoticz.com/wiki/Scripts#Batch_Scripts_.28MSWindows.29) that states that the action script parameter should be loaded as
`script://Domoticz/evoclient`

Using this last syntax the zones do trigger the action script (temperature is changed) but then the controller fails.

Writing this I'm actually realizing that this is not a relative path at all. There does appear to be some kind of auto completion for Windows though that will add the current drive to the path, only not with each device type.

**Comment by gizmocuz** [comment]
thats correct for non windows, see the source link above

**Comment by gordonb3** [comment]
ow!

Who did this?

> 			std::string scriptname;
> 			if (OnAction.find("script:///") != std::string::npos)
> 				scriptname = OnAction.substr(9);
> 			else
> 				scriptname = OnAction.substr(8);
> 

That is totally wrong. It looks like an attempt to fix users (or processes?) adding an OnAction path with just two slashes instead of three. Of course the thing is: what can break if we change this? This is in evohome.cpp btw.

**Comment by gizmocuz** [comment]
I did, this because some did 3 slashes
this is for non-windows... i did not care much about scripts and windows user, but a define around it if you like

**Comment by gordonb3** [comment]
But three slashes is in fact consistent with how SQLHelper does it. Without the additional slash SQLHelper applies what one could consider a DocumentRoot (szDataFolder + "scripts/"), but this bit of code in evohome.cpp maps such paths back to root. So that does account for the inconsistency we're seeing because the controller - which is a switch - is apparently handled by SQLHelper while all the other evohome components are handled by above code snippet.

Currently don't have access to my dev environment, but I think it should work if Windows users use script:///. Windows shellExecute should automatically put the current drive in front to complete the path.

**Comment by gordonb3** [comment]
Well, as it turns out I could not make the set setpoint work with any path setting on my Win7 x64 and changing system mode would also only work if I set a full path containing a drive letter.

So here's my pull request [#1100](https://github.com/domoticz/domoticz/pull/1100) which synchronizes path handling between evohome.cpp and SQLHelper.cpp.

**Comment by gizmocuz** [comment]
Thanks
