### ISSUE TITLE
Can't build with -DUSE_PYTHON:BOOL=On

### ISSUE THREAD

**Issue by tomhur** [domoticz/domoticz#1091]
Since python 3 is used also the python C api is changed. I get these errors then I try to build:
`
/home/tommy/src/domoticz/main/EventSystem.cpp: In member function 'void CEventSystem::EvaluatePython(const string&, const string&, const string&, uint64_t, const string&, int, const char*, std::__cxx11::string, uint64_t)':
/home/tommy/src/domoticz/main/EventSystem.cpp:2233:38: error: cannot convert 'char*' to 'wchar_t*' for argument '1' to 'void Py_SetProgramName(wchar_t*)'
   Py_SetProgramName((char*)Python_exe); // will this cast lead to problems ?
                                      ^
/home/tommy/src/domoticz/main/EventSystem.cpp:2235:45: error: 'Py_InitModule' was not declared in this scope
   Py_InitModule("domoticz_", DomoticzMethods);
                                             ^
/home/tommy/src/domoticz/main/EventSystem.cpp:2239:61: error: 'PyString_FromString' was not declared in this scope
   PyList_Append(path, PyString_FromString(python_Dir.c_str()));
`
and also:
`/home/tommy/src/domoticz/push/GooglePubSubPush.cpp: In member function 'void CGooglePubSubPush::DoGooglePubSubPush()':
/home/tommy/src/domoticz/push/GooglePubSubPush.cpp:236:25: error: cannot convert 'char**' to 'wchar_t**' for argument '2' to 'void PySys_SetArgv(int, wchar_t**)'
     PySys_SetArgv(1,argv);
                         ^
/home/tommy/src/domoticz/push/GooglePubSubPush.cpp:240:41: error: cannot convert 'char*' to 'wchar_t*' for argument '1' to 'void Py_SetProgramName(wchar_t*)'
      Py_SetProgramName((char*)Python_exe); // will this cast lead to problems ?
                                         ^
/home/tommy/src/domoticz/push/GooglePubSubPush.cpp:242:48: error: 'Py_InitModule' was not declared in this scope
      Py_InitModule("domoticz_", DomoticzMethods);`

This seems to be solved in file hardware/plugins/PluginManager.cpp

I have tested with version 3.5877 and also latest in master branch.

**Comment by sweetpants** [comment]
Better open  ticket on Domoticz Forum, verified and noticed the same behaviour on my test system.

**Comment by dnpwwo** [comment]
You can't use -DUSE_PYTHON with -DUSE_PYTHON_PLUGINS=YES because 1 uses Python 2 and one uses Python 3.

Just add -DUSE_PYTHON_PLUGINS=NO

**Comment by tomhur** [comment]
Still the same problem.

In CMakeLists.txt line 66 there is a dependency for at least python 3.2. I have both python 2.7 and 3.5 installed on the system.

**Comment by dnpwwo** [comment]
If you use "cmake -DCMAKE_BUILD_TYPE=Release -DUSE_PYTHON=On -DUSE_PYTHON_PLUGINS=NO"  then line 66 should not apply.

**Comment by tomhur** [comment]
It works with:
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/domoticz -DUSE_PYTHON:BOOL=On -DUSE_PYTHON_PLUGINS=No -DUSE_STATIC_BOOST=No -DUSE_STATIC_LIBSTDCXX=No -DPYTHON_EXECUTABLE:FILEPATH=/bin/python2.7 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7 -DPYTHON_LIBRARY:FILEPATH=/usr/lib64/libpython2.7.so .`
