### ISSUE TITLE
Unable to see temperature reports 1st day of the year

### ISSUE THREAD

**Issue by gaeljw** [domoticz/domoticz#1093]
Before anything... **Happy New Year !! ;)**

I just noticed a small issue when we want to see the temperatures reports the 1st of january. When we are 01/01/XXXX, the link to 'Reports' page on the 'Log' page doesn't work.

What happens is : 
* click on link 'Reports'
* XHR GET ".../json.htm?type=graph&sensor=temp&idx=4&range=year&actyear=2017".
  * Returns something like : 
```
{
   "resultprev" : [
      ...
      {
         "d" : "2016-12-30",
         "ta" : 17.620000000000001,
         "te" : 20.699999999999999,
         "tm" : 16.300000000000001
      },
      {
         "d" : "2016-12-31",
         "ta" : 17.719999999999999,
         "te" : 20.199999999999999,
         "tm" : 16.300000000000001
      }
   ],
   "status" : "OK",
   "title" : "Graph temp year"
}
```
* Then the JS error : 
```
ShowYearReportTemp @ domoticz.js:3600
onclick @ VM1517 Log:1
domoticz.js:3605 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.success (domoticz.js:3605)
```

Concerned line is in domoticz.js file : 
`if (data.result.length>0) {`

Quick fix is to check existence of `data.result` (we only have `data.resultPrev` since no data for current [new] year for now). Not sure how the reports page behaves when there is no data though..

**Comment by gizmocuz** [comment]
Could you test and propose a fix via a pull request?

**Comment by gizmocuz** [comment]
No feedback, closing topic
