### ISSUE TITLE
custom page issue

### ISSUE THREAD

**Issue by seblang** [domoticz/domoticz#1099]
Hi 

I  am trying to use this fabulous frontpanel but nothing appear on screen when I enter the adress in Navigator.

I have this kind of error in Domoticz error log :

Error: Webserver: File '/FlatZ-Frontpage/undefined/json.htm': No such file or directory (2) 

can some body help me? 
thanks in advance
regards
sebastien

**Comment by gizmocuz** [comment]
Plz use our forum!

**Comment by seblang** [comment]
Thanks for closing I have used the forum but without any success answers

**Comment by gizmocuz** [comment]
There are 8000+ users on our forum, and there is also a french forum.
If you do not get any help, try asking the question differently, if you still do not get help, we can't help you
The issues here are for c++/code issues
