### ISSUE TITLE
Domoticz Device Removal Issue

### ISSUE THREAD

**Issue by sghazagh** [domoticz/domoticz#1102]
Hi,
I am experiencing device remove issue on Domoticz running on Raspberry Pi.(Domoticz Version 3.5877)

Sometimes when I delete a Node from the list of available Nodes in WiFI Gateway device/node list, Domoticz says that the item is removed and its not showing that in the list, so its fine!

However, I realized that its actually keep the record of that NodeID somewhere as after that it does not allow to register the device with same NodeID again.

It forces me to remove the specific NodeID from the code that I want (for example remove #define MY_NODE_ID 11) and it then add it not to the same NodeID I was deleted but into the new NodeID for instance '13'.

It shows that the NodeID 11 is not available to register on so it uses the new available NodeId which in my case is 13.
But that does not seems correct as I assume after deleting the NodeID, it should be the next available NodeID in sequence to register as default and not skip that.

Please advise if I understood it correctly and see why it's happening...
Thanks,

**Comment by gizmocuz** [comment]
could you post some screenshots ?

**Comment by sghazagh** [comment]
Hi,
Here is snapshot of my Devices listed under my WiFi Gateway (IDX11).
As you can see the 'Alarm Siren' is registered on NodeID 13.
It had happened as I couldn't re-register it on NodeID 11 after removing the NodID 11 from the list and all it's sensors at device list.

It forced me to remove my reserved NodeID in my code and let the Domoticz decide on registering and assigning the NodeID. And it registered it on NodeID 13!

Hope you find why its happening!
I have been experiencing this for some other Nodes registration on and off...
![1](https://cloud.githubusercontent.com/assets/12246858/21661805/3f0f44dc-d32a-11e6-8c9f-50254bb27ca6.png)
![2](https://cloud.githubusercontent.com/assets/12246858/21661806/3f137e94-d32a-11e6-907e-5002d6802a5e.png)

**Comment by sghazagh** [comment]
Hi again,
I dug into the domoticz.db and as I expected, have found that the record of NodID 11 still has kept in the database in table "MySensorsChild":
![db](https://cloud.githubusercontent.com/assets/12246858/21662402/8caa2c86-d32d-11e6-8af1-7667145e52d5.png)

As you know, the red rectangle row in fact is REPEATER child id which has not been deleted after removal of NodeID 11.
By the way, the last two row then have registered fine as the NodeID was changed to 13.

Hope you can help...

**Comment by gizmocuz** [comment]
Thank you for the screenshots

Strange as when you delete a node, it calls

```
void MySensorsBase::RemoveNode(const int nodeID)
{
	m_sql.safe_query("DELETE FROM MySensors WHERE (HardwareID==%d) AND (ID==%d)", m_HwdID, nodeID);
	m_sql.safe_query("DELETE FROM MySensorsChilds WHERE (HardwareID==%d) AND (NodeID=='%d')",m_HwdID, nodeID);
}
```

when a child was not found in the system, it adds it to this table

What i could expect is that when you deleted it, you directly received a value for it ?

It would also recommend to assign fixed node id's to your sketches

**Comment by sghazagh** [comment]
`It would also recommend to assign fixed node id's to your sketches`

That's exactly when my problem happens.
If I set the static NodID in my sketch I cannot add it to NodeID 11 which I want. Other Node ID like for example 14,15,... should be fine I believe.

**Comment by gizmocuz** [comment]
I can not replicate this.
If you can , or can submit a pull request to solve the issue, please open this issue again
