### ISSUE TITLE
Alert sensor Notification

### ISSUE THREAD

**Issue by nmaster2042** [domoticz/domoticz#1106]
Hi,

Version: 3.6312
Platform: Odroid C2

Description: I'm trying to add notifications on an alert sensor without success.
I've done different tests but none of them actually passed.
When I click on the Notifications button of my alert sensor I get the corresponding notifications setup page. Then I add a new notification like this one:

Type: Usage
When: Below
Value: 2
Priority: Normal
Ignore Intervel: unchecked
Custom message: leave blank
Active systems: all checked

I click Add.

Alert sensor is updated with nvalue and svalue like this:
/json.htm?type=command&param=udevice&idx=133&nvalue=1&svalue=RAS

but I never get any notification.

I have only mail notification configured in domoticz setup.

**Comment by nmaster2042** [comment]
Here some screenshots of the setup.
![alert seensor 1](https://cloud.githubusercontent.com/assets/22748840/21742822/d7cdd79c-d4f6-11e6-8400-450d449ba4ac.png)
![alert seensor 2](https://cloud.githubusercontent.com/assets/22748840/21742823/d80cdc6c-d4f6-11e6-9e0f-f265ca0829bf.png)

**Comment by gizmocuz** [comment]
Implemented in
https://github.com/domoticz/domoticz/commit/c2407ad72ef1930196d57b2a88b77ff42bdfac48

new beta available soon

**Comment by brucemiranda** [comment]
Is there any similar feature for when the Alert Sensor is updated via the Domoticz code using the SendAlertSensor function rather than when its value is updated only via the json
