### ISSUE TITLE
Alarm Level, probably related to OpenZwave.cpp

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#1107]
So I've found lots of locks use alarm level to communicate info beyond "secure" and "tamper."  My particular issue is my Kwikset 910 lock.  It uses alarm level to communicate which user opened or locked the dead bolt.  From 0 (the unknown user) to user 30.  However, Domoticz doesn't understand this info.  Open Z-Wave seems to, the OZWCP shows the proper alarm level for the corresponding user, but Domoticz shows a binary result of 0 (unknown user, or "secure" in Domoticz) or 1 for everything above 0 also know as "Tamper" in Domoticz.  Now I've used some pretty hackish means in the past to pass this info from the OZWCP to a dummy sensor in Domoticz, but I'd prefer if the info was just right there!

On a side note, it would be nice if Alarm Type also made just one sensor with a byte value rather than a bunch of sensors with binary values.  It would save a lot of scripting on my side.  Thanks :D

**Comment by gizmocuz** [comment]
Could you extend domoticz and fix this issue ? (with a git pull request)

**Comment by Ittiz** [comment]
I don't have a compiler so probably not.  Also, I'm not too familiar with the code, I'd rather leave it up to someone who knows it better than I do.  Like I said the OZWCP shows the values correctly, but in Domoticz the corresponding devices are binary sensors that show active when the same value in the OZWCP is anything other than zero.  If they were some kind of multi-level sensor rather than a binary one it might fix the issue, but I don't know all the functions that would need to be changed.  It would probably need to be changed where Domoticz creates the node and also where it updates.  Up to now, I've only found where it updates which is bewteen line 2740 and 2790 of OpenZWave.cpp.  Or maybe I'm totally off but it's updating alarm stuff there :P

**Comment by gizmocuz** [comment]
I dont think domoticz can do anything at the moment with this information.
Could you post a screenshot of the sensor from the devices table ? (id/unit/type)

**Comment by Ittiz** [comment]
Sure thing, I've attached a picture of all the devices that have populated so far from the lock.  However, I'd like to point out that there are more, but they are rare so Domoticz hasn't seen them yet.  This link: [http://s7d5.scene7.com/is/content/BDHHI/ApplicationNote-UsingASCII-Z-Wave-Locks](http://s7d5.scene7.com/is/content/BDHHI/ApplicationNote-UsingASCII-Z-Wave-Locks) gives a detailed description of how to interface with these locks and what each thing is and does.  Also, Domoticz does seem capable of getting some information on the user codes from this lock and can definitely get the "Alarm Types" (the different ways the lock was operated).  But it treats it as a binary switch.  For instance, anyone can lock the door by pressing the lock button without entering their user code.  When they do this it sets the Alarm Level to off/0 for no user.  So in Domoticz the Alarm level appears to be off.  However, if anyone enters their code it brings the alarm level to on/1 in Domoticz.  If you are in the OZWCP however, you can see the appropriate alarm level in there for the user that operated the lock.

![kwiksetdoorlock](https://cloud.githubusercontent.com/assets/24983850/21963231/e90c6208-db04-11e6-9cc3-a1669ba3c9c0.png)

**Comment by gizmocuz** [comment]
So this is for alarm types:
18
19
112
162

I am reading through the official zwave documentation at the moment

could you post a screenshot of the control panel ? How does this look when someone uses 'his/her' code to open the door
I only have one sensor with alarm type/level it seems

**Comment by gizmocuz** [comment]
Can you export your zwave configuration (from the dropdown) and search if you have the following command classes in the file, and post the contents ? (or contact me on the forum and send me the file)

COMMAND_CLASS_SENSOR_ALARM

COMMAND_CLASS_ALARM

... maybe i should add a new device type ....

**Comment by Ittiz** [comment]
Here are all the possible Alarm Types from the document I linked these numbers are in hex:

--Alarm Type: 0x11: Lock Secured at Keypad – Bolt Jammed (Not fully extended) 
--Alarm Type: 0x12: Lock Secured at Keypad – Successful (Fully extended) 
--Alarm Type: 0x13: Lock Un-Secured by User (User-ID) at Keypad
--Alarm Type: 0x15: Lock Secured using Keyed cylinder or inside thumb-turn
--Alarm Type: 0x16: Lock Un-Secured using Keyed cylinder or inside thumb-turn
--Alarm Type: 0x17: Lock Secured by Controller – Bolt Jammed (Not fully extended) 
--Alarm Type: 0x18: Lock Secured by Controller – Successful (Fully extended)
--Alarm Type: 0x19: Lock Un-Secured by Controller – Successful (Fully retracted)
--Alarm Type: 0x1A: Lock Auto Secured – Bolt Jammed (Not fully extended)
--Alarm Type: 0x1B: Lock Auto Secured – Successful (Fully extended)
--Alarm Type: 0x20: All User Codes deleted from lock
--Alarm Type: 0x70: New User Code (User-ID#) added to the lock
--Alarm Type: 0xA1: Failed User Code attempt at Keypad 
--Alarm Type: 0xA2: Attempted access by user (User-ID#) outside of scheduled
--Alarm Type: 0xA7: Low battery level 
--Alarm Type: 0xA8: Critical battery level 
--Alarm Type: 0xA9: Battery level too low to operate lock

Here is a pic of the OZWCP for the alarm type and level:
![kwiksetdoorlockozwcp](https://cloud.githubusercontent.com/assets/24983850/21985941/1eb8191c-dbcb-11e6-904b-e1b45fffd981.png)

The Alarm Type is how the deadbolt was operated. In this pic it's currently 19 in decimal which corresponds to 0x13 in hex (the list above).  The Alarm Level shows that user 6 operated the lock.  So Looking at this information in cross-referencing with the list above I can see that user 6 unlocked the dead bolt using the keypad.

Here's a snippet from the cfg file for the Kwikset's COMMAND_CLASS_ALARM:

```
<CommandClass id="113" name="COMMAND_CLASS_ALARM" version="1" request_flags="2" issecured="true">

   <Instance index="1" />

   <Value type="byte" genre="user" instance="1" index="0" label="Alarm Type" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="19" />

   <Value type="byte" genre="user" instance="1" index="1" label="Alarm Level" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="6" />

</CommandClass>
```

Notice that alarm type has 19 as a value and Alarm Level has 6 as a value.  There is no COMMAND_CLASS_SENSOR_ALARM for this lock.  IF you need more info let me know.

**Comment by gizmocuz** [comment]
Alarm types 0x0C - 0xFE are reserved, maybe i can handle these differently
I also have to make a new type of sensor, or put this in a user variable....
I will assign this to myself, and try to think of a solution in the near feature

**Comment by Ittiz** [comment]
Thanks a bunch if you need me to test it let me know.  I'm sure this stuff will apply to other smart locks as well.  Previously to get the correct user info to Domoticz I needed a browser window open on my server with OZWCP open actively passing the info through a script I wrote to dummy sensors, it was such a pain.  Also, my server blew up and I lost it all :P

**Comment by gizmocuz** [comment]
It seems that in domoticz you have a switch for each type... this switch gets updated (might with the same value) each time the alarm went off correct? Can you work with this
In OZW Control Panel you always see 1 type/level ? and this type/level is changing ?
If in domoticz you had one type/level 'sensor', you could not separate a flood or tamper alarm ?
Or see, when was the last time the 'flood' was triggered, as this might be overwritten by a new alarm of another type ?

**Comment by Ittiz** [comment]
Yes I get a switch for every type of "alarm" there is.  Every time that type of action happens, like say the door being opened by a person at the keypad it turns that switch on, but never turns it off.  It never changes, just on once it's been activated one time.  Unless I use a script to turn it off (which I do).  As for the Alarm Level there is only one switch which basically makes it useless in Domoticz. It's either 0/off for activated by no user or 1/tamper for activated by a user.  The Alarms never overwrite each other on Domoticz they are either on or off.  In OZW I only see one Alarm Type and it's value corresponds the last alarm type activated and one Alarm Level who's value is the number of last user to operate the door.  Basically if I had access to the data in Domoticz the way it is in the OZWCP that would be ideal.

**Comment by gizmocuz** [comment]
It's a notifier.. not a real switch
The Data/Time should change correct?

But i ask again:

> If in domoticz you had one type/level 'sensor', you could not separate a flood or tamper alarm ?
> Or see, when was the last time the 'flood' was triggered, as this might be overwritten by a new alarm of another type ?
> 

You do have access to the same data as the control panel has... it's http
i think if you log what is requested, you will be able to

**Comment by Ittiz** [comment]
Yes when the action happens again it updates, like a notifier rather than a switch.  I'm not sure what you mean by log what was requested though.

**Comment by gizmocuz** [comment]
I think we need a new sensor type 'ZWave Alarm' that has a nValue, and optional sValue (source node id, and sometimes we receive extra data from an alarm sensor; see zwave specs)

**Comment by Ittiz** [comment]
Ok, that sounds good, would both the Alarm Level and Alarm Type be this new type of sensor or would you be making two new sensors?

**Comment by gizmocuz** [comment]
1 new sensor (=type) with a value (=level)

**Comment by Ittiz** [comment]
So basically the nValue=Type of alarm and sValue=Level of alarm (if any)?

**Comment by gizmocuz** [comment]
Thats what i said above yes, but sValue could have more meanings

**Comment by gizmocuz** [comment]
There is always a level value

**Comment by Ittiz** [comment]
Thanks, I'm not sure if what you said early didn't show correctly in my browser but it didn't make sense. :)

**Comment by gizmocuz** [comment]
Maybe this reads better ;)
1 new sensor (with the id of the alarm type) with a value (= alarm level)

Anyway... lot has changed here already... it is not ready to commit and needs to be tested

**Comment by Ittiz** [comment]
Hmm, that makes it sound like there will be many units like there is now (see my image with all the Alarm Type units)?  And each sensor will have a value that equals the alarm level?  If that is the way it is one issue will be that some Alarm Types produce a 0 value on the alarm level.  For instance, if I lock the door with a button press on the outside of the door it sets the Alarm Type to 18 (0x12: door locked from keypad) and the Alarm Level to 0 (for no user).  

Ideally, I think there should be two sensors: Lock Alarm Type and Lock Alarm Level where the Lock Alarm Type has a value equal to the alarm type and where the Lock Alarm Level has a value equal to the alarm level.  Or maybe this is what you're doing and I'm just confused.  As for testing, I don't have a compiler, I use Win Server 2008.  If you could get me a binary compiled I can test it.  Thanks

**Comment by gizmocuz** [comment]
No.
But have a look at the zwave alarm class documentation (now open), to see the available types (not so many!)

**Comment by gizmocuz** [comment]
Please send me a PM on the forum with your email address
It could take a few days

**Comment by gizmocuz** [comment]
Could you test beta # 6694 (or higher), you should now get new devices of type 'Alarm' in the devices table
they should be updated when a new alarm type/level is received
You can not use this new sensor in domoticz yet, it is just for test at the moment

**Comment by Ittiz** [comment]
Ok, will it interfere with the existing devices on that lock?  or will they just go dead and the new ones will show up when detected?

**Comment by gizmocuz** [comment]
No, the old behaviour still exists and functions as before.

**Comment by Ittiz** [comment]
Ok so will I need to delete those devices in order to see the new values?  I updated the version and I see all the same devices and value as before when operating the lock.

**Comment by gizmocuz** [comment]
you do not need to delete anything

gizmocuz said:

Could you test beta # 6694 (or higher), you should now get new devices of type 'Alarm' in the devices table
they should be updated when a new alarm type/level is received
You can not use this new sensor in domoticz yet, it is just for test at the moment

**Comment by gizmocuz** [comment]
be sure 'accept new devices' is enabled in the settings
if you do not get new devices... it seems your node does not support protocol version-2, which is strange

**Comment by Ittiz** [comment]
I have a z-stick gen5 which I think should support version 2.  However, the door lock is being forwarded through a dimmer switch that may be older.  Also, the specs for the lock are from like 2012, I'm not sure if that is pre version 2.

**Comment by Ittiz** [comment]
this is what I have found on the lock, not sure if it helps: 
http://s7d5.scene7.com/is/content/BDHHI/z-wave-configuration
http://products.z-wavealliance.org/products/1389/pics

**Comment by gizmocuz** [comment]
your node should send out a COMMAND_CLASS_ALARM version 2
whats your node hardware? can you paste a link to the manual ?

**Comment by Ittiz** [comment]
this is what I could find: http://www.kwikset.com/electronics/homeowners/technicaldocuments.aspx#smartcode-910

Is there a way I could tell in Domoticz or the OZWCP?

**Comment by Ittiz** [comment]
this is from the zwcfg file seems to indicate version 1

```
<CommandClass id="113" name="COMMAND_CLASS_ALARM" version="1" request_flags="2" issecured="true">
                <Instance index="1" />
                <Value type="byte" genre="user" instance="1" index="0" label="Alarm Type" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="21" />
                <Value type="byte" genre="user" instance="1" index="1" label="Alarm Level" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="1" />
                <TriggerRefreshValue Genre="user" Instance="1" Index="0">
                    <RefreshClassValue CommandClass="98" RequestFlags="0" Instance="1" Index="1" />
                </TriggerRefreshValue>
</CommandClass>
```

**Comment by Ittiz** [comment]
Here's a tidbit, I have another alarmable device.  A contact sensor.  It acted like you said the door should, a new device appeared called "Alarm Type: Burglar 7 (0x07)" it's value was set to 3.  I checked in the zwcfg file and it seems that that device is command class alarm version 2.  So it seems your code works as intended, however like you thought, the door lock is version 1.

**Comment by rjblake** [comment]
Thought I'd add in some info here as well on the Aeotec Multisensor 6 which also now appears as an "Alarm Type: Burglar 7 (0x07)". It seems that the motion & vibration detection is working as follows:
In a 'normal undisturbed state', it reports 'Event: 0x00 (0)'
when 'motion' has been detected, it reports 'Event: 0x08 (8)'
when 'vibration' has been detected, it reports 'Event: 0x03 (3)'
I've taken a look at the Sigma Specifications and not sure it is in agreement with them (I could be reading wrong) as 0x08 seems to be listed as 'reserved'

**Comment by gizmocuz** [comment]
Yes, and the reserved values are using by manufacturers, best to check your manual of the node

**Comment by dannybloe** [comment]
I have an Everspring smoke detector (SF812) and that reports:

- Tamper: Alarm Type=0x01 + Alarm Level=0x11 (17)
- Powered up: AT=0x02 + AL=0x01

**Comment by rjblake** [comment]
@gizmocuz - I've taken a look at the Aeotec Engineering manual and can't find any reference to what the sensor reports as far as PIR or Vibration. Only references parameters one can set regarding reports, timers, etc.

**Comment by gizmocuz** [comment]
@rjblake, i am pretty sure you will receive this as a sensor_multilevel not as alarm

**Comment by rjblake** [comment]
I'm now officially confused on this. Yes, I expect that it would report using COMMAND_CLASS_SENSOR_MULTILEVEL_V5, but the 'Alarm type' reference is how it is being reported in Domoticz. I'll have to work out how to get OpenZwave to show the 'debug' messages so I can see what is being sent

**Comment by Ittiz** [comment]
So I upgraded to V3.6784 today and now it says my deadbolt is dead.  Does this have something to do this?

**Comment by gizmocuz** [comment]
@Ittiz , no

**Comment by Ittiz** [comment]
k yeah, I found that the battery is getting low so that is probably the culprit.  Any progress on the locks?  I see regular door lock was added which is nice, so it looks correct now.  Rather than looking closed when it's open and being pen when it closed.

**Comment by gizmocuz** [comment]
Not yet, time is a problem, help is welcome

**Comment by gizmocuz** [comment]
In the new beta version (6861) it is now possible to react via blockly/lua to the alarm type/values

![zalarm_1](https://cloud.githubusercontent.com/assets/2265299/23586116/24c4642a-018f-11e7-8ba9-8735ef583972.PNG)

![zalarm_2](https://cloud.githubusercontent.com/assets/2265299/23586117/2793bf52-018f-11e7-8524-ce01656b7e9f.PNG)

Note, do not use the alarm type/level devices !, there is a new alarm device, use this
the type/level is now combined in this new alarm-device sensor, and the old type/level will be dropped soon
Next to the alarm-device, you might also see a sensor labeled 'Access Control', which is actually the new alarm-device sensor (0x06), with for example a value

0x01 = Manual Lock  Operation or
0x02 = Manual Unlock Operation or
0x05 = Keypad Lock  Operation ...
...

... but all this can be found in the manual of the node

Beta is in the make, will take one hour.... please let me know your findings !

**Comment by Ittiz** [comment]
hmm I don't have any new devices for my door lock.  It seems it's still only recognizing alarm type version 2?  Running Domoticz version 3.6863.

**Comment by gizmocuz** [comment]
you won't get new devices compared to the latest implementation, it is only that you can use it now in blockly/lua/scripts
Alarm Version 2 is good.. and if you have sensors like below, then you can use them

![image](https://cloud.githubusercontent.com/assets/2265299/23599370/e7615fae-0240-11e7-8f2b-75919266f56e.png)

**Comment by rjblake** [comment]
@gizmocuz - great news. Just tried using Blockly (working nicely) and in Lua using otherdevices_zwavealarms['MyAeotecSensorAlarmDeviceName'] and works just as well. Many thanks

**Comment by gizmocuz** [comment]
Great! Thanks for the feedback.
Maybe it is possible you could extend the wiki a little bit ? (json part, or zwave/blockly part)

**Comment by rjblake** [comment]
Will do - I'll take a look tonight

**Comment by rjblake** [comment]
@gizmocuz - would you like me to add to this http://www.domoticz.com/wiki/Event_script_examples , or create a new Wiki entry?

**Comment by gizmocuz** [comment]
I was thinking more like in here:
http://www.domoticz.com/wiki/LUA_commands
http://www.domoticz.com/wiki/Zwave

**Comment by rjblake** [comment]
Ok - will do

**Comment by rjblake** [comment]
@gizmocuz - are there any plans to include keep a log of the sensor states?

**Comment by Ittiz** [comment]
If you could could leave the old Alarm Type and old Alarm Level devices in for COMMAND_CLASS_ALARM version 1 that would be good?  I have scripts that use it without another real option unless this stuff is implemented for version 1 as well as 2.

**Comment by gizmocuz** [comment]
No, Alarm Type/Level has to go, this was added for debug reason
beside the Type/Level you should really see another alarm class, with a more descriptive label, like 'Burglar' or something
You need to use this switch
This old way, is going to stay (for now at least)

**Comment by Ittiz** [comment]
As I mentioned above, my lock uses COMMAND_CLASS_ALARM version 1 so I don't get an extra switch.  I get the old Alarm Type and Alarm Level switches.  I need to use Alarm Type to tell my script that something has happened with the lock so my script can snatch the data in OZW rather than Domoticz. If I don't have that switch my script will need to do a costly string search on a timer, which would be much more unreliable.

**Comment by gizmocuz** [comment]
You Should have another sensor next to alarm type/level, because i take this value for this sensor from the other sensor if that makes sense
Could you post a screenshot of your devices tab, filtered with the nodeid to see all sensors belonging to that node ?

**Comment by gizmocuz** [comment]
(you should also see this in the openzwave control panel, could you show me all sensors for that node too)

**Comment by Ittiz** [comment]
Here some pics of my devices.  There is a new device called "sensor" (ID 800) however its value never changes, its last update was when I restarted Domoticz.  For the OZWCP I blurred out the user codes.

At the moment what I do is I have a script that waits for device "Alarm Type PDL" to turn on.  It then fetches the OZWCFG file and grabs the actual alarm Level and Type from there to figure out what happened and who did it.  From there it updates some dummy alert devices.

![doorlockdevices](https://cloud.githubusercontent.com/assets/24983850/24011750/0aea2140-0a52-11e7-98d0-868caff3327a.png)
![ozwcpdoorlock](https://cloud.githubusercontent.com/assets/24983850/24011751/0aeb31de-0a52-11e7-96be-f36000324f63.png)

**Comment by hvbommel** [comment]
Could it be I no longer see my BeNext TagReader500 devices because of this work in progress ? Note: I was using 2 of the 4 devices. One that indicated home/away. The other to steered the beeper.

**Comment by gizmocuz** [comment]
@hvbommel, no, because as you know i have such a tag reader and that is working correctly
(Do not use the alarm type/level)

Okey, we need to keep the alarm type/level... maybe because we do not know type = 22 ?

**Comment by hvbommel** [comment]
I will look into it and get my side fixed. Something else must be broken. Never mind, my problem I think.

**Comment by Ittiz** [comment]
@gizmocuz there are 17 different alarm types and 31 different alarm levels in OZWCP.  When an alarm type is seen for the first time by Domoticz it's added as a new device.  Which I didn't show in my pic because I couldn't get them all together. since their idxs are all over the place.  However using those is not a good solution because the action has to happen to the lock before the device appears.  Then it needs to be manually added in the devices panel before a script can act on them.  For certain things like "all users deleted from lock" and "battery dead" that is not an acceptable solution.  As for the alarm level key when a new alarm level is found nothing happens at all except the alarm level device is turned on (if the alarm level is 1 or higher) or turned off if the value was 0.  The only way to know the alarm level has changed (so that you know to check the value in OZW with a script) is through the alarm level device.

**Comment by gizmocuz** [comment]
ahhh good, so it is added, yes you need to use thos.
If you think the id's are messed up, please provide a code patch.
If you type the hex number of the id, together with the hardware name in the filter box, you should have an idea of all sensors of a node
(close enough)
And when you add a new node, you of course label all sensors correctly, so you can just filter by a name right ?

When you could use those sensors in an script it would work right ?

**Comment by hvbommel** [comment]
Forget my earlier question a dag ago. My BeNext500 now indeed works ok again after rebuilding open-zwave & domiticz.

**Comment by Ittiz** [comment]
Those extra things have always been there (since 2015 anyway).  However for things like "all users deleted from lock" and "battery dead" that is not an acceptable solution.  Because you can't use those or create notifications for them until Domoticz sees them for the first time and even then only after it's been manually added in the devices panel.  You could potentially get locked out of your house.

**Comment by Ittiz** [comment]
And oh the sensors I'm talking about are the same ones you can see in my device panel image I submitted on the 15th of Jan.
