### ISSUE TITLE
Domoticz completely stops responding if zwave dies

### ISSUE THREAD

**Issue by bjornreppen** [domoticz/domoticz#1108]
I have noticed that if my zwave network is unhealthy to the point that the zwave controller stops responding, then the domoticz web server also stops responding.  In other words all of Domoticz becomes unavailable.

I'm running my own builds on Raspberry pi 3 based off git head.

**Comment by gizmocuz** [comment]
Please use our forum

**Comment by Mashi** [comment]
Thanks.  Not really interested in discussion, just wanted to let you know about the a buggy zwave handling.
