### ISSUE TITLE
I2C.cpp contains strange assumption that __arm__ is defined only on Linux and i2c bus is exists only on ARM

### ISSUE THREAD

**Issue by samm-git** [domoticz/domoticz#1109]
Hi, 

I am now building domoticz on the FreeBSD/RPi and found that build failed on https://github.com/domoticz/domoticz/blob/master/hardware/I2C.cpp. Reason is very simple  - there are a lot of places like https://github.com/domoticz/domoticz/blob/master/hardware/I2C.cpp#L28, where there is a wrong assumption that `__arm__` is defined only on Linux (it is not, of course), and also that i2c bus works only on `__arm__` (that is also wrong). I think correct way to handle that is to add something like WITH_LINUX_I2C (and WITH_FREEBSD_I2C in the feature) and avoid to use `__arm__` in any non-arm specific places. I do not have (yet) i2c devices around, but probably in the feature will get something to add FreeBSD related code.  For now i am recommending to change defines to more correct way to avoid build failure on any non-Linux ARM device.

For now to avoid compilation error i renamed `__arm__` to `__armlinux__` locally. Same apply to https://github.com/domoticz/domoticz/blob/master/hardware/PiFace.cpp.

**Comment by samm-git** [comment]
Just a few links which will help to implement i2c on RPi/BSD
- https://vzaigrin.wordpress.com/2014/04/28/working-with-i2c-in-freebsd-on-raspberry-pi/ 
- https://github.com/gelraen/cros-ectool-freebsd/blob/master/sysutils/cros-ectool/files/patch-util__comm-i2c.c

**Comment by gizmocuz** [comment]
Thanks for the pull request
