### ISSUE TITLE
API - Unknown authentication scheme

### ISSUE THREAD

**Issue by DarrylvanderPeijl** [domoticz/domoticz#1113]
Since I upgraded to the latest stable version I'm having issues with the API of Domoticz.

My On/Off actions trigger a API call, those dont work anymore from my Pi.
When requesting the API endpoint from my laptop, I get a good reponse:

{
   "status" : "OK",
   "title" : "Update Device"
}

When requesting it from my Pi, through a LUA script or with wget, I get errors:

Connecting to 10.10.10.5:8080... connected.
HTTP request sent, awaiting response... 401 Unauthorized
Unknown authentication scheme.
Authorization failed.

Tested the following:

wget http://test:test@10.10.10.5:8080/json.htm?type=command&param=udevice&idx=82&nvalue=0&svalue=26

wget http://test:test@localhost:8080/json.htm?type=command&param=udevice&idx=82&nvalue=0&svalue=26

wget --user=test --password=test http://10.10.10.5:8080/json.htm?type=command&param=udevice&idx=82&nvalue=0&svalue=26

wget http://10.10.10.5:8080/json.htm?type=command&param=udevice&idx=82&nvalue=0&svalue=26

![image](https://cloud.githubusercontent.com/assets/11892641/21898893/9bd51394-d8ee-11e6-9edf-05f2bf4e3761.png)

ps. The forum registration is broken, capcha is not working correctly.

**Comment by gizmocuz** [comment]
Forum registration is working, we have some new members today (seen from the admin log)

Okey, seems you protected your domoticz with an username/password.
Did you set the type to basic authentication ? (as this is what you do with curl)

If this is on the same machine, you can put '127.0.0.1' in the local network option
if you always send execute this command from a fixed machine/ip address you can also put this IP address in there

There have been posts about this on the forum as well, you should be able to find them if you use the search option.

You can also use the normal login method and work with a cookie, but specifying these ip addresses in the local network option is easier

**Comment by DarrylvanderPeijl** [comment]
Thanks!
I haven't changed any settings, but after setting the local networks stuff began to work again.
