### ISSUE TITLE
Netatmo readings delayed

### ISSUE THREAD

**Issue by Emmanuel-FR** [domoticz/domoticz#1116]
Hi,

I verified that there is a delay of about 20 minutes between the readings that can be made with the Netatmo website and the measurements taken from Domoticz's log.

I don't have the expertise to check the Netatmo worker code and I don't know if it's a "feature" of Netatmo's API's, but this is a problem when you try to regulate temperature in a room (makes nice oscillations).

Here's an example (red "+" are from Netatmo website and blue "x" are from Domoticz log, units are minutes and °C, 5 mn step).

![strange](https://cloud.githubusercontent.com/assets/24943015/21948796/a98d7152-d9ed-11e6-96a6-daea875d32b4.jpg)

Two problems can be seen : 
-  a delay of about 20 minutes between the two (Domoticz log is late) ;
-  some staggering, with values being repeated 4 times (duration = 20 mn...), that seems to mean that only one measurement is made every 20 mn (?).

So, either a bug in the worker code or something on Netatmo's side ?

P.S. : I double-checked with another temperature sensor to make sure there was not some funny business with Netatmo's server.
P.P.S : The refresh rate of 20 mn is a tad long, I tried to force a refresh with a data time-out, but that was a very bad idea (got my IP banned from all Netatmo's API for one day).

**Comment by Emmanuel-FR** [comment]
I checked this morning, the issue is solved in the beta version that I had installed just before raising the issue. Good work, sorry.

**Comment by gizmocuz** [comment]
Please use our forum next time
