### ISSUE TITLE
[Project management] Tags for Beta release

### ISSUE THREAD

**Issue by CedricGatay** [domoticz/domoticz#1121]
Hi, 
I try to maintain a Docker-Domoticz image that I run on my Synology (but that should run on any x86 device). I just saw a 6367 beta release but not the tag relative to it. 
Is it planned (it could be nice to have this), may be we can have 3.6367-beta or something else if you want to denote the fact that this tag is in fact a beta ?

Regards, and keep up the great work !

**Comment by gizmocuz** [comment]
no, only releases will be tagged
can you work with this ?

**Comment by CedricGatay** [comment]
I will manage to if this is the way you want to ;). But, could you at least point me to the commit corresponding to the tag (or provide me a way to find out) ?

**Comment by gizmocuz** [comment]
For every commit, the automatic build system will build a beta
The stable releases you can find here
https://github.com/domoticz/domoticz/releases

**Comment by CedricGatay** [comment]
Ok, sounds good to me, can you tell me how do I figure out the generated version number (as shown on the download page) from a commit then ?

**Comment by gizmocuz** [comment]
I am no git expert... but you can probably do a bash/git command and strip out a tag
if no tag is found, it is a beta version
But why not always use the latest beta version?

**Comment by CedricGatay** [comment]
In fact I'm grabbing the code and building it in a Docker image : https://github.com/CedricGatay/docker_domoticz 
So I wanted to get a match between a git commit and a beta version too (to provide beta builds for the Docker image too). I assume you've got somewhere this match (version numbers are not coming out from nowhere).
Thanks for your answers anyway. If you don't have more informations, don't hesitate to close this issue as it is not really one ;)

**Comment by gizmocuz** [comment]
Not really... when the latest beta wes # 69484, and a release is created it will be the same number+1
maube in the feature a release will be 3.1, 4.1 etc

**Comment by CedricGatay** [comment]
Ok, and does the git revision appears somewhere in the builded package ?

**Comment by CedricGatay** [comment]
Nevermind, I found it on your https://releases.domoticz.com/releases/?dir=./beta page (.h files) :)

I will sort this out :)
