### ISSUE TITLE
Serial port listing on FreeBSD is incomplete

### ISSUE THREAD

**Issue by samm-git** [domoticz/domoticz#1123]
It was found that serial port listing on FreeBSD is incomplete, only USB adapters are listed. Additionally code wrongly lists .lock files. I found correct listing algorithm in the https://github.com/martinling/libserialport/blob/master/freebsd.c#L338, and planning to implement PR to domoticz.

**Comment by gizmocuz** [comment]
Looking good, if the function works you only can the ports that you can open for R/W can you verify this ?
If thats working, could you add a patch for domoticz to support this ?
Otherwise you need to make a link to ttyUSB20 for example

**Comment by samm-git** [comment]
Yes, i am planning to do the patch and prepare PR. BTW, while we are here, i have a question. There is a not very common hardware, turris gadgets (https://www.turris.cz/gadgets/). This is experimental project of the Czech brand (Jablotron) which producing alarm systems. They created a patch for the very old domoticz version, which i currently ported to the latest domoticz with a minimal changes. I own such hardware, so planning to test it and polish if needed. Patch is not big (https://github.com/domoticz/domoticz/compare/master...samm-git:jablotron) and i am thinking to do a pull request after testing. Are you ok with this?

**Comment by gizmocuz** [comment]
Can you build this with our new python plugin system ? see the example files in plugin/examples

**Comment by samm-git** [comment]
@gizmocuz i can try, but my python knowledge is very limited now, so it would take some time.
