### ISSUE TITLE
No sValues for pTypeLimitlessLights

### ISSUE THREAD

**Issue by deennoo** [domoticz/domoticz#1124]
Using Domoticz : 
Version: 3.6367
Build Hash: bf2a0004
Compile Date: 2017-01-15 15:05:07

And LimitlessLights Hardware (Yeelight / MiLight)

There is no sValues for this device on database, please can you add it for brightness level ? as for Hue ?

Thanks

**Comment by gizmocuz** [comment]
brightness is stored in lastlevel (see MainWorker::decode_LimitlessLights)

**Comment by deennoo** [comment]
Ok, can we use it for sValues on code? Or get it via lua ?

**Comment by deennoo** [comment]
according EventSystem.cpp do i have to create a "otherdevice_lastlevel" fonction as it's do for svalues ?

https://github.com/domoticz/domoticz/blob/2fd8bdc3ffb9c681267892154807917fe3e8cad2/main/EventSystem.cpp#L2428

**Comment by corbinmunce** [comment]
this should now be resolved, with limitless lights storing the brightness in svalue

**Comment by deennoo** [comment]
Ok thank you.
