### ISSUE TITLE
Fully Support for Fibaro Motion v3.2 

### ISSUE THREAD

**Issue by kmandevnull** [domoticz/domoticz#1132]
This is issue is a super-set of the issue #1131

Aside to the above issue, there are other issues such as
1.After motion is detected, motion sensor continues to stays ON, after functioning fine for a few days.
2. Or, it doesn't detect motion at all.
Additional details are available here: https://www.domoticz.com/forum/viewtopic.php?f=24&t=11044&p=114743#p114743

**Setup details:**

domoticz v3.5877 (latest stable version)
OZW version 1.3492.
controller: aeon zstick gen5 USB
sensor: fibaro motion FGMS-001 EU v3.2

=======
If somebody, here could suggest, what additional details would you require to resolve the full support of domoticz for this new device. Thanks.

**Comment by gizmocuz** [comment]
Please use our forum
Also try to set an OFF delay to 5 minutes, and try the motion sensor again, maybe it does not send an off ?

**Comment by dutchdevil83** [comment]
i can confirm that since last update i also have issues with the motion sensor. Sensor and Burglar stays on and is not turning off. Seems like the changes in the zwave xml file is messing things up in domoticz.

**Comment by gizmocuz** [comment]
Please dont cross post!
Since it's a problem starting with a configuration file update, please contact openzwave directly
