### ISSUE TITLE
Extend Display values for Dummy Distance device

### ISSUE THREAD

**Issue by bvermolen** [domoticz/domoticz#1133]
I want to display the distance between my phone and my house. The dummy distance device only provides centimeter and inches as unit of measure. A distance of 12 000 000 cm is not readable.

Please add also meters/kilometers to show easy to read values. 

An extra extension would be to dynamically switch between km/m/cm/mm based on the distance (don't know if that is possible).

Version: 3.5877
Build Hash: 15b013c
Compile Date: 2016-11-10 16:44:33

**Comment by gizmocuz** [comment]
You can create a custom sensor for this
Please use our forum
