### ISSUE TITLE
SQL Query error reported in CWebServer::RType_HandleGraph

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#1137]
While browsing the data from the Domoticz android app, I'm getting some SQL error :

2017-01-18 19:28:49.855 Error: SQL Query("SELECT Value, Date FROM MultiMeter_Calendar WHERE (DeviceRowID==20 AND Date>='2017-01-11' AND Date<='2017-01-18') ORDER BY Date ASC") : no such column: Value

Probably because I have a "FIBARO System FGWPE Wall Plug" device (i.e. multi-meter)

**Comment by gizmocuz** [comment]
I think it should have requested the data from the Meter_Calendar table , instead of the multi_meter
But what sensor data are requesting ? And do you experience this in the normal web gui as well ?

**Comment by sbouchex** [comment]
I'm not experiencing the same issue with the web gui.

The problem occurs while asking weekly data on the device called "Conso Purif"

Database attached

[domoticz.zip](https://github.com/domoticz/domoticz/files/717413/domoticz.zip)

**Comment by gizmocuz** [comment]
I can not test this as i do not use the android app
Please contact the author of the app

**Comment by sbouchex** [comment]
OK I will
