### ISSUE TITLE
GUI Switches tab loading slow

### ISSUE THREAD

**Issue by SilverViper** [domoticz/domoticz#1139]
I noticed that when I switch to the Switches tab several times it takes longer and longer to load in most browsers, most noticeable in IE and Edge but also Chrome. I ran profiling while switching to the Switches tab and it appears that /app/LightsController.js is ran to add lots of childs to the DOM. Looking in the DOM I can see this is used to create "Manual Light/Switch" and "Learn Light/Switch" buttons.

However, switching to a different tab and back again adds again all the childs to the DOM, which eventually slows down loading of the Switches tab. My thought would be adding a check in LightsController.js:init() to see if it already ran or not.

I'm running v.3.6371 (beta release).

**Comment by gizmocuz** [comment]
Nice find!, Could you propose a patch/pull request to fix this?

**Comment by SilverViper** [comment]
I don't have a development environment set up right now but I'm doing root cause analyzes for the moment first. 

The part that creates and builds up the delay is at line 3947 in the current revision. A for loop that adds 256*13=3328 items to the DOM.

I see you moved that bit lower in this commit (from line 2886 to 2925 in this version): https://github.com/domoticz/domoticz/commit/7390a2c1f2c28df1f22ff5a2353911ac668c94e5#diff-7bd091f9ebe6a5ae834e92e2bfd579ce

You moved it outside $( "#dialog-addmanuallightdevice" ).dialog({}); Any idea why? Moving it back in there prevents it from adding 3328 items to the DOM every sequential switch to the Switches tab. Then it is only run when the "Manual Light/Switch" button is clicked. Could still be a pain if you need to add lots of switches though...

**Comment by gizmocuz** [comment]
I have no idea why... but moving it back is a very good idea ;) Maybe i'm blessed with an to powerfull pc here
I will move it back asap....
Could definitely use some help with the web gui part... specially with AngularJS ... if you could help.. that would be great!
If you find more issues, please report them all ;)

**Comment by gizmocuz** [comment]
Thanks

**Comment by SilverViper** [comment]
Nice fix/rewrite! And quick support I might add as well!

Just updated and the original issue is confirmed to be resolved. Can't test functionality of adding Manual Light/Switch other than the GUI loads OK. One note though, if I go to the Switches tab and back to the Dashboard and back to the Switches tab I do see two (empty) div's being added for the buttons again. So the reuse of the buttons works when you stay in the Switches tab, but when you left it and go back they are generated again and if you click on the Manual Light/Switch button, the latest div gets filled. Is this because you put the HasInitializedAddManualDialog as a property of the scope?

It's unlikely to become a problem though, just mentioning so you know it could be an issue in the future.

I have zero experience with AngularJS unfortunately, but I like finding root causes, so if I can help you with that let me know :)

**Comment by gizmocuz** [comment]
Great find again... have to double check this
I just pushed another commit to make it a bit faster again (custom icon loading, also in the utility tab)
https://github.com/domoticz/domoticz/commit/5dcaede15816d6cdb75d2019b478ea6a8872535a

**Comment by SilverViper** [comment]
Ah right. Going through the tabs it also happens in the Scenes, Temperature, and Weather tabs, adding divs each time they are opened instead of reusing existing ones...

**Comment by gizmocuz** [comment]
Thanks, not sure i understand the problem 100%, could you describe it in a bit more detail ?

**Comment by SilverViper** [comment]
The tabs Scenes, Temperature, and Weather also have buttons, e.g., Forecasts on the Weather tab and some other dialogs hidden by default. These dialogsare recreated each time the tab is opened. Lesser of an issue as their HTML is a lot smaller...
