### ISSUE TITLE
Creating a Selector Switch

### ISSUE THREAD

**Issue by MrTheoW** [domoticz/domoticz#1152]
When following the steps om [https://www.domoticz.com/wiki/Toon](url) i stumble upon the fact i don't see the "Selector Actions" what is displayed in picture 4.
I see the "Niveau" (Level) and "Actie" (Action) header, but right beneath that i see the description field.

As soon as i save the selector (to edit it later) it saves is but when i enter it again, All the Selector levels i have entered are gone, and so is the content of the switch icon. (Can't choose any icon from that point on)

The only way to fix the switch is to delete the virtual switch in Devices and start over just to end up with the same results.
Have tried it with Chrome and Edge.

Version: 3.6437
Build Hash: 3114c77
Compile Date: 2017-01-22 19:17:59

**Comment by MrTheoW** [comment]
Sorry... Was to quick on pressing the Save button.

**Comment by gizmocuz** [comment]
If it possible you can use the forum ?
