### ISSUE TITLE
Database corruption bug

### ISSUE THREAD

**Issue by ben423423n32j14e** [domoticz/domoticz#1153]
Corruption of the Domoticz database occurred by sending the following JSON to a P1 smart meter sensor:
`
curl -s "http://USERNAME:PASSWORD@192.168.0.5/json.htm?type=command&param=udevice&idx=488&svalue=2012.672"
`

Domoticz V3.6395

**Comment by gizmocuz** [comment]
Well you should just set a value to a sensor... 
Probably if you delete this sensor (with an external editor) it is solved again
If you next time create a dummy P1 sensor, then make a backup of the database, and look at the values
Or see the JSon WIKI

**Comment by ben423423n32j14e** [comment]
Yep, I came across it by accident thought I'd "try the P1 Meter" and see what it looked like, the second my script sent the incorrect JSON data it corrupted the DB.

I know the data is incorrect, I just reported it in case you wanted to "catch" errors such as this in the code and prevent them from corrupting the DB.

Cheers

**Comment by gizmocuz** [comment]
It is impossible to catch this for 100+ sensors ... 
I checked the code, it handles a possible crash here... and this causes the record to be send to the web browser to be corrupted (if this is the last sensor)
Just deleting it from the devices tab solved the problem

**Comment by ben423423n32j14e** [comment]
no worries, I just deleted the last device manually from the DB using DB Browser for SQLite and it was back working fine.

Thanks Gizmocuz!
