### ISSUE TITLE
Ability to use more blockly programming statements

### ISSUE THREAD

**Issue by MathijsG** [domoticz/domoticz#1155]
I really like Domoticz and since having my RFLink running I would like to add some more complexity. Using lua for my scripts is on my todo list, but currently I'm exploring the point and click functionality that Blockly provides.

However when I visit https://developers.google.com/blockly/ I see a lot more programming options than the Blockly Domoticz gives. For example a while loop is missing and some of the more advanced logic blocks are also missing.

Is this something which could be added? Would be nice :).

And with the camera functionality I only see the option to e-mail the image, with a very specific block: Maybe an option is to break these specific blocks down into seperate parts?

![image](https://cloud.githubusercontent.com/assets/529552/22210549/851577da-e18a-11e6-94fb-2d4ec665b862.png)

Maybe it's better to break this down into a "Make image" block, so you can easily attach this to other things. Maybe even notifications with this image, instead of e-mails.

**Comment by gizmocuz** [comment]
in domoticz you can only email a camera snapshot, no need to break it down... it's perfect like this, otherwise we had to drag 5 different things right ?

Sure some more functionality like in the latest blockly could be added, could you help with this ?

**Comment by gizmocuz** [comment]
No feedback, closing topic

**Comment by jasperslot** [comment]
I am also looking for this! I am not sure how I can help you gizmocuz? Do you need to know what kind of blocks could/shoud be added? Or someone who is going to code this?
