### ISSUE TITLE
Add the support of the RTSP protocol

### ISSUE THREAD

**Issue by yop190** [domoticz/domoticz#116]
Hi,

Some camera don't support snapshot jpg, but they have only the rtsp protocol.
In this case, if domoticz intergate natively the support of rtsp protocol could be great ;)

Cheers

**Comment by gizmocuz** [comment]
For streaming this could work (via HTML5 it should not be to complicated)
But what if we want a snapshot of the camera attached by email ?
That would be complicated

What camera are you using? I thought all cameras had a snapshot url

**Comment by yop190** [comment]
Hi,

I'm using a dvr (ES-DVR8216D) with 16 analog camera behind and there is not snapshot url available on this device:(
Streaming could be great in first time, and why not after attached snapshot camera by email ;)

Cheers

**Comment by gizmocuz** [comment]
but how would you get/create a snapshort from a streaming camera?

**Comment by yop190** [comment]
Maybe domoticz could do it (convert rtsp to jpg on the fly) or integrate motion in domoticz (http://motion.sourceforge.net/) ?

**Comment by gizmocuz** [comment]
that wont be easy, but if you could make a pull request with the needed changes, that would be great
Please use our forum, we would like to keep this only for developers
