### ISSUE TITLE
Alert sensor notification not working on LUA call

### ISSUE THREAD

**Issue by nmaster2042** [domoticz/domoticz#1163]
Hi

Version: 3.6441
Platform: X86_64

Description: It's same kind of issue than the #1106 I created.
Alert sensor notification is not working when sensor is updated by LUA call.

Here Notification I set on a new alert sensor:

Type: Usage
When: Greater
Value: 3
Priority: Normal
Ignore Intervel: checked
Custom message: leave blank
Active systems: all checked

I click Add.

Alert sensor is updated with nvalue and svalue like this in LUA script

commandArray = {}
local DeviceIDToUpdate = 68
...
...
commandArray['UpdateDevice'] = DeviceIDToUpdate .. "|4|Too Hot !"
...
...
return commandArray

On the domoticz web interface I get updated values from LUA script, but I never get any notification.

I have only mail notification configured in domoticz setup.

**Comment by gerard33** [comment]
Check this post on the forum http://www.domoticz.com/forum/viewtopic.php?f=6&t=14137&p=109681#p102996.

The commandArray['UpdateDevice'] is only updating the device and not firing any triggers.
Try it with the JSON command from #1106. Probably you will receive an notification then.

`/json.htm?type=command&param=udevice&idx=68&nvalue=4&svalue=Too Hot`

**Comment by nmaster2042** [comment]
Hi gerard33, thank you for your comment.

I didn't know about the usability of commandArray['OpenURL']  in LUA script.
I thought it was only avaliable on blockly.

Until now I'm using os.execute with a curl command, witch I find quite dirty.
Your workarround is thus nicer than mine. I'll switch to openUrl as workarround until issue is fixed.

It's not a critical issue but I think the nicest way would be LUA calls triggers notifications the same way as other sensors.

Unfortunately I've not skills to fix it by myself and push it so I post here what I discover wile expanding my home automation system.

**Comment by gizmocuz** [comment]
@nmaster2042 , it is all explained here
https://www.domoticz.com/wiki/Events

**Comment by nmaster2042** [comment]
Thanks gizmocuz.
