### ISSUE TITLE
Cross compile warnings.

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#1164]
Domoticz-v3.6478 cross compile warnings.
I think these warnings came after a change in XiaomiGateway.h
Is this a bug in my compilation environment, or is it a bug in XiaomiGateway.h?

[ 25%] Building CXX object CMakeFiles/domoticz.dir/main/Logger.cpp.o
[ 25%] Building CXX object CMakeFiles/domoticz.dir/main/mainworker.cpp.o
In file included from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/main/../hardware/XiaomiGateway.h:8:0,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/main/mainworker.cpp:111:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/install//usr/local/domoticz/include/openssl/aes.h:63:0: warning: "AES_ENCRYPT" redefined
 # define AES_ENCRYPT     1
 ^
In file included from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/hardware/openzwave/aes/aescpp.h:26:0,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/hardware/openzwave/Driver.h:42,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/main/../hardware/openzwave/control_panel/ozwcp.h:40,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/main/../hardware/OpenZWave.h:11,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/main/mainworker.cpp:34:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/hardware/openzwave/aes/aes.h:45:0: note: this is the location of the previous definition
 #define AES_ENCRYPT /* if support for encryption is needed          */
 ^
In file included from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/main/../hardware/XiaomiGateway.h:8:0,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/main/mainworker.cpp:111:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/install//usr/local/domoticz/include/openssl/aes.h:64:0: warning: "AES_DECRYPT" redefined
 # define AES_DECRYPT     0
 ^
In file included from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/hardware/openzwave/aes/aescpp.h:26:0,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/hardware/openzwave/Driver.h:42,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/main/../hardware/openzwave/control_panel/ozwcp.h:40,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/main/../hardware/OpenZWave.h:11,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/main/mainworker.cpp:34:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.0/domoticz-r6478/hardware/openzwave/aes/aes.h:46:0: note: this is the location of the previous definition
 #define AES_DECRYPT /* if support for decryption is needed          */
 ^
[ 26%] Building CXX object CMakeFiles/domoticz.dir/main/RFXNames.cpp.o

**Comment by gizmocuz** [comment]
Could you make a patch for this ?

**Comment by Jumbotroll** [comment]
This error appeared after
#include <openssl / aes.h>
was added to the line 8 in XiaomiGateway.h
domoticz v3.6231 was ok.
I'll test some :-)

**Comment by gizmocuz** [comment]
Could you check the new commit ? Made a small change, moved the AES header inclusion in the CPP file, and it should now also build when SSL is not supported by the OS

**Comment by gizmocuz** [comment]
@corbinmunce , hope all is still OK ?

**Comment by Jumbotroll** [comment]
Success!
Compiling completed without any warning after recent commits.
Thanks!

**Comment by corbinmunce** [comment]
@gizmocuz, yes still works well on my system

**Comment by gizmocuz** [comment]
Thanks for checking...
