### ISSUE TITLE
Cross Compile failed after pull #1174 with -DUSE_PYTHON_PLUGINS=NO

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#1175]
Compiling with Python all build is ok, but compiling with  -DUSE_PYTHON_PLUGINS=NO it fails.

[100%] Building CXX object CMakeFiles/domoticz.dir/tinyxpath/xpath_static.cpp.o
Linking CXX executable domoticz
CMakeFiles/domoticz.dir/hardware/Kodi.cpp.o: In function `http::server::CWebServer::Cmd_KodiMediaCommand(http::server::_tWebEmSession&, http::server::request const&, Json::Value&)':
Kodi.cpp:(.text+0x577c): undefined reference to `http::server::CWebServer::Cmd_PluginCommand(http::server::_tWebEmSession&, http::server::request const&, Json::Value&)'
collect2: error: ld returned 1 exit status
make[5]: *** [domoticz] Error 1

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/pull/1180

**Comment by Jumbotroll** [comment]
Success!
Tested and all fine after #1180
