### ISSUE TITLE
Device Sharing - Incorrect values

### ISSUE THREAD

**Issue by TimelessNL** [domoticz/domoticz#1182]
Hi, 

I tried device sharing between 2 Domoticz instances. They are both on V3.5877 running on LEDE.
But for some reason the values of the "Motherboard Sensors" and "BMP180" appear incorrect on my Master Domoticz instance. However they are correct on my Slave instance.

I do have a "HTU21D" as well, which is working fine on both my Master and Slave instances.

So I have no idea what could be going wrong. I've attached some pictures to make my situation more clear.

**SLAVE:**
![device sharing - slave](https://cloud.githubusercontent.com/assets/10838968/22408623/659e6064-e67c-11e6-86a5-e9a73a2bdf46.PNG)
**MASTER:**
![device sharing - master](https://cloud.githubusercontent.com/assets/10838968/22408622/65993c92-e67c-11e6-9cbf-f33676abbdc0.PNG)

Regards,
Timeless

**Comment by TimelessNL** [comment]
Mmh.. Found some posts around the web with people having identical issues:

Link [(Dutch)](https://gathering.tweakers.net/forum/list_message/43908004#43908004) / [(English)](https://translate.google.com/translate?sl=nl&tl=en&js=y&prev=_t&hl=nl&ie=UTF-8&u=https%3A%2F%2Fgathering.tweakers.net%2Fforum%2Flist_message%2F43908004%2343908004&edit-text=&act=url)
[Link](https://www.domoticz.com/forum/viewtopic.php?f=6&t=7303#p57048)
[Link (Not entirely the same case though)](https://www.domoticz.com/forum/viewtopic.php?t=13016&start=20#p98914)

So it seems to be a Little/Big endianes issue.
-1st I would like to mention that this should be added to the [Wiki](https://www.domoticz.com/wiki/Setting_up_Device_sharing).
-2nd, are there any plans to support Little/Big endianes conversion, or using an alternative like JSON for master/slave communication?

_I ask this because there are plans to integrate Domoticz (& OpenZwave) in LEDE/OpenWRT. So to share sensors between the platforms Little/Big endianes conversion is a must, this because of the wide range of targets and instruction-sets._

**Comment by gizmocuz** [comment]
That is currently impossible as we send over the complete structure.
otherwise for all structures (100?) we should make a conversion...

**Comment by TimelessNL** [comment]
But converting Little/Big endianes is supported with standard functions in glibc since version 2.9 see [link](https://linux.die.net/man/3/le64toh) and possibly in uClibc as well [link](https://github.com/hwoarang/uClibc/blob/master-metag/include/endian.h).

It's not just a problem I'm experiencing. There are also people that want to share devices between the Raspberry and a NAS/Linux machine for example which has the same issue.

**Comment by gizmocuz** [comment]
Do you have any idea how much work it is to convert back/forward structures ?
Take a look at the rfxtrx.h header file for example... there are many more internally

**Comment by TimelessNL** [comment]
I'm just offering a possible solution here.
But no I do not know how much work it is, since I can study all of the code in just 1 hour after finding a possible cause.

**Comment by gizmocuz** [comment]
yep, but data received from real hardware has the order of the hardware... and that needs to be translated for the other side
Let me put it this way, buying 2 raspberry pi's is cheaper

**Comment by TimelessNL** [comment]
_Not that I want to be rude or anything, but this is exactly whats wrong with the Raspberry community.
Like "if it works don't fix it" or "just buy another raspberry will fix your problems".
Just like people using WiringPi instead of a more common approach of sysfs._

But enough about that...

When data is transmitted over a network it will aways be "Big Endian" see: [Link](https://en.wikipedia.org/wiki/Endianness)

> Big-endian is the most common format in data networking; fields in the protocols of the Internet protocol suite, such as IPv4, IPv6, TCP, and UDP, are transmitted in big-endian order.

The data has to be converted anyway. So when the conversion is done right there should be no issue between the Sender and Receiver because they are both speaking in Big Endianness. The Local system has to convert it to their desired endianness after receiving it from the network stack.

But if there is no need for a fix, then just say so and add it to the Wiki. I just noticed the issue and pin-pointed it to an endianness problem.

**Comment by gizmocuz** [comment]
Okey, then please... create a pull request that transforms 'every' structure then is send and received (from slave <> master) to JSon
This JSon we can gzip and transfer/unpack

**Comment by gizmocuz** [comment]
And yes... i voted now 100+ for sysfs ! also on the forum, nobody wants to implement it...

**Comment by TimelessNL** [comment]
I think converting it to JSON is not really necessary, right now all TCP/UDP communication is done in Little (or big, depends on platform) endianness and there is no conversion at either side of the TCP/UDP connection. So that's why it works most of the time. Even while it is not the official standard.

Currently I'm working on a Domoticz I2C bug, but when that one is fixed and I have some spare time I could investigate this issue further.

For now I wanted to mention/pin-point this issue. So when people see identical cases they can refer to my issue report. Or fix it if they so desire. Because I don't think the issue-er always has to fix the problem he/she reports, maybe people reading these issue reports can also help finding a solution.

Is it possible to mention this issue in the [Wiki](http://www.domoticz.com/wiki/Setting_up_Device_sharing), and refer to this bug report? Because Domoticz also seems to support Synology NAS devices which some are also Big endianness and so the problem also exists there.

**Comment by TimelessNL** [comment]
> And yes... i voted now 100+ for sysfs ! also on the forum, nobody wants to implement it...

Maybe its wise to make some sort of a wish/future list. So if some one wants to contribute to the project he/she can add that support. Currently most people are adding stuff they personally need without any kind of maintainer support later on. So it's more like drop it here and never see it again.

**Example:**
Because I'm searching for the I2C issue I also spotted this: ([I2C.cpp line 155](https://github.com/domoticz/domoticz/blob/master/hardware/I2C.cpp)):
> 	//Giz: Could the author of this function please check his/her spelling!

Which seems kinda odd in my opinion? How did this even come into the source code in the first place?

**Comment by gizmocuz** [comment]
The comment is mine... The English from the author with these changes is really bad
And indeed... i also mentioned to him how i would have it done... thats why i rebuilded it partly again
Anyway, yes, please mention it in a wiki that the communication between master/slave should have the same architecture, and you also found when you searched the forum.

**Comment by TimelessNL** [comment]
Why is this issue closed?

The issue still stands and there is no fix for it yet? Just because we discussed it does not mean that the case is closed and magicaly fixed?

**Comment by gizmocuz** [comment]
Because this issue is trashed now
Please create a new issue, and please mind your attitude dear friend!

**Comment by TimelessNL** [comment]
Sorry. I don't see a problem with my current attitude. I just react in a way I feel treated right now.

**Comment by gizmocuz** [comment]
Okey morron, playtime is over!

**Comment by gizmocuz** [comment]
This is caused by a mismatch in processor architectures, and specifically little/big endianness differences

**Comment by hansij66** [comment]
Will this issue be fixed/planned to be fixed? I have a master on an x86 architecture and would like to have a raspberry slave.

**Comment by TimelessNL** [comment]
You probably won't see this issue. The Raspberry Pi's ARM processor defaults to Little Endian which is also which a x86 processor is running at.

I had this problem because I was running a Little Endian master with a Big Endian slave. I don't know what the status of this issue is, but it probably wont matter to your case.

**Comment by gizmocuz** [comment]
Fastest to buy another rpi. But yes the communication should be rewritten in json

**Comment by TimelessNL** [comment]
Correct me if I'm wrong. But a Raspberry and x86 based system will be just fine together? They are both Little Endian. So another raspberry won't be necessary I suppose.

**Comment by mvhconsult** [comment]
@TimelessNL A Synology NAS and Raspberry Pi2 did not work together unfortunately. Not sure what your setup will be, but if you want to be safe: use similar hardware.

**Comment by TimelessNL** [comment]
Synology used a range of processor architectures in their NAS products. So it also depends on which model you tested your setup on.

And yes, similar hardware is most of the times better.

**Comment by hansij66** [comment]
It worked for me x86/x64 as master and Raspberry a client. Master & Client Domoticz version were not the same (but reasonably close together)

**Comment by mvhconsult** [comment]
I have a DS916+ and a Raspberry Pi2. No luck, although I haven't tested recently.

**Comment by TimelessNL** [comment]
Mmh strange. The DS916+ has an x86/64 processor. So it should have worked.

But I think we all verified that there is an issue in some cases. So I don't think it will help much discussing which configurations work and which do not.

**Comment by gizmocuz** [comment]
This is probably a know issue and has to do with little/big endian

**Comment by poudenes** [comment]
EDIT: Accepting new devices was disabled. But Custom Sensors i still not see in Master

Im having 2 Raspberry Pi 3 with both V3.9052 Beta on. Everything what i do i cant get any devices from slave to master. All settings are correct reading the link

"https://www.domoticz.com/wiki/Setting_up_Device_sharing"
