### ISSUE TITLE
P1 meter - add ability to set monthly price

### ISSUE THREAD

**Issue by samm-git** [domoticz/domoticz#1183]
Hi, i built my own IR sensor module and communicating using it with my Energy Meter. It gives me ability to read T1/T2 usage which i am later importing to the Domoticz. Also i calculated summary cost for the T1/T2 energer per KWatt and it gives me ability to predict expenses.

However my energy supplier also charging fixed monthly fee for the services, so to get accurate prediction i have to count it as well. What do you think, does it make a sense to add setting for this to the "Meter/Counter Setup" settings tab? Later this can be used in the reports, by adding to montly and daily (fee/num_of_days_in month * current_day) reports. If its sounds reasonable i start working on PR, because i believe that such payment scheme (fixed + per kw) is very common.

**Comment by gizmocuz** [comment]
I think at the end of the year you have to add 12 x (some $) ?

**Comment by samm-git** [comment]
Exactly. Or in the end of the month in some countries (e.g. in Ukraine)

**Comment by gizmocuz** [comment]
Then i suggest to do this by hand, otherwise there will be a lot of codework involved

**Comment by samm-git** [comment]
Ok, np. I am closing this issue.
