### ISSUE TITLE
Nefit Easy Pressure stays 25.5bar

### ISSUE THREAD

**Issue by yvelk** [domoticz/domoticz#1184]
Nefit Easy server v3.1.0
Domoticz v3,5877

The pressure of the central heating says and stays on 25.5bar. I cannot fix this, or don't know how.

Regards,
Yves

**Comment by gizmocuz** [comment]
Please use our forum

**Comment by gizmocuz** [comment]
If you do, i can also send you a PM

**Comment by yvelk** [comment]
Hi Gizmocuz,


What forum? Robert said I should have posted it on github.


Yves.


________________________________
Van: gizmocuz <notifications@github.com>
Verzonden: maandag 30 januari 2017 16:02
Aan: domoticz/domoticz
CC: yvelk; Author
Onderwerp: Re: [domoticz/domoticz] Nefit Easy Pressure stays 25.5bar (#1184)


If you do, i can also send you a PM

-

**Comment by gizmocuz** [comment]
https://www.domoticz.com/forum

**Comment by yvelk** [comment]
http://www.domoticz.com/forum/viewtopic.php?f=34&t=15808


Yves.


________________________________
Van: gizmocuz <notifications@github.com>
Verzonden: maandag 30 januari 2017 16:06
Aan: domoticz/domoticz
CC: yvelk; Author
Onderwerp: Re: [domoticz/domoticz] Nefit Easy Pressure stays 25.5bar (#1184)


https://www.domoticz.com/forum

Domoticz - Index page<https://www.domoticz.com/forum>
www.domoticz.com
Who is online. In total there are 102 users online :: 13 registered, 2 hidden and 87 guests (based on users active over the past 5 minutes) Most users ever online was ...



-
