### ISSUE TITLE
Not working - I2C sensors on x86 Linux

### ISSUE THREAD

**Issue by TimelessNL** [domoticz/domoticz#1188]
Hi,

I'm trying to get I2C working on a [PC Engines Alix](https://pcengines.ch/alix6f2.htm), which is a x86 platform. Since commit [68ec8e03802a1c5a098b63d57b2aa022f2f41ff2](https://github.com/domoticz/domoticz/commit/68ec8e03802a1c5a098b63d57b2aa022f2f41ff2) this should be possible for any linux platform using /dev/i2c-X. Just like I successfully tested with a MIPS24kc instruction-set [here (defined __ arm __ but is practically thesame](https://www.domoticz.com/forum/viewtopic.php?f=17&t=15396)

The sensors got detected:
_(used: [CJMCU HTU21D BMP180 BH1750FVI Temperature Humidity Barometer Light Brightness Sensor](https://nl.aliexpress.com/store/product/CJMCU-HTU21D-BMP180-BH1750FVI-Temperature-Humidity-Barometer-Light-Brightness-Sensor/206605_32378884566.html?detailNewVersion=&categoryId=200001407))_
```
root@lede:~# i2cdetect 0
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will probe file /dev/i2c-0.
I will probe address range 0x03-0x77.
Continue? [Y/n] y
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- 23 -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- 77
```

But in Domoticz it does not seem to work:
```
2017-02-01 12:19:46.974 I2C_BMP085/180: Worker started...
2017-02-01 12:19:52.044 I2C_HTU21D: Worker started...
2017-02-01 12:20:18.032 Error: I2C_BMP085/180: Error reading sensor data!...
2017-02-01 12:20:23.046 Error: I2C_HTU21D: Error writing I2C!...
2017-02-01 12:20:23.046 Error: I2C_HTU21D: Error reading temperature!... 
```

Which I find odd because running a  python script _(see below - Python code:)_ worked fine:
```
root@lede:~# python bmp180sensor.py
Temperatuur :  23.7 ° C
Luchtdruk    :  1012.56 mbar
```
2nd test:
```
root@lede:~# python bmp180sensor.py
Temperatuur :  23.9 ° C
Luchtdruk    :  1012.29 mbar
```
So my BMP180/wiring/i2c-port/target/OS are working fine.

In my previous working Domoticz test with a [GL.Inet 6416(MIPS24kc)](https://wiki.openwrt.org/toh/gl-inet/gl-inet_64xx) I used a [i2c-gpio](https://wiki.openwrt.org/doc/hardware/port.i2c) _(just like the Raspberry Pi has)_ implementation because there was no hardware i2c-port available. But the PC Engines ALIX has a hardware i2c directly from the AMD Geode processor so maybe the i2c port is to fast? Unfortunately the PC Engines ALIX has no easy accessible GPIO's _(or I have to de-solder the LEDs )_ so I cannot test my theory.

I used Domoticz Stable 5877 for both the ALIX and GL.Inet. The GL.Inet worked fine after manually adding the __ arm __ define but the ALIX did not. I also tested today's HEAD for the ALIX so including the previous mentioned commit, but that did not help either.

**Python code:**
```
#!/usr/bin/python

# BMP180 luchtdruk + temperatuur sensor
# https://raspberrytips.nl/bmp180/
# Gebaseerd op een script gemaakt door Matt Hawkins

import smbus
import time
from ctypes import c_short

DEVICE = 0x77

bus = smbus.SMBus(0)

def convertToString(data):
  return str((data[1] + (256 * data[0])) / 1.2)

def getShort(data, index):
  return c_short((data[index] << 8) + data[index + 1]).value

def getUshort(data, index):
  return (data[index] << 8) + data[index + 1]

def readBmp180(addr=DEVICE):
  REG_CALIB  = 0xAA
  REG_MEAS   = 0xF4
  REG_MSB    = 0xF6
  REG_LSB    = 0xF7
  CRV_TEMP   = 0x2E
  CRV_PRES   = 0x34
  OVERSAMPLE = 3

  cal = bus.read_i2c_block_data(addr, REG_CALIB, 22)

  AC1 = getShort(cal, 0)
  AC2 = getShort(cal, 2)
  AC3 = getShort(cal, 4)
  AC4 = getUshort(cal, 6)
  AC5 = getUshort(cal, 8)
  AC6 = getUshort(cal, 10)
  B1  = getShort(cal, 12)
  B2  = getShort(cal, 14)
  MB  = getShort(cal, 16)
  MC  = getShort(cal, 18)
  MD  = getShort(cal, 20)

  # Lees Temperatuur
  bus.write_byte_data(addr, REG_MEAS, CRV_TEMP)
  time.sleep(0.005)
  (msb, lsb) = bus.read_i2c_block_data(addr, REG_MSB, 2)
  UT = (msb << 8) + lsb

  # Lees Luchtdruk
  bus.write_byte_data(addr, REG_MEAS, CRV_PRES + (OVERSAMPLE << 6))
  time.sleep(0.04)
  (msb, lsb, xsb) = bus.read_i2c_block_data(addr, REG_MSB, 3)
  UP = ((msb << 16) + (lsb << 8) + xsb) >> (8 - OVERSAMPLE)

  # Opmaak temperatuur
  X1 = ((UT - AC6) * AC5) >> 15
  X2 = (MC << 11) / (X1 + MD)
  B5 = X1 + X2
  temperature = (B5 + 8) >> 4

  # Opmaak luchtdruk
  B6  = B5 - 4000
  B62 = B6 * B6 >> 12
  X1  = (B2 * B62) >> 11
  X2  = AC2 * B6 >> 11
  X3  = X1 + X2
  B3  = (((AC1 * 4 + X3) << OVERSAMPLE) + 2) >> 2

  X1 = AC3 * B6 >> 13
  X2 = (B1 * B62) >> 16
  X3 = ((X1 + X2) + 2) >> 2
  B4 = (AC4 * (X3 + 32768)) >> 15
  B7 = (UP - B3) * (50000 >> OVERSAMPLE)

  P = (B7 * 2) / B4

  X1 = (P >> 8) * (P >> 8)
  X1 = (X1 * 3038) >> 16
  X2 = (-7357 * P) >> 16
  pressure = P + ((X1 + X2 + 3791) >> 4)

  return (temperature/10.0,pressure/ 100.0)

def main():

  deg = u'\xb0'
  (temperature,pressure)=readBmp180()
  print "Temperatuur : ", temperature,deg.encode('utf8'), "C"
  print "Luchtdruk    : ", pressure, "mbar"

if __name__=="__main__":
   main()
```

**Comment by gizmocuz** [comment]
Best to debug the code then.... could you do this ?

**Comment by TimelessNL** [comment]
I'm currently working on that. My start post is specificly written with LEDE(OpenWRT fork) in mind so maybe there are just some i2c deps missing.

I'm currently building Domoticz for Voyage which is a debian based OS specifically for Alix boards and such. So if that does not work the problem must be in our Domoticz i2c library. From there I can start debugging.

It would be nice to know if some one could reproduce my situation though. Best on another x86 platform so I know that there are really no hardware defects in my Alix board.

**Comment by TimelessNL** [comment]
**UPDATE:**
I just tested Domoticz V3.6571 on [Voyage Linux](http://linux.voyage.hk/) and this is the result:
```
2017-02-02 12:49:41.786 Domoticz V3.6571 (c)2012-2017 GizMoCuz
2017-02-02 12:49:41.787 Build Hash: 3f3ce6f, Date: 2017-01-01 18:15:35
2017-02-02 12:49:41.789 Startup Path: /root/domoticz/
2017-02-02 12:49:42.183 PluginSystem: Started, Python version '3.4.2'.
2017-02-02 12:49:42.203 Active notification Subsystems: http (1/12)
2017-02-02 12:49:42.207 WebServer(HTTP) started on address: :: with port 8080
2017-02-02 12:49:42.223 WebServer(SSL) started on address: :: with port 443
2017-02-02 12:49:42.227 Proxymanager started.
2017-02-02 12:49:42.231 Starting shared server on: :::6144
2017-02-02 12:49:42.236 RxQueue: queue worker started...
2017-02-02 12:49:42.237 TCPServer: shared server started...
2017-02-02 12:49:44.242 EventSystem: reset all events...
2017-02-02 12:49:44.244 EventSystem: reset all device statuses...
2017-02-02 12:49:44.246 I2C_BMP085/180: Worker started...
2017-02-02 12:49:44.247 EventSystem: Started
2017-02-02 12:49:44.397 PluginSystem: Entering work loop.
2017-02-02 12:50:14.575 Error: I2C_BMP085/180: Error reading sensor data!... 
```
So unfortunately this did not do the trick. :(

**Comment by samm-git** [comment]
I can take a look on that if you can provide ssh to the linux hw with i2c and this sensor.

**Comment by TimelessNL** [comment]
SSH access would be difficult, since I'm behind a NAT connection. Teamviewer would be an option. But maybe it's best to move this conversation to my [Domoticz Topic](https://www.domoticz.com/forum/viewtopic.php?f=17&t=15396&p=118600) so this issue report stays clean and orderly.

**Comment by gizmocuz** [comment]
Is this still open ?

**Comment by TimelessNL** [comment]
Unfortunately I'm still waiting for my USB-I2C stick to arrive. This will make it easier for me to debug this issue.

But I think you can close this issue for now. I'll continue on my forum post as requested.

Thanks

**Comment by gizmocuz** [comment]
Okey, thanks for your effort !
I got myself a 	'Bus Pirate' (V4)
