### ISSUE TITLE
MySensors: add possibility to combine measurements of sensors

### ISSUE THREAD

**Issue by GertSanders** [domoticz/domoticz#119]
Sometimes a sensor-node with multiple sensors, fails to send all measurement data in 1 go. E.g. a temperature and humidity node (SI7021 based) sends both Temp and Hum values, but sometimes only the Temp or only the Hum value gets through to Domoticz.

In those cases the node is seen as a new node with same ID but different IDX. In my case the same node has three IDX values (26,27 and 28).

26  MySensors Gateway   0401    0   TempHum Temp + Humidity WTGR800 21.3 C, 53 %

27  MySensors Gateway   0401    1   TempHum Temp    LaCrosse TX3    21.1 C

28  MySensors Gateway   0402    1   TempHum Humidity    LaCrosse TX3    Humidity 47 %

In the above list the three "devices" are actually the same node.

This is a request to be able to combine the two devices with same ID so that data is merged again.

Maybe best to be able to change ("combine") nodes in the devices overview with the option to merge their data (merging mayby not always required of opportune, so this should be an optional action).

**Comment by gizmocuz** [comment]
This should not be the case.
If a Temp AND Humidity has been received, this should always been interpreted as temp+Hum sensor, if only humidity is send, it should update the Temp+Hum sensor, same if only temp is received

But why you have 'fail to send' ?

**Comment by GertSanders** [comment]
I send the measurements in separate messages and some do not get acknowledged by the gateway. As a result I think they are not received by the controller.
Maybe the sensor had such a problem on first presentation, and then the controller sees only 1 measurement presented. Could this cause multiple definitions?

**Comment by GertSanders** [comment]
I send the measurements in separate messages and some do not get acknowledged by the gateway. As a result I think they are not received by the controller.
Maybe the sensor had such a problem on first presentation, and then the controller sees only 1 measurement presented. Could this cause multiple definitions?

**Comment by GertSanders** [comment]
Why failed messages, maybe because of all the different 2.4ghz networks around my house (14 on last count).

**Comment by gizmocuz** [comment]
mysensors uses a different channel....
