### ISSUE TITLE
Philips Hue White group shows as RGBW

### ISSUE THREAD

**Issue by gielie** [domoticz/domoticz#1202]
#887 

problem still there, running latest beta.

Individual white light bulbs are correct but the group shows as rgbw.

Any idea how to solve this.

**Comment by gizmocuz** [comment]
Probably with a code patch

Do the groups work ?

**Comment by gielie** [comment]
Yes, groups works fine, but they are also shown as rgbw while the bulps are white ambiance

**Comment by gizmocuz** [comment]
If you edit the group... can you set the type to 'Push On' ? Does it still work then ?

**Comment by gizmocuz** [comment]
Maybe best to send me a PM on the forum, so i can ask you for some debug output

**Comment by gielie** [comment]
Any news on this topic?

**Comment by jjnj023** [comment]
If there is any need for testing i can help.

**Comment by mattijsf** [comment]
I'm running V3.8276 and I still can't get the Hue groups with Hue Ambiance lights to work as a proper dimmer. It always recognizes the group as RGBW while a single light bulb from the group get a proper dimmers slider. The group is newly created and added after I updated to 3.8276.

The group only contains Hue Ambiance lights. I would expect it was possible to add the group and get the same slider / dim functionality as I would have when controlling the single light bulb.

![screen shot 2017-08-12 at 13 58 27](https://user-images.githubusercontent.com/706368/29240469-62582cea-7f66-11e7-91d1-d670c312e802.png)

While dimming works with the popup the UI is much less convenient when using the dashboard to control lights.

**Comment by gizmocuz** [comment]
If you "Still" can not get it to work, maybe you should do a little more work and submit a patch ?

**Comment by Nenodema** [comment]
Are there any updates on this bug/feature? My "older" hue color lights are also recognized as RGBW and not as AC.

I have 6 lights, 2 new ones (hue white Ambiance) and 4 color lights. The new ones are created with AC and dimmable but the older ones are recognized as RGBW lights.

![image](https://user-images.githubusercontent.com/33698556/33657736-7c590ee2-da7a-11e7-8650-fbfc76e96c82.png)
