### ISSUE TITLE
BME280 i2c adress

### ISSUE THREAD

**Issue by TychoHae** [domoticz/domoticz#1203]
I tried to use the new i2c option for the BME280 and got the error message

Error Writing to I2C register.

searching online for the error I gave me the source code at

https://github.com/domoticz/domoticz/blob/master/hardware/I2C.cpp

There i noticed that the i2c address of the BME280 was set to

#define BMEx8x_I2CADDR	0x76

where my adafruit bme280 connected to raspberry pi has i2c address 0x77

by changing 0x76 to 0x77 and recompiling the code i got it working.

Since there seem to be bme280 with either i2c address 0x76 or 0x77 some error handling to chose the right one will be useful.

I think it is were nice that the bme280 is included at all by now, by the way

(version 3.6595)

**Comment by gizmocuz** [comment]
Thanks for the positive feedback
Yes, i see in the official adafruit library that this is set to 0x77 (i suspect you use an adafruit board)

#define BME280_ADDRESS                (0x77)

If we use the I2C bus the sensor can use one of two addresses to communicate with. The default is 0x77. The address is set by the voltage applied to the SDO pin. The Adafruit board has a pullup resistor on the breakout board which will pull the pin high and set the default address to 0x77. The alternative is pull the pin to ground and this will set the address to 0x76.

The reason for this is that the BMPx8x I2C address is already 0x77

**Comment by TychoHae** [comment]
Thank you for pointing out how to set the Adafruit board to 0x76 , did this and now the BME280 is working fine with the official (beta) build. Saves me the trouble of recompiling my personal fix every upgrade

**Comment by bdwilton** [comment]
the sparkfun BME280 uses a solder link to change address from 0x76 (default) to 0x77.  Would be nice to potentially have address selection through the UI for this.  Could have an address field where its entered or in the existing selection have two entries for the BME280 one for the 0x76 and 0x77 addresses
