### ISSUE TITLE
text sensor disappeared

### ISSUE THREAD

**Issue by blindlight86** [domoticz/domoticz#1204]
version: 3.6605
platform: raspberry pi3

I try to use some HTML tags such as <a>, <br>, <iframe> in a dummy text sensor. This's an example:
`position = country, city, street, building`
`position_text = '<a style="color:black" target="blank" href="http://api.map.baidu.com/marker?title='..user..'&content=here&output=html&location='..lat..','..lon..'">'..position..'('..fixedtime..')</a><br>powerstatus:' .. powerstatus.. '</br>'`
Putting position_text in the text sensor will create a link to show a pin (lat ,lon) in the map.

But if the text gets too long, the sensor will disappear from "Utility" and "Devices" page. Looks like it is deleted. 
Actually, it's not. If I use JSON and its idx to check the status, it's still there, but the Data is missing. 
And I manually shorten the text. When it gets short enough, it'll appear again, magically. 
In the forum, other people seem have same [problem.](http://www.domoticz.com/forum/viewtopic.php?t=13318&start=100#p107716)

**Comment by gizmocuz** [comment]
Please use the forum!
