### ISSUE TITLE
Data device property not complete for MiLight/AppLamp

### ISSUE THREAD

**Issue by jeroenvanpelt** [domoticz/domoticz#1205]
Using Domoticz beta 3.6608.

When calling http://<IP>:8080/json.htm?type=devices the 'Data' property of a MiLight/AppLamp dimmer differs from the same property of a KlikAanKlikUit dimmer in that is does not include the dim level. The dim level is included in the 'Status' property of the MiLight/AppLamp dimmer device.

See below for the contents for a MiLight/AppLamp dimmer and for a KAKU dimmer:

{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         **"Data" : "Set Level",**
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 23,
         "HardwareName" : "RFLink Gateway",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "0000F102",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-02-04 17:21:21",
         "Level" : 15,
         "LevelInt" : 15,
         "MaxDimLevel" : 100,
         "Name" : "TV Light (R)",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         **"Status" : "Set Level: 15 %",**
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBW",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Lighting Limitless/Applamp",
         "TypeImg" : "dimmer",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "388"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         **"Data" : "Set Level: 13 %",**
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 7,
         "HardwareName" : "LAN RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "08B4682",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-02-04 17:21:20",
         "Level" : 13,
         "LevelInt" : 2,
         "MaxDimLevel" : 15,
         "Name" : "Kitchen Counter Light",
         "Notifications" : "false",
         "PlanID" : "6",
         "PlanIDs" : [ 6 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         **"Status" : "Set Level: 13 %",**
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "dimmer",
         "Unit" : 12,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "32"
      },

**Comment by gizmocuz** [comment]
This is not stored

**Comment by jeroenvanpelt** [comment]
Oke, can't see why though.

**Comment by gizmocuz** [comment]
I think you will have to look in the code for this
