### ISSUE TITLE
Recent beta update (Feb 2017) lost z-wave device settings

### ISSUE THREAD

**Issue by getSurreal** [domoticz/domoticz#1215]
Not sure which update did it.  I've upgraded a few times in the last couple of weeks.  In the z-wave device management, all the node names went back to unknown and set the polling to 'no'.  In addition the schlage lock is no longer identified with a description or manufacturer and does not show any configuration settings.  It is nice though that switching to a "Door Lock" instead of a "Door Contact" now correctly shows the lock status.

Version: 3.6653
Build Hash: 0c6cf81
Compile Date: 2017-02-08 08:50:16

**Comment by gizmocuz** [comment]
Nothing changes related to the manufacturer display... very strage

**Comment by TimelessNL** [comment]
This is because the OpenZwave cache is refreshed/deleted. Don't know why this happens though.

**Comment by getSurreal** [comment]
I've been updating beta releases fairly frequently and it was not happening in mid January.  Maybe it's already fixed though, because I just did another update and it did not reset the polling back to no.  Side note, the IDs don't seem to match what's listed in devices.  How do I match them back up to rename them from unknown?

**Comment by getSurreal** [comment]
Removing the z-wave node and re-adding it restored the manufacturer information.
