### ISSUE TITLE
SMTP Email Fails

### ISSUE THREAD

**Issue by getSurreal** [domoticz/domoticz#122]
Test button gives the following error 

```
 Problem sending notification, please check the api key
```

I don't have any of the notification services requiring an API key setup.  I'm just want to use smtp.

Debug logs don't provide any additional information.

```
 Error: Notification sent (email) => Failed
```

**Comment by gizmocuz** [comment]
the error popup message will be corrected in the next release.
but i think your email settings are incorrect, please use our forum for help
