### ISSUE TITLE
SBFspot import data - BUG

### ISSUE THREAD

**Issue by novorum** [domoticz/domoticz#1222]
Importing old data from SBFspot gives false data. The values are to high, a factor 100.
Explanation:
SBFspot values in .csv files are stored in Wh. To convert them to kWh a multiplication of 1000 is needed instead of 100000.
BUG is located at hardware/SBFspot.cpp on lines 319 & 358.
Changing:
double kWhCounter = atof(szKwhCounter.c_str()) * 100000;
To:
double kWhCounter = atof(szKwhCounter.c_str()) * 1000;

Changing and compiling these values worked for me.

**Comment by gizmocuz** [comment]
please create a git pull request

**Comment by novorum** [comment]
Unable to publish changes
Created a new branch > made change > new commit > sync failed due to permission issues

**Comment by gizmocuz** [comment]
You do not need to Sync, but create a 'Pull Request', if you browse to your repository (you forked our project to your repo right?), then you should see a green button 'Create Pull Request'
