### ISSUE TITLE
Blinds timer

### ISSUE THREAD

**Issue by morilm** [domoticz/domoticz#1223]
Trying to revisit Blinds timer #837 
Hi.

I think it will be very useful to have the stop and timer on the blinds. This will allow to open/close them for 5-10 secs instead off full open/close status.

Even the best solution, but complex would be to set the % to time duration (on while 10 sec and them stop).

I know newer devices (Fibaro) can set the %, but the old ones doesn't, so a On - Stop command is needed to stop the blinds half open (or Off - Stop)

Thansk
Miguel

**Comment by PHIL-IP** [comment]
> I think it will be very useful to have the stop and timer on the blinds. This will allow to open/close them for 5-10 secs instead off full open/close status.

Yes I think that it's really useful

**Comment by gizmocuz** [comment]
Yes this could be helpful... but how...
In a scene/group you can already do this...
Maybe an option to long-press the open/stop/close, it will show a popup, and here you can click on 5 different positions..
open
1/3 open
1/2 open
2/3 closed
closed

Only possible when the blinds are full open/closed, otherwise you would never know

It needs some settings/per blind as well...

Not an easy task i suppose...

**Comment by PHIL-IP** [comment]
Hi,
perhaps just adding "Delay On" and "Delay Off" like in the On/OFF type :)
... and let the user do what he want with that

**Comment by gizmocuz** [comment]
That does not give the 5 options

**Comment by PHIL-IP** [comment]
Yes I know, but I think it's more simple to do :)

**Comment by gmaslowski** [comment]
@PHIL-IP what blinds (manufacturer and model) are we talking about?

**Comment by PHIL-IP** [comment]
@gmaslowski Any brand or model.

**Comment by gmaslowski** [comment]
@PHIL-IP did you thought of a virtual device with possibility to set percentage? Such virtual device could control via lua script other devices (actual blinds). You could add logic of recalculating percentage into time there.

**Comment by PHIL-IP** [comment]
@gmaslowski No just the same Blinds device but with a field to set time (in seconds).

i.e the device send the "close" command, wait x seconds and send a "stop" command.
I know that some brand or model don't have stop so it's possible to put a checkbox to select if the device must send a stop command or the same command to stop the blind.

I'm not sure that I'm clear :)

**Comment by gmaslowski** [comment]
@PHIL-IP yes, you're clear and I think I understand your problem so I'm trying to help. The lua script approach (supported in domoticz) gives you the same possibility you desribed. Try it out.

**Comment by PHIL-IP** [comment]
Thanks :)
I know that it's can be done using script but it's a better way if that is native in Domoticz ;)

**Comment by inzuno** [comment]
Hi

I need the stop function too! I really miss it because I don't know lua scripts...
I was thinking of a field with the total duration of opening or closing so after you can set a percentage, or you can set a duration of manually opening or closing in seconds.

Thanks!

**Comment by waltervl** [comment]
This old issue can be closed because it is implemented with Blinds percentage and percentage can be set with timers.
