### ISSUE TITLE
Door Lock Issue not visible on Android phone

### ISSUE THREAD

**Issue by Jan1050** [domoticz/domoticz#1224]
### Door Lock Issue not visible on Android phone (Samsung Galaxy S7 Edge)
Beta Version: 3.6694

If I use/change to the "_**Door Lock**_" Icon, then this is not visible on the Android Phone under Dashboard or Room. 

Other question, is it possible to make an "Door Lock" inverted option, the same option as "Blind" and "Blind Inverted"?

**Comment by gizmocuz** [comment]
Could you show some screenshots ? Is it with the android application ?

**Comment by gizmocuz** [comment]
No feedback ,closing issu....

**Comment by jrich523** [comment]
Sorry didnt see this before. here are the screen caps. i set a door to "door lock" and "door contact" only contact shows up in the android app.
![website](https://cloud.githubusercontent.com/assets/2077508/24580032/e3862b24-16b5-11e7-82d2-ba2dfc93067c.png)
![app](https://cloud.githubusercontent.com/assets/2077508/24580035/e7d9fd04-16b5-11e7-94b1-6bc72f31d0a3.png)
