### ISSUE TITLE
Updating dummy switch via json now triggers on/off actions

### ISSUE THREAD

**Issue by jcox10** [domoticz/domoticz#1227]
v3.0.6694-7, build hash 81e71ee, 2017-2-11, on Synology DS214play

After updating to 6694-7, updating dummy switch status via json is now triggering the on/off actions of the device, which causes looping.  Previous versions did not behave this way (not sure the exact version I was running before, but it was installed around Feb 1)

I am updating the status like this:
`/json.htm?type=command&param=udevice&idx=16&nvalue=0` 

Domoticz receives the update, then starts triggering the on/off actions as shown in the logs.  I have a problem with my device not returning a valid HTTP response, so that's why it says error opening url.  But this shows that the on/off actions are being triggered.

2017-02-12 18:16:14.407 Incoming connection from: 192.168.79.115
2017-02-12 18:16:14.417 (Dummy) Light/Switch (Outlet)
2017-02-12 18:16:14.402 Error: Error opening url: http://192.168.79.115/OFF
2017-02-12 18:16:14.417 (Dummy) Light/Switch (Outlet)
2017-02-12 18:16:14.424 Error: Error opening url: http://192.168.79.115/OFF
2017-02-12 18:16:14.436 (Dummy) Light/Switch (Outlet)
2017-02-12 18:16:14.443 Error: Error opening url: http://192.168.79.115/OFF
2017-02-12 18:16:14.461 (Dummy) Light/Switch (Outlet)
2017-02-12 18:16:14.466 Error: Error opening url: http://192.168.79.115/OFF
2017-02-12 18:16:14.475 (Dummy) Light/Switch (Outlet)
2017-02-12 18:16:14.481 Error: Error opening url: http://192.168.79.115/ON
2017-02-12 18:16:14.491 (Dummy) Light/Switch (Outlet)
2017-02-12 18:16:14.714 (Dummy) Light/Switch (Outlet)
2017-02-12 18:16:14.731 Error: Error opening url: http://192.168.79.115/ON
2017-02-12 18:16:14.736 Error: Error opening url: http://192.168.79.115/OFF
2017-02-12 18:16:14.749 (Dummy) Light/Switch (Outlet)
2017-02-12 18:16:14.758 Error: Error opening url: http://192.168.79.115/OFF

**Comment by gizmocuz** [comment]
I think this is desired by most users ?
It also triggers the event system (lua/python/blockly)

**Comment by jcox10** [comment]
Odd that it was working without triggering for a few months now. That's why I thought something was introduced into the code just recently.

I do see that most users would probably want the triggering behavior, to react to the on/off event.  Maybe I just need to go to 2 dummy devices, one to show status, and one to initiate the on/off.

**Comment by jcox10** [comment]
Looks like this is the change that modified the behavior: https://github.com/domoticz/domoticz/commit/e0b3973cef2a9249b544e81f860eb723d085956b

**Comment by odelma** [comment]
Hi, for "normal" dummy switches udevice json command still seems to work like "UpdateDevice", i.e. does not trigger the event system (at least this is true for my current setup running version: 3.6692). But for selector switch, the behavior has changed. I understand the need to trigger event system for sensor updates, but for switches (like the selector switch), I though the reason we have both "switchcmd" and "udevice" json methods is that we can also use the "UpdateDevice" when we just want to change the status and not trigger the event system...?

**Comment by gizmocuz** [comment]
Yes your right... i will revert this...

**Comment by gizmocuz** [comment]
Reverted

**Comment by odelma** [comment]
Thanks! :smile:

**Comment by alfonso-presa** [comment]
I think this is broken again in Beta. udevice commands are triggering my LUA scripts.

Logging the 'devicechanged' pairs names shows that the device that triggered the event was the one changed with 'udevice'.

Could you please take a look at it.

Thanks!

**Comment by gizmocuz** [comment]
we reverted it... but please have a look

**Comment by alfonso-presa** [comment]
I can confirm event LUA scrips are being triggered when updating a dummy switch state with `udevice`command in 7253. According to this issue and some forum entries I think this is not the expected behavior, right?

Steps to reproduce:
1. Create a dummy switch called `Test` (idx: 214 in my case). Edit: Set the event to be executed only on device changes.
2. Create a LUA Event with the contents:
```lua
commandArray = {}

for deviceName,deviceValue in pairs(devicechanged) do
  print("Device '".. deviceName.. "' is " ..deviceValue)
end

return commandArray
```
3. Open the logs view
4. Run the following from a terminal changing the ip, port and idx:
```sh
curl http://IP:PORT/json.htm\?type=command\&param=udevice\&idx=214\&nvalue=1
```
5. This will appear in the log event though, AFAIK, it shouldn't:
```
2017-04-06 23:35:51.218 LUA: Device 'Test' is On
```

Thanks!

**Comment by tparvais** [comment]
Hello

I have the same question : how to adapt switch status by api without triggering the script behind ! 
I have a domoticz pulse switch controlling a relay. Switch status in domoticz must be updated according another variable (current measurement ) 

I cannot do this due to this "bug" if it is one . Tx

**Comment by gohamstergo** [comment]
still ocurring on 3.8153.

edit: however, i did discover this:
commandArray['UpdateDevice']='idx|nValue|sValue' 
which seems to be working for lua at least, but isnt really what original OP was looking for..

**Comment by notsec** [comment]
Running 3.8153 and have this issue, very annoying. I have an ESP controlling an relay and if i push the controll button for the relay to fast something happens and an infinite loop of on and off are sent from domoticz to my ESP relay. Maybe this is a "Disco light" funktion ;-)
I hope that this can be resolved. @jcox10 is this working for you or do you still have the problem?

**Comment by psolyca** [comment]
I am on 3.9548 and have also the issue.
From ESPeasy, if I send
`SendToHttp myhost,8080,/json.htm?type=command&param=udevice&idx=4&nvalue=0&svalue=Off`
to return the state of my relay the action of my virtual switch is triggered and a command is send to the ESP which toggle the relay which send back the state to Domoticz which trigger the action... loop.

Using a slave switch as a workaround do not function anymore as changing the status of the slave also trigger the action of the master.
I do not want to use a user variable as a flag.
@gizmocuz this issue seems to be present again, could it be possible to open it ?

**Comment by dannybloe** [comment]
I guess you want more control in the api call to either trigger the event or not using a parameter. Sometimes you do want to trigger the actions and sometimes you don't.

**Comment by gizmocuz** [comment]
@psolyca , you mean this problem ? "Updating dummy switch via json now triggers on/off actions"
If that is so, it is like this for a long time now ?

**Comment by psolyca** [comment]
Yes I mean this issue.
I am new to Domoticz but I have read a lot before posting on this issue.

My configuration is this one :
- A physical switch connected to an ESP board,
- A relay connected to the ESP board to activate a light.
- A virtual switch on Domoticz.
The physical switch launch an event which toggle the relay and have to send the state of the relay (i.e. the light) to Domoticz reflect the status of the relay (i.e. the light)
The virtual switch can also send a command to toggle the relay.
But when the state is send from the ESP to Domoticz, the action of the virtual switch is triggered and the ESP triggered the relay which send back the state which... loop

I thought that
`SendToHttp myhost,8080,/json.htm?type=command&param=switchlight&idx=4&switchcmd=Off`
will triggered the action Off and change the status and
`SendToHttp myhost,8080,/json.htm?type=command&param=udevice&idx=4&nvalue=0&svalue=Off`
will just changed the status of the virtual switch without triggering the action Off.

Am I clear or do I misunderstand the command ?

Edit : I am installing the stable release to test if that work or not.
Edit2 : Same behaviour.

**Comment by odelma** [comment]
Hi, I think it should be:
`/json.htm?type=command&param=udevice&idx=4&nvalue=0&svalue=0` for Off and
`/json.htm?type=command&param=udevice&idx=4&nvalue=1&svalue=0` for On. Or this is at least what I am using (successfully) to change state without triggering an action.

**Comment by gizmocuz** [comment]
I had a look in the code, it indeed does trigger on/off actions, and i suppose some some users want this to happen.

But:
if your switch if of type "Lighting 2" it will handle On/Off actions

if your switch is from another type (ARC/X10), it will not trigger On/Off actions

Can you change your switch type ?

**Comment by psolyca** [comment]
@odelma: That do not work neither on stable release nor in last beta 3.9565.

@gizmocuz: My switches are virtual switches of type "Light/Switch". I did not find a way to change them to Lighting 2 or ARC/X10 ! Do I have to add a specific hardware ?

BTW, I find a way to avoid the loop on the ESP side.

**Comment by gizmocuz** [comment]
@psolyca , you do not want on/off actions, so it should 'not' be lighting 2, but could you post a screenshot of the widget in the 'switches' tab?

**Comment by psolyca** [comment]
@gizmocuz, here is a screenshot.
![switch_tab](https://user-images.githubusercontent.com/3757683/40906795-360c427e-67e2-11e8-9cd7-4bf1ba46b34a.png)

**Comment by gizmocuz** [comment]
@psolyca , thanks. Sorry, but from the devices view, what type/subtype is it ?
I try to replicate it here, and to be sure , you do NOT want on/off actions to happen with udevice correct ?

**Comment by psolyca** [comment]
@gizmocuz , Type is "Light/Switch", subtype is "Switch".

But I think I have found what I did wrong (not really wrong but I did not understood clearly the way is was done). 

I am using a LUA script with devicechanged event and not the two "Action on" and "Action off" area.
So, even an update of the state of the virtual switch fired my script.
So I need a way to retain the old state and compare with the new and run or not my command.

Sorry to have bother you with this.

**Comment by gizmocuz** [comment]
Maybe you can make use of a user variable,

if switch_state!=variable {
 variable=switch_state
 if (switch_state=="On") then xx
 else  if (switch_state=="Off") then yy
}

**Comment by psolyca** [comment]
Thanks for this.

**Comment by cherowley** [comment]
Can we reopen this please?

Can we just simply have a new json command to update a device without it triggering scripts/events etc?

**Comment by gizmocuz** [comment]
@cherowley , WebServer.cpp, arround line 2905, there is an optional parameter,  'parseTrigger' , default set to true.
Please make a PR where you check/use the optional json call parameter 'parseTrigger' (please not that it could not be provided.. 99,9% of the time, so default it should be 'true')

**Comment by cherowley** [comment]
Ah, when I click on new pull request, the create new request button is not enabled?

**Comment by gizmocuz** [comment]
@cherowley , you need to fork the project, then check it out locally, make some changes, test it, commit it, then on your fork you see a button 'Create Pull Request"
Please be sure you checkout the 'active' branch... which is the 'development' branch

**Comment by cherowley** [comment]
Ah I see. I'll have to defer to someone else then as I suspect that testing it will mean compiling it which I would not be able to do (unless there is a ms visual studio solution ?) let alone know where to put the if (parseTrigger == false) { return; } commands..

Ah ha! just found a solution - I'll see how I get on :)

**Comment by gizmocuz** [comment]
there is a Visual Studio solution in the msbuild folder, please read the INSTALL.txt file, you need to download/unpack the windows libraries

**Comment by cherowley** [comment]
getting a little further :)

installed libraries and adjusted location of stdafx.h as that was in the wrong place.

Using vs2013.. It's complaining that I don't have v142 - is it ok to change to v120?

Trying to compile using v120 results in dozens of errors:

c:\vc source\domoticz-development\webserver\server_settings.hpp(127): error C2436: '{ctor}' : member function or nested class in constructor initializer list (..\hardware\AccuWeather.cpp)
1>  Arilux.cpp
1>c:\vc source\domoticz-development\webserver\server_settings.hpp(127): error C2436: '{ctor}' : member function or nested class in constructor initializer list (..\hardware\AnnaThermostat.cpp)
1>c:\vc source\domoticz-development\hardware\annathermostat.cpp(87): error C3083: '{ctor}': the symbol to the left of a '::' must be a type
1>c:\vc source\domoticz-development\hardware\annathermostat.cpp(88): error C2533: 'CAnnaThermostat::Init' : constructors not allowed a return type
Error	24	error C2436: '{ctor}' : member function or nested class in constructor initializer list (..\hardware\Arilux.cpp)	c:\vc source\domoticz-development\webserver\server_settings.hpp	127	1	domoticz
Error	37	error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?	c:\vc source\domoticz-development\hardware\atagone.cpp	566	1	domoticz

**Comment by gizmocuz** [comment]
Sure as long as you do not commit changes from the project files
But you can also download VS2019 (community edition)

... i think you need to upgrade your visual studio, if you want a productive version, use 2017, if you want the latest/greatest ... 2019.

Ps. The community edition is free

**Comment by cherowley** [comment]
Ah boo, I just could not get it to even compile let alone know how to change the code...

I'll have to leave it to you genius guys who know and understand the code base to implement - I know a lot of people would like this feature (going by postings in the forums)..

**Comment by rwaaren** [comment]
As far as I know the JSON 
`/json.htm?type=command&param=udevice&nvalue=0&svalue=0&idx=`

do what you want. I used it a couple of days ago to implement the methods quietOff() and quietOn() in dzVents and got user confirmations (and test results) that it did the job.
 
Can you please open a topic on the forum if your findings are different ?

**Comment by cherowley** [comment]
Ah I’m not using dzevents.

I’m using lua scripting linked to virtual device – these are fed by espeasy devices..

The scripts are always ran..

I guess that udevice code is different in the lua engine than the dzevents engine ☹

**Comment by mikkel75** [comment]
This should be reopened... the 
/json.htm?type=command&param=udevice&nvalue=0&svalue=0&idx=
DOES trigger an output in MQTT "domoticz/out".

REALLY need a way to update devices WITHOUT triggering the event system (and generate output on MQTT "domoticz/out).

/M

**Comment by gizmocuz** [comment]
@mikkel75 , please do NOT crosspost and DO NOT use CAPITALS !
You SHOULD go to the forum and ask the question there, OR ... look at the SOURCE CODE to see how this could be done
You could then make a PR to add a additional parameter to prevent a trigger.

**Comment by mikkel75** [comment]
sorry if the use of capitals offended you - that was not my intention.
i really just don't understand why such a great piece of software as domoticz is still lacking this - to me - basic feature.
it also seems like the intention was to not trigger events using udevice - thats what is written on the wiki anyway:

> If you just want to update the status of the switch in Domoticz without running these actions, use the &param=udevice option instead (see update-section below).

**Comment by gizmocuz** [comment]
Sure we want triggers... but it depends how you use it.
It is very easy to add in Domoticz, time is always an issue
Did you have a look in the CWebServer::Cmd_UpdateDevice function ?
This one was extreme easy to add yourself if you had taken some time for it

https://github.com/domoticz/domoticz/commit/8770e0474fb9630c3a27158da8cdf9f8103cc9e3

Hope it works now as expected in beta 11656

**Comment by DaeMonSx** [comment]
loop here as well.
Any smart solution yet?
iam updating domoticz switches via json call, and from domoticz I have created links which are triggering the device relays.
Now it loops back and force, stays in loop.
I seem to be reluctant using two items in domoticz just for control, and second for feedback.
Any smart idea or solution? Thank for the hints

**Comment by gizmocuz** [comment]
@DaeMonSx , Please state your version... As you can see this should be solved in the beta version
