### ISSUE TITLE
Domoticz won't start after update, PID file error.

### ISSUE THREAD

**Issue by ageir** [domoticz/domoticz#1229]
Today I updated Domoticz to the latest beta and it won't start anymore. See error below.
It has been working perfectly for many months and have been updating to the latest beta version regularly without any problems at all. But today it won't work. Did something change in how domoticz handles pid files?

I'm running it as its own domoticz user and not as root. And I haven't changed anything else in the system.

Domoticz version
```
2017-02-13 15:23:48.151  Domoticz V3.6700 (c)2012-2017 GizMoCuz
2017-02-13 15:23:48.153  Build Hash: 64bfebe, Date: 2017-02-13 12:42:38
```

```
Feb 13 15:22:06 raspberrypi domoticz[973]: Domoticz is starting up....
Feb 13 15:22:06 raspberrypi domoticz[977]: Could not open PID lock file /var/run/domoticz.pid, exiting
Feb 13 15:22:06 raspberrypi domoticz[977]: Domoticz is exiting...

```

**Comment by oohlaf** [comment]
See https://github.com/domoticz/domoticz/pull/1211#issuecomment-279142248
It fixes Systemd daemonize function to actually fork and create a PID file, which previously was broken.

Are you using Systemd or init.d startup script?

Are you sure the PID file location is writable by domoticz user?
Usually /var/run/XXX.pid is only writable by root and maybe you never noticed that a PID file was never actually created.

```
# mkdir /var/run/domoticz
# chown domoticz.domoticz /var/run/domoticz
```
and add `-daemon -pidfile /var/run/domoticz/domoticz.pid` as startup argument to Domoticz

**Comment by ageir** [comment]
Thanks. That fixed it. It was crashing before I added the settings you referred to the startup file. Wasn't forking properly.
