### ISSUE TITLE
Graphs on iOS show spikes at the edges of switching values.

### ISSUE THREAD

**Issue by GertSanders** [domoticz/domoticz#123]
My voltage measurements jump a lot between 2 values, which is not the problem in itself. But the graphic showing the evolution has become unreadable when I'm NOT zoomed in.

As a picture tells more then words, here is what it looks like on my iPhone (tablet gives the same).

![img_7347](https://cloud.githubusercontent.com/assets/14805320/10302249/c634ec2e-6c0a-11e5-8485-7927d289ac74.PNG)

Zooming in a bit I get:

![img_7349](https://cloud.githubusercontent.com/assets/14805320/10302325/88e1df66-6c0b-11e5-8022-35c636036359.PNG)

Further zooming in:

![img_7350](https://cloud.githubusercontent.com/assets/14805320/10302331/a13ce0a6-6c0b-11e5-91fc-e24bd1367a4e.PNG)

Even more:

![img_7351](https://cloud.githubusercontent.com/assets/14805320/10302340/b31d3a0a-6c0b-11e5-818d-2081e1a8c89d.PNG)

It seems this an issue only on iOS (Safari).

On my PC in Inter Explorer 11 I get the following: no spikes at the edges. But the vertical lines are wider in the middle then at the edges. The primitive used to plot a vertical line must be a curved shape to show this strange narrowing at the edge.

![chart](https://cloud.githubusercontent.com/assets/14805320/10302383/2ea00e32-6c0c-11e5-854b-1920f5cfbc40.jpeg)

The question now is, why are these spikes visible, is there something that can be done to avoid them ? Especially on mobile devices with Safari these spikes make graphs unusable. Maybe use a different grapics library without this strange behaviour to plot lines ?

**Comment by gizmocuz** [comment]
i think it is the way the browser plots the graph

if you set your shortlog to 2 days, i think you have a better graph

**Comment by GertSanders** [comment]
I agree it is the browser, but why bring down the number of shown samples, when the primitive to show a line could be changed? As I have no idea how the graph is created, that is why I'm asking. But if need be, I wil dive in the code to check, and then ask my collegues (developers) if they can propose an improvement.. I'm an electronics engineer turned manager, so my knowledge of code is very old and rusty.

I would like to keep the view of a week data instead of seeing just 2 days of data.

**Comment by gizmocuz** [comment]
this also had to do with a bug, normally the shortlog has a value every 5 minutes.
The graph is made by HighCharts
