### ISSUE TITLE
After the adding of ET & LV caching issues appear due to missing i18n files

### ISSUE THREAD

**Issue by pvangorp** [domoticz/domoticz#1237]
After upgrading to V3.6722 I ran into caching issues.
The problem is that the i18n files are missing in the repository for ET & LV
I tested the issue by copying EL to ET and EL to LV and everything works fine again.
So please add the missing files!
![1](https://cloud.githubusercontent.com/assets/25818919/23020109/c59a6ee6-f445-11e6-81f8-ba211632b4b9.png)
![2](https://cloud.githubusercontent.com/assets/25818919/23020110/c59d3748-f445-11e6-94e0-58021052edec.png)
![3](https://cloud.githubusercontent.com/assets/25818919/23020111/c59dc280-f445-11e6-9958-a27c1d9ba81c.png)

**Comment by gizmocuz** [comment]
Pascal, after 2 emails from you, i think i know...
Anyway, will be solved in the next beta
