### ISSUE TITLE
TOON Error getting current state

### ISSUE THREAD

**Issue by jcarduino** [domoticz/domoticz#125]
Error in log:
2015-10-06 17:15:45.296 Error: ToonThermostat: Error getting current state!
Still investigating. Get some confusing results... puzzled...

**Comment by gizmocuz** [comment]
if you know why, please open a new issue, else use our forum

**Comment by jcarduino** [comment]
Had a clue but deleted it as I was reinvestigating. Have to do some coding for it. Has to wait as I left for few days France.

Mvg 

Johan Corstjens

**Comment by gizmocuz** [comment]
Great, if you have an update, please let us know

**Comment by sj3fk3** [comment]
I get the same error: Error: ToonThermostat: Error getting current state!

**Comment by jcarduino** [comment]
I am low on time sadly to actively hunt this down right now. However I also discovered that it also leaves open connections to toon servers resulting in failed login attempts as only 4 connections are allowed. Perhaps this is also affecting getting current state. 

Hope to find some time to add some debug code to toon driver to investigate this. 

Mvg Johan Corstjens

Verstuurd via mobile

**Comment by gizmocuz** [comment]
i found out that only two applications can be used (your real toon, and for instance domoticz)
if you also log in via the web interface, you might receive a timeout, but this should go away after a while

**Comment by slinkos** [comment]
Everyone I know using Toon and Domoticz have this problem. WIch makes controlling your Toon with Domoticz very unreliable... Anybody got any news regarding this?

**Comment by EdwinKort** [comment]
Almost a year and half gone and still Toon is throwing this :(
