### ISSUE TITLE
404 error for WindowsLibraries.7z

### ISSUE THREAD

**Issue by ffes** [domoticz/domoticz#1251]
I want to build domoticz with VS2015.

[INSTALL.md](https://github.com/domoticz/domoticz/blob/master/INSTALL.md) says I need to download http://www.domoticz.com/WindowsLibraries.7z but that gives a 404 error.

What is the correct URL?

**Comment by gizmocuz** [comment]
Sorry, hope you can update the INSTALL.md as well.
You can find the needed libraries in our git repo, one above this one
