### ISSUE TITLE
Json issue with a lightswitch: error opening url

### ISSUE THREAD

**Issue by TroisSix** [domoticz/domoticz#1252]
Hi,

I have Domoticz Beta 3.6765, and I have an url issue with "Action On" call in a lightswitch.

I used "Action On" and "Action Off" with a lightswitch (zwave: Vision ZG8101 Garage Door Detector), it always worked with this to activate another lightswitch:
`https://MY_IP/json.htm?type=command&param=switchlight&idx=XXX&switchcmd=On`

But for a moment I have an error message when calling url: 
`Error: Error opening url: https://MY_IP/json.htm?type=command¶m=switchlight&idx=XXX&switchcmd=On`

As you can see, my url seems to be wrong with this:
`?type=command¶m=switchlight`
instead of :
`?type=command&param=switchlight`

I tried to type letter by letter from scratch, but I still have this bug...

What do you think I could do to solve it?
Has anyone else already had the same bug?

Thanks for your help.

**Comment by gizmocuz** [comment]
Tested with the latest beta version, no problems at all
![image](https://cloud.githubusercontent.com/assets/2265299/23208083/fa3768ea-f8f3-11e6-8e20-111e2ab3dc12.png)

Please use our forum
