### ISSUE TITLE
Add light of type Arilux AL-LC0x failed

### ISSUE THREAD

**Issue by HKohout** [domoticz/domoticz#1253]
Hi,

I'm using last beta version V3.6765 and tried the following:
* Add a new hardware of type Arilux AL-LC0x
* Add a new light, enter name IP address and hit OK
* Message appears, that the new device can be found in the devices tab.
* But: There is no device

For verification I made an database export and had a look in the table **DeviceStatus**.
Still nothing found (no additional entry).

I had a look in File hardware/Arilux.cpp and wondering about that in function **InsertUpdateSwitch()** there is no insert-statement for adding a row to table **DeviceStatus**.
In line 133 there's just an UPDATE-statement.

**Comment by LKapie** [comment]
I installed and tested an Arilux device and experienced the same issue. 
Wondering if there is any follow up to be expected on this issue?

**Comment by LKapie** [comment]
Tested today with latest beta 3.706 on Raspi and Windows:

~~Raspi: adding device: OK, device can be found in devices list.~~
~~Windows: adding device: NOK, message tells device is added but cannot be found in devices list.~~
~~So problem seems to be in de windows distribution... Maybe @HKoHout can confirm??~~

Tested a bit more and found out both Raspi and Windows versions are acting the same and I can reproduce the issue on both distributions; problem seems to be the "accept new hardware" checkbox. 

When I activate "accept new hardware" (permanent or for 5 min)  the Arilux AL-LC04 is added correctly in both the Raspi and Windows version. When "accept new hardware" is off the device is not added correctly.
So the good news is that there is a work-around. @HKohout can you check and confirm?

**Comment by HKohout** [comment]
Hm. Tested a few minutes ago with 3.7067 on a RasPi. Still not working for me. 
The RasPi runs with the official image.
Any suggestions?

**Comment by LKapie** [comment]
Did you test after my latest (changed) description of the issue?
So "accept new hardware" checkbox "on"?

**Comment by HKohout** [comment]
That did the trick. Thank you :-)

**Comment by LKapie** [comment]
Tested other functions of the arilux and my conclusion is that code is a bit buggy;
- Disabling hardware (so uncheck checkbox "Enabled") does not work. 
- Renaming hardware does not work.
- Switching device on with timer does not work: Error: Error sending switch command, DevID: 90, Time: 2017-03-20 22:20:01
- some other?

Most of the time not ok to make a bundle of issues but I have the feeling this code needs some additional work before it can be (bèta) released ?!
If it is appreciated/helpfull I'm of course available for testing...

**Comment by gizmocuz** [comment]
Disabling the hardware should be fixed in the next beta
Dont know about the other points... could the author of this class look at this ?

**Comment by ducseb** [comment]
Hello, 

I'm the dev of this class, no problem I'll fix the problems as soon as possible. 

Sorry for the inconvenience.

**Comment by gizmocuz** [comment]
No worries

**Comment by chatainsim** [comment]
@ducseb did you fix the issue ?
Thanks

**Comment by BioGeekJoey** [comment]
Has this been solved? I'm currently experiencing a similar bug but not sure if I should open a new report.

**Comment by gizmocuz** [comment]
@ducseb, where you able to fix this ?

**Comment by gizmocuz** [comment]
No feedback, closing issue
