### ISSUE TITLE
[feature request] auto-backup specific settings

### ISSUE THREAD

**Issue by Lyr3x** [domoticz/domoticz#1256]
Im using the auto backup, which is working fine. But it would be nice if the user can specify the back up time and maybe the folder through the UI (Settings). 

I personally would change the backup time to the night, because if the backup is starting domoticz wont react since the backup process is done.

**Comment by gizmocuz** [comment]
I agree, and also one backup a day is enough.
Are you able to make this functionality in domoticz ?

**Comment by Lyr3x** [comment]
i will try it and i'll give it a shot, but can you tell me where the existing backup function is implemented. (just the file.. cause there are a lot 💯 )
