### ISSUE TITLE
Issue with tag reader Benext on last version of beta domoticz

### ISSUE THREAD

**Issue by seblang** [domoticz/domoticz#1265]
I am using Domoticz but since last update 2_6775 and 2_6796 my tag reader doesn't work any more!
Connexion issue - 6 bip
Somebody have te same issue?

**Comment by bob123bob** [comment]
Same issue here. But we are talking about v3.6775 not v2.6775
Issue already discuss on the forum but with no success
https://www.domoticz.com/forum/viewtopic.php?f=6&t=16251#p121464

Dev team please help, it was working before.

**Comment by seblang** [comment]
I am on windows version  2_6775 and 2_6796! both version doesn't work.
I have re-installed version 2_6129 and it's work fine again.

**Comment by gizmocuz** [comment]
I remember something has been changed related to the tag reader... but can not find the changes
Hope someone can debug this in the code
My tag reader is not alive anymore....

**Comment by seblang** [comment]
Can someone can debug this in the code? 
Gizmocuz, if it's needed we can made a donation so you can buy a new tag reader

**Comment by gizmocuz** [comment]
No i can buy one, but my time is limited for the next days
Hope another c++ developer with a tag reader can have a look at this
you can check the code changes

**Comment by seblang** [comment]
Hi Gizmocuz I hope.
It's possible to know who have done the modification ?

**Comment by gizmocuz** [comment]
I think i did the modification.
Hope to receive a new TAG reader today

**Comment by gizmocuz** [comment]
Its fixed now
