### ISSUE TITLE
Compile warnings

### ISSUE THREAD

**Issue by zuidwijk** [domoticz/domoticz#1272]
Did a pull a few minutes ago, got these warnings:

/home/marcel/domoticz/main/mainworker.cpp: In member function ‘void MainWorker::decode_CartelectronicTIC(int, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)’:
/home/marcel/domoticz/main/mainworker.cpp:10381:66: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘uint32_t {aka unsigned int}’ [-Wformat=]
          sprintf(szTmp, "%u;%ld", counter2ApparentPower, counter2);
                                                                  ^
/home/marcel/domoticz/main/mainworker.cpp:10400:66: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘uint32_t {aka unsigned int}’ [-Wformat=]
          sprintf(szTmp, "%u;%ld", counter2ApparentPower, counter2);
                                                                  ^
/home/marcel/domoticz/main/mainworker.cpp:10460:66: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘uint32_t {aka unsigned int}’ [-Wformat=]
          sprintf(szTmp, "%u;%ld", counter2ApparentPower, counter2);
                                                                  ^
/home/marcel/domoticz/main/mainworker.cpp:10477:60: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘uint32_t {aka unsigned int}’ [-Wformat=]
    sprintf(szTmp, "%u;%ld", counter1ApparentPower, counter1);
                                                            ^
/home/marcel/domoticz/main/mainworker.cpp: In member function ‘void MainWorker::decode_CartelectronicEncoder(int, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)’:
/home/marcel/domoticz/main/mainworker.cpp:10512:166: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘uint32_t {aka unsigned int}’ [-Wformat=]
 Response->CEENCODER.id1 << 24) + (pResponse->CEENCODER.id2 << 16) + (pResponse->CEENCODER.id3 << 8) + pResponse->CEENCODER.id4));
                                                                                                                                ^
/home/marcel/domoticz/main/mainworker.cpp:10518:34: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘uint32_t {aka unsigned int}’ [-Wformat=]
    sprintf(szTmp, "%ld", counter1);
                                  ^
/home/marcel/domoticz/main/mainworker.cpp:10528:34: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘uint32_t {aka unsigned int}’ [-Wformat=]
    sprintf(szTmp, "%ld", counter2);
                                  ^

**Comment by zuidwijk** [comment]
It does compile and it does work, only the warnings.

**Comment by gizmocuz** [comment]
Thanks, fixed in
https://github.com/domoticz/domoticz/commit/cfa7b98080d911bad9856211b3049cba59c43672
