### ISSUE TITLE
Three minor issues with the Qubino Smart Meter (ZMNHTDx)

### ISSUE THREAD

**Issue by petrovcicklemen** [domoticz/domoticz#1275]
Tested versions: latest stable and also the available beta version

After including the Qubino SmartMeter device three issues were found:

- The Name column (in the Domoticz GUI and the Open Zwave Control Panel) is set to "Unknown" string. Since Domoticz wraps the OpenZwave library, this is must probably an OZW issue. Is there any other way to remedy this, rather than manually editing the domoticz.db file (table ZWaveNodes)?

[Picture of Issue 1](https://dl.dropboxusercontent.com/u/55075286/issue_1.png)

- Domoticz doesn't display all the data, which the OZW provides. In the attached picture you can see, that there are also kWh and kVAh units fetched, but they are not listed in the "Devices" region in Domoticz.

[Picture of Issue 2](https://dl.dropboxusercontent.com/u/55075286/issue_2.png)

- In the OZW Control panal, the kVAh unit is correctly displayed at the appropriate measurement, while in Domoticz, the same measurement has a Watt unit. Due to this issue, the plotted graphs look weird and make no sence, since they are scaled for the Watt unit. 

[Picture of issue 3](https://dl.dropboxusercontent.com/u/55075286/issue_3.png)

 Would anybody know how to remedy these problems?

Regards.

**Comment by gizmocuz** [comment]
Please use our forum
