### ISSUE TITLE
Include statement syntax

### ISSUE THREAD

**Issue by jrich523** [domoticz/domoticz#1279]
So i was just trying to update my master branch and recompile, and i ran in to an issue i didnt previously have.

the syntax for many of the includes (mostly around MQTT) are <> based rather than ""

which, according to the VS docs https://msdn.microsoft.com/en-us/library/36k2cdd4.aspx
the "" is probably a better option since it includes the local project and then looks at the same things the <>

Obviously a lot of folks are compiling/running this on nix systems and im not sure what impact that would have on those systems.

my development knowledge is not around C++ so this is all pretty new to me, am i way off base here and missing something else?

Also i've noticed we're starting to get more people interested in development, it might be worth while to add a development Group to the forums with perhaps General Development, WebUI and Device Development, to help keep this clean since really this question probably shouldnt be in here.

**Comment by gizmocuz** [comment]
I never had issues before, and compile at least a few times a day
You seem to use visual studio, are you using VS2015 ? If not, try 2015

**Comment by jrich523** [comment]
Yes its 2015, i'll do some more reading to see if there is something missing, but from what i've read so far it sounds like "" should be used anytime the include is something with in your project.
Basically its says that the <> method looks  for the /l param value for paths or the "include" env variable so I guess its possible you have one of those two things configure where i dont?

**Comment by gizmocuz** [comment]
Yes, but then nobody should be able to compile correct? and thats not the case

**Comment by jrich523** [comment]
Weird, so i had at one point created a "release-deploy" build to have it build and deploy to my server and attach a debugger, which according to the commit was removed but VS is still showing it. If i change it to just "release" it works and from what i can tell the projects configuration for "release" build has a different "additional include directories" configured, which is the exact problem Im having. When I add the ..\MQTT to my build config it all works fine.

It seems like we would be better served to use "" rather than <> because the reason the <> is working is because of the compiler configuration which would need to be updated if we add stuff to the project (like MQTT was added since my last pull apparently)

I think if we move to "" we can remove the configuration of 'additional include directories' which will simplify things moving forward, but i dont really know what impact this would have on nix, none im guessing since its a setting within the VS project config, unless you're using some tool to build the VS project config.

not a big deal, just trying to get a better grasp on things.

**Comment by gizmocuz** [comment]
then i suspect you did not copy the project settings (build settings)

**Comment by jrich523** [comment]
i did, but the last time i pulled it apparently didnt have the /mqtt stuff since thats the only part that was missing from my list. its fixed now.

I suspect there is a performance hit for using "" since it will have to scan the entire project vs just checking what is defined. 

either way, i think im good now, thanks!

**Comment by gizmocuz** [comment]
Great ! Now i expect lots of contributions from you haha ;)

**Comment by jrich523** [comment]
lol i would love to contribute more (any) but im still trying to get my c++ up to speed!

Also what are your thoughts on the dev related forums i mentioned in the original post?

**Comment by gizmocuz** [comment]
It of course all depends on your build settings

**Comment by gizmocuz** [comment]
(include paths)
