### ISSUE TITLE
[Error] Unable to add notification: no column named SendAlways

### ISSUE THREAD

**Issue by YoranSys** [domoticz/domoticz#128]
Hi,
When I try to add notifications I have this type of error and no notification are created:
- 2015-10-07 13:31:36.790 Error: SQL Query("INSERT INTO Notifications (DeviceRowID, Params, CustomMessage, ActiveSystems, Priority, SendAlways) VALUES ('177','S','','email;kodi',0,0)") : table Notifications has no column named SendAlways
- 2015-10-07 13:31:36.792 Error: SQL Query("SELECT ID, DeviceRowID, Params, CustomMessage, ActiveSystems, Priority, SendAlways, LastSend FROM Notifications ORDER BY DeviceRowID") : no such column: SendAlways
- 2015-10-07 13:31:43.503 Error: SQL Query("INSERT INTO Notifications (DeviceRowID, Params, CustomMessage, ActiveSystems, Priority, SendAlways) VALUES ('177','O','','',0,0)") : table Notifications has no column named SendAlways
- 2015-10-07 13:31:43.504 Error: SQL Query("SELECT ID, DeviceRowID, Params, CustomMessage, ActiveSystems, Priority, SendAlways, LastSend FROM Notifications ORDER BY DeviceRowID") : no such column: SendAlways

My domoticz version is: Version: 2.3266
Build Hash: 6237ae2
Compile Date: 2015-10-06 14:27:17

**Comment by gizmocuz** [comment]
how is this possible? Did you swap between stable and beta versions maybe ?

it should have been added automatically

you can add the column by issuing:

ALTER TABLE [Notifications] ADD COLUMN [SendAlways] INTEGER DEFAULT 0

but you might miss more updates

you can also make a backup of the database, open the preference table, and set the database version to 71

**Comment by YoranSys** [comment]
Thank you,
I change the database version to 71 and now it's working well !

Tks for this great soft ;)

**Comment by gizmocuz** [comment]
Your welcome ;)
