### ISSUE TITLE
Rename/change 'Restart system' menu item

### ISSUE THREAD

**Issue by BenoitDuffez** [domoticz/domoticz#1280]
I was trying to troubleshoot something, and I figured I could restart the service/process behind Domoticz. I found the `Restart system` menu entry.

I DID NOT EXPECT TO REBOOT THE WHOLE SERVER!!!!
It's not a Raspberry on my desk, it's a whole server with lots of services and I didn't want it to reboot.

I would love a change from `Restart` to `Reboot` and make the confirmation dialog more explicit, like `THIS WILL PHYSICALLY REBOOT THE MACHINE`.

What do you think? Well, now I know. But for newcomers...

**Comment by gizmocuz** [comment]
Well it's restarting the system, same as the shutdown system... this shuts down the system

**Comment by BenoitDuffez** [comment]
I'm just talking about the wording, I did not find restart explicit, and I never expected it to mean reboot. Others might get confused?

**Comment by gizmocuz** [comment]
Dont think so... what is the button under the restart option ?

**Comment by BenoitDuffez** [comment]
Shutdown.

**Comment by gizmocuz** [comment]
so... what would restart do ? I think it is very clear

**Comment by BenoitDuffez** [comment]
What I expected:

* Restart => something like `/etc/init.d/domoticz restart`
* Shutdown => something like `/etc/init.d/domoticz stop`

Domoticz should not physically reboot the system. Just restart itself (as a process).

**Comment by gizmocuz** [comment]
try what the restart option in windows does ...
Anyway, i think it is clear enough
So you experienced a different behaviour, then do not use the menu option again if you want to shutdown domoticz
We could extend it with restart domoticz (you can create a pull request for this... only visible on unix systems please)
Remember, some people have no linux experience, then want/need to shutdown the system sometimes, or restart it

**Comment by BenoitDuffez** [comment]
That's why I just wanted to rename this to reboot machine and power off machine. Something more explicit and cross platform.

Indeed I will never use it again but I'm proposing a change in case someone else would be trapped like me.

**Comment by gizmocuz** [comment]
If you press the windows start menu, the option is also labeled 'restart'

**Comment by BenoitDuffez** [comment]
Windows is an OS!!! When you close Excel your computer doesn't reboot...

**Comment by gizmocuz** [comment]
Yes your correct
