### ISSUE TITLE
deviceID inconsistency in Python subsystem

### ISSUE THREAD

**Issue by seventer** [domoticz/domoticz#1287]
As I reported in:
[http://www.domoticz.com/forum/viewtopic.php?f=65&t=15233&start=100#p121878](url) there seems to be an inconsistency in the deviceID handling. Resulting in unable to use notification and external json commands.

I found in file:  domoticz/hardware/plugins/PythonObjects.cpp at line 630

`sprintf(szID, "%X%02X%02X%02X", 0, 0, (self->HwdID & 0xFF00) >> 8, self->HwdID & 0xFF);`

after changing the code to:
`sprintf(szID, "%02X%02X%02X%02X", 0, 0, (self->HwdID & 0xFF00) >> 8, self->HwdID & 0xFF);`

everything seems to work fine, both, notification and json commands work as expected.

bug and fixes are tested on V3.6808
--Gerard

**Comment by gizmocuz** [comment]
Please continue the discussion in the forum, and if needed create a pull request
