### ISSUE TITLE
cross compile with -DUSE_PYTHON_PLUGINS=NO error

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#1291]
domoticz v3.6828 all ok.
domoticz v3.6831 fails.
Compile with Python work ok, but compile with  -DUSE_PYTHON_PLUGINS=NO fails with this error.
[ 99%] Building CXX object CMakeFiles/domoticz.dir/tinyxpath/xpath_expression.cpp.o
[100%] Building CXX object CMakeFiles/domoticz.dir/tinyxpath/xpath_static.cpp.o
Linking CXX executable domoticz
CMakeFiles/domoticz.dir/main/WebServer.cpp.o: In function `http::server::CWebServer::PostSettings(http::server::_tWebEmSession&, http::server::request const&, std::string&)':
WebServer.cpp:(.text+0x227d9): undefined reference to `http::server::CWebServer::PluginLoadConfig()'
collect2: error: ld returned 1 exit status
make[5]: *** [domoticz] Error 1

**Comment by gizmocuz** [comment]
Thanks for reporting, should be fixed with latest commit

**Comment by Jumbotroll** [comment]
Fixed!
domoticz v3.6833 all ok.
Thanks!
