### ISSUE TITLE
[Request] - Add Tado thermostat as native device

### ISSUE THREAD

**Issue by rjblake** [domoticz/domoticz#1294]
I have changed from my Toon to a Tado thermostat and would like to add this as a native Domoticz device. My C++ skills are definitely not up to the task, but I believe that the Thermosmart device could possibly be adapted fairly simply to create a Tado device. I have all the relevant API type info that I'm currently using in my PHP scripts but am lost where to start in C++

**Comment by gizmocuz** [comment]
We have a lot of hardware classes that are almost identical to the tado
I suggest you look into these once, then if you found one, copy/paste it under a new name, and start the development
Or maybe you can create a python plugin with the new python plugin system ?

**Comment by rjblake** [comment]
Ok - will give it a try

**Comment by gizmocuz** [comment]
Great thanks!

**Comment by willemstoker** [comment]
Any progress on this?

**Comment by theelog** [comment]
I too would love to see this added to Domoticz.

**Comment by morilm** [comment]
My vote also for adding Tado AC to the devices....   it should be difficult by using the API provided (most difficult part is to get the homeID).

There is homebrigde plugin available on npm

**Comment by gizmocuz** [comment]
@rjblake, did you had any luck implementing this ? (native or via a python plugin)

**Comment by pnieuwla** [comment]
any news on this?

**Comment by raptile** [comment]
I would like this aswell

**Comment by rjblake** [comment]
I'm afraid I just have not had the time available to begin looking at this. It has not been a high priority for me, as Domoticz is logging the data and I also use Tado data for a proximity/geofence provided by the PHP scripts. As the thermostat is very much 'set and forget', I have very little need to every change settings. Using Apple devices and Homebridge puts all the functionality in one place. I can see why some would want to include in Domoticz and if I get some time I'll give it a go, but cannot guarantee any timelines for now

**Comment by dotms** [comment]
I just put in a pull request to add this functionality to Domoticz: https://github.com/domoticz/domoticz/pull/2306

**Comment by MijnHanden** [comment]
Hi, 
When I used the Tado in domoticz the first time I saw all devices except one of the thermostats, but I did see the % energy request of that room. I removed the Tado from the hardware list and re-added it but now I don't see any of the items in the device list.
When I add tado in and look at the log I see this:
2018-04-28 08:43:05.557 Tado: Worker started. Will poll every 30 seconds.
2018-04-28 08:43:10.557 Tado: Attempting login.
2018-04-28 08:43:16.483 Tado: Retrieved webapp environment from API.
2018-04-28 08:43:22.474 Tado: Received access token from API.
2018-04-28 08:43:22.475 Tado: Received refresh token from API.
2018-04-28 08:43:22.475 Tado: Login succesful.
2018-04-28 08:43:28.156 Tado: Registered Home 'xxxxxx' with id 15xxxx
2018-04-28 08:43:33.858 Tado: Registered Zone 1 'woonkamer' of type HEATING
2018-04-28 08:43:33.858 Tado: Registered Zone 5 'Lynn' of type HEATING
2018-04-28 08:43:33.858 Tado: Registered Zone 6 'Owen' of type HEATING
2018-04-28 08:43:33.858 Tado: Registered Zone 0 'Warm water' of type HOT_WATER
once in a while I see:
2018-04-28 08:58:23.663 Tado: Received access token from API.
2018-04-28 08:58:23.663 Tado: Received refresh token from API.

but nothing showing up in my devices list, not under all devices or not used or even search with $ does not show anything. any Idea what I am doing wrong?
![image](https://user-images.githubusercontent.com/22778095/39393170-550e9646-4ac2-11e8-89b8-949e0581fddc.png)
I am on the latest beta. Ubuntu is up to date as well.
Thanks for the help
MH

**Comment by dotms** [comment]
Please make sure that 'Accept new hardware devices' is enabled (or use 'Allow for 5 minutes'). Without it the plugin won't be allowed to add new devices. You can find it under Setup > Settings and then all the way down on the left side.

**Comment by rjblake** [comment]
@dotms - really appreciate your effort and work on this. I 'turned it on' yesterday and working well. In looking to replace my PHP script, wondered if you would consider the following enhancements:
1. Away indicator - change from switch to alert. Also with additional parameter for proximity (currently I have these as Home, Close and Away)
2. Outside temperature - since Tado already reports this, it is possibly one less call to Wunderground or OpenWeather

**Comment by dotms** [comment]
@rjblake Thank you. In order to keep discussion a bit more central and organized let's continue at http://domoticz.com/forum/viewtopic.php?f=34&t=23265 . If that works for you then please close this issue and pick it up from there :)

**Comment by rjblake** [comment]
Closing the issue as Tado is now included as a native device :) - awesome job dotms!
