### ISSUE TITLE
HTTP/HTTPS poller doesn't get all the data

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#1300]
I found that when I'm getting json data the poller doesn't get the whole thing if there is a lot of data.  Just 2024 characters only.  It would be nice if it could get more than that, much more than that.  I checked it to make sure it wasn't *bonking* on some unescaped special character and it wasn't.  It's always stopping at exactly the same point regardless of content.  I also opened the data in my browser and it looked normal as well.

**Comment by gizmocuz** [comment]
I just verified by generating a 76KB json file, that in

void CHttpPoller::GetScript()

the GET/POST is retrieving this object correctly

So the only position where this could go wrong is 

luaScript.executeLuaScript(m_script, sResult);

Maybe there is an error in the json ? did you try an online verifier like

jsonviewer.stack.hu

the online json generator is located at:

http://beta.json-generator.com

**Comment by Ittiz** [comment]
Everything seems using json.stack.hu.  Maybe I'm barking up the wrong tree?  To troubleshoot I made the system print the json to the log.  Maybe there is a size limit of what can be printed in the log?

**Comment by gizmocuz** [comment]
Yes, 200 lines

**Comment by Ittiz** [comment]
it's all output to one line 300 characters or more long.

**Comment by gizmocuz** [comment]
? ;) okey... why ?? sure that can also be the issue
Best to debug with the code maybe ? and/or write it to disk

**Comment by Ittiz** [comment]
I'm getting the json from an http source that I can't alter.  here's a sample:

{"accel":{"desc":["Ax","Ay","Az"],"unit":"m/s²","data":[[1488722952755,[9.787037,-0.088259846,0.18632634]]]},"battery_voltage":{"unit":"V","data":[[1488722948185,[4.2]],[1488722950296,[4.2]],[1488722952330,[4.2]]]},"mag":{"desc":["Mx","My","Mz"],"unit":"µT","data":[[1488722947829,[-51.6875,-6.5,7.1875]],[1488722947958,[-51.5,-6.6875,7.25]],[1488722948084,[-51.6875,-6.5,6.75]],[1488722948222,[-52.0625,-5.875,6.375]],[1488722948350,[-52.375,-5.8125,6.875]],[1488722948476,[-52.8125,-5.9375,6.6875]],[1488722948611,[-52.75,-5.625,6.625]],[1488722948737,[-53.3125,-6.625,6.375]],[1488722948864,[-53.5,-6.5,5.875]],[1488722948992,[-52.9375,-5.8125,6.5625]],[1488722949121,[-53.5625,-6.3125,6.25]],[1488722949259,[-52.9375,-5.9375,6.5625]],[1488722949384,[-52.125,-5.8125,7.1875]],[1488722949526,[-52.375,-6.4375,6.375]],[1488722949642,[-52.1875,-6.125,5.9375]],[1488722949768,[-52.125,-5.8125,6.4375]],[1488722949894,[-52.1875,-6.4375,8.5625]],[1488722950021,[-52.6875,-6.625,10.625]],[1488722950339,[-52.75,-7.25,12.875]],[1488722950384,[-52.1875,-7.5625,12.0]],[1488722950448,[-52.5,-7.4375,9.6875]],[1488722950535,[-51.6875,-7.5,10.0625]],[1488722950683,[-52.0625,-7.25,10.5625]],[1488722950789,[-52.875,-7.125,13.1875]],[1488722950914,[-52.9375,-7.0625,12.8125]],[1488722951040,[-52.9375,-6.625,12.25]],[1488722951174,[-52.375,-6.8125,11.8125]],[1488722951301,[-52.125,-7.375,11.8125]],[1488722951433,[-52.25,-7.5,14.125]],[1488722951561,[-52.75,-7.6875,13.9375]],[1488722951692,[-53.0,-7.6875,14.5]],[1488722951819,[-52.8125,-7.5,14.875]],[1488722951946,[-53.125,-7.0625,12.9375]],[1488722952072,[-53.5625,-6.1875,11.125]],[1488722952198,[-53.5,-5.8125,10.9375]],[1488722952330,[-54.125,-5.875,10.4375]],[1488722952472,[-53.4375,-5.875,12.4375]],[1488722952585,[-52.875,-6.75,15.8125]],[1488722952712,[-52.6875,-6.625,15.4375]]]},"battery_temp":{"unit":"℃","data":[[1488722948185,[34.0]],[1488722950296,[34.0]],[1488722952331,[34.0]]]},"battery_level":{"unit":"%","data":[[1488722948185,[100.0]],[1488722950296,[100.0]],[1488722952330,[100.0]]]},"light":{"unit":"lx","data":[[1488722947560,[15.0]],[1488722947864,[17.0]],[1488722947967,[18.0]],[1488722948070,[15.0]],[1488722948181,[17.0]],[1488722948387,[19.0]],[1488722948496,[18.0]],[1488722948902,[20.0]],[1488722949005,[17.0]],[1488722949113,[19.0]],[1488722949529,[17.0]],[1488722950339,[19.0]],[1488722950339,[18.0]],[1488722950458,[19.0]],[1488722950649,[18.0]],[1488722951284,[17.0]],[1488722951393,[19.0]],[1488722951498,[17.0]],[1488722952310,[18.0]],[1488722952540,[17.0]]]},"proximity":{"unit":"cm","data":[[1488722952757,[100.0]]]},"gravity":{"desc":["Gx","Gy","Gz"],"unit":"m/s²","data":[[1488722952757,[7.117117,-1.9445211,-3.5409317]]]},"lin_accel":{"desc":["LAx","LAy","LAz"],"unit":"m/s²","data":[[1488722912833,[-51.74674,-33.317753,-70.73735]],[1488722952757,[2.66992,1.8562613,3.727258]]]},"rot_vector":{"desc":["x*sin(θ/2)","y*sin(θ/2)","z*sin(θ/2)"],"unit":"","data":[[1488722912833,[-0.111434415,-0.3645942,-0.65359133]],[1488722952757,[0.7357932,-0.41826934,0.5160134]]]}}

**Comment by gizmocuz** [comment]
You can send me PM on the forum with the URL, i can then check if it is receiving it correctly

**Comment by gizmocuz** [comment]
Thanks for the link, confirmed, there is no problem. probably printing 1 line with 2600+ characters is... but i do not consider this as a problem
