### ISSUE TITLE
Latest versions got error RelayNet.cpp.o

### ISSUE THREAD

**Issue by zuidwijk** [domoticz/domoticz#1306]
From https://github.com/domoticz/domoticz
   b291587..abacb53  master     -> origin/master
   5eb8cd5..d807d71  Python-Plugins -> origin/Python-Plugins
Updating b291587..abacb53
....
[ 59%] Building CXX object CMakeFiles/domoticz.dir/hardware/RelayNet.cpp.o
/home/marcel/domoticz/hardware/RelayNet.cpp: In member function ‘virtual bool RelayNet::WriteToHardware(const char*, unsigned char)’:
/home/marcel/domoticz/hardware/RelayNet.cpp:230:31: error: ‘UNREFERENCED_PARAMETER’ was not declared in this scope
  UNREFERENCED_PARAMETER(length);
                               ^
CMakeFiles/domoticz.dir/build.make:2606: recipe for target 'CMakeFiles/domoticz.dir/hardware/RelayNet.cpp.o' failed
make[2]: *** [CMakeFiles/domoticz.dir/hardware/RelayNet.cpp.o] Error 1
CMakeFiles/Makefile2:103: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
marcel@domoticz:~/domoticz$

**Comment by zuidwijk** [comment]
bool RelayNet::WriteToHardware(const char *pdata, const unsigned char length)
{
        bool bOk = true;

        UNREFERENCED_PARAMETER(length);

#if RELAYNET_USE_HTTP

        bOk = WriteToHardwareHttp(pdata);

#else

        bOk = WriteToHardwareTcp(pdata);

#endif

        return bOk;
}

**Comment by gizmocuz** [comment]
I think this is already fixed

**Comment by VMF214** [comment]
same for me.
Have you a solution to fix it?
UPDATE:
ok git pull resolved it for me. Thanks!

**Comment by zuidwijk** [comment]
Yup, solved!
