### ISSUE TITLE
MainWorker::m_wind_calculator not feeded

### ISSUE THREAD

**Issue by gaudryc** [domoticz/domoticz#131]
Are you aware that the attribute MainWorker::m_wind_calculator is not feeded ?

Did I miss something ?

**Comment by gizmocuz** [comment]
it is:

mainworker.h(134):  std::map<unsigned short, _tWindCalculationStruct> m_wind_calculator;
mainworker.cpp(2506):dDirection=m_wind_calculator[windID].AddValueAndReturnAvarage(dDirection);

**Comment by gaudryc** [comment]
But this line gets something from the map ?
Where is the line to put something in the map ?

Am I too tired ? ;-)

**Comment by gizmocuz** [comment]
hehe, maybe ;) it calls a function that returns a value as well,
function is labeled

"Add Value" ... And ... "Return Avarage"

**Comment by gaudryc** [comment]
I think I need to take a look to the documentation because I am not used to
this kind of syntax.

I thought :

Std::map<A,B> m;
C c = m[a].toto(y);

Was equal to :

Std::map<A,B> m;
B b = m[a];
C c = b.toto(y);

There is no modifier call on the map here, only access call.
I don't understand anything.

**Comment by gizmocuz** [comment]
Its not that complicated, but maybe write a HelloWorld.cpp and test it

**Comment by gaudryc** [comment]
Yep I have to test it ;-)

**Comment by gizmocuz** [comment]
Later (another milestone version) we could use kind of the same technique for other sensors (temp/power/...) to calculate the min/max/avr in the shortlog interval

**Comment by gaudryc** [comment]
I made my HelloWorld program.
You are right.
All of my colleagues are amazed of this behavior but it is described in the  documentation of std::map.

We are too old... ;-)

Sorry for the inconvenience.
You can close this critical issue now.
