### ISSUE TITLE
Mysensors dimmer has only 16 steps

### ISSUE THREAD

**Issue by LemarinelNet** [domoticz/domoticz#1312]
Domoticz v3.6478

I made some boards with MySensors v2.2.
Each board implements a dimmer, which allow for 0-100% values.

Domoticz see them as **Lighing 2** devices, which seems to be limited to 16 steps (according to forum).

I need 100 steps support.

Thanks !

**Comment by gizmocuz** [comment]
Then you need to create a patch that for dimmers domoticz will use the type pTypeGeneralSwitch

**Comment by LemarinelNet** [comment]
I'll try so !
If I succeed, I'll do a pull request ;)

**Comment by gizmocuz** [comment]
Thanks, please only do this for dimmers, not for other sensor types
People having dimmers will get new devices

**Comment by LemarinelNet** [comment]
Yes, that's what I was going to (try to) do :)

**Comment by LemarinelNet** [comment]
Hi,
I've made a patch for this issue. 
You now only have to merge it ;)

**Comment by gizmocuz** [comment]
Thanks, i made a small request there
