### ISSUE TITLE
MySensors : Allow printing of raw frames in log view

### ISSUE THREAD

**Issue by LemarinelNet** [domoticz/domoticz#1320]
When creating new nodes, we frequently need to debug them, and check what kind of message the gateway is receiving.

In Jeedom, there is a log view for received messages (undecoded)

I'd like to implement such a feature in domoticz.

There could be 2 ways of doing so, when log level is set higher to a specific level (ERROR ?) : 

- Write undecoded frames in Log output 
- or write undecoded frames to a log file.

If we decide to write messages to a log file (mysensors.log), how should the file name/path be set ?

I'm willing to write the patch ;)

**Comment by gizmocuz** [comment]
If you compile domoticz in debug mode, you should see more logging
If you want to debug your mysensors node, you should not debug with domoticz but with:
- The Arduino interface
- myscontroller (https://www.mysensors.org/controller/myscontroller)

You could also connect your gateway and debug this in the Arduino IDE, or the myscontroller

Making a second gateway that just snoops the traffic is also an option
