### ISSUE TITLE
Daily Power Notification with $value

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#1327]
P1 Smartmeter USB receives 2 values for different tariffs (Usage1 & Usage2).

When I send a "Daily" notification with $value only Usage1 is reported.

Should be the sum of Usage1 & Usage2.

**Comment by gizmocuz** [comment]
Please explain a bit more... how is this notification send, some screenshots

**Comment by ghost** [comment]
Usage1:
<img width="150" alt="screen shot 2017-02-26 at 10 17 33" src="https://cloud.githubusercontent.com/assets/7728338/23821634/f2b9ae50-0638-11e7-92ba-f77bda719928.png">

Usage2:
<img width="156" alt="screen shot 2017-02-26 at 10 24 02" src="https://cloud.githubusercontent.com/assets/7728338/23821632/f2b8a352-0638-11e7-9203-fc7aac25c2e9.png">

Notification settings:
<img width="685" alt="screen shot 2017-03-11 at 09 01 38" src="https://cloud.githubusercontent.com/assets/7728338/23821644/6cf32732-0639-11e7-9b28-4f4d5804cf31.png">

$value at midnight (for Daily Usage notification):
<img width="225" alt="screen shot 2017-02-26 at 10 22 44" src="https://cloud.githubusercontent.com/assets/7728338/23821633/f2b91b70-0638-11e7-8e70-8080e16b4e49.png">

**Comment by gizmocuz** [comment]
Hmmm in SQLHelper.cpp, line 5341 we have

```
				float musage=(total_real[0]+total_real[1])/EnergyDivider;
				m_notifications.CheckAndHandleNotification(ID, devname, devType, subType, NTYPE_TODAYENERGY, musage);
```

this should send the sum of both counters.... are you able to debug this ?

**Comment by gizmocuz** [comment]
i think it should read
total_real[0]+total_real[2]

**Comment by ghost** [comment]
I made this change to SQLHelper.cpp (do I need to do more to debug?), but we'll have to wait till midnight ;) And, I think in weekends only the tariff for Usage1 is used (Nuon) so we'll probably have to wait till monday as well.

(I'll remove this bug-report from the forum as well, added it there a while ago, but here is alot more workable :) )

<img width="938" alt="screen shot 2017-03-11 at 09 54 15" src="https://cloud.githubusercontent.com/assets/7728338/23821924/c73881a4-0640-11e7-88c5-a1e02c5f98c6.png">

**Comment by gizmocuz** [comment]
Okey, please let me know your findings ;)

**Comment by ghost** [comment]
So far, not so good, still reporting just the Usage1 value.

To be sure, I just changed:

```
 //Check for Notification
                        if (devType==pTypeP1Power)
                        {
                                float musage=(total_real[0]+total_real[1])/EnergyDivider;
                                m_notifications.CheckAndHandleNotification(ID, devname, devType, subType, NTYPE_TODAYENERGY, musage);
                        }
```
to:

```
 //Check for Notification
                        if (devType==pTypeP1Power)
                        {
                                float musage=(total_real[0]+total_real[2])/EnergyDivider;
                                m_notifications.CheckAndHandleNotification(ID, devname, devType, subType, NTYPE_TODAYENERGY, musage);
                        }
```

That is correct right? No need for additional actions?

**Comment by gizmocuz** [comment]
Thats correct!, Please create a pull request to make this change 100%

**Comment by gizmocuz** [comment]
Corrected it myself

**Comment by ghost** [comment]
👍 thanks. I know too little C to do this I'm affraid :(
