### ISSUE TITLE
domoticz_applyXpath and domoticz_applyJSONpath

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#1333]
These don't seem to function in regular Lua scripts, just in Lua_parsers.

**Comment by gizmocuz** [comment]
Some more info, examples, the problem ?

**Comment by Ittiz** [comment]
This LUA script:

local motionalert = domoticz_applyXPath(s,'//CGI_Result/motionDetectAlarm/text()')
local soundalert = domoticz_applyXPath(s,'//CGI_Result/soundAlarm/text()')

Works in Lua_parser scripts, but doesn't work as a regular Lua script using curl to fetch it.  I get an error in the log that says domoticz_applyXPath is nil.  However, I can still parse the data using str search and sub str functions so the data is there.  I assume domoticz_applyJSONpath has the same issue because those two functions always appear together in the code.

**Comment by gizmocuz** [comment]
Not into Lua... are you able to look into this on ?

**Comment by sbouchex** [comment]
@gizmocuz need help ?

**Comment by gizmocuz** [comment]
Maybe Ittiz, for me the best help is to google a lot about lua... but i might have a closer look at python ;)

**Comment by Ittiz** [comment]
The issue is I don't think the functions that allow you to use domoticz_applyXPath and domoticz_applyJSONPath are loaded for LUA scripts.  Only for LUA parser scripts using with HTTP/HTTPS polling.

**Comment by sbouchex** [comment]
That's exactly this, those 2 methods are not available to events but only for parsers. I will try to integrate them for both lua scripts kinds.

**Comment by Ittiz** [comment]
Thanks sbouchex, it'll make working with XML and JSON much easier.

**Comment by Ittiz** [comment]
I can gladly say this issue is now resolved.  sbouchex's change allowed me to rid my script of a bunch of costly subStr and strFind calls and get it down to one domoticz_applyXPath call!
