### ISSUE TITLE
Clang 4.0 issue.

### ISSUE THREAD

**Issue by xbeaudouin** [domoticz/domoticz#1348]
Seems we have some issues with Clang 4.0 compilation  : 

```
wrkdirs/usr/ports/www/domoticz/work/domoticz-3.5877/hardware/HarmonyHub.cpp:219:46: error: ordered comparison between pointer and zero ('void *' and 'int')
                                if (memset(m_databuffer, 0, BUFFER_SIZE) > 0)
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
/wrkdirs/usr/ports/www/domoticz/work/domoticz-3.5877/hardware/HarmonyHub.cpp:812:42: error: ordered comparison between pointer and zero ('void *' and 'int')
                if(memset(m_databuffer, 0, BUFFER_SIZE)>0)
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
2 errors generated.
*** Error code 1
```

Clang 4.0 is the compilator on upcomming FreeBSD 12.0.

Full log at : http://beefy11.nyi.freebsd.org/data/head-i386-default/p436115_s315218/logs/domoticz-3.5877_1.log

**Comment by gizmocuz** [comment]
Thats some funky code !

I am 99% sure this should be just a memset and no 'if'

I changed the code, tested it, and it's working correctly.

Looking at other places where a memset is done it looks like what i changed/fixed is correct

Now why a memset, and not just reading the socket data, and setting a zero at the position of the returned amount of bytes to terminate the string... i dont know

**Comment by gizmocuz** [comment]
(new code committed)
