### ISSUE TITLE
[Request] Update for Youless LS120

### ISSUE THREAD

**Issue by mbnn** [domoticz/domoticz#1349]
Hello,

Youless has a new version available, the LS120 which has a P1 port and measures gas and electricity at the same time. Could we please get support for this in Domoticz?

http://wiki.td-er.nl/index.php?title=YouLess#P1_status_info
http://youless.nl/blogpost/items/nieuw-model-ls120.html 

Another note, when electricity goes into the - (when more power is coming in due to solar panels), right now big numbers show up for Youless devices. This is fine with P1 USB cables.

**Comment by gizmocuz** [comment]
Please do not cross post.
Why not using a P1 usb cable to domoticz ? Do you need the YouLess at all if you have a smart meter?

**Comment by mbnn** [comment]
Implemented :)

**Comment by gizmocuz** [comment]
Hope it works
