### ISSUE TITLE
ziblue rfplayer implementations

### ISSUE THREAD

**Issue by neogta** [domoticz/domoticz#1368]
Hello,
I'm a new rfplayer RFP1000 owner which has been in the code for a while, looking at "hardwares" rfplayer has been "present" in ZiBlueBase.cpp and ziblue_usb_frame_api.h since october by @gizmocuz 

I'm wondering if / when / how I could call the following protocol defined in the forementionned file : 
                { 1, "VISONIC_433" },
                { 2, "VISONIC_868" },
                { 3, "CHACON_433" },
                { 4, "DOMIA_433" },
                { 5, "X10_433" },
                { 6, "X2D_433" },
                { 7, "X2D_868" },
                { 8, "X2D_SHUTTER_868" },
                { 9, "X2D_HA_ELEC_868" },
                { 10, "X2D_HA_GAS_868" },
                { 11, "SOMFY_RTS_433" },
                { 12, "BLYSS_433" },
                { 13, "PARROT_433_OR_868" },
                { 14, "reserved" },
                { 15, "reserved" },
                { 16, "KD101_433" },
                { 0, NULL }

Meaning, I need an on/off switch to called "PARROT" protocol on A/1 address, is this doable or needs to be implemented ? 

(automatic detection mis detect the type) 

thanks for the great work on this project and let me know how I can help (debug logs / testing / etc.) ! 
Regards,
Younes

**Comment by deennoo** [comment]
Same for me please, X2D implentation is a great feature and open doors to many system who are already installed !

**Comment by gizmocuz** [comment]
I have to continue integrating this hardware.
I suspect your lights should already work...
I stopped development since at that time KaKu/AC/ARC was not working correctly
Hope to pick it up as soon as possible

**Comment by neogta** [comment]
Little update,
1) my switch does not work from Domoticz.

this beeing said,
2) Without adding switch in domoticz : 
a) when I turn on the switch with "official remote" I get in DEBUG log : 
```
2017-03-21 15:24:07.740  ZiBlue: frameType: 1, frequency: 433920 kHz
2017-03-21 15:24:07.741  ZiBlue: rfLevel: -41 dBm, floorNoise: -100 dBm, PulseElementSize: 1
2017-03-21 15:24:07.741  ZiBlue: number: 47, Repeats: 0, Delay: 0, Multiply: 40
```

b) when I turn off the switch with "official remote" I get in DEBUG log : 
```
2017-03-21 15:24:09.697  ZiBlue: frameType: 1, frequency: 433920 kHz
2017-03-21 15:24:09.697  ZiBlue: rfLevel: -41 dBm, floorNoise: -100 dBm, PulseElementSize: 1
2017-03-21 15:24:09.698  ZiBlue: number: 47, Repeats: 0, Delay: 0, Multiply: 40
```

3) in Learning mode : 
```
2017-03-21 15:26:45.637  New sensors allowed for 5 minutes...
2017-03-21 15:26:48.918  (rfplayer) Light/Switch (Unknown)
2017-03-21 15:26:48.925  ZiBlue: frameType: 1, frequency: 433920 kHz
2017-03-21 15:26:48.926  ZiBlue: rfLevel: -46 dBm, floorNoise: -99 dBm, PulseElementSize: 1
2017-03-21 15:26:48.926  ZiBlue: number: 49, Repeats: 0, Delay: 0, Multiply: 40
```

If i press the button in Domoticz, which does not work, log tells me : 
```
2017-03-21 15:26:59.467  User: Admin initiated a switch command (79/Prise Dehors/On)
2017-03-21 15:26:59.468  (rfplayer) Light/Switch (Prise Dehors)
2017-03-21 15:27:01.663  User: Admin initiated a switch command (79/Prise Dehors/Off)
2017-03-21 15:27:01.664  (rfplayer) Light/Switch (Prise Dehors)
```
No ZiBlue ligne :(

4) manual mode does NOT contain the correct subtype (PARROT)

5) finally, from RFPlayer Configurator : 
Remote On : 
```
ZIA44 FRAME: frameType: 0, cluster: 0, dataFlag: 0, 
rfLevel: -41dBm, floorNoise: -99dBm, rfQuality: 10
protocol: 6 (DOMIA), infoType: 0, frequency: 433920Khz
subType: 0, id: 1  (OFF, A1)
```
Remote Off : 
```
ZIA44 FRAME: frameType: 0, cluster: 0, dataFlag: 0, 
rfLevel: -46dBm, floorNoise: -100dBm, rfQuality: 10
protocol: 6 (DOMIA), infoType: 0, frequency: 433920Khz
subType: 0, id: 0  (OFF, A1)
```

Parrot On : 
`ZIA++ON PARROT A1`

Parrot Off : 
`ZIA++OFF PARROT A1`

Regards,
Younes

**Comment by gizmocuz** [comment]
Yep, it needs more time and development, if you can help, great !

**Comment by neogta** [comment]
Hello,
just for information, I'm not a C developper at all, I script / php / etc. but no C.
I can read and understand most of the code but I'm not sure I can bring anything in the Dev process.

This beeing said, I'd be happy to test and debug if needed,
Younes

**Comment by stuntteam** [comment]
The number of protocols supported by the device itself is really limited and it appears that there are no plans to expand this..

**Comment by gizmocuz** [comment]
AC/ARC is also not very good supported... actually can't receive it... (but working in their testlab)
X10 reception is also not 100%
@stuntteam, is this in cooperation with you guy's ? as they mention RF_Link ? Or did they use a wrong word ;)

**Comment by neogta** [comment]
@stuntteam limited ? it's the device that support the most of protocols :) 433 and 868 mhz frequency.
Indeed, it seems AC/ARC were left out.
BUT since AC/ARC is a 433mhz, PARROT function might work with this protocol :)

RFlink is mentionned in the interface, the device can "decode" rflink

**Comment by gizmocuz** [comment]
@neogta , come on ! it's at the moment the device that supports the least hardware
You can absolutely not compare RFLink or RFXCom with this device, they support way more, and they work also good!

Maybe after some time this is going to be also another great piece of hardware...

The biggest problem, no support from development over there... I'm stuck, won't get it to work... got the device already months ago

Asked them to support there own implementation in Domoticz, like RFLink does, this seems to be a great combination as new protocols are supported directly in Domoticz
(No reaction, maybe the code is not made in house... )

**Comment by stuntteam** [comment]
In my opinion the main issue is that the cpu load is at 100% and they wont add more protocols they told me. Parrot does not work with many popular devices. 
Also: RTS only the basic protocol is supported.. RFlink does 2 newer flavors.
X2D: does not work with the thermostat I have been testing. (RFLink has X2D now too..)

**Comment by neogta** [comment]
Well we learn everyday ... I got caught by their commercials on many home automation oriented sites on what was the new revolution hardware to control everything with any software ...

The fact that development does not provide support is a real issue indeed, they should spend some time with all the implementer who needs it if they want their device to success.

Indeed, their implementation would be ideal but like you say, I decompiled their jar file on my free time and I'm having doubts on who the developper are.

**Comment by stuntteam** [comment]
@gizmocuz: Nope, we have no relation to RFPlayer. 

@neogta "it's the device that support the most of protocols :) 433 and 868 mhz frequency.
Indeed, it seems AC/ARC were left out."
Our RFlink Gateway is the device that supports most protocols and has 433, 868 and 2.4Ghz. RFplayer only supports the ones you listed and those not even properly. Also, RFPlayer costs 149 euros.. rflink you can toss together for 10 euros (including arduino and decent RF modules) and the software is free!

**Comment by gizmocuz** [comment]
I close this issue as the manufacturer does not seem to find out an issue
