### ISSUE TITLE
zwave timeouts on al devices after update to v3.6944

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#1384]
I was stable running on v3.6500
i upgraded to V6944 because i heared the alarm secure message on the FGMS001 device was gone  after release v3.6935.

upgraded fine with no apparent problems(do not know if i had timeouts during this version)
after that i upgraded to DSM v 6.1 and also upgraded to domoticz V3.6953/6959

i now have timeouts on al my devices
i have polling enabled on al my devices because otherwise the powerstatus and usage(kWh) gets screwed up.
when i disable polling the timeouts stop but so dos the accurate updates of my devices

current setup
synology DSM 6.1
domoticz V3.6959 (Jumbotroll package)
Aeotec ZW5 stick
2x Fibaro FGWPE101 zw5
1x fibaro FGD212 dimmer ZW5
1x FGMS001 zw5
1x Qubino ZMNHADx relay module with temp sensor.

may the change what cause the alarm secure message to dissapear is responsible for the timeouts appearing.

i was told DSM6.1 is using the same usb drivers as v6.0 so i doubt dsm 6.1 is causing the problem.

please let me know if i need to provide any files

**Comment by szczukot** [comment]
Do you use other modules like  Satel Integra or Logitech or OpenWeatherMAp ?

**Comment by GravityRZ** [comment]
No
Only modules from fibaro and 1 qubino

The reason i have polling on is the kwh meters from those modules fluctuate(watt value goes to zero sometimes) without polling

Qubino needs polling on because of the temperature sensor

**Comment by gizmocuz** [comment]
Do discuss this on the forum
