### ISSUE TITLE
log settings changed after v3.7067

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#1387]
just installed v7067, hopefully that my timeout problem  would be gone.
well it is not

instead somebody mixed up the log settings.

all the data which normally appears in the ALL tab now appears in the ERROR tab in red.

all tab: completely empty
status tab:logs the status and shows timeouts in RED
error tab:shows all the timeouts in RED.

**Comment by szczukot** [comment]
i have this same problem after this commit 
https://github.com/domoticz/domoticz/commit/501a743973d4f7388f8d7fc7b07fee585b563ea8
tab ERROR and ALL are swapped

**Comment by Siewert308SW** [comment]
Strange,
Pi3, Jessie 8 and Domo 7067 with out those issues.

**Comment by Zuikkis** [comment]
I also had this, but clearing  browser cache helped.

**Comment by Zuikkis** [comment]
File www/app/LogController.js  has changed. Also you probably need to refresh the browser cache..

**Comment by GravityRZ** [comment]
refreshed browser and log tabs seems to be back to normal

this is the first time i needed to do this

**Comment by gizmocuz** [comment]
Yep, its because the appcache version number was not increased, will do so on a next commit
