### ISSUE TITLE
I tryed to compile for Openwrt and issue with error: 'atoi' was not declared in this scope

### ISSUE THREAD

**Issue by kofec** [domoticz/domoticz#1389]
There was a fix for this 
https://github.com/domoticz/domoticz/commit/3c744591280ede535c5bc4ca56add2a5b7261e3d

but by another commits was removed.

Current issue:
make[6]: Leaving directory '/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz'
[ 14%] Built target lua
make[6]: Entering directory '/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz'
make[6]: Leaving directory '/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz'
[ 22%] Built target mqtt
make[6]: Entering directory '/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz'
make[6]: Leaving directory '/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz'
make[6]: Entering directory '/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz'
[ 23%] Building CXX object CMakeFiles/domoticz.dir/hardware/openwebnet/bt_openwebnet.cpp.o
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp: In static member function 'static std::__cxx11::string bt_openwebnet::getWhatDescription(const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&)':
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1143:37: error: 'atoi' was not declared in this scope
   int scenNumber = atoi(what.c_str());
                                     ^
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1419:32: error: 'atoi' was not declared in this scope
   int iWhat = atoi(what.c_str());
                                ^
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1609:33: error: 'atoi' was not declared in this scope
    int iWhat = atoi(what.c_str());
                                 ^
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1674:32: error: 'atoi' was not declared in this scope
   int iWhat = atoi(what.c_str());
                                ^
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1735:32: error: 'atoi' was not declared in this scope
   int iWhat = atoi(what.c_str());
                                ^
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1928:51: error: 'atoi' was not declared in this scope
     int profileID = atoi(whatParameters[0].c_str());
                                                   ^
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp: In static member function 'static std::__cxx11::string bt_openwebnet::getWhereDescription(const string&, const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&)':
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp:2023:40: error: 'atol' was not declared in this scope
    long lMacAddr = atol(macAddr.c_str());
                                        ^
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp:2029:25: error: 'atoi' was not declared in this scope
    if (atoi(unit.c_str()) == 0) {
                         ^
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp:2082:30: error: 'atoi' was not declared in this scope
         if (atoi(what.c_str()) == 11 ){
                              ^
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp:2167:40: error: 'atoi' was not declared in this scope
    int iWhere = atoi(whereRight.c_str());
                                        ^
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp:2193:25: error: 'atoi' was not declared in this scope
   if (atoi(where.c_str()) == 0) {
                         ^
/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/openwebnet/bt_openwebnet.cpp:2224:33: error: 'atoi' was not declared in this scope
     int amb = atoi(begin.c_str());
                                 ^
CMakeFiles/domoticz.dir/build.make:2174: recipe for target 'CMakeFiles/domoticz.dir/hardware/openwebnet/bt_openwebnet.cpp.o' failed
make[6]: *** [CMakeFiles/domoticz.dir/hardware/openwebnet/bt_openwebnet.cpp.o] Error 1
make[6]: Leaving directory '/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz'
CMakeFiles/Makefile2:107: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[5]: *** [CMakeFiles/domoticz.dir/all] Error 2
make[5]: Leaving directory '/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz'
Makefile:149: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz'
Makefile:71: recipe for target '/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/.built' failed
make[3]: *** [/home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/.built] Error 2
make[3]: Leaving directory '/home/kofec/openwrt/LEDEraspberry/package/domoticz'
package/Makefile:105: recipe for target 'package/domoticz/compile' failed
make[2]: *** [package/domoticz/compile] Error 2
make[2]: Leaving directory '/home/kofec/openwrt/LEDEraspberry'
package/Makefile:101: recipe for target '/home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/stamp/.package_compile' failed
make[1]: *** [/home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/kofec/openwrt/LEDEraspberry'
/home/kofec/openwrt/LEDEraspberry/include/toplevel.mk:197: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by gizmocuz** [comment]
We use atoi in lots of source files...
I see what is going on here... the author forgot to include a file...
Please try the new commit
https://github.com/domoticz/domoticz/commit/613cd0e70fcef358dee732591b30a84f2f3c21d1

**Comment by kofec** [comment]
Thanks a lot for very quick fix. I close the ticket:

[ 56%] Building CXX object CMakeFiles/domoticz.dir/hardware/OpenWebNetTCP.cpp.o
[ 57%] Building CXX object CMakeFiles/domoticz.dir/hardware/OpenWebNetUSB.cpp.o
In file included from /home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/usr/include/boost/asio/detail/socket_types.hpp:61:0,
                 from /home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/usr/include/boost/asio/detail/epoll_reactor.hpp:30,
                 from /home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/usr/include/boost/asio/detail/reactor.hpp:21,
                 from /home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/usr/include/boost/asio/detail/impl/task_io_service.ipp:24,
                 from /home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/usr/include/boost/asio/detail/task_io_service.hpp:198,
                 from /home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/usr/include/boost/asio/impl/io_service.hpp:71,
                 from /home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/usr/include/boost/asio/io_service.hpp:767,
                 from /home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/usr/include/boost/asio/basic_io_object.hpp:19,
                 from /home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/usr/include/boost/asio/basic_socket.hpp:20,
                 from /home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/usr/include/boost/asio/basic_datagram_socket.hpp:20,
                 from /home/kofec/openwrt/LEDEraspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/usr/include/boost/asio.hpp:21,
                 from /home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/ASyncSerial.h:6,
                 from /home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/OpenWebNetUSB.h:4,
                 from /home/kofec/openwrt/LEDEraspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/domoticz/hardware/OpenWebNetUSB.cpp:10:
/home/kofec/openwrt/LEDEraspberry/staging_dir/toolchain-arm_arm1176jzf-s+vfp_gcc-5.4.0_musl-1.1.16_eabi/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
 #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
  ^
[ 57%] Building CXX object CMakeFiles/domoticz.dir/hardware/openwebnet/bt_openwebnet.cpp.o
[ 57%] Building CXX object CMakeFiles/domoticz.dir/hardware/OpenZWave.cpp.o
[ 58%] Building CXX object CMakeFiles/domoticz.dir/hardware/openzwave/control_panel/ozwcp.cpp.o
