### ISSUE TITLE
Remote server: Error: input buffer out of sync, going to restart!....

### ISSUE THREAD

**Issue by LKapie** [domoticz/domoticz#1391]
Tested with latest version 3.7078 with the following setup:

Raspi with RFlink, 1-Wire, Evohome, GPIO, HUE
Windows 10 with S0 meter USB

Raspi reads energy counters from windows system via Domoticz-remote server. 
With update to latest version (on both systems) log on Raspi system shows error:
"Error: input buffer out of sync, going to restart!...." 

No reference to hardware so at first I disabled RFlink without result.
Als disabling 1Wire, GPIO or HUE did not remove the error.

Only until I disabled remote server the error was gone so it seems it's related to Domoticz-remote server.

Logs don't show relevant information according to me so not included. I can of course do more testing or provide more info if required.

**Comment by gizmocuz** [comment]
Please use our forum, you might want to consider looking for our 'persistent devices' page on our wiki

**Comment by LKapie** [comment]
Dear @gizmocuz ,
I checked the forum and the page about 'persistent devices' before I raised the issue but my impression is that this error/message is not valid in my situation:
- My understanding is that 'persistent devices' errors occur for local devices like for example USB ports.
- In my case the windows system where the local S0 usb device resides is functioning correctly and not throwing errors in the log.
- On the Raspi system where the errors occur the cause seems to be the Domotics-remote server (switching it off removes the error from the log) which is addressed by the IP address of the remote machine.
If you expect or are sure the issue is caused by 'persitency' I hope you can explain a bit so I have a clue how to fix it...

**Comment by gizmocuz** [comment]
Okey, now i understand, it's a master/slave issue
We recently added 64 extra characters in the general device structure
did you update both systems to the same version ? this is very imporant

**Comment by gizmocuz** [comment]
I see the problem, the RX buffer size is 40 bytes,  this is not enough

**Comment by LKapie** [comment]
Ok thnx. If you let me know when it's in the build I can/will test.

**Comment by LKapie** [comment]
See discussion about this error also on the forum but you will be aware of it:
[http://www.domoticz.com/forum/viewtopic.php?f=6&t=16727&start=20](url)

**Comment by gizmocuz** [comment]
Should be solved with version 7112 (or higher) available now

**Comment by LKapie** [comment]
Running 3.7113 for almost an hour on raspi and windows with domoticz-remote server "on" without any problem or error. Issue is fixed and can be closed as far as I'm concerned.

**Comment by gizmocuz** [comment]
Great, thanks for testing !
