### ISSUE TITLE
MySensors heartbeat not handled

### ISSUE THREAD

**Issue by LemarinelNet** [domoticz/domoticz#1396]
Some of my sensors doesn't send status back, or rarely (i.e. heaters, I send them a new target value, but they don't send replies).
To circumvent the "last seen" which then go bad, I decided to use the mysensors sendHeartBeat function.
It sends an internal message, the gateway recognize it but domoticz don't.

I've took a look at the code, but I can't figure out what's wrong ?

**Comment by gizmocuz** [comment]
I suggest to compile in debug mode (and suggest to use VS2017)
Next set some breakpoints, specifically on line 1629
Or in the function UpdateNodeHeartbeat
You should see also what is received, a log of this would maybe also explain things

**Comment by LemarinelNet** [comment]
I'm not on windows, so I will use Eclipse to debug it.
I've put some debug logs to try, I've just seen that the UpdateNodeHeartbeat function is called, but there's something wrong inside the iterators...

**Comment by gizmocuz** [comment]
Great! (i mean... Eclipse... not the iterator problem of course)
If there is a problem, hope you can find it and make a fix for it

**Comment by oohlaf** [comment]
Might not be related to this, but I see the following compiler warnings in this module:
```
[ 51%] Building CXX object CMakeFiles/domoticz.dir/hardware/MySensorsBase.cpp.o
/home/olaf/src/domoticz/hardware/MySensorsBase.cpp:26:10: warning: enumeration value 'V_UNKNOWN' not handled in switch [-Wswitch]
        switch (vType)
                ^
/home/olaf/src/domoticz/hardware/MySensorsBase.cpp:149:10: warning: enumeration values 'S_GPS', 'S_WATER_QUALITY', and 'S_UNKNOWN' not handled in switch [-Wswitch]
        switch (pType)
                ^
/home/olaf/src/domoticz/hardware/MySensorsBase.cpp:492:13: warning: 46 enumeration values not handled in switch: 'V_TEMP', 'V_HUM', 'V_PRESSURE'... [-Wswitch]
                                switch (vType)
                                        ^
/home/olaf/src/domoticz/hardware/MySensorsBase.cpp:582:10: warning: 17 enumeration values not handled in switch: 'V_RAINRATE', 'V_HVAC_FLOW_STATE', 'V_HVAC_SPEED'... [-Wswitch]
        switch (vType)
                ^
/home/olaf/src/domoticz/hardware/MySensorsBase.cpp:2088:11: warning: 26 enumeration values not handled in switch: 'S_WIND', 'S_RAIN', 'S_UV'... [-Wswitch]
                switch (pType)
                        ^
5 warnings generated.
```

**Comment by gizmocuz** [comment]
This is not related, and these warnings are valid, but could be ignored

**Comment by gizmocuz** [comment]
Could be around the switch case 492, i am only handling the heartbeat for the following value types:

				case V_TRIPPED:
				case V_ARMED:
				case V_LOCK_STATUS:
				case V_STATUS:
				case V_PERCENTAGE:
				case V_SCENE_ON:
				case V_SCENE_OFF:
				case V_UP:
				case V_DOWN:
				case V_STOP:
				case V_RGB:
				case V_RGBW:

Maybe we miss some... it could be a complicated issue to support all types, as for all types we should recover the IDX in the database, or we should remember this...

**Comment by LemarinelNet** [comment]
That's why I proposed to refactor the IDX formatting (sometime %X%02X%02X%02X, sometime %02X%02X%02X...), because I don't see any reason for different sensors  to have different IDX format !?
Having only one kind of IDX (just integer, no formatting), would simplify heartbeat handling : just update the nodes with Idx=ID on WHERE clause !

I just pushed a commit on MySensorBase.cpp for this modification, I now have to make an update script in SQLHelper to move all old IDX to new ones.

**Comment by gizmocuz** [comment]
Thanks... but it's not so easy...
Did you finished the conversion script ?

**Comment by LemarinelNet** [comment]
Yes, I must test it... Missing free time at the moment :(

**Comment by nekitoss** [comment]
@gizmocuz 
Did i understand correctly - at the moment when node calls sendHeartbeat() - domoticz will do nothing?
Is "last seen" for node and childs independent? (Can last seen for **node** be updated if no data from **childs** were sent? For example: in leakage sensors if i have only one child (send alarm only if leak detected), but i need to know that it is still alive and protects me, so i need update last seen of node without updating child last time (so i can see when last leak was detected))
Looking at "switch case 492"  - did i understood correctly: only if one of these types were send from node to controller then "last seen" of node and those child in domoticz will be updated?

Also tested
```
sendBatteryLevel(97, true);
wait(3000);
```
with (data changing every send) _and_ without any sensors no battery data appeared in devices tab. Did i something wrong?
**UPD**:somehow battery level appeared. possibly i was using sensor not in switch list...

In all cases (heartbeat also) i see the data in MYSController sniffer. Without sending some sensor data, but with heartbeat or batterylvl domoticz updates last seen only at presentation.
