### ISSUE TITLE
HTTPS notification "failed" but in fact not

### ISSUE THREAD

**Issue by Markourai** [domoticz/domoticz#14]
Hi, 
I'm using the Custom HTTP/Action with my mobile provider setting and what happened is that the notification works but domoticz said that it failed "Error: Notification sent (http) => Failed".

Mobile provider URL:
https://smsapi.free-mobile.fr/sendmsg?user=#FIELD1&pass=#FIELD2&to=#TO&msg=#MESSAGE

Domoticz version is 2778

**Comment by gizmocuz** [comment]
Could it be that nothing is returned ? I made a patch that this will be ok for the HTTP notification system, and it will be in the next beta

**Comment by gizmocuz** [comment]
Should be fixed now

**Comment by Markourai** [comment]
I will try it. Thank you.
For information, here is what the provider said about the HTTP response code.

```
200 : SMS sent.
400 : One mandatory parameter is missing.
402 : Too many SMS sent in a short time.
403 : Service is not enable or wrong login/password.
500 : Server side error. Try again later.
```

**Comment by Markourai** [comment]
It works. Thank you.
