### ISSUE TITLE
Using clang as compiler on Linux (Raspberry Pi3) shows a lot of warnings

### ISSUE THREAD

**Issue by oohlaf** [domoticz/domoticz#1403]
Have a look at the full output at http://paste.debian.net/924191

Issue summary:

1.  A lot of switch statements have missing cases and/or no default to catch them. That leads to potential errors that might be difficult to debug.
```
/home/olaf/src/domoticz/hardware/HEOS.cpp:931:14: warning: 102 enumeration values not handled in switch: 'HTYPE_RFXtrx315', 'HTYPE_RFXtrx433', 'HTYPE_RFXLAN'... [-Wswitch]
                                        switch (hType) {
```
2.  For loops that should be while loops in several places
```
/home/olaf/src/domoticz/hardware/AnnaThermostat.cpp:341:8: warning: expression result unused [-Wunused-value]
                for (pElem; pElem; pElem = pElem->NextSiblingElement())
```
3.  Missing parenthesis when combining bitwise operators that have the same precedence level
4.  Variable access is not deterministic across compiler implementations when combining multiple post-fix operators on the same variable in one statement. Depending on the compiler the variable access might be different leading to difficult to debug issues.
```
/home/olaf/src/domoticz/hardware/MochadTCP.cpp:489:42: warning: multiple unsequenced modifications to 'j' [-Wunsequenced]
        m_mochadsec.SECURITY1.id1 = (hex2bin(p[j++]) << 4) | hex2bin(p[j++]);

```
5.  Not sure about this one, need to google why this is not recommended.
```
In file included from /home/olaf/src/domoticz/hardware/plugins/Plugins.cpp:12:
/home/olaf/src/domoticz/hardware/plugins/PythonObjects.h:27:18: warning: offset of on non-POD type 'CImage' [-Winvalid-offsetof]
                { "ID", T_INT, offsetof(CImage, ImageID), READONLY, "Domoticz internal Custom Image Number" },
                               ^                ~~~~~~~
```

I'll try to fix some of the warning in my branch, but adding default rules to the various switch statements needs someone with knowledge of the particular module.

**Comment by gizmocuz** [comment]
Sometimes you know 99,9% sure that only 2 switch statements are going to happen.
Warnings that defaults (or the others) are not handled (like on a default OSX compiler) is not something i agree with.
For example, you made a hardware plugin, and you supply two switch types.
No need to add defaults for this.
Can only go wrong with people are playing directly in the database, but even then it will go correct because only two are handled.
Going to try to compile with clang as well, thanks for the help!

**Comment by gizmocuz** [comment]
Compiled with CLang, made some modifications already
