### ISSUE TITLE
MySensors S_WATER / V_VOLUME not handled correctly

### ISSUE THREAD

**Issue by seant100** [domoticz/domoticz#1404]
Domoticz is picking up a MySensor sensor with S_Water/V_Volume as an RFX Meter with counter. S_WATER / V_VOLUME should display as a fixed volume (no counter) in Litres or perhaps other units applicable to water volume.

**Comment by gizmocuz** [comment]
No, this is correct.
There was no need to create an additional meter, that is why we are reusing this type
