### ISSUE TITLE
BME280 Faulty Humidity reading

### ISSUE THREAD

**Issue by Roselt** [domoticz/domoticz#1410]
Connected the BME280 to the Raspberry Pi GPIO. The pressure and temperature readinga are correct but the humidity reading is showing 71% but when I connect the exact same sensor to my ESP8266 it shows 41% which is the correct value compared to other sensors I've got.

I am running the latest beta Domoticz V3.7153.

**Comment by gizmocuz** [comment]
Please try first with a python test application to see what values this returnes

**Comment by gizmocuz** [comment]
No feedback received... did you test with the python script... do we need a change ? was there a problem, or an false alarm ?

**Comment by Roselt** [comment]
Sorry for only replying now.  I did test with a python script and the reading was working. 
I updated Domoticz to the latest beta just now and the reading is correct now.

**Comment by gizmocuz** [comment]
Nothing to do with the beta, code has not been changed since the first commit
Great it's working for you now

**Comment by bdwilton** [comment]
I had this issue on first connection to the BME280 sensor, Domoticz was showing 64% humidity while the python script was returning 44-45%.  Issue stayed until I did a stop / start of domoticz.

**Comment by gizmocuz** [comment]
you should not mix python and domoticz

**Comment by bdwilton** [comment]
hi gizmocuz, yes I should have explained better.  I installed BME280 in domoticz but humidity was too high compared to other sensors in the house.  So I stopped domoticz and ran the python script I had which I initially used to check that the sensor was working.  The python returned a similar humidity to the rest of the house.  I then restarted domoticz and it was now reading the correct value.  So not running python on domoticz i2c at the same time.
Just thought I would say the circumstance or how it happened for me, then what seemed to get it working correctly.

**Comment by gizmocuz** [comment]
Looks like an initialisation error... when you powerdown the pi (unplug the adapter) for 10 seconds and restart, do you have a correct reading ?
I am not a big van of the I2C class at all... i would recommend to have a look at 'MySensors'

**Comment by bdwilton** [comment]
Just did a shutdown and no issue with it at all.  It has worked fine without issue apart for the instance it was first added to the hardware.  So after adding the sensor it was producing a high value.  After any restart of the software it has not had any issues.

**Comment by Roselt** [comment]
@gizmocuz This issue is still there. I see someone else also raised it again in the forum http://www.domoticz.com/forum/viewtopic.php?f=6&t=19605

Everytime I recycle power to the PI, I have to run the python test script to get the correct value on Domoticz. I have now added the test script to my PI start-up to make sure I get the correct value. So it seems there is an issue with the sensor initialization in Domoticz.

**Comment by gizmocuz** [comment]
Please have a look in the code, else as mentioned, use mysensors.org

**Comment by 523p** [comment]
BME280 itself is not accurate sensor. Huge compensations are needed with measuring. Mostly on humidity. It is pitty, there si no humidity compensation in Domoticz (just temp offset).
