### ISSUE TITLE
Standard ID attribution

### ISSUE THREAD

**Issue by LemarinelNet** [domoticz/domoticz#1412]
I see that DeviceID attribution is "messy".
Sometimes, the Child ID is included in Device ID, sometimes not.
Wouldn't it be easier to have te same rule everywhere ?
That's annoying for MySensors, which presents different kinds of child for the same node, so the same node can have multiple DeviceID depending of childs (i.e. 00000208 for node 2, child 8 of kind S_TEXT, and 00000002 for the same node, with child 1 of kind DIMMER....)

I can't see any reason why the ChildID is not always set in the Unit column (sometimes put in the DeviceID with constant "1" unit, sometimes in the Unit...)

I'm ok to work on this refactoring, but I need beta-testers, since it can break a lot of things !

**Comment by travellingkiwi** [comment]
One of my top two biggest gripes is this very issue. I'm happy to work with you on this one.

**Comment by LemarinelNet** [comment]
I've made a small search in the code to see all DeviceID formatting. There is a lot of them, but only a few do use ChildID in ID generation.
At first, the highest priority I see is in the hardware/DomoticzHardware.cpp whhere childId is used. These functions are used for others plugins, and precisely MySensors, which is why I need to refactor it.

I'll start by modifying only this one for the moment.

**Comment by DebugBill** [comment]
I also faced this issue and tried to fix it for the Sensor Alert. I quickly step back as it broke upward compatibility. My new sensors where created with a nicely formated ID, but when old sensors where updated it would in fact create a new one with the new ID and leave the old one unattended. This meant all past data was "lost". Users reacted quite negatively (and I understand it).

The Gizmocus suggested that I write a database upgrade script to "convert" the exiting sensors to the new format. Sounded like a good idea.... exept that some sensors are created with standard helpers (SendAlertSensor" in my case, while others are created "raw" with "RXDecode". Also, the childIDs currently passed and ignored by various hardwares are not always 0, or 1, but almost anything, so the database update must handle all cases individually when reconstructing the new ID.

In the end I thought that was too much work just for making it look nice.... and I gave up. And this is only one simple, seldom used sensor.

Conclusion: I am fully in line with you.... but I feel you are starting a very long journey here.

**Comment by szczukot** [comment]
This is a big problem for me.  When i add new module, all devices different create own ID, Unit etc.
+1

**Comment by szczukot** [comment]
I think that should be created a parallel branch (target) with two big changes:
- ID standarization
- Using general devices instead of RFX (remove all sDecodeRXMessage. Use only SendXXXSensor).

Currently, development is a very big problem.
And it will be harder and harder.
We have to do big cleanup and standarization.

**Comment by gizmocuz** [comment]
This can be done after the relesse and is why I started with the general devices 
I know some users will miss the specific device display when they use a rfxcim/rflink but Hmmmm

**Comment by gizmocuz** [comment]
Project was started with only a RFXCOM tranciever

**Comment by szczukot** [comment]
I guess :)
But now it's the past.

**Comment by LemarinelNet** [comment]
Yes, the code doesn't lie about this: many functions are based on RFXCOM.
Also, I've seen that some kind of devices (C structs) have DeviceID, but no UnitID : we will need to add it to be fully compatible. If we don't, we will still need to store ChildID (UnitID) in DeviceID for some kind of devices. Not nice !

**Comment by gizmocuz** [comment]
It will be a very big upgrade, also all current devices needs to be correctly patched to the new general devices
Luckily i can test this for most of them.
When there is no UnitID, we just use '1' as unit id
I think i'm going to accept less patches for new hardware and focus on making a new stable release

**Comment by gizmocuz** [comment]
Do note, for switches (things we send out with RF) all these different types are needed as they are need to be send with different protocols

**Comment by szczukot** [comment]
Maybe time for release "2.0". Without back compability.
And simplify sensors like in OpenHab (only few type and you can do anything with differens devices)

**Comment by gizmocuz** [comment]
No... we want backwards compatibility... (i want... ) i have years of logging... 3-4 years...

**Comment by MasterCATZ** [comment]
while you are at it please don't shorten unique ID's 
out of 500 DS18B20 I can only use 100 as all the rest are duplicated because the last 2 Digits all being the same 
and even worse EVERY DS2413 I have here is a duplicate , how has no one had this issue before! 

whos bright idea was it to turn 2-wire 64bit unique ID's 8-bit family code, 48-bit serial number and 8-bit CRC
 into 2 byte ID's

**Comment by gizmocuz** [comment]
It is a CRC hash.. that change is very very very small
Buy another one.. or use mysensors
Thank you for taking my bright mind into question.. did you had a look through the whole code before making such a bright command@

**Comment by LemarinelNet** [comment]
I'm back after some time... Winter is coming, I'll have some time to code...
I'll try to see how I can work with @gizmocuz  to contribute on this issue.
