### ISSUE TITLE
OFF action not called when there is no ON action in switches

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#1414]
with latest version V3.7149 the off action is not called when there is no on action
also when you specify an ON action also it is being called for both on and off

very annoiyng when you have switches(Hue scenes) which do not need an on action but need an off action to be turned off

Already mentioned this on the forum but apaerntly nobody noticed this

**Comment by gizmocuz** [comment]
Do not respect an answer in a day
Yes i did notice this, and also this issue.
This is also called cross posting... please do not do this

**Comment by GravityRZ** [comment]
Ok sorry but since it was obvious snd nobody replied i thought it might be missed.
Will be more patient in the future

Verstuurd vanaf mijn iPhone

Op 28 mrt. 2017 om 08:52 heeft gizmocuz <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Do not respect an answer in a day
Yes i did notice this, and also this issue.
This is also called cross posting... please do not do this

**Comment by gizmocuz** [comment]
Should be solved in the latest commit
