### ISSUE TITLE
Please support an own Topic for"MySensors Gateway with MQTT"

### ISSUE THREAD

**Issue by micropet** [domoticz/domoticz#1415]
Please support in "MySensor's Gateway with MQTT" the use of an existing topic.
At the moment "domoticz /in/ MyMQTT" and "domoticz /out / MyMQTT" are fixed.

**Comment by zaphodus** [comment]
There is a pull request, where the name of the topic was generated from the gateway name. Eg: domoticz/in/<GatewayNodeName>, domoticz/out/<GatewayNodeName>

#1411

**Comment by micropet** [comment]
Oh, not seen. Thank you.

**Comment by micropet** [comment]
Perhaps once again to clarify:

I have two MySensors MQTT gateways here.
The one topic is "mysensors-out" and the second is "mysensors-out1".
Now I would like to use these topics in Domoticz.

**Comment by zaphodus** [comment]
Ok, I understand. 

I have 14 MySesors MQTT gateways. The topic names look like these:

Node1:
domoticz /in /Node1
domoticz /out /Node2

Node2:
domoticz /in /Node2
domoticz /out /Node2

There is no free text field in the harware table, where you can store the topic name.

**Comment by gizmocuz** [comment]
If needed, you can store them in the field 'Extra'

**Comment by zaphodus** [comment]
Currently the ca filename is stored in this field.

**Comment by gizmocuz** [comment]
Yes, but you can make a semicolon separated string list value1;value2 for example, or have a look how other hardware devices do this

**Comment by micropet** [comment]
@zaphodus
i think you have 14 MySensors Nodes and only 1 Gateway.

i have 2 Gateways
Gateway 1 has topic-prefix=mysensors-out and topic-prefix=mysensors-in
Gateway 2 has topic-prefix=mysensors1-out and topic-prefix=mysensors1-in

I can not change these Topics because I use them in other programs.

**Comment by zaphodus** [comment]
I'm sorry if it was not clear. I have 14 MySesors MQTT gateways. 
I will look at how to implement editable topic names

![kepernyokep - 2017-03-29 - 12 03 30](https://cloud.githubusercontent.com/assets/15976565/24451495/5c79e13a-147f-11e7-8f9d-9ffb458588fc.png)

![kepernyokep - 2017-03-29 - 12 12 29](https://cloud.githubusercontent.com/assets/15976565/24451504/629053ec-147f-11e7-8069-754fc2a231de.png)

**Comment by micropet** [comment]
yes -  editable topic names would be nice 👍

**Comment by gizmocuz** [comment]
Why do you have 14 gateways ? Would 1 not be sufficient ?

**Comment by arturmon** [comment]
Why not do altogether editable all the field "domoticz"?

**Comment by gizmocuz** [comment]
Why do you need multiple gateways ? Would 1 not be sufficient ?

**Comment by zaphodus** [comment]
I have locally attached sensors on the gateways. The gatways are ESP8266 without NRF radio. But the node id of the MySensors gateway is 0 and cannot be changed. So if multiple gateways are used, the sensor ids will be in conflict. 
This conflict can be resolved: 
1) by unique sensor ids, but the number of sensors are limited to 255
2) by unique mqtt topic names

**Comment by gizmocuz** [comment]
1. 255 sensors Must be enough
2. this is not the way it is designed... you better use 1-wire then.
Or just get yourself some nRF024, they are extremely cheap
