### ISSUE TITLE
Selector Switch : TypeError: undefined is not an object (evaluating '$.selectorSwitchLevels.join')

### ISSUE THREAD

**Issue by SnouF** [domoticz/domoticz#1416]
hi
I have a javascript error with Selector switch in webUI.
`TypeError: undefined is not an object (evaluating '$.selectorSwitchLevels.join') http://localhost:8080/#/LightSwitches 1743:95`

To reproduce the bug: 
1/ Create a dummy switch
2/ edit it and select subtype "selector"
3/ add an action
4/ save
5/ go back
6/ click "edit" 
=> js error

Tested in Firefox, chromium, epiphany (webkit)

Domoticz beta:
Version: 3.7196
Build Hash: 7a224cd9

**Comment by gizmocuz** [comment]
How about from the hardware tab, dummy hardware, create virtual sensor, you create directly a selector switch ?

**Comment by SnouF** [comment]
I do not understand the question (my English is not very good: D)

But I just saw a bug at the creation of Seletor. When I click "Add a level selector" (I have the interface in French I do not know the exact label in English) I have an other js error :

[Error] TypeError: undefined is not an object (evaluating 'table$.data('levelActions').split')
	AddSelectorAction (LightsController.js:1435)
	AddSelectorLevel (LightsController.js:1324)
	onclick (Script Element 8:1)

**Comment by SnouF** [comment]
Screenshot (I juste change the language to english)

![capture du 2017-03-29 20-52-54](https://cloud.githubusercontent.com/assets/1040481/24471417/5b0c84a4-14c2-11e7-9c74-e7bbdbed3133.png)

**Comment by gizmocuz** [comment]
You are creating the selector switch wrong, you need to do it from the dummy hardware in the hardware setup with the button

**Comment by SnouF** [comment]
Oh, oops! Sorry for this bad bug report
