### ISSUE TITLE
Tellstick support missing in latest beta?

### ISSUE THREAD

**Issue by Zuikkis** [domoticz/domoticz#1418]
Hi,

I have some Tellstick sensors and switches. They all stopped working when I updated to latest beta. The devices are still listed, but there is absolutely no tellstick activity shown in the logs..  

It works fine when I use my own compiled version, so maybe you just have tellstick disabled in the build?

**Comment by gizmocuz** [comment]
Don't think so.. Can you compare the two code repo's?
Or does it need to be enabled by the cmake command line?
If yes, then you always need to do this.. Unless someone creates a native implementation

**Comment by Zuikkis** [comment]
But I mean, I updated domoticz using the update button, and Tellstick devices stopped working. When I reverted back to my own compiled version, they work again.

I'm currently downloading the latest changes from upstream to see if there are differences, but I don't think so..

**Comment by Zuikkis** [comment]
This is the error I get when trying to toggle a Tellstick light switch:
2017-03-29 21:16:30.131 Error: Switch command not send!, Hardware device disabled or not found!

**Comment by Zuikkis** [comment]
Hmm, I think this is a common problem, see here:

https://www.domoticz.com/forum/viewtopic.php?f=21&t=15067&hilit=tellstick

cmake looks for telldus development files, and then decides whether to include tellstick. But you don't need any command line arguments for cmake.

**Comment by Zuikkis** [comment]
Just finished building the current repo, and tellstick works fine. So the problem is just in your build? See cmake output if  telldus is not found..

**Comment by Zuikkis** [comment]
Is this fixed now?

**Comment by gizmocuz** [comment]
i closed it because of your comment: "Just finished building the current repo, and tellstick works fine. So the problem is just in your build? See cmake output if telldus is not found.."

**Comment by Zuikkis** [comment]
Yes.. Current repo is fine, that's what I tested and said.

I don't know who builds the binary releases available from domoticz.com, but the problem is that his build environment does not have libtelldus-dev installed. cmake checks that and does not build tellstick.

What's more confusing, tellstick still appears in the Hardware page, you can select it but it won't work.. This must be very confusing to the user, who thinks he is doing something wrong.

You can check domoticz binary with "grep libtelldus domoticz", it says if binary file matches or not..

**Comment by gizmocuz** [comment]
Yes you are right... sorry i did not build support for this... someone needs to fix this... i guess it is a #define in cmake, and we could use that in c++ to hide the hardware if not found ?
Or someone needs to write a 100% native class for it, so it will always work, i guess you can talk directly to the usb device, and you do not need a api if you can code it directly ? (i can not do this)

**Comment by Zuikkis** [comment]
100% native class has problems. There are many different kind telldus devices, you would need to support them all. For example I have Tellstick Net, which is connected with Ethernet, not USB..

Can't you just include libtelldus in your build system? Telldus has a Raspberry native version available, no need to  compile anything..

https://developer.telldus.com/wiki/TellStickInstallationUbuntu

I think you only need the libtelldus-core-dev package.

**Comment by gizmocuz** [comment]
Well i for sure hope the commands/interface would be the same between the ethernet/usb ?
I think this will make the final executable larger, and maybe it would not run on all systems
There are alternatives... but thats not really a solution
But you can always build yourself, and let the system automatically build/update

**Comment by Zuikkis** [comment]
You are right, just checked that my version of Domoticz does not start if "libtelldus-core.so" is not found on the system. So it's not good for all users. I don't know if it would be possible to only load the library if actually using tellstick? 

The current Tellstick support works so well that I would not really want to start modifying that... :( 

If you look in the forum thread linked above, there are many users wondering about this. Maybe you could release two versions of the binary? At least for stable releases..

**Comment by Risca** [comment]
> You are right, just checked that my version of Domoticz does not start if "libtelldus-core.so" is not found on the system. So it's not good for all users. I don't know if it would be possible to only load the library if actually using tellstick?

This was fixed with https://github.com/domoticz/domoticz/pull/2727 :wink:
(sorry to necrobump, I was investigating another Tellstick issue and found this issue)
