### ISSUE TITLE
Critical security issue and design issue in the Web server layer

### ISSUE THREAD

**Issue by gaudryc** [domoticz/domoticz#142]
I was looking for fixing the long term authentication token issue (to allow a user to reconnect automatically if he has a valid cookie), I had discovered some critical issues.

Are you aware that two different users who are simultaneously connected share the same instance of the CWebserver class therefore the same instance of the cWebem class therefore the same instance of the class cWebemRequestHandler ?

The class cWebem holds sessions (why not), user passords (why not), current user (critical issue) and current request attributes (critical issue).

The solution would be to put all user data and all request data in the request object. It needs to refactor the webserver classes. It needs also to add the request object as the first argument of all web action and command methods.

Do you allow me to create a new branch to fix all of this ?

**Comment by gizmocuz** [comment]
Sounds good! It would clean a few things as well, and makes it more logical in the web actions
(Please pass it as const)

**Comment by gaudryc** [comment]
I have created the branch (https://github.com/gaudryc/domoticz/tree/fix_webserver_design_issue) and committed the first step : request as method argument...

**Comment by gizmocuz** [comment]
Super! thanks a million!
So this means soon instead of

m_pWebEm->m_actualuser_rights

we can/should use

req->m_actualuser_rights

? (and the username as well)

**Comment by gaudryc** [comment]
I have tried to remove m_actualuser and m_actsessionid by putting them in request.session attribute but it cannot work because commands (eg. Login) need to modify the session thus the request, and const is really const...
I think i will add an new argument : session& sess.

**Comment by gizmocuz** [comment]
you mean from domoticz->webserver needs to modify the session ?
its been a while ago, but i thought this was all handled in the webserver ?

**Comment by rkluwen** [comment]
Not sure if I get this straight. But the attributes indeed need a session object. The life span of a request is only temporary.

**Comment by gaudryc** [comment]
Job is done.
All "session" attributes are now in a WebEmSession object.
All "request" attributes are now in a request object.
All request parameters are accessible from the request object using static methods.

Next step : create another pull request to manage long term cookies and athentication token.

**Comment by gizmocuz** [comment]
Nice !, going to take this with us in a next stable release (might be next week(end))

**Comment by gaudryc** [comment]
OK, thank you.

Now I will work on long term cookies and authentication token.

2015-10-18 18:50 GMT+02:00 gizmocuz notifications@github.com:

**Comment by gizmocuz** [comment]
Thanks for the patch, its merged into the master branch now
