### ISSUE TITLE
Bug with "Electric (Instant + counter)" subtype

### ISSUE THREAD

**Issue by apazga** [domoticz/domoticz#1438]
Hi,

It seems that the counter (for month/year) is not working at it should.
The screenshot shows that measures from today are normal. But if you see the data that is appearing as "Last week" for today, there is some strange behaviour and it's showing a really high value.

This is happening sometimes, and I really don't know how to debug it.
![captura de pantalla 2017-04-04 18 55 23](https://cloud.githubusercontent.com/assets/6894350/24669208/d79ff89c-1969-11e7-96fd-b4f053fe4d9a.png)

Example for "Last year" that shows those "spikes":
![captura de pantalla 2017-04-04 19 09 47](https://cloud.githubusercontent.com/assets/6894350/24669344/59acd044-196a-11e7-99c2-f79f04192211.png)

I think that there's may be an issue when there is some zero value (today we have a blackout at home at 9.00).

Regards,
Abel.

**Comment by gizmocuz** [comment]
correct, a blackout can cause this... shift-click on the value will solve this
Please use our forum

**Comment by apazga** [comment]
Ok, thanks @gizmocuz 
Anyway, I'm trying to debug this behaviour. If I find something I'll submit a PR.
