### ISSUE TITLE
Timeclock does not work

### ISSUE THREAD

**Issue by 0n3-70uch** [domoticz/domoticz#1443]
Hello everybody,

I notice a little problem in the current beta version 3.7253.
When I add a timeclock to a light switch with for example "off, daily, in time, 1:00am" then it doesn't work.
With the previous beta everything is fine. I went back to stable version 3.5877 and used the 3.7253 database backup... the timeclock is running perfect.

Thanks for this great and free home automation platform.
Greetings
Fabian

**Comment by gizmocuz** [comment]
Please use our forum, Only C++ related questions/feedback/code stuff
