### ISSUE TITLE
html output has unprocessed 'ngclass' code

### ISSUE THREAD

**Issue by flatsiedatsie** [domoticz/domoticz#1444]
In the HTML output for the menu there are some odd things like:

`<li ng-show="config.EnableTabDashboard" ng-class="**{'current_page_item':getClass('/Dashboard')}**" class="clDashboard current_page_item">
`
These are also in the stable release.

They do not impede functionality. But they might be indicative for a deeper issue?

**Comment by gizmocuz** [comment]
Could you tell which file/line number ?

**Comment by flatsiedatsie** [comment]
If you right-mouse-button on any menu item and select 'inspect' you should see it right away. I don't know what file generates the menu.

**Comment by gizmocuz** [comment]
Okey after editing your first question, i can now see the html code.
This is angularjs code, and specifically in this case it checks if it needs to highlight the menu button in case this menu is selected.
For example when you press the 'switches' button to go to the switches page, this button is highlighted
