### ISSUE TITLE
Data in week log chart of "Incremental Counter" is 0!

### ISSUE THREAD

**Issue by howei6** [domoticz/domoticz#1446]
I has an Incremental Counter to log everyday reading time on kindle. The data in week log chart is zero!
![image](https://cloud.githubusercontent.com/assets/22789316/24812063/37b6a814-1bfb-11e7-8c29-8fd612e8a320.jpg)

I have checked the log in "Meter_Calendar" Table in Sqlite. The result shows that all log is working in the right way.
![image](https://cloud.githubusercontent.com/assets/22789316/24812086/50b63500-1bfb-11e7-857c-bb8c961c8d3f.jpg)

![image](https://cloud.githubusercontent.com/assets/22789316/24812099/5f0265b6-1bfb-11e7-9a59-e22171580d8c.jpg)
So, I think there is some bug in the display of week chart. Plesase Confirm!

Here are my setting and scripts:
` {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "94 Min",
         "CounterToday" : "8 Min",
         "CustomImage" : 0,
         "Data" : "94 Min",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "Electric",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "82020",
         "LastUpdate" : "2017-04-08 00:48:00",
         "Name" : "Kindle Time",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Counter Incremental",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "counter",
         "Unit" : 1,
         "Used" : 1,
         "ValueQuantity" : "Time",
         "ValueUnits" : "Min",
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "20"
      },`

`
local timer_device_ID = 20
commandArray = {}
commandArray['UpdateDevice'] = timer_device_ID .. '|0|0'
local TotalMinutesOn = otherdevices_svalues['Kindle Time']
if otherdevices['Kindle'] == 'On' then
  TotalMinutesOn = TotalMinutesOn + 1
end
commandArray['UpdateDevice'] = timer_device_ID .. '|0|' .. tostring(TotalMinutesOn)
return commandArray
`

**Comment by gizmocuz** [comment]
What is your forum username ?

**Comment by howei6** [comment]
I have no forum account. Do you mean i should post it in forum？

**Comment by gizmocuz** [comment]
yes, but if you had a forum account, you could send me a backup of your database so we can use it to debug
