### ISSUE TITLE
Notification interval issue

### ISSUE THREAD

**Issue by pvangorp** [domoticz/domoticz#1447]
Since version V3.7259 I receive weather sensor notifications every x minutes instead of the defined interval for sensors of 12 hours and switch interval direct. I've got two systems and both have the same issue since V3.7259. But this wasn't an issue in previous versions. I removed all notification till a fix is available.

**Comment by jvandenbroek** [comment]
What trigger did you set? I've lowered some of my temp sensors and they just trigger once during the set interval time. Which platform are you running on?

**Comment by pvangorp** [comment]
Ik draai de laatste raspbian jessie versie met alle updates en de laatste domoticz beta. Voor de laatste beta ging het goed. Na de laatste niet meer. Dit geldt voor Raspberry pi 3 en zero w. Ik heb mijn weersensornotificatie als volgt ingesteld:
Vochtigheid	Groter 80 %	All		Normaal	Nee	Nee
Als je een gebeurtenis aanmaakt die alleen kijkt bij bijvoorbeeld sunset dan gaat het wel goed. Lijkt alleen in notificatie te zitten.
Ik heb net domoticz ge-update naar v3.7.266, zag aanpassingen mbt notificatie

**Comment by jvandenbroek** [comment]
I'll continue in English for other readers if you don't mind.
Strange, also set the humidity lower and just triggers once during set interval period, as expected. Just to be sure; did you try re-add them?

You're saying a sunset event doesn't trigger it, are you using customized events (setup -> more options -> events) or lua scripts to trigger notifications?

**Comment by pvangorp** [comment]
I've tried remove and add them again (on two sepperate systems) both had the same issue. Sunset event works fine! I use the default object based function to create triggers. That works fine! The problem is notification. I was just testing the v3.7266 version. I'll let you know

**Comment by jvandenbroek** [comment]
OK, so I can rule out any scripts being involved. Nothing has changed since the version you've tested that could influence this behavior, so I expect you get the same result. But it's just very strange that I can't replicate the issue, I'm also using many temp / humidity sensors with notification triggers.

One thing that isn't clear to me yet, but important to address this issue: You only get these notifications when they actually match? So when humidity is lower than 80%, you won't get any notifications when the trigger is set to >80%, right? Just that when humidity is >80%, you'll get them every sensor update?

**Comment by pvangorp** [comment]
I only get messages when matching and message with every sensor update is also correct!

**Comment by jvandenbroek** [comment]
I can replicate the issue when a Custom Message has been set, which I'll fix. Is it set in your notifications?

**Comment by pvangorp** [comment]
Yes I have a custom message! I'm glade you could replicatie it.

**Comment by pvangorp** [comment]
Should I remove notification or is it an easy fix which is solved in the next version?

**Comment by jvandenbroek** [comment]
Yes, I'll push a fix later today, need to do some tests first.

**Comment by pvangorp** [comment]
Thank you for helping me with this issue😀

**Comment by pvangorp** [comment]
I just installed Version: 3.7267, but the issue still occures. Is this fix applied in this build?

**Comment by jvandenbroek** [comment]
Needs to be merged first, can't do that myself :)

**Comment by gizmocuz** [comment]
Its mergerd 22 hours ago... would have expected it to be in a long time ago now

**Comment by pvangorp** [comment]
I still had issues with 3.7267 I have installed 3.7277. I'll test it and I let you know if it's working.

**Comment by pvangorp** [comment]
Look like it is fixed in 3.7277

**Comment by pvangorp** [comment]
Is solved!
