### ISSUE TITLE
daylight saving time bug in tables Xxxx_Calendar

### ISSUE THREAD

**Issue by domcars0** [domoticz/domoticz#1451]
There is a bug for the daylight saving time in all Xxx_Calendar SQL Tables.
This year the DST in France was on 2017 March 26. In all the Xxx_Calendar table there is no input for this day, but there is 2 entries for the 2017 March 25!

Example for the Wind:
```
sqlite> select * from Wind_Calendar where Date='2017-03-25' and DeviceRowID=19;
19|92.4|0|109|0|178|2017-03-25
19|118.99|0|59|0|88|2017-03-25
sqlite> select * from Wind_Calendar where Date='2017-03-26' and DeviceRowID=19;
sqlite>
```

It's possible to see the bug on the graphics 
See this subject:
https://easydomoticz.com/forum/viewtopic.php?f=9&p=34956

**Comment by gizmocuz** [comment]
As you can read in the topic, and also on our forum (there is whole long post about this) this is already fixed in the beta version.
Please use the forum
