### ISSUE TITLE
8 port relays in combination with GPIO output not working with slave mode 

### ISSUE THREAD

**Issue by pvangorp** [domoticz/domoticz#1452]
When I try to control my 8 ports relays with GPIO output and the slave option, the master relay works fine, both pictures change but the slave relay doesn't change. When using them individually everything works fine. I temporary solved it by using a group, because a group does work. But that is not a sollution for the long term. You have to create an extra group for each combination. I tested the latest stable and beta V3.7266.

**Comment by gizmocuz** [comment]
Please use our forum
