### ISSUE TITLE
Unable to use custom python modules in plugins

### ISSUE THREAD

**Issue by stas-demydiuk** [domoticz/domoticz#1466]
Have an issue when using python modules in python plugins. As example requests module:

1. When trying to import "requests" python module in the file head, plugin stops working immediately, even onStart is not called, no errors, just nothing happens. Sample plugin.py:

```
import Domoticz

import sys
sys.path.append(sys.prefix+'/lib/site-packages')

import requests;

def onStart():
    Domoticz.Log('Start')
    return True
```

2. When I'm trying to import requests module in for example onHeartbeat function then this function will be called ones, return result to Domoticz (log message for example) and plugin stops working (no errors, no logs)

Also there is an information from other users about similar behavior with gpio and uuid modules.
[Discussion on forum](https://www.domoticz.com/forum/viewtopic.php?f=65&t=15233&start=120#p127761)

**Comment by gizmocuz** [comment]
Please use our Forum
