### ISSUE TITLE
Dashboard display issue for Teleinfo tile

### ISSUE THREAD

**Issue by pepsi92** [domoticz/domoticz#1470]
Hi,

Since I upgraded to 3.0.7310, the dashboard tile representing the electric usage (Teleinfo module) looks stange. Each time the dashboard page is loaded, the value is displayed twice (see. screenshot below). If I keep the page open, the value is correctly displayed after the first update of the data, basically after 5'. If I leave the dashboard for another tab and come back or if I reload the page, the issue appears again.

![capture ecran 2017-04-12 a 23 10 53](https://cloud.githubusercontent.com/assets/18167025/25038139/5ef82d60-20fd-11e7-88bd-c02dcd0a3236.png)

Note that the issue does not affect the Utility tab where the same tile (with more info) is displayed correctly.

Any idea? It seems I'm not the only one facing this (minor) issue.

My environment:
- Domoticz 3.0.7310 running on a Synology DS416play with DSM 6.1. I'm using the package from Jadahl
- Teleinfo USB module
- RFXCOM - RFXtrx433E USB module

Thanks for your help on this issue.

**Comment by advfr** [comment]
Hello Pepsi, same problem for me 👍 (Pï2 3.0.7320).

![double conso instantanee](https://cloud.githubusercontent.com/assets/27512635/25052900/749fdbb6-2154-11e7-8e6f-344efac467ba.png)

Good luck and big thanks to the whole team for your hard work.

**Comment by gizmocuz** [comment]
There are also issues with p1 meter display
Maybe revert the previous patch?

**Comment by gizmocuz** [comment]
Is this solved in the latest beta version ?

**Comment by advfr** [comment]
Good evening !

Yes, it's OK on 3.0.7534, good job \o/

Thanks a lot.

**Comment by gizmocuz** [comment]
Thanks for the feedback

**Comment by pepsi92** [comment]
Hi,
Fixed for me as well in 3.0.7550 running on Synology. 
Many thanks !

**Comment by gizmocuz** [comment]
There was still a problem with General kWh sensors... this has been fixed this morning...
