### ISSUE TITLE
Wrong dimmer visual controls

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#1479]
Dimmer have bug in GUI:
![dimmer](https://cloud.githubusercontent.com/assets/10205661/25085643/89c9b00a-2363-11e7-87d4-3909973745bb.png)

**Comment by xztraz** [comment]
this is skin dependent if you mean the slider is too long? which skin is that?

**Comment by szczukot** [comment]
This is for element-light. Other look good i think.

**Comment by xztraz** [comment]
made a fix but i need someone to test it.
You can copy the ccs to your system and see if it works

Fix is copied from dark-element so should work

Link:
https://github.com/domoticz/domoticz/pull/1483

**Comment by xztraz** [comment]
merged now so should be fine in beta build now. can you please test that

**Comment by Siewert308SW** [comment]
Latest beta, cleaned browser cache but no luck...
![schermafdruk 2017-04-18 19 53 38](https://cloud.githubusercontent.com/assets/25230393/25145230/de48527c-2470-11e7-970b-fee8955ba298.png)

**Comment by xztraz** [comment]
test in other browser

**Comment by Siewert308SW** [comment]
My previous post was with firefox.
Screenshot below with edge, don't have chrome to test.

![schermafdruk 2017-04-18 19 59 24](https://cloud.githubusercontent.com/assets/25230393/25145513/b1f09616-2471-11e7-9c78-75a9c6b61768.png)

Screenshot below is with explorer:
![schermafdruk 2017-04-18 20 01 50](https://cloud.githubusercontent.com/assets/25230393/25145610/e8b30b5c-2471-11e7-8a2c-da39684223b6.png)

**Comment by szczukot** [comment]
I use chrome - still is wrong.

**Comment by Siewert308SW** [comment]
Weird... Fiddling around in the css files.
But whatever i do with the .dimsliders, no changes are visible.

**Comment by xztraz** [comment]
hm. i have not tested it in element-light but it works fine in element dark. I use a separate browser that is set to clean all files, cookies and cache upon restart. you should at least see changes when you fiddle around so sounds like cache issue.

use inspect element in your browser to see where the dimmer gets it's style from

**Comment by Tommit1** [comment]
in element-dark
![grafik](https://cloud.githubusercontent.com/assets/16592719/25182786/0326d60e-2516-11e7-9022-8b7c280e4555.png)
in element-light
![grafik](https://cloud.githubusercontent.com/assets/16592719/25182993/9d4c6b2c-2516-11e7-9508-f8532be3a122.png)

Rules seem to be different

**Comment by xztraz** [comment]
There you can see that the dimslider style is from custom.css(in dark) and style.css(in light) style.css is default skin.

code is the same in both styles in dimslider section making a diff of css.

Or wait.. ah maybe // is not good for comments in css files.. doh.. i'll remove that and see if it works better..

link:
https://github.com/domoticz/domoticz/pull/1488

![image](https://cloud.githubusercontent.com/assets/25690871/25189065/5f44ac1a-2528-11e7-8adb-f3df1176b0d0.png)

**Comment by Tommit1** [comment]
Tested it... and it seems  // resulted in a truncated custom.css file excatly at //..
Now it looks ok ....

![grafik](https://cloud.githubusercontent.com/assets/16592719/25197819/a638866a-2545-11e7-822e-c489456a221f.png)

Thanks...

**Comment by xztraz** [comment]
Perfect :) thanks for testing. 

Comments are good they said...   Bwoah.

**Comment by xztraz** [comment]
Fix is now merged and should be available now. Can this be closed?

**Comment by Siewert308SW** [comment]
Just updated and tested...
Theme/dimsliders works like a charm now.
Thx, did oversee those slashes and never noticed they where the problem.

**Comment by xztraz** [comment]
Nice :)

well i also missed them at first. 

**Issue can be closed**
