### ISSUE TITLE
SBFSpot Implement SQLite instead of CSV

### ISSUE THREAD

**Issue by netforce** [domoticz/domoticz#1493]
### SQLite support for SBFspot plugin

The SBFspot hardware module needs the CSV files for his PV data. This files take a lot of space on the harddrive without propper cleaning while SBFspot has the posibility to write everything in the SQLite database.

If "CSV_Export=0" go see if the "SQL_Database=" has a ".db"  extension, if so, use SQLite, if not, check for SQL_Hostname,Password and use MySql. Everything else, fail with sensible error that above values do are not as expected.

**Comment by gizmocuz** [comment]
Are you able to implement this in Domoticz?

**Comment by gizmocuz** [comment]
Closing the issue, no feedback, also i dont think you can open this database when it is in use by sbfspot
