### ISSUE TITLE
GUI and error log freaking out... GUI screwed up

### ISSUE THREAD

**Issue by Siewert308SW** [domoticz/domoticz#1497]
I have one RPi3 which is on version 3.7377 with hash: 2b6e719 and all is fine
I just updated my second RPi3 to 3.7379 with hash: c9dc621 and the GUI in the settings page has layout which is completely different from what we know.
And Domoticz error log has red text and is mentioning that Domoticz is restarting every few seconds.
I have the feeling that those changes "flatsiedatsie" made screwed up.

I happens when install Domoticz beta fresh but also when i update a existing installation.
I has nothing to do with browser cache.

![schermafdruk 2017-04-25 18 48 36](https://cloud.githubusercontent.com/assets/25230393/25397333/33748e38-29e8-11e7-8e6c-8eb04a5efe03.png)

![schermafdruk 2017-04-25 18 49 59](https://cloud.githubusercontent.com/assets/25230393/25397337/377003a0-29e8-11e7-9d98-7aa3048b0b94.png)

**Comment by Tommit1** [comment]
and I have the feeling he actually needs some help with Git....

which I can't deliver...

My feeling is based on reading this: 

 flatsiedatsie replied a day ago

Now how do I undo this..

**Comment by Siewert308SW** [comment]
@Tommit1 For sure... But my opinion is try, test before committing something.
If something is coded and not known if it will work then don't
Also ask or try on a empty git before committing to a production/beta git.

p.s
Also don't have that much experience with git.
But just tried to pull the current git and then revert back to the 21 april.
Works like a charm, only don't dare to push it ;-)

@flatsiedatsie 
What are you using to commit to github?
You can revert changes or replace the previous files.

@gizmocuz 
If @flatsiedatsie can't fix this, can you revert the latest changes he made to get Domoticz working again.
#c9dc621c847dcac04faec0c9c0aa2dea61c18b3b
#495d5b07460a675e2870a0bd05741451680f0ec1
#2b6e7192d2ce786aa3446bba3dd12f5b231ba2db
#09c345e2cd6b85fabd925ed6e50df003fc68f18e
#ff87d018d15f6cab179aebaa62d398899855dc11

**Comment by flatsiedatsie** [comment]
Wait what? Oh no!!

I accidentally did something in the master branch a day or two ago. I tried deleting it, but couldn't find how to do it.

I didn't realise I had made a commit!

**Comment by flatsiedatsie** [comment]
I use the web interface. I'm an interaction designer, not a coder. Usually I upload files to the GuiWorks branch. But the web interface can be a bit unclear on where you are. 

Sorry!

**Comment by flatsiedatsie** [comment]
I still can't find any way to undo it via the web interface. If anyone can undo it for me: please!

**Comment by Siewert308SW** [comment]
Don't know how to do it by webgui.
For my own github for my scripts i use tortoise and from there i can revert back to e specific commit.
And then push it, but as i never pushed something overhere and don't want to screw thing up more i leave this to @gizmocuz or any other dev.
But is for sure that all your commits have to be reverted. ;-)
As this issue exists for over 48hr now i can't imagine no one else has noticed it as this issues makes Domoticz unusable or they all haven't updated yet.
We have to wait until someone picks this up.

**Comment by Egregius** [comment]
I'm also on 3.7379 on a RPi3 (since 3 hours) and can't see anything weird in the web settings page. Looks just the same. 
Also don't experience anything weird in functionality.

**Comment by darkrain-nl** [comment]
Me too, yesterday I installed a brand new RPi3 with Domoticz v3.7379, at first I had the problem reported here. But after configuring domoticz.sh in /etc/init.d to enable logfiles and restarting the service the problem went away...
Maybe you can try this, @Siewert308SW ?

**Comment by Siewert308SW** [comment]
@darkrain-nl 
That something i could do.
But it shouldn't be needed, You can't expect when this beta is beeing released as Stable that users have to ticker the /init.d to get Domoticz working again.
Even the one who committed @flatsiedatsie mentions that is a wrong commit.

@Egregius 
I know your well known to Domoticz.
But did you clean the browser cache and rebooted the system, thats when the issues appears on my side?

**Comment by darkrain-nl** [comment]
@Siewert308SW don't worry, I totally agree with you on this one.

**Comment by Egregius** [comment]
No, I didn't. Normally it get's refreshed automatically, not in this case. 
Now I see the new settings page, looks cool :)
Still no issues found about restarting or red lines in the log.
Now sent a reboot to the Pi, I'll be back soon with an update

**Comment by Siewert308SW** [comment]
Just noticed @gizmocuz reverted the gui changes.
I can confirm no more issues, as for me this solves the issue

**Comment by flatsiedatsie** [comment]
Yes, it has been fixed. Sorry again, I'll make sure to be extra careful in future.

**Comment by Siewert308SW** [comment]
@flatsiedatsie ;-)

**Comment by odelma** [comment]
@flatsiedatsie - could [this](https://www.domoticz.com/forum/viewtopic.php?p=130125#p130125) (mobile) GUI-issue be related to these changes you've made? In any case, keep up the good work, it's been due for a while now for Domoticz GUI to get a bit of an overhaul...:smile:

**Comment by flatsiedatsie** [comment]
Yeah I was wondering about that. But in theory none of my changes have made it into domoticz yet.

**Comment by flatsiedatsie** [comment]
I also did a quick check. On my version the mobile interface does update the sensor values.
