### ISSUE TITLE
lua_parser Xpath issue using HTTP poller 

### ISSUE THREAD

**Issue by nmaster2042** [domoticz/domoticz#1507]
Domoticz: V3.3792
Platform: Odroid C2
OS: Debian jessie

Hi,

I'm trying to get air quality from XML source using HTTP poller and lua_parser script without success.

Here is a sample of y XML source:

`
<root><node><dateIndice>2017-04-29</dateIndice><agglomerationCodeInsee>97209</agglomerationCodeInsee><agglomeration>FORT-DE-FRANCE</agglomeration><valeurIndice>6</valeurIndice><SousIndiceO3>2</SousIndiceO3><SousIndiceNO2>1</SousIndiceNO2><SousIndicePM10>4</SousIndicePM10><SousIndiceSO2/><Commentaire/><sourceAASQA>http://www.lcsqa.org/aasqa/code/39</sourceAASQA></node><node><dateIndice>2017-04-29</dateIndice><agglomerationCodeInsee>76540</agglomerationCodeInsee><agglomeration>ROUEN</agglomeration><valeurIndice>4</valeurIndice><SousIndiceO3>4</SousIndiceO3><SousIndiceNO2>2</SousIndiceNO2><SousIndicePM10>3</SousIndicePM10><SousIndiceSO2>1</SousIndiceSO2><Commentaire/><sourceAASQA>http://www.lcsqa.org/aasqa/code/25</sourceAASQA></node><node><dateIndice>2017-04-29</dateIndice><agglomerationCodeInsee>27229</agglomerationCodeInsee><agglomeration>EVREUX</agglomeration><valeurIndice>4</valeurIndice><SousIndiceO3>4</SousIndiceO3><SousIndiceNO2>1</SousIndiceNO2><SousIndicePM10>3</SousIndicePM10><SousIndiceSO2>1</SousIndiceSO2><Commentaire/><sourceAASQA>http://www.lcsqa.org/aasqa/code/25</sourceAASQA></node>
...
...
</root>`

In order to know how to parse it I did it on command line like this:

First I get the XML data from server:

`$ wget -O test.xml http://www.lcsqa.org/surveillance/indices/prevus/jour/xml/`

Then I use xmllint with xpath to get global indice of air quality in my area:

`$ xmllint --xpath '//node[agglomerationCodeInsee=76540]/valeurIndice/text()' test.xml`

And I get:

`4`

Now, I creat a HTTP poller with the URL, and a airquality.lua in the domoticz/scripts/lua_parsers folder that looks like this:

`-- ID domoticz
local deviceId = 133

-- Retrieve the request content
s = request['content'];

-- Parse XML values
local iGlobal = domoticz_applyXPath(s,'//node[agglomerationCodeInsee=02691]/valeurIndice')

print('Indice: ' .. iGlobal)

-- Update device
domoticz_updateDevice(deviceId,'',iGlobal)`

But when I activate the poller, I can see in the logs something like this:

`2017-04-29 17:36:22.242 CLuaHandler: udevices: Indice: true`

It seems I get a boolean instead of the real value, so I tried other Xpath options in the lua script:

ex:

`local iGlobal = domoticz_applyXPath(s,'//node[agglomerationCodeInsee=02691]/valeurIndice/text()')`

But no more success.

The domoticz_applyXPath function may contain a bug as I already managed to get values for less complex XML data structures, without using xpath.

Thank you your help.

**Comment by gizmocuz** [comment]
You get better help on our forum

**Comment by nmaster2042** [comment]
But nobody helped me and I think there is a bug.

**Comment by nmaster2042** [comment]
See here: https://www.domoticz.com/forum/viewtopic.php?f=61&t=15244

No replies.
