### ISSUE TITLE
LUA domoticz_applyXPath() inconsistent results

### ISSUE THREAD

**Issue by nmaster2042** [domoticz/domoticz#1509]
Domoticz: V3.3792
Platform: Odroid C2
OS: Debian jessie

Hi,

My last issue has been misunderstood and quickly closed: I wasn't requesting help, but was reporting a bug, so please check before closing it.

There is an issue with the domoticz_applyXPath() function in LUA.

There is actually something wrong regarding results returned by domoticz_applyXPath(), a valid Xpath pattern returns nothing in the case below.

Here is a sample of y XML source:

`<!-- --> <root><node><dateIndice>2017-04-29</dateIndice><agglomerationCodeInsee>97209</agglomerationCodeInsee><agglomeration>FORT-DE-FRANCE</agglomeration><valeurIndice>6</valeurIndice><SousIndiceO3>2</SousIndiceO3><SousIndiceNO2>1</SousIndiceNO2><SousIndicePM10>4</SousIndicePM10><SousIndiceSO2/><Commentaire/><sourceAASQA>http://www.lcsqa.org/aasqa/code/39</sourceAASQA></node><node><dateIndice>2017-04-29</dateIndice><agglomerationCodeInsee>76540</agglomerationCodeInsee><agglomeration>ROUEN</agglomeration><valeurIndice>4</valeurIndice><SousIndiceO3>4</SousIndiceO3><SousIndiceNO2>2</SousIndiceNO2><SousIndicePM10>3</SousIndicePM10><SousIndiceSO2>1</SousIndiceSO2><Commentaire/><sourceAASQA>http://www.lcsqa.org/aasqa/code/25</sourceAASQA></node><node><dateIndice>2017-04-29</dateIndice><agglomerationCodeInsee>27229</agglomerationCodeInsee><agglomeration>EVREUX</agglomeration><valeurIndice>4</valeurIndice><SousIndiceO3>4</SousIndiceO3><SousIndiceNO2>1</SousIndiceNO2><SousIndicePM10>3</SousIndicePM10><SousIndiceSO2>1</SousIndiceSO2><Commentaire/><sourceAASQA>http://www.lcsqa.org/aasqa/code/25</sourceAASQA></node> ... ... </root>`

In order to know how to parse it I did it on command line like this:

First I get the XML data from server:

`$ wget -O test.xml http://www.lcsqa.org/surveillance/indices/prevus/jour/xml/`

Then I use xmllint with xpath to get global indice of air quality in my area:

`$ xmllint --xpath '//node[agglomerationCodeInsee=76540]/valeurIndice/text()' test.xml`

And I get:

`4`

Now, I create a HTTP poller with the same URL for XML source, and a airquality.lua in the domoticz/scripts/lua_parsers folder that looks like this:

`-- ID domoticz
local deviceId = 133

-- Retrieve the request content
s = request['content'];

-- Parse XML values
local iGlobal = domoticz_applyXPath(s,'//node[agglomerationCodeInsee=02691]/valeurIndice')

print('Indice: ' .. iGlobal)

-- Update device
domoticz_updateDevice(deviceId,'',iGlobal)`

But when I activate the poller, I can see in the logs something like this:

`2017-04-29 17:36:22.242 CLuaHandler: udevices: Indice: true`

It seems I get a boolean instead of the real value, so I tried other Xpath options in the lua script:

ex:

`local iGlobal = domoticz_applyXPath(s,'//node[agglomerationCodeInsee=02691]/valeurIndice/text()')`

But no more success.

So Xpath doesn't react correctly in this case.

**Comment by sbouchex** [comment]
Looks like a bug in tinyxpath

**Comment by gizmocuz** [comment]
Can you create a small xml file with for example only one value
Upload this to your own webserver, and test with this
If this does not work, post here the complete xml you are using

**Comment by nmaster2042** [comment]
Hi, 

I just tried with a simple xml sample on a local web server as you proposed.

The result remains the same.

Here is the sample

`<!--  -->`
`<root>`
    `<node>`
        `<dateIndice>2017-05-31</dateIndice>`
        `<agglomerationCodeInsee>76540</agglomerationCodeInsee>`
        `<agglomeration>ROUEN</agglomeration>`
        `<valeurIndice>4</valeurIndice>`
        `<SousIndiceO3>4</SousIndiceO3>`
        `<SousIndiceNO2>2</SousIndiceNO2>`
        `<SousIndicePM10>3</SousIndicePM10>`
        `<SousIndiceSO2>1</SousIndiceSO2>`
        `<Commentaire/><sourceAASQA>http://www.lcsqa.org/aasqa/code/25</sourceAASQA>`
    `</node>`
`</root>`

The request in the lua script is loke this:

`local iGlobal = domoticz_applyXPath(s,'//node[agglomerationCodeInsee=76540]/@valeurIndice')`
`print('Indice global: ' .. iGlobal)`

I also tried this one:

`local iGlobal = domoticz_applyXPath(s,'//node[agglomerationCodeInsee=76540]/@valeurIndice/text()')`
`print('Indice global: ' .. iGlobal)`

with same result: 

Here the printed in the logs of the value I get:

`2017-05-31 19:28:19.235 CLuaHandler: udevices: Indice global: true`

**Comment by nmaster2042** [comment]
Even simpler sample here:

`<!--  -->`
`<root>`
    `<node>`
       `<dateIndice>2017-05-31</dateIndice>`
        `<agglomerationCodeInsee>76540</agglomerationCodeInsee>`
        `<valeurIndice>4</valeurIndice>`
    `</node>`
`</root>`

But no more success.

**Comment by gizmocuz** [comment]
Doesn't look like valid xml... but okey... and could you also send me a complete lua sample code ? i am not into lua, but i can debug this

**Comment by nmaster2042** [comment]
I have found an online xml validator http://xmlvalidation.com/ where I uploaded the 2 samples I posted yesterday and no error were found.

Here is the LUA code I put in the lua_parsers directory, named airquality.lua

`-- ID domoticz`
`local deviceId = 133`

`-- Retrieve the request content`
`s = request['content'];`

`-- Parse XML values`
`local iGlobal = domoticz_applyXPath(s,'//node[agglomerationCodeInsee=76540]/valeurIndice')`
`print('Indice global: ' .. iGlobal)`

`-- Update device`
`domoticz_updateDevice(deviceId,'',iGlobal)`

**Comment by sbouchex** [comment]
I have traced the xpath parsing inside tinyXml and it looks like the code is buggy and as the code is way old, there are good not having a fix.

But...

I just discovered tinyXml2 (https://github.com/leethomason/tinyxml2) and tinyXml2-ex (https://github.com/stanthomas/tinyxml2-ex) which are providing xml parsing + xpath. I'm going to do some tests and I let you know.

**Comment by gizmocuz** [comment]
Great! Yes i know this library existed, but it would also mean you have to make some changes in other parts of the software (openzwave control panel usage for instance)
Hope it works !

**Comment by sbouchex** [comment]
namespaces are different, so we can embed the 2 parsers

**Comment by sbouchex** [comment]
The "tinyxml2-ex" (xpath) part does not look very mature... Navigation/Filtering is half working :-(
