### ISSUE TITLE
Virtual Thermostat take long time to set temp

### ISSUE THREAD

**Issue by zofiel** [domoticz/domoticz#151]
When you try to change a virtual thermostat It takes a llong time to process and you receive the following log message:

Error: EventSystem: Warning!, lua script /opt/domoticz/scripts/lua/script_device_calefaccion.lua has been running for more than 10 seconds

I'm trying with the recommended code:

commandArray['UpdateDevice']='idx|nValue|sValue'

more info: http://www.domoticz.com/forum/viewtopic.php?f=6&t=4347&start=20

**Comment by gizmocuz** [comment]
not a domoticz issue, please continue to use the forum

**Comment by zofiel** [comment]
I'm disagree with the closure of the issue.

The script work well, but domoticz doesn't works fine with thermostat
