### ISSUE TITLE
Rain gauge Oregon data week bug

### ISSUE THREAD

**Issue by marcot26** [domoticz/domoticz#1512]
Oregon rain guage TFA  (rgr126n) not work correctly. Daily data is reset but immediately after they are added to those of the previous day, distorting the day's rainfall data.
 
![screenshot_20170430-095622](https://cloud.githubusercontent.com/assets/28217563/25576314/2bc66466-2e5e-11e7-877d-c61ada41825a.png)

**Comment by marcot26** [comment]
![screenshot_20170501-153814 2](https://cloud.githubusercontent.com/assets/28217563/25580884/7b449776-2e84-11e7-9b8a-65580e5be1b6.png)
![screenshot_20170501-153806](https://cloud.githubusercontent.com/assets/28217563/25580896/86e7a3fc-2e84-11e7-8f43-036e921c324b.png)

**Comment by gizmocuz** [comment]
What hardware are you using to receive this device ?

**Comment by gizmocuz** [comment]
No feedback... also no issues here
