### ISSUE TITLE
PT2262 switch status not changing to 'Off'

### ISSUE THREAD

**Issue by harolds** [domoticz/domoticz#1517]
When using a cheap AliExpress relay switch I can switch it on and off by using an 'Lightning 4, PT2262, On/Off' virtual switch type. But the status stays at 'On'. Domoticz does shows its switching it on and off (in the popup) and the relay is responding correctly.

Off topic: its not possible to create an virtual switch for PT2262 because there is no pulldown menu item for this type. Can that be fixed too so I can start using these relays with Domoticz? I created the PT2262 virtual switch by learning it from a remote. Or make it possible to copy virtual switches (and thus make it possible to change the ID it uses too).

Update: when change the database value (nValue) of the virtual switch to '0' the switch if 'Off' and can be switched to 'On' again (resulting in nValue = '1'). Only switching back to off does not change nValue to '0'.

**Comment by jvandenbroek** [comment]
Looked into the code and looks like this protocol only supports the on command. When switching off, you're actually sending the on command. There is no way to determine what state the relay actually has, so you'd better change it's device to Push On button.

**Comment by gizmocuz** [comment]
Thanks for looking into this !
