### ISSUE TITLE
Editing a hidden device ($myDevice) doesn't display the $ in the name field

### ISSUE THREAD

**Issue by dannybloe** [domoticz/domoticz#1518]
Create a hidden device (name starts with $). Then edit the device. The name field erroneously doesn't show the $ prefix. If you are not aware of this and you just want to change the icon and press save you accidentally change the name and turn the device into a visible device because the $ is removed.

**Comment by gizmocuz** [comment]
I don't experience this behaviour
You press the 'edit' icon from within the devices view ?
It displays the $ sign.
Tested with latest beta, and chrome browser

![image](https://cloud.githubusercontent.com/assets/2265299/26530865/9a33caee-43dd-11e7-8a18-82bf81615fa0.png)

**Comment by dannybloe** [comment]
I can't reproduce it in the latest codebase. I'll keep an eye on it.
