### ISSUE TITLE
Slimme Meter does not show all the statistics

### ISSUE THREAD

**Issue by edegroot-nl** [domoticz/domoticz#1523]
Slimme Meter doesn't show the all the values anymore.
The statistics at night are empty at 0 watts. 
Daytime and weekends works correctly. (last beta version domoticz)

**Comment by gordonb3** [comment]
Unsure what you are referring to. Readings look okay here. What version are you at? "last beta version" is somewhat of a moving target.

**Comment by edegroot-nl** [comment]
I'm at 3.7410.. my readings on the mobile theme are like this:
What i find out is that the readings are normal on the desktop browser theme. (my apologies for the confusing title)
![img_6322](https://cloud.githubusercontent.com/assets/26502612/25713110/e6e8fc12-30f3-11e7-8f1c-01e03ba26c9e.jpg)

**Comment by gordonb3** [comment]
Looks like you disabled graphing of Usage 1 (it's grayed out). If you click on the literal, the graph should return.

**Comment by edegroot-nl** [comment]
I feel stupid now. Damn.. for me it's wise to register on the forum. thank you.

**Comment by gizmocuz** [comment]
Please use our forum next time
