### ISSUE TITLE
Humidity graph shows 'temperature' as label

### ISSUE THREAD

**Issue by koenkooi** [domoticz/domoticz#1533]
I was working on adding info from my Ducobox ventilation unit through the JSON API when I noticed that the resulting graphs for the humidity sensors show 'temperature' and 'degrees':

Version 3.7439 revision a2148229cd8823df4657e9f60a70847b11fb8ccc

![schermafbeelding 2017-05-08 om 09 47 52](https://cloud.githubusercontent.com/assets/259525/25794980/81963d10-33d3-11e7-8511-6fb65c3b748f.png)

**Comment by Tommit1** [comment]
What kind of sensor is this in domoticz ... humidity only or a combined TEMPHUM one?

**Comment by koenkooi** [comment]
Humidity only:
<img width="1208" alt="schermafbeelding 2017-05-08 om 14 45 32" src="https://cloud.githubusercontent.com/assets/259525/25804646/06347608-33fd-11e7-86b4-83046fa1fdf3.png">

**Comment by ikkemaniac** [comment]
2nd that for the virtual humidity sensors as well (HUM only)

**Comment by szczukot** [comment]
I have sensor 
Temp + Humidity + Baro (Type THB1 - BTHR918, BTHGN129) and all graphs is without data :(
I only see current value on sensor.

**Comment by koenkooi** [comment]
Why was this closed? It's still an issue in both master and development.

**Comment by gizmocuz** [comment]
whoops sorry, please contact me on the forum, i would like to have a backup of your database to do some debugging against

**Comment by koenkooi** [comment]
I can't do PMs yet, so here's the topic: https://www.domoticz.com/forum/viewtopic.php?f=6&t=20268

**Comment by koenkooi** [comment]
Fix confirmed:
<img width="1193" alt="schermafbeelding 2017-11-08 om 09 04 05" src="https://user-images.githubusercontent.com/259525/32537691-ccd50e66-c463-11e7-90d0-945c41f5c388.png">

**Comment by szczukot** [comment]
I have 
![image](https://user-images.githubusercontent.com/10205661/32540701-c3937900-c46d-11e7-96e3-891616f21015.png)

![image](https://user-images.githubusercontent.com/10205661/32540842-3ced99c0-c46e-11e7-91c8-3f195a7afc5a.png)

and graph for Weather tab (and last icon - barometr)):
![image](https://user-images.githubusercontent.com/10205661/32540807-1cc2643c-c46e-11e7-97c4-f41e490521bd.png)

graph from first icon (temperature):
![image](https://user-images.githubusercontent.com/10205661/32540873-53d7ee42-c46e-11e7-871c-5ff9508a4033.png)

graph from second icon (humidity):
![image](https://user-images.githubusercontent.com/10205661/32540928-791dfb24-c46e-11e7-94d8-18086c446be7.png)

**Comment by gizmocuz** [comment]
szczukot please create a new issue or contact me directly as I don't think this is related..

**Comment by Pjedr** [comment]
Lik  szczukot commented on 27 Jul 2017 I have sensor Temp + Humidity + Baro (Type THB1 - BTHR918, BTHGN129) and all graphs is without data :( I only see current value on sensor.

All my TempHumBaro meters only shows actual values, no graph in log view, in database is recent history, in custom graph i can see the history lines. It must stll be a bug.

dx | Hurdguod | ID | Unit | Namme | Type | SubType | Data |   |   |   | Lêst sjoen
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | 1537 | RFXtrx433 | 9600 | 0 | Binnen TempFochtBaro | Temp + Humidity + Baro | THB2 - BTHR918N, BTHR968 | 19.0 C, 37 %, 1040 hPa | 7 | Leech |   | 2018-02-26 02:38:25
  | 221 | DarkSky IO Drogeham Thuis | 0001 | 1 | Droegeham TempFochtBaro | Temp + Humidity + Baro | THB1 - BTHR918, BTHGN129 | -4.8 C, 79 %, 1034 hPa | - | - |   | 2018-02-26 02:36:14
  | 225 | DarkSky IO Groningen Werk | 0001 | 1 | Grins TempFochtBaro | Temp + Humidity + Baro | THB1 - BTHR918, BTHGN129 | -4.5 C, 76 %, 1034 hPa | - | - |   | 2018-02-26 02:36:14
  | 168 | Surhuisterveen Centrum | 0001 | 1 | SurhústerfeanTempFochtBaro | Temp + Humidity + Baro | THB1 - BTHR918, BTHGN129 | -3.4 C, 73 %, 1033 hPa | - | - |   | 2018-02-26 02:31:13
  | 1105 | Open Weather Map | 0001 | 1 | OWM TempFochtBaro | Temp + Humidity + Baro | THB1 - BTHR918, BTHGN129 | -9.0 C, 85 %, 1031 hPa | - | - |   | 2018-02-26 02:31:08

**Comment by gizmocuz** [comment]
@Pjedr, i have these sensors as well without issue.
Please upgrade to the latest beta version, next clear your browser cache, next clear the browser app-cache (yes two different things!), and try again. (or open a private browser)
