### ISSUE TITLE
dzVents tmp location

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#1547]
I learned from dannybloe that dzVents will be intergrated in Domoticz.
Please make sure that temporary storage files location could be parameterized because those should be placed on a tmpfs.
Otherwise the SD-card will worn out soon.

**Comment by gizmocuz** [comment]
This means when using linux (raspberry for example) this should be written to /tmp

**Comment by SargonofAssyria** [comment]
Beter would be that it is a parameter in Settings. This way one can also use  USB ssd drive.
But /tmp would be fine too.

**Comment by gizmocuz** [comment]
Why? The  temp folder is exactly made for this purpose

**Comment by SargonofAssyria** [comment]
I am the kind of guys that would like to have everything on special places. But like I wrote /tmp is fine.

**Comment by dannybloe** [comment]
It's on my list to make the location configurable in the settings. Which reminds me... it would be nice if the settings for dzVents are accessible from the web-ui.... /me makes a note
