### ISSUE TITLE
SolarEdge not fetching data in 7477

### ISSUE THREAD

**Issue by Jeffreyvanesch** [domoticz/domoticz#1554]
Domoticz doesn't fetch the newly created solaredge devices when it's added as 'SolarEdge via Web API', When entering the required data (APIkey,Serial&SiteID) the new hardware gets added  but eventually nothing happens.
The log shows Error: SolarEdgeAPI: Error getting http data! 

I'm suspecting that i might be a issue with the code the defined code is; `sURL << "https://monitoringapi.solaredge.com/sites/list?size=1&api_key=" << m_APIKey << "&format=application/json";` This throws a 403 error
Only when using `http://monitoringapi.solaredge.com/1/details.json?api_key=MYAPIKEY&callback=overview` it results in a response.

**Comment by gizmocuz** [comment]
Nothing changed lately, so its not the version.

Also the configuration option only consist of an API key, and no site id

**Comment by Jeffreyvanesch** [comment]
In 7477 it still is a required value to set up the hardware, Leaving it blank doesn't get accepted. See the snippet.

Could such be caused that i don't have full permission to the admin section of the monitoring portal, According to the manual on solaredge it still generates a Site-APIkey when not being a full admin.
![image](https://cloud.githubusercontent.com/assets/25173470/26353974/03f18684-3fc3-11e7-8883-324d30354dd5.png)

**Comment by gizmocuz** [comment]
Then i think you should clear your browser cache + appcache

![image](https://cloud.githubusercontent.com/assets/2265299/26356518/9a338814-3fcc-11e7-935e-709deb52e30d.png)

If it still crashes, please send me a PM on the forum with your API key so i can debug for you

**Comment by Jeffreyvanesch** [comment]
Cleaned up the browser and app cache, eventually ended up with using firefox.

The other fields as shown in your snippet are displaying, The only concern is when clicking add and refreshing the page blanks the Remote Address,Port,UN/PW fields, only the API Key is present afterwards.
Again no devices are showing up in the devices tab while the workers process is started.

Going to retry this later on today (at daylight) to see if this makes a difference. If not i'll send a PM.
![image](https://cloud.githubusercontent.com/assets/25173470/26382523/11255834-402d-11e7-9e6e-e590333d9e8e.png)

EDIT:

Issue resolved after database cleanup.

**Comment by Jeffreyvanesch** [comment]
Iss

**Comment by gizmocuz** [comment]
Could you explain what you did and cleaned? This could be of interest to other users.
Thanks in advance

**Comment by Jeffreyvanesch** [comment]
I've cleaned the chrome (app)cache and removed the solaredge hardware from the database, that did the trick.

I noticed that when it's producing more than 1000 W the counter still shows usage as Watt instead of kWh, any chance this to kWh.

**Comment by gizmocuz** [comment]
Nope sorry, its also clearer to read 3456 Watt instead of 3.4 kWatt

**Comment by coleus74** [comment]
To solve some problems with Fibaro switch i updated Domoticz to the latest available beta version (3.8003) but now i don't get the data from solaredge.

I deleted the hardware and recreated (with only api key) but the log continues to say: Error: SolarEdgeAPI: Error getting http data!

I have seen from the code the check of the url below to verify the http solaredge communication which for me gets the correct data.

https://monitoringapi.solaredge.com/sites/list?size=1&api_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&format=application/json

what can I do?

Thank you

**Comment by MasterCATZ** [comment]
now this is something I was not expecting to see 
I have an solar edge 5000 defiantly going to try and get this working is their a guide for getting API for this ? mine just directs to a site ID

**Comment by gizmocuz** [comment]
Please use our forum

**Comment by tnys** [comment]
I seem to be having the same issue (after upgrading to 3.8153).  I've been checking the source code, and when Domoticz is getting the inverters, it looks for /reporters/list in the XML, while the XML returned by solaredge in my installation returns _/equipmentList/list_. The top-level XML element thus isn't _reporters_, but it is _equipmentlist_.

Below is the snippet returned by SolarEdge API when I list the equipment:

```
<equipmentList>
<count>1</count>
<list>
<name>Inverter 1</name>
<manufacturer>SolarEdge</manufacturer>
<model>------</model>
<serialNumber>7E1A312F-F8</serialNumber>
</list>
</equipmentList>
```

**Comment by gizmocuz** [comment]
I just checked on a friends system, working here.
Are you maybe able to debug/test this and create a patch ?
There have been no changes as far as i know... or see... lets see last changes 5 months ago... so no

**Comment by tnys** [comment]
I have been debugging the issue and have contacted SolarEdge for more information. Will keep you posted here.

**Comment by gizmocuz** [comment]
Dont think that was needed as it was working. Please send me a PM with your login details on the forum and i can have a look if you want

**Comment by tnys** [comment]
I am not allowed to PM yet - account is tnys.
