### ISSUE TITLE
Netatmo anemometer value recognised as temperature

### ISSUE THREAD

**Issue by trandbert37** [domoticz/domoticz#1559]
Hello everyone and thank you for this very beautiful project !

I publish this issue to report a small problem with my Netatmo Anemometer value's.

As you can see in bottom right of this capture, the wind speed value is correct but (in the top right) I have a value of temperature that is not real and that is provided by the anemometer.

![domoticz](https://cloud.githubusercontent.com/assets/16879382/26408598/88ef6190-409e-11e7-8498-3bcf38985138.png)

I use Domoticz beta version 3.7479 (I have the same problem with the stable version).

Trandbert37

**Comment by gizmocuz** [comment]
You say that it is provided by your 'Wind' meter ? do you also see this in the netatmo dashboard?

**Comment by trandbert37** [comment]
Yes, it's provided by my wind meter and I don't see it in Netatmo dashboard

**Comment by gizmocuz** [comment]
It looks like it is the exterieur (outside temp value) but divided by 10)
it is possible to check this if the value is 24 for instance, if you see -2.4 ?
Its a pity they did not install a temp sensor...

**Comment by trandbert37** [comment]
![capture du 2017-05-25 17-56-58](https://cloud.githubusercontent.com/assets/16879382/26458449/9189045c-4173-11e7-9526-92c067d14f8d.png)

It's not that, I thinck that it's the wind orientation value (in degree).

**Comment by gizmocuz** [comment]
Are you able to debug the code?

What do you see as type/subtype for this wind sensor under 'devices'?

**Comment by trandbert37** [comment]
![capture du 2017-05-25 18-05-37](https://cloud.githubusercontent.com/assets/16879382/26458839/c5f752ec-4174-11e7-9d88-c011a4bb7f29.png)

I have this result, but I don't know how to debug

**Comment by Tommit1** [comment]
It's not wind orientation and not outside temperature  .. Have a look... it is 'Temperature ressentie' value of Weather data below in anemometer... it's wind dependent for sure ... or in english it is Chill factor temperature as a separate device.. I just disabled this from being displayed.. don't think this is an 'error'..
or just rename it : Netatmo Chill

**Comment by trandbert37** [comment]
Thanck for your response, I now understand.

It will may be better to have a calculated temperature (normal temperature - chill temperature)
