### ISSUE TITLE
Constants for barometric forecast inconsistent in API

### ISSUE THREAD

**Issue by dannybloe** [domoticz/domoticz#1563]
When calling the json api for updating barometer or temp+hum+baro the forecast value is for each of these calls is inconsistent. E.g. for the first (update barometer) 4 == Thunderstorm while for the latter 4 == Rain. 

Seem like that needs to be fixed (and the docs updated coz that doesn't even mention Thunderstorm).

**Comment by gizmocuz** [comment]
Those are probably also two different device types with their own internal baro forecast calculation.
Yes, there are two systems (unfortunately)

**Comment by gizmocuz** [comment]
But all should be explained correctly in the wiki ?

**Comment by dannybloe** [comment]
It seems it doesn't do any calculation. It just displays whatever value I pass for the forecast. At least that's what I assume😉

**Comment by gizmocuz** [comment]
Yes for virtual devices sure

**Comment by dannybloe** [comment]
That's what I was testing. Dummy devices. It felt weird that for a Baro you have different constant values than for Temp+Hum+Baro. 
And on top of that, the wiki states the wrong constants. As it turns out that for Baro forecast=4 gives you a Thunderstorm and the same value for Temp+Hum+Baro gives you Rain.

So I think someone with more C++ knowledge than me should have a look at the code and see what constants are really accepted and what it means and update the wiki (and if you ask me: the code to make them similar).
🙂

**Comment by gizmocuz** [comment]
I don't think you understand this ... but ok.. let someone else have a look
In the mean time, you now know why this happens

**Comment by dannybloe** [comment]
I updated the wiki so it now reflects the difference between these two devices. Case closed.
