### ISSUE TITLE
Counter for Water goes insane sometimes

### ISSUE THREAD

**Issue by empierre** [domoticz/domoticz#1566]
Hi,

  Tried to understand the issue, but couldn't.

  Settings for water = 1000 (in liter)

 called by: curl -s "http://$domo_ip:$domo_port/json.htm?type=command&param=udevice&idx=129&svalue=425329"

  value set in domoticz: 18 10^18

![menu_011](https://cloud.githubusercontent.com/assets/7287178/26495327/8506c4e8-4223-11e7-958e-a8be5e5bbf97.png)

  sometime it is ok, impossible to find a reason why

**Comment by JurikRistjouw** [comment]
I have the same issue sometimes. I think it is when the sensor is exactly in between reflective and non reflective material. This way, the sensor is blinking on/off rapidly and makes some interesting readings. I think the only solution is building in some kind of hysteresis with a schmit trigger or analogue reading with a margin. It is hard to debounce these kind of sensors i guess.

**Comment by jvandenbroek** [comment]
I suppose you're using GPIO? If so, you could try to set the period and or debounce time higher in hardware settings. I actually wrote this function for my old gas meter which had similar issues.  

Edit: Ah I see you're calling it with curl, my mistake. The calling script should indeed use some form of hysteresis to prevent those spikes.

**Comment by gizmocuz** [comment]
A capacitor might help... dont think this is a domoticz issue ?

**Comment by empierre** [comment]
Hello,

  This is a mysensors with a reed, and I have a gateway between.
  There is no message storm thanks to it (and I have the flow info too)
   I don't understand why the full index in wrote in the database rather than the delta, it is because on the same hour something has already been calculated ? How is it calculated today ?

  Before this happened when I have a power shortage, so not very often, at the moment without power shortage every day....  and in my logs I have all API calls so I know there is nothing on the origin.

 Same calls 10 min before were ok, then it goes insane ... so I have to remove the value and lose the whole day data...

**Comment by gizmocuz** [comment]
when your mysensor node is started, it should 'first' request the last counter value from domoticz
i quess it might start with 0 in your case ?

**Comment by empierre** [comment]
No, I persist it in a VAR in DZ and retrieve it. I will not log till it has the answer.

I don't know if this is linked to the value (425329) but it happens everyday now

**Comment by PHIL-IP** [comment]
Same thing for me as you can see here : https://easydomoticz.com/forum/viewtopic.php?f=20&t=4118
For me the value is **always** the same -> 18 446 744 027 136 000
This is happen always when the sensor is power ON.
The value is saved in V_VAR4 and restored via a request() in the setup.

**Comment by gizmocuz** [comment]
I think this needs to be fixed in the sensor's code, and is not related to domoticz.. but the sollution would be nice to post here..
I am not having this issue anymore as i tweaked my mysensors code.. but unfortunately have lost the source file

**Comment by JurikRistjouw** [comment]
any thoughts on what you changed?

**Comment by gizmocuz** [comment]
Yes.. the request of the last meter value from Domoticz
