### ISSUE TITLE
Don't turn off after delay if already turned off

### ISSUE THREAD

**Issue by mu3** [domoticz/domoticz#1573]
Domoticz v3.7468

**Comment by gizmocuz** [comment]
Not all hardware can send it's actual state back to Domoticz. For instance Kaku/Coco (433Mhz) hardware.
So you can not tell if something was really off.
You can make your own blockly/script that checks if something is not off and turn it off.
Please use our Forum

**Comment by mu3** [comment]
![monosnap domoticz 2017-05-29 16-29-11](https://cloud.githubusercontent.com/assets/661220/26551869/43a92588-448d-11e7-8cb1-c7ed9a70b453.png)
I mean when I have auto turning off timeout and have turned off the device manually (through Domoticz) before this timeout fires, no need to send additional command (clear the timeout).
