### ISSUE TITLE
Pushbullet doesn't work

### ISSUE THREAD

**Issue by mu3** [domoticz/domoticz#1574]
Domoticz v3.7468

**Comment by jvandenbroek** [comment]
Working fine here on latest build (v3.7540). Could you please try it out first on the latest beta and report back? Thank you.

**Comment by mu3** [comment]
No Update Available !...
![screen shot 2017-05-29 at 16 31 05](https://cloud.githubusercontent.com/assets/661220/26551707/7d93ce52-448c-11e7-9332-e9c37f7624bd.png)
![screen shot 2017-05-29 at 16 32 42](https://cloud.githubusercontent.com/assets/661220/26551708/7d99b1be-448c-11e7-9b28-697a5c5a5857.png)

I'm on mac

**Comment by jvandenbroek** [comment]
Do you get an error message in the log? Are using Test in Settings and does it say the notification has been sent?

**Comment by mu3** [comment]
![monosnap pushbullet - your devices working better together 2017-05-29 18-39-29](https://cloud.githubusercontent.com/assets/661220/26555666/e3716ab0-449e-11e7-8d64-1f5d142fe585.png)
![screen shot 2017-05-29 at 18 40 53](https://cloud.githubusercontent.com/assets/661220/26555667/e39665e0-449e-11e7-8f5c-5becd8d361a5.png)
![screen shot 2017-05-29 at 18 42 46](https://cloud.githubusercontent.com/assets/661220/26555668/e3a4c6b2-449e-11e7-9059-c878cf8f46d4.png)

## Same on v3.7541

**Comment by jvandenbroek** [comment]
I'd suspect this is platform related since you're on the Mac build. 

Could you set https://www.google.com under Custom HTTP/Action, leave all other fields empty and test? Look in the log for Notification sent (http). If it says Failed, I believe something is wrong with the Curl implementation. Otherwise, if it succeeds, we need to look further into this specific issue.

**Comment by mu3** [comment]
![screen shot 2017-05-30 at 16 15 42](https://cloud.githubusercontent.com/assets/661220/26585021/99e666c4-4553-11e7-9fb8-8ae09439d481.png)

`2017-05-30 16:16:05.408 2017-05-30 16:16:05.408 Notification sent (http) => Success`

Which actually does the same:

![screen shot 2017-05-30 at 16 16 35](https://cloud.githubusercontent.com/assets/661220/26585052/ad30e34e-4553-11e7-88e0-d1d15a8b5298.png)

**Comment by jvandenbroek** [comment]
Interesting, that's seems OK. Did it actually work before last Sunday? If that's the case, I think the build version you opened the issue with was still showing an old cached version.. There has been some changes in the notification system a few days ago, but I need to know for sure that it's related to this issue.

Edit: Could you actually check https://www.google.com or some other domain on HTTPS? That might be the issue.

**Comment by mu3** [comment]
I've just started using Domoticz 🤷

**Comment by jvandenbroek** [comment]
Hehe OK. But could you please test https:// in the URL/action field, so I know if there is an issue with SSL on Mac. Simply https://www.google.com should give success in log. The problem seems that you won't get any response from the Pushbullet API, since the log shows "Pushbullet: " without any response messages (which normally help to indicate the issue).

**Comment by mu3** [comment]
Sure!

![screen shot 2017-05-30 at 18 38 46](https://cloud.githubusercontent.com/assets/661220/26591785/64554520-4567-11e7-8f04-422a0e499591.png)

`2017-05-30 18:38:44.943 2017-05-30 18:38:44.943 Notification sent (http) => Success`

**Comment by jvandenbroek** [comment]
Thank you! So that's also not the problem... Hmm strange issue. Could you try the following in terminal:

```
curl -k -u <MY_API_KEY>: -X POST https://api.pushbullet.com/v2/pushes --header 'Content-Type: application/json' --data-binary '{"type": "Test", "title": "Test, "body": "Test"}'

curl -u <MY_API_KEY>: -X POST https://api.pushbullet.com/v2/pushes --header 'Content-Type: application/json' --data-binary '{"type": "Test", "title": "Test, "body": "Test"}'

curl --header 'Access-Token: <MY_API_KEY>' -X POST https://api.pushbullet.com/v2/pushes --header 'Content-Type: application/json' --data-binary '{"type": "Test", "title": "Test, "body": "Test"}'
```

Where you replace <MY_API_KEY> with your own API key? Does this work? (make sure you include the ' at the end of the line which I just edited in)

Just added 2 more commands, could you test them in order and tell me if one or all of them succeed?

**Comment by mu3** [comment]
Here you go (Domoticz server is on a mac at home):

![shot](https://cloud.githubusercontent.com/assets/661220/26594323/ec31b66a-456f-11e7-98bb-b81c7051e166.png)

**Comment by mu3** [comment]
Just checked Prowl, also doesn't work

UPDATE:
Test notification is sent with priority `-100`
>2017-05-30 19:27:56.594 2017-05-30 19:27:56.594 Error: Prowl: 
>Field not valid: Priority must be in range [-2, 2]
>2017-05-30 19:27:56.594 2017-05-30 19:27:56.594 Error: Notification sent (prowl) => Failed

So with a real priority it does work:
>2017-05-30 20:36:00.429 2017-05-30 20:36:00.429 Notification sent (prowl) => Success

**Comment by gizmocuz** [comment]
Prowl works here

**Comment by mu3** [comment]
Used actual key instead of <MY_API_KEY>

    curl -k -u <MY_API_KEY>: -X POST https://api.pushbullet.com/v2/pushes --header 'Content-Type: application/json' --data-binary '{"type": "Test", "title": "Test, "body": "Test"}'
    → curl: (35) Server aborted the SSL handshake

    curl -u <MY_API_KEY>: -X POST https://api.pushbullet.com/v2/pushes --header 'Content-Type: application/json' --data-binary '{"type": "Test", "title": "Test, "body": "Test"}'
    → {"error":{"code":"invalid_request","type":"invalid_request","message":"Failed to decode JSON body.","cat":"(=^‥^=)"},"error_code":"invalid_request"}

    curl --header 'Access-Token: <MY_API_KEY>' -X POST https://api.pushbullet.com/v2/pushes --header 'Content-Type: application/json' --data-binary '{"type": "Test", "title": "Test, "body": "Test"}'
    → {"error":{"code":"invalid_request","type":"invalid_request","message":"Failed to decode JSON body.","cat":"(=^‥^=)"},"error_code":"invalid_request"}


Fixed the typos:

    curl -u <MY_API_KEY>: -X POST https://api.pushbullet.com/v2/pushes --header 'Content-Type: application/json' --data-binary '{"type":"note","title":"Test","body":"Test"}'
    → {"active":true,"iden":…

**Comment by jvandenbroek** [comment]
Oh sorry, I suppose that last 2 work when you use "type:": "note" instead of test in the json body. Interesting to see the first fails, guess the used certificate isn't in your certificate store. Not sure how it works on Mac, but I'll look into it.

**Comment by mu3** [comment]
@jvandenbroek See the update about Prowl

**Comment by jvandenbroek** [comment]
@mu3 Will fix the Prowl testing, but that is not the cause of this issue (test Pushbullet works fine here). I think it has to do with how curl communicates on Mac over SSL. Maybe we need to force it to use TLS instead of SSLv2, will do some more checks.

**Comment by jvandenbroek** [comment]
Could you try the latest beta and report back? Thank you.

**Comment by gizmocuz** [comment]
This is why we have a forum...

**Comment by mu3** [comment]
Sorry I didn't respond, and sorry I've moved to Home Assistant.

**Comment by gizmocuz** [comment]
No worries, thanks for the feedback!
