### ISSUE TITLE
EvohomeWeb.cpp: error: expected ')' before 'PRIu64' - crosscompile for powerpc

### ISSUE THREAD

**Issue by trusnak** [domoticz/domoticz#1577]
```
[ 44%] Building CXX object CMakeFiles/domoticz.dir/hardware/EvohomeWeb.cpp.o
/home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878/hardware/EvohomeWeb.cpp: In member function 'void CEvohomeWeb::DecodeZone(CEvohomeWeb::zone*)':
/home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878/hardware/EvohomeWeb.cpp:433:72: error: expected ')' before 'PRIu64'
    m_sql.safe_query("UPDATE DeviceStatus SET Name='%q' WHERE (ID == %" PRIu64 ")", ndevname.c_str(), DevRowIdx);
                                                                        ^
/home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878/hardware/EvohomeWeb.cpp: In member function 'void CEvohomeWeb::DecodeDHWState(CEvohomeWeb::temperatureControlSystem*)':
/home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878/hardware/EvohomeWeb.cpp:475:72: error: expected ')' before 'PRIu64'
    m_sql.safe_query("UPDATE DeviceStatus SET Name='%q' WHERE (ID == %" PRIu64 ")", ndevname.c_str(), DevRowIdx);
                                                                        ^
/home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878/hardware/EvohomeWeb.cpp:482:86: error: expected ')' before 'PRIu64'
    m_sql.safe_query("UPDATE DeviceStatus SET DeviceID='%q',Name='%q' WHERE (ID == %" PRIu64 ")", dhwdata["dhwId"].c_str(), ndevname.c_str(), DevRowIdx);
                                                                                      ^
/home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878/hardware/EvohomeWeb.cpp: In member function 'uint8_t CEvohomeWeb::GetUnit_by_ID(long unsigned int)':
/home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878/hardware/EvohomeWeb.cpp:547:87: error: expected ')' before 'PRIu64'
     m_sql.safe_query("UPDATE DeviceStatus SET Name='%q',DeviceID='%q' WHERE (ID == %" PRIu64 ")", devname, ID, DevRowIdx);
                                                                                       ^
make[5]: *** [CMakeFiles/domoticz.dir/build.make:1439: CMakeFiles/domoticz.dir/hardware/EvohomeWeb.cpp.o] Error 1
make[5]: Leaving directory '/home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878'
make[4]: *** [CMakeFiles/Makefile2:68: CMakeFiles/domoticz.dir/all] Error 2
make[4]: Leaving directory '/home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878'
make[3]: *** [Makefile:137: all] Error 2
make[3]: Leaving directory '/home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878'
make[2]: *** [Makefile:77: /home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878/.built] Error 2
make[2]: Leaving directory '/home/linker/turris-power/feeds/turrispackages/cznic/domoticz'
make[1]: *** [package/Makefile:188: package/feeds/turrispackages/domoticz/compile] Error 2
make[1]: Leaving directory '/home/linker/turris-power'
make: *** [/home/linker/turris-power/include/toplevel.mk:183: package/domoticz/compile] Error 2

```
It looks like wrongly escaped sql query.

**Comment by jvandenbroek** [comment]
https://stackoverflow.com/questions/14535556/why-doesnt-priu64-work-in-this-code

**Comment by trusnak** [comment]
jvandenbroek: you are right, this commit tried to solve it: 
https://github.com/domoticz/domoticz/commit/fce3667343b86aa5e7cd61baf03c68b26e2b190c
I don't understand why the macro was commented out:
`+//#define __STDC_FORMAT_MACROS`

**Comment by jvandenbroek** [comment]
I think the author tested the code and didn't see a need for this macro. Let's see what @gordonb3 has to say about it.

**Comment by gordonb3** [comment]
Hmm, you're right. That does seem wrong. I'll verify

**Comment by trusnak** [comment]
I tried to uncomment the macro with:
```
--- hardware/EvohomeWeb.orig	2017-05-29 13:06:42.334309162 +0200
+++ hardware/EvohomeWeb.cpp	2017-05-29 13:06:52.444308850 +0200
@@ -18,7 +18,7 @@
 #include "../main/mainworker.h"
 #include "../json/json.h"
 #include "hardwaretypes.h"
-//#define __STDC_FORMAT_MACROS
+#define __STDC_FORMAT_MACROS
 #include <inttypes.h>
 #include "../main/localtime_r.h"
 #include "../httpclient/HTTPClient.h"
```

No success :(

**Comment by jvandenbroek** [comment]
Try removing CMakeCache.txt. All other files seem to incorporate this macro and you're only failing on the EvohomeWeb, so it should be the cause of it's failure.

**Comment by trusnak** [comment]
I removed CMakeCache.txt before recompile. It seems to be problem with escaping. Same issue is with mainworker.cpp, see one of the error:
```
[ 25%] Building CXX object CMakeFiles/domoticz.dir/main/mainworker.cpp.o
/home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878/main/mainworker.cpp: In member function 'void MainWorker::ProcessRXMessage(const CDomoticzHardwareBase*, const unsigned char*, const char*, int)':
/home/linker/turris-power/build_dir/target-powerpc_8540_uClibc-0.9.33.2/domoticz-3.5878/main/mainworker.cpp:2372:75: error: expected ')' before 'PRIu64'
   m_sql.safe_query("UPDATE DeviceStatus SET BatteryLevel=%d WHERE (ID==%" PRIu64 ")", BatteryLevel, DeviceRowIdx)
```
What about to use this:
`m_sql.safe_query("UPDATE DeviceStatus SET BatteryLevel=%d WHERE (ID==%' PRIu64 ')", BatteryLevel, DeviceRowIdx`
instead of original one with "":
`m_sql.safe_query("UPDATE DeviceStatus SET BatteryLevel=%d WHERE (ID==%" PRIu64 ")", BatteryLevel, DeviceRowIdx`
With those changes at all occurrences, it can be compiled without error - tested. So simple %s/"PRIu64"/'PRIu64'/g on mainworker.cpp and EvohomeWeb.cpp. But, I'm not sure if this change will affect expected functionality.

**Comment by gizmocuz** [comment]
there is also a cmake cache folder

**Comment by trusnak** [comment]
Openwrt build system is removing whole directory before recompile ;)

**Comment by gordonb3** [comment]
Had a look in my logs. The thing with the change referenced above was that I did not encounter the issue in my first version of the code (which did include the problematic SQL statements). The problem just suddenly popped up and yes that stackoverflow message got me going again. I have no clue why and how it got commented out.

I have some code additions just about ready for push and will make sure this is corrected as well

**Comment by gordonb3** [comment]
PS: might want to note that the PRIu64 usage and corresponding MACRO definitions are in other files as well.

**Comment by trusnak** [comment]
Compilation is successful if you will replace all occurrences of " PRIu64 " with ' PRIu64 ', but then there is a problem with SQL errors in the log:
Error: SQL Query("UPDATE DeviceStatus SET BatteryLevel=255 WHERE (ID==") : near "==": syntax error
So my theory was wrong. Sorry.

**Comment by jvandenbroek** [comment]
It's a long shot, but could it be caused by the inclusion of inttypes.h in MQTT/uthash.h without the macro defined? According to https://stackoverflow.com/a/30851225 the macro should always be defined before inclusion.

**Comment by gordonb3** [comment]
Hard to say. You'd need to follow the complete dependency tree to find where it could include inttypes. Don't think it would have anything to do with mosquitto though.

In any case I pushed my updates and just did a full (cross) compile without issues.

**Comment by jvandenbroek** [comment]
But I find it interesting to see that this user had the same issue with a PowerPC toolchain, which indicates that the PPC compiler is behaving differently. It is indeed the only occurrence which doesn't define the macro and Mosquitto seems to be included on top. But I'm not sure if how the dependency tree of the compiler works, but I think it's worth a shot.

This is of course not related to any of your code @gordonb3, but could solve the issue for @trusnak

**Comment by Jumbotroll** [comment]
Same error when try to cross compile for Synology arch-88f6281.
x86, armadaxp,armada370,armada375 and alpine all ok.

[ 22%] Building CXX object CMakeFiles/domoticz.dir/main/mainworker.cpp.o
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp: In member function 'bool MainWorker::AddHardwareFromParams(int, const string&, bool, _eHardwareTypes, const string&, short unsigned int, const string&, const string&, const string&, const string&, int, int, int, int, int, int, int, bool)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:999:19: error: expected type-specifier before 'Rtl433'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:999:19: error: cannot convert 'int*' to 'CDomoticzHardwareBase*' in assignment
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:999:19: error: expected ';' before 'Rtl433'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp: In member function 'void MainWorker::ProcessRXMessage(const CDomoticzHardwareBase*, const unsigned char*, const char*, int)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:2364:75: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:2372:69: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp: In member function 'void MainWorker::decode_Rain(int, _eHardwareTypes, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:2975:56: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp: In member function 'void MainWorker::decode_LimitlessLights(int, _eHardwareTypes, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:5536:60: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp: In member function 'void MainWorker::decode_evohome2(int, _eHardwareTypes, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:6274:71: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp: In member function 'void MainWorker::decode_evohome1(int, _eHardwareTypes, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:6332:71: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp: In member function 'void MainWorker::decode_evohome3(int, _eHardwareTypes, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:6456:55: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp: In member function 'void MainWorker::decode_CartelectronicTIC(int, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:10377:29: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp: In member function 'bool MainWorker::GetSensorData(uint64_t, int&, std::string&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:10587:116: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:10641:83: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:10702:95: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp: In member function 'bool MainWorker::SwitchLightInt(const std::vector<std::basic_string<char> >&, std::string, int, int, bool)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:11661:81: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp: In member function 'bool MainWorker::SwitchLight(uint64_t, const string&, int, int, bool, int)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:11770:132: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp: In member function 'bool MainWorker::SwitchScene(uint64_t, const string&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:12325:74: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:12338:99: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:12350:108: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:12363:113: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544/main/mainworker.cpp:12390:101: error: expected ')' before 'PRIu64'
make[5]: *** [CMakeFiles/domoticz.dir/main/mainworker.cpp.o] Error 1
make[5]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544'
make[4]: *** [CMakeFiles/domoticz.dir/all] Error 2
make[4]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7544'
make[2]: *** [compile_target] Error 2
make[2]: Leaving directory `/home/dahl/spksrc-master/cross/domoticz'
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz'
make: [arch-88f6281] Error 2 (ignored)

**Comment by gizmocuz** [comment]
As you can see, quite a lot of classes uses this
This is there for quite a long time, so something must have changed then ?

**Comment by gordonb3** [comment]
Looks like something went wrong with pull request #1570 

There's a `break` missing at line 998. Don't think it could cause this particular issue though.

**Comment by jvandenbroek** [comment]
Good catch, switches don't work sequentially so it could be the cause of more undefined behavior?

**Comment by gordonb3** [comment]
Seems to run fine, but I guess there could be issues if I try to add devices because the hardware name for my evohome installation is now probably bound to the CRtl433 class.

As for the 7544 release I can't reproduce the error on any of my systems. Have to note though that I run this from a package manager (Gentoo ebuild) that starts with an empty work folder every time, so I have no precompiled items in there that might say something else than the current code does.

Also: I cross compile against the exact same SoC as that synology box has.

**Comment by gizmocuz** [comment]
Why would it be bound to the 'CRtl433' ?

**Comment by gordonb3** [comment]
Because hardwaretype is first bound to CEvohomeWeb, but since it does not return (`break`) it will next bind to CRtl433.

Ah! Wait up. Seems I forgot to restart the service after the merge. It actually does not start the evohome worker at all but I now have an RTL433 worker instead. Somehow I'm also seeing log times replicated twice on most lines now. Definitely bad, but again no compile issues.

**Comment by Jumbotroll** [comment]
It's still fails when cross compile for Synology arch-88f6281 armv5.
Marvell 88F628x Linux 2.6.32
6281-gcc464_glibc215_88f6281-GPL

[ 24%] Building CXX object CMakeFiles/domoticz.dir/main/Logger.cpp.o
[ 24%] Building CXX object CMakeFiles/domoticz.dir/main/LuaCommon.cpp.o
[ 24%] Building CXX object CMakeFiles/domoticz.dir/main/LuaHandler.cpp.o
[ 25%] Building CXX object CMakeFiles/domoticz.dir/main/mainworker.cpp.o
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp: In member function 'void MainWorker::ProcessRXMessage(const CDomoticzHardwareBase*, const unsigned char*, const char*, int)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:2365:75: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:2373:69: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp: In member function 'void MainWorker::decode_Rain(int, _eHardwareTypes, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:2976:56: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp: In member function 'void MainWorker::decode_LimitlessLights(int, _eHardwareTypes, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:5537:60: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp: In member function 'void MainWorker::decode_evohome2(int, _eHardwareTypes, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:6275:71: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp: In member function 'void MainWorker::decode_evohome1(int, _eHardwareTypes, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:6333:71: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp: In member function 'void MainWorker::decode_evohome3(int, _eHardwareTypes, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:6457:55: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp: In member function 'void MainWorker::decode_CartelectronicTIC(int, const tRBUF*, MainWorker::_tRxMessageProcessingResult&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:10378:29: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp: In member function 'bool MainWorker::GetSensorData(uint64_t, int&, std::string&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:10588:116: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:10642:83: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:10703:95: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp: In member function 'bool MainWorker::SwitchLightInt(const std::vector<std::basic_string<char> >&, std::string, int, int, bool)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:11662:81: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp: In member function 'bool MainWorker::SwitchLight(uint64_t, const string&, int, int, bool, int)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:11771:132: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp: In member function 'bool MainWorker::SwitchScene(uint64_t, const string&)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:12326:74: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:12339:99: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:12351:108: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:12364:113: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/main/mainworker.cpp:12391:101: error: expected ')' before 'PRIu64'
make[5]: *** [CMakeFiles/domoticz.dir/main/mainworker.cpp.o] Error 1
make[5]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546'
make[4]: *** [CMakeFiles/domoticz.dir/all] Error 2
make[4]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546'
make[2]: *** [compile_target] Error 2
make[2]: Leaving directory `/home/dahl/spksrc-master/cross/domoticz'
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz'
make: [arch-88f6281] Error 2 (ignored)

**Comment by gordonb3** [comment]
Okay, since apparently the order of loading include files can be the issue, how about try and move the following section starting at line 144 in mainworker.cpp to above the hardware includes (at line 21)?

> #include "mainstructs.h"
#define __STDC_FORMAT_MACROS
#include <inttypes.h>

**Comment by Jumbotroll** [comment]
@gordonb3 
I moved 
#include "mainstructs.h"
#define __STDC_FORMAT_MACROS
#include <inttypes.h>
above line 21 and now it's failed in 44% when cross compile 88f6281 armv5.

[ 43%] Building CXX object CMakeFiles/domoticz.dir/hardware/EvohomeSerial.cpp.o
[ 44%] Building CXX object CMakeFiles/domoticz.dir/hardware/EvohomeWeb.cpp.o
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/hardware/EvohomeWeb.cpp: In member function 'void CEvohomeWeb::DecodeZone(CEvohomeWeb::zone*)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/hardware/EvohomeWeb.cpp:497:72: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/hardware/EvohomeWeb.cpp: In member function 'void CEvohomeWeb::DecodeDHWState(CEvohomeWeb::temperatureControlSystem*)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/hardware/EvohomeWeb.cpp:539:72: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/hardware/EvohomeWeb.cpp:546:86: error: expected ')' before 'PRIu64'
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/hardware/EvohomeWeb.cpp: In member function 'uint8_t CEvohomeWeb::GetUnit_by_ID(long unsigned int)':
/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546/hardware/EvohomeWeb.cpp:611:87: error: expected ')' before 'PRIu64'
make[5]: *** [CMakeFiles/domoticz.dir/hardware/EvohomeWeb.cpp.o] Error 1
make[5]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546'
make[4]: *** [CMakeFiles/domoticz.dir/all] Error 2
make[4]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-88f6281-6.1/domoticz-r7546'
make[2]: *** [compile_target] Error 2
make[2]: Leaving directory `/home/dahl/spksrc-master/cross/domoticz'
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz'
make: [arch-88f6281] Error 2 (ignored)

**Comment by gordonb3** [comment]
Makes sense. That indicates that there must be something in EvohomeWeb.h that causes the incorrect loading error. I just noticed I have an include in there that doesn't really need to be there. Could you try [this patch](https://github.com/gordonb3/domoticz/commit/374f81e.patch) and see if that resolves the issue?

**Comment by Jumbotroll** [comment]
@gordonb3 
Build ok on 88f6281 armv5 with latest patch :-)
[ 99%] Building CXX object CMakeFiles/domoticz.dir/tinyxpath/xpath_stream.cpp.o
[ 99%] Building CXX object CMakeFiles/domoticz.dir/tinyxpath/xpath_stack.cpp.o
[100%] Building CXX object CMakeFiles/domoticz.dir/tinyxpath/xpath_static.cpp.o
[100%] Building CXX object CMakeFiles/domoticz.dir/tinyxpath/xpath_syntax.cpp.o
Linking CXX executable domoticz

**Comment by gordonb3** [comment]
Thanks. So it was curl. I'll push that patch on to mainline.

**Comment by Jumbotroll** [comment]
@gordonb3 
:+1: 
And move the
#include "mainstructs.h"
#define __STDC_FORMAT_MACROS
#include <inttypes.h>
above line 21 ??

**Comment by gordonb3** [comment]
Doesn't appear to be necessary to fix this issue. If moving curl from the header file to the corresponding code file fixed it for the hardware module it will also fix it for mainworker. It's definitely something to watch out for when adding new hardware, so yes it's probably not a bad idea but I like gizmocuz to call it if we should.

**Comment by Jumbotroll** [comment]
@gordonb3 
Ok, so I did a test build here now with the patch and without move the 
#include "mainstructs.h"
#define __STDC_FORMAT_MACROS
#include <inttypes.h>
and that worked nice, so the EvohomeWeb.h patch did the trick :-)

**Comment by gordonb3** [comment]
Had to. BTW it's not that I don't need curl at all, it just didn't need to be in the header file. There is of course still a future hazard of a class being added where a specific include in the header file can't be avoided and cause the issue to re-emerge.

**Comment by trusnak** [comment]
Everything works for me, now. Thanks a lot for fast solution. OpenWrt package for powerpc built without any problems.

**Comment by gordonb3** [comment]
No worries. Jumbotroll's feedback helped a lot in identifying the source of the problem.
