### ISSUE TITLE
RFE: Reload SSL certificate automatically

### ISSUE THREAD

**Issue by dwmw2** [domoticz/domoticz#1590]
I suspect a large number of people are using LetsEncrypt certificates now, which have a relatively short lifetime and are automatically renewed. It would be really useful for Domoticz to automatically spot that the file has changed, and reload it. Or at least to have a command to reload it instead of having to completely restart.

**Comment by gizmocuz** [comment]
Yes, maybe we can add an kind of extension in domoticz to enable/auto renew this ?

**Comment by gizmocuz** [comment]
No response, closing issue, please use our forum!

**Comment by dwmw2** [comment]
When I finally got round to it, this turned out to be trivial.
Each time we accept an incoming connection, we prepare the TLS session for next one. We can just reload the cert each time.

#2407
