### ISSUE TITLE
Xiaomi Gateway use with homebridge

### ISSUE THREAD

**Issue by theo-69** [domoticz/domoticz#1598]
I am trying to use the Xiaomi Gateway with Homebridge. I can see all Devices in Homebridge but I can not use them, they don't show any function :-(

**Comment by gizmocuz** [comment]
Please use our forum.

**Comment by theo-69** [comment]
LOL

**Comment by gizmocuz** [comment]
Next time please 'read' the message before you post here.
Its hard to miss when you create a new issue.
