### ISSUE TITLE
RFXcom T13 Screenline Blinds

### ISSUE THREAD

**Issue by Spazpeker** [domoticz/domoticz#1600]
Hello
I can only see Open Close and stop commands for blinds
whereas the Screenline has open Close Angle+ Angle -
there only seems to be open close and stop available for Blind control ?

**Comment by gizmocuz** [comment]
That's correct, it has not been implemented.
Maybe you could add an additional blind type with angle support ?
Which hardware are you using ?

**Comment by Spazpeker** [comment]
I have the domoticz running on a Pi 3

**Comment by Spazpeker** [comment]
How do i add an additional blind type ?
