### ISSUE TITLE
1-Wire DS2450 Quad voltage sensor not properly recognised

### ISSUE THREAD

**Issue by tparvais** [domoticz/domoticz#1618]
Hello

I've a DS2450 (Quad voltage ADC) used for anomometer in AAG weatherstation. (Serie 0x20).
In domoticz, I see only one unique value instead of 4:
_115 1-Wire 0004 0 Unknown RFXSensor Voltage 4642 mV - - Ajouter un dispositifRenommer le dispositif Log 2017-06-13 13:02:14_

The DS2450 is behind a master hub hobby board, connected via Serial/USB on a PI3.
Via OWFS, I see correctly all the values of the DS2450. (volt.A volt.B...)

I think there is a problem in in 1WireByOWFS.cpp:

```
default:
      {
         [b]fileName.append("/volt.").append(1,'A'+unit)[/b];
         break;
      }
```

that gives volt.A1, volt.A2...

instead of volt.A volt.B volt.C & volt.D which is the real names

Possible to correct ?

**Comment by gizmocuz** [comment]
Thanks for reporting.
Made some changes, and it should be solved in beta 7970
Please confirm if its working correctly

**Comment by tparvais** [comment]
Hello
It seems to work now. thank you

However, when you have many 1-wire sensors, discovering the sensor is a big challenge as the 1-wire address is not displayed correctly in device list. Watch this photo:

![image](https://user-images.githubusercontent.com/3889811/27122954-9a5d69aa-50ec-11e7-9de1-861b3112e537.png)


The ID is wrong. 

Thomas

**Comment by gizmocuz** [comment]
you link to the image does not work, you can copy and paste the image in github
What is wrong with the ID ? Do note we only take part of the ID

**Comment by tparvais** [comment]
photo uploaded. The problem is indeed on the fact the ID is too much truncated or not related to the 1-wire address

**Comment by gizmocuz** [comment]
Why is that a problem? It should work?

**Comment by tparvais** [comment]
With many 1-wire, it almost impossible to identify  which domoticz line belongs to which 1-wire sensor with truncated id. 

Look at the photo: I don't have 1-wire with ID 194, 0001, 0002, ... I don't know from where these numbers are coming ==> I cannot link this with a real sensor.

71CA: this is truncated 1-wire address, we can manage, but not obvious at all

Maybe it's another bug ?

**Comment by gizmocuz** [comment]
It is intended

**Comment by tparvais** [comment]
I agree to close, Quad value is solved.
But I don't understand why 1. it is intendend to truncate or 2. use 'random' ID for 1-wire sensor instead of their full address. Hope you understand me correctly about these 2 points ?

**Comment by gizmocuz** [comment]
This is because of the internal handling and value size limitation

**Comment by MasterCATZ** [comment]
1-wire sensor should use their full address , domoticz capability's are being greatly crippled using truncated 'random' ID's

**Comment by gizmocuz** [comment]
Please don't cross post
