### ISSUE TITLE
Hobby-board barometer DS2438 recognised as "Solar Radiation"

### ISSUE THREAD

**Issue by tparvais** [domoticz/domoticz#1621]
Hello

I connected a DS2438 hobby board barometer. It is recognised by Domoticz 3.7679 as "solar radiation" and not barometer.

Address is 26.775CB5000000

109 1-Wire 43 1 Solar Radiation General Solar Radiation 1000.0 Watt/m2 - - Ajouter un dispositifRenommer le dispositif Log 2017-06-13 21:16:55
108 1-Wire 775C 92 Temperature Temp LaCrosse TX3 31.8 C - - Ajouter un dispositifRenommer le dispositif Log 2017-06-13 21:16:55
-Solar radiation is crazy: it is supposed to be pressure

1WireByOWFS.cpp:

float C1WireByOWFS::GetPressure(const _t1WireDevice& device) const
{
   std::string realFilename = device.filename + nameHelper(device.filename, device.family); // for family 26 (DS2438) + pressure + HobbyBoards

   std::string readValue=readRawData(std::string(realFilename+"/pressure"));
   if (readValue.empty())
      return -1000.0;
   return static_cast<float>(atof(readValue.c_str()));

I suspect the owfs path is wrong. Unfortunately, there is is no debug info.

My full path (including master hub) is /mnt/1wire/1F.313104000000/main/26.775CB5000000/B1-R1-A/pressure

Any idea ?

Thank you

**Comment by gizmocuz** [comment]
Please use our forum

**Comment by tparvais** [comment]
Already done
[http://www.domoticz.com/forum/viewtopic.php?f=27&t=17944](url)
. I suspect a rela bug behind this. 

Thank you
