### ISSUE TITLE
Weight scale virtual sensor inconsistency

### ISSUE THREAD

**Issue by ben423423n32j14e** [domoticz/domoticz#1632]
Click "Log" on the sensor and look at Month and Year, title is hard fixed to "BWR102 Last Month", should be changed to "Weight Last Month" and "Weight Last Year".

Minor I know but not consistent with Sound Level, Voltage and Watts virtual sensors etc...

**Comment by gizmocuz** [comment]
Could you make a patch for this ?

**Comment by gizmocuz** [comment]
Patch not working ?

**Comment by ben423423n32j14e** [comment]
It works but I'm not sure RFXtrx.h is the right place to put #define sTypeWEIGHT 0x3

Is there a better place to define it? Also I don't know what 0x3 is, I just incremented it...

First attempt at using Visual Studio with Domoticz...

**Comment by gizmocuz** [comment]
No you have to place it in the same header where pTypeGeneral is defined

**Comment by gizmocuz** [comment]
Is this still something you would like to make a patch for ?

**Comment by ben423423n32j14e** [comment]
I don't have a sufficient understanding of VB, best the maker of the original weight scale solve the issue. In the meantime I'll close this issue.

I'll stick to my bash scripts on the Domoticz forum :)
