### ISSUE TITLE
Kaku/Coco switched off by timer switch on command

### ISSUE THREAD

**Issue by harolds** [domoticz/domoticz#1636]
When using a sunset timer my Kaku/Coco lamp is switched off when it was already on. This happens to both lamps that I configured to use a sunset timer. So if I manually switch the lamp on at 18:00 and then when sunset comes at 22:00 the lamp is switched off! Not what I would except to happen. I know I could work around it by using a blockly or lua script but still it should work with the standard timers.

I am using the latest development branche (Version: 3.7995, Build Hash: 15e44a0, Compile Date: 2017-06-19 16:28:02)

![snap 2017-06-20 at 09 36 13](https://user-images.githubusercontent.com/4362052/27321897-5ada0626-559c-11e7-9a15-af5ba8497cac.png)

**Comment by gizmocuz** [comment]
Using a same timer for three years so it is not a problem with sunset/rise and a timer
Try setting the level to 100%

**Comment by gizmocuz** [comment]
Please use the forum as stated when you created this issue
