### ISSUE TITLE
OWL CM180 Energy usage seems wrong in daily chart

### ISSUE THREAD

**Issue by Kurairaito** [domoticz/domoticz#1640]
The value printed in the Log button for the energy usage seems wrong related to the Power usage in the 24 Hours chart 

Datas are OK in the last week, last month and last year chart.
![energy usage](https://user-images.githubusercontent.com/11020393/27384128-145d8dce-568e-11e7-866b-a01ec4a1d6e8.png)
![power usage](https://user-images.githubusercontent.com/11020393/27384136-198c5aaa-568e-11e7-8423-85129e7dd1b6.png)

I don't understand where those values come from as for exemple :
from 07:00AM to 07:55AM  there where 12 value with exactly 437Watt in power usage but Energy usage show 38833Wh
and from 10:00AM to 10:55AM there where also 12 value with exactly 437W in power usage but Energy usage show 38615Wh
Where today (from midnight) I consumed only about 7kWh (=== 7000 Wh far below the value shown in one hour timeframe)

EDIT : seem in Log that the OWL report a measure every minutes which explain why the same power usage in log can give 2 different Energy usage value. But still don't understand why values are so huge.

**Comment by gizmocuz** [comment]
Please use the forum as stated when you created this issue
