### ISSUE TITLE
'Door Lock' icon on Floorplan always shows as Unlocked

### ISSUE THREAD

**Issue by Lundis-se** [domoticz/domoticz#1641]
Running Domoticz 3.8001, problem also in 3.7981

In Floorplan the icon for 'Door Lock' always shows as Unlocked, if i place the mousepointer over the icon the pop-up-text  Locked/Unlocked changes as expected.
if tab 'Switches' is selected the icon is working as expected.
Icon for 'Door contact' switch is working in both Floorplan and Switches tab

**Comment by gizmocuz** [comment]
Fixed in beta 8152
