### ISSUE TITLE
Function to toggle notifications of device through LUA

### ISSUE THREAD

**Issue by roelbeun** [domoticz/domoticz#1649]
Purpose is for debug device on/off. If on, notifications will be enabled for particular devices. This way I don't need to manually set all notifications for each device. 

Already possible in some way?

**Comment by roelbeun** [comment]
Otherwise I can do it through a ondevicechange event, when on then send a notification.....

Then set an if statement for checking if it should a notification.

**Comment by gizmocuz** [comment]
Best to add a manual notification if you want to debug a device (or use your alternative method)
