### ISSUE TITLE
 Stop order of fibaro dimmable roller shutter not correct

### ISSUE THREAD

**Issue by Pigloox** [domoticz/domoticz#1650]
Hi,

Actually, stop order for a FGRM-222 (dimmable roller shutter) is not correct, 
the stop order corresponds to the descent order and causes problems during a cycle stop.

I know that this function is managed by class 0x26 (STOP SWITCH MULTILEVEL) but I do not know enough about development so I ask for help.

Thanks

**Comment by febalci** [comment]
Having the same problem with Qubino ZMNHCD Flush Shutter modules. Unfortunately there's no index for STOP in 0x26. As far as i understand in openzwave python implementation they are using "releasebutton":

manager = libopenzwave.PyManager()
manager.create()
manager.releaseButton(value_id)

And being a beginner in domoticz i really am not sure whether Domoticz uses C++ or python implementation of Openzwave. And yet, maybe all i write here are pure nonsense :)

UPDATE: Domoticz uses openzwave C++ library. Yet, this implementation also have pushbutton and releasebutton functions.

**Comment by rominetb44** [comment]
Hi,

Same issue....
The STOP command is working in ozw via a POST at /ozwcp/buttonpost.html with NodeId-SWITCH MULTILEVEL-user-button-1-1=false and NodeId-SWITCH MULTILEVEL-user-button-1-2=false

Could-it be added in Domoticz please ?

Thanks

**Comment by gizmocuz** [comment]
Yes, could you provide a patch?

**Comment by gizmocuz** [comment]
Seems nobody wants to make a patch, or it is not a real problem.
Closing issue, feel free to reopen when (you or someone else) is working on a pull request/patch

**Comment by roblomq** [comment]
Is this issue still open? If yes, I know it's not my setup that has the wrong settings and I don't have to look further..
