### ISSUE TITLE
Clickatell platform (newer version) is not working

### ISSUE THREAD

**Issue by imdos** [domoticz/domoticz#1651]
My Domoticz version is 3.800 

It appears to me that the code in Domoticz for Clickatell is only for the "old" platform and my account (registered this month) doesn't work. 

Apparently since nov 2016 there is a new platform which works with another URI and parameters. Could you therefore include a switch or something and register the new site as well. 

Attached an screenshot of the new login and one from my portal in which I am logged in (to show the credits). 
![domoticz-clickatell](https://user-images.githubusercontent.com/3097627/27539671-aa41fba2-5a7d-11e7-932c-00d67f3f5bf4.PNG)
![domoticz-clickatell-login](https://user-images.githubusercontent.com/3097627/27539672-aa42a93a-5a7d-11e7-992a-b20ca6d28c2a.PNG)

The error from Domoticz
> 2017-06-26 12:15:08.075 Error: Clickatell SMS Gateway: ERR: 108, Invalid or missing api_id
> 2017-06-26 12:15:08.075 Error: Notification sent (clickatell) => Failed

And the documentation from Clickatell
> curl "https://platform.clickatell.com/messages/http/send?apiKey=Ouxxxxxxxxxxx==&to=31612345678&content=Test+message+text"

> https://www.clickatell.com/developers/api-documentation/http-api-send-message/

**Comment by gizmocuz** [comment]
Could you make a patch for this ?

**Comment by imdos** [comment]
I'll have a look once I get back from my holiday. The code doesn't look too
complex, but I'm kinda missing a good start documentation or guide (the
same applies to my modification I will make for a python plugin).

**Comment by gizmocuz** [comment]
Clickatell has good documentation
Development can best be done under windows with visual studio 2017

**Comment by gizmocuz** [comment]
Hi Sander, got a change to correct this ?

**Comment by imdos** [comment]
Just got back from holiday. Still haven't had time to look into this.
I'm working on modifications for the python plugin for woonveilig for
osmotic atm. I hope to find some time in the upcoming month.

But the clickatell patch should be an addition to the original. Is that ok?
Otherwise there should be some sort of switch to choose from.

**Comment by gizmocuz** [comment]
Hi Sander,

Best not to reply directly via email as you give to much private information away... (i edited the post)

Yes, it should completely overwrite the current implementation as this does not work anymore

Hopefully it is something of a URL change...

**Comment by ghost** [comment]
It's more than an URL change. I believe Clickatell has made a mess of this whole thing.
Old customers are stuck with the old API. New customers must use the new API version.

The API key has changed from a numeric value to a long text string.
Username and password are no longer needed.
New API supports UTF-8 as default which is nice.
Numbers can be preceeded with a + sign. That didn't work in the old API if I can recall right.

EDIT:
**All Clickatell accounts created after 15 November 2016 must use the new API which is not supported by Domoticz**.  Older Clickatell customers must create a new account to get access the new API. I suggest Domoticz notification is changed to use the new API.

**Comment by r3wt3d** [comment]
Hi

Is there any update for this issue?

old one looks like this:

https://api.clickatell.com/http/sendmsg?user=xxxxxx&password=xxxxxxxx&api_id=xxxxxx&to=15XXXXXXX&text=test&from=13XXXXXXXXX

new one looks like this:
https://platform.clickatell.com/messages/http/send?\
apiKey=xxxxxxxxxxxxxxxxx==\&to=15XXXXXXXXX\
&content=test

So it shouldn't be a big problem to fix?

**Comment by gizmocuz** [comment]
Please make a patch and test it first...

**Comment by Dainyx22** [comment]
Hi,
r3wt3d where clickatell in raspberri location?

**Comment by DewGew** [comment]
Is there any update for this issue?

**Comment by gizmocuz** [comment]
@r3wt3d , no it's not and quite simple. Could you make a Pull request?

**Comment by gizmocuz** [comment]
Thanks for the join effort guys !
