### ISSUE TITLE
New device

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#1662]
I bought a z-wave siren  (Linear WA105DBZ-1) and it wasn't on the list. So I added it to my configuration.  However it's annoying to have to keep restoring it from back-up every time I upgrade.  I've attached the files.  I'd extend the source myself but I have no clue how to do that using GitHub.

[Config.zip](https://github.com/domoticz/domoticz/files/1117794/Config.zip)

**Comment by flatsiedatsie** [comment]
You can use the web interface to add/propose changes too. That might be easier.

**Comment by gizmocuz** [comment]
You have to submit this configuration file to OpenZWave, so it can be included.
If it is included, and it is not in domoticz after some days, give me a PM and i will update the config files for Domoticz
@flatsiedatsie , yep, first a new stable release... going on holiday soon so i have a lot of time (i hope) to integrate them

**Comment by Ittiz** [comment]
I submitted it to open zwave, we'll see.

**Comment by gizmocuz** [comment]
Thanks!

**Comment by Ittiz** [comment]
Can you merge open  z-wave into the new build?  They fixed the bug but they did it like 2 hours after you merged the files the last time.  Thanks

**Comment by gizmocuz** [comment]
Updates/Additions to configuration files are not considered 'bugs'
Please be happy that it was included into their repo that fast.
Working on the merge with Domoticz now...
