### ISSUE TITLE
MacOS release naming wrong.

### ISSUE THREAD

**Issue by ekgerke** [domoticz/domoticz#1675]
Under MacOS X "uname -s" returns "Darwin" not "OSX" as update script expects. The update scripts fail. Also restarting the domoticz service under MacOS will not work within the update script for an obvious reason of the lack of a "service" command.

> _Location: http://releases.domoticz.com/releases/release/domoticz_darwin_x86_64.tgz [following]
> --2017-07-07 01:18:50--  http://releases.domoticz.com/releases/release/domoticz_darwin_x86_64.tgz
> Resolving releases.domoticz.com... 104.31.78.142, 104.31.79.142, 2400:cb00:2048:1::681f:4e8e, ...
> Reusing existing connection to www.domoticz.com:80.
> HTTP request sent, awaiting response... 404 Not Found
> 2017-07-07 01:18:50 ERROR 404: Not Found._

**Comment by gizmocuz** [comment]
Thanks for the report... Can you propose a patch?

**Comment by gizmocuz** [comment]
No response, closing issue, please feel free to reopen when you created a patch for this
