### ISSUE TITLE
rtl_433 ppm error setting

### ISSUE THREAD

**Issue by pschonmann** [domoticz/domoticz#1677]
Hi, im missing in rtl_433 setting that set ppm error correction.
Should be possible add line where i can write parameters how to launch rtl_433. Other switches can be usefull too.

[-d RTL-SDR USB device index] (default: 0)
[-g gain] (default: 0 for auto)
[-f frequency] [-f...] Receive frequency(s) (default: 433920000 Hz)
[-H seconds] Hop interval for polling of multiple frequencies (default: 600 seconds)
[-p ppm_error] Correct rtl-sdr tuner frequency offset error (default: 0)
[-s sample rate] Set sample rate (default: 250000 Hz)
[-R device] Enable only the specified device decoding protocol (can be used multiple times)

**Comment by gizmocuz** [comment]
It's an open source project.. feel free to enhance this class
There is an options field in the hardware table that you can use for all options
Then enhance the setup in the code and HTML
