### ISSUE TITLE
BUG FOUND!! Can't add more than one Xiaomi Gateway

### ISSUE THREAD

**Issue by xtremforce** [domoticz/domoticz#1678]
Add one Xiaomi Gateway to domoticz works fine, but if you try to add another, devices never shows up.

And here's the error log:
XiaomiGateway: NOT LISTENING TO UDP FOR HARDWARE ID 4

Guys with the same problem:
https://www.domoticz.com/forum/viewtopic.php?t=16929

Build version:v3.8061
Is there any workaround?

**Comment by corbinmunce** [comment]
Multiple gateways are not supported - this decision has been made to simplify development during beta. For now, you can setup a second Domoticz server on a different subnet to run a 2nd Xiaomi Gateway

**Comment by gizmocuz** [comment]
Not a bug, please kindly ask to implement this
