### ISSUE TITLE
Satel Integra pulling stops

### ISSUE THREAD

**Issue by marcinkowalczyk** [domoticz/domoticz#1681]
Hi,

 From time to time my Satel integra integration stops. In log I can see following

2017-07-09 07:38:10.621 Error: Satel Integra: bad data length received
2017-07-09 07:38:10.621 Error: Satel Integra: Send 'Read Outputs' failed
2017-07-09 07:38:11.621 Error: Satel Integra: bad data length received
2017-07-09 07:38:11.627 Error: Satel Integra: Get info about new data is failed
2017-07-09 07:38:12.659 Error: Satel Integra: bad data length received
2017-07-09 07:38:12.659 Error: Satel Integra: Send 'Read Outputs' failed 

I need to disable-enable device and then it works again. Currenty using 3.8015 but it's there since at least November stable release (first one I used)

**Comment by szczukot** [comment]
Pls set Date Timeout to 5 minutes.
If connection is broken, module is restarting.

All remarks about Integra module, You may write on forum to me https://www.domoticz.com/forum/viewtopic.php?t=4260

**Comment by marcinkowalczyk** [comment]
I have it set already to 30mins, but no luck. Will try with 5 mins

**Comment by gizmocuz** [comment]
Working ?

**Comment by gizmocuz** [comment]
No response, closing issue, please use our forum!

**Comment by rafalwal** [comment]
Hi
I have the same problem. Reducing time does not help. After some time, an error occurs.
It helps (for some time) blocking and unblocking Satel hardware at Domoticz.

**Comment by archer87pl** [comment]
Hi, I have some problem. Do you have guys any solution for that problem?

> 2018-12-29 19:36:21.784 Error: Satel Integra: bad data length received
> 2018-12-29 19:36:21.784 Error: Satel Integra: Send 'Read Outputs' failed

**Comment by szczukot** [comment]
https://www.domoticz.com/forum/viewtopic.php?f=56&t=4260&p=202017#p202017
