### ISSUE TITLE
Add Temp+Baro sensor type for selecting e.g. a BMP280 sensor

### ISSUE THREAD

**Issue by bieshaar** [domoticz/domoticz#1689]
Would like to request adding a Temp+Baro sensor as a type for the sensors when creating a virtual sensor.
In my configuration I have ESPEasy running with a BMP280 sensor. This sensor give Temp+Baro readings.

In Domoticz I can only select the Temp+Hum+Baro sensor when adding a virtual sensor
With this selection the humidity stays empty because it is not on the sensor. It's kind of strange to see it in your dashboard giving a 0% humidity.

The list now contains:
Temperature
Temp+Hum
Temp+Hum+Baro

Adding Temp+Baro would be perfect for the sensor list.

**Comment by gizmocuz** [comment]
Do you also get a forecast value ?

**Comment by gizmocuz** [comment]
(And an altitude)

**Comment by bieshaar** [comment]
No, in my setup it is connected by using EspEasy on a Wemos, and only returns temp and pressure. The Json output for the bmp280 is:

{
"TaskName": "Barometer",
"Temperature": 22.24,
"Pressure": 1005.42
}

**Comment by gizmocuz** [comment]
Thanks!. Implemented in beta 8151, could take an hour before it is available
Usage is explained in the wiki here
http://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Temperature.2Fbarometer

**Comment by bieshaar** [comment]
Great, thanks!

**Comment by bieshaar** [comment]
Not working for 100%.
The pressure isn't received when send by ESPEasy, stays at 0.0 hPa. Temp is ok.

Also in the device list the type is BMP085 I2C. Should be corrected to BMP280.

**Comment by gizmocuz** [comment]
Dont mind the TYPE... did you try the json/wiki method ? what is send to domoticz ?

**Comment by bieshaar** [comment]
Json method works.
However ESPEasy works on Temp/Hum/Baro sensor, although Hum stays empty because nothing is send.
Don't know how to filter the data send from ESPEasy. Any tips?

**Comment by gizmocuz** [comment]
No... so it seems you need to use a temp+hum+baro sensor then ?
OR... better... talk to the ESPEasy guys to send it as Temp+Baro...
I don't know ESPEasy...

**Comment by bieshaar** [comment]
The request was about not using temp+hum+baro beacuse of the zero reading on the hum :)

**Comment by gizmocuz** [comment]
Sure, that is why you can now use a Temp+Baro sensor right ?
It is also working with or official json/wiki right ?
An external library (ESPEasy) does not seem to work with it right ? Then this library should be fixed right ?
... So not a domoticz issue right ?

Sorry... i know i'm right... hope you get it right now also.... ;)

**Comment by bieshaar** [comment]
??? Not sure how to read the tone?

**Comment by gizmocuz** [comment]
With some fun.. but also with a seriousness into it... we added it, now please ask ESPEasy to support it, we (Domoticz) can not change this library as it is not ours

**Comment by bieshaar** [comment]
Ok will contact ESPEasy
