### ISSUE TITLE
Dimmer slider

### ISSUE THREAD

**Issue by bublikOff** [domoticz/domoticz#1693]
It would be nice to force update dashboard after dimmer sliding. Add something like:
`setTimeout(RefreshFavorites, 1000);` 
to SetDimValue function

For the moment only after dimmer on/off event it updates status of other devices on the screen

**Comment by gizmocuz** [comment]
it should update also when there is a change in the dimmer value... no need to refresh each second
It should check for updates each 10 seconds at least
will have a look here

**Comment by gizmocuz** [comment]
It does work.
Add a dummy switch, change the type to 'dimmer', open two browsers to the switches page
change the dim slider to a value.. now wait (max. 10 seconds) on the other browser and you see the status changing
