### ISSUE TITLE
missing API on wiki page

### ISSUE THREAD

**Issue by ljubomirb** [domoticz/domoticz#1698]
Currently, there is no documentation on API wiki page about how to get graph (history data) for anything other than temp. 
For temp, it is as follows:

> /json.htm?type=graph&sensor=temp&idx=IDX&range=day
> /json.htm?type=graph&sensor=temp&idx=IDX&range=month
> /json.htm?type=graph&sensor=temp&idx=IDX&range=year

However, Domoticz can fetch other data (other then temp) as well, but it is not documented. My guess is that it's something trivial as replacing "temp" with "util", but that is not working (at least on stable release).

**Comment by gizmocuz** [comment]
Open with the chrome browser the developer tools (f12) then click on the network tab
Then goto the graph you want, see the http calls... There you have it
