### ISSUE TITLE
accuweather update choice

### ISSUE THREAD

**Issue by deennoo** [domoticz/domoticz#1699]
Adding Accuweather is a great and the best weather service on my side.

Accuweather provid a free api for 50 call / 24h, which can be enough for most of us, this give a weather lookup every 30 minutes

Looking @ accuweather.cpp file, it's look like api is call every 600 secondes , is this possible to change it for every 30 minutes 1800 Secondes please ?

**Comment by gizmocuz** [comment]
https://developer.accuweather.com/pricing-and-data-packages

**Comment by jvandenbroek** [comment]
I checked it out and it stopped working after 8 hours or so. If you look at this link, it says it's limited to 50 calls/day: https://developer.accuweather.com/packages

**Comment by szczukot** [comment]
When i wrote this code, limit to 50 calls/day didn't exist.
But I all time use this module, and it works all day.

**Comment by gizmocuz** [comment]
whaaa... then i would say use another service like wunderground ? forecast.io ?
I will make the change

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/commit/ca72d27aec6b2d76a029a1c35be1f8aee557f2b7

**Comment by szczukot** [comment]
My mistake. 
I think about OpenWeatherMap :) It have only limit for 60 calls per minute.

**Comment by gizmocuz** [comment]
is it working correctly now with my latest patch or do we need to change it back?

**Comment by jvandenbroek** [comment]
I believe we're fine now, @szczukot is/was referring to OWM, not this service.

**Comment by gizmocuz** [comment]
Thanks!
