### ISSUE TITLE
dzVents armAway() sets domoticz.security to "Armed Away" before delay expires

### ISSUE THREAD

**Issue by heggink** [domoticz/domoticz#1705]
when invoking armAway(), domoticz.security is set to "Armed Away" immediately rather than when the delay in settings is expired. Tested as follows:
1 script with 
on = { security = { domoticz.SECURITY_ARMEDAWAY, domoticz.SECURITY_DISARMED } },
printing domoticz.security on invocation.
another triggered by dummy device logging domoticz.security
The last logs "Armed Away" before the system is armed. The first only after the timer is expired.

Request: during the timer phase, return "Arming" rather than "Disarmed".

**Comment by dannybloe** [comment]
So if I understand it correctly: if you set security to armed from a script, Domoticz immediately set the security state without taking the delay from the settings into account?

**Comment by heggink** [comment]
Correct.
Btw, I would LOVE to be able to test for an interim state between Disarmed and Armed but I understand that this would constitute a change.

**Comment by dannybloe** [comment]
Does it also set it to armed immediately if you pass it a delay from script? Like in dzVents device.disarm().afterSec(30)? 

I'd say that if you set it from script it should be effected immediately unless you pass it a delay like this. The delay in the settings is more to give security panel users the time to close the doors or leave the house. If you do it from script you have much more control over specific timings.

**Comment by heggink** [comment]
Understand and that proviced a nice 'workaround' that I will implement but here's the thing: when I invoke armAway() from dzv then the domoticz.security state changes immediately even though the delay in settings is set to 90 seconds. I also have a dzv script that triggers on "security =" where I can clearly see that the system isn't really armed until after the delay so, 'formally', the domoticz.security state is incorrect until after the delay. Now I don't use the arm/disarm domoticz panel anyway so could set the delay to 1 second and then use your afterSec(90). Since all devices that switch the alarm on all use the same script (thanks to global_data), that will absolutely work (so many thanks for implementing it although I need to get it into my scripts). Still, the domoticz.security state should not be armed until the delay expires hence me logging this here.

**Comment by gizmocuz** [comment]
Please discuss this on the forum or on Slack
