### ISSUE TITLE
 Last update of a user variable reported different

### ISSUE THREAD

**Issue by rkuijer** [domoticz/domoticz#1709]
Domoticz Build Hash: a5381c1
Build Date: 2017-07-22 19:47:45

The reported last update of a user variable is reported different.
The date format is without the leading zero, if the month consist of just one number. 
example:
LaptopCurrentLow lastupdate = 2017-7-23 14:11:38
Instead of LaptopCurrentLow lastupdate = 2017-**0**7-23 14:11:38

This will cause the a failure 
Error: EventSystem: in script_time_laptopjes: [string "--..."]:46: field 'month' missing in date table
With the function;
```LUA
function timedifference (s)
  year = string.sub(s, 1, 4)
  month = string.sub(s, 6, 7)
  day = string.sub(s, 9, 10)
  hour = string.sub(s, 12, 13)
  minutes = string.sub(s, 15, 16)
  seconds = string.sub(s, 18, 19)
  t1 = os.time()
  t2 = os.time{year=year, month=month, day=day, hour=hour, min=minutes, sec=seconds}
  difference = os.difftime (t1, t2)  
  return difference
end
```

**Comment by dannybloe** [comment]
This is fixed in the current beta. Please check it out.
