### ISSUE TITLE
LUA os.execute(ping) => ping: icmp open socket: Operation not permitted

### ISSUE THREAD

**Issue by DarkAllMan** [domoticz/domoticz#1723]
Currently on V3.8136 - Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-87-generic x86_64)
I have a LUA script in Events
``
os.execute('ping 192.168.1.160 >> /var/www/ping.log 2>&1')
``

When I check the log file, it always lists:
ping: icmp open socket: Operation not permitted

Tried to do a chmod on /bin/ping
Tried to do a setcap on /bin/ping
Nothing seems to help.

**Comment by gizmocuz** [comment]
we have native hardware support for pinging devices... could you not this?

**Comment by DarkAllMan** [comment]
I could not find information about it…
How does this work?

**Comment by gizmocuz** [comment]
Try the 'System Alive Checker(ping)' from the hardware setup

**Comment by DarkAllMan** [comment]
This is not working for me... I added the hardware and an IP, but nothing happens....
Switch does not get status ON

**Comment by gizmocuz** [comment]
we have a user forum.... i think if you search there, you will find answers.. you need to be on the beta version for sure...
The issues here are for code related issue

**Comment by DarkAllMan** [comment]
I'm also on the forum... but no answers. I hoped it was maybe a coding issue. (I'm on the lastest beta).
