### ISSUE TITLE
Support HTTPS for IP Camera

### ISSUE THREAD

**Issue by lalmat** [domoticz/domoticz#1724]
Hi all,

First of all, thanks for this legend... wait for it... dary project. It's really a pleasure to use this software every days and as a developper, I will be very pleased to contribute.

I wish to add a feature to support HTTPS streams on IP Camera. At the moment, only HTTP is allowed. I think it's just a variable to add on the front-end app.

Is there any plans to develop this feature or may I start to implement it ?

Thanks.

**Comment by gizmocuz** [comment]
Is this for an in-house camera? Then I suppose http is still Ok?

**Comment by digimago** [comment]
@gizmocuz from a security perspective it is wise to at least treat connected cameras as an attack vector that can easily be made a lot less interesting by implementing HTTPS if the camera supports it. This is especially the case of course in more public WiFi situations, but why not up privacy a notch and prevent the video stream from being hi-jacked in the first place? On the other hand I do not know how many camera's actually support CA certificates versus very weak vendor signed certificates.

**Comment by gizmocuz** [comment]
From a Domoticz perspective this does not matter at all, but yes, if you do not trust your local in-house network or http does not exist then this should be implemented.
It's implemented in the upcoming beta version (8183+) tested with a public online camera

**Comment by lalmat** [comment]
In my house configuration, cameras are in behind a firewalled VLAN. External cameras are connected over ethernet so It will be easy for someone to put a device between camera and my network and do some nasty stuff on my home network. This choice is to protect the wifi password and to avoid wifi scam attack during a housebreaking scenario

To access to my cameras, my firewall/router accept only incoming secured connections from the public ip to the isolated VLAN. Non secured incoming connections or new outgoing connections from the isolated VLAN to the home VLAN or to the internet are forbidden.

Of course as identifiers are sent by a basic auth authentication, I use a reverse proxy to secure with a certificate (I have my own Certificate Authority) the connexion between my phone and the reverse proxy.

As a result, if a MIM attack occur (by placing a device between camera and ethernet cable) the attacker need to be in wifi range or he need to have his own network in 3G or 4G to have just an image of my garden... That reduce correctly the impact of the breach. He will be unable to connect to the internet or to my home network (and access to the alarm or the domoticz stuff).

I've started to work on the patch, but I will pull the upcoming beta version to see if it correspond to what I want.

Maybe I am a little too paranoid, but only paranoid survives !

**Comment by gizmocuz** [comment]
I think you are... Unless you are a very interesting person to spy on hahaha
Anyway it's implemented now... Hope all works as expected

**Comment by lalmat** [comment]
Thank you very much ! I'll test it as soon as possible.
