### ISSUE TITLE
domoticz_applyJsonPath not working correctly

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#1727]
It seems to me that the domoticz_applyJsonPath is not working correctly in LUA.  According to [this](https://github.com/json-path/JsonPath) the below code should get the idx of node 6 (has the ZW node id 14).  It doesn't output anything.  Also If I paste my JSON and path into [here](http://jsonpath.herokuapp.com) it works fine.  So it seems like something wrong with the way domoticz handles it.
```
local zwHWID = 2 --CHANGE: The IDX of the Z-wave controller the device is associated with.
local zwnodeID = 14 --CHANGE: The Z-wave node ID

	-- Load data from Node data
	local nodedata = assert(io.popen('curl "http://127.0.0.1/json.htm?type=openzwavenodes&idx=' .. zwHWID .. '" -la','r'))
	local thenodedata = nodedata:read('*all')
	nodedata:close()
	--done getting Node data
	
	local zwnodeIDx = domoticz_applyJsonPath(thenodedata,".result[?(@.NodeID == '" .. zwnodeID .. "')].idx")
	print(zwnodeIDx)
```

However the below code works, although is less useful because it won't always be node 6.  So then to get the correct idx I'll have to run it through a loop.  

```
local zwHWID = 2 --CHANGE: The IDX of the Z-wave controller the device is associated with.
local zwnodeID = 14 --CHANGE: The Z-wave node ID

	-- Load data from Node data
	local nodedata = assert(io.popen('curl "http://127.0.0.1/json.htm?type=openzwavenodes&idx=' .. zwHWID .. '" -la','r'))
	local thenodedata = nodedata:read('*all')
	nodedata:close()
	--done getting Node data
	
	local zwnodeIDx = domoticz_applyJsonPath(thenodedata,".result[6].idx")
	print(zwnodeIDx)
```

**Comment by gizmocuz** [comment]
Please use our forum!

**Comment by Ittiz** [comment]
I was told to report things over here when I think I've found a bug, but ok
