### ISSUE TITLE
Google Cloud Messaging change for Firebase Cloud Messaging

### ISSUE THREAD

**Issue by deennoo** [domoticz/domoticz#1728]
GCM is changing for FCM 

Firebase Cloud Messaging (FCM) is the new version of GCM. It inherits the reliable and scalable GCM infrastructure, plus new features! See the FAQ to learn more. If you are integrating messaging in a new app, start with FCM. GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future.

https://developers.google.com/cloud-messaging/http-server-ref

Trying to use GCM on beta : 3.8155 result : 

2017-07-30 14:51:09.073 Error: GCM: Could not send message, HTTP Error
2017-07-30 14:51:09.073 Error: Notification sent (gcm) => Failed

Using Android Domoticz app and or course sending CGM id using thé app feature

**Comment by gizmocuz** [comment]
Thanks, we know....
Currently the GCM code is tested against Android and iOS... It should work on Android

**Comment by gizmocuz** [comment]
http://domoticz.com/forum/viewtopic.php?f=6&t=18601
