### ISSUE TITLE
Feature Requests: Show captor tendency via arrows.

### ISSUE THREAD

**Issue by zachari043** [domoticz/domoticz#1733]
Adding up or down arrow on captor to show the tendency 
And a Block like  "if Is rising ... "

![ex](https://user-images.githubusercontent.com/30619426/28816368-eadddb2a-76a4-11e7-9c10-b2edc29cfbe0.JPG)

**Comment by Dylantje** [comment]
looks a great option...

**Comment by gizmocuz** [comment]
Working on it...

**Comment by gizmocuz** [comment]
Almost finished... what would be a good period between measure points for the trend calculation ?
Probably 5 minutes is to short for temperature ? 30 minutes ?

**Comment by Dylantje** [comment]
mm I also think 30-45 is better then 5 minutes

**Comment by gizmocuz** [comment]
Try beta 10185, only implemented for temperature, and it's calculated over 30 minutes intervals.
When there is no icon, it's unknown or stable, else you will see a up/down arrow
The same can be done for any type of sensor of course (except switches... sort off)
It is only displaying this on the temperature tab for now!!!

**Comment by Bewo** [comment]
In my environment (15 temperature devices) it works like a charme ;-)
Nice feature - Thanks @gizmocuz 

![domoticz-temp](https://user-images.githubusercontent.com/8536696/48718574-f72d1880-ec1b-11e8-8649-9cdb02ab7675.png)

**Comment by gizmocuz** [comment]
Thanks for the feedback! Maybe we should make an option that you can specify for which sensors you would like to do this (temperature/utility/weather)

**Comment by Dylantje** [comment]
looks fancy...
Only perhaps possible to see this arrows also in the dashboard?

**Comment by gizmocuz** [comment]
@Dylantje , yes , as mentioned, currently only on the temperature tab

**Comment by gizmocuz** [comment]
Forgot about this one ;) ... should be implemented now in beta 14184
