### ISSUE TITLE
missing Stop Action on venetian blinds switch type

### ISSUE THREAD

**Issue by brian-f** [domoticz/domoticz#1738]
I'm actually managing these blinds through RFlink but I'm willing to migrate to wired relays, shorting NO open/stop/close buttons of the blinds via three differents GPIOs/URLs.

![immagine](https://user-images.githubusercontent.com/12842113/28882051-591cd7a2-77aa-11e7-8004-7e912c502f60.png)

![immagine](https://user-images.githubusercontent.com/12842113/28882027-404589ea-77aa-11e7-98bd-cf11e6d0b67a.png)

**Comment by gizmocuz** [comment]
I think you can do this via the EventSystem/Blockly correct?

**Comment by brian-f** [comment]
oh well, how could I not think of it? thanks, will try and report back

**Comment by reynolds99i5** [comment]
Hi, i need stop action too. 
I have 433 transmiter to stock blind controler (sending stop code via 433MHz)

**Comment by almostlunatic** [comment]
Hello, I also need the stop action. I have 3 relays to operate the blinds: Up, Stop and Down. Every relay is switched by a URL command (Power2, Power3, Power4 - "On" for 500 ms). I cant find the place where to apply an action to the STOP button.

**Comment by salcabo** [comment]
Hi, a stop action is a great improvement, I wonder if can be done
