### ISSUE TITLE
v3.8153 EvoHome not displaying correctly in Dashboard

### ISSUE THREAD

**Issue by reboot1983** [domoticz/domoticz#1739]
First things first: great new release! Congratulations!

I'm realy happy with the implementation of the 'EvoHome by API'! Works like charm! Real nice work.

I've noticed a small hickup, when adding my zones to the dashboard. In the dashboard the zones are added under 'Temperatuursensoren' (temperaturesensors), but also a heading appears called 'EvoHome devices'. (which is empty). I've added a screenshot to make thing more clear.

![image](https://user-images.githubusercontent.com/20405704/28889480-6b2d7996-77c4-11e7-8c9f-20d745f61130.png)

**Comment by gizmocuz** [comment]
Never seen 'Evohome devices' before... dont think that should be here... but i have a close look asap

**Comment by gizmocuz** [comment]
Only heating devices seems to be added under 'evohome Devices'
Do you have (added) any heating devices ? (device subtype = 'Heating')

**Comment by gizmocuz** [comment]
To be more specific
type should be Heating, subtype should be EvoHome
See for example on line 3300 in DashboardController.js

**Comment by reboot1983** [comment]
I added my EvoHome to Domoticz yesterday after I updated to the latest stable release.

Then the devices appeared within a few moments. After that was done I added the 5 rooms so they would be visible to the temperature tab. Then I marked these 5 as favorites and they appeared in the dashboard. Including the 'Evohome devices:' text.

This is the json of one of these devices:

```{
ActTime: 1501790492,
ServerTime: "2017-08-03 22:01:32",
Sunrise: "06:05",
Sunset: "21:27",
result: [
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "22.5 C, (12.0 C), Auto until 2017-08-03T23:00:00Z",
Description: "",
Favorite: 1,
HardwareID: 5,
HardwareName: "HoneyWell EvoHome WiFi",
HardwareType: "Evohome via Web API",
HardwareTypeVal: 75,
HaveTimeout: false,
ID: "2036214",
LastUpdate: "2017-08-03 22:00:56",
Name: "Werkkamer",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
SetPoint: 12,
ShowNotifications: true,
SignalLevel: 10,
Status: "Auto",
SubType: "Zone",
Temp: 22.5,
Timers: "false",
Type: "Heating",
TypeImg: "override_mini",
Unit: 2,
Until: "2017-08-03T23:00:00Z",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "85"
}
],
status: "OK",
title: "Devices"
}

**Comment by gordonb3** [comment]
Yes. That is a glitch that has existed for as long as I've used Domoticz. The text will show in Dashboard if you have Evohome hardware installed, regardless of whether you have any matching hardware marked as favourite. Also, the only device that will register under it is the main controller that you can find in the `switches` tab.

**Comment by gizmocuz** [comment]
do we need the special EvoHome in the dashboard ? If it is in the switches tab, it should be displayed under the switches on the dashboard correct?

**Comment by gordonb3** [comment]
Can't really comment on that because I don't know why it is there. I actually think a Hot Water Unit will also register under Evohome devices, but I don't have that. As a result I also don't know where this device will show in the tabs. Of course Evohome is a heating device so I guess it would make sense to make it more generic, but then there's also the issue that the Evohome zones register as temperature sensors.

One could also argue that heating devices could (or should) be grouped under Utility devices, currently referenced as `Utility Sensors` in dashboard. In fact I think it would make a lot more sense to have the Evohome controller listed under `Utility` than in the switches tab, even while it is conveniently defined as a multiselect switch. I fear that will make the challenge even bigger though.

From my perspective I actually wonder whether it makes sense at all to pre-group items at all. As it stands I now have lines with only one item on it and a scrollbar because the page is too long. And even though I can move items about, it is impossible to cross the pre-grouping boundaries or for that matter: change the order of that pre-grouping.

**Comment by gizmocuz** [comment]
Yes, current design is like this until I (or someone else) makes a better grouping.
There are also alternatives (room plans, floor plans etc)
Its the first time i see this here, it should not be here at all....
They should (now) be grouped where they belong.. switches/temp/utility
End users can place them in a room plan, or a floor plan if they don't like the current dashboard layout, or propose a pull request of course with a better alternative.

My problem with this is time... it's spare time for all of us.
In other projects i use this:
http://dsmorse.github.io/gridster.js/

**Comment by gordonb3** [comment]
Looks nice, although dragging blocks appears to have unexpected results at some points.

**Comment by gizmocuz** [comment]
thats only for the editing part... and needs to be customized as well ;)...

**Comment by brucemiranda** [comment]
Now, even when the Evohome controller (Heating, Evohome) device is marked as a favourite, it still won't appear in the Dashboard.

**Comment by gordonb3** [comment]
I think Rob changed something in Dashboard. The `evohome Devices` section is gone now and as none of the filters on the other sections appears to have been altered so is the controller.

**Comment by gizmocuz** [comment]
That could be the case... the setpoints/heating/mode devices should be placed under their normal section
Unless there is a new type 'evohome' , but then still (for now) it should be placed where other hardware classes are placing them
Setpoint->Temperature tab/section (i see evohome code in here)
Thermostat modes -> utility tab
various states (on/off) -> switches tab

**Comment by gordonb3** [comment]
pom-pom-pom... https://github.com/domoticz/domoticz/commit/c6c78e5

Must have made more sense back then.

**Comment by gizmocuz** [comment]
Nope, i did not have any EvoHome hardware (thinking about it)
I could have merged code from a fellow developer that was not good with GIT (or SVN at that time)

**Comment by gizmocuz** [comment]
Nevertheless sensors should be placed where they belong (at this moment) until we have a whole other way of (better) presenting/categorizing them.
We do have roomplans, floorplans to have a better view

**Comment by gordonb3** [comment]
Will be hard to figure out whom this came from then, unless of course you can trace that back in your personal communications from that time. Main evohome code appears to originate from `fullTalgoRythm` but I don't see any additions to DashboardController.js in his commits: https://github.com/fullTalgoRythm/Domoticz-evohome/commits?author=fullTalgoRythm

**Comment by gizmocuz** [comment]
Ok no worries, but i still want to point at my previous message ;)
