### ISSUE TITLE
HEAD request must not return a message-body

### ISSUE THREAD

**Issue by gaudryc** [domoticz/domoticz#174]
The HTTP/1.1 specifies :

"The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response. The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request. This method can be used for obtaining metainformation about the entity implied by the request without transferring the entity-body itself. This method is often used for testing hypertext links for validity, accessibility, and recent modification."

For example, Uptimerobot sends HEAD requests while checking http(s) requests...

If we fix it, we save some resources to serve these requests.

**Comment by gizmocuz** [comment]
Great find!

**Comment by rkluwen** [comment]
See my pull request.

**Comment by gizmocuz** [comment]
thanks for the fix
