### ISSUE TITLE
Domoticz Port not working if higher then 30000.

### ISSUE THREAD

**Issue by jivonl** [domoticz/domoticz#1746]
Unable to Strart domoticz server with port higher than "40000"

My Default port was 64133, but domoticz is not starting with any port higher then 40000.
i am able to start the domoticz from commandline on 30000 as an example.
i tested 64133, 50000, 40000, and only 30000 is working.

there is nog even any logging availible with verbose 1 and logfile etc. 

tested with Stable and Beta:
Build Hash: 388eeb0b
Build Date: 2017-08-07 08:26:56
V3.8237

**Comment by gizmocuz** [comment]
Have you checked the log output ? Because this is by design and the log will tell you
Please use our forum
