### ISSUE TITLE
www.domoticz.com forum does not send email

### ISSUE THREAD

**Issue by growveggies** [domoticz/domoticz#1753]
Hi,

Currently, the Domoticz.com/forum does not send password reset and account activation email.
I am currently locked out, because I need to do email address validation.
I Could not find other contact info, so, sorry for mis-using github to inform you.

Regards,
niceandeasy

### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version.
* Always state your version when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by brucemiranda** [comment]
Same issue for me too. I had to raise an Issue Report via github as a result.

**Comment by gizmocuz** [comment]
Geert, i send you an email
