### ISSUE TITLE
3.8266 : Virtual Sensor Selector Switch Levels greater than 100

### ISSUE THREAD

**Issue by brucemiranda** [domoticz/domoticz#1756]
On a Dummy Hardware if you create a Virtual Selector Switch and add Levels, the various levels are defaulted to increments of 10. First of all, I think the increments should be made editable too. 

When you get to 100, the Add level button is disabled, which is correct. However if you wait long enough that button becomes active again and then you can add levels more than a 100. Again in increments of 10. 

The issue comes when you select any of these levels more than a 100, the switch changes its value to 100 regardless of what value you choose beyond a 100. 

So either we should allow the Selector to go beyond a 100. Or make sure that adding levels more than a 100 is never possible. 

I also noticed another issue. If you change the device type using the Edit button then the Edit button becomes inactive and you cannot Edit that device any more. The only option then is to Delete the device and recreate it. 

See the json below for the test Device I created. 

`      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "myBoiler",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001409A",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-08-10 11:29:13",
         "Level" : 0,
         "LevelActions" : "|||||||||||||",
         "LevelInt" : 0,
         "LevelNames" : "Off|Level1|Level2|Level3|4|5|6|7|8|9|10|11|12|13",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "testSelector",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "74"
      }
`

**Comment by mo8Zomo0** [comment]
Yes, I was running into the same issue, though the website did not limit me even to create these values. I mapped temperature values 16-30 to this.
It seems that Domoticz uses percent to map these values and so it does not like 110%.
So currently it can not be more than 10 values

I fully agree, and in addition
* the index should be easy editable
* it should be possible to have free level selection (you might want a values of 13 and 37, ... percent)
* allow more than 10 values (not sure if more then 100 make sense as well, but why not)
* invalid values should be caught and not allowed
* a non percentage mode should be available.


Thats what I had in my logfile:
2017-08-20 17:02:53.670 User: Admin initiated a switch command (93/AC Set Temperature/Set Level)
2017-08-20 17:02:53.671 Error: Setting a wrong level value 110 to Selector device 8348987339011342509
2017-08-20 17:02:53.683 LUA: HeatpumpIR startup
2017-08-20 17:02:53.683 LUA: HeatpumpIR Debug, key:AC Set Temperature
2017-08-20 17:02:53.683 LUA: HeatpumpIR event started
2017-08-20 17:02:53.683 LUA: AC Set Temperature
2017-08-20 17:02:53.683 LUA:
2017-08-20 17:02:53.683 Error: EventSystem: in /opt/domoticz/scripts/lua/script_device Heatpump.lua: /opt/domoticz/scripts/lua/script_device Heatpump.lua:96: attempt to concatenate local 'settemperature' (a nil value)

**Comment by gizmocuz** [comment]
Its by design

**Comment by brucemiranda** [comment]
So in which case there is an issue that allows the Add Level button to become active even after 100% Levels have been added. The switch should never allow more than 100% to be added, if levels beyond 100% can never actually be selected.

**Comment by gizmocuz** [comment]
I think this is true yes, there is no 110% level

**Comment by brucemiranda** [comment]
Hence why, the button should remain disabled and never allow levels more than 100 to be added. But currently you can. It appears that the button is disabled only for a short time, if you wait long enough it gets reenabled, which should not happen.

**Comment by gizmocuz** [comment]
i agree, could you submit a pull request for this ?

**Comment by mo8Zomo0** [comment]
Even if it should only provide 100% more than 10 values on the switch would be handy, and
to be honest, if this is the design that all is mapped to a percentage, some redesign might not be the worst idea.

Like I have a led lamp switch with off=0, 10 cold, 20 medium, 30 warm, but in the scenes it just shows the percentage, here on this example it might be easy to remember, but there are more
complex ones, so showing the value instead of the percentage (or both) would be good as well.

**Comment by gizmocuz** [comment]
Sounds great and logical.. maybe an option for the value display
