### ISSUE TITLE
Update of beta release doesn't remember System's setting of batterylowlevel

### ISSUE THREAD

**Issue by imdos** [domoticz/domoticz#1757]
I've noticed a bug with the batterylowlevel settings in System => Other
![batterylowlevel](https://user-images.githubusercontent.com/3097627/29177428-fa9592e6-7dee-11e7-8052-d5b8bb99497d.PNG)

Short summary: After update the current value doesn't reflect the most recent one it appears but a previous state. 

Longer detailed one. 
I've updated today through the GUI and after a while got a notification from Pushbullet that I have a Low battery level on a Z-wave device (which is correct though). After making sure my dzVents script was correct (modified a bit; but original is "check battery levels.lua") I noticed that the level was set again to 20% (a previous setting I did). 
But which I supressed after a while on my previous beta release I was running (V3.8237). 

I have restored it again to 0 to disable the notification (see attached screenshot as well) and have it processed by dzVents, I'm going to use it to power-on and off my device through a power switch on rflink. 

I'm unsure how I can reproduce this AFAIK without upgrading of course to a newer version.

**Comment by gizmocuz** [comment]
Sorry, please post this on the forum under the dzEvents section.
I checked the code, and it is correctly stored in the database, not sure why dzEvents has a previous value

**Comment by imdos** [comment]
I'm unable to reproduce this issue. Might be a cached value which got stored or my mistake. In the latest update 3.8270 it doesn't show up. 

Sorry for the inconvenience!

**Comment by gizmocuz** [comment]
No worries !
