### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by gaudryc** [domoticz/domoticz#176]
We've got a memory leak.
When my domoticz starts, its memory is like this (using a top command) :
virtual : 174MB, Resident: 15MB, shared: 10MB
After 46 hours, I got :
virtual : 511MB, Resident: 51MB, shared: 12MB

During these 46 hours I had :
- 1 Uptimerobot monitoring on https://<my_domoticz_domain>/ ;
- 1 database backup each hour, using an http request (and login/logout) ;
- one lua time script (computing a time, two times a day) ;
- four lua device scripts (checking temperature and states) ;
- 8 blockly scripts ;
- 7 RFX devices (temperature) ;
- 2 ZWave Motion sensor ;
- 5 ZWave Relay Switch ;
- 1 ZWave RGBW ;
- 3 ZWave Wall plug ;
- 1 ZWave Multiple Switches ;
- 1 ZWave remote ;
- 1 Enocean Door sensor ;
- 1 Enocean Wall Switch.

My domoticz version use session cleanup.

Today, I've restarted domoticz after pausing the Uptimerobot.

**Comment by gizmocuz** [comment]
I discovered a possible memory leak (actually almost certain)  related to lua and patched it this morning,  but the friend of mine does not use lua
But this might solve this problem

**Comment by gaudryc** [comment]
I will try to take your changes but the GPU of my Macbook pro 2011 is dead so
I can't do anything but working with SSH on iOS and waiting for Apple to
change my motherboard (maybe 2 or 3 weeks).

:-(

**Comment by gizmocuz** [comment]
I think it is the https:// connection that causes the memory leak

what we will try

enable uptimerobot again on https, if the memory goes up (we can see this in 3 hours), then we do another test, we let uptimerobot connect to http (instead of https), if this also increases the memory, it is something in the latest webserver changes
If it stays normal, it is a https issue somehow

but this has been running on https for a long long time now

Sorry about your GPU ! ... with this it is a little black....
You could use mobaxterm and ssh and start an x-session or application....

**Comment by gaudryc** [comment]
I think we have to do on another domoticz instance without any device or
hardware but the motherboard.

**Comment by gizmocuz** [comment]
took my last commend back... need to investigate more

I still think we have to look in the eventsystem in the EvaluateLua function, the lua object is not freed, and this might cause a memory issue as well

**Comment by gaudryc** [comment]
Me too, I don't think the problem is in the HTTP or HTTPS side but to be "sure", I'm running 3 instances of domoticz on the same raspberry (the real one and the two empty ones).

I'm running a Uptimerobot on the HTTP port of the first empty one, and I'm logging a top command each 30 minutes.
I'm running a Uptimerobot on the HTTPS port of the second empty one, and I'm logging a top command each 30 minutes.

**Comment by gizmocuz** [comment]
I think you find the hardware monitor's memory sensor very usefull

(it does seems to be stable now)

**Comment by gaudryc** [comment]
Do you talk about the commented line EventSystem.cpp@2626 : lua_close(lua_state);  ?

**Comment by gaudryc** [comment]
I'm running another instance with 100 files script_device_demo__.lua and 100 files script_time_demo__.lua.

Each instance is domoticz V2.3502.

**Comment by gizmocuz** [comment]
Yes, in the EvaluateLua function

**Comment by gaudryc** [comment]
No memory leak while monitoring HTTP on domoticz_test_1 instance :
The values for the use of virtual, resident and shared memory always remain the same : 77596 kB, 9740 kB, 8652 kB.

samedi 31 octobre 2015, 17:15:46 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:00.65 domoticz_test_1
samedi 31 octobre 2015, 17:30:47 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:01.26 domoticz_test_1
samedi 31 octobre 2015, 17:45:47 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:01.87 domoticz_test_1
samedi 31 octobre 2015, 18:00:47 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:02.48 domoticz_test_1
samedi 31 octobre 2015, 18:15:47 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:03.04 domoticz_test_1
samedi 31 octobre 2015, 18:30:48 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:03.57 domoticz_test_1
samedi 31 octobre 2015, 18:45:48 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:04.17 domoticz_test_1
samedi 31 octobre 2015, 19:00:48 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:04.78 domoticz_test_1
samedi 31 octobre 2015, 19:15:48 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:05.33 domoticz_test_1
samedi 31 octobre 2015, 19:30:49 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:05.88 domoticz_test_1
samedi 31 octobre 2015, 19:45:49 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:06.52 domoticz_test_1
samedi 31 octobre 2015, 20:00:49 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:07.15 domoticz_test_1
samedi 31 octobre 2015, 20:15:49 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:07.77 domoticz_test_1
samedi 31 octobre 2015, 20:30:49 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:08.38 domoticz_test_1
samedi 31 octobre 2015, 20:45:50 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:08.95 domoticz_test_1
samedi 31 octobre 2015, 21:00:50 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:09.52 domoticz_test_1
samedi 31 octobre 2015, 21:15:50 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:10.08 domoticz_test_1
samedi 31 octobre 2015, 21:30:50 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:10.65 domoticz_test_1
samedi 31 octobre 2015, 21:45:51 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:11.23 domoticz_test_1
samedi 31 octobre 2015, 22:00:51 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:11.83 domoticz_test_1
samedi 31 octobre 2015, 22:15:51 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:12.43 domoticz_test_1
samedi 31 octobre 2015, 22:30:51 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:13.08 domoticz_test_1
samedi 31 octobre 2015, 22:45:52 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:13.69 domoticz_test_1
samedi 31 octobre 2015, 23:00:52 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:14.28 domoticz_test_1
samedi 31 octobre 2015, 23:15:52 (UTC+0100) | 22802 root      20   0 77596 9740 8652 S   0,0  1,0   0:14.91 domoticz_test_1

**Comment by gaudryc** [comment]
No memory leak while monitoring HTTPS on domoticz_test_2 instance :
The values for the use of virtual, resident and shared memory almost remain the same : ~77756 kB, 9,8 mB, 8840 kB.

samedi 31 octobre 2015, 17:16:01 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:00.97 domoticz_test_2
samedi 31 octobre 2015, 17:31:01 (UTC+0100) | 22858 root      20   0 77724 9,8m 8840 S   0,0  1,1   0:01.81 domoticz_test_2
samedi 31 octobre 2015, 17:46:01 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:02.70 domoticz_test_2
samedi 31 octobre 2015, 18:01:01 (UTC+0100) | 22858 root      20   0 77724 9,8m 8840 S   0,0  1,1   0:03.60 domoticz_test_2
samedi 31 octobre 2015, 18:16:02 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:04.48 domoticz_test_2
samedi 31 octobre 2015, 18:31:02 (UTC+0100) | 22858 root      20   0 77724 9,8m 8840 S   0,0  1,1   0:05.33 domoticz_test_2
samedi 31 octobre 2015, 18:46:02 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:06.18 domoticz_test_2
samedi 31 octobre 2015, 19:01:02 (UTC+0100) | 22858 root      20   0 77724 9,8m 8840 S   0,0  1,1   0:06.99 domoticz_test_2
samedi 31 octobre 2015, 19:16:03 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:07.83 domoticz_test_2
samedi 31 octobre 2015, 19:31:03 (UTC+0100) | 22858 root      20   0 77724 9,8m 8840 S   0,0  1,1   0:08.66 domoticz_test_2
samedi 31 octobre 2015, 19:46:03 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:09.51 domoticz_test_2
samedi 31 octobre 2015, 20:01:03 (UTC+0100) | 22858 root      20   0 77724 9,8m 8840 S   0,0  1,1   0:10.35 domoticz_test_2
samedi 31 octobre 2015, 20:16:04 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:11.11 domoticz_test_2
samedi 31 octobre 2015, 20:31:04 (UTC+0100) | 22858 root      20   0 77724 9,8m 8840 S   0,0  1,1   0:11.90 domoticz_test_2
samedi 31 octobre 2015, 20:46:04 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:12.68 domoticz_test_2
samedi 31 octobre 2015, 21:01:04 (UTC+0100) | 22858 root      20   0 77724 9,8m 8840 S   0,0  1,1   0:13.47 domoticz_test_2
samedi 31 octobre 2015, 21:16:05 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:14.20 domoticz_test_2
samedi 31 octobre 2015, 21:31:05 (UTC+0100) | 22858 root      20   0 77724 9,8m 8840 S   0,0  1,1   0:14.97 domoticz_test_2
samedi 31 octobre 2015, 21:46:05 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:15.73 domoticz_test_2
samedi 31 octobre 2015, 22:01:05 (UTC+0100) | 22858 root      20   0 77724 9,8m 8840 S   0,0  1,1   0:16.54 domoticz_test_2
samedi 31 octobre 2015, 22:16:06 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:17.34 domoticz_test_2
samedi 31 octobre 2015, 22:31:06 (UTC+0100) | 22858 root      20   0 77724 9,8m 8840 S   0,0  1,1   0:18.19 domoticz_test_2
samedi 31 octobre 2015, 22:46:06 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:18.99 domoticz_test_2
samedi 31 octobre 2015, 23:01:06 (UTC+0100) | 22858 root      20   0 77724 9,8m 8840 S   0,0  1,1   0:19.77 domoticz_test_2
samedi 31 octobre 2015, 23:16:06 (UTC+0100) | 22858 root      20   0 77756 9,8m 8840 S   0,0  1,1   0:20.59 domoticz_test_2

**Comment by gaudryc** [comment]
lua_state is closed in the CEventSystem::luaThread method so you cannot close it again at the end of EvaluateLua function (->SIG_SEG).

After 2 hours using 200 demo scripts, I don't have any memory leak :

2015/10/31 23:03:25 | 10573 root      20   0  101m  10m 9696 S   0,0  1,2   0:04.19 domoticz_test_3
2015/10/31 23:18:25 | 10573 root      20   0  100m  11m 9888 S   0,0  1,2   1:06.10 domoticz_test_3
2015/10/31 23:33:26 | 10573 root      20   0  100m  11m 9888 S   0,0  1,2   2:09.64 domoticz_test_3
2015/10/31 23:48:26 | 10573 root      20   0  100m  11m 9888 S   0,0  1,2   3:13.08 domoticz_test_3
2015/11/01 00:03:26 | 10573 root      20   0  100m  11m 9888 S   0,0  1,2   4:15.64 domoticz_test_3
2015/11/01 00:18:26 | 10573 root      20   0  100m  11m 9880 S   0,0  1,2   5:30.84 domoticz_test_3
2015/11/01 00:33:27 | 10573 root      20   0  100m 7012 5228 S  98,0  0,7   7:13.07 domoticz_test_3
2015/11/01 00:48:27 | 10573 root      20   0  100m 6188 4404 S   0,0  0,7   8:12.51 domoticz_test_3
2015/11/01 01:03:27 | 10573 root      20   0  100m 5936 4152 S   0,0  0,6   9:11.80 domoticz_test_3

**Comment by gizmocuz** [comment]
So the memory leak is gone ? That would be great!

**Comment by gaudryc** [comment]
I was testing with r3521 and Uptimrobot on my domoticz and domotiz_test_3 (HTTPS).
Everything seems to be OK.
Between 3h04 and 7h00, there was no Wifi so no Uptimerobot request.
On the domoticz instance (the real), you can see memory is stable to ~2.2%.

I will kepp you informed.

Date                | PID   USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND
====================|=======================================================================
2015/11/01 02:09:33 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   0:34.36 domoticz
2015/11/01 02:24:33 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   1:00.68 domoticz
2015/11/01 02:39:33 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   1:27.00 domoticz
2015/11/01 02:54:34 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   1:52.96 domoticz
2015/11/01 03:09:34 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   2:19.61 domoticz
2015/11/01 03:24:34 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   2:51.62 domoticz
2015/11/01 03:39:34 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   3:17.38 domoticz
2015/11/01 03:54:35 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   3:43.54 domoticz
2015/11/01 04:09:35 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   4:06.73 domoticz
2015/11/01 04:24:35 | 24130 root      20   0  178m  19m  12m S   0,0  2,1   4:28.12 domoticz
2015/11/01 04:39:35 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   4:50.22 domoticz
2015/11/01 04:54:35 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   5:11.82 domoticz
2015/11/01 05:09:36 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   5:33.24 domoticz
2015/11/01 05:24:36 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   5:55.62 domoticz
2015/11/01 05:39:36 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   6:17.87 domoticz
2015/11/01 06:09:37 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   7:03.02 domoticz
2015/11/01 06:24:37 | 24130 root      20   0  177m  18m  12m S  17,7  2,0   7:25.64 domoticz
2015/11/01 06:39:37 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   7:49.07 domoticz
2015/11/01 07:24:38 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   8:55.72 domoticz
2015/11/01 07:39:38 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   9:17.91 domoticz
2015/11/01 07:54:38 | 24130 root      20   0  177m  18m  12m S   0,0  2,0   9:39.75 domoticz
2015/11/01 08:09:39 | 24130 root      20   0  177m  18m  12m S   5,7  2,0  10:07.56 domoticz
2015/11/01 08:24:39 | 24130 root      20   0  177m  18m  12m S   0,0  2,0  10:36.18 domoticz
2015/11/01 08:39:39 | 24130 root      20   0  177m  18m  12m S   0,0  2,0  11:01.46 domoticz
2015/11/01 08:54:39 | 24130 root      20   0  177m  18m  12m S   0,0  2,0  11:27.19 domoticz
2015/11/01 09:09:40 | 24130 root      20   0  177m  18m  12m S   0,0  2,0  11:54.26 domoticz
2015/11/01 09:24:40 | 24130 root      20   0  177m  18m  12m S   6,0  2,0  12:21.05 domoticz
2015/11/01 09:39:40 | 24130 root      20   0  177m  18m  12m S   0,0  2,0  12:47.17 domoticz
2015/11/01 09:54:40 | 24130 root      20   0  178m  20m  12m S   0,0  2,2  13:13.26 domoticz
2015/11/01 10:09:40 | 24130 root      20   0  178m  20m  12m S   0,0  2,2  13:38.76 domoticz
2015/11/01 10:24:41 | 24130 root      20   0  178m  20m  12m S  34,1  2,2  14:05.02 domoticz
2015/11/01 10:39:41 | 24130 root      20   0  177m  19m  12m S   0,0  2,1  14:31.19 domoticz
2015/11/01 10:54:41 | 24130 root      20   0  177m  19m  12m S   0,0  2,1  14:57.00 domoticz
2015/11/01 11:09:41 | 24130 root      20   0  177m  19m  12m S   0,0  2,1  15:34.55 domoticz
2015/11/01 11:24:42 | 24130 root      20   0  178m  19m  12m S   0,0  2,1  16:02.13 domoticz
2015/11/01 11:54:42 | 24130 root      20   0  178m  19m  12m S   0,0  2,1  16:59.86 domoticz
2015/11/01 12:09:42 | 24130 root      20   0  178m  19m  12m S   0,0  2,1  17:29.57 domoticz
2015/11/01 12:24:43 | 24130 root      20   0  178m  19m  12m S   0,0  2,1  17:58.65 domoticz
2015/11/01 12:39:43 | 24130 root      20   0  179m  20m  12m S   0,0  2,2  18:27.68 domoticz
2015/11/01 12:54:43 | 24130 root      20   0  178m  19m  12m S   5,9  2,1  18:55.89 domoticz
2015/11/01 13:09:43 | 24130 root      20   0  178m  19m  12m S   0,0  2,1  19:24.78 domoticz
2015/11/01 13:24:43 | 24130 root      20   0  178m  19m  12m S   0,0  2,1  19:53.88 domoticz
2015/11/01 13:39:44 | 24130 root      20   0  178m  19m  12m S   0,0  2,1  20:24.81 domoticz
2015/11/01 13:54:44 | 24130 root      20   0  178m  19m  12m S   0,0  2,2  20:55.28 domoticz
2015/11/01 14:09:44 | 24130 root      20   0  178m  19m  12m S   0,0  2,2  21:36.83 domoticz
2015/11/01 14:24:44 | 24130 root      20   0  178m  19m  12m S   0,0  2,2  22:04.66 domoticz
2015/11/01 14:39:45 | 24130 root      20   0  178m  19m  12m S   0,0  2,2  22:32.11 domoticz
2015/11/01 14:54:45 | 24130 root      20   0  178m  20m  12m S   0,0  2,2  23:00.50 domoticz
2015/11/01 15:09:45 | 24130 root      20   0  178m  20m  12m S   0,0  2,2  23:30.44 domoticz
2015/11/01 15:24:45 | 24130 root      20   0  178m  20m  12m S   0,0  2,2  23:58.52 domoticz
2015/11/01 15:39:46 | 24130 root      20   0  178m  20m  12m S   0,0  2,2  24:26.51 domoticz
2015/11/01 15:54:46 | 24130 root      20   0  178m  20m  12m S   0,0  2,2  24:54.67 domoticz
2015/11/01 16:09:46 | 24130 root      20   0  178m  20m  12m S   0,0  2,2  25:22.33 domoticz
2015/11/01 16:24:46 | 24130 root      20   0  179m  20m  12m S   0,0  2,2  25:51.70 domoticz
2015/11/01 16:39:47 | 24130 root      20   0  178m  20m  12m S   0,0  2,2  26:20.08 domoticz
2015/11/01 16:54:47 | 24130 root      20   0  178m  20m  12m S  16,2  2,2  26:52.61 domoticz
2015/11/01 17:09:47 | 24130 root      20   0  178m  20m  12m S  22,0  2,2  27:26.49 domoticz
2015/11/01 17:24:47 | 24130 root      20   0  179m  20m  12m S   0,0  2,3  27:56.23 domoticz

**Comment by gizmocuz** [comment]
Looking good! I think it might have been fixed with the way the file from disk is read now.

**Comment by gaudryc** [comment]
After 60 hours :

PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM
24130 root      20   0  189m  25m 7524 S   6,6  2,8

So, it is quite normal.
There is something but we don't where yet.

**Comment by gizmocuz** [comment]
Or we fixed it with the previous commit? (file read change)

**Comment by gaudryc** [comment]
I left turn the 3521 release.

The resident memory increased by 105% in 90 hours: ~ 200KB memory leak per hour.
The virtual memory increased by 13% in 90 hours.

The memory leak does not appear in the following areas:
- HTTP(S), while polling;
- Lua
- Database backup using HTTP;
- Wunderground.

Do you know a way to run domoticz as a daemon with Valgrind on raspberry ?

**Comment by gizmocuz** [comment]
you could use the 'screen' command, and then run domoticz with

valgrind --leak-check=yes myprog arg1 arg2

You do have to compile with -g
(http://valgrind.org/docs/manual/quick-start.html#quick-start.prepare)

**Comment by gaudryc** [comment]
> Do you try it ?

Because I can't due to unhandled instructions in libcrypto.so and

> licofi_rpi.so.

**Comment by correa** [comment]
On the subject of memory leak, the upstream mosquito library have some memory leak fixes in upper versions. We are using a quite old version from 2013. This version also have some issues detecting SSL in MacOS. 

Would like to try to update, can I remove our copy and add as git submodule?

**Comment by gizmocuz** [comment]
If it still builds also on windows, than that might be a good option

**Comment by gaudryc** [comment]
I can't advise you to update this library because I don't use it and can't test it (I don't have any MySensors devices).
I don't even know where the source code is coming from.
I can't compare the old version to the new one.
I can't have the latest release notes.

If you can do all of these things, you can do it.

**Comment by correa** [comment]
It comes from mosquitto.org and it's BSD licensed, but our local copy has only parts of the original release package. I was mistaken, it's not from 2013, but it's from earlier this year, a couple of releases ago. Currently we are at 1.4.2. The changelog from upstream says there was an openwrt crash fix, which would be nice to have. It would be better if it were a submodule we could update without having to do much patching on it.

MQTT is a standard protocol and looks like there is a test server one can connect to test if it's working, but it won't be an actual MySensors hardware. I will keep this in a backlog until I can find a way to test the changes.

**Comment by gizmocuz** [comment]
thanks, if you find something, let us know (it was quite recently added to domoticz, so its not so old)
