### ISSUE TITLE
LIghtSwitches tab shows nothing

### ISSUE THREAD

**Issue by riesch** [domoticz/domoticz#1762]
LightSwitches Tab shows no rooms to pick from and no switches.
3.8279 
latest raspbian jessie version, july download
Raspberry pi 3
I run about 200 sensors, 11 rooms, Hardware: zwave, dummy, rfxcom, wunderground, hue, fritz
The only system modification involves a usb ethernet bridge to connect the hue bridge to the intranet through the pi

It occured after a clean install with a restore of the old database, though not immediately. I did see the tab intact and after solving some issues it dissapeard

Help!

**Comment by riesch** [comment]
![img_4998](https://user-images.githubusercontent.com/29521240/29248478-959b4e76-8019-11e7-902c-202ee5c7e330.PNG)
Oddly the same behaviour in the groups/scenes tab on my ipad - though not on my mac

**Comment by riesch** [comment]
In https mode this issue resolves, it exists in http mode only
Good enough for me, but still an issue

**Comment by gizmocuz** [comment]
clear your browser cache AND appcache, two different things, and use our forum.
As stated when you posted this issue, this is NOT for user problems!
