### ISSUE TITLE
v. 3.8153 : Lua scripts not triggered anymore

### ISSUE THREAD

**Issue by glecoz** [domoticz/domoticz#1763]
After upgrading v. 3.5877 > v. 3.8153, all my Lua scripts stopped being triggered by their corresponding devices (Lua print function at the beginning of any Lua script not shown in logs anymore, so the scripts are not triggered at all, while the corresponding device status are still updated properly in Domoticz UI, no errors in log, only positive log entries from RfxCom / Enocean events).

Had to rollback to previous v. 3.5877 and all is working fine again. 

Couldn't find any solution or workaround online for this issue on v. 3.8153, those found didn't help. 

Could the Domoticz team explain if there are some new requirements related to Lua (expected version, script naming changes etc...) ? Or push / post a fix ?

My current Lua version : 5.1.5

Thanks.

**Comment by gizmocuz** [comment]
Please use our forum! (there are answers)
