### ISSUE TITLE
Existing custom scripts/lua symlinks should not be overwritten by upgrade process

### ISSUE THREAD

**Issue by glecoz** [domoticz/domoticz#1764]
**Note :**
This issue has been renamed due to changes on problem identification.
See the following [comment](#issuecomment-322209938) below for the actual description of the current issue.

-------------------

As mentioned in #1763, all my Lua scripts stopped being triggered after upgrading to v3.8153.

@jvandenbroek, @balintkozma :

After investigation and upon recommendation of @gizmocuz on this [thread](https://www.domoticz.com/forum/viewtopic.php?f=6&t=18762&p=146171#p146171), it seems that commit 74b590528836 on `main/EventSystem.cpp` now requires that Lua script names must match device names.

This creates a huge regression in some cases, like mine :

I have 4 Chacon remote controls (RCs) like [this](https://goo.gl/6FWgNC) in a room, with a total of about 20 active buttons, all buttons appear as light switches in Domoticz, and I use a **single** Lua script (see code below) that **filters** the device name with a RegEx pattern and when matches, send the device name and button action [On|Off|Group On|Group Off] as variables to a PHP script :

```
-- Script that receives all Chacon RCs (remote controls) events (buttons pressed)

-- Always include this block
package.path = debug.getinfo(1,"S").source:match[[^@?(.*[\/])[^\/]-$]] .."?.lua;".. package.path
require ("common/functions");
commandArray = {}
--

allowed = filter_devicechanged({"^CHACON%_RC%_SL%_"}) -- All switches named CHACON_RC_SL_* on box
if (allowed['result']) then
    run_php_script('chacon_rc', '--button="'..allowed['var']..'" --action="'..otherdevices[allowed['var']]..'"')
    --print('It's a Chacon RC : --button='..allowed['var']..' --action='..otherdevices[allowed['var']])
else
    --print("It's another device... : "..get_first(devicechanged))
end

return commandArray -- Always maintain this line at the very end of this script
```

**So, how could this be done now ?** I cannot imagine to create 20 Lua scripts (one per device) that would include another single Lua script, this would be quite a nonsense :\

**I would therefore strongly suggest that this new constraint should be removed or improved, so that users can still filter multiple device names with a single Lua script when needed.**

**Comment by dannybloe** [comment]
Just use dzVents and you can create a wildcard trigger for you script. 

Afaik, this is all done to make the event system perform better. Earlier all scripts were always called even though you had your scripts named after the device (as the documentation already said you should). Seemed to me that you always used an undocumented side-effect of the previous implementation.

But that's my hunch.

**Comment by glecoz** [comment]
Hmmm... got it, thanks @dannybloe, I didn't know the existence of dzVents, this should do the trick, for those interested, documentation about the wildcards you're talking about can be found [here](https://www.domoticz.com/wiki/DzVents:_next_generation_LUA_scripting#on_.3D_.7B_..._.7D) and [here](https://www.domoticz.com/wiki/DzVents:_next_generation_LUA_scripting#Quickstart).

**Comment by jvandenbroek** [comment]
Despite being recommended to move to dzVents, matching all devices work fine as long as you don't name the script as a device name, see also note here: http://www.domoticz.com/wiki/Events#By_adding_your_own_scripts_to_the_scripts.2Flua.2F_dir_in_your_domoticz_installation_folder.

**Comment by glecoz** [comment]
@jvandenbroek, do you mean that the new script naming constraint implemented in v3.8153 uses partial and case insensitive matching ?

I mean, my current Lua script is named `script_device_chacon_rc.lua` and only have devices named `CHACON_RC_SL1_A1`, `CHACON_RC_SL1_A2` and so on... but I don't have any device named only `chacon_rc` as is my script name... even though my Lua script is not triggered anymore, while you seem to say that this should work in this case... This point can be useful to know for further reference and avoid any confusion... Can you elaborate on this ?

**Comment by jvandenbroek** [comment]
No, not partial, at least it's not intended that way. I've just tested it myself and it works fine when I use script_device_test.lua while having devices named like 'test 1' 'test 2', it still matches on ALL device changes (not only those containing test in it). So it should work fine as you have it and you're just having another issue here. Please continue in forum.

**Comment by glecoz** [comment]
Thanks @jvandenbroek for disambiguating, things are clear for me now, although I still don't understand why it stopped working then, I should have another new issue as you say, but I will try to move my code to dzVents, it seems to be safer and avoids custom filtering code as I did... thanks again...

**Comment by glecoz** [comment]
@jvandenbroek said :
> So it should work fine as you have it and you're just having another issue here. 

Finally found the whole issue :

The `./updaterelease` shell script (probably also triggered from the web UI update check) basically just downloads and extracts the new domoticz tarball from http into the current dir, and thus wiped out my custom `domoticz/scripts/lua` symlink with a new lua dir with just a demo lua script.

Since the `./scripts/lua` path is probably one of the few (if not the only) path a Domoticz end user can customize and probably need to make persistent across upgrades (including from a custom symlinked location pointing to a separate app), it would be nice and relevant if the `./updaterelease` script could check if a `scripts/lua` dir or symlink does not already exist, and only if not, move the sample lua dir from a temp or build location of the tarball to its final location, as follows :

```
# LUA_DIR below should be something like a concat of $PWD + '/scripts/lua' or similar
if [ ! -e $LUA_DIR ]
then
   # Move the lua dir and demo script from a temp location in the tarball to its final location 
   # only if no lua dir AND no lua symlink already exists
fi
```

This would ensure that custom paths are not wiped out. 

I personally have one git versioned domoticz dir (useful for domoticz rollbacks and testing) and my own home automation app git versioned in another repo (`/home/pi/some_user/home-automation` in the dir list below) with php bash and lua scripts triggered from the domoticz/scripts dir through relative paths in the lua scripts, this way most of my home automation logic is independent from any home automation platform such as Domoticz among others, and apps remain separated :

```
ls -la ~/domoticz/scripts
... (other Domoticz files / dirs)
lrwxrwxrwx 1 pi pi   48 Dec  4  2016 bash -> /home/pi/some_user/home-automation/scripts/cli/bash
lrwxrwxrwx 1 pi pi   56 Aug 14 15:36 lua -> /home/pi/some_user/home-automation/scripts/cli/lua/domoticz
lrwxrwxrwx 1 pi pi   47 Dec  4  2016 php -> /home/pi/some_user/home-automation/scripts/cli/php
... (other Domoticz files / dirs)
```

In the dir list above, the bash and php symlinks were preserved, since they don't exist in the domoticz tarballs, but the lua symlink had been replaced by a brand new lua sample dir with a demo file, during the upgrade process :(

Such a check would avoid users remember to manually recreate their scripts symlink(s) after each upgrade, or to apply a custom upgrade script after a web UI upgrade, and could avoid trouble for hours after each upgrade :) ... otherwise a dedicated user dir (and user/scripts/lua) that would remain untouched across upgrades could also make sense to avoid mixing custom paths within the core domoticz dirs.

**Comment by jvandenbroek** [comment]
Good you figured it out and thanks for letting know what caused it. But it's not an issue if you don't have the Lua dir as a symlink, obviously it doesn't always remove and replace the contents of that dir on updates (then all users would go crazy, not just you :P). I'm not sure if we should support symlink this way, because it could introduce other side effects. The update simple extracts a dir/file structure, which would indeed override the symlink.

We could leave this open for a while and have others look at this, but I don't think we should waste too much time on this.

**Comment by glecoz** [comment]
Thanks for your feedback, I partly agree but IMHO, since the `scripts/lua` is already preserved in case of a physical dir, one might guess it will also be preserved the same way in case of a symlink, and users cannot guess in advance the current different behaviour for this path between physical and symlink cases. Patching this issue could avoid long troubles, but I personally don't mind, since all my lua scripts include a functions.lua script, I could implement a constant with the destination path and make a secondary include as a workaround (thus duplicating most of my lua scripts) or simply create a custom upgrade script that recreates the scripts/lua symlink at the end of the process, but at least one reliable user path that remains untouched under all circumstances (whether its a dir or symlink) could make sense as most other apps do (Redmine, Symfony, etc... to name a few)

**Comment by gizmocuz** [comment]
Never symlink a base file , always make a copy
Yes it gets overwritten by the repo file and this is intended...

**Comment by glecoz** [comment]
I was talking about the case where the scripts/lua directory itself is symlinked (not a base file), and pointing to an independent personal app (which is my case) where other scripts such as php, bash, lua reside, the issue is that the scripts/lua currently remains untouched when is a dir and removed when is a symlink, this is not very consistent and requires to implement a custom domoticz shell update script to restore the symlink after the domoticz upgrade process, for users that have their own middleware app (i.e. PHP), and potentially consuming several APIs at the same time (Domoticz, Fibaro, etc...). Second, the lua/scripts is the most important dir for end users, where all their customization can reside as files within domoticz and therefore should be preserved in all cases. Duplicating all the required scripts from the middleware app to each tier platform doesn't make sense IMHO.
