### ISSUE TITLE
V3.8315 Unable to protect switch - checkbox missing

### ISSUE THREAD

**Issue by darkrain-nl** [domoticz/domoticz#1768]
I often protect switches to make sure I don't turn them off by accident.
With the latest beta this does not work anymore because the checkbox is missing:
![2017-08-18 10_59_01-domoticz](https://user-images.githubusercontent.com/24763370/29451946-d9ea8616-8404-11e7-8c92-c7a044fd1b9f.png)

**Comment by gizmocuz** [comment]
It is still there, could you delete the browser cache AND appcache, or try the chrome browser

**Comment by darkrain-nl** [comment]
After clearing the caches it is still not appearing, it does work on Chrome browser.
But I use Firefox and also tested Edge, both don't work... Should it work on these browsers or is just Chrome supported?

**Comment by gizmocuz** [comment]
Probably only chrome at the moment, working on the default theme for the next couple of weeks

**Comment by darkrain-nl** [comment]
Fair enough, Chrome as a workaround for the time being is fine by me.
Closing this now.
