### ISSUE TITLE
v3.8153: Python plugin framework - connection buffering send?

### ISSUE THREAD

**Issue by leejoow** [domoticz/domoticz#1769]
I'm using the Tradfri plugin from moroen in Domoticz. All is working correctly as long as I don't send to many commands.

In the debugging from pytradfri, I see that Domoticz sends the following:

```
Data received: b'{"action": "setHex", "deviceID": "65538", "hex": "efd275"}'
Data received: b'{"action": "setHex", "deviceID": "65543", "hex": "efd275"}{"action": "setHex", "deviceID": "65544", "hex": "efd275"}'
Unhandled Error
```

This should be 3 seperate commands (from the plugin the Send command is called three times, not two times. Because this is received as one datastream, the JSON is not correct and cannot be decoded by the json library.

Is this intended behaviour or a bug?

**Comment by dnpwwo** [comment]
Hi leejoow,

The JSON looks fine so if there is a bug I would say it is at the Tradfri
end. Domoticz will do individual network writes for each Send but has no
control on how the network layer actually sends the data.

The Kodi plugin recieves JSON and I've seen 3 messages arrive in the same
network packet, I'm not sure why you believe 2 messages together is invalid.

You can delay the sending of data to give slower devices more time which
could help (there is literally a 'delay' parameter to the Send command that
is the number of seconds Domoticz will wait) for example:

                self.TelnetConn.Send('PW?\r')
                self.TelnetConn.Send('ZM?\r', Delay=1)
                self.TelnetConn.Send('Z2?\r', Delay=2)
                self.TelnetConn.Send('Z3?\r', Delay=3)

cheers,

dnpwwo

**Comment by leejoow** [comment]
Hi dnpwwo,

I've altered the plugin I'm using. I expected every individual JSON had to be a seperate event.


Leo
