### ISSUE TITLE
Feature request: Multiple Toon hardware usage

### ISSUE THREAD

**Issue by remkolodder** [domoticz/domoticz#1770]
Hi,

I am using a Pi and enabled our homeToon to retrieve stats from it etc.
Now my parents also have a Toon and want me to generate some information and buttons for them within the same domoticz instance. That does not work as it seems that the ToonHardware is expecting one device per domoticz instance.

Would it be possible to add more Toon hardware devices ?

Thanks !

**Comment by gizmocuz** [comment]
Yes it is. But please use our forum
