### ISSUE TITLE
domoticz does not start on new raspian stretch (ssl problem)

### ISSUE THREAD

**Issue by TychoHae** [domoticz/domoticz#1772]
On a clean install of raspbian stretch when you install via

sudo curl -L install.domoticz.com | bash

domoticz gives the error:

./domoticz: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

stretch seems to ship with libssl.1.1.0

**Comment by gizmocuz** [comment]
Please use our forum, it is already mentioned there
