### ISSUE TITLE
v3.8153 : Level 0% (dropdown menu empty) when adding existing dimmer as a device to a scene

### ISSUE THREAD

**Issue by glecoz** [domoticz/domoticz#1776]
On the scenes panel > Edit a scene > under the Devices table, when adding an existing dimmer device to the scene, the Level menu remains empty / unselectable, and the device is added with 0% to the scene, the corresponding light will thus never switch on. Same while trying to update the device level after adding it to the scene.

A partial workaround is to switch the device property as an on/off device, add it to the scene, then revert the device back to a dimmer, it will at least be added with level 100% and will therefore switch on.

Issue appears at least on : Chrome Version 60.0.3112.101 (no errors on JS console, only jQuery Synchronous XMLHttpRequest deprecation notice).
But no issue on : Firefox 54.0.1 (Level dropdown / select correctly populated)
Mac OS Sierra 10.12.6

**Comment by gizmocuz** [comment]
Dont have this issue.
Could you:
- Clear the browser cache
- Clear the app-cache (yes two different things)
- Add a dummy switch
- Change it's type to dimmer
- Edit an existing scene, select this dummy dimmer
- I see the 'Level' option appearing

"jQuery Synchronous XMLHttpRequest deprecation notice)." is a known warning and does is not related to this

**Comment by glecoz** [comment]
Did all the steps you suggested but still have the issue, the only difference is that now I only have the "0 %" option available in the "level" select field while adding the dummy switch into the scene, while before this field was completely empty. Same issue on Chrome 60.0.3112.16 for Android.

**Comment by gohamstergo** [comment]
same issues here. did the suggested workaround for now.

**Comment by snyfear** [comment]
Same problem here with Firefox 59.0b8 but not present on Chrome v64

**Comment by gizmocuz** [comment]
Tested with firefox 60 and latest beta, no problem anymore
