### ISSUE TITLE
no connection with Toon since v3.8364

### ISSUE THREAD

**Issue by anconakip** [domoticz/domoticz#1783]
i have since the updat v3.8364 no connection with my Toon.

**Comment by freemann** [comment]
"duplicate" of https://github.com/domoticz/domoticz/issues/1782

**Comment by tlpeter** [comment]
I have it working again on 3.8.355. If i upgrade to a later release (at least one from 24-8-2017) then i get a login error.

**Comment by freemann** [comment]
@gizmocuz another issue after changing nothing :)
