### ISSUE TITLE
SolarEdge via Web API Error getting http data

### ISSUE THREAD

**Issue by JurikRistjouw** [domoticz/domoticz#1784]
version 3.8367
I noticed that the settings of the SolarEdge have changed somewhere in the latest betas. Since a few days I noticed no more data coming in so I investigated. Somehow the settings have changed in the hardware settings of the SolarEdge Web API. It wants a remote address, port and username/password and API key, instead of just the API key.

I have no clue what to fill in there and the wiki is outdated. 

I tried: prod.solaredge.com port 22222 with the username and password of the solaredge site and the API key, but no luck with that.

Thanx for helping out.

**Comment by gizmocuz** [comment]
It did not... But please show me the change

**Comment by mblokland** [comment]
![image](https://user-images.githubusercontent.com/31371265/29742577-1b4e90e2-8a82-11e7-9c19-693ba0b50c67.png)

For me also not working anymore

**Comment by JurikRistjouw** [comment]
@gizmocuz i also couldn't find any code changes the last days that would explain this. Hence the issue. It is like @mblokland shows (thanx for being faster than me) 
PS: last update from sensor was 23-08-2017 20:46 (i guess i updated at that time)

**Comment by mblokland** [comment]
fixed it after changing settings (adding longitude and latitude)

Remote address: Internal IP adress of solaredge
API Key: xxxxxx

working as before now.

**Comment by JurikRistjouw** [comment]
@mblokland I tried that, no luck with latest beta .8369 I already had the lat/long set, left the portnumber blank. Did you fill that in also?

edit: tried port 22222 no result
back to stable, only api key, instant data from solaredge.

**Comment by mblokland** [comment]
@JurikRistjouw nope left the port number blank also, me also back to stable! Working as before

**Comment by JurikRistjouw** [comment]
works again with new beta!
