### ISSUE TITLE
domoticz.com has been put offline?

### ISSUE THREAD

**Issue by djvdorp** [domoticz/domoticz#1789]
See: https://www.domoticz.com/

The website now states this:

```
Offline gezet door hsc vanwege abuse op 31aug
```

**Comment by Cino2424** [comment]
what does this mean?

**Comment by Ittiz** [comment]
seeing the same thing

**Comment by djvdorp** [comment]
@Cino2424 it is Dutch, and functionally means the website has been put offline by hsc (? probably system administrator of webhost) because of abuse on the 31th of August. I reported it as I was not sure if the author(s) of this project were aware of this yet.

Technically, it means that currently pressing Update in your Domotics installation won't work afaik.

**Comment by gizmocuz** [comment]
I notified the hosting provider... No idea why they did this, it could be related to bandwidth usage

**Comment by Tommit1** [comment]
In times of internet a hosting provider may use a notification or warning mail to inform?

**Comment by gizmocuz** [comment]
i aggree

**Comment by ultrara1n** [comment]
Online again, time to change the hosting provider 😆

**Comment by gizmocuz** [comment]
The 'load' was to high... i'm in contact to see if they can put us on a separate VPS
