### ISSUE TITLE
Room Plan screen doesn't get the proper name

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#1791]
Latest beta version.

I've been trying to add my house to the plans on Domoticz and I've noticed a bit of an issue that I'm pretty sure is a bug.  After the first room plan I add the subsequent room plans take on the name of the previous room plan and I have to edit it to correct the name.

**Comment by gizmocuz** [comment]
You mean you press 'Add Plan' enter a name, click on the ADD button, press 'Add Plan' again, give another name, and you see it added with the first name?
I do not have this... Did you clear your browser cache + appcache ?

**Comment by gizmocuz** [comment]
No feedback, closing issue. Please use our forum.
