### ISSUE TITLE
Email notification broken 3.8373 and newer

### ISSUE THREAD

**Issue by kungknut** [domoticz/domoticz#1795]
Hi!

I have noticed the email-notifications (Setup -> Settings -> Email) have stopped working since version 3.8373, maybe earlier. When degrading to latest beta (3.8356), downloaded from https://domoticz.com/downloads/, the problem disappear.

Regards

**Comment by TheReptile** [comment]
I guess it's the same issue as https://github.com/domoticz/domoticz/issues/1782

**Comment by kungknut** [comment]
Looks like it. No need for duplicates right? Closing this.
