### ISSUE TITLE
Feature Request: inverse door lock switch type

### ISSUE THREAD

**Issue by gorillica** [domoticz/domoticz#1799]
I realize that this was discussed under issue #916, but that's closed now.

I've got a Aeotec ZW062 Garage Door controller. It reports "off" when the door is closed/locked, and "on" when the door is open. I can't see any configuration parameter which would let me reverse this. So for me an inverted door lock switch type would be useful.

At the moment when I have the door switch set up as "Door lock", it shows "open" when the door is closed, and vice versa. Domoticz does show the correct state when I have the switch set as a "Door contact", but unfortunately eDomoticz (which I use to get Domoticz devices into Homebridge/Homekit) now doesn't let you operate Door contact devices—they're displayed as contact sensors only!

Thanks.

I'm currently running Domoticz 3.8389 beta (on Stretch, so no libssl-related problems here), and eDomoticz 2.0.11.

**Comment by gizmocuz** [comment]
Then i think you have to:
- Do some rewiring... or
- Talk to eDomoticz

You can probably also change it's type to a normal on/off and make some custom icons ?

**Comment by gorillica** [comment]
OK, I'll fiddle with it and see what I can come up with. I might be able to do something with accessing the switch in Homebridge over MQTT rather than through the eDomoticz plugin.
