### ISSUE TITLE
Domoticz v. 3.8153 Blockly broken If - Else if logic

### ISSUE THREAD

**Issue by motejowi** [domoticz/domoticz#1804]
When using **If - Else if** block, **Else if** statement is always entered, regardless of **If** statement result.
Correct execution should be like this: 
execute **Else if** statement ONLY when **If** statement was FALSE.

Example of wrong execution in Domoticz:
```
If button = On
Do
  If light = Off and a = 0
  Do
    Set a = 1
    Set light = On
  Else if light = On and a = 0
  Do
    Set light = Off
  Set a = 0

```
where **a** is user variable initially set to 0.
In this example not only Else executes but also (if light = On AND a = 0) executes despite the 'a' was set to 1 in previous statement.
Checked on [Google Developers Blockly demo](https://blockly-demo.appspot.com/static/demos/interpreter/step-execution.html) and there everything works correctly.

**Comment by flatsiedatsie** [comment]
I think the person who integrated Blockly into Domoticz isn't active anymore, which is why it gets little love.

**Comment by motejowi** [comment]
Thank you.
This is one of the top threads on Domoticz forum (Blockly examples), worth fix.

**Comment by gizmocuz** [comment]
@flatsiedatsie thats not quite true.. did a fair bit of work here... most times (if not all) you can rewrite the blockly so it does work

**Comment by motejowi** [comment]
Hello
So, it won't be fixed?
Regards M

**Comment by gizmocuz** [comment]
What will not be merged ? Where is the pull request to review ?
Did you review the current code ?

**Comment by csipeter** [comment]
In version 3.8153 Blocky else-if is buggy this is the fact. I hope in next stable version will be replaced, because current else-if structure is useless in 3.8153 (looks always true)

**Comment by gizmocuz** [comment]
@csipeter , this is an open source project made by people in their free time.
If you want something fixed (and i have seen (and closed) your other/same issue) you have to debug/patch the code yourself (which should not be that hard to do)
Another option is to go to lua/dzVents if something is not working out with blockly
