### ISSUE TITLE
Domoticz logs "Real" IP rather than "X-Forwarded-For" IP

### ISSUE THREAD

**Issue by briped** [domoticz/domoticz#1809]
Using latest beta 3.856 (no updates available).

Having Domoticz behind a reverse proxy shows all IPs in the log coming from the reverse proxy (normal behaviour). If X-Forwarded-For header is present, this should preferable also be present in the log.

This to achieve proper Fail2Ban integration.

**Comment by alcor93** [comment]
Actually the X-Forwarded-For and X-Real-IP fields are used only to check if the connection is comming from local network in the function AreWeInLocalNetwork. The proposal could be to do the same thing in the Cmd_LoginCheck function used to check the authentification and which is taking currently the basic remote ip field.

**Comment by NewFolk** [comment]
Same to me. 
Hope for the fix.

**Comment by matmuilwijk** [comment]
I had the same problem with another piece of software on my server. I wrote a small script that logged all redirects to the 'Login Failed' page to the auth-log, and let fail2ban filter from there. 

Tried copy-pasting it, and adjusting it for Domoticz, but havent succeeded yet. (Spend a whole 3 minutes on it though). I'll let you know when I've got it working. :)

**Comment by briped** [comment]
My workaround for now is a custom fail2ban filter and jail config:

https://gist.github.com/briped/acd91d0a1a20ca198c6c3e0daa458b82

It's in no way perfect. First regex is the URL for any login attempt when using HTML loginform, which will also be triggered (once) for successful logins. The second regex is when failed login from API (tested with IFTTT) (401).

**Comment by gizmocuz** [comment]
Could you try version 8442, i think it should work now

**Comment by gizmocuz** [comment]
No feedback and probably solved.

**Comment by briped** [comment]
Sorry for the lack of feedback. Since I've implemented a workaround, I haven't gotten around to following up on it. Will check and get back.

**Comment by briped** [comment]
It doesn't look like the issue is fixed, or I'm not doing something right. I've looked over the settings to see if there's some option, somewhere, which enables logging IP, or reverse proxy supprt, in the domoticz log, but I haven't found it.

The following is taken from the /var/logs/domoticz.log:
https://gist.github.com/briped/feed7cca52e395ccd9031d110092813a

Forgot to add version information...
Version: 3.8631
Build Hash: 8b89f7f3
Compile Date: 2017-10-24 09:30:28
dzVents Version: 2.3.0

**Comment by gizmocuz** [comment]
```
Oct 29 14:35:26 Phoenix domoticz[3541]: domoticz: PROXY: timeout occurred, reconnecting
Oct 29 14:35:26 Phoenix domoticz[3541]: 2017-10-29 14:35:26.435  Error: PROXY: timeout occurred, reconnecting
Oct 29 14:35:26 Phoenix domoticz: PROXY: timeout occurred, reconnecting
Oct 29 14:35:26 Phoenix domoticz[3541]: domoticz: PROXY: Connect failed, reconnecting: Operation canceled
Oct 29 14:35:26 Phoenix domoticz[3541]: 2017-10-29 14:35:26.435  Error: PROXY: Connect failed, reconnecting: Operation canceled
Oct 29 14:35:26 Phoenix domoticz: PROXY: Connect failed, reconnecting: Operation canceled
Oct 29 14:43:42 Phoenix domoticz[3541]: domoticz: Failed login attempt from ___REVERSE_PROXY_IP___ for '___VALID_USERNAME___' !
Oct 29 14:43:42 Phoenix domoticz[3541]: 2017-10-29 14:43:42.008  Error: Failed login attempt from ___REVERSE_PROXY_IP___ for '___VALID_USERNAME___' !
Oct 29 14:43:42 Phoenix domoticz: Failed login attempt from ___REVERSE_PROXY_IP___ for '___VALID_USERNAME___' !
```
I am not sure what i see here... ___REVERSE_PROXY_IP___ and ___VALID_USERNAME___
whats the value of ___REVERSE_PROXY_IP___ ?

**Comment by briped** [comment]
Sorry...
___REVERSE_PROXY_IP___ is just a search and replace of the internal IP of my reverse proxy, which I'm seeing in the domoticz.log. I'd expect to see the public IP as forwarded by the reverse proxy, either instead of or in addition to the actual source IP (which, as I mentioned, is the reverse proxy IP).

___INVALID_USERNAME___ and ___VALID_USERNAME___ are just search and replace for the valid username which I attempted to login with, using an invalid password (to trigger wrong password), and also an invalid username, in order to have logs of both types.

One caveat here is that the rerverse proxy and domoticz are actually installed on the same host, so the domoticz IP and the reverse proxy internal IP is actually the same, but I don't expect that to make any difference to the behavior?
