### ISSUE TITLE
Temperature Units in JSON

### ISSUE THREAD

**Issue by GreenTentacle** [domoticz/domoticz#1810]
A humble Feature Request:

(Related to my issue here https://github.com/PatchworkBoy/homebridge-edomoticz/issues/106)

It'd be great if in a device's status JSON, there was an element that described if the temperature was in C or F.  Something like `TempScale` or `TempUnits` ?

Alternatively, maybe if Domoticz settings' had a choice for displayed temperature units vs API temperature units ? 

Thanks !

**Comment by gizmocuz** [comment]
The temperature unit is set in the settings. After this it is always C or F ...
Internally all is stored in C, it is only when setting a Setpoint i believe we convert (internally) to the right/final output

**Comment by GreenTentacle** [comment]
Hello !

I get that, but I don't think there's a way to determine what units you're getting the temperature in if you're consuming the JSON (at least the JSON generated from single device status)-- and the JSON output seems to follow the 'display units' setting in Domoticz.

I was thinking of parsing the "data" element In the JSON for the F or C, but figured there might be a better way.  (On my install, for example, I get `"Data" : "22.3 C, 91 %",` when display units are set to C but `"Data" : "72.1 F, 91 %",` when it's set to F.  But if I consume the "Temp" element, I don't have a way of knowing if it's C or F)

**Comment by gizmocuz** [comment]
you know if domoticz is configured as C or F. And from that it will always be C or F and it is not mixed.
So there is no need for this additional field... it will also introduce more data

**Comment by GreenTentacle** [comment]
I see where you are coming from.  I was thinking more about situations where I (or someone writing a piece of software/plugin) _doesn't_ know what `$user`'s display units are set to, and wants to consume the data, via JSON, from Domoticz.

For my personal case, I'm using the edomoticz homebridge plugin to get homekit control of domoticz.  It appears that homebridge wants all temps sent to it in C.  The plugin assumes domoticz is sending it C, and if it gets F (and sends on F to homebridge) some unrealistic temperatures show up in homekit.  

The plugin authors could make a config option (or read a user var from Domoticz) to specify what display units Domoticz is using, and then do appropriate conversion I suppose.  However I thought it'd be more elegant if the user didn't have to specify that-- if Domoticz just told the plugin/consumer via JSON.  Kind of more of a 'zero configuration' sort of idea, from the end user's POV.

If this isn't something you think will happen, we can go ahead and close out the issue and I'll just have to inform the JSON consumer of the units as well.  Thanks for your time and work on Domoticz!

**Comment by gizmocuz** [comment]
You can ask domoticz for the metric system. Please have a look in the web interface how this is done (logging via the developer (network) console

When domoticz is set to Celsius, it should also communicate in Celsius, so edomoticz should work.

But it is best if they query domoticz for the units first.

For example, look at the 'getconfig' json command
