### ISSUE TITLE
v3.8394 broke LUA scripts triggering

### ISSUE THREAD

**Issue by soif** [domoticz/domoticz#1813]
After updating from v3.8390 to v3.8394 (due to commit 74dd223 ?) : 

The (classic) LUA scripts are no longer triggered .
Switching Settings/Others/EventSystem from ON to OFF then ON again , doesn't change anything : While the log says "EventSystem: Started", the LUA (device) scripts are still no longer triggered.

HTH

**Comment by jvandenbroek** [comment]
That shouldn't be the case and the fact you see 'EventSystem: Started' means it is actually started correctly and the mentioned variable is set to true. So most likely something else is causing issues. Are you sure when reverting to v3.8390 it works again? If so, what platform do you run on?

**Comment by soif** [comment]
Reverting to v3.8390 fixed the issue immediately.
I'm running Debian Jessie on a 386 platform.

BTW  the domoticz/scripts/lua folder is a symlink.

**Comment by jvandenbroek** [comment]
Well symlinks are deleted on update, so probably that is the problem ;) You'd better not use symlinks, or make sure you delete the lua folder after update and create the symlink manually.

**Comment by soif** [comment]
No, symlink were not deleted, I have an update script that does exactly what you said : 
- stop domoticz
- git pull Domoticz and OPenZwave, 
- compil both
- **delete the lua folder, then symlink it outside the domoticz folder**
- restart domoticz

My update script has worked fine for at least 50 update in the past, whithout a single issue.

BTW I've double checked the v3.8390 and  v3.8394 Lua folders are correctly symlinked, but the v3.8394 scripts are totally ignored, while the v3.8390 are working fine (as ALL previous versions).....

**Comment by jvandenbroek** [comment]
OK, didn't know you used git and compiled manually, only binary updates remove the lua symlink and replaces it with a folder. Curious to see if it will be fixed for you with this pull request (submitted 6 days ago): https://github.com/domoticz/domoticz/pull/1806

Not many people (if anyone else) seems to be affected by this, otherwise the forums / issue tracker would explode. But maybe in some rare cases the variable is first set to true and later disabled (but it's set to false on object creation, so really no explanation for why this would be out of order..).

You're mentioning symlink specifically, but I suppose just creating a folder and putting a script in there doesn't work as well?

**Comment by soif** [comment]
I've tested your (unmerged) commit, by downloading you modified _mainworker.cpp_ at:
https://github.com/jvandenbroek/domoticz/blob/b2c2ac5708fb1ca1ddc6f68368bc0cc7813218ef/main/mainworker.cpp

Then :
- I stopped Domoticz, 
- git pull v3.8394, 
- replaced mainworker.cpp by your version, 
- recompiled, 
- restarted, 

and......... VOILA 👍   : **LUA scripts are back** !!!

_So v3.8394 + your #1806 patch make LUA scripts to work again (at least for me!)_

Congratulations ! :1st_place_medal:

**Comment by jvandenbroek** [comment]
Great, thanks for testing it out! Funny to see it actually fixes something else than intended. It seems like that object initialization is out of order on some systems, what CPU and OS do you run?

**Comment by soif** [comment]
cat /proc/cpuinfo | grep name
`model name	: Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz`

cat /etc/debian_version 
`8.9`

uname -a
`Linux domo-ct 2.6.32-48-pve #1 SMP Fri Dec 23 10:22:54 CET 2016 x86_64 GNU/Linux`

_(OpenVz container under Proxmox VE 3.4)_


HTH

**Comment by soif** [comment]
@gizmocuz just merged this, which definitively fixes the issue. 

Thank you both 👍 👍 👍
