### ISSUE TITLE
HTTP Push variable %D and %V don't appear to work

### ISSUE THREAD

**Issue by codeaholics** [domoticz/domoticz#1814]
Using head of `development` branch (e9d01f664d901f0e60f156d5e9e99f2b222bd4c1).

Playing with HTTP Push, I have set up one of my devices as type "virtual device" and entered values for "target device/scene id" and "target property", and I expected those values to be substituted in for `%D` and `%V` respectively, given their descriptions. Instead, I get something like `0_1` for `%D` and nothing for `%V`.

The HTTP method is set to `POST` and I'm using these variables in the data section (rather than the URL or headers section). Other variables appear to provide sensible values.

**Comment by sbouchex** [comment]
According to the code : %D = Target Device id, %V : Target Variable

But for virtual device : "Target Variable" is empty (according to the table)
And %D is built based on <TargetDeviceID>_<DelimitedValue>

What would you expect ? We may add new keywords if needed

**Comment by codeaholics** [comment]
When you set up a virtual device, you get the opportunity to give it a "target device" and "target property". It's not clear to me what those are for if not for extracting with the % keywords. I would have expected "%D: Target Device" to give me... the target device. :) I accept it's slightly more of a stretch to expect "%V: Target Variable" to give me the target property. But, as I said, what other purpose do the target device and target property have if not for extracting via keywords to send to the downstream system?

**Comment by sbouchex** [comment]
OK I better understand what you mean. So something like %P for Target property and %V will return Target Device Id ?

**Comment by codeaholics** [comment]
I have no opinion on the technical solution! :D

But I still have to wonder, what are %D and %V useful for right now? And what happens to the information entered into the "target device" and "target property" fields?

**Comment by sbouchex** [comment]
They can be used by the peer service to later usage
