### ISSUE TITLE
RTL_433 Only gets humidity from La Crosse Technology TX141TH-BV2

### ISSUE THREAD

**Issue by GreenTentacle** [domoticz/domoticz#1816]
The La Crosse Technology TX141TH-BV2 is detected by the rtl_433 hardware, the device is created, but it's created as a humidity-only sensor (Should be temp+hum).

If I run RTL_433 standalone, this is the output:

```
 2017-09-18 21:58:39
:	LaCrosse TX141TH-Bv2 sensor
	Sensor ID:	 2e
	Temperature in deg F:	 83.48 F
	Humidity:	 61 %
	Battery:	 OK
	Test?:	 No
```

**Comment by gizmocuz** [comment]
Then i think you need to patch the rtl_433 hardware class so it will be added as a Temp+Hum...

**Comment by GreenTentacle** [comment]
Fixed by this patch to RTL_433: https://github.com/merbanan/rtl_433/commit/e3d2c2aa5e6d9745f45174f2d18d2e5548bc8ce7
