### ISSUE TITLE
Set Kelvin Level in Scene

### ISSUE THREAD

**Issue by lorenzo-deluca** [domoticz/domoticz#1820]
Hello to everyone,
in my new home I've a lot of Milight devices (GU10, e27, stripe, etc..)
On switch menu I can set colour, brightness, and kelvin level (0/25/50/75/100%).
When I set the status of the lights in a scene I can only set it: color, brightness, and tone (only in rgb mode).
It's not possible to set also Kelvin (would be great) ?

Thanks and congratulations for this fantastic project ;)
Keep it up! 

![milight](https://user-images.githubusercontent.com/32000123/30716764-59d7fc6a-9f1b-11e7-89ec-4de08d3be38c.png)

**Comment by poudenes** [comment]
maybe offtopic: The http: line is that a action to change the lamp? Do you get the info from the colorpicker that put into the http line? If so what is the http line. Because i want use my MIPOW bulbs with colorpicker as well but can't let it work.

**Comment by lorenzo-deluca** [comment]
Hello poudenes, maybe I explained wrong.
In LightSwitches menu I can choose everything (rgb colour, kelvin, set on/off http line etc..).
My question is about Scene menu, in this panel i cannot set kelvin level, right?

**Comment by poudenes** [comment]
I can only select a color but when i execute the scene the color won't change at all.
Maybe its a wrong programming in the plugin. 

But thanks for your reply

**Comment by lorenzo-deluca** [comment]
Color works, of course if the relay that powers the lamp is also piloted, it is necessary to wait before sending the color change command.

But it's off topic.

**Comment by lorenzo-deluca** [comment]
No way??

**Comment by oxje** [comment]
I also have this problem, it is related to the new-ish Milight RGBW+CCT bulbs where you can control the temperature. 

The switch itself does indeed support a 0-25-50-75-100 kelvin setting, but scenes and also the dashboard do not.

**Comment by lorenzo-deluca** [comment]
we hope this improvement will be implemented :+1:

**Comment by poudenes** [comment]
What i did was create Dummy Switches for : Kelvin, Sat. Brightness.
Use a python script to send value to milight bulbs and this link put in value of dummy switches.

Now i can use those dummy switches in Scenes to create right settings

**Comment by lorenzo-deluca** [comment]
Hi poudenes, Yes, it's a good workaround but in this way I have to create a dummy switch for each MiLight bulb.
For now I will do in this way, but it would not be bad to have the chance in the future to do so directly from the scene panel as well.

**Comment by poudenes** [comment]
I have same.. Have 16 MiLights in my house... So was a day work for me to add them all.
I read in the Limitless.cpp of DOmoticz the follow line:

// Commands
// V6
// Todo: Kelvin slider & WW/CW type

So maybe they will implement this all

**Comment by lorenzo-deluca** [comment]
I think management is already done because in LightSwitches you can select kelvin level or night light mode..
The only improvement would be to add the Kelvin attribute in the construction of a scene.

**Comment by poudenes** [comment]
True and +1 for that. Better to have a slider to select the level for Kelvin.

**Comment by gizmocuz** [comment]
implemented with #2078
