### ISSUE TITLE
Add support for calculating & plotting heat index?

### ISSUE THREAD

**Issue by mzealey** [domoticz/domoticz#1822]
I've got a number of DHT22's around, but in my location humidity fluctuates a lot as well as temperature. I would like to display graphs and have temperature tabs show the [Heat Index](https://en.wikipedia.org/wiki/Heat_index#Formula) which is a combination of the two and then be able to use this in various trigger scripts.

**Comment by gizmocuz** [comment]
You would like to see this as a line chart ? so inside the current charts ?
You could now already take the data from the database, and try this with excel... how will this look ?
Maybe you can post a screenshot... is it worth it ?

Another way, you can make a script, poll the temp+hum, do your calculations and update a dummy (virtual) temp sensor... do a poll every minute

**Comment by gizmocuz** [comment]
No feedback, closing issue, please use our forum
