### ISSUE TITLE
Feature request: Ikea Tradfri support

### ISSUE THREAD

**Issue by matmuilwijk** [domoticz/domoticz#1824]
There's a ton of work done already to make this possible, but implementing it is yet a pain. Native support would be amazing!

https://github.com/ggravlingen/pytradfri
https://github.com/moroen/IKEA-Tradfri-plugin

**Comment by moroen** [comment]
Native support would be great, and I'm planning to look into it. But since an official API is on the horizon, I'w waiting for the release of the API first.

**Comment by daljian** [comment]
Are there any news to share for this issue?

Is the API from IKEA available?

**Comment by gizmocuz** [comment]
It is not native supported, but you can use it via plugins:

https://www.domoticz.com/wiki/Ikea_Tradfri_Gateway

**Comment by pipiche38** [comment]
You can also purchase a Zigate and all ikea bulbes will be manage via Zigate and the plugin. In addition you’ll have the possibility to put xiaomi sensors
