### ISSUE TITLE
RTL_433 in domoticz: can't update or remove hardare

### ISSUE THREAD

**Issue by nmaster2042** [domoticz/domoticz#1826]
Domoticz version V3.8441
Arch: X86_64
OS: Ubuntu 17.04

Hi,

I tried the rtl_433 integration in domoticz and I discovered some small glitches using it.

1) When I add a rtl433 hardware in domoticz, I can't disable or change hardware name or rtl_433 parameter string because when I click on the update button after selecting the hardware, nothing happens. And I get nothing in the logs.

2) I can't delete the rtl433 hardware in domoticz: when I click on the delete button after selecting my hardware, I get the confirmation message box, clicking OK does nothing for 15 seconds and I get a red prompt "Problem deleting hardware" and domoticz crashes (see attached logs).

[rtl_433 domoticz crash.log](https://github.com/domoticz/domoticz/files/1329282/rtl_433.domoticz.crash.log)

I actualy can't remove the hardware even when I restart domoticz.

**Comment by gizmocuz** [comment]
There have been made some recent changes to this hardware class. Is this still the case?
(Sorry, i do not own this hardware to test)

**Comment by nmaster2042** [comment]
Hi  gizmocuz,

I just upgraded my domoticz test machine to the lastest beta V3.8627
Build Hash: 93492f29
Build Date: 2017-10-22 13:31:11

And the 2 issues remain the same.

**Comment by gizmocuz** [comment]
Tested it here under windows (dont have the hardware) but i can update/delete it without problems
could you install version 86xx + ? maybe it has been solved recently

**Comment by nmaster2042** [comment]
Yes I have 86xx, it doesn't change anything on my ubuntu PC.

I don't have any Windows machine to test sorry.

**Comment by gizmocuz** [comment]
found the issue.. there was no update handler.
But there is another issue, and that is that fgets is blocking, it does not return when there is no data read.
So it will wait endlessly for data before it can stop (and restart) the hardware class.
Need to have a good look at this...

**Comment by gizmocuz** [comment]
I made some changes, could you test the new beta version (8631) i also changed it to a non-blocking mode under posix systems (non-windows).
If everything is OK, it should still work and receive data, if not, tell me and i revert the blocking part

**Comment by gizmocuz** [comment]
A quick test on an odroid machine shows it's working ok

**Comment by nmaster2042** [comment]
I'll test on my domoticz and I'll confirm you ASAP.

**Comment by nmaster2042** [comment]
I updated to 8633, created a new rtl_433 hardware. 
It starts the hardware but I can't update the hardware name.
I got no reply from domoticz, nothing in logs.
Webserver accepts connections but browser stays blocked "waiting for reply".
And the same for wget in cmd line.
I have to kill and restart domoticz to get acces to the web interface.

**Comment by gizmocuz** [comment]
No issues here, i can disable/enable them
Maybe you should send a 433Mhz command ?

**Comment by nmaster2042** [comment]
It actually receive 433 Mhz signals from my temp/hum sensors and it creates and updates devices in domoticz, so I don't understand from where the issue comes from.

I'll do some more tests with this release.

I have rtl_433 lastest github version compiled and running fine in stand alone from command line.

I have an odroid too, I'll test on it instead of the X86_64 PC at the end of the week.

**Comment by gizmocuz** [comment]
i also compiled rtl_433 with the latest git version, on a odroid and do not have any issue

**Comment by nmaster2042** [comment]
Hi,

I compiled the Beta 8650, and now the issues about RTL433 are gone.

**Comment by gizmocuz** [comment]
Great, thanks for the feedback!
