### ISSUE TITLE
Https / ssl no longer working out of the box

### ISSUE THREAD

**Issue by Nostras** [domoticz/domoticz#1827]
Running on a pi3, raspbian stretch 9.1 kernel 4.9.51-v7+.
Libssl version taken from jessie and jessie-backports as no version is made available for stretch.

Using latest stable and beta (V3.8153, V.38441).
Asked for solution here first, but got workaround.
https://www.domoticz.com/forum/viewtopic.php?f=6&t=19571
But so far only reply is a workaround and not a solution ( and thus I consider it a bug ).
Chrome returns ERR_EMPTY_RESPONSE, firefox says "The connection was reset".

If you need more info, hit me.

**Comment by gizmocuz** [comment]
I consider this a disaster and spend many (many) hours on debugging the problem.
The issue seems related to libcurl and openssl 1.1
on these systems building against openssl 1.0.2l seems to work. therefor you need to apt-get install libssl1.0-dev (may 25th 2017, so NOT outdated)

**Comment by gizmocuz** [comment]
It should work again... can you try the latest beta ?
