### ISSUE TITLE
No Default Timer plan

### ISSUE THREAD

**Issue by cyclops1982** [domoticz/domoticz#1830]
Hi,

I've just installed Domoticz from source. All compiled and works well, but i've noticed that there is no Timer Plan present after the install.

I can still set timers and such, but when i then add a timer plan, those timers disappear.
If ia add a timer and use that in the settings, then my earlier set timers disaappear. It would be better if by default there is a timer plan that is also being used. So that a user can just 'add' timer plans to it, if needed.

**Comment by gizmocuz** [comment]
Setup->More options -> plans -> timer plans
it is using by default the 'default' timer plan

**Comment by cyclops1982** [comment]
What i'm saying is that on my install, there was NO plan at all.

**Comment by gizmocuz** [comment]
There is always an internal plan

**Comment by gizmocuz** [comment]
(0)

**Comment by cyclops1982** [comment]
Ok. it would be better if it shows that internal plan and that this is the default one selected, so you don't lose your timers when you add a plan....
