### ISSUE TITLE
Domoticz received fatal signal 6 - Evohome(?)

### ISSUE THREAD

**Issue by peliilep** [domoticz/domoticz#1835]
Currently using v 3.8450 (but this issue is since the last stable version)
I've got issues that after a service stop and start,  Domoticz can't be accessed via the web interface.
Every night at 2:00 a bash script stops the service, makes a backup of the db and some other important files and starts the service after about 20 seconds. Almost every night I get the following log:

```
2017-09-30 02:00:21.430  
2017-09-30 02:00:21.506  subtype           = Interface Response
Sequence nbr      = 2
response on cmnd  = Get Status
Receiver type     = 868.95MHz
Firmware version  = 1006
Firmware type     = ?
Hardware version  = 2.0
Undec             off
X10               disabled
ARC               disabled
AC                disabled
HomeEasy EU       disabled
Meiantech/Atlantic disabled
Oregon Scientific disabled
ATI/Cartelectronic disabled
Visonic           enabled
Mertik            disabled
AD                disabled
Hideki            disabled
La Crosse         disabled
FS20/Legrand      disabled
ProGuard          disabled
BlindsT0          disabled
BlindsT1          disabled
AE                disabled
RUBiCSON          disabled
FineOffset        disabled
Lighting4         disabled
Conrad RSL        disabled
ByronSX           disabled
IMAGINTRONIX      disabled
KEELOQ            disabled
Home Confort      disabled
2017-09-30 02:00:21.723  
2017-09-30 02:00:21.724  subtype           = Interface Response
Sequence nbr      = 2
response on cmnd  = Get Status
Transceiver type  = 433.92MHz
Firmware version  = 1019
Firmware type     = Ext2
Hardware version  = 1.3
Undec             off
X10               enabled
ARC               enabled
AC                enabled
HomeEasy EU       enabled
Meiantech/Atlantic disabled
Oregon Scientific disabled
ATI/Cartelectronic disabled
Visonic           disabled
Mertik            disabled
AD                enabled
Hideki            disabled
La Crosse         disabled
FS20/Legrand      disabled
ProGuard          disabled
BlindsT0          disabled
BlindsT1          disabled
AE                disabled
RUBiCSON          disabled
FineOffset        disabled
Lighting4         enabled
Conrad RSL        disabled
ByronSX           disabled
IMAGINTRONIX      disabled
KEELOQ            disabled
Home Confort      enabled
2017-09-30 02:00:21.878  (YouLess LS-120) P1 Smart Meter (Energy)
2017-09-30 02:00:21.883  (YouLess LS-120) P1 Smart Meter (Gas)
2017-09-30 02:00:22.346  MySensors: Gateway Ready...
2017-09-30 02:00:22.421  MySensors: Gateway Version: 2.1.0
2017-09-30 02:00:29.855  (EvoHome API) connect to Evohome server
2017-09-30 02:00:30.228  (Weather service) Temp + Humidity + Baro (Weather)
2017-09-30 02:00:30.233  (Weather service) Wind (Wind)
2017-09-30 02:00:30.239  EventSystem: Event triggered: Heating-Override_7
2017-09-30 02:00:30.239  (Weather service) UV (UV)
2017-09-30 02:00:30.241  EventSystem: Fetching url...
2017-09-30 02:00:30.244  (Weather service) Rain (Neerslag)
2017-09-30 02:00:30.255  (Weather service) General/Visibility (Visibility)
2017-09-30 02:00:30.478  Incoming connection from: 127.0.0.1
2017-09-30 02:00:30.480  (EvoHome API) connect to Evohome server
2017-09-30 02:00:31.593  Error: Domoticz received fatal signal 6 !...
2017-09-30 02:00:31.596  Error:   /home/pi/domoticz/domoticz() [0x1f1be2]
2017-09-30 02:00:31.596  Error:   /home/pi/domoticz/domoticz(_Z14signal_handleri+0x3d) [0x1f1c76]
2017-09-30 02:00:31.596  Error:   /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer_v2+0) [0x76ab9180]
2017-09-30 02:00:31.596  Error:   /lib/arm-linux-gnueabihf/libc.so.6(gsignal+0x38) [0x76ab7f70]
Domoticz received fatal signal 6

```
I suspect that the EvoHome API is related to this issue. Can anyone help to solve this? How to assess this and how to solve?

A manual restart of the service (sudo service domotica stop / start) solves the issue (most of the times).

**Comment by peliilep** [comment]
I did some additional manual stop/starts and in 1 out of 8 times I can reproduce the issue:

> pi@MSL-DOM-01:/tmp/log$ sudo service domoticz stop
pi@MSL-DOM-01:/tmp/log$ sudo service domoticz start
pi@MSL-DOM-01:/tmp/log$ sudo service domoticz status
 domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh)
   Active: **active (exited)** since Sat 2017-09-30 04:42:39 CEST; 15s ago
  Process: 12594 ExecStop=/etc/init.d/domoticz.sh stop (code=exited, status=0/SUCCESS)
  Process: 12633 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)

> Sep 30 04:42:51 MSL-DOM-01 domoticz[12642]: (EvoHome API) connect to Evohome...r
Sep 30 04:42:52 MSL-DOM-01 domoticz[12642]: (Weather service) Temp + Humidit...)
Sep 30 04:42:52 MSL-DOM-01 domoticz[12642]: (Weather service) Wind (Wind)
Sep 30 04:42:52 MSL-DOM-01 domoticz[12642]: EventSystem: Event triggered: He...7
Sep 30 04:42:52 MSL-DOM-01 domoticz[12642]: EventSystem: Fetching url...
Sep 30 04:42:52 MSL-DOM-01 domoticz[12642]: (Weather service) UV (UV)
Sep 30 04:42:52 MSL-DOM-01 domoticz[12642]: (Weather service) General/Visibi...)
Sep 30 04:42:52 MSL-DOM-01 domoticz[12642]: Incoming connection from: 127.0.0.1
Sep 30 04:42:52 MSL-DOM-01 domoticz[12642]: (EvoHome API) connect to Evohome...r
Sep 30 04:42:53 MSL-DOM-01 domoticz[12642]: Domoticz received fatal signal 6....
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by gordonb3** [comment]
I'm puzzled by the fact that `Evohome API` appears to exist in two instances. Can't spare the time at this moment, but I'm sure that is not the case in my own setup. I actually do run an older version though because starting with the last stable my machine goes into stall after four and a half days running, but I do have the most recent Evohome incorporated into it.

**Comment by gordonb3** [comment]
Still unsure about the double log entry, but I did find an issue related to processing schedule information from a DHW device. I currently have a pull request open that should fix this.

**Comment by gordonb3** [comment]
Could you try current beta?

**Comment by gordonb3** [comment]
Considering that there is no more feedback, may we assume that this issue is solved?

**Comment by gizmocuz** [comment]
yes i think so... it's been way over a month... that is why i try to transfer as much users to our forum as possible and keep github for code problems
