### ISSUE TITLE
[Request] - Icons for Push button

### ISSUE THREAD

**Issue by J-C-P** [domoticz/domoticz#1837]
Hello from Belgium,

This would be very nice if we could select an icon for a push button.
For instance, dummy switch for Volume up and down could use volume icon.

Anyway, the ability to add custom icon and use them with device other than switch or dimmer could be a great plus :-)

Thanks for the great work!

**Comment by ghost** [comment]
Do you know what would be cool, to be able to select an icon from the entire Font Awesome range to use as a icon. Perhaps in a dropdown list, or by entering the class ie. `play` for `fa fa-play` ?

Then you could really customise them with different sizes (`play fa-2x` for `fa fa-play fa-2x`) etc.

**Comment by Eorciu** [comment]
For "push button" workaround,  try use normal switch "On/Off" with "Off delay" = 1 
exp. 
![image](https://user-images.githubusercontent.com/29353438/33244877-69b6597a-d2ff-11e7-91dd-68a576c61367.png)

**Comment by gizmocuz** [comment]
@leecollings, people won't like those icons as well... it will always be a matter of taste..

**Comment by ghost** [comment]
@gizmocuz but surely giving people the option to create their own icons, from the huge library of Font Awesome will be much more popular than limiting them to selecting ones in a dropdown list.

Not to mention, using fonts to display icons is much lighter than using images... I personally think it's a fantastic flexibility feature, that should at least be polled?

If I can figure out how to get it working in Domoticz, I'll be happy to create a pull request to save you doing any work?

**Comment by Olifant1990** [comment]
+1 for custom icons from font-awesome!

**Comment by waltervl** [comment]
Custom Push Button Icon can be set. Custom Icons can be created from every source, see wiki https://www.domoticz.com/wiki/Custom_icons_for_webinterface
