### ISSUE TITLE
Support for MySensors FOTA Update

### ISSUE THREAD

**Issue by LemarinelNet** [domoticz/domoticz#1839]
Hi There,

I'd like to help implementing firmware over-the-air update for mysensors update.

The internals are quite simple, but I need to add some UI elements, and so I'll need help for this !

We can discuss the points if you want...

**Comment by gizmocuz** [comment]
Can't you use MYSController for this ?

**Comment by LemarinelNet** [comment]
The fact is that I'd like to use domoticz for all my home automation : I have all my lights that are bound to mySensors, and using MYSController for OTA would mean stop first domoticz (to free the serial port), then open MYSController, (which may eventually not know the devices ID, because they were set by domoticz, and device only present themself on boot). While MYSController is opened, all the scripts set on mySensors in domoticz would be offline. Then, when I'll have finished the update I'll have to start again domoticz.
This scenario could work, but it will be complex to use.

**Comment by bilbolodz** [comment]
Build ethernet gateway and you can connect Domoticz and MYSController in the same time.
