### ISSUE TITLE
domoticz.globalData not working in DzVents

### ISSUE THREAD

**Issue by jsiegmund** [domoticz/domoticz#1840]
I've been trying to get global variables to work. Either the documentation is not up to par, I'm doing something wrong or it just really doesn't work. 

I've created a new global_data.lua file inside of the scripts folder: 

```
return {
        helpers = {},
        globalData = {
            pirDisabled = { initial = false }
        }
    }
```

In my DzVents scripts I'm trying to access this variable as follows:

```
if (domoticz.globalData.pirDisabled == true) then
    return
end
```

From what I can find with logging, the variable is always nil. I've also tried setting it in script and reading it later, that also didn't work. I'm not doing anything fancy yet, just trying to get this basic thing to work. I'm running v3.8153, when needed I'll upgrade to the latest beta but I'd rather run a stable build.

**Comment by dannybloe** [comment]
You are almost there. You defined the data wrongly in global_data. It should not be **globalData** but **data**:

```
return {
        helpers = {},
        data = {
            pirDisabled = { initial = false }
        }
    }
```

**Comment by jsiegmund** [comment]
Sorry, late reply. This is kinda confusing @dannybloe. So now I've changed my global_data to: 

```
return {
    helpers = {},
    data = {
        pirDisabled = { initial = false }
    }
}
```

And wrote a simple test script like this: 

```
return {
	on = {
        timer = {
            'every minute'
        }
    },
	execute = function(domoticz, device)
		domoticz.log('Checking pir disabled: ' .. domoticz.globalData.pirDisabled)
	end
}
```

But when the script runs it says: 

```
2017-11-06 21:48:00.308 Error: dzVents: Error: An error occured when calling event handler TST_PIRDISABLED
2017-11-06 21:48:00.308 Error: dzVents: Error: ...cz/scripts/dzVents/generated_scripts/TST_PIRDISABLED.lua:8: attempt to concatenate field 'pirDisabled' (a nil value)
```

**Comment by jsiegmund** [comment]
Ah, I might have found something... it seems to matter where you place the scripts. I was editing the scripts in Domoticz which places them inside the generated_scripts folder. I now moved a couple of scripts into the scripts folder instead and now the variables seem to work. Going to do a little bit more research but I'm guessing thats the trick. Documentation can certainly use some improvement on this part.

**Comment by dannybloe** [comment]
I don't understand. The generated_scripts folder shouldn't be touched directly as it is entirely managed by Domoticz.

**Comment by dannybloe** [comment]
Can you please follow-up on this?
