### ISSUE TITLE
Checkboxes custom charts are invisible

### ISSUE THREAD

**Issue by dannybloe** [domoticz/domoticz#1841]
Caches are cleared, checked in Chrome (Version 61.0.3163.100 (Official Build) (64-bit)).
Seems to be that the checkboxes are hidden due to wrong css rules. See screenshots. 

![screen shot 2017-10-03 at 07 47 38](https://user-images.githubusercontent.com/2369994/31111602-701bcd24-a80f-11e7-9bd9-4c4c93e0a410.png)

![screen shot 2017-10-03 at 07 47 50](https://user-images.githubusercontent.com/2369994/31111605-76130314-a80f-11e7-8d35-ffad3482a613.png)

I don't have time right now to dive into this but I guess someone forgot to make exceptions for the new checkbox styling in this page.

**Comment by gizmocuz** [comment]
Fixed in upcoming beta.. this chart can have some work ;)... i like the graphana way better
