### ISSUE TITLE
Please create a 1.0 release

### ISSUE THREAD

**Issue by zi0r** [domoticz/domoticz#185]
For package maintainers, having tagged versions drastically makes our lives easier.  Please tag a release as 1.0 so that we can add this to the FreeBSD ports tree.

**Comment by gizmocuz** [comment]
must it be 1.0 ? or can it be 2.xxxx ?

**Comment by zi0r** [comment]
It can be any number you'd like. :)

**Comment by gizmocuz** [comment]
It's done ;)
