### ISSUE TITLE
Feature request: IIO Daemon support

### ISSUE THREAD

**Issue by stintel** [domoticz/domoticz#1853]
Please consider implementing support for the [IIO Daemon](https://wiki.analog.com/resources/tools-software/linux-software/libiio_internals#the_network_backend_and_iio_daemon)

This would allow to read values from sensors supported by the [Linux Industrial I/O subsystem](https://wiki.analog.com/software/linux/docs/iio/iio). This would be a nice alternative to MySensors.

**Comment by saper-2** [comment]
Now linux kernel (Raspberry Pi linux kernel 4.19.42) has built-in support for many sensors (on i2c and spi) including most popular: dht11, bme280 or bmp280.
See how it's look like 😄 

(I have hooked and configured bmp085)
![obraz](https://user-images.githubusercontent.com/8533673/62253604-bca88c00-b3f6-11e9-9dd1-53f05943713d.png)

**Comment by stintel** [comment]
Accessing sysfs should be relatively easy to implement, but just for clarification, I meant accessing the XML backend. This would make it possible to read sensors on remote devices running iiod.
