### ISSUE TITLE
Dimmer switch can't be edit

### ISSUE THREAD

**Issue by morilm** [domoticz/domoticz#1854]
Hi.

This issue is happening after creating a manual switch with "selector switch" type and "dimmer" as t

Switch is created, but as "selector" instead of dimmer.

After editing the switch and change the type to "dimmer" no further editing is possible.  
Switch/dimmer works ok.  It's on the edit on the dashboard

Thanks for the support.
Miguel

<img width="327" alt="captura de pantalla 2017-10-08 a las 11 58 47" src="https://user-images.githubusercontent.com/25224160/31315884-e656774e-ac21-11e7-8e7c-6dc8746063f3.png">
<img width="439" alt="captura de pantalla 2017-10-08 a las 12 09 34" src="https://user-images.githubusercontent.com/25224160/31315885-e656fcdc-ac21-11e7-8a50-48b70bf894c1.png">
<img width="427" alt="captura de pantalla 2017-10-08 a las 12 09 56" src="https://user-images.githubusercontent.com/25224160/31315886-e658b130-ac21-11e7-8bca-86db2a6b7bd9.png">
<img width="493" alt="captura de pantalla 2017-10-08 a las 12 10 09" src="https://user-images.githubusercontent.com/25224160/31315887-e65dc08a-ac21-11e7-8f30-89c717370068.png">

**Comment by morilm** [comment]
Just found the error on JavaScript:

LightsController.js:1539 Uncaught TypeError: Cannot read property 'split' of undefined
    at EditLightDevice (LightsController.js:1539)
    at HTMLAnchorElement.onclick (VM547 LightSwitches:1)
EditLightDevice @ LightsController.js:1539
onclick @ VM551 LightSwitches:1

Seems it's similar or same issue as #884

**Comment by gizmocuz** [comment]
Do you experience this when you create the selector switch from the 'dummy' hardware create button ?

**Comment by morilm** [comment]
Yes.. same behaviour.  As soon as you change the switch type from selector to dimmer you can't edit anymore.   Dimmer works fine, it's only the edit button on the dashboard

**Comment by gizmocuz** [comment]
Okey, but did you not need to create a dimmer switch instead of a selector switch ?
(Sorry, i do not use selector switches, and have no idea what they are for)

**Comment by morilm** [comment]
There is no dimmer switch.  Only selector switch and normal switch.  Issue only happens with the change from selector to dimmer, not if the change is from normal switch to dimmer...

**Comment by gizmocuz** [comment]
Yes that is what I meant

**Comment by gizmocuz** [comment]
you can not change the type to or from a selector switch
