### ISSUE TITLE
my.domoticz Id is not detected and changed after disk cloning

### ISSUE THREAD

**Issue by JRB202** [domoticz/domoticz#1855]
after cloning a linux disk containing a well working domoticz installation already connected with my.domoticz.com 
the cloned instance is keeking the same My Domoticz ID as the source
when it should be reinitialized based on a change of hardware like MAC address.

How can I force reinit of my domoticz ID (the instance ID) not the API key ?

**Comment by JRB202** [comment]
Any solution or workaround ?

**Comment by gizmocuz** [comment]
No, thats how the unique id is created
