### ISSUE TITLE
Telegram Notification layout

### ISSUE THREAD

**Issue by HoekieN** [domoticz/domoticz#1868]
Screenshot: https://www.domoticz.com/forum/download/file.php?id=13069

Using beta Version: 3.8590 and the layout for the telegram api seems a bit messy and also the option to turn it on/off is missing.

Clearing the cache did not solve the problem, checkt with IE, Chrome and Firefox.

**Comment by chatainsim** [comment]
This is because text is missing from www/i18n/domoticz-XX.json.gz
I've asked to add it in pull request #1857 
Regarding the layout, I've made a new pull request #1876 to fix it.

**Comment by HoekieN** [comment]
Alright thanks.

**Comment by chatainsim** [comment]
Merge has benen done, can you udate and check again ?

Thanks

**Comment by HoekieN** [comment]
i have updated to version: 3.8600 but it still looks the same for me.
Updated again, now to Version: 3.8611 Build Hash: 3f2afa3
It now looks like this: https://s1.postimg.org/1iawhoa77j/Knipselw.png
Cleared the cache and tried with Chrome, Firefox and Edge.

**Comment by gizmocuz** [comment]
Made a small patch, will be corrected in next beta version

**Comment by HoekieN** [comment]
Thanks it looks good now.
