### ISSUE TITLE
Winddelen: Connection error

### ISSUE THREAD

**Issue by Xorfor** [domoticz/domoticz#1869]
Since 12-oct-2017 retrieving values from Winddelen gives errors:

2017-10-13 20:25:12.266 Error: Winddelen: Error connecting to: http://backend.windcentrale.nl/windcentrale/productie_121.txt 
2017-10-13 20:25:12.599 Error: Winddelen: Error connecting to: http://backend.windcentrale.nl/windcentrale/productie_1.txt 
2017-10-13 20:25:22.328 Error: Winddelen: Error connecting to: http://backend.windcentrale.nl/windcentrale/productie_121.txt 
2017-10-13 20:25:22.661 Error: Winddelen: Error connecting to: http://backend.windcentrale.nl/windcentrale/productie_1.txt 
2017-10-13 20:25:32.390 Error: Winddelen: Error connecting to: http://backend.windcentrale.nl/windcentrale/productie_121.txt 
2017-10-13 20:25:32.721 Error: Winddelen: Error connecting to: http://backend.windcentrale.nl/windcentrale/productie_1.txt

**Comment by dartheide** [comment]
URL is changed. to https://backend.windcentrale.nl/windcentrale/productie?id=111
Line 90 from winddelen.cpp has to change from sprintf(szURL,"http://backend.windcentrale.nl/windcentrale/productie_%d.txt", m_usMillID);
to sprintf(szURL,"http://backend.windcentrale.nl/windcentrale/productie?id=%d", m_usMillID);

**Comment by Dylantje** [comment]
mmm

Is this the solution for Domoticz to?
When is this in the last Beta to find?? [ can some one make this fix please to domoticz beta? ]

Or where can i replace the changed line??

**Comment by Eternity-again** [comment]
I browsed my Syno directories hoping to find winddelen.cpp but couldn't find it...

**Comment by trandbert37** [comment]
I try to do this fix but it doesn't work for me

**Comment by Dylantje** [comment]
Is there perhaps someone  that know who build the winddelen hardware..

Perhaps he can update the hardware..

**Comment by gizmocuz** [comment]
The problem is that the old URL gives a 403 (Forbidden) and the new URL never returns as it keeps pushing new data

**Comment by Dylantje** [comment]
My app is functioning ok...
Perhaps there is a other feed..

I will try contact with windcentrale for a live feed...

**Comment by gizmocuz** [comment]
Your app probably has been updated...
We need a URL that returns immediately, and not keeps the line open... maybe a GET parameter (or POST header) would be great (if it is not already there)

**Comment by gizmocuz** [comment]
Solved.. will work again in the next beta version
![image](https://user-images.githubusercontent.com/2265299/31852283-5c4b69a2-b675-11e7-8d92-ffcbca3b08f1.png)

**Comment by Xorfor** [comment]
Just updated to 3.8614 and it works fine now. Thnx!!!

**Comment by Dylantje** [comment]
oke great work!!!
Thanks!
Gizmocuz

**Comment by Dylantje** [comment]
mm It still works :-)
Perhaps for the masters 👍 
I get a answer:
`Dit is de betere manier:

https://backend.windcentrale.nl/-gxvt=1

of mag ook zijn: http://backend.windcentrale.nl/-gxvt=1


Dit gebruikt de app om productie van molenid 1 op te halen.

Als je die opent krijg je elke vijf seconde een regel in beeld (in Firefox en Chrome werkt dat in elk geval), dat ziet er dan zo uit:

Z 5,1383,140,59,63,19.6,0,3202478,6625.0833333333,Z 4,1508505329,76780
Z 5,1431,145,61,65,19.4,0,3202480,6625.0833333333,Z 4,1508505334,76780
Z 5,1372,139,58,62,19.4,0,3202482,6625.0833333333,Z 4,1508505339,76780
Z 5,1256,127,53,57,19.1,0,3202484,6625.0833333333,Z 4,1508505344,76780
Z 5,1210,123,52,57,19.3,0,3202485,6625.0833333333,Z 4,1508505349,76780
Z 5,1341,136,57,62,19.4,0,3202487,6625.0833333333,Z 4,1508505354,76780
Z 6,1392,141,59,63,19.4,0,3202489,6625.0833333333,Z 4,1508505359,76780
Z 5,1408,143,60,64,19.6,0,3202491,6625.0833333333,Z 4,1508505363,76780
Z 5,1644,166,70,71,19.7,0,3202494,6625.0833333333,Z 4,1508505369,76780
Z 5,1644,166,70,71,19.7,0,3202494,6625.0833333333,Z 4,1508505369,76780
Z 6,1717,174,73,73,19.8,0,3202496,6625.0833333333,Z 4,1508505375,76780
Z 6,1698,172,72,72,19.9,0,3202502,6625.0833333333,Z 4,1508505385,76780
Z 5,1586,161,67,70,19.3,0,3202504,6625.0833333333,Z 4,1508505390,76780
Z 5,1214,123,52,57,19.1,0,3202505,6625.0833333333,Z 4,1508505395,76780
Z 5,1440,146,61,65,19.7,0,3202507,6625.0833333333,Z 4,1508505400,76780
Z 5,1477,150,63,66,19.4,0,3202509,6625.0833333333,Z 4,1508505405,76780
Z 6,1362,138,58,62,19.4,0,3202511,6625.0833333333,Z 4,1508505409,76780
etc etc.

Hij hangt na 5 minuten de lijn vanzelf op, om te voorkomen dat er runaway clients zijn (sommige Android telefoons openden om vage redenen meerdere verbindingen die nooit stoppen).

Die code gxvt in de url is een timestamp waaraan het serverproces kan zien wanneer deze link verstrekt is, en op basis waarvan hij kan oordelen of een link recent uitgegeven is. 

Klein beetje technische achtergrond nog: dit is een server die één response geeft, waarin regel voor regel data doorkomt. Een basic http client voldoet dan meestal niet, omdat die vaak pas resultaat geeft als het laden van de pagina voltooid is - wat hier dus 5 minuten zou duren.`

Perhaps this can help when there is something wrong in the future :-)

**Comment by Eternity-again** [comment]
Was able to install a beta Domoticz v6.1_3.0.8614-7 on my Synology and can confirm it is working again. Thanks!

**Comment by gizmocuz** [comment]
Hi Dylantje,

Yes that is the issue we have, we are a basic http client , so this does not work, we need an URL that returns immediately with 1 result line (and close the connection)

So the way i made it, it i will close the connection after i receive one line... so now we have a more advanced client ;)

**Comment by Eternity-again** [comment]
The problem seems to be back

Error: Winddelen: Error connecting to: http://backend.windcentrale.nl/windcentrale/productie?id=121
