### ISSUE TITLE
JSON output does not include a value for LUX sensors

### ISSUE THREAD

**Issue by dechamps** [domoticz/domoticz#1870]
Domoticz V3.8153

When using the JSON API to get information about my LUX (illuminance) sensors, I get the following response: https://gist.github.com/dechamps/6ae4cbd8d864a0e3e813c0a62af6da8e

The problem is, the JSON object doesn't directly provide the raw lux value (76 in this example) of the sensor. The only way to read it is to parse the "Data" field and extract the number ("76 Lux"). This is awkward and inconsistent with other sensors like Temp, Humidity and UVI, which do include dedicated fields for the sensor value.

**Comment by gizmocuz** [comment]
a lot of sensors use the data field this way. The raw values are in nvalue/svalue and would have to be brought out if you want them. But that also means for energy sensors you could end up with 6 separated values in the svalue field, and you still would need to parse it.
What are you trying to do with the '76' ? display it ? then 76 Lux would be better?

**Comment by dechamps** [comment]
Well, in the case of a "Temperature & Humidity" sensor, the value is in two fields in the JSON device output ("temp" and "humidity"), both on the same device. Which makes a lot of sense. I don't know about energy sensors, but presumably the same approach could be used there: there would be 6 fields, one per metric that the sensor exports.

It would be ideal if the same approach could be used consistently for all sensor types. Currently certain types of sensors (such as temperature, humidity, level) follow this approach, while others don't, and that's a bit inconsistent and confusing.

What I'm doing with the lux value is that I feed it to a [Prometheus][] timeseries storage system for further analysis. Prometheus deals with numbers, not strings - I can't just give it "76 lux", I need to extract the number first. Which makes sense, anyway - I can only do calculations and statistics on numbers, not strings.

  [Prometheus]: https://prometheus.io/

**Comment by gizmocuz** [comment]
okey, so you call the json output with some script, sure you can split the data field then ?
If you want you can make a patch that adds the 'nvalue' and 'svalue' fields of the device, then you have everything.
Sure an energy sensor with 6 values have to be handled differently then a single value
Another option is to add a 'label' for the value in the json output like 'volt', 'watt', 'lux' etc.. so a user interface can stitch them together easly
