### ISSUE TITLE
LastUpdate field in JSON output is ambiguous

### ISSUE THREAD

**Issue by dechamps** [domoticz/domoticz#1871]
Domoticz V3.8153

I'm using the Domoticz JSON interface to export sensor data to a sophisticated monitoring system. For this use case I care a great deal about the last updated time information (`LastUpdate` field) being accurate and reliable, because I require precise information about how stale the value is.

Right now this field is encoded as a date/time string expressed in local time, *without* any timezone suffix, for example: `2017-10-14 15:10:58`.

The use of local time without any timezone offset information makes this difficult to work with. It is impossible to reliably convert this back to an unambiguous timestamp (e.g. a Unix timestamp), because:

- The client might not know which timezone the Domoticz server is using. It is forced to guess or assume that the client and server are configured with the same local timezone, which is brittle and error-prone.

- Most importantly, without the timezone offset the date/time is ambiguous around daylight saving time transitions. For example, when a UK-based Domoticz server returns `2017-10-29 01:30:00`, it is *impossible* to know what actual time that is, because [that local time occurs twice][ukdst]!

Ideally, the `LastUpdate` field should follow the full RFC 3339 format, including timezone offset information. For example, the following date/time string is unambiguous: `2017-10-29 01:30:00+01:00`

Another solution would be to add a `LastUpdateUTC` field, or a `LastUpdateTimestamp` field (which could contain a Unix timestamp in seconds), both of which are not timezone-based and therefore unambiguous.

[ukdst]: https://www.timeanddate.com/time/change/uk/london?year=2017

**Comment by dannybloe** [comment]
I would add a lastUpdateUTC field otherwise many things will break.
Other than that I think it is a good idea to add this.

**Comment by gizmocuz** [comment]
It is specified in local time, as even when you work remotely from a different timezone (which i do quite a lot!) i would like to know that on 13:15 the light went on... yes , localtime from the domoticz system
the lastupdate time is used in the web interface in  the widget
And should also only be used to plot the time

**Comment by dechamps** [comment]
@gizmocuz Local time is only appropriate for a specific set of use cases, though. It's appropriate for the use case that you describe, but not for my use case where I want to know how "fresh" the device data is. I'm not advocating that we drop the local time field (which would indeed break many things, anyway), I'm just suggesting that we should also have a field that can be used to determine the actual absolute time when the update happened, so that more use cases can be appropriately covered.

**Comment by gizmocuz** [comment]
This time value is for the last update in the user interface.
If you want to do other things with it, you have already a script that pulls this json, then you could add your own timezone info to this

**Comment by dechamps** [comment]
It's impossible add timezone information after the fact, because the time is ambiguous, especially around DST transitions. The JSON output simply does not provide enough information to determine the actual absolute time that the LastUpdate field refers to. For example, `2017-10-29 01:30:00` is ambiguous in the UK.

**Comment by gizmocuz** [comment]
i understand, but else the whole gui needs to be changed, and the conversion from a time_t object to a readable format has to be done on the client side... costing some possible cpu cycles.
Again, this field is used for the domoticz web interface..

**Comment by gizmocuz** [comment]
Maybe you want to add a new json call to request the native database fields from the device ?

**Comment by dechamps** [comment]
> i understand, but else the whole gui needs to be changed, and the conversion from a time_t object to a readable format has to be done on the client side... costing some possible cpu cycles.
Again, this field is used for the domoticz web interface..

Again, I'm not advocating for changing the existing field (which would break current JSON clients). I'm advocating for adding a new one.

> Maybe you want to add a new json call to request the native database fields from the device ?

Well, if I were to do that I might as well read the DB directly… I'm using the JSON interface because I was under the impression that was a public API with some stability guarantees meant for consumption by external clients such as mine. I refrained from going directly to the DB because the database schema is technically an implementation detail of domoticz that is not supposed to be exposed to the outside. (Also, IIRC the last update time is stored in local time in the DB itself, which means going directly to the DB would not solve my problem.)

**Comment by gizmocuz** [comment]
That's correct. Then maybe add the timezone info as a separate field so you can combine them in your script.
You can not access the database directly if domoticz is running

**Comment by gizmocuz** [comment]
On second hand, we should not do this as it results in unneeded traffic.
In the getconfig call, you could for instance provide such an information

Regarding your script/needed info, i suggest to:
- add your own html file with a javascript that concat the timezone
- make a php script (domoticz can act as php server if you specify a php_cgi_path as startup parameter) and do the magic in here

**Comment by dechamps** [comment]
> You can not access the database directly if domoticz is running

Why not? I've done this before as an experiment and it seemed to work. SQLite is designed for [concurrent access from multiple processes][concur].

Regarding your other suggestions, I'm not sure how they would solve my problem. As far as I understand it, part of the problem is that the data I need simply isn't there in the database; it would need to be persisted in some way (perhaps in a new column). For example, if I'm in the UK and the only data that is persisted in the database is `2017-10-29 01:30:00`, then there is no way to get the actual absolute time back, because the only way to disambiguate that time is with the timezone offset (either +00:00 or +01:00 depending on whether the event occurred before or after the DST transition). If the offset is not persisted, then it's impossible to recover the actual timestamp. Adding the timezone offset at the time of query will not work, because what matters is the offset at the time the last update *occurred*, not what the current local time offset is as the time I'm querying for it.

  [concur]: https://sqlite.org/faq.html#q5

**Comment by gizmocuz** [comment]
You will experience some busy/locked behavior when you do this, and i do not advice it.
Anyways, sorry, can't help you here, and i do not want to introduce another field in the json as this is a waste of bandwidth
Again, try to work around your issue with a script, and for those two moments per year where you would expect a problem, try to program around them
