### ISSUE TITLE
A few problem with Selector Switch

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#1872]
Domoticz 3.8590 on RPi (chrome)

I have many problems with selectors.
Easy reproduction one of them:
1) Creating a new dummy switch
2) edit 
3) change to selector
4) add one level
5) save
Selector don't save. On board I see switch, after click I see selector but without level which i wrote.  

Maybe this is only bug in JS ?
I have many errors like:
1)
Uncaught TypeError: Cannot read property 'join' of undefined
    at EditLightDevice (LightsController.js:1750)
    at HTMLAnchorElement.onclick (VM2857 LightSwitches:1)
EditLightDevice @ LightsController.js:1750
onclick @ VM2857 LightSwitches:1
LightsController.js:1423 
2)
Uncaught TypeError: Cannot read property 'split' of undefined
    at AddSelectorAction (LightsController.js:1423)
    at AddSelectorLevel (LightsController.js:1312)
    at HTMLAnchorElement.onclick (VM2857 LightSwitches:1)

**Comment by gizmocuz** [comment]
Please use the forum. You should also create the selector switch from the dummy hardware setup page/button
