### ISSUE TITLE
Text sensor on Floorplan - bug

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#1880]
Domoticz 3.8590 on RPi
Bug on floorplan with Text device
1) Add Text virtual device
2) add this device to floorplan
3) show floorplan
4) click this device
5) whole floorplan hidden and nothing shows/happens.

Fantom

**Comment by gizmocuz** [comment]
Thanks for reporting, fixed in beta 8718

**Comment by szczukot** [comment]
On 3.8718 still wrong (cache clear)

**Comment by gizmocuz** [comment]
You should not be able to click on the text sensor anymore in the floorplan... that was the idea..

**Comment by szczukot** [comment]
But i stiill can click on icon.

**Comment by gizmocuz** [comment]
Make some changes, try beta 8722

**Comment by szczukot** [comment]
Yes - now is not clickable (this is workaround but ... OK)
Thanks

**Comment by gizmocuz** [comment]
You want it clickable ? What do you want to show ? The text changes log ?
If so, please make a pull request with a patch, this is one line of code to change
