### ISSUE TITLE
Bug : irrelevant Monthly/Yearly Temperature & humidity statistic due inconsistent sensor value

### ISSUE THREAD

**Issue by nepheris** [domoticz/domoticz#1886]
Sometimes the Temperature and humidity sensor send values that are plotted in Domoticz as " O°C - Humidity 0% . Most probably incomplete/mis received or corrupted radio tag from the sensor.

As far these 0-0 data are integrated in X Min, Max, and Overage temperature calculation by domoticz (if you don't delete it manually on the week graph) : monthly and yearly temperature reports are less relevant due these inconsistent values.

Is it possible : 
-  to filter the data to exclude the plotting of 0°C & 0% humidity  sensor radio tag ( impossible that both are 0 in the real life) ?
- to create a script to clean up the temperature-humidity sensor data-base of these "0°C-0% humidity", this would be great to recuperate the sensor history ? We could execute it weekly/ or on demand  to clean up the data-base as an option this would do the job.

As far I don't know coding all idea that would make it easier to solve this issue are welcome, please shoot  ! 

Thanks for you help

**Comment by gizmocuz** [comment]
Indeed it should not be 0 humidity !...
What hardware is receiving this ? i think the hardware manufacturer should check this (if possible) , Domoticz is just storing the received values

**Comment by nepheris** [comment]
@gizmocuz 

Hi, 

Indeed, this should be solved at hardware level but unfortunately I does not work like this. 

I have [smartware t°& humidity sensors 868Mhz](http://www.homewizard.fr/smartwares-thermo-hygrometer.html) that are connected to a HomeWizard Box.  If I look to the HomeWizard box interface I don't see these (0-0) values .... so I don't know if this is linked to the sensor and data are cleaned by the homewizard code , of if this is linked to the [homewizard box API](http://wiki.td-er.nl/index.php?title=Homewizard) that create these bugs ? 

Then I use the [github.com/domoticz-homewizard - plugin ](https://github.com/rvdvoorde/domoticz-homewizard/) plugin to get these data from the  homewizard API.  I have made a script to do it manually and I had to had add in the code a filter to excludes (0°C-0% humidity value). Now I am using the Gitub script because it enable to collect all data live from my homewizard box that was not the case before with my homemade script. Unfortunately, I can only do basic script, I have no PHP- Python- Javascript coding skills .... 

Can you help me : 
-  to create a script to clean out domoticz data base of this irrelevant value. I think this could make sense because it could be use for many other sensor in domoticz by adjusting the script parameters .

- to see with development team to update the Temperature and humidity domoticz sensor code to skip plotting of irrelevant values. 

Thanks for you  comment.

**Comment by gizmocuz** [comment]
a)
what do you mean to clean out ? you mean in the database? you could use 'SQLite Expert Personal Edition' for this and write a query

b)
This should not be done in the domoticz code. So you might ask this to the guys from the domoticz-homewizard-plugin
