### ISSUE TITLE
RGBW green and red mixed up

### ISSUE THREAD

**Issue by tlpeter** [domoticz/domoticz#1888]
I noticed that my Fibaro RGBW (correctly connected) give red when green is selected and green when red is selected. Also when i mix these colours then it is reversed.
I did see on the forum that this was fixed for RFlink already but apparantly not for zwave.

I am running Beta 3.8630 on a RPI 3

**Comment by gizmocuz** [comment]
then you connected it wrong... have plenty of them

**Comment by gizmocuz** [comment]
This is in the domoticz web interface?

**Comment by tlpeter** [comment]
Yes, in the webinterface.
I am sure it is connected well as it was connected to Milight before and worked in the past.
I am not sure if this still works Ok but i can try that.
Do you have the Fibaro FGRGBWM-441?

**Comment by stuiow** [comment]
I've got one of those RGBW fibaro switches and when wiring it up, noted the coloured wires don't related to the colour they output.
I had a post on the domoticz forum about this when i had issues.

**Comment by tlpeter** [comment]
With Milight the wires where spot on. There was also a post about RFlink where red and green where mixed up which is solved by someone.

**Comment by gizmocuz** [comment]
I have the FIBARO System FGRGBWM441 RGBW Controller
We send a color command to the RGB(W) nodes, this can not go wrong

**Comment by tlpeter** [comment]
You are the one that knows it. i just wanted to be sure that if i swap the wires that it is permanent.

**Comment by gizmocuz** [comment]
I would say try another HA controller to verify first....
Internally we send a zwave colour command to the node which has a fixed RGB layout, so it can not be mixed
Or someone has changed the internal code to convert from a Hue value to RGB..
I would test with another HA controller first...

**Comment by tlpeter** [comment]
I will try a different HA controller. I have a spare zwave stick lying around.
I will let you know hopefully this week.

**Comment by mosjonathan999** [comment]
i have this ledstrip controller as wel and all the colors are spot on. 
so i think it is in the connection of the wire's to the controller

**Comment by tlpeter** [comment]
I cannot seem to get another HA controller working very well and to be honest it costs too much time at the moment. If there are other people where it works like it should than i must believe that.
I will investigate the ledstrip, i bought a new and different one.
Thanks.

**Comment by gizmocuz** [comment]
Did you try connecting it differently ? (swap red/green)

**Comment by tlpeter** [comment]
Yes i just did and then it works fine.

**Comment by stuiow** [comment]
Yeah that's the colours I had to swap.
Common sense doesn't apply to led wiring it seems!

**Comment by gizmocuz** [comment]
No worries great it works now

**Comment by xztraz** [comment]
I've noticed cheap rgbw strips often have R and G mixed up on the strip itself. start there if similar probs

**Comment by gizmocuz** [comment]
Best to rewire so it works correctly
