### ISSUE TITLE
Add strings to language file [Suggestion]

### ISSUE THREAD

**Issue by DewGew** [domoticz/domoticz#1889]
There is some missing strings in the language files: 
`"About": "About",
"MyDomoticzSettings": "MyDomoticz Settings",
"SharedDomoticzAllowed": "Shared Domoticz Allowed",
"AppsAllowed": "Apps Allowed",`

**Comment by gizmocuz** [comment]
Thank you for reporting, i added the translations in our translation system... now they need to be implemented by all translators ;)
