### ISSUE TITLE
SQL update bug from approx. v3.8631

### ISSUE THREAD

**Issue by digdug3** [domoticz/domoticz#1893]
Since approximately version v3.8631, SQL update queries are not encoded/escaped anymore.
See: [`Forum`](http://www.domoticz.com/forum/viewtopic.php?f=6&t=20039)

**Comment by gizmocuz** [comment]
Of course you checked the history of the SQLHelper.cpp file to back this up ?
Please point me to the change that caused this

https://github.com/domoticz/domoticz/commits/development/main/SQLHelper.cpp

**Comment by digdug3** [comment]
Of course I didn't 👎 , I just noticed it. I did not do any beta updates for a long time, the stable did not have this problem. Will try to find it and point it to you. Or at least what beta introduced it.

**Comment by gizmocuz** [comment]
Okey, point i was making is that you should not use version numbers in your topic if you can not back this up.
Made a lot of changes in the latest beta versions so i got scared...

Looking in the code we use %q in our SQL queries (except on two places that another user introduced but has nothing to do with this and i will correct them)
I would have expected that %q would solve this problem... but i guess not?

https://sqlite.org/c3ref/mprintf.html

I will update SQLite from 3.20 to 3.21, but i do not see any history related to this error

I will try to replicate this issue

**Comment by digdug3** [comment]
~~The bug came after 13-10-2017 to narrow it down. The beta from 13-10-2017 worked. (Or at least didn't show me the error)~~ Edit: gordonb3 found is was already in v3.899 (20-09-2017)

You can replicate it by creating a dummy text and use ', " or % in the text. Biggest problem is you can create your own queries now.

**Comment by gizmocuz** [comment]
How do you update the text sensor ?

**Comment by digdug3** [comment]
Using a lua script:
`
msg = "It's cold outside (" .. sWeatherTemp .. "\194\176C), set weekend day-heating to: " .. DayTemp .. "\194\176C"`
`
commandArray['UpdateDevice'] = "187|0|" .. msg
`

**Comment by gordonb3** [comment]
Just ran a quick test on my own installation, replacing the original sqlite version from that release (3.8000) with the 3.20 version. No issues loading a string containing `'` or `%` from LUA, so that's not the cause.

**Comment by digdug3** [comment]
To make it more complicated: it looks like the query is stored:
This was the error:
`2017-10-25 18:14:00.249 Error: SQL Query("UPDATE DeviceStatus SET nValue='0',sValue='DFS: It's cold outside (14.2°C), set night-heating to: 17°C',LastUpdate='2017-10-25 18:14:00' WHERE (ID = '187')") : near "s": syntax error`
But after stopping and starting the service (so reloading the database), the data is there when you look at the logs for this dummy text:
`2017-10-25 18:14:00 | DFS: It's cold outside (14.2°C), set night-heating to: 17°C`
So somehow the data is stored.

**Comment by gordonb3** [comment]
I can't replicate that. It may be due to how you trigger the event though. I believe that if the event is set to run in the past when the event system is started it will execute at that time - which may follow a different procedure and thus succeed.

In any case the problem has existed for some time now. It is already in version 3.8390 (09/09). It is not in version 3.8315 (08/17).

**Comment by digdug3** [comment]
Then you can ignore my comment before, will edit it

**Comment by gordonb3** [comment]
Gotcha!

Problem starts with commit 9894cf0 which replaces the original update query by a literal string that cannot be processed for the proper character substitutions required by SQL. This commit entered mainline on 09/05 as version 3.8378 (f96438f).

**Comment by digdug3** [comment]
Great!

**Comment by gizmocuz** [comment]
Wha yes i see.. the one that wrote the patch in 'CEventSystem::UpdateDevice' should have done that differently.... this is not using %q in the sql query...
Thanks for spotting, i will look at that piece of code

**Comment by gizmocuz** [comment]
Tested, and fixed... beta will be available within the hour... code commited...
Hope there are no other places where it's done like before

**Comment by gordonb3** [comment]
Looks good to me

**Comment by gizmocuz** [comment]
Thanks for testing... looks much better now ;)

**Comment by digdug3** [comment]
Tested and can confirm it works, thanks for all the hard work!
