### ISSUE TITLE
Need to rename off level for virtual selector

### ISSUE THREAD

**Issue by sbaloo** [domoticz/domoticz#1895]
Hi
will it be possible to add the rename of off level for virtual selector?

Even if the 0 level is hide the icon don't move from on to off.

Or if level off is hidden, will it be possible to say that the off level if the 10. By doing this the icon will change.

You can choose :-) thanks

**Comment by gizmocuz** [comment]
Please discuss this on the forum as there is no reaction from the developers.
Maybe we need a discussion about this first
