### ISSUE TITLE
Feature request: Home Connect for Siemens Boch appliances

### ISSUE THREAD

**Issue by Nornode** [domoticz/domoticz#1896]
Would be amazing to have all these devices straight into Domoticz without immediate workarounds

As official documentation there are:
https://developer.home-connect.com
API documented here: 
https://developer.home-connect.com/?q=docs/api/general/endpoints_dataencoding

Some chatter on the forums to utilize FHEM as a work around to post MQTT messages:
https://domoticz.com/forum/viewtopic.php?t=16840#p155165

With FHCM - Home Connect git hub page:
https://github.com/sw-home/FHEM-HomeConnect

**Comment by korniza** [comment]
I can share the experience that the fhem is a little bit hard to be setup because of so many software to use. I hope also for a clean domoticz approach.

**Comment by nicolasplanchon** [comment]
Hi there,
Do we have news regarding the support of Home Connect appliances please ?

Best regards,
Nicolas.

**Comment by mario-peters** [comment]
After developing a couple of hours I created the 1.0 version of a Home-Connect plugin for my dishwasher.
More features to come.

See my GitHub project [Domoticz-Home-Connect-Plugin](https://github.com/mario-peters/Domoticz-Home-Connect-Plugin).

**Comment by firelook** [comment]
I have : 
2018-11-15 13:58:01.942 Error: lave_vaisselle hardware (16) thread seems to have ended unexpectedly
2018-11-15 13:58:15.965 Error: lave_vaisselle hardware (16) thread seems to have ended unexpectedly
2018-11-15 13:58:29.989 Error: lave_vaisselle hardware (16) thread seems to have ended unexpectedly
2018-11-15 13:58:44.012 Error: lave_vaisselle hardware (16) thread seems to have ended unexpectedly
any ideas where to look for ?

**Comment by firelook** [comment]
using See my GitHub project Domoticz-Home-Connect-Plugin. => on a SIEMENS SN778D16TE HOME CONNECT

**Comment by waltervl** [comment]
Can be closed, implemented by Python plugin.
