### ISSUE TITLE
GUI update/restart using systemd

### ISSUE THREAD

**Issue by briped** [domoticz/domoticz#1898]
When updating (or attempting to restart) Domoticz using the GUI, it fails, because the last step, the service restart, is never completed on systems using systemd.

Modifying the updaterelease, updatebeta etc. scripts to use systemctl restart domoticz.service doesn't really solve the issue, as the file is overwritten on every update.

Would it be possible to somehow check for systemd vs. sysvinit script and call the proper restart script, so that updating via GUI will work without having to manually restarting the service via SSH?

Version: 3.8631
Build Hash: 8b89f7f3
Compile Date: 2017-10-24 09:30:28
dzVents Version: 2.3.0

**Comment by gizmocuz** [comment]
You should have copied the script file and not linked to the script file.
This way, the 'actual' script file is not overwritten

Its not a work around, but in your copied/modified script you could call the systemd commands when calling start/stop/status

`systemctl start domoticz.service`

Else yes, if you could detect what is used then maybe you can make a patch in the update scripts

**Comment by briped** [comment]
Hmm, I haven't linked or copied any scripts. I've created the systemd script from the install instuctions, modified it according to my system etc.

But let me see if I understand your answer correctly...

Create the SysVInit script. Modify the start/stop/restart etc. sections of the SysVInit script to call its systemd equivilant?

If I am understanding it correctly, don't the SysVInit script require a pid file to check whether the started process is running or not?

**Comment by gizmocuz** [comment]
On what hardware/OS are you running ? If on raspberry, please use default Raspbian
Else i would suggest to copy 'updatebeta' to 'updatesystem' and make the needed changes and use the new script

**Comment by briped** [comment]
Intel NUC. Lubuntu 17.04.

And the domoticz gui update feature will the trigger updatesystem, and not overwrite on updates?

**Comment by gizmocuz** [comment]
No it will not, but updating via bash is 100x faster then the gui anyway...
I also have a Intel NUC's with ubuntu/debian, and there i have no issues

**Comment by briped** [comment]
It's not a matter of speed but of convenience. When there's a popup letting my update at the press of a button directly from the browser on either my smartphone or the desktop, it's not convenient to have to SSH to the server and manually initiate the service restart.

I'll look at the suggestion of copying updatebeta to updatesystem and see if that works, and keeps across an update. Otherwise I guess I'll try to google some more and hack together something that works, so it's actually possible to update domoticz simply by pressing the update prompt that pops up when a new update is available.

**Comment by chrisverhoef** [comment]
I'm facing the same issue with armbian 5.13.x. Ok, it's the experimental armbian 64-bit version for orangepi zero 2+ but I think the update_domoticz script could be made a little bit smarter for using the right init process tool (service or systemctl). I changed it at my side and now it works well. 
 
FROM

else
  sudo service domoticz.sh stop
  systemctl stop domoticz.service
  echo "please standby... (waiting 15 seconds)"
  sleep 15
  sudo service domoticz.sh start
  systemctl start domoticz.service
fi


TO

else
  if [ `which service` ]; then sudo service domoticz.sh stop
  elif [ `which systemctl` ]; then sudo systemctl stop domoticz.service
  else
        echo "No supported init process management tool like service or systemctl available"
        exit
  fi
  echo "please standby... (waiting 15 seconds)"
  sleep 15
  if [ `which service` ]; then sudo service domoticz.sh start
  elif [ `which systemctl` ]; then sudo systemctl stop domoticz.service
  else
        echo "No supported init process management tool like service or systemctl available"
  fi
fi

Should I make a pull request for this?

**Comment by gizmocuz** [comment]
On my default raspbian install when i execute

`which service`

I do not get any result

but when i issue

`sudo service domoticz status`

i do get result

... i do get result for 

`which systemctl`

but also for

`sudo which service`

**Comment by chrisverhoef** [comment]
I know, but the service command will be deprecated and the systemctl will be the one to use. For now some distro's have both others only have one of them.
In the current script both commands are fired that is not  necessary and actually a strange way in my opinion. So I think it's good to let the script figure out which command to use and only fire one and not two.
The other change is that the systemctl was not using sudo an I think this should be done with sudo, else (at least in my armbian (latest version)) it's asking for a password.

**Comment by gizmocuz** [comment]
Okey, then maybe we should check for the systemctl first ?
Please go ahead with a patch, i think the 'restart_domoticz' script also needs it ?

**Comment by travellingkiwi** [comment]
The proper check would be to verify if systemd is in use or not. If systems is in use, use systemctl. Otherwise use service

i.e. something like

```
if [[ `ps -p1` =~ systemd ]];
then
  sudo systemctl start domoticz.service
else
 sudo service domoticz start
fi
```

Although note that on most systems that run systemd you can still use init scripts anyway. Meaning systemd services aren't (usually) required even if systemd is in use.

**Comment by chrisverhoef** [comment]
@travellingkiwi, your totally right that your code is the proper way to implement. 
I have changed it in a way it's also working in sh (dash) and pushed the code to my fork. Now these two scripts looks more clean but the problem isn't fixed yet.  There is another error around sudo. I think it's a security related one when firing the script from the websever. I will investigate this further.

`Nov 16 19:24:41 localhost domoticz[28690]: sudo: unable to change to root gid: Operation not permitted`
`Nov 16 19:24:41 localhost domoticz[28690]: sudo: unable to initialize policy plugin`

**Comment by briped** [comment]
Sorry to butt in. I might not completely understand what you're doing in your attempt as the solution.

If all you're doing is checking if systemd process is running, then that approach would only work if you ensure  that people are using systemd instead of service. As the documentation is (or was?) it offers both approaches for startup script, so if I chose to use the service approach, while still having other daemons starting using systemd, then I would assume the current if/else approach to fail.

The only surefire way to ensure the suggested if/else to work is if you control the making of the systemd startup script as part of the installation process.

**Comment by chrisverhoef** [comment]
@briped, this if/else is not the solution, but an approach to make the script more reliable and not stopping and starting domoticz twice. Another one is the difference between the service and systemctl call, the first one is with sudo the other one is not using sudo. Although I think these scripts are relying a  on assumptions a lot, I'm currently only looking at these points. 

What the solution is for the error produced by using the update from the web front-end  I don't know for now. I'm just facing some logging which are telling me there are some security violations, which in my opinion is not that strange (Executing scripts which use root privileged fired from the webserver) . Maybe I have some time this weekend to take a look at it or maybe someone else has the clue earlier.

**Comment by gizmocuz** [comment]
@chrisverhoef about the root execution, that is needed by some hardware and can not be avoided easily

**Comment by chrisverhoef** [comment]
@gizmocuz maybe it's an idea to let the process management handled the restart. If we do it this way the user which is running the domoticz service doesn't need sudo (root) rights for the restart. This works for System V, Upstart and systemd.
I have changed the script update_domoticz in a way that it will only kill (send TERM signal) the process for non OSX. Also changed the systemd service script in a way it will always restart and wait for  10 seconds (this one is arbitrary and according the wiki now 1 minute, which is too much while upgrading).

So if you agree this is the right solution then I propose to pull the script update_domoticz and restart_domoticz from my dev fork. Also I want to add the systemd script (like the init.d domoticz.sh) and update the wiki page: [https://www.domoticz.com/wiki/Linux#Starting_Domoticz_automatically_when_the_system_boots]

**Comment by chrisverhoef** [comment]
@briped, as a workaround you can made the changes yourself so you can use the update from the GUI till this issue is solved:
- replace the `update_domoticz` in the scripts directory with the one from my development fork: https://github.com/chrisverhoef/domoticz/tree/development/scripts
- Make it immutable: `chattr +i` (else it will be overwritten by the next update from the GUI)
- Change your systemd script within the `Service` section so it will restart the system service :
 `Restart=always`
 `RestartSec=10`
- Reload the systemd manager configuration: `sudo systemctl daemon-reload`

**Comment by briped** [comment]
Thanks. It looks like your update_domoticz is for MacOS, where I use Ubuntu. It might be that I haven't looked properly. I unfortunately don't have much time until the new year, so I wont be able to look more thoroughly or test at the moment.

**Comment by chrisverhoef** [comment]
@briped, the changes are in the else clause, so especially not for the MacOS but for other Linux systems. I'm running this on Armbian and Fedora. Take you time, there is no need to hurry.

**Comment by gizmocuz** [comment]
Is the PID  in /var/run also deleted with the pkill command? is a normal user allowed to write to /var/run ?

**Comment by travellingkiwi** [comment]
On a R-Pi /var/run is normally 0755 and owned by root.root, so no a normal user can’t write to it. (RHEL/Centos should be the same)

What you can do however is have root create a subdirectory in there that is owned by the application user. That’s how mysql etc do it.

I don’t believe pkill removes anything from /var/run, that’s not a requirement of it. And normally it wouldn’t even look in there either.

H

**Comment by pipiche38** [comment]
BTW, where is the domoticz.service script. Is it expected to be part of the domoticz source code, or is it expected to be part of the Linux distribution package ?

**Comment by gizmocuz** [comment]
@pipiche38 , you are replying to a half year old topic...
There is currently no domoticz.service, there is a startup script for init.d that can be found inside the repo
