### ISSUE TITLE
Setting dimmer level loses On/Off State

### ISSUE THREAD

**Issue by madgeni** [domoticz/domoticz#1902]
When setting dim level of Light/Switch, you lose the opportunity to check the state of the light - For example, it sets Status to  "Set Level: 37 %" - and I lose the ability to check if the light is on or off until another command is issued. 

Is this a bug, or expected behaviour? Thanks!

**Comment by Siewert308SW** [comment]
Not a bug... Dimmer devices can be checked if ON in Lua by:
if otherdevices['Light'] ~= Off then
Meaning that if light isn't OFF then assumed it's ON so you can do a task to shut it down.

**Comment by gizmocuz** [comment]
Is this still the case?

**Comment by Siewert308SW** [comment]
Don't know if it ever was a case, the OP didn't respond to my post.
But Dimmer devices status has always been checked with "~= Off" to see if they are ON.
For me personally no need to change anything as i think it aint a bug.
Have been working/using this methode since the beginning of Domoticz.

**Comment by madgeni** [comment]
No worries - will close, had implemented that != 'On' || !='Off' as a workaround, just hadn't seen it documented :)
