### ISSUE TITLE
Thermostat setpoint negative values

### ISSUE THREAD

**Issue by korniza** [domoticz/domoticz#1907]
I try to control temperature on a fridge but the thermostat setpoint device refuse to change the value when the up/down arrows are pressed. instead it returns  on 0 C.
I suppose most people use it to control heat but what about fridges?

**Comment by gizmocuz** [comment]
Do you change temperatures that frequently for a (your) fridge ? that does not seem quite right to do so ;)
Therefor i am not sure if it would be worth investigating this deeper.
What hardware do you use ?

**Comment by ghost** [comment]
I think some people actually adjust their fridge and freezer between Summer and Winter seasons, I'm not sure why though as I'm sure they are generally meant to be left at a set temperature indefinitely.

Also, I'll ask again.. what hardware do you use to change your fridge temperature!? I've seen some Bosch WiFi enabled ovens and microwaves, perhaps it's the same thing?

**Comment by korniza** [comment]
lucky guess! I have a siemens wifi enabled fridge. The reason I like to change it, I need to put the fridge on vacation mode when we are away for more than 48 hours.

**Comment by gizmocuz** [comment]
If "lots of meat" in fridge and "temperature to low for 48 hours" then "meat is bad"
i think fridges are made to be set on a fixed temperature, but for cleaning you can pull out the plug of course

**Comment by dannybloe** [comment]
wtf is a vacation mode?? 😄  If you are on vacation then what? Make it colder/hotter? And... why can't you use a selector switch for this purpose?

**Comment by ghost** [comment]
Our fridge/freezer has a Vacation mode.

Essentially, it raises the temperature slightly, to take into account the unlikelyness of the doors being opened as frequently as usual, which would cause the fridge to work harder to keep regulating the temperature.

If the fridge knows it won't have to do this for a long period of time, then it can afford to just ease off it's work load a bit.

**Comment by korniza** [comment]
i can say this: if "lots of meat" then "decrease temperature by 2" on freeze. Also when ice cubes running low on a party, how about to put freezer on lower temperature so to get a new pack of ice cubes ready in shorter time?

**Comment by ghost** [comment]
I think there are more problems in the world to be honest!

I'll be honest, I can't see this being implemented at all.

**Comment by gizmocuz** [comment]
Correct... for the moment
