### ISSUE TITLE
MQTT not working for all switches

### ISSUE THREAD

**Issue by jcwlim** [domoticz/domoticz#1909]
Hi,

I notice just my virtual switch have MQTT message publish out.
My other switch add from "Hardware" (e.g. broadlink), when you switch on or off, Domoticz don't publish message. Even temperature also not publishing the message.

**Comment by harryd100** [comment]
MQTT is working just fine on latest Beta V3.8688

**Comment by jcwlim** [comment]
Yes, updated to the latest beta version. I work fine for all switches now.
Thanks.
