### ISSUE TITLE
Slave Device changing Primary Device logical status but not physical status.

### ISSUE THREAD

**Issue by J-C-P** [domoticz/domoticz#1911]
My setup consist of 
- Raspberry 3
- Domoticz Beta branch (current version 3.8692)
- SonOff 4CH Pro (Tasmota firmware 5.9)
- MQTT Mosquitto broker on the Rapberry
(All the previous parts works well together)
- A virtual Switch (as slave device of the Sonoff switch)

When I click the Sonoff switch in Domoticz, the Sonoff physical status is changed.
When I change the Sonoff physical status (via physical button), the Sonoff switch in Domoticz is updated
When I click the virtual switch in Domoticz, the Sonoff switch in Domoticz is changed according to the virtual switch BUT the physical state of the Sonoff is not changed.

I will try to summarize.
Changing a slave device switch also changes the primary switch status but does NOT change the primary switch physical state. (But the primary device switch works nicely to change the primary device physical state).
I tried to create a little video to demonstrate my problem. https://youtu.be/nrp-V4suzAs

What can I do to (help) resolve this problem?

Thanks a lot for all the good work! Very impressive :-)

**Comment by gizmocuz** [comment]
That is correct. A slave device only updates the status internally of the master.
This is also explained in our little manual.

For example you have a wall socket that you can turn on/off, this is the master switch. It does not send the status to domoticz (its a 433Mhz device for instance)
then you have a remote  that you paired with the wall socket.
When you operate the remote, a 433Mhz signal is send that domoticz can pick up, the actual wall socket changes it's state, but domoticz does not know that
So you add the remote as slave on domoticz.
Now when you press 'ON' on the remote, the status in domoticz of the actual wall socket also goes to ON

**Comment by J-C-P** [comment]
Ok. 
If this is by design, the issue can be closed.
I went thru the manual without understanding it the same way.
A last question :
How I am supposed to command a z-wave wall socket with a 423mhz wall switch? They both are known by Domoticz. I thought than was the point of slave/master device :-(

**Comment by gizmocuz** [comment]
you can create a 'group' and learn the 433Mhz switch to this
place your zwave wall socket in this group
