### ISSUE TITLE
Temperature and weather pages are blank

### ISSUE THREAD

**Issue by mosjonathan999** [domoticz/domoticz#1914]
Hello since beta 8692 there are no temperature and weather sensors shown on their pages.

there is also a forum post about it: http://www.domoticz.com/forum/viewtopic.php?f=6&t=20218

**Comment by gizmocuz** [comment]
there will be a new beta version within the hour... could you try this version.
Also please clear your browser cache

**Comment by mosjonathan999** [comment]
build domoticz from source problem is still here in beta 8697

**Comment by gizmocuz** [comment]
I receive updates here...

**Comment by gizmocuz** [comment]
Also clear your browser cache + appcache (two different things)
Looking at the domoticz incoming logs now, and the temperature tab, all in sync

**Comment by mosjonathan999** [comment]
i do also see update's when i look at the dashboard and the temp sensor is a favorite, but when i click on the temperature tab there is not 1 device shown the same for the weather page.
i did a delete off the cache i also went to a laptop that never connected with domoticz and on that machine a have the same problem

**Comment by gizmocuz** [comment]
try running the browser in a private window... do you see anything in the debug console ? (try the chrome browser)

**Comment by gizmocuz** [comment]
The dashboard is using the old update code so that should not be different
I did not not ANY favorite sensors... now i added all my test sensors as favorites, and they still update on the temp+weather tab

**Comment by Siewert308SW** [comment]
Same here, non of the above helps.
Just curious, where is the fix you mention.
As the i don't see a fix for this commit: https://github.com/domoticz/domoticz/commit/15d13dc86548502292289879b913e12fac6250ca

**Comment by mosjonathan999** [comment]
there are only deprecation warnings in developer console also private window does not help

**Comment by mosjonathan999** [comment]
the temperature tab opens a page that only says this: No Temperature sensors found or added in the system...

**Comment by gizmocuz** [comment]
I notice that when i am on the temperature tab and i have my chrome developer console open, that the websocket connection is closing and opening... not all the time
when it does not close, i get updates in the gui... when it closes and re-opens then i seem to miss updates

**Comment by gizmocuz** [comment]
@Siewert308SW ... looks like i do not see the changes in this commit in the actual repo... strange

**Comment by Siewert308SW** [comment]
Oh Dear... ;-)

**Comment by pcca-matrix** [comment]
Same here  websocket opened then close on chrome console dev but no update on gui

**Comment by gizmocuz** [comment]
@Siewert308SW  sorry my mistake... changes are inside

**Comment by gizmocuz** [comment]
@pcca-matrix, do you get updates on the weather tab ?

**Comment by pcca-matrix** [comment]
@gizmocuz  no update on weather tab , but websocket stay open

**Comment by gizmocuz** [comment]
weather tab should be ok
what i noticed (but maybe we should give the original author some time to work on this... but i know that can take quite some time because he as a normal life as well ;)... is that in the temperature controller the RefreshTemps function is called once... and uses the old method... and no timer is triggered after 10 seconds for another update
Maybe this function should not be used... but...
If there are any coders here that want to debug this, please give it a shot, else we should rest this and wait for the original author to have a look at this and users should not upgrade or should use the release version

**Comment by gizmocuz** [comment]
(i think i fixed something... hold on)

**Comment by pcca-matrix** [comment]
@gizmocuz no stress ;)

**Comment by gizmocuz** [comment]
Please try to build with the new code (possible clear browser/appcache)

**Comment by mosjonathan999** [comment]
still not working with new build and browser/appcache clear

**Comment by pcca-matrix** [comment]
still not working

**Comment by gizmocuz** [comment]
working nicely here (win32 visual studio debug), also no websocket open/close

**Comment by gizmocuz** [comment]
updated my life system (arm) ... no temperature and weather sensors... okey... i think i might have to revert some stuff later today

**Comment by pcca-matrix** [comment]
tried on fresh install on WM win32 , still not working

**Comment by gizmocuz** [comment]
Temp. fix in version 8699 (reverting the changes in the temp/weather controller)
Closing this issue now
