### ISSUE TITLE
Plans are added twice

### ISSUE THREAD

**Issue by C-Duv** [domoticz/domoticz#1915]
Using v3.8699 (beta) I have strange behavior: Plans are added twice.
I cleared cache and tested with other browser but the issue remains.

Steps to reproduce
------------------

* Go to `http://domoticz.example.com:8080/#/Roomplan`
* Click the *Add New Plan* button.
* Type any text (say *test*).
* Click the *Add* button.
* (The page refreshes itself)

Expected result
---------------

A new row with the name *test* in the plan list should be present.

Actual result
-------------

**Two** new rows with the name *test* are in the plan list.

Debug data
----------

At first, I thought the browser was sending the request twice but apparently
not: here are the HTTP traffic:

Request:

```
GET /json.htm?type=command&param=addplan&name=test HTTP/1.1
Host: domoticz.example.com:8080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 ...
DNT: 1
Referer: http://domoticz.example.com:8080/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: ****
```

cURL command to send the request:

```Shell
curl 'http://domoticz.example.com:8080/json.htm?type=command&param=addplan&name=test' -H 'Pragma: no-cache' -H 'DNT: 1' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.6,en;q=0.4' -H 'User-Agent: Mozilla/5.0 ...' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: ****' -H 'Connection: keep-alive' -H 'Referer: http://domoticz.example.com:8080/' --compressed
```

Response:

```
{
   "status" : "OK",
   "title" : "AddPlan"
}
```

Versions
--------

* Raspbian 8.0
* Domoticz v3.8699 (beta)

**Comment by gizmocuz** [comment]
We know, there is already a new beta version that solved this (and other things)

**Comment by C-Duv** [comment]
Correct: problem not appearing anymore in v3.8714.

**Comment by gizmocuz** [comment]
Thanks for the feedback!
