### ISSUE TITLE
API security issue

### ISSUE THREAD

**Issue by ebartz** [domoticz/domoticz#1916]
Hi there,

I am currently on this version:

```
Version: 3.8699
Build Hash: 5643ae96
Compile Date: 2017-11-04 16:18:05
dzVents Version: 2.3.0
```

I created a new user called 'api' as type "user" and allowed this user to handle one of my devices. I wanted to make sure that this api user is only able to control specific devices.

If I try it on the web interface everything is fine and if I try to touch a switch that I am not allowed to touch, get an error, as expected.

But if I try the same from the API it seems no matter which devices are allowed for the user, the user can just control everything. 

User settings:

![image](https://user-images.githubusercontent.com/6342767/32417494-ee5e02aa-c25a-11e7-964d-5b6a39cd3fea.png)

Device List:

![image](https://user-images.githubusercontent.com/6342767/32417498-06dd2f5e-c25b-11e7-835a-cb0662fff58f.png)

The ID of the Switch Testsw is 430 in this case. But I can still control 169 for example.

API calls are from external and the IP is not whitelisted.

Results look like this:

![image](https://user-images.githubusercontent.com/6342767/32417535-680d5240-c25b-11e7-8101-1900b0b68ebc.png)

Logs:

```
2017-11-05 18:52:01.297 User: api initiated a switch command (430/Testsw/Off)
2017-11-05 18:52:01.312 User: api initiated a switch command (430/Testsw/Off)
2017-11-05 18:54:43.973 User: api initiated a switch command (430/Testsw/On)
2017-11-05 18:54:43.981 User: api initiated a switch command (430/Testsw/On)
2017-11-05 18:53:27.000 User: api initiated a switch command (169/Licht X/On)
2017-11-05 18:53:27.017 User: api initiated a switch command (169/Licht X/On)
2017-11-05 18:53:53.162 User: api initiated a switch command (169/Licht X/On)
2017-11-05 18:53:53.180 User: api initiated a switch command (169/Licht X/On)
2017-11-05 18:54:46.963 User: api initiated a switch command (169/Licht X/On)
2017-11-05 18:54:46.978 User: api initiated a switch command (169/Licht X/On)
```

I would expect that the user would not be able to control devices over the api which are not allowed for that user.

**Comment by ultrara1n** [comment]
I've stumbled over this yesterday. I've revoked access to one of my switches for one user, but it is still possible for this user to execute the switch. 
Also if you are requesting a list of all light devices e.g. you will get all switches, regardless if you have access to them or not.

**Comment by gizmocuz** [comment]
Hmmm... what are the odds that a authorized user ... knows the domoticz API and can request a list of switches or control them with a curl command ?
I think you should be afraid of other things he/she can do... ;)

I made some changes and a new beta will be available within the Hour (8711)

**Comment by ultrara1n** [comment]
Well, I'm using this in connection with the Controlicz Skill for Alexa, and since there is no 100% security that my credentials "get lost" it would be cool if the attacker could only switch the switches i've allowed him to switch.
Otherwise this whole "Device -> User" is not needed and could be deleted if there is no trustable solution.

**Comment by gizmocuz** [comment]
Why don't you use Alexa with the python script solution ? This runs 100% in house, and also no delay.. (wemo emulation)

**Comment by ultrara1n** [comment]
Do you have a link for that? I only know the Controlicz and ha-bridge solution, which, i find, is way to much work to realise this. You will not get around to open your Domoticz either to Amazon or to Controlicz.
Since i'm using a whitelist to only allow the Controlicz IP to access my remote access, the attack surface is limited, but more security is never a disadvantage.

**Comment by gizmocuz** [comment]
You have to start the myhome.py (and keep it running, and at startup time)

[AmazonEcho.zip](https://github.com/domoticz/domoticz/files/1457435/AmazonEcho.zip)

If you like this approach, maybe you can extend the wiki?

**Comment by gizmocuz** [comment]
Closing this issue

**Comment by ultrara1n** [comment]
Well, this issue might be solved, but now no switch is working anymore 😄 
Trying to switch with **json.htm?type=command&param=switchlight&idx=364&switchcmd=On** results in an error and **json.htm?type=command&param=getlightswitches** displays no switch although there are switches shared to the user:
![pic](https://abload.de/img/unbenanntvmuaz.png)

**Comment by ultrara1n** [comment]
And in the Dashboard the switches are shown, but trying to switch them results in an error too.

**Comment by gizmocuz** [comment]
could be... but try this:
Chrome browser, tab 1, domoticz gui, logged in with this user
tab 2, your json command

i guess this works ?

If you directly call the json function without logging in, or the session cookie it will fail

**Comment by ultrara1n** [comment]
No, this doesn't work. 
I've opened a new icognito window, logged in at my remote installation see all assigned switches:
![Pic1](https://abload.de/img/pic1alzhq.png)

But then i try to switch one of them, and get this error:
![Pic2](https://abload.de/img/pic2s5zid.png)

Trying to see all with JSON:
![Pic3](https://abload.de/img/pic3xqyg9.png)

Trying to switch one with JSON:
![Pic4](https://abload.de/img/pic410xmd.png)

**Comment by gizmocuz** [comment]
i dont think that an incognito browser works as it does not store session cookies ?

Are you able to switch correctly from the web gui ?

If yes, please check the developer console for the network command send as this should be 100% what you wish to send

if it is working in the gui, it should work with the json request as it is the same code, so that means the check works...

**Comment by ultrara1n** [comment]
I've checked the Web GUI (2nd pic)
I've sent you the credentials and the adress via Domoticz Forum, so you can have a look yourself.

**Comment by gizmocuz** [comment]
Credentials are not working...

**Comment by gizmocuz** [comment]
Does this user have any devices assigned to him ?

**Comment by gizmocuz** [comment]
Sorry, found the issue... i had only one user created, and never deleted etc...
Fixed in beta 8721 (available within the hour)
