### ISSUE TITLE
Strings missing in translation files

### ISSUE THREAD

**Issue by sveinki** [domoticz/domoticz#1918]
The final line on the Domoticz dashboard: "Visit the Getting Started page at the Domoticz Wiki" is displayed in English and does not show up in Transifex. I suppose these will be two strings; "Visit the Getting Started page at the" and "Domoticz Wiki" due to the hyperlink.
Can someone make this translatable?

**Comment by gizmocuz** [comment]
Wiki is not a fixed naming like cm,km, Celsius ?

**Comment by gizmocuz** [comment]
First translation is now added to the system.
There was also a HTML format error in the Dashboard.
