### ISSUE TITLE
Bad graph for THB

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#1927]
RPI, latest beta 3.8708
I have
![image](https://user-images.githubusercontent.com/10205661/32540701-c3937900-c46d-11e7-96e3-891616f21015.png)

![image](https://user-images.githubusercontent.com/10205661/32540842-3ced99c0-c46e-11e7-91c8-3f195a7afc5a.png)

and graph for Weather tab (and last icon - barometr)):
![image](https://user-images.githubusercontent.com/10205661/32540807-1cc2643c-c46e-11e7-97c4-f41e490521bd.png)

graph from first icon (temperature):
![image](https://user-images.githubusercontent.com/10205661/32540873-53d7ee42-c46e-11e7-871c-5ff9508a4033.png)

graph from second icon (humidity):
![image](https://user-images.githubusercontent.com/10205661/32540928-791dfb24-c46e-11e7-94d8-18086c446be7.png)

**Comment by gizmocuz** [comment]
So on the normal weather tab and on the dashboard it also goes well or only on the floorplan?

**Comment by gizmocuz** [comment]
Maybe the showtemplog call should also be adjusted there.

**Comment by szczukot** [comment]
This is easy to reproduce. 
Just add open weather map hardware.
Graphs are the same from floorplan and weather tab.
On Temperature tab i see temperature device (with temp and humidity graph)
On Weather tab i see THB (with presure graph)
On Floorplan i see 3 devices: Temperature, Humidity and Presure

**Comment by gizmocuz** [comment]
I asked if this was only on the floorplan, and it seems you do have a problem with only the floorplan
There will be a new beta in an Hour that solves this problem

**Comment by szczukot** [comment]
Beta 3.8712
Added open weather map hardware.
On Temperature tab i see only THB device (with temp and humidity graph)
On Weather tab i see only pressure device (with only pressure graph)
On Floorplan i see 3 devices: 
-Temperature (with temp and humidity graph) 
-Pressure (with pressure graph)
-Humidity (**graph is empty**)

**Comment by gizmocuz** [comment]
You have to use the latest beta version, clear your appcache + browser cache to be sure

**Comment by szczukot** [comment]
I use Beta 3.8712
I don't see the newer version
I run app on the newets browser - clear cache etc.
It's like I wrote above

**Comment by gizmocuz** [comment]
Thats odd because i tested it before committing... i will do it again

**Comment by gizmocuz** [comment]
I am no floorplan expert.. (dont use it) but
When i click on the Temp sign (named THB, which is the correct device from openweathermap)
I see a chart from the Temp + Humidity, thats perfect

i have no idea why there is an additional Humidity sensor on the floorplan... why is that needed?
i think this should not be there? Maybe i should focus on get that removed ?

**Comment by gizmocuz** [comment]
Ohh and that Humidity sensor is displaying a percentage graph... it's calling the wrong graph function?

**Comment by szczukot** [comment]
Yes, It shows empty percentage graph.
This additional humidity sensor on floorplan is not very bad - we see humidity all time. Biut graph not found

**Comment by gizmocuz** [comment]
Okey... fixed in 8713 ... sorry i'm not the author of this code... it needs some word.
I also do not think it should add seperate sensors for temp and humidity...
New beta will be available within 15 minutes

**Comment by szczukot** [comment]
Yes. Now it works. 
Thanks.

**Comment by gizmocuz** [comment]
Thanks for the feedback! Hope the original author reads this and can have a look
