### ISSUE TITLE
No button on Kodi remote for Logitech Media Server

### ISSUE THREAD

**Issue by chatainsim** [domoticz/domoticz#1928]
Hello,

I'm using a LMS for my music.
It's working fine but the remote for slave is empty and I'm not able to click on button.
I have to use LUA script to start or stop music.

![image](https://user-images.githubusercontent.com/1167931/32597631-8ba423f8-c537-11e7-9e9b-e2e593ebce03.png)
I'm currently using v3.8701 but the issue appear on older version too.
Has you can see, there is other people with the same issue: https://www.domoticz.com/forum/viewtopic.php?f=28&t=7866&start=260#p143057

**Comment by mcmellow** [comment]
Same problem with HEOS speakers
![image](https://user-images.githubusercontent.com/15740537/33885694-5f08d04c-df44-11e7-8def-3f888f6fb6b3.png)
When I click on the remote control icon of my HEOS-switch this popup comes up. The switch-type is set to Media Player.

**Comment by chatainsim** [comment]
On Chrome nothing appears but in Firefox button show up when mouse come over.

**Comment by bcrippsy38** [comment]
Anyone know if there's a solution in the works for this issue?

**Comment by funxiun** [comment]
Maybe it is worth mentioning that this problem does not occur in the mobile version.
I just tested the Domoticz interface on my iPhone and iPad in combination with my HEOS speakers and a fully operational remote control appears (with icons).

**Comment by bcrippsy38** [comment]
Depends on the browser for android. Chrome and Firefox don't work. I was able to see the buttons on the beta Samsung browser... Is there a way to change the source using the plugin like amazon music, and then select a station within amazon music?

**Comment by gizmocuz** [comment]
No reaction, closing topic
