### ISSUE TITLE
Add type-of-device to the JSON API

### ISSUE THREAD

**Issue by NanneHuiges** [domoticz/domoticz#193]
Unless I am mistaken, there is no easy way to see what kind of device you are looking at from the 'all' devices request. This means either heuristically 'guess' if it is a switch, temperature-device or something else.

It would be really helpful if this was present in the JSON items per-device. The 'filter' name (e.g. 'light' or 'temp') could be added for instance. This would reduce the amount of calls to get the specific types!

Example (shortened), with added field `DeviceType`

```
   "result" : [
      {
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "Humidity" : 56,
         "Name" : "Cresta channel 1",
         "SubType" : "Cresta, TFA TS34C",
         "Temp" : 18.50,
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",

         "DeviceType": "temp"

      },
      {
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "Image" : "Light",
         "Name" : "Woonkamer - dressoir",
         "SubType" : "Impuls",
         "Type" : "Lighting 1",
         "TypeImg" : "lightbulb",

         "DeviceType": "light"

      },
```

Currently one might abuse the `TypeImg` field, or do some magic with the `Type`, but this is not a pretty method. The image field isn't intended for type-identification, and there doesn't seem to be a clear, exhaustive list for the Type field (the difference between an `lighting 1` and other switches isn't really relevant for instance).

**Comment by gizmocuz** [comment]
You have the [Type] and [SubType] these are the fields to look at
the difference of lighting types is very important

**Comment by NanneHuiges** [comment]
Ah, makes sense, but now I still have the issue of recognising them :)

Is there a list available for the different 'type' fields? I'm afraid to miss device types otherwise . E.G., we have lightings up to `lighting 9`? I know about `Temp + humidity`, are these also separately available? Or in more combinations?

**Comment by gizmocuz** [comment]
there is some source code here in this repository, you might look at the file RFXNames.cpp

**Comment by NanneHuiges** [comment]
Ah, thanks! For future passer-by's:  https://github.com/domoticz/domoticz/blob/master/main/RFXNames.cpp

look for const char *RFX_Type_Desc  (currently line 370, https://github.com/domoticz/domoticz/blob/master/main/RFXNames.cpp#L370 )

**Comment by empierre** [comment]
@NanneHuiges I have a REST gateway between Domoticz and Imperihome, where I already do mappings of this kind, it is either in Perl Dancer and now I am moving to NodeJs Express to have a Synology support.
https://github.com/empierre/MyDomoAtHome/
https://github.com/empierre/MyDomoAtHome/tree/nodejs

I don't know your project, if you need help or want to contribute, feel free !

**Comment by NanneHuiges** [comment]
Hmm, I'm kinda 'stuck' with java, as I'm building for android, but thanks :)
