### ISSUE TITLE
Double percentage sign %% in notification

### ISSUE THREAD

**Issue by harryd100** [domoticz/domoticz#1931]
When a notification is send for percentage, it shows a double percentage sign like:

NUC CPU Percentage is 88.8 %**%** [> 80.0 %**%**]

I think this is caused by:
{ NTYPE_PERCENTAGE, "%%" },

in RFXNames.cpp. Maybe also the case for Humidity?

{ NTYPE_HUMIDITY, "%%" },

Regards, Harry (Sweetpants)

**Comment by harryd100** [comment]
Just created a pull request

**Comment by gizmocuz** [comment]
Thanks, seen the request

https://github.com/domoticz/domoticz/pull/1933

**Comment by gizmocuz** [comment]
tested and merged, thanks!
