### ISSUE TITLE
Security panel hangs after a while (session locking?)

### ISSUE THREAD

**Issue by wslotboom** [domoticz/domoticz#1932]
Hi everybody,

I am trying to use the security panel. At first it works but if the panel stays open for a while the panel becomes unresponsive and even a page refresh won't work. The browser keeps saying that it is waiting for the server. If I open the link in a new browse tab it works again for a few minutes.

After googling for a while it seems like the symptoms of my problem equal session locking problems. Does anyone know how I can solve this? My setup is:

Version: V3.8153
Platform: Ubuntu 16.04LTS
Hardware: Intel Xeon E1220v2

Thanks for your help!

**Comment by DewGew** [comment]
I have the same problem...

**Comment by gizmocuz** [comment]
maybe we could add a timer that sends a noop command (or request the status of the security panel)

**Comment by wslotboom** [comment]
Hi gizmocuz, my temporary solution is to reload the panel every two minutes. From what I understand  with this problem, the session files get locked because the Ajax scripts keeps running. With PHP a solution is to close the session. I have not enough knowledge of the domoticz webserver to know of it is possible. Maybe someone has an idea how to do this?

**Comment by Hexagon** [comment]
Same problem here, this is most certainly a bug in the security panel JavaScript.

I'm currently working on a serious cleanup + basic support for themes. I'll keep you updated.

**Comment by Hexagon** [comment]
Will (hopefully) be fixed by http://domoticz.com/forum/viewtopic.php?f=31&t=21267

**Comment by gizmocuz** [comment]
Seems to be solved, thanks!
