### ISSUE TITLE
Floorplan incorrect icon door sensor

### ISSUE THREAD

**Issue by chatainsim** [domoticz/domoticz#1934]
Hello,
Since a long time I have an issue with the floorplan and my door sensor.
Icon for door stay in open state even if door are closed:
![image](https://user-images.githubusercontent.com/1167931/32650206-32b41084-c5fd-11e7-9651-a2607583954c.png)
In switches tab, icon are correct:
![image](https://user-images.githubusercontent.com/1167931/32650224-44bdecd2-c5fd-11e7-930c-f276d94bf061.png)
I'm currently using v3.8701.

**Comment by harryd100** [comment]
As far as I can see there is no closed door icon for the floorplan

**Comment by chatainsim** [comment]
@harryd100 were are the floorplan's icon ?

**Comment by sweetpants** [comment]
domoticz/www/images

**Comment by gizmocuz** [comment]
i guess it has to be added in the code for the floorplan (domoticzdevices.js)

**Comment by gizmocuz** [comment]
Sorry, found the issue... i had only one user created, and never deleted etc... 
Fixed in beta 8721 (available within the hour)

**Comment by gizmocuz** [comment]
Implemented in beta 8730 (available within 15 minutes)

Note to the author of the floorplan: Please change the code so it depends on the item type/subtype instead of a typeimage !...

**Comment by chatainsim** [comment]
Thanks but now I have the default Domoticz icon instead of door contact. How can I fix this?

**Comment by gizmocuz** [comment]
It seems you miss an icon.. the new sensor type on the flooplan uses door48.png and door48open.png
Both are default in domoticz
Try clearing your browser cache and appcache (two different things)
Try the chrome browser, try it also in private mode

**Comment by chatainsim** [comment]
@gizmocuz thanks it's working!
