### ISSUE TITLE
Bonjour

### ISSUE THREAD

**Issue by jiji45** [domoticz/domoticz#1936]
Bonjour.
Je n'arrive pas a utiliser Zibluerfplayer, il ne reconnait pas les commande chaco ni les transmetteurs de temperature oregon scientific
Merci d'avance de votre soutient.
clt

**Comment by harryd100** [comment]
English please!!

**Comment by chatainsim** [comment]
Here is the translation:
Hello,
I not able to use Zibluerfplayer, it doesn't recognize chacon's command nor Oregon Scientific's temperature sensors.
Thanks in advance for your help.
Regards

**Comment by sweetpants** [comment]
I think you better ask this question on the Domoticz forum http://www.domoticz.com/forum/. Github is only used for code related issues

**Comment by jiji45** [comment]
OK.
Merci pour vos réponses.
Cordialement.
