### ISSUE TITLE
No text wrapping or trimming for Text sensor on Floorplan

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#1937]
3.8718

![image](https://user-images.githubusercontent.com/10205661/32664984-253effb4-c633-11e7-8801-1ddde05b828a.png)

**Comment by gizmocuz** [comment]
please make a pull request with a solution
Also i would not place this sensor at all in a floorplan ?

**Comment by szczukot** [comment]
I'm not front-end developer :(

Another problem with Text device:
![image](https://user-images.githubusercontent.com/10205661/32891090-abecafc8-cad1-11e7-8592-82f9f2fd0ac4.png)

**Comment by gizmocuz** [comment]
Okey, the text sensor is NOT designed for this kind of stuff
