### ISSUE TITLE
TeleinfoBase.cpp

### ISSUE THREAD

**Issue by djskyz** [domoticz/domoticz#1938]
Bonjour, 

Ma trame teleinfo ne contient pas de "PAPP" du coup les informations ne remontent que tout les 5mns, pourriez-vous inclure un autre test à cet endroit afin que les compteurs soient mis à jour plus fréquement.

`void CTeleinfoBase::ProcessTeleinfo(const std::string &name, int rank, Teleinfo &teleinfo)
{`
`if ((teleinfo.pAlertPAPP != teleinfo.PAPP) || (difftime(atime, teleinfo.last) >= 290))
	{`

ADCO 039801185156 F
OPTARIF HC.. <
ISOUSC 30 9
HCHC 199459304 2
HCHP 037304514 .
PTEC HP..  
IINST 007 ^
IMAX 034 F
HHPHC A ,
MOTDETAT 030000 E

**Comment by harryd100** [comment]
English please!!

**Comment by gizmocuz** [comment]
Please use our forum! Or write English
