### ISSUE TITLE
Wooden structure background gone with default theme

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#1939]
after 8637 and als v8720 the default theme is missing the wooden tiled structure

if you edit the custom.css file in the default theme folder and excluse the base.css file it appears again

/@import url("base.css"); /* Don't remove this line! REMOVED THIS(added /) TO GET WOOD STRUCTURE BACK */

so the problem lies in the base.css file i suspect.

i did clear both cache files but that does not help.
problem definately appeared when changes were made to accomodate the new theme structure

old default theme folder only had the custom.css file

![domoticz-background-wrong](https://user-images.githubusercontent.com/16853535/32690910-82941d12-c6ff-11e7-9b66-1e96e9315370.jpg)

after avoiding loading the base.css file al is well again.
![domoticz-background-right](https://user-images.githubusercontent.com/16853535/32690911-82ad00b6-c6ff-11e7-9864-6865ba2ddca6.jpg)

HOWEVER, this kills the user interface on  a mobile device(everything misaligned)

so what is so special in the base.css that the wooden structure does not get loaded on a pc but when i exclude the base.css everything is fine on chrome(PC) but out of order on an iphone(safari)

**Comment by gizmocuz** [comment]
That is on purpose
