### ISSUE TITLE
lua scripting triggering broke in V3.8720

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#1940]
i have a script which polls if a device is on or off(eg iphone)
if the iphone is on it switches on a group.

this is not working anymore with the latest build 8720
was working with 8637

googled a bit and it seems this is the same old bug which was introduced in 83xx

-- Turn ON
if (devicechanged[a] == 'On') then
	if (otherdevices[b] == 'Off' and otherdevices[c] == 'Off' and otherdevices[d] == 'Off') then
	commandArray[f]='On'
	else
	commandArray[e]='On'
	end
	end

**Comment by gizmocuz** [comment]
Where did you find this on google ?
To replicate this issue, you have to at least provide a step by step instruction, and the script.

**Comment by GravityRZ** [comment]
https://github.com/domoticz/domoticz/issues/1813

i reverted back to 8637 to find out scripting still was still not working.
i checked Eventsystem and it was disabled.
could it be that the newer versions have lua disabled by default(in favor of Dzvents)(did not check because i did not know there was such a setting)

**Comment by gizmocuz** [comment]
Depends from what version you came from (but that should be more then a year old)
But great you got it working!

**Comment by GravityRZ** [comment]
no i came from version 8637
tried it again, upgraded to 8720.
checked lua is still enabled, scripts working.

i think we can close this (but still puzzeled how this happened because scripting broke on the first time by disabling lua on it's own

thanks
