### ISSUE TITLE
DzVents:: not always triggering on "user variable" change

### ISSUE THREAD

**Issue by freemann** [domoticz/domoticz#1941]
Here running the most recent beta 3.8720 and seeing the following issue;
When I change an "user variable" through http://192.168.xxx.xxx:8080/#/UserVariables, my DzVent script "
Dark" is triggered.
When the same "user variable" is change by an Event, the DzVent script "Dark" isn't triggered;
Here's my dark script:
```
return {
	on = {
		variables = {'Dark'}
	},
	execute = function(domoticz, device)
	    if(device.name == "Dark")then
    	    if(domoticz.variables('Dark').value=="True")then
                domoticz.email('Het is donker, Voordeurlamp planned to go "on"','..','x@x.nl')
                domoticz.devices('Voordeurlamp').switchOn().withinMin(18).checkFirst()
            elseif(domoticz.variables('Dark').value=="False")then
                domoticz.email('Het is licht, Voordeurlamp planned to go "off"','..','x@x.nl')
                domoticz.devices('Voordeurlamp').switchOff().withinMin(10).checkFirst()
            end
        end
	end
}
```

**Comment by gizmocuz** [comment]
Please use our forum and post this under the dzVents topic

**Comment by freemann** [comment]
thanks...

Its a Domoticz feature, so why reporting it on other platforms?

**Comment by gizmocuz** [comment]
Other platforms ?
At our forum are people who might be able to assist you in this

**Comment by freemann** [comment]
I raised it on git because previous issue(s) mentioned/posted on the forum are also still there. So thought: maybe it better to raise it on git to prevent the issues drowns on the forums.

So git is not appreciated and forum is not working.... 

Already worked around it, so no need to fix it.

**Comment by gizmocuz** [comment]
As mentioned when you created this issue, i want to keep git for code discussions and changes and not for end users.
What you did is cross posting which is also not allowed.
It can happen that you do not get a reaction on the forum.. after some weeks a 'bump' reply to your post is possible
It could also mean that other users do not have this issue, or like you worked around the problem

**Comment by dannybloe** [comment]
and I'm always on top of dzVents/(Lua)/Event-system related issues/bugs in the forum so when needed they will land in the tracker here as well (or get fixed right away). So it's best to stick to the forum.
