### ISSUE TITLE
Event trigger types (Device, Timer, User Variable, etc) change without user changing it

### ISSUE THREAD

**Issue by freemann** [domoticz/domoticz#1945]
Running 3.8720

Yesterday I reorganized all my events to trigger on device/timer/user var./etc.
Today I noticed a lot of events are triggering on Timer without I change it to that.

So it looks like the trigger type is changing without the user changed it.

**Comment by dannybloe** [comment]
You gotta give a way lot more information here as this doesn’t help. Have you done the troubleshooting as described in the documentation?

**Comment by freemann** [comment]
Which documentation? 
If I'm right you are the dev of DzVents, so don't know which docs you mean.

**Comment by dannybloe** [comment]
You aren’t using dzVents for scripting?

**Comment by freemann** [comment]
I'm using DzVents for scripting and also LUA/Python/Blocky. (for instance see; https://github.com/domoticz/domoticz/issues/1941)

Have no idea where to start looking and/or debug this.

Maybe you could give me a starting point?

**Comment by dannybloe** [comment]
First of all: use the forum. There’s one for dzVents with links to the documentation. Then read the doc.

**Comment by freemann** [comment]
posted it here, not going to the forum.

thanks.
