### ISSUE TITLE
mqtt set uservariables (type string) don't work in beta versions

### ISSUE THREAD

**Issue by uronito** [domoticz/domoticz#1946]
In the last stable versions setuservariables by mqtt work well

In the last beta versions setuservariables by mqtt don't work well. The uservariables (type string) returns 0 value in lua scripts when are updated by mqtt with command. Example:

`{"command": "setuservariable", "idx": 2, "value": "Off"}`

In the stable version mqtt works like a charm in this case.

Regards

**Comment by gizmocuz** [comment]
Have you looked in the database ? (make a backup of the database, open it with for example 'SQLite Expert Personal Edition'

**Comment by uronito** [comment]
I have looked in the database and there the values ​​are stored well. the problem is that when I want to use those values ​​in the lua scripts, they return a value of 0. In the stable version 3.8153 works correctly. But in the latest beta releases, this error occurs.

Regards

**Comment by gizmocuz** [comment]
Okey, so MQTT to a user variable is OK, so this should close this topic...
It looks you are trying to read a integer value instead of a string in your lua code
maybe post an example of your lua code, as i am not into scripts...
best to post a complete lua file that i can use to test against

**Comment by uronito** [comment]
In lua:

In version 3.8153  ----->  print(uservariables['estado-enchufe-despacho']) -----> Off

In beta versions ------->  print(uservariables['estado-enchufe-despacho'])------>0

Regards

**Comment by gizmocuz** [comment]
Quick question before i get into debugging with Lua ... when you update the variable via the web gui, it works correctly ?

**Comment by uronito** [comment]
yes, if i update the variable via web gui or json , update is correct.

Only by mqtt update fails.

Regards

**Comment by gizmocuz** [comment]
It's not a MQTT issue... if i look in the database, the value is correctly updated.
I will debug the Lua handling now

**Comment by uronito** [comment]
Hi @gizmocuz 

have you been able to verify that the error occurs?

i think the error is in Lua handling then.

Thanks!!!

**Comment by gizmocuz** [comment]
Yes it's working again, a new beta will be available shortly (8741)

**Comment by uronito** [comment]
Thanks!!!!!!

Regards!!!!!!!
