### ISSUE TITLE
Soft reset z-wave controller results in losing all node names on setup page

### ISSUE THREAD

**Issue by ben423423n32j14e** [domoticz/domoticz#1949]
Hardware: Raspberry Pi with Razberry Z-Wave card

Steps to re-produce:

1) Give a name to any Z-Wave device on the setup page for the Z-Wave hardware, save it.

2) Click "Soft reset controller" from the menu

Restart Domoticz, device names get lost.

**Comment by gizmocuz** [comment]
Yes that is expected... you reset your zwave controller.. all internal ID's are now mismatched, probably also all sensors that where already in the system
Its not advised to do this of course... but sometimes man need too.
Can't change this

**Comment by ben423423n32j14e** [comment]
Thanks Gizmocus, I would like to suggest adding a popup and confirmation when users try to do a soft reset explaining exactly what it is. I've used Domoticz for about 3 years now and still didn't know exactly what it does. Luckly I had a Z-Way backup for the network and a db backup of Domoticz to return to. Cheers

**Comment by dannybloe** [comment]
Yeah, that's certainly a good and probably easy way to prevent peeps from accidentally pressing the button. In fact, we should strive to have a confirmation dialog behind all these kind of 'destructive' commands.

**Comment by gizmocuz** [comment]
Of course you google first what a reset on a controller does ? In 5 years this is the first report.
I expect users to be careful enough... specially users using ZWave which is complicated by default.
A soft reset should bdw not have deleted anything, and probably a restart of domoticz should have solved the problem

https://groups.google.com/forum/#!topic/openzwave/ot7b0XkHtGg

**Comment by dannybloe** [comment]
It's just good practice to always ask for confirmation in these situations if there is no undo function (like deleting a folder). Even if you know what you are doing. People just make mistakes.. accidentally clicking on the wrong button next to the one you intended to click on etc. The task of a good UI is to always prevent people from doing stupid things if it can be avoided.

My two cents.
