### ISSUE TITLE
Counter device type has duplicate options

### ISSUE THREAD

**Issue by dannybloe** [domoticz/domoticz#1950]
<img width="903" alt="screen shot 2017-11-14 at 19 25 12" src="https://user-images.githubusercontent.com/2369994/32797324-bc7d381e-c971-11e7-8714-48a32fd45e53.png">

The unkown item is also interesting :)

**Comment by gizmocuz** [comment]
Thanks for reporting.
Fourth options seems to be "Time"
and the double include was probably caused by the websockets merge...
Both fixed and available in an upcoming beta version
