### ISSUE TITLE
Door Contact usage

### ISSUE THREAD

**Issue by sweetpants** [domoticz/domoticz#1951]
V3.8740
Intel NUC
Ubuntu 14.04 LTS

Hi, I noticed when trying to switch a switch of type "Door Contact", Domoticz returns a message "Error sending switch command, check device/hardware !". Is this 'works as designed"? Recently it was changed for the Floorplan (commit 903928221effecd6055dbe84973aa4969767ecc0 "Floorplan, door contact, disable clicking/switching, it's a contact". Should that not also be the case in the switches/dashboard tab?

**Comment by gizmocuz** [comment]
That is correct. You are not supposed to switch a 'contact', it is not a switch.

**Comment by gizmocuz** [comment]
Upcoming beta will prevent clicking on door contacts
