### ISSUE TITLE
Unable to disable certain hardware

### ISSUE THREAD

**Issue by sweetpants** [domoticz/domoticz#1954]
Version: V3.8742
Platform: Ubuntu 14.04/16.04
Plugin/Hardware: none

When trying to disable hardware i am unable to. The change is not accepted, noticed it for:
Nefit
WOL
MySensors

but maybe there are more.

**Comment by Eorciu** [comment]
I pull request which should fix this, https://github.com/domoticz/domoticz/pull/1962

**Comment by sweetpants** [comment]
Looks like it is fixed in V3.8755, thanks

**Comment by gizmocuz** [comment]
Thanks for checking, please close the issue when it's solved
