### ISSUE TITLE
Math Libraries for Blockly

### ISSUE THREAD

**Issue by tuxmartin** [domoticz/domoticz#1957]
https://domoticz.com/forum/viewtopic.php?f=31&t=10757

> It would be very nice to have some mathematical calculations in Blockly.
> 
> This is used in lots of other Blockly Examples but just outside of Domoticz
> https://developers.google.com/blockly/
> https://blockly-demo.appspot.com/static ... index.html
> https://blockly-games.appspot.com/
> 
> For the beginning I wouldn't need some very complex Calculations but even easy stuff like "Increase User Variable", "Check for Temperature + x", "Multiply Numbers to convert units" would be very useful ;)

![domoticz_blockly_math](https://domoticz.com/forum/download/file.php?id=13509)

**Comment by szczukot** [comment]
YEs. Recently I was missing the usual addition (setpoint + value)

**Comment by tuxmartin** [comment]
Is possible to install math lib for blockly as plugin?

**Comment by gizmocuz** [comment]
No.... yes... but that does not mean the underlying code will work... It is not as easy as 1+1

**Comment by szczukot** [comment]
Gizmocuz, can you upload the latest version? 
The current one is 1.5 years old and is very old.

**Comment by gizmocuz** [comment]
NO, and this can not be added as we need to support this as well.
As you might already know, if you want to use a more advanced script, you can use dzVents or Pytjon

**Comment by xztraz** [comment]
It's a bit of a shame not lifting the best part about domoticz. I just made the wiki on blockly a bit more understandable for beginners. Also why you can't use if and else as in normal languages and stack ifs and such probably needs a bit of code too.. :)

**Comment by szczukot** [comment]
I agree.
Not all domoticz users are IT developer. Blockly is super for normal people.
Gizmocu, please at least to update to the latest version of the library (fewer errors, more possibilities)

**Comment by gizmocuz** [comment]
No sorry, this won't make any difference and even might brake the current code.
That you can perform actions in blockly (or like adding things) will not say that domoticz knows what to do
Even simple things like IF temperature is higher then... this had to be coded to.
The current blockly implementation works, we can do the stuff we want, there is no reason to update it
For more advance usage in scripts as mentioned before, dzVents or Python is the solution.
Or someone needs to add some code for the new blockly functions in domoticz
