### ISSUE TITLE
Multiple Nest Thermostats Not Detectable

### ISSUE THREAD

**Issue by mysteryan** [domoticz/domoticz#196]
I have two thermostats in my home (common in multi-story homes) and Domoticz always only detects the first Nest thermostat, but not the second one. I've tried removing the hardware and re-adding it with and without a reboot. I've tried a clean installation and tried updating to the latest beta version of Domoticz and always fails to detect the second Nest.  Currently using a nestpy script using a different index argument with a virtual thermostat as a workaround.

**Comment by gizmocuz** [comment]
that is because there is currently support for one thermostat.
Is it possible to contact me on the forum/mail to send me the login credentials, with this i should get this to work for multiple sensors.

In the code we only use the first:
Json::Value vShared = *root["shared"].begin();

**Comment by gizmocuz** [comment]
implemented
