### ISSUE TITLE
eHouse udp listener build errors

### ISSUE THREAD

**Issue by mosjonathan999** [domoticz/domoticz#1967]
/home/pi/dev-domoticz/hardware/eHouse/EhouseUdpListener.cpp: In member function ‘void eHouseTCP::Do_Work()’:
/home/pi/dev-domoticz/hardware/eHouse/EhouseUdpListener.cpp:3235:14: warning: iteration 20u invokes undefined behavior [-Waggressive-loop-optimizations]
   if (AuraN[i] != NULL)
              ^
/home/pi/dev-domoticz/hardware/eHouse/EhouseUdpListener.cpp:3232:1: note: containing loop
 for (i = 0; i <= MAX_AURA_DEVS; i++)
 ^

i get the following errors when building from source

**Comment by gizmocuz** [comment]
Thanks for reporting, this should now be solved in 
https://github.com/domoticz/domoticz/commit/7626f71a0b28efb5dfeabd7dab8b2be0db1c59ce

**Comment by ehousepro** [comment]
Thank you for reporting
It was corrected already

@gizmocuz will you update it or should I put another pull request  ?

**Comment by gizmocuz** [comment]
I think I already fixed it

**Comment by ehousepro** [comment]
thanks, sorry for inconvinience
