### ISSUE TITLE
Layout issue in Safari

### ISSUE THREAD

**Issue by runerh** [domoticz/domoticz#1968]
There is an issue with the mobile layout in Safari, in full screen. The icons on the top of the page get placed all over the place.
I only see the issue if I open the webinterface from a saved shortcut on the desktop of my iPhone (fullscreen).
As long I'm not running the interface in fullscreen everyting looks okay, 
I have tried to flushed all cache in Safari, but didn't help.

Regards
Rune Rønning Hanssen

**Comment by gizmocuz** [comment]
Could you post a screenshot ?
I always run it that way, so once i go with safari to the Domoticz GUI, then i add a shortcut on the homescreen, and use this... this is also the preferred way because all is cached

**Comment by Mguss** [comment]
Hi. I have same problem.
Here is a screenshot.

//Micke
![img_0971](https://user-images.githubusercontent.com/8825256/33449962-99a7b31e-d60a-11e7-896b-fdd29653f13d.PNG)

**Comment by ageurtse** [comment]
Same problem here i’m running an iphone 8, the other iphones in the house all lower then 6 and 5 are good.

So it looks like it’s an iphone 8 problem

**Comment by ageurtse** [comment]
There are some icons missing on my phone.
And it only occures when i bookmar the page to the start screen of my phone.

Then it happens, if i delete this shortcut and opening the pake direct in safari it is working right

**Comment by runerh** [comment]
Hi
I have an iPhone 6S, so this issue isn't only related to iPhone 8.
Rune

![safari_issue_iphone6s](https://user-images.githubusercontent.com/34045342/33605798-6a3e768a-d9bb-11e7-906c-5c7ea12eae03.png)

**Comment by gizmocuz** [comment]
Is this solved in the latest beta version ?

**Comment by runerh** [comment]
I'll try to upgrade to the latest beta to night, and report back.

**Comment by gizmocuz** [comment]
@runerh , kindly reminder, did you notice this problem or has it been solved ?

**Comment by stas-demydiuk** [comment]
@gizmocuz FYI I tried and wasn't able to reproduce it on my device with latest Domoticz beta and iOS 11

**Comment by gizmocuz** [comment]
Thanks for the feedback.
I also checked it against an iPhone, just wanted to be sure it was not solved only here ;)
