### ISSUE TITLE
Philips HUE unreachable state

### ISSUE THREAD

**Issue by khaeljy** [domoticz/domoticz#1969]
Hi,

Philips Hue not showing the unreachable state of bulbs.
So, it's possible to toggle the state of a bulb unreachable in Domoticz without error.

Can you add the unreachable status for Philips Hue and blocking all commands to an unreachable bulb?

Thank you!

**Comment by gizmocuz** [comment]
could you add some more information like the flag we should check from the hue output ?

**Comment by khaeljy** [comment]
Yes, when you get light status (_/api/username/lights/id_), the output return a "**state**" element that contain the "**reachable**" flag (indicates if a light can be reached by the bridge).

```
{
	"state": {
		"hue": 50000,
		"on": true,
		"effect": "none",
		"alert": "none",
		"bri": 200,
		"sat": 200,
		"ct": 500,
		"xy": [0.5, 0.5],
		"reachable": true,
		"colormode": "hs"
	},
	"type": "Living Colors",
	"name": "LC 1",
	"modelid": "LC0015",
	"swversion": "1.0.3"
}
```

Source : [https://developers.meethue.com/documentation/lights-api](https://developers.meethue.com/documentation/lights-api)

**Comment by gizmocuz** [comment]
This flag is now handled/checked in the latest beta
