### ISSUE TITLE
eHouse mainworker build issue

### ISSUE THREAD

**Issue by chatainsim** [domoticz/domoticz#1975]
Hello,

I have some issue when building Domoticz in mainworker.cpp.o related to eHouse I think:
```
CMakeFiles/domoticz.dir/main/mainworker.cpp.o : Dans la fonction « MainWorker::AddHardwareFromParams(int, std::string const&, bool, _eHardwareTypes, std::string const&, unsigned short, std::string const&, std::string const&, std::string const&, std::string const&, int, int, int, int, int, int, int, bool) » :
mainworker.cpp:(.text+0x2722a) : référence indéfinie vers « eHouseTCP::eHouseTCP(int, std::string const&, unsigned short, std::string const&, int, int, int, int, int, int) »
collect2: error: ld returned 1 exit status
```

**Comment by ehousepro** [comment]
I think you have some broken files from different repos
In my opinion you should:
-  kill all unused application make more free spaces and memory
- git pull (newest version of domoticz)
- clean all (depending on tools you use)
- recompile all files again

**Comment by ehousepro** [comment]
This is Linker issue - NON eHouse issue
**From domoticz ROOT catalogue**

**Option 1) Clean all files (very long recompilation ~up to 1 hour) options my be removed  or changed
-USE_STATIC_OPENZWAVE
-DCMAKE_BUILD_TYPE=Release**

./cmake-clean ./
cmake -USE_STATIC_OPENZWAVE -DCMAKE_BUILD_TYPE=Debug -debug-out CMakeLists.txt
make

**Option 2) Clean only affected file by eHouse implementation** 

rm ./CMakeFiles/domoticz.dir/main/mainworker*
rm ./CMakeFiles/domoticz.dir/main/WebServer*
rm ./CMakeFiles/domoticz.dir/hardware/eHouseTCP*
rm ./CMakeFiles/domoticz.dir/hardware/eHouse/*
cmake -USE_STATIC_OPENZWAVE -DCMAKE_BUILD_TYPE=Debug -debug-out CMakeLists.txt
make

**I think for most integrations (adding hardware) with domoticz this linking error can be solved by running:**
rm ./CMakeFiles/domoticz.dir/main/mainworker*
rm ./CMakeFiles/domoticz.dir/main/WebServer*
before compilation/linking

**Comment by chatainsim** [comment]
What I tried is:
```
rm -r domoticz
git clone https://github.com/domoticz/domoticz.git
cd domoticz
cmake -DUSE_PYTHON=YES -DCMAKE_BUILD_TYPE=Release CMakeLists.txt
make -j 2
```
But it also failed.

I'll try again with:
```
cmake -DUSE_PYTHON=YES -DCMAKE_BUILD_TYPE=Release -USE_STATIC_OPENZWAVE CMakeLists.txt
```
Then with the debug option.

But since now, every time I compil Domoticz, I'm doing:
```
make clean
rm -r CMakeFiles CMakeCache
git pull
cmake -DUSE_PYTHON=YES -DCMAKE_BUILD_TYPE=Release CMakeLists.txt
make -j 2
```
Is it the correct way ?

**Comment by chatainsim** [comment]
Ok, since I've made a git pull, I have an other issue but in HardwareMonitor.cpp for some other thing:
```
/home/simon/SRC/DoMoTiCz1/hardware/HardwareMonitor.cpp: In member function ‘float CHardwareMonitor::GetProcessMemUsage()’:
/home/simon/SRC/DoMoTiCz1/hardware/HardwareMonitor.cpp:548:56: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(std::basic_string<char>)’
   std::ifstream mfile("/proc/" + sPid.str() + "/status");
                                                        ^
/home/simon/SRC/DoMoTiCz1/hardware/HardwareMonitor.cpp:548:56: note: candidates are:
In file included from /home/simon/SRC/DoMoTiCz1/hardware/../main/Logger.h:6:0,
                 from /home/simon/SRC/DoMoTiCz1/hardware/HardwareMonitor.cpp:4:
/usr/include/c++/4.8/fstream:467:7: note: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
       ^
/usr/include/c++/4.8/fstream:467:7: note:   no known conversion for argument 1 from ‘std::basic_string<char>’ to ‘const char*’
/usr/include/c++/4.8/fstream:453:7: note: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream() : __istream_type(), _M_filebuf()
       ^
/usr/include/c++/4.8/fstream:453:7: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/4.8/fstream:427:11: note: std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
/usr/include/c++/4.8/fstream:427:11: note:   no known conversion for argument 1 from ‘std::basic_string<char>’ to ‘const std::basic_ifstream<char>&’
make[2]: *** [CMakeFiles/domoticz.dir/hardware/HardwareMonitor.cpp.o] Erreur 1
make[2]: *** Attente des tâches non terminées....
make[1]: *** [CMakeFiles/domoticz.dir/all] Erreur 2
make: *** [all] Erreur 2
```
I will update boost to 1.65.1 since I have v1.61.0 maybe this will help.

**Comment by gizmocuz** [comment]
There is a new code update

issue

cd domoticz
git pull
make

**Comment by chatainsim** [comment]
Even with boost 1.65.1 I have the issue.
I don't know how to fixe this. It's the first time it fail like this (and I've compiled Domoticz a lot's of time without issue).
Just see the new commit https://github.com/domoticz/domoticz/commit/b20c56ee3be4dc34332b968e5d78b758e33fcd45 will try again ! 👍

**Comment by ehousepro** [comment]
Are you still writing about eHouseTCP linking problem?
Did you try manual erase of files explained above?

**Comment by chatainsim** [comment]
@ehousepro Since I'm doing a rm -r CMakeFiles so yes, I'm removing the files explained above

**Comment by ehousepro** [comment]
Ensure if you have ehouse lines in CMakeLists.txt
hardware/eHouseTCP.cpp
hardware/eHouse/EhouseEvents.cpp
hardware/eHouse/EhouseTcpClient.cpp
hardware/eHouse/EhouseUdpListener.cpp

Check if you have files itself in your installation

**Comment by ehousepro** [comment]
I test Fresh compilation (10:20 CET) from scratch to new directory with your options: Ubuntu x64  17.04

_git clone https://github.com/domoticz/domoticz.git domo
cd domo
cmake -DUSE_PYTHON=YES -DCMAKE_BUILD_TYPE=Release CMakeLists.txt
make -j 2_

**Completed successfully** 

Try to do the same in new location

**Comment by chatainsim** [comment]
I think this is because I've made some change in CMakeLists.txt to add support of Python3.5 and the file wasn't replace with the git pull.
I revert back and test again.

**Comment by ehousepro** [comment]
Yes !!!

if you modified files locally they are not replaced from git repository: 

So you can add eHouse lines to cmakelists manually or compare to newest file (maybe something else was added in the mean time)
hardware/eHouseTCP.cpp
hardware/eHouse/EhouseEvents.cpp
hardware/eHouse/EhouseTcpClient.cpp
hardware/eHouse/EhouseUdpListener.cpp

Please Recheck and Close eHouse Issue if OK

**Comment by chatainsim** [comment]
Ok, It's working now !
Thanks @ehousepro

**Comment by ehousepro** [comment]
ok

**Comment by chatainsim** [comment]
Even when I'm deleting the CMakelists.txt, git pull nerver retrieved the file.
Is there a way to fixe this ?

**Comment by ehousepro** [comment]
maybe it is in git ignore list?
do you have any warnings during "git pull"?

**Comment by ehousepro** [comment]
or maybe you have make "git stash" to ignore your changes?

**Comment by chatainsim** [comment]
I didn't use git stash and I have no warning during git pull.
Also not in the ignore list ... Strange.
I will make a script to remove the file before pulling then test if exist and use wget to grab a copy online.

Thanks

**Comment by ehousepro** [comment]
As I know (not sure - pls. check in interenet) running **git stash** drop your local changes, so **you have to do it**.

**Comment by chatainsim** [comment]
Seems correct:
```
Use git stash when you want to record the current state of the working directory and the index, but want to go back to a clean working directory. 
The command saves your local modifications away and reverts the working directory to match the HEAD commit.
```

I will try.
