### ISSUE TITLE
DarkSky Weather Lookup always saves 0 values for Outdoor Rain?

### ISSUE THREAD

**Issue by djvdorp** [domoticz/domoticz#1976]
Version: 3.8153 (latest stable on Raspberry Pi3)
Build Hash: 494fff7
Compile Date: 2017-07-30 12:19:41

I am using the DarkSky Weather Lookup device to log and monitor the outside weather in The Netherlands. As you might very well be aware, it has been very much Autumn/Winter outside, so there is lots of rain and even wet snow at the moment. However, my Outdoor Rain values are always 0 in Domoticz Dashboard?

**Comment by djvdorp** [comment]
I am adding Weather Underground now, it might be a DarkSky API problem maybe, so the data, not app.

**Comment by gizmocuz** [comment]
You can check this yourself by requesting the data manually on the darksky site

**Comment by gizmocuz** [comment]
No response, closing issue
