### ISSUE TITLE
1000W during 1h = 1000Wh

### ISSUE THREAD

**Issue by sifourquier** [domoticz/domoticz#1981]
Hi
I have create a fork of domoticz and i have found a bug and your code have the same bug
when a sensor of type General/kWh for example dummy/Electric (Instant+Counter)
have 1000W during 1hour or more. The power usage (Wh) are less of 1000Wh for example 917Wh (he lost 5 minute of power usage)
I join my patch. my patch can remove or add 1 minute of power but it is best of 5minutes

thanks you for your job

[0001-fix-power-kWh-usage.tar.gz](https://github.com/domoticz/domoticz/files/1523253/0001-fix-power-kWh-usage.tar.gz)

**Comment by gizmocuz** [comment]
Thank you !, Could you make a pull request against our development branch with your patch ?
