### ISSUE TITLE
IDX attribution is not working in create virtual sensor command

### ISSUE THREAD

**Issue by NoelieRamuzat** [domoticz/domoticz#1983]
Hi,
I am using the V3.8771 of Domoticz and I have troubles in creating a virtual sensor.
I use the following command:
/json.htm?type=createvirtualsensor&idx=NBR&sensorname=TemperatureSensor&sensortype=80

The NBR attributed to idx is not taken into account and a default idx is given to my virtual sensor. The sensorname seems to have not been set neither, I have "HardwareName" : "Unknown?" when I list all the devices.

Thank you for your time.

**Comment by szczukot** [comment]
What is mean "NBR" ? ISit string or integer ?

**Comment by NoelieRamuzat** [comment]
It is a string. What I meant is that whatever number I put it doesn't work.
Even if I directly put the url in my browser, the virtual sensor created
has a default idx.


Le 5 déc. 2017 6:31 PM, "Fantom" <notifications@github.com> a écrit :

What is mean "NBR" ? ISit string or integer ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/domoticz/domoticz/issues/1983#issuecomment-349378961>,
or mute the thread

**Comment by szczukot** [comment]
In this pull request i also fix error with bad sensor name (before is not set):
https://github.com/domoticz/domoticz/pull/1961

**Comment by szczukot** [comment]
If i set idx=123 i see new device with hardware id = 123

**Comment by szczukot** [comment]
@NoelieRamuzat is it ok now ?

**Comment by NoelieRamuzat** [comment]
@szczukot yes I am sorry I forgot to answer.
I have the good hardware id, I thought that we can fix the idx directly but I use the hardware one instead.
Thank you for your help !
