### ISSUE TITLE
Images are always retrieved from the server when browsing the root site

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#1984]
When going to the address http://<host>:8080 with by browser several time, the themes images are always retrieved from the server. They should be cached by the browser instead.

Going to http://<host>:8080/#/Dashboard http://<host>:8080/#/LightSwitches is working fine (i.e. cached images but the root access is not working fine.

Why not caching the images until the server is upgraded ?

**Comment by gizmocuz** [comment]
Might be an appcache issue? Or a browser issue, it should be cached

**Comment by sbouchex** [comment]
it appears to be firefox specific. It works with Chrome and Edge
