### ISSUE TITLE
Solaredge via web api issue

### ISSUE THREAD

**Issue by alcindof** [domoticz/domoticz#1985]
Hi,

Last month my SolarEdge inverter was installed.
For about the last two weeks I tried to configure the "Solaredge via web api" but I ran into the same issue as noted in "SolarEdge via Web API Error getting http data" #1784 

At least the configuration menu looks like:
![configmenu](https://user-images.githubusercontent.com/34269451/33851337-015a1e8e-deb7-11e7-92eb-6870c11f2930.png)
Instead of asking for just a site id, a serial and API Key like in [https://www.domoticz.com/wiki/File:Add_hardware.png](https://www.domoticz.com/wiki/File:Add_hardware.png)
![add_hardware](https://user-images.githubusercontent.com/34269451/33851392-30045ee8-deb7-11e7-9197-30827df99824.png)

#1784 mentioned the issue had been resolved by some new beta of or before September 9th (2017).
However I have not been able to trace back any details. And for me the issue exists at this moment.

I have looked for any beta patch information, code changes specifically for that period. However my Github knowledge is clearly lacking :-(

I am running the (latest?) beta V3.8771 (automatic upgrade on my Rasberry Pi dedicated for Domoticz).
_Edit December 9th: Now running beta V3.8775, issue persists._

_Edit December 12th, added Linux version:
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux
pi@raspberrypi:~ $ lsb_release -irc
Distributor ID: Raspbian
Release: 8.0
Codename: jessie_

How can I resolve this issue? 
Thank you!

Best regards,
Alcindof

PS A roll-back (to the last official release) appears to be a lot of work. And I rather have this fixed in the current beta branch.

**Comment by gizmocuz** [comment]
I think something has broke in the latest beta releases (it still works for people already configured it)
There should only be the option for API key
From who did you get the API key ? From the mechanic ?

**Comment by gizmocuz** [comment]
There will be an update in an hour and it should now only look like:

![image](https://user-images.githubusercontent.com/2265299/33897040-b12d3dde-df64-11e7-91cc-c498b86a185c.png)

**Comment by alcindof** [comment]
Great, I look forward to the beta with fix.
I can generate a new (Dutch: Nieuw) API key (DutchL Sleutel) at the bottom of the Admin > Site Access tab of https://monitoring.solaredge.com site
![apikey](https://user-images.githubusercontent.com/34269451/33898910-119ed9ac-df6a-11e7-92f3-2f0121c789a7.png)
Thank you for looking into this issue!

**Comment by alcindof** [comment]
Hi gizmocuz ,

It looks exactly as your picture. But looking a bit better I expected to need to enter a siteid (and maybe serial)?

The documentation @ https://www.solaredge.com/sites/default/files/se_monitoring_api.pdf refers to a siteid besides the api-key:

URL: /site/{siteId}/dataPeriod 
Example URL: https://monitoringapi.solaredge.com/site/1/dataPeriod?api_key=L4QLVQ1LOKCQX2193VSEICXW61NP6B1O 

I am getting an error now:
2017-12-12 19:58:14.544 SolarEdgeAPI Worker started... 
2017-12-12 19:58:20.660 Error: SolarEdgeAPI: Error getting http data! 

Best regards,
AlcindoF

**Comment by rubenb85** [comment]
Hi Gizmocuz,

I'm running 3,8153 and try to configure my SolarEdge inverter but I'm having almost the same issue. I can add my inverter via the API and I don't get an error in the log. "SolarEdgeAPI Worker started..." and that's it. When I type a wrong API key I get an error in the log: "Error: SolarEdgeAPI: Error getting http data!" so it look likes the API is working fine but I don't get any devices in my list. 

Any idea?

I've tried to upgrade (for test) to the beta you've released but I'm running it on my Synology and I can't get it on it.

Best regards,
Ruben

**Comment by gizmocuz** [comment]
You do not have to enter a siteid anymore, the API key is enough.
Also there needs to be sun... the inverter needs to have a reading.
That is, during sun hours (sunrise/set) and when there is sun.
If there is no sun, there is no read-out
For example, if you live in the Netherlands, there is a very good change the last reading was from yesterday 16:30 (and now it is 11:30 and still no reading)

**Comment by alcindof** [comment]
Here comes the sun, here comes the sun
And I say it's all right

Running V3.8785
Yes, now that there is sun: The data appears after enabling/activating the hardware again just now
After adding the five new devices< I sould make these favorites from there respective tabs and add them to the Dashboard tab.

**Comment by alcindof** [comment]
This issue is resolved and closed.

**Comment by insippo** [comment]
I try but without luck. Domoticz version is 3.8924
[https://photos.app.goo.gl/XvveRwNUxOMWZL252](url)

**Comment by gizmocuz** [comment]
@insippo , please do not post images on outside pages, the image can also not be found.
You can copy/past images in here.

**Comment by berg26** [comment]
I have the same issue, Error: SolarEdgeAPI: Error getting http data!
Domoticz version 3.9052. Raspberry PI 3. Fresh install with Noobs. Raspbian updated to latest version (updates and (dist-)upgrades)
Tried reboots, cleared browser cache, removed and re-entered Solaredge hardware settings in Domoticz. Tried a new API key from my Solaredge account. I get the right screen in Domoticz that gizmocuz shows in this thread now, I only have to enter the API code. Solar system is producing now. Nothing works.

Any Idea?

Best Regards,
Berg26

**Comment by mestief** [comment]
Hi,
I also have the same problem. I'm on Version: 3.8153
I have the same menu as topic starter. 
I only entered my Api key and the only thing I see in the log is: 
_2018-05-02 12:26:19.909 SolarEdgeAPI Worker started…_
When I enter a wrong Api key  I get:
_2018-05-02 12:26:03.904 Error: SolarEdgeAPI: Error getting http data!_
BTW the Sun is Shining and my inverter is working correctly. I'm producing power right now.
My location settings are also correct. My Dashboard shows Sun up: 05:58 Sun down: 21:03 for today.
Hope someone can help to get this fixed.

Regards,
Stief

**Comment by sweetpants** [comment]
Did you read the complete post? When I read it you should upgrade to beta

**Comment by mestief** [comment]
Hi,
Thanx for the response. Guess I didn't read it well enough. Missed the post from alcindof where he mentioned that it's working.
Will try later today.

**Comment by insippo** [comment]
I update Domotizc to latest and add this api key. Next day if inverter working  Domoticz created some new devices.

**Comment by insippo** [comment]
![apikey](https://user-images.githubusercontent.com/4020757/39562218-1ea236c2-4eb3-11e8-89f1-3f04aa12b130.png)
 I deleted some symbols from key on the picture
