### ISSUE TITLE
Domoticz crash with P1 slimme meter

### ISSUE THREAD

**Issue by doc221** [domoticz/domoticz#1989]
Hello,
I am running 3.8153 on a raspberry PI and I am running into the problem that when the P1 Slimme meter is active, it crashes domoticz after some time. Syslog shows the message below. I have no clue where to go from here.
Can someone help me on this?
P1 Smart Meter: Meter reports as DSMR 5.0

Dec 10 22:26:04 raspberrypi domoticz: Domoticz received fatal signal 11 !...
Dec 10 22:26:04 raspberrypi domoticz: (Slimme meter) P1 Smart Meter (Power)
Dec 10 22:26:04 raspberrypi domoticz:   /home/pi/domoticz/domoticz() [0x1cdc48]
Dec 10 22:26:04 raspberrypi domoticz:   /home/pi/domoticz/domoticz(_Z14signal_handleri+0x58) [0x1cdd00]
Dec 10 22:26:04 raspberrypi domoticz:   /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer_v2+0) [0x76b14180]

**Comment by alcindof** [comment]
Hi,
I am running beta V3.8775 also on a RPi(3b) and I have no issues.
Here are my settings:
![p1slimmemeter](https://user-images.githubusercontent.com/34269451/33851188-815dabe2-deb6-11e7-99c2-575088b83ddf.png)
I do not know if it is a setting issue or it will be fixed by updating (automatically - if set to do it so) to the latest beta. 
I hope this helps.
Best regards,
AlcindoF

**Comment by rwaaren** [comment]
Hi AlcindoF,

which OS is on your RPi(3B)?

**Comment by alcindof** [comment]
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux

pi@raspberrypi:~ $ lsb_release -irc
Distributor ID: Raspbian
Release:        8.0
Codename:       jessie

**Comment by rwaaren** [comment]
That might be a reason why I experience something different: 
xxx@PI-2:$uname -a
Linux PI-2 4.9.26v7-aufs #1 SMP Tue May 9 20:14:03 CEST 2017 armv7l GNU/Linux

xxx@PI-2: $lsb_release -irc
Distributor ID: Raspbian
Release:        9.1
Codename:       stretch

**Comment by doc221** [comment]
I installed the 3.8775 Beta on Raspbian 8.0. Runs like a charm since!!!
Thanks for the help.
