### ISSUE TITLE
Rtl_433 - Pressure, Wind, Humidity patch

### ISSUE THREAD

**Issue by TimelessNL** [domoticz/domoticz#1996]
Hi,

I've created a small patch for Rtl_433. with the following changes:

- Fixed parsing of pressure, should be pressure_hPa.
- Added initial support for Wind sensor based on my HIDEKI Wind sensor. _Unfortunaly my Wind sensor only gives 1 temperature on rtl_433 for now (RFXcom detects both temp&chill). Since I only have 1 temperature I chose it to be Chill._
- Fixed parsing of humidity, some devices use LL and HH for minimal and maximal values. _Don't know why but this is probably because these sensor display LL & HH on their display. For example: [GT-WT-02](https://github.com/merbanan/rtl_433/blob/6531ea48a7933ac8289724672059e54fd8aad8eb/src/devices/gt_wt_02.c#L22)._ I've chosen the LL to be 10% and HH to be 90%. But it's hard to chose a good default since not all sensors have the same measure range.

Please have a look at my patch and let me know what you think:
[rtl_433_domoticz.zip](https://github.com/domoticz/domoticz/files/1557555/rtl_433_domoticz.zip)

**Comment by gizmocuz** [comment]
Patch is looking good but maybe next time you could make a pull request so we can easily see the changes ?
One thing to look for, have a look at mainworker::decode_Wind, if the chill=0 then it will be correctly calculated.
So it is better to send the temperature and leave the chill 0

**Comment by TimelessNL** [comment]
Thanks, yeah next time I will create a pull request. Was a little late yesterday and really wanted to know if there was something to improve.

Mmh, so if I set bHaveWindTemp (true) and switch the current temperature around then I will get a chill calculated? Ok :) going to give that a try.

What about this sensor only reporting 1 wind-speed? I noticed decode_wind also checks for sTypeWIND6 and put Gust into Speed. But since I now say bHaveWindTemp(true) the subtype will be set to sTypeWIND4 in SendWind(). Will it be valid to just put the current windspeed value in both speed&gust when calling the SendWind function?

**Comment by TimelessNL** [comment]
Ok I've updated/tested my patch. And the chill temp works great :)
_note: I've used the same value for speed&gust, because this seemed right to me_
[rtl_433_domoticz_v2.zip](https://github.com/domoticz/domoticz/files/1560143/rtl_433_domoticz_v2.zip)

Let me know what you think.

**Comment by gizmocuz** [comment]
Looking good. Speed and Gust are two different things. I will try to get some readings from my windows sensor this weekend to see if it reports speed and gust. I know the RFXTrx433e does report two different values. Maybe it is a rtl433 library issue if it is not reported and it needs to be implemented.
If you like, please submit a pull request so this patch can be merged ;)

**Comment by TimelessNL** [comment]
It seems that there is a CSV parameter for wind_gust:
_[current csv name list of rtl_433]_
`time,model,id,channel,battery,temperature_C,mic,rid,button,humidity,state,brand,rain_rate,rain_total,gust,average,direction,pressure_hPa,uv,power_W,energy_kWh,unit,group_call,command,dim,dim_value,wind_speed,wind_gust,wind_direction,dipswitch,rbutton,device,temperature_F,rc,brandmodelidtemperature_C,setpoint_C,switch,direction_str,direction_deg,speed,rain,msg_type,signal,hours,minutes,seconds,year,month,day,sensor_code,uv_status,uv_index,lux,wm,fc,ws_id,rainfall_mm,wind_speed_ms,gust_speed_ms,current,interval,learn,windstrength,winddirection,flags,maybetemp,binding_countdown,depth,power0,power1,power2,node,ct1,ct2,ct3,ct4,Vrms/batt,temp1_C,temp2_C,temp3_C,temp4_C,temp5_C,temp6_C,pulse,sid,transmit,moisture,status,type,pressure_PSI,battery_mV,pressure_bar,code,pulses,energy,deviceid,len,to,from,payload,event,heartbeat,brandmodelidstatus,temperature_C1,temperature_C2,temperature,test,newbattery,heating,heating_temp,water,counter,alarm,depth_cm,repeat,temperature_1_C,temperature_2_C`

And I noticed this in decode_wind: [This sensor is only reporting gust, speed=gust](https://github.com/domoticz/domoticz/blob/566ad3921bbe43ea7e3df8b9516f7acde55df84a/main/mainworker.cpp#L3086)
So I made the choice to set gust=speed (which is the other way around). But maybe it's better to parse "wind_gust" as well and support both wind sensors with only "wind_speed" and "wind_speed&wind_gust". So when rtl_433 supports gust for this kind of sensor it will work out of the box with Domoticz.

I also tested my wind sensor with my RFXCOM433e and it reports both speed&gust. So the sensor is perfectly capable which makes me assume it's just a rtl_433 problem.

But lets wait for your sensor readings first, to see if "wind_gust" gets reported.
I'm using the [TFA 30.3168](https://weerhuisje.nl/nl/a/tfa/tfa-30_3168-windsensor-draadloos_-solar/10000031/9547) by the way.

**I also had a issue with rtl_433 and temp&hum sensors,** I noticed a temp&hum sensor will sometimes be parsed as temperature=0 and humidity=0. I suspect rtl_433 was not able to decode the received message correctly  and then defaults to 0 and 0. I've not seen this happening during live decoding of rtl_433 but noticed this a couple times a day in the Domoticz logs. So I'm not sure if we parse it incorrectly of rtl_433 is putting out wrong data. Maybe it's wise to check if temp and hum are both 0? Because this kind of measurement with 0% humidity is invalid anyway as far as I know.

Ps. I'm currently programming Domoticz from within LEDE's buildroot environment, thats also why I made a patch instead. I have to fork Domoticz before I can provide a pull-request. Is it ok if we make the final decisions first and then fire the pull-request?

**Comment by TimelessNL** [comment]
Have you tested your windsensor @gizmocuz?

Ps. I also want to include a temp != 0 && hum != 0 check like i mentioned in my previous post, what do you think about that workaround?

**Comment by gizmocuz** [comment]
No not yet... hope to do it soon, else it has to wait until next year. But plz create a pull request as this can be added later

**Comment by TimelessNL** [comment]
Ok. Will create the pull request soon. Ok if I include the temp&&hum != 0 constraint?

**Comment by gizmocuz** [comment]
Sure because a humidity of 0 (which is rare) and also a temperature of 0 does not happen often ;)

**Comment by TimelessNL** [comment]
Haha true. Ok going to create a pull request. Issue closed :)

**Comment by TimelessNL** [comment]
I've created the pull-request.
