### ISSUE TITLE
For now... we use the commit revision number because...

### ISSUE THREAD

**Issue by gizmocuz** [domoticz/domoticz#2]
Yes, i know, we should work with hashes, but for now we use the revision number with

git rev-list HEAD --count

and i add the value 2107 for it

Reason:
- in the previous code (on SVN) an update was flagged if the new (above) version number was higher then the current version number
- this is now changed, but current beta/release users of domoticz (that are using the binary update functionality) still needs this to update to a new beta/release version

I hope (expect) that all beta users will update in a month to a new beta version, so we can stop this

From that moment the version number 2.xxxx will be changed to 3.yyyy whet yyyy is the git commit revision number (maybe also show the hash code)

So please, dont flame/blame etc at the moment

to go from a revision number back to the commit hash code you could call

git rev-list --reverse HEAD | cut -c1-7 | nl | awk "{ if(\$1 == "635") { print \$2 }}"

(where 635 is the number)

**Comment by ghost** [comment]
When will be change number version in Domoticz to the same as in History ?

**Comment by gizmocuz** [comment]
@ghost, only when we make an release, we are not going to update this file for every commit, also the commit history above has the current commits

**Comment by gizmocuz** [comment]
Closing issue, we are using also the build hash
