### ISSUE TITLE
Teleinfo Courant Alert levels

### ISSUE THREAD

**Issue by Marbaf** [domoticz/domoticz#2009]
Hello,
I think there might be an issue with Teleinfo Courant alert levels.
Comment on top of _AlertLevel_ function is:

> Alert level is 1 up to 80% usage, 2 between 80% and 90%, 3 between 90% and 98%, **4** above

But inside function, last if statement, level variable is set to 3 instead of 4:
`int CTeleinfoBase::AlertLevel(int Iinst, int Isousc, char* text)
{
	int level;
	float flevel;

	flevel = (float)(Iinst*100) / Isousc;
	level = 1;
	sprintf(text, " < 80%% de %iA souscrits", Isousc);
	if (flevel > 80)
	{
		level = 2;
		sprintf(text, ">80%% et <90%% de %iA souscrits", Isousc);
	}
	if (level > 90)
	{
		level = 3;
		sprintf(text, ">90%% et <98%% de %iA souscrits", Isousc);
	}
	if (level > 98)
	{
		level = 3; // shouldn't it be 4 here?
		sprintf(text, ">98%% de %iA souscrits", Isousc);
	}
	return level;
}`

BR

**Comment by Marbaf** [comment]
In fact, it is worse than I thought. Tested variable in last two if statements should be flevel.

**Comment by gizmocuz** [comment]
Please submit a PR if needed
