### ISSUE TITLE
RFE: Dynamically link libstdc++, libgcc, libsqlite, liblua

### ISSUE THREAD

**Issue by dwmw2** [domoticz/domoticz#201]
I'm building domoticz for OpenWRT. On a space-constrained system it's quite important that we use dynamically linked libraries rather than statically linking our own copy.  I may do Fedora packages, and we have similar packaging requirements there for different reasons.

Obviously I can fix this with out-of-tree patches (which is easier in some ways because it can be unconditional), but it would be nicer to fix it properly so the upstream build system allows building either way. Should I work on doing it 'properly', or is that not something that would be welcomed?

**Comment by gizmocuz** [comment]
Is it then still possible that for example raspberry pi users can make a new install (sdcard image) and issue:

 mkdir domoticz
 cd domoticz
 wget http://domoticz.sourceforge.net/domoticz_linux_armv7l.tgz
 tar xvfz domoticz_linux_armv7l.tgz
 rm domoticz_linux_armv7l.tgz

to install domoticz?

Or do they now need to install dependency's ?

How about existing users with the above setup, trying to update to a new beta/stable version from the web interface, i think domoticz will just stop ?

Maybe it is possible to tweak the CMakeList.txt file to implement support for building with or without static build ? or make a #define for openWRT?

**Comment by dwmw2** [comment]
> Maybe it is possible to tweak the CMakeList.txt file to implement support for building with or without static build ? 

That's absolutely possible, and is my preferred approach. I certainly wouldn't want to _break_ the static install that you describe, and it should probably remain the default.

The reason I asked first is because there was a possibility that you _(unwisely, IMHO)_ might have said _"no, I **always** want static builds and I don't even want to **allow** people to link dynamically"_. In that case I could have just done a hackish local patch to make it link dynamically.

You don't seem to be saying that, so I'll take the time to do it properly and submit a PR which allows for building with -DUSE_STATIC_SQLITE=NO, etc. Thanks for the prompt feedback.

(Note that the pull request I've just submitted doesn't cover this; it just does some other basic fixes which are prerequisites.)

**Comment by dwmw2** [comment]
The build breakage for PR#203 with the MSVC build is noted; I'll fix it shortly (in case you get to looking at this before I fix it...)

**Comment by dwmw2** [comment]
OpenWRT covers a lot of devices, many of them _extremely_ limited. Each library might only be a few hundred KiB but that's a few hundred KiB of flash _and_ RAM, for _every_ application which statically links just a few 'small' things...

In the case of Fedora packaging, the motivation is different — there, it's not about size. The packaging guidelines require that we do not ship static copies of libraries which are provided by the system, so that we can have more confidence that (especially security) bug fixes in libraries will actually be effective everywhere.

**Comment by gizmocuz** [comment]
Maybe you could make (for now) a new CMakeList.txt for openwrt ?
