### ISSUE TITLE
RFLink and LivingColors Gen 1

### ISSUE THREAD

**Issue by Daydreamer0008** [domoticz/domoticz#2014]
I have a working RFLink with a CC2500 module.
It works, it sees my LivingColors remote when I press a button (Both in the loader and in Domoticz)

If I create a switch from it, and press on, I get the error "Error: RFLink: Error/Unknown command received!..."

(Domoticz version 3.8795 and RFlink R48)

**Comment by gizmocuz** [comment]
Probably the same as https://github.com/domoticz/domoticz/issues/2024
Please continue there, at the moment we are testing a recent patch, that could take a few days
