### ISSUE TITLE
Domoticz becomes non-responsive 2-3 times a day

### ISSUE THREAD

**Issue by obruchez** [domoticz/domoticz#2017]
Domoticz becomes non-responsive up to 2-3 times a day (i.e. the web interface, as well as the API / apps don't work anymore). I have to do a "sudo service domoticz restart" to make it responsive again.

As a workaround, I tried and added a crontab that does a preventive restart every night, but it doesn't help much.

Version: I always have the latest version (git fetch, git pull, make), but I've been experiencing this problem for months now. The current version is 3.8795.

Hardware:
- Rfxcom RFXtrx433E USB controller
- Aeon Labs Z-Wave Plus Z-Stick ZW090C GEN5 USB controller

How can I help? How can I enable detailed/trace logs?

**Comment by kottle** [comment]
I noticed the same issue, it seems we interface and API does't work, the engine still works (my internal scripts are executed). The current version is 3.8795.
My workaround is an health check script that checks every 5 minutes if API works.
File Edit Options Buffers Tools Sh-Script Help                                                                                                                                                                                                                                  

#!/bin/bash                                                                                                                                                                                                                                                                     
DATE=`date`
echo "$DATE check_domoticz" >> /home/pi/scripts/logs/check_domoticz.log
status=$(curl --silent 'http://<domoticz_ip_address>/json.htm?username=YWRtaW4=&password=QWxpY2UkMDEk' --max-time 10 )
echo "response: $status"  >> /home/pi/scripts/logs/check_domoticz.log
if [[ "$status" == *"OK"* ]]; then
    echo "OK"  >> /home/pi/scripts/logs/check_domoticz.log
else
    echo "KO"  >> /home/pi/scripts/logs/check_domoticz.log
    killall -9 domoticz
    sleep 2
    sudo service domoticz restart
fi
I hope this can help you.

About the issue It seems a race condition on CSQLHelper, this is my stack trace
(gdb) thread apply all bt

Thread 20 (Thread 0x6a53f440 (LWP 27623)):
#0  0x76c3dce8 in __pthread_cond_timedwait (cond=0x6af7c810, mutex=0x6af7c7f8, abstime=0x6a53ecdc) at pthread_cond_timedwait.c:198
#1  0x0057379c in boost::this_thread::hidden::sleep_for(timespec const&) ()
#2  0x001f7320 in sleep_milliseconds(long) ()
#3  0x004c21ac in Plugins::CPlugin::Do_Work() ()
#4  0x00571f24 in thread_proxy ()
#5  0x76c36fc4 in start_thread (arg=0x6a53f440) at pthread_create.c:335
Backtrace stopped: Cannot access memory at address 0x58ea0df8

Thread 19 (Thread 0x6ae7f440 (LWP 27622)):
#0  0x76c3dce8 in __pthread_cond_timedwait (cond=0x6af22e20, mutex=0x6af22e08, abstime=0x6ae7ecdc) at pthread_cond_timedwait.c:198
#1  0x0057379c in boost::this_thread::hidden::sleep_for(timespec const&) ()
#2  0x001f7320 in sleep_milliseconds(long) ()
#3  0x004c21ac in Plugins::CPlugin::Do_Work() ()
#4  0x00571f24 in thread_proxy ()
#5  0x76c36fc4 in start_thread (arg=0x6ae7f440) at pthread_create.c:335
Backtrace stopped: Cannot access memory at address 0x58ea0df8

Thread 18 (Thread 0x6b8ae440 (LWP 27621)):
#0  0x76c3dce8 in __pthread_cond_timedwait (cond=0x6bc75018, mutex=0x6bc75000, abstime=0x6b8adcdc) at pthread_cond_timedwait.c:198
#1  0x0057379c in boost::this_thread::hidden::sleep_for(timespec const&) ()
#2  0x001f7320 in sleep_milliseconds(long) ()
#3  0x004c21ac in Plugins::CPlugin::Do_Work() ()
#4  0x00571f24 in thread_proxy ()
#5  0x76c36fc4 in start_thread (arg=0x6b8ae440) at pthread_create.c:335
Backtrace stopped: Cannot access memory at address 0x58ea0df8

Thread 17 (Thread 0x6c6ce440 (LWP 27620)):
#0  0x76c3dce8 in __pthread_cond_timedwait (cond=0x6d87ebb8, mutex=0x6d87eba0, abstime=0x6c6cdcdc) at pthread_cond_timedwait.c:198
#1  0x0057379c in boost::this_thread::hidden::sleep_for(timespec const&) ()
#2  0x001f7320 in sleep_milliseconds(long) ()
#3  0x004c21ac in Plugins::CPlugin::Do_Work() ()
#4  0x00571f24 in thread_proxy ()
#5  0x76c36fc4 in start_thread (arg=0x6c6ce440) at pthread_create.c:335
Backtrace stopped: Cannot access memory at address 0x58ea0df8

Thread 16 (Thread 0x6cfff440 (LWP 27619)):
#0  0x76c40eec in __lll_lock_wait (futex=futex@entry=0x7dd7c4 <m_sql+148>, private=0) at lowlevellock.c:43
#1  0x76c39b78 in __GI___pthread_mutex_lock (mutex=0x7dd7c4 <m_sql+148>) at pthread_mutex_lock.c:80
#2  0x001ec4b0 in boost::mutex::lock() ()
#3  0x0024e9d0 in CSQLHelper::query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#4  0x0024ef78 in CSQLHelper::safe_query[abi:cxx11](char const*, ...) ()
---Type <return> to continue, or q <return> to quit--- 
#5  0x0024fc50 in CSQLHelper::GetPreferencesVar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#6  0x0024fdf0 in CSQLHelper::GetPreferencesVar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&) ()
#7  0x001d88d0 in CEventSystem::GetCurrentMeasurementStates() ()
#8  0x001daaac in CEventSystem::CreateBlocklyLuaState() ()
#9  0x001dc58c in CEventSystem::EvaluateBlockly(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long long) ()
#10 0x001e7278 in CEventSystem::EvaluateEvent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long long) ()
#11 0x001e8274 in CEventSystem::EvaluateEvent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#12 0x001e8558 in CEventSystem::Do_Work() ()
#13 0x00571f24 in thread_proxy ()
#14 0x76c36fc4 in start_thread (arg=0x6cfff440) at pthread_create.c:335
#15 0x76a8dc68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 15 (Thread 0x6e3ff440 (LWP 27617)):
#0  0x76c3dce8 in __pthread_cond_timedwait (cond=0x6f500960, mutex=0x6f500948, abstime=0x6e3fed3c) at pthread_cond_timedwait.c:198
#1  0x0057379c in boost::this_thread::hidden::sleep_for(timespec const&) ()
#2  0x001f72c8 in sleep_seconds(long) ()
#3  0x00415f70 in COpenWeatherMap::Do_Work() ()
#4  0x00571f24 in thread_proxy ()
#5  0x76c36fc4 in start_thread (arg=0x6e3ff440) at pthread_create.c:335
#6  0x76a8dc68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 14 (Thread 0x6ebff440 (LWP 27616)):
#0  0x76c3dce8 in __pthread_cond_timedwait (cond=0x6f500738, mutex=0x6f500720, abstime=0x6ebfed44) at pthread_cond_timedwait.c:198
#1  0x0057379c in boost::this_thread::hidden::sleep_for(timespec const&) ()
#2  0x001f72c8 in sleep_seconds(long) ()
#3  0x0041266c in CHttpPoller::Do_Work() ()
#4  0x00571f24 in thread_proxy ()
#5  0x76c36fc4 in start_thread (arg=0x6ebff440) at pthread_create.c:335
#6  0x76a8dc68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 13 (Thread 0x6f3ff440 (LWP 27615)):
#0  0x76c3dce8 in __pthread_cond_timedwait (cond=0x6f500528, mutex=0x6f500510, abstime=0x6f3fed44) at pthread_cond_timedwait.c:198
#1  0x0057379c in boost::this_thread::hidden::sleep_for(timespec const&) ()
#2  0x001f72c8 in sleep_seconds(long) ()
#3  0x0041266c in CHttpPoller::Do_Work() ()
---Type <return> to continue, or q <return> to quit---
#4  0x00571f24 in thread_proxy ()
#5  0x76c36fc4 in start_thread (arg=0x6f3ff440) at pthread_create.c:335
#6  0x76a8dc68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 12 (Thread 0x6fdff440 (LWP 27610)):
#0  0x76c3dce8 in __pthread_cond_timedwait (cond=0x7dd6f8 <m_mainworker+3768>, mutex=0x7dd6e0 <m_mainworker+3744>, abstime=0x6fdfeca4) at pthread_cond_timedwait.c:198
#1  0x0022af40 in MainWorker::Do_Work_On_Rx_Messages() ()
#2  0x00571f24 in thread_proxy ()
#3  0x76c36fc4 in start_thread (arg=0x6fdff440) at pthread_create.c:335
#4  0x76a8dc68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 11 (Thread 0x705ff440 (LWP 27609)):
#0  0x76c3dce8 in __pthread_cond_timedwait (cond=0x279f658, mutex=0x279f640, abstime=0x705febbc) at pthread_cond_timedwait.c:198
#1  0x0057379c in boost::this_thread::hidden::sleep_for(timespec const&) ()
#2  0x001f7320 in sleep_milliseconds(long) ()
#3  0x00225760 in MainWorker::Do_Work() ()
#4  0x00571f24 in thread_proxy ()
#5  0x76c36fc4 in start_thread (arg=0x705ff440) at pthread_create.c:335
#6  0x76a8dc68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 10 (Thread 0x70dff440 (LWP 27608)):
#0  0x76a8e334 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00351a00 in boost::asio::detail::epoll_reactor::run(bool, boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>&) ()
#2  0x0035250c in boost::asio::detail::task_io_service::run(boost::system::error_code&) ()
#3  0x00506368 in tcp::server::CTCPServer::Do_Work() ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 9 (Thread 0x715ff440 (LWP 27607)):
#0  0x76c40eec in __lll_lock_wait (futex=futex@entry=0x7dd7c4 <m_sql+148>, private=0) at lowlevellock.c:43
#1  0x76c39b78 in __GI___pthread_mutex_lock (mutex=0x7dd7c4 <m_sql+148>) at pthread_mutex_lock.c:80
#2  0x001ec4b0 in boost::mutex::lock() ()
#3  0x0024e9d0 in CSQLHelper::query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#4  0x0024ef78 in CSQLHelper::safe_query[abi:cxx11](char const*, ...) ()
#5  0x00243e14 in CScheduler::DeleteExpiredTimers() ()
#6  0x00244070 in CScheduler::Do_Work() ()
#7  0x00571f24 in thread_proxy ()
#8  0x76c36fc4 in start_thread (arg=0x715ff440) at pthread_create.c:335
#9  0x76a8dc68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

---Type <return> to continue, or q <return> to quit---
Thread 8 (Thread 0x727e1440 (LWP 27605)):
#0  0x76c413c4 in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x005aa9d0 in unixRead ()
#2  0x005a9fd4 in readDbPage ()
#3  0x005f67b4 in getPageNormal ()
#4  0x005f8564 in moveToChild ()
#5  0x005f9250 in sqlite3BtreeMovetoUnpacked ()
#6  0x005f9504 in handleDeferredMoveto ()
#7  0x0062e7a0 in sqlite3VdbeExec ()
#8  0x026945a8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 7 (Thread 0x72fe1440 (LWP 27604)):
#0  0x76a8e334 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00351a00 in boost::asio::detail::epoll_reactor::run(bool, boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>&) ()
#2  0x00359b94 in boost::asio::io_service::run() ()
#3  0x00571f24 in thread_proxy ()
#4  0x76c36fc4 in start_thread (arg=0x72fe1440) at pthread_create.c:335
#5  0x76a8dc68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 6 (Thread 0x737e1440 (LWP 27603)):
#0  0x76a8e334 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00351a00 in boost::asio::detail::epoll_reactor::run(bool, boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>&) ()
#2  0x0035250c in boost::asio::detail::task_io_service::run(boost::system::error_code&) ()
#3  0x0052d208 in http::server::server_base::run() ()
#4  0x00288f44 in http::server::CWebServer::Do_Work() ()
#5  0x00571f24 in thread_proxy ()
#6  0x76c36fc4 in start_thread (arg=0x737e1440) at pthread_create.c:335
#7  0x76a8dc68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 5 (Thread 0x73fe1440 (LWP 27602)):
#0  0x76a8e334 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00351a00 in boost::asio::detail::epoll_reactor::run(bool, boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>&) ()
#2  0x00359b94 in boost::asio::io_service::run() ()
#3  0x00571f24 in thread_proxy ()
#4  0x76c36fc4 in start_thread (arg=0x73fe1440) at pthread_create.c:335
#5  0x76a8dc68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 0x747e1440 (LWP 27601)):
#0  0x76c3dce8 in __pthread_cond_timedwait (cond=0x273cfe8, mutex=0x273cfd0, abstime=0x747e0b84) at pthread_cond_timedwait.c:198
---Type <return> to continue, or q <return> to quit---
#1  0x0057379c in boost::this_thread::hidden::sleep_for(timespec const&) ()
#2  0x001f7320 in sleep_milliseconds(long) ()
#3  0x003355e4 in CInfluxPush::Do_Work() ()
#4  0x00571f24 in thread_proxy ()
#5  0x76c36fc4 in start_thread (arg=0x747e1440) at pthread_create.c:335
#6  0x76a8dc68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0x75303440 (LWP 27600)):
#0  0x76c40ebc in __lll_lock_wait (futex=futex@entry=0x7dd7c4 <m_sql+148>, private=0) at lowlevellock.c:46
#1  0x76c39b78 in __GI___pthread_mutex_lock (mutex=0x7dd7c4 <m_sql+148>) at pthread_mutex_lock.c:80
#2  0x001ec4b0 in boost::mutex::lock() ()
#3  0x0024e9d0 in CSQLHelper::query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#4  0x0024ef78 in CSQLHelper::safe_query[abi:cxx11](char const*, ...) ()
#5  0x002605dc in CSQLHelper::UpdateValueInt(int, char const*, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool) ()
#6  0x002620c0 in CSQLHelper::UpdateValue(int, char const*, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool) ()
#7  0x004da4f0 in Plugins::CDevice_update(Plugins::CDevice*, _object*, _object*) ()
#8  0x75b971d0 in PyCFunction_Call () from /usr/lib/arm-linux-gnueabihf/libpython3.5m.so
#9  0x75d018f8 in PyEval_EvalFrameEx () from /usr/lib/arm-linux-gnueabihf/libpython3.5m.so
#10 0x75d00358 in PyEval_EvalFrameEx () from /usr/lib/arm-linux-gnueabihf/libpython3.5m.so
#11 0x75d00358 in PyEval_EvalFrameEx () from /usr/lib/arm-linux-gnueabihf/libpython3.5m.so
#12 0x75d81538 in ?? () from /usr/lib/arm-linux-gnueabihf/libpython3.5m.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0x75b03440 (LWP 27598)):
#0  0x76c3dce8 in __pthread_cond_timedwait (cond=0x26d9890, mutex=0x26d9878, abstime=0x75b028f4) at pthread_cond_timedwait.c:198
#1  0x0057379c in boost::this_thread::hidden::sleep_for(timespec const&) ()
#2  0x001f7320 in sleep_milliseconds(long) ()
#3  0x00262d20 in CSQLHelper::Do_Work() ()
#4  0x00571f24 in thread_proxy ()
#5  0x76c36fc4 in start_thread (arg=0x75b03440) at pthread_create.c:335
#6  0x76a8dc68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0x75f3b420 (LWP 27597)):
#0  0x76c41d10 in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x0057396c in boost::this_thread::hidden::sleep_for(timespec const&) ()
#2  0x001f72c8 in sleep_seconds(long) ()
#3  0x0018c1dc in main ()

**Comment by gizmocuz** [comment]
We are working on the issue in about reported issue
