### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [domoticz/domoticz#2018]
I guess that a different program design will be needed for your function “[signal_handler](https://github.com/domoticz/domoticz/blob/e7605b42b45c96307ef8f3e8ad6cd060b21018ce/main/domoticz.cpp#L177 "Check signal handling.")”.
- The variables “`fatal_handling`” and “`g_bStopApplication`” should [use the data type “`sig_atomic_t`”](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Description for the usage of sig_atomic_t").
- The function “[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html "Terminate a process.")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").

**Comment by gizmocuz** [comment]
This is an open source project, please submit a PR to help

**Comment by elfring** [comment]
Would you like to consider other software design options?
- [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "Wait for queued signals")
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "The self-pipe trick")
- [Signal-safe locks](https://locklessinc.com/articles/signalsafe_locks/ "Description for signal-safe locks")

**Comment by gizmocuz** [comment]
as said, please submit a PR so we can review your suggestions

**Comment by elfring** [comment]
* I imagine that the usage of the data type “`sig_atomic_t`” could be applied directly.
* The other software design options are described in some information sources. How would you like to achieve a corresponding consensus there?

**Comment by gizmocuz** [comment]
If you find a way, please submit a PR

**Comment by gizmocuz** [comment]
No reaction from OP, probably there was no way. Closing issue, feel free to open any time or do a PR
