### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [domoticz/domoticz#2019]
I would like to point out that identifiers like “[`_CCmdLine`](https://github.com/domoticz/domoticz/blob/2d1898932fcdd8ff4af8424a46f189fc50e29106/main/CmdLine.h#L124)” and “[`__HIDUSAGE_H__`](https://github.com/domoticz/domoticz/blob/494fff71685f319b25e7824684c299162b19f8c3/libusb/hidusage.h#L19)” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by gizmocuz** [comment]
these are not our code files and should be changed first by the original author.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by gizmocuz** [comment]
there is no reason for a code change as this does not influence us
Unless you can prove this behavior, please open a PR

**Comment by elfring** [comment]
It seems that this software depends on other components which contain questionable implementation details.
Would you like to improve the software situation further?

**Comment by gizmocuz** [comment]
Many open source projects depend on third party libraries of course. You could contribute to them as well, and then update our includes as well

**Comment by elfring** [comment]
* How would you like to convince the Microsoft Corporation (for example) to become more standard compliant?
* Which alternatives would you find acceptable for parsing of command lines?
