### ISSUE TITLE
Wenzhou TKB Control System type=0311, id=0304

### ISSUE THREAD

**Issue by dav76df** [domoticz/domoticz#2022]
Hi,
the zwave module wenzhou is not included in the manufacturer_specific.xml file
We can not access the configuration of this double switch
this is the message:
Wenzhou TKB Control System Unknown: type=0311, id=0304
Thank you

**Comment by gizmocuz** [comment]
Please check if this is added already to OpenZWave, it should be added there first.
We update our files from time to time from their repository
