### ISSUE TITLE
Seismic Intensity Device Request

### ISSUE THREAD

**Issue by febalci** [domoticz/domoticz#2029]
Using stable 3.8153. Getting:

OpenZWave: Value_Added: Unhandled Label: Seismic Intensity, Unit: mercalli

message in the log from Fibaro FGMS001 Motion Sensor. This sensor has a Seismic activity sensor to detect earthquakes. Since i am (and probably quite a significant Domoticz users) living in a very active earthquake zone, the use of this device is very important for us; actually it is the only reason why i bought it. Is it possible to add a device supporting the 'Seismic Activity' to support FGMS001 or any other seismic activity sensors?

**Comment by Siewert308SW** [comment]
Would love to, hope someone will jump on this.
Over here we have issues with our national gas company and drilling gas causes earthquakes.
Have several FGMS001 in and around my house and would love to monitor if a quake is occurring.

**Comment by febalci** [comment]
In zwcfg.xml, the COMMAND_CLASS_SENSOR_MULTILEVEL details are as follows:
(In Domoticz Devices, only the Temp and Lux shows up.)
```<CommandClass id="49" name="COMMAND_CLASS_SENSOR_MULTILEVEL" version="8" innif="true">
<Instance index="1" />
<Value type="decimal" genre="user" instance="1" index="1" label="Temperature" units="C" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="24.9" />
<Value type="decimal" genre="user" instance="1" index="3" label="Luminance" units="lux" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="57" />
<Value type="decimal" genre="user" instance="1" index="25" label="Seismic Intensity" units="mercalli" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0" />
<\CommandClass>```

**Comment by tlpeter** [comment]
I would like to see that one as well.

**Comment by GravityRZ** [comment]
is somebody paying attention to this wish.

i would like to have this as well. should not be that difficult to make.
i is just like the pir sensor. instead of showing it on/off in the icon just let is display a value

**Comment by gizmocuz** [comment]
I got a Fibaro FGMS001 Motion Sensor, but i never received a 'Seismic Intensity' value

@GravityRZ , please make a pull request for this

**Comment by febalci** [comment]
Seismic Intensity device pops up when you enable "24-Tamper-Operating" mode from "Tamper only" to "Tamper and Earthquake detector". With the current beta there's no more "OpenZWave: Value_Added: Unhandled Label: Seismic Intensity, Unit: mercalli" error, but device is not created also. I can see the earthquake mercalli in the OZW control panel and it works according to the vibrations sensed.

**Comment by Siewert308SW** [comment]
> 
> 
> Seismic Intensity device pops up when you enable "24-Tamper-Operating" mode from "Tamper only" to "Tamper and Earthquake detector". With the current beta there's no more "OpenZWave: Value_Added: Unhandled Label: Seismic Intensity, Unit: mercalli" error, but device is not created also. I can see the earthquake mercalli in the OZW control panel and it works according to the vibrations sensed.

Don't know but are you sure?
I never ever enabled 24 and still all my motion sensors are called with a Unhandled Label: Seismic Intensity warning.

**Comment by gizmocuz** [comment]
have you enabled accept new devices in settings ?

**Comment by Siewert308SW** [comment]
@gizmocuz ofcourse ;-)

**Comment by waltervl** [comment]
Implemented with https://github.com/domoticz/domoticz/commit/4bebb985dd213010e73f78174db7a40345af866e
