### ISSUE TITLE
settings page gives Bad Request when server started with a -webroot

### ISSUE THREAD

**Issue by dannybloe** [domoticz/domoticz#2037]
If you start the domoticz sevice with -webroot then applying settings in the gui will give you a bad request.

**Comment by gordonb3** [comment]
I think this is solved now?

**Comment by gizmocuz** [comment]
Tested it, there seems to be no issue anymore. closing issue. Feel free to re-open when you still have issues.
One thing i noticed is that you specify 'test' as webroot, you can not navigate to http://127.0.0.1:8080/test , you have to add a trailing slash
