### ISSUE TITLE
"Executing script" base directory escape

### ISSUE THREAD

**Issue by jbriard** [domoticz/domoticz#2038]
Hello,

When I set-up a "On Action" script on a switch for exemple, Domoticz think the base directory is _/[domoticz_home]/scripts_   .

If you put _script://home/domoticz-script/timers/test.sh_ in the "On Action" domoticz will try to run _/[domoticz_home]/scripts/domoticz-script/timers/test.sh_ and failed.

this is perfect. I have to put my script in /[domoticz_home]/scripts .

But if instead of putting my script in the /[domoticz_home]/scripts folder I change the "On Action" script path with _script://../../home/domoticz-script/timers/test.sh_, domoticz can execute code outside the base directory and this is bad.

I think the use of "../" should not be allowed to prevent this behaviour.

V3.8798

Regards

**Comment by gizmocuz** [comment]
Thanks... not such a problem as you need to have access to this location before i suppose, but it should now be prevented with this commit
https://github.com/domoticz/domoticz/commit/219d6c3fe0f7e59c73c30b4a6e30c3608b40394a

**Comment by bizziebis** [comment]
It also gets bad when you try this:

script:///bin/touch /test.log | touch /test2.log

And even worse:
script:// | touch /test.log

Now change that last command to | rm -rf * / and count your tears.

Don't get me wrong. I like the fact that I can trigger remote scripts/commands. But it's easy to abuse, and hard to fix I think.
