### ISSUE TITLE
Language files

### ISSUE THREAD

**Issue by Rafik89** [domoticz/domoticz#2039]
Please upgrade language files from the site
https://www.transifex.com/domoticz/domoticz/
I translated Polish.

**Comment by febalci** [comment]
Also done; Turkish

**Comment by Rafik89** [comment]
Not yet updated ...

**Comment by gizmocuz** [comment]
Thanks! I updated the translation files, should be in the new beta shortly (within two hours)

**Comment by Rafik89** [comment]
again, the translations are old
![screenshot](https://user-images.githubusercontent.com/1193307/35472916-30a772c8-0378-11e8-9f00-33ca13d71ef3.png)

**Comment by gizmocuz** [comment]
AGAIN you could send me a PM on the forum! This is done manually
