### ISSUE TITLE
Security Panel Security issue

### ISSUE THREAD

**Issue by Hexagon** [domoticz/domoticz#2040]
Version: 3.8797
Build Hash: 590d813
Compile Date: 2017-12-30 04:23:16

Conditions:
1. Server down.
2. Enter password in security panel, try to arm/disarm (wall mount panel, opened before server went down).
3. Panel will show "NO CONNECT"
4. Password will be left readable in DOM until reconnected or refreshed.

**Comment by Hexagon** [comment]
Will be fixed by http://domoticz.com/forum/viewtopic.php?f=31&t=21267

**Comment by gizmocuz** [comment]
Closed by merging PR
