### ISSUE TITLE
operate z-wave device hangs domoticz

### ISSUE THREAD

**Issue by rrozema** [domoticz/domoticz#2046]
Since beta 3.8794 my domoticz became unresponsive as soon as I operated one of my z-wave devices. I've been getting and compiling different commits of the development branch and 5db4eec is the last commit that lets me operate one of my switches. From commit 470448c "Add support for Twilight and day length (#1998)" on domoticz becomes unresponsive when any of my z-wave devices is operated.

Raspberry pi 3, Jessie (latest updates installed), razberry gpio board as controller.

**Comment by Siewert308SW** [comment]
Seems that #1998  creates more problems then expected.
But as far as i know #2008 should fix it, haven't tried it yet but god knows why the fix is still pending after 19days.
Tomorrow i compile a version without #1998, and one with the pull request #2008.

**Comment by rrozema** [comment]
I just loaded my old database into my working installation and the same issue re-surfaced without having the code changed. So I'm going to close this one myself, as it is not (only) the source changes in this release that is causing my problems.

**Comment by gordonb3** [comment]
@Siewert308SW That doesn't make sense. #2008 is complementary to #1998, so you won't even be able to apply it.

**Comment by Siewert308SW** [comment]
@gordonb3 i see, was convinced it was a fix for the current timer issue. My bad.
