### ISSUE TITLE
Persistent XSS in webserver found

### ISSUE THREAD

**Issue by Jarthianur** [domoticz/domoticz#2048]
### Summary

Webui (e.g. add Hardware section) allows input with HTML/JS content. These special characters are not escaped and directly stored/retrieved from sqlite-db, hence causing a persistent XSS vulnerability.

### Affected version(s)

Actual master branch (2018-01-08), probably also previous versions.

+ Version: V3.8799 and earlier
+ Build date: 2018-01-06 01:51:32

### Steps to reproduce:

+ clone repo
+ build from master branch
+ run with `./domoticz`
+ access webserver via browser on localhost:8080
+ Under Setup->Hardware add a arbitrary device and type in the "Name" field: `<script>alert('XSS');</script>`

From then on, any user accessing this page will execute this JS. There may be other pages/sections affected as well.

### Patch

Escape/Encode all HTML specialchars when stored/retrieved from the DB. This should be done server-side. We will try to open a PR for this issue.

<img width="800" alt="domoticz_xss_proof" src="https://user-images.githubusercontent.com/18551061/34669421-e2965abe-f471-11e7-8ec5-0aa3d1db3c29.png">

**Comment by Hexagon** [comment]
I would suggest that only the api response (json) is escaped/htmlencoded. No need to process before database, in fact this could raise other issues.

One way would be to wrap each response member in an type enforcing function. Like:

`root["delaySecods"] = safeJsonInt(delaySeconds); root["deviceName"] = safeJsonString(device->name);` where safeJsonInt converts to a pure integer, then back to string, safeJsonString htmlencodes etc.
  
(There is of course no need to wrap pure c++ int/floats etc., only if they are stored and as strings in the database)

**Comment by gizmocuz** [comment]
Thanks for the report! Did you open a PR ?

**Comment by gizmocuz** [comment]
It seems to wrong when it's displayed in a lot of elements.
Hope it's done now in
https://github.com/domoticz/domoticz/commit/a3282d10c41fa43e65cb20ffbd02216a1133e9ea

**Comment by Jarthianur** [comment]
Sorry, I had some time off....

No I didn't open a PR yet. To be honest we haven't found the exact place where in the code the 'print-to-client' takes place and where exactly to apply the fix. I mean, this codebase isn't that small and there are many distributed lines of code involved into the WebServer stuff. But now we can see, hopefully all, those places.

 I've looked into the safeHtml function. Filtering out script-tags is at least a good step, but not enough. There are many ways of injecting JS left, through styles etc. I would recommend to filter special HTML characters at all, like brackets (<>) and so on, as it's done in php's htmlspecialchars or whatever.
This would be then a real "safe"-HTML function.

We will open a PR for that this week.

**Comment by gizmocuz** [comment]
Thanks... yes what i did is a small step in the right direction... Please feel free to modify the code and make a PR

**Comment by Jarthianur** [comment]
Done in this [PR](https://github.com/domoticz/domoticz/pull/2105).
