### ISSUE TITLE
HTML5 appcache vs. gzipping

### ISSUE THREAD

**Issue by Hexagon** [domoticz/domoticz#2050]
In my opinion, either appcache, gzipping of sources or both should be removed.

I see no point in using appcache, as all major browsers cache static assets by default. Plus that appcache is primarily for making a web application available when the server is down. Maybe keep appcache only for the offline-page?

Gzipping of sources (js files etc) destroys version history. IF compression is to be used, it should be done automatically by the server while serving files.

Any thoughts? I can make a pull request.

**Comment by Hexagon** [comment]
Below is a normal refresh before and after disabling appcache plus unzipping all compressed js. The difference is within the margin of ranomness :)

![Before and after disabling caching and compression](https://56k.guru/r/beforeafter.png)

**Comment by koenkooi** [comment]
Personally, I think if gzip is used, it should be done by the buildsystem during 'make install', not on the fly at runtime. When using domoticz on things like raspberry pi class hardware the on-the-fly gzipping adds a *lot* of overhead.

**Comment by gizmocuz** [comment]
We know, discussed before, on the todo list, gzipping on build
