### ISSUE TITLE
MySensors blinds are not working properly

### ISSUE THREAD

**Issue by gryzli133** [domoticz/domoticz#2053]
I'm working on RollerShutter controller using MySensors. Everything is working fine as a Dimmer, but it would be better to use Blinds widget in Domoticz.

The my sensors library use for Blinds S_COVER Presentation Sub-Type:

Type        |   Value |          Comment                  |                    Variables
S_COVER |      5     | Window covers or shades  | V_UP, V_DOWN,V_STOP,V_PERCENTAGE

The percentage is working fine, but the buttons not. MySensors gateway receive message V_Status:

Type         |   Value |          Comment                    |                    Used by
V_STATUS |      2     |    Binary status. 0=off 1=on | S_LIGHT, S_DIMMER, S_SPRINKLER, S_HVAC, S_HEATER

Instead of V_UP, V_DOWN,V_STOP:

Type         |   Value |          Comment                    |                    Used by
V_UP        |     29    |     Window covering. Up.     |                  S_COVER
V_DOWN |     30    |   Window covering. Down.   |                 S_COVER
V_STOP    |     31    |    Window covering. Stop.    |                 S_COVER

The percentage is working OK using:
Type                   |   Value |          Comment                     |       Used by
V_PERCENTAGE  |     3     | Percentage value. 0-100(%)   |    S_DIMMER

It would also good to have a Domoticz Widget to support 3 button (UP-STOP-DOWN) + percentage.
Would it be possible to get such a widget with this functionality:

Button pressed - send TRUE (1) in the message to gateway and backlight the button. Press another button or percentage bar, then unlight that button. It would very nice to be able to work the button in two-way communication - if Gateway send TRUE (1) for button, then backlight it, when come FALSE (0) then unlight it. Internal check, if another button is backlighted, then unlight it first.
Slider pressed - send actual slider value as setpoint. Then display on slider the feedback value.

Actually it could work as a 3 light switches (internally interlocked with each other - only one can be active at a time) and dimmer bar. But at the moment using 4 widgets to control one blind would take just to much place on my dashboard - I have 25 blinds at home...

Thank you in advance! :)

PS: here some details about the data types:
https://media.readthedocs.org/pdf/mysensors/latest/mysensors.pdf
and actual library header:
https://github.com/mysensors/MySensors/blob/master/core/MyMessage.h

**Comment by tmaster21** [comment]
Why do you close this if it's not corrected yet.?

percentage bar don't work
status it's always closed or stopped..

**Comment by slarti42** [comment]
I just spent 4 hours "fixing" a mysensors S_COVER node because the percentage wouldn't show in domoticz when I changed it from a physical switch. Turns out domoticz was to blame here. The node reports V_PERCENTAGE correctly but domoticz just happily says "On" or "Off" for that blinds_percentage-device. Anyone have any idea where to look in the source?

**Comment by waltervl** [comment]
Still an issue?
