### ISSUE TITLE
Timers stopped working on stable 3.8153 without a reason since 14/01/2018!

### ISSUE THREAD

**Issue by sammyke007** [domoticz/domoticz#2066]
Running 3.8153 stable for a couple of months. Yesterday 14/01/2018 all of my timers stopped working? I changed or added nothing? Seems I have to go beta now :-(

They were working fine everyday and now it stopped working without a reason?

I've got timers running before/after sunset/sunrise, on time, after ... and none of them work anymore all off a sudden...

**Comment by odutille** [comment]
Hello

I'm on stable also (raspberry)  and have the same issue with "On Time" timers.

I've also tested on MacOs (V3.8153 Build Hash: 494fff7), and found out that "**On Time**" timers do not work (they just don't trigger), however "**Fixed Date/Time**" timers do work - I see the corresponding line in the logs and the state of the virtual switch is indeed updated.

`2018-01-16 13:50:01.696  Schedule item started! Name: calendrier chauffe, Type: Fixed Date/Time, DevID: 5, Time: 2018-01-16 13:50:01`
`2018-01-16 13:50:01.704  (Dummy hardware) Lighting 1 (calendrier chauffe)`

Is it the same for you ?

**Comment by sammyke007** [comment]
I solved it!
My Domoticz is running on a Synology and the taskmanager (crontab) was writing a logfile to a folder filled with +10.000 log files. After removing this folder and after disabling the Synology taskmanager logging, it worked again!
