### ISSUE TITLE
ZWave battery-status out of sync

### ISSUE THREAD

**Issue by digdug3** [domoticz/domoticz#2068]
Somehow it takes more than a week to get all battery-statuses on the same Zwave node to get the same value.

Would it be possible to sync the battery level with OpenZwave during a nightly Z-Wave heal or sync the battery level across all devices on the same Z-Wave node ID?

See: http://www.domoticz.com/forum/viewtopic.php?f=6&t=18781

**Comment by Olifant1990** [comment]
The same problem is this:
I have a smart P1 meter in my home, which shows electricity usage and my gas usage.
On peak hours and off peak hours have a different device.
When I am using power during on peak hours, my off peak meter shows "timeout". But, as these two devices are devices from the same Z-Wave node, you can say it is still receiving updates and active.
Same with battery status for different devices from the same node

**Comment by waltervl** [comment]
Closing this old issue. OpenZwave is deprecated and succeeded by ZwavJS2MQTT https://www.domoticz.com/wiki/ZwaveJS2MQTT
