### ISSUE TITLE
Sunrise is 07:60 ?

### ISSUE THREAD

**Issue by tarkan123** [domoticz/domoticz#2070]
My sunrise seems to be 07:60  (It should be 08:00).

Running Beta v3.8805

Section of log showing this -

2018-01-15 00:00:01.109  Sunrise: 07:60:00 SunSet: 16:20:00
2018-01-15 00:00:01.110  Day length: 08:20:00 Sun at south: 12:09:00
2018-01-15 00:00:01.110  Civil twilight start: 07:21:00 Civil twilight end: 16:58:00
2018-01-15 00:00:01.110  Nautical twilight start: 06:39:00 Nautical twilight end: 17:40:00
2018-01-15 00:00:01.110  Astronomical twilight start: 05:59:00 Astronomical twilight end: 18:20:00

Screenshot showing sunrise and sunset times -

![capture](https://user-images.githubusercontent.com/29799041/34951177-4f15a528-fa0d-11e7-89a5-4f4affacb15c.JPG)

**Comment by jjalling** [comment]
Hi tarkan123, are you willing to post your coordinates from domoticz? If you don't want to disclose them on github, you can send them in a private message - I couldn't reproduce the error when I had a look earlier today.
BR Jonas

**Comment by tarkan123** [comment]
I did not want to post my exact location, and anyhow my sunrise today has changed to 07:59

I had a play around and can get a sunrise of 07:60  using  Lat 51.0  and Lon -1.0

**Comment by jjalling** [comment]
Thats totally understandable. I can't get it to show 7:60 when using the coordinates you posted. What hardware are you running domoticz on? I'm using a Xeon server myself.
BR Jonas

**Comment by tarkan123** [comment]
It is pretty plain - RPi3, Stretch o/s., RF-Link - nothing different than majority of other Domoticz users!!

I am running dzvent version of the Solar script  ( http://www.domoticz.com/wiki/Real-time_solar_data_without_any_hardware_sensor_:_azimuth,_Altitude,_Lux_sensor...) Not sure if this has the possiblity of changing anything in terms of the system sunrise/sunset times !?!?

Bizarre !

**Comment by jjalling** [comment]
Nah, i'm pretty sure it's because of the ARM, as I don't see it on x86 - i'll fire up a rpi3 later today, and see if i can provoke the error.

/Jonas

**Comment by gizmocuz** [comment]
Did this happen again ? I know there have been some recent changes in the sunrise/set code that might have caused this

**Comment by tarkan123** [comment]
Yes the bug is still there.

Running beta v3.8834  and setting the location as  Lat 45.9 / long -0.09   =  sunrise at 07:27 ,  sunset at 16:60


![capture](https://user-images.githubusercontent.com/29799041/35481681-27ffc6cc-0420-11e8-9754-c73fdd5e7656.JPG)

**Comment by tarkan123** [comment]
Update : it seems the problem is related to rounding up/down,  in the above example if I change the Lat to 45.6   then sunset becomes 17:00,  but at Lat to 45.9 it becomes 16:60.

**Comment by gizmocuz** [comment]
Found the issue, will be solved in the upcoming beta version

**Comment by tarkan123** [comment]
Seen your commits - rounding issue in the formula.

**Comment by gizmocuz** [comment]
Yep! Must be it... ;)
