### ISSUE TITLE
Domoticz Beta (plugin system) - python3.5* and libpython3.5* compatibility 

### ISSUE THREAD

**Issue by Siewert308SW** [domoticz/domoticz#2073]
Don't how to exactly describe it.
But after some reverse engineering and user reports as seen here: https://www.domoticz.com/forum/viewtopic.php?f=65&t=21379&p=166704#p166704 we found out that at least Domoticz Beta (plugin system) isn't compatible with python3.5* and libpython3.5*.
Users who upgrade their packages to 3.5 experience crashes in their plugin system.
Also reports says and experienced it my own when reverting back to python3.4* and libpython3.4* the issue is over.
Don't know if it's known issue?

**Comment by SargonofAssyria** [comment]
On my production and slave system I am using Python version 3.4.2 and still having crashes with the Python plugin system. Both domoticz V3.8807 beta.
On a TEST system with python 3.5.3 I have one python plugin (buienradar) with Domoticz V3.8153 (stable) I have no issues at all. Domoticz is running more than 14 days without a problem.
So I think it should be something else.

**Comment by flatsiedatsie** [comment]
The thread mentioned also has a user that was on 3.4.2

**Comment by Siewert308SW** [comment]
true.
If i'm right then he had python 3.5 while libpython was 3.4 or vice versa.
 Can't have a look right now, sorry.
Yesterday i tried to reproduce, both packages on Stretch chrash while Jessie did run but was stable.

**Comment by dnpwwo** [comment]
I run Python 3.5.3 on a pi3 Stretch box with 8 plugins running and it ran for 33 days before I restarted to upgrade it.

Was building from source though.

**Comment by flatsiedatsie** [comment]
I am running beta on a fresh install of Dietpi with Python 3.5.x without problems.

**Comment by Siewert308SW** [comment]
@dnpwwo 
Took a dive and found a treasure.
I know those who are suffering issues with new OS builds have to install libssl1.0.0
Today i compile the latest beta and domoticz crashes with a segmentation fault.
So i installed (jessie rpi3) sudo apt-get install libssl1.0.0-dbg and voila, domoticz is running.
Even plugins which caused the crash are running...
https://www.domoticz.com/forum/viewtopic.php?t=17531

**Comment by gizmocuz** [comment]
Do you also have issues when you use the pre-compiled version ? That is, when you install it via the 'sudo' method ? (see our download page)
(Why don't you use stretch bdw?)

**Comment by Siewert308SW** [comment]
Sorry for my late reply @gizmocuz ,
But didn't know how to give a proper reply on this one.
Still don't know so sorry if it sounds rude.
English aint my best language to express my self and it's even harder on technical issues.
So is do apologize it sounds rude or arrogant.
But i ask my self if i really should answer this one. "(Why don't you use stretch bdw?)"

Let me say it this way.
- Latest Jessie and Stable release aren't compatible anymore due to changes in the OS at the latest repo update.
- Jessie and Beta do work and is stable with working plugins
- Stretch and Stable is a no go, Plugin System as by many at the forum reported crash
- Stretch and Beta is a complete disaster and unstable, rolling back Python version do make it stable.
Many times reported but almost, almost everyone involved just reply with "no issues here, you fault"

Take for example the latest fixed memory leak, no need to say more.
So my answer to my reported issue and your questing who not Stretch.
It's a no go, as it is completely instable from the end user perspective.
You guys as devs no what to do and where to look.

I would suggest you guys take a look at those reports.
Flash stable and beta pre compiled binary and also compile them on latest Jessie and Stretch.
You'll see what we mean...

Say it again, i aint intend to be rude...

**Comment by rwaaren** [comment]
Just as dnpwwo, I also build from source because ./updatebeta still results in a fatal signal 11 just after the start of the plugin system.
Is there any information about my system that can help the developers to get to the root cause ?

**Comment by heggink** [comment]
Build from source on my pi3 makes python3.5 work but then the Nest plugin breaks :-( (error login). So the official beta has a working Nest plugin but no support for p3.5 and the compile has a working p3.5 but a broken Nest plugin. Both call themselves version 8873 Weird...

**Comment by heggink** [comment]
Anyone building from source with a working Nest thermostat?

**Comment by Siewert308SW** [comment]
@heggink 
Old or new Nest hardware implantation?
On Stretch i even can't build anything from source, don't know why.
On Jessie i can compile without issues and Nest (old one) works perfect.
Haven't test/used new Nest implantation.

**Comment by heggink** [comment]
Stretch & old. I cannot get the new to work. I can build Stretch fine but then, as indicated, Nest breaks hence my interest in finding out if the likes of @rwaaren or @dnpwwo have the old Nest plugin and have compiled successfully. I hate to downgrade python to 3.4 as I don't want to uninstall fail2ban (which depends on 3.5 on stretch).

**Comment by rwaaren** [comment]
Sorry but no,  I don't have a Nest plugin ( I use evohome)

**Comment by flatsiedatsie** [comment]
does this help narrow it down?

https://www.domoticz.com/forum/viewtopic.php?f=6&t=22012

**Comment by heggink** [comment]
Just did a simple test: take a working python plugin (ie check it doesn't crash domoticz on use, in my case bt-presence), add "import urllib.request", restart domoticz and invoke the plugin (add in HW, add device).

Conclusion: lust adding **import urllib.request** crashes domoticz. AFAICT, this issue is urllib specific. Doing a simple diff between the python3.4/urllib and python3.5 shows a bunch of differences. Question then is whether urllib is to blame or another dependency (e.g. libssl).

**Comment by kofec** [comment]
I agree with comment provided @heggink

**Comment by gizmocuz** [comment]
would be great if this crash could be catched so domoticz does not crash and a error log can be shown..

**Comment by heggink** [comment]
@gizmocuz apologies for hijacking this thread for a related question: since 3.4 works and 3.5.3 crashes, I tried 3.6.4 (git pull, compile, install). install works fine (python3 --version shows 3.6.4) but domoticz keeps loading 3.5.3 and ignores 3.6.4. Any idea? Wanted to check if the issue is with 3.5 alone. I did read that domoticz nowadays requires python-dev which installs a bunch of files that are not present after make install of 3.6.4.

**Comment by FilipDem** [comment]
Had more or less the same but with Python 3.4 and 3.5. I configured ("alternatives") 3.4 as default python(3) version. However in every case Domoticz still loads 3.5...

**Comment by heggink** [comment]
All: is python 3.5.3 still a cause for crashing the latest betas or has this issue been resolved?

**Comment by dnpwwo** [comment]
@heggink,

My understanding is that this is a build problem rather than a Python3 problem.

I believe the betas are built on the Jessie OS and those don't seem to work with Python 3.5 on Stretch (probably the lib ssl thing).  Betas built from source on the Stretch OS work with Python 3.5.x just fine (my home runs on that).  If you want to try it yourself have a look at this thread (https://github.com/domoticz/domoticz/issues/1891#issuecomment-395661157) and pull a Stretch built image to try.

Stretch has been out for nearly 12 months, perhaps now is the time to make that the supported OS on Pi and build the betas on it?

**Comment by gizmocuz** [comment]
@dnpwwo , the build systems are 'Stretch' and using python 3.5.3

**Comment by gizmocuz** [comment]
> Debian GNU/Linux 9 \n \l
> 
> PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
> NAME="Debian GNU/Linux"
> VERSION_ID="9"
> VERSION="9 (stretch)"
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
>

**Comment by gizmocuz** [comment]
I guess some people have to update to stretch and use the latest python, but best to wait for the upcoming stable build
If you do want to update to stretch now, you have to update to the beta version with:

cd domoticz
./updatebeta

**Comment by heggink** [comment]
I'll give this a test later on my test pi to see if there are still issues with jessie/py353/domo-updatebeta. Let's see. Hope I can get it done before my travel to Sweden on Sunday.

**Comment by gizmocuz** [comment]
@heggink , you have to use stretch

**Comment by gizmocuz** [comment]
@heggink , or put a new SD card in, install latest raspbian (stretch), next use the sudo command to install domoticz (see our main website) ----> domoticz will fail to run,
next issue

cd domoticz
./updatebeta

now it should work

**Comment by heggink** [comment]
@gizmocuz already using stretch for quite a while:
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
uname -a: Linux raspi 4.14.27-v7+ #1100 SMP Fri Mar 16 13:51:48 GMT 2018 armv7l GNU/Linux
python3 --version: Python 3.5.3

just did an updatebeta. Started domoticz by hand, added life360 puthon plugin that uses urllib. Immediately leads to a segmentation fault.

The net: this issue is not resolved and agree with @dnpwwo that is resolved by compiling by hand ie a build issue of some sort (SLL related?).

Would be nice if this is addressed as part of the next stable.

**Comment by heggink** [comment]
```
sudo ./domoticz  -www 8123 -verbose
2018-06-09 12:18:37.355  Status: Domoticz V3.9611 (c)2012-2018 GizMoCuz
2018-06-09 12:18:37.356  Status: Build Hash: 92f39671, Date: 2018-06-09 09:59:16
2018-06-09 12:18:37.357  Status: Startup Path: /home/pi/domoticz/
2018-06-09 12:18:37.392  Sunrise: 05:16:00 SunSet: 21:59:00
2018-06-09 12:18:37.392  Day length: 16:43:00 Sun at south: 13:05:00
2018-06-09 12:18:37.392  Civil twilight start: 04:27:00 Civil twilight end: 22:48:00
2018-06-09 12:18:37.392  Nautical twilight start: 03:08:00 Nautical twilight end: 00:07:00
2018-06-09 12:18:37.392  There is no astronomical twilight in the space of 24 hours
2018-06-09 12:18:37.392  Status: EventSystem: reset all events...
2018-06-09 12:18:37.533  Status: PluginSystem: Started, Python version '3.5.3'.
2018-06-09 12:18:37.542  Active notification Subsystems: (0/14)
2018-06-09 12:18:37.544  Status: WebServer(HTTP) started on address: 0.0.0.0 with port 8123
2018-06-09 12:18:37.553  Status: WebServer(SSL) started on address: 0.0.0.0 with port 443
2018-06-09 12:18:37.556  Status: Proxymanager started.
2018-06-09 12:18:37.558  Starting shared server on: 0.0.0.0:6144
2018-06-09 12:18:37.558  Status: TCPServer: shared server started...
2018-06-09 12:18:37.558  Status: RxQueue: queue worker started...
2018-06-09 12:18:39.561  Status: Hardware Monitor: Started
2018-06-09 12:18:39.577  Status: EventSystem: reset all events...
2018-06-09 12:18:39.578  Status: EventSystem: reset all device statuses...
2018-06-09 12:18:39.756  Status: Python EventSystem: Initalizing event module.
2018-06-09 12:18:39.757  Status: EventSystem: Started
2018-06-09 12:18:39.757  Status: EventSystem: Queue thread started...
2018-06-09 12:18:39.894  Status: PluginSystem: Entering work loop.
2018-06-09 12:18:53.013  Status: Incoming connection from: 192.168.1.112
2018-06-09 12:21:07.382  Status: (L360) Started.
Segmentation fault

```

**Comment by gizmocuz** [comment]
@heggink , i think there is a miss communication.
Anyways, there are two topics about this now, and i find the most interesting comment here:
https://github.com/domoticz/domoticz/issues/1891#issuecomment-395953300

**Comment by heggink** [comment]
Indeed. Hadn't seen that one. thx! Can this one then be closed?

**Comment by gizmocuz** [comment]
I think we can... it's about the same problem... let's continue there
