### ISSUE TITLE
Feature request: mobile devices presence detection

### ISSUE THREAD

**Issue by flatsiedatsie** [domoticz/domoticz#2080]
Now that Domoticz has a Mobile Devices page, it seems it would only be a small step to incorporate presence detection as a default feature?

There are numerous scripts and plugins that aim to do this. So yes, there are options. But it also means that this is a much requested function, and that making it a default feature could be something that a lot of users would enjoy.

**Comment by ghost** [comment]
The already present "System Alive Checker (Ping)" does it for me ;)

**Comment by xztraz** [comment]
http://www.domoticz.com/wiki/System_Alive_Checker_(Ping)

**Comment by xztraz** [comment]
You also have the geofence feature in the Domoticz mobile app to use more specific locations than just your wifi/lan.
