### ISSUE TITLE
Is there a issue in cmakelist or travis.yml when building? Z-Wave issue solved, hopefully 

### ISSUE THREAD

**Issue by Siewert308SW** [domoticz/domoticz#2088]
@gizmocuz 
Due to the latest Z-Wave timeout error reports i did some searching.
I also suffered the issue that after reboots some nodes where declared dead, timeouts or not connected while the still reported their status if triggered.

In my search i found something interesting.
Had a look into travis.yml
Where i found some info which i executed manually before compiling.

At first i found and installed packages in travis which aren't installed automatically or mentioned anywhere.
- g++-6
- cmake-data
- zlib1g-dev
also installed libssl1.0.0-dbg to overcome the segmantion fault in plugin system.

After that i found the following in travis.yml and executed it manually.

```
cd open-zwave-read-only
wget http://www.domoticz.com/domo.patch
patch -p1 < domo.patch
make
cd..

cd domoticz
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_LIBRARY_PATH=open-zwave-read-only
CONF_SWAPFILE=1024
make
```
When done rebooted and voila...
No more timeouts or other issues.
I try to look if there is a issue but can't find it in the cmaklist or anything else.
But it's strange when conduction it manually the issue resolves.

edit:
Also post my reproduce guide in the actual thread to see if they get the same results.
https://www.domoticz.com/forum/viewtopic.php?f=6&t=21334&p=167806#p167806

**Comment by gizmocuz** [comment]
Hi!

Not sure i understand, do you have a problem with the travis builds ?
Because it looks you are compiling for a raspberry ? (CONF_SWAPFILE)

What hardware/platform/software do you use ?

The patch is needed for the Scene command class

Travis builds for ubuntu 32/64 bit, not for the raspberry

**Comment by gizmocuz** [comment]
On the raspberry build systems this patch is also applied
