### ISSUE TITLE
Domoticz crashes when python plugin calls Devices[x].Update()

### ISSUE THREAD

**Issue by teeminus** [domoticz/domoticz#2092]
I experienced a crash when my python plugin calls Devices[x].Update(__nvalue__, __svalue__) instead of Devices[x].Update(nValue = __nvalue__, sValue = __svalue__). I attached a demo plugin which will trigger the crash when uncommenting line 16. [plugin.txt] https://github.com/domoticz/domoticz/files/1667162/plugin.txt)

I am using the following setup:
Domoticz V3.8846, Build Hash: 7ad6a383, Date: 2018-01-25 08:53:23
Python 3.5.3
Linux debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
Debian GNU/Linux 9.1 (stretch)

Backtrace: [backtrace.txt](https://github.com/domoticz/domoticz/files/1667166/backtrace.txt)

**Comment by teeminus** [comment]
Problem might be related to #2073

**Comment by dnpwwo** [comment]
Actually problem is related to [#2071](https://github.com/domoticz/domoticz/commit/29ea5a9e58d486ed91f55cf7ba6a0ecf452dc325#diff-e9f6e9faf637f943546c5e0acc50bb1c).

Support for positional parameters was broken when some additional parameters were added and some behaviour was changed.  I've pushed a change to restore functionality.

Thanks for the script BTW, much easier to debug things when you can provoke the problem :)

**Comment by teeminus** [comment]
Crash seems to be fixed now .Thanks for your fast response :-)
