### ISSUE TITLE
Update python event handler default code

### ISSUE THREAD

**Issue by teeminus** [domoticz/domoticz#2097]
The current default event handler code when creating a new python plugin does not work. This is because of two reasons (as far as I noticed):
1) The variables defined by the domoticz.py (scripts/python/domoticz.py) are not present
     * changed_device: the current device that changed (object of Device)
     * changed_device_name: name of current device (same as changed_device.name)
     * is_daytime: boolean, true when it is is daytime
     * is_nighttime: same for the night
     * sunrise_in_minutes: integer
     * sunset_in_minutes: integer
     * user_variables: dictionary from string to value
2) The domoticz.log(message_type, message_body) function is broken. Fixing this problem would break the DomoticzEvents.Log() function so a new function must be defined.

I would recomment to remove the domoticz.py helper and replace the default python plugin code with the code from the following file: domoticz/scripts/python/script_device_demo.py

**Comment by emontnemery** [comment]
What is "default python plugin code"?
In which way is domoticz.log broken?

**Comment by teeminus** [comment]
The default code I refere to is the code you get presented, when you create a new python event script from the web interface.

When you create a new python event script from the web interface, the script does not work. Here is the error log (printed using the code from pull request #2139):
`2018-02-22 19:31:24.635 Error: EventSystem: Failed to execute python event script "default"`
`2018-02-22 19:31:24.635 Error: EventSystem: Traceback (most recent call last):`
`2018-02-22 19:31:24.635 Error: EventSystem: File "", line 67, in`
`2018-02-22 19:31:24.635 Error: EventSystem: File "/opt/domoticz/scripts/python/domoticz.py", line 42, in log`
`2018-02-22 19:31:24.635 Error: EventSystem: domoticz_.log(0, " ".join([str(k) for k in args]))`
`2018-02-22 19:31:24.635 Error: EventSystem: AttributeError: module 'DomoticzEvents' has no attribute 'log'`

**Comment by gizmocuz** [comment]
This has been quite a long open issue, is this still valid?

**Comment by gizmocuz** [comment]
There have been no feedback from the OP since 22th February, i guess it's not an issue anymore ?
Closing topic, feel free to re-open when needed

**Comment by charger** [comment]
As a newbie user, I try to create Python script, see default file which said to use `domoticz.log`.
After saving the script I got `EventSystem: AttributeError: module 'DomoticzEvents' has no attribute 'log'`
So this problem still exists.
How should I write to log from `time` `Python` script?

**Comment by gizmocuz** [comment]
@charger , that has nothing to do with this, please use our forum!

**Comment by Gustry** [comment]
IMHO, this issue is still valid in the new stable release. The default python code provided in Domoticz is broken. I have the same python error while saving the default code. Logging is not possible.

**Comment by charger** [comment]
I found that logging is possible with
```
import DomoticzEvents as DE
DE.Log("Hi Domoticz!")
```

But `EventSystem: NameError: name 'changed_device' is not defined`... 
UPD: But `DE.changed_device` works. So there is a [working example](https://github.com/domoticz/domoticz/blob/development/scripts/python/script_device_demo.py)

**Comment by hdoedens** [comment]
The problem with the sample code is that the log function is called with lowercase `l`. So this code:

`import DomoticzEvents as domoticz_ `
`def log(*args):
    domoticz_.log(0, " ".join([str(k) for k in args]))`

needs to be changed to:
`import DomoticzEvents as domoticz_ #`
`def log(*args):
    domoticz_.Log(0, " ".join([str(k) for k in args]))`
