### ISSUE TITLE
[Improvement] Setting an user variable as a value in the timers section

### ISSUE THREAD

**Issue by Patricen1** [domoticz/domoticz#2100]
Hello,

Would it be possible allowing user variables to be set in the "value" field of a timer?

Thanks
Patrice

**Comment by gizmocuz** [comment]
Not at the moment, why would you need to do this ?

**Comment by Patricen1** [comment]
Hello,
I do have setpoints for thermostats (Popp radiator valves). The setpoint values are set using timers for regular weekdays ans week-ends.
It would be very convenient having a multiple level switch to set température setpoint values like "no frost" at 4°,  "away" at 16°, "eco" at 18° etc. and use those values as a setpoint for timers. For this, it looks to me that the only way would be having a user variable for timer setpoints.

I'm currently using an ugly blockly that triggers every minute and checks if the multiple level switch is on away mode and then overrides the timer scheduled setpoint if it is the case. This is really not looking good to me, and i would like to find à better solution.

Any other suggestion regarding this issue is welcome, but user variable looks to me being the solution.

Thanks!

**Comment by pipiche38** [comment]
This would be a very convenient feature

**Comment by waltervl** [comment]
Perhaps solved by functionality of https://github.com/domoticz/domoticz/pull/5052 ?

**Comment by Patricen1** [comment]
Indeed, this functionality looks brilliant. Nevertheless, I wrote this topic at my beginnings and I was not aware about timer plans that solved my issue.
Working this way made me think about an enhancement that would be great:
- Currently, setpoints are applied only on setpoint change
- What would be very interesting is that setpoints are also applied on timer plan change, so that there is no need to wait for a setpoint change of the newly applied timer plan.

**Comment by waltervl** [comment]
I guess that it something to discuss on that PR. Perhaps it already changes. Or else make a new issue or forum discussion once implemented.
