### ISSUE TITLE
Running a helper function after some time (afterXX)

### ISSUE THREAD

**Issue by elxsi** [domoticz/domoticz#2102]
Hi,

I just added a helper function to the global_data.lua file. I can call the function without
any problems, but I would like do to something like this:

domoticz.helpers.speech(domoticz, 20, "Hello world").afterSec(30)

Can this be achieved in some way?

Thank you

**Comment by dannybloe** [comment]
Please use the forum for these kind of questions. 
And to answer your question: not without a lot of coding. But you can do it inside your helper and pass the delay time as a parameter.
