### ISSUE TITLE
Sensor data via MQTT does not have 'adjustment' applied

### ISSUE THREAD

**Issue by TheGuv** [domoticz/domoticz#2109]
I've recently added some devices reporting temperature via MQTT. They all read high compared to my other RFM69 based sensors so I added an adjustment. I notice that the temperature adjustment (in _edit device_) is not applied to the displayed reading for the MQTT sensors.

e.g. domoticz.log:
`2018-02-05 18:37:21.456  MQTT: Topic: domoticz/in, Message: {"idx":189,"nvalue":0,"svalue":"28.0;32.0;2"}` 
- temp 28C humidity 32%.

Edit Device.adjustment is -6C

Displayed temperature is 28.0, it should be 22.0C

Domoticz Version: 3.8809 (stable)

Is MQTT sensor data expected to not have the adjustment applied or did I miss something?

**Comment by TheGuv** [comment]
Anybody able to confirm that adjustment is not taken into account?

**Comment by gizmocuz** [comment]
Correct, it is applied internally in domoticz once received/stored

**Comment by aroussel62** [comment]
Got the same issue there still in 3.9030 (beta).

It seems temperature adjustment is not applied to virtual devices (updated via mqtt as TheGUv did) so the corrected value isn't stored in database (even shown in dashboard and devices views) after mqtt message recieved.

**Comment by gizmocuz** [comment]
@aroussel62 , this should now be solved in the latest beta, could you verify this ?
(see MainWorker::UpdateDevice) for temp/hum/baro and combinations

**Comment by aroussel62** [comment]
@gizmocuz  Hi, tested it with temp/hum sensors (vers beta 3.9584) and it works well
thanks a lot

**Comment by gizmocuz** [comment]
Great, thanks for the review !
