### ISSUE TITLE
Synology compile error EcoCompteur.cpp error: ‘stod’ was not declared in this scope

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#2112]
[ 40%] Building CXX object CMakeFiles/domoticz.dir/hardware/EcoCompteur.cpp.o
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r8887/hardware/EcoCompteur.cpp: In member function ‘void CEcoCompteur::GetScript()’:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r8887/hardware/EcoCompteur.cpp:139:72: error: ‘stod’ was not declared in this scope
   SendKwhMeter(m_HwdID, 1, 255, root["data1"].asFloat(), stod(fields[7]), "Conso 1");
                                                                        ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r8887/hardware/EcoCompteur.cpp:144:72: error: ‘stod’ was not declared in this scope
   SendKwhMeter(m_HwdID, 2, 255, root["data2"].asFloat(), stod(fields[9]), "Conso 2");
                                                                        ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r8887/hardware/EcoCompteur.cpp:149:73: error: ‘stod’ was not declared in this scope
   SendKwhMeter(m_HwdID, 3, 255, root["data3"].asFloat(), stod(fields[11]), "Conso 3");
                                                                         ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r8887/hardware/EcoCompteur.cpp:154:73: error: ‘stod’ was not declared in this scope
   SendKwhMeter(m_HwdID, 4, 255, root["data4"].asFloat(), stod(fields[13]), "Conso 4");
                                                                         ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r8887/hardware/EcoCompteur.cpp:159:73: error: ‘stod’ was not declared in this scope
   SendKwhMeter(m_HwdID, 5, 255, root["data5"].asFloat(), stod(fields[15]), "Conso 5");
                                                                         ^
make[5]: *** [CMakeFiles/domoticz.dir/hardware/EcoCompteur.cpp.o] Error 1

**Comment by sweetpants** [comment]
Already reported see https://github.com/domoticz/domoticz/pull/2107

**Comment by Jumbotroll** [comment]
Ok. Didn't see that. Thanks :-)

**Comment by DenisMartin0** [comment]
@Jumbotroll could you test the modification proposed in #2111 ?

**Comment by Jumbotroll** [comment]
@DenisMartin0 
Cross compiled for Synology arch-x86 and all went fine here with #2111 modification. Going to test with some different toolchains for different synology models now..
