### ISSUE TITLE
Error Compiling on BananaPI M3

### ISSUE THREAD

**Issue by sergiotropea** [domoticz/domoticz#2113]
I would like to try bananapi and use eMMC storage support. my SO Description and error code below:

- Ubuntu Server 16.04
- Linux bpi-iot-ros-ai 3.4.39-BPI-M3-Kernel #6 SMP PREEMPT Wed Nov 29 06:31:42 UTC 2017 armv7l armv7l armv7l GNU/Linux

```
/usr/bin/ld: CMakeFiles/domoticz.dir/hardware/Arilux.cpp.o: undefined reference to symbol 'epoll_create@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/libc.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:5464: recipe for target 'domoticz' failed
make[2]: *** [domoticz] Error 1
CMakeFiles/Makefile2:103: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

Anybody can help me?

**Comment by gizmocuz** [comment]
You should be able to follow this guide:

https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source

Maybe update GCC to version 6

**Comment by gizmocuz** [comment]
No response, hope it worked. Closing issue
