### ISSUE TITLE
HTML improvement: add 'options' class

### ISSUE THREAD

**Issue by flatsiedatsie** [domoticz/domoticz#2114]
Currently there are quite a few inconsistencies in the Domoticz HTML output. Chrome is now grading some of these as errors. Perhaps some low-hanging fruit could be fixed.

Some examples:
- In item tables, instead of classes each TD is given an ID. This is one of the error Chrome complains about, as officially an ID should always be unique, while you can have more than one of a class. I would propose a slow transition. First, these TD's could a class with the same name as the ID they currently have. So for example, _td id="name"_ would become _td id="name" class="name"_ . Sometime in the (far) future, the ID's could be fased out. The Aurora theme, for example, currently uses javascript to copy the ID's into classes. This is important because JQuery assumes correct CSS. Many of its functions work on elements with classes, but don't work on ID's, requiring hacks.

- Some TD's don't have a name, which makes them very hard to target via CSS. In the Aurora theme I have suggested a few, which are again 'hacked in' via jquery. For example: give the TD that contains options like "edit" and "log" the _options_ class name.

Without names for elements, you get CSS like this:

	body table#itemtable tr td:first-child + td + td + td + td + td + td {
		font-size: 90%;
		clear: both;
		padding: 0 5% 0 5%;
		line-height: 130%;
	}

and:

	#settingscontent textarea + span,
	#settingscontent textarea + span + span,
	#settingscontent textarea + span + span + span,
	#settingscontent textarea + br + span,
	#settingscontent textarea + br + span + span,
	#settingscontent textarea + br + span + span + span {
		color: #ccc;
		font-size: 10px
	}

Which is currently in the Domoticz CSS.

This styling is very fragile. It breaks as soon as the order of the html changes. You could say that this is the opposite of that CSS is for: separate structure from styling. Here CSS is actually making Domoticz less easy to work on, instead of easier.

I could add this CSS (as I has done before in the Gui rework branch).

Should I?

**Comment by gizmocuz** [comment]
Yes please go ahead! But can you show the errors chrome is giving ? As i don't have them here.

**Comment by flatsiedatsie** [comment]
<strike>Oddly enough I don't see the errors now either. Perhaps it was on another browser. But I did see them.</strike>

<img src="https://www.pineapplejazz.com/public/domoticz/other/chrome-errors.png">
Chrome gives 54 errors like this.

So:
- I've directly added the 'options' class everywhere. It already existed on the utilities page.
- I've created pull requests for the addition of the classnames to all TD's that already had ID names.
- I've proposed a name for the unnamed TD on the dashboard which contains switches and sliders.

**Comment by flatsiedatsie** [comment]
So, what is going on here?
- I asked permission. You said "go for it".
- I added the classes.
- Feedback was: let's change the classes names a little. I said: ok, I can do a replace-all as soon as these basic classes are accepted (saves a lot of work).
...
- changes are not accepted?

**Comment by gizmocuz** [comment]
I thought we were going to integrate your theme as basis, and starting with the needed javascript/html/css changes first (without the theme) in a version controlled way (github)
The changes in those 4 separate pull requests where indeed discussed, naming would have to be BEM based, or at least different of course.

**Comment by flatsiedatsie** [comment]
So then why did you not accept the changes? Because the names weren't BEM already?

I am not a GIT guru, I use the web interface. This limits how I can help. In this case. For example, I cannot change a merge request.

The steps I suggested were:
1. Accept the changes to add simple classnames.
2. Change the names to BEM names.

2 will be a simple find replace. But only if 1 is accepted. Otherwise I have to to all the work again from scratch.

**Comment by flatsiedatsie** [comment]
hi

**Comment by gizmocuz** [comment]
Git is not so complex

1. Fork our project, now you have it on your own github
2. Checkout the Domoticz Development from your github
3. Make the changes (start simple please, not 1000 changes in one PR)
4. Commit the changes
5. Now when you go to your github/domoticz page, you see a green button 'Create Pull Request'
6. Press that button, and it's done
7. If there are any changes to be added, just keep committing them to your domoticz fork until it gets merged

**Comment by flatsiedatsie** [comment]
Hmm, that's exactly what I did. But step 7 was not possible in the web interface.

**Comment by gizmocuz** [comment]
Was there a error message being displayed or any reason why it could not commit ?
If the PR was already merged/closed, then this is not possible

**Comment by waltervl** [comment]
Closed. Changes not implemented.
