### ISSUE TITLE
Question: OpenZWave source files and folder in Domoticz?

### ISSUE THREAD

**Issue by rjblake** [domoticz/domoticz#2116]
In the 'domoticz->harware->openzwave' section, there are various sources from the OpenZWave repo. Are these compiled into Domoticz in any way, or serve any purpose? In the build instructions, it states you need to build the OpenZWave library before compiling. Reason I am asking is that I have used a branch of OZW that includes the BarrierOperator class and would like to add this functionality to Domoticz; but not sure if I also need to sync these files as well. Anyone got some tips?

**Comment by gizmocuz** [comment]
If there are changes in the header files, yes you need to update the headers here

**Comment by rjblake** [comment]
Thanks Gizmocuz. To be honest, find it all rather confusing, as there are some files/headers (e.g. CentralScene.h) from the OpenZwave Dev branch, but looks like some from the Master as not all dev branch there. Have there been any thoughts on the inclusion of the BarrierOperator (along line of CentralScene inclusion); or is this all pending an update from the OZW crowd?

**Comment by gizmocuz** [comment]
Best if OZW gets things merged
