### ISSUE TITLE
403 Forbidden You don't have permission to access /wiki/Main_Page on this server.  Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.  Apache/2 Server at www.domoticz.com Port 80

### ISSUE THREAD

**Issue by Twimpy** [domoticz/domoticz#2119]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version.
* Always state your version when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by Twimpy** [comment]
what is wrong with domoticz web site i get on all www.domotics 403 error.

**Comment by gizmocuz** [comment]
its not www.domotics
