### ISSUE TITLE
Include new openzwave control panel

### ISSUE THREAD

**Issue by wolph** [domoticz/domoticz#212]
I've recently created an update for the openzwave control panel including a bootstrap3 interface which is a bit more usable than the old one. There are always improvements available of course but I think it's easier to use than the old version and a bit prettier.
![Bootstrap 3 OpenZWave Control Panel](https://cloud.githubusercontent.com/assets/270571/9980781/ea9b394a-5fa5-11e5-8964-09e30d81c78d.png)

The issue on that side is currently open here if you're interested: https://github.com/OpenZWave/open-zwave-control-panel/issues/35
But I think Domoticz is including a separate version anyhow, so I was wondering if an immediate pull request would be appreciated or if everything should go through the upstream repo.

(ps: it appears that domoticz is only supporting part of the z-wave interface, is that intentional? The scene section of the interface appears broken since there's no url endpoint for that)

**Comment by gizmocuz** [comment]
Looking nice !
Domoticz has it's own scene implementation, and it could be very confusing if this was allowed.
Domoticz is also using bootstrap2, will that also work ?
(And has removed the controller devicename/usb)

**Comment by wolph** [comment]
Yes, I see how the scenes could be confusing to allow as well. It's easy enough to disable it by simply hiding that option from the list though :)
The same goes for removing the devicename/usb stuff, hiding it shouldn't be more than a line of javascript for both.

As for bootstrap 2 versus 3, while they are mostly similar, the differences are great enough that they're not really compatible. The official list of things to change can be found here http://getbootstrap.com/migration/ and it's mainly just a search/replace type of thing. But some things actually got added/removed from bootstrap 3 so it would be extra work to support those.

Ultimately I would suggest updating everything to bootstrap 3 (or even 4) at some point, but for the time being I think they can easily coexist in this case. The z-wave interface is quite a separate thing anyhow. Now all we need is a solution to cleanly support both domoticz and the standard openzwave control panel with a single codebase. I'm currently thinking about loading a "config.js" or "local.js" javascript or something to enable/disable certain parts.

**Comment by gizmocuz** [comment]
is this in the standard openzwave codebase?

**Comment by wolph** [comment]
Yes, it's been merged a couple of months ago: https://github.com/OpenZWave/open-zwave-control-panel/pull/36

**Comment by gizmocuz** [comment]
Great!, and it can not work with the current bootstrap of domoticz ?
Do you think you could make a pull request with the needed changes to domoticz ?
You specially have to watch/care that the mobile devices get the mobile menu, i experienced this before when upgrading to boostrap 2
Maybe you could add a minimal boostrap 3 implementation/files, just in our control panel folder?
(but a total upgrade would be nice to have _g_)

**Comment by wolph** [comment]
Downgrading to the old bootstrap is an option but it would require a lot of separate template work which is not the best idea imho.

For the future it would indeed be better to upgrade bootstrap within domoticz but that could be a lot of work, can't say I can make a reasonable estimation at this point.

A minimal bootstrap 3 implementation would probably be the easiest solution for now, just name the files bootstrap3.js and bootstrap3.css so it won't conflict. I can make a pull request somewhere in the next couple of months but I'm pretty overbooked at the moment. It's probably not that much work since I'm actually running domoticz with the newer version. But the domoticz server responds slightly different from the regular open-zwave install so we might need some limitations.

**Comment by gizmocuz** [comment]
In the next couple of months wont work....
Best to leave it like this than
Thank you for your support!
