### ISSUE TITLE
Feature Request: possibility to change default icons

### ISSUE THREAD

**Issue by htilburgs** [domoticz/domoticz#2124]
Within Domoticz there is the possibility to add custom icons. Currently you can only select these images for this devices: On/Off, Dimmer, Media Player, Selector

It would be nice to have the possibility to change other device types to. For example:
- Smoke Detector
- Blinds
- Door contact
- etc...

Is it possible to add this functionality to Domoticz?

**Comment by febalci** [comment]
I also highly support this request...

**Comment by mvveelen** [comment]
Looks like request: #2212

But I also support this request 👍

**Comment by sonar98** [comment]
Door contact is possible ... any plans on implementing this for Blinds etc?

**Comment by gizmocuz** [comment]
Nope not at this moment. Icon is fine and clean. This one also has a 'stop' button that is used in some hardware.
Most things you can already customize

**Comment by waltervl** [comment]
Most devices can use custom icons
