### ISSUE TITLE
Libssl 1.1 vs libssl 1.0.2

### ISSUE THREAD

**Issue by kofec** [domoticz/domoticz#2126]
Sorry but I don't have time to continue previous investigation but today I have a while and what I found
https://github.com/domoticz/domoticz/issues/2098

Thread 3 "domoticz" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb5613430 (LWP 31660)]
__GI_strcmp (p1=, p2=) at strcmp.c:38
38	strcmp.c: No such file or directory.
(gdb) bt
#0 __GI_strcmp (p1=, p2=) at strcmp.c:38
#1 0x00687cd0 in getrn ()
#2 0x00687ef8 in lh_insert ()
#3 0x0066dcec in OBJ_NAME_add ()
#4 0x0068dfd4 in EVP_add_digest ()
#5 0xa7a87e5c in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

so I decide to remove(change name of) library /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1 to
/usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.1
and now Domticz is working fine but 2 python plugins which are using libcrypto.so.1.1 failed (as it is missing).

ldd show that Domoticz should use 1.0.2 so I don't know why Domoticz crash when use 1.1

~/domoticz $ ldd domoticz
	/usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.2 (0xb6d7b000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0xb6d65000)
	libusb-0.1.so.4 => /lib/arm-linux-gnueabihf/libusb-0.1.so.4 (0xb6d4d000)
	libudev.so.1 => /lib/arm-linux-gnueabihf/libudev.so.1 (0xb6d30000)
	librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb6d19000)
	libresolv.so.2 => /lib/arm-linux-gnueabihf/libresolv.so.2 (0xb6cf4000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6ccb000)
	libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0xb6ca4000)
	libcurl.so.4 => /usr/lib/arm-linux-gnueabihf/libcurl.so.4 (0xb6c28000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6c15000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6b96000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6a57000)
	/lib/ld-linux-armhf.so.3 (0xb6efb000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6a2a000)
	libnghttp2.so.14 => /usr/lib/arm-linux-gnueabihf/libnghttp2.so.14 (0xb69fc000)
	libidn2.so.0 => /usr/lib/arm-linux-gnueabihf/libidn2.so.0 (0xb69ca000)
	librtmp.so.1 => /usr/lib/arm-linux-gnueabihf/librtmp.so.1 (0xb69a1000)
	libssh2.so.1 => /usr/lib/arm-linux-gnueabihf/libssh2.so.1 (0xb696c000)
	libpsl.so.5 => /usr/lib/arm-linux-gnueabihf/libpsl.so.5 (0xb694f000)
	libssl.so.1.0.2 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.2 (0xb68f0000)
	libgssapi_krb5.so.2 => /usr/lib/arm-linux-gnueabihf/libgssapi_krb5.so.2 (0xb68a7000)
	libkrb5.so.3 => /usr/lib/arm-linux-gnueabihf/libkrb5.so.3 (0xb67f0000)
	libk5crypto.so.3 => /usr/lib/arm-linux-gnueabihf/libk5crypto.so.3 (0xb67b1000)
	libcom_err.so.2 => /lib/arm-linux-gnueabihf/libcom_err.so.2 (0xb679e000)
	liblber-2.4.so.2 => /usr/lib/arm-linux-gnueabihf/liblber-2.4.so.2 (0xb6782000)
	libldap_r-2.4.so.2 => /usr/lib/arm-linux-gnueabihf/libldap_r-2.4.so.2 (0xb672d000)
	libunistring.so.0 => /usr/lib/arm-linux-gnueabihf/libunistring.so.0 (0xb661e000)
	libgnutls.so.30 => /usr/lib/arm-linux-gnueabihf/libgnutls.so.30 (0xb6491000)
	libhogweed.so.4 => /usr/lib/arm-linux-gnueabihf/libhogweed.so.4 (0xb6454000)
	libnettle.so.6 => /usr/lib/arm-linux-gnueabihf/libnettle.so.6 (0xb640d000)
	libgmp.so.10 => /usr/lib/arm-linux-gnueabihf/libgmp.so.10 (0xb639a000)
	libgcrypt.so.20 => /lib/arm-linux-gnueabihf/libgcrypt.so.20 (0xb62ca000)
	libkrb5support.so.0 => /usr/lib/arm-linux-gnueabihf/libkrb5support.so.0 (0xb62af000)
	libkeyutils.so.1 => /lib/arm-linux-gnueabihf/libkeyutils.so.1 (0xb629c000)
	libsasl2.so.2 => /usr/lib/arm-linux-gnueabihf/libsasl2.so.2 (0xb6275000)
	libp11-kit.so.0 => /usr/lib/arm-linux-gnueabihf/libp11-kit.so.0 (0xb6217000)
	libidn.so.11 => /lib/arm-linux-gnueabihf/libidn.so.11 (0xb61d6000)
	libtasn1.so.6 => /usr/lib/arm-linux-gnueabihf/libtasn1.so.6 (0xb61b6000)
	libgpg-error.so.0 => /lib/arm-linux-gnueabihf/libgpg-error.so.0 (0xb6196000)
	libffi.so.6 => /usr/lib/arm-linux-gnueabihf/libffi.so.6 (0xb617e000)

Is it possible to force to use version 1.0.2 ?

**Comment by gizmocuz** [comment]
I suspect when you uninstall 1.1 and install 1.0.2 it should only find the later

**Comment by kofec** [comment]
I consider removing libcrypto 1.1:
pi@RpiKotlownia:~ $ sudo apt-get remove libssl1.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
distro-info-data fonts-lato gir1.2-glib-2.0 iso-codes iw javascript-common libbabeltrace-ctf1 libbabeltrace1 libc6-dbg libdbus-glib-1-2 libdw1 libexpat1-dev
libgirepository-1.0-1 libjs-jquery liblua5.2-0 libmpdec2 libpython2.7-minimal libssl-doc libtcl8.6 libyaml-0-2 python-apt-common python-minimal python2.7-minimal
ruby-did-you-mean ruby-minitest ruby-net-telnet ruby-power-assert ruby-test-unit wireless-regdb
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
apt-listchanges ca-certificates crda dh-python gdb iotop libpython-stdlib libpython2.7-stdlib libpython3-dev libpython3-stdlib libpython3.5 libpython3.5-dev
libpython3.5-minimal libpython3.5-stdlib libruby2.3 libsasl2-modules libssl-dev libssl1.1 lsb-release openssl python python-pip-whl python-rpi.gpio python2.7 python3
python3-apt python3-cffi-backend python3-crypto python3-cryptography python3-dbus python3-dev python3-gi python3-idna python3-keyring python3-keyrings.alt python3-minimal
python3-pip python3-pkg-resources python3-pyasn1 python3-secretstorage python3-setuptools python3-six python3-wheel python3-xdg python3.5 python3.5-dev python3.5-minimal
rake ruby ruby2.3 rubygems-integration vim-nox
0 upgraded, 0 newly installed, 52 to remove and 0 not upgraded.
After this operation, 128 MB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.

**Comment by gizmocuz** [comment]
when you do have time, remove 1.1, also do an autoremove and test. No need to post a log when you do not remove it, going back to python <3.5 seems also a good idea (like 3.4)

**Comment by kofec** [comment]
Where I can read about "There seems to be an issue betweeb libcurl and OpenSSL 1.1.0 on newer raspbian system (stretch). On these systems i recommend using libssl1.0-dev instread of libssl-dev." ?

**Comment by kofec** [comment]
I found this topic. https://github.com/curl/curl/issues/1695

**Comment by kofec** [comment]
I have compile by myself on my raspberry Pi1. it take about 12h but now it is stable when all plugins available
