### ISSUE TITLE
Humidity displayed as (undecoded) hexadecimal percentage

### ISSUE THREAD

**Issue by TheGuv** [domoticz/domoticz#2128]
Version: 3.8809 (stable)
I have a Fine Offset (FO) WH1050 weather station sending date to Domoticz via RFLink. It is identified in Domoticz as a WTGR800 Temp+Humidity. The temperature is correct but I notice the displayed humidity appears to be displayed as undecoded hexadecimal.

That is, for an actual humidity of 70% (as displayed by the FO display unit) the Domoticz display indicates 46%. Now, as 0x46 is 70dec I think this is a clue.

domoticz.log confirms it is receiving the following data:
RFLink: 20;99;Alecto V2;ID=005b;TEMP=00a1;HUM=46;WINSP=004b;WINGS=0076;RAIN=0001;
and Domoticz displayed temperature of 16.1C (correct) and humidity 46% (incorrect, it should be 70%).

Could this be because the WTGR800 sends humidity in decimal and the FO in hex, or just a bug maybe?

I have not tried a beta release recently; the last two I tried had very broken sunrise/sunset timers so I reverted back to stable.

**Comment by gizmocuz** [comment]
Domoticz just translates the text 46 to 46 integer.
As probably many users have temp+hum sensors, it might be a problem just for this specific sensor.
Best to contact RFLink

**Comment by xztraz** [comment]
have you the latest version of rf-link firmware?

Here are the data from some of my rflink sensors. Temp reported as hex but not humidity and corretly read by domoticz. 

> Feb 12 11:13:07 raspberrypi domoticz: RFLink: 20;64;AlectoV3;ID=308c;TEMP=00dd;HUM=37;BAT=OK;
> Feb 12 11:13:28 raspberrypi domoticz: RFLink: 20;65;AlectoV3;ID=30aa;TEMP=000f;HUM=81;BAT=OK;
> Feb 12 11:13:43 raspberrypi domoticz: RFLink: 20;66;Acurite;ID=824f;WINSP=001a;WINDIR=0005;RAIN=16c7;BAT=OK;
> Feb 12 11:14:02 raspberrypi domoticz: RFLink: 20;67;Acurite;ID=824f;TEMP=0012;HUM=98;WINSP=001a;BAT=OK;
> Feb 12 11:14:04 raspberrypi domoticz: RFLink: 20;68;AlectoV3;ID=3037;TEMP=0019;HUM=80;BAT=OK;
> Feb 12 11:14:09 raspberrypi domoticz: RFLink: 20;69;Mebus;ID=4601;TEMP=0015;
> Feb 12 11:14:16 raspberrypi domoticz: RFLink: 20;6A;AlectoV3;ID=30aa;TEMP=000f;HUM=81;BAT=OK;
> Feb 12 11:14:20 raspberrypi domoticz: RFLink: 20;6B;Acurite;ID=824f;WINSP=0033;WINDIR=0003;RAIN=16c7;BAT=OK;
> Feb 12 11:14:38 raspberrypi domoticz: RFLink: 20;6C;Acurite;ID=824f;TEMP=0012;HUM=98;WINSP=004c;BAT=OK;
> Feb 12 11:14:44 raspberrypi domoticz: RFLink: 20;6D;Mebus;ID=4601;TEMP=0015;
> Feb 12 11:14:49 raspberrypi domoticz: RFLink: 20;6E;AlectoV3;ID=308f;TEMP=0032;HUM=90;BAT=OK;
> Feb 12 11:14:52 raspberrypi domoticz: RFLink: 20;6F;AlectoV3;ID=30cc;TEMP=0014;HUM=85;BAT=OK;
> Feb 12 11:14:52 raspberrypi domoticz: RFLink: 20;70;AlectoV3;ID=3037;TEMP=0019;HUM=80;BAT=OK;
> Feb 12 11:14:56 raspberrypi domoticz: RFLink: 20;71;Acurite;ID=824f;WINSP=004c;WINDIR=0002;RAIN=16c7;BAT=OK;
> Feb 12 11:13:07 raspberrypi domoticz: RFLink: 20;64;AlectoV3;ID=308c;TEMP=00dd;HUM=37;BAT=OK;
> Feb 12 11:13:28 raspberrypi domoticz: RFLink: 20;65;AlectoV3;ID=30aa;TEMP=000f;HUM=81;BAT=OK;
> Feb 12 11:13:43 raspberrypi domoticz: RFLink: 20;66;Acurite;ID=824f;WINSP=001a;WINDIR=0005;RAIN=16c7;BAT=OK;
> Feb 12 11:14:02 raspberrypi domoticz: RFLink: 20;67;Acurite;ID=824f;TEMP=0012;HUM=98;WINSP=001a;BAT=OK;
> Feb 12 11:14:04 raspberrypi domoticz: RFLink: 20;68;AlectoV3;ID=3037;TEMP=0019;HUM=80;BAT=OK;
> Feb 12 11:14:09 raspberrypi domoticz: RFLink: 20;69;Mebus;ID=4601;TEMP=0015;
> Feb 12 11:14:16 raspberrypi domoticz: RFLink: 20;6A;AlectoV3;ID=30aa;TEMP=000f;HUM=81;BAT=OK;
> Feb 12 11:14:20 raspberrypi domoticz: RFLink: 20;6B;Acurite;ID=824f;WINSP=0033;WINDIR=0003;RAIN=16c7;BAT=OK;
> Feb 12 11:14:38 raspberrypi domoticz: RFLink: 20;6C;Acurite;ID=824f;TEMP=0012;HUM=98;WINSP=004c;BAT=OK;
> Feb 12 11:14:44 raspberrypi domoticz: RFLink: 20;6D;Mebus;ID=4601;TEMP=0015;
> Feb 12 11:14:49 raspberrypi domoticz: RFLink: 20;6E;AlectoV3;ID=308f;TEMP=0032;HUM=90;BAT=OK;
> Feb 12 11:14:52 raspberrypi domoticz: RFLink: 20;6F;AlectoV3;ID=30cc;TEMP=0014;HUM=85;BAT=OK;
> Feb 12 11:14:52 raspberrypi domoticz: RFLink: 20;70;AlectoV3;ID=3037;TEMP=0019;HUM=80;BAT=OK;
> Feb 12 11:14:56 raspberrypi domoticz: RFLink: 20;71;Acurite;ID=824f;WINSP=004c;WINDIR=0002;RAIN=16c7;BAT=OK;

**Comment by TheGuv** [comment]
@gizmocuz thanks, that makes some sense. The temperature is supplied in hex and correctly decoded by Domoticz though. Is it the case the humidity is supposed to be different and in decima or just text formatl?

@xztraz Indeed not. I'm using r33 which is quite old, but I needed some mods and that's the most recent source I found. The RFLink is in a really inaccessible location so if necessary I'll patch the humidity elsewhere :)

**Comment by gizmocuz** [comment]
@TheGuv , i would expect a general notation for the humidity and i don't think it should be different for this type of sensor.
Best to update your RFLink firmware. Closing the issue now, if it does not work after the update, please re-open

**Comment by xztraz** [comment]
Just some fixes regarding humidity in RfLink.  you should really upgrade. i think i saw this bug and got it corrected by dev like a year ago among other bug fixes

v46-v48
- Fixed: AlectoV3 Humidity value validation
- Fixed: FineOffset vs Alecto improved differentiation, Note: device ID's have changed for WS1100
- Fixed: Alecto WS-1100 humidity
- Fixed: AlectoV1 Rain, Wind and Humidity values
v38
- New Device: FineOffset Temperature & Humidity sensors
v34
- Fixed: Alecto WS1100 working properly again (Adjusted pulse range and displayed humidity value)

**Comment by xztraz** [comment]
@TheGuv 

here are some steps to upgrade it remotley from a linux machine if thats what you use. (this should really be integrated in domoticz)

https://www.fontenay-ronan.fr/update-rflink-gateway-on-linux-ubuntu/

https://www.domoticz.com/forum/viewtopic.php?t=7988

**Comment by TheGuv** [comment]
@gizmocuz Thanks for the confirmation.

@xztraz Yes, you are correct that this was fixed in RFLInk and thanks for the pointer to the flashing guide. I do know how to flash, the issue is that the device is on the rooftop and the ladder is heavy and I'm basically lazy :) I also forgot to connect the reset line of the Mega2560 running RFLink to a port on the Rpi it's connected to otherwise I'd flash it remotely. When it warms up a bit I'll fix it properly but until then
```
@@ -741,7 +732,11 @@
 		else if (results[ii].find("HUM") != std::string::npos)
 		{
 			bHaveHum = true;
-			humidity = RFLinkGetIntStringValue(results[ii]);
+			if (results[2].find("Alecto V2") != std::string::npos) {
+			    humidity = RFLinkGetHexStringValue(results[ii]);
+			} else { humidity = RFLinkGetIntStringValue(results[ii]); }
 		}
 		else if (results[ii].find("HSTATUS") != std::string::npos)

```
LOL. Ghetto for sure. Let this be a warning to other putting stuff into difficult-to-reach places...

**Comment by xztraz** [comment]
well.. remote upgrade should be remote.. no climbing. :)  don't you connect it via usb to your pi?
