### ISSUE TITLE
[TELEINFO USB] Labels of Linky "standard" mode not handled

### ISSUE THREAD

**Issue by BinuitBinuit** [domoticz/domoticz#2129]
Hello,

I am currently using Domoticz to retrieve the teleinfo of a Linky meter via the Hardware **Teleinfo USB**.
The current code handles perfectly the labels of the **Historical** mode of the teleinfo, but unfortunately it does not handle the labels of the **Standard** mode.
In my specific case, I need to retrieve the labels **EAST** and **EAIT** that display the amount of energy respectively consumed and injected on the network.
All the available labels of the Standard mode can be found in this french document - chapter 6.2.2 (page 18): http://www.enedis.fr/sites/default/files/Enedis-NOI-CPT_54E.pdf

I have two questions regarding that issue:
1) Is it planned to develop the handling of the labels of the Standard mode?
2) Is there a temporary solution that I can implement to get the labels I need? (like a plugin or anything else - I am running Domoticz on a Raspberry Pi 3)

Thank you!

Benoit

**Comment by fabienp5** [comment]
Hello,

I have this project too, i need to have energy consumed and injected on the network.

thank you for help

PS: sorry i d'ont speak/write english very well

**Comment by gizmocuz** [comment]
Someone that has this type of meter could try to implement this. As it should be a quite simple addon, it is not nececery to write a complete new (python) plugin

**Comment by Martial83** [comment]
Hi,
Do you have news about this?
I'm very interested with that.
Thank you

**Comment by fabienp5** [comment]
I don't have news about this, but i'm always interested about this to.
I d'ont have linky = standard mode for test... it isn't free to cange historic on standard, so i wait someone have already standard mode et can confirm test = ok 
(sry for my enlgish i'm french )

**Comment by bnj-04** [comment]
Hello, i created a native python plugin to get data from linky in "standard mode". it's working but need some more work to improve the reliability : https://github.com/bnj-04/LinkyStdMode

**Comment by Martial83** [comment]
Hello,
Can you see EAST and EAIT from the same Linky meter at the same time? If so, you must not be in France since ENEDIS does not know how to put the meter in "Producer" mode when we are selling surplus. 
Thank you to confirm me.

**Comment by Martial83** [comment]
> .. it isn't free to cange historic on standard, so i wait someone have already standard mode et can confirm test = ok

Bien sûr que si que c'est gratuit ! (en France du moins)

**Comment by bnj-04** [comment]
Bonjour, non, je ne vois que les trames EAST et SINSTS, pas de EAIT ni de SINSTI :(

J'ai pu demander au technicien enedis de configurer le linky en mode standard pendant l'installation de celui ci, c'est juste un choix dans une liste déroulante sur leur tablette connecté au linky, ca prend 2 secondes.

**Comment by Martial83** [comment]
C'est bien ça, et ils ne savent pas (leur logiciel ne le permet pas) configurer le mode "Producteur" quand on est aussi consommateur. Je les ai traîné devant le médiateur de l'énergie, ils reconnaissent le problème, mais "ils ont tellement de problèmes plus graves à régler !" (dixit le médiateur) !!!

**Comment by gizmocuz** [comment]
Please keep every conversation in English

**Comment by Martial83** [comment]
C'est un sujet franco français me semble-t-il!

**Comment by xbeaudouin** [comment]
Well even if this is a specific french hardware, the project is in english (looking for that when Linky will be at my home...).

**Comment by Martial83** [comment]
Dommage, je m'en vais ...

**Comment by waltervl** [comment]
Should be implemented with https://github.com/domoticz/domoticz/pull/5045 and https://github.com/domoticz/domoticz/pull/5076
