### ISSUE TITLE
Imac instructions followed but not working

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#213]
I followed everything and all worked up to instruction to start program by typing ./domoticz i.e
iMacBG:domoticz BG$ ./domoticz
-bash: ./domoticz: No such file or directory
iMacBG:domoticz BG$ 
There is a file called domoticz.sh to which I do not have permission.  Changing permission with chmod 755  allow me to execute with ./domoticz.sh but nothing happens.  I look at the domoticz.sh file and I see a line about username pi ???   Something now quite right I think.   Do I have an RPi version and not the one for the mac.  I followed the instructions which included the preparations and the downloading and compiling of the source code.   I could not put this on the Forum as its not working as follows

General Error
SQL ERROR [ mysqli ]
Table './pkjv172828_bb1/bb_sessions' is marked as crashed and should be repaired [145]
An sql error occurred while fetching this page. Please contact an administrator if this problem persists.

**Comment by gizmocuz** [comment]
It looks like you did not build the source, or it did not succeeded building
Please try the forum again
