### ISSUE TITLE
rtl433 and custom parameters.

### ISSUE THREAD

**Issue by josu98** [domoticz/domoticz#2130]
Version: 3.8153
Platform: Ubuntu 16.04
Plugin/Hardware: RTL-SDR
Description:

Hi!

After latest update the system doesn't read the extra parameters added under Hardware for rtl433. No matter what I write there it just use the default setting specified in rtl433.cpp. It worked in previous version.

Regards.

**Comment by gizmocuz** [comment]
do you see your command line (extra arguments) in the log being displayed ?

Rtl433: Worker started... (Extra Arguments: %s)

**Comment by josu98** [comment]
The log says: 2018-02-13 07:16:04.281 Rtl433: Worker started...
It doesnt say anything about (extra arguments) in the log.
I have the following command as extra parameters: -d 0 -f 433550000

**Comment by josu98** [comment]
hmm... just realized that Im having trouble updating hardware parameters under the menu Hardware. When I try I get an error saying "Error updating hardware..." if I then click the menu Devices I get an error saying "Problem retrieving devices" and I have to restart the Domoticz service.
This began after updating to latest version and I did that by executing command "sudo ./updaterelease" from cli. Do I have to do anything else to complete the update of Domoticz or is that it? 

Regards.

**Comment by josu98** [comment]
I stopped the Domoticz service and recompiled it. I then ran the install, started the service and it works now. I can now modify the HW and it reads the extra parameters at startup. 
Thanks for your input!
