### ISSUE TITLE
Domoticz dashboard failed to access after latest beta update

### ISSUE THREAD

**Issue by jcwlim** [domoticz/domoticz#2131]
May I know where did domoticz store its log? Ever since I updated to the latest beta, my dashboard failed to load. Service is running though. If I install the release version, then it is okay but I need better MQTT support so I need to use beta version.
Can anyone help her?

**Comment by jcwlim** [comment]
Found the problem, it seem like a python plugin causing it fail to start.

**Comment by gizmocuz** [comment]
yes, it is mentioned here before
