### ISSUE TITLE
Multiple Oregon THN132N are seen as the same device with a RFPlayer

### ISSUE THREAD

**Issue by ultrasuperpingu** [domoticz/domoticz#2135]
I have 2 THN132N setup with different channels but they share the same id (id EA4C). I checked without the RFPlayer software and it sends a field with the channel. I guess this information is not used by domoticz. It's probably the same for others Oregon products.

**Comment by ultrasuperpingu** [comment]
I just look at the source code and it seems that the channel field (INCOMING_RF_INFOS_TYPE4 and INCOMING_RF_INFOS_TYPE5 idChannel field) is not event used so the problem is indeed present for all Oregon Products. We can see that in the file ZiBlueBase.cpp, method ParseBinary (lines 606, 608, 627). I don't look at how the SendTemp*Sensor methods are working but my guess is that the NodeID parameter has to be unique. So a simple fix will be to provide something like a hash between the idPHY field and the idChannel (example SendTempSensor(pSen->idPHY^pSen->idChannel,...)

**Comment by gizmocuz** [comment]
Yes you are correct, the NodeID has to be unique.
You could do a hashing, or if both values are 8 bit you could do something like

`NodeID = (a << 8) | b`

**Comment by ultrasuperpingu** [comment]
idPHY is a short, so it could be : pSen->idPHY<<16|pSen->idChannel
But I don't have a build environment but my raspberry 1 and I can't compile domoticz on it (unable to link due to lack of RAM :( ), so I can't test it...

**Comment by gizmocuz** [comment]
The Node_ID for a temp sensor is 16 bit, so a hash would then be a good solution

**Comment by gizmocuz** [comment]
If there is still a problem, please feel free to make a pull request with the needed changes
