### ISSUE TITLE
Notification for temperature sensor

### ISSUE THREAD

**Issue by Derf911** [domoticz/domoticz#2137]
Hello,

I use Domoticz v8922 (before I used the latest stable)?

I have many temperature and humidity Xiaomi sensors.
I configured notifications (telegram and email) when the humidity level is too high or low --> No problem.
I tried to configure temperature notification but it doesn't work : I don't received email or telegram notification.

Is it a bug ? How to troubleshoot it ?

Thanks

**Comment by sweetpants** [comment]
I'm on V3.8922 also and Email and Telegram notification for temperature works fine. So maybe this is Xiaomi specific.

**Comment by gizmocuz** [comment]
Looking at the Xiaomi class code, it is using the default method for updating temperature sensors in domoticz and thus this should also work.
