### ISSUE TITLE
Encoding issues on v3.8917

### ISSUE THREAD

**Issue by jonferreira** [domoticz/domoticz#2138]
as per https://www.domoticz.com/forum/viewtopic.php?f=6&t=22171&p=171029#p171029

starting with v3.8917 I've been having encoding issues with ' (maybe others as well)

any http request such as json.htm?type=devices or json.htm?type=command&param=getplandevices&idx=3&roomname=xxx will return ' encoded as &apos;

``
{
   "result" : [
      {
         "DevSceneRowID" : "25",
         "Name" : "Biancas&apos; Room",
         "devidx" : "25",
         "idx" : "4",
         "order" : "4",
         "type" : 0
      },
      {
         "DevSceneRowID" : "467",
         "Name" : "Biancas&apos; Room Light",
         "devidx" : "467",
         "idx" : "74",
         "order" : "74",
         "type" : 0
      },
      {
         "DevSceneRowID" : "195",
         "Name" : "Biancas&apos; Room Roller Shutter",
         "devidx" : "195",
         "idx" : "82",
         "order" : "82",
         "type" : 0
      }
   ],
   "status" : "OK",
   "title" : "GetPlanDevices"
}
``

This also affects the frontend but *not* the devices list

![frontend](https://user-images.githubusercontent.com/7714292/36201590-602fd34c-1178-11e8-9956-1312abde7b1b.PNG)
![devices](https://user-images.githubusercontent.com/7714292/36201591-604e674e-1178-11e8-8f52-b5f31849cc21.PNG)

**Comment by bizziebis** [comment]
Sounds like the result of pull request #2105

**Comment by jonferreira** [comment]
ah bugger, that explains it alright!

Hopefully @gizmocuz or @Jarthianur can take a look at this

**Comment by Jarthianur** [comment]
Definitely caused by the mentioned PR.

When seeing such HTML entities literally, your browser does not support it.
There are a lot of discussions how to replace `'` in HTML. Actually `&apos;` is defined first since HTML 5.
Most modern browsers are capable of that, but its not supported everywhere, especially (like with most internet standards) in IE's.

It would be more safe to replace `'` with `&#39;`, its official HTML representation.

**Comment by jonferreira** [comment]
Well I'm using FF 58 so that's pretty much up to date.

That said I can't see why it would be a "browser rendering issue" given that the same happens with a REST request to /json.htm?type=devices using for example Googles Advanced REST Client and `'` is displayed fine on the Devices tab as shown on the above screenshot.

**Comment by Jarthianur** [comment]
Ok so it's not a browser issue, I admit.

The REST call will of course return the string like `Some&apos;Test` as this is the string returned by the domoticz backend. In the domoticz frontend, this string is then printed directly to the webpage what was the actual reason for this security fix.

This is also why it's displayed correctly when you visit the devices page.

Following information would be necessary to find a solution to your issue.

+ Are other filtered characters also affected? (`< > "`)
+ How is the json response imported to your client?
+ How does the raw HTML look like in that above screenshot showing the issue?

Maybe the device name gets encoded clientside also, then you would see something like this `Some&amp;apos;Test` in the raw page source.

Could you please post the respective raw HTML here?

**Comment by jonferreira** [comment]
`<td id="name" ng-bind="ctrl.item.Name" class="ng-binding">Sofias&amp;apos; Room</td>`

**Comment by jonferreira** [comment]
Did another test with the characters you've mentioned,those look OK

`<td id="name">Relay433 - Momentary ch2 &lt; &gt; "</td>`

Seems to be just the `' `that's missbehaving

**Comment by Jarthianur** [comment]
Ahh that's it.

It seems that the angular client does some modification on it.
You see the `Sofias&amp;apos; Room` ? That's why the apostrophe is not rendered, because the ampersand itself gets encoded.
What I think is also interesting, is that the double quote gets back decoded to plain `"`.

So there is some clientside filtering going on here, but only on some entities.

As I'm not a domoticz developer (just found that sec-issue), I sadly can't help you further.
I think this is a job for the responsible frontend devs now.

**Comment by jonferreira** [comment]
while it does make sense what you've mentioned I'm not sure it's a "frontend issue" to be honest, I see the same bahviour on MQTT and on the Logs...

**Comment by Jarthianur** [comment]
Honestly I don't know why this should affect the logs.
EDIT: Maybe this https://github.com/domoticz/domoticz/blob/494fff71685f319b25e7824684c299162b19f8c3/www/app/LogController.js#L14 one here.

The JSON response is `Biancas&apos; Room`, but the resulting HTML is `Biancas&amp;apos; Room`.
Whatever component is reading that json and injecting it to the html is modifying it. Is there any usage of angulars safehtml filters?

But as I've said, I'm not too deep into that code.

**Comment by jonferreira** [comment]
OK so this is interesting and something I haven't noticed before!

Similar named Z-Wave devices don't have this problem (front end and logs) but instead it seems to be related with Evohome hardware only

```
2018-02-16 09:36:42.924  (Evohome HGI80) Heating (Sofias&apos; Room)
2018-02-16 09:36:42.935  (Evohome HGI80) Heating (Biancas&apos; Room)
2018-02-16 09:53:30.329  (Aeotec Z-Stick Gen5) Light/Switch (Sofias' Room Roller Shutter)
2018-02-16 09:53:30.469  (Aeotec Z-Stick Gen5) Light/Switch (Sofias' Room Roller Shutter)
```

That said the fact that a REST request returns

`"Name" : "Sofias&apos; Room",`

Doesn't make my life any easier given that I now have to update ever logic (node-red) I have

**Comment by Jarthianur** [comment]
Hmm,

as far as I can see, every hardware component is handled by its own class(es) even for the web interface. So it may happen that not every component is effected by that, just because it was left out or whatever.

If other services depend on this json REST API, filtering HTML could definitely lead to problems like that. Hence it would be probably better to return the json response in raw format again and do the filtering consistently in the (angular) frontend.

But this is up to the domoticz devs and a decision I can not make.

**Comment by jonferreira** [comment]
Yes makes sense, lets see what @gizmocuz says about that

**Comment by jonferreira** [comment]
For what is worth Room names are also screwed

**Comment by devrosx** [comment]
hello maybe this problem i noticed in dzvents is same as your problem with encoding
here is link [(http://www.domoticz.com/forum/viewtopic.php?f=59&t=22270)]

**Comment by jonferreira** [comment]
could be, to be honest encoding seems to be a bit of a mess right now :(

**Comment by gizmocuz** [comment]
Maybe we should undo #2105 ? If someone can name devices that causes scripts to be executed, then he/she has already access to domoticz

**Comment by jonferreira** [comment]
I'd say it makes sense but not in a position I can make suggestion to be honest :(

**Comment by Jarthianur** [comment]
I'd say that too.
The component affected by XSS is the domoticz frontend, so as a follow-up maybe involve HTML filters there (ng-bind-html etc...).

**Comment by gizmocuz** [comment]
@Jarthianur , shall i undo the patch and could you have a look at the angular fix maybe ?

**Comment by Jarthianur** [comment]
It's up to you, but I'd say yes, undo the patch.

I'll try to have a look at the angular stuff, but I'm really short of time atm.

**Comment by dwmw2** [comment]
We definitely shouldn't be seeing things like
` "Name" : "Biancas&apos; Room Light",`
in the JSON. That should be a proper JSON representation of the string, without HTML entities. Any escaping of input data should be done on the "client" side, in the HTML/JS in the browser.

**Comment by gizmocuz** [comment]
True, this patch will be reverted in the next beta (code already committed, build system should be ready in 15 minutes)

**Comment by jonferreira** [comment]
Thanks for the path.

Interestingly I had to rename some of the devices in order to get the ' back
