### ISSUE TITLE
Support Osram Lightify on Hue Bridge

### ISSUE THREAD

**Issue by arjanwaard** [domoticz/domoticz#214]
Please add lightning type "Color temperature light" as a dimmable light to PhilipsHue.cpp. Adding this allows the detection of Osram LIghtify lights. 

JSON output of bridge : 
"4": {
    "state": {
      "on": false,
      "bri": 84,
      "ct": 370,
      "alert": "none",
      "colormode": "ct",
      "reachable": true
    },
    "type": "Color temperature light",
    "name": "Woonkamer hoek",
    "modelid": "Classic B40 TW - LIGHTIFY",
    "manufacturername": "OSRAM",
    "uniqueid": "7c:b0:3e:aa:00:14:a5:f4-03",
    "swversion": "1131860",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  }

**Comment by gizmocuz** [comment]
Is it possible you can make a patch ?
RGBW lights have on/bri/sat/hue as parameter, this on has on/bri/ct
dont know what value 'ct' is, and you could probably test this?

**Comment by arjanwaard** [comment]
ct is the Color Temperature axis, see "Color gets more complicated" on http://www.developers.meethue.com/documentation/core-concepts

Value of 500 is the equivalent of 2000K and and 153 is 6500K

**Comment by gizmocuz** [comment]
But that is the level i think, not the color
are you sure this light does not have sat/hue also ?

http://stackoverflow.com/questions/22564187/rgb-to-philips-hue-hsb

Else we should handle this light differently, and internally convert the hue/sat to ct/merik ?

**Comment by arjanwaard** [comment]
No sat/hue values, the only thing settable is the color temperature between 2700K and 6500K.

**Comment by arjanwaard** [comment]
Probably best to add an extra HLTYPE_WHITE where we use the sTypeLimitlessWhite subtype of pTypeLimitlessLights, handle the ct value the same way as sat and hue ? Add Limitless_WarmWhiteIncrease and Limitless_CoolWhiteIncrease as commands ?

**Comment by gizmocuz** [comment]
is this lamp for white light only?
I think there are more types, maybe the RGBW have sat/hue in the json ?

**Comment by arjanwaard** [comment]
This lamp is white only, tunable from 2000K to 6500K.  I think the OSRAM RGBW is reported as "Extended color light".

**Comment by gizmocuz** [comment]
Okey, then i think it is best to check for this light type, check if the json contains sat/hue, if not add it as a white light, else add it as a color light....
Unfortunately i dont have a hue system

**Comment by arjanwaard** [comment]
I think the check for "Color temperature light" type is sufficient. I added this type to the lightning2 check in my patch of PhilipsHUE.cpp. This enables the discovery by Domoticz and adds a slider to set the brightness but lacks the possibility to set the color temperature.
