### ISSUE TITLE
Best way of adding doorbell from rtl433

### ISSUE THREAD

**Issue by mzealey** [domoticz/domoticz#2140]
Hi there, I've added support for Byron doorbell in rtl433 and I would like to put this into domoticz so I can run some actions when doorbell is pressed. Doorbells only really have an ID (and perhaps a melody selector flag) passed in so difficult to auto-create devices based on that (eg standard on/toggle probably wouldn't do it). What do you think would the best approach to integrate this into the domoticz rtl433 code in order to automatically add them, perhaps add a doorbell field in rtl433? Or any better ideas? Just let me know and I'm happy to code it up.

**Comment by gizmocuz** [comment]
It should be handled as a switch. (see the RFXTRX433 implementation code, search for 'chime')
Then once you added the switch, you can edit it, and set it's type to 'switch')
Please use an existing switch type, do not create a new type... for example pTypeGeneralSwitch
