### ISSUE TITLE
Automatically add wind speed, wind direction and gust speed from rtl433

### ISSUE THREAD

**Issue by mzealey** [domoticz/domoticz#2141]
I've got a WH1080 and rtl433 driver picks it up and adds temp/hum and rainfall into domoticz just fine. It also provides the following fields: `speed` (wind speed km/h), `gust` (wind gust speed km/h), `direction_deg` (wind direction degrees from north). It would be great if these can be added in to the parser too please

**Comment by xztraz** [comment]
some kind of policy on weather devices that only give current windspeed would be nice too. gust can be calculated as the maximum reading during a time period and average wind should be the average reading.

**Comment by Muller59** [comment]
@xztraz 

i use the following DzVents script to solve your problem. Hope it helps

`
-- ************************************************************************
-- UpdWindGust - update the windgust information in the sensor fed with
--               KNMI data (via script knmi-weerlive.sh) with windgust
--               information. Define windgust as the max windspeed in the
--               last 10 minutes.
--               The script knmi-weerlive is run every 10 minutes, so to
--               get 10 reading the time needed is 100 minutes (1 hour 40 minutes.)
--
-- Programmer: R. Muller
-- date 2018-12-13
--
-- Version     date        Programmer  Reason
-- ==========  ==========  ==========  
-- 1.0.0       2018-12-13  RM          Initial release
--
-- ************************************************************************

return {
	on = {
		devices = {
			'Buitenstation Wind KNMI'  -- KNMI data, no wind gust info 
		}
	},
	data = {
        windGust = { history = true, maxItems = 10, maxMinutes = 100 } -- declare list
},
	execute = function(domoticz, device)
        -- store current windspeed in data table for later retieval of Max windspeed 
        domoticz.data.windGust.add(device.speed)
        -- update winddevice with current values, adding the gust info.
        local windDevice = domoticz.devices("Buitenstation Wind KNMI")
        windDevice.updateWind(windDevice.direction, 
                              windDevice.directionString, 
                              windDevice.speed, 
                              domoticz.data.windGust.maxSince('01:40:00'), 
                              windDevice.temperature, 
                              windDevice.chill).silent()
        -- domoticz.log('windGust Max is ' .. tostring(domoticz.data.windGust.maxSince('01:40:00') .. 'm/s'), domoticz.LOG_INFO)
		domoticz.log('Device ' .. device.name .. ' was updated with wind gust information', domoticz.LOG_INFO)
	end
}
`

**Comment by waltervl** [comment]
Implemented with https://github.com/domoticz/domoticz/commit/96e3c628df4c7564492fb2ade09f663d129a5cab ??
