### ISSUE TITLE
Support of Cartelectronic TIC Pulse 433Mhz with RFPlayer

### ISSUE THREAD

**Issue by ultrasuperpingu** [domoticz/domoticz#2143]
The RFPlayer firmware V1.23 support a 433Mhz whMeter (https://www.cartelectronic.fr/home/124-tic-pulses-868mhz.html). It would be great to have this supported in domoticz.

**Comment by sweetpants** [comment]
Github is only used for sw issues/bug fixes. I think you better ask this through the forum http://www.domoticz.com/forum/viewforum.php?f=31&sid=2b16876144d20d738ba63b1c66e369d2

**Comment by ultrasuperpingu** [comment]
Ok, sorry about that. I will. Thank you. Do you want me to close this?
