### ISSUE TITLE
Inconsistent HTTP REST interface

### ISSUE THREAD

**Issue by daljian** [domoticz/domoticz#2144]
Hi,
I can turn off a group using 'switchcmd=Off' or 'switchcmd=off'
Like so:
#1 - Off
curl -k 'https://user:pwd@abc123.mynetgear.com:5060/json.htm?type=command&param=switchscene&idx=2&switchcmd=Off' --compressed
#2 - off
curl -k 'https://user:pwd@abc123.mynetgear.com:5060/json.htm?type=command&param=switchscene&idx=2&switchcmd=off' --compressed

So I expect to be able to switch on following same conventions, ie 'switchcmd=On' or 'switchcmd=on'

Like below
#3 - On
curl -k 'https://user:pwd@abc123.mynetgear.com:5060/json.htm?type=command&param=switchscene&idx=2&switchcmd=On' --compressed
#4 - on
curl -k 'https://user:pwd@abc123.mynetgear.com:5060/json.htm?type=command&param=switchscene&idx=2&switchcmd=on' --compressed

In all four cases I get an OK response from Domoticz:
{
   "status" : "OK",
   "title" : "SwitchScene"
}

However in case #4 the group is not switched on.

I'm using following version:
Version: 3.8153
Build Hash: 494fff7
Compile Date: 2017-07-30 12:19:41

My use-case is to setup google home using ifttt.com and pass my command (on or off) to the API, hence I can not influence the case used (On/on). 
My proposal is to accept both On/on and Off/off - Or even be totally case insensitive.

**Comment by gizmocuz** [comment]
The incorrect switch command (lower case) gets translated to OFF, you should follow the JSON API and enter correct values

**Comment by daljian** [comment]
Thanks,
Posting link to the API in case some other user might find this issue and looking for similar information.
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Turn_a_light.2Fswitch_on
