### ISSUE TITLE
RTL433 unable to add -X parameter

### ISSUE THREAD

**Issue by mzealey** [domoticz/domoticz#2145]
I want to add new devices using the flex spec on a rtl433 setup like `-X "Byron_BY_Doorbell:OOK_PWM:500:1000:3300:1200,match={2}0x3,repeats>=4,bits=21"`

However due to https://github.com/domoticz/domoticz/blob/1b93845524466baf1a8b881fc4df0ffafd9d9a15/hardware/Rtl433.cpp#L28 the :s in the spec get stripped which means it cannot start.

**Comment by gizmocuz** [comment]
This is done for security reasons. Maybe the library could be updated to support your device ?

**Comment by mzealey** [comment]
They are increasingly going to add devices like this rather than hard-coded. Certainly on linux colon char is not a problem presumably it was mostly an attempt to stop paths on windows. Is there not an easier library to prevent unwanted execution (like `quotemeta` in perl) or to exec the command without a shell?

**Comment by gizmocuz** [comment]
okey, then you could also rename the binary, and replace the original filename with a script that calls the renamed binary with the command line parameters?
But best if the library is updated, and you update the library/exe on your system (if you have hardware that gets supported)
