### ISSUE TITLE
Python Plugin adds a device without permission to this

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#2146]
3.8922
I have python plugin for ebusd.
Accept new Hardware Devices = false
Plugin adds the device even though it does not have permission

**Comment by gizmocuz** [comment]
Could you point us to the download place of this script ?

**Comment by szczukot** [comment]
https://github.com/guillaumezin/DomoticzEbusd
But I understand that a c++ code call "INSERT INTO DeviceStatus" without permision, andthis is bug for all plugins

**Comment by dnpwwo** [comment]
Pushed a fix for this for the plugin framework.

This is quite a common defect for C++ hardware support code as well (which I didn't fix). From a quick look: BleBox, eHouseTCP, Gpio, HEOS, Kodi, Limitless, LogitechMediaServer, OnkyoAVTCP, OpenWebNetTCP, PanasonicTV, RelayNet, Tellstick, WOL create their own devices and don't respect m_sql.m_bAcceptNewHardware

**Comment by szczukot** [comment]
Yes. I think that m_sql should not be available for modules.

**Comment by gizmocuz** [comment]
All hardware should use the functions in DomoticzHardware.cpp/h when possible

**Comment by gizmocuz** [comment]
I think that those classes should use the methods in DomoticzHardware.cpp to update sensors

**Comment by gizmocuz** [comment]
(As should python, if it is a temp only sensor, use SendTempSensor... yes this might be some rewriting but can also help in feature development, we also have 1 preferred temp sensor type.

**Comment by waltervl** [comment]
Looks to be fixed on Python framework and PR #2174 
Close?
