### ISSUE TITLE
PVOutput not displaying totals in V3.8922

### ISSUE THREAD

**Issue by Aad3229** [domoticz/domoticz#2149]
V3.8922 beta 

I use the "PVOutput (input)" hardware to get the kWh's of my solar panels from PVOutput into Domoticz. Except userid and password for PVOutput there is noting you can customize.
In the latest stable I used, I could see in the utility Tab of Domoticz for my solar panels:

Today xxx kWh, followed by the xxxxx total kWh.

The beta 3.9822 only displays the current day value (see attached picture), however, in Setup/Devices, the total kWh from PVOutput is displayed in the Data column (see attached picture). So the data is coming into Domoticz, but it is not displayed on the Utility Tab on the Solar panels. 

![solar](https://user-images.githubusercontent.com/36635914/36385280-688d37d2-1592-11e8-9c35-b937a05edc5d.JPG)
![solardevice](https://user-images.githubusercontent.com/36635914/36385281-68a2a0fe-1592-11e8-8e45-513b3492c840.JPG)

**Comment by gizmocuz** [comment]
If you click on "Log" and then "Report" do you see your counter value ?
Do you need a total (ever) counter value to be seen 24/7 ? Or is your most interest the today counter the value to see ?

**Comment by Aad3229** [comment]
Hi, This is the report sccreen:
 
I see monthly totals and the total counter value, this total value was on the utility screen before this beta :
![image](https://user-images.githubusercontent.com/36635914/36504308-5d03989c-1750-11e8-9c87-710735f4113d.png)

 
Like with my Gas meter, which still shows the total on the utility screen in the current beta:
![image](https://user-images.githubusercontent.com/36635914/36504334-7636a494-1750-11e8-9f35-f639b85b6efb.png)

 
It would be very nice to have this totals for my “Zonnepanelen” on the utility screen again.

**Comment by gizmocuz** [comment]
Thanks, could you also answer the second question, and with a reason

**Comment by gizmocuz** [comment]
(i would suggest to press also 'Edit' and change the type to 'Return')

**Comment by Aad3229** [comment]
My most interest is the today value counter although it would be nice to have the overall totals in the same view like before.

**Comment by gizmocuz** [comment]
Thats not really a reason, why ? This because it's an increasing counter ... you can see this (if you want) in the report

**Comment by Aad3229** [comment]
In the old version, I could see todays revenue and total revenue in one view (on utility tab). Now I have to click Now I have to do 2 clicks more to go to "log" and then "report" (I enter the total revenue in an Excel sheet). 
If it is not easy for you to get it back like before in one view, then so be it. I will still be a happy Domoticz user.
