### ISSUE TITLE
RGB popup, white slider layout problem

### ISSUE THREAD

**Issue by xztraz** [domoticz/domoticz#2151]
Version: 3.8924
Build Hash: 4b5824be
Compile Date: 2018-02-19 11:50:16
dzVents Version: 2.4.1

Skin:
element-dark

![image](https://user-images.githubusercontent.com/25690871/36387545-8776564a-1599-11e8-9909-2cf3747ed8b6.png)

**Comment by gizmocuz** [comment]
please use our forum. We would like to keep git for coders that supply also patches.

**Comment by xztraz** [comment]
well you rated my patch and made your own that didn't solve the problem. so i think a remaining bug should be documented in a sys with tracking.  Is the forum a better place for bug tracking you say?
