### ISSUE TITLE
"Off Delay" on switch is not working

### ISSUE THREAD

**Issue by Nenodema** [domoticz/domoticz#2155]
Version: 3.8153
Build Hash: 494fff7
Compile Date: 2017-07-30 12:19:41
Platform: Raspberry PI

The "Off Delay" in any kind of switch is not working. It looks like the code completely ignores the configured "Off Delay".
The "On Delay" is working as expected. I have reproduced this problem on two Domoticz instances.

![image](https://user-images.githubusercontent.com/33698556/36425885-a09643ba-1648-11e8-9251-16fe15a923b1.png)

**Comment by sweetpants** [comment]
Try upgrading to the latest Beta first (as the RED forum rules state). For sure it is working there

**Comment by Nenodema** [comment]
Check, i didn't tried that yet. Any idea when a new version (with this fix) will be released?

**Comment by sweetpants** [comment]
I'm on latest Beta and do not have this problem

**Comment by Nenodema** [comment]
@sweetpants 

Thanks for testing. I will close this issue and i hope that a new version will be released soon :-)

**Comment by gizmocuz** [comment]
Please do not close an issue that you consider still open and you created... unless it was no issue

I tested it as well, created a dummy hardware and added a dummy switch.
Set the On-Delay to 10 seconds, and the Off-Delay to 20 seconds, this is the log:

2018-02-21 08:20:33.128  User: Admin initiated a switch command (146/MyDummySwitch/On)
2018-02-21 08:20:43.144  Dummy: Received null operation for Light/Switch
2018-02-21 08:20:43.160  (Dummy) Light/Switch (MyDummySwitch)
2018-02-21 08:21:03.196  (Dummy) Light/Switch (MyDummySwitch)

As you can see, no issues at all, therefor i will close this topic.

Next time, please use the Forum first

**Comment by velkrosmaak** [comment]
If I set the off delay to 300 it works. If I set it to 900, which is the desired time of 15 minutes, it just never turns off. An issue with larger delay times?

**Comment by sweetpants** [comment]
Please use forum first and upgrade to latest Beta first. I'm on latest beta and do not have this issue
