### ISSUE TITLE
Plugin Transport does not support SNI 

### ISSUE THREAD

**Issue by imcfarla2003** [domoticz/domoticz#2156]
Using the internal Connection mechanism to connect to Hive does not work as it requires SNI.
Applying this one line patch fixes it:

```
diff --git a/hardware/plugins/PluginTransports.cpp b/hardware/plugins/PluginTransports.cpp
index 5110422e..dc6d7049 100644
--- a/hardware/plugins/PluginTransports.cpp
+++ b/hardware/plugins/PluginTransports.cpp
@@ -377,6 +377,7 @@ namespace Plugins {
 
                        m_TLSSock = new boost::asio::ssl::stream<boost::asio::ip::tcp::socket&>(*m_Socket, *m_Context);
                        m_TLSSock->lowest_layer().set_option(boost::asio::ip::tcp::no_delay(true));
+                       SSL_set_tlsext_host_name(m_TLSSock->native_handle(), m_IP.c_str());
 
                        //m_TLSSock->set_verify_mode(boost::asio::ssl::verify_peer);
                        m_TLSSock->set_verify_mode(boost::asio::ssl::verify_none);



```

**Comment by gizmocuz** [comment]
As this material was a bit new to me i did some reading, for example here:
https://blog.layershift.com/sni-ssl-production-ready/

It might not be a good idea to enable this as default it looks like, and maybe you could make a command line argument for this ?

**Comment by dnpwwo** [comment]
The argument against SNI seems to be centered around poor support in some browsers (mainly IE) and seems at least a few years old.  The impacted function is initiating client side connections so browsers aren't an issue here. 

I didn't find anything around any security issues associated with it.

How about I run some tests to confirm backwards compatibility and if it seems okay I add it?

The current TLS implementation is still experimental and undocumented so if it causes problems we can revert it.

**Comment by gizmocuz** [comment]
@dnpwwo , if you could do some tests that would be great.
I don't think we have any Windows_XP users anymore since we use a compile flag that causes the software to not run anymore on those obsolete platforms (v141 istead of v141_xp)

**Comment by dnpwwo** [comment]
Initial backwards compatibility testing works fine on sites like Google.

Domoticz acts like a browser that now supports SNI and SSL connection is successful even though Google doesn't use SNI. From a progression test perspective does anyone know a website that does use it?

**Comment by imcfarla2003** [comment]
The hive site does and that works.It is hard to tell if a site does or doesn't use it as browsers completely mask it.On 23 Feb 2018 05:48, dnpwwo <notifications@github.com> wrote:Initial backwards compatibility testing works fine on sites like Google.
Domoticz acts like a browser that now supports SNI and SSL connection is successful even though Google doesn't use SNI. From a progression test perspective does anyone know a website that does use it?

**Comment by imcfarla2003** [comment]
Now committed - cheers
