### ISSUE TITLE
RFE: Split configuration database from data logging database

### ISSUE THREAD

**Issue by dwmw2** [domoticz/domoticz#216]
Embedded devices using flash-based storage — especially the crappy SD/MMC devices with their own built-in translation layer, and using a normal block file system such as ext4 on top — should always be careful to avoid doing too many writes to the device. For long-term embedded use cases, it's best for the file system to be read only.

It would be useful to separate the permanent configuration of Domoticz, from the ongoing data logging. In some cases the former might be kept on the real file system, while the latter can be in a tmpfs and thus _just_ in memory.

It's not the end of the world if that gets lost on a restart, and it _is_ painful if constantly writing to the storage device means the system doesn't boot any more after a few months of operation.

**Comment by gizmocuz** [comment]
i care very much when the logs are lost... this is why we have domoticz
... and those crappy cards, this is the reason why we say to use a class-10 card.

**Comment by dwmw2** [comment]
Separating them gives uses the _option_ of temporary storage for the logs. It certainly wouldn't _force_ you to use temporary storage.

And the class 10 cards might be slightly less crappy than the others but they're still crappy. And it's still a fundamental design flaw to have them pretend to be spinning rust, just to use a traditional block file system on top of them. (cf. http://www.slideshare.net/ennael/dwmw2-kr201209 https://www.youtube.com/watch?v=Aq4P0ced1wI etc.)

Sure, using a better card can buy you time. But for an embedded system which you want to keep working for years, you _really_ don't want to be constantly writing to the same device you need to boot from. Trust me :)

**Comment by gizmocuz** [comment]
using the card for some years now without problems
you can specify the database (user/data path) and point this to a another file system if you want

**Comment by dwmw2** [comment]
I can't split the configuration _(usernames, what devices are attached, etc.)_ from the minute-by-minute temperature readings though, can I? All I'd like to do is have an _option_ to put those in separate sqlite files.

**Comment by gizmocuz** [comment]
If you place the database on a good file system then there is no need for that.. Besides the log is much more important

**Comment by gizmocuz** [comment]
And we have a good build in backup option that can also store it in a remote location

**Comment by dwmw2** [comment]
The problem is that for devices like the Raspberry Pi which have _only_ the one SD card as storage, there isn't a lot you can do. The failure mode is often at the _device_ level — especially when it gets subjected to power failures. So you can't partition it and put the database in a certain partition, because that doesn't help. The only thing that helps is _not_ writing to the SD card at all. My plan was to keep the running logs in a database on tmpfs, _and_ back it up to a remote server (perhaps in real time), and restore it on restart (if possible). But right now, all I wanted to do was have the facility to split long-term from short-term data. It shouldn't even be that hard or intrusive; I can try to knock up a patch which does it.

**Comment by gizmocuz** [comment]
that is not true, you can mount a read/write NFS partition, and let domoticz use this for the database storage
Same for the backup folder, you could make a link to a nfs folder (or other filesystem)
The orange pi has a sata connector if i remember correctly

storing the short-log on a temp-fs, how about when we reboot the pi, will we loose all ?

**Comment by dwmw2** [comment]
I'm not sure I'd want to use NFS for the day-to-day operation. That would mean the NFS server and the routers/switches would need to be on UPS which lasts as long as the Domoticz system. Even if we didn't have any other reliability concerns about NFS.

I would definitely want the system to be able to operate standalone.

What I was thinking was the short-term database in tmpfs and backed up over the network basically in real time (or every five minutes, at least). On a clean shutdown a 'final' backup would be triggered. On startup, we'd restore the short-term database from the server. Those operations could actually be handled by the initscripts, rather than Domoticz itself.

So the common case would be that it all just works and nothing is lost. On an unclean shutdown you might lose the last tiny bit of data — but that you expect anyway, and on SD cards you probably expect to lose a whole lot more on an unclean power failure.

Only if the server is actually absent when you power up, is the shortlog lost. And again, this is a deployment choice — nobody would be _forced_ to put the shortlog in tmpfs. To support this, all we really need on the Domoticz side is to allow the _flexibility_ for the user to deploy it in such a way.

**Comment by Itsmmai** [comment]
Hi, I know this is a very old post but I still have a question about it. dwmw2 is mentioning a different database place. Can someone help me with this. How can I move my database to a different path (and still working off course, I know how the mv command works :-))

thanks for helping !
Ab
