### ISSUE TITLE
NSS_TELEGRAM don't exist in DZVents

### ISSUE THREAD

**Issue by papo-o** [domoticz/domoticz#2166]
Hello,
in DZVents, the Telegram notification is not implemented 
can you ad it?
thanks

**Comment by sweetpants** [comment]
As a workaround you can make a LUA function like:
`local function telegram(msg)
            domoticz.openURL('https://api.telegram.org/"your BOT API key"/sendMessage?chat_id="Your chat-ID"&text=' .. msg)
end`

**Comment by papo-o** [comment]
thanks but bot is missing
the correct syntax would be
`
local function telegram(msg) 
domoticz.openURL('https://api.telegram.org/bot"your BOT API key"/sendMessage?chat_id="Your chat-ID"&text=' .. msg) 
end
`

**Comment by sweetpants** [comment]
You are right, deleted a little too much from my API key, thnx

**Comment by gizmocuz** [comment]
Telegram is implemented. (At least in the beta version)
