### ISSUE TITLE
Python plugins must push values on regular basis to prevent timeout

### ISSUE THREAD

**Issue by guillaumezin** [domoticz/domoticz#2169]
Hello,

I wrote a ebusd plugin. If I don't push values, even the same, at a regular basis, say every 5 minutes, the device becomes red in Domoticz interface. I don't see a way to prevent this, and I don't think it makes sense to push the same value again and again for a device whose value changes very slowly.

The python plugin developper documentation states that we can update the TimedOut flag. I was thinking it was up to the plugin developper to declare when a device handled by the plugin is faulty, but the flag seems ignored, the device doesn't become red if I turn it to 1.

**Comment by flatsiedatsie** [comment]
It would be great if different devices could have their own timeout values.

For example:
- I use Xiaomi Mi Flower Mate sensors, and normal operation is that they are only polled once every day.
- I also have a secure heater device built in MySensors. If that loses communication for more than a minute, that's something I'd like to see reflected in the interface.

**Comment by guillaumezin** [comment]
I agree, and more than that, it would be great to let the plugins completely decide which device they own is timed out or not, based on a refresh time, a loss of communication, etc.

**Comment by guillaumezin** [comment]
I propose a correction is PR #2173

**Comment by dnpwwo** [comment]
So the defect is that the existing plugin controlled time out functionality doesn't work unless Z-Wave is enabled? 

Otherwise is functions as expected?

**Comment by guillaumezin** [comment]
Nope, the timedout parameter given from plugin is ignored if it is not this type of device:

`						(dType == pTypeLighting1) ||
						(dType == pTypeLighting2) ||
						(dType == pTypeLighting3) ||
						(dType == pTypeLighting4) ||
						(dType == pTypeLighting5) ||
						(dType == pTypeLighting6) ||
						(dType == pTypeFan) ||
						(dType == pTypeLimitlessLights) ||
						(dType == pTypeCurtain) ||
						(dType == pTypeBlinds) ||
						(dType == pTypeRFY) ||
						(dType == pTypeChime) ||
						(dType == pTypeThermostat2) ||
						(dType == pTypeThermostat3) ||
						(dType == pTypeThermostat4) ||
						(dType == pTypeRemote) ||
						(dType == pTypeGeneralSwitch) ||
						(dType == pTypeHomeConfort) ||
						((dType == pTypeRadiator1) && (dSubType == sTypeSmartwaresSwitchRadiator)) ||
						((dType == pTypeRego6XXValue) && (dSubType == sTypeRego6XXStatus))`

So for instance, for temperature setpoint, if the plugin doesn't send a value on a regular basis, the device is shown in timeout state, even if is the normal behaviour from the plugin point of view.

The PR changes that so timedout parameter is passed for every device handled by a plugin, it has nothing to do with zwave, except that a portion of the code I moved was just after a zwave timeout piece of code.

**Comment by dnpwwo** [comment]
I had another look and realised github fooled me by collapsing the code so you moved it further than I first thought.  I had forgotten how messy that function is !

Looks fine to me, I do wonder if the web front end will handle this properly for all devices, maybe that's a problem for another day.

**Comment by guillaumezin** [comment]
This is now handled, PR #2173 has been merged
