### ISSUE TITLE
Internal zlib copy

### ISSUE THREAD

**Issue by correa** [domoticz/domoticz#217]
Looking at both Visual Studio project and top level CMakeLists.txt looks like the zlib copy in the zlib folder is not used at all.

CMake tries to find zlib with a find_package, but that will only look the binary library on the system, it won't build our internal copy.

Should we remove it? Should we add it to the build and have a switch an option like we do for sqlite and lua?

**Comment by gizmocuz** [comment]
If it is not used,then we might better remove it....
I thought it was used in the webserver class...
Or with the gz compression...

**Comment by correa** [comment]
I believe it is used, didn't check if there are actual zlib calls. ldd on linux shows it's used, just not our local copy. On linux it gets linked against the system zlib. I guess on windows it's not available, must be an optional feature (?)

**Comment by gizmocuz** [comment]
Correct, windows does not have zlib installed by default
