### ISSUE TITLE
Plugin Framework Request: Uservariables

### ISSUE THREAD

**Issue by febalci** [domoticz/domoticz#2172]
Would it be possible for the Plugin Framework to support Domoticz Uservariables? At the moment there is no way to read or write Domoticz User variable.

**Comment by flatsiedatsie** [comment]
I use python's shelve function to store variables, an idea I stole from the Smart Virtual Thermostat plugin by Logread

**Comment by gizmocuz** [comment]
@febalci , no idea what you mean... If you mean you can not access user variables via the plugin framework (blockly, lua, python) then you are wrong, this is possible

**Comment by gizmocuz** [comment]
No reaction, closing issue, feel free to open it when you can explain more
