### ISSUE TITLE
Double entry for ON Switch

### ISSUE THREAD

**Issue by sineverba** [domoticz/domoticz#2175]
More detail come from here: http://www.domoticz.com/forum/viewtopic.php?p=172688&sid=2e143619c1ebb415a95efeaad0f790d2#p172688

I'm using version 3.8153 on Raspberry Pi3.

I command ON and OFF a relay, via API.

When API initialize the ON command, entry **is twice registered**. When API send OFF, in log there is only one entry.

The issue seems catch from an user:

**"In mainworker.cpp SwitchLight call SwitchLightInt
SwitchLight checks that value is changed or not (and call or not SwitchLightInt)

Tasker from event call directly SwitchLight (and don't check last state of switch)"**

Thank you very much

**Comment by gizmocuz** [comment]
Thanks for reporting, i do not experience this issue when i created a dummy hardware and switch, and using the beta version.

Could you tell me the version of Domoticz you are using?
Did you try with the beta ?
What JSON command did you use? I used:

[(http://127.0.0.1:8080/json.htm?type=command&param=switchlight&idx=99switchcmd=On)]

**Comment by sineverba** [comment]
Thank you. I would not test the beta, 'cause I'm in production. The V is 3.8153.

To set state I call the URL:

`?type=command&param=switchlight&idx=$id_sensor&switchcmd=$new_state`

**Comment by gizmocuz** [comment]
You could install the beta version on another system (maybe a windows system), or you could make a complete backup of your domoticz folder so you can always restore this.
As it seems this error is not there in the beta version i am closing this issue. Please re-open if you still experience this when testing with the beta version.

**Comment by rjblake** [comment]
Got this problem on Beta 3.9043. Sending the command "https://www.mysite.com:8443/json.htm?type=command&param=switchlight&idx=313&switchcmd=On" results in the following entry. Same happens when clicking on the switch button for On or Off
![screen shot 2018-03-13 at 9 31 08 pm](https://user-images.githubusercontent.com/9930554/37368375-59eb3e60-2706-11e8-98b5-760e735b284c.png)

**Comment by sweetpants** [comment]
I'm on latest Beta (V3.9048) and cannot confirm this behaviour. Only one command is send and logged at a time

**Comment by loglux** [comment]
I have the same issue on v4.9796

**Comment by gizmocuz** [comment]
What hardware is being controlled ? For example, if it's zwave, and you have your controller in a group (every group has different meanings) it could be that the node acknowledge the ON/OFF as well

**Comment by loglux** [comment]
No. There are mqtt devices running by ESPurna.  The log shows that the command goes one but Domoticz show it twice in the statistic page

**Comment by Camposmansi** [comment]
The problem they have is the same but it happens to me through MQTT and not through API

**Comment by gizmocuz** [comment]
@Camposmansi , okey, that might be easier to debug for me. So you added a dummy hardware in domoticz, created a virtual switch inside this.
Then you use MQTT to switch this to On or Off and you get two log entries ?
Could you post me the MQTT mosquitto_pub command line message you are sensing ? With this we should be able to debug this

**Comment by Camposmansi** [comment]
@gizmocuz No problem
[893767] [DOMOTICZ] Received value 1 for IDX 108
[893769] [RELAY] #0 scheduled ON in 0 ms
[893771] [RELAY] #0 set to ON
[893784] [MQTT] Sending domoticz/in => {"idx": 108, "nvalue": 1, "svalue": ""} (PID 1)

And duplicate in the https://github.com/xoseperez/espurna/issues/1145

**Comment by gizmocuz** [comment]
@Camposmansi , thanks for the message. Can you also confirm that you used the above procedure to create the switch ?

**Comment by Camposmansi** [comment]
@gizmocuz I create a Dummy switch

**Comment by gizmocuz** [comment]
Tested and there is no issue. So first try from the command line.

```
mosquitto_pub -h 172.16.0.242 -t domoticz/in -m "{\"idx\": 1210, \"nvalue\": 1, \"svalue\": \"\"}"
mosquitto_pub -h 172.16.0.242 -t domoticz/in -m "{\"idx\": 1210, \"nvalue\": 1, \"svalue\": \"\"}"
mosquitto_pub -h 172.16.0.242 -t domoticz/in -m "{\"idx\": 1210, \"nvalue\": 0, \"svalue\": \"\"}"
```

And the log (don't mind the first log, this is created by default when you create the dummy switch):

![image](https://user-images.githubusercontent.com/2265299/46462730-7ed0dc00-c7c2-11e8-8010-1065398369cd.png)

Remember that when you publish a switch command, MQTT of course get's a message back with the current status.

From a second instance listen to the MQTT messages with

` mosquitto_sub -h localhost -t domoticz/#`

**Comment by Camposmansi** [comment]
It keeps happening and I have the last beta, it only happens in domoticz not in home assistant, as you can see these are my messages when I activate the switch

Se ha APAGADO la luz de la Pecera Hass
prueba pecera apagar DomoticZ
prueba pecera apagar DomoticZ 

![image](https://user-images.githubusercontent.com/9553844/46465822-efc7c200-c7c9-11e8-917c-e8ea7d42282b.png)

and I repeat if I turn on the physical switch does not happen, only from inside domoticz and espurna

**Comment by gizmocuz** [comment]
@Camposmansi , can you disable all your events (disable the event system in the settings)
Disable any listeners on your broker
And perform the exact steps i did above (create dummy switch, command line MQTT testing)
Does it happen now ?

**Comment by Camposmansi** [comment]
> @Camposmansi , can you disable all your events (disable the event system in the settings)
> Disable any listeners on your broker
> And perform the exact steps i did above (create dummy switch, command line MQTT testing)
> Does it happen now ?

@gizmocuz 
In command line no problem.
Activated from espurna no problem.
I do not have notifications from domoticz and problem.
I put the notifications by dzevent and activating from domoticz and problem

I inform you that I am not the only one who happens to him, in telegram we are all those who use espurna with the problem

**Comment by gizmocuz** [comment]
@Camposmansi , to be fair... it does not seem a domoticz issue and it is working correctly from the command line.
No idea what 'espurna' is ... do you have a link ?
It could also be a dzVents issue

**Comment by lamptah** [comment]
I have the same behavior as @Camposmansi with domoticz and espurna. I believe the first entry in the log is domoticz doing the switching (publishing MQTT command on domoticz/out), and the second entry is espurna echoing back that the switch has switched by sending a MQTT message to domoticz/in some hundred milliseconds later with the same nvalue as was just commanded in response to the physical state change.

![image](https://user-images.githubusercontent.com/43920495/46707272-36bd1980-cc07-11e8-9eff-cb39830ece17.png)
![image](https://user-images.githubusercontent.com/43920495/46707305-62400400-cc07-11e8-9364-49f65405ca4b.png)


If i disable the espurna domoticz integration (i.e. unsubscribe from domoticz/out), no switching takes place, no reporting of physical state change on domoticz/in, and no double messages in the log.

**Comment by Camposmansi** [comment]
@gizmocuz Hi 
I pass you in link to the git of espurna with the forum of the problem where it says that it is of domoticz
https://github.com/xoseperez/espurna/issues/1145#issuecomment-425712874

**Comment by gizmocuz** [comment]
@Camposmansi , well when you issue a JSON/MQTT to domoticz, it will perform the action, for example when a light switches ON, we log this in the light log.
Of course MQTT needs to be notified that a light has switched on (there might be more MQTT clients depending on this)
"Espurna" receives this, fine, but why does this has to be send back to domoticz ?

Anyway, this it is not a Domoticz issue. It clearly looks "Espurna" is echoing back what it receives.
As you can see what happens when you use the command-line tools, maybe you can ask the developer of "Espurna" to have a quick look at this as well. (Feel free to contact me)

**Comment by Camposmansi** [comment]
Ok, thank you very much, I'll write again and you'll know it
Thank you very much for your time
