### ISSUE TITLE
[Blocky] Sent notification through subsystem Telegram

### ISSUE THREAD

**Issue by HomeServ** [domoticz/domoticz#2177]
I could not find the option to send a notification through the Telegram subsystem.
All other (pushX, http etc.) options are found but not the Telegram one.

Could this be added?

**Comment by sweetpants** [comment]
Please ask these questions through the forum. Telegram support is already in there, maybe you should upgrade first?

**Comment by HomeServ** [comment]
I'm on V3.8944.
Can't find the telegram subsystem. See screenshot;
![capture](https://user-images.githubusercontent.com/7603291/36730411-9ca37bfe-1bc7-11e8-90f8-08664daa9257.PNG)

**Comment by sweetpants** [comment]
As a workround you could always use HTTP if you setup a telegram BOT. 
#TO your chat-id
https://api.telegram.org/"your BOT API key"/sendMessage?chat_id=#TO&text=#MESSAGE

**Comment by HomeServ** [comment]
I'm sorry for forgetting to mention it was for blocky. Thought it was obvious due to "[Blocky]" in the title.
For now I've setup the HTTP subsystem.

**Comment by sweetpants** [comment]
My bad, did not read the tittle...... hope it works with HTTP. Maybe somebody will pick it up and change the code so that it could be selected in Blockly.

**Comment by gizmocuz** [comment]
Telegram notifications are now possible in blockly with the new beta version ( 8973)
