### ISSUE TITLE
Domoticz v3.8975 compiling warnings.

### ISSUE THREAD

**Issue by Alitoy** [domoticz/domoticz#2181]
Orange Pi + 2E, Armbian 3.38.
When compiling Domoticz v3.8975   a lot of warnings:
pi@orangepiplus2e:~/domoticz$ sudo make -j3
[  0%] Built target domoticz_gch
-- Found Git: /usr/bin/git (found version "2.16.2")
[ 12%] Built target lua
[ 19%] Built target mqtt
[ 20%] Built target sqlite
[ 20%] Built target revisiontag
Scanning dependencies of target domoticz
[ 21%] Building CXX object CMakeFiles/domoticz.dir/main/Camera.cpp.o
[ 21%] Building CXX object CMakeFiles/domoticz.dir/main/domoticz.cpp.o
[ 21%] Building CXX object CMakeFiles/domoticz.dir/main/dzVents.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
[ 22%] Building CXX object CMakeFiles/domoticz.dir/main/EventSystem.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
[ 22%] Building CXX object CMakeFiles/domoticz.dir/main/EventsPythonModule.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
[ 22%] Building CXX object CMakeFiles/domoticz.dir/main/EventsPythonDevice.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
......
[ 55%] Building CXX object CMakeFiles/domoticz.dir/hardware/Winddelen.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
/home/pi/domoticz/hardware/USBtin_MultiblocV8.cpp: In member function ‘void USBtin_MultiblocV8::Traitement_SFSP_Switch_Recu(unsigned int, unsigned char, char, char, unsigned int*)’:
/home/pi/domoticz/hardware/USBtin_MultiblocV8.cpp:348:192: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 7 has type ‘long unsigned int’ [-Wformat=]
  _log.Log(LOG_NORM,"MultiblocV8: Receiving SFSP Switch Frame: Id: %s Codage: %d Ssreseau: %d SwitchID: %08X CodeTouche: %02X",NomRefBloc[RefBloc].c_str(),Codage,Ssreseau,SwitchId, codetouche );
                                                                                                                                                                                                ^
[ 55%] Building CXX object CMakeFiles/domoticz.dir/hardware/WOL.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
....
[ 59%] Building CXX object CMakeFiles/domoticz.dir/webserver/proxyclient.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
[ 59%] Linking CXX executable domoticz
[100%] Built target domoticz

I'm not sure if this is a big problem.
It's possible that this is a problem with my Armibian.

**Comment by sweetpants** [comment]
If it only are warnings, and compilation succeeds without errors, it should not be a problem.

**Comment by ben33880** [comment]
make clean before 
make 
should "remove" warning

**Comment by sweetpants** [comment]
Not this one, you should upgrade the gcc compiler to version 6 to get ride of this warning

**Comment by Alitoy** [comment]
**sweetpants**, кight. Everything is compiled and running.
... but it's much better when there are no warnings. )))
**ben33880**, thank you. I'll try the next compilation.
**sweetpants** . I updated the gcc and gcc++ to version 6.3. The next time I update Domotics I will try it with version 6.3.
Another warning confuses me at 55%. :
[ 55%] Building CXX object CMakeFiles/domoticz.dir/hardware/Winddelen.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
/home/pi/domoticz/hardware/USBtin_MultiblocV8.cpp: In member function ‘void USBtin_MultiblocV8::Traitement_SFSP_Switch_Recu(unsigned int, unsigned char, char, char, unsigned int*)’:
/home/pi/domoticz/hardware/USBtin_MultiblocV8.cpp:348:192: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 7 has type ‘long unsigned int’ [-Wformat=]
_log.Log(LOG_NORM,"MultiblocV8: Receiving SFSP Switch Frame: Id: %s Codage: %d Ssreseau: %d SwitchID: %08X CodeTouche: %02X",NomRefBloc[RefBloc].c_str(),Codage,Ssreseau,SwitchId, codetouche );
This warning does not apply to the GSC.

**Comment by ben33880** [comment]
i had the same warnings, because upgrade of gcc.
make clean does the job.

**Comment by sweetpants** [comment]
This is a format warning, that won't get away with a make clean. Just tired it and it comes back, doing a second make will skip it because it compiles succesfully during the previous make.

**Comment by gizmocuz** [comment]
Should be fixed by now
