### ISSUE TITLE
XiaomiGateway new Aqara devices request

### ISSUE THREAD

**Issue by kovainfo** [domoticz/domoticz#2182]
Would it be possible for the Domoticz to support new Aqara devices? At the moment there is no way to use new Aqara wall swithes (1 and 2 buttons models):

2018-03-02 12:31:30.628 XiaomiGateway: unhandled model: ctrl_ln1.aq1
2018-03-02 12:34:59.196 XiaomiGateway: unhandled model: ctrl_ln2.aq1

**Comment by kovainfo** [comment]
Cool!

**Comment by scordal** [comment]
Hello corbinmunce:I have the same problema but I do not know how to implement your fix for 
ctrl_ln1.aq1 issue.
Any friendly instructions on how to apply this fix?
Appreciatte the great woirk you do.

**Comment by kovainfo** [comment]
@scordal 
this is not issue.
use latest beta.
in latest beta this aqara devices works fine!

**Comment by scordal** [comment]
Thanks @kovainfo 
I tried to install the latest beta and the webpages were completelly blank, I could not browse around. So after that I re-updated to stable reléase.
I guess I will have to wait until beta is released.

Thanks
