### ISSUE TITLE
(dzvents) Process LUA scripts on sub-folders - Feature request

### ISSUE THREAD

**Issue by elxsi** [domoticz/domoticz#2189]
Hi,

it would be nice to support the execution of LUA scripts in sub-folders of  /opt/domoticz/scripts/dzVents/scripts. I have a lot of (about 130) different LUA scripts 
which I would like to place in different sub-folders (i.e. lights/, temperature/, alerts/, etc) to better
sort them.

Would this be possible?

Thanks!

**Comment by dannybloe** [comment]
Wow, so many! You know that you can combine related device-events into single scripts? 
Anyway, patches are happily accepted (including unit-tests of course). There is some code that reads  all the files in the folder. That should be adapted to recursively traverse the file-tree. And.. I guess some magic has to be done to be able to require the scripts in subfolders as well.

**Comment by gizmocuz** [comment]
Please continue this discussion on the forum
