### ISSUE TITLE
Static libs

### ISSUE THREAD

**Issue by gordonb3** [domoticz/domoticz#2190]
I suppose it makes sense during experimental phase to use individual configure flags for linking specific dependencies dynamic or static, but it gets kind of messy in production where it doesn't make sense to link one library dynamically and the other one statically.

Therefore: would you please consider grouping this decision under one single configure flag, both for the existing choices and those that may follow?

**Comment by gizmocuz** [comment]
Not sure what you mean by this, but please submit a PR
Not all libraries need to be linked statistically and some do as they might not exist on other systems (or not even in the apt-repo anymore)

**Comment by gordonb3** [comment]
What I am referring to is that because I (need to) compile Domoticz for my system myself there is no reason for me to link common libraries statically. At present this requires me to specify this for multiple dependencies and looking at the way development is going this number of additional defines will grow in the future. And I really do mean require, because I would need to rebuild the libs on my system to provide the static libs as well as I do not have these.

Main point beig: I can't see a reason why one would link one library statically and another one dynamically, in any order. The request is therefore to group these and to put anything that moves form dynamic to static in mainline gets placed in this group as well.

**Comment by gizmocuz** [comment]
might be partly solved with the debian package PR later on
