### ISSUE TITLE
Missing value at Energy Sensor

### ISSUE THREAD

**Issue by mcmellow** [domoticz/domoticz#2196]
Version: 3.8975
Platform: Rpi 2 / Raspbian
Sensor: Electricity (instant and counter) 

At this Energy sensor the value for Total Energy (Data) is missing, only Actual Power (Usage) and (Today Energy (CounterToday) are displayed.
The sensor is updated with the following code in dzVents. But using lua or a json via http gives the same incoplete results.  It is also tested with the different 'default' domoticz user interfaces as well as with Aurora. 

`domoticz.devices(iActPwr).updateElectricity(Power, Energy)
`
Power = The actual power in Watts
Energy = The Total Lifetime Energy in kWh

See also the following forum topics

[Missing value at Energy Sensor](https://www.domoticz.com/forum/viewtopic.php?t=22391)
[Solar panels not showing overall totals](https://www.domoticz.com/forum/viewtopic.php?t=21985)
[Electric (instant+counter) - Domoticz doesn't compute Energy](https://www.domoticz.com/forum/viewtopic.php?t=22117])

Devicetype = Electricity (instant and counter) json output:

```
{
ActTime: 1520336362,
AstrTwilightEnd: "20:19",
AstrTwilightStart: "05:19",
CivTwilightEnd: "18:59",
CivTwilightStart: "06:38",
DayLength: "11:13",
NautTwilightEnd: "19:39",
NautTwilightStart: "05:59",
ServerTime: "2018-03-06 12:39:22",
SunAtSouth: "12:05",
Sunrise: "07:12",
Sunset: "18:25",
result: [
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CounterToday: "4.186 kWh",
CustomImage: 0,
Data: "401.075 kWh",
Description: "",
Favorite: 1,
HardwareID: 8,
HardwareName: "Energy",
HardwareType: "Dummy (Does nothing, use for virtual switches only)",
HardwareTypeVal: 15,
HaveTimeout: false,
ID: "00082068",
LastUpdate: "2018-03-06 12:39:01",
Name: "Actueel Vermogen SE",
Notifications: "false",
Options: "1",
PlanID: "4",
PlanIDs: [
4
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "kWh",
SwitchTypeVal: 4,
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Usage: "1644 Watt",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "68"
}
],
status: "OK",
title: "Devices"
}
```
![electricitydevice](https://user-images.githubusercontent.com/15740537/37044842-d652d19a-2164-11e8-93dd-7b81877afbe1.png)

**Comment by gizmocuz** [comment]
This is intended by a recent change to cleanup all sensors
Anyway, this is an always increasing value and you can display this in the report view

**Comment by mcmellow** [comment]
Understanding your comment correctly. I Know Energy is an always increasing value and I can think of a dozen other ways to display the Energy. But I used this sensor to show just both the Power and the Energy.
My question: Can and will this sensor be fixed in order to display both, the Power and Energy again as it does before. Like I found it in f.i in the dzVents documentation.

**kWh, Electricity (instant and counter)**
counterToday: Number.
updateElectricity(power, energy): Function. Supports command options.
usage: Number.
WhToday: Number. Total Wh usage of the day. Note the unit is Wh and not kWh!
WhTotal: Number. Total Wh usage.
WhActual: Number. Actual reading.

**Comment by mcmellow** [comment]
@gizmocuz   An update:
When the atttribute **CounterToday** == 0  Then the value for Energy (attribute **data**) is displayed at after the word today. 
When the atttribute **CounterToday** <> 0  then the value for **CounterToday** is displayed at after the word today.
So odd things are happening with this sensor

**Comment by mcmellow** [comment]
@gizmocuz 
The topics
[Domoticz doesn't show total kWh anymore](https://www.domoticz.com/forum/viewtopic.php?f=28&t=21613&p=174970#p174970)
[Electric (instant+counter) - Domoticz doesn't compute Energy](https://www.domoticz.com/forum/viewtopic.php?f=59&t=22117&p=174879#p174879) 
are also about the same issue.
So more and more users are asking about it. Please can you give an update about the status of this issue

**Comment by sweetpants** [comment]
GizMoCuz already answered this question "_This is intended by a recent change to cleanup all sensors
Anyway, this is an always increasing value and you can display this in the report view_"

**Comment by mcmellow** [comment]
@sweetpants   Does this means it is removed from this sensor? How this this work? Where can I found this?  Sorry about my ignorance about it.

**Comment by sweetpants** [comment]
That is how i read it, it's removed.
![total energy](https://user-images.githubusercontent.com/23421160/37566212-6d7c77c4-2ab6-11e8-8ae0-4c4ade30c38e.png)

**Comment by mcmellow** [comment]
@sweetpants  Sorry, but it is still unclear to me. I see also the total Energy in the report and in the attributes with a json command.  But not on the sensor.
The reaction from @gizmocuz is cryptic to me.  There are no reactions on questions and updates on this issue nor on the topics about on the forum. Can't find any explanation in the documentation. It is all very vague.

**Comment by gizmocuz** [comment]
It has been removed, and you can see it in the report. This is what i always wrote. So what you experience is intended, and not vague !
