### ISSUE TITLE
Feature request: panel to define text to send to nodes

### ISSUE THREAD

**Issue by GertSanders** [domoticz/domoticz#220]
In de settings panel of the notifications, maybe we can extend this with a text edit field to define a text to be sent, a dropdown showing all V_TEXT capable sensors and a button for CLEAR or SEND.

It would make sense to add it there, because you could consider sending a string in V_TEXT to a node as a "notification" action.

**Comment by gizmocuz** [comment]
I think this is only for mysensors ?
Maybe you could add a switch to your sketch, if this is triggered, you 'request' the V_TEXT ?
then when you have a notification, you also switch that switch (via blockly)

**Comment by empierre** [comment]
you could imagine this to any system that does text to speech... for example I can make a JSON request to the imperihome client that can also works as a server and make a TTS from a string sent to it.
The V_TEXT is interresting as a notion for it has a value that is either received or sent to a node, so you have the last official status of the string. It is to me a bit like the TEXT dummy sensor but with the send/receive capacity

**Comment by GertSanders** [comment]
Well, obviously the idea started from using MySensors. But I wonder why you can send van V_TEXT from node to node or to controller and not fron controller to node. You can send commands to a node, why not text then?
Thruth be told, I think your proposal is a hack for lack of a better solution. Why does a node always need to request text? This is a good idea for nodes that sleep a lot, but not ideal for nodes that are always on.

**Comment by gizmocuz** [comment]
true, but not easily implemented on this side

**Comment by empierre** [comment]
In fact this is more a Vera initial behavior: a device has sates and
configurations values you can see in its definition.

From there you can modify one or the other.

Some will be sent to the node, e.g. zwave configuration change, some are
pure "internal", this is an extendable model this way.

Text is just a part of it, if this text is a RGB value this could change a
node RGB for example. If this is a integer, this could set the water meter
current reported index if this shifted for some reason.

There is always a good use of this. We coiuld say this is half a way of you
user variables but extended.

**Comment by gizmocuz** [comment]
agree, but now, not easily implemented

**Comment by OliverHi** [comment]
I am having the same problem (I need to send V_Text to a node from domoticz). Any updates? Will this be implemented (soon)?
At least for me as a user its strange that this is missing... I can also send other values like RGB color back to the nodes.

**Comment by gizmocuz** [comment]
Best to help with development

**Comment by sushukka** [comment]
Any update with this? There are more and more hacks being made around this. Extra switches, dummy sketch loops, dimmer hacking, scripts bypassing Domoticz etc. I alone have already around dozen of scripts and dummy sensors getting around this bug. People need some way to pass parameters back to MySensors nodes; it's in the very core in any even slightly advanced home automation building.

It's hard to understand why it is so complicated to have Domoticz initiate an update to the node when the V_TEXT sensor is changed. Switches, dimmers have two-side communication and they pass different values. MySensors nodes handle the V_TEXT input like any other inputs in their receive function. I tested this with OpenHAB: changed V_TEXT sensor value on OpenHAB and the update was nicely sent to the node without any extra hacking or similar.

This is really starting to get in the nerves and according to forums I'm definitely not alone. So far I have around 100 active sensors/IDXs in my home and this is the only place with Domoticz where I have to do things in a dirty way.  I'm not in anyway an advanced developer so I have problems to see why this is so complicated. Could someone pretty please give a short explanation why? Example: I have a dummy selector switch which has http/json update commands in action fields to update a V_TEXT variable. V_TEXT variable is updated fine, but nothing is sent to the actual node. To a noob outsider why not: if V_TEXT is updated --> send normal MySensors message "node:child:command:ack:type:payload"?
