### ISSUE TITLE
event when client connects to server - Feature Request

### ISSUE THREAD

**Issue by f-verani** [domoticz/domoticz#2200]
It would be great to have a way to run a script or equivalent when someone connects to the server through web browser.
Behind this request, I have many variables that I want to update to get current state. There are only for end user. For the moment, I run some scripts every 5/10 min depending on importance.

**Comment by sweetpants** [comment]
Please use the forum for such requests. Github is only used for bugs and problems

**Comment by gizmocuz** [comment]
You will already receive a message (IP, and with authentication also the username)
