### ISSUE TITLE
General alert device don't send is own state by mqtt

### ISSUE THREAD

**Issue by gibbo520** [domoticz/domoticz#2201]
General alert device don't send is own state by mqtt

**Comment by gizmocuz** [comment]
I need way more information to debug this.
What do you mean by this, and how can i replicate this ?

**Comment by gibbo520** [comment]
Hi !
so how to replicate :
install mosquitto server and mosquitto-client 
in hardware add mqtt client 
create virtual hardware and add a new type alarm
now form ssh subscribe to topic domoticz/out  

 like mosquitto_sub -h 127.0.0.1 -t domoticz/out

now you can see topic like switch etc …

now from second shell try to change status of new hw alarm created 

wget -o /dev/null "http://127.0.0.1:8080/json.htm?type=command&param=udevice&idx=your alarmidx&nvalue=4&svalue=4”     #alarm
wget -o /dev/null "http://127.0.0.1:8080/json.htm?type=command&param=udevice&idx=your alarmidx&nvalue=0&svalue=0”     #normal


let me know :)

I’m here if u need details 

Bye :)



Il giorno 11 mar 2018, alle ore 13:14, gizmocuz <notifications@github.com> ha scritto:

I need way more information to debug this.
What do you mean by this, and how can i replicate this ?

**Comment by gizmocuz** [comment]
Tested against latest beta (sensor type = alert), and working without problems

> {
>    "Battery" : 255,
>    "RSSI" : 12,
>    "description" : "",
>    "dtype" : "General",
>    "id" : "83096",
>    "idx" : 1096,
>    "name" : "MyAlarm",
>    "nvalue" : 4,
>    "stype" : "Alert",
>    "svalue1" : "4",
>    "unit" : 1
> }
>
