### ISSUE TITLE
Cosmetic issue

### ISSUE THREAD

**Issue by gn33** [domoticz/domoticz#2203]
Cosmetic issue :
![image](https://user-images.githubusercontent.com/37216119/37210650-cb21fb24-23a9-11e8-8570-846dd00a62e4.png)

![image](https://user-images.githubusercontent.com/37216119/37210678-e0b5bc46-23a9-11e8-9edf-77577a9430f6.png)

**Comment by gizmocuz** [comment]
Do you have the first (RGB) cosmetic issue also with the default theme ?
And yes sure that second one is crazy! You should use the dropdown method

**Comment by gn33** [comment]
No issue for RGB with defaut theme but same issue for the cube with default theme.

**Comment by gizmocuz** [comment]
Then it is best to report this to the author of this theme or supply a patch for those themes
