### ISSUE TITLE
Unit issue xiaomi temp HR% pressure

### ISSUE THREAD

**Issue by gn33** [domoticz/domoticz#2204]
![image](https://user-images.githubusercontent.com/37216119/37210785-35c2ff96-23aa-11e8-9bb7-e38ded8c1c24.png)

With the last xiaomi sensor (temp HR% pressure)
Unit must be mbar instead of bar

**Comment by gizmocuz** [comment]
so this should read 1.0 bar ? You can change this in the code

**Comment by gn33** [comment]
Can explain me more how to change unit in mBar or hpa because in weather we don't use Bar.

Thanks for you help

**Comment by DAVIZINH0** [comment]
hello, same problem. How can i modify the scale?

**Comment by gizmocuz** [comment]
The programmer of this hardware class could use a custom sensor for this
