### ISSUE TITLE
Add PHP(7) as Event language

### ISSUE THREAD

**Issue by bertoost** [domoticz/domoticz#2207]
Since PHP is one of the popular programming languages, it's maybe a good idea to add it as language for the event scripts. Lately I have updated and saw python was added too.
I tried myself, but no luck.
Would be great to have PHP as event language available too.

**Comment by gizmocuz** [comment]
Thanks for the suggestion!
Yes we have python for quite some time now, also LUA (dzVents) and script call support.
I would suggest that you take a look at dzVents.
If this is not working out for you (but i think it is), then you can always call your own python scripts, but i think we have enough scripting languages at the moment
