### ISSUE TITLE
Switch Type Door Contact - choose icon.

### ISSUE THREAD

**Issue by dmonty2** [domoticz/domoticz#2212]
Domoticz is a wonderful project.  I have several reed switches on doors, windows, garage doors, sliding doors.  However I can not match up the icons.

When choosing Switch Type: "Door Contact" it always shows the Door icon.  Type "Door Contact" doesn't give me an option to change the icon like the "On/Off" type does.

Please update the "Door Contact" type to support changing it's icon.  I have reed switches installed on windows, garage doors, and sliding doors and it would be wonderful if I could use matching icons.

**Comment by ivooovi** [comment]
Hi dmonty2,
did you try adding your own custom icons?  See also 
 https://www.domoticz.com/wiki/Custom_icons_for_webinterface for more info. 

You might also want to check the forum

**Comment by dmonty2** [comment]
@ivooovi - yes I added a custom icon and submitted it to domoticzicons@gmail.com.

This ticket is a request to have Domoticz switch type: "Door Contact" have the ability to change icon from a door icon to any other type of icon.  Right now it is locked into door-icon-only.


"On Off" has icon selector:
![on_off_has_icon_selector](https://user-images.githubusercontent.com/1381071/37507076-2924e24a-28aa-11e8-8501-70ec5c46a7c0.png)

"Door Contact" has no icon selector:
![door_contact_no_icons](https://user-images.githubusercontent.com/1381071/37507084-35c7c170-28aa-11e8-9f57-a0db83fd41bf.png)

**Comment by mvveelen** [comment]
I second that. Would like to have separate icons for doors and windows.

**Comment by gizmocuz** [comment]
@dmonty2 , but you can do what you want with the On/Off and custom icon correct?

**Comment by pbda** [comment]
@gizmocuz : No because "On/Off" has the ability to be switched on user interface. "Contact "or "Door Contact" is a readonly switch which cannot be changed on user interface. Using "On/Off" should be confusing for the user.

**Comment by dmonty2** [comment]
@gizmocuz, yes I'm using an On/Off right now to apply custom window and garage icons for aesthetics.  However, as @pbda mentioned, this is confusing as a reed switch is read-only.

**Comment by gizmocuz** [comment]
Currently you have to choose 'Door Contact', and yes, it is currently not possible to change the icon of this

**Comment by pbda** [comment]
Generally speaking, it would be nice to have a generic switch from which to choose:

- can be switched On
- can be switched Off
- icon
- label when On: On, Open, Armed, Locked...
- label when Off: Off, Closed, Disarmed...

For example, I have a Contact which indicates if my alarm is armed. I would like to have:
- can't be switched on user interface
- icon: Alarm
- label when On: Armed,
- label when Off: Disarmed

**Comment by gizmocuz** [comment]
As said, a door contact for now

**Comment by gohamstergo** [comment]
any news on this happening?

**Comment by colani** [comment]
Love to see this option

**Comment by gizmocuz** [comment]
@colani , this has been already implemented in the beta version for a long time now

**Comment by kini24** [comment]
Well, how about Geofencing? This is also a read-only switch. To hell with the icon, but I can also change the status of this switch manually.
