### ISSUE TITLE
Error while compiling V3.9031.

### ISSUE THREAD

**Issue by Alitoy** [domoticz/domoticz#2214]
Error while compiling V3.9031. (Orange Pi + 2E, Armbian 5.38)
The compilation did not end. (only 78%)
(
pi@orangepiplus2e:~$ gcc --version
gcc (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04) 6.3.0 20170519
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
)
Help. What to do ?

****
.....
[ 28%] Building CXX object CMakeFiles/domoticz.dir/hardware/1Wire.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
In file included from /usr/include/c++/6/algorithm:62:0,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:37,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/boost/date_time/time_clock.hpp:17,
                 from /usr/include/boost/thread/thread_time.hpp:9,
                 from /usr/include/boost/thread/lock_types.hpp:18,
                 from /usr/include/boost/thread/pthread/thread_data.hpp:12,
                 from /usr/include/boost/thread/thread_only.hpp:17,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from /home/pi/domoticz/main/stdafx.h:57,
                 from <command-line>:0:
/usr/include/c++/6/bits/stl_algo.h: In function ‘_RandomAccessIterator std::__find_if(_RandomAccessIterator, _RandomAccessIterator, _Predicate, std::random_access_iterator_tag) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<long long unsigned int*, std::vector<long long unsigned int> >; _Predicate = __gnu_cxx::__ops::_Iter_equals_val<const long long unsigned int>]’:
/usr/include/c++/6/bits/stl_algo.h:112:5: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<long long unsigned int*, std::vector<long long unsigned int> >’ will change in GCC 7.1
     __find_if(_RandomAccessIterator __first, _RandomAccessIterator __last,
     ^~~~~~~~~
/usr/include/c++/6/bits/stl_algo.h:112:5: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<long long unsigned int*, std::vector<long long unsigned int> >’ will change in GCC 7.1
/usr/include/c++/6/bits/stl_algo.h: In member function ‘void CWebSocketPush::OnDeviceReceived(int, long long unsigned int, const string&, const unsigned char*)’:
/usr/include/c++/6/bits/stl_algo.h:162:43: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<long long unsigned int*, std::vector<long long unsigned int> >’ will change in GCC 7.1
          std::__iterator_category(__first));
                                           ^
/usr/include/c++/6/bits/stl_algo.h: In member function ‘void CWebSocketPush::UnlistenTo(long long unsigned int)’:
/usr/include/c++/6/bits/stl_algo.h:162:43: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<long long unsigned int*, std::vector<long long unsigned int> >’ will change in GCC 7.1
          std::__iterator_category(__first));
                                           ^
/usr/include/c++/6/bits/stl_algo.h: In member function ‘bool CWebSocketPush::WeListenTo(long long unsigned int)’:
/usr/include/c++/6/bits/stl_algo.h:162:43: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<long long unsigned int*, std::vector<long long unsigned int> >’ will change in GCC 7.1
          std::__iterator_category(__first));
                                           ^
/usr/include/c++/6/bits/stl_algo.h: In member function ‘void CWebSocketPush::ListenTo(long long unsigned int)’:
/usr/include/c++/6/bits/stl_algo.h:162:43: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<long long unsigned int*, std::vector<long long unsigned int> >’ will change in GCC 7.1
          std::__iterator_category(__first));
                                           ^
[ 29%] Building CXX object CMakeFiles/domoticz.dir/hardware/1Wire/1WireByOWFS.cpp.o
....
[ 77%] Building CXX object CMakeFiles/domoticz.dir/notifications/NotificationLogitechMediaServer.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
[ 78%] Building CXX object CMakeFiles/domoticz.dir/tcpserver/TCPClient.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
[ 78%] Building CXX object CMakeFiles/domoticz.dir/tcpserver/TCPServer.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
[ 78%] Building CXX object CMakeFiles/domoticz.dir/webserver/proxyclient.cpp.o
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
[ 78%] Linking CXX executable domoticz
CMakeFiles/domoticz.dir/hardware/BleBox.cpp.o: In function `BleBox::GetApiDeviceState(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
BleBox.cpp:(.text+0xc34): undefined reference to `Json::Value::Value(Json::Value&&)'
BleBox.cpp:(.text+0xc82): undefined reference to `Json::Value::Value(Json::Value&&)'
CMakeFiles/domoticz.dir/hardware/LogitechMediaServer.cpp.o: In function `CLogitechMediaServer::Query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
LogitechMediaServer.cpp:(.text+0x4c4): undefined reference to `Json::Value::Value(Json::Value&&)'
LogitechMediaServer.cpp:(.text+0x548): undefined reference to `Json::Value::Value(Json::Value&&)'
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:6009: recipe for target 'domoticz' failed
make[2]: *** [domoticz] Error 1
CMakeFiles/Makefile2:71: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
pi@orangepiplus2e:~/domoticz$
****

Thank you in advance for your help ! )))

**Comment by gizmocuz** [comment]
Did you follow

https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source

**Comment by Alitoy** [comment]
Thanks for the answer.
I began to do everything according to the instructions.
Updated boost to 1.66.0
Began to compile.
Several times a warning appeared, compiler report "note":
 ....will change in GCC 7.1

Do I need to update the GCS to version 7.1?

**Comment by Alitoy** [comment]
For example : 
[ 94%] Building CXX object CMakeFiles/domoticz.dir/json/json_writer.cpp.o
In file included from /usr/include/c++/6/map:60:0,
                 from /usr/local/include/boost/date_time/gregorian/greg_month.hpp:18,
                 from /usr/local/include/boost/date_time/gregorian/greg_ymd.hpp:16,
                 from /usr/local/include/boost/date_time/gregorian/greg_calendar.hpp:17,
                 from /usr/local/include/boost/date_time/gregorian/gregorian_types.hpp:19,
                 from /usr/local/include/boost/date_time/posix_time/posix_time_config.hpp:18,
                 from /usr/local/include/boost/date_time/posix_time/posix_time_system.hpp:13,
                 from /usr/local/include/boost/date_time/posix_time/ptime.hpp:12,
                 from /usr/local/include/boost/date_time/posix_time/posix_time_types.hpp:12,
                 from /usr/local/include/boost/thread/thread_time.hpp:11,
                 from /usr/local/include/boost/thread/lock_types.hpp:18,
                 from /usr/local/include/boost/thread/pthread/thread_data.hpp:12,
                 from /usr/local/include/boost/thread/thread_only.hpp:17,
                 from /usr/local/include/boost/thread/thread.hpp:12,
                 from /usr/local/include/boost/thread.hpp:13,
                 from /home/pi/domoticz/main/stdafx.h:57:
/usr/include/c++/6/bits/stl_tree.h: In member function ‘std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::iterator std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_emplace_hint_unique(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::const_iterator, _Args&& ...) [with _Args = {const std::piecewise_construct_t&, std::tuple<const Json::Value::CZString&>, std::tuple<>}; _Key = Json::Value::CZString; _Val = std::pair<const Json::Value::CZString, Json::Value>; _KeyOfValue = std::_Select1st<std::pair<const Json::Value::CZString, Json::Value> >; _Compare = std::less<Json::Value::CZString>; _Alloc = std::allocator<std::pair<const Json::Value::CZString, Json::Value> >]’:
/usr/include/c++/6/bits/stl_tree.h:2193:7: **note**: parameter passing for argument of type ‘std::_Rb_tree<Json::Value::CZString, std::pair<const Json::Value::CZString, Json::Value>, std::_Select1st<std::pair<const Json::Value::CZString, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<const Json::Value::CZString, Json::Value> > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const Json::Value::CZString, Json::Value> >}’ **will change in GCC 7.1**
       _Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6/bits/stl_tree.h: In function ‘std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::iterator std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_insert_unique_(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::const_iterator, _Arg&&, _NodeGen&) [with _Arg = std::pair<const Json::Value::CZString, Json::Value>&; _NodeGen = std::_Rb_tree<Json::Value::CZString, std::pair<const Json::Value::CZString, Json::Value>, std::_Select1st<std::pair<const Json::Value::CZString, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<const Json::Value::CZString, Json::Value> > >::_Alloc_node; _Key = Json::Value::CZString; _Val = std::pair<const Json::Value::CZString, Json::Value>; _KeyOfValue = std::_Select1st<std::pair<const Json::Value::CZString, Json::Value> >; _Compare = std::less<Json::Value::CZString>; _Alloc = std::allocator<std::pair<const Json::Value::CZString, Json::Value> >]’:
/usr/include/c++/6/bits/stl_tree.h:1989:7: **note**: parameter passing for argument of type ‘std::_Rb_tree<Json::Value::CZString, std::pair<const Json::Value::CZString, Json::Value>, std::_Select1st<std::pair<const Json::Value::CZString, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<const Json::Value::CZString, Json::Value> > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const Json::Value::CZString, Json::Value> >}’ **will change in GCC 7.1**
       _Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6/bits/stl_tree.h:1989:7: note: parameter passing for argument of type ‘std::_Rb_tree<Json::Value::CZString, std::pair<const Json::Value::CZString, Json::Value>, std::_Select1st<std::pair<const Json::Value::CZString, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<const Json::Value::CZString, Json::Value> > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const Json::Value::CZString, Json::Value> >}’ will change in GCC 7.1
/usr/include/c++/6/bits/stl_tree.h: In member function ‘Json::Value& Json::Value::operator[](Json::Value::ArrayIndex)’:
/usr/include/c++/6/bits/stl_tree.h:950:65: **note**: parameter passing for argument of type ‘std::_Rb_tree<Json::Value::CZString, std::pair<const Json::Value::CZString, Json::Value>, std::_Select1st<std::pair<const Json::Value::CZString, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<const Json::Value::CZString, Json::Value> > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const Json::Value::CZString, Json::Value> >}’ **will change in GCC 7.1**
    return _M_insert_unique_(__pos, std::forward<_Arg>(__x), __an);
                                                                 ^
In file included from /usr/include/c++/6/map:61:0,
                 from /usr/local/include/boost/date_time/gregorian/greg_month.hpp:18,
                 from /usr/local/include/boost/date_time/gregorian/greg_ymd.hpp:16,
                 from /usr/local/include/boost/date_time/gregorian/greg_calendar.hpp:17,
                 from /usr/local/include/boost/date_time/gregorian/gregorian_types.hpp:19,
                 from /usr/local/include/boost/date_time/posix_time/posix_time_config.hpp:18,
                 from /usr/local/include/boost/date_time/posix_time/posix_time_system.hpp:13,
                 from /usr/local/include/boost/date_time/posix_time/ptime.hpp:12,
                 from /usr/local/include/boost/date_time/posix_time/posix_time_types.hpp:12,
                 from /usr/local/include/boost/thread/thread_time.hpp:11,
                 from /usr/local/include/boost/thread/lock_types.hpp:18,
                 from /usr/local/include/boost/thread/pthread/thread_data.hpp:12,
                 from /usr/local/include/boost/thread/thread_only.hpp:17,
                 from /usr/local/include/boost/thread/thread.hpp:12,
                 from /usr/local/include/boost/thread.hpp:13,
                 from /home/pi/domoticz/main/stdafx.h:57:
/usr/include/c++/6/bits/stl_map.h: In member function ‘bool Json::Value::removeIndex(Json::Value::ArrayIndex, Json::Value*)’:
/usr/include/c++/6/bits/stl_map.h:483:4: note: parameter passing for argument of type ‘std::_Rb_tree<Json::Value::CZString, std::pair<const Json::Value::CZString, Json::Value>, std::_Select1st<std::pair<const Json::Value::CZString, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<const Json::Value::CZString, Json::Value> > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const Json::Value::CZString, Json::Value> >}’ will change in GCC 7.1
    __i = _M_t._M_emplace_hint_unique(__i, std::piecewise_construct,
    ^~~
In file included from /usr/include/c++/6/map:60:0,
                 from /usr/local/include/boost/date_time/gregorian/greg_month.hpp:18,
                 from /usr/local/include/boost/date_time/gregorian/greg_ymd.hpp:16,
                 from /usr/local/include/boost/date_time/gregorian/greg_calendar.hpp:17,
                 from /usr/local/include/boost/date_time/gregorian/gregorian_types.hpp:19,
                 from /usr/local/include/boost/date_time/posix_time/posix_time_config.hpp:18,
                 from /usr/local/include/boost/date_time/posix_time/posix_time_system.hpp:13,
                 from /usr/local/include/boost/date_time/posix_time/ptime.hpp:12,
                 from /usr/local/include/boost/date_time/posix_time/posix_time_types.hpp:12,
                 from /usr/local/include/boost/thread/thread_time.hpp:11,
                 from /usr/local/include/boost/thread/lock_types.hpp:18,
                 from /usr/local/include/boost/thread/pthread/thread_data.hpp:12,
                 from /usr/local/include/boost/thread/thread_only.hpp:17,
                 from /usr/local/include/boost/thread/thread.hpp:12,
                 from /usr/local/include/boost/thread.hpp:13,
                 from /home/pi/domoticz/main/stdafx.h:57:
/usr/include/c++/6/bits/stl_tree.h: In member function ‘Json::Value& Json::Value::resolveReference(const char*)’:
/usr/include/c++/6/bits/stl_tree.h:950:65: note: parameter passing for argument of type ‘std::_Rb_tree<Json::Value::CZString, std::pair<const Json::Value::CZString, Json::Value>, std::_Select1st<std::pair<const Json::Value::CZString, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<const Json::Value::CZString, Json::Value> > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const Json::Value::CZString, Json::Value> >}’ **will change in GCC 7.1**
    return _M_insert_unique_(__pos, std::forward<_Arg>(__x), __an);
                                                                 ^
/usr/include/c++/6/bits/stl_tree.h: In member function ‘Json::Value& Json::Value::resolveReference(const char*, const char*)’:
/usr/include/c++/6/bits/stl_tree.h:950:65: note: parameter passing for argument of type ‘std::_Rb_tree<Json::Value::CZString, std::pair<const Json::Value::CZString, Json::Value>, std::_Select1st<std::pair<const Json::Value::CZString, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<const Json::Value::CZString, Json::Value> > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const Json::Value::CZString, Json::Value> >}’ **will change in GCC 7.1**
    return _M_insert_unique_(__pos, std::forward<_Arg>(__x), __an);
                                                                 ^
[ 95%] Building CXX object CMakeFiles/domoticz.dir/tinyxpath/action_store.cpp.o

Update GCC to 7.1 ?

**Comment by gizmocuz** [comment]
no, and warnings are not errors. Great it is working now

**Comment by Alitoy** [comment]
**gizmocuz**,  thank you !
