### ISSUE TITLE
Light On/Off script actions are not working correctly for Dummy hardware

### ISSUE THREAD

**Issue by NichUK** [domoticz/domoticz#2216]
Using Beta channel, Version: 3.8976, Build Hash: f4e68d7f, Compile Date: 2018-03-07 07:43:30
Running as a service on Windows 10

I have some Tuya compatible sockets, which I have managed to control remotely. I created batch files to turn sockets on/off. I created a "Dummy" device in Dometicz to use as a controller, and added a switch to that.

I put the batch files in Dometicz\scripts and checked that they worked correctly from there. I think wired them up into On and Off actions inside the switch:
```
OnAction: script://Domoticz\scripts\TuyaTerraceLeftOn.bat
OffAction: script://Domoticz\scripts\TuyaTerraceLeftOff.bat
```
When trying to switch on, nothing happens, and the log shows:
```
2018-03-11 11:49:20.673 User: Admin initiated a switch command (38/Terrace Left/On)
2018-03-11 11:49:20.707 Error: SQLHelper: Error script not found 'Domoticz\scripts\TuyaTerraceLeftOn.bat'
2018-03-11 11:49:20.709 (Virtual Device) Light/Switch (Terrace Left)
```
When trying to switch off, nothing happens, and the log shows:
```
2018-03-11 11:50:37.774 User: Admin initiated a switch command (38/Terrace Left/Off)
2018-03-11 11:50:37.810 (Virtual Device) Light/Switch (Terrace Left)
```
This leads me to believe that something is wrong with the selection of the path for the On action (as the scripts are both present in the directory, with permissions that should be good. (I set that folder to Everyone: List, Read, Execute just to make sure, although LocalSystem should have full permissions anyway).
The Off action doesn't complain that it can't find the script, but doesn't seem to run it correctly, as nothing happens.

Nich

**Comment by NichUK** [comment]
I should add, that I then wrote a small webservice wrapper in Node,  and connected that up as a webhook using the action commands, and that's working well.
I did initially have an issue with that because I wasn't returning anything from the webservice. I wonder if that could be an issue with the batch file? Does the script running *require* an echoed output to be returned to it?

**Comment by sweetpants** [comment]
Try: (watch the 3 ///)

OnAction: script:///Domoticz\scripts\TuyaTerraceLeftOn.bat
OffAction: script:///Domoticz\scripts\TuyaTerraceLeftOff.bat

**Comment by NichUK** [comment]
@sweetpants So that was interesting... Now, neither script leave errors in the log, but only the Off script actually works. 
The on script appears to work, but nothing happens (although I then ran the script at command prompt, and it worked perfectly, leaving it in the on state so I could test) the off script, which actually does run successfully.

So I think there is actually an issue with executing the on script, and also, the screen needs to be updated as it currently says:

```
On Action:  (Should start with http:// or script://)
Off Action:  (Should start with http:// or script://)
```

Thanks for the suggestion. I'm also surprised that there isn't an additional script field for a _status_ call, for feedback into the dummy device, but that's a feature discussion. :)

**Comment by gizmocuz** [comment]
it also should say this. The idea is that you put your scripts in the scripts folder, and do not store them elsewhere, so you do not need the hardcoded location like /domoticz.scripts/...
At least... that is the idea... and working under linux, but it might be it is not correctly working like this under windows.
Could you have a look at CSQLHelper::HandleOnOffAction and try to debug this ?

**Comment by Alitoy** [comment]
Try: 
OnAction: script:///TuyaTerraceLeftOn.bat
OffAction: script:///TuyaTerraceLeftOff.bat

**Comment by virusczz** [comment]
@NichUK Hi this is exactly what i am searching for :). Please help also :)
What is in side of the bat file ?

Thank you
