### ISSUE TITLE
RGB JSON support

### ISSUE THREAD

**Issue by empierre** [domoticz/domoticz#222]
Hello,

  Sorry for the confusion, but I am still searching for the RGB info:
- a dummy rgb lamp opens up the popupo but does not send the rgb value back. Also there is nothing on the actual RGB value in the light JSON output.
- how can I create a "real" limitless one so I can try to reverse engineer the JSON commands ? or maybe you can point me where I can find this ? 

Thanks,

**Comment by gizmocuz** [comment]
the dummy hardware is a good start
if you open the gui with 'chrome', and open the debug console, and switch to the network tab
you should see the commands being send

**Comment by empierre** [comment]
Hello,

 there is still only hue & brightness, do you plan to add the RGB color value or the third parameter of HSB ?

type=command&param=setcolbrightnessvalue&idx=395&hue=128&brightness=42&iswhite=false
