### ISSUE TITLE
New Notifications

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#2220]
Updated to 3.9045 and started getting new annoying notifications in the log.  I see that there was an [update regarding them](https://github.com/domoticz/domoticz/commit/6f1c187201deab1f0a5eeffb0fcf98084090c040).  Now every time my server updates a dummy switch via LUA, this is what I get:

> 2018-03-13 13:38:51.049 CLuaHandler (updateDevice from LUA) : idx=22 nvalue=0 svalue=0 invalue=0 signallevel=12 batterylevel=255
> 2018-03-13 13:38:51.050 Warning: Notification NOT handled (type: F4 - Light/Switch, subtype: 73 - Switch), please report on GitHub!

Any clue about this?  It says to report it on GitHub. Thanks

**Comment by guillaumezin** [comment]
My fault, I'm pushing a PR #2221

**Comment by Siewert308SW** [comment]
Whats going on?
Updated to 3.9047.
Domoticz log is floodding with with following messages:
Warning: Notification NOT handled (type: F3 - General, subtype: 29 - kWh), please report on GitHub!

**Comment by Ittiz** [comment]
got this for 3.9047 as well:

> 2018-03-14 09:42:50.492 Warning: Notification NOT handled (type: F3 - General, subtype: 21 - Thermostat Fan Mode), please report on GitHub!
> 2018-03-14 09:42:50.535 (Z-Stick Gen5) General/Thermostat Fan Mode (Thermostat Fan Mode)
> 2018-03-14 09:42:50.575 Warning: Notification NOT handled (type: F3 - General, subtype: 21 - Thermostat Fan Mode), please report on GitHub!
> 2018-03-14 09:42:50.611 (Z-Stick Gen5) General/Thermostat Fan Mode (Thermostat Fan Mode 2)
> 2018-03-14 09:42:50.650 Warning: Notification NOT handled (type: F3 - General, subtype: 18 - Thermostat Clock), please report on GitHub!
> 2018-03-14 09:42:50.686 (Z-Stick Gen5) General/Thermostat Clock (Thermostat Clock)
> 2018-03-14 09:42:50.725 Warning: Notification NOT handled (type: F3 - General, subtype: 18 - Thermostat Clock), please report on GitHub!
> 2018-03-14 09:42:50.802 (Z-Stick Gen5) General/Thermostat Clock (Thermostat Clock 2)

It seems the Dummy switch LUA updater no longer spams my log in the 3.9047 update, so that's fixed.

**Comment by guillaumezin** [comment]
The error on switch should have gone in 3.9047, need to dig a bit for the kHw trouble

**Comment by Siewert308SW** [comment]
@guillaumezin 
But the questions is what are these messages?

edit:
Just enabled the except all hardware option.
Seems those messages are gone after Domoticz discovered unused devices.
So meaning i have to include all unused devices, which to me seems pointless as thre are 128 unused z-wave devices which i don't use and always get rid of.

**Comment by guillaumezin** [comment]
We reworked the notifications to handle all notifications (except switches) in one place, this way, this is the same code path for command, json update, and update from python plugin. The message tells that the function handling all the notifications (CheckAndHandleNotification) was asked to handle a notification for a device not yet or incorrectly supported. It could be harmless. It let us 2 choices : silently ignore the device notification (there are cases where we don't want to push notifications), or push the notification as requested

**Comment by Siewert308SW** [comment]
Thx for the clarification.
Still don't understand, i better don't ask anymore. ;-)
Sorry i can't debug this one, meanwile back to 3.9034 as i'm getting nuts of all those messages... ;-)

**Comment by guillaumezin** [comment]
@Siewert308SW Do you know what hardware is managing your kWh device? Dummy, ZWave, ... ? Do you have any script that updates the device through JSON?

**Comment by Siewert308SW** [comment]
Kwh devices is just a plain z-wave Fibaro and CoolCam plug.
No dummy and no script that updates the device through JSON.

**Comment by guillaumezin** [comment]
@gizmocuz @dnpwwo I'm unable to reproduce the kWh problem, for me notifications works, with Dummy and Zwave kWh. I'm able to trigger an error message with a malformed json update only, for instance `http://localhost:8080/json.htm?type=command&param=udevice&idx=7&nvalue=0&svalue=4` instead of `http://localhost:8080/json.htm?type=command&param=udevice&idx=7&nvalue=0&svalue=4;4` because kWh expect svalue with 2 float numbers separated by ;

May Zwave send a malformed svalue?

Should we silently ignore strarray when the size is not the expected one in CheckAndHandleNotification()?

**Comment by rjblake** [comment]
Getting a lot of these too:

2018-03-15 15:00:52.108 Warning: Notification NOT handled (type: F3 - General, subtype: 18 - Thermostat Clock), please report on GitHub!
2018-03-15 15:01:05.301 Warning: Notification NOT handled (type: F3 - General, subtype: 18 - Thermostat Clock), please report on GitHub!
2018-03-15 15:01:06.836 Warning: Notification NOT handled (type: F3 - General, subtype: 18 - Thermostat Clock), please report on GitHub!
2018-03-15 15:01:06.881 Warning: Notification NOT handled (type: F3 - General, subtype: 18 - Thermostat Clock), please report on GitHub!
2018-03-15 15:01:06.943 Warning: Notification NOT handled (type: F3 - General, subtype: 18 - Thermostat Clock), please report on GitHub!
2018-03-15 15:01:06.973 Warning: Notification NOT handled (type: F3 - General, subtype: 18 - Thermostat Clock), please report on GitHub!
2018-03-15 15:01:07.041 Warning: Notification NOT handled (type: F3 - General, subtype: 18 - Thermostat Clock), please report on GitHub!

**Comment by guillaumezin** [comment]
Most of theses message should disappear on last beta, would you try?

I have just a double with kHw and Temp + humidity devices

**Comment by rjblake** [comment]
Updated to latest Beta (3.9117) and the warnings have all disappeared now

**Comment by Siewert308SW** [comment]
Still have those messages while i'm on 3.9168
Those message only appear for my z-wave nodes for which i removed unused devices.
Those messages are for devices i don't use and there for removed from the device unused list.

**Comment by guillaumezin** [comment]
> Still have those messages while i'm on 3.9168

The messages should be more precise on last betas, could you post them?

**Comment by Siewert308SW** [comment]
@guillaumezin 

All devices mentioned below are powerplugs.
Fibaro and coolcam and all devices mentioned below aren't available as i don't use this particular piece of device and there for removed from the unused device list to prevent a couple of hundred unused devices flooding the database.

Warning: Notification NOT handled (Hardware: 29 - Aeotec Gen5, ID: 00001401, Unit: 1, Type: F3 - General, SubType: 29 - kWh), please report on GitHub!
Warning: Notification NOT handled (Hardware: 29 - Aeotec Gen5, ID: 00000201, Unit: 1, Type: F3 - General, SubType: 29 - kWh), please report on GitHub!
Warning: Notification NOT handled (Hardware: 29 - Aeotec Gen5, ID: 00000401, Unit: 1, Type: F3 - General, SubType: 29 - kWh), please report on GitHub!
Warning: Notification NOT handled (Hardware: 29 - Aeotec Gen5, ID: 00000501, Unit: 1, Type: F3 - General, SubType: 29 - kWh), please report on GitHub!
Warning: Notification NOT handled (Hardware: 29 - Aeotec Gen5, ID: 00000601, Unit: 1, Type: F3 - General, SubType: 29 - kWh), please report on GitHub!
Warning: Notification NOT handled (Hardware: 29 - Aeotec Gen5, ID: 00000701, Unit: 1, Type: F3 - General, SubType: 29 - kWh), please report on GitHub!
Warning: Notification NOT handled (Hardware: 29 - Aeotec Gen5, ID: 00001A01, Unit: 1, Type: F3 - General, SubType: 29 - kWh), please report on GitHub!
Warning: Notification NOT handled (Hardware: 29 - Aeotec Gen5, ID: 00001401, Unit: 1, Type: F3 - General, SubType: 29 - kWh), please report on GitHub!
Warning: Notification NOT handled (Hardware: 29 - Aeotec Gen5, ID: 00001701, Unit: 1, Type: F3 - General, SubType: 29 - kWh), please report on GitHub!
Warning: Notification NOT handled (Hardware: 29 - Aeotec Gen5, ID: 00001801, Unit: 1, Type: F3 - General, SubType: 29 - kWh), please report on GitHub!

**Comment by guillaumezin** [comment]
@Siewert308SW And you don't get messages like ""Warning: Expecting svalue with at least 1 elements separated by semicolon, 0 elements received..."? That's odd...

**Comment by Siewert308SW** [comment]
@guillaumezin Nope, non or what so ever.
Message i posted earlier disappears when i enable "Accept all hardware"

**Comment by guillaumezin** [comment]
@Siewert308SW Thank you, I think I found the problem, it should be corrected in a few days

**Comment by Siewert308SW** [comment]
@guillaumezin Great news.
 thx and awaiting...
