### ISSUE TITLE
Aqara wall plug device ctrl_86plug.aq1

### ISSUE THREAD

**Issue by kovainfo** [domoticz/domoticz#2222]
Please, add support for new Aqara wall plug device: ctrl_86plug.aq1

> 2018-03-06 20:28:37.138 XiaomiGateway: unhandled model: ctrl_86plug.aq1
> 2018-03-06 20:28:37.138 {"cmd":"read_ack","model":"ctrl_86plug.aq1","sid":"158d0001f4e1e7","short_id":9022,"data":"{\"voltage\":3600,\"status\":\"on\",\"inuse\":\"1\",\"power_consumed\":\"424\",\"load_power\":\"1.96\"}"}

**Comment by kovainfo** [comment]
@corbinmunce please, add this plug! ))

**Comment by corbinmunce** [comment]
basic support should be added in #2312 

I don't have these plugs to test.

**Comment by kovainfo** [comment]
Cool!!! It's worked!!!
