### ISSUE TITLE
Double entry for ON or OFF switch either through UI or API call

### ISSUE THREAD

**Issue by rjblake** [domoticz/domoticz#2226]
Request this is re-opened as problem continues to exist where both the ON and OFF commands or selection through the UI results in command being sent twice. Details documented here:

[Previously Closed issue #2175](https://github.com/domoticz/domoticz/issues/2175)

**Comment by sweetpants** [comment]
I'm on latest Beta (V3.9048) and cannot confirm this behaviour. Only one command is send and logged at a time

**Comment by rjblake** [comment]
I've restarted everything and the issue no longer exists. However, I now have a new issue relating to the physical switches and their operation. Will open a new issue
