### ISSUE TITLE
Usb serial link data missing

### ISSUE THREAD

**Issue by jouveadrien** [domoticz/domoticz#2232]
Hi,

I'm using a serial link to communicate between Raspberry (where domoticz is installed) and an Arduino.
I have develop my own very simple communication protocol between Arduino and Raspberry over USB, I want to improve it but for the moment I'm blocked on this issue.

First of all, I have made a test with a simple python script running on Raspberry to verify if my arduino correctly send the data.
When I write a python script to read data from the serial link I already received all the data.
My python script to read serail link data:
```
import serial

class test:
    def __init__(self):
        self.ser = serial.Serial('/dev/ttyACM0', 115200)

    def read(self):
        while 1:
            line = self.ser.readline()
            print(line)
            sleep(1)
t = test()
t.read()
```
it send me back the data write over usb link from Arduino:
```
cStateMachine::stopBlind:   Cuisine: Stop the blind
cStateMachine::downBlind    Cuisine: Up the blind
cStateMachine::stopBlind:   Cuisine: Stop the blind
```

But when I use a Python script in domoticz to do the same:
```
    def onMessage(self, Connection, Data, Status, Extra):

        Domoticz.Log("Connection: " + str(Connection) + "/ Status" + str(Status))
        try:
            if (str(Data) != ""):
                #jsonData = json.loads(Data)
                #Domoticz.Log("Json received: " + json.dumps(jsonData))
                # read data in JSON
                #val = jsonData['toto']
                received = str(Data)
                received = received.replace("b\'", "")
                received = received.replace("\'", "")
                self.dataLocal = self.dataLocal + received
                Domoticz.Log("Total val: " + self.dataLocal)
                if ("#" in self.dataLocal and self.dataLocal.endswith("#\'")):
                    array = str(self.dataLocal).split("#")
                    #Domoticz.Log("data splited: " + str(array))
                    for val in array:
                        if (val.find("42") != -1):
                            self.watchdog = False
                            self.counter = 0

                if (not self.dataLocal.endswith("#\'")):
                    array = str(self.dataLocal).split("#")
                    self.dataLocal = array[-1]
                else:
                    self.dataLocal = ""
        except:
            Domoticz.Log("Fail to read JSON value")
```
Note: I'm sure I have only one plugin which is reading on USB port. Because I have implemented the onMessage def in only one script

In "Total val" I received very various data with the same frame send from Arduino:
For example I receive:
```
(Watchdog) Total val: cStateMachine::stopBlin
(Watchdog) Total val: cStateMachine
(Watchdog) Total val: cStateMachine::stopBlind:\t\tCuisine: Stop
```
Don't care about "\t\t" because it was replace by python when it print.
As you can see some data are missing.

For sure, I possibly do somethings wrong, but I try to find information on internet, on forum and on your issue data base but I find nothing.

Last information I have try on domoticz latest stable version, and the beta version 3.9052 and I already reproduce the issue.

I'm a professionnal developper so I can do code on my side if it's necessary.

cheers

**Comment by gizmocuz** [comment]
Please implement this with MySensors.org
