### ISSUE TITLE
Device timers page no more accessible when a -webroot is set at startup

### ISSUE THREAD

**Issue by paifre** [domoticz/domoticz#2233]
Hello,

**Device timers page** no more accessible when a -webroot is set at startup
Removing webroot parameter, it works fine.

Similar behavior but not same root cause I guest with "**Apply Settings**" button. 
_Storesettings.webem_ request is failing with 400 error code when a webroot is set

 Release 3.9052 on raspbian

Thx

**Comment by gordonb3** [comment]
Version 9031, my current dev version, I'm seeing the same 400 return code on storesettings.webem but the settings do apply. Had not noticed the timers yet, but webinspector shows a 400 return code here as well and the cause appears clear: it tries to load `/views/timers.html` which of course is missing the webroot part.

**Comment by paifre** [comment]
Hello,

Corrections are working fine for Timers and 'Apply Settings'. **Thanks a lot.**
But... problem moved to Switch log page :( 
With webroot declared, nothing is happening (looks like no request is sent to server)

Testing now logs on Temperature devices page, i can see **HTTP/400 error code** on device_temperature_log.html and TemperatureLog.js

It works **correctly** for Scenes, Weather and Utilities

Release 3.9138 on raspbian

Thx

**Comment by gizmocuz** [comment]
@paifre , got the same problem here ... this is fixed now and a new beta should be available shortly

**Comment by gordonb3** [comment]
I was wondering why I could not replicate that, but I hadn't installed the latest beta yet. Should we somehow make the code handle that issue? It seems to be bound to happen again some time in the future.

**Comment by paifre** [comment]
Hello,

No more problems with last fix on this issue.  

**Thanks a lot for the amazing work you're all doing.**

**Comment by gizmocuz** [comment]
@gordonb3, hmmm no better that the authors do it right... sames a couple of cpu cycles ;)
