### ISSUE TITLE
Error 'X-Content-Type: nosniff' is given since domoticz in beta mode

### ISSUE THREAD

**Issue by fennec622** [domoticz/domoticz#2234]
Hi
first thanks for your job
I use personal version of frontpage
and since i pass in domoticz beta, frontpage doesn't work

[Error] Did not load script at 'http://10.0.0.1:8080/json.htm?type=devices&plan=1&jsoncallback=jQuery31108805318969018416_1521367357609&_=1521367358460' because non script MIME types are not allowed when 'X-Content-Type: nosniff' is given.

When i write

http://10.0.0.1:8080/json.htm?type=devices&plan=1&jsoncallback=jQuery31108805318969018416_1521367357609&_=1521367358460

directly in browser all is ok

I use frontpage with apache2

I load script like that

<script src="js/frontpage2.js"></script>

and in frontpage2.js

$.ajaxSetup({
                        dataType: "json",
                        contentType: "application/json",
            async: true,
                        global: false,
                        timeout: connectTimeout,
                        cache: false 
});

$.ajax({
            url: [$.domoticzurl,'/json.htm?type=graph&sensor=',vtype,'&idx=',xIDX,'&range=',vrange,'&jsoncallback=?'].join('')
        })

Since 5 days github of domoticz change

request_handler.cpp add
//browser support to prevent XSS
reply::add_header(&rep, "X-Content-Type-Options", "nosniff");
reply::add_header(&rep, "X-XSS-Protection", "1; mode=block");

Can you help me

Thanks

**Comment by gizmocuz** [comment]
This is done for XSS protection.
Your script, is this not inside the domoticz/www/js folder ? If not, could you try adding this there?

**Comment by fennec622** [comment]
Thanks for your help

I use apache2 on ubuntu server

and frontpage source is 

https://github.com/vil1driver/monitor

all files is in /var/www

before no XSS protection active all is ok

thanks

**Comment by gizmocuz** [comment]
could you also host the files in domoticz/www ?

**Comment by fennec622** [comment]
Yes if i move in domoticz/www all is ok

Is it possible to use from apache2 ?

thanks a lot

**Comment by gizmocuz** [comment]
i quess if you host it on the same machine... do you need to host it on apache2 if you can host in in domoticz ?

**Comment by fennec622** [comment]
Yes same machine, apache2 and domoticz

I don't try localhost in adress, i use 10.0.0.1

**Comment by MAkerboom** [comment]
I use nginx on port 80/443 for this purpose:

if the root of my domain/ip (https://domain/) is requested it is passed to domoticz
nginx config: `location / { proxy_pass http://10.0.0.1:8080 }`
if my custom frontpage (https://domain/frontpage) is requested pass it to apache2:
nginx config: `location /frontpage { proxy_pass http://10.0.0.1:8081 }`

In the frontpage script you use http://10.0.0.1/json.htm instead of http://10.0.0.1:8080/json.htm. Because both are running (virtually) on port 80 no XSS issue's

**Comment by gizmocuz** [comment]
But if it is to complex for others, feel free to make a PR that removes the nosniff, but it might be wise to keep it

**Comment by gizmocuz** [comment]
(or even better, create an XSS option that you can disable)
