### ISSUE TITLE
Feature suggestion: Improve scene/group activation

### ISSUE THREAD

**Issue by emontnemery** [domoticz/domoticz#2244]
Would it make sense to make the following changes to scene/group activation:
- Add option/dropdown component to WebUI to manually choose activation device
- Make it possible to make an activating device toggle a group

**Comment by gizmocuz** [comment]
1. Yes it does, a dropdown that also highlights the current activation device
2. not sure i understand, this is already possible i thought

**Comment by bizziebis** [comment]
1. Are you sure this is already implemented? As far as I can see you can only add an activation device by 'learn' command. So you can only add a device which actually sends a RF signal like a switch or motion sensor.

Would be great to add other devices to trigger a scene/group.

**Comment by gizmocuz** [comment]
@bizziebis , i was talking about the two points the opp is mentioning, so '1' is not yet implemented, and '2' is i think

**Comment by emontnemery** [comment]
@gizmocuz I can't find a way to _toggle_ a group with an activation device, just to switch it on or off, maybe I missed something?

**Comment by gizmocuz** [comment]
No you do not miss anything, you can learn a code to a scene and also to a group.
A scene is like a 'push' button, it fires the commands... in the same order
When you learn a remote for instance to a group, then when you press 'ON' it will turn on all devices in the group, when you press OFF, it will turn off all devices in the group.
This is already working, so only the option to manually specify an activation device would be great

**Comment by romainrossi** [comment]
@gizmocuz : Point 2 is not working if the remote has only 1 button (the ON button) : it only switches ON the group. Maybe an option to select the action could be useful.
This could also give the possibility to trigger different scene/group with the ON and OFF button of a remote.

**Comment by gizmocuz** [comment]
@romainrossi , this is a very old thread.
Firstly, a Scene can only be activated and not turned On/Off, and I think you should be able to learn different buttons to scenes
It is intended (for Kaku remotes) that when btn 2 ON is received that ON is triggered, and btn 2 OFF is received to trigger a OFF to a group

**Comment by romainrossi** [comment]
@gizmocuz : sorry to resuscitate this old thread... Let me detail my previous message.

My current problem :
I have Enocean remotes (Nodon soft button : https://nodon.fr/en/nodon/the-soft-button-enocean/) with only 1 button. It can only send the "On" command (or the command is interpreted as such by Domoticz).

When I make an association with a Domoticz Group (not a Scene); this remote can only switch ON the Group. It can not switch OFF.

The current (only?) solution is to use a script to perform this **Toggle** action, depending on the current state of the group.
Or to create 2 Scenes ans use two remotes.

So the feature request suggested in this issue (the second point) "Make it possible to make an activating device **toggle** a group" would be of interest to me. I would even suggest to add a drop-down list to select the action for each activating device (Switch ON, Switch OFF, Toggle, Use command provided by the activating device).

I tested also with an Enocean remote with 4 buttons (https://nodon.fr/en/nodon/enocean-wall-switch/); but each of the buttons send the ON command on 4 different devices. On this one, I used 2 Scenes associated with two buttons to switch ON and OFF a light.

For Scenes, these remotes works great however, as a scene can only be activated as you say.

**Comment by martinprins** [comment]
I have another reason for such a function. I want to use an old KAKU remote to switch a few groups on or off. The remote uses the old ARC protocoll. For a unclear reason i can define the switch only manually by using the house and unit code - learn does not work. 
For this I defined a dummy switch that works. However i cannot couple this to a group.

**Comment by rwaaren** [comment]
@martinprins Please check [this post](https://github.com/domoticz/domoticz/issues/4584#issuecomment-764802951) to see how to couple a dummy switch as activation device with a simple API call

**Comment by almostlunatic** [comment]
I have several Sonoff PIR sensors. I can add them as activating devices when removed from under a cover to simulate a "Press  button on Remote", so it appears as an activating device with Code "On". It's not possible to add this device (or maybe any) with code "off". So, a bulb added on Devices turns on and stays on forever. I can add Off delay for th bulb, say 60 sec, but then again the bulb turns off after set time and I rest into the darkness, as the sensor has the blind time of 60 seconds when the movements need to be off, and then it resends the on-action. I don't mention than in the night time I would like to have a different action (brightness) of this bublb than within the daylight. So, some simple additions would avoid people to start scripting with every scene occasion.

**Comment by waltervl** [comment]
Closing this old issue. For further discussion about usage of group/scene use the forum.
