### ISSUE TITLE
Domoticz does not compile on cygwin

### ISSUE THREAD

**Issue by ultrasuperpingu** [domoticz/domoticz#2247]
The file main/Camera.cpp fail to compile with errors:
#error You must add -D__USE_W32_SOCKETS to your compiler options.

**Comment by gizmocuz** [comment]
and when you do this ?

**Comment by ultrasuperpingu** [comment]
If I add the definition, I get errors earlier during the build. I'll try to investigate this evening.

**Comment by gizmocuz** [comment]
Is it working now ? (bdw why don't you compile with VStudio ?)

**Comment by ultrasuperpingu** [comment]
No, it's not. There is a problem with boost asio and mosquitto and I was too lazy to try to fix it so I compiled on my roommate linux install :( But you're right, I should have use VS but I usually try to avoid it because it's almost always a pain to get all dependencies setted up correctly :)

**Comment by ultrasuperpingu** [comment]
Hi, I finally manage to compile on VS since my roommate's computer is not always available and I have some little changes to do on domoticz and I saw that you provide up to date precompiled dependencies ;) So, I definitly should have use VS on the first place because it was REALLY easy :) So I guess for most people, it's not a big deal to not have the project compiling on cygwin and I pretty sure I would not take time to see what's the problem. So I'm going to close the issue if you're ok with it...
