### ISSUE TITLE
Windows Libraries issues with cmake and runtime

### ISSUE THREAD

**Issue by correa** [domoticz/domoticz#225]
Windows Libraries zip is a handy download to get windows developers going, but it differs quite from how the original libraries are packed, and thus if we try to get cmake working on windows we run into these:

Precompiled headers:
- The generator in CMakeLists.txt for MSVC simply doesn't work at all. We can fix this by using Cotire [1] or CMakePCHCompiler[2]. I tried the later and it works, but Cotire should be a better choice.

FindPackage(Boost):
- Expects the libraries to be in stage/lib or lib and not separated by release and debug folders, as the library names won't clash.
- It's built with static runtime, which isn't standard and won't offer us much advantages. It would be easy to include the runtime into the installer for final users.

FindPackage(OpenSSL)
- We can't use the standard FindOpenSSL.cmake because it's built with static runtime, which it doesn't support. 

I was able to work out Precompiled header issues, and boost issues, but the OpenSSL issue made me consider that I was getting into too much effort to keep current Windows Libraries layout then I should.

Proposal: Recreate Windows Libraries to use dynamic runtime, and standard layouts so FindPackage can find those with less work-around.

[1] https://github.com/sakra/cotire
[2] https://github.com/mitchellwong/CMakePCHCompiler

**Comment by gizmocuz** [comment]
thats true, but why don't you use visual studio 2015 ?

**Comment by correa** [comment]
I got into all of that trouble trying to get the internal zlib copy usable on Windows. I did for Linux and perhaps mac, didn't try on the MacBook.

I've changed the zlib block to this:

```
    if(USE_BUILTIN_ZLIB)
        add_subdirectory (zlib)
        include_directories(${ZLIB_INCLUDE_DIRS} ${CMAKE_BINARY_DIR}/zlib)
    else(USE_BUILTIN_ZLIB)
        find_package(ZLIB REQUIRED)
        if(ZLIB_FOUND)
            MESSAGE(STATUS "ZLIB libraries found at: ${ZLIB_LIBRARIES}")
            MESSAGE(STATUS "ZLIB includes found at: ${ZLIB_INCLUDE_DIRS}")
        else()
            MESSAGE(FATAL_ERROR "ZLIB not found on your system, see install.txt how to get them installed. (for example 'sudo apt-get install zlib1g-dev')")
        endif(ZLIB_FOUND)
    endif(USE_BUILTIN_ZLIB)
```

**Comment by gizmocuz** [comment]
maybe add

option(USE_BUILTIN_ZLIB "Use builtin zlib library" NO)

above this

**Comment by gizmocuz** [comment]
Is all working correct now ?
