### ISSUE TITLE
milight cannot be added to dashboard

### ISSUE THREAD

**Issue by Tontze** [domoticz/domoticz#2257]
After latest beta update, milight switches disappeared from dashboard, and cannot be added back ? 

Also, it is impossible to get milight bulps to white color, no white button anymore ..

**Comment by jeffreyveldt** [comment]
Same with the Hue lights

**Comment by gizmocuz** [comment]
Same with ZWave RGB

**Comment by salopette** [comment]
Same with Yeelight

**Comment by gizmocuz** [comment]
You can 'now' update to a new beta version... should be fixed

**Comment by gizmocuz** [comment]
Clear the appcache + browser cache

**Comment by salopette** [comment]
V3.9165
Build Hash: cb223c8b
Build Date: 2018-04-02 08:17:23


Fine! Everything is back! Milight, Yeelight

**Comment by gizmocuz** [comment]
Thanks for the feedback!

**Comment by Tontze** [comment]
Unfortunately, my milights are not back. I did ./updatebetarelease, and did remove appcache, and refreshed.

Log: Domoticz V3.9165 (c)2012-2018 GizMoCuz

**Comment by gizmocuz** [comment]
@Tontze , also remove the browser cache (two different things), or try a private browser, or another browser.

**Comment by dannybloe** [comment]
If you use Chrome and you go to the dev panel > Application > Clear storage and click the `Clear site data` button it also clears the application cache (you can verify that by going to chrome://appcache-internals. Pressing the `Clear site data` button also removes the entry in the appcache-internals page.
