### ISSUE TITLE
Wrong Z-wave node id shown

### ISSUE THREAD

**Issue by Olifant1990** [domoticz/domoticz#2266]
Some devices get a wrong Z-wave node id.
See attachment.
All shown devices are from 1 Z-wave device and are all node 0x08.
Only the Gas meter gets a different type ID, and so the USB 032 (0x20) is wrong.

![devices](https://user-images.githubusercontent.com/25199588/38205019-5580e4f2-36a5-11e8-9984-211cefd407fe.PNG)

**Comment by jvanderzande** [comment]
What is shown in the Hardware Tab for this device?

**Comment by Olifant1990** [comment]
I have attached the hardware view and the Z-Wave nodes.
The showed devices in my first post belong to hardware Idx 2 (OpenZwave USB) and Z-Wave node id 008 (0x08)

![hardware](https://user-images.githubusercontent.com/25199588/38212794-56d326e8-36bf-11e8-9d38-e4d56ad01b01.PNG)
![z-wave nodes](https://user-images.githubusercontent.com/25199588/38212795-5706325e-36bf-11e8-9986-0707b001f3ac.PNG)

**Comment by jvanderzande** [comment]
Then there isn't much I can change to the rather basic logic used in the patch I made: https://github.com/domoticz/domoticz/pull/2033/files
It uses the ID, which in this case is 2052, to retrieve the ZWAVE ID,  but I have no idea how that can be translated back in this case to the appropriated ZWAVE device 8. 
Thoughts?

**Comment by Olifant1990** [comment]
I know you made this patch. Recently I copied your work to the log page, see https://github.com/domoticz/domoticz/pull/2157. This wasn't accepted by @gizmocuz as not needed. You see here that this code is maybe not the correct way to find the belonging node-id (as it is almost the same way of implementation as I did).
I have no clue yet for my gas device. Maybe @gizmocuz can help a little?

**Comment by jvanderzande** [comment]
I guess the issue is the ID assigned by the ZWAVE part, which in this case seems to lack the Zwave DeviceId. I have a lot of ZWAVE devices of several different brands and they all are identified perfectly with this little bit of code. 
Does the patch you made identify it properly? I looks to me as the same logic I added to the Browser clientside script or am I mistaken?

**Comment by Olifant1990** [comment]
I will have a look in the database soon, let's see if I can find something missing.

Also I can't say if my script would have identified it correctly, because I do'nt have a P1 meter on my test system. But I don't think so, as it is the same logic as yours indeed.

**Comment by Olifant1990** [comment]
I cannot find anything wrong in the database.
It must be the part when adding this device and the code somewhere asigns a device ID indeed.

**Comment by jvanderzande** [comment]
I guess I understand what the issue is here but not sure how to solve that as it goes against the current logic for all other devices. 2052 is a Decimal value and when converted to HEX it's value is:  804 meaning Zwave device 8 sub device 04 which sounds about right. All 4 digit DeviceId's I have in the table are Hex notations which need to be converted to Decimal. This seems to be the other way around.

**Comment by jvanderzande** [comment]
Could you check what the DeviceID, Type and SubType values are the DeviceStatus table is in domoticz.db?  The examples i have contain the decemial value in this field, so must be converted in the domoticz program's webserver to hex and returned as such in the JSON result for: 
http://ip/json.htm?type=devices&displayhidden=1&displaydisabled=1&filter=all&used=
So maybe the conversion for this devicetype isn't done. What is the Type for this device?

**Comment by Olifant1990** [comment]
Sure: 

DeviceID: 2052
Type: 251
SubType: 2

**Comment by jvanderzande** [comment]
I think the issue is that Domoticz is not converting the DeviceID from the decimal value in the Table to the HEX notation in the JSON result for this particular Type/SubType., where all other ZWAVE deviceID's are.
 I am not sure how that's determined so maybe @gizmocuz can comment?

**Comment by Olifant1990** [comment]
@gizmocuz Any thoughts?

**Comment by gizmocuz** [comment]
There is a 99% relation ship between the zwave node_id and the actual device that is being created.
Some devices are displayed in decimal, while others have a hex ID
When adding a new node it is advised to directly name your sensors to avoid confusion

**Comment by jvanderzande** [comment]
I honestly think that Domoticz isn't converting the decimal DeviceID from the Table to hex for this type, unlike the other zwave devices!  This is the only logical explanation for me :)

**Comment by gizmocuz** [comment]
Well that should be quite easy to verify:

ZWaveBase, if (pDevice->devType == ZDTYPE_SENSOR_GAS)
Here the gas sensor is send

Then in the database the ID should be seen, and in the webserver class the id is being generated to be shown on the devices tab

**Comment by gizmocuz** [comment]
2052 is 0804 in hex

**Comment by gizmocuz** [comment]
Webserver/cpp, line 8858, here the ID is transfered to HEX, but only for the types below
Maybe here we should add the P1 smart meter for electra and gas and then it's in hex

**Comment by gizmocuz** [comment]
Changes, will be solved in the upcoming beta release
https://github.com/domoticz/domoticz/commit/0aa5912078cc700f37b2b117a5c68d1211ec867a

**Comment by jvanderzande** [comment]
I had seen that hex conversion part, so hence my comments, but couldn't figure out how it determined the devices it does it for.  Knew it would be a piece of cake for you 😄 ..  thanks

**Comment by gizmocuz** [comment]
Yes sorry! I also did not read this entire thread... but there are more types that display in decimal.
A user should name it's devices after adding a new node to the system, regardless of what new ID is assigned to a device. It could have been an incremental counter for instance (as id)
