### ISSUE TITLE
still, milight cannot be added to desktop

### ISSUE THREAD

**Issue by Tontze** [domoticz/domoticz#2267]
For some this was fixed, but for some reason, mine is not working.

Did update now via web notification, removed appcache (chrome://appcache-internals/#), and did ctrl+f5

Tried changing theme too, no luck. Restarted whole system and removed power from rpi, no luck.

Ver 3.9168 now. I have few milight added via milight gateway, and few via rflink. None of these are shown on desktop..

**Comment by Tontze** [comment]
Seems to work in microsoft edge, but not in chrome ?

**Comment by Tontze** [comment]
chrome console : 
`jquery-3.3.1.min.js:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

**Comment by emontnemery** [comment]
@Tontze The warning is not the cause if your problem... What type of milight (V4/V5/V6)?

**Comment by Tontze** [comment]
The one with the light Inside. But have also milight through rflink, they dont use controller at all. All milights still missing.

**Comment by emontnemery** [comment]
Please go to hardware page, click on "Set Mode" on one of the rows for the Milight that you can't add.
Now, what does it say for:
- Bridge type
- Type

![image](https://user-images.githubusercontent.com/14281572/38213848-10db7d1c-36c3-11e8-9d9a-2a6932a37126.png)

**Comment by Tontze** [comment]
It says v6, rgbww

**Comment by emontnemery** [comment]
I can't reproduce your problem, can you check that:
- You see the problem also in browser's Incognito mode / In private mode
- The devices show up on the LightSwitches page and are marked as favorites
- You have the corrections from cb223c8b31d662ecf96eaa4731f6b6649140f6a6
  - Line 212 of www/app/DashboardController.js should say `(item.Type.indexOf('Color Switch') == 0) ||`
  - Line 1919 of www/app/DashboardController.js should say `(item.Type.indexOf('Color Switch') == 0) ||`

**Comment by Tontze** [comment]
incognito mode seems to work.
Devices are under switches tab, and are favorited.

line 212 is ok, but 1919 says : 

`   if (jj == 0) {
`

**Comment by emontnemery** [comment]
Sorry, typo, should have been line 1909.

If it works in incognito mode, it's due to browser cache issue..
Please change `# ref` version number in www/html5.appcache and ctrl+reload twice.
Best to change to a smaller number so cache refresh triggers next time you update Domoticz.

**Comment by Tontze** [comment]
I incremented #ref by 1,  few times F5, few times ctrl+r, and few times ctrl+f5. Did also remove appcache again. 

No help, still missing :/

**Comment by emontnemery** [comment]
Can you verify www/app/DashboardController.js seen by chrome is the right one:
- ctrl + shift + i to open developer mode
- choose "Sources" tab
- Navigate to app/DashboardController.js and verify lines 212 and 1909

**Comment by Tontze** [comment]
Line 212:	(item.Type.indexOf('RFY') == 0) ||
Line 1909: (item.Type.indexOf('ASA') == 0) ||

**Comment by emontnemery** [comment]
OK, so Chrome is using wrong/old file for some reason..
Try to right click on app/DashboardController.js and choose "Open in new tab" and check that it's opening from the right address.
Compare with what address Edge is fetching from (copy location in the popup) and contents:
![image](https://user-images.githubusercontent.com/14281572/38218608-a4e38bda-36d2-11e8-9cfa-a1e03ffd97f5.png)

**Comment by Tontze** [comment]
In both address is same, and correct. In edge, lines 212, 1909 are as they are supposed to be.

in chrome console : 

`[Deprecation] Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS.`

And im using http only. What does that mean that appcache is deprecated on insecure origins ?

**Comment by gizmocuz** [comment]
that has always been the cache

Chrome: to clear the browser cache, open the developer console, select the network tab, refresh the page
right click on an item in the network tab, select 'clear cache'
Next clear the appcache, navigate to 
chrome://appcache-internals/

clear the cache

**Comment by Tontze** [comment]
Thanks gizmoguz, clearing browser cache did it !

**Comment by emontnemery** [comment]
So this can be closed?

**Comment by gizmocuz** [comment]
Yep ;)
