### ISSUE TITLE
scenes timers empty

### ISSUE THREAD

**Issue by gordonb3** [domoticz/domoticz#2268]
version 3.9154

no problem with switches timers

**Comment by gordonb3** [comment]
Seems related to [this topic post](https://www.domoticz.com/forum/viewtopic.php?f=6&t=22911)

>  2018-04-02 20:55:47.828 Error: SQL Query("SELECT ID, Active, [Date], Time, Type, Cmd, Level, Color, Days, UseRandomness, MDay, Month, Occurence FROM SceneTimers WHERE (SceneRowID==1) AND (TimerPlan==0) ORDER BY ID") : no such column: Color

**Comment by emontnemery** [comment]
Oops, I will push a fix for that..

**Comment by emontnemery** [comment]
@gordonb3 Please test the patch in #2270

**Comment by gordonb3** [comment]
Seems to do the trick
