### ISSUE TITLE
P1 Smart Meter Annual Reports are broken

### ISSUE THREAD

**Issue by MAkerboom** [domoticz/domoticz#2269]
Device type: P1 Smart Meter
Error: Go to device -> Log -> Report: No data is shown, error in browser console

The `ShowP1YearReport()` function gives a javascript error in the Chrome browser:
```
Uncaught TypeError: Cannot read property 'match' of undefined
    at u (jquery.dataTables.min.js:63)
    at Ha (jquery.dataTables.min.js:59)
    at Y (jquery.dataTables.min.js:12)
    at t.<anonymous> (jquery.dataTables.min.js:123)
    at t.iterator (jquery.dataTables.min.js:98)
    at t.<anonymous> (jquery.dataTables.min.js:122)
    at t.<anonymous> (jquery.dataTables.min.js:102)
    at t.visible (jquery.dataTables.min.js:100)
    at w.fn.init.fnSetColumnVis (jquery.dataTables.min.js:83)
    at Object.success (domoticz.js:9323)
``` 

Did a bit of debugging:
Hiding the unused table columns when not delivering energy results in the error above:
```
			oTable.fnSetColumnVis(5, bHaveDelivered);
			oTable.fnSetColumnVis(6, bHaveDelivered);
			oTable.fnSetColumnVis(7, bHaveDelivered);
			oTable.fnSetColumnVis(8, bHaveDelivered);
```

Don't know the proper fix, so can't make a pull-request.

Domoticz version info: 
```
Version: 3.9168
Build Hash: 5f4b6858
Compile Date: 2018-04-02 15:54:41
dzVents Version: 2.4.2
Python Version: 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170124]
```

**Comment by gizmocuz** [comment]
I have no issues with the electic meter.
Does it work from the Utility page ?
Could you clear the browser cache AND appcache (two different things)

**Comment by MAkerboom** [comment]
@gizmocuz 
Today I read your message at work and was surprised it worked on Windows 10: Chrome Stable and IE10.
So back home on my Chromebook running 'Version 65.0.3325.184 (Official build) (64-bits)' it's still broken, and can't fix it.

Steps I took to clear browser and app cache:
1. open dev-tool (`control-shift-i`)
2. application tab
3. clear storage menu item
4. all checkboxes selected and 'Clear site data'
I even bumped my `domoticz/www/html5.appcache` to be sure. Also tried 'Incognito mode'.

No go... (same on my Android phone running Chrome, but less sure I refreshed all caches)

[edit]
b.t.w. the graphs day/week/month/year do work. Also commenting out all the `oTable.fnSetColumnVis()` lines brings back the data, but doesn't hide the empty columns of course.

**Comment by gizmocuz** [comment]
This proves it is a cache issue

Open the chrome developer console goto network refresh the page 
Right mouse in the network console on a item,McLean browser cache
Google the chrome url to delete the appcache
Now it should work
Also try Domoticz in private mode, should also work

**Comment by MAkerboom** [comment]
I did all that, still no go:

The app cache is reloading:
```...
Application Cache Progress event (614 of 614) 
VM501 Utility:1 Application Cache Cached event
```
Also the in private (incognito) mode doesn't work and gives the same javascript error

[edit]
I even tried a guest session on my chromebook, no caches could survive that... also broken. I really can't explain it other than an issue on chromebook

**Comment by MAkerboom** [comment]
@gizmocuz 

I updated jquery.dataTables from 1.10.8 to 1.10.16 and now all is working again.

[edit]
This also fixed it on Android chrome for me

[edt2]
Needs some GUI fixes. Tables aren't shown in the right layout and buttons for first/last next/prev aren't themed.

**Comment by gizmocuz** [comment]
Thanks, would be great if you get the theming working and can make a pull request ;)

**Comment by MAkerboom** [comment]
Hmmm 1.10.8: 
> This software was originally released on 12th August, 2015.

guess a lot has changed and a lot of work to use the latest version?

[edit]
On the previous version `1.10.15` the theming is intact and no javascript error.
Can you bump to that version using:
https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js
https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css

No need for a pull request for that right?

[edit2]
Made my first pull request :)
