### ISSUE TITLE
Hue devices controlled locally don't sent MQTT notification

### ISSUE THREAD

**Issue by jonferreira** [domoticz/domoticz#2273]
following #2229 

If I turn On / Off / Change Colour via Domo it all works perfectly fine.
If I do it via Hue App / Hue Remote, Domo UI does update but doesn't seem to notify MQTT

**Comment by jonferreira** [comment]
@gizmocuz @emontnemery  Domoticz UI doesn't auto-update either - you need to refresh the page.

How to replicate:

Open Domoticz UI - Switches tab
Have Hue Bulb A Off
Turn On Hue Bulb A via Hue App / Hue Switch
Status won't refresh
F5
Hue Bulb A now shows as On

Underneath Domo does a "poll" every couple of seconds to /json.htm?type=devices&filter=light&used=true&order=[Order]&lastupdate=1522754255&plan=0

This doesn't seem to include the new "Colour Switch" type of devices

**Comment by emontnemery** [comment]
So, it's two issues?
- MQTT update does not work
- Web UI does not auto refresh

Both MQTT update and web UI auto refresh is working fine for me, so not straight forward to fix..

**Regarding MQTT:**
The Domoticz Hue integration should poll the Hue bridge for status and notify Domoticz on changes.
Can you confirm using MQTT client there is a domoticz/out message when you switch the light from WebUI but there is no domoticz/out message when you use your external app?

**Regarding UI auto refresh:**
Please try in incognito mode / in private tab to make sure it's not another cache issue.
The filtering should be OK, filtering for "light" includes pTypeColorSwitch (around line 8638 in WebServer.cpp).

**Comment by jonferreira** [comment]
Yes, it does appear to be two different problems (maybe related?) all started yesterday when I updated domo to latest beta.

**MQTT**:

Yes, that's correct. I get the expected MQTT message when I switch them on / off using Domo but nothing when using Hue App or Hue Switches

```
{
   "Battery" : 255,
   "Color" : "{\"b\":59,\"cw\":0,\"g\":255,\"m\":3,\"r\":52,\"t\":0,\"ww\":0}",
   "Level" : 99,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Color Switch",
   "id" : "00000002",
   "idx" : 57,
   "name" : "Hue color spot 1",
   "nvalue" : 1,
   "stype" : "RGBW",
   "svalue1" : "99",
   "switchType" : "Dimmer",
   "unit" : 1
}
```

**UI Auto Refresh**

Not sure what to say, I did tried on a different browser (that never opened domo before) and incognito window but it just doens't work unless if I manually refresh the page or "change tabs", i.e. Switches - Scenes - Switches
Again this was working fine 2 days ago.

Strange that you can't reproduce though

**Comment by emontnemery** [comment]
One thing which might be worth checking:
The Domoticz Hue integration was modified to add Domoticz devices matching the Hue device's capabilites, instead of hardcoded to RGBW type.
In some cases, this could mean there is now a Domoticz device with "correct" type, and an old one with the hardcoded RGBW type. The "old" device will still work, except that it won't be updated.
Please check if this is the case for you.

**Comment by jonferreira** [comment]
OK anything in particular I should be looking at?

![image](https://user-images.githubusercontent.com/7714292/38249818-dbd26c2a-3744-11e8-93d5-a4ae0942822a.png)

That seems to be a bit of a mess with loads of scenes and groups but the bulbs itself are 56, 57, 85,86 and 637

I did noticed that they keep getting renamed for some reason. They've "lost" their name after updating, i.e. overriden by what's on the Hue Bridge, and I've renamed them twice already but keep reverting to what's on Hue Bridge eventually

**Comment by emontnemery** [comment]
Yeah, looks a bit messy...
I'll add some debug prints to try to narrow in on what goes wrong.
Are you building Domoticz yourself, and if not which HW do you run on (Windows, Linux RPi, Linux x64..)?

**Comment by jonferreira** [comment]
Nop, not that skilled I'm afraid so standard Domo install (Beta channel) on a PI with Jessie

Happy to help diagnosing if you give me some pointers on what you need.

**Comment by emontnemery** [comment]
Ouch, unfortunately I can't build for Pi...

Anyhow, standard log might be enough, please do:
- Stop the domoticz service on the pi
- Manually run domoticz with additional log
  `./domoticz -loglevel 3 -debug -verbose 2 -log log01.log`
- Turn on / off your hue light with Web UI
- Wait 20 s
- Turn on / off your hue light with Web UI
- Wait 20 s
- Turn on / off your hue light with other app
- Wait 20 s
- Turn on / off your hue light with other app
- Wait 20 s
- Paste contents of log01.log on pastebin or similar

**Comment by jonferreira** [comment]
OK I've just spent the last 1.3h around this.

Installed a new domo instance on a second PI just to follow your steps above, first with v3.8153 (working as expected) then with v3.9176  - working fine as well!

So that meant that same Domo version, controlling same hue bulbs, same bridge and same MQTT server had a different behaviour.

So I went a head and took drastic measures - deleted all the existing hue devices and recreate them. It's working fine now!
This seems to imply there's some sort of problem with the "migration script" and users may need to delete / recreate Hue devices.

Jeez that was painful!

**Comment by emontnemery** [comment]
OK, good to hear it's working for you now!

I also think something might not be quite right with the migration..
Anyhow, please close this issue unless you kept the domoticz.db from the "bad" setup and have time to do some more testing.

**Comment by jonferreira** [comment]
yeah I have hourly backups so should be able to restore the DB on the "test instance" and follow the steps you've mentioned.

Off topic: can you clarify the nvalue logic on Color Switch devices?

I get

```
on
{
   "Battery" : 255,
   "Color" : "",
   "Level" : 99,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Color Switch",
   "id" : "00000002",
   "idx" : 696,
   "name" : "Living Room Plant Pot Color Spot",
   "nvalue" : 1,
   "stype" : "RGBWW",
   "svalue1" : "99",
   "switchType" : "Dimmer",
   "unit" : 1
}

colour change
{
   "Battery" : 255,
   "Color" : "{\"b\":62,\"cw\":0,\"g\":255,\"m\":3,\"r\":92,\"t\":0,\"ww\":0}",
   "Level" : 99,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Color Switch",
   "id" : "00000002",
   "idx" : 696,
   "name" : "Living Room Plant Pot Color Spot",
   "nvalue" : 10,
   "stype" : "RGBWW",
   "svalue1" : "99",
   "switchType" : "Dimmer",
   "unit" : 1
}

off
{
   "Battery" : 255,
   "Color" : "{\"b\":62,\"cw\":0,\"g\":255,\"m\":3,\"r\":92,\"t\":0,\"ww\":0}",
   "Level" : 98,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Color Switch",
   "id" : "00000002",
   "idx" : 696,
   "name" : "Living Room Plant Pot Color Spot",
   "nvalue" : 0,
   "stype" : "RGBWW",
   "svalue1" : "98",
   "switchType" : "Dimmer",
   "unit" : 1
}
```

So, 1 for On, 0 for Off and 10 for "colour change"?

**Comment by emontnemery** [comment]
Yes exactly, nValues are device type dependent.
For dtype color switch:
```
#define Color_LedOff 0
#define Color_LedOn 1
#define Color_SetColor 10
```

Edit:
For the logic, nvalue = 0 or Level = 0 for off, otherwise switch is on.
There's a few variations on this in the Domotiz WebUI js.
You will always get a valid color object, not only if nvalue is 10.

**Comment by emontnemery** [comment]
@jonferreira I've setup a build environment for Pi now, I'll upload a build tomorrow with additional prints as well as (hopefully) a more sane migration of Hue devices that are of the "wrong" type.

**Comment by jonferreira** [comment]
@emontnemery sounds great, thanks for the effort.

I did noticed a few other quirks - will test a couple more times before opening a new issue but basically if you change **Level** on the Hue App / Switch MQTT isn't notified and when you change **Color** with the Hue App neither Domoticz or MQTT is notified. In my case I've changed Color quite a few times with the Hue App in the past few minutes and the Color variable is stuck at "{\"b\":81,\"cw\":0,\"g\":255,\"m\":3,\"r\":29,\"t\":0,\"ww\":0}" (last color change I did with domo)

**Comment by emontnemery** [comment]
The non update of color is intentional, I don't own genuine Hue lights and didn't want to add that functionality without testing. Please go ahead and open a new issue requesting that if you have time to test it.

**Comment by emontnemery** [comment]
Updated Pi build with:
- Extra prints
- Improved migration of Hue devices with "wrong" type (should now change subtype instead of creating new devices)

http://montnemery.com/domoticz_hue/linux_armv7l/001/domoticz_linux_armv7l.tgz

**Comment by jonferreira** [comment]
Fantastic work, thanks.

I take you'll do a pull request soon and all I'll need to do is to update to the latest Beta?

**Comment by emontnemery** [comment]
Do you mean you can not reproduce _either_ of these issues:
- No MQTT update when turning on/off in an external app
- Web UI does not auto refresh when turning on/off in an external app

when you start with your pre-upgrade database backup with this builld: http://montnemery.com/domoticz_hue/linux_armv7l/001/domoticz_linux_armv7l.tgz

**Comment by jonferreira** [comment]
I've not tested it yet, will do it later today - was just congratulating for the effort.

I've opened up #2281 though
