### ISSUE TITLE
domoticz.com offline

### ISSUE THREAD

**Issue by Failure404** [domoticz/domoticz#2274]
Sorry for posting here.
domoticz.com is offline since yesterday and I really need that beta update.
Thanks for reading.

**Comment by gizmocuz** [comment]
I think it is a cloudflare issue, temporarily disabled. Could you try again ?

**Comment by Failure404** [comment]
At the moment it seems it's still going through CF.
CF tells me "An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources."

**Comment by mo8Zomo0** [comment]
Thats the CFdescription to the 522 error:
https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522

I get either or error:
![screen shot 2018-04-03 at 13 47 51](https://user-images.githubusercontent.com/2004752/38247902-0f369d82-3747-11e8-97ac-b0dc1baf096c.png)

![screen shot 2018-04-03 at 12 45 01](https://user-images.githubusercontent.com/2004752/38247903-0f59e314-3747-11e8-8312-5308925a7b4f.png)

**Comment by gizmocuz** [comment]
Could you try again, maybe it was in the middle of a reboot

**Comment by gizmocuz** [comment]
works now perfectly here

**Comment by mo8Zomo0** [comment]
No, still does not work from Northern Europe:

Error 522 Ray ID: 405b68e17cf34279 • 2018-04-03 12:07:02 UTC
Connection timed out


![screen shot 2018-04-03 at 14 07 56](https://user-images.githubusercontent.com/2004752/38248441-a9684a8a-3748-11e8-971b-daf0333c4578.png)

**Comment by Failure404** [comment]
For a brief moment I could access it, but now it's back to 522.

**Comment by mo8Zomo0** [comment]
@Failure404 as I mentioned above, it could also have been a cached version, I got that as well.

@Failure404  / @gizmocuz : where are you located?

I just checked with a host in the US and that was able to access the file. So it still can be a DNS or access list (server/firewall/...) issue.

```
# wget -O domoticz_release.tgz "http://www.domoticz.com/download.php?channel=stable&type=release&system=${OS}&machine=${MACH}"
--2018-04-03 14:15:54--  http://www.domoticz.com/download.php?channel=stable&type=release&system=linux&machine=armv7l
Resolving www.domoticz.com (www.domoticz.com)... 104.31.78.142, 104.31.79.142, 2400:cb00:2048:1::681f:4e8e, ...
Connecting to www.domoticz.com (www.domoticz.com)|104.31.78.142|:80... connected.
HTTP request sent, awaiting response... 522 Origin Connection Time-out
2018-04-03 14:16:25 ERROR 522: Origin Connection Time-out.

```


vs from the US:

```
#  wget "http://www.domoticz.com/download.php?channel=beta&type=release&system=linux&machine=armv7l"
--2018-04-03 14:17:51--  http://www.domoticz.com/download.php?channel=beta&type=release&system=linux&machine=armv7l
Resolving www.domoticz.com (www.domoticz.com)... 2400:cb00:2048:1::681f:4e8e, 2400:cb00:2048:1::681f:4f8e, 104.31.79.142, ...
Connecting to www.domoticz.com (www.domoticz.com)|2400:cb00:2048:1::681f:4e8e|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://releases.domoticz.com/releases/beta/domoticz_linux_armv7l.tgz [following]
--2018-04-03 14:18:07--  http://releases.domoticz.com/releases/beta/domoticz_linux_armv7l.tgz
Resolving releases.domoticz.com (releases.domoticz.com)... 2400:cb00:2048:1::681f:4e8e, 2400:cb00:2048:1::681f:4f8e, 104.31.79.142, ...
Reusing existing connection to [www.domoticz.com]:80.
HTTP request sent, awaiting response... 200 OK
Length: 13220161 (13M) [application/octet-stream]
Saving to: ‘download.php?channel=beta&type=release&system=linux&machine=armv7l’

download.php?channe 100%[===================>]  12.61M  7.69MB/s    in 1.6s

2018-04-03 14:18:09 (7.69 MB/s) - ‘download.php?channel=beta&type=release&system=linux&machine=armv7l’ saved [13220161/13220161]

```

The actual download then seems to be hosted on a different server which works for me.
@Failure404 so if you know how to build the right URI you can access it like:
http://releases.domoticz.com/releases/beta/domoticz_linux_armv7l.tgz for a RaspberryPi

**Comment by Failure404** [comment]
@mo8Zomo0 You are right, I was able to fetch the file.
I'm located in Germany.

**Comment by DewGew** [comment]
I got the 522 error also...

**Comment by dobber81** [comment]
I was able to reach domoticz.com for a brief few seconds, then back to 522.
Error 522 Ray ID: 405bb300cff67606 • 2018-04-03 12:57:39 UTC
Trying from Sweden

**Comment by gizmocuz** [comment]
Yes, the download is hosted on another server
I'm located in the netherlands
I did a reset of the server some hours ago

Maybe this is a cloudflare issue as we have been using this for quite some time, and it always worked OK
Possibly we need to wait some days

**Comment by emontnemery** [comment]
Sorry for very offtopic, but how are the raspberry pi beta binaries built?

**Comment by gizmocuz** [comment]
I send a message to the hosting provider, if this does not improve by Thursday I will move it to another VPS

The betas are build with two raspberry pi's I bought... Crontab to build is once an hour

**Comment by Tontze** [comment]
aaargh this withdrawal symptom without forum ... :D

**Comment by jeffreyveldt** [comment]
Online, but with a major certificate issue. 290 days overdue.

**Comment by gizmocuz** [comment]
i know... i disabled cloudflare...

**Comment by jppmedia** [comment]
In the south of France also "offline"

**Comment by gizmocuz** [comment]
Should be online again, try a shift-refresh

**Comment by jppmedia** [comment]
OK! online in France!

**Comment by sweetpants** [comment]
Hmm, I'm having problems resolving www.domoticz.com

dig www.domoticz.com 

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.domoticz.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: **SERVFAIL**, id: 20605
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.domoticz.com.		IN	A

;; Query time: 18 msec
;; SERVER: 192.168.24.250#53(192.168.24.250)
;; WHEN: Wed Apr 04 18:31:09 CEST 2018
;; MSG SIZE  rcvd: 45

DNS server is not answering, other sites work fine.
Looks like the delegation to domoticz.com is gone (NS records missing)
Secure delegation is broken. When using DNSSEC validation there is no answer returned. According to whois the zone should be signed, but it isn't see http://dnsviz.net/d/domoticz.com/dnssec/

   Name Server: NS1.TRANSIP.NL
   Name Server: NS2.TRANSIP.EU
   DNSSEC: signedDelegation
   DNSSEC DS Data: 13686 7 1 DF15728F313981672EA8BB35869D8421535E017D
   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
**>>> Last update of whois database: 2018-04-04T16:50:06Z <<<**

**Comment by gizmocuz** [comment]
Should be ok, changes could take 24 hours

**Comment by witsoft001** [comment]
I can not access to domoticz.com for a few weeks ,and get error 1020 access denied by cloudflare , in China.  What should I do, thanks!

**Comment by gizmocuz** [comment]
@witsoft001 , i am afraid whole China is currently blocked because the server is under attach since weeks... From China
One way to solve this for now is to use a free VPN service.
I am sorry, but currently there is no other way

**Comment by witsoft001** [comment]
> @witsoft001 , i am afraid whole China is currently blocked because the server is under attach since weeks... From China
> One way to solve this for now is to use a free VPN service.
> I am sorry, but currently there is no other way

Thanks for your reply.
