### ISSUE TITLE
Deleting device logs does not work anymore

### ISSUE THREAD

**Issue by sweetpants** [domoticz/domoticz#2276]
Since last beta(s) V3.9176, deleting device logs does not work anymore. When pushing 'Clear' it asks for confirmation, press Ok and nothing happens. I think commit dbe8f40 has something to do with this

**Comment by Failure404** [comment]
I am experiencing the very same problem. Clicking OK and nothing happens.

**Comment by sweetpants** [comment]
When you refresh the page (F5) the log eventually is cleared.

**Comment by sweetpants** [comment]
Thanks, working again
