### ISSUE TITLE
Color lights not handled by python plugins onCommand callback

### ISSUE THREAD

**Issue by 999LV** [domoticz/domoticz#2278]
Before the Easter break, the work done by @emontnemery in his branch [https://github.com/emontnemery/domoticz/tree/rgbww_dev_merge](url) worked well with python plugins. When coming back from the break, I note that neither that repo nor the main domoticz/development code (now that it is merged) work: python plugins onCommand callback no longer gets called.

I could be more precise with build numbers or diff analysis if needed, but I sense this is a result of the rebasing of the pull request into the domoticz repo.

**Comment by emontnemery** [comment]
Please explain the issue in more detail: Which action is it that does not trigger an onCommand?
If it's the web UI, please test in incognito mode / in private tab to make sure it's not a cache issue.

**Comment by 999LV** [comment]
thanks @emontnemery , but I was way too fast in posting that issue... it has nothing to do with your work nor domoticz as a matter of fact...
It is just that my plugin imports the bluepy module (to drive the RPi bluetooth LE adapter) and that module seems to have some poor error handling that causes in certain circumstances all messages queued for the plugin to be stuck.... including onCommand !
I'll try to find a better bluetooth module to use...
Closing the issue
