### ISSUE TITLE
FloorPlans issue

### ISSUE THREAD

**Issue by kovainfo** [domoticz/domoticz#2279]
When i press on temp sensor or baro sensor - screen is cleared and nothing more.

**Comment by quack3d** [comment]
Same thing reported here: https://www.domoticz.com/forum/viewtopic.php?f=6&t=22901

**Comment by szczukot** [comment]
I have this same problem

**Comment by dnpwwo** [comment]
Seems that someone is working their way through Domoticz changing how the Log page works for the HTML tabs but not the Floorplans.

Pushed a fix for Temperature sensors but only just saw the post for switches

**Comment by kovainfo** [comment]
@dnpwwo Cool! But BARO sensor still have this issue. including dummy baro sensor...

**Comment by pj-r** [comment]
Found one more: Custom sensors.

This one is compressor hz from MySensors heat pump node but this can be reproduced with dummy custom sensor.

`VM186 Floorplans:1 Uncaught ReferenceError: ShowGeneralLog is not defined
    at SVGImageElement.onclick (VM158 Floorplans:1)`

`      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 15,
         "Data" : "0 Hz",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 4,
         "HardwareName" : "Mys-Wireless-LAN",
         "HardwareType" : "MySensors Gateway with LAN interface",
         "HardwareTypeVal" : 42,
         "HaveTimeout" : false,
         "ID" : "00000105",
         "Image" : "Heating",
         "LastUpdate" : "2018-04-16 13:51:15",
         "Name" : "PumppuCompressor",
         "Notifications" : "false",
         "PlanID" : "13",
         "PlanIDs" : [ 13 ],
         "Protected" : false,
         "SensorType" : 1,
         "SensorUnit" : "Hz",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Custom Sensor",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "Heating",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "152",
         "YOffset" : "434",
         "idx" : "142"
      },`

**Comment by kovainfo** [comment]
!Can't find variable: ShowGeneralLog
{
    function onclick(evt) {
        if (Device.ignoreClick != true) {
            $("body").trigger("pageexit");
            ShowGeneralLog('#floorplancontent', 'ShowFloorplans', '1', 'Pressure', '');
        }
        ;
    }
}

**Comment by gizmocuz** [comment]
@dnpwwo , seems indeed like it, but the changes are great!

**Comment by pj-r** [comment]
Looks like dashboard uses(works correctly):
`ShowGeneralGraph('#dashcontent','ShowFavorites',142,'PumppuCompressor','Hz', 'Custom Sensor');`

And floorplan tries now to use this url:
'#/Devices/142/LightLog'

I think it should show graph for sensors instead of lightlog?
```
this.type: "General"
item.SubType: "Custom Sensor"
item..SensorUnit: "Hz"
```

**Comment by waltervl** [comment]
To be closed?
