### ISSUE TITLE
MiLight Controllers and RGB/RGBWW/RGBWW+CTT update 

### ISSUE THREAD

**Issue by poudenes** [domoticz/domoticz#2280]
Version v3.9177
Platform: Rasbian
Hardware: Limitless/AppLamp/Mi Light with LAN/WiFi / SET MODE: V6 RGBWW

After RGB/RGBWW/RGBWWCTT update this MiLight Controller Support is broken.
I have 2 controllers but focus on 1 because the problem is clear to understand.

When i add first 4 zones (remote 1) everything is work how it has to be.<br/>
When i add second 4 zoned(remote 2) they all act like the first 4 zones. So it doen't control the second 4 zones.

With Version: 3.9139 Build Hash: 75213953 this problem wasn't there.

MiLIght Controller with first Remote: Zone 1, 2, 3, 4 RGBWW
![img_3162](https://user-images.githubusercontent.com/4399532/38297611-5721840a-37f5-11e8-816e-fd7158210699.png)

MiLIght Controller with second Remote: Zone 1, 2, 3, 4 RGBW
![img_3163](https://user-images.githubusercontent.com/4399532/38297619-5b962ad6-37f5-11e8-8745-a650fef8246c.png)

Here when MiLilight Controller is added in Domoticz. and the total 8 zones:
![screen shot 2018-04-04 at 10 33 39](https://user-images.githubusercontent.com/4399532/38297623-5eebbbb0-37f5-11e8-84d2-398ce5b031d9.jpg)

**Comment by emontnemery** [comment]
Did you change anything in your setup, did you for example recreate the "MiLight" hardware?
Which steps do you follow to add your remotes?
I'm asking because Domoticz' Limitless code is very simple, there seems to be no way for one instance of "Limitless/Applamp/Mi Light" to control more than a single light plus the groups so I think you need to create two instances of "Limitless/Applamp/Mi Light".

**Comment by emontnemery** [comment]
I've reviewed the Limitless code more carefully now, and I think you misremember, it really seems impossible you had Remote 1 and Remote 2 tied to a single Domoticz Hardware instance, there is no support for this in the Domoticz code.
Please remove hardware "MiLIght 1", then add first a "Milight 1" with type set to RGBW, and then a "Miligth 2" with type set to RGBWW, and confirm if it solves your issue:
![image](https://user-images.githubusercontent.com/14281572/38335103-867e01d4-385d-11e8-8cf6-696162724fd9.png)

**Comment by poudenes** [comment]
When a do a clean install and add 1 milight controller and change mode to v6 and rgbww then in device list I see all 8 zones. 
I did this all the time when I did a rebuild of my system after playing around and screwed up.

I will do some tests and add them separate and see what happen

**Comment by emontnemery** [comment]
Yes, you will see all 8 zones because the limitless code does not clean up after itself when you change the mode.
However:
- If mode is V6/rgbw, only the rgbw zones can be controlled
- If mode is V6/rgbww, only the rgbww zones can be controlled

Please test a bit more, then I'll modify the limitless code to clean up when mode is changed..

**Comment by poudenes** [comment]
I did add now as follow:
1) add Milight Contoller 1 as "MLC 1 RGBWW" hardware
2) change Mode to V6 / RGBWW
3) add the zones that have RGBWW
4) add Milight Controller 1 as "MLC 1 RGBW" hardware
5) change mode to V6 / RGBW
6) add the zones that have RGBW

This is not working at all.
None of the bulbs are working then

**Comment by emontnemery** [comment]
@poudenes I'm out of ideas and I have no Milight Controller to test with :(
One way forward would be to build a debug version of the older, working, Domoticz and dump data sent to the controller by the Limitless code..
You're running Domoticz on a Raspberry Pi, correct?

**Comment by poudenes** [comment]
@emontnemery Did a second test

Add Controller with V6/RGBWW mode i get 4 Zones RGBWW and 4 Zones RGB 
Both 4 zones have same output. So Zone 1 RGBW is same as Zone 1 RGBWW etc

Add same Controller with V6/RGBW mode i get 4 Zones RGBW

Now all bulbs are working again.

So when you add a MiLight Controller with latest beta it add 2 x 4 Zones But the Zones with RGBW as SubType are same as the 4 zones RGBWW
In old Beta when you add MiLIght Controller you get 2 x 4 zones and have total 8 zones to control with 1 Hardware device

So something has been changed....

Ill now make a copy of my working Domoticz Config and add new MiLight Controller for RGBW and see if i can run the latest beta then

**Comment by emontnemery** [comment]
_In old Beta when you add MiLIght Controller you get 2 x 4 zones and have total 8 zones to control with 1 Hardware device_
Can you please let me know "Build Hash" of old beta which is working for you, you find it on Setup->About page.
Then I will modify that version with some additional prints.

**Comment by poudenes** [comment]
@emontnemery Here you are:
Version: 3.9139
Build Hash: 75213953
Compile Date: 2018-03-31 08:19:09
dzVents Version: 2.4.1
Python Version: 3.4.2 (default, Oct 19 2014, 14:03:53) [GCC 4.9.1]

also did:

Did some tests with a different RPi and copy of my current running system
Add new MiLight Controller with V6/RGBW, add the 4 zones.

Now the scripts working again. 

I only see 1 missing thing now. RGBW devices doen't have a Kelvin option. Maybe you can add this with a button and underwater is gives the Bulb RGB Color (255.255.255) 

Now devices have only ColorPicker and Brightness option. You can't change them to Full Color (Kelvin) old style color of a normal Bulb.

**Comment by emontnemery** [comment]
@poudenes 
> Now the scripts working again. I only see 1 missing thing now.

I'm confused:
- Beta with build hash 7521395: Is working or not working?
- Latest beta: Is working or not working?

> RGBW devices doen't have a Kelvin option

This is correct, RGBW device has only single white LED, so no way to support color temperature

**Comment by poudenes** [comment]
@emontnemery Version: 3.9139 Build Hash: 7521395 is beta build that work (old situation) 1 Hardware device and 2 x 4 zones RGBWW and RGBW

I have on a different RPi copied this version. updated to latest beta (as speak) and add again MiLight Controller with V6/RGBW mode. Add those 4 zones and updated scripts (IDX) and worked.

I use setRGB() with dZvents and put de RGBW Bulb to rub(255.255.255) to have the Kelvin back.

**Comment by emontnemery** [comment]
@poudenes So to conclude, there is no more issue, everything is working now even with latest beta?

To set white, just use the color picker in white mode:
![image](https://user-images.githubusercontent.com/14281572/38389322-5a5b6a30-391e-11e8-8c13-8ae4bd0299e5.png)

**Comment by odelma** [comment]
@emontnemery 

> I've reviewed the Limitless code more carefully now, and I think you misremember, it really seems impossible you had Remote 1 and Remote 2 tied to a single Domoticz Hardware instance, there is no support for this in the Domoticz code.

I'm afraid you are somewhat mistaken here. I can confirm I have been using the same MiLight hardware for setting up both RGBW and RGBWW groups controls (i.e. to control the 8 groups available in v6 bridges). After updating to latest beta this is not possible anymore as @poudenes reported. For me this meant that half of my MiLight switches stopped working. It is now only either RGBW or RGBWW that works via Domoticz, depending which I setup last. I have altogether six bridges so I'm very much hoping there is a way to fix it to avoid setting up 6 new hardware devices and 30 new switches to groups, scenes, scripts etc. :smile: But if it comes to that it is of course doable.

All in all, an excellent update to extend the usability of Domoticz with RGBW(W) hardware 👍

**Comment by emontnemery** [comment]
@odelma Alright then :)
I want to prepare a debug build of the old Domoticz code to see what it sends to the Milight controller, obviously I don't 'get' the Domoticz' Limitless implementation. Which OS and HW are you running Domoticz on?
Edit: You have added the controllers to Domoticz as HW type "Limitless/AppLamp/Mi Light with LAN/WiFi interface", right?

**Comment by poudenes** [comment]
@emontnemery I have saved all my old versions. So if you want a old running beta version where Milight controller control 2 x 8 zones let me know

**Comment by emontnemery** [comment]
@poudenes I mean I want to build a beta for you or @odelma which will have some extra prints.
Here's a raspbian build: http://montnemery.com/domoticz_limitless/linux_armv7l/001/domoticz_linux_armv7l.tgz
Please collect log with this build where you toggle all eight groups (RGBW and RGBWW).
There should be some print like: Limitless: sending followed by hexdump of data sent to the controller.

**Comment by emontnemery** [comment]
@poudenes, @odelma: here's a Raspbian build: http://montnemery.com/domoticz_hue/linux_armv7l/004/domoticz_linux_armv7l.tgz
Now it should again be possible to control 4 RGBW and 4 RGBWW devices, please test.
@odelma Let me know if you need build for other platform.

**Comment by poudenes** [comment]
@emontnemery correct. I can add 1 Milight Controller and set mode to V6/RGBWW and can control all 2 x 4 Zones again. Everything work Color Picker + Brightness, Kelvin + Brightness

i Have 1 Bulb RGBW add in a RGBWW Zone. Kelvin not work (Thats Correct) Give upper part Kelvin and can use brightness. Colder part not work but thats correct. I see no strange behaviour because of the RGBW RGBWW mixup for this bulb

**Comment by odelma** [comment]
@emontnemery Thanks, I can confirm this version is working in similar way as it was before I updated to latest beta. Both RGBW and RGBWW groups are working for the same MiLight hardware. Here's log output for two switches, both in group 1 and the first is RGBWW and the second RGBW:

2018-04-08 00:00:07.475 User: Admin initiated a switch command (473/TV taustavalo/On)
2018-04-08 00:00:07.887 RFLink: 20;11;MiLightv1;ID=20262B;SWITCH=01;RGBW=0000;CMD=ON;
2018-04-08 00:00:07.916 (MiLight Bridge5 v6) Color Switch (TV taustavalo)
2018-04-08 00:00:07.916 MQTT: Publish: domoticz/out ({
"Battery" : 255,
"Color" : "{\"b\":0,\"cw\":255,\"g\":0,\"m\":2,\"r\":0,\"t\":0,\"ww\":0}",
"Level" : 39,
"RSSI" : 12,
"description" : "",
"dtype" : "Color Switch",
"id" : "1",
"idx" : 473,
"name" : "TV taustavalo",
"nvalue" : 1,
"stype" : "RGBWW",
"svalue1" : "39",
"switchType" : "Dimmer",
"unit" : 1
}
)

2018-04-08` 00:00:11.020 User: Admin initiated a switch command (468/Olohuoneen kattovalo/On)
2018-04-08 00:00:11.225 RFLink: 20;12;MiLightv1;ID=26AA;SWITCH=01;RGBW=e600;CMD=ON;
2018-04-08 00:00:11.282 (MiLight Bridge5 v6) Color Switch (Olohuoneen kattovalo)
2018-04-08 00:00:11.283 MQTT: Publish: domoticz/out ({
"Battery" : 255,
"Color" : "{\"b\":0,\"cw\":255,\"g\":0,\"m\":1,\"r\":0,\"t\":0,\"ww\":255}",
"Level" : 48,
"RSSI" : 12,
"description" : "",
"dtype" : "Color Switch",
"id" : "1",
"idx" : 468,
"name" : "Olohuoneen kattovalo",
"nvalue" : 1,
"stype" : "RGBW",
"svalue1" : "48",
"switchType" : "Dimmer",
"unit" : 1
}
)

> Which OS and HW are you running Domoticz on?
You have added the controllers to Domoticz as HW type "Limitless/AppLamp/Mi Light with LAN/WiFi interface", right?

I'm running Domoticz on Raspbian Stretch / RPi3B and hardware is as you mention.

edit: cannot do much more testing with this version as my Aeotec Z-wave USB stick is not recognized and I don't have a separate test build.

edit2: probably not (at least directly) related to this but I'll note this down here as I cannot at the moment debug this very much. With MiLight bridge v5 and RGBW bulbs I cannot seem to turn them back to white if I change them to a certain color. If I change to the dimmer slider, it only dims the active color and does not change it to white.

**Comment by emontnemery** [comment]
@poudenes, @odelma Is everything working now in latest beta?
@odelma This issue: _With MiLight bridge v5 and RGBW bulbs I cannot seem to turn them back to white if I change them to a certain color._ is #2303, right?

**Comment by odelma** [comment]
@emontnemery Yes, all of these issues are solved, at least on my setup. Thanks a lot!

**Comment by poudenes** [comment]
@emontnemery everything is working here as well. Also at my setup :). I didn't revert back with MiLIght Controller to control 8 zones on 1 hardware devices. I leave it as it is now :)

**Comment by emontnemery** [comment]
@poudenes OK, I'm sorry about being a bit stubborn about RGBW + RGBWW at the same time :)
Please close this issue of everything is working now.
