### ISSUE TITLE
Selector/dimmer switches missing after 3.9168

### ISSUE THREAD

**Issue by Mats80L** [domoticz/domoticz#2282]
Hi

After updating to beta 9168 several switches are missing from both the dashboard and the switches page

Found this thread on the forum describing other user with the same issue:
[http://www.domoticz.com/forum/viewtopic.php?f=6&t=22902](url)

App cache has been cleared
I even tried it on a fresh computer and get the same issue there

Strange thing it works better on a mobile client, there the devices are visible on the dashboard but not under the switches tab

Notice it is the same room in all below screenshots

PC Dashboard:
![image](https://user-images.githubusercontent.com/38070001/38301993-8acee89a-3801-11e8-84e6-f7c51e646ac9.png)

PC Switches:
![image](https://user-images.githubusercontent.com/38070001/38302018-98496ce8-3801-11e8-8d25-c81a5173daab.png)

IPAD Dashboard:
![image](https://user-images.githubusercontent.com/38070001/38302088-cac72cf0-3801-11e8-9bee-9fb35dd9f777.png)

IPAD Switches tab:
![image](https://user-images.githubusercontent.com/38070001/38302111-d7da62d6-3801-11e8-8000-3910b81d8a31.png)

**Comment by emontnemery** [comment]
Please:
- Try in incognito mode / in private tab.
- Open chrome developer console (ctrl-shift-i) and check if there are any error messages when switching between dashboard and switches tabs

**Comment by Mats80L** [comment]
Hi!

Yes there is an error caught in the console when switching pages:

![image](https://user-images.githubusercontent.com/38070001/38305777-66b5a482-380e-11e8-9f53-881cd0b66405.png)

**Comment by Mats80L** [comment]
And same error in incognito mode...

**Comment by emontnemery** [comment]
That's caused by Chrome using an outdated version of domoticz.js
Can you please:
- Paste row "Build Hash" from page /#/About (Setup-About) here
- Delete www/js/domoticz.js.gz from your Domoticz installation directory if it exists, and please confirm if the file existed (there's a workaround in the code to delete it)
- Confirm you see the issue also in an "incognito mode" tab
- Force clean Chrome's cache:
  - Open the developer console, select the network tab, refresh the page
  - right click on an item in the network tab, select 'clear cache'
  - Next clear the appcache, navigate to chrome://appcache-internals/

**Comment by Mats80L** [comment]
Played around abit and updated to latest beta, same error there

Build Hash:
![image](https://user-images.githubusercontent.com/38070001/38321007-88742954-3836-11e8-868f-8fce7f0c9ced.png)

Deleted file domoticz.js.gz - It existed

Same issues in icognito tab

History and cache cleared, appcache removed

After removing domoticz.js.gz a new error is generated
I think after removing this file my PC browser started acting better, more devices are shown on the dashboard
But under the Switches tab the error is generated in Chrome and there are several devices/switches missing there
![image](https://user-images.githubusercontent.com/38070001/38321443-fe6472f8-3837-11e8-8e34-f0699366ddf6.png)

**Comment by Mats80L** [comment]
Im running domoticz on Linux x86_64 if thats of any help
Ubuntu 16.04

So I did some more testing to try and fix this

I made a backup of my domoticz folder
Then deleted the whole domoticz folder and rebuilt the latest stable (master branch) version from scratch
Restored my DB, scripts and floorplan image from the backup
At this point everything is working again, everything is visible on both Dashboard and Switches tabs

At that point I reran the updatebeta script and updated to latest beta
And the exact same issues and errors are then back again

I think I will downgrade to the stable version again

**Comment by emontnemery** [comment]
Interesting that the file domoticz.js.gz was still there, it should have been automatically removed.
Which OS is Domoticz running on?
Can you confirm the file www/js/domoticz.js (with no .gz) is present?

If www/js/domoticz.js is present, please do the following:
- Open chrome  developer console
- Open the switches tab in Domoticz
- Show the network tab in developer console
- Right click on row json.htm?type=devices&filter=light&used=true&order=[Order]&plan=0 and choose copy->copy respone
- Paste the response here

Edit:
I must be tired, you can just go to URL <domoticzserver:8080>json.htm?type=devices&filter=light&used=true&order=[Order]&plan=0 directly, no need to go through all the hoops of the developer console.
Also, you should change plan parameter to match the room which has the problem.

**Comment by emontnemery** [comment]
@Mats80L It would be really great if you could paste the response to json.htm?type=devices&filter=light&used=true&order=[Order]&plan=0 for the non working version though.

**Comment by Mats80L** [comment]
Linux Ubuntu 16.04 x86_64
Updated to beta again 3.9185

Found something interesting when editing the roomplan:

See that device named RGB
![image](https://user-images.githubusercontent.com/38070001/38328027-0f544d88-384a-11e8-92ec-3f98e3767fd2.png)

Moving it up and down in the plan determines what devices are shown in the dashboard and switches tab

![image](https://user-images.githubusercontent.com/38070001/38327870-aca0f79a-3849-11e8-8bad-38d1148ed862.png)
![image](https://user-images.githubusercontent.com/38070001/38327902-bc565888-3849-11e8-8231-8be884ab3156.png)

![image](https://user-images.githubusercontent.com/38070001/38327954-e421f804-3849-11e8-8281-06b0c967c219.png)
![image](https://user-images.githubusercontent.com/38070001/38327968-ea1793f4-3849-11e8-8d96-d9e2cef15559.png)

Json output as you requested, for room 2
[json-output-plan2.txt](https://github.com/domoticz/domoticz/files/1877202/json-output-plan2.txt)

**Comment by Mats80L** [comment]
Removing that TRC02 device in the Devices settings seems to have solved the issue as far as I can see...

Something with the new RGB code perhaps?

**Comment by emontnemery** [comment]
Thanks a lot, super helpful!

The issue is this device: "Vardagsrum - RGB" of type "TRC02 (RGB)".
When changing the LED color dimmer stuff (#2229), I did not find any user with TRC02 device and the code differs a lot from all other color dimmer HW.
So, I left the TRC02 code as "TODO", but didn't realize it would break the UI..

Can you confirm if it is possible to set color of "Vardagsrum - RGB" with stable version of Domoticz?
If possible, how, is it with the color picker or some other way:
![image](https://user-images.githubusercontent.com/14281572/38328853-44cfd476-384c-11e8-8b9c-565c93c9a17e.png)

PS:
Är det inte dags att slänga ut julgranen snart? :)

**Comment by emontnemery** [comment]
@Mats80L, please try this version: http://montnemery.com/domoticz_trc02/150.1/3e6ea9aa26599d30ffd7d1e98a520b41c63ff2af/domoticz_linux_x86_64.tgz
Now WebUI should show up even with "Vardagsrum - RGB" in the list, and there's a (fairly slim) chance you can also set color of your TRC02 devices.

**Comment by Mats80L** [comment]
Installed that file and it did the trick, seems ok now. 
Good job!

![image](https://user-images.githubusercontent.com/38070001/38335417-7f3375e8-385e-11e8-9d4b-316cf12e8357.png)

And the julgran is gone for the year but the nexa switch is left in the socket year round, otherwise they tend to gets lost or mixed up until next christmas

Thanks for your help emontnemery!

**Comment by emontnemery** [comment]
@Mats80L Cool! So even setting the color of the TRC02 switch actually works? Does the brightness slider work too?

**Comment by Mats80L** [comment]
I noticed that the mobile version of the webpage is still broken
It has the same issue where placing this device amongst the devices causes all following devices to not be shown on the webpage

The On/Off command works well, and to be honest that all that I really use
I set a color manually and let domoticz controll the on/off on a timer.


But another problem is that the other commands causes the TRC02 controller to change mode
In domoticz I am guessing the ON command now gets resent with every command, like dim or change color
Every time you press ON on the physical remote it changes mode/cycles to different effects
color picker -> fade1 -> fade2 -> white

So the On button is not only used for On but is also a mode selector
Found this manual describing it
![image](https://user-images.githubusercontent.com/38070001/38354862-561710e0-38bb-11e8-8827-1a28aeaaed19.png)


And the color picker is off, choosing red (4times to counter above bug) generates some kind of blue color
![image](https://user-images.githubusercontent.com/38070001/38355447-3833425e-38bd-11e8-811d-9e7cfc0db170.png)

**Comment by Eisenhauer1987** [comment]
Hi,

i have a simular problem after updating to latest beta for pi3:

Version: 3.9198
Build Hash: b7c82601
Compile Date: 2018-04-05 11:39:38
dzVents Version: 2.4.3

Since this, no Hue and Arilux AL-LC0x devices display on the dashboard tab. On the Switch tab is all normal and i can switch the lights normal.

What can i do to solve the problem?

**Comment by gizmocuz** [comment]
@Eisenhauer1987 , clear the browser cache + appcache , two different things

**Comment by Eisenhauer1987** [comment]
all cleared, now i have no switches in switch tab, too.

**Comment by emontnemery** [comment]
@Eisenhauer1987 Please check two things:
- Please delete file www/js/domoticz.js.gz in Domoticz installation directory if present
  **Note: Do NOT delete www/js/domoticz.js**
  - If present, clear the browser cache + appcache again
- Please open developer console (ctrl-shift-i) and check for any errors when you switch between dashboard and switches tab

**Comment by emontnemery** [comment]
@Mats80L 
**For the mobile version:**
Have you tried incognito mode on your mobile device to make sure it's not cache issue?
If it's not, try to reproduce in Chrome set to mobile mode:
- Open developer mode
- Click this icon: ![image](https://user-images.githubusercontent.com/14281572/38371695-61ced8fa-38ed-11e8-8184-06846b97f226.png)
- Reload

**For the TRC02 issues:**
Thanks for the really clear test report! The remaining issues must be old ones, but I guess now is as good a time as any to fix them..
- The reason for the unintentional mode change is clear, I'll make a new build where it should be fixed
- For the wrong color mapping, plese try to play around with the color picker and find the setting that gives you bright red, bright green and bright blue and paste corresponding log.

**Comment by emontnemery** [comment]
@Mats80L Please test this version where TRC02 should no longer change modes on color change: http://montnemery.com/domoticz_trc02/151.1/061cbfb3e32c74108ac2d1009536bd4aa4def2b9/domoticz_linux_x86_64.tgz

**Comment by Mats80L** [comment]
That version works fine, it switches correctly

**Comment by emontnemery** [comment]
Brilliant!

Do have the energy/time to do some testing of the color setting as I suggested?

**Comment by Mats80L** [comment]
And I played with the color picker and pulled the log:

Red (around orange in todays color picker):
setcolbrightnessvalue: ID: 5a, bri: 29, color: '{m: 3, RGB: ffb600, CWWW: 0000, CT: 0}'
TRC02: Color.mode: 3
TRC02: r:255,g:182,b:0,->30
TRC02: Color.mode: 3
TRC02: Setting color to: 9

Green (where blue is today):
setcolbrightnessvalue: ID: 5a, bri: 100, color: '{m: 3, RGB: 0e31ff, CWWW: 0000, CT: 0}'
TRC02: Color.mode: 3
TRC02: r:14,g:49,b:255,->164
TRC02: Color.mode: 3
TRC02: Setting color to: 50

Blue is impossible to generate in domoticz color picker
Based on manually playing around in RFXMNGR it should have code 93 
= TRC02: Setting color to: 93

-------------------------------------------------------------------

From RFXMNGR
Color Range is 6-84 HEX
Subtract 6 from RFXMNGR color code to get the domoticz color code

Red: (Domoticz Color = 9)
RFXmngr Command sent = Color F (HEX for 15)

Green: (Domoticz Color = 50)
Send RFXmngr Command = Color 38 (HEX for 56)

Blue: (Domoticz Color = 93?)
RFXmngr Command = Color 63 (HEX for 99)

**Comment by Mats80L** [comment]
Perhaps the range needs to be increased?

Largest value I can select on the color picker generates a value of 78
TRC02: Setting color to: 78

Max value domoticz should send should be 126 to get all colors if my math is correct

**Comment by emontnemery** [comment]
Yeah, the range seems wrong, I think hex and decimal is mixed in Domoticz:
Hue is mapped to 84-6=78, but it should be **0x**84-6=126, right?

**Comment by Mats80L** [comment]
yes exactly

**Comment by Eisenhauer1987** [comment]
Hi,

deleting the file:  www/js/domoticz.js.gz and clear appcache and browser data was the solution for me. Switches are visible in the tabs, now

Thank you

**Comment by emontnemery** [comment]
@Mats80L Please try this one: http://montnemery.com/domoticz_trc02/153.1/e3bd9b56cf145cf85ed125bcfe58facaf039c007/domoticz_linux_x86_64.tgz
@Eisenhauer1987 OK, thanks for reporting. The file www/js/domoticz.js.gz is supposed to be automatically deleted by Domoticz itself..

**Comment by Mats80L** [comment]
That one works perfectly!
The colors are selected correctly and blue is now available

**Comment by Virtlink** [comment]
I had an issue where none of my switches appeared under the Switches tab. The solution was, after hours of trying and searching, to remove the file `www/js/domoticz.js.gz`. That fixed it.
