### ISSUE TITLE
Electric (Instant + Counter) Graph 10x too high 

### ISSUE THREAD

**Issue by CherAlban** [domoticz/domoticz#2292]
Hi,

When using the dummy device "Electric (Instant + Counter)" with json:

`http://192.168.0.1:8080/json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=200;0`

the dashboard shows the correct values (e.g. 200 Watt):

![image](https://user-images.githubusercontent.com/29152864/38368565-e7a43266-38e5-11e8-929d-b42847d50540.png)

but the log graphs show wrong values ~10x higher (e.g. 2000 Watt):

![image](https://user-images.githubusercontent.com/29152864/38369727-abd51a9a-38e8-11e8-9941-715f861f97b6.png)

**Comment by CherAlban** [comment]
I checked the SQLite data-types for "Meter", INTEGER is used for both Value and Usage entries. While the dashboard interprets "2005" as 200.5W, the log graph displays 2005W. I have  no idea which interpretation is the intended one and where to best fix this mismatch. Could somebody more experienced please give me a hint?

**Comment by gizmocuz** [comment]
you have to divide by 10

**Comment by CherAlban** [comment]
Hi Gizmocuz, you cannot simply devide by 10, as there is a mismatch of interpretation between what is displayed on the dashboard and what is shown in the logs, they are not consistent. If you check both pictures I inserted above, you will see that the same number in the database once gets interpreted as 200.0W and once as 2000W. I don't mind which interpretation you prefer, but they should be consistent.

**Comment by gizmocuz** [comment]
Okey, i will have to look into this.
It is just that i never heard about this issue, and the meter type is commonly used

**Comment by CherAlban** [comment]
If I can do anything to support you to resolve this issue, please just let me know.

**Comment by CherAlban** [comment]
Can you re-open the Issue?

**Comment by waltervl** [comment]
And close it again?

**Comment by gizmocuz** [comment]
Double checked and no issue here. Today counter is also kind of strange.

**Comment by CherAlban** [comment]
Sorry, for not keeping track with this issue, I can confirm it is working in current versions.
