### ISSUE TITLE
Error javascript V3.9202 at LightsController.js:762 

### ISSUE THREAD

**Issue by ayasystems** [domoticz/domoticz#2297]
Switch ON/OFF is not working with beta V3.9202

Uncaught ReferenceError: getLEDType is not defined
    at EditLightDevice (LightsController.js:762)
    at HTMLAnchorElement.onclick ((index):1)
EditLightDevice @ LightsController.js:762
onclick @ (index):1

The error is raised when you try to edit a switch item

I'm ussing an orange pi Zero. Domoticz was installed from script and then updated to beta to avoid lib ssl issues.

Regards!

**Comment by sweetpants** [comment]
I'm on the same version but do not experience this. Can you give a step-by-step procedure to reproduce this?

**Comment by ayasystems** [comment]
I have create a dummy switch (ONOFF) then i go to the LightSwitches tab, select it and the issue is here.... I can not change setting due a the javascript error.

I can create an user for you to test it if you need

**Comment by sweetpants** [comment]
I cannot reproduce this on a dummy switch, so it must be something locally. have you cleared browser and app cache? (two different things)

**Comment by ayasystems** [comment]
Yes, i did a cache clean and app cache and test it as private mode with chrome.
I did the test also with Explorer (never used before)

I

Regards

**Comment by ayasystems** [comment]
![image](https://user-images.githubusercontent.com/7864168/38417745-d3d6d158-3999-11e8-9ca5-c3cf2a82046b.png)

**Comment by sweetpants** [comment]
Could it be related to: https://github.com/domoticz/domoticz/issues/2282

**Comment by emontnemery** [comment]
- Please delete file www/js/domoticz.js.gz in Domoticz installation directory if present
  **Note: Do NOT delete www/js/domoticz.js**
- Clear the browser cache + appcache (those are two different things)

**Comment by ayasystems** [comment]
![image](https://user-images.githubusercontent.com/7864168/38420023-c75e4b32-39a2-11e8-96c0-f4bc619d78ff.png)


It is working now!! 
![image](https://user-images.githubusercontent.com/7864168/38420169-31d6b116-39a3-11e8-98db-2f1a9745223f.png)


Thanks

Do you need aditional information ??


Regards!
