### ISSUE TITLE
New url to notifymyandroid

### ISSUE THREAD

**Issue by dobber81** [domoticz/domoticz#2298]
Old link for sending notifications through notifymydroid is broken.

Old: https://www.notifymyandroid.com/publicapi/verify?apikey=YOUR-API-KEY

New: https://notifymyandroid.appspot.com/publicapi/verify?apikey=YOUR-API-KEY

Source: https://www.domoticz.com/forum/viewtopic.php?f=6&t=21124&hilit=notify

Someone needs to change the source code.

Using Domoticz 3.9201

**Comment by jvandenbroek** [comment]
https://www.domoticz.com/forum/viewtopic.php?f=6&t=21124&p=177167#p177167

**Comment by gizmocuz** [comment]
Where is this URL used ? (please show a reference to the code) as i don't think we use this

**Comment by dobber81** [comment]
I could be wrong, but I think its here: https://github.com/domoticz/domoticz/blob/development/notifications/NotificationNma.cpp

line 33

**Comment by gizmocuz** [comment]
On this line we use "https://www.notifymyandroid.com/publicapi/notify" which is the correct and latest API calling method.
We do not use the verify url...

**Comment by dobber81** [comment]
I just tried http://www.notifymyandroid.appspot.com/publicapi/notify and get a good response. 
When I use http://www.notifymyandroid.com/publicapi/notify I get the max messages sent message. Still their fault, but notifymyandroid.appspot.com is working while notifymyandroid.com is not.
I did get an error when trying with https. So maybe this is a lost cause.

**Comment by gizmocuz** [comment]
Have a look here:

https://notifymyandroid.appspot.com/api.jsp

where did you read that we need to use http://www.notifymyandroid.appspot.com/publicapi/notify ?

Are you a paid customer ? (if not, pay the few bugs)

**Comment by gizmocuz** [comment]
(You should also use https)

**Comment by dobber81** [comment]
Yeah I know. They don't seem to update anymore. I have moved on to pushover, but still kind of liked NMA. I just wanted a working solution. But perhaps removal of the nma support in domoticz is better. People buy the nma service, believing that it will work in domoticz. The only one to blame is the developer of NMA.

**Comment by gizmocuz** [comment]
Why should it be removed ? I like it very much! No need for any other system.
So you are a paid customer ?
Where did you read that the url is changed ?

We can change it... but verification would be nice

**Comment by dobber81** [comment]
I am a paid customer for nma and for the domoticz android app. All this worked great until a few months ago. After that only a few messages comes through, then we get the log saying too many messages.
The only place I found that link was in the domoticz forum. This thread: https://www.domoticz.com/forum/viewtopic.php?f=6&t=21124&hilit=notify
Since the nma crew are not maintaining their site anymore and dont answer to messages I start to feel it is a lost cause.

**Comment by dobber81** [comment]
My guess is that they did not intend for the api link to stop working and that they dont seem too interested in solving the issue. Just pure luck that someone found the appspot link that seem to be functional.

**Comment by gizmocuz** [comment]
Would be a bad case!
The new url seems to work correctly, i changed the code and it should be available in the upcoming beta release

https://github.com/domoticz/domoticz/commit/bb5d16cdfee3b49b16773e124395ba2f4b8b2de8

**Comment by dobber81** [comment]
Nice! I'll give it a go when the next beta is released. I sure hope they dont shut that link down if they ever decide to fix the original one :)

**Comment by jvandenbroek** [comment]
@gizmocuz see the topic on the forum posted above. Some user found that the appspot url works, but I also wanted an official statement before implementing anything other. So there are 2 options: remove it since it's no longer maintained, or change the URL (however wouldn't/shouldn't do that without consent imo) 

Edit: well seems it's already decided then ;)

**Comment by gizmocuz** [comment]
We would know soon enough....
Else we could use another platform like (https://signal.org/), or use Pushbullet

Beta should now be available

**Comment by dobber81** [comment]
I just tried it. Looks good. Sent about 20 notifications rapidly and they all came through. When I did that in previous versions maybe half of them worked. I sure hope you guys don't get in trouble for pushing to another server :) At least this mess gave me opportunity to try pushover. From now on I will use both services in case one is down.

**Comment by gizmocuz** [comment]
@jvandenbroek ,
Yes, i tested the url good, and also with the forum posts it seems to be working good.
Not removing a great notification system when not needed, and it was also one of the first systems, so i have a lot of respect for them.
If they stop, sure we need something else... maybe 'Signal' is an option

**Comment by Failure404** [comment]
Hi,
it seems NMA is now completely gone. App is not working anymore and the website says NMA will be shutdown May 24th due to fear of GDPR. see -> http://www.notifymyandroid.com/

**Comment by gizmocuz** [comment]
Whaaaa..... thats a shame ! I really liked it, and they where one of the first notification systems with prowl!

**Comment by gizmocuz** [comment]
I guess it needs to be removed before making a new stable
