### ISSUE TITLE
Milight Set White Mode

### ISSUE THREAD

**Issue by MrRodz** [domoticz/domoticz#2303]
Hi i have 

Version v3.9203
Platform: Rasbian
Hardware: Limitless/AppLamp/Mi Light with WiFi / SET MODE: V4/5 RGBW

Hi a few days ago i lost the ability to set my lights to white. All the colours work, but when trying to use the colour picker to get pick white i get red, blue or green.

previously there was a button "Set White" that worked great. I've tried to set in the colour picker and the brightness mode with no joy.

thanks in advance

**Comment by emontnemery** [comment]
@MrRodz Thanks for reporting.
White mode should be possible by using black/white mode of color picker.

Can you confirm you see this print in the log when trying to set a white color:
`AppLamp: SetRGBColour - Color mode 1 is unhandled, if you have a suggestion for what it should do, please post on the Domoticz forum`

If you do, I'll prepare a debug build which hopefully corrects this issue, please let me know which build you need:
- Linux for Raspberry Pi
- Linux for x86-64
- Windows

**Comment by emontnemery** [comment]
Raspberry Pi test build: http://montnemery.com/domoticz_hue/linux_armv7l/006/domoticz_linux_armv7l.tgz
@odelma Please test if you have time
@MrRodz Please let me know if you need binary for other system:
- Linux for x86-64
- Windows

**Comment by odelma** [comment]
@emontnemery Thanks! Should have some time to test tomorrow evening if no one beats me to it...:smile:

**Comment by MrRodz** [comment]
@emontnemery Thanks, i can now set the lights too white on the black and white scale from the switches page. However when i go into edit the switch it is now shown as a blinds. 

i do not require any other builds thanks.

![domoticz 3](https://user-images.githubusercontent.com/38086707/38473516-1ae70d60-3b89-11e8-8bfe-d7d2256ff6aa.png)
![domoticz 2](https://user-images.githubusercontent.com/38086707/38473517-1afe7b3a-3b89-11e8-93b7-2110cab72c70.png)

**Comment by emontnemery** [comment]
@MrRodz #2305 is merged in latest beta, can this be closed now?

**Comment by emontnemery** [comment]
@gizmocuz Please close this issue, it is fixed by #2305

**Comment by gizmocuz** [comment]
@emontnemery ,Thanks!
