### ISSUE TITLE
MiLight and timers+brightness

### ISSUE THREAD

**Issue by Tontze** [domoticz/domoticz#2307]
Not a bug, but improvement for setting timers and brightness level.

Since there is no more field where to write brightness level percentage, you need to try many times with slider to find percentage you want to use.  Please bring the field back :)

**Comment by Tontze** [comment]
For clarification, you need to slide slider to some point, then accept it, and then you see what % position  slider was. If its not the one you want, you need to edit it and move slider a bit to find correct % ... 

Not very handy do you think ?

**Comment by emontnemery** [comment]
No, not very handy at all and I agree UI should be same for both normal dimmers and color dimmers.
@stas-demydiuk, I think I broke this when doing the RGBW stuff. Should I fix it, or are you working on the edit/timer/scenes stuff?

Also, I don't think it's handy to have a drop-down where you have to scroll to choose 0..100, but not sure how to make the UI both easy/quick to use and allow exact setting.

**Comment by stas-demydiuk** [comment]
@emontnemery currently I'm not working on the edit/timer/scenes stuff, so feel free to update it if required

**Comment by Tontze** [comment]
Perhaps you could use slider, but show percentage when sliding ?

**Comment by Tontze** [comment]
Will this be improved ? I was about to do outdoor lightning that lights up bit by bit during sunset.. But its impossible with timers now ..

**Comment by emontnemery** [comment]
Yeah, I'll try to get it fixed this weekend. Sorry about the delay!
It would be great if you could help testing, are you running Domoticz on Raspberry Pi?

Please have a look in #2810, and let me know if I understood your request correctly.

**Comment by Tontze** [comment]
Yup i can help, if instructed carefully :D

**Comment by waltervl** [comment]
Fixed, can be closed
