### ISSUE TITLE
Device dependant issues (content not loaded) with Web UI

### ISSUE THREAD

**Issue by odelma** [domoticz/domoticz#2311]
https://www.domoticz.com/forum/viewtopic.php?f=6&t=23013
https://www.domoticz.com/forum/viewtopic.php?f=6&t=23024

There is pretty good description of the issue already on the above forum threads. I'll copy it partly here:

> Version: 3.9203
Platform: Raspberry Pi3B / Raspbian Stretch
Plugin/Hardware: Z-wave, RFLink, HarmonyHub etc.
Description: Domoticz web interface does not open with browsers (Safari, Chrome) on iPad2 / iOS 9.3.4 after update to latest beta.

Web interface works well on Chrome & Safari on my Macbook and also with iPhones running iOS 11. However, after updating to latest beta (from a beta published about three weeks ago) I no longer cannot open the web interface (well, I can open the page, it loads, but items are more or less missing on each tab, e.g. on the Dashboard only an empty drop-down menu for "add new device" is shown right below the navbar) on iPad2 running iOS 9.3.4. The iPad is being used as a wall-mounted control dashboard.

Needless to say, I've cleared all offline content as well as I can on the iPad, tried with incognito mode etc. but behaviour is consistent. I hooked up the iPad to the Macbook to enable the Web Inspector and can see several errors on the console. However, I'm pretty clueless on what exactly is causing them as nothing like this is shown on e.g. Chrome on the Macbook. I've also tried with multiple themes but seems there is no effect, errors are still consistent.
![image](https://user-images.githubusercontent.com/10372952/38645619-61f80d42-3ded-11e8-81cd-22eb0f285d41.png)
![image](https://user-images.githubusercontent.com/10372952/38645629-6ac73010-3ded-11e8-928e-297f7f2d1866.png)

Any pointers on how to get my old iPad2 back on track displaying Domoticz would be appreciated. And yes, could always go for a custom dashboard but I quite like the standard interface and it has been serving me well thus far. Wouldn't like to give up yet :)

@stas-demydiuk - I did not find you on the forum and therefore decided to open the issue here. I noted you've recently made some improvements (much appreciated! 😃) to the web UI. Could there be any relation to these issues experienced with the web UI? And as you seem to know your way around the UI stuff very well, maybe you could take a look even if there isn't any relation...

**Comment by emontnemery** [comment]
Edit: @odelma, I should have read the description more carefully, sorry about that!

**Comment by odelma** [comment]
Thanks, I tried to be clear above that at least for me, no measure I’ve been able to take (incl. clearing all cached / offline content, cookies, using incognito mode, installing new browsers) has had an effect on the outcome on this particular device (iPad2). Console shows the same errors consistently.

Other devices work and therefore I’m very puzzled what is causing this.

**Comment by stas-demydiuk** [comment]
@odelma if problem is only on iPad with iOS 9.3.4, then issue could be that this version of mobile safari doesn't support "let" and "const" JavaScript features that are used in new color picker. 

If you have access to domoticz sources on your machine try to replace any `let` definitions to just `var` in all .js files and check if it helps

**Comment by anttiodelma** [comment]
@stas-demydiuk thanks, will test later this evening
@emontnemery no problem, your suggestion works in 99% user interface problems :smiley: In fact, not knowing how iOS 9.3.4. stores cache (is it even possible to remove everything, does other browsers use Safari as the engine to perform certain things etc.) I guess it is possible it is behind this issue as well. Might have to try reinstalling iOS altogether....

**Comment by emontnemery** [comment]
@anttiodelma Can you check the Safari version on your iPad? Not being an iPad owner myself, is Safari locked at some ancient version since the iPad 2 is no longer updated?

Edit: I opened #2313 for this, @anttiodelma let me know if you need a build prepared for testing.

**Comment by odelma** [comment]
@emontnemery I can check the exact version if needed. But changing "let" to "var" did the trick 👍 

I ran:
`sudo grep -rl '/home/pi/domoticz/www/js/' -e "let" | sudo xargs sed -i 's/let /var /g'`

And it is working again... Thank you for the patch as well, I take it does not effect the actual functionality? 😄

**Comment by emontnemery** [comment]
Never mind about the version then, and great that it works now!

There's a hidden "let" waiting for you in the compressed www/js/jquery.wheelcolorpicker.js.gz, you might want to fix that one as well if you own any RGB light :)
You also need to replace a couple of "const" with "var" in www/app/DeviceTimers.js

Very brave way to modify the code by the way 😄

**Comment by odelma** [comment]
@emontnemery thanks for the tips, maybe on my wall tablet these won't be an issue, I rarely change the RGB lights from there or access timers. So I can wait for #2313 to take care of those, thanks again for that! 

Well, I first checked what would change. Would've been quite brave indeed to replace everything blindly 😁 

edit: guess I can close this now?

**Comment by emontnemery** [comment]
@odelma It would be great if you could verify the issue is indeed fixed in latest beta, which includes #2313, then close

**Comment by odelma** [comment]
@emontnemery - seems to be working very well again, thanks a lot! 😄
