### ISSUE TITLE
Hue:  add options to not import groups and scenes

### ISSUE THREAD

**Issue by jonferreira** [domoticz/domoticz#2314]
as per #2281 would be great to have options to not import hue groups / scenes available

**Comment by emontnemery** [comment]
@jonferreira Please test this build: http://montnemery.com/domoticz_hue/linux_armv7l/012/domoticz_linux_armv7l.tgz

**Comment by jonferreira** [comment]
Thanks @emontnemery 

Add Groups seem to be working as expected but the Add Scenes doesn't seem to do anything, i.e. regardless if it's checked or not Scenes always get added

**Comment by emontnemery** [comment]
OK, sorry about that.
Please test this build: http://montnemery.com/domoticz_hue/linux_armv7l/013/domoticz_linux_armv7l.tgz

**Comment by jonferreira** [comment]
Looks fine now, awesome!!

**Comment by jonferreira** [comment]
@emontnemery believe this was new publised to Beta so can be closed?

**Comment by emontnemery** [comment]
@jonferreira Yes, please close the ticket.

**Comment by jonferreira** [comment]
t
