### ISSUE TITLE
Problem with web interface (hidden elements)

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#2319]
RPI v 3.9222
Top bar covers other elements
![error](https://user-images.githubusercontent.com/10205661/38767939-9d8309b6-3feb-11e8-8d8c-0ab71638d0c1.png)

**Comment by Tontze** [comment]
I can confirm this too.

**Comment by sweetpants** [comment]
Which Theme and how to re-produce? I'm on the same version but don't see this

**Comment by szczukot** [comment]
I use simple-blue
A few weeks ago all worked properly

**Comment by gizmocuz** [comment]
Use the default theme for now

**Comment by szczukot** [comment]
Why is it closed ?
Problem not solved.

**Comment by gizmocuz** [comment]
it is solved by using the default theme, which everyone should use in the current beta (upcoming release) until we have some changes.
Custom themes can update their css file to correct the position of the top items
