### ISSUE TITLE
Kodi plugin does not work if using DNS-name in IP-address-field

### ISSUE THREAD

**Issue by ralin3** [domoticz/domoticz#232]
So yeah, it's kinda obvious that I should use the IP-address in the "IP-Address"-field, but then again - why depend on IP's when DNS is a thing?

The extension always errors out in an "Invalid Argument" when using DNS-name, even though there is nothing wrong with the DNS-alias.
When switching to IP it works instantly.

So I guess this is an issue for making the field only accept IP's (which would have made me catch the error earlier) or making the extension work with DNS or IP, and changing the name of the field.

**Comment by dnpwwo** [comment]
Added DNS resolution in today's commit.  

Never really thought about it because my Kodis all have static IPs.

Close this if it now works for you.

**Comment by ralin3** [comment]
Confirmed to work, but maybe change the name of the field now? It still says "IP Address".
OT: I also have static IP's, but a DNS-alias is preferred anyway.
Easier for other residents to remember "KodiKitchen" than 192.168.123.234 - not to mention IPv6.

**Comment by gizmocuz** [comment]
its also faster to use a direct ip address

**Comment by ralin3** [comment]
It shouldnt be noticeable for a human with a local DNS-resolv.

**Comment by ralin3** [comment]
Hi,
I didn't close this issue because the text before the field still says: "IP Address" - and now you can use both IP and DNS.

**Comment by gizmocuz** [comment]
that is because we want users to enter an IP ADDRESS

**Comment by ralin3** [comment]
But why? Wouldnt that be counterproductive when Domoticz needs to
support ipv6?

On Wed, Dec 2, 2015, at 18:43, gizmocuz wrote:

> that is because we want users to enter an IP ADDRESS
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/domoticz/domoticz/issues/232#issuecomment-161394149

**Comment by gizmocuz** [comment]
In house there will be no need for IPV6, there is more hardware that does not support it
and an IPV6 ip address is also an ip address

**Comment by kylegordon** [comment]
I disagree, IPv6 is becoming commonplace with the advent of 6LowPAN networks (ie, lightbulbs, sensors, etc). It's one of the major competitors to Zigbee and Z-Wave. LIFX and Cisco are backing 6LowPAN.

In addition, manufacturers encourage the use of RFC6762 encourages the use of multicast DNS to resolve devices on the network, such as Netgear using router.local, Microsoft and Apple using it to resolve local devices, Epson printers, and others that I can't recall right now.

We look back at those that said "there will be no need for IPV6" and realise they were wrong. Not everyone will have their own BIND9 DNS servers, but their networks will have mDNS in the house, or an equivalent.

**Comment by gizmocuz** [comment]
I was talking about in house, they're is totally no need for ipv6 in a private network

**Comment by kylegordon** [comment]
The very premise of IPv6 is the removal of NAT (and the 'private' RFC1918 addresses that you're relying on), and the issuance of public IPs to every user. The current IETF best practice recommendation is to issue anything between a /48 to to /64 to all end sites.

I'm not suggesting it needs to be implemented right now, but I do think it's very unwise to discount IPv6 in the home, and not consider supporting it at all.

**Comment by ralin3** [comment]
It's not very wise to disregard the use of DNS at home either, just
because you don't use it doesn't mean others don't.

On Sun, Dec 27, 2015, at 18:22, Kyle Gordon wrote:

> The very premise of IPv6 is the removal of NAT (and the 'private'
> RFC1918 addresses that you're relying on), and the issuance of public
> IPs to every user. The current IETF best practice recommendation is to
> issue anything between a /48 to to /64 to all end sites.
> 
> I'm not suggesting it needs to be implemented right now, but I do
> think it's very unwise to discount IPv6 in the home, and not consider
> supporting it at all.
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/domoticz/domoticz/issues/232#issuecomment-167432489
