### ISSUE TITLE
Doorswitch icon wrong in Floorplan

### ISSUE THREAD

**Issue by devennekes** [domoticz/domoticz#2320]
In Floorplan door open icon is shown when door is closed. Installed: bèta 3.9222.

**Comment by sweetpants** [comment]
What contact type are you using?

**Comment by devennekes** [comment]
I'm using Klik aan Klik uit AMST-606-sensors. Until a few weeks ago everything worked fine. Notation of the door switch in the dashboard is OK.

**Comment by JezzaGas** [comment]
I have the same issue with switch type 'door contact'. 3.9224 on RPi. I'm using a mix of Fibaro and Lightwave MCS. The doors are showing as always open on the floor plan but have the correct state in the switches tab. This has been an issue for the last couple of weeks.

**Comment by sweetpants** [comment]
Hmm, i'm on latest beta too and have several door-contact's. All show the same status on floorplan and switches tab. Must be something locally or RPi only. Have you cleared the app cache and and browser cache (two seperate things) already?

**Comment by devennekes** [comment]
Yes, I cleared both caches, but unfortunately it didn't solve the problem.

**Comment by JezzaGas** [comment]
I have cleared all the caches and it hasn't made any difference. This is happening across all my browsers / devices. It is only an issue if the switch type is 'door contact' and it is only a problem in the floor plan tab. The 'door contact' icons are displayed correctly on the dashboard and the switches tabs. If I change all of my MCSs back to type 'contact' rather than 'door contact' then they display correctly.

**Comment by sweetpants** [comment]
Ok, now i see. I use type 'contact', this one is ok in floorplan. Seems ther is no icon for a closed door. There is on for a locked door only. 
![door48](https://user-images.githubusercontent.com/23421160/38820699-dd30712a-419e-11e8-927e-d34b9b227b7a.png)
![door48open](https://user-images.githubusercontent.com/23421160/38820704-e3564dd6-419e-11e8-852e-467efb3336eb.png)

I think you should use type 'contact' instead.

**Comment by JezzaGas** [comment]
I am now using the 'contact' type. The odd thing is that until a couple of weeks ago I was using the 'door contact' type and it was displaying correctly in the floor plan.

**Comment by sweetpants** [comment]
There where some changes about 5 months ago in this area (Commit f2e978b608721b7f80643d1cbdd46a929dcf39f7) but as far as i know there has never been a door-closed icon

**Comment by quack3d** [comment]
Inspect on closed Door contact in Floorplan says /images/door48open.png whereas inspect on closed Door contact under Switches says images/door48.png.

Previously also Floorplan showed door48.png when Door contact was closed. I have a sensor on my lockbolt so Door contact was perfect for me. Now it looks like my door is unlocked all the time.

**Comment by Wob76** [comment]
Is there a fix for this? Just updated to 3.9462 from 3.8932 and now all doors appear open on the floorplan, details show the door is closed, but as mentioned by sepodele it is pointing to door48open.png, previous behaviour was showing to door48.png

**Comment by gizmocuz** [comment]
@Wob76 , then it is probably not fixed ...
So... are we talking about a "door contact" or a "door lock" ? we do not have a "door switch"

**Comment by gizmocuz** [comment]
Seems you are talking about the 'door contact"...

**Comment by Wob76** [comment]
Hi, I am talking door contact, I don't have any smart locks.

Edit: I thought there might have been a manual fix, such as renaming door48.png to door48closed.png, but it does appear that the floorplan is referring to door48open.png regardless of the contacts state.

**Comment by sweetpants** [comment]
For 'door contact' there is only one icon (the one with the green arrow), see a few posts back. This is showed on the floorplan always, dispite the state. That is why I use 'contact', this has two icons (grey/red)

**Comment by gizmocuz** [comment]
There are two icons, as you can see in the 'switches' overview.
It should be fixed now in beta 9471, it was so easy, i almost did not want to do this and leave it as a practice for you @Wob76 ;)

**Comment by Wob76** [comment]
haha, thanks, but I'll stick to playing in my scripts :)

**Comment by gizmocuz** [comment]
Is it working correctly ?

**Comment by sweetpants** [comment]
Hmm, i'm confused now. When selecting 'door contact' it looks ok in floorplan now
![image](https://user-images.githubusercontent.com/23421160/40414730-56db1f38-5e79-11e8-965b-db84a0bdffc1.png)
(can't test, my arms are not long (90km) enough) 
![image](https://user-images.githubusercontent.com/23421160/40414572-dee310d0-5e78-11e8-8fe5-bd9d4a566a57.png)
But when hoovering over the icon it says 'Open Deur' which suggests you can open (unlock??) this door but you can't. Using type 'contact' and hoovering over the icon shows nothing, which is correct.

**Comment by gizmocuz** [comment]
Yes, i noticed this also... but that was not the problem reported here

**Comment by gizmocuz** [comment]
Also that would be easy to solve

**Comment by gizmocuz** [comment]
Fixed in commit https://github.com/domoticz/domoticz/commit/ff9904e981d7f2722b36eb0a4420608c738595dd

Beta is building, could take an hour
