### ISSUE TITLE
Re: display problem: Update textdevice with string> 240 chars

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#2321]
Version: V3.9227 (and a couple of earlier versions)
Platform: RPI3 Debian Stretch
Plugin/Hardware: 

When I update a text device with a string with a length > 240 chars, it is updated in the database with the full length string but I don't see the device back in the device tab or in the utility tab. I is completely gone from those views.
If I cutoff the string to max. 240 chars and update the device it magically comes back to those tabs.

changing user interface themes / clearing cache / clearing appcache does not change this behaviour.
to be sure I also tested with updating the text device with a string of > 255 chars in sqlite3 and checked if it was really there

[code]sqlite> update DeviceStatus set sValue = "A123456789B123456789C123456789D123456789E123456789F0123456789G0123456789H123456789I123456789J123456789K123456789L123456789M123456789N123456789O123456789P123456789Q123456789R123456789S123456789T123456789U123456789V123456789W123456789X123456789Y123456789Z123456789" where ID = 770;
sqlite>
sqlite> select * from DeviceStatus where ID=770;
ID|HardwareID|DeviceID|Unit|Name|Used|Type|SubType|SwitchType|Favorite|SignalLevel|BatteryLevel|nValue|sValue|LastUpdate|Order|AddjValue|AddjMulti|AddjValue2|AddjMulti2|StrParam1|StrParam2|LastLevel|Protected|CustomImage|Description|Options|Color
770|35|00082770|1|Weather forecast (dz) (long)|1|243|19|0|0|12|255|0|A123456789B123456789C123456789D123456789E123456789F0123456789G0123456789H123456789I123456789J123456789K123456789L123456789M123456789N123456789O123456789P123456789Q123456789R123456789S123456789T123456789U123456789V123456789W123456789X123456789Y123456789Z123456789|2018-04-15 18:00:09|10|0.0|1.0|0.0|1.0|||0|0|0|||
[/code]

After this update, device 770 disappeared from both my device tab and my utility tab.
When I shortened my string to 240 chars and updated device 770 in DeviceStatus with that, the device magically re-appeared on those tabs.

**Comment by gizmocuz** [comment]
In the database, the 'svalue' is 200 characters long, we should at least clip to 200 in the code

**Comment by rwaaren** [comment]
@gizmocuz , thanks for your reaction.
for me the issue is not about a clip in the code. My issue is that the device is no longer shown at all on the device tab and utility tab when the string is longer than 240 chars. That is why I now clip the length of the text to 240 in my (dzVents) code to ensure the device is visible on the tabs.

I also see this statement on the sqlite..org
" in sqlite numeric arguments in parentheses that following the type name (ex: "VARCHAR(255)") are ignored."

https://www.sqlite.org/datatype3.html   (3.1.1. Affinity Name Examples)

**Comment by gizmocuz** [comment]
@rwaaren , i understand, this was a note to myself to make sure to clip it in the upcoming release
But i just found the issue, there is an internal check if the svalue length is smaller then a buffer that is needed to create the json output, and it's not...
I will make a code patch so it will return 'invalid sValue size (to large!!)'

**Comment by gizmocuz** [comment]
I guess sqlite will clip/truncate the data, so there is no need for a patch for this
Fixed in next beta, closing issue
