### ISSUE TITLE
Issue with selector switchs

### ISSUE THREAD

**Issue by gysmo38** [domoticz/domoticz#2324]
It look like with selector button there is no more display for levels and actions.
![image](https://user-images.githubusercontent.com/988934/38867059-2bbf3b38-4243-11e8-8576-596293e400c4.png)

**Comment by sweetpants** [comment]
Version? Platform? Compiled from source or binary?
Web Cache/App Cache cleared?
I'm on latest Beta, no problem there

**Comment by gysmo38** [comment]
Sorry it work in private tab...
