### ISSUE TITLE
URL encode in action

### ISSUE THREAD

**Issue by gysmo38** [domoticz/domoticz#2325]
If I try to put a json command in action there is problem with the url.
For example
http://domo:8080/json.htm?type=command&param=switchlight&idx=1463&switchcmd=Toggle
become
http://domo:8080/json.htm?type=command¶m=switchlight&idx=1463&switchcmd=Toggle
Is there a trick to get it work?
Version: V3.9268 Platform: RPI Binary

**Comment by dannybloe** [comment]
What you see is very likely just the rendering of the log entry in the browser. Check the real Domoticz logs.

**Comment by sweetpants** [comment]
That's weird, If I put your command as On action on my switch, it stays the same, and it works
![image](https://user-images.githubusercontent.com/23421160/38870020-d70f1450-424c-11e8-8c87-7930a3e394b4.png)
Workaround is to call your actin from a bash script using curl, but it should work

**Comment by gysmo38** [comment]
Hello,
I check on log and it send the wrong URL.
You are right, the issue is only on selector switch not normal switch.
To get it work, I change the order of parameters.
Instead of using this:
http://domo:8080/json.htm?type=command&param=switchlight&idx=1463&switchcmd=Toggle
I use this
http://domo:8080/json.htm?param=switchlight&type=command&idx=1463&switchcmd=Toggle

It look like &para is encoded :(

**Comment by gordonb3** [comment]
How do you issue that request? Because I just created a virtual selector switch and I cannot replicate the problem.

**Comment by dannybloe** [comment]
Did you check the log from the command line (by starting ./domoticz)? Do you still see the wrong url then?

**Comment by gizmocuz** [comment]
This is probably solved by the latest changes to the selector switch ?

**Comment by gizmocuz** [comment]
As there is no feedback from @gysmo38 after almost two months, 3 people here with no problem, i am going to assume there is no problem.
Feel free to re-open this issue if there still is a problem
