### ISSUE TITLE
Import random module crash Domoticz on Raspbian Stretch

### ISSUE THREAD

**Issue by guillaumezin** [domoticz/domoticz#2326]
Hello

On RPI3, Raspbian Stretch, Python 3.5.3, Domoticz version 3.9227, Domoticz crash when a plugin using the random module is loaded (I needed randint function).

To reproduce, I copy Baseplugin.py as plugins/test/plugin.py, I chmod +x plugins/test/plugin.py and I add "import random" after "import Domoticz". I enable the plugin, and Domoticz crash, until I remove "import random".

`Thread 3 "domoticz" received signal SIGSEGV, Segmentation fault.`
`[Switching to Thread 0x7561d430 (LWP 32230)]`
`__GI_strcmp (p1=<optimized out>, p2=<optimized out>) at strcmp.c:38`
`38      strcmp.c: Aucun fichier ou dossier de ce type.`
`(gdb) bt`
`#0  __GI_strcmp (p1=<optimized out>, p2=<optimized out>) at strcmp.c:38`
`#1  0x0069fbf0 in getrn ()`
`#2  0x0069fe18 in lh_insert ()`
`#3  0x00685c0c in OBJ_NAME_add ()`
`#4  0x006a5ef4 in EVP_add_digest ()`
`#5  0x6aff2e5c in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1`
`Backtrace stopped: previous frame identical to this frame (corrupt stack?)`

I cannot reproduce the problem on Ubuntu 17.10, it seems specific to RPI3 or Raspbian Stretch, and may be related to the fact that Domoticz is compiled against libssl1.0 and python3 against libssl1.1 (see the reference to libcrypto.so.1.1 in the backtrace, which is inside libssl1.1 package)

**Comment by 999LV** [comment]
@guillaumezin , I had not had an opportunity to use the random module in python plugins, but this looks very similar to what happens when importing the request module on same platform and the pre-build binaries. My fix for this is to compile domoticz with dynamic linking of openssl pending an update of the way the default binaries are built (I think Gizmocuz was concerned about that, but cannot remember why).

**Comment by edog1973** [comment]
I've run into this same issue running on a Pi.   To exasperate the issue, the "default" python script under the Events tab has an "import random" line.  Creating a new python script, enabling and saving crashes the entire system.  Worse yet it immediately crashes again on restart.  

I'd recommend removing the "import random" line from the default script, it does not seem to be serving any purpose.  At least until this issues is resolved.

**Comment by Dams-38** [comment]
Got same issue with Zigate plugin that crash on line "import random" but i'm on Cubieboard and not Raspberry.

**Comment by waltervl** [comment]
Stale, can be closed
