### ISSUE TITLE
Synology cross compile error Tado.

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#2328]
Synology cross compile error.

[ 72%] Building CXX object CMakeFiles/domoticz.dir/hardware/Tado.cpp.o
In file included from /home/dahl/spksrc-master/toolchains/syno-x86-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/include/c++/4.9.3/regex:35:0,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:25:
/home/dahl/spksrc-master/toolchains/syno-x86-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/include/c++/4.9.3/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
#error This file requires compiler and library support for the
^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp: In member function ‘bool CTado::MatchValueFromJSKey(std::string, std::string, std::string&)’:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:578:2: error: ‘match_results’ is not a member of ‘std’
std::match_resultsstd::string::const_iterator _Matches;
^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:578:2: note: suggested alternative:
In file included from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio/read_until.hpp:26:0,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio.hpp:91,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/../tcpserver/TCPClient.h:3,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/../tcpserver/TCPServer.h:4,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/mainworker.h:11,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:21:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio/detail/regex_fwd.hpp:29:7: note: ‘boost::match_results’
class match_results;
^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:578:48: error: expected primary-expression before ‘>’ token
std::match_resultsstd::string::const_iterator _Matches;
^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:578:50: error: ‘_Matches’ was not declared in this scope
std::match_resultsstd::string::const_iterator _Matches;
^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:581:2: error: ‘regex’ is not a member of ‘std’
std::regex _reSearch(sKeyName + ": '(.*?)'");
^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:581:2: note: suggested alternative:
In file included from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/regex_fwd.hpp:27:0,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio/detail/regex_fwd.hpp:20,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio/read_until.hpp:26,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio.hpp:91,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/../tcpserver/TCPClient.h:3,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/../tcpserver/TCPServer.h:4,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/mainworker.h:11,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:21:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/regex/v4/regex_fwd.hpp:60:48: note: ‘boost::regex’
typedef basic_regex<char, regex_traits > regex;
^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:582:7: error: ‘regex_search’ is not a member of ‘std’
if (!std::regex_search(sJavascriptData, _Matches, _reSearch)) {
^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:582:52: error: ‘_reSearch’ was not declared in this scope
if (!std::regex_search(sJavascriptData, _Matches, _reSearch)) {
^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp: In member function ‘bool CTado::GetTadoApiEnvironment(std::string)’:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:607:2: error: ‘match_results’ is not a member of ‘std’
std::match_resultsstd::string::const_iterator _Matches;
^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:607:2: note: suggested alternative:
In file included from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio/read_until.hpp:26:0,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio.hpp:91,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/../tcpserver/TCPClient.h:3,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/../tcpserver/TCPServer.h:4,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/mainworker.h:11,
from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:21:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio/detail/regex_fwd.hpp:29:7: note: ‘boost::match_results’
class match_results;
^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:607:48: error: expected primary-expression before ‘>’ token
std::match_resultsstd::string::const_iterator _Matches;
^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:607:50: error: ‘_Matches’ was not declared in this scope
std::match_resultsstd::string::const_iterator _Matches;
^
make[5]: *** [CMakeFiles/domoticz.dir/hardware/Tado.cpp.o] Error 1
make[5]: Leaving directory /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268' make[4]: *** [CMakeFiles/domoticz.dir/all] Error 2 make[4]: Leaving directory/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268'
make[3]: *** [all] Error 2
make[3]: Leaving directory /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268' make[2]: *** [compile_target] Error 2 make[2]: Leaving directory/home/dahl/spksrc-master/cross/domoticz'
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz'
make: [arch-x86] Error 2 (ignored)

**Comment by sweetpants** [comment]
Looks like https://www.domoticz.com/forum/viewtopic.php?f=47&t=23119, compiler version too old?
