### ISSUE TITLE
Json command setcolbrighnessvalue not working properly

### ISSUE THREAD

**Issue by Janco59** [domoticz/domoticz#2332]
The json command .../json.htm?type=command&param=**setcolbrightnessvalue**&idx=418&hue=0&**brightness=0**&iswhite=false doesn't reduce brightness to zero but to an unknown low value. If a high(er) value is selected, it works properly.

Irrespective off the value, the command is always confirmed with:
{
   "status" : "OK",
   "title" : "SetColBrightnessValue"
}

This applies to Domoticz v3.9268 and maybe some earlier builds. Before it used to work as expected.

**Comment by emontnemery** [comment]
@Janco59 This is same as https://www.domoticz.com/forum/viewtopic.php?f=6&t=23081&p=178130#p178130, and you see it on Philips Hue lights?

**Comment by Janco59** [comment]
Yes, one of the people commenting on that thread suggested to open a thread here.
It's indeed on Philips Hue (old model Hub with Hue Bloom light, haven't tested it on other hardware).

**Comment by emontnemery** [comment]
@Janco59 : I've made a potential correction and it would be great if you could verify it. Do you build Domoticz yourself, or should I prepare a test build and if so for which OS (Windows PC, MacOS, Linux x86, Linux Raspberry Pi)?

**Comment by Janco59** [comment]
@emontnemery: Never built it myself. It would probably mean a lot of work for me. If you would be able to make a test build for Raspberry, I would be happy to test it.

**Comment by emontnemery** [comment]
~~OK, please test this build:~~
~~http://montnemery.com/domoticz_hue/linux_armv7l/012/domoticz_linux_armv7l.tgz~~
Edit:
Updated build, please try this instead:
http://montnemery.com/domoticz_hue/linux_armv7l/013/domoticz_linux_armv7l.tgz

**Comment by Janco59** [comment]
Downloaded the build. Is there an easy way to update? I haven't done this before. Just installed the system from scratch a long time ago.

**Comment by emontnemery** [comment]
@Janco59 
OK, since this is an unofficial build for testing, I'd recommend to first do a full backup (assuming domoticz is installed in /home/pi/domoticz:
```
cd /home/pi
sudo systemctl stop domoticz
tar -zcf domoticz_full_backup.tgz domoticz
```
Now, transfer the newly created `domoticz_full_backup.tgz` to your PC (for example) and double and triple check that `domoticz_full_backup.tgz` can be opened (for windows, use 7-zip for example) and that it includes the entire domoticz installation (domoticz.db, all your scripts you may have created, etc)

Then download and extract the test build on top of your domoticz installation, and restart domoticz:
```
cd /home/pi/domoticz
wget http://montnemery.com/domoticz_hue/linux_armv7l/013/domoticz_linux_armv7l.tgz
tar -xzf domoticz_linux_armv7l.tgz
sudo systemctl start domoticz
```

Now do the testing of the hopefully fixed Philips Hue issue.

To revert back to your old installation:
```
cd /home/pi
sudo systemctl stop domoticz
rm -R domoticz
tar -xzf domoticz_full_backup.tgz
sudo systemctl start domoticz
```

**Comment by Janco59** [comment]
**@emontnemery**
The first test seem to be positive: zero brightness really switches off the light and different brightness values do indeed change the light intensity of both Hue lights I tried. Will test more extensively tomorrow.

**Comment by Janco59** [comment]
**@emontnemery**
Sorry, can't test anymore. With your build the Hue subsystem worked, but my Z-Wave stick was not recognised anymore. On top of that, the VNC server, although running, was not able to show any image anymore and even on a real monitor, after rebooting, just a blinking cursor, no graphical or other interface anymore. I rebuilt the system and reinstalled the full backup without problems. Unfortunately domoticz crashes after a few minutes and half of my devices is not even recognized any more. Will probably have to build everything from the ground up which will take a lot of time. 
Grrr, not the first time that backups (how useful are they anyway) don't work as expected.

**Comment by emontnemery** [comment]
@Janco59 I'm really sorry to hear that!

As long as you hold on to your backup (and the backup copy of domoticz.db is good) you should be able to go back to a working state: (Re)install domoticz, and then restore domoticz.db from the backup, as well as custom scripts etc from the backup.

**Comment by emontnemery** [comment]
@Janco59, @gizmocuz Please close this ticket
