### ISSUE TITLE
Spaces are converted to %20 in selector switches

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#2339]
In recent betas it was possible to add for example a Selector Switch with the name "Apple TV". In the latest Beta versions the name changes to "Apple%20TV".

- when you edit one of the levelnames of an existing device all spaces in all level names are converted to %20 
- when you add a new selector switch, all spaces in all level names are converted to %20

Scripts based on these levelnames do not interpret the %20 to be the same as a space so this changed behaviour influences the system more than only at a display level.

http://www.domoticz.com/forum/viewtopic.php?f=6&t=23158&p=178576#p178576

**Comment by gizmocuz** [comment]
Thanks for reporting, solved in upcoming version

**Comment by rwaaren** [comment]
I checked in  V3.9300 but now the levels and names can no longer be edited using the edit button on the device in the switches tab.
This is also true when adding a new selector switch.


![knipsel2](https://user-images.githubusercontent.com/24454798/39109737-6f3dbabc-46ce-11e8-9d31-39ea5c65275d.PNG)

.![knipsel](https://user-images.githubusercontent.com/24454798/39109668-1f3c7f9e-46ce-11e8-9697-d3100284fee8.PNG)
