### ISSUE TITLE
Selector switch levels and levelnames cannot be edited. (was: Spaces are converted to %20 in selector switches  #2339) 

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#2341]
Ref: #2339 

I checked in  V3.9300 but now the levels and names can no longer be edited using the edit button on the device in the switches tab.
This is also true when adding a new selector switch.

![knipsel2](https://user-images.githubusercontent.com/24454798/39109737-6f3dbabc-46ce-11e8-9d31-39ea5c65275d.PNG)

.![knipsel](https://user-images.githubusercontent.com/24454798/39109668-1f3c7f9e-46ce-11e8-9697-d3100284fee8.PNG)

**Comment by stas-demydiuk** [comment]
@rwaaren could you please share your browser console log when you open device edit page?

**Comment by rwaaren** [comment]
@stas-demydiuk,

seems to be something local. On my laptop I saw this behaviour even after clearing all browser caches but on my desktop it is OK. After a complete restart of my laptop edit page is working there OK as well.
 Sorry for the confusion caused.
