### ISSUE TITLE
Can not switch with this DeviceID, use a switch created with our id_base!

### ISSUE THREAD

**Issue by Eisenhauer1987** [domoticz/domoticz#2344]
Hi I have this error:

"Can not switch with this DeviceID, use a switch created with our id_base!"

with my Enocean FSB61NP-230V. I have no documentation found about this error. DomoticzVersion: Latest Beta

Forum Thread: https://www.domoticz.com/forum/viewtopic.php?f=56&t=23161&p=178605#p178605

Please explain this error message. Regards!

**Comment by gizmocuz** [comment]
Please do not cross post
