### ISSUE TITLE
Cant add action to selector switch

### ISSUE THREAD

**Issue by devrosx** [domoticz/domoticz#2352]
Version: latest 3.9326
Platform: ubuntu
Plugin/Hardware: bananapi
Description:

hello, noticed that i cant add script path to selector switch (its not saved) when i save some script or url and open again selector switch path is blank. even when i edit allready configured selector switch (with defined paths) then hit save, reopen selector swith and all action paths are gone...
whith normal buttons script path works without problem..
on selector switch with allready defined urls it works (without editing)

bug allready confirmed by other user
http://www.domoticz.com/forum/viewtopic.php?f=6&t=23203

**Comment by gizmocuz** [comment]
Thanks for reporting. Acknowledged!
It is send to the web interface correctly, but the RType_SetUsed function is not taking over the settings for some reason.

**Comment by gizmocuz** [comment]
Problem is probably in CSQLHelper::BuildDeviceOptions, it splits the options with a ':' and this goes wrong for url's/scripts as they contain double points... i will fix this later

**Comment by gizmocuz** [comment]
Fixed, new beta available within the hour

**Comment by devrosx** [comment]
Thanks for quick fix :)

**Comment by gizmocuz** [comment]
No worries... fixed in version 9327, should be available now

**Comment by sweetpants** [comment]
Working again, thanx
