### ISSUE TITLE
Netatmo smart radiator valves support

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2353]
Netatmo is now providing radiator valves. While Domotocz support currently Netatmo weather and thermostat it would be good to have the support of the Radiator Valves as well

**Comment by gizmocuz** [comment]
Do you own a radiator ? If yes, could you send me a PM on the forum ?

**Comment by pipiche38** [comment]
I sent you everything you need ;-)

**Comment by pipiche38** [comment]
Working from version #9433

**Comment by pipiche38** [comment]
You can also set the thermostat Setpoint value and also get the local temperature. However there is a Scheduled in place on the Netatmo cloud which will overwrite for example the setpoint (as setpoint is only valid for 3hours by default).

The good point is that you get the new setpoint later on (I believe you do some kind of polling to the netatmo cloud).

I don't think that there is anyway to overwrite the schedule from domoticz, but I think everyone should be aware.

**Comment by gizmocuz** [comment]
Should be implemented in the latest beta version

**Comment by gizmocuz** [comment]
In the code we specify an end-time for the new setpoint, this is by default 1 hour.
We could set this to 1 day ?
But you can also put your thermostat in 'away' mode when you are not home and this stays in this mode until specified otherwise

**Comment by pipiche38** [comment]
While looking on the API HOMESDATA, I found the following information, and it seems that the setpoint could be Manual or Schedule. If it is schedule then it rely I believe on Netatmo schedule, but if we put it Manual, and even "hg" (which I don't know what it is ) I believe that we can then rely on a full schedule from Domoticz, no ?

    id: "2402104223"
    reachable: true
    therm_measured_temperature: 23
    heating_power_request: 100
    therm_setpoint_temperature: 16
    therm_setpoint_mode: "schedule"
    therm_setpoint_start_time: 1526312039
    therm_setpoint_end_time: 0

    id: "2833407963"
    reachable: true
    therm_measured_temperature: 22
    heating_power_request: 100
    therm_setpoint_temperature: 30
    therm_setpoint_mode: "manual"
    therm_setpoint_start_time: 1526312107
    therm_setpoint_end_time: 1526322600

**Comment by gizmocuz** [comment]
That seems correct

**Comment by pipiche38** [comment]
Found quiet interesting information on 
https://github.com/Netatmo/Netatmo-API-PHP/blob/master/src/Netatmo/Clients/NAThermApiClient.php (you might already know that)

So I think your id on using "manual" and setting 1 days is probably the best as we then overwrite the schedule for a day .

What I understand also is that the Max temperature is 30°C. If on the current domiticz we set to 33°C, nothing happen. So it might be important that when doing setpoint there is some control , no ?

**Comment by gizmocuz** [comment]
I think this is now implemented and the issue can be closed ?

**Comment by pipiche38** [comment]
Agree to close. 
Thanks
