### ISSUE TITLE
dark-th3me alignment issue

### ISSUE THREAD

**Issue by pepsi92** [domoticz/domoticz#2354]
Hi,

I have a minor issue using the dark-th3me theme in domoticz. Some of the panels in the dashboard view are not correctly aligned when there is a slider inside:

![capture ecran 2018-04-28 a 09 13 52](https://user-images.githubusercontent.com/18167025/39393439-7b08c94a-4ac5-11e8-9254-e83367393f14.png)

Not a recent issue. It appears for a long time but I never take the time to report it.

Any idea ?

Kind regards,
Nicolas

**Comment by gizmocuz** [comment]
Use the default theme for now
