### ISSUE TITLE
Fresh Install, Can't Add Timer

### ISSUE THREAD

**Issue by majorsl** [domoticz/domoticz#2360]
Fresh install of Domoticz V3.9379 on RPi-Stretch (not Lite).
Input Location Settings (time, sunrise/set shown in GUI).
Create a switch with test dummy hardware.
Click Timer.
Regardless of what is picked, "Add" doesn't do anything. Cannot add timers.

Relevant discussion here with at least one person replicating issue.

https://www.domoticz.com/forum/viewtopic.php?f=6&t=23230&p=179155#p179155

I had debug logging running, and nothing at all is shown in the logs for errors or (attempted) action when clicking "add".

Edit: I don't know if it would help, but I quickly tared up my db files.
[domodb.tar.gz](https://github.com/domoticz/domoticz/files/1958767/domodb.tar.gz)

**Comment by sweetpants** [comment]
Looks like RPi only. I'm on Linux V3.9831 and no problem adding a timer according the above URL post to a dummy switch.

**Comment by majorsl** [comment]
Just for fun, I installed Jessie with the latest beta. Same thing. At least I can install the stable version now.

EDIT: stable version is working as expected.

**Comment by amauryschwartz** [comment]
Hi guys,

I've the same issue than @majorsl.

My config :
Domoticz V3.9389 on RPi-Stretch Lite

I've noticed this issue in the browser console (appears when I click "Add ") : 
TypeError: Cannot read property 'addTimer' of undefined
    at Object.addTimer (DeviceTimersController.js:141)
    at fn (eval at compile (angular.min.js:242), <anonymous>:4:164)
    at e (angular.min.js:288)
    at m.$eval (angular.min.js:151)
    at m.$apply (angular.min.js:151)
    at HTMLButtonElement.<anonymous> (angular.min.js:288)
    at HTMLButtonElement.dispatch (jquery-3.3.1.min.js:2)
    at HTMLButtonElement.y.handle (jquery-3.3.1.min.js:2)

**Comment by emontnemery** [comment]
@amauryschwartz That looks like browser cache issue, can you please try in incognito mode / in private tab?

**Comment by amauryschwartz** [comment]
@emontnemery Thanks for the advice. I've tried with different computers, different browsers, incognito mode = same issue.

**Comment by majorsl** [comment]
FWIW, when I was trying to solve it I tried: incognito (Chrome), Firefox, Safari, Edge and my wife's laptop with various combinations of browsers too.

**Comment by emontnemery** [comment]
@majorsl: I fail to reproduce with fresh install on raspberry pi. Can you check my steps, maybe you do something different?

These are my exact steps:
- In raspberry pi shell:
```
mkdir domoticz
cd domoticz
tar -xzf domoticz_linux_armv7l.tgz
./domoticz

```
- In browser
  - Navigate to http://<raspberrypi-ip>:8080/
  - Setup -> Hardware
  - Type: Dummy, Name: Dummy HW
  - Add
  - Create Virtual Sensors
  - Name: Switch 1, Sensor Type: Switch
  - Switches
  - Click "Timers"
  - Type: On Time
  - Add
- Expected result: Timer not added as per issue description
- Result: Timer is added:
![image](https://user-images.githubusercontent.com/14281572/39661915-4fae0dd8-505a-11e8-99c7-16de25330929.png)

**Comment by emontnemery** [comment]
@majorsl, @amauryschwartz Please let me know if I do something wrong when testing, I can't reproduce your issue.

**Comment by majorsl** [comment]
@emontnemery I'm sorry I haven't been back to this yet.  I have stable installed and working.  When I have a couple of days off I'll pop in a new SD and try again.  My steps were different:

- fresh install of stretch (not lite)
- sudo apt update
- sudo apt upgrade (reboot if required)
- sudo curl -L install.domoticz.com | bash

Once up and running:

- http://:8080
- Setup - Settings - Location - Apply (I thought location might be needed for Times, at least sunrise/set.)
- Setup - Hardware
- Type: Dummy, Name: Dummy HW
- Add
- Create Virtual Sensors
- Name: Switch 1, Sensor Type: Switch
- Switches
- Click "Timers"
- Type: On Time
- Add

Alternately:

- Switches
- Manual Light/Switch
- Fill out info
- Add

Trying to set timers either way did not work.

Both ways above work perfectly for me with the stable release. I'm controlling some old x10 modules with scripts and dummy hardware while I look into migrating to much newer equipment.

**Comment by tsesakamoto** [comment]
@majorsl I also have the same issue.
I followed your steps as described, but I can't use Stable version (web page not found). 
Maybe the difference is that I use a Raspberry Pi 3B+.

When I upgrade to Beta, it all works, but I still can't add timers.
Also I can't add devices in a created group. I select a device, click add, but it won't appear in the device list of the group.

**Comment by emontnemery** [comment]
Since you are both first installing stable version and then upgrading to beta, I still think it might be an issue with bad version of WebUI served to the browser.

Please follow these steps:
1. Delete `www/js/domoticz.js.gz` under domoticz install directory if it exists
   Note: Do NOT delete `www/js/domoticz.js`
2. Delete `www/js/domoticzdevices.js.gz` under domoticz install directory if it exists
   Note: Do NOT delete `www/js/domoticzdevices.js`
3. Try in browser incognito mode

If this helped, clear browser cache AND browser appcache, it should now work also in non incognito mode

**Comment by tsesakamoto** [comment]
Thanks @emontnemery, it worked for me!
I can add timers now. Also I can add switches to a group now.
