### ISSUE TITLE
Active: active (exited) ERROR  with the lastest beta

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#2361]
Are there more people that having problems with the last domoticz update?

I get the %^&%*^&  exited error:

domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh; bad; vendor preset: enabled)
   Active: active (exited) since Sun 2018-04-29 17:14:11 CEST; 52s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1731 ExecStop=/etc/init.d/domoticz.sh stop (code=exited, status=0/SUC
  Process: 1847 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/S

Search the form to this error:
viewtopic.php?f=3&t=19341

Only most of links are dead..
And all the other thing in this thread are not give the solution

When i use the latest stable my system is working strange, bud working....

Some one??

Thanks

**Comment by Siewert308SW** [comment]
This is what i get when running gdb session on the latest available beta (3.9379) 
At the moment of this writing no newer version available 

Thread 10 "domoticz" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x720ff430 (LWP 637)]
0x002f396c in CSQLHelper::UpdateValueInt(int, char const*, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool)
    ()
(gdb)

**Comment by emontnemery** [comment]
This is fixed in beta 3.9381, which unfortunately has not made it to Raspberry Pi yet: https://domoticz.com/downloads/

**Comment by Dylantje** [comment]
mmm i run on a Odroid
Seenow there is a special image? for this board.
How can i see what type Domoticz i run?

Perhaps an idea when the fix is ready to use for the pi?

**Comment by Komagain** [comment]
@Dylantje as far as i see, there is an odroid dedicated release at http://www.domoticz.com/downloads/

https://releases.domoticz.com/releases/beta/domoticz_linux_aarch64.tgz

**Comment by Siewert308SW** [comment]
@emontnemery thx for the head up, hope to see it into the RPi version soon...

**Comment by Dylantje** [comment]
yes is sse now there is a odroid X64 version..
i think i use the 32 version.....
Do i need to install a 64 version os?
I use now:
Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.14.5-92 armv7l)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

Is this x64?
Or how can i run a ubuntu 16.04.4  on my Odroid Xu4?

**Comment by emontnemery** [comment]
@Dylantje Beta including fix for #2355 is now released also for 32-bit ARM: https://domoticz.com/downloads/, please close this ticket.

**Comment by Dylantje** [comment]
Thanks Guys!!!
