### ISSUE TITLE
Switch type Dimmer causes Uncaught ReferenceError: isLED is not defined

### ISSUE THREAD

**Issue by taakberg** [domoticz/domoticz#2362]
Using the latest beta 3.9379.

Whenever I create a virtual switch with type 'Dimmer', the interface breaks. The switch is not displayed, because Javascript throws the following error:
```
Uncaught ReferenceError: isLED is not defined
    at Object.<anonymous> (LightsController.js:formatted:965)
    at Function.each (jquery-3.3.1.min.js:2)
    at Object.success (LightsController.js:formatted:748)
    at u (jquery-3.3.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.min.js:2)
    at k (jquery-3.3.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.min.js:2)
    at Object.send (jquery-3.3.1.min.js:2)
    at Function.ajax (jquery-3.3.1.min.js:2)
    at ShowLights (LightsController.js:formatted:735)
```

This seems to be caused by [this commit](https://github.com/domoticz/domoticz/commit/fae2ff0c78c0879b2ac61afe439ea8910df0ac40), where there is referred to an isLED method that doesn't exist.

**Comment by emontnemery** [comment]
The isLED method exists..

Please make sure:
- If the file www/js/domoticz.js.gz exists under domoticz installation directory, delete it
  Note: Do NOT delete www/js/domoticz.js
- Test in incognito mode / in private tab to rule out browser cache issue

**Comment by taakberg** [comment]
You're right. This resolved the issue. Thanks!

**Comment by gmaslowski** [comment]
@emontnemery I still don't fully understand why this happens. I'm creating a docker image every couple of weeks for the beta versions and I'm keep getting the error as described. The image building looks like this: https://github.com/gmaslowski/rpi-domoticz/blob/master/Dockerfile . In shorter words -> execute `curl -L install.domoticz.com | sudo bash` and then execute `./updatebeta`. Does this mean that the stable version contains this *.js.gz file which is not needed and not being deleted during the beta upgrade?

**Comment by gizmocuz** [comment]
@gmaslowski , that is correct, some .gz files are deleted when upgrading to the beta version

**Comment by emontnemery** [comment]
@gmaslowski Yeah, as @gizmocuz says, the stable version has the .gz version, and that is supposed to be deleted during upgrade. However, a few users have reported that the delete did not happen.

**Comment by gizmocuz** [comment]
@emontnemery , it does happen unless they switched back to a release version, and then loaded a beta database.
Never go to a previous version is the lesson

I like the way python creates those pyc files. It will recompile when there is a change in a python file.
Would be great if we could do the same in runtime for .gz files, no need for feature deletions then
