### ISSUE TITLE
Xiaomi Gateway generate domoticz crash 

### ISSUE THREAD

**Issue by bregomoz** [domoticz/domoticz#2363]
Hi, 
I try to use the last beta version of domoticz with Xiaomi Gateway as described here [https://www.domoticz.com/wiki/Xiaomi_Gateway_(Aqara)](Xiaomi_Gateway_(Aqara))
and with the last beta version of domoticz it crash the application 

> 2018-04-30 14:59:47.114  (Xiaomi Gateway) Color Switch (Xiaomi RGB Gateway)
> 2018-04-30 14:59:47.123  (Xiaomi Gateway) Light/Switch (Xiaomi Gateway Volume)
> 2018-04-30 14:59:47.238  Error: Domoticz received fatal signal 11 !...
> 2018-04-30 14:59:47.251  Error:   /home/pi/domoticz/domoticz() [0x252178]
> 2018-04-30 14:59:47.251  Error:   /home/pi/domoticz/domoticz(_Z14signal_handleri+0x4c) [0x252230]
> 2018-04-30 14:59:47.251  Error:   /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0x76c766b0]
> 2018-04-30 14:59:47.251  Error:   /home/pi/domoticz/domoticz(_ZN10CSQLHelper14UpdateValueIntEiPKchhhhhiS1_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x60c) [0x2f396c]
> 2018-04-30 14:59:47.251  Error:   /home/pi/domoticz/domoticz(_ZN10CSQLHelper11UpdateValueEiPKchhhhhiS1_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x60) [0x2f4e98]
> 2018-04-30 14:59:47.251  Error:   /home/pi/domoticz/domoticz(_ZN10MainWorker10decode_LuxEi15_eHardwareTypesPK5tRBUFRNS_27_tRxMessageProcessingResultE+0xb0) [0x2997fc]
> 2018-04-30 14:59:47.251  Error:   /home/pi/domoticz/domoticz(_ZN10MainWorker16ProcessRXMessageEPK21CDomoticzHardwareBasePKhPKci+0xc24) [0x2b8cf4]
> 2018-04-30 14:59:47.251  Error:   /home/pi/domoticz/domoticz(_ZN10MainWorker22Do_Work_On_Rx_MessagesEv+0x7b4) [0x2bc424]
> 2018-04-30 14:59:47.251  Error:   /home/pi/domoticz/domoticz() [0x7d01b0]
> 

With the previous stable version of domoticz it's working without issue : 

> 2018-04-30 13:53:37.095  XiaomiGateway: will listen on 9898 for hardware id 2
> 2018-04-30 13:53:37.095  XiaomiGateway: Delaying worker startup...
> 2018-04-30 13:53:42.096  XiaomiGateway: Worker started...
> 2018-04-30 13:53:42.116  XiaomiGateway: Using 192.168.0.44 for local IP address.
> 2018-04-30 13:53:42.280  XiaomiGateway: RGB Gateway Detected
> 2018-04-30 13:53:42.281  XiaomiGateway: New Gateway Found (dcdf0d1e/Xiaomi RGB Gateway)
> 2018-04-30 13:53:42.285  (Xiaomi Gateway) Lighting Limitless/Applamp (Unknown)
> 2018-04-30 13:53:42.287  XiaomiGateway: New Switch Device Found (dcdf0d1e)
> 2018-04-30 13:53:42.290  (Xiaomi Gateway) Light/Switch (Unknown)
> 2018-04-30 13:53:42.293  XiaomiGateway: New Switch Device Found (dcdf0d1e)
> 2018-04-30 13:53:42.297  (Xiaomi Gateway) Light/Switch (Unknown)
> 2018-04-30 13:53:42.299  XiaomiGateway: New Switch Device Found (dcdf0d1e)
> 2018-04-30 13:53:42.303  (Xiaomi Gateway) Light/Switch (Unknown)
> 2018-04-30 13:53:42.306  XiaomiGateway: New Switch Device Found (dcdf0d1e)
> 2018-04-30 13:53:42.310  (Xiaomi Gateway) Light/Switch (Unknown)
> 2018-04-30 13:53:42.313  XiaomiGateway: New Switch Device Found (dcdf0d1e)
> 2018-04-30 13:53:42.317  (Xiaomi Gateway) Light/Switch (Unknown)
> 2018-04-30 13:53:42.425  XiaomiGateway: New Switch Device Found (01a680b0)
> 2018-04-30 13:53:42.429  (Xiaomi Gateway) Light/Switch (Unknown)
> 2018-04-30 13:53:42.432  XiaomiGateway: New Switch Device Found (01bc4051)
> 2018-04-30 13:53:42.436  (Xiaomi Gateway) Light/Switch (Unknown)
> 2018-04-30 13:53:42.440  (Xiaomi Gateway) General/Voltage (Xiaomi Voltage)
>

**Comment by Komagain** [comment]
You should try the 3.9381 version,
it has fix the following issue [2357](https://github.com/domoticz/domoticz/issues/2357)

**Comment by apazga** [comment]
I'll wait for the update via updatebeta script. Do you know when will it be uploaded?

**Comment by emontnemery** [comment]
It's uploaded now.

**Comment by bregomoz** [comment]
Hi, Version: 3.9389 solved the issue as for [2357](https://github.com/domoticz/domoticz/issues/2357).
Unfortunately I was not able to build binary by myself :/.

@gizmocuz Thanks for the build.
