### ISSUE TITLE
SQL error on adding a timer (Hue column does not exist)

### ISSUE THREAD

**Issue by wulfy** [domoticz/domoticz#2365]
Hi there,

I'm running Domoticz 3.8153 on raspbian stretch.
I can't add any timer on my switch devices (when adding a timer nothing happens).
I check my logs and found an SQL error:
```
Error: SQL Query("SELECT ID, Active, [Date], Time, Type, Cmd, Level, Hue, Days, UseRandomness, MDay, Month, Occurence FROM Timers WHERE (DeviceRowID==2) AND (TimerPlan==0) ORDER BY ID") : no such column: Hue
2018-05-01 13:23:56.317 Error: SQL Query("SELECT ID, Active, [Date], Time, Type, Cmd, Level, Hue, Days, UseRandomness, MDay, Month, Occurence FROM Timers WHERE (DeviceRowID==2) AND (TimerPlan==0) ORDER BY ID") : no such column: Hue
```

Should I add "Hue" column? (i have no Hue devices, only zwaves).
I previously installed the BETA verion of domoticz but I fall back to the release version. May be something wen wrong during the "downgrade" ?

Thank you !

W

**Comment by gizmocuz** [comment]
You can not switch between beta and stable as the database has been patched!
Switch back to the beta should solve it

**Comment by gizmocuz** [comment]
(Or load an old backup made with that stable version!)
