### ISSUE TITLE
Add Milight does not work anymore

### ISSUE THREAD

**Issue by Cliff-R-K** [domoticz/domoticz#2366]
If I add a milight hub husing the "Limitless/AppLamp/..." option on the hardware page the hub is found and 4 milight groups are created. But the strange thing is that all devices that are created gets the same ID. All have ID=1 (Not IDX).

If I click the green arrow to add them they do not show up on the switches page. I can still turn the milight bulbs on and off from clicking on the bulb on the devices page. If I add another hub it also gets the same ID and does not show up on the switches-page after configuration.

I had it all working before but now I do not know if it is the beta version that caused this or if there is some other problem.

**Comment by sweetpants** [comment]
platform, OS, domoticz version? log messages?

**Comment by Cliff-R-K** [comment]
Raspbery Pi 3
Raspbian
domoticz beta 3.9379

**Comment by sweetpants** [comment]
There is an issue adding devices which is fixed in Beta v3.9381. Unfortionatly there is no binary version availible for rpi yet. https://github.com/domoticz/domoticz/issues/2357

**Comment by gizmocuz** [comment]
Should be there

**Comment by emontnemery** [comment]
@burton666 I think it's correct with same ID, the groups are distinguished by different Unit, ID is hardcoded to 1.
After clicking the green arrow, can you verify that the milight groups show up in the JSON response:
`http://<domoticz_ip>:8080/json.htm?type=devices&filter=lights`

**Comment by jdecelis** [comment]
I Have the same problem with v3.9390.

**Comment by emontnemery** [comment]
@jdecelis:
After clicking the green arrow, can you verify if the milight groups show up in the JSON response:
`http://<domoticz_ip>:8080/json.htm?type=devices&filter=lights`

**Comment by jdecelis** [comment]
they are all listed in that json file even if the green arrow is not clicked

**Comment by emontnemery** [comment]
@jdecelis Good. Can you check that "Used" field for the relevant device in the JSON data is changed from 0 -> 1 when you click the green arrow, and changes back 1 -> 0 when you click the purple arrow to again remove it?

**Comment by jdecelis** [comment]
Yes it changes accordingly

**Comment by jdecelis** [comment]
updated to 3.9421 and still milight devices are not listed under switches.

**Comment by Tontze** [comment]
Mine works correctly on 3.9390

**Comment by emontnemery** [comment]
@jdecelis, @burton666: Since it works for most people, and there is no issue in domoticz backend according the the tests by @jdecelis this might be caused by bad state of browser or app cache.

Please make sure:
1. If the file `www/js/domoticz.js.gz` exists under domoticz installation directory, delete it
   Note: Do NOT delete `www/js/domoticz.js`
2. Test in incognito mode / in private tab to rule out browser cache issue

**Comment by jdecelis** [comment]
@emontnemery point 1solved  it... thanks
