### ISSUE TITLE
Crash every day or multiple times a day

### ISSUE THREAD

**Issue by zwartevogel** [domoticz/domoticz#2367]
I'm running on a RPI 3 domoticz build V3.9379

It randomly stops working every couple of days, sometimes multiple times a day. The domoticz log tells me this:
2018-05-01 03:02:35.865  RFLink: 20;33;Friedland;ID=24828280;SWITCH=1;CMD=ON;CHIME=01;
2018-05-01 03:02:35.871  Error: Domoticz received fatal signal 11 !...
2018-05-01 03:02:35.885  Error:   /home/pi/domoticz/domoticz() [0x252178]
2018-05-01 03:02:35.885  Error:   /home/pi/domoticz/domoticz(_Z14signal_handleri+0x4c) [0x252230]
2018-05-01 03:02:35.885  Error:   /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer_v2+0) [0x76be0180]
2018-05-01 03:02:35.885  Error:   /home/pi/domoticz/domoticz(_ZN10CSQLHelper14UpdateValueIntEiPKchhhhhiS1_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x60c) [0x2f396c]
2018-05-01 03:02:35.885  Error:   /home/pi/domoticz/domoticz(_ZN10CSQLHelper11UpdateValueEiPKchhhhhiS1_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x60) [0x2f4e98]
2018-05-01 03:02:35.885  Error:   /home/pi/domoticz/domoticz(_ZN10MainWorker20decode_GeneralSwitchEi15_eHardwareTypesPK5tRBUFRNS_27_tRxMessageProcessingResultE+0x94) [0x2a8c34]
2018-05-01 03:02:35.885  Error:   /home/pi/domoticz/domoticz(_ZN10MainWorker16ProcessRXMessageEPK21CDomoticzHardwareBasePKhPKci+0xc04) [0x2b8cd4]
2018-05-01 03:02:35.885  Error:   /home/pi/domoticz/domoticz(_ZN10MainWorker22Do_Work_On_Rx_MessagesEv+0x7b4) [0x2bc424]
2018-05-01 03:02:35.886  Error:   /home/pi/domoticz/domoticz() [0x7d01b0]

Anyone knows what can be the issue? And even better, what can solve this issue?

**Comment by McMornan** [comment]
Hi,

I have the same issue and the same error message. I pulled latest beta 9389 and compiled from source ... still the same issue. 

regards,
Lars

**Comment by jonferreira** [comment]
Wondering if it's somehow related with #2364

How are you running domoticz?

**Comment by Tontze** [comment]
i needed to drop down to stable since i cuoldnt start latest beta anymore, it dies immediately after start. On the forum many have reported this issue.

**Comment by jonferreira** [comment]
Yes I'm having the same problem with the latest Beta! Updated yesterday in an effort to fix #2364 but just made it worse: it either crashes while booting or few minutes after :(

**Comment by emontnemery** [comment]
@zwartevogel, @McMornan, @Tontze:
Please note version v3.9379 was extremely unstable due to #2355. The stacktrace reported by @zwartevogel is #2355 so please close this ticket.
Note: If you can still reproduce crashes, start domoticz through gdb and print a stacktrace once you get the crash:
```
gdb ./domoticz
run
<wait for segmentation fault>
bt
```
Then open a new ticket with the full stack trace.

**Comment by xztraz** [comment]
Crash on Version: 3.9389
Build Hash: 28d24885

```
[Thread 0x6f7ff440 (LWP 11104) exited]
[New Thread 0x6f7ff440 (LWP 11105)]
[Thread 0x6f7ff440 (LWP 11105) exited]
2018-05-04 10:10:04.935  Error: Device creation failed, Domoticz settings prevent accepting new devices.
2018-05-04 10:10:07.039  (RfLink) Temp + Humidity (Temp-Vinden S)
2018-05-04 10:10:07.044  HttpLink: sending global variable atticsouth_temp with value: 13.0
[New Thread 0x6f7ff440 (LWP 11112)]
[Thread 0x6f7ff440 (LWP 11112) exited]
2018-05-04 10:10:07.079  HttpLink: response
2018-05-04 10:10:07.082  HttpLink: sending global variable atticsouth_hum with value: 65
[New Thread 0x6f7ff440 (LWP 11113)]
[Thread 0x6f7ff440 (LWP 11113) exited]
2018-05-04 10:10:07.118  HttpLink: response
2018-05-04 10:10:08.058  (RfLink) Temp + Humidity (Inne-Hall)
2018-05-04 10:10:08.504  Kodi: (test) Connect to '1.2.3.4:9090' failed: (110) Connection timed out

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x6b5ff440 (LWP 6111)]
0x003ed90c in boost::asio::detail::epoll_reactor::deregister_descriptor(int, boost::asio::detail::epoll_reactor::descriptor_state*&, bool) ()
(gdb) bt
#0  0x003ed90c in boost::asio::detail::epoll_reactor::deregister_descriptor(int, boost::asio::detail::epoll_reactor::descriptor_state*&, bool) ()
#1  0x0047bd80 in boost::asio::detail::reactive_socket_service_base::destroy(boost::asio::detail::reactive_socket_service_base::base_implementation_type&) [clone .isra.140] ()
#2  0x00484578 in CKodiNode::handleConnect() ()
#3  0x00484ef8 in CKodiNode::Do_Work() ()
#4  0x007d0190 in thread_proxy ()
#5  0x76f27e90 in start_thread (arg=0x6b5ff440) at pthread_create.c:311
#6  0x76d8b598 in ?? () at ../ports/sysdeps/unix/sysv/linux/arm/nptl/../clone.S:92 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by jonferreira** [comment]
Sounds to me the problem is on the dummy Kodi hardware you have with IP set to 1.2.3.4...

Obviously it shouldn't crash but still, if that's the case it's pretty easy to fix

**Comment by xztraz** [comment]
it crashed before with a http request as last thing before crash. so i don't think it's that (also it has been running with the test kodi device for months before wo prob).

I have removed it anyway and waiting for next crash with trace

**Comment by emontnemery** [comment]
@jonferreira I think you're right, the crash is in the destructor of a boost socket in a CKodiNode object. The socket seems to be incorrectly used both by Domoticz' main thread and by the worker thread without synchronization, which will cause crashes.

**Comment by jonferreira** [comment]
yeah sounds about right :)

That doesn't sound like the same problem me or @zwartevogel is having though

**Comment by emontnemery** [comment]
Right, the issue reported by @zwartevogel is duplicate of #2355 and this issue should be closed..
@xztraz Can you open a new issue for the crash in CKodiNode please?

**Comment by zwartevogel** [comment]
I updated to v3.9389 and no problems anymore! Thanks!

**Comment by dnpwwo** [comment]
@xztraz you should try the Kodi Python plugin, it has a lot more functionality and is actively supported

**Comment by emontnemery** [comment]
@dnpwwo If no one is maintaining the native kodi functionaility, can it be removed?

**Comment by dnpwwo** [comment]
@emontnemery, its not that no one is maintaining it, it is as supported as most hardware in Domoticz.  There haven't been any issues reported for a few years and it hasn't been upgraded either was my point.

Overall I think anything that makes the c++ codebase smaller is a good thing (that's why I made the python framework) so I don't have a problem with removing it from the backend code but some people still use it so you should probably ask on the forum if anyone would mind. 

There is also some fuctionality around remote controls in the web server and UI that would need to remain because it is used by a number of devices.

**Comment by xztraz** [comment]
@dnpwwo i'm running both variations of kodi remote. the built in and the pyhton. i had forgot a bout some test i did before with the non responsive client. well i haven't had a crash in 20h+ so maybe it was that.

**Comment by dannybloe** [comment]
Well, there can be a legitimate reason to remove stuff from code. I guess the best thing to do is to make it deprecated for an entire (stable) release and show a warning in the log that support will be removed in the next stable.

**Comment by dnpwwo** [comment]
@dannybloe that certainly would be the way to do it although to me there is no point removing a single piece of hardware unless there is a consensus amoung the devs that we should be moving to Python controlled hardware with a view to the C++ running core automation functions and being as small as possible.

For example, I also run Python instead of using the native C++ RAVEn Energy Monitoring support because it has more functionality.  There are also Python and C++ versions of some amplifiers too.

Maybe this should be a slack discussion
