### ISSUE TITLE
Hex code,  near hue and yeelight bulb

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#2368]
Dear developers....
Until a few months ago there was a option to set a hex code in the hue or yeelight.
Now this gone..
Is there perhaps a option to get this hex code option back?
This was a very great option to set all bulbs into the same color.
With the colorpicker is this almost impossible.

**Comment by emontnemery** [comment]
Where would you like to see this, is it in timer and scene editors?

**Comment by gizmocuz** [comment]
This was in the JSON api

**Comment by Dylantje** [comment]
Dear...
In this area was in older versions a place where you set the color with hex...
https://drive.google.com/open?id=1dHFUUglCOUDKZHVJ4yuHLeKTyUXhPEWi

**Comment by gizmocuz** [comment]
Ahhh okey..yes that is indeed gone now....

**Comment by Dylantje** [comment]
That was a great feature ...
All the lights the same color..
And the same level...

**Comment by emontnemery** [comment]
@dylantje Where would you like to see this, is it in timer and scene editors?

Edit: Also, which format do you suggest? There is now both RGB picker and color temperature picker..

**Comment by Dylantje** [comment]
Dear,,, When you can implement this great!!
The type/format should be in my eyes..:
http://www.color-hex.com/  [ in the top there is a color picker that give the color a Hex code ]

Where u can place this.. like it on the place where i let you see....
Perhaps also in the timer section.

If possible...
Perhaps als in blockley..:-) [ set a bulb in blockley, to a hex code. ]

And when you are my superhero....
If possible make a fade option in the timer and blockley section..:-)


And when you will be a super super hero for the WAF.... and the kids..
A disco option ,... :-)

Only i think i'am  dreaming out loud ....
Thanks..!!
 xx

**Comment by Dylantje** [comment]
mmm Dream this night about it :-)
Perhaps also in the groups/scene section..

x
x

**Comment by gizmocuz** [comment]
@emontnemery , i think he is talking about the colorwheel popup. In the new popup you can not enter a hex value, so you have to click on a point to set the color.

**Comment by gizmocuz** [comment]
According the colorwheel pickers github page, it should be possible to add a textbox for the RGB value, do you think this is possible to implement ?
Maybe also at the bottom of the sliders a small numeric textbox for the slide values

**Comment by emontnemery** [comment]
@gizmocuz Yeah, it's no biggie to add it, either use built in functionality in the colorwheel picker as you say, or something custom. I can work on it in a couple of weeks if no one else has time.

**Comment by gizmocuz** [comment]
@emontnemery , that would be great! (maybe after the gdb PR :grinning: hehe

**Comment by 111wolf111** [comment]
Hi...
Any word on getting the hex back?....really miss the hex to set all my lights the same instead of just hit and miss.
Wish I could help, but I have no programming skills.
Thanx

**Comment by gizmocuz** [comment]
@emontnemery , can't this be entered in the color popup ?

**Comment by 111wolf111** [comment]
no unfortunately not....unless I'm really missing something......

this is the popup

![dom1](https://user-images.githubusercontent.com/43987175/46670199-d2339780-cbd1-11e8-9bd7-adab2c9a88db.jpeg)


and this is in the scenes

![dom2](https://user-images.githubusercontent.com/43987175/46670018-520d3200-cbd1-11e8-8932-4de627b86797.jpeg)

**Comment by gizmocuz** [comment]
If the popup is extended a few pixels in height (under the color: picker) then we could add a editbox for the hex value maybe ? I know most color pickers support this by default, so it also might be setting a 'flag' and it will be displayed and no additional code has to be written

**Comment by 111wolf111** [comment]
That would be great, anything to get it back, unfortunately I have no skills to do it, I know your probably busy as hell but would be great if you could find some time to pop it in.....
Thanx

**Comment by emontnemery** [comment]
@gizmocuz You're right, such an input is available in the color picker already. The "problem" is that I added support for color temperature as well as color + color temperature at the same time, so it's not as easy as just turning it on.
I'll have time to look at this at the end of October though.

**Comment by gizmocuz** [comment]
@emontnemery , thanks for the help already ! If there is room, i would put an edit box under the picker and the sliders, that way users could exactly enter what they want

**Comment by 111wolf111** [comment]
@gizmocuz @emontnemery , Thanks guys for looking into it, can't tell you how much I appreciate it.

**Comment by emontnemery** [comment]
@Dylantje, @111wolf111 Please have a look at #2810, and comment if your request is correctly understood.

**Comment by 111wolf111** [comment]
@emontnemery, yes the hex would be great, you are a champ.... thanx soooo much!!

**Comment by 111wolf111** [comment]
@emontnemery, @gizmocuz , I saw that #2810  has been added so updated to beta 10119, but unfortunately the hex is still not there, even with default skin... :-(

**Comment by 111wolf111** [comment]
nevermind, I'm on 10145 and it's there now...... you guys are champs, thanx so so much, it's really appreciated... :+1: 
what would be really fantastic is if the hex could be there also for the switches..... but to me the scene were more important....

**Comment by Dylantje** [comment]
Dear developers
Great work!!
Almost there....

Is it perhaps possible to make an option to set the light-value to % options ...
So i can set  more lights at the same time, to the same light-value

**Comment by waltervl** [comment]
Fixed, Issue can be closed
