### ISSUE TITLE
Slider not visible for Switch type Light/Switch, AC, Dimmer 

### ISSUE THREAD

**Issue by richarddeweerd** [domoticz/domoticz#2370]
For (new) switches of type Light/Switch, AC, Dimmer the slider is not visible see:

![missing-slider](https://user-images.githubusercontent.com/4639826/39565883-f10f211e-4eb9-11e8-9fcb-3bedd92bd902.png)

Version: V3.9389

**Comment by Eorciu** [comment]
the same problem in theme "Aurora"  (Version: V3.9389)
![image](https://user-images.githubusercontent.com/29353438/39574222-a29a45d2-4ed6-11e8-9237-71cd703d7c5f.png)

**Comment by emontnemery** [comment]
@richarddeweerd, @Eorciu  Do you see this issue also in browser's incognito mode?

**Comment by Eorciu** [comment]
Yep. Still missing slider 
![image](https://user-images.githubusercontent.com/29353438/39592934-a2be3c94-4f08-11e8-8aa5-89b84f15f771.png)

**Comment by emontnemery** [comment]
@Eorciu: OK, maybe it's a bug related to this commit: https://github.com/domoticz/domoticz/commit/7dc47a16ed311c054af666cfa45f292d4e5fb11f

Can you please post output of http://<domoticz_ip>:8080/json.htm?type=devices&filter=lights

**Comment by richarddeweerd** [comment]
@emontnemery I cropped only the switch that is showing faulty:

`{
    "ActTime": 1525380017,
    "AstrTwilightEnd": "23:49",
    "AstrTwilightStart": "03:28",
    "CivTwilightEnd": "21:50",
    "CivTwilightStart": "05:27",
    "DayLength": "15:03",
    "NautTwilightEnd": "22:42",
    "NautTwilightStart": "04:35",
    "ServerTime": "2018-05-03 22:40:17",
    "SunAtSouth": "13:05",
    "Sunrise": "06:07",
    "Sunset": "21:10",
    "result": [{
        "AddjMulti": 1.0,
        "AddjMulti2": 1.0,
        "AddjValue": 0.0,
        "AddjValue2": 0.0,
        "BatteryLevel": 255,
        "CustomImage": 0,
        "Data": "Set Level: 1 %",
        "Description": "",
        "DimmerType": "none",
        "Favorite": 1,
        "HardwareID": 8,
        "HardwareName": "RF",
        "HardwareType": "RFLink Gateway USB",
        "HardwareTypeVal": 46,
        "HaveDimmer": false,
        "HaveGroupCmd": false,
        "HaveTimeout": false,
        "ID": "00AE6306",
        "Image": "Light",
        "IsSubDevice": false,
        "LastUpdate": "2018-05-03 21:09:02",
        "Level": 1,
        "LevelInt": 1,
        "MaxDimLevel": 100,
        "Name": "Schemerlamp",
        "Notifications": "false",
        "PlanID": "0",
        "PlanIDs": [
            0
        ],
        "Protected": false,
        "ShowNotifications": true,
        "SignalLevel": "-",
        "Status": "Set Level: 1 %",
        "StrParam1": "",
        "StrParam2": "",
        "SubType": "AC",
        "SwitchType": "Dimmer",
        "SwitchTypeVal": 7,
        "Timers": "true",
        "Type": "Light/Switch",
        "TypeImg": "dimmer",
        "Unit": 1,
        "Used": 1,
        "UsedByCamera": false,
        "XOffset": "0",
        "YOffset": "0",
        "idx": "297"
    }],
    "status": "OK",
    "title": "Devices"
}`

**Comment by emontnemery** [comment]
@richarddeweerd Thanks!
The reason for no dimmer slider in UI is that `HaveDimmer` is set to `false` in the JSON response. I think it's an old bug which have surfaced due to changes in 7dc47a1.
Can you please check "Type" and "SubType" of the device with idx=297?
Easiest way is probably to open domoticz.db in "DB Browser for SQLite".

**Comment by richarddeweerd** [comment]
Type = 244
SubType = 11

![device](https://user-images.githubusercontent.com/4639826/39603264-04e373c0-4f28-11e8-80c8-2158cb35517c.png)

**Comment by emontnemery** [comment]
@richarddeweerd Thank you! Root cause found (old bug in GetLightStatus()), I'll try to push a fix tomorrow.

**Comment by richarddeweerd** [comment]
Thanks!
