### ISSUE TITLE
Mobile view needs improvement

### ISSUE THREAD

**Issue by quack3d** [domoticz/domoticz#2371]
Floorplan appears to be missing some margins or something. Look at the picture to the left. The Domoticz writing at the bottom is missing and the settings icon on top right is cut off. Easy to spot when using Inspect and Toggle device toolbar in Chrome.

The right picture shows the hidden PLANS menu in mobile view. To even be able to choose Roomplan, Floorplan and Timerplan there you have to long press PLANS.

I'm using dark-th3me.

![domoticz](https://user-images.githubusercontent.com/25592497/39581548-1fe06fde-4eec-11e8-8706-a5f3849f962e.png)

**Comment by flatsiedatsie** [comment]
Try the Aurora theme. It works much better on mobile.

**Comment by gizmocuz** [comment]
Why would you even go there on such a small device ? Maybe we should remove most of the setup option on a mobile view (small screen)

**Comment by quack3d** [comment]
I often go there via mobile to fix things and add to the floorplan when I'm not in front of a computer.

But what about the first issue? Wrong place to report about bug in the dark-th3me?

**Comment by gizmocuz** [comment]
Not really, but mentioned before, in the current beta and upcoming release ONLY the default theme is supported.
