### ISSUE TITLE
Domoticz on Ubuntu 18.04 with curl does not work

### ISSUE THREAD

**Issue by Cliff-R-K** [domoticz/domoticz#2373]
I am running Ubuntu 18.04, after install domoticz works but if I install curl which is needed for some of my scripts domoticz is not accessable after update.

Installed Curl via apt-get. This updated libcurl3 to libcurl4 which breaks Domoticz

`burton666@domoticz:~/domoticz$ ./domoticz
./domoticz: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./domoticz)
burton666@domoticz:~/domoticz$
`

So I have to choose between installing Curl and runnign Domoticz

**Comment by gordonb3** [comment]
Compile Domoticz from source.

**Comment by jpg06** [comment]
Hi,
An other way is to do `apt-get install libcurl3`
After, you can use the latest version of domoticz on ubuntu 18.04

**Comment by martin3000** [comment]
> sudo apt-get install libcurl3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libcurl3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libcurl4:i386 libcurl4

E: Package 'libcurl3' has no installation candidate
