### ISSUE TITLE
Barometer not saving history

### ISSUE THREAD

**Issue by xztraz** [domoticz/domoticz#2381]
Version: 3.9390
Build Hash: 8d290f21
Compile Date: 2018-05-06 12:50:59
dzVents Version: 2.4.5
Python Version: 3.4.2 (default, Oct 19 2014, 14:03:53) [GCC 4.9.1]

Barometric dummy device don't seem to save any history (and you get no prediction)

Using an ESP to send data to domoticz. receiving to a dummy sensor
![image](https://user-images.githubusercontent.com/25690871/39713748-2eeab694-5228-11e8-9c31-6c2a3268a851.png)
I get correct data on barometric pressure.
and i can see it on the weather devices page too
![image](https://user-images.githubusercontent.com/25690871/39713790-54637dc0-5228-11e8-9f66-26ad946a9005.png)

But there is no history saved
![image](https://user-images.githubusercontent.com/25690871/39713837-7bb61126-5228-11e8-87f3-79b9a9e516d5.png)

Other types of barometric sensors work fine like Temp+Baro and T+B+H. It seem to be a problem with the only barometric pressure sensor.

log doesn't say anything when updating sensor.  i get fresh data from sensor in gui. should be over 24h logged now.

**Comment by gizmocuz** [comment]
Could you give me the complete json call ? It looks like there is possible something wrong with it as the prediction is "unknown" ...

**Comment by flatsiedatsie** [comment]
Unknown usually means there is not enough data yet to create the prediction. If it's a dummy device it has no real data, so cannot create a prediction?

**Comment by gizmocuz** [comment]
you could based on it's value...
I do both own temp+hum+baro sensors as well as baro only sensors, and see no issues.
Try clearing your browser + appcache, or as said, please show us the json call that is used to update the baro sensor as there might be something wrong with it
Saying "using an esp" ... that does not say me anything what is called via JSON

**Comment by xztraz** [comment]
oh the call to update the sensor.  hmm its from espeasy log from that.

371166428 :  Domoticz: Sensortype: 3 idx: 926 values: 1016.86;1019;0;0
so it sends some dummy values too. first one is the barometric pressure.

Well if it works for you its probably the espeasy call thats wrong.
tried with Sensortype 1 also but then it does not work at all. (only sends one value)

do you have a tcpdump command i can use i can look at the actual packet.

**Comment by xztraz** [comment]
Got it
From ESP Sensor
GET **/json.htm?type=command&param=udevice&idx=926&nvalue=0&svalue=1016.98;1019;0;0&rssi=9** HTTP/1.1

looking at the api for json.
/json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=BAR;BAR_FOR
The above sets the parameters for a Barometer device from hardware type 'General'
IDX = id of your device (This number can be found in the devices tab in the column "IDX")
BAR = Barometric pressure
BAR_FOR = Barometer forecast


So its probably the extra values that is sent. if that isn't in range 0-6 it seem to mess stuff up.

**Comment by xztraz** [comment]
Changed the second value to 0. now prediction says stable. (it still sends the extra values thou)
So my data was a bit out of range. Lets wait a bit and see if it saves some history now.

how do you update a barometric sensor if you don't have prediction?  i though domoticz did the prediction?

**Comment by xztraz** [comment]
No still no history.

**Comment by gizmocuz** [comment]
Every 5 minutes there should be a history value added
But if i look at your svalue... this seems not correct 1016.98;1019 ? whats this ?

> Barometer
> /json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=BAR;BAR_FOR
> The above sets the parameters for a Barometer device from hardware type 'General'
> IDX = id of your device (This number can be found in the devices tab in the column "IDX")
> BAR = Barometric pressure
> BAR_FOR = Barometer forecast
> 
> Barometer forecast can be one of:
> 0 = Stable
> 1 = Sunny
> 2 = Cloudy
> 3 = Unstable
> 4 = Thunderstorm

so a valid call is

/json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=1023.4;1

**Comment by gizmocuz** [comment]
So there are 2 parameters in svalue, not 4

**Comment by gizmocuz** [comment]
Could you point me to that espeasy code ?

**Comment by xztraz** [comment]
> ... this seems not correct 1016.98;1019 ? whats this ?

the second value was a rest from some testing. changed it to 0 after reading on the api. and then i get the gui to say stable. (but still no hist)

the dummy device in espeasy

![image](https://user-images.githubusercontent.com/25690871/39965019-6560cd9a-5691-11e8-9e35-81b0284a5e04.png)

there are no baro only device in espeasy so. tried type single. that doesn't register at all in domoticz for baro.   /json.htm?type=command&param=udevice&idx=926&nvalue=0&svalue=1022.07&rssi=9 HTTP/1.1

![image](https://user-images.githubusercontent.com/25690871/39965043-c97fba3e-5691-11e8-80a1-316bd2d05c57.png)

The goal is to just register barometric pressure without temperature from this device since temp is way off (internal temp on heated pcb)

**Comment by xztraz** [comment]
i find it odd that i can see the baro value in domoticz gui but history seem to interpret the data differently.

**Comment by xztraz** [comment]
i've tried with type_dual
GET /json.htm?type=command&param=udevice&idx=926&nvalue=0&svalue=1022.05;0&rssi=9 HTTP/1.1
that looks better and registers in history.

esp code for temp_baro https://github.com/letscontrolit/ESPEasy/blob/fcea12b51594ceecee835cc1da2993446e2792e2/src/_CPlugin_DomoticzHelper.ino
row 77
it tries 4 values.

**Ok so the espeasy could have a baro only device wich sends only 2 values. dual seem to do that.
Domoticz could have stricter check of incoming data. throw away extra stuff. and accepting less values?** 

as a good programmer said. wide in, narrow out. 

Isn't domoticz doing the prediction calculations? if so how can i send data without the prediction value to domoticz.

I'm using a MS5611 sensor (many decimals on pressure) but it doesn't give prediction
it would be nice with more decimals in history thou. it only saves with 1 decimal. sensor gives 4.
2 decimals would give less stepping

**Comment by gizmocuz** [comment]
You are responsible for sending correct values to domoticz
But good you got it working...

If it is a Temp+Baro sensor, then you should send it as a temp baro (see the wiki/json implementation of this)

**Comment by xztraz** [comment]
thanks for the help. well as i said the temp sensor reads an uninteresting value therefor i don't want to send it since i can't filter it out in the domoticz end. but i'll just have to redo the sensor a bit so the temp readings are correct.  what i understand from reading on pressure. the temp is important to for internal calculations.
