### ISSUE TITLE
about MQTT and Domoticz design

### ISSUE THREAD

**Issue by mqu** [domoticz/domoticz#2387]
hello all,

I am facing some difficulties to interface MQTT device to Domoticz. I can't understand why design has been done that way in Domoticz ? I suppose the right way should be something like in Home-Assistant (https://www.home-assistant.io/components/sensor.mqtt/) : 
- MQTT broker collects data from any device on network
- usually with MQTT protocol, data is published based on "path" ; no need to worry about Domoticz IDs
- data is transmitted as simple values not in complex JSON format : 1 path for 1 value

Domoticz configuration for MQTT should be : 
 - parameters to connect to an MQTT broker (server),
 - for each device : give mqtt path : for example : /home/device/heater/indoor/temp for indoor temperature of my home heater

I have never seen a standard to make auto-discovery of MQTT device. Home-Assistant has one. 

best regards.

edit : "Home-Assistant may have one"

**Comment by gizmocuz** [comment]
First use the forum, and second, it seems you are a happy home assistant user, so please continue to use that product if you are not happy about domoticz

**Comment by mqu** [comment]
what is the problem with this issue ?

**Comment by gizmocuz** [comment]
4,

1. you should use the forum, unless you are a developer that are willing and can contribute to the code
2. it is a very negative post
3. if you find home-assistant better, no need to make a commercial for this here, just use that platform
4. "I have never seen a standard to make auto-discovery of MQTT device. Home-Assistant has one." has nothing to do with your remark

Now remember this is an open source project made by developers in their free time.

You can always use node-red if you want to parse the json data
Why on earth do we need to send out 10 different messages to a client when all can be done in one json object ?
Yes it is a choice of implementation, maybe if you can code, you could make a option to output it in another way

**Comment by mqu** [comment]
OK, but : 
- I have an account on github, no account on domoticz forum
- I will never use either domoticz and home-assitant,
- I can't understand the way my post is really negative : remember, English is not my mother tong. We can continue to discuss in french.
- Home-Assistant seems to be more is the design and principle of MQTT than Domoticz ; this is a fact.  My purpose was just to point you about that design.
- I have writen a MQTT gateway for my Viessman heater. With that gateway I can connect MQTT client without need to write any line of code : just need to configure and use. There  is many MQTT client with nice GUI under Android and cloud.

best regards.

**Comment by mqu** [comment]
en français : je ne te remercie pas du tout pour ton ouverture et ton accueil.

mon intention est juste de remonter auprès de votre communauté que la façon que vous avez d'utiliser MQTT me semble assez étrange. L'écosystème MQTT va certainement aller grandissant. La communauté toute entière Domoticz aurait à y gagner en utilisant MQTT d'une manière plus standard.

sachez que je n'utilise aucun des 2 logiciels : ni Domoticz et ni Home-Assistant. Si je me permet de faire une remarque sur ce forum, c'est bien parce que j'ai une demande de support qui me concerne (interface viessman-mqtt) en lien avec Domoticz. Quand un utilisateur est perdu, j'essaie de l'aider.

bien cordialement.

**Comment by gizmocuz** [comment]
Okey, it is a language issue.
When you created this issue, it was stated in the message that you have to use the forum
Could you point me to such a niece client for Android ?
Is there a specification (written document) for this kind of MQTT implementation ? If yes, then we could maybe add an option for it.
That said again, as you probably know how MQTT works, when we want to have all parameters for a sensor available, we need to send 10 broadcasts per sensor... that is to much

**Comment by mqu** [comment]
- about MQTT GUI : https://www.hivemq.com/blog/seven-best-mqtt-client-tools 
- cloud : Cayenne + MQTT : https://mydevices.com/cayenne/features/api/
- Android : https://play.google.com/store/search?q=mqtt&c=apps&hl=fr (MQTT Dashboard).

**Comment by gizmocuz** [comment]
Thanks, but can you point to a document that describes how MQTT sensor values should be send ? Like a standard

**Comment by mqu** [comment]
here is some command I can send with a bash script to my MQTT gateway.
```
# subscribe to any value publish on MQTT broker :
mosquitto_sub -u marc -P passwd  -h localhost -v -t "#"
v1/home/objects/viessman/data/temp/indoor 19.1
v1/home/objects/viessman/data/temp/outdoor 14.1
v1/home/objects/viessman/data/temp/boiler 30
v1/home/objects/viessman/data/temp/hot-water 39
v1/home/objects/viessman/data/temp/gaz 19
...
v1/objects/viessman//data/temp/indoor 19.4
v1/objects/viessman//data/temp/outdoor 14.8
v1/objects/viessman//data/temp/boiler 32
v1/objects/viessman//data/temp/hot-water 47
v1/objects/viessman//data/temp/gaz 33
v1/objects/viessman//data/settings/power/value 2.0
v1/objects/viessman//data/settings/temp/hot-watter 50.0
v1/objects/viessman//data/settings/temp/room/normal 19.0
v1/objects/viessman//data/settings/temp/room/low 14.0
v1/objects/viessman//data/settings/party-mode 0.0
v1/objects/viessman//data/stats/kwh/yesterday 20.83
v1/objects/viessman//data/stats/kwh/this-month 723.49
...

# what is indoor temperature ?
mosquitto_sub -u marc -P passwd  -h localhost -v -t "v1/objects/viessman//data/temp/indoor"
v1/objects/viessman//data/temp/indoor 19.4

# modify indoor temperature setting
mosquitto_pub -u marc -P passwd  -h localhost  -t "v1/objects/viessman//data/settings/temp/room/normal" -m  18
```
hope this help. Usually, MQTT topics are ordered hierarchically. You can subscribe to them with regular expressions (wildcards).

No need to make polling with MQTT : you are notified when a value has changed. No need to worry about network and CPU overload.

**Comment by mqu** [comment]
here is how Jeedom-MQTT configuration is done here : https://projetsdiy.fr/jeedom-mqtt-objets-connectes-domotique-diy/

1. configure  MQTT broker acces
2. for each sensors, we just need to enter sensor topic.

and voila.

**Comment by mqu** [comment]
please could you re-open this ticket ?

**Comment by mqu** [comment]
https://dzone.com/articles/mqtt-for-iot-communication :+1: 
The Topic

Every MQTT communication relies on the concept of “The Topic.” A single unique topic defines a unique pipeline, or connection between publishers and subscribers. Essentially, if the topic of the message published matches the topic subscribed, the subscriber gets the message. As simple as that!

It gets better. MQTT even allows hierarchies to be defined within its topics. Hierarchy levels are separated by a slash. For example, a topic for sending temperature in your living room could be “house/living-room/temperature”. This basically defines the hierarchy as “temperature is the child of living-room, which is the child of house”. This can be done for other rooms too, like “house/kitchen/temperature”, “house/bedroom/temperature”.

Moreover, you can also subscribe to multiple sensors using something called wildcards. There are two wildcards, “+” and “#”. The plus sign is a single level wild card that only allows arbitrary values for one level of the hierarchy while the hash sign allows data to come in from all underlying hierarchy levels.

**Comment by mqu** [comment]
https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices

Use specific topics, instead of general ones

When naming topics it is important not to use them like a queue, for example using only one topic for all messages is a anti pattern. You should use as specific topics as possible. So if you have three sensors in your living room, you should use topics myhome/livingroom/temperature, myhome/livingroom/brightness and myhome/livingroom/humidity, instead of sending all values over myhome/livingroom. Also this enables you to use other MQTT features like retained messages, which we cover in one of the next posts.

**Comment by mqu** [comment]
interesting links : 
- http://wiki.mqopen.org/doku.php ; topic standardization ? : http://wiki.mqopen.org/topics
- https://hackaday.io/project/7342-mqopen/log/33302-mqtt-topic-structure-redesign
- IOT hardware devices supporting MQTT : https://ubidots.com/docs/devices

may edit multiple times.

**Comment by gizmocuz** [comment]
Sorry, in non of the documents i found what i was looking for. (a kind of standard)

For each device we have more then 10 things to tell, sure for you only 1 thing could be important, for others other parameters.
We do not want to send all them separate to a broker... it gets flooded, specially when you have lots of devices. 

So this is what could be an option, but we really have to discuss this with other users/developers.

We already have a push mechanism, that can push certain values from a sensor to something.. (fibaro,http,influx,...)

For example, take a temp+hum+baro device, it has 3 sensors, if you go to Setup->Push->Fibaro (for example) you can select this device, and say, i want the 'temperature' to be pushed as 'temp' to the fibaro.

For MQTT, instead of specifying a 'target' variable (as you mention), it would be easiest for the users to not have to choose the target variable, but internally we use 'Temperature', or a conversion table so it the target becomes 'temp'
This way, the users can choose what to 'use/push' from a sensor.
We know the values types anyway of course

Instead of manually selecting what values to send, we can also do this automatically.
But that will mean for the above device example we will push to MQTT the following data:

Temperature
Humidity
Humidity Status
Barometer
Forecast 

These are 5 messages

That is, if you subscribe to #

But there are more things to tell that are of much interest to other users:

ID
Type
SubType
MeterType/SwitchType
raw values
Last Received
...
..
^the list goes on

Now we send it as JSON

That your final client can not translate JSON and pick out a value, well... maybe the could implement that ??
Another option is to use Node-Red (as already mentioned), where you will be able to subtract the values you want from the JSON and do whatever it is you want to do with it (even send it to MQTT again in your own topics)

**Comment by mqu** [comment]
never mind : I don't use Domoticz and I will never use it. If any user can help for a better MQTT integration, this is the place where to discuss of.

using Node-Red as a MQTT gateway seems a little overloaded for me. Using this extra software give user extra complexity. Perhaps it is the good way for you, this is not my point of view.

best regards.

**Comment by gizmocuz** [comment]
@mqu, So that is why i proposed the 'other' way we could do it so you will get topic/sensor/temp kind of messages.
But if you never will use domoticz or any of the other mentioned home automation applications, then why are you here ?
Or you only need a gateway ? Then ask your MQTT client to be able to pass JSON messages, not that complicated.
Antway, closing issue... ohhh it was already closed.
Bye

**Comment by livello** [comment]
@gizmocuz  This is exactly what I faced with. 
Usecase: wifi-relay that controls over mqtt bus. Wifi-relay must subscribe to domoticz/out then parse every message from domoticz (tens or hundreds per minute in big system) and check idx parameter. It would cost a lot of CPU-time and a lot of traffic. 
I know a workaround - setup bash script and send openhab-like messages to mqtt every relay changing. 
It's first and very simple problem. But if I go further with automatization, there would be more of that stuff.

**So  it 's very strange that you see advantages with using heavy flat json messages and don't see realy awful disadvantages.** 

Is there a way to make mqtt messages simpler and multilevel (openhab-like)? Or I need to make some sort of translator?

**Comment by gizmocuz** [comment]
@livello , it's a matter of design. And please note that i am very strange!
Have you read my from the 14th of May ?
that will push it to somechannel/kitchen/temperature/20.3, somechannel/kitchen/humdity/65.3 ...
