### ISSUE TITLE
Http actions saved and/or displayed without URL encoding in selector switch and they don't work

### ISSUE THREAD

**Issue by balintkozma** [domoticz/domoticz#2389]
Ver: V3.9417

Saving an URL encoded http action in a selector switch removes URL encoding.

Original URL:
http://127.0.0.1:9090/json.htm?type=command&param=switchlight&idx=1&switchcmd=Set%20Level&level=0

After saving and re-opening the selector switch:
http://127.0.0.1:9090/json.htm?type=command¶m=switchlight&idx=1&switchcmd=Set Level&level=0

&para -> ¶, %20 -> [space]

And it doesn't work:
2018-05-14 17:39:39.584 Error: Error opening url: http://127.0.0.1:9090/json.htm?type=command&param=switchlight&idx=1&switchcmd=Set Level&level=0

**Comment by gizmocuz** [comment]
Set Level with a level of 0... should this not be Off instead ?
Made some changes, could you test beta 9440 ?

**Comment by balintkozma** [comment]
Yes, good point, it is a shutter actually, and all the other level values I want to set fail the same way.
Tested with 9440, it is the same.

**Comment by gizmocuz** [comment]
Can you clear your browser cache and appcache (two different things) and try again ?

**Comment by balintkozma** [comment]
&para is now escaped well, but the %20 space problem is still there, still cannot execute the action because of this.

Tried with clearing browser cache, incognito mode, even in a different browser.

**Comment by gizmocuz** [comment]
Okey, so what you type in the edit box, is now correctly displayed ?
If yes, remove the %20 and just add a space, is it working then ?
This seems to be two different issues, i would like to have the first one fixed and then move to the second ;)

**Comment by balintkozma** [comment]
Ok.
1. click on 'Edit' on the selector switch
2. on the 'Selector Actions' click on the pencil icon
3. put there an URL encoded URL, containing %20
4. click on 'Save' on the dialog
5. the %20 is displayed well in the 'Selector Actions' table
6. click on Save under the description field, that saves the whole selector switch
7. click on 'Edit' again
8. %20 is not there, only space

The URL cannot be executed (when I click on the buttons on the selector switch), no matter if I use %20 or space. (because it ends up space always)

Looking at your commit, the escapeHTML doesn't look for %20 to escape.

**Comment by gizmocuz** [comment]
My commit was about making the table row non-html, i will need to investigate the 2nd problem

**Comment by gizmocuz** [comment]
Debugging SQLHelper.cpp, line 4260, the on/off actions are url-decoded, and i get a good string

OnAction = CURLEncode::URLDecode(GetSelectorSwitchLevelAction(BuildDeviceOptions(Options, true), llevel));

"http://127.0.0.1:9090/json.htm?type=command&param=switchlight&idx=1&switchcmd=Set Level&level=0"

So at 'CSQLHelper::HandleOnOffAction' it is still correct

At line 3162, it is still the url above

My domoticz runs on port 8080, so i get a HTTP error:

**2018-05-15 18:54:22.734  Error: Error opening url: http://127.0.0.1:9090/json.htm?type=command&param=switchlight&idx=1&switchcmd=Set Level&level=0**

Still OK, now i will change the url to port 8080, and debug the webserver and see what is received:

As you see no issues:

![image](https://user-images.githubusercontent.com/2265299/40071673-c0ed82fc-5871-11e8-8c81-8865c3dfcb0b.png)


%20 should also not be there, as mentioned above, you should also do a normal space.
We do not ask users to urlencode what they type... that would be complicated

**Comment by balintkozma** [comment]
Then how do I hold it wrong?

It tried the URLs with curl, is this relevant?

![screenshot from 2018-05-15 19-14-58](https://user-images.githubusercontent.com/15109984/40072478-48ed78b8-5874-11e8-9197-0de8790b909d.png)

**Comment by gizmocuz** [comment]
with 'curl' you might need to escape html, but in domoticz not
does the domoticz log say anything when you press the selector button ?

**Comment by balintkozma** [comment]
Only that error opening url I wrote in the initial message. 
![screenshot from 2018-05-17 19-02-11](https://user-images.githubusercontent.com/15109984/40192500-dac45626-5a04-11e8-8602-ce430b5e0e17.png)
How can I setup the debugging environment that you use?

**Comment by gizmocuz** [comment]
Okey, could you tell me:
- the platform you run domoticz on (raspberry ? stretch)
- the domoticz version (latest beta i suppose)
- if you replace the url with https://www.google.com it is working ?

**Comment by balintkozma** [comment]
I run it on raspbian stretch, I compile it from the development branch on the pi, because I use patched openzwave.
https://www.google.com isn't working either (Error opening url), it might be a compilation issue?

**Comment by gizmocuz** [comment]
It could be you are linking against an old openssl library
Can you try the beta binary?

**Comment by balintkozma** [comment]
With beta binary it is the same with my URL, but it is ok with https://www.google.com

![screenshot from 2018-05-18 14-50-36](https://user-images.githubusercontent.com/15109984/40235707-5ddafd48-5aab-11e8-9895-304a3248255e.png)

**Comment by gizmocuz** [comment]
Okey, staying on the binary beta, with your url, the error is they same ?
What happens when you enter http://127.0.0.1:9090 ? You domoticz runs on port 9090 right ?
Did you put 127.0.0.1 in your local networks in the settings (this is default)

**Comment by balintkozma** [comment]
http://127.0.0.1:9090 is OK. Yes, my domoticz runs on 9090. 127.0.0.* is in the local networks.
Outside domoticz the long URL still  works with curl and %20, as with the compiled domoticz.

**Comment by balintkozma** [comment]
This is OK with the selector switch:
http://127.0.0.1:9090/json.htm?type=command&param=switchlight&idx=1&switchcmd=Off

It has to be the space.

**Comment by gizmocuz** [comment]
I still (with debugging) see no issues.
Could you add a dummy hardware (if not already), add a switch.
Edit the switch, set it as a dimmer
go to the devices overview, find this switch, write down the IDX value (lets day 123)

then in the selected switch for the "OFF" action (for example) enter

http://127.0.0.1:9090/json.htm?type=command&param=switchlight&idx=123&switchcmd=Set Level&level=0

**Comment by gizmocuz** [comment]
It was a bit more... could you try beta 9464?

**Comment by balintkozma** [comment]
beta 9464 is working as it should:
When I use Set%20Level, then it remains Set%20Level after re-opening, and the URL works.

But it has a side effect on the dashboard:
![screenshot from 2018-05-22 17-02-06](https://user-images.githubusercontent.com/15109984/40371257-59e76764-5de2-11e8-93e1-9ed3707cbc52.png)

This is a virtual selector switch, created with 'Create Virtual Sensors' button on the Dummy hardware

**Comment by gizmocuz** [comment]
Sorry, forgot the dashboard... moment!

**Comment by gizmocuz** [comment]
Should be correct in beta 9468

**Comment by balintkozma** [comment]
It is! Thanks for the support!
