### ISSUE TITLE
API: creating a device results in ERR answer

### ISSUE THREAD

**Issue by sineverba** [domoticz/domoticz#2392]
Domoticz v is 3.8153.

I did write my custom API php wrapper.

I'm tryng to add a new Selector Switch under a Dummy Hardware with idx = 4, but I got "ERR".

My custom call is present also here https://github.com/sineverba/domoticz-api/blob/v1.0.2-alpha/src/Client.php

but, basically, is, per API documentation

`/json.htm?type=createdevice&idx=4&sensorname=prova&devicetype=50&devicesubtype=5`

Where, idx is real (this is my Dummy Hardware).

I pass `0XF4` per `$type` and `0X3E` per `$subtype`, converted by `hexdec` php function.

I did try also with example reported on documentation, getting the ERR.

Another question. After a successfull Selector Switch creation, how can I remove all values and insert my custom levels? Cannot find anything on the doc.

Thank you

**Comment by gizmocuz** [comment]
Please use the forum.
If you open the chrome developer console, and open the network tab, then create the dummy sensor from the native domoticz hardware page, you see the URL that is being called
