### ISSUE TITLE
[FR] Mysensors smartSleep

### ISSUE THREAD

**Issue by Lyr3x** [domoticz/domoticz#2394]
I think the smartSleep feature is not yet implemented. It will be very helpful to create battery powered nodes with smartSleep. Sometimes i want to change a value of a node from Domoticz, which is not working at the moment.

https://www.mysensors.org/apidocs/group__MySensorsCoregrp.html#gad9e11c9a491940337f7354f553391f2f

https://www.mysensors.org/download/sensor_api_20#sleeping

**Comment by gizmocuz** [comment]
This is quite interesting... going to have a peak on this in the weekend !

This is something new from the latest MySensors core and there are two new messages:

	I_PRE_SLEEP_NOTIFICATION	= 32,	//!< Message sent before node is going to sleep
	I_POST_SLEEP_NOTIFICATION	= 33	//!< Message sent after node woke up (if enabled)

**Comment by Lyr3x** [comment]
That will be awesome!

**Comment by gizmocuz** [comment]
Do you know how this is going to work ?
Let's say the node signals it is going to sleep... 
And for some reasons domoticz needed to send some commands to the node like
- Switch On
- Switch Off
- Update text sensor
...
(Multiple messages)

When the node signals that it is awake again, we need to send those messages
How long does the node stay awake ?
How many messages van we send ?
What should be a good delay (milliseconds) between the messages transmitted to the node ?

**Comment by gizmocuz** [comment]
Think it is now implemented.
Plz try beta  9453 or higher, interested in your findings...

**Comment by Lyr3x** [comment]
Well thank you for your fast support and the extrem fast implementation. I will try this later today or tomorrow and give you feedback.

**Comment by Lyr3x** [comment]
I switched one device from sleep to smartSleep, which results in no sleep at all:

`
#define SLEEP_TIME 0
#define DIGITAL_INPUT_SENSOR 3
sleep(digitalPinToInterrupt(DIGITAL_INPUT_SENSOR), RISING, SLEEP_TIME);
`
changed to
`smartSleep(digitalPinToInterrupt(DIGITAL_INPUT_SENSOR), RISING, SLEEP_TIME);`

**Comment by gizmocuz** [comment]
Welll ehh yes, try setting the SLEEP_TIME to 10000 (it is in milliseconds 10000 = 10 seconds)

**Comment by Lyr3x** [comment]
Setting the time to 0 should result in sleeping until waking up through  the Interrupt. I will check the Return value to see whats happening. I think i'll get an MY_SLEEP_NOT_POSSIBLE

**Comment by gizmocuz** [comment]
Thanks. (Domoticz can not fix this issue ;)

**Comment by Lyr3x** [comment]
I know ;) 
https://github.com/mysensors/MySensors/issues/1038 this is the cause for my problem.
When setting a fix sleeptime the feature is working fine 👍 Thank you.

**Comment by MarcusKlerks** [comment]
@gizmocuz 
Thanks for this implementation and it works... but only sometimes:(. It feels like being lucky when it works but I cannot get reliable results.

Could it be that in the implementation you have to reverse the order? As stated in the referenced description "send heartbeat and process incoming messages before going to sleep" the processing of any waiting (or even incoming) messages should be processed BEFORE going to sleep and thus after the I_PRE_SLEEP_NOTIFICATION. To further support I have also seen that the MY_SMART_SLEEP_WAIT_DURATION_MS (time for execution of messages) is the wait period before going to sleep. 
What do you think?
Mark
