### ISSUE TITLE
[EnOcean] Adds hardware but not device on tables

### ISSUE THREAD

**Issue by EdddieN** [domoticz/domoticz#2397]
Using V3.9458 on RPI

Adding an EnOcean device with 3 metrics: Temperature, Humidity and Co2 adds the device to the DB but not the sensors. 

Adding device:
2018-05-19 11:54:13.060 EnOcean: 01 (0A/07) A5 24 20 3C 80 05 03 D5 8E 00 01 FF FF FF FF 30 00
2018-05-19 11:54:13.060 EnOcean: destination: 0xffffffff RSSI: 52
2018-05-19 11:54:13.060 EnOcean: 4BS data: Sender id: 0x0503d58e Status: 00 Data: 3c
2018-05-19 11:54:13.060 EnOcean: 4BS, Variant 2 Teach-in diagram: Sender_ID: 0x0503D58E
2018-05-19 11:54:13.060 Manufacturer: 0x3c (CLOUD_BUILDINGS_LTD)
2018-05-19 11:54:13.060 Profile: 0x09
2018-05-19 11:54:13.060 Type: 0x04 (GasSensor.04)
2018-05-19 11:54:13.060 EnOcean: Sender_ID 0x0503D58E inserted in the database
2018-05-19 11:54:18.731 EnOcean: 01 (0A/07) A5 6C 61 62 0E 05 03 D5 8E 00 01 FF FF FF FF 33 00
2018-05-19 11:54:18.731 EnOcean: destination: 0xffffffff RSSI: 49
2018-05-19 11:54:18.731 EnOcean: 4BS data: Sender id: 0x0503d58e Status: 00 Data: 62
2018-05-19 11:55:16.769 EnOcean: 01 (0A/07) A5 24 20 3C 80 05 03 D5 8E 00 01 FF FF FF FF 37 00
2018-05-19 11:55:16.769 EnOcean: destination: 0xffffffff RSSI: 45
2018-05-19 11:55:16.769 EnOcean: 4BS data: Sender id: 0x0503d58e Status: 00 Data: 3c
2018-05-19 11:55:16.769 EnOcean: 4BS, Variant 2 Teach-in diagram: Sender_ID: 0x0503D58E
2018-05-19 11:55:16.769 Manufacturer: 0x3c (CLOUD_BUILDINGS_LTD)
2018-05-19 11:55:16.769 Profile: 0x09
2018-05-19 11:55:16.769 Type: 0x04 (GasSensor.04)
2018-05-19 11:55:16.769 EnOcean: Sender_ID 0x0503D58E already in the database
2018-05-19 11:56:04.403 EnOcean: 01 (0A/07) A5 7C 82 67 0E 05 03 D5 8E 00 01 FF FF FF FF 3D 00
2018-05-19 11:56:04.403 EnOcean: destination: 0xffffffff RSSI: 39
2018-05-19 11:56:04.403 EnOcean: 4BS data: Sender id: 0x0503d58e Status: 00 Data: 67

Looking at DB, device hardware is there:
sqlite> SELECT * FROM EnoceanSensors ;
ID|HardwareID|DeviceID|Manufacturer|Profile|Type
1|3|0503D58E|60|9|4

However requesting device sensors returns nothing:
sqlite> select * from DeviceStatus where HardwareID = 3;
sqlite> 

The hardware I'm using is this one:
http://www.pressac.com/enocean-co2-sensor-temperature-and-humidity

**Comment by gizmocuz** [comment]
Could you check if 'Accept new Hardware' is enabled in the settings ?

**Comment by EdddieN** [comment]
Hello,

Yes it is (permanently), tried even with a fresh new install using ESP3.

I can send you a device if it helps.

**Comment by EdddieN** [comment]
Right, trying to get my head around it, and have almost non existent knowledge of C++ but happy to give it a try. This is so far what I'm seeing by looking at ESP2 and ESP3.cpp files.

The sensor is identified as a Type: 0x04 (GasSensor.04) which has TH + RH + Co2, however looking at ESP3.cpp, a decoder like this:

> 1360					else if (szST == "LightSensor.01")

is missing.

I can imagine I need to do something like this (from ESP3):

> 1459 				else if (szST.find("TempHum")==0)
> 					{
> 						//(EPP A5-04 01/02)
> 						float ScaleMax = 0;
> 						float ScaleMin = 0;
> 						if (iType == 0x01) { ScaleMin = 0; ScaleMax = 40; }
> 						else if (iType == 0x02) { ScaleMin = -20; ScaleMax = 60; }
> 						else if (iType == 0x03) { ScaleMin = -20; ScaleMax = 60; } //10bit?
> 
> 						float temp = GetValueRange(DATA_BYTE1, ScaleMax, ScaleMin,250,0);
> 						float hum = GetValueRange(DATA_BYTE2, 100);
> 						RBUF tsen;
> 						memset(&tsen,0,sizeof(RBUF));
> 						tsen.TEMP_HUM.packetlength=sizeof(tsen.TEMP_HUM)-1;
> 						tsen.TEMP_HUM.packettype=pTypeTEMP_HUM;
> 						tsen.TEMP_HUM.subtype=sTypeTH5;
> 						tsen.TEMP_HUM.rssi=12;
> 						tsen.TEMP_HUM.id1=ID_BYTE2;
> 						tsen.TEMP_HUM.id2=ID_BYTE1;
> 						tsen.TEMP_HUM.battery_level=9;
> 						tsen.TEMP_HUM.tempsign=(temp>=0)?0:1;
> 						int at10=round(std::abs(temp*10.0f));
> 						tsen.TEMP_HUM.temperatureh=(BYTE)(at10/256);
> 						at10-=(tsen.TEMP_HUM.temperatureh*256);
> 						tsen.TEMP_HUM.temperaturel=(BYTE)(at10);
> 						tsen.TEMP_HUM.humidity=(BYTE)hum;
> 						tsen.TEMP_HUM.humidity_status=Get_Humidity_Level(tsen.TEMP_HUM.humidity);
> 						sDecodeRXMessage(this, (const unsigned char *)&tsen.TEMP_HUM, NULL, -1);

However on ESP2.cpp I can see there's a "GasSensor.04"  definition, but seems not right for this sensor. 

I had a look at the specs of the device I'm trying to use:
Example packet in Domoticz log from ESP3 for a "GasSensor.04":
EnOcean: 01 (0A/07) A5 51 39 7B 0E 05 03 D5 8E 00 01 FF FF FF FF 2D 00

Data bytes decode for 4BS telegram RORG=A5, FUNC=09, TYPE=04 (Domoticz sensor "GasSensor.04")

> DB3 = Humidity in 0.5% steps, 0...200 -> 0...100% RH (0x51 = 40%)
> DB2 = Concentration in 10 ppm steps, 0...255 -> 0...2550 ppm (0x39 = 570 ppm)
> DB1 = Temperature in 0.2C steps, 0...255 -> 0...51 C (0x7B = 24.6 C)
> DB0 = flags (DB0.3: 1=data, 0=teach-in; DB0.2: 1=Hum Sensor available, 0=no Hum; DB0.1: 1=Temp sensor available, 0=No Temp; DB0.0 not used)

data decode info taken from EnOcean profiles doc at https://www.enocean-alliance.org/eep/

so I think I can decode it, but how do I map it onto Domoticz? Do I map it as THRH and then an external Co2? A bit of guidance would help if possible.

**Comment by EdddieN** [comment]
Hello,
With the help of a friend we managed to get it to work by editing the ESP3 file. Is it safer to attach the file here? never used github before

**Comment by gizmocuz** [comment]
Great work !!
No please proceed as follow:

- for windows i use tortuisegit, you get a right mouse menu in the explorer

- backup your modified file somewhere (just in case)
- go to the github domoticz code page, on the top right you see a button "Fork" press this button to fork it on your own repository (account)
Go to your own repo, checkout domoticz, make the changes (copy the backup file from above in your source folder)
Then commit your changes, and then push your changes
Next go back to your github account, domoticz fork
You will now see a button, "Make pull request", press this button and make a PR
Now we can merge/review the changes
If there is a need to make modifications before we merged it, you can just keep commiting/pushing to your fork

**Comment by EdddieN** [comment]
Ok, I have done it via web directly (no tortuisegit for mac), hopefully I got it right:
https://github.com/domoticz/domoticz/pull/2424

**Comment by gizmocuz** [comment]
Excellent !
