### ISSUE TITLE
New Aqara cube seems not to work

### ISSUE THREAD

**Issue by 1981nick1982** [domoticz/domoticz#2398]
In #2393 I have inserted  the new Aqare cube because it gave an error (XiaomiGateway: unhandled model: sensor_cube.aqgl01) 

The error message has disappeared but there is still a problem that it can not be found in the list of devices. However, I see the appropriate device in the log file.

2018-05-18 20:49:09.879 {"cmd":"heartbeat","model":"sensor_cube.aqgl01","sid":"...","short_id":..."data":"{\"voltage\":2975}"}

**Comment by 1981nick1982** [comment]
The problem is still there after the adjustments I made. #2399

**Comment by gizmocuz** [comment]
Did you enable 'accept new hardware' in the settings ?

**Comment by 1981nick1982** [comment]
Yes it is on. other xiaomi devices just work. There are more people on the domoticz forum that have the same problem.

**Comment by gizmocuz** [comment]
Could you add a link to the forum ?
You made the code changes in domoticz ?

**Comment by 1981nick1982** [comment]
Here is the link to the forum:
https://www.domoticz.com/forum/viewtopic.php?f=6&t=23457&sid=727ef10698b940be6e3dd836c32bcfb8

The problem is also present in Home Assistant, and has to do with a new protocol of the cube. Several tests show that the gateway does not send information of the new cube to the outside, except for the battery status.

See:
https://github.com/home-assistant/home-assistant/pull/14393

**Comment by sirs2k** [comment]
Well I just got my cube model MFKZQ01LM which is supposed to be supported.
the cube is getting detected by HA, I can see the cube's battery percentage but no actions from the cube are getting sent to HA.
But my cube has the Aqara logo on it, not sure if the Original MI cube and the new Aqara cubes could have the same MFKZQ01LM number?

**Comment by gizmocuz** [comment]
From what i can read above, there seems to be a protocol change, and it has to be implemented by someone with a cube (i dont have a cube)

Is it this one ?

https://www.aliexpress.com/item/Xiaomi-Mi-Magic-Cube-Controller-Zigbee-Version-Controlled-by-Six-Actions-For-Smart-Home-Device-work/32812410838.html

The page says you also need " Match with Xiaomi multifunctional gateway to use" do we need a gateway as well ?

Will this also work with

https://www.aliexpress.com/item/Original-Xiaomi-Mi-Smart-WiFi-Socket-Zigbee-Version-APP-Remote-Control-Timer-Power-Plug-Power-Detection/32843331455.html

https://www.aliexpress.com/item/Original-Xiaomi-AQara-Smart-Temperature-Humidity-Sensor-ZigBee-Wifi-Wireless-Work-With-xiaomi-smart-home-mijia/32853631922.html

https://www.aliexpress.com/item/Original-Xiaomi-Aqara-Smart-Window-Door-Sensor-Intelligent-Home-Security-with-ZigBee-Wireless-Connection-Mi-Home/32850876709.html

Thinking about investing i some Xiaomi hardware to help with development

**Comment by gizmocuz** [comment]
Can anyone response on the above message ? Else i can not start development (and it will take a few weeks to receive the hardware)

**Comment by 1981nick1982** [comment]
Yes, that's the cube. The other products you show also works with the gateway. I have been using the temperature sensor that you have there for a while in domoticz. You still need the gateway to get everything working. Get the idea that the gateway is the problem that does not transmit the signals from the cube. Now i'm now looking at an open platform where the gateway is no longer needed. I am waiting for the components for this. it works via mqtt so i think its also possible to get it working via domoticz. https://github.com/Koenkk/zigbee2mqtt

**Comment by gizmocuz** [comment]
@1981nick1982 , okey, but i do not understand the gateway part... the cube is not the gateway ?
Do you have a link to the gateway ?
If i understand correctly, the gateway works, but the new cube does not ?
Is it not better to adjust the code so the new cube will work instead of installing a separate daemon/process for this ?

**Comment by 1981nick1982** [comment]
The problem is that the gateway does register the data in the xiaomi app. But no data is sent to the outside over the cube. The new cube works via a new protocol. I think that the problem is located in the firmware of the gateway. 
In Home assistant the same problem is present. See link for the discussion about this: https://github.com/home-assistant/home-assistant/pull/14393

Here is a link to the gateway:
https://nl.aliexpress.com/item/Updated-Version-Original-Xiaomi-Mi-Smart-Multifunctional-Gateway-WiFi-Remote-Center-Control-16-Million-RGB-Lights/32830125805.html?

**Comment by salopette** [comment]
is there anything new about the Aqara Cube?

**Comment by Nemesis24** [comment]
It seems work here

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/611

**Comment by pipiche38** [comment]
There is a big difference I think between the dresden-elektronic/deconz-rest-plugin and the current implementation in Domoticz, as for Domoticz this is going via the Xiaomi gateway, except if you are using the Zigate plugin.

**Comment by Nemesis24** [comment]
I understand but they seems use 
lumi.sensor_cube.aqgl01 
Domoticz use
Sensor_cube.aqgl01

**Comment by RezzZ** [comment]
just updated my bridge to 1.4.1_15**7**.0143 and the aqara cube is now available in domoticz as device!

it's confirmed here too:
https://www.domoticz.com/forum/viewtopic.php?f=6&t=23457&sid=cd3c1f5207222c9c156917db40587e3e&start=20

so this issue can be closed

**Comment by DarkAllMan** [comment]
Seems that ROTATE is not detected!
It is via Mi Home App, but not in domoticz

**Comment by RezzZ** [comment]
rotate works just fine in my domoticz.

**Comment by DarkAllMan** [comment]
Really, what version are you on?

**Comment by RezzZ** [comment]
4.9999 (beta because of the bug with philips hue bridge not working properly is last stable)

**Comment by DarkAllMan** [comment]
And which Bridge Firmware?

**Comment by RezzZ** [comment]
1.4.1_157.0143

**Comment by DarkAllMan** [comment]
ok, I will test going back to latest stable and see if that solves my issue.

**Comment by den2487** [comment]
> ok, I will test going back to latest stable and see if that solves my issue.

what result? very interesting
buy or not to buy this cube for domoticz?

**Comment by RezzZ** [comment]
depends on how you want to use it. But as I mentioned before, the device works now in domoticz

**Comment by DarkAllMan** [comment]
It works for me yes :)

**Comment by den2487** [comment]
> depends on how you want to use it. But as I mentioned before, the device works now in domoticz

i want  use it like a switch for light in the different rooms,  i think, i need to buy and test it.

**Comment by waltervl** [comment]
Fixed, issue can be closed
