### ISSUE TITLE
Evohome temporary setpoints not reported

### ISSUE THREAD

**Issue by dwmw2** [domoticz/domoticz#240]
When the normal schedule is overridden on the controller and a new temperature set point given for a zone, this is reported as such:

```
2015-12-01 14:50:58 095 RQ --- 18:002668 01:063863 --:------ 2349 001 02 ()
2015-12-01 14:50:58 045 RP --- 01:063863 18:002668 --:------ 2349 013 02089804FFFFFF0012010C07DF (�����)
2015-12-01 14:50:58 evohome: ZONE_SETPOINT_MODE: Setting: 3: 2200 (0=Auto) 2015-12-01 18:00
```

However, we don't seem to report that. It's just marked as 'Normal'.

I'm fairly sure this _used_ to work at some point when I was first trying to set things up, but I couldn't say what version that was with.

**Comment by gizmocuz** [comment]
could you make a patch?

**Comment by gizmocuz** [comment]
no feedback, please use the forum, maybe the original evohome author can respond

**Comment by dwmw2** [comment]
Yeah, sorry for the delay. Got distracted by other things (monitoring oil tank: http://www.domoticz.com/wiki/Lua_-_Oil_Tank_Monitor ). Realistically speaking, I'll probably end up fixing the issues with the volume "sensor" before I get round to further improvements on the Evohome side which are basically cosmetic. Not to mention Real Work™.
