### ISSUE TITLE
Selector switch : html actions with special characters

### ISSUE THREAD

**Issue by pepsi92** [domoticz/domoticz#2402]
Hi,

First, thanks to all the contributors for this great product ! :)

I'm trying to integrate domoticz with my Sonos environment using the node-sonos-http-api (using the following tutorial : https://www.domoticz.com/forum/viewtopic.php?f=38&t=10940) but I encounter somethging I think may be an issue. 

My environment is : 
- Domoticz 3.9439 running on a Synology
- NodeJS v8 (node 8.9.4)
- node-sonos-http-api v1.6.0
- Sonos environment with only one room named "Séjour" (note the uppercase "S" and the "é")

So as described in the tutorial, I've created a dummy HW and an associated selector switch with the following actions : 
![capture ecran 2018-05-21 a 17 22 22](https://user-images.githubusercontent.com/18167025/40315441-b3996360-5d1b-11e8-8076-3c385a56fa5c.png)

Now, when the buttons are used, a wrong URL is passed to the node-sonos-http-api. The "S" and "é" letters are wrongly converted. By example, when I use the Vol- switch, I get the following in node-sonos-http-api : 

> 2018-05-21T15:26:48.625Z INFO http server listening on 0.0.0.0 port 5005
> 2018-05-21T15:26:57.992Z ERROR 
>   { error: 'action \'sã©jour\' not found' }

Everything works fine when I send the exact same URL to the node-sonos-http-api using my browser.
Everything works fine when I rename the room to "sejour" in Sonos and Domoticz.
![capture ecran 2018-05-21 a 17 49 12](https://user-images.githubusercontent.com/18167025/40316682-60cddaea-5d1f-11e8-9f3d-c25824eee62f.png)

Any idea ?

KR,
Nicolas

**Comment by gizmocuz** [comment]
I changed the topic as it is not lowercase, but it's about the characters that are being used.
Will look into this

**Comment by gizmocuz** [comment]
Could you try beta 9464?

**Comment by pepsi92** [comment]
Great, thanks a lot for fixing this issue so quyickly !

I just installed 9469 and it is working now :)

**Comment by pepsi92** [comment]
If you agree, I will close the issue.

**Comment by gizmocuz** [comment]
Thanks for the feedback !
