### ISSUE TITLE
Xiaomi temp/humi/pressure sensor takes wrong values with a blockly.

### ISSUE THREAD

**Issue by prelude0000** [domoticz/domoticz#2403]
Temperature with blockly working fine but there is a bug with a humidity.

In graphs and DB humidity values are saved and used right but in blockly values are 1 or 3 (maybe some other but i have only seen those 2 values). I check values whit a "show current states" button and "write to log" block and both showing wrong values.

Clip from "show current states"

<clip>

> 64 | 20_Varasto_Huone_Temperature | 21.4 | 2018-05-21 22:02:44 | 21.4
> -- | -- | -- | -- | --
> 65 | 20_Varasto_Huone_Humidity | 1 | 2018-05-21 22:02:44 | 1
> 66 | 20_Varasto_Huone_Pressure | 1021.0 | 2018-05-21 22:02:44 | 1021.0
> 

</clip>

**Comment by gizmocuz** [comment]
That is because the 'Show Current Values' displays the sValue, and the humidity value is stored in the nValue in the database (i would have made this screen much more differently)
So the internal value is correct

**Comment by gizmocuz** [comment]
the sValue is for the status: normal (0), comfort (1), dry (2) and wet (3)

**Comment by gizmocuz** [comment]
Just tested with a "if hum>55 then write a debug log" and using the JSON api to update

http://127.0.0.1:8080/json.htm?type=command&param=udevice&idx=1096&nvalue=60&svalue=1

And it is working correctly, so it is only the displaying

**Comment by gizmocuz** [comment]
(Display will be a bit better in upcoming beta)

**Comment by gizmocuz** [comment]
@prelude0000 , could you check if the values are displayed correctly now ?

**Comment by prelude0000** [comment]
2018-05-23 22:35:38.938  Domoticz V3.9476 (c)2012-2018 GizMoCuz
2018-05-23 22:35:38.938  Build Hash: 0747e583, Date: 2018-05-23 16:11:16

show current states is now mutch better:
> 

64 | 20_Varasto_Huone_Temperature | 21.6 | 2018-05-23 22:36:34 | 0/21.6
-- | -- | -- | -- | --
65 | 20_Varasto_Huone_Humidity | 37 | 2018-05-23 22:36:34 | 37/1
66 | 20_Varasto_Huone_Pressure | 1018.0 | 2018-05-23 22:36:34 | 0/1018.0



In log side there is still that "1" and not 37. 

Blockly -> write to log <sensor name hum>
and this is what i see in log file:
2018-05-23 22:58:18.853 1

**Comment by gizmocuz** [comment]
Fixed in next beta version:

![image](https://user-images.githubusercontent.com/2265299/41099091-ca694fc0-6a5d-11e8-96f4-a5d3e468b293.png)

output:
![image](https://user-images.githubusercontent.com/2265299/41099111-d73c32da-6a5d-11e8-8867-d7b54db49342.png)
