### ISSUE TITLE
The different Daikin devices status are not updated 

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2410]
In case of a change via an other remote control, of any Daiking devices parameters, this is not reflected into the Domoticz Devices.

For instance if with the Daiking remote controller you power on or power off the AC, the corresponding Power Devices in domoticz is not updated accordingly.
This is the same for Mode, Fan rate and Fan direction

Information is available through a /aircon/get_control_info URL

**Comment by pipiche38** [comment]
Did some investigation while reading the code.
(1) The polling is done only every Daikin_POLL_INTERVAL 300  ( 300s / 15' ) which seems to be quiet long. 30'' or at least 1' would be more favourable to handle update done by an other controller.

(2) I tried to understand how the decoding is done, but my knowledge on cpp syntax is limited. But I did a test of reducing Daikin_POLL_INTERVAL to 30 (seconds), and there is no update done. So I suspect that the response of  `/aircon/get_control_info` is not processed correctly.
Should be somewhere in 
`CDaikin::GetControlInfo()` function on the section
` for (itt = results.begin(); itt != results.end(); ++itt)`

**Comment by gizmocuz** [comment]
Did you enable 'accept new hardware' under settings ?
Else it might be your username/password, please contact me on the forum (gizmocuz) and we can try to debug together. When i wrote this i tested online to another user, was working great

**Comment by pipiche38** [comment]
The Devices are already present in Domoticz, it is about polling information from the Daikin interface to the Domoticz devices.
I have currently identified that the Polling is set to 300s ( 15 minutes ) which seems to be quiet long. There is maybe a Domoticz needs for that, but I think 60s would be more acceptable.

I also started to instrument the code a bit in order to understand what is happening when update is needed.

Will come back with recommendation ;-)

**Comment by pipiche38** [comment]
Discussion on Forum is available here: https://www.domoticz.com/forum/viewtopic.php?f=34&t=23566

**Comment by pipiche38** [comment]
I think , I found the issue in the code. If I'm not mistaken the Switch name is hardcoded, while on my setup and because I have 3 Daikin hardware I have renamed them.

For instance , is the following is not hardcoding "Ventillation", "Winds", "Mode" and "Power"
```InsertUpdateSwitchSelector(6, true, 10, "Ventillation");
InsertUpdateSwitchSelector(7, true, 10, "Winds");
InsertUpdateSwitchSelector(5, true, 50, "Mode");
UpdateSwitchNew(1, -1, (results2[1][0] == '1') ? false : true, 100, "Power");
```

**Comment by gizmocuz** [comment]
300 seconds is 5 minutes
