### ISSUE TITLE
Xiaomi smart wall plug not detect consumption

### ISSUE THREAD

**Issue by DAVIZINH0** [domoticz/domoticz#2412]
Hello,
I install a xiaomi smart wall plug and domoticz detects it. Perfect!!

But onlye detect as switch, not consumption data.

The other xiaomi plug (not wall) cand detect the consumption.

Is this a bug?

thanks a lot

**Comment by AlbrtoSam** [comment]
I have exacly same issue. My device is a QBCZ11LM

**Comment by AlbrtoSam** [comment]
Any update on here?

**Comment by DAVIZINH0** [comment]
This problem solves with this issue:
https://github.com/domoticz/domoticz/issues/2470

Great work to @AlbrtoSam !!!!
