### ISSUE TITLE
Floorplan image is broken

### ISSUE THREAD

**Issue by MathijsG** [domoticz/domoticz#2413]
Updated to the latest beta, beta V3.9476.

I have an existing floorplan all set up with a floorplan file named 'plattegrond.gif' located in : 
/home/pi/domoticz/www/images/floorplans
![image](https://user-images.githubusercontent.com/529552/40452189-45b32fa8-5ee1-11e8-9330-274d3b476aa4.png)

However, I get an empty Floorplan page and when I get to the settings of the floorplan I see a broken image:

![image](https://user-images.githubusercontent.com/529552/40452171-398ac20e-5ee1-11e8-8251-ab5f8a5bd126.png)

Don't know any more relevant info you would need? looks like the path is somehow messed up?

**Comment by sweetpants** [comment]
There where some changes in this area. Floorplan images to database, but .gif is not supported when I look into the code. Only .jpg, .jpeg,.png and .bmp are supported

**Comment by KirillFedorov** [comment]
How can i change picture now?

**Comment by MathijsG** [comment]
Gif has worked for years, looks like just the path get's wrong, but the rendering of gif is just a browser thing if you ask me? And currently there looks no way to alter the image of an existing floorplan.

**Comment by sweetpants** [comment]
The change was that all floorplan images are now stored into the datatabase. For this domoticz search in your current floorplan path for the above mentioned file formats. .gif is not one of them, hence you don't see it anymore.

**Comment by sweetpants** [comment]
I have created a PR, just wait till it get's accepted and merged

**Comment by gizmocuz** [comment]
Gif was never supported as far as i know...

**Comment by sweetpants** [comment]
Hmm, MathijsG said it worked for years. But thanks for merging this PR

**Comment by MathijsG** [comment]
It was accepted as an upload, and worked for more than year now :). With the previous way of handling a file it's all just image rendering of the browser and just linking to a file. Now the binaries are moved within the actual database things are getting different I guess.

**Comment by sweetpants** [comment]
Can you test with V3.9483?

**Comment by gizmocuz** [comment]
Beta is in the make... will take 10 minutes.
Yes i just checked the code... what to say... if you placed a file myfile.crx , it was added to the appcache dynamically

Looking in the original webserver sourcecode, i do not see support for this, see below image:
![image](https://user-images.githubusercontent.com/2265299/40478115-7f8f89e4-5f48-11e8-893d-da5026e4bffa.png)

**Comment by gizmocuz** [comment]
Questions is, should we support GIF ?

**Comment by dannybloe** [comment]
well.. you also support bmp so gif doesn't look so weird next to this ancient format. Most browsers probably won't render bmp at all.. 
Better add support for svg ;-)

**Comment by MathijsG** [comment]
Why all this logic for different file formats anyway? Why not just save the whole filename with extension already in it.?

All the rendering is up to the browser.

But looking at the logic it sounds I could convert the gif to a png and it would work again? I will try that later today.

@sweetpants tried the new beta you're referring to, but all the same. Empty page, and on the floor plan settings I only see a broken reference.

**Comment by sweetpants** [comment]
Can you upload a new (or your old) floorplan under settings using the new Beta? When I upload one (.gif) i see it appear under floorplan.

**Comment by MathijsG** [comment]
I get a broken image as a result, the same as the current floorplan.
![image](https://user-images.githubusercontent.com/529552/40488075-2d59fa9c-5f66-11e8-9a73-8832b240485d.png)

Besides that, in the file dialog I need to change to all types, to show Gif files.

But is there a way to alter an existing floorplan? I see the option to add a file only when I create a new one. This whole uploadbox is gone when I want to alter the current one. The problem is, it's quite a hassle to make a new one, when I only want to change the image.

**Comment by sweetpants** [comment]
First clear your browser cache/app cache. There should be a preview icon left to the name
![image](https://user-images.githubusercontent.com/23421160/40488818-ed1ad396-5f67-11e8-90aa-9b3db5b9edbe.png)
which you can save the image file with (right mouse click)

**Comment by MathijsG** [comment]
Hmm, somehow it does work now. Any option to alter the image of my existing floorplan to this new working one? removing the whole floorplan with all defined rooms and stuff, will break more than I'd like.

The floorplan dialog also contains a UX dialog inconsistency by the way:
It's one of the only dialogs where the cancel action is on the left, instead of on the right. Which confuses a lot.
![image](https://user-images.githubusercontent.com/529552/40489438-62e141b8-5f69-11e8-9d6a-ea63fbd7e9f6.png)

**Comment by sweetpants** [comment]
Then everything needs to be checked, for instance the Cancel/OK dialog needs to be changed too
![image](https://user-images.githubusercontent.com/23421160/40499429-34c37b48-5f82-11e8-8818-f61b1b11e14c.png)

**Comment by gizmocuz** [comment]
Thats for another issue/topic

**Comment by gizmocuz** [comment]
The later is default bootbox bdw... Yes the floorplan code needs better i18n integration, noticed this as well
