### ISSUE TITLE
Stange values by some counters Zwave and 1 wire..

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#2418]
After a few weeks my counters a totally gone crazy..
Iuse 1 kwh and the Zwave counter give more the 50 Kwh in the graph....?
[https://www.domoticz.com/forum/viewtopic.php?f=6&t=17148](url)
I try to setup a new domoticz make no different.
I have the problem with serval openzwave supported devices.. [ different brands ]
In the thread there are people that this  issue also with dallas sensors.

There are more people that have this problem...
So i hope..

**Comment by gizmocuz** [comment]
Can't share this experience on any of my counter sensors

**Comment by Dylantje** [comment]
Dear Rob..
U can use my whole system, my DB and everything you need tot fix this 
Send me a mail and i give you everything u want

Thanks!!!

**Comment by Dylantje** [comment]
Perhaps something to do with Python.. [ i do not now how ]
When i use a plugin buienradar or idect my system [ lubuntu ts 19804 ]  is domoticz going to active:exited That means domoticz is not working any more..

**Comment by waltervl** [comment]
@Dylantje do you still have this issue? If not, can you close this issue please?
