### ISSUE TITLE
svalue update via MQTT does not trigger Datapush (Fibarolink)

### ISSUE THREAD

**Issue by sj3fk3** [domoticz/domoticz#242]
I'm using node-red to push data from jeenodes to domoticz and from there via a fibarolink to my fibaro system. But I noticed that when I update a value with MQTT it does not trigger an event.

**Comment by sbouchex** [comment]
@sj3fk3 Could you enable logging on the FibaroLink in order to see if some errors are displayed ? FYI, I have tested with the HttpLink (similar to FibaroLink) and it works fine.

**Comment by sj3fk3** [comment]
Logging was enable did not show anything. I think It does not catch the change in the value and therefor never gets triggered? It's not an issue for me anymore. I've started using node-red, it can listen to the mqtt queue and then trigger fibaro.
