### ISSUE TITLE
Latest beta 3.9501 strange values on devices label

### ISSUE THREAD

**Issue by sineverba** [domoticz/domoticz#2426]
On beta 3.9458 floorplans doesn't work.

![1](https://user-images.githubusercontent.com/2634842/40569275-8e624b62-6080-11e8-8654-e5fb5b673bf1.png)

On beta 3.9501 floorplans works (I can see the example inside) but sensors device labels have strange chars

![2](https://user-images.githubusercontent.com/2634842/40569302-c448cbca-6080-11e8-81a4-66c76bb0df0c.png)

On edit / log etc buttons, they shows an "undefinied".

They as need to display:

![3](https://user-images.githubusercontent.com/2634842/40569322-e4c92340-6080-11e8-911d-d77ceb8aea1a.png)

Unfortuntaly, after revert to ./updaterelease, I cannot btw remove the "new css/theme" of latest beta... I did also removed the appcache.

Have a nice day

**Comment by gizmocuz** [comment]
Try clearing browser cache + appcache (two different things!)
If that does not work, Can you edit your selector switches again ?

**Comment by sineverba** [comment]
Oh, as my last sentence, I did remove appcache and clear browser (ctrl+f5). I did try also with anonymous.

I didn't can edit anymore. Every Tab (log edit etc.) Did show Simply "undefined"

**Comment by gizmocuz** [comment]
Yes, and can you rename them ?

**Comment by gizmocuz** [comment]
If not, please contact me on the forum , i am very interested in a database backup

**Comment by sineverba** [comment]
Cannot edit.
In the forum Your name is the same? Can you search for me? I'm sineverba

**Comment by gizmocuz** [comment]
@sineverba , send you an gmail

**Comment by DAVIZINH0** [comment]
hello.
I have this problem in floorplan. In switch page apears ok

**Comment by sineverba** [comment]
@DAVIZINH0 which version?
@gizmocuz I did answer to your last email. On front page now seems ok. I have strange chars now in the API.

**Comment by DAVIZINH0** [comment]
Hello,
now the 3.9502
I make a clear cache in firefox (full, app included). and see this
![captura](https://user-images.githubusercontent.com/32111460/40580986-04e79a90-614d-11e8-8d6b-b9297415d588.jpg)

**Comment by askold2** [comment]
In beta 3.9502 the problem is solved partly. Now everything is fine on the "Dashboard" tab and
It is possible to edit devices on the "Switches" tab, but the names on the "Switches" and the "Floorplan" tabs are still broken. In the edit of switches the names are right. The names are not broken for all switches, but it seems that those who have selectors.

**Comment by gizmocuz** [comment]
turned out @sineverba was using an old version and it was already solved
@askold2 , yes we know, has been discussed in another issue topic here, still needs work, will be solved today but i have to wait some hours because i need to test some compile changes

**Comment by gizmocuz** [comment]
Floorplan fixed in upcoming beta, closing issue

**Comment by DAVIZINH0** [comment]
ok, thanks a lot!!
