### ISSUE TITLE
history log stop working after 2 days 

### ISSUE THREAD

**Issue by deennoo** [domoticz/domoticz#2429]
Domoticz beta 3.9502 linux debian

water and gas counter - incremental counter update from an esp8266 using mqtt
temp only device - update from an esp8266 using http api

I can have value on database and widget who are update to real date and hour , but nothing is update on log and 48h history

Only a domoticz restart allow it allow it to work for 24h, after nothing is shown on histoy ( 48h and daily) and nothing is written on database.

probleme start since 11/05/2018

extract from my database idx 314 is a dummy temp device for my swimming pool, i use avg temp to calculate how many time to start the pump

[code]
"314"	"14.4"	"17.7"	"15.79"	"0.0"	"0.0"	"0"	"0"	"0.0"	"0.0"	"0.0"	"0.0"	"2018-05-06"
"314"	"17.1"	"20.4"	"18.59"	"0.0"	"0.0"	"0"	"0"	"0.0"	"0.0"	"0.0"	"0.0"	"2018-05-07"
"314"	"18.9"	"20.3"	"19.57"	"0.0"	"0.0"	"0"	"0"	"0.0"	"0.0"	"0.0"	"0.0"	"2018-05-08"
"314"	"18.7"	"20.0"	"19.37"	"0.0"	"0.0"	"0"	"0"	"0.0"	"0.0"	"0.0"	"0.0"	"2018-05-10"
"314"	"17.3"	"19.8"	"18.26"	"0.0"	"0.0"	"0"	"0"	"0.0"	"0.0"	"0.0"	"0.0"	"2018-05-11"
"314"	"18.0"	"18.3"	"18.17"	"0.0"	"0.0"	"0"	"0"	"0.0"	"0.0"	"0.0"	"0.0"	"2018-05-16"
"314"	"17.6"	"18.6"	"18.01"	"0.0"	"0.0"	"0"	"0"	"0.0"	"0.0"	"0.0"	"0.0"	"2018-05-17"
"314"	"23.3"	"23.6"	"23.5"	"0.0"	"0.0"	"0"	"0"	"0.0"	"0.0"	"0.0"	"0.0"	"2018-05-21"
"314"	"22.4"	"23.5"	"22.93"	"0.0"	"0.0"	"0"	"0"	"0.0"	"0.0"	"0.0"	"0.0"	"2018-05-22"[/code]

i'm 100% sure of my device, and as you can see there is no database wrinting from 11/05 to 16/05

16/05 i restar domoticz and data was written for 2 days and nothing else until 21/05/2018 coming home from holiday and device was update and ok on widget but history was lock on 17/05/2018

**Comment by averni59** [comment]
Domoticz beta v3.9527 on Synology

I've the same issue with all devices on "Measure" menu : 
 - gaz, water, elec ... updated from MQTT
 - CPU, RAM ... updated from motherboard sensors

Values are updated and could be read during 24 hours.
I haven't any datas between 28/05/2018 and 10/05/2018.

**Comment by gizmocuz** [comment]
@averni59 , maybe update first to the latest version, there have been some MQTT changes.
If you connect to the MQTT broker with an external application, do you still see the updates ?
If not, the problem might be on the 'source' side ?

**Comment by averni59** [comment]
@gizmocuz, I don't think it's a MQTT issue because data are correctly updated day to day but seems to be deleted after a day.
Besides, I have the same issue with mother boards sensors and zwave devices on "Mesures"  menu.

I haven't try to reboot yet nor to update domoticz.

Thank you,

**Comment by gizmocuz** [comment]
@averni59 , are you talking about the short log ? Yes that is normal, but in the day charts there should be a new entry each day

**Comment by averni59** [comment]
The [daily view](https://drive.google.com/open?id=1St40vm9VQomdRXFMpyYzNPum8VFsGyCa) is OK.
But on other views, datas from 28/05 to 10/06 are missing : 
 - [monthly](https://drive.google.com/open?id=1N0J6DjpMFaEoDK-hIactDyOr5o707a_G)
 - [May report](https://drive.google.com/open?id=10zaXUk37kvJ9bxA6NGWiT_EqQ9Q66hl5) 
 - [June report](https://drive.google.com/open?id=1MZPo8Qbb9zsqJQRLAkZQSauIN1GFddHe)

**Comment by gizmocuz** [comment]
Can you contact me on the forum? I would like to do some debugging

**Comment by averni59** [comment]
I've just created an account on the forum but I can't use the chat feature currently due to an antispam bot.
Can you contact me first ? Then I will reply you back.

**Comment by gizmocuz** [comment]
Send you an email

**Comment by gizmocuz** [comment]
@averni59 , send you an email

**Comment by gizmocuz** [comment]
Has this been solved yet ?

**Comment by averni59** [comment]
Hello,

Not yet.
I've try a tips found on the forum : disable script, clear shortlogs,
reboot, enabe script ; but it doesn't work.

As soon as the v4 will be available on Synology, i will try a fresh install
and import the base.
Unless you have another thing to test.

By the way, congratulations and thank you for your work on the v4. I'm
impatient to test it.

**Comment by averni59** [comment]
Hello,

I've just installed the v4.
The problem is now solved !

Thank you !

**Comment by gizmocuz** [comment]
Thanks for the feedback!
