### ISSUE TITLE
Domoticz goes offline  after about 5 minutes

### ISSUE THREAD

**Issue by riesch** [domoticz/domoticz#2430]
Domoticz beta 3.9502 linux stretch
Rapsberrypi 3B
Used hardware: atag one, zwave, hue, rfxcom
dzvents enabled
Updated from about 3.9450
Only clue so far : log states that dzvents is running longer than 10 seconds.

Other domoticz installation with only p1 hardware is running fine on domoticz beta 3.9502 Rapsberry pi zero W

**Comment by riesch** [comment]
![schermafbeelding 2018-05-27 om 10 08 15](https://user-images.githubusercontent.com/29521240/40583855-9564afd8-6196-11e8-9620-ba2597a67143.png)
This is new too

**Comment by riesch** [comment]
after a backup and restore of the database domotica no longer shuts down. the selector switch issue remains though.
another thing is that de update button disappeared. also no longer an option in the settings
![schermafbeelding 2018-05-27 om 10 44 45](https://user-images.githubusercontent.com/29521240/40584086-42f85c72-619b-11e8-8860-0dbd486e85d7.png)

**Comment by riesch** [comment]
after updating to 3.9517 the issue has been solved.

**Comment by gizmocuz** [comment]
@riesch , please use the forum
