### ISSUE TITLE
Invalid python template script corrupts fresh Domoticz beta install on Pi

### ISSUE THREAD

**Issue by jkransen** [domoticz/domoticz#2433]
Version: 3.9501
Build Hash: 4eb1bc70
Compile Date: 2018-05-25 16:53:11
dzVents Version: 2.4.5
Python Version: 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170124]
Raspberry Pi / Raspbian Stretch

I had a smoothly running system with the latest Domoticz beta on the latest Raspbian Stretch yesterday (Except for one issue:viewtopic.php?f=6&t=23590). Then I added a Python based event script from the GUI. In fact I didn't even edit the script, just saved the template that merely logs. Since then, I get segmentation faults when starting Domoticz. I read lots of issues about Python dependencies in the past, but this is the beta branch and I got the impression that these problems should not occur there anymore. 

First question, is there a quick way to remove the Python script without a running Domoticz? But in general, what steps are needed to get Python enabled and working without segmentation fault?

Please test a fresh install on a Pi, and see if you get a basic Python script working.

**Comment by gizmocuz** [comment]
@jkransen , anything can happen with the beta
There is already a thread about python scripts giving issues, but what script did you use ?

**Comment by jkransen** [comment]
As I stated, I just saved the template Python script from the GUI. The point of this issue is not about Python scripting, but about the fact an incorrect script can bring the whole system down. That's a Domoticz issue rather than a Python scripting one.Also, a template script should be correct.

**Comment by gizmocuz** [comment]
@jkransen , yes we know, nothing we can do about it... seems we can not 'catch' the crash
