### ISSUE TITLE
Segfault and Signal 6 on latest betas

### ISSUE THREAD

**Issue by heggink** [domoticz/domoticz#2437]
Beta 9433 was my last stable beta. Beta 9517 throws both signal 6's and signal 11's again.
No changes in devices/plugins, only beta update. Something changed causing mem issues.
Opened at the request of @emontnemery

**Comment by heggink** [comment]
One sig 11 happens straight after midnight (00:00:01 EventSystem: reset all events -> signal 11)

**Comment by kovainfo** [comment]
Confirm: One sig 11 happens straight after midnight (00:00:01 EventSystem: reset all events -> signal 11)
`2018-05-29 00:00:00.853  There is no astronomical twilight in the space of 24 hours
2018-05-29 00:00:00.853  EventSystem: reset all events...
2018-05-29 00:00:01.151  Error: Domoticz received fatal signal 11 !...
2018-05-29 00:00:01.153  Error:   /home/pi/domoticz/domoticz() [0x2529d0]
2018-05-29 00:00:01.153  Error:   /home/pi/domoticz/domoticz(_Z14signal_handleri+0x4c) [0x252a88]
2018-05-29 00:00:01.153  Error:   /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer_v2+0) [0x76bd3180]`

**Comment by kovainfo** [comment]
Since 26 MAY, in 00:00, when issue happes, does NOT update the data in the "calendar" tables:
Percentage_Calendar
MultiMeter_Calendar
Meter_Calendar

But
Temperature_Calendar is OK

**Comment by kovainfo** [comment]
Ok, problem is stable:

> Tue 29 May 05:19:16 MSK 2018
> root@raspberrypi:/home/pi# service domoticz stop
> root@raspberrypi:/home/pi# date 052823582018
> Mon 28 May 23:58:00 MSK 2018
> root@raspberrypi:/home/pi# service domoticz start
> root@raspberrypi:/home/pi# tail -f /tmp/domoticz.txt 
> 2018-05-28 23:59:18.659  (XiaomiGateway) General/kWh (power (kWh))
> 2018-05-29 00:00:00.789  Sunrise: 03:56:00 SunSet: 20:58:00
> 2018-05-29 00:00:00.789  Day length: 17:01:00 Sun at south: 12:05:00
> 2018-05-29 00:00:00.789  Civil twilight start: 03:01:00 Civil twilight end: 21:53:00
> 2018-05-29 00:00:00.789  Nautical twilight start: 01:13:00 Nautical twilight end: 23:41:00
> 2018-05-29 00:00:00.790  There is no astronomical twilight in the space of 24 hours
> 2018-05-29 00:00:00.790  EventSystem: reset all events...
> 2018-05-29 00:00:00.976  Error: Domoticz received fatal signal 11 !...
> 2018-05-29 00:00:00.979  Error:   /home/pi/domoticz/domoticz() [0x2529d0]
> 2018-05-29 00:00:00.979  Error:   /home/pi/domoticz/domoticz(_Z14signal_handleri+0x4c) [0x252a88]
> 2018-05-29 00:00:00.979  Error:   /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer_v2+0) [0x76c77180]
> 
> ^C

**Comment by gizmocuz** [comment]
Possible has something to with with creating the day values.
Looks like it goes wrong with meter devices, but can't see where.
There have been two patches on this
- new managed meter
- i converted all float values to long long values as the database has no floats in the meter tables (using atoll, so that should not crash)

When debugging, you can set a breakpoint in the mainworker where it checks if the day has been different/past, then force the cursor to think it has

**Comment by gizmocuz** [comment]
When i try with a database backup from a user that has problems and force a m_sql.ScheduleDay(); , i have no issues

**Comment by gizmocuz** [comment]
Could be the EventSystem... But can not see what could be wrong with it

**Comment by gizmocuz** [comment]
I have reverted my 'long long' patch, as it seems a sqlite3_sprintf issue, but cant see anything wrong with the previous patch. Maybe it does not know %lld and it should be %ll, still here, debugging a database day schedule on a windows system with VStudio results in no error

**Comment by heggink** [comment]
@gizmocuz hope that fixes things. Unfortunately, both my solar panel and P1 totals are missing for the last 2 days. Is there a way to re-enter these by hand?

**Comment by gizmocuz** [comment]
@heggink , not easily no

**Comment by emontnemery** [comment]
@heggink Can you try to reproduce with debugger to get a stacktrace, perhaps backup database and then force time to 23.58?

**Comment by heggink** [comment]
won't be able to today and also just updated to the latest beta that hopefully solves this. Today/tomorrow bad timing for me unfortunately. On the road...

**Comment by emontnemery** [comment]
@heggink OK, no worries!

**Comment by kovainfo** [comment]
new beta v3.9530 works fine for me.
I set the time to 23:58, waited until 0 and everything works fine

**Comment by gizmocuz** [comment]
@kovainfo , thanks for testing ! I also got a good response from another user.
Could mean two things:

- recheck the managed meter patch (only the part where the meter values are updated in the calendar)
- recheck long-long patch (SQLite (linux) can not work with %lld ?)

**Comment by heggink** [comment]
Sig 11 resolved indeed. @gizmocuz Close this and open specific issue to address the meter patch issues?

**Comment by gizmocuz** [comment]
@heggink , thats a good idea !
