### ISSUE TITLE
Xiaomi socket plug not detect consumption 

### ISSUE THREAD

**Issue by DAVIZINH0** [domoticz/domoticz#2438]
Hello,
Since 26 may, my xiaomi plugs stop detect consumption.
I allways update the beta version as soon as release and maybe something change.
Now i have the 3.9527 and there is not data since 26/05

**Comment by DAVIZINH0** [comment]
WOW. im stupid!!!

I have the xiaomi gateway blocked in the router, and disable de internet access of the gateway.
I have all the information in domoticz, i not need xiaomi connection.

I restore de internet conection to the xiaomi gateway and yes!!! domoticz obtain the consumption!!!
This need the internet access??? is posible???

IM SHOCKED!

**Comment by gizmocuz** [comment]
@DAVIZINH0 , have a look in the code and you know!

**Comment by DAVIZINH0** [comment]
ok, sorry!!
I'm going to search. some clue or part of the code where to look?

**Comment by DAVIZINH0** [comment]
solved!!

**Comment by gizmocuz** [comment]
@DAVIZINH0 , not quite solved, we still need a patch ;)

**Comment by DAVIZINH0** [comment]
jejeje, ahhh ok ok
i thing the solution is that the gateway must have internet access.
:-O

**Comment by gizmocuz** [comment]
Merged !
