### ISSUE TITLE
Since MAY 26 sig 11 happens straight after midnight (00:00:01 EventSystem: reset all events -> signal 11)

### ISSUE THREAD

**Issue by kovainfo** [domoticz/domoticz#2440]
problem is stable:
> Tue 29 May 05:19:16 MSK 2018
> root@raspberrypi:/home/pi# service domoticz stop
>
> root@raspberrypi:/home/pi# date 052823582018
> Mon 28 May 23:58:00 MSK 2018
>
> root@raspberrypi:/home/pi# service domoticz start
>
> root@raspberrypi:/home/pi# tail -f /tmp/domoticz.txt
> 2018-05-28 23:59:18.659 (XiaomiGateway) General/kWh (power (kWh))
> 2018-05-29 00:00:00.789 Sunrise: 03:56:00 SunSet: 20:58:00
> 2018-05-29 00:00:00.789 Day length: 17:01:00 Sun at south: 12:05:00
> 2018-05-29 00:00:00.789 Civil twilight start: 03:01:00 Civil twilight end: 21:53:00
> 2018-05-29 00:00:00.789 Nautical twilight start: 01:13:00 Nautical twilight end: 23:41:00
> 2018-05-29 00:00:00.790 There is no astronomical twilight in the space of 24 hours
> 2018-05-29 00:00:00.790 EventSystem: reset all events...
> 2018-05-29 00:00:00.976 Error: Domoticz received fatal signal 11 !...
> 2018-05-29 00:00:00.979 Error: /home/pi/domoticz/domoticz() [0x2529d0]
> 2018-05-29 00:00:00.979 Error: /home/pi/domoticz/domoticz(_Z14signal_handleri+0x4c) [0x252a88]
> 2018-05-29 00:00:00.979 Error: /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer_v2+0) [0x76c77180]
> 
> ^C

when issue happes, does NOT update the data in the "calendar" tables:
Percentage_Calendar
MultiMeter_Calendar
Meter_Calendar

But
Temperature_Calendar is OK

Raspberry Pi 3, 
Domoticz v3.9527

**Comment by kovainfo** [comment]
This issue on forum:
https://www.domoticz.com/forum/viewtopic.php?f=6&t=23623

**Comment by gizmocuz** [comment]
Please join here https://github.com/domoticz/domoticz/issues/2437
