### ISSUE TITLE
dzVents.lua:19: attempt to concatenate local 'runtimePath' (a nil value)

### ISSUE THREAD

**Issue by svde** [domoticz/domoticz#2442]
Latest github code (7ded4156c37518ebebe0ce5ca144ae3d683e1995) is showing this in syslog:

May 29 13:43:58 * domoticz[4801]: EventSystem: in /opt/domoticz/dzVents/runtime/dzVents.lua: /opt/domoticz/dzVents/runtime/dzVents.lua:19: attempt to concatenate local 'runtimePath' (a nil value)
May 29 13:44:00 * domoticz[4801]: EventSystem: in /opt/domoticz/dzVents/runtime/dzVents.lua: /opt/domoticz/dzVents/runtime/dzVents.lua:19: attempt to concatenate local 'runtimePath' (a nil value

I'm not sure if its harmful.

**Comment by rwaaren** [comment]
I don't see this message on my PI-3, Debian stretch,  domoticz  V3.9529 and I use a lot of dzVents scripts

**relevant lines in dzVents.lua Domoticz V3.9462** 

local currentPath = globalvariables['script_path'] -- should be path/to/domoticz/scripts/dzVents

package.path = package.path .. ';' .. currentPath .. '?.lua'
package.path = package.path .. ';' .. currentPath .. '../../dzVents/runtime/?.lua'
package.path = package.path .. ';' .. currentPath .. '../../dzVents/runtime/device-adapters/?.lua'
package.path = package.path .. ';' .. currentPath .. 'dzVents/?.lua'

**relevant lines in dzVents.lua Domoticz V3.9529**

local scriptPath = globalvariables['script_path'] -- should be ${szUserDataFolder}/scripts/dzVents/
local runtimePath = globalvariables['runtime_path'] -- should be ${szStartupFolder}/dzVents/runtime/


package.path = package.path .. ';' .. scriptPath .. '?.lua'
package.path = package.path .. ';' .. runtimePath .. '?.lua'
package.path = package.path .. ';' .. runtimePath .. 'device-adapters/?.lua'
package.path = package.path .. ';' .. scriptPath .. 'dzVents/?.lua'
package.path = package.path .. ';' .. scriptPath .. 'scripts/?.lua'
package.path = package.path .. ';' .. scriptPath .. '../lua/?.lua'
package.path = package.path .. ';' .. scriptPath .. 'scripts/modules/?.lua'
package.path = package.path .. ';' .. scriptPath .. '?.lua'
package.path = package.path .. ';' .. scriptPath .. 'generated_scripts/?.lua'
package.path = package.path .. ';' .. scriptPath .. 'data/?.lua'
package.path = package.path .. ';' .. scriptPath .. 'modules/?.lua'

_Not sure about the do's and dont's yet but maybe better to have this conversation on the forum ?_

**Comment by dannybloe** [comment]
Perhaps your dzVents version doesn’t match with the Domoticz version.

**Comment by svde** [comment]
it's from https://github.com/domoticz/domoticz

$ git status
On branch development
Your branch is up to date with 'origin/development'.

nothing to commit, working tree clean


I think the globalvariables['runtime_path']  isn't set...

**Comment by svde** [comment]
The packages was upgraded but domoticz wasn't restarted. Restarting domoticz fixed it.
