### ISSUE TITLE
Improve stack trace

### ISSUE THREAD

**Issue by emontnemery** [domoticz/domoticz#2443]
The backtrace functions are almost completely unusable on Raspberry Pi, and often gives no useful stacktrace information. I have tried several other libraries with similar functionality as backtrace, of which libunwind was the most promising, but it was still not nearly good enough.
One main root cause is that libc on debian (and hence raspbian) is compiled without flags needed to aid stack unwinding (-f-unwind-tables -f-asynchronous-unwind-tables), and there also does not seem to be any library with good heuristics for finding return addresses on the stack.

Proposal:
- Compile release version of domoticz with some additional flags to aid debugging
  - This could be removed on "master" branch, but should be kept on "development" to get useful reports from end users
- Let domoticz call gdb to print the stacktrace on raspberry pi build as well as / instead of using backtrace functions
  - From domoticz signal handler, spawn gdb (I have a working prototype, I'll open a PR for review)
  - This could be removed on "master" branch, but should be kept on "development" to get useful reports from end users

**Comment by gizmocuz** [comment]
Boost also has a stacktrace library, could this be of use ?

https://www.boost.org/doc/libs/1_65_1/doc/html/stacktrace.html

If we compile under _DEBUG, we can use that define, check if GDB exists, and then spawn it
No need to have debug information in a release version.
There is a very good step-by-step instruction set to compile domoticz (just enable the DEBUG build) should not be that hard
A good callstack of the domoticz functions being called should not be that difficult you would say...
Debugging crashdumps under visual studio works as a charm, but my knowledge for linux is limited.

**Comment by gizmocuz** [comment]
Maybe there way of saving the dump file and dumping it on restart might work as well

**Comment by emontnemery** [comment]
@gizmocuz I think I did already check boost stacktrace, and it's just a wrapper for lower level functions. But I'll check again.
I agree no need for this kind of debug information in stable release, but don't you think it would be good for the official betas? Not all users are comfortable with compiling themselves, so a proper stacktrace would make the "Signal 11 every week"-bug reports much easier to debug.

This looks like a good starting point for your idea of saving coredump:
https://code.google.com/archive/p/google-coredumper/

**Comment by gizmocuz** [comment]
@emontnemery , in the getting started item of the boost library, they explain why a good dump fails when an application crashes, and that you get good/better results when you save it, and when you launch the application again, check for the crashdump
The library is pretty good bdw.

About debug/release builds, the beta's should be quite stable, but about the signal 6/11, if many users experience this then:
- we (developers) should try to replicate it in debug mode (maybe with asking for a database backup)
- provide a good tutorial how to setup a build enviroment

This because i think adding debug information in beta release builds / packages, will increase the package size big time

Thankfully at this moment, when people experience a crash, we have enough developers and users compiling themselves to debug it

**Comment by emontnemery** [comment]
@gizmocuz What is being talked about in the boost library documentation is just about minimizing the risk of not being able to print from the signal handler. This has nothing to do with the bad stacktraces on Raspberry Pi.
What they're talking about doesn't give you a better stacktrace, it just removes the risk that the call to printf() / cout() hangs for whatever reason.
The issue with Raspberry Pi is basically very unfortunate default compiler settings used to build Debian for ARM, which means the stack can't be unwound by runtime stack unwinding libraries. GDB can (as I understand it) work around this by guessing on which stack content are return addresses.

**Comment by gizmocuz** [comment]
@emontnemery , ok clear, but if we build in debug mode, we should be able to show a call stack displaying at least from what function it was coming from in domoticz?
So lets say an illegal printf, called from domoticz::class::functionX, you should see something like
-->printf illegal bla bla
--> domoticz::class::functionX

**Comment by heggink** [comment]
Given mrkabs' latest entry https://www.domoticz.com/forum/viewtopic.php?f=6&t=19022 is this getting to some solution/closure? Some of us still seem to suffer these intermittent signal 6/11 issues so an informative stack trace would be really really helpful.

**Comment by gizmocuz** [comment]
@emontnemery , could the last post help from this forum:
https://www.raspberrypi.org/forums/viewtopic.php?t=60540

(sudo apt-get install libc6-dbg)

Did you compiling with '-g -rdynamic' ? like explained in domoticz.cpp (line 51)

**Comment by gizmocuz** [comment]
Did some testing as well with a simple program that crashes... unfortunately still no line numbers

**Comment by gizmocuz** [comment]
When i compile my crashing application with

> gcc -g -rdynamic ./test.cpp -o test

and launch it in gdb, i do get some useful debug information

so spawning gdb sounds a good idea...

I needed to install gdb, and i also installed the libc6-dbg package

I don't think it is a good idea to include symbols in a release build,
i would only do this in debug compile mode
The output of GDB is print on the console ?

**Comment by emontnemery** [comment]
I already implemented spawning of gdb, if you think it's a reasonable
approach, I'll open a PR.

Note I'm not talking about adding line number, I'm talking about fixing
complete lack of valid stack trace in some situation (e.g from call to
abort) due to unfortunate compile flags used to build raspbian.

**Comment by gizmocuz** [comment]
But we do see line numbers (functions) where the crash happens in domoticz ? (call stack)
Not something like domoticz+0x208048

**Comment by gizmocuz** [comment]
What happens when we update via the web interface? Internally a service restart is done that could take some time, let's say a minute.

Will this setting be a problem ?

RestartSec=5s

Should this be set to 70s ?

**Comment by gizmocuz** [comment]
Admin is allowed to reboot the system from the menu, will this not cause a SIGSYS signal ?

SystemCallFilter=@reboot

**Comment by gizmocuz** [comment]
PrivateDevices is default false, and can be removed from this service file

**Comment by gizmocuz** [comment]
when domoticz terminates, it tries to stop all hardware nicely.

TimeoutStopSec=10

might be to short ! and could result in a database flush issue

I would recommend setting this to 30

**Comment by gizmocuz** [comment]
As per documentation i would suggest the following two lines as there is no system man page

Documentation=https://www.domoticz.com
Documentation=https://www.domoticz.com/wiki

**Comment by gizmocuz** [comment]
@emontnemery , have you got any luck with the PR ?
I am thinking about making a new release beginning next week

**Comment by emontnemery** [comment]
@gizmocuz I've been away for a while! If not too late, I'll open a PR the next few days?

**Comment by gizmocuz** [comment]
@emontnemery, it's never to late ! ;)
But we might put this in the next beta version... no hurry !

**Comment by emontnemery** [comment]
Opened PR #2530
