### ISSUE TITLE
Selector switch scrumbled after upgrade to latest beta

### ISSUE THREAD

**Issue by zwartevogel** [domoticz/domoticz#2444]
After updating to the latest beta (9530) my selector switch has no actions but only has one action with the hash name 'T2ZmfFRWfE1lZGlhY2VudGVy'. Before the update there were (manually added) 4 actions.

**Comment by gizmocuz** [comment]
This is with the web interface ?
Clear the browser cache + appcache (two different things)
If that does not work, edit the selector switch and change the names

**Comment by zwartevogel** [comment]
Thanks, that solved my problem.
