### ISSUE TITLE
Notifications - Custom message - conversion to http format

### ISSUE THREAD

**Issue by ALROCHARARI** [domoticz/domoticz#2445]
I'm using French version of Domoticz version 3.9530 from 2018-05-29.
I'm using email and Clickatell notifications.
When creating or changing a custom message, the text entered is converted when saved.
See sample: "Temperature in the living room too high." converted to
"Temperature%20in%20the%20living%20room%20too%20high."
I suspect this issue could be there since a long time but did not made changes to my notifications for months.

**Comment by deennoo** [comment]
this issue is the same for all http:// and script action store in all dummy selector switch


script%3A///home/nico/domoticz/scripts/shell/volume60.sh
--


http%3A//127.0.0.1%3A8080/json.htm%3Ftype%3Dcommand%26param%3Ddiscomodenum6%26idx%3D2842

**Comment by gizmocuz** [comment]
I just discovered this as well... will look into this

**Comment by gizmocuz** [comment]
@deennoo , two different issues

Both should be fixed.

**Comment by ALROCHARARI** [comment]
Working like a charm now.
Can be closed for me.

Keep going on with the good work gizmocuz !

**Comment by gizmocuz** [comment]
Thanks!

**Comment by deennoo** [comment]
sorry @gizmocuz 

But not solve on my side

After updating to v3.9580 it doesn't correct value on action on and off on selector switch, they are all still html coded as : 

http%3A//127.0.0.1%3A8080/json.htm%3Ftype%3Dcommand%26param%3Ddiscomodenum9%26idx%3D2842

**Comment by gizmocuz** [comment]
@deennoo , did you re-edit the switch actions/levels, giving them the correct values ?
(And clear browser+appcache)
