### ISSUE TITLE
Error compiling from "Depending on boost 1.60 and chrono" version

### ISSUE THREAD

**Issue by aldodemi** [domoticz/domoticz#2447]
Debian server

from yesterday release I receive compile error (no problems before): 
[ 99%] Building CXX object CMakeFiles/domoticz.dir/tinyxpath/xpath_static.cpp.o
[ 99%] Building CXX object CMakeFiles/domoticz.dir/tinyxpath/xpath_syntax.cpp.o
[100%] Linking CXX executable domoticz
CMakeFiles/domoticz.dir/main/EventSystem.cpp.o: nella funzione "boost::thread::do_try_join_until(timespec const&)":
EventSystem.cpp:(.text._ZN5boost6thread17do_try_join_untilERK8timespec[_ZN5boost6thread17do_try_join_untilERK8timespec]+0x7e): riferimento non definito a "boost::thread::do_try_join_until_noexcept(timespec const&, bool&)"
CMakeFiles/domoticz.dir/main/Helper.cpp.o: nella funzione "boost::this_thread::sleep_for(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > const&)":
Helper.cpp:(.text._ZN5boost11this_thread9sleep_forERKNS_6chrono8durationIlNS_5ratioILl1ELl1000000000EEEEE[_ZN5boost11this_thread9sleep_forERKNS_6chrono8durationIlNS_5ratioILl1ELl1000000000EEEEE]+0x28): riferimento non definito a "boost::this_thread::hidden::sleep_for(timespec const&)"
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:6095: set di istruzioni per l'obiettivo "domoticz" non riuscito
make[2]: *** [domoticz] Errore 1
CMakeFiles/Makefile2:104: set di istruzioni per l'obiettivo "CMakeFiles/domoticz.dir/all" non riuscito
make[1]: *** [CMakeFiles/domoticz.dir/all] Errore 2
Makefile:149: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2

**Comment by gizmocuz** [comment]
Please use the forum!
To solve issue

make clean
remove the CMakeFiles folder, the CMakeCache file and issue the default cmake command again, followed by make

**Comment by aldodemi** [comment]
Sorry, previously not found on the forum...
done all but doesn't work, I also started from scratch but always the same error:

**Comment by gizmocuz** [comment]
Whats your boost version installed ? Did you follow
https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI
(Also works for other systems)

latest boost version is 1.67

**Comment by aldodemi** [comment]
yes, followed the article you noted and it is 1.67

**Comment by sweetpants** [comment]
Hmm strange, had the same issue and just updated boost from 1.58 to 1.67 and compiling works again.
When building boost be sure to use:
./bootstrap.sh --with-libraries=atomic,date_time,exception,filesystem,iostreams,locale,program_options,regex,signals,system,test,thread,timer,log

./b2 install

**Comment by sweetpants** [comment]
Oops, to early. during linking i get CMakeFiles/domoticz.dir/main/EventSystem.cpp.o: In function `boost::thread::do_try_join_until(boost::detail::mono_platform_timepoint const&)':
EventSystem.cpp:(.text._ZN5boost6thread17do_try_join_untilERKNS_6detail23mono_platform_timepointE[_ZN5boost6thread17do_try_join_untilERKNS_6detail23mono_platform_timepointE]+0x8b): undefined reference to `boost::thread::do_try_join_until_noexcept(boost::detail::mono_platform_timepoint const&, bool&)'
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:6087: recipe for target 'domoticz' failed
make[2]: *** [domoticz] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sweetpants** [comment]
Started all over again after re-install boost 1.67 on my test system
cd ~/domoticz
make clean
rm CMakeCache.txt
rm -rf CMakeFiles
cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt
make -j 4

Now it compiles and links again without errors

**Comment by aldodemi** [comment]
Re-install boost 1.67 and done exactly what you suggested but always the same errors

**Comment by sweetpants** [comment]
Weird, also updated my production system using the same procedure and this also went fine. Running V3.9540 now on both systems.

**Comment by gordonb3** [comment]
Better to just completely remove the domoticz source folder and start with a fresh git clone.

**Comment by aldodemi** [comment]
Already dono, three time :-), always the same error

**Comment by gizmocuz** [comment]
@aldodemi 
try removing the complete source folder
please follow our wiki:
https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by gordonb3** [comment]
Searching the net for `boost::detail::mono_platform_timepoint` returns that this is part of the boost chrono library.

The Debian packages site next states the following on [Package: libboost-dev](https://packages.debian.org/wheezy/libboost-dev)
>For the following subprojects separate packages exist: **[chrono](https://packages.debian.org/sid/libboost-chrono-dev)**, date-time,_ filesystem, graph, iostreams, locale, math, mpi, program_options, python, regex, serialization, signals, system, test, thread, timer, and wave. 

You probably do not have that additional package installed.

**Comment by aldodemi** [comment]
@gordonb3: As I followed the wiki it say:
...
./b2 stage threading=multi link=static --with-thread --with-system --with-chrono
sudo ./b2 install threading=multi link=static --with-thread --with-system --with-chrono
...
as you can see "chrono" is there...

@gizmocuz: already done, removed domoticz source folder and the started again following the wiki you mentioned...

**Comment by aldodemi** [comment]
Note that all works correct until the "Depending on boost 1.60 and chrono" revision 3029591committed on May 29, 2018

**Comment by gordonb3** [comment]
Right. We seem to have two independent issues here.

OP (@aldodemi) has an issue with boost:thread and @sweetpants has an issue with boost::chrono which is in fact missing from the bootstrap.sh command he listed above

**Comment by sweetpants** [comment]
Correction, sweetpants **_had_** a problem. Just did a make clean, removed CMakeCache.txt, removed folder CMakeFiles/ and followed the WiKi. All working well now on both my systems.

**Comment by aldodemi** [comment]
Started another time from scratch, following the wiki now error is:
CMakeFiles/domoticz.dir/main/EventSystem.cpp.o: nella funzione "CEventSystem::EvaluateLua(std::vector<CEventSystem::_tEventQueue, std::allocator<CEventSystem::_tEventQueue> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)":
EventSystem.cpp:(.text+0x1dfdd): riferimento non definito a "boost::thread::do_try_join_until_noexcept(timespec const&, bool&)"
CMakeFiles/domoticz.dir/main/LuaHandler.cpp.o: nella funzione "CLuaHandler::executeLuaScript(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)":
LuaHandler.cpp:(.text+0x1e85): riferimento non definito a "boost::thread::do_try_join_until_noexcept(timespec const&, bool&)"
CMakeFiles/domoticz.dir/main/Helper.cpp.o: nella funzione "sleep_seconds(long)":
Helper.cpp:(.text+0x838): riferimento non definito a "boost::this_thread::hidden::sleep_for(timespec const&)"
CMakeFiles/domoticz.dir/main/Helper.cpp.o: nella funzione "sleep_milliseconds(long)":
Helper.cpp:(.text+0x88f): riferimento non definito a "boost::this_thread::hidden::sleep_for(timespec const&)"
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:6095: set di istruzioni per l'obiettivo "domoticz" non riuscito
make[2]: *** [domoticz] Errore 1
CMakeFiles/Makefile2:104: set di istruzioni per l'obiettivo "CMakeFiles/domoticz.dir/all" non riuscito
make[1]: *** [CMakeFiles/domoticz.dir/all] Errore 2
Makefile:149: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2

**Comment by sweetpants** [comment]
What Gcc version are you using? Make sure you are on V6
(BTW, I can't read Italian, so limited to help you)

**Comment by aldodemi** [comment]
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
this is (more or less) the english version:
CMakeFiles/domoticz.dir/main/EventSystem.cpp.o: in function "CEventSystem::EvaluateLua(std::vector<CEventSystem::_tEventQueue, std::allocatorCEventSystem::_tEventQueue > const&, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&)":
EventSystem.cpp:(.text+0x1dfdd): reference not defined to "boost::thread::do_try_join_until_noexcept(timespec const&, bool&)"
CMakeFiles/domoticz.dir/main/LuaHandler.cpp.o: in function "CLuaHandler::executeLuaScript(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits, std::allocator >, std::allocator<std::__cxx11::basic_string<char, std::char_traits, std::allocator > > >&)":
LuaHandler.cpp:(.text+0x1e85): reference not defined to "boost::thread::do_try_join_until_noexcept(timespec const&, bool&)"
CMakeFiles/domoticz.dir/main/Helper.cpp.o: in function "sleep_seconds(long)":
Helper.cpp:(.text+0x838): reference not defined to "boost::this_thread::hidden::sleep_for(timespec const&)"
CMakeFiles/domoticz.dir/main/Helper.cpp.o: in function "sleep_milliseconds(long)":
Helper.cpp:(.text+0x88f): reference not defined to "boost::this_thread::hidden::sleep_for(timespec const&)"
collect2: error: ld returned 1 exit status

**Comment by aldodemi** [comment]
Release v3.9560 compile error (starting from scratch):

CMakeFiles/domoticz.dir/main/EventSystem.cpp.o: nella funzione "CEventSystem::EvaluateLua(std::vector<CEventSystem::_tEventQueue, std::allocator<CEventSystem::_tEventQueue> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)":
EventSystem.cpp:(.text+0x1dfdd): riferimento non definito a "boost::thread::do_try_join_until_noexcept(timespec const&, bool&)"
CMakeFiles/domoticz.dir/main/LuaHandler.cpp.o: nella funzione "CLuaHandler::executeLuaScript(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)":
LuaHandler.cpp:(.text+0x1e85): riferimento non definito a "boost::thread::do_try_join_until_noexcept(timespec const&, bool&)"
CMakeFiles/domoticz.dir/main/Helper.cpp.o: nella funzione "sleep_seconds(long)":
Helper.cpp:(.text+0x838): riferimento non definito a "boost::this_thread::hidden::sleep_for(timespec const&)"
CMakeFiles/domoticz.dir/main/Helper.cpp.o: nella funzione "sleep_milliseconds(long)":
Helper.cpp:(.text+0x88f): riferimento non definito a "boost::this_thread::hidden::sleep_for(timespec const&)"
collect2: error: ld returned 1 exit status

**Comment by sweetpants** [comment]
Just compiling new releases is not going to help you if you are missing things. Still looks like you are missing the right boost (thread) parts when linking.

**Comment by aldodemi** [comment]
Ok, but what to do other then:

mkdir boost
cd boost
wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz
tar xfz boost_1_67_0.tar.gz
rm boost_1_67_0.tar.gz
cd boost_1_67_0/
./bootstrap.sh
./b2 stage threading=multi link=static --with-thread --with-system --with-chrono
sudo ./b2 install threading=multi link=static --with-thread --with-system --with-chrono
cd ../../
rm -Rf boost/

to have the rights boost?

**Comment by sweetpants** [comment]
Did you also remove the old boost references as the Wiki states? After that re-install new boost

**Comment by HoekieN** [comment]
If you had boost version 1.6x before then first delete the following files/folders: /usr/local/lib/libboost* and /usr/local/include/boost
And then install boost.
If you don't delete it then boost will not be upgraded to 1.67, can check the version here: /usr/local/include/boost/version.hpp just open the file in a txt editor.

**Comment by sweetpants** [comment]
I don't think aldodemi had a 1.6x version installed because then compilation would have succeeded (if chrono was added)

**Comment by gizmocuz** [comment]
@HoekieN , i also did not uninstall it. The b2 install script will overwrite the /usr/local/include/boost/version.hpp also

**Comment by gizmocuz** [comment]
@aldodemi , please update the code (git pull) , i removed the boost chrono dependency
I am struggling with a certain class (concurrent_queue) that is using a scoped_lock that is not available in cxx11, else we could remove the boost thread as well

**Comment by aldodemi** [comment]
@gizmocuz now it compile without problem. Thank you.

**Comment by gizmocuz** [comment]
Great to hear, but i'm still puzzled what was wrong ;)
