### ISSUE TITLE
Error Compiling Logger.cpp.o

### ISSUE THREAD

**Issue by angelosan** [domoticz/domoticz#2448]
Platform:
Raspberry Pi3 B - Raspbian GNU/Linux 8.0 (jessie)
lib boost ver. 1.67
cmake ver. 3.11.2
Python Version: 3.4.2 (default, Oct 19 2014, 14:03:53) [GCC 4.9.1]

this error occurs from the

**commit 377ffb8b32d8bf0910b64459ab6e3a43aa05ce15**
Author: Rob Peters <info@domoticz.com>
Date:   Sun May 27 08:26:18 2018 +0200
converted boost:to_string to std::to_string where appropriate

until the last one

**commit 5a00ba936ab9b39606add5ab7a783297fcd1446f**
Date:   Wed May 30 16:41:41 2018 +0200

make clean
rm -rf CMakeFiles; rm -rf CMakeCache.txt; rm -rf cmake_install.cmake
cmake -DCMAKE_BUILD_TYPE=Release -Wno-dev .

thank's for your attention

-------
**/opt/domoticz/main/Logger.cpp: In member function ‘void CLogger::GetLogPreference()’:
/opt/domoticz/main/Logger.cpp:400:46: error: ‘to_string’ is not a member of ‘std’
    m_sql.UpdatePreferencesVar("LogLevel", 0, std::to_string(VBL_ALL));
                                              ^
/opt/domoticz/main/Logger.cpp:400:46: note: suggested alternatives:
In file included from /usr/local/include/boost/exception_ptr.hpp:9:0,
                 from /usr/local/include/boost/thread/exceptional_ptr.hpp:10,
                 from /usr/local/include/boost/thread/future.hpp:25,
                 from /usr/local/include/boost/thread.hpp:24,
                 from /opt/domoticz/main/stdafx.h:57:
/usr/local/include/boost/exception/detail/exception_ptr.hpp:493:5: note:   ‘boost::to_string’
     to_string( exception_ptr const & p )
     ^
In file included from /usr/local/include/boost/exception/to_string_stub.hpp:9:0,
                 from /usr/local/include/boost/exception/info.hpp:11,
                 from ### /usr/local/include/boost/exception/detail/exception_ptr.hpp:14,
                 from /usr/local/include/boost/exception_ptr.hpp:9,
                 from /usr/local/include/boost/thread/exceptional_ptr.hpp:10,
                 from /usr/local/include/boost/thread/future.hpp:25,
                 from /usr/local/include/boost/thread.hpp:24,
                 from /opt/domoticz/main/stdafx.h:57:
/usr/local/include/boost/exception/to_string.hpp:73:5: note:   ‘boost::to_string’
     to_string( std::pair<T,U> const & x )
     ^**

**Comment by gizmocuz** [comment]
I think your GCC version is to old, try updating 6.3 or higher

**Comment by angelosan** [comment]
solved 
thank you
