### ISSUE TITLE
Command line options for logging confusing !

### ISSUE THREAD

**Issue by gizmocuz** [domoticz/domoticz#2449]
I find the current command lines options related to logging very confusing,
and it looks some our double and could be removed/changed ?

I am currently working on a unix configuration file, the variable names could be slightly different then the command line options, but it is easy to make a link to the actual once

```
# Verbose log level (0 is none, 1 is all important, 2 is debug)
# verbose=1

# Log file (for example /var/log/domoticz.log)
# log_file=/var/log/domoticz.log

# Log level (0=All, 1=Status+Error, 2=Error , 3= Trace )
# loglevel=0

# Debug mode/Log trace level (enables internal debug traces to be available in the output log)
# debug=yes

# Log thread ID's (log thread ids; useful for trouble shooting.)
# logthreadids=yes
```

So we have a 'verbose' mode with 'debug',
and we have a 'debug' command line option

We have a 'log level' where we also have trace,
and we have a 'debug' command line option

something sounds very double !

How about we make the 'Log Level' a structure where we can enable options

{
 bool bLogStatus
 bool bLogError
 bool bLogTrace
 bool..
}

so for example the commandline/config will be
loglevel=status,error,trace

The 'trace' isnt that 'debug' ?

**Comment by gordonb3** [comment]
Don't forget -DDEBUG_WWW which is only available at compile time and you need to recompile to switch it off.

**Comment by gizmocuz** [comment]
Thanks for pointing out... 
There where some double loggings, and i removed the DEBUG_WWW and replaced them with (commented out) trace calls.
If certain parts of the web server needs to be debugged, they can be uncommented
Otherwise there was to much information logged

**Comment by dnpwwo** [comment]
For the Python plugins I added a logging mask to allow people to choose which parts they want to log.  Could we create one for the main logging?  e.g: EventSystem, WebServer, Hardware, ...

**Comment by gizmocuz** [comment]
@dnpwwo , that's for 'debug' logging
Sound like a good idea

So let's start with creating a log structure as proposed above, with 3 log levels

```
{
 bool bLogStatus
 bool bLogError
 bool bLogDebug
}

```
I think it is OK to say 'Trace' is also 'Debug' ?

and then an optional parameter for debug level (which is an enum/uint32_t bitfield)

```
enum _eDebugLevel
{
 DEBUG_LEVEL_NORMAL = 0x00000001.
 DEBUG_LEVEL_HARDWARE=0x00000002,
 DEBUG_LEVEL_WEBSERVER=0x00000004,
 DEBUG_LEVEL_EVENTSYSTEM=0x00000008,
 DEBUG_LEVEL_PYTHON=0x00000010,
 DEBUG_LEVEL_THREADIDS = 0x00000020,
...
};

```

That should be able to be specified from the commandline/configuration file as text of course like

debug_level = normal,python

maybe when a user enabled 'debug' logging, 'normal' should be included by default

we add a two additional log functions

```
	void LogDebug(const _eDebugLevel, const std::string& sLogline);
	void LogDebug(const _eDebugLevel, const char* logline, ...)
```

or call them just 'Debug' so you get _log.Debug(....)

Ps. the LogLevel could also be a enum/uint32_t of course

**Comment by gizmocuz** [comment]
With that we can remove

```
# Verbose log level (0 is none, 1 is all important, 2 is debug)
# verbose=1

# Debug mode/Log trace level (enables internal debug traces to be available in the output log)
# debug=yes

# Log thread ID's (log thread ids; useful for trouble shooting.)
# logthreadids=yes
```

And it should be feature proof

**Comment by gordonb3** [comment]
So where does loglevel `Normal` fit in here?

**Comment by gizmocuz** [comment]
@gordonb3 , indeed, we need to add this as well of course
Ohhh my... i see that one is used in various wrong ways as well, going to clean that up as well

**Comment by gizmocuz** [comment]
Starting implementation

Ohh my

```
			if (m_notification_log.size() >= MAX_LOG_LINE_BUFFER)
				m_notification_log.erase(m_last_error_log.begin());
```
That might trow an exception, or when there are logs of errors, a memory overflow

**Comment by gizmocuz** [comment]
Changed the logging system

https://github.com/domoticz/domoticz/commit/a188a925f9a85df822f7f7be79cf2bd935b0d6c5

There is still a lot not 100% ... a lot of developers used LOG_STATUS to log errors
Some even log crazy things like 

> _log.Log(LOG_STATUS, "Aura to much !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! to much");

or

> _log.Log(LOG_STATUS, " WIFI INDEX !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! to much");


or

> _log.Log(LOG_STATUS, "[Perform Queue Event] Q[%d] Now -> Retry: %d", i, EvQ[i]->LocalEventsDrop);

there are many things wrong with this, the least it should have is an identifier like "eHouse: blaaaa"

It might be a good idea to add this as parameter to the log function, but that will be a lot of work

**Comment by gordonb3** [comment]
breaking your own rule? ;)
>\+	// Gizmocuz: This has been in for quite some while, is it verified ?

**Comment by gizmocuz** [comment]
Nope, this is a comment to the author that has to many debug lines that could be removed
When it is not removed or i do not have feedback for some time, i will remove it
I could write it on a piece of paper but this seems more efficient
