### ISSUE TITLE
API : LevelNames & LevelActions array (in selectors) are dead

### ISSUE THREAD

**Issue by soif** [domoticz/domoticz#2454]
Was working fine, until about one month.

Now (v3.9476) when querying the API, the **LevelNames** field (used to be an array of `levels => names`) and the **LevelActions** field are wrongly replaced with an encoded string, ie

```
            [AddjMulti] => 1
            [AddjMulti2] => 1
            [AddjValue] => 0
            [AddjValue2] => 0
            [BatteryLevel] => 255
            [CustomImage] => 9
            [Data] => Off
            [Description] => 
            [DimmerType] => none
            [Favorite] => 1
            [HardwareID] => 6
            [HardwareName] => Dummy
            [HardwareType] => Dummy (Does nothing, use for virtual switches only)
            [HardwareTypeVal] => 15
            [HaveDimmer] => 1
            [HaveGroupCmd] => 1
            [HaveTimeout] => 
            [ID] => 00000100
            [Image] => Generic
            [IsSubDevice] => 
            [LastUpdate] => 2018-02-04 17:40:47
            [Level] => 0
            [LevelActions] => fHx8fA==
            [LevelInt] => 0
            [LevelNames] => T2ZmfE9ufEF1dG98Q29uZm9ydHxIZ2Vs
            [LevelOffHidden] => 
            [MaxDimLevel] => 100
            [Name] => c.Salon
            [Notifications] => false
            [PlanID] => 3
            [PlanIDs] => Array
                (
                    [0] => 3
                )

            [Protected] => 
            [SelectorStyle] => 0
            [ShowNotifications] => 1
            [SignalLevel] => -
            [Status] => Off
            [StrParam1] => 
            [StrParam2] => 
            [SubType] => Selector Switch
            [SwitchType] => Selector
            [SwitchTypeVal] => 18
            [Timers] => false
            [Type] => Light/Switch
            [TypeImg] => Light
            [Unit] => 1
            [Used] => 1
            [UsedByCamera] => 
            [XOffset] => 0
            [YOffset] => 0
            [idx] => 115
```

HTH

**Comment by gizmocuz** [comment]
Do at least a search here on github.
This is meant to be

**Comment by soif** [comment]
I DID a search, but only with ["LevelNames"](https://github.com/domoticz/domoticz/issues?utf8=%E2%9C%93&q=is%3Aissue+LevelNames) and this did not returned any issue **title** related to this. I later edited the title of my issue to add "LevelActions". I've now searched ["LevelActions"](https://github.com/domoticz/domoticz/issues?utf8=%E2%9C%93&q=is%3Aissue+LevelActions)  and still did not found any other related issue title.

After reading your comment, the only thing i can find now is a little comment from you in #2434 saying those fields are base64 encoded. As you can see the TITLE of this issue ("MDAH no connection to devices") as ABSOLUTELY nothing related to this issue.

So i am supposed to read EVERY issue, even those with title NOT related ?

You're a litte rude with me. :cry:  Keep cool, I 'm just trying to help.  :wink:

**Comment by gizmocuz** [comment]
@soif, not rude, but explained this to many times now.
Anyway, do you need the variables undecoded ?

**Comment by soif** [comment]
_I'm also developer, have many open source projects here at GH, while also maintaining a 30k visitors / day forum (since over 20 year........), so I'm pretty aware of the RTFM issue...._ :trollface:  

In this particular case, as you might see, I've done my best to RTFM first, and the evidence of an OBVIOUS duplicate issue, is at minimum  arguable. 😇

Anyway, this is now totally forgotten 😉

> do you need the variables undecoded ?

I personally can update [phpMyDomo](http://www.phpmydomo.org/) (8K downloads with 2/3 using Domoticz) to base64 decode the value (this is a 1 minute fix), but I can't figure the real advantage to now have LevelNames + LevelActions  base64 encoded.

BTW YOUR software is really excellent, and I use it (thru phpMyDomo) daily 🍻 🍻 🍻

**Comment by gizmocuz** [comment]
@soif , as said, did not want to be rude, but it is explained elsewhere.
It was a change that was needed, this selector switch is really strangely build.
When i changed it, i totally forgot about third party apps/interfaces... indeed phpMyDomo is probably also one that is using the selector switches.
My main goal is currently to solve as many issues as possible and then create a new stable.
Also just changed the logging completely, if phpMyDomo is also displaying a log tab, it might be worth looking at the current domoticz implementation

So don't worry, be happy ;)

**Comment by patrickferreira** [comment]
Hi @gizmocuz,
Thanks for the hard work.
I am sorry if this has been asked before (I looked beforehand). Is there a way, through the API, to know wether the selector switches are using the new or old system? That way I can implement it safely and make it work for both, at least until the current beta goes to release.

I could just check the Domoticz version and make a dev accordingly, just making sure there is no other way to go.

**Comment by dannybloe** [comment]
@gizmocuz maybe too late but shouldn't we just consider to restore the levelName/actionNames to non-decoded for backwards compatability and create a new attribute with the base64 encoding and use that in the GUI. That way, existing API uses out there have a change to migrate.
That shouldn't be too hard I guess. 

Again, I said it before, it is usually not a good idea to change the API like this without having at least some basic way of versioning the API.

Having said that, if reverting this change isn't an option, then how about **always** adding Domoticz' version in the API response (next to the status attribute). That way, future API consumers can check for this attribute and act accordingly.

**Comment by dannybloe** [comment]
@patrickferreira perhaps, in the mean time, you can use this call `/json.htm?type=command&param=getauth`. It will return the Domoticz' version number. Knowing after which version the stuff got encoded you can check for that.

**Comment by gizmocuz** [comment]
@dannybloe , we do have versioning in domoticz, each commit/build the 'APPVERSION' in appversion.h is increased.
And also indeed by the json api call you can get the version number
I can try to revert it... it's a beta, and we can do what we want with beta's right ? that is why we have beta versions, trying to make things better
The base64 was needed because encodeURIComponent was not sufficient for japanees for example
The way the selector switch was implemented was kind of different then the normal switch, you don't see base64 for normal switches for example

**Comment by dannybloe** [comment]
Yeah, I know it was needed, we should definitely encode the stuff. Just looking for a way to not break ye ole systams ou'there. 
Anyway, I was suggesting to return the version number with every json call, just as part of the standard response package, on the same level as `results`. Perhaps that's a good idea. From what I see now (in my Domoticz) that isn't the case.

**Comment by gizmocuz** [comment]
correct, you get it when you login or call getversion/getauth
For dzVents that is not needed, it's already available in the code
for mobile application, they are calling getversion/auth anyway, so they know the version, no reason to add this in every json output

**Comment by patrickferreira** [comment]
Yeah, what I had in mind is using the API to retrieve the version number, and do stuff accordingly.

It's the first time in 5 years that the API breaks like that, the Domoticz team always does quite an amazing job at keeping the API working backwards. 👍 

Would you be kind enough in telling me with what version it changed?  That way I can make a nice "IF/ELSE" in my code.

**Comment by soif** [comment]
>no reason to add this in every json output

except avoiding to have to call the API twice, VS one single request as it used to be.
So less load for the server, simpler code for the client, and a faster GUI experience for the final user.

**Comment by gizmocuz** [comment]
@soif , you have to call getauth or getversion anyway , it's the first thing you do i hope
@patrickferreira , as you can find in the issue tracker, v3.9476/9501, but i assume people have already installed a later version
Yes we always did a nice job, thanks! Sometimes a change is needed, hopefully not that often
Are you on slack as well ? The next time i/we can have a discussion in the developer channel

**Comment by patrickferreira** [comment]
Nice, didn't know there was a slack channel!
Can you PM me the details?

**Comment by gizmocuz** [comment]
@soif, are you on slack now ? if not, please contact me on the forum (gizmocuz)

**Comment by soif** [comment]
not on slack, 
just sent you a PM on the forum (wxop) . 
BTW I usually dont monitor your forum very often, You'd rather send me an email...

**Comment by soif** [comment]
> you have to call getauth or getversion anyway , it's the first thing you do i hope

No 

- "getversion"  is is not needed for the purpose of PMD so it is not used, ..._expect if the API is now supposed to not be backward compatible_ 😁 😁 😁 
- 'getauth' : I don't know what is it (not documented on the [wiki](https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s) ), and not needed by PMD
