### ISSUE TITLE
Counter values dissapearing

### ISSUE THREAD

**Issue by sweetpants** [domoticz/domoticz#2455]
Hi, opened this topic https://www.domoticz.com/forum/viewtopic.php?f=6&t=23682 on the forum, but no response yet.

After a "General: Counter Incremental" update the value disappears. Only a refresh of the screen brings the new value back until the next counter update. Also should the values in the dashboard not be swapped? In the Utility tab the today count appears in the top right corner.

It also looks like the Value Quantity & Value Weight can't be edited

**Comment by gizmocuz** [comment]
I corrected the Counter Incremental and RFXMeter display on the Utility/Dashboard tabs in the latest beta version.
I don't know if you are using the x64 arm version, if not, then the new beta (9623) should be available (soon)

Hope it solves the problem, and also the problems from the other user(s) on the forum

Is it possible you could check this ?

**Comment by sweetpants** [comment]
Just tested, looking much better
![image](https://user-images.githubusercontent.com/23421160/41201636-8260db0c-6cbb-11e8-8854-83a2bc00531e.png)

And the counter stays on screen now

Excep my Nefit Gas Meter is now screwed up
![image](https://user-images.githubusercontent.com/23421160/41201643-a2ccd1de-6cbb-11e8-909b-2610ed2d3cb0.png)

Edit: Sorry previous pictures where wrong (not dashboard)

**Comment by gizmocuz** [comment]
Thanks for testing, gas meter should be correct in latest beta version (9625)
Must have been a shock to see your new usage statistics ;)

**Comment by sweetpants** [comment]
Current value looks Ok now. I guess there is no total 'usage' count for Gas as you can get it through reports?

![image](https://user-images.githubusercontent.com/23421160/41220566-13b79f22-6d62-11e8-87d4-930e676795c5.png)

**Comment by rwaaren** [comment]
I see a total usage for Gas on my utility tab 
![knipsel](https://user-images.githubusercontent.com/24454798/41223059-fd8855b4-6d68-11e8-9c63-25b162c2d299.PNG)

**Comment by sweetpants** [comment]
But not on the dashboard while it shows it for incremental counters

**Comment by gizmocuz** [comment]
@sweetpants , i can't read that blue color in the first screenshot
Yes there is a total gas counter

**Comment by gizmocuz** [comment]
Okey i understand now, there is no counter value on the dashboard.
Yes that was not there... is that needed ? it's an always incremental counter
The incremental counter is a different story as it is not gas/energy
If you really miss it, please create another issue.
Closing this issue as this has been solved (working towards a stable here...)
