### ISSUE TITLE
Adjust temperature for virtual device with mqtt domoticz/in

### ISSUE THREAD

**Issue by fennec622** [domoticz/domoticz#2457]
Hi

I can't adjust temperature with device virtual mqtt domoticz/in temp

Is it normal 

thanks

**Comment by sweetpants** [comment]
Please address these kind of questions on the forum first. Github is only used for bugfixes.
Working fine here using the sample from the Wiki on V3.9560 using

mosquitto_pub -h 192.168.24.250 -u [username] -P [password] -t "domoticz/in" -m '{"idx":142, "nvalue":0, "svalue":"41.2"}'

**Comment by fennec622** [comment]
ok for command it's work

But if i wan't adjust temperature in web, adjust doesn't work

I use ESP8266 with tasmato for update temperature by mqtt with DHT11, but DHT11 value is 3° too high

![capture](https://user-images.githubusercontent.com/24509422/40884572-574806b6-6716-11e8-9468-2a226f2d0e49.PNG)

Adjust doesn't work with virtual device

**Comment by sweetpants** [comment]
Verified on V3.9560, can't adjust temperature on Virtual Temp device. For the time being, can you adjust it on the tasmato side?

**Comment by fennec622** [comment]
https://github.com/arendst/Sonoff-Tasmota/issues/2895

**Comment by gizmocuz** [comment]
The reason for this is/(was) that with a real device, when received, the adjustment value was applied
solved in beta 9564, could take an hour before it's available
