### ISSUE TITLE
Domoticz Offline Ubuntu 18.04

### ISSUE THREAD

**Issue by detxm80** [domoticz/domoticz#2459]
Hi, this is the problem:
./domoticz: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./domoticz)

it's under surveillance?

thanks

**Comment by gizmocuz** [comment]
Not yet. Are you using the binary or compiling yourself ?
I suspect that our build system is not using 18.04 yet

**Comment by detxm80** [comment]
Hi gizmocuz, i tried both and i ve the same problem..

**Comment by gordonb3** [comment]
Doesn't seem possible. There is no strict dependency from Domoticz on libcurl3. You are either referencing an old header file or you are reusing already compiled files that link to libcurl3.

**Comment by gizmocuz** [comment]
@detxm80 , did you got it working ?

**Comment by detxm80** [comment]
not @gizmocuz , i m not the onlyone that have this ploblem, look the domoticz forum....

**Comment by gizmocuz** [comment]
@detxm80 , sorry, i am unable to read every forum topic to find it
Please post the forums post link here

**Comment by detxm80** [comment]
yes sorry,
for example:
http://www.domoticz.com/forum/viewtopic.php?f=6&t=23357

i'm with new install and not update

**Comment by ronnyandre** [comment]
I have the same issue. It happened after I ran `sudo apt-get dist-upgrade`

As far as I can see, libcurl3 has been upgraded to libcurl4, thus making Domoticz not work as it looks for libcurl3, which is actually removed from the system by libcurl4.

Please make a fix for this.

**Comment by gizmocuz** [comment]
If you are using the binary version, have a look at our travis script and see if you can update this to use
As far as i can see it is using 'libcurl4-openssl-dev'

**Comment by martin3000** [comment]
This is in the current installer script:

> domoticz_DEPS=( curl libcurl3 unzip wget sudo cron libudev-dev)
