### ISSUE TITLE
Webinterface causes huge CPU consumption with Chrome (Mac)

### ISSUE THREAD

**Issue by Lyr3x** [domoticz/domoticz#2460]
Since a few days i see that the domoticz UI uses always about 90-100 % of my CPU when visiting with Chrome 67.0.3396.62 on my Macbook. This happens with a local connection as well as with a remote connection and its not happening with Safari. 
Ofcourse i tried to delete cache/cookies etc.

Would appreciate help with this, as i'm not sure what is the problem here.

**Comment by sweetpants** [comment]
Please discuss this on the forum first. Github is only used for identified bugfixes only. As you seem to be the only one having this, this could be something else. Also you have to supply more information, hardware, OS, current version etc etc
