### ISSUE TITLE
Selector Switches broken

### ISSUE THREAD

**Issue by Lyr3x** [domoticz/domoticz#2462]
I updated yesterday to v3.9571 (on Rpi 2)  and right after the update all selector switches were broken:
<img width="377" alt="screen shot 2018-06-05 at 08 24 32" src="https://user-images.githubusercontent.com/6078365/40958563-10398486-689a-11e8-8b65-dc03a5fc8e6f.png">

When creating a new Selector Switch it shows the same behavior.

**Comment by gizmocuz** [comment]
First try clearing the browser cache and appcache (two different things)
Search the github issues, this has been handled before
try editing the switch, and set the correct names again, or at least tell what name you are trying to give the actions

**Comment by Lyr3x** [comment]
Appcache and cache clear didnt worked out for me, but renaming one action of each selector switch resolved the problem. After the rename i changed back to the original name and it is working now. Weird.

Hope this will help others too.
