### ISSUE TITLE
Error log tab missing

### ISSUE THREAD

**Issue by sweetpants** [domoticz/domoticz#2463]
Since V3.9572 and 73, the error tab is missing in the log area. 2 users (including me) have reported this on the forum

![image](https://user-images.githubusercontent.com/23421160/40971554-4cab8bb6-68be-11e8-96d9-cb1afa52f892.png)

**Comment by gizmocuz** [comment]
Thats correct, means, you do not have errors

**Comment by gizmocuz** [comment]
When you enable debug logging, and have debug messages, you also get a new debug tab

**Comment by sweetpants** [comment]
Sounds logical this new approach. Thanks for explaining
