### ISSUE TITLE
Door Contact Delay

### ISSUE THREAD

**Issue by jannnfe** [domoticz/domoticz#2464]
Hello,
i have updated to the latest beta, fresh cleaned Cache und History.
I'm missing the On and Off Delay since the new update.
Strange fact: Before I added 30 Sec. Off Dalay and this is still working but the options to change the value is away.

Before: 
![37507084-35c7c170-28aa-11e8-9f57-a0db83fd41bf](https://user-images.githubusercontent.com/30130742/40998025-db902678-6906-11e8-9421-4a7d7e3d4095.png)

After:
![bildschirmfoto 2018-06-05 um 21 25 01](https://user-images.githubusercontent.com/30130742/40998063-eee97a76-6906-11e8-9e73-ab35ca5cc122.png)

And one more thing:
Latest beta the crosshair in the ground plan to select a room is totally broken in Safari, but this is another story.

Thanks!

**Comment by gizmocuz** [comment]
If you change the type to On/Off it is working again
I am now comparing version 8888 against 9571 and do notice a change
Will work again in upcoming beta version (9574), thanks for reporting
