### ISSUE TITLE
First Slack #development meet-up

### ISSUE THREAD

**Issue by dannybloe** [domoticz/domoticz#2466]
Hello fellow devs @gizmocuz and I thought it would be a good idea to have a more regular get-together on Slack. So, starting this Thursday (June 7th) at 19:30 (CEST) we will gather in Slack #development (or whatever other channel we are already member of). **So, cancel all your appointments, put the kids to bed early, or get up early (if you'r in another time-zone) and join in**. Let's see if we can join forces to get a new stable.

If you don't have a Domoticz Slack account and you consider yourself as a (future) Domoticz developer, please send me a message and I will invite you.

**Comment by dnpwwo** [comment]
Hmmm...that's 3:30 (AEST) the kids will (probably) be in bed but so will I

A little later could be better for the other hemisphere

**Comment by dannybloe** [comment]
Owh.. yeah.. that will be very hard to find some overlap there. Maybe next time we can do it in a morning or afternoon.. The idea is to have one every week.

**Comment by kiddigital** [comment]
Let's see if in 2023 we can have one or more development meetups :)
