### ISSUE TITLE
Xiaomi Yeelight Ceiling

### ISSUE THREAD

**Issue by airmonitor** [domoticz/domoticz#2467]
Hello.

Recently after updating firmware on yeelight ceiling I lost ability to manage lights from domoticz.
FW version on yeelight which was installed is 1.5.5_0181
Domoticz version v3.9573.

In logs:

 2018-06-07 11:26:55.129 Error: YeeLight: Exception: connect: No route to host
2018-06-07 11:27:00.325 Error: YeeLight: Exception: connect: Connection refused
2018-06-07 11:27:03.384 Error: YeeLight: Exception: connect: Connection refused 

When I ping device from domoticz:

ping 192.168.1.54
PING 192.168.1.54 (192.168.1.54) 56(84) bytes of data.
64 bytes from 192.168.1.54: icmp_seq=1 ttl=255 time=112 ms
64 bytes from 192.168.1.54: icmp_seq=2 ttl=255 time=32.7 ms
64 bytes from 192.168.1.54: icmp_seq=3 ttl=255 time=236 ms

I'm able to turn on/off lights on my other ceiling lamp which is using previous version of firmware, prior to 1.5.5_0181.

**Comment by gizmocuz** [comment]
is there a port change ? the default port was 55443
What is the new firmware version ?
Is the developer mode still enabled ?

**Comment by airmonitor** [comment]
Hi gizmocuz,

Thx for reply.
After your input I dig deeper into yeelight and found that firmware update turned OFF LAN control for this light.
After switching it back to ON I'm able to manage lights via Domoticz.

Thx.

**Comment by gizmocuz** [comment]
@airmonitor , that is why it is always good to use the forum ;)
