### ISSUE TITLE
Roadmap to stable 4.x

### ISSUE THREAD

**Issue by gizmocuz** [domoticz/domoticz#2468]
We all want to release a new stable version (4.x), and we are getting close, but there are some important issues that needs to be solved before doing so.
Let's add here the 'need to be solved' issues towards the 4.x release

Please use the zenhub plugin in combination with github to see the list
https://www.zenhub.com/

**Comment by rbisschops** [comment]
That would be great! The latest stable is getting close to 1 year now. I start running into problems with some of the bugs esp. with dZvents. Can't wait for the a new stable, don't want to go for betas for my two prod RPi's.

**Comment by sineverba** [comment]
Please remove the appcache from 4.X.

It is deprecated also: https://developers.google.com/web/tools/lighthouse/audits/appcache

The very good work is inficiated from them, also...

Have a nice day

**Comment by dannybloe** [comment]
Yay!!! Congrats!!

**Comment by gizmocuz** [comment]
Thanks! Forum post follows soon

**Comment by sweetpants** [comment]
Great work guys

**Comment by froguinou** [comment]
Very Nice job

**Comment by pepsi92** [comment]
Congrats!!! Many thanks to gizmocuz and all the contributors.

**Comment by Ascariota** [comment]
Yes Thx.
