### ISSUE TITLE
Login broken in latest beta versions -> cache refresh failed and offline screen

### ISSUE THREAD

**Issue by Olifant1990** [domoticz/domoticz#2469]
Running v3.9587 and I cannot get logged in into Domoticz.

After I installed the update, when I go to the url (https://localhost:1995/) I see the blue Browser Cache is being refreshed...
Please standby...

After a while I get a red error "Browser Cache Refresh Failed"
The console have 1 message: TypeError: event.url is undefined[Meer info] 192.168.0.2:1995:137:1
Which is this piece of code:
<code>
function logEvent(event) {
	var re = /https:\/\/my.domoticz.com\/.*\/html5.appcache/i;
	if (event.type == "error" && event.url.match(re) != null) {
		document.location = "https://my.domoticz.com/mydomoticz/dashboard";
	}
}
</code>

The network tab is showing this 403 error: https://192.168.0.2:1995/json.htm?type=command&param=getconfig

Then I tried to login (even the cache build failed) and then I get the Offline screen. Nothing more.
And stille the 403 error.

What I tried then:

I got to my development domoticz, updated it with the latest code and tried it with my current database.
Same problem there.
Then I tried it with a new database.
Now I can get in Domoticz.
When I then go to settings and set a admin username and password, with the login-page auth-type, I get the offline problem again, with the 403 error in the network tab.

Can someone help me with this?
Need to get back into Domoticz :(

**Comment by Olifant1990** [comment]
hm... when digging: something todo with https://github.com/domoticz/domoticz/commit/5a00ba936ab9b39606add5ab7a783297fcd1446f#diff-b178aa1b57f3c23ff1c6fbce4b495e30 ?

**Comment by Olifant1990** [comment]
@gizmocuz 
hm... when digging: something todo with https://github.com/domoticz/domoticz/commit/5a00ba936ab9b39606add5ab7a783297fcd1446f#diff-b178aa1b57f3c23ff1c6fbce4b495e30 ?

**Comment by Olifant1990** [comment]
For now I could solve it by setting the Preference "AuthenticationMethod" to 1 via phpLiteAdmin and restart domoticz. So, basic-auth is still working

**Comment by gizmocuz** [comment]
@Olifant1990 , There where two errors, one is the browser cache (was a floorplan whitelist issue), and the other looks like a cookie issue.
Working on it

**Comment by gizmocuz** [comment]
Fixed in beta 3.9589
