### ISSUE TITLE
ctrl_86plug.aq1 wall socket plug

### ISSUE THREAD

**Issue by AlbrtoSam** [domoticz/domoticz#2470]
I cant see wall plug consumption using V3.9587 ( i dont know if it worked before ).

I can see this in logs:

Status: {"cmd":"heartbeat","model":"ctrl_86plug.aq1","sid":"158d000221b1b2","short_id":54728,"data":"{\"voltage\":3600,\"status\":\"on\",\"inuse\":\"1\"}"}

I cant see power usage also...

**Comment by AlbrtoSam** [comment]
I already receive power usage on logs, but domoticz doesnt create a consumption device:

2018-06-08 01:16:23.668 Status: {"cmd":"heartbeat","model":"ctrl_86plug.aq1","sid":"158d000221b1b2","short_id":54728,"data":"{\"voltage\":3600,\"status\":\"on\",\"inuse\":\"1\",\"power_consumed\":\"1\",\"load_power\":\"3.71\"}"}

I saw where the problem is and i solved changing code. It works for me now.

On domoticz/hardware/XiaomiGateway.cpp

I Solved changing on line 872 name = "Xiaomi Smart Wall Plug";   with name = "Xiaomi Smart Plug";
I changed that to trigger line 531 if (Name == "Xiaomi Smart Plug") {
			if (load_power != "" && power_consumed != "") {
				int power = atoi(load_power.c_str());
				int consumed = atoi(power_consumed.c_str()) / 1000;
				SendKwhMeter(sID, 1, 255, power, consumed, "Xiaomi Smart Plug Usage");
			}

So i guess that a better way to solve it is just change on line 531:
if (Name == "Xiaomi Smart Plug") {
if ((Name == "Xiaomi Smart Plug") || (Name == "Xiaomi Smart Wall Plug")) {

**Comment by gizmocuz** [comment]
@AlbrtoSam , 

"if ((Name == "Xiaomi Smart Plug") || (Name == "Xiaomi Smart Wall Plug")) {"

sounds good, could you make a pull request for this change ?

Do you expect any more different "plugs" ?

If yes, then you can maybe also use

if (Name.find("Plug")!=std::string::npos) {
...

**Comment by AlbrtoSam** [comment]
I have never did a pull request before but im going to try.  Regarding the second part I saw the same structure along the code, and i dont think there will be another type of plug. ( there are some other xiaomi plugs but they are wifi )

**Comment by gizmocuz** [comment]
Great, here is the steps you need to take to make a PR
fork our git repo to your own account (using the fork button on top of our repo)
clone your fork (your repo)
make the changes
commit and push to your fork
then in github at your fork you will see a 'create pull request' button,
if you hit that button, you can make a pull request
you can keep pushing changing to your github repo/fork until the patch is merged

**Comment by AlbrtoSam** [comment]
I did it twice because i did it wrong first time. Im sorry ! 

Thank you @gizmocuz for your help!!!

**Comment by gizmocuz** [comment]
Great fix, thanks!
