### ISSUE TITLE
gnu++11 flag needed on Raspberry Pi

### ISSUE THREAD

**Issue by stappel** [domoticz/domoticz#2474]
The current source tree (rev 9597) does not compile anymore on a Raspberry Pi2. The GNU compiler (4.9.2) needs an extra compiler flags to accept C++11 files. 
for example it failes on:
`[ 20%] Building CXX object CMakeFiles/domoticz.dir/main/Helper.cpp.o
In file included from /usr/include/c++/4.9/chrono:35:0,
                 from /home/pi/domoticz/main/Helper.cpp:17:
/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
`

by changing the file CMakeLists.txt and adding 
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11")`
i got it working.

**Comment by gizmocuz** [comment]
I assume you did this underneath this line ?

IF(CMAKE_COMPILER_IS_GNUCXX)

**Comment by stappel** [comment]
pushed fix looks fine, running make now

**Comment by gizmocuz** [comment]
Thanks, me too ;) (2 arm systems (x86/x64) and ubuntu/osx)

**Comment by gizmocuz** [comment]
Looks like it's working ! Thanks!

**Comment by stappel** [comment]
sorry to disappoint you, but the flto is to much for a Raspberry.
I tried it three times to compile, but it runs out of memory on the final linking each time. and i did a reboot and a make clean try.

so please remove the lto option.

**Comment by gizmocuz** [comment]
Noticed that as well, removed it in the branch an hour ago
