### ISSUE TITLE
After latest change to Xiaomi Gateway in domoticz beta - Smart power plugs are no longer switchable

### ISSUE THREAD

**Issue by icemanxbe** [domoticz/domoticz#2477]
After the latest Update to XiaomiGateway.cpp, switches are read-only in domoticz.

I can see the current state. but if there is an attempt to change the state: Status: XiaomiGateway: SendMessageToGateway failed on first attempt, will try again.

And nothing happends.

**Comment by gizmocuz** [comment]
Why is this course 5 minutes later?
