### ISSUE TITLE
http poller returns error in domoticz

### ISSUE THREAD

**Issue by ajay10000** [domoticz/domoticz#2479]
Raising this bug as I have upgraded to v3.9560 and still getting this error continuously:
2018-06-08 16:42:59.779 Error: CLuaHandler: cannot read /home/pi/domoticz/scripts/lua_parsers/: Is a directory

This error did not occur in 3.5837, as I was logging weewx weather data to domoticz in that version.

I have posted to this topic without any luck: https://www.domoticz.com/forum/viewtopic.php?t=18699

I don't have any experience with C but looking at the source code in LuaHandler.cpp, line 211, the 'script' variable seems to be missing or empty, thus the error above.
std::string fullfilename = lua_Dir + script;

I think the 'script' variable would be the name of the lua handler in /home/pi/domoticz/scripts/lua_parsers, which in my case would be weewx_json_thb.lua. It must be pulled from the database at some stage but that is where I get lost.

My hardware setting for the http poller are shown in the attachment.
![image](https://user-images.githubusercontent.com/19726706/41197440-12087180-6ca2-11e8-8cc9-6078f691ef3f.png)

I am parsing weather station data from weewx and have checked it is being generated and the weewx server is working and the current.json file shows the correct data in a browser (example below)

current.json in browser:
title "Current Weather"
time "08/06/18 18:00:00"
alt "250 meters"
hardware "WH1080"
uptime "1 day, 10 hours, 44 minutes"
serverUptime "1 day, 9 hours, 59 minutes"
weewxVersion "3.6.2"
stats
current
outTemp "10.4"
windchill "10.4"
heatIndex "10.4"
dewpoint "9.2"
humidity "92"
insideHumidity "83"
barometer "1022.7"
windSpeed "1"
windDir "346"
windDirText "NNW"
windGust "4"
windGustDir "315"
rainRate "0.0"
insideTemp "12.2"
almanac
sun
sunrise "07:27:58"
sunset "17:02:28"
moon
phase "Last quarter"
fullness "31%"

I hope this helps someone to track down this bug.

Many thanks - Andrew

**Comment by gizmocuz** [comment]
@ajay10000, send you a private message for a debug request on the forum

**Comment by ajay10000** [comment]
I'm disgusted with myself for not trying another browser/private browsing mode and report that this was a browser cache issue, due to a change in the number of http poller fields.

Please accept my apologies!

Andrew
