### ISSUE TITLE
getVersion request fails

### ISSUE THREAD

**Issue by stas-demydiuk** [domoticz/domoticz#2481]
In the 3.9623 beta I see that request
`/json.htm?type=command&param=getversion`
fails and additionally it causes the whole domoticz to restart after each such request

I wonder if someone could take a look.

Thanks,
Stas

**Comment by sweetpants** [comment]
Cannot confirm this on Linux compiled by source
{
   "DomoticzUpdateURL" : "",
   "HaveUpdate" : false,
   "Revision" : 0,
   "SystemName" : "linux",
   "UseUpdate" : true,
   "build_time" : "2018-06-10 14:05:07",
   "dzvents_version" : "2.4.6",
   "hash" : "415a22d",
   "python_version" : "3.5.2 (default, Nov 23 2017, 16:37:01) \n[GCC 5.4.0 20160609]",
   "status" : "OK",
   "title" : "GetVersion",
   "version" : "3.9623"
}
