### ISSUE TITLE
unexpected result  with json.htm?type=devices&filter=all&used=true&order=Name (related to commit fd814fe ?)

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#2482]
"ActTime": 1528646429,
"AstrTwilightEnd": "00:00",
....
**"app_version": "szAppVersion",**

I expected to get the Domoticz version in the return.

**Comment by gizmocuz** [comment]
Haha... Is it is provided in quotes... Need to fix that late

**Comment by rwaaren** [comment]
Solved in V3.9624
