### ISSUE TITLE
Support OpenZWave options.xml settings being changed from Domoticz GUI

### ISSUE THREAD

**Issue by ben423423n32j14e** [domoticz/domoticz#2483]
Manually editing OpenZWave Config/options.xml allows significant performance optimization, these options should be available for change via the Domoticz web GUI:

Setup > Hardware > OpenZWave > Setup > Controller > (I'm thinking the settings should go here).

Based on my experience and others here: https://www.domoticz.com/forum/viewtopic.php?f=24&t=10702&p=106018

I'm thinking these should be the default or similar (safe settings) within Domoticz for the new options:

RetryTimeout value="3000"
PerformReturnRoutes value="true"
AssumeAwake value="false"
ThreadTerminateTimeout value="4000"

Personally I run a RetryTimeout of 1500 with good results on my setup with about 60 devices so 3000 should be a conservative value based on experiences others have reported in the above thread.

Issue created as per request: https://www.domoticz.com/forum/viewtopic.php?f=24&t=19307#p183091

**Comment by gizmocuz** [comment]
Thanks for adding! Great idea

**Comment by ben423423n32j14e** [comment]
No worries, I don't have the coding skills to add this myself.

I just play with Lua, PHP, BASH and Python (wish I knew C++), maybe in the future. :)

**Comment by gizmocuz** [comment]
Oeps, sorry for the above messages, was playing around with the github project page

**Comment by gizmocuz** [comment]
ThreadTerminateTimeout seems not being used in OZW, only with WinRT, and domoticz is not a WinRT application

**Comment by gizmocuz** [comment]
- Implemented: OpenZWave, controller options for RetryTimeout, AssumeAwake and PerformReturnRoutes can now be set

Will be available in the next beta version. If you select the controller (node 1), you can change these settings:

![image](https://user-images.githubusercontent.com/2265299/41818970-0d8d7016-77b9-11e8-9ec1-1039e475b25a.png)
