### ISSUE TITLE
Master / Slave Setup Pyhon Plug-in

### ISSUE THREAD

**Issue by Kevincoenen** [domoticz/domoticz#2484]
> OS: Ubuntu 16.0.4 LTS
> Hardware: Intel NUC
> Domoticz Version: 3.9625 - 529bd73d
> Python Version: 3.4.8 / 3.5.2

When using a Master / Slave Setup in Domoticz, devices using the Python Plug-in system do not show up as shared devices. Adding a dummy devices does work, so the internal communication between the Domoticz devices is working. The Domoticz and Python versions are the same on both devices, and I also tried to downgrade from Python 3.5.2 to Python 3.4.8, but to no avail. The log doesn't generate any error's, and all seems fine according to the log.

**Comment by dnpwwo** [comment]
@Kevincoenen, 

Can you be a little more specific?

What plugin are you using (or post your own)? Is the Python device the master or the slave? 

What did you do to test it?

**Comment by Kevincoenen** [comment]
@dnpwwo I'm using the Denon/Marantz Plug-in that you created (using version 3.2.3), and the Sonos Plug-in that gerard33 made. The Python device is the slave device. As test I created multiple dummy switches (On/Off / Dimmers) on the slave device and these show up on the master. The slave device is a fresh installation of Ubuntu 16.0.4 which is up to date, and I installed the latest Domoticz. If you need more information, I'm glad to give it to you.

**Comment by Siewert308SW** [comment]
Same for dummy devices.
It's because the device ID or Unit code are the same for newly created devices.
Found out when I made several new dummies with different ID or Unit type.
But also tried the run several plugins (renamed) which amended to create different ID's.
The all devices are seen by the master.
Don't know how to resolve this unfortunately.

**Comment by gizmocuz** [comment]
After a new stable I will add an origin-id

**Comment by Siewert308SW** [comment]
thx...

**Comment by arpeesee** [comment]
สวัสดีครับ

**Comment by pipiche38** [comment]
This would be a nice to have it in the roadmap as I got several complains from users whom cannot use the Master/Slave setup with devices which are controlled via the Python Plugin framework.

**Comment by waltervl** [comment]
This is indeed a frequently requested feature (or not expected lack of functionality ;-) ) by users on the forum.

**Comment by abroeders** [comment]
It seems that devices created with the 'MQTT Autodiscovery plugin' are also affected with this bug. Master slave doesn't work on them.

**Comment by gizmocuz** [comment]
Yes this is a known problem that I hope to address soon. But on your 'other' Domoticz installation you can just add another MQTT hardware instance to control them ?

**Comment by Barry40** [comment]
I hope this is getting fixed asap!
Today my hole new (old sonoff) zigbee network has been unworking because the remote does not share any device.. grrr

**Comment by gizmocuz** [comment]
@Barry40 , Okey, but this never worked
But I assume you are using Zigbee2MQTT, and in this case it is extreme easy to use remote locations as both Domoticz instances connect to MQTT
You get a 100% same experience on both instances

**Comment by Barry40** [comment]
Hi gizmo, thnx for replying.
No i 'm using phoscon. I added deconz plugin to my other (remote) side as well and this worked, so for me this case can be closed for now.
Only thing is that it has some delay or something on some zigbee pirs, when motion is detected its take some seconds before the lamps goes on.
I have to look into this, but thats not the case noe.
Sorry for the interrupt!

**Comment by gizmocuz** [comment]
Okey so time to switch to Zigbee2MQTT

**Comment by Barry40** [comment]
I will check!
Why is it better then? ;)

Op do 16 mrt. 2023 09:29 schreef gizmocuz ***@***.***>:

**Comment by gizmocuz** [comment]
Very large community with the most hardware supported.
It also has a very nice web interface to add/configure/control your nodes.
And for some devices it is possible to update the firmware.
It also works with other software (like homebridge)
And because it is MQTT, you have access to it from remote locations as well.

**Comment by Barry40** [comment]
I have looked into before, but i tought it was better to use the deconz
plugin because it has a shorter connection to phoscon, but it looks like i had it wrong then 🤭
Sounds way better.. will install and let you know! Thanks!

Op do 16 mrt. 2023 09:38 schreef gizmocuz ***@***.***>:

**Comment by mikey-hub** [comment]
I just set up the DSC Alarm via EnvisaLink plugin on a slave, unaware of this old bug. Is it realistic to hope for a fix in the near future or do I need to rebuild my setup? 

The latter include the move of individual hardware / devices to other Domoticz services (slaves or the server). The issue with this is that I can't find any information on how to move an individual hardware (or device) to another Domoticz service and preserve its history. I can only find information on moving the full database. Any suggestions? Thanks

**Comment by CreasolTech** [comment]
Hoping that it will be possible to export any device from one "slave" domoticz to a "master" one soon, even if devices on the slave domoticz are managed by a python plugin!

**Comment by mikey-hub** [comment]
> Hoping that it will be possible to export any device from one "slave" domoticz to a "master" one soon, even if devices on the slave domoticz are managed by a python plugin!

@CreasolTech - is this something being worked on at the moment, do you know?

**Comment by bertrand-benoit** [comment]
Any news ?

**Comment by gizmocuz** [comment]
I think until now nobody implemented this yet..... The whole master/slave needs to be changed, should not be that hard, but it's something after the 2024.1 release... (which is not that long away)

**Comment by gizmocuz** [comment]
Please check beta 15790 ... Both client/server need to run on this beta... quite some things have changed.
You probably will get new devices, so make sure 'Accept new hardware/devices' is enabled in the settings

**Comment by bertrand-benoit** [comment]
> Please check beta 15790 ... Both client/server need to run on this beta... quite some things have changed. You probably will get new devices, so make sure 'Accept new hardware/devices' is enabled in the settings

Ok I'll try that.

**Comment by gizmocuz** [comment]
(Try the latest beta version as 15790 is from two weeks ago)
