### ISSUE TITLE
MySensors SmartSleep implementation

### ISSUE THREAD

**Issue by MarcusKlerks** [domoticz/domoticz#2487]
Thanks for the implementation of SmartSleep and it works... but only sometimes.

I think the reason for this is the reverse order that is implemented in MySensorsBase.cpp. According the description in [https://www.mysensors.org/apidocs/group__MySensorsCoregrp.html#gad9e11c9a491940337f7354f553391f2f](url) ("send heartbeat and process incoming messages before going to sleep") the processing of any waiting (and incoming) messages should be done BEFORE going to sleep and thus after the I_PRE_SLEEP_NOTIFICATION message in stead of after the I_POST_SLEEP_NOTIFICATION as is currently implemented (that is if I interpret the code correctly). 
The handling of waiting messages is done during the wait time preceding sleep as defined by MY_SMART_SLEEP_WAIT_DURATION_MS. Playing with that time (think of seconds) made it work but not reliable. And of course waiting seconds is far too long.

**Comment by MarcusKlerks** [comment]
Working like a charm now, thanks for the update.

**Comment by gizmocuz** [comment]
Cool! Thanks for the feedback!
