### ISSUE TITLE
Nest Auto Away switch toggling rapidly

### ISSUE THREAD

**Issue by julianmclean** [domoticz/domoticz#249]
Seems to be something broken with respect to Nest Thermostat/Protect setup, which _may_ be contributing to the observed behaviour:

A few days ago (November sometime), I started experiencing an issue with my Nest setup. I'm afraid I do not know the Domoticz code version, but whenever my Nest is put into away mode (either automatically or manually), the mirrored switch in Domoticz would rapidly switch on/off repeatedly (every couple of seconds) until the Nest is put back in Home mode. As I use my Nest as the main driver of presence in the home, this was causing havoc with related Events!

I have tried deleting and re-adding the hardware/switches, and now experience an additional problem, which potentially could be related. In my house (and Nest account), I have 1 Thermostat and 3 Protects. When I now add the Nest Hardware, I get 5 devices, 2 for SetPoint/Thermostat as expected, but for the other 3, I appear to get a fairly random result. The 3 devices always have the default names I have assigned to my 3 Protects (Hall, Upstairs, Loft), however I can see that only some of the device types are set as Smoke Alarm (from multiple tests, between 0 and 2 of them). The other(s) are Lighting On/Off. None of them are labelled as "Auto Away" (which I think was the default label for Away functionality?). When I manually toggle the Away state on my Nest, I can see one of these switches react (i.e. it actually IS the Auto Away one, just not labelled correctly), and start to exhibit the same rapid toggling behaviour. I have updated to build 3774 but still experiencing the same issue, no matter how many times I delete/re-add the Nest.

If I had to guess, then the code changes to support the Protect and the multiple Thermostats are causing an issue, as the timeline seems to roughly align with Domoticz version history notes.

Happy to provide any other details as required.

**Comment by gizmocuz** [comment]
We updated the nest code recently, do you still experience this issue ?

**Comment by julianmclean** [comment]
I will set it back up again on the latest code and report back. (I had removed the Nest hardware and resorted to a one-way integration via IFTTT!)

**Comment by julianmclean** [comment]
I've set it up again, and so far, so good. None of the Nest Protect devices are showing up any more, and the rapid-toggling behaviour is also resolved. I have tried setting Home/Away from both the Nest app and Domoticz and both seem to remain in sync as expected. Suggest can close this issue and I'll re-open/open another if I have any more problems. Thanks - great product!

**Comment by gizmocuz** [comment]
Thanks for the feedback, glad it's working !
