### ISSUE TITLE
Cannot Delete Timers anymore

### ISSUE THREAD

**Issue by sweetpants** [domoticz/domoticz#2495]
I don't know if this needs to be resolve before new stable, but this morning I discovered that I cannot delete timers anymore https://www.domoticz.com/forum/viewtopic.php?f=6&t=23854
I'm on V3.9639 at the moment. I can still add, edit timers but not delete them then I get "Problem Deleting Timer"
BTW, the same counts for scene timers

**Comment by gizmocuz** [comment]
If that's the case it needs to be resolved for sure

**Comment by sweetpants** [comment]
Update: Seems to work with FF but not in Chrome and Vivaldi also Chrome incognito mode has the same issue. Investigating further.

Edit: Seems to be browser related. Does not work on Chrome (incl Incognito) and Vivaldi, but works on Firefox

Edit: Chrome, Edge and FF on W10 also do not work

**Comment by gizmocuz** [comment]
If that is the case there should be a error message on the chrome developer console I think.. could you check this?

**Comment by sweetpants** [comment]
Did some checking, but i'm not sure if i fully understand. When pushing the 'delete' button, nothing happens in the console. Starting the GUI and going to the switch timer menu produces:

![image](https://user-images.githubusercontent.com/23421160/41505603-a675252e-720c-11e8-9bf6-b63849e7bea4.png)

**Comment by sweetpants** [comment]
Did some additional debugging and found:

XHR finished loading: GET "http://192.168.24.250:8080/json.htm?param=deletetimer&type=command".

Should there not be an idx in there?

**Comment by gizmocuz** [comment]
Yes there should... See webserver.cpp deletetimer

**Comment by sweetpants** [comment]
I see, but my Chrome browser is sending above API call which is wrong and results in:
{
   "status" : "ERR"
}
hence the error it can't delete the timer.
When using FF it sends the API call

GET "http://192.168.24.250:8080/json.htm?idx=71&param=deletetimer&type=command"
Which is right

**Comment by sweetpants** [comment]
I can't figure out why this is going wrong on different browsers. I see timers are beeing handled by DeviceTimersController.js but I can't see why it does not take the timerIdx when calling the API.

**Comment by sweetpants** [comment]
@stas-demydiuk Thank you soo much. As soon as GizMoCuz commits this PR, I will test it.

**Comment by sweetpants** [comment]
@stas-demydiuk Tested the changes in app.js on my test machine and this fixes the "Timer Delete"  issue. Now wait for GiZMoCuz to merge it into the development branch. Thanks again

**Comment by gizmocuz** [comment]
@sweetpants , have not looked at the PR, but found out that the problem seems to come from 'utils.confirmDecorator', it does not seem to parse the parameter to the deletetimer function.
(called from DeviceTimersController.js, line 12)
Don't be to fast calling 'help', this was a nice exercise.
Sure i'm going to merge the PR, but after i solved the puzzle here ;)
