### ISSUE TITLE
No more exit in menu

### ISSUE THREAD

**Issue by sineverba** [domoticz/domoticz#2496]
Update from last stable to 3.9639.

There isn't anymore button "exit/logout"

![immagine](https://user-images.githubusercontent.com/2634842/41504921-d2ceadee-71fc-11e8-849d-473fa5506b43.png)

Another thing: in settings, is it possible to split the password page in another tab? Every time, 'cause autocompile, need to clean values before pushing "save".

**Comment by sweetpants** [comment]
Please discuss this on the domoticz forum first
Have you cleared your browser and app cache? (browser and app cache are two different things)
Tried another browser?
Checked www/js
if domoticz.js keep it
if domoticz,js.gz delete it
restart domoticz

**Comment by sineverba** [comment]
Ah, for restart no problem, see next issue (worse than this). My Domoticz restarts After crashes 2/3 time at day.

 I did not specify, but I did try 3 different browser (Chrome FF and Edge bleah) also in incognito.

Unfortunately I insist that appcache (deprecated by uncle Google itself) creates more trouble than necessary. And every update is a pain with this appcache (IMHO and based on forum threads)

The logout is present in the other themes, not in default.

**Comment by sweetpants** [comment]
I still cannot confirm the logout button problem with default theme using Chrome Version 67.0.3396.79 (Official Build) (64-bit) on Ubuntu 16.04-3 LTS

![image](https://user-images.githubusercontent.com/23421160/41520983-a130144c-72d0-11e8-969b-c7c1aa67c9cb.png)

**Comment by gizmocuz** [comment]
@sweetpants , user complains about appcache more then once and needs to clear it

**Comment by sweetpants** [comment]
I know, i keep telling this over and over. But people do not read the RED forum rules. But this user wants that domoticz is not going to use the appcache anymore in the future because it is depricated bij Google.

**Comment by gizmocuz** [comment]
@sweetpants , yes, but we need it for offline applications on the users homescreen (iOS/Android)
So it is not only used in the browser. And not only by Chrome
And... he/she needs to come up with a PR that changes it
