### ISSUE TITLE
Error: Domoticz (YeeLight) received fatal signal 6 !... 

### ISSUE THREAD

**Issue by sineverba** [domoticz/domoticz#2497]
I had from several days this error on stable.

I did read previous issues and I did decide to move to latest beta.

After some hour, bang, new fatal signal 6.

```
2018-06-17 14:14:23.300  Error: Domoticz received fatal signal 6 !...
2018-06-17 14:14:23.304  Error:   /home/sineverba/domoticz/domoticz() [0x25458c]
2018-06-17 14:14:23.304  Error:   /home/sineverba/domoticz/domoticz(_Z14signal_handleri+0x4c) [0x254644]
2018-06-17 14:14:23.304  Error:   /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0x76bf56b0]
2018-06-17 14:14:23.304  Error:   /lib/arm-linux-gnueabihf/libc.so.6(gsignal+0xa0) [0x76bf445c]
sineverba@rpi3:~ $

```
Neither monit can catch it. How can I solve?

I have only some temperature sensor, no meter involved, a Yeelight controller and a relay.

Thank you

**Comment by gizmocuz** [comment]
Are you doing anything with python ?
What domoticz version are you using ?
Have you tried to disable all hardware and let this run for 2 hours, still working, enable 1 other hardware, test 2 hours, working, enable another
This way you find out what happens

**Comment by sineverba** [comment]
Nothing with python.
Crashes are very random. 1 every 24h, 7 every hour.... I did not try disable all hardware. I have mysensors  and yeelight.

Btw, the configuration is same from about 1 month. Crashes are more recent.

**Comment by sineverba** [comment]
I can add that it happens (also) at every local midnigt...

**Comment by gizmocuz** [comment]
Okey, try disabling the hardware and debug step by step plz

**Comment by gizmocuz** [comment]
How are the tests going ? Did you try with the latest stable ?

**Comment by sineverba** [comment]
I'm happy that you asked me. GOt so many crashes that... do you want laugh? On night from friday and saturday I did reinstall ALL and restart with a total clean installation. Of course I got the 3.8153... For some hour I did not get the last 4...

But, I'm installing on another PI another test environment with last stable.

I will not know ever what done with previous installation. But... long story made short: 1 environment stable for real stuff and 1 for test :)

**Comment by gizmocuz** [comment]
That is the ideal setup indeed ! ;)
Plz let me know how it goes, if it is working now

**Comment by sineverba** [comment]
Got same error on the fresh install, totally clean, 3.8153, on raspberry Pi3 with last raspbian available at 4/18.

I'm removing the yeelight controller. So i have motherboard and my sensors 2.2.0 gateway (installed on Pi itself).

A question: does Yeelight Controller use python? Because Domoticz log everytime present the "failed load Dynamic pitython bla bla bla). Never cares about It in 1+ year.

**Comment by gizmocuz** [comment]
No it does not use python. (All native domoticz hardware is written in c++)
Domoticz tries to load python, but can only do so when python 3.5+ is installed.
In this case, it looks you do not have this installed. (not a bad thing! Unless you want to do something with python)

Okey, so we can conclude that the problem is with the Yeelight hardware plugin? If you disable that, it continues to work ? (no crash)
Or could it be the motherboard hardware plugin ?

**Comment by sineverba** [comment]
I will tell you in a week of test. removed yeaterday, if no crash in a week we can think issue is Yeelight. In next days I will add yeelight on test Pi1 with last stable, btw. For the moment test PI1 (with only one Mysensors + motherboard) no crash at all.

Production Rpi3 (with 4 Mysensors + motherboard) no crash from the moment I removed yeelight.

**Comment by gizmocuz** [comment]
Thanks, let me know, if thats the problem i will connect some yeelights here to test

**Comment by sineverba** [comment]
Small update:

**"Production environment"**: PI3 + 4xMysensors 2.0.0 + Hardware Dummy + 2X Dummy switches + Motherboard + Domoticz 3.8153 (stable).
- Fresh setup 23/06/2018 with also yeelight hardware
   -- Got +2 crash every day.
   -- Removed Yeelight Hardware on 24/06/2018: +24h ago, no crash after I removed the Yeelight Hardware.

"Development environment": Pi1 + 1xMysensors 2.0.0 + Hardware Dummy + 2X Dummy switches + Motherboard + Domoticz 4.97 (stable).
- Fresh setup 23/06/2018: never got a crash.

I'm proceding to add the Hardware Yeelight PHP on development environment.

**Comment by gizmocuz** [comment]
@sineverba , would be better if the internal yeelight plugin was fixed....
What kind of lamp did you add ? Do you perform any actions when the crash is happening ?
Do you have timers...
Anything you can tell me to replicate the issue here?

**Comment by sineverba** [comment]
The lamp is the RGB. Atm no crash in both environment. Crashes are very random, but I did notice often at midnight.
No particular action: last times all crashed during my absence and lamp off. Last crash was after 30/40 min that lamp worked as flow.

No timers at all.

I'm not anymore sure that issue is Yeelight.... I was sure that development would crash on midnight, but no.

The only thing sure is that after +36h that I removed the Yeelight from PRODUCTION environment, no crash at all. 

Maybe someother fixed on 4.97 ? But I got crash until the last beta before last release..... :(

Next things I will try:

1 - Downgrade the DEVELOPMENT to 3.8153 (maybe, don't know if it worths) and add yeelight hardware
2 - Upgrade the PRODUCTION to 4.97. After a week, I will add the Yeelight Hardware (after removing from DEVELOPMENT, to no conflict).

**Comment by sineverba** [comment]
**I can confirm at 99% that issue derived from Yeelight.**

Today I did reset my lamp and after a while boom! "Error 6" (first message) on DEVELOPMENT enviroment (the only one with Yeelight Hardware control).

**Comment by sineverba** [comment]
Update.

I can confirm that Domoticz crashes with error 6 resetting the Yeelight (e.g. poweron and poweroff cycle for 5/6 times). And other crashes **random** during the use. But it doesn't crash anymore if lamp is shutdown (via software, power connected but shutdown via his APP or Domoticz).

===== How try reproduce =====

So, if lamp is linked to main but poweroff from APp or Domoticz, no crash in +7 days.
If I power on the lamp from Domoticz or APP and "leave on" in every mode (scene, light, etc etc), no crash or very little crash.

If I reset the lamp (after that is added to Domoticz, reset is made by physical switch on and switch off for 5/6 times) I got the error 6 crash.
If I play "too heavy" with lamp (scene, on, off, light, brightness, scene, etc) I could have a error 6 crash.

Maybe too much information to Domoticz?

===== /How try reproduce =====

**Version tested: 3.8153 - 4.9700 - 4.9732**

Rpi1 and Rpi3 + uSD new transcend brands class 10.

Hardware: MySensors 2.0.0 + Motherboard sensors + Dummy Switches. Custom Let''s encrypt certificates.

The only one complaints from Domoticz are by Python version (I don't use Python) and DHT for certificate (that I don't care both).

**Comment by sineverba** [comment]
Yesterday I did restart my router, for issues communication. Of course Yeelight lamp (off) lost his signal. When it did restart, bam! Error 6 on Domoticz.

**Comment by gizmocuz** [comment]
Added some safety checks now. Please try beta 9764

**Comment by rwaaren** [comment]
@sineverba Does this thumbs up (cannot see when it was added)  means this issue can be closed ?

**Comment by sineverba** [comment]
Yes. I'm closing it.
