### ISSUE TITLE
Notification not working for blinds

### ISSUE THREAD

**Issue by devrosx** [domoticz/domoticz#2502]
hello, dunno if its bug or feature request
but Notification for blinds type not working (in menu type is only Switch On / Switch Off state) so in menu should be Open/close state (so probably other switch states are also missing)

thanks

**Comment by gizmocuz** [comment]
Have you tried to do this with dzVents or blockly ?

**Comment by devrosx** [comment]
hello, yes with dzVents state notification working without problem for any types, but the way it works now in Notification panel is imho confusing for new users (i tried first use Switch on for open state and Switch off state for close state) which does not work...

**Comment by waltervl** [comment]
Notifications on Blinds are working when using On/Off which should be interpreted as Open/Close (or inverted).
Blinds with a percentage also have a level notification option.
So closing this issue.
