### ISSUE TITLE
GCM device notifications not working in latest beta

### ISSUE THREAD

**Issue by bostjane** [domoticz/domoticz#2504]
Hi,

I've upgraded from stable v3.8153 to beta v3.9657 on Windows and Mobile Device notification no longer works. Log says:
Error: SQL Query("SELECT SenderID, DeviceType FROM MobileDevices WHERE (ID IN (pushover))") : no such column: pushover

**Comment by bostjane** [comment]
I wasn't specific enough. I was talking about GCM messaging. The log message appeared when send via dzVents. When pressing "Test" button for GCM in Settings->Notifications there was no such message, but messaging still doesn't work.
After going back to stable release it works just fine...

**Comment by gizmocuz** [comment]
Not a fix, but could it be you specified a certain device ? ( |Device= )
(Just looking at the code)

**Comment by bostjane** [comment]
You mean if I specified a device when sending notification in dzVents? No I haven't, here is the line:
domoticz.notify('Vlom v Bitnjah#devid=v92E48E15FA935AA&DETAILS='..device.name)

I did a few more test and when hitting the "Test" in Settings->Notifications notification arrive almost instantly in stable release, while in beta notification arrive with minutes delay at best, in most cases does not arrive at all. Interestingly, log says success.
Using dzVents with line above, notification never arrive and SQL error appears in log. 

I have two mobile devices in Setup->More options->Mobile Devices, both enabled for notification. I don't know if it has anything to do with it, but I tested beta on different computer with imported Domoticz database and OZW config file. Everything other seems to work just fine.

Further, I use two notification systems, GCM and Custom http. I would like to point out that when notification is called from dzVents, custom http works, only GCM fails.

**Comment by gizmocuz** [comment]
@bostjane , i think there is no difference in code between the stable or beta, but lets find out by looking at the history of the GCM notification helper:

https://github.com/domoticz/domoticz/commits/development/notifications/NotificationGCM.cpp

Okey, there seems to be 5 changes, some of non importance

Thats all i can do as i don't use GCM, and don't know how to debug.

Maybe @galadril or @Olifant1990 could have a small look onto this one ?

**Comment by galadril** [comment]
If you use the test button on the mobile devices page to test a push notification.. does that one work?
It's the green arrow icon at the right side:

![afbeelding](https://user-images.githubusercontent.com/14561640/41707833-53f7476a-753f-11e8-8de5-cabbdfbbac39.png)

**Comment by Olifant1990** [comment]
@bostjane, If you can receive the test message, GCM is working fine.
That you do receive them late sometimes has something to do with the energy saving system from Android.

I am running beta version 9639 and I do receive notifications, send by LUA script.
Maybe a bug in dzVents or something? I am not familiar with dzVents.

**Comment by galadril** [comment]
Indeed.. but looking at the error.. "no such column: pushover" sounds for my like a dzVents bug maybe>?

**Comment by gizmocuz** [comment]
It seems to come from 'NotificationGCM.cpp', line 52 ? If that is the case, i think it wants to find a string in an integer ID column ?

**Comment by Olifant1990** [comment]
I will have a look this evening.
Or in the meantime @gizmocuz can revert my change of commit https://github.com/domoticz/domoticz/commit/09155ed07c3420e8551361f0231c24377eca11fa#diff-d2d64d905fb932ea47ea98f5d457cc4f ?
(Just only the NotificationGCM.cpp change I dit there).
I will rewrite that piece of code to use extradata midx_ instead. That what you started :)

**Comment by gizmocuz** [comment]
@Olifant1990 , no idea how to revert a single commit, but feel free to make a PR

**Comment by Olifant1990** [comment]
#2509 will solve this problem for as far as I can test.

**Comment by bostjane** [comment]
I did few more tests and looks like GCM itself is working afterall. Tested in Setup->Settings->Notifications and also in  Setup->More options->Mobile Devices,  I can't really explain why sometimes takes even 10 minutes or more for notification to arrive while it always did instantly in stable version. If it would be solely  Google/Android power saving "feature" than it wouldn't matter from where the request initiated.

Original issue still exists and seems to be more dzVents related as:

domoticz.notify('BostjanTest#message') doesn't work and produces Error: SQL Query("SELECT SenderID, DeviceType FROM MobileDevices WHERE (ID IN (pushover))") : no such column: pushover

while

domoticz.notify('BostjanTest') works just fine.

Further if I try LUA with domoticz.notify('BostjanTest#message') it also works...

**Comment by Olifant1990** [comment]
Maybe you got also an Android version update? I only know the powersaving features on Android are getting more aggressive.

The fix I wrote, isn't rolled out to the beta on the website. @gizmocuz accepted my code change just an hour ago and I don't know when a new beta is build.
Only if you run your code via Visual Studio/github, you should have your problem solved.
I am pretty sure the fix shouldn't give that SQL error anymore.

**Comment by bostjane** [comment]
Just tested latest beta v3.9673 on Windows and can confirm that also SQL error has been solved and notifications arrive as expected.
Thanks to all.

**Comment by brjhaverkamp** [comment]
Sorry to leave a comment here on a closed issue, but I can not find any documentation on how to use the gcm subsystem with SendNotification. And I found no other way to contact @bostjane bostjane. Can you or anyone else share a working example?
