### ISSUE TITLE
Compiling fresh git clone V3.9657 on PI-3 (Debian stretch) gives error in PhilipsHue.cpp

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#2505]
Error during compiling. To make sure nothing local I remove source directory and took a fresh git clone. Same error:

/usr/local/src/domoticz/hardware/PhilipsHue/PhilipsHue.cpp:346:34: error: invalid initialization of non-const reference
 of type ‘std::_Rb_tree_iterator<std::pair<const int, CPhilipsHue::_tHueGroup> >&’ from an rvalue of type ‘std::map<int
, CPhilipsHue::_tHueGroup>::iterator {aka std::_Rb_tree_iterator<std::pair<const int, CPhilipsHue::_tHueGroup> >}’
   auto & ittGroup = m_groups.find(nodeID - 1000);
                     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/domoticz.dir/hardware/PhilipsHue/PhilipsHue.cpp.o] Error 1
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
make: *** [all] Error 2

**Comment by gizmocuz** [comment]
@rwaaren , please wait a day next time before reporting. Building on different architectures will sometimes reveal compile errors that are not available in the other.
Also building takes a long time... sure we will notice this as we check the build systems
