### ISSUE TITLE
[RTL433] AlectoV1 Wind Sensor: Unhandled sensor reading

### ISSUE THREAD

**Issue by HansVanEijsden** [domoticz/domoticz#2506]
Hi all,

`rtl_433 -G` finds this (currently there's no wind though):

```
trying device  0:  Realtek, RTL2838UHIDIR, SN: 00000001
Found Rafael Micro R820T tuner
Using device 0: Generic RTL2832U OEM
Exact sample rate is: 250000.000414 Hz
[R82XX] PLL not locked!
Sample rate set to 250000.
Bit detection level set to 0 (Auto).
Tuner gain set to Auto.
Reading samples in async mode...
Tuned to 433920000 Hz.
2018-06-20 23:35:09 :	AlectoV1 Wind Sensor
	House Code:	 44
	Channel:	 1
	Battery:	 OK
	Wind speed:	 0.00 m/s
	Wind gust:	 0.00 m/s
	Direction:	 180
	Integrity:	 CHECKSUM
```

But Domoticz 3.9656 shows this:

> 2018-06-20 23:38:46.246 Status: Rtl433: Unhandled sensor reading, please report: (2018-06-20 23:38:46,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,0.000,0.000,180,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 2018-06-20 23:38:46.246 )

All my other RF-sensors are detected by rtl_433 and parsed by Domoticz, but this wind sensor is unknown to Domoticz.
I hope you can add the sensor, with the above information. Thanks!

**Comment by HansVanEijsden** [comment]
Some more readings, so you can see the values:

> 2018-06-21 02:03:58.460 Status: Rtl433: Unhandled sensor reading, please report: (2018-06-21 02:03:58,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,1.200,1.600,180,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-06-21 02:03:58.460 )
2018-06-21 02:04:29.388 Status: Rtl433: Unhandled sensor reading, please report: (2018-06-21 02:04:29,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,1.200,1.400,180,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-06-21 02:04:29.388 )
2018-06-21 02:05:00.316 Status: Rtl433: Unhandled sensor reading, please report: (2018-06-21 02:05:00,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,1.200,1.600,180,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-06-21 02:05:00.316 )
2018-06-21 02:06:02.174 Status: Rtl433: Unhandled sensor reading, please report: (2018-06-21 02:06:02,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,1.200,2.200,180,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-06-21 02:06:02.174 )
2018-06-21 02:06:33.101 Status: Rtl433: Unhandled sensor reading, please report: (2018-06-21 02:06:33,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,1.200,1.400,270,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-06-21 02:06:33.101 )
2018-06-21 02:07:04.030 Status: Rtl433: Unhandled sensor reading, please report: (2018-06-21 02:07:04,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,1.200,1.800,225,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-06-21 02:07:04.030 )
2018-06-21 02:07:35.558 Status: Rtl433: Unhandled sensor reading, please report: (2018-06-21 02:07:35,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,1.200,1.000,225,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-06-21 02:07:35.558 )
2018-06-21 02:08:06.486 Status: Rtl433: Unhandled sensor reading, please report: (2018-06-21 02:08:06,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,1.200,2.000,270,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-06-21 02:08:06.486 )
2018-06-21 02:09:08.342 Status: Rtl433: Unhandled sensor reading, please report: (2018-06-21 02:09:08,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,1.000,1.000,225,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-06-21 02:09:08.342 )

**Comment by gizmocuz** [comment]
Maybe @TimelessNL could have a look at adding support for this. It seems internally in the code i see code for a wind sensor

**Comment by TimelessNL** [comment]
I'll try to find some time for this somewhere next week. I did add my wind sensor, but there are 3 or more wind variables in RTL_433. It seems that this sensor uses one of the other variables.

@HansVanEijsden can you verify that this wind sensor does not have a temperature sensor?

**Comment by HansVanEijsden** [comment]
That would be great @TimelessNL, thanks in advance.

The Alecto device has a modular setup. This particular device has a wind sensor and a temperature/humidity sensor. The wind sensor transmits every 30 seconds and the temperature/humidity sensor transmits every 3 minutes.

Domoticz decodes the temperature/humidity sensor without problems, see the red arrow:
![schermafbeelding 2018-06-21 om 13 49 10](https://user-images.githubusercontent.com/11890145/41717431-0b408ee4-755a-11e8-890e-3f417540e477.png)

And this is what `rtl_433 -G` shows about both sensors:

> 2018-06-21 13:36:49 :	AlectoV1 Temperature Sensor
	House Code:	 44
	Channel:	 1
	Battery:	 OK
	Temperature:	 16.50 C
	Humidity:	 50 %
	:	CHECKSUM

> 2018-06-21 13:37:20 :	AlectoV1 Wind Sensor
	House Code:	 44
	Channel:	 1
	Battery:	 OK
	Wind speed:	 2.60 m/s
  Wind gust:	 5.00 m/s
  Direction:	 225
  Integrity:	 CHECKSUM

> 2018-06-21 13:39:25 :	AlectoV1 Wind Sensor
  House Code:	 44
  Channel:	 1
  Battery:	 OK
  Wind speed:	 3.60 m/s
  Wind gust:	 5.00 m/s
  Direction:	 270
  Integrity:	 CHECKSUM

> 2018-06-21 13:39:55 :	AlectoV1 Temperature Sensor
  House Code:	 44
  Channel:	 1
  Battery:	 OK
  Temperature:	 15.50 C
  Humidity:	 50 %
  : CHECKSUM

Let me know if you need more information, I'm glad to help. Thanks!

**Comment by HansVanEijsden** [comment]
@TimelessNL I've recorded the AlectoV1 Wind Sensor with `rtl_433 -a -t`, maybe it helps. You can play it back (after unzipping) with `rtl_433 -r`.
The file: [g003_433.92M_250k.cu8.zip](https://github.com/domoticz/domoticz/files/2217111/g003_433.92M_250k.cu8.zip)

**Comment by TimelessNL** [comment]
Sorry,  seems I've missed the notification of your first message. I will try to support this within a couple of days.

**Comment by TimelessNL** [comment]
@HansVanEijsden
Can you build my domoticz/development fork with commit: https://github.com/TimelessNL/domoticz/commit/442fa56ae50684fc183c12f4a03b2f6411f886cd

See if that add's support for your windsensor.

**Comment by HansVanEijsden** [comment]
Hi @TimelessNL, what a surprise, you made my day. Thanks for taking the time, especially during these really hot Dutch days. I've built your fork, great.

It works! Well, kind of. Wind is showing up beautifully, I love it:
![wind](https://user-images.githubusercontent.com/11890145/43647284-7a6ddac0-9737-11e8-9e52-64d3f52bef02.png)
But there's something strange (to me) happening: now there's also an "ice cube" with permanently 0 ºC in it (see the upper red arrow).
And as you can see, no wind gusts are recorded (although they are there, according to `rtl_433` output).

Also in "devices" there aren't any wind gusts visible (the upper red arrow. The lower red arrow is the temperature reading of the device, same ID):
![apparaten](https://user-images.githubusercontent.com/11890145/43647379-c8e8dc54-9737-11e8-8947-a12a44949b2c.png)

I don't know if it's user error, but let me know if you need new recordings. Thanks!

**Comment by HansVanEijsden** [comment]
Update: Eve (via HomeKit: Domoticz -> eDomoticz -> HomeBridge -> Eve) displays it too, thanks to your work. 👍🏻 
![eve](https://user-images.githubusercontent.com/11890145/43648821-c3b57158-973b-11e8-87f5-d0dfcae1bee1.png)

**Comment by TimelessNL** [comment]
Haha indeed. That's why it took me so long to start implementing this. I'm more a winter person :).

Currently this 0°c is by design. As far as I know domoticz does not support a wind sensor without temperature. Thats why I asked if your sensor had one. Normally a wind sensor will also calculate the "chill temperature" based on the wind speed, so we know how the actual temperature should "feel" like.

For some reason your sensor does not provide this info so I hardcoded it to be 0°c. Which is in my opinion the most sensible value.

I noticed that you've set the speed unit in "bf", currently there isn't that much wind in my area (also live in the netherlands) maybe thats why the gust value is 0bf? rtl_433 uses m/s. So maybe thats the issue?

**Comment by TimelessNL** [comment]
@HansVanEijsden
Recent days have been proven more windy, any change regarding your windmeter?

**Comment by HansVanEijsden** [comment]
Hi there, @TimelessNL, thanks for the reminder. And yes, I switched it immediately to m/s to have a more precise readout.

There's no change regarding the wind meter, still no wind gusts, only wind speed:
![schermafbeelding 2018-08-08 om 19 31 40](https://user-images.githubusercontent.com/11890145/43854144-5072485a-9b42-11e8-92cb-d8058fb69a2f.png)

The wind meter transmits gusts though, here some `rtl_433 -G` output:
```
2018-08-08 19:34:21 :	AlectoV1 Wind Sensor
	House Code:	 44
	Channel:	 1
	Battery:	 OK
	Wind speed:	 2.20 m/s
	Wind gust:	 2.20 m/s
	Direction:	 270
	Integrity:	 CHECKSUM
2018-08-08 19:34:52 :	AlectoV1 Wind Sensor
	House Code:	 44
	Channel:	 1
	Battery:	 OK
	Wind speed:	 2.40 m/s
	Wind gust:	 3.60 m/s
	Direction:	 180
	Integrity:	 CHECKSUM
```

Do you have any ideas?

**Comment by TimelessNL** [comment]
@HansVanEijsden
Mmh indeed. You should have received some gust readings by now.

Can you do 2 things for me:

1. Create a new dump with atleast 2 or more readings.

2. Post the entire output of "rtl_433 -F csv -q -I 2" including 1 reading and csv legend. I'm curious if something has changed in the CSV output.

I'm still clueless why it does update the sensor though, since it only processes the data if all the CSV parameters are present...

**Comment by HansVanEijsden** [comment]
Here's the output of `rtl_433 -F csv -q -I 2`:

```
time,model,id,channel,battery,temperature_C,mic,rid,button,humidity,state,brand,rain_rate,rain_total,gust,average,direction,pressure_hPa,uv,power_W,energy_kWh,unit,group_call,command,dim,dim_value,wind_speed,wind_gust,wind_direction,dipswitch,rbutton,device,temperature_F,status,rc,brandmodelidtemperature_C,setpoint_C,switch,direction_str,direction_deg,speed,rain,msg_type,signal,hours,minutes,seconds,year,month,day,sensor_code,uv_status,uv_index,lux,wm,fc,ws_id,rainfall_mm,wind_speed_ms,gust_speed_ms,current,interval,learn,windstrength,winddirection,flags,maybetemp,binding_countdown,depth,power0,power1,power2,node,ct1,ct2,ct3,ct4,Vrms/batt,temp1_C,temp2_C,temp3_C,temp4_C,temp5_C,temp6_C,pulse,sid,transmit,moisture,type,pressure_PSI,battery_mV,pressure_bar,code,pulses,energy,device id,len,to,from,payload,event,heartbeat,brandmodelidstatus,temperature_C1,temperature_C2,test,newbattery,heating,heating_temp,water,counter,alarm,depth_cm,repeat,temperature_1_C,temperature_2_C,device_type,raw_message,switch1,switch2,switch3,switch4,switch5
Found Rafael Micro R820T tuner
Exact sample rate is: 250000.000414 Hz
[R82XX] PLL not locked!
Sample rate set to 250000.
Bit detection level set to 0 (Auto).
Tuner gain set to Auto.
Tuned to 433920000 Hz.

2018-08-08 20:53:24,AlectoV1 Temperature Sensor,44,1,OK,20.600,CHECKSUM,,,67,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-08-08 20:53:55,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,2.400,3.400,225,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-08-08 20:54:26,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,2.600,3.800,270,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-08-08 20:54:57,AlectoV1 Wind Sensor,44,1,OK,,CHECKSUM,,,,,,,,,,,,,,,,,,,,2.600,2.400,225,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
```

I'm trying to make a new dump but it doesn't record all the sensors, I don't know why but I keep trying. 😉

**Comment by TimelessNL** [comment]
I don't need all your sensors. Just the wind sensor is enough ;)

**Comment by HansVanEijsden** [comment]
Edited. 😉

**Comment by TimelessNL** [comment]
I think I've found the issue. It's simply hitting the wrong if :/

Kuch... stupid me :P

**Comment by TimelessNL** [comment]
@HansVanEijsden

I've updated my branch, could you do another test?

**Comment by HansVanEijsden** [comment]
Great, thanks! I'll start building now, it takes a little more than 1 hour here. I'll let you know here!

**Comment by TimelessNL** [comment]
You don't have to do a complete rebuild. The buildprocess is smart enough to only rebuld rtl_433.

**Comment by HansVanEijsden** [comment]
I just discovered that, yes.. cmake is smarter than I thought. Great!
Here are the gusts!
![chart](https://user-images.githubusercontent.com/11890145/43860118-01ec79b0-9b53-11e8-881f-55fcd78b2878.png)
![schermafbeelding 2018-08-08 om 21 34 42](https://user-images.githubusercontent.com/11890145/43860126-0696e478-9b53-11e8-971e-88515c0ce91a.png)
Thank you so much. I'm happy! 😃 😃

**Comment by TimelessNL** [comment]
@gizmocuz I've created the pull request. 

@HansVanEijsden If that's handled you should be able to use the official domoticz again :)

**Comment by gizmocuz** [comment]
@TimelessNL , merged

**Comment by TimelessNL** [comment]
Thanks!

@HansVanEijsden If you verify that the development domoticz branch works for you, you may close this issue.

**Comment by HansVanEijsden** [comment]
The development domoticz branch works for me, thanks again for all.

**Comment by TimelessNL** [comment]
No problem, happy to help ;)
