### ISSUE TITLE
Switch subtype door contact no longer setable/clickable

### ISSUE THREAD

**Issue by bostjane** [domoticz/domoticz#2511]
I use garage door controller whose subtype I set to "door contact" (nice icon and open/close states). In stable release I could click on device+s widget to send on/off command to it to open/close garage door. In beta v3.9673 this device is no longer clickable, i.e. user is not allowed to switch state.
In theory I could use "door lock inverted" but states locked/unlocked are not as good as open/close for garage door and also Domoticz client for Android doesn't even show devices of that type.

Is this a bug or intentional change? If intentional, could it be to revert it back or even make an option in widget's settings if device is clickable or not.

**Comment by sweetpants** [comment]
This is Works As Designed. The previous way was wrong. A 'Door Contact ' should never be 'clickable'. You could use SwitchType On/Off and choose a different Icon, but then it says On/Off instead of Open/Closed

**Comment by bostjane** [comment]
I only partially agree with you - it depends on very specific usage. If "door contact" (DC) is a sensor reporting if window or door is closed or open, then yes, it shouldn't be clickable. But in case DC is actually a garage door controller, then you need it to be clickable as controller has two functions - it reports current state in case garage door is operated manually or it can close contacts and close/open door via ZWave - in this case it needs to be clickable.
Well yes, I may set it as switch, but similar goes for users of "read only" DC's :) They may also choose some sort of read-only sensor and choose the right icon :)

My vote is to make it clickable again....

**Comment by gizmocuz** [comment]
@bostjane , so it is not a contact, it is a garage door opener, a on/off switch
You should use the door-lock type. If you do not like the icons (it is just an icon!?) then use it as a normal on/off with a custom icon
The contact will not be clickable again as you can not operate a 'contact'

**Comment by bostjane** [comment]
@gizmocuz, I see and I understand. The thing is that change broke ideal solution for garage door controllers. It's the icon and the status which was Open/Close instead of On/Off. It's "only" that. But the icon and label are two big reasons to have switch subtypes at the first place, right?
What would mean to make new subtype Garage door which would be a copy of door contact from stable release where door contact was still clickable? Quite complicated and not really worth it at the moment or quick and trivial and doable?

**Comment by gizmocuz** [comment]
@bostjane, it was wrong in the previous stable and has been corrected
You can edit the switch and set this to a door type
