### ISSUE TITLE
dzVents directory changed

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#2513]
i Have a synology 718+ running DSM6.2
i upgraded from V3.8720 to V4.9700
Domoticz seems to run alright but is having problems locating the dzVents.lua file

it is looking at 
/usr/local/domoticz/dzVents/runtime/dzVents.lua
however when i check the new install has put it at /usr/local/domoticz/var/dzVents/runtime/dzVents.lua

is this normal?
how can i correct this?

stopping and starting dzvents did not help

when i copy the directories to the old location it finds the dzVents.lua file but get an error on line 33

2018-06-24 13:57:51.196 Error: EventSystem: in /usr/local/domoticz/dzVents/runtime/dzVents.lua: /usr/local/domoticz/dzVents/runtime/dzVents.lua:33: attempt to concatenate local 'triggerReason' (a nil value)

**Comment by gizmocuz** [comment]
Please ask this question here:
https://www.domoticz.com/forum/viewtopic.php?f=56&t=2620

feel free to re-open this issue if it is not a synology package issue
