### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by Olifant1990** [domoticz/domoticz#2514]
Don't know if this belongs here as a code issue, but take a look at the version numbers:

I read that the current stable number is now version 4.9700

But, the website still displays version 3.9700. And if I download the Windows zip file, it is still 2_9700
Same for the beta. website shows 3.9711 (must be 4.9711) and the download for Windows says 2_911.exe

I didn't look for the other OS files, but maybe it is a problem here too?

**Comment by gizmocuz** [comment]
Thanks for spotting, it was the website script, and i also found a cmake package version number that needed to increase. But when you launch the application, and look the history, both are correct

**Comment by Olifant1990** [comment]
I see the version number on site has been updated indeed.
But, the version in the windows zip-file is still 2.xxxx.
See image:

![content domoticz_windows_x86 zip file](https://user-images.githubusercontent.com/25199588/42082060-4cf47412-7b87-11e8-9bc1-bbf22cb6c8e6.JPG)

**Comment by gizmocuz** [comment]
Thanks for reporting, also fixed in next commit/beta/stable

**Comment by Olifant1990** [comment]
Next problem with numbers:
Last week I downloaded the windows beta zip.
Inside was a file named DomoticzSetup_4_9722.exe
But after installing it, It is clear it should be 4_9732 (as Domoticz says itself.

Just a few minutes I downloaded the newest beta (9753) and the filename is still DomoticzSetup_4_9722.exe

**Comment by Olifant1990** [comment]
@gizmocuz 
Something to do with the static number on line 72 and 78 of domoticz.rc? (VALUE "FileVersion", "4.0.0.9722").
And somewhere else where the filename is created?

**Comment by gizmocuz** [comment]
Yes, i think that is the problem. I will make a patch for the innosetup, we just remove the version in the filename...
