### ISSUE TITLE
Request: remote control, own scripts

### ISSUE THREAD

**Issue by mDieli** [domoticz/domoticz#2515]
A dedicated device for every TV/setop box/DVD player/receiver etc is not a thing that is doable.
However, for a lot of TV's etc are scripts available that makes sending commands to that device possible.
At this moment, we create for example a dummy switch for every command (1 switch for play, one for pause, etc) or we can use a selector switch to combine a few of these commands.

Wouldn't it be great if we can have the "remote" design from Kodi as a switch that we can adjust like the selector switch and add our own commands?

**Comment by gizmocuz** [comment]
I would suggest to get yourself a Logitech harmony hub (or similar hardware)
This is outside the scope of this project

**Comment by mDieli** [comment]
Hi Gizmocuz,

I'm afraid you are missing my point here.
What I meant, is a (dummy) selector switch with the *design* of the "(kodi)
remote" that allready is in Domoticz.(or something likewise)
This is purely a software thing so there is no need for any Logitech
Harmony hub. Al the dummy selector switch (with remote design) needs to do,
is launching commands/scripts by the push of the corresponding button.

Best regards and keep up the good work!

**Comment by gizmocuz** [comment]
No i did not miss your point....
First, this should be discussed in the Forum... but, domoticz is a home automation tool, not a remote control for your television. Sure we can turn on the television and lights... but just use your normal control to change channels.
And have a look at the harmony hub, it's a software 'thing' as well, has an phone application too.
Can control lots and lots of hardware
