### ISSUE TITLE
Shared Devices Switches unconfigured on master

### ISSUE THREAD

**Issue by Lyr3x** [domoticz/domoticz#2516]
Domoticz Version on Master and Slave: 4.9711
Platform Master: Debian Strech (x64)
Platform Slave: Debian Strecht (ARMv7) (Pi2)

Problem:
I configured two switches on my slave Pi a normal On/Off switch which triggers a bash script and a selector switch with 4 Levels which also triggers bash scripts. 

They appear as Unkown / Unkown - Switch and Unkown /Unknown - Selector Switch. 

When adding the switches from the Device tab both are set up as normal On / Off switches and the normal switch is working fine. 

But the selector switch does not have any of the defined levels and dont work without adding the script path manually

I read about the architecture problem, but both platforms are little endian

**Comment by Tixav** [comment]
+1
see [http://www.domoticz.com/forum/viewtopic.php?f=6&t=20240&p=156415#p156415]

**Comment by gizmocuz** [comment]
That is correct and true. This as the minimum values are transmitted (nValue/sValue) not the option values
It will be a lot of overhead to transmit this all the time (currently working on a better transfer solution, but thats besides this topic), so for selector switches (and also utility types), it is a once time fix/setting you have to manually do.
Should not be to hard/complicated, specially when you have both browsers side-by-side and can do a copy/paste

**Comment by Lyr3x** [comment]
You are right that it is not that complicated to set-up, but it is an issue right? Are there specific ideas for an better more reliable system? Would be glad to support.

**Comment by waltervl** [comment]
Closing this old issue.
