### ISSUE TITLE
Domoticz site down?

### ISSUE THREAD

**Issue by sweetpants** [domoticz/domoticz#2518]
It seems the domoticz site https://www.domoticz.com/ is down? 

Forbidden
You don't have permission to access / on this server.
Server unable to read htaccess file, denying access to be safe

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by DewGew** [comment]
Me too from sweden...

**Comment by sweetpants** [comment]
Seems up again, but performance is very poor. This has been for several days already

**Comment by gizmocuz** [comment]
True, i will move everything to a VPS soon, but might take some weeks

**Comment by sweetpants** [comment]
Thanks, can there also be done something about this cookie thing? A lot of users are complaining and yes sometimes it's annoying if you remove cookies after closing browser and you enter the forum via a link.

**Comment by gizmocuz** [comment]
Yes, stupid European rules... remove cookies after browsing ? who will do so ?
You have to accept the rules... i know it is irritating, but this implementation is using cookies to store the info, a lot of sites do
If you know a better phpBB extension that will store this in the user table ?
But then again, a user does not have to login, and still has to accept it
I think this is more a phpBB issue, or an issue of the extension, maybe you could ask around ?
I can remove it, but i am technically not allowed to do so by the new law

**Comment by sweetpants** [comment]
Ok, clear, I will have a look when back from hollidays, case closed
