### ISSUE TITLE
hue lights status does not update/reflect real status

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#2519]
Upgraded to V4.9700(did a clean install)
everything seems to work(all lights/temp readings react) except the hue lights.
when hue lights are switched on by either a script or a scene the lights turn on but the status in domoticz stays off.

curl command to switch on scene(pointing to ip adress hue hub): lights turn on, domoticz status say they are off
hue scene from within domoticz: lights turn on, domoticz status say they are off

it seems that everything which is done by the hue hub does work but the status does not get reflected to domoticz user interface.

lights switched on from the domoticz interface do work, lights go on, switch reflects on status

so this seems to be a thing between hue hub and domoticz

**Comment by Lyr3x** [comment]
I realised the same thing yesterday. In one specific case: 
If i turn off the "All lights" switch the corresponding lights like "bed lamp" are switching "off" but the domoticz switches staying "on"

**Comment by rwaaren** [comment]
Checked with a couple of earlier domoticz versions.

Versions including and before V3.9657 create Hue devices when Hue hardware is added
Versions after and including V3.9659 do not create Hue devices when Hue hardware is added

**Comment by GravityRZ** [comment]
yes and it creates a ton of scenes(the same ones) you do not have in the hub
it mentions huelabs so that is not what you want either

**Comment by gizmocuz** [comment]
This might have been caused by a recent code cleanup.
I reverted this partly, could you have a look at beta 9722+
If it's not working, then we have to look at the recent changes in the code to see what changed

**Comment by Lyr3x** [comment]
Tested 9722 and for me its the same behavior as before.

**Comment by GravityRZ** [comment]
do you mean hue still not updating in 9722

**Comment by Lyr3x** [comment]
Yes. Sorry that was unclear 👎 

>yes and it creates a ton of scenes(the same ones) you do not have in the hub
it mentions huelabs so that is not what you want either

I need to say that i cant see this in my devices list. I just got the standard Hue bridge Scenses and switches, and there is no additional scene added since i upgraded to 4.x. So maybe this is "only" an initial setup problem.

**Comment by rwaaren** [comment]
with 9722:
Adding new Hue hardware creates all Hue scenes as devices and these are working when activated on the setup -> devices tab. They do not show-up in the switches-tab or anywhere else.
Hue devices are not created.

**Comment by GravityRZ** [comment]
i know that but normally you only get the scenes which are defined in the hue app. with 9700 you also get a lot of extra scenes(which show up as switches when you set them to used, green arrow)) the current scenes however were not recreated and kept the same device id

the old devices still work so this is not a matter of recreating the devices to solve the problem.

i think somebody deleted to much "usefull" code
> with 9722:
Adding new Hue hardware creates all Hue scenes as devices and these are working when activated on the setup -> devices tab. They do not show-up in the switches-tab or anywhere else.
Hue devices are not created.

**Comment by gordonb3** [comment]
hmmm???

```
@@ -334,7 +334,7 @@ bool CPhilipsHue::SwitchLight(const int nodeID, const string &LCmd, const int sv
        if (nodeID < 1000)
        {
                //Light
-               auto & ittLight = m_lights.find(nodeID);
+               auto && ittLight = m_lights.find(nodeID);
                if (ittLight != m_lights.end())
                {
                        pState = &ittLight->second;
@@ -343,7 +343,7 @@ bool CPhilipsHue::SwitchLight(const int nodeID, const string &LCmd, const int sv
        else if (nodeID < 2000)
        {
                //Group
-               auto & ittGroup = m_groups.find(nodeID - 1000);
+               auto && ittGroup = m_groups.find(nodeID - 1000);
                if (ittGroup != m_groups.end())
                {
                        pState = &ittGroup->second.gstate;
```
The original single `&` in there is not a bitwise AND but an address-of operator. By doubling it the value of `ittGroup` is now also treated as an address-of operator. Probably the only reason that it still compiles is because of the auto specifier.

**Comment by gizmocuz** [comment]
@gordonb3 , no, this had to be done to make the iterator writable (it's a pointer that way)
But even so, i reverted that change here , thats why i asked to test 9722

**Comment by gordonb3** [comment]
Okay. If you're sure. I simply get itchy when I see ** and && variables and it doesn't seem right that you change the definition on the variable and then continue to use it like nothing was changed.

Or does this update not function without 114a968e?

**Comment by GravityRZ** [comment]
is it not a good idea to revert everything completely?
breaking things and then trying to solve those breaks is as lot more work then avoiding breaking it in the first place.
is this not the whole idea of github: push a new version, if problems revert and go back to the drawing board. creating bugs and then solving them(and creating others) in a new release is doing it the Apple way

**Comment by MoiLeviathan** [comment]
Hello, i have a little (big) problem.
When i open my color light with domoticz, i can't close this light with domoticz. Where is the problém ?
Sorry i'm french.

**Comment by icemanxbe** [comment]
Removed and readded my hue bridge. Only thing i get are scenes. No groups or lights show up. Latest beta.

**Comment by gizmocuz** [comment]
@GravityRZ , there is not much more to revert in this class ? I am not reverting changes by the latest authors, only my recent changes

Edit:
It is also good to know 'where' the problem occurred. So now we know, and the other changes can stay in.
Yes the idea is that it gets checked, if it is not working, it gets fixed and checked again

**Comment by gizmocuz** [comment]
@emontnemery, is it possible you can have a peek or explain ? You did a lot of hard work on this class...

**Comment by gizmocuz** [comment]
@icemanxbe, did you enable 'accept new hardware' under settings ?

**Comment by gizmocuz** [comment]
Also make sure in the hardware setup of the Hue, that you checked 'Add Groups/Scenes' if needed

**Comment by gordonb3** [comment]
@gizmocuz
According to @rwaaren some comments back it started failing on two distinct commits, the first of which I quoted above and the second I named the commit number. It seems to me that if you revert those two commits it should start working again.

So that would be the code where `auto` has the single ampersand. Never used `auto`, but from what I understand reading into it using a single ampersand returns a reference and using the double ampersand gives direct access which sounds something like a hard link?

**Comment by gizmocuz** [comment]
Confirmed, no lights are added
Found the issue... moment

**Comment by gizmocuz** [comment]
solved in beta 9727

**Comment by icemanxbe** [comment]
Works like a charm again. Thanks for the quick fix!

**Comment by gizmocuz** [comment]
Thanks for the feedback, sorry for the troubles. Was this OK in the stable ? Else we need to release a new stable soon

**Comment by icemanxbe** [comment]
That I don't know. 
I use the beta release mainly for everything.
My theme for some reason doesn't like the stable release.

**Comment by rwaaren** [comment]
@gizmocuz, sorry but no. It was not OK in the stable.

**Comment by Lyr3x** [comment]
In 9278 the state is also changing again 👍

**Comment by dgilbert2** [comment]
All working on my system with 4.9728 beta, thank you, Looking forward to the stable version update for my main system.

The only minor observations I have seen is that when all lights in a group/room are switched on, the domoticz Group device shows "Set Color" rather than "On".

Also the Group showing the status of the ALL Hue lights in the house is not updated when every light is switched on.

Excellent work though, thank you :-)

**Comment by HansieNL** [comment]
I can confirm too. Running Stable 4.9700. Light states are indeed not updated if switched outside of Domoticz.

**Comment by GravityRZ** [comment]
ok so where does this leave us, will 9728 be the new stable
we can update to 9728 beta but a stable which is not stable is not logical

i also noticed that updating to 9700 resets the kWh meters. totals stay the same but readout is set to zero.

**Comment by GravityRZ** [comment]
tested 9827 and can confirm hue lights are updated again(but the status takes approx 5 seconds to update which is slower then before)
also lots of hue devices are generated. not the scenes you want but a lot of  rubbish
devices from id 260 al up to 357 are generated
![huescenes](https://user-images.githubusercontent.com/16853535/42055368-38cc7a86-7b17-11e8-9700-5d0755429a5b.jpg)

**Comment by Lyr3x** [comment]
i cant confirm the creation of those devices. There are no changes in my device list. But i can confirm that it takes 5-10 seconds to change the state.

**Comment by GravityRZ** [comment]
somehow the accept new hardware was toggled to on. normally this does not create extra devices unles you disable/enable the hub. al i do is install, restore database and then they show up.

**Comment by icemanxbe** [comment]
I do not have the 5 second delay.
On the dashboard pages.. Yes.
But my events/scripts trigger within 1 second when I turn my Hue lights on or off via the switch on the wall.
The dashboard just updates the state more slowly. I'm guessing that's a refreshing issue?

For me everything is perfectly fixed.

**Comment by GravityRZ** [comment]
yes i mean the dashboard pages. lights  switch on/off instantly. not a dealbraker but the update seems a bit slower thats all

**Comment by GravityRZ** [comment]
will close this. hue problem fixed
