### ISSUE TITLE
Evohome Status: Warning: Notification NOT handled

### ISSUE THREAD

**Issue by onsmam** [domoticz/domoticz#2525]
i have evohome witch updates via a script. when a thermostat gets updated i get the following message:

2018-06-28 18:26:03.992 Status: Warning: Notification NOT handled (Hardware: 22 - Thermostat, ID: 93049, Unit: 4, Type: 46 - Heating, SubType: 0 - Zone), **please report on GitHub!**

so i reported the warning.

is there a way to silence this message? in the other issues it looks like a wrong json update?

the update my script does is:

/json.htm?type=command&param=udevice&idx=$idx&nvalue=0&svalue=$temp;$setpoint;$mode

**Comment by gizmocuz** [comment]
Please use the forum!
What version are you using ? Did you try the latest beta ?

**Comment by onsmam** [comment]
the warning says: "please report on github..." so i did...

latest beta installed....

**Comment by onsmam** [comment]
new beta is indeed working! thanx.. had searched for days, didnt found anything... after your post saw the update in de notificationhelper

**Comment by gizmocuz** [comment]
Right, so the issue that was closed underneath yours here was this:

https://github.com/domoticz/domoticz/issues/2520

Try to search also here on github

Great it is solved now!

**Comment by onsmam** [comment]
My appologies.. will search github.. thanx for the great program!
