### ISSUE TITLE
New memory leak

### ISSUE THREAD

**Issue by heggink** [domoticz/domoticz#2528]
Ever since one of the latest betas, memory is leaking again.
Anyone else seeing this? Over 3 days, process memory increased from 12 to 33%...

**Comment by heggink** [comment]
On 4.9712 btw

**Comment by gizmocuz** [comment]
Weird as there have been no memory changes, did you look at the code history/changes ?
Is it the domoticz process or the system memory that increases ?

**Comment by heggink** [comment]
Domoticz process... In NYC At the moment so no time to check out changes.

**Comment by heggink** [comment]
It's a pretty significant leak: restarted before I went to bed and now (12hrs later) it took an additional 10%. That's like 20% a day.

**Comment by gizmocuz** [comment]
Weird... if you got time, could you try disabling the event system and see how that goes, or maybe it is related to one of your enabled hardwares ?

**Comment by freemann** [comment]
here also memory increasing;
![screenshot - 02_07_2018 18_42_46](https://user-images.githubusercontent.com/601053/42176009-cf33e88e-7e27-11e8-8a73-0bc6e239b4f8.png)
CPU is pretty stable;
![screenshot - 02_07_2018 18_51_30](https://user-images.githubusercontent.com/601053/42176368-fec55f64-7e28-11e8-842c-176809b8f80e.png)

I'm pretty sure that's it going on since I upgrade to the last stable. The month memory graph is clearly showing an memory raise since 24-06-2018, the day the new stable was release and I updated it.
Since then I also updated raspbian to Stretch. Maybe some new lib which is causing some troubles?!

currently running the following hardware:
![screenshot - 02_07_2018 18_46_29](https://user-images.githubusercontent.com/601053/42176180-5b04592a-7e28-11e8-9f22-d2cd12c059f4.png)

After a few days running Domoticz is getting a bit slow/less responsive.

**Comment by gizmocuz** [comment]
Stretch is not new
As asked.. try disabling the event system and all you hardware
Then enable them one by one to debug the issue please

**Comment by freemann** [comment]
ok... so no memory changes and Stretch is not new.

Will see what I can do with this great weather, soccer on tv, etc.

**Comment by heggink** [comment]
Because of the lack of #me2's on the forum, I decided to upgrade to the latest beta first and it may well be that this has resolved the issue. So something may have been fixed after 4.9712. Let's see!

**Comment by heggink** [comment]
![image](https://user-images.githubusercontent.com/3987735/42188645-26df1964-7e55-11e8-818b-3efb9e7de329.png)
Latest beta fixes the issue. No idea what happened but closing.

**Comment by gizmocuz** [comment]
Don't think so ;) but great it is solved

**Comment by heggink** [comment]
Bad news: domoticz ran fine for a bunch of weeks and, all of a sudden, Sunday evening started to gradually consume memory again. Reboot gives it but something triggers to start memory consumption to go up big time. 
Currently in Lee Vegas buy will investigate as soon as I get back.

**Comment by freemann** [comment]
I saw "the same" behavior while you opened this issue.
Now I'm not seeing any issues and memory is running great.
![screenshot_20180717-212807](https://user-images.githubusercontent.com/601053/42840970-d18ea546-8a08-11e8-8c6e-c0cc8b72b3ff.jpg)
It's slightly higher with the upgraded raspbian version, but acceptable.

**Comment by heggink** [comment]
Well that's the thing: it runs just fine until, all of a sudden memory increases at a steep angle. It can run for weeks with no issues. I have no clue what's causing it but will do some digging.

**Comment by freemann** [comment]
Where my month graph drops around 11 July, I updated my Stretch to the latest Kernel version. Looks like after that it's fixed for me.
Currently I'm running:
```
Linux raspberrypi 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l
NU/Linux
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch
```

**Comment by heggink** [comment]
Found it. It's a misbehaving python plugin (life360) that generates errors but apparently losses memory doing so. Closing as no domoticz.

**Comment by dnpwwo** [comment]
@heggink ,

Can you point me to the plugin source and post the errors?  It is probably the Plugin Framework that is losing the memory so I'd like to take a look.

**Comment by heggink** [comment]
I took the life360 plugin and changed it to put the distance from home in a distance device so I can monitor how far away people are.
Doing 2 trips in the USA, it gave errors as soon as I landed (some index error).
Currently traveling but will send you stuff when I get back.

**Comment by heggink** [comment]
@dnpwwo just submitted a bug with the life360 plugin @febalci wrote. You can find it here: https://github.com/febalci/DomoticzLife360/issues/9

Let me know if that is enough for you. the googleapi call is clearly not what the plugin expects and it crashes onHeartbeat which causes it to leak memory like no tomorrow. Whether the last is a python issue or a framework issue I cannot tell as I don't really know python at all.
Thanks for any help you can provide.

H

**Comment by nekitoss** [comment]
@gizmocuz i have some memory leak. 
![memory_leak](https://user-images.githubusercontent.com/11498479/44437926-623b6480-a5c5-11e8-9d64-35e3ae1c8e09.jpg)
I have 3 test scripts (trying set text on dummy button) - i tried to disable them one-by-one for couple of hours each- no impact. The drop of memory usage is when i realized that usage is around 90% - i restarted system (via domoticz menu). 
![chart](https://user-images.githubusercontent.com/11498479/44438541-3ec5e900-a5c8-11e8-82d0-e1eb81db6cb5.jpeg)
The important note - if zoom in those "stairs" each one is at beginning of each hour (xx:00-xx:05) for example 18:00-18:05
![memory_leak2](https://user-images.githubusercontent.com/11498479/44438048-0ae9c400-a5c6-11e8-9f30-475caefb2e96.jpg)
if i remember correctly (just cleared my log in web interfce) - at that time backups are made, think that is related to them
You can see, that before update to 4.97 emory usage was stable.
```
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie
```
![memory_leak3](https://user-images.githubusercontent.com/11498479/44438619-a4b27080-a5c8-11e8-8641-0e427524627d.jpg)

**Comment by gizmocuz** [comment]
@nekitoss, what version of domoticz are you running ?
By default, domoticz does NOT make any database backups each hour.
If you enabled this option, disable it
Also disable ALL hardware and ALL scripts
Now check if everything is stable (should be), if not, some other application on your raspberry is causing this.
If it is stable. enable 1 hardware, monitor for a few hours, if that is stable, enable the others one by one and test.
Now you should be able to determine where the problem recides

**Comment by nekitoss** [comment]
@gizmocuz 
As you can see on screenshots in my previous comment - i use `v4.9700`.
Build hash is `a3a45906` Build date `2018-06-23 17:24:51`
on my Pi i'm running only Domoticz and MySensors Gateway (Lan)

Yesterday i guessed you will ask me that `=)`, so i disabled backups. And disabled last enabled script (it is DZventz, reacting on dummy switch, (trigger is device, not timer) but it didn't even existed when stairs already were on graph, so i'm shure problem is NOT related to this script).
After disabling backups i restarted system(right drop in memory usage).
![chart 1](https://user-images.githubusercontent.com/11498479/44460183-ce918480-a614-11e8-95ab-e83de6078398.jpeg)
Since restart there is no stairs. Of course, memory still slightly growing (it is ok i think, same growth as before update to 4.97)
![chart 2](https://user-images.githubusercontent.com/11498479/44460209-d94c1980-a614-11e8-8d99-bbd419c1116e.jpeg)
So i'm still shure that problem is related to backups.
The idea is that i've enabled backups since first day installed domoticz, and i noticed problem after update to last stable 4.97. 
But i have to admit that before last stable i've been using beta builds - don't remember if last beta version before i moved to 4.97 was lower or higher.... 
I moved to stable because each beta update was corrupting my powermeter data at the moment of update - i had spikes. But i couldn't  use previous stable because for domoticz raspberry info addon i needed higher version (some feature was there). But even on stable i had one dayly spike few days ago...  But this problem i should investigate and post somewhere esle(alredy deleted wrong data spike)...

**Comment by gizmocuz** [comment]
When you enable backups, and leave it running, does the system crash ? or will it kind of repair/flush the memory ?
Just trying to see if it is a caching issue.
Else the problem must be in 'CSQLHelper::BackupDatabase'
But looking at that function, it seems fine

**Comment by nekitoss** [comment]
How i can check that for you?
If you mean Log in the browser in domoticz - then there were no error tab present ( i know it appear if i'm doing something wrong in script).
If you mean OS on raspberry - then too, no restarts of OS were found (i have "online time"), also haven't noticed any restarts of domoticz itself (but i don't check it frequently and didn't watched log).
I noticed problem only when suddenly looked at memory usage and opened graph...

**UPD:**
at `~17:05` i've enabled backups again.
stairs appeared, as expected:
![chart](https://user-images.githubusercontent.com/11498479/44608601-f5aaaa80-a7fc-11e8-8dfd-a31a60ebf2f4.jpeg)
![chart2](https://user-images.githubusercontent.com/11498479/44608607-fa6f5e80-a7fc-11e8-9526-3a4d8ebe4e8f.jpg)

i've logined twice and checked **syslog** - before and after:
```
Aug 24 07:17:01 raspberrypi CRON[27177]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 08:17:01 raspberrypi CRON[13395]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 09:17:01 raspberrypi CRON[331]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 10:17:01 raspberrypi CRON[16714]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 11:17:01 raspberrypi CRON[1851]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 12:17:01 raspberrypi CRON[21090]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 13:17:02 raspberrypi CRON[8806]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 14:17:01 raspberrypi CRON[27446]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 15:17:01 raspberrypi CRON[13174]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 16:17:02 raspberrypi CRON[426]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 17:06:30 raspberrypi dhcpcd[11174]: eth0: MTU set to 1492
Aug 24 17:07:22 raspberrypi systemd[1]: Starting Session c3 of user pi.
Aug 24 17:07:22 raspberrypi systemd[1]: Started Session c3 of user pi.
Aug 24 17:17:01 raspberrypi CRON[20402]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 18:17:02 raspberrypi CRON[7896]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 19:17:01 raspberrypi CRON[26569]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 20:17:01 raspberrypi CRON[13487]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 21:17:01 raspberrypi CRON[606]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 22:17:01 raspberrypi CRON[21642]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 24 23:17:01 raspberrypi CRON[9734]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 25 00:11:31 raspberrypi systemd[1]: Starting Session c4 of user pi.
Aug 25 00:11:31 raspberrypi systemd[1]: Started Session c4 of user pi.
```

in log tab in browser **error tab** appeared (maybe related to my script that i enabled back yesterday):
```
2018-08-23 01:11:57.612 Error: MySensors: Repeating previous command (2/2)
2018-08-24 18:01:17.680 Error: MySensors hardware (2) thread seems to have ended unexpectedly
2018-08-25 00:01:24.110 Error: MySensors hardware (2) thread seems to have ended unexpectedly
2018-08-25 00:20:53.836 Error: MySensors: Repeating previous command (2/2)
```

in **status tab** i have:
```
2018-08-23 01:11:55.732 Status: User: Admin initiated a switch command (56/Boiler_IR/Set Level)
2018-08-23 01:11:55.923 Status: dzVents: Info: Handling events for: "Boiler_IR", value: "Set"
2018-08-23 01:11:55.923 Status: dzVents: Info: ------ Start internal script: dummy3: Device: "Boiler_IR (Dummy)", Index: 56
2018-08-23 01:11:55.924 Status: dzVents: Info: Device Boiler_IR was changed to Set
2018-08-23 01:11:55.924 Status: dzVents: Info: ------ Finished dummy3
2018-08-23 01:11:55.983 Status: EventSystem: Script event triggered: /home/pi/domoticz/dzVents/runtime/dzVents.lua
2018-08-23 01:17:13.932 Status: MySensors: Node: 2, Sketch Name: Boiler Temperature Sensor
2018-08-23 01:17:13.935 Status: MySensors: Node: 2, Sketch Version: 1.0
2018-08-23 18:53:19.297 Status: Incoming connection from: 192.168.1.7
2018-08-24 00:00:03.611 Status: EventSystem: reset all events...
2018-08-24 00:00:03.621 Status: dzVents: Write file: /home/pi/domoticz/scripts/dzVents/generated_scripts/dummy3.lua
2018-08-24 17:10:38.927 Status: Incoming connection from: 192.168.1.7
2018-08-24 18:00:02.638 Status: Starting automatic database backup procedure...
2018-08-24 18:01:17.679 Status: Ending automatic database backup procedure...
2018-08-24 19:00:03.706 Status: Starting automatic database backup procedure...
2018-08-24 19:00:37.150 Status: Ending automatic database backup procedure...
2018-08-24 20:00:01.324 Status: Starting automatic database backup procedure...
2018-08-24 20:00:33.269 Status: Ending automatic database backup procedure...
2018-08-24 21:00:00.826 Status: Starting automatic database backup procedure...
2018-08-24 21:00:33.212 Status: Ending automatic database backup procedure...
2018-08-24 22:00:09.308 Status: Starting automatic database backup procedure...
2018-08-24 22:00:47.216 Status: Ending automatic database backup procedure...
2018-08-24 23:00:00.853 Status: Starting automatic database backup procedure...
2018-08-24 23:00:30.134 Status: Ending automatic database backup procedure...
2018-08-25 00:00:04.134 Status: EventSystem: reset all events...
2018-08-25 00:00:04.135 Status: dzVents: Write file: /home/pi/domoticz/scripts/dzVents/generated_scripts/dummy3.lua
2018-08-25 00:00:04.308 Status: Starting automatic database backup procedure...
2018-08-25 00:01:24.108 Status: Ending automatic database backup procedure...
2018-08-25 00:07:54.773 Status: Incoming connection from: 192.168.1.7
2018-08-25 00:20:51.167 Status: Incoming connection from: 192.168.1.7
```
(added small part of log from previous day)

Now i disabled script to be shure it doesn't generate an error, and waiting for your reply

FYI **script code** is:
```
return {
	on = {
		devices = {
			'Boiler_IR'
		}
	},
	execute = function(domoticz, device)
	    domoticz.devices(29).updateText(device.state)
		domoticz.log('Device ' .. device.name .. ' was changed to ' .. device.state, domoticz.LOG_INFO)
-- 		domoticz.devices(59).updateText('FromDZVents')
-- 		domoticz.log('Device ' .. domoticz.devices(59).name .. ' was changed to ' .. domoticz.devices(59).text, domoticz.LOG_INFO)
	end
}
```

**Comment by gizmocuz** [comment]
Ok, please let the backup continue, see if you have a memory issue (your pi should crash , or domoticz)
It takes 30 seconds to make a backup.. that's a long time, in this time, everything has to wait...
do you need it that frequently ? 
Maybe i should rebuild the backup functionality to do only daily/weekly/monthly backups instead of hourly

**Comment by nekitoss** [comment]
no, i think i really don't need them if nothing happens (or if i don't update domoticz). just found problem and source of it, and trying to help you =)

So, nothing happend:
- same messages (only dates chenged) in syslog `CRON[xxxxx]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)`
- memory reached ~93% on 25th, and floating at that point
- same error messages  `MySensors hardware (2) thread seems to have ended unexpectedly` in error tab in domoticz - but from 29th more frequently: every hour at time of backup.

checked "disk" space :
```
user@raspberrypi:~ $ df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root        7508524 6388152    760732  90% /
devtmpfs          468148       0    468148   0% /dev
tmpfs             472756       0    472756   0% /dev/shm
tmpfs             472756    6372    466384   2% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs             472756       0    472756   0% /sys/fs/cgroup
/dev/mmcblk0p1     64456   22248     42208  35% /boot
tmpfs              94552       0     94552   0% /run/user/1000
```

and size of backups dir:
```
user@raspberrypi:~/domoticz $ sudo du -sh
1.4G    .
```

I may try upgrade distro, hoping nothing will break. I don't think theer will be ay crash - my system worked a lot of time in same mode... it was just luck that i noticed....

```
user@raspberrypi:~ $ uptime
 01:18:58 up 8 days, 20:13,  2 users,  load average: 0.15, 0.10, 0.14
```
![chart 3](https://user-images.githubusercontent.com/11498479/44882438-f55a5580-acbb-11e8-8df9-cc180b29815b.jpeg)
those little spikes are at 6.30 in the morning. then at 7.00 (at backup) goes back down a little. last spike is now, when i'm checking all this.

**Comment by heggink** [comment]
Since the original cause was determined to not be a domoticz issue, do you want me to close?

**Comment by gizmocuz** [comment]
Yes thank you, i will close it
