### ISSUE TITLE
HUE: Not yet perfect

### ISSUE THREAD

**Issue by chrislader** [domoticz/domoticz#2529]
Since last fix, my HUE lights are working better, but not all.

Case:
- turning on lights through HUE app, they get polled within domoticz and are all turned on as well. This is fixed since last beta. Goes for hue color, white and lux lights.

Case2:
- turning on lights through a scene (hue scene from devices, not domoticz scene) all lamps get turned on as well, however only my colored lamps and hue lux lights are polled and turned on in domoticz. My HUE white lamps are on, but not in Domoticz; it still sees them as “off” (while in fact they are on).

**Comment by chrislader** [comment]
In case1: the HUE white lights also are not seen in domotcz after turning on by HUE app. So color and lux are polled correctly and turned on in domoticz, but HUE white lights are not (they are on, but not in domoticz). Polling seems not to work for them.

Everything worked perfect while i was on 3.x 
Now i am on latest beta.

**Comment by chrislader** [comment]
Running on rasp pi. Stretch

Beta: 4.9732

**Comment by chrislader** [comment]
Extra addition; they are “HUE White Ambiance” lights

**Comment by chrislader** [comment]
Might found a clue;

When starting up domoticz, I see that the lights are defined as color (which they are not)![Image](https://i.imgur.com/SIXtkBK.jpg)

Not sure, but i noticed the HUE lux lights are not defined as color (they work)

**Comment by chrislader** [comment]
Ok, found the problem and solution.

It appears that since the last update my ambiance lights are identified 2 times;

1. In devices tab they are identified as subtype “AC”. These are not synced at polling, but DO work when pressed.

2. I found a second identical device (for the same light) identified as subtype “WW”. This one does work! It gets polled. It also has a color icon (to select the color of white).

So I guess that others have the same problem during last updates. Solution is easy.

**Comment by emontnemery** [comment]
@chrislader If your light is of type WW, it should be identified as a color switch of type WW, not as an AC switch. If you remove the 2 copies of the same light, is it again identified twice?

**Comment by NiekN** [comment]
I have a small issue about the Hue.
Now the level of a hue bulb is visible. If i switch them ON, i see the state is 'ON' but also the level is set correctly.  When i activate DIM mode, the light will go the 50% , and that is also shown in the level bar .
But when i switch the lights OFF , the state will show OFF , but the level bar will not go the 0%

![hue](https://user-images.githubusercontent.com/32562791/42690983-a0cd2ae6-86a6-11e8-9ba3-d62a36e77212.jpg)

**Comment by darkrain-nl** [comment]
I like that behavior, cause when you now turn the light back on it will have the same % as before. That is very nice when turning the lights on via script.
I would also not say this is a bug...

**Comment by gizmocuz** [comment]
I agree, it's also with most switches

**Comment by chrislader** [comment]
Ok, there is still a problem with Hue lights who are identified as ‘AC’. For example Hue Lux (EOL product).

I still have a few of those. They are not synced/polled correctly when I operate them using the hue app.

It seems to have something to do with AC hue lights. There is another topic with an AC switch from busch jaeger; maybe they are related.

**Comment by chrislader** [comment]
Its #2613
