### ISSUE TITLE
Can't compile on debian wheezy

### ISSUE THREAD

**Issue by vansatchen** [domoticz/domoticz#2531]
Debian Wheezy with gcc 4.7.2 and boost 1.67 with last upgrades.

`ugu@NAS:/mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz$ cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt -DCURL_INCLUDE_DIR=/mnt/HD/HD_a2/Nas_Prog/curl/include/curl -DCURL_LIBRARY=/mnt/HD/HD_a2/Nas_Prog/curl/lib/libcurl.a -DUSE_PYTHON=NO
-- The C compiler identification is GNU 4.7.2
-- The CXX compiler identification is GNU 4.7.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Failed to get ProjectRevision from git
-- Read ProjectRevision from appversion.default
-- ###########################
-- Compiling Revision #9700
-- ###########################
-- Using builtin Mosquitto library
-- Found OpenSSL: /usr/lib/arm-linux-gnueabi/libssl.so;/usr/lib/arm-linux-gnueabi/libcrypto.so (found version "1.0.1t") 
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Looking for 3 include files sys/types.h, ..., linux/i2c.h
-- Looking for 3 include files sys/types.h, ..., linux/i2c.h - found
-- Building with I2C support
-- Looking for include files sys/types.h, linux/spi/spidev.h
-- Looking for include files sys/types.h, linux/spi/spidev.h - found
-- Building with SPI support
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- OPENSSL_LIBRARIES: /usr/lib/arm-linux-gnueabi/libssl.so;/usr/lib/arm-linux-gnueabi/libcrypto.so
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   system
-- Linking against boost static libraries
-- Found ZLIB: /usr/lib/arm-linux-gnueabi/libz.so (found version "1.2.7") 
-- ZLIB libraries found at: /usr/lib/arm-linux-gnueabi/libz.so
-- ZLIB includes found at: /usr/include
-- Found CURL: /mnt/HD/HD_a2/Nas_Prog/curl/lib/libcurl.a  
-- Curl libraries found at: /mnt/HD/HD_a2/Nas_Prog/curl/lib/libcurl.a
-- Curl includes found at: /mnt/HD/HD_a2/Nas_Prog/curl/include/curl
-- Found LIBUSB: /usr/lib/arm-linux-gnueabi/libusb.so  
-- LIBUSB found at: /usr/lib/arm-linux-gnueabi/libusb.so
-- ==== OpenZWave not found, support disabled!
-- GPIO is not available
-- Not found telldus-core (telldus-core.h), not adding tellstick support
/usr/bin/c++  ;;-std=c++11;-O3;-DNDEBUG;-I/mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main;-I/mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/tinyxpath;-I/usr/include;-I/usr/local/include;-I/usr/include;-I/mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/zip;-I/mnt/HD/HD_a2/Nas_Prog/curl/include/curl;-DBUILTIN_MQTT;-DHAVE_EXECINFO_H;-DHAVE_LINUX_I2C;-DHAVE_LINUX_SPI;-DWWW_ENABLE_SSL;-DWITH_LIBUSB -x c++-header -o /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/stdafx.h.gch/.c++ /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/stdafx.h
-- Using static libgcc/libstdc++
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz`

`[ 20%] Building CXX object CMakeFiles/domoticz.dir/main/Camera.cpp.o                                                                                                                         
In file included from /usr/local/include/boost/asio/use_future.hpp:156:0,
                 from /usr/local/include/boost/asio.hpp:131,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPClient.h:3,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPServer.h:4,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/mainworker.h:11,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/Camera.cpp:7:
/usr/local/include/boost/asio/impl/use_future.hpp: In function ‘void boost::asio::detail::promise_invoke_and_set(std::promise<T>&, F&, Args&& ...)’:
/usr/local/include/boost/asio/impl/use_future.hpp:49:21: error: ‘current_exception’ is not a member of ‘std’
/usr/local/include/boost/asio/impl/use_future.hpp:49:21: note: suggested alternative:
In file included from /usr/local/include/boost/exception_ptr.hpp:9:0,
                 from /usr/local/include/boost/thread/exceptional_ptr.hpp:10,
                 from /usr/local/include/boost/thread/future.hpp:25,
                 from /usr/local/include/boost/thread.hpp:24,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/stdafx.h:57:
/usr/local/include/boost/exception/detail/exception_ptr.hpp:437:5: note:   ‘boost::current_exception’
In file included from /usr/local/include/boost/asio/use_future.hpp:156:0,
                 from /usr/local/include/boost/asio.hpp:131,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPClient.h:3,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPServer.h:4,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/mainworker.h:11,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/Camera.cpp:7:
/usr/local/include/boost/asio/impl/use_future.hpp: In function ‘void boost::asio::detail::promise_invoke_and_set(std::promise<void>&, F&, Args&& ...)’:
/usr/local/include/boost/asio/impl/use_future.hpp:63:6: error: invalid use of incomplete type ‘class std::promise<void>’
In file included from /usr/local/include/boost/asio/packaged_task.hpp:23:0,
                 from /usr/local/include/boost/asio.hpp:101,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPClient.h:3,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPServer.h:4,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/mainworker.h:11,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/Camera.cpp:7:
/usr/include/c++/4.7/future:123:11: error: declaration of ‘class std::promise<void>’
In file included from /usr/local/include/boost/asio/use_future.hpp:156:0,
                 from /usr/local/include/boost/asio.hpp:131,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPClient.h:3,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPServer.h:4,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/mainworker.h:11,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/Camera.cpp:7:[ 20%] Building CXX object CMakeFiles/domoticz.dir/main/Camera.cpp.o                                                                                                                         
In file included from /usr/local/include/boost/asio/use_future.hpp:156:0,
                 from /usr/local/include/boost/asio.hpp:131,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPClient.h:3,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPServer.h:4,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/mainworker.h:11,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/Camera.cpp:7:
/usr/local/include/boost/asio/impl/use_future.hpp: In function ‘void boost::asio::detail::promise_invoke_and_set(std::promise<T>&, F&, Args&& ...)’:
/usr/local/include/boost/asio/impl/use_future.hpp:49:21: error: ‘current_exception’ is not a member of ‘std’
/usr/local/include/boost/asio/impl/use_future.hpp:49:21: note: suggested alternative:
In file included from /usr/local/include/boost/exception_ptr.hpp:9:0,
                 from /usr/local/include/boost/thread/exceptional_ptr.hpp:10,
                 from /usr/local/include/boost/thread/future.hpp:25,
                 from /usr/local/include/boost/thread.hpp:24,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/stdafx.h:57:
/usr/local/include/boost/exception/detail/exception_ptr.hpp:437:5: note:   ‘boost::current_exception’
In file included from /usr/local/include/boost/asio/use_future.hpp:156:0,
                 from /usr/local/include/boost/asio.hpp:131,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPClient.h:3,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPServer.h:4,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/mainworker.h:11,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/Camera.cpp:7:
/usr/local/include/boost/asio/impl/use_future.hpp: In function ‘void boost::asio::detail::promise_invoke_and_set(std::promise<void>&, F&, Args&& ...)’:
/usr/local/include/boost/asio/impl/use_future.hpp:63:6: error: invalid use of incomplete type ‘class std::promise<void>’
In file included from /usr/local/include/boost/asio/packaged_task.hpp:23:0,
                 from /usr/local/include/boost/asio.hpp:101,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPClient.h:3,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPServer.h:4,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/mainworker.h:11,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/Camera.cpp:7:
/usr/include/c++/4.7/future:123:11: error: declaration of ‘class std::promise<void>’
In file included from /usr/local/include/boost/asio/use_future.hpp:156:0,
                 from /usr/local/include/boost/asio.hpp:131,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPClient.h:3,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPServer.h:4,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/mainworker.h:11,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/Camera.cpp:7:
...
/usr/local/include/boost/exception/detail/exception_ptr.hpp:42:5: note:   ‘boost::exception_ptr’
In file included from /usr/local/include/boost/asio/use_future.hpp:156:0,
                 from /usr/local/include/boost/asio.hpp:131,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPClient.h:3,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/../tcpserver/TCPServer.h:4,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/mainworker.h:11,
                 from /mnt/HD/HD_a2/Nas_Prog/Domoticz/domoticz/main/Camera.cpp:7:
/usr/local/include/boost/asio/impl/use_future.hpp:558:64: error: template argument 1 is invalid
make[2]: *** [CMakeFiles/domoticz.dir/main/Camera.cpp.o] Error 1
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
make: *** [all] Error 2`

Please, how can i fix it?
Domoticz building for NAS Dlink DNS-327l with original firmware and appropriate to debian wheeze components like kernel, libc6 and other.
Older versions of domoticz build without problems.

**Comment by gizmocuz** [comment]
You need GCC 6.7 or higher, boost 1.67

**Comment by Jumbotroll** [comment]
GCC 4.7 or higher is it not?

**Comment by vansatchen** [comment]
On debian jessy with gcc 4.9 same errors. Its so sadly. Will have to look for other solutions. Thanks.

**Comment by gizmocuz** [comment]
Gcc 6.7 or higher
Just update gcc
And you should install stretch...

**Comment by thegwydd** [comment]
I know it's an old issue but I come across this page looking for the solution to the same problem.
I'm writing here just for who's looking for same solution.
I've been able to build asio 1.13.0 (non-boost) on gcc 4.9.2 using -DASIO_DISABLE_STD_FUTURE.
If you use the asio boost version you need to use -DBOOST_ASIO_DISABLE_STD_FUTURE
I know it's not the same setup but it may help.
