### ISSUE TITLE
Undefined with edit switches

### ISSUE THREAD

**Issue by orgalinq** [domoticz/domoticz#2535]
I have Domoticz version 4.9700 now.
If I want to update switches (switches tab), I get the message "not defined".
(I don't know if it was also the case with the previous version.)
What can I do, please help.

Best regards,
Jan Walhof
![undefined](https://user-images.githubusercontent.com/10545973/42160043-1d6eceba-7df6-11e8-8fa2-fd7d42e86059.png)

**Comment by GravityRZ** [comment]
did you clear browser cache, close/open browser and tried again?

**Comment by orgalinq** [comment]
Thank you for your reply.
Problem solved. Indeed I cleared with chrome browser the browser cache. No change. But after chrome://appcache-internals/# the problem was solved.
