### ISSUE TITLE
Meter readings and Graphs

### ISSUE THREAD

**Issue by jonferreira** [domoticz/domoticz#2540]
following the discussion at https://github.com/domoticz/domoticz/commit/9cfe88a6ced8d62de6206ae76306552fb9e87c16

The way graphs are implemented, if N is lower than N-1, graph will go crazy.

I reckon there should be a check such as

if ( n > (n-1)) {
value = n - (n-1)
else
value = n

**Comment by gizmocuz** [comment]
Correct, but HOW can a counter value be lower then a previous value ? a counter is ALWAYS incremental

**Comment by jonferreira** [comment]
Theoretically: yes. Real world: no. 
Take the RFXMeter / WPC3 counter, if power goes out the pulse count is reset. Same happens if the pulse count max out (think it's a 32bit number)
Should be a small fix that won't have any negative impact and should ensure the graphs don't get all messed up when / if that happens. 
Honestly, right now it's the one thing I think Dominicz needs improving :)

Edited: Removed email stuff

**Comment by gizmocuz** [comment]
Okey, please make a PR

**Comment by jonferreira** [comment]
I would if I could, unfortunately I can't seem to get to grips with domo development :(

I'd say the necessary edit would be at WebServer.cpp@14205

changing
`
float TotalValue = float(actValue - ulFirstValue);`

to 

```
if(actValue > ulFirstValue) {
float TotalValue = float(actValue - ulFirstValue);
} else {
float TotalValue = float(actValue);
}
```

I may be wrong though...

**Comment by gizmocuz** [comment]
@jonferreira , what problems are you struggling with to compile Domoticz ?
The easiest would be visual studio maybe ? Very good debugging/breakpoint options
I think you are close with the fix, but don't want untested code....

**Comment by jonferreira** [comment]
No problem **compiling**,  just me being a noob and struggling to get started :)

**Comment by gizmocuz** [comment]
You could try these instructions:

https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source

It could be that you need to patch 'ulFirstValue' as well

So two options, your sollution:

`float TotalValue = (actValue > ulFirstValue) ? float(actValue - ulFirstValue) : actValue`

or

```
float TotalValue;
if(actValue > ulFirstValue) {
        TotalValue = float(actValue - ulFirstValue);
} else {
        TotalValue = float(actValue);
        ulFirstValue = actValue;
}
```

**Comment by jonferreira** [comment]
Thanks @gizmocuz, I'll see if I can setup a VM with windows + VS for developing

I've tried it in the past with domo and could never make it work to be honest,can't recall what the problem was though :(

You code does look good and "should" work, obviously needs to be tested first

**Comment by jonferreira** [comment]
OK just made a PR with the fix, seems to do the trick :)

before
![image](https://user-images.githubusercontent.com/7714292/42479433-c546d62a-83d0-11e8-825b-5e7f38477bbd.png)

after
![image](https://user-images.githubusercontent.com/7714292/42479404-ab4eba80-83d0-11e8-8774-d2e7ec15c798.png)

**Comment by gizmocuz** [comment]
Thanks for the PR, but could you make the PR against the development branch, not the master branch ?

**Comment by jonferreira** [comment]
my bad,should be OK now

**Comment by gizmocuz** [comment]
Thanks!, Merged the PR ;)

**Comment by xztraz** [comment]
what if this was implemented on the counter itself than just the presentation of the data.
This is of course solvable in dzvents quite easily but it would be a nice addition to keep data sensible from the start.
