### ISSUE TITLE
Synology armada build error.

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#2542]
Build error Domoticz V.4.0.9751 on Marvell Armada 370 88F6707.
x86 and apollolake (Intel Celeron J3355) is ok.

[ 21%] Building CXX object CMakeFiles/domoticz.dir/main/Camera.cpp.o
[ 21%] Building CXX object CMakeFiles/domoticz.dir/main/domoticz.cpp.o
/home/dahl/spksrc-master/spk/domoticz/work-armada370-6.2/domoticz-r9751/main/domoticz.cpp: In function ‘bool dumpstack_gdb()’:
/home/dahl/spksrc-master/spk/domoticz/work-armada370-6.2/domoticz-r9751/main/domoticz.cpp:96:21: error: ‘PR_SET_PTRACER’ was not declared in this scope
  int retval = prctl(PR_SET_PTRACER, PR_SET_PTRACER_ANY, 0, 0, 0);
                     ^
/home/dahl/spksrc-master/spk/domoticz/work-armada370-6.2/domoticz-r9751/main/domoticz.cpp:96:37: error: ‘PR_SET_PTRACER_ANY’ was not declared in this scope
  int retval = prctl(PR_SET_PTRACER, PR_SET_PTRACER_ANY, 0, 0, 0);
                                     ^
make[5]: *** [CMakeFiles/domoticz.dir/main/domoticz.cpp.o] Error 1
make[5]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-armada370-6.2/domoticz-r9751'
make[4]: *** [CMakeFiles/domoticz.dir/all] Error 2
make[4]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-armada370-6.2/domoticz-r9751'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-armada370-6.2/domoticz-r9751'

**Comment by gizmocuz** [comment]
It should be found in this header

#include <sys/prctl.h>

**Comment by gizmocuz** [comment]
I made a small code change, but it seems (reading elsewhere) it has to do with an old system architecture.
Those nasses are from 2015/2016, so thats not so old, is it possible to upgrade the building platform maybe ?
But it should compile now

**Comment by Jumbotroll** [comment]
Thanks! I will do a test build later tonight..

**Comment by Jumbotroll** [comment]
Fix working!
Marvell Armada 370 use pretty old Linux kernel 3.2.40
compiled with latest toolchain from synology for DSM 6.2
armada370-gcc493_glibc220_hard-GPL
I will take a look if I am missing some another updates, but another build with newer kernel working ok.
