### ISSUE TITLE
kWh meters, total usage counter gone

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#2544]
do not know when this happened but after upgrading to v4.9700 the totals are gone.
they are still in the report but not displayed as a counter anymore.
Also i noticed that some of the meters apparently display a negative usage 
in 9728 this is still the case
counters are set to compute instead of device but switching to device does not make a difference.

![image](https://user-images.githubusercontent.com/16853535/42418239-4db6adfe-829c-11e8-8138-0b5671ca74dd.png)

**Comment by Olifant1990** [comment]
I know from the past  the total counters are removed on purpose. You can view them on the device list as needed.
But maybe someone els can confirm this?

**Comment by gizmocuz** [comment]
Yes, they are removed for quite some time as it was just an incremental counter.
You can still see the total (if needed) from the report view
