### ISSUE TITLE
Incorrect Power notification

### ISSUE THREAD

**Issue by RezzZ** [domoticz/domoticz#2554]
I used this topic to receive a daily notification for my power and gas usage. I recently noticed that (at least in my setup) the power usage notification is off.

My power usage table (in domoticz) looks as follow (for the last 4 days, inc weekend):

DateTime | Usage 1 | Usage 2
-- | -- | --
2018-07-06 00:00:00 | 2.434 | 9.202 .     (sum=11636)
2018-07-07 00:00:00 | 14.214 | 0
2018-07-08 00:00:00 | 14.526 | 0
2018-07-09 00:00:00 | 2.928 | 9.354 .     (sum=12282)

the sums are correctly displayed in the log, but I received the following notifications at midnight in Telegram:
Domoticz WBP105, [07.07.18 00:00]
Power today: 7.6 kWh

Domoticz WBP105, [08.07.18 00:00]
Power today: 19.3 kWh

Domoticz WBP105, [09.07.18 00:00]
Power today: 20.2 kWh

Domoticz WBP105, [10.07.18 00:00]
Power today: 7.6 kWh

As you can see, none of them match what Domoticz is displaying.

The rule I've set up in the Power notifications window looks like this:

TYPE | WHEN | ACTIVE SYSTEMS | CUSTOM MESSAGE | PRIORITY | IGNORE INTERVAL | RECOVERY
-- | -- | -- | -- | -- | -- | --
Today | Greater 0 kWh | http | $name today: $value kWh | Normal | No | No

Any thoughts what might be going wrong here?

Tried looking up the values stored in the Domoticz database but can't seem te find the table storing usage statistics.

**Comment by gizmocuz** [comment]
It could be in the Meter or Multimeter tables, but have a look at the ID of your sensor.
Best to ask this in the forum, is it a P1 Smart meter?

**Comment by RezzZ** [comment]
Yes, P1 Smart meter. I will check the tables!

**Comment by gizmocuz** [comment]
Did you find anything odd ?

**Comment by RezzZ** [comment]
ok, so here is what I found. for the P1 meter there are 6 values stored in the Multimeter_Calendar table.

DeviceRowID | Value1 | Value2 | Value3 | Value4 | Value5 | Value6 | Counter1 | Counter2 | Counter3 | Counter4 | Date 
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
104|14526|0|5715|0|0|0|2362215|0|1760320|0|2018-07-08
104|2928|0|4667|0|9354|0|2365169|0|1769674|0|2018-07-09

Values 1 and 5 are the values for Usage 1 and 2. But, at least for me, the value 3 also has a value.

Weird thing though, in the weekend this values is added to the usage1, and during weekdays the value is subtracted from the sum of usage 1 and 2.

This cannot be right?

**Comment by gizmocuz** [comment]
I always have a peek at the code inserting these values int the database ;)

Normal multi_meter_table: (short log)
				value1 = powerusage1;
				value2 = powerdeliv1;

				value5 = powerusage2;
				value6 = powerdeliv2;

				value3 = usagecurrent;
				value4 = delivcurrent;

Meter table:
First we get the min/max from the normal table values:
MIN(Value1), MAX(Value1), MIN(Value2), MAX(Value2), MIN(Value3), MAX(Value3), MIN(Value4), MAX(Value4), MIN(Value5), MAX(Value5), MIN(Value6), MAX(Value6)

For the P1, we store the
value 1 = MAX(Value1)-MIN(Value1)
value 2 = MAX(Value2)-MIN(Value2)
value 3 = MAX(Value3)-MIN(Value3)
value 4 = MAX(Value4)-MIN(Value4)
value 5 = MAX(Value5)-MIN(Value5)
value 6 = MAX(Value6)-MIN(Value6)

So here in the Netherlands (so at your place too), the meter swappes between Usage1 and Usage2 (day/night) and weekend, and if you have solar panels at return power, also Deliv1/Deliv2, but thats not the case here

So, first entry, 2018-07-08, thats a sunday, the meter is on night/weekend mode, that is only usage1
so you only get values 1 and 3

This meter was the first device supported in domoticz, and exists for 4 years, i am sure it is OK

**Comment by RezzZ** [comment]
you are right that the 8th of July is a Sunday so I don't see a Usage2 value, but why is the usagecurrent (value3) added to the reported powerusage for that day? My daily usage is the value for usage1 = 14526. This is also the usage domoticz is reporting in the frontend for that day, in the graphs and it's tables.
Is my notification setup incorrect? Should I use something else as $value?

**Comment by waltervl** [comment]
No updates, closing this very old issue.
