### ISSUE TITLE
Z-Wave controler and nodes not visible in beta 4.9758

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#2555]
Win7 platform, run as service.
Upgraded from 4.9732 to 4.9758

After upgrade all Z-Wave support was gone, or at least not visible in Settings page there all devices is normally.

Tried to restart both Domoticz Service and then Machine from cold reboot but same result, so I restored my whole Domoticz folder and all was back up and running again in 4.9732 mode.

By the way, why is the beta download file indicating 4.9722? It was the same when I upgraded to 4.9732 but at that time I guessed it was just a one time coincidence...?  

Thanks!

**Comment by pipiche38** [comment]
Same problem here #2556

**Comment by gizmocuz** [comment]
If you open the chrome developer console (F12) , does it show anything ?

**Comment by pipiche38** [comment]
Problem is fixed with v4.9763 !

**Comment by RicardP** [comment]
Yes, thanks gizmocuz and for feedback pipiche38. And yes it works again in last beta just installed here 4.9763.

Cheers!
