### ISSUE TITLE
OpenZwave HW doesn't display the nodes anymore 

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2556]
I have updated with a git pull my domoticz beta branch . V4.9756

Since , I am not able to see the Open ZWave nodes. Hopefully the Openzwave Control panel works !

No error in the logs

Here are the screenshots:
<img width="1284" alt="screen shot 2018-07-10 at 19 58 14" src="https://user-images.githubusercontent.com/8291674/42529260-44d12168-847e-11e8-9905-391037159bc9.png">

<img width="1363" alt="screen shot 2018-07-10 at 19 57 58" src="https://user-images.githubusercontent.com/8291674/42529261-4505b7fc-847e-11e8-8ed2-6e1cddbd4fae.png">

<img width="1630" alt="screen shot 2018-07-10 at 19 58 29" src="https://user-images.githubusercontent.com/8291674/42529259-448f87a8-847e-11e8-8c39-53a29e7da99e.png">

**Comment by pipiche38** [comment]
The Group&Network function which give a map of the Zwave network doesn't produce anything !

**Comment by gizmocuz** [comment]
Did you cleared your browser cache + appcache ? If you open the chrome developer console, does it report anything when you press the setup button ?
I still see all nodes here on 9758

**Comment by pipiche38** [comment]
Did a full clear of the firefox (MacOs) and problem remains
Did try with Safari same proble

**Comment by Biggav87** [comment]
I have the same issue, my system is running on a pi using the razberri daughter board. i am using chrome on windows 7. I have nothing in the log of domoticz nor in the chrome log. i have also just added a new wallmote quad switch and it appears in the openzwave console but not in domotics. i have tried clearing the cache and app cache with no luck.

i have also reported it here with no responses yet.
https://www.domoticz.com/forum/viewtopic.php?f=6&t=24135&p=185978#p185978

**Comment by rwaaren** [comment]
Same issue on Chrome Version 67.0.3396.99  and Edge and Iexplorer on windows 10.
Even after clearing cache and appcache

**Comment by gizmocuz** [comment]
None of you mention anything about the developer console, this is very important as it might be a javascript error
I updated two other systems here (both raspberry) to 9578, also no issues

@Biggav87 , that might be another issue, did you enable accept new hardware in the settings ?
Did you add it via the domoticz openzwave setup, or directly on the stick ?

**Comment by rwaaren** [comment]
@Gizmocuz 

developer console in chrome complain about missing file
blob:http://192.168.192.51:8084/9b5216c5-48c3-4bff-b389-b58726cd51a1:1

**Comment by Biggav87** [comment]
@gizmocuz This is all i have in the console, the non-unique error repeats a couple of time further. 

When i added the new device (fresh out of the box) i clicked the 'include node' button under the 'node management' menu. i am adding this to an existing operational system and when the new device is added you get the usual popup identifying the device however it doesn't end up on the list.

![image](https://user-images.githubusercontent.com/30516860/42556108-160ae2b6-851d-11e8-8c25-2740c8e5750c.png)

**Comment by rwaaren** [comment]
Only replacing binary with V4.9756  ==>> same behaviour
Only replacing binary with V4.9754  ==>> Nodes reappear

**Comment by Biggav87** [comment]
excuse my ignorance @rwaaren what exactly did you change? and how?

**Comment by rwaaren** [comment]
@Biggav87 Sent you a PM on the forum but in short; I copied the locally kept previous binaries over the current domoticz binary on my test system and restarted domoticz. This is NOT an advise to do this on your production system as it might break stuff.

**Comment by ookonbekend** [comment]
@gizmocuz Fyi, I've the same issue

**Comment by gizmocuz** [comment]
@Biggav87 , sorry, i can not see the file that is missing in the error.
You only copied the executable ? In that case, there is no file missing

**Comment by ookonbekend** [comment]
![image](https://user-images.githubusercontent.com/33123496/42568643-1e58472e-850e-11e8-8780-987270fa7c10.png)

Not sure if this error is related or new, but this one is different compared to the other errors (like Biggav87's screenshot)

**Comment by gizmocuz** [comment]
This is not a file from Domoticz
@ookonbekend , could you (or someone else) send me a PM on the forum, i would like to see this myself via remote access to domoticz...
Very strange, updated 3 machines with each an OZW usb stick, all working fine

**Comment by ookonbekend** [comment]
@gizmocuz Sorry, I can't assist you with a remote session (Policies, hopefully someone else can!)

Additional, when click Node management > Groups & Network, I get a empty screen and the following error

PS I use a Aeotec ZW090 Z-Stick Gen5 EU

![image](https://user-images.githubusercontent.com/33123496/42573326-19e7c4ae-851c-11e8-8414-6f2d905d78a8.png)

**Comment by gizmocuz** [comment]
@ookonbekend , no problem, i think @pipiche38 already contacted me, hopefully we get this sorted.
In your case, it looks that

json.htm?type=command&param=zwavegroupinfo&idx=<HW_IDX>

does not return any nodes, where HW_IDX is the idx in the hardware setup page

http://xxx.xxx.xxx.xxx:8080/json.htm?type=command&param=zwavegroupinfo&idx=<HW_IDX>

**Comment by ookonbekend** [comment]
Correct!
http://xxx.xxx.xxx.xxx:8080/json.htm?type=command&param=zwavegroupinfo&idx=<HW_IDX>

{
   "result" : {
      "MaxNoOfGroups" : 0
   },
   "status" : "OK",
   "title" : "ZWaveGroupInfo"
}

**Comment by gizmocuz** [comment]
I did change some bits in the code, but that should have the same functionality

Changed:

`unsigned int homeID = boost::lexical_cast<unsigned int>(sd[0]);`

to

`unsigned int homeID = (unsigned int)atoi(sd[1].c_str());`

there are a few lines with boost:lexical_cast i changes to 'atoi', double checked everything again

**Comment by gizmocuz** [comment]
Wait a sec... i remember some zwave sticks with a large home id number. Could you export your database from the settings page, open this with an editor (for example with 'SQLite Expert Personal Edition')
Then open the ZWaveNodes table, and post the value of 'HomeID' ? (or a partly screenshot)

**Comment by ookonbekend** [comment]
Thanks for SQLite tip accessing the database ;-)
![image](https://user-images.githubusercontent.com/33123496/42575387-a108ab84-8520-11e8-8787-8aabf3127df2.png)

**Comment by gizmocuz** [comment]
Thanks ! Yes, that is what is going wrong... hold on.. doing some testing/debugging

**Comment by pipiche38** [comment]
Here is mine 
sqlite> select * from ZWaveNodes;
1|20|3290841831|1|Controller|Aeotec ZW090 Z-Stick Gen5 EU|0
2|20|3290841831|2|Unknown|FIBARO System FGMS001-ZW5 Motion Sensor|0
3|20|3290841831|3|Unknown|EUROtronic EUR_SPIRITZ Wall Radiator Thermostat|0
4|20|3290841831|4|Unknown|EUROtronic EUR_SPIRITZ Wall Radiator Thermostat|0
5|20|3290841831|5|Unknown|EUROtronic EUR_SPIRITZ Wall Radiator Thermostat|0
6|20|3290841831|6|Unknown|EUROtronic EUR_SPIRITZ Wall Radiator Thermostat|0
7|20|3290841831|7|Unknown|EUROtronic EUR_SPIRITZ Wall Radiator Thermostat|0
8|20|3290841831|8|Unknown|EUROtronic EUR_SPIRITZ Wall Radiator Thermostat|0

**Comment by gizmocuz** [comment]
Yep, also a large HomeID... fixed the screw up, code committed, and building a new beta
(That could take an hour because i changed some other things as well)

**Comment by ookonbekend** [comment]
Just updated to v4.9763
Great, all nodes visible again.
Many thanks for your efforts, much appreciated!

**Comment by pipiche38** [comment]
Yes, I do confirm.

Thanks a lot

**Comment by Biggav87** [comment]
I have just updated to V4.9763 and they are all back.

Thanks All!

**Comment by bbqkees** [comment]
This afternoon I restarted my machine. This evening I noticed my lights did not turn on. I was on 4.9760. Indeed no Z-Wave devices in the Z-Wave hardware page, the Z-Wave control panel is empty . However, after the update to 4.9763 still no Z-Wave devices and all Z-Wave switches are red.

There is still a populated ZWaveNodes table in the database. Home ID is just 8 digits long.

Do I need to restore a backup or is there another solution?

**Comment by gizmocuz** [comment]
@bbqkees , maybe just disable/enable the hardware... this has nothing to do with this bug, as nodes where operational and visible in the control panel.
Could be that usb ports have swapped ?

**Comment by bbqkees** [comment]
disable/enable did not work unfortunately.
USB device is persistent, and I can see it's still there with lsusb.
All other hardware is running fine, my Hue lights f.i. turn on in the evening.

The following appears in the Domoticz log, it times out 5 times:
```
OpenZWave: Starting...
2018-07-13 08:56:20.122 Status: OpenZWave: Version: 1.4-3102-g8bbcfb25-dirty
2018-07-13 08:56:21.127 Status: OpenZWave: Received timeout notification from HomeID: 0, NodeID: 255 (0xff) 
```

I'm running it on Debian Stretch (recently updated succesfully from Jessy).

**Comment by gizmocuz** [comment]
Could you stop domoticz
edit the zwave configuration file (or restore a backup) in Config/zwcfg_xxxxx.xml (replace xxxx with the correct id)
Check if you have a xml node for node 0 or 255, remove them (be careful to keep the xml syntax intact)
Now start domoticz, it should work again

**Comment by bbqkees** [comment]
I have no node with id 0 or 255 in that config file.

Could it be a hardware failure?

**Comment by gizmocuz** [comment]
Hope not.... yes, you should not have node 0 or 255 ... do you use the binary version ?

**Comment by bbqkees** [comment]
I'm sorry but what do you mean with 'binary version'?
I'm using the older Aeotec Zstick v2.

**Comment by gizmocuz** [comment]
Are you compiling domoticz yourself ?
If you plug the stick in a windows system and launch domoticz, is it starting correctly ?

**Comment by gizmocuz** [comment]
(But again, you should create another issue actually for this)

**Comment by bbqkees** [comment]
Turns out the stick was turned off for some reason, normally a blue led is on when it is plugged in but it was not.
After I reinserted the stick the blue light came back on and everything is back.

**Comment by gizmocuz** [comment]
@bbqkees , pfview... great to hear it's working again!
