### ISSUE TITLE
Daiking hardware doesn't manage setpoint, fan speed ..

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2562]
Since v4.9701 Daiking hardware doesn't work any more.

- Pooling not working
- Setpoint not working
- Fan speed not working
- Mode not working

Looks like a lot of refactoring/cleanup have been made and impact drastically the behaviour

**Comment by pipiche38** [comment]
OK. seems that remove the hardware and create it again, solve some of the issues.

However it looks like there are some strange behaviour like 
You switch on
You set a SetPoint
You Set to Cold
==> The SetPoint is overwritten by an other temperature (most likely from the Daikin Split itself, which has some memory of temp ... based on Mode )

=> So I think we need to enhance the Daikin hardware to accomodate better with all of the values returned by the get_control_info

**Comment by gizmocuz** [comment]
ehhh don't think this was a refactor issue right ?

**Comment by pipiche38** [comment]
@gizmocuz you are correct. I have no idea why I had to delete the hardware and create again, for the rest this seems to be buggy from start ;-)

**Comment by gizmocuz** [comment]
Good to hear, as a lot of work had been put into the cleanup and refactoring.
Maybe you can find the cause and create a PR

**Comment by pipiche38** [comment]
Created #2565 for the Mode changes versus Temperature, Fan rate and Fan direction

**Comment by pipiche38** [comment]
Seems that I'm in the trouble again. When switching from one mode to the other, I see the Status message in Domoticz

`Status: User: support initiated a switch command (419/Clim Salon Mode/Set Level)`

But nothing is done on the Daikin hardware

A restart of the Hardware doesn't help !

Investigating how does it behave on the Stable branche v4.9701

**Comment by pipiche38** [comment]
While it looks like it works correctly on stable branch v4.9701

**Comment by pipiche38** [comment]
From my current investigation there are some part of the code which are not executed !
