### ISSUE TITLE
Feature request: Additional Group type "Blinds group"

### ISSUE THREAD

**Issue by gertfriend** [domoticz/domoticz#2564]
Would it be possbile to add under Scenes a new Group "Blinds Group" with the Buttons Open, Close AND Stop?

I would like to define Groups of Blinds to open and close (with stop not close - MY function at Somfy Remotes)

Thanks.

**Comment by gizmocuz** [comment]
Why not make one dummy blind/switch, and make a blockly/dzvents that handles the rest?
If dummy = close, then close blinds 1,2,3,4,5,6 etc

**Comment by ghost** [comment]
Would all of the blinds close simultaneously?

**Comment by gertfriend** [comment]
Yes, thats right. All blinds in the group will close simultaneously.
