### ISSUE TITLE
Daiking - Switching mode get the device memorized Temp, Fan rate and Fan direction

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2565]
As documented in  https://github.com/ael-code/daikin-control , when you change the Mode ( Auto, Cold, Fan, Heat, Deshum), the device take the memorized Temperature, Fan rate and Fan Direction.

So, when selecting a Mode, Domoticz should either do a GetSensorInfo() in order to update the various Domoticz devices, or memorize the different target Temperature, Fan rate and Fan direction per mode.

**Comment by gizmocuz** [comment]
Sounds like a plan !  Could you make a PR for this ? 
Currently each 300 seconds (5 minutes) the sensor details are queried, looks like at the end of 'WriteToHardware' a call to GetMeterDetails has to be done ?

**Comment by pipiche38** [comment]
That is a way, 

I was thinking an other way, which is when changing the Mode then the next onHeart we do a Pool in order to collect all Infos set by the Device.
In such we stay under the general synopsis of the program and we just do a GetMeterDetail and we avoid any re-entrance issue .

**Comment by gizmocuz** [comment]
Even simpler, just make sec_counter a member variable and set it to Daikin_POLL_INTERVAL - 5, so it will get polled after 5 seconds ?

**Comment by pipiche38** [comment]
Most likely it will be done in the SetModeLevel() as this is the place where we can switch from one Mode to and other one. While if we do it in the WriteToHardware() then it will be done in place where it is not needed like (setting Fan rate, Temperature Setpoint .... )

As, I'm not a C++ guru, I'll see how to implement your suggestion which looks pretty smart. I have seen the sec_counter already in the Do_Work()

**Comment by pipiche38** [comment]
@gizmocuz short question on better way to use GitHub. I currently have 2 files which have been changed, ( Daikin.ccp and Daikin.h ). As I do the change manually on Gihub via the web interface, this looks like I'll produce 2 PR.
Is there any better way to get only 1 PR integrating those 2 changes ?

**Comment by gizmocuz** [comment]
You have to go to our github page, and fork the repo (pressing the fork button), then you check it out to your account. Then you checkout your forked repo, make the changes (copy the two modified files back), commit the changes. Then you go back to your github project page, and you will see a button, create pull request. Do so, and you should be done.
I though you already made some changes to this class, thats what i see in the history ?

**Comment by pipiche38** [comment]
You right I already did, but was doing the fork file by file. I never 
did the fork ahead.

I'll do now, much better ...

**Comment by pipiche38** [comment]
I have a potential PR but it is against the Master branch 4.9701, but not on the dev branch due to #2569

**Comment by gizmocuz** [comment]
You have tot make the PR to the development branch

**Comment by pipiche38** [comment]
Problem found and not related to development branch #2570 , it is infact related to to a case where the Daikin device is in FAN mode and in such case, Temp and Hum are not set to a value but to '--'.

Will now fix this second problem in order to provide a PR addressing those.
