### ISSUE TITLE
Xiaomi Aqara Vima smart lock dont work

### ISSUE THREAD

**Issue by andrkaz** [domoticz/domoticz#2566]
Domoticz Version: 4.9700
After adding Vima smart lock to Xiaomi gateway and restart Domoticz (XiaomiMessage int 1 is true)  in log:

2018-07-14 17:26:02.991 Status: XiaomiGateway: unhandled model:
2018-07-14 17:26:02.991 Status: {"cmd":"read_ack","model":"","sid":"158d000222b1a8","short_id":34862,"data":"{\"voltage\":3314}"}

How to repair this?

**Comment by corbinmunce** [comment]
Are you on the latest firmware for your Xiaomi Gateway?  If so, we need to wait for an update from Xiaomi.

this bit: **"model":""**, indicates it is new hardware, but not yet supported by the API.

**Comment by andrkaz** [comment]
Firmware version is 1.4.1_155.0143. Plugins also up to date

**Comment by Nemesis24** [comment]
This is the same thing for me ... with 1.4.1_156.0143

**Comment by PeggyFree** [comment]
Are we waiting for a Xiaomi Gateway firmware update or a Domoticz Xiaomi Plugin update?

**Comment by andrkaz** [comment]
Gateway firmware updated to 1.4.1_157.0143 No news

**Comment by andrkaz** [comment]
Gateway firmware updated to 1.4.1_159.0143 No news

**Comment by DAVIZINH0** [comment]
any news about this?

**Comment by andrkaz** [comment]
No. Gateway firmware is 1.4.1_167.0158 and lock dont support

**Comment by DAVIZINH0** [comment]
:-( thanks for your reply!

**Comment by andrkaz** [comment]
Two years from the start of sales Vima lock. I see there will never be support for a lock in the gatewayю If any want use Vima lock in Domoticz: 
Buy USB dongle CC2531 and use zigbee2mqtt.io. It support devices, which not support by Xiaomi gateway

**Comment by waltervl** [comment]
Issue can be closed

**Comment by gizmocuz** [comment]
We indeed support zigbee2mqtt and with this it should work
