### ISSUE TITLE
Migrating the Zigate python plugin to a Native hardware device manager

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2567]
Zigate is a USB/Wifi stick which enable to control a number of Zigbee devices.

Today the Zigate hardware is managed via a python plugin. It would be nice to have a migration of this plugin to a Native domoticz hardware .

I'm more than willing to contribute to the development, but I need someone to draw the first C++ skeleton, as I'm more C guy than a C++

**Comment by dnpwwo** [comment]
I'm curious, what functionality would you want the native implementation to have that the plugin can not have?

The C++ codebase is already huge so unless you need the hardware to do something additional there seems little point in making it bigger to add yet another device.

**Comment by pipiche38** [comment]
For me it is not about adding specific functionality. It is much more to 
make it upstream. and as it is to manage a pure HW community like 
Open-Z-Wave I was thinking that it could make sense.

May be I'm wrong
