### ISSUE TITLE
Lightswitches not shown in dashboard except in mobile mode.

### ISSUE THREAD

**Issue by simon5738** [domoticz/domoticz#2568]
Lights in dashboard are only visible in mobile mode. When settings are changed to normal or compact the switches disappear. They come back after changing the setting back to mobile mode .

Chome 67.0.3396.99 (Officiële build) (64-bits)
Domoticz: (running on a raspberry pi 3)
Version: 4.9727
Build Hash: 70f8afaa
Compile Date: 2018-06-28 08:27:34 (I ran updatebeta today.)
dzVents Version: 2.4.6
Python Version: None

This is the setting I have to change.
![image](https://user-images.githubusercontent.com/35577826/42779688-6f57e648-8941-11e8-9815-b8a60080a44f.png)

Available switches in 'mobile' mode:
![image](https://user-images.githubusercontent.com/35577826/42779707-7eb75f60-8941-11e8-8886-630094a5bf21.png)

And put back to 'normal': 
![image](https://user-images.githubusercontent.com/35577826/42779726-8b40f7f0-8941-11e8-8f58-3b7c8aad0264.png)

This tab is not effected by the settings so no switches in this tab:
![image](https://user-images.githubusercontent.com/35577826/42779981-4d3193d8-8942-11e8-8022-8138a5614442.png)

**Comment by gizmocuz** [comment]
Try to Clearing your browser cache AND appcache first
Try a private browser
Try to user our forum

**Comment by simon5738** [comment]
Thanks for you reply.
Clearing cache and appcache did not work. Even so did the private browser. 

For further reference. I found this later and it solved the problem:

[https://github.com/domoticz/domoticz/issues/2282#issuecomment-378952139](url)

> Please delete file www/js/domoticz.js.gz in Domoticz installation directory if present
Note: Do NOT delete www/js/domoticz.js
If present, clear the browser cache + appcache again
