### ISSUE TITLE
Domoticz can't handle multiple Z-Wave controllers (Aeotec Z-Stick GEN5)

### ISSUE THREAD

**Issue by jonferreira** [domoticz/domoticz#2572]
Current Setup:

Aeotec Z-Stick A on /dev/ttyACM0
Aeotec Z-Stick B on /dev/ttyACM1 (using ser2net (remote) and socat (locally))

Stick A has been up and running for a couple of years and stick B was added today. As soon as it's enabled domoticz goes crazy starting with Z-Wave devices being impossible to control (although I still receive status updates).

Upon further look I can see that Stick A devices were added in ZWaveNodes table to Stick B. Here's an example:

![image](https://user-images.githubusercontent.com/7714292/42827539-886d4cd4-89de-11e8-9e0a-69536cbd4abb.png)

**HardwareID** 17 -> Stick B
**HomeID** 4164314680-> Stick A
**HardwareID** 14 -> Stick A
**HomeID** 3834619487 -> Stick A

Also worth mentioning that the OZW Panel is all messed  up too and doesn't seem able to distinct Stick A from B which makes me wondering if it's OZW related?

**Comment by jonferreira** [comment]
Am I the only one trying to run a single domoticz instance with two (or more!) Z-Wave Sticks?

@gizmocuz you who knows all things is this by design or an OZW limitation?

**Comment by travellingkiwi** [comment]
I used to run with a RaZBerry and an Aeotec. the RazBerry was master, the Aeotec a secondary controller. The two sticks were controlled by different instances of domoticz running on separate hardware. Apart from the usual connectivity issues and stuff, the wave was (reasonably) ok… Certainly I had no more problems with Domoticz talking to the Wave than anyone else… 

Note that I did have issues with several things, so I’ve returned to openhab… I dream of one day seeing a stable and useful home control implementation that isn’t bloated, slow, unreliable, but have yet to find one. OpenHab is certainly none of those things, but then neither is Domoticz. Both are built to keep windows people happy. Monolithic, large, slow etc.
But I digress...


H

**Comment by jonferreira** [comment]
thanks for your input @travellingkiwi 

for what is worth I'm running domoticz **betas** for a couple of years and I'm quit happy with it. Other than this **one** bug (remember I'm on beta!) a month or so ago the system has been rock solid, much **much** better than my times with Vera

anyway I'm quite curious to find out if I'm being stupid or what, really can't get 2 sticks to run on the same domoticz instance

**Comment by gizmocuz** [comment]
The ozw library is for a single zwave controller

**Comment by gizmocuz** [comment]
Besides you don't want two controllers.. of you do.. then two instances of domoticz is the option

**Comment by jonferreira** [comment]
ah bugger didn't knew about that limitation! that's a shame!

suppose that explain why there's no "Open Z-wave over ethernet" hardware like we have with the RFXtrx..

Yes, I need 2 controllers due to range, I could get one as Secondary but that's messy, would have much preferred 2 primaries, i.e. 2 independent Z-Wave networks (similar to how HS can handle multiple Z-Nets)

Guess I'll have to work with second domoticz server and share its devices then, thanks @gizmocuz 

PS: I just noticed that when you set up a "Slave" instance the "Main" instance can import its devices but it's missing names - is that by design?

**Comment by Risca** [comment]
@gizmocuz, the [OpenZWave documentation](http://www.openzwave.com/dev/) says
> [OpenZWave](http://www.openzwave.com/dev/namespaceOpenZWave.html) supports multiple controllers[...]

I don't know if that applies to primary/secondary controllers in the same zwave network or if the library can manage multiple controllers (separate networks) on the same physical machine.

My use case is:
* zwave.me Razberry - zwave+ devices
* zwave.me UZB - zwave (not plus) devices.

I got some devices that I can't find ZWave+ versions of, and I don't want to downgrade my whole network just for these devices. 

Where is the limitation? OpenZWave support? Domotics support? Both?

**Comment by jonferreira** [comment]
Honestly, to me it feels like a Domoticz limitation, probably no one ever thought of using 2 Z-Wave interfaces with Domoticz...

**Comment by Risca** [comment]
It was the first thing I thought of when I learned that zwave+ networks will "degrade" to zwave networks if 1 single device is zwave type

**Comment by jonferreira** [comment]
yeah me too seems it's not supported so I had to deploy another PI

**Comment by Risca** [comment]
Well, it looks like it's kinda supported but broken. I see that 2 different openzwave configs are created (one for each controller) and domoticz doesn't complain about dual controllers. However, when I added the second controller, it got all the devices from the first controller, and the first controller lost all devices :\

**Comment by jonferreira** [comment]
closed without an answer, cool....

**Comment by gizmocuz** [comment]
@jonferreira , i think i answered this on 26 july

**Comment by jonferreira** [comment]
@gizmocuz I think @Risca did raised some valid questions though

**Comment by gizmocuz** [comment]
@jonferreira , good thinking... still answered on the 26th of July

**Comment by Risca** [comment]
So, if I understand you correctly, the answer is to use 2 instances of Domoticz to solve this issue?

**Comment by gizmocuz** [comment]
@Risca , I'm not sure if that would work either, but two different machines work

**Comment by Risca** [comment]
That's how I have it setup right now. Would be nice to only require one machine, though

**Comment by dnpwwo** [comment]
Definitely not a ZWave problem overall, I have an early dev Python plug-in talking to a second stick and it does not “see” the devices from the first one.

Must be the way OZW is set up in Domoticz
