### ISSUE TITLE
Please add support for Xiaomi Aqara Air Conditioning Companion in XiaomiGateway

### ISSUE THREAD

**Issue by costeab** [domoticz/domoticz#2573]
Hello,
Can you add support for the Xiaomi Aqara Air Conditioning Companion?
Is an Air Con controller using IR led and at the same time is an aqara gateway device .
Currently the plugin reports this: XiaomiGateway: unhandled model: acpartner.v3

More info on the device: https://files.xiaomi-mi.com/files/aqara/aqara-rozetka-EN.pdf
Regards,
Bogdan

**Comment by kovainfo** [comment]
https://github.com/domoticz/domoticz/pull/2912

**Comment by waltervl** [comment]
Implemented, can be closed
