### ISSUE TITLE
add "daphile" as a supported Logitech Media player model type

### ISSUE THREAD

**Issue by aginies** [domoticz/domoticz#2574]
Currently daphile is no a supported type of Logitech Media player.
It should be added to the list of supporte Media type in LogitechMediaServer.cpp file.

**Comment by marek2k** [comment]
Same problem here

`Error: Logitech Media Server: model 'daphile' not supported.`

**Comment by gizmocuz** [comment]
Added, hope it works (beta 10531+)
https://github.com/domoticz/domoticz/commit/4e23c377c564668abf439d16c766352ba44b8751

**Comment by waltervl** [comment]
Implemented, can be closed.
