### ISSUE TITLE
Seems that Build is broken with gcc 8.1.1 on Fedora

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2576]
When building domoticz, I got a compilation error 

See here after a recommendation I found

https://stackoverflow.com/questions/20759750/resolving-redefinition-of-timespec-in-time-h

```

make
[  1%] Built target minizip
[  8%] Built target mqtt
[  9%] Built target sqlite
[ 20%] Built target lua
-- Found Git: /usr/bin/git (found version "2.17.1")
-- domoticz has been modified locally: adding "-modified" to hash
[ 20%] Built target revisiontag
[ 21%] Built target domoticz_gch
[ 22%] Building CXX object CMakeFiles/domoticz.dir/main/Camera.cpp.o
In file included from /usr/include/sys/stat.h:30,
                 from /usr/local/include/boost/asio/detail/impl/eventfd_select_interrupter.ipp:23,
                 from /usr/local/include/boost/asio/detail/eventfd_select_interrupter.hpp:80,
                 from /usr/local/include/boost/asio/detail/select_interrupter.hpp:25,
                 from /usr/local/include/boost/asio/detail/epoll_reactor.hpp:28,
                 from /usr/local/include/boost/asio/detail/reactor.hpp:21,
                 from /usr/local/include/boost/asio/detail/impl/scheduler.ipp:23,
                 from /usr/local/include/boost/asio/detail/scheduler.hpp:212,
                 from /usr/local/include/boost/asio/system_context.hpp:19,
                 from /usr/local/include/boost/asio/impl/system_executor.hpp:22,
                 from /usr/local/include/boost/asio/system_executor.hpp:129,
                 from /usr/local/include/boost/asio/associated_executor.hpp:21,
                 from /usr/local/include/boost/asio.hpp:21,
                 from /usr/share/domoticz/beta-domoticz/main/../tcpserver/TCPClient.h:4,
                 from /usr/share/domoticz/beta-domoticz/main/../tcpserver/TCPServer.h:4,
                 from /usr/share/domoticz/beta-domoticz/main/mainworker.h:10,
                 from /usr/share/domoticz/beta-domoticz/main/Camera.cpp:7:
/usr/include/bits/types/struct_timespec.h:9:8: error: redefinition of ‘struct timespec’
 struct timespec
        ^~~~~~~~
In file included from /usr/include/sched.h:32,
                 from /usr/include/pthread.h:23,
                 from /usr/include/c++/8/armv7hl-redhat-linux-gnueabi/bits/gthr-default.h:35,
                 from /usr/include/c++/8/armv7hl-redhat-linux-gnueabi/bits/gthr.h:148,
                 from /usr/include/c++/8/ext/atomicity.h:35,
                 from /usr/include/c++/8/bits/basic_string.h:39,
                 from /usr/include/c++/8/string:52,
                 from /usr/share/domoticz/beta-domoticz/main/stdafx.h:17:
/usr/include/bits/types/struct_timespec.h:8:8: note: previous definition of ‘struct timespec’
    has nanoseconds instead of microseconds.  */
        ^~~~~~~~
make[2]: *** [CMakeFiles/domoticz.dir/build.make:89: CMakeFiles/domoticz.dir/main/Camera.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/domoticz.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by pipiche38** [comment]
Adding -DHAVE_STRUCT_TIMESPEC in CMakelist.txt makes it working

```

  IF(CMAKE_COMPILER_IS_GNUCXX)
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -DHAVE_STRUCT_TIMESPEC")
    #SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-switch")
    #ADD_DEFINITIONS( -Wall -O0 -ggdb )
    #ADD_DEFINITIONS( -Wfatal-errors -Wformat=2 -Werror=format-security )

```

**Comment by svde** [comment]
It builds on FC28 and rawhide, see: https://build.opensuse.org/package/show/home:stefan_van_der_eijk/domoticz

**Comment by pipiche38** [comment]
And what gcc/c++ version ?

Envoyé de mon iPhone

**Comment by svde** [comment]
8.1.1
https://build.opensuse.org/public/build/home:stefan_van_der_eijk/Fedora_Rawhide/x86_64/domoticz/_log

**Comment by pipiche38** [comment]
Fine ! 
do you mean that the problem I'm reporting is not true ? and the PR that I have provided doesn't make sense ?

My point was to contribute, what I saw in the past is Arm is ahead of x86

Here are the Fedora update which created the issue : 
Upgraded:
  crda.armv7hl 3.18_2018.05.31-2.fc28
  curl.armv7hl 7.59.0-5.fc28
  e2fsprogs.armv7hl 1.44.2-0.fc28
  e2fsprogs-libs.armv7hl 1.44.2-0.fc28
  glibc.armv7hl 2.27-30.fc28
  glibc-common.armv7hl 2.27-30.fc28
  glibc-devel.armv7hl 2.27-30.fc28
  glibc-headers.armv7hl 2.27-30.fc28
  glibc-langpack-en.armv7hl 2.27-30.fc28
  kernel-headers.armv7hl 4.17.6-200.fc28
  libcom_err.armv7hl 1.44.2-0.fc28
  libcom_err-devel.armv7hl 1.44.2-0.fc28
  libcurl.armv7hl 7.59.0-5.fc28
  libcurl-devel.armv7hl 7.59.0-5.fc28
  libss.armv7hl 1.44.2-0.fc28 
  libxcrypt.armv7hl 4.1.0-1.fc28
  libxcrypt-devel.armv7hl 4.1.0-1.fc28

**Comment by svde** [comment]
No need to get upset, we're on the same team.

I've changed the config for FC28 on OBS so it first looks in the updates before the original packages (this was the other way round, hence it wasn't using gcc-8.1.1). The build is running now, and has passed the 23% mark (where the error you're reporting took place).

PS: you're free to use my domoticz package, just add this repo: http://download.opensuse.org/repositories/home:/stefan_van_der_eijk/Fedora_28/home:stefan_van_der_eijk.repo

**Comment by pipiche38** [comment]
As mentioned, I have reported the problem on RPI3B+ / Arm … Your package is only on x86

**Comment by pipiche38** [comment]
Fedora Update Notification
FEDORA-2018-85c0ff9183
2018-07-17 15:16:45.224417

Fedora 28 Update: glibc-2.27-30.fc28
- Use _STRUCT_TIMESPEC as guard in <bits/types/struct_timespec.h> (swbz#23349)


https://sourceware.org/bugzilla/show_bug.cgi?id=23349

**Comment by svde** [comment]
Building for aarch64 now:
https://build.opensuse.org/package/live_build_log/home:stefan_van_der_eijk/domoticz/Fedora_28/aarch64

**Comment by Cardy165** [comment]
The main fedora repo's now have v4.7900
[https://apps.fedoraproject.org/packages/domoticz/overview/](https://apps.fedoraproject.org/packages/domoticz/overview/)

I requested them built and they have now been released.

Clicking on domoticz-4.9700-1.fc28 seems to show most architectures are available.

**Comment by pipiche38** [comment]
@Cardy165 that is good as the current one is quiet out-dated. But as reported 4.9700 (as well as Beta) are facing the issue with glibc-2.27-30.fc28

**Comment by gizmocuz** [comment]
Closing issue, feel free to re-open if needed
