### ISSUE TITLE
div id="dialog-replacedevice" display when basic-auth

### ISSUE THREAD

**Issue by landaisbenj** [domoticz/domoticz#2578]
https://github.com/domoticz/domoticz/blob/41a2a5311da23eed7848a0a35c034a007e572d39/www/index.html#L1419

`style="display: none;"` isn't apply in this div. So it's appear when log with basic-auth.

I don't know if it's an issue...

**Comment by gizmocuz** [comment]
Forgot to mention the commit... all is correct now ?

**Comment by landaisbenj** [comment]
I'm not on beta. But I follow code, and you add the same code as all other div... I think it's good..
