### ISSUE TITLE
Revision on cmake is dependings of git. 

### ISSUE THREAD

**Issue by xbeaudouin** [domoticz/domoticz#258]
Hello,

I am trying to make a FreeBSD port of domoticz. I use the freebsd port framework that can download a specific tag / version from github

Unfortunatly the tar.gz from github doesn't have .git directory that makes the CMake macro fails like this :

-- Found OpenSSL: /usr/lib/libssl.so;/usr/lib/libcrypto.so (found version "1.0.1p") 
fatal: Not a git repository (or any parent up to mount point /usr)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at CMakeLists.txt:145 (MATH):
  math cannot parse the expression: "+2107": syntax error, unexpected
  exp_PLUS, expecting exp_OPENPARENT or exp_NUMBER (1)

-- Compiling Revision #
-- Boost version: 1.55.0

I have 2 way to fix this :

1- Haxor the CM around lines 135 to 150.
2- Make a quick and dirty tarball from the github and push it into a server somewhere.

The second way is... "usable" but still very dirty.

Is there any good way to fix this ?

Kind regards,
Xavier

**Comment by dwmw2** [comment]
FWIW in the OpenWRT port (https://github.com/openwrt/packages/pull/2007) I used option 1. Although I wasn't stunningly happy about it. I'd just had enough of CMake hacking that week.

In the OpenConnect VPN client I have a trick which generates the revision from git only when building from git. Proper releases have a pregenerated version.h already present in the tarball, generated by the `make dist` step. There's a makefile rule which updates `version.c` **if** any of the other files have changed. And which will make it `-unknown` if it can't find a git repository. See http://git.infradead.org/users/dwmw2/openconnect.git/blob/v7.06:/version.sh and http://git.infradead.org/users/dwmw2/openconnect.git/blob/v7.06:/Makefile.am#l115

Not sure how useful that is for Domoticz which doesn't seem to have the same focus on tarball releases, but you're welcome to lift anything from that if you find it useful. Just having the same _"rebuild appversion.h only if other files have changed"_ logic would at least allow people building from tarballs to drop an appversion.h into place without having to hack the makefiles, as a first step.

**Comment by xbeaudouin** [comment]
So this is really a shame (have same issue with Open-Zwave lib as well).
As discussed with a FreeBSD commiter, dependcy of git "live" access is clairely _forbidden_ during the package building.
So I will make a dirty patch that change CMakeLists.txt and getgit.cmake.

Please developpers make a clean build of your releases.

**Comment by gizmocuz** [comment]
Please explain a bit more in detail...
the version #,build hash is taken from git, and should be like it!

**Comment by xbeaudouin** [comment]
Not possible because the FreeBSD port is base on this scenario (that CANNOT BE CHANGED) when using github : 
[kiwi@portsbuild ~/tmp]$ fetch https://github.com/domoticz/domoticz/archive/master.zip
fetch: https://github.com/domoticz/domoticz/archive/master.zip: size of remote file is not known
master.zip                                              36 MB 1512 kBps 00m25s
[kiwi@portsbuild ~/tmp]$ unzip master.zip 
(...)
[kiwi@portsbuild ~/tmp]$ cd domoticz-master/
[kiwi@portsbuild ~/tmp/domoticz-master]$ cmake -DCMAKE_BUILD_TYPE=Release 
[kiwi@portsbuild ~/tmp/domoticz-master]$ cmake -DCMAKE_BUILD_TYPE=Release 
-- The C compiler identification is Clang 3.4.1
-- The CXX compiler identification is Clang 3.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib/libssl.so;/usr/lib/libcrypto.so (found version "1.0.1p") 
fatal: Not a git repository (or any parent up to mount point /usr)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at CMakeLists.txt:145 (MATH):
  math cannot parse the expression: "+2107": syntax error, unexpected
  exp_PLUS, expecting exp_OPENPARENT or exp_NUMBER (1)

-- Compiling Revision #
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
-- Linking against boost static libraries
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.8") 
-- ZLIB libraries found at: /usr/lib/libz.so
-- ZLIB includes found at: /usr/include
-- Found CURL: /usr/local/lib/libcurl.so (found version "7.44.0") 
-- Curl libraries found at: /usr/local/lib/libcurl.so
-- Curl includes found at: /usr/local/include
-- Found LIBUSB: /usr/lib/libusb.so  
-- LIBUSB found at: /usr/lib/libusb.so
-- ==== OpenZWave not found, support disabled!
-- Not building on Raspberry Pi. GPIO support disabled.
-- Not found telldus-core (telldus-core.h), not adding tellstick support
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Configuring incomplete, errors occurred!
See also "/home/kiwi/tmp/domoticz-master/CMakeFiles/CMakeOutput.log".
See also "/home/kiwi/tmp/domoticz-master/CMakeFiles/CMakeError.log".

As you see the .zip (or .tar.gz) given by the button "Download ZIP" doesn't include the directory .git, so the revision number using git.... it NOT possible at all.

All your releases have this issue so "the version #,build hash is taken from git, and should be like it!" doesn't works at all.

**Comment by gizmocuz** [comment]
okey, what do you propose ?

**Comment by dwmw2** [comment]
If you were actually making releases, I'd suggest that the `make dist` or whatever you do to make the tarball should create an `appversion.h` file and then the build system would only rebuild that file if any of the other files are modified. And fall back to `v3.xxxx-unknown` if it's not actually in git. I already linked to examples of scripting that can do that.

But since you aren't actually making releases, that's not so simple. Perhaps just add the `make dist` target in git anyway, so that people who _do_ need to package it and build that way can do it anyway?

**Comment by gizmocuz** [comment]
why do you think we are not making releases ?
We have stable's and beta's

And yes, maybe i am not that good with cmake build scripts and platforms etc...
so if you could assist in any way, that will be appreciated of course, just dont expect that i know 'all' and blame me for this problem plz !

**Comment by dwmw2** [comment]
Are you making tarballs, or just tagging in git and calling that a release?

**Comment by dwmw2** [comment]
I'm certainly not criticising for not making tarballs; just offering up the solution I came up with for my own purposes elsewhere, and noting that your use case is slightly different...

**Comment by gizmocuz** [comment]
we making tarbals, have a look at sourceforge, or here:

www.domoticz.com/releases/

currently here only beta's as this upload folder is quite new

did you had a look at the 2 scripts provided with the source ? makebeta and makerelease ?

there is also an version file created

you could also have seen that the every commit goes trough appveyor and travis

cmake can also make packages, but as i said, i'm not a cmake genious

**Comment by xbeaudouin** [comment]
Hi,

Looking at files provided : 
- on SF (link on the domoticz page "take the source" point to github), have to find it and have a look. I can find only windows binaries and raspberry pi images. Not Sources.
- on domoticz releases, there is only binaries, FreeBSD needs the sources not the linux binary as well.

FreeBSD ports are really strict, we have to get the official tarballs OR using a tag / version from github (we needs reproductable builds !) and don't rely on third party tarballs (you know security / MiM issues).

I don't critize the fact you work on github and use a SCM as versioning, but maybe make bumpversion should be a good idea ?

How did I get into this ? See https://www.domoticz.com/wiki/FreeNAS, since FreeNAS is FreeBSD based, a FreeBSD port should be a good idea to spread the world.

Anyway I did an internal way of handling that, with dirty patches on the CMakeFiles as most porters do with projects that rely too much on the SCM used as versioning.

I wanted to inform you that the tarball/zip given on the release tab are not usuable as is.

**Comment by gizmocuz** [comment]
you reply on our github page, so you know where the sources are

So when we tag a new release, you can work with it ? (the source is in the tar.gz in the releases page)

bumversion i would like to try to avoid.... this is how we used to work....

maybe it would be nice if FreeBSD can work with SCM ?

**Comment by xbeaudouin** [comment]
Freebsd work with tgz/.zip from github. 
The portbuilding is done _without_ network.
The Releases that are on github have the issue there. Did you rollup a new release ?

**Comment by gizmocuz** [comment]
"Did you rollup a new release" no not yet
Okey, so i need to find a way, that when tagging a new release we create the version file, and put that in the archive, so the cmake can check for git, if not found, it uses the local version file
Some kind of hook

**Comment by bapt** [comment]
Usually what is done is the following:
- Always have a version in the sources.
- Test the git utility is present and if a .git directory is present:
  - if no: stick with the version in the sources
  - if yes: append to the version the hash of the sources obtained via git rev-parse --short HEAD

This allows releases via tag: if one grabs the tag tarball then it has the plain default version (X.Y.Z)
This allows you to keep the information in the version string for people fetching and building from git (X.Y.Z-hash).
You can also add an extra test if .git is present: git diff-index -m --name-only HEAD
if the result of the above command is not empty, it means that the user has modified the sources and is not strictly using the git version. You can then append a -dirty/-modified to the version:
X.Y.Z-hash-modified.

You already do something very close, so might not be complicated :)

The reason why FreeBSD does not want to use scm when fetching is because we want to ensure the sources used to build a package are actually the sources that have been tested. The way to ensure that is via checksums of the distfiles. 
Fetching sources from github generated archives (based on tags and/or commit hash) is correctly fit with that requirement.
