### ISSUE TITLE
Domoticz overrides current working directory breaking dzVents

### ISSUE THREAD

**Issue by Cardy165** [domoticz/domoticz#2580]
I have come across this issue with domoticz 4.7900

I am using Fedora 28 and the following package on x86_64:
[https://koji.fedoraproject.org/koji/buildinfo?buildID=1104258](https://koji.fedoraproject.org/koji/buildinfo?buildID=1104258)

When I try to use LUA the code was always failing to run after a lot of debugging I traced the issue to what seems to be this error. 

`Error: EventSystem: in /usr/bin/dzVents/runtime/dzVents.lua: cannot open /usr/bin/dzVents/runtime/dzVents.lua: No such file or directory`

At first I thought it was a problem with systemd not setting the correct WorkingDirectory but after changing the binary to a simple bash script this confirmed that the Current Working Directory was being set to /usr/share/domoticz       (this is where domoticz is installed).

The section from the systemd service file also has the correct settings
```
EnvironmentFile=/etc/sysconfig/domoticz
# Give the right to open priviliged ports. This allows you to run on a port <1024 without root permissions (user/group setting above)
#CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/domoticz -www $WWW_PORT -sslwww $SSL_PORT -sslcert $SSLCERT -sslpass $SSLPASS -sslmethod $SSLMETHOD -ssloptions $SSLOPTIONS -ssldhparam $SSLDHPARAM -wwwroot $WWW_ROOT -dbase $DBASE -userdata $USERDATA -verbose $VERBOSE -log $LOG -loglevel $LOGLEVEL -debuglevel normal,eventsystem,python
WorkingDirectory=/usr/share/domoticz
```

The problem seems that because domoticz is called as /usr/bin/domoticz it ignores the current working directory and sets /usr/bin as the CWD.

I am not a C developer and whilst I have looked through the code above I don't know whats causing this behaviour. I didn't have of these issues with the last stable release and am wondering if something has changed.

I requested the build of the new version from the fedora developers. I plan to update the ticket with the resolution to this issue once I can figure what the problem is so any help is greatly appreciated.

**Comment by Cardy165** [comment]
I have also tried switching to the user domoticz and running from the command line

```
[domoticz@domoticz ~]$ cd /usr/share/domoticz/
[domoticz@domoticz ~]$ pwd
/usr/share/domoticz
[domoticz@domoticz ~]$ domoticz -www 8080 -sslwww 8443 -sslcert /var/lib/domoticz/domoticz.pem -sslpass -sslmethod -ssloptions -ssldhparam -wwwroot /usr/share/domoticz/www -dbase /var/lib/domoticz/domoticz.db -userdata /usr/share/domoticz/ -verbose 1 -log /var/log/domoticz.log -loglevel normal,status,error,debug
```

Using /usr/bin/domoticz or just domoticz as the binary is in the path seems to make no difference.

`2018-07-20 17:38:37.511  Error: EventSystem: in /usr/bin/dzVents/runtime/dzVents.lua: cannot open /usr/bin/dzVents/runtime/dzVents.lua: No such file or directory`

**Comment by jvandenbroek** [comment]
You should specify -approot /usr/share/domoticz

**Comment by svde** [comment]
There are some more issues with the fedora package. I've decided to roll my own based on their package. See: https://build.opensuse.org/package/show/home:stefan_van_der_eijk/domoticz

**Comment by gizmocuz** [comment]
Can this issue be closed ?

**Comment by svde** [comment]
I wouldn't close it. Similar issue open on redhat bugzilla, on the domoticz package in Fedora.

See: https://bugzilla.redhat.com/show_bug.cgi?id=1759558

**Comment by svde** [comment]
> You should specify -approot /usr/share/domoticz

It then still can't find JSON.lua, see: https://bugzilla.redhat.com/show_bug.cgi?id=1759558

**Comment by gizmocuz** [comment]
How about when you install Domoticz in your home folder or in /opt ?

**Comment by svde** [comment]
On my "production" system I run a [modified](https://build.opensuse.org/package/show/home:stefan_van_der_eijk/domoticz) version of Fedora's package, the scripts operate out of /usr/share/domoticz/, and it works.

I've setup a test system to troubleshoot the Fedora package. Most of domoticz is also installed in /usr/share/domoticz/, but the Fedora packager tried to move some of the scripts to /var/lib/domoticz/ and this doesn't work.

Note: I've only been testing dzVents scripts, so maybe Danny should be involved. What the Fedora packager is trying to accomplish is to move the user writeable directories to /var/lib/domoticz, and leave the "fixed" stuff in /usr/share/domoticz/

**Comment by gizmocuz** [comment]
@svde , that is not what i asked.
Could you install domoticz in your home folder or in the /opt folder ?
And do not make use of /var/lib /usr/share /... at all  ?

**Comment by svde** [comment]
I guess I could do that. Before I start, what are we going to prove with it?

anyway... on my test system (fc32), trying to install using scripts/install.sh, and it breaks because it needs libcurl4.
domoticz_DEPS=( curl libcurl4 unzip wget findutils cronie sudo domoticz_DEP)

That package doesn't exist anymore:
$ rpm -qa | sort | grep curl
curl-7.69.1-1.fc32.x86_64
libcurl-7.69.1-1.fc32.x86_64
libcurl-devel-7.69.1-1.fc32.x86_64

**Comment by gizmocuz** [comment]
then try to build it by hand following this tutorial:

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by svde** [comment]
Trying.. but the builds are failing (internal compiler error: Segmentation fault) on my (very old) test system.

**Comment by xvello** [comment]
Hello folks,

I have been hit with the same issue while trying to use domoticz in nixos, with a `szUserDataFolder` path different from `szStartupFolder`. The result of my investigation is that [the code populating `package.path`](https://github.com/domoticz/domoticz/blob/2e2691522939b4642f28568f67ef52d20eb1e543/dzVents/runtime/dzVents.lua#L17-L29) does assume both paths are equal:

JSON.lua,  XmlParser.lua and xml2lua.lua being available to dzEvents only relies on the [`scriptPath .. '../lua/?.lua;' ..`](https://github.com/domoticz/domoticz/blob/2e2691522939b4642f28568f67ef52d20eb1e543/dzVents/runtime/dzVents.lua#L23) line, which resolves to `${szUserDataFolder}/scripts/lua/?.lua`.

As these files are shipped in the package and not maintained by the user ; they should be specified from `szStartupFolder`, not `szUserDataFolder`. An easy user-side workaround for it is to just copy the JSON.lua file from the package to user data, but I see three ways to fix this for all new users:

1. **Easiest**: add `runtimePath .. '../../scripts/lua/?.lua;'` to `package.path`. To account for a user having their own modified `${szUserDataFolder}/scripts/lua/JSON.lua` file, should this new path go at the end of the list?
2. **Cleaner**: edit `main/dzVents.cpp` to export a new `lua_libs_path` global  set to `${szStartupFolder}/scripts/lua`, and use that path in the `package.path` builder
3. **Cleanest**: as these three lua files are dependencies of `dzEvents/runtime/Utils.lua`, I feel like they should be moved into `dzEvents/runtime/` too, either at this level or into a `libs/` subfolder. I'm not sure of all the implications of this change though.


@gizmocuz would you have a preferred approach to solving this? I can prepare a PR to implement either one.

**Comment by rwaaren** [comment]
> 3. **Cleanest**: as these three lua files are dependencies of `dzVents/runtime/Utils.lua`, I feel like they should be moved into `dzVents/runtime/` too, either at this level or into a `libs/` subfolder. I'm not sure of all the implications of this change though.

This might be the cleanest way for dzVents but classic Lua should also be able to use them without accessing a specific dzVents folder

Please contact me on the forum via PM (waaren) and explain >1 and 2> so we can decide what would be the best way forward.

**Comment by svde** [comment]
Did you take a look at how Fedora solved this in their package?
https://src.fedoraproject.org/rpms/domoticz/blame/domoticz.spec?identifier=master

**Comment by rwaaren** [comment]
> Did you take a look at how Fedora solved this in their package?
> https://src.fedoraproject.org/rpms/domoticz/blame/domoticz.spec?identifier=master

Thx for the link. I did not see this before.
I doubt if using ln is is the best way of dealing with this issue. It is now already missing a link to the XML parsers so some of the dzVents methods will fail. My preference is to use an approach that works for most if not all Linux / Windows type of operating systems without the need to maintain it at another place then domoticz / dzVents itself.

**Comment by waltervl** [comment]
Closing this as no further development is expected. Also seems to be further packages created for fedora: https://koji.fedoraproject.org/koji/packageinfo?packageID=24401
