### ISSUE TITLE
Cannot remove text from device "On action" or "Off action"

### ISSUE THREAD

**Issue by Jjesper** [domoticz/domoticz#2581]
Version: 4.9700 (and updated to Beta 4.9788 to see if issue remained, it did).
Platform: Debian 9.5 amd64
Plugin/Hardware: ALL
Description:

When filling in an alternative "On action" (http(s):// or script://) for a device, as for Off action, I was not able to remove it afterwards cq "clear the value".

It gave the error that the field can not be empty.
It was not like this in the previous stable version.

I edited my database to work around it, cleared the column StrParam1 / 2 in table DeviceStatus.

**Comment by sweetpants** [comment]
Tested this on v4.9796 and works fine here

**Comment by Jjesper** [comment]
I’ll check this later if it has been resolved after updating. 

Addition: issue in OP only seems to be regarding switches, not for scenes or groups, at least that was what I found out.
