### ISSUE TITLE
Dummy device via MQTT not instantly updated on floorplan

### ISSUE THREAD

**Issue by Jjesper** [domoticz/domoticz#2582]
Version: 4.9700 (and updated to Beta 4.9788)
Platform: Debian 9.5 amd64
Plugin/Hardware: Dummy
Description:

I have a Dummy switch, which is updated by MQTT.
It turns off and on perfectly, also reports nicely to Domoticz in device log and system log, but does not "auto-update" on the Floorplan, as Hue lights for example will do.

If I turn on the switch manually from the switch tab, same issue.
I have to manually refresh the page to get the switch to show it's current state, while Hue lamps "auto-update" without refreshing.

I'm also not sure if this is related to the new stable version. I updated to the beta channel, not solved.

**Comment by sweetpants** [comment]
Tested this with a dummy MQTT switch and works fine on V4.9796. There is a little (browser refresh) delay, but it automatically updates on my floorplan.
