### ISSUE TITLE
Onewire ds2408 not possible to control

### ISSUE THREAD

**Issue by pklarsjo** [domoticz/domoticz#2585]
I am using an emulated DS2408 device (onewirehub on attiny85) via OWFS. Directly in OWFS I can control outputs by echoing to PIO.x, but via domoticz nothing happens. I have done some debugging and found out that It quits directly in 1WireByOWFS/Setlightstate/Finddevice, but that is how far I have gotten. Domoticz sees the device and readback of changes performed via OWFS from prompt is reflected as status changes in Domoticz.

**Comment by szczukot** [comment]
Domoticz properly read data from DS2408, but don't write state to it ?

**Comment by pklarsjo** [comment]
Correct.

mån 10 sep. 2018 kl. 10:04 skrev Fantom <notifications@github.com>:

**Comment by szczukot** [comment]
What are You see in logs after send command to DS2408 ?

**Comment by tomaszszczukobls** [comment]
@pklarsjo ?

**Comment by waltervl** [comment]
Stale, can be closed
