### ISSUE TITLE
Domoticz crashes when WiFi lost on Raspberry Pi

### ISSUE THREAD

**Issue by askold2** [domoticz/domoticz#2588]
My domoticz (any version from 4.9700 and later) periodically crashes.
I don't see any diagnostics of problems in domoticz.log, but I see there is a time when it last worked. 

domoticz.log:
...
2018-07-22 22:41:00.260  Status: EventSystem: Script event triggered: timer
2018-07-22 22:41:00.434  (XGW) Light/Switch (Xiaomi Gateway Alarm Clock)
2018-07-22 22:42:00.277  Status: EventSystem: Script event triggered: timer

In the file syslog I see, at this time:

syslog:

Jul 22 22:41:01 raspberrypi dhcpcd[395]: wlan0: carrier lost
Jul 22 22:41:01 raspberrypi dhcpcd[395]: wlan0: deleting address fe80::158b:ecee:6bfe:da95
Jul 22 22:41:01 raspberrypi avahi-daemon[264]: Withdrawing address record for fe80::158b:ecee:6bfe:da95 on wlan0.
Jul 22 22:41:01 raspberrypi avahi-daemon[264]: Leaving mDNS multicast group on interface wlan0.IPv6 with address fe80::1
58b:ecee:6bfe:da95.
Jul 22 22:41:01 raspberrypi avahi-daemon[264]: Interface wlan0.IPv6 no longer relevant for mDNS.
Jul 22 22:41:01 raspberrypi dhcpcd[395]: wlan0: deleting default route via 192.168.100.1
Jul 22 22:41:01 raspberrypi dhcpcd[395]: wlan0: deleting route to 192.168.100.0/24
Jul 22 22:41:01 raspberrypi avahi-daemon[264]: Withdrawing address record for 192.168.100.200 on wlan0.
Jul 22 22:41:01 raspberrypi avahi-daemon[264]: Leaving mDNS multicast group on interface wlan0.IPv4 with address 192.168
.100.200.
Jul 22 22:41:01 raspberrypi avahi-daemon[264]: Interface wlan0.IPv4 no longer relevant for mDNS.
Jul 22 23:05:25 raspberrypi dhcpcd[395]: wlan0: carrier acquired

**Comment by jvandenbroek** [comment]
While not a direct solution for your problem, you could try to set a static IP to the wifi adapter. Not sure if it will retain the address on connection loss, but I'd say give it a try.

**Comment by askold2** [comment]
I already have static IP. It does not help.

**Comment by emontnemery** [comment]
@askold2 Do you still see this issue with latest beta?

**Comment by askold2** [comment]
Sorry, I'm not home right now. I can check it only in a month.

**Comment by askold2** [comment]
@emontnemery Checked. Alas, nothing has changed.

**Comment by emontnemery** [comment]
@askold2 OK, too bad. Can you please attach /home/pi/domoticz/domoticz_crash.log here?

**Comment by askold2** [comment]
[domoticz_crash.log](https://github.com/domoticz/domoticz/files/2377487/domoticz_crash.log)

**Comment by waltervl** [comment]
Stale, can be closed.
