### ISSUE TITLE
idx is a string for scenes sent over MQTT

### ISSUE THREAD

**Issue by karl-gustav** [domoticz/domoticz#2590]
After the latest update* scenes sent over MQTT looks like this

    {
        "LastUpdate" : "2018-07-19 18:32:05",
        "Name" : "111",
        "Status" : "On",
        "Timers" : "false",
        "Type" : "Scene",
        "idx" : "27"
    }

notice that `idx` is a `string`, it used to be a `int`, and it still is a `int` for other events sent over MQTT.

\*  V4.9700, Build Hash: a3a45906, Build Date: 2018-06-23 16:24:51

**Comment by sweetpants** [comment]
Created PR #2593 to change to integer

**Comment by sweetpants** [comment]
Fixed as off V4.9796

{
   "LastUpdate" : "2018-07-26 19:29:32",
   "Name" : "Gr_1",
   "Status" : "Off",
   "Timers" : "false",
   "Type" : "Group",
   "idx" : 1
}

**Comment by emontnemery** [comment]
@karl-gustav, @gizmocuz Can this be closed since #2593 was merged?

**Comment by gizmocuz** [comment]
Yep
