### ISSUE TITLE
Missing Z-Wave devices, but available in OZW CP

### ISSUE THREAD

**Issue by cincuranet** [domoticz/domoticz#2591]
I have added Qubino 3-phase meter (`ZMNHXDx`) into Domoticz and although I can see "all" the data in OZW's Control Panel, some devices are not added in Domoticz.

OZW CP:
![ozw-cp](https://user-images.githubusercontent.com/4540597/43121152-14e3927a-8f1d-11e8-8879-d9585a183342.png)

Devices:
![devices](https://user-images.githubusercontent.com/4540597/43121162-1cb07eb4-8f1d-11e8-9937-12e8a7aeb00c.png)

The missing devices are for _kWh_ (surprisingly the _kVAh_ is there, but with wrong unit), _Exporting_ and (at least) the last _Unknown_ (which is _var_).

The definition in OZW is:
```xml
<CommandClass id="50" name="COMMAND_CLASS_METER" version="4" request_flags="3" innif="true">
    <Instance index="1" endpoint="1" />
    <Instance index="2" endpoint="2" />
    <Instance index="3" endpoint="3" />
    <Instance index="4" endpoint="4" />
    
    <Value type="decimal" genre="user" instance="1" index="0" label="Energy" units="kWh" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0" />
    <Value type="decimal" genre="user" instance="1" index="4" label="Energy" units="kVAh" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0" />
    <Value type="decimal" genre="user" instance="1" index="8" label="Power" units="W" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="2458.4" />
    <Value type="decimal" genre="user" instance="1" index="24" label="Power Factor" units="Power Factor" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.7671" />
    <Value type="decimal" genre="user" instance="1" index="28" label="Unknown" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="-140.0" />
    <Value type="bool" genre="user" instance="1" index="32" label="Exporting" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />
    <Value type="button" genre="system" instance="1" index="33" label="Reset" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0" />
    
    <Value type="decimal" genre="user" instance="2" index="0" label="Unknown" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0" />
    <Value type="decimal" genre="user" instance="2" index="8" label="Power" units="W" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="240.5" />
    <Value type="decimal" genre="user" instance="2" index="16" label="Voltage" units="V" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="242.7" />
    <Value type="decimal" genre="user" instance="2" index="20" label="Current" units="A" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.407" />
    <Value type="decimal" genre="user" instance="2" index="24" label="Power Factor" units="Power Factor" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.5604" />
    <Value type="bool" genre="user" instance="2" index="32" label="Exporting" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />
    <Value type="button" genre="system" instance="2" index="33" label="Reset" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0" />
    
    <Value type="decimal" genre="user" instance="3" index="0" label="Unknown" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0" />
    <Value type="decimal" genre="user" instance="3" index="8" label="Power" units="W" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="64.0" />
    <Value type="decimal" genre="user" instance="3" index="16" label="Voltage" units="V" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="239.8" />
    <Value type="decimal" genre="user" instance="3" index="20" label="Current" units="A" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.583" />
    <Value type="decimal" genre="user" instance="3" index="24" label="Power Factor" units="Power Factor" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.8819" />
    <Value type="bool" genre="user" instance="3" index="32" label="Exporting" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />
    <Value type="button" genre="system" instance="3" index="33" label="Reset" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0" />
    
    <Value type="decimal" genre="user" instance="4" index="0" label="Unknown" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0" />
    <Value type="decimal" genre="user" instance="4" index="8" label="Power" units="W" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="169.8" />
    <Value type="decimal" genre="user" instance="4" index="16" label="Voltage" units="V" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="241.7" />
    <Value type="decimal" genre="user" instance="4" index="20" label="Current" units="A" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.904" />
    <Value type="decimal" genre="user" instance="4" index="24" label="Power Factor" units="Power Factor" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.7814" />
    <Value type="bool" genre="user" instance="4" index="32" label="Exporting" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />
    <Value type="button" genre="system" instance="4" index="33" label="Reset" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0" />
</CommandClass>
```

Might be related to #803.

**Comment by gizmocuz** [comment]
It could be that there was no update received for the kWh sensor. Is "accept new hardware" still enabled in the settings ?

**Comment by cincuranet** [comment]
Yes it is. I have it permanently on.

**Comment by cincuranet** [comment]
Also, the device 353 on the image, which should be W on all 3 phases and total kWh (instance==1, index==0 in the XML defintion) is a wrong device type. I believe instead of `Usage, Electric` it should be `General, kWh`. Because with this device the kWh is lost. That's also how i.e. Fibaro plug power consumption device is recognized.

**Comment by cincuranet** [comment]
Looking at it once more, looks like the device 351 could be the kWh. But it's still wrong device.

**Comment by cincuranet** [comment]
I went downstairs to check the display on the meter and now with more distinct values, the device 351 on the images is `kVAh` for sure (yes, the device type is probably not right, but I think Domoticz does not have specific device for `kVAh`, `General, kWh` might be closest). 

Device 353 is `W`, as expected. Maybe the `kWh` value is lost because of wrong device type? Although usually there's one extra (i.e. with Fibaro devices) with `W`+`kWh` on Domoticz side (`General, kWh`).

The 352 is weird. Sometimes (as far as I can tell when the value is received from scheduled send from the meter) it shows the same value as 351 (hence `kVAh`) and sometimes (as far as I can tell when the value is received from "push" (on change) send from the meter) same value as 353.

The `var` is completely missing, I think.

**Comment by cincuranet** [comment]
Or not. 

The 351 device is mixing `kWh` and `kVAh`.
![img](https://user-images.githubusercontent.com/4540597/44664533-d2a61380-aa13-11e8-8608-f38ad24fc8a2.png)

And the 352 is mixing `current W`, `kVAh` and `kWh`.
![img](https://user-images.githubusercontent.com/4540597/44664596-fff2c180-aa13-11e8-9b5b-714187edc032.png)

Looks like something is not matching between values received from OZW and devices.

**Comment by prein2** [comment]
I have the same device, but don't see the 3-phase values in the OZW control panel. Did you compile another openZwave version yourself?

I see some endpoint mapping errors in the log. That seems logical, since not all endpoints get mapped.

![knipsel](https://user-images.githubusercontent.com/4078115/44812752-69233200-abd8-11e8-8df2-b624f23c2bac.JPG)

I'm on version 4.9960. Any clues?

**Comment by cincuranet** [comment]
I integrated it into OZW
(https://github.com/OpenZWave/open-zwave/pull/1557) and manually copied
the config files into Domoticz (4.9700). I suppose the new config files
will be in Domoticz with next stable version.

**Comment by gizmocuz** [comment]
If it is merged, it is probably already available in the beta version

**Comment by prein2** [comment]
Unfortunately not.. Running the latest beta, excluded and included the node, but still the same.

**Comment by cincuranet** [comment]
It is merged. But for production I, unless really really necessary, use
stable only.
But. Can I do something to pinpoint what's causing Domoticz to not
properly handle data from OZW into its own devices?

**Comment by prein2** [comment]
Running Beta 4.999 now, excluded and included Zwave device. Now it works:
![afbeelding](https://user-images.githubusercontent.com/4078115/45752544-1d333e00-bc16-11e8-9adf-d7c377fb1047.png)

**Comment by octavianrusu** [comment]
Unfortunately, I’m having the same issue, is there a solution for this? I really tried everything but no energy counter whatsoever. I tried on stable and unstable versions of Domoticz. Any help appreciated.

**Comment by ootjersb** [comment]
I am running the latest beta (4.10311) and I can see the correct values in OpenZWave control panel with the correct units, however the total kWh device seems to be missing. According to OZW it is also returned in the value. Could this help something? Is there something I can do?

**Comment by gizmocuz** [comment]
Try enabled 'accept new hardware/devices' in the settings. Does the value update in the control panel ?

**Comment by cincuranet** [comment]
I have that as default and it doesn't change a thing. :(

**Comment by ootjersb** [comment]
I do have accept new hardware turned on; and already had it. This does not seem to change anything. I noticed this morning that a lot of devices for this same node were not automatically updated. I have now enabled polling. I can see the devices getting updated. I also see the kWh value in control panel being updated (even without pressing refresh)

**Comment by ootjersb** [comment]
Some screenshots to indicate the problem. I would like to have the control panel 28.4 value, but as you can see it does not show up on the devices list. Control panel (I have only snipped the top part, others are fine):
![control panel](https://user-images.githubusercontent.com/33753713/50728821-2cd88300-1130-11e9-8f81-c6547c6646f6.PNG)
Devices (all of them for this node):
![devices](https://user-images.githubusercontent.com/33753713/50728826-382bae80-1130-11e9-8f2e-931b0970221a.PNG)

**Comment by cincuranet** [comment]
Just look at **all** (i.e. script and notification) values for device 304. I bet you'll see both _kWh_ and _kVAh_ values. At least my Domoticz somewhat mixes these two.

**Comment by ootjersb** [comment]
Thanks that brought me a step further. I am not sure how you mean I should get all values for the device. But I did add a notification and dzVents script to do that. I can see that I get more values quickly after each other, and the first value seems to be the kWh value, and the last the kVAh value.

If I only add a dzVents script then I see that it is not triggered for every value, but only for the last of the three that happens almost at the same time, so I am not sure yet on how to best split the values that it reports.

**Comment by cincuranet** [comment]
Yes, that's what I do as well. But I took a different approach. I created virtual sensor. In script I take the value that's only slightly bigger than the virtual sensor's value, because the kVAh value is going to be a lot bigger and that way I can filter it (of course initialize the virtual sensor with current kWh value).

**Comment by bulbje** [comment]
Can this (still) be a similar problem:
https://www.domoticz.com/forum/viewtopic.php?t=33377
https://www.domoticz.com/forum/viewtopic.php?f=24&t=35726&p=270798#p270798
I want to buy MCOHome A8-9 Multi-sensor if all the sensors (including movement and VOC) are visible in Domoticz.

Has anybody ever found a solution or a workaround?
Do I have to open a new issue?

**Comment by gizmocuz** [comment]
This has already been reported. We need to add this into our system.
Time is an issue here, so if you could add support for this and make a PR, that would be great!

**Comment by grrrmml** [comment]
Hello together,
this is not directly connected to this issue, but maybe indirectly: I tried to add an ZHAAirQuality sensor via deCONZ plugin.
Smanar added device type mapping to 'Air Quality' which lead to a sensor in Domoticz of subtype "Voltcraft CO-20".
Are there chances for another sensor subtype for VOC measurement, and maybe even customizable translation of ppq values to an air quality string (excellent, good, ...)? If this can be achieved manually with a custom sensor, I'd be happy for a hint (deCONZ plugin beta now maps a custom sensor).

Some details concerning that sensor type were just discussed in https://github.com/Smanar/Domoticz-deCONZ/issues/103.

With best regards

**Comment by kiddigital** [comment]
As OZW is deprecated, this issue is closed.
