### ISSUE TITLE
Travis Linux build broken

### ISSUE THREAD

**Issue by emontnemery** [domoticz/domoticz#2599]
The travis script fails to patch zwave example build: https://travis-ci.org/domoticz/domoticz/builds/408853253?utm_source=github_status&utm_medium=notification

Build output causing the error:
```
$ (cd open-zwave-read-only; wget http://www.domoticz.com/domo.patch; patch -p1 < domo.patch; make)
--2018-07-27 08:57:32--  http://www.domoticz.com/domo.patch
Resolving www.domoticz.com (www.domoticz.com)... 185.27.142.198
Connecting to www.domoticz.com (www.domoticz.com)|185.27.142.198|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20280 (20K)
Saving to: ‘domo.patch’
100%[======================================>] 20,280      --.-K/s   in 0.1s    
2018-07-27 08:57:32 (180 KB/s) - ‘domo.patch’ saved [20280/20280]
patching file cpp/build/Makefile
Hunk #1 succeeded at 65 with fuzz 1 (offset 6 lines).
patching file cpp/hidapi/hidapi/hidapi.h
patching file cpp/hidapi/libusb/hid.c
Hunk #2 succeeded at 1430 (offset 6 lines).
patching file cpp/hidapi/linux/hid.c
patching file cpp/hidapi/mac/hid.c
patching file cpp/hidapi/windows/hid.cpp
patching file cpp/src/Driver.cpp
Hunk #2 succeeded at 226 (offset 2 lines).
patching file cpp/src/command_classes/CentralScene.cpp
patching file cpp/src/command_classes/CentralScene.h
patching file cpp/src/platform/HidController.cpp
patching file cpp/src/platform/HidController.h
patching file cpp/src/platform/unix/SerialControllerImpl.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n] 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by Jumbotroll** [comment]
It's a changes in domo.patch.
You can use this patch: http://www.jadahl.com/domo.patch

**Comment by emontnemery** [comment]
@gizmocuz Can you please fix this?
How about moving the patch at `http://www.domoticz.com/domo.patch` to git instead?

**Comment by gizmocuz** [comment]
Sorry, just back from holiday.
Patch worked for quite some time, so something must have changed.

You can download the patch and see what it does, feel free to send me an updated version

the removal of the HID support has been merged by OZW ;) Yes!
https://github.com/OpenZWave/open-zwave/pull/1516

So this can be removed from the patch file

The other one is the centralscene patch (OZW patch 1125 out of my mind)
The reason i want to keep using my own patch is that a PR can change any second and might break the current domoticz code.
Once PR 1125 is merged, we need to review this in domoticz

For now, it is easiest to checkout OZW development, and only apply PR 1125, and create the patch
You can add it to our repo, maybe a folder 'patches'
