### ISSUE TITLE
Winddelen - connection error => FIXED in beta v4.9863

### ISSUE THREAD

**Issue by Eternity-again** [domoticz/domoticz#2600]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version.
* Always state your version when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue. 

This issue is CLOSED (Winddelen: Connection error #1869) but it is back again.

Error: Winddelen: Error connecting to: http://backend.windcentrale.nl/windcentrale/productie?id=121

**Comment by LudoStes** [comment]
Winddelen - connection error
Same error here, it seems this started 23-7-2018 22:43 (last measurement).
I have latest version updated today (29-7) : version 4.9796
Start/Stop the RaspBerrry (no result)
Start/Stop Hardware Interface (no result)

From Error log:
Error: Winddelen: Error connecting to: http://backend.windcentrale.nl/windcentrale/productie?id=41

Looks like the website doesn't report with data
![knipsel](https://user-images.githubusercontent.com/22729384/43364547-77e576a6-931c-11e8-8272-0a50ece9dd8f.JPG)

Would it no be an idea to use this link (where 41 is the id of windturbine)
https://zep-api.windcentrale.nl/production/41/live?ignoreLoadingBar=true

**Comment by Eternity-again** [comment]
Can the URL be edited in Domoticz?

**Comment by Eternity-again** [comment]
Here the same.

Updated to the latest beta v4.9796 dated 2018-07-26 still has no Winddelen data.

**Comment by Xorfor** [comment]
It is better to use https://zep-api.windcentrale.nl/production/[id]/live. I also use this link in my Domoticz Python plugin. Look at [https://github.com/Xorfor/Domoticz-Windcentrale-Plugin/wiki](https://github.com/Xorfor/Domoticz-Windcentrale-Plugin/wiki) for more info.

**Comment by Eternity-again** [comment]
Thanks @Xorfor

Where do I edit the URL?

PS
I tried to install Phyton 3 but got an error installing PIP and gave up. Goal was the Winddelen Phyton plugin..

**Comment by LudoStes** [comment]
After some time / trial I am getting the plugin working :-)

Installed GIT
Installed Phyton (version 3.4.2)
Installed the plugin
Installed beta version (domoticz)
restarteded sever time domoticz service

Now I get first results in (but no wind)
Xorfor thanks for the plugin

**Comment by LudoStes** [comment]
@Xorfor 
Looks like it cannot handle negative numbers …
from log …. "powerAbsTot":-12.0,"powerAbsWd":-1.0 …..
….. (WindMolen - Power (3)) Updating device from 0:'0' to have values 0:'0'.
….. (WindMolen) Update WindMolen - Power (3): 0 - '0' - 0
….. (WindMolen - Power (total)) Updating device from 0:'0' to have values 0:'0'.
….. (WindMolen) Update WindMolen - Power (total): 0 - '0' - 0

**Comment by Xorfor** [comment]
**@LudoStes** 
If there is no wind or during maintenance, sometimes the windmills report with negative numbers. That is why I report a 0 instead of the negative value.

**Comment by Eternity-again** [comment]
Updated to latest Domoticz beta domoticz_armadaxp-6.2_4.0.9796-7.spk
Still to luck.

@LudoStes
I was trying the same. I will investigate that again. Had a hard time installing Phyton 3

**Comment by Eternity-again** [comment]
Updated to latest beta v4.9815, still broken.

**Comment by gizmocuz** [comment]
@Eternity-again , well of course someone needs to write a patch to solve this right ?

**Comment by Eternity-again** [comment]
@gizmocuz 
Previously updating to a new beta solved this issue for me. Sorry if I have not understood the correct way of solving this.

Unfortunately my Linux knowledge is poor; I have not been able to install the suggested Phyton plugin. I get stuck after trying to install PIP, with an error in the command line.

**Comment by Eternity-again** [comment]
Working again after updating to beta v4.9863

**Comment by gizmocuz** [comment]
Yes, made some changes here. Thanks for checking!

**Comment by LudoStes** [comment]
Yes working. And also some new measurements (like wind direction and rpm) 👍
