### ISSUE TITLE
Crash when trying to access webserver

### ISSUE THREAD

**Issue by claneys** [domoticz/domoticz#2602]
I can't reach the webserver using the latest update 4.9700. Instead, it displays:
 "Browser Cache is being refreshed...
Please standby..."
 then
"Browser cache refresh failed" and domoticz is offline.

Domoticz in its side segfault and dump a core file. I got two report that relate to the crash, one about domoticz that tells me that "domoticz killed by SIGILL" and the kernel itself telling me that it oops with the reason "traps: domoticz[24077] trap invalid opcode ip:7f951d4b5e22 sp:7f9510764688 error:0 in libssl.so.1.1.0h[7f951d4b2000+5000]"
So it seems to be related to the handling with libssl... I don't get into it deeper but I see that domoticz is linked with libssl 1.0.0 and 1.1.0 ?

I don't really get it, but I tried with compiled version and with the release archive from domoticz upstream channel and same happens.

Here is an archive about the crash: [domoticz-crash_2018-07-30.zip](https://github.com/domoticz/domoticz/files/2239249/domoticz-crash_2018-07-30.zip)

**Comment by claneys** [comment]
I want to add a note that if I don't try to access to the webUI then domoticz just runs fine.

**Comment by emontnemery** [comment]
@claneys Domoticz should only use libssl 1.0..
If you didn't solve the issue, can you please:
```
sudo apt install pax-utils
libtree domoticz
```

**Comment by claneys** [comment]
I'm using a fedora distro not a debian. Ok, it should only libssl 1.0, I'll try to make it use only this version so. A question why use this old version ?

pax-utils doesn't have libtree but a lddtree, I suppose it is what you need:
```bash
# lddtree domoticz
domoticz => ./domoticz (interpreter => /lib64/ld-linux-x86-64.so.2)
    libusb-0.1.so.4 => /usr/lib64/libusb-0.1.so.4
        libusb-1.0.so.0 => /usr/lib64/libusb-1.0.so.0
    libudev.so.1 => /usr/lib64/libudev.so.1
        libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1
    librt.so.1 => /usr/lib64/librt.so.1
    libresolv.so.2 => /usr/lib64/libresolv.so.2
    libz.so.1 => /usr/lib64/libz.so.1
    libcurl.so.4 => /usr/lib64/libcurl.so.4
        libnghttp2.so.14 => /usr/lib64/libnghttp2.so.14
        libidn2.so.0 => /usr/lib64/libidn2.so.0
            libunistring.so.2 => /usr/lib64/libunistring.so.2
        libssh2.so.1 => /usr/lib64/libssh2.so.1
        libpsl.so.5 => /usr/lib64/libpsl.so.5
        libssl.so.1.1 => /usr/lib64/libssl.so.1.1
        libcrypto.so.1.1 => /usr/lib64/libcrypto.so.1.1
        libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2
            libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0
                libselinux.so.1 => /usr/lib64/libselinux.so.1
                    libpcre2-8.so.0 => /usr/lib64/libpcre2-8.so.0
            libkeyutils.so.1 => /usr/lib64/libkeyutils.so.1
        libkrb5.so.3 => /usr/lib64/libkrb5.so.3
        libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3
        libcom_err.so.2 => /usr/lib64/libcom_err.so.2
        libldap-2.4.so.2 => /usr/lib64/libldap-2.4.so.2
            libsasl2.so.3 => /usr/lib64/libsasl2.so.3
                libcrypt.so.1 => /usr/lib64/libcrypt.so.1
                    libfreebl3.so => /usr/lib64/libfreebl3.so
            libssl3.so => /usr/lib64/libssl3.so
            libsmime3.so => /usr/lib64/libsmime3.so
            libnss3.so => /usr/lib64/libnss3.so
            libnssutil3.so => /usr/lib64/libnssutil3.so
            libplds4.so => /usr/lib64/libplds4.so
            libplc4.so => /usr/lib64/libplc4.so
            libnspr4.so => /usr/lib64/libnspr4.so
        liblber-2.4.so.2 => /usr/lib64/liblber-2.4.so.2
    libpthread.so.0 => /usr/lib64/libpthread.so.0
    libdl.so.2 => /usr/lib64/libdl.so.2
    libm.so.6 => /usr/lib64/libm.so.6
    libc.so.6 => /usr/lib64/libc.so.6
    ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
```

**Comment by claneys** [comment]
Ok, I compiled the right version from source of openssl and directly configure domoticz with the following:

```bash
# cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/domoticz -DOPENSSL_SSL_LIBRARY=/usr/local/lib64/libssl.so.1.0.0 -DOPENSSL_INCLUDE_DIR=/usr/local/include/ -DOPENSSL_CRYPTO_LIBRARY=/usr/local/lib64/libcrypto.so.1.0.0 CMakeLists.txt
```
This compile fine and may gave the following output at link:

```bash
/usr/bin/ld: warning: libssl.so.1.1, needed by /usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/libcurl.so, may conflict with libssl.so.1.0.0
/usr/bin/ld: warning: libcrypto.so.1.1, needed by /usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/libcurl.so, may conflict with libcrypto.so.1.0.0
```

Although, this is enough to make it works. 

But, why don't use the latest openssl libraries with the latest security fixes ?
