### ISSUE TITLE
Domoticz v4.9788 crashes when updating hardware "Domoticz - Remote Server"

### ISSUE THREAD

**Issue by jonferreira** [domoticz/domoticz#2604]
As soon as the "Update" button is clicked, even if nothing was changed, this happens

``
terminate called without an active exception

Thread 5 "domoticz" received signal SIGABRT, Aborted.
[Switching to Thread 0x74eb9440 (LWP 12409)]
0x76cecf70 in raise () from /lib/arm-linux-gnueabihf/libc.so.6
(gdb) thread apply all bt

Thread 47 (Thread 0x6f8ff440 (LWP 12891)):
#0  0x76d90c14 in epoll_wait () from /lib/arm-linux-gnueabihf/libc.so.6
#1  0x003cc268 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2  0x003cdd90 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3  0x003d54f8 in boost::asio::io_context::run() ()
#4  0x00832f38 in thread_proxy ()
#5  0x76f27e90 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
#6  0x76d90598 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 46 (Thread 0x67eff440 (LWP 12890)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x70c043f8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 45 (Thread 0x66fff440 (LWP 12746)):
#0  0x76d90c14 in epoll_wait () from /lib/arm-linux-gnueabihf/libc.so.6
#1  0x003cc268 in boost::asio::detail::epoll_reactor::run(long, boost::asio::det---Type <return> to continue, or q <return> to quit---
ail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2  0x003cdd90 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3  0x003d54f8 in boost::asio::io_context::run() ()
#4  0x00832f38 in thread_proxy ()
#5  0x76f27e90 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
#6  0x76d90598 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 43 (Thread 0x700ff440 (LWP 12744)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
Backtrace stopped: Cannot access memory at address 0x4358464a

Thread 30 (Thread 0x686ff440 (LWP 12436)):
#0  0x76f2cb30 in pthread_cond_timedwait@@GLIBC_2.4 ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x007f15f0 in OpenZWave::EventImpl::Wait(int) ()
#2  0x007eeedc in OpenZWave::Wait::Multiple(OpenZWave::Wait**, unsigned int, int) ()
#3  0x007f5a24 in OpenZWave::Driver::PollThreadProc(OpenZWave::Event*) ()
#4  0x0082f254 in OpenZWave::ThreadImpl::Run() ()
---Type <return> to continue, or q <return> to quit---
#5  0x0082f270 in OpenZWave::ThreadImpl::ThreadProc(void*) ()
#6  0x76f27e90 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
#7  0x76d90598 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 29 (Thread 0x68eff440 (LWP 12435)):
#0  0x76d89964 in select () from /lib/arm-linux-gnueabihf/libc.so.6
#1  0x76d9dda4 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
#2  0x68efecd8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 28 (Thread 0x696ff440 (LWP 12434)):
#0  0x76f2c7a4 in pthread_cond_wait@@GLIBC_2.4 ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x007f16a8 in OpenZWave::EventImpl::Wait(int) ()
#2  0x007eeedc in OpenZWave::Wait::Multiple(OpenZWave::Wait**, unsigned int, int) ()
#3  0x00802c90 in OpenZWave::Driver::DriverThreadProc(OpenZWave::Event*) ()
#4  0x0082f254 in OpenZWave::ThreadImpl::Run() ()
#5  0x0082f270 in OpenZWave::ThreadImpl::ThreadProc(void*) ()
#6  0x76f27e90 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
#7  0x76d90598 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
---Type <return> to continue, or q <return> to quit---

Thread 26 (Thread 0x69eff440 (LWP 12432)):
#0  0x76f30010 in connect () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x00000032 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 25 (Thread 0x6a6ff440 (LWP 12431)):
#0  0x76f2cb30 in pthread_cond_timedwait@@GLIBC_2.4 ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x0024e258 in CEventSystem::EventQueueThread() ()
#2  0x00980678 in execute_native_thread_routine ()
#3  0x76f27e90 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
Backtrace stopped: Cannot access memory at address 0x1ec

Thread 24 (Thread 0x6aeff440 (LWP 12430)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x00b1ed28 in m_mainworker ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

---Type <return> to continue, or q <return> to quit---
Thread 23 (Thread 0x6b8ff440 (LWP 12429)):
#0  0x76f300c0 in recv () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0xff0c0000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 22 (Thread 0x6c0ff440 (LWP 12428)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 21 (Thread 0x6c8ff440 (LWP 12427)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 20 (Thread 0x6d0ff440 (LWP 12426)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
---Type <return> to continue, or q <return> to quit---
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x00070e68 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 19 (Thread 0x6d8ff440 (LWP 12425)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 18 (Thread 0x6e0ff440 (LWP 12424)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x00b9a860 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 17 (Thread 0x6e8ff440 (LWP 12423)):
#0  0x76d89a34 in pselect () from /lib/arm-linux-gnueabihf/libc.so.6
#1  0x008655b0 in mosquitto_loop.part ()
#2  0x0048a504 in MQTT::Do_Work() ()
---Type <return> to continue, or q <return> to quit---
#3  0x00980678 in execute_native_thread_routine ()
#4  0x76f27e90 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
#5  0x76d90598 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 16 (Thread 0x6f0ff440 (LWP 12422)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x00070e68 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 13 (Thread 0x70aff440 (LWP 12417)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 12 (Thread 0x714ff440 (LWP 12416)):
#0  0x76f2cb30 in pthread_cond_timedwait@@GLIBC_2.4 ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x002946a4 in MainWorker::Do_Work_On_Rx_Messages() ()
---Type <return> to continue, or q <return> to quit---
#2  0x00980678 in execute_native_thread_routine ()
#3  0x76f27e90 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
#4  0x76d90598 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 11 (Thread 0x71cff440 (LWP 12415)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x00000004 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 10 (Thread 0x724ff440 (LWP 12414)):
#0  0x76d90c14 in epoll_wait () from /lib/arm-linux-gnueabihf/libc.so.6
#1  0x003cc268 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2  0x003cdd90 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3  0x005f8258 in tcp::server::CTCPServer::Do_Work() ()
#4  0x00980678 in execute_native_thread_routine ()
#5  0x76f27e90 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
#6  0x76d90598 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
---Type <return> to continue, or q <return> to quit---

Thread 9 (Thread 0x72cff440 (LWP 12413)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x5b6096b8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 7 (Thread 0x73eb9440 (LWP 12411)):
#0  0x76d90c14 in epoll_wait () from /lib/arm-linux-gnueabihf/libc.so.6
#1  0x003cc268 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2  0x003cdd90 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3  0x0062b2f4 in http::server::server_base::run() ()
#4  0x002fcad0 in http::server::CWebServer::Do_Work() ()
#5  0x00980678 in execute_native_thread_routine ()
#6  0x76f27e90 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
#7  0x76d90598 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 5 (Thread 0x74eb9440 (LWP 12409)):
#0  0x76cecf70 in raise () from /lib/arm-linux-gnueabihf/libc.so.6
---Type <return> to continue, or q <return> to quit---
#1  0x76cee324 in abort () from /lib/arm-linux-gnueabihf/libc.so.6
#2  0x00000020 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0x75eb9440 (LWP 12407)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x00b20260 in m_httppush ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0x766b9440 (LWP 12406)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x70c05370 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0x766c2220 (LWP 12403)):
#0  0x76f30730 in nanosleep () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76f2f504 in __pthread_enable_asynccancel ()
   from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x009aebc0 in ?? ()
---Type <return> to continue, or q <return> to quit---
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

``

**Comment by emontnemery** [comment]
@jonferreira I think this issue is what was solved by #2587, can you please try updating to domoticz 4.9796?

**Comment by jonferreira** [comment]
@emontnemery thanks, all good now

2018-08-02 09:13:39.196  Status: Domoticz: TCP/IP Worker stopped...
[Thread 0x6b6ff440 (LWP 9207) exited]
[New Thread 0x6b6ff440 (LWP 9279)]
2018-08-02 09:13:40.201  Status: Domoticz: TCP connected to: 192.168.1.4:6144

Sorry for missing that issue before!
