### ISSUE TITLE
Unproper graph display for SetPoint Log

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2608]
When you click on Log for a SetPoint device, I feel that we have a wrong graph displayed.

In the here after graph, the setpoint move from 20° to 21° at 22h. So practically the SetPoint value move from 20 to 21 at 22:00 when the setpoint was set. 
The graph here is giving a wrong representation and must be aligned with the reality.

![capture](https://user-images.githubusercontent.com/8291674/43648525-eca41d86-973a-11e8-8a46-f4e8720d5b73.PNG)

I would expect something draw by the red line ( it should be straight lines )

![inkedcapture_li](https://user-images.githubusercontent.com/8291674/43648850-dc3a9b86-973b-11e8-8604-313e467797bb.jpg)

PS/ Such type of graph can make set for measure, where you can accept that there is a smooth shift from one measure to the other one, but in case of setpoint this is more a trigger

**Comment by gizmocuz** [comment]
I agree! Like we have for the switches log.
Could you make a PR ?

**Comment by pipiche38** [comment]
@gizmocuz , I can work on that but would appreciate if you could give me some pointers on where to find the functions doing such graphs ?

**Comment by gizmocuz** [comment]
Should be fixed in next beta version (9854)

![image](https://user-images.githubusercontent.com/2265299/44000910-abe83530-9e28-11e8-98c8-8c02c745ae47.png)

**Comment by pipiche38** [comment]
Thanks:!
