### ISSUE TITLE
Clickatell Sms not working on beta

### ISSUE THREAD

**Issue by germed1** [domoticz/domoticz#2610]
Hi
I experiencing a problem with Clickatell SMS delivery. I have both accounts with Clickatell (a new Sms platform and the old one Communicator) and both of them are not working. The test messages from Clickatell platform are delivered, but not when I use the test button in Domoticz (my blocky sms scripts also not working anymore) . I'm on version 4.9796, Raspberry pi 3.

**Comment by sweetpants** [comment]
pls discuss this on the forum first to see if more users are effected.

**Comment by germed1** [comment]
Hi, thanks for your response.
Already discussed https://www.domoticz.com/forum/viewtopic.php?f=6&t=24175  not so much feedback received however, could you check it directly?

**Comment by sweetpants** [comment]
Hi, i'm not a clickatell user but use the free Telegram solution (BOT) which is also natively supported with Domoticz and works very well.

**Comment by germed1** [comment]
Thanks for the suggestion, but where I go is not always internet connection is present, therefore I have to stick to the cellular network solutions.

**Comment by loglux** [comment]
Clickatell uses different API for new users that is not compatible with Domoticz. The problem is because some users can use old API with no issue. I guess Domoticz developers among with them. If you open a new account you won't be able to use the old API. It could be easily changed in Domoticz code but as I've already said, some of the old users have no issue.

**Comment by gizmocuz** [comment]
Someone has to create a pull request to solve this (and test before doing so)

**Comment by loglux** [comment]
Domoticz use this link 
https://api.clickatell.com/http/sendmsg?user=xxxxxx&password=xxxxxxxx&api_id=xxxxxx&to=15XXXXXXX&text=test&from=13XXXXXXXXX

But if you are a new Clickatell user you must use 
https://platform.clickatell.com/messages/http/send?apiKey=your_key&to=your_mobile_phone_number&content=Test+message+text
There are no fields like 'from' or 'user and 'password' and apiKey is used instead of api_id

**Comment by gizmocuz** [comment]
@loglux , did you look at the domoticz code ? domoticz does not use api.clickatell.com but platform.clickatell.com, so the URL seems correct ?
Now there is some data posted (sPostData), that might need to be changed...
So please have a look at the code, do some changes, test it, and submit a github pull request is everything is tested and OK

**Comment by loglux** [comment]
I'll take a look but anyway the registration and test form in Settings - Notification is completely wrong

**Comment by loglux** [comment]
it designed to old api request.

**Comment by loglux** [comment]
so the api.platform.com I took from Domoticz wiki, by the way

**Comment by loglux** [comment]
I've checked the source code. It completely wrong!
**https://github.com/domoticz/domoticz/blob/development/notifications/NotificationSMS.cpp
return (_clickatellApi != "" && _clickatellUser != "" && _clickatellPassword != "" && _clickatellTo != "" && _clickatellFrom != "");
}

**Comment by gizmocuz** [comment]
@loglux , wiki ? Best to look at the source code. So you looked at the source code... what you copy/pasted above has nothing to do with the API call itself, which is around line 64 till 78
Sure it might be wrong, but as this is an open source project, please correct it, test it, and make a PR

**Comment by loglux** [comment]
I had a look at the source code and found that it is completely wrong and use outdated parameters, There are must be apiKey instead of api_id, and parameters user, password and from are no longer used by Clickatell. So Domoticz makes a completely wrong request

**Comment by gizmocuz** [comment]
@loglux , probably, thats what people are telling. So maybe it is time someone creates a patch, test it, and make a PR?

**Comment by loglux** [comment]
I'll take a look at this weekend. There is also a javascript library that checks parameters on the webform. I'll try just ignore that and make changes in cpp. just to see how it works

**Comment by gizmocuz** [comment]
@loglux , did you find anything ? I checked the code again, and we use the platform api call

**Comment by DewGew** [comment]
Any luck with this issue? For newer  users we only need `"https://platform.clickatell.com/messages/http/send?apiKey=" + API + "&to=" + NUMBER + "&content=" + MESSAGE` to send sms.
In settings _user_, _password_ and _from_ is required. But those are not needed.

**Comment by loglux** [comment]
No. I'm still using a direct HTTP link not the function.

**Comment by nb-ceffa** [comment]
https://github.com/domoticz/domoticz/pull/3994
