### ISSUE TITLE
Toggle timer on scene group with the API

### ISSUE THREAD

**Issue by Gustry** [domoticz/domoticz#2614]
I'm trying to toggle timers for a group:
`curl -s 'http://10.0.0.101:8080/json.htm?type=command&param=enabletimer&idx=9'
`

The answer is : 
```
{
   "status" : "OK",
   "title" : "EnableTimer"
}
```

But neither in the Domoticz UI or in the API the timer is enabled:
`http://10.0.0.101:8080/json.htm?type=schedules` gives me:
```

Active | "false"
-- | --
Color | ""
Date | ""
Days | 128
DevName | "Petits volets"
DeviceRowID | 5
IsThermostat | "false"
Level | 100
MDay | 0
Month | 0
Occurence | 0
Randomness | "false"
ScheduleDate | ""
Time | "00:20"
TimerCmd | 0
TimerID | 9
TimerType | 4
TimerTypeStr | "After Sunset"
Type | "Scene"

```

It's working well for a normal switch timer, but not for a group.

Thanks

Version 4.9700

**Comment by gizmocuz** [comment]
Open the chrome developer console, and select the network tab
Next edit your group timer in the domoticz web interface, you should now see what it being send

**Comment by emontnemery** [comment]
@Gustry TimerID is not unique, so you need to specify if it's a device timer or scene/group timer.
In your case:
`curl -s 'http://10.0.0.101:8080/json.htm?type=command&param=enablescenetimer&idx=9'`

I updated the wiki with this information: https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Enable_specific_schedule.28timer.29_for_Scenes.2FGroups
Please close this issue..

**Comment by Gustry** [comment]
Ok thanks. I will try this weekend

**Comment by Gustry** [comment]
But I think it still wrong that the API responds with a "OK" message.

**Comment by emontnemery** [comment]
It replies "OK" because the TimerID is not unique.
If you have more then 9 device timers, you're enabling the device timer with TimerID 9.

**Comment by Gustry** [comment]
> If you have more then 9 device timers, you're enabling the device timer with TimerID 9.

Well, not exactly. I just tried this:
```
http://10.0.0.101:8080/json.htm?type=command&param=disabletimer&idx=idwhichdoesntexist
```
and it gives:
```
{
   "status" : "OK",
   "title" : "DisableTimer"
}
```

Same for 
```
http://10.0.0.101:8080/json.htm?type=command&param=enablescenetimer&idx=idwhichdoesntexist
```

```
{
   "status" : "OK",
   "title" : "EnableSceneTimer"
}
```
So I take this one as a bug.

But it seems it's working well for 
```
http://10.0.0.101:8080/json.htm?type=command&param=enablescenetimer&idx=9
```
Thanks for the update on the wiki!

**Comment by Gustry** [comment]
Sorry I don't understand why the issue is closed.
```
http://10.0.0.101:8080/json.htm?type=command&param=enablescenetimer&idx=idwhichdoesntexist
```
or
```
http://10.0.0.101:8080/json.htm?type=command&param=enablescenetimer&idx=3
```
returns OK.
But I don't have a scene timer ID 3, so it's very confusing to have "OK" in the answer.

Has this issue already been fixed?

**Comment by emontnemery** [comment]
It's closed because the error you describe in the issue description has been resolved.
Please open a new issue about the lack of error handling.

**Comment by sweetpants** [comment]
As far as i know the OK means your JSON is ok. The user is responsible for testing if the TimeID exists. You can get a list of timers for scenes by issueing ../json.htm?type=schedules&filter=scene first and see if your timer exists.
