### ISSUE TITLE
Building a debug version on a Pi on stretch doesn't seem to be possible

### ISSUE THREAD

**Issue by dannybloe** [domoticz/domoticz#2615]
Just created a new image for my Pi3 using Stretch, fresh install. Following all the steps in the install guid I noticed it doesn't seem to be possible anymore to build (link) a debug version. Also, earlier I could build Domoticz using `make -j 3` but now I can only use `make` or it will run out of memory. That last one is acceptable but I think we do need to be able to build a debug version just to be able to troubleshoot problems on Pi's.

Or am I missing something here? If so, then we have to update the install docs (which doesn't mention Stretch at all making me think the instructions are outdated).

**Comment by kovainfo** [comment]
this is not issue.
RPi3 has insufficient memory for "j 3" make options 
use "make" without any options

**Comment by dannybloe** [comment]
You didn't correctly read what I wrote. 
Besides.. on Jessy `-j 3` worked just fine. 
But the topic is basically about a debug build.

**Comment by gizmocuz** [comment]
Yes, it it the word 'Also', i had to read your post 3 times...
Did you follow our wiki, and made the swap file ?

**Comment by dannybloe** [comment]
No I did not. When I read it I had previously built Domoticz on this same Pi a dozen times successfully (`-j 3` and Debug) so I considered it not to be applicable in my case that time. I never ran out of memory before. So maybe that line should be adapted in the wiki stating that on Stretch (on a Pi3) you do have to make a swapfile if you want to build a debug version. 

So yeah, I missed that suggestion because of my experience before.

Compiling now with a swapfile...

**Comment by SargonofAssyria** [comment]
It might be possible to use zram as a swap solution.

**Comment by dannybloe** [comment]
A swap file indeed did the trick.

**Comment by dannybloe** [comment]
Updated the wiki for this.

**Comment by gizmocuz** [comment]
@dannybloe , where did you updated the wiki ? As i remember, in the wiki was already some comments for the swap file

**Comment by dannybloe** [comment]
I added two comments that on Stretch you may need the swap file if you want to build a debug version and that -j 2 or 3 probably doesn't work. See: https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source#Compiling

**Comment by gizmocuz** [comment]
depends, i run stretch on a system with 4GB, works perfectly.

This already says enough

If you system has limited memory, you might need to create a swap file for compilation. On Debian Stretch you need a swap file if you want to build the debug version.

**Comment by dannybloe** [comment]
This article is about building on a Raspberry Pi. Afaik the Pi3+ has a fixed amount of 1Gb Ram

**Comment by gizmocuz** [comment]
It's for all debian versions, including ubuntu etc. Article needs to replace the other one in the feature

**Comment by dannybloe** [comment]
That may be true but the title of the article now says: Raspberry Pi - Build Domoticz from source

**Comment by gizmocuz** [comment]
Thats why i said "Article needs to replace the other one in the feature"

**Comment by dannybloe** [comment]
Haha.. I know.. just clarifying why I wrote it down as I did.
