### ISSUE TITLE
Can't send battery level to device using MQTT

### ISSUE THREAD

**Issue by ben423423n32j14e** [domoticz/domoticz#2618]
The MQTT interface is missing the ability to send battery level to a device in Domoticz.

https://www.domoticz.com/forum/viewtopic.php?f=56&t=24419

With the increased popularity of zigbee2mqtt this will be important to be able to attach battery levels to Domoticz device idx

Eg, I've got a smoke detector that I'd really like to be notified if battery level falls below x.

MQTT publish, topic: 'zigbee2mqtt/livingroomsmokedetector', payload: '{"battery":"100.00","voltage":3045}'

**Comment by gizmocuz** [comment]
I'm not a MQTT expert, but it seems when you use the MQTT 'udevice' method, there is a 'Battery' field, see the MQTT code in domoticz (hardware/MQTT.cpp)

The example in the forum post(s) are for a switch

https://www.domoticz.com/wiki/MQTT

With udevice you have the same options as the JSON option

**Comment by ben423423n32j14e** [comment]
I appreciate the pointer however it quite literally does not appear to work.

I've read the MQTT.cpp code as well, I cannot get MQTT to pass battery level to a device.

I'd now be up to about 6 hours trying to get it to work. I have a tonn of Zigbee sensors all needing battery data fed in via MQTT.

Here is a Node Red example trying to get it to work, I've also separately tried the udevice method without success.

`[{"id":"754b5cba.b792d4","type":"mqtt in","z":"f962b96d.7044c8","name":"zigbee2mqtt/out","topic":"zigbee2mqtt/xiaomitestbutton","qos":"2","broker":"6e165f21.f7645","x":300,"y":40,"wires":[["9f9ffb94.e2bba8"]]},{"id":"9f9ffb94.e2bba8","type":"json","z":"f962b96d.7044c8","name":"","property":"payload","action":"","pretty":false,"x":450,"y":40,"wires":[["586c4fb7.44f7d"]]},{"id":"d990bc47.0aa8c","type":"mqtt out","z":"f962b96d.7044c8","name":"","topic":"domoticz/in","qos":"","retain":"","broker":"cd51966f.aa7e38","x":750,"y":40,"wires":[]},{"id":"586c4fb7.44f7d","type":"function","z":"f962b96d.7044c8","name":"Format Data","func":"// Xiaomi WXKG01LM Button\nvar click = msg.payload.click.toString();\nvar batt = Math.round(msg.payload.battery);\nmsg.payload.idx = 1213 ;\nmsg.payload.command = 'switchlight' ;\nmsg.payload.switchcmd = 'Set Level' ;\nif(click == 'click') {\n    var level = 0\n} else if (click == 'double') {\n    var level = 10\n// Action holding button before release (not used)\n//} else if (click == 'long') {\n//    var level = 20\n} else if (click == 'long_release') {\n    var level = 20\n}\nmsg.payload.level = level;\nmsg.payload.Battery = batt;\nreturn msg;","outputs":1,"noerr":0,"x":590,"y":40,"wires":[["d990bc47.0aa8c","4b098fa0.3d3c6"]]},{"id":"4b098fa0.3d3c6","type":"debug","z":"f962b96d.7044c8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload.Battery","x":820,"y":100,"wires":[]},{"id":"6e165f21.f7645","type":"mqtt-broker","z":"","name":"Zigbee","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"domoticz/bridge/state","birthQos":"0","birthPayload":"online","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""},{"id":"cd51966f.aa7e38","type":"mqtt-broker","z":"","name":"Domoticz","broker":"192.168.0.5","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]`

**Comment by gizmocuz** [comment]
I need a command line MQTT example with udevice on a voltage sensor with battery percentage to verify/debug this.

**Comment by jvanderzande** [comment]
it looks like the Battery value is not interpreted with the "switchlight" command but works fine with "udevice" command. 
Try something like this tochange that to "udevice":
`[{"id":"57c9e0dd.1e44e","type":"mqtt in","z":"8f2e755.c5df088","name":"zigbee2mqtt/out","topic":"zigbee2mqtt/xiaomitestbutton","qos":"2","broker":"e0b040c9.f3a92","x":165,"y":247,"wires":[["d5dd1f5c.78f11"]]},{"id":"d5dd1f5c.78f11","type":"json","z":"8f2e755.c5df088","name":"","property":"payload","action":"","pretty":false,"x":315,"y":247,"wires":[["ac8c43fc.c39ca"]]},{"id":"863f61d1.002f1","type":"mqtt out","z":"8f2e755.c5df088","name":"","topic":"domoticz/in","qos":"","retain":"","broker":"ca160f08.92f1e","x":615,"y":247,"wires":[]},{"id":"ac8c43fc.c39ca","type":"function","z":"8f2e755.c5df088","name":"Format Data","func":"// Xiaomi WXKG01LM Button\nvar click = msg.payload.click.toString();\nvar batt = Math.round(msg.payload.battery);\nmsg.payload.idx = 1213 ;\nif(click == 'click') {\n var level = 0\n} else if (click == 'double') {\n var level = 10\n// Action holding button before release (not used)\n//} else if (click == 'long') {\n// var level = 20\n} else if (click == 'long_release') {\n var level = 20\n}\nmsg.payload.nvalue = 2 ;\nmsg.payload.level = level;\nmsg.payload.svalue = level.toString();\nmsg.payload.Battery = batt;\nreturn msg;","outputs":1,"noerr":0,"x":455.00000762939453,"y":252.00000381469727,"wires":[["863f61d1.002f1","612cdd85.f2f9c4"]]},{"id":"612cdd85.f2f9c4","type":"debug","z":"8f2e755.c5df088","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload.Battery","x":685,"y":307,"wires":[]},{"id":"e0b040c9.f3a92","type":"mqtt-broker","z":"","name":"Zigbee","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"domoticz/bridge/state","birthQos":"0","birthPayload":"online","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""},{"id":"ca160f08.92f1e","type":"mqtt-broker","z":"","name":"Domoticz","broker":"192.168.0.5","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]`

**Comment by ben423423n32j14e** [comment]
jvanderzande, you sir are a genius! Copied and pasted your node-red example and it works (device control + it stores the battery).

Much appreciated! 👍
