### ISSUE TITLE
Scene 'Off action' triggered instead of 'On action' .. depending on button of remote control

### ISSUE THREAD

**Issue by d-EScape** [domoticz/domoticz#2624]
I control several scenes using a (cheap) KaKu remote control. De remote is intended for four KaKu devices with on and off buttons for each. So 8 keys to officially control 4 devices.

This works:
You can add the off buttons as well as the on buttons as activating devices for scenes. The cheap remote can control 8 different scene's this way, which is great!

Example:
When i hit the deviceX 'On' button on the remote, scene1 is activated. When i hit the deviceX 'Off', scene2 is activated... etc.

When i activate a scene2 by pressing the 'deviceX' 'Off' button all assigned lights are turned on (as expected).

Now for the unexpected:
Although the lights do turn on as configured, the 'On action' script will not run. The 'Off action' script is called instead.
When activating the scene in any other way the 'On action' runs.
Scenes that are activated through the 'On' side of the remote also run the 'On action', as expected.

I suspect this is a leftover of group functionality. Since a group would have on and off triggers and could use both the on and off button on the remote. A scene only has a On trigger. The 'Off' button does trigger scene activation and turn the lights on, but the code that calls the script seems to look at the type off button instead of the type of event (activation).

I will include two screenshots to clarify this hard to explain issue.
One screenshots shows a scene that can be triggered through a 'Off' button on the remote and has devices configured (this works).
The other shows a scene that is also triggered by a off button but tries to run a 'On action' script. That only works when triggered by something else than remote control.

<img width="1178" alt="schermafbeelding 2018-08-09 om 18 16 19" src="https://user-images.githubusercontent.com/8693608/43911831-c5fc8cf2-9c00-11e8-8b20-1497b886b9d3.png">
<img width="1181" alt="schermafbeelding 2018-08-09 om 17 16 36" src="https://user-images.githubusercontent.com/8693608/43911851-d59e5c6c-9c00-11e8-8d39-bf09847f6dba.png">

**Comment by gizmocuz** [comment]
Thanks for the explanation! I think you are right, going to look into this !

**Comment by gizmocuz** [comment]
What version of Domoticz are you running ?
I am unable to replicate this.
Note that in your scene, you have one light, that you actually turn OFF instead of ON (tuinverlighting_rouleren)

**Comment by d-EScape** [comment]
Hi gizmocuz,

Thanks for looking into this issue! I'm running V4.9796 compiled from source on raspbian. 'Tuinverlichting_Rouleren' is a dummy switch that triggers a script that gradually changes the (subtile) light colors in my garden. In the first example it is indeed off. The real lights are turned on.

I only get the issue when using my Kaku remote and the button that is 'officially' a Off button. Activating the scene trough the web interface or from a script works just fine. Did you try a KaKu remote? Mine is a Klik aan Klik uit type: AYCT-102.

**Comment by gizmocuz** [comment]
I also use a kaku remote for testing

Could you try the steps i did

- Create a dummy switch
- set a ON action in this switch

Create a scene, add the dummy switch with the ON command
Learn the kaku off button (not the group off, the off of one of the actions)

Now when i press the off button, the ON action is called for the dummy switch
This can not be any other way, as the switch itself will also be turned (correctly) on

**Comment by d-EScape** [comment]
I know this will work and am already using this method as a work around. The dummy switch is a device in the scene, and devices already work. It is only the action scripts that are not behaving as expected. Could you try this to replicate:

- create a scene
- make a Kaku off button the activation trigger for the scene
- Set a script for on action (‘aan actie’)
- trigger the scene with the Kaku off button
Does the script run?

You can try the same but set the script as the off action for the scene.
Does the script run?

**Comment by gizmocuz** [comment]
Ahh okey.. it is the on action in the scene... I will check this ASAP

**Comment by gizmocuz** [comment]
Should work as expected in upcoming beta
