### ISSUE TITLE
Synology build error.

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#2633]
[ 22%] Building CXX object CMakeFiles/domoticz.dir/main/Helper.cpp.o
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r9841/main/Helper.cpp: In function ‘bool IsWSL()’:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r9841/main/Helper.cpp:1149:53: error: ‘O_RDONLY’ was not declared in this scope
  int status_fd = open("/proc/sys/kernel/osrelease", O_RDONLY);
                                                     ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r9841/main/Helper.cpp:1149:61: error: ‘open’ was not declared in this scope
  int status_fd = open("/proc/sys/kernel/osrelease", O_RDONLY);
                                                             ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r9841/main/Helper.cpp:1153:57: error: ‘read’ was not declared in this scope
  ssize_t num_read = read(status_fd, buf, sizeof(buf) - 1);
                                                         ^
make[5]: *** [CMakeFiles/domoticz.dir/main/Helper.cpp.o] Error 1

**Comment by sweetpants** [comment]
Same as https://github.com/domoticz/domoticz/issues/2634 fixed in https://github.com/domoticz/domoticz/pull/2635

**Comment by Jumbotroll** [comment]
fixed in #2635.
