### ISSUE TITLE
Compilation error after recent git pull on dev branch

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2634]
[ 23%] Building CXX object CMakeFiles/domoticz.dir/main/Helper.cpp.o
/usr/share/domoticz/beta-domoticz/main/Helper.cpp: In function ‘bool IsWSL()’:
/usr/share/domoticz/beta-domoticz/main/Helper.cpp:1149:53: error: ‘O_RDONLY’ was not declared in this scope
  int status_fd = open("/proc/sys/kernel/osrelease", O_RDONLY);
                                                     ^~~~~~~~
/usr/share/domoticz/beta-domoticz/main/Helper.cpp:1149:53: note: suggested alternative: ‘STA_RONLY’
  int status_fd = open("/proc/sys/kernel/osrelease", O_RDONLY);
                                                     ^~~~~~~~
                                                     STA_RONLY
/usr/share/domoticz/beta-domoticz/main/Helper.cpp:1149:18: error: ‘open’ was not declared in this scope
  int status_fd = open("/proc/sys/kernel/osrelease", O_RDONLY);
                  ^~~~
/usr/share/domoticz/beta-domoticz/main/Helper.cpp:1149:18: note: suggested alternative: ‘popen’
  int status_fd = open("/proc/sys/kernel/osrelease", O_RDONLY);
                  ^~~~
                  popen
/usr/share/domoticz/beta-domoticz/main/Helper.cpp:1153:21: error: ‘read’ was not declared in this scope
  ssize_t num_read = read(status_fd, buf, sizeof(buf) - 1);
                     ^~~~
/usr/share/domoticz/beta-domoticz/main/Helper.cpp:1153:21: note: suggested alternative: ‘fread’
  ssize_t num_read = read(status_fd, buf, sizeof(buf) - 1);
                     ^~~~
                     fread
make[2]: *** [CMakeFiles/domoticz.dir/build.make:167: CMakeFiles/domoticz.dir/main/Helper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/domoticz.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by sweetpants** [comment]
Already reported, due to https://github.com/domoticz/domoticz/commit/0f04a3dddc2350f18a5684ee46f4c1a8cad20b5d

**Comment by pipiche38** [comment]
Duplicate as #2633

**Comment by gizmocuz** [comment]
That why you first search in the issues or have a look at the latest once
