### ISSUE TITLE
Synology build error.

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#2637]
Not all synology build have this problem, but arch-rtd1296 and arch-qoriq.

[ 24%] Building CXX object CMakeFiles/domoticz.dir/main/Scheduler.cpp.o
[ 25%] Building CXX object CMakeFiles/domoticz.dir/main/SignalHandler.cpp.o
/home/dahl/spksrc-master/spk/domoticz/work-rtd1296-6.2/domoticz-r9854/main/SignalHandler.cpp: In function ‘bool printRegInfo(siginfo_t*, ucontext_t*)’:
/home/dahl/spksrc-master/spk/domoticz/work-rtd1296-6.2/domoticz-r9854/main/SignalHandler.cpp:71:109: error: ‘mcontext_t’ has no member named ‘arm_lr’
  _log.Log(LOG_ERROR, "siginfo address=%p, address=%p", info->si_addr, ((ucontext_t *)ucontext)->uc_mcontext.arm_lr);
                                                                                                             ^
make[5]: *** [CMakeFiles/domoticz.dir/main/SignalHandler.cpp.o] Error 1

**Comment by gizmocuz** [comment]
Have the same issue for 64 bit arm systems

https://github.com/domoticz/domoticz/pull/2575

**Comment by Jumbotroll** [comment]
Thanks.
