### ISSUE TITLE
Domoticz doesn't compile on latest commit

### ISSUE THREAD

**Issue by remcom** [domoticz/domoticz#2645]
On commit 4b274d4739661ac3bbae58158ff3e34e0e72edf0

I have the following compile error on a debian 9 machine

`/home/remco/domoticz/webserver/server.cpp: In member function ‘void http::server::server_base::heart_                                                                                beat(const boost::system::error_code&)’:
/home/remco/domoticz/webserver/server.cpp:139:21: error: ‘boost::asio::steady_timer {aka class boost:                                                                                :asio::basic_waitable_timer<std::chrono::_V2::steady_clock>}’ has no member named ‘expires_after’; di                                                                                d you mean ‘expires_at’?
   m_heartbeat_timer.expires_after(std::chrono::seconds(4));
                     ^~~~~~~~~~~~~
CMakeFiles/domoticz.dir/build.make:5078: recipe for target 'CMakeFiles/domoticz.dir/webserver/server.                                                                                cpp.o' failed
make[2]: *** [CMakeFiles/domoticz.dir/webserver/server.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by gizmocuz** [comment]
What version of GCC are you using ? Try updating to 6 or higher
What version of boost have you installed ? Try using 1.67 or higher

**Comment by remcom** [comment]
I'm running;
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
libboost1.62-dev

I will check if i can update boost. Good to now is that if boost is the issue that poelple on debian 9 machines are unable to build when you just use default apt-get versions.

**Comment by remcom** [comment]
Updated boost to 1,68 and did a clean build. Now i have more errors

`CMakeFiles/domoticz.dir/main/Camera.cpp.o: In function `boost::system::system_category()':
Camera.cpp:(.text._ZN5boost6system15system_categoryEv[_ZN5boost6system15system_categoryEv]+0x5): undefined reference to `boost::system::detail::system_category_ncx()'
CMakeFiles/domoticz.dir/main/Camera.cpp.o: In function `boost::system::generic_category()':
Camera.cpp:(.text._ZN5boost6system16generic_categoryEv[_ZN5boost6system16generic_categoryEv]+0x5): undefined reference to `boost::system::detail::generic_category_ncx()'
CMakeFiles/domoticz.dir/main/EventSystem.cpp.o: In function `boost::thread::do_try_join_until(boost::detail::mono_platform_timepoint const&)':
EventSystem.cpp:(.text._ZN5boost6thread17do_try_join_untilERKNS_6detail23mono_platform_timepointE[_ZN5boost6thread17do_try_join_untilERKNS_6detail23mono_platform_timepointE]+0x7e): undefined reference to `boost::thread::do_try_join_until_noexcept(boost::detail::mono_platform_timepoint const&, bool&)'
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:6099: recipe for target 'domoticz' failed
make[2]: *** [domoticz] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`

Going to revert to old boost version. Also the hash that I'm coming from isn't building with the boost 1.68

**Comment by gizmocuz** [comment]
Okey, please try following the wiki here
https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source

**Comment by remcom** [comment]
Oke. Got it fixed. Already did everything their to update libboost for the exeption of ` cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt`

After that its working again. Thnx for the tips @gizmocuz
