### ISSUE TITLE
something weird with battery levels

### ISSUE THREAD

**Issue by heggink** [domoticz/domoticz#2649]
I use both the python battery device plugin (uses zwave xml) as well as a dzvents script to look at the battery status of devices. I've now had 2 occasions where, after replacing the battery, the status is not reported correctly in dzvents where teh JSON interface is updated. Example posted here.

https://www.domoticz.com/forum/viewtopic.php?f=6&t=24436&p=188813#p188813

The net: either lua or dzvents uses outdated info where teh zwave.xml and json have the updated values.

Any idea what's going on?

and yes, I did restart and so forth.

**Comment by rwaaren** [comment]
I experienced the same. After updating to beta V4.9910 and a soft reset of my Zwave controller and a heal network (both in node management under hardware tab) and a bit of patience, the status is reported correctly again.

**Comment by heggink** [comment]
Latest beta (9999) seems to have resolved this issue. Just changed a battery and the response was pretty much immediate... Closing as no longer an issue.
