### ISSUE TITLE
Respond to MySensors request() for V_KWH

### ISSUE THREAD

**Issue by mzealey** [domoticz/domoticz#2650]
https://github.com/domoticz/domoticz/blob/a593d3b8a737456aea23edfdc458027d0b142a3e/hardware/MySensorsBase.cpp#L2284 handles most of MySensors request() details. I've got a MySensors device sending V_WATT for instant measurements and V_KWH for totals. On reboot the device looses the previous V_KWH details and requests them from domoticz. But domoticz won't respond as there isn't code in this function to return it unfortunately.

**Comment by gizmocuz** [comment]
Hi, if you look at the watermeter sketch example, you see it uses a VAR, this is supported
Can you post a link to your KWH sensor example ?

**Comment by gizmocuz** [comment]
Did you solved this ?

**Comment by gizmocuz** [comment]
No response, i assume it is solved, thanks for all the feedback !
