### ISSUE TITLE
Problem during last upgrade

### ISSUE THREAD

**Issue by sweetpants** [domoticz/domoticz#2653]
During last upgrade I got the following messages:
git pull
Updating c4fcbb2..77917fd
error: Your local changes to the following files would be overwritten by merge:
	hardware/DenkoviTCPDevices.cpp
	hardware/DenkoviTCPDevices.h
	hardware/DenkoviUSBDevices.cpp
	hardware/DenkoviUSBDevices.h
Please, commit your changes or stash them before you can merge.
Aborting

harrys@harrys-pc ~/MyProjects/Cpp/Domoticz/domoticz $ git stash
warning: CRLF will be replaced by LF in hardware/DenkoviTCPDevices.cpp.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in hardware/DenkoviTCPDevices.h.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in hardware/DenkoviUSBDevices.cpp.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in hardware/DenkoviUSBDevices.h.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in hardware/DenkoviTCPDevices.cpp.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in hardware/DenkoviTCPDevices.h.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in hardware/DenkoviUSBDevices.cpp.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in hardware/DenkoviUSBDevices.h.
The file will have its original line endings in your working directory.
Saved working directory and index state WIP on development: c4fcbb2 Merge pull request #2606 from dzelyaydinov/development
HEAD is now at c4fcbb2 Merge pull request #2606 from dzelyaydinov/development

When issuing a git pull again i still get 

git pull
Updating c4fcbb2..77917fd
error: Your local changes to the following files would be overwritten by merge:
	hardware/DenkoviTCPDevices.cpp
	hardware/DenkoviTCPDevices.h
	hardware/DenkoviUSBDevices.cpp
	hardware/DenkoviUSBDevices.h
Please, commit your changes or stash them before you can merge.
Aborting

If I do a make, it builds the new version, but git pull still issues the error

This is on both my test as production system

**Comment by sweetpants** [comment]
After a hard reset to the development branch **git reset --hard origin/development** it seems fixed again.

**Comment by gizmocuz** [comment]
And that in 30 minutes
