### ISSUE TITLE
Install script tries to install to wrong home directory if user is root

### ISSUE THREAD

**Issue by tjswe** [domoticz/domoticz#2655]
Trying to install on the Dietpi distribution which uses root as default user.

Running curl -L install.domoticz.com | sudo bash

When install script runs i get the error

mkdir: cannot create directory `/home/root/domoticz´: No such file or directory

(This is because the user root has its home directory in /root. /home/root does not exist)

An idea would be to check /etc/passwd for the correct home directory? 

Other than that, thanks for a super software! Keep it up!

**Comment by tjswe** [comment]
No!

I was to quick in the install wizard

I do get to choose the install directory.

Nothing to see here. 

Sorry!

**Comment by gizmocuz** [comment]
Also please use the forum
