### ISSUE TITLE
iphone7 Enabled checkbox unchecks itself.

### ISSUE THREAD

**Issue by SaintLenneth** [domoticz/domoticz#2658]
Hi,

Was doing some testing with the gcm notifications and noticed that my iphone7 suddenly was not receiving any notifications. Did a check at Mobile Devices page to find that Enabled check box is unchecked. Have then checked the checkbox but after sometime, it unchecks itself again.

This has happened a few times and seemingly randomly.
Any idea that might have caused this to happen ?
Using Stable Domoticz 4.9700  
![image](https://user-images.githubusercontent.com/41514839/44311054-2365ad00-a413-11e8-8fec-a4cfb79a7d28.png)

Thanks !

**Comment by gizmocuz** [comment]
Nope, does this still happens ?

**Comment by waltervl** [comment]
Stale, can be closed.
