### ISSUE TITLE
Hue dim level is limited to 16 steps

### ISSUE THREAD

**Issue by marcovandeveen** [domoticz/domoticz#2659]
**Observation**

dim % hue app |  brightness hue api | dim % domoticz
------------ | ------------- | ------------- 
1% | 1 | 6%
15% | 38 | 13%
30% | 76 | 26%
50% | 127 | 53%
98% | 248 | 100%
100% | 254 | 100%

**Impact**
For me this had the following impact: confusing behavior in my Lua scripts that are controlling the dim levels for various lights. The scripts detect a manual override by comparing the last automatically set dim level, with the current dim level. However the value set through Lua, is different then the level effective in Domoticz.

**Likely cause**
@emontnemery in issue #2613:
> Philips Hue integration is using LIGHTING2 type to represent simple dimmers, which is limited to 16 dim levels.

**Comment by emontnemery** [comment]
The fix is straightforward:
- Use pTypeGeneralSwitch instead of pTypeLighting2, affects functions CPhilipsHue::WriteToHardware, CPhilipsHue::InsertUpdateSwitch
- Add database patch to migrate existing Hue devices from pTypeLighting2 to pTypeGeneralSwitch

**Comment by chrislader** [comment]
I ll monitor this story and test my hue lights as well for the fix.

**Comment by emontnemery** [comment]
Please try this build: http://montnemery.com/domoticz_hue_general_switch/001/domoticz_linux_armv7l.tgz

Changes:
- At first start of Domoticz, there will be a one-time database upgrade to migrate existing Hue devices from pTypeLighting2 to pTypeGeneralSwitch
- Hue integration uses pTypeGeneralSwitch instead of pTypeLighting2

**Make a backup of your domoticz installation / database before testing!**
The database migration is done only once, so if it has bugs it's not easy to retest without a backup.

Easiest way to test is to simply drop the domoticz binary from the domoticz_linux_armv7l.tgz in your domoticz install directory after making a backup of the domoticz database.

Please save the domoticz log and paste the relevant parts (there are prints during the database migration, as well as when a state change is detected after polling the Hue gateway).

**Comment by marcovandeveen** [comment]
Will do a.s.a.p. But probably next week, as I'm out for a weekend.

**Comment by emontnemery** [comment]
@marcovandeveen, @chrislader Did you find the time to test?

**Comment by marcovandeveen** [comment]
Not yet. This weekend.

**Comment by chrislader** [comment]
@Emontnemery 
Im still on holiday so cant help/test at this moment. Hopefully marcovandeveen can send his results asap.

**Comment by marcovandeveen** [comment]
I deployed the build, but no change. Also hue lights still state lightning2. 
I didn't see log DB migration log statements.

**Comment by emontnemery** [comment]
@marcovandeveen Very strange.. Can you confirm you can still control the dimmer from Domoticz UI using the "Lighting 2" device?
If that works, please double check you deployed the build correctly as I removed Lighting 2 support from the Philips hue class.

Maybe easiest way is to check the md5 matches:
```
$ md5sum domoticz
d552eb79fb09f225535594ac6475be27  domoticz
```

**Comment by marcovandeveen** [comment]
My bad: used wrong binary. 

**OBSERVATIONS**
**Migration log**
2018-09-02 15:25:48.490 Status: Domoticz V4.9920 (c)2012-2018 GizMoCuz
2018-09-02 15:25:48.491 Status: Build Hash: 0e6e2ec7-modified, Date: 2018-08-21 22:38:55
2018-09-02 15:25:48.491 Status: System: Raspberry Pi
2018-09-02 15:25:48.491 Status: Startup Path: /home/pi/domoticz/
2018-09-02 15:25:48.515 Status: HueBridge DB patch: Migrate device with DeviceID '0000001' to new DeviceID '00000001'
2018-09-02 15:25:48.515 Status: HueBridge DB patch: Migrate device with DeviceID '0000002' to new DeviceID '00000002'
2018-09-02 15:25:48.515 Status: HueBridge DB patch: Migrate device with DeviceID '0000008' to new DeviceID '00000008'
2018-09-02 15:25:48.515 Status: HueBridge DB patch: Migrate device with DeviceID '000000C' to new DeviceID '0000000C'
2018-09-02 15:25:48.516 Status: HueBridge DB patch: Migrate device with DeviceID '000000D' to new DeviceID '0000000D'
2018-09-02 15:25:48.534 Status: EventSystem: reset all events...

**Switchtypes**
I don't have hue devices with 'lightning2' as subtype anymore

**Dimlevels**  

dim % hue app | brightness hue api | dim % domoticz
------------ | ------------- | ------------- 
1% | 1 | Off
15% | 39 | 14%
30% | 76 | 30%
50% | 127 | 50%
98% | 250 | 98%
100% | 254 | Off

**Comment by marcovandeveen** [comment]
So the 1% and 100% states are wrongly interpreted as 'Off'. Note that the hue api returns 'on': true at those levels

**Comment by emontnemery** [comment]
Thanks for testing!

I'll fix the incorrect mapping of the 1% and 100% dim levels and upload a new binary.

**Comment by emontnemery** [comment]
@marcovandeveen Please try this one: http://montnemery.com/domoticz_hue_general_switch/002/domoticz_linux_armv7l.tgz

**Comment by marcovandeveen** [comment]
Tests with a40012c90abe727dce6945dfc0d0eef1 domoticz

**Observation 1: from hue to domoticz**

dim % hue app | state % hue app |  brightness hue api | state in hue api |  dim % domoticz | state domoticz
------------ | ------------ | ------------- | ------------- | ------------- | -------------
1% | On | 1 | On | **16%** | **OFF**
15% | On |  36 | On | 16% | On
30% | On | 76 | On | 30% | On
50% | On | 126 | On | 50% | On
98% | On | 248 | On | 98% | On 
100% | On | 254 | On | 100% | On

Issue: Domoticz light state at 1% incorrect

**Observation 2: from domoticz to hue**

dim % domoticz app | state % domoticz app |  dim % in hue app | state hue app
------------ | ------------ |  ------------- | -------------
1% | On |  1% | On
15% | On |  15% | On
30% | On |  30% | On
50% | On | 50% | On
98% | On |  98% | On 
100% | On | 100% | On

No issues

**Observation 3: Changing hue state in while dim level is 1%**
1. Switch light on with 30% in hue app. Domoticz update correspondingly
2. Dim light to 1% in hue app. Domoticz is changed to state 'OFF'
3. Switch off light in hue app (while being on 1%). Domoticz state doesn't change
4. Switch on light in hue app (while being on 1%). Domoticz state changes to 'ON' and dimlevel to 1%

**Observation 4: Hue API brightness values at 1%**
Dimming in hue app to 1% can give two values in hue API
```
"state": {
    "on": true,
    "bri": 1
}
```

And 

```
"state": {
    "on": true,
    "bri": 0
}
```

**Comment by marcovandeveen** [comment]
It seems the domoticz light state is updated based on the API brightness (bri), instead of the state. 

The result is that API bri: 1 or bri: 0 results in off state in domoticz.

**Comment by emontnemery** [comment]
Try this one:
http://montnemery.com/domoticz_hue_general_switch/003/domoticz_linux_armv7l.tgz

I added some debug prints in Domoticz log to understand why the 1% dimlevel is not working, as well as a fix for the 0% (which is outside Philips hue spec..)

**Comment by marcovandeveen** [comment]
The md5sum is the same as the previous build: a40012c90abe727dce6945dfc0d0eef1 domoticz

Is that correct?

**Comment by emontnemery** [comment]
No, that was not correct..
Try this one: http://montnemery.com/domoticz_hue_general_switch/004/domoticz_linux_armv7l.tgz

**Comment by marcovandeveen** [comment]
75f3bdac6322daafd0ba231ac99a1ed9  domoticz

**Observation 1: from hue to domoticz**

dim % hue app | state % hue app |  brightness hue api | state in hue api |  dim % domoticz | state domoticz
------------ | ------------ | ------------- | ------------- | ------------- | -------------
1% | On | 0 | On | 1% | On
15% | On |  38 | On | 15% | On
30% | On | 75 | On | 30% | On
50% | On | 127 | On | 50% | On
98% | On | 248 | On | 98% | On 
100% | On | 254 | On | 100% | On
1% | Off | 0 | Off | 1% | Off 
50% | Off | 127 | Off | 50% | Off 
100% | Off | 254  | Off | 100% | Off 

No issues

**Observation 2: from domoticz to hue**

dim % domoticz app | state % domoticz app |  dim % in hue app | state hue app
------------ | ------------ |  ------------- | -------------
1% | On |  1% | On
15% | On |  15% | On
30% | On |  30% | On
50% | On | 50% | On
98% | On |  98% | On 
100% | On | 100% | On

No issues

**Observation 3: Changing hue state in while dim level is 1%**
1. Switch light on with 30% in hue app. Domoticz updates correspondingly
2. Dim light to 1% in hue app. Domoticz is changed is NOT changed
3. Switch off light in hue app (while being on 1%). Domoticz state changes to 'Off'
4. Switch on light in hue app (while being on 1%). Domoticz state changes to 'On' and dimlevel to 1%

No issues

**Observation 4: logging**
See [Logging.txt](https://github.com/domoticz/domoticz/files/2350408/Logging.txt)

**Comment by marcovandeveen** [comment]
Not sure about the logging, but problems seem to be resolved.

**Comment by emontnemery** [comment]
Thanks a lot for the very detailed testing and reporting!

I opened PR #2709.

**Comment by marcovandeveen** [comment]
Thanks a lot for fixing. Can I safely upgrade to the latest beta, from the modified build?

**Comment by emontnemery** [comment]
Yes, it should be fine, but please backup the Domoticz database just in case.
