### ISSUE TITLE
Flod messages of kodi plugin

### ISSUE THREAD

**Issue by DAVIZINH0** [domoticz/domoticz#2667]
Hello,
In first place sorry if this message is not apropiated.
I see in last betas that the kodi plugin flod my log with messages like this:

>  2018-08-22 11:55:33.130 Kodi: (Kodi_Salon) Handling message: '{"id":1001,"jsonrpc":"2.0","result":"pong"}'.
2018-08-22 11:56:03.134 Kodi: (Kodi_Salon) Handling message: '{"id":1001,"jsonrpc":"2.0","result":"pong"}'.
2018-08-22 11:56:33.137 Kodi: (Kodi_Salon) Handling message: '{"id":1001,"jsonrpc":"2.0","result":"pong"}'.
2018-08-22 11:57:03.139 Kodi: (Kodi_Salon) Handling message: '{"id":1001,"jsonrpc":"2.0","result":"pong"}'.
2018-08-22 11:57:33.144 Kodi: (Kodi_Salon) Handling message: '{"id":1001,"jsonrpc":"2.0","result":"pong"}'.
2018-08-22 11:58:03.144 Kodi: (Kodi_Salon) Handling message: '{"id":1001,"jsonrpc":"2.0","result":"pong"}'.
2018-08-22 11:58:33.149 Kodi: (Kodi_Salon) Handling message: '{"id":1001,"jsonrpc":"2.0","result":"pong"}'. 

or similar with a media is playing with the progress every minute.
Its posible not show this low level of logs?

Thanks

**Comment by dnpwwo** [comment]
What logging level do you have set for the plugin on the hardware page?

**Comment by DAVIZINH0** [comment]
Hello,
i have:
Error + forced messages

is this the problem?

**Comment by bizziebis** [comment]
I would like to change this too. But I don't see an option of a log level anywhere at the hardware page, or plugin settings page..

**Comment by dnpwwo** [comment]
Sounds like you guys are using the native Kodi support rather than the plugin version.

The plugin has a lot more functionality (including adjustable logging).

[https://github.com/dnpwwo/Domoticz-Kodi-Plugin](url)

**Comment by DAVIZINH0** [comment]
yes, im using the native support.
Thanks for the advice, i will lock for the plugin version

**Comment by gizmocuz** [comment]
I see. In the plugin there is way to many logging indeed and this should be set to the hardware option (i will do that)
@dnpwwo , shall i remove the native support for kodi in Domoticz ?
Is the python script in the repo and available for end-users to select from the hardware dropdown ?
What if users can't install python ?

**Comment by gizmocuz** [comment]
@DAVIZINH0, will be solved in the upcoming beta version

**Comment by DAVIZINH0** [comment]
ok, thanks a lot!

**Comment by dnpwwo** [comment]
The native version still works well and as you point out not everyone wants
(or can) install python. I think we should leave it, some people still use
it.

The 'python script in the repo' is a python plugin so it does show up in
the drop down when installed.

**Comment by gizmocuz** [comment]
@dnpwwo , it's not 'really' inside domoticz, the script is in 'examples' and needs to be 'moved' somehow to the main 'script' folder.
I don't see a benefit of having two hardware classes (c++/python) for the same hardware.
Are both the same ? If not, one could have more functionality then the other, in that case, the previous one should be removed....

A bit off topic, i see a python plug "Awox SmartPlug"  in the plugin folder, but don't see this under 'hardware', same if i move the kodi/denon example plugin a directory higher
" Status: PluginSystem: Started, Python version '3.6.3'."

**Comment by gizmocuz** [comment]
@dnpwwo , please ignore previous plugin comment of not showing up... had to launch the right domoticz instance ! (whoeps...)

**Comment by dnpwwo** [comment]
@gizmocuz,

The examples are really just that, examples for developers to copy. I add
things to them when new features are added to the framework, I wouldn't
recommend moving them higher.  There is a plugin page on the wiki (
https://www.domoticz.com/wiki/Plugins) that shows all advertised plugins
and where to find them

The Kodi plugin version I maintain is on github (
https://github.com/dnpwwo/Domoticz-Kodi-Plugin) and it does have some extra
features but the native one is still quite functional and some people use
it.

The Amox Smartplugin should be removed, it does not comply with the current
API and will not work.

**Comment by gizmocuz** [comment]
Maybe we should create a more general python plugin repository ?
This way, we could build a plugin system in domoticz that can let end-users select a plugin to install/remove

**Comment by gizmocuz** [comment]
Anyway, thats outside the scope of this issue, this issue is fixed in the current beta version
