### ISSUE TITLE
No  log for EVO home devices in GUI desktop version

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#2670]
Not sure on which version it starts but an empty screen is presented  where day, month and year log are expected for EVO home temperature devices log page.
This behaviour is on V4.9868 - V4.9921 but probably started on earlier version.

Data is still updated in the Temperature and Temperature_Calendar tables and loggraphs are still shown when using the android app.

see also [http://www.domoticz.com/forum/viewtopic.php?f=6&t=24459]
I see this on my Synology (DSM 6.2) and on my PI (Debian Stretch)

**Comment by rwaaren** [comment]
Seems to be picked up already by gordonb3 (Pull request #2669:  repair graphs and reports for Evohome devices )

**Comment by gordonb3** [comment]
And already committed as well :D

**Comment by rwaaren** [comment]
Seems to work on chrome in incognito mode and in other browsers but even after clearing cache / appcache several times, restarting chrome and desktop I still don't get the graphlogs in normal chrome mode. 
Anything else to be cleared ?

**Comment by gordonb3** [comment]
Don't know. I've never used chrome. Do know that cache can bite sometimes though.

**Comment by rwaaren** [comment]
Solved in V4.9926
For chrome browser also clear Browsing date:

[ctrl][shift][delete] -->Advanced
Choose 
"cookies and other site data"
"cached images and files"
"hosted app data"
[Clear data]
