### ISSUE TITLE
Enhance logging a little bit.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#2676]
My logging shows:
2018-08-25 09:59:50.669 (RFXCOM) Lighting 1 (Zolder staande lamp)
It would be nice if the logging also shows if this switch was set On or Off

**Comment by gizmocuz** [comment]
You can enable verbose logging in the startup parameters

**Comment by SargonofAssyria** [comment]
You are right, but then the log grows rapidly.
My settings are Errors and minimal execution info. I beleave that's the default.
Even then my logs are several Mb per day.
A simple status of the device at the end the line would be appreciated.

**Comment by gizmocuz** [comment]
It's not easy to do as the switch (in this case) is handled elsewhere then where the log is displayed, and they are not linked.
If you need a log message, you can add a simple blockly/event that adds a log message when the switch will turn on/off.
Yes, it's a work-around, but possible

**Comment by SargonofAssyria** [comment]
OK, Tnx.
