### ISSUE TITLE
Ec3kMeter may crash on certain ec3k readings

### ISSUE THREAD

**Issue by Batilan** [domoticz/domoticz#2678]
Using V4.9913 I got this error when enabling Ec3kMeter. It was able to connect to ec3k-server but Ec3kMeter crashes after a few sensor readings with the following message.

2018-08-19 17:49:32.373  Status: Ec3kMeter: connected to: 127.0.0.1:3001
terminate called after throwing an instance of 'Json::LogicError'
2018-08-19 17:49:34.270  (EC3K) General/kWh (EC3K meter e2a5 Usage)
  what():  LargestUInt out of Int range
Aborted

I will try to find the root-cause of this issue.

@llagendijk

**Comment by gizmocuz** [comment]
I think you have to look in Ec3kMeterTCP::ParseData
Maybe you can write the json to disk and post this here, or debug the class

**Comment by Batilan** [comment]
Thx. Found the issue, Indeed the issue is in ParseData on Integer conversion.
Will create a pull request, fix is minor.
