### ISSUE TITLE
[MySensors] Data from light sensors not displayed after upgrade to latest stable

### ISSUE THREAD

**Issue by pompilir** [domoticz/domoticz#2687]
Hi,
I've updated my domoticz to this latest stable version. But now all my MySensors (v2.2) light sensors (photo-resistor sending V_LIGHT_LEVEL numbers) are not working.
I can see all of them sending the number in the Setup tab. But on my devices the reported light is nomore updated and only the last value (acquired before the update of Domoticz) is displayed, as in the image attached
![1535475196133-screenshot-from-2018-08-28-18-52-33-resized](https://user-images.githubusercontent.com/14028689/44766343-574e7a00-ab59-11e8-9952-29be66193c9d.png)

Do you know any reason?
Thanks in advance!

**Comment by gizmocuz** [comment]
I have no idea, i guess this is related to MySensors ? Could you edit your topic to include this
Did you based your sketch on an example ? Which example ?
Did you try to enable 'accept new hardware', do you get maybe new sensors ?
This latest stable is 9700 ?

**Comment by pompilir** [comment]
Hi,
thanks for your reply. It's not related to MySensors (v2.2) for sure because all my problems arose when I've updated to the latest Domoticz (4.9700). 
I'm sending messages of V_LIGHT_LEVEL type for my S_LIGHT_LEVEL sensor. 
Again, only after the Domoticz upgrade all the S_LIGHT_LEVEL sensors vales are not displayed...

**Comment by gizmocuz** [comment]
@ricmail85 , sure it is related to MySensors as you are sending V_LIGHT_LEVEL, which is a MySensors command
Can you point me to your sketch (put it on https://pastebin.com/ , or point me to the example you created this from)
Without this, i can not debug

**Comment by pompilir** [comment]
Hi,
thanks for your support. I'm using this sketch in my project: https://www.mysensors.org/build/light-lm393
thanks again!

**Comment by pompilir** [comment]
I've done more testing and upgraded domoticz to latest beta. But no results yet.
The V_LIGHT_LEVEL are correctly displayed in the Setup tab but not on the device widgets... 

Do you have any news? Thanks!

**Comment by gizmocuz** [comment]
Still need to work on this, time is the issue

Looking at the domoticz MySensors code to see when a LUX sensor is send:

S_LIGHT_LEVEL/V_LEVEL

Seems if you use S_LIGHT_LEVEL/V_LIGHT_LEVEL you can a percentage sensor in domoticz

Do you have accept new hardware enabled in the settings ? Do you have a percentage sensor or a lux sensor or both an one is updating ?

**Comment by pompilir** [comment]
Yes I'm using percentage (V_LIGHT_LEVEL) not lux (V_LEVEL). I can try to change my code and send lux...
All the hardware is accepted automatically.

**Comment by pompilir** [comment]
Solved. In the new versions of Domoticz it created new devices for the percentage Light sensors. The one shown in the picture were the "old" sensors that now are recognized only as Lux sensors.
So i've removed the old Lux sensors and replaced with the new Percentage ones.

Everything seems to work correctly.
Thanks for your support

**Comment by gizmocuz** [comment]
Great!, thanks for the feedback!
