### ISSUE TITLE
Wrong today values for Counter device

### ISSUE THREAD

**Issue by cincuranet** [domoticz/domoticz#2688]
Domoticz versions: 4.9957, 4.9700 (current stable)

* Add new _Counter_ device (using _Dummy_ hardware). This is the initial state. No edits to the device were made.
![counter1](https://user-images.githubusercontent.com/4540597/44776719-0a7a9b80-ab79-11e8-929f-52c7084e2372.png)

* Update the value using API `http://127.0.0.1:8080/json.htm?type=command&param=udevice&idx=1&svalue=1000`.
![counter2](https://user-images.githubusercontent.com/4540597/44776797-35fd8600-ab79-11e8-980c-7171adc0f534.png)
The total value _1kWh_ is correct, the daily is not.

* Update again `http://127.0.0.1:8080/json.htm?type=command&param=udevice&idx=1&svalue=3000`.
![counter3](https://user-images.githubusercontent.com/4540597/44776873-66452480-ab79-11e8-928b-70e340502985.png)
The daily is still `0`.

* After a while the daily is `0 kWh` (not `0` only).
![counter4](https://user-images.githubusercontent.com/4540597/44776915-84ab2000-ab79-11e8-8c61-649379fb8317.png)

* Updating again, now to _5kW_, updates both values, but the daily is _3kWh_ behind.
![counter5](https://user-images.githubusercontent.com/4540597/44777047-e10e3f80-ab79-11e8-87cf-2252bcec0b42.png)

**Comment by gizmocuz** [comment]
Can you wait at least 5 minutes, every 5 minutes a value is stored in the database and is used for the calculation

**Comment by cincuranet** [comment]
Fine with me.
