### ISSUE TITLE
Unable to use ipv6 address in "Local Networks (no username/password):"

### ISSUE THREAD

**Issue by bnj04** [domoticz/domoticz#269]
Hello,

i was trying to enter an ipv6 address in the field "Local Networks (no username/password):" but this didn't work. I then check the code and see that there is nothing specific to handle ipv6 address.

any chance to add this functionality ?

thank you,

**Comment by gizmocuz** [comment]
could you add it ? not that ipv6 minded here...

**Comment by bnj04** [comment]
i'm not really sure i have the skill to add this support in c++, i will try ;)

**Comment by rkluwen** [comment]
Look at the struct _tIPNetwork in cWebEm.h. You will want to add ipv6 support in that. After that, see the function AddLocalNetworks() that is in cWebEm.cpp. Scan the string "network" to see if it's an ipv6 address and set the flags in the structure accordingly.
Finally, the function AreWeInLocalNetwork() needs to be adapted. This is a hint for anybody that wants to fix this issue.
