### ISSUE TITLE
v4.9960 - SSL certificate not loaded anymore

### ISSUE THREAD

**Issue by simonedimarzio** [domoticz/domoticz#2690]
SSL certificate (created 2 days ago with COMODO) does not work anymore after upgrading to v4.9960.
It was working fine in v4.9956.

The connection is marked by browsers as "Not Secure".

**Comment by simonedimarzio** [comment]
I'm sorry, pem file have been overridden by Domoticz update, my fault.

**Comment by gizmocuz** [comment]
Use the forum next time please!
