### ISSUE TITLE
Building domoticz and make FGKF601 work

### ISSUE THREAD

**Issue by f-bor** [domoticz/domoticz#2693]
Hi,

I can't get a keyfob FGKF601 remote controller to work when I build domoticz from source (the buttons are never added to the devices). It's working perfectly when I use the precompiled versions you distribute, either on windows or linux. 

I'm building on a debian 9 x86_64 and I have tried to match the libraries used in the binary distribution to understand why it's failing with my own build.

This issue is I am having troubles finding the exact openzwave source you have used to compile yours. Could you please provide me a tarball with this source ?

Also, I saw you have copied the headers from the openzwave library directly into domoticz. It seems that's an issue to me and I was wondering why ? (they did a small definition change in the dev branch that triggers linking errors because of headers mismatch)

**Comment by gizmocuz** [comment]
First, try following this wiki (yes, also for your debian system) 
https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

Make sure you follow it step-by-step, including all folder names ! This is extreme important

You can see in the travis build file how we compile as well

**Comment by f-bor** [comment]
Indeed I have followed the wiki at the beginning. Then, after hours of searching why my keyfob's buttons were not added, I gave a try to your binaries (I had to build the openssl 1.0.0 to run it on my debian). It worked like a charm.

Then, I tried to build the master branch, and it also failed. So I tried to build the master branch with various openzwave versions, and it failed each time. I even built it with openssl 1.0.0, just to be sure.

I think this problem is related to openzwave library because I have this log when I use the git version (as instructed in the wiki), regardless the version of domoticz:
> 2018-08-31 19:25:01.742 Detail, Node002, Decrypted Packet: 0x00, 0x5b, 0x03, 0x00, 0x80, 0x01
> 2018-08-31 19:25:01.742 Info, Node002, Received Central Scene set from node 2: scene id=1 in 7680 seconds. Sending event notification.
> 2018-08-31 19:25:01.743 Warning, Node002, No ValueID created for Scene 1

And I have this one when I use your binaries:
> 2018-08-31 19:29:52.018 Detail, Node002, Decrypted Packet: 0x00, 0x5b, 0x03, 0x00, 0x80, 0x01
> 2018-08-31 19:29:52.019 Info, Node002, Received Central Scene set from node 2: scene id=1 with key Attribute 128. Sending event notification.
> 2018-08-31 19:29:52.019 Detail, Node002, Initial read of value
> 2018-08-31 19:29:52.019 Detail, Node002, Initial read of value
> 2018-08-31 19:29:52.019 Detail, Node002, Notification: ValueChanged
> 2018-08-31 19:29:52.019  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: CENTRAL SCENE, Label: Scene ID, Instance: 2
> 2018-08-31 19:29:52.019 Detail, Node002, Notification: ValueChanged
> 2018-08-31 19:29:52.021  (dummy) Light/Switch ()

The only real difference I see is the snapshot of openzwave library (3164 vs 3079). I am willing to investigate what has change in the library but it would help me a lot to have the source you used to build your binaries and that's working.

**Comment by f-bor** [comment]
Also, I just checked the history of CentralScene.cpp in openzwave git and there is no record of the log message that's displayed with your binaries (saying "with key Attribute xxx"). Are you using a custom or patched version of openzwave ?

**Comment by gizmocuz** [comment]
Ahh OK, yes, then you need to apply the centralscene patch (see the travis build script)

**Comment by f-bor** [comment]
Yes, I figure by myself that a "git pull origin pull/1125/head" in the openzwave folder was the solution.

As I lost hours and saw quite some other folks having the same issue, may I suggest to add to the wiki's page a disclaimer or a mention to the travis build script to have a fully functionnal domoticz ? I think everyone is expecting having the same level of features when building from source than installing binaries.

**Comment by f-bor** [comment]
I also have the same problem as in issue #2243 to make keyfob working with double tap, triple tap, long press start and long press end (switch does not appear). I did some debugging and code reading and as I understand the openzwave library, domoticz shoud process "Scene Number" notifications instead of "Scene ID".

The scene id value always corresponds to the button pressed, regardless how we press it. The scene number is computed like this in openzwave: 10*scene_id + key_attribute So it identifies both the button and how we press it.

I did the change in my build (that's only 2 lines to change in OpenZWave.cpp) and it's working fine now: there is one switch in domoticz for each (button, press mode or press state) pair.

**Comment by gizmocuz** [comment]
@fredbor , no not yet, waiting for openzwave to merge the patch (hopefully soon)
After the final patch has been merged, we are going to look at the current implementation

**Comment by jacobhallgren** [comment]
> I also have the same problem as in issue #2243 to make keyfob working with double tap, triple tap, long press start and long press end (switch does not appear). I did some debugging and code reading and as I understand the openzwave library, domoticz shoud process "Scene Number" notifications instead of "Scene ID".
> 
> The scene id value always corresponds to the button pressed, regardless how we press it. The scene number is computed like this in openzwave: 10*scene_id + key_attribute So it identifies both the button and how we press it.
> 
> I did the change in my build (that's only 2 lines to change in OpenZWave.cpp) and it's working fine now: there is one switch in domoticz for each (button, press mode or press state) pair.

Can you please tell me more of what files /lines you changed to make the keyfob apear as all buttons not only six?

**Comment by f-bor** [comment]
Hi,

@jacha05, you just have to change the two occurrences of "Scene ID" by "Scene Number" in hardware/OpenZWave.cpp. Otherwise, I did a commit with the changes: https://github.com/f-bor/domoticz/commit/f3a6813576e12d1471d2dcf110fa9b1572ba169d

@gizmocuz, openzwave has merged the central scene patch. Do you plan to do the implementation ?

**Comment by jacobhallgren** [comment]
> Hi,
> 
> @jacha05, you just have to change the two occurrences of "Scene ID" by "Scene Number" in hardware/OpenZWave.cpp. Otherwise, I did a commit with the changes: [f-bor@f3a6813](https://github.com/f-bor/domoticz/commit/f3a6813576e12d1471d2dcf110fa9b1572ba169d)
> 
> @gizmocuz, openzwave has merged the central scene patch. Do you plan to do the implementation ?
@f-bor 
Sorry I must be blind. Can't find the hardware folder in my installation. Not in domoticz/Config

and not in /domoticz. where is that folder?

Regards, Jacob

**Comment by jacobhallgren** [comment]
`system@domoticz:~/domoticz$ls
CPackConfig.cmake        License.txt     domoticz.db-shm  domoticz_crash.log     ozwcp.stat.XXXXXX  server_cert.pem  www
CPackSourceConfig.cmake  domocookie.txt  domoticz.db-wal  dzVents                ozwcp.topo.XXXXXX  stdafx.h.gch
Config                   domoticz        domoticz.old     ozwcp.poll.XXXXXX.xml  plugins            updatebeta
History.txt              domoticz.db     domoticz.sh      ozwcp.scenes.XXXXXX    scripts            updaterelease
` 

`system@domoticz:~/domoticz/Config$ ls
2gig                      dome                 firstalert  horstmann                  merten       schlage      waynedalton
BeNext                    domitech             forest      idlock                     nexia        schlagelink  wenzhou
OZW_Log.txt               domux                fortrezz    ingersoll                  nodon        sensative    widom
act                       dragontech           frostdale   inovelli                   northq       shenzen_neo  zipato
aeotec                    duwi                 ge          intermatic                 oomi         simon        zooz
assa_abloy                ecolink              gocontrol   iris                       options.xml  steinel      zwave.me
august                    electronicsolutions  gr          kaipule                    options.xsd  stelpro      zwcfg.xsd
cooper                    enerwave             graber      kwikset                    philio       swiid        zwcfg.xsd.save
danfoss                   eurotronic           greenwave   leviton                    polycontrol  telldus      zwcfg_0x000f0e32.xml
device_classes.xml        everspring           hank        linear                     popp         thermofloor  zwcfg_0xc8d88c15.xml
device_classes.xsd        everspringct         heiman      logicsoft                  qees         trane        zwcfg_0xe4588e6a.xml
device_configuration.xsd  evolve               heltun      manufacturer_specific.xml  qubino       tronika      zwp
devolo                    fakro                homeseer    manufacturer_specific.xsd  rcs          vision       zwscene.xml
dlink                     fibaro               honeywell   mcohome                    remotec      vitrum       zwscene.xsd
system@domoticz:~/domoticz/Config$ `

**Comment by jacobhallgren** [comment]
@f-bor 
Recomplied domoticz and I now have the hardware folder and the devices are showing up. Except when I double/triple-click. But hold and 1-click works. Do you get devices when double/triple-clicking etc?

Checking my OZW_Log I get the same key_attribute when double/triple-clicking as when I only click once. Do you know how to make it so the keyfob sends unique key_attribute values when I click once, twice and thrice?

In this issue: https://github.com/domoticz/domoticz/issues/2243 he gets diffrent attributes for every key pressed (X times)

**Comment by jacobhallgren** [comment]
Figured it out setting value 15 in paramets 21-26 did it. Now all attributes show up and the switches. Cheers!

**Comment by f-bor** [comment]
ah that's nice. I'm glad you made it :)

**Comment by tih** [comment]
Um, so if I'm reading this right, applying https://github.com/f-bor/domoticz/commit/f3a6813576e12d1471d2dcf110fa9b1572ba169d to Domoticz, and https://github.com/OpenZWave/open-zwave/pull/1125 to OpenZWave should be sufficient to make the Fibaro keyfob useable for scene activations?

**Comment by f-bor** [comment]
yes, except you don't need the openzwave PR anymore since it has been merged into openzwave.

**Comment by tih** [comment]
I don't really understand the relationship between the Dev and master branches in OpenZWave... Will the code always be newer in Dev, even though e.g. the config subtree is lagging? I've been building from the master branch locally, because the "317 commits ahead, 209 commits behind" status of Dev looks fishy. Should I just switch to Dev? The config subtree should be irrelevant for Domoticz, because we have our own copy, I suppose...?

**Comment by f-bor** [comment]
ah yes you are right, they did'nt merge into the master branch and I guess domoticz does not support openzwave dev version. So you need to use the openzwave master branch and apply PR 1125.

**Comment by tih** [comment]
It works just great! Thank you so much! :)

**Comment by TheUlpio** [comment]
In OZW 1.6, witth commit 2298810, my Fibaro keyfob works out of the box. Time to close this issue?

**Comment by gizmocuz** [comment]
Could you give it one more try with beta 10844 ? Just to double check

**Comment by TheUlpio** [comment]
Ok, I'm with beta 10848:

This is how i set scenes associated to buttons:
- square button (todo, i,m waiting a fibaro fgs223 to control the lights in my daughter's bedroom)
- circle button single tap: desk lamp on; double tap: desk lamp off
- X button single tap: hall dimmer to 25%; double tap: dimmer to 50%; triple tap: dimmer to 100%; long press: dimmer off
- triangle button single tap: bathroom light on; double tap: bathroom light off
- minus button not used for now, but i added all devices flawlessly
- plus button single tap: daughter's bedroom blind to 25%; double tap: blind to 50%; triple tap: blind to 100%; long press: blind off

All devices are added by activating the "allow for 5 minutes" option in settings and then all are added in devices.

@gizmocuz i can confirm it works out of the box. Thanks for the fantastic job :)

**Comment by gizmocuz** [comment]
Great, thanks for testing !!!

**Comment by TerrorSource** [comment]
> Ok, I'm with beta 10848:
> 
> This is how i set scenes associated to buttons:
> 
> * square button (todo, i,m waiting a fibaro fgs223 to control the lights in my daughter's bedroom)
> * circle button single tap: desk lamp on; double tap: desk lamp off
> * X button single tap: hall dimmer to 25%; double tap: dimmer to 50%; triple tap: dimmer to 100%; long press: dimmer off
> * triangle button single tap: bathroom light on; double tap: bathroom light off
> * minus button not used for now, but i added all devices flawlessly
> * plus button single tap: daughter's bedroom blind to 25%; double tap: blind to 50%; triple tap: blind to 100%; long press: blind off
> 
> All devices are added by activating the "allow for 5 minutes" option in settings and then all are added in devices.
> 
> @gizmocuz i can confirm it works out of the box. Thanks for the fantastic job :)

Updated to 10881 beta and added a Keyfob, Only got the 6 button sensors. i cannot use them for double or triple click.
How did you manage to get that working?

**Comment by gizmocuz** [comment]
@TerrorSource , do you have 'accept new hardware/devices' enabled in the settings ?
Nothing happens when you double click on a button ?
Could you enable the Debug log on the controller, then restart the OZW hardware, then wait till it has queried all devices, then double press the button.
Now open the log file in the config folder, and check if you see any messages from this node (related to the button/scene press)
Be sure you have also updated to the latest openzwave code

**Comment by TerrorSource** [comment]
It is turned on in settings and always has been:
ON - Accept new Hardware Devices Allow for 5 Minutes
ON - Hide Disabled Hardware Sensors
OFF - Flash sensor when an update is received

Will try the things you mentioned later today.

**Comment by TerrorSource** [comment]
@gizmocuz i enabled "Debug mode" on the Aeotec Gen5. Did a soft-reset of the controller.
Removed the Keyfob and re-added. 
Pressed the Square button once, it was added to Domoticz.
Pressed the Square button twice, not added
Pressed the Square button triple, not added.

Or isn't this what you ment? I didn't quite get what you wanted with the logs.
How can i retreive the openzwave version?

**Comment by gizmocuz** [comment]
@TerrorSource , a softreset was not needed
When you select the 'controller' from the node list (node 1), you get some options underneath
Enable the 'debug'
Press 'apply config' at the bottom...
I think you have to disable the hardware, and enable it , to take this into account ...

Now when you look at the domoticz log, and you press 1 time, you should see a log line
If you double press, you should see another, if not, go to the config folder, you should see a new file (OZW_Log****)
In here you should see some lines mentioning the node (keyfob) when you press double

Do NOT FORGET to disable the debug log... it will get quite big !!!!

Also, check your configuration of the node... i remember i had to enable 'scene' activation somehow... 
By the config... or by holding two buttons... should be in the manual

**Comment by TerrorSource** [comment]
@gizmocuz working now! Thanks!

Only thing that doesn't work right now is:

10. Single button associations - operating mode: 
- Single press switches state to opposite
"This parameter allows to choose operating mode for single button associations."
Key's of the Keyfob(all 18 of them) are "ON" and do not switch to "OFF".
When i press the switch in Domoticz itself i get "Error sending switch command, check device/hardware !"

**Comment by gizmocuz** [comment]
You can not send a command to a 'scene' node type.... 
You need to add a Scene/Group in domoticz, and learn the right keyfob button to this, then add devices in there.

**Comment by TheUlpio** [comment]
@TerrorSource sorry for my late answer. I think this may be a forum topic, but i'm happy to help you here.

First thing to check is how parameters 21~26 are set in hardware (mine 15 for all buttons. The default 9 is only for press once and hold). To set them you have to wakeup the device (press both circle and plus buttons)

Then, in settings select the "allow for five minutes button". this opens the log window. Then you have to push every button once, twice, thrice and hold (until the led flashes).

Logs report a line only for the first time you push a button. No logs for other sequences, So you can se a line for square button, a line for the circle button, and so on (6 lines).

Then go to devices tab and search the last devices added. That's all. I just tried and works like a charm

**Comment by gizmocuz** [comment]
@TheUlpio , correct, there is a forum topic about this. But i was answering to the fact that TerrorSource was sending switch commands with Domoticz to the keyfob.
Anyway, case closed, all working , all happy ;)
