### ISSUE TITLE
Netatmo thermostats duplicated multiple times

### ISSUE THREAD

**Issue by RobMeerwijk** [domoticz/domoticz#2700]
Bug appeared first release 3.8153 just a few days before installing 4.9700. 

**Description:**
On every refresh of Netatmo there is a change that there is a new Setpoint for one or more thermostats. The ID-changes, but the last two bytes remain equal. When changing the value of the setpoint via Domoticz randomly one of the thermostats is given the new value. This is often not the intended thermostat.

At some point in time, 5 thermostats appeared as 30 virtual thermostats.
 
**Attempts to correct the problem**
- Removed all Thermostats from Domoticz: no solution
- Switched back to the names that are stored in the Netatmo Server: no solution 
- Updated Domoticz to latest release (june 2018): no solution
- Removed Netatmo hardware and added it again: no solution
- Tried latest beta (sept 2nd 2018): no solution
- Rremove all "Away"'s and all Temperature sensors belonging to the thermostats: no solution

See also: https://www.domoticz.com/forum/viewtopic.php?t=23985

**Comment by gizmocuz** [comment]
Send you a PM on the forum for a debug request

**Comment by RobMeerwijk** [comment]
Hi any news on this bug? Thanks!

**Comment by RobMeerwijk** [comment]
Things got worse, lately. I made a workaround that kept me happy. I created a guest for every netatmo thermostat on the netatmo site and I create a separate netatmo hardware entry in domoticz for every thermostat. But right now I get two setpoint devices for every thermostat device. So the work around is gone now.
