### ISSUE TITLE
EnOcean ESP3 + Trio2sys din module

### ISSUE THREAD

**Issue by xbeaudouin** [domoticz/domoticz#2703]
Hello,

Tried to find some help on forums but I don't have any clues.

I have some DIN modules like this one : http://trio2sys.fr/index.php/fr/produits-enocean-sans-fil-sans-pile-interoperable/recepteur-sans-fils-sans-pile-interoperable-enocean/39

This can replace a traditional module and give the opportunity to have EnOcean commands.

Unfortunatly it is not usuable on Domoticz and the vendors doesn't want to help me to integrate this.

Uppon registration I get this on the log : 
```
2018-08-09 18:31:24.681 EnOcean: destination: 0xffffffff RSSI: 24
2018-08-09 18:31:24.681 EnOcean: teach-in request received from 01A0490F (manufacturer: 02C). number of channels: 255, device profile: D2-01-01
2018-08-09 18:31:24.681 EnOcean: Sender_ID 0x01A0490F already in the database
```

I have tried to tweak around line 1894 in EnOceanESP3.cpp but I get 255 unusable switch which is not what it supposed to be (there is only 1 chanel on this module).

Is there some people that can help me ? or this is something on ESP3 that is not yet implemented ?

Regards,
Xavier

**Comment by alexis-via** [comment]
Datasheet of the product say it uses Enocean profile D2-01-00 (http://tools.enocean-alliance.org/EEPViewer/profiles/D2/01/00/D2-01-00.pdf). For the moment, only D2-01-0C is supported, cf https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L2120

**Comment by waltervl** [comment]
@efdeb Can this issue be closed? In Wiki https://www.domoticz.com/wiki/EnOcean there is support mentioned for
D2-01-XX, Electronic Switches and Dimmers with Local Control
Is D2-01-00 part of D2-01-XX ??

**Comment by efdeb** [comment]
According to EnOcean-Equipment Profiles EEP-2.6.8 specification, all D2-01-XX devices **send their status** using CMD 0x4 - Actuator Status Response telegram. This status telegram is supported by Domoticz, so yes, this issue can be closed.

Nb. I do not own all EnOcean devices to test, so reopen an issue in case of problem.
