### ISSUE TITLE
Netatmo: timeout temperature devices when connection issue

### ISSUE THREAD

**Issue by 999LV** [domoticz/domoticz#2706]
I noted that when my Netatmo weather station goes offline (happens from time to time at my vacation home that local wifi connectivity seems to drop and requires a weather station reset, but this is a separate issue), domoticz keeps updating the temperature devices every 10 minutes with the same value and no error message.

I would suggest that the hardware driver rather sets the device status as « timedout » and stops updating the temperatures. This will allow scripts or plugins (such as the Smart Virtual Thermostat python plugin that I wrote) to discard inaccurate temperature readings.

Unfortunately my c++ coding skills are minimal and I am hoping that the netatmo.cpp hardware driver can be modified by somebody... otherwise I will have to create a python plugin (that I can code...) from scratch which would be a lot of duplicate development work.

Many thanks for help from the core developpers if one can find the time to look into this.

**Comment by gizmocuz** [comment]
Yes, that's the normal behavior. we could make a global settings for this to not do so
If you can code python, you might be able to code C

**Comment by 999LV** [comment]
For now, I am testing an approach where the Netatmo hardware stops updating the domoticz sensor devices if the last update field in the Netatmo data is older than the last update in domoticz. This way the devices time out in the GUI after the global « sensor time out » setting time (red banner) and scripts/plugins can test this last update for timeout.
Will submit a pull request when ready for production.

**Comment by 999LV** [comment]
pull request submitted: https://github.com/domoticz/domoticz/pull/2752
