### ISSUE TITLE
RFXcom and lighting 4 (pt2262)

### ISSUE THREAD

**Issue by gysmo38** [domoticz/domoticz#2713]
Hello,
Since 1week, I have issue with RFXcom and Lighting 4.
It work well during months but with last upgrade when I send lighting 4 command, my rfxcom stop to work.
The red led stay on  on the rfxcom. I need to pul/unplug the rfxcom to get it work again.

I have also ARC, AC and Blyss devices. They work perfectly until I use the Lighting 4 device.
If someone can help me, it will be very appreciate.

**Comment by gizmocuz** [comment]
@gysmo38 , i think you posted this on the forum, or mailed me directly. This is called cross posting and is not allowed.
At least a reference to the original message would be nive

**Comment by gysmo38** [comment]
So if I do it wrong. I send a message here Remove RFXCom specifics from CDomoticzHardwareBase #2680 but we told me to open an issue.
So I open an issue here. This is not the good way?
