### ISSUE TITLE
Incorrect units for humidity and pressure on "Custom Temperature Graph"

### ISSUE THREAD

**Issue by piranha32** [domoticz/domoticz#2717]
The tooltips on the graph show temperature units for all series shown. I identified two bugs in www/app/TemperatureCustomLogController.js:
1. baseName calculation has not been updated after the format of series name changed.
2. There was missing code assigning units for barometric series.

Attached patch fixes both bugs.
[TemperatureCustomLogController.js_tooltip_units.txt](https://github.com/domoticz/domoticz/files/2391446/TemperatureCustomLogController.js_tooltip_units.txt)

**Comment by gizmocuz** [comment]
bugs or problem ? As .2 was not implemented and considered a missing feature ?
As for .1, this needs to be [1], as the string contains <name of sensor>:<type>

I added the unit for the barometric sensor. It should be available in the next beta version

Thanks for the patch! If possible, please try to make a pull request
