### ISSUE TITLE
Xiaomi Gateway: Use DNS name rather than IP address

### ISSUE THREAD

**Issue by kireque** [domoticz/domoticz#2718]
Since my last update the native support for multiple Xiaomi Gateways have been implemented. Which is a great option!

Only it's not possible to add the Gateway using the DNS name. I really don't want to use IP addresses for this kind of configurations. 
Is it possible to create a new option in the hardware tab for the Xiaomi Gateway to add it using the DNS name? A simple nslookup should do the trick?

**Comment by gizmocuz** [comment]
Best to let the code resolve the DNS name into an IP address, winsock has default functions for this....
