### ISSUE TITLE
Data Timeout enable, always trigger a restart of the plugin

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2721]
I have enabled Data Timeout for a plugin to 5'

Even if this plugin is receiving messages more often than every minutes, I get a restart.

```
Sep 21 21:41:46 pi3 domoticz[921]: 2018-09-21 21:41:46.569  (Zigate) updating SQN from f9 to 01
Sep 21 21:41:46 pi3 domoticz[921]: 2018-09-21 21:41:46.622  (Zigate) updating SQN from ef to ff
Sep 21 21:41:46 pi3 domoticz[921]: 2018-09-21 21:41:46.674  (Zigate) updating SQN from fa to 02
Sep 21 21:41:53 pi3 domoticz[921]: 2018-09-21 21:41:53.439  (Zigate) updating SQN from b3 to c4
Sep 21 21:42:01 pi3 domoticz[921]: 2018-09-21 21:42:01.038  Error: Zigate hardware (3) nothing received for more than 5 Minutes!....
Sep 21 21:42:02 pi3 domoticz[921]: 2018-09-21 21:42:02.039  Error: Restarting: Zigate
Sep 21 21:42:02 pi3 domoticz[921]: 2018-09-21 21:42:02.040  Status: (Zigate) Stop directive received.
Sep 21 21:42:02 pi3 domoticz[921]: 2018-09-21 21:42:02.040  Status: (Zigate) Exiting work loop.
Sep 21 21:42:02 pi3 domoticz[921]: 2018-09-21 21:42:02.179  Error: CConnection_disconnect, disconnection request from 'Zigate' ignored. Transport does not exist.
Sep 21 21:42:02 pi3 domoticz[921]: 2018-09-21 21:42:02.185  Status: (Zigate) onStop called

```

As you can see in the here above example, messages have been received 8 seconds before it get restarted !

I'm on Beta/development version 4.9999 ( 4ef5bf01a6fc577587972354cb9931e07f48f832 )

**Comment by gizmocuz** [comment]
Does it update any sensors ? This is not about messages, but updating actual sensors inside domoticz

**Comment by gizmocuz** [comment]
No feedback received, closing issue.

**Comment by differentieel** [comment]
sorry for reopening this issue - it happens on my Domoticz RPi Zero setup in 'connection' with a RPi Zero Pihole plugin - setup is working well
from the log:

```
2020-11-23 03:00:02.067 Status: Starting automatic database backup procedure...
2020-11-23 03:00:16.485 Status: Ending automatic database backup procedure...
```
**2020-11-23 03:00:16.731 Error: CConnection_disconnect, disconnection request from "HadVanger" ignored. Transport does not exist.**
```
2020-11-23 03:01:04.098 Status: Notification sent (Email)
2020-11-23 04:00:01.778 Status: Starting automatic database backup procedure...
2020-11-23 04:00:18.507 Status: Ending automatic database backup procedure... 
```

HadVanger = Pihole

Although the process continues i would like to correct settings to have an error free Domotizc setup.
Any suggestion is welcome.

**Comment by gizmocuz** [comment]
@differentieel , Please state your Domoticz version and if you tried the latest beta version ....
Pihole plugin for Domoticz or you mean running PiHole ?
How large is your database ?
Do you need to have a automatic database backup ? I mean, I am running domoticz for 8 years and I don't use it
From time to time I make a backup from the settings page

**Comment by differentieel** [comment]
thnx 4 responding Gizmucuz

Version: 2020.2 (build 12690)
Build Hash: c63fd800e-modified
Compile Date: 2020-11-21 08:24:28
dzVents Version: 3.0.16
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

plugin is called "Pi-hole summary" - xfr-pihole

database: 10,1 MB on disk

thnx for your backup suggestion - i have complete standstills on a regular base - i assume SDcard issues - will look for another more reliable sollution
