### ISSUE TITLE
Domoticz can't recognize a new Aqara Wireless Mini Switch remote.b1acn01

### ISSUE THREAD

**Issue by loglux** [domoticz/domoticz#2724]
I've got a new (International??) version Aqara Wireless Mini Switch. I managed to setup it in MiHome but Domoticz can't recognize the device and nothing showing up in the Devices List.

Instead, I can see an error message in Domoticz log:

2018-09-23 17:06:08.901 Status: XiaomiGateway: unhandled model: remote.b1acn01

**Comment by kovainfo** [comment]
https://github.com/domoticz/domoticz/pull/2725

**Comment by OnlyRinaldo** [comment]
Same problem: Status: XiaomiGateway (ID=2): unhandled model: remote.b1acn01

**Comment by loglux** [comment]
Look at the previous post from kovainfo, He has fixed it.
![aqaranewswitch](https://user-images.githubusercontent.com/37578325/46172968-e061e980-c29c-11e8-8b36-5c5270a063a7.PNG)

**Comment by kovainfo** [comment]
Fixed in beta 10022

**Comment by gizmocuz** [comment]
Please close issues when there solved...
