### ISSUE TITLE
Weather -> Forecast Button Link to 260 Broadway, New York City, NY

### ISSUE THREAD

**Issue by Dtrieb** [domoticz/domoticz#2726]
If I click on weather and the the forecast Button I get the weather from 260 Broadway, New York City, NY not from my city.

**Comment by gizmocuz** [comment]
Is your latitude and longitude correct?

**Comment by Dtrieb** [comment]
Yes it is!
![chrome_2018-09-30_18-52-34](https://user-images.githubusercontent.com/3650284/46260084-1f34b100-c4e2-11e8-86f4-5ddf297570e3.png)
![chrome_2018-09-30_18-54-00](https://user-images.githubusercontent.com/3650284/46260095-370c3500-c4e2-11e8-9709-61e37f1ecd7f.png)

**Comment by Pooj2** [comment]
The url that is requested when pushing on the forecast button is to see in the api output. See <your domotics url>/json.htm?type=devices&used=true&order=Name. Look for forecast_url. Translate the url at [https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_atob](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_atob). You will see something that starts with `https://darksky.net/#/f/<your settings>,` which always leads to the address above.

I had to make the following change to make it work in  domoticz/www/app/ForecastController.js:
Old: `			htmlcontent += '<iframe class="cIFrameLarge" id="IMain" src="//darksky.net/#/f/' + $scope.config.Latitude + ',' + $scope.config.Longitude + '"></iframe>';`
New: `			htmlcontent += '<iframe class="cIFrameLarge" id="IMain" src="//darksky.net/forecast/' + $scope.config.Latitude + ',' + $scope.config.Longitude + '/ca12/en"></iframe>';`

The /ca12/en above are my preferences, you can get your preference by pushing on the upper right buttons in the darksky.net page.

Than restart domoticz and your browser (my browser cache get cleaned), push the button and see.

Don't mind the output of the api, it will stay the same wrong or dated url.

**Comment by Dtrieb** [comment]
> The url that is requested when pushing on the forecast button is to see in the api output. See /json.htm?type=devices&used=true&order=Name. Look for forecast_url. Translate the url at https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_atob. You will see something that starts with `https://darksky.net/#/f/<your settings>,` which always leads to the address above.
> 
> I had to make the following change to make it work in domoticz/www/app/ForecastController.js:
> Old: `htmlcontent += '<iframe class="cIFrameLarge" id="IMain" src="//darksky.net/#/f/' + $scope.config.Latitude + ',' + $scope.config.Longitude + '"></iframe>';`
> New: `htmlcontent += '<iframe class="cIFrameLarge" id="IMain" src="//darksky.net/forecast/' + $scope.config.Latitude + ',' + $scope.config.Longitude + '/ca12/en"></iframe>';`
> 
> The /ca12/en above are my preferences, you can get your preference by pushing on the upper right buttons in the darksky.net page.
> 
> Than restart domoticz and your browser (my browser cache get cleaned), push the button and see.
> 
> Don't mind the output of the api, it will stay the same wrong or dated url.

Thank you that work for me!

**Comment by gizmocuz** [comment]
@Dtrieb , sorry why did you close this issue ? On the next update, that file is overwritten and it will not work anymore.

What does '/ca12/en' do ? will that work here in Europe for example ?

Maybe the /f/ call has changed and the latitude/longitude is not taken into account.

We need a global solution and a patch in the code

**Comment by Dtrieb** [comment]
Okay sorry @gizmocuz

I think only the URL changed from /f to /forecast

**Comment by mgabor-bp** [comment]
Dear All, I have tried this one:
htmlcontent += '<iframe class="cIFrameLarge" id="IMain" src="//openweathermap.org/weathermap?basemap=map&cities=true&layer=temperature&lat=' + $scope.config.Latitude + '&lon=' + $scope.config.Longitude + '&zoom=12"></iframe>'; 
but nothing changes. I also get DarkSky:
![image](https://user-images.githubusercontent.com/49124247/56591722-84b8ce00-65e9-11e9-92f2-fd48fa9d9593.png)

What can I do? Should you help me? Thanks.
