### ISSUE TITLE
Smoke sensor multigateway not working

### ISSUE THREAD

**Issue by AlbrtoSam** [domoticz/domoticz#2728]
I have some xiaomi smoke sensors which worked fine in a multigateway environment. Once the domoticz version uses multigateway support, i had several devices duplicated ( as temperature sensors...) but this sensor is not duplicated.

I still see the update messages on log:

2018-09-25 12:53:34.653 Status: {"cmd":"report","model":"smoke","sid":"158d0001e86354","short_id":25615,"data":"{\"density\":\"1\"}"}
2018-09-25 12:53:34.667 Status: {"cmd":"heartbeat","model":"smoke","sid":"158d0001e86354","short_id":25615,"data":"{\"voltage\":3085,\"alarm\":\"0\"}"}

But the item doesnt refresh or create a new one...

**Comment by kovainfo** [comment]
it's not a bug. this is due to the fact that the sensor was incorrectly registered in the system. remove the sensor and domoticz create it again.

**Comment by AlbrtoSam** [comment]
Kovainfo!!! you did the trick!. I removed the "old" sensors and some hours later, i have the new ones...

This is not the behaivour i had on my temp sensors... But it works this way. Thank you !
