### ISSUE TITLE
HTTP Message headers field case-sensitive

### ISSUE THREAD

**Issue by Fredquerty** [domoticz/domoticz#2734]
Hello, Currently the  request parser built into domoticz via LUA script is case sensitive specifically with following header " content-length " (` if( (*ph).name == "Content-Length" ) `)

if domoticz receive in the post **c**ontent-**l**ength: 124 it doesn't work
if domoticz receive in the post **C**ontent-**L**ength: 124 it works

In the rfc2616 protocole, the field names are case-insensitive ( https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2 )

could you in a post request to read the content with case-insensitive ?

thanks by advance
Fred

**Comment by gizmocuz** [comment]
Hi Fred, Yes you are right! But who is generating this ? Is it your own script ? Maybe you could tweak this.
Of course we can convert everything internally to upper/lowercase, but that takes more processing time.
As the whole RFC is writing it as "Content-Length", you would suppose any implementer would also do this
If that's not possible, i make a patch. It's the first time i hear there is a issue with it

**Comment by Fredquerty** [comment]
Hi, I modified the following LUA script "example_json.lua" in lua_parsers with my JSON. I want to use domoticz like "plateform"  to receive datas from the Sigfox backend via callback. So it is the Sigfox backend that sends the headers in lowercase (content-length). There is not script between Sigfox backend and the domoticz lua parsers. I took one week to find the problem.
it would be really nice if you can do a patch and then I could test it with my test plateform
Thanks

**Comment by Fredquerty** [comment]
Hi, Have you got any idea when you have time to make the patch for to read the content with case-insensitive ( beta version ) ?
Thanks by advance for your help

**Comment by gizmocuz** [comment]
Try beta 10023 ...
But since you correctly found the spot where it needed to be changed, feel free to make some code changes when needed to Domoticz! ;)

**Comment by Fredquerty** [comment]
Thanks it works very nice
