### ISSUE TITLE
Please add support for RFXCOM Blinds T16 Zemismart

### ISSUE THREAD

**Issue by Mart101010** [domoticz/domoticz#2735]
Please can the support be added for BlindsT16 Zemismart. It's already supported by RFXCOM but unfortunatly not in the latest Beta 4.10009

![blinds rfxcom](https://user-images.githubusercontent.com/43669046/46198269-56516980-c30c-11e8-84bb-0736e8135140.JPG)
![blinds domoticz](https://user-images.githubusercontent.com/43669046/46198279-5f423b00-c30c-11e8-8e28-d550933ea612.JPG)

**Comment by timetatime06** [comment]
Hi

**Comment by Mart101010** [comment]
I've noticed that it has been added in de beta/development version code (main/RFXNames.cpp line 662), but unfortunatly it does not show op in the type drop down menu of the latest beta version V4.10064.  Is there still something left to do?

**Comment by gizmocuz** [comment]
Needed to be added to lights.html ... not sure if it works, but in two hours there should be a new beta (10089)
Hope it works, please test

**Comment by Mart101010** [comment]
Gizmocuz,

I've tested it with version (10090) and I can confim that it works fine. 

Thank you

**Comment by gizmocuz** [comment]
Great! Thanks for the feedback !
