### ISSUE TITLE
 forum

### ISSUE THREAD

**Issue by vosnieuws** [domoticz/domoticz#2741]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version.
* Always state your version when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by gizmocuz** [comment]
What is the issue you want to report here?

**Comment by gizmocuz** [comment]
Please use the forum next time
