### ISSUE TITLE
Notifications not sent when device is updated from a script

### ISSUE THREAD

**Issue by cincuranet** [domoticz/domoticz#2742]
When a device's value is updated from a script (dzVents in my case), the notifications defined on that device are not sent. Works fine when updated using JSON API.

Tested on 4.9700 as well as 4.10022.

**Comment by gizmocuz** [comment]
what kind of device ?

**Comment by cincuranet** [comment]
Probably any. I tested it with "3-phase Amps" and "Energy" devices.

**Comment by gizmocuz** [comment]
Then it seems dzVents is directly storing values into the database and not using the internal methods to update sensors.

**Comment by cincuranet** [comment]
I don't think that's correct. It's using `UpdateDevice` command. 

For example for 3-phase Amps: 
The update is triggered here https://github.com/domoticz/domoticz/blob/development/dzVents/runtime/device-adapters/ampere_3_phase_device.lua#L15. Which ends up in here https://github.com/domoticz/domoticz/blob/development/dzVents/runtime/Device.lua#L22 and using `UpdateDevice`. That eventually ends up in regular `commandArray` (https://github.com/domoticz/domoticz/blob/development/dzVents/runtime/Domoticz.lua#L196).

**Comment by gizmocuz** [comment]
Okey, but if that calls "MainWorker::UpdateDevice", then you will get notifications.
but if this calls "CEventSystem::UpdateDevice", then it will not, it is storing the values directly in the database

I made some changes, could you test this with beta 10033 ?

**Comment by cincuranet** [comment]
I can confirm 10033 (8a17b425) has this solved.

**Comment by cincuranet** [comment]
Thanks for a quick fix. Hoping for stable soon. ;)

**Comment by gizmocuz** [comment]
Great, thanks for the feedback. Yeah it's time for a new stable, maybe shorten the version number as well ;)
