### ISSUE TITLE
Notification ignores Sound Setting at Pushover

### ISSUE THREAD

**Issue by saschaabraham** [domoticz/domoticz#2747]
I wanted silent status updates sent via pushover. I have used the DOMOTICZ.SOUND_NONE constant, but this setting is ignored. I have always the default notification sound in Pushover.
Using '&sound=none' in the extra field works.
So it seems that there is an error transferring the sound setting via the sound field in domoticz.

I have used the latest beta (4.10023)
Regards,
Sascha

**Comment by gizmocuz** [comment]
I have no idea what DOMOTICZ.SOUND_NONE is .... where is this used ?
Using &sound=none should indeed work

I guess you talk about dzVents ?

Could you post your script for others to review ?

**Comment by saschaabraham** [comment]
Yes, i used dzVents. There is a constant defined, called DOMOTICZ.SOUND_NONE which is later on converted to a SendNotification command in this way:

```
local data = subject
				.. '#' .. message
				.. '#' .. tostring(priority)
				.. '#' .. tostring(sound)
				.. '#' .. tostring(extra)
				.. '#' .. tostring(_subSystem)
		self.sendCommand('SendNotification', data)

```
Maybe this is wrong, because the wikipage for the LUA commands says this:
`commandArray['SendNotification']='subject#body#extraData#priority#sound#subsystem'`

A different order...  
I have not found the position in the source code where the sendnotifiction-command is handled, so i can not prove this.

**Comment by gizmocuz** [comment]
It's not pushover specific related i think... it's a global 'SendNotification' command, which can be found in the file EventSystem.cpp

**Comment by gizmocuz** [comment]
no response, closing issue

**Comment by saschaabraham** [comment]
Why closed?
I have shown that dzVents creates a wrong Sendcommand. (Wrong order of settings).
I didn't realise that i had to do something...

**Comment by gizmocuz** [comment]
Maybe it was closed because there was no response ? Did you make a post on the forum in the dzVents section ?

**Comment by saschaabraham** [comment]
I thought here is enough. And again, I have shown what's wrong.

**Comment by gizmocuz** [comment]
"Again", please make a post on the forum first, dzVents developers are monitoring this
You "could' have proven something, but as you've seen, 23 days, and no reaction, you could be the only one with this (possible) problem.
If you use the forum, there is a good change you get some feedback. Maybe all that needs to be done is update the wiki

**Comment by dannybloe** [comment]
I will look into this. Could be a bug.

**Comment by gizmocuz** [comment]
@dannybloe , can this issue be closed ?

**Comment by rwaaren** [comment]
Checked the command and the wiki. Working as designed and as described in the wiki. 
domoticz.notify (
                             "Sound test", 
                             "none", 
                             domoticz.PRIORITY_NORMAL, 
                             domoticz.SOUND_NONE,    
                             "",   
                             domoticz.NSS_PUSHOVER 
                          ) 
produce a silent message. Using other sound constants do produce pushover messages with sounds

**Comment by gizmocuz** [comment]
@rwaaren , thank you for looking in to this !
