### ISSUE TITLE
Evohome via web api not working - bug in EvohomeWeb.cpp?

### ISSUE THREAD

**Issue by andyjbm** [domoticz/domoticz#2748]
Hi,
So I've been having a problem connecting to Evohome via the web api using domoticz version  4.9701 on an utd debian stretch. I'm getting the error:

`2018-10-02 02:10:06.037 Status: (Evohome 103) connect to Evohome server`
`2018-10-02 02:10:06.310 Error: (Evohome 103) HTTP client error at login!`

After a quick nosey around to try and fix it (yes username/password all good etc etc) and not getting anywhere I tried the c++ version of the original python script from [https://github.com/gordonb3/domoticz-evohomeclient](url) and this worked straight out of the tin no problem.

So I did a bit more digging to see if there were more detailed logs that could be enabled to find out why the native built-in "evohome via web api" wasn't working. 

My search lead me to two lines of code in EvohomeWeb.cpp in CEvohomeWeb::login() here:
`#define EVOHOME_HOST "https://tccna.honeywell.com"`
and
`if (!HTTPClient::POST(EVOHOME_HOST"/Auth/OAuth/Token", pdata.str(), LoginHeaders, s_res))`

If we resolve the #define we get:
`if (!HTTPClient::POST("https://tccna.honeywell.com""/Auth/OAuth/Token", pdata.str(), LoginHeaders, s_res))`
which has a double quote stuck in the middle of the url string literal - from the end of the define and the start of the string literal following.
So this will compile and execute fine, but with the result that the double quote will reduce to a single quote in the resulting string variable.
Therefore my conclusion is that HTTPClient::POST is going to be passed a url string thus:
`https://tccna.honeywell.com"/Auth/OAuth/Token`
with a single quote stuck in the middle of the url. Am I reading this correctly?

To me this is never going to work? Obviously it did at some point! Maybe a previous library ignored the quote for a while and it's gone unnoticed but some other library bug has been fixed and the quote is now screwing up the call to login to the totalconnect server?

The code for the standalone evohome-client is different:
`	std::stringstream ss_url;`
`	ss_url << EVOHOME_HOST << url;`

and will compile the url string correctly.

I am away from other boxes I could try compiling on right now but I'm convinced enough to raise the question.
Am I right?

Regards,
Andy

**Comment by gordonb3** [comment]
Quick test:
```
#include <iostream>
#define EVOHOME_HOST "https://tccna.honeywell.com"
int main()
{
	std::cout << EVOHOME_HOST"/Auth/OAuth/Token" << std::endl;
	return 0;
}
```
returns `https://tccna.honeywell.com/Auth/OAuth/Token`

Unless this is platform specific I'd say the preprocessor does translate this correctly. I'm noticing though that most of the HTTP errors reported with this module occur with the last stable release. The main problem with this is that the internal HTTP client does not actually report what error occurred - it just returns that there was one. Is it an option for you to try beta?

**Comment by andyjbm** [comment]
Hi @gordonb3 
I could have a shot at beta but I'm gonna have to work out how to compile that on the box I've got the problem with. (EDIT: What am I talking about? I didn't need to compile beta - just download it.)

So I've been running domoticz on a pi with the piggyback busware scc rf board and it's been working great. Over the last 6 months my trusty openmediavault nas got an overhaul all the way up to version 4.0 . There's a domoticz plugin for OMV 4.0 so yay! more consolidation however this is the box I've got the problem with and yes it doesn't help that the HTTP client doesn't tell you what the error is.

OMV is essentially debian however your "platform specific" observation is probably where its at so I'll have a go at trying the beta on it and report back.

Thanks,

Andy.

**Comment by andyjbm** [comment]
Hi @gordonb3 
Ok progress so far..
Beta downloaded but:
`./domoticz: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

So a quick `apt-get install  libssl1.0.0 libssl-dev` was not so quick:

`Package libssl1.0.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source`

So I'm googling some more...

Andy

**Comment by andyjbm** [comment]
Hi @gordonb3 

Ok so more progress.

Libssl has moved on some in stretch so the version the beta needs is no longer available but:
`wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u9_amd64.deb`
`dpkg --install libssl1.0.0_1.0.1t-1+deb8u9_amd64.deb`

got me a working beta.
And yay! Evohome via API now logging in and pulling devices in Setup>Devices but nothing populated in temperature tab.

A quick look at the log:
2018-10-02 17:18:39.200 Status: (Evohome 103) Worker started...
2018-10-02 17:18:49.203 Status: (Evohome 103) connect to Evohome server
2018-10-02 17:18:52.752 (Evohome 103) fetch data from server
2018-10-02 17:18:52.753 (Evohome 103) Heating (EvoTouch)
2018-10-02 17:18:54.605 Status: (Evohome 103) register new zone 'Living Room'
2018-10-02 17:18:54.607 Status: (Evohome 103) register new zone 'Hall'
2018-10-02 17:18:54.608 Status: (Evohome 103) register new zone 'Kitchen'
2018-10-02 17:18:54.609 Status: (Evohome 103) register new zone 'Cellar'
2018-10-02 17:18:54.610 Status: (Evohome 103) register new zone 'Bed1'
2018-10-02 17:18:54.611 Status: (Evohome 103) register new zone 'Bed2'
2018-10-02 17:18:54.612 Status: (Evohome 103) register new zone 'Spare'
2018-10-02 17:18:54.614 Status: (Evohome 103) register new zone 'First Flr Bath'
2018-10-02 17:18:54.615 Status: (Evohome 103) register new zone 'Attic Bed'
2018-10-02 17:18:54.616 Status: (Evohome 103) register new zone 'Attic Store'
2018-10-02 17:18:54.617 Status: (Evohome 103) register new zone 'Attic Shower'
2018-10-02 17:20:55.243 Error: (Evohome 103) HTTP client error at get status!

In need of some help at this point. What next?

Thanks,

Andy.

**Comment by andyjbm** [comment]
Ok, silly me, I had to add the devices manually. In setup>devices green arrow -> etc. now a blue arrow <-
So now I have my evohome zones in the temperature tab.

But does the error 
2018-10-02 17:20:55.243 Error: (Evohome 103) HTTP client error at get status!
matter at all?

I will carry on some more with the beta.

Thanks,

Andy.

**Comment by gordonb3** [comment]
Yeah, I get that error from time to time as well. As said, the built-in HTTP client is not very verbose with regard to the type of error. It just says error, which can be anything from (temporary) DNS failure to timeout to an actual protocol (or header) error. It may also mean that the portal is down, as happened to be the case this morning.

Effectively I have no clue and since it is https it also makes very little sense to try monitor the traffic using  tools like wireshark. It's just one of those mysteries that just have to be I guess ;)

**Comment by gizmocuz** [comment]
If you enable debug logging, you will see more information why the internal HTTP client is bailing out

**Comment by andyjbm** [comment]
Ok, thanks for that @gizmocuz I'll give the debug logging a shot and see what that gives.

So regards this OP issue to conclude:

Stable didn't work, beta does so I guess whatever it was is fixed for the next release?

libssl version that beta depends on is no longer present in debian stretch maybe this needs attention? As a separate issue? Or is that just a beta thing and the next stable will be fine? Note I didn't have the libssl problem with the latest stable release.

I have a working domoticz again (thanks for your help) albeit beta and not stable but we like living on the edge. So I'm happy to close this issue if there's nothing further you think useful here.

Worked fine for most of the night then it had difficulty for an hour around 6am this morning. I guess that's when the portal was down like you said @gordonb3?

2018-10-03 06:04:25.489 Status: (Evohome 103) connect to Evohome server
2018-10-03 06:04:26.209 Error: (Evohome 103) login failed with message: Runtime Error
2018-10-03 06:06:26.233 Status: (Evohome 103) connect to Evohome server
2018-10-03 06:07:56.253 Error: (Evohome 103) HTTP client error at login!
2018-10-03 06:09:56.280 Status: (Evohome 103) connect to Evohome server
2018-10-03 06:13:58.654 Status: (Evohome 103) connect to Evohome server
2018-10-03 06:15:28.679 Status: (Evohome 103) logon fail treshold reached - trottling
2018-10-03 06:15:28.679 Error: (Evohome 103) HTTP client error at login!
2018-10-03 06:21:28.757 Status: (Evohome 103) connect to Evohome server
2018-10-03 06:21:29.307 Status: (Evohome 103) logon fail treshold reached - trottling
2018-10-03 06:29:29.407 Status: (Evohome 103) connect to Evohome server
2018-10-03 06:29:35.185 Status: (Evohome 103) logon fail treshold reached - trottling
2018-10-03 06:29:35.185 Error: (Evohome 103) login failed with message: Runtime Error
2018-10-03 06:39:35.311 Status: (Evohome 103) connect to Evohome server
2018-10-03 06:39:42.266 Status: (Evohome 103) logon fail treshold reached - trottling
2018-10-03 06:39:42.266 Error: (Evohome 103) login failed with message: Runtime Error
2018-10-03 06:51:42.430 Status: (Evohome 103) connect to Evohome server
2018-10-03 06:57:50.677 Error: (Evohome 103) HTTP client error at get status!
2018-10-03 06:59:50.704 Status: (Evohome 103) connect to Evohome server
2018-10-03 07:03:56.911 Error: (Evohome 103) HTTP client error at get status!
2018-10-03 07:05:56.936 Status: (Evohome 103) connect to Evohome server
2018-10-03 07:12:05.614 Error: (Evohome 103) HTTP client error at get status!
2018-10-03 07:14:05.642 Status: (Evohome 103) connect to Evohome server
2018-10-03 07:18:11.788 (Evohome 103) fetch data from server
2018-10-03 07:20:13.672 (Evohome 103) fetch data from server
2018-10-03 07:22:15.090 Error: (Evohome 103) HTTP client error at get status!
2018-10-03 07:24:15.117 Status: (Evohome 103) connect to Evohome server
2018-10-03 07:24:18.584 (Evohome 103) fetch data from server
2018-10-03 07:26:20.329 (Evohome 103) fetch data from server

Thanks guys,

Andy

**Comment by gordonb3** [comment]
Yes, in this message:
`2018-10-03 06:04:26.209 Error: (Evohome 103) login failed with message: Runtime Error`
the part following the colon is in fact returned by the portal itself, either in HTML or json. Looks like they had some issues with the back-end server.

**Comment by xbeaudouin** [comment]
This is not new. Evohome servers has issues all the time. If you have an "alarm" evohome, you have to pray those fscking servers works to add a new token.. Sometime it took several days to have their "cloud"(sic) working.
Really a pain in the ass. Hope one day I will use the HGI80 working (but I never figured how to make this working)...

**Comment by andyjbm** [comment]
@xbeaudouin it's worth persevering with the HGI80 or equivalent solution. I had a busware scc rf board piggybacked on a pi and it was awesome if not a tad slow as a domoticz server. 

I've moved domoticz to more grown up hardware (as mentioned above) with the downside of not being able to use the piggyback board and not being able to see the individual HR80 temps and relay info and what they're set to - missing that already after only a day of a working Evohome api approach. 

The upside to the api is that its a piece of cake to get it working! (Aside of the issues I had above!) And I'm thinking of an approach to automate the evohome schedules with domoticz (but that's for a forum topic rather than github) which I don't think can be done over honeywell RF.

Might have to see if I can hook up the serial connections on the piggyback to the new server hardware or just use the pi as a serial repeater over wifi.

The pursuit for perfection never ends...

**Comment by gordonb3** [comment]
May like to know that the web API does in fact allow backup and restore of schedules. There is currently nothing in the Domoticz part of the code that accesses the `restore` part in the base library though.

**Comment by andyjbm** [comment]
Thanks @gordonb3  I'd seen the standalone evohome-client downloads the schedule but hadn't got as far as discovering there was no provision for pushing the schedule back.

Just for the record tonight I set up another domoticz for another enthusiastic evohome friend. This time on a banana pi m2 berry (yeouch!)

The point I'm making is that we were able to set up evohome via web api on stable with no problem. Didn't need beta.

For those that don't subscribe to tldr the issues we *did* have follow:

Actually went rather well. Debian (armbian/bananian or whatever) lite stretch image.
installed domoticz using:
`curl -L install.domoticz.com | sudo bash`

domoticz complained of no python 3.
`...Python: Failed dynamic library load, install the latest libpython3.x library...` 
It needed apt-get install libpython3-dev to make it happy. No idea if that would have broken anything but fixed anyway.
Also domoticz would only listen on ipv6 even though ip4 was working and that's how we were sshing to it.
Fix for that was to disable ip6 in /etc/sysstl.conf with net.ipv6.conf.all.disable_ipv6 = 1
Well ok not really a "fix" but it got ip4 working non the less.
Setting up evohome via web api was troublefree.

So another happy domoticz subscriber joins the flock. Step two is to get his scc rf board working!

**Comment by gordonb3** [comment]
That appears to have gone lost in translation....

There are three versions of the evohome web client that I authored:
1. there is the [base library](https://github.com/gordonb3/evohomeclient)
1. there is the [python script replacement](https://github.com/gordonb3/domoticz-evohomeclient) communicating with both Evohome and Domoticz
1. there is the internal Evohome via Web API hardware class

All versions feature the schedule backup and restore functions. Both the Domoticz providers use the backup to provide the until time of the current setpoint. There is a small adjustment in the internal provider to also allow querying the corresponding setpoint from that schedule backup for direct feedback to the GUI when you cancel an override. There are a few more tiny differences, e.g. the internal provider will not allow you to set an override when heating is off - the external provider will execute it and you'll see the original setting return after the next update. Main difference is that the internal provider (which runs as a service) keeps the schedule in memory, while the external provider which is a single run instance stores this in a file.

What the base Evohome library does not provide is an add/change/delete schedule item procedure because this is beyond the scope of that project. Such functions have also not been added to the two Domoticz providers, but if someone is willing to extend the Domoticz API that might be something for the future.

The external Domoticz provider does in fact allow write back (restore) of the schedule. The base library also contains two samples that do both backup and restore.


BTW Clueless about why it works with stable on a banana pi and not on other systems (including pi3 I've been told).

**Comment by andyjbm** [comment]
Hi gordonb3
Ok thanks for that detail. Very useful. My use case for automating changing schedules as an example would be when my kids pop home from university. Their rooms each have a schedule for when they're home and when they're away. By detecting they're home (their phone just connected to wifi for example) the "away" schedule can be switched for the "at home" schedule.

> 2. there is the python script replacement communicating with both Evohome and Domoticz

Ok. This is what I used as mentioned in the OP to get domoticz/evohome working when the "evohome via web api" hardware device didn't work. I noticed that it had created a file called schedule.something and assumed it would be able to post a modified file back to honeywell.

>The external Domoticz provider does in fact allow write back (restore) of the schedule. The base library also contains two samples that do both backup and restore.

Ok that's even better. So I could do it the way I first thought? I'd be backing up the whole schedule as far as the provider/honeywell API is concerned and then editing the schedule file somehow some place else, then pushing it back as a restore.

>What the base Evohome library does not provide is an add/change/delete schedule item procedure because this is beyond the scope of that project. 

The whole concept of scheduling schedules (or even just changing them under automation) gets very complicated very quickly so I'm not surprised! I've not given it any serious thought yet. Moving domoticz to the NAS was the first step in that direction.

>BTW Clueless about why it works with stable on a banana pi and not on other systems (including pi3 >I've been told).

I could switch back to stable and see if I can enable debug logging and get some more info if that would help? Or was the problem that the stable release HTTP client does not have that debug logging detail but the beta does? I think I did try `-loglevel=debug` as a command line switch but it didn't give any more detail in the log. I was struggling to find UTD info on how to use the loglevel / logdetail / verbose switches which is what led me to the source code in the first place.

**Comment by gordonb3** [comment]
Actually changing the schedule would be childishly simple because it's just a few lines of json. You also don't need to restore all zones to change the schedule on a single zone, because they actually do need to be loaded individually.

Having some kind of error message might be nice. Looking at the code it seems to depend on where the error occurs whether you will ever see one though. Debug appears to concentrate on HTTP return errors.

**Comment by bertoost** [comment]
Still not working here.. 

```
2020-05-05 12:50:38.375 Status: (Evohome) Worker started...
2020-05-05 12:50:48.376 Status: (Evohome) connect to Evohome server
2020-05-05 12:52:48.575 Status: (Evohome) connect to Evohome server
2020-05-05 12:54:48.759 Status: (Evohome) connect to Evohome server
```

Even tried creating a new account at the honeywell portal

**Comment by rwaaren** [comment]
I cannot replicate this issue on my systems. 
I have not seen any problems with Evohome via WEB API in the last 12 months apart from occasional downtime for maintenance on my- or Evohome side.

Not with domoticz on Synology, domoticz on RPI-3B (stretch and buster) and no problems since I moved to Intel NUC (Also Debian Buster). All on more or less latest domoticz Beta versions

Would be interesting to see what the difference in setup is.

**Comment by bertoost** [comment]
Maybe it's because I am using the Docker image on a RPI3? 
I'm using the image described in the docs here; https://www.domoticz.com/wiki/Docker

**Comment by dannybloe** [comment]
The plugin in Domoticz is kind of broken for many. Gordon forked the code into his own repo and fixed the problem. I'm not good enough with C++ but maybe someone can port the necessary fixes. 
`https://github.com/gordonb3/oikomaticz/blob/master/src/hardware/Honeywell/EvohomeWeb.cpp`

**Comment by waltervl** [comment]
@dannybloe Is this still an issue?

**Comment by bertoost** [comment]
The API is functioning now for me.

**Comment by andyjbm** [comment]
> @dannybloe Is this still an issue?

Hi, @dannybloe,

The original issue was fixed for me with the beta in 2 Oct 2018.

The subsequent issues others commented I do not know. By that time I'd moved from the evohome webapi to RF data collection which gives much more info for me.

So closed for me thanks.

Andy.
