### ISSUE TITLE
[Issue/Feature suggestion] - Yeelight ceiling light

### ISSUE THREAD

**Issue by adrianmihalko** [domoticz/domoticz#2749]
//cc @emontnemery 

**Issues:**

- In iPhone's Homebridge (HomeKit) color changing feature is missing, there is only brightness/on/off.

- Moving cursor to the to the top, it does not change light at all. Little bit lower it works, it changes to yellow.

Not working:
<img width="424" alt="46036494-e5406500-c105-11e8-8abf-34e9680ad083" src="https://user-images.githubusercontent.com/733361/46343662-cfb7c780-c63e-11e8-8845-b6d012709458.png">

Works until this:

<img width="411" alt="46036506-ec677300-c105-11e8-84d1-7a0273ab7615" src="https://user-images.githubusercontent.com/733361/46343689-e100d400-c63e-11e8-9da7-fabf3730667f.png">

**Feature suggestion:**

It would be great to make Yeelight plugin work like in Home Assistant. In HA it updates itself with light value (color + light status) even when I turn it on via Yeelight app/other control. In Domoticz, Yeelight switch changes only when I control trough Domoticz. In HA even the icon color is representing the actual color temperature of the light, but I don't think that this would be possible in Domoticz.

<img width="573" alt="46310645-33e77680-c5c0-11e8-8456-2cf669679544" src="https://user-images.githubusercontent.com/733361/46343704-ecec9600-c63e-11e8-9659-6da4f34cbdb2.png">

- It would be nice to integrate Moonlight mode: https://forum.yeelight.com/t/enable-moonlight-of-yeelight-ceiling-with-api/1182

**Comment by emontnemery** [comment]
> In iPhone's Homebridge (HomeKit) color changing feature is missing, there is only brightness/on/off.

Please report this as bug on Homebridge

> Moving cursor to the to the top, it does not change light at all. Little bit lower it works, it changes to yellow.

Domoticz assumes all yeelights support color temperatures 1700..6500K, but according to yeelight API:
`"CT": Current color temperature value. The range of this value depends on product model,
refert to Yeelight product description. This field is only valid if COLOR_MODE is 2.`
What yeelight model do you have where this is not working?
Let's see if there's some way to understand valid color temperature, I can provide a debug build.
Are you running Domoticz on Raspberry Pi?

> It would be great to make Yeelight plugin work like in Home Assistant. In HA it updates itself with light value (color + light status) even when I turn it on via Yeelight app/other control. In Domoticz, Yeelight switch changes only when I control trough Domoticz.

Is at least light status (on/off/dim level) working in Domoticz, or is it not working at all?

> It would be nice to integrate Moonlight mode: https://forum.yeelight.com/t/enable-moonlight-of-yeelight-ceiling-with-api/1182

The information in the forum is not aligned with API documentation: https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf, but let's give it a try.

**Comment by adrianmihalko** [comment]
Hi emontnemery, 

in the meantime I completely switchted to HomeAssistant and I can't test these functions anymore. :( I am closing this issue, if any Domoticz user have this issue, please open a new ticket.
