### ISSUE TITLE
WiringPi library not found. GPIO support disabled.

### ISSUE THREAD

**Issue by Alkarex** [domoticz/domoticz#275]
Hello,
It looks like the instructions for using WiringPi on Raspberry Pi are outdated.

I followed https://www.domoticz.com/wiki/GPIO and http://wiringpi.com/download-and-install/ (and also looked at https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI ) and during the cmake, Domoticz cannot find the WiringPi library:

```
cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt
...
-- Building on Raspberry Pi... (bcm_host.h found in /opt/vc/include)
-- WiringPi include was found in /usr/include...
-- ==== WiringPi library not found. GPIO support disabled.
-- ==== (Please follow http://wiringpi.com/download-and-install/ if you want to use GPIO.)
```

I tried to install WiringPi with a manual compilation:

``` sh
git clone git://git.drogon.net/wiringPi
cd wiringPi
./build
```

or with the Raspbian package:

``` sh
sudo apt-get install wiringpi
```

with the exact same result.

It seems to be related to this forum thread https://www.domoticz.com/forum/viewtopic.php?f=47&t=7678 but the suggested static build process does not work anymore with the current distribution of WiringPi, and anyway, linking against the static version of WiringPi does not seem to be the easiest way (for installers) as it does not get installed by default:

```
cd wiringPi
make static
make: *** No rule to make target 'static'.  Stop.
```

Any update on the current approach for enabling GPIO?

**Comment by gizmocuz** [comment]
You could use the SD card image...

**Comment by Alkarex** [comment]
@gizmocuz Then CMakeLists.txt needs to be updated to say "stop there and grab an image" ;-)
My own system is working fine; the point of this issue is to report that both the documentation and CMakeLists.txt are buggy.

**Comment by Alkarex** [comment]
P.S. User [stamppot](https://www.domoticz.com/forum/viewtopic.php?f=47&t=7678#p54660) is proposing to help with a patch, but the static/dynamic strategy needs to be decided.

**Comment by Alkarex** [comment]
P.P.S: I am happy to contribute e.g. documentation patches if it can help.

**Comment by jvandenbroek** [comment]
I had the same problem, worked around it by symlinking libwiringPi.a to libwiringPi.so (or the other way around).

**Comment by Alkarex** [comment]
Thanks for the tip, @jvandenbroek :+1: 
Maybe this could be added to the documentation, while waiting for something better.

**Comment by gizmocuz** [comment]
You have to build the static libraries

**Comment by jvandenbroek** [comment]
Well, I thought the same, but somehow it works without the static library build? Building succeeds and GPIO is working fine with just symlinking to the dynamic lib?? Maybe some intelligent linking system doing its magic..

**Comment by gizmocuz** [comment]
as stated above, please compile as a static lib, symlinking is not a good idea, sure it could work
