### ISSUE TITLE
GUI logpage does not show graphs for Watermeter

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#2750]
PI debian stretch  / Windows 10
V4.10032 and earlier 
V4.10009 and before are OK

GUI logpage does not show graphs for Watermeter 
Data is still in the database and can be accessed via JSON-API call
http://IP:PORT/json.htm?type=graph&sensor=counter&idx=IDX&range=year (or day or week or month) does return the data
Browser cache and appcache cleared and double checked with different themes and domoticz restart

http://www.domoticz.com/forum/viewtopic.php?f=6&t=25113

datatable for last week:

2018-09-25 00:00:00	NaN
2018-09-26 00:00:00	NaN
2018-09-27 00:00:00	NaN
2018-09-28 00:00:00	NaN
2018-09-29 00:00:00	NaN
2018-10-01 00:00:00	NaN
2018-10-02 00:00:00	NaN

JSON call for next week

"ValueQuantity": "",
"ValueUnits": "",
"result": [
{
"d": "2018-09-25",
"v": "0.220"
},
{
"d": "2018-09-26",
"v": "0.330"
},
{
"d": "2018-09-27",
"v": "0.450"
},
{
"d": "2018-09-28",
"v": "0.360"
},
{
"d": "2018-09-29",
"v": "0.290"
},
{
"d": "2018-10-01",
"v": "0.410"
},
{
"d": "2018-10-02",
"v": "0.300"
}
],
"status": "OK",
"title": "Graph counter week"
}

**Comment by gizmocuz** [comment]
Using version 10023 and i see no issues

![image](https://user-images.githubusercontent.com/2265299/46354419-d8b89100-c65e-11e8-82a9-139cbddd1e3f.png)

You have not a single chart ? no day/week/month or year ? Looks something is wrong with the data in the database. Is this generated by a script ?

**Comment by rwaaren** [comment]
No single chart. All date available in databasetables deviceStatus, Meter and Meter_Calendar 
also readable using JSON.
Data is generated by a json since 22/10/2017 (curl "http://IP:PORT/json.htm?type=command&param=udevice&idx=982&svalue=nnnn 
Issue was reported in forum by mrelfire (on windows 10 V4.10030/ I am on RPI V4.10032)

**Comment by gizmocuz** [comment]
json command looks correct, could you contact me on the forum ? i would like to debug with your database, if you already known my email, please send me a copy with a link to this issue plz

**Comment by gizmocuz** [comment]
Also check in the Meter_Calendar database table if you have day records for your water meter

**Comment by Mart101010** [comment]
I have the same issue with the GUI logs when using Firefox. With Chrome it is working well. But watermeter is not working with both browsers

**Comment by LouiS22** [comment]
Have the same issue as above. No graphical data in browser. I'm on latest beta (10033). Data should be present as I can see the daily consumption and total consumption, but no graphical display (charts) at all.

**Comment by rwaaren** [comment]
> json command looks correct, could you contact me on the forum ? i would like to debug with your database, if you already known my email, please send me a copy with a link to this issue plz

Sent you a PM on the forum

**Comment by gizmocuz** [comment]
Problem seen now here as well, thanks for reporting...
(Working on custom dividers per meter)

Seems $.DividerWater in domoticz.js is undefined. If i set this to 1000, the graph is back... continuing debugging..
.. fixed in upcoming beta

**Comment by rwaaren** [comment]
Fixed
