### ISSUE TITLE
P1 smart meter values broken

### ISSUE THREAD

**Issue by twpeltenburg** [domoticz/domoticz#2753]
Since the latest beta the power usage decimals are broken:

![power usage](https://user-images.githubusercontent.com/43619543/46436511-4517bb00-c759-11e8-8719-01ea3ab4ad5c.PNG)

also the gas usage decimals are broken:

![gas usage](https://user-images.githubusercontent.com/43619543/46436593-86a86600-c759-11e8-9eb9-67583b86ae72.PNG)

**Comment by arnemauer** [comment]
Same here... a lot of NaN and calculation of totals is going wrong.

![domoticz meter error](https://user-images.githubusercontent.com/268051/46585102-8e734d80-ca6c-11e8-9e26-998b9a2198fb.PNG)

**Comment by sweetpants** [comment]
There where some changes in this area in commit https://github.com/domoticz/domoticz/commit/600cb678cfa86f1ddfacfdb62c316c710f8ca1ca, This can happen wit Beta versions. If you compiled from source you can revert to commit https://github.com/domoticz/domoticz/commit/b2ba312ac81f955a5930b687c8d4fafd93ade324

**Comment by gizmocuz** [comment]
I don't think any wrong values are stored in the database, but it is 'possible' calculated wrong.
The idea is to have a custom meter divider per meter (for electricity the default is 1000)

**Comment by gizmocuz** [comment]
@sweetpants , ehmmm are you sure it is caused by the above code change ?

**Comment by gizmocuz** [comment]
@sweetpants , i think it is caused by https://github.com/domoticz/domoticz/commit/2dd17686ceff46519cfa62cd4668d757a03fee61

**Comment by gizmocuz** [comment]
@twpeltenburg , in the new beta this has been reverted

**Comment by twpeltenburg** [comment]
> @twpeltenburg , in the new beta this has been reverted

Is that V4.0039? Cause that won't download. Not through the web interface or via sudo ./updaterelease. I get the following error message: 

ERROR WHILE DOWNLOADING UPDATE,
CHECK YOUR INTERNET CONNECTION OR TRY AGAIN LATER !...

Internet connection is OK. I have powercycled the pi repeatedly.

**Comment by twpeltenburg** [comment]
Awesome

**Comment by stas-demydiuk** [comment]
@arnemauer could you please clarify if the all data in table is correct and issue is only in the summary calculations (above the table)? Or there are some issues with data in table as well?

**Comment by gizmocuz** [comment]
From what i noticed it was only the summary above.
There was also another change, but maybe that happened earlier...
I coded it once... that when someone who does not have any solar panels (no return), these values are not displayed. Not in the summary, but also the columns in the table where removed
