### ISSUE TITLE
Debian 9 Stretch / PC AMD64 / Libssl1.0.0 not available

### ISSUE THREAD

**Issue by ALROCHARARI** [domoticz/domoticz#2754]
Do you plan to update Domoticz to support latest Libssl version as no LibSSL1.0.0 version is available for Domoticz in Debian Stretch 9 in 64bits ?
Tried to find the subject in the other issues but did not found it.

**Comment by gizmocuz** [comment]
Cant you install a previous one ? Did you try to compile domoticz by source ?

**Comment by Porzeczek** [comment]
@ALROCHARARI 
Did you try to install libssl1.0.2?
`apt-get install libssl1.0.2`

**Comment by gizmocuz** [comment]
@ALROCHARARI , any feedback would be great after 2 weeks

**Comment by ghost** [comment]
Hello,

try that :

```
git clone https://github.com/domoticz/domoticz.git
cd domoticz
git checkout tags/4.9700
make -j4
systemctl restart domoticz.service
```
for update do to directory and 

```
cd domoticz
git pull
git checkout tags/4.9700 #can be new tag
make -j4 
```

**Comment by gizmocuz** [comment]
@mmaura66 , why would you want to checkout 9700 ? thats rather old

**Comment by rremy** [comment]
> @ALROCHARARI
> Did you try to install libssl1.0.2?
> `apt-get install libssl1.0.2`

I tried, but unfortunately that's not the same.
After installing libssl1.0.2 the error message is same as before.
"error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory"

**Comment by rremy** [comment]
If you would like to run on debian 9, you can download the libssl1.0.0 from the debian packages website:
https://packages.debian.org/jessie/libssl1.0.0
after download you can install it with dpkg -i <filename.deb>

**Comment by ghost** [comment]
> 
> 
> @mmaura66 , why would you want to checkout 9700 ? thats rather old

because I thought the tags were used to indicate stable versions

**Comment by gizmocuz** [comment]
@mmaura66 , thats correct, but i consider the beta's quite stable... and in beta versions stuff is fixed...
