### ISSUE TITLE
custom range api call for 'counter' sensor faulty value calculation

### ISSUE THREAD

**Issue by Jzz81** [domoticz/domoticz#2756]
When calling the api for an energy meter (P1 power meter) with a custom range set like so:
`/json.htm?type=graph&sensor=counter&idx=47&range=2018-10-01T2018-10-04`
The result values are faulty. Inspection of 'WebServer.cpp' in the code base showed a mix-up of usage and delivery values like below (line number 16598 and onwards):
```
float fUsage = (float)(atof(szUsage1.c_str()) + atof(szUsage2.c_str()));
float fDeliv = (float)(atof(szDeliv1.c_str()) + atof(szDeliv2.c_str()));

if (fDeliv != 0)
	bHaveDeliverd = true;
sprintf(szTmp, "%.3f", fUsage / divider);
root["result"][ii]["v"] = szTmp;
sprintf(szTmp, "%.3f", fDeliv / divider);
root["result"][ii]["v2"] = szTmp;
```
Fault is in the last 2 lines, where the 'fDeliv' variable is assigned to the 'v2' parameter, generally used for 'Usage_2'.

The usage and delivery values are added-up (first 2 lines) to create 2 values, instead of keeping the original 4 values available (reason unknown).

Suggested fix is to use the same code for the 'year/month' range, with 2 usage and 2 delivery variables, like so:
```
float fUsage_1 = static_cast<float>(atof(szUsage1.c_str()));
float fUsage_2 = static_cast<float>(atof(szUsage2.c_str()));
float fDeliv_1 = static_cast<float>(atof(szDeliv1.c_str()));
float fDeliv_2 = static_cast<float>(atof(szDeliv2.c_str()));

fDeliv_1 = (fDeliv_1 < 10) ? 0 : fDeliv_1;
fDeliv_2 = (fDeliv_2 < 10) ? 0 : fDeliv_2;

if ((fDeliv_1 != 0) || (fDeliv_2 != 0))
	bHaveDeliverd = true;

sprintf(szTmp, "%.3f", fUsage_1 / divider);
root["result"][ii]["v"] = szTmp;
sprintf(szTmp, "%.3f", fUsage_2 / divider);
root["result"][ii]["v2"] = szTmp;
sprintf(szTmp, "%.3f", fDeliv_1 / divider);
root["result"][ii]["r1"] = szTmp;
sprintf(szTmp, "%.3f", fDeliv_2 / divider);
root["result"][ii]["r2"] = szTmp;
```

Can make a bugfix / Pull request for this if needed.

**Comment by gizmocuz** [comment]
Thanks for your report. I don't think it is faulty, the result returns two values, usage and delivery, both "tarrif 1" and "tarrif 2" have been combined in one value
What do you mean exactly with "The result values are faulty" ? Could you post a log ?
These values are (also) used for the graphs i think

**Comment by Jzz81** [comment]
I think you are right. The values are not so much faulty but the combined values were unexpected. Furthermore the 'v2' parameter is a parameter generally used for Usage_2.
Is there a specific reason that the tarrif 1 and tarrif 2 values are combined (and v2 is used for Delivery in this case)?

Getting into this issue, I found another glitch. The code calculates the values for 'today' seperately. For 'week' and 'month' this is good, but in a custom range, it is possible that 'today' is not part of the range. The code does not check that, and always calculates and shows the today values.

**Comment by gizmocuz** [comment]
The call/result is used for the graphs inside the gui.
"v1" = value_1, "v2" = value_2 , whatever they contain, for water/energy/percentage/temp, they are all different.
It seems you want to have more details back, that can be arranged. We could extend the API call with a flag like "details=1" (or similar)
About 'today', that is only happening when your range is inside the short-log range, best to check the code (webserver.cpp, for example like 16400 for temp)
Feel free to check the code and make changes, but make sure that the graphs/reports are still working correctly in the gui

**Comment by Jzz81** [comment]
Thanks for the pointers. I did not realize that the graphs in the gui uses the same code. Seems rather logical.
I am not experienced in c++ coding, but I will try to make some changes to the code. I will keep an eye on the graphs in testing. 

About the 'today' issue; I don't really understand what you mean with short-log range. I will investigate the Webserver.cpp file for temp like you said, but if I use the 'counter', the results are not good. If the custom range includes today, for example: `range=2018-10-12T2018-10-15`, the result is as expected, but if it does not include today, for example `range=2018-10-12T2018-10-14`, the last day (in this case, yesterday) is displayed twice, but with some other values (not the values of the 14th, but also not the values of today). This also happens when you use a range from longer ago, for example from 2 months ago, like so: `range=2018-08-12T2018-08-14`. The 14th is displayed twice, with some values (same as in the other example).
This all happens on my production machine (stable release 4.7900 on FreeBSD)(FreeNas acually, but it uses the FreeBSD ports).

I think this is what triggered me to open an issue and call the values 'faulty'. If you include today in the range, the results are nog faulty. If you do not, they are.

I will investigate what exacly happens and if I can solve it.

**Comment by gizmocuz** [comment]
@Jzz81 , we have to kinds of logs in the database, a short-log (5 minute values, default kept for 48 hours), and day values (calendar table)

**Comment by gizmocuz** [comment]
Closing issue for now
