### ISSUE TITLE
Allow dynamically linking libjsoncpp and tinyxml

### ISSUE THREAD

**Issue by FedericoCeratto** [domoticz/domoticz#2758]
libjsoncpp and tinyxml are statically linked. Adding ability to dynamically link them would be good for security and packaging.

Related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=899058

**Comment by gizmocuz** [comment]
I don't see any json/tiny text reference on that web page ?

**Comment by FedericoCeratto** [comment]
The related bug is simply there to track the packaging effort.

**Comment by FedericoCeratto** [comment]
The related bug is simply there to track the packaging effort.

**Comment by gizmocuz** [comment]
Those libraries are extreme small and are compiled in real-time.
Also windows users needs to be updated when there is a possible security issue, and that will NOT happen when it is externally linked on other platforms.
So best to patch those files in domoticz, and that 10KB overhead of code is not a problem

**Comment by FedericoCeratto** [comment]
FYI the request is not related to binary size but security. Shared libraries receive security updates independently and requires no rebuild/deploy of domoticz.

**Comment by gizmocuz** [comment]
Yes, see my comment above why i do not prefer to have this as shared library
