### ISSUE TITLE
RGB Color Change via API triggers switch "Off Action"

### ISSUE THREAD

**Issue by tom87** [domoticz/domoticz#2759]
Version: 4.10039

Im changing the colors of my RGB device (z-wave, Fibaro RGBW Controller) via API calls.
Since the RGB support got extended to support RGBW and I think some other options this issue seems to exist.

Whenever I'm calling the api to change the color:
/json.htm?type=command&idx=221&param=setcolbrightnessvalue&hex=8B0000&brightness=100&iswhite=false

the "Off Action" of the switch is triggered, and by that I mean the http site that is defined in the switch settings under "Off Action" is called. I have also defined an "On Action" but it is not called in this instance.

**Comment by gizmocuz** [comment]
So you say, when setting the color/brightness for a RGB/W switch , it is using the OFF action instead of the ON action

**Comment by gizmocuz** [comment]
Fixed in beta 10051 (available within an hour), thanks for reporting!
