### ISSUE TITLE
Update Mysensor TempHum Error

### ISSUE THREAD

**Issue by Spugna85** [domoticz/domoticz#276]
Hi,
 I have a Mysensor physical node (Arduino) with 6 sensor DHT22.
So I have 12 values, 6 temperature and 6 humidity, so listed:
-Sensor0 (ID=0501): H0 (IDCHILD = 0), T0 (IDCHILD  = 1)
-Sensor1 (ID=0503): H1 (IDCHILD  = 2), T1 (IDCHILD  = 3)
-Sensor2 (ID=0505): H2 (IDCHILD  = 4), T2 (IDCHILD  = 5)
-Sensor3 (ID=0507): H3 (IDCHILD  = 6), T3 (IDCHILD  = 7)
-Sensor4 (ID=0509): H4 (IDCHILD  = 8), T4 (IDCHILD  = 9)
-Sensor5 (ID=050B): H5 (IDCHILD  = 10), T5 (IDCHILD  = 11)

Domoticz create 6 sensor (Model:Temp + Humidity, subtype:WTGR800).

Each update temperature (T0 to T5) correctly updates the sensor device in the table.
Example:
T0 updates the temperature of the first sensor (ID: 0501)
T1 updates the temperature of the second sensor (ID: 0503)
and so on...

While each update of humidity (H0 to H5) always updates the first sensor for the node.
Example:
H0 refresh the humidity of the first sensor (ID: 0501)
H1 refresh the humidity of the first sensor (ID: 0501)
and so on...

I think that the problem is that Domoticz use "IDCHILD" temperature as the sensor address for Model "Temp + Humidity" and uses the default 0 to update the humidity.

So, if I have more sensors, any humidity variation on one of them, generates an incorrect update of the first sensor and a missing update of another sensor.

What do you think?

**Comment by gizmocuz** [comment]
Could you set the temp+hum both on the same child id, for all sensors?

DTH1: (child id 0 for both temp+hum)
DTH2: (child id 1 for both temp+hum)
...
DTH5: (child id 4 for both temp+hum)

**Comment by Spugna85** [comment]
Now I just tried this:
Sensor0 (ID=0500): H0 (IDCHILD = 0), T0 (IDCHILD = 0)
Sensor1 (ID=0501): H1 (IDCHILD = 1), T1 (IDCHILD = 1)
...
Sensor5 (ID=0505): H5 (IDCHILD = 5), T0 (IDCHILD = 5)

And yet I can see the same behavior: 
each update of humidity, always updates only the first sensor (in this case ID=0500).

Unfortunately, this solution does not seem to solve the problem :(

**Comment by gizmocuz** [comment]
Looking at the code I can confirm this does not work....
Maybe we should make a function that checks for a temp (or hum) or (baro) close to the current child id
not so easy as It looks I think

**Comment by Spugna85** [comment]
I can see that domoticz always assigns the "child id temp" to sensor "temp
- hum". You could do a background check on receipt of an humidity update,
  if the child id equals "child id temp" - 1, you can assign it to the
  correct sensor. it's just an idea, maybe it is possible ... alternatively
  would be useful to recognize humidity and temperature sensors as 2
  different, what do you think?
  Il 02 gen 2016 1:27 AM, "gizmocuz" notifications@github.com ha scritto:

**Comment by gizmocuz** [comment]
it could be + or - one, but that's indeed what I was thinking about

**Comment by Sevift** [comment]
And what if
_tMySensorChild *pChildHum = FindChildWithValueType(pChild->nodeID, V_HUM, (pChild)->childName);

and

MySensorsBase::_tMySensorChild\* MySensorsBase::FindChildWithValueType(const int nodeID, const _eSetType valType, const std::string childName)
...
for (itt = pNode->m_childs.begin(); itt != pNode->m_childs.end(); ++itt)
    {
        if (itt->childName == childName)

because
#define Location "qwerty"
gw.present( Motion_CHILD, S_MOTION, Location );
gw.present( Humidity_CHILD, S_HUM, Location );
Location it childName

**Comment by gizmocuz** [comment]
That is if you name your nodes/childs, as is not the case for a lot of users

**Comment by guiguid** [comment]
Hi,
We can mix the both solutions above : 
 **first** : check for an indentical descrition (My sensor presentation code : 
`void present(uint8_t childSensorId, uint8_t sensorType, const char *description, bool ack);`
with : **description** as an optional textual description of the attached sensor.

**second** : if first failed : increment an internal counter for each temp CHILD_ID, an merge HUM, BARO ... with the current internal temp CHILD_ID

Example: 

My SENSOR : 
present (IDCHILD = 0) TEMP, "SENSOR1"
present (IDCHILD = 1) TEMP
present (IDCHILD = 2) HUM
present (IDCHILD = 3) HUM, "SENSOR1"
present (IDCHILD = 4) TEMP
present (IDCHILD = 5) TEMP
present (IDCHILD = 6) HUM

DOMOTICZ : 
-Sensor0 : TEMP (IDCHILD = 0), HUM (IDCHILD = 3) ( by description)
-Sensor1 : TEMP (IDCHILD = 1), HUM (IDCHILD = 2)
-Sensor2 : TEMP (IDCHILD = 4) 
-Sensor3 : TEMP (IDCHILD = 5), HUM (IDCHILD = 6)

Feature : 
- no modification on MySensor protocol
- don't break compatibility with old sensors
- easy to code

**Comment by gizmocuz** [comment]
you can not go out from a textual description, as this is not implemented in most sketch examples
... yes you can modify the sketches, but then you can also modify the sketches to solve problems

So i quess we should support this combination?

My SENSOR : 
present (IDCHILD = 0) TEMP //temp sensor 1
present (IDCHILD = 1) TEMP //temp+hum sensor 1
present (IDCHILD = 2) HUM
present (IDCHILD = 3) TEMP //temp+hum sensor 2
present (IDCHILD = 4) HUM
present (IDCHILD = 5) TEMP //temp sensor 2
present (IDCHILD = 6) TEMP //temp+hum sensor 3
present (IDCHILD = 7) HUM
present (IDCHILD = 8) HUM //hum sensor 1
present (IDCHILD = 9) HUM //hum sensor 2
present (IDCHILD = 10) TEMP //temp sensor 3

If you agree, could you make a pull request ? (maybe create a mysensors test branch?)

**Comment by BmdOnline** [comment]
Hi,

The goal is to add a group ID for each node's child (we can discuss for a good method, I'll explain mine below).
Then, when we need to find a child to combine with (FindChildWithValueType calls from SendSensor2Domoticz), we have to restrict this search to the group ID.

To do this, my method will be :
First, add "groupID" property in _tMySensorChild struct (MySensorsBase.h).
Then, when adding a new child in mNode.m_childs collection, we have to assign his groupID (see below).
Finally, we can use this groupID later, in FindChildWithValueType function. To do this, we have to add a new parameter to the function (called valGroup, identifying requested group).

The complex part is to identify groups.
Maybe later, we can add a new interface in MySensor Node setup to manually assign group. Maybe later...

For now, when reading childs from database (LoadDevicesFromDatabase), we only have to increment groupID when an sensor type already exists in current groupID.

For example :

```
present (IDCHILD = 0) TEMP  // groupID 1
present (IDCHILD = 1) TEMP  // groupID 2
present (IDCHILD = 2) HUM   // groupID 2
present (IDCHILD = 3) TEMP  // groupID 3
present (IDCHILD = 4) HUM   // groupID 3
present (IDCHILD = 5) TEMP  // groupID 4
present (IDCHILD = 6) TEMP  // groupID 5
present (IDCHILD = 7) HUM   // groupID 5
present (IDCHILD = 8) HUM   // groupID 6
present (IDCHILD = 9) HUM   // groupID 7
present (IDCHILD = 10) TEMP // groupID 7
```

Note : Childs 9 and 10 are presenting HUM before TEMP, but they are in the same group.

Another example :

```
present (IDCHILD = 0) TEMP, "SENSOR1" // groupID 1
present (IDCHILD = 1) TEMP            // groupID 2
present (IDCHILD = 2) HUM             // groupID 2
present (IDCHILD = 3) HUM, "SENSOR1"  // groupID 3
present (IDCHILD = 4) TEMP            // groupID 3
present (IDCHILD = 5) TEMP            // groupID 4
present (IDCHILD = 6) HUM             // groupID 4
```

Note : Childs 3 and 4 are presenting HUM before TEMP, HUM is named "SENSOR1", but they are in the same group.

Last example, with other sensors :

```
present (IDCHILD = 0) TEMP  // groupID 1
present (IDCHILD = 1) TEMP  // groupID 2
present (IDCHILD = 2) HUM   // groupID 2
present (IDCHILD = 3) WIND  // groupID 2
present (IDCHILD = 4) HUM   // groupID 3
present (IDCHILD = 5) TEMP  // groupID 3
present (IDCHILD = 6) RAIN  // groupID 3
present (IDCHILD = 7) WIND  // groupID 3
present (IDCHILD = 8) TEMP  // groupID 4
present (IDCHILD = 9) HUM   // groupID 4
present (IDCHILD = 10) TEMP // groupID 5
```

Note : RAIN, WIND and other sensors are treated exactly like TEMP, HUM...
We attach them to their respective groupID.
I think it's not a problem.

With this method, we have to determine groupID once when loading database. Then we don't have to repeat this work.
And later, we can imagine an interface for manual assign groupID and add them to database.

What do you think about this ?

**Comment by BmdOnline** [comment]
Hi,

I have tried to implement it. Seems good.
I will verify my code and try to pull changes.

**Comment by handfreezer** [comment]
Hello,

  What you've done is just amazing as I was looking for the way how groupID works in mysensors with hum and temp.

  May I do a suggestion : as you are proposing to add an interface to change groupID, but not for now, could you just add a global option that unactivate grouping child_id for a MySensor Gateway (Serial or LAN)?

So, the result could be something like:
present (IDCHILD = 1) TEMP             // groupID 1
present (IDCHILD = 2) HUM             // groupID 2
present (IDCHILD = 3) HUM            // groupID 3
present (IDCHILD = 4) TEMP            // groupID 4

**Comment by BmdOnline** [comment]
Hi,
I don't know enough domoticz code structure for improve MySensors configuration interface without side effect.
So, I prefer leave it.

Maybe gizmocus can add an option to enable / disable grouping.

**Comment by gizmocuz** [comment]
This should already been taken care of... see the forum thread about mysensors/grouping
you have to adjust your id's

**Comment by jonasengs** [comment]
Hi!

Unfortunately this update doesn´t work very well with my setup.. As you can see in the picture the first are ok to group, but the rest need to be separated.

![screen shot 2016-12-12 at 19 56 12](https://cloud.githubusercontent.com/assets/24530029/21112196/22ba73e8-c0a5-11e6-81df-73b5a3a52bed.png)

I´ve read the forum posts about grouping, but can´t find a method to get them separated.. How do I accomplish that? 

regards

**Comment by jonasengs** [comment]
Answer to my question:
I found a workaround by naming all sensors v_hum - then they are placed in different groups and are possible to work with in domoticz...

I tried with v_var1 and v_voltage but they all ended up in the same groups. 

I can see some solutions:
- grouping would be triggered on all v_.. the same way as for v_hum and v_temp
- be able to edit groups in the hardwaretab - seems to me that it would be possible in the same way that you can edit timeout now?

these are just suggestions, I have too little knowledge myself to make them real..

thanks for a super plattform! I feel som happy to get rid of vera and its stupid UI!

**Comment by palmerfarmer50** [comment]
Does anyone have an example of this code? Still struggling to get two of these working
