### ISSUE TITLE
MySensors S_IR Playback Device cannot send commands

### ISSUE THREAD

**Issue by lamptah** [domoticz/domoticz#2764]
Using most recent beta V4.10039

I was building an IR node for MySensors over the weekend. I managed to have the MySensors node recognize a IR code and send the code number to Domoticz, where the appropriate device was auto created:

![image](https://user-images.githubusercontent.com/43920495/46589969-95ef2280-ca7d-11e8-9f11-e152841abd50.png)
![image](https://user-images.githubusercontent.com/43920495/46589621-de0c4600-ca79-11e8-927b-559ea7838711.png)

However when trying to change the state of the device in Domoticz to trigger a SEND event at the MySensors node, I get faults:

![image](https://user-images.githubusercontent.com/43920495/46589650-23c90e80-ca7a-11e8-84ad-819b5d86871c.png)

 `Oct 07 21:11:07 raspberrypi domoticz[29682]: 2018-10-07 21:11:07.591  Status: User: admin initiated a switch command (66/TV On/Off/On)`
`Oct 07 21:11:07 raspberrypi domoticz[29682]: 2018-10-07 21:11:07.591  Error: MySensors: Light command received for unknown node_id: 1, child_id: 5`

Searching for the MySensors command V_IR_SEND, I was able to find the section in hardware/MySensorsBase.cpp that I think was supposed to be executed within MySensorsBase::WriteToHardware. It appears to me there are two `else if (packettype == pTypeGeneralSwitch)` in there (line 1390 and line 1604), and the code to send the V_IR_SEND message is in the second else if which would never be reached.

For testing, I commented out the first `else if (packettype == pTypeGeneralSwitch)` from line 1390 to 1452 and re-compiled it myself, and in that version the IR device works well and can be triggered through domoticz.

`Oct 07 22:02:40 raspberrypi domoticz[15060]: 2018-10-07 22:02:40.476  Status: User: admin initiated a switch command (66/TV On/Off/On)`
`Oct 07 22:02:40 raspberrypi domoticz[15060]: 2018-10-07 22:02:40.582  MySensorsMQTT: Topic: domoticz/in/MyMQTT/5/2/1/1/32, Message: 1`
`Oct 07 22:02:40 raspberrypi domoticz[15060]: 2018-10-07 22:02:40.682  MySensorsMQTT: Topic: domoticz/in/MyMQTT/5/2/1/1/32, Message: 1`
`Oct 07 22:02:40 raspberrypi domoticz[15060]: 2018-10-07 22:02:40.682  Error: MySensors: Unhandled sensor (sub-type=32), please report with log!`
`Oct 07 22:02:40 raspberrypi domoticz[15060]: 2018-10-07 22:02:40.685  (MySensors) Light/Switch (TV On/Off)`

(The ACK message from MySensors triggers an error here too, but everything still works.)

**Comment by gizmocuz** [comment]
That last 'else if' is indeed not correct... should be fixed in latest code/beta

V_IR_SEND is not also ignored... strange this is 'received'

Hope all is working correctly now

**Comment by lamptah** [comment]
After upgrading to beta V4.10055 it works. Thanks! 

It did lead me to find another problem though with the implemention of V_IR_SEND for my purposes... I made a forum post http://www.domoticz.com/forum/viewtopic.php?f=59&t=25224 about that one as I think it is not a bug but an enduser issue.

**Comment by gizmocuz** [comment]
Thanks for the feedback !
