### ISSUE TITLE
Philips lamp showing "set color" as status in devices tab.

### ISSUE THREAD

**Issue by pjensen1977** [domoticz/domoticz#2767]
Running version v4.10051 (but noticed it doing before this version also).

When enabling a Philips Hue light, the status under "switches" says "On", but when looking in the devices tab it shows data as "Set Color". I belive this is the reason my scripts wont function anymore (since on/off status is not being read properly).

**Comment by gizmocuz** [comment]
"Set Color" is also an "On" state, could you not handle this in your script as well ? What value do you read in your script that should) contains only On/Off or the switch command "Set Color"

**Comment by pjensen1977** [comment]
Generally i used domoticz.devices('Lamp1').state == 'On'  and that used to work, but i havent spend any time on domoticz since last winter, and i noticed the scripts were not working anymore. So i don's think the "Set Color" was happening before. But i can use domoticz.devices('Lamp1').state == 'On' or domoticz.devices('Lamp1').state == 'Set Color' i guess. Just thought i mention it, caused me couple of hours to find this out.

**Comment by gizmocuz** [comment]
Maybe you could do != 'Off' (is not off)

**Comment by gizmocuz** [comment]
There is also Set Level, Chime, ...

**Comment by pjensen1977** [comment]
Agreed :-)
