### ISSUE TITLE
Main screen not showing fully on Chrome. 

### ISSUE THREAD

**Issue by pjensen1977** [domoticz/domoticz#2768]
Version: V4.10051

When loading up domoticz in Chrome the 'main' window is shifted too high causing to show half a button or missing first line. It does seem to work fine in Firefox.

**Comment by gizmocuz** [comment]
Could you post a screenshot as i dont experience this. Make sure you use the default theme

**Comment by pjensen1977** [comment]
You are right, it was the theme in Chrome. Never thought about that.
