### ISSUE TITLE
Add "last Update" field to security state.

### ISSUE THREAD

**Issue by omegasa** [domoticz/domoticz#2769]
Can you add **lastUpdate** field to security state?

**Comment by gizmocuz** [comment]
Sorry i am not sure what you mean with this, maybe you could explain it with a picture ?
For every sensor you should see a 'Last Seen' text value in the widgets

**Comment by omegasa** [comment]
> Sorry i am not sure what you mean with this, maybe you could explain it with a picture ?
> For every sensor you should see a 'Last Seen' text value in the widgets

This is not sensor, this is global domoticz state: domoticz.SECURITY_ARMEDAWAY, domoticz.SECURITY_ARMEDHOME, domoticz.SECURITY_DISARMED

And it will be very useful to know, when this state was set, to get it via domoticz.SECURITY_ARMEDAWAY.lastUpdate.hoursAgo for example.

**Comment by gizmocuz** [comment]
Are you talking about dzVents ? Blockly ? what ?

**Comment by gizmocuz** [comment]
Lua ?

**Comment by omegasa** [comment]
> Are you talking about dzVents ? Blockly ? what ?

Sorry, this is my first request here... Feeling myself silly...
I'm asking for DzVents option, yes. But i'm guess it it the same in LUA...

**Comment by rwaaren** [comment]
Look at http://www.domoticz.com/forum/viewtopic.php?f=59&t=25206#p193731 for a workaround using domoticz uservariables. You can also ask @dannybloe via the forum if lastUpdate can be implemented natively in dzVents. The lastUpdate field of the security panel is available in domoticz.

**Comment by gizmocuz** [comment]
Yes i was just going to say, please use the forum
