### ISSUE TITLE
way to much digits on kWh values

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#2773]
in v4.10009 everything was fine.
now upgraded to v4.10059 and the kWh values of some meters have a lot of (useless digits)
i think somebody else mentioned this also but can not find the report anymore

![image](https://user-images.githubusercontent.com/16853535/46853152-98df6f80-cdfd-11e8-8573-0bfd3a2e0230.png)

**Comment by sweetpants** [comment]
I think this i introduced in https://github.com/domoticz/domoticz/commit/93b71fb5adef035149a166546b33720fcae0a6c2
however, i'm on v4.10059 also but do not see this on my dummy energie meters
![image](https://user-images.githubusercontent.com/23421160/46853605-e27c8a00-cdfe-11e8-9584-880fe8752b9b.png)

**Comment by GravityRZ** [comment]
mine are not virtual devices but powerplugs
i tested and when i switch a light on and it starts consuming the value goes back to normal digits.
however the 2 virtual kWh counters i have keep on displaying a large amount of digits 
please note these are not the small fonts used with today:xxxx. these are the large numbers on top.

so the small areas are probably updated ok when power is drawn. the big ones however do not update with a lesser amount of digits.

i think the digits should always be rounded to avoid this behavior 4 digits max after the comma (the dot)

![image](https://user-images.githubusercontent.com/16853535/46856627-35f2d600-ce07-11e8-8aff-abe0e28d72d4.png)

![image](https://user-images.githubusercontent.com/16853535/46856662-528f0e00-ce07-11e8-8435-e24e07ae0f47.png)

**Comment by xbeaudouin** [comment]
I've got same side effect on gaz :  
Before 
<img width="398" alt="capture d ecran 2018-10-12 a 10 18 25" src="https://user-images.githubusercontent.com/1261517/46857032-448dbd00-ce08-11e8-891d-ef102308c881.png">
After :  
<img width="399" alt="capture d ecran 2018-10-12 a 10 18 34" src="https://user-images.githubusercontent.com/1261517/46857042-4c4d6180-ce08-11e8-8314-5f7fd0723327.png">
Regards

**Comment by GravityRZ** [comment]
i think  there needs to be a difference in calculating in max resolution and displaying things

displaying things always rounded to a couple of digits. nobody wants to see these long numbers period.

**Comment by ZaphodBeeblebroxIV** [comment]
It seems to be a general problem. have a similar behaviour using my rain gauge.
![image](https://user-images.githubusercontent.com/44122165/46908466-692a8780-cf23-11e8-93b6-0e77cb0cdff7.png)

**Comment by gizmocuz** [comment]
It's caused by a resent change... nothing to worry about, it's just a display issue, and issues happen in beta's

**Comment by gizmocuz** [comment]
Should be solved in beta 10064, thanks for reporting!

**Comment by GravityRZ** [comment]
thanks
