### ISSUE TITLE
Local Networks (no username/password): and Localhost

### ISSUE THREAD

**Issue by AlbrtoSam** [domoticz/domoticz#2774]
Im using 4.10059 and i get a new error. I have local Network option (no username/password) with values 192.168.1.*;127.0.0.*;localhost

If i do a wget using "localhost" it complains about password. It works fine if i use the local ip address instead. It worked before for me on previous versions.

root@raspbalbrto:/home/pi/scripts# wget http://localhost:8080/json.htm?type=command
--2018-10-12 10:23:29--  http://localhost:8080/json.htm?type=command
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.

root@raspbalbrto:/home/pi/scripts# wget http://192.168.1.227:8080/json.htm?type=command
--2018-10-12 10:23:40--  http://192.168.1.227:8080/json.htm?type=command
Connecting to 192.168.1.227:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24 [application/json]
Saving to: ‘json.htm?type=command.1’

json.htm?type=command.1                       100%[=================================================================================================>]      24  --.-KB/s    in 0s

2018-10-12 10:23:40 (1.04 MB/s) - ‘json.htm?type=command.1’ saved [24/24]

**Comment by sweetpants** [comment]
Please discuss this on the forum first.

**Comment by sweetpants** [comment]
BTW, you are connecting to the IPv6 localhost. Unless you support ipv6 this is WAT
comment out ::1 in your etc/hosts or rename it to something else like ip6-loopback ip6-localhost
