### ISSUE TITLE
Hue dimmer recognition

### ISSUE THREAD

**Issue by Martijnh89** [domoticz/domoticz#2780]
Hi!

Since the beta updates from early October I have some issues with my Hue lights. Some lights, even bundles of lights, are recognized as dimmers. When I change them to an on/off type switch, they work fine as on/off going to the last state they were in. This is how I used them the last years. 

Since the beta updates from early October the light will switch back to a dimmer type switch after a while, usually after one of these lights are updated. I see that there is a commit concerning switch/dimmer recognition, but I'm not sure if this is what results in this bug. If I select to use a Hue light as an on/off type switch, it would be great if it just stays an on/off light switch and doesn't revert back to a dimmer type switch. 

I tried to find the code where it goes wrong, but I'm unfortunately not able to find what causes it. Thanks in advance!

**Comment by jukkapirinen** [comment]
Also Osram Smart+ Plug is not getting on status, it is always off. From hue bridge I can see state on:true.

```
{
  "state": {
    "on": true,
    "alert": "select",
    "mode": "homeautomation",
    "reachable": true
  },
  "swupdate": {
    "state": "notupdatable",
    "lastinstall": null
  },
  "type": "On/Off plug-in unit",
  "name": "Osram1",
  "modelid": "Plug 01",
  "manufacturername": "OSRAM",
  "productname": "On/Off plug",
  "capabilities": {
    "certified": false,
    "control": {
      
    },
    "streaming": {
      "renderer": false,
      "proxy": false
    }
  },
  "config": {
    "archetype": "classicbulb",
    "function": "functional",
    "direction": "omnidirectional"
  },
  "uniqueid": "7c:b0:3e:aa:00:ad:2b:86-03",
  "swversion": "V1.04.12"
}
```

**Comment by Martijnh89** [comment]
Yes good find, I have the same issue with my osram plugs on hue. They are not synced unless I control them from Domoticz. Both Hue issues are since beta’s early october.

**Comment by jukkapirinen** [comment]
So maybe related to this pull request https://github.com/domoticz/domoticz/pull/2709 which was merged on 8 Sep.
@emontnemery can you please take a look.

**Comment by emontnemery** [comment]
Ok, I can have a look early next week.
What system are you guys on, Raspberry Pi?

**Comment by Martijnh89** [comment]
Thanks! Yes, pi3 with the latest beta running.

**Comment by emontnemery** [comment]
Ok, just to make clear: Are the lights supporting only on/off but incorrectly defined as dimmers, or do you want to force dimmers to show up as on/off switches?

A similar log as the one from @bbogey would be extremely useful.

**Comment by jukkapirinen** [comment]
I'm running Ubuntu 18.04 x86_64.
The Osram plugs are correctly shown as On/Off switch, but not getting the state.
In device log I see both On and Off switches are logged as Off.

**Comment by Martijnh89** [comment]
Regarding the dimmer issue I’m unable to find the error.. 

But what happens: a lamp is recognized as a dimmer when I add it or reboot domoticz, when I change it to on/off switch it works but after a short while the lamp changes back to dimmer again. So it keeps resetting back to dimmer, while I have set it as on/off switch.

So yes: I force dimmers to show up as on/off, which works, but after a short while they reset to dimmer again.

**Comment by emontnemery** [comment]
@martijnh89 Why would you want to force a dimmer to appear as an on/off switch? What benefit does it give you?
Edit: I should clarify that changing to dimmer is by design to make sure Domoticz state is aligned with data received from Hue hub, but some override option could be added to Hue HW to disable this if useful. Or even disable correcting device type completely, but maybe other user would complain.

**Comment by Martijnh89** [comment]
Thanks @emontnemery!

Two Things:
1. I use these lamps on a fixed setting (%), and therefore as on/off. I don’t want anyone to change the brightness of these lamps. However, every lamp is a dimmer in hue even if you want to use these on/off. Domoticz had the possibility to use it as on/off which was a perfect solution.
2. In Dashticz the dimmers are shown as dimmers as well, while I want to have these lights visible as on/off in dashticz.

This always worked in domoticz; if I select a lamp to use as on/off instead as a dimmer it always turns on with the predefined (or last known) setting. But only recently the lamp reverts back to a dimmer after a while.

**Comment by emontnemery** [comment]
@Martijnh89 The Osram plugs issue should definitely be fixed, I'll provide a debug build with extra prints to understand why it's not working.

Your issue with mapping a dimmer (I suspect your light is actually not just a dimmer, but a light with **configurable color temperature**, please confirm) can be solved with an automation instead: Create a dummy on/off type switch and setup automations to tie its state to the Hue light's state.

Allowing user to force the type of a device which is well known (as is the case for "smart" things like Hue lights) makes little sense. "Stupid" 433MHz devices is a different case, there it's typically impossible to know the type of a device.

@gizmocuz What do you think? Should it be possible for the user to "force" device type?

Edit: It's also not possible to force Yeelight, Xiaomi or Zwave lights to be an on/off type light when it's a light with configurable color temperature or some RGB light variant.

**Comment by Martijnh89** [comment]
Thanks a lot for your support! And I agree, this is how it can be solved. I just reported it because it worked the last two years like this and now it was changed. Previously when I set the lamp as an on/off switch it would stay this way. If this is the new standard, and when a user wants to have it as an on/off switch, they can create a dummy. 

The lamp is just a hue white dimmable lamp by the way, no colour or white ambiance lamp. 

Thanks again for the support.

**Comment by emontnemery** [comment]
@Martijnh89 If it's a simple white dimmable light it should work to force it as a switch. I'll add some debug prints to see what's going on!

**Comment by Martijnh89** [comment]
Thanks, that would be great! I have three white dimmable hue lights, and they are the only ones I used to force on/off which used to work before the bètas in october. It can be forced, and works, but changes back to a dimmer type switch.

**Comment by emontnemery** [comment]
@Martijnh89 Please test this Raspberry Pi build: https://montnemery.com/domoticz_hue_fix_2780/001/domoticz_linux_armv7l.tgz
There is no fix yet, just extra prints.

Please make a backup of your domoticz databse first!

**Comment by Martijnh89** [comment]
Thanks @emontnemery! I have installed it, do you want me to do something like setting the hue white lights from dimmer to on/off?

**Comment by emontnemery** [comment]
@Martijnh89 Try to reproduce the issues you have reported:
- Turn on/off Osram Smart+ Plug with Hue app -> state is not updated in Domoticz
- Change type of white light to on/off -> it is automatically changed back to dimmer

In both cases, please collect domoticz log file from start until finish of test and paste here.

Edit:
In the log, you should find something like this:
```
2018-10-27 22:38:31.193  Status: Philips Hue: '{"lights":{"1":{"state":{"on":true,"bri":254,"hue":46433,"sat":218,"xy":[0.5, t":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Sonoff","modelid":"LCT007","uniqueid":"60::"5.50.1.19085"}},"groups":{},"schedules":{},"config":{"name":"Philips hue","mac":"60:01:94:9D:3B:0B","dhcp":true,"ipaddress".255.0","gateway":"192.168.0.1","proxyaddress":"none","proxyport":0,"bridgeid":"600194FFFE9D3B0B","UTC":"2018-10-27T22:38:31"ate":"2018-10-27T22:38:31","create date":"2018-10-27T22:38:31","name":"Remote"}},"swversion":"01041302","apiversion":"1.17.0""","text":"","notify": false},"linkbutton":false,"portalservices":false}}'
2018-10-27 22:38:31.193  Status: HueBridge checking state of 'Sonoff'
2018-10-27 22:38:31.193  Status: On: true
2018-10-27 22:38:31.194  Status: HueBridge state change for 'Sonoff'
2018-10-27 22:38:31.194  Status: Philips Hue: InsertUpdateSwitch called for device 'Sonoff' with type 5
```

**Comment by Martijnh89** [comment]
I tested the hue white lamps first, everything looks good in the basic log. When I change it to on/off nothing interesting in the log, it still sees it as "dimmable light" but it remains an on/off switch. I can turn it on or off within Domoticz and it still remains an on/off switch. 

Interesting though, when I turn the lamp on within the hue app, the following thing happens:

`2018-10-29 19:48:50.182 Status: HueBridge checking state of 'Hal'
2018-10-29 19:48:50.182 Status: On: true
2018-10-29 19:48:50.182 Status: HueBridge state change for 'Hal'
2018-10-29 19:48:50.182 Status: Philips Hue: InsertUpdateSwitch called for device 'Hal' with type 1
2018-10-29 19:48:50.183 Status: Philips Hue: adding device 'Hal'`

I have the full log available before the change, after the change and after the light was turned on in hue. See the attached files, sorry for the docx format..

I will now check the status of the osram plug. 

[Standard after reboot.docx](https://github.com/domoticz/domoticz/files/2526668/Standard.after.reboot.docx)
[After changing to onoff.docx](https://github.com/domoticz/domoticz/files/2526669/After.changing.to.onoff.docx)
[After switching light on with hue app.docx](https://github.com/domoticz/domoticz/files/2526670/After.switching.light.on.with.hue.app.docx)


.

**Comment by Martijnh89** [comment]
Allright, I also tested the Osram plug. This is interesting cause it still doesn't work, but the log looks quite similar to the above where an "InsertUpdateSwitch" and device creation is triggered. 

When I had the plug off in hue and in Domoticz everything was fine, it shows "Vaatwasser" as off:

`2018-10-29 20:04:41.830 Status: HueBridge checking state of 'Vaatwasser'
2018-10-29 20:04:41.831 Status: On: false`

Then I switched the plug on with the hue app. The first log after it shows the following:

`2018-10-29 20:05:42.534 Status: HueBridge checking state of 'Vaatwasser'
2018-10-29 20:05:42.535 Status: On: true`

So it does see that it is "on", but in Domoticz it stays off. Later in this log the following shows up:

`2018-10-29 20:05:42.535 Status: HueBridge state change for 'Vaatwasser'
2018-10-29 20:05:42.535 Status: Philips Hue: InsertUpdateSwitch called for device 'Vaatwasser' with type 0
2018-10-29 20:05:42.535 Status: Philips Hue: adding device 'Vaatwasser'`

And in the same log it says it again later on:

`2018-10-29 20:05:42.544 Status: Philips Hue: InsertUpdateSwitch called for device 'Group Vaatwasser' with type 0
2018-10-29 20:05:42.545 Status: Philips Hue: adding device 'Group Vaatwasser'`

After this, the log looks similar as before with nothing about the "Vaatwasser" except that it is on:

`2018-10-29 20:09:55.483 Status: HueBridge checking state of 'Vaatwasser'
2018-10-29 20:09:55.483 Status: On: true`

However, in Domoticz it still shows "off".

Both logs:

[Osram test off.docx](https://github.com/domoticz/domoticz/files/2526689/Osram.test.off.docx)
[Osram test on.docx](https://github.com/domoticz/domoticz/files/2526690/Osram.test.on.docx)

**Comment by emontnemery** [comment]
@Martijnh89 Thanks for the logs, I think the root cause is clear now.
Try this build: https://montnemery.com/domoticz_hue_fix_2780/002/domoticz_linux_armv7l.tgz

**Comment by Martijnh89** [comment]
Thanks a lot @emontnemery, but something seems to be wrong with this build. After I restore my backup it freezes, and Domoticz seems to be unavailable to reach. Even after a reboot. I tried installing the build from yesterday and after uploading the same backup it works perfectly fine.

**Comment by emontnemery** [comment]
@Martijnh89 Sorry about that, try this one:
https://montnemery.com/domoticz_hue_fix_2780/003/domoticz_linux_armv7l.tgz

**Comment by Martijnh89** [comment]
Thanks! Both issues still remain unfortunately, the on/off white lamp switches back to dimmer again with the same log:

`2018-10-31 08:17:40.501 Status: HueBridge checking state of group 'Hal'
2018-10-31 08:17:40.501 Status: On: false
2018-10-31 08:17:40.501 Status: Philips Hue: InsertUpdateSwitch called for device 'Group Hal' with type 1
2018-10-31 08:17:40.501 Status: Philips Hue: adding device 'Group Hal'
`

The Osram plug doesn't update, even though it does see that it's state is on. But it presents the same error as before:

`2018-10-31 08:20:02.124 Status: HueBridge checking state of group 'Vaatwasser'
2018-10-31 08:20:02.124 Status: On: true
2018-10-31 08:20:02.124 Status: Philips Hue: InsertUpdateSwitch called for device 'Group Vaatwasser' with type 0
2018-10-31 08:20:02.124 Status: Philips Hue: adding device 'Group Vaatwasser'`

**Comment by emontnemery** [comment]
@Martijnh89 OK, please try this one:
https://montnemery.com/domoticz_hue_fix_2780/004/domoticz_linux_armv7l.tgz

**Comment by Martijnh89** [comment]
Great job @emontnemery, the dimmer issue is fixed. The white lamps now stay on/off when they update and do not revert back to a dimmer type switch. The log shows:

`2018-10-31 22:40:05.615 Status: HueBridge checking state of group 'Hal'
2018-10-31 22:40:05.615 Status: On: false
2018-10-31 22:40:05.615 Status: Philips Hue: InsertUpdateSwitch called for device 'Group Hal' with type 1`

The osram plugs still don't work unfortunately. When they are off the log says:

`2018-10-31 22:41:26.518 Status: HueBridge checking state of group 'Vaatwasser'
2018-10-31 22:41:26.518 Status: On: false`

When I turn them on in hue the log says:

`2018-10-31 22:42:06.964 Status: HueBridge checking state of group 'Vaatwasser'
2018-10-31 22:42:06.964 Status: On: true
2018-10-31 22:42:06.965 Status: Philips Hue: InsertUpdateSwitch called for device 'Group Vaatwasser' with type 0`

And the next update from hue it says:

`2018-10-31 22:42:27.196 Status: HueBridge checking state of group 'Vaatwasser'
2018-10-31 22:42:27.196 Status: On: true`

But in Domoticz the switch remains off. It doesn't add the device again as shown in previous logs, so that's an improvement!

**Comment by emontnemery** [comment]
@Martijnh89 Good to hear the dimmer issue is fixed.
Here's an attempt to fix the on/off switch issue too: 
https://montnemery.com/domoticz_hue_fix_2780/005/domoticz_linux_armv7l.tgz
(Sorry for many iterations, I don't have any Philips Hue HW so I can't test myself)

**Comment by jukkapirinen** [comment]
I could test also in my system, can you provide a patch?

**Comment by emontnemery** [comment]
@bbogey Sure, https://github.com/domoticz/domoticz/pull/2830

**Comment by jukkapirinen** [comment]
Yes it works now for both individual Osram switch and for the hue group. Also log shows the status OK.

![image](https://user-images.githubusercontent.com/9322054/47853050-38cd5f00-dde6-11e8-9478-3d41271b2c78.png)

For dimmable lights it just tells the percentage, so not sure if can be used with events to check if status = "on"?

![image](https://user-images.githubusercontent.com/9322054/47853672-248a6180-dde8-11e8-9838-bba516113184.png)

**Comment by jukkapirinen** [comment]
Tested the dimmable light (RGBW) it does not get the "On" status in events, as it sets the color or level only.

So this is not working, if I set "hue color lamp 2" On from hue app.
![image](https://user-images.githubusercontent.com/9322054/47854024-4d5f2680-dde9-11e8-9e40-5fb37ba8b931.png)

If I switch it on from Domoticz control panel with On button, it will work.


Edit: Also this is not working
![image](https://user-images.githubusercontent.com/9322054/47854496-8a77e880-ddea-11e8-85df-611b59524a64.png)

**Comment by Martijnh89** [comment]
Not to worry @emontnemery, I'm extremely grateful with what you're doing! Both issues I started this topic for have been solved, the Osram plugs also update perfectly fine now. 

@bbogey, wasn't this always the case? I remember that I test these lamps with "is not off" instead of "is on".

**Comment by jukkapirinen** [comment]
Hmm yes of course, this is working fine, thanks.

<img width="422" alt="screenshot 2018-11-01 at 19 55 50" src="https://user-images.githubusercontent.com/9322054/47869719-54e5f600-de10-11e8-9d0e-129dcf8a7aa7.png">

**Comment by jukkapirinen** [comment]
One more minor anomaly I noticed with Osram plugs and events.
If I trigger plug off with event, it will have entry in log that switch was turned off. But again when hue bridge polls the status, again it will have an entry in the log.

2018-11-02 08:38:07 | Off <- off status from hue bridge
2018-11-02 08:38:00 | Off <- dzVent event set it off after 30 minutes
2018-11-02 08:07:40 | On <- pressed on from the plug


Here is the event trigger

         if domoticz.devices('CoffeePlug').state == 'On' and domoticz.devices('CoffeePlug').lastUpdate.minutesAgo >= 30 then
            domoticz.devices('CoffeePlug').switchOff()
        end 


Other than that everything works like intended, thank you very much.

**Comment by emontnemery** [comment]
@bbogey Do you mean you get two 'Off' events to your dzVents script?
Does this happen with RGB light / Dimmer / Osram On/Off switch or only with the Osram On/Off switch?

**Comment by jukkapirinen** [comment]
No I mean I get two Off status logged in Osram plug device log. One when dzVents script turn off the switch, and when hue polls the status another Off status is logged. 
Probably if another event script would monitor the Off status from the plug, it would trigger two times.
Need to test the same with RGBW light also.

**Comment by emontnemery** [comment]
@bbogey OK, I understand the issue now. Can you please get Hue API log like you did in your first comment, both for Osram plug device, and a group with only Osram plug device?

**Comment by Martijnh89** [comment]
Thank you so much for the fix and the work @emontnemery, great job!

**Comment by emontnemery** [comment]
@bbogey After merge of #2830 and #2839 your issue with two off states should be fixed, can you please test it?
