### ISSUE TITLE
Selector switch shows level value instead of name and hides camera icon

### ISSUE THREAD

**Issue by reflecti** [domoticz/domoticz#2785]
I'm using selector switch to control my PTZ camera presets. When domoticz page is loaded the associated camera icon is visible on the switch along with the set level, not correct name. When another state is selected for selector switch the name updates correctly but at the same time the camera icon disappears.

![cam_visible](https://user-images.githubusercontent.com/32667581/47272896-c3b38b80-d594-11e8-9c17-e05b113a5116.PNG)
![cam_hidden](https://user-images.githubusercontent.com/32667581/47272895-c3b38b80-d594-11e8-9a01-a93f4d1eaf10.PNG)
Page reload:
![cam_visible_10](https://user-images.githubusercontent.com/32667581/47272897-c3b38b80-d594-11e8-9416-8d767a16b9d7.PNG)

Domoticz Version 4.9700

**Comment by gizmocuz** [comment]
Could you update to the beta first and check if this is still happening ?

**Comment by reflecti** [comment]
4.10311 seems to have exactly same behaviour. I added a screenshot from switch settings also.
<img width="960" alt="domoticz selector switch" src="https://user-images.githubusercontent.com/32667581/50576239-1bcd0080-0e16-11e9-8636-2b963bd3c128.png">

**Comment by waltervl** [comment]
Just tested with beta 14205 and similar behavior: after switching to another level the camera icon disappears until a manual page refresh (F5). I did not see the level number displayed only the correct level names.

**Comment by gizmocuz** [comment]
Thanks for reporting, solved in upcoming beta
