### ISSUE TITLE
Selector icon and text not updating

### ISSUE THREAD

**Issue by Tontze** [domoticz/domoticz#2786]
Selector with dimmer light.

I have Json command on and off specified, selector buttons work properly. But it seems i can turn off light with bulb icon, when using it, selector button or ON/OFF text is not changing. --> Bulb goes off, but selector buttons and text shows ON.

**Comment by Tontze** [comment]
Further, if i add json command to selector button, then switch state is not updated anymore.

**Comment by gizmocuz** [comment]
Could you maybe enlighten things with a small screenshot ?
As far as i am aware, a selector type switch should have 'no' bulb that you can press. Is the type set to 'selector' ?

**Comment by Tontze** [comment]
You can achieve such a selector by adding light, and then changing it to selector and still leave icon for lamp :) 

I tried to make milight selector to change colors, since its pain to select colors using built in method :)

![selector2](https://user-images.githubusercontent.com/28216916/47617895-1c26e380-dad5-11e8-9122-2a27ab0f2b6a.PNG)
![selector](https://user-images.githubusercontent.com/28216916/47617896-1c26e380-dad5-11e8-9ef1-57656fe25c2e.PNG)

**Comment by gizmocuz** [comment]
Hmmm i tried here, and i could not click the bulb ... but you should not use the bulb but the buttons Off/On/Green

**Comment by Tontze** [comment]
ok, for a test, i changed Z-Wave dimmer to selector, on/off buttons i added, do work, but state not updated in any way..  Behaviour there is the same as for previous switch.

**Comment by Tontze** [comment]
I too added new dummy bulb, and could not interact with icon

**Comment by gizmocuz** [comment]
I think it is the type/subtype of the switch that is different when you create it from the dummy hardware vs changing the type from an existing switch
