### ISSUE TITLE
Stuck with "Domoticz Offline" page

### ISSUE THREAD

**Issue by jmuchemb** [domoticz/domoticz#2788]
Often, my Firefox Android (v62) gets stuck with the "DOMOTICZ OFFLINE" page. The only way to access again my instance is to erase "cookies and active connections", which is terribly annoying.

Domoticz is behind nginx. Nothing in access/error logs when it happens.

- Firefox: v62
- Domoticz: current stable (4.9700) or a668baf917333e93f92dd9bb7c77eef8e0bc4ce4 (Oct 18)

**Comment by gizmocuz** [comment]
Best to ask on the forum
