### ISSUE TITLE
Json API: wrong ScheduleDate ?

### ISSUE THREAD

**Issue by duhlin** [domoticz/domoticz#2789]
Hello,

The API query such as json.htm?type=schedules returns elements such as:
```
 {
         "Active" : "true",
         "Date" : "",
         "Days" : 100,
         "DevName" : "Consigne_Salon",
         "DeviceRowID" : 65,
         "IsThermostat" : "true",
         "MDay" : 0,
         "Month" : 0,
         "Occurence" : 0,
         "ScheduleDate" : "2018-10-23 10:00:00",
         "Temperature" : "20.0",
         "Time" : "10:00",
         "TimerID" : 5,
         "TimerType" : 2,
         "TimerTypeStr" : "On Time",
         "Type" : "Device"
      },
```
Unfortunately, in the following example, it looks like that the ScheduleDate is not a correct one as 2018-10-23 is on Tuesday, while the rule is only valid on wednesday, saturday and sunday (days: 100). Is it "by design" ?

---
Version: 4.9700
Build Hash: a3a45906
Compile Date: 2018-06-23 16:24:51
dzVents Version: 2.4.6
Python Version: None

**Comment by gizmocuz** [comment]
With this query, it reads the schedules from the database.
In here the date field is probably set when you added the timer.
But internally when the schedulers are loaded/checked/performed, the correct date/time is used
This routine is used for the web-gui/applications
Someone could write a routine that returns the active timers used in the scheduler class
