### ISSUE TITLE
Days of the month in blockley [ weeks ]

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#2790]
Dear developers..

I hope you can make a option to use days of the month.
And perhaps months of the year
If possible with or in blockley
Or otherwise in timers in a dummy switch.
Or when you guys have a better solution, everything is fine.

So i can send my friends a automatic mail on them birthday
And i send my wife a mail on our weddingday..:-)

EDIT:
Found the days... GREAT.
Only i mis in the timer section the weeks of the years
Perhaps that one possible to build in?

**Comment by sweetpants** [comment]
Why are you posting this on github, is it a bug? Github is meant for bugs only. This is a feature request.

**Comment by Dylantje** [comment]
sorry.. I was thinking.....
Where can i place the request

**Comment by sweetpants** [comment]
https://www.domoticz.com/forum/viewforum.php?f=31
