### ISSUE TITLE
Customization of update intervals

### ISSUE THREAD

**Issue by robotechnics** [domoticz/domoticz#2793]
It will be good to have a way to customise the update interval in the database. At the moment all sensors data is saved in the database every 5 mknutes (which seems to be hardcoded on SQL????.cpp?. It will be good to be able to modify that value on the web interface.

**Comment by sweetpants** [comment]
Github is used only for bug fixes, is this a bug or feature request? Please discuss this on the forum first https://www.domoticz.com/forum/viewforum.php?f=31.
