### ISSUE TITLE
Problem with LvlControl and On/Off versus current Level

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2794]
I'm currently facing an issue with Level Control created with the following command in a Plugin

`Domoticz.Device(DeviceID=str(DeviceID_IEEE),Name=str(t) + "-" + str(DeviceID_IEEE) + "-" + str(Ep), Unit=unit, Type=244, Subtype=73, Switchtype=7 ).Create()`

Basically , this device should be able to report Level control on one side, and On/Off status on the other side and I would consider independently.

If you take the example of a bulbe, then it could be Off with Level at 95%. In that particular case, Domoticz consider it as ON , which is wrong !

Here is how I'm updating it : 
```
nValue = 2
sValue =  round((int(value,16)/255)*100)
UpdateDevice_v2(Devices, x, str(nValue), str(sValue))
```

**Comment by gizmocuz** [comment]
Please use the forum
