### ISSUE TITLE
Hue color lights has no turn off option in Groups

### ISSUE THREAD

**Issue by roelbeun** [domoticz/domoticz#2799]
Hi,

As shown in attached image the group lacks an option to turn off Hue color lights, I can only set the dim level to the lowest point which is 1%.

Other Hue lights still have the Command Off option.

It's my first hue color light so i'am not sure if this is a bug or feature.

I can set it offline in a Scene, but i rather use the existing groups.

Can you help/assist? Thank you.

![2018-10-25_10-22-03](https://user-images.githubusercontent.com/3465197/47488842-79a50100-d845-11e8-8200-1930a36dba8f.png)

**Comment by gizmocuz** [comment]
This is correct, this is also for normal switches.
The 'group' listens to the command received, so if a group is turned off, all lights will turn off, also the Hue lights
A scene is a collection of individual 'states'

**Comment by roelbeun** [comment]
Ah yes now I get it, thank you for your reply.

I just need to turn the group off :) then it doesn't care about what state is specified.

Now I'am turning the group On, that's why it's acting like a Scene
