### ISSUE TITLE
Python plugin dev - Devices[unit].Update

### ISSUE THREAD

**Issue by zaraki673** [domoticz/domoticz#2801]
Hi,

Could someone explain how SuppressTriggers works (with True or False, yes i know :D).
In our plugin, when we try to update a device with SuppressTriggers=True, the device is not update, but domoticz logs says that it update plugin : 

`2018-10-25 18:49:14.623 (zigate) Update v2 Values 0:'Off: **SuppTrigger_: True** ForceUpdate_: False' (Motion-Garage)`
`2018-10-25 18:49:14.623 (Motion-Garage) Updating device from 1:'On' to have values 0:'Off'.`

When SuppressTriggers=False, device is update, same log : 

`2018-10-25 19:48:53.922 (zigate) Update v2 Values 0:'Off: **SuppTrigger_: False** ForceUpdate_: False' (Motion-SalonBaie)`
`2018-10-25 19:48:53.922 (Motion-SalonBaie) Updating device from 1:'On' to have values 0:'Off'.`

Is it normal ?

**Comment by gizmocuz** [comment]
Please use the forum (https://www.domoticz.com/forum/viewforum.php?f=65)

**Comment by pipiche38** [comment]
This is a Bug, the SupressTriggers doesn't behave as expected, and when set to True there is no update done in the Database. Could you kindly re-open it ?

**Comment by zaraki673** [comment]
as ask by pipiche38, coul you reopen this 
forum : http://www.domoticz.com/forum/viewtopic.php?f=65&t=25071#p195591

**Comment by gizmocuz** [comment]
Thanks, if possible in the feature mention the forum link in your first post

**Comment by pipiche38** [comment]
We can close this issue as it is not needed anymore .

**Comment by waltervl** [comment]
As mentioned before this issue can be closed.
