### ISSUE TITLE
notification on kodi devices via hostname in stead of ip address

### ISSUE THREAD

**Issue by brjhaverkamp** [domoticz/domoticz#2805]
Currently the notification on kodi can only be configured based on ip address. 
This is very inconvenient for non-technical users. or where the ip address is dynamic. 
Setting the device by hostname and looking up the corresponding ip via dns would be more robust.

**Comment by sweetpants** [comment]
If you want to use dynamic IP, you need a local DNS server and a DHCP server that is able to register the DNS name into this DNS. I think 99% of the users do not have a local DNS server running on their network.

**Comment by gizmocuz** [comment]
Or better, give all your "Fixed" devices a "Fixed" IP address ? That's even more robust.
But checking the code, you can enter a hostname in the gui where it says IP-Address, did you try this ?

**Comment by brjhaverkamp** [comment]
@sweetpants: I think it is much more common than you think. Most modern routers do combine dhcp and dns(proxying) to reply to local hostnames. And even when using fixed IP adresses, they are  much harder to remember than hostnames and will break things when you have to do a renumbering.
@gizmoncuz: Is it in the code? I tried and it didnt seem to work, hence the reported issue. The label clearly said IP-address, so I didnt test further.

**Comment by gizmocuz** [comment]
Yes the label suggests IP address, but i entered my desktop name and it resolves correctly in the code.
If you look at the code you also see the boost asio url resolver being used

**Comment by gizmocuz** [comment]
Can you try it ?

**Comment by xztraz** [comment]
i use pfsense. register nodes on my home network under domain home.  i entered the adress to the kodi machine and it works fine (domoticz on different domain even)

![image](https://user-images.githubusercontent.com/25690871/96606215-50fe5780-12f7-11eb-9286-91f4708d276e.png)

I would say closed. possibly a tooltip explaining that a name also works would be good.

**Comment by waltervl** [comment]
Updated wiki, general LAN https://www.domoticz.com/wiki/Hardware_Setup#Setting_up_a_LAN_hardware
