### ISSUE TITLE
Windows later .dll issues

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#2807]
Hi,

Since some later betas Windows run fails due to normally missing msvcp140.dll and vcruntime140.dll in System 32 and SysWOW64 folders. In my case I am running Domoticz on both 64bit Win-7 and -10 platforms and the problem was the same. I had one Win 10 installation that had those .dll files for some unknown reason and on this machine I could start i.e. 4.10102 without problems. So, I copied this machines .dll files to the failing Win-7 and -10 installs and Domoticz started again, Desktop start as well Run as a Service. 

Please note that it is two different versions of those .dll files in System32 vs. SysWOW64. At least in my case it seemed so...

**Comment by gizmocuz** [comment]
Hmmm I think it's the openzwave dll that needs this.
It's the Visual Studio 2015 redist dependency.
It does still run on my development environment (which is 99% windows 10 bdw)
Probably this has been like this for quite some time now, we used to static link openzwave, now it is using a DLL
Are both your windows installations up2date ?
If yes, i think the only way to avoid this is to static link the openzwave library again in release build

**Comment by gizmocuz** [comment]
Solved in upcoming beta

**Comment by RicardP** [comment]
Late reply, sorry. Yes all installations are kept up to date, also if manually checking Windows Update. However I guess those .dll files was installed on the working machine by some other program installations (most uninstalled as well) done in the past, because I use this PC not only for Domoticz. 
I will test to rename those .dll temporary after the upcoming solution and see if it still starts.

Many thanks for everything! :)
