### ISSUE TITLE
Weather forecast now always in english

### ISSUE THREAD

**Issue by TheUlpio** [domoticz/domoticz#2808]
Sorry for my bad english...

After the commit #2775 which solves the issue #2726, i've noticed that darksky iframe in forecast page is always set to english. i can change other options, ie units (m/s ,km/h...) and them are kept, but language returns always to english.

If i open darksky page in browser, all settings are kept, so, i can have at the same time a tab with darksky in my native language and another tab with the domoticz forecast page in english.

This happens on all my devices (PCs -> various linux distro; tablets -> android) also if i flush browser cache and delete cookies (in this case i have to set again my options).

analyzing the domoticz iframe html, it starts with:

"<!doctype html>"
"\<html lang="en">"
"\<head>"
"..." 

so "english" is forced in code. 

I'm not a programmer, so i ask if it's a way to integrate in forecastcontroller.js also the lang option as set in config page.

**Comment by gizmocuz** [comment]
commit #2775 was only a url changed. I think you had English before ?

The iframe is created in ForecastController.js and does not contain the lang="en", in fact "lang="en"" does not exist anywhere except in the frontpage example

Can't change this

**Comment by TheUlpio** [comment]
@gizmocuz Thank you for taking a look at this.

the lang=en statement doesn't come from domoticz. It's an hard coded variable in the darksky page (imho it is used only in case user doesn't override with his choice in url). A sort of default value.
The url problem as described in #2726 was already investigated by me in this forum thread https://www.domoticz.com/forum/viewtopic.php?t=15484, But I abandoned changes because the page became only in english.

>  I think you had English before ?

No, until this change i had Italian. Seems that with this change, which imho is the correct way to build part of the url, if the url is not fully qualified, darksky redirects to something like:
`https://darksky.net/forecast/[lat],[long]/ca12/en`

> Can't change this

Well, you can! In #2726 comments, you asked about a /ca12/en statement. The "ca12" part is a code which tells darksky page which units user wants (ca ->km/h, si ->m/s, uk2->miles/h, us->imperial units). This is the default if nothing is provided. The "en" part is the language of the requested page.

So, in forecastcontroller.js the url should be something like this:

`htmlcontent += '<iframe class="cIFrameLarge" id="IMain" src="//darksky.net/forecast/' + $scope.config.Latitude + ',' + $scope.config.Longitude + '/ca12/ + $scope.config.combolanguage"></iframe>';`

The point is that as i'm not a programmer, i don't know if something like "scope.config,combolanguage" statement refers to the combo "language" in config page. Maybe this is obvious for you, but is really over my ability.

As a curiosity, googling here and there to better document this issue, i've found this https://community.home-assistant.io/t/darksky-forecast-language-other-than-english/6725
So the problem is not only for domoticz :)

**Comment by gizmocuz** [comment]
Thanks for the explanation. Yes i was just looking at the new iframe generation which is just this:

`htmlcontent += '<iframe class="cIFrameLarge" id="IMain" src="//darksky.net/forecast/' + $scope.config.Latitude + ',' + $scope.config.Longitude + '"></iframe>';`

So here are no language options.... it would be nice that darksky would 'guess' the users browser language...

i made a change, and the new URL is now (when selecting 'Dutch' in the settings)

htmlcontent += '<iframe class="cIFrameLarge" id="IMain" src="//darksky.net/forecast/' + $scope.config.Latitude + ',' + $scope.config.Longitude + '?lang=' + $rootScope.config.language + '"></iframe>';

it adds ?lang=nl

but i see no change

at the top right you can select the language, maybe it remembers it ?

**Comment by TheUlpio** [comment]
Well, it seems that the "?lang=" syntax isn't recognized by darksky. The only one accepted is in the form:

` https://darksky.net/forecast/[lat],[long]/[units]/[language]`

and this syntax have to be fullfilled in each part. If i do something like:

` https://darksky.net/forecast/[lat],[long]/[language]` (no units part)

the page defaults to:

` https://darksky.net/forecast/[lat],[long]/ca12/en`

so the units part is mandatory. In api documentation there is an "auto" parameter which would be useful, but seems it isn't recognized in url composition.

I noticed that in domoticz settings -> system there is the language field which provide the correct localization code.
Also, in settings -> meters/counters there are useful info about temperature and wind speed units (the ca12 part in url), but this requires some kind of logic to translate these data in darksky codes (ca/si/uk2/us). So imho a start code to achieve (part of) the goal could be (i'm picking from your code as i'm not really sure what i'm writing)

`htmlcontent += '<iframe class="cIFrameLarge" id="IMain" src="//darksky.net/forecast/' + $scope.config.Latitude + ',' + $scope.config.Longitude +'/ca12/' +$rootScope.config.language + '"></iframe>';`

This way the url is fully qualified (all data are in place in the required sequence and should work).

> at the top right you can select the language, maybe it remembers it ?

No, this is the only field that, if set, return to english each time the iframe ia opened (but remembers if the same page is opened in browser)

**Comment by gizmocuz** [comment]
Thanks! Yes that works !

![image](https://user-images.githubusercontent.com/2265299/47616686-81240e80-dac0-11e8-8e1c-143226415d17.png)

Next is to deal with the ca12 part....

**Comment by TheUlpio** [comment]
Thank you for your hard work ad your time @gizmocuz. This is the power of open source!
I don't know if the ca12 can be deepened in this issue or if it's better to open another one or a forum thread, but in my tests i observed that:

-  for the literal part darksky allows only four choises:

>°F,mph = us
°C,m/s = si
°C,km/h = ca
°C,mph = uk2

- for the numeric part (the way time is shown in the time bar):

> 12 = time in am/pm notation
24 = time in the 24h notation.

so, imho all these combination can be obtained combining settings which are already present in the setup -> settings fields
Just my two cents

**Comment by gizmocuz** [comment]
That was easy to do... it works! The code is now:

```
			var units = "ca24";
			if ($rootScope.config.TempSign == "F") {
			    units = "us12";
			} else {
			    if ($rootScope.config.WindSign == "m/s")
			        units = "si24";
			    else if ($rootScope.config.WindSign == "km/h")
			        units = "ca24";
			    else if ($rootScope.config.WindSign == "mph")
			        units = "uk224";
			}
			htmlcontent += '<iframe class="cIFrameLarge" id="IMain" src="//darksky.net/forecast/' + $scope.config.Latitude + ',' + $scope.config.Longitude + '/' + units + '/' + $rootScope.config.language + '"></iframe>';

```

Closing the issue
