### ISSUE TITLE
Westinghouse fan support with RFXCOM XL 

### ISSUE THREAD

**Issue by eschuermann** [domoticz/domoticz#2814]
Domoticz version: stable and latest v4.10110 icw RFXCom433XL

I have upgraded my RFXcom to th XL version, and Domoticz to the latest stable (and latest beta as well). I amongst others use it to control a Westinghouse fan. With a previous RFXCOM433ext I used to use the Lucci air AC controls for it. After the upgrade to the XL the fan can't be controlled anymore. When I use RFXmgr, I see the protocol is now Westinghouse:

17-10-2018 08:30:34:921= Fan command

Packettype = Fan
subtype = Westinghouse
subtype = Westinghouse
Sequence nbr = 13
ID = SW1=Off, SW2=Off, SW3=Off, SW4=Off
Command = OFF
Signal level = +9 dBm
------------------------------------------------

From RFXCOM support:
Westinghouse could be controlled in Ext2 firmware with LucciAir or Westinghouse commands. This is possible because LucciAir was not present in Ext2 firmware. Because LucciAir and Westinghouse are present in ProXL1 firmware you have to use a Westinghouse device in Domoticz now.

I however do not have the possibility to select type Westinghouse as fan, only Lucci Air. Is it possible to add the Westinghouse support (back) to domoticz? See also 
https://www.domoticz.com/forum/viewtopic.php?f=44&t=24392 
in the forum.

**Comment by gizmocuz** [comment]
Okey, i think i did it, but i can't test... try beta 10123, it should be available in two hours from now
Let us know if it works please

**Comment by eschuermann** [comment]
Hi, it partly works, as I can switch the fan on. But cannot select speed or shut it off, or turn on/off the lights. 

These are the commands used by RFXCOM, I hope this helps claryfing the command structure (it is similar to Lucci AC Fan).

Light On/Off


================================================
29-10-2018 07:07:06:888= Fan command
================================================
Packettype    = Fan
subtype       = Westinghouse
subtype       = Westinghouse
Sequence nbr  = 4
ID            = SW1=Off,  SW2=Off,  SW3=Off,  SW4=Off
Command       = Light
Signal level  = +9 dBm
------------------------------------------------
29-10-2018 07:07:07:137
Packettype        = Receiver/Transmitter Message
subtype           = Transmitter Response
Sequence nbr      = 4
response          = ACK, data correct transmitted


Fan level High

================================================
29-10-2018 07:07:35:372= Fan command
================================================
Packettype    = Fan
subtype       = Westinghouse
subtype       = Westinghouse
Sequence nbr  = 7
ID            = SW1=Off,  SW2=Off,  SW3=Off,  SW4=Off
Command       = HI
Signal level  = +9 dBm
------------------------------------------------
29-10-2018 07:07:35:578
Packettype        = Receiver/Transmitter Message
subtype           = Transmitter Response
Sequence nbr      = 7
response          = ACK, data correct transmitted

Fan level Medium

================================================
29-10-2018 07:07:50:373= Fan command
================================================
Packettype    = Fan
subtype       = Westinghouse
subtype       = Westinghouse
Sequence nbr  = 8
ID            = SW1=Off,  SW2=Off,  SW3=Off,  SW4=Off
Command       = MED
Signal level  = +9 dBm
------------------------------------------------
29-10-2018 07:07:50:675
Packettype        = Receiver/Transmitter Message
subtype           = Transmitter Response
Sequence nbr      = 8
response          = ACK, data correct transmitted


Fan level Low

================================================
29-10-2018 07:08:04:088= Fan command
================================================
Packettype    = Fan
subtype       = Westinghouse
subtype       = Westinghouse
Sequence nbr  = 9
ID            = SW1=Off,  SW2=Off,  SW3=Off,  SW4=Off
Command       = LOW
Signal level  = +9 dBm
------------------------------------------------
29-10-2018 07:08:04:345
Packettype        = Receiver/Transmitter Message
subtype           = Transmitter Response
Sequence nbr      = 9
response          = ACK, data correct transmitted


Fan Off

================================================
29-10-2018 07:08:20:180= Fan command
================================================
Packettype    = Fan
subtype       = Westinghouse
subtype       = Westinghouse
Sequence nbr  = 10
ID            = SW1=Off,  SW2=Off,  SW3=Off,  SW4=Off
Command       = OFF
Signal level  = +9 dBm
------------------------------------------------
29-10-2018 07:08:20:418
Packettype        = Receiver/Transmitter Message
subtype           = Transmitter Response
Sequence nbr      = 10
response          = ACK, data correct transmitted

**Comment by gizmocuz** [comment]
Please try beta 10149

**Comment by eschuermann** [comment]
Hi Gizmocuz,

everything is now working as it should! Thanks for your efforts, case can be closed ;-)

Regards,
Erwin
