### ISSUE TITLE
Unable to delete counter incremental historical records

### ISSUE THREAD

**Issue by ayasystems** [domoticz/domoticz#2818]
Hi

Current version 4.101405

I am not able to delete historical data from counter incremental.

![image](https://user-images.githubusercontent.com/7864168/47648204-a032a700-db79-11e8-9e1e-8b253fbdba4a.png)

![image](https://user-images.githubusercontent.com/7864168/47648222-ad4f9600-db79-11e8-92e4-e6beeaea0020.png)

But is not deleted

Regards

**Comment by gizmocuz** [comment]
Can you try this on the month/year graph ?

**Comment by sweetpants** [comment]
You can in month and year graphs, only not in (7) daily graph.

**Comment by ayasystems** [comment]
I can do in month and year. 

In the week section delete feature is not responding, nothing happens, the popup asking is not showed.

in the daily section show the popup but the data is not deleted. If i see the respond with debug the response is:

{
   "status" : "OK",
   "title" : "deletedatapoint"
}


but the data is not deleted.

regards
