### ISSUE TITLE
Milight dimming not working as it should

### ISSUE THREAD

**Issue by Tontze** [domoticz/domoticz#2819]
There is a problem when using dimming on milight bulbs.

If you decrease brightness low enough, you cant set it to 100% directly, you need to firs bring it up to 75% or so, after that you can set 100%.

you can easily produce this behaviour witj json commands, set to 25%, and after that to 100%, nothing happends :/  From 75% changing to 100% works.

**Comment by Tontze** [comment]
Actually, setting brightnesses between 13 - 87 do work .. 

So minimum you can set is: 

`http://192.168.8.150:8080/json.htm?type=command&param=switchlight&idx=238&switchcmd=Set%20Level&level=13`

And maximum is : 

`http://192.168.8.150:8080/json.htm?type=command&param=switchlight&idx=238&switchcmd=Set%20Level&level=87`

**Comment by poudenes** [comment]
You can't dim to 1% for example. There is a limit of the bulb itself. Also in Milight App you can't dim to 1 % it will be always more then that. I don't know what the equal percentage will be that will be the lowest value.

**Comment by Tontze** [comment]
Yup. But it should get fixed In domoticz, you cant now set it To 100% since it doesnt work..
