### ISSUE TITLE
Motherboard Sensors Disk Usage shows wrong disk

### ISSUE THREAD

**Issue by febalci** [domoticz/domoticz#2822]
Domoticz 4.9700 Stable
Ubuntu 18.04

When installed for the first time, the native Motherboard Sensors Plugin Disk Usage shows everything correctly. After some reboots or (Something i still don't know), disks (or mount points) show percentage usage wrongly from another mount point. 

The 'df -h' number of disks or their order in the list changes occasionally on ubuntu. Guess the Motherboard Sensors is updating values according to the order number in the list. So when a disk goes down on the list from 3rd to 4th for example, Motherboard Sensors still assigns the value of 3rd disk to the new mount point that comes into the 3rd order. 

In summary, when the df -h list changes from this:

udev                                     7.8G     0  7.8G   0% /dev
tmpfs                                    1.6G  4.9M  1.6G   1% /run
/dev/mapper/highlander--vg-root          213G   22G  180G  11% /
tmpfs                                    7.8G  8.0K  7.8G   1% /dev/shm
tmpfs                                    7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/loop0                               4.8M  4.8M     0 100% /snap/canonical-livepatch/49
/dev/loop1                                88M   88M     0 100% /snap/core/5662
/dev/loop2                                88M   88M     0 100% /snap/core/5548
/dev/nvme0n1p1                           511M  6.1M  505M   2% /boot/efi
/dev/sda1                                916G   50G  821G   6% /media/hdd 

to this:

udev                                     7.8G     0  7.8G   0% /dev
tmpfs                                    1.6G  4.9M  1.6G   1% /run
/dev/mapper/highlander--vg-root          213G   22G  180G  11% /
tmpfs                                    7.8G  8.0K  7.8G   1% /dev/shm
tmpfs                                    5.0M  4.0K  5.0M   1% /run/lock
tmpfs                                    7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/loop0                               4.8M  4.8M     0 100% /snap/canonical-livepatch/49
/dev/loop1                                88M   88M     0 100% /snap/core/5662
/dev/loop3                               5.0M  5.0M     0 100% /snap/canonical-livepatch/42
/dev/loop2                                88M   88M     0 100% /snap/core/5548
/dev/loop4                                88M   88M     0 100% /snap/core/5328
/dev/loop5                               5.0M  5.0M     0 100% /snap/canonical-livepatch/50
/dev/nvme0n1p1                           511M  6.1M  505M   2% /boot/efi
/dev/sda1                                916G   50G  821G   6% /media/hdd

the /dev/sda1 (10th item in the list) disk usage device in domoticz shows the result of /dev/loop2 (10th item in the new list) instead...

**Comment by gizmocuz** [comment]
Yes i think your'e right here... but it's the first time i see someone using snap devices.
https://askubuntu.com/questions/906581/what-is-dev-loopx

**Comment by febalci** [comment]
I upgraded Ubuntu 16.04 to 18.04 with Software&Updates setting. I guess Ubuntu uses snap by default in that sense. When i write snap list:

Name                 Version    Rev   Tracking  Publisher   Notes
canonical-livepatch  8.0.6      50    stable    canonical✓  -
core                 16-2.35.4  5662  stable    canonical✓  core

So i didn't use snap devices on purpose but i guess Ubuntu is relying on snap starting from 16.04.

**Comment by gizmocuz** [comment]
you can delete the snaps if your new (updated) versions works correctly
