### ISSUE TITLE
P1 meter missing total count when go to report.

### ISSUE THREAD

**Issue by HoekieN** [domoticz/domoticz#2824]
When i go to the chart of my P1 meter i see the the usage of that day with a total:
![image](https://user-images.githubusercontent.com/28273279/47751362-d105ff80-dc91-11e8-97e5-32c4d1f2b6eb.png)
But when i go to the report the total count is missing:
![image](https://user-images.githubusercontent.com/28273279/47751191-69e84b00-dc91-11e8-9691-36bb65f19ac5.png)

i cleared my cache and checked om multiple devices.

Version: 4.10149
Build Hash: 0046914e-modified
Compile Date: 2018-10-30 08:13:34
dzVents Version: 2.4.7
Python Version: 3.6.6 (default, Sep 12 2018, 18:26:19) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

**Comment by gizmocuz** [comment]
Thanks for reporting! There have been a change in code rendering the charts/tables for P1 devices.
Will have a look at this asap

**Comment by gizmocuz** [comment]
Working again in beta 10155
