### ISSUE TITLE
The -userdata parameter is required to end in a / - but this is not enforced

### ISSUE THREAD

**Issue by tih** [domoticz/domoticz#2826]
Domoticz normally determines the path to its various component directories working from the path to the invoked executable itself, by using that path up to and including the last '/' as a starting point. Several paths are derived from this, by appending directory names to it. When this is done, it is assumed that the original path (typically in the szUserDataFolder variable) ends in a '/'. Picking an example at random:

std::string sbackup_DirD = szUserDataFolder + "backups/daily/";

If the user chooses to give the user data folder as a command line parameter, though, he or she might understandably specify e.g. "-userdata /opt/domoticz", without the trailing slash. Domoticz will accept this parameter without complaint, and end up making mistakes like (using the example above) trying to put daily backups in "/opt/domoticzbackups/daily/".  Similarly, the scripting subsystems will be looking for "/opt/domoticzscripts/", which again does not exist.

My suggestion would be to have the -userdata switch (and probably the other switches that are used to supply directory paths) check for a trailing slash, and silently append one if it's missing.

**Comment by tih** [comment]
Looks like it's szStartupFolder (command line parameter -approot, config file parameter app_path) and szUserDataFolder (command line parameter -userdata, config file parameter userdata_path) that are expected to have a trailing slash, and will cause problems if that slash is missing, while szWWWFolder (command line parameter -wwwroot, config file parameter http_root) is expected *not* to have a trailing slash.

Fallback settings for these are: szStartupFolder calculated from argv[0], szUserDataFolder copied from szStartupFolder, and szWWWFolder calculated as szStartupFolder + "www".

Incidentally, szWebRoot (described as "additional web root, useful with proxy servers") does not have a fallback, so remains unset if the user doesn't explicitly configure it, but is still unconditionally used in main/mainworker.cpp,  in the call "m_webservers.SetWebRoot(szWebRoot);".

**Comment by tih** [comment]
I'm unsure both how you'd prefer to handle this, and what's the canonically proper way to ensure a string ends in a specific character in C++, but something like this might do the trick, checking, and fixing if needed, szStartupFolder and szUserDataFolder after the last time each is set (by switches, config file settings, or fallback mechanisms), but before the first time they're used:

[domoticz.DIFFS.trailing-slashes.txt](https://github.com/domoticz/domoticz/files/2541783/domoticz.DIFFS.trailing-slashes.txt)

**Comment by gizmocuz** [comment]
I think it's solved with this patch ?
https://github.com/domoticz/domoticz/commit/e695a8aa63e44e67de4533de88249170898baa76

**Comment by tih** [comment]
That looks better than my suggestion, which further cluttered up an already overly complex main().

However, you're still only handling the situation where the command line parameter is used to set the szUserDataFolder variable - but there are three more problem sources: the command line parameter for overriding the application folder, and the configuration file parameters for it and for the user data folder.

Add calls to FixFolderEnding() for those three, and all will be well.

**Comment by tih** [comment]
Now that Rob Peters has paved the way, handling the three other cases was easy. :)

**Comment by gizmocuz** [comment]
Thanks, merged !
