### ISSUE TITLE
In Events, Blockly editor window is not displaying

### ISSUE THREAD

**Issue by paifre** [domoticz/domoticz#2831]
Hello,

Opening Events function (setup/more options/Events) Blockly editor window is not displaying with version **10157**
On left, I have the list of existing scripts
On the top of the frame, I have a line with the tab + import/export/save/delete
Nothing else displayed
Create new blockly script doesn't make the blockly editor window appearing
Creating new python or Lua or dzEvents, the editor window is appearing

I cleaned up appcache with chrome:appcache, used private navigation, MS Edge.... same behaviour

Message reported in Chrome console
angular.min.js:124 TypeError: Blockly.Xml.textToDom expected an <xml> document.
    at Object.Blockly.Xml.textToDom (blockly_compressed.js:1224)
    at Function.Blockly.Options.parseToolboxTree (blockly_compressed.js:1130)
    at new Blockly.Options (blockly_compressed.js:1126)
    at Object.Blockly.inject (blockly_compressed.js:1679)
    at EventViewer.js:193
    at angular.min.js:137
    at m.$digest (angular.min.js:148)
    at m.$apply (angular.min.js:151)
    at l (angular.min.js:103)
    at t (angular.min.js:108) "Possibly unhandled rejection: {}"

Previous messages are the following (partial list)
blockly_compressed.js:881 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MAX}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_AVERAGE}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MEDIAN}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MODE}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_STD_DEV}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_RANDOM}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_MATH_CHANGE_TOOLTIP}.

**Comment by stas-demydiuk** [comment]
@paifre Have you modified Blockly editor with custom Math functions in previous events editor?

**Comment by paifre** [comment]
Hello,
No, all Blockly scripts are simple ones

**Comment by paifre** [comment]
First errors are the following, starting with some LOGIC stuff

WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_EQ}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_NEQ}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LT}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LTE}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GT}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GTE}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_AND}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_OR}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_WHILE}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_CONTROLS_FOR_TOOLTIP}.
blockly_compressed.js:881 WARNING: No message string for %{BKY_CONTROLS_FOREACH_TOOLTIP}.

**Comment by paifre** [comment]
New messages after a new cache cleaning.
Please, notice that my custom webroot has been removed in this failing request

angular.min.js:110 GET http://xxxxx.home:999**9/a**pp/events/blockly_toolbox.xml 400 (Bad Request)
(anonymous) @ angular.min.js:110
n @ angular.min.js:105
(anonymous) @ angular.min.js:102
(anonymous) @ angular.min.js:137
$digest @ angular.min.js:148
$apply @ angular.min.js:151
...
...
...
angular.min.js:124 Possibly unhandled rejection: {"data":"<html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html>","status":400,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/app/events/blockly_toolbox.xml","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"Bad Request","xhrStatus":"complete"}

**Comment by paifre** [comment]
Should help to fix the problem...
Using a customized webroot leads to a failure...
Testing right now without a webroot, I can see Blockly editor :)

**Comment by gizmocuz** [comment]
There was an absolute path in the code. Could you try beta 10160 ?

**Comment by paifre** [comment]
Correction works fine. Great job.
Many thanks
