### ISSUE TITLE
Events Editor - Limit of 95 lines !

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#2834]
Hello,
I have tried to edit some of my dzVents scripts. I have built them using the web based events editor.
I run into an issue that a script cannot have more than 95 lines of code !!

If the script has more than 95 lines, it cannot be saved !
Please correct so I can edit my scripts again.

EDIT

It looks the limit is maybe the number of characters in the scripts, it is blocking above 3887 !

**Comment by stas-demydiuk** [comment]
Sounds very similar to https://www.domoticz.com/forum/viewtopic.php?f=6&t=25437&sid=54664ae1f58d25eec01e14f2c1897eb7

@gizmocuz is it possible to update JSON API for creating events to support POST request
`/json.htm?type=events&param=create&...`

**Comment by Olivier6767** [comment]
Thanks. Yes this is the same issue. I'm using NGINX as reverse proxy. 
If I bypass the reverse proxy, I can save my script without any issue. 
If I go through the reverse proxy I get an HTTP error 413  - Request entity too large.

I tried increasing the limits in nginx.conf but I cannot find any value that works. Here are my current settings:
client_max_body_size    	1000M;
client_body_buffer_size 	128k;
client_header_buffer_size 	64k;
large_client_header_buffers 32 64k;

I hope there will be a fix because I cannot bypass the reverse proxy when outside.

**Comment by gizmocuz** [comment]
@stas-demydiuk , sure it's possible, we already have a few API calls using POST
(m_pWebEm->RegisterPageCode)

**Comment by gizmocuz** [comment]
@Olivier6767 , could you check with the latest beta version (for example 10198+) to see if it is working now?

**Comment by Olivier6767** [comment]
@stas-demydiuk, I just tested with release 10198 and my longest script. It works perfectly, no more issues saving changes, even when accessing through the reverse proxy.

Thanks!

**Comment by gizmocuz** [comment]
Thanks for the feedback
