### ISSUE TITLE
Wifi controller: Arilux AL-LC0x not functioning in a Group

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#2837]
Beta versions...
The hardware Arilux AL-LC0x wifi rgbw controller is not working when i use this hardware ( or a light from this hardware ) in a group.
When i use a switch from this hardware the light is working great.
When i try to use this in a group alone or with other lights.
Sometimes Domoticz crashes.

**Comment by waltervl** [comment]
Is this still an issue in latest stable 2022.1 or beta?
