### ISSUE TITLE
Problem with timers and updating domoticz at the same time

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#2845]
Domoticz 4.10174

Switch with simple timer On/Off
Timer On set On Time = 15.00
Timer Off set On Time = 16.00
I started updating domoticz about 15.59 (domoticz started after 16.00). Or for example stopped domoticz, when some timer has to be execute.
Timer set to 16 o'clock did not work.
The switch was turned on until 16.00 the next day

**Comment by gizmocuz** [comment]
Why would you do this ? and i see two ON timers. But please use the forum

**Comment by szczukot** [comment]
Why I upgrading domoticz?? it's probably a normal operation?
First timer is ON, second is OFF
