### ISSUE TITLE
Youless LS120; retrieve P1 and S0 at sime time

### ISSUE THREAD

**Issue by reharmsen** [domoticz/domoticz#2849]
The current YouLess implementation only allows P1 (Power and Gas) readouts in Domoticz.
With the 1.4 firmware both P1 and S0 can be used together.

In my case I am using a Youless for both P1 and S0 to also measure Solarpanels. (Youless installed yesterday) Would be nice when both P1 and S0 can be used natively in Domoticz.

See example JSON:
[YouLess.zip](https://github.com/domoticz/domoticz/files/2560722/YouLess.zip)

I am on Domoticz 4.9700

PS. Also see this forum post
https://www.domoticz.com/forum/viewtopic.php?t=22377

**Comment by gizmocuz** [comment]
Thanks for the log. Seems quite easy to implement this in the YouLess class of Domoticz...
(You should give it a try!, i just simplified the code for you)

In your log i see cs0 = 0.003 and ps0 = 0, could you contact me on the forum for a debug session ?

It might work in beta 10187 , it might not.... you should enable 'accept new hardware' in the settings to get a new sensor.
The values for usage and the counter might be a multiple of 1000 off, but it's hard to see then ps0 = 0

Remember if you can learn dzVents, you should be able to make a very small adjustment in the c++ code

**Comment by reharmsen** [comment]
Thanx for the updated code.

I'm not at home at the moment, so not able to update of check my domoticz instance. (Need to set this up)

Fortunately I can access my Youless remotely.
Current JSON shows:
cs0": 7.859,"ps0": 87,

This corresponds to 7.859 kWh (almost 8 kWh on the counter) and 87 watt (current output)

I guess based on the code, the cs0 should be multiplied by 1000 (as the other counters are multiplied to).

I will be able to update and verify tomorrow at best.

**Comment by gizmocuz** [comment]
Thanks! Then i think it could work now... ;)

**Comment by reharmsen** [comment]
Yup, seems to be working great! (al least with 4.10198)
Thanks!

**Comment by loedeman** [comment]
As @reharmsen says, I also confirm this to be working great on 4.10.199. Thanks a lot @gizmocuz!

**Comment by mcmikev** [comment]
I also have the youless but only connected to the S0 bus and do not use the P1 meter.
With old FW in the Youless I see the solar generated power , but with new firmware 1.4.1 and latest beta (build from source) 4.10199 I see no new device with accept new hardware turned on.
What do I mis?
Device and firmware:
Model: LS120
Firmware versie: 1.4.1-PO

**Comment by mcmikev** [comment]
I reverted back to firmware 1.3.4.PO2 to get the update again from my solarpanels.
Let domoticz accept new hardware the whole night and restarted the youless etc. but no result.

**Comment by reharmsen** [comment]
@mcmikev 
Can you post a sample JSON? You can get one by browsing to /e on the YouLess.
I will try to check/debug the code with this, to see whether I can find the issue.

Is there anything in the log of Domoticz about the YouLess?

**Comment by mcmikev** [comment]
Thanks for te response. Just reflahsed again with 1.4.1.PO and did what you asked.

result of /e 
d=20181115&t=09:01&v1=7119&v2=109&c1=1

**Comment by mcmikev** [comment]
where v1=7119 my current S0 counter is on de youless page in 7,119 kWh

**Comment by gizmocuz** [comment]
I was expecting JSON output from the /e command... is this what you get ?
If this is the output, can you try /e?f=j

**Comment by mcmikev** [comment]
did the command (in firefox if that matters) and result is : d=20181115&t=09:21&v1=7166&v2=166&c1=1

command executed : 
http://192.168.x.x/e?f=j

**Comment by mcmikev** [comment]
I read on a page that this format is the PV output format
I have the PO firmware that includes the script to upload the output to pvoutput.org

source of info : http://wiki.td-er.nl/index.php?title=YouLess
PV output firmware

Th non JSON format output is in the format described on the PVoutput site:

 d=20170817&t=22:56&v1=0&v2=0&c1=1&v3=1935267&v4=570

**Comment by mcmikev** [comment]
just flashed the enelogic version of the firmware for the youless and then the output is
[{"tm":1542270655,"net": 26.909,"pwr": 0,"ts0":1542270686,"cs0": 7.195,"ps0": 0}]

**Comment by mcmikev** [comment]
With enelogic firmware I do see the Youless S0 device being added :-)
With PVoutput firmware it does not work. At least a conclusion. But can that be added as well?

**Comment by gizmocuz** [comment]
Love that wiki

v2: ????? (Power Generated in Watt)

Looks to me that with the PVOutput

cs0 = v1
ps0 = ????

And it looks it does not contain the gas value ?

Maybe the script that you use that outputs data to pvoutput could use the json format ?

**Comment by mcmikev** [comment]
I don't use a custom script. It is an thing in the firware that uploads the statistics every 300 second to the pvoutput.org site (api)

**Comment by gizmocuz** [comment]
Okey, and this option is not available when you have json output ? If not, please request this @ YouLess

**Comment by reharmsen** [comment]
As this works (at least for me) let's Close the issue

**Comment by mcmikev** [comment]
Hi I have to get back to this issue. I have a youless ls120 connected with S0 to my din kwh meter on the S0 connectors. With old firmware there is no change and it is either P1 or S0 for the pulses.
With newer firmware you can have both, but my ls120 is only connected with S0 and not with P1.
Because of that it seems that the meter is not updated (someone on the forum explained that) but that is the only way for me and others to measure. Only on S0.
Can the code be changed to also update that reading in realtime / seconds?
When openening the http://ipyouless/e or /a ther is output. The /e in json style.
Had to go back again to old firmware in the ls120 otherwise no updates.

Can this be looked into please? Is it possible to only use the S0 and not P1???

**Comment by gizmocuz** [comment]
@mcmikev , sure we can look at this, but you could have a look as well in the YouLess.cpp code,
it is not complicated at all.
From what I see, both P1 and S0 are read and handled (S0 = cs0 and ps0 field)
Could you post the JSON output of the new Firmware that does not work ?
But if you could debug and make a PR that would also be great

**Comment by mcmikev** [comment]
Hi, thx for responding.

I have firmware 1.4.3-EL for this test in the Youless LS120
With /a the output is on 1.3.4-EL is:

/a:
 3778,633 kWh
379 Watt
0%  
OK (227)
0

on 1.4.3-EL it is:
/a:
 3778,647 kWh
0 Watt
1%  
* 
 8,162 kWh
369 Watt
0

/e?f=j output on 1.4.3.-EL is:
[{"tm":1580390283,"net": 3778.647,"pwr": 0,"ts0":1580390370,"cs0": 8.165,"ps0": 367}]

The last part is the S0 value and is updating on the webpage and If i refresh the page (/e?f=j)
However under domoticz the value of the meter is updated only at hardware start.
Refreshing domoticz does not change the value. Only hardware stop/start will update.

**Comment by gizmocuz** [comment]
@mcmikev , i send a email to the address that is registered in the Forum
