### ISSUE TITLE
winddelen counter should reset to 0 in new year

### ISSUE THREAD

**Issue by AntoineVDH** [domoticz/domoticz#285]
The total counter is not reset to 0 at new years eve. As the total kWh is received per year from the backend server, the reset should also be done on the domoticz.

**Comment by AntoineVDH** [comment]
![schermafdruk van 2016-01-02 17 55 03](https://cloud.githubusercontent.com/assets/16518553/12075234/023b6842-b17a-11e5-998d-50a2ef6dc3c8.png)

**Comment by gizmocuz** [comment]
You can shift-click the large value to delete it

**Comment by gizmocuz** [comment]
Please use our forum, as the author of the winddelen implementation is also on there
