### ISSUE TITLE
New Switch Type: KNX

### ISSUE THREAD

**Issue by emme73** [domoticz/domoticz#2852]
Could it be possible to add a new manual switch model type:
Type: Switch/Dimmer/Blinds (with percentage)
Model: KNX
ID splitted into 3 groups:
Group1: values 0..31
Group2: values 0..7
Group3: values 0..255
since Groups will compose the device ID, this would be really helpful in let Domoticz communicate with a KNX bus using an external system (via MQTT)
thanks

**Comment by gizmocuz** [comment]
That would be possible... what hardware are you using ? I have some Gyra hardware
Why can't you use the current switch types in domoticz ? (general switch that has 255 dimmer values)

**Comment by emme73** [comment]
Actually I'm using a nodered flow to get both KNX (IP Tunnel using KNXjs node) and Domoticz (via MQTT) telegrams and synch the status between the two
Actually I'm able to exchange only 1bit values (on/off, up/down, stop), I've tried with rolling shutters position (1byte) but looks too difficult to get synch for messages looping.
The node use a table to cross reference the domoticz ID with the KNX group, so having the ID within the MQTT domoticz telegram will avoid to keep changing the table all the time a change is made

More... some switches (like rolling shutters) will use more than 1 group: ON/Off (1bit), stop (1bit), position (1byte)
It would be nice to draw an hardware connector (like the one done for OpenWebNet), but unfortunately Unfortunately, I do not have enough knowledge to do that (but I know KNX protocol)
Thanks
ciao
m

**Comment by gizmocuz** [comment]
@emme73 , thats for the explanation but i am not sure i follow you...
We have many switch types in domoticz already. Almost any switch can be configured to be a specific type, a on/off, a dimmer, a roller shutter etc...
A switch has a 32bit ID and a 8 bit unit value. You should be able to do all 1-bit KNX switching with this ?
So i suggest to use the default general switch type for this. (From the hardware setup, add a dummy hardware if you did not do this already.., and add a switch)

**Comment by emme73** [comment]
@gizmocuz you are right.... other switches type can be adapted to this role....
I'll try to figure out using this...
In the meanwhile it would be nice to implement a KNX connector to fully support this bus.... :P 
I think this request can be closed with no solution. 
thanks
ciao
M

**Comment by gizmocuz** [comment]
Hope you find a way!
