### ISSUE TITLE
Feature Request: Upload Floorplan image from GUI

### ISSUE THREAD

**Issue by correa** [domoticz/domoticz#2853]
Currently the floorplan background image must be copied to www folder with some file transfer tool such as scp. It would be nice to be able to upload from the GUI itself, like icons can currently.

**Comment by sweetpants** [comment]
Feature requests are discussed on the forum. Github is for bugfixes only.
To answer your question, if you are on latest Beta, you can upload floorplans already. They are stored in the database now
