### ISSUE TITLE
Install script does not chown data to current user

### ISSUE THREAD

**Issue by tvwerkhoven** [domoticz/domoticz#2858]
The install script (from install.domoticz.com) does not chown files to the current user, and instead inherits file permissions from the release file. The fix is simple:

```
--- install_domoticz.sh	2017-09-09 14:11:41.000000000 +0200
+++ install_domoticz_fixed.sh	2018-11-10 14:28:49.607054107 +0100
@@ -367,6 +367,7 @@
 	echo "::: Unpacking Domoticz..."
 	tar xvfz domoticz_release.tgz
 	rm domoticz_release.tgz
+	chown --recursive "${Current_user}":"${Current_user}" *
 	Database_file="${Dest_folder}/domoticz.db"
 	if [ ! -f $Database_file ]; then
 		echo "Creating database..."
```

**Comment by gizmocuz** [comment]
no issues here... all is owned by the 'pi' user...

**Comment by tvwerkhoven** [comment]
Yes, that's the issue, the script only works for user 'pi', not any other user (e.g. `domoticz`). This `chown` fixes that :)

**Comment by gizmocuz** [comment]
hmmm why is this happening ? there is no reference for the pi user in the install script at all ?
It should for any user that has sudo rights

**Comment by tvwerkhoven** [comment]
I think it’s because the files are owned by user pi inside the tar.gz file and the permissions are retained when unpacking. Can that be?

**Comment by gizmocuz** [comment]
That could very well be the case... maybe it needs to be unpacked differently, but from my understanding this only happens when the 'user' exists on the system. Does the pi user exists on your system? If yes, why not use it ?

**Comment by gizmocuz** [comment]
No response, closing issue
