### ISSUE TITLE
DzVents TELEGRAM subsystem errorcode 400 messag must be non-emtpy

### ISSUE THREAD

**Issue by delcara** [domoticz/domoticz#2859]
Version: 4.10197
Build Hash: 90c95998
Compile Date: 2018-11-11 15:33:34
dzVents Version: 2.4.7

When I use NSS_TELEGRAM as notify subsystem in DzVents I get the following error from the Telegram API:
Error: Telegram: {"ok":false,"error_code":400,"description":"Bad Request: message must be non-empty"}

**Comment by gizmocuz** [comment]
Please use our forum. (dzVents section)
