### ISSUE TITLE
issue with backupdatabase.php

### ISSUE THREAD

**Issue by jbfenris** [domoticz/domoticz#2862]
I try to backup my Domoticz configuration using backupdatabase.php either though the web interface or by calling directly the URL using curl command but in both case I just receive an empty file.

I'm using the last beta version 4.10199 on Raspberry Pi

**Comment by rwaaren** [comment]
Please have a look at the forum. A similar issue was posted there and could be set to solved.

https://www.domoticz.com/forum/viewtopic.php?t=23062#p177730

**Comment by jbfenris** [comment]
The only solution is to copy the DB file, the backupdatabase.php doesn't work anymore even if I follow the proposed solutions in the forum.

Here is some details of the curl command on the backup URL

curl -v http://192.168.1.21:8080/backupdatabase.php > test.db                                          
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.1.21...
* TCP_NODELAY set
* Connected to 192.168.1.21 (192.168.1.21) port 8080 (#0)
> GET /backupdatabase.php HTTP/1.1
> Host: 192.168.1.21:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0< HTTP/1.1 200 OK
< Content-Length: 0
< Content-Type: text/html;charset=UTF-8
< Cache-Control: no-cache
< Pragma: no-cache
< Access-Control-Allow-Origin: *
< Set-Cookie: SID=bce42ac83745833397c2a3fdbefe65f0_NzMyMzNmOTAtMjRjNy00MTlmLWE2NGEtOTcxYzE0NTQxOTNi.1542143843; HttpOnly; path=/; Expires=Tue, 13 Nov 2018 21:17:23 GMT
<
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
* Connection #0 to host 192.168.1.21 left intact
