### ISSUE TITLE
www.domoticz.com forum does not send email

### ISSUE THREAD

**Issue by crashcoq** [domoticz/domoticz#2865]
Hello

I can't activate my account on domoticz forum
My account is open from many years but it's now inactive
i have this message "The specified username is currently inactive. If you have problems activating your account, please contact a board administrator."

but i can't find "contact us" on the forum ...

could help me?

**Comment by gizmocuz** [comment]
Hmm most users find a way to send me a direct email....
whats your username?

**Comment by crashcoq** [comment]
my username is david31
my mail is david.m*****te@free.fr

**Comment by gizmocuz** [comment]
Please try now

**Comment by crashcoq** [comment]
It work fine
For my information, where I can find the link for contact administrator without a valid account?

Thanks for your reactivity 
Cordially

**Comment by gizmocuz** [comment]
@crashcoq , no idea, but when people are having registration issues then i receive mails...
Great it's working again!
