### ISSUE TITLE
Enhancement: information to make logrotate work. please implement if suitable

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#2868]
logrotate on Synology(and other platforms) does not work because the domoticz.log file gets locked.
you can copytruncate which empties the file but because domoticz constantly writes to it it jumps back to the old file size. result, empty logfile but very big in size because it still contains spaces.

The solution instead of writing to the logfile (use >) we need to append to the logfile (>>)

in the start-stop-status script or in the install script(depending on platform) we need to change

rm -f $LOGFILE  (removes the old logfile if it exists or not)
touch $LOGFILE (makes a new logfile)

in the domoticz startup line we use >> instead of >  (APPEND to file instead of WRITE to file)

now when logrotate kicks in the logfile rotates and copytruncate is able to empty the file(filesize 0 bytes)
because we use APPEND to this file (>>) we append to 0 bytes eg the logfile grows from 0

i tested this and it works on synology and will problably work on any other platform which has the same problem(keeping the logfile locked when writing to it)

Jumbotroll allready changed this in the synology package so all synology owners can now have a normal working logrotate

**Comment by gizmocuz** [comment]
How about when you use the commandline to specify the log file, and use the sig-hup method to do the log rotation?

**Comment by GravityRZ** [comment]
as far as i can tell it is using the commandline to specify the logfile but is is piping/writing into a new logfile by using >. al i did was changing that into a >> command

i tried kill -HUP(if that's th same as sig-hup) but domoticz did not like that.

anyway if i can choose for a methode which does not disrupt an application in any way that might be the better solution.

`su ${USER} -c "${DOMOTICZ} -www ${PORT} -wwwroot ${WWWROOT} -sslwww ${RSSLPORT} -sslcert ${RSSLCERT} -approot ${INSTALL_DIR}/ -userdata ${INSTALL_DIR}/var/ -dbase ${DB_FILE} &>> $LOGFILE & echo \$! > ${PID_FILE}"`

if you can specify a sigkill command i need to use on domoticz synology i will be happy to try but either way somewere changes need to be made.
a very simple one in the start-stop-status script so copytruncate(instead of postrotate) works and will not disrupt any process or more commands in the logrotate file to force domoticz to open a new logfile and start writing to that one.

i googled a lot and nobody solved this issue on synology(not with a sig KILL, not with a change of script, not with a restart of the package).
if it was that simple to use a kill command to restart(not restarting domoticz completely) to force writing to a new log file why did nobody think of that before

**Comment by gizmocuz** [comment]
sorry, i meant using the commandline (not piping to the log) via -log
if you look in the signalhandler.cpp you will see how the log file is rotated.
this was created via a pull request from another developer, and it looks this is also the correct way for deamons to rotate log files

**Comment by GravityRZ** [comment]
ok, i understand. since this aparently is not a problem any more for other platforms but only synology i think we can let this one go.
Jumbotroll already implemented my solution in his package because it was so easy and does not conflict with any original code.

**Comment by gizmocuz** [comment]
@GravityRZ , still it's good to know if the default method would also work for others

**Comment by GravityRZ** [comment]
agreed. but this means  Jumbotroll still needs  to test/change things.
i can probably test something to see how things work.

-log i can test to see what type of logfile is created(if this is in append mode we are done and can use copytruncate)
if this file is still in write mode we need to use a command to create a new log file
something like kill -HUP pid.
in the end we will get the same result

**Comment by GravityRZ** [comment]
did some testing of my own.

the -log function creates the logfile in APPEND mode so this works really well and we do not need sigkill but we can use copytruncate.

i am closing this one.
Thanks for pointing us in the right direction.

initially i solved the problem an other way but by using the -log function it now complies to the original code.

Still the synology script needed modification but since this was really easy as well Jumbotroll implemented the -log function.
