### ISSUE TITLE
Removed notifcation rule send message

### ISSUE THREAD

**Issue by bgommers** [domoticz/domoticz#2869]
In Domoticz V4.10213 a disabled or removed/deleted notification rule sends messages. Also unchecking the notification type ‘http’ (which I am using) makes no sense.

**Comment by sweetpants** [comment]
Please supply more information how to re-produce and what device type, explain _"the notification type ‘http’ (which I am using) makes no sense."_

**Comment by bgommers** [comment]
Using "DarkSky (Weather Lookup)" with a notification on "Temperature and Wind"-device (Type 'wind' and subtype 'TFA') when temperature drops below zero. The notification has 'http' as the active system.

Because 'Ignore Interval' is checked Domoticz sends a message every minute (after an update of Darksky) which is a bit too much.

By disabling all active systems except 'browser' I tried to stop sending the message, but gave no result. Because it is not that hard to re-enter the notification I deleted the notification entirely, but the sending messages from the Darksky "Temperature and Wind"-device didn't stop. In the end I disabled the Darksky-hardware in order to prevent messages being send.

On the internet I found another example which looks like it is pretty much the same: https://www.domoticz.com/forum/viewtopic.php?t=25602.

If you need more information, just let me know.

**Comment by sweetpants** [comment]
If you select 'below' a certain temperature, then it's normal that the notification is triggered on every update. Domoticz just does an API call and tests the notification criteria which is valid if the temperature is below it. This is WAD as far as i know.

I have tested this with Darksky (BTW, it updates every 5 minutes, not 1 minute on my system)

About the deleted notification still being triggered, i can't confirm this. After deleting it I do not get any notifications anymore.

**Comment by bgommers** [comment]
The notification being triggered is not the issue. It is not what I really wanted, but it works as expected.

About the notifications, where are they stored? And is there any possibility to check if the notification is deleted correctly?

**Comment by gizmocuz** [comment]
They are stored in memory (NotificationHelper class), and when a notification is deleted, it calls 'RemoveNotification' and this function calls 'ReloadNotifications', so yes this "should" work correctly as planned
