### ISSUE TITLE
Selector switch floorplan has limited options

### ISSUE THREAD

**Issue by ericstaal** [domoticz/domoticz#2870]
The selector list item on the floorplan has less options than the selector on the dashboard:

![selector](https://user-images.githubusercontent.com/16288222/48671181-d3d37200-eb24-11e8-961f-53635c518d6d.png)

and on the dashboard:
![selector](https://user-images.githubusercontent.com/16288222/48671209-0a10f180-eb25-11e8-9dff-db2af5a9108e.png)

**Comment by gizmocuz** [comment]
I think what you want to do has not much to do with home automation.
A solution could be multiple selector switches...
