### ISSUE TITLE
Implementing cereal

### ISSUE THREAD

**Issue by rkluwen** [domoticz/domoticz#2871]
I created the two template functions in CDomoticzHardwareBase below.

The use case is:

	_tTempBaro ExampleTemperature;
        // to serialize, do:
	std::string serialized = Serialize<_tTempBaro>(ExampleTemperature);
        // to reconstruct, do:
	ExampleTemperature = Deserialize<_tTempBaro>(serialized);

Code:

class CDomoticzHardwareBase : public StoppableTask
{
public:
...............................
	template <typename StructType>
	static std::string Serialize(StructType buf)
	{
		std::stringstream stream;
		{ // we start a new scope, so the archive flushes to the stream upon destruction
			cereal::PortableBinaryOutputArchive oarchive(stream);
			oarchive(buf);
		}
		return stream.str();
	};

	template <typename StructType>
	static StructType Deserialize(std::string str)
	{
		std::stringstream stream(str);
		cereal::PortableBinaryInputArchive iarchive(stream);
		StructType result;
		iarchive(result);
		return result;
	};
}

**Comment by rkluwen** [comment]
Now, do we have all the RFX types implemented as structures already?
There needs to be a way to convert one to the other. Maybe a special copy constructor as in:

_tTempBaro  {
         _tTempBaro (RBUF buf) {
                 baro = buf.BARO.baro1;
                 // etc.
         }
}

**Comment by waltervl** [comment]
Closing this very old issue. If needs work please reopen.
