### ISSUE TITLE
Gust wind conversion error in dzvents

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#2872]
Domoticz Version 4.10.213

I have a Netatmo weather station including the wind sensor. The wind sensor in domoticz is show as type Wind, subtype Weather Station.
The values for Speed and Gust in the Domoticz sensor are stored as 10 * m/s.
When retrieving the values in dzvents it appears that the Speed value is calculated correctly (converted to km/h). However the Gust value is always calculated to m/s. It should also be converted to km/h.

Example:
```
local WindMeter = domoticz.devices('Netatmo_Wind')
domoticz.log('WindMeter = ' .. WindMeter.state, domoticz.LOG_DEBUG)
domoticz.log('Speed = ' .. WindMeter.speed .. ' km/h', domoticz.DEBUG)
domoticz.log('Gust = ' .. WindMeter.gust .. ' km/h', domoticz.DEBUG)

```
WindMeter = 6.00;N;19;44;0.0;0.0
Speed = 6.8000001907349 km/h
Gust = 4.4 km/h            <=== This value is wrong, it should be 15.84 km/h

Can this be corrected so the values for Wind and Gust a re reported in the same unit? Thanks.

**Comment by rwaaren** [comment]
Please don't change this. It would cause many weather related scripts to report wrong values for Gust.
Not every weather station fill the sValue of wind devices using the same unit. Some do in m/sec, others in Bf. and maybe some in km/h. My preference would be to do the conversion to the required unit in the user script and not in dzVents wind device adapter.

**Comment by gizmocuz** [comment]
Yes i agree, if it's stored internally in m/s, then the scripts should do the conversion

**Comment by Olivier6767** [comment]
I agree with you that conversions should be done in the user script.

What I was trying to explain is that there is an inconsistency in the way the values are made available in dzVents.

**Example**
`sValue of wind device is : 6.00;N;19;44;0.0;0.0`

**Domoticz API documentation**
WS = 10 * Wind speed [m/s]
WG = 10 * Gust [m/s]

So in the example above, WS = 1.9 m/s and WG = 4.4 m/s

**However in dzVents, if I do:**
```
local WindMeter = domoticz.devices('Netatmo_Wind')
domoticz.log('sValue = ' .. WindMeter.state)
domoticz.log('WS = ' .. WindMeter.speed)
domoticz.log('WG = ' .. WindMeter.gust)
```

**The result is:**
```
sValue = 6.00;N;19;44;0.0;0.0
WS = 6.8000001907349
WG = 4.4
```

This means that dzVents DOES convert the WS value to km/h (which is my default setting in Domoticz/Settings), but it converts WG to m/s. So there is an inconsistency in which unit is used between WS and WG.

I'm fine with either:
- returning both values to the unit chosen as default by user in Domoticz/Settings
- returning both values in m/s

II just think it should be done consistently between WS and WG.

**Comment by rwaaren** [comment]
My observations ( while using the same sValues )  are different. Using this function

    local function wind()
        local windDevice = dz.devices(841)
        logWrite("windDevice.state " .. windDevice.state)
        logWrite("windDevice.speed " .. windDevice.speed)
        logWrite("windDevice.gust  " .. windDevice.gust)
        for i = 1,#windDevice.rawData do
            logWrite(windDevice.name .. "  rawdata[" .. i .. "] " .. windDevice.rawData[i])
        end
        for i = 1,#windDevice._adapters do
            logWrite(windDevice.name .. "  adapter[" .. i .. "] " .. windDevice._adapters[i])
        end
        
    end

The loglines are:

    2018-11-21 12:59:00.836  Status: dzVents: Info:  Dumper: ------ Start external script: dumper.lua:, trigger: every minute
    2018-11-21 12:59:00.838  Status: dzVents: Debug: Dumper: Processing device-adapter for wind Rotterdam: Wind device adapter
    2018-11-21 12:59:00.838  Status: dzVents: Debug: Dumper: windDevice.state 6.00;N;19;44;0.0;0.0
    2018-11-21 12:59:00.838  Status: dzVents: Debug: Dumper: windDevice.speed 2
    2018-11-21 12:59:00.838  Status: dzVents: Debug: Dumper: windDevice.gust  4.4
    2018-11-21 12:59:00.839  Status: dzVents: Debug: Dumper: wind Rotterdam  rawdata[1] 6.00
    2018-11-21 12:59:00.839  Status: dzVents: Debug: Dumper: wind Rotterdam  rawdata[2] N
    2018-11-21 12:59:00.839  Status: dzVents: Debug: Dumper: wind Rotterdam  rawdata[3] 19
    2018-11-21 12:59:00.839  Status: dzVents: Debug: Dumper: wind Rotterdam  rawdata[4] 44
    2018-11-21 12:59:00.839  Status: dzVents: Debug: Dumper: wind Rotterdam  rawdata[5] 0.0
    2018-11-21 12:59:00.839  Status: dzVents: Debug: Dumper: wind Rotterdam  rawdata[6] 0.0
    2018-11-21 12:59:00.839  Status: dzVents: Debug: Dumper: wind Rotterdam  adapter[1] Wind device adapter
    2018-11-21 12:59:00.840  Status: dzVents: Info:  Dumper: ------ Finished dumper.lua

My setting in Domoticz/Setting is beaufort for windSpeed. I am not sure what the standard in other countries is for reporting windGust but in the Netherlands it is either m/s or Km/h.
So maybe we need another Setting for windGust in Domoticz/Settings ?

**Comment by Olivier6767** [comment]
If I change my settings (Domoticz/Settings) to m/s for Wind device, then the script will report the same as your results, meaning both values are sent back in m/s.

So this confirms that in dzVents, windDevice.speed converts the value to the unit defined in Domoticz/Settings, while windDevice.gust always converts to m/s.

I think both values should be reported in the same unit.

**Comment by rwaaren** [comment]
That is not what I think is happening. dzVents just reports what it gets from domoticz core. There is no other manipulation of that data than a division by 10.
As in my previous comment; in the Netherlands reporting of windspeed is done in a different unit (Bf) then reporting of windgust. (m/sec or km/h). So my preference would still be to do the conversion in the user script or (even better) to add another setting in the domoticz/Setting page for windgust

**Comment by Olivier6767** [comment]
If you are correct and the unit setting in Domoticz/Settings is only for WindSpeed, then should be a setting for WindGust.
If the setting was for all wind values, then it is a bug and WS and WG should be reported in the same unit in dzvents.
Either way would be fine, but the current situation is not clear.

**Comment by gizmocuz** [comment]
The setting in the settings should of course be for both
If you look in the weather tab, is it displayed correctly ? If yes, it's a dzVents issue, if not, it's a internal issue

**Comment by Olivier6767** [comment]
I confirm that in the weather tab, both wind and gust use the unit defined in settings. If I change the unit in settings, both wind and gust will be reported in the new unit.
I agree that it is a dzvents issue. In dzvents both wind and gust should be reported in the same unit, either the one defined in settings, or always m/s.

**Comment by rwaaren** [comment]
OK will pick it up with @dannybloe because I don't see any conversion in either C++ or Lua part of dzVents

**Comment by rwaaren** [comment]
in dzVents 2.4.9 we implemented speedMs and gustMs for wind devices. speed and gust are still available with the remark in the wiki documentation that gust is now presented in M/s but that this could change in the future and that it might than follow the same conversions as speed.

**Comment by Olivier6767** [comment]
Great!
Thanks!
