### ISSUE TITLE
Milight - Limitless luck of options

### ISSUE THREAD

**Issue by Takisg** [domoticz/domoticz#2873]
The milight hardware has only the options of 

RGBW
CCT
RGB+CCT
RGB

There are new products that pair only with FUT089 / B8 or FUT091 /B2

Please add the new type of remote controls

**Comment by gizmocuz** [comment]
You need to be 'way' more specific...

What hardware ? FUT089 ? (it's a remote i guess) ?

**Comment by Takisg** [comment]
My setup is:

FUT089 is a 8-Zone RGB+CCT Remote Controller.
Milight ibox2 wifi box
LS2 5 IN 1 Smart LED Controller
FUT105 12W RGB+CCT LED Bulb

All these works with the remote controller and with the android application + ibox2

Also i have make a esp8266_milight_hub (esp8266 + NRF24L01+) and it also works well when i select "FUT089 / B8" like the original remote.

Domoticz does  not work.

FUT089 send other codes...

**Comment by Takisg** [comment]
Maybe the following  links can help  someone to understand the differences to the code...

https://github.com/sidoh/esp8266_milight_hub/blob/master/lib/MiLight/FUT089PacketFormatter.h

https://github.com/sidoh/esp8266_milight_hub/blob/master/lib/MiLight/FUT089PacketFormatter.cpp

**Comment by waltervl** [comment]
This old issue is closed.
