### ISSUE TITLE
Report tab empty (4.10216)

### ISSUE THREAD

**Issue by jivonl** [domoticz/domoticz#2876]
V4.10216 Build Hash: 3a7bedee Build Date: 2018-11-20 10:09:10

i cannot see Report status of power (or gas)
![image](https://user-images.githubusercontent.com/2757391/48839086-97a14b00-ed8a-11e8-8af5-bf1f04119f16.png)
Report tab is empty (all the years)
![image](https://user-images.githubusercontent.com/2757391/48839104-a556d080-ed8a-11e8-8ba8-e485b698e77a.png)

**Comment by sweetpants** [comment]
I'm on the same version, no problems here

**Comment by gizmocuz** [comment]
Please clear your browser cache and appcache (two different things) and use the forum

**Comment by jivonl** [comment]
Edge is indeed working fine. (it was on multiple devices with chrome) please close this ticket. Thnx
