### ISSUE TITLE
Python plugin crash (SVT)

### ISSUE THREAD

**Issue by twpeltenburg** [domoticz/domoticz#2879]
I get the following error when trying to use Smart Virtual Thermostat.
Domoticz version: V4.10224 (latest beta)
Python version: 3.4.2
OS: Raspberry Pi (Debian Jessie)

2018-11-21 23:56:36.176 Error: Domoticz(pid:6271, tid:6277('PluginMgr')) received fatal signal 11 (Segmentation fault)
2018-11-21 23:56:36.176 Error: siginfo address=0xa8293f40, address=0x7205a8

I do not believe this is an issue with SVT itself, but more a Python issue. When I enable the hardware Domoticz completely crashes. The only thing I get from the log is stated above. When I disable the hardware everything is fine.

I have tried multiple Python versions. Any idea?

**Comment by pipiche38** [comment]
@twpeltenburg  did you have a look to that issue : https://github.com/domoticz/domoticz/issues/1605

**Comment by pipiche38** [comment]
looks like other users are getting the same with an other plugin !

https://github.com/sasu-drooz/Domoticz-Zigate/issues/252#issuecomment-441328483
