### ISSUE TITLE
Settings change to Fahrenheit confuses homebridge

### ISSUE THREAD

**Issue by gknops** [domoticz/domoticz#2883]
When I change the Settings/Temperature to display in Fahrenheit, Homekit (via home bridge) interprets the Fahrenheit as if it were celsius. Changing the setting back to Celsius and Homekit shows the temperature correct.

Example:

Settings: Celsius (correct)
Domoticz: 0ºC, Homekit 32F

Settings: Fahrenheit (wrong)
Domoticz: 32F, Homekit: 90F (32ºC)

Homebridge or domoticz bug?

**Comment by gizmocuz** [comment]
Homebridge, you are in the wrong forum.
When homebridge is using the json 'getconfig' it will receive the scaling
