### ISSUE TITLE
CSS issue mobile Safari Events page (endless expanding)

### ISSUE THREAD

**Issue by tjdevdev** [domoticz/domoticz#2892]
In 'bootstrap.css'  the class '.container-fluid' (should be line 594) contains 'padding-right: 20px;'. In mobile Safari, after choosing an event, this padding causes the code edit box to expand endlessly to the right. This prevents selecting any other Event or saving the event. Scrolling to the right is not possible.

If not absolutely necessary either removing 'padding-right: 20px;' works or adding Safari specific css after the initial "padding-right", eg:

.container-fluid {
    padding-right: 20px;
    -webkit-padding-end: 0px;
  padding-left: 20px;
  *zoom: 1;
}

**Comment by gizmocuz** [comment]
@tjdevdev , what domoticz version are you using ? Is this with the new editor ?
Is this the only place with this problem ? If yes, we could add this in the event editor html/style ?

**Comment by tjdevdev** [comment]
The behaviour was already present in 3.8153, but also in the new version 4.9700 & 4.9701. 
I only see the 'text box expanding issue' on the Events page (Setup > More options > Events).  
Haven't noticed any adverse effect by adding the webkit CSS line. 

Note: Editing on mobile Safari is far from perfect, but at least with the event right side menu visible it is possible to enable/disable events or do small changes in the scripts.

**Comment by gizmocuz** [comment]
Could you try with the latest beta and the new event editor ?

**Comment by Reneke43** [comment]
I've had the same issue with the release versions. I can confirm this is gone with the new event editor. I'm currently using version 4.10234

**Comment by gizmocuz** [comment]
@Reneke43 , thanks for the confirmation !
