### ISSUE TITLE
JSON.lua not included but required by dzVents

### ISSUE THREAD

**Issue by sander1988** [domoticz/domoticz#2893]
The Domoticz Utils.lua tries to include the JSON.lua library, but it's not included in the Domoticz release.

**Error:**
/opt/domoticz/dzVents/runtime/dzVents.lua: /opt/domoticz/dzVents/runtime/Utils.lua:56: module 'JSON' not found:
        no field package.preload['JSON']
        no file '/usr/local/share/lua/5.2/JSON.lua'
        no file '/usr/local/share/lua/5.2/JSON/init.lua'
        no file '/usr/local/lib/lua/5.2/JSON.lua'
        no file '/usr/local/lib/lua/5.2/JSON/init.lua'
        no file './JSON.lua'
        no file '/var/lib/domoticz/scripts/dzVents/JSON.lua'
        no file '/opt/domoticz/dzVents/runtime/JSON.lua'
        no file '/opt/domoticz/dzVents/runtime/device-adapters/JSON.lua'
        no file '/var/lib/domoticz/scripts/dzVents/dzVents/JSON.lua'
        no file '/var/lib/domoticz/scripts/dzVents/scripts/JSON.lua'
        no file '/var/lib/domoticz/scripts/dzVents/../lua/JSON.lua'
        no file '/var/lib/domoticz/scripts/dzVents/scripts/modules/JSON.lua'
        no file '/var/lib/domoticz/scripts/dzVents/JSON.lua'
        no file '/var/lib/domoticz/scripts/dzVents/generated_scripts/JSON.lua'
        no file '/var/lib/domoticz/scripts/dzVents/data/JSON.lua'
        no file '/var/lib/domoticz/scripts/dzVents/modules/JSON.lua'
        no file '/var/lib/domoticz/scripts/dzVents/JSON.lua'
        no file '/var/lib/domoticz/scripts/dzVents/JSON.lua'
        no file '/usr/local/lib/lua/5.2/JSON.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './JSON.so'

I fixed it by adding the JSON.lua manually (from http://regex.info/blog/lua/json) and put the file in /opt/domoticz/dzVents/runtime/ .

But shouldn't this file be included in the Domoticz release?

I'm running Domoticz version 4.9700 . Tested on both Ubuntu (x64) and RPI.

**Comment by sweetpants** [comment]
I would suggest to upgrade to latest Beta first. No problem here with dzVentz

**Comment by rwaaren** [comment]
The file JSON.lua should be in domoticz/scripts/lua as it is used by lua scripts.
dzVents is 100% lua and will find the JSON if it is in this place.
