### ISSUE TITLE
compiler error on SQLHelper

### ISSUE THREAD

**Issue by gordonb3** [domoticz/domoticz#2895]
I'm receiving an error on SQLHelper since it was last changed:

    {standard input}: Assembler messages:
    {standard input}:80112: Warning: end of file not at end of a line; newline inserted
    i686-pc-linux-gnu-g++: internal compiler error: Killed (program cc1plus)
    make[2]: *** [CMakeFiles/domoticz.dir/build.make:519: CMakeFiles/domoticz.dir /main/SQLHelper.cpp.o] Error 4
    make[2]: *** Deleting file 'CMakeFiles/domoticz.dir/main/SQLHelper.cpp.o'
    make[2]: *** Waiting for unfinished jobs....

The fix appears to be to add a newline to the end of the file, but for some reason git doesn't pick up that change so I can't push it.

**Comment by gordonb3** [comment]
...and it gets even more ugly on the crossdev chain:

    {standard input}: Assembler messages:
    {standard input}:65788: Error: undefined local label `.L10297'
    {standard input}:65789: Error: undefined local label `.L10297'
    armv5tel-softfloat-linux-gnueabi-g++: internal compiler error: Killed (program cc1plus)
    make[2]: *** [CMakeFiles/domoticz.dir/build.make:519: CMakeFiles/domoticz.dir/main/SQLHelper.cpp.o] Error 4
    make[2]: *** Waiting for unfinished jobs....

**Comment by gizmocuz** [comment]
I can't see anything wrong with it....:

```
[ 23%] Building CXX object CMakeFiles/domoticz.dir/main/LuaHandler.cpp.o
[ 23%] Building CXX object CMakeFiles/domoticz.dir/main/mainworker.cpp.o
[ 24%] Building CXX object CMakeFiles/domoticz.dir/main/Scheduler.cpp.o
[ 24%] Building CXX object CMakeFiles/domoticz.dir/main/SignalHandler.cpp.o
[ 24%] Building CXX object CMakeFiles/domoticz.dir/main/SQLHelper.cpp.o
[ 24%] Building CXX object CMakeFiles/domoticz.dir/main/WebServer.cpp.o
[ 25%] Building CXX object CMakeFiles/domoticz.dir/main/WebServerHelper.cpp.o
```

looks like a memory issue... are you building on a raspberry ? (swap file enabled?)

**Comment by gordonb3** [comment]
As shown in the two log segments: x86 for test, cross-building on that same (virtual) machine for armv5te.

The problem appears to be that the file does not have a newline after the closing `}` and the compiler regards this as a breach of rules. For some reason if I open the file in either gedit or nano it appears to automagically add that extra newline and if I hit save the compile runs correctly, but as said git does not see any difference.

Maybe I should try `vi` and see if that picks up on anything weird, but I kind of have a hate-affair with that editor...

**Comment by gizmocuz** [comment]
In VStudio it looks normal... but anyway, that should not produce an error (nor warning) ...
Looking in github it also seems normal.
But feel free to make a patch if needed

**Comment by gordonb3** [comment]
Success!

`vi` did the job (PR #2901)

**Comment by gizmocuz** [comment]
Thanks! I merged your PR!
