### ISSUE TITLE
MQTT update device failed while api OK

### ISSUE THREAD

**Issue by pouicr** [domoticz/domoticz#2897]
Hi 

Currently in version 4.10213, I am having a problem with mqtt update cmd.

I am controlling plugs from mqtt without any issue (using switchligth cmd).

I tried controlling my westinghouse fan using the same principle but it fails.

While the API version is working:

`http://xxxx/json.htm?type=command&param=switchlight&idx=41&switchcmd=med`

The equivalent with MQTT `{"command":"switchlight","idx":41,"switchcmd":"med"}` is not valid which is coherent with controls done in https://github.com/domoticz/domoticz/blob/3741a530c2260cea2f337a095aa9477847fc00cb/hardware/MQTT.cpp#L253

So I change in flavor of `udevice` cmd.

I convert the API working JSON into the MQTT cmd.
it gives something like
```json
{"command":"udevice","idx":41,"nvalue":2}
```

Both are creating following JSON in domoticz/out:
```json
{"Battery":255,"RSSI":12,"description":"","dtype":"Fan","id":"000000","idx":41,"name":"Fan","nvalue":2,"stype":"Westinghouse","switchType":"On/Off","unit":0}
```

However, while the API is working fine the MQTT version does not work.

Am I doing something wrong? Is there a known issue?

**Comment by gizmocuz** [comment]
The problem is on line 260/261 ... this should not be checked like this.
Currently only a few commands are allowed now
Better to call 'GetLightCommand', and if that fails, then exit

If you can compile domoticz by source, you could try to remark those lines

**Comment by gizmocuz** [comment]
Hmmm it seems already been remarked in the current beta version, try upgrading

**Comment by pouicr** [comment]
Thx, I am using a docker image from Linux server not available in beta.
I'll find a way.

Thx anyway for your answer.
