### ISSUE TITLE
Hue bridge timeouts after bridge update

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#2898]
probably not a bug in domoticz (since i did not change anything) but yesterday i updated the hue bridge
after that i am getting an error that the bridge can not be reached

so this happens hours after the update and both bridge and domoticz were reset.

2018-12-04 11:49:00.604  Error: Philips Hue: Error getting Light States, (Check IPAddress/Username)

BSB002 1810251352 updated 2-12-2018

domoticz v10224

any body else noticed this?

**Comment by gizmocuz** [comment]
Still working here....
Maybe it got a new IP address ?

**Comment by GravityRZ** [comment]
no it has the same ip address. it looks like after some time it is not reachable but only for a brief moment.

the update was supposed to update the lamps to enable startup settings when poweroff/on happens(now they go to 100%)
only the bridge was updated and not the lamps

**Comment by GravityRZ** [comment]
no timeouts for a day now.
yesterday the bulbs updated and now have the startup feature(in the hub, not it the app)
maybee the roleout of this feature caused all this. will close this post after a couple of days since it aparently has nothing to do with domoticz but is nice to know for the moment

**Comment by GravityRZ** [comment]
seems to be steady now. maybe it had something to do with the recent roleout of the startup feature
