### ISSUE TITLE
protected switches still switch without a password 2.4016

### ISSUE THREAD

**Issue by hansworst24** [domoticz/domoticz#290]
Hi,

I just noticed that when you turn a switch on/off through api/json URL, the switch still switches, when no "passcode" variable is sent. When sending a wrong "passcode" variable, the json-return is indeed "WRONG".

way to test ; create virtual switch, protect it, and type the URL in a browser to turn the switch on or off. Without the passcode variable, it still switches !

**Comment by gizmocuz** [comment]
Thanks for reporting, fixed in latest commit, also for switches

**Comment by hansworst24** [comment]
Perfect :) Many thanks for all the good work ! I'm in the process of providing a Windows Phone app for Domoticz, that's how I encountered the issue :)
