### ISSUE TITLE
Cosmetic fix:HUE light percentage is 1% to high on all dimmable lights (E27 multicolor LCT007)

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#2905]
domoticz version 4.10224

i noticed for a while now that the hue light percentage is exactly 1% to high then reported in other apps.
Both Homekit, native hue app and eve all report percentages 1% lower.
since i made my scenes with nicely rounded percentages(35, 40, 65, 80%) i noticed this for a while but did not think it was a bug at that time
So in domoticz they read 36, 41, 66, 81%
would be nice however if this gets corrected.
must be a rounded thingie

**Comment by GravityRZ** [comment]
Bump. can somebody take a look at this.

domoticz percentages on hue lights are 1% to high

i compare this with both the hue app and homekit.

if i select 35% on the hue app Domoticz will display 36%
this is either a rounded issue or a 0-99% issue(at least it looks that way)

**Comment by waltervl** [comment]
Still an Issue @GravityRZ ?

**Comment by GravityRZ** [comment]
no it is not. i corrected this another way. sorry, was not aware that i left this one open

closing it
