### ISSUE TITLE
Toon Thermostat

### ISSUE THREAD

**Issue by Pandabeer40** [domoticz/domoticz#2907]
Toon Thermostat is not corresponding anymore - due to possible changes at Eneco - it's not possible to exchange information between Domoticz / Toon Thermostat

Request to implement Toon API into Domoticz

**Comment by gizmocuz** [comment]
Thanks, if you could help with that please...
Another option (i read) is to 'hack' your toon

**Comment by Pandabeer40** [comment]
I’d like to help – but I have no real programming knowledge – I can offer my Toon 😉 – It’s a version 2 and probably difficult to hack – I think a API integration in Domoticz is better…


https://developer.toon.eu/

If I can do something – please let me know – but as said, I don’t have any programm skills

**Comment by Pandabeer40** [comment]
I have an account at developer.toon.eu - I'd like to start, but I don't know where - where can I find the Toon Thermostat files in Domoticz right now? Can I start rewriting this part in a test version of Domoticz and try to make it work? (I see the API works with the Curl commands which already work on the website of developer.toon.eu - bit now... how to implement in Domoticz
if somebody can give me a start or maybe I can help somebody with the account at developer.toon.eu

Peter

**Comment by Pandabeer40** [comment]
Found it!! I used, due to new login / account at Eneco, a symbol in my password - probably this wil not work good in the password string within Domoticz - now I changed my password to standard alphanumuric symbols and everything is working fine!

Maybe this can be changed in the future as well implement the Toon API to be ready for the future before Eneco stops with toonopafstand.eneco.nl

**Comment by gizmocuz** [comment]
You can read the INSTALL.TXT file and look for the part how to compile under windows (visual studio)
Or if you are using a raspberry pi, you can compile from the command line (see our wiki)

https://wiki.domoticz.com/wiki

The toon hardware you can find in the hardware folder, and the file... 'ToonThermostat.cpp/h'

the username/password are only used here:

`bool CToonThermostat::Login()`

line 307

`sstr << "username=" << m_UserName << "&password=" << m_Password;`

i think we need to url encode the password field, like

`sstr << "username=" << m_UserName << "&password=" << CURLEncode::URLEncode(m_Password);`

I have changed this in beta 10270, is it possible you can test with this beta:
- if it works with your current password
- if it works with your previous password containing a symbol

**Comment by darkrain-nl** [comment]
Just a small remark, the new Toon app from Eneco itself also has issues with special characters in the password...

**Comment by Pandabeer40** [comment]
Thank you Gizmocuz, I will try the new version and login possibilities
this weekend! And will give you feed back 

gizmocuz schreef op 13-12-2018 09:18:

> You can read the INSTALL.TXT file and look for the part how to compile under windows (visual studio)
> Or if you are using a raspberry pi, you can compile from the command line (see our wiki) 
> 
> https://wiki.domoticz.com/wiki 
> 
> The toon hardware you can find in the hardware folder, and the file... 'ToonThermostat.cpp/h' 
> 
> the username/password are only used here: 
> 
> bool CToonThermostat::Login() 
> 
> line 307 
> 
> sstr << "username=" << m_UserName << "&password=" << m_Password; 
> 
> i think we need to url encode the password field, like 
> 
> sstr << "username=" << m_UserName << "&password=" << CURLEncode::URLEncode(m_Password); 
> 
> I have changed this in beta 10270, is it possible you can test with this beta: 
> 
> * if it works with your current password
> * if it works with your previous password containing a symbol
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

-- 
Met vriendelijke groet, 

Peter Boermans 

Links:
------
[1]
https://github.com/domoticz/domoticz/issues/2907#issuecomment-446880297
[2]

**Comment by Pandabeer40** [comment]
Hello Jan, 

Thank you for your remark - last week the Eneco and TOON app worked both
with the password with symbol - so in my case this was now issue (and
not recongnized by me that this was giving any conflicts in Domoticz
hardware settings ;))

**Comment by Pandabeer40** [comment]
Hi Gizmocuz,

 

Looks like the symbol in the password works as well in Domoticz! Thank you!

**Comment by gizmocuz** [comment]
Thanks for the feedback ! Please do not reply to emails directly but use github as else it will copy/past the whole email headers
