### ISSUE TITLE
Smart Meter Usage and Delivery not updated when Usage or Delivery is 0

### ISSUE THREAD

**Issue by akamming** [domoticz/domoticz#2908]
Hi,

I found a bug: I noticed the smart meter devices for usage and delivery are not updated when the value seems to be 0

See the example below (on beta 4.100224 on a pi 3b):

![slimme meter](https://user-images.githubusercontent.com/30364409/49782385-69be7f00-fd16-11e8-955b-208d215931c9.jpg)

as you can see. idx 247, 254 and 255 are not updated. I have a pv system with a 3phase inverter, and there is a bit of sunshine, so i think what is happening
- the PV system is currently producing a bit of power, 
- The PV systems spreads the generated power over the 3 phases
- Since the power consumption is not equally divided over the 3 phases, on L2 there is a bit of delivery and on L1 and L3 there is usage
- L2 delivery, L1 usage and L3 usage are reported correctly)
- for L2 usage, L1 and L3 delivery nothing is reported, i would expect an update of the devices with a 0 value, however no update takes place

See also forum post [https://www.domoticz.com/forum/viewtopic.php?f=6&t=26031](url)

**Comment by gizmocuz** [comment]
Yes i think you are right looking at the code... 
Fixed in upcoming beta version (10268), thanks for reporting!

**Comment by akamming** [comment]
Nice, this was fixed very fast!
