### ISSUE TITLE
problem compiling on centos 6.7

### ISSUE THREAD

**Issue by kshesq** [domoticz/domoticz#291]
Hi, i am trying to compile the source according to this page:
http://www.domoticz.com/forum/viewtopic.php?f=47&t=9586

but when I run:
cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt

I get this message;

CMake Error at CMakeLists.txt:145 (MATH):
  math cannot parse the expression: "+2107": syntax error, unexpected
  exp_PLUS, expecting exp_OPENPARENT or exp_NUMBER (1)

Can someone help me fix this?

TIA
Kim

**Comment by gizmocuz** [comment]
Please use our forum, specially when there is already a post that you can reply to
