### ISSUE TITLE
Linker errors

### ISSUE THREAD

**Issue by hvbommel** [domoticz/domoticz#2913]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version.
* Always state your version when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by hvbommel** [comment]
I am trying to build the latest domoticz development branch in combination with the openzwave Dev branch. This to test if the Bnext 500 tag reader now works with the latest openzwave changes. I am getting linker errors. For details see attached document "domoticz_linker_errors.txt".

Question: is someone looking at this? or should I look at this?

thanks.

[domoticz_linker_errors.txt](https://github.com/domoticz/domoticz/files/2677672/domoticz_linker_errors.txt)

Henri

**Comment by hvbommel** [comment]
Oh I found the problem, After pulling the openzwave master branch all linked ok. So I cant test the openzwave Dev branch in this setup. My mistake.

**Comment by gizmocuz** [comment]
Please use our forum!
