### ISSUE TITLE
rtl_433 mqtt topic api

### ISSUE THREAD

**Issue by merbanan** [domoticz/domoticz#2916]
Hi, we are working on a MQTT api for rtl_433. The payload will be the json that rtl_433 always have been outputting. But is there any preference on how the topics are generated? I know very little about Domoticz internals but if there is any structure that would be useful for Domoticz integration I am interested to hear those.

**Comment by gizmocuz** [comment]
As far as i can see, the current RTL433 implementation is not based on JSON but on a CSV structure.
(See hardware/Rtl433.cpp)

What would be the benefit to MQTT compared to just plugging the RTL433 directly in a raspberry for example running domoticz ?
With a master/slave setup you can also send it across the net...

I think if we rebuild the current implementation and make this work with JSON, then it should not be that hard to transfer the MQTT data to the parser.

Not sure how many influence you have on the MQTT code, but you could also rebuild this so it calls the domoticz mqtt 'udevice' format directly, this way no code changes have to be made in Domoticz

**Comment by gizmocuz** [comment]
Of course if you want to make this generic... a kind of 'tag' that we know the MQTT payload contains RTL433 data would be great.
Do you have a document/json containing all current possible outputs ? That could help changing the current Domoticz CSV implementation to JSON

**Comment by merbanan** [comment]
Can you point me to the mqtt 'udevice' format code/description? It sounds like the closest thing what I ask for. Our aim is to build a reliable stable api with mqtt for transport and json for the payload. Hopefully it is a more maintainable solution then parsing cvs output. The specification (wip) can be found here https://github.com/merbanan/rtl_433/pull/827/files.

**Comment by gizmocuz** [comment]
@merbanan , the udevice method is of course pretty Domoticz specific, i dont know if you want to go that far.
It can be found here:
https://github.com/domoticz/domoticz/blob/development/hardware/MQTT.cpp#L140

maybe when you put the JSON inside a <rtl_433> tag, it would be OK for all applications to implement it their own way. This way we can distinguish that the JSON payload is from rtl_433

**Comment by merbanan** [comment]
Ok, thanks. We'll adapt the json payload generation so it is possible to add unique identifiers. That way it should be easy for a parser to send off the payload to the correct plugin parser.
