### ISSUE TITLE
OpenZwave: doesn't cope with device node rename on reboot/reconnect

### ISSUE THREAD

**Issue by dpocock** [domoticz/domoticz#2917]
When I first set up the Z-Stick, it was /dev/ttyACM1

After a reboot, it was /dev/ttyACM0

Domoticz configuration had to be changed through the Hardware page to use /dev/ttyACM0 and then it started working again.

It would be nice if it could detect situations like this automatically, especially for USB devices.

**Comment by gizmocuz** [comment]
First, what domoticz version are you using ? If using the beta version, you should see other (persistant) usb names that you could/should use
Second, please use our forum, this has been addressed many times, search for persistent devices on our wiki
