### ISSUE TITLE
Xiaomi Gateway (Aqara) - Please add support for  Aqara LED Smart Bulb

### ISSUE THREAD

**Issue by grubson77** [domoticz/domoticz#2918]
I suppose that "Xiaomi Aqara ZNLDP12LM LED Smart Bulb" is a new product. 
https://www.gearbest.com/smart-bulb/pp_009892485950.html

It is not a yeelight bulb, but aqara. It communicates using zigbee protocol. 
Unfortunately Xiaomi Gateway on Domoticz did not discover this device. Please add a support for this. 
Thanks !

**Comment by deennoo** [comment]
Thé bulb isn't show on Xiaomi api.  This need to bé done by Xiaomi first

**Comment by grubson77** [comment]
I can control the bulb via Mi Home app on android, so I guess the api should be already updated.

**Comment by viacheslav-huma** [comment]
Any updates on this?

**Comment by mench32** [comment]
Do you have any news?

**Comment by gizmocuz** [comment]
No, but please continue this discussion on the Forum
