### ISSUE TITLE
dzVents integration tests fail on release 4.10298 (seems to be related to commit  67682df)

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#2919]
http://localhost:8080/json.htm?param=saveuservariable&type=command&vname=varCancelled&vtype=0&vvalue=0
false
{["status"]="ERR"}
And all other saveuservariable commands

**Comment by dannybloe** [comment]
Mm. That's bad. API changes without keeping existing ones in tact or is that something else?
We really need to find a way to have the dzVents integration tests run on Travis somehow so we know when someone breaks stuff. The dzVents integration tests are not just for dzVents but they sort of test a huge amount of the API and all the dummy hardware types including almost the entire event system (the Lua/dzVents part that is ;-) ).

**Comment by gizmocuz** [comment]
Duplicate post, should be fixed already
