### ISSUE TITLE
Blocky 'Disable Block' don't work

### ISSUE THREAD

**Issue by Xenomes** [domoticz/domoticz#2920]
Hi All,

I am on beta 4.10.298 when disabling a part of blocky blocks this part will still be executed. 

![domoticz disabeld blocky script](https://user-images.githubusercontent.com/11648297/50207945-37dd9600-0370-11e9-86d5-058013d095a3.gif)

**Comment by gizmocuz** [comment]
Thanks for pointing this out. Does this also happen after a restart ?
Are there any other scripts sending this notification ?

**Comment by Xenomes** [comment]
Yes also after a restart. No other script is being called by the 'test knop'. All other function are also not working. The hole disable function won't work. 😅

**Comment by gizmocuz** [comment]
Did not know you could partly disable blockly blocks... should work now in beta 10310)

**Comment by Xenomes** [comment]
Thank you very much for enable the feature! It will be every handy for built of future blocks scripts. Happy new year!!!
