### ISSUE TITLE
Update uservariable fails because of DB structure mismatch

### ISSUE THREAD

**Issue by mlstolk** [domoticz/domoticz#2921]
Commit 1d883c1 (@gizmocuz)  broke something in the query to update a uservariable. 
_This is not yet fixed in the patch that is included in version 4.10299_

SQL Query("SELECT Name, VarType FROM UserVariables WHERE (ID==8)") : no such column: VarType
Error: MQTT: unknown idx received! (idx 8)

**Comment by mlstolk** [comment]
Probably VarType should refer to the column ValueType, which does exist in that table?

**Comment by gizmocuz** [comment]
Thanks for reporting. Must have copy/pasted this from somewhere.. should be fixed now
