### ISSUE TITLE
PluginManager.cpp:388:86: error: expected ‘)’ before ‘PRIu64’

### ISSUE THREAD

**Issue by non7top** [domoticz/domoticz#2924]
Building version 4.9700
Faced compilation error

```
/tmp/tmp.wG5LlbvHZw/domoticz-4.9700/hardware/plugins/PluginManager.cpp: In member function ‘void Plugins::CPluginSystem::DeviceModified(uint64_t)’:
/tmp/tmp.wG5LlbvHZw/domoticz-4.9700/hardware/plugins/PluginManager.cpp:388:86: error: expected ‘)’ before ‘PRIu64’
   result = m_sql.safe_query("SELECT HardwareID,Unit FROM DeviceStatus WHERE (ID == %" PRIu64 ")", ID);
                            ~                                                         ^~~~~~~
                                                                                      )
make[2]: *** [CMakeFiles/domoticz.dir/hardware/plugins/PluginManager.cpp.o] Error 1


$ gcc --version
gcc (GCC) 8.2.0

```

**Comment by sweetpants** [comment]
Why on earth would you build this version? If you want to build from source, take the latest Beta.

**Comment by non7top** [comment]
`Stable Release` sounds convincing to me. Domoticz.com also promotes it as `Stable`

**Comment by sweetpants** [comment]
The Pre-build version yes, but if you want to use the source from stable, then i think you are on your own. I'm using Beta only, also on my production system and it pretty stable for years now. If you build from source it's easy to go back if something happens and if there is a problem you can help out (It's an Open Source project)

**Comment by non7top** [comment]
So, I tried latest master at b15219463edf6e11847019ec3939ff80a376645c and it failed with the same exact error

```
/tmp/tmp.T2zRKfrV26/domoticz-b15219463edf6e11847019ec3939ff80a376645c/hardware/plugins/PluginManager.cpp: In member function ‘void Plugins::CPluginSystem::DeviceModified(uint64_t)’:
/tmp/tmp.T2zRKfrV26/domoticz-b15219463edf6e11847019ec3939ff80a376645c/hardware/plugins/PluginManager.cpp:385:86: error: expected ‘)’ before ‘PRIu64’
   result = m_sql.safe_query("SELECT HardwareID,Unit FROM DeviceStatus WHERE (ID == %" PRIu64 ")", ID);
                            ~                                                         ^~~~~~~
                                                                                      )
```

**Comment by sweetpants** [comment]
I compile from source also and do not have this error gcc version 6.5.0

**Comment by gizmocuz** [comment]
@non7top , could you have a look here:

https://stackoverflow.com/questions/14535556/why-doesnt-priu64-work-in-this-code

**Comment by non7top** [comment]
Thanks, this simple patch fixes it for me

https://github.com/non7top/spm/blob/master/recipes/files/pluginmanager_fix.patch

**Comment by gizmocuz** [comment]
Thanks! Patch applied in repo
