### ISSUE TITLE
Geo location lookup fails with REQUEST_DENIED

### ISSUE THREAD

**Issue by TheReptile** [domoticz/domoticz#2929]
On a new install I tried to lookup the Geo coordinates, but I got the following error:

Geocode was not successful for the following reason: REQUEST_DENIED

After investigating a bit I found out this url is called:

https://maps.googleapis.com/maps/api/js/GeocodeService.Search?4s<address>&7sUS&9sen-US&callback=_xdc_._arh3cs&token=31788

When I executed the url manually, I got a result back with the following error:
```
/**/_xdc_._arh3cs && _xdc_._arh3cs( {
   "error_message" : "Geocoding Service: You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key",
   "results" : [],
   "status" : "REQUEST_DENIED"
}
 )
```
It seems the current api won't work anymore without an account.

**Comment by gizmocuz** [comment]
Thanks for reporting ! Should be fixed in the upcoming beta version

**Comment by ward0** [comment]
@gizmocuz when is this fixed in stable? still getting error.

**Comment by gizmocuz** [comment]
probably when the stable is released... and that's not now
Try the new beta
