### ISSUE TITLE
Energy logs have months screwed up

### ISSUE THREAD

**Issue by gajotnt** [domoticz/domoticz#2937]
Using version 4.10311. Upgraded from stable because year 2019 wasnt showing in the utilities logs.

Now i can choose 2019 but other things are screwed up
![energy](https://user-images.githubusercontent.com/25504364/50634935-baa14c00-0f3f-11e9-8219-b531a8a80c5a.JPG)

**Comment by gizmocuz** [comment]
No issue here, what type of sensor is this ? (General kWh ?)
Can you clear your browsers app-cache AND browser cache (two different things) and or try in the browsers private mode ?

**Comment by gajotnt** [comment]
Yes general kwh. Cleared both the caches, tried even with a new browser install, deleted the www dir from the server and did a install.
During the upgrade from 4.9700 to the latest beta maybe something got screwed in the DB?

**Comment by gizmocuz** [comment]
@gajotnt , could you contact me on the forum ? I would like to debug with your database

**Comment by gajotnt** [comment]
Done

**Comment by gizmocuz** [comment]
Thanks... no issues here... can you use the default template, english language, clear the app-cache AND browser cache and check again ?

![image](https://user-images.githubusercontent.com/2265299/50738246-0a974180-11d2-11e9-8b4c-c9c4675a3503.png)

Also try connecting via a private browser

**Comment by gajotnt** [comment]
Did all that several times. must be some problem with my raspberry pi. Will do a fresh install of everything.
Thanks

**Comment by gizmocuz** [comment]
I dont think it is related to your raspberry pi... try updating to the latest beta, and try a private browser (or another browser)

**Comment by gajotnt** [comment]
I even tried on 2 of my friends computers that never accessed a domoticz webpage.
I noticed all my tasmota devices have the wrong time from the MQTT broker that's on the same RPI3 of the domoticz install so maybe that's one thing I have to look into even thou in domoticz the hours and date is right.

**Comment by gajotnt** [comment]
Tried a new windows install of domoticz, restored the DB over to the new windows install, tried 3 diferent browsers, all with their caches cleaned, same bug.
How did you import the db? Any extra step I may have missed?

![domoticz](https://user-images.githubusercontent.com/25504364/50765118-74f8c200-1264-11e9-985c-044b868a41ea.JPG)

**Comment by gizmocuz** [comment]
I dont know the problem in the above screenshot, i was looking at the silly months in your first screenshot
missing months , double october etc...
i just placed your database in the domoticz folder

**Comment by gajotnt** [comment]
Sorry should have taken the screenshot on 2018, in 2019 It's showing december when it should be january. and in 2018 its still "silly" lol

tried two fresh installs (one on RPi3 and the other on windows) this is just very wierd lol
![domoticz_2018_kwh](https://user-images.githubusercontent.com/25504364/50778437-72f72900-128d-11e9-99c4-8e9801c5b29c.JPG)

**Comment by gajotnt** [comment]
Got it working!!!!!!
Its my timezone!!!
changed it to Canada timezone and everything is showing OK

**Comment by gajotnt** [comment]
But In 2019 its still showing december instead of January

**Comment by gajotnt** [comment]
Ok, just configured my PC to Amsterdam Timezone (UTC +1), everything showing OK.

My timezone is UTC -1 Azores

Maybe with this information you can check if theres some bug in the code

**Comment by gizmocuz** [comment]
The system running domoticz and the system where you are using your browser both have the same timezone ?

**Comment by gajotnt** [comment]
Yeas the Raspberry Pi is using the Atlantic Azores Timezone (-1h)

**Comment by gajotnt** [comment]
Running Domoticz beta 4.11528
This is still an issue. Timezone Azores GMT -1h
![bug](https://user-images.githubusercontent.com/25504364/69540069-59c69c00-0f75-11ea-8a55-9342e2c40bb5.PNG)

**Comment by gajotnt** [comment]
Beta Version 4.11662
Only utility tab displays this behavior.
Temperature and Weather shows the months correctly.

**Comment by waltervl** [comment]
Is this still an issue?

**Comment by gajotnt** [comment]
Yes. Have to change my timezone to show correct months on energy logs

**Comment by gizmocuz** [comment]
@gajotnt , that is strange, you seem to be the only one with this problem.
On the system where you installed Domoticz, you have configured the system and specified the correct timezone there?

**Comment by gajotnt** [comment]
Yes the timezones are correct in the Raspberry.
![CorrectTimezone](https://user-images.githubusercontent.com/25504364/156937695-dbcebe18-f1c2-488f-80a3-bc86fa6df6a5.png)
![othertimezone](https://user-images.githubusercontent.com/25504364/156937696-deab343e-c358-481b-aa90-e6310d952510.png)

**Comment by gizmocuz** [comment]
@gajotnt , thanks for the clear explanation.
Could you check two things:
- is this only for kWh reports or also for Temperature(other) sensors ?
- when you open your browsers development console (function key F12) and go to the network tab (if this is the first time you open it, please dock it to the bottom of your browser), and refresh the report page, you should see some JSON calls that get the data from Domoticz.
Could you check that this data contains January/February/march and not December.
If it contains the correct date/time, we know it is a GUI issue, if it also contains December we know it's a internal Domoticz issue

**Comment by gajotnt** [comment]
Yes, this only happens in the Kwh.

I think this is what you asked, and it looks like it pulls the months correctly.
![json](https://user-images.githubusercontent.com/25504364/157141046-42f515f3-199a-492a-aac3-a847010beacf.png)

**Comment by gizmocuz** [comment]
Sorry I am still trying to reproduce this.... Do you have any HTML/JS script skills ?
I tried here on my (windows) system, set the timezone to -1, refreshed the chart of a Domoticz instance of this machine, and a remote machine, the chart stays correct

What version of Domoticz are you running ? I hope the latest stable or beta ?

**Comment by gajotnt** [comment]
No not many skills with JS.

Im runing the latest stable (but did run betas for a long time) on a RPi.

When i get home i'll post my settings on raspi-config and domoticz version.

In the meanwhile i have reinstalled windows 2 times. And RPi one time. Maybe i can send you my DB?

**Comment by gizmocuz** [comment]
Sure, I have send you a PM on the forum with my email address

**Comment by gajotnt** [comment]
![timezone rpi](https://user-images.githubusercontent.com/25504364/159064941-a0806892-52c7-4e4d-bad9-5b14453fa744.png)
![version domoticz](https://user-images.githubusercontent.com/25504364/159064962-725bcb58-0326-426c-bec9-c393aa56e023.png)

sent the db in the domoticz forum.

**Comment by gizmocuz** [comment]
Sorry about the delay. I received the database and did some checking.
You database has some internal errors, not sure how you made the database backup, maybe you copied it instead of exporting from the settings menu ?
I have no issues here, checked the 'total' device, for 2021,2020,2019 all months are displayed and fine.
Could you try to set your domoticz to default english ?

**Comment by luzpaz** [comment]
Is this ticket still relevant ?
