### ISSUE TITLE
IDEA: Console for lua/dzvents

### ISSUE THREAD

**Issue by DAVIZINH0** [domoticz/domoticz#2938]
Hello,
Sorry if this is not the correct place to suggest a idea, i will move to the correct place if you say to me.

My idea es have a "console" or something similar to put one lua command and test it.
In some case i want to test a command because i dont know if works fine or not and i must create a "test script"; with this idea you can use the console to test it and view the results.

its posible?, do you see usefull like me?

thanks!

**Comment by rwaaren** [comment]
Why not post this question on the forum ?
If you refer to a standard Lua command you can try it on the Command Line Interface.
Just type lua from the prompt and you are in the Lua command interpreter. Here you can test all commands but you won't have the data (structures) available from the domoticz instance.

**Comment by DAVIZINH0** [comment]
ok, i will close and put in the forum. thanks a lot!
