### ISSUE TITLE
Change on textsensor not published on domoticz/out

### ISSUE THREAD

**Issue by wimdo** [domoticz/domoticz#2940]
I noticed that an update on a virtual sensor defined as text-sensor is not published on domotiz/out.
Additional actions are needed ot get the chagned value published. 

It looks like this issue is similar to  https://github.com/domoticz/domoticz/issues/2380
For my specific sensors I want to switch form MySensors to  MQTT but run into the same issue that recently was resolved. 

Domoticz version :  4.9700

**Comment by gizmocuz** [comment]
It's working in that issue, so i don;t think it's related.
If it was recently resolved, it is probably resolved in the beta version, did you try the beta version?

**Comment by wimdo** [comment]
Hi, 

 

Missed to answer this one. 

In the meantime I stopped using mySensors and solved my problem with a combination of NodeJS and Domoticz. 

 

With kind regards, 

Wim Dossche

 

Van: gizmocuz [mailto:notifications@github.com] 
Verzonden: zondag 3 februari 2019 9:20
Aan: domoticz/domoticz
CC: wimdo; Manual
Onderwerp: Re: [domoticz/domoticz] Change on textsensor not published on domoticz/out (#2940)

 

It's working in that issue, so i don;t think it's related.
If it was recently resolved, it is probably resolved in the beta version, did you try the beta version?
