### ISSUE TITLE
Linker error after fresh install from source

### ISSUE THREAD

**Issue by sweetpants** [domoticz/domoticz#2946]
This afternoon i re-installed my test system (Ubuntu 16.04 LTS) from source following the Wiki, and compilation seems to go ok, but during linking i get the following error

/usr/bin/x86_64-linux-gnu-ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libssl.a(ssl_algs.o): undefined reference to symbol 'EVP_dss1@@OPENSSL_1.0.0'
//lib/x86_64-linux-gnu/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:6216: recipe for target 'domoticz' failed
make[2]: *** [domoticz] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

Before this fresh install, updating and compiling was working normally.

**Comment by gizmocuz** [comment]
Which wiki source did you use ?

Try this one:
https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by gizmocuz** [comment]
Why are you using 16.04 when you re-install your system over 18.04 LTS ?

**Comment by sweetpants** [comment]
That's the wiki i used. I'm using 16.04 because my production system is 16.04 also, i don;t want to use a higher OS version. I keep both systems up2date at the same time

**Comment by gizmocuz** [comment]
Perfect! Okey installing 18.04 LTS here to test... but time is running out tonight

**Comment by gizmocuz** [comment]
you might look at our travis build system that compiles for ubuntu to see any packages/configuration options you might need (by looking at the travis file in the repo)

**Comment by sweetpants** [comment]
Ok, i will give it a try, it looks like it has something to do with SSL

**Comment by gizmocuz** [comment]
Tested with 18.04, followed the wiki to the letter, no issues compiling:

![image](https://user-images.githubusercontent.com/2265299/50816008-881c9800-131f-11e9-93ed-c88f05f2bbbd.png)

**Comment by sweetpants** [comment]
Re-installed my test machine with 18.04 and there it compiles ok. Don;t know what happened, maybe an OS update/upgrade screwed up my test machine, but only after a fresh install, normal updates (git pull, make) of domoticz went fine. Going to upgrade/re-install my production machine with 18.04 shortly, need some time off to do that. Thanks anyway

**Comment by gizmocuz** [comment]
Glad it's working !
