### ISSUE TITLE
Group/Scene state changes initiated by a group device are not passed to eventSystem

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#2947]
In the eventSystem the group/scene state does not get updated when an underlying device has changed state. In the database the update is done (by updating nValue) but this change is not propagated to the eventSystem. A call to M_mainworker. M_eventsystem. GetCurrentScenesGroups () seems to be missing. If I add this call to SQLHelper.cpp (see code snippet)  the state change to the group/scene does make it to the eventSystem. Tested on  V4.10321

```
		//Set new Scene status
		safe_query("UPDATE Scenes SET nValue=%d WHERE (ID == %" PRIu64 ")",
			int(newValue), Idx);
            	if (m_sql.m_bEnableEventSystem)  // Only when eventSystem is active
			m_mainworker.m_eventsystem.GetCurrentScenesGroups(); 
```
My c++ skills are not yet at the level required to change this to a more efficient approach where only the affected scenes/groups (a device can belong to multiple groups/scenes) are called.
Happy to turn this into a PR if this is the right way of handling.

**Comment by gizmocuz** [comment]
Thanks! PR merged
