### ISSUE TITLE
Switching between themes not working properly

### ISSUE THREAD

**Issue by jvandenbroek** [domoticz/domoticz#295]
On Chrome and Firefox (at least on my Linux installation) I can't switch normally between themes, it only picks up the first change. By cleaning 'Offline Website Data' in Firefox and 'Cookies and other site and plugin data' in Chrome the last selected theme loads in. Not a big issue, but probably not how it's intended to work.

Edit: Just tested a few times, seems like you also need to clean the 'regular' cache on both browsers to make this work.

**Comment by gizmocuz** [comment]
or stick to one browser i suppose ? or goto settings and press the apply button

**Comment by ghost** [comment]
This should not be closed. Cached need to be cleared by domoticz

**Comment by gizmocuz** [comment]
Can you submit a pull request for this?

**Comment by ghost** [comment]
I will look into this. I also get the warning AppCache is deprecated. https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache so worst case senario is that the entire cache mechanism should be reworked. 

Edit: I need to read some more about it, but it is supported way more than other browsers.

**Comment by gizmocuz** [comment]
Thanks!
Appcache should still be supported by all browsers (maybe not firefox, dont know... dont use it anymore)
The above document points to 'Service Workers', but this is not supported 100% in all browsers, even for some browsers you need to tweak the config
Please try to keep the offline app support working under iOS (placing a shortcut from firefox on the homescreen gives you an offline application)
