### ISSUE TITLE
Dummy Gas meter is not counting the totals

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#2950]
Dear developers

I use a dummy gas meter, that is not counting the total usage for al time. [ counting with a lua script ]
Only the dummy is counting1 dag, and reset to 0  every day @ 00.00

The real gas meter is counting all the usage for days, weeks etc..

So i think there is a setting or something wrong...

Could someone please take a look..

To the master forum:
[https://www.domoticz.com/forum/viewtopic.php?f=6&t=26415](url)

**Comment by rwaaren** [comment]
Please use the forum for this question and include your script. Chances that someone will see your question and come with an answer is much higher as a lot more people are looking at the forum.
