### ISSUE TITLE
LUA Block comment in Built-in script editor

### ISSUE THREAD

**Issue by ArnieO** [domoticz/domoticz#2952]
The internal LUA editor accepts block comment indications correctly, but the code does not change to green upon when entering the block comment codes. When event file is reopened, the color changes.
It would be great if the code color changed to green immediately when valid start/end block comment codes are entered:
Start of block comment: --[[
End of block comment: ]]

**Comment by Bewo** [comment]
I know this issue too. But you don't need to reopen the file. Just do a little change and the code color changes. For example: Press "Enter" after the ]] to add a new line, and the commented block turn's green completely.

**Comment by rwaaren** [comment]
The requested behavior is already active. (At least with default theme in recent Beta's)
