### ISSUE TITLE
Feature request: would it be possible to introduce an hourly timer like we already have for daily, weekly, etc. ?

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#2957]
I know it can already be done with 23 daily timers or with scripts but an additional hourly timer seems logical.

**Comment by gizmocuz** [comment]
This can be done very easy with a script indeed, but whats your use case ?

**Comment by rwaaren** [comment]
User request: https://www.domoticz.com/forum/viewtopic.php?f=6&t=26035&p=203209&hilit=hour#p203219
It just sounds logical if you have this already for days / weeks / etc. And if it is relatively easy to implement I would say put it on a wishlist. 
If not also not a problem because as I already stated there are many other options to do this but for users not into scripts this would be easier

**Comment by gizmocuz** [comment]
So it is for playing a MP3 file every hour... like a clock tone...
Well i would say, use a script for this one ;)
