### ISSUE TITLE
Manual added Plugins don't appear in Hardware

### ISSUE THREAD

**Issue by Xenomes** [domoticz/domoticz#2959]
Hi All,

I'm on beta 4.10.343 I have added a plug-in to my system and notice that my all custom plugins are not displayed. The ones already activated are not working any more.

On the screenshot Buienrader is missing from the list.
![afbeelding](https://user-images.githubusercontent.com/11648297/51070962-49058400-164a-11e9-8f78-67f3f5c16e67.png)

**Comment by rwaaren** [comment]
Please post this on the forum after you looked at the many posts and solutions there and if the problem still persists after applying these solutions. Thx

**Comment by Xenomes** [comment]
Sorry, not a error of Domoticz. Python was not working anymore then noting has changed ....
