### ISSUE TITLE
Unable to update from 4025 on Raspberry pi

### ISSUE THREAD

**Issue by n-de-groot** [domoticz/domoticz#296]
Since version 4025 error updating beta versions on Rpi:

_Update Available !... Update Now?
Version #4031_

After 2%: _Error while downloading Update, check your internet connection or try again later !..._

As far as I know the internet connection is ok, no problems in other applications.

**Comment by PatrickEekhout** [comment]
I had the same problem a couple of days ago. Thought it had something to do with my setup only. You can do the following to update:
SSH to your Pi
cd domoticz
./updatebeta
This worked for me. Good luck!

**Comment by GertSanders** [comment]
Same problem and solution here on 2 different  RPi’s (both were on 4025)

**Comment by gizmocuz** [comment]
I think this could have been a sourceforge site problem, i had a report like this just a day before, and works again now

**Comment by gizmocuz** [comment]
Okey, i seem to have the same issue now, before i upgraded from version #3xxx

**Comment by gizmocuz** [comment]
fixed in #4065, the update script had no executable rights duo a change from a fellow developer
to update to the latest version, login via SSH to your domoticz folder and issue
./updatebeta

**Comment by GASOLINE** [comment]
`chmod +x updatebeta`
fixed the problem for me.

**Comment by joopie83** [comment]
hello, none of this things works for me :(.
this is what i get:

pi@raspberrypi ~/domoticz $ ./updatebeta
Updating to latest beta version...
Please Standby...
--2017-02-02 18:16:45--  http://domoticz.sourceforge.net/beta/domoticz_linux_armv7l.tgz
Resolving domoticz.sourceforge.net (domoticz.sourceforge.net)... 216.34.181.96
Connecting to domoticz.sourceforge.net (domoticz.sourceforge.net)|216.34.181.96|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://domoticz.sourceforge.io/beta/domoticz_linux_armv7l.tgz [following]
--2017-02-02 18:16:45--  https://domoticz.sourceforge.io/beta/domoticz_linux_armv7l.tgz
Resolving domoticz.sourceforge.io (domoticz.sourceforge.io)... 216.34.181.153
Connecting to domoticz.sourceforge.io (domoticz.sourceforge.io)|216.34.181.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-02-02 18:16:48 ERROR 404: Not Found.

tar (child): domoticz_linux_armv7l.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove `domoticz_linux_armv7l.tgz': No such file or directory
Restarting Domoticz... (please standby...)
[....] Restarting Domoticz Home Automation System: domoticz2017-02-02 18:16:49.009  Domoticz V2.3530 (c)2012-2015 GizMoCuz
2017-02-02 18:16:49.009  Build Hash: 9eef872, Date: 2015-11-01 11:41:18
2017-02-02 18:16:49.010  System: Raspberry Pi
2017-02-02 18:16:49.011  Startup Path: /home/pi/domoticz/
domoticz: Domoticz is starting up....
. ok
pi@raspberrypi ~/domoticz $

**Comment by gizmocuz** [comment]
@joopie83, Use the forum
