### ISSUE TITLE
Protocol button does not work anymore

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#2960]
Version: 4.10343
Build Hash: 3e3f545e
Compile Date: 2019-01-11 08:41:48
dzVents Version: 2.4.9
Python Version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]

since the last update is the switch and sensors is no longer a function when you click on protocol.

If you click on it, nothing happens.
No matter what device.
I also have different browsers

<a href="https://www.directupload.net" target="_blank"><img src="https://s15.directupload.net/images/190112/3q67mzt4.jpg" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by sweetpants** [comment]
Working fine here, please clear your browser and app. cache first. In general do this always after an update
