### ISSUE TITLE
Disable log for given requests

### ISSUE THREAD

**Issue by laibulle** [domoticz/domoticz#2961]
Hello, 

as an API user I would like to send commands without logging it in the timeseries store.

I use domoticz to interact with devices at high velocity (several req/sec), on a small arm CPU. 

First, I don't want to pollute timeseries store with non important data.
Second, timeseries are quite expensive for relational databases so I would turn this feature off when not needed.
Third, I want to log all low velocity requests.

Would you accept a pull request with this feature ?

for example with an optional `log` parameter

```
/json.htm?type=command&param=switchlight&idx=99&switchcmd=On&log=false
```

Best regards

**Comment by gizmocuz** [comment]
@laibulle , sorry, this will not be possible as we need evidence when/who performed this action
