### ISSUE TITLE
Json Api - Check user rights on saving and updating events + uservariables

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz#2962]
I think that this should be considered a bug right? If I have a viewer account, it looks like i can still save (enable/disable) events via the json api or update uservariable.

I found this issue during testing the api's for the mobile apps. The web interface doesn't allow you to browse to events or user variable.

I don't know if only the action api's (update/insert/toggle) should check the user rights? Or also the api's that get data, like the log api?

**Comment by gizmocuz** [comment]
Looking at the code it already checks if you have admin rights
(EventSystem.cpp, void CWebServer::EventCreate)
