### ISSUE TITLE
Falmec fan support with RFXcom

### ISSUE THREAD

**Issue by mwelkers** [domoticz/domoticz#2965]
I run Domoticz v.4.10181 build hash 50dd71e5

The Falmec fan appears to be supported in the RFXnames.cpp (line 792) and RFXtrx.h (lines 759-769). But when I want to manually add the Falmec fan in Switches tab I cannot select it and doesn't show up in the drop down. What can I do? Should I be looking at another place in Domoticz?

**Comment by mwelkers** [comment]
Tried to add it, but no luck yet. Also tried it with a work-around using node-RED but it also hasn't included the option for fan-control yet.

**Comment by kiddigital** [comment]
@Pregabaline , is this issue still relevant?

**Comment by mwelkers** [comment]
No, the issue can be closed.

**Comment by Bluearrow75** [comment]
@mwelkers how did you resolve this? I am having the same issue.

**Comment by gizmocuz** [comment]
It does show up

![Image](https://github.com/user-attachments/assets/aad22570-c1c9-4ede-821e-facac8ce7989)

**Comment by Bluearrow75** [comment]
> It does show up
> 
> ![Image](https://github.com/user-attachments/assets/aad22570-c1c9-4ede-821e-facac8ce7989)

Sorry I probably didn't explain enough.

Yes I see the Falmec type but it is not fully usable.

Looking to the code in RFXtrx.h Domoticz seems to support all actions: On/Off for the light and 4 Fan speeds: 

<img width="296" alt="Image" src="https://github.com/user-attachments/assets/b3581cea-e708-47c1-81ae-d37a1354a4cc"/>

However when adding the device it only does one thing: cuts off the power, both light and fan (I think it is the 0x1) in the code.

This is the switch:

<img width="430" alt="Image" src="https://github.com/user-attachments/assets/d1ce20fc-a4f9-4c41-8fcb-89c0c1edf7e4" />

Domoticz does see that it is a fan though:

<img width="1383" alt="Image" src="https://github.com/user-attachments/assets/612d4963-b53e-4647-8103-32e7f1b72dc7" />

Would you know how I can get Domoticz to support all actions supported by Falmec protocol? At least Light On/Of and the 4 fan speed?

**Comment by gizmocuz** [comment]
I think I got it working... Can't test on a real device, but please give beta 16491 a try!

Now I added the Light On/Off and the 4 speeds, but maybe we need to add the 'Power (off)' as well, let me know!

**Comment by Bluearrow75** [comment]
EDITED as I noticed another strange brahvior
-----------
Thanks a lot for the quick beta!

Everything works much better but a couple things are not working as expected:
- Light On, Turns on the light as expected
- Speed 1 to 4 set the correct speed as expected. However if the light is On it turns it off
- Light Off, turns off the light as expected. But it turns off the fan as well. I would have expected that Light off turns off the light only. For me the current "Light Off", should "Power off"

FYI I tested beta 16492

<img width="98" alt="Image" src="https://github.com/user-attachments/assets/761b3770-0e2c-4404-8235-071bc9ecb5af" />

Thanks again!

**Comment by gizmocuz** [comment]
Great there is progress 😊

What does the status of the fan say in the web GUI when you turn off the light? (light off) ?
(it should)

In beta 16494 I added the Power Off option in the popup, I wonder what that does.

Could you also try sending these commands with the RFXCom RFXmngr application?

http://www.rfxcom.com/Downloads

**Comment by Bluearrow75** [comment]
I tested with 16494. Below the results :) 

1- Light on
- it says "light on" in the gui
- switches the light on as expected
- BUT switches off the fan if active

2- Light off
-  it says "light off" in the gui
- switches the light off as expected
- BUT it switches off the speed if active

3- speed 1 to 4
- it says "speed x" in the gui
- it switches on the fan at the corresponding speed
- BUT it switches off the light!!! => THIS IS A NEW => as a result there is no way to get the light and fan on at the same time! 
I am almost sure I did not have this with the previous version

4- Power off 
- it says power in the GUI and it switches off both fan and light 

As for the RFXmngr I have already tested. I actually tested it before testing with domoticz and everything seemed to work as expected. I will test again though to remove any doubt and let you know

Thank you again for your help!

**Comment by Bluearrow75** [comment]
Ok I retested with Rfxmngr. I actually have the same exact behaviour than the one I have in Beta 16494 
Not sure why this is happening. I tried to compare the behaviour with Flamec's remote that has a small screen that shows the status. Flamec's remote seems to keep the status of the hood and renforces it each time even if you change another parameter that has nothing to do with. Explanation:
- If switch on the light with the remote, the light icon will get displayed on the remote
- Then If I set speed 1 with the remote, the light is still displayed and a bar shows the speed 1
- Then when I hit light off using domoticz or rfxmngr, it will switch off both the fan and the light. However looking to the remote it is still holding the previous status (light on + speed 1)
- Then if I use the remote to set the speed 2, the light will go back on and the speed to 2. =>the remote kept the status of the light. So even though I did not ask it to switch on the light and I only changed the speed, the light is back on. It feels like it is retransmitting the full status each time

**Comment by gizmocuz** [comment]
I am not sure I can help you with this. Maybe you can contact RFXCom?

**Comment by Bluearrow75** [comment]
I understand thank you. I will reach out to RFXCom. 
Otherwise the update you provided helped a lot. Now at least I can turn off and turn on the light which is great. I created a dummy switch for that which calls light on/off commands through json. Therefore now I have the light in HomeKit.
