### ISSUE TITLE
Blockly event Error on Hardware Device disabled

### ISSUE THREAD

**Issue by bennydente** [domoticz/domoticz#2969]
Hi,

I'm on stable version 4.9701.

I have a blockly event called 'Name_of_event' trigger on Device (device ID is 13 but this is not important) state change (On/Off) and write a value in a Variable "Name_of_variable" with ID=4. The event work fine but I see these error in Log. 

Error: EventSystem: Device ('XXXXXX', ID=4) used in event 'Name_of_event' not found, make sure that it's hardware is not disabled!

I have not created Device with ID4, so I think Blockly Event check also in Device table scheme and report this strange error.
 
Thanks, bye.

**Comment by bennydente** [comment]
hi, anyone have same issues?

**Comment by gizmocuz** [comment]
As mentioned when you created the issue, update to the beta first to see if the issue has already been resolved.
Next, please post a screenshot of the blockly please

**Comment by bennydente** [comment]
Hi, now I'm on Version: 4.10427 and the problem persist. here the blocky screenshot.

![schermata 2019-02-15 alle 13 57 13](https://user-images.githubusercontent.com/22501791/52858306-0d1e7c80-312a-11e9-92c7-fcde404c24b7.png)

thanks, bye.

**Comment by gizmocuz** [comment]
Could you post a screenshot from the devices tab where your 'device (switch)' highlighted ?

I am unable to replicate this:
- created a dummy switch
- created a text variable

Same blockly logic produces:

![image](https://user-images.githubusercontent.com/2265299/52963962-74923180-33a1-11e9-9759-b3a3bc2ddeaa.png)

**Comment by bennydente** [comment]
Here you are:
thanks.

![schermata 2019-02-19 alle 15 09 31](https://user-images.githubusercontent.com/22501791/53021180-e8dbdc00-3458-11e9-9eef-5f646d0221e8.png)
![schermata 2019-02-19 alle 15 10 12](https://user-images.githubusercontent.com/22501791/53021185-ee392680-3458-11e9-9bb2-005b530757f6.png)
![schermata 2019-02-19 alle 15 15 42](https://user-images.githubusercontent.com/22501791/53021382-630c6080-3459-11e9-8333-634dc28b6216.png)

![schermata 2019-02-19 alle 15 11 10](https://user-images.githubusercontent.com/22501791/53021193-f42f0780-3458-11e9-9cba-5babafed1191.png)

**Comment by bennydente** [comment]
Hi, i delete and create the Variables again and the problem gone. better that way. thanks.
