### ISSUE TITLE
Pushbullet notification title text

### ISSUE THREAD

**Issue by D4NH** [domoticz/domoticz#297]
would it be possible to set the default title to Domoticz instead of the same text as the body text? 

Notification in Pushbullet now looks like:
Tv on
Tv on

Im guessing the title/subject is the same the body text and taken from the custom message option in the notification setting.

**Comment by tofra** [comment]
I created a test, and this is what I get from pushbullet
![image](https://cloud.githubusercontent.com/assets/1746173/12499133/4056efec-c0a8-11e5-90b2-de2d75fcb344.png)
using this blocky
![image](https://cloud.githubusercontent.com/assets/1746173/12499151/50ee77da-c0a8-11e5-963a-fb6c7ba7d2f1.png)

What do you see?

**Comment by D4NH** [comment]
That works, getting the correct subject and message now.
Guess I'll set up all blocky events for the notifications :+1:

**Comment by gizmocuz** [comment]
Would not do that, instead i would go looking in the notification code in Domoticz ?

**Comment by gizmocuz** [comment]
Had a look, a new beta version is made (#4274)
When the Subject/Body are the same, the Subject will be Domoticz, also for other notification systems

**Comment by D4NH** [comment]
thanks for the update!

**Comment by tofra** [comment]
@D4NH Did you use a LUA script? If yes, post me the details.

@gizmocuz I don't think this is a "good" approach, as the user maybe wants to have the same subject as message. I would leave it the way it was, if he want to have the same subject/message, he can specify it.

**Comment by D4NH** [comment]
@tofra no, im using blocky now, before I used the custom option in the notification setting
<img width="571" alt="screen shot 2016-01-22 at 08 59 49" src="https://cloud.githubusercontent.com/assets/6664547/12505368/9749a96e-c0e6-11e5-91b0-b59e43f3be5c.png">

**Comment by gizmocuz** [comment]
@tofra, i dont agree with this one, also if you send NMA or Prowl messages, you do not want to see the same message twice (body/subject), sending only the subject looks much better now
No need to send it twice, unless you got more to tell in the body
