### ISSUE TITLE
Request] Xiaomi with Zigbee Ikea bulbs

### ISSUE THREAD

**Issue by boscorelly** [domoticz/domoticz#2970]
Hi, is it planned to support Ikea bulbs iwth Xiaomi Gateway ?

**Comment by pipiche38** [comment]
Xiaomi gateway manage the xiaomi hub. 

For ikea bulbs you might better check www.zigate.fr which is independent of the manufacturer and Ikea as well as xiaomi are working with

Envoyé de mon iPhone

**Comment by boscorelly** [comment]
i know but all is working fine for what i need with xiaomi gateway as a gateway device.

Xiaomi and Ikea have made a partnership for bulbs. Now ikea bulbs are controlled and added in mi home app and controlled from gateway, using zigbee.

**Comment by rorie1982** [comment]
Same question here, after the latest firmware update from the Xiaomi gateway v2 and the Mi Home app Ikea lights are added and working, got it working last night. In Domoticz the Ikea lights are not visible at the moment. So my question is it planned to support Ikea bulbs connected with the Xiaomi gateway?

**Comment by boscorelly** [comment]
I hope it will be because it's zigbee too :)

**Comment by deennoo** [comment]
Does Ikea bulb are shown on domoticz log ? 

Aqara bulb isn't

**Comment by Teunissm** [comment]
Same question over here, it would be great when the Ikea bulbs wich are connected to the xiaomi gateway (this works perfect) are implemented in Domoticz like e.q. Ten door switches or the human body sensor.....

**Comment by gizmocuz** [comment]
i am going to buy some hardware and hope to be able to support Xiaomi/Zigbee...

I was looking at the AQara ZHWG11LM controller, is this the correct one ?
Can someone supply a link to the right ikea bulb ?
Any other hardware i should order for testing (aliexpress links please)

**Comment by pipiche38** [comment]
Do you mean you’ll implement a native zigbee hardware ? Or do you mean you’ll extend the support of xiaomi gateway?

Envoyé de mon iPhone

**Comment by gizmocuz** [comment]
I will extend the support of the xiaomi gateway (maybe).
There is a zigbee usb stick.. i remember i have read something on the forum

**Comment by landaisbenj** [comment]
[xiaomi gateway](https://www.google.fr/amp/s/m.aliexpress.com/item/32645949131.html#ampf=undefined) and [Aqara gateway](https://m.fr.aliexpress.com/item/32910821884.html?pid=808_0002_0131&spm=a2g0n.search-amp.list.32910821884&aff_trace_key=&aff_platform=msite&m_page_id=7567Pa1LEarrEGf4gxtV_9Z-IwjFeY6TqWgsQxID248OnI3g7SciwopaXhgNMFar2Eml1549119814218) both support some xiaomi device AND aqara device. Since some times, xiaomi gateway can support too some ikea buble in some server (mainland). All server may be updated soon (I think) and I don't know for aqara gateway. 

And me too I see an usb gateway from xiaomi but it not buyable (just sell on xiaomi shop on China)

And a private project create [zigate usb dongle](https://zigate.fr/) can support many zigbee device. 

I hope it can help.

**Comment by stas-demydiuk** [comment]
Also there is one more project around it [zigbee2mqtt](https://koenkk.github.io/zigbee2mqtt/) with corresponding plugin for Domoticz https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin
At the moment I guess it has wider devices support, bigger community and chipper hardware.

**Comment by pipiche38** [comment]
I’m focussing on Zigate plugin , where we are in beta currently providing native support of Groups

**Comment by swejmansson** [comment]
I connected an IKEA bulb(IKEA E14 white spectrum) the other day. Works fine with Xiaomi gateway but no device created in Domoticz. Not running latest beta, but let me know if you want me to do tests for.....

**Comment by gizmocuz** [comment]
@swejmansson , can you debug/compile domoticz ? They you could help testing.
What is the name of the bulb ? TRÅDFRI ? 

https://www.ikea.com/nl/nl/catalog/categories/departments/lighting/36812/

**Comment by Bastiaan81** [comment]
I have the Ikea Tradfri GU 10: https://www.ikea.com/nl/nl/catalog/products/80365270/

Updated the gateway to the latest firmware. After adding my gateway to the latest final version of Domoticz, the log says:

> 2019-02-05 09:45:56.613 Status: XiaomiGateway: Worker started...
> 2019-02-05 09:45:56.614 Status: XiaomiGateway: Using 192.168.2.151 for local IP address.
> 2019-02-05 09:45:56.619 Status: XiaomiGateway: RGB Gateway Detected
> 2019-02-05 09:45:56.620 Status: XiaomiGateway: New Gateway Found (0088b9e9/Xiaomi RGB Gateway (192.168.2.70))
> 2019-02-05 09:45:56.639 Status: XiaomiGateway: New Xiaomi Gateway Alarm Ringtone Found (34ce0088b9e9)
> 2019-02-05 09:45:56.644 Status: XiaomiGateway: New Xiaomi Gateway Alarm Clock Found (34ce0088b9e9)
> 2019-02-05 09:45:56.648 Status: XiaomiGateway: New Xiaomi Gateway Doorbell Found (34ce0088b9e9)
> 2019-02-05 09:45:56.651 Status: XiaomiGateway: New Xiaomi Gateway MP3 Found (34ce0088b9e9)
> 2019-02-05 09:45:56.655 Status: XiaomiGateway: New Xiaomi Gateway Volume Found (34ce0088b9e9)
> 2019-02-05 09:45:56.664 Status: XiaomiGateway: unhandled model:
> 2019-02-05 09:45:56.664 Status: XiaomiGateway: unhandled model:
> 2019-02-05 09:45:56.664 Status: XiaomiGateway: unhandled model:

**Comment by gizmocuz** [comment]
@Bastiaan81 ,whats the domoticz version you are using ? the log message should be like:

Status: XiaomiGateway (ID=%d): unhandled model: %s

(with ID and string)

Make sure you are on the latest beta version

**Comment by Bastiaan81** [comment]
@gizmocuz , I was on the latest stable. 

After updating, the log gives more information:

> 2019-02-05 10:14:27.784 Status: XiaomiGateway (ID=2): unhandled model: , name: Xiaomi Switch
> 2019-02-05 10:14:27.784 Status: XiaomiGateway (ID=2): unhandled model: , name: Xiaomi Switch
> 2019-02-05 10:14:27.784 Status: XiaomiGateway (ID=2): unhandled model: , name: Xiaomi Switch

**Comment by gizmocuz** [comment]
Hmm this means that the 'model' field is empty...

**Comment by Bastiaan81** [comment]
I'm looking in my log, I have a Python error, could that be the problem?

> 2019-02-05 10:14:27.753 Status: EventSystem - Python: Failed dynamic library load, install the latest libpython3.x library that is available for your platform.

**Comment by swejmansson** [comment]
@gizmocuz The bulb is PartNr: 703.182.84, Model: LED1536G5 Link: https://www.ikea.com/nl/nl/catalog/products/70318284/

My present stable installation is working great, no issues at all at the moment = happy family :smile: 
Let me find my backup SD-card and i clone my installation and install latest beta from script. Is that good enough? Or do i need to compile? 


> @swejmansson , can you debug/compile domoticz ? They you could help testing.
> What is the name of the bulb ? TRÅDFRI ?
> 
> https://www.ikea.com/nl/nl/catalog/categories/departments/lighting/36812/

**Comment by lukbe** [comment]
Hello,
exist any way how to add ikea tradfri gu10 bulb connected to the xiaomi gateway in to the domoticz ?

I have last beta update (Version: 4.10603) and all devices connected to the xiaomi gateway are visible in the domoticz, only ikea tradfri bulbs are not visible :( ...

**Comment by minscof** [comment]
same question, is it possible to control ikea bulb through xiaomi gateway and domoticz ?

**Comment by boscorelly** [comment]
for now, no.

I don't know where to find the api guide for xiaomi gateway

**Comment by schmurtzm** [comment]
Please find here the API documentation for xiaomi gateway : 
https://aqara.gitbooks.io/lumi-gateway-lan-communication-api/content/
Hope this will help ;)

**Comment by boscorelly** [comment]
so, i need to query it via http and json ? or it's only an json response ?

**Comment by gytisrepecka** [comment]
Anyone figured out the way to see Ikea Trådfri lights in Domoticz when those bulbs are connected to Mi Gateway and visible via Mi App?

I can see other devices connected to Mi Gateway in Domoticz but not Ikea bulbs :(

**Comment by waltervl** [comment]
I think this issue can be closed, nowadays people better use open gateways like zigbee2mqtt or Zigate.

**Comment by gytisrepecka** [comment]
Indeed - ZiGate works smooth 👍

**Comment by gizmocuz** [comment]
Yep as well as Zigbee2MQTT (Tested with Ikea devices)

**Comment by schmurtzm** [comment]
Not agree, do we have statistics usage of the add on ? I’m pretty sure that there almost more users of this gateway compared to zigbee2mqtt.
Users have just the use to take care to not switch on the gateway after HA…
« Hey there is another product , oh yes they should use it, you can close this issue ».


I don’t understand the issue management here…
