### ISSUE TITLE
Telegram parse mode

### ISSUE THREAD

**Issue by toppe** [domoticz/domoticz#2976]
Hi Guys,

Currently i'm using the following code to send an notification to Telegram with Domoticz (dzVents):

`domoticz.notify("Domoticz", "*Warning!*\nHeavy weather is coming!", domoticz.PRIORITY_NORMAL,domoticz.SOUND_DEFAULT, "" , "telegram")`

This is working perfectly but the only thing i'm missing is `parse_mode` on HTML so i can use simple markup's for my text.

As described [here](https://core.telegram.org/bots/api#sendmessage) this is possible with the `parse_mode` set to HTML or markdown.

Anyone a suggestion how i can make text bold in the notification send via `.notify`?

**Comment by chatainsim** [comment]
It can be possible.
Add a selector in Telegram config in Domoticz: None / HTML / Markdown
Store in Domoticz database as TelegramParsemode for exemple and add it to json data around line 47
json["parse_mode"] = _parsemode; 

If I have time I can have a look but if someone else has more time, please be my guest :+1:

**Comment by toppe** [comment]
Hopefully this will be built-in because I have no idea where to edit the files haha!

**Comment by chatainsim** [comment]
Made a PR for this #3099

**Comment by chatainsim** [comment]
For now it's only markdown, but I will add support for HTML too.

**Comment by waltervl** [comment]
Partly implemented, close?
