### ISSUE TITLE
json response not guaranteed to exist in www/js/domoticz.js

### ISSUE THREAD

**Issue by ernorv** [domoticz/domoticz#298]
on lines 5100 (or about) and 5370-ish (or about), the month and year log of a wind type, the resultprev is used inside a block which only checks for the existence of the data.result in the json response. The resultprev is not guaranteed to exist, resulting in no month and year graph at all. suggest to put a check around like:

(for the month, somewhere around line 5100):
//------------------ start paste --------------------
if (typeof data.resultprev != 'undefined') {  // ERV, resultprev is not guaranteed to exist in the answer
                                $.each(data.resultprev, function (i, item) {
                                    datatable_prev_sp.push([GetPrevDateFromString(item.d), parseFloat(item.sp)]);
                                    datatable_prev_gu.push([GetPrevDateFromString(item.d), parseFloat(item.gu)]);
                                });
                            }
//------------------ end paste --------------------
and for the year graph (somewhere around line 5374 or so)
//------------------ start paste --------------------
if (typeof data.resultprev != 'undefined') {  // ERV, resultprev is not guaranteed to exist in the answer

```
                            $.each(data.resultprev, function (i, item) {
                                datatable_prev_sp.push([GetPrevDateFromString(item.d), parseFloat(item.sp)]);
                                datatable_prev_gu.push([GetPrevDateFromString(item.d), parseFloat(item.gu)]);
                            });
                        }
```

//------------------ end paste --------------------
This should then prevent the js engine from quiting on the job at hand

Regards

**Comment by gizmocuz** [comment]
Thanks, will be included in the next commit (bHavePrev)
