### ISSUE TITLE
mqtt ca-filename tls

### ISSUE THREAD

**Issue by ilsicca** [domoticz/domoticz#2980]
Hello, I have a nodemcu that connects correctly to a mqtt broker (localhost) running on port 8883 on Windows 10 with the fingerprint of the CA.
mosquitto.conf
cafile C:\mosquitto\certs\ca.crt.pem
certfile C:\mosquitto\certs\server.crt.pem
keyfile C:\mosquitto\certs\server.key.pem
tls_version tlsv1.1

Now when I add the CA-Filename to my Domoticz (localhost) it returns the error "Error: MQTT: Failed enabling TLS mode, return code: 10 (CA certificate: 'C: \ Program Files (x86) \ Domoticz \ ca.crt .pem '. "Can you help me?

![image](https://user-images.githubusercontent.com/46833657/51421778-55c23480-1b82-11e9-98b0-b923c2968721.png)

**Comment by ilsicca** [comment]
This is the log of Domoticz
 
2019-01-25 22:14:16.338  Status: MQTT: Worker stopped...
2019-01-25 22:14:17.349  Status: MQTT: Connecting to localhost:8883
2019-01-25 22:14:17.349  Error: MQTT: Failed enabling TLS mode, return code: 10 (CA certificate: 'C:\mosquitto\certs\ca.crt')

**Comment by ilsicca** [comment]
i´m resolved this issue, the ca-filename option not work in windows. I installed domoticz on debian 9 and it worked!

**Comment by ilsicca** [comment]
Hi, the mqtt not subscribed to 'domoticz/in', this is the log of domoticz
![image](https://user-images.githubusercontent.com/46833657/51803998-15298180-223a-11e9-8521-f79fc5518a87.png)

can you help me?

**Comment by gizmocuz** [comment]
Best to ask this on the forum
