### ISSUE TITLE
DzVents: Unable to switchOn device

### ISSUE THREAD

**Issue by didi31** [domoticz/domoticz#2984]
Hi
I have 3 devices with the same name: Temperature, SetPoint and switch.
The command device.switchOn() does not work on the switch device.
If I change the name of the switch device, it works.
DzVents version 2.4.6

**Comment by rwaaren** [comment]
Please use the forum for this !

From the dzVents wiki (
https://www.domoticz.com/wiki/DzVents:_next_generation_LUA_scripting )
One tip before you get started: **Make sure that all your devices have unique names. dzVents will give you warnings in the logs if device names are not unique.**

**Comment by didi31** [comment]
I did not see that...sorry
Which log are you talking about? I did not see any warning in the domoticz one.

**Comment by rwaaren** [comment]
> Which log are you talking about? I did not see any warning in the domoticz one.
domoticz log 
-- 2019-01-20 16:45:00.741  Status: dzVents: Error (2.4.10): Multiple items found for duplicateNameTest (device). Please make sure your names are unique or use ids instead.

Can you please close this issue and open one on the forum if still needed ? Thanks
