### ISSUE TITLE
Tado Radiator thermostat - Only "read" mode

### ISSUE THREAD

**Issue by vampywiz17** [domoticz/domoticz#2985]
Hello there,

My tado devices working well (a normal thermostat and a radiator one) but a few days ago, i bought a new radiator thermostat and replace the old one. After that,  i install a old device a another Radiator. Now the new Thermsotat working well, but the old one (on the new place) is only "read mode" I see all device and values in Domoticz, but i can not change it (on/off, temperature, etc...) the new one on old place is working well.

I try to delete and re-add the old device, but not help at all...

I use the latest Stable domoticz. (try the latest beta, same result)

**Comment by vampywiz17** [comment]
New info:

It not important, what device use it on third room. The problem is the third room. If i add it, can not change the values.

I try to delete all hardware and add it again, change the devices in rooms and i notice it, not important where is the new/old thermostat, the problem is the third room.

**Comment by jeanpaul1977** [comment]
I have thee same issue for quite some time now. I also have 3 zones and one of them is failing. For me it's the zone with the highest idx; I think that's what you mean with the third zone?

I checked some logging, but couldn't find anything related; using beta V4.10.420

**Comment by vampywiz17** [comment]
> I have thee same issue for quite some time now. I also have 3 zones and one of them is failing. For me it's the zone with the highest idx; I think that's what you mean with the third zone?
> 
> I checked some logging, but couldn't find anything related; using beta V4.10.420

Yes, exactly same problem! Yes the highest IDX is the bad.

Main problem that the plugin original developer is stopped the work (he use a other system now) so i dont know how to solve this problem.

**Comment by gizmocuz** [comment]
@vampywiz17 , best to change the code, or contact me on the forum (PM) with the login details and a reference to this issue, i might be able to debug

**Comment by vampywiz17** [comment]
@jeanpaul1977 @gizmocuz Any progress at your side to solve this issue?

I open a thread on new official tado Community Forum. It possible that they found something.

https://community.tado.com/en-gb/discussion/500/domoticz-integration-problem-with-third-room#latest

**Comment by jeanpaul1977** [comment]
I just updated to the latest beta: V4.10532 but still the same here.

**Comment by vampywiz17** [comment]
> I just updated to the latest beta: V4.10532 but still the same here.

@jeanpaul1977 The Tado plugin source code is not change some month ago, so it not fixed yet, yes. I don't know how to solve it, now that the original developer is left the project.

**Comment by vampywiz17** [comment]
@jeanpaul1977 I found a alternative way! Now i control Tado with IFTTT webhook (blocly scripts) . It not help the manual control , but with blockly, working like a charm!
