### ISSUE TITLE
Energy is not calculated for virtual electric sensor

### ISSUE THREAD

**Issue by krejkrejkrej** [domoticz/domoticz#2989]
I'm on Domoticz v4.10362. I've got an virtual "electric (instant+counter)" sensor. Documentation says that

> if you choose as type "Energy read : Computed", this is just a "dummy" counter, not updatable because it's the result of DomoticZ calculs from POWER

So; have set the sensor to "Computed", and am updating it using (traditional) Lua:

```
table.insert(commandArray, {['UpdateDevice'] = 
    string.format("%d|0|%d;0.0", otherdevices_idx['VP Effekt'], row.EFFEKT )})
```

I've tried feeding Domoticz different sValues, such as "2000;0" ,  "2000;0.0" or "2000", where 2000 is instant power consumption, but Domoticz does not compute energy consumption. Instead Domoticz uses the dummy energy value supplied. 

I can see there's code in SQLhelper.cpp (UpdateValueInt) to calculate energy, but it seems this code is not executed or buggy (I'm too unfamiliar with C++ ...) . I did check the device entry in the database, and the options field seems correct to me. 

I'm happy to supply any additional needed info.

**Comment by gajotnt** [comment]
From my experience it will only calculate if you use something like this:
```
return {
	on = {
	          devices = {
         'Total' --Name of the device you are reading from (this ensures your new dummy device gets updated when this one is) 
      }
	},
	
	
	execute = function(domoticz, device)
		    if domoticz.devices('Total').WhActual < -1 then
		       currentpower = -(domoticz.devices('Total').WhActual)
		        domoticz.openURL({
                        url = 'http://127.0.0.1:8080/json.htm?type=command&param=udevice&idx=98&nvalue=0&svalue='..currentpower..';0',
                        method = 'GET'})
            else
                		        domoticz.openURL({
                        url = 'http://127.0.0.1:8080/json.htm?type=command&param=udevice&idx=98&nvalue=0&svalue=0;0',
                        method = 'GET'})
            end
	end
}
```
This was the only way i could get domoticz to calculate correctly my wasted solar power.

**Comment by krejkrejkrej** [comment]
Thanks @gajotnt . That's an interesting workaround. I actually ended up calculating energy myself in Lua instead.

**Comment by gizmocuz** [comment]
Cam this issue be closed ?

**Comment by krejkrejkrej** [comment]
@gizmocuz If you ask me: No - since the problem in Domoticz has not been resolved (AFAIK).

**Comment by gizmocuz** [comment]
@krejkrejkrej , okey, as you find the code buggy, please have a look and try if you can solve this by debugging

**Comment by krejkrejkrej** [comment]
Was this problem fixed?
