### ISSUE TITLE
possibility to create custom sensors

### ISSUE THREAD

**Issue by duhlin** [domoticz/domoticz#299]
Hello,

I'm looking for the ability to create custom sensors. For instance, I've noticed that the external temperature of my raspberry pi could be evaluated with a function of the internal temperature and the cpu usage. Something like `ExternalT = f(InternalT, CPU)`.

I've understood that I can create a user variable but I would like it to be displayed as a normal temperature sensor.

What do you think of providing the ability to create custom sensors with:
- sensor type (temperature/meteo/other)
- a formula implying other sensors (it would be nice to be able to refer to values at a previous time too)

I think I'll be able to contribute to the development if you give me some advice on the implementation.

Regards,

Lionel

**Comment by gizmocuz** [comment]
I wonder how accurate this will be, did you do any testing with an external temperature sensor next to it ?
The easiest way is to add this in the hardware monitor class that already checks the raspberry pi's temperature and CPU

There are a few places where all the incoming values are going through, one is the eventsystem class
There you could do the magic of formula's and creating new sensors maybe ?
(But i would eventually put this in a separate class)

Could be a complex job, but could be nice ;)

Maybe we could somehow update blockly to the new system, and use formula's there ?
That might not be a bad idea ?

**Comment by duhlin** [comment]
Hello,

I've successfully implemented what I was looking for using a LUA script which updates the value of a dummy sensor according to the raspberry temperature and cpu usage. You were right about the accuracy of the system. It is not a perfect sensor. The precision is about 0.5 celcius in my case.

Still, I have the feeling that something can be improved to tackle problems like this one. I can see other use cases where we may want to distinguish between sensors/actuators and the displayed information.
For instance, I have a switch that put my heating to 'off' when the switch is 'on'. I'd prefer to display it has a 'heating' switch instead of the current display which is 'stop_heating'.
I think it is fairly similar to the raspberry temperature use case where I would like to apply a transformation on the measured value before displaying it.

I would see a value for a 'LUA' device which could:
- get the value from other sensors (be triggered when the value of the other sensor changes)
- set the value of another sensor (at periodic timestep or when the input changes)
  In addition, if we allow this 'LUA' device to store an internal state, it could be use to implement control laws like PID to solve the heating regulation problem for instance.

As a conclusion, I would appreciate any development to decouple the sensors/actuators and the user interface which displays or controls them. I acknowledge that it won't deliver a new functionality since it is already possible with LUA scripting and dummy devices. But in my opinion, it would be much more intuitive for new users.

What do you think?
