### ISSUE TITLE
Darksky (Weather Lookup) - no negative values in Windchill 

### ISSUE THREAD

**Issue by Sneeuwtijger** [domoticz/domoticz#2990]
Version: 4.10363
Darksky (Weather Lookup) - 
Wind device - type TFA - does not provide negative Windchill values - all values are positive.
Checked in Darksky Api call return - values in are in degrees Fahrenheit - possible mis calculation in switch to degrees Celcius?

**Comment by gizmocuz** [comment]
I don't think so, can you post a API response with a negative wind temperature value ?

I just checked with a location in Finland (66.503944,25.729391) (where it is freezing currently), and got good results

But i found possible issue, that is when the temperature was still positive, but the chill was negative, i have corrected this in beta 10393
Maybe you could check with this version, and if this does not solve it, add another darksky using 66.503944,25.729391 as location

**Comment by Sneeuwtijger** [comment]
I just checked in 10394 - positive temp and negative wind chill - problem solved.
Thx very much ;)
