### ISSUE TITLE
Feature request: Use MQTT for Thermostat Setpoint

### ISSUE THREAD

**Issue by MiloshCZ** [domoticz/domoticz#2991]
Hi,
is it possible to add support for Thermostat setpoint in MQTT protocol? I would like to create simple thermostat control panel (ESP8266 + display), but there is no simple way how to change thermostat setpoint via MQTT.
I create some workaround via uservariable and simple script, but ....

Thank you

**Comment by maxcrystal** [comment]
I think it could be done with the same command as for temperature sensor: https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Temperature

**Comment by MiloshCZ** [comment]
@maxcrystal  Thank you for your idea. It is working (I have tried somoething similiar, but without success.

Right MQTT command is:
`{"command":"udevice","idx": 34,"nvalue":1,"svalue" : "10"}`
