### ISSUE TITLE
Bug with Xiaomi smart switch

### ISSUE THREAD

**Issue by Milan1989** [domoticz/domoticz#2992]
Domoticz version: 4.9700
Xiaomi gateway firmware:1.4.1_164.0158

Xiaomi smart switch: https://www.gearbest.com/smart-light-bulb/pp_257679.html?wid=1433363

There is a bug in domoticz when I use Xiaomi smart switch. If I push the switch once it appers in Domoticz twice as you can see in the log. 

![2019-01-24_17h53_10](https://user-images.githubusercontent.com/35316485/51695555-99de8a80-2003-11e9-838e-73fbb196c398.png)

**Comment by gizmocuz** [comment]
Thanks for reporting, send you an email

**Comment by Milan1989** [comment]
Hello,

Is there any update for this issue. Unfortunately the problem is still exist.

Thanks

**Comment by Milan1989** [comment]
Issue can be closed. Problem has been solved.
