### ISSUE TITLE
System Alive Checker (Ping) not working on V. 4.10364

### ISSUE THREAD

**Issue by bennydente** [domoticz/domoticz#2999]
I'm on Version: 4.10364
i have enabled System Alive Checker (Ping) and add one IP on same network. but the device not go on ON state. of corse the target IP is alive. thanks, bye.

**Comment by Siewert308SW** [comment]
I'm on RPi3 with same version without issues. All devices are toggling.

**Comment by bennydente** [comment]
Ubuntu 18.04 for me.

**Comment by sweetpants** [comment]
Working fine on my Ubuntu 18.04 installation

**Comment by trandbert37** [comment]
Try with another device. It may not be able to answer ping ..

**Comment by bennydente** [comment]
The target device respond to ping command.

i see this error in syslog
Jan 29 10:16:55 XXXX domoticz[1876]: 2019-01-29 10:16:55.446  (IP monitor) Lighting 2 (Gateway)
Jan 29 10:17:01 XXXX CRON[1923]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jan 29 10:17:27 XXXX domoticz[1876]: sudo: unable to change to root gid: Operation not permitted

**Comment by bennydente** [comment]
hi. i reinstall operating system and now work. I don't understand why first don't. thanks.
