### ISSUE TITLE
inclusion impossible of a valid device

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#3000]
Version: 4.9700 stable
Platform: RPI3 b+
Plugin/Hardware: trio2sys temperature sensor 10020076 protocol enOcean
Description:
The product is in the hardware list of domoticz but the inclusion is impossible (EEP=A5-02-13)
Dongle usb used: usb300

Note: with the DolphinView software the inclusion is possible -> dongle and device run correctly

**Comment by gizmocuz** [comment]
Have you tried the beta version ?

**Comment by ghost** [comment]
No.
Why ? Is it the solution ?
I don't see the correction in the history.txt dated October 2018

Is it possible to debug the inclusion ?

**Comment by ghost** [comment]
Inclusion solved with the 4.10373 version

But no graphic of the temperature (pressing the temperatureLog icon of the device display the dashboard !)

**Comment by gizmocuz** [comment]
Try to delete the browser cache and appcache

**Comment by ghost** [comment]
That was the solution !
Many thanks
