### ISSUE TITLE
Low refresh rate Enphase solar data

### ISSUE THREAD

**Issue by rbakker69** [domoticz/domoticz#3001]
With the Enphase Envoy link I noticed a 15 min refresh time, which makes it difficult to calculate a real power consumption, because the P1 export/import values are updated every 10 sec.

I use the envoy-metered and the latest Domoticz beta version and looked up the source code to find out how the Enphase data is collected.  It would be nice to pick the values of the next section from the production.json output, which hold the current values. See production.json output below.

Is it possible to make a change in the following file/function?

File: domoticz/hardware/EnphaseAPI.cpp   
Function: EnphaseAPI::getProductionDetail()

	#Old: Getting production data wich is only refreshed every 15min
	#Old: Values are integers: "wNow":34, "whLifetime":681670
	Json::Value reading = root["production"][0];

	#New: use current data, so the 30s interval is getting always new data
	#New: More accurate values: "wNow":23.511, "whLifetime":697091.391 
	#New: Not sure if a rounding of the value is needed
	Json::Value reading = root["production"][1];

================================================

Complete output of production.json of the Enphase Envoy-metered:
{
	"production":[
	{
		"type":"inverters",
		"activeCount":10,
		"readingTime":1548862916,
		"wNow":34,                                            --> 15 minutes refresh time
		"whLifetime":681670                              --> 15 minutes refresh time
	},
	{
		"type":"eim",
		"activeCount":1,
		"measurementType":"production",
		"readingTime":1548863583,
		"wNow":23.511,                                      --> always current and accurate
		"whLifetime":697091.391,                       --> always current and accurate
		"varhLeadLifetime":0.127,
		"varhLagLifetime":572791.172,
		"vahLifetime":1153328.827,
		"rmsCurrent":0.667,
		"rmsVoltage":229.543,
		"reactPwr":146.969,
		"apprntPwr":153.036,
		"pwrFactor":0.14,
		"whToday":2694.391,
		"whLastSevenDays":11686.391,
		"vahToday":4667.827,
		"varhLeadToday":0.127,
		"varhLagToday":2518.172
	}],
	"consumption":[
	{
		"type":"eim",
		"activeCount":1,
		"measurementType":"total-consumption",
		"readingTime":1548863583,
		"wNow":254.196,
		"whLifetime":879000.134,
		"varhLeadLifetime":938688.689,
		"varhLagLifetime":608796.487,
		"vahLifetime":1763836.794,
		"rmsCurrent":2.282,
		"rmsVoltage":229.57,
		"reactPwr":-383.624,
		"apprntPwr":523.805,
		"pwrFactor":0.49,
		"whToday":4151.134,
		"whLastSevenDays":36909.134,
		"vahToday":7210.794,
		"varhLeadToday":4068.689,
		"varhLagToday":2961.487
	},
	{
		"type":"eim",
		"activeCount":1,
		"measurementType":
		"net-consumption",
		"readingTime":1548863583,
		"wNow":230.685,
		"whLifetime":660660.244,
		"varhLeadLifetime":938688.562,
		"varhLagLifetime":36005.314,
		"vahLifetime":1763836.794,
		"rmsCurrent":1.614,
		"rmsVoltage":229.597,
		"reactPwr":-236.655,
		"apprntPwr":370.634,
		"pwrFactor":0.63,
		"whToday":0,
		"whLastSevenDays":0,
		"vahToday":0,
		"varhLeadToday":0,
		"varhLagToday":0
	}],
	"storage":[
	{
		"type":"acb",
		"activeCount":0,
		"readingTime":0,
		"wNow":0,
		"whNow":0,
		"state":"idle"
	}]
}

**Comment by rbakker69** [comment]
By googling a bit further I noticed that my production.json output is only valid for the 'envoy-s metered'. The standard envoy-s has only the first section: root["production"][0].

So the current code is right for the envoy-s so this issue should be een enhancement request for supporting the metered version. This could be done by adding a type field and handle the collecting different, or could be a new hardware item 'Enphase Envoy Metered with LAN (HTTP) interface".

**Comment by gizmocuz** [comment]
Can't you detect if it contains the second section/field, and if so, use this instead?

**Comment by rbakker69** [comment]
That could be an option, but than the output must be evaluated, because the use of current meters is always optional. I think personally it is good to facilitate the choice that Enphase is given: use the metered data or use the inverters data. This could be facilitated in the hardware configration below the IP address and port with the option: use metered data. 

Additional it should be nice to show a zero value for used, when the solar panels produce no more power. Somehow the metered data always show a negative value after sunset.

**Comment by Sebastiii** [comment]
Hi,
Is there any update on this ?
Thanks

**Comment by waltervl** [comment]
domoticz/hardware/EnphaseAPI.cpp seems to be updated a lot since creation of this issue. especially https://github.com/domoticz/domoticz/commit/c618c9d19e65880ac55f9f9495b40912d00401f1
