### ISSUE TITLE
[Feature] Duplicate scenes

### ISSUE THREAD

**Issue by cconde** [domoticz/domoticz#3003]
I'm making my first Domoticz setup and I'm creating some scenes for the home.

I have a few similar ones, and I've missed the possibility to duplicate an existing scene, as a template for a new one.

This could be useful, and even esxtend to sensors, etc...

Thank you for this great job!
Ivan

**Comment by cconde** [comment]
Just in case I'm outdated:

Version: 4.9700
Build Hash: b97777b
Compile Date: 2018-06-23 16:18:06
dzVents Version: 2.4.6
Python Version: None

**Comment by gizmocuz** [comment]
This is currently not possible, and as work-around you have to create them again... 
Because it's just a view you should be done now ;)

**Comment by GeitjeG** [comment]
Is it already possible to implement this? Would really come in handy in my case. I have large scenes...

**Comment by rwaaren** [comment]
Other workaround (tested and working on V2020.2 (build 12068)

create new empty / group in GUI
write down old idx / new idx

```
stop domoticz 
backup domoticz.db
sudo sqlite3 domoticz.db

insert into SceneDevices(SceneRowID, DeviceRowId, Cmd, Level, Color, OnDelay, OffDelay) select <new idx> , DeviceRowID,Cmd, Level, Color, OnDelay, OffDelay from SceneDevices where SceneRowID = <old idx> ;

.quit
start domoticz 
```

**Comment by MikeyMan83** [comment]
Would like to have this feature as well. Especially to lighten the burden of the Zwave migration.
