### ISSUE TITLE
AnnaThermostat not working since firmware 3.1.4

### ISSUE THREAD

**Issue by Ectholian** [domoticz/domoticz#3006]
Since firmware 3.1.4 of Anna Thermostat (Domoticz Version: 4.9700) the plugin is not working anymore. The only thing logged is:
Error: AnnaThermostat: Invalid data received!

Scanning the source it seems a xml parsing failure, but if i try to parse the xml locally with the source it doesn't report any problems. There are more users with this problem:

https://www.domoticz.com/forum/viewtopic.php?f=6&t=26741&p=205387

**Comment by gizmocuz** [comment]
Could you contact me on the forum with some login credentials ? Or post the XML here please

**Comment by p-hagen** [comment]
I am about to push a fix for this

**Comment by gizmocuz** [comment]
Thanks for the PR, does this solve the issue ?

**Comment by Ectholian** [comment]
I am unable to test it myself since i dont have a linux development environment set up and i am using a jadahl dsm package from the stable line. I will ask in the forum topic for someone to test.

**Comment by gizmocuz** [comment]
@Ectholian , if you own a windows version, you could download/install/test the windows version

**Comment by p-hagen** [comment]
It resolves the issue . I have tested it from a Mac and raspberry and in has been reported in the forum by an other user that it solved it for them too

**Comment by gizmocuz** [comment]
Great, Thanks for the feedback and PR!

**Comment by Ectholian** [comment]
Thanks guys!

**Comment by p-hagen** [comment]
np

**Comment by ivooovi** [comment]
I am using for many years the Anna thermostat with Domoticz but with the upgrade to the latest beta I get now invalid data received in my logs. It is not working. My Anna is on firmware 1.8.20.

Can you please assist

**Comment by WilliamRoxit** [comment]
> I am using for many years the Anna thermostat with Domoticz but with the upgrade to the latest beta I get now invalid data received in my logs. It is not working. My Anna is on firmware 1.8.20.
> 
> Can you please assist

This issue is fixed in the development branch. So you need to install one of the beta's, version 4.10406 or newer. For support it is better to visit the forums: http://www.domoticz.com/forum/viewtopic.php?f=6&t=26741

**Comment by ivooovi** [comment]
> > I am using for many years the Anna thermostat with Domoticz but with the upgrade to the latest beta I get now invalid data received in my logs. It is not working. My Anna is on firmware 1.8.20.
> > Can you please assist
> 
> This issue is fixed in the development branch. So you need to install one of the beta's, version 4.10406 or newer. For support it is better to visit the forums: http://www.domoticz.com/forum/viewtopic.php?f=6&t=26741

I also posted in this forum and some more people that there are Anna versions that can't be upgraded beyond firmware 1.8.20. I am running the latest beta of Domoticz on my rPi.

**Comment by Ectholian** [comment]
I see. It looks like the fix for firmware 3.1.4 broke the plugin for firmware 1.8.20. I am unable to re-open this issue i guess? @gizmocuz @p-hagen

**Comment by p-hagen** [comment]
Working on it.....
