### ISSUE TITLE
Request: Thermostat logging, missing devicename

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#3009]
In the domoticz logging with Thermostats there is the devicename missing.
`2019-02-02 20:59:01.053  EventSystem: Sending Thermostat Mode to device....
2019-02-02 20:59:01.060  EventSystem: Sending SetPoint to device....
2019-02-02 20:59:01.079  EventSystem: Sending SetPoint to device....
`
On the place of the .... it would be nice to have the devicename, and to what something is changed..

**Comment by gizmocuz** [comment]
An option is to add a log message yourself in your event... but it should be implemented now in beta 10405

**Comment by SargonofAssyria** [comment]
Tnx, is it possible to log the new setpoint value also?

**Comment by gizmocuz** [comment]
Sure, will be available in beta 10411 and up

**Comment by SargonofAssyria** [comment]
Tnx, again. 💯 %
