### ISSUE TITLE
[Xiaomi Gateway ] Wrong BatteryLevel reported for temp domoticz device from a flumi.weather sensor

### ISSUE THREAD

**Issue by lboue** [domoticz/domoticz#3010]
### BatteryLevel Issue 

I would report an issue with domoticz 'Temp' device from a flumi.weather sensor paired with a Xiaomi Gateway (lumi.gateway.v3):

* Running Domoticz V4.10395
* Issue: BatteryLevel reported wrong value for for 'Temp' device from a flumi.weather sensor. I remains  always at 100% level
* Compare : BatteryLevel reported OK for for 'Temp + Humidity' device from a flumi.weather sensor

**Exemple for a561 ID device (voltage reports 3005):**
```
pi@raspberrypi:~ $ miio inspect 158d0001a4a561
 INFO  Attempting to inspect 158d0001a4a561

Device ID: 158d0001a4a561
Model info: lumi.weather
Address: Owned by miio:52051463
Token: Automatic via parent device
Support: At least basic

Type info: sensor, miio, miio:subdevice, sub-thing
Capabilities: battery-level, atmospheric-pressure, relative-humidity, temperature, state

Properties:
  - voltage: 3005
  - temperature: 21.23
  - humidity: 48.05
  - atmosphericPressure: 101350
Parent:
  Device ID: ***51463
  Model info: lumi.gateway.v3
  Address: 192.168.1.4
  Token: *******************via auto-token
```

You can check by yourself on the screenshot. 

![image](https://user-images.githubusercontent.com/938089/52175537-a0a89280-27a5-11e9-82ba-70a8f5437dce.png)

Regards,

**Comment by gizmocuz** [comment]
the flumi.weather sensor .. is it a temp+hum device ? it has the same ID, why is there a temp only device ?
I think that should not be there at all, and you should only see the temp+hum device

**Comment by gizmocuz** [comment]
Made some small changes. It should not generate duplicate sensors anymore. (so your temp sensors won't update anymore, only your temp+hum in your case)
Could you try beta 10406 ?

The 'temp' sensor in domoticz does not have a battery percentage, only a low/high

**Comment by lboue** [comment]
Thanks for this change. 

I own THB Xiaomi square sensors (temperature + humidity + atmospheric-pressure). You can find it on [gearbest website](https://www.gearbest.com/access-control/pp_626702.html).

I did the upgrade to beta 10406. I removed all my Xiaomi 'temperature' devices and they didn't come again after that. I can confirm that doen't generate duplicate sensors anymore.

I also removed 'Temp + Humidity' devices. It seems that TH (Temp + Humidity) devices are generated but with is a strange behavior. I have new sensors with name 'Xiaomi Pressure' and type 'Temp + Humidity'.

But BatteryLevel is OK now.

![image](https://user-images.githubusercontent.com/938089/52177101-9f369480-27bc-11e9-9187-65e5b3f62dcd.png)

**Comment by gizmocuz** [comment]
Sorry about that, will be solved in beta 10408

**Comment by lboue** [comment]
Thanks for the fix on naming. 
After few hours, the same issue occur as you can see:

![image](https://user-images.githubusercontent.com/938089/52180150-dc158200-27e2-11e9-9cfd-34a53b2b8271.png)

Same issue with Beta  4.10411.

**Comment by gizmocuz** [comment]
This can only mean that sometimes the gateway only receives a temperature and not the corresponding humidity.
Seems like the Node (or the controller/gateway) handles it like it is sending/receiving the temperature first, then a temp+hum then a temp+hum+baro
What temperature node have you got ? (maybe a link to aliexpress)

One way to prevent this, is to internally keep a record what the best type of the sensor is, if it was once a temp+hum+baro, keep threading this as such.
This needs to be stores/reloaded from the database as well, we can use the MySensorsChilds table for this
