### ISSUE TITLE
Replace Device (Domoticz Manual P.20) sometimes crashes domoticz.

### ISSUE THREAD

**Issue by sincze** [domoticz/domoticz#3011]
Domoticz V4.10395
I tried the domoticz manual p20 to replace an old device that had a new ID due to battery replacement.
Domoticz Crashed.... after restart I was able to replace the device. (RFXCOM ID)
I tried to replace another device (RFLINK ID) -> domoticz crashes.
after restart I was able to replace the device.

It goes wrong as soon as I select the NEW device and press replace.
[domoticz-2019-02-03_113308.txt](https://github.com/domoticz/domoticz/files/2825416/domoticz-2019-02-03_113308.txt)

I've seen this issue before the latest beta as well. but unable to find the cause.

**Comment by gizmocuz** [comment]
Could it be that it takes a very long time (you have lots of history), and the mainthread (watchdog) kills domoticz ?

**Comment by sincze** [comment]
Could be indeed. Tempsensor Data goes back to 2016.

**Comment by gizmocuz** [comment]
Are you able to compile yourself ? If yes, could you add a 'return' here

```
void MainWorker::HeartbeatCheck()
{
 return;
..
..
}
```
I think this is the routine causing the issue

**Comment by sincze** [comment]
At the moment the setup is in such a way that I always download the latest version.
However I found https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source so let me give it a try.

**Comment by sincze** [comment]
> Are you able to compile yourself ? If yes, could you add a 'return' here
> 
> ```
> void MainWorker::HeartbeatCheck()
> {
>  return;
> ..
> ..
> }
> ```
> I think this is the routine causing the issue

ok almost ready to compile. In which file should I look to make the change before compiling ?

**Comment by sincze** [comment]
Found the mainworker.h and modified to:

        void HeartbeatCheck()
        {
                 return;
        }

**Comment by sincze** [comment]
Modified the /main/mainworker.cpp

```
void MainWorker::HeartbeatCheck()
{
        return;
        std::lock_guard<std::mutex> l(m_heartbeatmutex);
        std::lock_guard<std::mutex> l2(m_devicemutex);

        m_devicestorestart.clear();

        time_t now;
        mytime(&now);
        ..
       ..
}
```

**Comment by sincze** [comment]
Compiling started 17:00 on RPI 3.

**Comment by gizmocuz** [comment]
Thanks!

**Comment by sincze** [comment]
> Thanks!

For some reason after 15 minutes or so compiling (make -j 3) crashed the SSH session and the services running on the PI. (had no access). Restarted the Pi, starting over

**Comment by sincze** [comment]
Still no luck... 
Created 3 GB SWAP file now... hopefully that will fix it. So it can complete the compiling part.
[source](https://digitizor.com/create-swap-file-ubuntu-linux/)

**Comment by sincze** [comment]
Ok with the SWAP file... it does not crash... but it is not fast at all.
After 2 hours....
[ 39%] Building CXX object CMakeFiles/domoticz.dir/hardware/DenkoviUSBDevices.cpp.o

**Comment by sincze** [comment]
Damn... ssh session stopped again.. Is there a way to easily cross compile on my windows 10 machine for a Pi? That would speed up the process a lot. i7 with lots of memory ;-)

**Comment by sincze** [comment]
Meanwhile:

$sudo make -j 3 >> /var/tmp/make.log &
$tail -f make.log

**Comment by sincze** [comment]
I can confirm, after modification. I replaced 10 devices without domoticz crashing.
Seems 1 line solved the issue! 
It took over 8 hours to compile on my SD powered Raspberry PI..
Whats next?

**Comment by gizmocuz** [comment]
Thanks for the confirmation. Yes it's a long compile time, that is why you can also use the binaries from our build server.
I will make some code changes that it will not call abort

Bdw, you have to follow the wiki how to compile, it is not -j 3 !
