### ISSUE TITLE
settings-hardware page - modification of parameters

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#3016]
Hello,
Please apologize my vision of dummy ...

In order to modify, for example, the serial port of a device, you must go in the ADD form but you must click the Update button above to confirm the mofidication.
It's a little bit confusing.
If you click the ADD button you create a new device and if you delete the old one, you lost the data !
I think IMHO that the layout could be updated to make the dialog more coherent.

**Comment by gizmocuz** [comment]
You need to press the "ADD" button to add a new hardware.
When you selected a hardware, you have the options to "Update" or "Delete" the hardware
It's like this in almost every editor

But if you know a better way, please propose a layout (drawing)

**Comment by ghost** [comment]
What is confusing for me is the position of the button: why I must go in the ADD form to make an update ?!
I don't know the opinion of the other users.
I also note there is no consistency with the "devices" page. In this page, you select the line and you press the icons at end of the line. A dialog form is displayed and you do or not your modification.
Why not to harmonize the principle ?
It's only a suggestion. I can live with the actual solution !
The idea behind would to have a graphical chart for all functions of domoticz.
What do you think about it?
I am a dummy and also a dreamer ...

**Comment by ghost** [comment]
Or somethin like that:
![domo1](https://user-images.githubusercontent.com/194631/52295119-4c570b80-297b-11e9-962a-430aaf5b4b28.jpg)
![domo2](https://user-images.githubusercontent.com/194631/52295139-537e1980-297b-11e9-9512-26440076e680.jpg)
![domo3](https://user-images.githubusercontent.com/194631/52295147-57aa3700-297b-11e9-8539-e0c9ea264929.jpg)
