### ISSUE TITLE
Make the dummy gascounter acting like the real gascounter

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#3018]
Developers...

Is it perhaps possible to get the dummy gas counter make exactly the same like the real gasmeter.
In the real there is a other total counter then in the dummy.
The dummy is not counting the total days so there is not a yearly counter like the real counter.
The dummy starts every day with 0?

Perhaps?

**Comment by gizmocuz** [comment]
User...

The Gas device is not starting everyday from 0... it is probably your feed that resets everyday and starts counting from zero
The 'real ?' and the 'dummy' device is 100% the same !
So please check your source and update script... 

What hardware are you using ? Maybe you should get a P1 meter !

Please use the forum

**Comment by waltervl** [comment]
Can be closed.
