### ISSUE TITLE
MySensors : Allow printing I_LOG_MESSAGE internal messages in log view

### ISSUE THREAD

**Issue by harty911** [domoticz/domoticz#3019]
In MySensor specification, there is a dedicated INTERN command type to log messages in the controller
"I_LOG_MESSAGE(9) Sent by the gateway to the Controller to trace-log a messages.

Is it possible to log these messages in the log view ?

This issue is different from #1320, the purpose here is not to debug a gateway or sensor. The goal is to monitor logs coming from gateway or sensor. 

In my case, I develop some smart sensors, and I use theses messages when some hardware failure or malfunction occurs. 

I found another similar topic in forum:
http://www.domoticz.com/forum/viewtopic.php?f=31&p=205202

**Comment by gizmocuz** [comment]
@harty911 , sure this is possible. As i assume you can make your own sketch, please make a pull request here with the needed changes

**Comment by ZHEL12** [comment]
加上qq群；933241376

**Comment by efrainmrz** [comment]
https://www.facebook.com/kathia.maciasuribe

**Comment by ardi814** [comment]
wow dong tapi saya ga peduli
