### ISSUE TITLE
Netatmo wind gauge not updated anymore

### ISSUE THREAD

**Issue by nonolk** [domoticz/domoticz#3020]
Hello,

Since I updated domoticz to the last beta version (4.10415), my wind gauge is not updated anymore. All other modules from my weather station are proprely updated. 

Best regards,

**Comment by sweetpants** [comment]
Could it be related to this? https://github.com/domoticz/domoticz/commit/cc75ca02337471bae56aca1a469399c67fcde866

**Comment by nonolk** [comment]
Yes, might be.

**Comment by nonolk** [comment]
So after investigation, it seems in fact there is a new device created for my wind gauge.
I don't think this is wanted ? Isn't it ?

**Comment by criscaru** [comment]
> Hello,
> 
> Since I updated domoticz to the last beta version (4.10415), my wind gauge is not updated anymore. All other modules from my weather station are proprely updated.
> 
> Best regards,

The same happens to me for Netatmo Thermostats. I see only the following error:
 Error: Netatmo: cloud data for module [XXXXXX] no longer updated (module possibly disconnected)

**Comment by gizmocuz** [comment]
@nonolk , it's indeed not so nice that a new device is created...
But you can replace your old device in domoticz with the new one

**Comment by nonolk** [comment]
@gizmocuz, yes I know that I could replace a device by another one of the same kind. But in this particular case it didn't work as the only option I had, was to select and unknow device. The newly created device name is "Anemometre2".....
![image](https://user-images.githubusercontent.com/26922736/52341174-36e0f080-2a12-11e9-9bd9-671ee3914e2e.png)

**Comment by nonolk** [comment]
Wait, I think I understand why I can't select the new device, in fact there is a litle diffrence between the old and the new device. The new device doesn't have the "feels like" temperature.
I this case, as it was wrong it's a good thing.

@gizmocuz do you think this is the reason why, I could not replace the old device with the new one?

**Comment by 999LV** [comment]
@criscaru , @gizmocuz , my recent PR was meant to address the weather sensors timeouts. I realize that thermostats have a different refresh interval, so should be skipped from the timeout check. I made a new PR to implement this ( #3023 )

**Comment by gizmocuz** [comment]
Thanks!
