### ISSUE TITLE
Fix for Anna thermostat firmware 3.1.4 XML breaks  firmware 1.8.XXX

### ISSUE THREAD

**Issue by p-hagen** [domoticz/domoticz#3021]
The fix merged earlier this week  fixed the changed  the read error caused by  the file format by firmware 3.1.4 in the ANNA gateway (Plugwise smile). and advise was given to upgrade to that version.
However older ANNA's do not seem to have the option to upgrade.

Solution proposed to resolve above issue is: 
Determine right after Init()  which way of transforming the XML output works and  set a flag.
Check flag and use appropriate transformation at every GetMeterDetail();

Status: Code is ready and working/tested  with version 3.1.4 of the Anna Gateway firmware for  Domoticz running on Mac and Raspberry but needs test/verification against older Anna. 

Only way I can  test is with remote access to an  ANNA  with firmware 1.8.xxx
I wait to see if its provide otherwise I push the change if no one objects

**Comment by gizmocuz** [comment]
Sounds great ! Detection of the firmware type seems the way to go

**Comment by ivooovi** [comment]
hi @p-hagen , 
maybe I can do a test for you as I have an Anna on 1.8.20, controlled via Domoticz on rPi latest beta. Please let me know.

**Comment by jgaalen** [comment]
I've made another pull request and was successfully tested with XML of 1.8.20 and 3.1.4

**Comment by p-hagen** [comment]
Thh Latest pull request  from @jgaalen works and is tested with physical 3.1.4
