### ISSUE TITLE
geocoder.geocode service fails with REQUEST_DENIED

### ISSUE THREAD

**Issue by gopsgithub** [domoticz/domoticz#3026]
Geocode service call is not working for the past few weeks, below URL is called
https://maps.googleapis.com/maps/api/js/GeocodeService.Search?
 
I have manually executed the url and getting the below error
 
/**/_xdc_._5x72we && _xdc_._5x72we( {
   "error_message" : "Geocoding Service: You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key",
   "results" : [],
   "status" : "REQUEST_DENIED"
})

**Comment by gizmocuz** [comment]
@gopsgithub , as stated when you created this issue, you NEED to specify your domoticz version, AND also try the beta version if you report errors
I suggest you do the later
