### ISSUE TITLE
Add functionality to telegram notifications

### ISSUE THREAD

**Issue by cronyx** [domoticz/domoticz#3029]
Enhancement:
Need to add telegram notifications ability to use socks5 proxy, since in some countries telegram are banned by DPI. If possible, it was great. Thanks!

**Comment by gizmocuz** [comment]
Can you setup your system to always use a socks proxy ?
You can also have a look at PushOver for instance

**Comment by cronyx** [comment]
> Can you setup your system to always use a socks proxy ?

it's a bad idea, if the proxy stops working, I may not receive important notifications.

> You can also have a look at PushOver for instance

No, i'm use GCM notification as primary and telegram as secondary. Tor server as socks5 proxy on localhost (127.0.0.1:1080) for blocked services. Since it is not possible to use a built in notification system via telegram without a proxy, I use a script for alerts, this is not very convenient.

```
#! /bin/bash

# Proxy setup
PROXY_IP="80.*.*.*"
PROXY_PORT="1080"

# Bot setup
BOT_ID="bot********"
TOKEN="*********"
CHAT_ID="******"

curl -x socks5://$PROXY_IP:$PROXY_PORT "https://api.telegram.org/$BOT_ID:$TOKEN/sendMessage?chat_id=$CHAT_ID&text=$1"
```
I would like to have a check box "use proxy" in the settings telegram notifications and be able to use the built-in system.

options for curl to activate proxy

curl_easy_setopt(curl, CURLOPT_PROXY, "127.0.0.1:1080");
curl_easy_setopt(curl, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5);
