### ISSUE TITLE
MySensors hardware submenu missing

### ISSUE THREAD

**Issue by BmdOnline** [domoticz/domoticz#3033]
Hi,

Using Domoticz v4.10411 (but problem is older), I can't access "Setup" submenu in hardware configuration for MySensors.
Button `Setup` is displayed, but when I click on it, I have an empty screen (only "Device: MySensors" is displayed, nothing else).

It occurs when I try to use `MySensors Gateway USB` or `MySensors Gateway with MQTT interface`
But it works correctly when I try to use `MySensors Gateway with LAN interface`

I've tried with french and english interface.
![image](https://user-images.githubusercontent.com/5605245/52524316-fd231a80-2c9b-11e9-8fb0-d4c21f435eb1.png)

![image](https://user-images.githubusercontent.com/5605245/52524327-14620800-2c9c-11e9-9961-f96972b2235d.png)

**Comment by sweetpants** [comment]
This must be a caching problem because I do not have this issue and have never seen it. Currently i am on 4.10421
![image](https://user-images.githubusercontent.com/23421160/52524795-69544d00-2ca1-11e9-9f2a-fcfd696f17fb.png)

**Comment by BmdOnline** [comment]
I've tried from 2 computers (Windows / Linux) and 2 browsers on Windows (Edge / Firefox nightly).
I've tried with 2 domoticz installations (2 archlinux computers).
Curious !

I will try to upgrade and try again.

**Comment by BmdOnline** [comment]
Installed 4.10421 and have same problem !
![image](https://user-images.githubusercontent.com/5605245/52525502-04055980-2cab-11e9-884c-c6d00b1df392.png)

**Comment by BmdOnline** [comment]
I've tried several commits and found it :
The problem occurs since release 4.10403 (commit 3c0a6c3b04225b7b8dd11d16d09c00e802ce9252)

**Comment by stas-demydiuk** [comment]
@BmdOnline I will take a look

**Comment by BmdOnline** [comment]
Commit 91a981efa298df042327450ddae4a44237bfb10e seems to correct the problem.
I've manually compiled v4.10426 and it works.

I'm going to deploy it on my servers now, and check again if it's okay.
Thanks.

**Comment by BmdOnline** [comment]
Yes, problem is really corrected. Everything seems to works correctly.
Thanks.
