### ISSUE TITLE
Please add idx in response when a RoomPlan is created

### ISSUE THREAD

**Issue by Xorfor** [domoticz/domoticz#3037]
If I use the Domoticz API/JSON to add hardware and/or devices, I get a response with the idx of the created hardware/device. However, when I created a roomplan with `/json.htm?type=command&param=addplan&name=NAME`, I get a response without the idx of the created roomplan. Please add this idx in the response.
This will make it much more easier, to add devices to the roomplan with other rest calls, because names are not unique in Domoticz, only the idx.

**Comment by gizmocuz** [comment]
Not sure why this is needed.
The gui has no issues adding room plans.
When you add a roomplan, you need to refresh the roomplan table as well.
The highest idx is of course the new roomplan

**Comment by Xorfor** [comment]
You are right, it is not required for the gui, because the user clicks on the roomplan and add devices.

However, when I am using Python and the Domoticz JSON/API calls to add a roomplan with something like 'curl http://localhost:8080/json.htm?type=command&param=addplan&name=NAME', I do not get the idx in the response. So I have to use '/json.htm?type=plans' and find a roomplan with the name NAME. Because the roomplan name is not unique I am not really sure that I will get the correct idx.
The call to create a uservariable (/json.htm?type=command&param=adduservariable) also doesn't return the idx, but here the variable name has to be unique so I am sure that I will find the correct idx! 
The JSON/API calls to create hardware or devices always return the idx. 

To add the idx in the response of the created roomplan (and also for adduservariable and adduser?), makes the JSON/API more flexible and act like the other hardware and device calls.

**Comment by gizmocuz** [comment]
Yes you are correct about the creation of the hardware...
If you can program python, you should have no problem adding this option...

But in the upcoming beta it has been added:
https://github.com/domoticz/domoticz/commit/09534cd76dfd2e5f9cc28a0f1208ffea04303a29

**Comment by Xorfor** [comment]
Works great. Thnx!!!
