### ISSUE TITLE
Hard to distinguish which level is selected on selector switch. 4.10416

### ISSUE THREAD

**Issue by ressof** [domoticz/domoticz#3038]
It is hard to distinguish which level is selected on selector switches when both selected and unselected levels are blue.
![image](https://user-images.githubusercontent.com/15242922/52554979-be4eab00-2de8-11e9-8336-9cd42274a9d6.png)

**Comment by mcmikev** [comment]
+1 very hard to see indeed.

**Comment by dotWils** [comment]
+1 very hard indeed

**Comment by gizmocuz** [comment]
Thanks for reporting... fixed in beta 10678

**Comment by dotWils** [comment]
Still the same in 10678...

**Comment by harryd100** [comment]
Clearded browser and application cache?

**Comment by dotWils** [comment]
Is Red button now, like something is wrong or in error for which this color is usually used.
Maybe Green?

**Comment by gizmocuz** [comment]
Actually it should be purple like all other button's highlight colors

New beta available (10682)

**Comment by dotWils** [comment]
Looking great! Better!
