### ISSUE TITLE
Custom graph - for temperature + switches

### ISSUE THREAD

**Issue by mmodzele** [domoticz/domoticz#304]
Now 'custom graph' is available for temperature only (we are able to compare selested temperatures on the graph)

It will be great if possible to have custom graph for temperature + switches

(because often switches are controlling temperature so it will be great to have both on one graph!)

**Comment by gizmocuz** [comment]
Could you make this and submit a pull request?
Maybe a general custom graph under the settings menu
(graphs for all sensor types)

**Comment by gizmocuz** [comment]
no response or pull request
