### ISSUE TITLE
UI status of blinds differs from status of blinds in the device log 

### ISSUE THREAD

**Issue by aschaake** [domoticz/domoticz#3042]
I have a strange problem. When I open my sunscreen (Blinds) Domoticz shows themessage Open (that's right) When I close them domoticz UI shows Closed (Thats also right). But when i push Open and at the desired point i stop the opening proces by pushin g the stop button Domoticz used to say stopped in the UI in previsous versions (3.XXX). But now when I push STOP the domoticz UI say CLOSED.

The log says STOP ande the UI dashboard and the switches pannel both show CLOSED as status. Can this be fixed so open shows open in the ui, close shows closed, and stop shows stopped again?

The log:
[http://schaake.info/images/log_zonnescherm.PNG](url)

The UI:
[http://schaake.info/images/ui_stop.PNG](url)

Version: 4.10427 on RPI3

**Comment by aschaake** [comment]
anyone with this problem? Think its a bug? Wre can I find the bigtext field so I can change it myself???

**Comment by sweetpants** [comment]
Your images are not visible, just drag them into this window

**Comment by aschaake** [comment]
![ui_stop](https://user-images.githubusercontent.com/39566739/52918293-9635df00-32f5-11e9-80ab-e20f1634c8d7.PNG)
![log_zonnescherm](https://user-images.githubusercontent.com/39566739/52918294-98983900-32f5-11e9-8748-ab1ef01040da.PNG)

**Comment by aschaake** [comment]
Pictures better now?

**Comment by aschaake** [comment]
Anyone have this problem ?

**Comment by aschaake** [comment]
> Your images are not visible, just drag them into this window

**Comment by aschaake** [comment]
Why are there no comments on this case?

**Comment by waltervl** [comment]
Do you still have this issue in current stable? I do not have blinds with stop so cannot test.

**Comment by aschaake** [comment]
Yes. this problem still is present in the current stable.

Now: v2022.1 on RPI 4b

**Comment by gizmocuz** [comment]
What hardware are you using?

I just added a dummy switch, edit the switch, set the type to Blinds + Stop
Pressed open, closed and stop ... when pressing stop it displays:

![image](https://user-images.githubusercontent.com/2265299/153874616-e0002ed8-9411-4a9c-9a73-0563fa6350c0.png)

**Comment by aschaake** [comment]
As mentioned I use a rp4b.

The blinds are connected with a rfxcom 433mhz connection.

**Comment by gizmocuz** [comment]
That is very nice..... must be something different in there... I will try to debug this

**Comment by aschaake** [comment]
When I can help please notify me.

**Comment by gizmocuz** [comment]
Found it! A new beta is building (14189) , could take 30 minutes
