### ISSUE TITLE
Native support for Google Home?

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#3044]
Are there any plans for native support for Google Home in Domoticz?

**Comment by aschaake** [comment]
would be very welcome indeed. Or some more alternatives for controlicz?

**Comment by gizmocuz** [comment]
Have you taken a look at https://sinric.com ? Maybe that could work ?
Sure i am happy if someone could build native support for it (and for Amazon Echo)

**Comment by TheReptile** [comment]
You could try this plugin: https://github.com/giejay/domoticz-gbridge-plugin

**Comment by JurikRistjouw** [comment]
I agree with @TheReptile. I've been using this plugin a few months now. It works as a nice alternative to what is mentioned. You can use that for free if you are willing to host your own. Having said that, I also would like to see native support.

**Comment by ressof** [comment]
@TheReptile can you both control lights and get temperature from sensors with this plugin?

**Comment by TheReptile** [comment]
@ressof Yes, I can control the lights "Turn on the kitchen light" and set the temperature "Set the thermostat to 20" There seems to be some bug with querying the temperature.

**Comment by eldigo** [comment]
This plugin also works nicely
https://github.com/DewGew/Domoticz-Google-Assistant

**Comment by waltervl** [comment]
Can be closed as plugins are created.

**Comment by SargonofAssyria** [comment]
Strange. The first is an external bridge ( https://gbridge.kappelt.net/ ) of which the url does not exists anymore. Last updates 3 years ago. The DewGew is not a plugin, but works nicely with Domoticz, but still not native.

**Comment by rrozema** [comment]
Given, it's not native Domoticz, but as a years long user I can truely recommend Nick Madge's Controlicz (https://controlicz.com/). He provides a professional-like service at a really reasonable price of 20 brittish pounds per year. Controlicz has support for pretty most any device type you can control from Google Assistant. If something new is added/changed by Google Nick is most of the times quick to pick it up into Controlicz too. Plus, Nick is usually very fast to respond and eager to help if you run into any problems.
My Domoticz setup wouldn't have had the same level of acceptance by my family without Controlicz!

**Comment by JurgenLB** [comment]
With homebridge there is a plug-in for Google Home. So you can use that
