### ISSUE TITLE
Toon api domoticz

### ISSUE THREAD

**Issue by rene2716** [domoticz/domoticz#3046]
Since eneco shut down their old access point domoticz needs to work with the new api. Can someone look into this? 

### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version.
* Always state your version when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by Josje92** [comment]
Same problem here. Saw something about special characters causing trouble last December. Tried that out too.

My logs:

```
2019-03-02 20:30:06.947 Status: ToonThermostat: Worker started...
2019-03-02 20:30:13.679 Error: ToonThermostat: Invalid data received, or invalid username/password!
```

**Comment by darkrain-nl** [comment]
You can have a look at: https://github.com/JohnvandeVrugt/toonapilib4domoticz 
That is a python plugin using the Toon API.
Not perfect yet, but it is working fine for me a few weeks already.

**Comment by Josje92** [comment]
> You can have a look at: https://github.com/JohnvandeVrugt/toonapilib4domoticz
> That is a python plugin using the Toon API.
> Not perfect yet, but it is working fine for me a few weeks already.

Looks promising what you guys built, I've setup a bit, but saw that I needed a developer API key. Especially because of the fact that I know how incredibly easy the regular Domoticz plugin used to work, I'm a bit too lazy to set this all up.

**Comment by Wolfensteijn** [comment]
> > You can have a look at: https://github.com/JohnvandeVrugt/toonapilib4domoticz
> > That is a python plugin using the Toon API.
> > Not perfect yet, but it is working fine for me a few weeks already.
> 
> Looks promising what you guys built, I've setup a bit, but saw that I needed a developer API key. Especially because of the fact that I know how incredibly easy the regular Domoticz plugin used to work, I'm a bit too lazy to set this all up.

Well, Eneco/Quby have shut down the old way of working. So the only way to get any connection is using the current API endpoint. And for this an account is needed.

Luckily, the creation of an account and the API codes is also real easy. Just set it up and got it working with 5 minutes of just following the documentation.

If you don't want to set up a developers account, there are some other things you can do. Connect your domoticz install directly to the P1 port on your meter, and place an Opentherm Gateway between the Toon and your boiler. But that requires a lot more work ;)

**Comment by Hiu80** [comment]
> 
> Luckily, the creation of an account and the API codes is also real easy. Just set it up and got it working with 5 minutes of just following the documentation.
>

Hello, i am struggeling to understand how to create this API codes. I have read the documentation but i am still not able to get this working. I think i am missing something, or my basic understanding of how this is supposed to work is not correct. Can you please help me by providing some steps how you have authorized your domoticz installation and got the API codes?

Many thanks!

**Comment by Wolfensteijn** [comment]
First step is to create an account on developer.toon.eu

When you have created and activated your account, hoover your mouse over your account name in the upper right corner and click 'My Apps'

In the My Apps screen, click on 'Add a new App'
Fill in the information. What you fill in does not really matter, just make it something you can easily recognize. The Callback URL can be a bogus domain name, or a personal website. If you are going to use better authentication for some reason, read up on Oauth and how Callback URL's should be used. But for use in Domoticz, this doesn't matter.
Now you have created your App. Copy the Consumer Key and Consumer Secret to your ToonApiLib settings in Domoticz.
 
For installation of this plugin, follow the documentation of the plugin.
For Raspberry Pi's and generic Linux installs this is: https://github.com/JohnvandeVrugt/toonapilib4domoticz/blob/master/INSTALL_PI.md And it basicly is just downloading the toonapilib4domoticz files into the plugin folder of your Domoticz install.

Hope this helps you a bit.

Kind regards,
Wolf Schouten

**Comment by gizmocuz** [comment]
No response, i guess it is solved then

**Comment by Pandabeer40** [comment]
Looks like the new Beta of Domoticz will not work together with ToonApiLib - I get some difficult errors in de log - after removing the dir of toonapilib4domoticz everythis is working again - please can you take a look how to solve - I posted also on the forum of Domoticz under bugs - but still no answer

Domoticz(pid:1323, tid:1329('PluginMgr')) received fatal signal 11 (Segmentation fault)
2019-09-11 20:49:56.470 Error: siginfo address=0x52b, address=(nil)

**Comment by Wolfensteijn** [comment]
I can't even get the plugin to work anymore, so way of troubleshooting that issues.

Also, I have sort of given up on using the Toon API, and I am using an OpenTherm Gateway (fun little project) for information about the thermostat and boiler. And I am using a Raspberry Pi Zero wifi with P1 cable to get information about my power and gas usage.

So no need anymore to communicate with Toon using the API. Which is the reason I hadn't noticed that it broke down :D

**Comment by darkrain-nl** [comment]
> 
> 
> Looks like the new Beta of Domoticz will not work together with ToonApiLib - I get some difficult errors in de log - after removing the dir of toonapilib4domoticz everythis is working again - please can you take a look how to solve - I posted also on the forum of Domoticz under bugs - but still no answer
> 
> Domoticz(pid:1323, tid:1329('PluginMgr')) received fatal signal 11 (Segmentation fault)
> 2019-09-11 20:49:56.470 Error: siginfo address=0x52b, address=(nil)

This has to do with Raspbian Buster I guess, do you use this version?

**Comment by Wolfensteijn** [comment]
No, I am running Ubuntu 18.04 as a VM on top of Vmware ESXi.

**Comment by darkrain-nl** [comment]
yes but I was replying to @Pandabeer40 ;-)

**Comment by Pandabeer40** [comment]
@darkrain-nl. I had alsof the problem on a Raspberry Pi with Stretch - plugin was working with latest master version of Domoticz, when upgrading to a newer beta version, the problems starting. Now trying to run on a Pi4; same issues but didn't try latest master version. Direct to latest beta... domoticz was killed by plugin toonapilib

Hope somebody can figure out the problem and fix this nice plugin based on the latest api of Toon

Grtz,
Peter
