### ISSUE TITLE
gpio number > 256 exeedes unit code for LIGHTING2 packets

### ISSUE THREAD

**Issue by PeterHolik** [domoticz/domoticz#3047]
On my system i have following gpio pin numbering:

# ls -la /sys/class/gpio/

drwxr-xr-x  2 root root    0 Feb 13 16:18 .
drwxr-xr-x 77 root root    0 Feb 12 11:53 ..
--w-------  1 root root 4096 Feb 10 19:28 export
lrwxrwxrwx  1 root root    0 Feb 10 19:27 gpio444 -> ../../devices/pci0000:00/0000:00:02.0/0000:03:00.0/usb2/2-4/2-4.1/2-4.1:1.0/gpiochip2/gpio/gpio444
lrwxrwxrwx  1 root root    0 Feb 10 19:15 gpiochip444 -> ../../devices/pci0000:00/0000:00:02.0/0000:03:00.0/usb2/2-4/2-4.1/2-4.1:1.0/gpio/gpiochip444
lrwxrwxrwx  1 root root    0 Feb 10 19:15 gpiochip448 -> ../../devices/pci0000:00/0000:00:02.0/0000:03:00.0/usb2/2-4/2-4.2/2-4.2:1.0/gpio/gpiochip448
lrwxrwxrwx  1 root root    0 Feb 10 19:15 gpiochip452 -> ../../devices/pci0000:00/0000:00:1f.0/gpio_ich.0.auto/gpio/gpiochip452
--w-------  1 root root 4096 Feb 13 16:18 unexport

SysfsGpio updates to the configured pin where ignored because then pin number is stored as a Byte value in LIGHTING2.unitcode.

My temporary workaround is to change all sql queries in domoticz/hardware/SysfsGpio.cpp from

result = m_sql.safe_query("SELECT nValue,Options FROM DeviceStatus WHERE (HardwareID==%d) AND (Unit==%d)", m_HwdID, m_saved_state[i].pin_number);

to
result = m_sql.safe_query("SELECT nValue,Options FROM DeviceStatus WHERE (HardwareID==%d) AND (Unit==%d)", m_HwdID, (unsigned char)m_saved_state[i].pin_number);

This is not a really good solution but helps me at the moment using domoticz.

**Comment by gizmocuz** [comment]
Those are very high numbers.. any idea why this is so on your system ?
I think the better solution (for now) is to decalrfe 'pin_number' as uint8_t in the structure

**Comment by PeterHolik** [comment]
The numbers are assigned by the system.
I use a ft232R using cbus-pin's on kernel 4.20 as gpio's.

**Comment by PeterHolik** [comment]
Declare pin_number as uint8_t is wrong because to access the pin a path is build:

snprintf(path, GPIO_MAX_PATH, "%s%d/value", GPIO_PATH, m_saved_state[i].pin_number);

**Comment by gizmocuz** [comment]
Thats right... hmmm then for database specific issues (unit_code) you need indeed m_saved_state[i].pin_number&0xFF

**Comment by PeterHolik** [comment]
Do you fix this issue?

**Comment by gizmocuz** [comment]
I probably explained above how to solve it, and you have to try it, if it works, please create a PR
