### ISSUE TITLE
MQTT/CayenneLPP plugin issue

### ISSUE THREAD

**Issue by jeroenkl** [domoticz/domoticz#3050]
Hi Gizmocuz,

The MQTT cayenne wrapper is not working with GPS.
Using the buildin plugin: The Things Network (MQTT/CayenneLPP) with LAN interface
Latest beta, currently: 4.10430

 2019-02-10 19:36:50.538 (MQTT client gateway TTN) Temp (ttgo_beam_ttnmapper) 
 2019-02-10 19:36:50.541 (MQTT client gateway TTN) General/Voltage (ttgo_beam_ttnmapper) 
 2019-02-10 19:36:50.531 Status: TTN_MQTT: GPS not implemented yet! 

Looks like it is not implemented yet or is it a bug?

Best regards,

Jeroen

**Comment by gizmocuz** [comment]
Hi Jeroen,

Yes, this is not implemented yet (as i do not have a GPS node)

But i also do not think we have any sensors for it... (we do have a 'clock' sensor)

If you would like me to implement the clock sensor, or a text sensor representing the GPS coordinates, let me know.
Please send me a PM on the forum referring this issue

(If possible the JSON output of the MQTT message, or with some credentials)

**Comment by jeroenkl** [comment]
Great, PM will follow

**Comment by jeroenkl** [comment]
Hi Gizmocuz,
Required information is provided via the Domoticz forum as requested. Appreciated in advance.

rgds, Jeroen

**Comment by jeroenkl** [comment]
Hi Gizmocuz,
Did you find the required information via the Domoticz forum as requested?

rgds, Jeroen

**Comment by gizmocuz** [comment]
Yes thanks but time got in my way... Will look at this tomorrow

**Comment by jeroenkl** [comment]
Ok, great!

**Comment by gizmocuz** [comment]
@jeroenkl , i can implement this as a text sensor... what are you planing to do with it ?
The issue with the text sensor is that it will also keep a log of changes (like the light/switch log),
is that a problem ?
If you expect lots of updates, then maybe putting it in a user variable is an option ?
(Depends on you usage)

Do you also support LPP_UNIXTIME ?

**Comment by jeroenkl** [comment]
Hi Gizmocuz,

Do you receive the data from my GPS sensor?
I want to use the data in domoticz, to be able to see where my GPS is and with a geofence trigger.
There will be a lot of updates, like every change of movement. 

I'll check LPP_UNIXTIME, will dig into it this weekend. Maybe GPS time can update it.

thanks.

Jeroen

**Comment by gizmocuz** [comment]
@jeroenkl , okey, If i put the GPS coordinates in a uservariable like "latitude<dot comma>longitude<dot comma>altitude" will that work for you ?

**Comment by Ree26er** [comment]
Can we talk in a chat open chat link ? Because I don’t even kno If I’m
talking to someone right know

**Comment by jeroenkl** [comment]
Hi Gizmocuz, 

Yes great!

**Comment by gizmocuz** [comment]
@jeroenkl , i have not verified it, but it should work in the new beta version (could take another hour before the build is available)

See the code changes at:
https://github.com/domoticz/domoticz/commit/aa011c15ba4f1ef000ef9ff75566eaa3a33da604

@Ree26er , what do you mean ?

**Comment by jeroenkl** [comment]
@gizmocuz, thanks! I'll inform you this afternoon with the results.

Jeroen

**Comment by jeroenkl** [comment]
@gizmocuz, it works thanks!!!

**Comment by jeroenkl** [comment]
@gizmocuz 
Got since some weeks the follwing issue filling the logfiles:
2019-07-24 14:40:29.961 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: /home/pi/domoticz/dzVents/runtime/Utils.lua:26: bad argument #1 to 'gmatch' (string expected, got nil)

Only occurs when my TTN GPS tracker is online sending data to cayenne.

Can you please check?

BR,

Jeroen
