### ISSUE TITLE
Devices / all devices are missing from the selection

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#3052]
Hello, in devices / in the selection is missing all device button.

Now you have to click each one individually, earlier you could select all by button.

<a href="https://www.directupload.net" target="_blank"><img src="https://s15.directupload.net/images/190217/p6ickkuo.jpg" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by pipiche38** [comment]
In addition if you add a device , there is no way of reloading the page. For instance if you click all devices there is no refresh as it was prior the all changes done on the device list

Envoyé de mon iPhone

**Comment by salopette** [comment]
I mean if you want to delete multiple devices, you have to select each one individually.
Previously you could by a click in the red marked field.
But now nothing is in the field!

**Comment by pipiche38** [comment]
@salopette , you are right, this is indeed true since they have integrated a PR which has rebuild the all Device List, but they are quiet some regression from the previous version:

- No all select
- No Refresh

**Comment by salopette** [comment]
is it still being repaired?

**Comment by stas-demydiuk** [comment]
@pipiche38 in what cases do you need to manually refresh the list? Does just page refresh not work for you for some reason?

**Comment by stas-demydiuk** [comment]
@salopette what is the usecase to delete multiple devices at once?

**Comment by salopette** [comment]
I mean this function is in the picture in the circle:

Man was able to select and delete all devices earlier, now you have to click each one individually, if you want to delete!

<a href="https://www.directupload.net" target="_blank"><img src="https://s15.directupload.net/images/190220/w7mqcuvd.jpg" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by stas-demydiuk** [comment]
Yes, this was done partially on purpose as deleting all available devices doesn't look like as operation you will do too often, doesn't it?

**Comment by salopette** [comment]
Ок, я думал это ошибка.

**Comment by gizmocuz** [comment]
@stas-demydiuk , please place it back... i use it also quite often
i make a filter (in the search box...) and delete all devices that affects the filter

**Comment by devrosx** [comment]
also noticed that last seen toggle switch in Devices tab isn't working on last build...

**Comment by pipiche38** [comment]
Looks like when you select, it select ALL Devices in the table, and NOT only the visible device on the screen!!!!

It must select all devices on the screen !

**Comment by gizmocuz** [comment]
@stas-demydiuk , maybe you can bring back the old functionality and let the table handle this ?

**Comment by pipiche38** [comment]
I think this one is back, at least on 10547 so the issue can be close

**Comment by RicardP** [comment]
@stas-demydiuk @gizmocuz In version 4.10619 The select ALL checkbox still selects the whole table, not only the visible once! I just wiped my complete device list, luckily had the hourly backups.... 

Windows platform
Tested with Firefox.

**Comment by pipiche38** [comment]
This is issue pop-up again, it was fixed and then recently shows up. Very annoying, as I had a similar issue as @RicardP
