### ISSUE TITLE
Electricy counters are not correct (TOTALS)

### ISSUE THREAD

**Issue by SPLeon** [domoticz/domoticz#3053]
Domoticz V 4.10431 on Raspberry Pi

The counters on electricity don't work correctly. I just updated to latest version to check if it's fixed.
Some examples:

**Year overview electricity 2019**

Total Usage: T1: 299.448 kWh, T2: 187.019 kWh, **Total: 323.717 kWh**
Counter: T1: 6516.964 kWh, T2: 3172.473 kWh
Total Return: R1: 54.306 kWh, R2: 108.444 kWh, **Total: 323.717 kWh**

**Overview Electricity Feb 2019**

Total Usage: T1: 105.733 kWh, T2: 54.501 kWh, **Total: 60.031 kWh**
Total Return: R1: 32.747 kWh, R2: 67.456 kWh, **Total: 60.031 kWh**

Totals seems to be incorrect.

**Comment by gizmocuz** [comment]
There will be a new beta version. This should be fixed in https://github.com/domoticz/domoticz/pull/3048

**Comment by gizmocuz** [comment]
Thanks for the feedback!
