### ISSUE TITLE
Influxdb settings should be an Url instead of server/port

### ISSUE THREAD

**Issue by davidlb** [domoticz/domoticz#3056]
As InfluxDb push relies on HTTP API, settings should be an Url instead of server/port, especially useful when using a reverse-proxy in front of Influxdb.

**Comment by gizmocuz** [comment]
Could you post an example what your URL would have to be like ?

If you look at the code (InfluxPush.cpp, line 85), it seems the database variable can be used for this

But it's the first time i hear about this

**Comment by gizmocuz** [comment]
If you use a 'revere-proxy', we could add a new setting 'path' ?

**Comment by davidlb** [comment]
Yes, a new setting "path" would do the job too.
To push data to influxdb, I use this URL: https://domain.com:443/influx-api/write?db=mydb&...

Here is my nginx reverse-proxy entry for influxdb:
    location /influx-api/ {
        proxy_pass http://localhost:8086/;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }

**Comment by gizmocuz** [comment]
In the next beta version you can enter the proxy path:

![image](https://user-images.githubusercontent.com/2265299/53150491-f4421b00-35b0-11e9-88d6-1c9d1253796d.png)

But you could of course have forwarded/used a different port ?

**Comment by davidlb** [comment]
Thanks !
