### ISSUE TITLE
after update Blockly can't trigger groups	

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#3057]
Version: 4.10442
Build Hash: 14a385a6
Compile Date: 2019-02-19 09:25:39
dzVents Version: 2.4.14
Python Version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]

https://www.domoticz.com/forum/viewtopic.php?f=6&t=27063&sid=3a75e3a4468b4d9b53d39402cf9b25ce

**Comment by kovainfo** [comment]
Version: 4.10444
Not just Blockly, LUA scripts also don't work.

Me too (((
all automation stopped working! it's very bad (((

**Comment by gizmocuz** [comment]
Seems _tActionParseResults.iRepeat needed to be 1 by default
Should be fixed in the next beta (should be ready within the hour)

**Comment by loglux** [comment]
Automation has broken after update to 4.10444. That is a catastrophe, my smart house is going mad. 
I use dzVents and toggleSwitch, switchOn and switchOff don't work anymore, making no effect

**Comment by sweetpants** [comment]
I'm on 4.10445 and all still works

**Comment by salopette** [comment]
4.10445 still works!

THX
