### ISSUE TITLE
toggleSwitch() doen'st work after update to beta v4.10444

### ISSUE THREAD

**Issue by loglux** [domoticz/domoticz#3058]
the dzVents command toggleSwitch() doesn't work after update Domoticz to v4.10.444 beta today.

**Comment by loglux** [comment]
switchOff and switchOn don't work as well for every devices

That means that automation is completely broken now

**Comment by Siewert308SW** [comment]
Correct... With normal Lua scripts selector and dummy devices can't switch anymore

**Comment by rwaaren** [comment]
Solved in V4.10445. Please close

**Comment by Siewert308SW** [comment]
Installed it 30min ago and it didn't  solve mine.
Will test again tomorrow.

**Comment by Siewert308SW** [comment]
After some testing V4.10445 did fix my issue where my dummy and selector switches wheren't toggled.

**Comment by gizmocuz** [comment]
Thanks for the feedback !
