### ISSUE TITLE
Bugs in user rights for cameras

### ISSUE THREAD

**Issue by iffen5** [domoticz/domoticz#3059]
I found a issue's in the andriod app. I have already made a bugreport in github domoticz /ANDROID. But the devoplper said that the problem lays in Domiticzserver. Look at https://github.com/domoticz/domoticz-android/issues/495

The bug is that that you have to "Admin" to see cameras in the app. We have about 50 - 70 users in my system and they all have to see alla cameras in the system and also be  able to use all switches.
So all of this users have to haave the right "USER"
We can't allow all to be admins.
**regards Ingemar wararak**

I will post previos answer herer:

****[T-bond](/T-bond) ** commented [on 22 Jan](#issuecomment-456435314)**
I think I get what is the problem.
An user with viewer permission has no access to the cameras' list. (https://host:443/json.htm?type=cameras) gives 403 (forbidden).
But if you attach a camera image to a switch you can query that camera even with viewer permission. (https://host/camsnapshot.jpg?idx=2&count=358?t=1548169366835 )

So I think not showing the cameras in the Android App is the correct solution, so this issue should be closed.

I also understand that you would like to give access to the people with viewer rights to view the cameras, but I think this should be changed on the Domoticz server first, and only reflect these changes in the app after that.

(I also noticed, that you can access cameras with the given link, when it is not attached to a switch, so it maybe can be considered as a security issue and should be fixed also on the Domoticz server, or give users right to access all the cameras)

****[ffen5](/iffen5) ** commented [29 days ago](#issuecomment-456577905)**
Is it the same problem with user "user"?
rgds ingemar

****[T-bond](/T-bond) ** commented [29 days ago](#issuecomment-456612995)**
Yes. If you login with an user account, and try to access then `/json.htm?type=cameras` you will get a 403 on the Domoticz server itself.

**Comment by iffen5** [comment]
Is there someone who can help me? We have a use for Domoticz at my flightclub and we are maybe 50 persons who is going to use it. The only problem now is that cameras doesn't work with user rights "user" or "viewer"

**Comment by gizmocuz** [comment]
It's not a bug, it is how it is implemented...

The reason for this is that the current JSON call also returned private parameters like username/passwords

Made a new JSON call in the code:

https://github.com/domoticz/domoticz/commit/414dfe3d6608dd3587bc145be0ade6bf8321ebd4

/json.htm?type=cameras_user

With this you now get the enabled camera's with IDX and Name

You can use the snapshot JSON function to retrieve the snapshot like before

**Comment by gizmocuz** [comment]
Thanks for the feedback...
