### ISSUE TITLE
Python Events

### ISSUE THREAD

**Issue by gmisuth** [domoticz/domoticz#3061]
Dear Everyone,

I'm trying to import the python module called "requests" to make a setpoint command. I installed the package and is working fine in the python3 shell. The problem is, that in the domoticz web event interface when i try to import "requests" I get a error saying that there is no module named "requests".
I compared the PATH values in my shell and in the web python interface. They differ and I think that is the problem.
Is there any way that I can get this working somehow?
Thank you all!
The two PATH values:
-Python3 shell: ['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/mano/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']
-Domoticz python web interface: ['/home/my_username/domoticz/scripts/python/', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload']

-kishaver

**Comment by pipiche38** [comment]
I suggest that you use the forum for such topic, and if I'm nt mistaken a recent update on the Beta version is addressing that issue!

**Comment by gmisuth** [comment]
Okay, I'll do that thank you for your information.
