### ISSUE TITLE
Synology cross compile problem domoticz-4.10449

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#3063]
#[ 75%] Building CXX object CMakeFiles/domoticz.dir/hardware/ToonThermostat.cpp.o
[ 76%] Building CXX object CMakeFiles/domoticz.dir/hardware/TTNMQTT.cpp.o
/home/dahl/spksrc-master/spk/domoticz_python/work-x86-6.2/domoticz-r10449/hardware/TTNMQTT.cpp: In member function ‘void CTTNMQTT::UpdateUserVariable(const string&, const string&)’:
/home/dahl/spksrc-master/spk/domoticz_python/work-x86-6.2/domoticz-r10449/hardware/TTNMQTT.cpp:336:86: error: cannot pass objects of non-trivially-copyable type ‘const string {aka const class std::basic_string<char>}’ through ‘...’
  result = m_sql.safe_query("SELECT ID FROM UserVariables WHERE (Name=='%q')", varName);
                                                                                      ^
/home/dahl/spksrc-master/spk/domoticz_python/work-x86-6.2/domoticz-r10449/hardware/TTNMQTT.cpp:340:87: error: cannot pass objects of non-trivially-copyable type ‘const string {aka const class std::basic_string<char>}’ through ‘...’
   result = m_sql.safe_query("SELECT ID FROM UserVariables WHERE (Name=='%q')", varName);
                                                                                       ^
/home/dahl/spksrc-master/spk/domoticz_python/work-x86-6.2/domoticz-r10449/hardware/TTNMQTT.cpp:348:125: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string<char>}’ through ‘...’
   m_sql.safe_query("UPDATE UserVariables SET Value='%q', LastUpdate='%q' WHERE (ID==%d)", varValue.c_str(), szLastUpdate, ID);
                                                                                                                             ^
make[5]: *** [CMakeFiles/domoticz.dir/hardware/TTNMQTT.cpp.o] Error 1

**Comment by gizmocuz** [comment]
Right... sorry about that! (Wish this could be changed somehow ...)
