### ISSUE TITLE
Blinds level does not reflect the percentage of level

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#3065]
In Domoticz show fully out even Open Z-Wave control panel says the correct value i.e. 65%

Windows, run as service
Version 4.10411

![1](https://user-images.githubusercontent.com/21274628/53301505-ebbd3f00-3853-11e9-8a6f-ead932dab1e5.JPG)
![2](https://user-images.githubusercontent.com/21274628/53301507-ee1f9900-3853-11e9-84d9-2c32072450e4.JPG)

**Comment by Rowanooijen** [comment]
Also the value doesn't seems to be correct. With all my vibrato shutters with domotica fully closed will be like 75% on domoticz. So the range I can control the blinds are form 0% (fully open) to 75% (fully closed)

**Comment by michahagg** [comment]
Could be fixed by this commit: https://github.com/domoticz/domoticz/commit/b92d81ab4c55d9b226cbb43195c647f1c13fd983
See also this issue: https://github.com/domoticz/domoticz/issues/4289

**Comment by RicardP** [comment]
> 
> 
> Could be fixed by this commit: [b92d81a](https://github.com/domoticz/domoticz/commit/b92d81ab4c55d9b226cbb43195c647f1c13fd983)
> See also this issue: #4289

@michahagg Thanks for info, I am running latest beta now so fingers-X :)

**Comment by cndian** [comment]
Where do I need to put the commit?

**Comment by rwaaren** [comment]
> Where do I need to put the commit?

It is already merged in recent Beta (build 12282)
See [This wiki page](https://www.domoticz.com/wiki/Domoticz_versions_-_Commits) for all recent commits

**Comment by rwaaren** [comment]
> Where do I need to put the commit?

It is already merged in recent Beta (build 12282)
See [This wiki page](https://www.domoticz.com/wiki/Domoticz_versions_-_Commits) for all recent commits

**Comment by cndian** [comment]
Thanks! Is it not possible to only add this specific commit? Because I want to continue run the stable 2020.2 version.

**Comment by rwaaren** [comment]
> Thanks! Is it not possible to only add this specific commit? Because I want to continue run the stable 2020.2 version.

No

**Comment by cndian** [comment]
When I get the beta does this also resolve the problem for the status update of the fgr223? When i slide the slider to for example 25% the blinds go down but the slider stays on open.

**Comment by rwaaren** [comment]
Please use the forum.
