### ISSUE TITLE
Additional Widget for 5 buttons remote control

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#3068]
In the context of the Zigate plugin, we ate now support the IKEA TRADFRI Remote command.
https://www.ikea.com/us/en/catalog/products/20303317/

As you can see on the picture there are 5 Buttons

- Centrale button ( Toggle On/off)
- Top/down buttons - dimmer +/-
- Left/right buttons - dimmer +/-

Would it be possible to have an additonal Switch in Domoticz able to manage 2 Level Control as well as a Toggle ?

**Comment by gizmocuz** [comment]
Is it not already working correctly ?

**Comment by pipiche38** [comment]
Sorry, I might have missed something, but I don't think that there is in Domoticz a SwitchType and the corresponding Widget which show 2 Dimmers in one single widget !

**Comment by gizmocuz** [comment]
Can't you use a 'selector switch' for this (and maybe some additional scripting)

**Comment by pipiche38** [comment]
So do I, I was just thinking that if some designer has a good idea on how to represent a 2 Level Control Widget with an On/off, this would be great.
As when you use the Selector Switch, you loose the Level part ...

**Comment by gizmocuz** [comment]
I don't see why, as the remote has 5 buttons, you could replicate them with a selector switch
