### ISSUE TITLE
Issue with energy calculation

### ISSUE THREAD

**Issue by BmdOnline** [domoticz/domoticz#3069]
Hi,
I have an issue with energy calculation with Domoticz.
I'm using Domoticz v4.10426.

My configuration :
I have created a current sensor (SCT013 sensor), sending measures to Domoticz using MySensors.
Data is sent each minute.
It works correctly, and sends current (A), power (W) and energy (kWh).
Reported values for current and power are correct, but energy is underestimated !

I have logged values sent by MySensors, computed them in a worksheet.

Here is my analysis :
Domoticz samples every 5 minutes, so we have 12 values per hour.
It seems that Domoticz only uses 11 of these values for the hourly calculation.
From hh:00 to hh:55, or from hh:05 to next hh:00

For example :
![sample for issue](https://user-images.githubusercontent.com/5605245/53347127-c0e8ee80-3918-11e9-9e23-1c5b1b605b6e.png)

Maybe the problem is elsewhere, but what is certain is that the data transmitted is correct, but the energy calculation is too low.

**Comment by BmdOnline** [comment]
Some investigations later...
Hourly calculation is wrong, but daily calculation is right.
Measures are stored correctly in database.

It is only the difference between the first and last hourly index that is incorrectly calculated.
At least that's what I conclude.

**Comment by gizmocuz** [comment]
As Domoticz is using the meter values for Daily calculations there can be no issue...

But for the actual day calculation, do you miss the consumption of the last hour ?

Are you talking about the 'widget' on the dashboard/utility tab , or the graph log ?

It should take the counter value of the beginning of the day (meter table... not meter_calendar table), and the last value reported in the devicetable table

WebServerp.cpp (for example) line 9567

Assuming the meter is of the same type, in the graph it is calculated at line 15839

**Comment by BmdOnline** [comment]
I'm talking about "usage last 24h" graph :
- Line chart (5 min samples) is correct.
- Hourly bar chart seems to miss some values in calculation.

If I'm right (I don't find where it is calculated), it calculates difference between first and last index from each hour.
It must calculate difference between first index from each hour and first index from next hour.

Stored values are correct since daily and monthly charts are right.

Edit : it seems to be calculated around line 13850.

**Comment by BmdOnline** [comment]
Yes, it has to do with lines 13900 to 13957.

You are calculating :
`long long ulTotalValue = ulLastValue - ulFirstValue;`
And doing it for each hour, with this grouping : `actDateTimeHour = sd[2].substr(0, 13);`

In other words (and for example, between 07:00 and 08:00) :
`ulFirstValue` is index from 07:00
`ulLastValue` is index from 07:55
`ulTotalValue` is the difference from 07:00 to 07:55

You're skipping consumption from 07:55 to 08:00.

Right calculation has to be something like
`ulFirstValue` : index from 07:00
`ulLastValue` : index from 08:00
`ulTotalValue` : the difference from 07:00 to 08:00

and so on...

I'm not comfortable enough to update the code, I'm afraid it will change the structure of this loop too much.

**Comment by gizmocuz** [comment]
@BmdOnline , But you are able to compile ?
Maybe moving the whole 'if' block to the bottom after:

```
if (!bHaveFirstRealValue)
{
	bHaveFirstRealValue = true;
	ulFirstRealValue = ulLastValue;
}
```

then the if block:

```
if (actDateTimeHour != LastDateTime || ((method == 1) && (itt + 1 == result.end())))
...
```

Feel free to expiriment

**Comment by BmdOnline** [comment]
Actual code is counting from hh:00 to hh:55.
Applying your suggestion, it counts from hh:05 to next hh:00 (and miss data from hh:00 to hh:05).

I will experiment... :wink:

**Comment by BmdOnline** [comment]
@gizmocuz 

In fact, we need to add `ulLastValue` one last time for each hour :
For now, when `actDateTimeHour != LastDateTime` occurs we miss last `ulLastValue`

I've moved `uLastValue` assignment before the whole `if` block :
```
long long actValue = std::strtoll(sd[0].c_str(), nullptr, 10);

if (actValue >= ulLastValue)
    ulLastValue = actValue;
```
Is moved between
```
//bars / hour
std::string actDateTimeHour = sd[2].substr(0, 13);
```
And
```
if (actDateTimeHour != LastDateTime || ((method == 1) && (itt + 1 == result.end())))
```

I have checked and each hourly consumption is correct now.
I don't know if it generates sides effects !

**Comment by gizmocuz** [comment]
Okey, if possible please do some testing and create a pull request, or post the whole function part here (only the 20 or so lines)

**Comment by BmdOnline** [comment]
OK. I'm going to do that. 
I also have a doubt about the units (Wh vs kWh) between the different graphs (day, month...).
