### ISSUE TITLE
Devices does not trigger MQTT group status

### ISSUE THREAD

**Issue by jcwlim** [domoticz/domoticz#3070]
After many checked, found that when I trigger a group Domoticz will publish group + devices in that group MQTT message which is wonderful.
However, when I trigger the devices itself, it does not publish group MQTT message.
Example: Light a and light b are in group c. When I switch off group c, Domoticz will publish group c status to off, Light a and light b status to 0.
But if now I switch on light a, Domoticz will publish mqtt message for light a nvalue to 1 and suppose it should publish group c status to "MIXED" as well. << this part is missing...

**Comment by bikeymouse** [comment]
I can add that there are are more issues with the group and MQTT.

Normally if a scene or group is switched on or off, this is published with the MQTT Client Gateway to domoticz/out

However, if I change this in the hardware settings to publish to domoticz/idx or any of the other options, I no longer get any updates on status changes off the scene's/groups on MQTT, while for all other devices this is still done as expected.

**Comment by gizmocuz** [comment]
@lily148 , when you created this issue, there was a 'form' that you needed to fill in, or at least answer some of the questions
I do think you could be right here... I see what can be done about this.
Still please edit your first issue message and provide the missing details

**Comment by waltervl** [comment]
No feedback so closed.
