### ISSUE TITLE
User variable update crash

### ISSUE THREAD

**Issue by gmisuth** [domoticz/domoticz#3072]
Dear everyone,

I was working with user variables and the first thing I noticed is that I cannot add a new user variable, always get a red ERROR message. This is okay, I can do a workaround with the json call.
The other thing is that whenever I try to update a user variable through python events (using the json call and urllib for that) domoticz crashes and i had to restart it from terminal.
Maybe I'm doing something wrong but I have no clue what is the problem. The update works fine if I do it from a json call from my browser. I had the stable version of domoticz, and now I reinstalled it and compiled it for myself in the hope of getting it working again.
I hope someone can help me.
Thank you all!

Sincerely,
-kishaver

**Comment by gizmocuz** [comment]
@kishaver , is it possible to post here the JSON call to create the variable, and the call to update the variable ?

**Comment by gizmocuz** [comment]
Also try beta 10531+

**Comment by gmisuth** [comment]
Dear @gizmocuz ,

thank you for your reply I really appreciate that.

So the two mentioned json calls are:
http://127.0.0.1/json.htm?type=command&param=adduservariable&vname=myvariable&vtype=0&vvalue=0
The variable is a integer and the default value is 0.
http://127.0.0.1/json.htm?type=command&param=updateuservariable&vname=myvariable&vtype=0&vvalue=1
When I call both of them domoticz crashes. Well I'm not sure if it crashes but I cant access through the web interface.
Also I would like to mention that it only happens to user variables. I use setpoint commands and they work fine.
The other thing is that to open the url I use urllib, to open the url the commands is:
urllib.request.open("my_url")

I'm currently on version 4.10525, is there another newer version? I have to downlaod it from here, GitHub?

Thank you for your help again.

-kishaver

**Comment by gmisuth** [comment]
I found the new version, will try it and the post an update if it's working or not.
UPDATE:
Okay so I updated domoticz to version 10531 but the problem still occurs.
I get this Error message on the log:
 2019-02-27 13:03:06.309 Error: WebServer:80 thread seems to have ended unexpectedly (last update 68.000000 seconds ago)
2019-02-27 13:03:20.312 Error: WebServer:80 thread seems to have ended unexpectedly (last update 82.000000 seconds ago)
2019-02-27 13:03:34.315 Error: WebServer:80 thread seems to have ended unexpectedly (last update 96.000000 seconds ago)
2019-02-27 13:03:48.318 Error: WebServer:80 thread seems to have ended unexpectedly (last update 110.000000 seconds ago)
2019-02-27 13:04:02.321 Error: WebServer:80 thread seems to have ended unexpectedly (last update 124.000000 seconds ago)
2019-02-27 13:04:16.324 Error: WebServer:80 thread seems to have ended unexpectedly (last update 138.000000 seconds ago) 

I noticed, that the user variable changes at the time when it has to change, just the webserver crashes. After a restart I can see that the user variable changed to the proper value.

**Comment by FredWst** [comment]
Hi,

I got the same trouble on string type, change to integer working. 
and of course adapt my script.

Fred

**Comment by gmisuth** [comment]
@FredWst I'm not sure that I get what you are trying to say. Can I somehow make this working?

**Comment by FredWst** [comment]
> @FredWst I'm not sure that I get what you are trying to say. Can I somehow make this working?

I'm using Dzevents script and using user variables declared as string.
I got error when writing to those variables since a few release. ( something related to date ??? report by domoticz)
So I change my script to use integer variable and no more error.

Fred

**Comment by gizmocuz** [comment]
@gmisuth, I am unable to crash domoticz with the two json calls with the latest beta, is this still the case?

**Comment by gmisuth** [comment]
@gizmocuz 
Thank you for your response.
Well I updated to the latest and now it's not crashing, but the user variable is unchanged.
`urllib.request.urlopen('http://127.0.0.1/json.htm?type=command&param=updateuservariable&vname=heatingprog&vtype=0&vvalue=1')`
This is the JSON call I chaked the parameters of it twice so I'm sure it's okay.
The urllib function call works fine, since before this JSON command the code changes a Thermostat with a SetPoint command.

**Comment by gizmocuz** [comment]
@gmisuth , is your valuetype of type 0 ? An integer ? (vtype=0) if it is a string you need to use vtype=2

**Comment by gmisuth** [comment]
@gizmocuz , Yep, it's a integer and the name is correct too.
I'ts strange, because it crashed again at that call. After I need to restart domoticz and the uservariable is updated by the JSON call. I'm on the latest beta version.

**Comment by gizmocuz** [comment]
try disabling the eventsystem in the settings and try again

**Comment by gmisuth** [comment]
I'm not sure if I get what you are saying, but I disabled the eventsystem in the settings (Others tab). Then obviously none of my events would be run. If I switch it back I still get the crash.

**Comment by gizmocuz** [comment]
could you disable it, and enter the url in the browser to see if that gets the variable updated

**Comment by gmisuth** [comment]
Yep, I get a 'OK' response and the variable gets updated without crash.

**Comment by gizmocuz** [comment]
So there is an issue with your script.. disable all scripts, then enable the eventsystem, make one simple script that updates the uservariable only, continue from there
