### ISSUE TITLE
Question: Anna plugin rewrite to Plugwise heating system  (Rip or add)

### ISSUE THREAD

**Issue by p-hagen** [domoticz/domoticz#3073]
Hey Guys,

After I looked at the Plugwise Anna it became obvious it could support most of the other Plugwise systems with a rewrite.
The code im now running at home  now supports the Plugwise family, Anna , Adam, tom, Lisa   and can support the other devices in the plugwise family  just as easy.
It has changed from a single thermostat to  supporting the zone heating system.
It provides the same functionality as the old, but ID's and names etc  have changed to match the new system better
Do I replace the old Anna plugin, or can we add  this one  separately until  it is fully stable ?

**Comment by gizmocuz** [comment]
@p-hagen , if your code is better then the current one we have in domoticz, please create a pull request with the changes

**Comment by p-hagen** [comment]
I'll run  some tests... Then do a PR... thanks for the advice
