### ISSUE TITLE
NAS-WR01ZE (type=0200)

### ISSUE THREAD

**Issue by Beddie** [domoticz/domoticz#3076]
Using the latest domoticz beta version the 
NAS-WR01ZE device is being recognized as a unknown device, type=0200. This device is not working correctly, strange KWh readings and parameters which can not be updated. Switching power On/Off does work.
A requested manufacturer manual has been posted on:
https://community.smartthings.com/t/release-neo-coolcam-power-plug/144274/62

**Comment by gizmocuz** [comment]
Is there a configuration for in the openzwave repository for this device? Of not please go there first

**Comment by Beddie** [comment]
Thank you, I just committed 2 changes in the openzwave repository:
1- A new configuration file in directory "Config/shenzen_neo" called "nas-wr01ze.xml"
2- Updated "manufacturer_specific.xml" and made a pull request.

**Comment by Beddie** [comment]
The openzwave masterbranch has been updated with the device configuration. Should i create a pull request?

**Comment by gizmocuz** [comment]
I updated the configuration files in domoticz, and they will be available in the new beta shortly
Thanks for reporting
