### ISSUE TITLE
Temperature sensor graph log

### ISSUE THREAD

**Issue by FredWst** [domoticz/domoticz#3078]
Hello,

Since many months graph not showing.
The issue is "ORDER BY Date ASC" in SQL request need to remove it.

line 13260 file main/WebServer.cpp

root["title"] = "Graph " + sensor + " " + srange;
not  working
result = m_sql.safe_query("SELECT Temperature, Chill, Humidity, Barometer, Date, SetPoint FROM %s WHERE (DeviceRowID==%" PRIu64 ") ORDER BY Date ASC", dbasetable.c_str(), idx);

working
result = m_sql.safe_query("SELECT Temperature, Chill, Humidity, Barometer, Date, SetPoint FROM %s WHERE (DeviceRowID==%" PRIu64 ")", dbasetable.c_str(), idx);

Rev V4.10531 running on MacOs Mojave.

Fred

**Comment by gizmocuz** [comment]
Hi Fred,

Thank you for taking time to solve this.

Could you try changing it to:

ORDER BY [Date] ASC

If that still does not work, could you open the database in a editor (Like SQLite Expert Personal Edition), and manually perform this query ?

Edit:
Hmm when searching for 'ORDER BY Date' in the code, it returns 72 results, so i do not think this could be the real problem...
Could you try with a Editor ?
Maybe you have a invalid date somewhere in the log table ?

**Comment by FredWst** [comment]
Hi,

I try order by [date] ASC -> same result doesn't work.

Query result with DBBrowser for sqlite

SELECT DeviceRowID, Temperature,Chill, Humidity,Barometer,DewPoint,Setpoint,Date FROM Temperature  WHERE (DeviceRowID=13)  order by date ASC 
-- Result: database disk image is malformed

SELECT DeviceRowID, Temperature,Chill, Humidity,Barometer,DewPoint,Setpoint,Date FROM Temperature  WHERE (DeviceRowID=13)
-- Result: 572 rows returned in 176ms
13 | 22.3 | 0.0 | 54 | 0 | 12.54 | 0.0 | 2019-03-03 13:05:00
13 | 22.3 | 0.0 | 54 | 0 | 12.54 | 0.0 | 2019-03-03 13:10:00
13 | 22.3 | 0.0 | 54 | 0 | 12.54 | 0.0 | 2019-03-03 13:15:01
13 | 22.3 | 0.0 | 54 | 0 | 12.54 | 0.0 | 2019-03-03 13:20:00


SELECT DeviceRowID, Temperature,Chill, Humidity,Barometer,DewPoint,Setpoint,Date FROM Temperature  WHERE (DeviceRowID=13)  order by date DESC
-- Result: 572 rows returned in 182ms
13 | 20.8 | 0.0 | 51 | 0 | 10.29 | 0.0 | 2019-03-05 13:05:00
13 | 20.8 | 0.0 | 51 | 0 | 10.29 | 0.0 | 2019-03-05 13:00:01
13 | 20.7 | 0.0 | 51 | 0 | 10.2 | 0.0 | 2019-03-05 12:55:00
13 | 20.7 | 0.0 | 51 | 0 | 10.2 | 0.0 | 2019-03-05 12:50:00


In this table I've also a Dummy Setpoint with id = 16
I don't see anything wrong in date

SELECT DeviceRowID, Temperature,Chill, Humidity,Barometer,DewPoint,Setpoint,Date FROM Temperature  order by date ASC 
-- Result: 886 rows returned in 266ms

It means that "where DeviceRowID=13" directive and "order by date ASC" -> is a bad why ? :(

Fred

**Comment by FredWst** [comment]
Hi,

My db was corrupt !
I follow this to clean it.
https://sqliteviewer.com/blog/database-disk-image-malformed/

**Method to Rectify SQLite Database Disk Image is Malformed
Now, to prevent the corruption loss and to get the data back in healthy state, it is mandatory to take the backup. A recent backup will always help you to restore the database in case of emergency. Moreover, to repair the damaged or unhealthy SQLite database, hyou can follows these steps as mentioned below:

Firstly, open the database Browser for SQLite
In the next step, run database check command. For this, hit on the tab of Execute SQL
Now, you need to type in PRAGMA integrity check & hit on play. If the SQLite database is damaged, then the same error will appear. However, if the SQLite have no such issue then you will see “Query executed successfully: PRAGMA integrity_check (tool 0ms).”
You can even export the database into SQL. For this, you need to click on File and then on Export>>Database to SQL file…
Then, choose objects you wish to migrate on the dialog box of Export SQL… Apart from this, define some other options too.
After this, hit on OK button to begin the process of export
As soon as the database is moved successfully, import it back to SQLite browser. For this perform these few simple clicks: Click on File>>Import>>Database from SQL file…**

I let you closed this none issue. :)

Fred

**Comment by FredWst** [comment]
I let you closed after have read
