### ISSUE TITLE
Small cosmetic changes

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#308]
Hello
I found bug to small changes looks better. Text on Notification  "If enabled, it will bypass the Notification interval specified in the Settings page" should be set about checkbox , not under. And i think should be consist in (): (If enabled, it will bypass the Notification interval specified in the Settings page) because it is tooltip. Looks on my screen i moved it about checkbox but also please add ().
![1](https://cloud.githubusercontent.com/assets/4134018/12221230/f6ea436e-b791-11e5-83ba-25ac594ac8b0.jpg)

**Comment by gizmocuz** [comment]
fixed in upcoming commit

**Comment by ghost** [comment]
Thanks
