### ISSUE TITLE
-21474836.480 kWh value

### ISSUE THREAD

**Issue by Beddie** [domoticz/domoticz#3081]
When using the latest beta version the NAS-WR01ZE device kWh readings are not correct, see image below:

![image](https://user-images.githubusercontent.com/11497137/53582868-a87b0d00-3b80-11e9-8e18-63163d454b27.png)

After device inclusion:
kWh = 0.000 kWh 
After some (undefined) time (the same result on 4 different devices):
kWh = -21474836.480 kWh

**Comment by RicardP** [comment]
Hi,
I guess it is a Z-Wave node? If so I believe it is a OZW issue, check if the node shows the same value in ozwcpl? If same corrupt value is there you should report this to https://github.com/OpenZWave/open-zwave/issues

**Comment by Beddie** [comment]
Thank you, it does show the same value on ozwcpl. I will report this to openzwave issues
