### ISSUE TITLE
WIth the new List of Devices on beta there is no device list refresh

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#3084]
Beta 4.10531

Since the new Device List layout (which is great), there is no refresh of such list, when going from NOt Used, to Used or to All of Devices.
It was really convenient before, when having new devices created by a Python Framework plugin !

So I think when moving from one tab, to the other, or when simply re-asking Hardware-Devices (even if we are on such screen) a full refresh of the Device List is a needed

**Comment by gizmocuz** [comment]
I agree, that was the same behavior as before
@stas-demydiuk , is this something to add ?

**Comment by pipiche38** [comment]
agree. I think the Refresh button is a great enhacement
