### ISSUE TITLE
Webserver inaccessable when sending commands too quickly after eachother

### ISSUE THREAD

**Issue by DutchHans** [domoticz/domoticz#3085]
I have noticed that sending commands too quickly after eachother results in an inaccessable webserver (on a Pi, don't know if other platforms are also involved) Fing gives no webser ports (only 22 and 5900) only thing to resolve this is a reboot of the Pi. This issue happens when I delete devices (more than one) from the devices tab, when I delete dead nodes from the z-wave hardware tab and from a script which deletes dummy devices.  If I can be of any help, please let me know.

**Comment by gizmocuz** [comment]
Those commands could take quite some time, depending on the type of harddisk domoticz is installed on
(It needs to delete quite a few things in the database)
But in the end, it should return to normal correct ?

If you can code, you could try adding a mutex at the top of the delete scripts

Does your 'bash' script waits for a return of the curl command ?

**Comment by DutchHans** [comment]
@gizmocuz  
Something has changed in the past few days: Domoticz webserver ports 8080 and 443 were gone when I executed the commands too quickly and only a reboot brought them back. I have just tried to "overload" Domoticz by deleting several switches but the webserver stalled for a second but then returned.
These two commands are executed direct after eachother; no waitstates

commandArray['OpenURL'] = "http://192.168.xxx.xxx:8080/json.htm?type=setused&used=false&idx="..titelIDX..""
commandArray['OpenURL'] = "http://192.168.xxx.xxx:8080/json.htm?type=deletedevice&idx="..titelIDX..""

**Comment by DutchHans** [comment]
@gizmocuz,

There is something weird in the webserver: I tried to ad a z-wave node; (add node) it failed and pressing the abort button did nothing; the wheel kept spinning then resulted in a non accessable webpage. Only thing was a reboot. I guess it is all connected with each other

**Comment by gizmocuz** [comment]
@DutchHans , nothing changed....
No, i think it is another issue, if you can replicate this, please make a new issue
closing this one
