### ISSUE TITLE
With the new Device List when selecting all visible devices and delete, you delete ALL !

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#3087]
Very annoying bug,

With the new introduced Device List, if you use the recent select all VISIBLE devices and then you press the Trash icon (Delete). You get ALL Devices deleted !

**Comment by gizmocuz** [comment]
@stas-demydiuk , is it possible you could have a look at this ?

**Comment by stas-demydiuk** [comment]
Yes, sure, will take a look, probably on weekend

**Comment by pipiche38** [comment]
Fixed in
4.10545
Build Hash: 9a6f48a1-modified
Build Date: 2019-03-07 11:37:07

**Comment by pipiche38** [comment]
That one is back with 10603

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/pull/3167

**Comment by gizmocuz** [comment]
Fixed
