### ISSUE TITLE
rtl_433 temperature_F not parsed

### ISSUE THREAD

**Issue by Net-time** [domoticz/domoticz#3088]
The  inFactory sensor   ID        : 63 Temperature: 73.50 °F   Humidity  : 36 %
Reports in Farenheit so does not get parsed.
As would any other sensor that reports in Farenheit.

Guessing something like this should be inserted before temperature_C in Domoticz/hardware/Rtl433.cpp:

`
	if (FindField(data, "temperature_F"))
	{
		tempF = (float)atof(data["temperature_F"].c_str());
		tempC= (tempF-32.0) / 1.8;
		haveTemp = true;
	}

	if (FindField(data, "temperature_C"))
	{
		tempC = (float)atof(data["temperature_C"].c_str());
		haveTemp = true;
	}
`

**Comment by gizmocuz** [comment]
Thanks for reporting. Implemented in the latest code.
Feel free to make a pull request
