### ISSUE TITLE
rtl_433 moisture not parsed

### ISSUE THREAD

**Issue by Net-time** [domoticz/domoticz#3089]
This is mainly for the Opus-XT300 sensor, on my part it should be sufficient to have it displayed as temp+humidity as it displays air temperature so no new device is needed.

Guessing something like this should be inserted  in Domoticz/hardware/Rtl433.cpp:

`if (FindField(data, "moisture"))
{
humidity = atoi(data["moisture"].c_str());
haveHumidity = true;
}`

**Comment by gizmocuz** [comment]
We do have a moisture sensor in Domoticz
I think it has the same value meaning as your sensor:

```
const char *Get_Moisture_Desc(const int moisture)
{
	if (moisture < 10)
		return "saturated";
	else if (moisture < 20)
		return "adequately wet";
	else if (moisture < 60)
		return "irrigation advise";
	else if (moisture < 100)
		return "irrigation";
	else
		return "dangerously dry";
}
```

Implemented in upcoming beta version
