### ISSUE TITLE
Possibility of DoS attack by spamming JSON requests

### ISSUE THREAD

**Issue by Maccraft123** [domoticz/domoticz#3090]
I have malfunctioning NodeMCU which can hang Domoticz on Raspberry Pi.
It spams JSON light on/off.
We should limit that.
It is a good idea to set this limit it on 1/s or 2/s.
After 5 minutes of spamming Domoticz could add IP address automatically to blacklist where packets go to /dev/null.

**Comment by xbeaudouin** [comment]
Hi,
Really, I think this can be done using ratelimiting from a nginx reverse proxy. Adding such code into domoticz mainstream maybe not a good idea...
Regards

**Comment by gizmocuz** [comment]
Thank you for reporting. I indeed think this should not be added to domoticz
But can you make a bash script illustrating this ?
What happens to domoticz ?

**Comment by Maccraft123** [comment]
Domoticz doesn't respond to any changes in input switches and isn't able to do anything
#!/usr/bin/env bash
while true
do
    curl **IP**/json.htm?type=command&param=switchlight&idx=**IDX**&switchcmd=On
    curl **IP**/json.htm?type=command&param=switchlight&idx=**IDX**&switchcmd=Off
done

**Comment by gizmocuz** [comment]
@Maccraft123 , thank you for the script, had to put the URL between ""
I can see that this could influence the performance on some systems
Myself, i experienced it was a little slower, but it was still functional (odroid as hardware)
As it did not crash domoticz, i don't think this should be considered as a big issue
(Of course best to check the script ;) )
