### ISSUE TITLE
With the new Device List - if the Hardware is disable you still see the devices 

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#3093]
In the V4.9700, when you go in the Delive List and the Hardware is disabled, you don't any of the related devices.

Here with the new version, ALL devices are shown despite the fact that some Hardware could be disabled !

**Comment by gizmocuz** [comment]
@stas-demydiuk , could you have a look at this ? there is a option 'displaydisabled' that should be set to false

**Comment by stas-demydiuk** [comment]
@pipiche38 Are you sure it was working differently with old Device List, as I use exactly the same request to get all devices:
```
/json.htm?type=devices&displayhidden=1&displaydisabled=1&filter=all&used=all
```
I guess `displaydisabled` param affects will disabled devices be shown or not but it was hardcoded to `1` even before my update

**Comment by pipiche38** [comment]
May be it is not related to your changes, but for me it was indeed such behaviour, Hardware disabled, no devices shown.

**Comment by pipiche38** [comment]
thanks
