### ISSUE TITLE
Request: Energy and Gas add cost per day

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#3094]
It would be nice to have extra fields in "Setting / Meters /Counters" for deliverycosts and netmanagementcost (in Dutch Vaste leveringskosten and Netbeheerskosten). Now I have to estimate those costs (which are fixed per day) per kWh for electricity and M3 and gas.

**Comment by rwaaren** [comment]
Is already in the reports

**Comment by SargonofAssyria** [comment]
No its is not. Dutch net managementcosts are made up from variable cost per kWh or m3 and fixed costs for delivery per day or month. In Domoticz are only variable costs available.

**Comment by rwaaren** [comment]
You are right. I confused this with one of the available scripts on the forum to calculate this.
