### ISSUE TITLE
having Web page entry point for each python framework plugin

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#3095]
The Python plugin Framework offer the flexibility to develop light-couple plugin with domoticz. 
However , the plugin them are lacking Web User Interface in terms of administration and user experience as it is only limited to the Hardware page when launching the plugin.

For some complex plugin, there is a need to develop their own web pages and to display in a Web UI their own plugin data.

It would be a great improvement to have the current Domoticz web server able to launche plugin web pages.

If the webserver can be tweaked to 

1. allow loading pages from that folder
[Domoticz]/[plugins]/[Your Plugin Folder]/[www]

and then make it possible to navigate to:
https://127.0.0.1:8080/plugin/[Your Plugin Folder]

and it will search in
Domoticz/plugins/Your Plugin Folder/www

1. allow plugin pages getting access to the [Domoticz]/[plugins]/[Your Plugin Folder]/ file in RW access, so the Web pages could read/update plugin related configuration file.

In case we need to restrict for security reason the RW access I would say that the access right could specify as

```
..../plugins/<your plugin/     
                                     /Data    - ReadWrite
                                    /Conf     - ReadWrite
                                    /www    - Read
                                    /www/... - Read
```

**Comment by dnpwwo** [comment]
Extending the webserver seems okay but writing back to the file system directly is not great from a security perspective. Better to have a standard update URL that passes a JSON payload to a plugin callback for processing.

Not hard to do but @gizmocuz would need to be on board with it because I know he has some concerns in this area.

**Comment by gizmocuz** [comment]
@dnpwwo , i already had a small discussion about this with @pipiche38 but time is always the issue ...
This was the idea i proposed that might be a good solution
Of course the plugin should only be allowed to write in it's own folder... i think this is already possible with the python scripts ?
If not, then maybe indeed a callback function with filename/payload might be a good option
But i suspect the python plugins could already store files ?

**Comment by pipiche38** [comment]
Yes python plugins can store there own data on files...

**Comment by pipiche38** [comment]
@gizmocuz 
At least, if we could have the ReadOnly in the first shoot, this would be highly improving the plugin experience,
then it will leave us some time to address the RW part

**Comment by pipiche38** [comment]
@gizmocuz , @dnpwwo 

Some thought 

1. Domoticz Web server, allows to launch a web page on the plugins/<my plugin>/www/  directory.

1. We extend the OpenZWave specific APIs to the Python Plugin framework by

To query the Plugin details:
 `../json.htm?type=plugin&idx=HardwareID of the plugin`, which will provide what ever information the plugin wants to share

To change a plugin Parameter:
`../json.htm?type=command&param=applyplugin&idx=HardwareID&valuelist=plist`

**Comment by pipiche38** [comment]
@gizmocuz any chance to tweak the web-server ?

@gizmocuz , @dnpwwo  what do you think about the suggestion to extend the OZW specific APIs to the Plugin Framework in order to send Query and Update to the plugin ?

**Comment by dnpwwo** [comment]
I am looking at something similar myself but stll haven't found a solution that fits comfortably in the current application although some parts are obvious.

I'm adding a mechanism to allow arbitrary structured configuration (JSON) to be stored in an existing field in the hardware table in the database.  Authors are currently using variables, hidden devices or files at the moment so there is a clear need for an enhancement. Should be available in a week or so (I'm travelling for the next 5 days).

To serve web page content to allow configuration I have been thinking about simply running a web server inside the plugin itself on a different port using the built in framework connection's 'Listen' function.  That way authors can do whatever they want. Serving files is pretty trivial. Launching it would simply require an HTML button/ link to be added to the plugin's description HTML for the user to click. 

The onMessage function in this plugin [https://github.com/dnpwwo/Domoticz-Google-Plugin](url) returns audio files to a web client for example.

**Comment by pipiche38** [comment]
Very interesting approach.

However I suspect that it works in your case, because you are using the 
HTTP connection.

In my case, I'm either using TCP or SERIAL to get connected to the 
Hardware. And so not in situation to open a 2nd communication channel 
for the Web Part. Then in the case we would be able to do so, I feel 
that I will have to implement a web-serve via the onMessage API.

For the Web admin part to administrate the Plugin and the Hardware we 
are considering using:
- HTML5 , CSS and JavaScript


Patrick

**Comment by pipiche38** [comment]
@dnpwwo I did investigation and this is awesome, I'm able now to run a webserver (at least to serve Html pages) to client. Responding to Get and Post verbs.

So I fully understood your approach and that sound pretty smart.

In my case, it is even pretty easy as the physical devices are either TCP or SERIAL, so an additional connection on HTTP is easy to handle ;-)

**Comment by pipiche38** [comment]
@dnpwwo any chance to get the possibility to have an additional parameter in the Plugin HTML part to get a URL ?

The best would be to have URL equal to the Domoticz WebRoot + <parameter> + <port>
and have the possibility to use <parameter> and <port> inside the plugin.

In such I would have the way to open the Admin page of the plugin directly from the Plugin Hardware and that would be awesome .

Ultimatly when HTTPS would work, we would have the possibility to select the scheme.
