### ISSUE TITLE
SupressTriggers option in Python plugin Framework

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#3097]
When updating a device from a python plugin, associated to the API Devices.Update(), there is an option call SuppressTriggers.

By default this option is False and every time you do cll Devices.Update() you trigger the notification system, so the dzVents and LUA script_device are triggers.

If you set the option to True when calling the API, you disable the trigger effect, but most of the values are not store in the Database.
Due to that the last seen information is not up-to-date at all, and this create a confusion as the Devices seems to be dead (or not live anymore ).

We need a mechanism from the API to at least tell that the device is still live and so Domoticz can reported accurately.

Here after are the description of the Option:

> SuppressTriggers | Optional Default: False 
> 
> Boolean flag that allows device attributes to be updated without  notifications, scene or MQTT, event triggers. nValue and sValue are not  written to the database and will be overwritten with current database  values.

I did into the code, and the only attributes which will be written are the Device Type,Subtype,Swichtype.

CC: @dnpwwo

**Comment by dnpwwo** [comment]
I don't know the thinking behind this functionality, it was done by someone else.

No idea how much it is used.

**Comment by pipiche38** [comment]
@dnpwwo , what do you suggest ? 

I do a PR addressing the current needs ? my idea is to make BatteryLvl and SignalQuality updated to the DB despite the fact that SupressTriggers is enabled . What do you think ?

**Comment by pipiche38** [comment]
Did further investigation inside the code, and I could understand why the 'someone else' did it like that.
It looks like m_sql.Update() is doing the Trigger itself. So it is not inside the 

m_sql.UpdateValue(self->HwdID, sDeviceID.c_str(), (const unsigned char)self->Unit, (const unsigned char)self->Type, (const unsigned char)self->SubType, iSignalLevel, iBatteryLevel, nValue, sValue, sName, true);

**Comment by pipiche38** [comment]
Close, not the right way to do .
