### ISSUE TITLE
Cannot set listen port to greater than 32767

### ISSUE THREAD

**Issue by gsimon75** [domoticz/domoticz#3098]
There is an explicite check for port numbers greater than 32767 [here](https://github.com/domoticz/domoticz/blob/289d917fb0a3106df7b40641a9a9069a48d51676/main/domoticz.cpp#L874), which seems to be over-restrictive, since the upper limit for tcp ports is 65535.

This behaviour appeared at 2017-03-02 and is still there as of now (2019-03-06):
```
commit bc7823feedfc16a18890da8b07560353b0532073
Author: gizmocuz <info@domoticz.com>
Date:   Thu Mar 2 13:18:37 2017 +0100

    Implemented checking for valid www/ssl port
```

**Comment by gizmocuz** [comment]
That is correct. You should not use ports in that range.
Try using another port

**Comment by gsimon75** [comment]
> You should not use ports in that range.

Could you please add some reasoning as of why not?

**Comment by gizmocuz** [comment]
It's just to avoid using a Ephemeral Port Range.... But you have plenty of ports available to choose from

**Comment by gsimon75** [comment]
Ah, I see! Thanks for the info :) !

And for those who find this topic in the future, according to the [Wikipedia article](https://en.wikipedia.org/wiki/Ephemeral_port#Range):
"An ephemeral port is a short-lived transport protocol port for Internet Protocol (IP) communications....Many Linux kernels use the port range 32768 to 61000..."
