### ISSUE TITLE
Xiaomi gateway

### ISSUE THREAD

**Issue by michass** [domoticz/domoticz#3101]
Version: 4.10533
Cut IP adress

![image](https://user-images.githubusercontent.com/43785139/53915343-0071b200-4060-11e9-92a3-c7b6fcbae052.png)
![image](https://user-images.githubusercontent.com/43785139/53915442-33b44100-4060-11e9-8582-22592d47fd26.png)

**Comment by gizmocuz** [comment]
Please explain what is your issue...

**Comment by michass** [comment]
I have 192.168.0.152 IP of gateway,
In logs i have 192.168.0. and Domoticz don't get any informations from cube, no devices discovered.
I have 4.10533 version in docker on synology.
I already tried to use Jaddahl package for synology 4.0.10538-8 and it works.
Maybe this is build issue, and after update can be better.
I would like to stay in cantainer.

**Comment by gizmocuz** [comment]
There have been no xiaomi changes in the last 3 versions so it might also be a network issue
Please continue using the forum

**Comment by michass** [comment]
yes, but yesterday my gateway arrived, maybe this changes between 533 and 538 fix problem.

**Comment by gizmocuz** [comment]
then you have to update your system

**Comment by michass** [comment]
then i need to wait for new build.

**Comment by michass** [comment]
Which port I need to map, to use Getaway?
9898 is not enough.

**Comment by maciekk05** [comment]
@michass, did you solved this issue? I have the same problem when I tried to add gateway on domoticz installed on docker. 
I use the same Gateway on RPi and there is no problem. Udp 9898 is open. So I suspect that problem is connected with domoticz on docker configuration.

**Comment by michass** [comment]
Yes,
you need to "use same network as host docker" now you can't change domoticz ports(8080 fixed port), but works.
You need also change each aliases to domoticz in external units and hardware, where domoticz adress is needed.

**Comment by maciekk05** [comment]
Thanks for feedback. In the meantime I solved this issue (docker run with networking host) so, the end of the day I went the same way as You advised above.  Xiaomi gateway installed correctly and all xiaomi devices found in one minutes.
