### ISSUE TITLE
Devices: Last Seen sort issue in Safari

### ISSUE THREAD

**Issue by HansVanEijsden** [domoticz/domoticz#3103]
Thanks for the new devices list. I like it better!
Unfortunately I had to install Chrome to use it, because in Safari the list doesn't get sorted on date, and also if I click on the Last Seen sort column (upper right, "Laatst gezien" in Dutch) the list doesn't sort by date.
There are no errors visible in the Safari console.

Safari 12.0.3 (14606.4.5), MacOS Mojave 10.14.3 (18D109). No Safari plugins enabled. Language nl_NL.
Domoticz Version: 4.10547, Build Hash: a76a0fdb, Compile Date: 2019-03-08 03:04:06.

![schermafbeelding 2019-03-08 om 16 59 03](https://user-images.githubusercontent.com/11890145/54039562-8bb78880-41c3-11e9-9e38-3ed64f218e78.png)

Let me know if you need more info. Thank you!

**Comment by stas-demydiuk** [comment]
@HansVanEijsden the issue should be fixed in latest Domoticz beta

**Comment by HansVanEijsden** [comment]
@stas-demydiuk confirmed working again. Thank you very much for the fix!
