### ISSUE TITLE
rtl_433 Opus XT-300 moisture not parsed

### ISSUE THREAD

**Issue by Net-time** [domoticz/domoticz#3104]
`model     : Opus-XT300   Channel   : 2             Temperature: 21 C         Moisture  : 27 %          Integrity : CHECKSUM
`
~~It does not have battery indication so it get parsed as temperature only.~~
Edit: Was wrong there, it's because a temperature/moisture device does not exist yet.

I'll let you figure out the code this time as you seem on top of things and the implications on the rest of the code, which I am not. Ta!

**Comment by Net-time** [comment]
Hehe, think I'll leav a suggestion anyhow.
Dont know if it's customary to do "hotfixes" as this sensor should have a new device type.
But I would be happy with it in the interim.
Not att all sure if the batterylevel shold be 0 or 255 to indicate no battery?
'
 	if (haveTemp && haveMoisture) 
 	{ 
		// Hotfix for OPUS XT-300 until new device added.
		batterylevel = 255;
 		SendTempHumSensor(sensoridx, batterylevel, tempC, moisture, model); 
 		return true; 
 	} 

insert somewhere before "367 	if (haveTemp) "
'

**Comment by gizmocuz** [comment]
@Net-time , we have a moisture sensor in domoticz , best to send the temp and the moisture sensor
SendMoistureSensor

**Comment by Net-time** [comment]
@ gizmocuz , Unless I read the documentation wrong the moisture sensor does not take temperature as an argument. Anyway domoticz / hardware / Rtl433.cpp does not support it.
It does not have a " if (haveTemp && haveMoisture). 
It's spring so I'm taking a break in programming and I need a bigger memorycard to compile Domoticz.
For now I recompiled merbanan/rtl_433 locally to send humidity instead of moisture. which solves my immidiate problem, but not anyone elses. I'll be back in winter to sort this unless allready done. Ta

**Comment by gizmocuz** [comment]
@Net-time , spring/summer is also a great time to program ;)
You can always compile/test under windows

**Comment by giocaf** [comment]
Hi all,
someone knows why my moisture sensor send a wrong signal to the 0 Channel with  temperature at -40?
Starting the transmission it sends acceptable signal into channel 2 After few hours It start to send at 0 Channel...
Someone knows why?
Thankyou!

**Comment by gizmocuz** [comment]
@giocaf , please use our forum

**Comment by giocaf** [comment]
Hi gizmocuz, are you talking about the domoticz forum?

**Comment by gizmocuz** [comment]
@giocaf , yes i do ;)

**Comment by dgrostoto** [comment]
As far as i know, domoticz will now create 2 devices, one device with moisture and another device with temperature, which will handle all information gathered by rtl_433., and coherent with domoticz handling. The two devices created can be "joined" in one graph using dashticz (V3) for example.
If it does not work as is, let me know and i'll fix it, else this issue can be closed (see  PR https://github.com/domoticz/domoticz/pull/3902 )

**Comment by geschriever** [comment]
Hi,
The XT-300 is parsed by Domoticz integrated RTL433 however it is reporting in CB and not in %.
According the specifications it should be %, is it possible to change this?
<img width="461" alt="image" src="https://user-images.githubusercontent.com/60884808/101341876-05414680-3882-11eb-8299-9d6fb7ba5a95.png">

<img width="384" alt="image" src="https://user-images.githubusercontent.com/60884808/101341966-273ac900-3882-11eb-93b0-5eedbabbd48d.png">

**Comment by gizmocuz** [comment]
That's because the internal moisture censor in Domoticz reports in Centibars.
It is possible, but then we have to use it as a custom sensor

**Comment by geschriever** [comment]
Thanks for the quick feedback!
Seems to be feasible as custom sensor because the XT-300 = R 121 is reporting in % and not in CB.
Please if you could do so, it would be great but I'm not sure if it will hurt anybody else with the same sensor.
Thanks in advance


> That's because the internal moisture censor in Domoticz reports in Centibars.
> It is possible, but then we have to use it as a custom sensor

**Comment by gizmocuz** [comment]
In beta 12732 it should be a custom sensor now.. hope not many users used the current moisture sensor

**Comment by geschriever** [comment]
Thanks, it works for a few minutes like a charm, but then Domoticz crashes (see also crashlog)?
Maybe a small issue but please could you have a look?
[domoticz_crash.log](https://github.com/domoticz/domoticz/files/5655045/domoticz_crash.log)

**Comment by geschriever** [comment]
I've reinstalled both values for the sensors in Domoticz, probably this will solve the issue. Will test now for a few days.
I did only replaced the customer sensor moisture and not the temperature, now both are reinit.

**Comment by geschriever** [comment]
Seems to be stable now, no crashes anymore. Thanks!
