### ISSUE TITLE
Thermostatr to tab Temperature

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#311]
Hello
From some days i start use Z-Wave Danfoss Thermostat. It is show after find in Tab Utility. I think that better option is move devices thermotat to Tab Temperature, In this tab temp will be devices show temperature and set temperature. But in tab utility will be devices to measure utiklity and other ex usage CPU, Memory. Thermostat does not fit to this tab. In other system automation home also thermotat is with temp.
Please move it to tab temp.

**Comment by ghost** [comment]
Why ? When you close issue and PR please put reason why or why not mered because i dont know what is a reason ?

**Comment by pepijng** [comment]
This is not aan issue but works as designed.

**Comment by ghost** [comment]
Ok but it is not intuitive. The thermostat should be logically in temperature.

**Comment by gizmocuz** [comment]
And also when i tell you by email i will not change it, you should not post it here to ask again
