### ISSUE TITLE
Fibaro roller shutter 3 level not working

### ISSUE THREAD

**Issue by boscorelly** [domoticz/domoticz#3112]
Hi,

i have a fibaro roller shutter 3.
It's successfully integrated with domoticz in secure mode.

However, i can't set a level in domoticz :
> 2019-03-11 16:40:47.724 OpenZWave: Domoticz has send a Switch command!, Level: 43, NodeID: 6 (0x06)
> 2019-03-11 16:46:48.768 Status: OpenZWave: Received timeout notification from HomeID: 3439074512, NodeID: 6 (0x06)

is use the latest domoticz beta

**Comment by ihagens** [comment]
Hi have the same issue. 
Not sure its a Domoticz issue. (https://forum.fibaro.com/topic/32841-roller-shutter-3-calibration-and-working-issues/?page=2)

https://community.openhab.org/t/problems-with-brandnew-fibaro-fgr223-roller-shutter-3/65278/2

@boscorelly Did they work before you updated to the latest beta??

**Comment by boscorelly** [comment]
Hi,

i have take back the module. i don't have this one but i know there is also a fibaro firmware issu

**Comment by ihagens** [comment]
Fibaro firmware issue Shouf he fixed in the latent firmware. However there is a issue in the latest openzwave support as well. Got hold of a V2 for now as well

**Comment by jonferreira** [comment]
Any update on this? I have 6 RS3 to install but seem they're unusable as is...

I have the old v2 and they used to behave a bit odd but still usable. Upon activation they would

report "desired" position
report "old" (i.e. current) position
--motor working--
report "new" position

So messy, but usable.

These seem worse as they only do 

report "desired" position
report "old" (i.e. current) position

**Comment by boscorelly** [comment]
The problem is as firmware problem. You need to contact your seller to refund you or upgrade the firmware. Nothing to deal with domoticz.

**Comment by jonferreira** [comment]
Not really. Old models do the same.

Plus apparently the RS3 v5.1 causes more harm than good judging by the reviews. That said I do have a Fibaro HC2 I can use to update its firmware so happy to test and report back
