### ISSUE TITLE
Domoticz Forum down????

### ISSUE THREAD

**Issue by harryd100** [domoticz/domoticz#3115]
When selecting https://www.domoticz.com/forum/ i get an HTTP ERROR 500.

**Comment by rwaaren** [comment]
Yes. but was up for some time around 18:00

**Comment by pipiche38** [comment]
This morning at 8:30 AM CET
<img width="843" alt="Screenshot 2019-03-15 at 08 34 31" src="https://user-images.githubusercontent.com/8291674/54415655-33b9de00-46fd-11e9-8281-bda2de20e998.png">

**Comment by harryd100** [comment]
Works again, case closed

**Comment by pipiche38** [comment]
I'm sorry not !
Please check the sub-forums !
<img width="1189" alt="Screenshot 2019-03-15 at 14 45 59" src="https://user-images.githubusercontent.com/8291674/54435590-228ac480-4731-11e9-9180-192f04334bea.png">

**Comment by harryd100** [comment]
This morning it was working

**Comment by Siewert308SW** [comment]
Website has its ups and downs, server is not really stable at the moment.
hope it's back on track soon...
