### ISSUE TITLE
Netatmo: Error connecting to Server...

### ISSUE THREAD

**Issue by alaunay** [domoticz/domoticz#3119]
Hello,

Using the last git domoticz, I'm unable to connect to the netatmo api, domoticz gives me a

2019-03-18 12:24:47.053  Error: Netatmo: Error connecting to Server...

I modified a bit the cpp file to print what it sends:

2019-03-18 12:24:46.989  Error: httpUrl: https://api.netatmo.net/oauth2/token
2019-03-18 12:24:46.989  Error: httpData: grant_type=password&client_id=5588029e485a88af28f4a3c4&client_secret=6vIpQVjNsL2A74Bd8tINscklLw2LKv7NhE9uW2&username=modified%40modified.com&password=nope&scope=read_station read_thermostat write_thermostat read_homecoach

And tried directly on CLI:

$ curl -s -d "grant_type=password&client_id=5588029e485a88af28f4a3c4&client_secret=6vIpQVjNsL2A74Bd8tINscklLw2LKv7NhE9uW2&username=modified%40modified.com&password=nope&scope=read_station read_thermostat write_thermostat read_homecoach" "https://api.netatmo.net/oauth2/token"

{"access_token":"hexastuff|hexastuff","refresh_token":"hexastuff|hexastuff","scope":["read_station","read_thermostat","write_thermostat","read_homecoach"],"expires_in":10800,"expire_in":10800}

It works on CLI, but it seems the HTTPClient part in the domoticz doesn't do what it needs...

I've no idea how to debug this, c++ isn't something I know (more than printing a few variables).

Hints ?

**Comment by lorenzo-deluca** [comment]
I've the same problem.
I receive errors on email and sometimes I receive several mail with "Netatmo: Error connecting to Server..." Probably this is a Netatmo server problem, is it possible to remove from errors, maybe only an info log message ?
It's on Netatmo.cpp

`bool ret = HTTPClient::POST(httpUrl, httpData, ExtraHeaders, sResult);
	if (!ret)
	{
		_log.Log(LOG_ERROR, "Netatmo: Error connecting to Server...");
		return false;
	}`

Thanks to everyone.

**Comment by pipiche38** [comment]
same and still existing problems, can it be related to a too often polling

**Comment by gizmocuz** [comment]
Yes it could be related. It is currently set to 500 seconds (5 minutes)
Is it possible you can change/test this ?

**Comment by pipiche38** [comment]
@gizmocuz you know that I'm more a python man than a C++, but yes, I'll try that .

However while looking at the code, the comment says the Weather is updated every 10mins, which correspond to the 600 (=10 minutes)

Found that on the web, so I'll make a test with every 15'
> According to the Netatmo documentation data is measured every 5 minutes by the modules and sent to the servers every 10 minutes. So there is no need to lower the polling frequency. Data is retrieved at once, so individual data points do neither make sense nor is it possible.


Test is in place. Will keep you posted

**Comment by gizmocuz** [comment]
Your fast with c as well👍😎

**Comment by pipiche38** [comment]
It came to 1 issue per day. In  order to see if it is conclusive or not, I'll revert the fix and monitor back to see if I get it more often

**Comment by gizmocuz** [comment]
Thank you for testing!

**Comment by pipiche38** [comment]
Ok, I'll refine a PR to see what is the best convenient time, but this is conclusive.
My only concern is that 900s was reducing a lot, but I was still getting once or twice a day the error message

**Comment by waltervl** [comment]
Perhaps make the update frequency a user setting in hardware? Will make things more complex in the PR but will be more flexible in the end for the netatmo user....

**Comment by pipiche38** [comment]
Then you need to find someone else. I can only basic C/C++ programming 

Envoyé de mon iPhone

**Comment by waltervl** [comment]
If I read here https://dev.netatmo.com/apidocumentation/weather the data is updated every 10 minutes to the server so there is no need to check every 5 minutes. But that is for Weather data. I do not know what the values are for other areas.
And with regards to my remark about update frequency you can ignore it off course, no bad feelings ;-)

**Comment by pipiche38** [comment]
I'll push a PR, now, but the error still happen time to time, but for sure less than  before.
