### ISSUE TITLE
JSON output for Groups/Scenes don't contain PlanID and PlanIDs

### ISSUE THREAD

**Issue by hansworst24** [domoticz/domoticz#312]
**/json.htm?type=devices&filter=all&used=true** provides all devices and scenes/groups that are used. For all devices it also provides to which Plan they belong (PlanID and PlanIDs). This isn't the case for Groups/Scenes, which do not contain a PlanID or PlanIDs.

I _could_ get the scenes/groups belonging to a Plan, by asking **/json.htm?type=devices&filter=all&used=true&plan=3**, and then filter out the IDX's for Groups/Scenes, but I personally think it would be much nicer to provide the PlanID and PlanIDs for Scenes/Groups by default, when asking for all devices.

Please let me know if this is worth a fix !

ps : checked on V2.4088, the issue is still there. I'm running V2.4015

**Comment by gizmocuz** [comment]
Thats worth a fix indeed as scenes/groups can be part of a 'plan'
Please go ahead and make the patch

**Comment by hansworst24** [comment]
Thanks, but I'm afraid I can't make the patch on Domoticz itself :open_mouth:   I was more thinking about making a work-around within the upcoming Windows Phone app I'm writing :smile: I feel comfortable in VB.net by now, but C is.....too cryptic :smile:

**Comment by EddyK69** [comment]
I will implement this :)
Expect to make a pull request soon...

**Comment by EddyK69** [comment]
Patch submitted in pull request #346

**Comment by hansworst24** [comment]
You're the bomb EddyK69 :smiley: I'll check it out once its merged.

**Comment by EddyK69** [comment]
yw!
It has been merged...

**Comment by hansworst24** [comment]
works like a charm !

**Comment by EddyK69** [comment]
Sorry to tell, but this patch has been reverted because of issues with scene without a roomplan (see #346). I will try to fix this and make a new PR

**Comment by gizmocuz** [comment]
i still think it works, but it was causing problems when a scene was not in a room plan (as in default)
so scenes in a room plan, should work with the current patch...i suppose, but i might be wrong

**Comment by EddyK69** [comment]
Applied fix in PR #357
