### ISSUE TITLE
Door Contact state

### ISSUE THREAD

**Issue by Addie363** [domoticz/domoticz#3121]
Hello,

I think there is something wrong with switch type  Door Contact.
In this case I use a Shenzhen Neo Electronics Co Ltd Door/Window Detector+ door contact and when I look at the logging it somethimes logs a on/off and an other time it logs an open /close.
Sow I don't know what statement to use in the Blockly. Is this a bug?

**Comment by Siewert308SW** [comment]
Just checked as never watched or investigated those device logs.
But as for the latest beta i see only on/off.
I use Lua with Open/Close which works as the widget says open/close which is the real state, don't know but think Blocky will react on Open/Close aswell no matter what the log says.

**Comment by Addie363** [comment]
Today the switch is in a good mood. I'ts in the open/closed mood. Yesterday it was in the on/off mood...
I've made a workaround by cloning the blockly's and making to versions of them. One for the on/off mood and another for the open/closed. It olso changes randomly trough the day. It happaned a few weeks ago, until I noticed the heating and air-dehumifyer did not stop when the door was open. I'running latest beta's...

**Comment by gizmocuz** [comment]
@Addie363 , it's not a general door contact problem and might be related to the (chineese) hardware
Do you still have this issue? Also with for example a Fibaro/Aeotec ?

**Comment by Addie363** [comment]
Hello, 

The rules i've made witrh the on/off function are suspended for two weeks now, and it seems to work with the open/close rules. Look's like it is no issue anymore...

**Comment by gizmocuz** [comment]
Thanks for the feedback
