### ISSUE TITLE
Forum down again

### ISSUE THREAD

**Issue by harryd100** [domoticz/domoticz#3124]
This page isn’t working www.domoticz.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by sincze** [comment]
Still indeed.
Deze pagina werkt niet www.domoticz.com kan dit verzoek momenteel niet verwerken.
HTTP ERROR 500

**Comment by Siewert308SW** [comment]
Yep... Lately it's common to see it down then up.
Already down for almost 3 days after that the certificate issue.

**Comment by DewGew** [comment]
Website and wiki works for me  but not the forum. @gizmocuz @dannybloe

**Comment by gizmocuz** [comment]
Thanks for reporting... no idea why it happens, maybe it is getting to busy
@Siewert308SW , thanks for your always positive support comments !

Maybe it way a problem with one of the latest kernels, it's upgraded again, hope it will be better now

There is also quite some activity for fail2ban

**Comment by sincze** [comment]
Tnx @gizmocuz , all up and running here indeed!

**Comment by harryd100** [comment]
Thnx, working again.

**Comment by Siewert308SW** [comment]
@gizmocuz

Your welcome... 🙈
