### ISSUE TITLE
JS error when trying to add a device to a scene

### ISSUE THREAD

**Issue by alex1712** [domoticz/domoticz#3130]
When I try to add a bulb to a scene nothing happens. Checking the browser developer tools I could see this error:

```
Uncaught TypeError: $(...)[0].getJSONColor is not a function
    at Object.<anonymous> (ScenesController.js:169)
    at Function.each (jquery-3.3.1.min.js:2)
    at AddDevice (ScenesController.js:164)
    at HTMLAnchorElement.onclick ((index):1)
```

<img width="1432" alt="screenshot" src="https://user-images.githubusercontent.com/408460/55033221-eac62b80-5012-11e9-84bd-08d2bf7b7c0e.png">

**Comment by gizmocuz** [comment]
Could you mention the version you are using ?

**Comment by waltervl** [comment]
No feedback, can be closed.
