### ISSUE TITLE
Add Selector Switch New Level With JSON

### ISSUE THREAD

**Issue by aminjoharinia** [domoticz/domoticz#3143]
What is The JSON URL for Add a new level for selector switch
I add the selector using this url:
```
http://127.0.0.1:8080/json.htm?type=createvirtualsensor&idx=IDX&sensorname=NAME&sensortype=1002
```
and need to add some new levels using JSON

**Comment by Olifant1990** [comment]
I was looking into this a while ago too.
Then I found this thread: https://www.domoticz.com/forum/viewtopic.php?t=16555
Never done it myself, so I don't know if this (still) works.
Have a look and let us know! :)

**Comment by aminjoharinia** [comment]
@Olifant1990 
The problem is this base64 code not working and delete all levels
here is the code in that url
```
TGV2ZWxOYW1lcyUzQU9mZiU3Q0xldmVsMSU3Q0xldmVsMiU3Q0xldmVsMyU3Q2xldmVsNCUzQkxldmVsQWN0aW9ucyUzQSU3QyU3QyU3QyU3QyUzQlNlbGVjdG9yU3R5bGUlM0EwJTNCTGV2ZWxPZmZIaWRkZW4lM0FmYWxzZSUzQg==
```
The Full Url

```
http://url:port/json.htm?type=setused&idx=IDX&name=NAME&description=&strparam1=&strparam2=&protected=false&switchtype=18&customimage=0&used=true&addjvalue=0&addjvalue2=0&options=TGV2ZWxOYW1lcyUzQU9mZiU3Q0xldmVsMSU3Q0xldmVsMiU3Q0xldmVsMyU3Q2xldmVsNCUzQkxldmVsQWN0aW9ucyUzQSU3QyU3QyU3QyU3QyUzQlNlbGVjdG9yU3R5bGUlM0EwJTNCTGV2ZWxPZmZIaWRkZW4lM0FmYWxzZSUzQg==
```
I think the format is Wrong
here is Decode base64
```
LevelNames%3AOff%7CLevel1%7CLevel2%7CLevel3%7Clevel4%3BLevelActions%3A%7C%7C%7C%7C%3BSelectorStyle%3A0%3BLevelOffHidden%3Afalse%3B
```

**Comment by gizmocuz** [comment]
seems to be urlencoded as well

**Comment by gizmocuz** [comment]
But if you look at your chome developer console you should be able to see what is being called, and the source is also open
