### ISSUE TITLE
Rtl433: Unhandled sensor reading  akhan / X10

### ISSUE THREAD

**Issue by alex1313c** [domoticz/domoticz#3144]
Hello
Sorry for my english translated
I have two problems  i use Realtek RTL2832 based DVB dongle to receive 433Mhz I use the latest version RTL, and domoticz version: 4.10602 
the first is a remote control key 3 buttons ("beeper X6 R-TX2") which is very well
 recognized by the command rtl__433 -G ( or protocol 48)

```
time      : 2019-04-09 20:27:00
model     : Akhan 100F14 remote keyless entry      ID (20bit): 0x6e890
Data (4bit): 0x4 (Mute)
_ _ _ _ _ _ _ _ _ _ _ _

time      : 2019-04-09 20:27:07
model     : Akhan 100F14 remote keyless entry      ID (20bit): 0x6e890
Data (4bit): 0x1 (Lock)
_ _ _ _ _ _ _ _ _ _ _ _

time      : 2019-04-09 20:27:08
model     : Akhan 100F14 remote keyless entry      ID (20bit): 0x6e890
Data (4bit): 0x2 (Unlock)
_ _ _ _ _ _ _ _ _ _ _ _

```
and on domoticz:

```
2019-04-09 20:28:57.341 Status: Rtl433: Unhandled sensor reading, please report: (time,msg,codes,model,id,channel,state,unit,group,battery,
temperature_C,humidity,brand,sid,data,sensor_id,battery_low,battery_ok,sequence_num,message_type,wind_speed_mph,wind_speed_kph,wind_avg_mi_h,
wind_avg_km_h,wind_dir_deg,rain_inch,rain_in,temperature_F
2019-04-09 20:28:57.341 |2019-04-09 20:28:56,,,Akhan 100F14 remote keyless entry,452752,,,,,,,,,,0x4 (Mute),,,,,,,,,,,,,
2019-04-09 20:28:57.341 ) 

-------------------

2019-04-09 20:29:05.254 Status: Rtl433: Unhandled sensor reading, please report: (time,msg,codes,model,id,channel,state,unit,group,battery,
temperature_C,humidity,brand,sid,data,sensor_id,battery_low,battery_ok,sequence_num,message_type,wind_speed_mph,wind_speed_kph,wind_avg_mi_h,
wind_avg_km_h,wind_dir_deg,rain_inch,rain_in,temperature_F
2019-04-09 20:29:05.254 |2019-04-09 20:29:05,,,Akhan 100F14 remote keyless entry,452752,,,,,,,,,,0x1 (Lock),,,,,,,,,,,,,
2019-04-09 20:29:05.254 ) 

-------------------

2019-04-09 20:29:12.066 Status: Rtl433: Unhandled sensor reading, please report: (time,msg,codes,model,id,channel,state,unit,group,battery,
temperature_C,humidity,brand,sid,data,sensor_id,battery_low,battery_ok,sequence_num,message_type,wind_speed_mph,wind_speed_kph,wind_avg_mi_h,
wind_avg_km_h,wind_dir_deg,rain_inch,rain_in,temperature_F
2019-04-09 20:29:12.066 |2019-04-09 20:29:11,,,Akhan 100F14 remote keyless entry,452752,,,,,,,,,,0x2 (Unlock),,,,,,,,,,,,,
2019-04-09 20:29:12.066 ) 

-------------------
```

My second problem and protocol x10 (motion detector X10 MS13E and wall remote X10 SS13) ( Protocol 22 )

```
time      : 2019-04-09 20:33:40
model     : X10-RF       houseid   : B             deviceid  : 2
state     : ON           data      : 708f10ef
_ _ _ _ _ _ _ _ _ _ _ _

```
log domoticz 

```
2019-04-09 20:34:27.044 Status: Rtl433: Unhandled sensor reading, please report: (time,msg,codes,model,id,channel,battery,temperature_C,humidity,brand,
sid,data,sensor_id,battery_low,battery_ok,sequence_num,message_type,wind_speed_mph,wind_speed_kph,wind_avg_mi_h,wind_avg_km_h,wind_dir_deg,rain_inch,rain_in,
temperature_F
2019-04-09 20:34:27.044 |2019-04-09 20:34:26,,,X10-RF,,,,,,,,1888424175,,,,,,,,,,,,,
2019-04-09 20:34:27.044 ) 
```

on the other hand if I activate the protocol 96 it works except that all my equipment X10 controls the Lightning 2 (DMX10 RF)

`2019-04-09 20:35:32.234 (RTL433) Lighting 2 (DMX10RF)`

I also have 2 remote controlled KR18 and KR21 that are not visible with the command rtl__433 -G, but that's another problem
Do you have a solution to save it's equipment thank you in advance

**Comment by alex1313c** [comment]
Hello .

I still can not operate the remote control :(

Someone would have any idea

**Comment by taismi** [comment]
> Hello .
> 
> I still can not operate the remote control :(
> 
> Someone would have any idea

I have same kind of problems. Domoticz support for RTL433 is broken.

`2019-05-26 15:14:41.710  Status: Rtl433: Unhandled sensor reading, please report: (time,model,button,id,channel,battery,temperature_C,mic,rid,humidity,state,brand,rain_rate,rain_total,gust,average,direction,pressure_hPa,uv,power_W,energy_kWh,unit,group_call,command,dim,dim_value,wind_speed,wind_gust,wind_direction,dipswitch,rbutton,device,temperature_F,status,rc,brandmodelidtemperature_C,setpoint_C,switch,direction_str,direction_deg,speed,rain,msg_type,signal,hours,minutes,seconds,year,month,day,sensor_code,uv_status,uv_index,lux,wm,fc,ws_id,rainfall_mm,wind_speed_ms,gust_speed_ms,current,interval,learn,windstrength,winddirection,flags,maybetemp,binding_countdown,depth,dev_id,power0,power1,power2,node,ct1,ct2,ct3,ct4,Vrms/batt,temp1_C,temp2_C,temp3_C,temp4_C,temp5_C,temp6_C,pulse,sid,transmit,moisture,type,pressure_PSI,battery_mV,pressure_bar,code,pulses,energy,device id,len,to,from,payload,event,heartbeat,brandmodelidstatus,temperature_C1,temperature_C2,test,newbattery,heating,heating_temp,water,wind_dir_deg,uvi,light_lux,counter,alarm,depth_cm,repeat,temperature_1_C,temperature_2_C,device_type,raw_message,switch1,switch2,switch3,switch4,switch5,house_id,module_id,sensor_type,sensor_count,alarms,sensor_value,battery_voltage,data,failed,pressure_kPa`

**Comment by alex1313c** [comment]
Hello
How to declare in domoticz that it is an ON / OFF sensor
Do you have any idea about a RTL433 USB TNT compatible keychain remote control model that works on domoticz

**Comment by dgrostoto** [comment]
Hello, there multiple demand of device support here.
The main thing to know is that rtl_433 do not auto tell (auto discovering) what type of sensor/actuator it is about.
Presently domoticz deduce the type of device from the data it finds. For example, if there a temperature field, it deduces it is a temperature sensor and create the adhoc sensor in domoticz (provided the user let the automatic creation of devices domoticz parameters web interface).
Here we have a beeper X6 R-TX2 with is a switch with 3 states at least, and two X10 (motion detector and i'm not sure what type is the wall remote ? a remote command with several buttons ?)
So we have to interpret those device of the correct type.
@gizmocuz
The question is : do we try to use the normalized set of keys (newmodel) of rtl_433, if this model is complete enough this could be a good option,
or do we add a type sensor so that domoticz create the adhoc device with the good value taken from normalized keys ?

**Comment by gizmocuz** [comment]
I am not a RTL433 expert, it is best to test the latest beta version to see if this works for you.
I use a RFXCom RFXtrx433-E/X device for reception and sending
