### ISSUE TITLE
domoticz.sh runs domoticz as root

### ISSUE THREAD

**Issue by m4lvin** [domoticz/domoticz#3145]
The `domoticz.sh` script does not actually pass `--chuid` to `start-stop-daemon` because it is only added in the line testing whether the daemon is already running. See https://github.com/domoticz/domoticz/blob/ce68fa52ca292b5f784af47e45440196c272df1e/domoticz.sh#L60 versus https://github.com/domoticz/domoticz/blob/ce68fa52ca292b5f784af47e45440196c272df1e/domoticz.sh#L62

I wanted to make a pull request. The [instructions](https://github.com/domoticz/domoticz/blob/development/.github/CONTRIBUTING.md#fixing-bugs) say to base against the `master` branch, but the `development` branch seems to be the one actually used. Which one should I use?

**Comment by harryd100** [comment]
pull-requests are done against the development branch as far as i know

**Comment by m4lvin** [comment]
Why is this now closed? Has it been fixed?

https://github.com/domoticz/domoticz/blob/development/domoticz.sh#L62 still looks wrong to me.

Should I make a PR against the master branch?

**Comment by gizmocuz** [comment]
@m4lvin , yes please, please make a PR against the development branch.
We were waiting for a small response 23 days ago ;)
