### ISSUE TITLE
scene timer screen wrong

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3147]
i upgraded to V4.10602 and noticed that when i want to edit a scene timer i get this weird screen.

I cleared out the browser cache and the problem is gone.
i am using the latest chrome browser
However after using domoticz for a while (10 minutes) the problem is there again.
it only seems to happen with the scenes, not the switches
i came from v4.10394 so do not know during which build this happened.

any ideas

![scene timers  fout](https://user-images.githubusercontent.com/16853535/56090543-b6bc8880-5ea3-11e9-82c9-49011afe2be4.JPG)

**Comment by RicardP** [comment]
Hi, I belive it is a browser issue, try another browser, clear cach, etc...? :)

**Comment by GravityRZ** [comment]
yes i thought so too but it is re occuring after a while.
this never happened before
after a new install it is normal to clear cache and problems are gone.
now after clearing cache the problem is gone but appears after a while without that domoticz has changed

i only have it with the log and timer buttons of all the scenes

**Comment by rwaaren** [comment]
Do you see in www/js  a file domoticz.js.gz, ?
if its there remove it, (KEEP domoticz.js !! )

**Comment by GravityRZ** [comment]
no only 
domoticz.js
domoticzdevices.js
luxon.min.js

and a lot of .gz files

**Comment by rwaaren** [comment]
Better to discuss on the forum as it seems not an issue for all users but my approach would be to remove all files from this directory and update to latest Beta (this will install all required files in this directory)

**Comment by GravityRZ** [comment]
ok thanks, will try

**Comment by GravityRZ** [comment]
will close the issue here
