### ISSUE TITLE
Thermostat Mode widget

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#3148]
I had a look #2906 , as I wanted to use this sType in order to create a Thermostat Mode inside a dedicated plugin.

Unfortunately it looks like sTypeZWaveThermostatMode is RESERVED to ZWave Hardware only and the modes seems to be hardcoded or something like that !

Could we have a widget sTypeThermostatMode which should be based on the same approach of the ZWaveThermostatMode but instead having the various mode stored in the Options field, as it is done for the Switch Selector ?

**Comment by gizmocuz** [comment]
I think the modes are received from the zwave node itself.
Maybe you can use a selector switch type ?

**Comment by pipiche38** [comment]
So did I (moving to selector Switch).
But I think that it would be beneficial for all plugins to extend features developed for an other one.
