### ISSUE TITLE
Need help for watchdog

### ISSUE THREAD

**Issue by Barabba11** [domoticz/domoticz#3149]
Hi! I'm really sorry to post here and as an issue, I don't know other ways to contact you, thaks for understanding!
I've tried to subscribe to forum but it asked me to order the days (chapta) and I did it (Firefox) but it doesn't work, and I overcome the number of attempts. May you intruduce to foru and easier chapta? Thanks..

My qestion regard your Watchdog, I've reaspberry and Node Red, I would like to use it but I'm afraid to create problems after it. I kindly ask your support for the installation, if I understand well I have to type the following commands:
sudo modprobe bcm2835_wdt
echo "bcm2835_wdt" | sudo tee -a /etc/modules
sudo apt-get install watchdog
sudo update-rc.d watchdog defaults
sudo nano /etc/watchdog.conf   and unhash the watchdog device (what is the watchdog device? Something working under domoticz?)  un hash #max-load-1 (is it the load of CPU? if goes over it for one minute it reboots)
sudo nano /etc/init.d/domoticz.sh and edit:
OPTIONS="-www 8080 -loglevel=normal -log /tmp/domoticz.log"  (does this means that it will check the port 8080 by sending an http and expecting a response, loglevel normal what is for? the -log /tmp/domoticz.log expects to find this file (who does create it?)

Maybe add this too?
DAEMON_ARGS="$DAEMON_ARGS -www 8080 -loglevel=normal"
DAEMON_ARGS="$DAEMON_ARGS -sslwww 443"  (to check the port 443 by ssl?)
DAEMON_ARGS="$DAEMON_ARGS -log /tmp/domoticz.log"

after open sudo nano /etc/watchdog.conf and uncomment
file                    = /tmp/domoticz.log
change                  = 300  (what is this for?)
And finally sudo service watchdog start

I don't care about the email, is already enough complicated to make this run properly ))
Well for me it is enough to check if the TCP port 1080 is open and responsive, as well as 22 SSH, may you please help me? Thank you!!

**Comment by Barabba11** [comment]
please kindly help me, thank you!

**Comment by Barabba11** [comment]
Please kindly help, thank you!

**Comment by Dekkerjj** [comment]
Hi Barabba, You're right this is not an issue that belongs on github and is not an issue for the coders.


Apparently you're wondering whether to use [Watchdog](https://www.domoticz.com/wiki/Setting_up_the_raspberry_pi_watchdog) (thorough reading of this tutorial has half your questions answered) as a port monitor which is not the intention of this tutorial. 
In this case watchdog looks for (the absence of) changes in the domo-logfile and restarts the Pi if there's no change (for f.e. 300 seconds)
[Uptimerobot](https://uptimerobot.com/) might be a better option for port monitoring. 

I suggest you have a go at re-registering at the forum again. (May I introduce to you Chrome and 'Incognito' mode?) ;-)

I kindly suggest closing this issue

**Comment by Barabba11** [comment]
thank you a lot for your kind answer! Uptimerobot can't be a solution for me, I need something working in local only (without internet) that can reset RB when a TCP port on loopback is not more open.
May you please explain the sense of this? WHich kind of checks is making? 
DAEMON_ARGS="$DAEMON_ARGS -www 8080 -loglevel=normal"
DAEMON_ARGS="$DAEMON_ARGS -sslwww 443" (to check the port 443 by ssl?)

About the logfile, I can create a file in RAM from NR and edit it periodically, I can write there for example the number of the seconds and minutes of the clock: I open file, reset the file content, write the minutes:seconds and save the file, will it work?
Thank you a lot for help, I really need someone who can support me

**Comment by rkluwen** [comment]
Just jumping on to this thread: Have you looked at the monit package yet?

**Comment by Barabba11** [comment]
Thank you for kind suggestion! I'm looking at it now!

**Comment by Dekkerjj** [comment]
@Barabba11 
The questions you ask about the checks that `DAEMON_ARGS=` does are not checks. They are variables that domoticz uses, f.e. `DAEMON_ARGS="$DAEMON_ARGS -log /tmp/domoticz.log"` makes domoticz create and use a logfile in /tmp/domoticz.log .

Watchdog then is able to use the logfile to monitor for (the absence) of logging.

btw. This is the last explanation I am going to give here, I still think you should make an effort and use the forum for these questions and close this issue (because it it not a programmatic issue)
User issues is what the forum is meant for.
