### ISSUE TITLE
Switches charts graphs

### ISSUE THREAD

**Issue by kovainfo** [domoticz/domoticz#3151]
Charts for any switches do not work. also does not work sorting by date.

(MacOSX Safari version 12.1 (14607.1.40.1.4)
![Снимок экрана 2019-04-17 в 9 36 38](https://user-images.githubusercontent.com/36986231/56266430-da2a4200-60f4-11e9-92a2-bc1a75a83b7a.png)

**Comment by kovainfo** [comment]
This works for me only in mozilla firefox. ((

**Comment by gizmocuz** [comment]
Could you clear your browser + appcache, and also try in private browsing mode ?
I use Chrome, no issues here

**Comment by kovainfo** [comment]
Ok, looks like this is Safari issue. besides, both the desktop version and the mobile version do not work.
