### ISSUE TITLE
Custom Menu

### ISSUE THREAD

**Issue by DewGew** [domoticz/domoticz#3161]
When a html document is in the templates folder the custom menu shows even if custom menu is set to disabled in settings.

**Comment by gizmocuz** [comment]
I can't replicate this... are you on the beta version ?

**Comment by DewGew** [comment]
Yes IM on beta

**Comment by gizmocuz** [comment]
I renamed the example template to have the .html extension.
The custom menu was visible. Then under settings, i disabled the custom menu
The button was gone.
Are you using the default theme ?

**Comment by DewGew** [comment]
I try both default and machinon themes. Seems like its just me that have this issue.

**Comment by DewGew** [comment]
I've cleared cache, restart domoticz, same issue on edge.

![dashboard](https://user-images.githubusercontent.com/28799807/56946369-3300ce00-6b2a-11e9-931c-381cf4460877.png)

**Comment by gizmocuz** [comment]
Tested once again... no issue here with Brave/Chrome/Edge/Firefox ....
Sorry, could you please create a forum post about this as i do not think it's a code issue
