### ISSUE TITLE
Latest beta not showing new made user variables in blockly. 

### ISSUE THREAD

**Issue by astrapowerrr** [domoticz/domoticz#3166]
Version: 4.10629

As I made some new user variables to put in my blockly they just don’t show up. 
Only the variables I made before from stable version or older...

I tried integer and float but they just aren’t there for use in blockly. 

I have screenshots from my made variables. 
And from not showing up in blockly.

**Comment by rwaaren** [comment]
I cannot reproduce this behavior in version V.10629 on Debian.  Just tested with both integer and float (named test2 and test3) and the both show immediate in Blockly without restarting domoticz or refreshing cache (Chrome).

**Comment by astrapowerrr** [comment]
ok closed.. tried this even this afternoon and nothing and now they show up..
sorry for your time..
