### ISSUE TITLE
Ubuntu 19.04 libssl1.1 update breaks Domoticz

### ISSUE THREAD

**Issue by sz4bi** [domoticz/domoticz#3168]
after release update from 18.10 to 19.04 domoticz not starting anymore because of missing libs

`domoticz: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

ubuntu 19.04 uses `libssl1.1` while 18.10 uses `libssl1.0` 
manually copying 18.10 libs (`libcrypto.so.1.0.0` and `libssl.so.1.0.0`) from libssl1.0 package to /usr/lib/x86_64-linux-gnu fixes it, domoticz start normally

symlinking libcrypto.so.1.0.0 and libssl.so.1.0.0 to libcrypto.so.1.1 and libssl.so.1.1 is not working

similar issue #3155

**Comment by gizmocuz** [comment]
Please continue at #3155
