### ISSUE TITLE
Default installation directory issue

### ISSUE THREAD

**Issue by IanDury** [domoticz/domoticz#317]
"make install" used to install in /opt/domoticz but with the latest beta r4088 it now installs in the default cmake_install_prefix /usr/local directory.

The change causing this is in the file domoticz/CMakeLists.txt:
set(CMAKE_INSTALL_PREFIX "/opt/${CPACK_PACKAGE_NAME}" CACHE PATH "Install path prefix, prepended onto install directories.")

This used to be:
set(CMAKE_INSTALL_PREFIX "/opt/${CPACK_PACKAGE_NAME}" CACHE PATH "Install path prefix, prepended onto install directories." FORCE)

Apparently the FORCE option is needed to overwrite existing entries.

**Comment by gizmocuz** [comment]
Thanks, i will add this change in the next commit

**Comment by IanDury** [comment]
Thanks!
