### ISSUE TITLE
After Update to last beta CheckAuthToken

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#3171]
I have issue after last Update 

CheckAuthToken(ID=3cftzehhehehhejje40edbb77c36342b1a_MGRjMjfjfhhfhhdbfNy00Yzc3LThmMTMtYzJmNjhkZGVmMWE4) : session id not found

**Comment by gizmocuz** [comment]
Did you try logging in/out ? Made some changes, and the session name has changed

**Comment by gizmocuz** [comment]
I see a possible issue... one moment

**Comment by salopette** [comment]
I do not have login in my domoticz.

**Comment by gizmocuz** [comment]
Please try the new beta ( 10674)

**Comment by salopette** [comment]
Thx.
It works again!

**Comment by gizmocuz** [comment]
Thanks for your help!

**Comment by LiloBzH** [comment]
same problem on new stable version ... :(

**Comment by LiloBzH** [comment]
i have update with last Beta version and it's ok.
I come back on Stable channel with the next stable version !
