### ISSUE TITLE
COMMAND_CLASS_SENSOR_MULTILEVEL sensor types should not be identified using sensor labels

### ISSUE THREAD

**Issue by paalkr** [domoticz/domoticz#3173]
We are some users that have created a OZW configuration file for the 1.92 firmware for the Heatit 021 Thermostat (https://www.heatit.com/heating-control/floor-heating-thermostats/heatit-z-wave-thermostat/). The new 1.92 firmware and also the new hardware versions (https://www.heatit.com/heating-control/floor-heating-thermostats/heatit-z-trm2fx/) of the thermostat does support several temperature sensors using Multi Channel Command Class (Multichannel encapsulation). Ideally we would like to give each sensor the correct label (floor, external, internal) in the OZW database file, but then Domoticz fails to import the sensors because the Label is no longer Temperature.

All details and suggestions from the OZW maintainers are available here
https://github.com/OpenZWave/open-zwave/pull/1758

**Comment by gizmocuz** [comment]
Thanks for the heads up, i will work on this after a new release...,
