### ISSUE TITLE
Error with compile / make with new boost 1.70 (wiki steps)

### ISSUE THREAD

**Issue by mcmikev** [domoticz/domoticz#3174]
Just updated my rpi3 using the steps on the wiki build from source. 
Updated boost from 1.6 to 1.7 version and now unaniem to build. 

Error below comes right after the make command. 
Did an make clean already but did not help. 

Found boost_headers 1.70.0 at /usr/local/lib/cmake/boost_headers-1.70.0
-- Found boost_thread 1.70.0 at /usr/local/lib/cmake/boost_thread-1.70.0
--   libboost_thread.a
-- Adding boost_thread dependencies: headers
-- Found boost_system 1.70.0 at /usr/local/lib/cmake/boost_system-1.70.0
--   libboost_system.a
-- Adding boost_system dependencies: headers
-- Boost  found.
-- Found Boost components:
   thread;system
-- Linking against boost static libraries
CMake Error at CMakeLists.txt:589 (message):
  Found libBoost version 1.70.0, 106000 or newer required

**Comment by gizmocuz** [comment]
Noticed as well... seems possible that CMake needs to be updated...

**Comment by mcmikev** [comment]
To what version? Or is it under investigation?

**Comment by gizmocuz** [comment]
Has to be investigated..

**Comment by harryd100** [comment]
I am building domoticz on a new Linux platform Ubuntu 18.04-2 LTS and experience the same issue following the Wiki.

-- Found boost_headers 1.70.0 at /usr/local/lib/cmake/boost_headers-1.70.0
-- Found boost_thread 1.70.0 at /usr/local/lib/cmake/boost_thread-1.70.0
--   libboost_thread.a
-- Adding boost_thread dependencies: headers
-- Found boost_system 1.70.0 at /usr/local/lib/cmake/boost_system-1.70.0
--   libboost_system.a
-- Adding boost_system dependencies: headers
-- Boost  found.
-- Found Boost components:
   thread;system
-- Linking against boost static libraries
CMake Error at CMakeLists.txt:589 (message):
  Found libBoost version 1.70.0, 106000 or newer required

**Comment by mcmikev** [comment]
Does the wiki has to be rolled back to the old info or can we expect a resolution for this error soon. Unable to build and update and test now.

**Comment by gizmocuz** [comment]
The wiki has already been taken care of until we know how to solve this.
It's not a Domoticz issue only, hope you googled as well
The wiki/CMakeList file will be updated to use version 70 (or 71) when possible

**Comment by gizmocuz** [comment]
I think i found a way to compile with 1.70 !

Please see the new instructions at:

https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source

Could you verify them ?

**Comment by rwaaren** [comment]
#identify boost stuff
sudo apt list --installed | grep boost
#remove old boost stuff
sudo apt remove libboost*

#Build & Install new Boost Libraries as per the wiki
#compiled new cmake as per the wiki
#after installing cmake 
sudo hash -r
cd beta
sudo git pull
sudo make  # failed (referring to old version)
sudo cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt  # 
sudo make  # busy now and will take some hours. Come back when finished

**Comment by gizmocuz** [comment]
@rwaaren , 'sudo make' ? sudo 'cmake' ? you should not run those commands as 'sudo'
Please follow the wiki

**Comment by mcmikev** [comment]
I am building now. So far so good !!

**Comment by mcmikev** [comment]
get more errors than before 

`[ 22%] Building CXX object CMakeFiles/domoticz.dir/main/EventSystem.cpp.o
In file included from /usr/include/c++/6/map:60:0,
                 from /home/pi/dev-domoticz/main/stdafx.h:47:
/usr/include/c++/6/bits/stl_tree.h: In member function ‘std::pair<std::_Rb_tree_node_base*, std::_Rb_tree_node                                                          _base*> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_get_insert_hint_unique_pos(std::_Rb_tree<                                                          _Key, _Val, _KeyOfValue, _Compare, _Alloc>::const_iterator, const key_type&) [with _Key = long long unsigned i                                                          nt; _Val = std::pair<const long long unsigned int, CEventSystem::_tUserVariable>; _KeyOfValue = std::_Select1s                                                          t<std::pair<const long long unsigned int, CEventSystem::_tUserVariable> >; _Compare = std::less<long long unsi                                                          gned int>; _Alloc = std::allocator<std::pair<const long long unsigned int, CEventSystem::_tUserVariable> >]’:
/usr/include/c++/6/bits/stl_tree.h:1928:5: note: parameter passing for argument of type ‘std::_Rb_tree<long lo                                                          ng unsigned int, std::pair<const long long unsigned int, CEventSystem::_tUserVariable>, std::_Select1st<std::p                                                          air<const long long unsigned int, CEventSystem::_tUserVariable> >, std::less<long long unsigned int>, std::all                                                          ocator<std::pair<const long long unsigned int, CEventSystem::_tUserVariable> > >::const_iterator {aka std::_Rb                                                          _tree_const_iterator<std::pair<const long long unsigned int, CEventSystem::_tUserVariable> >}’ will change in                                                           GCC 7.1
     _Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6/bits/stl_tree.h: In function ‘std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::ite                                                          rator std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_emplace_hint_unique(std::_Rb_tree<_Key, _Va                                                          l, _KeyOfValue, _Compare, _Alloc>::const_iterator, _Args&& ...) [with _Args = {const std::piecewise_construct_                                                          t&, std::tuple<const long long unsigned int&>, std::tuple<>}; _Key = long long unsigned int; _Val = std::pair<                                                          const long long unsigned int, int>; _KeyOfValue = std::_Select1st<std::pair<const long long unsigned int, int>                                                           >; _Compare = std::less<long long unsigned int>; _Alloc = std::allocator<std::pair<const long long unsigned i                                                          nt, int> >]’:
/usr/include/c++/6/bits/stl_tree.h:2193:7: note: parameter passing for argument of type ‘std::_Rb_tree<long lo                                                          ng unsigned int, std::pair<const long long unsigned int, int>, std::_Select1st<std::pair<const long long unsig                                                          ned int, int> >, std::less<long long unsigned int>, std::allocator<std::pair<const long long unsigned int, int                                                          > > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const long long unsigned int, int> >}’ will                                                           change in GCC 7.1
       _Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/6/map:61:0,
                 from /home/pi/dev-domoticz/main/stdafx.h:47:
/usr/include/c++/6/bits/stl_map.h: In member function ‘void CEventSystem::GetCurrentMeasurementStates()’:
/usr/include/c++/6/bits/stl_map.h:483:4: note: parameter passing for argument of type ‘std::_Rb_tree<long long                                                           unsigned int, std::pair<const long long unsigned int, int>, std::_Select1st<std::pair<const long long unsigne                                                          d int, int> >, std::less<long long unsigned int>, std::allocator<std::pair<const long long unsigned int, int>                                                           > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const long long unsigned int, int> >}’ will ch                                                          ange in GCC 7.1
    __i = _M_t._M_emplace_hint_unique(__i, std::piecewise_construct,
    ^~~
/usr/include/c++/6/bits/stl_map.h:483:4: note: parameter passing for argument of type ‘std::_Rb_tree<long long                                                           unsigned int, std::pair<const long long unsigned int, int>, std::_Select1st<std::pair<const long long unsigne                                                          d int, int> >, std::less<long long unsigned int>, std::allocator<std::pair<const long long unsigned int, int>                                                           > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const long long unsigned int, int> >}’ will ch                                                          ange in GCC 7.1
    __i = _M_t._M_emplace_hint_unique(__i, std::piecewise_construct,
    ^~~
`

**Comment by rwaaren** [comment]
Compiled, linked and tested. All seems to work. But as @gizmocuz mentioned I use sudo on some of the steps.
Did the steps again and compiling now as std user.

**Comment by gizmocuz** [comment]
@mcmikev , those are warnings and not errors

@rwaaren , thanks for testing... the build systems now also use boost 1.70 and the new methods

Closing issue
