### ISSUE TITLE
evohome device in dashboard

### ISSUE THREAD

**Issue by fullTalgoRythm** [domoticz/domoticz#3178]
There seems to be some discussion about the evohome controller device in the dashboard. Code is currently commented out over classification of the device. The evohome controller device was copied from the security panel and therefore follows the same template. They are both switches and both have a separate place in the dashboard. This was never correct but was simply done out of consistency with the existing code base.

Personally I would want separate customisable groups / tabs such as heating and security. These may have devices from the other tabs included as appropriate. I wouldn't personally want all temperature devices just the ones that relate to room heating. I'm sure this has already been discussed and suggested but was deemed too much work at the moment.

My comment is that it seems a bit churlish to remove working code over the grouping structure which will never be correct for everyone. I think at least you would also have to remove the security panel as well as surely that is also in the wrong place?

**Comment by gizmocuz** [comment]
We already have 'rooms' where you can place your devices in.. ain't that the same ?
You could maybe add an option for a custom tab linked to a roomplan so this only shows the devices from that roomplan ?

**Comment by fullTalgoRythm** [comment]
Previously in the dashboard I got the evohome device and temperature devices. I could then select a room with just the heating devices in it. At the moment the evohome device is commented out of the dashboard so it won't display at all i.e. it's broken. The dashboard has a cut down ui for evohome so this was not really the same but it did use to work. We went through this discussion in the past when the code was introduced and because all the evohome relays are under lighting and switches as well as all the security stuff you agreed that would be ok. At the moment though you have commented out the evohome device from the dashboard and said to move it to utility which as mentioned is not we previously discussed. I'm just trying to get evohome device back in the dashboard, surely if people don't like which category or whatever we can just tell them the above about using the 'rooms'. Wouldn't it be better to have a working feature for some people rather than completely broken?

**Comment by dannybloe** [comment]
As as side note: I really think we should have intrinsic support for a dedicated tab in the UI for the heating system. Many other domotica apps already have that. It is such a fundamental part of a smart home that it definitely favour for such a section. Every smart house has smart heating and you definitely don't want the controls for them scattered around other tabs like switches or utilities in general. A roomplan is orthogonal to that. It's not the same. (besides, right now, the roomplan is being misused as a grouping mechanism and should not be as a group != room but a room == group. Just two different things, which is not a good thing UI/concept wise.) 
So, if you ask me, maybe it is a good thing to start doing this right and come up with an initial concept of a heating section which has sections for the controller(s), the zones, the heating program/scheduling etc. Perhaps look to how others are doing this (e.g. https://manuals.fibaro.com/knowledge-base-browse/heating-panel-in-fibaro-home-center/)

(And as I said above, this is totally not the same as a roomplan).

**Comment by gizmocuz** [comment]
We can do it both ways... i also want to support separate tabs, but for this we need to be able to render the widgets independently. Currently the code to render a temperature widget is in the temperature controllers/templates.

@dannybloe , Zones are rooms (roomplans) we already support those
Timers for a SetPoint devices could look like this, but someone has to build it.
Same for Lights/Switches, this could be enriched a bit as well

But currently this is not yet supported.
For now @fullTalgoRythm, you could use the custom template option and build a evohome gui.
When this is working great, i should be able to link this to the hardware and be able to display this in it's own tab.
There is already an idea that each hardware could provide it's own HTTP code

**Comment by fullTalgoRythm** [comment]
Ok that's good in the long term but what I wanted to get back in the short term is the evohome device in the dashboard. It was in there without any issues for about 3-4 years but now it's gone over some category issue but doesn't sound like a quick fix to me. Really my suggestion is just to bring it back for now, it's just the same as the security panel anyway. I can send a pull request but only if you're happy to merge it back again?

**Comment by gizmocuz** [comment]
I have no idea what you are referring about the security panel ?

**Comment by TheUlpio** [comment]
I think he (and me too) is simply asking to re enable the evohome device in the dashboard. Actually if I click on the star in the control (in the switches tab):
![image](https://user-images.githubusercontent.com/13163959/154806177-7e3359a5-431a-4b76-b2c8-12c007b6c706.png)
it turns yellow, but the control does not appear in the dashboard like everyone else does. The "add to panel" star icon, in this case, does nothing.
This is useful to set globally (not setpoints) the state (e.g. day off, normal, etc.) without navigate to the stitches tab
