### ISSUE TITLE
Barometer rounding

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#3183]

**Comment by SargonofAssyria** [comment]
Domoticz version 4.10602
A MQTT message comes in: 
`MQTT: Topic: domoticz/in, Message: {"idx":149,"nvalue":0,"svalue":"24.9;38.6;2;1015.8;5","Battery":200,"RSSI":5}`
The value in Domoticz gets rounded.
`Temp + Humidity + Baro | THB1 - BTHR918, BTHGN129 | 24.9 C, 38 %, 1016 hPa`
The normal Barometer device does not get rounded.
`General | Barometer | 1015.8 hPa`
Please make at least 1 decimal available in the "THB1 - BTHR918, BTHGN129" device.

**Comment by gizmocuz** [comment]
i think the problem could be in MainWorker.cpp, line 13412

`if (subType == sTypeTHBFloat)`

Could you try to always use it as a float and check if that solved the issue ?

**Comment by SargonofAssyria** [comment]
I would love to, but I don't exactly know what you mean.
I am talking about a Virtual Device which in the database has type 84 and subtype 1 created by Domoticz

**Comment by gizmocuz** [comment]
Do you compile domoticz yourself ? Then open a text editor and adjust the code at the mentioned location
make it 'if (1==1)' for example
If you do not compile yourself, can you try to compile yourself ?

**Comment by SargonofAssyria** [comment]
Current I cannot compile it myself, I look into it and try to compile it with Visual Studio Code.
Would it be possible to compile on Windows for Raspberry?
I will compile it on Raspberry, will take some time.

**Comment by rwaaren** [comment]
local compiled with (1==1), the value is stored with 1 decimal in the database. Gui still shows the  "chopped" value;  meaning 1016.8 shows as 1016 
Local compiled Beta without change (1 == 1) store rounded value in database.

**Comment by gizmocuz** [comment]
@rwaaren , thanks for testing! The only Temp+Hum+Baro type that supports a float is subtype 0x10 (sTypeTHBFloat)
We could use this as default in dummy.cpp

**Comment by SargonofAssyria** [comment]
@rwaaren Tnx, for testing, my compile ended in an error of TCPClient.cpp.o

**Comment by kofec** [comment]
Take one commit less

**Comment by kofec** [comment]
Take one commit less

**Comment by gizmocuz** [comment]
@kofec , latest code should work again... why an old file got committed is still a puzzle to me
