### ISSUE TITLE
EcoCompteur does not read specified port

### ISSUE THREAD

**Issue by cryptax** [domoticz/domoticz#3184]
The support for "EcoCompteur Legrand with LAN interface" gets an URL and a port from the end-user. However, the code (`https://github.com/domoticz/domoticz/blob/development/hardware/EcoCompteur.cpp`) does not take the port into account.

I think the following lines should be changed to include `m_port`:

```c++
void CEcoCompteur::GetScript()
{
	// Download instantaneous wattage
	std::string sInst;
	std::string sUrl = m_url + "/inst.json";
	if (!HTTPClient::GET(sUrl, sInst))
	{
		_log.Log(LOG_ERROR, "EcoCompteur: Error getting 'inst.json' from url : " + m_url);
		return;
	}

	// Download hourly report
	std::string sLog2;
	sUrl = m_url + "/log2.csv";
        if (!HTTPClient::GET(sUrl, sLog2))
```

Probably, if `m_port` is set, it ought to be:

```c++
std::string sUrl = m_url + ":" + m_port + "/inst.json";
```

**Comment by gizmocuz** [comment]
Thanks for reporting, Fixed in next beta/release
