### ISSUE TITLE
Domoticz fail to login after upgrade to 4.10659

### ISSUE THREAD

**Issue by numanx11** [domoticz/domoticz#3185]
After upgrading to latest stable version on my RaspberryPi I can't login anymore.
The webpage shows Domoticz Offline.
The logs shows Error: CheckAuthToken(ID=**RANDOM HASH**) : session id not found.

I can log in if I start domoticz with -nowwwpwd

It seems that I am not the only one with this issue:  https://www.domoticz.com/forum/viewtopic.php?f=3&p=213607&sid=4e5d61334e3e1c1a156f11d899223bc2#p213607

**Comment by annegerben** [comment]
same here

**Comment by gizmocuz** [comment]
Already reported here... please use the search option, or just check the latest issues

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/issues/3123#issuecomment-489640454

**Comment by GASOLINE** [comment]
If I reset passwd I can login again:

**Resetting the Website Username/Password**

_To reset the website username/password in case this is lost there are two options.

-     Specify –nowwwpwd as command line argument
-     Place a file labeled ‘resetpwd’ inside the root Domoticz installation folder. 

Each minute the existence of this file is checked, and if found the Username/Password is reset and the file is removed._
