### ISSUE TITLE
Camera Stream url api [Feature Request]

### ISSUE THREAD

**Issue by DewGew** [domoticz/domoticz#3186]
Is it possible to add options to use video mjpeg url instead of frame by frame. Then use this thrue API. 

Even nicer would be to convert video url to hls stream for cast to TV with chromecast

**Comment by gizmocuz** [comment]
If you would like to contribute this, that would be great !
Please make it platform independent. (Windows/Linux)

At the moment we poll the JPEG as fast as possible, resulting in motion... like a motion jpeg
Also this has the benefit it will display everywhere and if you have a slow connection, it's polled slower

**Comment by DewGew** [comment]
I dont know anything about C++. Just some python and javascript.

**Comment by xztraz** [comment]
if domoticz should be able to run mjpeg streams or h264 it's going to use a lot of recources. you can't just throw away frames in a stream like that. an rpi would be to slow.  but a sollution ish cold be to just pass along the url for the stream directly to the browser on the custom page. but then you would loose functionality like snapshots. or use aurora skin with an iframe and put your mjpeg stream in that

**Comment by DewGew** [comment]
I don’t Know how it works but Home assistant has function to cast camera to chromecast via Google assistant. This is what I am looking for.

**Comment by DewGew** [comment]
It's not needed to stream in domticz ui. Its only needed  to cast to chromecast.

**Comment by xztraz** [comment]
that sounds like it's just passing along an url to chromecast. you could probably do that with a script. have you had a look at the chromecast plugin?

**Comment by xztraz** [comment]
did you test that? can you close this?

**Comment by DewGew** [comment]
> did you test that? can you close this?

I need URL from camera with any of those formats to send to chromecast (Google Assistant):
HLS (HTTP Live Streaming)
DASH (Dynamic Adaptive Streaming over HTTP)
Smooth Streaming
Progressive MP4

It need to convert from motion jpg or mjpeg etc.

**Comment by DewGew** [comment]
Solved this with a another software. Now I can send my cameras to chromecast with Google assistant with my Python script https://github.com/DewGew/Domoticz-Google-Assistant
