### ISSUE TITLE
Issue with btn-group

### ISSUE THREAD

**Issue by landaisbenj** [domoticz/domoticz#3187]
In default theme visual we have this: 
![image](https://user-images.githubusercontent.com/32144431/57310674-78a13600-70ea-11e9-9850-24f0a7a39356.png)
it's because of this:
![image](https://user-images.githubusercontent.com/32144431/57310714-8c4c9c80-70ea-11e9-9389-4da8f20b9550.png)

with :
```
btn-group {
display: block;
}
```

we have this:

![image](https://user-images.githubusercontent.com/32144431/57310901-ea797f80-70ea-11e9-9622-cf60b7dcf271.png)

**Comment by gizmocuz** [comment]
Solved it in a different way as you do not want to modify the btn-group style as it is used elsewhere too.
But shortening your labels also solves your problem

**Comment by landaisbenj** [comment]
[EDIT] Ok i don't saw your hardcoded comit...

Thanks for your reply. Maybe you can do this in add a more targeted css selector like this:

```
.btn-group[id^="selector"] {
}
```
I don't know other collateral.

And i can't shortening labels on this system labels:
![image](https://user-images.githubusercontent.com/32144431/57445758-52e37080-7253-11e9-94b5-111efddc04ae.png)
So maybe you can add a scroll ? :
```
.btn-group[id^="selector"] {
    overflow-x: auto;
}
```
  make this:
![image](https://user-images.githubusercontent.com/32144431/57447546-a35ccd00-7257-11e9-8859-63a221a8ba4f.png)

**Comment by gizmocuz** [comment]
@landaisbenj , seems you know what you are doing here ! Nice ...
So please create  pull request for this (revert my patch too)
Could you tweak the scrollbar as well to have it look at bit nicer?
(https://github.com/utatti/perfect-scrollbar)

**Comment by landaisbenj** [comment]
I know css, but i think i do not have all the view on the project. 

I can try to revert your patch and make a css selector, but i don't know how to implement your scrollbar plugin. Maybe you know one who can make this ?

**Comment by waltervl** [comment]
No feedback, closing this
