### ISSUE TITLE
Domoticz not building on latest commit 8ecc171

### ISSUE THREAD

**Issue by remcom** [domoticz/domoticz#3189]
Latest version from git (8ecc171) compiles with the following errors

`/home/remco/domoticz/tcpserver/TCPClient.cpp:115:1: error: prototype for ‘tcp::server::CSharedClient::CSharedClient(tcp::server::CTCPServerIntBase*, http::server::CProxyClient*, const string&, const string&)’ does not match any in class ‘tcp::server::CSharedClient’
 CSharedClient::CSharedClient(CTCPServerIntBase *pManager, http::server::CProxyClient *proxy, const std::string &token, const std::string &username) :
 ^~~~~~~~~~~~~
In file included from /home/remco/domoticz/tcpserver/TCPClient.cpp:2:0:
/home/remco/domoticz/tcpserver/TCPClient.h:63:7: error: candidates are: tcp::server::CSharedClient::CSharedClient(const tcp::server::CSharedClient&)
 class CSharedClient : public CTCPClientBase,
       ^~~~~~~~~~~~~
/home/remco/domoticz/tcpserver/TCPClient.h:67:2: error:                 tcp::server::CSharedClient::CSharedClient(tcp::server::CTCPServerIntBase*, std::shared_ptr<http::server::CProxyClient>, const string&, const string&)
  CSharedClient(CTCPServerIntBase *pManager, std::shared_ptr<http::server::CProxyClient> proxy, const std::string &token, const std::string &username);
`

**Comment by rwaaren** [comment]
Same on Raspberry PI-3 Debian stretch, Boost version: 1_68
g++ (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516
Fresh clone of development branch  

```
git log
commit 8ecc1716ea74c4db98b4f426d852469a71cdd340


    Reverting changing from last build (...w?)

commit 7a483bb3810bda8219b070128a21b492fbd91a44

    - Fixed: issue with Session ID/Login
    - Appveyor, release build now also using VS2019

```
after
git rebase -i dba7797c75d6e35d9ac523a70729372a79c1d16e
and dropping last 2 commits
make works again

**Comment by gizmocuz** [comment]
I think something went wrong in the last two commits somehow...
Old file where committed somehow.
Should be fixed again, thanks for reporting!
