### ISSUE TITLE
DzVents HTTPResponse.lua always returns status code of 0

### ISSUE THREAD

**Issue by derekoharrow** [domoticz/domoticz#3191]
With the latest developer release of Domoticz (v4.10705), the HTTPResponce function in dzvents/runtime/HTTPResponse.lua always returns a statusCode of 0, and .ok of false.

I've tried some debug statements in this code and it does appear that responseData.headers is being set, as is responseData.data, but responseData.statusCode always seems to be 0.

This means that any dzVents HTTP callback requests that check for item.ok, or item.statusCode fail.

**Comment by gizmocuz** [comment]
@rwaaren , is it possible you could have a peak at this ?

**Comment by rwaaren** [comment]
Will have a look. Probably tomorrow.

**Comment by derekoharrow** [comment]
I did have a look at HTTPResponse.lua and couldn't see any issues there. It seems like the responseData being passed to HTTPResponce when it's called doesn't include/set statusCode. 
With my somewhat limited LUA development skill set, I couldn't quite work out what was calling HTTPResponce or setting the responseData

**Comment by rwaaren** [comment]
I assume this is the same as [this forum post ](https://www.domoticz.com/forum/viewtopic.php?f=59&t=27853 ) ?

**Comment by gizmocuz** [comment]
@rwaaren , i think so

I have verified the C++ code, and the statusText/Code are correctly being push

I added the dump table as you asked on the forum this is the result:

> 2019-05-09 08:12:16.215  Status: dzVents: Info:  dumping item table:
> 2019-05-09 08:12:16.215  Status: dzVents: > ok: false
> 2019-05-09 08:12:16.215  Status: dzVents: > isDevice: false
> 2019-05-09 08:12:16.216  Status: dzVents: > protocol: HTTP/1.1
> 2019-05-09 08:12:16.216  Status: dzVents: > isScene: false
> 2019-05-09 08:12:16.216  Status: dzVents: > data:
> 2019-05-09 08:12:16.216  Status: dzVents: > isSecurity: false
> 2019-05-09 08:12:16.217  Status: dzVents: > trigger: mycallbackstring
> 2019-05-09 08:12:16.217  Status: dzVents: > isHTTPResponse: true
> 2019-05-09 08:12:16.217  Status: dzVents: > callback: mycallbackstring
> 2019-05-09 08:12:16.217  Status: dzVents: > isTimer: false
> 2019-05-09 08:12:16.217  Status: dzVents: > isGroup: false
> 2019-05-09 08:12:16.218  Status: dzVents: > baseType: httpResponse
> 2019-05-09 08:12:16.218  Status: dzVents: > isVariable: false
> 2019-05-09 08:12:16.218  Status: dzVents: > statusText: Couldn't connect to
> 2019-05-09 08:12:16.218  Status: dzVents: > statusCode: 7
> 2019-05-09 08:12:16.218  Status: dzVents: > headers:
> 2019-05-09 08:12:16.219  Status: dzVents: > _contentType:
> 2019-05-09 08:12:16.219  Status: dzVents: > isJSON: false
> 2019-05-09 08:12:16.220  Status: dzVents: Info:  ------ Finished Script #1
> 

Seems perfect here .... this is an internal curl error when i entered a wrong port number to connect to

Here is the dump when i push data to an influxDB:

> 2019-05-09 08:14:00.708  Status: dzVents: Info:  dumping item table:
> 2019-05-09 08:14:00.708  Status: dzVents: > isTimer: false
> 2019-05-09 08:14:00.709  Status: dzVents: > data:
> 2019-05-09 08:14:00.709  Status: dzVents: > isScene: false
> 2019-05-09 08:14:00.710  Status: dzVents: > isGroup: false
> 2019-05-09 08:14:00.710  Status: dzVents: > isVariable: false
> 2019-05-09 08:14:00.711  Status: dzVents: > isDevice: false
> 2019-05-09 08:14:00.711  Status: dzVents: > ok: true
> 2019-05-09 08:14:00.712  Status: dzVents: > baseType: httpResponse
> 2019-05-09 08:14:00.712  Status: dzVents: > statusText: No Content
> 2019-05-09 08:14:00.713  Status: dzVents: > isHTTPResponse: true
> 2019-05-09 08:14:00.716  Status: dzVents: > _contentType: application/json
> 2019-05-09 08:14:00.717  Status: dzVents: > isJSON: false
> 2019-05-09 08:14:00.717  Status: dzVents: > isSecurity: false
> 2019-05-09 08:14:00.718  Status: dzVents: > trigger: mycallbackstring
> 2019-05-09 08:14:00.718  Status: dzVents: > callback: mycallbackstring
> 2019-05-09 08:14:00.719  Status: dzVents: > statusCode: 204
> 2019-05-09 08:14:00.719  Status: dzVents: > protocol: HTTP/1.1
> 2019-05-09 08:14:00.720  Status: dzVents: > headers:
> 2019-05-09 08:14:00.720  Status: dzVents: >     X-Influxdb-Version: 1.5.3
> 2019-05-09 08:14:00.720  Status: dzVents: >     Request-Id: a4e6275d-7221-11e9-acd7-000000000000
> 2019-05-09 08:14:00.721  Status: dzVents: >     Content-Type: application/json
> 2019-05-09 08:14:00.721  Status: dzVents: >     X-Request-Id: a4e6275d-7221-11e9-acd7-000000000000
> 2019-05-09 08:14:00.722  Status: dzVents: >     Date: Thu, 09 May 2019 06:14:03 GMT
> 2019-05-09 08:14:00.722  Status: dzVents: >     X-Influxdb-Build: OSS
> 2019-05-09 08:14:00.724  Status: dzVents: Info:  ------ Finished Script #1
>

**Comment by derekoharrow** [comment]
> I assume this is the same as [this forum post ](https://www.domoticz.com/forum/viewtopic.php?f=59&t=27853) ?

Yes, it is. I posted there first before I found the GitHub repo.

**Comment by derekoharrow** [comment]
I've posted the requested debug info on [the domoticz forum](https://www.domoticz.com/forum/viewtopic.php?f=59&t=27853&p=213937#p213937)

**Comment by gizmocuz** [comment]
@derekoharrow, lets continue here for a bit as we else need to check on two locations

could you login in your raspberry and issue

curl -I -H "Testing: Test header so you see this works" http://www.google.com

Do you see a line returned with

`HTTP/1.1 200 OK`

Is it on the first line ?

could you issue the curl command to the URL you are calling from your script,
do you also get a line back

`HTTP/1.x 200 OK`

Or at least a line starting with HTTP/1.....

Is it on the first line ?

Not that we should scan the result only on the first line, but it is currently mandatory that there is a line returned with 

> HTTP/1.xxxx

Could you also state again your current beta domoticz version?

**Comment by derekoharrow** [comment]
Domoticz v4.10705 

```
pi@domoticz:~$ curl -I -H "Testing: Test header so you see this works" http://www.google.com
HTTP/1.1 200 OK
...
```

The URL I'm calling is part of the TADO API, and it doesn't work if I use the -I. Using -v for verbose returns:
```
 curl -v  "https://my.tado.com/api/v2/me" -H "Authorization: Bearer `cat /var/tmp/tadotoken`"
*   Trying 52.50.88.181...
* TCP_NODELAY set
* Connected to my.tado.com (52.50.88.181) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.tado.com
*  start date: Sep  3 00:00:00 2018 GMT
*  expire date: Oct  3 12:00:00 2019 GMT
*  subjectAltName: host "my.tado.com" matched cert's "*.tado.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x637ea8)
> GET /api/v2/me HTTP/1.1
> Host: my.tado.com
> User-Agent: curl/7.52.1
> Accept: */*
> Authorization: Bearer #########################
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< date: Thu, 09 May 2019 10:11:36 GMT
< content-type: application/json;charset=UTF-8
< set-cookie: AWSALB=iHkRQl6k+mKbw6bjfveMjIujYVQWmw4siS8W2tBf4grRK16wcVboZM8O9pUH4MsksZrtMFvsBPnd7AjgbKlsKEKKqdAh/E7pmFr201VDpLvedfFUSjShmkyOK01H; Expires=Thu, 16 May 2019 10:11:36 GMT; Path=/
< server: nginx
< access-control-allow-origin: *
< x-application-context: application:production
< etag: W/"b2e604df1e6e871c"
< cache-control: no-cache, must-revalidate
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000
<
* Curl_http_done: called premature == 0
* Connection #0 to host my.tado.com left intact
{"name":"Derek ","email":"derek@##########","username":"derek@##########","id":"##########","homes":[{"id":######,"name":"Home"}],"locale":"en_GB","mobileDevices":[{"name":"Dereks S8+","id":######,"settings":{"geoTrackingEnabled":true},"location":{"stale":false,"atHome":true,"bearingFromHome":{"degrees":#######,"radians":######},"relativeDistanceFromHomeFence":0.0},"deviceMetadata":{"platform":"Android","osVersion":"9","model":"Samsung_SM-G955F","locale":"en"}}]}
```

As you can see, there is an HTTP/2 200 in there.

The code was working fine on the previous stable (4.9700) and hasn't been changed for the latest version.

**Comment by rwaaren** [comment]
Thx. From what I see here, it looks like you have a mismatch between the domoticz executable and HTTPResponse.lua 

The dzVents subdirectory must be aligned with the version of domoticz. 

Could it be that you updated the domoticz binary without aligning the dzVents subdrectory ? (This could happen when you compile locally and only copy the binary to your work directory)

**Comment by derekoharrow** [comment]
I initially used ./updaterelease to go to v4.10659, but I experience the repeated CheckAuth log file issue

I then used ./updatebeta to go to v4.10705 to get to where I am now.

What that did to dzVents, I've no idea!

How do I get the two to align now?

**Comment by rwaaren** [comment]
the ./updatebeta should do that.
The latest HTTPResponse.lua can be found in <domoticz dir>/dzVents/runtime and should be
```
local _  = require('lodash')
local utils = require('Utils')

local function HTTPResponce(domoticz, responseData)

	local self = {}
	 
	self.headers = responseData.headers or {}
	self.baseType = domoticz.BASETYPE_HTTP_RESPONSE
	self.data = responseData.data
	self._contentType = _.get(self.headers, {'Content-Type'}, '')
    
    self.isJSON = false

    self.statusText = responseData.statusText
    self.protocol = responseData.protocol
    self.statusCode = responseData.statusCode
    
    self.ok = ( self.statusCode >= 200 and self.statusCode <= 299 )
	
	self.isHTTPResponse = true
	self.isDevice = false
	self.isScene = false
	self.isGroup = false
	self.isTimer = false
	self.isVariable = false
	self.isSecurity = false

	self.callback = responseData.callback
	self.trigger = responseData.callback

	if (string.match(self._contentType, 'application/json') and self.data) then
		local json = utils.fromJSON(self.data)

		if (json) then
			self.isJSON = true
			self.json = json
		end
	end
	return self
end
return HTTPResponce

```

**Comment by derekoharrow** [comment]
p.s. I've just run ./updatebeta again, to go to v4.10715. It does list the dzVents files when running, but the issue still persists.

**Comment by derekoharrow** [comment]
My HTTPResponse.lua matches what you have pasted above.

**Comment by gizmocuz** [comment]
@derekoharrow , the curl command also works with tado

```
curl -I -H "Testing: Test header so you see this works" https://my.tado.com/api/v2/me
HTTP/2 401
date: Thu, 09 May 2019 10:42:46 GMT
content-type: application/json;charset=UTF-8
set-cookie: AWSALB=6hSkNR62tvrey/z7tr9pc/nsAngqko6vGE46uI3zNqYST2wkeUoA03B/CJhCFKB9bNvnW+uHbgdzmHDkVt+VSO6/8U6NKK/p8kD4t0JrT/N2OSy/H4Q5w8bTmLlc; Expires=Thu, 16 May 2019 10:42:46 GMT; Path=/
server: nginx
access-control-allow-origin: *
strict-transport-security: max-age=31536000
```

@rwaaren , i think i found the problem, there is no reason for the error returned after 404 !
Strange, but i guess it's a private server develpment

One moment i make a patch for this

**Comment by gizmocuz** [comment]
@derekoharrow , could you re-run ./updatebeta
Version 10716 should solve it

**Comment by derekoharrow** [comment]
Yes! That's fixed it!
Thank you for all your help, and for fixing it so quickly.

**Comment by rwaaren** [comment]
> @rwaaren , i think i found the problem, there is no reason for the error returned after 404 !
> One moment i make a patch for this

Thx , guess I should re-read the book about defensive programming again !

**Comment by gizmocuz** [comment]
Great it's solved, thanks all for the help ;)

@rwaaren , always a nice read... but RFC 2616 section "**6.1 Status-Line**" and "**6.1.1 Status Code and Reason Phrase**" clearly states that it should be in this format.
The webserver tado is using (might be it's own development) is not providing the "**Reason-Phrase**"
Anyways, it's solved! ;)
