### ISSUE TITLE
log broken for "scale" virtual sensor

### ISSUE THREAD

**Issue by PatrBal** [domoticz/domoticz#3192]
domoticz v4.10706 on MacOS.
I have 2 virtual sensors that are updated every minute by a script using the API/JSON url.
One is a temperature sensor and the other one is a "scale" sensor displaying a weight in kg.
Values appear correctly in the dashboard.

 When I click on "log" in the temperature sensor, the history is displayed as expected. 

When I click on "log" in the scale sensor, the history page is always empty :

<img width="1354" alt="Screenshot 2019-05-08 at 20 21 44" src="https://user-images.githubusercontent.com/44707588/57398300-f474ae80-71ce-11e9-9b45-8a8c1e922d69.png">

Any idea?

**Comment by gizmocuz** [comment]
Thanks for reporting, fixed in next beta/release

**Comment by PatrBal** [comment]
Thanks, but it does not seem to be fixed. I have just created a new "scale" virtual sensor, updated it by the API/JSON url and looked at the log/history, which is still empty.

**Comment by gizmocuz** [comment]
Could you clear your browser cache + appcache and try again (or with a browser in private mode)

**Comment by PatrBal** [comment]
Yep! You are right. I did it and now, it works as expected. Thanks again!
