### ISSUE TITLE
Wrong error if setHue not in range

### ISSUE THREAD

**Issue by TAYALE** [domoticz/domoticz#3194]
In rgbw_device.lua:

`                        if not(hue) or not(inRange(hue, 0, 360)) then
                                domoticz.log('Brightness value need to be number from 0-100', utils.LOG_ERROR)
                                return false
                        end
`

The errormessage should not be about Brightness

**Comment by TAYALE** [comment]
Same is valid for setColor. There also wrong message about brightness.

**Comment by rwaaren** [comment]
You are right. Thx for reporting !
Will correct soon. #3196

**Comment by rwaaren** [comment]
#3196 was merged into development this morning
