### ISSUE TITLE
Issue with release package on github 10.717 (wrong commit hash same as 10.693)

### ISSUE THREAD

**Issue by kofec** [domoticz/domoticz#3197]
You are not lucky regarding the releases on github :-)
There is something wrong with this release probably you didn't change the commit  - both release 10.693 and 10.717 have the same hash 
https://github.com/domoticz/domoticz/commit/649306c4de2371177e186384874206c18e861f7c

So I see the same issues as for 10.693
Can you please regenerate/correct it.
Thanks in advance

**Comment by kofec** [comment]
One more thing I noticed. You didn't merge development to master - As you always did.

**Comment by gizmocuz** [comment]
What version does it display at the top ?

**Comment by gizmocuz** [comment]
I think it's the build hash from the development branch, i moved the development build files to the stable folder
Will update the master branch soon for when a new stable will be released

**Comment by tobbenb** [comment]
Could you delete the last release and redo it correctly, so the users of our docker container (linuxserver) can use their container again? 
Some users already updated to our stable 4.10659, then updated to stable 4.10717 and got an error that downgrading is not allowed.
Stable 4.10659 builds 4.10693.
Stable 4.10717 builds 4.10659.
So the newer version is in fact older, causing the database downgrade not allowed.
It's simple to delete the release and create a new release that use the correct commit.

**Comment by gizmocuz** [comment]
You mean in the GitHub releases section?

**Comment by tobbenb** [comment]
Yes. Go to the release and then push delete, then make a new release and then you should be able to choose commit i stead of a branch.

**Comment by gizmocuz** [comment]
@tobbenb , thanks should be solved now

**Comment by tobbenb** [comment]
Great. I'll trigger a manual build.
Thanks for the fix.
