### ISSUE TITLE
Can't add dummy devices

### ISSUE THREAD

**Issue by Calimerorulez** [domoticz/domoticz#32]
Hi,

I'm currently running 2879, and I'm not able to add dummy devices.

The hardware dummy device is addable, but dummy sensors can't be added... Domoticz says that they can be found in the devices (Apparaten) tab, but they aren't displayed or added.

**Comment by gizmocuz** [comment]
Did you enable accept new hardware in the settings?
Why don't you use our forum for these questions?

**Comment by Calimerorulez** [comment]
Sorry gizmocuz, that both wasn't clear to me.

**Comment by gizmocuz** [comment]
No problem. In the settings, you have to enable accept new hardware
We have a forum for questions
