### ISSUE TITLE
Log Graphs are not showing for all switches

### ISSUE THREAD

**Issue by derekoharrow** [domoticz/domoticz#3200]
Running v4.10717 on Raspberry Pi 3 (Jessie).

As per [this discussion ](https://www.domoticz.com/forum/viewtopic.php?f=6&t=27833)on the forum.

When you go to the switches page, and click on Log next to a switch you should get a graph of the switch status over time.

This is working for some switches, but not for others.

There doesn't seem to be any pattern between those that do and those that don't work. It doesn't seem to relate to a specific switch type (I have switches of the same type, some work some don't).

I've also tried clearing the switch history and leaving it some time to see if that makes a difference and it doesn't appear to.

It's not a browser cache issue - I've completely cleared the cache, tried in-cognito windows, different browsers, etc.

Multiple users are also reporting this, so it's not specific to me.

**Comment by kenmercer** [comment]
I'm also running 4.10717 and can confirm the problem. The log button for all my switches redirects to my dashboard which was blank until I cleared my firefox cache. Logs for my temperature sensors work correctly from the temperature page but, from my dashboard, show a blank dashboard: http://rpi.local:8080/#/Dashboard

**Comment by gizmocuz** [comment]
@kenmercer , please clear your browser cache + appcache, this is about the two new graphs at the top of the switch log (day/week), and has noting todo with dashboard/temperature switches

Going to have a look at this, maybe @stas-demydiuk you have an idea ?

**Comment by kenmercer** [comment]
Thanks, that's a big improvement. My multi level select switches now have a highlight in the selected position and I get temperature graphs from the dashboard, temperature and switch tabs. My fishtank switch log correctly shows it came on at 6pm tonight but not at 6.30am - 8am interval this morning although that is listed in the text log. That's in the new "Today" graph (looks nice). The older graph below is strange with a "square wave" and each entry on Jan1. My rice cooker runs from a 1 minute script and doesn't have any "on" in the graph (but it does in the text).

**Comment by GravityRZ** [comment]
also look at the problem i logged. i think it is related to this one. i do not have the problems regsarding the dashboard but logging is definately affected. somehow the new functionsality does not show anything and the old graphs below are wrong with time stamps al dated thursday jan 1, 01:00:00.000.
the last 3 digits increment .001, 002, 003 etc with each timestamp

**Comment by stas-demydiuk** [comment]
@GravityRZ I've create the #3206 PR to fix your issue
@gizmocuz could you please merge

**Comment by GravityRZ** [comment]
Thanks @stas-demydiuk 

does this fix also affect the graphs itself because at the moment the switching looks very repetitive while the actual switching moments are not.

**Comment by gizmocuz** [comment]
@stas-demydiuk , merged, thanks for the help !!

**Comment by GravityRZ** [comment]
Good work 
Thanks @stas-demydiuk @gizmocuz

tested it and it works. graphics above switch textlog now showing data. graph below texlog  looks good. date timestamp also working correctly.

Cosmatically:
one thing i noticed, the values, when 100% (eg virtual switch, fibaro on/off module, qubino on/off module) do not show 100% but 99% or 98%. this is regarding al the NON DIMMABLE switches either virtual or physical. maybe it is a rounded thing because i also have a virtual switch which does display 100%
![qubino switchlog 99](https://user-images.githubusercontent.com/16853535/57581141-c84d7c00-74b3-11e9-9860-71fc2f37fec5.png)

![fibaro switchlog 98](https://user-images.githubusercontent.com/16853535/57581144-cdaac680-74b3-11e9-8f4c-ee84dd2b3232.jpg)

![virtual switch 99](https://user-images.githubusercontent.com/16853535/57581160-18c4d980-74b4-11e9-9c57-93facd49ce82.jpg)

![virtualswitch 100](https://user-images.githubusercontent.com/16853535/57581168-1c586080-74b4-11e9-86df-f4be7ba7a7f4.jpg)

New comment
also the new graphs above textlog do not seem to register on dimmable hue lights 
i noticed these lights are switches on using a bash script(using curl which calls the hue scene from the hub directly).
it looks like the new graphs are not working when lights are switched on/off from a bash script

**Comment by gizmocuz** [comment]
> it looks like the new graphs are not working when lights are switched on/off from a bash script

I don't think this has anything to do with the charts...? If it is not registered in the text log, it will not display in the chart... quite easy...

**Comment by GravityRZ** [comment]
let me do some more testing but as far as i can tell  it registers in the text log, lower graph but not on the newer top graphs.

everything registers exept for the hue lights.
when i switch them on manually on/off the register.

i can upload pictores but what i see is clear.
hue lights are switched on, texlog and downgraph register the correct status but top graphs are blank

when i switch them off/on manually the do register in the top graph.
somehow i think the data from the top graph is not coming from the same source as the textlog

**Comment by kenmercer** [comment]
I thought I'd look in a copy of domoticz.db but couldn't open my devices page to get the IDs. Wondered if domoticz was running slow so:
pi@rpi:~/domoticz $ top | grep domoticz
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND  ## for reference
 7696 root      20   0  211464  42212  17732 S   0.3  4.4  68:48.64 domoticz    
 7696 root      20   0  211464  42212  17732 S   3.9  4.4  68:48.76 domoticz    
 7696 root      20   0  211464  42212  17732 S   0.3  4.4  68:48.77 domoticz    

rebooted...
  510 root      20   0  190016  21792  13864 S   4.3  2.3   0:00.97 domoticz    
  510 root      20   0  190016  21476  13864 S   1.0  2.3   0:01.00 domoticz    
  510 root      20   0  190016  21476  13864 S   1.0  2.3   0:01.03 domoticz    
I don't know what it means of if it's useful but I still cannot access the devices page. Perhaps the database is corrupted?

**Comment by GravityRZ** [comment]
> > it looks like the new graphs are not working when lights are switched on/off from a bash script
> 
> I don't think this has anything to do with the charts...? If it is not registered in the text log, it will not display in the chart... quite easy...

Negative, they do not register on Hue lights when the hue lights are turned on either by a bash script or with a hue scene

here is the proof.
al switch on/off  actions register on both text.log and bottom graphs, not the top ones

for now the priority is probably going to the zwave 1.6 problems but please keep this one open to investigate.

![hue1](https://user-images.githubusercontent.com/16853535/57703884-2ec3cd00-7661-11e9-9bf4-a75e0e63d49d.JPG)
![hue2](https://user-images.githubusercontent.com/16853535/57703885-2f5c6380-7661-11e9-9792-f406c8754cca.JPG)
![hue3](https://user-images.githubusercontent.com/16853535/57703888-2f5c6380-7661-11e9-93f4-f5a87264e668.JPG)

**Comment by GravityRZ** [comment]
it could be that thee hue lights do not register as ON. if you look at the commands it says set color so that is probably the problem.

**Comment by stas-demydiuk** [comment]
@GravityRZ yes, exactly, top charts are only displays changes between on/off states or their equivalents. I guess in some hardware you can change color without turning the light on.

**Comment by GravityRZ** [comment]
ok but this needs to register as on. when the light is turned on, even when it is at 10% it should show up like the bottom graphs. they register when i physically switch them on/off(by pressing the button)

hue scenes(which show up as switches) do not register nor do curl commands like curl -X PUT -d '{"scene":

is it possible the Set Color also is interpreted as ON for the above graph. the bottom graph does not seem to have problems with this.

obviously hue uses Set Color to both switch the light on with a certain color

**Comment by GravityRZ** [comment]
tested it with build 785. working now. thanks @stas-demydiuk

**Comment by rolandbreedveld** [comment]
Did all recomondations, but still no data "today" and "last 7 days" charts, the "text log" is fine

**Comment by gizmocuz** [comment]
@rolandbreedveld , could you please make a new issue ?
You are also not telling us what Domoticz version you run, what hardware type, what sensor type,
if it is received bij RF, or you are using a script, or another external device (like a ESP)
