### ISSUE TITLE
URL for particular room

### ISSUE THREAD

**Issue by cincuranet** [domoticz/domoticz#3204]
It would be nice to have a way to link directly to particular room. To be able to open what one wants to see directly, instead of selecting from dropdown first.

**Comment by gizmocuz** [comment]
@cincuranet , just to verify, are you talking about the floorplan or the rooms dropdown in the temperature tab for example ?

**Comment by cincuranet** [comment]
Rooms dropdown in tabs.
![img](https://user-images.githubusercontent.com/4540597/57565963-dd98ac80-73c6-11e9-9eda-e487c64e6ba2.png)

**Comment by gizmocuz** [comment]
I think this is added in this commit:

https://github.com/domoticz/domoticz/commit/e4c367ae2b0167f7e13f56796d90235949e9c5a8

Could you check this with the latest beta version ?

In the URL you should see the room id

> http://127.0.0.1:8080/#/LightSwitches?room=25

**Comment by cincuranet** [comment]
Does seem to work for _Switches_, but other sections do not have this value in query string.

**Comment by gizmocuz** [comment]
@cincuranet , added it for the temperature and utility tab and dashboard as well
Could you try beta 10810 ? as far as i could test its working

**Comment by xztraz** [comment]
DOMOTICZ V4.10810
works for lightswitches
http://192.168.x.x:8080/#/LightSwitches?room=6
but not for temp, dash or util

**Comment by gizmocuz** [comment]
Sorry, should be available now

**Comment by cincuranet** [comment]
Confirmed. Now to wait for stable release. ;)
