### ISSUE TITLE
Request: Lux device with decimals

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#3207]
Request for a change in the Lux device.
A lot of Lux devices like MAX44009 and others have 1 or more digits.
It would be nice that values below 100 Lux are entered in the database and displayed in the GUI with at least 1 digit. e.g 57,2 Lux.
This way there is no jump from 1 to 0 Lux, so 0,5 Lux will be possible.

**Comment by gizmocuz** [comment]
Hmmm a 0.5 difference... you can't notice that... it's probably from an Arduino analog sensor ?
My Lux sensor goes to around 848 Lux, won't spot a 847.5 here

What's your range ?

It is however possible to add support for this, but 0.5 lux... does not make much of a difference if you ask me ?

**Comment by SargonofAssyria** [comment]
A MAX44009 has a range of 0.045 Lux to 188,000
So tenths are easyly detectable. Around 1 Lux it is twilight detection.
And 1.0 Lux and 0.9 Lux is 10% differance.
Also it would be nice to have a logaritmic scale (or a section of scale type), because sunlight is 50.000 Lux and more.
Then the lines below 100 Lux completely disapear.
The reason: I would like to have my roller-shutters closed at around 0.5 Lux or less.
My wife still finds 1 Lux to much, and I would not like to argue with here.

**Comment by gizmocuz** [comment]
1 lux is complete dark... so you better check your sketch and see if you can tweak this...

https://docs.microsoft.com/en-us/windows/desktop/sensorsapi/understanding-and-interpreting-lux-values

0.5 lux.. you really can't notice ! So please fix your sketch ! (or sensor, or position of your sensor)

**Comment by xztraz** [comment]
Illuminance (lux) | Surfaces illuminated by
-- | --
0.0001 | Moonless, overcast night sky (starlight)
0.002 | Moonless clear night sky with airglow
0.05–0.3 | Full moon on a clear night
3.4 | Dark limit of civil twilight under a clear sky
20–50 | Public areas with dark surroundings
50 | Family living room lights
80 | Office building hallway/toilet lighting
100 | Very dark overcast day
150 | Train station platforms
320–500 | Office lighting
400 | Sunrise or sunset on a clear day.
1000 | Overcast day; typical TV studio lighting
10,000–25,000 | Full daylight (not direct sun)
32,000–100,000 | Direct sunlight


1 lux is quite sufficent light to see where you're walking.
