### ISSUE TITLE
Domoticz crashes with Chromecast plugin

### ISSUE THREAD

**Issue by FilipDem** [domoticz/domoticz#3208]
When upgrading today to the newest Beta version, the **plugin system crashes** due to my Chromecast plugin. It was not the case with my previous Domoticz version (the same plugin was working well). Don't know exactly which version I had installed previously, but it was also a rather recent one. See version information below. Installation is on a Raspberry Pi.

It does only crash when my Chromecast is powered. So probably on the discoveryCallback. When the plugin system crashed, only a reboot of RPI solves the problem, under the condition that the Chromecast is powered off. When the Chromecast is not powered off, the plugin system crashed immediately after restart.

The Chromecast plugin: [plugin.py.txt](https://github.com/domoticz/domoticz/files/3169446/plugin.py.txt)
And the crash report: [domoticz_crash.txt](https://github.com/domoticz/domoticz/files/3169484/domoticz_crash.txt)

The new installed version (that is crashing) is: Version: 4.10730, Build Hash: 467892e1, Compile Date: 2019-05-10 16:26:44, dzVents Version: 2.4.19, Python Version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]

**Comment by dnpwwo** [comment]
The stack trace you supplied suggests that the PLugin Manager crashed rather than your plugin.

You need to turn debug on in your plugin and post that log

**Comment by FilipDem** [comment]
Hi, Indeed that's what I indicated in my bug report. I redid the excercise with the debug on. Attached you can find the updated crash report and the domoticz debug information:
[domoticz_crash.txt](https://github.com/domoticz/domoticz/files/3169836/domoticz_crash.txt)
[domoticz.txt](https://github.com/domoticz/domoticz/files/3169837/domoticz.txt)
Thanks,
Filip

**Comment by dnpwwo** [comment]
Looks like a like a libcrypto linking issue.  There are posts on the forum where other people have solved this.  From memory you need version 1.0 instead of 1.1

**Comment by FilipDem** [comment]
OK Thanks. Will take a look at it. Just strange that all worked very well
before the upgrade of Domoticz.
Keep you posted.
