### ISSUE TITLE
Units are incorrectly displayed in the log/history graph of a "scale" virtual sensor (weight sensor).

### ISSUE THREAD

**Issue by PatrBal** [domoticz/domoticz#3211]
Domoticz v4.10731, macOS.
I have a "scale" virtual sensor (weight sensor) that is updated every minute by a script. I have set the unit as "Kilograms" in the Setup/Settings/Meters/Counters menu. Values are displayed correctly in the Dashboard with the appropriate unit "kg" added as expected. However, unlike the other sensors, the unit is replaced by a question mark in the log/history graphs:
<img width="1354" alt="Screenshot 2019-05-12 at 11 35 25" src="https://user-images.githubusercontent.com/44707588/57580566-a3eda180-74ab-11e9-858e-3f9407f9e5fd.png">

**Comment by gizmocuz** [comment]
Implemented... next time please continue at your previous issue

**Comment by PatrBal** [comment]
Ok, sorry. Thanks!
