### ISSUE TITLE
cmake newest version

### ISSUE THREAD

**Issue by rkluwen** [domoticz/domoticz#3212]
Is the newest cmake version really neccesary?
I don't like so much to be having those bleeding edgde version that are not a standard on any default application repository.

**Comment by kofec** [comment]
Fo openwrt environment I add patch:
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,5 +1,5 @@
 #set to minimum version that supports clean build
-cmake_minimum_required(VERSION 3.14.0)
+cmake_minimum_required(VERSION 3.13.0)
```

**Comment by gizmocuz** [comment]
@rkluwen , yep for boost 1.70, wiki has been updated

**Comment by gizmocuz** [comment]
(Always good to have the latest CMake... boost these days requires so.... , I was happy with the previous boost, but seems not everyone does so... trying to keep everyone happy)
For installation/update see:

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI
