### ISSUE TITLE
HTTPClient::GET is not safe

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#3214]
Static method HTTPClient::GET and others in this class are not thread safe. 
Many modules use this class, and when usesr use for example BleBox and DarkSky (with frequent checking devices) only one module works. Others are throwing errors.

**Comment by gizmocuz** [comment]
Don't think so... Never experienced this and never heard about issues as well
Please write a small 'stand alone' test application with the http class , and two threads demonstrating this

**Comment by szczukot** [comment]
I don't have problem, but a few people reported me this same problem: when they use BleBox + DarkSky, one of them randomly stopped working. When they disabled one, next works ok.
I check code and only one common part is HTTPClient.

**Comment by gizmocuz** [comment]
Don't assume , please build a test application to test

**Comment by gizmocuz** [comment]
Please re-open the issue if it is a problem (with a test source.cpp)
