### ISSUE TITLE
Some Lua require give error (started around using cmake 3.14.3 / boost 1.70.0)

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#3216]
when using  socket = require ('socket') in Lua code

error loading module 'socket.core' from file '/usr/local/lib/lua/5.2/socket/core.so':
/usr/local/lib/lua/5.2/socket/core.so: undefined symbol: lua_gettop

[Also see this Forum topic](https://www.domoticz.com/forum/viewtopic.php?f=6&t=27940&p=214599#p214486)

**Comment by Dylantje** [comment]
on my ubuntu 18.04 Lts the same error

**Comment by mikkel75** [comment]
I have same problem....anybody know a fix?

**Comment by mikkel75** [comment]
According to wiki (https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source) CMake 3.14+ and boost 1.7 should work - any idea what is causing this and how to fix?

**Comment by gizmocuz** [comment]
Lua != CMake, don't see how that could cause an issue

**Comment by mikkel75** [comment]
I'm no expert, but since Lua is missing some linked functions I'm guessing it has to do with the build of Lua that isn't done with static libs or someting... as I say I'm NO expert in this at all :)

**Comment by gizmocuz** [comment]
Could you try linking lua statically? Could be a version mismatch as normally Domoticz is using version 5.1

**Comment by mikkel75** [comment]
Would love to try, but how do I do that?

**Comment by gizmocuz** [comment]
Well it seems this should be the default already, but try compiling Domoticz with

```
cd dev-domoticz
git pull
cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt -DUSE_OPENSSL_STATIC="NO" -DUSE_BUILTIN_LUA=YES
make


```

**Comment by pagocs** [comment]
I built a new version (4.11203) with a statically linked LUA as you suggested, but unfortunately the result is same.

**Comment by gizmocuz** [comment]
The Domoticz lua version is 5.1 , and maybe on your system is 5.2 ? And the socket library is not by default part of the 5.1 library.
Could you try copying the 5.2 code in the Domoticz/Lua map and build Domoticz with 5.2 ?

**Comment by mikkel75** [comment]
For the LUA socket to be statically linked, how do I add that into the Lua source tree?

**Comment by pagocs** [comment]
Based on my experience the issue is not directly depend on the socket module because any required lua modules cause the same error. For example here is the out when I tried to "load" lfs module in a test script:

package.path = "/opt/domoticz/scripts/lua/?.lua;"..package.path;
print( "Command: local lfs = require( \"lfs\" );");
local lfs = require( "lfs" );
print( "require( \"lfs\" ); success...");

Log out:
2019-08-20 16:42:00.406 Status: LUA: Command: local lfs = require( "lfs" );
2019-08-20 16:42:00.407 Error: EventSystem: in test: error loading module 'lfs' from file '/usr/local/lib/lua/5.2/lfs.so':
2019-08-20 16:42:00.407 /usr/local/lib/lua/5.2/lfs.so: undefined symbol: lua_gettop

The issue was arisen after the cmake and boost was updated. Prior the update I did not have any issue with the compiled version.

**Comment by mikkel75** [comment]
What versions of cmake and boost should I use in order to avoid this issue and still be able to compile Domoticz successfully?

**Comment by gizmocuz** [comment]
Domoticz should/is using Lua 5.1 ... not 5.2 ...

**Comment by mikkel75** [comment]
I was more asking for the cmake and boost versions to use....

**Comment by gizmocuz** [comment]
I know, once again, Domoticz code is shipped with 5.1, so i guess the reason why it goes wrong here is that i see logs referring to 5.2

You can find the compile instructions here:

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by pagocs** [comment]
Sorry, but I am a little bit confused now.

I checked my last working rpi domoticz build (V4.10603) which is running perfectly with the same lua modules (5.2, installed with LuaRocks). 
Between the two build I did not changed anything just upgraded the boost and the cmake version what was required.

I made a fresh git clone - as the Raspberry wiki described - and as I see under the dev-domoticz/lua folder there is a 5.2.2 version of lua, or I misunderstanding something...

README
> This is Lua 5.2.2, released on 21 Mar 2013.
> 
> For installation instructions, license details, and
> further information about Lua, see doc/readme.html.`

and in the src/lua.h
> #define LUA_VERSION_MAJOR	"5"
> #define LUA_VERSION_MINOR	"2"
> #define LUA_VERSION_NUM		502
> #define LUA_VERSION_RELEASE	"2"


So, I have no idea how I can move forward...

CMAKE version: 3.14.3
Boost version: 1_70

**Comment by gizmocuz** [comment]
Oeps, very sorry about this then... i though we where running 5.1 !...

Looking here:

https://github.com/domoticz/domoticz/tree/development/lua/src

It seems that there have been no changes to the Lua part since 4 years

Looking at the comments here, we tried upgrading Lua but that did not work:

https://github.com/domoticz/domoticz/tree/development/lua

I don't think it has anything to do with the CMake version (or boost), but it might have to do with the changes in CMakeList.txt, in the domoticz root folder, or in the lua root folder, or in the lua/src folder.
You want to check the history here

**Comment by pagocs** [comment]
Thanks! I would like to avoid any mistake, so I double checked it with the current downloadable version from here:  https://www.domoticz.com/downloads/
The test was same as I quoted earlier and run ARM32 bit version. The result are:
- the stable ARM32 version is working perfectly
- the beta is produce the same error

**Comment by mikkel75** [comment]
Any update on how to get around this error on the latest beta?

**Comment by gizmocuz** [comment]
Fastest way is to check the history/cmakelist and try to revert what (if) is changed

**Comment by mikkel75** [comment]
I've compared latest src against latest stable (4.10717)..

It doesn't look like the CMakeLists.txt is changed within the lua dir.

There however some changes in the root CMakeLists.txt - some are irrelevant Zwave stuff...

This could be relevant, but I simply don't know the CMAKE system enough...
(It's the lines from 775)

Latest src:
```
target_link_libraries(domoticz ${Boost_LIBRARIES} ${ZLIB_LIBRARIES} ${MINIZIP_LIBRARIES} ${CURL_LIBRARIES} pthread ${LUA_LIBRARIES} ${MQTT_LIBRARIES} ${SQLite_LIBRARIES} ${CMAKE_DL_LIBS} ${TELLDUS_LIBRARIES})

IF(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  target_link_libraries(domoticz -lresolv)
elseif(CMAKE_SYSTEM_NAME STREQUAL "OpenBSD")
  target_link_libraries(domoticz ${EXECINFO_LIBRARIES})
elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
  target_link_libraries(domoticz ${EXECINFO_LIBRARIES})
else()
  target_link_libraries(domoticz -lrt -lresolv ${EXECINFO_LIBRARIES})
ENDIF()
```

Stable:

```
IF(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  target_link_libraries(domoticz ${Boost_LIBRARIES} ${ZLIB_LIBRARIES} ${MINIZIP_LIBRARIES} ${CURL_LIBRARIES} pthread ${LUA_LIBRARIES} ${MQTT_LIBRARIES} ${SQLite_LIBRARIES} ${CMAKE_DL_LIBS} ${TELLDUS_LIBRARIES})
elseif(CMAKE_SYSTEM_NAME STREQUAL "OpenBSD")
  target_link_libraries(domoticz ${Boost_LIBRARIES} ${ZLIB_LIBRARIES} ${MINIZIP_LIBRARIES} ${CURL_LIBRARIES} pthread ${LUA_LIBRARIES} ${MQTT_LIBRARIES} ${SQLite_LIBRARIES} ${CMAKE_DL_LIBS} ${TELLDUS_LIBRARIES} ${EXECINFO_LIBRARIES})


else()
  target_link_libraries(domoticz -lrt ${Boost_LIBRARIES} ${ZLIB_LIBRARIES} ${MINIZIP_LIBRARIES} ${CURL_LIBRARIES} pthread ${LUA_LIBRARIES} ${MQTT_LIBRARIES} ${SQLite_LIBRARIES} ${CMAKE_DL_LIBS} ${TELLDUS_LIBRARIES} ${EXECINFO_LIBRARIES})
ENDIF()

```

Any suggestions...?

**Comment by gizmocuz** [comment]
@mikkel75 , you could try building with the previous settings to see if that solves the issue

**Comment by mikkel75** [comment]
Hmmm anyone understand what he mean in this post:
https://gitmemory.com/issue/apache/trafficserver/5158/489277513
Seems to be a fix we could use as well....

**Comment by mikkel75** [comment]
I'm giving up on this and rewriting my LUA to Python.... :(

**Comment by gizmocuz** [comment]
Do you need sockets? What kind of plugin have you written?

**Comment by mikkel75** [comment]
It's a plugin that access a Roth Touchline heater controller - it's http based access... thats's why I need sockets

**Comment by gizmocuz** [comment]
Plet then indeed use python or a bash script and a crontab job
No idea why there are socket errors ...

**Comment by pagocs** [comment]
Based on my experience the issue is not directly connected to the socket but any lua modul which is installed with luarocks. I tried different modules (lfs, md5,...) and the result was a same error...

**Comment by pagocs** [comment]
I had some time today to investigate this issue. As I discovered adding the -rdynamic linker options is could solve the issue.

**Comment by gizmocuz** [comment]
@pagocs , thank you for your time and research! Please feel free to make a PR

**Comment by mikkel75** [comment]
Could you please give a little more details on the fix you have found...?
Where did you add the -rdynamic option?

**Comment by pagocs** [comment]
@mikkel75 until I will create a pull request add the following lines to the 'CMakeLists.txt' file after the 68th row. 

> IF(CMAKE_COMPILER_IS_GNUCXX)
>       message(STATUS "Add symbol export option...")
>       SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -rdynamic")
> ENDIF(CMAKE_COMPILER_IS_GNUCXX)

You should re generate the make files before start build. 
Se here: https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source
> cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt -DUSE_OPENSSL_STATIC="NO"

I tested on RPi and Ubuntu.

**Comment by gizmocuz** [comment]
@pagocs , this sets the compiler flag for the whole Domoticz project, is it not sufficient to do this for the Lua CMake file only ?

**Comment by pagocs** [comment]
@gizmocuz unfortunately I am not expert about the Linux dynamic linking, but as I understand it should export the lua functions if the lua is statically linked and want to use external modules. The "-rdynamic" is a linker options so could not resolve the exporting issue if that is only defined in lua module compilation.

Here is the thread which was a same issue: https://github.com/cpjreynolds/lua53-sys/issues/1

**Comment by gizmocuz** [comment]
@pagocs , another question, do you know why did we not had this problem for the last 6 years ?
And suddenly we do ? Seems the -rdynamic is exporting all symbols from the executable and will make it probably a lot larger and seems not needed?
What is LuaRocks and why is it installed/needed? Domoticz is using it's own Lua library, maybe you should try to delete this and build again ?
Does that solve the problem ?

**Comment by pagocs** [comment]
I already tried rebuild the whole environment from the scratch with no success.

I re check the project settings with the stable version and the latest development version. As result You can find attached two "link.txt" files what I generated on a same Linux VM with cmake.

As you can see the "#10726.link.txt" file which is belong to the stable version is already contains the "-rdynamic" against the other one.

[#10726.link.txt](https://github.com/domoticz/domoticz/files/3756254/10726.link.txt)
[#11393.link.txt](https://github.com/domoticz/domoticz/files/3756255/11393.link.txt)

Currently I have no idea which difference in "CMakeList.txt" file cause this results.

**Comment by gizmocuz** [comment]
I noticed a difference between the stable CMake project and the current, no idea if this has a influence ?

**-Wno-psabi**

```
Before: SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
Now: SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wno-psabi")

```

**Comment by pagocs** [comment]
@gizmocuz I tried build a new version without -rdynamic and without -Wno-psabi options but the original issue is still exists. So I would like find where/why the -rdynamic option was disappeared.

After jumping around the commits I guess the following change cause the issue: 
-#set to minimum version that supports clean build on cygwin
-cmake_minimum_required(VERSION 2.8.4)
+#set to minimum version that supports clean build
+cmake_minimum_required(VERSION 3.14.0)

Commit: 4e4ee999c4b323514c0ba81ab1ff3afb10d2f1cd

Here is the reason:

> CMake 3.3 and below, for historical reasons, always linked executables on some platforms with flags like -rdynamic to export symbols from the executables for use by any plugins they may load via dlopen. CMake 3.4 and above prefer to do this only for executables that are explicitly marked with the ENABLE_EXPORTS target property.

Source: https://cmake.org/cmake/help/v3.6/policy/CMP0065.html

**Comment by gizmocuz** [comment]
Thanks for the PR! One question that maybe you could check, what happens when you replace Lua 5.2 with the latest version (5.3.5)
Is everything working without this patch ?

**Comment by pagocs** [comment]
OK, I'll give it a try...
Are you think to replace the new LUA version in the domoticz project also?

**Comment by gizmocuz** [comment]
@pagocs , yes if this solves the issue... If not, i will merge your patch of course...

**Comment by pagocs** [comment]
@gizmocuz I tried the following cases with updated LUA 5.3 on the system, reinstalled LUARocks, reinstalled LUA rocks modules

- and domoticz built original LUA 5.2 and without ENABLE_EXPORTS option.
Result: **fail**
Error: EventSystem: in Script #1: [string "--..."]:27: module 'lfs' not found:
	no field package.preload['lfs']
	no file '~/domoticz/scripts/lua/lfs.lua'
	no file '/usr/local/share/lua/5.2/lfs.lua'
	no file '/usr/local/share/lua/5.2/lfs/init.lua'
	no file '/usr/local/lib/lua/5.2/lfs.lua'
	no file '/usr/local/lib/lua/5.2/lfs/init.lua'
	no file './lfs.lua'
	no file '/usr/local/lib/lua/5.2/lfs.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './lfs.so'

- and domoticz built with updated LUA to 5.3 and without ENABLE_EXPORTS option. 
Result: **fail**
Error: EventSystem: in Script #1: error loading module 'lfs' from file '/usr/local/lib/lua/5.3/lfs.so':
	/usr/local/lib/lua/5.3/lfs.so: undefined symbol: lua_gettop

- and domoticz built with updated LUA 5.3 and with ENABLE_EXPORTS option.
Result: **everything work fine.**

If you would like I could be create an another PM with updated LUA. I did not tested exhaustively but in short term it is work perfectly with some moderate complexity scripts.

**Comment by gizmocuz** [comment]
@pagocs , thank you again for your time/testing. I merged your PR
I made a branch for Lua 5.3, but i want to verify if dzVents also works before merging this

**Comment by pagocs** [comment]
@gizmocuz yw. I am testing the 5.3 LUA on my test device also..

As I discovered it could be better to add the 
> add_definitions(-DLUA_COMPAT_BITLIB) 

to cmakelist.txt in lua folder, because the old bitlib is not included by default in 5.3 against the 5.2 version.

**Comment by gizmocuz** [comment]
@pagocs , thanks! You mean at the top of lua/src/CMakeList.txt or in the domoticz main default CMakeList ?

Edit: Is it complex to use the new bit operators from 5.3 ?

**Comment by pagocs** [comment]
@gizmocuz I meant lua/src/CMakeList.txt

I do'nt have so much practice with 5.3 but as I see the new bitwise operators much better as the old library functions because same as in C: https://www.lua.org/manual/5.3/manual.html#3.4.2

But from the backward compatibility of view it could be better if the old method is not removed yet.

For example I using the old method in more LUA scripts on my main system.

**Comment by rwaaren** [comment]
Solved after moving to domoticz version with Lua 5.3
```

--[[ luasocket tester. 

        Tested with V4.11474 but should work with any domoticz version with Lua 5.3

        prerequisites: 

            sudo apt install lua5.3
            sudo apt install liblua5.3-dev
            sudo wget https://luarocks.org/releases/luarocks-3.2.0.tar.gz
            sudo tar zxpf luarocks-3.2.0.tar.gz
            cd luarocks-3.2.0
            ./configure
            sudo make bootstrap
            luarocks install luasocket
            
        log:
           > sourcet:
           >     default()
           >     by-length()
           >     until-closed()
           > source()
           > connect4()
           > newtry()
           > select()
           > sink()
           > _SETSIZE: 1024.0
           > BLOCKSIZE: 2048
           > protect()
           > sinkt:
           >     default()
           >     keep-open()
           >     close-when-done()
           > udp()
           > _DEBUG: true
           > try()
           > skip()
           > __unload()
           > connect6()
           > udp6()
           > tcp()
           > gettime()
           > sleep()
           > connect()
           > choose()
           > tcp6()
           > bind()
           > dns:
           >     toip()
           >     tohostname()
           >     gethostname()
           >     getnameinfo()
           >     getaddrinfo()
           > _VERSION: LuaSocket 3.0-rc1

           dzVents: Info: socketTester: PI-6
           dzVents: Info: socketTester: {"PI-6"}
           dzVents: Info: socketTester: {{["addr"]="::1", ["family"]="inet6"}, {["addr"]="127.0.0.1", ["family"]="inet"}}
           dzVents: Info: socketTester: {"192.168.192.109", {["alias"]={}, ["name"]="PI-6", ["ip"]={"192.168.192.109"}}}

]]--

return 
{
    on = 
    {
        timer = {'at 10:*'},
    },

    logging = { level = domoticz.LOG_DEBUG },

    execute = function(dz)
        _G.logMarker =  _G.logMarker or _G.moduleLabel
        local socket = require("socket")    
        
        dz.utils.dumpTable(socket)
        dz.log(socket.dns.gethostname())
        dz.log(socket.dns.getnameinfo(socket.dns.gethostname()))
        dz.log(socket.dns.getaddrinfo('localhost'))
        dz.log({ socket.dns.toip(socket.dns.gethostname())})
    end
} 
```

**Comment by pagocs** [comment]
The original  lua_gettop issue is came back with 2020.01 version.

**Comment by pagocs** [comment]
I am afraid the new cmake (3.17.0) which is proposed on the build guide (https://www.domoticz.com/wiki/Build_Domoticz_from_source) is reintroduced the issue.

I checked and the cmake.list file is contains the the necessary option
`SET_TARGET_PROPERTIES(${_targetName} PROPERTIES ENABLE_EXPORTS ON)`
but has no effect.

But replacing to the direct linker options
`SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -rdynamic")`
still solve the issue.

So if it is suitable I could create a new pull request.

**Comment by gizmocuz** [comment]
@pagocs , thank you for looking in to this.
So this means when you replace that line with the '-rdynamic' line, we do not need to use a external LUA and we could use all system plugins ?
That would be great
Yes please make a PR, but please not that I am working on a branch to remove ALL external libraries from the Domoticz repository (a few we have to keep as submodule), so it could take a little time before I can merge this into the development branch as I would like to merge the other branch asap

**Comment by pagocs** [comment]
@gizmocuz no, unfortunately this means no any change just could be use again the external modules (llfs,socket,..) in LUA scripts.

No problem, I will make PR shortly.

**Comment by gizmocuz** [comment]
Thanks for your PR, Because of my previous PR merge we had a merge conflict so I applied this patch myself.
All should be fine now in the current development branch
