### ISSUE TITLE
controller NodeID not showing up in Devices page

### ISSUE THREAD

**Issue by Vinisz** [domoticz/domoticz#3219]
After update to lateset release, and beta after that, the controller NodeID is not showing up in Devices page anymore (only generic name "Controller")
This way, it is impossible to find out what is what.

Issue was mentioned as well here : http://www.domoticz.com/forum/viewtopic.php?f=24&t=12636&p=214281#p214281

![Knipsel](https://user-images.githubusercontent.com/49644964/57764964-ccbca380-7704-11e9-8143-cf76f98b1276.png)

**Comment by gizmocuz** [comment]
They are highlighted in the new version in the ID, please use our Forum!

**Comment by Vinisz** [comment]
Hmm, I'm able to find them but hightlighted ? No, they are not.... (at least not at my site)

**Comment by gizmocuz** [comment]
Please show me a screenshot of the current device tab

**Comment by Vinisz** [comment]
here you go...

![Knipsel](https://user-images.githubusercontent.com/49644964/57773087-79078580-7717-11e9-96fe-9911e7f8e61e.png)

**Comment by gizmocuz** [comment]
There is indeed no highlight... are you using the 'default' theme ? did you try deleting the browser cache+appcache ?

**Comment by gizmocuz** [comment]
Sorry, nevermind, it is indeed removed

**Comment by Vinisz** [comment]
Well, I always try to look at the "why" and at the value of things but I have no idea how removing those ID's as it was before are helping the end-user of the product.... , even more, when moving from Fibaro HC2 to domoticz I was already a bit suprised how this was working in Domoticz, (I mean, a link would even be better)
Do not understand me wrong, I'm not bashing the developpers, I appreciate all the great work, but to "remove" something without good reason sounds kinda strange right ?

**Comment by gizmocuz** [comment]
Should be back in beta 10757

**Comment by gizmocuz** [comment]
@Vinisz , this is an open source project, please feel free to contribute. I have no experience with HC2, no idea how it looks

**Comment by Vinisz** [comment]
I know it is open source, I'm not a developper so I can only provide you with tips from a user perpective and my look at things. In the fibaro there is no decoupling of devices(switches and sensors)  and hardware as is in domoticz, now, both have I think their advantages and disadvantages of this.. in the end, it would be awesome of you could "click" on a hardware item and that the screen then opens with a pre-filtered list of switches and sensors related to those hardware....

**Comment by gizmocuz** [comment]
I understand. Yes this is the same behavior as we have now for MySensors

**Comment by Vinisz** [comment]
I can confirm the hightlighting is back in 10760 (which I run now)
