### ISSUE TITLE
Cube status exceeding card size

### ISSUE THREAD

**Issue by parthuman** [domoticz/domoticz#3225]
As per picture.

![cube](https://user-images.githubusercontent.com/50465898/57932286-7725f980-78b2-11e9-9b56-00c206be8fa6.jpg)

New Cube attached today. Works. Just status showing all instead of current.

Version: 4.10717
Build Hash: b38b49e5
Compile Date: 2019-05-09 12:04:08
dzVents Version: 2.4.19
Python Version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]

**Comment by parthuman** [comment]
Note: using selector style and menu is a valid workaround.

**Comment by gizmocuz** [comment]
@parthuman , how do you mean status is showing all ? The correct status (move) is being shown
What kind of cube is this ?
Yes there is a limit for the amount of options in a selector switch if you use buttons of course

**Comment by parthuman** [comment]
Yes the status is fine. Its working 100%. The issue is that some of the status 'swing' 'alert' 'free_fall' 'rotate' go outside of the card. 

As stated if you select the menu style its fine.

this is a minor UI layout issue. Priority 3 or 4.

**Comment by rwaaren** [comment]
You can also try machinon GUI theme in settings
