### ISSUE TITLE
Xaoimi cube command list shown as basic list on the scene

### ISSUE THREAD

**Issue by parthuman** [domoticz/domoticz#3226]
minor item. 

A cube has many options such as 'rotate', 'double tab' etc. however these are not translated when setting a scene.

Steps to repro:
- OPen a new scene
- Select Cube
- Shake cube during 'add device' for the action
- Action code appears as 'on'.

Seems this event is now trigged by any cube action and not just rotation or shaking etc.

Workaround.

can always add some code.

![Cubecomment](https://user-images.githubusercontent.com/50465898/57938764-c1ae7280-78c0-11e9-9fbe-ab3b228f385c.jpg)

**Comment by rwaaren** [comment]
Sounds like a feature request.
Better to discuss on the forum but this could easily be handled by a script.
