### ISSUE TITLE
Rflink Milight RGBCCT

### ISSUE THREAD

**Issue by baliku83** [domoticz/domoticz#3228]
Hello everybody
I folow the C procedure of Rflink faq to pair and create RGBCCT light, domoticz create a RGBW subtype device.

For this RGBCCT products we need to use controls of the RGBWWZ subtype device.

So I've changed in SQL the subtype of this device directly in database, I've tried everything : RGB, RGBW, RGBWZ, RGBWW and RGBWWZ but no one can control correctly the RGBCCT milight bulb.

Color and ON/Off features are OK in all case, but dimming, saturation and temperature have heratics comportments or simply doesn't work.

If devellopers need a beta tester I am OK for that, MP me.

Many thanks.
Best regards.

**Comment by gizmocuz** [comment]
You should be able to dim the light by selecting a darker color ?

**Comment by baliku83** [comment]
Dimming is relatively working, not as excepted, but missing 2 faders : Temperature and Saturation.
To understand, selecting darker color is not possible, colors are defined by a sort of scale.
For exemple 0=red, 50=Green and 100=Bleu. if you "slide" at 25 you have a yellow color...

**Comment by baliku83** [comment]
Dimming is working relatively, not as excepted, but still missing 2 faders : Temperature and Saturation.
To understand, selecting darker color is not possible, colors are defined by a sort of scale.
For exemple 0=red, 50=Green and 100=Bleu. if you "slide" at 25 you have a yellow color...
If you want a darker yellow you have to dim down the entire device. 
The problem is that dimming fader, in this state of devellopement, is a mix of Fading and saturation, with a very heratic comportment...

**Comment by baliku83** [comment]
I have a way to improve it.
I've installed ESP8266 Milighthub plugins of sidoh
https://github.com/sidoh/esp8266_milight_hub
and all is clear : the saturation and color are controled with the color circle : 
at the exterior of the circle , saturation = 100 = color without white
at the interior of the circle, saturation =0 = color with full white

The problem with the rflink control is that saturation and dimming are on the same control.
You have to, if you want to improve it, to put saturation and color (hue) on the same control AND let dimming alone on a fader.
Beside the color temperature have to be fonctional

Subtype 4  = RGBWW

Is it clear ?

Many thanks

**Comment by waltervl** [comment]
Is this still an issue?

**Comment by baliku83** [comment]
I think yes...

**Comment by gizmocuz** [comment]
I thought you solved it by using another hub ?

https://github.com/sidoh/esp8266_milight_hub

is it a RFLink controller issue, or a milight issue?

**Comment by baliku83** [comment]
Yes, i cheat with the esp, but the milight problem isn't solved.

**Comment by gizmocuz** [comment]
The issue is not very clear to me, also not the phrase "heratics comportments"

You should be able to pick a color and there should also be a slider for the brightness of that color, with this you should be able to make any color you like ?
Maybe you have a issue with the color control that it does not look/work the way you want, but you should be able to set the color with it ?
