### ISSUE TITLE
Dashboard icon virtual incremental counter (energy generated) not correct

### ISSUE THREAD

**Issue by gimbal2000** [domoticz/domoticz#3231]
I've created an Virtual sensor General - Counter Incremental, and opened (edit) the sensor in the 'Utility' tab and modified it's type to 'Energy Generated'.
On doing this the icon in the 'Utility' tab changes to a solar-sunshine icon.
However, in the Dashboard the icon remains a black 'counter' icon.
Is this by design, or a bug?

In Utility:
![afbeelding](https://user-images.githubusercontent.com/25183058/57971873-2ab2ea80-7994-11e9-894a-6f1fb40dde01.png)

In Dashboard:
![afbeelding](https://user-images.githubusercontent.com/25183058/57971882-38687000-7994-11e9-879d-4ecb02275eb6.png)

Setting:
![afbeelding](https://user-images.githubusercontent.com/25183058/57971888-4f0ec700-7994-11e9-96e0-6b088d8aaf8a.png)

**Comment by gizmocuz** [comment]
Thanks for reporting, fixed in upcoming beta 10793
