### ISSUE TITLE
Master/slave not working on Raspberry Pi GPIO

### ISSUE THREAD

**Issue by keriszafir** [domoticz/domoticz#3233]
Using Domoticz 4.10717 on Raspbian buster (testing), RPi 2B.

GPIO pins 7, 10 are exported as outputs and connected with LEDs, and 15, 27 as inputs with interrupts on both edges, connected with buttons.
Hardware driver: Raspberry's GPIO port. Devices configured as:
7 ("light 1"), 10 ("light 2") - on/off light switches
15 ("black button"), 27 ("blue button") - contacts, set as slaves to 7 and 10 respectively.
Telegram notifications enabled on light 1 going on and off.

When I turn light 1 or light 2 from the switches panel, everything is OK: I see the state change in the switches tab (light bulb lit / dark) and devices list, get the notifications where appropriate, the LEDs are turned on/off.

When I turn the black button on, I should see light 1 go on - there is a change in status in the switches tab as well as devices, but the LED doesn't go on nor off, and no notifications are fired.

Tried solving it with a blockly script triggered on device:
if black button = on, then set light 1 to on
if black button = off, then set light 1 to off
but it didn't work either.

I also added a dummy on/off button, configured it as a slave to light 1, turned it on and off - the effect is the same, no notifications, no LED change.

**Comment by gizmocuz** [comment]
Please use the forum
