### ISSUE TITLE
Windows build plan?

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#3234]
Hi! 

Is it a lot of work getting Windows build back on track? I'm especially interested in trying out the integration of OZW 1.6, or is it not recommended yet?  

Many thanks!!

**Comment by gizmocuz** [comment]
That's also one of the reasons it is not being build yet
As you might have read in the other issue, work is in progress, you should not use it until all is sorted out
You can always build yourself if you want to.
Another issue is that AppVeyor is not accepting VS2019 as platform yet.. minor issue

**Comment by RicardP** [comment]
Ok @gizmocuz, thanks for your comments, and fantastic work!

**Comment by RicardP** [comment]
OZW 1.6 seems getting functional, maybe time to get some feedback from Windows users as well? :)

**Comment by gizmocuz** [comment]
Almost.... But you can build it yourself

**Comment by Olifant1990** [comment]
Any progress on the Windows Beta build? Or is it too instable to be online atm?

**Comment by RicardP** [comment]
@Olifant1990 I did not try build it myself as I have no idea how to do it, especially as it seems difficult to get Windows built even for the developers here :)

Hope someone with Windows-feelings help us to catch up soon and then stay in frontline, as before! 🍻

**Comment by gizmocuz** [comment]
It is not a good idea to enable the windows builds yet. The new OZW 1.6 integration is not 100% done
If you want to build yourself , have a look at the INSTALL.TXT file
It's very simple

**Comment by RicardP** [comment]
@gizmocuz Ok thank you for feedback. If 1.6 is not as functional/stable as 1.4 was then it is good idea to wait. But if you mean wait because new OZW/ZWave features that is still not fully supported I think it is fine to release also the Windows betas, it is beta releases after all so no one can be upset if doesn't work as expected, or not at all.     

Big thanks for all great achievements you provide!

**Comment by RicardP** [comment]
😃 It looks Win build was released/fixed now, at download page... thanks @gizmocuz 

Before upgrading, I will make a complete copy of Domoticz installation folders (as I always does), so I can revert everything if having problems. Some scary anyway... ;)

**Comment by gizmocuz** [comment]
Got AppVeyor up and running again with VS2019... But make a complete backup before you upgrade to the beta version
