### ISSUE TITLE
Qubino module does not work in build 10793

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3235]
module is recognized in zwave and registers as functional. temp reading comes in.
however i can not switch the light on. i get an error that the device is unavailable

it checks out ok in ozw panel

module is a Qubino ZMNHADx.xml
i am using just S1 and the temp sensor

i attached a ozwlog module 11 is the qubino ZMNHADx
[domoticz.log](https://github.com/domoticz/domoticz/files/3195359/domoticz.log)
[OZW_Log.txt](https://github.com/domoticz/domoticz/files/3195360/OZW_Log.txt)

also i was getting these errors also on module 11
in the log they only show up for node 8

> 2019-05-18 19:50:10.786 Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/dahl/spksrc-master/spk/domoticz/work-apollolake-6.2/open-zwave-read-only/cpp/src/Manager.cpp (Line 1768)
2019-05-18 19:50:10.786 Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/dahl/spksrc-master/spk/domoticz/work-apollolake-6.2/open-zwave-read-only/cpp/src/Manager.cpp (Line 1768)
2019-05-18 19:50:14.786 Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/dahl/spksrc-master/spk/domoticz/work-apollolake-6.2/open-zwave-read-only/cpp/src/Manager.cpp (Line 1768)
2019-05-18 19:50:14.786 Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/dahl/spksrc-master/spk/domoticz/work-apollolake-6.2/open-zwave-read-only/cpp/src/Manager.cpp (Line 1768)
2019-05-18 19:50:14.786 Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/dahl/spksrc-master/spk/domoticz/work-apollolake-6.2/open-zwave-read-only/cpp/src/Manager.cpp (Line 1768)

**Comment by gizmocuz** [comment]
Wrong version number ? and also format your issue correctly... no idea what you used, but try to put it in a 'quote' block

**Comment by GravityRZ** [comment]
sorry, used code instead of quotes. will take more care of this

**Comment by gizmocuz** [comment]
Could you try to build the code/debug this ? I also think you need to update your openzwave repo checkout

**Comment by GravityRZ** [comment]
i will ask jumbotroll again. initialy i send this to him because it seems related to his build (synology platform)

**Comment by gizmocuz** [comment]
Yes, but again, best to test yourself... you probably have a windows machine, so just compile under visual studio and set breakpoints and test please

**Comment by GravityRZ** [comment]
figured it out. the problem is in the module config files
some modules do not like the new mapping command

v1.6 format in a lot of modules, causing problems, not working modules and errors

`<CommandClass id="96">
    <Compatibility>
      <MapRootToEndpoint>true</MapRootToEndpoint>
    </Compatibility>
  </CommandClass>`

v1.4 format in a lot of modules
WORKING when you apply this format on the v1.6 file
` <CommandClass id="96" mapping="endpoints" />
   </CommandClass>`

thee irony is that this command seems to be applied to be backward compatable but it is not.
will open a new issue specifically for this.

i found out what the problem is but do not know if this should be fixed in another way since 1.6 has an other file format

**Comment by gizmocuz** [comment]
@GravityRZ , is this the same issue you reported in another issue ?
Did you test with version 10850+ as well ? Is this Domoticz related ?

**Comment by GravityRZ** [comment]
yes it is.
tested it with 10848:not working zwave config file still mappingendpoints
when i comment the complete mapping command, delete cachefile and startup domoticz again it works

```
<!-- Map endpoints to instances -->
  <CommandClass id="96">
   <!-- <Compatibility>
   <!--    <MapRootToEndpoint>true</MapRootToEndpoint>
   <!--  </Compatibility>
  </CommandClass>
```

**Comment by gizmocuz** [comment]
@GravityRZ , okey, but then it is a OpenZWave configuration issue ? Could you report that to OpenZWave ?

**Comment by GravityRZ** [comment]
ok i will
