### ISSUE TITLE
Can't use url as param on action.

### ISSUE THREAD

**Issue by Smanar** [domoticz/domoticz#3236]
Hello, not a critical bug, but boring.

CF https://www.domoticz.com/forum/viewtopic.php?f=6&t=27915&p=214329#p214329
Seem in your code you are using OnAction.find("http://"). It's not a better idea to check if the string start with it ?

Because I m sure it will bug too if I use something like that 
script:///home/pi/notification/message.py "my message have http:// in it"

**Comment by gizmocuz** [comment]
We could compare it to 0 (should start with it)

**Comment by Smanar** [comment]
Ha yep, use (OnAction.find("http://") == 0) instead of (OnAction.find("http://") != std::string::npos)

**Comment by gizmocuz** [comment]
Should be fixed in beta 10797, it is possible to verify ?
Please also update the forum post if it's solved

**Comment by Smanar** [comment]
Sure, not tonight, but I will make a return tomorrow.

**Comment by Smanar** [comment]
It works perfectly. thx, was so fast.
