### ISSUE TITLE
Selector switch drop-down usability regression

### ISSUE THREAD

**Issue by etsach** [domoticz/domoticz#3237]
When a selector switch has many options, you generally set it to "Select Menu" mode, so that instead of having discrete buttons on the interface, you have a drop-down menu.

On stable 4.9700, this was rendered as a native HTML `<select>` drop-down. This makes browser handle the drop-down placement properly, and mobile platforms have their own way to make this user friendly with small touch devices (such as iOS making a scroll wheel with all options at the bottom of the screen).

On the newer stable 4.10717, it seems the drop-down has been implemented "in house" (divs, css and js). There were likely good reasons for this, but this made the selector unusable in some cases:

- Rendering is way too small on mobile for properly selecting an item with finger touch
- When there are many options, the drop-down list is huge, without any scroll bar
- When the device is at the bottom of the screen, the drop down list goes below the screen bottom, making items unaccessible (see screenshot below)

![2019-05-19 16-49-51-1](https://user-images.githubusercontent.com/11438049/57984133-d3c31900-7a58-11e9-8dfc-9ce4b5e86bf2.png)

I think that making a full custom drop-down list which has proper placement, scrolling, touch features, proper size on phones, accessibility, etc... is a huge task, if you don't use a framework for this, you should stick to the native `<select>`.

**Comment by gizmocuz** [comment]
Could you make a PR with a normal <select> box? Maybe a small class for theming

**Comment by gizmocuz** [comment]
@galinette2000 , not sure, but if you look in the HTML code (LightController.js / ShowLights), you will see (~ line 1334) that it is using a normal select control

**Comment by waltervl** [comment]
Can be closed?
