### ISSUE TITLE
Cross compile synology mainworker.cpp error domoticz-4.10798

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#3242]
[ 25%] Building CXX object CMakeFiles/domoticz.dir/main/mainworker.cpp.o
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r10798/main/mainworker.cpp: In member function ‘void MainWorker::RemoveDomoticzHardware(CDomoticzHardwareBase*)’:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r10798/main/mainworker.cpp:393:83: error: ‘__MYFUNCTION__’ was not declared in this scope
    _log.Log(LOG_ERROR, "Mainworker: Exception: %s (%s:%d)", e.what(), std::string(__MYFUNCTION__).substr(std::string(__MYFUNCTION__).find_last_of("/\\") + 1).c_str(), __LINE__);
                                                                                   ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r10798/main/mainworker.cpp:397:76: error: ‘__MYFUNCTION__’ was not declared in this scope
    _log.Log(LOG_ERROR, "Mainworker: Exception catched! %s:%d", std::string(__MYFUNCTION__).substr(std::string(__MYFUNCTION__).find_last_of("/\\") + 1).c_str(), __LINE__);
                                                                            ^
make[5]: *** [CMakeFiles/domoticz.dir/main/mainworker.cpp.o] Error 1
make[5]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r10798'
make[4]: *** [CMakeFiles/domoticz.dir/all] Error 2
make[4]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r10798'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r10798'
make[2]: *** [compile_target] Error 2
make[2]: Leaving directory `/home/dahl/spksrc-master/cross/domoticz'
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz'
make: [arch-x86] Error 2 (ignored)

**Comment by Jvsjvs** [comment]
Still same build error on RaspberryPi. Only now with unresolved symbol: "__MYFUNCTION__" instead of "MYFUNCTION"
