### ISSUE TITLE
Unable to compile with CMake 3.14.x

### ISSUE THREAD

**Issue by gvdhoven** [domoticz/domoticz#3243]
Latest github code.

```
> make
CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
  CMake 3.14.0 or higher is required.  You are running version 3.7.2


-- Configuring incomplete, errors occurred!
See also "/opt/zwave/dev-domoticz/CMakeFiles/CMakeOutput.log".
See also "/opt/zwave/dev-domoticz/CMakeFiles/CMakeError.log".
Makefile:7382: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
```

This didn't detect CMake 3.14.4 which was installed from source.
```
> cmake -version
cmake version 3.14.4
```

Issue was: old version of CMake was still in /usr/bin; after removing it with `sudo apt-get purge cmake` the new version still exists, but now the error is:
```
> make
make: /usr/bin/cmake: Command not found
Makefile:7382: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 127
```

In other words, the make file doesn't seem to detect the newly installed version correctly.

Partial solution:
1. `sudo apt-get remove cmake` (removes old version)
2. `sudo apt-get autoremove` (removes packages no longer needed)
3. `sudo ln -s /usr/local/bin/cmake /usr/bin/cmake`
4. CWD into dev-domoticz, run make.

In the end, this gives a linker error that the boost libraries can't be found.
```
[100%] Linking CXX executable domoticz
/usr/bin/ld: cannot find -lBoost::chrono
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:3633: recipe for target 'domoticz' failed
make[2]: *** [domoticz] Error 1
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

I noticed boost was installed in /usr/local/include so i did this: `ln -s /usr/local/include/boost /usr/include/boost`; but this also didn't solve the issue.

**Comment by Webunity** [comment]
Solution:
1. `sudo apt-get remove cmake` (removes old version)
2. `sudo apt-get autoremove` (removes packages no longer needed)
3. `sudo ln -s /usr/local/bin/cmake /usr/bin/cmake`
4. CWD into dev-domoticz, run make. If you get a 'boost' error, run make again that worked for me.

**Comment by Webunity** [comment]
update: this gives a linker error that the boost libraries can't be found.
```
[100%] Linking CXX executable domoticz
/usr/bin/ld: cannot find -lBoost::chrono
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:3633: recipe for target 'domoticz' failed
make[2]: *** [domoticz] Error 1
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

After installing the (latest known) boost package on the Pi with `sudo apt-get install libboost1.62-dev` it gives thesame output, so stuck right now.

**Comment by gizmocuz** [comment]
Have you tried following our wiki how to install CMake and compile?
There should be no problems

**Comment by dnpwwo** [comment]
I had issue like this too.

From memory the `cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt -DUSE_OPENSSL_STATIC="NO"` command from the wiki sorted them out (followed by a `make`) assuming that you have upgraded boost already

That said, right now Linux builds are failing in mainworker.cpp because __MYFUNCTION__ isn't declared but hopefully that will be sorted soon (so don't git pull right now!)

**Comment by gvdhoven** [comment]
I've followed [the wiki](https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source#Build_.26_Install_Boost_Libraries) way way back when i compiled it for the first time, but haven't checked that since then since compilation from source always was successful for me.

I re-followed all steps with regards to installing boost 1.7, rebuilding openzwave and executing `cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt -DUSE_OPENSSL_STATIC="NO"` in my dev-domoticz dir and it seems to work now.

**Comment by gizmocuz** [comment]
@dnpwwo , should also compile fine again now

**Comment by dnpwwo** [comment]
Confirmed, its fine on Ubuntu 18.04 and Windows from source now.

thanks
