### ISSUE TITLE
Unable to see log of devices

### ISSUE THREAD

**Issue by goedh452** [domoticz/domoticz#3245]
In the new update 4.10717 I'm experiencing problems with viewing the log of devices. In the devices-tab clicking the log-button of a device, simply does noting. In the others tabs clicking the button wil bring me back to the dashboard page. Anyone having the same issue?

My setup is a Raspberry Pi with Domoticz en Homebridge.

**Comment by rwaaren** [comment]
This has an answer on the forum [cache issue](https://www.domoticz.com/forum/viewtopic.php?f=6&t=28048#p215143)

**Comment by goedh452** [comment]
You are absolutely right. Could have figured this out myself. Thanks for the response!
