### ISSUE TITLE
Open Weather Map - wind not seen after 07.05.2019

### ISSUE THREAD

**Issue by ClavosPL** [domoticz/domoticz#3249]
Open Weather Map wind sped gust  chill

After last stable update on 07.05.2019, beta nothig changes
dont see any values for Wind Speed, Chill, Gust, [last seen 07.05.2019]
rest values from Open Weather Map working.

**Comment by gizmocuz** [comment]
@ClavosPL , best to start your compiler and debug

**Comment by ClavosPL** [comment]
Domoticz change Subtype for that device
From "Weather Station" to "TFA" and create new devices ... why dont now
