### ISSUE TITLE
openzwave v1.6 config file format causing errors and problems

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3253]
tested this on build 10806

i had problems with both qubino and fibaro modules.
on the fibaro module ZMNHADx i got an error in the log and the switch itself was fully recognised in zwave but was not working.

i turns out the new mapping endpoints command in v1.6 is causing this problem

some modules do not like the new mapping command

v1.6 format in a lot of modules, causing problems, not working modules and errors

`<CommandClass id="96">
    <Compatibility>
      <MapRootToEndpoint>true</MapRootToEndpoint>
    </Compatibility>
  </CommandClass>`

v1.4 format in a lot of modules
WORKING when you apply this format on the v1.6 file
` <CommandClass id="96" mapping="endpoints" />
   </CommandClass>`

can somebody with config file knowledge investigate this.

**Comment by remcom** [comment]
@GravityRZ What kind of issues do you see on the ZMNHADx. I have 2 and they seem to work fine for me.

**Comment by remcom** [comment]
Nevermind. i have 2 ZMNHND. Both are relays so i got confused

**Comment by GravityRZ** [comment]
checked the config file of the ZMNHND. they do not use the new mapping command(probably also not the old one) so yes that unit should work.

**Comment by Fishwaldo** [comment]
copying the old config format into a 1.6 config file will *NOT* work. we ignore the old format, and the new format is whats looked at. 

a full log file from 1.6 without ozwcache_*.xml is needed to debug this.

**Comment by GravityRZ** [comment]
ok so what do you need me to do?
install latest build from scrap(not update)
delete ozwcache file
enable debug on zwave controller
stop zwave controller
start zwave controller
send you the OZW_log.txt

**Comment by Fishwaldo** [comment]
I have no idea how! 

I just need a OZW_log file that’s produced without the presence of ozwcache.

**Comment by GravityRZ** [comment]
ok. will send it tomorrow

**Comment by GravityRZ** [comment]
here is the logfile
started clean with no cachefile present.
i also included the cache file it made after startup just in case you need it(renamed to .txt)

[OZW_Log.txt](https://github.com/domoticz/domoticz/files/3215404/OZW_Log.txt)

[ozwcache_0xcea80b03.txt](https://github.com/domoticz/domoticz/files/3215408/ozwcache_0xcea80b03.txt)

**Comment by Fishwaldo** [comment]
Christ its a buggy device.....
Can try removing the MapRootToEndpoint Capability from the config file, and resend me the log if it still doesn't work.

**Comment by GravityRZ** [comment]
i tested that. with the old mapping=endpoint command the unit is working.
if you state that this command is skipped because of the old format then yes removing MapRootToEndpoint will fix it.

please note that this unit has multiple endpoints (I1, I2, I3)
i am only using I1 and the temperature input and they work without the MapRootToEndpoint command.
do not know about I2 and I3 but still it is best to remove the command from the configfile because with this command I1 is not working at al.

**Comment by gizmocuz** [comment]
@GravityRZ , is this issue still open ?

**Comment by GravityRZ** [comment]
yes but it is also opened in open-zwave. will close this one
