### ISSUE TITLE
OZW Tried adding value, not succeeded

### ISSUE THREAD

**Issue by Vinisz** [domoticz/domoticz#3255]
Multiple errors in the OpenZwvae control panel about "tried adding vaue"
Below errors appear in red in the log (this node 117 is just an exmaple, it is a fibaro wall plug)

OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 117 (0x75), CommandClass: METER, Label: Unknown, Instance: 1, Index: 0

**Comment by gizmocuz** [comment]
We're working on the 1.6 implementation as you might know.
What version of domoticz are you using? Latest beta ??
What did you do in the control panel ? this error is from the domoticz log

**Comment by Vinisz** [comment]
I'm switching all the time between last beta and last production cause I really like to test the OZW1.6 stuff but I cannot use it in production at the moment.... (latest beta needs to have the "doubleclick" working before I can stay on the beta versions)
I posted quite some logging in the Venentian blinds issue as well

**Comment by gizmocuz** [comment]
@Vinisz , could you try beta version 10580+ to see if this solves your issue ?

**Comment by gizmocuz** [comment]
no response, assuming solved. please re-open if it's not

**Comment by ROV28** [comment]
I have the same problem:

`2019-06-16 21:16:41.051 Error: OpenZWave: Unhandled Meter type: Power, class: 0x32 (METER), NodeID: 4 (0x04), Index: 8, Instance: 1`
`2019-06-16 21:16:41.051 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 4 (0x04), CommandClass: METER, Label: Power, Instance: 1, Index: 8`

Running Domoticz V4.10917 on a Fedora 30 Linux system.

**Comment by sincze** [comment]
quick update. 
Apparently updated from 1.4 -> 1.6 by updating domoticz to latest beta.
so we are experiencing issues as described [issue](https://github.com/domoticz/domoticz/issues/3385)

Running

Domoticz V4.10962
Build Hash: d11c33725
Build Date: 2019-07-06 15:11:14

In the log there is now 
```
2019-07-07 10:57:42.245 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 10 (0x0a), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-07-07 10:58:13.500 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 10 (0x0a), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
```

**Comment by gizmocuz** [comment]
@sincze , best to continue here
