### ISSUE TITLE
TypeError: "response.result is undefined"

### ISSUE THREAD

**Issue by Phyks** [domoticz/domoticz#3257]
Hi,

I've just installed Domoticz (fresh install from the install script, see https://www.domoticz.com/wiki/Raspberry_Pi#Install_Domoticz) and went to the browser interface, to the "Devices" tab.

The "Devices" tab keeps showing "Loading". It seems there is an issue with

```
http://127.0.0.1:8080/json.htm?displayhidden=1&filter=all&type=devices&used=all
```

which returns a JSON dict without any `result` entry, resulting in the following error in the JS console:

```
TypeError: "response.result is undefined"
    refreshDevices http://127.0.0.1:8080/app/devices/Devices.js:540
    Angular 13
    execCb http://127.0.0.1:8080/js/require.js:29
    check http://127.0.0.1:8080/js/require.js:18
    enable http://127.0.0.1:8080/js/require.js:23
    init http://127.0.0.1:8080/js/require.js:17
    j http://127.0.0.1:8080/js/require.js:26
    setTimeout handler*g.nextTick< http://127.0.0.1:8080/js/require.js:32
    j http://127.0.0.1:8080/js/require.js:26
    requirejs http://127.0.0.1:8080/js/require.js:31
    Angular 9
    jQuery 8
    Angular 16
    jQuery 8
 Possibly unhandled rejection: {}
…
```

Tested with the latest stable (v4.10717) as well as the beta channel (v4.10810).

Thanks!

**Comment by gizmocuz** [comment]
Can you clear your browser cache + appcache ? (or try a private browser?)
I started from scratch (deleted the database) and can not reproduce this

**Comment by rwaaren** [comment]
I see the same message when installing from scratch but only if I go to [devices] in the setup pull down

**Comment by gizmocuz** [comment]
Sorry let me check, i was checking the Utility tab

**Comment by gizmocuz** [comment]
Yep... going to fix this one

**Comment by gizmocuz** [comment]
Thanks for reporting! Solved in beta 10821

**Comment by Phyks** [comment]
Indeed, I was accessing from the Setup tab. Thanks for the fix, will try ASAP!

**Comment by PersoRu** [comment]
I have the same issue. Wouldn't it be smart to fix this in the Stable release? Everyone who try to install it form the official page will stuck?

**Comment by gizmocuz** [comment]
@PersoRu , yes, or we should release a new Stable soon... But it is only when there is nothing in the system

**Comment by lethalwp** [comment]
Hello,
I have the same problem: fresh install (beta from today) on raspberry buster, the device tab keeps "loading....". I did notice this happens in chrome, but it works in firefox!
