### ISSUE TITLE
Blind controls inverted on the FloorPlan

### ISSUE THREAD

**Issue by etsach** [domoticz/domoticz#3267]
I am using Domoticz with several Somfy RTS 433MHz blinds. On the switch tab the action buttons are correct, ie the purple open icon does open the blind, and the grey closed icon does close the blind.
These switches have been added to the FloorPlan view, and when hovering the mouse over a blind icon, the action switches pop up. Clicking on the open blind does close it, and the closed blind does open it.

Using Domoticz stable v4.10717

**Comment by gizmocuz** [comment]
Thanks for reporting, should be fixed in beta v4.10852
