### ISSUE TITLE
sliders on dashboard don't slide in opera

### ISSUE THREAD

**Issue by xztraz** [domoticz/domoticz#3268]
DOMOTICZ V4.10826

I can't slide the sliders on dashboard.
they work on floorplan and switches thou

**Comment by gizmocuz** [comment]
No issues here, maybe your'e on a old beta ?

**Comment by xztraz** [comment]
tested in firefox and it works but not in opera. it worked in opera ~2 betas ago.  
ie ok
chrome ok

**Comment by xztraz** [comment]
reboot seemed to have solved the sliders.. closing :)
