### ISSUE TITLE
Wording issue in i18n

### ISSUE THREAD

**Issue by gaudryc** [domoticz/domoticz#327]
Could you please change the following string ?

"Not al months have this amount of days, some months will be skipped!"
to
"Not all months have this amount of days, some months will be skipped!"

Thanks in advance.

**Comment by gaudryc** [comment]
And :

"Not al years have this date, some years will be skipped!"
to
"Not all years have this date, some years will be skipped!"

;-)

**Comment by gizmocuz** [comment]
Done

**Comment by EddyK69** [comment]
Oops, sorry & thanks :D

**Comment by gaudryc** [comment]
Your welcome ;-)
