### ISSUE TITLE
POPP Strike-Lock 012501 

### ISSUE THREAD

**Issue by sergiotropea** [domoticz/domoticz#3271]
Hi, everybody,
I have a strange difficulty with the Strike-Lock POPP device. It is included correctly, even safely, but does not make the switch. On the forums I found conflicting opinions. The manufacturer guarantees that it is compatible with my radio module. Below is the current configuration:

- Domoticz V4.10717
- RaZberry con ZMEERAZ2

Has anyone had experience with this problem?

**Comment by gizmocuz** [comment]
Please include the forum link and also the Domoticz version you are using

**Comment by sergiotropea** [comment]
Hi, thank for your answer, i found  [this](https://github.com/home-assistant/home-assistant/issues/11938), probably is useful also for Domoticz. What do you think about? What i can do to help you to close this issue?
My Domoticz Version is Domoticz V4.10717 with RaZberry (ZMEERAZ2).

Thanks in Advance

**Comment by gizmocuz** [comment]
Did you try updating to the beta version (10850+) to see if this works ? Make sure you have 'accept new hardware' enabled in the settings

**Comment by sergiotropea** [comment]
I updated wiith 10850 version. I included node in safe mode, i have to changed the Key id in Options File. And now the POPP starting. Thanks in advance.
