### ISSUE TITLE
RTL433: rid is ignored, cannot distinguish sensors

### ISSUE THREAD

**Issue by taismi** [domoticz/domoticz#3272]
RTL433 uses id, rid and channel to distinguish sensors but Domoticz's Rtl433.cpp use only id and channel. 

`unsigned int sensoridx = (id & 0xff) | ((channel & 0xff) << 8);`
https://github.com/domoticz/domoticz/blob/development/hardware/Rtl433.cpp#L341
https://github.com/domoticz/domoticz/blob/4.10717/hardware/Rtl433.cpp#L331

This causes sensors with same id an channel to be seen as one device in Domoticz. RFLink sees sensors as separate devices.

**Comment by gizmocuz** [comment]
True, I would have xorred it maybe or shifted it
Not something that can be changed without all current users getting new id's
But how big are the odds that this is happening and can this be avoided by the user as well ?

**Comment by taismi** [comment]
I have sensors with IDs like 0109, 0209 and 0309. This is easy to use if you have only three sensors. Sensors support three channels. This doesn't work anymore with higher sensors count. Maybe an option to combine id and rid would solve things so by default users would not get new IDs. I have rids 28, 116, 30, 46, 113, 116, 124, 232. 

In the transmission first octet is 9. After that there are two octets which are seen in RFLink's ID but no it RTL433. After that there's an octet which's last two bits are channel. First two bits are unknown for me.

-------
I found from the RTL433 source code that  first octet could also be 5 .
> Prologue sensor protocol
> 4 bit fixed 1001 (9) or 0110 (5)

I don't know why RTL433 set fixed value to ID and rest to RID. Some sensors don't show RID, only ID which contains all.

**Comment by gizmocuz** [comment]
Seems like you can control those id's ? So you can also assign them a different id ... 1,2,3 etc

**Comment by taismi** [comment]
Only three different id's are possible and I have 8 sensors. All sensors have unique rid's.

**Comment by bousqi** [comment]
> RTL433 uses id, rid and channel to distinguish sensors but Domoticz's Rtl433.cpp use only id and channel.
> 
> `unsigned int sensoridx = (id & 0xff) | ((channel & 0xff) << 8);`
> https://github.com/domoticz/domoticz/blob/development/hardware/Rtl433.cpp#L341
> https://github.com/domoticz/domoticz/blob/4.10717/hardware/Rtl433.cpp#L331
> 
> This causes sensors with same id an channel to be seen as one device in Domoticz. RFLink sees sensors as separate devices.

Same issue on my side. With prologue sensor you can merge id and rid to make a longer and more reliable ID.
Channel concatenated to ID seems to be insufficient. 
I have all my prologue sensors with ID 5 and RID helps to distinguish them. Some of them are using the same channel. 
By the way a channel is  a communication parameter, not an identifier.

**Comment by bousqi** [comment]
> Seems like you can control those id's ? So you can also assign them a different id ... 1,2,3 etc

No way to control ID on Prologue sensors.
When battery is replaced, ID is kept while RID is "randomly" modified.

**Comment by gizmocuz** [comment]
That is for most 433Mhz, you get a new id

**Comment by gizmocuz** [comment]
Receiving this sensor with a RFXCom RFXtrx433 module, you also get a ID (8 bits) and a Unit(Channel) bits

Maybe the code could/should be modified with

`unsigned int sensoridx = ((id & 0xff) << 8) | (channel & 0xff);`

Don't think it changes anything

**Comment by bousqi** [comment]
No that won't change anything.

Here is a dump of sensor list I have :
```
{"time" : "2019-08-19 10:36:47", "model" : "Prologue sensor", "id" : 5, "rid" : 228, "channel" : 2, "battery" : "OK", "button" : 0, "temperature_C" : 25.000, "humidity" : 63}
{"time" : "2019-08-19 10:36:59", "brand" : "OS", "model" : "THGR122N", "id" : 254, "channel" : 3, "battery" : "OK", "temperature_C" : 23.300, "humidity" : 58}
{"time" : "2019-08-19 10:36:59", "model" : "Prologue sensor", "id" : 5, "rid" : 186, "channel" : 1, "battery" : "OK", "button" : 0, "temperature_C" : 24.700, "humidity" : 68}
{"time" : "2019-08-19 10:37:01", "model" : "Prologue sensor", "id" : 5, "rid" : 18, "channel" : 1, "battery" : "OK", "button" : 0, "temperature_C" : 24.400, "humidity" : 69}
{"time" : "2019-08-19 10:37:10", "model" : "Prologue sensor", "id" : 5, "rid" : 6, "channel" : 2, "battery" : "OK", "button" : 0, "temperature_C" : 25.500, "humidity" : 60}
{"time" : "2019-08-19 10:37:16", "model" : "Prologue sensor", "id" : 5, "rid" : 155, "channel" : 3, "battery" : "OK", "button" : 0, "temperature_C" : 24.200, "humidity" : 67}
{"time" : "2019-08-19 10:37:22", "model" : "Prologue sensor", "id" : 5, "rid" : 228, "channel" : 2, "battery" : "OK", "button" : 0, "temperature_C" : 25.000, "humidity" : 63}
{"time" : "2019-08-19 10:37:24", "brand" : "OS", "model" : "THGR122N", "id" : 246, "channel" : 2, "battery" : "OK", "temperature_C" : 24.000, "humidity" : 62}
{"time" : "2019-08-19 10:37:24", "brand" : "OS", "model" : "THGR122N", "id" : 246, "channel" : 2, "battery" : "OK", "temperature_C" : 24.000, "humidity" : 62}
{"time" : "2019-08-19 10:37:25", "brand" : "OS", "model" : "THGR122N", "id" : 228, "channel" : 1, "battery" : "OK", "temperature_C" : 20.900, "humidity" : 77}
{"time" : "2019-08-19 10:37:25", "brand" : "OS", "model" : "THGR122N", "id" : 228, "channel" : 1, "battery" : "OK", "temperature_C" : 20.900, "humidity" : 77}
```

As you can see I have more sensor from one type than channels available. Thus naming as defined is not enough. Example :
```
{"time" : "2019-08-19 10:36:59", "model" : "Prologue sensor", "id" : 5, "rid" : 186, "channel" : 1, "battery" : "OK", "button" : 0, "temperature_C" : 24.700, "humidity" : 68}
{"time" : "2019-08-19 10:37:01", "model" : "Prologue sensor", "id" : 5, "rid" : 18, "channel" : 1, "battery" : "OK", "button" : 0, "temperature_C" : 24.400, "humidity" : 69}
```

Any chance to get something more precise like : 
```
unsigned int sensoridx = ((id & 0xff) << 8) | (rid & 0xff);
```

Channel is related to RF frequencies, not to sensor identifiers. If user would like to change channel with the small switch available on sensor itself, it will be declared a new sensor which is not the case.

Don't you agree ?

**Comment by gizmocuz** [comment]
Maybe, but the RID is not always provided.

For example, this is a received line:

"2019-07-03 16:22:59,,,LaCrosse WS,,32,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,909.090,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"

**Comment by bousqi** [comment]
I agree with your statement, but when RID is not provided, ID seems to be sufficient.
What about having RID = 0 when not provided ?

**Comment by gizmocuz** [comment]
Could you test the following:

```
uint16_t sensoridx = (id & 0xff) << 8;

if (rid!=0)
   sensoridx  |= rid & 0xff;
else
   sensoridx  |= channel & 0xff;

```

**Comment by gizmocuz** [comment]
I can't seem to find a document specifying the RID ...

https://github.com/merbanan/rtl_433

**Comment by bousqi** [comment]
Ok, I'll give a try.
Can you please point me out the build instructions ? (Found them it was in install.md)

Why do you want to keep channel when rid is not available? As I said one user can change channel config on a sensor to avoid RF conflicts. Keeping channel in ID will discard all previous acquired data, I guess (I'm a new user to domoticz and maybe I'm missing something).

Alternative solution : what about enlarging final sensor I'd to a uint32_t ? There will be enough space for channel, id, rid

**Comment by bousqi** [comment]
Oh I just realized the sensorIdx is already on an  32Bits int.
Great, let's move all of them onboard like this :
```
unsigned int sensoridx = (id & 0xff) | ((rid & 0xff) << 8) | ((channel & 0xff) << 16);
```

**Comment by gizmocuz** [comment]
Okey, so it IS working with the channel ID ? This is normal behavior, also when receiving with a RFXtrx433 transceiver

It's a 16 bit value, so << 16 won't work

**Comment by bousqi** [comment]
not yet tested, I started to build Domoticz on a Pi Zero (I must have paid attention to that). 
Finally compilation fails due to a memory allocation failure.
I'll get back to my PI3B tu build.

**Comment by bousqi** [comment]
I'm struggling to compile from RPI3B for Pi Zero platform.
I must specifiy target platform with these options
 -mcpu=arm1176jzf-s -mfpu=vfp 
but where set them for GCC to use those.

Work in progress..

EDIT : found it in CMakeList.txt, restarting build process

**Comment by dgrostoto** [comment]
rid is now handled as id for this sensor (rtl_443 newmodel with normalized keys). So now sensors can be distinguished correctly.
I suggest that this issue can be closed.  Don't hesitate to tell me if there is a problem this this, i probably could help to fix.

**Comment by dgrostoto** [comment]
related to PR https://github.com/domoticz/domoticz/pull/3902
