### ISSUE TITLE
Switch is a badly shown on Floor Plan

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#3273]
4.10826
On floor plan i have switch with water icon. I can't change state of this switch. When i click on it, i see only log. A few version ago, i see under icon info like on/off, and this icon was clickable (switch on/of)

**Comment by gizmocuz** [comment]
I think this is caused by this patch

https://github.com/domoticz/domoticz/pull/3239

going to revert this, i think what @stas-demydiuk is looking for is a new switch type 'Read Only' that prevents people from turning it on/off and goes directly to the log

**Comment by gizmocuz** [comment]
@stas-demydiuk , you need to set the switch-type to 'contact' and choose the water icon
You should not be able to switch a 'contact' type... this is also not possible from the dashboard/switches tab
(But is currently possible from the Floorplan)

Should now not be possible with this commit:

https://github.com/domoticz/domoticz/commit/bd4137b2f95c8795517bcb7336acc7f6ecec4196

**Comment by szczukot** [comment]
done
