### ISSUE TITLE
fix #3269 Breaks the connection between domoticz and Youless.

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#3274]
#3269 

This fix breaks the connection between domoticz and my Youless.
Checked with previous version, other system and CLI curl and locally with reverted fix and confirmed that the error Error: YouLess: Error connecting to: 192.168.192.222
that was introduced with this fix is solved by reverting.

**Comment by gizmocuz** [comment]
Can you debug the code? It should generate the same url

**Comment by rwaaren** [comment]
Will do.

**Comment by rwaaren** [comment]
> Can you debug the code? It should generate the same url

It did not generate the same url.  Was it because the /e compared to /a ? or was there something else ?
#3277 does fix it (tested)

**Comment by gizmocuz** [comment]
@rwaaren , thanks for the PR!
Verified the stringstream, no problems detected. It's also used everywhere and is perfect c++
If you set a breakpoint at the beginning of HTTPClient::GET you should see this
This should be solved in beta 10836
