### ISSUE TITLE
Sensative door/window stripes stopped working after OZW1.6

### ISSUE THREAD

**Issue by Shupez** [domoticz/domoticz#3275]
Hi,
I have Domoticz beta ver: 4.10826 on a RPi 3 with a Razberry V2 Z-wave.
After the latest OZW1.6 update, my Sensative Stripes stopped working properly. Now they say the door is open all the time even though it´s closed. And my Pushover script does´nt send any notifications longer for them.
Everything else is working. I have a lot of other Z-wave stuff that works.
Is this a known problem?
What can I do?

/J

**Comment by gizmocuz** [comment]
Please do a little bit more research and browse done of the issues here
Use the stable for now until all is sorted
