### ISSUE TITLE
Custom Templates - Current Page Broken

### ISSUE THREAD

**Issue by nayrnet** [domoticz/domoticz#328]
Minor UI glitch, When selecting a custom template, the current page sticks to whatever page you were on last.

This makes it impossible to directly navigate back to where you started from.

Example, Start off on Dashboard, Open a Custom Template, WebUI still thinks the current page is the Dashboard so the link to click on dashboard is Highlighted and Disabled.

See Screenshot, notice URL says dashboard even though the custom template for nzbget is loaded

![screen shot 2016-01-13 at 3 33 08 am](https://cloud.githubusercontent.com/assets/3732081/12291809/af8f414c-b9a6-11e5-8765-9426acb86e4c.png)

Expected Behavior was for the custom tab to highlight when viewing a custom template, or at least nothing in the menu be highlighted.

Wish: direct link to custom templates, like /#/Custom/nzbget.. my news reader happens to be my default home page and I'd like to open it via domoticz so I can navigate all services with ease.
Wish: "Custom" seems like an odd choice, would not "Apps" be more appropriate since thats what this seems like its for, custom app interfaces.. even the sample template looks like an app to me.

**Comment by gizmocuz** [comment]
Can you submit a patch ?

**Comment by nayrnet** [comment]
Ive been trying, have not made alot of progress so far.. I'll keep at it though, I thought it might be really easy to fix, turns out that's not the case.

**Comment by gizmocuz** [comment]
Think i managed todo it !

New beta in the making (#4798), could take an hour (code already committed)

When you now go to the custom template, you see the browser address bar changing, and you can use this url to directly go to it

**Comment by nayrnet** [comment]
you are the man! I'll play with it tonight.. this will allow everything tie in so nicely w/Domoticz, my default homepage is a [news reader](http://selfoss.aditu.de/) I host on the same box as domoticz so it works well in an iframe..
