### ISSUE TITLE
Z-wave, nodes, pushing refresh node info and then refresh page gives name unknown

### ISSUE THREAD

**Issue by xztraz** [domoticz/domoticz#3280]
DOMOTICZ V4.10841 RPI

To recreate:
Go to hardware -> Zwave setup.
select any named zwave node.
push "refresh node info"
reload page.
name of refreshed node is now "unknown"

from log
```
...
May 28 18:47:40 raspberrypi domoticz: OpenZWave: Node Removed. HomeID: 3698476673, NodeID: 14 (0x0e)
May 28 18:47:40 raspberrypi domoticz: OpenZWave: New Node added. HomeID: 3698476673, NodeID: 14 (0x0e)
...

```
before
![image](https://user-images.githubusercontent.com/25690871/58496292-e08eed80-8179-11e9-8e0b-a3ded945f623.png)
after
![image](https://user-images.githubusercontent.com/25690871/58496361-04523380-817a-11e9-9be9-633e141925e0.png)

**Comment by gizmocuz** [comment]
@xztraz , found the issue. Seems this was happening from the beginning (one of the first stables)
Solved in beta 10850

**Comment by xztraz** [comment]
great! thanks for the fix. also tested and name is now remembered. 

Keep up the good work
