### ISSUE TITLE
Not all sensors from a multi-sensor device are handled using rtl_433 support

### ISSUE THREAD

**Issue by blitt001** [domoticz/domoticz#3283]
After upgrading from 4.9700 to 4.10717 my WH24 weatherstation only exposes the temperature and humidity. Windspeed, UV and winddirection are not detected anymore.

It seems that the problem is in the file Rtl433.cpp in domoticz. The have done a change that when humidity and temperature are handled, the function direct will return (because of the line " return true;". This means that wind sensor will not be handled because that code will never be reached.

I have added a modification that will handle all the sensors of the weather station.

In the attached ZIP file there is the modified CPP file.

[Rtl433.zip](https://github.com/domoticz/domoticz/files/3229703/Rtl433.zip)

**Comment by gizmocuz** [comment]
Thanks! If possible, could you make a PR in the feature ?
I have modified the code and it should now work again in beta 10847. Is it possible to verify this ?

**Comment by devrosx** [comment]
after latest update on my rflink only temp devices are visible in logs, energy and meteo station updates are gone in log....
rflink switches works ok

**Comment by gizmocuz** [comment]
@devrosx , this is about RTL433, and has nothing to do with RFLink ?

**Comment by devrosx** [comment]
sorry then, I updated yesterday and Meteostation and owl energy updates are gone,  and I saw some changes in rflink code in github...
I can check the sensors but I doubt that both of them broke

**Comment by gizmocuz** [comment]
Do you use RTL433 ? If not, this is not the right issue, please use the forum.
Also mention on the forum what version you where upgrading from, and what version you are running now

**Comment by gizmocuz** [comment]
@blitt001, is your wind sensor reporting with the new version ?

**Comment by blitt001** [comment]
Yes, currently, Wind-speed, wind-direction and also the rainfall is working again.
Tested with domoticz build 10848

**Comment by gizmocuz** [comment]
Great thanks for the feedback!
