### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Olifant1990** [domoticz/domoticz#3287]
I have a family member running Domoticz v4.10717 on a Raspberry Pi.
Clean installation.
Then he added a rfxcom device via settings/hardware.
After that, the page stays blank.
In the console is the following error:
TypeError: Cannot read property 'map' of undefined
    at Devices.js:541

See also https://www.domoticz.com/forum/viewtopic.php?t=28109
It has been reported there too.

Does anyone know how to solve this?

**Comment by gizmocuz** [comment]
Thanks for reporting, best to continue on the forum
