### ISSUE TITLE
Reopen of  #3264: Scene updates not showing on dashboard (pc browsers)

### ISSUE THREAD

**Issue by pa3fat** [domoticz/domoticz#3288]
Scenes toggles are not updated still on V4.10848. Within the Scene tab itself it seems ok.

**Comment by gizmocuz** [comment]
@pa3fat , please do not cross post a issue. Thanks for reporting, found the issue. Beta 10849 solves the issue

**Comment by pa3fat** [comment]
Tested: status is not resolved.

Pa3fat is in NL at port 8080

Van: gizmocuz <notifications@github.com>
Verzonden: 30 May, 2019 10:31
Aan: domoticz/domoticz <domoticz@noreply.github.com>
CC: Ron van Doremalen <ronvandoremalen@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [domoticz/domoticz] Reopen of #3264: Scene updates not showing on dashboard (pc browsers) (#3288)


Closed #3288<https://github.com/domoticz/domoticz/issues/3288>.

**Comment by pa3fat** [comment]
Edge seems to work !
Flushed cached of FF also. Strange.

Van: gizmocuz <notifications@github.com>
Verzonden: 30 May, 2019 10:31
Aan: domoticz/domoticz <domoticz@noreply.github.com>
CC: Ron van Doremalen <ronvandoremalen@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [domoticz/domoticz] Reopen of #3264: Scene updates not showing on dashboard (pc browsers) (#3288)


Closed #3288<https://github.com/domoticz/domoticz/issues/3288>.

**Comment by pa3fat** [comment]
Flushed all data on FF for every webpage. Not it is ok.

Tnx Ron

Van: gizmocuz <notifications@github.com>
Verzonden: 30 May, 2019 10:31
Aan: domoticz/domoticz <domoticz@noreply.github.com>
CC: Ron van Doremalen <ronvandoremalen@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [domoticz/domoticz] Reopen of #3264: Scene updates not showing on dashboard (pc browsers) (#3288)


Closed #3288<https://github.com/domoticz/domoticz/issues/3288>.

**Comment by pa3fat** [comment]
Issue is back.

**Comment by gizmocuz** [comment]
Thanks for reporting... I also do experience refreshing issues, also in the scenes tab

**Comment by pa3fat** [comment]
V4.11301 shows it is solved. Tnx

**Comment by gizmocuz** [comment]
@pa3fat , thanks for the feedback !
