### ISSUE TITLE
Xiaomi Gateway Volume  - DzVents 2.4.22 - SwitchSelector - failed

### ISSUE THREAD

**Issue by SzemiSun** [domoticz/domoticz#3291]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version.
* Always state your version when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue. 
Domoticz Version 4.10854
I had a dzVents script which played a doorbell sound, but it doesn't work since I updated dzVents to 2.4.22 version

2019-06-03 21:33:16.200 Status: dzVents: Error (2.4.22): ElőszobaWirelessButton: An error occured when calling event handler ElőszobaWirelessButton
2019-06-03 21:33:16.200 Status: dzVents: Error (2.4.22): ElőszobaWirelessButton: ...moticz/dzVents/runtime/device-adapters/switch_device.lua:117: attempt to get length of field 'levelNames' (a nil value)

ElőszobaWirelessButton
56:                   		    XGVolume.switchSelector(10)

**Comment by gizmocuz** [comment]
Guidelines not taken in account

**Comment by SzemiSun** [comment]
Sorry, but I don't understand what do you think.
I hadn't found any information about it in guidelines.
The changelog contains only these lines:
[2.4.22]
selector.switchSelector method accepts levelNames
increased selector.switchSelector resilience
fix wildcard timerule

but it doesn't detaile how can I modify my code to work

**Comment by rwaaren** [comment]
> Sorry, but I don't understand what do you think.
> I hadn't found any information about it in guidelines.
> The changelog contains only these lines:
> [2.4.22]
> selector.switchSelector method accepts levelNames
> increased selector.switchSelector resilience
> fix wildcard timerule
> 
> but it doesn't detaile how can I modify my code to work

Please use the forum for this type of issues. Happy to help you there
