### ISSUE TITLE
GCM deprecated

### ISSUE THREAD

**Issue by Olifant1990** [domoticz/domoticz#3292]
In the logs the following is happening:
2019-06-03 23:15:01.843 Error: GCM: Can not connect to GCM API URL
2019-06-04 06:05:01.724 Error: GCM: Can not connect to GCM API URL

I guess now is the time the old default Android push service has been deprecated and we have to switch to the new FCM (Firebase Cloud Messaging) service.

Link: https://developers.google.com/cloud-messaging/android/android-migrate-fcm

**Comment by gizmocuz** [comment]
Thanks for reporting, could you test this and create a PR ?

**Comment by Olifant1990** [comment]
Yes, will have a look soon!

**Comment by rwaaren** [comment]
Not a complete PR but just tested replacing
`#define GAPI_POST_URL "https://gcm-http.googleapis.com/gcm/send"`

with 

`#define GAPI_POST_URL "https://fcm.googleapis.com/fcm/send"
`

in file 

 notifications/NotificationGCM.cpp

and the gcm notification works as before.
Is this something that we could put in place until a complete PR is ready ?

**Comment by Olifant1990** [comment]
Yes, that simply IS the FIX ;)
Only we need to refactor rename all GCM items to FCM.
But will do it :)

**Comment by Olifant1990** [comment]
Will do a lot more refactoring, so, please keep this open :)

**Comment by gizmocuz** [comment]
@Olifant1990 , okey, then i will wait merging the PR and you can continue pushing to your fork

**Comment by Olifant1990** [comment]
@gizmocuz 
Oh, I made a new branch/fork for the refactor items.
You can merge quick fix PR, but keep this issue open for a while please ;)

**Comment by gizmocuz** [comment]
Your fork is still their and you can continue pushing changes to it:

https://github.com/Olifant1990/domoticz/tree/gcmToFcm

**Comment by Olifant1990** [comment]
Done!
Fully tested and working, tested with old to new database, settings are still correct. And test with lua with GCM subsystem, all working!

**Comment by Olifant1990** [comment]
The old GCM seems to be working again, I receive notifications on my live system again. But, this still has to be changed!

**Comment by gizmocuz** [comment]
@Olifant1990 , thank you for the patch ! And the hard work!
GCM is flagged as depricated somewhere in 2018, FCM is almost the same, just a newer API

This patch is maybe a bit to much... next time it will be called 'Forest Cloud Messaging' .... who knows ?
It's still from Google.... 

Maybe it's best to only change the URL? This because it's to nested (you for example missed the 'blockly' part) and user scripts might also fail

And the only change was the URL

**Comment by Olifant1990** [comment]
You are right.
Maybe is it an idea, now I am this far, to redo the renaming part to a subsystem name like google?
Then it is clear what is meant by everyone?
And indeed, I need to have a look to blockly.
But all current custom (lua) custom scripts keep working with "gcm". See https://github.com/domoticz/domoticz/pull/3293/files?file-filters%5B%5D=.cpp&file-filters%5B%5D=.html&file-filters%5B%5D=.js&owned-by%5B%5D=#diff-845061517fbd204974d96e03e8dc720f rows 129+

**Comment by gizmocuz** [comment]
Okey , maybe we leave it at google, and just rename the URL
As you made this in a separate pull request, we use this one over this
Thank you again

**Comment by Olifant1990** [comment]
Not sure what you mean by "maybe we leave it at google, and just rename the URL"
is it: "yes, please rename the new FCM indeed to Google and we are going to use this in future" or "no, back to GCM (undo) and just rename the URL"

**Comment by gizmocuz** [comment]
Sorry i meant, "no, back to GCM (undo) and just rename the URL"
Like i did at commit 
https://github.com/domoticz/domoticz/commit/e9d52623a88aff7cbb8b8f4d043b61538cc96482

**Comment by RunnicFusion** [comment]
When will this fix be released into the stable version of Domoticz?

**Comment by gizmocuz** [comment]
@RunnicFusion , no need to ask this question twice in two different issues.
Your answer is inside the other issue

**Comment by gizmocuz** [comment]
@RunnicFusion , also note that you can compile the stable version yourself, and apply fixes

**Comment by brjhaverkamp** [comment]
Hi Gizmocuz,

Please accept this as a plea: I understand the simplicity of releasing a certain commit as stable and not branch of. But in cases like this it shows the limited flexibility. We are now having stable version where gcm does not work and a new release waiting for OZW1.6 to stablise. Could you please consider branching off a stable version and apply critical bugfixes there in future, so a stable release is usable for a wider user-base and a longer period?  
P.S. :I agree that in principle one can pull the source and compile your self. But not everyone is up for that.

**Comment by gizmocuz** [comment]
@brjhaverkamp , sure i understand you, but there are many more issues fixed in the beta, all waiting for a stable OZW 1.6
If you can not wait, how about using PushOver for the time being ?

**Comment by brjhaverkamp** [comment]
Hi Gizmocuz,

If the new stable is "imminent", for sure I can wait. But between the previous stable releases there was more than a year, iirc. So I was fearing a long waiting time. It felt like the best for your side as well, since it would reduce the pressure from all us (over)eager users for the next stable release:-) 

I still hope you can start a similar workflow, with the stable branch still getting some bugfixes for a while, while the development branch goes full steam with the latest and greatest feature additions.  From other projects I have seen, I think this is quite common and works well. It allows the non-bleeding edge users (like myself) to be able to have very stable product by only committing the critical bug-fixes to 2 branches(stable and development) And when the development branch has moved so much forward that backporting is a major hassle, the backporting stops.

**Comment by gizmocuz** [comment]
@brjhaverkamp , there the previous stable was not that long ago, and of course i would love to release a new one.
Seems like the OZW 1.6 switchover is almost perfect, so have you tried it ?

**Comment by brjhaverkamp** [comment]
@gizmocuz , sorry, I'm a bit more adventurous with other OS software, but home automation has too much of a WAF impact. And I currently have no setup to easily try development releases. So I use only the stable releases and tend to forget it is there. It just works. (mostly;-))
I'll wait patiently, as it seems the new stable with OZW 1.6  (and the GCM fix) will be out reasonably imminent.

Regards,

Bert

**Comment by gizmocuz** [comment]
@brjhaverkamp , well it's not that hard to make a copy of the current stable folder, install/upgrade-to the beta and test

**Comment by brjhaverkamp** [comment]
Hi all, I see there is still no stable release with this solved. Is there a timeline for it now?

**Comment by gizmocuz** [comment]
Almost, but as you might know, it is the beta renamed to stable, so better to test/upgrade to the stable

**Comment by brjhaverkamp** [comment]
Hi Gizmocuz.

Much appreciated! Looking forward to upgrading.
And we had this discussion before:-) You know my preference for stable releases and not upgrading to a beta release where you don't know the state of development at that point in time. And it gives the freedom to sort of separate bugfixes from feature development.

**Comment by xztraz** [comment]
could you also migrate the database over to fcm instead of gcm on all notifications.

**Comment by rwaaren** [comment]
> could you also migrate the database over to fcm instead of gcm on all notifications.

This is already done in build 11925 (  87bad52e2 ) DB_Version 143

**Comment by xztraz** [comment]
did not migrate gcm to fcm in -2020.2 update. had to change all notifications.

**Comment by gizmocuz** [comment]
@xztraz , "gcm" is/should still be handled in the scripts and you should see a status log message saying it is deprecated and that you should use fcm
Could you copy/paste a script where this does not work ?

**Comment by Olifant1990** [comment]
@gizmocuz Didn't you add this deprecated message after stable release? As of commit https://github.com/domoticz/domoticz/commit/2959863bb2e7a71a0febdb040556e64d305fdfc5?
I then found my lua scripts not working anymore and then you added this message (so solved for me, as I update with beta releases)

**Comment by gizmocuz** [comment]
@Olifant1990 , I thought it was in 2020.2 already....
In not, then @xztraz could update to the beta version

**Comment by xztraz** [comment]
it was just the notification on switches and temps in gui. no script.  it still contained gcm. no biggie but would be good if it where done automatically.  i'm going with stable :)
