### ISSUE TITLE
Gas sensor z-wave not work

### ISSUE THREAD

**Issue by ClavosPL** [domoticz/domoticz#3295]
OpenZWave USB
Version: 1.6-412-g97a25f5c-dirty

DOMOTICZ 4.10854 beta

Gas Sensor Zipato system Z-Wave dont work, dont change sensor state

Gas Alarm On:
2019-06-04 20:28:02.301 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 29 (0x1d), CommandClass: ALARM, Label: Gas, Instance: 1, Index: 18
2019-06-04 20:28:06.988 OpenZWave: Value_Added: Node: 29 (0x1d), CommandClass: ALARM, Label: Gas, Instance: 1, Index: 18

--------------------------------------
Z-wave Control Panel:

Gas sensor test on
![Gas system test on](https://user-images.githubusercontent.com/16576679/58904729-607fff00-8708-11e9-84c5-b7d240a338c9.PNG)

Gas sensor test realease
![Gas system test off](https://user-images.githubusercontent.com/16576679/58904659-46deb780-8708-11e9-954a-f2dfd1e517d4.PNG)

**Comment by petergebruers** [comment]
@ClavosPL thank you for reporting this.

@gizmocuz You may already know this, but I felt like "let's try to understand what is going on"
I think the code to detect the "Gas" label (in meter labels) messes with the reporting of the similarly named Alarm "Gas".

Line 2795 if I comment out vLabel.find("Gas") the alarm gets detected properly. Not a fix, just interesting... Fixes the "Tried adding value, not succeeded!" message.

```
	if (
		(vLabel.find("Energy") != std::string::npos) ||
		(vLabel.find("Power") != std::string::npos) ||
		(vLabel.find("Voltage") != std::string::npos) ||
		(vLabel.find("Current") != std::string::npos) ||
		(vLabel.find("Power Factor") != std::string::npos) ||
		//(vLabel.find("Gas") != std::string::npos) ||
		(vLabel.find("CO2 Level") != std::string::npos) ||
		(vLabel.find("Water") != std::string::npos) ||
		(vLabel.find("Moisture") != std::string::npos) ||
		(vLabel.find("Tank Capacity") != std::string::npos)
		)
```

V4.10885 Build Hash: c21cfa71b-modified

**Comment by gizmocuz** [comment]
@petergebruers , it used to work when we used the 1.4 library, but i think i made some coding faults...
Do you know what the vLabel is ? and the vOrgIndex ? (vID.GetIndex())
I might also have two classes mixed (Alarm and SensorAlarm)

**Comment by petergebruers** [comment]
I don't understand this part of the Domoticz cooe yet, but I will get there, eventually.
I can probably answer you when I run the debugger, or I can provide you with some code to inject "gas alarm" into Domoticz.

**Comment by gizmocuz** [comment]
@petergebruers , i just found a gas sensor ;) and the vOrgIndex = 18 (ValueID_Index_Alarm::Type_Gas)
I am investigating this now....  It goes already wrong in the include phase.... hope to have some positive news soon.
(label was 'Gas', which is correct, but internally the device/value is not found somehow)

**Comment by petergebruers** [comment]
I am not at home, from the top of my memory, when you don't comment that "gas" line one of those things you ask has an extra dot and an extra number, and comparison fails. Does this help?

**Comment by gizmocuz** [comment]
Yes i already found it... (And thanks for looking at this as well!!) but the whole scale id was not needed by the alarm class.
It was already removed from the 'AddValue' routine, but not from the 'UpdateValue'
Just pushed a new commit, but I think i can simplify it even more

@ClavosPL, could you test with beta 10888 ?

**Comment by ClavosPL** [comment]
Ok working

Domoticz add a new device
"Alarm Type: Gas 18 (0x12)"
------
Alarm Type: Gas 18 (0x12) | General | Alarm | Event: 0x00 (0), if GAS is ON then Event: 0x02 - without history
------
the old switch device works normally, and change state to and log history
