### ISSUE TITLE
Updating barometer with json/dzvents doesn't change ForecastStr

### ISSUE THREAD

**Issue by felix63** [domoticz/domoticz#3299]
If I use dzvents or json to update a barometer value (barometer and forecast) ForecastStr becomes 'Unknown' instead of correct value.

**Comment by rwaaren** [comment]
I don't see this behavior when updating a barometer with the JSON command, nor if I update it using the updateBarometer() method of dzVents.
Happy to help you with this on the forum if you post your question there.
Please include your version and the exact commands you use when you experience this when posting the issue.
