### ISSUE TITLE
Xiaomi: Vibration sensor Aqara

### ISSUE THREAD

**Issue by kitopopo** [domoticz/domoticz#3300]
.... ?

**Comment by kitopopo** [comment]
Hello,

I am trying to use a vibration sensor aqara so that depending on the wind my awnings are closed. The problem is that the vibration sensor has 3 levels of vibration adjustment (high, medium and low). Selecting the setting "high" (maximum value) the sensor is detecting vibration every minute and my awnings would close very fast.
The vibration sensor has a function in the mihome app called "vibration curve" with which I get a graph where I can see the value of "Strenght" as a function of time. I attach a picture
Would you be so kind to implement the "Strenght" value in domoticz so we can use this value? It would be very interesting to be able to use the "strenght" value in domoticz to control the closing of awnings depending on the force of the wind.
Thank you for your cooperation . Best regards.

![Vibration curve](https://user-images.githubusercontent.com/51416982/58977679-7bb34300-87ca-11e9-832f-b05215d57a19.jpg)

**Comment by DAVIZINH0** [comment]
Great idea! it will be a great feature for this sensor!

**Comment by gizmocuz** [comment]
For what hardware is this ?

**Comment by kitopopo** [comment]
Hi,

This hardware is a device from xiaomi. Is a aqara vibration sensor. Do you need have the xiaomi gateway for add this device. This device measure the vibrations. Have 3 levels: low, medium and high. Also have a vibrarion curve in the xiaomi home app but no is possible use this curve or the strenght value with domoticz. 

Best regards.

**Comment by gizmocuz** [comment]
Thanks i updated the title of your issue, so Xiaomi developers could have a look at this.
(I still need to start beginning to play with this hardware!)

**Comment by kitopopo** [comment]
I think is better that domoticz developers maybe can add this feature in domoticz ( strenght value ) . The strenght value in the xiaomi app works correctly. Is interesting that we can use the "strenght value" in domoticz to be able close my awinds depending of wind speed.

Regards and thanks

**Comment by kitopopo** [comment]
Can you update again the tittle of my issue for send this issue to domoticz developers?

Thanks again

**Comment by kitopopo** [comment]
Hello, I apologize, I did not understand the change of title. Now I understand. My english level is low. thanks for everything

Bedt regards

**Comment by pipiche38** [comment]
What type of Domoticz widget do you suggest to use to track the strength ?

**Comment by gizmocuz** [comment]
I CustomSensor ?

**Comment by DAVIZINH0** [comment]
I thing the important is register this value strength, that now is imposible to monitor.
one its monitor we can make scripts with this value.
Maybe the solution is simple as a custom sensor with "straingh" unit?
I see my log and my min value is 3 and my max value is 109,6

**Comment by kitopopo** [comment]
Hello,
Yes, I also think it would be a good idea to have a custom sensor that shows "strainght unit" because the value of the force ranges from 0 to 999. It would be great to use this value to use it in domoticz scripts. I have the vibration sensor attached to the arm of an awning, and depending on the force value chosen by me, I could close the awnings if the wind blows too hard.
Thanks for your cooperation. a cordial greeting

**Comment by pipiche38** [comment]
On the Zigate plugin which is capable to pair Xiaomi devices and Vibration too, we have a dedicated widget for Strength  and a Text Widget for Orientation

<img width="817" alt="Screenshot 2019-09-01 at 18 56 32" src="https://user-images.githubusercontent.com/8291674/64079635-3bd8fa80-ccea-11e9-8da6-9a3ecf527ec3.png">

**Comment by kitopopo** [comment]
> On the Zigate plugin which is capable to pair Xiaomi devices and Vibration too, we have a dedicated widget for Strength and a Text Widget for Orientation
> 
> <img alt="Screenshot 2019-09-01 at 18 56 32" width="817" src="https://user-images.githubusercontent.com/8291674/64079635-3bd8fa80-ccea-11e9-8da6-9a3ecf527ec3.png">

Hello dear friend,

Thank you for your comment.
Yes, I am sure that with zigate it is possible to use the vibration curve, but most users only have the xiaomi gateway. Anyway, thank you very much for the information. Thank you

**Comment by waltervl** [comment]
Can be closed?
