### ISSUE TITLE
edit icon

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#3305]
Changing the  icon for lights with type ARC does not work in edit window / The switch Icon sub window is not shown in the LightEdit tab for this type of switches. Does work for other types.

See forum postings
https://www.domoticz.com/forum/viewtopic.php?f=6&t=27162#p=215910
https://www.domoticz.com/forum/viewtopic.php?f=6&t=27375#p=211237
https://www.domoticz.com/forum/viewtopic.php?f=6&t=28249#p216487

clearing caches / change to other browser does not change the behavior

**Comment by gizmocuz** [comment]
Thanks, will be solved in a upcoming beta version!
