### ISSUE TITLE
S0 Meter stops receiving data.

### ISSUE THREAD

**Issue by xztraz** [domoticz/domoticz#3307]
DOMOTICZ V4.10881 RPI

My S0 Energy sensor stopped working 30-05-2019 (updating betas continuously)

![image](https://user-images.githubusercontent.com/25690871/59194308-e5479e80-8b88-11e9-81f0-ecbbcda2ded5.png)

![image](https://user-images.githubusercontent.com/25690871/59193530-4de14c00-8b86-11e9-9615-47403823841d.png)
if i go inte **set mode** under hardware i find this..
![image](https://user-images.githubusercontent.com/25690871/59193653-b7615a80-8b86-11e9-84c9-f1a4b4625651.png)

log says this during startup
`Jun 10 13:52:29 raspberrypi domoticz: S0 Meter: Using serial port: /dev/ttyACM1`

the settings page seem to have settings missing. not sure if thats the problem?

**Comment by gizmocuz** [comment]
Don't think so... it has also not been touched for a long long .... long time !
(You can check this before by looking in the repository, selecting the S0 meter class/file, and press the history button)

ACM1 ? maybe it's the wrong port ? Did you try using putty or another serial reader to check if it is receiving data at all ?

**Comment by xztraz** [comment]
i can't change the port via gui any more so a bit hard to test another port. i haven't moved the port since it was working.

serial port gives data

```
pi ~ $ sudo cat /dev/ttyACM1
ID:29668:I:10:M1:2:34093:M2:0:0:M3:0:0:M4:0:0:M5:0:0
ID:29668:I:10:M1:2:34095:M2:0:0:M3:0:0:M4:0:0:M5:0:0
ID:29668:I:10:M1:3:34098:M2:0:0:M3:0:0:M4:0:0:M5:0:0

```

**Comment by xztraz** [comment]
i see this in previous logs
`9652882:May 30 19:53:37 raspberrypi domoticz: S0 Meter: ID: 29668, Version: S0 Pulse Counter V0.5
`
but not after it stopped saving data.

**Comment by xztraz** [comment]
it was actually working now! weird. haven't changed anything. closing. user error probably but cant figure out what i did. and port is changable if just selecting the device without pushing the set mode button of course... :D

**Comment by gizmocuz** [comment]
We haven't change a thing either... Great it's working again

**Comment by xztraz** [comment]
i think i might have powercycled the rpi and that restarted the usb thingie. if it happens again i'll check serial data to see if its running some weird numbers or if it have hanged. thanks for the help.

**Comment by xztraz** [comment]
Got problems again.

I get values from sensor on serial interface
```
ID:29668:I:10:M1:3:186554:M2:0:0:M3:0:0:M4:0:0:M5:0:0
ID:29668:I:10:M1:4:186558:M2:0:0:M3:0:0:M4:0:0:M5:0:0
ID:29668:I:10:M1:4:186562:M2:0:0:M3:0:0:M4:0:0:M5:0:0
ID:29668:I:10:M1:4:186566:M2:0:0:M3:0:0:M4:0:0:M5:0:0
ID:29668:I:10:M1:4:186570:M2:0:0:M3:0:0:M4:0:0:M5:0:0
```

it stopped working after a restart of domoticz.

did a power cycle.
```
cat /dev/ttyACM1
ID:29668:I:10:M1:4:60:M2:0:0:M3:0:0:M4:0:0:M5:0:0
ID:29668:I:10:M1:4:64:M2:0:0:M3:0:0:M4:0:0:M5:0:0
ID:29668:I:10:M1:5:69:M2:0:0:M3:0:0:M4:0:0:M5:0:0
ID:29668:I:10:M1:3:72:M2:0:0:M3:0:0:M4:0:0:M5:0:0
ID:29668:I:10:M1:4:76:M2:0:0:M3:0:0:M4:0:0:M5:0:0
```

still dead..  something is unstable.  can't pin-point what.  the port is working as seen. and same port used by hw
```
Jun 15 22:11:59 raspberrypi domoticz: S0 Meter: Using serial port: /dev/ttyACM1
Jun 15 22:11:59 raspberrypi domoticz: S0 Meter: Worker started...
```

DOMOTICZ V4.10897

**Comment by xztraz** [comment]
maybe this:  signed int?
![image](https://user-images.githubusercontent.com/25690871/59556008-1591a180-8fbc-11e9-8817-3c46b474b7c9.png)

**Comment by gizmocuz** [comment]
No we use doubles... should not give a issue

**Comment by xztraz** [comment]
haven't seen this problem in a while now so closing. probably human error
