### ISSUE TITLE
Z-wave, nodes, pushing refresh node info and then refresh looses node id, type, manufacturer and configuration

### ISSUE THREAD

**Issue by xztraz** [domoticz/domoticz#3308]
DOMOTICZ V4.10881 RPI

some new problem on refresh node info.

selected node 009
pushed, request current stored values
and after a minute refresh node info on node 009 (node 008 untouched as reference)

![image](https://user-images.githubusercontent.com/25690871/59194802-78350880-8b8a-11e9-969e-b8b1b654737f.png)

log:
```
Jun 10 14:15:54 raspberrypi domoticz: OpenZWave: Node Removed. HomeID: 3698476673, NodeID: 9 (0x09)
Jun 10 14:15:55 raspberrypi domoticz: OpenZWave: Received timeout notification from HomeID: 3698476673, NodeID: 9 (0x09)
Jun 10 14:15:56 raspberrypi domoticz: OpenZWave: Received timeout notification from HomeID: 3698476673, NodeID: 9 (0x09)
Jun 10 14:15:57 raspberrypi domoticz: OpenZWave: Received timeout notification from HomeID: 3698476673, NodeID: 9 (0x09)
Jun 10 14:15:58 raspberrypi domoticz: OpenZWave: Received timeout notification from HomeID: 3698476673, NodeID: 9 (0x09)
Jun 10 14:15:59 raspberrypi domoticz: OpenZWave: Received timeout notification from HomeID: 3698476673, NodeID: 9 (0x09)

```

result: empty config, id set to 0x0000 and also type
![image](https://user-images.githubusercontent.com/25690871/59194914-deba2680-8b8a-11e9-8e0f-e6df64cb2231.png)

**Comment by xztraz** [comment]
ozw control panel just turned blank after i did the above 
![image](https://user-images.githubusercontent.com/25690871/59195260-c39be680-8b8b-11e9-99cd-7b47adc6f0c4.png)

and after a reboot nodes page look like
![image](https://user-images.githubusercontent.com/25690871/59196240-6c4b4580-8b8e-11e9-89c7-f08d4e58522b.png)

**Comment by gizmocuz** [comment]
Well if you press refresh, it will drop all settings.
If your log displays "Received timeout notification", it can not retrieve new settings
Did you try waking up the node, or pressing (tripple..) the magic button ?

**Comment by gizmocuz** [comment]
You can also try from the node dropdown to select again the option 'include' and tripple press the magic button

**Comment by xztraz** [comment]
tried tripple click before and after i push refresh node info. but to no avail.. 
still timeouts in the log.

i can still control the lights. so that communication works. 
i think there is something wrong with ozw. since the control panel goes dead and so. can i get log from ozw to file?

**Comment by gizmocuz** [comment]
It looks like no node information frame is send to the controller.
Made some big changes in the current beta version, maybe it is solved, but you might need to refresh some node information as the cache file is cleared

**Comment by xztraz** [comment]
after upgrade to DOMOTICZ V4.10897 and restart. ozw cp works again and all configuration and names and such now is visible again in domoticz zwave setup page. hammering on refresh node info and request current stored values don't seem to break stuff now.  Great!  it also seem to update configuration values from node.  Seem like its fixed!

![image](https://user-images.githubusercontent.com/25690871/59506643-0f5ed080-8ea9-11e9-903b-aafcc2d8cb11.png)
