### ISSUE TITLE
Error and  timesuntemplate not found

### ISSUE THREAD

**Issue by sergiotropea** [domoticz/domoticz#3310]
Hi,
my Domoticz version is: 4.10890
Build Hash: b9d6c8744
Compile Date: 2019-06-10 15:56:25
dzVents Version: 2.4.23
Python Version: 3.4.2 (default, Feb 10 2019, 17:57:51) [GCC 4.9.2]

I have problem with _timesuntemplate_. In any page i find this error:

`:8000/timesuntemplate:1` Failed to load resource: the server responded with a status of 404 (Not Found)`

I thing that this is correlated with event page problem. Infact i cant's do anythings becouse the system doesn't show the dashboard with blockly or code... etc... 
![screenshot-192 168 1 79-8000-2019 06 10-19-24-33](https://user-images.githubusercontent.com/25485825/59213561-7896c900-8bb5-11e9-96f8-af7f90f4e079.png)

**Comment by gizmocuz** [comment]
Did you clear the browsee cache and appcache? Tried another browser or in private mode?
(Note that browser cache and AppCache are two different things)
