### ISSUE TITLE
Darksky Rain not working with data push

### ISSUE THREAD

**Issue by jambees** [domoticz/domoticz#3311]
Domoticz V4.10891 (beta)

Darksky rain device doesn't seem to work properly with data push. I've tried all the various types of data push (FibaroLink, HTTP, GooglePubSub, InfluxDB) and when selecting the device name from the dropdown of the Darksky rain device, the Value To Send dropdown only has Unknown in it. I believe it should have Total Rain and Rain Rate. I wanted to use the InfluxDB push type. I find no rain series in influxDB even if I add this data push entry for this device with the Value to Send set to Unknown. I was running the latest stable version and encountered the same problem, have switched to the latest Beta but that seems to have the same issue. 

I've tried creating a new Darksky hardware item with a different name, letting it create a new set of sensors and then try to set up a data push with the new rain device but same issue.

![image](https://user-images.githubusercontent.com/51675963/59216745-34ef8f80-8bb4-11e9-8e49-cf8930c2974d.png)

![image](https://user-images.githubusercontent.com/51675963/59216805-5cdef300-8bb4-11e9-95ef-eec185fba9ff.png)

![image](https://user-images.githubusercontent.com/51675963/59216895-9fa0cb00-8bb4-11e9-97a7-7565eef45564.png)

**Comment by gizmocuz** [comment]
Thanks for reporting. Seems that the rain subtype (RainByRate) was not implemented throughout Domoticz.
I added support for this subtype, and it should work now in beta 10893

**Comment by jambees** [comment]
Confirmed working in 10893 and exporting into InfluxDB now. Thanks for rapid fix!
