### ISSUE TITLE
Blockly events not working on latest beta

### ISSUE THREAD

**Issue by bennydente** [domoticz/domoticz#3314]
Hi, i'm on version Version: 4.10897 on ubuntu 18.04 but something is wrong on blockly events.
this simple test events never triggered.

![Capture](https://user-images.githubusercontent.com/22501791/59341525-4fd31880-8d08-11e9-99dd-a36a0b972286.JPG)

i have a cronjob that every minute:
- set clock60sec variable to 1
- sleep 30sec
- set clock60sec variable to 0

so, i aspect that the event is triggered every minute. but not.... :-(

**Comment by rwaaren** [comment]
Better to post this on the forum first. 
Have you tried to change the user variable on the GUI ? It might just be the case that the Blockly will get fired then.

**Comment by bennydente** [comment]
hi, yes, i tryed via GUI and i can set every integer value. also i see the variable change every 30 second according cronjob.

**Comment by bennydente** [comment]
hi, i better test, and if I change the variable value by GUI the event is triggerd. if I change the value of varialbe from URL by json command via cronjob, the event is not triggered.

**Comment by rwaaren** [comment]
Can you please close this issue here and continue discussion on [ the forum topic about this ](https://www.domoticz.com/forum/viewtopic.php?f=6&t=28333&p=217009) ?
as you write here in your last update: "the event is triggered."

**Comment by bennydente** [comment]
hi, are you planning solve bug in next release? thakns for you job.
