### ISSUE TITLE
Custom Icons not working

### ISSUE THREAD

**Issue by Trigun** [domoticz/domoticz#3316]
Hi, I found out that uploading the custom icons are not working anymore.
also after deleting all the cash and history. nothing happens. this is an old issue as it happend before but I believe its there again. thank you!

**Comment by gizmocuz** [comment]
No issue here... maybe your custom icon zip file is wrong.
As this is seems to be an old issue for you, i would suggest to clear the AppCache and Browser Cache, use chome browser, use it in private mode, and try downloading a custom icon from

https://drive.google.com/drive/folders/0B-ZLFoCiqzMRfnZXV3RiTU1pdUEyWVF2TEpNQmxBN2xhUWo5MjhiamY0cVEwanFUM0Z0UVE

**Comment by gizmocuz** [comment]
And please use the Forum !
