### ISSUE TITLE
Intergas Incomfort Gateway

### ISSUE THREAD

**Issue by twpeltenburg** [domoticz/domoticz#3317]
The newer firmware on the Intergas Incomfort (LAN2RF) gateway requires a username and password, however I cannot put these in while adding the hardware. I'd rather not use a 3d party plugin for this hardware, but I'd like to use Domoticz' built in hardware.

**Comment by gizmocuz** [comment]
@twpeltenburg , could you send me a PM on the forum (gizmocuz)

**Comment by stingone** [comment]
> The newer firmware on the Intergas Incomfort (LAN2RF) gateway requires a username and password, however I cannot put these in while adding the hardware. I'd rather not use a 3d party plugin for this hardware, but I'd like to use Domoticz' built in hardware.

Still not changed in the latest version. Only manualy in the lua scripts.

**Comment by gizmocuz** [comment]
@stingone , did you had a look at the code in Domoticz and tried to add the needed changes ?
Can you verify if you can get data when you issue:

`http://<username>:<passwoprd>@<ipaddress>:<port>/data.json`

like

`http://username:passwoprd@192.168.20.10:1234/data.json`

**Comment by stingone** [comment]
> @stingone , did you had a look at the code in Domoticz and tried to add the needed changes ?
> Can you verify if you can get data when you issue:
> 
> `http://<username>:<passwoprd>@<ipaddress>:<port>/data.json`
> 
> like
> 
> `http://username:passwoprd@192.168.20.10:1234/data.json`

The JSON file was pointing to the wrong direction. i changed it,

Got it up and running now :)
