### ISSUE TITLE
No control of Z-Wave in Domoticz after certain time

### ISSUE THREAD

**Issue by SVdHeyden** [domoticz/domoticz#3319]
Configuration:

### Hardware: 
     CubieTruck
     Zwave USB stick: Aeotec Z-Stick S2
### Software: 
     Armbian 5.73 Linux 9 Stretch (4.19.25-Sunxi
     Domoticz version 4.10717 build hash: b38b49e5
     OZW USB Version:1.4-3335-g74e05982-dirty (don't know what 'dirty' means but it was there al the time)

After a few days Domoticz isn't able to control Z-wave devices anymore. commands are sent but nothing happens.
After a restart of the Domoticz server (not a reboot of Linux) and the removal of the file Domoticz/Config/zwcfg_****.xml (removal of the file is actual not needed) the system is working again for a few days. 
For the USB Zwave controler a udev rule is created to be sure that Domoticz is always looking for the correct port. udev rule is given below:
`SUBSYSTEM=="tty", SUBSYSTEMS=="usb", ATTRS{idVendor}==10C4", ATTRS{serial}=="0001", ATTRS{idProduct}=="ea60", SYMLINK+="ttyUSB21", OWNER="smarthome", Group="dailout"`

Sometimes after a restart of the Domoticz server (procedure as given above) the server isn't finding the USB Zwave controler while the SYMLINK is still active. Changing the USB port to the physical one and back to the SYMLINK the devices are found back in the hardware tab.

This problem started in the previous version of Domoticz. The version before the previous version I didn't have this problem. System was running for years without any issue. It is not due to hardware issues as I have the issue on different hardware platforms.

What kind of information do I need to deliver to solve the issue?

Thanks

**Comment by gizmocuz** [comment]
@SVdHeyden , you should not need the udev rule and see the the serial port by full id from the dropdown these days.
We are currently working on implementing OZW version 1.6, which is almost done and could solve your issue

Do you still receive anything ? maybe you have a zwave node that reports power, or a zwave temperature sensor ?
What hardware type is the node that can not be controlled ? Do you have different hardware, they all can not be controlled ?
Could you also try (yes this sounds strange!!) to use another power adapter, which supports more amps ?
I had this issue myself, also causing domoticz to crash (the whole armbian system)

**Comment by SVdHeyden** [comment]
Hi,

Thanks for your reply,


  *   Concerning the udev rule:
Ok I will use the port with the full id and remove the udev rule
  *   When the problem appear, none of the devices react on commands and indeed there are devices which are reporting Voltage, Current , Power but those are reporting by polling the devices.
Those devices are of the brand Qubino: ZMNHTDx smartmeter S4 S5 S6+. Those devices are able to report automatic however I didn't succeed to get them working in that way.
So to summarise - none of the devices are responding when the issue happens. I think the connection with the Z-wave controller is lost.
  *   I have indeed devices of different brands like; Fibaro, Qubino, TKB Home. Most of the devices are from Fibaro, two energy measuring devices from Qubino and one device from TKB home.
  *   Concerning the power addapter:
The CubieTruck has an UPS on board. So a battery is included in the power management, so I would be supprised if the power addapter will be the issue . By the way I've tried this setup on different hardware and experienced the same problem. So according to me it is not linked on hardware what the controlling part concerns.

Thanks

Greetings

**Comment by gizmocuz** [comment]
Yes it indeed looks like the communication is lost between Domoticz, OpenZWave and the USB Controller somehow...
Thats why I was thinking about a to low power supply

There have been made a lot of changes in the current beta version , which is using OZW version 1.6, but it is not quite ready for production.... 
It is for testing if you like... but then i would suggest to make a complete backup of your Domoticz folder, so you can always switch back (first stop Domoticz)
It might be worth checking this as your issue happens in a few days.
Please do note that the zwave cache file has changed, and all nodes will be asked to send there information frames.
It could be that some nodes needs to be triggered to send it (battery powered nodes, tripple click on a small button). When needed, you can now also select a node and press the new button 'Refresh Node Info'

**Comment by SVdHeyden** [comment]
Thanks fort he reply,

I will consider to install the beta version when I have the issue again. I've changed the USB to the serial port conteining the full id. If after a few days the issue appaers again I will load the beta version.

Keep you posted

Thanks


Greetings

S. Van der Heyden
P Before printing, think about the environment

**Comment by petergebruers** [comment]
Chiming in because I am an OpenZWave contributor



> Those devices are of the brand Qubino: ZMNHTDx smartmeter S4 S5 S6+. Those devices are able to report automatic however I didn't succeed to get them working in that way.

Fishwaldo, the maintainer of OZW has tested the SmartMeters recently (but probably different firmware) and they should be OK on 1.6 - there has been a discussion about 1.4 and the correct settings of the device. You might want to join this discussion:

https://groups.google.com/forum/#!topic/openzwave/kOL09dq4Mc0

I don't own such a device, I cannot confirm any of that.

> I think the connection with the Z-wave controller is lost.

The OZW_Log.txt would show signs of that, but it's best to have it in debug mode (which makes the file grow rather quickly).

> Sometimes after a restart of the Domoticz server (procedure as given above) the server isn't finding the USB Zwave controler while the SYMLINK is still active. Changing the USB port to the physical one and back to the SYMLINK the devices are found back in the hardware tab.

Not sure what is going on. When the stick resets, it drops from the USB bus for 1-2 seconds but afaik OZW does not sent a soft reset. So it should be always available. It has been noted that names like /dev/ttyACM* are not "stable" eg ACM0 and  ACM1 can swap places after reboot.

But one issue that can crop up is running software that scans or uses the serial ports of your system, like "modem manager" (don't know the details, might be "ubuntu" related) and some UPS software. OZW does not really lock the port for exclusive use and that kind of software can inject bytes or steal them, making OZW go into retry mode, and (sometimes) mark nodes as dead.

It is hard to tell what's going on. I do think we can rule out power supply, or "broken hardware". Those dongle's almost never fail.

I agree with @gizmocuz - it is worth trying the beta but "the usual warnings apply". It depends on many factors, I think only you can decide...

**Comment by SVdHeyden** [comment]
Thanks for the reply,

It seems that there are still issues with those devices. A solution isn't yet defined - pointing back to the Vendor.
For the moment with the polling approach it is working. I will follow the discussion  to see if there is a solution coming out.

Thanks


Greetings

S. Van der Heyden
P Before printing, think about the environment

**Comment by gizmocuz** [comment]
@SVdHeyden, as this does not seem a Domoticz issue I am closing the issue, feel free to open it again if needed
