### ISSUE TITLE
Implement feature chack and autupdate Domoticz

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#332]
Hello
Is any chance to add to Domoticz option autoupdate ? In settings add option for user:
-chack and autoupdate
-Frequency check: every day, every week, every month
-Time to chack and autoupdate

If it was check Domoticz automaticaly check and if available newer version download and iinstall automatilac newer version. It was very good option because now Domoticz not show info that new version is available.

Thanks
Peter.

**Comment by pepijng** [comment]
Again this is NO ISSUE. 
Github is not the place for this kind of requests!

Please read the documentation (manual/wiki/forum), this option is already there.
You don't want full automatic updates because a lot of people have customized there installation, just updates from the GUI.

If, in your situation, you want automatic updates it's easy to use a crontask/script for that.

**Comment by ghost** [comment]
Ok but is option manual check...It is in settings but i talk about automatic. Manual check example not work on WIndows and automatic also should be not working on WIndows and other sustem but will be support on Raspberry where most people use. In settings can be add info that this function not working on all systems and only work on Raspbbery

**Comment by pepijng** [comment]
Like i said, you can create scripts to implement this.
Please stop this this discussion here.

**Comment by nayrnet** [comment]
no automatic updates, no.. 

software of this nature should not be updating its self without supervision and approval, ever.

Domoticz is not a public service, the infrastructure is private and used by the people who own it.. This is not your web browser and has absolutely zero need for unattended updates.

Support Nightmare is all your asking for..

**Comment by gizmocuz** [comment]
Jees PiterEL why you write me emails about this, that i answer, and then post the same question here
Like said, not a good idea to update to the latest beta if not needed
