### ISSUE TITLE
Libcurl3 and libcurl4  @ sametime

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#3322]
Run always the last beta. on a odriod
Ubuntu server 18.04

Domoticz need libcurl3
And for dashticz i need libcurl4
When i install libcul3 the curl command is not working
after a update i need to install manually curl to get things working.

Only these 2 running @ the same time is not possible.
everytime i install libcurl4 domoticz is crashing.

Is there perhaps a solution to upgrade domoticz to the latses libcurl?
Or a other solution to run these two near eachother?

**Comment by gizmocuz** [comment]
I noticed on the Wiki (Dashticz topic) that it says Domoticz does not support serving PHP pages, which is not true at all.
(Made a quick note there on the wiki)

No idea why Dashticz needs libcurl4 ? i think you should be able to install both libraries at the same time

As the author of Dashticz is also running Domoticz, i must also assume

**Comment by gizmocuz** [comment]
Is this still an issue ?
