### ISSUE TITLE
Not able to get Fibaro door/window sensor 2 (fgdw-002) working properly

### ISSUE THREAD

**Issue by jockeastrom** [domoticz/domoticz#3323]
I have had a fibaro door/window sensor 2 lying around for some time and when I tried to get it up and running again I noticed that I can't get it to work in domoticz. I have had it working before.

The current list of devices for it is:
![image](https://user-images.githubusercontent.com/1738387/59542213-f8e66280-8f04-11e9-9cbd-3f7641f5d1f1.png)

Temperature is working fine.

As I remember it is the "Sensor" device (00011D00) that is of interest to follow open/closed state but this is not being updated after inclusion.

From the logs I can see the following while moving the magnet close and away from the sensor:

2019-06-15 00:37:44.932 (z-stick) General/Alarm (Alarm Type: Access Control 6 (0x06))
2019-06-15 00:37:44.934 (z-stick) Light/Switch (Access Control)
2019-06-15 00:37:44.930 Status: OpenZWave: Alarm received (Access Control: Door/Window Closed)
2019-06-15 00:37:53.735 (z-stick) General/Alarm (Alarm Type: Access Control 6 (0x06))
2019-06-15 00:37:53.737 (z-stick) Light/Switch (Access Control)
2019-06-15 00:37:53.734 Status: OpenZWave: Alarm received (Access Control: Door/Window Open)

Am I doing something wrong or has there been some breaking change in domoticz or openzwave that causes the device to not work properly?

I'm on the latest beta.

**Comment by gizmocuz** [comment]
Seems to be working fine.... the door switch that turns on/off when you use the magnet is 'Light/Switch (Access Control)'

**Comment by jockeastrom** [comment]
I was thinking that also but that switch started as "Off" and once the sensor was closed it reported "On". After that it only reports "On" events, never "Off". The log is showing "Alarm received..." for open/close events. Can I setup some switch and base its state on these alarms?

**Comment by gizmocuz** [comment]
Could you show some more logging ? i only see an closed and open ? looks fine from here...

**Comment by petergebruers** [comment]
@gizmocuz iirc you explained to me a very recently that the "switch" lumps together all "non clear alarms". EDIT: this is NOT the case for "Access Control", see explanation below.

From the logging I deduce that this sensor reports door open/close as:

```
Window/door is open | 0x16
Window/door is closed | 0x17
```

Both are NOT "clear" or actually "idle" as the specs call it and arguably depending on what it is used for both open and close can indeed be considered an alarm. Though most people probably expect "closed" to be a non-alarm condition but that's not how it is in the spec.

I would say, the switch object would indeed change once from "OFF" to "ON" but would never return bu this logic.

EDIT: source of this is "SDS13713 Notification Command Class, list of assigned Notifications.xlsx" in the public spec.

**Comment by gizmocuz** [comment]
@petergebruers , that's for the smoke type. Here we are talking about the 'Access Control' alarm type
This is handled here: OpenZWave.cpp Line 2707 

`if (vOrgIndex == ValueID_Index_Alarm::Type_Access_Control)`

Here you can see that 'case 0x17: 	// Door/Window closed' would set the switch to OFF, and 'case 0x16: 	// Door/Window open' should set the switch to ON

I need more logging from @jockeastrom  ... i only see one time a Closed/Open above, i want to see it two times after each other

**Comment by jockeastrom** [comment]
Below is a close-open-close-open sequence.

2019-06-15 17:23:30.528 (z-stick) General/Alarm (Alarm Type: Access Control 6 (0x06))
2019-06-15 17:23:30.532 (z-stick) Light/Switch (Access Control)
2019-06-15 17:23:30.524 Status: OpenZWave: Alarm received (Access Control: Door/Window Closed)
2019-06-15 17:23:30.533 Status: LUA: Device based event fired on 'Alarm Type: Access Control 6 (0x06)_ZWaveAlarm', value '23'
2019-06-15 17:23:30.533 Status: LUA: Device based event fired on 'Alarm Type: Access Control 6 (0x06)', value '23'
2019-06-15 17:23:34.109 (z-stick) General/Alarm (Alarm Type: Access Control 6 (0x06))
2019-06-15 17:23:34.112 (z-stick) Light/Switch (Access Control)
2019-06-15 17:23:34.104 Status: OpenZWave: Alarm received (Access Control: Door/Window Open)
2019-06-15 17:23:34.114 Status: LUA: Device based event fired on 'Alarm Type: Access Control 6 (0x06)', value '22'
2019-06-15 17:23:34.114 Status: LUA: Device based event fired on 'Alarm Type: Access Control 6 (0x06)_ZWaveAlarm', value '22'
2019-06-15 17:23:37.764 (z-stick) General/Alarm (Alarm Type: Access Control 6 (0x06))
2019-06-15 17:23:37.767 (z-stick) Light/Switch (Access Control)
2019-06-15 17:23:37.760 Status: OpenZWave: Alarm received (Access Control: Door/Window Closed)
2019-06-15 17:23:37.769 Status: LUA: Device based event fired on 'Alarm Type: Access Control 6 (0x06)_ZWaveAlarm', value '23'
2019-06-15 17:23:37.769 Status: LUA: Device based event fired on 'Alarm Type: Access Control 6 (0x06)', value '23'
2019-06-15 17:23:40.675 (z-stick) General/Alarm (Alarm Type: Access Control 6 (0x06))
2019-06-15 17:23:40.679 (z-stick) Light/Switch (Access Control)
2019-06-15 17:23:40.671 Status: OpenZWave: Alarm received (Access Control: Door/Window Open)
2019-06-15 17:23:40.681 Status: LUA: Device based event fired on 'Alarm Type: Access Control 6 (0x06)', value '22'
2019-06-15 17:23:40.681 Status: LUA: Device based event fired on 'Alarm Type: Access Control 6 (0x06)_ZWaveAlarm', value '22'

**Comment by petergebruers** [comment]
Oh, sorry, I am not online and had to guess :) That's OK then.

**Comment by gizmocuz** [comment]
@jockeastrom , could you show the log of the switch 'Access Control' ?

**Comment by jockeastrom** [comment]
2019-06-15 17:23:40 | On
2019-06-15 17:23:37 | On
2019-06-15 17:23:34 | On
2019-06-15 17:23:30 | On
2019-06-15 17:17:50 | On
2019-06-15 17:17:38 | On
2019-06-15 17:06:32 | On
2019-06-15 17:03:12 | On
2019-06-15 17:02:36 | On
2019-06-15 17:02:34 | On
2019-06-15 17:00:05 | On
2019-06-15 17:00:05 | On
2019-06-15 17:00:04 | On
2019-06-15 00:37:53 | On
2019-06-15 00:37:44 | On
2019-06-15 00:25:24 | On
2019-06-15 00:25:13 | On
2019-06-12 20:52:17 | On
2019-06-12 20:52:10 | On
2019-06-12 20:47:52 | On
2019-06-12 20:47:04 | On
2019-06-12 20:43:51 | On
2019-06-12 20:43:46 | On
2019-06-12 20:39:37 | On
2019-06-12 20:39:09 | On

**Comment by petergebruers** [comment]
Is that 1D34 or 1D00?

**Comment by jockeastrom** [comment]
It's from 00011D34.

**Comment by gizmocuz** [comment]
@jockeastrom , could you show the log of 1D00 ?

**Comment by jockeastrom** [comment]
1D00 only has an "Off" from when I included the sensor.

**Comment by gizmocuz** [comment]
Is there a configuration parameter that you can set to have it report as a Sensor Binary instead of a Basic Set ?

**Comment by gizmocuz** [comment]
@jockeastrom, can you program a little bit ? I wonder if the switch statement here is reached:

```
				if (vOrgIndex == ValueID_Index_Alarm::Type_Access_Control)
				{
					switch (intValue) {
```

Currently i am unable to make a new beta for the raspberry system (tomorrow again... machine got stuck!), but there have been some recent changes
Are you able to build yourself ?

https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source

**Comment by jockeastrom** [comment]
Sure, I can code. Haven't built domoticz but I will have a look later this evening. Thank you very much so far :).

**Comment by petergebruers** [comment]
I think you are suggesting there are 2 things going on here... One with reporting as Sensor or Basic Set and one as "alarm".
No, there is no parameter to select sensor binary. I am not sure what it is sending on lifeline. There is "group 2" which does this (quote from manual):

"2nd Association Group – “On/Off” is assigned to the device status - contact sensor (sends Basic Set command frames)."

> I wonder if the switch statement here is reached:

I am looking at the code and I'd say it is possible indeed that you don't get there (and then it does that "lumping thing isn't it)... I don't have a test device, sorry...

**Comment by gizmocuz** [comment]
@petergebruers , well the reason i asked, i have a Aeotec doorsensor, and this reports as basic or binary sensor, Domoticz needs to have the later configured.

@jockeastrom , Great !!!! Would be great if you could debug this. Maybe log the ...
Whoeps.... i think i have found the issue !
(Peter mentioned this as well before!)
I overwrite the intValue at some code above this... (i think i moved this piece of code to up some days ago).
I need to keep track of the original List value, and use that in the functions below.... let me quickly correct this...
(Still unable to build a new version for the 32bit raspberry)

**Comment by petergebruers** [comment]
@jockeastrom if you could do that, that would be awesome! Oh, @gizmocuz thinks he's found it, okay! Going to say it anyway, I build Domoticz on my Mac and it wasn't difficult, I had the right prerequisites and followed the instructions on the wiki. Assuming your on a nix system:

https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source#Raspberry_Pi_-_Build_Domoticz_from_source

**Comment by gizmocuz** [comment]
I corrected the code, and it should work now when you use the latest repository code... sorry about that!

**Comment by petergebruers** [comment]
> @petergebruers , well the reason i asked, i have a Aeotec doorsensor, and this reports as basic or binary sensor, Domoticz needs to have the later configured.

I've seen this mentioned on the Home Assistant forum quite a few times. I think it is not only Aeotec doing that, I have their Gen5 Motion sensor and it has that option as well. Also Philio Multisensors have some settings. Causes confusion and indeed the symption "I get no motion reports".

**Comment by gizmocuz** [comment]
@petergebruers , your correct about this... (and i own a philio sensor that does this)
Currently Domoticz ignores basic_set ... 
The reason for this is that a lot of hardware is advertising , let say, a binary sensor + a basic set, causing double switches to be created
You can see at the top of the Domoticz code in COpenZWave::AddValue that if COMMAND_CLASS_BASIC is received, it bails out
ZWave is already confusing... getting two switches for the same node is even more confusing

.. at least... that is what i remembered was the case

**Comment by petergebruers** [comment]
> The reason for this is that a lot of hardware is advertising , let say, a binary sensor + a basic set, causing double switches to be created

Makes sense, and Fishwaldo very recently made a proposal to add "flags" to a device's config file to indicate "interesting or not". It is not there yet and then the gateway builders still have to implement it.

On a Fibaro HC the config flag can "hide" a device. If there isn't such a file (which happens often if it is not a Fibaro module) then indeed you can get quite a lot of duplicates, because Z-Wave mandates backwards compatibility so the device manufacturers have to implement those duplicates.

Also the spec has specific instructions on how to handle Basic CC. The document "SDS10242 Z-Wave Device Class Specification.pdf" tells you what is mandatory and let's take for example a door lock:
```
5.6.4.2 Door Lock Specific Device Class
5.6.4.2.1.1 Basic Command Class Implementation
The basic command class MUST be implemented in the following way:
Basic Set = MUST be ignored to avoid unintentional operation. Cannot be mapped to another command class
Basic Get = Lock Get
Basic Report = Lock Report
```

Oh my! So if you would show this "Basic CC" in Domoticz then it would report state, but refuse to open or close, and that's intentional.

But I am probably digressing, by a fair amount. ;)

**Comment by jockeastrom** [comment]
Sorry that I haven't reported back. Didn't go as planned this weekend so I built domoticz today but then I realized that your change was included in the latest beta (4.10915) and the "Access Control" device is now reporting the Open/Closed state as expected. Good job!

**Comment by poudenes** [comment]
I have also some errors with those sensors. When my doors are open within some hours Fibaro sensors send something to Domoticz, Domoticz see that as a status change to close.

my neo cool cam Sensors work like a charm... I don't know how to help to find out why the fibaro ones change status in domoticz without actual close the door....

Im using: 
Version: 4.10717
Build Hash: b38b49e5
Compile Date: 2019-05-09 13:04:08
dzVents Version: 2.4.19
Python Version: 3.6.4 (default, Oct 10 2018, 09:47:26) [GCC 6.3.0 20170516]

**Comment by gizmocuz** [comment]
Is it possible to test this with the latest beta version ?
