### ISSUE TITLE
Zwave Valve control not able to switch

### ISSUE THREAD

**Issue by ClavosPL** [domoticz/domoticz#3325]
Domoticz V4.10906

Error sending command to Automatic Valve controler

The valve does not respond to on and off commands

After switching off the device from power for about 1 day, when the device does not detect the device and reconnects it. Then Hardware in openzvwae tab is = "Unknown" and valve works again

It starts to work until "Hardware" = G.R. GR105n Auto Valve + is refreshed like dis
![Zwave Valve control](https://user-images.githubusercontent.com/16576679/59549772-ca977000-8f62-11e9-90b6-1fafc2755cfd.PNG)
When description is unknown the valve works.

2019-06-15 11:35:49.218 Status: User: luki initiated a switch command (200/ZaworWody/On)
2019-06-15 11:35:49.218 Error: OpenZWave: Internal Node ValueID not found! (NodeID: 32, 0x20)

**Comment by petergebruers** [comment]
I am not sure if this is an OpenZWave problem or a Domoticz issue, let's try to find out. If it is OZW then it is my problem ;)

If you enable "accept new hardware" then in Z-Wave configuration Request an update from that node... You will get "Hardware" = G.R. GR105n (so it will stop working, sorry about that but cannot think of any other way). Then go in "Devices" and tell me which device are created for this node. Is it possible you get more than 1 switch and one of them works?

**Comment by ClavosPL** [comment]
ok i will try check this and post.

**Comment by ClavosPL** [comment]
Domoticz V4.10921

On more time:
yes domoticz create a new one device but the device is DEAD idx 202
--------------------
After approx. 24 hours off from power,  the valve has state as picture below
![Work at yunknown](https://user-images.githubusercontent.com/16576679/59976173-f9e05980-95c0-11e9-9855-d3d0cfd80028.PNG)

Hardvare is unknown but Switch works ok (idx200)
There are two switches, one of which is ok, in device tab as below
![Work 2 devices](https://user-images.githubusercontent.com/16576679/59976189-24caad80-95c1-11e9-9548-5adbb270512f.PNG)
the device idx 202 not working - switching it nothings change
IDX 200 is ok it works

When i go to get update node informatnion i have Hardware as below in hardware zwave tab:
![Not working hardware](https://user-images.githubusercontent.com/16576679/59976200-56dc0f80-95c1-11e9-99c3-fe053dfc3d89.PNG)

Then idx 202 not working, and idx 200 not working,
But idx 200 it changes state when I manually switch the valve (a button on the valve housing)

When i try change it in domoticz i have error like this
![error](https://user-images.githubusercontent.com/16576679/59976229-c0f4b480-95c1-11e9-9d9e-fe61ae7169df.PNG)

log 
2019-06-23 14:01:02.058 Status: User: Admin initiated a switch command (200/Workink_ZaworWody/Off)
2019-06-23 14:01:02.058 Error: OpenZWave: Internal Node ValueID not found! (NodeID: 32, 0x20)

in zwave control panel we have 
![gr105N TRU FALSE STATE](https://user-images.githubusercontent.com/16576679/59976259-2052c480-95c2-11e9-8f8b-1496d6fc793c.PNG)




.....dont now what happends
idx 200 it changes state when I manually switch the valve (a button on the valve housing)...

**Comment by gizmocuz** [comment]
Can you try this with the control panel ?

**Comment by ClavosPL** [comment]
Yes sorry ...
Domoticz V4.11079
Still nothing.

1. Unknown device working fine
![Hard valve unknown](https://user-images.githubusercontent.com/16576679/62833421-b5774e80-bc3e-11e9-9dad-e81868e88926.PNG)
![control panel unknown](https://user-images.githubusercontent.com/16576679/62833424-bf994d00-bc3e-11e9-9554-372129da5643.PNG)
![control panel unknown on_of working from CP](https://user-images.githubusercontent.com/16576679/62833427-c6c05b00-bc3e-11e9-9b44-d90c662a707c.PNG)



2 after refresh node info
Switching from domoticz device is impossible (error sending ....), but from Zwave control panel still possible.
![after refresh node info](https://user-images.githubusercontent.com/16576679/62833430-caec7880-bc3e-11e9-9911-32ffe21b5a70.PNG)

![Control panel after node refresh working on off from CP](https://user-images.githubusercontent.com/16576679/62833431-cde76900-bc3e-11e9-923d-1ae38b9864af.PNG)
in control panel on off action is possible

node info
![Controp panel node info](https://user-images.githubusercontent.com/16576679/62833435-df307580-bc3e-11e9-90f9-5be67aa688e9.PNG)

**Comment by gizmocuz** [comment]
@ClavosPL , OK, so after the refresh all looks OK, also when you disable/enable the ZWave hardware in Domoticz?
That is at least a step forward.

The switch you are trying to control is from the "Information" section ? Domoticz controls only 'user' types
What values are under 'Current' values ?
There should be a switch as well ?
What values are in the devices tab from this node ? Maybe there is more then one switch ?

**Comment by ClavosPL** [comment]
No after node refresh nothing works (still the same problem)
- Unknown device works,but after refresh node information not working
- Current values are "on" "off" in Zwave cotrol panel  (the same in unknown and GR105 )
- in domoticz panel, switch  works only when Hardware is **Unknown**
---
After refresh i exclude valve from system and include one mor time

- after exclude / include device, hardware GR105 i see only one new switch  in device tab from this hardware: (still not working swiching from domoticz system, only from Zwave control panel able to swich valve, but device state in domoticz is updated when i switch in ZWaveCP)
![New dewice after exclide incude](https://user-images.githubusercontent.com/16576679/62924240-f9d62c00-bdaf-11e9-8cf3-b67a4d79688d.PNG)

  |   | 270 | Z-Stick_Gen5 | 00022201 | 1 | Switch | Light/Switch | Switch | Off
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by gizmocuz** [comment]
Thanks for the feedback. There should also be a log line being added in Domoticz, could you open two browsers, one for the Log, and the other when you try to switch the value (switches page)

**Comment by ClavosPL** [comment]
Still not work , still the same problem.
V 11587
Fresh device inclusion , device G.R. GR105n
i must test the solution from here:

https://www.domoticz.com/forum/viewtopic.php?t=17605

the i post new comment

**Comment by waltervl** [comment]
No feedback, issue can be closed.
