### ISSUE TITLE
Link Error: class boost::asio::io_service has no member named ‘restart’

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#3327]
Hello,
I updated domoticz and I now have an error when compiling. The error is in PluginManager.cpp
I tried doing 'make clean' but it did not help.

I'm on Ubuntu 18.04.2 LTS on platform x86_64.
I also checked my current libboost library: dpkg -s libboost-dev | grep 'Version'
Version: 1.65.1.0ubuntu1

Domoticz recommends version 1.60.0 minimum so this shoudl be ok.

Any idea how to fix this?

`[ 80%] Building CXX object CMakeFiles/domoticz.dir/hardware/plugins/PluginManager.cpp.o
/home/Services/domotique/domoticz/hardware/plugins/PluginManager.cpp: In member function ‘void Plugins::CPluginSystem::Do_Work()’:
/home/Services/domotique/domoticz/hardware/plugins/PluginManager.cpp:324:7: error: ‘class boost::asio::io_service’ has no member named ‘restart’; did you mean ‘reset’?
   ios.restart();
       ^~~~~~~
       reset
CMakeFiles/domoticz.dir/build.make:2415: recipe for target 'CMakeFiles/domoticz.dir/hardware/plugins/PluginManager.cpp.o' failed
make[2]: *** [CMakeFiles/domoticz.dir/hardware/plugins/PluginManager.cpp.o] Error 1
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by petergebruers** [comment]
Try boost 1.7

This question was asked 3 days ago and the user reported success with 1.7

https://github.com/domoticz/domoticz/issues/3318

**Comment by dnpwwo** [comment]
I suspect the recommendation is out of date, 1.6 came out in 2015 and the Domoticz Windows build updated to 1.7 after the last stable was released.

Restart is in every version post 1.66 which itself is from 2017.

**Comment by petergebruers** [comment]
OK. Last time I checked the wiki build instructions it says 1.70 recommended. Did you find references to older versions?

**Comment by gizmocuz** [comment]
Always check the wiki when building fails. Domoticz could need an additional dependency, or specific library requirements

You can follow the instructions on this page:
https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by Olivier6767** [comment]
Thanks, I'm trying now with 1.70. 

Reference to 1.60 is in my CMakeLits.txt file:
```
## required min. libBoost version
SET(DOMO_MIN_LIBBOOST_VERSION 1.60.0)
```

**Comment by gizmocuz** [comment]
@Olivier6767 , thanks for reporting, updated this to 1.66
