### ISSUE TITLE
Netatmo Thermostat not return data

### ISSUE THREAD

**Issue by matmar29** [domoticz/domoticz#3331]
Hi,
From June 13 the two devices related to Netatmo Thermostat:
"Temperature detected and temperature setting" no longer work.
A Domoticz user wrote to me in the Domoticz forum, where I had previously opened a post about this problem.
He wrote to Netatmo who responded like this:

"Several months ago, we placed the "getthermostatdata" command as obsolete. It has remained active for several months to allow time for third-party application developers to adapt to the two new commands that replace it. The old order has finally been completely disabled recently.
I can not say for sure that this is the reason without seeing the code Domoticz, but the timing is perfectly. Anyway, as it is a third-party application, I invite you to contact Domoticz directly".

Is it possible to solve this problem in a future beta release?

Thank you
Alberto

**Comment by waltervl** [comment]
Is this still an issue?
