### ISSUE TITLE
Feature request: Add last seen notification to virtual switches

### ISSUE THREAD

**Issue by raqua** [domoticz/domoticz#3333]
I am on version 4.10717. 
I would like to be able to get notified when change on virtual switch did not happen for a certain time. Basically the same what I can now do on utility objects - if the virtual switch was not seen (changed or set in this context) for a certain amount of time, I want to be notified. 
Thanks for considering this.

**Comment by rwaaren** [comment]
This was discussed on the forum and a (script) solution was shared.  https://www.domoticz.com/forum/viewtopic.php?f=59&t=18566&p=217316

**Comment by raqua** [comment]
Thank you for the forum link, I will look at it. However, my request still stands. I am programmer and can code a lot of stuff (but I really don't feel like learning new language just to program Domoticz) However with this mindset, I can also code my own Domoticz then ... I use Domoticz in order to not to have code it and hence it would be nice to have this option. If for no other reason then for consistency... It is available somewhere and not on the other place, that makes no sense from user point of view.

**Comment by gizmocuz** [comment]
@raqua , i think you are using the wrong product.
Sure you can help with development/extending Domoticz, it's a open source project
If you expect other developers to do this for you ( "in order to not to have code it" )

In your github account i do not see any coding activity for the last 10 years, or i have overlooked it

More over, this could work for zwave or similar switches, this won't work for 433Mhz switches (switched that does not send status updates)

As explained by rwaaren, this can easily be done by using (for example) dzVents

**Comment by raqua** [comment]
@gizmocuz, I have politely suggested a new feature. And I explicitly wrote "Thanks for considering this". I was not forcing anything and I did not acted entitled for the solution in any way. My second post was merely a reaction to rwaaren's suggestion and explanation why I believe it would still be good to have that option even though there is a way to do it by code. 

I actually tried that suggested solution and it did not work (I don't remember it anymore, but I think there were some dzVents dependencies missing or different folder structure, maybe problem with my distro package).

Then I decided to try to code it in Python which I know a bit. Even the official Python example on Domoticz wiki does not work and there is some bug report about it here (quite old if I remember correctly). Maybe with your excellent contributor skills you could have a look at that... Let me know if you want me to provide you with details for that, I dig it up. ;)

I find your response unnecessarily aggressive and comes off as if the only users Domoticz is interested in are seasoned coders. And one should not dare to suggest new feature unless he can provide excellent Github credentials. I hope that was only some "lost in translation" moment among us because I believe that Domoticz has quite a potential also for non-coders.

"More over, this could work for zwave or similar switches, this won't work for 433Mhz switches" -> Fair point. I still think it would make more sense to have it for those that provide it that not have it at all. For sure there are 433Mhz devices that fall under "Utility" tab (signal?) and it is available there. But that is again just my opinion and polite suggestion, you are free to ignore it. I will not come to kill your hamster if you do so.

**Comment by gizmocuz** [comment]
@raqua , yes sorry i do not know the whole complete history, i only see these two posts from your here.
But developers are always welcome, you are free to correct the wiki as well !

THIS github issue page is for developers who want to contribute or discuss coding issues, not for feature requests. If you find me aggressive ... it must have something to do how you reacted to rwaaren and now to me as well... Great conversation !

Back to this topic. The main reason why this won't work is that even ZWave does not send any unnecessary status updates, so the 'last seen' is not updated,
MySensors can for example, but it is hardware specific.

We do have a hardware timeout .... 

What hardware do you use that us updating the switch last seen ?

I think for switches this is not a good idea to implement

**Comment by raqua** [comment]
@gizmocuz, 
no problem, as I expected, it was only misunderstanding, all good ... 

I am sorry, but I did not know this is only for developers. I wonder where do users report requests and bugs then ? Usually this is the place to do so in most projects.


Most devices I use are through Zigbee2Mqtt gateway and they all send last seen. Even if there is no state change, they occasionally send some keepalive message. Most of them are Xiaomi products and I also have some Ikea Tradfri wall socket + remote switch. One switch I have is Xiaomi Motion sensor. I worked around the missing last update for switch by using "signal" for the same device where I can set this up. 

But I wanted to have some ON/OFF switch that I would update myself from my own code and wanted to be notified if I stop updating it, meaning my code failed. In that case I can not work around using signal. 

I hope you understand it as I am not sure I made it perfectly clear .. :)

**Comment by gizmocuz** [comment]
@raqua , when you created the issue, you could read the posting rules.
We do have a large forum where people can communicate

I ordered some zigbee hardware and should receive the usb device next week. The week after I can test with this.
Then I hope i can see what you mean... I hope the devices are not sending the same status all the time.
Not sure how the keepalive works in MQTT, as far as i know I (or others) have not made a mechanism for this yet.
If the device or (zigbee2mqtt) is sending the last status all the time, then i guess the log for that switch is quite huge...
