### ISSUE TITLE
Web Interface not responding

### ISSUE THREAD

**Issue by SPLeon** [domoticz/domoticz#3335]
Hi there,

Since a couple of months the Domoticz web interface is not responding. After a reboot the web interface starts working again. Data is still being process when interface is not working, but I have to reboot the Pi every 4 -5 days.

Is this a known issue? How can I troubleshoot this?

Many thanks

**Comment by rwaaren** [comment]
Please don't crosspost.. The right place for these type of questions is indeed the forum where you posted the same question
