### ISSUE TITLE
Background image 'About Domoticz' page

### ISSUE THREAD

**Issue by BastiaanNaber** [domoticz/domoticz#3336]
I have an issue with the current 'About Domoticz' page, it shows a very dynamic moving picture in the background. The issues I have with this are:
1) I view domoticz through a VNC connection. This page is very bad for bandwidth over VNC.
2) The effect is far from professional to the eye. 

Please change the background to something static and more professional.

**Comment by rwaaren** [comment]
Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum

**Comment by BastiaanNaber** [comment]
I think this is a bug! The changing background image effects my usability of domoticz through a VNC server.

**Comment by ghost** [comment]
I do think it’s a bit 90s if I’m honest.
Not sure what the purpose is, as it doesn’t fit the rest of any of the other pages.

Just seems unnecessary.

**Comment by gizmocuz** [comment]
I created this just for fun... to have a nice page... even thought about adding music to it ;)

It's not a bug and there will always be people who do not like how things look.... i asked Cisco to change their web interface look in my switch....
