### ISSUE TITLE
IPv6 and updaterelease.sh

### ISSUE THREAD

**Issue by heind** [domoticz/domoticz#3340]
Hi,
Updating the release did not work for me from the Gui. From the command line I noticed the updaterelease script hanging at the wget command after resolving to an IPv6. I Suspected an IPv6 releated issue on your end so forced v4 by adding -4 to the wget command in updaterelease.sh and updated like a charm.
So either fix the v6 location of the update, or force ipv4, I'd say? 
Regards!

**Comment by gizmocuz** [comment]
Thanks for reporting !

Fixed in current beta (you might experience this issue one more time)
