### ISSUE TITLE
IntesisHome integration in Domoticz 

### ISSUE THREAD

**Issue by kitopopo** [domoticz/domoticz#3342]
Hi all,

First of all I would like to thank for this great forum and the support we have with Domoticz.
I have 2 units of IntesisHome (IS-IR-WIFI1) to be able to control the air conditioning through the application of IntessisHome. I have contacted several times with IntessisHome to know if they could integrate Intesishome in Domoticz. Your last email received from them says the following:

"The integration with the Domoticz platform was considered and, although it gave us a good impression as a service, it is unlikely that it will be integrated with Intesishome soon considering our Roadmap"

I think a lot of people would be interested in this integration. Could you consider integrating IntesisHome in domoticz?

Thanks in advance and receive a greeting greeting

**Comment by waltervl** [comment]
This issue can be closed in https://github.com/domoticz/domoticz/issues/4193 there is more info.

**Comment by kevin7benji7** [comment]
@gizmocuz @waltervl  Hello Sirs, it is Kevin, I am the person who you were talking about in 2020 about the possibility toe make the integration of air conditioenrs into Domoticz through IntesisHome solution but it was not possible. Now I am not working at Intesis anymore but I am working in Airzone. I do not know if you could find a solution to make such integration, if not, I wanted to retake this topic to inform you that we have a similar solution with a public API to make the integration you need, here you have our API: https://developers.airzonecloud.com/docs/local-api/#servers

Furthermore, in case you also work with Zigbee, we are about to realease the Airzone air conditioners gateways per each AC brand to integrate in Zigbee.

In case you need, my e-mail is [kvega@airzonecontrol.com](mailto:kvega@airzonecontrol.com)
Do not hesitate to send me your inquiries here or by e-mail or even whats/telegram

Thank you!

Kevin

**Comment by gizmocuz** [comment]
Hi Kevin,

The API looks quite easy to implement. Please try to do this via a Python plugin

**Comment by kevin7benji7** [comment]
Hello Gizmocuz,
Let me know what we can do to help you in this case to make the integration. Now we can do what you need, I have freedom and if you want I can send you a free device at no cost to you if it helps.
Let me know your comments, thanks,

**Comment by waltervl** [comment]
@kevin7benji7 You can use this python plugin as inspriration: https://github.com/luismalddonado/IntesishomewithDomoticz
