### ISSUE TITLE
Stable Release 4.10717 - Unable to compile - Found libBoost version 1.70.0, 106000 or newer required

### ISSUE THREAD

**Issue by gvdhoven** [domoticz/domoticz#3351]
```
-- ###########################
-- Compiling Revision #10659
-- ###########################
-- Using builtin Mosquitto library
-- Python3 includes found at: /usr/include/python3.5m
-- Building with I2C support
-- Building with SPI support
-- OPENSSL_LIBRARIES: /usr/lib/arm-linux-gnueabihf/libssl.a;/usr/lib/arm-linux-gnueabihf/libcrypto.a
-- Found Boost 1.70.0 at /usr/local/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS thread;system
-- Found boost_headers 1.70.0 at /usr/local/lib/cmake/boost_headers-1.70.0
-- Found boost_thread 1.70.0 at /usr/local/lib/cmake/boost_thread-1.70.0
--   libboost_thread.a
-- Adding boost_thread dependencies: headers
-- Found boost_system 1.70.0 at /usr/local/lib/cmake/boost_system-1.70.0
--   libboost_system.a
-- Adding boost_system dependencies: headers
-- Boost  found.
-- Found Boost components:
   thread;system
-- Linking against boost static libraries
CMake Error at CMakeLists.txt:589 (message):
  Found libBoost version 1.70.0, 106000 or newer required


-- Configuring incomplete, errors occurred!
See also "/opt/zwave/dev-domoticz/CMakeFiles/CMakeOutput.log".
See also "/opt/zwave/dev-domoticz/CMakeFiles/CMakeError.log".
```

Followed instructions according to the wiki; https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source
But it doesn't detect the right libBoost version

**Comment by gizmocuz** [comment]
Try to locate and remove old boost versions (with locate)
Our Travis build on Linux so this is not a Domoticz issue

**Comment by gvdhoven** [comment]
@gizmocuz thanx but it does say it finds the right one (1.70) which i just installed according to the wiki. So there is no 'old' one afaik.
**Update:**
Open `CMakeList.txt` from https://github.com/domoticz/domoticz/tree/4.10717
Change `SET(DOMO_MIN_LIBBOOST_VERSION 106000)` to `SET(DOMO_MIN_LIBBOOST_VERSION 1.66.0)`
CMake works again.

**Comment by gizmocuz** [comment]
You have an old cmake

**Comment by iamthemitch** [comment]
Is cmake 3.15.5 too old to build the stable branch ?

**Comment by logicor-cn** [comment]
I have the same problem with cmake-3.17 and boost-1.72.

Looking at the `FindBoost.cmake` of cmake-3.17, I think what you are trying to compare `DOMO_MIN_LIBBOOST_VERSION` with is actually `Boost_VERSION_MACRO`, not `Boost_VERSION`.  Latter is only equivalent to formal when cmake policy `CMP0093` equals `NEW`.

Replacing `Boost_VERSION` with `Boost_VERSION_MACRO` in `CMakeLists.txt` actually fixed this problem.

If you rely on a specific version of `FindBoost.cmake` implementation of cmake, one common practice is to ship that file in your repository so there would be no confusion.

**Comment by gizmocuz** [comment]
@iamthemitch , yes just upgrade to 3.16 (3.16.5 or higher), see the build instructions:

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by gizmocuz** [comment]
@logicor-cn , yes this has probably been changed in 3.17 (as it was in a few versions ago)
I don't want it to depend on a FindBoost.cmake file... would be great if it just worked all the time

I am compiling on a clean issue to try to solve a external lua problem, installed CMake 3.17 (release), and boost according above install instructions and i have no issue at all

-- Found Boost: /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0") found components: thread system
-

could you try to delete your domoticz build folder, make sure you have the release version of CMake and try with the above instructions in the link ?

cmake version 3.17.0
