### ISSUE TITLE
Domoticz not installing on latest raspbian

### ISSUE THREAD

**Issue by dimitrijp** [domoticz/domoticz#3353]
I cant install domoticz on latest raspbian (buster).  here is the output of; curl -L https://install.domoticz.com | bash. Im using RPI3B+.

100 16257  100 16257    0     0   3111      0  0:00:05  0:00:05 --:--:--  3559
:::
::: Script called with non-root privileges. The Domoticz installs server packages and configures
::: system networking, it requires elevated rights. Please check the contents of the script for
::: any concerns with this requirement. Please be sure to download this script from a trusted source.
:::
::: Detecting the presence of the sudo utility for continuation of this install...
::: Utility sudo located.
:::
::: You are root.
::: Verifying free disk space...
:::
::: apt-get update has not been run today. Running now... done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with Domoticz installation...
:::    Checking for apt-utils... installed!
:::    Checking for whiptail... installed!
:::    Checking for git... installed!
:::    Checking for curl... installed!
:::    Checking for libcurl3...

after check for libcurl3 it stops without error. It looks like its libcurl3 issue, since raspbian is using libcurl4

**Comment by rwaaren** [comment]
Can you please try 
```
sudo curl -sSL install.domoticz.com > install.sh
sudo sed -i 's/curl3/curl4/g' install.sh
sudo chmod 755 install.sh
sudo ./install.sh
```
as workaround and report back ?

**Comment by michi1g** [comment]
working for me
EDIT: correction: Install worked, interface is not working

**Comment by rwaaren** [comment]
Can you please elaborate ? It is not completely clear to me what is going wrong and at which step.

**Comment by michi1g** [comment]
Install runs without any errors, but i can't connect to the web interface

> ::: Restarting services...
:::
::: Enabling domoticz.sh service to start on reboot... done.
:::
::: Starting domoticz.sh service... done.
::: done.
:::
::: Installation Complete! Configure your browser to use the Domoticz using:
:::     192.168.178.79:8080
:::     192.168.178.79:443

Status gives:

> sudo service domoticz.sh status
● domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh; generated)
   Active: active (exited) since Tue 2019-06-25 11:42:08 CEST; 3s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 974 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)
Jun 25 11:42:07 raspberrypi systemd[1]: Starting LSB: Home Automation System...
Jun 25 11:42:08 raspberrypi domoticz.sh[974]: /home/pi/domoticz/domoticz: error while loading shared libraries: libusb-0.1.so.4: cannot open shared object
Jun 25 11:42:08 raspberrypi systemd[1]: Started LSB: Home Automation System.

> wget 127.0.0.1:8080
--2019-06-25 11:43:21--  http://127.0.0.1:8080/
Verbindungsaufbau zu 127.0.0.1:8080 … fehlgeschlagen: Verbindungsaufbau abgelehnt.

Translation : failed:Connection refused

**Comment by dimitrijp** [comment]
> Can you please try
> 
> ```
> sudo curl -sSL install.domoticz.com > install.sh
> sudo sed -i 's/curl3/curl4/g' install.sh
> sudo chmod 755 install.sh
> sudo ./install.sh
> ```
> 
> as workaround and report back ?

working thanks a lot :)

**Comment by dimitrijp** [comment]
> Install runs without any errors, but i can't connect to the web interface
> 
> > ::: Restarting services...
> > :::
> > ::: Enabling domoticz.sh service to start on reboot... done.
> > :::
> > ::: Starting domoticz.sh service... done.
> > ::: done.
> > :::
> > ::: Installation Complete! Configure your browser to use the Domoticz using:
> > :::     192.168.178.79:8080
> > :::     192.168.178.79:443
> 
> Status gives:
> 
> > sudo service domoticz.sh status
> > ● domoticz.service - LSB: Home Automation System
> > Loaded: loaded (/etc/init.d/domoticz.sh; generated)
> > Active: active (exited) since Tue 2019-06-25 11:42:08 CEST; 3s ago
> > Docs: man:systemd-sysv-generator(8)
> > Process: 974 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)
> > Jun 25 11:42:07 raspberrypi systemd[1]: Starting LSB: Home Automation System...
> > Jun 25 11:42:08 raspberrypi domoticz.sh[974]: /home/pi/domoticz/domoticz: error while loading shared libraries: libusb-0.1.so.4: cannot open shared object
> > Jun 25 11:42:08 raspberrypi systemd[1]: Started LSB: Home Automation System.
> 
> > wget 127.0.0.1:8080
> > --2019-06-25 11:43:21--  http://127.0.0.1:8080/
> > Verbindungsaufbau zu 127.0.0.1:8080 … fehlgeschlagen: Verbindungsaufbau abgelehnt.
> 
> Translation : failed:Connection refused

you are missing libusb-0.1 please try;

sudo apt-get install libusb-0.1

and reboot domoticz

**Comment by michi1g** [comment]
nice! That did the trick. Maybe check it in the script too?

**Comment by dimitrijp** [comment]
this solves it;

sudo curl -sSL install.domoticz.com > install.sh
sudo sed -i 's/curl3/curl4/g' install.sh
sudo chmod 755 install.sh
sudo ./install.sh

so closing the issue.

**Comment by rwaaren** [comment]
Re opened as this is only a workaround. Need to be solved by amending the install script

**Comment by rwaaren** [comment]
@gizmocuz fixed the install script

**Comment by Jero1ste** [comment]
it's working, thx

**Comment by freejoins** [comment]
I found some error in install.sh script. In line 97-98 for "grep" need use additional flag "-h", for not insert to variable full filename. Example:
```
97        DEBIAN_ID=$(grep -oP '(?<=^ID=).+' /etc/*-release | tr -d '"')
98        DEBIAN_VERSION=$(grep -oP '(?<=^VERSION_ID=).+' /etc/*-release | tr -d '"')
```
and this variable have value:
```
# grep -oP '(?<=^ID=).+' /etc/*-release | tr -d '"'
/etc/os-release:debian
# grep -oP '(?<=^VERSION_ID=).+' /etc/*-release | tr -d '"'
/etc/os-release:9

```
But if add flags "-h", variable have normal value:
```
# grep -ohP '(?<=^ID=).+' /etc/*-release | tr -d '"'
debian
# grep -ohP '(?<=^VERSION_ID=).+' /etc/*-release | tr -d '"'
9

```
```
# man grep | cat | grep -A3 "\-h,"
       -h, --no-filename
              Suppress the prefixing of file names on output.  This is the default when there is only one file (or only standard
              input) to search.

```

**Comment by rwaaren** [comment]
> I found some error in install.sh script. In line 97-98 for "grep" need use additional flag "-h", for not insert to variable full filename. Example:

This issue is about the latest ___raspbian___ . The grep commands are working on the latest raspbian

```
DEBIAN_ID=$(grep -oP '(?<=^ID=).+' /etc/*-release | tr -d '"')
DEBIAN_VERSION=$(grep -oP '(?<=^VERSION_ID=).+' /etc/*-release | tr -d '"')
echo $DEBIAN_ID # --> raspbian
echo $DEBIAN_VERSION # --> 10
```

If your issue is about another OS please open another issue and clearly state your hardware and OS.

btw. Current domoticz for Linux requires Buster (Debian version 10)

**Comment by gizmocuz** [comment]
@freejoins, I just installed a clean raspbian (version from 20 august 2020) and issued:

**curl -sSL install.domoticz.com | sudo bash**

There is absolutely no issue here.

Please use our forum first next time ...
