### ISSUE TITLE
Xiaomi round temperature sensors update

### ISSUE THREAD

**Issue by Marbaf** [domoticz/domoticz#3355]
Dear devs,
Running last domoticz beta Version: 4.10915 on raspberry 3.
Xiaomi Gateway and temperature sensors paired on older versions.

This issue concerns all my 4 round temperature sensors (old ones).
Each one is detected as 4 devices from Domoticz devices table (same ID):
 1. type: Temp | LaCrosse TX3
 2. type: Humidity | LaCrosse TX3
 3. type: Temp + Humidity | LaCrosse TX3
 4. type: Temp + Humidity | WTGR800

The most relevant one is the fourth (WTGR800) because it embeds all possible data: temp, humidity and battery level.
Unfortunatelly, its temp+humidity values are often unsynchronized with LaCrosse TX3 and older.

I suppose it is due to the way Xiaomi notifications are handled.
![image](https://user-images.githubusercontent.com/6973936/60257323-88135300-98d3-11e9-9eb6-fe2a2a101df2.png)
Thanks

**Comment by waltervl** [comment]
Still an issue on current stable 2022.1?

**Comment by Marbaf** [comment]
Don't know, domoticz does not restart after upgrade.
Just close, thanks.

**Comment by waltervl** [comment]
Well,  go to the forum if you need support for your upgrade.
