### ISSUE TITLE
OZWCP boolean used as string 

### ISSUE THREAD

**Issue by jotakar** [domoticz/domoticz#3356]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version.
* Always state your version when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by jotakar** [comment]
In OZWCP I cannot set ON/OFF for some devices in a ON/OFF field (switch) although the command is sent to the device.
Debugginn cp.js I see an strange behaviour
line 301, funcion PollReply()
```
val = nodes[i].values[j].value;
		if (val == 'False')
		  val = 'off';
		else if (val == 'True')
		  val = 'on';
	      }
	      break;
	    }
```
This code is Ok but when **val** must be **True** it takes a value of "True↵   " so when it should show On it doesn't so and a Off value appears in the Switch field. Same with False, because "**True**" is not equal to "T**rue↵** ". Others values are ended also with ↵
So looking for where `nodes `is filled with values I think that in line 248 we could change from actual
`nodes[id].values[k].value = values[j].firstChild.nodeValue;`
to
`nodes[id].values[k].value = values[j].firstChild.nodeValue;.trim()`
So values are shown right: On/Off instead of True/False and fields keeps the right values of switches 

Is that right?

**Comment by petergebruers** [comment]
Yes, well spotted. I am not a Domoticz developer but an OpenZWave developer and I can say two things.

- I fixed the True/False bug upstream in a slightly different way upstream, and upstream is

https://github.com/OpenZWave/open-zwave-control-panel

There are probably a few more changes between upstream and the version in Domoticz, I haven't checked.

- The ozwcp repo has this text at the top "UNMAINTAINED - We are looking for someone to maintain ozwcp!". I would say if you would like to keep that project alive than please start from there and see if it needs more of your fixes. We'll gladly accept PRs

BTW Justin Hammond is working on a GUI replacement of ozwcp.

That said, I still use ozwcp for quick tests...

**Comment by jotakar** [comment]
Oh, thanks.
After reading your answer  I realized that **cp.js** in the latest Domoticz version. is outdated. So there is no any error really, but perhaps there is a problem because of different versions. 
I tried latest version of cp.js with Domoticz and I get a blank control panel page.

**Comment by gizmocuz** [comment]
Fixed
