### ISSUE TITLE
Weekly programming

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#3361]
Hello, is it possible to record this in Domoticz?

http://www.domoticz.com/forum/viewtopic.php?f=31&t=20868&start=100&sid=bc3aa7601e87a1c0a8a7eeed35c2db71

**Comment by gizmocuz** [comment]
Sure, please go ahead. I would not add the odd/even week numbers as this is not a common usage
For this we have 'Timer Plans' in domoticz

**Comment by Patricen1** [comment]
@salopette, case seems to be closed due to an unanswered message.
Is it ppossible for you doing something regarding this excellent feature from Syrhus?

**Comment by salopette** [comment]
I have no idea myself. Have in the forum made the author aware, but there is no reaction.

**Comment by DenisMartin0** [comment]
@gizmocuz Just to be crystal clear: Have you noticed that default mode is actually a simple one-week planner as you suggested? The trick with even & odd weeks is just an option (Useful for some child joint custody/parenting schedule). [Screenshot](https://raw.githubusercontent.com/syrhus/domoticz-weekly-planning/master/images/setpoint_tabs.png) + [Github](https://github.com/syrhus/domoticz-weekly-planning)

Having said that:
  - Do you still want this feature (even/odd week switch) removed before accepting any pull-request?
  - Is rewriting it in AngularJS mandatory ? It's currently in plain JS.
  - Is there other topics that you'd like fixed before considering a merge?

Note 1: Duplicated PR #2979
Note 2: This contribution is experimenting an pretty interesting pull from the community both on [En](https://www.domoticz.com/forum/viewtopic.php?f=31&t=20868&start=120) & [Fr](https://easydomoticz.com/forum/viewtopic.php?f=17&t=5731&start=100) forums. I'd be happy to help finding a way through it...

**Comment by gizmocuz** [comment]
@DenisMartin0 , If you want, please leave the even/odd in as maybe some users needs this all the time, and for them to switch all the time the timer plans is not so nice.
About AngularJS, yes, that would be great if you could do this:
a) good for you skills and domoticz gui code, but
b) we might could use this in other timers as well (lights for example) in the feature?

**Comment by DenisMartin0** [comment]
Thx @gizmocuz for the even/odd decision.
I know from @syrhus that it is already working with Setpoints, Switch & Selector switch.

'Only' remaing issue is this question of Angular vs. plain JS... I've no pre-existing knowledge in Angular (neither in JS), I'm looking for support on forums, which is not so easy to find.

**Comment by waltervl** [comment]
A new PR is being prepared to be implemented https://github.com/domoticz/domoticz/pull/5052

**Comment by luzpaz** [comment]
Is this ticket still relevant ?

**Comment by kiddigital** [comment]
Nope.. close thanks to PR #5542
