### ISSUE TITLE
Temperature being mis-reported.

### ISSUE THREAD

**Issue by jdb1941** [domoticz/domoticz#3362]
After updating to V4.10921, it is mis-reporting my temperature sensors,  Below are images comparing between the temperature tab and what the z-wave controller is seeing.

Thanks.

![image](https://user-images.githubusercontent.com/52335196/60374537-fab72800-99d2-11e9-982b-6371ec36aad6.png)

![image](https://user-images.githubusercontent.com/52335196/60374582-20dcc800-99d3-11e9-8151-1d4481a4cd82.png)

**Comment by bramvreugd** [comment]
Probably the value in devices (79.8)is in celsius and the other (173.5) in Fahrenheit

**Comment by gizmocuz** [comment]
Could you check your cache/configuration file if the UNIT is set to "F" ? If it is not, that could be the issue

**Comment by gizmocuz** [comment]
No feedback, closing issue, problem is probably solved
