### ISSUE TITLE
OZW 1.6 RFID Keypad Zipato

### ISSUE THREAD

**Issue by dobber81** [domoticz/domoticz#3365]
Trying to enroll code for my home alarm rfid keypad from zipato. Works on latest stable, but not on dev.
Identified as Schlage Link (Wintop) Mini Keypad RFID.

2019-06-29 23:51:44.436 OpenZWave: Value_Added: Node: 85 (0x55), CommandClass: USER CODE, Label: Enrollment Code, Instance: 1, Index: 0
2019-06-29 23:51:44.436 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 85 (0x55), CommandClass: USER CODE, Label: Enrollment Code, Instance: 1, Index: 0

Domoticz 4.10935

**Comment by gizmocuz** [comment]
Is there anything in the log before this related to user codes ?

**Comment by dobber81** [comment]
Just one line when I initiate the new code enrollment:
2019-07-03 17:10:44.191 Status: OpenZWave: User Code Enrollment mode initiated...

2019-07-03 17:10:51.611 OpenZWave: Value_Added: Node: 85 (0x55), CommandClass: USER CODE, Label: Enrollment Code, Instance: 1, Index: 0
2019-07-03 17:10:51.611 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 85 (0x55), CommandClass: USER CODE, Label: Enrollment Code, Instance: 1, Index: 0

**Comment by gizmocuz** [comment]
@dobber81 , i am working on this, but currently there is a 'auto clear' build into OZW 1.6, which also causes the How/Away status to be reset.
The current beta version should handle the tag reader a bit better... but it is not finished
If you are depending on the tag reader, it is best to stay on the stable for now

**Comment by dobber81** [comment]
Thank you for your quick fix, it works well enough for the time being.
I can enroll codes and tags and I solved the status reset issue with a user variable that changes after a few seconds and has to be active for home switch to be triggered. Enough time for the reset to occur. Only bad thing is that I can not turn off the alarm in the first 10 seconds after activating it.

Most of the time we use our phones to activate/disable the alarm. But once in a while the keypad is used. Especially if the ethernet/wifi is down.

With the status home/away reset issue still present, do you want this ticket to remain open?

**Comment by gizmocuz** [comment]
Great to hear... yes please leave the ticket open... hope to close this soon

**Comment by dobber81** [comment]
Small issue with the codes:
In the ozwcache file some characters are "messy". Looks strange when I look at them under "User Code Management" also. Is this expected? It breaks a plugin that reads the cache file, due to the broken characters. Only tags act this way. If I add a digit code, it's fine in the ozwcache file and gui.

            <Value type="string" genre="user" instance="1" index="2" label="Code 2:" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="�MyT*">
                <Help>UserCode 2</Help>
            </Value>
            <Value type="string" genre="user" instance="1" index="3" label="Code 3:" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="�(2&#x0D;&#x01; &#x02;�$
                <Help>UserCode 3</Help>
            </Value>
            <Value type="string" genre="user" instance="1" index="4" label="Code 4:" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="�&gt;qT*">

<img width="1280" alt="Skärmavbild 2019-07-08 kl  18 38 54" src="https://user-images.githubusercontent.com/7099281/60827083-af113500-a1af-11e9-8ffc-bd8509a85216.png">

**Comment by gizmocuz** [comment]
@dobber81 , I also noticed while i was debugging that sometimes the codes that where received where not a string...
For example, during the enrollment, the value has is of **OpenZWave::ValueID::ValueType_String**
But sometimes i receive a string that has a size of 4, with zero's (0x00), so in the code i now check if that is the case

Steps performed during enrollment:

- received a tag code
- search in the 255 user codes for a empty placeholder, string=empty, or as above, the first character is a 0x00 (i do not think this is OK)
- set the value of the placeholder with the code received

`m_pManager->SetValue(vNodeValue, strValue);`

Where vNodeValue = the placeholder, and strValue is the code received (string)

@Fishwaldo, could it be the codes are not written as a string in the cache file ?
I thought to remember that in the 1.4 implementation the codes started with 0x ? (But i'm not sure, it has been a while)

**Comment by Fishwaldo** [comment]
The spec mandates that the “codes” are ascii, but some devices don’t obey that, and output it as a raw binary array. In 1.4 we used the RAW type for user code, in 1.6 we switched to String (to be in line with the spec for the majority of devices). 

If you have a device that does the Raw binary array (as some tag readers do) then you need to enable the “ExposeRawUserCodes” in the config file https://github.com/OpenZWave/open-zwave/wiki/CommandClass-Compatibility-Flags#usercode-commandclass  (and send me a PR please)

**Comment by gizmocuz** [comment]
@Fishwaldo , Thanks for pointing to this flag. i created a PR for this deivce:
https://github.com/OpenZWave/open-zwave/pull/1870

I have a question about erasing the usercode in 1.6... 

Currently i perform this action by doing:

```
					std::string sValue;
					sValue.assign(4,0);
					m_pManager->SetValue(vNodeValue, sValue);
```

I think when i send a empty string it is not accepted... (this also seems so looking at the code)

Is it possible to detect when an empty string is being assigned, that the library will send:

Version 1: (USER_CODE_SET)
StringUserCodes -> 0x00000000
RawUserCodes -> 4x 0x00

Version 2: (EXTENDED_USER_CODE_SET (0x0B))

I am not sure how to read the User_Code specification, but if i look at table 30 ( User Code::Set a User Code) and 31 (User Code::Set a User Code (v2)),
it seems that V1 is binary, with byte values in the range of 0x30-0x39 , minimum 4 bytes , max = 10 bytes
and V2 is a ASCII string, with the same lengths (4..10 bytes)

Could it be that the normal 'BeNext' and 'Schlage Link' are V1 nodes,
and the 'BeNext Tag Reader 500' is a V2 ? And in this case the only type that is using ASCII ?

Maybe in either case it could be a idea to convert either ASCII or binary chars to a string 0x31323334 ?

**Comment by Fishwaldo** [comment]
There is a ValueID for clearing UserCodes. You pass it the position you want to clear. 

From memory we are doing 4 x ascii 0’s by default but if you come across a device that does decimal 0 (or something else) let me know and I’ll update it with a config option and necessary code.

**Comment by gizmocuz** [comment]
Yes that's correct, you send 4 0x00 values... i guess it's then the same as what i perform above ;)
But there seems to be a difference between version 1 and 2, where version 2 needs to be set with command 0x0B, but that's maybe when someone has such a node

Is it a idea to go back to previous style for values, always translate the byte values (ASCII char = byte) to a HEX value, like [30,31,32,33,34] to "0x3031323334"
And when setting the value going back from HEX to bytes values ?
This way there is probably also no need for ExposeRawUserCodes ?

Is seems the specification is also talking about bytes, but in version 1 only a subset is used from 0x30..0x39 and in V2 any ascii value (!@#$&* etc) which can be translated to "0x21222324..."

**Comment by gizmocuz** [comment]
@dobber81 , the configuration file has been updated.
If you exclude/include again, do you still see strange character appearing or is all working correctly now ?

**Comment by dobber81** [comment]
I stil see the characters. I excluded the rfid reader, restarted, included secure and added a user code and then a tag.

Domoticz 4.11020

                <Instance index="1" />
                <Value type="string" genre="user" instance="1" index="0" label="Enrollment Code" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="�MyT*">
                    <Help>Enrollment Code</Help>

![image](https://user-images.githubusercontent.com/7099281/61476528-88ac8000-a98d-11e9-9eb4-ca394c7eebe5.png)

**Comment by gizmocuz** [comment]
@dobber81 , are you using domoticz 11010+ ?
If yes, could you have a look in the configuration file for this hardware if there is a line 

`<ExposeRawUserCodes>true</ExposeRawUserCodes>`

**Comment by dobber81** [comment]
Using 11020

           <CommandClass id="99" name="COMMAND_CLASS_USER_CODE">
                <Compatibility>
                    <ExposeRawUserCodes>true</ExposeRawUserCodes>
                </Compatibility>
                <State>
                    <CCVersion>1</CCVersion>
                    <Count>255</Count>
                    <InNif>true</InNif>
                    <StaticRequests>4</StaticRequests>
                </State>
                <Instance index="1" />
                <Value type="string" genre="user" instance="1" index="0" label="Enrollment Code" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="�MyT*">
                    <Help>Enrollment Code</Help>
                </Value>

**Comment by gizmocuz** [comment]
I hope you are able to debug the code.
"ExposeRawUserCodes" should cause internally to have the USER_CODE values as RAW type.
A GetValueAsString() should then convert the raw data to a hex string (just had a look in the code)
(0x12 0x34 0x56 0x78)

I don't think the codes are used in domoticz currently, so your node should still function.
But when doing scripting it could be nice to know which code was used

**Comment by dobber81** [comment]
I found something interesting.

               <Value type="raw" genre="user" instance="1" index="258" label="Raw UserCode" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0x8f 0x4d 0x79 0x54 0x2a 0x00 0x01 0x04 0x00 0x00" length="10">
                    <Help>UserCode 102</Help>
                </Value>

But as Code 102. Maybe 150 lines down.

The code that is visible in domoticz gui is still Code 2


                <Value type="string" genre="user" instance="1" index="2" label="Code 2:" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="�MyT*">
                    <Help>UserCode 2</Help>



So the tag is visible in cache as code 2 and 102, and in gui as only code 2, which has the bad characters. The plugin I'm using still halts on Code 2 in the cache due to the bad characters.

**Comment by dobber81** [comment]
If I remove the tag from domoticz both code 2 and 102 goes away. Readd and both appear again in cache.

**Comment by gizmocuz** [comment]
That is probably because the user_codes are in the range of 1 till 253 ... (index value)
258 is probably the last received code ? (RawValue)
As you can see in your cache file, the code is also not readable ("�MyT*")
I asked Fishwaldo from OpenZWave to always convert the code to a string above, but there was no reaction.
I think you have to debug/change the code yourself....

**Comment by dobber81** [comment]
That's too bad. I created a simple bash/sed workaround for myself that removes all lines having to do with the keypad from the cache file before it is used by the plugin I was having problems with. I guess that is good enough until I can replace the keypad in the future. Thanks for the effort!

**Comment by gizmocuz** [comment]
@dobber81 , got my hands on a previous benext model that has raw codes
Will try to get it working this weekend, but can't promise...

**Comment by gizmocuz** [comment]
@dobber81 , could you try beta 11022, this should work much better.
Still I am experiencing issues removing the tags... i will have to continue working on this one

**Comment by dobber81** [comment]
I tried 11022. Excluded and included the keypad.
I can now see tags like this "0x8F 0x4D 0x79 0x54 0x2A 0x00 0x01 0x04 0x00 0x00" in the gui. Much cleaner.
However I still get the messed up chars in the cache.

                <Value type="string" genre="user" instance="1" index="0" label="Enrollment Code" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="�MyT*">
                    <Help>Enrollment Code</Help>
                </Value>
                <Value type="string" genre="user" instance="1" index="1" label="Code 1:" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="11111">
                    <Help>UserCode 1</Help>
                </Value>
                <Value type="string" genre="user" instance="1" index="2" label="Code 2:" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="�MyT*">
                    <Help>UserCode 2</Help>
                </Value>
                <Value type="string" genre="user" instance="1" index="3" label="Code 3:" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="�(2&#x0D;&#x01; &#x02;�">
                    <Help>UserCode 3</Help>
                </Value>

And just as you previously said, Code 102 shows the last input code. Like the top "Enrollment Code", but with good characters.

**Comment by gizmocuz** [comment]
@dobber81 , thanks for testing. Also the home/away should work better now (no clean after a home or away)
The cache file issue is something for OZW to look at, but does not seem to be an issue

Could your plugin make use of the JSON call that is called to display the enrolled codes ?

http://127.0.0.1:8080/json.htm?type=command&param=zwavegetusercodes&idx=6

when idx is your zwave hardware idx

**Comment by dobber81** [comment]
No clean after home/away confirmed working again!

Actually, the plugin I'm using only pulls the battery status from the cache file. It has no need of the keypad code stuff at all. It's just that the plugin breaks when reading the bad characters in cache file.
Thats why I could solve the problem temporarily by just bash/sed away all the keypad stuff in the file.

Maybe there is a better way of pulling battery status from ozw than reading the cache file.

Edit: This is the plugin I'm using: https://github.com/999LV/BatteryLevel

**Comment by gizmocuz** [comment]
The battery status should be returned by calling

/json.htm?type=devices&used=true&filter=all&favorite=1

most times the battery status is send 'after' a value is received/changed, currently this causes the battery to be updated on the next change/update

**Comment by gizmocuz** [comment]
Always funny to see people using a script for things that are not build into software.
Sure it's great, but why not just ask for a option to report zwave battery levels as sensors ?
This is not hard to do, and everyone could enjoy it that way....

I also do not think that it is 'actual', and because of the recent changes related to saving the cache file, i do not think this is going to work in the feature

In beta 11023 i added a new json call:

json.htm?type=command&param=zwavegetbatterylevels&idx=3

where idx is the zwave hardware index

This returns a list of all nodes with the current battery levels.

Where level = 255, means no battery level received, or a node that does not support it (powered node)
Else the range is whats being receive (0-100)

Beta is building, could take an hour

**Comment by dobber81** [comment]
Thats a nice addition! I'll see what I can do with that info.
The reason I started using the battery plugin was to receive notifications when different units hit different %. Some sensors I have will give up at around 25%, while others keep going down to maybe 5% before dying.
I generally don't remove tags that often, but I'll be sure to give it a try when/if you find a fix for it.

**Comment by gizmocuz** [comment]
Closing this issue as this is working now (still could be better on OZW side)
