### ISSUE TITLE
Z-Wave powernodes from GreenWave stops reporting kwh usage after #897

### ISSUE THREAD

**Issue by JurikRistjouw** [domoticz/domoticz#3370]
Ever since 4.10897 my z-wave controlled greenwave powernodes stopped reporting their instance power usage in kWh. 

only thing in errorlog is:
2019-06-27 21:09:31.505 Error: OpenZWave: Unhandled value type: 4, OpenZWave.cpp:2108
2019-06-27 21:09:31.505 Error: OpenZWave: Unhandled value type: 1, OpenZWave.cpp:2108

Please advice how to resolve this issue.

Thanx

**Comment by JurikRistjouw** [comment]
I do see some timeout notifications on Status tho:

2019-07-02 18:02:19.763 Status: OpenZWave: Received timeout notification from HomeID: 4134421051, NodeID: 14 (0x0e)
2019-07-02 18:10:50.043 Status: OpenZWave: Received timeout notification from HomeID: 4134421051, NodeID: 3 (0x03)
2019-07-02 18:26:30.787 Status: OpenZWave: Received timeout notification from HomeID: 4134421051, NodeID: 15 (0x0f)
2019-07-02 18:37:11.076 Status: OpenZWave: Received timeout notification from HomeID: 4134421051, NodeID: 3 (0x03)
2019-07-02 18:53:33.135 Status: OpenZWave: Received timeout notification from HomeID: 4134421051, NodeID: 6 (0x06)
2019-07-02 18:59:16.170 Status: OpenZWave: Received timeout notification from HomeID: 4134421051, NodeID: 6 (0x06)

**Comment by gizmocuz** [comment]
Could you backup your whole domoticz folder (stop it first) and try the latest beta version (now 4.10935)

**Comment by MarcusKlerks** [comment]
I'm on 4.10935 and my greenwave devices don't report Usage and Energy anymore since introduction of OZW1.6 (see also https://www.domoticz.com/forum/viewtopic.php?f=6&t=28382). It looks like polling (wich is necesaary for Greenwave) doesn't work anymore. Reporting of Usage and Energy only occurs on restarting Domoticz.

**Comment by gizmocuz** [comment]
Okey, since there was a 'major' update in the meter class, could you (when all nodes have been queried, or you waited 5 minutes) try the following (best to have noting inside the greenwave!)

Have one domoticz gui open on the Log, a second browser on the hardware/zwave settings page

Select the greenwave node, and press the button 'Refresh Node Information', next press the small button on the greenwave (maybe it needs to be done 3 times, same as including it)
Do you see anything in the log (meter types received), , now try to disable polling, and enable it again, does this work ?

If not, without excluding it, try including it again (node dropdown, include node, and single/tripple press the small button)

**Comment by MarcusKlerks** [comment]
Did what you asked but with negative result :

**Test 1: Refresh Node Information and Press Include Button**
2019-07-03 10:39:13.961 (RaZberry) General/kWh (PN1 | Heater Office)
2019-07-03 10:39:13.997 (RaZberry) Usage (PN1 | Heater Office Usage)
2019-07-03 10:39:14.004 (RaZberry) General/kWh (PN1 | Heater Office)
That's it (one time only)

**Test 2: Disable/enable polling**
Nothing in the log

**Test 3: Include node**
2019-07-03 10:32:14.481 OpenZWave: Value_Added: Node: 15 (0x0f), CommandClass: INDICATOR, Label: Indicator, Instance: 1, Index: 0
2019-07-03 10:32:14.479 Status: OpenZWave: Node Removed. HomeID: 3507960504, NodeID: 15 (0x0f)
2019-07-03 10:32:16.618 OpenZWave: Value_Added: Node: 15 (0x0f), CommandClass: METER, Label: Electric - kWh, Instance: 1, Index: 0
2019-07-03 10:32:16.618 OpenZWave: Value_Added: Node: 15 (0x0f), CommandClass: METER, Label: Electric - W, Instance: 1, Index: 2
2019-07-03 10:32:16.618 OpenZWave: Value_Added: Node: 15 (0x0f), CommandClass: METER, Label: Exporting, Instance: 1, Index: 256
2019-07-03 10:32:17.528 (RaZberry) General/kWh (PN1 | Heater Office)
2019-07-03 10:32:17.571 (RaZberry) Usage (PN1 | Heater Office Usage)
2019-07-03 10:32:17.578 (RaZberry) General/kWh (PN1 | Heater Office)

One time only report

Additional: switching On and Off manually does give a (single) usage and energy report in the log for both On and Off

**Comment by JurikRistjouw** [comment]
> Could you backup your whole domoticz folder (stop it first) and try the latest beta version (now 4.10935)

I was already on #935 still have the issue. Is it also needed for me to try the include ceremony or is the log from @MarcusKlerks enough?

Thanx for helping out again!

**Comment by Olifant1990** [comment]
Go to the hardware -> z-wave device Setup button -> Node management -> Groups & network page.
Do you have an assosiation with your controller at group 1 of your GreenWave? The so called LifeLine?

**Comment by MarcusKlerks** [comment]
There is an association but it's on Wheel:
Group 1: Wheel; 
Group 2: Relay health; 
Group 3: Power level; 
Group 4: Overcurrent protection

So no lifeline.

**Comment by Olifant1990** [comment]
See https://forums.homeseer.com/forum/homeseer-products-services/system-software-controllers/hs3-hs3pro-software/hs3-hs3pro-discussion/91165-greenwave-powernode-polling-for-power-what-do-you-think
Look at the last post

And assosiation group 3? (Where HomeSeer must be your dongle in Domoticz ;))
And parameter 1?
What are your settings?

**Comment by MarcusKlerks** [comment]
As far as I can see I have the same assocations as mentioned in the article. 
Besides that: when looking in the z-wave control panel - current values I see that the values are updated so the Greenwave devices are reporting. It's just that the changes are not picked up in Domoticz.

**Comment by JurikRistjouw** [comment]
I think the problem is not with the z-wave part, but the communication between z-wave and domoticz from and after the denoted update... It did work after the big open z-wave update afaik.. it is just from version 4.10897 it does not update the values anymore...

**Comment by gizmocuz** [comment]
Maybe it is not only the meter nodes that are not polled anymore... hope to find some time to debug this issue with a greenwave.
I will also have to mention that using greenwave powernodes could mess up your whole zwave mesh network and you can run into big issues.
I know many people that had issues before, and when they took out this hardware , all was fine!
(they do not sell it anymore)
That having said... i myself also have 2 ... but i have to mention this
Hope to have a answer/solution soon!

**Comment by gizmocuz** [comment]
That having said... maybe i already see something in the code... OpenZWave.cpp, line 3633

`(ProductDescription.find("GreenWave PowerNode 6 port") != std::string::npos)`

It could be this name has changed, and it seem it is, now it is "GreenWave Reality Inc PowerNode 6 port"
I have rewritten this to use the manufactorer id and product id/type now

Could you test with the new beta (10948) ? I still want to verify this

**Comment by MarcusKlerks** [comment]
I see the same name but that doesn't seem to be the (only?) cause: It's still not working. I get reports on restart after the update but then it becomes silent wrt reporting. I've toggled 'Enable Polling' but that didn't help.
I have to mention that I never had any trouble with the Greenwave devices, only in the very beginning when I had only a few z-wave devices. Not it seems that the mesh network is strong enough.

**Comment by gizmocuz** [comment]
Found it... solved in version 10949

**Comment by MarcusKlerks** [comment]
Confirmed, thanks for the speedy solution.

**Comment by gizmocuz** [comment]
Thanks for the confirmation !

**Comment by JurikRistjouw** [comment]
very nice, will test as soon as i get domoticz back up and running..... But I am sure it will be fine.

Thanx!
