### ISSUE TITLE
4.10717 crashes on cold start on RPi 3B+

### ISSUE THREAD

**Issue by agambier** [domoticz/domoticz#3371]
Domoticz v4.10717 crashes on cold start.
Some times when I switch on my RPi, domoticz crashes but if I restart the service or reboot the RPi with the 'reboot' command it works fine.

Here is the crash log : [domoticz_crash.log].(https://github.com/domoticz/domoticz/files/3353736/domoticz_crash.log)

**Comment by gizmocuz** [comment]
Did you install Domoticz with the 'sudo' command ?

**Comment by agambier** [comment]
Yes I used the command described on domoticz.com

`curl -sSL install.domoticz.com | sudo bash`

and I updated it using the web interface.

**Comment by agambier** [comment]
It happens on two different RPi3B+...both installed with the same command line and updated using the webinterface

**Comment by agambier** [comment]
I disabled two python plugin I made...just in case...but it still crashes...

Here's a new crash log : https://github.com/domoticz/domoticz/files/3359491/domoticz_crash.log

**Comment by gizmocuz** [comment]
thanks for testing. Could you disable the complete event system + dzVents in the settings ?

**Comment by agambier** [comment]
Unfortunately it still crashes...

Here's the crash log with event system + dzVents disabled : https://github.com/domoticz/domoticz/files/3362768/domoticz_crash.log

Here's the crash log with only dzVents enabled : 
https://github.com/domoticz/domoticz/files/3362769/domoticz_crash_dzVents.log

Here's the crash log with only event system enabled : 
https://github.com/domoticz/domoticz/files/3362771/domoticz_crash_evt.log

Is there another log file than this crash dump...one with more details ?

**Comment by gizmocuz** [comment]
Is their any configuration you did that is different from all other installations on the raspberry ?
Did you try with a clean install ?
Could you make a full backup of the folder, then inside the original folder issue
./updatebeta

then reboot

**Comment by agambier** [comment]
> Is their any configuration you did that is different from all other installations on the raspberry ?

No only raspbian updates, domoticz and dependencies I need to make domoticz' plugins work.

The second raspberry is a clean install with almost nothing. The first one has much more installed apps.

I'll try next week to use updatebeta

**Comment by agambier** [comment]
I updated domoticz with the beta version : 4.10970 but it still crashes...

https://github.com/domoticz/domoticz/files/3371682/domoticz_crash.log

**Comment by gizmocuz** [comment]
@agambier , could you make a clean system (totally clean, no plugins nothing) and install Domoticz with the sudo command
Does it work ?
Then update to the beta .... does it still work ?
Next try to install your plugins, if it does not work, it's a plugin issue

**Comment by agambier** [comment]
I'll try but my plugins are disabled...

here's the list of the installed plugins :

![image](https://user-images.githubusercontent.com/2526892/60870183-a745a500-a230-11e9-95e7-7fa1ee1e118f.png)

I also have a dzVents script.

**Comment by gizmocuz** [comment]
@agambier , that is why i would like to check with a totally clean system and installation

**Comment by agambier** [comment]
I activated the log file using command switch **-log** and here is the output when it crashes...

It seems that a watchdog occured, the main thread seems blocked...
[domoticz.log](https://github.com/domoticz/domoticz/files/3402249/domoticz.log)

**Comment by gizmocuz** [comment]
@agambier , there are almost 50 news versions... could you try with beta 11019 ?

**Comment by gizmocuz** [comment]
Then again... i do not expect this was a clean install, with a clean (or no) database and no scripts correct?
It looks like a script causes this issue

**Comment by agambier** [comment]
No it's not a clean install but there's no plugins and no scripts.
But if you look at the last log (attached below) I think it might be a problem of RPi system clock synchronization.

First of all : **this log file has been created today**.

The first lines are timestamped at **'2019-07-17 16:14:22.643'** which is yesterday when I shutted down the RPi and the first error is timestamped at **'2019-07-18 17:02:04.151'** which is today, 24 hours and 47 minutes later, when I switch on the RPi today.

The error is : **'Error: mainworker seems to have ended or hung unexpectedly (last update 89247.000000 seconds ago)'** so it thinks the main thread was blocked for 89247 seconds which is **24 hours 47 minutes and 27 seconds**... The delay between these two lines below...

```
2019-07-17 16:14:25.550  Status: EventSystem: Queue thread started...
2019-07-18 17:02:04.053  Sunrise: 06:03:00 SunSet: 21:21:00
```

The thing is that the first lines have been written when domoticz started **today** the timestamps are wrong.

So I'm pretty sure it's not a matter of buggy plugins or scripts but much more a matter of RPi system clock synchronisation...

Domoticz starts before the RPi system clock has been synchronized using NTP and the system clock is updated which makes domoticz think the main thread was blocked for more than a day and then triggers the watchdog.

Which explains while it doesn't crash if I restart the service or reboot the RPi right after it has crashed.
So I'll try two scenario to confirm this theory...

1st scenario :
- Shutdown the RPi and write down the time
- wait for tomorrow
- switch on the RPi and check if the Error message has a delay corresponding to the one between today and tomorrow.

2nd scenario :
- Disable domoticz service
- Shutdown the RPi and write down the time
- wait for tomorrow
- switch on the RPi and wait for the boot process to finish
- start the domoticz service by hand and see if it crashes

[domoticz.log](https://github.com/domoticz/domoticz/files/3407163/domoticz.log)

**Comment by gizmocuz** [comment]
@agambier , i appreciate your research ! But there must be a 100.000 other users having this issue with the raspberry pi ?

**Comment by agambier** [comment]
I can confirm domoticz crashes because of the time set during its start process.
I performed two tests.

**Test 1**
Yesterday : 
- I delete the domoticz' log file
- I shut down the RPi at 17:33

Today:
- I switch on the RPi at 09:23

It crashed with the error : **'Error: mainworker seems to have ended or hung unexpectedly (last update 56981.000000 seconds ago)'** and 56981 is 15 hours 49 minutes and 41 seconds which is the perfect delay between yesterday and today when the time was synchronized during domoticz' start process.

Here's the crash log [domoticz_1.log](https://github.com/domoticz/domoticz/files/3410377/domoticz_1.log) and the important lines are :

```
2019-07-18 17:33:58.537  Status: EventSystem: Queue thread started...
# Time has been set by NTP service
2019-07-19 09:23:51.286  Sunrise: 06:04:00 SunSet: 21:20:00
...
# Domoticz triggers the watchdog
2019-07-19 09:23:51.541  Error: mainworker seems to have ended or hung unexpectedly (last update 56981.000000 seconds ago)

```

**Test 2**
To make sure crashes are because of the wathdog and the time set I tried to change the system time while domoticz is running (not starting).

Here're the steps to reproduce it:
- Disable domoticz service
- delete domoticz log file and domoticz crash dump file.
- reboot the RPi
- wait until the time is synchronized
- start domoticz using the command line
- wait for a few minutes
- disable the time synchronization with ` sudo timedatectl set-ntp false`
- change the systemtime to tomorrow with `sudo date +%Y%m%d -s "20190720`

And then domoticz crashes and create a crash dump file.
Here's the log file 
[domoticz_2.log](https://github.com/domoticz/domoticz/files/3410391/domoticz_2.log)
 and you can see it's the same errors as when it crashes during the start process. And the timestamps and the delay found by domoticz watchdog corresponds to the newtime.

```
2019-07-19 10:08:10.464  Status: PluginSystem: Entering work loop.
# change the system using the date command
2019-07-20 00:00:00.080  Error: mainworker seems to have ended or hung unexpectedly (last update 49870.000000 seconds ago)
```

So yes, I agree with you that a lot of users may have the same issue when using a RPi.
I noticed this issue when a power failure occurred during a storm.

I haven't check the source of domoticz to see how the watchdog feature is implemented but I guess it uses the system time which is vulnerable to time changes for example when internet connection is down during the boot process and comes back later so the time gets synchronized or during a power failure longer than the watchog limit or simply when domoticz starts before the time get synchronized.

I'll check the source code and see how it's implemented and check if using performance counters (CPU internal hardware clock ticks) could be used since it counts how many clocks ticks occurs between two functions calls so it's not vulnerable of time changes.

Connecting a RTC to the RPi can fix this but it's not easy for everybody to do it.

**Comment by agambier** [comment]
A workaround is to change the domoticz service script so it starts when the time synchronization is done.

I'll try this before investigating the source code.

**Comment by agambier** [comment]
I've check the source code. The watchdog is trigger by the function `heartbeat_check()` which use the function `time()` to get the [current calendar time](http://www.cplusplus.com/reference/ctime/time/) and compute the difference between the last time `heartbeat_check()` was called and if it's greather than 5 minutes it triggers the watchdog by sending the signal SUGUSR1 (on Linux).

So domoticz crashes is because of the system time synchronized after Domoticz has started so this should occurs on windows if the system time is changed of more than 5 minutes but I guess it almost never occurs during the start since PC have a RTC with a button cell battery.

here's the function :
```
static void heartbeat_check()
{
	time_t now;
	mytime(&now);

	double diff = difftime(now, m_mainworker.m_LastHeartbeat);
	if (diff > Heartbeat_Timeout)
	{
		_log.Log(LOG_ERROR, "mainworker seems to have ended or hung unexpectedly (last update %f seconds ago)", diff);
		if (!IsDebuggerPresent())
		{
#ifdef WIN32
			abort();
#else
			raise(SIGUSR1);
#endif
		}
	}

	diff = difftime(now, m_LastHeartbeat);
	if (diff > Heartbeat_Timeout)
	{
		_log.Log(LOG_ERROR, "main thread seems to have ended or hung unexpectedly (last update %f seconds ago)", diff);
		if (!IsDebuggerPresent())
		{
#ifdef WIN32
			abort();
#else
			raise(SIGUSR1);
#endif
		}
	}
}
```

And the watchdog main loop is...
```
void Do_Watchdog_Work()
{
	while(!g_stop_watchdog)
	{
		sleep_milliseconds(1000);
		heartbeat_check();
	}
}
```

Using the system time is not robust performance counters might be a better solution for both :
- Linux : [clock_gettime()](https://linux.die.net/man/2/clock_gettime) with clock CLOCK_MONOTONIC_RAW which is not affected by system time changes.
- Windows : [QueryPerformanceCounter()](https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancecounter)

**Comment by gizmocuz** [comment]
Okey, but you seem to be the first one with this issue.... I was not to happy that the one added the watchdog used abort/raise(SIGUSR1); maybe this should be changed as well.

But for windows we could use GetTickCount64, and clock_gettime for Linux. OS-X uses sysctl

But what type of internet connection do you have ? Wired or WiFi ?

I work with raspberries for quite some time, many users do... again your the first with this issue (or posted the issue)

You can always install a RTC in your RPI... 

I do not think there is a option in a startup script to wait until the date/time is set

If it takes a few seconds, you could add a startup delay ?

Or indeed modify the watchdog functions

**Comment by agambier** [comment]
I also have been working with raspberry and Linux for quite some times that doesn't mean we have seen all the possible issues. 

I think I'm not the only one who had a crash because of this. Maybe some people had this crash after a power failure longer than 5 minutes and though it was only because of the power failure and didn't try to investigate what happened and just rebooted the system. Not all of the domoticz users are software developers.

Plus, once the system is booted and domoticz running, system time is not supposed to change more than a few seconds because of a synchronization.

Just by reading how the watchdog is implemented we can see it's not robust and it's very easy to make it crashes just by changing the time using only two commands shell. I guess it wasn't tested.

According to me installing a RTC just to fix this is not jusitfied. RTC are intended when we need to have a very precise timer. Domoticz should not need a very precise timer NTP synchronization should be enough. It won't fix the watchdog functions it's just a workaround.

I think fixing the watchdog functions with as you said GetTickCount64() and clock_gettime() is a cleaner and more robust way to fix it. I'm ok to do it but it won't be before september I won't have spare time until then.

I agree that calling abort() and raising SIGUSR1 is not very clean but it will be a longer work to change it.

In a short delay changing the timing functions  would be the best cause it's no big deal.

**Comment by rwaaren** [comment]
Would it be an option to change to /etc/init.d/domoticz.sh script and add a dependency on $time ?
by changing the line
 `# Required-Start:    $network $remote_fs $syslog` 
to 
`# Required-Start:    $network $remote_fs $syslog $time`
?
The discussion on [Booting from LUN is crashing domoticz](https://www.domoticz.com/forum/viewtopic.php?f=6&t=28738l)] on the forum triggered me for this suggestion

**Comment by gizmocuz** [comment]
@rwaaren , yes sure ! @agambier , is it possible to test this ?

**Comment by agambier** [comment]
@rwaaren: I already tried this fix last friday and it didn't work but I performed only one reboot and I might have missed something. Debian wiki describes that it should works. (@gizmocuz: When I was talking about changing boot order in my previous post I was talking about this).

Next week I'll try this workaround one more time to validate it and maybe it can help people that have the same issue until this is really fixed. (@gizmocuz: Finally I'm not the only one but I didn't search on the forum).

This is a workaround that works if NTP server is available and system time get synchronized during boot process. If system time fails to get synchronized, domoticz will start and crash next time NTP server become available.

There's no doubt that watchdog is not implemented correctly. watchdogs can't be based on timers that can change like system time but always on hardware clocks.

I'll fix it but it won't be before September (except if someone have spare time and will to do it).

**Comment by gizmocuz** [comment]
I expect $time will do the trick here. I will add this to the default startup script for new users.

**Comment by gizmocuz** [comment]
@agambier , seems Eddy has success as well with the $time addon.
If you could try this with a couple of reboots you should be able to verify this

**Comment by agambier** [comment]
@gizmocuz: I will try this this week as I said.

As I said in my reply changing the startup script will work only if the NTP server is available.
After a power failure my RPi boots up faster than my internet box so the NTP server is reached after domoticz has started.

**Comment by agambier** [comment]
You already commited the [modification](https://github.com/domoticz/domoticz/commit/09a81f91959ed39e6aa9794d028044b93d4c570a) without testing.

It doesn't work on my RPi after changing the dependencies and updating init.d RC config.

The debian wiki explains that time sync [can occurs several minutes after NTP starts](https://wiki.debian.org/LSBInitScripts)

> $time | the system time has been set, for example by using a network-based time program such as ntp or rdate, or via the hardware Real Time Clock. Note that just depending on ntp will not result in an accurate time just after ntp started. **It usually takes minutes until ntp actually adjusts the time**. Also note that **standard insserv.conf just lists hwclock as $time**.

Plus, Raspbian release uses [systemd + init.d](https://unix.stackexchange.com/questions/233468/how-does-systemd-use-etc-init-d-scripts)

**Comment by rwaaren** [comment]
> You already commited the [modification](https://github.com/domoticz/domoticz/commit/09a81f91959ed39e6aa9794d028044b93d4c570a) without testing.
> 
change was tested by Eddy and me and works for us without problems. That does not imply it will work for all possible settings / configurations but at least it will not break anything that is not already broken.

**Comment by gizmocuz** [comment]
@agambier , that could be ... but then the time is set with the HWClock first, and later NTP

**Comment by agambier** [comment]
That's why it can't work.
during bootstage hardware clock is set with **fake-hwclock** service and then with NTP.
So domoticz starts because fake-hwclock is done, so $time is done, and later NTP synchronizes the clock and domoticz crashes.

This why in the log files timestamps are to equal to the time when the RPi was shutted down, fake-hwclock saves it at shutdown and reloads it back before NTP service does its jobs as soon as it can.

[fake-hwclock man page](http://manpages.ubuntu.com/manpages/bionic/man8/fake-hwclock.8.html)

Anyway....

**Comment by agambier** [comment]
@rwaaren : if you just rebooted right after you made the modification to /etc/init.d/domoticz.sh, of course it will work because the clock was synchronized before the reboot (since fake-hwclock save it just before reboot) and so it won't get delayed for more than 5 minutes for this reboot.

you must shutdown the RPi, unplug power and wait for at least 6 minutes before power it up again.

**Comment by rwaaren** [comment]
No I took the delay of > 5 minutes into account with my tests. 
What I did not test is a situation where the ntp service / server was not available when domoticz started.

In my setup, internet access is available before domoticz starts, so I never experienced the behavior you see.
If my situation was like yours I would always want the time/date to be more or less accurate before domoticz starts and I would implement a call to the ntp-wait program in my /etc/init.d/domoticz.sh to ensure domoticz would not start before ntpd could do it's work.
But as always YMMV.

As far as can see the implementation by @gizmocuz of the $time will not make your situation worse.

**Comment by gizmocuz** [comment]
If your internet is also not available, i would recommend to invest 1 $

https://www.aliexpress.com/item/32881077060.html?spm=a2g0o.productlist.0.0.1865777fkQhnPW&algo_pvid=362997d0-6cb1-4e8a-939b-9f510c12fd15&algo_expid=362997d0-6cb1-4e8a-939b-9f510c12fd15-1&btsid=4b57c1f9-fce5-4bfe-810a-ed78ee777f2b

**Comment by agambier** [comment]
For sure it won't make the situation worth but it doesn't fix the issue.

Thinking that $time will fix it, is a misunderstanding of how raspbian boot process works, that might help on PCs since they have hardware clocks.

If you've setup your raspbian to wait for the network to get ready it might help for sure.

After digging in the source files it's worth than I thought.
All heartbeats are based on system time and not a real clock ticks as it should.

What I'm saying is that implementation of watchdog and hearbeats in domoticz is very bad, not robust
and might be the source of other issues (and not only at boot time) and that why it needs to be fixed.

It is just in order to make domoticz better and reliable for everybody.

I'm able to find a workaround for myself....

**Comment by gizmocuz** [comment]
As mentioned earlier, there are far worse things going on if you do not have a correct date/time set.
(Timers.... scripts...)

As also mentioned, i am not to happy about the way the current watchdog is implemented.
It should also not exit the application and maybe try to restart the thread

We also know how to solve the issue in the software.

We also know how to solve the issue with hardware.

I think you should solve it both ways ! If you are going to depend on home-automation that you will run on a raspberry pi and you expect that this situation can occur, (and i am not talking about Domoticz, but any other software), i would definitely order some RTC boards,  I just ordered some more

About solving it software wise, I hope to find some time in the near feature, unless someone else beats me to it...

**Comment by agambier** [comment]
>As also mentioned, i am not to happy about the way the current watchdog is implemented.
It should also not exit the application and maybe try to restart the thread

This is the worth...
For now as a workaround I've added a [systemd drop-in file to restart domoticz service if it crashes](https://github.com/agambier/domoticz_addons/tree/master/systemd).

This is really a basic workaround but it helps making domoticz available in case of crash and it could be improved to send notification when domoticz is restarted because of a crash but I've no spare time untill september.

**Comment by merlot-dev** [comment]
> 
> 
> @agambier , i appreciate your research ! But there must be a 100.000 other users having this issue with the raspberry pi ?

I'm also experiencing a crash after cold restart

**Comment by merlot-dev** [comment]
> 
> 
> > As also mentioned, i am not to happy about the way the current watchdog is implemented.
> > It should also not exit the application and maybe try to restart the thread
> 
> This is the worth...
> For now as a workaround I've added a [systemd drop-in file to restart domoticz service if it crashes](https://github.com/agambier/domoticz_addons/tree/master/systemd).
> 
> This is really a basic workaround but it helps making domoticz available in case of crash and it could be improved to send notification when domoticz is restarted because of a crash but I've no spare time untill september.

Thank you for your effort.

I've come through this issue since I'm experiencing the same.

Unfortunately I can't apply this workaround as explained since I have no /etc/systemd/system/domoticz.service.d/   :(

Thank you anyway

**Comment by agambier** [comment]
> Unfortunately I can't apply this workaround as explained since I have no /etc/systemd/system/domoticz.service.d/ :(

This is normal, this directory doesn't exist you have to create it using
`sudo mkdir /etc/systemd/system/domoticz.service.d`
and then copy the `restart.conf` file.

This workaround can be applied to any Linux systems using systemd (Raspbian, Ubuntu based distros, ...)

Sorry for this mistake in my explanations.
I've update the README.md to add this frist command.

**Comment by gizmocuz** [comment]
@agambier , i think 5 seconds is a bit to fast... not sure how it will respond when you update to a new version. 30 seconds is maybe better

I think you mean 'can' ?

> This workaround can't be applied to any Linux systems using systemd (Raspbian, Ubuntu based distros, ...)

**Comment by agambier** [comment]
>I think you mean 'can' ?

Yes my bad...Fixed.

>@agambier , i think 5 seconds is a bit to fast... not sure how it will respond when you update to a new version. 30 seconds is maybe better

If the service is killed for example with `sudo killall domoticz` it will get restarted but if it is stopped properly with `sudo systemctl stop domoticz` it won't get restarted.

The update script seems to overwrite the files and then restart the service so it should work. At least from the command line.
```
echo "Updating to latest release version..."
echo "Please Standby..."
wget -O domoticz_release.tgz --no-check-certificate "https://www.domoticz.com/download.php?channel=stable&type=release&system=${OS}&machine=${MACH}"
tar xvfz domoticz_release.tgz
rm domoticz_release.tgz
echo "Restarting Domoticz... (please standby...)"
sudo service domoticz.sh restart
```

How do you perform the update from the web interface ? Do you call the update script ?

**Comment by gizmocuz** [comment]
Yes, the update script is called

**Comment by agambier** [comment]
So it should works.
I'll test it.
I'll modify the update script to add a 45s delay before extracting the files so I'll have the time to check the service status and it will 'simulate' a slow internet connection.

I'll let you know the results.

**Comment by agambier** [comment]
Do you think overwriting the files while domoticz is running may cause domoticz to crash ?

**Comment by agambier** [comment]
@gizmocuz : According to the source files the script called to update domoticz from the webinterface is not the same. I was talking about the `./updaterelease`

1. it calls `scripts/download_update.sh`
2. once it's downloaded it calls `scripts/update_domoticz`

here's the interesting part of the script :
```
# Restart on OSX
if [ ${OS} = "darwin" ]; then
  launchctl unload /System/Library/LaunchAgents/com.domoticz.server.plist
  echo "Please standby ... (waiting 15 seconds)"
  sleep 15
  launchctl load /System/Library/LaunchAgents/com.domoticz.server.plist
else
  sudo service domoticz.sh stop
  sudo systemctl stop domoticz.service
  echo "please standby... (waiting 15 seconds)"
  sleep 15
  sudo service domoticz.sh start
  sudo systemctl start domoticz.service
fi
```

There's a 15s delay to make sure the service is stopped.
It should be replaced, for Linux, with :
```
  sudo service domoticz.sh restart
  sudo systemctl restart domoticz.service
```

Since the restart command make sure the service is stopped before restarting it. 
As it's done in the script `./updaterelease`

**Comment by gizmocuz** [comment]
@agambier , if you tested the modified restart_domoticz then please make a PR

**Comment by dinacel** [comment]
I don't know if you work on this issue, if it was fixed, but I experienced the same problem on boot with a Raspberry Pi B+
And it seems the drop-in file works as expected ;)

**Comment by agambier** [comment]
I don't work on this issue and I will not because I've uninstalled Domoticz and switch to another app.
Hopefully for the domoticz community someone will take in consideration this bug because it might happen on any domoticz installation.

**Comment by jojobricolo57** [comment]
Hello,
I had exactly the same problem with a Raspberry Pi 4 and Buster. Crashes on cold start, every time. Domoticz newly installed and without plug-in. I tested with a raspberry Pi 3 and Stretch and it's the same thing, crash on startup.
After a lot of research I found this post and "domoticz_addons" from agambier solved all my problems. I confirm that there is a problem with Domoticz on Raspberry on cold start.
Thank you

**Comment by gizmocuz** [comment]
After reading this thread again, it seems to do with the date/time that might not have been set at your raspberry during startup

You do run with a internet connection on the Rpi i suppose ?

Are you able to connect a RTC module like the ds3231 ?

https://www.aliexpress.com/item/4000121268102.html

**Comment by jojobricolo57** [comment]
Hello
I do not use a ds3231 module on the raspberry, for me it is useless because it is connected to the internet and it sets the time on the internet. Domoticz is also connected to the internet for its functions. I don't see the point of adding this module, just to avoid a bug. I have several raspberry pi for several uses (motion, dns, etc.) and there has never been a need to maintain the time because it sets the time at boot. It would be good to correct this bug (even if I suspect that it is not easy) because an uninformed person will have big problems with Domoticz on Raspberry. I took a long time and a lot of manipulation before arriving here and finding this bug. Thank you

**Comment by gizmocuz** [comment]
@jojobricolo57 , i was just saying/meaning, if you have one laying around to test with it, so we can pinpoint the issue

**Comment by jojobricolo57** [comment]
I think there is no doubt about the problem, with the Domoticz agambier fix no longer crashing at boot. It is therefore a problem of time setting which makes Domoticz crash. I tested with a Raspberry 3 and 4, with Buster and Stretch, the version of Domoticz is the last version downloaded a few days ago, without plug in and without any configuration ("out of the box"). It is apparently an old bug and for novice users it is very difficult to find. If you could fix this it would be really good (but I think it's very complex).

**Comment by rwaaren** [comment]
Please help me understand which agambier fix you are referring to. The one I know of (and use) is a restart of domoticz after 5 seconds when it crashed; regardless what caused the crash.

**Comment by walawa75** [comment]
I also can report this issue. Domoticz still crashing on cold start and for a long time (last beta version too). When will you fix the issue please ? Maybe when over 10,000 users will leave the same message ;-) ?

**Comment by gizmocuz** [comment]
@walawa75 , it's very simple, make a patch, TEST everything and if everything is working, submit a PR

**Comment by agambier** [comment]
> Please help me understand which agambier fix you are referring to. The one I know of (and use) is a restart of domoticz after 5 seconds when it crashed; regardless what caused the crash.

I didn't make a fix but a **workaround**.

**Comment by agambier** [comment]
@gizmocuz : it's very simple when people are developper. That's why walawa75 asked the dev team a fix.

@walawa75, don't wait for a fix from the dev team. The ticket has been open last July and I also pointed out what source code is buggy (https://github.com/domoticz/domoticz/issues/3371#issuecomment-513207721) but the dev team didn't give a look at it. It's definitely a big fix cause all the timings are based on the same local timer but the dev team just tried to explain it completely normal.

**Comment by gizmocuz** [comment]
@agambier , thanks for your positive feedback, comment and help in this matter.
If you have a fix, please make a PR, if not, don't complain and try to help

**Comment by agambier** [comment]
62 comments and the only answer from the dev team is : "buy a RTC in China" and the issue is closed. 

I've already deeply examined and tested this issue....I let you count how many comments I wrote since I open this issue.

As I mentioned in a previous comment (https://github.com/domoticz/domoticz/issues/3371#issuecomment-571617297). I've uninstalled domoticz because of several issues and switch to another solution.

Sorry you get frustrated with my comment which is not a complain but just a fact.

**Comment by gizmocuz** [comment]
@agambier , First, I am not the 'dev team'
Yes, I suggested a RTC as a work-around , and this is a good investment anyway, not that it solves this issue
Yes, your tone makes everyone frustrated for sure ! It also does not solve anything.
There was however a possible Mutex issue in the startup that has just been fixed an hour ago, that could cause a crash at startup.
Solution seems simple, start the service when the system time has been initialized.
Maybe this is possible by tweaking the startup service

Then when someone asks here to point to the workaround and it's silent for 2 months, that does not help at all.

Anyway, I (not the 'dev team' ...) devote a lot of spare time to this project, and because of this i am unable to monitor everything (Sure i want to)
It does help when there is a solution and someone can make a PR that can be merged

**Comment by agambier** [comment]
Tweaking the start service is not a solution but a workaround, neither the
RTC. It's not because the NTP service has been started that the time is
set...you can't control when the NTP server will reply.

Already tried it...

If the local time is changed even after domoticz has ran for 10
days...domoticz crashes...so it might also happen when the time is changed
for the DST by adding an hour.

Already tried it...

That is what I've tried to explain dozen of times the issue is in the code
because it's based on the local time. Since this local time can be changed
or not set it's not a reliable clock that should not be used by the
domoticz internal watchdog.
You can try every workaround you want as soon as the time is changed
domoticz might crash.

I didn't ask to point to the work around to fix it...I pointed to the
source code that handle the watchdog. The workaround is just for people who
wants domoticz alive in case it crashes for any reason, even those not
related with this issue.

**Comment by agambier** [comment]
> Anyway, I (not the 'dev team' ...) devote a lot of spare time to this project, and because of this i am unable to monitor everything (Sure i want to)
> It does help when there is a solution and someone can make a PR that can be merged

You're 100% right ! 
but don't close an issue that is not fixed but confirmed by many users.

**Comment by walawa75** [comment]
> @gizmocuz : it's very simple when people are developper. That's why walawa75 asked the dev team a fix.

@gizmocuz your reaction is all the more sad that you really do a great job on domoticz (thank you really !!). Now we can tell you that YES there is an annoying bug that affects everyone, not just @agambier, which was simply the first to report it. I really was thinking that we were helping you by report you some domoticz bugs.

@agambier A big thank for your great fix method !!

**Comment by gizmocuz** [comment]
It does not happen when the DST changes, this is tested many times over the last years
It is also very easy to change the system time on a machine while Domoticz is running
This issue is/was/is? at the startup
As said there has been made a patch in 11939 that solves a possible crash at startup, and this might be related

**Comment by gizmocuz** [comment]
@agambier , this issue is closed automatically as there was no more messages/response in this issue.
It's system wide that this happens.
We need to do this because some issues are solved and there is no feedback that it works

**Comment by agambier** [comment]
>It does not happen when the DST changes, this is tested many times over the last years

You told me the same when I open this issue and told me I was the only one.

> It is also very easy to change the system time on a machine while Domoticz is running

And this will make domoticz crash...I tried it last summer to confirmed it !

> This issue is/was/is? at the startup

If the time is not set when domoticz starts and then the time is set by the NTP server with a new time different of  **Heartbeat_Timeout**   so domoticz crashes... But it's not only at startup it's when the time is changed with a value greater than the value **Heartbeat_Timeout** ....it's not in the domoticz startup procedures...it's in the watchdog that watch the plugins time execution.
I already explained and described everything several times before.

> As said there has been made a patch in 11939 that solves a possible crash at startup, and this might be related

If you fixed the watchdog it might be otherwise it's not.

**Comment by agambier** [comment]
> @agambier , this issue is closed automatically as there was no more messages/response in this issue.
> It's system wide that this happens.
> We need to do this because some issues are solved and there is no feedback that it works

The first time yes.
Today you closed it 4 hours ago.
Anyway....

As said walawa75 we tried to help the domoticz team by reporting bugs and also to spend a lot of our **spare** time to figure out and test  what's really happening in order to help the domoticz team so you guys won't have to re-test from the beginning and know the context of this issue.

You do a great work and a lot of work for sure but after more than 60 comments from many people your reply is : _"
@walawa75 , it's very simple, make a patch, TEST everything and if everything is working, submit a PR"_. 

I hope you didn't expect us to react a different way we did ?

**Comment by gizmocuz** [comment]
@agambier , the reason it was closes yesterday was because of your (again) positive feedback.

**Comment by agambier** [comment]
> @walawa75 , it's very simple, make a patch, TEST everything and if everything is working, submit a PR".

@gizmocuz: again don't get surprised of my positive feedback after your reply to walawa75. 

I definitively give up on domoticz.

**Comment by gizmocuz** [comment]
@agambier , heard you before.
Replying here with your negative vibes does not contribute to anything and just floods this issue.
