### ISSUE TITLE
Neo Coolcam PIR V2 pd02z.xml

### ISSUE THREAD

**Issue by poudenes** [domoticz/domoticz#3372]
Hi All,

It was not possible to disable the LED of the device. After some reading I did follow

`<Value type="list" genre="config" instance="1" index="10" label="Motion detection LED indication" value="1" size="1">  `
to
`<Value type="list" genre="config" instance="1" index="11" label="Motion detection LED indication" value="1" size="1">  `

Because Index 10 have a other function:

Function: Ambient Temperature Differential Report
Parameter Number: 10
Parameter Size: 1 Byte
Available Settings: 0 ~ 127
Default Setting: 5

Also there is a missing option

Function: Ambient Light Intensity Calibration
Parameter Number: 99
Parameter Size: 2 Byte
Available Settings: 1 ~ 65536
Default Setting: 1000

This is documented in manual and on this link:
https://products.z-wavealliance.org/products/1920/configs

Can you update the XML file?

**Comment by gizmocuz** [comment]
Thanks for your report. You have to supply this information to the OpenZWave project as we use their configuration files.
Once it is there, it will be merged from time to time into the Domoticz repository

**Comment by poudenes** [comment]
Did the request at OpenZWave :)
