### ISSUE TITLE
Multiple To addresses in email

### ISSUE THREAD

**Issue by mzealey** [domoticz/domoticz#3374]
When specifying multiple To addresses in email configuration section you MUST NOT have any whitespace around ;'s. For example I created `a@example.com; b@example.com` and then it tries delivering to ` b@example.com` (with a space in front of it) which obviously breaks things. Can you please change the code to split based on `/\s*;\s*/` or something as this is a nasty and unexpected bug.

**Comment by Olifant1990** [comment]
Need to use a kind of split on ; and/or a , and trim the white spaces I guess

**Comment by gizmocuz** [comment]
I would have expected that the extra space infront/behind would not break things ..
Fixed in https://github.com/domoticz/domoticz/commit/d9a86d234fcf60ab35a34c69753e847e865f3459
Will be available in a new beta soon
