### ISSUE TITLE
Motherboard Sensors on Raspberry Pi show the wrong values

### ISSUE THREAD

**Issue by TheReptile** [domoticz/domoticz#3375]
I noticed the disk space usage from the motherboard sensors report incorrect values on my Raspberry Pi 3.
These are the values in Domoticz:
![image](https://user-images.githubusercontent.com/22954131/60668385-1c4d5f00-9e6c-11e9-9b69-ea557dd154f5.png)

But in the console I see these values:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        57G  2.4G   53G   5% /
devtmpfs        459M     0  459M   0% /dev
tmpfs           464M     0  464M   0% /dev/shm
tmpfs           464M   47M  417M  11% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           464M     0  464M   0% /sys/fs/cgroup
/dev/sda1        42M   25M   17M  61% /boot
tmpfs            93M     0   93M   0% /run/user/1000
```
I'm using a 64 GB USB stick.

**Comment by gizmocuz** [comment]
Seems almost correct. We use 'df -x nfs -x tmpfs -x devtmpfs' and calculate the exact (not rounded) percentage with the blocks

double UsagedPercentage = (100 / double(dusage.TotalBlocks))*double(dusage.UsedBlocks);

**Comment by TheReptile** [comment]
@gizmocuz  Ehm, no?
/boot is 61% in use, yet in domoticz it's 4.15%?
and for / it's 5% vs 60.46%

But now you mention it, it seems the values of /boot and / are mixed up.

**Comment by JurikRistjouw** [comment]
@gizmocuz seems @TheReptile is right....

![photo_2019-07-04_22-26-29](https://user-images.githubusercontent.com/8580506/60686724-cba92680-9eaa-11e9-9161-f8baa1d7db96.jpg)

![image](https://user-images.githubusercontent.com/8580506/60686804-2e9abd80-9eab-11e9-84ec-e5578bb9f960.png)


![image](https://user-images.githubusercontent.com/8580506/60686738-e1b6e700-9eaa-11e9-87af-39f61eb8a288.png)

**Comment by gizmocuz** [comment]
@JurikRistjouw , mmm yep seems so, strange as this worked for more then a year... maybe DF has had some updates
Please have a look at the code (HardwareMonitor.cpp), ~lines 794 and 827

`double UsagedPercentage = (100 / double(dusage.TotalBlocks))*double(dusage.UsedBlocks);`

UsagedPercentage = (100/42137)*22685 = 53.83

I wrote a test application for you guys to test, copy and paste this to a file called **main.cpp**

```
#include <iostream>
#include <vector>
#include <map>
#include <cstring>

struct _tDUsageStruct
{
	std::string MountPoint;
	long long TotalBlocks;
	long long UsedBlocks;
	long long AvailBlocks;
};

std::vector<std::string> ExecuteCommandAndReturn(const std::string &szCommand, int &returncode)
{
	std::vector<std::string> ret;

	try
	{
		FILE *fp;

		/* Open the command for reading. */
#ifdef WIN32
		fp = _popen(szCommand.c_str(), "r");
#else
		fp = popen(szCommand.c_str(), "r");
#endif
		if (fp != NULL)
		{
			char path[1035];
			/* Read the output a line at a time - output it. */
			while (fgets(path, sizeof(path) - 1, fp) != NULL)
			{
				ret.push_back(path);
			}
			/* close */
#ifdef WIN32
			returncode = _pclose(fp);
#else
			returncode = pclose(fp);
#endif
		}
	}
	catch (...)
	{

	}
	return ret;
}

int main() 
{
	std::string m_dfcommand;
	int returncode = 0;
	std::vector<std::string> ret = ExecuteCommandAndReturn("df -x nfs -x tmpfs -x devtmpfs 2> /dev/null", returncode);
	returncode == 0 ?
		m_dfcommand = "df -x nfs -x tmpfs -x devtmpfs" :
		m_dfcommand = "df";

    std::cout << "Calculating disk usages...\n\n";
    
	//Disk Usage
	std::map<std::string, _tDUsageStruct> _disks;
	std::map<std::string, std::string> _dmounts_;
	std::vector<std::string> _rlines=ExecuteCommandAndReturn(m_dfcommand, returncode);
	if (!_rlines.empty())
	{
		for (const auto & ittDF : _rlines)
		{
			char dname[200];
			char suse[30];
			char smountpoint[300];
			long numblock, usedblocks, availblocks;
			int ret = sscanf(ittDF.c_str(), "%s\t%ld\t%ld\t%ld\t%s\t%s\n", dname, &numblock, &usedblocks, &availblocks, suse, smountpoint);
			if (ret == 6)
			{
				std::map<std::string, std::string>::iterator it = _dmounts_.find(dname);
				if (it != _dmounts_.end())
				{
					if (it->second.length() < strlen(smountpoint))
					{
						continue;
					}
				}
				if (strstr(dname, "/dev") != NULL)
				{
					_tDUsageStruct dusage;
					dusage.TotalBlocks = numblock;
					dusage.UsedBlocks = usedblocks;
					dusage.AvailBlocks = availblocks;
					dusage.MountPoint = smountpoint;
					_disks[dname] = dusage;
					_dmounts_[dname] = smountpoint;
				}
			}
		}
		int dindex = 0;
		for (const auto & ittDisks : _disks)
		{
			_tDUsageStruct dusage = ittDisks.second;
			if (dusage.TotalBlocks > 0)
			{
				double UsagedPercentage = (100 / double(dusage.TotalBlocks))*double(dusage.UsedBlocks);
				std::cout << "Disk: " << ittDisks.first << ", Mount: " << dusage.MountPoint << ", Used: " << UsagedPercentage << " %" << std::endl;
				dindex++;
			}
		}
	}

    return 0;
}
```
Next issue **g++ main.cpp -o main**

now test the program with:

**./main**

Is this correct?

**Comment by TheReptile** [comment]
@gizmocuz This is my output:
```
Calculating disk usages...

Disk: /dev/root, Mount: /, Used: 4.16197 %
Disk: /dev/sda1, Mount: /boot, Used: 60.4614 %
```
This seems to be correct:
```
$ df -h | grep -e root -e sda1
/dev/root        57G  2.4G   53G   5% /
/dev/sda1        42M   25M   17M  61% /boot
```
Perhaps a bit off-topic, but is it possible to reopen a closed issue?
I can't see any way to re-open the issue as the reporter.

**Comment by gizmocuz** [comment]
This is what Domoticz is doing as well...
Strange..
Can you debug the code in Domoticz?

**Comment by TheReptile** [comment]
I'll have a look, not sure how yet.

**Comment by gizmocuz** [comment]
Did you find anything ? Also create a forum post

**Comment by ravsit-activum** [comment]
I had similar errors regarding value of disk usage.
Domoticz creates devices according to the current state when creating the "Motherboard sensors" hardware. If the mount points change, e.g. when replacing the disk (SD card (rpi) to usb or ssd), Domoticz does not update the mount point descriptions. Then the read values are written to previously defined devices.
For me, something like this happened on rpi when I changed my sd card to ssd.
The solution is to change the descriptions HDD \.....  to the correct one according to the df (linux) command or to remove and re-add "Motherboard sensors". New devices will be created with the correct mount point description (however, new idx device numbers will be inconvenient).

I think that this is not an error, and handling such cases in the code will be difficult to implement.

**Comment by TheReptile** [comment]
I completely forgot about this due to real life interfering. 
What @ravsit-activum states sounds very plausible, since I migrated my setup from micro-SD to an USB-stick to prevent data corruption. Might be best to close this issue since it's user-caused.
