### ISSUE TITLE
Domoticz/GBridge Plugin crashes at startup after updating OS

### ISSUE THREAD

**Issue by JurikRistjouw** [domoticz/domoticz#3377]
I have updated my pi yesterday with the usual sudo apt update/upgrade.. after which domoticz crashes at startup. I have no clue what is wrong.  

Please advice how to approach/solve this issue? I allready installed the latest beta (10949)

Kind regards,

Jurik
[domoticz_crash.log](https://github.com/domoticz/domoticz/files/3363434/domoticz_crash.log)

**Comment by dnpwwo** [comment]
Don't know the fix but know the underlying cause.

From the stack trace it looks like the last update to the OS has made a change to the OpenSSL library that is now incompatible.  SSL has been an issue for a while on RPi, there are forum posts on potential fixes, I would suggest you look at those to see if it will help here.

**Comment by JurikRistjouw** [comment]
@dnpwwo Thanx, but my knowledge ends just about right there. Is there any way to revert the update to the OS of another fix?

**Comment by JurikRistjouw** [comment]
update: I figured it might be the gbridge plugin. As this is the only one working with the SSL library afaik. I moved the plugin, and now domoticz starts and works. I also updated to 10970. Should I open an issue on the gbridge repo?

**Comment by JurikRistjouw** [comment]
I opened an issue with the gbridge plugin repo:
https://github.com/giejay/domoticz-gbridge-plugin/issues/14

**Comment by JurikRistjouw** [comment]
Latest updates seems to de the trick
