### ISSUE TITLE
No rule to make target `/usr/lib/x86_64-linux-gnu/libudev.a'

### ISSUE THREAD

**Issue by antz29** [domoticz/domoticz#338]
Compile error when building on Ubuntu 14.04 - 

<img width="736" alt="screen shot 2016-01-14 at 10 58 34" src="https://cloud.githubusercontent.com/assets/190449/12322753/03d0fe46-baae-11e5-85d2-389787c957a7.png">

Have followed all the steps from the docs, all dependencies are installed, open-zwave compiled successfully.

Any assistance would be greatly appreciated! :smile:

**Comment by sbouchex** [comment]
have you installed the libudev-dev (64 bit) package ?

**Comment by antz29** [comment]
@sbouchex yes, libudev-dev is installed - see the output of apt-get policy below:

```
# apt-cache policy libudev-dev
libudev-dev:
  Installed: 204-5ubuntu20.15
  Candidate: 204-5ubuntu20.15
  Version table:
 *** 204-5ubuntu20.15 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     204-5ubuntu20 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

**Comment by sbouchex** [comment]
And in CMakeCache.txt ? What do you have ?

**Comment by sbouchex** [comment]
Just tried with a fresh 14.4 install : Everything went fine and got a valid binary

**Comment by gizmocuz** [comment]
also working fine on ubuntu 14 here

**Comment by gizmocuz** [comment]
No feedback, try a fresh install
