### ISSUE TITLE
BETA [4.10949] scenes doesn work anymore

### ISSUE THREAD

**Issue by henkiejan1** [domoticz/domoticz#3380]
Hi all,

After the last updates does my scenes not work anymore. The ESP lights with Espurna turns off instead of On and the settings with OpenZWAVE are not made. In the log of the Espurna devices i read:

`[926128] [DOMOTICZ] Error parsing data` continuesly... Maybe a reason it doesn work?

More information:
OrangePi Zero Plus
Allwinner H6 1.8GHz quadcore
1GB RAM
32GB SD card
Armbian 5.88 based on Ubuntu 18.04 LTS kernel 5.1.7

**Comment by gizmocuz** [comment]
@henkiejan1 , what was your previous Domoticz version ?
There have been many changes in OpenZWave lately and we are trying to integrate version 1.6

Could you explain "ESP lights with Espurna" a bit more ? As i understand, Espurna is working via MQTT ? There should be no changes related to MQTT in the beta version

What settings in OpenZWave are not saved/made ?

**Comment by jeroenkl** [comment]
Same problem:
SInce the last domoticz update the scenes are not working correctly.

 I've configured some lamps to switch 'On' but it is after the update set to '100%':

Incorrect:
 2019-07-06 09:34:51 Off 
 2019-07-06 09:34:21 Set Level: 100 % 
 2019-07-06 09:34:20 Set Level: 100 % 

correct (before the update):
 2019-07-05 12:01:03 Off 
 2019-07-05 12:00:34 On 
 2019-07-04 22:23:11 On 

 Version: 4.10959

 Hope this can be fixed,
 Jeroen

**Comment by jeroenkl** [comment]
probably caused by this change:
**Activating a scene containing devices which are dimmable now correctly… #3366**

**Comment by gizmocuz** [comment]
@jeroenkl , patch has been reverted in beta 10961 (available soon, building now)

@henkiejan1 , if you still could explain the workings of ESP and OpenZWave please

**Comment by jeroenkl** [comment]
thx's fixed

**Comment by henkiejan1** [comment]
> @jeroenkl , patch has been reverted in beta 10961 (available soon, building now)
> 
> @henkiejan1 , if you still could explain the workings of ESP and OpenZWave please

Excuse me for my late reply. But the scene does the following: It switched a few Sonoff switches on, after a delay of 3 seconds OpenZwave set the color and the brightness of the ZigBee lights in the bulb. Works with the older version, (prevrious beta) perfect. :)

The problem looks like fixed excuse me for my late reply. I am happy it works again.

**Comment by gizmocuz** [comment]
@henkiejan1 , thanks, but could you explain the ESP and Espurna ? Maybe point to the sketches ?
I have no experience with this and would like to test with that
