### ISSUE TITLE
Previous scene name visible when adding new scene

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#3386]
When one new scene is created, the Add Scene dialog appears correctly:

![Screen Shot 2019-07-06 at 8 28 09 pm](https://user-images.githubusercontent.com/6681733/60760389-9cbabe00-a02c-11e9-8558-be2410c04bf9.png)

After that, when the 'Add Scene' button is pressed the dialog box displays the name of the previously added scene.

![Screen Shot 2019-07-06 at 8 28 20 pm](https://user-images.githubusercontent.com/6681733/60760395-a9d7ad00-a02c-11e9-8d82-99afebc090cb.png)

**Comment by rwaaren** [comment]
Maybe I misunderstand. But why is this a code bug ? 
I happen to like it this way but if you like it or not is besides the point if it is a bug or not.

**Comment by ghost** [comment]
Of course it’s a bug. It never used to do this, and this isn’t correct UX behaviour.

Why on earth would you want to create two scenes with the same name? This is clearly an error.

**Comment by rwaaren** [comment]
In my opinion it is not a bug and it has been like this for at least since last stable but probably longer.
Even if you don't want to create multiple scenes with the same name is can be quite convenient for creating multiple scenes (or devices where you will see the same behavior) with similar names (like test01, test02, etc)
If you don't like it just refresh your cache (ctrl - r ) on chrome and the duplicate of the name will disappear in the create popup window.

**Comment by gizmocuz** [comment]
This is not a Bug, and sometimes very helpful

**Comment by ghost** [comment]
This is terrible UX and is absolutely a bug. You will never find this behaviour anywhere else.

Completely disregarding my opinion is also incredibly rude and insulting.

What is the point of open source if the people giving feedback aren’t even listened to?

**Comment by gizmocuz** [comment]
@leecollings , this is not considered a bug, if it was, it was corrected years ago
Secondly, we noticed your feedback , provided our feedback.
So it is meant to be, and it will stay like this.

And how rude was just your response ?

**Comment by ghost** [comment]
I’ll let it go because I respect your response and decision, but I can assure you my response was in no way rude.

**Comment by gizmocuz** [comment]
Neither was mine ;)
