### ISSUE TITLE
OpenZwave mess

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#3387]
Since about May my door lock (Kwikset Smartcode 910) stopped working.  It no longer talks back to Domoticz.  I can still actuate it.  But Domoticz can't consistently tell if it's locked or not.  I have a feeling it's related to all the new configurations updated an added from OZW.  My thermostat also lost all kinds of functionality as well. I built that config file myself for that and it seems that all the work was replaced with a file that isn't as good.   I also see this error "OpenZWave: Unhandled value type: 9, OpenZWave.cpp" spamming my log constantly and it has been for over a month.  It seems like it showed up around the same time so it may be related.

**Comment by gizmocuz** [comment]
@Ittiz , firstly, if you want us to help you, it could help by making a proper issue following the guidelines and  with a normal topic.
Secondly, as you already noticed we are working on getting OZW 1.6 implemented which is not that easy

You can just switch back not to the stable if you want (use to forum to see how to do this)

Or you could help by providing the correct/complete log lines....

And also specify your Domoticz version please !
