### ISSUE TITLE
TEXT sensor in Blocky if will never match

### ISSUE THREAD

**Issue by pvojnisek** [domoticz/domoticz#3388]
Getting TEXT messages from devices triggers a blocky event. If you try to match string in the TEXT sensor the result will never be true.
![image](https://user-images.githubusercontent.com/45441/60761803-a7874a00-a050-11e9-93e8-74b377d7b149.png)
The example above will never reach the write to log line.

**Comment by rwaaren** [comment]
PLease have a look at [ this ]( https://www.domoticz.com/forum/viewtopic.php?f=62&t=28388&p=217446&hilit=text+blockly#p217438)
