### ISSUE TITLE
Z-Wave Groups & Network menu option is missing

### ISSUE THREAD

**Issue by rrozema** [domoticz/domoticz#3389]
I can't recall the exact title anymore, but in the menu under the 'Node Management' button in the z-wave hardware setup screen there used to be an option to look at and change the associations for each z-wave device. This option is no longer available in beta version 4.10965.

Compiled using VC 2017, running on windows 7.

Since https://github.com/domoticz/domoticz/commit/b3e6f2458f8fe3faae03b7568b19e1f9b3844466#diff-f685a5212acf109be13a0418b5117d74
The next bit of code is missing from www/app/hardware/setup/ZWave.html:

                            <li><a href="javascript:ZWaveTopology();" ><button type="button" data-i18n="Groups & Network" class="btn btn-success">Groups & Network</button></a></li>

**Comment by gizmocuz** [comment]
You have this in the main hardware setup now as a separate tab:

![image](https://user-images.githubusercontent.com/2265299/60765223-f657d280-a096-11e9-9d6b-95bf63f6f71d.png)

**Comment by ReneSanders** [comment]
These tabs don’t work  in safari (iPad)

**Comment by gizmocuz** [comment]
@ReneSanders , how about the tabs in the settings ?
Do you see any errors ?

**Comment by ReneSanders** [comment]
@gizmocuz no, i don’t see any error.
Tabs like like in the system settings works fine
![BF028389-1944-4AB6-BA22-9E979483BE63](https://user-images.githubusercontent.com/49289241/62832562-dcc71f00-bc30-11e9-86bc-8bf402c97d2d.jpeg)

**Comment by gizmocuz** [comment]
Strange, as besides from duplicate section id's this has partly been copy/pasted from the setup page, and i do not see any errors.
Maybe you can help debug this on Safari ...
Do you have issues with Chrome or Firefox ?

**Comment by ReneSanders** [comment]
Tried it also within chrome. The same problem. I tried to activate the debug mode on safari but because I only have an IPad without a other Mac device, it is not possible to put it in develop mode. Now i try to find more info with chrome on my iPad

**Comment by petergebruers** [comment]
It's got to iPad specific then... Not only because you mention chrome has issues too, but because last week I checked the "groups" editor on Safari + macOS Mojave... I've got a (very) old iPad 2 on iOS 9 but cannot test right now.

**Comment by ReneSanders** [comment]
You are right. I have also the feeling that it is related to the iOS system. I’m using the iPad Air 2019 with iOS 12.4.  Problem with iOS is the debug mode. I can not activate it for safari and chrome because I don’t have a other Mac with safari.
