### ISSUE TITLE
On/Off Switch in Group show percentage state instead of "On"

### ISSUE THREAD

**Issue by jcwlim** [domoticz/domoticz#3390]
With the latest self compile version.
When I toggle the **group** to "On", all the "On/Off" subtype switches will show "Set Level: 100 %" instead of "On", this make all the previous set events not working.
Checked, if I toggle directly from the switch itself, status show "On"

**Comment by gizmocuz** [comment]
I think this has been reverted yesterday, could you checkout the latest code and test ?

**Comment by jcwlim** [comment]
Thanks for the information :)
Yes, confirmed it reverted back. Everything work fine with the latest code.
