### ISSUE TITLE
Cannot list devices

### ISSUE THREAD

**Issue by lovethat777** [domoticz/domoticz#3391]
Issue: On a fresh install, after adding a Xiaomi Gateway, stuck on "loading" on the "devices" page.

Version DomoticzSetup_4_10717 on Windows. Latest Python x86 installed.

![image](https://user-images.githubusercontent.com/51493833/60770681-21b1e000-a0de-11e9-909c-3749188f71d3.png)

The following request:

`http://127.0.0.1:8080/json.htm?displayhidden=1&filter=all&type=devices&used=all`

Returns the following, which has no `result` attribute:

`{
   "ActTime" : 1562521547,
   "app_version" : "4.10735",
   "status" : "OK",
   "title" : "Devices"
}
`

**Comment by gizmocuz** [comment]
@lovethat777 , is this still the case with the latest beta version ?
In the Devices.js i see code that checks against this..

**Comment by gizmocuz** [comment]
No feedback, guess it is solved
