### ISSUE TITLE
XiaomiGateway on another network

### ISSUE THREAD

**Issue by lovethat777** [domoticz/domoticz#3393]
How to add a Xiami GW which resides on another subnet than Domoticz ?
Example: Domoticz on 192.168.1.47 and Xiaomi GW on 10.59.50.34

I keep getting `XiaomiGateway (ID=2): Could not find local IP address with ifaddrs`

**Comment by sincze** [comment]
Tried to add Xiaomi on my IOT-VLAN, (domoticz in main LAN) same case, no luck. 
I need packet sniffer to determine where the packages get lost.

> Make sure the WiFi where your Xiaomi Gateway is connected is on the same subnet as your Domoticz server. Also have your Domoticz server connected directly to the same WiFi network, rather than a LAN cable (try disconnecting the LAN cable as well)

[wiki](https://www.domoticz.com/wiki/Xiaomi_Gateway_(Aqara))

**Comment by gizmocuz** [comment]
Could you please continue this discussion on the Forum
