### ISSUE TITLE
Second Xiaomi Gateway not create any device

### ISSUE THREAD

**Issue by vampywiz17** [domoticz/domoticz#3396]
Hello there,

I add a new Xiaomi gateway to my Home Automation system. I only want to use the light funktion, so i not add any child device.

I successfully add it to Domoticz, no error in log, but not create any device in devices tab. I check all possible things that i found in net (firewall, enable add device, restart Domoticz, same network etc...) but everything is working well.

Both gateway is same type, this one: https://www.aliexpress.com/item/32828475718.html?spm=a2g0s.9042311.0.0.43ee4c4dcLRIUV

Of course, the first is working normally. (with child devices)

I use latest stable Domoticz release.

**Comment by vampywiz17** [comment]
I found this in OpenHAB forum. The problem is similar and thay sayed the solution is first enable developer mode and after update the device... 

https://community.openhab.org/t/solved-openhab2-xiaomi-mi-gateway-does-not-respond/52963/193

The problem is i first update it, and after enable the dev. mode...

What do you think it possible that the auto discovery will work after the next firmware update?

**Comment by gizmocuz** [comment]
Please continue the discussion on the forum
