### ISSUE TITLE
Electric (Instant+Counter) daily total and initial value not calculated correctly

### ISSUE THREAD

**Issue by bjornprins** [domoticz/domoticz#3399]
I am monitoring the total revenue of a Piko solar inverter. Type is virtual device Electric (Instant+Counter). Both counter are filled with correct values every 5 minutes. The data in the tables look correct.

Two issues:
1. The initial value (here 6936 kWh) is always the initial counter of lifetime total, which is very high (not zero), so the graph starts with a spike. I expect Domoticz to calculate the difference with the second value and remove the initial (false) value.
2. Four days later the Last week graph shows a second spike (total counter, not difference since day before). It looks like there is an error in the calculation of totals per day.

Is it possible there is a bug in at MainWorker::decode_Energy (starting at line 8851 in mainworker.cpp)? I'm not very good at reading C++ code ;-)
The problem doesn't seem to exist with another virtual device (also solar inverter).

![image](https://user-images.githubusercontent.com/31687156/60949261-1b498100-a2f5-11e9-814e-747a1ce7a700.png)

This is an example of a different inverter (also Electric(Instant+Counter)) where the very high initial (lifetime) value is still visible in the monthly graph, so the other (lower/correct) values are not visible.
![image](https://user-images.githubusercontent.com/31687156/60949743-1d600f80-a2f6-11e9-9419-46e948ef4ba6.png)
 

Also posted this in the forum (no replies until now):
https://www.domoticz.com/forum/viewtopic.php?f=14&t=28618

**Comment by gizmocuz** [comment]
Because it is a virtual device and the default (first) value is 0, this can happen
Shift-click on the data point allows you to remove it

About the second issue, we use the meter value, this value should be a continues incremental value
There is no difference in calculation between your two sensors

**Comment by bjornprins** [comment]
The first value is the lifetime amount of energy generated. In this case 6 MW or 15 MW. I cannot reset these counters in the inverters. I tried to delete the first value, but it doesn't work. It asks for confirmation, but nothing happens, other values can be deleted, but not the first I guess.

The meter value is indeed a continuesly increasing value. But sometimes the day total isn't substracted from the day before and it shows the meter value instead of the difference.

**Comment by gizmocuz** [comment]
Try shift-click in the Last Month / Year graph

**Comment by bjornprins** [comment]
Whahaha, that worked! ;-)
It IS possible in the Last Month graph to delete a data point on the line chart, but it ISN'T possible in the Last Week graph. Bars can't be deleted it seems. 
And I was able to delete the initial value. Thanks!!

![image](https://user-images.githubusercontent.com/31687156/60976771-98ddb300-a32e-11e9-90d6-477df032d390.png)

**Comment by bjornprins** [comment]
Point 2: How can you explain the second peak 7023.181 kWh in the Last Week graph of the first screendump on Saturday? Now I have a gap, missing about 17 kWh that day.

**Comment by gizmocuz** [comment]
I can't.. it must be received

**Comment by bjornprins** [comment]
I think I found out why the wrong value was calculated. It looks like the Domoticz service was having issues with a buggy script I made. It was on 7/6/2019 at 0:00 AM. That's the time the daily total is calculated probably. So I will keep an eye on the graph for the coming weeks to see if it's fine now. Thanks for the help.

**Comment by gizmocuz** [comment]
Thanks for the feedback !

**Comment by bjornprins** [comment]
Please reopen this issue.
The problem with the peak values isn't related to a bug in my script. (See screen dump in next post) The daily total gets calculated wrong at least once a week. In the logs nothing wrong is reported. The peak value is lifetime total at that moment ( midnight?). I can delete those values, but that leaves zero's and wrong totals over the longer run. My script picks up the current value and lifetime total and returns this with dzvents. Nothing special and the values are correct because the lifetime total in the graph is the one I return.

**Comment by bjornprins** [comment]
![Screenshot_20190808-103435_DuckDuckGo](https://user-images.githubusercontent.com/31687156/62712400-c585f880-b9c8-11e9-8d58-e989be870544.jpg)

**Comment by gizmocuz** [comment]
There is a Forum section for dzVentz, when you post there, also post your script
