### ISSUE TITLE
Planned dimmer values

### ISSUE THREAD

**Issue by Epy** [domoticz/domoticz#342]
Hello
I'm using Domoticz on a virtual machine (Debian) linked to a Raspberry with Razbian and Z-Way. My heaters are controlled by QUBINO PWM modules seen as dimmers.

When I set values for those dimmers in a planning at defined hours (midnight, 2 AM etc.) the set values are 1% off the requested value:
I choosed 25% for example from the 5 by 5% list, I found it set à 24%; same for 20% set at 19% etc.

It's not a major bug but if it takes only a minute to fix it .. ;)
Thank you !

**Comment by gizmocuz** [comment]
Please use our form
