### ISSUE TITLE
Extend the "udevices" API call with json parsing 

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#343]
Current implementation of "udevices" is doing parsing with lua scripts but json parsing is not very easy with lua since there is not such json library for lua and embedding it in domoticz may not be easy.

Proposal: Add some lua functions to parse json

Example:
local temperature = domoticz_parseJson(buffer,"Monitor.S.S1.item1.value");
domoticz_updateDevice(15,0,temperature);

To do so, I would use the json library already there

I can do it

**Comment by gizmocuz** [comment]
Sound great, please go ahead !
