### ISSUE TITLE
Limitless\Milight Controller -  and RGBW

### ISSUE THREAD

**Issue by raspberry007** [domoticz/domoticz#352]
Hi,

I have created 10 IDs (4 channel per controller plus a master one) for two LED controllers (RGBW and CC/WC). However, I can only switch on one of them at one given time. If I want to change controllers, I have to change it Setup - Hardware - Limitless - Set mode - Type: RBGW or White. I am not able to use both of them at the same time. This is not logical at all. If all IDs present in the system, it would be more appropriate that the type is determined according to the ID? 

Many thanks
Alex

**Comment by gizmocuz** [comment]
Please use our form
