### ISSUE TITLE
No icons on floorplan for custom sensors

### ISSUE THREAD

**Issue by jlpdiez** [domoticz/domoticz#3523]
Tested with two Raspi3b+ with both Stable (4.10717) and beta (4.10940) versions.

I'm unable to display custom sensors icons from plugins in the floorplan. The *Floorplan Editor* results in the following image under **Firefox**:
![Screenshot from 2019-07-11 12-37-46](https://user-images.githubusercontent.com/3782057/61045477-38f11600-a3db-11e9-956c-6e1c67ae8154.png)
And under **Chromium**:
![Screenshot from 2019-07-11 12-53-18](https://user-images.githubusercontent.com/3782057/61045329-ef083000-a3da-11e9-8a8c-7a2d6ef86d14.png)

As you can see the icon from the plugin [WAN IP Checker](https://github.com/ycahome/WAN-IP-CHECKER) is displayed but not so the ones from [Speedtest](https://github.com/Xorfor/Domoticz-Speedtest-Plugin), [Disk Usage](https://github.com/Xorfor/Domoticz-Disc-usage-Plugin) or [PiMonitor](https://github.com/Xorfor/Domoticz-PiMonitor-Plugin). In Firefox you can't even move the thing. I suspect it maybe has to do with the displaying one being of type *Alarm* while the rest are *Custom Sensor*
![Screenshot from 2019-07-11 12-54-07](https://user-images.githubusercontent.com/3782057/61045450-2b3b9080-a3db-11e9-818e-a8b8f3096827.png)
![Screenshot from 2019-07-11 12-39-25](https://user-images.githubusercontent.com/3782057/61045097-70ab8e00-a3da-11e9-8826-d4872169874c.png)
As you can see, manually changing the icon for the custom sensor to any other doesn't fix the issue.

The Chromium console reports the following.
![Screenshot from 2019-07-11 13-00-51](https://user-images.githubusercontent.com/3782057/61046049-773b0500-a3dc-11e9-83bc-22416fbbbe6c.png)
In detail:
![Screenshot from 2019-07-11 13-15-21](https://user-images.githubusercontent.com/3782057/61046699-101e5000-a3de-11e9-8903-30bf0fe95dde.png)

I'm not entirely sure it's Domoticz at fault here, maybe it's the plugins. An example of how they're getting the images is, if I'm not mistaken, [here](https://github.com/Xorfor/Domoticz-PiMonitor-Plugin/blob/131da4156efe991d7b0a87388f1f439da61437d9/plugin.py#L150).

Any help on how to go about fixing it would be appreciated.

**Comment by gizmocuz** [comment]
Thanks for reporting, fixed in upcoming beta version (10984+)
