### ISSUE TITLE
Nodes not recognized

### ISSUE THREAD

**Issue by Juanuil** [domoticz/domoticz#3532]
Hi There,

I am on v4.11005 and my nodes with a double function are not regonized.
So my lighting in the rooms are not working anymore and also my sensors for lux and temperature don't repord anymore.
The log is telling me that the nodes have a time out notification and also harrdware info for z-wave stays on not all nodes have been requested.
Help!!!!!

**Comment by petergebruers** [comment]
Theoretically that should not happen on 11005...

See https://github.com/domoticz/domoticz/issues/3530

Not sure what is going on because 11005 should not be affected.

What you can try is either run an older beta before 4.10988 or build Domoticz from source and use the latest OpenZWave version, detailed instructions are here:

https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source

**Comment by LouiS22** [comment]
+1 on this issue, lot of my nodes are 0x0000

**Comment by norrland1** [comment]
I just did that, Domoticz 11005 and OpenZWave: Version: 1.6-839-gf45e8ab4-dirty

It identifies most nodes but there are some that it can't identify, battery nodes, but some other battery nodes are identified. It does not update values on these nodes either. 

Removed OZW cache and retried with same result.

**Comment by petergebruers** [comment]
> It identifies most nodes but there are some that it can't identify, battery nodes, but some other battery nodes are identified.

> Removed OZW cache and retried with same result.

If you delete ozwcache* then all devices will be re-interviewed. This is necessary to get the correct information.

This means battery devices won't be identified until they **wake up** (automatically based on wake up interval, or when you perform the right kind of clicks on a button on the device. See device manual). Until that happens they will have no name and ID will be 0x0000.

**Comment by Juanuil** [comment]
how can I remove ozwcache?

**Comment by Juanuil** [comment]
or how can I run an older version of domoticz?

**Comment by petergebruers** [comment]
> or how can I run an older version of domoticz?

I am sorry, I am not a Domoticz developer, but a OpenZWave Contributor. "Github" is a tool for developers to communicate, maybe you get an answer to that question, faster, on the Domoticz forum.

That said, if you know a bit about linux you can build from source as I said in my previous post (and build any version of Domiticz or OpenZWave - but "latest" of both should work when I post this)

Detailed instructions are here:

https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source

> how can I remove ozwcache?

Before you begin, make a backup of Domoticz. Read this post till the end.

Stop Domoticz. In the Config folder you'll find a file named ozwcache_ and then some characters. Move that file to a another place, it might have information for debugging later. Or for reference.

Start Domoticz. That file will be rebuilt. It will take some time, especially for battery operated devices. Battery devices won't be identified until they wake up (automatically based on wake up interval, or when you perform the right kind of clicks on a button on the device. See device manual).

**Comment by Juanuil** [comment]
What a mess I will try a new build from source.
I will keep you informed

**Comment by Juanuil** [comment]
Great, now I even don't get Domoticz to start again :-( 
Verry disapointed

**Comment by norrland1** [comment]
Most of mine that where unknown 0x0000 has identified them selfs by now.

**Comment by gizmocuz** [comment]
@Juanuil , om what hardware are you running Domoticz ? 
If it is on a raspberry pi:

go to your folder where you installed domoticz and issue:
./updatebeta

This should get you quickly on the latest beta

You can also go back to the stable release with:
./updaterelease

If you are using Ubuntu or any other Debian based system, try to use the binary version that you can install with the sudo command (see our website/download section)

Else, completely whipe your build folder, and follow our wiki for a step-by-step compilation instruction:

https://www.domoticz.com/wiki/Raspberry_Pi_-_Build_Domoticz_from_source

**Comment by Juanuil** [comment]
Hi Gizmocuz,

 

I’m running on a raspberry PI.

I have made a install from scratch today and will try this evening.

Only no Domoticz directory is made only a dev-domoticz is this oke?

 

Greetz Jan

**Comment by Juanuil** [comment]
So I made a install from scratch.
Everything is made in dev-domoticz, no domoticz folder is made.
Starting up didn't help.
So installed "The easy way" after that did ./updatebeta.
So now I'm getting domoticz
Then I restored the database.
I get my floorplans with all the nodes.
When I click a node I get "problem with sending command to node"
After that domoticz crashes!!!! and I  have tot sudo reboot.
I am completely lost and my wife is desparate because no lights respond and no curtains close.
Desparate need help!!!

Update 22:00 H
After another install everything is functioning again.

**Comment by gizmocuz** [comment]
@Juanuil , yes it's not the best idea to do this at night....
When you install, and i guess it's the binary install, you are installing the stable.
So i think you are on the stable now. Please stay there for now

If Domoticz crashes, there is no need for "sudo reboot"
If you want to restart Domoticz, just issue "sudo service domoticz restart"
(or stop to stop and start to start)

**Comment by Juanuil** [comment]
Hi Gizmocuz,

Glad that evrything is working again.
Still no idea why no directory Domoticz is made after a install from scratch, only a directory dev-domoticz.
After the quick install I did a ./updatebeta so I am on V4.11005 now.

**Comment by petergebruers** [comment]
That is good news. Thank you for reporting back. Be warned that OZW and Domoticz "Development" will still get updates and sometimes either ozwcache* might get cleared automatically or we ask you to clear it and then it takes time for all your devices to come back, especially battery devices (unless you click their buttons to wake them up).

What I don't understand, but don't worry about that I am only mentioning it "for the record" is that you started this issue by saying "I am on v4.11005 and my nodes with a double function are not regonized." which is a symptom of an earlier version. You end this issue by saying "After the quick install I did a ./updatebeta so I am on V4.11005 now." and it is working. I wonder what caused the difference. Maybe the extra steps did change something.

**Comment by gizmocuz** [comment]
@Juanuil , the dev-domoticz folder is made when you followed the wiki about how to compile Domoticz yourself.
It should (hopefully) not be created when you use the 'sudo' command to install Domoticz, then a folder 'Domoticz' is created in your root-folder

**Comment by Juanuil** [comment]
Oké Thank you all for the support!
