### ISSUE TITLE
No info on controlpanal OZW

### ISSUE THREAD

**Issue by Juanuil** [domoticz/domoticz#3536]
Hi hard workers,

Implementing ozw 1.6 gives you probally a lot of headache.
Let me tell you that you all are doing a good job.
I allready see a lot of improvement on response times for instance.
The reason I post issues is more to help you and give you information then to complain.

At this moment I am on v.4.11019 and since then I have no information on the control panel of OZW.
No nodes are being displayed. 

greetz
Jan

**Comment by gizmocuz** [comment]
@Juanuil , thanks ;) We are almost there i believe ....
Could you delete the browser cache + appcache ? (two different things)
That should do the trick... if not try another browser, or you browser in private mode

**Comment by Juanuil** [comment]
Hi Gizmocuz,

deleted cache and appcache yesterday allready.
Tried private window no response
use Firefox and IE. Today tried edge and here I have info.

**Comment by gizmocuz** [comment]
And in Chrome ? I still think it is a appcache issue

**Comment by Juanuil** [comment]
In Chrome I get info but name and location are empty
Firefox after diverse cache deletions nothing

**Comment by gizmocuz** [comment]
Name and location should not be filled in, only use the control panel for checking values/configuration, do the rest in Domoticz
I am closing the issue as i know 100% there are no issued with Chrome/Firefox and Edge as i test against them myself and use them during development.
Safari i ca not test
I am 99% if you have any issues that it is a cache issue. If you keep having issues, please use the forum
