### ISSUE TITLE
Dummy delivery kwh sums up wrongly

### ISSUE THREAD

**Issue by tonbor** [domoticz/domoticz#3537]
![Image1](https://user-images.githubusercontent.com/42464290/61438226-40ff0780-a93f-11e9-953d-854b9b949c68.jpg)
![Image2](https://user-images.githubusercontent.com/42464290/61438227-40ff0780-a93f-11e9-976b-d737d225bd43.jpg)
![Image3](https://user-images.githubusercontent.com/42464290/61438228-40ff0780-a93f-11e9-86a0-1ceb2add05fe.jpg)
The dummy reads well from this script. 
https://www.domoticz.com/forum/viewtopic.php?f=4&t=27656&p=218139&hilit=growatt#p218139
However, the totals are wrong. No hourly log in the day. After the day they are filled in. The total of today is yesterdays. The jpeg of the log is mixed up with delivery and use.
A picture tells a thousand words.

**Comment by gizmocuz** [comment]
It has to be a continues counter... is it updated according our Wiki (JSON)

**Comment by sincze** [comment]
@gizmocuz: this is a counter updated by 2 fields of a solar inverter: 
current_generation : todaytotal

Todaytotal starts at 0 the next day.
That is why the counter resets to 0 ;-) nothing continous about that.

Option 1: Please ;-) A new counter that can handle this ;-)
Option 2: (me) Adjust the code to read the inverter with current_generation : total_generation_since_install.
That would be continous. And ofcourse if that value is available in the specific webportal.

**Comment by gizmocuz** [comment]
@sincze , ok problem found. This has been reported before.
I think you have to do option 2, or use somehow a counter incremental type ?
