### ISSUE TITLE
Uploading icons: XML Parsing Error: not well-formed

### ISSUE THREAD

**Issue by giejay** [domoticz/domoticz#3539]
Im on the latest beta, and Im unable to upload any icons. I tried my own and the one from gizmocuz: https://drive.google.com/drive/folders/0B-ZLFoCiqzMRfnZXV3RiTU1pdUEyWVF2TEpNQmxBN2xhUWo5MjhiamY0cVEwanFUM0Z0UVE

But nothing seems to work, error in console:

XML Parsing Error: not well-formed
Location: http://192.168.2.17:8080/uploadcustomicon
Line Number 1, Column 1:

Domoticz version: V4.11019

**Comment by gizmocuz** [comment]
I have no issue with the tablet zip file.
Did you try clearing the browser cache + appcache (two different things)
Did you try with the Chrome browser?

**Comment by giejay** [comment]
I tried three different browsers, cleared cache, doesn't seem to make any difference.

**Comment by gizmocuz** [comment]
Could you post this on the forum and see if anyone else has this issue ?
