### ISSUE TITLE
Minor Label Change request (French language)

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#3540]
Just a very small improvement on a label related to Blinds for French language.

The Blind status for Closed in Domoticz is **Fermé**, which is correct.
However the Blind status for Opened in Domoticz is **Ouvrir**, it should be **Ouvert** (it's a status, not an action).

![image](https://user-images.githubusercontent.com/28684355/61581170-12d61f00-ab1b-11e9-99ac-35dbfb7445a0.png)

**Comment by gizmocuz** [comment]
When you hover the mouse over the open/close icons, is the tooltip correct? Because that is an action
I am not sure if we can currently support two Open translations

**Comment by Olivier6767** [comment]
There are only tooltips on the Close an Open buttons (the blind images). But these tooltips are different than the work on the top right.
Attached is an example of the tooltip when hovering over the Close button. It says **Fermer les stores** (Close the blinds). It's an action word and it is correct. 
My understanding is that the word on the top right is the Status.


![image](https://user-images.githubusercontent.com/28684355/61581421-3b134d00-ab1e-11e9-8e4d-8fb815c74c37.png)

**Comment by gizmocuz** [comment]
@Olivier6767 , okey that sounds good.... 
Then this change has to be made on our Transifex project here:

https://www.transifex.com/domoticz/domoticz/dashboard/
