### ISSUE TITLE
Custom Icon Yeelight Colour Bulb not showing

### ISSUE THREAD

**Issue by sincze** [domoticz/domoticz#3541]
### Issue Guidelines
Domoticz V4.10988

I have 2 types of yeelight. The Mono/WW and RGBW

For the Mono I can change the custom Icon.... for the Colour I can change it in the device properties but it does not show the icon on the dashboard as shown in the image.
![image](https://user-images.githubusercontent.com/5776333/61657005-38e9f380-acc2-11e9-804d-3ba7da602500.png)

**Comment by gizmocuz** [comment]
Yes this is the RGB(W/WW) color picker icon

**Comment by Harald777** [comment]
Would love to see that it is possible to change the RGB Icon to a custom icon, currently not possible.

**Comment by waltervl** [comment]
Solved with pr
