### ISSUE TITLE
Domoticz.Connection does not respond well to Connection: close

### ISSUE THREAD

**Issue by sincze** [domoticz/domoticz#3542]
Domoticz V4.11020

I started to develop a domoticz plugin using HTTP.py under /plugins/examples.
It needs to send a GET request and do Basic auth on port 80.

I use Domoticz.Connection for the connection
It authorizes with the target but only runs 1 time (no heartbeat after that). Domoticz needs to be restarted.
[logfiles](http://www.domoticz.com/forum/viewtopic.php?f=65&t=28766&p=219951#p219879)
If I don't add the basic auth ... the plugin 'works', tries to connect to the webserver,.. however is unable to login.
![image](https://user-images.githubusercontent.com/5776333/61728755-1b766180-ad76-11e9-900d-dfe63cf44a56.png)

According to fellow Forum member Dnpwwo the following could be the case:

_Despite your request to keep the connection open (using connection: keep-alive) the inverter's web server has informed you that it will terminate the connection once it has transmitted the response (using connection: close). This is valid under HTTP 1.1 and is the only circumstance where the web server can respond without informing the client how long the response is (for any pedants reading this, chunked encoding has a length prefixed on every chunk rather than via the content-length header).

I've never seen a web server actually do this but the code is designed to send any buffered data to the plugin when the connection closes so this should work (although not tested for the HTTP protocol).

![image](https://user-images.githubusercontent.com/5776333/61728523-ad319f00-ad75-11e9-8c32-6101bb52747f.png)

If this is a bug I hope it can be solved to complete the Plugin.

**Comment by gizmocuz** [comment]
It looks your plugin is stuck on something... that is why there is no response anymore.
This is not a Domoticz issue (i am almost certain)
Best to start with a plugin that does a 'get' on a known webpage on the internet, and print a logline
Just something simple, then continue from their.

Please use the forum as there are many more users that can help you there

**Comment by sincze** [comment]
@gizmocuz ok. tnx, Just to clarify
I started with working plugin... HTTP.py 

Changed working:

`<param field="Address" label="IP Address" width="200px" required="true" default="192.168.1.100"/>`

to...
```
<param field="Address" label="IP Address" width="200px" required="true" default="192.168.1.100"/>
<param field="Username" label="Inverter Username" width="200px" required="true" default="admin"/>
<param field="Password" label="Inverter Password" width="200px" required="true" password="true"/>

```

To enable basic authentication. And then it breaks.
If I remove the 2 lines the issue is over, no other changes in the plugin.

Fellow forum member @Dnpwwo had a closer look on it and found 3 problems with the way that the plugin http protocol is handling this. So I guess you are right this is a plugin thing :-)

- The web server sends a response with no length but sends it in 2 parts: the response header followed by the payload. Because the header has no length and there is no payload Domoticz incorrectly decides that the http response is complete.
- Because of the above, the protocol then treats the payload as a new response but then fails to parse it because it is invalid http.
- The generic flush on disconnect (which would be called if the 2 issues above are resolved) needs to be overridden for http

**Comment by gizmocuz** [comment]
You could try to see if working with dzVents has a better integration

**Comment by sincze** [comment]
Ok, did not know plugins did work with dzVents as well.
For myself I build it in PHP, has been running for over a year, tried to build a nice plugin for the community. ;)

**Comment by gizmocuz** [comment]
@sincze , dzVents is a powerfull scripting tool. It depends on what you want to create i suppose.
If it is just getting data from a remote web site and pushing this into domoticz, dzVents is also capable of doing this, and it won't crash the syste, if there is a python error
