### ISSUE TITLE
Philio PSM02-1 - CommandClass: Door/Window device not added

### ISSUE THREAD

**Issue by a-b-s** [domoticz/domoticz#3544]
Moving from Domoticz Stable V4.10717 using OpenZWave version 1.4-3335-g74e05982-dirty to Domoticz Beta V4.10717 until V4.11027 using OpenZWave version 1.6-764-g210c300b-dirty to 1.6-848-g39e050fa-dirty respectively, partly breaks the Philio PSM02-1 multisensor. Only **the Door/Window device is not added**. Other sensor devices e.g. motion, lux, temp, are working correctly.

Error in the domoticz log is the following:

> 
> 2019-07-14 10:53:31.550  Status: Domoticz V4.11005 (c)2012-2019 GizMoCuz
> 2019-07-14 10:53:31.550  Status: Build Hash: 65dd3fca2, Date: 2019-07-14 09:30:04
> 2019-07-14 10:53:34.248  Status: OpenZWave: Starting...
> 2019-07-14 10:53:34.248  Status: OpenZWave: Version: 1.6-841-g85d47e56-dirty
> 2019-07-14 10:53:37.314  Status: OpenZWave: Received unhandled notification type (30) from HomeID: 0, NodeID: 0 (0x00)
> 2019-07-14 10:53:37.314  Status: OpenZWave: User Alert - Manufacturer_specific.xml out of Date
> 2019-07-14 10:53:37.314  Status: OpenZWave: ManufacturerSpecificDB Ready
> 2019-07-14 10:53:37.609  Status: OpenZWave: Driver Ready

Include Node

> 2019-07-14 10:54:18.974  Status: New sensors allowed for 5 minutes...
> 2019-07-14 10:54:18.974  Status: OpenZWave: Node Include command initiated...
> 2019-07-14 10:54:49.883  Status: OpenZWave: Node Removed. HomeID: 4279337761, NodeID: 20 (0x14)
> 2019-07-14 10:54:49.883  OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: SENSOR BINARY, Label: Sensor, Instance: 1, Index: 0
> 2019-07-14 10:54:49.883  OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: BATTERY, Label: Battery Level, Instance: 1, Index: 0
> **2019-07-14 10:54:50.776  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-14 10:54:50.776  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-14 10:54:50.778  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-14 10:54:50.778  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-14 10:54:50.778  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)**
> 2019-07-14 10:54:51.035  OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Air Temperature, Instance: 1, Index: 1
> 2019-07-14 10:54:51.077  OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Illuminance, Instance: 1, Index: 3

Include Node Secure

> 2019-07-14 10:55:05.697  Status: New sensors allowed for 5 minutes...
> 2019-07-14 10:55:05.697  Status: OpenZWave: Node Include command initiated...
> 2019-07-14 10:55:10.845  Status: OpenZWave: Node Removed. HomeID: 4279337761, NodeID: 20 (0x14)
> 2019-07-14 10:55:10.845  OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: SENSOR BINARY, Label: Sensor, Instance: 1, Index: 0
> 2019-07-14 10:55:10.845  OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: BATTERY, Label: Battery Level, Instance: 1, Index: 0
> **2019-07-14 10:55:11.737  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-14 10:55:11.737  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-14 10:55:11.738  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-14 10:55:11.738  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-14 10:55:11.738  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)**
> 2019-07-14 10:55:11.957  OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Air Temperature, Instance: 1, Index: 1
> 2019-07-14 10:55:11.996  OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Illuminance, Instance: 1, Index: 3

I have a full OZW log file available if needed. 

Kind regards, Cooper

**Comment by gizmocuz** [comment]
@a-b-s , thanks for testing !
I have made some adjustments to the Domoticz code:

- implemented notification type (30), which displays a string from the controller
- added Debug lines before calling "GetValueLabel"

This version does not solve your issue (yet)....

Is it possible you could test with this version and copy/paste the new log lines.
I hope from these new log lines to figure out what/where the problem lies (Invalid ValueID passed to GetValueLabel), unless it is inside the OZW library.

I hope to test with a PSM02-1 sensor this weekend

The new beta version is 11029

**Comment by a-b-s** [comment]
@gizmocuz, thank you for your reply and quick actions. I updated domoticz to version 11029 and got a log output regarding the Philio PSM02-1
[domoticzEDIT.txt](https://github.com/domoticz/domoticz/files/3430533/domoticzEDIT.txt)

> 2019-07-25 09:57:02.080  Status: Domoticz V4.11029 (c)2012-2019 GizMoCuz
> 2019-07-25 09:57:02.081  Status: Build Hash: cdc33c102, Date: 2019-07-25 08:29:03
> 2019-07-25 09:57:04.667  Status: OpenZWave: Starting...
> 2019-07-25 09:57:04.667  Status: OpenZWave: Version: 1.6-848-g39e050fa-dirty
> 2019-07-25 09:57:06.311  Status: OpenZWave: ManufacturerSpecificDB Ready
> 2019-07-25 09:57:06.620  Status: OpenZWave: Driver Ready

Include node:

> 2019-07-25 10:01:48.743  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:48.743  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: BATTERY, Label: Battery Level, Instance: 1, Index: 0, Id: 0x14600011
> 2019-07-25 10:01:48.743  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:48.743  OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: BATTERY, Label: Battery Level, Instance: 1, Index: 0
> 2019-07-25 10:01:48.743  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:48.743  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: VERSION, Label: Library Version, Instance: 1, Index: 0, Id: 0x14E18017
> 2019-07-25 10:01:48.743  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:48.743  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:48.743  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: VERSION, Label: Protocol Version, Instance: 1, Index: 1, Id: 0x1000014E18017
> 2019-07-25 10:01:48.743  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:48.743  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:48.743  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: VERSION, Label: Application Version, Instance: 1, Index: 2, Id: 0x2000014E18017
> 2019-07-25 10:01:48.743  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:48.743  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:48.743  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: SENSOR BINARY, Label: Sensor, Instance: 1, Index: 0, Id: 0x144C0010
> 2019-07-25 10:01:48.743  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:48.743  OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: SENSOR BINARY, Label: Sensor, Instance: 1, Index: 0
> 2019-07-25 10:01:48.743  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:48.743  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: WAKE UP, Label: Wake-up Interval, Instance: 1, Index: 0, Id: 0x14E10013
> 2019-07-25 10:01:48.743  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.617  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.617  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: WAKE UP, Label: Wake-up Interval, Instance: 1, Index: 0, Id: 0x14E10013
> 2019-07-25 10:01:49.617  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.617  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.617  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: MANUFACTURER SPECIFIC, Label: Loaded Config Revision, Instance: 1, Index: 0, Id: 0x14DC8013
> 2019-07-25 10:01:49.617  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.617  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.617  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: MANUFACTURER SPECIFIC, Label: Config File Revision, Instance: 1, Index: 1, Id: 0x1000014DC8013
> 2019-07-25 10:01:49.617  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.617  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.617  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: MANUFACTURER SPECIFIC, Label: Latest Available Config File Revision, Instance: 1, Index: 2, Id: 0x2000014DC8013
> 2019-07-25 10:01:49.617  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.617  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.617  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: MANUFACTURER SPECIFIC, Label: Device ID, Instance: 1, Index: 3, Id: 0x3000014DC8017
> 2019-07-25 10:01:49.617  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.617  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.617  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: MANUFACTURER SPECIFIC, Label: Serial Number, Instance: 1, Index: 4, Id: 0x4000014DC8017
> 2019-07-25 10:01:49.617  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.664  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.664  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: MANUFACTURER SPECIFIC, Label: Config File Revision, Instance: 1, Index: 1, Id: 0x1000014DC8013
> 2019-07-25 10:01:49.664  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.664  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.664  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: MANUFACTURER SPECIFIC, Label: Loaded Config Revision, Instance: 1, Index: 0, Id: 0x14DC8013
> 2019-07-25 10:01:49.664  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.664  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.664  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: CONFIGURATION, Label: Basic Set Level, Instance: 1, Index: 2, Id: 0x20000149C0011
> 2019-07-25 10:01:49.664  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.664  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.664  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: CONFIGURATION, Label: PIR Sensitivity, Instance: 1, Index: 3, Id: 0x30000149C0011
> 2019-07-25 10:01:49.664  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.664  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.664  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: CONFIGURATION, Label: Light threshold, Instance: 1, Index: 4, Id: 0x40000149C0011
> 2019-07-25 10:01:49.664  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.664  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.664  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: CONFIGURATION, Label: Operation Mode, Instance: 1, Index: 5, Id: 0x50000149C0011
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: CONFIGURATION, Label: Multi-Sensor Function Switch, Instance: 1, Index: 6, Id: 0x60000149C0011
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: CONFIGURATION, Label: Customer Function, Instance: 1, Index: 7, Id: 0x70000149C0011
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: CONFIGURATION, Label: PIR re-detect interval time, Instance: 1, Index: 8, Id: 0x80000149C0011
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: CONFIGURATION, Label: Turn Off Light Time, Instance: 1, Index: 9, Id: 0x90000149C0011
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: CONFIGURATION, Label: Auto Report Battery Time, Instance: 1, Index: 10, Id: 0xA0000149C0011
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: CONFIGURATION, Label: Auto Report Illumination Time, Instance: 1, Index: 12, Id: 0xC0000149C0011
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: CONFIGURATION, Label: Auto Report Temperature time, Instance: 1, Index: 13, Id: 0xD0000149C0011
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-25 10:01:49.665  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.665  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-25 10:01:49.666  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.666  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-25 10:01:49.666  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.666  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-25 10:01:49.666  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.666  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1512)
> 2019-07-25 10:01:49.812  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.812  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: WAKE UP, Label: Minimum Wake-up Interval, Instance: 1, Index: 1, Id: 0x1000014E10013
> 2019-07-25 10:01:49.812  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.812  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.812  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: WAKE UP, Label: Maximum Wake-up Interval, Instance: 1, Index: 2, Id: 0x2000014E10013
> 2019-07-25 10:01:49.812  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.812  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.812  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: WAKE UP, Label: Default Wake-up Interval, Instance: 1, Index: 3, Id: 0x3000014E10013
> 2019-07-25 10:01:49.812  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.812  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.812  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: WAKE UP, Label: Wake-up Interval Step, Instance: 1, Index: 4, Id: 0x4000014E10013
> 2019-07-25 10:01:49.812  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.889  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.889  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Air Temperature, Instance: 1, Index: 1, Id: 0x10000144C4012
> 2019-07-25 10:01:49.889  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.889  OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Air Temperature, Instance: 1, Index: 1
> 2019-07-25 10:01:49.889  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.889  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Air Temperature Units, Instance: 1, Index: 256, Id: 0x100000014CC4014
> 2019-07-25 10:01:49.889  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.927  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.927  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Illuminance, Instance: 1, Index: 3, Id: 0x30000144C4012
> 2019-07-25 10:01:49.927  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.927  OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Illuminance, Instance: 1, Index: 3
> 2019-07-25 10:01:49.927  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.927  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Illuminance Units, Instance: 1, Index: 258, Id: 0x102000014CC4014
> 2019-07-25 10:01:49.927  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.990  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:49.990  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: MANUFACTURER SPECIFIC, Label: Device ID, Instance: 1, Index: 3, Id: 0x3000014DC8017
> 2019-07-25 10:01:49.990  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.050  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.050  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: MANUFACTURER SPECIFIC, Label: Serial Number, Instance: 1, Index: 4, Id: 0x4000014DC8017
> 2019-07-25 10:01:50.050  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.094  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.094  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: WAKE UP, Label: Minimum Wake-up Interval, Instance: 1, Index: 1, Id: 0x1000014E10013
> 2019-07-25 10:01:50.094  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.094  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.094  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: WAKE UP, Label: Maximum Wake-up Interval, Instance: 1, Index: 2, Id: 0x2000014E10013
> 2019-07-25 10:01:50.094  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.094  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.094  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: WAKE UP, Label: Default Wake-up Interval, Instance: 1, Index: 3, Id: 0x3000014E10013
> 2019-07-25 10:01:50.094  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.094  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.094  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: WAKE UP, Label: Wake-up Interval Step, Instance: 1, Index: 4, Id: 0x4000014E10013
> 2019-07-25 10:01:50.094  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.175  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.175  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: VERSION, Label: Library Version, Instance: 1, Index: 0, Id: 0x14E18017
> 2019-07-25 10:01:50.175  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.175  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.175  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: VERSION, Label: Protocol Version, Instance: 1, Index: 1, Id: 0x1000014E18017
> 2019-07-25 10:01:50.175  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.175  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.175  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: VERSION, Label: Application Version, Instance: 1, Index: 2, Id: 0x2000014E18017
> 2019-07-25 10:01:50.175  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.329  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.329  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: WAKE UP, Label: Wake-up Interval, Instance: 1, Index: 0, Id: 0x14E10013
> 2019-07-25 10:01:50.329  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.373  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.373  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Air Temperature, Instance: 1, Index: 1, Id: 0x10000144C4012
> 2019-07-25 10:01:50.373  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.415  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.415  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Illuminance, Instance: 1, Index: 3, Id: 0x30000144C4012
> 2019-07-25 10:01:50.415  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.454  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:50.454  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: BATTERY, Label: Battery Level, Instance: 1, Index: 0, Id: 0x14600011
> 2019-07-25 10:01:50.454  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:51.285  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 10:01:51.285  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: MANUFACTURER SPECIFIC, Label: Latest Available Config File Revision, Instance: 1, Index: 2, Id: 0x2000014DC8013
> 2019-07-25 10:01:51.285  Status: OpenZWave: ------------------------------------------------

**Comment by gizmocuz** [comment]
@a-b-s , sorry i made a mistake to call GetValueLabel inside the debug function. I will make a new beta, on e moment

**Comment by gizmocuz** [comment]
Could you try beta 11030 ? Beta for debian x86/64 is available, windows is available in 10 minutes

**Comment by a-b-s** [comment]
@gizmocuz again thank you for your efforts. Here is the log.

> 2019-07-25 11:21:35.812  Status: Domoticz V4.11030 (c)2012-2019 GizMoCuz
> 2019-07-25 11:21:35.813  Status: Build Hash: ce6da7e73, Date: 2019-07-25 10:43:32
> 2019-07-25 11:21:38.363  Status: OpenZWave: Starting...
> 2019-07-25 11:21:38.363  Status: OpenZWave: Version: 1.6-848-g39e050fa-dirty
> 2019-07-25 11:21:40.046  Status: OpenZWave: ManufacturerSpecificDB Ready
> 2019-07-25 11:21:40.340  Status: OpenZWave: Driver Ready

Include node:

> 2019-07-25 11:22:24.800  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 11:22:24.800  Status: OpenZWave: Debug Value: Node: 20 (0x14), CommandClass: CONFIGURATION, Instance: 1, Index: 13, Id: 0xD0000149C0011
> 2019-07-25 11:22:24.800  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 11:22:24.800  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 11:22:24.800  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueUnits, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1568)
> 2019-07-25 11:22:24.800  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 11:22:24.800  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueUnits, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1568)
> 2019-07-25 11:22:24.801  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 11:22:24.801  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueUnits, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1568)
> 2019-07-25 11:22:24.801  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 11:22:24.801  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueUnits, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1568)
> 2019-07-25 11:22:24.801  Status: OpenZWave: ------------------------------------------------
> 2019-07-25 11:22:24.801  Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueUnits, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1568)
> 2019-07-25 11:22:24.921  Status: OpenZWave: ------------------------------------------------

**Comment by gizmocuz** [comment]
@a-b-s, thank you for the Log. It seems now it is failing on "Invalid ValueID passed to GetValueUnits,".
I made a new beta, and i also added the source code line where it was called.

Is it possible to test version 11031 ?

You will get the "Invalid ValueID passed to GetValueLabel", but then i know from the log what command class / value type, is causing this issue

Thanks in advance !

**Comment by gizmocuz** [comment]
@a-b-s , i think we found the reason for the problem. In the latest build (11038) it should work

**Comment by a-b-s** [comment]
@gizmocuz sorry for the late reply. This morning I updated to 11038 and I can confirm that not only the Door/Window sensor is added to Domoticz but also the Tamper Sensor. Great job everyone! 

> CommandClass: SENSOR BINARY, Label: Door/Window Sensor, Instance: 1, Index: 1
> CommandClass: SENSOR BINARY, Label: Tamper Sensor, Instance: 1, Index: 2

However, on my end these devices do not change state, e.g. opening the door or taking the sensor of the wall, does not change the state of the sensor in Domoticz. Also there are no log entries for these sensors in Domoticz. I will have a look at the OZW log later to provide you with more related info/errors. Thanks again for all your time and efforts

**Comment by gizmocuz** [comment]
@a-b-s, you have to set the parameters correctly. (parameter 5 = 8, and 6=4, 7=4 or 22)

Also note that the node has 2 tamper switches, inside and on the back, try to operate both at the same time

**Comment by a-b-s** [comment]
@gizmocuz PERFECT! updating to **Domoticz Beta version 4.11038 with OpenZ-Wave version 1.6-848-g39e050fa-dirty** AND **setting the parameters to the suggested values** e.g.: 
- parameter 5 = 8
- parameter 6 = 4
- parameter 7 = 22

restores full functionality of the Philio PSM02-1!
