### ISSUE TITLE
DeviceType "Blinds Percentage Inverted" on Dummy (virtual) hardware send invalid MQTT message

### ISSUE THREAD

**Issue by tszalajITDev** [domoticz/domoticz#3545]
On Domoticz v 4.10717 I've defined a shutter of type Blinds Percentage Inverted on Dummy hardware and I have configured MQTT gateway to read Domoticz devices state changes.
Virtual shutter sends invalid commands when it's triggered via Open Blinds / Close Blinds buttons.
Scenario:
1. I set shutter via slider to 80 percent. I get MQTT message for state=true (OK) and level=80 (OK)
2. I set shutter via Open Blinds button. I get MQTT message for state=true (OK) and level=80 (not OK, expected 100)
3. I set shutter via Close Blinds button. I get MQTT message for state=false (OK) and level=100 (not OK, expected 0).
The problem with these scenarios is that it's impossible to determine whether user intention was to open blinds fully or partially with these two messages. State attribute is always true for levels > 0, and level attribute is always invalid when button is clicked, as it carries last value and not intended value.

**Comment by gizmocuz** [comment]
@tszalaj , don't you get a 'command' with the MQTT message, Like Set Level, or ON/OFF ? On means 100%, off means 0, set level can be anything

**Comment by tszalajITDev** [comment]
For these three actions messages are accordingly:
1. Slider to 44%:
{
   "Battery" : 255,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Light/Switch",
   "id" : "000140A1",
   "idx" : 81,
   "name" : "Test shutter",
   "nvalue" : 2,
   "stype" : "Switch",
   "svalue1" : "44",
   "switchType" : "Blinds Percentage Inverted",
   "unit" : 1
}
2. Open Blinds - svalue1 is still 44% although in UI it's 100%
{
   "Battery" : 255,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Light/Switch",
   "id" : "000140A1",
   "idx" : 81,
   "name" : "Test shutter",
   "nvalue" : 1,
   "stype" : "Switch",
   "svalue1" : "44",
   "switchType" : "Blinds Percentage Inverted",
   "unit" : 1
}
3. Close Blinds - svalue1 still 44% although in previous step was Open Blinds and now UI shows 0%
{
   "Battery" : 255,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Light/Switch",
   "id" : "000140A1",
   "idx" : 81,
   "name" : "Test shutter",
   "nvalue" : 0,
   "stype" : "Switch",
   "svalue1" : "44",
   "switchType" : "Blinds Percentage Inverted",
   "unit" : 1
}
So I wasn't right that intention is not distinguishable - I was just looking at processed data where nvalue=2 was interpreted as state attribute of type boolean equal TRUE.
So case can be closed, although correcting svalue1 to 100 for nvalue=1 and 0 for nvalue=0 would be much appreciated ;)

**Comment by gizmocuz** [comment]
I agree , but 'raw' data is being send. You could extend the MQTT.cpp class, somewhere arround line 656...
