### ISSUE TITLE
MQTT not reconnection after network hickup

### ISSUE THREAD

**Issue by gvansanden** [domoticz/domoticz#3549]
Version: 4.10717
Platform: Raspbian Stretch
Plugin/Hardware: Raspberry Pi
Description:
When there's a network hickup, Domoticz will not reconnect correctly to our MQTT server (running on another server).
It will keep logging messages like this:

2019-06-21 08:04:32.384 Error: MQTT: disconnected, restarting (rc=7)
2019-06-21 08:04:50.856 Status: Incoming connection from: 192.168.1.2
2019-06-21 08:05:01.208 Status: MQTT: Connecting to 192.168.1.5:1883
2019-06-21 08:05:01.334 Status: MQTT: re-connected to: 192.168.1.5:1883
2019-06-21 08:05:01.435 Status: MQTT: Subscribed
2019-06-21 08:05:10.625 Error: MQTT: disconnected, restarting (rc=7)
2019-06-21 08:05:39.552 Status: MQTT: Connecting to 192.168.1.5:1883
2019-06-21 08:05:39.678 Status: MQTT: re-connected to: 192.168.1.5:1883
2019-06-21 08:05:39.778 Status: MQTT: Subscribed
2019-06-21 08:05:49.138 Error: MQTT: disconnected, restarting (rc=7)
2019-06-21 08:06:18.064 Status: MQTT: Connecting to 192.168.1.5:1883
2019-06-21 08:06:18.190 Status: MQTT: re-connected to: 192.168.1.5:1883
2019-06-21 08:06:18.290 Status: MQTT: Subscribed
2019-06-21 08:06:28.198 Error: MQTT: disconnected, restarting (rc=7)
2019-06-21 08:06:57.123 Status: MQTT: Connecting to 192.168.1.5:1883
2019-06-21 08:06:57.251 Status: MQTT: re-connected to: 192.168.1.5:1883
2019-06-21 08:06:57.351 Status: MQTT: Subscribed

A restart of domoticz gets it back online, but we depend on MQTT for core functions.

**Comment by gizmocuz** [comment]
It seems Domoticz is receiving a on_disconnect after it is subscribed
We call **mosquittopp::reconnect** to reconnect, seems this is not working correctly

Are you able to code ? You could try to modify the function void **MQTT::Do_Work()**
Before calling reconnect() add this line:

m_bDoReconnect = false;

It looks like a double connect here, reconnect and underneath 'ConnectIntEx' is called

**Comment by gvansanden** [comment]
I could do that, but the issue only occurs every once in a while...

In the mosquitto logs, I do see:
1562600717: Client mosq_x6TC;CJf1tiNI6C=_P already connected, closing old connection.
1562600717: Client mosq_x6TC;CJf1tiNI6C=_P disconnected.

It looks like the old connection is still there and Domoticz is reconnecting faster than they expire, so every time it fails.

**Comment by gizmocuz** [comment]
That could also be the cause..... but i see 2 places in Do_Work that '(re)connect'
I think the whole logic in that function needs to be rewritten...
If 'firstime' then connect, else check if connection is still OK, if not, reconnect
At the end of the function also call disconnect

**Comment by gvansanden** [comment]
Yes, that seems exactly the issue we're having.  The MQTT server is in another location and every time the network bails out a couple of minutes (once every few weeks, sometimes months), the connection dies

**Comment by gvansanden** [comment]
You mean here:

						if (!m_bDoReconnect)
						{
							reconnect();

That should already be false

**Comment by gvansanden** [comment]
@gizmocuz any chance that there will be a release with this patched relatively soon?

**Comment by gizmocuz** [comment]
Could you test this and make a pull request?

**Comment by gvansanden** [comment]
@gizmocuz I haven't done C/C++ yet, but what should I modify?
```
void MQTT::Do_Work()
{
	bool bFirstTime=true;
	int msec_counter = 0;
	int sec_counter = 0;

	while (!IsStopRequested(100))
	{
		if (!bFirstTime)
		{
			int rc = loop();
			if (rc) {
				if (rc != MOSQ_ERR_NO_CONN)
				{
					if (!IsStopRequested(0))
					{
						if (!m_bDoReconnect)
						{
							reconnect();
						}
					}
				}
			}
		}

		msec_counter++;
		if (msec_counter == 10)
		{
			msec_counter = 0;

			sec_counter++;

			if (sec_counter % 12 == 0) {
				m_LastHeartbeat=mytime(NULL);
			}

			if (bFirstTime)
			{
				bFirstTime = false;
				ConnectInt();
			}
			else
			{
				if (sec_counter % 30 == 0)
				{
					if (m_bDoReconnect)
						ConnectIntEx();
				}
				if (isConnected() && sec_counter % 10 == 0)
				{
					SendHeartbeat();
				}
			}
		}
	}
	if (m_sDeviceReceivedConnection.connected())
		m_sDeviceReceivedConnection.disconnect();
	if (m_sSwitchSceneConnection.connected())
		m_sSwitchSceneConnection.disconnect();

	_log.Log(LOG_STATUS,"MQTT: Worker stopped...");
}

```

Changing:
```
if (!m_bDoReconnect)
					{
						reconnect();
```

to 

```
m_bDoReconnect = false;
reconnect();

```
But the if clause only fires if it is false already if I read it correct?

**Comment by gvansanden** [comment]
@gizmocuz I'm having a hard time figuring out how this works... (not having C experience).

But should this not be removed:
```
						if (!m_bDoReconnect)
						{
							reconnect();
						}
```

Or am I wrong there?

**Comment by gvansanden** [comment]
Hi @gizmocuz, we keep having issues with this.  Could you help me with which change I have to make because I know a bit of Python, but new to C....  I can test it and make a pull request if it works.

**Comment by gvansanden** [comment]
@gizmocuz 

I'm half guessing but what if we comment the reconnect:
`void MQTT::Do_Work()
{
	bool bFirstTime=true;
	int msec_counter = 0;
	int sec_counter = 0;

	while (!IsStopRequested(100))
	{
		if (!bFirstTime)
		{
			int rc = loop();
			// if (rc) {
			// 	if (rc != MOSQ_ERR_NO_CONN)
			// 	{
			// 		if (!IsStopRequested(0))
			// 		{
			// 			if (!m_bDoReconnect)
			// 			{
			// 				reconnect();
			// 			}
			// 		}
			// 	}
			// }
		}`

And put a disconnect at the end of the function as you suggested earlier?

**Comment by gizmocuz** [comment]
@gvansanden , best way is not to guess, but to test this...

I just tested the following:

- On one machine installed MQTT
- On my development machine I run Domoticz with MQTT , connecting to the other machine
- this was working
- then I disabled the MQTT service on the other machine, of course this caused a disconnect
- after a while I enable the MQTT service again, and it connects

2019-09-11 07:36:05.914  Status: MQTT: Connecting to 192.168.36.123:8883
2019-09-11 07:36:05.942  Status: MQTT: enabled TLS mode
2019-09-11 07:36:06.396  Status: MQTT: connected to: 192.168.36.123:8883
2019-09-11 07:36:06.614  Status: MQTT: Subscribed
2019-09-11 07:41:13.566  Error: MQTT: disconnected, restarting (rc=7)
2019-09-11 07:41:13.999  Status: MQTT: Connecting to 192.168.36.123:8883
2019-09-11 07:41:14.000  Status: MQTT: enabled TLS mode
2019-09-11 07:41:16.051  Error: MQTT: Failed to start, return code: 14 (Check IP/Port)
2019-09-11 07:41:48.550  Status: MQTT: Connecting to 192.168.36.123:8883
2019-09-11 07:41:48.550  Status: MQTT: enabled TLS mode
2019-09-11 07:41:50.579  Error: MQTT: Failed to start, return code: 14 (Check IP/Port)
2019-09-11 07:42:23.050  Status: MQTT: Connecting to 192.168.36.123:8883
2019-09-11 07:42:23.050  Status: MQTT: enabled TLS mode
2019-09-11 07:42:23.499  Status: MQTT: re-connected to: 192.168.36.123:8883
2019-09-11 07:42:23.719  Status: MQTT: Subscribed

There seems to be no problems ?

Did you post this on the Forum ? Do other people have this issue ?

**Comment by gvansanden** [comment]
@gizmocuz I posted in the forum but there where no replies.
You commented early in this ticket that the code looked wrong (which seems correct with my superficial knowledge of C) , so I'm currently working on that assumption.

From what I can see, the error is triggered only in specific circumstances.  There has to be a very brief network disruption.  Long disconnects don't trigger it because the connection will already have expired on the MQTT server.  My issue is that Domoticz tries to reconnect while Mosquitto hasn't timed out the old connection,the server logs of Mosquitto show the old connection was still there, so it keeps killing this connection with the same identifier.  Diconnecting completely also fixes the issue, but it comes back evey couple of days.

Once Domoticzs/Mosquitto get into the reconnect loop, it only recovers after restarting.

I doubt this issue hits many people as most run MQTT on the same Pi or at the least on the same network segment where these brief disconnects don't happen (either no disconnects or longer disconnects)

**Comment by gizmocuz** [comment]
I tested with using two different machines.
I will assume you have a windows pc, or can run windows somehow
Please install Visual Studio community edition (free), get the domoticz source code and the libraries (see Intall.txt), build Domoticz, set a breakpoint (F9) on those lines in MQTT.cpp, and try to debug

**Comment by waltervl** [comment]
Is this still an issue?

**Comment by gizmocuz** [comment]
Nope It works without issues
