### ISSUE TITLE
no icon selection on switch page

### ISSUE THREAD

**Issue by thales-man** [domoticz/domoticz#3550]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version.
* Always state your version when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by thales-man** [comment]
I'm missing a icon selection dropdown.
it used to be there, now it's gone...

is this a 'bug' or is it something I can fix?

![Screen Shot 2019-07-29 at 16 59 13](https://user-images.githubusercontent.com/17850586/62063216-6125a500-b222-11e9-8e67-07ca6b6d5be6.png)

**Comment by rwaaren** [comment]
Already reported here and on the forum. Please use the forum for these type of questions.
It is a bug in latest stable and is fixed in Beta (will not be fixed in V4.10717.

**Comment by thales-man** [comment]
smashing, I look forward to receiving fix!
