### ISSUE TITLE
Small bug for a switch type media player at dasboard page

### ISSUE THREAD

**Issue by NiekN** [domoticz/domoticz#3551]
I have a media player (kodi), and domoticz detects if it is ON or OFF 
At page switches it working fine, you can see the in status ON,OFF or VIDEO . But at dashboard page the status can only be ON or OFF . So when the player is switched ON or OFF the status is correct displayed. But when you start a movie , the status is going to VIDEO. Then at the dashboard the status will be OFF????
![HTPC dashboard](https://user-images.githubusercontent.com/32562791/62162068-b98a9e80-b317-11e9-8ded-a4c2c8fe1e8d.jpg)
![HTPC switches](https://user-images.githubusercontent.com/32562791/62162070-bd1e2580-b317-11e9-9ed2-dce1d2ac077c.jpg)

running Version: 4.11024

**Comment by NiekN** [comment]
also the latest version 4.11662  has this bug

**Comment by gizmocuz** [comment]
Please use our forum!
