### ISSUE TITLE
remote domoticz merges 2 devices into 1 when they have the same id and unit but different hardware

### ISSUE THREAD

**Issue by rrozema** [domoticz/domoticz#3560]
domoticz version: 4.11069

In my pi I have devices installed from 2 hardwares: "P1 Smart Meter USB" and "Enphase Envoy with LAN (HTTP) interface". Both have created their devices with unique hardware + ID + Unit values. Multiple devices have been created for each hardware, but the problem is in one for each device, these can be identified by values: "enphase" + 0001 + 1 and "smart meter" + 0001 + 1. As you should note, the values are the same, apart from the hardware.

In my windows domoticz I have configured the Domoticz - Remote Server with the ip adres , port, username and password for my Pi's domoticz. All devices available in my pi, minus 1, are available in my windows domoticz. So, I am missing one device in my windows domoticz, plus one device in my windows domoticz shows strange behavior: it keeps changing values and even the number of data every now and then. The strange behaving device has indentifing values "pi" + 0001 + 1.

What happens is this: the both devices in my pi each have unique identification only because their hardware id is different. In the windows domoticz however both have the same hardware id, that of the Remote Server hardware. Whenever an update for either device "enphase" + 0001 + 1 or "smart meter" + 0001 + 1 comes in from the pi, this gets sent to the device "pi" + 0001 + 1 in the windows server, which is the same device in the master domoticz. Both devices are merged into one because both have the same hardware id in the windows domoticz, thus the key is the same for both devices.

I have to little experience in c++ development to fix this bug, but enough to read it and I see that domoticzTCP.cpp doesn;t take the remote server's hardware part of the identification into account when mapping the devices from the remote server onto those of the master server.

**Comment by gizmocuz** [comment]
@rrozema , this is a known issue that has to be solved in a feature release

**Comment by waltervl** [comment]
Is this known issue fixed already?

**Comment by gizmocuz** [comment]
Please check beta 15790 ... Both client/server need to run on this beta... quite some things have changed.
You probably will get new devices, so make sure 'Accept new hardware/devices' is enabled in the settings

**Comment by gizmocuz** [comment]
It's fixed in the recent versions
