### ISSUE TITLE
Webinterface/Domoticz freeze because of OZW related issues...

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#3562]
Hi,

I notice many times that because of an issue in OZW, i.e. just one problematic Node, OZW gets unresponsive and then even locks up the core service Domoticz (or at least the Webserver) and gets frozen until OZW wakes up again.
How can it be that Domoticz as system core is not independent to plugins issues?

Many thanks!

//Ricard

**Comment by RicardP** [comment]
I should say that I am on Windows beta 11069, however the issue is not new... :)

**Comment by svollebregt** [comment]
I have the impression that this issue also causes Domoticz on my RPi to freeze. When I remove my OZW dongle everything is ok, but with the interface freezes soon after boot.
[link to Domoticz forum](https://www.domoticz.com/forum/viewtopic.php?f=6&t=28965&p=221187)

**Comment by gizmocuz** [comment]
@RicardP , All build-in hardware runs in it's own thread...
So it should be independent, unless something is calling functions in this hardware class (like a webserver requesting configuration options/values etc)
But when there is a exception/crash, it let's the complete application crash

**Comment by RicardP** [comment]
@gizmocuz , thank you for the feedback. I don't believe anything is crashing for me as I checked logs, ZWave did not restart since last time so Domoticz did not either. Maybe Domoticz is waiting unnecessarily long when ZW-network/Controller is busy/unstable? Could not Domoticz wait for a limited time and then print to log something like "Hardware time-out: OZW plugin did not respond in xx seconds". The Webserver timeout/unresponsive is printed in log, still it was caused by OZW, and can be like 60-280 seconds! I believe Domoticz is then not working either, not only the Webserver-GUI that is stuck for minutes?

The architecture should be focused on robustness prior features, especially in an automation system. A chain is not stronger than the weakest link... i.e. making the core application and built in functions independent as much as possible to plugins or devices flaws.

Anyway I did not experience stuck GUI since my last update 4.11235 with complete recreated ozw-cache (even if new cache was first uncompleted, I had to make "Refresh Node Info" on all Nodes #3597).

Cheers!

**Comment by gizmocuz** [comment]
@RicardP , are you compiling domoticz yourself or are you using a binary ?
Because domoticz is using a PR patch that should not let OZW crash in some cases.
Sure robustness is number one...

**Comment by RicardP** [comment]
@gizmocuz I am not compiling myself, using the frequent updated beta binary - Windows platform.
It does not look OZW crashing, instead sudden Domoticz Webpage/GUI freezing/non responsive for minutes can even happen because of a non responsive ZWave Node = OZW issue. So Domoticz seems at least not independent in respect to OZW integration.

Just sharing my experience as a user... :)

Thanks!

**Comment by gizmocuz** [comment]
Is this still an issue ?

**Comment by RicardP** [comment]
@gizmocuz yes I believe Domoticz still freeze due to certain OZW issues/interactions, however the stalls is not very frequent now as you seemed to have solved a lot of issues...
So we close this, for now anyway :)

Thanks!!
