### ISSUE TITLE
s0 meter with LAN interface. Can't add hardware in hardware tab

### ISSUE THREAD

**Issue by xztraz** [domoticz/domoticz#3567]
DOMOTICZ V4.11062 RPI

Trying to add hardware "s0 meter with LAN interface"
but it doesn't do anything when pushing add. No hardware added.

**Comment by gizmocuz** [comment]
Thanks for spotting, found the issue, and it's corrected in beta 11082

**Comment by xztraz** [comment]
great!

are there any protocol references for the lan meter that is usable for sending data from an esp for example

**Comment by gizmocuz** [comment]
@xztraz , yes there are, best to have a look on the website of the author of the hardware. The protocol is open
http://www.smartmeterdashboard.nl/

**Comment by xztraz** [comment]
Awesome thanks! didn't know where to look.
