### ISSUE TITLE
zwave : problem with nodon and neo coolcam

### ISSUE THREAD

**Issue by firelook** [domoticz/domoticz#3569]
windows 10
version : V4.11196
Build Hash: a380dfbe7
Build Date: 2019-08-12 07:59:02

Zwave : problems, it is working perfectly with Fibaro but not with nod ons after several hours and tryed to refresh manually

`

NodeID | Name | Description | Manufacturer | ID | Type | Last Seen | Enable Polling | Status
-- | -- | -- | -- | -- | -- | -- | -- | --
056 (0x38) | t11 | NodOn CRC-3-6-0x Soft Remote |   | 0x0000 | 0x0000 | 2019-08-12 10:02:59 | No |  
054 (0x36) | Water3 | Neo CoolCam Water Leakage Detector |   | 0x0000 | 0x0000 | 2019-08-12 10:02:59 | No |  
053 (0x35) | sw_arosage_back | FIBARO System FGS212 Switch 3kW |   | 0x0000 | 0x0000 | 2019-08-12 10:03:00 | No |  
052 (0x34) | sw_arosage_front | FIBARO System FGS212 Switch 3kW | FIBARO System | 0x1002 | 0x0402 | 2019-08-12 10:04:06 | No |  
051 (0x33) | d5 | Neo CoolCam Door/Window Detector |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
050 (0x32) | d4 | Neo CoolCam Door/Window Detector |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
049 (0x31) | dep2 | Neo CoolCam Battery Powered PIR Sensor |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
048 (0x30) | t2 | Everspring ST814 Temperature and Humidity Sensor |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
047 (0x2f) | t1 | Everspring ST814 Temperature and Humidity Sensor |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
046 (0x2e) | water2 | Neo CoolCam Water Leakage Detector |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
045 (0x2d) | water1 | Neo CoolCam Water Leakage Detector |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
044 (0x2c) | dep1 | Neo CoolCam Battery Powered PIR Sensor |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
043 (0x2b) | t10 | NodOn CRC-3-6-0x Soft Remote |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
042 (0x2a) | t9 | NodOn CRC-3-6-0x Soft Remote |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
038 (0x26) | t7 | NodOn CRC-3-6-0x Soft Remote |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
036 (0x24) | d3 | Neo CoolCam Door/Window Detector |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
035 (0x23) | d2 | Neo CoolCam Door/Window Detector |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
034 (0x22) | t6 | NodOn CRC-3-6-0x Soft Remote |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
031 (0x1f) | t5 | NodOn CRC-3-6-0x Soft Remote |   | 0x0000 | 0x0000 | 2019-08-12 10:02:54 | No |  
030 (0x1e) | Prise Z4 | Neo CoolCam Power plug 12A |   | 0x0000 | 0x0000 | 2019-08-12 10:02:52 | No |  
029 (0x1d) | d1 | Neo CoolCam Door/Window Detector |   | 0x0000 | 0x0000 | 2019-08-12 10:02:52 | No |  
027 (0x1b) | t4 | NodOn CRC-3-6-0x Soft Remote |   | 0x0000 | 0x0000 | 2019-08-12 10:02:52 | No |  
023 (0x17) | Prise Z2 | Neo CoolCam Power plug 12A |   | 0x0000 | 0x0000 | 2019-08-12 10:02:59 | No |  
021 (0x15) | zwave_N1_aquarium | FIBARO System FGWPE/F Wall Plug | FIBARO System | 0x1000 | 0x0600 | 2019-08-12 10:03:59 | No |  
020 (0x14) | Zwave_N-1_SousSol_P1 | FIBARO System FGWPE/F Wall Plug | FIBARO System | 0x1000 | 0x0600 | 2019-08-12 10:03:59 | No |  
019 (0x13) | Zwave_N0_SalleManger_P2 | FIBARO System FGWPE/F Wall Plug | FIBARO System | 0x1000 | 0x0600 | 2019-08-12 10:03:59 | No |  
018 (0x12) | ZWAVE_N1_chambre_P2 | FIBARO System FGWPE/F Wall Plug | FIBARO System | 0x1000 | 0x0600 | 2019-08-12 10:03:59 | No |  
015 (0x0f) | ZWAVE_N1_chambre_P1 | FIBARO System FGWPE/F Wall Plug |   | 0x0000 | 0x0000 | 2019-08-12 10:02:59 | No |  
014 (0x0e) | Unknown | Portable Remote Controller |   | 0x0000 | 0x0000 | 2019-08-12 10:02:46 | No |  
013 (0x0d) | ZWAVE_N1_Salle_Jeu_P1 | FIBARO System FGWPE/F Wall Plug | FIBARO System | 0x1000 | 0x0600 | 2019-08-12 10:03:58 | No |  
011 (0x0b) | Zwave_N0_SalleManger_P1 | FIBARO System FGWPE/F Wall Plug | FIBARO System | 0x1000 | 0x0600 | 2019-08-12 10:04:06 | No |  
004 (0x04) | ZWAVE_N1_Salon_P1 | FIBARO System FGWPE/F Wall Plug | FIBARO System | 0x1000 | 0x0600 | 2019-08-12 10:03:58 | No |  
001 (0x01) | Controller | Aeotec ZW090 Z-Stick Gen5 EU | AEON Labs | 0x005a | 0x0001 | 2019-08-12 10:02:46 | No |  

`

**Comment by gizmocuz** [comment]
Please have a look at the current/closed issues, it has been explained
