### ISSUE TITLE
z-wave : aeotec HEM ZW095-3C60 no reports

### ISSUE THREAD

**Issue by ilorel** [domoticz/domoticz#3570]
Hello,

I've been using domoticz on my synology DS218+ for one year without problem (actually arround 15 nodes).

Config : 
Synology DS218+ (dsm 6.2.2)
domoticz (Version: 4.11196)
OpenZWave : Version: 1.6-881-ga2f8a143-dirty

A couple of weeks ago, I bought an aeotec home energy meter ZW095-3C60 .
Include was OK, devices were created but their values were not updated automatically.
I changed parameters without success.
I excluded and re-included HEM and have the same issue.

After many research on internet, I found the OpenZWave Control Panel and if I press the refresh button, values and devices are updated once.
![OZW_page](https://user-images.githubusercontent.com/54119096/63049684-88929800-bed9-11e9-8aed-7db8799e6535.JPG)

I also tried to change and update group association and this node is the only one with group 1.1.
Is-it normal ?
![group_page](https://user-images.githubusercontent.com/54119096/63050165-bf1ce280-beda-11e9-82c1-44762da841b2.JPG)

I have no information or error in the logs...

With polling 'ON' on this node, the values were updated correctly, but polling ON mode is not correct for me.

I think it's a problem between domoticz and open zwave.
Is there any solution to update data normaly with this HEM?

Thanks for your help.
With regards

**Comment by gizmocuz** [comment]
@ilorel , if the values are also not refreshing in the control panel, it does not look like a issue with domoticz.
You could enable 'debug logging' when you select the controller, but do not debug for long as it generates a large file...
If you look in the debug log, do you see updates for W/V/A for the groups ?
If not, you do have to enable polling. Why do you say "polling ON mode is not correct for me" ?
Some devices needs polling, that is why this option is for... should be avoided if it should not be needed of course

**Comment by ilorel** [comment]
@gizmocuz , thanks for your answer.
I enabled "debug logging" for controller and I saw only one update, same as when I stop and restart domoticz.
After there is no more update as you can see in the log file (I kept only the node027 "HEM" information)
[OZW_Log_light_15_08_19.txt](https://github.com/domoticz/domoticz/files/3507149/OZW_Log_light_15_08_19.txt)

I don't understand why.
Of course, I could enable polling, but this equipment should work without polling.
Second reason, I need to trig on percent of watt and not on time.
Third reason, polling uses more cpu ressources on the system.

During my internet research, I found 2 persons with same problem.
One solved it with open zwave 1.6 update, the second had to reinstall domoticz from scratch.

In my case, openzwave update changed nothing and I don't want to restart from scratch.

Do you think deleting "ozwcache_XX.xml" file could help me ?

Thanks
Regards

**Comment by gizmocuz** [comment]
@ilorel , you can always make a backup of the config file (close domoticz first), move it to another location

Did you configure the parameters correctly ?

See here

https://blog.domadoo.fr/guides/jeedom-guide-dutilisation-du-compteur-denergie-hem3-daeon-labs/

**Comment by tonbor** [comment]
Perhabs same problem as with issue #3566, see debugging there.
