### ISSUE TITLE
Temperature setpoint over MQTT exhibits signs of multiple personality disorder

### ISSUE THREAD

**Issue by lbdroid** [domoticz/domoticz#3573]
When I publish a temperature setpoint over mqtt, domoticz replies TWICE.

Once in Degrees F and once in Degrees C.

Here is a log;
```
$ mosquitto_sub -h 127.0.0.1 -t '#' -v
 
domoticz/in {"idx":2,"svalue":"75"}
domoticz/out {
   "Battery" : 255,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Thermostat",
   "id" : "0014052",
   "idx" : 2,
   "name" : "Setpoint",
   "nvalue" : 0,
   "stype" : "SetPoint",
   "svalue1" : "75",
   "unit" : 1
}

domoticz/out {
   "Battery" : 255,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Thermostat",
   "id" : "0014052",
   "idx" : 2,
   "name" : "Setpoint",
   "nvalue" : 0,
   "stype" : "SetPoint",
   "svalue1" : "23.89",
   "unit" : 1
}
```

This is the publish command;
```
mosquitto_pub -h localhost -m '{"idx":2,"svalue":"75"}' -t domoticz/in
```

The value is correctly displayed in the website as "75.0^ F".

When I change the temperature setpoint in the website, I only get one MQTT message, which is the temperature in degrees C, which is the incorrect unit;

Example, set to 70:
```
domoticz/out {
   "Battery" : 255,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Thermostat",
   "id" : "0014052",
   "idx" : 2,
   "name" : "Setpoint",
   "nvalue" : 0,
   "stype" : "SetPoint",
   "svalue1" : "21.11",
   "unit" : 1
}
```

Domoticz should do one of the following instead of current behavior;
Option 1: Adhere strictly to the units selected in Setup/Meter/Counter Setup, or...
Option 2: Provide BOTH units in a single message, with the unit specified.

**Comment by gizmocuz** [comment]
I tried to replicate this using a clean domoticz, 1 dummy temperature sensor and a clean MQTT setup

Listening to the output with

`mosquitto_sub -h localhost -t "domoticz/out" -v`

and updating the sensor with:

`mosquitto_pub -h localhost -m '{"idx":117,"svalue":"75"}' -t domoticz/in`

I get only 1 message in the output:

> domoticz/out {
>    "Battery" : 255,
>    "RSSI" : 12,
>    "description" : "",
>    "dtype" : "Temp",
>    "id" : "82117",
>    "idx" : 117,
>    "name" : "MyTemp",
>    "nvalue" : 0,
>    "stype" : "LaCrosse TX3",
>    "svalue1" : "75.00",
>    "unit" : 1
> }
> 

Maybe you have some scripts running ? Can you try on a clean install ?

Also, when reporting issues, specify at least the Domoticz version, you did not read the posting guide!

Btw, I'm running with the latest beta version
