### ISSUE TITLE
Synology cross compile stop with error.

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#3574]
[ 59%] Building CXX object CMakeFiles/domoticz.dir/hardware/OpenWeatherMap.cpp.o
[ 59%] Building CXX object CMakeFiles/domoticz.dir/hardware/OpenWebNetTCP.cpp.o
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r11207/hardware/OpenWebNetTCP.cpp: In member function ‘bool COpenWebNetTCP::ownAuthentication(csocket*)’:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r11207/hardware/OpenWebNetTCP.cpp:531:76: error: cannot pass objects of non-trivially-copyable type ‘const string {aka const class std::basic_string<char>}’ through ‘...’
    _log.Log(LOG_ERROR, "COpenWebNetTCP: frame request error:'%s'", strFrame);
                                                                            ^
CMakeFiles/domoticz.dir/build.make:1570: recipe for target 'CMakeFiles/domoticz.dir/hardware/OpenWebNetTCP.cpp.o' failed
make[5]: *** [CMakeFiles/domoticz.dir/hardware/OpenWebNetTCP.cpp.o] Error 1
make[5]: Leaving directory '/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r11207'
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[4]: *** [CMakeFiles/domoticz.dir/all] Error 2
make[4]: Leaving directory '/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r11207'
Makefile:151: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/dahl/spksrc-master/spk/domoticz/work-x86-6.2/domoticz-r11207'

**Comment by xbeaudouin** [comment]
BTW Same error on FreeBSD ...:/

**Comment by rwaaren** [comment]
Is this still the situation after the last commit by @dnpwwo ? Compiling without issues on Raspberry Debian stretch

**Comment by dnpwwo** [comment]
My changes were WebSocket related not OpenWebNet.  @Spugna85 changed that.

Built on Windows and Ubuntu okay, I'll have a look at RPi.

Edit: Compiles on RPi (Buster) as well

**Comment by Spugna85** [comment]
I have now fixed with a pull request.

**Comment by Jumbotroll** [comment]
I can confirm the Pull request  #3576 fix cross compile error for synology.
