### ISSUE TITLE
Require easy way to define complex devices (simpler than it sounds)

### ISSUE THREAD

**Issue by lbdroid** [domoticz/domoticz#3575]
When enabling a complex piece of hardware, the view of that hardware in domoticz is messy, resulting in several "devices" that don't immediately appear to be associated.

As an example, I'm going to use a thermostat. The data points for a thermostat will including the following;
- the sensor readings (temperature[,pressure][,humidity][,vox][,co]),
- the mode of operation (off, heat, cool, auto),
- the temperature set point,
- the fan setting (on/auto),
- the current status (idle, heating, cooling, fan on, etc).

This imaginary thermostat can be created in domoticz in one of two ways;
1) write a new complex device that represents all of the data points it presents,
2) associate it with SEVERAL SEPARATE devices, each of which represents one of the data points.

Option 1 appears to be horribly complex and has to be done for each new type of complex device that is conceived.

Option 2 works currently, but results in the single complex device being represented as individual, separate devices, and worse, under different tabs, and with no ability to easily determine which devices are part of which hardware.

For example, the sensor readings for a BME280 will be represented by a temp+hum+pres sensor device, which ends up in the TEMPERATURE and WEATHER tabs.

The mode of operation is represented by a SELECTOR SWITCH in the switches tab.

The temperature set point is represented by a THERMOSTAT SETPOINT in the utility tab.

The fan mode is represented by an ON/OFF switch in the switches tab.

The current status can be represented in several ways, such as TEXT in the utility tab.

The complex hardware/device is set up as follows;
Hardware:
- MQTT Client Gateway
- DUMMY

Then each of the separate devices are created off of the DUMMY, and so they in reality are all part of the same Dummy HARDWARE item, so fundamentally, there actually is an association between all of the devices, but this association is not represented well in the UI.

WHAT IS ACTUALLY NEEDED

What is actually needed is a UI change rather than a fundamental change or complex new features. Specifically, the ability to create a UI widget that represents an item of "Hardware", that joins together all of the "Devices" that are part of that hardware, and to place that widget in a SINGLE tab of the UI. Further, when such a widget is presented for that hardware, the individual devices within it should NOT be displayed separately.

What this would do, is it would make it possible to define a piece of complex hardware with multiple data points by using the more fundamental building blocks that are already available.

**Comment by gizmocuz** [comment]
As your here on github (for coders), please fork the repository and make the needed changes and post some screenshots.

**Comment by lbdroid** [comment]
Is it your intention to offer to hire me to implement this feature?

**Comment by gizmocuz** [comment]
Yes and in return you can use Domoticz for free!

**Comment by lbdroid** [comment]
I don't work for free.
Let me know if you're interested in discussing what I charge.
