### ISSUE TITLE
Support of new Aqara LLKZMK11LM Two-way Control Module Wireless Relay Controller

### ISSUE THREAD

**Issue by nighthawkii** [domoticz/domoticz#3577]
Hi,

I bought some Aqara LLKZMK11LM Two-way Control Module Wireless Relay Controller, but they are not well recognized in Domoticz, currently they are considered as 2 devices :
device 1:
ID: 84AB
name : Xiaomi TempHum wireless relay
type: Temp + Humidity
subtype: WTGR800
data: 100.0C, 0%

device 2:
ID: 8502
name : Xiaomi TempHum
type: Temp + Humidity
subtype: WTGR800
data: 100.0C, 0%

So as they are not considered as actuators, no way to control them from domoticz...
I would expect to see them like a wired double switch actuator

I would be pleased to help, so if you need some info, just ask !

**Comment by gizmocuz** [comment]
Please use our forum
