### ISSUE TITLE
Buienradar plugin kills Domoticz

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#3579]
I place this in the Buienradar section.
Only perhaps here also useful.

https://github.com/ffes/domoticz-buienradar/issues/32

**Comment by gizmocuz** [comment]
I started with a native implementation, should be finished today

**Comment by Dylantje** [comment]
> 
> 
> I started with a native implementation, should be finished today

GREAT!!!!

Let me know i test!!!

**Comment by arjanvanleent** [comment]
This is looks great. But it don't show the windspeed.
The windspeed is showed in the json file of buienrader but not in domoticz

> {"$id":"20","stationid":6330,"stationname":"Meetstation Hoek van Holland","lat":51.98,"lon":4.1,"regio":"Hoek van Holland","timestamp":"2019-08-24T23:40:00","weatherdescription":"Zwaar bewolkt","iconurl":"https://www.buienradar.nl/resources/images/icons/weather/30x30/cc.png","graphUrl":"https://www.buienradar.nl/nederland/weerbericht/weergrafieken/cc","winddirection":"O","airpressure":1018.7,"temperature":18.0,"groundtemperature":14.5,"feeltemperature":18.0,"windgusts":3.0,"windspeed":0.1,"windspeedBft":0,"humidity":78.0,"precipitation":0.0,"sunpower":0.0,"rainFallLast24Hour":0.0,"rainFallLastHour":0.0,"winddirectiondegrees":79}

![image](https://user-images.githubusercontent.com/17556892/63643051-872b5180-c6c9-11e9-99b1-c5b6cad6b08e.png)


![image](https://user-images.githubusercontent.com/17556892/63643146-af678000-c6ca-11e9-82af-edaeef329731.png)

**Comment by rwaaren** [comment]
> This is looks great. But it don't show the windspeed.
> The windspeed is showed in the json file of buienrader but not in domoticz

Solved in next Beta (commit https://github.com/domoticz/domoticz/commit/a571b5a09e25c3c2ebd0aadff9c88a1e94bc47a0 )

**Comment by gizmocuz** [comment]
Thanks!
