### ISSUE TITLE
Can't access web interface

### ISSUE THREAD

**Issue by zpowellman** [domoticz/domoticz#3582]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version.
* Always state your version when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by zpowellman** [comment]
Installed Domoticz on new install of Raspbian desktop on Dell machine. Used Easy install (curl -L).
Looks like it all went well with no errors and success messages but I  can't  access web interface.  SSL`d into system and requested ./domoticz status and got /domoticz: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory.  Looks like I'm missing something?   Any help would be appreciated.
Thanks
Dan

**Comment by gizmocuz** [comment]
Please use our forum!
