### ISSUE TITLE
[Request] Floorplan add support for SVG

### ISSUE THREAD

**Issue by chatainsim** [domoticz/domoticz#3585]
Hello,

It would be nice to add support for SVG in the Floorplan.
Because png and jpg are limited in quality.

Thanks

**Comment by chatainsim** [comment]
Sorry, this in not an issue, submitting in forum.

Thanks

**Comment by gizmocuz** [comment]
That's a great idea... where is your forum post ?

My first try resulted in a mixed result. Yes it is not that difficult to add SVG support,
but those are vector based, and mostly consist of a transparent background color.

This results in:

![image](https://user-images.githubusercontent.com/2265299/63829201-25891280-c969-11e9-84c4-1079589727c4.png)

This we could solve by placing a 'rect' element as the first element:

![image](https://user-images.githubusercontent.com/2265299/63829706-87964780-c96a-11e9-89d2-62cb4bc338e5.png)

This might also solve possible transparent PNG issues ;)

There was a similar issue on the main floorplan page

**Comment by chatainsim** [comment]
Here it is : https://www.domoticz.com/forum/viewtopic.php?f=31&t=29185
I use a non transparent images for my plan so it shouldn't be a problem for me.
I will try when available.
Thank you for the great work.

**Comment by gizmocuz** [comment]
Beta should be available now

**Comment by chatainsim** [comment]
Nice, I'll try asap ! Thanks

**Comment by chatainsim** [comment]
For a non transparent images it's working fine. Thank you.

**Comment by gizmocuz** [comment]
@chatainsim , and transparent ? should work as well ?

**Comment by chatainsim** [comment]
yes, seems working too.

**Comment by gizmocuz** [comment]
Great, closing issue. Could you update your forum post ? (that it is implemented)

**Comment by chatainsim** [comment]
Done
