### ISSUE TITLE
Domoticz Remote Server Devices report all names as Unknown

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#3586]
I painfully edit all the names on my domoticz slave devices. But when I access them from a master all names are popping up as 'Unknown'. It would be nice if the domoticz remote server hardware uses the names of the slave devices, instead of the situation now, re-editing all the names.

Not sure if this is a bug or a feature request.

**Comment by gizmocuz** [comment]
@Tristan79 , that would mean that we have to send also the names to the master, and that would cause much more data traffic
The plan is to re-do the whole master/client setup, as currently it is also limited by device_id.
This will be done in the near feature
I know it is double work... a lot of copy/paste now, but it has to be done once
Closing issue now as currently it can not be changed, but hopefully soon it will be (also requesting already stored log information from the slave's)

**Comment by MikeyMan83** [comment]
Still very much appreciated that this is solved.

**Comment by gizmocuz** [comment]
@MikeyMan83 , yep, but the first thing to do is change the delivery method, instead of using binary we should serialize this object with cereal (which is already used in some parts of the code), with this we could also transmit the original name

**Comment by MikeyMan83** [comment]
Sounds good! It's quite hard to make the connection between different devices now. 

Also, I tried to test the master/slave setup yesterday. Only 68 of the roughly 400 devices are shared.

If I can help out with any logging or such let me know.

**Comment by gizmocuz** [comment]
Yes that is also an issue for some devices... specially devices that have strings as id's .... (like with MQTT/zigbee/some zwave)
And we need to expand the device table with a additional hardware id (the original hardware id) because it could be that on the slave the device_id/unit could be the same for other hardware
I'm currently struggling to get MQTT-AD blinds working (seems almost done) and after this I could have a look at this issue unless someone beats me to it 😊

**Comment by MikeyMan83** [comment]
That explains some of it indeed. I have lots of z-wave and mqtt devices. Wouldn't be surprised if those numbers add up.

**Comment by MikeyMan83** [comment]
Might be overstepping here, but also some simple sensors are not showing up:

![image](https://user-images.githubusercontent.com/6270724/187861921-eda73448-5252-4f68-aa4b-cf18aacf590b.png)

Again; if i can help in any way by sharing logs, screenshots or screenshare, let me know :)

**Comment by gizmocuz** [comment]
define simple ;) ... but Domoticz internal sensors with water? What hardware is this ? Not the internal motherboard hardware for sure

**Comment by gizmocuz** [comment]
But all hardware that is directly poking/storing in the database instead of using the default paths (like calling SendTempSensor, SendMeterSensor) will not be transmitted to the other side

**Comment by MikeyMan83** [comment]
Its an NPN sensor connected with GPIO :)

**Comment by gizmocuz** [comment]
Ahh nice! I use a ESP (with WiFi) for this and MQTT Auto discovery.... if you want the sketch let me know
But do you use the GPIO hardware? I thought this only had switches

**Comment by MikeyMan83** [comment]
Just following some guides:

https://www.picademie.nl/index.php/2021/04/09/watermeter-uitlezen/

Hope translate will do its job
