### ISSUE TITLE
Inconsistency of Door Contact sValue and Log

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#3587]
There is some inconsistency on the Door Contact Switchtype sValue and what is reported by Domoticz when looking after the logs of such widget/device

Door Contact nValue/sValue are set to 0/Closed or 1/Open

While if you look after the log history you get Off or On

I would expect Closed instead of Off, and open instead of On in order to be consistent.

This seems to be similar for Blinds Percentage where you get Off and On instead of Closed and Open

**Comment by gizmocuz** [comment]
Yes this is intended, like a door lock it's meaning is Closed/Open vs Open/Closed
A inverted switch or blind also swaps the labels

**Comment by mcmikev** [comment]
Sorry but do i understand it correcty when the door is open the log shows on and not open in the log. Closed the log shows off and not closed. That is because of a swap? I dont fully understand that Logic. Sorry. 
Can the log just show open or closed?
I have multiple sensors and it would be great if the logs show the same value as the svalue so that it 100% clear what it was

**Comment by gizmocuz** [comment]
Maybe post some screenshots and also the widget on de switches tab please

**Comment by mcmikev** [comment]
Sure, the "achterdeur" sensor is a z-wave sensor (fibaro) and the widget show open or closed, the log shows on or off.
![doorsensor](https://user-images.githubusercontent.com/10433087/63870378-28602380-c9ba-11e9-86b9-dc4f10095fa9.png)
![log](https://user-images.githubusercontent.com/10433087/63870388-2ac27d80-c9ba-11e9-9bde-ffa49f00b0f9.png)

**Comment by pipiche38** [comment]
bb5b485ea24271b74be24233e04259d803224f9f

**Comment by mcmikev** [comment]
YESSSSS, just did an update and indeed the correct status is shown in the log !!!
Thanks Gizmocuz!!

**Comment by pipiche38** [comment]
Great! Thanks for the quick return and closing the issue then.
