### ISSUE TITLE
Transparency Disappeared for PNG Floorplan.

### ISSUE THREAD

**Issue by loglux** [domoticz/domoticz#3593]
I use v4.11231 beta and since the previous release, the transparency for PNG images has been lost.
![transplost](https://user-images.githubusercontent.com/37578325/64060819-00dfa580-cbca-11e9-93a8-3e0369c1c324.png)

**Comment by gizmocuz** [comment]
Yes this is by design... i can't see your full floorplan and how it looks
I have done so, because we now also support SVG (vector files), those have no background 99% of the time.
I could have a look to see if i can figure out to turn on the background only for SVG files, but not sure if that is possible.
But show me a complete floorplan... it looks you have to 'cut/crop' the image ? You can do so with various free tools, even online tools

https://www.befunky.com/create/crop-photo/

**Comment by loglux** [comment]
It was OK until recently. I have changed nothing in the Floorplan image. It was transparent and this 'white area' wasn't visible.

**Comment by gizmocuz** [comment]
@loglux , please read my response and show me a complete floorplan !
If you have read my response, you would have seen that "I" changed this...

**Comment by loglux** [comment]
What the point? It just a transparent PNG image.

**Comment by gizmocuz** [comment]
To see if you just have to crop your floorplan image ?

**Comment by loglux** [comment]
It doesn't resolve the problem.

**Comment by loglux** [comment]
The problem is that the Domoticz interface does not support PNG transparency anymore.

**Comment by gizmocuz** [comment]
"Show" me your problem ? I only see a thick white border at the bottom, the right side looks OK to me.
The bottom you could crop ?

**Comment by loglux** [comment]
all sides

**Comment by gizmocuz** [comment]
Ohh you mean the 5 mm white display ? even that you can crop as mentioned before.
Again, just show me a complete floorplan, else I am going to close this issue... as it seems no issue at all

**Comment by loglux** [comment]
That the point again? The white area actually is no white at all, it's transparent in the PNG file. It must be unvisible.

**Comment by loglux** [comment]
![transp](https://user-images.githubusercontent.com/37578325/64061104-9e88a400-cbcd-11e9-8ab4-93232de8d594.png)

**Comment by loglux** [comment]
The question is still ignored - where the transparency gone?

**Comment by gizmocuz** [comment]
So showing this floowplan on a dark background gives you issues as well.
With a white background (don't all floorplans have white backgrounds???), it displays better
About the commercial text at the bottom, you can crop this

**Comment by gizmocuz** [comment]
@loglux , you still did not read my first answer?

**Comment by loglux** [comment]
What was the answer? Can I crop the image? That does not resolve the problem.

**Comment by loglux** [comment]
![newver](https://user-images.githubusercontent.com/37578325/64061502-916eb380-cbd3-11e9-8ed1-021f4a1622d6.png)
![oldver](https://user-images.githubusercontent.com/37578325/64061503-916eb380-cbd3-11e9-82ea-bef9b1fffd3a.png)

**Comment by loglux** [comment]
I don't have a white background. It's transparent, not white.

**Comment by dheuts90** [comment]
What is the problem? Just keep it white

**Comment by loglux** [comment]
Do you offer me to crop this part as well? It looked fine before the transparency was broken. 
![backgd](https://user-images.githubusercontent.com/37578325/64061707-499d5b80-cbd6-11e9-9998-3c2d5e500193.png)

**Comment by gizmocuz** [comment]
@loglux , the question you asked before was why has the transparency gone ... that i have answered
And to your last question, YES ! that SHOULD be white...
If that is your garden, and you don't want it white, add some greens....

**Comment by loglux** [comment]
I don't need this white, I'd roll back the release if it was possible.

**Comment by loglux** [comment]
It's not a garden, it's a street. I don't need it in my plan.

**Comment by loglux** [comment]
Guys, you're very very frustrating me. 
What changed you've done? I'll fix it manually on my computer.

**Comment by loglux** [comment]
I need the one of the previous beta releases to roll back.

**Comment by gizmocuz** [comment]
Google is your friend! Try searching for "git checkout specific commit".
After you have compiled this version and are running in it, make sure in the settings you disable checking for updates, and never ever update again

**Comment by loglux** [comment]
OK. How can I choose the beta version?
```
domoticz@littlehelp:~/dev-domoticz$ git tag -l
2.3530
3.4834
3.5834
3.5837
3.5877
3.8153
4.10658
4.10659
4.10693
4.10717
4.9700
domoticz@littlehelp:~/dev-domoticz$

```

**Comment by gizmocuz** [comment]
Look at the github commit history, this is not the place to discuss this.
There is probably a Forum topic about this, or it's on our wiki

**Comment by loglux** [comment]
it does show only stable releases

**Comment by loglux** [comment]
OK. I've got it. Since we are unable to find common ground, It's a time for me to migrate to another system.

**Comment by dannybloe** [comment]
I must say loglux has a point here. All those floorplans people have created so far have been created in a context without a white background. I know some people want to make it look good and spend a considerable amount of time to get it right. Now suddenly one person wants SVG (which is fine) and all those plans out there get an ugly white border. I don't think it is fair they now all have to edit their PNGs while it is so easy for this one or two persons to add a fill to their SVGs (they are text files after all). 

My two cents.

**Comment by dnpwwo** [comment]
Personally I prefer it with transparency.  

As @dannybloe says, if an SVG user wants a background they can edit the file and add one. Google knows how to do that so it isn't hard.

**Comment by gizmocuz** [comment]
I had no objections to alter it (see my first reaction), but the way this user is reacting/talking I do not agree of, and for me this is now on a very low priority.

As mentioned before, we just have to see if the floorplan image is SVG and draw a white background, or we drop the transparency and SVG users have to add their own background.

I might have a look at this in 2020, unless someone beats me to it...

**Comment by loglux** [comment]
I spent time to create the floorplan, then set up rooms for that. 
BTW, the transparency was a step on progress in web developing. You've just messed it up. I spend time studying and creating scripts etc. 

After all, you force me to spend time again to fix that. Maybe easier to migrate to another system. What I'm starting to do - looking for another HA alternative. 

I won't ask about priority or fix this issue anymore. I found your reaction very rude.

**Comment by a3vd** [comment]
How i it possible that you only support SVG transparence though it is much easier with png. ?

I agree with loglux i also spend time creating the png the way i want it , and i don't have a svg builder !
![rynesteynbeneden](https://user-images.githubusercontent.com/29863575/64367816-385eaf80-d019-11e9-8979-4337f707b2ec.png)
![eersteverdieping2019](https://user-images.githubusercontent.com/29863575/64367830-3c8acd00-d019-11e9-97b5-6534f1985a49.png)
![zolder](https://user-images.githubusercontent.com/29863575/64367834-3eed2700-d019-11e9-8a52-efd4ed7481b4.png)

Is anybody able to convert it for me ?, i can send you the original high res version !

**Comment by loglux** [comment]
This parameter (fill="white" creates this mess on the webpage) 

![fillwhite](https://user-images.githubusercontent.com/37578325/64369251-d51e4e80-d013-11e9-9196-833822ec8192.png)

If you change "white" to `"#013"`, the white shit will disappear.

It may be possible the parameter in the file FloorplanController.js in a line number 107 is responsible for that. 

`svgCont.childNodes[0].appendChild(makeSVGnode('rect', { width: "100%", height: "100%", fill: "white" }, ''));`

But I'm not sure. I've tried to change it to `#013` but the browser is still picking up the old version of the file and continuing to generate the white mess.

**Comment by loglux** [comment]
in domoticz/www/app/FloorplanController.js
in the line 107
`svgCont.childNodes[0].appendChild(makeSVGnode('rect', { width: "100%", height: "100%", fill: "white" }, ''));`

change "white" to "transparent"

`svgCont.childNodes[0].appendChild(makeSVGnode('rect', { width: "100%", height: "100%", fill: "transparent" }, ''));`

And then restart Domoticz (sudo systemctl restart domoticz - or whatever you do for that), clean up your browser cache and the white mess will disappear.

**Comment by a3vd** [comment]
Tnxs loglux , that did the job !

**Comment by gizmocuz** [comment]
Yep, almost, there was also a opaque background in the editor.
All removed in beta 11290 (available in an hour)

**Comment by a3vd** [comment]
Great job, Gizmocuz   indeed 11290 solved the problem !

Thanks !
