### ISSUE TITLE
Daikin Integrated plugin does not support new version of Adaptator

### ISSUE THREAD

**Issue by bueno79** [domoticz/domoticz#3595]
Hi,

HW :  raspberry 3
domoticz : stable 4.10717

I have 2 wifi for daikin in version BRP069A42. Both set with domoticz with integrated plugin. Just get a new wifi adaptator and the ref is now BRP069B42. It is not working anymore. It seems something has change.

when I had the module in logs I have this 
Error: Daikin: Error connecting to: 192.168.10.77

ON/Off switch is working but not the selector for mode or ventilation.

Someone is able to check the plugin ? Impossible to find the old version of the adaptator on internet. So Domoticz should support this now asap. Pleease :)

regards
Bueno

**Comment by gizmocuz** [comment]
Don't cross post on both Forum and Github!, Keep using the forum plz
