### ISSUE TITLE
buienradar virtual switch is it going to rain 266% when switched on

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3596]
i noticed in the log this virtual switch is set to 266% when it is going to rain.
it turns out this is also visible in the virtual device itself
i think this should be ON

![image](https://user-images.githubusercontent.com/16853535/64068491-25bf3180-cc39-11e9-9b74-fc5356d8b849.png)

**Comment by gizmocuz** [comment]
Found the issue! Fixed in beta 11248. I was reporting a level (255) , and that should have been 0 ...
Thanks for reporting!
