### ISSUE TITLE
.f3.lua and .f3.lua.swp are installed

### ISSUE THREAD

**Issue by yurivict** [domoticz/domoticz#3599]
These files are installed, among others:
```
...
domoticz/dzVents/runtime/tests/generated_scripts/internal2.lua
domoticz/dzVents/runtime/tests/scandir/.f3.lua
domoticz/dzVents/runtime/tests/scandir/.f3.lua.swp
domoticz/dzVents/runtime/tests/scandir/f1.lua
domoticz/dzVents/runtime/tests/scandir/f1lua
...
```

FreeBSD 12, port

**Comment by yurivict** [comment]
```domoticz/dzVents/.gitignore``` is also installed.

**Comment by rwaaren** [comment]
The files in tests/ are required for unit testing dzVents. 
.gitignore is used to ensure no user scripts etc.. become part of a git commit

**Comment by yurivict** [comment]
Why is .swp file required?

**Comment by rwaaren** [comment]
Same answer: The files in tests/ are required for unit testing dzVents.
the .swp file is a file that should be ignored by a particular test.  So if it would not be there you would not test that aspect.

**Comment by yurivict** [comment]
```.{fname}.swp``` are temporary swap files that ```vim``` creates when it opens the file.
I suspect that your vim crashed, and you just committed the swap file.

**Comment by rwaaren** [comment]
I cannot influence what you think or suspect.
