### ISSUE TITLE
Login form not working correctly

### ISSUE THREAD

**Issue by WaaaghNL** [domoticz/domoticz#360]
The problem:
When i'm trying to login with my username and password then i'm stuck in a endless loop to the login screen. But when i check the "remember me" option i go to the dashboard. 

i didn't check the basic auth

`Domoticz SDcard Image: Build Hash: 23830c2 Build Date: 2016-01-17 15:26:15 V2.4237`

`Browser: Google Chrome Versie 47.0.2526.111 m`
`Browser: MS Edge 25.10586.0.0`

**Comment by gizmocuz** [comment]
Please use our forum
