### ISSUE TITLE
Buienradar thresholds will not stick in user interface

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3600]
when changing the threshold settings(eg 25% to 45%) and press UPDATE. the change seems to stick and buienradar worker is stopped and started

however when we go to the main domoticz menu and back again to the hardware menu the settings are back to default 15 minutes and 25%

either the settings do not stick or the user interface does not update its settings when buienradar is selected'again in the hardware menu

there is no refresh button so 

![image](https://user-images.githubusercontent.com/16853535/64160358-1b20ba00-ce3c-11e9-92b2-90cc1a959da4.png)

**Comment by gizmocuz** [comment]
Thanks for reporting...
