### ISSUE TITLE
Buienradar: option to choose lon/lat location for more accurate rain prediction/fall

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3601]
i noticed that buienradar HW implementation chooses a "buienradar" measuring station which is as close as possible to your gps location.

they have approx 52 measuring stations but it is impossible to get a station really close to your location (unless you are one of the happy few who live on top of a station)

this is not problem for winspeeed and temp but since rain is local this makes a lot of difference.

The old buienradar script used a link in which you could put in your  GPS(lon/lat) location .
i have a feeling that this reading was more accurate.

Question. can this be implemented in the HW buienradar 
maybe an option to choose from native measuring station to local rain prediction

This is the curl link used in the script
lon/lat can easilly be imported from the domoticz settings page.

curl --max-time 3 -L -s 'https://gpsgadget.buienradar.nl/data/raintext?lat=" .. lat .. "&lon=" .. lon .. "'"

in case the data from the link is exactly the same as the data coming from the measuring station then ofcourse it makes no sense but looking at the screens when rain is falling at my location i do not see a lot happening right now (and it is pooring badly)

For you information
My location is ALKMAAR and Buienradar is using BERKHOUT STATION
thanks

**Comment by gizmocuz** [comment]
How come ? Domoticz is using the GPS location entered in the settings and finds the closest station.
Based on the location of the stations and your location the closest station will be calculated and used

**Comment by GravityRZ** [comment]
ok so the data coming from the link and the data from the closest station are the same

eg the link also takes data from the closest station based on the lon/lat input.

like i said, it is raining a lot outside but i hardly see any activity in domoticz
the closest measuringstation is approx 25km away so that should make sense

**Comment by gizmocuz** [comment]
Best to get yourself a 433Mhz rain sensor

**Comment by GravityRZ** [comment]
indeed that is a really good idea(why did i not think of that)

thanks

will close this one

**Comment by gizmocuz** [comment]
@GravityRZ , just to recap this:

1. The "buienradar" implementation in Domoticz uses the closest measurement station it can find based on your GPS location for the weather sensors
2. For the 'will it rain' measurement, your GPS location is also used

Those are two different URL's queries (as you might know), and can see in the code

The first one (temp,wind, uv, ....) you find OK, but for the second one, you find it not ok ?
There is no calculation in the second one, it is just your GPS coordinates and the URL you mentioned.

So you have two options:
1. Install a local weather station (i can recommend a Alecto WS5500, it is 868Mhz)
2. Enter a different GPS location in the settings

**Comment by GravityRZ** [comment]
Ok clear. So the readings should be the same but i have the idea that there is less rain falling then before(using the script and same gps location) while it actually is raining a lot at my location

**Comment by gizmocuz** [comment]
Most people would consider this to be a good thing ;)
It's the same url as it has been for years
