### ISSUE TITLE
png not transparent any more in the latest beta Version: 4.11254

### ISSUE THREAD

**Issue by a3vd** [domoticz/domoticz#3605]
Version: 4.11254

In the latest two version (after introducing svg) my transparent png images are not transparent any more, but transparent is changed in white color :-(
![Knipsel](https://user-images.githubusercontent.com/29863575/64339240-de8fc280-cfe3-11e9-9055-dffeb105dd3d.PNG)

**Comment by sincze** [comment]
Looks like: [#3593 ](https://github.com/domoticz/domoticz/issues/3593)
Nice Floorplan ;-)

**Comment by gizmocuz** [comment]
Same issue, indeed nice plan ;)
