### ISSUE TITLE
GAS support for Belgian smart meter (fluvius)

### ISSUE THREAD

**Issue by ThibautVos** [domoticz/domoticz#3606]
Hi,

The Belgian smart meter implementation for the gas reading is different than the NL one:  in the telegram the GAS reading are on 0-1:24.2.3  instead of 0-1:24.2.1.
Can this be changed in the code, so the belgian implementation is also supported?

Thanks.

**Comment by gizmocuz** [comment]
@ThibautVos , is this already corrected? Could you add a small reason for closing the issue ?

**Comment by ThibautVos** [comment]
I found this issue "missed Belgian gas meter in previous commit #3603" which already solved it apparently.  However, is this commit already in the beta version on the site? (windows)

**Comment by gizmocuz** [comment]
Yes, the beta version 11280 has this patch.
Thanks for the feedback!

**Comment by ThibautVos** [comment]
Damn, than this does not solve my issue :-(

**Comment by gizmocuz** [comment]
Could you post a complete telegram here?

**Comment by ThibautVos** [comment]
!DA4F
/FLU5\253770234_A

0-0:96.1.4(50213)
0-0:96.1.1(3153414731313030303037313930)
0-0:1.0.0(190905142315S)
1-0:1.8.1(000244.844*kWh)
1-0:1.8.2(000226.027*kWh)
1-0:2.8.1(000139.553*kWh)
1-0:2.8.2(000045.390*kWh)
0-0:96.14.0(0001)
1-0:1.7.0(00.000*kW)
1-0:2.7.0(00.198*kW)
1-0:32.7.0(240.0*V)
1-0:31.7.0(002*A)
0-0:96.3.10(1)
0-0:17.0.0(999.9*kW)
1-0:31.4.0(999*A)
0-0:96.13.0()
0-1:24.1.0(003)
0-1:96.1.1(37464C4F32313139303137303532)
0-1:24.4.0(1)
0-1:24.2.3(190905142001S)(00071.724*m3)
!0F77

**Comment by ThibautVos** [comment]
I see this in the log of Domoticz, so no gas readings: 
```
2019-09-05 15:41:15.846 (Fluvius smartmeter) General/Voltage (Voltage L1)
2019-09-05 15:41:15.230 Status: P1 Smart Meter: Using serial port: COM5
2019-09-05 15:41:15.249 Status: P1 Smart Meter: Worker started...
2019-09-05 15:41:15.826 Status: P1 Smart Meter: Meter reports as ESMR 5.0.2
2019-09-05 15:41:15.826 Status: P1 Smart Meter: Found gas meter on M-Bus channel 1
2019-09-05 15:41:16.835 (Fluvius smartmeter) P1 Smart Meter (Power)
2019-09-05 15:41:16.842 (Fluvius smartmeter) General/Voltage (Voltage L1)
2019-09-05 15:41:17.847 (Fluvius smartmeter) P1 Smart Meter (Power)
2019-09-05 15:41:17.859 (Fluvius smartmeter) General/Voltage (Voltage L1)
2019-09-05 15:41:18.844 (Fluvius smartmeter) P1 Smart Meter (Power)
2019-09-05 15:41:18.855 (Fluvius smartmeter) General/Voltage (Voltage L1)
```

**Comment by gizmocuz** [comment]
Do you get a gas reading every 10 seconds ? On my meter it is once every hour

**Comment by ThibautVos** [comment]
In each telegram the gas reading is included:
```
!3A59
/FLU5\253770234_A

0-0:96.1.4(50213)
0-0:96.1.1(3153414731313030303037313930)
0-0:1.0.0(190905161043S)
1-0:1.8.1(000244.847*kWh)
1-0:1.8.2(000226.027*kWh)
1-0:2.8.1(000140.679*kWh)
1-0:2.8.2(000045.390*kWh)
0-0:96.14.0(0001)
1-0:1.7.0(00.000*kW)
1-0:2.7.0(00.468*kW)
1-0:32.7.0(240.1*V)
1-0:31.7.0(002*A)
0-0:96.3.10(1)
0-0:17.0.0(999.9*kW)
1-0:31.4.0(999*A)
0-0:96.13.0()
0-1:24.1.0(003)
0-1:96.1.1(37464C4F32313139303137303532)
0-1:24.4.0(1)
0-1:24.2.3(190905161002S)(00071.777*m3)
!EEE9
```

**Comment by gizmocuz** [comment]
Then it should work...
I added your sample in the project, @gordonb3, is it possible you could have a look ?
In the P1 serial class you can enable the debug at the top, when you add a dummy P1 serial it might help debugging this ...
I was not able to call 'ParseP1Data', it did not want to take any character and it seems m_linecount = 0...

**Comment by gordonb3** [comment]
My bad. I mistakenly tried to match the number 1 instead of the character '1'. Addressed in PR #3607 

The above telegram is actually corrupted. I took the liberty to repair it in that same PR. The reason that you did not see any message returned on that is because the snippet starts with an end-of-telegram and ParseP1Data() does not handle cascaded telegrams - it stops after the first one which in this case happens to be empty.

**Comment by gizmocuz** [comment]
Thanks for the fast fix 😁👍

**Comment by ThibautVos** [comment]
Works perfect!! Thanks for the support!!
