### ISSUE TITLE
Buienradar rainfall next hour actually is rainfall LAST hour

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3608]
i would suspect that rainfall next hour would show us a forcast for what's coming but it is not

in fact it is showing what might have been falling last hour(we have the rain device for that)

link https://gpsgadget.buienradar.nl/data/raintext?lat=xx&lon=xx shows the old forecast which the script implementation was using.
maybee we can use this to fill in the rainfall next hour
might be difficult to update a prediction which changes over time

![image](https://user-images.githubusercontent.com/16853535/64362865-91c1e100-d00f-11e9-8d7c-87db20a2c766.png)

**Comment by rwaaren** [comment]
> i would suspect that rainfall next hour would show us a forcast for what's coming but it is not
> in fact it is showing what might have been falling last hour(we have the rain device for that)

Can you please explain why you come to this conclusion ?
If I look at the code ( V4.11284) the Rainfall next Hour device is updated using data from https://gpsgadget.buienradar.nl/data/raintext?lat=xx&lon=xx 

But maybe I misunderstand your issue ?

**Comment by GravityRZ** [comment]
ok, it is a good thing that that link is being used.

my problem is this
when i check that link now i see a forecast from 21:20 until 23:15
![image](https://user-images.githubusercontent.com/16853535/64374225-a60fd900-d023-11e9-908f-c708b898d058.png)


when i look at the same time at the domoticz device i see this graph.
it does not show me what is coming. it shows me what has passed.(eg graph stops at 20:00 and it needs to go to at least 2 hours ahead)
i like to see the expected rainfall.(so  a headsup of what is coming)


buienalarm does something similar which is working extremely accurate on my iphone.

![image](https://user-images.githubusercontent.com/16853535/64374255-b88a1280-d023-11e9-8b5e-cd05a7b717ba.png)

**Comment by gizmocuz** [comment]
What you see in the graph is the expected rain in the upcoming 15 minutes (or whatever you entered as a timeframe)
So at (it's a bit hard to read), 04:30 you can expect 0.2mm of rain
We can not inject data from the feature... nor has this been done from any script before
You can use this value to control your blinds/switches/....

**Comment by GravityRZ** [comment]
ok i understand that we can not project data into the future.

"Rainfall prediction" might be a better default name than "Rainfall next hour"  

The "Rain" device is what actually has been fallen (according to Buienradar)

still i think there is a problem

right now it is raining and the link shows
![image](https://user-images.githubusercontent.com/16853535/64433002-e9b72100-d0bd-11e9-8673-798c3b3357df.png)


domoticz does not show anything
is it going to rain switch 0
rain 0
rain next hour 0

devices do get timestamps

so the link works but somehow i do not think it is being used in domoticz(unless you fixed things shorly)
i am on build 11280, waiting for build 290 to test

![image](https://user-images.githubusercontent.com/16853535/64433099-1bc88300-d0be-11e9-867e-e583e7f28fed.png)

**Comment by GravityRZ** [comment]
so lets do  a test
this is coming from the link. let's see what is appearing in rainfall next hour. it should show us a lot of rain at different times because you state it gets the data from the same link.
will post the rainfall next hour graph after lets say 1 hour
![image](https://user-images.githubusercontent.com/16853535/64434525-02750600-d0c1-11e9-9c76-65e654c15b6a.png)

This is what we should see
![image](https://user-images.githubusercontent.com/16853535/64435548-f7bb7080-d0c2-11e9-924b-a7dd33691811.png)

and what we actually see from the rain next hour device until 17:30 is nothing
going to install build 290 to see if it helps
the only device which shows something of interest is rain percentage
![image](https://user-images.githubusercontent.com/16853535/64438652-c2b21c80-d0c8-11e9-9d7f-2b3b9ded52a9.png)

**Comment by gizmocuz** [comment]
First of, there are two different sensors created:

Rain Intensity, this is based on the timeframe,
Rainfall next Hour, this is the total rain expected in the next hour in mm/h

of course both are predicted

Note the rainfall next hour is in mm/h, no way this will be 92 ! 

double rain_mm_hour = (rain_avg == 0) ? 0 : pow(10, ((rain_avg - 109) / 32));

Do not that it's an average 

double rain_avg = total_rain_next_hour / total_rain_values_next_hour;

Again have a look in the source code, and feel free to play around with it, and if needed create a PR

**Comment by GravityRZ** [comment]
ofcourse i understand that 92 is not 92mm

what i would expect is that the prediction pattern from the link also appears in one of the devices(currently i do not see this)

installed build 11290 so let's wait for some rain.

regarding the thresholds (default 15 minutes and 25%) do they only affect the is it going to rain switch or also the devices

**Comment by GravityRZ** [comment]
i looked at the code (and i am not a programmer

looking good
> define BUIENRADAR_RAIN "https://gadgets.buienradar.nl/data/raintext/?lat=" // + m_szMyLatitude + "&lon=" + m_szMyLongitude;

is this not double up regarding attaching lat and lon to the string

> std::string szUrl = BUIENRADAR_RAIN + m_szMyLatitude + "&lon=" + m_szMyLongitude;

**Comment by rwaaren** [comment]
Couple of remarks: in the C++ code line 
`define BUIENRADAR_RAIN "https://gadgets.buienradar.nl/data/raintext/?lat=" // + m_szMyLatitude + "&lon=" + m_szMyLongitude;`
everything behind // is a comment

the return from Buienradar is to be read as follows. 
0 is no rain, 255 is very heavy rain
When needed, mm/h it can be calculated by the formula 10^((value -109)/32))
so 
77 = 0,1 mm/h
87 = 0,2 mm/h
92 = 0,3 mm/h
115 = 1,5 mm/h

My interpretation of the code: 
depending on your settings in the buienradar hardware the average is the sum of the values during the time set / time. Example if your time set = 15 minutes and the values for these 15 minutes are 0.1, 0.2 and 0.3, the average that you will see on the graph is 0.2
If the next prediction (after 5 minutes) is 0,2, 0.0, 0.0 the next point of the graph will be 0.1 (rounded from 0.066)

My graph seems to be accurate 
![image](https://user-images.githubusercontent.com/24454798/64461311-23f3e300-d0fd-11e9-89a9-5f2eeac16e28.png)

**Comment by GravityRZ** [comment]
@rwaaren that is good info.(and yes i am not a programmer so did not know about the //)
i was experimention with longer timeframes but those make the numbers even lower.
I will set the timeframe to 5 minutes 
can you tell me what the default timeframe was in the script?
I am looking at the code but i can not clearly see what is happening
it looks like it is looping through all the data from the site(2 hours of 5 minute  measurements) and the total average is the rainfall per 5 minutes all added up.

if this is the case then yes the script is showing  higher values(eg total rainfall for 2 hours) instead of average per timefrime

>         local c=0
        local rainNow=0
        local rainNowAvg = 0
        local rainSoon = 0
        local rainTime = ""
        local rainMax = 0
        for k,v in tmp:gmatch('(.-)|(.-)\r?\n') do
            -- k is rain value, v is time
            kn = tonumber(k)
            if c<=1 then
                if rainNow < kn then
                    rainNow = kn
                end
                if kn > 0 then
                    rainNowAvg = rainNowAvg + tomm(kn)/2
                end
            end
            if c<=3 and rainSoon < kn then 
                rainSoon = kn
            end
            if rainTime == "" and kn > 0 then
                rainTime = v
            end
            if kn > rainMax then
                rainMax = kn
            end
            c = c+1
        end

**Comment by rwaaren** [comment]
There are multiple versions of this Lua script and in the version you show here, the full two hours are used. Furthermore the result of this code only shows a value for rain intensity and does not say much about mm/h.

Having said this, I guess it's better to close this issue and if needed continue the discussion on the forum as it is no domoticz code issue .

**Comment by GravityRZ** [comment]
ok clear. i will close this one. at the moment it seems a lot more is happening when i put timeframe to 90 minutes.
