### ISSUE TITLE
LUA 'device' scripts are logged BEFORE the triggering event

### ISSUE THREAD

**Issue by soif** [domoticz/domoticz#361]
Domoticz v2.4268

When creating a LUA script which is triggered by a _devicechanged_ the LUA log entry appears **before** the _devicechanged_ log event entry.

IE :

```
2016-01-19 19:29:22.613 LUA : Device 'Test' as changed....
2016-01-19 19:29:22.611 (RFX usb) Temp + Humidity (Test)
```

_Notice the millisecond time value..._

It is not that important, but a bit confusing when debugging scripts ;-)
Keep up the amazing work !
HTH

**Comment by nayrnet** [comment]
I believe this is by design, If you were to have a script causes the system to hang/crash you will have the culprit in the logs.. If it were logging after or while its firing off an event you'd never figure out what was locking your system up... bad scripts can cause all sorts of unexpected behavior.

**Comment by soif** [comment]
Thank you for the amazing fast answer ;-)

I don't understand, why logging LUA before the triggering event is helpful whenever the LUA script causes a crash. Can you explain? (maybe my description is not clear enough)

**Comment by nayrnet** [comment]
if an event causes the process to deadlock or crash, it will not be able to execute any tasks.. such as writing to a log file.. if its written a few millaseconds before firing off an event; the log output will be saved regardless of the outcome of the event script.

current behavior in a crash:
`2016-01-19 19:29:22.613 LUA : Device 'Test' as changed....
 *** SEGFAULT ***`

either way I doubt anyone will change this behavior.. just cope with it is my advice, you'll find stuff like this is common with threaded applications.

**Comment by soif** [comment]
> if an event causes the process to deadlock or crash, it will not be able to execute any tasks.

Right! But if the event crashes it will then not log itself, nor logs the LUA script, because it crashed before it could trigger the script ...

> if its written a few milliseconds before firing off the script the log output will be there regardless...

So I will know that this event has caused a crash, and then not triggered the LUA script

If the event would be logged BEFORE my script and If the event did not crashed, but my script did crashed, at least I would see in the logs the latest event before my script causes the crash, no?

Am I totally misunderstanding what you say ???

**Comment by soif** [comment]
I've just seen that you edited your last comment.. Maybe I'm just not understanding the behavior of threaded applications. Sorry about that.

**Comment by gizmocuz** [comment]
Please use the forum
