### ISSUE TITLE
After reboot raspberry domoticz doen't start (xiaomi gateway problem)

### ISSUE THREAD

**Issue by kitopopo** [domoticz/domoticz#3612]
Good morning everyone,

2 or 3 months ago, after some update of domoticz we have observed that after resetting the raspberry domoticz does not start (domoticz starts with offline dashboard ). if we have to restart the service manually ( sudo service domoticz.sh restart ) the problem is solved until the next raspberry reboot
Today I made an ascertainment, I had to reinstall domoticz and I observed that after its new installation domoticz always started well, after loading my backup of the database the same problem occurred again. I thought that the problem was produced by some external hardware. I have been removing my hardware and I have observed that removing the xiaomi gateway then domoticz always starts correctly after restarting the raspberry. If I add the xiaomi gateway again individually with another password and without add any devices, the problem occurs again.
It is not necessary to remove the hardware from the gateway, simply disabling the xiaomi gateway domoticz starts well. 
This problem occurs in the latest stable and beta versions.
There are many users who have this same problem. Could it be that there is some kind of incompatibility between domoticz and the gateway produced in some update? Could you fix this problem in some new update? thanks in advance and best regards

**Comment by gizmocuz** [comment]
You have to ask the author of this class. It is also not written in a way that is normally used
(Looking for instance at the code in StartHardware , requesting configuration parameters from the database that could have been passed to the constructor!?)
Maybe everything could be started in Do_Work, after at least 10 seconds ?
Maybe there is something not ready when booting the system and this class needs a startup delay

**Comment by kitopopo** [comment]
> You have to ask the author of this class. It is also not written in a way that is normally used
> (Looking for instance at the code in StartHardware , requesting configuration parameters from the database that could have been passed to the constructor!?)
> Maybe everything could be started in Do_Work, after at least 10 seconds ?
> Maybe there is something not ready when booting the system and this class needs a startup delay

Hi, thanks for your help. I don't know how to contact the author, for this reason I have published the problem here. Hopefully the developer can see it or maybe github can get the problem. 
The problem is probably solved by adding a delay of several seconds at startup. Some colleague has also told me that this is solved. But in my view I think I could investigate and add this delay. But I think this is not the solution. The problem appeared after some update several months ago, therefore I think it should be solved in some new update. Best regards and thanks again.

**Comment by kitopopo** [comment]
Because I had no answers, I analyzed the syslog file in two different restarts of raspberry pi4. In the first reboot I have disabled the xiaomi gateway in domoticz and it starts perfectly, the domoticz.sh service [451] is called correctly. please, see the pictures. first i can see the domoticz version and after the build.

In the second reboot I have re-enabled the xiaomi gateway, the photo shows the same part of the boot and in all the syslog nobody invokes domoticz.sh [451] or domoticz.sh[451] is not executed.

Why does Domoticz start with the xiaomi gateway disabled? I am not a programmer to find out what happens, and I don't think anyone else has this problem. If there is an update almost every day of the beta version of domoticz because the developers do not correct the problem ?. A mystery.

![starts](https://user-images.githubusercontent.com/51416982/65380360-4deefd00-dcda-11e9-824f-6bf5dcce0c93.jpg)

![not start](https://user-images.githubusercontent.com/51416982/65380361-58a99200-dcda-11e9-888f-5b36503ac338.jpg)

can anybody help me? I think it is essential that domoticz start up correctly on a restart and it is not correct to have scripts that run every "x" minutes to monitor domoticz and lift the service. I would like to have a "Stable" domoticz.

 Thanks in advancee

**Comment by rwaaren** [comment]
I was able to more or less replicate this on my test Raspberry 4 with Debian buster, locally compiled domoticz V4.11331 and V4.11334. 
On a running domoticz I installed Xiaomi hardware and my devices were found and added to the system.
After a shutdown -r , the system boots and domoticz does automatically start but aborts as soon as the Xiaomi hardware is initialized.  Logmessages:
```
2019-09-22 22:37:41.412  Status: XiaomiGateway (ID=6): Worker started...
2019-09-22 22:37:41.429  Status: XiaomiGateway (ID=6): Could not detect local IP address using Boost.Asio: resolve: Host not found (authoritative)
2019-09-22 22:37:41.429  Status: XiaomiGateway (ID=6): XiaomiGateway IP address starts with: 192.168.192
2019-09-22 22:37:41.430  Error: XiaomiGateway: system
2019-09-22 22:37:41.431  Error: Domoticz(pid:635, tid:1009('Xiaomi')) received fatal signal 6 (Aborted)
2019-09-22 22:37:41.412  Status: XiaomiGateway (ID=6): Worker started...
2019-09-22 22:37:41.429  Status: XiaomiGateway (ID=6): Could not detect local IP address using Boost.Asio: resolve: Host not found (authoritative)
2019-09-22 22:37:41.429  Status: XiaomiGateway (ID=6): XiaomiGateway IP address starts with: 192.168.192
2019-09-22 22:37:41.430  Error: XiaomiGateway: system
2019-09-22 22:37:41.431  Error: Domoticz(pid:635, tid:1009('Xiaomi')) received fatal signal 6 (Aborted)
```
If I manually remove the Xiaomi hardware entry from the database after this abort domoticz starts without problem.

Looking at these messages it looks like the Hardware tries to use a network resource that is not (yet) available.
To test this I added the lines
```
	#Wait for network adapters to be available
        while [ 1 ]; do   if [ $(ip add sh dev wlan0 | grep inet | wc -l) -ne 0 ]; then      break;   fi   ;sleep 1 ;done
        while [ 1 ]; do   if [ $(ip add sh dev eth0 | grep inet | wc -l) -ne 0 ]; then      break;   fi   ;sleep 1 ;done
```
to /etc/init.d/domoticz.sh 
at the begin of the do_start() function. 
After this I rebooted my PI-4 a couple of times and every time domoticz start without problems with the Xiaomi gateway included.

Now I am pretty sure this is not the preferred method of doing this but it will do until it is fixed using the proper commands .

NB. please note that the line with wlan0 should only be used if you are activated the wireless network adapter on your PI.

**Comment by kitopopo** [comment]
Hello Goodnight. I am very happy to have found someone who has the same problem as me. I tried what you said and added those 2 lines in the domoticz.sh file and indeed after several reboots it always starts well now. 
(Yesterday it was late for me and I only found that the service did not start, I was not able to find that the service started and then stopped. I also agree with you that this is not the solution but for now it works very well and corrects the problem. I haven't been with raspberry and linux for a long time, I'm learning day by day and I'm making progress) 
Now let's wait to see if in the following updates the developers solve the problem that domoticz starts before eth0 is available. Many thanks. I believe that your solution will help many people who also have the same problem. Thanks again. A cordial greeting.

**Comment by rwaaren** [comment]
I looked a bit further into this and noticed that some parts of systemctl where not active on my PI4. To correct this, I did the following:

`sudo systemctl edit systemd-networkd-wait-online.service 
`
This will open an editor with an empty file. Add the following lines:

```
[Service]
ExecStart=
ExecStart=/lib/systemd/systemd-networkd-wait-online --interface=eth0 --interface=wlan0 --timeout=25
```

(Yes 2 times ExecStart=) and save the file.

```
sudo systemctl start systemd-networkd
sudo systemctl enable systemd-networkd
```
Commented the two previously added lines in /etc/init.d/domoticz.sh and rebooted the PI.

For now it does seem to do the job. Not sure if this should be done by the domoticz installation script for PI-4 system or that it should be part of default installation or Debian buster.

**Comment by kitopopo** [comment]
> I looked a bit further into this and noticed that some parts of systemctl where not active on my PI4. > Not sure if this should be done by the domoticz installation script for PI-4 system or that it should be part of default installation or Debian buster.

Goodnight dear friend,

I just tried your second provisional solution relationship and it also works. Both solutions works correctly. 

In this second solution I understand that we have created a service in raspbian that plays with the time of eth0  instead of modifying the domoticz boot file (domoticz.sh). i can not understand completely the second solution but its works correctly. i need study "Execstart" and "timeout" parameters.

In any case, I imagine that some moderator of github will transfer the problem to whom it may concern, either to the developers of domoticz or the developers of raspbian buster. Maybe both developers can read the problem here in github forum and find a definitive solution in future updates. 

Thanks again for your help, you have been very kind. best regards.

This morning I have updated to the version of domoticz V.411337. In the micro sd card that I am currently using, I do not have any of your 2 provisional solutions activated. I have restarted my raspberrypi4 five times and the 5 times domoticz has booted correctly. I have opened
domoticz.sh and I have verified that I do not have your 2 lines added, and I have also verified that the "systemd-networkd" service is turned off. just in case I executed on the command line: sudo systemctl stop systemd-networkd. I also have not activated my script that monitors that
domoticz is running every 5 minutes. Mysteriously it works well today. Maybe they have solved the problem in today's update. Can you check if domoticz starts correctly? if you corroborate that it starts correctly, I give the issue of github for resolved.

**Comment by kitopopo** [comment]
> I looked a bit further into this and noticed that some parts of systemctl where not active on my PI4. To correct this, I did the following:
> 
> `sudo systemctl edit systemd-networkd-wait-online.service `
> This will open an editor with an empty file. Add the following lines:
> 
> ```
> [Service]
> ExecStart=
> ExecStart=/lib/systemd/systemd-networkd-wait-online --interface=eth0 --interface=wlan0 --timeout=25
> ```
> 
> (Yes 2 times ExecStart=) and save the file.
> 
> ```
> sudo systemctl start systemd-networkd
> sudo systemctl enable systemd-networkd
> ```
> 
> Commented the two previously added lines in /etc/init.d/domoticz.sh and rebooted the PI.
> 
> For now it does seem to do the job. Not sure if this should be done by the domoticz installation script for PI-4 system or that it should be part of default installation or Debian buster.

Hi dear friend,

this morning I have updated to the version of domoticz V.411337. In the micro sd card that I am currently using, I do not have any of your 2 provisional solutions activated. I have restarted my raspberrypi4 five times and the 5 times domoticz has booted correctly. I have opened domoticz.sh and I have verified that I do not have your 2 lines added, and I have also verified that the "systemd-networkd" service is turned off. just in case I executed on the command line: sudo systemctl stop systemd-networkd. I also have not activated my script that monitors that domoticz is running every 5 minutes.
Mysteriously it works well today. Maybe they have solved the problem in today's update. Can you check if domoticz starts correctly? if you corroborate that it starts correctly, I give the issue of github for resolved.

Thanks in advance.

**Comment by rwaaren** [comment]
Please be aware that  sudo systemctl stop systemd-networkd. only stops this service until the next reboot. To disable you have to use  sudo systemctl disable systemd-networkd
You can check that using the command . sudo systemctl status systemd-networkd after a reboot.
If I disable the systemd-networkd, I still see domoticz crashing as soon as the Xiaomi hardware gets initialized.
I am also on V4.11337 and looking at the commits (using git log) I don't see any changes that could have solved this issue .In my opinion, enabling systemd-networkd with the settings as above is a
solution for Raspberry Pi-4 with buster. Question is how to ensure this setting (only during domoticz installation or at every start) 
Hope @gizmocuz can share his thoughts on this.

**Comment by kitopopo** [comment]
> Please be aware that sudo systemctl stop systemd-networkd. only stops this service until the next reboot. To disable you have to use sudo systemctl disable systemd-networkd You can check that using the command . sudo systemctl status systemd-networkd after a reboot. If I disable the systemd-networkd, I still see domoticz crashing as soon as the Xiaomi hardware gets initialized. I am also on V4.11337 and looking at the commits (using git log) I don't see any changes that could have solved this issue .In my opinion, enabling systemd-networkd with the settings as above is a solution for Raspberry Pi-4 with buster. Question is how to ensure this setting (only during domoticz installation or at every start) Hope @gizmocuz can share his thoughts on this.

Hello, domoticz effectively continues to fail with the latest update. As I have several micro SD cards I was testing with one in which I had deactivated "sudo systemctl disable systemd-networkd" but had activated the 2 lines in domoticz.sh. we have 2 domoticz.sh files. One file inside the domoticz folder and another inside the /etc/init.d/domoticz.sh folder. I had looked in the wrong domoticz.sh (/domoticz/domoticz.sh) the two lines were not added heare and and I thought wrongly that the problem had been solved, but really the 2 lines were added in the file /etc/init.d/domoticz.sh.
my mistake sorry. For this reason I quickly deleted the message in the forum but you had already received the reply email. Thank you very much anyway and we are still waiting to see if  @gizmocuz comments his thoughts. Thank you. Greetings

**Comment by kitopopo** [comment]
> I looked a bit further into this and noticed that some parts of systemctl where not active on my PI4. To correct this, I did the following:
> 
> `sudo systemctl edit systemd-networkd-wait-online.service `
> This will open an editor with an empty file. Add the following lines:
> 
> ```
> [Service]
> ExecStart=
> ExecStart=/lib/systemd/systemd-networkd-wait-online --interface=eth0 --interface=wlan0 --timeout=25
> ```
> 
> (Yes 2 times ExecStart=) and save the file.
> 
> ```
> sudo systemctl start systemd-networkd
> sudo systemctl enable systemd-networkd
> ```
> 
> Commented the two previously added lines in /etc/init.d/domoticz.sh and rebooted the PI.
> 
> For now it does seem to do the job. Not sure if this should be done by the domoticz installation script for PI-4 system or that it should be part of default installation or Debian buster.

Hi dear friend,

I have found another way to solve the problem without needing additional services or modifying domoticz.sh.
In the "start" menu of our raspberry pi 4 if we select preferences and then enter the configuration of the raspberry pi we can find an option called "network at startup", if we check this box domoticz starts correctly after a restart.
We confirm again that this is a network problem caused by domoticz startup or raspbian boot.

Best regards

**Comment by EDsteve** [comment]
> In the "start" menu of our raspberry pi 4 if we select preferences and then enter the configuration of the raspberry pi we can find an option called "network at startup", if we check this box domoticz starts correctly after a restart.

How would you do that with the command line?

**Comment by rwaaren** [comment]
sudo apt install raspi-config
sudo raspi-config

1 system options
   6 network at boot

**Comment by EDsteve** [comment]
> sudo apt install raspi-config
> sudo raspi-config
> 
> 1 system options
> 6 network at boot

Cool. Thanks. On my Pi it is:

3 Boot options
B2 Wait for network at boot
