### ISSUE TITLE
buienrader: Rain device suddenly shows negative numbers

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3613]
currently running build 22290.

All was looking really good for 2 days (saturday and sunday)
all of a sudden i checked and the rainfall seems to have changed to negative.
this was still normal this afternoon

![image](https://user-images.githubusercontent.com/16853535/64492846-1e230c80-d279-11e9-980d-5f6e96774208.png)

**Comment by gizmocuz** [comment]
Okey found the issue...
We are using the rain field 'rainFallLast24Hour'

This is the database:

![image](https://user-images.githubusercontent.com/2265299/64508402-a509d080-d2dd-11e9-905d-8ce9f3980971.png)

A 'normal' rain station (zwave/433/868Mhz) has a continues counter, this one wraps, at buienradars clock
Domoticz is using it's own clock

If you look in Buienradar.cpp, I tried to avoid issues here (~ line 434-452), but I guess it's not 100% safe

And to top it off, we poll every 10 minutes, so here is the issue

Made some modifications, please try beta 10295

Please note, if the rain toay is less then the first value of today (because of the loop, mine was 2.7), today's total will be 2.7

**Comment by GravityRZ** [comment]
ok tested it with 11298 but the graphics still show negative
cleared cache. do i need to reset something else

![image](https://user-images.githubusercontent.com/16853535/64540783-fdae8d00-d320-11e9-8553-93414b08858f.png)

**Comment by gizmocuz** [comment]
@GravityRZ , yes wait 24 hours, they will move out

**Comment by GravityRZ** [comment]
ok. had some idea it would do that.

**Comment by GravityRZ** [comment]
could this be coincidence

i updated to 11298 but now i see all the graphs are flat since 12:00.(updated around 17:00) could this be a side effect of the update.
devices are updated but not every 5 minutes but later (10 minutes or longer  i think)


![image](https://user-images.githubusercontent.com/16853535/64559872-8f30f580-d347-11e9-9878-f1e29c1d06fa.png)

**Comment by GravityRZ** [comment]
checked the json link
i can access it and the values in there are the same as in domoticz.
This must mean that station Berkhout is sending out the wrong info. at least is does not change.
Maybee somebody should go up there and replace the batteries

[quote]{"$id":"6","stationid":6249,"stationname":"Meetstation Berkhout","lat":52.65,"lon":4.98,"regio":"Berkhout","timestamp":"2019-09-09T21:20:00","weatherdescription":"Vrijwel onbewolkt (zonnig/helder)","iconurl":"https://www.buienradar.nl/resources/images/icons/weather/30x30/a.png","graphUrl":"https://www.buienradar.nl/nederland/weerbericht/weergrafieken/a","winddirection":"WZW","temperature":16.7,"groundtemperature":18.5,"feeltemperature":16.7,"visibility":32500.0,"windgusts":6.8,"windspeed":4.4,"windspeedBft":3,"humidity":58.0,"precipitation":0.0,"sunpower":629.0,"rainFallLast24Hour":0.0,"rainFallLastHour":0.0,"winddirectiondegrees":241},
[/quote]

**Comment by GravityRZ** [comment]
checked this morning. the station is gone after 02:00
after that it is complaining about the internet connection(because it can not find the station)
stopped/started the worker and now it is picking up another station

so still no feedback on the negative graphics since not enough time has passed

**Comment by gizmocuz** [comment]
@GravityRZ , would you please do not mix issues, this is not related to negative values in the rainfall shotlog graph

This is also not the forum.
Always best before posting, to check the recent changes in the commit log to see if it have could affect your issue at least.

https://github.com/domoticz/domoticz/commits/development

**Comment by GravityRZ** [comment]
agreed but at the time of posting i did not know it was not related.

i know you changed something which affected negative graphs and all of a sudden my graphs are behaving strange.

who would have thought that at the same time this particular station would go down.

![image](https://user-images.githubusercontent.com/16853535/64594535-86283e80-d3b0-11e9-9b4f-2d1b62024572.png)

hopefully it will stay positive

**Comment by GravityRZ** [comment]
was positive yesterday but now again negative. so the fix did not help

![image](https://user-images.githubusercontent.com/16853535/64672762-a61d3800-d46c-11e9-8128-1dd03b3f9144.png)

**Comment by gizmocuz** [comment]
@GravityRZ , hmmm could you show me the first few records of the day form the rain short-log table ?
(Like i did above)

**Comment by GravityRZ** [comment]
this is from the rain device

> 

DateTime | mm
-- | --
10-9-2019 10:00 | -1,30
10-9-2019 11:00 | 0,00
10-9-2019 12:00 | 0,00
10-9-2019 13:00 | 0,00
10-9-2019 14:00 | 0,00
10-9-2019 15:00 | 0,00
10-9-2019 16:00 | 0,00
10-9-2019 17:00 | -0,10
10-9-2019 18:00 | 0,00
10-9-2019 19:00 | 0,00
...
10-9-2019 20:00 | 0,00
11-9-2019 9:00 | 0,40


and this from the rainfail next 24 hours

> 

DateTime | Custom Sensor
-- | --
10-9-2019 9:20 | 0,00
10-9-2019 9:25 | 0,00
...
10-9-2019 9:30 | 0,00
10-9-2019 12:05 | 0,70
10-9-2019 12:10 | 0,60
10-9-2019 12:15 | 1,00
10-9-2019 12:20 | 1,30
10-9-2019 12:25 | 1,20
10-9-2019 12:30 | 1,00
10-9-2019 12:35 | 0,80
10-9-2019 12:40 | 0,70
10-9-2019 12:45 | 0,40
...
10-9-2019 12:50 | 0,20

**Comment by gizmocuz** [comment]
@GravityRZ , thanks ! But i' confused now... Rain/Rainfall ... those are two different sensors ?
How is your sensor with Type=Rain, Subtype=WWW (default name was <Location> Rain) ?

**Comment by GravityRZ** [comment]
yes correct
i have 2 devices and send you the info for both devices just in case you need them (if they are related)
Rain, the one which shows negative graphs(at the moment they are positive again
Rainfall next Hour, the which shows the last 24 hours

![image](https://user-images.githubusercontent.com/16853535/64680245-b558b180-d47d-11e9-9fc9-56f3581b4afe.png)

i see i used the wrong title. it is not about rainfall next hour device but about the Rain device
i will change the title(very confusing if we use last hour and next hour in different devices)

**Comment by GravityRZ** [comment]
right now it shows positive again

> 

DateTime | mm
-- | --
10-9-2019 11:00 | 0,00
10-9-2019 12:00 | 0,00
10-9-2019 13:00 | 0,00
10-9-2019 14:00 | 0,00
10-9-2019 15:00 | 0,00
10-9-2019 16:00 | 0,00
10-9-2019 17:00 | -0,10
10-9-2019 18:00 | 0,00
10-9-2019 19:00 | 0,00
10-9-2019 20:00 | 0,00
10-9-2019 21:00 | 0,00
10-9-2019 22:00 | 0,00
10-9-2019 23:00 | 0,00
11-9-2019 0:00 | 0,00
11-9-2019 1:00 | 0,00
11-9-2019 2:00 | 0,00
11-9-2019 3:00 | 0,00
11-9-2019 4:00 | 0,00
11-9-2019 5:00 | 0,00
11-9-2019 6:00 | 0,00
11-9-2019 7:00 | 0,00
11-9-2019 8:00 | 0,00
11-9-2019 9:00 | 0,40
11-9-2019 10:00 | 1,10


![image](https://user-images.githubusercontent.com/16853535/64680677-87c03800-d47e-11e9-88d8-15ce0e6b02ef.png)

**Comment by gizmocuz** [comment]
I am not sure what table you show me...
And i do not understand the value at 10 September 17:00 (-0,10)

The Domoticz database has 4(5) fields:

(rowid) DeviceRowID, Total, Rate, Date

is this from the "Rain" table ?

Because that could not have a negative value

It takes snapshots from the 'DeviceStatus' table, which is filled in **MainWorker::decode_Rain**

`float TotalRain = float((pResponse->RAIN.raintotal1 * 65535) + (pResponse->RAIN.raintotal2 * 256) + pResponse->RAIN.raintotal3) / 10.0f;
`

where pResponse->RAIN.raintotal1 = 0

and raintotal1 ,raintotal2 and raintotal3 are BYTES (unsigned chars)

**Comment by GravityRZ** [comment]
no i got it from the device from within Domoticz.

when looking at the rain device i see this data
DeviceRowID, Total, Rate, Date
hopefully you mean this
> 

> 313	0.1	0	2019-09-10 14:20:00
313	0.1	0	2019-09-10 14:25:00
313	0.1	0	2019-09-10 14:30:01
313	0.1	0	2019-09-10 14:35:00
.....
313	0.1	0	2019-09-10 14:40:00

**Comment by gizmocuz** [comment]
That looks OK, okey, so now it is possible the plotting of the graph, internally in the database it seems to be fine
You can check this by using for example a great free tool "SQLite Expert personal edition"

Don't have lots of free time at the moment, but I will look into this unless someone beats me to it

**Comment by GravityRZ** [comment]
still happening

The minus value is -7.8
the wednesday value is +7.8 and i can say it did not rain at al at 20:00

coincidence that those values are the same!!!

![image](https://user-images.githubusercontent.com/16853535/64815270-6c9c1800-d5a5-11e9-92b8-2eff76b837c3.png)

**Comment by GravityRZ** [comment]
still  a problem.
this might be related to the last day copying issue(total of last day is copied to next day) because that exact value shows up negative al of a sudden.

so at one time the total rain of yestarday is copied to next day (eg 7.7 +0=7.7)
and on the top graphs i think it is substracted (0 -7.7= -7.7)

something like that


![image](https://user-images.githubusercontent.com/16853535/65146074-51a12c00-da1b-11e9-95d3-577bf1f8d91e.png)

**Comment by gizmocuz** [comment]
@GravityRZ , as mentioned, it could be a 'graph' issue, could you therefor also post the values from the shortlog from 23:00 till 01:00 ?
(At least, I hope its a graph issue)

**Comment by GravityRZ** [comment]
here it is
the first problem (copying the total to the next day) is clearly visible
looks like a date bug where the day runs until 00:15

mostly you see day/date bugs which run from 00:00-00:00(should be 00:00-23:59)

the value in the database at 01:00 seems to be ok

if it is a graph issue it is strange that i have it while the other user reporting things about copying the raintotal to the next day has not experienced this

i use 
> 313	9.4	0	2019-09-17 23:50:00
> 313	9.4	0	2019-09-17 23:55:00
> 313	9.4	0	2019-09-18 00:00:01
> 313	9.4	0	2019-09-18 00:05:00
> 313	9.4	0	2019-09-18 00:10:00
> 313	9.4	0	2019-09-18 00:15:00
> 313	0.0	0	2019-09-18 00:20:01
> 313	0.0	0	2019-09-18 00:25:00
> 313	0.0	0	2019-09-18 00:30:00
> 313	0.0	0	2019-09-18 00:35:00
> 313	0.0	0	2019-09-18 00:40:01
> 313	0.0	0	2019-09-18 00:45:00
> 313	0.0	0	2019-09-18 00:50:00
> 313	0.0	0	2019-09-18 00:55:00
> 313	0.0	0	2019-09-18 01:00:01
> 313	0.0	0	2019-09-18 01:05:00
> 313	0.0	0	2019-09-18 01:10:00
> 313	0.0	0	2019-09-18 01:15:00
> 313	0.0	0	2019-09-18 01:20:01
> 313	0.0	0	2019-09-18 01:25:00
> 313	0.0	0	2019-09-18 01:30:00
> 313	0.0	0	2019-09-18 01:35:00
> 313	0.0	0	2019-09-18 01:40:00
> 313	0.0	0	2019-09-18 01:45:00
> 313	0.0	0	2019-09-18 01:50:00
> 313	0.0	0	2019-09-18 01:55:01
> 313	0.0	0	2019-09-18 02:00:00

![image](https://user-images.githubusercontent.com/16853535/65160704-8373bc00-da36-11e9-99a6-1938476e2350.png)

**Comment by gizmocuz** [comment]
@GravityRZ , thanks for the log ! I think i found the issue
I did reset the internal rain counter, but the last value in the database was still the last totals

Could you test version 11323

Also have a look at the code if possible

**Comment by GravityRZ** [comment]
installed 11324  on thursday 19-9 No rain
installed 11332 on saturday 21-9 No rain.
Today 23-9-2019 finally some rain. graphs are positive
rain accumulation however is still wrong but will post that in the other issue



![image](https://user-images.githubusercontent.com/16853535/65448701-bf918d00-de39-11e9-81c8-4bdc2cb9f29e.png)

**Comment by GravityRZ** [comment]
and no the problem is still there

![image](https://user-images.githubusercontent.com/16853535/65531505-5887dd00-defa-11e9-9931-fa7e8f160ba8.png)

**Comment by GravityRZ** [comment]
and 1 hour later back to positive and the negative entry is gone
something really strane is going on.

![image](https://user-images.githubusercontent.com/16853535/65534648-2f6a4b00-df00-11e9-9649-f8f31b791405.png)

**Comment by GravityRZ** [comment]
still positive after 24 hours

![image](https://user-images.githubusercontent.com/16853535/65627338-73785100-dfcf-11e9-9bab-d8f10e85d375.png)

**Comment by gizmocuz** [comment]
@GravityRZ , there is no reason to repeat yourself as there have been no changes related to buienradar that you can easily check by going to the history of the buienradar file itself
Also have a look at the code please

**Comment by GravityRZ** [comment]
Not a question regarding repeating myself but more of supplying additional info. If this is not wanted and the problem is clear i will gladly stop posting new info.

**Comment by gizmocuz** [comment]
@GravityRZ , Thanks, as mentioned before... the problem is in the counter reset, and a small dump of the data in the database will display this (as you posted before)

Again (sorry, now I am repeating myself a lot in this post...) please have a look at the code !
You are posting on GitHub, not the Forum.

I just make another attempt to solve this issue in beta 11345
Could you also check your system time , maybe there is a big difference against the world time ? (like more then (or around) 5 minutes on your system ?

**Comment by GravityRZ** [comment]
checked again and issue is still there with buil 11354.
i can  not check the code because i am not a programmer.
i however noticed something strange.
the reading at 00:00 was blank the whole day, like the reading was missing. somewhere around 18:00 it changed into -5.1(total of the previous day) so it seems the plotting routine does not look at the data in the database (which is 0) but it somehow get's it's data somewhere else, maybe memory get's overwritten.

![image](https://user-images.githubusercontent.com/16853535/66328686-65122980-e92d-11e9-9527-1cd2aa91b7e2.png)

**Comment by gizmocuz** [comment]
Merged in 11367

**Comment by GravityRZ** [comment]
Not sure if this is fixed. there still is an empty spot at 01:00 but we know  for sure the problem is not in the database but maybe in the plotting. not important enough to keep this one open.
