### ISSUE TITLE
Aeotec ZW100 MultiSensor 6 - Motionsensor detect Motion for 5s only

### ISSUE THREAD

**Issue by herm44** [domoticz/domoticz#3615]
since a month or so the motion detection for my "Aeotec ZW100 MultiSensor 6" seems to be broken (Beta versions). If Motion was detected it went back to "Off" after 5s, normal behaviour in my setup is to be on for 240s.

_Sep  8 20:10:38 minimaster domoticz: OpenZWave: Alarm received (Home Security: Motion Detected at Unknown Location), NodeID: 4 (0x04)
Sep  8 20:10:38 minimaster domoticz: (Zwave) General/Alarm (Alarm Type: Burglar 7 (0x07))
Sep  8 20:10:38 minimaster domoticz: (Zwave) Light/Switch (BM Arbeitszimmer)
Sep  8 20:10:43 minimaster domoticz: OpenZWave: Alarm received (Home Security: Clear), NodeID: 4 (0x04)_

**Comment by herm44** [comment]
pointing me to the "Binary Sensor Report" Command Class was the hint i needed to fix my "issue". after the change from "Basic Set" to "Binary Sensor Report", and using the other Switch, i again had a working Motion Detection. Thx for your help!

**Comment by petergebruers** [comment]
Thank you for reporting back. I am glad you've got your automation back. BTW good catch, to enable that report you need to change parameter 5  "Which commands to send when PIR motion sensor triggered" from the 1 (default) to 2 "Binary Sensor Report".

**Comment by rjblake** [comment]
Actually seems that this is a problem with the OpenZwave config - it has parameters to clear after 5000ms, but the specification for the Multisensor is in **seconds**. I have tried to change this, but will not accept higher values, so always clears after 5 secs
