### ISSUE TITLE
[Beta V4.11295-V4.11307] Domoticz doesn't log in without 'remember me' checked. (old: Domoticz web app offline, app works fine)

### ISSUE THREAD

**Issue by movhr** [domoticz/domoticz#3618]
Hi there!

After some troubles on my home network, I installed the beta version (V4.11295) of Domoticz using `~/domoticz/updatebeta`. Now after this upgraded, I was not able to access the domoticz web console after logging in from any device, presenting me with a gracious Domoticz Offline banner. Interestingly, the Domoticz app (android) works as expected (as can be seen in the log pasted below). I must admit I've tried downgrading, but as syslog told me, I cannot downgrade due to database compatibility issues.

In the log you will find the following IP addresses:
192.168.10.158 : my desktop on which I've tried accessing the web console from both Firefox and Edge.
192.168.20.165 : my android device that runs Firefox Private Browser (clearing cookies, cache etc).
192.168.100.173 : a little NodeMCU that transmits some data (successfully).

I'm running the following configuration
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
With Domoticz V4.11295

```Sep  9 20:19:41 raspberrypi systemd[1]: Stopping LSB: Home Automation System...
Sep  9 20:19:41 raspberrypi systemd[1]: domoticz.service: Succeeded.
Sep  9 20:19:41 raspberrypi systemd[1]: Stopped LSB: Home Automation System.
Sep  9 20:19:41 raspberrypi systemd[1]: Starting LSB: Home Automation System...
Sep  9 20:19:42 raspberrypi domoticz.sh[1331]: 2019-09-09 20:19:42.132  Status: Domoticz V4.11295 (c)2012-2019 GizMoCuz
Sep  9 20:19:42 raspberrypi domoticz.sh[1331]: 2019-09-09 20:19:42.132  Status: Build Hash: 588d244d2, Date: 2019-09-09 07:57:05
Sep  9 20:19:42 raspberrypi domoticz.sh[1331]: 2019-09-09 20:19:42.133  Status: Startup Path: /home/pi/domoticz/
Sep  9 20:19:42 raspberrypi domoticz.sh[1331]: domoticz: Domoticz is starting up....
Sep  9 20:19:42 raspberrypi domoticz: Domoticz is starting up....
Sep  9 20:19:42 raspberrypi domoticz: Domoticz running...
Sep  9 20:19:42 raspberrypi systemd[1]: Started LSB: Home Automation System.
# Things about sunrise and sunset
Sep  9 20:19:42 raspberrypi domoticz: PluginSystem: Started, Python version '3.7.3'.
Sep  9 20:19:42 raspberrypi domoticz: Active notification Subsystems: email (1/13)
Sep  9 20:19:42 raspberrypi domoticz: WebServer(HTTP) started on address: :: with port 8080
Sep  9 20:19:42 raspberrypi domoticz: WebServer(SSL) started on address: :: with port 8443
Sep  9 20:19:42 raspberrypi domoticz: Starting shared server on: :::6144
Sep  9 20:19:42 raspberrypi domoticz: TCPServer: shared server started...
Sep  9 20:19:42 raspberrypi domoticz: RxQueue: queue worker started...
Sep  9 20:19:44 raspberrypi domoticz: Arilux: Worker started...
Sep  9 20:19:44 raspberrypi domoticz: PluginSystem: Entering work loop.
Sep  9 20:19:50 raspberrypi domoticz: EventSystem: reset all events...
Sep  9 20:19:50 raspberrypi domoticz: EventSystem: reset all device statuses...
Sep  9 20:19:50 raspberrypi domoticz: Incoming connection from: 192.168.100.173
Sep  9 20:19:50 raspberrypi domoticz: Python EventSystem: Initalizing event module.
Sep  9 20:19:50 raspberrypi domoticz: EventSystem: Started
Sep  9 20:19:50 raspberrypi domoticz: EventSystem: Queue thread started...
Sep  9 20:20:10 raspberrypi domoticz: Login successful from 192.168.10.158 for user 'domokate'
Sep  9 20:20:10 raspberrypi domoticz: Incoming connection from: 192.168.10.158
Sep  9 20:20:10 raspberrypi domoticz: Login successful from 192.168.10.158 for user 'domokate'
Sep  9 20:20:10 raspberrypi domoticz: Incoming connection from: 192.168.10.158
Sep  9 20:22:08 raspberrypi domoticz: Login successful from 192.168.20.165 for user 'domokate'
Sep  9 20:22:08 raspberrypi domoticz: Incoming connection from: 192.168.20.165
Sep  9 20:22:34 raspberrypi domoticz: Incoming connection from: 192.168.20.165
Sep  9 20:22:36 raspberrypi domoticz: User: domokate initiated a switch command (3/ledstrip/Set Level)
Sep  9 20:22:36 raspberrypi domoticz: Arilux: Sending data to device
Sep  9 20:22:36 raspberrypi domoticz: (Ledstrip-Controller) Color Switch (ledstrip)
Sep  9 20:22:37 raspberrypi domoticz: User: domokate initiated a switch command (3/ledstrip/Set Level)
Sep  9 20:22:37 raspberrypi domoticz: Arilux: Sending data to device
Sep  9 20:22:38 raspberrypi domoticz: (Ledstrip-Controller) Color Switch (ledstrip)
```

**Comment by gizmocuz** [comment]
Did you try to restart Domoticz ?

**sudo service domoticz restart**

**Comment by chatainsim** [comment]
My brother has the same issue. Don't know on which version.
Domoticz is running fine but webui say offline.
Even after a restart of Domoticz or the Pi.

**Comment by GravityRZ** [comment]
was this not an appcache problem

i had the same thing but only from mobile browsers, not my pc running windows

try renaming the file html5.appcache to html5.appcache.disabled

it is in directory
/usr/local/domoticz/www

so ssh into where domoticz runs (rasberry, synology)

cd /usr/local/domoticz/www
mv -f html5.appcache html5.appcache.disabled

**Comment by gizmocuz** [comment]
You should not rename the appcache, just tell your browser to clear the appcache and the browser cache, to different things

Each browser is different, but for chrome you have to navigate to

chrome://appcache-internals/

**Comment by movhr** [comment]
I downloaded Chrome explicitly to test with, but it still gives me the error. It has not been installed on this machine before so no cache existed. Edge I had preinstalled but never used it to visit Domoticz either. Cache doesn't seem the problem. 
After visiting, I restarted domoticz with `sudo service domoticz restart` and cleared my local machine's Chrome cache with `del -Rf %localappdata%\Google\Chrome\User Data\Default`. It still didn't work.
Moving the html5.appcache doesn't fix it either.

**Comment by movhr** [comment]
Next I betaupdated to v4.11307 which has the same problem.

Also it seems like username and password are passed by parameters in a GET request while logging in. Should probably be marked as a security issue.

**Comment by movhr** [comment]
I successfully logged in by checking 'Remember me'! After logging out and unchecking the box while logging in, I had the 'Domoticz Offline' message again. Might be a bug somewhere or an issue with the browser rejecting cookies?

**Comment by gizmocuz** [comment]
@movhr , glad you solved it

Could you explain a bit more the following issue:

"Also it seems like username and password are passed by parameters in a GET request while logging in. Should probably be marked as a security issue."

Do you use HTTPS (Secure, TLS) ? Both Post/Get requests are encrypted, passwords are not stored in any log in Domoticz
If you do some funky stuff and use a reverse proxy, this might be a issue in the http server's log.
If you llike please make a pull request for this

Regarding clearing the cache, you can do this from the setup in Chrome, or opening the developer console (F12), go to the network tab and press the right mouse button and choose 'delete browser cache'

Any caching issues can also be cleared checked by opening the browser in private mode

**Comment by movhr** [comment]
I do not use HTTPS yet as I'm still trying to find a way to make the Things communicate more safely all together, although I'm not sure everybody is using HTTPS(!). Reasons for using POST requests as opposed to GET requests are that web queries are stored locally in browsers (bookmarks/history/cache) and adversaries may use CSRF to do harm. Also, it directly eliminates any leaks when someone decides to use a reverse proxy. In general, I'd recommend to put all information that would not be shared with a third party in a POST body. After all, why expose information if it's just as easy not to 😄

**Comment by Tobydeteckel** [comment]
I had the same issue and solved it by changing the authentication method on the settings page.

**Comment by waltervl** [comment]
Issue solved?

**Comment by gizmocuz** [comment]
The remember me feature will only work when using cookies

**Comment by gizmocuz** [comment]
The login form uses POST and not GET
