### ISSUE TITLE
Temperature on thermostat no longer updating

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#3619]
I have a CT100 plus thermostat.  After updating to the latest version 4.11300, the temperature reports 0.  The humidity sensor still works on it though. I looked through the commits and my guess is it caused by this one: https://github.com/domoticz/domoticz/commit/709c6d72eed7d7ea1a0a3ea13df07d56911a1aab

Since my other thermometers and multi sensors are still working and that is the only one with furnace and fan states, which was added in that commit.

Oh one additional thing is it also appears that the Z-Wave hub doesn't fully initialize anymore.  If I click on the setup for it it says that not all the nodes have been queried yet.  It's also worth noting that the OZWCP shows the correct values.

**Comment by gizmocuz** [comment]
@Ittiz , I don't think that commit has anything to do with it, as it adds support for a new command class 'COMMAND_CLASS_THERMOSTAT_OPERATING_STATE'

When you change anything on the thermostat, does that update in Domoticz or in the control panel ?

Could you show a screenshot of the control panel ?

Could you enable the debug log ?
- Select the controller node (node 1) and enable the debug log checkbox, then press safve changes.
- Disable the hardware, enable it again

Now in the Config folder you should see a log file (OZW_Log) , it will become quite big,
so as soon as you copied it, disable debug logging!!!

Could you zip and attach the debug log here ?

**Comment by Ittiz** [comment]
I did a shut down of the computer and booted it back up and the problem was resolved.
