### ISSUE TITLE
Xiaomi Gateway temp issue -100°

### ISSUE THREAD

**Issue by chatainsim** [domoticz/domoticz#3621]
Hello,
Since some time I have some issue with one of my temperature sensor from the Xiaomi Gateway.
Sometimes it give me -100°C.
I don't have this on Home Assistant.
![image](https://user-images.githubusercontent.com/1167931/64734406-e02b2000-d4e6-11e9-80a5-57afaecac42f.png)

I'm running v4.11230 of Domoticz.

**Comment by gizmocuz** [comment]
Please post this on the Forum

**Comment by chatainsim** [comment]
This morning I've got another thing about that.
Got a telegram notification about the -100°c:
![image](https://user-images.githubusercontent.com/1167931/64760331-c535cb80-d539-11e9-860e-b19c01cb6be9.png)
But nothing showed up in the graph:
![image](https://user-images.githubusercontent.com/1167931/64760373-e8f91180-d539-11e9-96f5-55f4b2fc95e1.png)
Should I still post this in the forum ?

Thanks

**Comment by gizmocuz** [comment]
Well yes makes sense, its -100 to you get a notification.
Anyways, post this on our forum in the Xiaomi Gateway section

**Comment by chatainsim** [comment]
For people having the same issue, just change the batterie:
https://www.domoticz.com/forum/viewtopic.php?f=68&t=29370&p=223840
