### ISSUE TITLE
Incorrect rain_calendar calculation

### ISSUE THREAD

**Issue by krejkrejkrej** [domoticz/domoticz#3625]
There's a problem with how precipitation is transferred to Rain_Calendar from Rain. Most probably a corner case or possibly a problem with calculation order or so. 

This is all the precipitation that was recorded on two days:

> sqlite> select * from Rain where DeviceRowId=343 and Date < '2019-09-07 02:30:00' and Date > '2019-09-06 23:30:00' ;
> 343|507.0|0|2019-09-06 23:35:01
> 343|507.0|0|2019-09-06 23:40:00
> 343|507.0|0|2019-09-06 23:45:00
> 343|507.0|0|2019-09-06 23:50:00
> 343|507.0|0|2019-09-06 23:55:00
> 343|509.0|200|2019-09-07 00:00:00
> 343|509.0|200|2019-09-07 00:05:00
> 343|509.0|200|2019-09-07 00:10:00
> 343|509.0|200|2019-09-07 00:15:00
> 343|509.0|200|2019-09-07 00:20:00
> 343|509.0|200|2019-09-07 00:25:01
> 343|509.0|200|2019-09-07 00:30:00
> 343|509.0|200|2019-09-07 00:35:00
> 343|509.0|200|2019-09-07 00:40:00
> 343|509.0|200|2019-09-07 00:45:00
> 343|509.0|200|2019-09-07 00:50:00
> 343|509.0|200|2019-09-07 00:55:00
> 343|509.0|0|2019-09-07 01:00:00
> 343|509.0|0|2019-09-07 01:05:00
> 343|509.0|0|2019-09-07 01:10:00
> 343|510.0|100|2019-09-07 01:15:00
> 343|511.0|200|2019-09-07 01:20:00
> 343|511.0|200|2019-09-07 01:25:00
> 343|511.0|200|2019-09-07 01:30:00
> 343|511.0|200|2019-09-07 01:35:00
> 343|511.0|200|2019-09-07 01:40:00
> 343|511.0|200|2019-09-07 01:45:00
> 343|511.0|200|2019-09-07 01:50:00
> 343|511.0|200|2019-09-07 01:55:00
> 343|511.0|200|2019-09-07 02:00:00
> 343|511.0|200|2019-09-07 02:05:01
> 343|511.0|200|2019-09-07 02:10:00
> 343|511.0|100|2019-09-07 02:15:00
> 343|511.0|0|2019-09-07 02:20:00
> 343|511.0|0|2019-09-07 02:25:00

A total of 4 mm, which is then summarised to 

> sqlite> select * from Rain_Calendar where DeviceRowId=343 and ( Date = '2019-09-06' or Date = '2019-09-07') ;
> 343|0.0|0|2019-09-06
> 343|2.0|200|2019-09-07

2 mm's of rain are missing, from one of the days. I can se the calculation being performed in 

> SQLhelper.cpp /CSQLHelper::AddCalendarUpdateRain()

but I'm unfortunately not capable of understanding the code well enough to be able to correct it myself.

**Comment by gizmocuz** [comment]
343|509.0|200|2019-09-07 00:00:00

509.0

what is the value on 2019-09-07 23:xx:xx (last value of the day), and the first value of 2019-09-08 00:00:00 ?

**Comment by krejkrejkrej** [comment]
> 343|511.0|0|2019-09-07 23:55:00
> 343|511.0|0|2019-09-08 00:00:00

**Comment by rwaaren** [comment]
Can this be closed now ?

**Comment by krejkrejkrej** [comment]
Has the problem been corrected? If not: No (of course)

**Comment by rwaaren** [comment]
Please tell us if the issue has been resolved with the fix #3663
