### ISSUE TITLE
The Alarm aka Notification Class needs work to get 1.6 compliant

### ISSUE THREAD

**Issue by petergebruers** [domoticz/domoticz#3627]
I recently introduced extra logging in the SendSwitchIfNotExists function. After this users posted interesting issues with alarm CC.

For example, see:

https://github.com/domoticz/domoticz/commit/e663f6f002f49ac89a953ab9de437ea0026345c9#commitcomment-35082930

The gist: "Not adding '11.instance.2.index.512.commandClasses.113' (i2 Alarm Type) "

So I added an FGMS-001 Fibaro Motion Sensor to my test network because it supports Notification CC...

It wants to add "7.instance.1.index.256.commandClasses.113"

```cpp
unsigned char ID1 = 0;
unsigned char ID2 = (unsigned char)((pDevice->nodeID & 0xFF00) >> 8); -----> 0
unsigned char ID3 = (unsigned char)pDevice->nodeID & 0xFF; -----> 7
unsigned char ID4 = pDevice->instanceID; -----> instanceID is 256 but ID4 is 0, NOK!
```

instanceID > 255 -----> BOOM!

Why 256? In AddValue

```cpp
int newInstance = GetIndexFromAlarm(vLabel);
if (newInstance == 0)
	newInstance = vOrgIndex;
_device.instanceID = newInstance;
```
Errrm...call to GetIndexFromAlarm is OZW 1.4 Stuff... Not good.

Index 256 means "Previous Event Cleared".

That code won't fly :wink:

I will submit a patch make the error message much clearer and at the same time reduce false positive logging.

```cpp
	if ((pDevice->instanceID > 255) || (pDevice->instanceID < 0))
	{
		_log.Log(
			LOG_ERROR,
			"SendSwitchIfNotExists: Not adding '%s' (%s) because instanceID %d does not fit in 8 bits",
			pDevice->string_id.c_str(), pDevice->label.c_str(), pDevice->instanceID);
		return;
	}
```

This will cause logging similar to this

```
Error: SendSwitchIfNotExists: Not adding '3.instance.1.index.256.commandClasses.113' (Previous Event Cleared) because instanceID 256 does not fit in byte
```

Of course you would rather want me to fix the handling of the Notification CC instead of logging something... I might do that, if I find the time.

**Comment by gizmocuz** [comment]
Maybe we should drop all instances with value 256  ? That also solve the automagic clears?

**Comment by petergebruers** [comment]
It is a bit more complicated than that. It depends on device age (CC version), device implementation, but generally speaking value 256 does convey useful information and should be handled... I have briefly pointed out the FGMS-001 is a good example of how a device can convey two different alarms (motion and tamper) and their respective clearing by using this mechanism. Many users seem to think the Notification class represent a kind of on/off state, but it is meant to be an "event" so there might be an "on" signal but no "off" signal. It For example a device might report an "error state" but never send the opposite "no more error state". I think the FGD-212 Dimmer does that (it can detect over current and I think it never sends a clear, but I need to double check if you want to use it as a test). 

Here's that brief discussion of the FGMS-001

<https://github.com/OpenZWave/open-zwave/issues/1889#issuecomment-513481073>

I know that explanation was terse. Give me some time, I'll try to write a much longer and detailed explanation.

**Comment by petergebruers** [comment]
Due to personal circumstances I am unable to work on this... I cannot tell when, and if, I'll be able to do so again. @gizmocuz if you want to close this issue, or rather keep it for reference, that is fine. I'll try to keep working with OpenZWave (but... I cannot make promises), you can ask questions there.

**Comment by waltervl** [comment]
Issue can be closed
