### ISSUE TITLE
Automatic database backup procedure fail

### ISSUE THREAD

**Issue by KroontjesPen** [domoticz/domoticz#3630]
Version: V4.10717 b386b49e5
Platform: Windows 10
RFXtrs433E

*After update problems on my Ockel computer where I had no backup I have the same problem on my PC.

2019-09-14 08:00:00.328 Status: Starting automatic database backup procedure...
2019-09-14 08:00:00.438 Status: Ending automatic database backup procedure...
2019-09-14 08:00:00.395 Error: Error writing automatic hourly backup file
2019-09-14 08:00:00.418 Error: Error writing automatic daily backup file
2019-09-14 08:00:00.438 Error: Error writing automatic monthly backup file

Those files are in c:\Program Files (x86)\Domoticz\backups\.
You can't write there without Admin rights.

*It seems that I lost this way my Blockly files on my Ockel PC.
https://www.domoticz.com/forum/viewtopic.php?f=3&t=27867&start=120#p223936

**Comment by gizmocuz** [comment]
@KroontjesPen , can you change the 'rights' of these folder with the right mouse button ?
Do you need automatic backups ? I run Domoticz since version 1, and don't use automatic backups
Once in a very long while, I make a database backup from the settings page
Good idea to do before updating for example..

**Comment by KroontjesPen** [comment]
@gizmocuz, thanks for your help.
What I have found is that Domoticz writes on 2 places the same database file.
One in the, normal hidden, map c:\ProgramData\Domoticz\
The other in c:\Users\All Users\Domoticz\ map.

Those daily, hourly and monthly maps in the c:\Program Files (x86)\Domoticz\backups map can also put there where the database file are.

On my Ockel mini PC I could lucky back to my old Domoticz version.
My Blockly files I have them block by block building again op my main PC.
Also saved then now in text files.

How you can used that database file, I don't no.

**Comment by gizmocuz** [comment]
You can export the database from the settings page
You can also import a backup database from the settings page

**Comment by KroontjesPen** [comment]
Now every thing is working on my PC and the Ockel mini-PC could taking it back, there is an other problem is case of the c:\Program Files (x86)\ write permission: dzVents scripts.
That is also not possible.

For this a shall make later a other topic.
