### ISSUE TITLE
FGMS-001 generating multiple messages

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3636]
do not know when this happened but it seems to get worse
currently running 11332 and notice the FGMS001 generated multiple messages.

with earlier builds i think it only was with the clearing command but now it is also the case when things are triggered

PIR sensor for example registers like 8 on commands instead of 1
same goes for the off command

it behaves like a jitter and i have to adjust my scripts so that they are not called multiple times and overload dzvents

![image](https://user-images.githubusercontent.com/16853535/65450917-7a238e80-de3e-11e9-8827-ff29a7e34fdd.png)

> 2019-09-23 20:01:13.311 Status: OpenZWave: Alarm received (Home Security: Motion Detected at Unknown Location), NodeID: 16 (0x10)
> 2019-09-23 20:01:13.344 Status: EventSystem: Script event triggered: /usr/local/domoticz/dzVents/runtime/dzVents.lua
> 2019-09-23 20:01:13.367 Status: OpenZWave: Alarm received (Home Security: Motion Detected at Unknown Location), NodeID: 16 (0x10)
> 2019-09-23 20:01:13.396 Status: EventSystem: Script event triggered: /usr/local/domoticz/dzVents/runtime/dzVents.lua
> 2019-09-23 20:01:13.629 Status: EventSystem: Script event triggered: /usr/local/domoticz/dzVents/runtime/dzVents.lua
> 2019-09-23 20:01:14.391 Status: OpenZWave: Alarm received (Home Security: Motion Detected at Unknown Location), NodeID: 16 (0x10)
> 2019-09-23 20:01:14.445 Status: EventSystem: Script event triggered: /usr/local/domoticz/dzVents/runtime/dzVents.lua
> 2019-09-23 20:01:14.640 Status: OpenZWave: Alarm received (Home Security: Motion Detected at Unknown Location), NodeID: 16 (0x10)
> 2019-09-23 20:01:14.767 Status: EventSystem: Script event triggered: /usr/local/domoticz/dzVents/runtime/dzVents.lua
> 2019-09-23 20:01:14.812 Status: OpenZWave: Alarm received (Home Security: Motion Detected at Unknown Location), NodeID: 16 (0x10)
> 2019-09-23 20:01:14.824 Status: OpenZWave: Alarm received (Home Security: Motion Detected at Unknown Location), NodeID: 16 (0x10)
> 2019-09-23 20:01:15.057 Status: EventSystem: Script event triggered: /usr/local/domoticz/dzVents/runtime/dzVents.lua
> 2019-09-23 20:01:15.114 Status: EventSystem: Script event triggered: /usr/local/domoticz/dzVents/runtime/dzVents.lua
> 2019-09-23 20:01:15.486 Status: OpenZWave: Alarm received (Home Security: Motion Detected at Unknown Location), NodeID: 16 (0x10)
> 2019-09-23 20:01:15.635 Status: EventSystem: Script event triggered: /usr/local/domoticz/dzVents/runtime/dzVents.lua
> 2019-09-23 20:01:17.031 Status: OpenZWave: Received timeout notification from HomeID: 3467119363, NodeID: 19 (0x13)
> 2019-09-23 20:01:17.094 Status: EventSystem: Script event triggered: /usr/local/domoticz/dzVents/runtime/dzVents.lua
> 2019-09-23 20:01:27.118 Status: EventSystem: Script event triggered: /usr/local/domoticz/dzVents/runtime/dzVents.lua
> 2019-09-23 20:01:37.068 Status: EventSystem: Script event triggered: /usr/local/domoticz/dzVents/runtime/dzVents.lua

**Comment by 999LV** [comment]
I am facing the same... and frankly I was very happy with OZW 1.4 behavior where the log did not show all these "alarms" (I do not care about "alarms" when the motion sensor is just used to switch own lights...)...

Besides the multiple triggers mentioned by @GravityRZ , domoticz's log is now clogged with zillions of alarm messages...

Interestingly older (non ZW 5) FGMS001 devices do not exhibit a similar behavior... Only ZW 5 do.

**Comment by laurentiugrama** [comment]
I have the same problem with FIBARO System FGD212 Dimmer 2+. As you can see I receive a lots of updates in a short period of time.
I tried to disable updates at device level without success

> 2019-09-24 23:39:22.683 (ZWave) General/kWh (kWh Meter - Children)
>2019-09-24 23:39:22.874 (ZWave) General/kWh (kWh Meter - Children)
>2019-09-24 23:39:35.013 (ZWave) General/kWh (kWh Meter - Children)
>2019-09-24 23:39:35.193 (ZWave) General/kWh (kWh Meter - Children)
>2019-09-24 23:40:11.593 (ZWave) General/kWh (kWh Meter - Children)
>2019-09-24 23:40:11.784 (ZWave) General/kWh (kWh Meter - Children)
>2019-09-24 23:40:23.923 (ZWave) General/kWh (kWh Meter - Children)
>2019-09-24 23:40:24.104 (ZWave) General/kWh (kWh Meter - Children)
>2019-09-24 23:40:36.233 (ZWave) General/kWh (kWh Meter - Children)

**Comment by waltervl** [comment]
Closing this old issue. OpenZwave is deprecated and succeeded by ZwavJS2MQTT https://www.domoticz.com/wiki/ZwaveJS2MQTT
