### ISSUE TITLE
OpenWebnet CEN , alarms , Blinds percentage FAULT

### ISSUE THREAD

**Issue by gibbo520** [domoticz/domoticz#3637]
hallo to everyone,
after the lasts updates ( not sure may be 1 month updates) , my openwebnet Bticino/legrands CEN button was not recognized from domoticz also arm and disarm of bulgrar alarm was not recognized.
The blinds with percentage , stop after 1 second even i want to close from open (about 25 second ) ...

Can you check whats wrong with last updates ? 
Now i have a may 2019 backup and was all good !

Thanks

**Comment by gizmocuz** [comment]
Please use the forum
