### ISSUE TITLE
MQTT Switch Command "brightness" doesn't work

### ISSUE THREAD

**Issue by laurentiugrama** [domoticz/domoticz#3638]
I tried all commands offered as exemple for "setcolbrightnessvalue" and brightness doesn't work for my Mi-Light device.
[Mqtt](https://www.domoticz.com/wiki/MQTT)

> {"command": "setcolbrightnessvalue", "idx": 2450, "hue": 274, "brightness": 40, "iswhite": false }
>{"command": "setcolbrightnessvalue", "idx": 2450, "hex": "RRGGBB", "brightness": 100, "iswhite": false }
>{"command": "setcolbrightnessvalue", "idx": 2450, "color": {"m":3,"t":0,"r":0,"g":0,"b":50,"cw":0,"ww":0}, "brightness": 40}

Equivalent commands for JSON work very well
[JSON](https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s)
>/json.htm?type=command&param=setcolbrightnessvalue&idx=130&color={"m":3,"t":0,"r":0,"g":0,"b":50,"cw":0,"ww":0}&brightness=100
>/json.htm?type=command&param=setcolbrightnessvalue&idx=99&hex=RRGGBB&brightness=100&iswhite=false

Please can you help me with a confirmation of issue/fix

Domoticz V4.11333 Arm 64 bit ODroid

**Comment by gizmocuz** [comment]
Could it be that the brightness is part of the RGB value ?
Does setting the RGB value work ? For example FF00FF is brighter then 440044

**Comment by laurentiugrama** [comment]
I tested and it doesn't work.
FF00FF is the same color as 440044 and is not brighter

**Comment by laurentiugrama** [comment]
**I checked the implementation for "setcolbrightnessvalue" for mqtt and Webserver and it seems to be diffrent**
https://github.com/domoticz/domoticz/blob/c3a517bff3253da7277570dbf72021e05fd3be11/hardware/MQTT.cpp#L295

https://github.com/domoticz/domoticz/blob/c3a517bff3253da7277570dbf72021e05fd3be11/main/WebServer.cpp#L6861

**MQTT use "level" instead of "brightness"**
**I changed in command to use level, in logs the value is ok but it doesn't work.
**Another difference is at the end when the function "m_mainworker.SwitchLight" is called.****

https://github.com/domoticz/domoticz/blob/c3a517bff3253da7277570dbf72021e05fd3be11/hardware/MQTT.cpp#L400-L405
https://github.com/domoticz/domoticz/blob/c3a517bff3253da7277570dbf72021e05fd3be11/main/WebServer.cpp#L6958-L6959

 **MQTT use switchcmd variable that it seems to be empty and automatically is initialized with "Ok"
The single option in this case is** 
>root["switchcmd"] = "Set Color";

https://github.com/domoticz/domoticz/blob/c3a517bff3253da7277570dbf72021e05fd3be11/hardware/MQTT.cpp#L283-L288


**In this case, the working command (tested) containt "switchcmd" and "level"**
>{"command" : "setcolbrightnessvalue", "idx": 10, "color": { "m": 3, "t": 90, "r": 255, "g": 0, "b": 55, "cw": 90, "ww": 90}, "level": 100,"switchcmd": "Set Color"}

**If you consider that that I identified correct the bug I will submit a pull request**
