### ISSUE TITLE
Rel#11337 / Unable to login: invalid user/password

### ISSUE THREAD

**Issue by paifre** [domoticz/domoticz#3640]
**Version 11337**
Rasbian Buster on Pi4
**Authentication mode: Login Page**

Unable to login: invalid user/password with both WIN Chrome or IOS Safari, even after purging all data related to website.
POST /domoticz/logincheck  --> systematic HTTP 401.
I've decoded user/password sent to webserver based on a server network trace. They are correct.
Rollback to 11316 --> login successfully

**Comment by rwaaren** [comment]
Do you see the same with V4.11337 ? (there was a recent commit in that area) 
And if so, do you compile locally or do you use the ./updatebeta command ? 
Make sure you also update the www directory.

**Comment by paifre** [comment]
Sorry, my mistake. I memorized wrongly the release number, I've tested with 11337. I've just checked appversion value in the folder I've saved at rollback time.
This is a compiled from source release after a git pull

Extract from my procedure to deploy a new drop:
mkdir  domoticz
cd dev-domoticz
find . -path "./dzVents*" -print | cpio -dump ../domoticz
find . -path "./plugins*" -print | cpio -dump ../domoticz
find . -path "./scripts*" -print | cpio -dump ../domoticz
find . -path "./www*" -print | cpio -dump ../domoticz
find appversion.h.txt History.txt License.txt domoticz -print | cpio -dump ../domoticz

**Comment by paifre** [comment]
I've tested also on my previous pi3 with Stretch debian.
I've upgraded it to 11337 and was able to reproduce the authentication problem with the logincheck url.
I have also tested with and without webroot. Same behavior.

**Comment by paifre** [comment]
If you guide me, maybe I can use the pi3 installation currently unused and do some debug or provide some traces.
I need to know where to do some modifications in the source code. Hope it could help.

**Comment by gizmocuz** [comment]
Clear your browser cache + appcache, if that does not work stop domoticz

> sudo service domoticz stop

go to the domoticz folder

> cd domoticz

start domoticz by hand with the recover password option:

> ./domoticz -nowwwpwd

You should now be able to login without password, you can change the password now

Let us know if that worked for you

**Comment by paifre** [comment]
Sorry for late answer.
New tests done today with Rel#11433

./domoticz
Enter user/password --> ok

./domoticz -webroot domo
Enter user/password --> KO

As domo is my historical webroot, trying with another webroot value
./domoticz -webroot titi
Enter user/password --> KO

Retesting without webroot
./domoticz
Enter user/password --> ok

Seems to be a some related webroot  issue

Best regards

**Comment by paifre** [comment]
Was looking to something else and finally another problem appears related to webroot too
Investigating with browser developper tools, with webroot, 
JSON request is receiving "404 Not Found" answer
ws://_myhostname:myport_/_mywebroot_/json

Restarting without webroot
JSON request is receiving expected 101 HTTP code: switching protocol. JSON thread discuss then regularly without issue every ten seconds

If prefer, I can open a dedicated issue for this, just let me know

Best regards,

**Comment by paifre** [comment]
Error trapped by webrowser console:
-------------------------------------
WebSocket connection to 'ws:/xxxxx:ppppp/domoticz/json' failed: Error during WebSocket handshake: Unexpected response code: 404
me.$$init | @ | angular-websocket.js:127
me.$open | @ | angular-websocket.js:255
(anonymous) | @ | angular-websocket.js:170
websocket.error   livesocket.js:87

**Comment by gizmocuz** [comment]
I will try to have a look at this.
Why do you need a webroot ? Should what you want to do not be possible with NGINX and a simple proxy/rewrite rule ?

**Comment by gizmocuz** [comment]
@paifre , websocket issue has been resolved, authentication remaining...
I would have thought that this problem was found before... or something has been broken recently
Still when using NGINX (or Apache) a webroot should not really be necessary

**Comment by paifre** [comment]
@gizmocuz  Fix on websocket with webroot works fine.
Many things are configure with webroot, I need to evaluate impact but agree having nginx has RP to rewrite URLs to remove webroot.
Many thanks.

**Comment by paifre** [comment]
Few comments  (still with webroot on )  on auth, open a fresh window
json/getconfig, old DMZSID --> Server answers 401 and request DMZSID=none
json/getrelease again with old DMZSID --> 401, still request client to set DMZSID=none
json/getauth with still old invalid DMZSID, still 401
client move to OFFLINE page

When login form get displayed purging cache,  return 401 on logincheck page
Server logs (webroot on):
2019-11-03 23:10:40.745  Error: CheckAuthToken(a3e1e8aff06de7e1c9f9abe2283a85ad_Yzc5Yzc5MDctYTBmZC00YzEyLWIyNmYtYTFiYzNhOTg2MTll) : session id not found
2019-11-03 23:10:41.177  Error: CheckAuthToken(a3e1e8aff06de7e1c9f9abe2283a85ad_Yzc5Yzc5MDctYTBmZC00YzEyLWIyNmYtYTFiYzNhOTg2MTll) : session id not found
2019-11-03 23:10:41.202  Error: CheckAuthToken(a3e1e8aff06de7e1c9f9abe2283a85ad_Yzc5Yzc5MDctYTBmZC00YzEyLWIyNmYtYTFiYzNhOTg2MTll) : session id not found

**Comment by paifre** [comment]
Few additional tests/debug:
When submitting user/password to url logincheck,
I've reached this branch and execute the return (line 2067 of cWebem.cpp) and receive 401
			if ((isPage || isAction || bCheckAuthentication) && !CheckAuthentication(session, req, rep))
			{
				return;
			}
 As I'm going in cWembem:CheckAuthentication, I'm reaching end of method without entering the different if conditions and reached myWhitelistURLs & itt section then out. Rep.content is set unauthorized in send_authorization_request

Some data
RequestHandle Out of CheckAuthentication --> session.rights= -1
RequestHandle Out of CheckAuthentication --> req.uri= /tototo/logincheck
RequestHandle Out of CheckAuthentication --> rep.content= <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>

RequestHandle  cmdparam= /tototo/logincheck

CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 4294967295
CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 4294967295
CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 4294967295
CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 4294967295
CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 4294967295
CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 8
CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 7
CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 4294967295
CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 4294967295
CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 4294967295
CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 4294967295
CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 4294967295
CheckAuthentication myWhitelistURLs
CheckAuthentication cmdparam.find(*itt)= 4294967295


Can't do much more, MyWhiteListURLs usage is not clear for me
Not sure webroot should be part of cmdparam string 

Hope it helps

Best regards

**Comment by paifre** [comment]
I've made a last dirty try
forcing cmdparam to get logincheck value when /tototo/logincheck is found --> successful dirty login :)

**Comment by paifre** [comment]
Doing a logout, unable to login again
CheckAuthToken
2019-11-04 02:35:09.915  Error: CheckAuthToken(81ce6b1afd75dae89ea5176708b25e5a_MTI1YjM2OWUtOTFlYi00MjVmLWE4YTQtY2E0YjhmMDQ2N2Ix) : session id not found
logincheck request is still sending old DMZSID, not taking care of the SetCookie DMZSID to none
Set-Cookie: DMZSID=none; HttpOnly; Expires=Thu, 01 Jan 1970 00:00:00 GMT
What browser does with an already pre-expired cookie ? How does it manage that ?

Sequence:
Request    logout.html
Request    LogoutController.js
Request URL: http://myhost:myport/tototo/json.htm?type=command&param=dologout
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: 
Referrer Policy: no-referrer-when-downgrade

Rough Request    json?getlanguage

**Comment by gizmocuz** [comment]
@paifre , as mentioned, things do not work correctly anymore when using webroot.
Why do you switched back to using webroot ? You said you got it working with NGINX without webroot

**Comment by paifre** [comment]
@gizmocuz , I still right now need to use webroot. As stated, many things are configure with domoticz running a webroot, I need to evaluate impact.

**Comment by szczukot** [comment]
@paifre Do you check "Rememeber me" ?

**Comment by Maes152** [comment]
As far as I know it is impossible to make Domoticz work in a subdirectory using NGINX without configuring webroot in Domoticz. Using the webroot in domoticz has worked wonderfully for many years, now all of a sudden it's broken and I can't login to domoticz anymore. Can you please restore the webroot functionality.

**Comment by Driekes** [comment]
Is there any news about this issue? I use webroot so I can use it for reverse proxy apache setup so I can access it remotely. Unfortunately since the latest stable, this doesn't work anymore.

**Comment by gizmocuz** [comment]
@Driekes , you should be able to configure a rewrite rule in Apache (and/or NGINX) so there is no need to a webroot
Just proxy a request (http://bla.com/mydomoticzentrypoint/*) to (http://10.0.0.8:8080/*)

**Comment by Driekes** [comment]
@gizmocuz I thought I checked this multiple times already, but I must have made a mistake. It works now! Thanks for your help.

**Comment by gizmocuz** [comment]
@Driekes , great to hear! Could you share your modification here for feature reference ?
(I should create a wiki page for this actually)

**Comment by Driekes** [comment]
This is the most important snippet in httpd-vhosts.conf. I'm not an expert, but from the outside I can approach it with SSL. I think I originally had an issue with the trailing /. If I then approached Domoticz without a trailing slash all references were to the original root, which contains a website. So the trailing slash (either below, or using it in the URL) proved to be critical. But putting this below at least forces you to use the /. (I have Domoticz installed on port 8085 for normal traffic and a random port for SSL.

<VirtualHost *:443>
    ProxyPass /domoticz/ http://localhost:8085/
    ProxyPassReverse /domoticz/ http://localhost:8085/
</VirtualHost>

**Comment by gizmocuz** [comment]
Thanks for sharing!

**Comment by Driekes** [comment]
@gizmocuz 

It is not solved. The interface is no longer updating. I have found these suggestions:
    ProxyPass "/json"  "ws://localhost:8085/json"
    ProxyPassReverse "/json"  "ws://localhost:8085/json"

However these don't work. I have read somewhere that this could be because I'm using https from the outside, but internally http. (wss vs ws). Not sure if that is the case, my knowledge is non existent here :P

**Comment by Driekes** [comment]
Well, searching a bit further, not related to domoticz but wstunnel vs apache, I have it working now.
What I have done (without any clue if all is required), to get reverse proxy working:

Enable mod_proxy, mod_proxy_http, mod_proxy_http2, mod_proxy_wstunnel.

Then I set it up with this code (port 8085):

```
<VirtualHost *:443>
    ServerName domain.com

    SSLEngine on
    ProxyPreserveHost On
    ProxyRequests off
    SSLCertificateFile "file-chain.pem"
    SSLCertificateKeyFile "file.pem"

    ProxyPass /domoticz/ http://localhost:8085/
    ProxyPassReverse /domoticz/ http://localhost:8085/

  <Location "/domoticz/json">
    ProxyPass "ws://localhost:8085/json"
  </Location>
</VirtualHost>
```

**Comment by gizmocuz** [comment]
Thanks for the feedback, I made a small wiki page here, hope it's OK:

https://www.domoticz.com/wiki/WebServer_Proxy

**Comment by Driekes** [comment]
@gizmocuz 
This was the exact suggestion I got on another topic, but that didn't work for me for the json part. Maybe because I am using https on the external site and http on the internal connection.
I used the <Location> thing, and that worked. So maybe you can put that as alternative in the wiki.
So far thanks for the quick response!

**Comment by gizmocuz** [comment]
@Driekes , did you also do it in that order ? First the json and then the rest?
If yes, I will put your block in here

**Comment by Driekes** [comment]
No, other way around. I'll test it, just to be sure.

**Comment by Driekes** [comment]
@gizmocuz I tried your suggestion, also in that order, but that didn't work for me. I have seen at least one other person it did work for, but I need the <Location> option. So hopefully it can help others if you add is as alternative to your wiki!

**Comment by gizmocuz** [comment]
I just add your option and see if it does not work for other people
Thank you again!

**Comment by fr3sh** [comment]
OMG I have spend 2 days figuring out what Im doing wrong :( and the reason was the webroot not working
Gladly i found this.

**Comment by Driekes** [comment]
Just curious, which option worked for you?

**Comment by Driekes** [comment]
Just curious, which option worked for you?

**Comment by gizmocuz** [comment]
webroot would be removed soon as this is not needed and should be proxied in the webserver
