### ISSUE TITLE
update data

### ISSUE THREAD

**Issue by cronyx** [domoticz/domoticz#3642]
Dashboard data not updated without refresh page. Some errors are available in debug console.
![errors](https://user-images.githubusercontent.com/2557102/65670609-5b93e200-e04e-11e9-9def-29e663b4fcef.png)

**Comment by redswan01** [comment]
I believe this is a Firefox problem linked to the introduction of websockets. See forum topic   [No auto refresh on 4.11316]( https://www.domoticz.com/forum/viewtopic.php?f=6&t=29414#p224758)

**Comment by cronyx** [comment]
Hm... thanks, its really firefox issue.
