### ISSUE TITLE
Return in the code make other code not reachable.

### ISSUE THREAD

**Issue by xbeaudouin** [domoticz/domoticz#3643]
In domoticz.js in line 1618
https://github.com/domoticz/domoticz/blob/c3a517bff3253da7277570dbf72021e05fd3be11/www/js/domoticz.js#L1618

We have a return . Then other code will be not reachable... Firefox complains about that... :/

**Comment by gizmocuz** [comment]
@xbeaudouin , that's the idea (that the next code does not get executed...)
It's removed in the next beta beta/repo code...
No idea why there should be a complain by Firefox... it was put there on purpose ;)
