### ISSUE TITLE
Fibaro Smart Implant FGBS-222 only shows one alarm input

### ISSUE THREAD

**Issue by kennetn** [domoticz/domoticz#3648]
I have a FGBS-222 and would like to use both inputs for showing a on/off status.
The device is running without encryption and both outputs are working fine.
The inputs however are merged in the same device in the device list.
I found that this is because both inputs end up with the same instance id here:
https://github.com/domoticz/domoticz/blob/c3a517bff3253da7277570dbf72021e05fd3be11/hardware/OpenZWave.cpp#L1752
The vLabel of the first input is "Instance 1: Home Security" and the other is "Instance 2: Home Security" because the search is just for "Home Security" they will both hit.
https://github.com/domoticz/domoticz/blob/c3a517bff3253da7277570dbf72021e05fd3be11/hardware/OpenZWave.cpp#L58
I tried adding { "Instance 2: Home Security",	0x41 },
and it looked like this fixed the issue so that I have both inputs in the device list.
I am running this on windows with a OpenZwave from last week.
I am a bit unsure what the right solution is here as it looks like the GetIndexFromAlarm is just for backwards compatability, however I do not see what the alternative is here. I am also unsure if the 0x41 I used might colide with something else?

**Comment by superjunky** [comment]
I would also like to know how this issue can be fixed.

**Comment by gizmocuz** [comment]
@kennetn / @superjunky , the function should return 0 (GetIndexFromAlarm), and it can not find a match on the label.
When it is 0, it should use the vOrgIndex value is used (AddValue, ~line 1792), and UpdateValue, ~line 2612
Maybe the code in UpdateValue is not right, i see it assigns a value to 'instance', but that is not used
(Maybe in UpdateValue it has to change vOrgInstance so it is used a few lines below)

It is indeed for backwards compatibility, the idea was to make the change to OpenZWave 1.6 compatible with previous used node devices.

**Comment by superjunky** [comment]
@gizmocuz , is there any documentation on how to setup a dev environment for Domoticz? I mainly want to know if there is a way to run tests without the need to compile. Or else a few time-saving pointers to get me going..

**Comment by gizmocuz** [comment]
@superjunky , yes it's described in INSTALL.md for Windows, and for linux you can follow https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by SirStonehill** [comment]
@gizmocuz , I would like to check in on this issue. Is there any news? I'm having the same problem on 2020.2.11995 stable.

**Comment by gizmocuz** [comment]
Feel free to debug, but do so with the latest code and version as your version is very old

**Comment by waltervl** [comment]
As OpenZwave is deprecated please check with Zwavejs2mqtt. This issue will be closed.
