### ISSUE TITLE
Dimmer svalue 255 

### ISSUE THREAD

**Issue by nayrnet** [domoticz/domoticz#365]
dimmers when at 100% have the svalue set to 255 and not 100, this is fine but its breaking the display on the webui.

When the dimmer is any value from 0-99% it displays fine, however when device is at 100% it will fall back to previous displayed value.

Dimmer set to 98% displays fine:
![screen shot 2016-01-19 at 7 35 11 pm](https://cloud.githubusercontent.com/assets/3732081/12438436/0c640672-bee4-11e5-9100-fc8eb3c645b9.png)
![screen shot 2016-01-19 at 7 49 49 pm](https://cloud.githubusercontent.com/assets/3732081/12438634/d9a30830-bee5-11e5-9378-4335cc24bc02.png)

Change the dimmer to 21%, wait a few moments for it to acknoledge it.. see lights dim, everything okay.
![screen shot 2016-01-19 at 7 35 49 pm](https://cloud.githubusercontent.com/assets/3732081/12438443/2ba4189c-bee4-11e5-8c3e-8382a45ba103.png)

Change the dimmer to 100%, wait a few moments, see lights brighten to 100% and then device refresh occurs and dimmer slider changes back to 21% like above.. Look at the device's svalue and it shows 255, where the svalue was 98 and 21 after the previous commands.:
![screen shot 2016-01-19 at 7 36 17 pm](https://cloud.githubusercontent.com/assets/3732081/12438465/5bd9ff40-bee4-11e5-88c3-afca924610be.png)

I suspect the UI needs to recognize that on/255 == 100% or some math is bad.

More complaints: https://www.domoticz.com/forum/viewtopic.php?f=11&t=8832

**Comment by nayrnet** [comment]
fixed: https://github.com/domoticz/domoticz/pull/368

**Comment by nayrnet** [comment]
still testing.. think I found the problem in the ZWaveBase, making this a poor fix

**Comment by nayrnet** [comment]
trying the following under ZWaveBase::SendDevice2Domoticz

                // Now check the values
                if (level == 0)
                        lcmd.LIGHTING2.cmnd = light2_sOff;
                else if ((level == 255) && (pDevice->devType == ZDTYPE_SWITCH_NORMAL))
                        lcmd.LIGHTING2.cmnd = light2_sOn;
                else
                {
                        level = (level > 100) ? 100 : level;
                        lcmd.LIGHTING2.cmnd = light2_sSetLevel;
                }

**Comment by nayrnet** [comment]
What do you think of this proposed solution? 
https://github.com/domoticz/domoticz/pull/369

This works out much cleaner I think.. A dimmer value should remain within 0-100.

**Comment by gizmocuz** [comment]
Think this is now solved in the latest commit (no new beta yet)
