### ISSUE TITLE
Domoticz not accessible from web interface

### ISSUE THREAD

**Issue by Komagain** [domoticz/domoticz#3650]
RPI 
hello After an update last week-end Domoticz failed in error segment Fault,
I did apt-get update / upgrade / .updaterelease
Now the service status is OK (running)
But I am still not able to access thru web interface (ssh is ok)
on the RPI: PiHole and Monit are running fine (SSH and Web)
`sudo nano /lib/systemd/system/domoticz.service` bring no file

`sudo nano /etc/init.d/domoticz.sh`
`PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin`
`DESC="Domoticz Home Automation System"`
`NAME=domoticz`
`USERNAME=domoticz`
`PIDFILE=/var/run/$NAME.pid`
`SCRIPTNAME=/etc/init.d/$NAME`

`DAEMON=/domoticz/$NAME`
`DAEMON_ARGS="-daemon"`
`#DAEMON_ARGS="$DAEMON_ARGS -daemonname $NAME -pidfile $PIDFILE"`
`DAEMON_ARGS="$DAEMON_ARGS -www 8093"`
`DAEMON_ARGS="$DAEMON_ARGS -sslwww 443"`
`DAEMON_ARGS="$DAEMON_ARGS -log /tmp/domoticz.txt"`
`#DAEMON_ARGS="$DAEMON_ARGS -syslog"`

`pi@domopi:~ $ sudo /etc/init.d/domoticz.sh status`
`● domoticz.service - LSB: Home Automation System`
`   Loaded: loaded (/etc/init.d/domoticz.sh; generated; vendor preset: enabled)`
`   Active: active (exited) since Tue 2019-10-01 14:40:10 CEST; 22min ago`
`     Docs: man:systemd-sysv-generator(8)`
`  Process: 611 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)`
`    Tasks: 0 (limit: 4915)`
`   CGroup: /system.slice/domoticz.service`

`Oct 01 14:40:09 domopi systemd[1]: Starting LSB: Home Automation System...`
`Oct 01 14:40:10 domopi domoticz.sh[611]: 2019-10-01 14:40:10.881  Status: Domoticz V4.10717 (c)2012-2019 GizMoCuz`
`Oct 01 14:40:10 domopi domoticz.sh[611]: 2019-10-01 14:40:10.889  Status: Build Hash: b38b49e5, Date: 2019-05-09 13:04:08
Oct 01 14:40:10 domopi domoticz.sh[611]: 2019-10-01 14:40:10.890  Status: Startup Path: /domoticz/
Oct 01 14:40:10 domopi domoticz.sh[611]: domoticz: Domoticz is starting up....
Oct 01 14:40:10 domopi domoticz[635]: Domoticz is starting up....
Oct 01 14:40:10 domopi domoticz[662]: Domoticz running...`
`Oct 01 14:40:10 domopi systemd[1]: Started LSB: Home Automation System.`
`

**Comment by gizmocuz** [comment]
@Komagain , please post this on our Forum
