### ISSUE TITLE
Domoticz Plugin system

### ISSUE THREAD

**Issue by schurgan** [domoticz/domoticz#3654]
Domoticz Plugin system only supports 255 devices. Can you increase the limit? I have more than 255 devices on a plugin, that's why I'm asking. At the moment I can not create more devices and there are errors. thanks

Error: Device creation failed, Device object is not associated with a plugin.

**Comment by dnpwwo** [comment]
@schurgan,

The 255 limit is not a plugin restriction it is a Domoticz restriction.

If plugins allowed more they would only partially work.

Sorry.

**Comment by schurgan** [comment]
And what can be done to handle this?  Are there other possibilities?

**Comment by dnpwwo** [comment]
Depends what your plugin is doing.

Can you run multiple copies of the same plugin and divide the devices between them?

What hardware are you supporting that has so many devices?

**Comment by schurgan** [comment]
Xiaomi. Could you help me copy the plugin? I have no idea how that's going.

**Comment by gizmocuz** [comment]
@schurgan , that is not normal.... ! Do you have 255 Xiaomi devices ? I can't believe that...

**Comment by schurgan** [comment]
No, I do not have 255 Xiaomi devices.  I have 254 devices in Domoticz because 1 Xiaomi device has 3 to 8 devices in Domoticz.  For example, a motion detector from Xiaomi makes 4 subdevices in Domoticz.  Physically, there are 40 to 50 devices from Xiaomi that I have

**Comment by gizmocuz** [comment]
@schurgan , could you explain this a bit more... 1 motion detector should create 1 device , a switch, which you maybe have to configure as type 'motion sensor'

**Comment by schurgan** [comment]
A motion detector (Xiaomi RTCGQ11LM) generates 4 sensors, a switch, a battery sensor, a sensor with signal strength and a sensor with light intensity.  A window sensor generates 3 sensors, just like a motion detector without sensor with light intensity

**Comment by gizmocuz** [comment]
@schurgan , that is not needed as the switch supports battery and strength.
As for the LUX sensor, that could be indeed a bonus.
So it seems you can reduce by 50% already

**Comment by schurgan** [comment]
I know it.  But I did not do the plugin.  I can not do anything myself.  And if I delete the devices that I do not need, they will come back the next time.

**Comment by gizmocuz** [comment]
You have to talk to the plugin maker (maybe he/she has a github account), or you could make a patch for the plugin yourself.
It is not a Domoticz issue

**Comment by gizmocuz** [comment]
Next to this, your database will be flooded and gets very large

**Comment by schurgan** [comment]
Yes, he is also on github.  I do not think he just changes the plugin for me.  If I could, I would have already rewritten the plugin.  What do you mean by the patch?

**Comment by schurgan** [comment]
Yes, he is also on github.  I do not think he just changes the plugin for me.  If I could, I would have already rewritten the plugin.  What do you mean by the patch?

**Comment by gizmocuz** [comment]
That means check out his code, make the needed changes and then commit. Thats how git works.
But you have to open a issue on his github account
Do you have a link?

**Comment by schurgan** [comment]
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin

**Comment by schurgan** [comment]
Is it possible to integrate the plugin in Domoticz?

**Comment by gizmocuz** [comment]
You have to open an issue on his github account/project page
I see there is already an issue on this project asking to merge it directly into the Domoticz project,
but maybe there is good reason not to do so yet (maybe it is not 100% finished)
Closing this issue, please open one there
