### ISSUE TITLE
Domoticz is not for 100% working under Windows because of write permission in C:\Program Files (x86)\

### ISSUE THREAD

**Issue by KroontjesPen** [domoticz/domoticz#3655]
In an other issue #3630 I mention the write permission in C:\Program Files (x86)\.
You need there admin rights.
Therefore hourly, daily and monthly backups couldn't be backup.

The domoticz.db file is put in C:\ProgramData\Domoticz\  for that reason I assume?

Now I found the same problems with the dzVents.
The are put in the C:\Program Files (x86)\Domoticz\dzVents\

Why not put Domoticz out of the C:\Program Files (x86)\ like the program Total Commander.

**Comment by KroontjesPen** [comment]
Looking further for a workaround but that is not aloud by Domoticz.
Auto start can NOT setting OFF, it's setting ON back directly.

The shortcut icon on the screen is useless because of the auto start.
There for NO start in admin mode or chancing the starting line.

**Comment by rwaaren** [comment]
Please find an explanation about the installation process and a way to control locations and other behavior in this [ Forum post ](https://www.domoticz.com/forum/viewtopic.php?f=4&t=29613#p225262)
And please continue discussion (if any) there.

**Comment by KroontjesPen** [comment]
**There is a workaround but that is not for normal Windows users.**

The rights of Domoticz map had to be changed for the users of that PC.

**Comment by rwaaren** [comment]
That is not necessary if you follow the method I described in the forum ( use a user writable location for the domoticz database )
