### ISSUE TITLE
Toggle mode for switch

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#3659]
I'm currently handling a Device which has a native Toggle command. However I do not see any easy way to get access from Domoticz UI.

Would it be possible to have an enhanced version of the standard Switch type, with a Toggle command in addition of On and Off.

I know that a Selector can be use, but this would be a real shame to have for such basic ?

**Comment by GravityRZ** [comment]
i solved this by creating a group with the name of the toggle switch(eg lamp-toggle)
putting a json toggle command for the switch you want to toggle  in both the ON and OFF field



http://192.168.1.xx:xxxx/json.htm?type=command&param=switchlight&idx=77&switchcmd=Toggle

**Comment by gizmocuz** [comment]
Thanks indeed the best way. Please ask these questions on the forum!

**Comment by pipiche38** [comment]
I known that there are several ways to turn around. But having a native Toggle on the widget will make the User Experience much efficient.

This is like the fact that for Venetian Covering in addition to Up and Down you have added Stop, which is lacking on the Blind widget
