### ISSUE TITLE
Qubino ZMNHADX needs node refresh after power failure

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3664]
running V4.11354

The qubino node had problems with lost grouping after power failure. this was solved in #1895
i however discovered that when this unit is disconnected from power and the power comes back the temp sensor still does not work.
it needs a node refresh to get the temperature reading working again
is there a way to solve this that this unit registers temperature again automatically after a power loss/failure?

**Comment by gizmocuz** [comment]
I think you have to ask this at OpenZWave as this is not a Domoticz issue.
Please post your issue there.

**Comment by GravityRZ** [comment]
ok, closing this one(still gray area)
