### ISSUE TITLE
Sending a message, the text entered is send including quotes

### ISSUE THREAD

**Issue by tofra** [domoticz/domoticz#367]
With this blocky:
![image](https://cloud.githubusercontent.com/assets/1746173/12499418/bf3ae924-c0aa-11e5-8020-6ed7808dee2b.png)
I receive a message including the double quotes. Using master branch. Stable version doesn't have this problem. (2.3530)
![image](https://cloud.githubusercontent.com/assets/1746173/12499580/0bde45ea-c0ac-11e5-92f0-ccf34256e756.png)

For now I debugged it up to EventSystem.cpp method CEventSystem::parseBlocklyActions. The "if" is located at line 1950. The string is looking like %22Header%22 (the double quotes are encoded)

I'll do some more investigating tomorrow..

**Comment by gizmocuz** [comment]
Should be fixed now!, Thanks for the location
