### ISSUE TITLE
Latest beta V4.11371 11375 Usb Problem 

### ISSUE THREAD

**Issue by zedbulo** [domoticz/domoticz#3672]
Hi,

After updating with latest Beta , python plugins lost usb settings......
so they don't work anymore......

Thks.

Rpi3 debian 10 updated

2019-10-17 17:10:52.580 Error: (Zigate) Plugin is not started ...
2019-10-17 17:10:52.580 Error: (Zigate) - Communication issue with the Zigate
2019-10-17 17:10:52.580 Error: (Zigate) - restart once the plugin, and if this remain the same
2019-10-17 17:10:52.580 Error: (Zigate) - unplug/plug the zigate
2019-10-17 17:10:52.889 Error: teleinfoGeneral hardware (10) thread seems to have ended unexpectedly
2019-10-17 17:10:57.589 (Zigate) No Firmware Version received from Zigate
2019-10-17 17:10:57.589 Error: (Zigate) Plugin is not started ...
2019-10-17 17:10:57.589 Error: (Zigate) - Communication issue with the Zigate
2019-10-17 17:10:57.589 Error: (Zigate) - restart once the plugin, and if this remain the same
2019-10-17 17:10:57.589 Error: (Zigate) - unplug/plug the zigate
2019-10-17 17:11:01.412 (Rfplayer) Pushing 'onHeartbeatCallback' on to queue
2019-10-17 17:11:01.445 (Rfplayer) Processing 'onHeartbeatCallback' message
2019-10-17 17:11:01.445 (Rfplayer) Calling message handler 'onHeartbeat'.
2019-10-17 17:11:01.445 (Rfplayer) Pushing 'ConnectDirective' on to queue
2019-10-17 17:11:01.445 (Rfplayer) Processing 'ConnectDirective' message
2019-10-17 17:11:01.445 (Rfplayer) Transport set to: 'Serial', '/dev/serial/by-id/usb-Ziblue_RFPLAYER_A11SVA8Z-if00-port0', 115200.
2019-10-17 17:11:01.446 (Rfplayer) Pushing 'onConnectCallback' on to queue
2019-10-17 17:11:01.446 (Rfplayer) Connect directive received, action initiation failed.
2019-10-17 17:11:01.446 (Rfplayer) Processing 'onConnectCallback' message
2019-10-17 17:11:01.446 (Rfplayer) Calling message handler 'onConnect'.
2019-10-17 17:11:01.446 (Rfplayer) Failed to connect (-1) to: /dev/serial/by-id/usb-Ziblue_RFPLAYER_A11SVA8Z-if00-port0
2019-10-17 17:11:01.446 (Rfplayer) Failed to connect (-1) to: /dev/serial/by-id/usb-Ziblue_RFPLAYER_A11SVA8Z-if00-port0 with error: open: No such file or directory
2019-10-17 17:11:02.598 (Zigate) No Firmware Version received from Zigate

**Comment by gizmocuz** [comment]
@zedbulo , what operating system/platform/hardware are you using ?
Don't you see any USB device ?
did you try
sudo lsusb -v

**Comment by zedbulo** [comment]
hi Gismocuz !!
Raspian buster 10
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
lsusb -v
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 
  bDeviceProtocol         2 TT per port
  bMaxPacketSize0        64
  idVendor           0x0424 Standard Microsystems Corp.
  idProduct          0x9514 SMC9514 Hub
  bcdDevice            2.00
  iManufacturer           0 
  iProduct                0 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                2mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Single TT
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0001  1x 1 bytes
        bInterval              12
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 TT per port
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0001  1x 1 bytes
        bInterval              12
Hub Descriptor:
  bLength               9
  bDescriptorType      41
  nNbrPorts             5
  wHubCharacteristic 0x000d
    Per-port power switching
    Compound device
    Per-port overcurrent protection
    TT think time 8 FS bits
  bPwrOn2PwrGood       50 * 2 milli seconds
  bHubContrCurrent      1 milli Ampere
  DeviceRemovable    0x02
  PortPwrCtrlMask    0xff
 Hub Port Status:
   Port 1: 0000.0503 highspeed power enable connect
   Port 2: 0000.0100 power
   Port 3: 0000.0100 power
   Port 4: 0000.0100 power
   Port 5: 0000.0503 highspeed power enable connect
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 
  bDeviceProtocol         0 Full speed (or root) hub
  bMaxPacketSize0        64
  bNumConfigurations      1
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0001
  Self Powered

Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 
  bDeviceProtocol         1 Single TT
  bMaxPacketSize0        64
  idVendor           0x1d6b Linux Foundation
  idProduct          0x0002 2.0 root hub
  bcdDevice            4.19
  iManufacturer           3 Linux 4.19.66-v7+ dwc_otg_hcd
  iProduct                2 DWC OTG Controller
  iSerial                 1 3f980000.usb
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0019
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 Full speed (or root) hub
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0004  1x 4 bytes
        bInterval              12
Hub Descriptor:
  bLength               9
  bDescriptorType      41
  nNbrPorts             1
  wHubCharacteristic 0x0008
    Ganged power switching
    Per-port overcurrent protection
    TT think time 8 FS bits
  bPwrOn2PwrGood        1 * 2 milli seconds
  bHubContrCurrent      0 milli Ampere
  DeviceRemovable    0x00
  PortPwrCtrlMask    0xff
 Hub Port Status:
   Port 1: 0000.0503 highspeed power enable connect
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0001
  Self Powered

Thks

**Comment by zedbulo** [comment]
Hi ,

Removed usb restarted rpi and handed usb .......... everything works again.

Thks
