### ISSUE TITLE
No icons refresh in Firefox

### ISSUE THREAD

**Issue by PHIL-IP** [domoticz/domoticz#3674]
Domoticz don't refresh its icons and/or devices values under Firefox since v4.11316 (perhaps little before).
i.e : when you click on a switch the icon does not change.
i.e 2 : When a temperature probe goes up a new value it is not modified on the Domoticz page

In the console the problem seems related to the angular-websocket.js file (angular-websocket.js:127:14)
Evry 4 or 5 second the console add a line with this error (translated from French) :
Firefox cannot establish a connection with the server at ws://xxx.xxx.xxx.xxx:8282/json. angular-websocket.js:127:14

None of the following versions so far (v4.11379) have solved the problem.
The problem is only present under Firefox, the other tested browsers (Chrome, Edge, I.E, Opera) work perfectly.

**Comment by gizmocuz** [comment]
Did you search on the forum about this?

**Comment by PHIL-IP** [comment]
Yes but no solution at this time.

**Comment by RicardP** [comment]
Regardless this problem, that I also experience, Firefox is generally very incompatible in my own experience, I have supported Firefox a long time but I must sadly admit it is forcing me to switch over to Chrome or Edge more frequently over time :(

**Comment by iassenk** [comment]
Same issue on Debian stretch with Firefox 60.9.0 esr - since Sep. 20 2019

Firefox console:
Firefox can’t establish a connection to the server at ws://xxx.xxx.xxx.xxx:8080/json.
angular-websocket.js:127:14
websocket error
livesocket.js:87:6

Using another browser is not a serious option...

**Comment by RicardP** [comment]
@iassenk What I meant if it is a bug/issue/behavior in Firefox specific then the problem should be pointed to Firefox, as other browsers works fine, or what do I not understand? :)

**Comment by iassenk** [comment]
I would say "works, but with errors" - here is console output from Chrome 79.0.3928.4:

TypeError: Cannot read property 'indexOf' of undefined
    at TranslateStatusShort (domoticz.js:1242)
    at RefreshItem (LightsController.js:344)
    at LightsController.js:794
    at m.$broadcast (angular.min.js:153)
    at $websocket.<anonymous> (livesocket.js:132)
    at $websocket.me.$$fireEvent (angular-websocket.js:116)
    at WebSocket.me.$$ws.onmessage (angular-websocket.js:137)
(anonymous) @ angular.min.js:124
(anonymous) @ angular.min.js:96
$broadcast @ angular.min.js:153
(anonymous) @ livesocket.js:132
me.$$fireEvent @ angular-websocket.js:116
me.$$ws.onmessage @ angular-websocket.js:137

**Comment by RicardP** [comment]
@iassenk Thank you, I have not the coding experience but I believe it is great you provide this information for the real brains here :)

**Comment by gizmocuz** [comment]
@PHIL-IP , have a look here
https://www.domoticz.com/forum/viewtopic.php?f=6&t=29499&p=226316

@iassenk, Chrome is working , but about your error, what type of switch is causing this problem ?
I will double check the TranslareStatusShort , but seems that this is working for most of the switches
Seems the item.Status is not available

**Comment by iassenk** [comment]
@gizmocuz, To get rid of potentially broken switches, i created a room with only one switch - type 
light/switch, switch on/off. It's an OZW Neo Coolcam outlet. When displaying only this room in "switches" tab, the result in Chrome is the same as above.

**Comment by gizmocuz** [comment]
@iassenk , @PHIL-IP , found the issue, solved in beta 11386 and up

**Comment by PHIL-IP** [comment]
@gizmocuz, thanks a lot. Always at the top :)
Domoticz works well now :)

**Comment by redswan01** [comment]
@gizmocuz, Firefox works correctly again for me too.
Thanks a lot:)

**Comment by iassenk** [comment]
@gizmocuz It seems massive work is done, thanks a lot!

**Comment by pipiche38** [comment]
While it works on Switch tab, it looks like it doesn't on the Dashboard tab. 
Firefox 70.0.1 ( Ubuntu)
Domoticz V4.11476

**Comment by pipiche38** [comment]
@gizmocuz , Running a Domoticz V4.11476 and while it behaves correctly on the Switch tab, it is not the case on the Dashboard one !

**Comment by gizmocuz** [comment]
@pipiche38 , maybe you need to clear your browser cache and appcache ? (Two different things)
Else perform this test:
Add a dummy hardware (if you have not one already)
Add a dummy switch
On the left of your desktop open a browser to Domoticz to the dashboard
On the right of your desktop open a browser to Domoticz to the switches tab

Now on the right turn the switch On/Off, you should see this on the left browser
