### ISSUE TITLE
P1 Smart Meter used in Belgium

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#3677]
They have started to roll out P1 Smart Meters in Belgium (Flanders).
Obviously since spring this year.
Several times since then it has been reported that the Gasmeter is missing.

The reason is that the protocol specification, used in The Netherlands slightly differs from the protocol specification used in Belgium.
See: https://www.fluvius.be/sites/fluvius/files/2019-07/1901-fluvius-technical-specification-user-ports-digital-meter.pdf
Fluvius wrote it down in chapter 4.3 and 4.4 of their document.

The Belgium specification can be found: https://onedrive.live.com/view.aspx?resid=EAEC8CA1B66CDF7B!245341&ithint=file%2Cdocx&authkey=!ABXM6pDlhjeOr7A
For the gasmeter, see chapter, 3.3.3 of the document.
In NL the OBIS reference is: 0-1:24.2.1 
In B the OBIS reference is: 0-1:24.2.3

In order to make it work in Belgium as well, a small modification is required

**Comment by gordonb3** [comment]
This has been implemented over six weeks ago, in pull #3603.

May also like to note that Belgium is expected to switch to OBIS 0-1:24.2.1 as described in the Dutch smart meter specification. The reason that they are currently using a different OBIS code is due to a legal decrete: OBIS 0-1:24.2.1 is temperature corrected by the meter, OBIS 0-1:24.2.3 is not and thus requires post-correction similar to old mechanical meters.

**Comment by FireWizard52** [comment]
Thanks.
I was not aware that this issue has been solved about 6 weeks ago and that Thibault Vos  picked up my suggestion to post his issue here.
Thanks for your additional note as well.

**Comment by gordonb3** [comment]
Coincidence probably... I had this on my ToDo list for some time but could not find the documentation that had apparently previously been openly available on the Eandis website, so I asked them. Found out later that the link to that document on onedrive had been obscured inside a PDF.

**Comment by FireWizard52** [comment]
Does this mean, that it has not been solved, but that it will be done?
I agree, that it has not been easy to find the documentation and I had not expected to find such  an essential specification on Onedrive.

**Comment by gizmocuz** [comment]
@FireWizard52 , as mentioned this has been implemented 6 weeks ago.
There might be remaining issues, but before opening this issue again, test this first.
If it ain't working, please re-open this issue
