### ISSUE TITLE
Setpoints messed up with latest build to V4.11390 and V4.11391

### ISSUE THREAD

**Issue by mcmikev** [domoticz/domoticz#3679]
I have tested this with Edge, Edge Dev, Chrome and InternetExplorer and all have the same behavior.

Setpoint to set heating in rooms is working in V4.11350 (my latest stable beta) and since the webhook issues I have stopped updating a while. Now with this being fixed I did a rebuild from source and that gives me this issue.

https://www.domoticz.com/forum/viewtopic.php?f=6&t=29841&sid=8ffe9bfc8658415ce7a302fd703061cf

Unable to use or set the setpoints anymore.

Not sure since when or what update this might have caused.

**Comment by gizmocuz** [comment]
@mcmikev , when posting a issue here, please follow the guidelines... that includes specifying the hardware/os
Did you clear your browser cache and appcache ? (Two different things)

When i click on a setpoint i get a popup with the actual temperature that i can set

What does not work ? When you do 'set' a setpoint, does that work ? Do you only experience a gui/drawing issue, are the buttons working ?

**Comment by mcmikev** [comment]
I was not sure if i should post here so therefor i included the link to bug section with my post and all details. 
I have a roomplan for heating there is a setpoint device for turning the danfoss on or off 

That is not working anymore. 
Build from source
Rpi3
V4.11390 and V4.11391 in version V4.11350 it is still fine and that is nu latest beta backup

Button do not work cannot see values just nam

**Comment by gizmocuz** [comment]
@mcmikev , you mean to set the setpoint to a degree ?
Could you add a dummy hardware, and create a virtual setpoint sensor.
Does this one work correctly ?
Did you clear the browser cache + appcache ?

**Comment by mcmikev** [comment]
This sensor is created by the virtual thermostat plugin.
I have also tested then with a new dummy setpoint and that is doing the same.
Someone is saying in the forum (link above) that it seems to work on the utility page but not on dashboard. 
I cannot test that quickly because I need to rebuild again then and test. I had to go back to latest backup here in order to use the heating and temp settings.

**Comment by mcmikev** [comment]
I will rebuild again and test. Give me some time

Forget above, I have kept the build with this error. I am renaming folders now and test for you

**Comment by mcmikev** [comment]
Okay tested and created a new dummy again. On utility page it is working, on dashboard it is not
Cleared cash and appcache.
Tested with IE, Chrome and Edge Dev (chromian based)
Same for all thermostat setpoints

**Comment by gizmocuz** [comment]
Thank you for investigating... I also used it from the Utility page...
