### ISSUE TITLE
notification for humidity via HTTP fails

### ISSUE THREAD

**Issue by gbonny1982** [domoticz/domoticz#3680]
I'm running v4.10717 on Python 3.6.8 and OZW 1.4-3335 on Ubuntu 18.04 x64 (installed last week from Download page Linux tgz).

I've set notifications HTTP+KODI for a humidity threshold like >65%. From time to time I receive the KODI message, however on the same time the message via HTTP (XMPP script) isn't delivered. 

Other HTTP notifications like door/window contacts/test/power levels are delivered via HTTP (XMPP script). So this seems specific to humidity.

**Comment by gizmocuz** [comment]
@gbonny1982 , that is probably by design. Switch notifications you want to receive always, other sensors, specially when for example the humidity goes up/down around your specified notification value, you do not want to receive 10 times a day (I don't...)
But if you want to, go to the settings, Notifications, and at the bottom also specify 1 minute for 'sensors'

**Comment by gbonny1982** [comment]
@gizmocuz I've configured now also notification via email and they are delivered maybe once or twice a day. You're right that you don't want a notification every minute. Once or twice a day is acceptable.

I'm gonna check my script tonight, it could be that there is a "greater than" symbol in the output which needs to be escape in the script.

**Comment by ravsit-activum** [comment]
I have the same problem.
https://github.com/domoticz/domoticz/issues/3673

I think the problem is with "%" symbol in output.

**Comment by gbonny1982** [comment]
I have no issues with % symbol. I receive messages via HTTP script like: "Battery low: Temp (level:5%)"

**Comment by gbonny1982** [comment]
Btw I have followed this how-to:
https://www.domoticz.com/wiki/Installing_XMPP_Notification_System
Made some minor adjustments to my situation. Like location of .sendxmpprc and I didn't get the "-t" to work so I removed it.

**Comment by gbonny1982** [comment]
I have tried escaping the "greater than" to no solution unfortunately yet:

```
#!/bin/sh
#echo "$4" | sendxmpp -u $1 -o $2 $3 &
value4=$4
value4="$(echo $value4 | sed 's/>/\\>/g')"
echo "$value4" | sendxmpp -u $1 -o $2 $3 &
exit 0
```

**Comment by gizmocuz** [comment]
I am building a new beta version, that could take up to one hour (beta 11401)

I made the following change:
https://github.com/domoticz/domoticz/commit/71f14f6159b16322e4cc2bb8a590a02dfd31fb80

maybe that solved the issue ?

**Comment by ravsit-activum** [comment]
> 
> 
> I have no issues with % symbol. I receive messages via HTTP script like: "Battery low: Temp (level:5%)"

i do some tests.

for Your text: "Battery low: Temp (level:5%)" data go to script,
but
for text: "Battery low: Temp [ (level:5%) ]" data do not go to script. 

So something is wrong with square brakets symbols: [ ].

**Comment by gizmocuz** [comment]
Ok this is getting very confusing !!!
So, script ? HTTP Notification ? Which one is it ?

**Comment by gizmocuz** [comment]
I have reverted the patch. Feel free to make a PR when needed.

**Comment by ravsit-activum** [comment]
> 
> 
> Ok this is getting very confusing !!!
> So, script ? HTTP Notification ? Which one is it ?

Custom HTTP/Action for Notifications.

Data do not go to script means that parameters #SUBJECT and #MESSAGE are empty.
I use action: script:///home/pi/domoticz/scripts/sendsms2.sh  "#SUBJECT" "#MESSAGE"

**Comment by gbonny1982** [comment]
my Custom HTTP/Action for Notifications:
script:///home/domoticz/domoticz/scripts/notify_xmpp.sh #FIELD1 #FIELD2 #TO "#MESSAGE"

See the contents of notify_xmpp.sh in my previous comment.

**Comment by gizmocuz** [comment]
@gbonny1982 , No reason I get confused... as the HTTP notification can also perform 'script'
That should have been split... and at least have been named "HTTP/Script"

Can you compile yourself ? I see a problem in the code

NotificationHTTP.cpp

this:

```
		stdreplace(destURL, "#SUBJECT", CURLEncode::URLDecode(Subject));
		stdreplace(destURL, "#MESSAGE", CURLEncode::URLDecode(Text));

```
should (I believe):

```
		stdreplace(destURL, "#SUBJECT", CURLEncode::URLEncode(Subject));
		stdreplace(destURL, "#MESSAGE", CURLEncode::URLEncode(Text));

```

So decode should be encode

**Comment by gbonny1982** [comment]
@gizmocuz Thanks for diving into this.  No problem getting confused, I think you're right that it has to be split up in the future.

I can spin off a separate VM tomorrow evening and I think I can compile it myself.

Regarding your solution, I think you're right to use URLEncode when you want to do a HTTP URL call (however I haven't used this feature yet).

I'm not sure about using URLEncode for a script call. It could work if I do a URLDecode in my script, I think. Maybe it's better to do nothing (no decode/encode) for script calls. I'm gonna try to figure it out tomorrow evening and will report back!

**Comment by gbonny1982** [comment]
I've modified my script temporarily to:

```
#!/bin/sh
#value4=$4
value4="TempHum Humidity is 86 % [> 65 %]"
echo "$value4" | sendxmpp -u $1 -o $2 $3 --tls-ca-path="/etc/ssl/certs" -n -t &
exit 0
```

This works. Now I have to check what domoticz exactly passes to the script.

I've added encryption to sendxmpp as you can see, without errors.
Btw, can someone update the wiki
https://www.domoticz.com/wiki/Installing_XMPP_Notification_System

For Ubuntu 18.04 
`echo "$4" | sudo sendxmpp -t -u $1 -o $2 $3`
should be either (no encryption)
`echo "$4" | sudo sendxmpp -u $1 -o $2 $3`
or (encryption no cert validation)
`echo "$4" | sudo sendxmpp -u $1 -o $2 $3 --tls-ca-path="/etc/ssl/certs" -n -t`

**Comment by gbonny1982** [comment]
I think that the script isn't called at all in case of a "TempHum Humidity is 86 % [> 65 %]".

```
#!/bin/sh
echo "hello world"
value4=$4
#value4="TempHum Humidity is 86 % [> 65 %]"
echo "$value4" | sendxmpp -u $1 -o $2 $3 --tls-ca-path="/etc/ssl/certs" -n -t &
exit 0
```

I've added an echo "hello world" at the beginning of my script. 
When I do a domoticz test message "hello world" appears in my syslog and I receive a script notification. 
When I receive a doorbell script notification, I see "hello world" in the syslog. 
But when I should receive a script humidity notification, "hello world" isn't printed in the syslog and I won't receive a script notification (while I receive a notification by email/kodi).

I think the URLDecode doesn't do any harm, but isn't needed either on line 101 & 102 NotificationHTTP.cpp. (did not test it)

So it seems that certain message's go through the AddTaskItem/SQLHelper.cpp and specifically the humidity one's aren't delivered. I can see the syslog entry from SQLHelper.cpp line 3361 and then it fails on line 3365 or 3366? Because line 3366 isn't executed (properly). 
I do not see the error message from 3369 in my syslog. Odd huh :-\

**Comment by gbonny1982** [comment]
Even a custom message like "attic too humid" was not delivered via script notification.

**Comment by gbonny1982** [comment]
When I set a custom notification like "attic too humid" the notification is delivered via script. Could it be that the '[' and ']' mess things up? I mean messages like "battery low (level: 5%)" and "doorbell >> ON" are delivered which rule out '%' and '>'.

**Comment by gbonny1982** [comment]
@gizmocuz do you have enough info right now?

**Comment by gizmocuz** [comment]
Could you please make the code modification to use URLEncode and test ?
It seems there was a mistake in the code, and URLDecode was used, but it needs to be encode as the section above uses this as well

**Comment by ravsit-activum** [comment]
Hi, i did modification and did test.

the correct lines are without Decode (it is plain text) and without Encode (in script we need plain text, too).

	stdreplace(destURL, "#SUBJECT", Subject);
	stdreplace(destURL, "#MESSAGE", Text);

Decode fails at plain text when "% ["

best regards

**Comment by gizmocuz** [comment]
@ravsit-activum , not sure what you did, but as mentioned above try with 

```
stdreplace(destURL, "#SUBJECT", CURLEncode::URLEncode(Subject));
stdreplace(destURL, "#MESSAGE", CURLEncode::URLEncode(Text));
```

**Comment by gizmocuz** [comment]
@ravsit-activum , could you post the result of the above, and perform the next test...
Without Decode/Encode like you did, but in the script command line (settings->notifications)
Add double quotes " before en after #SUBJECT and #MESSAGE like

script:///home/myhome/myscript "#SUBJECT" "#MESSAGE"

**Comment by ravsit-activum** [comment]
I did test with encode, and in script i got Encoded string - but we don't want in scripts encoded string.

i have quotes.
script:///home/pi/domoticz/scripts/sendsms2.sh  "#SUBJECT" "#MESSAGE"

With this lines the correct notification goes to script

stdreplace(destURL, "#SUBJECT", Subject);
stdreplace(destURL, "#MESSAGE", Text);



2019-10-25 13:06:39.973  Status: Notification: test Humidity is 73 % [>= 40 %]
2019-10-25 13:06:39.975  Notification sent (browser) => Success
2019-10-25 13:06:39.976  Status: Uwaga!!!
2019-10-25 13:06:39.976  Status: test Humidity is 73 % [>= 40 %]
2019-10-25 13:06:39.976  Status: test Humidity is 73 % [>= 40 %]
2019-10-25 13:06:39.976  Status: script:///home/pi/domoticz/scripts/sendsms2.sh  "test Humidity is 73 % [>= 40 %]" "test Humidity is 73 % [>= 40 %]"
2019-10-25 13:06:39.976  Status: Uwaga!!!
2019-10-25 13:06:39.976  Status:  "test Humidity is 73 % [>= 40 %]" "test Humidity is 73 % [>= 40 %]"
2019-10-25 13:06:39.976  Notification sent (http) => Success
2019-10-25 13:06:40.189  Status: Executing script sqlhelper: /home/pi/domoticz/scripts/sendsms2.sh
2019-10-25 13:06:40.189  Status: Executing params:  "test Humidity is 73 % [>= 40 %]" "test Humidity is 73 % [>= 40 %]"
test Humidity is 73 % [>= 40 %]
test Humidity is 73 % [>= 40 %]
RPI: test Humidity is 73 % [>= 40 %] test Humidity is 73 % [>= 40 %]

**Comment by gizmocuz** [comment]
@ravsit-activum , Thank you for testing. Yes that is what i thought... so putting the message/subject between quotes is the solution

Could you test my below fix, you could then/test without quotes as they will be added automaticcaly

```
		if (destURL.find("#SUBJECT") != std::string::npos)
		{
			//Make sure the subject is surrounded by quotes "#SUBJECT"
			if (destURL.find("\"#SUBJECT\"") == std::string::npos)
			{
				stdreplace(destURL, "#SUBJECT", "\"#SUBJECT\"");
			}
		}
		if (destURL.find("#MESSAGE") != std::string::npos)
		{
			//Make sure the message is surrounded by quotes "#MESSAGE"
			if (destURL.find("\"#MESSAGE\"") == std::string::npos)
			{
				stdreplace(destURL, "#MESSAGE", "\"#MESSAGE\"");
			}
		}

		stdreplace(destURL, "#SUBJECT", Subject);
		stdreplace(destURL, "#MESSAGE", Text);


```

**Comment by ravsit-activum** [comment]
yes, the code do their job

2019-10-25 13:53:07.115  Status: Notification: test Humidity is 101 % [>= 40 %]
2019-10-25 13:53:07.116  Notification sent (browser) => Success
2019-10-25 13:53:07.117  Status: Uwaga!!!
2019-10-25 13:53:07.117  Status: test Humidity is 101 % [>= 40 %]
2019-10-25 13:53:07.117  Status: test Humidity is 101 % [>= 40 %]
2019-10-25 13:53:07.117  Status: script:///home/pi/dev-domiticz/scripts/sendsms2.sh  "test Humidity is 101 % [>= 40 %]" "test Humidity is 101 % [>= 40 %]"
2019-10-25 13:53:07.117  Status: Uwaga!!!
2019-10-25 13:53:07.117  Status:  "test Humidity is 101 % [>= 40 %]" "test Humidity is 101 % [>= 40 %]"
2019-10-25 13:53:07.117  Notification sent (http) => Success
2019-10-25 13:53:07.356  Status: Executing script sqlhelper: /home/pi/dev-domiticz/scripts/sendsms2.sh
2019-10-25 13:53:07.356  Status: Executing params:  "test Humidity is 101 % [>= 40 %]" "test Humidity is 101 % [>= 40 %]"
test Humidity is 101 % [>= 40 %]
test Humidity is 101 % [>= 40 %]
RPI: test Humidity is 101 % [>= 40 %] test Humidity is 101 % [>= 40 %]

BTW. do You know why subject and text are the same?

**Comment by gizmocuz** [comment]
Yes because for these notifications there is no message, it is equal to the subject.
You don't have to include #MESSAGE in your script.
Subject/Message are only possible via events/blockly

**Comment by waltervl** [comment]
Issue solved?

**Comment by gbonny1982** [comment]
Hi, it is working now. Currently running Domoticz 2021.1 on Ubuntu 20.04 x64.

Wiki still needs to be changed, see my msg on 23 Oct 2019.

**Comment by waltervl** [comment]
Thank you for your reaction, I will update the wiki.

**Comment by waltervl** [comment]
Wiki updated

**Comment by gizmocuz** [comment]
There is a new Domoticz version
