### ISSUE TITLE
Datatables warning (Hardware -> ZWave Stick -> Setup)

### ISSUE THREAD

**Issue by elxsi** [domoticz/domoticz#3682]
I've compiled domoticz from the current github sources (v4.10725) and I'm receiving a datatables warning for every zwave device after opening the zwave (Aeotec) setup dialog:

Setup -> Hardware -> Setup (Aeotec ZWave Stick) -> Devices

DataTables warning: table id=nodestable - Requested unknown parameter '8' for row 0, column 8. For more information about this error, please see http://datatables.net/tn/4

DataTables warning: table id=nodestable - Requested unknown parameter '8' for row 2, column 8. For more information about this error, please see http://datatables.net/tn/4

DataTables warning: table id=nodestable - Requested unknown parameter '8' for row 3, column 8. For more information about this error, please see http://datatables.net/tn/4

...

Additionally, the battery column is empty for all rows. Assuming datatable columns start at position 0, then column 8 would be indeed the battery column.

Thank you!

**Comment by gizmocuz** [comment]
Could you clear your browser cache + appcache, two different things and try again ?
This is mentioned when you created the issue in the guidelines.
Also mentioned in the guidelines are other things we ask you to mention and perform before posting a issue here

**Comment by elxsi** [comment]
Hi,

thank you for your reply. Sorry, I've forgotten to mention - yes I've cleared the browser cache and the app cache. I've also tried opening domoticz in a private browser window, this did not change anything. The developer console does not show any javascript errors. Tested in chrome (76.0.3809.100) and firefox (60.9.0esr).

root@domoticz:/home/domoticz# cat /etc/debian_version 
9.11
root@domoticz:/home/domoticz# uname -a
Linux domoticz 4.15.18-20-pve #1 SMP PVE 4.15.18-46 (Thu, 8 Aug 2019 10:42:06 +0200) x86_64 GNU/Linux
root@domoticz:/home/domoticz# git status
On branch development
Your branch is up-to-date with 'origin/development'.

Please tell me if you need further information.

Thank you

**Comment by gizmocuz** [comment]
Thank you for the info.
I would have expected a cache issue as the columns are defined in the 'view' and filled by the controller
(www/app/hardware/setup/ZWave.js , line 689)
could you change this line

"8": item.Battery,

to

"8": "Hello world!",

then clear the browser cache/appcache, or private browser, now it should say hello world, does that make the errors disappear ?

**Comment by elxsi** [comment]
Hi,

thank you for your reply. Yes, this fixes the issue, "Hello World" gets displayed. Looks like item.Battery is undefined.

Thank you!

**Comment by gizmocuz** [comment]
@elxsi , and that should not be possible as this is always returned as a string in OpenZWave.cpp, line 5296

`root["result"][ii]["Battery"] = (pNode->batValue == 255) ? "-" : std::to_string(pNode->batValue);
`

**Comment by elxsi** [comment]
Hi,

I've added a console.log(item); in www/app/hardware/setup/ZWave.js just before 
var addId = oTable.fnAddData({..}); (line 673). The output shows, that item does not have a Battery field:

{Description: "AEON Labs ZW117 Range Extender 6", HaveUserCodes: false, HomeID: 3790970869, IsPlus: true, LastUpdate: "2019-10-22 18:05:10", …}
Description: "AEON Labs ZW117 Range Extender 6"
HaveUserCodes: false
HomeID: 3790970869
IsPlus: true
LastUpdate: "2019-10-22 18:05:10"
Manufacturer_id: "0x0086"
Manufacturer_name: "AEON Labs"
Name: "Aeotec AEOEZW117 Range Extender Typ 6"
NodeID: 30
PollEnabled: "false"
Product_id: "0x0075"
Product_name: "ZW117 Range Extender 6"
Product_type: "0x0004"
State: "Awake"
Version: 4
config: (5) [{…}, {…}, {…}, {…}, {…}]
idx: "23"
__proto__: Object

(see also attached screenshot)

root["result"][ii]["Battery"] = (pNode->batValue == 255) ? "-" : std::to_string(pNode->batValue);
is indeed in hardware/OpenZWave.cpp in line 5296.

Thanks


<img width="1257" alt="domoticz-screenshot_20191022" src="https://user-images.githubusercontent.com/7499705/67306280-ff11ce80-f4f6-11e9-95b7-47a86ea6c46e.png">

**Comment by gizmocuz** [comment]
Then your source code is not up 2 date ?
Are you compiling yourself ? make sure you have a fresh copy, or try the binary version
So either you should get "-" when no battery value is received yet or available, or a string value with the battery percentage

Or try rewriting that CPP line to

`root["result"][ii]["Battery"] = "Hi There 123!";`

that should plot the above text in the column

**Comment by stuiow** [comment]
Just want to add i'm getting this issue on Chrome as well.
Since from a couple of beta releases (4/5 days ago).
Edge works ok, chrome (on mobile and pc) both come up with the multiple errors as described earlier.
UPDATE - after clearing the cache, i closed chrome and then back into Domoticz, all is well.
The clear chrome cache and then closing chrome seemed to fix it for me.
I'll attempt the same on my chrome mobile later.

**Comment by gizmocuz** [comment]
@stuiow , let us know if that works, then we can close this issue

**Comment by stuiow** [comment]
Clearing browsing data on my chrome on the mobile also work. The errors are not appearing.

**Comment by gizmocuz** [comment]
@stuiow , thank you for reporting. Yes that's what i wrote in the first reply above.
