### ISSUE TITLE
Z-Wave Door Lock "Advanced" not handled (probably minor issue)

### ISSUE THREAD

**Issue by petergebruers** [domoticz/domoticz#3693]
This issue is not about the Lock Status, but about Lock_Mode aka "Locked (Advanced)"

If a lock supports this additional bit of information, Domoticz logs:

`Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1`

That is good because it is true, that Index is unhandled.

Index 1 is ValueID_Index_DoorLock::Lock_Mode (the lock status is Index 0, ValueID_Index_DoorLock::Lock and afaik that one is OK).

One way to handle this would be to check this specific case and change the logging to a warning level instead of an error because right now, actually, there is a bug in OZW handling that ValueID

https://github.com/OpenZWave/open-zwave/issues/1886

Probably no existing gateway software uses this status... But the it exists and the CC exposes it.

I cannot tell which locks support it, I don't own a lock, but I've used a Z-Uno to simulate a lock.

**Comment by Jofreathome** [comment]
Hi, I reported something like this last year november in the Domoticz forum.

https://www.domoticz.com/forum/viewtopic.php?f=6&t=30073&p=227833&hilit=Danalock#p227833

Now I have tried the latest stable version and the error is still there and it is even worse.

[Domoticz2020.1log.txt](https://github.com/domoticz/domoticz/files/4460628/Domoticz2020.1log.txt)

It would be very nice if this issue could be solved as I do not like it to see those red error lines appear in the log file.

**Comment by Jofreathome** [comment]
@petergebruers 
Hi, this issue stills exists in the latest beta and all the errors in the Domoticz logfile for every lock operation are pretty annoying.

**Comment by gizmocuz** [comment]
@Jofreathome , It is scheduled for OpenZWave 1.7, which is the next version. If the valueID is working we can try supporting it.
Or you could try to debug it and make a PR?

**Comment by waltervl** [comment]
Closing this old issue. OpenZwave is deprecated and succeeded by ZwaveJS2MQTT https://www.domoticz.com/wiki/ZwaveJS2MQTT
