### ISSUE TITLE
OpenWebNet member variables same as function parameters

### ISSUE THREAD

**Issue by gizmocuz** [domoticz/domoticz#3695]
@Spugna85 ,

Is it possible you can rename all class members with m_ ? like m_who
You are using who/where/... also in function parameters which is quite confusing and causes compiler errors

https://github.com/domoticz/domoticz/blob/1016549ac68100e13d6aea1f6a91ded42205caf3/hardware/openwebnet/bt_openwebnet.h#L358

Thank you!

**Comment by Spugna85** [comment]
[https://github.com/domoticz/domoticz/pull/3696](url)

**Comment by gizmocuz** [comment]
@Spugna85 , thank you very much for this! Much appreciated !

**Comment by Spugna85** [comment]
@gizmocuz no problem, but I would like to know why this page has been deleted:
[https://www.domoticz.com/wiki/MyHome_OpenWebNet_Via_LAN_Interface](url)
 also the hardware references on the main page have been deleted ..

**Comment by gizmocuz** [comment]
@Spugna85 , because you added it twice in the wiki, and i removed one
Or did you referenced the page a second time ?
Can't find it now... Sorry about this... strange... I am 100% sure i have seen it twice !

**Comment by gizmocuz** [comment]
Sorry, no that was about lua parsers
I did not delete yours...
And i don't see it in the log...

**Comment by Spugna85** [comment]
I don't understand what happened. unfortunately I don't have a copy of the page I wrote, if I have time I write it again ..

I tried to log in to the wiki, but it tells me:
Since MediaWiki 1.33 it is not possible anymore to use your Forum username / password

Could it be due to a version update of MediaWiki?

**Comment by gizmocuz** [comment]
Only when you wrote the article during the transformation
Could you contact me in the forum (OM) for a username / password request?
Registration is currently closed because of spam
