### ISSUE TITLE
French translation error

### ISSUE THREAD

**Issue by Hydci** [domoticz/domoticz#3706]
In the version "beta Version: 4.11415" there is a translation error
Open = Ouvert not Ouvrir 

![Ouvertnotouvrir](https://user-images.githubusercontent.com/36527391/68084038-8254ed80-fe30-11e9-9328-56cef2d04756.PNG)

For the doors it's the same
Open = Ouvert not Ouvrir
![porte](https://user-images.githubusercontent.com/36527391/68084087-3eaeb380-fe31-11e9-8386-ad0869bd301f.PNG)

**Comment by gizmocuz** [comment]
Thanks for reporting, but please use our transifex translation system. It seems also that French has two works for open/close ?

**Comment by Hydci** [comment]
Transifex ? I do not know what that means
You talk about that?
![french](https://user-images.githubusercontent.com/36527391/68086030-9d7f2780-fe47-11e9-85f2-50d8ac1eaa81.PNG)

in French ==> "Ouvert" is a status
in french ==> "Ouvrir" is a action

Regarding the closed status he and correct

**Comment by rwaaren** [comment]
All translatable strings in domoticz are maintained here:

https://www.transifex.com/domoticz/domoticz/

**Comment by Hydci** [comment]
@rwaaren Thank you for the link so I will look if I can help

Edit: 
I registered on the site to participate I managed to find the word to translate so I made the correct translation of it

**Comment by Hydci** [comment]
I made the correction of the file but I can not modify in the folders / home / pi / domoticz / www I do not understand too much the system of "domoticz-fr.json.gz" would you make me this pack with the new translation that i can try the fix?

**Comment by gizmocuz** [comment]
@Hydci , from time to time we merge the translations made in Transifex into Domoticz
If you update to beta 11464 you should now see your changes
(Could take an hour before the beta is available)

**Comment by Hydci** [comment]
Hello @gizmocuz thanks for the quickness of the patch, I just installed the update and correction and correct
![20191104_105554](https://user-images.githubusercontent.com/36527391/68113044-1b4c3d00-fef3-11e9-9700-3db53f10f87d.png)
(Thanks for the explanation for the corrections you apply)
