### ISSUE TITLE
generic_device.lua:203: attempt to call field 'tointeger' (a nil value) on change of many selectors

### ISSUE THREAD

**Issue by stephanvdplas** [domoticz/domoticz#3709]
After installing latest beta for Windows (V4.11464) with many (all?) selector changes the scripts don't do their job and in the log we see:

Error: EventSystem: in C:\Program Files (x86)\Domoticz\dzVents\runtime\dzVents.lua: ...oticz\dzVents\runtime\device-adapters/generic_device.lua:203: attempt to call field 'tointeger' (a nil value)

a lot of times.

**Comment by rwaaren** [comment]
@gizmocuz :  I checked and this Windows version is compiled with internal Lua 5.2 It should have been compiled with Lua 5.3 
In Lua 5.2 math.tointeger does not exist.
@stephanvdplas as work around until this has been fixed you can remove line 202, 203, 204 and 206 of 
`C:\Program Files (x86)\Domoticz\dzVents\runtime\dzVents.lua: ...oticz\dzVents\runtime\device-adapters/generic_device.lua`  or use the modified file from below commit 

Worked around it by removing math.tointeger and replaced by conditional math.floor

[https://github.com/domoticz/domoticz/commit/8358ec21f3f5b6836f0ca1300f4e4bc120cb08e8](https://github.com/domoticz/domoticz/commit/8358ec21f3f5b6836f0ca1300f4e4bc120cb08e8)

**Comment by kevsterd** [comment]
I'm getting a similar error on Raspian also.  This is off triggered Lua scripts within domoticz/scripts/lua.  Prior to the last update was working fine...

`.../domoticz/scripts/lua/script_device_watchman_sensor2.lua:64: attempt to call a nil value (field 'pow')`

Is this a change to how something works or a bug ?

(My script reads virtual sensors and updates others as a result)

**Comment by rwaaren** [comment]
> I'm getting a similar error on Raspian also. This is off triggered Lua scripts within domoticz/scripts/lua. Prior to the last update was working fine...
> 
> `.../domoticz/scripts/lua/script_device_watchman_sensor2.lua:64: attempt to call a nil value (field 'pow')`
> 
> Is this a change to how something works or a bug ?
> 
> (My script reads virtual sensors and updates others as a result)

Please check [this forum post](https://www.domoticz.com/forum/viewtopic.php?f=59&t=29973) Where it was announced that the change to Lua 5.3 has some breaking changes. One of them being the deprecated math.pow function

Please change math.pow(x, y) to x^y in your scripts.
also please state your version when reporting an issue. Thx !

**Comment by kevsterd** [comment]
Will do.  Thanks for pointing the link out.

Updated:  Yes that fixed it.  Updated forum post with my issue.

**Comment by gizmocuz** [comment]
@rwaaren , you could be right, let me double check this (windows and lua version)
Done, will be updated next time

**Comment by rwaaren** [comment]
Thx !!
Solved in V4.11476

**Comment by stephanvdplas** [comment]
Issue solved. Thanks!
