### ISSUE TITLE
Hue lights no percentage when switched on

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3712]
V4.11436

i noticed lately that the Hue lights will not reflect the percentage anymore when switched On

using the slider or script to switch on
Status reflects **Percentage**

using the on button or the On command
Status reflects **On**

this used to work in the past.
If the light is on but set to  a certain level the percentage should always be reflected

functionality is working when using a zwave dimmer(FGD212) so this definately is a bug, not a feature

![hue](https://user-images.githubusercontent.com/16853535/68277744-21b3f380-0070-11ea-9444-d3634bdf35bd.JPG)

**Comment by rwaaren** [comment]
See also [ Forum discussion ](https://www.domoticz.com/forum/viewtopic.php?f=68&t=30036&sid=7bebd595c93ed8d88cfe8a5fc461ce94#p227644)

**Comment by GravityRZ** [comment]
added additional info on the forum.

I think it is best to derive the light status(ON, OFF, 35%) from the light itself or from the domoticz light slider(0=OFF, 100=ON, in between is percentage
this way it works regardless of the command send to the light(Set Level for Zwave, Set Color for Hue)

please check the code between zwave dimmer buttons and hue device buttons
please check the code which is used to derive the status of the light(On, OFF, Percentage) between a zwave dimmer and a hue light.

the devices react differently so the must be a difference in the way things are handled

**Comment by GravityRZ** [comment]
Bump.
can we have a look at this?

HUE ON button for a RGBWW light now generates ON, i think this needs to be Set Color

Hue app works like this
Domoticz script works like this

easy change(but i can not do it)

**Comment by gizmocuz** [comment]
@GravityRZ , why are you not able to make the change ? It would be the best, you can test your change, and then make a patch ?
A "On" is something else then 'Set Color' ! It probably turns on the last color used

**Comment by GravityRZ** [comment]
I would not know how to change it. 
If you switch a hue color light on with anything but the domoticz hue button it sends a SetColor to the light. This indeed means last light level and color. So why should a domoticz on button send anything else?  

Even a zwave dimmer sends out set level(and not ON) when uou press the on button
Like i said domoticz buttons are not following the standard. 

This was not always the case so this changed somewhere in time

**Comment by gizmocuz** [comment]
@GravityRZ , that's not true for ZWave, for ZWave when you switch "On" or "Off" you actually set a binary value to true or false.
Nothing send for color information or brightness

Coming back to your Hue issue, I had a look in the code...

CPhilipsHue::SwitchLight

As you can see here in this code section, a On / Off is also a different command then Set Level / Set White / Set Hue / Set xxxx, you get the idea..
So also here, a On / Off is different then when you set a color
The hue will turn On at the last configured color

**Comment by petergebruers** [comment]
> Even a zwave dimmer sends out set level(and not ON) when uou press the on button

Are you talking about Domoticz? I haven't checked the Domticz code but Z-Wave does have the concept of "turn on to the last set value", it is in the spec and all multilevel devices have that. Some devices eg Fibaro FGD-212 have a parameter to force a value for on instead of last set...

Technically speaking, valid levels are (decimal):
-0 off
-1 lowest brightness or level
-99 maximum brightness or level aka 100%
-255 turn on to last remembered non-zero value.
Values 100 - 254 are invalid.

You'll often see people accidentally send 100 because you would think that is 100% but it is not, 99 is highest number. Imho most devices gracefully handle 100 but you might be surprised if you retrieve their level: they'll respond with "99".

On Fibaro Home sensor, the "on" button does send 255, meaning that if you turned off the dimmer when it was at 17, it will return to 17.

Spec:
SDS13781 Z-Wave Application Command Class Specification.pdf
Table 81, Multilevel Switch Set :: Value

States 1-99 and 255 are considered to be "on" states and 0 is off.

**Comment by GravityRZ** [comment]
I am talking about de buttons in domoticz when you switch on a zwave dimmer. 
When you press on it sends set level and uses the last used level. The same should go for a hue light but with hue color lights it needs to send a set color. 

So press ON In the hue app generates set color in domoticz
Press ON in domoticz generates ON

**Comment by gizmocuz** [comment]
@GravityRZ , when you use the On/Off buttons in Domoticz it sends a On / Off command, for both Hue and ZWave
You can see this when you open the network console

**Comment by GravityRZ** [comment]
But i am looking at the log from thr switch

Zwave dimmer gets a set level when on is pressed  

Please note that i am talking about what is reported on the light status. 

So the functionslity of the light is correct but the hue light displays on while it should display eg 80%
Look at the pictures and you instantly see what is wrong

I then look in the log and see on is send instead of set color

So either the command is wrong or the code which displays the status is wrong

Look at the pictures, the light status and the position of the slider. They should all match

**Comment by GravityRZ** [comment]
The lights which have the status ON were switched on using the domoticz on button

**Comment by gizmocuz** [comment]
@GravityRZ , I am talking about what is happening internally.
Again:
- When you flip a On / Off switch, a On / Off is send to the hardware (Hue/ZWave), not a level/colour

In the switch log in Domoticz, it should say On/Off. But for some hardware like 'Klik-Aan-Klik-Uit' or other 433Mhz devices, we DO need to also send a level... this is NOT the case for Hue/ZWave
So maybe someone programmed in the switch log to show the level, but that is internally NOT the case for Hue/ZWave, so maybe that is why there is confusion.

That you maybe use a third party Hue application, and this application does send a color command instead of a On / Off, that could be.

I am closing this issue as what is send to the hardware is correct

**Comment by GravityRZ** [comment]
i do not agree on closing this one.
i understand that you say the problem is not in the commands send(whether it is ON or Set Color)

So let's assume the commands are correct.

Then still if the light is turned on but burning at 50% it should say 50% regardless off how it was switched on.

This is not the case with the HUE color light.

when i switch the light on by pressing the ON button from the official HUE app the light comes on at the last level/color used and is displaying the last level/color used(THIS IS GOOD)

When using the domoticz ON button to switch the HUE  light on it displays ON instead of 50%
when using the domoticz ON button to switch on the ZWAVE dimmer light it displays 50%(and not ON)

so either way you put it it does not add up.

there is a difference a ZWAVE dimmer light behaves when compared to a HUE light when it comes to the displayed status of the light.

HUE
domoticz ON command in switchlog:ON status ON

ZWAVE dimmer
domoticz ON command in switchlog:Set Level  status:percentage

**Comment by GravityRZ** [comment]
i can not believe it is costing me so much effort to confince anybody that this is wrong.

A user interface should ALWAYS reflect the correct current status of a device

Green is Right
Red is WRONG(in any universe)

if the light is on but the slider is set to the current level and the light is glowing at that same level what is the use of status ON when we can exactly say how bright it is shining

a yes, now i can see how the light was switched on(with the ON button)
duhhh, who cares. If it is shining at a certain level i want to see that level(like it is with the Zwave dimmer light)



![hue-v2](https://user-images.githubusercontent.com/16853535/68779262-a5537e80-0634-11ea-8b12-a6ccdc778e27.jpg)

**Comment by gizmocuz** [comment]
I think it is time YOU start to learn programming!

**Comment by GravityRZ** [comment]
i think you are right (no offense taken). spotting problems is one thing. solving them a complete other story. can you point me to the part of the code were this happens?

i discovered something strange.
when stopping domoticz and starting it again the lights all show the correct percentage status (when they are on)
now when i switch a light off and back on again using the on button the percentage shows up again and in the log it states it receivved the set color command.

this only happens once, so the first time it reacts exactly like it should and i would like it. after that it is back to the ON status.
code producing different results when the same action is taken is not a good thing

**Comment by GravityRZ** [comment]
i bypassed the bug by updating the hue status using a dzVents script

every on command fired at the light will result in an updated light status with the correct percentage displayed.(like it should have been coded from the start)

problem  solved

**Comment by gizmocuz** [comment]
@GravityRZ , could you share your script ?

**Comment by GravityRZ** [comment]
sure, 
the silent part is important otherwise it starts to loop the command.

```
`-- there is a bug in the hue code which changes the light state of a Hue RGBWW light to ON
-- when you switch the light On in domoticz by using the ON button
-- using the slider, script or the original Hue app will not cause this, only when the On button of the RGBWW light is pressed in Domoticz
-- the correct status should be the light Percentage and not ON
-- This script reads the current dimlevel and send the command to the light.

return {
	on = {
	    -- include all the HUE lights which need this correction
		devices = {
            'Dressoirlamp',
            'Bamboelampklok',
            'Bamboelamphoek',
            'Dressoirlamptoog',
            'LampachterTV'
            },
	},

	execute = function(domoticz, trigger)
    local dimlevel = domoticz.devices(trigger.name).level
    if trigger.state == 'On' then
        domoticz.devices(trigger.name).dimTo(dimlevel).silent()
     
     end
	end
}
`
```

**Comment by dannybloe** [comment]
So the dimlevel is correctly available in the underlying data. Looks like it is just a GUI issue then.

(btw dzVents r0cks! 😉)

**Comment by GravityRZ** [comment]
Yes the dimlevel is correctly available but i doubt if it is a gui problem.
i see different commands send in the log of the light but i do not want to start the discussion again.
indeed dzVents r0cks. every day i am amazed what it can do.

ofcourse it helps a lot if peope like @waaren  jump in once in a while to show the power of dzVents

**Comment by dannybloe** [comment]
Btw, you can do this: `trigger.dimTo(dimLevel).silent()`

**Comment by GravityRZ** [comment]
Hmm. every time it try to do someting smart like that i get errors.
that is the reason why i mostly use the complete domoticz.devices and if i can add the .name.

indeed that works :-)
