### ISSUE TITLE
Humidity control

### ISSUE THREAD

**Issue by Addie363** [domoticz/domoticz#3714]
After last update to version Version: 4.11468 Build Hash: 508cc66a1 humidity control is not working anymore. In the log I see Error: EventSystem: Error updating variable humidityTmin5: Not a valid integer. The humidity is send now with a tenth of a grade (68.3) instead of decimals. Is this a bug?

**Comment by rwaaren** [comment]
Please use the forum for reporting script type of problems. And have a look at 
https://www.domoticz.com/forum/viewtopic.php?f=59&t=29973
