### ISSUE TITLE
Cannot set some Evohome modes

### ISSUE THREAD

**Issue by Jaap-Jan** [domoticz/domoticz#372]
Setting 'Day Off', 'Custom' or 'Heating Off' doesn't have any effect. The controller doesn't change the mode, though the API briefly displays the new state before restoring the state the controller actually has.

The other modes ('Normal', 'Economy' and 'Away') work as expected.

**Comment by gizmocuz** [comment]
Please use our forum, or if you made a patch, please do a pull request
