### ISSUE TITLE
When enable Buienradar in the hardware tab domoticz will crash within aprox 1 hour

### ISSUE THREAD

**Issue by Happyboy0980** [domoticz/domoticz#3720]
When enabling Buienradar in the hardware tab domoticz will crash within aprox 1 hour. 
When disabled everything runs fine.
In previous beta i had a simulair issue with this hardware.

Domoticz crash log looks as follow :

`[New LWP 22441]
[New LWP 22446]
[New LWP 22447]
[New LWP 22455]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
0x76e0851c in __waitpid (pid=22456, stat_loc=0x7ee88058, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
29      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame
* 1    Thread 0x7636c950 (LWP 22440) "domoticz" 0x76e0851c in __waitpid (pid=22456, stat_loc=0x7ee88058, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  2    Thread 0x75f34430 (LWP 22441) "Watchdog" 0x76e07d60 in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  3    Thread 0x75733430 (LWP 22446) "SQLHelper" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  4    Thread 0x74f32430 (LWP 22447) "PluginMgr" 0x76e07d60 in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  5    Thread 0x74391430 (LWP 22455) "InfluxPush" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37

Thread 5 (Thread 0x74391430 (LWP 22455)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x00aabf44 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x003f8bb8 in CInfluxPush::Do_Work() ()
#3  0x00acead4 in execute_native_thread_routine ()
#4  0x76dfcfc4 in start_thread (arg=0x74391430) at pthread_create.c:458
#5  0x76cbb038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 0x74f32430 (LWP 22447)):
#0  0x76e07d60 in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x002a6d2c in sleep_milliseconds(long) ()
#2  0x0066a38c in Plugins::CPluginSystem::Do_Work() ()
#3  0x00acead4 in execute_native_thread_routine ()
#4  0x76dfcfc4 in start_thread (arg=0x74f32430) at pthread_create.c:458
#5  0x76cbb038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0x75733430 (LWP 22446)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x00aabf44 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x00321b54 in CSQLHelper::Do_Work() ()
#3  0x00acead4 in execute_native_thread_routine ()
#4  0x76dfcfc4 in start_thread (arg=0x75733430) at pthread_create.c:458
#5  0x76cbb038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0x75f34430 (LWP 22441)):
#0  0x76e07d60 in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x002a6d2c in sleep_milliseconds(long) ()
#2  0x00309dd0 in Do_Watchdog_Work() ()
#3  0x00acead4 in execute_native_thread_routine ()
#4  0x76dfcfc4 in start_thread (arg=0x75f34430) at pthread_create.c:458
#5  0x76cbb038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0x7636c950 (LWP 22440)):
#0  0x76e0851c in __waitpid (pid=22456, stat_loc=0x7ee88058, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x0030968c in dumpstack_gdb(bool) ()
#2  0x00309c80 in signal_handler(int, siginfo_t*, void*) ()
#3  <signal handler called>
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#5  0x76c16824 in __GI_abort () at abort.c:89
#6  0x00af8494 in __gnu_cxx::__verbose_terminate_handler() ()
#7  0x00a58b84 in __cxxabiv1::__terminate(void (*)()) ()
#8  0x00a58bf8 in std::terminate() ()
#9  0x00226e3c in main ()

Main thread:
#0  0x76e0851c in __waitpid (pid=22456, stat_loc=0x7ee88058, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x0030968c in dumpstack_gdb(bool) ()
#2  0x00309c80 in signal_handler(int, siginfo_t*, void*) ()
#3  <signal handler called>
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#5  0x76c16824 in __GI_abort () at abort.c:89
#6  0x00af8494 in __gnu_cxx::__verbose_terminate_handler() ()
#7  0x00a58b84 in __cxxabiv1::__terminate(void (*)()) ()
#8  0x00a58bf8 in std::terminate() ()
#9  0x00226e3c in main ()
`

**Comment by waltervl** [comment]
Not enough information, issue can be closed.
