### ISSUE TITLE
iterator out of bound

### ISSUE THREAD

**Issue by RDols** [domoticz/domoticz#3721]
First, I'm the same person as RedDigital. I'm cleaning up / merging various accounts i have on github.

During some testing i had a crash in CEventSystem::GetEventTrigger. I saw the iterator go out of bound. Just found a closed issue item on this too: #2644. But was not fixed at that time.

**Comment by RDols** [comment]
Problem occurs when m_eventtrigger has only one element. The line

`itt = m_eventtrigger.erase(itt) - 1;`

wil get the iterator out of bound. Erase return the element after what is erased. That would be "end". since m_eventtrigger has 0 elements left, subtracting 1 will make the iterator go out of bound.

**Comment by RDols** [comment]
I make a PR in few minutes.

**Comment by gizmocuz** [comment]
Thanks for spotting! Merged the PR, thank you !
