### ISSUE TITLE
Console Error on FloorPlan configuration

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#3723]
The last beta 4.11474

Steps:
1) run domoticz
2) go to More Option->Plans->FloorPlan
3) go to More Option->Plans->RoomPlan
4) go to More Option->Plans->FloorPlan
5) select any floor plan

Error in console (and floor plan don't show):
domoticzdevices.js:819 Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at Function.Device.initialise (domoticzdevices.js:819)
    at RefreshPlanTable (FloorplanEditController.js:526)
    at FloorplanEditController.js:400
    at ConfirmNoUpdate (FloorplanEditController.js:698)
    at HTMLTableRowElement.<anonymous> (FloorplanEditController.js:382)
    at HTMLTableSectionElement.dispatch (jquery-3.4.1.min.js:2)
    at HTMLTableSectionElement.v.handle (jquery-3.4.1.min.js:2)

**Comment by rwaaren** [comment]
Cannot replicate this on Raspberry with Debian Buster on V4.11474. 
What hardware / OS do you see this on ?
Did you do a clear cache and a clear appcache (different things).

**Comment by szczukot** [comment]
Yes. All cache are clear.
Did You check the steps exactly as I wrote?
First time on FloorPlan thsi error not exists (point 2). But when i go to floorplan->roomplan->floorplan i have this error

I tested it on 3 browsers (chrome, IE, Edge)

**Comment by rwaaren** [comment]
I think I did but maybe I don't understand the sequence of your steps the way you mean them. Can you include screenshots so that the chance of miscommunication is less ?

**Comment by szczukot** [comment]
I run domoticz dashboard
I click Setup->More Options->Plans->FloorPlan
I click Setup->More Options->Plans->RoomPlan
I click Setup->More Options->Plans->FloorPlan
Line 807 (domoticzdevice.js) executed 2 times. But second time IF is not exexuted (false) and devCont = undefined.

**Comment by gizmocuz** [comment]
I am also not able to replicate this. Maybe it is depending on the devices you have in the plans.
Could you contact me on the forum ? (PM) I would like to debug your database if possible.
Is everything working besides the console error ?

Else please try to debug the html code and if needed make a patch

**Comment by szczukot** [comment]
Resolved by #3835
