### ISSUE TITLE
Evohome cannot connect with HGI80 on COM port

### ISSUE THREAD

**Issue by Olifant1990** [domoticz/domoticz#3725]
Last Sunday I updated my version to 4.11476 (Windows 10 PC).
After the update my Evohome connection with HGI80 isn't working anymore.
It says: Error opening serial port: COM4.
When trying to connect with COM4 with putty, I have no problems.
I rebooted my PC, changed the USB port etc. No solutions.
Something changed in the serial connections?
I went back to Domoticz version 4.11455 and it is connecting again.

**Comment by RicardP** [comment]
@Olifant1990 Same issue for me on 4.11476 regarding COM-port and RFXCom and Windows 10 platform.
Went back to 4.11468 = OK

**Comment by gizmocuz** [comment]
Found the issue. Boost 1.71 has different code than previous versions in win_iocp_serial_port_service.ipp
(open function)
The call to SetCommState fails....
I have to see what i can do about this, maybe overrule the function or revert to boost 1.70 ...

**Comment by gizmocuz** [comment]
Should be solved now (win32 builds using patched boost library)

**Comment by RicardP** [comment]
@gizmocuz Confirmed, works in 4.11490 Many thanks!!
