### ISSUE TITLE
Nest w/ Google Account

### ISSUE THREAD

**Issue by FoUStep** [domoticz/domoticz#3726]
As of 31st of August, Nest migrates to a Google Account (the old way works for a while, however new accounts do not work anymore). The homebridge-nest module was able to implement it with the following code:

>             "platform": "Nest",
>             "googleAuth": {
>                 "issueToken": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken...",
>                 "cookies": "OCAK...",
>                 "apiKey": "AIza..."
>             }

They've managed to obtain it through this:
> The values of "issueToken", "cookies" and "apiKey" are specific to your Google Account. To get them, follow these steps (only needs to be done once, as long as you stay logged into your Google Account).
> 
> Open a Chrome browser tab in Incognito Mode (or clear your cache).
> Open Developer Tools (View/Developer/Developer Tools).
> Click on 'Network' tab. Make sure 'Preserve Log' is checked.
> In the 'Filter' box, enter issueToken
> Go to home.nest.com, and click 'Sign in with Google'. Log into your account.
> One network call (beginning with iframerpc) will appear in the Dev Tools window. Click on it.
> In the Headers tab, under General, copy the entire Request URL (beginning with https://accounts.google.com, ending with nest.com). This is your "issueToken" in config.json.
> In the 'Filter' box, enter oauth2/iframe
> Several network calls will appear in the Dev Tools window. Click on the last iframe call.
> In the Headers tab, under Request Headers, copy the entire cookie (beginning with OCAK=... - do not include the cookie: name). This is your "cookies" in config.json.
> In the 'Filter' box, enter issue_jwt
> Click on the last issue_jwt call.
> In the Headers tab, under Request Headers, copy the entire x-goog-api-key (do not include the x-goog-api-key: name). This is your "apiKey" in config.json.

Also see [this](https://www.npmjs.com/package/homebridge-nest).

Is there anyway to get this working in Domoticz? Oauth and user/pass do not work anymore with Google Accounts, which makes the Nest useless in Domoticz.

**Comment by gizmocuz** [comment]
Is this the same issue ?

https://github.com/domoticz/domoticz/issues/3729

Then maybe this is solved now ?

**Comment by FilipDem** [comment]
Don't think it is the same. The #3729 still uses the NEST login. 
See also https://www.domoticz.com/forum/viewtopic.php?f=34&t=29984 (I wrote a workaround python plugin) to support Google Accounts for Nest. Anyway hope on a real plugin when Google APIs for Nest are available.

**Comment by waltervl** [comment]
Issue can be closed, implemented with Python plugin.
