### ISSUE TITLE
Cmake error on macOS after "Updated to MQTT 1.6.7" commit

### ISSUE THREAD

**Issue by petergebruers** [domoticz/domoticz#3730]
Travis already flagged it...

https://travis-ci.org/domoticz/domoticz/builds/612724881?utm_source=github_status&utm_medium=notification

On my Mac:

git clean -d -f -x

cmake -DCMAKE_BUILD_TYPE=Debug CMakeLists.txt -DUSE_OPENSSL_STATIC="NO"

logging stuff...

CMake Error at MQTT/CMakeLists.txt:40 (ADD_LIBRARY):
  Cannot find source file:

    read_handle_client.c

That version of MQTT/CMakeLists.txt probably does not belong to 1.6.7

For fun and giggles, I removed everything on line 40 that is no longer there and then Cmake will be happy, but I don't think that will lead to a working mqtt lib...

I might be able to spend some more time on this tomorrow.

**Comment by petergebruers** [comment]
Little bit of progress...

Copy the source file names listed on and after line 10 of the Mosquitto file here https://github.com/eclipse/mosquitto/blob/master/lib/CMakeLists.txt

Over the source file list at line 40 in MQTT/CMakeLists.txt

Makes cmake happy, "make" succeeds in compiling but fails linking with error:

[100%] Linking CXX executable domoticz
ld: library not found for -lmqtt

I noticed it did build a "libMQTT.a".

Unfortunately I have to go now...

**Comment by gizmocuz** [comment]
Thanks for reporting! Solved now....

**Comment by petergebruers** [comment]
Thanks, I can confirm this works on my Mac.
