### ISSUE TITLE
OpenZwave is causing 100% CPU

### ISSUE THREAD

**Issue by prein2** [domoticz/domoticz#3739]
Weird problem: Since a few days Domoticz is causing 100% CPU, when disabling openZwave, CPU utilisation is normal again. When the 100% CPU occurs, eventually nodes do not get updated meaning nothing Zwave related works anymore.

Strange thing:
nothing in OZWlog
nothing in domoticz log

Running latest beta on odroid c2 (friends system on latest beta has no problems) so now 4.11503

So where to start looking. How can I get more logging? 
problem started when updating to the 11 november dev version. since then updated to every latest dev version and the problem persisted.

reverting to latest stable results in domoticz not starting (guess some breaking change somewhere)
I don't know how to revert to the pre-11 november dev version.

so any tips to help me search for the problem?

**Comment by prein2** [comment]
OZWlog: 
system started 20.56, going to 100% at 21.20 nothing in the log...

`2019-11-20 20:56:23.918 Always, OpenZwave Version 1.6-943-gacce060e-dirty Starting Up
2019-11-20 20:56:23.937 Always, Using Language Localization 
2019-11-20 20:56:31.760 Error, Node003, ERROR: Dropping command, expected response not received after 1 attempt(s)
2019-11-20 20:56:31.761 Always, 
2019-11-20 20:56:31.761 Always, Dumping queued log messages
2019-11-20 20:56:31.761 Always, 
2019-11-20 20:56:31.761 Always, 
2019-11-20 20:56:31.761 Always, End of queued log message dump
2019-11-20 20:56:31.761 Always, 
2019-11-20 20:56:36.834 Error, Node003, ERROR: Dropping command, expected response not received after 1 attempt(s)
2019-11-20 20:56:36.835 Always, 
2019-11-20 20:56:36.835 Always, Dumping queued log messages
2019-11-20 20:56:36.835 Always, 
2019-11-20 20:56:36.835 Always, 
2019-11-20 20:56:36.835 Always, End of queued log message dump
2019-11-20 20:56:36.835 Always, 
`

**Comment by prein2** [comment]
never mind. USB issue.. USB keeps disconnecting and connecting.

**Comment by petergebruers** [comment]
Did you upgrade to Raspberry pi 4 and Aeotec stick? I've read about incompatibilities with USB3. Solved by connecting stick to USB2 hub.

**Comment by gizmocuz** [comment]
Could also be your power adapter, make sure it has enough Amps !... try another one...
I once had many crashes and weird behavior which i could not explain, until i run a overclock test and was pointed at a possible problem with my power adapter.
Changed it, all issues where resolved...

**Comment by prein2** [comment]
Uusing an odroid c2.
Started to read many forum threads on USB problems. I recognise a lot.. I have 4 USB devices connected of which a few run from a powered USB hub.

I am thinking of switching to another system (odroid N2 perhaps.. I like the emmc too much to switch back to pi..)

My C2 is running of a 6,5A power supply. the powered USB hub from a seperate 2.4A power supply. So power shouldn't be the problem.

**Comment by petergebruers** [comment]
Sounds like you have very good hardware. I like emmc too (using it on my NanoPi M4 RK3399 SoC - have a look at the Nanopi M4V2) but most of my test systems don't have emmc (OrangePi Soc). In that case, I only boot from SD then run databases, Domoticz, home assistant in systemd-nspawn containers on a USB connected SSD. So itI have lot's of USB traffic. But... I am not running Domoticz in production on those systems right now, but HASS. I test different systems.

I tell you this because I am an OpenZWave contributor and I work mostly on my Mac but also on those systems and I have not seen 100% CPU loops (yet - never say never). Needless to say I often throw "garbage" at OZW eg when I select wrong port... This proves nothing but I'd say... I'd rather keep an eye on the progress you make :wink:

**Comment by prein2** [comment]
status so far: something is causing USB disconnects:

device number 30+ woow, that means may USB reconnects since boot...
And the usb disconnects cause openzwave to go to 100%, a known bug.

strange thing is.. didn't change anything, but it is working since yesterday 21.20 without problems.
continuing to dive into the USB problems..

`Nov 20 21:14:31 localhost kernel: [11350.014624] usb 1-1.2: USB disconnect, device number 29
Nov 20 21:14:31 localhost kernel: [11350.019740] usb 1-1.2.1: USB disconnect, device number 30
Nov 20 21:14:31 localhost kernel: [11350.026359] ftdi_sio ttyUSB1: FTDI USB Serial Device converter now disconnected from ttyUSB1
Nov 20 21:14:31 localhost kernel: [11350.041205] ftdi_sio 1-1.2.1:1.0: device disconnected
Nov 20 21:14:31 localhost kernel: [11350.046575] usb 1-1.2.3: USB disconnect, device number 31
Nov 20 21:14:31 localhost kernel: [11350.051530] usb 1-1.2.3.1: USB disconnect, device number 32
Nov 20 21:14:32 localhost kernel: [11350.296419] usb 1-1.2: new full-speed USB device number 33 using dwc_otg
Nov 20 21:14:32 localhost kernel: [11350.396656] usb 1-1.2: not running at top speed; connect to a high speed hub
Nov 20 21:14:32 localhost kernel: [11350.404254] hub 1-1.2:1.0: USB hub found
Nov 20 21:14:32 localhost kernel: [11350.409677] hub 1-1.2:1.0: 4 ports detected
Nov 20 21:14:32 localhost kernel: [11350.786411] usb 1-1.2.1: new full-speed USB device number 34 using dwc_otg
Nov 20 21:14:32 localhost kernel: [11351.015256] ftdi_sio 1-1.2.1:1.0: FTDI USB Serial Device converter detected
Nov 20 21:14:32 localhost kernel: [11351.021628] usb 1-1.2.1: Detected FT232RL
Nov 20 21:14:32 localhost kernel: [11351.026554] usb 1-1.2.1: Number of endpoints 2
Nov 20 21:14:32 localhost kernel: [11351.031377] usb 1-1.2.1: Endpoint 1 MaxPacketSize 64
Nov 20 21:14:32 localhost kernel: [11351.036091] usb 1-1.2.1: Endpoint 2 MaxPacketSize 64
Nov 20 21:14:32 localhost kernel: [11351.040799] usb 1-1.2.1: Setting MaxPacketSize 64
Nov 20 21:14:32 localhost kernel: [11351.045842] usb 1-1.2.1: FTDI USB Serial Device converter now attached to ttyUSB1
Nov 20 21:14:33 localhost kernel: [11351.246362] usb 1-1.2.3: new full-speed USB device number 35 using dwc_otg
Nov 20 21:14:33 localhost kernel: [11351.466688] usb 1-1.2.3: not running at top speed; connect to a high speed hub
Nov 20 21:14:33 localhost kernel: [11351.474030] hub 1-1.2.3:1.0: USB hub found
Nov 20 21:14:33 localhost kernel: [11351.478957] hub 1-1.2.3:1.0: 4 ports detected
Nov 20 21:14:33 localhost kernel: [11351.876338] usb 1-1.2.3.1: new full-speed USB device number 36 using dwc_otg
Nov 20 21:14:34 localhost kernel: [11352.105689] cdc_acm 1-1.2.3.1:1.0: ttyACM1: USB ACM device`

**Comment by prein2** [comment]
Just to get back on everybody:
This has nothing to do with Domoticz. Turns out that there are some USB problems:
https://forum.odroid.com/viewtopic.php?f=141&t=23733

This causes disconnects which causes openZwave to go to 100% CPU (known bug):
https://github.com/OpenZWave/open-zwave/issues/111

So what I did: reshuffled my USB devices and the problem has been gone for 5 days now..

**Comment by gizmocuz** [comment]
Thank you for the feedback!
