### ISSUE TITLE
Problem to build domoticz beta this morning

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#3746]
[domoticz@rasp beta-domoticz]$ git pull

> remote: Enumerating objects: 190, done.
> remote: Counting objects: 100% (190/190), done.
> remote: Compressing objects: 100% (77/77), done.
> remote: Total 190 (delta 134), reused 142 (delta 113), pack-reused 0
> Receiving objects: 100% (190/190), 155.53 KiB | 856.00 KiB/s, done.
> Resolving deltas: 100% (134/134), completed with 68 local objects.
> From https://github.com/domoticz/domoticz
>    fdc90742a..26783ab3f  development -> origin/development
> Updating fdc90742a..26783ab3f
> Fast-forward
>  .travis.yml                                       |    2 +-
>  CMakeLists.txt                                    |   60 +-
>  MQTT/CMakeLists.txt                               |    4 +-
>  MQTT/mosquittopp.h                                |  133 ---
>  hardware/1Wire/1WireForWindows.cpp                |   29 +-
>  hardware/AccuWeather.cpp                          |    8 +-
>  hardware/AtagOne.cpp                              |    5 +-
>  hardware/BleBox.cpp                               |    5 +-
>  hardware/Buienradar.cpp                           |    8 +-
>  hardware/ColorSwitch.cpp                          |    9 +-
>  hardware/DarkSky.cpp                              |    5 +-
>  hardware/Ec3kMeterTCP.cpp                         |    5 +-
>  hardware/EcoCompteur.cpp                          |   14 +-
>  hardware/EcoDevices.cpp                           |    5 +-
>  hardware/EnphaseAPI.cpp                           |    6 +-
>  hardware/EvohomeWeb.cpp                           |   40 +-
>  hardware/EvohomeWeb.h                             |    2 +-
>  hardware/GoodweAPI.cpp                            |    8 +-
>  hardware/HEOS.cpp                                 |    5 +-
>  hardware/HarmonyHub.cpp                           |    5 +-
>  hardware/Honeywell.cpp                            |   14 +-
>  hardware/ICYThermostat.cpp                        |    8 +-
>  hardware/InComfort.cpp                            |    5 +-
>  hardware/Kodi.cpp                                 |    5 +-
>  hardware/LogitechMediaServer.cpp                  |    5 +-
>  hardware/MQTT.cpp                                 |   11 +-
>  hardware/MQTT.h                                   |   12 +-
>  hardware/NefitEasy.cpp                            |   20 +-
>  hardware/Nest.cpp                                 |    8 +-
>  hardware/NestOAuthAPI.cpp                         |   13 +-
>  hardware/Netatmo.cpp                              |   24 +-
>  hardware/OpenWeatherMap.cpp                       |    5 +-
>  hardware/OpenWebNetTCP.cpp                        |    8 +-
>  hardware/PhilipsHue/PhilipsHue.cpp                |   14 +-
>  hardware/SolarEdgeAPI.cpp                         |   11 +-
>  hardware/TTNMQTT.cpp                              |   11 +-
>  hardware/TTNMQTT.h                                |   12 +-
>  hardware/Tado.cpp                                 |   10 +-
>  hardware/Thermosmart.cpp                          |    8 +-
>  hardware/ToonThermostat.cpp                       |   22 +-
>  hardware/Winddelen.cpp                            |    5 +-
>  hardware/Wunderground.cpp                         |    8 +-
>  hardware/XiaomiGateway.cpp                        |   14 +-
>  hardware/YouLess.cpp                              |    5 +-
>  hardware/csocket.cpp                              |    2 +-
>  hardware/plugins/PluginProtocols.cpp              |   10 +-
>  hardware/serial/impl/unix.cpp                     |    2 +-
>  json/allocator.h                                  |  147 ++-
>  json/assertions.h                                 |   31 +-
>  json/autolink.h                                   |   25 -
>  json/config.h                                     |  200 ++--
>  json/forwards.h                                   |   10 +-
>  json/json.h                                       |    8 +-
>  json/json_batchallocator.h                        |  127 ---
>  json/{features.h => json_features.h}              |   26 +-
>  json/json_internalarray.inl                       |  454 ---------
>  json/json_internalmap.inl                         |  615 ------------
>  json/json_reader.cpp                              |  957 +++++++++---------
>  json/json_tool.h                                  |   55 +-
>  json/json_value.cpp                               | 1066 +++++++++++----------
>  json/json_valueiterator.inl                       |   41 +-
>  json/json_writer.cpp                              |  777 ++++++++-------
>  json/reader.h                                     |  389 ++++----
>  json/value.h                                      |  551 ++++++-----
>  json/version.h                                    |   26 +-
>  json/writer.h                                     |  256 ++---
>  main/EventSystem.cpp                              |   10 +-
>  main/LuaCommon.cpp                                |    5 +-
>  main/Scheduler.cpp                                |    5 +-
>  main/json_helper.cpp                              |   41 +
>  main/json_helper.h                                |    8 +
>  MQTT/mosquittopp.cpp => main/mosquitto_helper.cpp |  112 +--
>  main/mosquitto_helper.h                           |  119 +++
>  msbuild/domoticz.vcxproj                          |    9 +-
>  msbuild/domoticz.vcxproj.filters                  |   18 +-
>  notifications/NotificationGCM.cpp                 |    8 +-
>  notifications/NotificationPushbullet.cpp          |    7 +-
>  notifications/NotificationTelegram.cpp            |    7 +-
>  webserver/WebsocketHandler.cpp                    |   18 +-
>  79 files changed, 2775 insertions(+), 3983 deletions(-)
>  delete mode 100644 MQTT/mosquittopp.h
>  delete mode 100644 json/autolink.h
>  delete mode 100644 json/json_batchallocator.h
>  rename json/{features.h => json_features.h} (71%)
>  delete mode 100644 json/json_internalarray.inl
>  delete mode 100644 json/json_internalmap.inl
>  create mode 100644 main/json_helper.cpp
>  create mode 100644 main/json_helper.h
>  rename MQTT/mosquittopp.cpp => main/mosquitto_helper.cpp (71%)
>  create mode 100644 main/mosquitto_helper.h

[domoticz@rasp beta-domoticz]$ make
```
-- ###########################
-- Compiling Revision #11514
-- ###########################
-- Use builtin lua library
-- Using builtin Mosquitto library
-- Python3 includes found at: /usr/include/python3.7m
-- Building with I2C support
-- Building with SPI support
-- OPENSSL library found at: /usr/lib/libssl.a;/usr/lib/libcrypto.a
-- Linking against boost static libraries
-- Boost  found.
-- Found Boost components:
   thread;system
-- BOOST libraries found at:
-- Boost includes found at:
-- ZLIB library found at: /usr/lib/libz.so
-- ZLIB includes found at: /usr/include
-- Curl library found at: /usr/lib/libcurl.so
-- Curl includes found at: /usr/include
-- LIBUSB library found at: /usr/lib/libusb.so
-- /usr/share/domoticz/open-zwave-read-only/libopenzwave.a
-- GPIO is not available
-- Not found telldus-core (telldus-core.h), not adding tellstick support
/usr/bin/c++  ;;-std=c++11;-Wno-psabi;;-I/usr/include/python3.7m;-I/usr/share/domoticz/beta-domoticz/main;-I/usr/share/domoticz/beta-domoticz/tinyxpath;-I/usr/include;-I/usr/local/include;-I/usr/include;-I/usr/share/domoticz/beta-domoticz/zip;-I/usr/include;-I/usr/share/domoticz/beta-domoticz/hardware/openzwave;-DBUILTIN_MQTT;-DENABLE_PYTHON;-DHAVE_EXECINFO_H;-DHAVE_LINUX_I2C;-DHAVE_LINUX_SPI;-DWWW_ENABLE_SSL;-DWITH_TLS;-DWITH_LIBUSB;-DWITH_OPENZWAVE -x c++-header -c -o /usr/share/domoticz/beta-domoticz/stdafx.h.gch/.c++ /usr/share/domoticz/beta-domoticz/main/stdafx.h
-- Using static libgcc/libstdc++
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/share/domoticz/beta-domoticz
[  1%] Built target minizip
[ 12%] Built target lua
Scanning dependencies of target mqtt
[ 12%] Building C object MQTT/CMakeFiles/mqtt.dir/mosquitto.c.o
[ 12%] Building C object MQTT/CMakeFiles/mqtt.dir/actions.c.o
[ 13%] Building C object MQTT/CMakeFiles/mqtt.dir/alias_mosq.c.o
[ 13%] Building C object MQTT/CMakeFiles/mqtt.dir/callbacks.c.o
[ 13%] Building C object MQTT/CMakeFiles/mqtt.dir/connect.c.o
[ 13%] Building C object MQTT/CMakeFiles/mqtt.dir/handle_auth.c.o
[ 14%] Building C object MQTT/CMakeFiles/mqtt.dir/handle_connack.c.o
[ 14%] Building C object MQTT/CMakeFiles/mqtt.dir/handle_disconnect.c.o
[ 14%] Building C object MQTT/CMakeFiles/mqtt.dir/handle_ping.c.o
[ 15%] Building C object MQTT/CMakeFiles/mqtt.dir/handle_pubackcomp.c.o
[ 15%] Building C object MQTT/CMakeFiles/mqtt.dir/handle_publish.c.o
[ 15%] Building C object MQTT/CMakeFiles/mqtt.dir/handle_pubrec.c.o
[ 16%] Building C object MQTT/CMakeFiles/mqtt.dir/handle_pubrel.c.o
[ 16%] Building C object MQTT/CMakeFiles/mqtt.dir/handle_suback.c.o
[ 16%] Building C object MQTT/CMakeFiles/mqtt.dir/handle_unsuback.c.o
[ 17%] Building C object MQTT/CMakeFiles/mqtt.dir/helpers.c.o
[ 17%] Building C object MQTT/CMakeFiles/mqtt.dir/logging_mosq.c.o
[ 17%] Building C object MQTT/CMakeFiles/mqtt.dir/loop.c.o
[ 17%] Building C object MQTT/CMakeFiles/mqtt.dir/memory_mosq.c.o
[ 18%] Building C object MQTT/CMakeFiles/mqtt.dir/messages_mosq.c.o
[ 18%] Building C object MQTT/CMakeFiles/mqtt.dir/net_mosq.c.o
[ 18%] Building C object MQTT/CMakeFiles/mqtt.dir/net_mosq_ocsp.c.o
[ 19%] Building C object MQTT/CMakeFiles/mqtt.dir/options.c.o
[ 19%] Building C object MQTT/CMakeFiles/mqtt.dir/packet_datatypes.c.o
[ 19%] Building C object MQTT/CMakeFiles/mqtt.dir/packet_mosq.c.o
[ 20%] Building C object MQTT/CMakeFiles/mqtt.dir/property_mosq.c.o
[ 20%] Building C object MQTT/CMakeFiles/mqtt.dir/read_handle.c.o
[ 20%] Building C object MQTT/CMakeFiles/mqtt.dir/send_connect.c.o
[ 21%] Building C object MQTT/CMakeFiles/mqtt.dir/send_disconnect.c.o
[ 21%] Building C object MQTT/CMakeFiles/mqtt.dir/send_mosq.c.o
[ 21%] Building C object MQTT/CMakeFiles/mqtt.dir/send_publish.c.o
[ 21%] Building C object MQTT/CMakeFiles/mqtt.dir/send_subscribe.c.o
[ 22%] Building C object MQTT/CMakeFiles/mqtt.dir/send_unsubscribe.c.o
[ 22%] Building C object MQTT/CMakeFiles/mqtt.dir/socks_mosq.c.o
[ 22%] Building C object MQTT/CMakeFiles/mqtt.dir/srv_mosq.c.o
[ 23%] Building C object MQTT/CMakeFiles/mqtt.dir/thread_mosq.c.o
[ 23%] Building C object MQTT/CMakeFiles/mqtt.dir/time_mosq.c.o
[ 23%] Building C object MQTT/CMakeFiles/mqtt.dir/tls_mosq.c.o
[ 24%] Building C object MQTT/CMakeFiles/mqtt.dir/utf8_mosq.c.o
[ 24%] Building C object MQTT/CMakeFiles/mqtt.dir/util_mosq.c.o
[ 24%] Building C object MQTT/CMakeFiles/mqtt.dir/util_topic.c.o
[ 25%] Building C object MQTT/CMakeFiles/mqtt.dir/will_mosq.c.o
[ 25%] Linking C static library libmqtt.a
[ 25%] Built target mqtt
[ 26%] Built target sqlite
[ 26%] Built target domoticz_gch
-- Found Git: /usr/bin/git (found version "2.23.0")
[ 26%] Built target revisiontag
Scanning dependencies of target domoticz
[ 27%] Building CXX object CMakeFiles/domoticz.dir/main/Camera.cpp.o
[ 27%] Building CXX object CMakeFiles/domoticz.dir/main/domoticz.cpp.o
[ 28%] Building CXX object CMakeFiles/domoticz.dir/main/EventSystem.cpp.o
[ 28%] Building CXX object CMakeFiles/domoticz.dir/main/IFTTT.cpp.o
[ 29%] Building CXX object CMakeFiles/domoticz.dir/main/json_helper.cpp.o
[ 29%] Building CXX object CMakeFiles/domoticz.dir/main/LuaCommon.cpp.o
[ 30%] Building CXX object CMakeFiles/domoticz.dir/main/LuaHandler.cpp.o
[ 30%] Building CXX object CMakeFiles/domoticz.dir/main/mainworker.cpp.o
In file included from /usr/share/domoticz/beta-domoticz/main/../hardware/MQTT.h:4,
                 from /usr/share/domoticz/beta-domoticz/main/../hardware/MySensorsMQTT.h:3,
                 from /usr/share/domoticz/beta-domoticz/main/mainworker.cpp:75:
/usr/share/domoticz/beta-domoticz/main/../hardware/../main/mosquitto_helper.h:11:10: fatal error: mosquitto.h: No such file or directory
   11 | #include "mosquitto.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/domoticz.dir/build.make:284: CMakeFiles/domoticz.dir/main/mainworker.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/domoticz.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by gizmocuz** [comment]
@pipiche38, sorry but as mentioned before, give developers some time to check the build status of travis/appveyor before posting a issue like this
Just wait at least an hour
I just pushed a commit that 'should' solve this, but again, we have to wait for all build systems to comply.
Yep, making a branch was a better solution and will do so in the feature...
Closing this as it will be solved of course
