### ISSUE TITLE
MQTT Client Gateway and MySensors Gateway with MQTT clash

### ISSUE THREAD

**Issue by kokangit** [domoticz/domoticz#3750]
In summary, the problem is that domoticz connects its mqtt client gateway and its mysensors gateway to the same mqtt broker with the same client id.

Domoticz will connect twice to the mqtt broker with the same client ID. My mosquitto server will report that Domoticz is already connected and close the old connection. This is then repeated approximately every 30 seconds. And on it goes.

I run Domoticz V4.11510 in a docker container on a debian 10 (buster) host. The mqtt broker runs on the debian host.

Can this be configured differently? Is my setup faulty?

**Comment by gizmocuz** [comment]
Don't know, do you have a default MQTT installation ?

I just pushed some changes that will make sure each MQTT connection from Domoticz (main/mysensors/ttn) uses it's own ID

This has been added in beta 11527, which is currently building. (Could take up to 2 hours)

Could you test with this version ?

**Comment by kokangit** [comment]
Thanks for the quick response, really appreciated!
Yes, I don't have any fancy MQTT changes. Just vanilla install on my debian host and nothing special regarding Domoticz.
Sure, I'll build the beta myself and test.

**Comment by gizmocuz** [comment]
Just push a correction to my previous patch...
I indeed implemented the Client ID's last week... did not know it was so strict, but it makes sense ;)

**Comment by kokangit** [comment]
I built the latest in development now and it works fine! Thank you so much!

**Comment by rwaaren** [comment]
MQTT hardware gets disconnected every 30 seconds when connected from two or more domoticz instances to the same broker. On V4.11528

```
2019-11-24 16:35:41.299  Status: MQTT: Connecting to PI-5:1883
2019-11-24 16:35:41.501  Status: MQTT: re-connected to: PI-5:1883
2019-11-24 16:35:41.701  Status: MQTT: Subscribed
2019-11-24 16:36:08.646  Error: MQTT: disconnected, restarting (rc=7)
```

**Comment by gizmocuz** [comment]
@rwaaren , could you check the MQTT broker log why this happens ? Could it be because of the duplicate client ID as well ? I mean two instances will use the same name.
Maybe we should include a unique ID as well.
But I hope your log will tell us (like client with same ID connected.. or something)

**Comment by rwaaren** [comment]
In the broker log:
from 11/24/2019 @ 2:36pm (UTC) - 11/24/2019 @ 3:39pm (UTC)
141 times 
`Client Domoticz already connected, closing old connection. `

(With two domoticz instances MQTT connected to this broker)
After I stopped MQTT on my 2nd instance to test if the disconnecting would stop; and it did :-)

**Comment by gizmocuz** [comment]
@rwaaren , thanks that is what i expected... I have some ideas how to solve this... wont take to long

**Comment by gizmocuz** [comment]
@rwaaren , please try beta 11531

**Comment by rwaaren** [comment]
Working now. Thanks !

domoticz instances subscribe to broker with partially randomized strings 
Initial: 
system 1. Domoticz503eca85-1f1c-4303-9492-bd4fee46f7d9
system 2. Domoticz5d658bdd-a701-4812-bdcd-3a94879657ea

After domoticz restart on system 1 
Domoticzb9a46e62-5130-4592-bc20-70beb3e9df09 // new partial randomized ID

after disable/enable MQTT hardware, the  ID does not change

**Comment by darkManPi** [comment]
Hello 
The **problem still exist** for little different case.
In fact commit b89ba87 help for case with single MQTT connection per Domoticz instance having  few independent domoticz instances (unless no luck with random ;) ).

But when you will try to create more than one  "MySensors Gateway with MQTT interface" hardwares connecting to same MQTT server, the problem will come back.


**How to simulate problem:**
Create 2  "MySensors Gateway with MQTT interface" hardware connected to the same MQTT server. "Topic Prefix Mode" have not  influence 
Both hardware will keep on "fighting" for MQTT connection and MQTT server will be simply disconnecting one by one. 

```1576152152: Client Domoticz-MySensorsb9bc2348-483f-4e3a-9b0f-f80129080239 already connected, closing old connection.
1576152152: Client Domoticz-MySensorsb9bc2348-483f-4e3a-9b0f-f80129080239 disconnected.
1576152152: New client connected from 192.168.221.5 as Domoticz-MySensorsb9bc2348-483f-4e3a-9b0f-f80129080239 (c1, k40).
1576152178: New connection from ....
```


**Solution:**

Generate unique MQTT client ID for each single MQTT connection. At current moment client id will be global  for whole Domoticz instance as  introduced in commit b89ba87/c55e29c.
"szRandomUUID = GenerateUUID();"  could be set inside hardware/MySensorsMQTT.cpp. 
Same issue is exist for "hardware/TTNMQTT.cpp".

I have created separate issue #3793

Greetings

**Comment by Spyky** [comment]
Hello, since a few weeks i have the same issue  Error: MQTT: disconnected, restarting (rc=7)
There is a lot of reading above.. but is there a solution for this error
I update today to the latest version of domoticz and to buster in the hope it will solve something, but still get every 10 seconds this error.

Hope you can help.
