### ISSUE TITLE
OPENSSL error

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#3751]
I just updated to the latest beta version on my Debian 9 machine.  However now Domoticz fails to start with this error: "/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found"

However /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 and /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 both exist.  So I think it must be an error introduced in Domoticz somewhere.

**Comment by gizmocuz** [comment]
Same issue as https://github.com/domoticz/domoticz/issues/3737 where you are already posting.
Let's continue there

**Comment by Ittiz** [comment]
Sorry found that after creating this.

**Comment by gizmocuz** [comment]
No worries ;)
