### ISSUE TITLE
brightnessup /-down via API triggers switch "Off Action" in GUI and no change in brightness  of the light 

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#3753]
V4.11528 but probably also on earlier versions:

http://192.168.192.59:8084/json.htm?param=brightnessdown&type=command&idx=156
{
"status": "OK",
"title": "Set brightness down!"
}

No changes in brightness of the light and light is switched to off on switches tab

Same for 
http://192.168.192.59:8084/json.htm?param=brightnessup&type=command&idx=156

tested with Yeelight, Hue and virtual-devices  ; GUI behavior is same, real behavior also same where applicable.

**Comment by gizmocuz** [comment]
No idea what this for command is and it's probably for a special type of light... you can use the commands to set the 'level' to a specific value

**Comment by rwaaren** [comment]
Checked a bit more and brightnessup /-down commands are only implemented for Yeelight hardware connected lights. (but returns OK when called for any RGBWW light).
When calling this api for any RGBW(W) light the device state becomes empty.

**Comment by gizmocuz** [comment]
Yes because it is a unknown state
This API call should only be used for yeelight 
They're many others like disco mode
I don't consider this a issue...

**Comment by rwaaren** [comment]
OK. Reason why I bring this up is that after this call, the Yeelight is left in a condition where the state cannot be determined. So no way to programmatically determine if it is on or off or what the level is.
