### ISSUE TITLE
Any ideas how to save IP address through SendTempSensor? [BleBox example]

### ISSUE THREAD

**Issue by gadgetmobile** [domoticz/domoticz#3755]
Issue:

See this TODO here: https://github.com/domoticz/domoticz/blob/6ea6c9befd6de12188c6d220dc1453c5067b5e12/hardware/BleBox.cpp#L272

How this flows in practice:

1. Generally, BleBox integration stores the IP address in the DeviceID
2. `SendTempSensor()` has no way to pass an IP address (only node id at best)
3. Later, the temperature is decoded and the "DeviceID" is constructed here: https://github.com/domoticz/domoticz/blob/6ea6c9befd6de12188c6d220dc1453c5067b5e12/main/mainworker.cpp#L3407
4. Then, update value is called with this new id (e.g. "17") here: https://github.com/domoticz/domoticz/blob/6ea6c9befd6de12188c6d220dc1453c5067b5e12/main/mainworker.cpp#L3452
5. Now there's a DeviceStatus record with a DeviceID that doesn't have an IP encoded (like the original device which sent that temperature), so it appears as a "new device" in the node list.
6. And here (while loading records) the IP cannot be extracted from this new id: https://github.com/domoticz/domoticz/blob/6ea6c9befd6de12188c6d220dc1453c5067b5e12/hardware/BleBox.cpp#L1219

While such DeviceStatus records (without an IP in the DeviceID) can be detected and skipped, the issue is that those records are inserted in the first place (instead of the matching records being updated).

Are there any suggestions/practices to handle this?

**Comment by szczukot** [comment]
Hi
Yes - we need refactor this (my) code
I need use WOL table - not use ID device etc.

Fantom
ps. Where are you from?

**Comment by gadgetmobile** [comment]
Fixed/handled in: https://github.com/domoticz/domoticz/pull/3876

I considered the WOL table, but it isn't necessary, especially since IP should be tied to a unique hardware identifier. The new "architecture" of storing hardware/node info also make it unnecessary.

Also, since there's one IP = one hardware = one unique identifier, it doesn't make sense to add another database table in that relation. ("Address" field of hardware is 200 characters, so it's sufficient for IPv4 and MAC).
