### ISSUE TITLE
Conversion problem with wind speed and gust.

### ISSUE THREAD

**Issue by vampywiz17** [domoticz/domoticz#3760]
Hello there,

I use dummy weather station in domoticz (latest stable). I feed the device with Node-RED MQTT. 
My problem:

- get the data with weather station

- it is 2 km/h 

- i convert it in Node-RED to m/s (need this Domoticz)

- the value is : 0.5555555555555556 m/s

- now need to *10 (it say the Domoticz documentation)

- new value: 5.555555555555555

- convert it to string and send it to with svalue

- the Domoticz log say it successfully arrive, no rounding(i see it in "hardware menu"): 90;E;0;5.555555555555555;7.6;0

- Now, domoticz somehow convert it back to km/h and final i get **1.8 km/h** 

If i convert the last good value it manually: 5,555555555555555/ 0,27777777777778=19,99999999999984. Round it and i get "20" now move the decimal point and get "2.0" that the correct value, 

I think the problem somewhere in the final convert and rounding in Domoticz.

**Comment by vampywiz17** [comment]
I found the problem!

Domoticz basically only work with m/s. 

- first get the data: 5,555555555555555

- round it (or only cut the numbers after the point) and get 0,5 m/s. If i set to "show km/h value" simply convert the rounded/cutted m/s value (0.5/0,27777777777778) and get the wrong 1.8 km/h

So my idea is:

- if the user set "km/h" in settings, not use rounded/cutted value with converting, instead use the original svalue!

**Comment by gizmocuz** [comment]
You have to feed it as m/s, and in the Domoticz settings you can let it display as km/h

**Comment by vampywiz17** [comment]
@gizmocuz 

You misunderstand me. my problem is not that don't know how to swicth on the km/h display setting. My problem that the display setting is work wrong! It convert the rounded value (that display domoticz if i use the m/s setting) not the source that get the virtual sensor.

Please read it again my bug report. If the Domoticz use the km/h display setting with rounded value the source value 2 km/h will be 1.8 km/h!

Vizualize it:

source ----->conversion km/h to m/s------->value*10(and send to domoticz)----------->domoticz round it---->domo convert it to km/h

2 km/h ----> 0,5555555555555556 m/s ----> 5,555555555555556 m/s ----> 0.5 m/s -----------> 1.8 km/h

**Comment by gizmocuz** [comment]
If your 'source' is in km/h you need to convert it to m/s:

m/s = km/h divided by 3.6, that is 0.56 m/s ... extreme slow... send to domoticz as 5 (it's a integer value!)
Yes, converted back this is 0.5 * 3.6 = 1.8 km/h

I think we can live with the 0.2 km/h difference can we ?

**Comment by gizmocuz** [comment]
Do note that a lot of hardware is using integers in their datagram, TFA,Davis,WTGR800,Alecto...
