### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by akamming** [domoticz/domoticz#3761]
Running on rpi3b+ stretch latest beta. 

The current beta release has a memory leak. I did several tests and on my system, on which i concluded
- 4.11505 is ok
- 4.11506 leaks memory (making commit Jsoncpp deprecate fix (#3741) a possible candidate)
- current production version (on 29/11/2019)  leaks more memory (So my suspicion is there might be more than one memory leak..) 

The analysis can be found in [this forumthread](https://www.domoticz.com/forum/viewtopic.php?f=6&t=30305&p=229607#p229607) as well as more users with the same issue

i already looked  at the code changes at commit #3741 , but i don't see where it leaks, hopefully more experienced developers can have a look at it...

**Comment by akamming** [comment]
I'm not trying to report issues, but also try to fix them, so in the latest codebranch i reverted the commit #3741 and solved some merge issues, trying to prove this commit is really the issue. This morning i ran the test, and it looks like the memory leak is gone. With the memory leak, the memory usage immediately starts to rise. 

This effect is gone when this commit 3741 is no longer in the code, as you can see in the following graph : 
![result_versions2](https://user-images.githubusercontent.com/30364409/69899414-c53dae80-1365-11ea-99bd-cbee78a1acd5.png)
(4.11540 has the same code as 4.11539, just with commit 3741 reverted. The code can be found [here](https://github.com/akamming/domoticz/tree/revert3741) )

If someone tests this code also on windows (i cannot compile on windows), i could make a PR to fix the memory leak, but probably commit 3741 is in the code with a reason. So probably it's just a workaround till we fix the real problem. 

I already tried, but i cannot find the memory leak in the code of this commit (which probably says more about my coding skills than the complexity of the code ;-)). So I won't be able to fix the root cause.

@gizmocuz i just checked and found out you created all this code yourself. What is your advice here?

**Comment by rwaaren** [comment]
Also seem to be a relation with hardware. I disabled Hue on my test system with latest Beta and no memory leak occurred after this. Might well be that all hardware using the new JSON stuff suffer from this but I don't have all hardware on my test system.
Now started a test run on my production system with disabled Hue. 
V4.11539 

```
Native hardware:
Domoticz Internal
RFtrx433
Aeotec  Zwave stick
RFLink
P1
Youless
Hue
Harmony
PI1 Motherboard
Evohome
Xiaomi
Yeelight
MQTT
DarkSky
Virtual
Buienradar

Plugins:
Synology UPS
Homewizard
Sonos
PiMonitor
Synology
Z-Wave battery monitor

```



I Expect the memory leak curve to be less steep but not flat as I have also some other hardware active on this system using the new JSON stuff.
Will update this post with my results

201911301515 after disabling Hue: memory usage increased with the same speed

**Comment by akamming** [comment]
Makes sense. In commit 3741 a lot of hardware is changed to use the new json stuff. If you have a setup in which just one of these pieces of hardware makes the memory leak then this is A perfect setup for trying (and testing) to chance to code in a way it no longer leaks 

I don't use Hue. Mine is z-wave, p1 meter, motherboard monitor, buienradar native implementation, a bit of gpio and a dzvents script updating my solar power

**Comment by FireWizard52** [comment]
I installed the latest beta yesterday  at 13:23:07
Nov 29 13:23:07 RPi2 domoticz.sh[565]: 2019-11-29 13:23:07.353  Status: Domoticz V4.11539 (c)2012-2019 GizMoCuz
Nov 29 13:23:07 RPi2 domoticz.sh[565]: 2019-11-29 13:23:07.356  Status: Build Hash: 6c6c27a56, Date: 2019-11-29 09:53:24
From that time, memory usage doubled almost. It came from approx. 15-16% and is currently 29%
![Screenshot_memory 30112019](https://user-images.githubusercontent.com/46283323/69902382-42304e80-138d-11ea-9074-9dfad5220af2.png)

Following Native Hardware in use:

> 
Wake on Lan
Panasonic TV
Kodi
P1 smart meter
Equipment Alive (Ping)
RFXtrx433E
Motherboard sensors
DarkSky Weather
Buienradar
Enphase Envoy with LAN (HTTP) interface
MQTT
Domoticz - Remote Server
Virtual
Meteo Alarm EU RSS Reader

Plugins
UPS Monitor
OpenAQ
MQTT discovery
Buienradar.nl (Weather lookup)

**Comment by gizmocuz** [comment]
Going to check this next week
Could be related to some json functions
Should not be too hard to check

**Comment by akamming** [comment]
had a brainwave. I may have found the cause, I made this changeto json_helper.cpp which should force the CharReader is deleted from memory after it's used:

```
@@ -3,13 +3,23 @@

 bool ParseJSon(const std::string& inStr, Json::Value& json_output, std::string *errstr)
 {
+       bool result;
+       Json::CharReaderBuilder builder;
+       Json::CharReader *reader = builder.newCharReader();
+
        if (inStr.empty())
                return false;
+
+

-       return Json::CharReaderBuilder().newCharReader()->parse(
+       result = reader->parse(
                reinterpret_cast<const char*>(inStr.c_str()),
                reinterpret_cast<const char*>(inStr.c_str() + inStr.size()), &json_output,
                errstr);
+
+       delete reader;
+
+       return result;
 }

```
now testing. 1st 30 minutes are looking good. Keep you posted

**Comment by akamming** [comment]
Yep.. it's confirmed. After 90 mins memory usage is still at normal level. Created PR #3767 to fix...

**Comment by rwaaren** [comment]
Sounds good, I just started to test on my systems with this patch. Expect to see same result in a couple of hours.. 
Below my experiences in the last 24 hours ( offcourse without the patch )

![domoticz memory](https://user-images.githubusercontent.com/24454798/69907061-15e8f200-13ce-11ea-9305-9fdbcaab3370.png)

**Comment by rwaaren** [comment]
Huge improvement but too soon to conclude no other memory leaks ?

![domoticz memory](https://user-images.githubusercontent.com/24454798/69911995-bae1ea00-1423-11ea-9dc2-1efabd339bf3.png)

**Comment by akamming** [comment]
on my system i have another conclusion, Memory leak is really gone:

![effect fix](https://user-images.githubusercontent.com/30364409/69912775-2a5cd700-142e-11ea-8745-d105a6377313.png)

i look at the process usage, i see your graph is about total memory usage, so there  can be a lot of factors influence the total usage, what does the "process usage" graph look like? 

if that one doesn't grow, i think you have something else leaking memory on your system. If it does, then my 1st thought would be the 2nd leak is in the hardware you have and i don't ...

i am using the following hardware (+some dzvents script populating virtual sensors):
![hardware](https://user-images.githubusercontent.com/30364409/69912859-c63b1280-142f-11ea-8425-13595a7b0c0e.png)

So maybe zoom in on the hardware you have and i do not?

(BTW: I am now running a new test. I changed the code of the fix, so the code is more lookalike with other code within json_helper.cpp).

**Comment by rwaaren** [comment]
I would not spend more time on it now. It might well be that my memory usage trend line turns flat in a couple of hours...

The graph I showed in my previous post is only domoticz but measured from the OS level. Below you will see the process Usage ( internal ) which is almost the same.

![domoticz memory](https://user-images.githubusercontent.com/24454798/69913488-bb38b000-1438-11ea-810f-2ee561d87855.png)

Hardware definitions on this system
![domoticz hardware](https://user-images.githubusercontent.com/24454798/69913562-66496980-1439-11ea-9d8d-412955e18704.png)

**Comment by akamming** [comment]
Based on your history graph your the average memory usage was around 110-120mb before the memory leak. So if this is the only leak and the patch does it job, it should again stabilize around those numbers...

**Comment by rwaaren** [comment]
Not quite there yet..

![image](https://user-images.githubusercontent.com/24454798/69920603-3aa29f80-148a-11ea-9d4c-ba1c4ec57be7.png)

**Comment by rwaaren** [comment]
I amended the PR of @akamming a bit and tested with that change on my system. It looks like that solved also the remaining leak but would like to test another couple of hours before merging.

![image](https://user-images.githubusercontent.com/24454798/69938353-57b48e00-14dd-11ea-8788-cc2085270cbc.png)

**Comment by redswan01** [comment]
Maybe a different leak :(
Using PiMonitor 
![Memory use](https://user-images.githubusercontent.com/7438646/69946442-e8926600-14eb-11ea-99b3-6d032b70a7a0.PNG)
It looks to me here that the flat periods correspond to the time the pc which I use to check what's going on is asleep and the increase to when it's awake.
This is with 11539 on an rpi with Debian Jessie.
My system has an RFPlayer RFP1000 and a AEONlabs Zstick Gen5
Python plugins:
RFPlayer, Smart Virtual Thermostat, PiMonitor
Plus LUA and Python scripts and some home-built devices feeding virtual devices via JSON api.
I modified slightly the PiMonitor Domoticz memory function to count only the Domoticz process and not everything that includes the text "domoticz" which was also including memory use from some Python scripts. Changed "grep domoticz" to "grep $(pidof domoticz)".
The big drop, just after midnight o the 30-11, is due the a reboot by "monit" which timed out trying to access Domoticz.

**Comment by rwaaren** [comment]
> Maybe a different leak :(

Is this already with the patch from @akamming ? (It is not merged yet into Beta) 
If so please add my commit to it and test again. 
If not then your memory leak might well be same as what we see.

**Comment by redswan01** [comment]
No this is without that patch, I'm running the current Beta 11539. I'll wait for it to be merged as I'm not able at the moment to compile my own.
What puzzled me was that in my case the leak appears to be linked to the updating of the web gui, I would have expected the leak you see to be continuous irrespective of the web gui access as the devices/scripts calling the json api are always running.

**Comment by gizmocuz** [comment]
@akamming 
Reverting a complete library upgrade and a lot of functions and patches I don't call 'the fix'
That is why I said I would look into this ASAP
It would be nice to know where the probleem lies

**Comment by akamming** [comment]
@gizmocuz pls check the PR. Reverting the library was only a test to find out if that PR caused the memory leak. We already found the root cause. PR #3767 fixes this rootcause. @rwaaren is doing the latest tests...

**Comment by rwaaren** [comment]
Seems OK now in terms of memory leakage.  Strange thing is that in my tests I included a log message
	
```
if (inStr.empty())
	{
		_log.Log(LOG_ERROR, "InStr seems to be empty!");
		return false;
	}

```
But have not seen a single Error

**Comment by gizmocuz** [comment]
@akamming , sorry about that, was browsing my mobile.. going to have a look at this tomorrow.
(Was away for the weekend)

**Comment by akamming** [comment]
@gizmocuz no worries. Keep up the good work!

@rwaaren on my system all is also still ok (no memory leak, no crashes) with the fix. I also created an additional logline on empty strings and got no hits. (Which i expected,  cause on my system the leak was already gone with the 1st patch)

**Comment by gizmocuz** [comment]
Thanks for the PR. I have corrected the code and made it consistent with the ParseJSonStrict helper function.
Thank you for spotting this!
