### ISSUE TITLE
Arilux AL-LC0x timers

### ISSUE THREAD

**Issue by mojso** [domoticz/domoticz#3763]
Arilux AL-LC0x subtype RGBWZ  timers does not send command ON, only brightness level.
also on the slider works off but not on
command
manual switching on, it works
Off command work ok 
i use Magic Home wifi controller

please, can you make hardware plugin for magic home the same as arilux just modified command for ON via the slider - send first command ON then brightnes from 1 to 100. and for timers first ON command

**Comment by waltervl** [comment]
Still an issue?

**Comment by mojso** [comment]
> Still an issue?

I think it has been fixed.  the timer works.  the slider also works

**Comment by mojso** [comment]
![20220213_142823](https://user-images.githubusercontent.com/8018149/153755687-9b4643b0-c531-4ca8-9f05-1ec97d2ffc4a.jpg)

except this slider in Desktop Web .
Mobile Web is ok

**Comment by waltervl** [comment]
I do not see this slider placement issue on desktop in stable 2022.1 and latest beta. Can you clear your browser cache (or use browser in Private mode) and try again?

**Comment by mojso** [comment]
> I do not see this slider placement issue on desktop in stable 2022.1 and latest beta. Can you clear your browser cache (or use browser in Private mode) and try again?

![20220213_145804](https://user-images.githubusercontent.com/8018149/153756696-1af1cb2b-7b85-4226-a445-217a597d2a71.jpg)
same  in incognito 
And 
cleared   browser cache


it may only be on smaller screens. In the browser on my TV is ok

**Comment by mojso** [comment]
this is an error in the web site there is no space in the table not in the plugin itself.  
Arilux AL-LC0x  is ok  
- fixed (command for ON via the slider and timer on)

**Comment by waltervl** [comment]
I checked in chrome and firefox and no issues nor errors in console (F12).
So please clear your browser cache.
![Screenshot from 2022-02-13 15-47-14](https://user-images.githubusercontent.com/16327072/153758637-42a8361e-5739-4c99-801c-7ce7afa98dec.png)

**Comment by mojso** [comment]
I found where my mistake was
this appears if the Website is zoomed out.  
 (ctrl +/-)
from 90% down appears like this

**Comment by waltervl** [comment]
Thanks, I will close the issue.
