### ISSUE TITLE
Aeotec ZW175 Smart Switch 7+ relay not switching

### ISSUE THREAD

**Issue by HB787** [domoticz/domoticz#3765]
The Aeotec Smartswitch 7 does not switch the relay, only the led when clicking the device button.
However the device's relay is switching in the Open Z-Wave Control panel.

Found this in the logs at startup:
2019-11-23 12:56:16.147 Status: SendSwitchIfNotExists: Device '79.instance.1.index.0.commandClasses.38' (Level) with DeviceID '00004F01' matches '79.instance.1.index.0.commandClasses.37' (Switch). Domoticz will use the Dimmer (and hide the Switch).

It looks like the switch device is defined as a dimmer it explains why it is not switching at all.
Hope this can be an easy fix, for all Aeotec Smartswitch 7 users

Domoticz Version 4.11539 Beta

**Comment by gizmocuz** [comment]
@HB787 , could you post a screenshot of the Node table from Domoticz ? I am interested in the ID and Type value

**Comment by gizmocuz** [comment]
@HB787 , could you also check in the devices table if you get other switches as well ? And try to toggle the on/off status of those switches ?
It seems odd to receive a 'dimmer' for the smart switch, or could it dimm as well ?

**Comment by HB787** [comment]
> 
> 
> @HB787 , could you post a screenshot of the Node table from Domoticz ? I am interested in the ID and Type value

![SS7_Type](https://user-images.githubusercontent.com/58355498/70031213-0c68b100-15ab-11ea-95fa-c38f94315c57.jpg)

**Comment by HB787** [comment]
> 
> 
> @HB787 , could you also check in the devices table if you get other switches as well ? And try to toggle the on/off status of those switches ?
> It seems odd to receive a 'dimmer' for the smart switch, or could it dimm as well ?

I did tried to click on the other devices, after install the switch that toggles the Led actually had a dim value under data which is weird. So I tried to configure it as dimmer but that does not work either. In the OZW control panel it does switch the relay. Wil make a screenshot of the devices also here.
![SS7_Devices](https://user-images.githubusercontent.com/58355498/70032255-5c487780-15ad-11ea-83ec-cd31d6dcd7d5.jpg)

**Comment by HB787** [comment]
After clicking the first time the device 3413, the data row tekst "level = 50" disappears.

**Comment by HB787** [comment]
Thanks rwaaren for reopening, clicked incidentally on Close

**Comment by gizmocuz** [comment]
Thank you for the screenshot/ID's.
Could you try beta 11545 to see if this solves the issue ?

**Comment by HB787** [comment]
Yes relay now switching thank you very much!!

**Comment by gizmocuz** [comment]
Great, thanks for the feedback!, Hope your other issue with the 'Frequency' is also solved. Closing this one

**Comment by gertvdijk** [comment]
@gizmocuz Hi! I was wondering if you have any reference to a commit/change about the fix. I'm facing a similar issue with the same device in another project (https://github.com/OpenZWave/Zwave2Mqtt/issues/185) and I was wondering what was the solution in Domoticz to handle the ZW175.
