### ISSUE TITLE
Support of AQARA XIAOMI 2 relays

### ISSUE THREAD

**Issue by kitsen13** [domoticz/domoticz#3769]
As refered on forum here :

https://www.domoticz.com/forum/viewtopic.php?t=28973

XIAOMI 2 relays is seen like  2 temp devices, not switch device...

LLKZMK11LM device is not coded here :

https://github.com/domoticz/domoticz/blob/development/hardware/XiaomiGateway.cpp

Please add support for this module. (LLKZMK11LM)

**Comment by kovainfo** [comment]
wait for the gateway firmware update. at the moment, the gateway does not report information about this relay in developer mode.

**Comment by kitsen13** [comment]
@kovainfo ok thanks, is Xiaomi is about to close its gateway?

**Comment by Huupke** [comment]
Solved by #4839, propose to close
