### ISSUE TITLE
dzVents 2.4.19 matchesRule triggers on multiple dates

### ISSUE THREAD

**Issue by phpcoder** [domoticz/domoticz#3771]
Today on 3/12 I found that my dzVents script says it is Christmas...
After testing it was found that the method today.matchesRule(rule)) returns true for the rules like:
'on 03/12',
'on 13/12',
'on 23/12'
Perhaps this rule type is seldom used, so it was not noticed before.
Merry Christmas!

**Comment by rwaaren** [comment]
Thanks for reporting. Fixed in Domoticz V4.11547 (dzVents 2.5.2)
