### ISSUE TITLE
Popp 700397 wallplug switch outdoor is throwing errors

### ISSUE THREAD

**Issue by HB787** [domoticz/domoticz#3772]
The Popp 700397 outdoor wall-plug is generating these errors:

In the normal log:
OpenZWave: Value_Added: Unhandled Label: Frequency, Unit: Hz, Node: 73 (0x49), CommandClass: SENSOR MULTILEVEL, Label: Frequency, Instance: 1, Index: 32

In the error log:
Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 73 (0x49), CommandClass: SENSOR MULTILEVEL, Label: Frequency, Instance: 1, Index: 32

The device is working, relay and also energy consumption are working.
There is something wrong with the Frequency field or label in the XML.

Tried several times to erase and include again but the error stays the same.

Platform:  
Raspberry PI 4
Domoticz Beta 4.11544
USB Stick Aeotec ZW090 Gen5

**Comment by gizmocuz** [comment]
@HB787 , the 'Frequency' sensor was not yet implemented. Could you test with beta 11546 ?

**Comment by HB787** [comment]
Yes this now solved, there is no error anymore

**Comment by HB787** [comment]
Thank you again!

**Comment by gizmocuz** [comment]
Great, and you should get a new sensor in the devices tab (if accept new hardware/devices is enabled in the settings)

**Comment by HB787** [comment]
Yes there is a Frequency device now. 
I am happy with it Sir!

**Comment by gizmocuz** [comment]
Great! Thanks for the feedback!
