### ISSUE TITLE
Devices page "loading" forever

### ISSUE THREAD

**Issue by toffe** [domoticz/domoticz#3773]
Fresh install on Raspbian buster. I added my HW (RFXTRX433XL) and then go to Devices page. It only says "Loading..."

Chrome dev console says:
angular.min.js:124 TypeError: Cannot read property 'map' of undefined
    at Devices.js:541
    at angular.min.js:137
    at m.$digest (angular.min.js:148)
    at m.$apply (angular.min.js:151)
    at l (angular.min.js:103)
    at t (angular.min.js:108)
    at XMLHttpRequest.A.onload (angular.min.js:109) "Possibly unhandled rejection: {}"

It seems $ctrl.devices = response.result is undefined.

The result of:
http://192.168.1.20:8080/json.htm?displayhidden=1&filter=all&type=devices&used=all

is 
{
	"ActTime" : 1575407541,
	"AstrTwilightEnd" : "17:04",
	"AstrTwilightStart" : "05:21",
	"CivTwilightEnd" : "15:18",
	"CivTwilightStart" : "07:07",
	"DayLength" : "06:21",
	"NautTwilightEnd" : "16:13",
	"NautTwilightStart" : "06:12",
	"ServerTime" : "2019-12-03 22:12:21",
	"SunAtSouth" : "11:13",
	"Sunrise" : "08:02",
	"Sunset" : "14:23",
	"app_version" : "4.11547",
	"status" : "OK",
	"title" : "Devices"
}

**Comment by rwaaren** [comment]
same as #3391 
workaround: Create ( dummy ) hardware and at least 1 ( virtual ) device
Solved in later Beta's
