### ISSUE TITLE
Nest login (non-Oauth device type) fails after a change happened at Google's end

### ISSUE THREAD

**Issue by GaetanCambier** [domoticz/domoticz#3777]
sice this morning, domoticz deny to login. ( same as #3729 )

https://www.domoticz.com/forum/viewtopic.php?f=6&t=30139&sid=69a62f838acfa3daa053b1a93d1e63bd&start=20#p230113

it seem that the user agent is the cause of the problem

"User-Agent: Nest/3.0.1.15"
...fixes the issue.

**Comment by gizmocuz** [comment]
@GaetanCambier , when you report an issue here, please state the version you are using...!

**Comment by gizmocuz** [comment]
Should now be working (again) in beta 11551

**Comment by heggink** [comment]
Issue seems back :-( after I upgraded from 11556 to the beta of today.

**Comment by GaetanCambier** [comment]
I confirm the problem in version Domoticz V4.11595 since i have update my docker (4/1/2020 at 02h00 CET)
