### ISSUE TITLE
Recent crashes caused by different compile environments ?

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#3779]
Recently there are quite a number of reports on the forum about domoticz Beta's crashing on RPI's
For one of the forum member I compiled a Beta on my last debian stretch system and that version turned out to be stable. I now compiled two versions for this forum member. One version on stretch and the other one on buster. I am waiting on the results of those versions.

For my own systems I compile on RPI3 stretch for my RPI 3 system on buster and on RPI4 buster for my buster RPI4 system.

What else can I do to identify root cause of these crashes ?

**Comment by gizmocuz** [comment]
Do you have some forum links ?
In the mean time I updated all build systems (apt-update) and the current beta's are from the update system.
Maybe that helps, but it's the first time I hear about it.
Could also be related to the recent websocket change

**Comment by Tobydeteckel** [comment]
https://github.com/domoticz/domoticz/issues/3762

**Comment by Tobydeteckel** [comment]
https://www.domoticz.com/forum/viewtopic.php?t=30366

**Comment by Tobydeteckel** [comment]
https://www.domoticz.com/forum/viewtopic.php?f=47&t=30424

**Comment by Tobydeteckel** [comment]
https://www.domoticz.com/forum/viewtopic.php?f=47&t=30396

**Comment by gizmocuz** [comment]
@Tobydeteckel , it's not really helpful to dump some forum links here.
Also the later one (thread 30396) is solved by upgrading to the latest beta
The other one seems not related
The other one seems related to MQTT while the other could be related to the OS as well.

**Comment by pipiche38** [comment]
Dont' get me wrong, I'm not pointing anything, but I remember that a PR has been done recently to enable linking with python8. So don't what is going to happen if binaries are produced on a system with python8 and then  binary is executed on a platform without python8 !

**Comment by gizmocuz** [comment]
I think this can be closed ?

**Comment by rwaaren** [comment]
No new reports about this
