### ISSUE TITLE
Aeotec ZWA008 Door Window Sensor 7 Error

### ISSUE THREAD

**Issue by AlexF12004Roma** [domoticz/domoticz#3784]
Domoticz Latest Beta 4.1551

Aeotec ZWA008 added

I get 3 devices added:
-Sensor Light/Switch
-Alarm Type Light/Switch
-Alarm Level Light/Switch

On contact change only notification from 
2019-12-08 11:48:43.933 (Zwave) Light/Switch (Alarm Type)
2019-12-08 11:48:43.970 (Zwave) Light/Switch (Alarm Level) 
BUT always OFF
Sensor Light/Switch never notified

**Comment by gizmocuz** [comment]
Could you check it's settings if you could send it as a normal switch ?

**Comment by AlexF12004Roma** [comment]
There is nothing is Zwave device settings that seems useful to change behaviour

**Comment by gizmocuz** [comment]
Is the controller (node 1) in the lifeline of the node ? Usually group 1 ?
There is nothing in the settings that can specify what notification should be send when operating the node ?

**Comment by AlexF12004Roma** [comment]
![ZWA008](https://user-images.githubusercontent.com/6578842/70390015-3402b380-19c7-11ea-9e1a-dec1c51137f9.PNG)


The controller is in lifeline.
In settings nothing that let you specify what notifications should be sent.

From Manual:
Supported Command Classes
Sensor Binary (unsec+s2 Unauth)
Association Grp Info (unsec+s2 Unauth)
Device Reset Locally (unsec+s2 Unauth)
Central Scene (s2 Unauth)
Zwaveplus Info (unsec)
Supervision (unsec)
Configuration (unsec+s2 Unauth)
Alarm (unsec+s2 Unauth)
Manufacturer Specific (unsec+s2 Unauth)
Powerlevel (unsec+s2 Unauth)
Firmware Update Md (unsec+s2 Unauth)
Battery (unsec+s2 Unauth)
Wake Up (s2 Unauth)
Association (unsec+s2 Unauth)
Version (unsec+s2 Unauth)
Multi Channel Association (unsec+s2 Unauth)
Security 2
Transport Service (unsec)





Settings:


Parameter 1: Operation Mode.

This parameter allows switching between internal sensor and external sensor.

Size: 1 Byte, Default Value: 0

Setting	Description
0	the internal hall sensor is enabled (external input disabled)
1	the external input is enabled (internal hall sensor disabled)


Parameter 2: Door/Window State.

This parameter allows setting Door / Window Sensor 7 state when the magnet is close to the sensor.

Size: 1 Byte, Default Value: 0

Setting	Description
0	closed when the magnet is near
1	opened when the magnet is near


Parameter 3: Visual LED Indications.

This parameter defines events indicated by the visual LED indicator. Disabling events might extend battery life.

Size: 1 Byte, Default Value: 7, Range: 0 - 7

Setting	Description
0	no indications
1	indication of opening/closing status change
2	indication of wake up (1 x click or periodical)
4	indication of device tampering


Parameter 4: Range test after double click.

Allows enabling the activation of Z-Wave range test with double click of a Tamper Switch 2.

Size: 1 Byte, Default Value: 0

Setting	Description
0	Disable
1	Enable


Parameter 5: Group 2 Association Triggers.

This parameter defines events that result in sending On/Off commands to devices added to the 2nd Association Group. These commands are sent alternately to switch the devices On and Off. Commands represent the values of BASIC SET command frames. This parameter is inactive in external dry-contact mode (parameter “Operation Mode” set to 1).

Size: 1 Byte, Default Value: 0

Setting	Description
0	switch after opening and closing
1	switch after opening
2	switch after closing


Parameter 6: Commands sent to associated devices on Group 2.

Command frames sent to devices added to the 2nd association group.

Size: 1 Byte, Default Value: 2

Setting	Description
0	On
1	Off
2	On and Off


Parameter 7: Values of ON command frame sent to Group 2 Association.

The value of 0 turns OFF the device, 255 turns it On. In the case of associating the Dimmer or Roller Shutter module, values

Size: 1 Byte, Default Value: 255

Setting	Description
0 - 99	allow setting an Associated device to a specified level (0 is OFF)
255	ON


Parameter 8: Value of OFF command frame sent to Group 2 Association.

The value of 0 turns OFF the device, 255 turns it On. In the case of associating the Dimmer or Roller Shutter module, values.

Size: 1 Byte, Default Value: 0

Setting	Description
0 - 99	allow setting an associated device to a specified level. (0 is OFF)
255	ON


Parameter 9: Time Delay of ON command from Group #2.

The time period after which On command frame will be sent.

Size: 2 Byte, Default Value: 0

Setting	Description
0 - 32400	Time set in seconds


Parameter 10: Time Delay of OFF command from Group #2.

The time period after which the OFF command frame will be sent.

Size: 2 Byte, Default Value: 0

Setting	Description
0 - 32400	Time in seconds


Parameter 11: Delay of tamper alarm cancellation.

The time period after which a tamper alarm will be canceled.

Size: 2 Byte, Default Value: 0

Setting	Description
0 - 32400	Time in seconds


Parameter 12: Reporting tamper alarm cancellation.

Reporting cancellation of tamper alarm to the controller and 3rd Association Group.

Size: 1 Byte, Default Value: 1

Setting	Description
0	do not send tamper cancellation report
1	send tamper cancellation report


Parameter 13: Central Scene Event functionality.

Enable/Disable Central Scene Events.

Size: 1 Byte, Default Value: 0

Setting	Description
0	Contact Scene Events disabled
1	Contact Scene Events enabled


Parameter 14: Tilt Sensor Functionality enable/disable.

Tilt Sensor functionality enable/disable.

Size: 1 Byte, Default Value: 1

Setting	Description
0	Tilt Sensor disabled
1	Tilt Sensor Enabled


Parameter 15: Tilt sensitivity
You can use this parameter to adjust the tilt sensitivity if the tilt is too low or too high.
Size: 1 Byte, Default Value: 50



Setting	Description
1 - 100	Tilt sensitivity

**Comment by gizmocuz** [comment]
@AlexF12004Roma , seems your correct. Sometimes there is an option to change  BASIC SET to Binary

I assume the Domoticz version '1551' you mention is incorrect and you are running a recent beta version

When you go to the hardware setup of openzwave, and open the control panel from the dropdown, do you see sensors there that change when you open/close the sensor ?

**Comment by AlexF12004Roma** [comment]
Yes timestamp change,
i  see also logs change
2019-12-08 11:48:43.933 (Zwave) Light/Switch (Alarm Type)
2019-12-08 11:48:43.970 (Zwave) Light/Switch (Alarm Level)

but swtich remain always OFF

**Comment by gizmocuz** [comment]
But this seems to be from the domoticz log, not from the control panel
Could you post a screenshot of the control panel's sensors ?
Noting changes there, only the timestamp ?
In Domoticz, when you go to Setup->More Options->Events, you could try to create a blockly that will trigger a log mesage when the 'ZWave Alarm' value changes

**Comment by gizmocuz** [comment]
Maybe you need to disable parameter 14 ?
You can also try to enable reporting the On/Off in the 2nd association group and also add node 1 in this group

**Comment by gizmocuz** [comment]
Also make sure 'accept new devices' is enabled in the Domoticz settings

**Comment by AlexF12004Roma** [comment]
I tried everything, nothing change.
Added also lifeline on group 2.

Values of 'ZWave Alarm' al always OFF
![AlarmLOG](https://user-images.githubusercontent.com/6578842/70395613-9b892500-1a00-11ea-8d64-f7d9391bba25.PNG)

The control panel

![ControlPanel](https://user-images.githubusercontent.com/6578842/70395516-d048ac80-19ff-11ea-8537-101f34f15404.PNG)

**Comment by Olifant1990** [comment]
Maybe related, but I noticed this weekend a simular problem. I have a Hank watersensor, which should report ON when water is detected. But... I test this device sometimes and now, whatever I do, I only see OFF in Domoticz. ZWave control panel says OFF too. But I see some messages being received in controll panel, but not processed or something.Op 8 dec. 2019 21:21 schreef AlexF12004 <notifications@github.com>:I tried everything, nothing change.
Added also lifeline on group 2.
Values of 'ZWave Alarm' al always OFF

The control panel

**Comment by AlexF12004Roma** [comment]
I Enabled OZW DEBUG, this is the log: seems values changes in bytes are correct:

2019-12-08 21:50:25.200 Info, Node030, MultiChannelEncap with endpoint set to 0 - Send to Root Device
2019-12-08 21:50:25.200 Info, Node030, Received Basic set from node 30: level=0. Treating it as a Basic report.
2019-12-08 21:50:25.200 **Detail, Node030, Refreshed Value: old value=255, new value=0, type=byte**
2019-12-08 21:50:25.200 Detail, Node030, Changes to this value are not verified
2019-12-08 21:50:25.201 Detail, Node030, Notification: ValueChanged
2019-12-08 21:50:34.105 Detail,
2019-12-08 21:50:34.105 Info, Node030, MultiChannelEncap with endpoint set to 0 - Send to Root Device
2019-12-08 21:50:34.105 Info, Node030, Received Alarm report: type=0, level=0
2019-12-08 21:50:34.106 Detail, Node030, Refreshed Value: old value=0, new value=0, type=byte
2019-12-08 21:50:34.106 Detail, Node030, Changes to this value are not verified
2019-12-08 21:50:34.106 Detail, Node030, Refreshed Value: old value=0, new value=0, type=byte
2019-12-08 21:50:34.106 Detail, Node030, Changes to this value are not verified
2019-12-08 21:50:34.107 Detail, Node030, Notification: ValueChanged
2019-12-08 21:50:34.117 Detail, Node030, Notification: ValueChanged
2019-12-08 21:50:35.143 Detail, Node030, Received: 0x01, 0x0d, 0x00, 0x04, 0x00, 0x1e, 0x07, 0x60, 0x0d, 0x00, 0x01, 0x20, 0x01, 0xff, 0x5d
2019-12-08 21:50:35.144 Detail,
2019-12-08 21:50:35.144 Info, Node030, MultiChannelEncap with endpoint set to 0 - Send to Root Device
2019-12-08 21:50:35.145 Info, Node030, Received Basic set from node 30: level=255. Treating it as a Basic report.
2019-12-08 21:50:35.145 **Detail, Node030, Refreshed Value: old value=0, new value=255, type=byte**
2019-12-08 21:50:35.145 Detail, Node030, Changes to this value are not verified
2019-12-08 21:50:35.146 Detail, Node030, Notification: ValueChanged

**Comment by gizmocuz** [comment]
@AlexF12004Roma , thank you for the logs. I ordered a node from the donation money and hope to receive this tomorrow.
Did you wait 10 seconds, or was it automatically set to 255 at 2019-12-08 21:50:35.145?
Is there also any log about a change in the alarm report ?

**Comment by AlexF12004Roma** [comment]
I waited 10 seconds, manually activated the sensor.

I did not notice any log about alarm record, i should retry.

**Comment by gizmocuz** [comment]
@AlexF12004Roma , Ok i received the sensor.
It is working correctly, you should have a switch 'Access Control' that turns on/off when the Door/Window sensors changes from Open/Closed
Maybe reset the node ?

**Comment by AlexF12004Roma** [comment]
When added the device i have only 
-Sensor
-Alarm Type
-Alarm Level 

No AccessControl. 
I already excluded and include node, but no access control for node.

Should i have to update beta?

**Comment by AlexF12004Roma** [comment]
Updated to the lastest beta release.
Removed the node.
Resetted the node.
Addedd the node.

Now i have 4 elements, including Access Control:
![image](https://user-images.githubusercontent.com/6578842/70806932-ae16ac00-1dbc-11ea-8509-7c631af1bb30.png)

Now seems to work!

Thank you.

**Comment by AlexF12004Roma** [comment]
Tested also with external connections, works perfectly
another item added

![image](https://user-images.githubusercontent.com/6578842/70807539-08643c80-1dbe-11ea-8798-9d003aab4570.png)

**Comment by gizmocuz** [comment]
@AlexF12004Roma , that is why I asked 5 days before

"I assume the Domoticz version '1551' you mention is incorrect and you are running a recent beta version"

Great you got it working!

**Comment by AlexF12004Roma** [comment]
4 days ago i had 4.11551
Now updated to 4.11563

**Comment by gizmocuz** [comment]
@AlexF12004Roma , thanks ;) yes there was a OpenZWave code patch merged
