### ISSUE TITLE
Better Dummy Dimmer

### ISSUE THREAD

**Issue by nayrnet** [domoticz/domoticz#379]
Proposal: new subtype for pTypeLimitlessLights, called sTypeLimitless with no color attributes.
Then change the Dummy Switch from **pTypeLighting2, sTypeAC** to **pTypeLimitlessLights,sTypeLimitless**

This would only effect new dummy switches created after the change, and provide the new dummy switches with the ability to dim with 100 steps instead of 15.

Ive already tested by changing to sTypeLimitlessWhite and it worked wonderfully, however there are UI options for the color that do not need to be displayed, thus the proposal for the new type.

![screen shot 2016-01-24 at 3 40 15 am](https://cloud.githubusercontent.com/assets/3732081/12535796/3dc3750c-c24c-11e5-99c6-cd6c05ae97c1.png)

See: https://github.com/domoticz/domoticz/commit/bf6e3467de4b719559a8e288454aeb3496818d73

I am not quite sure how to enact these changes but I am willing to try if this proposal is accepted.

**Comment by nayrnet** [comment]
spoke too soon about it working wonderfully, it does not.. the Set Level switchcmd does not seem to work for the device.. crap.

Still, there is absolutely no reason why a dummy dimmer should not be 100 steps by default, other hardware dimmers are capable of this, its extremely restrictive to have the virtual switch be less capable than real switches.

This has bit me in the rear multiple times now and its long since time its been addressed.

examples: volume control needs more steps, dimming LED's needs more steps, etc.

now that we have selector switches, anyone who only has a few steps (motors/alarm levels) can simply use them or just round to the nearest logical setting and update the value.

If a new switch type is created anyone with the existing ones will retain functionality, maintaining backwards compatibility with scripts.

**Comment by Rimco** [comment]
Adding a sensor using the switches tab (manually) and using X10 seems to provide more steps. I'm suffering from the same problem if I add one from the hardware tab.

**Comment by gizmocuz** [comment]
Add a switch from the hardware tab (dummy hardware), export your database
open the database, go to the DeviceStatus table, go to your new switch
Set the subtype to 161

**Comment by nayrnet** [comment]
I set it to subtype 161 and it says unknown off latest git, still has 15 steps.. 
![screen shot 2016-02-02 at 2 17 43 am](https://cloud.githubusercontent.com/assets/3732081/12744758/345ba54e-c953-11e5-813a-e08b1004b2f7.png)

![screen shot 2016-02-02 at 2 17 23 am](https://cloud.githubusercontent.com/assets/3732081/12744760/38d6beb0-c953-11e5-9a09-8de2011a7ba5.png)

**Comment by gizmocuz** [comment]
that should work, latest Domoticz ? (version 4xxx)

**Comment by nayrnet** [comment]
Version: 2.4384
Build Hash: c41e8b4
Compile Date: 2016-02-02 01:04:44

**Comment by gizmocuz** [comment]
Just exported a copy of my database, here it works

![image](https://cloud.githubusercontent.com/assets/2265299/12751356/06de9d28-c9bd-11e5-862a-4d8238c1b8eb.png)

there could be one other dependency (i hope not) that the hardware device is openzwave ?

**Comment by nayrnet** [comment]
got it with the latest (2.4384), thank you for this.. this is important for several of my projects.

https://github.com/domoticz/domoticz/issues/419#issuecomment-180472788
