### ISSUE TITLE
Issue with RFXCOM - RFXtrx433 USB 433.92MHz Transceiver

### ISSUE THREAD

**Issue by Kratax** [domoticz/domoticz#3791]
Hi,

In the recent beta version, data from RFXCOM received through Imagintronix stopped working. At the same time, TFA protocol also started to be unstable. Was there any change implemented recently (circa 1 month) that could affect this? Currently the device working before (functional) even cannot be added. Otherwise, RFXCOM device is working well....

Thanks.

Kratax

**Comment by gizmocuz** [comment]
@Kratax , please use our forum.
Also when you report here a code issue, you have to obey the rules, there was a issue template with questions you need to fill.
I will assume your usb port has changes. Anyway, post this on the forum, thank you!
