### ISSUE TITLE
Deleting a scene from the devices tab does not delete a scene but try delete a device

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#3794]
When deleting a scene from the devices tab the command send is 
`http://<domoticz ip:domoticz port>/json.htm?idx=<id>&type=deletedevice`
It should send
`http://<domoticz ip:domoticz port>/json.htm?idx=<id>&type=deletescene`

[See forum post]( https://www.domoticz.com/forum/viewtopic.php?f=6&t=30509)

Issue is found in V4.10717 and reproducable in V4.11563

**Comment by GravityRZ** [comment]
i think i experienced this a while back(suddenly lost a hue light)
 and also an hour ago(coincidence)

it seems that lights and scene/group can get the same idx and indeed when you delete the group from the devices list you loose the light with the same idx

lucky i found out real fast and did a restore of the database.
deleting groups/scenes from the scenes tab does work

![image](https://user-images.githubusercontent.com/16853535/70749793-5715c600-1d2d-11ea-9651-6b4341fdc670.png)

**Comment by gizmocuz** [comment]
Yep, this was introduced when the devices tab was rebuild in AngularJS style.
Should be solved in 11564
