### ISSUE TITLE
Wrong icon description on floorplan for dimmer

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#3797]
the latest beta (4.11564)
On floorplan, device type Dimmer (icon default) showing percentage like "7987349%"

**Comment by gizmocuz** [comment]
Is this reproducible with a dummy ?

**Comment by szczukot** [comment]
Hmm. I try with dummy - and not.
Only on real device problem exists.

**Comment by szczukot** [comment]
![image](https://user-images.githubusercontent.com/10205661/70862087-d840a900-1f37-11ea-97bc-49c03d3d8806.png)

**Comment by gizmocuz** [comment]
Maybe it is a real device problem ? what type of switch/hardware is this ? (AC/ARC/?)

**Comment by szczukot** [comment]
When edit device I see: switch type "dimmer"
On device list: type "color switch" subtype "RGBW"

**Comment by waltervl** [comment]
This issue can be closed?

**Comment by waltervl** [comment]
Tested and RGBW devices shows valid percentage in Floorplan

**Comment by szczukot** [comment]
The latest domoticz
Dimmer
![image](https://user-images.githubusercontent.com/10205661/156147002-066d55c1-7273-4e58-998d-02d07f83d938.png)

![image](https://user-images.githubusercontent.com/10205661/156147377-c7bbfeed-9511-422f-a666-f6a756cd0cd5.png)

**Comment by gizmocuz** [comment]
@szczukot , could you have a look in the database (devicestatus table) at the device it's LastLevel value ? Is this a very high number?
Could you also post a screenshot of the device from the device overview, so we can see the hardware/type/subtype/unit?
