### ISSUE TITLE
enhancement in blocky/events support : time and math

### ISSUE THREAD

**Issue by GrmpCerber** [domoticz/domoticz#380]
Hi,

I need a few additions to blocky/events :
- getter for : 
  - week number
  - month
  - year

and, in addition, some math function :
- at least "modulo"
- even / odd would be nice
- "+", "-", "*", "/" would be high luxury

**Comment by GrmpCerber** [comment]
I would be happy to help with this, but I need some inputs on where and how to do it regarding : 
- UI
- Save/restore
- eval

**Comment by gizmocuz** [comment]
Please have a look at the code, it is all there, it is part javascript and c++
