### ISSUE TITLE
AppVeyor build failed but The Travis CI build passed for new PRs

### ISSUE THREAD

**Issue by brucemiranda** [domoticz/domoticz#3804]
Why is the The Travis CI build compile working but the AppVeyor build failing for new PRs?

**Comment by gizmocuz** [comment]
If you click on the details button you can see the issue

**Comment by gizmocuz** [comment]
I recompiled the library with the issue and it's solved now till there is a new version of visual studio

**Comment by brucemiranda** [comment]
Seems like you need to do the same again. My latest PR is not compiling.
