### ISSUE TITLE
Cannot reach domoticz.com. Cloudflare error 520?

### ISSUE THREAD

**Issue by Wamor** [domoticz/domoticz#3806]
Hello,

Sorry for posting here but for a few days I cannot reach www.domoticz.com anymore.
I've got an error 520 from Cloudflare. My RaspberryPi with domoticz on it was used in a DDOS-attack and I needed to do a complete re-install. I try to do a fresh domoticz install but cannot reach the server. I checked my IP-adres at projecthoneypot but nothing seems to be wrong.
Can somebody tell me what to do?

Regards,

Wamor

**Comment by gizmocuz** [comment]
Please send me a private message on the Forum with your IP address and country

**Comment by marek2k** [comment]
Hi,
I have the same problem. Error 520 from Cloudflare
Firefox display Error code: SSL_ERROR_BAD_CERT_DOMAIN

Is everything OK with the SSL certificate?
https://www.sslshopper.com/ssl-checker.html#hostname=domoticz.com

Regards,
Marek

**Comment by gizmocuz** [comment]
Nothing is wrong. Maybe you are from a country that has been blocked because of lots of ddos attacks.. try using a VPN
Also cloudflare is doing the certificate and there is nothing wrong with it

**Comment by Wamor** [comment]
Hello,

Just to let you know. My Internet-acces was blocked by my provider because one of my raspberry pi's was hacked and used for ddos attacks. I've got a new IP-address and everything works fine again.
Thank you for your response and sorry for bothering you! This issue can be closed now.

Regards,

Wamor
