### ISSUE TITLE
Domoticz Evohome fatal signal 6 (Aborted)

### ISSUE THREAD

**Issue by JanvdW304** [domoticz/domoticz#3808]
I am running Domoticz with Evohome via WebAPI on a RPI osmc installation. Yesterday evening I did a 'sudo apt-get update' and 'sudo apt-get dist-upgrade'. After that my Domoticz stops over and over again within some minutes.

I found in the log that Evohome seems to cause the issue; after making Evohome hardware inactive the problem is over, but I liked the Evohome integration :-(. I found some similiar issues on the forum, without a clear solution.

Log info just after a list with 'SQLH UpdateValueInt' lines that updates zone temperatures:
2019-12-21 00:24:15.562  [6e6fd440] Debug: HTTP 400: Bad Request
2019-12-21 00:24:15.652  [6e6fd440] Error: Domoticz(pid:13661, tid:13680('EvoHome')) received fatal signal 6 (Aborted)
2019-12-21 00:24:15.652  [6e6fd440] Error: siginfo address=0x355d, address=0x76e2d4f9
2019-12-21 00:24:15.692  [6e6fd440] Error: Failed to start gdb, will use backtrace() for printing stack frame

2019-12-21 00:24:15.697  [6e6fd440] Error: #0  /home/osmc/domoticz/domoticz() [0x30a82c]
2019-12-21 00:24:15.697  [6e6fd440] Error: #1  /home/osmc/domoticz/domoticz : signal_handler(int, siginfo_t*, void*) + 0x27c [0x30b2c4]
2019-12-21 00:24:15.697  [6e6fd440] Error: #2  /lib/arm-linux-gnueabihf/libc.so.6 :  + 0x24fe0 [0x76c95fe0]
2019-12-21 00:24:15.697  [6e6fd440] Error: #3  /lib/arm-linux-gnueabihf/libpthread.so.0 :  + 0xe386 [0x76e2e386]

This afternoon I deleted the Evohome hardware and created a new one. As soon as I switched it to active the troubles started over again. So I made the hardware inactive and the rest of the system works fine again.

Any clue how I can fix this?

**Comment by gordonb3** [comment]
Some changes had to be made because Honeywell made some updates related to authentication.

You state that you are receiving data from the module. Can you be more explicit about 'some minutes'? i.e. are we talking one or two update cycles from Evohome here, or 15 minutes maybe?

Assuming you have enabled the higher temperature precision, can you reset that to 0.5 degrees (same as controller). Does the problem still occur then?

**Comment by gordonb3** [comment]
Just noticing you mentioned the issues started after running system updates. Kind of overlooked that as the last update to the EvohomeWeb modules was the same day you entered this issue. That update was not entered into mainline prior to 11:00 AM though, so that can't be it.

You also said something about posts on the forum, are these all about Evohome or about other web based hardware as well?

**Comment by JanvdW304** [comment]
When the hardware is active Domotiz crashes almost immediately. It's possible to make the hardware inactive, but I have to do that immediately. So 2-3 minutes at most.

I have not changed temperature precision, was not aware that I was able to change this.

I found an issue that was quite similar (#1835) but it's not the same: e.g. my system crashes all the time when Evohome is active.

**Comment by gordonb3** [comment]
Right... So you get one update from Evohome and then it crashes right after showing a HTTP 400. Seems related to fetching the schedules. You can verify this by disabling `Show schedule` in the `Evohome via Web API` hardware property page, after which it should no longer crash.

What release of Domoticz are you running? Do you have the Evohome Hot Water module and/or a zone with no schedules set?

**Comment by JanvdW304** [comment]
You're right: the problem is solved after disabling 'Show schedule'.

In the Evohome system no schedules are set at all. Domoticz Blocky runs scripts on certain (presence and time) events to set zone temperatures with the Evohome client.

I run Domoticz version 4.11579.

**Comment by gordonb3** [comment]
Hmmm, that is quite interesting because this means that you must have had those HTTP 400 returns before and that Honeywell is sending an unexpected `id` field in the return body.

Bit hard for me to verify because once a zone has been assigned a schedule it is impossible to remove it completely. Would you be willing to run a sequence of commands and quote the result?

**Comment by JanvdW304** [comment]
Maybe I was happy too soon: Domoticz crashed again, but he was now live for some hours now.

And of course I am willing to do some tests, no problem.

**Comment by gordonb3** [comment]
Okay. First enter your credentials in the following format:
```
user=<your-email-address>
pwd=<your-password>
```

Then proceed with the next sequence:
```
postdata="installationInfo-Type=application%2Fx-www-form-urlencoded;charset%3Dutf-8&Host=rs.alarmnet.com%2F&Cache-Control=no-store%20no-cache&Pragma=no-cache&grant_type=password&scope=EMEA-V1-Basic%20EMEA-V1-Anonymous%20EMEA-V1-Get-Current-User-Account&Username=${user}&Password=${pwd}&Connection=Keep-Alive"

access_token=$(curl -X POST -H "Authorization: Basic YjAxM2FhMjYtOTcyNC00ZGJkLTg4OTctMDQ4YjlhYWRhMjQ5OnRlc3Q=" -H "charsets: utf-8" -H "Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -d "${postdata}" "https://tccna.honeywell.com/Auth/OAuth/Token" | sed "s/,.*$//" |sed "s/{ *\"//" | sed "s/access_token\" *: *//")

userId=$(curl -X GET -H "Authorization: bearer ${access_token}" -H "applicationId: b013aa26-9724-4dbd-8897-048b9aada249" -H "accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -H "content-type: application/json" -H "charsets: utf-8" "https://tccna.honeywell.com/WebAPI/emea/api/v1/userAccount" | grep "userId" | sed "s/[\" ,\n\r]//g" | sed "s/userId://")

firstZoneId=$(curl -X GET -H "Authorization: bearer ${access_token}" -H "applicationId: b013aa26-9724-4dbd-8897-048b9aada249" -H "accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -H "content-type: application/json" -H "charsets: utf-8" "https://tccna.honeywell.com/WebAPI/emea/api/v1/location/installationInfo?userId=${userId}&includeTemperatureControlSystems=True" | grep -m1 "zoneId"  | sed "s/[\" ,\n\r]//g" | sed "s/zoneId://")

curl -D /dev/stderr -X GET -H "Authorization: bearer ${access_token}" -H "applicationId: b013aa26-9724-4dbd-8897-048b9aada249" -H "accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -H "content-type: application/json" -H "charsets: utf-8" "https://tccna.honeywell.com/WebAPI/emea/api/v1/temperatureZone/${firstZoneId}/schedule"
```

In your case the output should start with `HTTP/1.1 400`. I'm interested in what follows.

**Comment by JanvdW304** [comment]
Here is the output:

HTTP/1.1 404 Not Found
Content-Type: text/html
Server: Microsoft-IIS/8.5
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Date: Fri, 27 Dec 2019 21:43:18 GMT
Content-Length: 1245
Set-Cookie: NSC_UDDOB-XfcBqj-TTM-WT=ffffffff090ecc0045525d5f4f58455e445a4a42378b;expires=Fri, 27-Dec-2019 21:45:19 GMT;path=/;secure;httponly

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

Note; I did change the names of the devices today, but didn't change them in the past

**Comment by gordonb3** [comment]
Not what I expected and this should neither cause the crash nor prompt the HTTP-400 you saw in the Domoticz log. The device names are of no consequence here btw, this is only numbered IDs

Maybe you could try for the full list of zones (requires the first three commands from the previous post to be executed in advance):
```
curl -X GET -H "Authorization: bearer ${access_token}" -H "applicationId: b013aa26-9724-4dbd-8897-048b9aada249" -H "accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -H "content-type: application/json" -H "charsets: utf-8" "https://tccna.honeywell.com/WebAPI/emea/api/v1/location/installationInfo?userId=${userId}&includeTemperatureControlSystems=True" | grep "zoneId"
```

Enter the returned values for `${firstZoneId}` in the last command. Should you have the hot water module, also try running that command with `temperatureZone` replaced with `domesticHotWater`. What I'm looking for is the full message of that `HTTP/1.1 400` that you quoted earlier.

**Comment by JanvdW304** [comment]
I am not sure what you ask me to do; which commands should I execute?

**Comment by gordonb3** [comment]
Same commands as before, except when you get to the line that starts with `firstZoneId` you should run the replacement command. Instead of returning just one zone, this will display a list of al your zones. For simplicity you could use each of these values in a variable assignment `firstZoneId=<zoneId>` and then run the last curl command after each new assignment.

If you have the Hot Water module, also run the following:
```
dhwId=$(curl -X GET -H "Authorization: bearer ${access_token}" -H "applicationId: b013aa26-9724-4dbd-8897-048b9aada249" -H "accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -H "content-type: application/json" -H "charsets: utf-8" "https://tccna.honeywell.com/WebAPI/emea/api/v1/location/installationInfo?userId=${userId}&includeTemperatureControlSystems=True" | grep -m1 "dhwId"  | sed "s/[\" ,\n\r]//g" | sed "s/dhwId://")

curl -D /dev/stderr -X GET -H "Authorization: bearer ${access_token}" -H "applicationId: b013aa26-9724-4dbd-8897-048b9aada249" -H "accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -H "content-type: application/json" -H "charsets: utf-8" "https://tccna.honeywell.com/WebAPI/emea/api/v1/domesticHotWater/${dhwId}/schedule"
```

**Comment by JanvdW304** [comment]
I ran the same commands as previous (last one 'userID='), then:
> `curl -X GET -H "Authorization: bearer ${access_token}" -H "applicationId: b013aa26-9724-4dbd-8897-048b9aada249" -H "accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -H "content-type: application/json" -H "charsets: utf-8" "https://tccna.honeywell.com/WebAPI/emea/api/v1/location/installationInfo?userId=${userId}&includeTemperatureControlSystems=True" | grep "zoneId"`

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    75  100    75    0     0    149      0 --:--:-- --:--:-- --:--:--   149

That doens't look like a list of zones, so I thought that I misunderstood something? Neverteless I tried to run the last command afterwards with the following result:
`HTTP/1.1 404 Not Found
Content-Type: text/html
Server: Microsoft-IIS/8.5
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Date: Mon, 30 Dec 2019 08:51:54 GMT
Content-Length: 1245
Set-Cookie: NSC_UDDOB-XfcBqj-TTM-WT=ffffffff090ecc1c45525d5f4f58455e445a4a42378b;expires=Mon, 30-Dec-2019 08:53:55 GMT;path=/;secure;httponly

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>`

**Comment by gordonb3** [comment]
Sorry. My bad. For some reason the line where the access_token is retrieved does not work the way it should, causing the rest of the commands to fail and construct bad URIs

You should get better results with this sequence:
```
access_token=$(curl -s -X POST -H "Authorization: Basic YjAxM2FhMjYtOTcyNC00ZGJkLTg4OTctMDQ4YjlhYWRhMjQ5OnRlc3Q=" -H "charsets: utf-8" -H "Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -d "${postdata}" "https://tccna.honeywell.com/Auth/OAuth/Token" | grep access_token | cut -d, -f1 |sed "s/{ *\"//" | sed "s/\"$//" | sed "s/access_token\" *: *\"//")

userId=$(curl -s -X GET -H "Authorization: bearer ${access_token}" -H "applicationId: b013aa26-9724-4dbd-8897-048b9aada249" -H "accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -H "content-type: application/json" -H "charsets: utf-8" "https://tccna.honeywell.com/WebAPI/emea/api/v1/userAccount" | grep "userId" | sed "s/[\" ,\n\r]//g" | sed "s/userId://")

firstZoneId=$(curl -s -X GET -H "Authorization: bearer ${access_token}" -H "applicationId: b013aa26-9724-4dbd-8897-048b9aada249" -H "accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -H "content-type: application/json" -H "charsets: utf-8" "https://tccna.honeywell.com/WebAPI/emea/api/v1/location/installationInfo?userId=${userId}&includeTemperatureControlSystems=True" | grep -m1 "zoneId"  | sed "s/[\" ,\n\r]//g" | sed "s/zoneId://")

curl -s -D /dev/stderr -X GET -H "Authorization: bearer ${access_token}" -H "applicationId: b013aa26-9724-4dbd-8897-048b9aada249" -H "accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -H "content-type: application/json" -H "charsets: utf-8" "https://tccna.honeywell.com/WebAPI/emea/api/v1/temperatureZone/${firstZoneId}/schedule"

```

**Comment by JanvdW304** [comment]
This doesn't result in a very meaningful result either, as far as I can see:

`HTTP/1.1 404 Not Found
Content-Type: text/html
Server: Microsoft-IIS/8.5
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Date: Mon, 30 Dec 2019 11:19:30 GMT
Content-Length: 1245
Set-Cookie: NSC_UDDOB-XfcBqj-TTM-WT=ffffffff090ecc0245525d5f4f58455e445a4a42378b;expires=Mon, 30-Dec-2019 11:21:30 GMT;path=/;secure;httponly

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>`

**Comment by gordonb3** [comment]
You should probably verify the content of the variables, i.e

```
echo ${access_token}
echo ${userId}
echo ${firstZoneId}
```

You are likely to find at least one that is empty. If that is the access_token then you hit the login rate limit that Honeywell imposed on the API

**Comment by JanvdW304** [comment]
I executed the commands again and verified the contents of these variables: all three of them are empty.

**Comment by gordonb3** [comment]
Yes, if the first one is empty then the rest of them are bound to be empty as well. You did set `user` and `pwd` variables, right?

**Comment by JanvdW304** [comment]
Yes, I did

**Comment by gordonb3** [comment]
Oops... and `postdata` as well?

**Comment by JanvdW304** [comment]
After setting user and pwd variables I have executed the four commands mentioned in your first post today (~2 hours ago) and verified the content of the three variables. Just repeated the process to be sure I didn't miss anything: same result.

**Comment by gordonb3** [comment]
Yeah, sorry about that. Again....

I forgot to add the line where the postdata is set, so you are actually not sending any credentials. This line needs to be executed prior to the four lines from earlier this morning

```
postdata="installationInfo-Type=application%2Fx-www-form-urlencoded;charset%3Dutf-8&Host=rs.alarmnet.com%2F&Cache-Control=no-store%20no-cache&Pragma=no-cache&grant_type=password&scope=EMEA-V1-Basic%20EMEA-V1-Anonymous%20EMEA-V1-Get-Current-User-Account&Username=${user}&Password=${pwd}&Connection=Keep-Alive"
```

**Comment by JanvdW304** [comment]
Mm, no better news: I did the following steps: (1) set user and pwd variables, (2) execute postdata command (3) execute other four commands and (4) verified the content of the three variables. Same result: all empty.

**Comment by gordonb3** [comment]
Guess we need to go manual then, dump the result from at least the login call to screen and copy-paste the relevant part

```
curl -s -X POST -H "Authorization: Basic YjAxM2FhMjYtOTcyNC00ZGJkLTg4OTctMDQ4YjlhYWRhMjQ5OnRlc3Q=" -H "charsets: utf-8" -H "Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml" -d "${postdata}" "https://tccna.honeywell.com/Auth/OAuth/Token"
```

**Comment by JanvdW304** [comment]
I get an error on screen:
`{"error":"invalid_grant"}`

**Comment by gordonb3** [comment]
Ouch. That explains a lot. It means that your password contains characters that require encoding as `%<ASCII HEX code>` to allow them to be passed in a URI string.

example: `!` should become `%21`

**Comment by JanvdW304** [comment]
Indeed, my password contains special characters. So, when I change that, it should be possible to switch on without Domoticz crashes?

**Comment by gordonb3** [comment]
No. It will just allow the sequence of commands listed here to pass, so that we can see the actual response from the Evohome portal and make the necessary changes to the code to properly handle it.

**Comment by JanvdW304** [comment]
OK, but in the meantime I changed my password (also in Domoticz hardware definition), restarted everything, but the situation remains unchanged: still no values for the three variables and the same error `{"error":"invalid_grant"}` for the last command.

**Comment by gordonb3** [comment]
I'm absolutely clueless. The same string of commands work perfectly fine on my system:
1. set `user` (username / email address)
2. set `pwd` (password)
3. set `postdata` (uses username and password)
4. get access token (uses `postdata`)

**Comment by JanvdW304** [comment]
I have no idea either. I have repeated all steps, but get the same output all time.

But for me it was very helpfull to disable 'Show schedule': the devices are now in Domoticz without crashing the system. So, thanks a lot for your help.

**Comment by gordonb3** [comment]
Okay. Would have been nice to know the actual return to make our end more robust, but a happy user is a happy user.

**Comment by JanvdW304** [comment]
Please let me know when I can check additional things

Met vriendelijke groet/ Kind regards,
Jan van de Wetering

________________________________

**Comment by waltervl** [comment]
This issue can be closed?
