### ISSUE TITLE
build failing rapidjson document.h -Wclass-memaccess

### ISSUE THREAD

**Issue by svde** [domoticz/domoticz#3810]
Beta build is failing on FC30, URL to build log: https://build.opensuse.org/package/live_build_log/home:stefan_van_der_eijk/domoticz/Fedora_31/x86_64

[  154s] /home/abuild/rpmbuild/BUILD/domoticz-4.11590/main/../webserver/../cereal/archives/../external/rapidjson/reader.h:487:58:   required from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 272; InputStream = rapidjson::BasicIStreamWrapper<std::basic_istream<char> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]'
[  154s] /home/abuild/rpmbuild/BUILD/domoticz-4.11590/main/../webserver/../cereal/archives/../external/rapidjson/document.h:2159:22:   required from 'rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 272; SourceEncoding = rapidjson::UTF8<>; InputStream = rapidjson::BasicIStreamWrapper<std::basic_istream<char> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator]'
[  154s] /home/abuild/rpmbuild/BUILD/domoticz-4.11590/main/../webserver/../cereal/archives/../external/rapidjson/document.h:2185:73:   required from 'rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with InputStream = rapidjson::BasicIStreamWrapper<std::basic_istream<char> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator]'
[  154s] /home/abuild/rpmbuild/BUILD/domoticz-4.11590/main/../webserver/../cereal/archives/json.hpp:438:48:   required from here
[  154s] /home/abuild/rpmbuild/BUILD/domoticz-4.11590/main/../webserver/../cereal/archives/../external/rapidjson/document.h:1939:24: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'class rapidjson::GenericValue<rapidjson::UTF8<> >' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
[  154s]  1939 |             std::memcpy(e, values, count * sizeof(GenericValue));
[  154s]       |             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  154s] /home/abuild/rpmbuild/BUILD/domoticz-4.11590/main/../webserver/../cereal/archives/../external/rapidjson/document.h:540:7: note: 'class rapidjson::GenericValue<rapidjson::UTF8<> >' declared here
[  154s]   540 | class GenericValue {
[  154s]       |       ^~~~~~~~~~~~
[  156s] make[2]: *** [CMakeFiles/domoticz.dir/build.make:118: CMakeFiles/domoticz.dir/main/domoticz.cpp.o] Error 1
[  156s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/domoticz-4.11590'
[  156s] make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/domoticz.dir/all] Error 2
[  156s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/domoticz-4.11590'
[  156s] make: *** [Makefile:155: all] Error 2

It seems to be fixed upstream: https://github.com/Tencent/rapidjson/pull/1323

Would updating rapidjson to a more recent release be an option?

**Comment by Hopham641994** [comment]
H

**Comment by gizmocuz** [comment]
Is this still an issue ?

**Comment by svde** [comment]
Not an issue anymore.
