### ISSUE TITLE
Popp 700397 energy meter stops working after a short while

### ISSUE THREAD

**Issue by HB787** [domoticz/domoticz#3814]
Team,

I have a Popp 700397 Smart outdoor plug connected, there was an issue with the frequency field that was missing but that was solved in a Beta version. 

Now there is an issue with the energy meter, it works, but only for a short while. 
After reporting the real wattage it goes back to 0.6 watt which I think is its own usage. 
Sometimes it falls back in a few seconds and sometimes for 5 minutes.

Hardware: Raspberry PI 4 
Domoticz:  4.11590 (Beta)
Controller: Aeotec ZW090 Gen5 Z-Wave USB Stick

Thanks in advance for looking into it.

**Comment by waltervl** [comment]
Still an issue?
