### ISSUE TITLE
Browser states does not update 

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#3818]
Hi,
Since many betas Browser states does not refresh/update as before... when I push a Virtual Switch controling other physical devices those values will not update, i.e. on/off or Power consumpion. However If manually refreshing Browser page states updates ok.

I am using Firefox on desktop and Chrome in my Android phone showing same behavoiurs...

Known issue?

**Comment by rwaaren** [comment]
> Since many betas Browser states does not refresh/update as before... when I push a Virtual Switch controling other physical devices those values will not update, i.e. on/off or Power consumpion. 

On which tabs do you see this behaviour 
On what hardware / OS did you install domoticz ?

**Comment by darkrain-nl** [comment]
Not the author of this issue, but I see the same.
On the Dashboard for instance, hardware is a Raspberry Pi 3B+ running Debian Stretch.

**Comment by RicardP** [comment]
@rwaaren Sorry for not saying, I am running Domoticz on WIN10 as service on a dedicated i3 NUC. 
At least Dashboard but as far I remember even other tabs.

**Comment by TheUlpio** [comment]
I also see this issue in the dashboard and switches tab (not tested other tabs):
I run domoticz server on an Odroid C2 with DietPI as OS, and quite a lot of zwave devices (aeon, fibaro, neo coolcam).
The issue is mainly in the lights/switches section of the dashboard. My aeon hem, in the utility sensors section is regularly updated.
The behavior is the same in firefox (70) and android (5.1 and 6) and happens few minutes after a page refresh or tab switch.
For example, accordy to the kodi device, I've been listening to the same song for two days, while the bathroom light is on from last Monday.

**Comment by rwaaren** [comment]
My domoticz is a locally compiled version V4.11595 executed on Raspberry Pi 3B with Debian Buster.
Checked utility, switch and dashboard tabs with different browsers (chrome, edge and firefox but cannot replicate the issue.

**Comment by TheUlpio** [comment]
@rwaaren is there a way to send you a video of the issue?

**Comment by rwaaren** [comment]
> @rwaaren is there a way to send you a video of the issue?

I think your issue is already clear from the description but if you think it adds something then best to add a link here.

**Comment by RicardP** [comment]
@rwaaren no problem, here it is...

[clip.zip](https://github.com/domoticz/domoticz/files/4010919/clip.zip)

I think my record speaks for itself? 

It is ZWave devices/values that does not update in my clip, can it be something wrong with data from OZW so Domoticz is not triggered to refresh when a value changes?

Cheers!

**Comment by gizmocuz** [comment]
Best to open the chrome developer console and check for worries m errors
First test with two browsers open and with a virtual switch...
Also if you are using nginx or a different webroot this has been discussed and solved on the forum

**Comment by darkrain-nl** [comment]
Turns out that it had to do with Nginx in my case, adding

`proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;`

To the config for Nginx fixed this for me.

**Comment by RicardP** [comment]
@gizmocuz So this is not an Domoticz issue? I just install your official  Domoticz Win-installations and gets this problem. In the past this was not an issue for me.

I tested two Browsers open and same Dashboard, when pushing the virtual switch also the second Browser same switch updates synchronized, but not the OZW provided states on any Browser if not updating pages with Browsers Refresh buttons.

I cannot see what I can do if Virtual switch works perfectly but not OZW devices? Please point me to the solution in the Forum so I can learn what to do?

Many thanks!

**Comment by TheUlpio** [comment]
@darkrain-nl This is not my case, i don't have nginx nor other sw installed on my server. Only domoticz

**Comment by darkrain-nl** [comment]
As the original issue is not resolved perhaps this issue should be reopened? @gizmocuz

**Comment by rwaaren** [comment]
Did anyone check the browser developer console tools (console tab) for any unexpected messages. 

( In chrome this can be opened with [ctrl] [shift] I )


![image](https://user-images.githubusercontent.com/24454798/71627611-b449bc80-2bf3-11ea-9872-b4830ca15161.png)

**Comment by RicardP** [comment]
@rwaaren I now noticed that if I do the same maneuver in Switches tab, instead of Dashboard, same states updates perfectly synchronized. So there seems to be an inconsistency in tabs behavior.

I tested the Developer console in Chrome, but I don't know what to look for. Because I see that a lot of "red and warnings" on most website I tested :)

**Comment by rwaaren** [comment]
My approach would be to concentrate on the differences in errors / warnings between the tabs

**Comment by RicardP** [comment]
@gizmocuz could you open this again as you closed it without a solution. I cannot get any obvious feedback from browser Development Console, But as I stated above... 

>  I now noticed that if I do the same maneuver in Switches tab, instead of Dashboard, same states updates perfectly synchronized. So there seems to be an inconsistency in tabs behavior.

How can it be a isolated issue for me as it is showing refresh error on only Dashboard and same problem on any browser, Android phone or PC.  

Thanks!

**Comment by RicardP** [comment]
@gizmocuz @rwaaren 

I did now some more tests and the states does not update on "Room" filtered Dashboard and those Devices that is Not set to "Add to Dashboard" = Yellow Star NOT indicated.

You can test easy with a Virtual Thermostat (setpoint) and add it to Plans-->Roomplan and i.e. Room "Livingroom". Now, go to Dashboard set Room to Livingroom if changing Set Point value the new value wont update if not reloading page, however if you check the Yellow star to it and try again then vale will update on Dashboards, both filtered and non filtered Dashboard.

**Comment by gizmocuz** [comment]
@RicardP , please try with a dummy switch first...

**Comment by RicardP** [comment]
@gizmocuz Why a dummy switch, my example is better as a dummy switch is only on/off and the knob you push updates. It is the related value/s that will not update like the numerical Set value on the Thermostat. Did you test my example with Dummy (virtual) Thermostat / Set point?

**Comment by RicardP** [comment]
@gizmocuz Did you even read my yesterday post, or am I unclear? I don't think so:

> I did now some more tests and the states does not update on "Room" filtered Dashboard and those Devices that is Not set to "Add to Dashboard" = Yellow Star NOT indicated.
> 
> You can test easy with a Virtual Thermostat (setpoint) and add it to Plans-->Roomplan and i.e. Room "Livingroom". Now, go to Dashboard set Room to Livingroom if changing Set Point value the new value wont update if not reloading page, however if you check the Yellow star to it and try again then vale will update on Dashboards, both filtered and non filtered Dashboard.

**Comment by gizmocuz** [comment]
Yep i was not testing correctly... Setting a breakpoint (or adding an alert box) in the RefreshItem function of the dashboard controller revealed the update was there, but it was ignored by a if/then rule
Should now work correctly in 11647

**Comment by RicardP** [comment]
@gizmocuz 
Big thanks, now it looks it is working as expected! :D 

Have a nice weekend!
