### ISSUE TITLE
Zwave General Alarm Event Device not added

### ISSUE THREAD

**Issue by AlexF12004Roma** [domoticz/domoticz#3820]
Domiticz beta  4.11590

![image](https://user-images.githubusercontent.com/6578842/71557945-c38f0580-2a4d-11ea-9251-5e5c8c73e3ea.png)

Device General | Alarm | Event: 0x00 (0)
Added but not shown in any Menu Tab.
Events correctly received and logged

**Comment by fr3sh** [comment]
the same here for that events
![000247_2020-04-03 20_50_09-Domoticz](https://user-images.githubusercontent.com/6498987/78395700-421bb600-75ee-11ea-984a-024b726d971a.jpg)

**Comment by gizmocuz** [comment]
That's correct, it is not 100% implemented, but you can use it in scripting already (blockly for example)

**Comment by fr3sh** [comment]
Thanx for a hint I will check it.
