### ISSUE TITLE
CM180 support via rtl_433 worker does not integrate total kwh

### ISSUE THREAD

**Issue by dgrostoto** [domoticz/domoticz#3832]
the rtl_433 worker report only instant watt usage from rtl_433 program : it discards the total consumption (in kwh) value, whereas the same device (OWL CM180) seems to be correctly integrated via RFXCom.

May it not be integrated differently : sendKwhMeter instead of sendWattMeter presently which only deals with instant watt usage ? or maybe both WattMeter and kwhmeter ?
My concern is  : while using sendkWhMeter, does it has to be called when total consumption is not reported by device (only usage) or not called at all in this case ?

**Comment by dgrostoto** [comment]
OK, I managed to get it work properly. There is two devices created : the first one is as it was done previously (usage electricity device) and the second one is type general in kwh, computed by device itself (since the device report total consumption in kwh).
Tested OK on my installation.
Here is the file modified, can you have a look and integrate it if you think it is OK ?
[Rtl433_04012020_release.cpp.txt](https://github.com/domoticz/domoticz/files/4022443/Rtl433_04012020_release.cpp.txt)

**Comment by gizmocuz** [comment]
Thank you for looking into this.
Unfortunately i can not see the change in the file you send, could you make a git Pull Request (PR) ?

**Comment by dgrostoto** [comment]
OK, created  a pull request for this
https://github.com/domoticz/domoticz/pull/3855

**Comment by gizmocuz** [comment]
Thank you for the PR !
What is the meaning of 'sequence' ? In your PR this is not used... is this an index ?
It also seams you only call 'SendKwhMeter' when 'haveSequence' is true
If we always need a sequence, then the if/then check could be

if (haveEnergy && havePower && haveSequence)

I have looked at the rtl_433 source code, and there are currently two devices being supported with 'energy_kWh'

- esic_emt7110
- oregon_scientific

the 'esic_emt7110' does not use the 'sequence', in that case, it will not work as SendKwhMeter will not be called

My 'bet' is that we do not need to use the 'sequence' and just use 'sensoridx' ?

**Comment by dgrostoto** [comment]
Hello, the sequence is a cycling index which tells what type of frame is sended.
In CM180 case it cycles from 4 to 0 (values from 4 to 1 defines secondary frames with instant power only and value 0 defines the main frame with instant power and total kwh).
I added this code with ikea sparsnas in mind which is is another device supporting total kWh also use sequence cycling (note there may have some code refactoring on rtl_433 side to report the right column or adapt from domoticz side : to be discussed). I did not see  esic_emt7110.
So you're right about the fact that we cannot assume that all energy meter uses sequence and even if, not necessarily in the same manner.
OK for not using sequence number, only use instant watt and total kwh presence to determine sensoridx (as we need 2 different sensorIdx for wattmeter and kwhmeter).
Sequence cycling could be used for error checking but as i did not see much error checking in rtl433, and it must be an error checking device specific, i'm not sure to develop this check (as you like).
I make the modifications in the PR.

**Comment by dgrostoto** [comment]
committed
https://github.com/domoticz/domoticz/pull/3855/files

**Comment by gizmocuz** [comment]
Thanks for the change !

One more request:

You now have a else {
}
block, but this was not needed, you could have left the "else if (FindField(data, "power_W"))"
and added a new

else if (FindField(data, "power_W"))

underneath this

Is it possible to do so ?

**Comment by dgrostoto** [comment]
Hello again, sorry for being not available these past days. I saw you integrated the PR (I don't mind about those "if/else" if you i prefer another coding style as long as the most devices are functional and code is still fluently readable). Thanks for your integration, it helps much for me as a plan to use several of these devices.

**Comment by dgrostoto** [comment]
if integration is complete, this issue can be closed.
