### ISSUE TITLE
Nest login (non-Oauth device type) fails after update to 4.11590 (beta)

### ISSUE THREAD

**Issue by dbomber** [domoticz/domoticz#3833]
It's like the issue 3777 (https://github.com/domoticz/domoticz/issues/3777).

The login fail with the error :
Error: Nest: Invalid data received, or invalid username/password!

**Comment by rwitkamp** [comment]
Same for me with 4.11590 beta

**Comment by heggink** [comment]
Yup. Pi beta seems a couple of releases old tho...

**Comment by bitflusher** [comment]
just confirming: 4.11605, last data januari 6

**Comment by juhnboii** [comment]
still not working on 4.11631, last data on my Domoticz was 5 januari

**Comment by waltervl** [comment]
Still an issue?
