### ISSUE TITLE
RTl433 Smoke detector GS

### ISSUE THREAD

**Issue by mojso** [domoticz/domoticz#3834]
please insert it into devices
Smoke detector GS 558 - vibration sensore
does not recognize it as a device

Json:
{"time" : "2020-01-04 14:19:30", "model" : "Smoke detector GS 558", "id" : 16624, "unit" : 5, "learn" : 0, "code" : "c81e05"}

`2020-01-04 14:03:08.294 Status: Rtl433: Unhandled sensor reading, please report: (time,msg,codes,model,button,id,channel,battery,temperature_C,mic,subtype,rid,humidity,state,status,brand,rain_rate,rain_rate_mm_h,rain_rate_in_h,rain_total,rain_mm,rain_in,gust,average,direction,wind_max_m_s,wind_avg_m_s,wind_dir_deg,pressure_hPa,uv,power_W,energy_kWh,radio_clock,unit,group_call,command,dim,dim_value,wind_speed,wind_gust,wind_direction,wind_avg_km_h,wind_max_km_h,dipswitch,rbutton,device,temperature_F,battery_ok,setpoint_C,switch,cmd,cmd_id,tristate,direction_deg,speed,rain,msg_type,signal,sensor_code,uv_status,uv_index,lux,wm,seq,rainfall_mm,wind_speed_ms,gust_speed_ms,current,interval,learn,message_type,sensor_id,sequence_num,battery_low,wind_speed_mph,wind_speed_kph,wind_avg_mi_h,rain_inch,rc,gust_speed_mph,wind_max_mi_h,wind_approach,flags,maybetemp,binding_countdown,depth,depth_cm,dev_id,sensor_type,power0,power1,power2,node,ct1,ct2,ct3,ct4,Vrms/batt,batt_Vrms,temp1_C,temp2_C,temp3_C,temp4_C,temp5_C,temp6_C,pulse,address,button1,button2,button3,button4,data,sid,group,transmit,moisture,type,pressure_PSI,battery_mV,pressure_kPa,pulses,pulsecount,energy,len,to,from,payload,event,alarm,tamper,heartbeat,temperature1_C,temperature2_C,temperature_1_C,temperature_2_C,test,probe,water,humidity_1,ptemperature_C,phumidity,newbattery,heating,heating_temp,uvi,light_lux,pm2_5_ug_m3,pm10_0_ug_m3,counter,code,repeat,maybe_battery,device_type,raw_message,switch1,switch2,switch3,switch4,switch5,extradata,house_id,module_id,sensor_count,alarms,sensor_value,battery_voltage,mode,version,type_string,failed,class,alert,secret_knock,relay,wind_dev_deg,exposure_mins,transmit_s,button_id,button_name,encrypted,misc,current_A,voltage_V,pairing,connected,gap,impulses,triggered,storage
2020-01-04 14:03:08.294 |2020-01-04 14:03:06,,,Smoke detector GS 558,,16624,,,,,,,,,,,,,,,,,,,,,,,,,,,,5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,c81e05,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2020-01-04 14:03:08.294 )`

**Comment by gizmocuz** [comment]
Could you post a log when the state is changing ? I would expect a state field like for a switch ?

**Comment by mojso** [comment]
that's all the sensor sends.  when activated sends this
From rtl_433
Json:
{"time" : "2020-01-04 14:19:30", "model" : "Smoke detector GS 558", "id" : 16624, "unit" : 5, "learn" : 0, "code" : "c81e05"}

**Comment by Net-time** [comment]
I get this sometimes when one of my temperature sensors send a truncated message.
Starting hardware RTL433 in Domoticz  with parameters -R -86 sorts it.
Unless Mosjo really has a unhandled sensor and it's just not a false positive?
The only mention of a sensor is "vibration sensore" no mark or model.
Anyway disabling "86" might trigger another parser.

**Comment by dgrostoto** [comment]
According to rtl_433 there is a key called "code" when the message is complete.
Please use the option -M newmodel to get the message from rtl_433 since I'm trying to get to new (default) model of rtl_433 with normalized keys.

**Comment by dgrostoto** [comment]
should work with PR https://github.com/domoticz/domoticz/pull/3902, maybe this issue can be closed.
