### ISSUE TITLE
Luminance is shown by domoticz multiplied by 10

### ISSUE THREAD

**Issue by Micha-123** [domoticz/domoticz#3839]
hi, i have an Zwave 4in1 multisensor "Vision Security"

in openzwave pannel it show a luminance at 1.04% but in domoticz it wil be shown as 10Lux 

it wil be always multiplied by 10

also tested the latest beta and it dont solves the problem

![SharedScreenshot](https://user-images.githubusercontent.com/35665484/71959841-efe81600-31f3-11ea-9301-09f02238cf68.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/35665484/71959845-f37b9d00-31f3-11ea-8ad1-8fdcf8e87ff6.jpg)

**Comment by xztraz** [comment]
test sensor (with phone app for example) to see if its is 1 lux or 10 lux where you measure

**Comment by Micha-123** [comment]
The phone app shows it like the openzwave page,

So if sensor shows in openzwave 20. 64% the phone shows it nearby like the sensor in openzwave. 

But domoticz shows not 20. 64 lux but 206 lux

Like the  .  (dot) was not after 20 but after the 6,

Domoticz rounds only the second number after dot. 

So if luminance is 20,66 so domoticz rounds it to 207 lux not to 20.7 lux.

I have also an other zwave sensor, the other sensor shows lux only per 1% on that sensor domoticz shows the lux good. So ig that sensor show 20% domoticz says 20lux

But the sensor that shows lux with two numbers after dot   like 20.66 domoticz shows 207 lux (rounds only the last number)


Now sensor is showing 0.87 lux (it is on the roof, so there ia realy dark)  but domoticz says 9 lux,  and in the darknes is thats not possible to be 9 lux

**Comment by xztraz** [comment]
just wanted to make sure the original reading where correct first. sounds like domoticz is taking numbers with decimals in another way.

**Comment by gizmocuz** [comment]
Domoticz convert the % value to Lux in a range from 0-1000, so this is not a bug.... (see the comments in OpenZWave.cpp, line 1912)

**Comment by Micha-123** [comment]
Yes but domotitcz converts the decimals wrong


So if sensor gives 20,78 % that must be 21 lux (rounded) 

Bomoticz convert it to 208 lux 

It rounds oy the last decimal

**Comment by gizmocuz** [comment]
@Micha-123 , no it does not. Percentage is not the same as Lux, 43.2% is not 43.2 lux
It is scaled to 0-1000 Lux, see the code above

**Comment by Micha-123** [comment]
sorry, i know it scale lux from 0 to 1000, but by that sensor i have is it realy % = Lux, i measures it, 90 lux (on an phone app) it gives its about 90% max lux on that sensor is 100, if it is more it gives simple 100 lux

i mesaured it, i can change it in the source code, but maybe is it configurable without need recompile domoticz from source ?


here is an pdf of that sensor

https://www.cd-jackson.com/zwave_device_uploads/307/ZSE40-tech-info.pdf


scale light reporting = 0x00 (%)

**Comment by gizmocuz** [comment]
Yes, and Domoticz is using LUX not percentage. This can/will not be changed, and is also not needed

**Comment by Micha-123** [comment]
Yez i know that domoticz is using lux, but by that devise is realy 30% = 30 lux,  i measured it with the phone app, 30 lux gives the phone app near the sensor and domoticz shows 301 lux

In openzwave pannel it shows lux right but as % not as lux.

So if without change the source and compiling domoticz by me own i must live with that fault measures and the lux is not usuable.

**Comment by gizmocuz** [comment]
That would be when the range of that device was in 0-100 lux, domoticz is unsing 0-1000

**Comment by gizmocuz** [comment]
0.1 lux is also extreme low... 100 lux is also very low

**Comment by Micha-123** [comment]
That device rage of that device is 0-100 %/lux

That is realy so, i make pictures later... 


Phone near the sensor,

Domoticz shows lux always  x10 of thst what the phone is showing

**Comment by gizmocuz** [comment]
Please mind you the issue is closed and not considered a issue.
It could be a language problem, but look at your first screenshot, the unit is in %,
also from experience it is percentage.
Domoticz converts this to a range of 0 - 1000 Lux, whatever, could have been converted to 0-5000 Lux
Anyway, 3.31% also does not make any sense does it ? It reads much better now
Issue closed, not an issue and this is by design

**Comment by Micha-123** [comment]
Yes i see it is closed.

3,31 (or rounded 3) makes more sense

Why?

I have another sensor (aeon labs) that sensor is downstairs and shows luminance direct by lux not percentage.

The "probem" zensor is on the roof where is only a smal window

No i open domoticz, downstairs by a day i see in domoticz 140 lux (where are much windows an there is realy much light) and on the roof where there is a Little bit of light comming through  small window, domoticz show me 260 lux

Looks that than much better? 

Why a range from 0 - 1000?

Why not make it configurable? In a file or by the semsor it self? And set it from 0 - 1000 as standard? So every one can use own right range that is used by sensor.

**Comment by gizmocuz** [comment]
The issue is that some sensors report in Lux, and some in Percentage.
I don't want to have two different type of Lux sensors inside the system.
Please feel free to make a PR with the option to change this per ZWave node, but as I see it (yeah i have a crazy mind), in the end its a value, if your % lux sensor reads 450 Lux in Domoticz, and you find that acceptable for let's say 'daylight', you should use this value in your scripts

**Comment by Micha-123** [comment]
For my own is it enough to chage it in the source, it is onle the only one sensor that report it i  percentage.

So i Thing i change it in the source or i make an simple config file where i can set the range without need to recompile whole domoticz. 

It was an idea to make it configurable for every one, and set it Standard to - 0 - 1000, so every can then "calibrate" his percentage node.

For my own is it enough when i change it in the source, but now i need to change it every time and compile if there is an new version of domoticz. 

thank you for the tip where it is to change in the source so i dont need to search it in the whole source.

**Comment by gizmocuz** [comment]
For your own, just create a patch that you can apply each time when you update the code
Good luck!

**Comment by xztraz** [comment]
Tip.  Read the data from sensor in a script (dzvents), make calculations and update a dummy sensor with the correct lux value. I've had to do similar stuff with some weather sensors that's read weird by domoticz (wind, gust for example). you can hide the original sensor with a $ in the name.  no patching needed. and domotics can continue to read that sensor as % which is a stupid measurement of light anyway..   0-1000 lux is nothing.. sun gives 60K-100K lux in full sunshine.

**Comment by Micha-123** [comment]
yes, thank you, it is only one sensor, so i maked a simple dzvents script to calculate the right value (and round the dezimals) and now it is looking fine, 


but maybe for the future it wil be nice to make it configurable in the device config (like the offset of temperatur sensors) so it wil be not needed to make for every sensor an second virtual sensor and kalkulate then update the virtual sensor by an script

a range from 0 to 1000 by an percentage (percentage is max 100 so it wil be simple x10) makes not much sense, they are to mach sensors reporting lux in % and they have all an other Range. maybe 1000 is wil be near much sensors but why not make it configurable? 



p.s. xtraz   1000 lux is realky MUCH, 


here is an good table of lux readings 

https://en.wikipedia.org/wiki/Lux


50 lux is living room lights (ok maybe now is it what more)

1000 lux is Overcast day; / Studio light

here you right 100k is direkt SUN

but mostly in a living room they are about 30 to 250 lux (measured on a wall, not directly under the lamp, but under the lamp is it much more) 

and all Cell phones give it so, so mostly you are within 0 and 400 lux in an living room (if you dont believe measure it with an professional Lux meter but not directly under the lamp, you dont turn the lighrt on for watching direct in the lamp) 



but for now i have it solved with an virtual sensor and an calculating dzvents script (so simple hehehe thank you for that advice)

**Comment by xztraz** [comment]
@Micha-123 i thought you had the sensor outside since you mentioned " it is on the roof, " i guess you meant in the ceiling indoors. well there you would not get 100K no. I work with cameras and tv-production. have a fairly good sense for lux ;)  Glad you solved it. Its the first sensor i've heard of reporting light with %. If you are happy with the script you could maybe upload it to the wiki so others can solve similar stuff too.

**Comment by Micha-123** [comment]
its the most simplest script i have ever made :D 

feel free to share it on wiki,

`return {
	on = {
		devices = {
			429
		}
	},
	execute = function(domoticz, device)
		local zolder1000 = domoticz.devices(429)
		local zolder = domoticz.devices(436)
		
		zolder.updateLux(domoticz.utils.round((zolder1000.lux / 1000) * 100))
		end
}`


but it wil be fine to have it on configurable in the WebIF like offset of Temp in Temperature sensors, simple set of maximum (in that script is it 100) of the sensor and thats it :D
