### ISSUE TITLE
Configuring (color) devices in a scene activates the device

### ISSUE THREAD

**Issue by dannybloe** [domoticz/domoticz#3840]
When you change the color of a device when configuring a scene actually turns the device on. It shouldn't do that. (At least for Hue devices)

**Comment by GravityRZ** [comment]
noticed this also on hue devices but thought it was a feature(eg see the color you selected/configured)

**Comment by gizmocuz** [comment]
If you mean when you change the color, it sends it to the actual light ?
Yeah this is meant to be, so you can set the exact color and see how it looks on the real device

**Comment by dannybloe** [comment]
Yes, I can see that but then it should return to the previous state when you leave the settings panel. It disrupts stuff where it shouldn't imho. But maybe that's too much work to make that work. Even better: a preview button that you can activate when editing the scene would be better I guess.

Ah well. It just annoyed me that suddenly lights turned on only to find out later when you enter the area that suddenly lights are on that you didn't know were on.

**Comment by gizmocuz** [comment]
Problem is when you then pick the color, you have to press each time on the preview... 
Good that you dont have to perform this a lot
