### ISSUE TITLE
Popp smart plug 700793 not in manufacturer_specific.xml

### ISSUE THREAD

**Issue by HB787** [domoticz/domoticz#3842]
Team,

The Popp Smart Plug 700793 exists as an xml file in the Config/popp directory, but the device is not recognized because it seems not to exist in the manufacturer_specific.xml.

When trying to include it, it does this with an unrecognized node name:
Unknown: id=0154 Unknown: type=0003, id=1002 | Unknown: id=0154 | 0x1002 | 0x0003 | 

Thanks in advance!

Platform:  Raspberry PI4
Controller: Aeotec zw-090 usb stick
Version: 4.11590
Build Hash: d7cb21393
Compile Date: 2019-12-21 11:03:24
dzVents Version: 2.5.3
Python Version: 3.7.3 (default, Apr 3 2019, 05:39:12) [GCC 8.2.0]

**Comment by HB787** [comment]
Hi Team,
Added this row to the manufacturer_specific.xml
<Product config="popp/700793.xml" id="1002" name="700793 Smart Power Plug" type="0003"/>

Now it was recognized.
The Popp 700793 power plug is also sold at the Hornbach stores at an attractive price.
Energy measurement works well, the plug is VDE certified and has a capacity of 3.2 Kw.

Hope this can be added to the next Beta release.

**Comment by gizmocuz** [comment]
You have to make a PR with the change in the openzwave repository.
