### ISSUE TITLE
custom templates custom.example issue

### ISSUE THREAD

**Issue by yoFra** [domoticz/domoticz#3843]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by yoFra** [comment]
I'm using domoticz V4.10717 on a rasp pi 2 B V1.1
I add Netatmo therm hardware to have some data and I would try custom.example

So rename, modifiy the last lines .domoticzurl and .PageArray vars and try it on browser.
The custom page appears but no value on it.

Checking server side no issues.
Checking browser side : there is a issue there :

--asking for data--
https://192.168.0.102/json.htm?type=devices&plan=4&lastupdate=1578739963&jsoncallback=jQuery33106113857464036324_1578739673577&format=json&_=1578739673607
--json issue--
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
--raw data--
var data={
   "ActTime" : 1578741769,
   "AstrTwilightEnd" : "19:29",
   "AstrTwilightStart" : "07:01",
   "CivTwilightEnd" : "18:15",
   "CivTwilightStart" : "08:15",
   "DayLength" : "08:51",
   "NautTwilightEnd" : "18:53",
   "NautTwilightStart" : "07:37",
   "ServerTime" : "2020-01-11 12:22:49",
   "SunAtSouth" : "13:15",
   "Sunrise" : "08:49",
   "Sunset" : "17:41",
   "app_version" : "4.10717",
   "status" : "OK",
   "title" : "Devices"
}

jQuery33106113857464036324_1578739673577(data);
----
Could you explain me what the problem ?

**Comment by rwaaren** [comment]
Maybe but not here. The domoticz issue list is meant for Code bugs. So please use the forum for this type of questions. 
And when doing so please add where you found this example so other members trying to help do not have to search for it.
Thx

**Comment by yoFra** [comment]
Sorry rwaaren but the template file i tried comes fron domoticz itself :
~/docmticz/www/templates/custom.example

**Comment by yoFra** [comment]
Hre is the link :
https://github.com/domoticz/domoticz/blob/development/www/templates/custom.example
