### ISSUE TITLE
Add 'More options' submenu timer for mouse-over

### ISSUE THREAD

**Issue by kipusoep** [domoticz/domoticz#3845]
The More options submenu underneath the Setup menu is acting a bit nervous, because it disappears whenever the mouse isn't hovering the submenu anymore.
So you have to be really careful when you don't want the submenu to disappear.

A fix shouldn't be hard. As an example I found a blogpost: https://css-tricks.com/dropdown-menus-with-more-forgiving-mouse-movement-paths/

**Comment by rwaaren** [comment]
Please use the forum for theming questions / remarks
There are already themes using other menu / submenu methods 
machinon theme being one of them

https://www.domoticz.com/forum/viewtopic.php?f=8&t=24084

**Comment by stefankip** [comment]
I'm sorry, didn't know there was something like themes support in Domoticz. I'll have a look to find some other theme then :-)
