### ISSUE TITLE
Button off delay not working as expected

### ISSUE THREAD

**Issue by mkudej** [domoticz/domoticz#3848]
Im on latest stable version: 
Version: 4.10717
Build Hash: b38b49e5
Compile Date: 2019-05-09 13:04:08
dzVents Version: 2.4.19
Python Version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]

I have seted up a button. I added for it 30 sec off delay.

Expectation:
When I click on active button, after [30sec] it will go off.

How it really works: 
I click off - button immediately go to off state.
What i noticed: When i turn on my button and wait delay [30sec] it automaticly turns off.

Is it general bug?

**Comment by rwaaren** [comment]
The domoticz github is for code bugs only.
Please use the forum for this question.

in domoticz there are two types of buttons.

push On button where you can set delays but can only push On
push Off button where you can not set delays
