### ISSUE TITLE
User management allows multiple accounts with same login

### ISSUE THREAD

**Issue by romainrossi** [domoticz/domoticz#3850]
Using the user management panel, it is possible to create multiple users with the same login.
It is even possible to create multiple account with the same login but different permissions.

![Capture d’écran de 2020-01-15 13-08-42](https://user-images.githubusercontent.com/26712493/72432900-75da0300-3798-11ea-9aca-bd0931eee386.png)

I think this is a bad behavior as users are identified by the login so it should be unique on the system.

I am using Domoticz built from the git repository (branch development) (see below for the version information). However, I think this issue is old and not specific to this version.

Version: 4.11609
Build Hash: 70500a9c6
Compile Date: 2020-01-13 19:44:14
dzVents Version: 2.5.5
Python Version: 3.6.9 (default, Nov 7 2019, 10:44:02) [GCC 8.3.0]

**Comment by gizmocuz** [comment]
Thanks for reporting! Solved in beta 11623
