### ISSUE TITLE
Dusk Sensor images reversed

### ISSUE THREAD

**Issue by MrHobbes74** [domoticz/domoticz#3853]
Dusk sensors are ON when it is dark and OFF when it is light.
Since I switced from released to the latest beta version (4.11605), dusk sensors show the reversed icons: ON = sunny and OFF = dark.

This is wrongly implemented in 
www/app/LightsController.js and www/app/DashboardController.js.

In above scripts, ON is considered sunny and OFF is considered dark for Dusk Sensors in various places. Can this be repaired? I have now done it manually in my domoticz installation.

**Comment by gizmocuz** [comment]
Thanks for reporting! Fixed in beta 11622
