### ISSUE TITLE
Daikin wifi worker : setpoint stuck with old value until next polling is done

### ISSUE THREAD

**Issue by dgrostoto** [domoticz/domoticz#3854]
It seems that when setPoint temperature is set with a new value. The web interface of domoticz does not update to specified value immediately. It waits next polling (polling is 300 seconds for in Daikin.cpp) to make the update.
The expected behaviour is that setpoint is immediately updated (and command is immediately sended but this point is OK).

There is two possibility to fix this issue IMHO :
1. member variable m_sec_counter be modified as for SetGroupOnOff() or SetModeLevel() ? (make it close to next polling so that next polling update the value) 
OR
2. A different technique be applied like 'Ventillation' (it's a fan) commands (normally controlled by SetF_RateLevel() but in this case i did not understood how immediate refresh is done) ?

Version used is compiled from github source code on 21/12/2019.

**Comment by dgrostoto** [comment]
I'm not sure which option is the best. I've done the first modification on my personal installation which seems to work OK as far as now, but i have to check there is no multiple (one for setting setpoint and one more a few seconds after to poll all AC data) http requests send to the wifi daikin interface (it may seem that this interface does not like frequent requests very much and may cause some problems to the main AC unit, in my case : it might locks maximum performance to 40%).

**Comment by gizmocuz** [comment]
Another option is to just send the new setpoint value to Domoticz
So you send the setpoint to the device, when the ret=OK (so it worked) call

SendSetPointSensor(20, 1, 1, temp, "Target Temperature");

**Comment by dgrostoto** [comment]
OK, i will try this a my system to see if it is OK. In any ways, do you prefer me to make a PR for this ?.

**Comment by gizmocuz** [comment]
If it is working great, sure a PR would be good

**Comment by dgrostoto** [comment]
Mmmm i've found other bugs about the same file recently. I keep an open eye and i will  fix them all in one PR.
(reminder) list of bugs found so far :
- setpoint does not update immediately
- setting setpoint does modify ventillation (side effect) with old value (but without apparent modification in the web interface)
- maybe setting ventillation does modify setpoint (reverse side effect) with old value (this one to be checked).

**Comment by gizmocuz** [comment]
Can this issue be closed?

**Comment by dgrostoto** [comment]
Yes! it behaves well. Just need to add else at the end SetSetPointSensor() method :
	if (sResult.find("ret=OK") == std::string::npos)
	{
		Log(LOG_ERROR, "Invalid response");
		return;
	}
	**else { 
		SendSetPointSensor(20, 1, 1, temp, "Target Temperature");
	}**
can you do so in the dev branch ? (i'm lazy to PR just for one line of code :) ) and this issue can be closed

**Comment by gizmocuz** [comment]
Thanks ! Yes but sometimes one line can make the difference ;)
('else' was not needed)
Should be available in upcoming beta (11671)
