### ISSUE TITLE
@gizmocuz @rwaaren

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#3860]
@gizmocuz @rwaaren 

I did now some more tests and the states does not update on "Room" filtered Dashboard and those Devices that is Not set to "Add to Dashboard" = Yellow Star NOT indicated.

You can test easy with a Virtual Thermostat (setpoint) and add it to Plans-->Roomplan and i.e. Room "Livingroom". Now, go to Dashboard set Room to Livingroom if changing Set Point value the new value wont update if not reloading page, however if you check the Yellow star to it and try again then vale will update on Dashboards, both filtered and non filtered Dashboard.

_Originally posted by @RicardP in https://github.com/domoticz/domoticz/issues/3818#issuecomment-577395933_

**Comment by gizmocuz** [comment]
Strange Issue topic, please continue your discussion in your original issue
