### ISSUE TITLE
Evohome Hotwater sensor graphs are showing incorrect setpoint

### ISSUE THREAD

**Issue by brucemiranda** [domoticz/domoticz#3861]
I changed my Hot Water setpoint from 60C to 55C today on the Evohome Controller. However the Domoticz graphs for the Hot Water device are still showing the setpoint as 60C. Which means that the set point is fixed in Domoticz somewhere. But where is that set?
I'd like the code to be able to change that set point value based on what the user does on Evohome.

**Comment by brucemiranda** [comment]
I've now submitted a PR myself to fix this.

**Comment by Olifant1990** [comment]
Please refer to it with a link ;)
https://github.com/domoticz/domoticz/pull/4414

**Comment by brucemiranda** [comment]
This will stay open until the PR 4414 is merged.
https://github.com/domoticz/domoticz/pull/4414

**Comment by Olifant1990** [comment]
That is wrong in my and GitHubs way ;)
You can close this as this problem is fixed in a PR.
As it is linked by naming it, everyone can see the PR is still open, but the bug itself is fixed!

**Comment by brucemiranda** [comment]
Fair enough. Closed.
