### ISSUE TITLE
Feature request: dzVents timer trigger to detect a startup of domoticz

### ISSUE THREAD

**Issue by MrHobbes74** [domoticz/domoticz#3864]
When Domoticz is terminated, the latest states are kept. But events that may occur during downtime are missed (e.g. sunset, sunrise). After a next startup of Domoticz, some states may be invalid but will not be re-triggered for a while. A re-initialization may be required through execution of some actions.

For example: to determine the current status of a one-way 433 mhz dusk sensor, a lamp can be switched on and off to force the dusk sensor to be triggered in case its dark.

Of course, I can write an Event that executes every minute and only does something the first time the script is executed (as was suggested in some forum topics). And I'm sure there are other workarounds. But native support would be more natural and does not require an Event to be executed every minute for nothing.

Is it possible to implement a timer trigger (similar to 'at sunset' and 'at sunrise') but then called e.g. 'at startup'? Events with this trigger would then only be executed directly after Domoticz' event loop started. For me it sounds like a natural extension of the event system to be able to automatically recover from downtime.

**Comment by MrHobbes74** [comment]
I'm gonna have a try at it myself. Browsing throught the code and the event queue, I think it is doable.

**Comment by gizmocuz** [comment]
Try WebServer.cpp, CWebServer::Cmd_UpdateDevice
Add a parameter like 'trigger' and check when it's set to true or false, when not provided is should always do the trigger to be backwards compatible

**Comment by rwaaren** [comment]
> I'm gonna have a try at it myself. Browsing throught the code and the event queue, I think it is doable.>

That would be great !
@dannybloe and me were discussing your request this morning on Slack and were going to give it try in the dzVents Lua code but it is much better if this can be triggered natively from the event system.
Please let me know if I can help with the dzVents side of things, updating the dzVents test suite and/or updating the documentation / wiki.

**Comment by dannybloe** [comment]
MrHobbes74 better not try it yourself without discussing this first. I have a branch with a lot of C++ code ready to do this with lots of ideas on how to do it but the branch is old. If we do this it has to be done right so other system events also can end up in dzVents. So: great you wanna help (really!)  but let's discuss it first. We're on Slack. PM me with your email and I'll add you if you are not already there.

**Comment by MrHobbes74** [comment]
Let's discuss on Slack. I'd love to contribute.

**Comment by MrHobbes74** [comment]
Delivered with PR #3901. Can be closed.
