### ISSUE TITLE
On/Off Action trigger returned 256

### ISSUE THREAD

**Issue by Lyr3x** [domoticz/domoticz#3868]
Version: 4.11652
Build Hash: 2ac631921
Compile Date: 2020-01-25 08:08:36
dzVents Version: 2.5.7
Python Version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
OS: Linux 4.19.0-0.bpo.4-amd64 #1 SMP Debian 4.19.28-2~bpo9+1 (2019-03-27) x86_64 GNU/Linux

Since the SamsungTV Python plugin seems to be broken (instant domoticz crash) I tried to add a little bash script to the on/off action of a dummy button.
The scripts working fine and without any problems. However, the dummy switch is not. Using other dummy switches with on/off scripts fine though.
On action gives no error but does not trigger the script and Off action is logging:
2020-01-25 21:28:38.061 Error: Error executing script command 
(/home/domoticz/domoticz/scripts/bash/tv_off.sh). returned: 256`

On script: (funny thing: worked with another tv just fine!)
```
#!/bin/bash
wakeonlan -i 255.255.255.255  B8:BC:5B:A9:5B:48 > /dev/null 2>&1 &
```

Off script:
```
#!/bin/bash
samsungctl --host 192.168.2.146 --port 8002 --timeout 2 --method websocket KEY_POWER 2>&1
```

Permissions:
```
-rwxr-xr-x  1 domoticz domoticz  147 Jan 24 22:21 tv_on.sh
-rwxr-xr-x  1 domoticz domoticz  102 Jan 24 22:56 tv_off.sh
```

**Comment by gizmocuz** [comment]
Please use the Forum
