### ISSUE TITLE
RTL433 PCR800 mm and inch confusion ?

### ISSUE THREAD

**Issue by dgrostoto** [domoticz/domoticz#3872]
This night i had my first rain reported by my PCR800 (i hadn't rain since days...), and  i found values reported in domoticz rather low, i investigated quickly and i think there confusion between inches and mm (the old battle royal Britanic system vs international metric system which already made a plane crash...)
rtl_433 software seems to report rain in inches and inches per hour.
But domoticz believe it is mm and mm per hour.
see below my data in the same hour
rtl433 - classic format (rounded 0.1%f)
time      : 2020-01-28 02:47:02                    brand     : OS
model     : PCR800       House Code: 134
Channel   : 0            Battery   : OK            Rain Rate : 0.3 in/hr     Total Rain: 1.5 in

rtl433 - csv format (without round by default)
time,msg,codes,model,button,id,channel,battery,temperature_C,mic,subtype,rid,humidity,state,status,brand,**rain_rate,rain_rate_mm_h,rain_rate_in_h,rain_total,rain_mm,rain_in,**gust,average,direction,wind_max_m_s,wind_avg_m_s,wind_dir_deg,pressure_hPa,uv,power_W,energy_kWh,radio_clock,sequence,unit,group_call,command,dim,dim_value,wind_speed,wind_gust,wind_direction,wind_avg_km_h,wind_max_km_h,dipswitch,rbutton,device,temperature_F,battery_ok,setpoint_C,switch,cmd,cmd_id,tristate,direction_deg,speed,rain,msg_type,signal,sensor_code,uv_status,uv_index,lux,wm,seq,rainfall_mm,wind_speed_ms,gust_speed_ms,current,interval,learn,message_type,sensor_id,sequence_num,battery_low,wind_speed_mph,wind_speed_kph,wind_avg_mi_h,rain_inch,rc,gust_speed_mph,wind_max_mi_h,wind_approach,flags,maybetemp,binding_countdown,depth,depth_cm,dev_id,sensor_type,power0,power1,power2,node,ct1,ct2,ct3,ct4,Vrms/batt,batt_Vrms,temp1_C,temp2_C,temp3_C,temp4_C,temp5_C,temp6_C,pulse,address,button1,button2,button3,button4,data,sid,group,transmit,moisture,type,pressure_PSI,battery_mV,pressure_kPa,pulses,pulsecount,energy,len,to,from,payload,event,alarm,tamper,heartbeat,temperature1_C,temperature2_C,temperature_1_C,temperature_2_C,test,probe,water,humidity_1,ptemperature_C,phumidity,newbattery,heating,heating_temp,uvi,light_lux,pm2_5_ug_m3,pm10_0_ug_m3,counter,code,repeat,maybe_battery,device_type,raw_message,switch1,switch2,switch3,switch4,switch5,extradata,house_id,module_id,sensor_count,alarms,sensor_value,battery_voltage,mode,version,type_string,failed,class,alert,secret_knock,relay,wind_dev_deg,exposure_mins,transmit_s,button_id,button_name,encrypted,misc,current_A,voltage_V,pairing,connected,gap,impulses,triggered,storage
2020-01-28 02:47:49,,,PCR800,,134,0,OK,,,,,,,,OS,0.270,,,1.531,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

and in domoticz  : 0.2 mm reported for same hour.
So inches seem to be "translated" directly (ie without conversion) in millimeters.

My proposal 
- i think there is a fix to do on rtl_433 and another fix on domoticz. On rtl_433 side, measurements should not be reported without the unit, and and domoticz side, the value should be interpreted and inch/mm choice should be a list choice on the parameter list of the application (next to the wind units).

**Comment by dgrostoto** [comment]
i've just checked the -C si option for rtl_433 and unfortunately it does not help (does nothing about inches/mm for classic nor csv output)

**Comment by gizmocuz** [comment]
These are the values in your log

![image](https://user-images.githubusercontent.com/2265299/73240705-0d2f5500-41a0-11ea-98ed-be0e1c14c3a5.png)

**Comment by gizmocuz** [comment]
With the above fields, domoticz is using the rain_total (have a look in the Domoticz/Rtl433.cpp code)
In the code from RTL433 (oregon_scientific) i see they are using inches indeed.
For the 'Biltema-Rain sensor' they use mm,
I think they should use one standard and do the internal conversion to mm

But.... for now we can compare against the model number and do the conversion

Please try beta 11658 ... it should convert the inches to mm ...

**Comment by dgrostoto** [comment]
Thanks for the beta. I'll try ASAP.
I ommited to say that actual rounding (in fact, looks more like truncating at first decimal) was losing a lot of precision (0.1 inch which seem the max truncate loose many millimeters of water...)
Do the rounding apply before of after conversion ?

I've checked with one of the mainteners of rtl_433. They have a new model (command line option is -M newmodel) created  nearly one year ago which seems to be the new one standard expected.
They is some work to integrate it (i see battery level is different from actual and certainly much more), Would you be OK for a rewrite of rtl433.cpp on domoticz to integrate with this newmodel ? (have to check for maturity about this model before of course).

**Comment by dgrostoto** [comment]
Note about maturity of rtl433 newmodel : in fact, rtl_433 will default shortly to the newmodel (oldmodel will be an option for few months then old stuff will be removed from code), so it will break compatibility soon.
https://github.com/merbanan/rtl_433/issues/1277#issuecomment-579160604

**Comment by gizmocuz** [comment]
Domoticz is using the rain counter (total rain since the beginning of time...) 2 digits would be better
conversion from inch to mm is a multiply of 25.4
0.1 inch -> 2.54mm
0.15 inch -> 3.81mm

it makes a difference indeed... if it is much... that is for you to decide ;)

About the 'new model' I am not sure if we need to modify the Domoticz code, but if it is not working, post a log line and we can make it work...

**Comment by dgrostoto** [comment]
i confirm that domoticz code need to be modified. I can PR relatively quickly it if you want, i feel now more comfortable with this kind of modification.

**Comment by gizmocuz** [comment]
Sure, please do so! All help is wanted of course ;)

**Comment by dgrostoto** [comment]
OK, job done. see PR https://github.com/domoticz/domoticz/pull/3902
(it was a little longer that i tought because i had to create a parser to be sure to get all rtl_433 new keys).

**Comment by dgrostoto** [comment]
I've noticed that there is a dozen of issues (declared in github) about rtl_433. The newmodel may change things about them and may close some of them (the prologue rid question for example https://github.com/domoticz/domoticz/issues/3272 since rid is now id for normalized keys).
If you're OK i can investigate on those cases and fix them as best as i can (I'm also using some prologue sensors, so I'm concerned by this issue). Let me know if my PR is OK for you and I'll start investigate those issue with the "newmodel"  and respond to other users concerning rtl_433 domoticz integration.

**Comment by dgrostoto** [comment]
ok this issue can be closed with PR https://github.com/domoticz/domoticz/pull/3902
