### ISSUE TITLE
event editor is empty

### ISSUE THREAD

**Issue by NiekN** [domoticz/domoticz#3873]
i updated Domotcz to version 4.11662(latest version)

but what is wrong with the events editor?
i want to edit a lua script and see
![image](https://user-images.githubusercontent.com/32562791/73299690-f0326a80-420f-11ea-9998-47a50a45c8d1.png)

i see no lua scipt anymore

**Comment by NiekN** [comment]
oops also the Devices tab is empty

![image](https://user-images.githubusercontent.com/32562791/73301251-b747c500-4212-11ea-9bbb-09d072d953a9.png)

**Comment by rwaaren** [comment]
Please use the forum for this type of questions. Thanks !!

A lot of the problems users experience after a domoticz update are gone when the browsercache and appcache (different things !) are cleared. There are also quite a number of posts on this forum related to these kind of problems. 

To summarize and sorted from little effort to a bit more effort take these steps and check after each step if it address the issues you encounter.

- clear browser cache and appcache 
    Chrome:     chrome://appcache-internals/#
    Firefox:    https://support.mozilla.org/en-US/kb/storage    
    
- in www/js look for domoticz.js.gz, if its there remove it, (KEEP domoticz.js !! )
- use incognito mode using 
    Chrome   [control] [shift] n
    Firefox: [control] [shift] p
    
- restart domoticz
- rename the location of the original installation and install the new version to an empty target directory. Next copy database and scripts from the old location and fire it up.


Hope this will also solve your problem.
