### ISSUE TITLE
Switch OFF Delay Feature implementation

### ISSUE THREAD

**Issue by SteveJos** [domoticz/domoticz#3874]
I would like to switch off a specific device (3d printer) with a give delay, e.g. the connected RaspberryPi will send a switch off command to the Domoticz server before shutting down all systems properly. In the meantime it sends the off command and directly kills the plug. 
The given delay feature does not work as one would expect it to be: if setting the "off delay" in seconds, Domoticz just power off the device after a given delay time instead of delaying the actual power off  command. 
Please help me to unterstand how I could implement my approach or change the code in order to get the delay feature work different.

Thank you in advance!
Stev

**Comment by rwaaren** [comment]
Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum

So please use the forum !
