### ISSUE TITLE
Domoticz Yeelight

### ISSUE THREAD

**Issue by fixss** [domoticz/domoticz#3875]
I have Domoticz v4.11665 installed on Ubuntu
Yeelight Bulbs color v2 firmware v2.0.6.0065
All connected to xiaomi gateway v2 and working though the miHome rules, but it always so laggie because of chinese servers, so i try to move to Domoticz.

I trying control my RGBWW Yeelight Bulbs through xiaomi wireless switch, but i have some problems:

1) All my Bulbs is RGBWW, but in Domoticz only one connected like it, and all the others is connected like RGBW. I tried delete all Bulbs and add them again, but with no luck. Some random bulbs connect like RGBWW, some like RGBW.

2) Absolutely no logs. Only if i turn on Bulb inside Domoticz - there is some information appear in logs. If i use Xiaomi MiHome\Yeelight\GoogleHome apps - nothing will be added in logs.

3) Another problem - Domoticz don't see any changes with bulbs, if i turn them on or off in Xiaomi MiHome\Yeelight\GoogleHome apps, domoticz do not update any information about it.

Please can somebody help me ? I trying figure it out for month, but looks like without help i can't.

**Comment by rwaaren** [comment]
Please use the forum for these type of questions. 
Thx

* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
