### ISSUE TITLE
24h graphs are not shown | beta 4.11666

### ISSUE THREAD

**Issue by josemi73** [domoticz/domoticz#3883]
Hi
I have updated to 4.11666 and Stretch to Buster because libc6 issue.
Everything seems working properly, but **24h graph don't show** in device Log page, it is empty. Nevertheless, last contact date and time are right.
Month and Year graphs are ok.
I have deleted cache, appcache, incognito mode, and I don't see them either.
What could I do?

![temperature](https://user-images.githubusercontent.com/52371223/73604987-d179fe00-4598-11ea-979c-54a741ec793e.GIF)

**Comment by gizmocuz** [comment]
I have no issues here.
Try another browser ?....
What type of device is this ?

**Comment by rwaaren** [comment]
I cannot replicate this on V4.11668 (NUC Debian Buster)

**Comment by josemi73** [comment]
> I have no issues here.
> Try another browser ?....
> What type of device is this ?

I have already tried three different browsers...
Devices are those with graph: humidity, temperature, by Xiaomi, Shelly, even OpenWeatherMap and DarkSky.

**Comment by josemi73** [comment]
I have downloaded domoticz.db for see values, and in LightingLog is getting updated data.

![LightingLog](https://user-images.githubusercontent.com/52371223/73605326-33d4fd80-459d-11ea-9aba-49b9dae3cffe.GIF)

**Comment by gizmocuz** [comment]
Could you try in Chrome, open the developer console (F12) and click on the 'console' tab
do you see any errors ?

**Comment by josemi73** [comment]
Three warnings:

![warnings](https://user-images.githubusercontent.com/52371223/73605621-c034ef80-45a0-11ea-93ca-91f5ce5c36e8.GIF)

**Comment by josemi73** [comment]
@gizmocuz 
24h Graphs are working now. Only I have re-installed pylgtv plugin because some errors, and I have deleted a error big value in the database. I do not know if it could have been that.
Thank you for your interest. I close the issue.

![sValue_error](https://user-images.githubusercontent.com/52371223/73606011-a77b0880-45a5-11ea-899b-8392820b9698.GIF)

**Comment by gizmocuz** [comment]
Great! Thanks for the feedback!!
