### ISSUE TITLE
Youless LS120 not giving pulse readings anymore

### ISSUE THREAD

**Issue by Juanuil** [domoticz/domoticz#3884]
After the last update to 4.11666 my LS120 is not reporting pulses anymore.
In the forum I read that there was a fix for de S0 update.
It might be fixed for S0 but I have a coventional meter and untill the last update this worked fine.
But now the normal pulse meter is not shown anymore in devices.
Even after removing and reinstalling the Youless only a S0 device appears.

**Comment by gizmocuz** [comment]
Please do not cross post, i just send you an email after reading your issue on the forum

**Comment by wimmme** [comment]
@gizmocuz I hate to say this but my LS120 is not working well in Version: 2020.2 (build 12136) (nor in 2020.2.11995)
I only have one device, youless counter (type energy)
Or should i open a new issue ?
