### ISSUE TITLE
Domoticz errors at 00:00:00

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3885]
running 4.11.605 stble for months on a synology platform
al of a sudden i get these errors.

is this related to domoticz. seems to run fine now but apparently it could not find the lua scripts at exactly 00:00:00

> 2020-02-02 00:00:00.286 Error: dzVents: Error: (2.5.5) module 'dzV-Dump MQTT' not found:
> 2020-02-02 00:00:00.286 no field package.preload['dzV-Dump MQTT']
> 2020-02-02 00:00:00.286 no file '/usr/local/share/lua/5.3/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/share/lua/5.3/dzV-Dump MQTT/init.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/lib/lua/5.3/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/lib/lua/5.3/dzV-Dump MQTT/init.lua'
> 2020-02-02 00:00:00.286 no file './dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file './dzV-Dump MQTT/init.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/dzVents/runtime/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/dzVents/runtime/device-adapters/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/dzVents/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/scripts/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/../lua/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/scripts/modules/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/generated_scripts/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/data/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/modules/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-Dump MQTT.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/lib/lua/5.3/dzV-Dump MQTT.so'
> 2020-02-02 00:00:00.286 no file '/usr/local/lib/lua/5.3/loadall.so'
> 2020-02-02 00:00:00.286 no file './dzV-Dump MQTT.so'
> 2020-02-02 00:00:00.286 Error: dzVents: Error: (2.5.5) module 'dzV-P1 meter-telegram' not found:
> 2020-02-02 00:00:00.286 no field package.preload['dzV-P1 meter-telegram']
> 2020-02-02 00:00:00.286 no file '/usr/local/share/lua/5.3/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/share/lua/5.3/dzV-P1 meter-telegram/init.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/lib/lua/5.3/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/lib/lua/5.3/dzV-P1 meter-telegram/init.lua'
> 2020-02-02 00:00:00.286 no file './dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file './dzV-P1 meter-telegram/init.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/dzVents/runtime/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/dzVents/runtime/device-adapters/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/dzVents/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/scripts/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/../lua/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/scripts/modules/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/generated_scripts/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/data/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/modules/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-P1 meter-telegram.lua'
> 2020-02-02 00:00:00.286 no file '/usr/local/lib/lua/5.3/dzV-P1 meter-telegram.so'
> 2020-02-02 00:00:00.286 no file '/usr/local/lib/lua/5.3/loadall.so'
> 2020-02-02 00:00:00.286 no file './dzV-P1 meter-telegram.so'
> 2020-02-02 00:00:00.287 Error: dzVents: Error: (2.5.5) module 'dzV-P1 meter' not found:
> 2020-02-02 00:00:00.287 no field package.preload['dzV-P1 meter']
> 2020-02-02 00:00:00.287 no file '/usr/local/share/lua/5.3/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/share/lua/5.3/dzV-P1 meter/init.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/lib/lua/5.3/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/lib/lua/5.3/dzV-P1 meter/init.lua'
> 2020-02-02 00:00:00.287 no file './dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file './dzV-P1 meter/init.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/dzVents/runtime/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/dzVents/runtime/device-adapters/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzVents/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/scripts/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/../lua/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/scripts/modules/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/generated_scripts/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/data/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/modules/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-P1 meter.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/lib/lua/5.3/dzV-P1 meter.so'
> 2020-02-02 00:00:00.287 no file '/usr/local/lib/lua/5.3/loadall.so'
> 2020-02-02 00:00:00.287 no file './dzV-P1 meter.so'
> 2020-02-02 00:00:00.287 Error: dzVents: Error: (2.5.5) module 'dzV-Skybell-IFTTT-telegram' not found:
> 2020-02-02 00:00:00.287 no field package.preload['dzV-Skybell-IFTTT-telegram']
> 2020-02-02 00:00:00.287 no file '/usr/local/share/lua/5.3/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/share/lua/5.3/dzV-Skybell-IFTTT-telegram/init.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/lib/lua/5.3/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/lib/lua/5.3/dzV-Skybell-IFTTT-telegram/init.lua'
> 2020-02-02 00:00:00.287 no file './dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file './dzV-Skybell-IFTTT-telegram/init.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/dzVents/runtime/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/dzVents/runtime/device-adapters/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzVents/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/scripts/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/../lua/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/scripts/modules/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/generated_scripts/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/data/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/modules/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-Skybell-IFTTT-telegram.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/lib/lua/5.3/dzV-Skybell-IFTTT-telegram.so'
> 2020-02-02 00:00:00.287 no file '/usr/local/lib/lua/5.3/loadall.so'
> 2020-02-02 00:00:00.287 no file './dzV-Skybell-IFTTT-telegram.so'
> 2020-02-02 00:00:00.287 Error: dzVents: Error: (2.5.5) module 'dzV-Veranda-aan' not found:
> 2020-02-02 00:00:00.287 no field package.preload['dzV-Veranda-aan']
> 2020-02-02 00:00:00.287 no file '/usr/local/share/lua/5.3/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/share/lua/5.3/dzV-Veranda-aan/init.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/lib/lua/5.3/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/lib/lua/5.3/dzV-Veranda-aan/init.lua'
> 2020-02-02 00:00:00.287 no file './dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file './dzV-Veranda-aan/init.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/dzVents/runtime/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/dzVents/runtime/device-adapters/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzVents/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/scripts/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/../lua/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/scripts/modules/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/generated_scripts/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/data/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/modules/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/domoticz/var/scripts/dzVents/dzV-Veranda-aan.lua'
> 2020-02-02 00:00:00.287 no file '/usr/local/lib/lua/5.3/dzV-Veranda-aan.so'
> 2020-02-02 00:00:00.287 no file '/usr/local/lib/lua/5.3/loadall.so'
> 2020-02-02 00:00:00.287 no file './dzV-Veranda-aan.so'
>

**Comment by rwaaren** [comment]
I cannot replicate this on my Synology 916+ domoticz Version: 4.11665
Seem highly unlikely that this is caused by domoticz. Please upgrade to latest Beta first and if still an issue report on the forum so Jadahl can also have a look.
Thx
