### ISSUE TITLE
Problem with 4.11666 and >

### ISSUE THREAD

**Issue by PHIL-IP** [domoticz/domoticz#3886]
Hi,
Since the install of the beta 4.11666 Domoticz has a status : Active (Exited) 
If I launch domoticz with the command : ./domoticz then I can see this error :
 ./domoticz: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by ./domoticz)
./domoticz: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ./domoticz)

I have no error with the versions 4.11660 and 4.11662, only since the 4.11666
Domoticz run on a Raspberry Pi 3 B+ under Raspian 9.11 (Stretch) and the last version of GLIBC is the 2.24.

How can I continue to use beta on my Raspberry under Raspian 9.11 ?

Regards

**Comment by kevsterd** [comment]
I get the same.   Something obviously broken in the build.... My error is

`./domoticz: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by ./domoticz)
./domoticz: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ./domoticz)
`

I'm on Stretch as well.   Machine was running prior release (Jessise) but I upgraded it as I thought that may the issue, as well as needing to as well.

`PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch

4.14.94-v7+ #1193 SMP Tue Jan 22 15:34:30 GMT 2019 armv7l GNU/Linux`

Need to try and remember how to roll back or hoping someone fixes it. please !

**Comment by kevsterd** [comment]
Looks like its a known issue, being discussed on the main forum
https://www.domoticz.com/forum/viewtopic.php?f=6&t=31157&start=20

Fix is to upgrade to Raspian Buster !
