### ISSUE TITLE
Invisible buttons on iPhone

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#3890]
Version 4.10717
On IOS is the motion button displayed with white text The buttons are olmost invisible when there is no motion detected.
![IMG_1543](https://user-images.githubusercontent.com/33230021/73833409-3e47ff00-480a-11ea-8624-4a1d3be2764a.PNG)

**Comment by MrHobbes74** [comment]
This is an issue with the IPhone app, not with Domoticz itself. Please move to here: 
https://github.com/domoticz/domoticz-xamarin

**Comment by gizmocuz** [comment]
@HilverinkJ , is this with the native domoticz web gui ? In that case we need to solve it in Domoticz

**Comment by ghost** [comment]
Yes, it is.

Verstuurd vanaf mijn iPhone

**Comment by gizmocuz** [comment]
Should be solved now in beta 11748

**Comment by waltervl** [comment]
> Should be solved now in beta 11748

Closing this.
