### ISSUE TITLE
Latest Beta on buster. Zwave-timeout crashes domoticz

### ISSUE THREAD

**Issue by xztraz** [domoticz/domoticz#3891]
RPI updated to buster.
latest beta as 2020-02-05

Zwave timeouts seem to crash/hang domoticz.

log:
`
Feb  5 14:20:22 raspberrypi domoticz: dzVents: Info: Handling events for: "Motion North", value: "Off"
Feb  5 14:20:22 raspberrypi domoticz: dzVents: Info: ------ Start internal script: Utebelysning Aut: Device: "Motion North (Dummy)", Index: 989
Feb  5 14:20:22 raspberrypi domoticz: dzVents: Info: ------ Finished Utebelysning Aut
Feb  5 14:20:23 raspberrypi domoticz: OpenZWave: User Alert - Manufacturer_specific.xml out of Date
Feb  5 14:20:23 raspberrypi domoticz: OpenZWave: Received unhandled notification type (30) from HomeID: 0, NodeID: 0 (0x00)
Feb  5 14:20:23 raspberrypi domoticz: OpenZWave: User Alert - Manufacturer_specific.xml out of Date
Feb  5 14:20:23 raspberrypi domoticz: OpenZWave: ManufacturerSpecificDB Ready
Feb  5 14:20:24 raspberrypi domoticz: OpenZWave: Driver Ready
Feb  5 14:20:24 raspberrypi domoticz: SendSwitchIfNotExists: Device '8.instance.1.index.0.commandClasses.38' (Level) with DeviceID '00000801' matches '8.instance.1.index.0.commandClasses.37' (Switch). Domoticz will use the Dimmer (and hide the Switch).
Feb  5 14:20:24 raspberrypi domoticz: SendSwitchIfNotExists: Device '9.instance.1.index.0.commandClasses.38' (Level) with DeviceID '00000901' matches '9.instance.1.index.0.commandClasses.37' (Switch). Domoticz will use the Dimmer (and hide the Switch).
Feb  5 14:20:24 raspberrypi domoticz: SendSwitchIfNotExists: Device '15.instance.1.index.0.commandClasses.38' (Level) with DeviceID '00000F01' matches '15.instance.1.index.0.commandClasses.37' (Switch). Domoticz will use the Dimmer (and hide the Switch).
Feb  5 14:20:26 raspberrypi domoticz: OpenZWave: Received timeout notification from HomeID: 3698476673, NodeID: 17 (0x11)
`

forum: https://www.domoticz.com/forum/viewtopic.php?f=6&t=31181

**Comment by gizmocuz** [comment]
@xztraz , is it solved ? What was the issue?

**Comment by xztraz** [comment]
The upgrade went south so i can't say this was a proper bug. I can't reproduce now. had to re-install from scratch and went to stable instead.
