### ISSUE TITLE
Thermosmart keeps on set temparature while program is ended

### ISSUE THREAD

**Issue by harolds** [domoticz/domoticz#3894]
There is a problem with the Thermosmart plugin. I have setup schedules on the thermosmart so that it will keep my house warm during the day. And at 23:00 it goes to its away/night mode. That means 15 degrees. As soon as I enable the Thermosmart plugin in Domoticz it does no longer switch back to the temperature that I have setup for the night (so 15 degrees). And thus the heating stays on the whole night! Its next to our bedroom so it keeps us awake... very annoying.

Of cause I could manually set the temperature to 15 degrees before I go to bed. But that should not be needed as this is all automated.

I have contacted the Thermosmart team about this problem and they concluded that the problem is the plugin so they can not fix it in their product.

I hope someone can figure this out and fix it.

**Comment by rwaaren** [comment]
As you may have noticed this issue list is not the best place for reporting issues in plugins.
You will probably have more luck if you try to contact the developer of the plugin via the domoticz forum or the github for that plugin (if any)
