### ISSUE TITLE
contact and doorcontact : inverted

### ISSUE THREAD

**Issue by kenvannylen** [domoticz/domoticz#3895]
When window/door is closed, the contact/doorcontact is making contact, but the status will be displayed as "open".  This is the opposite of what should be displayed.
"contact inverted" and "door contact inverted" should be available to select from as a switch type. (comparable to doorlock inverted and blinds inverted).

Best solution would be to have an extra checkbox "inverted" that you can check or uncheck, for all the switch types.

I'm using the Denkovi IP-MAXI via LAN (HTTP) hardware.

**Comment by kenvannylen** [comment]
Please, make it possible to invert ALL switches... A harware door/window switch is closed when it's making contact (1). It's opened when the contact is broken (0). This is the opposite of how a door and contact is programmed in domoticz. Please create a checkbox to make it possible to invert every type of switch.

**Comment by gizmocuz** [comment]
That is depending on the hardware you use I suppose
When it is making door-contact or contact, it should be 'closed' and considered not to raise any alarm
when it does not make contact it should be 'open'

And no it is not a good idea to make it generic for all switches, also does not make sense, for example we receive ON from a 433Mhz node or ZWave node, then it is ON

Does 'Contact' and 'Door-Contact' both report the same status, this because you are using a relay board (contact) and not an official 'door-contact'

**Comment by kenvannylen** [comment]
Dear,

Thanks for your reply.
Indeed, it does not make sense to invert standard hardware like ZWave. On means on, off means off.

I am using a relay board (denkovi) with I/O contacts to read my hardware wired magnet door and window contacts. Closed is when the magnets are closed (the wire circuit is closed) and the relay board passes “ON” to domoticz.  (it can not be reversed in the denkovi board, unfortunately). Domoticz translates “ON” for a switch, as “Open” for a contact/doorcontact. It should be possible to invert contact and door contact in this situation.

**Comment by kenvannylen** [comment]
This is still an issue. A hardware switch that is making contact (or not) should be possible to be translated as open or closed. An possibility to invert is needed for this...

**Comment by kenvannylen** [comment]
Please create a "contact inverted", similar to "doorlock inverted". I really need this !

**Comment by gizmocuz** [comment]
@kenvannylen , Indeed, and I am using ZWave.
Please contact Denkovi about this, maybe their status is inverted
