### ISSUE TITLE
dzVents logging with LOG_ERROR does not trigger Domoticz's notification

### ISSUE THREAD

**Issue by cincuranet** [domoticz/domoticz#3897]
Whenever an error in Domoticz happens and the _Send Errors as Notifications_ is enabled an email is sent. But when I log manually in dzVents with LOG_ERROR, this email is not sent. This looks to me like an unexpected behavior and I think the same email should be sent.

Version: 4.10717
Machine: RPi 3
OS: Raspian (10.2, 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l)

**Comment by rwaaren** [comment]
> Whenever an error in Domoticz happens and the _Send Errors as Notifications_ is enabled an email is sent. But when I log manually in dzVents with LOG_ERROR, this email is not sent. This looks to me like an unexpected behavior and I think the same email should be sent.
> 
> Version: 4.10717
> Machine: RPi 3
> OS: Raspian (10.2, 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l)

An Email is send when a dzVents LOG_ERROR is logged in recent beta's.
