### ISSUE TITLE
Feature request: disable event system via api

### ISSUE THREAD

**Issue by mrrioes** [domoticz/domoticz#3900]
to switch between a "smart mode" and a "dumb mode" I´m searching for a way to disable the event system with a switch. I´m currently doing this for timerplan with a dummy switch and the api command. 
Would be nice if this could be done for the events as well instead of having a if condition in every single script.

**Comment by gizmocuz** [comment]
Sorry this is not possible and have to be set from the settings page
You might be able to read/change this via a bash script

**Comment by mrrioes** [comment]
Ok. Can you give me a hint how to do that via bash?

**Comment by rwaaren** [comment]
yes, use sqlite3 with a SQL statement.
please use the forum for howto type of questions
