### ISSUE TITLE
"Big number" on counter.

### ISSUE THREAD

**Issue by Smanar** [domoticz/domoticz#3903]
Hello there is a problem on some counter, for exemple the RFXmeter.
On the code it seem you are using.

```
						result2 = m_sql.safe_query("SELECT MIN(Value) FROM Meter WHERE (DeviceRowID='%q' AND Date>='%q')", sd[0].c_str(), szDate);
						if (!result2.empty())
						{
							std::vector<std::string> sd2 = result2[0];

							uint64_t total_min = std::stoull(sd2[0]);
							uint64_t total_max = std::stoull(sValue);
							uint64_t total_real = total_max - total_min;
```

But there is a problem if you reset the counter, total_max  = 0 and you have total_real with a "negative vlue"

Sometime you have it only on device widget, so it's not a problem, it is corrected on next value, but sometime it's logged, and you have that on report

![Capture_Domoticz_-_Google_Chrome_2020-02-09_20-43-35_43425232](https://user-images.githubusercontent.com/4583709/74108693-3925df80-4b7d-11ea-9c99-ead038986f6d.png)

It's not possible make something like
```
if (total_max > total_min)
{
uint64_t total_real = total_max - total_min;
}
else
{
uint64_t total_real = total_max;
}
```

With this code, during the reset, the value memorised is 0 (if sValue= 0) , and on next report total_min will be 0.
Or something to ignore the value or force a reset ?

I know it's fixed the next day, but ATM report are totaly unusable (and I know the manipulation to repair it, but it's not for me)

**Comment by gizmocuz** [comment]
You can also shift click on the value in the interface to delete it
Feel free to make a PR

**Comment by Smanar** [comment]
Yep, as I have said, I know how to repair, but it's not for me, It's not the first user I see whith this problem.
There is no-one with the full domotiz dev environnement that want to try theses 3 lines changes ?

And there is a problem.
IDK how to reproduce the bug, I can with widget, but it don't appear on report every time, this screenshot is not from me.

**Comment by nesalkiN** [comment]
Yeah. I got this (my image) when I had a big power cut at home.

**Comment by Smanar** [comment]
Ok, so on my side I give up.
I have find how to correct the display in the widget, the modification is so easy (and logic, seriously I don't understand why it's not corrected yet)
```
//prevent "big number" bug
if (total_max < total_min)
{
	total_min = 0;
}
```

But this bug is on so many place (for all report too), and so many device type.

**Comment by karekaa** [comment]
I struggle with some similar problems, where temperatures from RFLink based nodes are sometimes far off, where typical the next temperature is a jump of e.g. 20 celsius up or down before the very next is sensible value again.  There should be a way to intervene with some correction, to say that a new value is too far off from the previous, there either don't record or set it to the same as the previous valid one.
What about adding a hook before next value is stored into the database for how to make an own sanity check for either through away the new value or artificially set it to some more sensible one?

**Comment by gizmocuz** [comment]
@karekaa , we could do this yes... If you like, please make a PR with the needed changes in mainworker.cpp
But of course.. this should not happen !? ... Do you have an alternative way to receive this sensor ? Via a RTL433 stick ? Or RFXCom RFXtrx433-e/xl ? Is it a problem only with the RFLink ?
Do you use the latest firmware ? Maybe tell the developer ?

**Comment by gizmocuz** [comment]
@Smanar , same as the previous message, yes it sounds logical... Please make a PR with the needed changes in mainworker.cpp

**Comment by Smanar** [comment]
@gizmocuz I have find on the code for the widget display, easy to repair.
But I haven't found on the code for the "report" panel, the page where domoticz display graph for daily/monthly/year and make calculation for price.

The first one isn't important, just need another value to correct display, but the second one is realy usefull. If you remember the fonction name ?

**Comment by gizmocuz** [comment]
@Smanar , surely the problem has to be addressed in the backend system and not in the web gui
Of course your hardware should not send such a big number, but it should be catched/ignored in mainworker.cpp

**Comment by Smanar** [comment]
In fact I m not sure  (or depend what you are calling backend system)
It's not backend system fault, you send it a value and it store it.
It's not device fault, he have a real value and send it as it.

For me the problem is just when domoticz use database to display something on GUI (or make calculation)
And it's this part I can't find on code when you are making monthly report for exemple (I realy don't know your code)

**Comment by gizmocuz** [comment]
@Smanar , I don't thing the problem is the underlying c++ code that generates the big value,
the big value is probably inside the database.
Could you verify this ?
Else if you see the big number in the graph, could you send me a PM in the forum so we could email ? I would like to have a closer look inside your database...

**Comment by Smanar** [comment]
I need some time to genereate the bug (I haven't it on my side, I know how to provoke it on widget, but haven't tried with database yet)
But perhaps you have someone with it here https://www.domoticz.com/forum/viewtopic.php?f=6&t=31507&p=238467#p238467

**Comment by Smanar** [comment]
OK, so I realy can't reproduce the problem.
I can reproduce it visually but on my side It 's never memorised ...

I have tried
- increase value by 10 during a day and set lower value.
- set a value on a day then nothing on next and same after. (to simulate a power cut)

Domoticz store value "as it" or it can make modification before storage ?

**Comment by gizmocuz** [comment]
@Smanar , best to have a look inside the database with for example 'SQLite Expert Personal Edition'

**Comment by Smanar** [comment]
Yeah, you are right, but I haven't the bug on my side, I m asking to other user if some of them have keep it, but without suprise for the moment all have cleaned the database.

**Comment by Smanar** [comment]
Ok, so impossible for me finding bugged database, impossible to reproduce bug.

Too rare situation, not usefull keep this issue open.

I will re-open it later, if I have something usefull.
