### ISSUE TITLE
User rights management : viewer/user/admin on a device basis

### ISSUE THREAD

**Issue by dgrostoto** [domoticz/domoticz#3906]
Hello,
Could it be possible to manage user rights on a per device basis instead of a per user as presently ?
Actually, the need is to get a read only access on deviceA and the read/Write access on deviceB for one user.
This will permit for example to create a dashticz dashboard for a user to have access to lights switchs  but not for heat devices which are also a switch (let's say it is a home visitor :) )

**Comment by gizmocuz** [comment]
No you have to do it per user bases. But you can login with the option 'remember me' that should give you access for quite some time with this user

**Comment by dgrostoto** [comment]
I should have precised that it concerns json api accesses (i suppose Users declared in domoticz web interface apply to json calls). After reflexion, I understand that it might be complex on the same web interface to have some device ReadOnly access and others ReadWrite access.
But that's a real problem for big systems with many users (with major security concerns) which use only json API, i really need a finer access so that a user can have access to one device RO and other device RW. The option "remember me" does not help since it applies to the web interface i think.
The only workaround i've imaginated is to have one user per device rights (one device : 2 users, the first one readonly for the device and the second RW), but that's pretty ugly (a tons of users have to be created and password management is difficult to handle)
May i propose some PR to make a finer access to devices ?

**Comment by gizmocuz** [comment]
For those switches that 'some' users should not allow to switch... you can enable the 'protected' option, this will ask for an additional password

**Comment by dgrostoto** [comment]
OK, I'll do some tests to understand how it works and how i can make use of it (i'm still relatively new to domoticz) and i'll get back to you.
