### ISSUE TITLE
RGB, setKelvin(), cancelQueuedCommands()

### ISSUE THREAD

**Issue by EvgenaNet** [domoticz/domoticz#3907]
Hi!
Here is a problem.
If we do setKelvin() in the loop, we can not stop this loop by cancelQueuedCommands() such, as with dimTo(), for example.

Here is the simle code.
`return {

	--active = false,
	
	on = {
		devices = { 32 }				   -- список устройств, изменение статусов которых приведет к запуску данного скрипта
	},
	
	logging = {
		level = domoticz.LOG_INFO,
		marker = 'ТЕСТ'
	},
	
	execute = function(domoticz, device)
	
		local button	= domoticz.devices(32)			-- 32 - кнопка в спальне
		local lamps		= domoticz.groups(1)

		if ( button.state == 'Click' ) then

			lamps.devices().forEach(function(lamp)

				lamp.cancelQueuedCommands()

				dim = 1
				kelvin = 99
				pause = 0

				for i = 1,100 do
					lamp.dimTo(dim).afterSec(pause)
					lamp.setKelvin(kelvin).afterSec(pause)   -- IF COMMENT THIS STRING cancelQueuedCommands() WORKING WELL
					domoticz.log('lamp.name ' .. lamp.name .. ' dimTo(' .. dim .. ') setKelvin(' .. kelvin .. ') afterSec(' .. pause .. ')')
					pause    = i * 18
					dim      = dim + 1
					kelvin   = kelvin - 1
				end
			
			end)

			domoticz.log('активирован режим "Рассвет"')
			
		elseif ( button.state == 'Double Click' ) then
		
			lamps.devices().forEach(function(lamp)
				lamp.cancelQueuedCommands()         -- отмену очереди команд нужно делать для каждого устройства отдельно
			end)
			lamps.switchOff().checkFirst() -- включить свет

		end

	end
	
}`

**Comment by rwaaren** [comment]
> Hi!
> Here is a problem.
> If we do setKelvin() in the loop, we can not stop this loop by cancelQueuedCommands() such, as with dimTo(), for example.
> 

As described in the wiki; method cancelQueuedCommands() method is only available for state changes, update commands and user variables.  setKelvin, setColor and the likes are implemented using an openURL call. These scheduled commands cannot be cancelled because there is no direct link to a device after scheduling the command.
