### ISSUE TITLE
Trouble with "double click" and "long click" (Xiaomi Wireless Single Wall Switch)

### ISSUE THREAD

**Issue by EvgenaNet** [domoticz/domoticz#3908]
Hello!
Domoticz doesn't recognize double click and long click action from Xiaomi Wireless Single Wall Switch (WXKG03LM). Only one click.

**Comment by gizmocuz** [comment]
@EvgenaNet , could you send me a PM on the Forum (gizmocuz) i would like to debug this
Probably this has to be added in the software
Do you see the status in the dashboard/widget changing ?

**Comment by EvgenaNet** [comment]
> @EvgenaNet , could you send me a PM on the Forum (gizmocuz) i would like to debug this
> Probably this has to be added in the software
> Do you see the status in the dashboard/widget changing ?

"PM" - what is this?
I did not understand questions about Statuses.

**Comment by gizmocuz** [comment]
@EvgenaNet , PM = Private Message, send me a private message on the forum

**Comment by EvgenaNet** [comment]
> @EvgenaNet , PM = Private Message, send me a private message on the forum

I can not register there...
"You have incorrectly sorted the items to the correct list of the confirmation question."
And such every time.

**Comment by EvgenaNet** [comment]
> @EvgenaNet , PM = Private Message, send me a private message on the forum

How i can register? What happened with registration? )))

**Comment by EvgenaNet** [comment]
> @EvgenaNet , PM = Private Message, send me a private message on the forum

Where i need to click to write you PM?

![Image of Yaktocat](https://raw.githubusercontent.com/EvgenaNet/images/master/!%20screenshot.jpg)

**Comment by EvgenaNet** [comment]
> @EvgenaNet , PM = Private Message, send me a private message on the forum

"We are sorry, but you are not authorised to use this feature. You may have just registered here and may need to participate more in discussions to be able to use this feature."

**Comment by gizmocuz** [comment]
@EvgenaNet ,
You should already have an account and have asked this question in the Forum
I have send you an email

**Comment by EvgenaNet** [comment]
> @EvgenaNet ,
> You should already have an account and have asked this question in the Forum
> I have send you an email

Next time i will be make as you said )
I have send you a reply.

**Comment by EvgenaNet** [comment]
> @EvgenaNet ,
> You should already have an account and have asked this question in the Forum
> I have send you an email

Hello! How are you? 
Every day i checking: was problem resolve or no... Still no.

**Comment by EvgenaNet** [comment]
> @EvgenaNet ,
> You should already have an account and have asked this question in the Forum
> I have send you an email

Hi!
See please: https://www.domoticz.com/forum/viewtopic.php?f=6&t=31421

**Comment by gizmocuz** [comment]
I send you a email in return, there are some problems with your system or the Xiaomi plugin.
But i do see the changes in the log correctly

![image](https://user-images.githubusercontent.com/2265299/75609722-46dedd00-5b0b-11ea-8a8a-3527dc38fd6e.png)

This is with the beta version.

**Comment by EvgenaNet** [comment]
Solution of this problem is here: https://github.com/domoticz/domoticz/pull/3962

**Comment by gizmocuz** [comment]
The issue was caused because the Selector switch did not have all levels (40,50,60,70,80 and 90 where missing)

**Comment by EvgenaNet** [comment]
> The issue was caused because the Selector switch did not have all levels (40,50,60,70,80 and 90 where missing)

Because the Selector switch have wrong levels ))
