### ISSUE TITLE
Update to most recent beta gives: mainworker.cpp error: conversion from ‘time_t {aka long int}’ to ‘Json::Value’

### ISSUE THREAD

**Issue by HoekieN** [domoticz/domoticz#3909]
I am trying to upgrade from current version:
Version: 4.11672
Build Hash: ba48297aa-modified
Compile Date: 2020-02-06 00:46:09
dzVents Version: 2.5.7
Python Version: 3.6.9 (default, Nov 7 2019, 10:44:02) [GCC 8.3.0]
To the latest beta and i am getting below error

ubuntu@ubuntu:~/dev-domoticz$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"

[ 29%] Building CXX object CMakeFiles/domoticz.dir/main/mainworker.cpp.o
/home/ubuntu/dev-domoticz/main/mainworker.cpp: In member function ‘void MainWorker::HandleAutomaticBackups()’:
/home/ubuntu/dev-domoticz/main/mainworker.cpp:1433:44: error: conversion from ‘time_t {aka long int}’ to ‘Json::Value’ is ambiguous
    backupInfo["duration"] = mytime(NULL) - now;
                                            ^~~
In file included from /home/ubuntu/dev-domoticz/main/../main/../json/reader.h:11:0,
                 from /home/ubuntu/dev-domoticz/main/../main/../json/json.h:11,
                 from /home/ubuntu/dev-domoticz/main/../main/json_helper.h:3,
                 from /home/ubuntu/dev-domoticz/main/mainworker.cpp:17:
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:326:3: note: candidate: Json::Value::Value(bool)
   Value(bool value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:304:3: note: candidate: Json::Value::Value(double)
   Value(double value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:302:3: note: candidate: Json::Value::Value(Json::Value::UInt64)
   Value(UInt64 value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:301:3: note: candidate: Json::Value::Value(Json::Value::Int64)
   Value(Int64 value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:299:3: note: candidate: Json::Value::Value(Json::Value::UInt)
   Value(UInt value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:298:3: note: candidate: Json::Value::Value(Json::Value::Int)
   Value(Int value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:334:10: note:   initializing argument 1 of ‘Json::Value& Json::Value::operator=(Json::Value&&)’
   Value& operator=(Value&& other);
          ^~~~~~~~
/home/ubuntu/dev-domoticz/main/mainworker.cpp:1460:44: error: conversion from ‘time_t {aka long int}’ to ‘Json::Value’ is ambiguous
    backupInfo["duration"] = mytime(NULL) - now;
                                            ^~~
In file included from /home/ubuntu/dev-domoticz/main/../main/../json/reader.h:11:0,
                 from /home/ubuntu/dev-domoticz/main/../main/../json/json.h:11,
                 from /home/ubuntu/dev-domoticz/main/../main/json_helper.h:3,
                 from /home/ubuntu/dev-domoticz/main/mainworker.cpp:17:
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:326:3: note: candidate: Json::Value::Value(bool)
   Value(bool value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:304:3: note: candidate: Json::Value::Value(double)
   Value(double value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:302:3: note: candidate: Json::Value::Value(Json::Value::UInt64)
   Value(UInt64 value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:301:3: note: candidate: Json::Value::Value(Json::Value::Int64)
   Value(Int64 value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:299:3: note: candidate: Json::Value::Value(Json::Value::UInt)
   Value(UInt value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:298:3: note: candidate: Json::Value::Value(Json::Value::Int)
   Value(Int value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:334:10: note:   initializing argument 1 of ‘Json::Value& Json::Value::operator=(Json::Value&&)’
   Value& operator=(Value&& other);
          ^~~~~~~~
/home/ubuntu/dev-domoticz/main/mainworker.cpp:1486:44: error: conversion from ‘time_t {aka long int}’ to ‘Json::Value’ is ambiguous
    backupInfo["duration"] = mytime(NULL) - now;
                                            ^~~
In file included from /home/ubuntu/dev-domoticz/main/../main/../json/reader.h:11:0,
                 from /home/ubuntu/dev-domoticz/main/../main/../json/json.h:11,
                 from /home/ubuntu/dev-domoticz/main/../main/json_helper.h:3,
                 from /home/ubuntu/dev-domoticz/main/mainworker.cpp:17:
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:326:3: note: candidate: Json::Value::Value(bool)
   Value(bool value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:304:3: note: candidate: Json::Value::Value(double)
   Value(double value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:302:3: note: candidate: Json::Value::Value(Json::Value::UInt64)
   Value(UInt64 value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:301:3: note: candidate: Json::Value::Value(Json::Value::Int64)
   Value(Int64 value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:299:3: note: candidate: Json::Value::Value(Json::Value::UInt)
   Value(UInt value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:298:3: note: candidate: Json::Value::Value(Json::Value::Int)
   Value(Int value);
   ^~~~~
/home/ubuntu/dev-domoticz/main/../main/../json/value.h:334:10: note:   initializing argument 1 of ‘Json::Value& Json::Value::operator=(Json::Value&&)’
   Value& operator=(Value&& other);
          ^~~~~~~~
CMakeFiles/domoticz.dir/build.make:296: recipe for target 'CMakeFiles/domoticz.dir/main/mainworker.cpp.o' failed
make[2]: *** [CMakeFiles/domoticz.dir/main/mainworker.cpp.o] Error 1
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
ubuntu@ubuntu:~/dev-domoticz$

**Comment by rwaaren** [comment]
Compiling latest Beta V4.11687  on Debian 
RPI-4 (Buster) RPI_3 (Buster) and Intel NUC (Buster) all without any problem.
RPI-3 stretch does show the issue as described by @HoekieN

**Comment by rwaaren** [comment]
@HoekieN can you please check if the quick fix (#3910) also solve your issue

**Comment by HoekieN** [comment]
Thanks for the quick fix, it works.
