### ISSUE TITLE
Month translation

### ISSUE THREAD

**Issue by gaudryc** [domoticz/domoticz#391]
Hi @gizmocuz !

Could you please add the following string to translation files ?
"May": "May"

Thanks in advance.

Regards,
Chris

**Comment by gizmocuz** [comment]
I see this already in the language files (i checked Dutch)

"May": "Mei",

**Comment by gizmocuz** [comment]
what do you miss ?

**Comment by gaudryc** [comment]
Yep, I'd missed something ;-)
I'm sorry for the inconvenience.
