### ISSUE TITLE
PVOutput limited API Calls

### ISSUE THREAD

**Issue by Pandabeer40** [domoticz/domoticz#3911]
I've seen this issue was closed end of 2018 - but nowadays it's back - for regular users op PVOutput - there is a limitation in API calls per hour

Please can you change the script to 6 times per hour - or let the user choose for standard PVoutput user (6 times per hour) or donator of PVOutput (60 times per hour)

Thank you in advance

> 2020-02-15 10:45:22.284 Error: PVOutput (Input): Error login!

It starts after 20 minutes in my case with Error Login in the Log File

**Comment by waltervl** [comment]
Still an issue?

**Comment by Pandabeer40** [comment]
Dear Walter, since 2021 I'm using Home Assistant - so this can be closed in my opinion
