### ISSUE TITLE
Problem with the plugin PanasonicTv => Flood logs

### ISSUE THREAD

**Issue by gmatta93** [domoticz/domoticz#3912]
Hi,

I've noticed a problem with the plugin PanasonicTV.
It seems that the PollIntervalsec setting is not taken into account.
No matter the setting I give, the plugin tries to handle the connection with my tv ang writes logs every 5 seconds.

Thank you for your help,
Guillaume

**Comment by gizmocuz** [comment]
Best to have a look in the code

void CPanasonicNode::Do_Work()

You could see why this happened... was an easy fix
