### ISSUE TITLE
New picker for adding devices to room plan doesn't show all available hardware devices. 

### ISSUE THREAD

**Issue by felix63** [domoticz/domoticz#3916]
Running Version: 4.11696 on Rasberry.

When trying to add new devices to an existing room plan the new picker (improvement) shows not all of my active hardware devices. It fails to the build-in 'Fritzbox' and 'Buienradar' hardware. As a result, I can not add devices from this hardware.
<img width="651" alt="Schermafbeelding 2020-02-17 om 00 35 19" src="https://user-images.githubusercontent.com/16501940/74615066-8fff5c00-511d-11ea-9be4-150732a247e7.png">
<img width="651" alt="Schermafbeelding 2020-02-17 om 00 34 36" src="https://user-images.githubusercontent.com/16501940/74615069-9261b600-511d-11ea-8545-ebc7a2cc99dd.png">

**Comment by gizmocuz** [comment]
If i look in your first screenshot, the hardware seems disabled (Fritzbox)
Do you have any devices for Buienradar ?

**Comment by felix63** [comment]
Yes, I have 15 devices for Buienradar. Fritzbox has 2. Enabling or disabling devices doesn't make any difference to which devices are shown in the picker. Also renaming the hardware doesn't make any difference.

**Comment by gizmocuz** [comment]
@felix63 , could you send me a PM on the Forum (gizmocuz)

**Comment by felix63** [comment]
done

**Comment by felix63** [comment]
My bad. Hardware didn't have any active devices..
