### ISSUE TITLE
Device page is reacting slow after PR #3914

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#3918]
Not sure if @stas-demydiuk gets notified about my remark on the closed #3914 
If it does I will close this issue 

Please see the discussion on the [forum](https://www.domoticz.com/forum/viewtopic.php?f=6&t=31379) about the behavior of the devices tab after #3914 
 
If an extra selection could be added to device tab (similar to the Used = (No / Yes) one ), to activate / deactivate it, I would see the real time updates on the devices tab as a welcome extra option. Especial together with the selections you can make on the left pane.
obviously the jumping back to page 1 should be prevented.

**Comment by stas-demydiuk** [comment]
Hi @rwaaren, thanks for reporting, will take a look!

**Comment by rwaaren** [comment]
I guess [issue #3922 ](https://github.com/domoticz/domoticz/issues/3922)  might also be related ?
