### ISSUE TITLE
Lua: s = uservariables_lastupdate['name'] return nothing

### ISSUE THREAD

**Issue by nesalkiN** [domoticz/domoticz#3919]
Running Domoticz on Docker and something broke in Lua in the latest builds.
On 4.11696 just now.

In Lua:
s = uservariables_lastupdate['name'] returns nothing now. Before, it returned date and time.

**Comment by nesalkiN** [comment]
Used the same script for years:

```
t1 = os.time()
s = uservariables_lastupdate['IVTData']
-- returns a date time like 2013-07-11 17:23:12

year = string.sub(s, 1, 4)
month = string.sub(s, 6, 7)
day = string.sub(s, 9, 10)
hour = string.sub(s, 12, 13)
minutes = string.sub(s, 15, 16)
seconds = string.sub(s, 18, 19)

commandArray = {}

print("IVTData last updated: " .. s .. " (" .. difference .. " seconds)." )

t2 = os.time{year=year, month=month, day=day, hour=hour, min=minutes, sec=seconds}
difference = (os.difftime (t1, t2))

if (difference > 300) then
	commandArray['SendNotification']='IVTData!#IVTData saknas sen mer än 5 minuter!'

end 

return commandArray
```

Error:

> 2020-02-17 16:32:00.479 Error: EventSystem: in IVT-data timer: [string "t1 = os.time() ..."]:5: bad argument #1 to 'sub' (string expected, got nil)

**Comment by MrHobbes74** [comment]
Thanks for the bugreport! Already found the issue, will file a PR tonight

**Comment by MrHobbes74** [comment]
Solution has merged today, issue should be solved. Can you check this? @NiklasOlofsson

**Comment by nesalkiN** [comment]
> Solution has merged today, issue should be solved. Can you check this? @NiklasOlofsson

Yep. Solved. Thanks!
