### ISSUE TITLE
devices deselected automatically

### ISSUE THREAD

**Issue by felix63** [domoticz/domoticz#3922]
Running Version: 4.11696 on Rasberry.

When selecting devices in the device list they get deselected automatically after a couple of seconds.

**Comment by rwaaren** [comment]
#3924 fixed it in such a way that now only devices that received a real time update while being selected are de-selected. Other selected devices will keep the select mark active. 
Can you check and when OK close this issue ?

**Comment by felix63** [comment]
Version: 4.11707 does resolve the problem of deselected devices. However when deleting or changing names of devices these updates are not shown unless the screen is refreshed.

**Comment by rwaaren** [comment]
> Version: 4.11707 does resolve the problem of deselected devices. However when deleting or changing names of devices these updates are not shown unless the screen is refreshed.

That should be fixed in later Beta's (> V4.11711)

**Comment by gizmocuz** [comment]
Solved
