### ISSUE TITLE
Domoticz reports no data available in database

### ISSUE THREAD

**Issue by olpayras** [domoticz/domoticz#3925]
In domoticz v4.10717 when a rfxcom bridge works with a temperature sensor which has no humidy sensor like TFA sensor for swimingpool, domoticz detect it as a temperature + humidity sensor. But that's not the trouble.

Troubles occur when you try to look at the reports. Reports are empty and domoticz indicate that's there's not data available in database. But there's data and graph is okay.

I thought trouble was because I merged DATA with an old oregon sensor, but no. In fact, i update all my humidy data with 100 value and reports are working fine now. But I think i will have to do it regulary because new values are at 0 for humidity data.

I dont know if this has been reported or if normal, but just tell you my experiance.

I think you can easily reproduce by putting all humidy data from a temperature+humidity sensor to 0.

Personnaly i reproduce it easily with this sensor :

`13 | RFXCOM | 0701 | 1 | Piscine | Temp + Humidity | Alecto WS1700 | 8.8 C, 0 %`

Thanks for reading my bad english.

Olivier.

**Comment by gizmocuz** [comment]
Thanks for reporting ! This also seems to happen in the beta version and is related to a javascript error in TemperatureReport.js:252

**Comment by gizmocuz** [comment]
Fixed in beta 4.11700

**Comment by olpayras** [comment]
Thank you so much for your fix. I'll try it in a further stable revision, but will try it first on a test computer.
