### ISSUE TITLE
Some missing devices when syncing with Remote Domoticz Server

### ISSUE THREAD

**Issue by Modjor** [domoticz/domoticz#3928]
Hello,
I'm bieleve the below is a bug - apologies if it's not (also posted under the Bugs and problems forum section.

**Environment:**
Version: 4.10717 (also tested with beta 411707 - same issue)
Platform: Master is Syno Docker x86, Slave/Remote is RPi3
Plugin/Hardware: rfxtrx433 usb / Orego 433 mhz Sensors / TIC Pulse 433mhz Elec meters / 433mhz light switch

**Steps to duplicate:**
1. Setup new vanilla domoticz RPi with rfxtrx (=> slave)
2. set a user password
3. wait for 433mhz sensors to show up in the devices list
4. add sensor to domoticz
5. setup a vanilla domoticz on the synology (=> Master)
6. On this Synology/Master, add a Domoticz Remote Server in Hardware (RPi/Slave)
7. Wait for the sensors to show up in the Master devices list

**Results:**
- 433mhz Light switches and Temperature/humidity sensors are showing up on Slave and Master (Oregon Scientific sensors mostly)
- 433 mhz Electric meters are NEVER showing up on the Master, they only appears on the Slave directely connected to the rfxtrx USB. Missing devices are properly appearing and getting updated on the Slave Domoticz as Usage/Electric, General/kwh and RFXMeter/RFXMeter counter.

**Expected Results:**
- All sensors shared on the Slave/Remote should appear on the Master when their status/value changes.

**Comment by pviolero** [comment]
I have a similar issue with some zigbee devices. It seems that the slave (where the zigbee devices are visible) don't send the devices to the master when they are managed through a python plugin.  On the same slave I have other devices (for example motherboard) that are correclty visible on the slave AND the master. The issue appear only for devices managed by python plugin.

**Comment by pipiche38** [comment]
check #2642

**Comment by Modjor** [comment]
Apologies never came back to update this ticket. Yes indeed it was related to some python code to support the device. I created a mirror device (keep it in sync using a dzevents script) and was able to replicate this new virtual device to the master domoticz.

**Comment by gizmocuz** [comment]
Please check beta 15790 ... Both client/server need to run on this beta... quite some things have changed.
You probably will get new devices, so make sure 'Accept new hardware/devices' is enabled in the settings
