### ISSUE TITLE
Websocket requests very slow

### ISSUE THREAD

**Issue by bizziebis** [domoticz/domoticz#3937]
Domoticz Version: 4.11711

I noticed that after some of the last commits, the response time to a request trough websocket is very high. Somewhere around 20 to 40 seconds for each request. This is most noticable when you edit a device, edit timers, edit notifications or show the log of the device.

When running Chrome DevTools and focussing on the websocket messages, I see 2 ~ 5 messages each second of updated devices. That's expected in my system. 

When I run the stalled requests as a JSON URL request in the browser, I gat an instant reply.

2 tries to edit 2 different devices:
Device 1:

```
event: "request"
requestid: 13
query: "type=devices&filter=light&used=true&order=[Order]&lastupdate=1582233425&plan=0"
```
6 seconds

```
event: "request"
requestid: 14
query: "rid=6093&type=devices"
```
0.2 seconds

```
event: "request"
requestid: 15
query: "param=getlightswitches&type=command"
```
0.2 seconds

```
event: "request"
requestid: 16
query: "idx=6093&param=getsubdevices&type=command"
```
20 seconds

```
event: "request"
requestid: 17
query: "type=custom_light_icons"
```
40 seconds

----------
Device 2
```
event: "request"
requestid: 19
query: "rid=3536&type=devices"
```
0.2 seconds

```
event: "request"
requestid: 20
query: "param=getlightswitches&type=command"
```
0.3 seconds

```
event: "request"
requestid: 21
query: "idx=3536&param=getsubdevices&type=command"
```
20 seconds

```
event: "request"
requestid: 22
query: "type=custom_light_icons"
```
40 seconds

I'm running Domoticz in a Linux VM (Buster) on an i5 CPU. Avarage CPU load is 2%. No spikes during requests.

**Comment by gizmocuz** [comment]
Same issue here. For example when I go to the notifications of a switch it takes 20 seconds for the list to fill

**Comment by stas-demydiuk** [comment]
@gizmocuz any ideas why does server response so long for some websocket requests comparing to http ones?

**Comment by gizmocuz** [comment]
@stas-demydiuk , no sorry, i also have to dig into this one. Maybe it is the canceling of the websocket when you go to the edit/notification/other page
I hope to have a look at this tomorrow unless someone beats me to it

**Comment by stas-demydiuk** [comment]
We could always revert `www/app/domoticz.api.js` to use http instead of websockets as a transport, but I would prefer us to try fixing websockets first as it decreases latency between UI and backend because of no need to create new http connection (handshake and such stuff)

**Comment by gizmocuz** [comment]
@stas-demydiuk , sorry, yes please revert this change (domoticz.api.js to http) as i can now also not see where things go wrong, which url's are called etc.
Makes it also difficult for feature developers to quickly see which API/JSON call was called.
There are also other things that go wrong now, like when you click on a temperature sensors log button, there is no year log, report does not work etc...
(Okey it is working, but takes 20 seconds, the day/month is instant)

**Comment by gaeljw** [comment]
I could not even load Domoticz at all due do this change (or after few minutes only..). Glad to see it rollbacked for now :)
