### ISSUE TITLE
Option Pulse for Relay GPIO

### ISSUE THREAD

**Issue by pp1984** [domoticz/domoticz#394]
Hi
I have one question. Is any chance to add to Domoticz option to set PULSE for Relay which i use by GPIO? I want use it to my SOMFY Blinds connect to remote TELIS4 RTS. And when i on relay it takes too long PULS and blinds not close or open. Blinds in affect change position step by step. I need set short time to relay. I set by event that when relay is ON ith should OFF by 0.2secunds but i hear that sometime PULS on relay is long somteimes is short. And when is short is ok and Blinds open and close very good ok.

Please need help.

**Comment by pepijng** [comment]
Why are you posting this here? This kind of issues need to be discussed on the forum and you, PepeEL already created a topic.
