### ISSUE TITLE
New OTGW devices

### ISSUE THREAD

**Issue by svkeulen** [domoticz/domoticz#3943]
There are OpenTherm GateWays that output a different format over serial. See the post:
https://domoticz.com/forum/viewtopic.php?f=26&t=23042
A time ago I wrote code that I am still using today (https://domoticz.com/forum/viewtopic.php?f=26&t=23042&start=20#p181457). 

Recently some other user was asking on the forum if the code ended up in the main developers branch. I replied that I will contact the developers about this.

Maybe it is a wise idea to add an extra device to the list. I don't know if there are any users using the current OTGW source.

**Comment by gizmocuz** [comment]
@svkeulen , thanks for the post and links!
Yes I am using the current OTGW implementation, and i think some other users as well.
The reason why the new code (your code) is not being added to the development branch is that I haven't seen a Git Pull Request for this ...
Could you make a PR ? Then we can also see the changes
Do the old OTGW hardware devices still work with your code ? Or is it a matter of upgrading the OTGW firmware ?

**Comment by svkeulen** [comment]
Old hardware doesn't work with my code. I think it has to do with the firmware version. I'm running version 4.2.5. The code changed quite a lot since the output differs a lot. I will make a PR

**Comment by gizmocuz** [comment]
This was not a bug
