### ISSUE TITLE
Error: SQL Query("VACUUM") : database or disk is full

### ISSUE THREAD

**Issue by berbergh** [domoticz/domoticz#3957]
### Issue Guidelines
A couple of days ago, I made a fresh SD with the Buster Lite release of Raspian, in order to keep up with the beta releases.
On top of that, I did easy Domoticz setup, as per curl -L https://install.domoticz.com | bash

There where some issues, because I had a funny screen when the stable release of domoticz started. After ./updatebeta, I got normal screens.

Now, every hour, I see stuff like this:
2020-02-26 19:18:41.543 Error: SQL Query("VACUUM") : database or disk is full
2020-02-26 20:00:04.228 Status: Starting automatic database backup procedure...
2020-02-26 20:00:04.521 Error: SQL Query("VACUUM") : database or disk is full
2020-02-26 20:00:07.684 Status: Ending automatic database backup procedure... 

Manual database backup works fine.

Domoticz release is 11748
This is my OS:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by gizmocuz** [comment]
could you check your filesystem for enough disk space ?
Do you have automatic database backup enabled ? If yes, disable this
If you open the database with a program like "SQLite Personal Edition' and check your database, do you have any errors ?

**Comment by gizmocuz** [comment]
Did you use the forums search function ?
https://www.domoticz.com/forum/viewtopic.php?t=26509

best to use the forum
