### ISSUE TITLE
Wrong switch states on floorplan after set scene

### ISSUE THREAD

**Issue by raaq1911** [domoticz/domoticz#3958]
Hello

I have a problem with wrong switch states on floorplan after set scene. When I turn on a scene which set OFF to all switches, on floor plan all switches type on/off turned on. At the same time in "switches" tab is allright (switches have real states). When I want to ON switch in floor plan, I must click to turn off swich (it's only changes state to off in floor plan), and second time click to turn on. This issue absent with diffrent type of switches (f.e. dimmer). 

RGDS

**Comment by gizmocuz** [comment]
That is because a scene can have a mixed state if you turn on/off devices in a scene
How does it look on the Scene tab ?

**Comment by raaq1911** [comment]
I have a mixed state in scene, but when I click on scene which turn off all, this problem still occurs.
Scene tabs: https://tinypic.pl/65cpqrcnfiqu
Scene "wyłącz wszystko": https://tinypic.pl/vm9q3w1ihf9z

**Comment by gizmocuz** [comment]
What happens when you refresh your browser in the floorplan view ?
(Sorry i do not use/have floorplans so it is hard to test), could you also post a screenshot from the floorplan where it goes wrong ?

**Comment by raaq1911** [comment]
Before  click a scene, one part of swithces are on, second part are off, after click scene (scene turn off all) floorplan looks like this: https://tinypic.pl/8exf5qdkb3i5 but in Switches tab, ALL is OFF state.

**Comment by gizmocuz** [comment]
What happens when you refresh the browser (function key F5), maybe the floorplan needs to refresh when you click a switch/scene

**Comment by raaq1911** [comment]
Nothing happens. Floorplan is refreshed and have all switchs state on. Please note that this does not apply to other types of switches, only type on/off (dimmer or mi lamp works fine).

**Comment by raaq1911** [comment]
Additionally, this same problem occurs in switch tab in Domoticz Lite (on android). After set scene to turn off all, in Domoticz Liite on Andoid I see all switches type on/off is state on.

**Comment by gizmocuz** [comment]
@raaq1911 , I added 5 dummy switches and put them on, put them in a scene, added a floorplan, put everything in the floorplan.
Activated the Scene, all lights are off as expected
I played a bit, and all is working correctly.

You are on one of the latest beta versions i suppose ?

**Comment by raaq1911** [comment]
Tested on stable and beta version.
OK, I tried a dummy switches - works fine. So problem is only with switches type on/off which communicate via mqtt and device is shelly 2.5. Shelly RGBW works fine.

**Comment by gizmocuz** [comment]
Okey maybe not a Domoticz issue then ?
How have you configured the Shelly 2.5 with MQTT ?

**Comment by raaq1911** [comment]
I'm not sure, but communicate is OK.
Here my settings: https://tinypic.pl/qusl34kljdoc
and in Domoticz: https://tinypic.pl/be1kl36krfiv

It's works fine, except status in floorplan after set scene :(

**Comment by gizmocuz** [comment]
Best to ask discuss this problem with the maker of the Shelly MQTT plugin on the Forum.
This does not seem to be a Domoticz issue and therefor i will close this issue.
If after discussion it is a Domoticz issue, please feel free to re-open this again
