### ISSUE TITLE
Cannot delete Devices in Device List  

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#3965]
I just updated to V4.11774 on my Win10 installed Domoticz. 

Then I checkbox'ed some unwanted RFXCom added Devices and pushed trashcan to delete from list, but they are still in the list... I also tried to select only one at the time but still not deleted.

**Comment by rwaaren** [comment]
Just tried to replicate but devices are deleted in my windows 10 setup (V4.11774) .
Please clear cache / appcache and check logfiles for any relevant messages
If devices are still in the list you could try to restart domoticz and check if devices are removed from the list.

**Comment by RicardP** [comment]
Hi @rwaaren  Just tried again this morning and without doing anything, except waiting, it now worked,. Yesterday I tried both Firefox and Edge-Chromium without success… Strange browser cache issues, as “always”!

Thanks, closing it.
