### ISSUE TITLE
ZWAVE not reporting all Battery Values

### ISSUE THREAD

**Issue by sincze** [domoticz/domoticz#3969]
Domoticz V4.11662

It seems not all ZWAVE doorsensors battery information come through in Domoticz. However it is available in the zwave control panel. 

![image](https://user-images.githubusercontent.com/5776333/76146410-ce3fc980-6092-11ea-851d-a9f035b7bbad.png)

![image](https://user-images.githubusercontent.com/5776333/76146573-304cfe80-6094-11ea-9cca-82a348e8ac92.png)

What did I miss here?

**Comment by gizmocuz** [comment]
@sincze , that is because at startup it probably takes it from the cache file
When the device 'transmits' the battery status, 'then' it is available in Domoticz

**Comment by sincze** [comment]
Quickest way to test this would be ... backup the cache and have the network rebuild itself?
Or other safe solution that can be done to test this?

**Comment by gizmocuz** [comment]
Yes that is a quick way, the other is just to have a look in the code and you can see that we store battery values when we receive it
What happens when you wait a day or use them? Do they show up ? Most nodes transmits at least once a day, or when you operate them.

**Comment by sincze** [comment]
![image](https://user-images.githubusercontent.com/5776333/77357006-b41b1200-6d47-11ea-86c0-b0534adcfd51.png)

haha indeed after installing 2020.1 I now have more battey values. Did not dare to remove the cache. Simple update solved a lot so I guess the cache is the culprit indeed not Domoticz.

**Comment by gizmocuz** [comment]
Domoticz does not use the values from the cache. It updates the battery values when the node is sending it
So at startup you might not have battery values, but over time you will.

**Comment by AlexF12004Roma** [comment]
With the latest beta i noticed a problem with battery level on AEON devices.
All battery levels to zero even if it's not true.

![image](https://user-images.githubusercontent.com/6578842/79108742-43c84500-7d77-11ea-8ec0-98337576b5e0.png)

**Comment by darkrain-nl** [comment]
> 
> 
> With the latest beta i noticed a problem with battery level on AEON devices.
> All battery levels to zero even if it's not true.
> 
> ![image](https://user-images.githubusercontent.com/6578842/79108742-43c84500-7d77-11ea-8ec0-98337576b5e0.png)

I think this is the same as in https://github.com/domoticz/domoticz/issues/3815
