### ISSUE TITLE
FGWPF-102 Gen5 plug missing lifeline group after upgrade to 4.11776

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3970]
installed 4.11776 
i noticed my fgd212 dimmer is behaving strange.

lights are flickering
did a recalibration but the issue stays.

my old range after callibration wa 10-58%
now it it 29-69%.
also can not dimmer to  a low level

decided to roll back to 4.11744 and all seems to function again.

did we chasnge anything regarding the fgd212 or on a zwave level?

**Comment by rwaaren** [comment]
You can see recent commits either [here](https://github.com/domoticz/domoticz/commits/development) or on this [wiki page](https://www.domoticz.com/wiki/Domoticz_versions_-_Commits)

**Comment by GravityRZ** [comment]
yes, i do not see anything which would cause this (with my limited code knowledge)
let's wait to see if other people experiencing this also

**Comment by GravityRZ** [comment]
had some time today to do the upgrade again.
now it seems to work without problems

**Comment by gizmocuz** [comment]
I upgraded the openzwave library... But great it's working again!

**Comment by GravityRZ** [comment]
hmm. spoke to soon.

i decided to delete the cache file to check if everything is recognized again.
all the devices come backu up but when i look at the groups i have problems with the FGWPF-101 Gen5 device.
it fails to add 1 or 1.1 to group 1
whatever ui do(refresh node, disable/enable zwave) i can not get it to add 1 or 1.1 to group 1 anymore

devices seem to work but if 1 is not in group 1(this can cause problems)
any idea how this is related.
what can i do to get the groups back(did refresh node in domoticz and in zwave panel)

![image](https://user-images.githubusercontent.com/16853535/76229079-f4e03a80-6221-11ea-9c4d-2a3bbe0a7dea.png)

**Comment by GravityRZ** [comment]
restoring the original file instantly restores the groups
perhaps i need to mention this on the openzwave forum
![image](https://user-images.githubusercontent.com/16853535/76233685-d6ca0880-6228-11ea-9b4d-38bcf6426594.png)

**Comment by GravityRZ** [comment]
this entry seems to be missing in the new cache file (and perhaps the config file

```
> <CommandClass id="96" name="COMMAND_CLASS_MULTI_INSTANCE/CHANNEL">
>                 <Compatibility />
>                 <State />
>             </CommandClass>
```

**Comment by GravityRZ** [comment]
moved this to the openzwave github
