### ISSUE TITLE
Trouble with beta version 4.11777 and Tasmota?

### ISSUE THREAD

**Issue by gajotnt** [domoticz/domoticz#3971]
After updating to beta version 4.11777, my tasmota flashed devices stoped interaction with domoticz, but i can interact with the devices if using the domoticz app/web page.

So from the webpage/app i can turn the devices on/off and they work as expected. But if i go to the devices and turn them on/off nothing will change with domoticz.

Utilities and temperature sensors are still updated in domoticz. So at least that is working well.

https://www.domoticz.com/forum/viewtopic.php?f=6&t=31617&p=239066

When i physicly change the switch it sends this command:

13:42:58 MQT: domoticz/in = {"idx":92,"nvalue":1,"svalue":"","Battery":100,"RSSI":10}
13:42:58 MQT: stat/HallSala/RESULT = {"POWER2":"ON"}
13:42:58 MQT: stat/HallSala/POWER2 = ON

**Comment by gajotnt** [comment]
Version 4.11780, still same problem.

https://www.domoticz.com/forum/viewtopic.php?f=6&t=31617&p=239273

**Comment by gajotnt** [comment]
Domoticz receives the MQTT message...

2020-03-10 23:11:49.369 MQTT: Topic: domoticz/in, Message: {"idx":92,"nvalue":1,"svalue":"","Battery":100,"RSSI":9}

Dont understand why nothing happens in domoticz

![domo](https://user-images.githubusercontent.com/25504364/76369945-ce56f800-6324-11ea-8101-7b4383344a7f.PNG)
![tasmo](https://user-images.githubusercontent.com/25504364/76369964-e62e7c00-6324-11ea-899f-3c3d441c8683.PNG)

**Comment by gizmocuz** [comment]
It might be related to the latest changes in MQTT to prevent an endless loop

https://github.com/domoticz/domoticz/commits/development/hardware/MQTT.cpp

But if you say everything except the switch is working, I am not sure it is related to this change

**Comment by gajotnt** [comment]
Indeed this is strange, domoticz receives the information, but in the case of the switchs it doesnt change the state and therefore doesnt apply any automations :-/ but if working from domoticz app everything works has expected.

Temperature and utility are all working has expected, domoticz receives the info and processes it.

**Comment by gizmocuz** [comment]
Could you test this with a Dummy Switch, A new test event that logs something based on the state (On/Off) and via the mosquitto_pub console application?

**Comment by gajotnt** [comment]
Not that tech savy, but will try to figure out how to do that.

**Comment by gajotnt** [comment]
Is that what you asked for? :/ 

![test](https://user-images.githubusercontent.com/25504364/76456976-77eec580-63c7-11ea-8e7f-803586f1f97b.PNG)

**Comment by gajotnt** [comment]
took some time to do some testing, domoticz is registring the switch turning on or off, but is not relaying the information to other devices that have the same idx

![tasmotalog](https://user-images.githubusercontent.com/25504364/76469047-fc980e80-63dc-11ea-8d6c-4759f2beee32.png)

**Comment by gizmocuz** [comment]
It is correct that Domoticz does not transmit the device to MQTT again if that is what you mean
So when a MQTT In message is received , the update/change is NOT send to MQTT/Out
This was causing an endless loop, see the link of my second reply
If that is not what you mean, what do you mean with "Other device"

**Comment by gajotnt** [comment]
For example, i have a sonoff touch on my 1st floor (idx92) that turns on/off a sonoff basic thats on the second floor (with the same idx), i have several devices connected like this, maybe i should not do it like this, but it always worked so... xD
So i have to create dummy devices for each individual sonoff and then create rules or slave/sub devices?

**Comment by gizmocuz** [comment]
Yes or you could use a scene/group and learn that dummy switch as activation code

**Comment by gajotnt** [comment]
Ok thanks, will do that then. Was so easy the other way, but it is what it is. Thanks for your patience.

**Comment by gajotnt** [comment]
Sorry for bothering you again. Is there anyway i can revert back several beta builds before that commit to mqtt? 

Cant get this working and the wife if giving me a tough time.

**Comment by rwaaren** [comment]
If you have a backup with Version V4.11762 or earlier but not earlier as V4.11650 yes

**Comment by gajotnt** [comment]
Dont have any backup of those versions  :( shame :(

**Comment by rwaaren** [comment]
Send me a dm on the forum (waaren) and include your hardware and OS version  and maybe I can help.

**Comment by gajotnt** [comment]
done

**Comment by Masurov** [comment]
I was using the same technique as gajotnt to implement a "two way" switch with two tasmota devices.
  
A single dummy switch device on Domoticz side et shared idx on both tasmota devices configuration. Both tasmota switches were synced and I had a single light switch showing the light status on Domoticz. This was very convenient and running fine until the I updated to Domoticz 2020.2.

A group cannot be used because Tasmota does not work with a group idx, only switch idx. And because modifying the state of a switch in the group, does not change the whole state, this is a not a solution to have a 2 way switch behaviour.

You have to create a dummy for each switch instead of a single one. Then I used dzVents to sync 2 (or more switches). Here is the script if it can help someone 👍 
```
syncedDevices = {'Entrée', 'Entrée (bis)'} -- list the devices you want to sync
return {
    on = {
        devices = syncedDevices
    },
    execute = function(domoticz, device)
        
        for _, toSync in ipairs(syncedDevices) do
            if (device.name ~= toSync and domoticz.devices(toSync).state ~= device.state) then
                domoticz.devices(toSync).setState(device.state)
            end
        end
    end
}
```
