### ISSUE TITLE
Signal 11 on Plugin_ASIO

### ISSUE THREAD

**Issue by heggink** [domoticz/domoticz#3979]
Every couple of days (5 days typically), my domoticz crashes with segmentation fault as per the below. Any idea what Plugin_ASIO does and how to debug/resolve?
OS: Buster
Domoticz version 4.11740. 
Outside of this, domoticz is really stable and memory consumption is more stable then I have ever seen so great improvements.

Mar 11 18:46:57 domoticz domoticz: (P1) P1 Smart Meter (Electra)
Mar 11 18:47:05 domoticz domoticz: Domoticz(pid:485, tid:525('Plugin_ASIO')) received fatal signal 11 (Segmentation fault)
Mar 11 18:47:05 domoticz domoticz: siginfo address=0x1e5, address=0x76de4b1d
Mar 11 18:47:13 domoticz domoticz: (P1) P1 Smart Meter (Electra)
Mar 11 18:47:13 domoticz domoticz: Thread 25 (Thread 0x687f8220 (LWP 525)):
Mar 11 18:47:13 domoticz domoticz: #0  0x76c9938c in __waitpid (options=0, stat_loc=0x687f71e0, pid=9641) at ../sysdeps/unix/sysv/linux/waitpid.c:30
Mar 11 18:47:13 domoticz domoticz: #1  0x76c9938c in __waitpid (pid=9641, stat_loc=0x687f71e0, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
Mar 11 18:47:13 domoticz domoticz: #2  0x002daec4 in dumpstack_gdb(bool) ()
Mar 11 18:47:13 domoticz domoticz: #3  0x002db490 in signal_handler(int, siginfo_t*, void*) ()
Mar 11 18:47:13 domoticz domoticz: #4  0x76a96130 in <signal handler called> () at ../sysdeps/unix/sysv/linux/arm/sigrestorer.S
Mar 11 18:47:13 domoticz domoticz: #5  0x59ded788 in  ()
Mar 11 18:47:13 domoticz domoticz: #6  0x76de4b1c in  () at /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1

**Comment by lokonli** [comment]
Was this solved? I see the same.

**Comment by heggink** [comment]
No. It still happens occasionally. I never understood it by looking at the code. It's as if this is the base plugin name allocation before it gets assigned it's real name ie some kind of weird bug. It largely started to happen with the slide plugin. I cleaned up a bunch of old plugins (primarily dummy stuff) that made it go away for a while but sometimes it's back. Then I fiddle again (disable plugin, enable it). That mostly works. It looks like an obscure bug in the python framework that I thought only I had...

**Comment by heggink** [comment]
Reopened as still there and confirmed by others.

**Comment by heggink** [comment]
Closed again as seems to be related to the resilience of the python plugin system. Found a way to prevent it.
