### ISSUE TITLE
Partially lost contact with z-wave node range since two days (beta V4.11782)

### ISSUE THREAD

**Issue by Sarcas666** [domoticz/domoticz#3982]
V4.11782
Build Hash: f88d21a1a
Build Date: 2020-03-13 07:48:54
on Raspi3 Buster

hardware : rfxcom usb, zwave usb, 

Since two days I seem have at least partly lost communications with nodes 002 - 011. 
The is no configuration when I select those nodes in the 'Device zwave usb' screen. Node 001 doesn't work though. Node 002 still sends info (temperature, movements, lux) but node 003 is silent (battery is fine). The other nodes are smoke/CO sensors. They are still reporting temperatures. 

There are no errors in the logs.

Not sure what to do next. 

<img width="1178" alt="Schermafbeelding 1" src="https://user-images.githubusercontent.com/970974/76679005-04be9c80-65dd-11ea-872c-565e1292c471.png">

<img width="1616" alt="Schermafbeelding 2" src="https://user-images.githubusercontent.com/970974/76679091-e60cd580-65dd-11ea-9586-ed27a91a794c.png">

**Comment by gizmocuz** [comment]
Have you just upgraded to the beta version ?
Select a node that has ID/Type of 0x0000, use the button 'Refresh Node Info', you might need to wake up the node to let it send the node information.

**Comment by MarcusKlerks** [comment]
I'm meeting the same problem: updating to v4.11784 made me lose all info on battery operated nodes. Thinking that was an incident I did wake op all nodes to retrieve the info. After that all worked well again. Today I updated to v4.11786 and again got the same problem: lose info on all battery operated nodes. Since wake up all these nodes manually involvels a lot of work I decided to revert to v4.11784 which solved my problem for now but makes it difficult to keep up with beta versions.
My system is Rasberry Pi3, Razberry (old) running Buster.

**Comment by gizmocuz** [comment]
@MarcusKlerks , also here try the above steps to refresh the node information

**Comment by Sarcas666** [comment]
Refreshing and patience brought most of them back. Not all battery info is updated, but data is being send.

**Comment by MarcusKlerks** [comment]
@gizmocuz , I did refresh nodes/wake up nodes updating to v4.11784 as mentioned above. But I get the same problem (losing node info) when updating from v4.11784 to v4.11786. The problem exists on battery operated nodes (fibaro, neo coolcam, heiman). Let me know what I can do to tackle this problem.

**Comment by MarcusKlerks** [comment]
It's getting frustating: Updating from v4.11786 (all nodes present) to v4.11794 gave the same problem: battery operated nodes losing info. After refreshing the node info all worked well again. Until upgrading from v4.11794 to v4.11799 where the problem still shows. After upgrading the log shows 'New node added...' for all the battery nodes and node info is gone.
I'm going to refresh again but it would be very welcome if the problem can be solved.
Just noticed that the same thing happens when domoticz service is restarted. What can be broken?

**Comment by dobber81** [comment]
I have the same problem as described above. However, not all battery devices are affected. My "Vision" units and "Heimann" smoke alarms keep their settings and info. Coolcam units need to be refreshed, and also a few non-battery units that soon after boot are refreshed.

**Comment by gizmocuz** [comment]
@dobber81 , at least state your platform/version as there have been recent changes

**Comment by dobber81** [comment]
Sorry about that!
I'm on Raspberry pi 4 2gb. Buster. Build 11835. Noticed the same issues over the last 5 builds at least.
I do not compile by myself. I use the update function in Domoticz.

At every boot or process restart I loose info on a few units. Always the same ones. The non-battery units get the info back a few minutes after domoticz is back online. 3 PIR sensors, all from shenzen/neo need to be refreshed manually, or wait until they wake up after a few hours, to get the configuration info back. They all show ID 0x0000 during that time.

**Comment by gizmocuz** [comment]
@dobber81 , and when you select such node, and press on the 'Refresh Node Information' button ?
You might have to wake-up the node, specially when it is a battery node before doing so...
Try it with one first

**Comment by MarcusKlerks** [comment]
@gizmocuz , Refresh Node Information/Wake-up certaily works bur doesn't solve the problem since new updates/restart domoticz still leads to loss of node information. Log showing 'New node added...' for the nodes that lost information. Today i upgraded to v2020.1 but the problem still exists.
No idea what could be the cause or where to look?

**Comment by dobber81** [comment]
As MarcusKlerks noticed refresh helps, and the node is recognized again. But I don't want to manually refresh a bunch of battery nodes every time a I reboot the machine/update domoticz to new version.
I have the timeout set to 6 hours on most of my battery nodes. In theory it could be up to 6 hours from my reboot until my PIR devices register motion to my alarm system.
Most of my battery units are remembered during a reboot. But a bunch of devices are "lost" and needs to be recognized again. Either by refresh-by-timer or manually refreshed.

**Comment by sincze** [comment]
I do recognize the NEO behaviour guys.
Very frustrating that I need to climb a ladder remove the cover and press the button on the device with plenty of nodes... It is frustrating. 
![image](https://user-images.githubusercontent.com/5776333/77357395-5b984480-6d48-11ea-82ba-5e731e28eeea.png)

But I updated to 2020.1 on a Pi3 and no issues. So I was very happy.

**Comment by dobber81** [comment]
Sorry to say that 2020.1 (11835) does not solve the issue here. Just tried a reboot and ended up with my neo PIR's 0x0000.

**Comment by gizmocuz** [comment]
@dobber81 , there have been no changes regarding openzwave in the beta versions, you can see this in the commit history

It looks like the node information is not written in the cache file, could you have a look in the Config folder, there is a file called 'zwcfg_xxxx.xml'
When you go to Hardware/OpenZWave and from the dropdown choose 'Control Panel' does the Status of these nodes say 'Ready' ?
For now, please do not update/restart

**Comment by Sarcas666** [comment]
> Sorry to say that 2020.1 (11835) does not solve the issue here. Just tried a reboot and ended up with my neo PIR's 0x0000.

Same here. Running the latest version, neo stays at 0x0000.

**Comment by sincze** [comment]
If no changes in zwave I would say I'm lucky for a change. Have had my share of zwave problems.
For now, please do not update/restart`
Running the latest betas can result in some **signal** errors so the restart was out of my hands ;-) the monitor would kick in and restart Domoticz for me. 
- domoticz-server-v4.11662.tar occasional restart
- domoticz-server-v4.11807.tar have had no issues
- 2020.1  up for 1d 17h 41m

Zwave seems to be rather strange. 
Top floor is running Xiaomi sensors, without issues but that is a side node completely off-topic.

**Comment by dobber81** [comment]
The node is definitely in the ozwcache-file. Easy to find, with all its current values.
Not an sd/ssd error either. Tried this setup both on SSD and iscsi to nas.
After a reboot status is "Sleeping". Until I either wait up to 6 hours, or manually trigger a wakeup by button and the node is updated again. Between reboot and refreshed status is 0x0000 in domoticz and Sleeping in control panel.

**Comment by RicardP** [comment]
I have less and less issues with ZWave over time as OZW 1.6 today is a lot improved.
I have some issues with Fibaro and Qubino nodes being buggy over time (power cycle fix them for some weeks).
I would say ZWave related issues already seen at ozw-cpl is not caused by Domoticz, it is a local system issue or you should report it at https://www.openzwave.com/

**Comment by MarcusKlerks** [comment]
Updated to build 11835 having the same problem. Nodes with missing info are NOT present in ozwcache_xxxx.xml (zwcfg_xxxx.xml was used prior to OZW1.6?) until node info is refreshed. Status in OZW Control Panel is 'Probe (sleeping)'.
Has there been a ZWave update that is the cause of this problem?

**Comment by gizmocuz** [comment]
@MarcusKlerks , and you selected that node, wake-up the node (by pressing the button) and selecting 'Refresh Node Info' in the user interface ?
Then after waiting a minute, you pressed 'Refresh' to see if that has been received ?
If not, wake up the node again

And as you can read, we updated OZW to 1.6

**Comment by MarcusKlerks** [comment]
@gizmocuz , yes I did/do all that and then the node info is back. The problem is that it has to be done after every update/restart of domoticz which is at least very annoying.
And yes, I know we are on OZW1.6 since a long time. After update to 1.6 node refresh was also necessary but since that time everything worked just fine until a few updates back.

**Comment by gizmocuz** [comment]
@MarcusKlerks , Domoticz is linked directly to the latest (master) code from OpenZWave.
It seems that those nodes you have problems with are being queried for something and that the node does not give the result back
You could enable the debug log ? Select node 1 (the controller) and enable the debug log, and press 'Apply configuration'
Now OpenZWave will restart, and then when it goes wrong, have a look in the log file
(Better copy the log file to a safe place first)
Do not forget to disable the debug log as it can become quite big!

**Comment by MarcusKlerks** [comment]
Ok done so, I think the problem is logged as:
![image](https://user-images.githubusercontent.com/6135524/77544890-ef355680-6ea9-11ea-9034-63b3b96bf44b.png)
The lines with 'Skipping Cache Save...' are exactly the nodes missing info after restart.

**Comment by gizmocuz** [comment]
Could you report this to OpenZWave ?

**Comment by MarcusKlerks** [comment]
I have reported it to the OZW forum.

**Comment by gizmocuz** [comment]
Thanks, please report the progress

**Comment by iassenk** [comment]
Same issues on raspbian pi3 buster, latest build 11836.
I think commit  2948df585b412f9abcb62bb7cad817e071c5260e is the beginning of the endless OZW "brain damage" Could you revert this until OZW community find a solution?

**Comment by gizmocuz** [comment]
@iassenk , I am sorry that is not that easy. Let's hope the OZW community finds a solution

**Comment by RicardP** [comment]
@MarcusKlerks I just visited OZW but I could not find you posted it under Issues tab? Sorry, asking just to be sure we get attention to this :)

**Comment by MarcusKlerks** [comment]
Reported in the OZW forum: https://groups.google.com/forum/#!topic/openzwave/PbeVho2Z-4Q

A (first) answer from Justin Hammond:

> This is how 1.6 works now to avoid cache corruption bug that was present in 1.4
Once the device wakes up, and is fully discovered, it will be saved to the cache. 

This cannot be true imho: an unplanned restart of the system would cause all automation, safety and security sensors not to be working until they reported after wake-up. Do we have to minimize the wake-up interval to minutes thereby exhausting batteries?

**Comment by gizmocuz** [comment]
@MarcusKlerks , surely when the device is fully discovered, it's configuration is saved in the cache
and the cache is used on startup, but i think you might have another issue, as mentioned above, it could be that OZW is requesting a specific command class value, and the node does not answer/supply it, and it keeps waiting for it
This you should be able to see when you enable the debug logging see above, there should be some timeout messages maybe

**Comment by MarcusKlerks** [comment]
@gizmocuz , maybe you can help me by analyzing the attached log file. When I look at e.g. node006 (Fibaro motion) it get initially the requested response but in the end it is not added to the cache.
[OZW_Log.txt](https://github.com/domoticz/domoticz/files/4387187/OZW_Log.txt)

**Comment by gizmocuz** [comment]
@MarcusKlerks , the log says

> 2020-03-25 14:58:22.646 Info, Node006, Skipping Cache Save for Node 6 as its not past QueryStage_CacheLoad

This is a message from the OZW Driver, and i assume in the control panel the node still indicates 'sleeping' as it is a battery node

I assume the node is working correctly ?

**Comment by MarcusKlerks** [comment]
When the node is not ready the staus in Control Panel is 'Probe (sleeping)', when after a wake-up the node info is retrieved the status is 'Sleeping'. After that the sensor works correct.

**Comment by MarcusKlerks** [comment]
Can be closed (see #4119)
