### ISSUE TITLE
missing add/remove device after #3978

### ISSUE THREAD

**Issue by kovainfo** [domoticz/domoticz#3983]
After #3978 icons for add/remove devices is missing
<img width="1329" alt="Снимок экрана 2020-03-14 в 16 34 08" src="https://user-images.githubusercontent.com/36986231/76683022-bbd50b00-6611-11ea-9e6e-a070d48c178e.png">

@stas-demydiuk

**Comment by stas-demydiuk** [comment]
Sorry, missed that

**Comment by MiG-41** [comment]
When can be this fix be ready in updatebeta ?
Unfortunatly i miss it very urgently...

**Comment by rwaaren** [comment]
> When can be this fix be ready in updatebeta ?
> Unfortunatly i miss it very urgently...
If you can't wait until next Beta.

change line 334 in <domoticz dir>/www/app/devices/Devices.js  from 
`if (device) {`
to

`if (isScene) {`

and then Stop / start domoticz and clear browsercache

**Comment by gizmocuz** [comment]
Thanks for thr quick fix!
