### ISSUE TITLE
Version 4.11794 Compile error

### ISSUE THREAD

**Issue by aldodemi** [domoticz/domoticz#3986]
Please someone can help?
Thank
Aldo

-- ###########################
-- Compiling Revision #11794
-- ###########################
-- Use builtin lua library
-- Using builtin Mosquitto library
-- Using builtin JSonCPP
-- Python3 includes found at: /usr/include/python3.7m
-- Building with I2C support
-- Building with SPI support
-- OPENSSL library found at: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Linking against boost static libraries
-- BOOST libraries found at: /usr/local/lib
-- Boost includes found at: /usr/local/include
-- ZLIB library found at: /usr/lib/x86_64-linux-gnu/libz.so
-- ZLIB includes found at: /usr/include
-- Curl library found at: /usr/lib/x86_64-linux-gnu/libcurl.so
-- Curl includes found at: /usr/include/x86_64-linux-gnu
-- LIBUSB library found at: /usr/lib/x86_64-linux-gnu/libusb.so
-- /home/domoticz/open-zwave-read-only/libopenzwave.a
-- GPIO is available
-- Not found telldus-core (telldus-core.h), not adding tellstick support
-- Using precompiled headers
CMake Error at CMakeLists.txt:695 (target_precompile_headers):
  Unknown CMake command "target_precompile_headers".

-- Configuring incomplete, errors occurred!
See also "/home/domoticz/domoticz/CMakeFiles/CMakeOutput.log".
See also "/home/domoticz/domoticz/CMakeFiles/CMakeError.log".
make: *** [Makefile:7684: cmake_check_build_system] Error 1

**Comment by rwaaren** [comment]
What is your hardware / OS / 32 or 64 bit / cmake version / gcc version ?

**Comment by aldodemi** [comment]
HP desktop, Ubuntu 19.04, 64 bit, until Mar 11, 2020 version no problem to compile, no OS/other application update done

**Comment by rwaaren** [comment]
And what about cmake and gcc versions ?

**Comment by aldodemi** [comment]
cmake version 3.15.4
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

**Comment by Jumbotroll** [comment]
You have to update to cmake version 3.16.5..
https://github.com/domoticz/domoticz/commit/2430e5c85624139dd15a74267d6e50992e394509

**Comment by aldodemi** [comment]
Update to cmake version 3.16.5 solved the problem.
Thank fro your help
Aldo

**Comment by gizmocuz** [comment]
@aldodemi , please check the compilation wiki or commit log

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI
