### ISSUE TITLE
No python execution ?

### ISSUE THREAD

**Issue by davidmarli** [domoticz/domoticz#3987]
Hello,

I have raspbian buster fresh install.
I did 

> curl -L https://install.domoticz.com | bash.

All is fine I upgrade to last beta version.I restore mybackup.

BUT I have still a pb, in the about tab, the last line is
Python : none

But I have Python installes !!! (3.7.3)

And with that thing, I can't use some plugins...

How to fix this ?

Thnak you for your help.

**Comment by rwaaren** [comment]
Please use the forum
