### ISSUE TITLE
MASTER-SLAVE paradigm

### ISSUE THREAD

**Issue by yo3hjv** [domoticz/domoticz#3988]
Did anyone think to a different Master-Slave concept in which, the Slave will point to a fixed IP?
This can be helpfull when the Slave system is on a dynamic IP and cannot be reached from outside.
It is my case, my Domoticz is connected to a 3G mobile network and cannot be reached even by DDNS.
In actual paradigm, the MASTER points to a fixed-IP Slave Domoticz; a Slave pointing to a Master with fixed IP can be usefull for many other users.

Thank you,
Adrian

**Comment by JurgenLB** [comment]
the master is always on fix IP and in case there is somthing wrong you need to access the slave. If the slave has a dynamic ip you don't know whitch ip to connect to. so I think both will need a static IP.
I also have a master / slave with fixed IP

**Comment by gizmocuz** [comment]
And you could use DNS names ?

**Comment by JurgenLB** [comment]
I didn't try DNS names, I just use a static IP for master and slave
