### ISSUE TITLE
AIQ sensor get value

### ISSUE THREAD

**Issue by empierre** [domoticz/domoticz#399]
Hello,

  I am searching to get the value of Air quality sensors through lua, and it seems that neither otherdevices_nvalue nor otherdevices_svalue returns a value "attempt to index global 'otherdevices_nvalue' (a nil value)"

**Comment by gizmocuz** [comment]
Please use our forum, or if your here, please look at the code of the EventViewer

the code displays:

```
        case pTypeAirQuality:
            utilityval = (float)(sitem.nValue);
            isUtility = true;
            break;
```

So i think it is in the utility values

**Comment by empierre** [comment]
Hello,

  added in the forum but "for i, v in pairs(devicechanged) do print(i, v) end" reports nothing

**Comment by gizmocuz** [comment]
I have no idea how lua works

**Comment by empierre** [comment]
there is this in the EventSystem.cpp but nothing for the nvalue, do you know who knows about this ? 
        lua_setglobal(lua_state, "otherdevices_svalues");

**Comment by empierre** [comment]
ok found, I'll update the wiki

```
    print(otherdevices_utility['AqCO2_Utility'])
```

**Comment by gizmocuz** [comment]
Thanks!
