### ISSUE TITLE
Fibaro Smoke Sensor wrong default for parameter 12.

### ISSUE THREAD

**Issue by jvberlo** [domoticz/domoticz#3991]
Version: 4.11777
For Firbaro device 'FGSD002 Smoke Sensor' is the configuration text for setting 12 incorrect.

12. BASIC OFF frame value: 
BASIC OFF frame is sent in case of FIRE ALARM cancellation. Available settings: (1 - 99) or 255. Default setting: **255**

The default setting according the Fibaro site https://manuals.fibaro.com/smoke-sensor/

 12. BASIC ON frame value
BASIC OFF frame is sent in case of FIRE ALARM cancellation. Its value is defined by the parameter.
Available settings: 0-99, 255
0 – turn off the device
1-99 – set the device to 1-99%
255 – set the last status
Default setting: **0**
Parameter size: 1 [byte]

**Comment by gizmocuz** [comment]
Thanks for reporting ! Please update to the latest beta to see if the problem still persist.
If it does, please report this on the openzwave repository as we use the configuration files from openzwave
