### ISSUE TITLE
Daikin wifi worker : multiple bugs in Daikin.cpp

### ISSUE THREAD

**Issue by dgrostoto** [domoticz/domoticz#4007]
Hello,
After several weeks of observing  my daikin wifi adaptor behaviour with domoticz , I identified several bugs in daikin worker which appear much clear to me after deeper analysis :
-when setting fan rate then setpoint shortly after, the fan rate reset to the old value at time of setpoint modification (side effect)
-idem between setpoint, fan rate, power on/off and possibly (not tested yet) power mode, fan dir.
-double set in BDD and domoticz web interface for setpoint power on/off and possibly (not tested yet) fan rate, fan dir, power mode.

The side effect comes from the mecachism that only rely on polling to set internal class member variables and forgot to set the same members on a direct user action. 
The double set bug is due to incorrect handling of setting data which does not take into account  if it comes from a set request or a polling (get request).

So i propose a pull request to correct all these bugs. I will detail any modifications afterwards.

**Comment by dgrostoto** [comment]
additionnal bug found during testing :
-worker was doing a http set control info at startup with empty arguments value which always fails (due to the missing arguments in the query string)

**Comment by gizmocuz** [comment]
Great! If you think it's all working correctly please make a PR

**Comment by dgrostoto** [comment]
Here are the documentation of modifications described as desired behavior below. If there is a divergent behavior observed this has to be considered as a bug (i will be pleased to correct it) :
Please note the main challenge comes from the fact that 6 parameters (power on-off/fan rate level/mode/dir level/target temperature/humidity target) are all set within the http request called set_control_info.

- Creation of a agregator for the 6 parameters :  to make a sort of buffer for "set control info" http request to request the hardware device only every 3 seconds at maximum (more frequent request are not recommended, the official android app have a bug about this).

- In case of continuous modifications (let say one modif per second) of the any of 6 parameters quoted above (which should not occurs but all cases have been considered), http set control info request is done every 7 seconds (this is a balance between reactivity and hardware sanity)

- Choice was done to keep a reactive web interface, so changes are immediately reflected on web interface even if the real command (http request) is not fired immediately. If request fails for any reason, the next polling (occurs every 300 seconds) will settle down each represented device values in the web interface.

- If an external ( ie : not from domoticz) action (example : standalone http request, remote infrared controller, android wifi app, etc...) is done on device, the modified value will be taken into account in domoticz at next polling (stored in BDD and value show in web interface and modification log in web interface)
- No more forced polling to get the value from device (web interface reacts immediately) and internal state is updated as soon as http set_control_info request returns OK to keep coherent information state.

- At last but not least, at each polling, values are updated only if the value is different from its internal state (ie : only if a set was from a external command).

Please also note that set_let was left as is (direct http request with no buffering), since it is a separate http request and is (very) quick to respond and it does not involve the PAC hardware device. Thus it can be utilised in dzvents (or else) scripts are much as wanted (we can make it use for blinking led if wanted).
No additionnal features are present here. It is a correction only.

Example of use in dzvents script :
now you can do those 2 lines on a off device :
domoticz.devices(pac_hardware_on_off).switchOn()
domoticz.devices(pac_hardware_set_point).setTemperature(20.0)
they will fire only on http request with the two modifications correctly (before the correction 2 http requests were fired and the second was switching off the hardware device).

**Comment by dgrostoto** [comment]
Hope my little doc is clear for every one. Feel free to ask questions of course.
PR is coming

**Comment by dgrostoto** [comment]
@gizmocuz 
Here are remaining questions (i left the code untouched for these points )
- line 754 in new file (PushandWaitRXMessage) why pushing message here if not sure at this point the hardware exist in BDD ? (may be a bug ?)
- for switch type (setFRate SetFDirLevel SetGroupOnOFF ...) switch values seems to be written before in BDD where as setpoint seems to need to have an explicit update (line 799 setsetpointsensor) why ?

**Comment by gizmocuz** [comment]
@dgrostoto , I am sorry but I did not create this class. Maybe best to look in the file history for the original author and discuss with him.
I do hope to use it this year !

**Comment by dgrostoto** [comment]
OK nevermind for those 2 questions. As far as now it works perfects at my home (i own a Daikin middle range pac as you guessed).
I could not find in git hub howto to request you review the PR, if you can do so, it will be great. Here is the PR :
https://github.com/domoticz/domoticz/pull/4016

**Comment by gizmocuz** [comment]
Thanks for the PR ! Looking great !

I did a little cleanup:
- Removed the debug save to disk (As some people work in debug...)
- Removed old comments
- Checked if the levels are correct

Could you check if checking against a valid level is ok ? I added this code:

```
void CDaikin::SetModeLevel
	else
		return; //Wrong level!

void CDaikin::SetF_RateLevel(const int NewLevel)
	else
		return; //Wrong level!

void CDaikin::SetF_DirLevel(const int NewLevel)
	else
		return; //Wrong Level
```

**Comment by dgrostoto** [comment]
Mmmmm, OK i see the case you want to handle, but we need to raise theses case a little higher in the calling stack. Let me propose a more complete handling in the PR.

**Comment by dgrostoto** [comment]
compiling on rasp 3B+ ... rather long...
Ah and, I liked to use LOG_WARNING (i make extensive use of this level of logging at work, which is very useful for finding bug afterwards on a working configuration). I used LOG_STATUS in AggregateSetControlInfo() instead but could it be possible to have the LOG_WARNING ad hoc macro ?

**Comment by dgrostoto** [comment]
OK, PR modified let me know of OK for you (maybe the little clean up is to be redone, sorry for that).

**Comment by gizmocuz** [comment]
Looks like all my changes have been reverted ? You could have done a git pull first...

**Comment by gizmocuz** [comment]
Merged the PR, thank you again !!

**Comment by dgrostoto** [comment]
Let's move to the next thing i'd like to be better in domoticz. :)
