### ISSUE TITLE
Pinger not working when running domoticz as user pi

### ISSUE THREAD

**Issue by baahver** [domoticz/domoticz#4009]
I'm running domoticz as user pi on raspberry with Raspbian Buster.
Domoticz version first from beta and now updated to v2020.1
Domoticz is running as pi, set in domoticz.sh
See: [https://www.domoticz.com/forum/viewtopic.php?f=6&t=31708](url)

linux user pi is able to use the ping command and ping 192.168.178.29.
But when setup system alive checker with this ip-address, and activate the device, the device never changes state. 
When running domoticz as root, the device state will change, and it is visible that 192.168.178.29 is alive.
So this looks like a permission error somewhere.

**Comment by baahver** [comment]
I'm wondering, is it not intended to run domoticz as another user then root? The options in the configuration file suggest that running domoticz as pi, or another user, should be  possible.
Is there no security issue involved when running domoticz as root user?

**Comment by xbeaudouin** [comment]
Unfortunately ICMP needs to be initiated by a high priv user. So by unix design, this is not possible (without... fork /sbin/ping...).
The security depends of you... If you have a dedicated machine / vm for domoticz... You'll have to check that anybody cannot access your domoticz without you permission.

**Comment by baahver** [comment]
Okay, thank you xbeaudouin. I will start and run domoticz as root then.

**Comment by baahver** [comment]
Someone on the forum showed me the sentence on bottom off the wiki page about the system alive checker. 

> Non-root permissions on Linux
When running Domoticz without root (recommended), you need to add the correct socket capabilities for this to function properly (otherwise it will fail silently!):
$ sudo setcap cap_net_raw=+eip path_to_domoticz_executable

So this is possible to run domoticz as user and preferable.

**Comment by Marbaf** [comment]
Hi,
I do not want to open an issue for this, so trying here.
I noticed domoticz is running as root and should not. I am pretty sure it was not like that in the past but did not pay attention when it changed.
Running on a raspberry pi, I stopped the process and ran a chown -R pi. on the folder.
Then I added the option --chuid pi to the daemon launch command.
But impossible to have domoticz running.
So the question is how to get domoticz running as pi when it is running as root?

**Comment by kiddigital** [comment]
A reason for domoticz to run as root is to have access to directly connected hardware.

In theory it should be possible to run as a non-root user, but most of the time Domoticz runs on a dedicated machine. Why is running as root a problem in those cases?

**Comment by Marbaf** [comment]
I do not want to piss anyone, I know domoticz has a long history and many contributors.
It is a matter of security. Running as root means the application has full rights on the system. A well designed application should have its dedicated user. This user can then have any rights till it is clearly stated and acknowledged.

**Comment by baahver** [comment]
Hi Marbaf,
I agree that Domoticz should not run as root. 
Although I stopped working with Domoticz and switched to Home Assistant, I can share my Domoticz config. 
I had best success by starting Domoticz as a Systemd service. This was on Raspberry pi, 3 and 4.
This was my systemd file: /etc/systemd/system/domoticz.service
```
[Unit]
      Description=domoticz_service
      After=network.target

[Service]
      Type=forking
      User=pi
      Group=users
      RuntimeDirectory=domoticz
      PIDFile=/var/run/domoticz/domoticz.pid
      ExecStart=/home/pi/domoticz/domoticz -daemon -pidfile /var/run/domoticz/domoticz.pid -www 8080 -sslwww 8090 -log /home/pi/log/domoticz.log
      ExecReload=/bin/kill -HUP $MAINPID
      KillMode=process
      WorkingDirectory=/home/pi/domoticz
      ExecStartPre=/usr/bin/sudo setcap 'cap_net_raw=+eip' /home/pi/domoticz/domoticz
      Restart=on-failure
      RestartSec=1m
      #StandardOutput=null
[Install]
      WantedBy=multi-user.target
      Alias=domoticz.sh.service
```

**Comment by Marbaf** [comment]
Thank you very much baahver.
I was also concerned by the fact that Domoticz still not use systemd properly...
My system was stable and optimized enough that I did not pay attention to it for months/years. While trying to update and clean the installation, I admit I have installed HA Core on anoter SD card...

**Comment by gizmocuz** [comment]
@Marbaf / @baahver , if you want you can make a PR for SystemD ... I have nothing against it and all systems these days support it

**Comment by Marbaf** [comment]
Almost 5 years of data in my domoticz database especially Teleinfo (electrical power supply) history is particularly useful nowadays.
According to this [official page](https://www.domoticz.com/wiki/Linux) systemd is the preferred way. But installation script still deploys sysV scripts (and in my case, from scratch installation crashes with my old db).

@baahver Do you confirm the setcap command is for pinger (alive checker) usage?

**Comment by baahver** [comment]
Yes it is!
See post 5 above

**Comment by Marbaf** [comment]
@baahver How did you solve this issue:
`domoticz: Could not open PID lock file /var/run/domoticz/domoticz.pid, exiting`
The _/var/run_ folder is virtual and gets wiped at shutdown. I found the below directive from [this discussion](https://www.domoticz.com/forum/viewtopic.php?t=29148):
`ExecStartPre=/usr/bin/install -d -m 0755 -o pi -g users /var/run/domoticz`

**Comment by baahver** [comment]
I have no Domoticz runnning so I do not know anymore. Have you tested it? It looks okay to me. 
If this does not work as expected, maybe you could at this command to cron as @reboot ?
` sudo crontab -e `
and add:
` @reboot /usr/bin/install -d -m 0755 -o pi -g users /var/run/domoticz `
But I have not tested that.
