### ISSUE TITLE
SOUND_SWITCH Support

### ISSUE THREAD

**Issue by Fishwaldo** [domoticz/domoticz#4010]
Opening this on behalf of Qubino Support (@petrovcicklemen):

Does Domoticz support the SOUND_SWITCH cc introduced in OZW 1.6?

![QUBINO_SOUND_SWITCH](https://user-images.githubusercontent.com/842308/77337502-f05c6b80-6d63-11ea-97dd-a6446aff50f1.png)

**Comment by gizmocuz** [comment]
No, currently we do not support this as this is a new class for us.
I received already some emails from Klemen about this, and asked for a sample, or we wait until it is available in the store.
I don't like to implement things 'virtual'
Thanks for reporting! I will reply here when it is done

**Comment by waltervl** [comment]
Implemented with https://github.com/domoticz/domoticz/commit/f838ee373738187b05039869465e36a4efdfb7b9
