### ISSUE TITLE
No error message when lua script fails

### ISSUE THREAD

**Issue by dwmw2** [domoticz/domoticz#4011]
I have the script from https://www.domoticz.com/wiki/Lua_-_Oil_Tank_Monitor stored as `scripts/lua/script_device_tank.lua`.

On updating from Domoticz 4.10717 to 2020.1, it stopped working.

I think it's because Domoticz is refusing to run it because of its filename? Since it needs to run when **either** the temperature or the sensor level are updated, it needs to be stored with *both* filenames `script_device_oil_tank_sensor.lua` **and** `script_device_oil_tank_temp.lua` ?

**Comment by gizmocuz** [comment]
I think you have better luck on the Forum as probably other users that where using the beta have faced this.
Did you try doing it via the normal Event Editor ?

**Comment by rwaaren** [comment]
Did you visit the wiki page after november 4th 2019 ?
This is what's in the wiki history...

curprev 22:30, 4 November 2019‎ Rwaaren talk contribs‎  6,863 bytes -9‎  Changed math.pow(x,y) to x^y undo

**Comment by dwmw2** [comment]
@rwaaren That appears to have been it; thanks. Having math.pow() appears to have made Domoticz completely stop acknowledging the existence of the script at all. No error message; nothing.

**Comment by rwaaren** [comment]
Probably something else. If you force an error you will see that iin the log 

`2020-03-24 20:02:25.384 Error: EventSystem: in Script #5: [string "commandArray = {} ..."]:3: attempt to call a nil value (field 'power')
`
If your experience is different:
What are you loglevel parms when starting domoticz and in domoticz  settings ?

**Comment by dwmw2** [comment]
It was running from a terminal like this:
`domoticz -noupdates -approot /usr/share/domoticz/ -loglevel 10 -syslog daemon -userdata /opt/domoticz/ -sslcert /etc/acme/*/fullchain.cer -sslwww 8443 -sslkey /etc/acme/*/*.key -ssldhparam /etc/acme/dhparam.pem`

**Comment by dwmw2** [comment]
In the meantime I rewrote it using dzVents anyway:
```
--
-- dzVents script to calculate oil tank levels
-- Based on my original at https://www.domoticz.com/wiki/Lua_-_Oil_Tank_Monitor
-- David Woodhouse <dwmw2@infradead.org>
--

-- Input devices: Temperature and air gap above fluid in tank
local tank_temp_sensor = 'Oil tank temperature'
local depth_sensor = 'Oil level sensor'

-- Output devices: Percentage full, volume.
local pct_sensor = 'Oil level'
local volume_sensor = 'Oil'

-- To adjust for fluid expansion
-- Report volume/percentage as they would be at 10°C
local canon_temp = -10
-- Kerosene
local expansion_coeff = 1.00099

-- Tank dimensions
local tank_height = 120
local tank_area = 60 * 181

return {
        on = {
                devices = {
                        'Oil tank temperature',
                        'Oil level sensor'
                }
        },
        execute = function(domoticz, device)
		local depthdev = domoticz.devices(depth_sensor)
		local tempdev = domoticz.devices(tank_temp_sensor)
		local pctdev = domoticz.devices(pct_sensor)
		local volumedev = domoticz.devices(volume_sensor)

		local depth = depthdev.state
		-- Calculate percentage and volume
		local pct = (tank_height - depth) / tank_height * 100
		local volume = (tank_height - depth) * tank_area / 1000

		-- Adjust for fluid expansion
		if tempdev ~= nil then
		   local temp = tempdev.state
		   local temp_delta = temp - canon_temp
		   local scale = expansion_coeff ^ temp_delta
		   pct = pct * scale
		   volume = volume * scale
		end
		domoticz.log('Tank update to ' .. pct.. '% ' .. volume .. 'l', domoticz.LOG_INFO)
		pctdev.updatePercentage(pct)

		local prev_volume = volumedev.state + 0
		volume = -volume
		domoticz.log('Volume ' .. volume .. ' was ' .. prev_volume, domoticz.LOG_INFO)
		-- Don't allow fluctuations to screw up the usage calculations. Only go up if it's been refilled.
		if volume >= prev_volume or (volume < (prev_volume - 100)) then
		    domoticz.log('Raising volume from ' .. prev_volume .. ' to ' .. volume, domoticz.LOG_INFO)
		    volumedev.update(0, volume)
		else
		    domoticz.log('Not reducing volume from ' .. prev_volume .. ' to ' .. volume, domoticz.LOG_INFO)
		end
	end
}

```

**Comment by rwaaren** [comment]
Thx. I will add the dzVents version to the wiki

**Comment by dwmw2** [comment]
Ta. Note my device names have changed since my first version; was going to make them match.

One of these days I do plan to stop abusing the water meter and having to use negative numbers to get a sane "oil used" graph...

**Comment by dwmw2** [comment]
I have (finally) realised my temperature calibration is utterly bogus and is adjusting the reported volume the wrong way round. Here's the fixed version:
```
--
-- dzVents script to calculate oil tank levels
-- Based on https://www.domoticz.com/wiki/Lua_-_Oil_Tank_Monitor
-- David Woodhouse <dwmw2@infradead.org>
--

-- Input devices: Temperature and air gap above fluid in tank
--local tank_temp_sensor = 'Oil tank temperature'
local tank_temp_sensor = 'Gas Temperature (left)'
local depth_sensor = 'Oil level sensor'

-- Output devices: Percentage full, volume.
local pct_sensor = 'Oil level'
local volume_sensor = 'Oil'

-- To adjust for fluid expansion
-- Report volume/percentage as they would be at 10°C
local canon_temp = 10
-- Kerosene
local expansion_coeff = 1.00099

-- Tank dimensions
local tank_height = 120
local tank_area = 60 * 181

return {
        on = {
                devices = {
                        depth_sensor
                }
        },
        execute = function(domoticz, device)
		local depthdev = domoticz.devices(depth_sensor)
		local tempdev = domoticz.devices(tank_temp_sensor)
		local pctdev = domoticz.devices(pct_sensor)
		local volumedev = domoticz.devices(volume_sensor)

		local depth = depthdev.state
		-- Calculate percentage and volume
		local pct = (tank_height - depth) / tank_height * 100
		local volume = (tank_height - depth) * tank_area / 1000

		-- Adjust for fluid expansion
		if tempdev ~= nil then
		   local temp = tempdev.state
		   local temp_delta = canon_temp - temp
		   local scale = expansion_coeff ^ temp_delta

		   -- temp_delta is how much colder the tank is than the canonical temperature
		   -- When the tank is colder, we scale *up* the reported volume to report it what it would be at 10°C
		   -- When the tank is warmer, we scale down.
		   -- domoticz.log('Scale factor ' .. scale .. ' for ' .. temp .. '°C delta ' .. temp_delta .. '°C', domoticz.LOG_INFO)
		   pct = pct * scale
		   volume = volume * scale
		end
		domoticz.log('Tank update to ' .. pct.. '% ' .. volume .. 'l', domoticz.LOG_INFO)
		pctdev.updatePercentage(pct)

		local prev_volume = volumedev.state + 0
		volume = -volume
		domoticz.log('Volume ' .. volume .. ' was ' .. prev_volume, domoticz.LOG_INFO)
		-- Don't allow fluctuations to screw up the usage calculations. Only go up if it's been refilled.
		if volume >= prev_volume or (volume < (prev_volume - 100)) then
		    -- domoticz.log('Raising volume from ' .. prev_volume .. ' to ' .. volume, domoticz.LOG_INFO)
		    volumedev.update(0, volume)
		else
		    -- domoticz.log('Not reducing volume from ' .. prev_volume .. ' to ' .. volume, domoticz.LOG_INFO)
		end
	end
}

```

I don't seem to be able to log in to the wiki or even create an account any more; is that expected?

**Comment by gizmocuz** [comment]
@dwmw2 , unfortunately since a few mediawiki updates the plugin to access the phpBB system is not working anymore.
You have to create a new account, and that is currently disabled because of all the bots/spammers
I have enabled registration for now, could you let me know when to close this ?

**Comment by dwmw2** [comment]
```
A database query error has occurred. This may indicate a bug in the software.
[367bc6881ea3f61016b74d67] 2020-03-25 14:30:26: Fatal exception of type "Wikimedia\Rdbms\DBQueryError"
```

**Comment by dwmw2** [comment]
And now creating an account 'dwmw2' appears to complain that the account name already exists, while trying to recover the password complains that it doesn't...

**Comment by gizmocuz** [comment]
Could you try with a different username ?

**Comment by gizmocuz** [comment]
If not, please contact me on the forum with the new content that you would like to have changed
(Or on Slack)

**Comment by dwmw2** [comment]
I'd prefer not to use a different username. The content was just the fixed dzVents script in https://github.com/domoticz/domoticz/issues/4011#issuecomment-603819613 above *(with the temperature calibration no longer being utterly bogus and backwards)*, into the wiki page at https://www.domoticz.com/wiki/Lua_/_dzVents_-_Oil_Tank_Monitor

Thanks.

**Comment by gizmocuz** [comment]
@dwmw2 , I know, can't help you with wiki access at the moment, to much spamming/fake user registrations etc. Specially these days.
I updated the Lua code on the Wiki Page, thanks !
