### ISSUE TITLE
Waether Forecast: Dasksky refuses connection

### ISSUE THREAD

**Issue by DaKarlii** [domoticz/domoticz#4012]
Since Update to Version: Version 2020.1 (March 22th 2020), Wather Forecast is not Possible anymore. Just got a Browser PopUp With:

<iframe class="cIFrameLarge" id="IMain" src="//darksky.net/forecast/XX.XXXXXX,YY.YYYYYYY/si24/de"></iframe>

In the background the Iframe says: "Darksky refuses the connection"

If the URL will called directly in the Browser, everything is ok.

Domoticz is running on latest Raspbian.

**Comment by gizmocuz** [comment]
Please try beta 11836, it's now using the forcecast.io embedded URL until someone finds a better way

**Comment by Yoz12** [comment]
Hi,
It's because Domoticz makes a call to the API over HTTP and not HTTPS. 
Try with http://darksky.net/forecast/40.7127,-74.0059/us12/en --> NOK
https://darksky.net/forecast/40.7127,-74.0059/us12/en --> OK

But I don't know where I can change it

**Comment by gizmocuz** [comment]
@Yoz12 , it depends, do you access domoticz via https ? if yes, it should also do this to darksky
But you can check this by modifying the code in www/app/ForecastController.js

**Comment by DaKarlii** [comment]
Hi guys,

I tried to edit the ForecastController.js and add https and http to the link. But still "Darksky refused the connection".

Btw. I  already got the Wether devices from Darksky: Temp, Hum, Baro, Windspeed, Rain... all of the OK. Only the Forecast Frame isn't working!


@gizmocuz: The workaround fixes the issue not to 100%
I Still geht the Browser PoPup, but in the background the Frame gets loaded!

**Comment by gizmocuz** [comment]
@DaKarlii , please clear the browser cache + appcache first, or try a private browser
You do have to remove the 'alert' box call (which i have done already in the development branch)

**Comment by DaKarlii** [comment]
@gizmocuz : Yes i always test with a clean browser session, but i didn't noticed that i have to remove the alert box!
Now it is fine! Thank your very much!

**Comment by gizmocuz** [comment]
@DaKarlii , chaning the line to the below does not solve the issue 9(here)

`htmlcontent += '<iframe class="cIFrameLarge" id="IMain" src="https:////darksky.net/forecast/' + data.Latitude + ',' + data.Longitude + '/' + units + '/' + $rootScope.config.language + '"></iframe>';
`

The error returned (by Darksky) is:

Refused to display 'https://darksky.net/forecast/12.3456,78.9876/ca24/en' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by DaKarlii** [comment]
@gizmocuz : Yes i know. adding http or https to the link doesn't help.
But your "Temporally fix for issue 4012" does. But first i only edited the link and didn't turned of the alerting. For now I'm fine with this solution/workaround.

As fas as i understand the Problem here is DarkSky, because they dont allow to use there website in a frame. Right?

**Comment by gizmocuz** [comment]
@DaKarlii , yes that is correct.
Another option is to open a new webpage when you click on the forecast button
But i hope the temp solution is OK

**Comment by Yoz12** [comment]
Hi,
Thanks for your support. It's perfect for me !
