### ISSUE TITLE
Feature request : Access/modification to Netatmo Energy planning

### ISSUE THREAD

**Issue by MuadDibVV** [domoticz/domoticz#4013]
Is it possible to add a new feature to see and modify the used Netatmo Energy planning.
(It's possible with IFTTT so the API exist)
It's important for me to automatically change planning on holidays
Thanks a lot

**Comment by MuadDibVV** [comment]
In the meantime, I call an IFTTT webhook who will do the work, a little shame but it works.

**Comment by MuadDibVV** [comment]
> In the meantime, I call an IFTTT webhook who will do the work, a little shame but it works.

In view of the new IFTTT policy, the point becomes very important again.

**Comment by gizmocuz** [comment]
@MuadDibVV , I have no idea what this is about. But feel free to experiment with the code

**Comment by MuadDibVV** [comment]
> @MuadDibVV , I have no idea what this is about. But feel free to experiment with the code

@gizmocuz Thanks for your answer. Unfortunately it's a bit complex for me to understand the existing code :-(
In hardware/Netatmo.cpp
It's necessary to get more information from the existing Get /Homesdata ("schedules"/"name" https://dev.netatmo.com/apidocumentation/energy#homesdata)
Creating a switch with this values
Créating function on change of this switch to access Post /Switchhomeschedule (https://dev.netatmo.com/apidocumentation/energy#switchhomeschedule)

**Comment by JurgenLB** [comment]
I believe the code in Netatmo.h uses only the scope NETYPE_WEATHER_STATION = 0, NETYPE_HOMECOACH, NETYPE_ENERGY
so I think this is the limitation at this moment, I'm willing to try to understand and expand the code when I have the time

**Comment by JurgenLB** [comment]
I think with the recent changes in the code of Netatmo.cpp this is resolved and can be closed.
