### ISSUE TITLE
Openwrt compile error

### ISSUE THREAD

**Issue by batorencjusz** [domoticz/domoticz#4014]
Hello!

I can't compile version higher than 4.11784 for openwrt. 
Every compilation ends up with fallowing error:

> fatal: not a git repository: './.git'
> 
> -- Failed to get ProjectRevision from git
> -- Read ProjectRevision from History.txt
> -- ###########################
> -- Compiling Revision #1
> -- ###########################
> -- Use builtin lua library
> -- MQTT library found at: /openwrt/staging_dir/target-mips_24kc_musl/usr/lib/libmosquitto.so
> -- MQTT includes found at: /openwrt/staging_dir/target-mips_24kc_musl/usr/include
> -- Using builtin JSonCPP
> -- Python3 includes found at: /openwrt/staging_dir/target-mips_24kc_musl/usr/include/python3.7
> -- Building with I2C support
> -- Building with SPI support
> -- OPENSSL library found at: /openwrt/staging_dir/target-mips_24kc_musl/usr/lib/libssl.so;/openwrt/staging_dir/target-mips_24kc_musl/usr/lib/libcrypto.so
> -- Linking against boost dynamic libraries
> CMake Warning at /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1125 (message):
>   New Boost version may have incorrect or missing dependencies and imported
>   targets
> Call Stack (most recent call first):
>   /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1247 (_Boost_COMPONENT_DEPENDENCIES)
>   /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1885 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:528 (find_package)
> 
> 
> CMake Warning at /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1125 (message):
>   New Boost version may have incorrect or missing dependencies and imported
>   targets
> Call Stack (most recent call first):
>   /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1247 (_Boost_COMPONENT_DEPENDENCIES)
>   /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1885 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:528 (find_package)
> 
> 
> CMake Warning at /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1125 (message):
>   New Boost version may have incorrect or missing dependencies and imported
>   targets
> Call Stack (most recent call first):
>   /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1247 (_Boost_COMPONENT_DEPENDENCIES)
>   /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1885 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:528 (find_package)
> 
> 
> CMake Warning at /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1125 (message):
>   New Boost version may have incorrect or missing dependencies and imported
>   targets
> Call Stack (most recent call first):
>   /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1247 (_Boost_COMPONENT_DEPENDENCIES)
>   /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1885 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:528 (find_package)
> 
> 
> CMake Warning at /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1125 (message):
>   New Boost version may have incorrect or missing dependencies and imported
>   targets
> Call Stack (most recent call first):
>   /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1247 (_Boost_COMPONENT_DEPENDENCIES)
>   /openwrt/staging_dir/host/share/cmake-3.15/Modules/FindBoost.cmake:1885 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:528 (find_package)
> 
> 
> -- BOOST libraries found at: /openwrt/staging_dir/target-mips_24kc_musl/usr/lib
> -- Boost includes found at: /openwrt/staging_dir/target-mips_24kc_musl/usr/include
> -- ZLIB library found at: /openwrt/staging_dir/target-mips_24kc_musl/usr/lib/libz.so
> -- ZLIB includes found at: /openwrt/staging_dir/target-mips_24kc_musl/usr/include
> -- Curl library found at: /openwrt/staging_dir/target-mips_24kc_musl/usr/lib/libcurl.so
> -- Curl includes found at: /openwrt/staging_dir/target-mips_24kc_musl/usr/include
> -- ==== OpenZWave not found, support disabled!
> -- GPIO is available
> -- Not found telldus-core (telldus-core.h), not adding tellstick support
> -- Using precompiled headers
> CMake Error at CMakeLists.txt:684 (target_precompile_headers):
>   Unknown CMake command "target_precompile_headers".

in file CMakeError.log:

> 
> 
> Determining if the include file execinfo.h exists failed with the following output:
> Change Dir: /openwrt/build_dir/target-mips_24kc_musl/domoticz-d93f467a7b149514783f83c8e9119130ba612d42/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/make cmTC_40680/fast && make[4]: Entering directory '/openwrt/build_dir/target-mips_24kc_musl/domoticz-d93f467a7b149514783f83c8e9119130ba612d42/CMakeFiles/CMakeTmp'
> /usr/bin/make -f CMakeFiles/cmTC_40680.dir/build.make CMakeFiles/cmTC_40680.dir/build
> make[5]: Entering directory '/openwrt/build_dir/target-mips_24kc_musl/domoticz-d93f467a7b149514783f83c8e9119130ba612d42/CMakeFiles/CMakeTmp'
> Building C object CMakeFiles/cmTC_40680.dir/CheckIncludeFile.c.o
> /openwrt/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/bin/mips-openwrt-linux-musl-gcc   -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap/openwrt/build_dir/target-mips_24kc_musl/domoticz-d93f467a7b149514783f83c8e9119130ba612d42:domoticz-d93f467a7b149514783f83c8e9119130ba612d42 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -flto    -o CMakeFiles/cmTC_40680.dir/CheckIncludeFile.c.o   -c /openwrt/build_dir/target-mips_24kc_musl/domoticz-d93f467a7b149514783f83c8e9119130ba612d42/CMakeFiles/CMakeTmp/CheckIncludeFile.c
> /openwrt/build_dir/target-mips_24kc_musl/domoticz-d93f467a7b149514783f83c8e9119130ba612d42/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: execinfo.h: No such file or directory
>  #include <execinfo.h>
>           ^~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/cmTC_40680.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_40680.dir/CheckIncludeFile.c.o' failed
> make[5]: *** [CMakeFiles/cmTC_40680.dir/CheckIncludeFile.c.o] Error 1
> make[5]: Leaving directory '/openwrt/build_dir/target-mips_24kc_musl/domoticz-d93f467a7b149514783f83c8e9119130ba612d42/CMakeFiles/CMakeTmp'
> Makefile:121: recipe for target 'cmTC_40680/fast' failed
> make[4]: *** [cmTC_40680/fast] Error 2
> make[4]: Leaving directory '/openwrt/build_dir/target-mips_24kc_musl/domoticz-d93f467a7b149514783f83c8e9119130ba612d42/CMakeFiles/CMakeTmp'

**Comment by gizmocuz** [comment]
You have to use CMake 3.16 or higher, 3.17 recommended

**Comment by batorencjusz** [comment]
i think it's about execinfo.h

> 
> /openwrt/build_dir/target-mips_24kc_musl/domoticz-d93f467a7b149514783f83c8e9119130ba612d42/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: execinfo.h: No such file or directory
> #include <execinfo.h>
> ^~~~~~~~~~~~
> compilation terminated.

**Comment by gizmocuz** [comment]
IF you have CMake 3.16/3.17, is this your first compile ?
Did you follow this guide (should also apply for openwrt)

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

If you search here in the issues for openwrt you will find more users

**Comment by batorencjusz** [comment]
yeah i'd read it but for openwrt (at the moment) cmake version is 3.15.1 so this guide will not work.
in CMakeLists.txt its:

> 
> #set to minimum version that supports clean build
> cmake_minimum_required(VERSION 3.14.0)
> 
> project(domoticz)
> 
> ## required min. libBoost version
> SET(DOMO_MIN_LIBBOOST_VERSION 1.66.0)
> ##

execinfo.h is in glibc but openwrt is using musl.

i did compile version up to 4.11784 without any problems.

**Comment by gizmocuz** [comment]
Yes the guide will work as it shows you how to build CMake 3.17

**Comment by batorencjusz** [comment]
i've got CMake 3.17 on my system

> ~ cmake --version
> cmake version 3.17.0
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).

but when buliding domoticz for openwrt compilation using 3.15 from openwrt sources

**Comment by gizmocuz** [comment]
@batorencjusz , Sorry I do not understand you completely.
Can you compile without errors on your system (with CMake 3.17, following the guide mentioned above) ?
If yes, then i consider this issue closed

**Comment by gizmocuz** [comment]
@@batorencjusz , I assume you could compile Domoticz ?

**Comment by batorencjusz** [comment]
yes i can compile on my system without any errors BUT
to compile .ipk file for openwrt i have to compile domoticz in openwrt sources for my platform (ath79). 
Current stabile version of openwrt uses CMake 3.15
Development version uses 3.16

At the moment its impossible to compile version higher than 4.11784 for stable version because of CMake version. So the only think i can do now is wait until CMake version for openwrt sources will be bumped to 3.16 or higher.

THX for youre help

**Comment by gizmocuz** [comment]
@batorencjusz , good that you can compile on your system.
For CMake, 3.16 is fine

Besides, you can easily compile CMake (any version) yourself if you follow our wiki
