### ISSUE TITLE
Google PubSub export not working

### ISSUE THREAD

**Issue by zak-mo** [domoticz/domoticz#4021]
Hello,

   Google Pubsub is not working and keeps returning:

> Error: Error sending data to GooglePubSub : Python not available!

   However, Python is correctly detected by Domoticz as we can see below: 

> Version: 4.11807
> Build Hash: 3c6fbb7ed
> Compile Date: 2020-03-22 10:25:34
> dzVents Version: 3.0.1
> Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

   Domoticz is running on Raspbian 10.

   I also tried to build Domoticz from sources (in Ubuntu 18.04) using option -DUSE_PYTHON=yes (as stated by the author [here](https://github.com/domoticz/domoticz/pull/726#issue-76556172)) but i'm still getting the same error message...

**Comment by gizmocuz** [comment]
It is best to follow this tutorial:

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

(It is also for Ubuntu)

But please try with the latest stable/beta (11838) , install domoticz with the 'sudo' command:

https://www.domoticz.com/downloads/

If that is working (or not working), when you compile manually, does it say it finds Python ?
When you issue a 'git pull' in your source tree, and you are doing a different CMake call (like -DUSE_PYTHON=YES) , please remove the folder 'CMakeFiles' and the file 'CMakeCache.txt' before doing so, this will rebuild everything

**Comment by zak-mo** [comment]
Hi,

   Thanks for your answer!

   In a few words (details below), when compiled manually (from fresh new sources / folder) Python is correctly detected by Domoticz on startup, but I still have the same error message: Error: Error sending data to GooglePubSub : Python not available! 

   I tried to understand the error and I noticed that a [lot of files](https://github.com/domoticz/domoticz/search?q=ENABLE_PYTHON&unscoped_q=ENABLE_PYTHON) are using the condition "#ifdef ENABLE_PYTHON" whereas the condition "#ifdef ENABLE_PYTHON_DECAP" is used only for [GooglePubSubPush.cpp](https://github.com/domoticz/domoticz/search?q=ENABLE_PYTHON_DECAP&unscoped_q=ENABLE_PYTHON_DECAP).

   I tried to replace #ifdef ENABLE_PYTHON_DECAP by #ifdef ENABLE_PYTHON in GooglePubSubPush.cpp and compiled again sources (to undo the change [here](https://github.com/domoticz/domoticz/commit/b66d08c827ef17791631bd78b020c32b724ca575#diff-340308c89c00131478ed944a1c5f026e)). But unfortunately it did not compile at all, I had an error when it came to compile this file ...

   With a lot of details, here is what you asked for: 

**Domoticz on latest beta for Raspbian**
_Installed the '[easy way](https://www.domoticz.com/wiki/Raspberry_Pi#The_.22easy.22_way)'_

- About Page:
> Version: 2020.1 (build 11836)
> Build` Hash: 7e0c5045a
> Compile Date: 2020-03-25 17:53:32
> dzVents Version: 3.0.1
> Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

- On the logs on startup: 
> PluginSystem: Started, Python version '3.7.3'.
> Python EventSystem: Initalizing event module.

- Once Google PubSub export is enabled (after devices are added), I can see the error below in the logs:
> Error: Error sending data to GooglePubSub : Python not available!

**Domoticz on latest stable for Linux / Ubuntu**
_Installed from https://www.domoticz.com/downloads/ run as sudo_

- About page:
> Version: 2020.1 (build 11838)
> Build Hash: 372611b76
> Compile Date: 2020-03-26 15:21:15
> dzVents Version: 3.0.1
> Python Version: 3.7.5 (default, Nov 7 2019, 10:50:52) [GCC 8.3.0]

- On the logs on startup:
> PluginSystem: Started, Python version '3.7.5'.
> Python EventSystem: Initalizing event module.

- Once Google PubSub export is enabled (after devices are added), I can see the error below in the logs:
> Error: Error sending data to GooglePubSub : Python not available!

**Ubuntu compiled manually using -DUSE_PYTHON=YES (following this tutorial https://www.domoticz.com/wiki/Build_Domoticz_from_source)**
_Official sources, not modified at all_
- The commands used to compile:
> git clone https://github.com/domoticz/domoticz.git dev-domoticz
> git pull
> cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt -DUSE_OPENSSL_STATIC="NO" -DUSE_PYTHON=yes
> make

- About page:
> Version: 2020.1 (build 11839)
> Build Hash: 139d994e5
> Compile Date: 2020-03-27 06:53:01
> dzVents Version: 3.0.1
> Python Version: 3.7.5 (default, Nov 7 2019, 10:50:52) [GCC 8.3.0]

- On the logs on startup:
> PluginSystem: Started, Python version '3.7.5'.
> Python EventSystem: Initalizing event module.

- Once Google PubSub export is enabled (after devices are added), I can see the error below in the logs:

> Error: Error sending data to GooglePubSub : Python not available!

**Comment by zak-mo** [comment]
I tried again to "fix" the push/GooglePubSubPush.cpp file by:

- replacing all the #ifdef ENABLE_PYTHON_DECAP conditions with #ifdef ENABLE_PYTHON
- replacing _ialize();_ line 248 with Py_Initialize();

But I'm still not able to compile correctly ... I'm afraid I'm not skilled enough yet to fully fix it!

However, I'm pretty sure there have been an issue on this file for a few years.

I also tried to restore using a previous version ([that one](https://github.com/domoticz/domoticz/commit/80720bab59c8fc130659207a361441df1d0cc49c/push/GooglePubSubPush.cpp)) and by updating line 204 and 209 to match the correct definition of function ProcessSendValue(). But still not able to compile sources ...

**Comment by gizmocuz** [comment]
@wotan01 , if you follow this guide step by step it should give you a compiled domoticz:

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by zak-mo** [comment]
@gizmocuz yes, this guide works fine thanks. However, I cannot get Google PubSub export to work whether it is with already compiled domoticz, or manually compiled domoticz (all other features i'm using are running well!). 

By digging further, I found some issues on the file GooglePubSubPush.cpp that, I believe, prevent this feature to work as it should:
- all the python stuff seems to be ignored because the condition #ifdef ENABLE_PYTHON_DECAP is used instead of #ifdef ENABLE_PYTHON
- there is the typo line 248 _ialize();_ instead of Py_Initialize();

It looks like this Google Pubsub feature was neutralized on [this commit](https://github.com/domoticz/domoticz/commit/b66d08c827ef17791631bd78b020c32b724ca575#diff-340308c89c00131478ed944a1c5f026e). But any change I do locally on the file GooglePubSubPush.cpp prevent me to compile correctly. 

Official Domoticz sources are working well, and the guide you mentioned also. But the Google Pubsub export is not working and I'm not able to fix it.

**Comment by waltervl** [comment]
Is Google PupSub export working on latest stable 2022.1 ?
