### ISSUE TITLE
Nefit setting in Tab others oke, but in dashboard NaN

### ISSUE THREAD

**Issue by biancapascal** [domoticz/domoticz#4025]
In the tab Others i can set the temperture without any problem, and in dashboard i get NaN.
See attachments.
In tab others
![nefit1](https://user-images.githubusercontent.com/7604917/77895690-72262a80-7277-11ea-865b-a53ff9c142a6.PNG)
In tab dashboard
![nefit2](https://user-images.githubusercontent.com/7604917/77895695-72bec100-7277-11ea-9fb2-e6975af532f9.PNG)

Meanwhile this was not a problem in the previous version before the latest update.

**Comment by Sneeuwtijger** [comment]
Did you try switching to Default Theme ?

**Comment by pascalbianca** [comment]
> Did you try switching to Default Theme ?

Yes all theme's give the same results on both tabs.

**Comment by gizmocuz** [comment]
Did you clear the browser cache + appcache (two different things), or try a private browser session first
Just tried it here, and I experience no issues

**Comment by pascalbianca** [comment]
browser cache i cleared but appcache how must that be done in chrome?
i see in IE that the problem isn't there.

**Comment by pascalbianca** [comment]
SOLVED , thank you very mutch

**Comment by gizmocuz** [comment]
Great it is working now ! But when you created this Issue, there was a guideline presented that you need to follow, one of the lines was

"Clear your browser cache + AppCache (two different things!!)"

**Comment by pascalbianca** [comment]
ow, sorry , this is total new for me. 
Next time i try that first.
