### ISSUE TITLE
rtl_433 vs whx080

### ISSUE THREAD

**Issue by rumpibandi** [domoticz/domoticz#4026]
i tried the rtl sdr usb dongle on 868 mhz and it find an weather station what i have and the protocol what it recognised is the device WHx080, everything work only the wind direction is always 0 angle (N)
if i try-t in a cmd the rtl_433 than there was listed correct angle, so i suppose the recieved data precessing is not fully correct.

**Comment by gizmocuz** [comment]
Domoticz version ?

**Comment by rumpibandi** [comment]
sorry actually the 2020 01 stabil windows.

**Comment by gizmocuz** [comment]
Could you post a RTL433 reception line here from the command line utility ? maybe i could try to debug this

**Comment by rumpibandi** [comment]
![kép](https://user-images.githubusercontent.com/56233474/77918686-84ff2600-729c-11ea-80c3-961cfbc2a000.png)
that was what i got only, unfortunately i'm not an expert only now started to learn how its working, i hope this can maybe help

**Comment by rumpibandi** [comment]
no any raw data, and unfortunately i do not know how can get it...

**Comment by rumpibandi** [comment]
![kép](https://user-images.githubusercontent.com/56233474/77919123-12db1100-729d-11ea-96e9-78b8f1c6be90.png)

**Comment by rumpibandi** [comment]
![kép](https://user-images.githubusercontent.com/56233474/77919184-26867780-729d-11ea-9879-448da36d8dc1.png)

**Comment by rumpibandi** [comment]
![kép](https://user-images.githubusercontent.com/56233474/77919314-4b7aea80-729d-11ea-9303-68d546d29163.png)

**Comment by gizmocuz** [comment]
instead of domoticz, could you run the rtl433 executable by hand ? and enable logging

**Comment by rumpibandi** [comment]
could you please provide the exact command / parameters to this loggong? 
https://github.com/merbanan/rtl_433
somehow with this?
[-F kv | json | csv | mqtt | influx | syslog | null | help] Produce decoded output in given format.
       Append output to file with :<filename> (e.g. -F csv:log.csv), defaults to stdout.
       Specify host/port for syslog with e.g. -F syslog:127.0.0.1:1514
than i try it :D
Thanks!

**Comment by rumpibandi** [comment]
trying this:
rtl_433 -f 868300000 -F csv:c:\tmp\log.csv
waiting now the result

**Comment by rumpibandi** [comment]
[rtllog.txt](https://github.com/domoticz/domoticz/files/4403486/rtllog.txt)
actually it is not providing values ... but if i terminated the command i got a header into this log.csv, i separated this to different rows, in this maybe you can see where is the wind direction degree and wind direction...
![kép](https://user-images.githubusercontent.com/56233474/77924702-4bcab400-72a4-11ea-9918-f6354831452a.png)

**Comment by rumpibandi** [comment]
final results...
[log.txt](https://github.com/domoticz/domoticz/files/4403620/log.txt)

**Comment by rumpibandi** [comment]
![kép](https://user-images.githubusercontent.com/56233474/77927647-c21ce580-72a7-11ea-923b-de565f2786d5.png)
if i check the results in excel

**Comment by gizmocuz** [comment]
@rumpibandi , thank you for the log.
Are you using the latest RTL433 executable/version ?
Because for wind direction the field is now 'wind_dir_deg'

**Comment by rumpibandi** [comment]
in this case maybe not, i do not know the ver, i found it somewhere, if i'm right on github, do you have the link of the last version? i will download and try it.
thanks in advance and your work!

**Comment by rumpibandi** [comment]
https://github.com/winterrace/rtl_433_win/releases/tag/v19.8.19
is this the last?

**Comment by gizmocuz** [comment]
https://github.com/merbanan/rtl_433/releases

**Comment by rumpibandi** [comment]
here i could not find rtl_433.exe, only py... as we discussed i'm using domo and this under windows10.
and i found the visual studio project but could not build it...  do you have the latest exe?

**Comment by rumpibandi** [comment]
found this:
https://bintray.com/chzu/dist/rtl_433#files
will try

**Comment by rumpibandi** [comment]
i downloaded the latest file from the link above, and it looks like you were right, at first look it works well! Thanks you very much!
![kép](https://user-images.githubusercontent.com/56233474/78016935-cac6f780-734b-11ea-9441-c7a5a6a70d6a.png)

**Comment by gizmocuz** [comment]
Great it's working!
