### ISSUE TITLE
Domoticz doesn't echo an /out update through MQTT when a devices is udpdated via /in

### ISSUE THREAD

**Issue by t0mg** [domoticz/domoticz#4035]
I believe this behavior was an intended change (might be due to commit 20462bb29e93a1de68a05840462bcc92feb53e3a) but I don't understand the reasoning for it. Besides it actually breaks Reacticz which relies on MQTT to update its UI. 

The state of the UI in Reacticz is completely decoupled from local user interactions, so when pressing a button on Reacticz it sends an MQTT or JSON message then Reacticz waits on the /out message from domoticz to reflect any change in its UI. This behavior seems broken with the 2020.1 release as the /out messages are now emitted only if the command was sent over JSON.

As a consequence the UI of Reacticz will only get updated for actions that rely on JSON messaging (which is considered as a fallback for lack of MQTT support on specific commands, not the primary choice).

**Comment by gizmocuz** [comment]
Please use the search option here as this is already being discussed

**Comment by t0mg** [comment]
Ok, I suppose you are talking about [this one](https://github.com/domoticz/domoticz/issues/3863#issuecomment-592040551). I missed it because that issue was closed. While I understand the reasoning, I can see several cases where this doesn't work (including reacticz) so I agree with the conclusion of the discussion suggesting that this change should be made optional. How can I track this topic ? Should the issue be reopened ?

Thanks!

**Comment by gizmocuz** [comment]
I don't know Reacticz, but could this be updated ?

**Comment by t0mg** [comment]
Technically, yes, but this goes against the core principle in Reacticz and React apps in general. 

In React apps, when you click on a checkbox, it doesn't check the box immediately: the components calls a method on a model, and the model will update a state object, and finally the UI reflects the state update and checks the box. It's that same principle that I applied to Reacticz: the whole point of Reacticz was to make sure that the buttons accurately reflect the true state of Domoticz devices at all times. Reacticz doesn't assume a state change because the user clicked a button. It sends commands and relies on domoticz/out messages to update the UI state.

Changing that design pattern would render Reacticz pointless to me. Other, more complex Domoticz dashboards could be used instead.

**Comment by gizmocuz** [comment]
Please try beta 11922, for MQTT there is now a settings option to Enable/Disable the loopback.
Default set to True, as this will be the default later, and this option might be removed in the feature
It goes into all core principles to broadcast the same message back, it should be one client that publishes a message and received by everyone listening to it

https://1sheeld.com/mqtt-protocol/

**Comment by t0mg** [comment]
Thank you for getting back to me on this. Unfortunately that didn't work for me, changing the new loopback option seemed to have no effect (I double checked with http://www.hivemq.com/demos/websocket-client/). I've been having trouble since 2020.1 so maybe that's just my setup that's broken.

In order to be future proof Reacticz should be partly rewritten to only send commands through the JSON API (currently it uses MQTT for all the supported commands and falls back to JSON for the rest). This is doable, and fairly easily, but I am currently no longer actively working on it, so unfotunately I won't be able to do these changes myself. Feel free to shut down the project if you think that's best.

Cheers,
