### ISSUE TITLE
Setpoint thermostats timers doesn’t work anymore

### ISSUE THREAD

**Issue by busshi** [domoticz/domoticz#4040]
Hello,

I just updated to the latest version 2020.1. Since that my dummy setpoints timers doesn’t work anymore. I made a lot of tests but sometimes it works, randomly... Most of the times it doesn’t trigger.  No error in the log, just Resent EventSystem (in status) but no error. Am I the only one to face this issue ?

pi3 buster, domoticz 2020.1, everything up-to-date (fresh install)

**Comment by rwaaren** [comment]
Please do not open a new issue for this and continue the discussion on issue https://github.com/domoticz/domoticz/issues/3967.
