### ISSUE TITLE
New feature : possibility to create a setpoint timer

### ISSUE THREAD

**Issue by busshi** [domoticz/domoticz#4041]
Hi

Is it possible to create a timer for a dummy thermostat (setpoint) with the Json API ? I coulnd’t find on the Wiki. I am stuck with my (on time) thermostats timers which doesn’t work at all since the update. I made a lot of tests to make the timers working. If I change On Time to Fix Date/Time it is working. But I can’t do it manually everyday. So I was creating a bash script to copy all the schedules from a day to another but it is not possible with the API because I cannot create a setpoint timer nor update one with the API. 🤔Doesn’t somebody have any idea ?? 
Is there a hidden function to do it ?

**Comment by rwaaren** [comment]
Please use the forum topic [Suggestions](https://www.domoticz.com/forum/viewforum.php?f=31) for suggestions and feature requests. Domoticz github is for reporting and discussing code bugs.
