### ISSUE TITLE
Dashboard update

### ISSUE THREAD

**Issue by Allras82** [domoticz/domoticz#4045]
Hi,

This is a minor thing.
After update to 2020.1, my dashboard does not update status after turning no/off switches. I have to manual refresh browser befor the new status is shown.
This i haven't seen in the "old" version.

BR Allan

Version: 2020.1
Build Hash: 63fa969e4
Compile Date: 2020-03-22 15:16:16
dzVents Version: 3.0.1
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

**Comment by rwaaren** [comment]
I cannot replicate this on my system (Debian) / browser (Chrome)

Updates are instant on my dashboard,
Sorry to ask but did you clear cache and appcache ? (different things)

**Comment by pepsi92** [comment]
Hi,

Same issue for me, since more than 6 months now (and of course the browser cache has been cleared many times since then). Sorry, I should have reported it earlier :)

Domoticz v4.11774 running on Synology DSM 6.2.2-24922 Update 4

KR,
Nicolas

**Comment by rwaaren** [comment]
> Same issue for me, since more than 6 months now (and of course the browser cache has been cleared many times since then). 

Most people clear browser cache when they see some kind of unexpected behavior in a GUI. Not many also clear appcache and cookies and/or other history. Stil that solves the majority of GUI related problems. Just have a look on the forum and be surprised how many forum members came to the same conclusion..

**Comment by pepsi92** [comment]
Yes, fully agree with you. Usualy, I clean everything (see below the options I use in FF)

<img width="444" alt="Capture d’écran 2020-04-02 à 18 21 52" src="https://user-images.githubusercontent.com/18167025/78273372-052cc200-750f-11ea-93a4-9fe2b7bea5ea.png">

**Comment by rwaaren** [comment]
Please forgive my ignorance but my French is close to none existent. Does this include appcache
- clear appcache 
    Chrome:     chrome://appcache-internals/#
    Firefox:    https://support.mozilla.org/en-US/kb/storage

**Comment by pepsi92** [comment]
Sorry I forgot to change to english before. Below the same with Fitefox in english:

<img width="445" alt="Capture d’écran 2020-04-02 à 19 02 04" src="https://user-images.githubusercontent.com/18167025/78277282-8aff3c00-7514-11ea-9054-16d272ce0a7b.png">

I think the Chrome "appcache" is  the same that the Firefox "Offline Website Data". It seems the link you provided in your message propose a different way to clean these data. I will try this as the result may be different.

**Comment by Sneeuwtijger** [comment]
This is the French site - https://support.mozilla.org/fr/kb/api-de-stockage-des-sites-web-veulent-enregistrer-

**Comment by gizmocuz** [comment]
Could you try with a private browser windows ? (control-shift-n)
Also are you working behind a webserver proxy ? In this case, you need to proxy the websocket as well, see this wiki:

https://www.domoticz.com/wiki/WebServer_Proxy

**Comment by Allras82** [comment]
Ahh problem found, it's the proxy setup....
When i'm running local behind the proxy, it works :-)

**Comment by pepsi92** [comment]
Same for me, it works fine now after updating the webserver proxy settings.
Thanks !
