### ISSUE TITLE
Little problem but still some compile warning about Mosquito

### ISSUE THREAD

**Issue by aldodemi** [domoticz/domoticz#4048]
[ 79%] Built target libmosquitto
[ 79%] Building CXX object extern/mosquitto/lib/cpp/CMakeFiles/mosquittopp_static.dir/mosquittopp.cpp.o
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_connect_wrapper(mosquitto*, void*, int)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:27:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   27 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:27:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   27 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_connect_with_flags_wrapper(mosquitto*, void*, int, int)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:36:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   36 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:36:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   36 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_disconnect_wrapper(mosquitto*, void*, int)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:43:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   43 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:43:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   43 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_publish_wrapper(mosquitto*, void*, int)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:50:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   50 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:50:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   50 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_message_wrapper(mosquitto*, void*, const mosquitto_message*)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:57:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   57 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:57:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   57 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_subscribe_wrapper(mosquitto*, void*, int, int, const int*)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:64:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   64 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:64:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   64 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_unsubscribe_wrapper(mosquitto*, void*, int)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:71:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   71 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:71:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   71 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_log_wrapper(mosquitto*, void*, int, const char*)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:79:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   79 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:79:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   79 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
[ 80%] Linking CXX static library libmosquittopp_static.a
[ 80%] Built target mosquittopp_static
[ 80%] Building CXX object extern/mosquitto/lib/cpp/CMakeFiles/mosquittopp.dir/mosquittopp.cpp.o
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_connect_wrapper(mosquitto*, void*, int)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:27:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   27 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:27:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   27 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_connect_with_flags_wrapper(mosquitto*, void*, int, int)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:36:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   36 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:36:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   36 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_disconnect_wrapper(mosquitto*, void*, int)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:43:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   43 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:43:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   43 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_publish_wrapper(mosquitto*, void*, int)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:50:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   50 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:50:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   50 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_message_wrapper(mosquitto*, void*, const mosquitto_message*)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:57:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   57 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:57:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   57 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_subscribe_wrapper(mosquitto*, void*, int, int, const int*)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:64:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   64 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:64:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   64 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_unsubscribe_wrapper(mosquitto*, void*, int)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:71:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   71 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:71:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   71 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp: In function ‘void mosqpp::on_log_wrapper(mosquitto*, void*, int, const char*)’:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:79:21: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   79 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                     ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:79:44: warning: ‘mosquittopp’ is deprecated [-Wdeprecated-declarations]
   79 |  class mosquittopp *m = (class mosquittopp *)userdata;
      |                                            ^
In file included from /home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.cpp:19:
/home/domoticz/domoticz/extern/mosquitto/lib/cpp/mosquittopp.h:90:32: note: declared here
   90 | class mosqpp_EXPORT DEPRECATED mosquittopp {
      |                                ^~~~~~~~~~~
[ 80%] Linking CXX shared library libmosquittopp.so
[ 80%] Built target mosquittopp
[ 82%] Built target mosquitto_sub
[ 83%] Built target mosquitto_pub
[ 84%] Built target mosquitto_rr
[ 85%] Built target mosquitto_passwd
[100%] Built target mosquitto

**Comment by gizmocuz** [comment]
Yep, as you can see this is a warning, it is also deprecated, do when the people from mosquitto take it our of there source tree the message will stop
