### ISSUE TITLE
Blind switches in floorplans mode

### ISSUE THREAD

**Issue by peychart** [domoticz/domoticz#4054]
Version: 2020.1
Platform: RPi3
Device: RfxCom - RFXtrx433
My home page: https://github.com/peychart
Description: "Switch on" no longer work in floorplans mode since the 2020.1 version.

Hi,
Since upgrade to the last stable version, blinb switches type can not close (RTS) blinds anymore on the floorplans... only the opening (switch off) remains possible.
 
Blinds already opened (with correct status icon), switches send yet an open signal, not a close signal.

Only switches in popup remain ok and allow to switch on (close the blinds) or off properly... But, on tablets, using this popup is impractical, especially since the popup then remains open and the page, sometimes even zoomed, must be refreshed... :-(
(especially since my terminal is a 10" tablet with more than 40 devices displayed...)

Regards

**Comment by wouterlet** [comment]
I have the same issue. Next to that it would be nice if the stop status would also be available!
Keep up the good work!

**Comment by peychart** [comment]
Problem solved: I migrated under home-assistant (more possibilities) ... ;-)

**Comment by gizmocuz** [comment]
Glad you solved it
