### ISSUE TITLE
Thermostat setpoint cannot go to minus

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#4055]
I hope some one can make the Thermostat setpoint is going to minus.
Now only possible to 0 and + value.
For my heatpump i need minus value.

Hope there is a option..

**Comment by writeangle** [comment]
Is this for the purpose of setting the heating mode to a setpoint that's negative?

**Comment by Dylantje** [comment]
Could be.
And also for the shift option to set to -1 to -5

**Comment by Vincent835** [comment]
Hi, 
I need the same function in order to shift +/-5°C temperature target. 
Thank you

**Comment by gizmocuz** [comment]
@Dylantje , I don't understand, your 'heat pump' is for heating, why on earth do you need to send a value from 0 degrees or lower ?

**Comment by kiddigital** [comment]
> Hi, 
> 
> I need the same function in order to shift +/-5°C temperature target. 
> 
> Thank you 

Is this because the device does not want to receive an absolute value (positive and higher than say 0 or more) but expects a relative value to deviate from a given 'middle' value? What would be a logical range? Somewhere between -10 to +10?

Which Domoticz module do you use to control the device?

**Comment by Vincent835** [comment]
> Is this because the device does not want to receive an absolute value (positive and higher than say 0 or more) but expects a relative value to deviate from a given 'middle' value? What would be a logical range? Somewhere between -10 to +10?

For my heat pump, the room temperature setpoint is absolute.
But the water temperature is calculated automatically by the heat pump and can be adjusted by + or - 5 ° C.

> Which Domoticz module do you use to control the device?

I am writing a python plugin to monitor and configure my heat pump.
It is a DAIKIN ALTHERMA HT with an RTD-W modbus module.

The solution I found is a 11 level selector from -5 to + 5 ° C.

**Comment by gizmocuz** [comment]
Could you guys please stay on topic. Which is:

"Thermostat setpoint cannot go to minus"

**Comment by pipiche38** [comment]
I would tend to agree that having a Setpoint to - makes some sense. We might not have the use case right now, but why not having a connected fridge or icer where we have to setpoint to -25° !

**Comment by gizmocuz** [comment]
@pipiche38 , I am not aware of such device.
Of course you can convince me by supplying a link to a API that uses set points < 0 degrees

**Comment by vandermark1977** [comment]
I agree with the heatpump case: We shift the water outlet temperature from -5 to +5. It would be very useful if you can simply click down from zero te negative values in the thermostat.setpoint device.

**Comment by Vincent835** [comment]
Hi  Gizmocuz,

> @pipiche38 , I am not aware of such device.
> Of course you can convince me by supplying a link to a API that uses set points < 0 degrees

Because of the restriction on the thermostat setpoint device, here is what I had to do for my plugin: a switch selector device instead of a thermostat setpoint device. With all the problems converting levels (0 to 110) to offset value (-5 to +5).
![Switch selector +-5](https://user-images.githubusercontent.com/64158236/107695111-6fc29880-6cb0-11eb-8b4d-0d5b0e3b9c56.JPG)
https://github.com/Vincent835/Domoticz_DAIKIN_ALTHERMA_RTD-W

A thermostat set point with a negative value could solve this difficulty.

**Comment by BazemanKM** [comment]
I agree with the heatpump case: We shift the water outlet temperature from -5 to +5. It would be very useful if you can simply click down from zero te negative values in the thermostat.setpoint device.

**Comment by ajarzyn** [comment]
+1 from me I would like to use it with [luxtronic2 plugin:](https://github.com/ajarzyn/domoticz-luxtronic2).

Also would be good to set range, and step for one click of up/down arrow.

**Comment by gizmocuz** [comment]
I created a dummy Temperature Setpoint device, and set the value to -5, seems to work here...

![image](https://user-images.githubusercontent.com/2265299/145842266-3cbfff56-8673-43c3-b192-a6f71543c648.png)

**Comment by Vincent835** [comment]
Hi @gizmocuz ,
Cloud you set it with the down arrow? Or you set it with the "edit" menu?
![Set point](https://user-images.githubusercontent.com/64158236/145882043-7590a692-6ab5-4ebc-ad5f-9d34c90c9e73.PNG)
I would like to use the arrows but it doesn't work.
But, I'm agree, it works using the "edit" menu.

Thank you for this remark.

------------------------------------
À propos de Domoticz
Version: 2021.1
Build Hash: 8547c5b7e
Compile Date: 2021-04-17 17:29:11
dzVents Version: 3.1.7
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by ajarzyn** [comment]
> I created a dummy Temperature Setpoint device, and set the value to -5, seems to work here...

Reproduced your steps here.

It is true you can set it writting value directly into the text box, and then press press:
![image](https://user-images.githubusercontent.com/18590439/145955679-3a8b2505-7d98-4b56-86da-ff065edf30b5.png)

But then you have this javascript [domoticz.js](https://github.com/domoticz/domoticz/blob/development/www/js/domoticz.js#L5912)

```
function SetpointDown() {
	var curValue = parseFloat($('#setpoint_popup #popup_setpoint').val());
	curValue -= 0.5;
	curValue = Math.round(curValue / 0.5) * 0.5;
	if (curValue < 0) {
		curValue = 0;
	}
	var curValueStr = curValue.toFixed(1);
	$('#setpoint_popup #popup_setpoint').val(curValueStr);
}
```

which forbids us to go lower then 0 with an arrow.
I could create pull request for removing that `if (curValue < 0) {`, but I do not know if it would be acceptable solution.

I feel like `thermostat` device should give possibility to set range, and step size. Maybe it would be possible to use `Options` argument for that?
With that change it would be crucial to check this parameters in three functions:
`function SetpointUp() {`
`function SetpointDown() {`
`function SetSetpoint() {`

In my opinion it would be very nice feature.
 
@gizmocuz what is your opinion on that?

**Comment by kiddigital** [comment]
Indeed it would make the most sense if the Thermostat Setpoint device is able to provide a MinValue, MaxValue and optional stepSize to the front-end. Range could than be for example from +15 to +25 (step size 0.5) or from -5 to +5 (stepsize 1), etc. 

The call `json.htm?type=devices&filter=temp&used=true` should return these values for the UI to use (= step 1).

Step 1. would be the check if/how/where we can store these values and return them in the API call.
Step 2. figure out where/how should we be able to set the range/stepsize as they could be different per (thermostat/setpoint) 'device' and not on 'hardware' settings level
Step 3. would be for the UI to use these in the 'ShowSetpointPopup' function and in the actual Popup Window

**Comment by gizmocuz** [comment]
@ajarzyn , for now, you could make a PR that allows the down arrow to go below zero.
That should solve this issue ?

At a later stage, or another PR, a range and step size could indeed be usefull

**Comment by waltervl** [comment]
Implemented

**Comment by ajarzyn** [comment]
@waltervl what do you mean that's implemented? The whole solution or just temporary bottom limit removal?

If you meant the latter I would like to suggest to open "proposition" or "feature request" to not forget that there are additional action items as described by @kiddigital comment above.

**Comment by waltervl** [comment]
The issue that setpoint cannot go below 0 is solved. If you would like another feature request you are free to ask or even better to build it yourself and make a pull request.
