### ISSUE TITLE
Improve scaling of graphs

### ISSUE THREAD

**Issue by Antori91** [domoticz/domoticz#4059]
Hello Domoticz team,
Graph scaling is not good at all. Is there any way to improve it. 
For details about this from a user perspective, see   https://www.domoticz.com/forum/viewtopic.php?f=31&t=27673

**Comment by gizmocuz** [comment]
@Antori91 , feel free to make adjustments and create a PR

**Comment by Antori91** [comment]
Hello Gizmocuz, 
Many thanks for your quick answer. I'm going to open a PR.

**Comment by Antori91** [comment]
Hello Gizmocuz, Many thanks for your quick answer. I understand that you are inviting me to do the change. But, I don't know the Domoticz source code. It's a little too difficult for me.

**Comment by waltervl** [comment]
In latest stable 2022.1 this issue is fixed.
