### ISSUE TITLE
make install chokes

### ISSUE THREAD

**Issue by rkluwen** [domoticz/domoticz#4061]
When I do a fresh installation from the development tree, compile and then run "sudo make install", then I get:

CMake Error at extern/mosquitto/man/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/home/pi/domoticz/extern/mosquitto/man/mosquitto_passwd.1": No such file
  or directory.
Call Stack (most recent call first):
  extern/mosquitto/cmake_install.cmake:62 (include)
  cmake_install.cmake:47 (include)

make: *** [Makefile:91: install] Error 1

**Comment by rkluwen** [comment]
Besides that, if I compile openzwave and then install it.
And after that, I remove the original open-zwave-readonly folder, cmake cannot found the openzwave libraries.

**Comment by gizmocuz** [comment]
You should not need to do a make install... did it ever worked ?

You need to leave the OpenZWave folder because when issuing 'sudo make install' , openzwave does not install the static library.
I do not know why this is, but that is the reason you have to leave it

You could checkout domoticz to the folder where you want to use it... 

As always, please follow this guide

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by gizmocuz** [comment]
@rkluwen, refactored the (quick) above answer a bit

**Comment by rkluwen** [comment]
We could make openzwave a module in the extern/ folder, or?

**Comment by niziak** [comment]
> "/home/pi/domoticz/extern/mosquitto/man/mosquitto_passwd.1": No such file

Similar error on PC. It was working with 2020.1. From uknown reason man files in `extern/mosquitto/man` are not generated. Invoking `make` in `extern/mosquitto` solves problem. After this `sudo make install` works.

**Comment by gizmocuz** [comment]
@rkluwen , yes we could do this ... feel free to make a patch
Then maybe also patch the makebeta/release scripts to use the config folder from the extern/ folder, but do take care that Domoticz has been using a capital C letter at the start, can't change it now or we have to make a code patch for this as well, and a cleanup (sqlhelper.cpp version change)

**Comment by gizmocuz** [comment]
@niziak , we do not need the man files with make install, maybe there is more installed then domoticz ?
