### ISSUE TITLE
Xiaomi Temp Sensor WTGR800 not updated LaCrosse are

### ISSUE THREAD

**Issue by sincze** [domoticz/domoticz#4064]
Running Domoticz 2020.1

I noticed something interesting. 
![image](https://user-images.githubusercontent.com/5776333/78927211-c367c280-7a9e-11ea-9fac-3dc2f3ec42d0.png)

Í've several XIAOMI temp sensors around the house and want to receive battery warnings if they are low. 1 temp sensor will create 4 Domoticz sensors if paired via XIAOMI Gateway. 

The WTGR800 is the one I'm interested in as that one shows me **TEMP + HUMID + Battery**.

I noticed that this WTGR800 device is not updated regularly, however the LaCrosses' TX3 are!
Unfortunately the LaCrosse does not show the TEMP + HUMID + **Battery**.

**Comment by gizmocuz** [comment]
@sincze , Best to look in the code, but it seems that the humidity is not always transmitted
If that is the case, it is best to keep a record internally if a sensor did include temp/hum/baro, and in this case use the last send values with the new received value
(So store a structure with type,temp,hum,baro , and when only the temp is send/updated, use the stored hum/baro value to update the temp+hum+baro sensor ... if the type=temp+hum+baro)

**Comment by sincze** [comment]
Thinking "outside the temp humid sensor box, with your assumption in my head. 
We could modify the code to just update the Lacrosse Temp / Humid Sensor by adding the Battery value if that is updated somewhere else.  Seems simpler?

**Comment by gizmocuz** [comment]
Depends, are there temp only sensors ? or humidity/baro only sensors ?
It might be a good idea to enable some logging to see what is coming in.. if it is always temp+hum, or that sometimes the humidity is not provided

**Comment by sincze** [comment]
Mmm interesting indeed.
To my knowledge only temp + humid sensors and the following can be found if log is enabled:

```
2020-04-10 18:31:22.704 Status: {"cmd":"report","model":"sensor_ht","sid":"158d00020eead3","short_id":54340,"data":"{\"temperature\":\"2431\"}"}
2020-04-10 18:31:22.725 Status: {"cmd":"report","model":"sensor_ht","sid":"158d00020eead3","short_id":54340,"data":"{\"humidity\":\"3312\"}"}
2020-04-10 18:31:22.754 Status: {"cmd":"heartbeat","model":"sensor_ht","sid":"158d00020eead3","short_id":54340,"data":"{\"voltage\":3225,\"temperature\":\"2431\",\"humidity\":\"3312\"}"}}
2020-04-10 18:48:10.709 Status: {"cmd":"report","model":"sensor_ht","sid":"158d00034d4410","short_id":9314,"data":"{\"temperature\":\"3014\"}"}
2020-04-10 18:48:10.786 Status: {"cmd":"report","model":"sensor_ht","sid":"158d00034d4410","short_id":9314,"data":"{\"humidity\":\"2383\"}"}
2020-04-10 18:48:10.828 Status: {"cmd":"heartbeat","model":"sensor_ht","sid":"158d00034d4410","short_id":9314,"data":"{\"voltage\":3005,\"temperature\":\"3014\",\"humidity\":\"2383\"}"}

```
Seems all values are present.
I also checked the original French site: 
![image](https://user-images.githubusercontent.com/5776333/79007515-99c0a100-7b5b-11ea-90c9-81450412a104.png)
[Site](http://domo-attitude.fr/xiaomi-smart-home-presentation-inclusion-domoticz/)

From the code I would say it's okay? 
But remember.. I am not a developer, or the sID< 0 ..... sometimes..

```
void XiaomiGateway::InsertUpdateTempHum(const std::string &nodeid, const std::string &Name, const float Temperature, const int Humidity, const int battery)
{
	unsigned int sID = GetShortID(nodeid);
	if (sID > 0) {
		SendTempHumSensor(sID, battery, Temperature, Humidity, Name);
	}
}
```

probably need to go through:
```
void XiaomiGateway::xiaomi_udp_server::handle_receive(const boost::system::error_code & error, std::size_t bytes_recvd)
```
![image](https://user-images.githubusercontent.com/5776333/79015887-017fe780-7b6e-11ea-9bf7-40f5cd20a82a.png)

**Comment by sincze** [comment]
As I was unable to see any strange things in the code except for the temp sensor always having 100% battery which seems logical if no 'voltage' value is received it remains 255 by default.:

```
	int battery = 255;
					if (voltage != "" && voltage != "3600") {
						battery = ((atoi(voltage.c_str()) - 2200) / 10);
					}
```

I went back to Domoticz... 
To discover.... this
![image](https://user-images.githubusercontent.com/5776333/79016474-5e2fd200-7b6f-11ea-9fee-e96393357654.png)

All TEMP+HUMID sensors happily in sync. What do you know..

**Comment by gizmocuz** [comment]
so there is no issue ?

**Comment by sincze** [comment]
Checked again today. All values are still the same.
![image](https://user-images.githubusercontent.com/5776333/79073156-411d0f80-7ce5-11ea-86e5-40aaa7bbace9.png)

Battery value of Lacrosse Temp is faulty but that was not the issue I reported..
