### ISSUE TITLE
Switches properties cog always asks for protection password (i.e. Somfy RFY)

### ISSUE THREAD

**Issue by mlstolk** [domoticz/domoticz#4065]
In the latest beta versions, including 2020.1 (build 11930), the options cog icon in the top-right corner of a switch (Somfy RFY shutter), now always shows the dialog "Please enter password", even when there is no password set.

I have tried:
- Clearing the "Light/Switch Protection" password at the Settings page. After applying, this results in showing a filled-in (masked) password field on the Settings page; the switch's device properties popup remains inaccessible because it prompts for a password.
- Setting a password. Undesirable, but now I can indeed enter that password and see the desired popup menu.
- Nulling the value in the ProtectionPassword row of the domoticz database. Still asks for a password.

**Comment by GravityRZ** [comment]
can confirm this.(why should a password be needed)
switches luckily seem to work
i am on 2020.1 build  11839 so this happened some time before

**Comment by gizmocuz** [comment]
Corrected in next update
