### ISSUE TITLE
Updating Domoticz on Windows, then Domoticz fails to start

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#4068]
Domoticz won't start on my Win Install (run as service) after updating from "older" betas 4.11779 --> 2020.1.11932.

![bild](https://user-images.githubusercontent.com/21274628/79039695-5f024b80-7be3-11ea-8bf1-e77b05915710.png)

I tested and failed on both a Win7 and Win10 system running previous betas like mentioned, however a frequently beta-updated Win10 system (my main Domoticz install) I managed to update to 2020.1.11932 without any issue.

**Comment by gizmocuz** [comment]
Could you try to install Domoticz as an application and launch this to see if this gives a better error message ?
It could be that there are some missing DLL's

**Comment by sledgemhammer** [comment]
Same issue will share my findings for diagnostics : 
This error is due to mosquitto.dll missing. As soon as you put mosquitto.dll in the domoticz directory the error is changed, but domoticz still refuse to start. (at my system)
Installing the redistributions of mosquite software (both x64 and x84) did not solve the problem.

**Comment by RicardP** [comment]
As @sledgemhammer I get the same "missing mosquitto.dll" when running in application. However I did not try further for now.

**Comment by gizmocuz** [comment]
Thanks, I figured it out, hope to have a sollution soon

**Comment by gizmocuz** [comment]
Still struggling with it, you can checkout the win32 repo and find the dll's in here, but hope to get appveyor working again soon

**Comment by gizmocuz** [comment]
There is a new installer available, hope this one works (manual build/upload)

**Comment by PHIL-IP** [comment]
> 
> 
> There is a new installer available, hope this one works (manual build/upload)

Hi, 
I had that problem, too but now with the last version installed all seems looks good :)
Thanks

**Comment by sledgemhammer** [comment]
Confirmed domoticz starts normal now ( application and as service)  with latest download
2020.1.11940.

Thank you so much !

**Comment by RicardP** [comment]
Same here, works on all three win systems now :) Many thanks for everything @gizmocuz :)
