### ISSUE TITLE
Ubuntu make fails with "Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)"

### ISSUE THREAD

**Issue by HoekieN** [domoticz/domoticz#4070]
When i try to upgrade from version:
Version: 2020.1 (build 11856)
Build Hash: 835fd0168-modified
Compile Date: 2020-04-02 00:13:54
dzVents Version: 3.0.2
Python Version: 3.6.9 (default, Nov 7 2019, 10:44:02) [GCC 8.3.0]

to the current beta i get the following error:

ubuntu@ubuntu:~/dev-domoticz$ make
-- Submodule update
Submodule 'extern/jsoncpp' (https://github.com/open-source-parsers/jsoncpp.git) registered for path 'extern/jsoncpp'
Submodule 'minizip' (https://github.com/domoticz/minizip.git) registered for path 'extern/minizip'
Submodule 'extern/mosquitto' (https://github.com/eclipse/mosquitto.git) registered for path 'extern/mosquitto'
Submodule 'extern/sqlite-amalgamation' (https://github.com/azadkuh/sqlite-amalgamation.git) registered for path 'extern/sqlite-amalgamation'
Cloning into '/home/ubuntu/dev-domoticz/extern/jsoncpp'...
Cloning into '/home/ubuntu/dev-domoticz/extern/minizip'...
Cloning into '/home/ubuntu/dev-domoticz/extern/mosquitto'...
Cloning into '/home/ubuntu/dev-domoticz/extern/sqlite-amalgamation'...
Submodule path 'extern/jsoncpp': checked out '3beb37ea14aec1bdce1a6d542dc464d00f4a6cec'
Submodule path 'extern/minizip': checked out 'f5282643091dc1b33546bb8d8b3c23d78fdba231'
Submodule path 'extern/mosquitto': checked out '22e0a4ba9bd6b0ce0f430638a54e6d9d1ca4af59'
Submodule path 'extern/sqlite-amalgamation': checked out 'cd945465998165e6ec5dbb302cda29723927fe84'
CMake Error at /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR) (Required is at
  least version "5.3")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.16/Modules/FindLua.cmake:231 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:402 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/dev-domoticz/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/dev-domoticz/CMakeFiles/CMakeError.log".
Makefile:7688: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1

Ubuntu version:
ubuntu@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

**Comment by gizmocuz** [comment]
You have to follow this guide:

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

do not the extra packages that are installed (apt-get)

**Comment by HoekieN** [comment]
My mistake, i did not notice the page had some update's.
It is works now :)
