### ISSUE TITLE
import requests from domoticz python not working

### ISSUE THREAD

**Issue by jvberlo** [domoticz/domoticz#4071]
when using a python script within domoticz you get a error when you try "import requests" using the script directly in python3 or sudo python3 works fine. Then import requests works.

**Comment by rwaaren** [comment]
Did you also post this question on the forum? You will reach a much wider audience and maybe some of the forum members have seen this behavior before and can help.

**Comment by jvberlo** [comment]
Thanks for tour response.

Yes I did create a post on the forum (https://www.domoticz.com/forum/viewtopic.php?f=28&t=32073).

But i think it is a bug. Even in a clean install it is not working.

**Comment by waltervl** [comment]
No further response, closing this issue.
