### ISSUE TITLE
Error: MQTT: disconnected, restarting (rc=7)

### ISSUE THREAD

**Issue by Spyky** [domoticz/domoticz#4075]
#3750 #3793
Hello, since a few weeks i have the same issue Error: MQTT: disconnected, restarting (rc=7)
There is a lot of reading int he issuses #3750 #3793. But it is not clear to me how to resolve this error.

I update today to the latest version of domoticz and to buster in the hope it will solve something, but still get every 10 seconds this error.

Hope you can help.

**Comment by rwaaren** [comment]
Does MQTT work at all in your system
What is your current version of domoticz.
What hardware platform do you use
What do you use as settings for MQTT on the hardware tab
Do you have > 1 domoticz systems connected to MQTT
Do you have > MQTT modules on the hardware tab

**Comment by Spyky** [comment]
Does MQTT work at all in your system
. Yes it worked for more then a year ok
What is your current version of domoticz.
. Was stretch moved this weekend to raspian in the hope it would solve the
problem
What hardware platform do you use
. Raspberry 3b
What do you use as settings for MQTT on the hardware tab
. Ipadres username password
Do you have > 1 domoticz systems connected to MQTT
. More than 1
Do you have > MQTT modules on the hardware tab
. I had 3 modules. Yesterday I changed it 2 one and it worked better.

So the problem looks solved. Strange that it worked this way for more than
a year. It still worked, but the errors where written to the log.


Op ma 20 apr. 2020 21:27 schreef rwaaren <notifications@github.com>:
