### ISSUE TITLE
Philips Hue Bulb incorrectly identified as switch only device instead of dimmable device

### ISSUE THREAD

**Issue by solfred** [domoticz/domoticz#4080]
Hi, 
Domoticz configuration:
Version: 2020.1.11804
Platform: Raspberry PI3B+ / Debian Buster

I own a Philips Hue starter kit, which contains a bridge & 2 white lamps.
Domoticz has added the lamps as Light/Switch instead of dimmer.

2020-04-15 14:25:05.718 (Philips Hue) **Light/Switch** (Hue white lamp 1)

But the lamps are dimmable, as shown when calling the API:
"modelid": "LWB010",
"productid": "Philips-LWB010-1-A19DLv4",
"productname": "Hue white lamp",
"swversion": "1.50.2_r30933",
"type": "**Dimmable light**",

Domoticz json API returns **"DimmerType" : "none"**, but it is possible using this API to change the brightness of the lamps. On the other hand, dzVents does not allow dimTo or setLevel methods.
In Domoticz interface, changing the device from switch to dimmer solve the issue.
But at the first place, Domoticz should have detected that the lamp were dimmable. 

Regards

**Comment by gizmocuz** [comment]
@solfred , when you go to the switches tab and press 'edit' on the switch, you can set the type to 'dimmer'

**Comment by solfred** [comment]
Hi, 
Yes waaren has helped me on this :-) . 
But as the device is dimmable, Domoticz should detect it and configure it as dimmable not as a light/switch.  I have also a Xiaomi gateway that was correctly identified as RGBW, dimmer. So it should be the same for these hue bulbs. This was rather confusing for me as I was not supposed to change the type of this device. My assumption was: if Domoticz detects this device as a switch, so it is a switch. Moreover this is a very common Philips hue device not an exotic device so I supposed that it was widely used by Domoticz users, In my idea it was more a dzVents bug as the json API was capable to dim the light. 

Best regards
Fred

**Comment by gizmocuz** [comment]
@solfred , that's correct... I looked at the code, and when the API/JSON output has a "bri" (brightness) field, it should be flagged as a dimmer

https://github.com/domoticz/domoticz/blob/52674382e7970d0333eb1e1e04d56bf9a151dd51/hardware/PhilipsHue/PhilipsHue.cpp#L790

Could you check or post the "lights" / "state" part of this lamp ?

**Comment by solfred** [comment]
>

> 
> 
> @solfred , that's correct... I looked at the code, and when the API/JSON output has a "bri" (brightness) field, it should be flagged as a dimmer
> 
> https://github.com/domoticz/domoticz/blob/52674382e7970d0333eb1e1e04d56bf9a151dd51/hardware/PhilipsHue/PhilipsHue.cpp#L790
> 
> Could you check or post the "lights" / "state" part of this lamp ?

Output from Philips native API:

{
  "state": {
    "on": true,
    "bri": 254,
    "alert": "select",
    "mode": "homeautomation",
    "reachable": true
  },
  "swupdate": {
    "state": "noupdates",
    "lastinstall": "2020-04-04T13:41:50"
  },
  "type": "Dimmable light",
  "name": "Lampe 1",
  "modelid": "LWB010",
  "manufacturername": "Signify Netherlands B.V.",
  "productname": "Hue white lamp",
  "capabilities": {
    "certified": true,
    "control": {
      "mindimlevel": 2000,
      "maxlumen": 806
    },
    "streaming": {
      "renderer": false,
      "proxy": false
    }
  },
  "config": {
    "archetype": "classicbulb",
    "function": "functional",
    "direction": "omnidirectional",
    "startup": {
      "mode": "safety",
      "configured": true
    }
  },
  "uniqueid": "00:17:88:01:02:cf:6e:aa-0b",
  "swversion": "1.50.2_r30933",
  "swconfigid": "754CE4FC",
  "productid": "Philips-LWB010-1-A19DLv4"
}

**Comment by gizmocuz** [comment]
@solfred , this looks correct, and in 'CPhilipsHue::LightStateFromJSON' it should have been set to HLTYPE_DIM
Could you verify this by adding some logging in the code ?
If not, could you send me a PM on the Forum...
