### ISSUE TITLE
Aqara opple switch long press event

### ISSUE THREAD

**Issue by michi1g** [domoticz/domoticz#4081]
Hi!
I just got my Aqara Opple switch (4 button version WXCJKG12LM) I have implemented them through deconz-rest-api and I get websocket events. I want to be able to use one pair of buttons for dimming my lights. 
When long pressing the button I get the following websocket log:

>  ### WebSocket Data : {'e': 'changed', 'id': '40', 'r': 'sensors', 'state': {'buttonevent': 3001, 'lastupdated': '2020-04-16T10:16:46.052'}, 't': 'event', 'uniqueid': '04:cf:8c:df:3c:79:19:39-01-0012'}

where 3001 is button 3 and long press is 001. A short press results in 3002, double click 3004

My problem: 3001 isn't recognized as a state in domoticz. I was thinking to use something like:
`while state == 3001 brightness++ light.dimTo(brightness)`

The switch is recognized as a selector switch with B1-B8. This switch would be able to have 3 states for each button (click, double click, long click)
How would I have to implement it correctly?

I would appreciate any help!

**Comment by rwaaren** [comment]
> I would appreciate any help!

Not clear from the description if this a code bug. If not please close this issue and ask the question on the forum in an appropriate subforum

**Comment by michi1g** [comment]
Don't know if it's a bug or just a feature request.
The switch should be recognized as a 12 option selector (click, double click, long click) it is shown as 8 option selector and long click isn't recognized by domoticz.
Websocket msg is sent by deconz-rest-api as posted above

**Comment by Smanar** [comment]
@michi1g 
Hello, this problem is not from Domoticz but from the deconz plugin.

You have already an issue for this device here https://github.com/Smanar/Domoticz-deCONZ/issues/46

On this github, you have a beta version for this device with better support, but ATM we are waiting for deconz Version 2.05.76, the previous have some problem with the device (except if you compile yourself the code)

**Comment by michi1g** [comment]
@Smanar 
I have compiled the beta myself and have the switch working. It just isn't recognized correctly in domoticz

**Comment by Smanar** [comment]
Are you trying the beta version of the plugin ?
Because the widget will be 
>kwarg['Options'] = {"LevelActions": "|||||||||||||||||", "LevelNames": "Off|B1|B2|B3|B4|B5|B6|B1L|B2L|B3L|B4L|B5L|B6L|B1D|B2D|B3D|B4D|B5D|B6D", "LevelOffHidden": "true", "SelectorStyle": "1"}

You have more than just B1 > B8.

Anyway, the code haven't been tested with last compiled version, so I think it still need adjustment.

**Comment by waltervl** [comment]
Plugin issue and fixed so closed
