### ISSUE TITLE
Buienradar

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4083]
Starting april 16th around midnight, Buienradar does return 0,0 for lat,lon location of the weatherstation when called using [the URL used in Buienradar.cpp](https://data.buienradar.nl/2.0/feed/json) 

See this [forum topic](https://www.domoticz.com/forum/viewtopic.php?f=6&t=32214) for more details.

It's reported to buienradar but until they respond to that we don't know if this is a temporary issue on there side or a changed policy that will not be changed back.
If the latter we need to change the way we get the weatherstation closest to the calling systems location. Hopefully it is not needed but if so below table might be of some use. Stations on this list are verified and operational except Hoofdplaat which seems to be down
 
```
Station	lat,	lon	location
===============================
6215	52.12,04.43 Voorschoten
6225	52.47,04.57 IJmuiden
6229	53.00,04.75 Texelhors
6235	52.92,04.78 Den Helder
6239	54.85,04.73 Zeeplatform F-3"
6240	52.30,04.77 Schiphol
6242	53.25,04.92 Vlieland
6248	52.63,05.17 Wijdenes
6249	52.65,04.98 Berkhout
6251	53.38,05.35 Hoorn Terschelling
6252	53.22,03.22 Zeeplatform K13
6257	52.50,04.60 Wijk aan Zee
6258	52.65,05.40 Houtribdijk
6260	52.10,05.18 De Bilt
6267	52.88,05.38 Stavoren
6269	52.45,05.53 Lelystad
6270	53.22,05.77 Leeuwarden
6273	52.70,05.88 Marknesse
6275	52.07,05.88 Arnhem
6277	53.42,06.20 Lauwersoog
6278	52.43,06.27 Heino
6279	52.73,06.52 Hoogeveen
6280	53.13,06.58 Groningen
6283	52.07,06.65 Groenlo-Hupsel
6285	53.57,06.40 Huibertgat
6286	53.20,07.15 Beerta
6290	52.27,06.90 Twente
6308	51.38,03.38 Cadzand
6310	51.45,03.60 Vlissingen
6311	51.37,03.66 Hoofdplaat     -- Down
6312	51.46,03.62 Oosterschelde
6313	51.50,03.25 Vlakte aan de Raa
6315	51.45,04.00 Hansweert
6316	51.65,03.70 Schaar
6319	51.23,03.83 Westdorpe
6320	51.93,03.67 LE Goeree
6321	52.00,03.28 Euro platform
6323	51.53,03.90 Goes
6324	51.60,04.00 Stavenisse
6330	51.98,04.10 Hoek van Holland
6331	51.52,04.13 Tholen
6340	51.45,04.33 Woensdrecht
6343	51.88,04.32 Rotterdam Geulhaven
6344	51.95,04.45 Rotterdam
6348	51.97,04.93 Lopik-Cabauw
6350	51.57,04.93 Gilze Rijen
6356	51.87,05.15 Herwijnen
6370	51.45,05.42 Eindhoven
6375	51.65,05.70 Volkel
6377	51.20,05.77 Ell
6380	50.92,05.78 Maastricht
6391	51.50,06.20 Arcen	 	.
```

**Comment by GravityRZ** [comment]
since buienradar is not that trusty i would vote for a manual/automatic station choice input field

while we are at it, also delete those error messages we have no use for. stop logging them
because of all those useless messages flooding the log i did not even notice anymore that buienradar was not working(because i do not bother to check te logs anymore)

if this is not proof  to get rid of them then i do not know what is.

not usefull

```
2020-04-17 09:12:39.537 Error: BuienRadar: Error getting http data! (Check your internet connection!)
2020-04-17 01:32:50.690 Error: Buienradar hardware (9) thread seems to have ended unexpectedly

```

usefull(this is the first usefull error message i noticed from buienradar
`2020-04-17 10:58:04.475 Error: BuienRadar: No (nearby) station found!`

**Comment by rwaaren** [comment]
> while we are at it, also delete those error messages we have no use for. stop logging them
> because of all those useless messages flooding the log i did not even notice anymore that buienradar was not working(because i do not bother to check te logs anymore)

Can you please stop moaning about this.  Your opinion is now quite known to the whole domoticz community.

**Comment by GravityRZ** [comment]
point taken.

**Comment by rwaaren** [comment]
Buienradar restored it's service to provide lat/lon  of the weatherstations
