### ISSUE TITLE
MQTT domoticz\out - don't publish change status for Milight Swich 

### ISSUE THREAD

**Issue by laurentiugrama** [domoticz/domoticz#4086]
Hi,
Till last week I used an old version of domoticz (autumn 2019). 
I upgrade to the last beta 11944 (raspberry) and I found that when I change the status for a Milight switch the information is not published on MQTT domoticz/out queue.
Can you tell me where in code this action is triggered in order to search for the problem?

**Comment by rwaaren** [comment]
>Milight switch the information is not published on MQTT domoticz/out queue.

Please search before posting 
[Forum post](https://www.domoticz.com/forum/viewtopic.php?f=6&t=31711)
[Closed issue](https://github.com/domoticz/domoticz/issues/3863)
