### ISSUE TITLE
Saving settings is broken in the 2020.1 update

### ISSUE THREAD

**Issue by mooninite** [domoticz/domoticz#4087]
Domoticz 2020.1
Fedora 31 x86_64

I'm getting a 404 from https://server.com:8443/storesettings.webem and settings are not saving.

An strace shows that the Domoticz handling of 'webem' files is not working.

    [pid 1728877] openat(AT_FDCWD, "/usr/share/domoticz/www/storesettings.webem", O_RDONLY) = -1 ENOENT (No such file or directory)
    [pid 1728877] openat(AT_FDCWD, "/usr/share/domoticz/www/storesettings.webem.gz", O_RDONLY) = -1 ENOENT (No such file or directory)

This is my startup command:

    /usr/bin/domoticz -www 0 -sslwww 8443 -sslcert /var/lib/domoticz/domoticz.pem -sslpass -sslmethod -ssloptions -ssldhparam -wwwroot /usr/share/domoticz/www -dbase /var/lib/domoticz/domoticz.db -userdata /var/lib/domoticz/ -log /var/log/domoticz.log -loglevel 2

**Comment by gizmocuz** [comment]
No issues here, did you clear your browser cache + appcache ? Two differrent things

**Comment by mooninite** [comment]
It is cache related. It's unfortunate that the cache is marked to live forever.

The new URL doesn't use the .webem suffix, which would have been a clue my cache is out of date. Thanks.

**Comment by gizmocuz** [comment]
@mooninite , thank you for the feedback.
Next time please take time to follow our issue guideline

* Clear your browser cache + AppCache (two different things!!)
