### ISSUE TITLE
Exception in MySensorsBase::SendSensor2Domoticz()

### ISSUE THREAD

**Issue by bmellink** [domoticz/domoticz#4088]
The MySensorsBase::SendSensor2Domoticz() function generates an exception due to a null pointer around line 990 in hardware/MySensorsBase.cpp where vType == V_FORECAST. The following code

```
		if (pSensorBaro)
			{
				float Baro;
				if (pSensorBaro->GetValue(V_PRESSURE, Baro))
				{
					int forecast = intValue;
					if (forecast == bmpbaroforecast_cloudy)
					{
						if (Baro < 1010)
							forecast = bmpbaroforecast_rain;
					}
					SendBaroSensor(pSensorBaro->nodeID, pSensorBaro->childID, pSensorBaro->batValue, Baro, forecast, (!pChild->childName.empty()) ? pChild->childName : "Baro");
				}
			}
			else
			{
				if (pChild->GetValue(V_FORECAST, stringValue))
				{
					std::string devname = (!pChild->childName.empty()) ? pChild->childName : "Forecast";
					SendTextSensor(pSensorBaro->nodeID, pSensorBaro->childID, pChild->batValue, stringValue, devname);
				}
```
The else clause (with pSensorBaro==null) still uses pSensorBaro->nodeID. This will generate an exception which will crash domoticz. I fixed the code as follows:

```

			if (pSensorBaro)
			{
				float Baro;
				if (pSensorBaro->GetValue(V_PRESSURE, Baro))
				{
					int forecast = intValue;
					if (forecast == bmpbaroforecast_cloudy)
					{
						if (Baro < 1010)
							forecast = bmpbaroforecast_rain;
					}
					SendBaroSensor(pSensorBaro->nodeID, pSensorBaro->childID, pSensorBaro->batValue, Baro, forecast, (!pChild->childName.empty()) ? pChild->childName : "Baro");
				}
			}
			else
			{
				_tMySensorChild *pSensorForecast = FindChildWithValueType(pChild->nodeID, V_FORECAST, pChild->groupID);
				if (pSensorForecast && pChild->GetValue(V_FORECAST, stringValue))
				{
					std::string devname = (!pChild->childName.empty()) ? pChild->childName : "Forecast";
					SendTextSensor(pSensorForecast->nodeID, pSensorForecast->childID, pChild->batValue, stringValue, devname);
				}

```
Please modify the code in MySensorsBase.cpp as I do not seem to be able to push the git repo myself

**Comment by gizmocuz** [comment]
@bmellink , thanks for spotting. Please for our project to your private account, check this out, make the modification, push it back.
If you now go to the fork on your account, you should see a green button to compare/create a pull request, if you do this, we can merge this
pSensorBaro should be pChild there

**Comment by bmellink** [comment]
added pull request as https://github.com/domoticz/domoticz/pull/4091 
I hope I used the right procedure to enter the pull request

**Comment by gizmocuz** [comment]
Thank you for the PR, looking good (as PR)
But should the fix not be to only use pChild-> instead of pSensorBaro-> ?

So this is the only change:

`SendTextSensor(pChild->nodeID, pChild->childID, pChild->batValue, stringValue, devname);`

**Comment by bmellink** [comment]
I spotted the error because my sensors created random data due to a hardware malfunction. I do not have a sensor of the exact type that is used to handle this code. So you might be right the change is limited to 

`SendTextSensor(pChild->nodeID, pChild->childID, pChild->batValue, stringValue, devname);
`
In order to fix the null pointer I looked at the way the other sensors handle this type of child sensor and copied that code. I will need to create a sensor of this specific type to be 100% sure. I will look into this. Until then we should fix the null pointer exception anyway. What do you want to do?

**Comment by gizmocuz** [comment]
@bmellink , could yo make the patch with 'pChild' only ?

**Comment by gizmocuz** [comment]
I applied the patch directly, thanks for reporting!
