### ISSUE TITLE
Defining HeartBeat

### ISSUE THREAD

**Issue by yoFra** [domoticz/domoticz#4092]
I currently develop a plugin for Tuya devices.
I found a strange thing when using `Domoticz.HeartBeat()` :
Despite defining different heartbeats for each hardware, all heartbeats fire 10 seconds later.

With the code bellow, i give the following log :

2020-04-22 08:44:38.399 (Pr03) Leaving onStart. 1st heartbeat in **18s**
2020-04-22 08:44:38.549 (Pr05) Leaving onStart. 1st heartbeat in **14s** 
2020-04-22 08:44:38.701 (Pr04) Leaving onStart. 1st heartbeat in **19s**
2020-04-22 08:44:38.864 (Sèche linge) Leaving onStart. 1st heartbeat in **10s**
2020-04-22 08:44:39.068 (Machine à laver) Leaving onStart. 1st heartbeat in **16s**

2020-04-22 08:44:**48**.738 Status: (Pr03) Device added to DomoticzTuyaManager
2020-04-22 08:44:**48**.768 Status: (Machine à laver) Device added to DomoticzTuyaManager
2020-04-22 08:44:**48**.797 Status: (Pr04) Device added to DomoticzTuyaManager
2020-04-22 08:44:**48**.824 Status: (Sèche linge) Device added to DomoticzTuyaManager
2020-04-22 08:44:**48**.852 Status: (Pr05) Device added to DomoticzTuyaManager 

```python
    def onStart(self):
        # do my stuff ... ending with
        # on les étale de manière aléatoire sur la période de 10 secondes
        #   pour éviter une charge toutes les 10 secondes
        self.firstHeartBeat = 10 + random.randint(0,9)
        Domoticz.Heartbeat(self.firstHeartBeat)
        Domoticz.Log('Leaving onStart. 1st heartbeat in {}s'.format(self.firstHeartBeat))
        
   def onHeartbeat(self):
        # On fixe ensuite le heartbeat à 10s
        if ( self.firstHeartBeat != 10 ):
            self.firstHeartBeat = 10
            Domoticz.Heartbeat(self.firstHeartBeat)
        Domoticz.Status('Device added to DomoticzTuyaManager')
        # then other stuff ...
```

**Comment by yoFra** [comment]
Sorry.
I forgot mention that i use Domoticz v2020.1 on a Raspberry Pi 2 Model B Rev 1.1

**Comment by pipiche38** [comment]
My 2 cents

- Heartbeat is by default fired every 10s
- Heartbeat fire could be impacted by blocking requests in your plugin code
- My understanding is that that Hearbeat MUST be defined once at plugin start, before the first onHearbeat call
- By experience using random is quiet hazardous, I found several cases where random module is making Domoticz to crash

**Comment by yoFra** [comment]
>     * Heartbeat is by default fired every 10s
OK
>     * Heartbeat fire could be impacted by blocking requests in your plugin code
Normal
>     * My understanding is that that Hearbeat MUST be defined once at plugin start, before the first onHearbeat call
That's what i've done onStart and then set it back to 10 sec at first Heartbeat
>     * By experience using random is quiet hazardous, I found several cases where random module is making Domoticz to crash
No crash encountered

**Comment by pipiche38** [comment]
> > * By experience using random is quiet hazardous, I found several cases where random module is making Domoticz to crash
> > ```
> 
> No crash encountered

Platform dependent from what I see

**Comment by pipiche38** [comment]
Are  you sure you can do that . l Domoticz.Heartbeat() inside the onHeartbeat call back !
