### ISSUE TITLE
Wrong KWh measurement from Qubino Smart Meter

### ISSUE THREAD

**Issue by mantoz** [domoticz/domoticz#4093]
Hi guys,
   I'm investigating the issue that I detailed at [https://www.domoticz.com/forum/viewtopic.php?f=6&t=32279](https://www.domoticz.com/forum/viewtopic.php?f=6&t=32279)

The KWh meter reports wrong data in Domoticz, while I think that Qubino is correctly measuring this data, as I can see from OZW Control Panel.
In particular, I see that the KWh meter component in Domoticz periodically receives 2 floats from Qubino. The first value is the power (that's correct). Instead, the second value **should** be the KWh value from the Qubino smart meter. However, this value appears to be wrong; in particular it's not the first field ("Electric - kWh") but it appears to be the seventh field ("Electric - kVar"), multiplied by 1000.

I have some doubts that the seventh field itself is really expressed in kVAr (more probably, VAr), but this will be an additional field of investigation.

Let me know if I can do something more.

Thanks,
mantoz

**Comment by gizmocuz** [comment]
@mantoz , please follow the guidelines when you create a new issue, could you complete them ?
You should also add this info in your Forum post

**Comment by mantoz** [comment]
@gizmocuz I'm still investigating, as time permits, so completion will need some time.
Let's see if I can do things more clear with a deeper analysis.

This is the log of Domoticz receiving data from Qubino (I added some debug lines in the code):
![qubino_log_issue](https://user-images.githubusercontent.com/54588025/80220387-051e6e80-8644-11ea-9472-eb96f88420a1.png)


Step 0: the KWh counter component in Domoticz is fed with 2 parameters: power and energy. Both come from the Qubino smart meter as I configured the KWh counter component as "Energy read: from device".
Power, the first parameter, appears to be correct; energy is not.

Step 1:
So, this said, let's analyze energy data.
In my case, the KWh counter is fed multiple times: once with correct data (coming from nodeID=3, instanceID=1, indexID=0) which in fact is the KWh value in the Qubino device.

Then, the KWh counter is fed with wrong data, coming from nodeID=3, instanceID=1, indexID=8. This value should/could be the measured reactive power, according to device data, expressed in kVAr. 
My load is a little 28W halogen lamp. For sure, that reactive power is not in kVAr, more probably it's expressed in VAr, so the scaleMultiply value should not be 1000 like it is, but should be 1.

The KWh counter is also fed with data coming from other indexIDs (see 1, 9 etc.) which are not KWh, but KVAh and KVArh (or VAh, VArh), so they should not be fed to the KWh counter in Domoticz. 

So, the code finds several power/powerenergy devices in the same Qubino, and feeds them all to the KWh counter in a short time, when it should not.
I will look for a fix, but I don't want to break things up in the code (in particular for other power/energy meters). Any suggestion please?

Thanks,
mantoz

**Comment by gizmocuz** [comment]
@mantoz , thank you for the details, but I am more talking about the Domoticz version to start with ?
Are you running the latest beta, did you try with the latest beta version ?

**Comment by mantoz** [comment]
Sorry @gizmocuz, I did not get that part :)
I'm still running beta 11939, I will upgrade to the latest beta and re-check.

**Comment by mantoz** [comment]
Updated to latest beta and tested. Same issue.

Domoticz code finds multiple power meters inside the Qubino (KWh, KVAh, KVArh) and "enumerates" them. 
Some of them are found in the first _else if_:

`else if (pDevice->devType == ZDTYPE_SENSOR_POWER`

around line 395 in ZWaveBase.cpp; others are found in the subsequent _else if_:

`else if (pDevice->devType == ZDTYPE_SENSOR_POWERENERGYMETER)`

However, Domoticz should only consider the KWh meter (indexID==0) when calling SendKwhMeter().
One idea would be adding a dedicated code section for this Qubino smartmeter, based on its Manufacturer_id/Product_id, similarly to what has already been done in the code for Fibaro Wallplug.
