### ISSUE TITLE
Various users report that latest pre compiled beta on RPI fails / crash

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4097]
Pre compiled Build 11980 fails for various RPI users.

Locally compiled version works on Raspberry (Debian Buster and Inte NUC)

https://www.domoticz.com/forum/viewtopic.php?f=6&t=32337
https://www.domoticz.com/forum/viewtopic.php?f=6&t=32340

**Comment by rwaaren** [comment]
To summarize:
Prebuild binary 11980 fails on RPI

Local compiled build 11981 all work on my system but not on others 
Local compiled build 11979 works on my- and  other Systems.

https://www.domoticz.com/forum/viewtopic.php?p=244961#p244961

**Comment by gizmocuz** [comment]
@rwaaren , I just updated a raspberry that had version 11790 to 11981 without issues (this one only has ZWave enabled and a Domoticz remote connection)
I will update more systems
One of my remote main systems was running 11980 and updates to 11981 without issues
My own Master (11959, running on a Odroid 64bit arm) .... won't update

So we can say this has to do with 'some' hardware , starting by hand reveals a problem in the constructor of  CBuienRadar::CBuienRadar (invalid argument (const char*))
There was a recent change in here

I suspect that it could be a left-over from old configuration parameters for this hardware

Yep, looking in my database backup reveals that in the database for username/password there is 'undefined', that won't cast to a number

Users affected could update to the new beta version by issuing the following commands

Login via SSH and issue:

```
cd domoticz
./updatebeta
```

I will add a reply to the forum
