### ISSUE TITLE
Compile on Mac/OSX results in error - misssing 

### ISSUE THREAD

**Issue by bmellink** [domoticz/domoticz#4098]
Compile on OSX generates the following link error:
```
Undefined symbols for architecture x86_64:
  "_fopen64", referenced from:
      _fopen64_file_func in libminizip.a(ioapi.c.o)
     (maybe you meant: _fill_fopen64_filefunc)
  "_fseeko64", referenced from:
      _fseek64_file_func in libminizip.a(ioapi.c.o)
  "_ftello64", referenced from:
      _ftell64_file_func in libminizip.a(ioapi.c.o)
```
Error is in the minizip/ioapi.h header file that is different from repos found elsewhere (example is https://github.com/flokart-world/minizip).

For OSX the following defines need to be in place:
```
#define fopen64 fopen
#define ftello64 ftello
#define fseeko64 fseeko
```
This seems to be related when a few weeks ago we separated out the minizip module as external repository. This means the fix needs to done in the https://github.com/domoticz/minizip repository

**Comment by gizmocuz** [comment]
Thank you for reporting, I will make the change asap!

**Comment by gizmocuz** [comment]
Code it patched
