### ISSUE TITLE
Include specific page in HTML title

### ISSUE THREAD

**Issue by rreuvekamp** [domoticz/domoticz#4108]
Every page in the web UI has the same HTML title ("Domoticz"). This makes it hard to differentiate pages when multiple browser tabs with Domoticz are open. It would be great if the specific page title would also be displayed in the HTML title.

Screenshot showing the issue:

https://i.imgur.com/3GSRoym.png

### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by gizmocuz** [comment]
That is intended, it is a single page application. This is the case with a lot of browser related applications (Like for instance my Router)

**Comment by rreuvekamp** [comment]
That's true, but it's possible for single page apps to change the tab title dynamically.

PS: Sorry for commenting after it's closed :$

**Comment by gizmocuz** [comment]
No problem!
Yes that is correct, but it is not the desired behavior
I do not think you open much multiple instances in the browser ?
