### ISSUE TITLE
Reports from OZW door sensors not being seen in domoticz

### ISSUE THREAD

**Issue by jefft4** [domoticz/domoticz#4111]
Aeotec door/window sensor 6 is reporting state changes to OpenZWave, seen in OZW_Log.txt, but these are not being recorded in domoticz.log or seen in the related domoticz device states.

Issue exists since 2020.1; repeatable on a clean system in 2020.2.  Have excluded, re-included device; does not resolve the issue.

Attachments: OZW_Log showing Aeotec sensor as Node 003, excluded, re-included as Node 007, opened and closed a couple of times; domoticz.log showing nothing.
[OZW_Log-AeotecDoor6.txt](https://github.com/domoticz/domoticz/files/4541057/OZW_Log-AeotecDoor6.txt)
[domoticz_log-AeotecDoor6.txt](https://github.com/domoticz/domoticz/files/4541058/domoticz_log-AeotecDoor6.txt)

**Comment by waltervl** [comment]
If still an issue try with Zwavejs2mqtt as openzwave is deprecated. See wiki https://www.domoticz.com/wiki/ZwaveJS2MQTT
