### ISSUE TITLE
[bug] Problem serving PHP content

### ISSUE THREAD

**Issue by lokonli** [domoticz/domoticz#4113]
Domoticz: 2020.2, compiled from source
Debian 10

Serving PHP files was not succesful after starting domoticz with:
./domoticz -www 8081 -sslwww 8091 -php_cgi_path /usr/bin/php-cgi

I did some debugging, and it seems there are two problems in webserver/fastcgi.cpp

line 350:
URLEncode doesn't encode parenthesis. On my system  HTTP_USER_AGENT contains parenthesis. This is literally copied into the command, which make execute (via sh) fail.

line 373:
My php-cgi outputs the return character '/r' after the newline '/n'. As a result there is no empty line, and the test fails. This results in a not-found error reported by the browser.

For the first problem we could extend the CURLEncode::csUnsafeString= "\"<>%\\^[]`+$,@:;/!#?=&" in CURLEncode, but I have no idea of any side effects.
Further, is it necessary to encode? We can just add the php-cli variables within single quotes?

For the second problem we should skip '\r' characters.

I'll create a PR later this week. Instead of urlencoding I'll use single quotes.

**Comment by gizmocuz** [comment]
@lokonli , thanks for looking into this, hope your PR fixes it... The code in fastcgi.cpp is quite old

**Comment by kiddigital** [comment]
Fixed by PR #4326
