### ISSUE TITLE
Compilation of 2020.2 fails on macOS

### ISSUE THREAD

**Issue by PatrBal** [domoticz/domoticz#4114]
Compilation of 2020.1 had raised no problem under macOS Catalina.
However, I am unable to compile 2020.2

> git clone https://github.com/domoticz/domoticz.git Domoticz
> cd Domoticz
> cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/Headers -DPYTHON_LIBRARY=/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib -DUSE_PYTHON_PLUGINS=NO CMakeLists.txt > ~/Desktop/output-cmake.txt  2>&1

Here is the file output-cmake.txt : 
[output-cmake.txt](https://github.com/domoticz/domoticz/files/4542562/output-cmake.txt)

> make > ~/Desktop/output-make.txt  2>&1

Here is the file output-make.txt
[output-make.txt](https://github.com/domoticz/domoticz/files/4542568/output-make.txt)

It seems that there is a problem with the newly appeared submodules "extern/minizip" and "extern/mosquitto". Have any idea ? Thanks in advance.

**Comment by gizmocuz** [comment]
If you look at the output of your make command, you do see the error ?

**"fatal error: 'utlist.h' file not found"**

What does this say ? I think it says that the header utlist.h is not found

This means you have to (somehow) install this on your system

If you google a bit, you will find out that this file is part of the uthash package

I am no OSX expert, but after some searches on google , I found out that there is probably a port/package for your system as well

https://ports.macports.org/port/uthash/summary

You could try to install this

**Comment by beeepus** [comment]
Hello,

Had the same issue. utlist.h file not found with 2020.2
But i found it under extern/mosquitto/src/deps/ so it seems to be included but not properly declared i guess .
I just changed the inclusion to #include "../src/deps/utlist.h" in messages_mosq.c 
It now compiles with out error.
Now i encounter other issue with minizip but that's another topic.

::beep

**Comment by gizmocuz** [comment]
@beeepus , that does seem a problem in the CMake project of Mosquitto
Could you try checking it their repository out in a new folder and try if you can build this ?
If not, maybe you could create a issue on their repository, maybe they can remove this dependency

**Comment by PatrBal** [comment]
Thanks @gizmocuz and @beeepus for your feedbacks.

I have downloaded https://github.com/troydhanson/uthash and copied the file utlist.h in Domoticz/main as a quick-and-dirty workaround. The error with utlist.h does not show up anymore, but it still does not compile successfully. As mentioned by @beeepus, the problem now seems to come from "minizip".

> git clone https://github.com/domoticz/domoticz.git Domoticz
> cp ~/Desktop/uthash-master/src/utlist.h Domoticz/main
> cd Domoticz
> cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/Headers -DPYTHON_LIBRARY=/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib -DUSE_PYTHON_PLUGINS=NO CMakeLists.txt > ~/Desktop/output-cmake.txt 2>&1

Here is the file output-cmake.txt:
[output-cmake.txt](https://github.com/domoticz/domoticz/files/4552465/output-cmake.txt)

> make > ~/Desktop/output-make.txt 2>&1

Here is the file output-make.txt:
[output-make.txt](https://github.com/domoticz/domoticz/files/4552510/output-make.txt)

Thanks again to you all.

**Comment by gizmocuz** [comment]
@PatrBal , please post the error line... that saves us saving the file to disk, opening it, searching for it

I recently made a patch for minizip here for OSX:

https://github.com/domoticz/minizip

Maybe you should update the dependencies by issuing:

 git submodule update --remote

From within the domoticz source folder

**Comment by PatrBal** [comment]
@gizmocuz , sorry for the long file !

I have issued:

> git submodule update --remote

The output was:

> Submodule path 'extern/jsoncpp': checked out 'd517d598a797aa370792b5354da0152f949cfa5e'
> Submodule path 'extern/minizip': checked out '78eb93e8e0ba228f37b197d2022d66b73856c9ff'
> Submodule path 'extern/mosquitto': checked out '0296bd2e55dee20bfcf3e110b7ec14532a1fd985'

Then, I issued "make". Same error occurred:

> Undefined symbols for architecture x86_64:
>  "_fopen64", referenced from:
>     _fopen64_file_func in libminizip.a(ioapi.c.o)
>     (maybe you meant: _fill_fopen64_filefunc)
>  "_fseeko64", referenced from:
>      _fseek64_file_func in libminizip.a(ioapi.c.o)
>  "_ftello64", referenced from:
>      _ftell64_file_func in libminizip.a(ioapi.c.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [domoticz] Error 1
> make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
> make: *** [all] Error 2

**Comment by lwalbert** [comment]
hi,
running cmake then make again after error on utlist.h solved the issue for me.
My work around for the fopen64 stuff in mini zip was to add the following line in file CMakeLists.txt under "Darwin" if statement line 56:
add_definitions(-DUSE_FILE32API)

like this:
IF(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-switch -Wno-parentheses-equality -Wno-deprecated-declarations -Wno$
  add_definitions(-DUSE_FILE32API)
ENDIF()

**Comment by PatrBal** [comment]
Hi all!

I confirm that the workaround provided by @lwalbert works for me (thanks).
So, summarizing, to build successfully 2020.2 under macOS Catalina, two workarounds are needed.

1) add the file https://github.com/troydhanson/uthash/blob/master/src/utlist.h in domoticz/main
2) add the line
> add_definitions(-DUSE_FILE32API)
before the
> ENDIF()
at line 56 of the file CMakeLists.txt

**Comment by gizmocuz** [comment]
@PatrBal , did you try to install the uthash port ?

**Comment by PatrBal** [comment]
@gizmocuz , as I use Homebrew as a package manager and not Macports, I found a way to install uthash via Homebrew:

> brew install clib
clib install uthash

But then, I did not succeed to include the header files in uthash, within cmake (but I have very little experience in c compilation). As, I still had the error "utlist.h not found", I ended up to copy the file "utlist.h" in domoticz/main which did the trick.

**Comment by beeepus** [comment]
Hello,
I just found out that i could use -DUSE_BUILTIN_MINIZIP=NO -DUSE_BUILTIN_MQTT=NO because they are already installed on my system and then 2020.2 compiles and runs just fine.
Thank you.

::beep

**Comment by xslr** [comment]
This issue has been fixed by the mosquitto project with the following commit https://github.com/eclipse/mosquitto/commit/4ab0f4bd3979fc196b2cec04a9298ecc7a38f62a. This commit is not yet in master.
In the meantime, the issue can be worked around by adding `-DWITH_BUNDLED_DEPS=ON` to the cmake invocation of domoticz.

**Comment by PatrBal** [comment]
Thanks @xslr . Your commit eclipse/mosquitto@4ab0f4b has now been added to master. I have just built succesfully 2020.2 (build 12106) under macOS Catalina without having to add -DWITH_BUNDLED_DEPS=ON to the cmake invocation of domoticz.
All the problems raised in this issue are now cleanly solved for me.

**Comment by xslr** [comment]
Great that it works @PatrBal! Just to clear things up, the commit was authored by @ralight, not me :)

**Comment by gizmocuz** [comment]
Is it possible to test if you could build the latest development branch of Domoticz as well ?
It should checkout the latest mosquitto code.
Going to make a new stable release soon as it also fixes a OZW issue

**Comment by lwalbert** [comment]
Hi gizmocuz, just did a git pull and make. Build 100%
Status: Domoticz V2020.2 (build 12102) (c)2012-2020 GizMoCuz

**Comment by lwalbert** [comment]
Hi, the update done in file: hardware/openzwave/control_panel/ozwcp.cpp
#include <Options.h>
#include <Manager.h>
#include <Node.h>
#include <Group.h>
#include <Notification.h>

gave compile errors. Reverting back to:

#include <openzwave/Options.h>
#include <openzwave/Manager.h>
#include <openzwave/Node.h>
#include <openzwave/Group.h>
#include <openzwave/Notification.h>

Compiles 100% OK

compiler error:
[ 62%] Building CXX object CMakeFiles/domoticz.dir/hardware/openzwave/control_panel/ozwcp.cpp.o
/Users/lwalbert/domoticz-2020.2/hardware/openzwave/control_panel/ozwcp.cpp:44:10: warning: non-portable path to file
      '<node.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include <Node.h>
         ^~~~~~~~
         <node.h>
In file included from /Users/lwalbert/domoticz-2020.2/hardware/openzwave/control_panel/ozwcp.cpp:44:
/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Headers/Node.h:21:20: error: expected function body after
      function declarator
PyAPI_FUNC(node *) PyNode_New(int type);
                   ^
/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Headers/Node.h:22:17: error: expected function body after
      function declarator
PyAPI_FUNC(int) PyNode_AddChild(node *n, int type,
                ^
/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Headers/Node.h:25:18: error: expected function body after
      function declarator
PyAPI_FUNC(void) PyNode_Free(node *n);
                 ^
/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Headers/Node.h:27:1: error: unknown type name 'PyAPI_FUNC'
PyAPI_FUNC(Py_ssize_t) _PyNode_SizeOf(node *n);
^
/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Headers/Node.h:27:23: error: expected ';' after top level
      declarator
PyAPI_FUNC(Py_ssize_t) _PyNode_SizeOf(node *n);
                      ^
                      ;
/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Headers/Node.h:42:18: error: expected function body after
      function declarator
PyAPI_FUNC(void) PyNode_ListTree(node *);
                 ^
[ 62%] Building CXX object CMakeFiles/domoticz.dir/hardware/openzwave/control_panel/zwavelib.cpp.o
1 warning and 6 errors generated.

**Comment by PatrBal** [comment]
Hi, same compile errors as @Iwalbert here.

**Comment by gizmocuz** [comment]
This is caused by a reason pull request

https://github.com/domoticz/domoticz/pull/4206

@dwmw2 , could you maybe have a look why this seems not to be working for macOS users ?
I am tempted to make openzwave submodule, maybe that will solve some issues ?

**Comment by dwmw2** [comment]
It looks like the OSX compiler is wrongly including a `node.h` that it finds somewhere else, instead of the `Node.h` that it's asked to include. It "helpfully" complains that it's including the wrong file, when it does so.

I'll see if I can make it *not* include the wrong file...

**Comment by dwmw2** [comment]
I'll take this to OpenZWave and propose a change in their include file setup. It *would* be nicer if they put their headers in a subdirectory.

**Comment by gizmocuz** [comment]
@dwmw2 , that could be a solution, a folder in the root structure 'openzwave' , like currently for 'cpp'

**Comment by PatrBal** [comment]
Hi, the above issue is still there in 2021.1. To be able to compile successfully 2021.1 on macOS Big Sur, I need to modify hardware/openzwave/control_panel/ozwcp.cpp as suggested above by lwalbert. Otherwise, the compile error with <Node.h> shows up.

**Comment by gizmocuz** [comment]
Would be nice if that could be solved by OZW...

But I maybe found something interesting

https://cmake.org/cmake/help/v3.0/command/include_directories.html

So for 'darwin' systems in the CMakeList.txt file we maybe could add the OZW include folder BEFORE the SYSTEM include files

Not sure if it works, but you could give this a try

**Comment by lwalbert** [comment]
Hi @gizmocuz,
adding the folder name openzwave infront of Node.h does the magic somehow:
<openzwave/Node.h>
works when compiling on Mac OSX and raspberry pi. 
Compiler seems to find the Node.h somewhere.
No need to copy the Node.h file to Domoticz-dev folder.

not shure if other compile systems might be affected like windows.
But raspberry and OS X seems to be happy

as you can see, no Node.h file in folder:
<img width="430" alt="Skjermbilde 2021-04-21 kl  11 39 44" src="https://user-images.githubusercontent.com/64552548/115532801-6a786000-a296-11eb-91a4-abfa39cf5b03.png">
<img width="380" alt="Skjermbilde 2021-04-21 kl  11 43 10" src="https://user-images.githubusercontent.com/64552548/115533327-eecae300-a296-11eb-875d-d6135ed4675b.png">

Br
lwalbert

**Comment by dwmw2** [comment]
>  adding the folder name openzwave infront of Node.h does the magic somehow:

Right, the problem is that the folder name isn't guaranteed to be "openzwave" and even if it was, the *parent* folder isn't guaranteed to be in your compiler's include search path anyway.

So while that might happen to work, today, for you, it's "wrong".

The contract that OpenZWave has with applications that use it is "the directory containing OpenZWave's Node.h and other headers shall be directly on your compiler's search path, and you should include "Node.h" with just that name"

Especially on systems without case-sensitive filenames, that isn't a stunningly clever thing for them to do. Let me go and chase down whether I actually did take it up with them, or whether I forgot...

**Comment by dwmw2** [comment]
Making sure openzwave's include directory is *first* on our compiler search path before whatever else provides [Nn]ode.h seems like a good solution for now.

**Comment by gizmocuz** [comment]
@lwalbert, did you also tested on a clean raspberry pi system and following this guide to the letter:

https://www.domoticz.com/wiki/Build_Domoticz_from_source

**Comment by lwalbert** [comment]
> @lwalbert, did you also tested on a clean raspberry pi system and following this guide to the letter:
> 
> https://www.domoticz.com/wiki/Build_Domoticz_from_source

Not completely clean system, but cloned domoticz into a new folder and build.
But if you like, I can do a complete setup on a fresh raspberry image following the guide :)

**Comment by lwalbert** [comment]
Hi @gizmocuz,

Just tested on a clean raspberry image and by following the steps in guide to the letter.
+ added the <openzwave/Node.h> to hardware/openzwave/control_panel/ozwcp.cpp,
then ran CMake and make command. 
Domoticz built 100%
no errors, only one warning in minizip build.

```
[  1%] Building C object extern/minizip/CMakeFiles/minizip.dir/zip.c.o
/home/dietpi/dev-domoticz/extern/minizip/zip.c: In function ‘zipOpenNewFileInZip4_64’:
/home/dietpi/dev-domoticz/extern/minizip/zip.c:1248:28: warning: assignment to ‘const long unsigned int *’ from incompatible pointer type ‘const z_crc_t *’ {aka ‘const unsigned int *’} [-Wincompatible-pointer-types]
         zi->ci.pcrc_32_tab = get_crc_table();
                            ^
[  1%] Linking C static library ../../lib/libminizip.a
[  1%] Built target minizip
...
...
...
[100%] Building CXX object CMakeFiles/domoticz.dir/tinyxpath/xpath_syntax.cpp.o
[100%] Linking CXX executable domoticz
[100%] Built target domoticz
```

Br
lwalbert

**Comment by JurgenLB** [comment]
I have this message on my build also.
`domoticz/extern/minizip/zip.c:1248:28: warning: assignment to ‘const long unsigned int *’ from incompatible pointer type ‘const z_crc_t *’ {aka ‘const unsigned int *’} [-Wincompatible-pointer-types]
 1248 |         zi->ci.pcrc_32_tab = get_crc_table();
      |                            ^ 
`

I find `get_crc_table`
used in "zip.c"
`zi->ci.pcrc_32_tab = get_crc_table();`

and in "unzip.c"
`s->pcrc_32_tab = get_crc_table();`

there are also some warning's about "is deprecated". But that is something different I believe.
the Build runs to complement.
I'm on a raspberry Pi 4 - 8gb  with Debian GNU/Linux 12 (bookworm) so it is on multiple platforms.

kind regards.
