### ISSUE TITLE
Atag one . Error: Atag: Invalid/no data received...

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#4116]
Hi,
Domoticz V4.10717 Build Hash: b38b49e-modified
Build Date: 2019-05-09 13:04:08
 on synology .

For a long time logging my atag devices whos working fine but after a technical Atag issue I have to install a new thermostat.
After that i'm facing the following problem:

> 2020-04-28 20:39:15.221 Error: Atag: Invalid/no data received...
> Error: Atag One nieuw hardware (12) nothing received for more than 5 Minutes!....
> 2020-04-28 20:39:17.791 Status: Atag: Worker stopped...
> 2020-04-28 20:39:17.791 Status: Atag: Worker started...
> 2020-04-28 20:39:17.791 Error: Restarting: Atag One nieuw

After removing Atag One from Domoticz hardware, and after a domoticz restart, and installing the hardware again, this issue is still there.

Is it possible that not all the (old) hardware information is removed?

As far as I can see Domoticz is grabbing the information from mij Atag account. The Atag hardware information is changed there.

Joop.

**Comment by ghost** [comment]
After a better look, the problem is there are no devices made after defining a new hardware device.
Is anyone aware of this problem?

**Comment by gizmocuz** [comment]
Could you check in your settings that 'Accept new hardware/devices' is enabled ?

**Comment by ghost** [comment]
Yes, it is.

![Aantekening 2020-04-29 134850](https://user-images.githubusercontent.com/33230021/80592760-4043e780-8a20-11ea-95f4-66afdf97a7a3.png)

**Comment by varontron** [comment]
Hi Mr. Hilverink.  I am trying to contact Pauline Leefsma.  My father stayed with her family when she was a child in The Hague.  If you know her please contact me (see my profile) and I'll relay the whole story.  Thanks!

**Comment by petrie61** [comment]
Here same issue. Can someone please give some advice?

**Comment by daywlker** [comment]
Im having the same issue too.  But it doesnt like the problem is with domoticz, but the connection from the atag one drops?

2022-01-02 20:33:47.358 Error: AtagOne: Invalid/no data received...
2022-01-02 20:34:47.951 Error: AtagOne: Invalid/no data received...
2022-01-02 20:35:48.620 Error: AtagOne: Invalid/no data received...
2022-01-02 20:36:49.235 Error: AtagOne: Invalid/no data received...
2022-01-02 20:37:49.871 Error: AtagOne: Invalid/no data received...
2022-01-02 20:38:50.464 Error: AtagOne: Invalid/no data received...
2022-01-02 20:39:51.029 Error: AtagOne: Invalid/no data received...
2022-01-02 20:40:51.562 Error: AtagOne: Invalid/no data received...
2022-01-02 20:41:52.121 Error: AtagOne: Invalid/no data received...
2022-01-02 20:42:52.667 Error: AtagOne: Invalid/no data received...
2022-01-02 20:43:53.234 Error: AtagOne: Invalid/no data received...
2022-01-02 20:44:53.808 Error: AtagOne: Invalid/no data received...
2022-01-02 20:45:54.409 Error: AtagOne: Invalid/no data received...
2022-01-02 20:46:55.030 Error: AtagOne: Invalid/no data received...

**Comment by waltervl** [comment]
Still an issue?

**Comment by daywlker** [comment]
Yes it is,  do you have a solution for this?

Gr
Maurice

**Comment by gizmocuz** [comment]
@daywlker , is it possible to contact me on our Slack channel for a debug session ?
The problem seems to be in 'CAtagOne::GetMeterDetails' where no/invalid data is returned, but I have to debug this

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

**Comment by petrie61** [comment]
If daywlkr has not time i'm willing to help as well. I really want this issue to be solved. At this moment running the latest beta of domoticz. I can login to the Atag portal. I can also send REST message to the Atag One locally wit SoapUI.

**Comment by gizmocuz** [comment]
@petrie61 , sure no problem!

**Comment by petrie61** [comment]
@gizmocuz, Nice! What can I do to help?

**Comment by gizmocuz** [comment]
Update to beta 14191 and check if it's solved ;)

**Comment by petrie61** [comment]
@gizmocuz haha, that's easy. Come back to you today.

**Comment by petrie61** [comment]
@gizmocuz sorry:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/96421883/154072149-7a48882b-1674-4b7f-9f4c-49ef6fc4fac2.png">

**Comment by gizmocuz** [comment]
Hmmm okey best to also send me a message on our Slack channel see link above

**Comment by gizmocuz** [comment]
@petrie61 , from what I understand from 'daywlker' the problem starts after a view hours and is solved when stopping/starting the hardware.
Not directly...
You seem to have a problem directly which is ODD, so maybe it is your username/password ?
If you ATagOne up2date ?

**Comment by petrie61** [comment]
@gizmocuz I have it direct. I just login to the Atag portal to check or I could make an extra account for you. This not possible unfortunately. But that conform that I my password and username are correct. Or my AtagOne is up2date is a good question. I do not think so but I not at home until Thursday. But you connect to the cloud I thought? Some extra logging would help :).

**Comment by gizmocuz** [comment]
Please try beta 14193, because there are 3 positions with the same error message it was unclear where the error was arising ...
Did it ever worked ?

**Comment by gizmocuz** [comment]
Let's continue on Slack as it never worked and the error is indeed directly from the start

**Comment by petrie61** [comment]
@gizmocuz I already sent you some messages via Slack. I'm new on slack so I hope it works.

**Comment by gizmocuz** [comment]
Did you click on my username ? It should be on the bottom left

**Comment by gizmocuz** [comment]
The issue from Petrie61 was that german language was not supported and there seems to be a issue with multiple devices.
Unfortunally I don't own a Atag
