### ISSUE TITLE
Cosmetic: Counter waterflow sometimes does not round

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#4120]
current build 2020.1.11839

waterflow device sometimes does not round up numbers

![image](https://user-images.githubusercontent.com/16853535/80645816-f254d100-8a6b-11ea-91ab-9e05da0e9579.png)

**Comment by gizmocuz** [comment]
Thanks for reporting, but what hardware is feeding the data ? Could it be that the data provider already uses non rounded numbers ?

**Comment by GravityRZ** [comment]
The data is sent by and esp8266 device. 
The dummy device value which i send over is set to use 0 decimals so it should be rounded.

when i check the hourly numbers in domoticz they all show rounded numbers per hour
The daily usage is an accumulation of those numbers i think.

to make sure i will check it out on the esp forum. maybe it is still a float number but they just delete the decimals

**Comment by gizmocuz** [comment]
Very odd indeed. Looking in the code, there should be round numbers in the database, is that possible to check (for example export the database via settings, then open it with SQLite Expert Personal Edition),
The tables to look in are Meter/Meter_Calendar
If those are all round numbers, then it goes wrong in CWebServer::RType_HandleGraph (MTYPE_WATER)
You water divider in the settings is set to a round number ? (Like 1000)
The Meter is of type 'water' ?

I am confused now as you mention 'waterflow' , but this does not display a graph like yours (For the week)
It should be of type General/Waterflow

**Comment by gizmocuz** [comment]
@GravityRZ , thanks for editing the post and making it clear that it we're talking about the main counter device.
Could you check/answer the above questions ?

**Comment by GravityRZ** [comment]
Weird. i am pretty sure i answered those questions but my post seems gone.

numbers in the database are rounded(eg 1005)
also when you hover over the 1004.9999999999 it states that it is 1005
water divider is set to 1000(not 0)
the meter is of type counter, subtype water(this is the way i create a dummy sensor)
in domoticz it shows up as an RFXMeter subtype RFXMeter counter

**Comment by gizmocuz** [comment]
All looking good ! Could you try the following
Go to the utility tab where you see the water meter, next press F12 to open the developer console (You can dock this with a icon/dropdown at the botton of your browser)
Next go to the network tab, press the clear button
Now press the 'Log' button on the water meter, and in the network console you should see a line line:

http://<IPADDRESS>:8080/json.htm?type=graph&sensor=counter&idx=2531&range=week

If you left click (select) this line, on the right you should be able to see the response of Domoticz
It should return JSON , and for each day you should see a value with 3 digits in the 'v' variable

Like

```
		{
			"d" : "2020-04-26",
			"v" : "0.246"
		},
		{
			"d" : "2020-04-27",
			"v" : "0.347"
		},
```

If that is also the case I am going to modify the GUI/Javascript code, else the problem already lies in Domoticz

**Comment by GravityRZ** [comment]
this is what i see.

```
{
	"ValueQuantity" : "",
	"ValueUnits" : "",
	"result" : 
	[
		{
			"d" : "2020-04-26",
			"v" : "1.043"
		},
		{
			"d" : "2020-04-28",
			"v" : "1.008"
		},
		{
			"d" : "2020-04-29",
			"v" : "1.022"
		},
		{
			"d" : "2020-04-30",
			"v" : "0.482"
		},
		{
			"d" : "2020-05-01",
			"v" : "0.753"
		},
		{
			"d" : "2020-05-02",
			"v" : "0.999"
		},
		{
			"d" : "2020-05-03",
			"v" : "0.438"
		}
	],
	"status" : "OK",
	"title" : "Graph counter week"
}
```

**Comment by gizmocuz** [comment]
Looking good as well. Okey I will have to dig into the Gui/JS code to see what could go wrong here

**Comment by waltervl** [comment]
@GravityRZ still an issue?

**Comment by GravityRZ** [comment]
Hi waltervl,

i have not noticed this for a very long time. maybe is resolved itself.
Anyway, it is not in the database so not a big deal to close this one.
if it starts popping up regularly again i might bring it up again.
