### ISSUE TITLE
Version 2020.2: Submodules are not included in the release tarball

### ISSUE THREAD

**Issue by nuxeh** [domoticz/domoticz#4121]
Hi,

If you are building Domoticz using the tarball releases from Github, the recent 2020.2 release has become broken, because, now dependencies appear to be using submodules, the code for these dependencies is not included in the release tarball.

Additionally, neither is the `.git` directory included, so there is no chance of using the tarball to obtain the expected submodule revisions. So as far as I can tell, it's not possible to build it at all.

Furthermore, it seems that inclusion of submodule code is not currenty supported by Github, [see here](https://github.community/t5/How-to-use-Git-and-GitHub/Create-Release-that-contains-submodule/td-p/12073/highlight/false).

**Comment by gizmocuz** [comment]
Well after you unpacked the tarball, you have to issue

git submodule update --init --recursive

If your build system has no internet, there are only a few sub-modules, you just have to get those as well (same goes for the project library dependencies as well)

If you just want to download/build, We have a excellent guide here, that does not involve instructions to download the tarball

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by nuxeh** [comment]
@gizmocuz as I mentioned, the `.git/` is not included, so :

```
$ wget https://github.com/domoticz/domoticz/archive/2020.2.tar.gz
$ tar -xzf 2020.2.tar.gz
$ cd domoticz-2020.2/
$ git submodule update --init --recursive
fatal: not a git repository (or any of the parent directories): .git
```

It's not a problem for me, I can fetch from git for my packaging requirements, I'm just saying that the release tarball will be useless until submodule code is included in Github release tarballs, just FYI.

**Comment by gizmocuz** [comment]
@nuxeh , sorry about that.
I think this is a github issue, would be great if they detected that submodules are used and automatically check them out and make the tarball

**Comment by nuxeh** [comment]
Yes, indeed, you would hope that they're working on it, plenty of people have requested it on the Github community page linked above.

Thank you for everything you've done making Domoticz, it's a nice project!
