### ISSUE TITLE
Domoticz offline after last update

### ISSUE THREAD

**Issue by JanC57** [domoticz/domoticz#4122]
After updating the browser cache failed. Domoticz is still running; I found the following issue. How can I solve this?

● domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh)
   Active: active (exited) since Thu 2020-04-30 08:41:04 CEST; 11min ago
  Process: 740 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)

Apr 30 08:41:04 raspberrypi domoticz.sh[740]: /home/pi/domoticz/domoticz: er...y
Apr 30 08:41:04 raspberrypi systemd[1]: Started LSB: Home Automation System.
Hint: Some lines were ellipsized, use -l to show in full.
pi@raspberrypi:~ $ sudo service domoticz stop
pi@raspberrypi:~ $ cd domoticz
pi@raspberrypi:~/domoticz $ ./domoticz
./domoticz: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
pi@raspberrypi:~/domoticz $

**Comment by gizmocuz** [comment]
Please complete all questions in the issue guideline first when you make a post
(Make sure you are on buster as well)

**Comment by Sturla22** [comment]
I am having the same issue, also on a raspberry pi (not buster).
I tried upgrading to buster but then I get an issue with libusb instead: 
`/etc/domoticz/domoticz: error while loading shared libraries: libusb-0.1.so.4`
My current libusb version is 1.0.0

It looks like there is some discussion here as well: https://www.domoticz.com/forum/viewtopic.php?f=6&t=31157&p=241098&hilit=libssl#p241098

**Comment by gizmocuz** [comment]
As stated on the release notification on the forum, you need Buster, @Sturla22 forum topic also mention this
