### ISSUE TITLE
Build fail due to incorrect file linking concerning openzwave

### ISSUE THREAD

**Issue by k96hkh** [domoticz/domoticz#4127]
Hi!

Was trying to do my monthly update of domoticz when I got a build error which I think might be a bug. Bear with me since I'm new to this but. The error is that the file "ValueIDIndexes.h" can't be found but when I search for it it's located here: /usr/include/openzwave/ValueIDIndexes.h

Is it a fault? Is the fault in domoticz or openzwave source code? I'm runnning Arch linux and using the AUR package build function.

[  4%] Building CXX object CMakeFiles/domoticz.dir/main/mainworker.cpp.o
I filen inkluderad ifrån /usr/include/openzwave/Driver.h:37,
                   ifrån /home/henrik/builds/domoticz-git/src/domoticz/main/../hardware/openzwave/control_panel/ozwcp.h:41,
                   ifrån /home/henrik/builds/domoticz-git/src/domoticz/main/../hardware/OpenZWave.h:10,
                   ifrån /home/henrik/builds/domoticz-git/src/domoticz/main/mainworker.cpp:39:
/usr/include/openzwave/value_classes/ValueID.h:34:10: ödesdigert fel: ValueIDIndexes.h: Filen eller katalogen finns inte
   34 | #include "ValueIDIndexes.h"
      |          ^~~~~~~~~~~~~~~~~~
kompilering avslutad.
make[2]: *** [CMakeFiles/domoticz.dir/build.make:369: CMakeFiles/domoticz.dir/main/mainworker.cpp.o] Fel 1
make[1]: *** [CMakeFiles/Makefile2:225: CMakeFiles/domoticz.dir/all] Fel 2
make: *** [Makefile:172: all] Fel 2
==> FEL:  Ett fel uppstod i package().
    Avbryter...

**Comment by rwaaren** [comment]
> Was trying to do my monthly update of domoticz when I got a build error which I think might be a bug. Bear with me since I'm new to this but. The error is that the file "ValueIDIndexes.h" can't be found but when I search for it it's located here: /usr/include/openzwave/ValueIDIndexes.h

Did you do the "make install" for openzwave (as described in  [updated build instructions](https://www.domoticz.com/wiki/Build_Domoticz_from_source) )?

**Comment by k96hkh** [comment]
I would say yes. It was done via a makepkg script (from arch linux AUR), see below:

  make \
    DESTDIR="$pkgdir" \
    PREFIX='/usr' \
    instlibdir='/usr/lib' \
    sysconfdir='/etc/openzwave' \
    install

As seen in the attached files domoticz finds the zwave files and libraries, zwave builds and installs just fine (via makepkg). Maybe worth pointing out is that the arch AUR makepkg has the following cmake options:
cmake \
		-DCMAKE_BUILD_TYPE=Release \
		-DUSE_BUILTIN_LUA=NO \
		-DUSE_BUILTIN_MQTT=NO \
		-DUSE_BUILTIN_SQLITE=NO \
		-DUSE_OPENSSL_STATIC=NO \
		-DUSE_STATIC_BOOST=NO \
		-DUSE_STATIC_LIBSTDCXX=NO \
		-DUSE_STATIC_OPENZWAVE=NO \
		CMakeLists.txt

Note also that this error appeared between now and maybe two months ago and I have been trying to figure out what has changed since then.

[domoticz-git-r12012-1-x86_64-build.log](https://github.com/domoticz/domoticz/files/4570240/domoticz-git-r12012-1-x86_64-build.log)
[domoticz-git-r12012-1-x86_64-package.log](https://github.com/domoticz/domoticz/files/4570241/domoticz-git-r12012-1-x86_64-package.log)

**Comment by gizmocuz** [comment]
The CMake project also has to add/find this '/usr/include' include path
See the CMake project, try to tweak this

**Comment by k96hkh** [comment]
I can get it to compile if I remove the trailing "/openzwave" at line 715 - 717 in the CMakeLists.txt

715    ELSE()
716      include_directories(${OPENZWAVE_INCLUDE_DIRS}/openzwave)
717    ENDIF()

I can see this was worked at beginning of April but I don't understand nor explain why this it should or should not work. Long time since I was on a FreeBSD system but I just think it is plausible that FreeBSD and Linux has the same path structure of openzwave and the same path finding code should work, or?

**Comment by gizmocuz** [comment]
I think we can close this issue ?

**Comment by k96hkh** [comment]
I haven't heard of anyone else having the same issue here nor from aur.archlinux.org. I tried to build domoticz today with same result (same hack works to make it build though). I'll close it, just annoying that I don't understand why this happens when building it with shared libraries on an arch-system :(

Cheers!
