### ISSUE TITLE
CSV export corrupt on Swedish environment

### ISSUE THREAD

**Issue by ugge77** [domoticz/domoticz#4128]
### Wrong separator

When downloading a graphs as CSV from the "hamburger" menu to a system where the locale uses comma as decimal separator the resulting file will be corrupt.

```
"DateTime","Temperature"
"2020-05-02 07:25:00",22,7
"2020-05-02 07:30:00",22,7
"2020-05-02 07:35:00",22,7
"2020-05-02 07:40:00",22,9
...
```
On these systems the separator should be semikolon instead.
```
"DateTime";"Temperature"
"2020-05-02 07:25:00";22,7
"2020-05-02 07:30:00";22,7
"2020-05-02 07:35:00";22,7
"2020-05-02 07:40:00";22,9
...
```

*Client:* Windows 10, Swedish language settings

*Host:* Raspberry PI, Rasbian
*Version:* 2020.2
*Build:* 12004

**Comment by gizmocuz** [comment]
That depends on why you prefer. But this can be set with 

https://api.highcharts.com/highcharts/exporting.csv.itemDelimiter

It seems to guess it from the browsers locale ?

**Comment by ugge77** [comment]
As far as I can see the language set in my Firefox is Swedish
![bild](https://user-images.githubusercontent.com/10853768/80914517-587f7380-8d4c-11ea-9601-8747f3e98b71.png)
and should use `;` as swedish uses `,` for decimal?

On my laptop where the system locale is english it works as expectected.
Does Domoticz let Highchart decide or is it hardcoded using this parameter?
I haven't found where the chart settings reside inside Domoticz code.

**Comment by gizmocuz** [comment]
Domoticz let's Highcharts decode this, we do not specify how to separate the field

**Comment by gizmocuz** [comment]
You could try to go to their website, and try their demo and see if that exports correctly ?

**Comment by FredrikFornstad** [comment]
Highcharts corrected this issue in version  6.0.4 (2017-12-15). See  [HighCharts changelog](https://www.highcharts.com/blog/changelog/#highcharts-v6.0.4). and press bugs  The [csv export module](https://github.com/domoticz/domoticz/blob/development/www/js/export-csv.js.gz) in domoticz is from May 2017, but I do not know if it is relevant.

**Comment by FredrikFornstad** [comment]
Also saw that the [export-csv](https://github.com/highcharts/export-csv) module has been depreciated and the function is since 5.0.11 found as part of the Highcharts repo. Since domoticz is now on Highcharts version 7.1.2 I guess this file should be replaced in domoticz as well?

**Comment by gizmocuz** [comment]
Could you try beta 12017, I made some changes

**Comment by ugge77** [comment]
Just installed 12017 and can confirm that it now works as expected.
Tested on two machines, Swedish and English system locale. Both separator and decimal character is right.

**Comment by FredrikFornstad** [comment]
It works for me too. I have tested with a Win 10 64-bit client using IE 11.778.18362.0 , Edge 44.18362.449.0 and Chrome 81.0.4044.129.

Thanks!

**Comment by gizmocuz** [comment]
Thanks for the feedback !
