### ISSUE TITLE
Scene activation functionality always disabled in 2020.2

### ISSUE THREAD

**Issue by skywalker1979** [domoticz/domoticz#4129]
If using Zwave devices, (it's happening to me with fibaro dimmer2) and you try to enable the function "28. Scene activation functionality" the function stays disabled after being saved.

**Comment by rwaaren** [comment]
Is it possible to report this to [OpenZWave](https://github.com/OpenZWave/open-zwave/issues) ?

**Comment by skywalker1979** [comment]
...done.

**Comment by skywalker1979** [comment]
Actuallly....maybe it needs to stay open? if not...it's ok to close it...for me.

**Comment by rwaaren** [comment]
Could you link the opened openzwave issue here ?

**Comment by skywalker1979** [comment]
https://github.com/OpenZWave/open-zwave/issues/2209

**Comment by skywalker1979** [comment]
Reinstalling Domoticz solved the problem.
