### ISSUE TITLE
General - Voltage sensor notification settings does not load correctly a value containing decimals

### ISSUE THREAD

**Issue by skywalker1979** [domoticz/domoticz#4130]
If a value with a decimal is saved in the notifications settings of a voltage sensor, it is accepted when you enter it, but if you try to edit the value after it has been saved it will be loaded as integer in the value field.
Raspberry pi 3
Domoticz 2020.2

![image](https://user-images.githubusercontent.com/19272233/80913006-68de2100-8d41-11ea-978b-0a84bc1ec782.png)

**Comment by ArnieO** [comment]
This issue is still there.
![image](https://user-images.githubusercontent.com/10295178/219943191-82dac2f9-188e-47c2-9426-cd39c7381603.png)

**Comment by gizmocuz** [comment]
Sorry about that! Took me 3 years to find the cause of this and create a fix for this 😁

The fix was a one-word replacement.

https://github.com/domoticz/domoticz/commit/a7adebb539c58137ec9fbefaa765d4cd842d8ef6

Solved in beta 15085
