### ISSUE TITLE
Question: Installation directories

### ISSUE THREAD

**Issue by nuxeh** [domoticz/domoticz#4131]
Hi,

I tried to sign up to the forum but was locked out by the registration captcha, so posting here.

I have a question relating to installation paths for Domoticz, since I'm trying to package it optimally for NixOS (Linux).

The install creates the following directories, copied directly from the source, to `/opt`:

- `scripts`
- `plugins`
- `Config`
- `dzVents`

I wish to override this so they are installed in more conventional places according to unix filesystem layout. I can choose where to install these directories, i'm just not sure how Domoticz's search paths will work to find these directories correctly at runtime.

Question 1: Are any of the above required to be read+write at runtime?
Question 2: What does `-userdata` point to? Will setting this flag allow Domoticz to find the above paths?
Question 3: If not, how can I point Domoticz to find these paths? (looking in the same directory as the binary is not an ideal option here).

Thanks!

**Comment by nuxeh** [comment]
Actually, I just found the `-approot` CLI parameter, which isn't shown in the usage information, I think that might help.

**Comment by nuxeh** [comment]
I made a PR to document that parameter: https://github.com/domoticz/domoticz/pull/4134

I have a feeling this parameter will fix things for my use case, if that turns out to be the case when I get a chance to test that tomorrow, I'll close this issue.

**Comment by gizmocuz** [comment]
I think Domoticz could find the AppRoot by itselfs, it checks where itself is located so this parameter should be obsolete.
But please test your PR and let us know

Your Unix filesystem layout is not the Domoticz preferred layout
That someone says you 'have' to stick to a certain strange system does not mean we have to comply with that
It makes it also very hard to backup.
Sure a data path I can understand, still, making a quick backup of 1 folder seems way more easier then making a archive containing multiple folder locations (sure you can make a bash file yes)

Regarding the forum, try to use a different email address or use a VPN for registration

**Comment by nuxeh** [comment]
All I'm saying is that this is not a "standard" approach. The Domoticz forum has many examples of people looking for a solution to having more standard directory layout.

Having the flexibility to allow for a more standard filesystem layout aids packaging, which makes installing Domoticz easier to install for more users, and therefore aids adoption.

As far as I am aware there are no official (deb or otherwise) packages, which there could be!

**Comment by nuxeh** [comment]
Can now confirm that the `-approot` parameter is essential to packaging Domoticz nicely for NixOS, so please don't deprecate it, it's very useful for adding flexibility in the install location. Thanks!

**Comment by gizmocuz** [comment]
@nuxeh , Thanks for testing, I won't deprecate it.
Every Unix system seems to have their preferred way of storing files 'somewhere'
I like it to be in 1 folder, nice and easy
