### ISSUE TITLE
Boost 1.73 compatibility

### ISSUE THREAD

**Issue by neheb** [domoticz/domoticz#4139]
This is not compiling anymore:

https://downloads.openwrt.org/snapshots/faillogs/arc_archs/packages/domoticz/compile.txt

The changelog has this line:

```
Changed all uses of the boost.bind placeholders to use the boost::placeholders namespace.
```

LLVM recommends avoiding bind: https://clang.llvm.org/extra/clang-tidy/checks/modernize-avoid-bind.html

bind exists in the std namespace. No idea why the boost version is being used.

**Comment by gizmocuz** [comment]
@neheb , probably because we had to build with GCC 6 at that time ?

Please feel free to make the needed patches in a PR, or for now stay at 1.72

**Comment by ffontaine** [comment]
It seems that this issue has been fixed by https://github.com/domoticz/domoticz/commit/bbcf7fd0646d74b7f169b3aa4231d9150028ed0d as I'm able to build domoticz with boost 1.73 on buildroot.

**Comment by gizmocuz** [comment]
That is correct. Closing issue
