### ISSUE TITLE
Evohome setmode script is not called after setting EvoTouch status

### ISSUE THREAD

**Issue by bertoost** [domoticz/domoticz#4140]
Hi,

Since the native integration of Evohome via Web API is not working (see https://github.com/domoticz/domoticz/issues/2748) and I want to move on with my home automation, I decided to use the python scripts as described here; https://www.domoticz.com/wiki/Evohome#Adding_Evohome_via_scripting_.28web.29
Those scripts are a little bit outdated as well, but as developer I was able to fix them (happy to share my findings btw).

After a heavy debug and improvements I managed to get it working. Decided to use the scripts as python scripts instead of shell scripts which executes by python anyway.
For the settemp this is working fine. It sends signals to the Evohome API and my heating system is updated as well.

But for the EvoTouch, the setmode script is configured, but it's not being reached at all. When I call the script on the commandline myself, it works like a charm, but it looks like the script is not reached from the Domoticz UI when selecting a status. Nothing happens.
I have checked the sqlite database and the script is stored correctly at the EvoTouch record, like the other devices for settemp.
Can someone clear this out for me? Shouldn't this be working?

Thanks in advance.

**Comment by waltervl** [comment]
No feedback. Close this old issue.
