### ISSUE TITLE
Wiki link open in new tab

### ISSUE THREAD

**Issue by DomoticX** [domoticz/domoticz#4141]
Could the wiki link be opened in a new tab instead of exiting the settings page? thanks!

**Comment by rwaaren** [comment]
Please ask these kind of questions on the forum. The domoticz issue list is for domoticz code bugs.

Also be more specific in your question.  

- Is this a browser issue?
- What version are you on? Hardware / OS / domoticz version?
- What do you see?
- What did you expect?

etc..
