### ISSUE TITLE
Devices, Timer: Missing option to set events to happen only "Once".

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#4144]
Occasionally I need to set an event to trigger/happen only "Ones", at a special date. Only me? :)

**Comment by gizmocuz** [comment]
@RicardP , you could add a dummy switch, for this switch add a timer for a fixed date/time, use this dummy switch in your script/event

**Comment by RicardP** [comment]
@gizmocuz thanks for your input, I found the "Fixed date" setting already available, sorry.

Have a nice day!
