### ISSUE TITLE
No update flooplaner item from resume webpage

### ISSUE THREAD

**Issue by djdevil** [domoticz/domoticz#4152]
Version: 2020.2
Build Hash: b63341bc0
Compile Date: 2020-04-26 13:47:55

I noticed that when my tablet resumes from sleep and the browser was displaying the floorplaner the devices are not automatically updated to their latest status together with the displayed time.
before the 2020 version everything worked perfectly! is the new websocket that creates this problem?

**Comment by gizmocuz** [comment]
@djdevil , Not sure, but I think you can emulate this in the Chrome developer console (F12), and press the device button, then set the device offline ... and online again

**Comment by djdevil** [comment]
hello @gizmocuz thx for reply i try with Firefox debug i have this error

```
TypeError: data.result is undefined
handleMessage http://192.168.1.7/app/livesocket.js:78
Angular 2
        $$fireEvent
        onmessage

```
I don't know if I managed to recreate the error? But I can confirm that when the tablet wakes up from standby and I see the floor plan it tries to load the device status icons

**Comment by gizmocuz** [comment]
I added some safety checks, could you try beta 12062?

**Comment by djdevil** [comment]
@gizmocuz  thx for reply unfortunately I'm in a stable version and I don't have another card to try the beta. Can I edit some files from the www folder?

**Comment by gizmocuz** [comment]
@djdevil , if you do edit some files, you are also on some beta version
You can make a full backup of your Domoticz folder, and if the beta does not work, you can always go back

**Comment by waltervl** [comment]
Tested in stable 2022.1: Fixed
