### ISSUE TITLE
Qubino dimmer and shutter do not have an [ON] or [Open] status

### ISSUE THREAD

**Issue by baahver** [domoticz/domoticz#4154]
I have different Blockly scripts. One with a Qubino dimmer and One with a Qubino Shutter. 
Both have the same problem. 

The script never reacts on [Open] status on the Shutter or [On] status on the dimmer. Because those status is never there. These devices are Closed / Off, or set to level %. 

This wouldn't be an problem if I could use If stutus is > % 1 AND < % 100. But then I get an error:
" Error: EventSystem: Lua script error (Blockly), Name: zonnescherm test_2 => [string "result = 0; weekday = os.date('*t')['wday']; ..."]:1: attempt to compare string with number "

I contacted Qubino about this. I am no expert. And they wrote me: 
"The device reports  COMMAND_CLASS_SWITCH_MULTILEVEL_REPORT and that is a hex value that the gateway later convert in a decimal value and manage it how is programmed to.
​
Check if the Open state can be somehow programmed in the Gateway software eg any % higher than X% set the state in the gateway to open. "

I assume this is a bug in the way those status is reported / managed? Or Status > 1% AND < 100% should be possible.

Version: 2020.2
Build Hash: b63341bc0
Compile Date: 2020-04-26 13:47:55
dzVents Version: 3.0.2
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

**Comment by waltervl** [comment]
Is this stall an issue? If this are Zwave Devices (not mentioned) please consider moving to ZwaveJS2MQTT as OpenZwave is deprecated.
