### ISSUE TITLE
Idea: simple thermostats as utility sensors

### ISSUE THREAD

**Issue by nuxeh** [domoticz/domoticz#4156]
Hi,

A feature I would really like (if it doesn't exist already, and I haven't missed it somehow) would be to have simple point and click utility sensors for temperature control, e.g.

 - Simple hysteretic thermostat
 - PID temperature controller

I personally think it could be a valuable addition, and could enhance general ease of use, since it would mean you don't have to dive into writing scripts to achieve simple temperature control.

I was wondering if implementing such a thing would be feasible, if so I would consider putting some time into developing such utility devices for Domoticz.

Would be interested to know anyone's thoughts.

Thanks!

**Comment by pcurt** [comment]
Hi, 
I am using this useful plugin:
https://www.domoticz.com/wiki/Plugins/Smart_Virtual_Thermostat.html
I think that it matches with what you are looking for

**Comment by nuxeh** [comment]
Thanks @pcurt! This plugin looks promising
