### ISSUE TITLE
Pluginsystem: External link not working properly

### ISSUE THREAD

**Issue by DomoticX** [domoticz/domoticz#4157]
in the plugin tag externallink="mywebsite.com"

does not open a external url, but appends to internal ip like:

http://192.168.2.16:8080/mywebsite.com
(and gives 404 Not Found error)

instead of:

mywebsite.com

-----------------------------
Using:
ersion: 2020.2
Build Hash: b63341bc0
Compile Date: 2020-04-26 12:47:55
dzVents Version: 3.0.2
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

**Comment by gizmocuz** [comment]
@DomoticX , I have no idea what or how you use the plugin, maybe you could post the plugin ?
With an example we can replicate it
How about using http://mywebsite.com ?

**Comment by DomoticX** [comment]
you can find the plugin here (just updated it ;-)): https://github.com/DomoticX/domoticz-modbus
example:

```
<plugin key="ModbusREAD" name="Modbus RTU/ASCII/TCP - READ v2020.2E" author="S. Ebeltjes / DomoticX.nl" version="2020.2E" externallink="mywebsite.com" wikilink="https://github.com/DomoticX/domoticz-modbus">
    <description>
        <h3>Modbus RTU/ASCII/TCP - READ</h3>
        With this plugin you can readout RS485 Modbus devices with methods RTU/ASCII/TCP<br/>
        <br/>
		<h3>Functions of the READ plugin:</h3>
        Read Coil (Function 1)<br/>
        Read Discrete Input (Function 2)<br/>
        Read Holding Registers (Function 3)<br/>
        Read Input Registers (Function 4)<br/>
        <br/>
        <h3>Supported data types:</h3>
        No conversion (passtrough) / BOOL / INT / UINT / FLOAT / STRING<br/>
		<br/>
        <h3>Set-up and Configuration:</h3>
        See wiki link above.<br/> 
    </description>
    <params>
.....
<plugin>
```

**Comment by DomoticX** [comment]
Tried with http:// in front , seems to work then ;-)

So without http:// is seems to paste it after the internal ip....

**Comment by gizmocuz** [comment]
I am pretty sure this is the expected behavior as it is inside a href
Could indeed also be used to retrieve a file in the web folder
(hardware.js)
Great it's working !!
