### ISSUE TITLE
The archives of the Beta builds 12049 for Windows / Linux and ARM 64 on  https://www.domoticz.com/downloads/ are broken.

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4160]
The archives of the Beta builds 12049 for Windows / Linux and ARM 64 on 
https://www.domoticz.com/downloads/ are broken.

ARM 32 is OK.

Also see [Forum post; Unexpected end of file during update 12049]( https://www.domoticz.com/forum/viewtopic.php?f=6&t=32656&p=247270#p247270)

**Comment by gizmocuz** [comment]
Seems to be building fine on travis and is updated on our website

**Comment by rwaaren** [comment]
Build 12055 is ok for all 4 archives
