### ISSUE TITLE
Update available, updating, no update

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#4165]
Several users experience issues in case a new update is available.

If you press "Check for Update" and an update is available you get the message "No Update Available", while there is one. Some users go to the cli and solve it from there. For me pressing F5 (Refresh) starts the update immediately. See also the discussion at: https://www.domoticz.com/forum/viewtopic.php?f=6&t=32734

**Comment by rwaaren** [comment]
On what domoticz versions (before update / after update) and what hardware do you see this behavior ?

**Comment by FireWizard52** [comment]
@rwaaren 

Domoticz versions:

At the moment I use 12067 and I had in on 12065 but it happens since approx. a week.
I did not pay much attention at as I pressed simply F5

But I have some info that might be interesting:

pi@RPi2:/var/log $ more daemon.log|grep domoticz
May 17 12:21:22 RPi2 systemd[1]: domoticz.service: Succeeded.
May 17 12:21:22 RPi2 systemd[1]: domoticz.service: Found left-over process 22320 (updatebeta) in control group while starting unit. Ignoring.
May 17 12:21:22 RPi2 systemd[1]: domoticz.service: Found left-over process 22370 (sudo) in control group while starting unit. Ignoring.
May 17 12:21:22 RPi2 systemd[1]: domoticz.service: Found left-over process 22379 (systemctl) in control group while starting unit. Ignoring.
May 17 12:21:22 RPi2 domoticz.sh[22405]: 2020-05-17 12:21:22.454  Status: Domoticz V2020.2 (build 12065) (c)2012-2020 GizMoCuz
May 17 12:21:22 RPi2 domoticz.sh[22405]: 2020-05-17 12:21:22.454  Status: Build Hash: bbcf7fd06, Date: 2020-05-17 11:46:37
May 17 12:21:22 RPi2 domoticz.sh[22405]: 2020-05-17 12:21:22.454  Status: Startup Path: /home/pi/domoticz/
May 17 12:21:22 RPi2 domoticz.sh[22405]: domoticz: Domoticz is starting up....
May 17 14:55:37 RPi2 systemd[1]: domoticz.service: Succeeded.
May 17 14:55:37 RPi2 systemd[1]: domoticz.service: Found left-over process 29207 (updatebeta) in control group while starting unit. Ignoring.
May 17 14:55:37 RPi2 systemd[1]: domoticz.service: Found left-over process 29243 (sudo) in control group while starting unit. Ignoring.
May 17 14:55:37 RPi2 systemd[1]: domoticz.service: Found left-over process 29252 (systemctl) in control group while starting unit. Ignoring.
May 17 14:55:37 RPi2 domoticz.sh[29319]: 2020-05-17 14:55:37.455  Status: Domoticz V2020.2 (build 12067) (c)2012-2020 GizMoCuz
May 17 14:55:37 RPi2 domoticz.sh[29319]: 2020-05-17 14:55:37.455  Status: Build Hash: 0fc3c7b70, Date: 2020-05-17 13:15:45
May 17 14:55:37 RPi2 domoticz.sh[29319]: 2020-05-17 14:55:37.456  Status: Startup Path: /home/pi/domoticz/
May 17 14:55:37 RPi2 domoticz.sh[29319]: domoticz: Domoticz is starting up....

The Hardware is both Rasberry Pi 1B and 2B

I did not investigate why the left-over.

**Comment by FireWizard52** [comment]
Additional info.
I checked the other pi and exactly the same:

pi@RPi1:/var/log $ more daemon.log|grep domoticz
May 17 12:19:26 RPi1 systemd[1]: domoticz.service: Succeeded.
May 17 12:19:26 RPi1 systemd[1]: domoticz.service: Found left-over process 23704 (updatebeta) in control group while starting unit. Ignoring.
May 17 12:19:26 RPi1 systemd[1]: domoticz.service: Found left-over process 23735 (sudo) in control group while starting unit. Ignoring.
May 17 12:19:26 RPi1 systemd[1]: domoticz.service: Found left-over process 23740 (systemctl) in control group while starting unit. Ignoring.
May 17 12:19:27 RPi1 domoticz.sh[23752]: 2020-05-17 12:19:27.248  Status: Domoticz V2020.2 (build 12065) (c)2012-2020 GizMoCuz
May 17 12:19:27 RPi1 domoticz.sh[23752]: 2020-05-17 12:19:27.254  Status: Build Hash: bbcf7fd06, Date: 2020-05-17 11:46:37
May 17 12:19:27 RPi1 domoticz.sh[23752]: 2020-05-17 12:19:27.255  Status: Startup Path: /home/pi/domoticz/
May 17 12:19:27 RPi1 domoticz.sh[23752]: domoticz: Domoticz is starting up....
May 17 14:54:14 RPi1 systemd[1]: domoticz.service: Succeeded.
May 17 14:54:14 RPi1 systemd[1]: domoticz.service: Found left-over process 30801 (updatebeta) in control group while starting unit. Ignoring.
May 17 14:54:14 RPi1 systemd[1]: domoticz.service: Found left-over process 30825 (sudo) in control group while starting unit. Ignoring.
May 17 14:54:14 RPi1 systemd[1]: domoticz.service: Found left-over process 30830 (systemctl) in control group while starting unit. Ignoring.
May 17 14:54:14 RPi1 domoticz.sh[30842]: 2020-05-17 14:54:14.698  Status: Domoticz V2020.2 (build 12067) (c)2012-2020 GizMoCuz
May 17 14:54:14 RPi1 domoticz.sh[30842]: 2020-05-17 14:54:14.704  Status: Build Hash: 0fc3c7b70, Date: 2020-05-17 13:15:45
May 17 14:54:14 RPi1 domoticz.sh[30842]: 2020-05-17 14:54:14.705  Status: Startup Path: /home/pi/domoticz/
May 17 14:54:14 RPi1 domoticz.sh[30842]: domoticz: Domoticz is starting up....

**Comment by TheReptile** [comment]
I guess it's still the same issue as https://github.com/domoticz/domoticz/issues/4162
Most likely @gizmocuz needs to tweak the server further.

**Comment by gizmocuz** [comment]
It should work again...

**Comment by TheUlpio** [comment]
Tried now. Updated from 12067 to 17073 without any issue. I think this can be closed now.
Thank you @gizmocuz

**Comment by gizmocuz** [comment]
Well there are still some users hammering the update url every 5 second...
Still have to find a way to bypass this
