### ISSUE TITLE
Tesla temperature and Outside temperature are the same

### ISSUE THREAD

**Issue by GuidoRu** [domoticz/domoticz#4167]
Hi,

Since May 1st (About) the Tesla "Temparature" and "Outside temperature" are the same. Looking at the numbers, I suspect that Outside Temp. is given the values for Temparature. 

Would be great if this can be fixed!

**Comment by MrHobbes74** [comment]
Yea, found the issue! Thanks! I will fix it ASAP.

**Comment by MrHobbes74** [comment]
Solution in PR 4168

**Comment by GuidoRu** [comment]
That quick. Tnx!
