### ISSUE TITLE
Feature request: Login user and password in log file when not authorized.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#4169]
I got these kind of log lines in my domoticz.log
`2020-05-19 15:17:01.560 Error: [web:8080] Failed authentication attempt, ignoring client request (remote address: 192.168.x.x)`
Router is connected to the internet and all traffic is routed to my Synology NAS.
Only https is accepted and the portnumber is a strange one, but still they find it.
I got my synology working as reversed proxy to the raspberry Pi.
It would be useful if the used user and password is also logged when the login attempt failed.

**Comment by Olifant1990** [comment]
My opinion? No thanks... If I mistype my username/password, then it is in plain text in a log.

**Comment by SargonofAssyria** [comment]
First, if you mistype than that combination is not valid.
Second, if you do it right, don't grant users rights to more then they need to.
In my case nobody has access to the raspberry pi at shell level.
In Domoticz everybody else is a normal user, which do not have access to Settings, so cannot see logging....
I have, and others may have too, regular logging attempts from the outside world.
Despite the fact that I have chosen a 'strange'  portnumber and only use HTTPS from outside world.
They try by portscanning to get in, I just want to know if they get close, I doubt, but they could.

**Comment by Olifant1990** [comment]
Well, if I have the username/password combination of admin/admin (it's not, but for now in this example) and I mistyped the combination like admii/admin, I can easily guess what it had to be... So break in.
And my Domoticz is on a Windows machine. When there are more admins, they can see the log files.
Just a simple programming rule: NEVER EVER store a password somewhere plain.

**Comment by SargonofAssyria** [comment]
Yeh, but an admin should trust an other admin, because they can see each other password.
If you are an admin, do don't have to break in, because you are already in.

**Comment by Olifant1990** [comment]
Nope, trust is not an excuse to write down a password in plain ;)
So many hacks thinkable which can read for example logs/databases etc.

**Comment by SargonofAssyria** [comment]
If it can't be done by Domoticz, I will do it myself, no problem.

**Comment by gizmocuz** [comment]
Password should never be exposed in plain. Do note that the log is also visible for 'user' types of users in Domoticz, not only a user with Admin rights.

**Comment by SargonofAssyria** [comment]
In my Domoticz the  'user' types of users only have a Logout 'button' on the place where the Setup is.
But then again, I closed the issue 15 hours ago. I will do it myself.

**Comment by SargonofAssyria** [comment]
I already done it on my reverse proxy server on my NAS, which is the accesspoint to the angry outside world for my whole network.
