### ISSUE TITLE
Feature request: More info in logfile on pinger

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#4171]
Using 2020.2 and newer. Randomly I get these error messages in the logfile.
`2020-05-20 22:49:07.970 Error: Pinger: This is a read-only sensor!`
In the 'old' stable 4.10717 those messages were not present.
It would be helpful if there would be a little bit more info, like which IP-address.

**Comment by Olifant1990** [comment]
It looks like you have the hardware type "System Alive Checker (Ping)" with some devices.
This message is saying that you are somehow (clicking/script/etc.) trying to change a device state, which is read-only.

**Comment by SargonofAssyria** [comment]
I know, but I asked for a little bit more info. Please read the last line of the first post.

**Comment by gizmocuz** [comment]
I added a bit more information in the upcoming beta version (name/ip), but as Olifant1990 says, you are trying to switch a read-only sensor.
Your script, or your manual action, should also reveal the Ping Name/ID/IP

**Comment by SargonofAssyria** [comment]
Tnx, I am looking forward to it.
