### ISSUE TITLE
Oregon-UVR128

### ISSUE THREAD

**Issue by geschriever** [domoticz/domoticz#4172]
Please can you add the Oregon sensor to the RTL433 interface in Domoticz.
I get the next message:
Rtl433: Unhandled sensor reading, please report: ({"time" : "2020-05-21 12:24:06.740469", "protocol" : 12, "model" : "Oregon-UVR128", "id" : 155, "uv" : 5, "battery_ok" : 1, "mod" : "ASK", "freq" : 433.864, "rssi" : -0.100, "snr" : 15.669, "noise" : -15.769})

Do you need more information?

Thanks in advance,
Gé Schriever

**Comment by gizmocuz** [comment]
Should work now in beta 12077 and higher

**Comment by gizmocuz** [comment]
@geschriever , question, how to do get the snr/rssi/noise inside the above json payload ? I don't see that here, is it a command line parameter?
If yes, we could enable this by default and also use the rssi

**Comment by geschriever** [comment]
@gizmocuz, thanks! Is working now! I just add -R 12 to the command line parameter. No other parameter in.
Below a random message I get back from Domoticz log.
Another line (just for showning you). I do receive more of this kind of lines.
 
2020-05-22 15:08:10.827 Status: Rtl433: Unhandled sensor reading, please report: ({"time" : "2020-05-22 15:08:10.018798", "protocol" : 86, "model" : "Smoke-GS558", "id" : 7336, "unit" : 0, "learn" : 0, "code" : "e39500", "mod" : "ASK", "freq" : 433.850, "rssi" : -0.126, "snr" : 15.170, "noise" : -15.296})

Thanks again!

**Comment by gizmocuz** [comment]
@geschriever , great it's working!
I don't see the rssi ... I will do some googleing for this

**Comment by geschriever** [comment]
Maybe by installing a lot kind of try-out software of RTL_433 native something is changed.
I have installed the latest version of RTL_433 but do not know if it interact with Domoticz_RTL433?

**Comment by gizmocuz** [comment]
Should work, i just compiled the version from 4 days ago...

**Comment by geschriever** [comment]
See picture for my setting using RTL_433 HW in Domoticz

![screenshot 2020-05-22 om 15 35 09](https://user-images.githubusercontent.com/60884808/82673281-dd6df680-9c41-11ea-96d8-27465d3e2753.jpg)

And this in the current log:
![screenshot 2020-05-22 om 15 36 31](https://user-images.githubusercontent.com/60884808/82673441-2c1b9080-9c42-11ea-8f94-91e7929bf8f9.jpg)
