### ISSUE TITLE
Checkauthtoken session id not found

### ISSUE THREAD

**Issue by heggink** [domoticz/domoticz#4174]
Many users have a bunch of these errors in the log again. Any idea what's causing this?

**Comment by DAVIZINH0** [comment]
Hello,
I have this problem with a lot of:
CheckAuthToken(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx) : session id not found

I use domoticz in docker (version: V.411786) (last versión available for linuxserver docker)
App for mobile is Android paid version. Last version released (22/05)

If you want any information tell me

thanks

**Comment by FireWizard52** [comment]
Hi,

See also: https://www.domoticz.com/forum/viewtopic.php?f=6&t=32680&p=248248#p248248

To many users are experiencing this issue.

I use the Domoticz Lite app on 4 devices (3 tablets and 1 phone)
All the devices are Android.

3 of them has been updated (automatically) to version 0.2.224 (7535) last evening (guess araound 22:00h) and
the other one was still on version 0.2.223 (7499).

So it wasn't the beta branch.

Remark: Mostly I saw this issues during the night, if their is not any activity from PC's or something. The PC's are off.

Regards

**Comment by heggink** [comment]
I just uninstalled the android domoticz app and the problem went away so no domoticz linux problem.

**Comment by kitopopo** [comment]
Hi dear friends,

The error appear when i use the domoticz pay app in android. When i use a widget appears the error at the moment. I have cleared the app cache and the frequency of the error is lower but it continues to appear . each time it appears with a different token code . We have been with this error for a long time, I think they should fix it

**Comment by DAVIZINH0** [comment]
same for me kitopopo but the creator say that he cant replicate the problem :-(

**Comment by kitopopo** [comment]
> same for me kitopopo but the creator say that he cant replicate the problem :-(

the creator can not replicate the problem? This error appeared more than 6 months ago and it is a constant error that many people have, it is also quite annoying, I do not understand how they cannot reproduce the problem. I have verified that it is related to the android domoticz payment application. From my point of view I do not know how they have been able to close the issue when the problem is not solved. @gimocuz know about this problem?

**Comment by DAVIZINH0** [comment]
> > same for me kitopopo but the creator say that he cant replicate the problem :-(
> 
> the creator can not replicate the problem? This error appeared more than 6 months ago and it is a constant error that many people have, it is also quite annoying, I do not understand how they cannot reproduce the problem. I have verified that it is related to the android domoticz payment application. From my point of view I do not know how they have been able to close the issue when the problem is not solved. @gimocuz know about this problem?

this is the github of the android app. I think the problem is the android app because if you unistall the app the problem dissapears
https://github.com/domoticz/domoticz-android/issues/629

**Comment by rwaaren** [comment]
see [forum post](https://www.domoticz.com/forum/viewtopic.php?p=273684#p273684)

**Comment by kitopopo** [comment]
> see [forum post](https://www.domoticz.com/forum/viewtopic.php?p=273684#p273684)

Oh yeaa the error is solved in the lastest beta. Thank you very much. you are a good team, congratulations.

**Comment by DAVIZINH0** [comment]
great! no more errors!!
thanks a lot!
