### ISSUE TITLE
SolarEdge via Web API Error getting http data

### ISSUE THREAD

**Issue by jomi75** [domoticz/domoticz#4175]
Hi All,
i am facing the following problem. After few weeks my SolarEdge Api is returning the following error message: SolarEdge via Web API Error getting http data

i searched the community already and tried the following:
* clear browser caches
* different browser
* update Domoticz (now 2020.2)
* disable/enable the hardware component in Domoticz
* deleted / created the hardware component in Domoticz
* restarted 
* created new API on the SolarEdge portal

hopefully somebody can guide me into the right direction to fix the problem.

thanks

**Comment by jomi75** [comment]
Hi
Does somebody have a clue? Or is a reinstall required?

**Comment by Hanskes** [comment]
Same problem here! Anyone?

**Comment by gizmocuz** [comment]
It seems the data is returning and the hardware is functioning, but you get these errors in the log correct?
Made a new beta version that adds a bit more logging information (which HTTP call is called that returns with a error)
Do you also get a 'thread' timeout ?
It looks like the one of the 3 HTTP calls is taking a very long time

It seems to be a problem with the SolarEdge web server as it does not happen all the time, sometimes (here) it goes find for 18 hours

**Comment by Sarcas666** [comment]
Same here, sometimes there are dozens of these errors in the log. Data seems to be coming through regardless. Im running 2020.2 (build 12227) currently.

**Comment by waltervl** [comment]
This issue should be solved (no relevant code changes for this issue except extra logging). So probably a SolarEdge server issue.
