### ISSUE TITLE
Getting more done in GitHub with ZenHub

### ISSUE THREAD

**Issue by gizmocuz** [domoticz/domoticz#418]
Hola! @gizmocuz has created a [ZenHub](http://www.zenhub.io) account for the **domoticz** organization. ZenHub is the leading team collaboration and project management solution built for GitHub.

---
#### How do I use ZenHub?

To get set up with ZenHub, all you have to do is **[download the browser extension](https://www.zenhub.io?utm_source=ZHOnboarding)** and log in with your GitHub account. Once you do, you’ll get access to ZenHub’s complete feature-set immediately.
#### What can ZenHub do?

ZenHub adds a series of enhancements directly inside the GitHub UI:
- Real-time, customizable task boards for GitHub issues;
- Burndown charts, estimates, and velocity tracking based on GitHub Milestones;
- Personal to-do lists and task prioritization;
- “+1” button for GitHub issues and comments;
- Drag-and-drop file sharing;
- Time-saving shortcuts like a quick repo switcher.
### [Add ZenHub to GitHub](https://www.zenhub.io?utm_source=ZHOnboarding)

_Still curious? See [more ZenHub features](https://www.zenhub.io/features?utm_source=ZHOnboarding) or read [user reviews](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/reviews). This issue was written by your friendly ZenHub bot, posted by request from @gizmocuz._

![ZenHub Board](https://cloud.githubusercontent.com/assets/8771909/11153956/233ac4a8-89f1-11e5-94b1-1569d3f38b4d.png)

**Comment by sijones** [comment]
Am liking this, nice!

**Comment by gizmocuz** [comment]
Thanks, me too ;) it is simple but efficiant

**Comment by remb0** [comment]
I think this issue can be closed.

**Comment by gizmocuz** [comment]
This is for other developers, why ?

**Comment by szczukot** [comment]
Maybe now, section "Bugs and Problems" (and maybe "Suggestion") on forum is not needed? Maybe it should be redirected to the Issue on GitHub? It would be easier to manage and would not duplicate the posts.

**Comment by gizmocuz** [comment]
Certainly not, because 95% on the forum is not a software bug but a user bug (or problem)
As long as it are also problems, and not real software bugs this issue tracker will get flooded
(Like with these last 3 messages)
If it continues, i probably will install something like Monit
Edit... last 4 messages

**Comment by gizmocuz** [comment]
What should be done in case of a software bug, make an issue here, assign yourself for instance to it, use the zenhub interface to put it in in progress, when finished set it to solved
And maybe discuss 'here' with a beta tester the progress
