### ISSUE TITLE
openURL().afterSec(s) with s non integer

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#4182]
Hi all,

version: 2020.2 (dzVents 3.0.7)
Platform: RPI + Raspbian Buster

To put it simple, openURL().afterSec(s) seems not to work if s is not an integer, in such case the afterSec() is ignored and openURL() executed without delay.

After updating to v2020.2 a few days ago I noticed that domoticz was not managing my curtains well. To manage them I use a not too simple combination of dzvents scripts where one of them sends messages to itself via openURL(). I have noticed that the culprit was that calls to openURL().afterSec() were executing immediately instead of after the specified delay. The parameter to afterSec() was a non integer number. Simply using round() to convert the parameter to an integer solved this.

afterSec() used upon other device methods seems to work OK.

Unfortunately I do not know what was my previous Domoticz version prior to the update, maybe 4.10717 or 2020.1.

Regards.

**Comment by dannybloe** [comment]
Then what is the problem here? You are supposed to pass it an integer as stated in the documentation. Then don’t pass it strings as it will give you unpredictable results.

**Comment by ghost** [comment]
Hi,

I'm passing no strings, but non integer numbers such as 2.5 (the number 2.5, not the string '2.5'). Sorry but, where in the documentation is stated that the numbers expected by afterXXX() must be integers?

Regards.

**Comment by rwaaren** [comment]
> I'm passing no strings, but non integer numbers such as 2.5 (the number 2.5, not the string '2.5'). Sorry but, where in the documentation is stated that the numbers expected by afterXXX() must be integers?

I was not aware that there was this restriction with the openURL and emitEvent commands. For other commands, floats do work in the afterSec() methods.  I added a note in the wiki.

Will discuss  and have a look at the code to see if this can be solved. Until fixed please use integers 

**Off topic:** If you use openURL to (re)trigger a script you might want to consider the use of emitEvent() in combination with the customEvents trigger.

**Comment by ghost** [comment]
As I stated before, this behaviour changed at some point between v4.10717 and v2020.2. Before that, openURL().afterSec() accepted non integer parameters without problems.

Regards.

**Comment by rwaaren** [comment]
Fixed in version Domoticz V2020.2 (build 12105)
