### ISSUE TITLE
Update to version 12102 not working

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#4187]
It updates to 12099.

For details see: https://www.domoticz.com/forum/viewtopic.php?f=6&t=32858

Regards

**Comment by salopette** [comment]
Same problem too.
./updatebeta does not work either.

**Comment by gizmocuz** [comment]
Already noted and being worked on

**Comment by TheReptile** [comment]
I checked the updater script and noticed the APPHASH is strange?
```
#define APPVERSION 12102
#define APPHASH "b5745509b-modified"
#define APPDATE 1590645937
```
Not sure if it's related though.

**Comment by gizmocuz** [comment]
Nope, strangely it seems that the output (of my 32bit build system anyway) put the compiled executable into a 'bin' folder
This caused the new archive not to be uploaded, but the apphash was updated.

Made some changes and it seems to build fine again

**Comment by pa3fat** [comment]
After screen refresh in FF it now wants 12105 and same update loop. On 12102 according to the main dashboard page.

**Comment by pa3fat** [comment]
12106 fixes the issue. Tnx !

**Comment by gizmocuz** [comment]
Unfortunately there still seems to be a issue as the CMake produces the final binary in the 'bin' folder for some reason.
It could be because of some external project CMake configuration, this was a copy/build action
Still have to find a solution for this

**Comment by jeroenkl** [comment]
I'm also stuck on 12099, manual update doesn't help.
![image](https://user-images.githubusercontent.com/37976568/83387107-72b07e00-a3ec-11ea-8578-49d9a08edb14.png)

@gizmocuz anything you can help me/us with?

**Comment by SiskoBen** [comment]
> Unfortunately there still seems to be a issue as the CMake produces the final binary in the 'bin' folder for some reason.
> It could be because of some external project CMake configuration, this was a copy/build action
> Still have to find a solution for this

@gizmocuz ,
Maybe it has something to do with the https://github.com/domoticz/domoticz/commit/8f9c93cca81c294c72fd033052978f6cfe7c8dc3# change in https://github.com/domoticz/domoticz/commit/8f9c93cca81c294c72fd033052978f6cfe7c8dc3#diff-af3b638bc2a3e6c650974192a53c7291 line 386 a line is added regarding binary directory

```


+ set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR})
+ #SET(EXECUTABLE_OUTPUT_PATH "" CACHE INTERNAL "Where to put the executables for Domoticz")


```

**Comment by jeroenkl** [comment]
New beta release 12117 works fine! Thanks!
![image](https://user-images.githubusercontent.com/37976568/83419796-f5096400-a425-11ea-8a23-3d7f1d942dca.png)

**Comment by gizmocuz** [comment]
Not really... Made another local patch
Very weird this started on 32bit build lately since I force the external dependencies to be up to date
Glad it is working
