### ISSUE TITLE
Change Lighting2/ZWave to General/Switch

### ISSUE THREAD

**Issue by gizmocuz** [domoticz/domoticz#419]
Going to change the current switch used in zwave to be a general switch.
This switch has 100 dim levels, and we could/should use this as a default dummy switch

**Comment by gizmocuz** [comment]
Just added a pTypeGeneralSwitch/sSwitchGeneralSwitch
When you now add a new switch from the dummy hardware, this is the default
This switch supports 100 dim levels
Next is to replace the Topic switch to this one and do a database migration patch as well

**Comment by nayrnet** [comment]
thank you, I will test this right away.
