### ISSUE TITLE
Support for intesis home IS-IR-WIFI1

### ISSUE THREAD

**Issue by kitopopo** [domoticz/domoticz#4193]
Dear @gizmocuz 

From January 1st 2020 Intesis is part of HMS Networks AB as an own business unit. I have been talking to a technician from the technical service of HMS NETWORKS AB and he tells me that he finds domoticz interesting and that he will speak to the development department from HMS to tell them.

We can see more requests for integration in the forum:

> https://domoticz.com/forum/viewtopic.php?f=31&t=32595

Is a possible integration of this system being studied? thanks in advance, kind regards

**Comment by gizmocuz** [comment]
@kitopopo , Maybe this is possible if they have a local working API for the device.
A quick read on the internet shows this could be possible.
It could maybe also work with IFTTT, if that is correct, you should already be able to control it

**Comment by kitopopo** [comment]
Hello, thanks for your answer, if control is possible by IFTTT, but it has its limitations and disadvantages, a direct integration would be much better, everything would work much better. Many users have requested this for a long time. Please value your integration in domoticz, we would be very grateful. thanks in advance and receive a cordial greeting

**Comment by sergio-bcn** [comment]
Appreciated @gizmocuz 
I would also be interested in having my Intesis Home IS-WIFI-IR  integrated in domoticz. Currently I have to use it directly through IS app, buy impossible to use with Domoticz. A direct integration would be interesting, since through all the ways I have tried the result has not been good.
Thanks in advance for your help!

**Comment by gizmocuz** [comment]
Could someone test if there is a local API ? And test if that is working ?
Or maybe we could get instructions from the technical team from HMS Networks AB (maybe a unit to test with)

**Comment by kitopopo** [comment]
> Could someone test if there is a local API ? And test if that is working ?
> Or maybe we could get instructions from the technical team from HMS Networks AB (maybe a unit to test with)

Hello dear @gizmocuz , thanks for your reply.

`https://www.domoticz.com/forum/viewtopic.php?t=28194`

In this issue in the domoticz forum the integration is also requested and it seems that intesis home if it has an API, it seems that several users with a phyton script have worked for them, I tried this some months ago but the plugin did not work for me  with the IS-IR -WIFI1, I will still look for information about the api if do you need it.  best regards

**Comment by kitopopo** [comment]
> Could someone test if there is a local API ? And test if that is working ?
> Or maybe we could get instructions from the technical team from HMS Networks AB (maybe a unit to test with)

Dear @gizmocuz ,

I can not test the api.  I have tried but no good news. This is the answer from HMS Networks:

```
Hi Enrique,

Our API is thought for professionals that want to offer AC integration into their systems. 

We understand the need of our clients to get IntesisHome working with different home automation systems so we have developed the compatibility with Siri, Google Assistant, Amazon Alexa and IFTTT.
In case you want to do an open-source integration, we have another line of product that might be of interest.
```

maybe you can get instructions from the technical team from HMS Networks AB with a unit test. 

Thanks in advanced. Best regards.

**Comment by gizmocuz** [comment]
Okey, it seems they don't want to open their API and have another product to implement in open-source.
So your best bed is now to use IFTTT.
For now I'm closing this issue, feel free to re-open when anything changes

**Comment by kitopopo** [comment]
Dear @gizmocuz ,


I have had email contact with an Spanish technician from HMS thanks to @sergio-bcn . 
He has answered me about the Intesishome Api and  about the request to include Intesishome in domoticz, I put his answer below:

```
I did not know your request to HMS, over the last few years we have been receiving requests from end users and programmers, mainly asking for a solution by Intesis with Domoticz, just as it happened with other known systems in Spain such as Eedomus and Jeedom and with which We got to develop drivers for these systems as you can see at: https://www.intesis.com/products/ac-interfaces/wifi-gateways

And here you can see the news from Jeedom-Intesa by WMP: http://www.domoticadomestica.com/plugin-oficial-jeedom-para-controlar-pasarelas-intesis/

That is why my colleagues had to suggest the other WiFi model (WMP - WiFi Multi Protocol) since it is practically the same as IntesisHome, only that WMP works locally with third-party systems such as those already mentioned, Fibaro, CRESTRON, Control4. .. or anyone working with ASCII-TCP.

The issue of the API with IntesisHome is somewhat delicate, we do not give access unless they are a company and in very specific cases such as for specific projects, that is, very few companies have access.

I would like to ask you if you or Sergi belongs to any company? Or make the request to us as end customers? It is to provide all the information to my colleagues.

From past experiences like Control4 and in Spain with Eedomus and Jeedom, I think the best thing would be to create a driver for Domoticz with our WMP gateways since if I'm not mistaken, Domoticz can speak in ASCII-TCP, that's why I would speak with my colleagues to transmit the market request to you.

In case you were a company, you could look at the API issue with IntesisHome but for this there should be a large demand for IntesisHome gateways.

Please let me know your comments about it
```

I am beginning to lose myself on what would be the best way to include Intesis Home in domoticz. 
If it seems good to you, I can tell the technician that you or someone else on your team will contact him. If you are agree I can send to you by private message the email address of the HMS technician   and you can speak with him about more technical details about the inclusion. I wait news from you.

Thank you very much in advance, again receive a cordial greeting.

**Comment by kitopopo** [comment]
dear @gizmocuz ,

As there is no way to send a pm through github I leave you here the email address of Kevin (HSM technician), His email address is keve@hms-networks.com, We would be very grateful if you could contact him to try an integration between Intesis Home and Domoticz. I cannot help anymore, I have done everything possible.
if you need anything else you can comment it here. Thanks in advance. A cordial greeting.

**Comment by kevin7benji** [comment]
Hello everybody!
@gizmocuz It is Kevin Vega working at HMS Industrial Networks in Barcelona (Igualada), manufacturer for Intesis brand, it is a pleasure to meet you. I have been talking these last days (if I am not wrong) with @kitopopo and @sergio-bcn about Domoticz topic. I also talked with a colleague who I work with in Iberia market to talk about it  and we would like to arrange a phone meeting with all of you in order to talk about it and check the possibilities to develop a Domoticz Driver for our Intesis gateway.
If you want, you can send me an e-mail to keve@hms-networks.com in order to arrange such meeting.

Thank you  so much and have a nice weekend!

Kevin Vega

**Comment by kitopopo** [comment]
Dear @gizmocuz  , 

How are you? I hope you are good
you said in your last message that we could re-open the isue if something changed, i can not re-open this issue. 
Now we have the collaboration of HMS staff to carry out the integration with intesis home. @kevin7benji has written to make a video call to discuss technical details about inclusion. would you be so kind to reopen the issue and reply?  Maybe i can open a new issue referencing this issue.
we are waiting news from you. Thank you very much in advance. Kind regards

**Comment by awalsum** [comment]
I'm considering buying a controller for my 3 multi-split indoor units, but am anxious to know if this is going to work. With native support through Domoticz, I trust it should work. I hope you guys can work something out.

**Comment by kitopopo** [comment]
Hello, 

the truth is that these units work incredibly well with splits and through the application of intesis home, I tried to get that @gizmocuz  to talk with HMS personnel for a possible native integration of domoticz but I do not know how the negotiations have ended. 
It would be very interesting to be able to make scripts in domoticz and that when opening a window the air conditioning stops, or for example that at a specific time at night or when the room temperature reaches x value the blinds are opened so as not to sleep all the night time with the air conditioning on. or for example that the air conditioners are turned off when leaving the house. An infinity of ideas. 
Until now I am still waiting for an native integration.

**Comment by gizmocuz** [comment]
@kitopopo , I can't remember I had contact with the manufacturer. (It has been a while)
Looking at this thread I see I did not.... I must have missed the replies... sorry.
It would be great if someone with this hardware could integrate/test this.
@kevin7benji , Sorry, I missed your reply. Much appreciated!

@awalsum , It looks you know some python. If the protocol is not that complicated you could try to add support for Domoticz.
I don't see a webpage on the Intesis website describing the protocol of the Intesis gateway

**Comment by kevin7benji** [comment]
> @kitopopo , I can't remember I had contact with the manufacturer. (It has been a while)
> Looking at this thread I see I did not.... I must have missed the replies... sorry.
> It would be great if someone with this hardware could integrate/test this.
> @kevin7benji , Sorry, I missed your reply. Much appreciated!
> 
> @awalsum , It looks you know some python. If the protocol is not that complicated you could try to add support for Domoticz.
> I don't see a webpage on the Intesis website describing the protocol of the Intesis gateway

Good Morning,
Do not worry @gizmocuz, in this link you have the protocol specifications for our WMP WiFi gateways: https://intesis.com/docs/wmp-protocol-specs

Thanks,

Kevin

**Comment by gizmocuz** [comment]
@kevin7benji , Looks like a very easy straight forward implementation ;) Going to send you an email

**Comment by kevin7benji** [comment]
> @kevin7benji , Looks like a very easy straight forward implementation ;) Going to send you an email

@gizmocuz Nice!! I am currently on vacations and I come back on Tuesday 1st September but you can also send an email with me in copy, to my colleague Mauro Dion at mdao@hms-networks.com
I talked about this topic to him some time ago, he will be able to explain you anything you need

**Comment by gizmocuz** [comment]
@kevin7benji , already send you an email ;) Maybe you could forward it

**Comment by kevin7benji** [comment]
@gizmocuz I have just forwarded to my colleague, you will be contacted soon

**Comment by awalsum** [comment]
> 
> 
> @awalsum , It looks you know some python. If the protocol is not that complicated you could try to add support for Domoticz.

I mess with Python a little, but I'm not real familiar with the socket part of it. I also don't have an Intesis unit yet to test anything. I have asked a local air conditioner installer about acquiring a unit, but I haven't heard back from him yet. When I wrote the Qlima Python script, I was able to test what I was doing, which made it a lot easier.

**Comment by RDols** [comment]
Hello,

Isn't "AirconWithMe" a product of intesis ?

I Recently have bought airco units with a "AirconWithMe" module inside. I'm have implemented this as a native type in Domoticz, and currently testing it. It directly communicates with the module on the local ip using the web interface (api.cgi). (Note this code isn't merged yet into the development branch.)

I'm not sure if this works the same for IS-IR-WIFI1 and other modules, but a good change it does.

my development branch:
https://github.com/RDols/domoticz/tree/AirconWithMe

Btw. I looked at the WMP document. But my module does not have listen port on 3310.

**Comment by RDols** [comment]
@kitopopo, 
is it possible to check if the following works on your module?

1. using a web browsers go the local ip address of the module.
2. logon with user: Operator password: operator
3. Then select "Signals" in the top, and you can see the settings?

**Comment by kitopopo** [comment]
> @kitopopo , ¿
> es posible verificar si lo siguiente funciona en su módulo?
> 
> 1. utilizando un navegador web, vaya a la dirección IP local del módulo.
> 2. inicio de sesión con usuario: contraseña de operador: operador
> 3. Luego, seleccione "Señales" en la parte superior y podrá ver la configuración.

Dear @RDols ,

I can't connect trought IP with my 2 modules IS-IR-WIFI1. I get the message cannot access this website. ERR_CONNECTION_REFUSED. 
The only way (that I know of) to connect to the module through IP is when I am pairing it with my network because the module generates a wifi point to configure it. But I think it works something different than other devices, it is necessary to first connect to the wifi point device and then open the "ihconfig.com" address for configure it. I attach the user manual link. 

https://www.intesishome.com/docs/IS-IR-WIFI-1_User_Manual_esp.pdf

Maybe @kevin7benji maybe kevin knows a way to make this possible?

Thanks for your help. a cordial greeting

**Comment by RDols** [comment]
I also send an email to Kevin and Mauro. I expect simular answer that they don't have same interfaces. In that case i keep de "AirconWithMe" seperated.

**Comment by kevin7benji** [comment]
Hello @kitopopo and @RDols ,

Excuse me the delay in my answer, I just came back yesterday from my vacations.
First of all, please note that we have two WiFi models for air conditioning machines, IntesisHome (IS-IR-WIFI-1) and WMP (IS-IR-WMP-1), they are similar phisically but Intesis Home is related to a cloud service and our APP, you can access through web, app to your device connected to such cloud. It is native compatible with Amazon Alexa, Google Assistant, Siri Shortcuts and IFTTT. With IntesisHome you can not connect via IP, according your comment you have been doing requests to your IntesisHome but IntesisHome did not answer you because it can not listen to you for being a complete solution already programmed: https://www.intesishome.com/

Meanwhile WMP (which works over) ASCII/TCP is not related to any cloud server or APP, is composed of a public protocol so that you can create a Driver and you can integrate them into a third systems like Control4, Eedomus, Vera and many more, if Domoticz develop his driver you will be able to integrate perfectly and natively your air machines with Domoticz.
With WMP you must program other device with ASCII driver. With this solution, you can program a device with ASCII driver (Several easy commands) and make run your Air conditioner, in this link you have the models available, the last one of the list is the IS-IR-WMP-1 (Official Order Code INWMPUNI001I000), in the documentation of each product you have the protocol specification, user manual...: https://www.intesis.com/products/ac-interfaces/wifi-gateways
WMP devices stablish a TCP connection (Port 3310).

At last but not least, Airconwithme is Low version for IntesisHome device, it is a solution we manufacture but it is only supplied by Mitsubishi Heavy Industries, with Airconwithme nor full IntesisHome version you will not be able to connect with Domoticz, with WMP you will.

If you have any doubt please, let me know.

Thank you!

Kevin

**Comment by kitopopo** [comment]
Hello dear friends, 

I think that throughout the trajectory of this post we have been deviating a lot. The request of the initial post was to be able to include the IS-IR-WIFI1 module to domoticz, but not a new module called IS-IR-WMP-1. I think that all of us who have the first module are not going to get rid of them and now buy new gateway modules, I think it is not available to everyone. Is there no way to integrate the first module? maybe through the API? perhaps this may not be possible due to HMS business reasons or internal policies. I thought it was easier to do a native integration

In any case, I am not opposed to the integration of the second WMP model, there may be other people who are interested, but from my point of view I think the most economical solution is to use a broadlink RM4 mini for have a comunication between domoticz and IS-IR-WIFI1. 

Thank you all for your work and collaboration. I am very grateful for the collaboration of all of you.

Best regards

**Comment by gizmocuz** [comment]
@kitopopo , the RM4 mini could probably directly control your HVAC device (it's a nice device once you get it working)

**Comment by kitopopo** [comment]
> @kitopopo , el RM4 mini probablemente podría controlar directamente su dispositivo HVAC (es un buen dispositivo una vez que lo hace funcionar)

@gizmocuz ,Yes, I think it is the most economical solution if the IS-IR-WIFI1 module cannot be integrated, everyone speaks highly good of the RM4 mini, thanks,

Best regards

**Comment by awalsum** [comment]
The RM4 mini won't report a status from the air conditioner back to Domoticz, if I'm correct. That's a functionality I would really want because it assures me that the sent command was also received, but also in the event that the unit was operated with the IR remote. I hope @gizmocuz and @kevin7benji can work things out for the WMP modules.

**Comment by kitopopo** [comment]
> El RM4 mini no informará el estado del aire acondicionado a Domoticz, si estoy en lo cierto. Esa es una funcionalidad que realmente me gustaría porque me asegura que el comando enviado también se recibió, pero también en el caso de que la unidad se operara con el control remoto IR. Espero que @gizmocuz y @ kevin7benji puedan resolver las cosas para los módulos WMP.

Hi dear friend,

I don't know if the RM4 report the status of the air aconditioner, probably no, but you can open the intesis home app and see the status, the intesis home app report the status correctly after send a remote control order. I have test this now and the intesis home app report correctly (IS-IR-WIFI1 module).

I would like to make it clear that I am not opposed to the negotiations between the two companies continuing and I hope they will continue to integrate the new WMP gateway since many other users may be interested, like you. I simply comment on the most economically affordable option that I am going to opt for. a cordial greeting

**Comment by awalsum** [comment]
I'm wondering if anything is still happening on this front? Been quiet for a while.

**Comment by kevin7benji7** [comment]
> > @kitopopo , el RM4 mini probablemente podría controlar directamente su dispositivo HVAC (es un buen dispositivo una vez que lo hace funcionar)
> 
> @gizmocuz ,Yes, I think it is the most economical solution if the IS-IR-WIFI1 module cannot be integrated, everyone speaks highly good of the RM4 mini, thanks,
> 
> Best regards

@gizmocuz @kitopopo @waltervl @RDols Hello Sirs, it is Kevin, I am the person who you were talking about in 2020 about the possibility toe make the integration of air conditioenrs into Domoticz through IntesisHome solution but it was not possible. Now I am not working at Intesis anymore but I am working in Airzone. I do not know if you could find a solution to make such integration, if not, I wanted to retake this topic to inform you that we have a similar solution with a public API to make the integration you need, here you have our API: https://developers.airzonecloud.com/docs/local-api/#servers

Furthermore, in case you also work with Zigbee, we are about to realease the Airzone air conditioners gateways per each AC brand to integrate in Zigbee. 

In case you need, my e-mail is kvega@airzonecontrol.com 
Do not hesitate to send me your inquiries here or by e-mail or even whats/telegram

Thank you!

Kevin

**Comment by gizmocuz** [comment]
@kevin7benji , if you make a Zigbee device, and it is working with Zigbee2MQTT it will work in Domoticz
If you want to write yourself a plugin to work with your hardware, you can use python, or use a ESP32 and MQTT Auto Discovery

**Comment by kevin7benji7** [comment]
This week we have launched our Zigbee gateway for Air conditioners: https://www.airzonecontrol.com/ib/es/soluciones-de-control/aidoo/zigbee/

Not yet but this gateway will be compatible with Zigbee2MQTT.

As I said, we put our gateway as at your disposal, whether Zigbee, Z-WAVE or our Local API with free access in case you are interested in doing something to control the air conditioners from your system, I was just writing to inform you. Thank you
