### ISSUE TITLE
Crash on pi upon program termination when using mydomoticz

### ISSUE THREAD

**Issue by rkluwen** [domoticz/domoticz#420]
![image](https://cloud.githubusercontent.com/assets/5295912/12842756/01d7539e-cbf5-11e5-9737-f86b603c5781.png)

**Comment by gaudryc** [comment]
Did you update your domoticz since 8 days ?

**Comment by rkluwen** [comment]
I didn't. Maybe someone else updated the domoticz proxy code. But I doubt itm looking at the repository. Why did you ask?

**Comment by rkluwen** [comment]
Created pull request https://github.com/domoticz/domoticz/pull/503
