### ISSUE TITLE
Counter- type counter divider not working/implemented

### ISSUE THREAD

**Issue by reinos** [domoticz/domoticz#4201]
When creating a RFXMeter counter with type "Counter" the "Counter Divider" doesn't work.

See https://www.domoticz.com/forum/viewtopic.php?f=6&t=30760&p=232637 and https://www.domoticz.com/forum/viewtopic.php?f=6&t=32929&p=249487

Is this an known issue?

**Comment by gizmocuz** [comment]
What type of device you are trying to display with the counter type ?
This because the counter type is used for counting, like how many apples fall from the tree today,
or how many times someone walked into a room

**Comment by reinos** [comment]
Good point. Its about the profit of my solar system in EUR. I did try it first with the custom sensor, however, that is in fact a percentage sensor and does not show well the profit per day.

What I want is that it shows the value in a bar graph instead of a line graph.

For example the GAS from the P1 is a good example how I'd like to show my profit.

![Screenshot 2020-06-03 at 08 20 37](https://user-images.githubusercontent.com/633730/83602678-512dce80-a573-11ea-81fa-e7b68428f935.png)

as currently it shows it this way

![Screenshot 2020-06-03 at 08 20 57](https://user-images.githubusercontent.com/633730/83602712-5ee35400-a573-11ea-8284-6df2f824db99.png)

Is there a way to show the graph for my profit in the way the GAS is showing? And if possible to handle values like `0.01` EUR or `0.50` EUR or `1.08` EUR (with decimal)

(still, I think the divider of the custom type of the counter does not work or I misused it 🙈,)

**Comment by gizmocuz** [comment]
Maybe the option should be hidden when the counter type is selected...
You have to use the General/kWh device type for this, edit it once added, and change the type to 'return'

**Comment by reinos** [comment]
Thanks, but I have that one already in place to log the kWh of my solar system. This time I want a sensor that can calculate the profit in EUR. And for `General/kWh` I cannot set the divider (its `1000` instead of `100`) and I cannot set the unit (it should be `EUR` and not `kWh`)

> Maybe the option should be hidden when the counter type is selected..

Yes as this is very confusing.

**Comment by gizmocuz** [comment]
OK understood ... so basically you would like to see the option to change the graph type of the custom sensor between line/bar ?

**Comment by reinos** [comment]
Yes 😄 , just like the example of the P1/Gas

![Screenshot 2020-06-03 at 08 20 37](https://user-images.githubusercontent.com/633730/83609461-a1f6f480-a57e-11ea-96e7-5260c4197d7e.png)

**Comment by reinos** [comment]
After thinking about this again. Why not fixing the divider as that counter sensor should show a bar graph. I use one for my solar and set the type to `energy generated` and that worked great! just what I needed 

So I think, but I cannot see how this translate to the code, by fixing the divider for the type `counter` should solve my issue as I set the divider to `100` so I can feed the sensor euro cent values. 

Here https://github.com/domoticz/domoticz/blob/development/main/WebServer.cpp#L10067-L10074  and here https://github.com/domoticz/domoticz/blob/development/main/WebServer.cpp#L10110-L10116 I think.

Also it should be nice to have a custom image when selecting the type `counter`.

What do you think?

**Comment by gizmocuz** [comment]
@reinos , going to have a look at the divider now... need to make some dummy data first.
No custom image support for counters at the moment.
When you set it to 'Energy Generated' you already has a custom icon (compared to normal counters)

**Comment by reinos** [comment]
Great! let me know.
Yes, so it would be nice (and I think possible) to add a custom icon by yourself if you set the type to `counter` 😊

**Comment by gizmocuz** [comment]
@reinos , this divider change needs to be done on much more places then just those two locations
I am also not able to verify this.
Are you able to compile yourself ? Could you contact me on the forum (PM)

This is a test counter with the divider set to 1000

![image](https://user-images.githubusercontent.com/2265299/83843581-92ee7e80-a705-11ea-9a38-34a8ce2aa5b0.png)

Made a new test branch here:

https://github.com/domoticz/domoticz/tree/counterDivider

If you send me a message, let me know here as i do not read PM's frequently

**Comment by reinos** [comment]
Hi @gizmocuz I have no idea how to test it. I have a Raspberry PI working in production and no device to test on... 😞  

I'd hoped that it was just a simple changes for you man 😅

**Comment by gizmocuz** [comment]
@reinos , did you send me a PM on the Forum ?

**Comment by reinos** [comment]
No, it seems I cannot send you a message...

> We are sorry, but you are not authorised to use this feature. You may have just registered here and may need to participate more in discussions to be able to use this feature.

**Comment by gizmocuz** [comment]
I see you just registered ... I send you an email...
