### ISSUE TITLE
Domoticz WebServer Crashes

### ISSUE THREAD

**Issue by TheItschi** [domoticz/domoticz#4211]
Version: 2020.2 (build 12100)
Platform: Windows 10 Pro

Description:

I'm have a strange issue when saving changed scripts or changing the value of a user variable using Domoticz web interface. Sometimes it works but in most cases the web interface immediately stops working when doing so. There is nothing special to see in the console log but the following message appears after about 60s: "Error: WebServer:8080 thread seems to have ended unexpectedly (last update 60.000000 seconds ago)".

The only way to get the web interface working again is killing Domoticz process and start it again. Trying to end Domoticz by the console menu ends the icon but Domoticz process keeps running.

I'm having that issue since a couple of releases including the last stable and the current mentioned above. Any idea how I can solve this?

**Comment by gizmocuz** [comment]
Could you disable the event/dzvents system in the settings, then restart Domoticz
And then change a value or change a script ?

**Comment by TheItschi** [comment]
dzvents was already turned off, but disabling "Lua, Blockly, Scipts" let the Web Server crash. Howerver the settings where all off after restarting Domoticz and I could change variables & scripts without  any issues. 

After reenabling "Lua, Blockly, Scipts" in settings I found an "EventSystem - Python: Failed dynamic library load, install the latest libpython3.x library that is available for your platform." entry in the log.  A second restart of Domoticz solved that problem and all scripts are running again (including the Python scripts). Unfortunately now Domoticz Web Server crashes again after almost any change of a script or an user variable.

**Comment by TheItschi** [comment]
Anything else I could do to help finding the issue?

**Comment by Tontze** [comment]
I have similar issue, everytime i change something in settings and save, domoticz is not reached anymore. Restarting domoticz brings it back. 

 Domoticz V2020.2 (build 13104)

**Comment by kiddigital** [comment]
@TheItschi , still an issue?

**Comment by TheItschi** [comment]
Unfortunately yes.

**Comment by gizmocuz** [comment]
@TheItschi , please do not reply by email as this will also include personal information.
What version are you currently using ? Could you try the latest beta version as we made some fixes in this version related to the webserver.
If it still gives issues, do you have some steps to reproduce it ?
