### ISSUE TITLE
Error: OpenZWave: Type_Notification, NodeID not found internally!. HomeID: 0, NodeID: 255 (0xff)

### ISSUE THREAD

**Issue by walawa75** [domoticz/domoticz#4214]
Since the 2020.1 update I get this error ramdomly when I reboot the Raspberry Pi. Then no device loaded in OZW dasboard and nothing works.
A simple reboot/service restart can solve the problem.

My USB port for UZB key is permanent but no more chance with that. Please fix that !!

**Comment by bikeymouse** [comment]
I can report that this is a common issue, which I also reported[ earlier](https://github.com/domoticz/domoticz/issues/4192), together with another issue (not being able to remove a node) which was closed.
