### ISSUE TITLE
If restarting Domoticz during Switch Delay Off timer, then Switch stays on forever.

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#4218]
If lets say you have started a Switch set with xxxx seconds Delay Off, then a Power Outage, Crash Reboot or Manual Reboot happens to your Domoticz Server. After that the Timer is lost and Switch seems stay on forever...
I guess Timers in Domoticz is "simple" counter sessions not stored in the database?

I would suggest the present Timer function to be changed into Scheduled Events, to be more reliable.
Also showing the Switch set Timer "Remaining time" and "Due time" would be great.

**Comment by RicardP** [comment]
@gizmocuz any comments? :)

**Comment by gizmocuz** [comment]
Yes, This is not going to happen. If you have a power outage, or whatever reason, the switch should stay as it is.
This is also for zwave switches, (and maybe others), it keep's it's state

**Comment by RicardP** [comment]
@gizmocuz sure I know physical devices have often possibilities to set remember last states and other parameters. However I meant Delay Timers within Domoticz:

![bild](https://user-images.githubusercontent.com/21274628/84112270-b6c50380-aa28-11ea-8656-a4255fe1d69f.png)

**Comment by gizmocuz** [comment]
Yes that is also not what you want... Imagine you have a physical switch that was "On" and you had a off delay going on in 3 minutes.
Now you get a power failure, your whole house is dark, power goes on, physical switch goes on (last state), you don't want that to go off in 3 minutes (I don't)
Now I see you have a off delay for 8 hours... that is a lot... and can understand your problem.
But most people have a value between 10 seconds and 5 minutes
Not sure what type of device it is, but you could also add a timer to turn it off at fixed times

**Comment by RicardP** [comment]
The device is a Virtual Switch used in a Blockly script for controlling a Hot Tub 4KW water heater.
I am not using any such Timer delay for just Lamps. I am using also for Floor Heating and Infra Heaters in the Garden Room. I don' really buy your scenario to support the present behavior. I do not arguing what is right or wrong for you, but in my opinion if a function is lost by an reboot then it is an issue.

**Comment by gizmocuz** [comment]
In your case it is a virtual switch, in other cases a real switch, there is no difference

**Comment by RicardP** [comment]
@gizmocuz Yes I know, I just explained exactly my setup. 
But you do still not agree it is an issue when functionality is altered by a Restart like it is now?

**Comment by gizmocuz** [comment]
No sorry, I think this is a good behavior. Anything could happen with a switch, it's not safe to do so

**Comment by rwaaren** [comment]
@RicardP if you are interested in an approach, where you can define a maxOn time for switches, that is persistent over system reboots; there is a dzVents script available for that. 
Just continue the discussion in the [forum post](https://www.domoticz.com/forum/viewtopic.php?f=31&t=25276) you opened back in 2018 on this topic.

**Comment by RicardP** [comment]
@gizmocuz if an unforeseen reason restart Domoticz I think Domoticz (or any system) primary should be designed to be restored to previous state. Or even better adding an User Option to chose what should happen after restart. Sorry, I don't understand what you mean "anything could happen to a switch"?

**Comment by RicardP** [comment]
Here is my involved Blockly, just for your reference it works perfectly and I have no time to learn DzVents in the near future :)

![bild](https://user-images.githubusercontent.com/21274628/84129349-25fb2180-aa42-11ea-8e1b-4a473cf579fc.png)

**Comment by gizmocuz** [comment]
Maybe you could make a PR with the needed changes ? Then we can review it

**Comment by RicardP** [comment]
@gizmocuz I am not skilled in software development unfortunately. Don't take me wrong, I do not demand you or someone else to work for my interests :) I just wanted to point out the consequences of present method in my setup. And I wanted to give an idea for possible future improvement.
Thanks for your feedback and consideration! :)

**Comment by gizmocuz** [comment]
I think it is a very dangerous option...
There are to many rules to look at in your script, but dzVents is quite easy to understand and easier to follow
If this is about getting your pool up a (constant) temperature, you could also use a smaller off-time, like an hour, or even shorter (30 minutes), via dzVents you let your script check every 30 minutes and if needed turn on the heater (and the off timer for 30 minutes)
So when you have a power outage, it might not be heated for max. 30 minutes (depending where in the 30 minutes you have a power outage)

Or you could make a PR where you store the current schedule states to disk every minute, and at start reload them, but i think it's dangerous
