### ISSUE TITLE
Device not found for disabled hardware with timer

### ISSUE THREAD

**Issue by bikeymouse** [domoticz/domoticz#4219]
Version: 2020.2 (build 12067) and earlier.
Hardware: Raspbery Pi 2B+/3B+

I have disabled some hardware on my (test) system. 
Now I get errors because the system is still trying to activate this hardware because there where timers set on those switches:
`Error: Switch command not send!, Hardware device disabled or not found!`

IMO, this is a bug: if hardware is disabled, the timers for this hardware should be disabled as well. Or alternatively: the timer routine should check if the hardware is enabled/present first.

**Comment by bikeymouse** [comment]
Bump: any remark/insights if this is "by design" or indeed a bug that is going to be solved?

**Comment by rwaaren** [comment]
The message you see is in fact the result of the check if the hardware is enabled/present. No activation is done.
The timers are set on device level and when you disable hardware, it is a user responsibility to disable 0 or more attached devices.

**Comment by bikeymouse** [comment]
Thanks for your answer. However If in fact the message is the result of the check, then there is no exception. 
So why throwing an error and filling up the log and not just don't activate the device?

**Comment by rwaaren** [comment]
Because the designer of this part of domoticz considered it prudent to inform the user that this potential unnoticed situation occurred.
