### ISSUE TITLE
Data record in 'LightingLog' table if no hardware is accepted

### ISSUE THREAD

**Issue by laoranz** [domoticz/domoticz#4220]
Domoticz version: 2020.2

In the database, I have in 'LightingLog' table, some records with DeviceRowID=1.84467440737096e+19 (ie: 0xffffffffffffffff)

The problem seems to come from the function : uint64_t CSQLHelper::InsertDevice(...)

If not new hardware is allow, -1 is return (i.e. 0xffffffffffffffff in uint64_t).
`
	if (!m_bAcceptNewHardware)
	{
		return -1; //We do not allow new devices
	}
`

But in the function CSQLHelper::UpdateValueInt, a test is done to determit if the insert has success.
And this test check if result is minus 1 : 

`
	ulID = InsertDevice(HardwareID, ID, unit, devType, subType, 0, nValue, sValue, devname, signallevel, batterylevel);

	if (ulID < 1)
		return -1;
`

So with value of ((uint64_t) -1) the test pass true.

And data can be record in database.

**Comment by waltervl** [comment]
So how to reproduce this issue? 
What is the risk if it is not solved?
As you have investigated it already, do you also have a proposal to solve it?
