### ISSUE TITLE
RFXCom - Novy Hood support

### ISSUE THREAD

**Issue by Maeslant** [domoticz/domoticz#4222]
Since last year the RFXCom firmware/software support Novy hoods. Can this be added to the RFXCom support.

See [Forum](https://www.domoticz.com/forum/viewtopic.php?f=31&t=31220)

**Comment by gizmocuz** [comment]
According the User Manual you should also be able to receive this device.
What happens when you press a button the remote ? Do you get a new device ? (Make sure you have enabled accept new hardware/devices in the settings)

**Comment by gizmocuz** [comment]
Also try with the latest beta version (version 12138 or higher) added some support
If you do not receive it, try adding it manually from the Lights/Switches page (top left button)
If you press the 'test' button, and it works, you should be able to use the JSON commands to send a switch command (nvalue = 1 till 4) (5=learn, not sure you want to use this)
If that is working, I think you should be able to add a selector switch to Domoticz, and create 4 actions for each function
(See the RFXMngr application for the functions)
Let me know if it worked... or not ....

**Comment by Maeslant** [comment]
Updated to 12138.

If I ask to learn log shows;
ERror: RFXCOM: Invalid data received!...

If I add the novy through the manual add, I can't use the test button. This
does not work.

For the RFXCom manager, I got these codes from RFXCom.

**Comment by gizmocuz** [comment]
I have no idea what those codes are ? What are these numbers ?

Do you have the latest firmware ?

The RFXCom manager should display packets/structures from type Fan

**Comment by Maeslant** [comment]
Those are RAW transmit codes. If I go to RAW transmit, I open such
code and it works.

**Comment by Maeslant** [comment]
![rfx](https://user-images.githubusercontent.com/59930296/84161623-c0be2500-aa6f-11ea-91e5-b773e00ecfb1.JPG)
![afzuig](https://user-images.githubusercontent.com/59930296/84161626-c156bb80-aa6f-11ea-875d-7a0fc0b59ec6.JPG)

This is for Domoticz
 
I can select Novy and a selector switch, but when I use test it does not work. I tried changing id= 1 (in 3 different fields) does not work either.

**Comment by Maeslant** [comment]
![novy](https://user-images.githubusercontent.com/59930296/84162031-36c28c00-aa70-11ea-99fb-3c353164d075.PNG)


In this screenshot it shows the ID=1. Do I fill this in anywhere?

**Comment by gizmocuz** [comment]
Yes in the last dropdown so 00 00 01

**Comment by gizmocuz** [comment]
I see a wrong type in the screenshot, not the Novy but Lucci Air DCII...
Could be a problem inside Domoticz or you selected a wrong fan type

Looks like the last gui code was not commited... please upgrade to version 12143, when you now test/add the manual Novy switch, it should say Novy
Build systems are building, could take up to 15 minutes

**Comment by Maeslant** [comment]
Many thanks! I added the Novy and used an selector switch.

Added 4 steps with a json for a custom sensor. What even I do (which switch or both JSONs) it goes on/off. 
Am I missing the last step?

![json](https://user-images.githubusercontent.com/59930296/84189855-3d63fa00-aa96-11ea-9d94-ad8ed1704e7b.JPG)

**Comment by gizmocuz** [comment]
@Maeslant , when you added the manual Fan, and pressed the 'test' button, did anything happen on the Actual Fan ?
I think you can use http://127.0.0.1 or https://127.0.0.1 as it will be a internal call
In the device overview, the new fan has IDX = 10 ?
When you enter that command in a browser , does it work ? Do you see anything in the log when you issue that command ?
Only nvalue=2 or 1 is good , 1 = power, 2=plus 3=min 4=light

**Comment by Maeslant** [comment]
I added a manual fan, I pressed the test button and it turns on (or off, depending on how many times you push the button).

So the connection works.

Now my new fan has IDX=10. It is a selector Switch, and I made 4 additions. (And off).

When I use JSON as show in the screenshot, it just turns on. I can use the JSON locally and it comes back;


  |  
-- | --
status | "OK"
title | "Update Device"


(I'm sure the IPs are OK, as I tested it with a scene command.)

Summary, On/Off works. I can not use the buttons 1-4 as described.

**Comment by gizmocuz** [comment]
@Maeslant , that's good news, so the connection works, now only the json needs to be solved.
I think it fails because it is a selector switch, could you for the test, make it a normal on/off switch and test the json (nvalue = 1 till 4)
If that works, i think the json call for a selector switch is different

If you set the type back to selector switch, follow the wiki documentation for the selector switch:

https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Selector_Switch

/json.htm?type=command&param=switchlight&idx=10&switchcmd=Set%20Level&level=LEVEL

LEVEL = level of your selector (This number can be found in the edit selectors page, in the column "Level", 0 = Off)

Almost there...

**Comment by Maeslant** [comment]
I think I understand.

So made a new on/off switch; IDX13.

https://10.0.1.5:8443/json.htm?type=command&param=udevice&idx=13&nvalue=4 

nvalue = 1 -4 tested. See the pictures, it does work in Domoticz, only the Novy Hood does not get the input. So nothing happens.

If I push the lightbulb on the Switch, it turns on and off. So the communication works with Novy for on/off, but not for JSON. (nValue=1 is Power, does not work)
![code4](https://user-images.githubusercontent.com/59930296/84352301-63d08500-abbd-11ea-9550-1752a1c4d12a.JPG)
![code1](https://user-images.githubusercontent.com/59930296/84352302-64691b80-abbd-11ea-831c-885a986a3415.JPG)
![code2](https://user-images.githubusercontent.com/59930296/84352304-6501b200-abbd-11ea-8415-0d31effdea4f.JPG)
![code3](https://user-images.githubusercontent.com/59930296/84352306-6501b200-abbd-11ea-9d73-6924fdbf489d.JPG)

**Comment by gizmocuz** [comment]
I think i know why this happens, it is because the value is put in the database directly (udevice) and there is no actual switch command
could you try this:

/json.htm?type=command&param=switchlight&idx=13&switchcmd=power
/json.htm?type=command&param=switchlight&idx=13&switchcmd=light
/json.htm?type=command&param=switchlight&idx=13&switchcmd=plus
/json.htm?type=command&param=switchlight&idx=13&switchcmd=min

**Comment by gizmocuz** [comment]
I will see if i can fix the udevice for switches here

**Comment by gizmocuz** [comment]
If that works, just create a dummy selector switch and use the above 4 commands as level actions (with 127.0.0.1 i suppose)

**Comment by subtrEM** [comment]
> Yes in the last dropdown so 00 00 01

FWIW, 01 00 00 is the code that seems to work.

Also, the dummy selector with 4 commands does work.
