### ISSUE TITLE
Red/green icons in energy generated report incorrect.

### ISSUE THREAD

**Issue by gimbal2000** [domoticz/domoticz#4224]
I have an 'energy generated' utility device 
![afbeelding](https://user-images.githubusercontent.com/25183058/84168383-a38d5480-aa77-11ea-8324-31cc9910e2f0.png)

I noticed however that in the 'Report' screen the red/green arrows are incorrectly colored. An increase is a positive thing for energy generating devices, and should be green I think :-)
But the icons are colored as if it was a energy 'used' device:

![afbeelding](https://user-images.githubusercontent.com/25183058/84168593-e3543c00-aa77-11ea-8382-a93462cfa1e1.png)

**Comment by gizmocuz** [comment]
A increase in energy used is bad for the wallet

**Comment by gimbal2000** [comment]
> A increase in energy used is bad for the wallet

True, but an increase in energy _generated_ is **good** for the wallet :-)

**Comment by gizmocuz** [comment]
Yes very true ;) Icons should be swapped then ;)

**Comment by gimbal2000** [comment]
I don't want to be anoying, but I would prefer to only swap the colors; as an increase in energy generated (compared to a prior month) remains an _increase_. 
Only the fact that it is a positive thing instead of a negative thing is different :-D

**Comment by gizmocuz** [comment]
Thats what i meant as well

**Comment by gizmocuz** [comment]
Implemented in beta 12154
