### ISSUE TITLE
defender detection in latest Win version : Wacapew.C!ml (2020.2.12164  2020-06-12 )

### ISSUE THREAD

**Issue by sledgemhammer** [domoticz/domoticz#4233]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

Hi,

Just downloaded the latest windows installer archive

2020.2.12164 |   | 2020-06-12 |   | 12,27 MB

I get a defender warning about Win32/Wacapew.C!m detection inside the archive file
Googling that name , it seems to be related to phishing & trojan

Tried to download again...same result

Now scanning my test system (where domoticz is the only use. & no email on that system)
Result : No infections, only the zip file that was downloaded.

Is this a false positive ?

**Comment by rwaaren** [comment]
> 
> Is this a false positive ?

Yes. Is there already for a long time. I use AVG internet security on my Windows systems and they always want to analyze it in there labs and after a couple of minutes they come back that no threat is found.
