### ISSUE TITLE
Timer on Groups/Scenes mallformed/broken

### ISSUE THREAD

**Issue by sledgemhammer** [domoticz/domoticz#4235]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

Version: 2020.2 (build 12164)
Build Hash: 2aae3498e
Compile Date: 2020-06-12 07:02:29
dzVents Version: 3.0.9
Python Version: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 15:51:26) [MSC v.1900 32 bit (Intel)]

{{ ::'Name'|translate }}: {{::vm.itemName}}

Blue buttons also mallformed, sunset starts mallformed but is corrected after 1 sec.
see screenshot. Only on this tab and only on timers, all others work fine
Just updatet to latest beta, cleaned all history and empty cache, but stil same issue 

![Knipsel](https://user-images.githubusercontent.com/36365231/84591938-81fae700-ae42-11ea-95fa-3ddb75e78376.JPG)

**Comment by rwaaren** [comment]
Please use the forum.

These GUI issues are 99 out 100 times related to browser cache / appcache (different things)

**Comment by qweluke** [comment]
I had the same problem, pressing shift+command+r solved the issue
