### ISSUE TITLE
lua scripts: otherdevices_svalues returns very high value for incremental counter

### ISSUE THREAD

**Issue by niziak** [domoticz/domoticz#4236]
I have one virtual meter "Counter Incremental" to show energy usage in kWh. It is receiving delta pulses using HTTP from ESP8266. This works perfectly for years and this meter show correct values.

Additionally I have another virtual meter "Usage (Electric)" to show current power. It derives power from previous meter using LUA script. And it was working until update from v4 to 2020.1. Now in LUA scripts 
value of Counter Incremental is wrong and very high I cannot get direct pulse count. Debug logging from LUA scripts shows:
`otherdevices_svalues['Energia'] = '18446744073705951732'`
previously it was sth like:
`otherdevices_svalues['Energia'] = '2.00'`

**Comment by gizmocuz** [comment]
Maybe you have to post the complete script.
Your script is using/calculating '18446744073705951732' ? Then it seems a script issue

**Comment by waltervl** [comment]
No feedback, issue closed
