### ISSUE TITLE
Notifications via browser

### ISSUE THREAD

**Issue by rkluwen** [domoticz/domoticz#424]
I have an idea that someone might want to pick up: Browser notifications. Something like https://jsbin.com/ziwod/2/edit?html,js,output.

If nobody does, I will check it eventually. But that will be after the event driven javascript app is ready. Which probably takes some months.

Here some developer documentation about the pluggable notification system. I wrote it whilst originally implementing this. Maybe it is of use to somebody.
I copied it from a Word document, so the layout may not be 100% optimal:

https://docs.google.com/document/d/15QjkBantPgWIwTnZD9TJi-ohijztwJ8rfjOrBHrofx4/edit?usp=sharing

**Comment by gizmocuz** [comment]
Nice idea, but do you think a lot of users are sitting in front of a browser and waiting for notifications ?
The current notification implementations can also give a desktop notification, or a mobile/tabled notification, is this not enough ?
