### ISSUE TITLE
rtl_433 pressure PSI is not used

### ISSUE THREAD

**Issue by dgrostoto** [domoticz/domoticz#4241]
Hello,
I wondering about the the change https://github.com/domoticz/domoticz/commit/52a25d7e0228074a1535bc8020def7cddfd33e6d#diff-1d55c8017a05ee6441de14038af3fce4
I guess it is not usable since rtl_433 won't send any PSI metrics. (it is kpa if my memory is good).
Because PSI is not part of the international metric system. (required when calling rtl_433 with -C si).
If rtl_433 send PSI data, i think this is probably a bug from rtl_433 side (i can correct it if this is the case).
Do you remember why this change happened ? (did not find any issue related to this).

**Comment by gizmocuz** [comment]
@dgrostoto , I received a bunch of these packets and added it to the system.
We try to implement as much protocols as possible

**Comment by dgrostoto** [comment]
I think the packet you received were sent from an old version of rtl_433. I personally checked all units and all protocols from rtl_433 (the newmodel of rtl_433 which comes with ), and the PSI unit cannot occur with the correct version. My last PR in domoticz about rtl_433 worker was exactly to include all units that comes with the -C si option of rtl_433 (international system) so we don't have to deal with (on domoticz side only one unit for each type of measure (pressure/temp/humidity/moisture etc..)
That was to goal to simplify and deal with a unified set of units which does not care about the sensor reported be rtl_433.
WIth PSI (which is not indeed a protocol but just a unit type), it makes two different units for the same measure (pressure) : kPA and PSI.
The only measure which will be sent by rtl_433 for pressure (whatever the sensor it comes from) is in kPA.
