### ISSUE TITLE
DzVent complains that there is no sunset in the arctic

### ISSUE THREAD

**Issue by Strangeloff** [domoticz/domoticz#4242]
My logs are filling up with this error, and I suspect it is causing delays when running scripts:

"Error: dzVents: Error: (3.0.2) No information about sunrise and sunset available. Please set lat/lng information in settings."

The lat/lng is set to:  69.63937 / 18.97718. There is no sunset here.

**Comment by rwaaren** [comment]
> "Error: dzVents: Error: (3.0.2) No information about sunrise and sunset available. Please set lat/lng information in settings."
> The lat/lng is set to: 69.63937 / 18.97718. There is no sunset here.

Thx for reporting. 
Can you change lines 
```

	-- check if the user set a lat/lng
	-- if not, then daytime, nighttime is incorrect
	if (_G.timeofday['SunriseInMinutes'] == 0 and _G.timeofday['SunsetInMinutes'] == 0) then
		utils.log('No information about sunrise and sunset available. Please set lat/lng information in settings.', utils.LOG_ERROR)
	end
```

in \<domoticz dir\>/dzVents/runtime/Domoticz.lua

to

```
	-- check if the user set a lat/lng
	-- if not, then daytime, nighttime is incorrect
	if not(globalvariables.longitude and globalvariables.latitude) then
				utils.log('No information about longitude / latitude available. Please set lat/lng information in settings.', utils.LOG_ERROR)
	end
```

and check again ?

**Comment by rwaaren** [comment]
Fixed by https://github.com/domoticz/domoticz/commit/9b32e57199ace9670aebdadf7418e15ab3ecc93b ( build 12183 )
