### ISSUE TITLE
Icons upload doesn't work error undefined

### ISSUE THREAD

**Issue by kitopopo** [domoticz/domoticz#4245]
Hi dear friends,

I get an error loading the icon collection. undefined. I have reinstalled domoticz and without loading any database the problem persists, there is no way to upload icons always the same error. I have also given write permissions to the entire domoticz folder on a raspberry 4. I test it with several icons collection in zip format but none works.

in the domoticz forum people are experiencing problems again

https://www.domoticz.com/forum/viewtopic.php?f=28&t=30754&p=249186#p249186

I have also tried several icon packs and the problem persists. Is there a solution? I have the latest beta version of domoticz installed. Thanks in advanced

Version: 2020.2 (build 12184)
Build Hash: 17f0a1bca-modified
Compile Date: 2020-06-22 07:44:36
dzVents Version: 3.0.9
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

**Comment by kitopopo** [comment]
Dear friends,

In the domoticz version: 2020.2 (build 12230) the problem persist. Any solution?

**Comment by rwaaren** [comment]
Just checked with various icon packs  (see links below) on  build 12230 but cannot reproduce the issue., Icons are uploaded and used without problems

(uploaded from download folder in desktop as user with admin rights in domoticz (Chrome browser )

 [iconpack 1](https://drive.google.com/drive/folders/0B4fi5h8mtKF3UVpkcXBoVFNJUkU)
[iconpack 2](https://drive.google.com/drive/u/0/folders/0B-ZLFoCiqzMRSkFaaWdHV1Qxbm8)

**Comment by kitopopo** [comment]
Dear friend,

I have test all your icons but the same problem appears. Maybe is my database corrupt and I have the edit the database file? I use machinon theme, If a select custom icons appear only one icon with the name fake icon, i deleted this corrupt icon but now all is empty.

I don't know where is the problem, any idea? 

thanks in advanced

**Comment by rwaaren** [comment]
Are you also following this [forum post](https://www.domoticz.com/forum/viewtopic.php?f=6&t=30691#p253489) ?

**Comment by kitopopo** [comment]
> Are you also following this [forum post](https://www.domoticz.com/forum/viewtopic.php?f=6&t=30691#p253489) ?

Oh yeah, thanks @rwaaren , under raspbian graphic interface doesn't work, but it works from windows graphic interface. 
Thank you very much.

Best regards

**Comment by wkossen** [comment]
I have the same problem on raspberry pi. i tested to see if it was an access-control problem in the images folder, it wasn't. 
the 'undefined' error seems to come from line 44 of the CustomIconsController.js file. (at least, there is an undefined word in there). unfortunately, i'm not enough of a programmer to understand how we got there, and what happens (or doesn't happen) next. Hope someone can fix this. i'm running current stable on up-to-date pi (raspbian).
