### ISSUE TITLE
Domotics 2020.1 with buildroot on pandaboard with openzwave crashes

### ISSUE THREAD

**Issue by subramaniam** [domoticz/domoticz#4246]
Hi All,

I am new to domoticz and am trying to compile it from source on my pandaboard. To keep the setup lean I am using buildroot. The image boots up fine and I am able to launch the domoticz daemon and that works fine. However, the moment I add my Aeotec Gen 5 Z Wave Stick ZW 090 A, I see that domotiz segfaults.

# 1970-01-01 00:04:53.326  Status: OpenZWave: using config in: /opt/domoticz/Config/
munmap_chunk(): invalid pointer
1970-01-01 00:04:53.350  Error: Domoticz(pid:225, tid:242('ZWaveBase')) received fatal signal 6 (Aborted)
1970-01-01 00:04:53.350  Error: siginfo address=0xe1, address=0xb6719fe5
1970-01-01 00:04:53.380  Error: Failed to start gdb, will use backtrace() for printing stack frame

1970-01-01 00:04:53.391  Error: #0  /opt/domoticz/domoticz() [0x11b560]
1970-01-01 00:04:53.393  Error: #1  /opt/domoticz/domoticz() [0x11bf54]
1970-01-01 00:04:53.393  Error: #2  /lib/libc.so.6 :  + 0x26a00 [0xb671aa00]
1970-01-01 00:04:53.393  Error: #3  /lib/libc.so.6 :  + 0x17856 [0xb670b856]

Further I tested building domoticz from source on my linux workstation and that works fine. However, I would definitely want to have a SBC based solution and have a bunch of pandaboards lying around.

To debug further, I enabled remote gdb and let it run and took a backtrace once the issue happened.
Here is what I see in the backtrace.

Program received signal SIGILL, Illegal instruction.
0xb6ccf148 in _armv7_tick () from /home/kaushik/git/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libcrypto.so.1.1
(gdb) 
Continuing.
[New Thread 282.296]
[New Thread 282.285]
[New Thread 282.286]
[New Thread 282.287]
[New Thread 282.288]
[New Thread 282.289]
[New Thread 282.290]
[New Thread 282.291]
[New Thread 282.292]
[New Thread 282.293]
[New Thread 282.294]
[New Thread 282.295]
[New Thread 282.297]
[New Thread 282.298]
[New Thread 282.299]

Thread 2 "ZWaveBase" received signal SIGABRT, Aborted.
[Switching to Thread 282.296]
__libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
47      ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
(gdb) bt 
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
#1  0xb670dfe4 in __libc_signal_restore_set (set=0xb07fc928) at ../sysdeps/unix/sysv/linux/internal-signals.h:84
#2  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xb66ff2e2 in __GI_abort () at abort.c:79
#4  0xb67357c8 in __libc_message (action=action@entry=do_abort, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:181
#5  0xb673a78e in malloc_printerr (str=<optimized out>) at malloc.c:5339
#6  0xb673a9b2 in munmap_chunk (p=<optimized out>) at malloc.c:2830
#7  0xb6bf4204 in OpenZWave::Options::ParseOptionsXML(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /home/kaushik/git/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libopenzwave.so.1.6
#8  0xb6bf43a0 in OpenZWave::Options::Lock() () from /home/kaushik/git/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libopenzwave.so.1.6
#9  0x00284c88 in COpenZWave::OpenSerialConnector() ()
#10 0x00285160 in COpenZWave::GetInitialDevices() ()
#11 0x002f8d48 in ZWaveBase::Do_Work() ()
#12 0x003a4ec6 in std::execute_native_thread_routine (__p=0xb1800a68) at /tmp/dgboter/bbs/rhev-vm7--rhe6x86_64/buildbot/rhe6x86_64--arm-none-linux-gnueabihf/build/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#13 0xb6ab1bd6 in start_thread (arg=0xe217e9e9) at pthread_create.c:479
#14 0xb677ef4c in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /home/kaushik/git/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

====================================================
I will continue to post more as I dig deeper, but would appreciate feedback on how to move forward.

The openzwave commit used is 62444b0f979c337d2091d77d89cf63c2ae9775cf

DOMOTICZ_VERSION = 2020.1

**Comment by subramaniam** [comment]
After enabling debug builds for openzwave and tinyxml I see the following bt:

Thread 2 "ZWaveBase" received signal SIGABRT, Aborted.
__libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
47      ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
(gdb) bt
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
#1  0xb67b5fe4 in __libc_signal_restore_set (set=0xaeffb7b0) at ../sysdeps/unix/sysv/linux/internal-signals.h:84
#2  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xb67a72e2 in __GI_abort () at abort.c:79
#4  0xb67dd7c8 in __libc_message (action=action@entry=do_abort, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:181
#5  0xb67e278e in malloc_printerr (str=<optimized out>) at malloc.c:5339
#6  0xb67e3b40 in _int_free (av=<optimized out>, p=0xaeffc8e8, have_lock=<optimized out>) at malloc.c:4173
#7  0xb6ca7e4c in OpenZWave::Internal::Scene::ReadScenes() () from /home/kaushik/git/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libopenzwave.so.1.6
#8  0xb6c92d58 in OpenZWave::Manager::Manager() () from /home/kaushik/git/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libopenzwave.so.1.6
#9  0xb6c930f0 in OpenZWave::Manager::Create() () from /home/kaushik/git/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libopenzwave.so.1.6
#10 0x00284c8c in COpenZWave::OpenSerialConnector() () at /tmp/dgboter/bbs/rhev-vm7--rhe6x86_64/buildbot/rhe6x86_64--arm-none-linux-gnueabihf/build/build-arm-none-linux-gnueabihf/obj/gcc3/arm-none-linux-gnueabihf/libstdc++-v3/include/bits/exception.h:63
#11 0x00285160 in COpenZWave::GetInitialDevices() () at /tmp/dgboter/bbs/rhev-vm7--rhe6x86_64/buildbot/rhe6x86_64--arm-none-linux-gnueabihf/build/build-arm-none-linux-gnueabihf/obj/gcc3/arm-none-linux-gnueabihf/libstdc++-v3/include/bits/exception.h:63
#12 0x002f8d48 in ZWaveBase::Do_Work() () at /tmp/dgboter/bbs/rhev-vm7--rhe6x86_64/buildbot/rhe6x86_64--arm-none-linux-gnueabihf/build/build-arm-none-linux-gnueabihf/obj/gcc3/arm-none-linux-gnueabihf/libstdc++-v3/include/bits/exception.h:63
#13 0x003a4ec6 in std::execute_native_thread_routine (__p=0xb3c034c8) at /tmp/dgboter/bbs/rhev-vm7--rhe6x86_64/buildbot/rhe6x86_64--arm-none-linux-gnueabihf/build/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#14 0xb6b59bd6 in start_thread (arg=0xeb896e2a) at pthread_create.c:479
#15 0xb6826f4c in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /home/kaushik/git/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by subramaniam** [comment]
The above log doesnt make any sense to me :( Doesnt seem to be a consistent failure now that I rebuilt the libs.

**Comment by gizmocuz** [comment]
@subramaniam ,

Could you first try building with both the latest Domoticz code (That means the active development branch en not the master branch)
And the latest OpenZWave code (from the master branch)

Most of us are using a Single Board Computer (SBC), these days it's a Raspberry Pi/ODroid mostly

Try to install Buster and a kernel that is at least 4.16+, after this, try the 'binary' version of Domoticz,
install this with:

'curl -sSL install.domoticz.com | sudo bash'

And see how that goes

**Comment by subramaniam** [comment]
@gizmocuz , Thank you for your response. I will try to see if I can get that done on a pandaboard. I dont have a pi hand ATM.

**Comment by subramaniam** [comment]
@gizmocuz
I tried compiling with development domoticz and Dev openzwave. There were some patches required to have buildroot build with these branches. Tagging  @ffontaine  to get some feedback on this . I have the changes [here](https://github.com/subramaniam/buildroot/tree/panda-domoticz-dev-br). However, I still get the same error.

Some observations:
1. The external repos that domoticz pulls in is not used for the buildroot setup. The build specific versions are pulled instead.
2. Buildroot uses a cross compilation toolchain. I am not sure if openzwave along with domoticz has ever been used with a cross compilation setup. I will try with a different toolchain to see if that helps.

**Comment by ffontaine** [comment]
I added domoticz to buildroot 4 years ago. buildroot is used to cross-compile embedded systems which, most of the time, have memory constraints (i.e. not only Raspberry Pis). So, buildroot's philosophy is to use external libraries as much as possible instead of letting each package embeds its own bundle libraries that's why `-DUSE_BUILTIN_XXX=OFF` are used when possible. It should also be noted that having external libraries is also good for security purposes: when a CVE is found (e.g. 5 CVEs were published on mosquitto in 2018 and 6 CVEs in 2019), a single patch on the external library will fix the security issue for all the packages that use this library.

However, I have more and more difficulties to keep domoticz up to date. Indeed, I was working on bumping domoticz to 2020.02 but I give up:
- The patch that you suggested on minizip was, quickly, rejected a few weeks ago: https://github.com/domoticz/domoticz/pull/4238.
- The second difficulty is linked to openzwave: how can I know the openzwave commit hash to use for a given domoticz's version? It is interesting to note that openzwave is the only package that don't have a `-DUSE_BUILTIN_XXX` parameter.
- Finally, I don't have any more Z-Wave devices so I can't make any runtime tests anymore.

I don't think my answer will really help you but If you find a fix for your runtime issue or if you want to update domoticz's version in buildroot, feel free to send a patch to the mailing list.

**Comment by subramaniam** [comment]
@ffontaine , Thank you for the response. The -DUSE_BUILTIN_XXX concepts makes sense for buildroot. I wish we had used that in some of our previous projects. At this point it looks like the issue is wrt openzwave. I still am not sure if this is a buildroot issue or a cross compilation issue though. 

Just started using my zwave devices. I had tried Home assistant and quickly moved to openHAB2. However, want to put the panda boards and the beagles to some good use and thought domotoicz would be good choice. 

Do feel free to suggest things that you think might help. I will post updates if any to this issue.

**Comment by subramaniam** [comment]
@ffontaine  @gizmocuz  Oh BTW, I tried the comandline MinOZW and that seems to work fine. Not sure if thats useful.

**Comment by subramaniam** [comment]
Cc: @ffontaine 

Was not able to work on this for a while. Tried to do the same with a buildroot setup for x86 using qemu and I see the same issue with the latest master. This seems more to do with buildroot and cross compilation I feel. Do let me know if you want me to try out anything specific. Thanks

**Comment by Risca** [comment]
I experienced random segfaults with openzwave when built in Buildroot. My problems went away when I re-compiled tinyxml without the `TIXML_USE_STL` flag (or used the bundled tinyxml version in openzwave)

**Comment by gizmocuz** [comment]
Maybe it is time to switch to ZWaveJS2MQTT and use the new MQTT Auto Discovery hardware in Domoticz.
OpenZWave is not being developed any more

**Comment by gizmocuz** [comment]
Bdw, running perfectly for years and years on Raspberry Pi's, ODroid systems

**Comment by Risca** [comment]
My problem with tinyxml is most likely a toolchain/libc++ issue since it worked on my host toolchain but not on target. In the end, I got it working and am happy to repurpose this old BifferBoard =)

**Comment by gizmocuz** [comment]
Thats great... but you should probably still transfer to ZWaveJS2MQTT

**Comment by Risca** [comment]
I'll take a look, but for my purposes (5 nodes, domoticz acting as a slave) this is all I need.

I just wanted to help others who happen to stumble upon this issue.

**Comment by Risca** [comment]
No way ZWaveJS2MQTT will run on my BifferBoard! It's nodeJS and I have 486SX CPU with 32 MB RAM :grimacing: domoticz+openzwave works just fine =)

**Comment by gizmocuz** [comment]
I would invest in a Raspberry Pi or ODroid.... Also way faster (also the gui)
It starts with 5 nodes ;)
