### ISSUE TITLE
adding RFX sonoff doesn't work

### ISSUE THREAD

**Issue by firelook** [domoticz/domoticz#4247]
Version : Domoticz2020.2 (build 12185)
OS : Windows 10
hardware RFXCOM - RFXtrx433 USB 433.92MHz Transceiver  Version: Ext/1007 S

I can not add  anymore Somfy devices like electrical outlet on RFY

I did not do it since a long time, so I have no clues when it stop to be added
It is working well to on / off existant installation, or receiving information

please feel free to ask any questions if you need more informations

**Comment by gizmocuz** [comment]
Did you follow this guide to learn the transceiver to your Somfy blinds ?

https://www.domoticz.com/wiki/RFXtrx433E

**Comment by firelook** [comment]
sorry it is not blind but electrical outlet.
I have several which are working well, I just bought new ones (same as the others) (ref : Somfy 2401365 - Pack de 3 prises ON/OFF télécommandées type E | Télécommande 5 canaux RTS incluse | Compatible TAHOMA) 

aand they do not want to be included. I know it is working because I can attach them to the remote control

**Comment by gizmocuz** [comment]
Could you try to include 1 via the RFXMngr application ?

**Comment by firelook** [comment]
yes done, and same error, it is not RFY, so thanks it is not the application but I do not understand what happen !

good hint and sorry to have bother you !

**Comment by gizmocuz** [comment]
No worries, If you think this was working before, please contact Support of RFXCom
