### ISSUE TITLE
undefined scene appears on dashboard if no switches favourited

### ISSUE THREAD

**Issue by derekoharrow** [domoticz/domoticz#4248]
Domoticz Version: v2020.2 (build 12184) on Raspberry Pi

I have a number of scenes marked as Favourites, and these all appear on the Dashboard. I don't have anything else marked as favourites - no switches or anything.

On the Dashboard it shows a Scene called "undefined", which isn't in the database (I checked) and when you click on it the log file shows an error:

`2020-06-25 15:09:53.715 Error: User: derek, scene not found (idx=undefined)!`

If I then Favourite a Switch so it appears on the Dashboard, this Undefined scene disappears and all then works ok.

I assume that the fact no switches are Favourited is causing some issues in the Dashboard code.

NOTE: This is causing issues with the iOS app too as it crashes on the Dashboard tab.

**Comment by gizmocuz** [comment]
@derekoharrow , I am trying to simulate this:
- Using a empty database (I renamed my to domoticz.db.old)
- Using the default Domoticz theme
- Created a Dummy hardware
- Added two switches (create virtual Sensors button)
- Added two 'Scenes', in Scene 1 I added the two switches
- Made the Scene 'Favorite'
- It shows up on the dashboard and I can activate it

**Comment by derekoharrow** [comment]
So, I have 5 scenes on my dashboard, and the 6th that appears as undefined.
Do you have any other devices on the dashboard - the undefined scene only appears when I don't have anything else on the dashboard at all. As soon as I add a switch to the dashboard it disappears...

**Comment by gizmocuz** [comment]
@derekoharrow , I started with a clean database and followed the above steps, as you can see there are no other devices on the dashboard
Could you try to above steps ?

**Comment by waltervl** [comment]
No feedback
