### ISSUE TITLE
2020.2 Problem with openwebnet binding (f454)

### ISSUE THREAD

**Issue by umbz** [domoticz/domoticz#4252]
Hi everyone, I have a problem with the openwebnet interface and specifically with the lights command (at the moment)

I have a series of lights with position below 10 whose ignition control is, _for example_
` * 1 * 1 * 06 ##`

The automatic detection of the switch  works but  the widget sends a command  like this

` * 1 * 1 * 6 ##` (without leading zero)

which however is not interpreted by the F454.

The problem occurs with WHERE under 10.

I think it's a bug

Dz Version 2020.2

**Comment by umbz** [comment]
More details: 
this is a commands guide
Where (normal)

[0-9] -> Area: Area = 8 *who*what*8##
[0-9][0-9] -> Area light Point : Area = 8 Light= 6  *who*what*86##
[#0-#9] -> Group: Group = 2 *who*what*#2##
0 -> General
Where (extended) -> through virtual configuration

[0-10] -> Area: Area = 8 *who*what*8##
[0-10][1-15] -> Area light Point : Area = 8 Light= 12  *who*what*86##
[#0-#9] -> Group: Group = 2 *who*what*#2##
0 -> General

If is  triggered this command '* 1 * 1 * 6 ##'  the scs bus search an entire "6" area and then lights on the the devices attached to this area.  
In my case area 6 doesnt exist because my switch is in area "0" that seems to be trimmered ...

**Comment by Spugna85** [comment]
Hello,

the specification reports this:

```
Area A [00, 1 − 9, 100]:
• <A>! Area of private riser
• <A>#4#<Int>! Area of local bus

Point to point A; PL:
• A = 00; PL [01 − 15]
• A [1 − 9]; PL [1 − 9]
• A = 10; PL [01 − 15];
• A [01 − 09]; PL [10 − 15]
• <A><PL>! Point to point of private riser
• <A><PL>#4#<Int>! Point to point of local bus
```

as you can see, 06 is not acceptable and therefore not managed.
In the conversion the driver makes the 0 disappear and thus manages the area 6.
The correct message should be:
* 1 * 1 * 0006 ##

it looks like you have devices with no area.
The driver was made following the specification mentioned, I don't think I can manage this case easily.
If you have few devices and you can do it, I recommend configuring them in another area, which is not 0.

**Comment by Spugna85** [comment]
Apart from the clarifications above, after checking the code, I can confirm that area 0 does not work. Currently if WHERE is less than 10, it is acquired as an area command or:

```
0 = GENERAL
1-9 and 01-09 = Area command
```

The problem is that at the moment there is no recognition of the correct WHERE based on the number of characters that make it up.
As you can see from the specification, area = 00 and 10 are two special variants that have the WHERE field 4 characters long.
This should be recognized:

```
0 = General command
1-9 and 01-09 = Area command
00XX = Area commands, 00 and PL = XX
10XX = Area commands, 10 and PL = XX
```

To manage this, the change is not easy because the combination of WHO and WHERE generates the ID of the device, which is used for the reverse translation, that is when the command is sent by Domoticz.

**Comment by umbz** [comment]
My specifications are from official bticino forum.. I don't know if they are written from a bticino technician or not (i remember yes) . But i have  area 0 and with openhab works perfectly.
So i have 
1*1*06##
1*1*05##
And so on.

This commands works similar to other areas commands like  1*1*15*

Where i can find official documentation if exists? 

I don't know if it's easy changing the area on the devices, so I try..

**Comment by umbz** [comment]
i reviewed the actuator config on my_home_suite. and in fact area 0 exists (ambiente) 
![immagine](https://user-images.githubusercontent.com/10219236/86513707-9b250100-be0c-11ea-86d0-06d91cb6ae47.png)

**Comment by Spugna85** [comment]
Here the docs : [https://developer.legrand.com/documentation/open-web-net-for-myhome/](url)

As I wrote above, area 0 exists, but it currently conflicts with the management of general and area devices.

**Comment by umbz** [comment]
Spugna is true, i have to change the area but  i if you know i have to change both actuators and light control config  ?

**Comment by Spugna85** [comment]
Yes, you must change both the actuator and the command module. 
I saw that you have 'MyHome Suite', do you have the project of your home?
If it has been configured via software, you can fix everything in a few minutes, 
if instead there are physical configurators it will take some time ...
If you need help contact me via pm on the Domoticz forum.

**Comment by alessandro-lac** [comment]
Hi, 
I believe I have the same problem.
 
I have a dimmer which sends the command: 
`*1*8*0010##`

when I do change it from Domoticz, it sends the command: 
`*1*8*10##`

Can you help me fix this?

**Comment by Spugna85** [comment]
Hi Alessandro, 
as written above, domoticz cannot manage area 0 at this time. The quickest solution is to change the area of ​​your system. Are you able to do it?

**Comment by alessandro-lac** [comment]
Is it something that I can do with the installer code and the regular MyHomeUp app? Or do I need other software?

**Comment by Spugna85** [comment]
I don't have MyHomeUp, I guess you're using it with Server1. MyHomeUp should allow you to set area and point, even if it usually sets one by default to facilitate the user.

I use F454 or MH202 with MyHome Suite, which is a software downloadable from the site. This allows you to configure actuators and controls and to see all the configuration present.

However, if the system has been configured through MyHomeUp, if you modify it with the suite, you can create a misalignment.

My advice is to change the settings with MyHomeUp by logging in as a configurator, however I don't have it so I can't guide you with these changes.

**Comment by Spugna85** [comment]
I'm trying to solve the problem of area 0 with this: [#4279 ](https://github.com/domoticz/domoticz/pull/4279).
Can anyone test as soon as it gets approved?

**Comment by umbz** [comment]
i compiled now from sources and lights management on area 0 seems working.

good job.  

I will control if we have some other problems
