### ISSUE TITLE
Netatmo problem

### ISSUE THREAD

**Issue by Hydci** [domoticz/domoticz#4253]
Hello,
I am in version domoticz 2020.2 for some time I noticed that the netatmo device creates after a reboot of the new devices the old ones if we delete them the new ones which had been created take back the place of the old ones and the new ones are created again I post an image to better explain

https://imgur.com/a/4piZnlc

**Comment by gizmocuz** [comment]
It seems that the devices get a new ID ?
This also happens with a lot of 433Mhz hardware
You can press 'edit' on a previous senor and select 'transfer device' to transfer it to the new device

**Comment by Hydci** [comment]
Hello @gizmocuz 
Indeed the devices receive a new id
Thank you for the transfer tip.
do we leave the problem open or not as it is a known problem?

**Comment by gizmocuz** [comment]
I think we can close the issue
