### ISSUE TITLE
Domoticz loses Z-Wave hardware information about Manufacturer and Description

### ISSUE THREAD

**Issue by Hoiss** [domoticz/domoticz#4255]
Hi,
I already asked in the forum [https://www.domoticz.com/forum/viewtopic.php?f=6&t=33166](https://www.domoticz.com/forum/viewtopic.php?f=6&t=33166) ,  but it seems I might need real technical experts to get the root of this issue.
My problem is that everytime I setup my system and include all devices, at some point in this process domoticz loses all the hardware information of the z-wave devices. It happened already 3 times now and it seems to be related to the combination of excluding and including devices, which is sometimes necessary in my case if a device was a bit too far away from the main unit during the include process.

If I then click on Setup->Hardware->razberry2_setup I see all the devices with correct ID and Type info, but the Manufacturer and Description info is like 
Description:  Unknown: id=0260 Unknown: type=8002, id=1000+
Manufacturer:  Unknown: id=0260

Also excluding and including one of the devices work, but it tells me in the case of include that it's an unknown device!
So it seems to me like the manufacturer_specific.xml is not parsed any more or something like that!?

Did someone ever run into similar issue? Or does someone have an idea what could be wrong now or what I could try to fix that?

**Comment by gizmocuz** [comment]
It seems you are not using the latest beta version, first upgrade to this version.
I do not know if it is a powered node, but when you remove one of them, there could become a problem with your "Mesh Network"
There is a good book about ZWave on Amazon

**Comment by Hoiss** [comment]
Hi gizmocuz,
thanks a lot for replying to this issue!
The one after the issue appeared this time was a battery powered smoke sensor. It didn't show all subdevices and therefore I excluded it and included it again... obviously something went wrong then and all devices showed the non parsed Description and Manufacturer info.
Is there any chance for me to debug this? If I knew where the starting point is for parsing the Description and Manufacturer info, I maybe could try to have a look at this issue.

Is it easy to switch to the beta and back to the stable without doing the whole include process again? I am always a bit conservative leaving stable versions, I ran too often into other issues then. That's why I was so happy reading about the new stable version 02.2020 and decided to update my system.

**Comment by gizmocuz** [comment]
@Hoiss , there have been quite some improvements in the latest beta related to ZWave.
It's safe to upgrade now

**Comment by hvbommel** [comment]
after update

![zwave-config-lost](https://user-images.githubusercontent.com/14799318/86571594-f3c1de80-bf71-11ea-8ac0-3a34c739a91b.JPG)

**Comment by hvbommel** [comment]
@Hoiss 
If my pictures shown above do no not match exactly the problem you have please say so, so that we do not mix two different problems into one thread. I may need to make it a seperate one if you problem is different.

**Comment by hvbommel** [comment]
@Hoiss 
I have removed my entries, about "OpenZWave not fully initialized yet!" because after reading your initial question one more time mine is a different issue. It may even not be a bug but just an unreachable device or so. I will wait and see if I get the error back. If so I may raise a new issue. Sorry for the intervention.

**Comment by Hoiss** [comment]
OK, it seems I'd need to try out the beta to check if this issue is still there.
But at the moment I really am afraid that I need to setup the system again after upgrading domoticz to the beta.
I've done this already 3 times since updating to 2020.02 and I have no power to repeat this process again. I have several devices inside wall connectors and it's a lot of work.
So I decided to stay on the current release and to live with this issue, because it seems to be just a display issue maybe connected to a parse problem of the manufacturer files. The devices itself work as they should (ok one aeotec motion sensor never tells me motion but temperature and humidity works - but I don't know if this would be solved in the beta).
Maybe the next release solves my issues, we'll see.
Thanks for your input anyway!
