### ISSUE TITLE
OpenZwave, Popp & Co Z-Rain reporting error in logfile, OpenZWave.cpp:3266

### ISSUE THREAD

**Issue by hvbommel** [domoticz/domoticz#4256]
I am getting this OpenZWave error reported in the logfile for "Popp Z-Rain Rain Sensor+" every time the device updates its values:

2020-07-05 12:44:27.105 Error: OpenZWave: Value_Changed: Unhandled value type ZDTYPE_SWITCH_NORMAL (2). Node: 3 (0x03), CommandClass: SENSOR MULTILEVEL, Label: General Purpose, Instance: 1, Index: 2 (OpenZWave.cpp:3266)

I am running Domoticz 2020.2 Build 12194.

Note: This is the code that is reporting the error at line 3266 in OpenZWave.cpp.
_log.Log(LOG_ERROR, "OpenZWave: Value_Changed: Unhandled value type ZDTYPE_SWITCH_NORMAL (%d). Node: %d (0x%02x), CommandClass: %s, Label: %s, Instance: %d, Index: %d (%s:%d)", vType, NodeID, NodeID, cclassStr(commandclass), vLabel.c_str(), vID.GetInstance(), vID.GetIndex(), std::string(__MYFUNCTION__).substr(std::string(__MYFUNCTION__).find_last_of("/\\") + 1).c_str(), __LINE__);

**Comment by gizmocuz** [comment]
@hvbommel , I would not expect a 'Switch/General Purpose' for a rain sensor... Is the rain being detected as a device and working normally ?

**Comment by hvbommel** [comment]
@gizmocuz, It is one of the switches that indicate: Rain has started/stopped. The "Rain" and "RainRate" values work fine.

**Comment by gizmocuz** [comment]
@hvbommel , (2) in the log means that the value type is 'decimal', which is strange as i would expect a boolean value (or integer), but not decimal
If you go to the openzwave hardware setup, and from the node dropdown choose 'Control Panel', select this node, and look at the values, do you see this switch here? What is it's value ?
Could you post a screenshot of the values ?

**Comment by hvbommel** [comment]
![5727DD39-8214-47AF-8409-6B3F531AF694](https://user-images.githubusercontent.com/14799318/86532746-8740d400-becc-11ea-96c6-cad59042f35d.jpeg)

**Comment by hvbommel** [comment]
![08ABE758-6A56-4D32-88A0-87F87E18C4BE](https://user-images.githubusercontent.com/14799318/86533156-54e4a600-becf-11ea-998d-eb6fe4f69cef.jpeg)

The switch is called “general purpose”

**Comment by gizmocuz** [comment]
Could it be you have another switch that is updating when it starts to rain ?
The General Purpose (18.0) could that be the temperature ? No idea what it is.
Does the value change or is it always 18 ?
If it is, I would ignore the error for now

**Comment by hvbommel** [comment]
There is only the controller and the rain device. This device does not report temperature. It only reports mm water, rain rate, rain start/stop and havy rain start/stop. When I am at home in a fee hours I will check if I can relate the 18.0 value with someting else.

**Comment by hvbommel** [comment]
After I manually put water in the device, here are its updated readings. It looks like "General Purose" and "Water" are showing the same data. Note both "Sensor" and "Exporting" both show "Off". Maybe  that are the switches. I will also add the devices view here. I only received the rain sensor last Friday so I dont have a lot experience with it. But the rain readings look ok. Also I checked the zwave xml file for this device. Values look ok according to the specs I got. I did change 2 "shorts" to "bytes" but that did not help (I was expecting that result of course because the water readings look ok).

![ozw-rain](https://user-images.githubusercontent.com/14799318/86536759-58d1f180-beea-11ea-8f2f-4fed22dbdca9.JPG)

![devices](https://user-images.githubusercontent.com/14799318/86536868-5e7c0700-beeb-11ea-998f-0a2e27100ac1.JPG)

**Comment by hvbommel** [comment]
More Data of the units of the rain device below:

idx:1071 (/json.htm?type=devices&rid=1071)
{
	"ActTime" : 1593966396,
	"AstrTwilightEnd" : "00:00",
	"AstrTwilightStart" : "00:00",
	"CivTwilightEnd" : "22:41",
	"CivTwilightStart" : "04:42",
	"DayLength" : "16:26",
	"NautTwilightEnd" : "23:51",
	"NautTwilightStart" : "03:33",
	"ServerTime" : "2020-07-05 18:26:36",
	"SunAtSouth" : "13:42",
	"Sunrise" : "05:29",
	"Sunset" : "21:55",
	"app_version" : "2020.2 (build 12194)",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 78,
			"CustomImage" : 0,
			"Data" : "Off",
			"Description" : "",
			"DimmerType" : "none",
			"Favorite" : 0,
			"HardwareID" : 24,
			"HardwareName" : "Openzwave",
			"HardwareType" : "OpenZWave USB",
			"HardwareTypeVal" : 21,
			"HaveDimmer" : true,
			"HaveGroupCmd" : true,
			"HaveTimeout" : false,
			"ID" : "00000300",
			"Image" : "Light",
			"IsSubDevice" : false,
			"LastUpdate" : "2020-07-05 11:06:05",
			"Level" : 0,
			"LevelInt" : 0,
			"MaxDimLevel" : 100,
			"Name" : "Z-Rain Sensor",
			"Notifications" : "false",
			"PlanID" : "0",
			"PlanIDs" : 
			[
				0
			],
			"Protected" : false,
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"Status" : "Off",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "Switch",
			"SwitchType" : "On/Off",
			"SwitchTypeVal" : 0,
			"Timers" : "false",
			"Type" : "Light/Switch",
			"TypeImg" : "lightbulb",
			"Unit" : 1,
			"Used" : 0,
			"UsedByCamera" : false,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "1071"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}

idx:1072 (/json.htm?type=devices&rid=1072)
{
	"ActTime" : 1593966449,
	"AstrTwilightEnd" : "00:00",
	"AstrTwilightStart" : "00:00",
	"CivTwilightEnd" : "22:41",
	"CivTwilightStart" : "04:42",
	"DayLength" : "16:26",
	"NautTwilightEnd" : "23:51",
	"NautTwilightStart" : "03:33",
	"ServerTime" : "2020-07-05 18:27:29",
	"SunAtSouth" : "13:42",
	"Sunrise" : "05:29",
	"Sunset" : "21:55",
	"app_version" : "2020.2 (build 12194)",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 78,
			"CustomImage" : 0,
			"Data" : "Off",
			"Description" : "",
			"DimmerType" : "none",
			"Favorite" : 0,
			"HardwareID" : 24,
			"HardwareName" : "Openzwave",
			"HardwareType" : "OpenZWave USB",
			"HardwareTypeVal" : 21,
			"HaveDimmer" : true,
			"HaveGroupCmd" : true,
			"HaveTimeout" : false,
			"ID" : "00000302",
			"Image" : "Light",
			"IsSubDevice" : false,
			"LastUpdate" : "2020-07-05 11:06:05",
			"Level" : 0,
			"LevelInt" : 0,
			"MaxDimLevel" : 100,
			"Name" : "Z-Rain General Purpose",
			"Notifications" : "false",
			"PlanID" : "0",
			"PlanIDs" : 
			[
				0
			],
			"Protected" : false,
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"Status" : "Off",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "Switch",
			"SwitchType" : "On/Off",
			"SwitchTypeVal" : 0,
			"Timers" : "false",
			"Type" : "Light/Switch",
			"TypeImg" : "lightbulb",
			"Unit" : 1,
			"Used" : 0,
			"UsedByCamera" : false,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "1072"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}

idx:1073 (/json.htm?type=devices&rid=1073)
{
	"ActTime" : 1593966488,
	"AstrTwilightEnd" : "00:00",
	"AstrTwilightStart" : "00:00",
	"CivTwilightEnd" : "22:41",
	"CivTwilightStart" : "04:42",
	"DayLength" : "16:26",
	"NautTwilightEnd" : "23:51",
	"NautTwilightStart" : "03:33",
	"ServerTime" : "2020-07-05 18:28:08",
	"SunAtSouth" : "13:42",
	"Sunrise" : "05:29",
	"Sunset" : "21:55",
	"app_version" : "2020.2 (build 12194)",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 0,
			"Data" : "0 mm/h",
			"Description" : "",
			"Favorite" : 0,
			"HardwareID" : 24,
			"HardwareName" : "Openzwave",
			"HardwareType" : "OpenZWave USB",
			"HardwareTypeVal" : 21,
			"HaveTimeout" : false,
			"ID" : "0000030C",
			"Image" : "Custom",
			"LastUpdate" : "2020-07-05 18:07:09",
			"Name" : "Z-Rain Rain Rate",
			"Notifications" : "false",
			"PlanID" : "0",
			"PlanIDs" : 
			[
				0
			],
			"Protected" : false,
			"SensorType" : 1,
			"SensorUnit" : "mm/h",
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"SubType" : "Custom Sensor",
			"Timers" : "false",
			"Type" : "General",
			"TypeImg" : "Custom",
			"Unit" : 1,
			"Used" : 1,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "1073"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}

idx:1074 (/json.htm?type=devices&rid=1074)
{
	"ActTime" : 1593966524,
	"AstrTwilightEnd" : "00:00",
	"AstrTwilightStart" : "00:00",
	"CivTwilightEnd" : "22:41",
	"CivTwilightStart" : "04:42",
	"DayLength" : "16:26",
	"NautTwilightEnd" : "23:51",
	"NautTwilightStart" : "03:33",
	"ServerTime" : "2020-07-05 18:28:44",
	"SunAtSouth" : "13:42",
	"Sunrise" : "05:29",
	"Sunset" : "21:55",
	"app_version" : "2020.2 (build 12194)",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 0,
			"Data" : "0;42.0",
			"Description" : "",
			"Favorite" : 0,
			"HardwareID" : 24,
			"HardwareName" : "Openzwave",
			"HardwareType" : "OpenZWave USB",
			"HardwareTypeVal" : 21,
			"HaveTimeout" : false,
			"ID" : "0301",
			"LastUpdate" : "2020-07-05 18:07:09",
			"Name" : "Z-Rain Water",
			"Notifications" : "false",
			"PlanID" : "0",
			"PlanIDs" : 
			[
				0
			],
			"Protected" : false,
			"Rain" : "38.0",
			"RainRate" : "0",
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"SubType" : "TFA",
			"Timers" : "false",
			"Type" : "Rain",
			"TypeImg" : "rain",
			"Unit" : 0,
			"Used" : 1,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "1074"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}

@gizmocuz, If need more data please let me know.

Here is the link to config info of the the Z-Rain device: 
https://products.z-wavealliance.org/products/2418/configs

**Comment by hvbommel** [comment]
REF #4255
Also, while experimenting, I also noticed the problem reported in #4255. I was excluding and including the device followed by a domoticz restart. My config was lost and I only could restore it by exluding the Z-Rain followed by a include. After that all was functioning ok. This is a problem as you need to get to the device physically todo the exclude/include. Now that I have it on my desk, for testing,  it is easy to do of course.

Note: This problem (#4255) is not 100% reproducable in my case but I have seen it 3 times in this weekend. I solved it the first time by a by ZWave-stick reset and after that the includes. The other times I only excluded/included devices to restore operation.

**Comment by gizmocuz** [comment]
@hvbommel , thanks for all the tests. You should first update to the latest beta version to see if problem 4255 still exists
It indeed looks like 'general' is the same as the water value (* 1000)

I think the problem here is in OpenZWave.cpp, line 2022:

```
		else if (vOrgIndex == ValueID_Index_SensorMultiLevel::General_Purpose)
		{
			_device.devType = ZDTYPE_SWITCH_NORMAL;
		}
```

I think we need to change this to

```
		else if (vOrgIndex == ValueID_Index_SensorMultiLevel::General_Purpose)
		{
			if (vType == OpenZWave::ValueID::ValueType_Decimal)
			{
				_device.custom_label = "?";
				_device.devType = ZDTYPE_SENSOR_CUSTOM;
			}
			else
				_device.devType = ZDTYPE_SWITCH_NORMAL;
		}
```

Please check beta 12200 to see if this solves the issue

**Comment by hvbommel** [comment]
@gizmocuz, I will update to the latest beta now and will let you know the results asap. I need to build a new docker-image, that takes about 45 minutes.

**Comment by hvbommel** [comment]
Thanks a lot for the very fast solution, this is fixed now. No More errors in the log, only good status.

![general sensor](https://user-images.githubusercontent.com/14799318/86573022-0dfcbc00-bf74-11ea-9202-9bd78ba127c7.JPG)

2020-07-06 10:27:58.213 (Openzwave) General/Custom Sensor (Z-Rain Rain Rate)
2020-07-06 10:27:58.231 (Openzwave) General/Custom Sensor (Z-Rain General Purpose)

(minor) Question: Is the "?" needed or is it better to remove ? ie so that we would display "3.5" instead of "3.5 ?"

**Comment by gizmocuz** [comment]
@hvbommel , you can press 'Edit' on the sensor and change the Unit
Great it's solved now !

**Comment by hvbommel** [comment]
ah ha, YES, the edit did the final (minor) trick. Thanks again !
![Z-rain](https://user-images.githubusercontent.com/14799318/86577780-0bea2b80-bf7b-11ea-94df-dec1652e41bd.JPG)
