### ISSUE TITLE
Can you do blockly math as standard please?

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#4260]
Hello, can you do math in Blockly as a standard please?
I tried the Stas file and it works fine.
This will only be overwritten after Domoticz has been updated.
Can you please use this as the default in your brunch, that would be great!

https://github.com/domoticz/domoticz/pull/2857/commits/007839c5bc67d256ed3103a010d8604d38f3a905

thank you

**Comment by rwaaren** [comment]
This has been asked before and rejected.

Also what have you tried? The underlying code is not in domoticz so kind of surprising if you can actually do something with it, other then playing with blocks.

Adding mathblocks  in Blockly does nothing without underlying code in the rest of domoticz.  
Check  [issue 1957](https://github.com/domoticz/domoticz/issues/1957)
