### ISSUE TITLE
Sound device incorrectly displayed in Floorplan

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#4261]
If you want to display a "Sound level" device on a Floorplan, it is not presented with the "Loudspeaker"symbol, but as a switch with the "Lamp" symbol.

See forum: https://www.domoticz.com/forum/viewtopic.php?f=6&t=33336&p=252087#p252087

**Comment by gizmocuz** [comment]
Thanks for reporting, fixed in  beta 12215. (You might need to clear the appcache/browser cache)
