### ISSUE TITLE
Domoticz does not start after update to 12223

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#4265]
After update to the Linux version 12223, domoticz will not start, due to missing library files.
For the details see Forum: https://www.domoticz.com/forum/posting.php?mode=reply&f=6&t=33360

**Comment by FireWizard52** [comment]
Sorry already reported

**Comment by gizmocuz** [comment]
Already reported here

https://github.com/domoticz/domoticz/issues/4264
