### ISSUE TITLE
OpenZWave, device becomes unusable

### ISSUE THREAD

**Issue by hvbommel** [domoticz/domoticz#4267]
Only sometimes, about one out of 10 times, when I reboot or restart Domoticz I get "Not all Nodes have been Queried yet, OpenZWave not fully initialized yet!". The device ID and Type become 0x0000, manufacturer is not listed anymore. I am running 2020.2 Build 12227 but have seen it also on older builds for about 2 weeks now. Before that time I was not using OpenZwave actively so I cant tell when the problem started.

The only way to make my device (Popp Z-Rain) working again I have found so far is: 
1. climb and get my device of the roof. 
2. exclude it 
3. include it. 

I have attached some of my screenshots.
![OpenZwave-problem](https://user-images.githubusercontent.com/14799318/87626346-6f6b1a80-c72c-11ea-9766-e60eb7688450.JPG)
![OpenZwave-problem-part2](https://user-images.githubusercontent.com/14799318/87626348-7003b100-c72c-11ea-84d5-f9ad2b68ce72.JPG)
![OpenZwave-problem-part3](https://user-images.githubusercontent.com/14799318/87626448-9fb2b900-c72c-11ea-8ff2-97097c8e988b.JPG)

**Comment by gizmocuz** [comment]
It looks it is waiting waiting for a value from the rain sensor, and since it is a battery device it is having a issue with it.
It could also be a problem with the node. I have the same node:

![image](https://user-images.githubusercontent.com/2265299/87633190-34bcae80-c73b-11ea-9d6d-fda2091e8ad3.png)

I gave up and bought a 433Mhz rain gauge

You could try to enable the debug log on the controller (select node 1, and enable the debug option).
(Do not keep this enabled to long as the log can become quite big)

Inside the Config folder you will find the log (OZW_Log.txt)

You do not have to reboot, but it will probably also happen when you disable and enable the hardware

**Comment by hvbommel** [comment]
Thanks for getting back. I will try to debug it. I am trying my luck;  Do you know if there is any config file that I could restore form backup to make the device work again? Att I still have the error in place. I did not clear the error so that I can do some troubleshooting.

**Comment by hvbommel** [comment]
I enabled debug but that didn't help. I now have done my exclude followed by include and now works again. I would think it not the Z-Rain itself because during restart time it is sleeping as it is a battery powered device. It looks like Domoticz/OpenZwave gets confused for some reason. Also saw the same problem with my BNext500 tag reader. The only thing I never replaced was my AEON Labs controller. I have 3 of those so I will replace it just to rule out that one too. Because the problem is very intermittent it may take a while before I have results.
Picture after Exclude/Include of ZRain
![OpenZwave-good](https://user-images.githubusercontent.com/14799318/87661648-3f8a3a00-c761-11ea-9bc7-23d646373681.JPG)

**Comment by gizmocuz** [comment]
By enabling the debug option, and restarting the hardware by disable/enable, try to get to a state where it says 0x0000 0x0000 again
Then wait 5 minutes
Next make a copy of the log file, and examine this file for any suspicious activity

**Comment by hvbommel** [comment]
I have put another controller in. Also, after I read your note ,I have disabled/enabled OpenZwave USB hardware 10x. It keeps working as advertised. So I can't reproduce this.
Question: Do you want me to close this issue? or leave it open for a few days and see if any others can add valuable info that could us help troubleshoot?

**Comment by gizmocuz** [comment]
You can leave it open... Maybe it has solved itself

**Comment by hvbommel** [comment]
I was debugging a bit more. I have extracted all the OpenZWave traces in my logfile. I can see things go wrong. See attached. These messages caught my eye: "User Alert - Manufacturer_specific.xml out of Date". I noticed I have different versions of same on my system; manufacturer_specific.xml, manufacturer_specific.xml.1 and manufacturer_specific.xml.2. I have added these files here also for analysis. For some reason the xml file gets corrupted on domoticz shutdown or startup. looks like someting goes wrong when manufacturer_specific.xml gets updated from https://github.com/OpenZWave/open-zwave.

[ZWave-logging.txt](https://github.com/domoticz/domoticz/files/4937418/ZWave-logging.txt)

[manufacturer_specific_xml_2.txt](https://github.com/domoticz/domoticz/files/4937521/manufacturer_specific_xml_2.txt)
[manufacturer_specific_xml_1.txt](https://github.com/domoticz/domoticz/files/4937522/manufacturer_specific_xml_1.txt)
[manufacturer_specific_xml.txt](https://github.com/domoticz/domoticz/files/4937523/manufacturer_specific_xml.txt)

**Comment by gizmocuz** [comment]
@hvbommel , the file "manufacturer_specific_xml.txt" looks like a valid XML, I have also tested this online with a verification tool.
It is not corrupt.
Sure it can happen that there are updates, these could occur everyday, but I don't think this is related to the ZRain configuration file

You are logging with the wrong system. The log is from Domoticz, but you need to enable the OpenZWave debug log.
You can do so by selecting the controller (node 1) and enable the 'debug' option (and press apply settings)
Now you have a new file in the Config folder, see a few posts up

**Comment by hvbommel** [comment]
That file /domoticz/Config/OZW_log.txt does not contain interesting data att. When problems occured debugging was not turn on for OZW so that is likely why. I will keep OZW debug ON so for next time when I see the problem I may have more info in it. (yes, I will monitor the size). 

Can you explain the "out of dates" in the domoticz logfile? or are these just normal & no problem.

**Comment by gizmocuz** [comment]
Thanks, yes, the debug log is the most important in this case.
Feature versions might automagically update the openzwave configuration files

**Comment by hvbommel** [comment]
Now that I turned on OZW debugging I noticed lots of create errors. After creating the domoticz/Config/images/act all these errors are gone and the logfile is clean (only normal good messages)

ages) . Could that be releated to the problem you think ? see attached. I have updated my dockerfile also so that this folder is now created next time when I build a new image.

before
[OZW_log.txt](https://github.com/domoticz/domoticz/files/4937736/OZW_log.txt)

after creating Config/images/act
[OZW_log_clean.txt](https://github.com/domoticz/domoticz/files/4937754/OZW_log_clean.txt)

**Comment by hvbommel** [comment]
I did see the error again and I also now see 
"2020-07-17 15:05:51.100 Detail, Notification: User Alert - Manufacturer_specific.xml out of Date" in the OZW_log.txt
This may be ok. I build a new docker image so the xml will initally be the version currently in git. Now an update of manufacture_specific.xml from 108 to 109 was done. 

![zwave-config-lost-2](https://user-images.githubusercontent.com/14799318/87790054-3f14a080-c840-11ea-8687-e5aa81ea5466.JPG)

Now I have the OZW logfile:
[OZW_log_error_repro.txt](https://github.com/domoticz/domoticz/files/4937974/OZW_log_error_repro.txt)

**Comment by gizmocuz** [comment]
Maybe we should disable the automagically updating process of openzwave as Domoticz does not ship the images as it is not currently used

 Node002, Skipping Cache Save for Node 2 as its not past QueryStage_CacheLoad

**Comment by hvbommel** [comment]
Indeed, that is what I was thinking also, Is that a code change? Or is that a setting somewhere?

PS:  With what I know now I should be able to reproduce at will by have the 108 version of the xml. That will cause the update and expose the probem likely. I have not tried that yet but can do.

**Comment by gizmocuz** [comment]
It's happening since some recent versions (openzwave)
No idea how to turn this behavior off, I asked this question on their google forum

**Comment by hvbommel** [comment]
As possible a workaround I have edited manufacturer_specific.xml and changed Revision="108" to Revision="999". Now it does not update anymore. Hopefully that stops the problems.

Update: The above workaround trial did not fix the problem. The same error returned.

**Comment by hvbommel** [comment]
So I did another experiment:
1. I created a working situation with the controller and Z-Rain installed, all working
2. I renamed the ozwcache_0xef8d06fd.xml to _ozwcache_0xef8d06fd.xml (i.e. delete the ozw cache)
3. Restart domoticz
4. A new cache ozwcache was created
5. Now I had the original problem (see 1st screenshot posted in here)
6. Removed the new created cache
7. Renamed the original cache back to ozwcache_0xef8d06fd.xml
8. Restarted Domoticz
9. Now it all works again.

Theory: The cache gets corrupted, or becomes incompatible after update, causing the problem.

Debugging note:
To find moments in time of possible corruption do the below. Then using these times go look in theOZW_log.txt
$ cat domoticz.log | grep "Manufacturer_specific.xml out of Date"
2020-07-11 06:58:39.858  Status: OpenZWave: User Alert - Manufacturer_specific.xml out of Date
2020-07-15 19:24:44.767  Status: OpenZWave: User Alert - Manufacturer_specific.xml out of Date
2020-07-15 21:02:16.854  Status: OpenZWave: User Alert - Manufacturer_specific.xml out of Date
2020-07-16 00:33:35.224  Status: OpenZWave: User Alert - Manufacturer_specific.xml out of Date
2020-07-16 11:45:03.054  Status: OpenZWave: User Alert - Manufacturer_specific.xml out of Date
2020-07-17 15:05:51.100  Status: OpenZWave: User Alert - Manufacturer_specific.xml out of Date
2020-07-17 17:15:45.740  Status: OpenZWave: User Alert - Manufacturer_specific.xml out of Date
2020-07-17 17:22:02.043  Status: OpenZWave: User Alert - Manufacturer_specific.xml out of Date
2020-07-17 22:13:25.697  Status: OpenZWave: User Alert - Manufacturer_specific.xml out of Date

**Comment by gizmocuz** [comment]
Question, as I'm unsure, is there a small button on the rain sensor to make it awake and to send it's node information frame?
(Same button the exclude/include it)
I can understand that when you delete the cache file, it needs to build this again
It needs to have the node information frame to complete it's query state
That does not say it is corrupt

**Comment by hvbommel** [comment]
The device has ONE button, called the Z-Wave button. It is used for everything; Inclusion, exclusion, wakeup, reset firmware upgrade. The documentation says: "To wakeup the device pleasae perform the following action: Push the Z-Wave button once". I must say I have not done the wakeup when I had the error situation. It is a good idea. I will try that and get back here with results.

**Comment by hvbommel** [comment]
So I did the test:
1. remove the ozw cache
2. restart domoticz
3. press the wakeup button once (short press)
4. wait a minute
5. refresh the screen
6. and YES the Z-Rain device is back, everything ok.

After this test I did the following test:
1. change the Z-Rain wake time value to 300 seconds on the domoticz hardware screen
2. press the Z-Rain wakeup button once so that it gets the new settings
3. delete the ozw cache again
4. wait 5 minutes for the Z-Rain device to wakeup
5. and YES this worked also, now without touching the device.

The above is of course a simulated problem situation. Time will learn if the above procedure also works for the real error case.

Conclusion: OpenZwave is not handing battery powered device very gently. The normal wakeup time is once every day. So in that case the situation may get back to normal after max 1 day. I did never wait that long, so I cant tell if that works for sure.

To be fixed (I think) : After OZW update dont loose battery powered devices but be clever about it by using stored device information. This is a OpenZwave issue, not a Domoticz issue, right ?

Note: I have set the Z-Rain wakeup time to 3600 seconds. So next time, when openzwave updates, if all is well Z-Rain should come back to normal within an hour. I may use a little more battery but that is fine.

**Comment by hvbommel** [comment]
I noticed the following in the ozw /domoticz/Config/options.xml 
    Should OZW automatically download new Config File Versions. Default is true
    <Option name="AutoUpdateConfigFile" value="false"

I was experementing with this options.xml, to see if it works so that later I can change the AutoUpdateConfigFile, and tried to log to a different file like this:
<Option name="LogFileName" value="openzwave.log"

But OpenZwave is not picking it up, it keeps logging to OZW_log.txt
Question: is there another location where I should edit this file so that it has effect on OpenZwave ?

Another question:
In my docker images I build the open-zwave MASTER branch.
@gizmocuz Question: what open-zwave branch would you currently recommend in combination with Domoticz, the master or another?

**Comment by gizmocuz** [comment]
@hvbommel , the 'AutoUpdateConfigFile' was set in Domoticz to 'true', but you should be able to change the name of log file with 'LogFileName'
I just made a commit to set it to 'false' (AutoUpdateConfigFile)
Use the default OpenZWave branch (which is the master)
Best to follow this guide:

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

Or use the binary

**Comment by hvbommel** [comment]
Thanks for the commit and the answers. It is building now. Once it is read I will verify the xml if AutoUpdateConfigFile is set to false. I will try to change the LogFileName again. Once done I will report here.

Use the binary is indeed maybe a better option. According to the OpenZwave folks these are the tested ones and recommended by them to use, I learned yesterday . This is what Justin Hammond said yesterday; "The tested builds are only the tar/zip files on the OZW site. if you continue to use HEAD of master - You are playing with fire. There Could be potential breakages etc in HEAD at any time"

**Comment by gizmocuz** [comment]
True, but I was talking about the Domoticz binaries not openzwave
Just make sure you disable openzwave , change the config file, then enable it

**Comment by hvbommel** [comment]
I was indeed thinking you ment ozw binaries, thanks for pointing out. I will get back here once my build is ready, it is still building.

**Comment by Pandabeer40** [comment]
Hi Gizmocuz and hvbommel,

I occur also problems with Zwave after upgrading to the latest beta 12227 / 12230 see also my post at: https://www.domoticz.com/forum/viewtopic.php?f=6&t=33418

Please can you advise how I get my wave network back to working?

**Comment by hvbommel** [comment]
I have installed the latest beta now. I see the following:
1. after initial image startup (not having the up to date ozw cache) I see the screen saying "Not all Nodes have been Queried yet, OpenZWave not fully initialized yet!"
2. Four minutes later (I have set my Z-Rain wakeup to 240 seconds) Z-Rain wakes up
3. Then everything is normal
4. Now at my next Domoticz restart all is ok immediate.

So this all looks like expected behaviour now. It also means the after initial install of domoticz it can take 24 hours (default wakeup time setting) before battery powered devices have their "normal" state.

Summary: 
I think the latest beta is a positive improvement. 
@Pandabeer40 I would recommend to install it and set your ozw device wakeup settings to a value you like.

Still one question remaining:
When I change my ozw logfile setting it does not work. It keeps logging to the default file. Am I overlooking something simple? 
I like to log to a mapped volume /log/openzwave.log so that I dont need to look into the container all the time, that is why.

Note:
Openzwave logging after domoticz startup. After the wakeup of Z-Rain all is normal again. So I think the below expected behaviour.

2020-07-19 12:42:54.078  Status: OpenZWave: using config in: /domoticz/Config/
2020-07-19 12:42:54.095  Status: OpenZWave: Starting...
2020-07-19 12:42:54.095  Status: OpenZWave: Version: 1.6-1210-g6cf37295

2020-07-19 12:47:58.906  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SENSOR BINARY, Label: Sensor, Instance: 1, Index: 0
2020-07-19 12:47:58.906  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: BATTERY, Label: Battery Level, Instance: 1, Index: 0
2020-07-19 12:47:58.994  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SENSOR MULTILEVEL, Label: General Purpose, Instance: 1, Index: 2
2020-07-19 12:47:59.038  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SENSOR MULTILEVEL, Label: Rain Rate, Instance: 1, Index: 12
2020-07-19 12:47:59.083  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: METER, Label: Water - m3, Instance: 1, Index: 32
2020-07-19 12:47:59.083  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: METER, Label: Exporting, Instance: 1, Index: 256

2020-07-19 12:48:02.544  (OpenZwave) General/Custom Sensor (Z-Rain Total)
2020-07-19 12:48:02.594  (OpenZwave) General/Custom Sensor (Z-Rain Rate)
2020-07-19 12:48:02.638  (OpenZwave) Rain (Z-Rain Water)
2020-07-19 12:48:02.694  Status: OpenZWave: All Nodes queried

**Comment by Juanuil** [comment]
Same problem here.
after update to 12230 battery operated devices get an id 000.
this looks like the sameproblem we had a couple of months ago with sending the value of battery power.
we then also had to renew node info and wake the devices up.

**Comment by hvbommel** [comment]
@Juanuil Can you please let us know:
- what build you are running
- if all ozw device have normal good status after they did at least one wakeup

Note: because I set my Z-Rain wakeup to 240 seconds this happens within 4 minutes in my case. I know it will cost a bit more battery power but I like the responsiveness.

**Comment by Juanuil** [comment]
Hi hvbommel,

Yes after a wakeup everything is oké.
build 2020.2 12230.
after a restart I have to wake them up again.

**Comment by hvbommel** [comment]
Or wait until they wakeup themselves. .

Question: Have you set "Assume Awake" to "False" in your ozw controller config?

I currently also run build 2020.2 12230 and so see improvements thanks to changes made by gizmocuz.

**Comment by hvbommel** [comment]
I see no evidence OpenZwave is loading the options file. I do see the below in the OZW_log.txt
cat OZW_Log.txt | grep domoticz/Config
2020-07-19 14:20:15.062 Info, Loading Localization File /domoticz/Config/Localization.xml
2020-07-19 14:20:15.064 Info, Loaded /domoticz/Config/Localization.xml With Revision 11
2020-07-19 14:20:15.067 Info, Loading NotificationCCTypes File /domoticz/Config/NotificationCCTypes.xml
2020-07-19 14:20:15.067 Info, Loaded /domoticz/Config/NotificationCCTypes.xml With Revision 11
2020-07-19 14:20:15.069 Info, Loading SensorMultiLevelCCTypes File /domoticz/Config/SensorMultiLevelCCTypes.xml
2020-07-19 14:20:15.069 Info, Loaded /domoticz/Config/SensorMultiLevelCCTypes.xml With Revision 4

@gizmocuz Do you have a easy way to prove that the options.xml file is in fact loaded and used instead of using the defaults? (instead of deep debugging). I am just curious if that is another little bug.

**Comment by gizmocuz** [comment]
@hvbommel , Why would it not be loaded ? And no it's not a bug.
It is loaded by openzwave by default, best to check the source code

**Comment by hvbommel** [comment]
np, I will debug it.

**Comment by Pandabeer40** [comment]
@hvbommel @gizmocuz I'm already running on 12230 - still with a lot of problems with Zwave - I have a floorthermostat running on power - also not recocnized

![Knipsel](https://user-images.githubusercontent.com/44602201/87878124-994d6700-c9e2-11ea-8d04-c4cfc1a099e3.PNG)

**Comment by Juanuil** [comment]
After waking the devices up problems are gone, even after restart

**Comment by Pandabeer40** [comment]
Not for me - I tried to awake some ZWave sensors / thermostat - without any result

**Comment by hvbommel** [comment]
@Pandabeer40 What build are you running? 
Like @Juanuil I see it all working so far with the latest build. (I only have a ozw logfile redirection issue, a minor problem, that I will debug.)

**Comment by Pandabeer40** [comment]
@hvbommel I run latest Beta 12230
![Knipsel](https://user-images.githubusercontent.com/44602201/87883218-3a99e480-ca06-11ea-84e2-530ff234bbfe.PNG)

**Comment by hvbommel** [comment]
@gizmocuz - I debugged my logging issue by tracing code. It turns out you can specify in LogFileName exactly what it says; the log filename. I was trying to provide a path & filename  (/log/OpenZWave.log). It does not accept that. And also, options.xml works great.

So you where right ... it is NOT a bug and works as intended. Sorry about that, thanks for your help.

**Comment by hvbommel** [comment]
@Pandabeer40 can you give your wakeup settings for all these devices?

**Comment by Pandabeer40** [comment]
@hvbommel I use some Spiritz Thermostat which have FLIRS in stead of wake up time - these Thermostat, most of them, are not recocgnized, Yesterday evening my CO sensor was in the list, now it's dissapeared again ;( - should I exclude all Zwave clients and included them again? (which are not recocgnized)

See print screen  some have had contact last couple of hours with the controller - but without result parameters

![Knipsel](https://user-images.githubusercontent.com/44602201/87903375-1ff25a80-ca5c-11ea-8688-e419278e6e67.PNG)

**Comment by hvbommel** [comment]
@Pandabeer40 I am not an expert on those (most) ozw devices so I can't advise. You may want to study the ozw logfile (OZW_log.txt), with debugging turned, on and see if that helps. Also you may want to exclude/include one or two and see if that works and see if they also survive restarts with the latest build (2020.2 build 12230 or later).

update for @pandabeer40
So yes I would recommend:
- run Domoticz 2020.2 build 12230 or later 
- exclude/include all your failing devices
- and see if it all continues to work fine after that point.

**Comment by hvbommel** [comment]
Good news report. I have added additional ZWave devices now. See below. And after Domoticz restart they all are ok immediate. I don't see any problems anymore since the code changes made by @gizmocuz . According to me this issue can be closed.

![OpenZwave-all-good](https://user-images.githubusercontent.com/14799318/87971180-354f9f00-cac5-11ea-83f0-00190c47221e.JPG)

**Comment by hvbommel** [comment]
This issue is quiett so I will close it. It all works for fine for since the change made by @gizmocuz.
