### ISSUE TITLE
Devolo Radiator Thermostat temperature measuring lost

### ISSUE THREAD

**Issue by beninhos** [domoticz/domoticz#4270]
Version: V4.10717
Platform: raspbian
Plugin/Hardware: razberry / Danfoss Devolo Home Control Radiator Thermostat (0x0175:0x0005) openzwave
Description:after working for a while temperature measuring stops in domoticz.
solution: re-pair the device..... (not nice)
expect: device not to loose connection or, if it happens, to re-synchronise after it.

Found out that the temperature arrives in the openzwave controlpanel http://<domoticzip>/ozwcp/cp.html
but domoticz stops receiving.

The thermostat function however, keeps working when this problem occurs.

**Comment by gizmocuz** [comment]
Is there anything in the log ? (An error or status)
I would expect if it is updated in the control panel, it also should update in Domoticz itself
Is it only at startup the temperature updates and during normal operation not ?

**Comment by beninhos** [comment]
Sorry for the delay, we building a case to make this issue more clear. We'll post this in the coming days. 

This occurs during normal operation, not just after a startup. 

To give some more details; it stops updating current temperature in a room at, like it went to sleep and did not wake, but the same thermostat however, keeps working and does give a signal to heat the room.

**Comment by janneman001** [comment]
Hi i work together with beninhos in this project. We have similar setups.

We work with: Danfoss Devolo Home Control Radiator Thermostats TVR. It is a OEM Danfoss product in which Devolo added temperature measuring.

I found nothing specific in the logs except an occasional:

2020-07-29 22:16:23.793 Status: OpenZWave: Received timeout notification from HomeID: 3741434132, NodeID: 31 (0x1f)

Indeed the situation for that particular device is a bad reception corner of the house.

I also have exact the same type TVR in a good reception place in the house. This one does not loose the temperature measuring for months.

It looks like the thermostat function in domoticz for this device is resilient to timeout and picks up again but the temperature function is not.

Domoticz ignores the temperature measuring completely after the timeout. However when i go to the openzwave panel i see the temperature is correct and keeps updating.

If i want domoticz to work with it again i need to remove the device and pair it again.

It should be equally resilient as the thermostat working in my opinion.

I hope this helps. If i can do more to move this forward please let me know. 
 
regards,
Jan

**Comment by beninhos** [comment]
hi @gizmocuz is there anything info we can add to help solve this issue?  I made screenshots, because my logfile says nothing about the issue. 

Look at the device with nodeId=009 (0x09). It's clearly online, and had been for a while.

- Temperature does not load and says it's still offline.
- Thermostat is online and gives signal to heat the room to 15.0 degrees (not a real issue in the summer :-))
- Battery status does get a readout, but the air temperature does not. 

now, this situation is after a power outage in this house. But it helps explaining what is happing during normal runtimes too. There's not a consistent readout. 

<img width="992" alt="Schermafbeelding 2020-08-31 om 20 47 58" src="https://user-images.githubusercontent.com/15123228/91758514-6fd24e80-ebd0-11ea-8e3e-385900339ff7.png">
<img width="1244" alt="Schermafbeelding 2020-08-31 om 20 47 42" src="https://user-images.githubusercontent.com/15123228/91758523-73fe6c00-ebd0-11ea-823e-85aaf9123fdc.png">

**Comment by janneman001** [comment]
I have a similar issue now with another setup and the FIBARO System FGBS001 Universal Binary Sensor. With temperature sensors connected.

After a while the updating in domoticz stops. However when i look into the openzwave control panel, communication still goes on. Temperature is updated correctly.

These are 3 separate  domoticz setups with similar issue that a zwave device update on temperature stops updating over time and is not able to re-connect. However openzwave is.
 
What can i do to get this forward?

**Comment by gizmocuz** [comment]
@janneman001 , you could update to the latest beta version. There has been a second update method enabled

**Comment by janneman001** [comment]
Ok. Until now always followed stable. I will try the beta now.

**Comment by janneman001** [comment]
@gizmocuz 

I updated 2 sites with the Beta. Let's say site L and site Z.
Site L now works on DomoticzV2020.2 (build 12377) since September 16
Site Z a little later DomoticzV2020.2 (build 12392) since September 19

Site L with Rpi2 Razberry did not update without some problems however this is the oldest and might have some legacy in the db.
I found out i had to update to Raspbian Buster (i did that first).

- Zwave control Panel works now and then
- I had to re-pair some window sensors (zwave)
- RF433 suffers from amnesia for some nodes. Had to re-learn them.

However the Devolo TRVs nodes healed by this domoticz version, temperature measuring started again and work like a charm since then.

Site Z with Rpi3B+ Aeonlabs gen5 usb and even more develo's and the fibaro binary sensor updated like a charm and works since then flawless.
Also the open zwave panel works there like before.
Also new tabs appeared in the domoticz zwave hardware panel with nice overview and graph.

Thanks for your advice.
My convidence about the product has grown.

Would like to know still when i can go back to stable. I mean what is the expectation of these betas to be declared stable?

regards,
J.

**Comment by janneman001** [comment]
![Schermafdruk van 2020-09-26 12-26-57](https://user-images.githubusercontent.com/7555596/94338567-aa72af80-fff3-11ea-814f-a989cf3dc08a.png)
Really nice!

**Comment by gizmocuz** [comment]
@janneman001 , you can not go 'back' to a previous version, so best to stay with the beta
It's time for a new stable soon

**Comment by beninhos** [comment]
I can confirm the latest version fixed my issue too.  Great 👍 

Did something change in the battery-status readout too? I kinda found out the after the beta update, that some battery's were reported empty, but they were not even close to that and at least at 50% .
