### ISSUE TITLE
Notifications with Xiaomi temperature sensors

### ISSUE THREAD

**Issue by Marbaf** [domoticz/domoticz#4273]
Hi all,
I have setup email notifications on different temperature devices from rfxcom or Xiaomi gateway.
After loss of all my freezer content, I found out that all triggers on Xiaomi temperature values does not work no matter the comparison.
No issue with other temperature sensors.
BR

**Comment by rwaaren** [comment]
Tested with current build (12230) and Xiaomi temperature sensor but cannot reproduce the issue. (Moved sensor outdoor to test)
Received below Email and similar alert on all other configured notification susbsystems.

![Xiaomi](https://user-images.githubusercontent.com/24454798/87902942-2cc27e80-ca5b-11ea-9f81-43ac646d9fa3.png)
