### ISSUE TITLE
Solaredge api three phase

### ISSUE THREAD

**Issue by marsflow2** [domoticz/domoticz#4274]
Hello 

modify the Solaredge API file for three-phase please

Json result :

`08:04:41","totalActivePower":297.0,"dcVoltage":748.812,"groundFaultResistance":7629.18,"powerLimit":100.0,"totalEnergy":8076800.0,"temperature":44.3057,"inverterMode":"MPPT","operationMode":0,"vL1To2":400.938,"vL2To3":403.0,"vL3To1":403.156,"L1Data":{"acCurrent":0.8125,"acVoltage":230.562,"acFrequency":50.0135,"apparentPower":189.0,"activePower":80.0,"reactivePower":-171.0,"cosPhi":1.0},"L2Data":{"acCurrent":0.976562,"acVoltage":232.969,"acFrequency":50.0133,"apparentPower":244.0,"activePower":80.0,"reactivePower":-212.0,"cosPhi":1.0},"L3Data":{"acCurrent":1.04688,"acVoltage":233.375,"acFrequency":50.0122,"apparentPower":227.0,"activePower":137.0,"reactivePower":-201.0,"cosPhi":1.0}},{"date":"2020-07-23 
`

thank you

**Comment by gizmocuz** [comment]
@marsflow2 , could you test beta 12238 ? It should now support 3 phase inverters
