### ISSUE TITLE
RFXCOM:  Please add Byron BY support for transmit

### ISSUE THREAD

**Issue by jefft4** [domoticz/domoticz#4276]
Enhancement request - add Byron BY to supported *transmit* protocols for rfxcom.

To elaborate on the request:
There are more *transmit* protocols on the list in current rfxmngr versions than are available in domoticz when creating a new rfxcom device - Byron BY is one example.  Could we please add Byron BY transmit capability?

Specifically about BY *transmit*:
- There's no way to transmit Byron BY from domoticz; the protocol is not listed when creating a device and the Byron SX protocol is not sufficiently compatible.  I’ve tried different possible device IDs under SX and nothing activates my BY chimes.

Details:
SX: rfxmngr has a three-byte device ID, 00 – xx – yy, and a tune ID [0-15]; domoticz gives a two-byte device ID (presumably the xx – yy part) and a unit code [1-16].
BY: rfxmngr has a three-byte device ID, [00|01] – xx – yy, and a tune ID [0-7], no unit ID.

I've also had a problem with how BY is received, for which I'll raise a second issue to include whatever detailed info I can get (I don't have the set-up here to compile and debug the domoticz source code so I will be limited to eyeballing the code for clues).

For what it's worth, currently running 2020.2 on Ubuntu 19.04 x64.

**Comment by gizmocuz** [comment]
@jefft4 , this is not a forum. So the least you could do is search in the Domoticz code for references of Byron BY
Next to this, when you made this issue, there was a guideline with all kinds of questions that you did not fill in
Because of this we do not even know the version of Domoticz you are using.
The ByronBY should be able to be received, so best to compile Domoticz and set a breakpoint in **MainWorker::decode_Chime**

**Comment by jefft4** [comment]
@gizmocuz, my apologies, looking back I see that it's a very broad request, perhaps not helpful.  I've edited to make it much more specific.

It's enhancement request so I assumed that it would be best raised as a ticket here to join the queue... if you want enhancements logged somewhere else, just say and I’ll move it.

**Comment by gizmocuz** [comment]
@jefft4 , maybe best to debug Domoticz and help implement this.
Thanks for completing your first post, it's still missing the version you are using ...

**Comment by jefft4** [comment]
Added version, for what that's worth.  You're flattering me quite a lot by assuming that I have enough skills in the right language to do the work!  ;-)

**Comment by gizmocuz** [comment]
@jefft4 , I think by having some small looks you should be able to debug...
Problem is that I do not own a Byron BY device and therefor I am unable to debug this
I could order one if there not to expensive. Could you show me a picture of the device ?

![image](https://user-images.githubusercontent.com/2265299/90222623-ba9c4a00-de0c-11ea-9871-253f5ab5a9f4.png)

Do you live in the Netherlands by any chance ?

**Comment by jefft4** [comment]
I have several around the house; this is a basic one: https://www.chbyron.eu/byron-20-001-69-plug-in-door-chime-100m-by202-20.001.69  (GBP25, Amazon).  I'm in the UK, but I could send you a transmitter and chime if the need be (I have spares).  There might be positive news on the code too...  Just pulled down the domoticz source and had a look in VSCode; it's C++, which I've not used properly in about 15 years but I do remember enough of for small changes... so that's a positive start :-)  

I'll search through and see if I can at least work out what needs to change.  I've already spotted where BY is mapped onto 'SelectPlus3' for receive, which causes some strange behaviour that I'd like to change.  Haven't found the device create/transmit part yet, more functions to look at...

Is there any documentation around that would help me to understand (1) the architecture of domoticz and how the modules relate, (2) how domoticz handles the RFXCom API and (3) why people have done things previously like mapping BY to SelectPlus3?  Best if I can avoid recommending changes that break something that was done for a good reason.  

Aside - looks like two guys wrote most of the RFX handling code, according to Git.  Either of them still involved with domoticz?

J.

**Comment by gizmocuz** [comment]
Do you know the names of those two guys ? Maybe by looking at them you could figure out if they are still involved with Domoticz?
Would be great If you could send me a chime/transmitter as loan for testing, please contact me on the forum (same username)

**Comment by jefft4** [comment]
PM sent on the forum re bells.  I also included some more info about the receive side problem with BY, with an example.

The names that Git is showing most in the RFX code, aside from your own, are Rob Peters (mostly 2018, seems to have been updating RFXCom for the 433XL and newer firmware) and Stuntteam (2016, adding more RFX devices); dzelyaydinov also had his/her hands in some of the modules.

**Comment by gizmocuz** [comment]
@jefft4 , I am not sure where you look, but best to have a look here:
https://github.com/domoticz/domoticz/commits/development/main/RFXtrx.h

I have replied to your PM

**Comment by jefft4** [comment]
Thanks.  BY is there - interestingly, RFXCom seem to have renamed SelectPlus3 to BY, or replaced it, at some point.   

Transmit looks like it should be simple enough, as all the definitions for BY are there in RFXCom's headers; just need to change the domoticz RFX manual switch creation functionality to define the BY attributes and add the extra protocol.

The BY receive problem (wrong address, sound ID as part of address) seems to be with how the received data structure is interpreted; rfxmngr gets it right, domoticz looks like it's slipped the data by a few bits.  I'd need to set up some debugging and look at the received data to see whether that's caused in RFXCom's structure or in domoticz.  If you can advise on a good toolchain to use, I'm up for giving that a try while I get a chime over to you to play with.

**Comment by gizmocuz** [comment]
@jefft4 , I will advise to use Visual Studio 2019 (See INSTALL.txt file), when you build in debug mode you can set breakpoints

**Comment by jefft4** [comment]
Perfect.  Installing it now... :-)

**Comment by gizmocuz** [comment]
@jefft4 , Please try beta 12252 (building now), you will get a new Chime device, but with this device you should also be able to trigger the BY201

**Comment by jefft4** [comment]
That's a neat approach, combining transmit and receive into a single device; I like it!

Loaded 12269 (that was latest on the beta channel by the time I got to it) and it works a treat.  Thank you :-)  
BY chime now shows on receive as [ ID F85685  | Unit 133 | Chime | Byron BY ] and if I set the switch type to 'doorbell' then click it in the UI, it chimes.  Perfect.

Will this create a new chime device for each chime sound, if the sound number is changed, or does it ignore the sound number now?

**Comment by gizmocuz** [comment]
@jefft4 , this will create a new device for every new sound. But..... I could not find a way to change the sound, is that possible on the doorbell ?

**Comment by jefft4** [comment]
It's done by the transmitter; there's a little button inside that cycles through the available sounds.  https://www.chbyron.eu/product/attachment?productId=00.640.36&attachmentName=b66b1842-5535-4e8e-ac13-33b050300ad9__00.640.36_IM_ZZZ.pdf
The 'sound ID' is part of the message decoded by RFXmngr from the RFXCom; I think I identified which bits it is in the example codes that I PM'd you on the forum.  If I cycle my transmitter (BY32) through the sounds, I get 8 devices in domoticz with IDs F85680 / Unit 128 through to F85687 / Unit 135, so the sound ID is still being taken as part of the device ID as it was previously.  Not all the chimes have that many sounds, some repeat sounds to make up the set.

Ideally, we would ignore those sound ID bits when deciding if it's a new device on receive so as not to create lots of possible chime devices and have to guess which is the doorbell today ;-) but maybe that wouldn't work so easily for transmit as the device would then need the sound ID as an attribute to set when transmitting.  Perhaps we could create all 8 possible devices and group them somehow so that we can monitor the group or parent for receive while using the individual devices for transmit?

**Comment by jefft4** [comment]
Tried a workaround using existing functionality...  I can add all the chimes as activation devices to a group with one dummy device 'doorbell'.  All 8 sounds then switch on the dummy just fine, but downside is that the group isn't like a momentary push switch and doesn't ever go back to the 'off' state.
I guess I could add an event to switch it off after a couple of seconds, although in that case, it'll probably be more effective to write an event to monitor the 8 chimes.

**Comment by gizmocuz** [comment]
@jefft4 , I guess you choose 'a' sound, and leave your doorbell at it ?

**Comment by jefft4** [comment]
When it works... occasionally I've seen them change the sound without being asked!

I guess the conflict between ignoring sound ID on receive and needing it on transmit isn't easily resolved given that a doorbell switch device has no additional attribute to hold the sound ID.  I'm also not certain that a second bell push - say, at a side door - can't cause a different sound; it would make some sense if it did.  

Writing a little event to handle the 8 possible chimes will be the way to go.  Well worth it to have the 8 transmit options.

**Comment by gizmocuz** [comment]
@jeff, if you want to make it totally correct, you have to generate the ID as:

	//Convert to ID
	uint8_t id1 = CHIME.id1 >> 7;
	uint8_t id2 = ((CHIME.id1 << 1) & 0xFF) + (CHIME.id2 >> 7);
	uint8_t id3 = ((CHIME.id2 << 1) & 0xFF) + (CHIME.sound >> 7);
	uint8_t unit = CHIME.sound & 0x07;

	//Convert Back
	CHIME.id1 = (id1 << 7) | (id2 >> 1);
	CHIME.iid2 = ((id2 << 7) & 0xFF) | (id3 >> 1);
	CHIME.sound = ((id3 << 7) & 0xFF) | unit;

I will leave that PR for you ;)
