### ISSUE TITLE
Crash in CEventSystem::SetEventTrigger

### ISSUE THREAD

**Issue by RDols** [domoticz/domoticz#4278]
Looking for some zwave issue in run into an unhandeld exception. It's in CEventSystem::SetEventTrigger, more exactly while erasing the iterator from m_eventtrigger.

``` c++
  for (auto itt = m_eventtrigger.begin(); itt != m_eventtrigger.end(); ++itt)  
  {
    if (itt->ID == ulDevID && itt->reason == reason && itt->timestamp >= atime)
    {
      m_eventtrigger.erase(itt--);
    }
  }
```
I'm pretty sure this is not the correct way to delete element inside an loop. The (old) iterator is broken after an erase. Luckily easy to fix. Erase returns the next (new) element, or end() if it was the last one.
``` c++
  for (auto itt = m_eventtrigger.begin(); itt != m_eventtrigger.end();)  
  {
    if (itt->ID == ulDevID && itt->reason == reason && itt->timestamp >= atime)
      itt = m_eventtrigger.erase(itt);
    else
      itt++;
  }
```

I had a deja-vue, thought i had fixed this before, but was not the same:
https://github.com/domoticz/domoticz/pull/3722/commits

I did an short search for simular situations, found some:
- HttpClient.cpp, bool SocketSet::update(), _store.erase(it++);
- WakeUp.cpp, void WakeUp::QueueMsg(Driver::MsgQueueItem const& _item), m_pendingQueue.erase(it++);
- ValueStore.cpp, void ValueStore::RemoveCommandClassValues(uint8 const _commandClassId), m_values.erase(it++);
- Tellstick.cpp, void CTellstick::ThreadSendCommands(), m_commands.erase(it++);
- TCPServer.cpp, bool CTCPServerProxied::OnDisconnect(const std::string &token), connections_.erase(itt);

Will fix what i find, and create an pull request. But wil take a little while. Currently i have debug code i don't want to push.

Regards,
  Richard

**Comment by gizmocuz** [comment]
@RDols , is it possible to verify that it's working correctly now ? Your PR has been applied (Thanks bdw!)
