### ISSUE TITLE
Loosing domoticz login password

### ISSUE THREAD

**Issue by hvbommel** [domoticz/domoticz#4287]
My password is lost every week or so. Because of this my remote logins fail. Locally (192.168.x.x)  everything keeps working fine. After setting the password, using local connection & the settings screen, remote login works again. I am looking for hints to troubleshoot & fix this.

**Comment by gizmocuz** [comment]
@hvbommel , when you use 'Remember me' you will get a cookie that should be valid for about a month.
It could be that you installed some browser extensions/applications that cleans this ?

**Comment by hvbommel** [comment]
I am seeing the problem starting at the same time on multiple browers on multiple machines. Also the domoticz app and pilot fail when remote (ie not on 192.168.x.x)  Only after I set the password (to the same I am expecting) on the the domoticz settings page I can login on all browsers and the apps work fine again. So to me it does not look like a cooky issue.

**Comment by hvbommel** [comment]
Status update: I have not seen it happen again. I will just wait a bit longer and get back here.

**Comment by hvbommel** [comment]
Closing it. I did not see it happen anymore. If I see it again I will reopen it.
