### ISSUE TITLE
Improvement/openweathermap (#4284) results in coredump

### ISSUE THREAD

**Issue by svde** [domoticz/domoticz#4288]
Compiling & running commit d5da96f53152e19261602f94db459c4835a29cd5 (domoticz-2020.2.12234) results in:

Aug 12 10:36:20 void domoticz[2648825]: 2020-08-12 10:36:20.372  Status: OpenWeatherMap: Got invalid poll interval (0). Using default 600.
Aug 12 10:36:20 void domoticz[2648825]: terminate called after throwing an instance of 'std::invalid_argument'
Aug 12 10:36:20 void domoticz[2648825]:  what():  stoi
Aug 12 10:36:20 void audit[2648825]: ANOM_ABEND auid=4294967295 uid=988 gid=985 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 pid=2648825 comm="domoticz" exe="/usr/bin/domoticz" sig=6 res=1
Aug 12 10:36:20 void audit: BPF prog-id=4287 op=LOAD
Aug 12 10:36:20 void audit: BPF prog-id=4288 op=LOAD
Aug 12 10:36:20 void systemd[1]: Started Process Core Dump (PID 2648833/UID 0).
Aug 12 10:36:20 void audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@1-2648833-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 12 10:36:20 void systemd[1]: domoticz.service: Main process exited, code=dumped, status=6/ABRT
Aug 12 10:36:20 void systemd[1]: domoticz.service: Failed with result 'core-dump'.
Aug 12 10:36:20 void audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=domoticz comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Aug 12 10:36:20 void systemd-coredump[2648834]: Process 2648825 (domoticz) of user 988 dumped core.#012#012Stack trace of thread 2648825:#012#0  0x00007f8366ad3915 raise (libpthread.so.0 + 0x14915)#012#1  0x000056297b08c7c1 _Z14signal_handleriP9siginfo_tPv (domoticz + 0x31f7c1)#012#2  0x00007f8366ad3a90 __restore_rt
 (libpthread.so.0 + 0x14a90)#012#3  0x00007f83664cb9e5 raise (libc.so.6 + 0x3c9e5)#012#4  0x00007f83664b4895 abort (libc.so.6 + 0x25895)#012#5  0x00007f8366714961 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold (libstdc++.so.6 + 0x9e961)#012#6  0x00007f836672044c _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6
+ 0xaa44c)#012#7  0x00007f83667204b7 _ZSt9terminatev (libstdc++.so.6 + 0xaa4b7)#012#8  0x00007f8366720769 __cxa_throw (libstdc++.so.6 + 0xaa769)#012#9  0x00007f8366717370 _ZSt24__throw_invalid_argumentPKc (libstdc++.so.6 + 0xa1370)#012#10 0x000056297b35cc68 _ZN9__gnu_cxx6__stoaIlicJiEEET0_PFT_PKT1_PPS3_DpT2_EPKcS5_P
mS9_ (domoticz + 0x5efc68)#012#11 0x000056297b04f499 _ZN10MainWorker21AddHardwareFromParamsEiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb15_eHardwareTypesS7_tS7_S7_S7_S7_iiiiiiib (domoticz + 0x2e2499)#012#12 0x000056297b051268 _ZN10MainWorker22AddAllDomoticzHardwareEv (domoticz + 0x2e4268)#012#13 0x000056
297b05319a _ZN10MainWorker5StartEv (domoticz + 0x2e619a)#012#14 0x000056297af6e570 main (domoticz + 0x201570)#012#15 0x00007f83664b6042 __libc_start_main (libc.so.6 + 0x27042)#012#16 0x000056297afac35e _start (domoticz + 0x23f35e)#012#012Stack trace of thread 2648826:#012#0  0x00007f8366557801 clock_nanosleep@@GLIBC
_2.17 (libc.so.6 + 0xc8801)#012#1  0x00007f836655d157 __nanosleep (libc.so.6 + 0xce157)#012#2  0x000056297b0083f5 _ZNSt11this_thread9sleep_forIlSt5ratioILl1ELl1000EEEEvRKNSt6chrono8durationIT_T0_EE (domoticz + 0x29b3f5)#012#3  0x000056297b08c988 _Z16Do_Watchdog_Workv (domoticz + 0x31f988)#012#4  0x00007f836674eb84 e
xecute_native_thread_routine (libstdc++.so.6 + 0xd8b84)#012#5  0x00007f8366ac8432 start_thread (libpthread.so.0 + 0x9432)#012#6  0x00007f8366590913 __clone (libc.so.6 + 0x101913)#012#012Stack trace of thread 2648828:#012#0  0x00007f8366557801 clock_nanosleep@@GLIBC_2.17 (libc.so.6 + 0xc8801)#012#1  0x00007f836655d15
7 __nanosleep (libc.so.6 + 0xce157)#012#2  0x000056297b0083f5 _ZNSt11this_thread9sleep_forIlSt5ratioILl1ELl1000EEEEvRKNSt6chrono8durationIT_T0_EE (domoticz + 0x29b3f5)#012#3  0x000056297b4bebd2 _ZN7Plugins13CPluginSystem7Do_WorkEv (domoticz + 0x751bd2)#012#4  0x00007f836674eb84 execute_native_thread_routine (libstdc
++.so.6 + 0xd8b84)#012#5  0x00007f8366ac8432 start_thread (libpthread.so.0 + 0x9432)#012#6  0x00007f8366590913 __clone (libc.so.6 + 0x101913)#012#012Stack trace of thread 2648827:#012#0  0x00007f836658b37d syscall (libc.so.6 + 0xfc37d)#012#1  0x00007f836674c4df _ZNSt28__atomic_futex_unsigned_base19_M_futex_wait_unti
lEPjjbNSt6chrono8durationIlSt5ratioILl1ELl1EEEENS2_IlS3_ILl1ELl1000000000EEEE (libstdc++.so.6 + 0xd64df)#012#2  0x000056297b0ae30e _ZNSt23__atomic_futex_unsignedILj2147483648EE22_M_load_and_test_untilEjjbSt12memory_orderbNSt6chrono8durationIlSt5ratioILl1ELl1EEEENS3_IlS4_ILl1ELl1000000000EEEE (domoticz + 0x34130e)#01
2#3  0x00007f836674eb84 execute_native_thread_routine (libstdc++.so.6 + 0xd8b84)#012#4  0x00007f8366ac8432 start_thread (libpthread.so.0 + 0x9432)#012#5  0x00007f8366590913 __clone (libc.so.6 + 0x101913)
Aug 12 10:36:21 void systemd[1]: systemd-coredump@1-2648833-0.service: Succeeded.

Reverting to the previous commit (c00c8e0c606df2991a6fb9ecbf42b975261f94ac) lets domoticz run fine.

**Comment by gizmocuz** [comment]
What did you previously used as parameter for OpenWeatherMap ? A lat/long or station ID ?

**Comment by gizmocuz** [comment]
I noticed that previously we had to supply the lat/long parameter as "lat=12.2233&lon=34.1764" where now it expects 52.2233,5.1764
And because of this it is now crashing... I will patch some code... small moment

**Comment by svde** [comment]
Station name (Meerhoven in my case).

**Comment by gizmocuz** [comment]
This patch also breaks default behavior as the current values are not used anymore by default... going to patch this as well

**Comment by gizmocuz** [comment]
And also with this patch you can not use city names anymore since the API call has been changed
But we can resolve the city to lat/long values again because the original API call provides these

![image](https://user-images.githubusercontent.com/2265299/90018589-70e91d80-dcad-11ea-8424-acf67e2e9289.png)

Still this patch was way from finished.... (almost done here)

**Comment by gizmocuz** [comment]
@svde , Is it possible you could verify it is working again ?

**Comment by kiddigital** [comment]
Sorry @svde that I broke your environment. I should have at least documented the incompatibility and handled the 'old' value better instead of crashing.

For me it was a design decision to break backward compatibility because you could consider the way it 'worked' before was actually flawed.  The setting screen (re-use of the Wunderground settings screen) stated that you should specify lat,lon (same as most other services) and you had to figure out yourself what the expected way of specifying was. I had to find out through the code and also some posts on the forum to get the old version working! And the old way just happened to be the way the old API expected parameters. The new API expected it different (and more) so I decided to make it work more logical and also in sync what the user sees in the settings.

@gizmocuz , apologies in breaking compatibility.  A next time I will document some relevant design decision better in the Pull Request so at least it is clear. Is there a way to handle these kind of 'breaks'?

 I noticed that you added some code to handle to old way of specifying and although that works, it also add instant legacy code that keeps being dragged along. Of course I should have handled the old input without crashing. Reporting an error message stating that the input was (now) wrong and should be changed would already be much better.

What could be a good way to inform the users?

**Comment by gizmocuz** [comment]
@kiddigital , there is no latency, the lat/lon is only resolved once during startup

**Comment by svde** [comment]
> Sorry @svde that I broke your environment.
No problem!

After @gizmocuz fix / roll-back, my original setting also didn't work. I then tried putting the lat/lon in, and also "0". None of these worked for me. I used this opportunity to switch to the Buienradar plugin, which I've already been using for rain prediction.

**Comment by kiddigital** [comment]
> > Sorry @svde that I broke your environment.
> 
> No problem!
> 
> 
> 
> After @gizmocuz fix / roll-back, my original setting also didn't work. I then tried putting the lat/lon in, and also "0". None of these worked for me. I used this opportunity to switch to the Buienradar plugin, which I've already been using for rain prediction.

 @svde  Hm.. that is weird. Was there anything within the logs that revealed why it didn't work?
If historical data isn't relevant. Could you try to delete the OWM hardware and add a new one? See if that does work... (maybe run with debug logging turned on if it doesn't)

BTW: I run both OWM and Buienradar as OWM has weatherstation closer to my location than Buienradar does :) Fun to see the differences and now the new OWM has much more sensors than Buienradar.

Interested to get feedback on your experience with OWM. Thx

**Comment by gizmocuz** [comment]
@svde, there has been a new update that has been tested with:
0 (uses your current latitude/longitude configured in the Domoticz Settings)
lat,lon (52.1,6.3)
City (Amsterdam)
Cite,Country (Amsterdam,NL)

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/issues/4290

**Comment by sonar98** [comment]
At this moment it is not possible to put in the StationID anymore.
In the description in hardware it says it would be possible:
(StationID of Lengte,Breedtegraad)
(0 = Standaard instelling)

**Comment by gizmocuz** [comment]
Correct, that is the only one that needs to be implemented. I see what I can do about this...

**Comment by kiddigital** [comment]
> Correct, that is the only one that needs to be implemented. I see what I can do about this...

@gizmocuz , if it helps I am willing to write a patch for this asap (as I might have caused the issue in the first place). Just let me know.

**Comment by gizmocuz** [comment]
@kiddigital , I think it's best if i continue doing this as I also implemented to other options, should not be that hard

**Comment by gizmocuz** [comment]
@sonar98 , It's a bit unclear how users should find out station id's on the openweathermap site
Could you provide yours as example, or some examples?
I think they look like: 583436dd9643a9000196b8d6
Do they always have a fixed length? (24 bytes = 192bit)

**Comment by sonar98** [comment]
For Utrecht it is:
2745912

On openweathermap.org there is a searchbox in the top (black) bar.
If you search for a city there you get the results page withh a links to the weatherstations like this:
https://openweathermap.org/city/2745912


This is in the old API documentation:

[By city ID](https://openweathermap.org/current#cityid)
Description:
You can call by city ID. API responds with exact result.
We recommend to call API by city ID to get unambiguous result for your city.

List of city ID city.list.json.gz can be downloaded here http://bulk.openweathermap.org/sample/

API call:
api.openweathermap.org/data/2.5/weather?id={city id}&appid={your api key}

Parameters:
id City ID
Examples of API calls:
api.openweathermap.org/data/2.5/weather?id=2172797

**Comment by gizmocuz** [comment]
@sonar98 , thanks! Got it working, but it is a City-ID, not a Station-ID... (in the web gui, changes that as well)
Could you test with beta 12242, should now also work

**Comment by sonar98** [comment]
Changed the settings from lat,lon to the Station-ID and I'm getting data from openweathermap.

So, yes it is working now.
