### ISSUE TITLE
Fibaro FGR 223 not working as expected

### ISSUE THREAD

**Issue by mooky31** [domoticz/domoticz#4289]
Hello,

As described [here](https://www.domoticz.com/forum/viewtopic.php?t=30382#p241279), Domoticz does not correctly send the 'Open' command to FGR-223. 
It sends value 255, which means set last position, not 'Open'. 
For 'Open', FGR-223 expects value 99 (that is actually quite clearly described in Z-Wave SWITCH_MULTILEVEL command specification). So if you only open/close a blind, that will work, but only due to the fact, that previous position would be 0 (closed) or 99 (opened). 
But if you try to position the blind on intermediate level (for example 50%), it sets at 50%. Then you press close, it closes. Then you press open, it sets at 50% instead of fully opening.

The topic gives some workarounds, but they are very dirty.
Could you please implement a quirk for this device in domoticz ?

Thank you

**Comment by gizmocuz** [comment]
Probably related to this pull request https://github.com/domoticz/domoticz/pull/4285

**Comment by mooky31** [comment]
Yes this is it !
As I don't want to take the risk to use my own built version of domoticz, I hope it will be commited and I'll have to wait for the next release.

**Comment by waltervl** [comment]
> Probably related to this pull request #4285
