### ISSUE TITLE
Crashes after upgrading tot 2020.2 (12236), reason unknown

### ISSUE THREAD

**Issue by zeddski** [domoticz/domoticz#4290]
Hi all,

I've upgraded to the latest release, only to have Domoticz crash on me. After a service restart it just crashes again (restart_errors.txt).
The error messages do not help me further.
What I've tried so far:
- Remove Z-Wave cache as this seems a sore point in Domoticz. Did not help.
- Reinstalled fresh Domoticz, restored a backup, crash (restore_errors.txt).
- Tried temporarily removing the Config folder, crash.

I'm not convinced Z-Wave is the problem, but have no idea where to start looking for the cause. Help is very much appreciated.
Crash log uploaded.

Regards,
- Zeddski

[Restore_errors.txt](https://github.com/domoticz/domoticz/files/5067757/Restore_errors.txt)
[Restart_errors.txt](https://github.com/domoticz/domoticz/files/5067758/Restart_errors.txt)
[domoticz_crash.log](https://github.com/domoticz/domoticz/files/5067786/domoticz_crash.log)

**Comment by zeddski** [comment]
Update: did some more digging and found the offending hardware to be my OpenWeather device.
I was triggered by Error # 13, where apparently this device did something to crash Domoticz
`Error: #13 0x00528b84 in COpenWeatherMap::StartHardware() ()`
I restored my previous version and database, disabled the OpenWeather device and retried the upgrade. No more problems. Restarted Domoticz several times without issues.

Seems some part of this virtual device don't work correctly in this release.
Please let me know if I can do something to help figure this out!

**Comment by gizmocuz** [comment]
@zeddski , try updating to the new beta version, i think this has been solved already, if not , let me know what parameters you use in your current openweather hardware setup (please post the value here)

**Comment by zeddski** [comment]
@gizmocuz I did upgrade to the latest version, that's where my troubles began.
I've found the issue though: the "location" parameter was set to my home town "Rosmalen,NL". This has worked in the past, apparently not anymore. By putting lat&lon in the location parameter it all works fine.
I'm now running 12236 with OpenWeather enabled and running. Thanks!

**Comment by gizmocuz** [comment]
I will try to get your home town location also to work. I think it is seen as lat/lon now (rosmalen=lat, NL is lon), without ,NL it could work as well
Let me try to debug this

**Comment by gizmocuz** [comment]
Please try beta 12240, should now be possible again to also enter a City,Country as configuration parameter.
Hope all combinations are now possible again

**Comment by zeddski** [comment]
Works - thanks for the (very) quick response.
Both parameter styles (lat/lon and city/country) now work for me.
Logging shows correct lat/lon when city/country is used 👍
