### ISSUE TITLE
add new option (eg. set temp set childlock) to  device ts0601 

### ISSUE THREAD

**Issue by Bartekn86** [domoticz/domoticz#4291]
please add nev device 
mqtt supports ts0601 but domoticz not,
https://aliexpress.ru/item/4001043738901.html?spm=a2g0s.9042311.0.0.1b6033edHXNB4c&_ga=2.27185918.2138683156.1593276537-279917533.1590225196
This is thermostatic valve that we want to add to domoticz
Domoticz can not read temperature and can not set what is able to set in thermostat
https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/TS0601_thermostat.md**

**Comment by Bartekn86** [comment]
hi, 
i know that is not a forum, sb can confirm that domoticz cant read/set  values from  ts0601 ?
what is the chance of getting interested in the problem?

**Comment by gizmocuz** [comment]
@Bartekn86 , you need to create a Forum topic as well, there are more users on the Forum that could help you.

But here, you should at least post the answers to the issue guidelines when you created the issue,
also post the MQTT message the thermostat publishes, the device type / sub type in Domoticz (if it a setpoint device in Domoticz ? Should be), what is Domoticz publishing to MQTT ?
Way more info please

**Comment by gizmocuz** [comment]
And I think you are using Zigbee2MQTT ? There is probably a section about that on the Forum, but also edit this topic and at least mention this!

**Comment by Bartekn86** [comment]
Thanks for response, im newbie in home automatic so dont be nervous please :-) in my opinion, this link explains it all
I do not know how to check what is really sending domoticz, but I know that in the place mqtt -> devices i can read values ​​fromsensors e.g TT001ZAV20 but not from ts601 
https://github.com/Koenkk/zigbee2mqtt/issues/3821  

Thank you

**Comment by pipiche38** [comment]
You can have a dedicated Switch On/Off for Child Lock
