### ISSUE TITLE
Distance virtual sensor does not convert between centimeters and inches correctly

### ISSUE THREAD

**Issue by cookemmm** [domoticz/domoticz#4292]
I created a virtual sensor and it reported 29.8 centimeters...I edited the sensor and changed the display to inches and it reports 18.5 inches. 29.8 centimeters should convert to 11.73228 inches.

**Comment by rwaaren** [comment]
> I created a virtual sensor and it reported 29.8 centimeters...I edited the sensor and changed the display to inches and it reports 18.5 inches. 29.8 centimeters should convert to 11.73228 inches.

What is your domoticz version?
what type / subtype is the device? 
How is the device updated?
Where did you made the change?

**Comment by cookemmm** [comment]
What is your domoticz version? 2020.2
what type / subtype is the device? Virtual/Distance 
How is the device updated? HTTP call to domoticz
Where did you made the change? Press the Edit button on the device on the utility screen

**Comment by gizmocuz** [comment]
@cookemmm , thanks for reporting. We were converting to miles instead of inches.
Solved in beta 12246
