### ISSUE TITLE
1wire: Reading sensors values from OWFS sometimes fails

### ISSUE THREAD

**Issue by Erik-NA** [domoticz/domoticz#430]
Using owfs 3.0p2 with a onewire hub (https://www.hobby-boards.com/store/pages.php?pageid=8) together with humidity/temp-sensors based on DS2438.

Sometimes Domoticz cannot read from owfs to retrieve sensor values. It works from command line, so it must be a problem related to the onewire implementation in Domoticz? 
A restart of the onewire hardware device in Domoticz usually fixes the problem, until next time it fails to read sensor values. If does not work I must restart my raspberry PI.

Another related issue is that when restarting Domoticz, Domoticz sometimes fails to start until owfs is restarted.

**Comment by gizmocuz** [comment]
Did you try with 3.1p1 ?

**Comment by Erik-NA** [comment]
Same thing with owfs 3.1p1 as with 3.0p2 on Domoticz v2.4439. 
Currently Domoticz cannot read any values from DS2438-based sensors on both versions. (Sensor type 26 in owfs) Temperature devices (type 28) are working.

**Comment by gizmocuz** [comment]
Did domoticz support type 26 in the first place ? (sorry i am not the author of the 1wire class)

**Comment by szczukot** [comment]
I see, that this device is supported by 1wire (DS2438 is Smart Battery Monitor).
Erik-NA: please give me info about : 
ls /mnt/1wire/uncached/26.xxxxxxxxxxx

**Comment by Erik-NA** [comment]
In Domoticz the sensors was last seen 2016-02-03. I do not know which Domoticz version, but I update daily if there is a update available.
what kind of information? For some reason I cannot attach a zip file to this issue :(

**Comment by Erik-NA** [comment]
[DS2438.zip](https://github.com/domoticz/domoticz/files/128158/DS2438.zip)
Yes, here it is!

**Comment by Erik-NA** [comment]
Here is one uncached: 
[uncached.zip](https://github.com/domoticz/domoticz/files/128273/uncached.zip)

**Comment by szczukot** [comment]
Did You try set verbose to 1 ? (./domoticz -verbose 1)
Pls set it and show log.

**Comment by Erik-NA** [comment]
[domolog.txt](https://github.com/domoticz/domoticz/files/129258/domolog.txt)
Here is a log file using Domoticz V2.4552 with verbose set to 1

**Comment by szczukot** [comment]
Do you see on this list your device type 26 ?

**Comment by Erik-NA** [comment]
Could this have something to do with the log entry "Error: 1-Wire : Device family (ef) is not actually supported" regarding 1wire? EF is a 1wire hub.

**Comment by Erik-NA** [comment]
No, I have nothing about device type 26 in the log.

**Comment by szczukot** [comment]
But other devices, connected to hub do you see and they working ?

**Comment by szczukot** [comment]
Pls send me "LS" from all catalog /mnt/1wire.
Maybe this hub is show device not in main dir, but in subdir.

**Comment by Erik-NA** [comment]
All devices are connected to the hub actually. Temp sensors (id 28) works, but not humid/temp sensors (id 26)
[ls.txt](https://github.com/domoticz/domoticz/files/129659/ls.txt)
[ls2.txt](https://github.com/domoticz/domoticz/files/129660/ls2.txt)

**Comment by Erik-NA** [comment]
Some months ago, I wrote this lua script to check and control owfs in Domoticz. (In the script I have temporarily disabled owfs restart)
[script_time_owfs.txt](https://github.com/domoticz/domoticz/files/129686/script_time_owfs.txt)

**Comment by szczukot** [comment]
Ok. You see 3 devices with family code 26 in main directory.
I checked code, and it is looks properly :(
I will add some debug logs, compile under rpi and will send you for test

**Comment by Erik-NA** [comment]
OK, I will test it.

**Comment by gizmocuz** [comment]
There seem to be Humidity issues with 1-Wire after the patch currently?

http://www.domoticz.com/forum/viewtopic.php?f=6&t=10565&e=1&view=unread#unread

**Comment by tomaszszczukobls** [comment]
This problem is exists before.
In this post exists version 2.3530.
I trying to find bug in this code, but It looks ok.
I must add logs and users must show their result

**Comment by tomaszszczukobls** [comment]
Maybe this patch is created problem ??
https://github.com/domoticz/domoticz/commit/f0980c727a592c34a98fbba2aff477edfd6d3c48
It is very likely (99%).

**Comment by szczukot** [comment]
A few more logs: https://github.com/domoticz/domoticz/pull/489
Pls waiting for merge, run domoticz with "verbose 2" and show logs

**Comment by Erik-NA** [comment]
[domolog.txt](https://github.com/domoticz/domoticz/files/133296/domolog.txt)
Here is the log

Isn't the file path wrong?
Get Temperature from /mnt/1wire/26.802692010000/B1-R1-A =
Get Humidity from /mnt/1wire/26.802692010000/B1-R1-A =

Correct file path is
Get Temperature from /mnt/1wire/26.802692010000/temperature
Get Humidity from /mnt/1wire/26.802692010000/humidity

**Comment by szczukot** [comment]
I think so. I wrote about this : 2 post above.
For sure you do not have those directories?

**Comment by Erik-NA** [comment]
I have the directories, containing three text files, "gain", "offset" and "pressure"
Gain content = 21.7391
Offset content = 904.7
Pressure content = 971.657

 /mnt/1wire/26.802692010000/temperature content = 3.03125 (it is cold in my crawl basement...)
/mnt/1wire/26.802692010000/humidity content = 84.5606 (humidity is also high, but not yet too high. The purpose for this humidity and temp sensor is to control a dehumidifier in my crawl basement)

**Comment by szczukot** [comment]
Do You have in directory something like this 
/mnt/1wire/26.802692010000/B1-R1-A*
or
/mnt/1wire/26.802692010000/EDS*
?

**Comment by Erik-NA** [comment]
[ls.txt](https://github.com/domoticz/domoticz/files/133930/ls.txt)
Here is a file list

**Comment by szczukot** [comment]
Ok. I see that you have directory B1-R1-A
please show me "ls /mnt/1wire/26.802692010000/B1-R1-A"

**Comment by szczukot** [comment]
Ok. I see.
i trying fix this bug (but this is not my code and i dont have this sensor)

**Comment by szczukot** [comment]
It is my proposal :)
https://github.com/domoticz/domoticz/pull/492

**Comment by Erik-NA** [comment]
Using v2.4621. I have three sensors with id 26.  I can see in the log that Domoticz is fetching pressure three times, but no temp or humid values are fetched? Other temp sensors, id 28, are working.

**Comment by szczukot** [comment]
No. First domoticz is fetching data for temperature. Next to Volatge, pressure etc.
Pls check for new version of domoticz with this https://github.com/domoticz/domoticz/pull/492

**Comment by gizmocuz** [comment]
@szczukot, do you want me to merge/build a new beta, or is this not needed?

**Comment by szczukot** [comment]
pls merge and build.
A few people will can tested this fix

**Comment by gizmocuz** [comment]
new beta

**Comment by Erik-NA** [comment]
Using v2.4623. Humid values now works!! However, temperature is reported as zero degrees.

**Comment by Erik-NA** [comment]
I can see in the log that temp values from my three id 26 devices are handled, but the temperature is set to zero degrees.

**Comment by szczukot** [comment]
temperature from devices family 26 is still not work ?
pls show me new log with verbose 2

**Comment by Erik-NA** [comment]
[domolog.txt](https://github.com/domoticz/domoticz/files/134873/domolog.txt)
Log file attached

**Comment by szczukot** [comment]
pls show me:
cat /mnt/1wire/26.802692010000/temperature

**Comment by Erik-NA** [comment]
cat /mnt/1wire/26.802692010000/temperature
3.34375

**Comment by szczukot** [comment]
I don't have idea :(
In log i see : 
2016-02-17 18:49:37.698 1Wire (OWFS): Get Temperature from /mnt/1wire/26.802692010000 = 0
Thats is mean : i found this file ("temperature") and reading "0" from it.

Is other values from this sensor work (voltage, humidity etc) ?

**Comment by Erik-NA** [comment]
Strange!!

#service domoticz.sh stop
#cat /mnt/1wire/26.802692010000/temperature
3.0625
#service domoticz.sh start
2016-02-18 10:34:06.973  Domoticz V2.4633 (c)2012-2016 GizMoCuz
2016-02-18 10:34:06.975  Build Hash: cc4ebbc, Date: 2016-02-17 19:45:38
2016-02-18 10:34:06.976  System: Raspberry Pi
2016-02-18 10:34:06.978  Startup Path: /home/pi/domoticz/
domoticz: Domoticz is starting up....
#cat /mnt/1wire/26.802692010000/temperature
0

How to explain that?

**Comment by Erik-NA** [comment]
And look at this
#cat /mnt/1wire/26.802692010000/temperature
0
#cat /mnt/1wire/26.802692010000/temperature
0
#cat /mnt/1wire/26.802692010000/temperature
0
#cat /mnt/1wire/26.802692010000/temperature
0
#cat /mnt/1wire/26.802692010000/temperature
0
#cat /mnt/1wire/26.802692010000/temperature
3.15625
#cat /mnt/1wire/26.802692010000/temperature
3.15625
#cat /mnt/1wire/26.802692010000/temperature
3.15625
#cat /mnt/1wire/26.802692010000/temperature
3.15625
#cat /mnt/1wire/26.802692010000/temperature
0
#cat /mnt/1wire/26.802692010000/temperature
0
#cat /mnt/1wire/26.802692010000/temperature
0

**Comment by Erik-NA** [comment]
Is this maybe a 1wire owfs issue?

**Comment by szczukot** [comment]
Can You check one thing : diconnect all sensor, and connect only one (family 26) ?

**Comment by Erik-NA** [comment]
Have briefly investigated this. It works when two DS2438 are connected (one DS2438 on each port on the hub. The hub is separately powered). It does not work when three DS2438 are connected.I will investigate it more thoroughly this weekend.

**Comment by szczukot** [comment]
Ok. Please check another situation:
Only one DS2438 and a few other (DS18B20 etc)

**Comment by Erik-NA** [comment]
I have three branches connected to the hub. All three branches has one DS2438 and at least one temperature sensor.  However I choose to connect, two branches works without any problems. When the third is connected, the temperature from all DS2438 are set to zero degrees mostly. Sometimes they can preset correct temperature in about ten seconds, and then turn to zero degrees.

When reading temperature from console, from OWFS, it is the other way around - mostly correct temperature is read.

One earlier observation is that sometimes I cannot restart Domoticz without first restarting OWFS. Domoticz fails to start when this happens.

I do not know if this is a Domoticz or an OWFS issue?

**Comment by szczukot** [comment]
I think, that problem is hub from hooby board :( Maybe they incorretly support Skip Rom command.
I will change one thing in code (i sent skip rom command when number of devices is more than 3). This is not very good solution, but we check is it the problem.

**Comment by gizmocuz** [comment]
that is why in the previous version we used the 'cached' version, i think this should not give zero ?

**Comment by tomaszszczukobls** [comment]
Erik-NA
Please check
cat /mnt/1wire/unchached/26.802692010000/temperature
but you must test it long time.
This catalog refreshed default after ever 15 sec

**Comment by Erik-NA** [comment]
If I run cat /26.802692010000/temperature until it reports zero degrees, which it does a number of seconds, and then running  cat uncached/26.802692010000/temperature, the latter shows correct value.
Running Domoticz v2.4790 simultaneously

**Comment by Erik-NA** [comment]
# cat 26.802692010000/temperature

4.125root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.125root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.125root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.125root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.125root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.125root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.125root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat 26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat 26.802692010000/temperature
0root@pi:/mnt/1wire# cat 26.802692010000/temperature
0root@pi:/mnt/1wire# cat 26.802692010000/temperature
0root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.12525root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.09375^[[Aroot@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.15625^[[Aroot@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.21875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.12575root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.21875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.21875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.12555root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.21875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.09375root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.18755^[[Aroot@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.21875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.09375root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.25625^[[Aroot@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.21875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.25625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.125root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.1255root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.0625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.09375root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.21875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.21875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.18755root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.125root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.125root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.18755root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.25625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.09375root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.21875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.21875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.21875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.15625root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.18755root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.09375root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature
4.1875root@pi:/mnt/1wire# cat uncached/26.802692010000/temperature

**Comment by gizmocuz** [comment]
We used to use the uncached previously, someone changed this... dont know why, but he/she had probably a good reason to do so ....

I think in the header file "1WireByOWDS.h" you can change at the top 

#define OWFS_Base_Dir "/mnt/1wire"

to

#define OWFS_Base_Dir "/mnt/1wire/uncached"

Maybe it is worth a try to see if this solves all the problems ?

**Comment by szczukot** [comment]
I have a few ideas to solve this problem. I will do some fix.
