### ISSUE TITLE
AirconWithMe implementation

### ISSUE THREAD

**Issue by RDols** [domoticz/domoticz#4301]
@gizmocuz 
Recently i had two airco units installed. These are equiped with an AirconWithMe wifi module. There are some scripts available, but doens't do the job for me. And some requests on the forum. It has a (relativly) well documented local web interface. 

I implemented this in my (local) fork as a hardware type. After a little clealup of the code i would like to create a pull request for this.

**Comment by gizmocuz** [comment]
Great ! Hoping for more sunny days here ;)

**Comment by RDols** [comment]
@gizmocuz 

I could be there is a simular request for this: #4193 
Depending on the outcome there if it's indeed the same, and if the WMP protocol implementation is better i will create a pull request, or change it (e.g. renamening it to "Intesis Airco Control".

**Comment by LarsenDX** [comment]
@RDols Thank you! I have AirconWithMe devices attached to my Mitsubishi Heavy (MHI) AC in the house. I can help test the code. Is a pull request planned for this? About WMP, as far as I can tell, AirConWithMe devices only offer the JSON API (HTTP port 80) and do not implement the WMP protocol. I port scanned my devices and only find port 80 to be open.

**Comment by RDols** [comment]
@LarsenDX There will be a PR. Don't known when. It's hanging on 4 minor points:
1. Simularity with Intesis devices. (by now i known that they are not the same, so this bullet point can be checked.
2. need to fix a minor issue with the configuration. 
3. Want to look if its possible to add default values for for new devies (username and password)
4. Me. I'm a little limited in time.

Code is a branch on my account, but you need to compile it yourself.

**Comment by LarsenDX** [comment]
@RDols Good stuff. I'll check out your branch and give it a spin.

**Comment by LarsenDX** [comment]
>     1. Simularity with Intesis devices. (by now i known that they are not the same, so this bullet point can be checked.
Does your code not account for that by calling and parsing the result of getavailabledatapoints?

**Comment by RDols** [comment]
The getavailabledatapoints is called once (for every instance). The description is hard coded though. I'm not using "http://IpAddress/js/data/data.json" for that. I found this call just recently, and would not add much. 

It looks like the Intesis Wifi modules have the HTTP port blocked. And the Intesis WMP modules don't support this API at all.

**Comment by LarsenDX** [comment]
Sure. I read through vendor comments in #4193. Looks to me like it makes sense to have 3 different hardwares in domo.
Intesishome, WMP and AirconWithMe. (I didn't realize that AirconWithMe is only supported by MHI).

**Comment by wouterlet** [comment]
Hi RDols,

I just updated my domoticz to 2021.1. This includes your Airconwithme plugin if I'm right. I tried to connect them but it doesn't seem to work? Probably I'm doing something wrong. However there not much to do wrong. I filled in the IPadress of the Airco (192.168.1.102 (fixed adress by my router)) and filled in the username/password I filled in the the Airconwithme App. In my domoticz log I get the following:

2021-04-24 12:56:46.030 Error: Airco Huiskamer: Login failed : request failed!
2021-04-24 12:56:46.030 Error: Airco Huiskamer: GetAvailableDataPoints failed :

And off course no devices are added in my devices list.

What am I doing wrong? Hope you can help!

**Comment by LarsenDX** [comment]
Hi,

Credentials are probably not correct. Try operator / operator.

Regards,
LarsenDX

**Comment by wouterlet** [comment]
Thanks that was the trick!

**Comment by LarsenDX** [comment]
@gizmocuz This can be closed. Thanks.
