### ISSUE TITLE
Error in log about "inactivation delay" : wrong time unit

### ISSUE THREAD

**Issue by loldrine** [domoticz/domoticz#4308]
Used version : beta @ 866265e2a49436e05276a576cef38a3be9bceb92

When a hardware is set with inactivation delay using delay=24 hours, when timeout is reached the log displays:
xxx hardware (x) nothing received for more than 1440 Days!....

The right value must be "1 Day" instead of "1440 Days".

The issue comes from main/mainworker.cpp, line 13530:
       totNum = pHardware->m_DataTimeout / 60;

m_DataTimeout must be divided by 60*60*24=1440 and not by 60 only to have a result in day(s)

Thanks for the code fix

**Comment by rwaaren** [comment]
> When a hardware is set with inactivation delay using delay=24 hours, when timeout is reached the log displays:
> xxx hardware (x) nothing received for more than 1440 Days!....
> 
> m_DataTimeout must be divided by 60_60_24=1440 and not by 60 only to have a result in day(s)

Thx for reporting. Fixed in build 12281;  divider set to 86400 ( 24 * 60 * 60)

**Comment by loldrine** [comment]
Tested OK.
Thanks
