### ISSUE TITLE
Extra command from nowhere 

### ISSUE THREAD

**Issue by PeterBoomhut** [domoticz/domoticz#4309]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

Raspberry Pi 3b , Domoticz version 2020.2
I've been "programming in Blockly" by pushing a button on the remote, an event in blockly does switching an number of lights off. Strange enough , the last light is switching on, but that's not what in the event is written.

![Screenshot_2020-08-29 Domoticz](https://user-images.githubusercontent.com/69416350/91655115-b7f95000-eaae-11ea-8b78-786d7d6cdd8c.png)
The switch Keuken is programmed to go off, but something is switching him back on?

![Resultaat Blockly](https://user-images.githubusercontent.com/69416350/91655138-e840ee80-eaae-11ea-9969-3d0b16154682.png)

This the logs from each light.

On the forum i'had no results,
Peter Rozenveld

**Comment by rwaaren** [comment]
You did not answer my questions on the forum. This is clearly not a code bug
