### ISSUE TITLE
SolarEdgeAPI should try reading missing consecutive datapoints

### ISSUE THREAD

**Issue by michahagg** [domoticz/domoticz#4319]
The SolarEdgeAPI worker collects from the Monitoring API the latest power and energy produced by the SolarEdge inverter. It does that every 5 minutes. Each time, it collects data from the past 10 minutes. Mostly this results in 1 datapoint: the one from the first 5 minutes. Sometimes even that datapoint becomes available past 10 minutes.

A solution might be to have SolarEdgeAPI record which datapoints are missing. Then have it keep trying to read them and record them at the right timestamp. Any ideas?

To create a correct graph of the SolarEdge inverter power, SolarEdgeAPI must be able to record datapoints in the past. Using SendKwhMeter() this is not possible. Is there a way to record datapoints in the past?

Furthermore, if SolarEdgeAPI is to store datapoints in the Meter/Meter_Calendar tables by itself, would it make sense to record the datapoints with their original timestamps? Now each datapoint is recorded exactly at a whole number of 5-minute intervals.

Thanks in advance.

**Comment by gizmocuz** [comment]
@michahagg , you have to use SendKwhMeter so all underlying architecture will work.
But it does not make sense that when we poll every 5 minutes we align the timestamps... it's accurate enough
Or we should poll every minute, which is not allowed as there is a rate limit of 300 calls per day
There is a very small change we get the same reading, and even if this happens this will be corrected at the next call
Previous tests with requesting the measurements from 5 minutes ago resulted in no results.
I'm leaving this as it is right now

**Comment by michahagg** [comment]
@gizmocuz Thanks for looking into my issue. You're right about following the architecture, of course. Still I think the graph should not be 5 minutes behind reality. I'll stick with what it is now.
:-)
