### ISSUE TITLE
Synology compile error. eVehicles/eVehicle.cpp

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#4323]
[100%] Building CXX object CMakeFiles/domoticz.dir/tinyxpath/xpath_syntax.cpp.o
[100%] Linking CXX executable domoticz
CMakeFiles/domoticz.dir/hardware/eVehicles/eVehicle.cpp.o: In function `CeVehicle::CeVehicle(int, CeVehicle::eVehicleType, std::string const&, std::string const&, int, int, bool, std::string const&)':
eVehicle.cpp:(.text+0x25eb): undefined reference to `CMercApi::CMercApi(std::string, std::string, std::string)'
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:4268: recipe for target 'domoticz' failed
make[5]: *** [domoticz] Error 1
make[5]: Leaving directory '/home/dahl/spksrc-master/spk/domoticz_python/work-cedarview-6.2/domoticz-r12337'
CMakeFiles/Makefile2:371: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[4]: *** [CMakeFiles/domoticz.dir/all] Error 2
make[4]: Leaving directory '/home/dahl/spksrc-master/spk/domoticz_python/work-cedarview-6.2/domoticz-r12337'
Makefile:168: recipe for target 'all' failed
make[3]: *** [all] Error 2

**Comment by gizmocuz** [comment]
@Jumbotroll , Not sure what the compile issue could be....
It compiles here fine under Windows/Linux, is your CMakeProject file also updated ?
Maybe clear the CMake Cache folder and cache file ?

(Edited: Corrected spelling typo)

**Comment by Jumbotroll** [comment]
> @Jumbotroll , Not sure what the compile issue could be....
> It compiles here fine under Windows/Linux, is your CMakeProject file also updated ?
> Make clear the CMake Cache folder and cache file ?

Thanks!
I will take a closer look :-)

**Comment by Jumbotroll** [comment]
Fixed..
