### ISSUE TITLE
Some recent update to beta-line makes plugin crash server

### ISSUE THREAD

**Issue by frontfoto** [domoticz/domoticz#4328]
Server: Ubuntu Linux
Version of domoticz: 2020.2 (build 12377)

Had trouble since updating. Some earlier build broke something with plugin Tahoma/Conexoon plugin for IO blinds. The plugin seems to work with the stable version 2020.2 without crashes. It crashes a disconnects the plugin and when trying to update it crashes. More info https://domoticz.com/forum/viewtopic.php?f=6&t=33874

**Comment by gizmocuz** [comment]
@frontfoto , Are you sure it is 'this' commit that caused it not to work ?
Could you checkout a previous build ?
You talk about Python plugins, but the commit you are referring to has nothing to do about this, have you checked the files changed by that PR ?

**Comment by frontfoto** [comment]
No I'm not really sure about the commit. But focused on something that has been changed recently that was more general. I haven't got any devices connected to the other commits. My skills are limited in debug. :( Sadly I haven't got a hard line where the trouble started. The plugin seems to run fine under the stable one and I had it running i some earlier beta. Any suggestion how I can continue on debug road?

**Comment by gizmocuz** [comment]
Yes, you can checkout any 'commit' you want, from 2020.2 till the most recent commits

`git checkout <commit-id>`

like

`git checkout c42fecf84a88b897dd30b502fe6f9af3457a1bf8`

will checkout

`https://github.com/domoticz/domoticz/commit/c42fecf84a88b897dd30b502fe6f9af3457a1bf8`

**Comment by frontfoto** [comment]
Looking further in this. Updated to latest commit and now it hasn't crashed since 1 h 26 min. Will see it's connected to time.

**Comment by frontfoto** [comment]
Tried the stable release and had no crashes. I guess if I take out commits from github I need to compile as well? Or does it exist old zip with earlier commits?

**Comment by frontfoto** [comment]
The plugin has been confirmed working in build. 12313 since the plugin maker runs that version. So something between 12313 and recent version conflicts with the plugin or at least making the plugin misbehave.

**Comment by frontfoto** [comment]
So between 12338 and 12313 something changed. My guess is that it's connected to build 12332 but haven't got a version before this. To much of newbie to compile after git checkout. Which I suspect I need to do.

**Comment by gizmocuz** [comment]
@frontfoto , if you follow this guide:

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

and use the above git checkout method to checkout a specific build, you should find a domoticz binary in your build/bin folder

**Comment by frontfoto** [comment]
thank u @gizmocuz, I managed to checkout a version and compile it. So now it's running to see if I can manage to catch some more info. But when I try to make a new checkout and compile to the same library I don't get the new version. Do I have to empty my folder before and making a new git pull or perhaps a fetch?

**Comment by gizmocuz** [comment]
You should see the final build binary in the 'bin' folder
did you issue a 'make' command after checking out?
In the extreme condition, you can delete the CMakeFiles folder and the CMakeCache.txt file and issue again

cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt

if you experience a crache, try to build in 'Debug' mode:

cmake -DCMAKE_BUILD_TYPE=Debug CMakeLists.txt

Most times you get more debug information with this during a crash

**Comment by rwaaren** [comment]
@frontfoto 

any progress on this ?

**Comment by frontfoto** [comment]
Tried a lot of but did not manage to solve which version that changed the game plan. But the devoloper seems to managed to work around and had his plugin working and since then no more strange crashes from sny of those plugins. Thanks for your effort in helping me.
