### ISSUE TITLE
Zwave node not identified after latest beta update

### ISSUE THREAD

**Issue by AlexF12004Roma** [domoticz/domoticz#4329]
Domoticz 2020.2 build 12340
on Raspberry

after the upgrade to the lastest beta some nodes description manufacturer, id and type not shown anymore and not working

![image](https://user-images.githubusercontent.com/6578842/92415005-3ca33880-f157-11ea-9403-b9da0e8e6f81.png)

**Comment by AlexF12004Roma** [comment]
Tried to restore a database backup but domoticz crash on startup.
The only solution would be a backup with a previous beta release but i cannot find a repo where download past beta releases.

**Comment by gizmocuz** [comment]
@AlexF12004Roma , What version dit you run before ?
Have you tried selecting the node and hit the button 'Refresh Node Info' ?
If they are battery operated, could you wake up the node first before requesting the node information ?

**Comment by AlexF12004Roma** [comment]
Hi @gizmocuz ! Thanks for the reply.
Wakeup and refresh node info trick works! I try for 2 nodes. Now i will do for all.

I did not updated beta from April, more or less.
In database i cannot see version

![image](https://user-images.githubusercontent.com/6578842/92440496-e95bd500-f1ac-11ea-9052-3798499abdd8.png)

**Comment by AlexF12004Roma** [comment]
Some problems with some nodes that with this procedure makes domoticz crash:

 2020-09-08 08:40:31.532 Error: Domoticz(pid:23030, tid:23078('OZW-driver')) received fatal signal 11 (Segmentation fault)
2020-09-08 08:40:31.532 Error: siginfo address=0x220, address=0x827c88

**Comment by gizmocuz** [comment]
What type of node does this? Is this always, or when you try again it works?

**Comment by AlexF12004Roma** [comment]
After some retries seems to works.

**Comment by michahagg** [comment]
Keep a working copy of domoticz/Config/ozwcache_*.xml handy. Domoticz occassionally looses the device entries. It saves you a lot of work if you can just replace the empty xml-file with one with all the devices present.

**Comment by AlexF12004Roma** [comment]
OK! Thanks a lot!

**Comment by AlexF12004Roma** [comment]
Just a suggestion, maybe a copy(backup) step of the file in the update sh file could be useful
