### ISSUE TITLE
Annatherm presets have changed in latest beta.  Stable and older beta's need  to be migrated properly

### ISSUE THREAD

**Issue by p-hagen** [domoticz/domoticz#4335]
Issue exist since latest update to Annatherm: august  31th -commit cca10cd218e9cefc01a10f8f201aee5a115a6b24 
To resolve this I've written code that allows you to check and  migrate  the Names and actions of a selector switch.
and provided it in a helper functions  I've raised a PR for this  https://github.com/domoticz/domoticz/pull/4327

Als as requested by @gizmocuz I've also made a generic Create/update helper function for selector switches simulair liek SendSwitch.

Can someone review? if not  wanted as generic functions, I willl port back the functionality to be only in the Annatherm plugin

**Comment by gizmocuz** [comment]
There is no need to create a new issue
