### ISSUE TITLE
Tado New Feature: Open Window Detection

### ISSUE THREAD

**Issue by LarsenDX** [domoticz/domoticz#4336]
This issue tracks the addition of the feature Open Window Detection to domoticz/hardware/Tado. 

The Tado Smart Thermostat can detect an open window in a zone and alert the user. The Domoticz Tado hardware, at start-up, checks each zone and records if the zone supports Open Window Detection. For each supported zone a new switch is created. ex:  Home Kitchen Open Window Detected. 
The switch gets pulled high when the API reports an open window. The switch get pulled low when the API no longer reports an open window. This is a read-only switch.

**Comment by gizmocuz** [comment]
@LarsenDX , thank you for the PR. It's been merged!
