### ISSUE TITLE
Support rtl 433 flex spec triggers

### ISSUE THREAD

**Issue by mzealey** [domoticz/domoticz#4338]
The flex spec of rtl 433 can be used to output some very limited triggers when, for example a doorbell is pressed:

```
time,msg,codes,protocol,mod,freq,freq1,freq2,rssi,snr,noise,model,id,temperature_C,humidity,battery_ok,status,brand,channel,rain_rate,rain_rate_mm_h,rain_total,rain_mm,gust,average,direction,wind_max_m_s,wind_avg_m_s,wind_dir_deg,pressure_hPa,uv,power_W,energy_kWh,radio_clock,unit,group_call,command,dim,dim_value,wind_speed,wind_gust,wind_direction,wind_avg_km_h,wind_max_km_h,mic,dipswitch,rbutton,device,button,setpoint_C,switch,cmd,cmd_id,tristate,direction_deg,speed,rain,msg_type,signal,sensor_code,uv_status,uv_index,lux,wm,seq,rainfall_mm,wind_speed_ms,gust_speed_ms,current,interval,learn,sensor_id,battery_low,sequence_num,message_type,wind_speed_mph,wind_speed_kph,rain_inch,rc,gust_speed_mph,wind_approach,flags,maybetemp,binding_countdown,depth,depth_cm,dev_id,sensor_type,subtype,power0,power1,power2,node,ct1,ct2,ct3,ct4,Vrms/batt,batt_Vrms,temp1_C,temp2_C,temp3_C,temp4_C,temp5_C,temp6_C,pulse,address,button1,button2,button3,button4,data,sid,state,group,transmit,moisture,type,pressure_kPa,battery_mV,pulses,energy,len,to,from,payload,event,heartbeat,temperature1_C,temperature2_C,temperature_1_C,temperature_2_C,test,probe,water,humidity_1,ptemperature_C,phumidity,newbattery,heating,heating_temp,uvi,light_lux,pm2_5_ug_m3,pm10_0_ug_m3,counter,code,alarm,repeat,maybe_battery,device_type,raw_message,switch1,switch2,switch3,switch4,switch5,extradata,house_id,module_id,sensor_count,alarms,sensor_value,battery_voltage,rid,failed,class,alert,secret_knock,relay,wind_dev_deg,exposure_mins,transmit_s,button_id,button_name,encrypted,misc,count,num_rows,rows
2020-09-10 20:29:36.862081,,{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048;{21}a78048,,ASK,433.947,,,-0.111,15.970,-16.080,Byron_BY_Doorbell,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,25,25,;;;;;;;;;;;;;;;;;;;;;;;;
```

Presently rtl 433 outputs are ignored if no obvious fields are found per https://github.com/domoticz/domoticz/blob/ec4c55d4a88fafce60efe106cb59b198ea6c9eab/hardware/Rtl433.cpp#L520 . However it would be good to register the device if the model has been specified and send a trigger so that we can capture stuff like flex spec doorbell pushes above.

**Comment by gizmocuz** [comment]
@mzealey , No I think we covered almost all possible fields here.
Don't know what a 'flex spec doorbell' is... but your output is not JSon, if you posted a JSon output we could have a look to see how we can implement this
Also for < $10 you have a good 433Mhz doorbell that 'just works'

**Comment by mzealey** [comment]
Ah sorry thought it was still doing csv parsing. I've managed to get the JSON output to something like:

```
{"time" : "2020-09-10 21:38:36.088911", "model" : "Byron_BY_Doorbell", "count" : 25, "num_rows" : 25, "len" : 21, "data" : "a78078", "id" : "4321", "command" : "On", "mod" : "ASK", "freq" : 433.906, "rssi" : -0.785, "snr" : 14.857, "noise" : -15.641}
```

with the following flex config spec:

```
decoder n=Byron_BY_Doorbell,m=OOK_PWM,s=500,l=1000,r=3300,g=1200,repeats>=4,bits=21,match={16}0x1234,unique,get=@0:{1}:id:[0:4321 1:4321],get=@0:{1}:command:[0:On 1:On]
```

I can control what the command is but I can't see any way to provide a doorbell command per #4339

**Comment by gizmocuz** [comment]
I need to test this... Instead of calling SendSwitch for doorbells we should call SendSwitchUnchecked, but only for doorbells and scene devices as sometimes a multiple of the same command is received from RTL433

**Comment by mzealey** [comment]
Yes perhaps unchecked but not multiple times within a couple of seconds window? rtl 433 seems to be good at detecting and merging duplicate rows now for most of my devices

**Comment by gizmocuz** [comment]
@mzealey , could you give me your complete rtl433 command line for the Byron-BY ? Got the same doorbell here so should be easy to test

**Comment by mzealey** [comment]
I'm putting the following into /etc/rtl_433/rtl_433.conf; i think you can pass it with -X on cmdline as well if you want.

```
decoder n=Byron_BY_Doorbell,m=OOK_PWM,s=500,l=1000,r=3300,g=1200,repeats>=4,bits=21,match={2}0x3,unique,get=@0:{16}:id,get=@0:{1}:command:[0:On 1:On]
```

The last bit specifies the command; get before that should pass the id straight into domoticz but I've not fully tested it yet.

**Comment by gizmocuz** [comment]
@mzealey , thanks! Yes i tried that but (using the commandline) i received an error, maybe it needs the keyword 'spec' somewhere
I don't have a /etc/rtl_433/rtl_433.conf ...

**Comment by mzealey** [comment]
I would have thought `-X 'n=Byron_BY_Doorbell,m=OOK_PWM,s=500,l=1000,r=3300,g=1200,repeats>=4,bits=21,match={2}0x3,unique,get=@0:{16}:id,get=@0:{1}:command:[0:On 1:On]'` should work, otherwise if you create that conf file and just toss the line above in it then it should automatically use it. You need to be on a reasonably recent rtl_433 (< 1 year old) I think.

**Comment by gizmocuz** [comment]
That works... above the line started with decoder n=Byron_BY_Doorbell....

**Comment by mzealey** [comment]
yup the `decoder ` bit is for the conf file i guess in place of -X

**Comment by gizmocuz** [comment]
But... nothing is received... (It is with a RFXCom RFXTRX433-E)
You could changing the SendSwitch call with the Unchecked...

**Comment by mzealey** [comment]
For me it registers the device in domoticz but then never returns other presses so I'm pretty sure the Unchecked will work correctly.

**Comment by mzealey** [comment]
@gizmocuz can you change the source to Unchecked, that will certainly fix my issues.
