### ISSUE TITLE
Ability to send a doorbell command via rtl433

### ISSUE THREAD

**Issue by mzealey** [domoticz/domoticz#4339]
https://github.com/domoticz/domoticz/blob/a732966941b341b90d4b0c5c1c51f7558965612f/hardware/Rtl433.cpp#L305 only allows off/on commands. However a doorbell only ever reports pushes. But `SendSwitch` ignores changes if the on/off value has not changed so it is impossible to hook up a doorbell via this method

**Comment by gizmocuz** [comment]
Please do not make multiple issues
