### ISSUE TITLE
Latest beta rtl 433 crashes frequently - issue with nested JSON outputs?

### ISSUE THREAD

**Issue by mzealey** [domoticz/domoticz#4340]
2020.2 works fine. latest beta crashes every 5-15 minutes. 
[Here is the crash log](https://github.com/domoticz/domoticz/files/5207506/domoticz_crash.log)

**Comment by mzealey** [comment]
OK I captured the console crash output:

```
terminate called after throwing an instance of 'Json::LogicError'
  what():  Type is not convertible to string
2020-09-11 09:18:50.469  Error: Domoticz(pid:4658, tid:4686('RTL433')) received fatal signal 6 (Aborted)
2020-09-11 09:18:50.469  Error: siginfo address=0x1232, address=0xffffffff
```

I'm guessing the new JSON parsing (https://github.com/domoticz/domoticz/blob/a732966941b341b90d4b0c5c1c51f7558965612f/hardware/Rtl433.cpp#L84 ?) should be wrapped in an exception handler to output this as an error.

The line causing the issue (captured by strace) would appear to be:

```
{\"time\" : \"2020-09-11 09:32:01.485343\", \"enabled\" : 103, \"frames\" : {\"count\" : 15, \"fsk\" : 0, \"events\" : 15}, \"stats\" : [{\"device\" : 12, \"name\" : \"Oregon Scientific Weather Sensor\", \"events\" : 30, \"ok\" : 30, \"messages\" : 30}]}
```

So nested json causing the crash?

**Comment by mzealey** [comment]
```
{\"time\" : \"2020-09-11 10:17:32.010916\", \"enabled\" : 102, \"frames\" : {\"count\" : 21, \"fsk\" : 1, \"events\" : 1}, \"stats\" : [{\"device\" : 43, \"name\" : \"Watchman Sonic / Apollo Ultrasonic / Beckett Rocket oil tank monitor\", \"events\" : 1, \"ok\" : 1, \"messages\" : 1}]}\n{\"time\" : \"2020-09-11 10:17:32.010916\", \"enabled\" : 102, \"frames\" : {\"count\" : 21, \"fsk\" : 1, \"events\" : 1}, \"stats\" : [{\"device\" : 43, \"name\" : \"Watchman Sonic / Apollo Ultrasonic / Beckett Rocket oil tank monitor\", \"events\" : 1, \"ok\" : 1, \"messages\" : 1}]}\n
```

as well

**Comment by gizmocuz** [comment]
Crash has been solved in latest commit.
This was causes because Frames and Stats are a Object/Array

**Comment by gizmocuz** [comment]
(New beta available within the hour (12355)

**Comment by mzealey** [comment]
I can work around this by disabling the `report_meta stats` and `protocol` lines in /etc/rtl_433/rtl_433.conf - they were enabled by default and it seems to be mostly them that were triggering this error.

Now have installed the 12355 beta no crashes for a while looks to have fixed the issue thanks

**Comment by mzealey** [comment]
These or similar crashes are still an issue in latest release/build of domoticz against rtl 433 master branch. Disabling some of the `report_meta` is workaround.

**Comment by gizmocuz** [comment]
This is a very old thread. Could you display the received data that is causing it to crash ?
