### ISSUE TITLE
Domoticz remote not sending some sensors to the master?

### ISSUE THREAD

**Issue by mzealey** [domoticz/domoticz#4345]
I have a remote domoticz reading the following data from mysensors:

![image](https://user-images.githubusercontent.com/6083471/93023612-d0ae4d80-f5f8-11ea-80c1-ad756718b89f.png)

The other hardware (1wire, generic gpio) is getting sent to the master fine, but this mysensor / kwh data is not being sent properly. I see the following in master logs:

```
2020-09-13 17:39:42.808 (Pi Pool House) General/kWh (Unknown)
2020-09-13 17:39:42.816 (Pi Pool House) General/kWh (Unknown)
2020-09-13 17:39:42.823 (Pi Pool House) General/kWh (Unknown)
2020-09-13 17:39:42.832 (Pi Pool House) General/kWh (Unknown)
2020-09-13 17:39:42.840 (Pi Pool House) General/kWh (Unknown)
2020-09-13 17:39:42.849 (Pi Pool House) General/kWh (Unknown)
```

and the following in the devices list:

![image](https://user-images.githubusercontent.com/6083471/93023647-06ebcd00-f5f9-11ea-80d3-80b4dae6b3c4.png)

Appears to be combining the 3 sensors into 1?

Master domoticz is latest beta, slave domoticz is 2020.2

**Comment by mzealey** [comment]
No ideas how to debug this further?

**Comment by pviolero** [comment]
I have a similar issue with some zigbee devices. It seems that the slave (where the zigbee devices are visible)  don't send the devices to the master when they are managed through a python plugin.

**Comment by pipiche38** [comment]
> I have a similar issue with some zigbee devices. It seems that the slave (where the zigbee devices are visible) don't send the devices to the master when they are managed through a python plugin.

this is linked to #2484 where I think Master/Slave are not supported when using the Python Framework which I beleive is your case as there is no native plugin for Zigbee.

**Comment by mzealey** [comment]
Any ideas about this?

**Comment by waltervl** [comment]
Perhaps try to set the master/remote relation for this device again? Perhaps something went wrong on 

 What is the hardware ID of the 1 wire from remote on the master?

You also can switch on debug logging, see troubleshooting wiki https://www.domoticz.com/wiki/Troubleshooting#Activate_logging_to_OS-file_.28with_or_without_debugging.29
