### ISSUE TITLE
building with USE_BUILTIN_MQTT set to false leads to inconsistency

### ISSUE THREAD

**Issue by gms1** [domoticz/domoticz#435]
an external "mosquittopp.h" is referenced during the compilation of "hardware/MQTT.cpp"
but instead of linking the corresponding "libmosquittopp.so", the internal "MQTT/mosquittopp.cpp" ( referencing the internal "MQTT/mosquittopp.h" ) gets compiled and linked ( using the external "libmosquitto" )

I will make a pull request... I think the existing use-flag "USE_BUILTIN_MQTT" should be used for both "libmosquitto" and "libmosquittopp". because of their strong dependency; do you agree?

**Comment by gizmocuz** [comment]
yes, thanks! Someone changed this recently

**Comment by gms1** [comment]
fixed by pull request #436
