### ISSUE TITLE
Open weather map

### ISSUE THREAD

**Issue by mojso** [domoticz/domoticz#4351]
open weather map plugin does not read rain data.  in the json file on the open weather map the amount of rain appears but in domoticz it is always zero

Json

`{"coord":{"lon":20.97,"lat":42.01},"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10d"}],"base":"stations","main":{"temp":289.92,"feels_like":291.09,"temp_min":288.15,"temp_max":291.15,"pressure":1015,"humidity":93},"visibility":10000,"wind":{"speed":0.97,"deg":356},"rain":{"1h":0.18},"clouds":{"all":75},"dt":1600405140,"sys":{"type":1,"id":7023,"country":"MK","sunrise":1600402775,"sunset":1600447254},"timezone":7200,"id":785082,"name":"Tetovo","cod":200}`

**Comment by rwaaren** [comment]
As per the issue guidelines:

Before opening a new issue, please review the following:
* Always state your version and hardware platform when reporting code related issues
* First try to update to the latest beta version
* Often we will require Log Files and Screenshots to help diagnose the issue.

Does the issue occur in the OWM hardware module ?

**Comment by mojso** [comment]
I am using Version: 2020.2 (build 12377). On raspberry pi 3b+  
yes in the OWM hardware module 

all other parameters work well (temperature, atmospheric pressure, wind, UV index .. etc) except the amount of rain and the switch - is it raining

![Screenshot_20200918-214757_Chrome](https://user-images.githubusercontent.com/8018149/93639662-aa721e80-f9f9-11ea-809b-8bf786ca1590.jpg)

Log from omw
`2020-09-19 00:19:14.239 (Vreme) General/Text (Weather Description)
2020-09-19 00:19:14.250 (Vreme) Temp + Humidity + Baro (TempHumBaro)
2020-09-19 00:19:14.259 (Vreme) Temp (Feel Temperature)
2020-09-19 00:19:14.267 (Vreme) Wind (Wind)
2020-09-19 00:19:14.276 (Vreme) UV (UV Index)
2020-09-19 00:19:14.291 (Vreme) General/Visibility (Visibility)
2020-09-19 00:19:14.299 (Vreme) General/Percentage (Clouds %)
2020-09-19 00:19:14.308 (Vreme) Rain (Rain (Snow))`

**Comment by rwaaren** [comment]
@kiddigital 
I can only compare data from [build 12234]( https://github.com/domoticz/domoticz/commit/d5da96f53) onwards but if I compare current rain from the OWM hardware module with the results from a dzVents script (using the same API call, API key and location ) for this period, I also see that where the dzVents script reports rain, the OWM hardware module reports 0.

Happy to provide more information.

**Comment by gizmocuz** [comment]
Thanks for reporting. Found the issue, it was caused by a re-declaration of the rain variable in a if/then clause.
This caused the actual rain variable to be always 0
Also did some cleaning up here

Should be fixed in beta 12390, which should be available within 1 or 2 hours

**Comment by kiddigital** [comment]
@mojso @rwaaren Thanks for catching this.

And @gizmocuz thanks for fixing this so quickly 😁
