### ISSUE TITLE
unable to start Domoticz after upgrade (missing libssl.so.1.1)

### ISSUE THREAD

**Issue by amita1974** [domoticz/domoticz#4354]
After performing upgrade (and also with Domoticz version 4.11803), I get connection error on the web browsing (domoticz web page shows ERR_CONNECTION_REFUSED) and when checking domoticz status using
sudo /etc/init.d/domoticz.sh status
I can see the error:
domoticz.sh[765]: /home/pi/domoticz/domoticz: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

I went back to version 4.11590 bu replacing the domoticz directory with the content of that directory, restart domoticz (sudo /etc/init.d/domoticz.sh stop, sudo /etc/init.d/domoticz.sh start), and refresh the GUI access, which seems to work OK.
Now sudo /etc/init.d/domoticz.sh status works fine and I get te web access back.

System information: Using RP3 model B v1.2
output of hostnamectl command:
```
hostnamectl
   Static hostname: raspPiJessiLight
         Icon name: computer
           Chassis: n/a
        Machine ID: 2e7311d7868244978f314762db251c8e
           Boot ID: 59f0a6f957dc47e1838a5ea5d935ee70
  Operating System: Raspbian GNU/Linux 8 (jessie)
            Kernel: Linux 4.9.35-v7+
      Architecture: arm
```

**Comment by Sneeuwtijger** [comment]
You do not state what version of Domoticz you are upgrading to - I suspect 2020 
But - you better first check the forum - https://www.domoticz.com/forum/viewtopic.php?f=6&t=31157&start=20
And I can give you the solution - you should upgrade to Buster from Jessie - read the forum topics
