### ISSUE TITLE
Unable to delete graph points with build 12392

### ISSUE THREAD

**Issue by TheReptile** [domoticz/domoticz#4356]
With the latest beta (12392) I cannot delete measured points anymore from the graphs.
I think this is related to commit https://github.com/domoticz/domoticz/commit/3034fcb3ef13fff155190b8e2a3b514126d12ec2

This is running on a RPI 3B with the latest rasbian.

The previous beta worked fine.
See the attached screen-capture, after confirming the delete, the points are not removed.

![graph](https://user-images.githubusercontent.com/22954131/93709997-40fe2700-fb43-11ea-9525-fdb247bbd143.gif)

**Comment by rwaaren** [comment]
@TheReptile

Do you see any message in the domoticz log?
What deviceType / devicesubSubType are you testing this on? I tried some types on my system but cannot replicatie the issue.
( same domoticz version / other hardware / OS )

**Comment by TheReptile** [comment]
@rwaaren No I don't see any message in the domoticz log.
This is the power usage graph of a NAS-WR01Z Power plug 12A+ using Razberry, the subtype is electric.
![image](https://user-images.githubusercontent.com/22954131/93752390-e32f1500-fbfe-11ea-9325-f46ee7216b29.png)

**Comment by rwaaren** [comment]
@TheReptile, @michahagg, 

After a restart and a browser cache refresh I now see the same. 
What happens on my system is that when I try to delete a datapoint, a different datapoint (with a timestamp of 2 hours earlier gets deleted)

**Comment by michahagg** [comment]
@TheReptile @rwaaren Sorry for the delayed reply. I think I know what causes the 2-hour offset between the point selected and the point deleted. I'll fix this shortly.

Thanks for testing and reporting!

**Comment by TheReptile** [comment]
Just tested the new beta, seems to work fine now, thanks @michahagg !
