### ISSUE TITLE
unexpected end of file in linux Beta tar 

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4358]
Updating using ./updatebeta results in problems. Because of corrupted tar? 
When updating from my own git clone update does work. 

On git files dzVents/runtime/HistoricalStorage.lua and dzVents/runtime/Utils.lua seem to be OK and complete.

`sudo wget -4 -O domoticz_beta.tgz --no-check-certificate "https://www.domoticz.com/download.php?channel=beta&type=release&system=linux&machine=x86_64"`
 
`sudo tar -tvf domoticz_beta.tgz
`

```
-rwxrwxr-x travis/travis     7166 2020-09-19 09:37 dzVents/runtime/misc/testdzVents.sh
-rw-rw-r-- travis/travis    12426 2020-09-19 09:37 dzVents/runtime/HistoricalStorage.lua

gzip: stdin: unexpected end of file
-rw-rw-r-- travis/travis     1243 2020-09-19 09:37 dzVents/runtime/Camera.lua
-rw-rw-r-- travis/travis     2400 2020-09-19 09:37 dzVents/runtime/dzVents.lua
-rw-rw-r-- travis/travis    14607 2020-09-19 09:37 dzVents/runtime/Utils.lua
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```
When downloading the file via Browser and try to open with 7zip I see a similar unexpected EOF message

**Comment by gizmocuz** [comment]
I see no issues here.... Downloaded it, unpacked the tgz, unpacked the tar... all happy

**Comment by rwaaren** [comment]
@gizmocuz 
issue was in 12392. 
12393 is OK again

Indeed; all happy... now 😆
