### ISSUE TITLE
Lost devices

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#4369]
Domoticz 2020.1
Synology 218+
DSM 6.2.3-25426 Update 2

Hi,

After pairing Aeotec Doorbell 6 

![Schermafbeelding Zwave nodes](https://user-images.githubusercontent.com/33230021/94844489-99c0a000-041e-11eb-9fad-4a4838617384.png)

All devices are not  reachable anymore

![Schermafbeelding Devices](https://user-images.githubusercontent.com/33230021/94845182-9e398880-041f-11eb-9d47-c9da68888291.png)

Is  there  a solution for this?

Joop.

**Comment by gizmocuz** [comment]
Please use our forum, a restart might help
