### ISSUE TITLE
Teleinfo USB partially broken

### ISSUE THREAD

**Issue by molusk** [domoticz/domoticz#437]
Teleinfo tile doesn't show usage anymore.
It worked flowlessly before but since I updated 1 hour ago it's broken.

Graph are still OK but caption on weekly histo only shows Usage 2 which is always equal to 0 in my case (my contract only has only one price and doesn't switch from Usage 1 to Usage 2).

![teleinfo casse](https://cloud.githubusercontent.com/assets/17114364/12876130/beae6578-cdfa-11e5-9b76-11d31910e2a7.PNG)

**Comment by molusk** [comment]
Erratum, week histogram are OK.
But it seems notifications are triggered but the value shown on the tile so I don't get notifications anymore.

**Comment by gizmocuz** [comment]
Please use our forum, also the teleinfo developers are there !
