### ISSUE TITLE
Wind / temp / chill device does not show devicelog for last 24 hours

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4373]
Seems related to ["Supported more sensors" commit](https://github.com/domoticz/domoticz/commit/12113bc63265fbf270e132939871884b30e6cc11
)

See screenshots in
[comment on commit ] ( https://github.com/domoticz/domoticz/commit/12113bc63265fbf270e132939871884b30e6cc11#comments)

Build 12442
Locally compiled
Debian on Intel NUC /  RPI4

Clearing cache and appcache and trying with other browser / incognito mode in Chrome does not solve it.

**Comment by Bartekn86** [comment]
same issue, not showing devicelog for last 24h, after last update i think

**Comment by rwaaren** [comment]
Thx for fixing!
Tested with build 12444 and all my sensors now show the correct devicelogs.
