### ISSUE TITLE
No add or update button on notification page

### ISSUE THREAD

**Issue by cronyx** [domoticz/domoticz#4376]
![photo_2020-10-03_18-46-22](https://user-images.githubusercontent.com/2557102/95020905-945d9280-0676-11eb-864b-0a98e98e47f8.jpg)

```
Version: 2020.2 (build 12450)
Build Hash: 3b9300eed-modified
Compile Date: 2020-10-04 11:31:05
dzVents Version: 3.0.14
Python Version: 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
```

**Comment by rwaaren** [comment]
@michahagg, I see the same behavior. Cleared browser and appcache without effect.
Could this be related to your recent PR's?

**Comment by gizmocuz** [comment]
@michahagg , I fixed this one, we might have to check all other pages for correct closing tags.
Sure this might feel a bit little irritant, but in the end we have better HTML code...
