### ISSUE TITLE
Missing today log of a temperature device

### ISSUE THREAD

**Issue by Olifant1990** [domoticz/domoticz#4377]
In version 12450 I am missing the day log of a temperature device.
It shows only month and year.
Maybe sinds a last few commits?
There are no errors in the console.

![afbeelding](https://user-images.githubusercontent.com/25199588/95046036-927de880-06e3-11eb-909f-807f1fc7a7f9.png)

**Comment by rwaaren** [comment]
> In version 12450 I am missing the day log of a temperature device.

I am on the same version but cannot replicate this behavior . I use the default theme and chrome browser. Could it be cache related?

![image](https://user-images.githubusercontent.com/24454798/95049545-3ec2cd80-06ea-11eb-95fd-780e72045280.png)

**Comment by Olifant1990** [comment]
Hmz, indeed.
When I load my Domoticz in a private session (still using Firefox), it is working.
Must be some cache problem indeed, will clear it and it must work again. Thanks!
