### ISSUE TITLE
Data timeout always restart plugin

### ISSUE THREAD

**Issue by dwhile** [domoticz/domoticz#4378]
I use the Hive plugin in domoticz. Setting the data timeout causes the plugin to restart after the timeout period irrespective of sensors that are updated.

The data timeout is currently set to 30 minutes. Here are the relevant lines from the log:

2020-10-05 15:17:35.235 (House) DomoticzVersion Available 2020.2
2020-10-05 15:26:50.090 Active notification Subsystems: browser, email (2/13)
2020-10-05 15:27:41.533 (X10) Light/Switch (Pool pump)
2020-10-05 15:27:47.364 (X10) Light/Switch (Pool pump)
2020-10-05 15:47:48.982 (House) Starting
2020-10-05 15:47:48.982 (House) DomoticzVersion Available 2020.2

As you can see the plugin is started at 15:17:35.235 and then again at 15:47:48.982 - 30 minutes later.

The attached file (devices.docx) show the devices recognised by the plugin and shows that the current temperature is updated regularly.
[devices.docx](https://github.com/domoticz/domoticz/files/5328153/devices.docx)

I would expect domoticz to recognise that the sensor has been updated and not restart the plugin.

**Comment by gizmocuz** [comment]
@dwhile , what is the 'Hive' plugin, is this a native Domoticz plugin, or a third party plugin ?
After a bit of googling I think you have to post this issue here:

https://github.com/imcfarla2003/domoticz-hive/issues

**Comment by dwhile** [comment]
No this is not a problem with the plugin but a problem with Domoticz. The plugin works fine - it retrieves the sensor data and updates the devices in Domoticz. It is just that Domoticz doesn't appear to recognise that the device has been updated and consequently restarts the plugin after the data timeout has expired.

**Comment by gizmocuz** [comment]
@dwhile , as this does not happen with the native plugins and with this specific plugin, I can only assume it is not a Domoticz issue.
Or this does not work with all Python plugins.
As this is the first time hear this, it is best to contact the plugin developer and have a look together

**Comment by dwhile** [comment]
I did wonder whether this is a problem for the python plugin system. I don't know whether any other python plugin has the same problem as I only have the one plugin loaded. 
I will try and create a "dummy" python plugin and see if it occurs with that.

**Comment by dwhile** [comment]
Ok
I have loaded the Denon/Marantz plugin from the examples directory (I happen to have a Denon receiver). The plugin works fine and finds the receiver and updates the devices in Domoticz.

I set the data timeout to 5 minutes and after 5 minutes I can confirm that the plugin restarts. I confirmed this by adding a logging line in the onStart routine and it prints out this message.

So the problem definitely appears to be in the handling of the python plugins in Domoticz and not in the plugin.

Oct  6 15:28:16 backup domoticz[90205]: 2020-10-06 15:28:16.548  (Test) Plugin starting.....
Oct  6 15:28:16 backup domoticz[90205]: 2020-10-06 15:28:16.549  (Test) Update 0:'Off' (Test - Power)
Oct  6 15:28:16 backup domoticz[90205]: 2020-10-06 15:28:16.549  (Test) Update 0:'0' (Test - Main Zone)
Oct  6 15:28:16 backup domoticz[90205]: 2020-10-06 15:28:16.550  (Test) Update 0:'52' (Test - Main Volume)
Oct  6 15:28:16 backup domoticz[90205]: 2020-10-06 15:28:16.551  (Test) Update 0:'0' (Test - Zone 2)
Oct  6 15:28:16 backup domoticz[90205]: 2020-10-06 15:28:16.551  (Test) Update 0:'40' (Test - Volume 2)
Oct  6 15:28:16 backup domoticz[90205]: 2020-10-06 15:28:16.602  (Test) Connected successfully to: 192.168.0.114:23
Oct  6 15:28:16 backup domoticz[90205]: 2020-10-06 15:28:16.656  (Test) Update 0:'Off' (Test - Power)
Oct  6 15:28:16 backup domoticz[90205]: 2020-10-06 15:28:16.661  (Test) Update 0:'0' (Test - Main Zone)
Oct  6 15:28:16 backup domoticz[90205]: 2020-10-06 15:28:16.665  (Test) Update 0:'52' (Test - Main Volume)
Oct  6 15:28:16 backup domoticz[90205]: 2020-10-06 15:28:16.669  (Test) Update 0:'0' (Test - Zone 2)
Oct  6 15:28:16 backup domoticz[90205]: 2020-10-06 15:28:16.672  (Test) Update 0:'40' (Test - Volume 2)
Oct  6 15:28:17 backup domoticz[90205]: 2020-10-06 15:28:17.129  (Test) Update 0:'Off' (Test - Power)
Oct  6 15:28:17 backup domoticz[90205]: 2020-10-06 15:28:17.131  (Test) Update 0:'0' (Test - Main Zone)
Oct  6 15:28:17 backup domoticz[90205]: 2020-10-06 15:28:17.132  (Test) Update 0:'52' (Test - Main Volume)
Oct  6 15:28:17 backup domoticz[90205]: 2020-10-06 15:28:17.132  (Test) Update 0:'0' (Test - Zone 2)
Oct  6 15:28:17 backup domoticz[90205]: 2020-10-06 15:28:17.133  (Test) Update 0:'40' (Test - Volume 2)
Oct  6 15:28:18 backup domoticz[90205]: 2020-10-06 15:28:18.141  (Test) Update 0:'Off' (Test - Power)
Oct  6 15:28:18 backup domoticz[90205]: 2020-10-06 15:28:18.143  (Test) Update 0:'0' (Test - Main Zone)
Oct  6 15:28:18 backup domoticz[90205]: 2020-10-06 15:28:18.144  (Test) Update 0:'52' (Test - Main Volume)
Oct  6 15:28:18 backup domoticz[90205]: 2020-10-06 15:28:18.144  (Test) Update 0:'0' (Test - Zone 2)
Oct  6 15:28:18 backup domoticz[90205]: 2020-10-06 15:28:18.145  (Test) Update 0:'40' (Test - Volume 2)
.
.
.
Oct  6 15:33:21 backup domoticz[90205]: 2020-10-06 15:33:21.497  (Test) Update 0:'0' (Test - Main Zone)
Oct  6 15:33:21 backup domoticz[90205]: 2020-10-06 15:33:21.501  (Test) Update 0:'52' (Test - Main Volume)
Oct  6 15:33:21 backup domoticz[90205]: 2020-10-06 15:33:21.504  (Test) Update 0:'0' (Test - Zone 2)
Oct  6 15:33:21 backup domoticz[90205]: 2020-10-06 15:33:21.507  (Test) Update 0:'40' (Test - Volume 2)
Oct  6 15:33:21 backup domoticz[90205]: 2020-10-06 15:33:21.683  (Test) Plugin starting.....
Oct  6 15:33:21 backup domoticz[90205]: 2020-10-06 15:33:21.684  (Test) Update 0:'Off' (Test - Power)
Oct  6 15:33:21 backup domoticz[90205]: 2020-10-06 15:33:21.685  (Test) Update 0:'0' (Test - Main Zone)
Oct  6 15:33:21 backup domoticz[90205]: 2020-10-06 15:33:21.686  (Test) Update 0:'52' (Test - Main Volume)
Oct  6 15:33:21 backup domoticz[90205]: 2020-10-06 15:33:21.687  (Test) Update 0:'0' (Test - Zone 2)
Oct  6 15:33:21 backup domoticz[90205]: 2020-10-06 15:33:21.688  (Test) Update 0:'40' (Test - Volume 2)

As can be seen from the log the devices are updated on every call to onHeartbeat but the plugin gets restarted after 5 minutes (the data timeout).

**Comment by gizmocuz** [comment]
@dwhile , thank you for you research....
You also receive a message like "nothing received for more xxx..." I assume ?
If yes, this will mean that 'pHardware->m_LastHeartbeatReceive' does not get updated

I made a patch for this in commit: https://github.com/domoticz/domoticz/commit/1c3859e1d16884b395586d43c580639591d3d8ce

Is it possible to check beta 12452 to see if the issue is resolved ?

**Comment by dwhile** [comment]
Hi
I have tried beta 12453 and run the same test as above using the Denon/Marantz plugin and can confirm that the plugin is no longer restarted after the data timeout. 

I will do a further test with the original Hive plugin shortly.

**Comment by gizmocuz** [comment]
Great, thanks for testing !

**Comment by dwhile** [comment]
Hi
I have now tried beta 12453 with the original Hive plugin and can also confirm that there is no restart after the data timeout. So it appears the problem is fixed.

Thanks

**Comment by gizmocuz** [comment]
Great! Thank you for your feedback!
