### ISSUE TITLE
Zwave blind open issue

### ISSUE THREAD

**Issue by nonolk** [domoticz/domoticz#4379]
Dear Gizmocuz,

In complement to this [4285](https://github.com/domoticz/domoticz/pull/4285), it's working perfectly when using the slider, but Open button is still sending 255 which is wrong see logs below:
When pushing the open button:
_2020-10-05 14:53:21.046 Status: User: Admin initiated a switch command (1029/Volet Baie vitrée 1/On)
2020-10-05 14:53:21.047 OpenZWave: Domoticz has send a Switch command!, Level: 255, NodeID: 55 (0x37)
2020-10-05 14:53:21.056 (Zwave) Light/Switch (Volet Baie vitrée 1)_

When using the slider:
_2020-10-05 14:54:52.917 Status: User: Admin initiated a switch command (1029/Volet Baie vitrée 1/Set Level)
2020-10-05 14:54:52.918 OpenZWave: Domoticz has send a Switch command!, Level: 99, NodeID: 55 (0x37)
2020-10-05 14:54:52.926 (Zwave) Light/Switch (Volet Baie vitrée 1)_

The device type is Blind percentage inverted as you can see below:
![Screen Shot 2020-10-05 at 16 56 17](https://user-images.githubusercontent.com/26922736/95096404-81a59500-072c-11eb-8a88-47abfb5ef491.png)

And the micromodule is a Qubino ZMNHCDx:
![Screen Shot 2020-10-05 at 17 02 54](https://user-images.githubusercontent.com/26922736/95096511-a437ae00-072c-11eb-8391-7045706629b7.png)

I'm able to compile domoticz from sources and to test debug code if needed.

Best regards,

**Comment by gizmocuz** [comment]
@nonolk , when you set the slider to 50%, next press the 'close' button.
Next press the 'open' button, where does your blind go to ?

**Comment by nonolk** [comment]
@gizmocuz the blind goes back to 50% ;-)
Here are the logs:
_ 2020-10-10 10:02:40.570 OpenZWave: Domoticz has send a Switch command!, Level: 50, NodeID: 54 (0x36)
2020-10-10 10:03:11.166 OpenZWave: Domoticz has send a Switch command!, Level: 0, NodeID: 54 (0x36)
2020-10-10 10:03:27.819 OpenZWave: Domoticz has send a Switch command!, Level: 255, NodeID: 54 (0x36)_
![67654C0A-1A21-4A85-81FF-A3C1DA2104DF](https://user-images.githubusercontent.com/26922736/95650042-3ea74100-0ae1-11eb-8b15-ff17c4257a4e.jpeg)
This device is also a Qubino zmnhcdx
![F0259F35-4E42-400A-9738-DAE0F7C2F03E](https://user-images.githubusercontent.com/26922736/95650099-93e35280-0ae1-11eb-954a-f9ad6b0fd643.jpeg)

**Comment by gizmocuz** [comment]
Okey, that makes sense... 255 = go to last position.
Do you use the slider often ? Is this maybe not a wanted situation ? (Going to the previous position, instead of all the way up)

But are you on the latest beta that has this patch to send 99 ?

**Comment by nonolk** [comment]
@gizmocuz , yes I’m using the slider and the buttons it depends on the time of the sun and the time of the day ;-)

For the moment I’m running domoticz Version: 2020.2 (build 12461), so normally yes the patch should be in. And it is for the slider,  it not for the button.

**Comment by gizmocuz** [comment]
@nonolk , the patch should have been for the button as well

**Comment by gizmocuz** [comment]
@nonolk , could you have a look at this patch ?:

https://github.com/domoticz/domoticz/commit/b92d81ab4c55d9b226cbb43195c647f1c13fd983

Could you try chaning ==100 to >99 ?

**Comment by nonolk** [comment]
@gizmocuz I’ll do it, and I will report back

**Comment by nonolk** [comment]
@gizmocuz I did it and it didn’t help. It still send level 255. I will have look to the code to see if I can find a solution.

**Comment by gizmocuz** [comment]
@nonolk , I think I found the place where it happens (Actually two)
- First in MainWorker::SwitchLightInt, here the last (set) level is retrieved from the database.
... the reason, imagine you have a dimming light bulb, and you like it to be set to 80% (you done so with the slider),
next time you turn 'On' the light, it should go to 80%, not 100%
... so at this point, the level is 80%, still the switch command send is 'On'

Next we arrive in ZWaveBase::WriteToHardware, ~line 910 (I can not debug if this where it happens currently, it might also be line 927, 

			else if ((cmnd == gswitch_sOn) || (cmnd == gswitch_sGroupOn))
				svalue = 255;

Anyway, 255 means (in ZWave language), Go to last/previous value/position

This is also what happens... good for 'lights/bulbs', maybe not for roller shutters... but maybe it is

I can imaging that around 14:00pm, you always need to position your blinds at 40% to keep the sun out
So if you have done this once via the slider, next time you can use the up/down buttons

**Comment by nonolk** [comment]
I was more or less at the same point as you, What I'm sure, it's in case of a button push we never go to this:
```
else if (
 			(
 				(switchtype == STYPE_BlindsPercentage)
 				|| (switchtype == STYPE_BlindsPercentageInverted)
 				|| (switchtype == STYPE_VenetianBlindsUS)
 				|| (switchtype == STYPE_VenetianBlindsEU)
 				)
 			&& (gswitch.cmnd == gswitch_sSetLevel) && (level == 100)
 		) {
 			if (pHardware->HwdType == HTYPE_OpenZWave)
 			{
 				//For Multilevel switches, 255 (0xFF) means Restore to most recent (non-zero) level,
 				//which is perfect for dimmers, but for blinds (and using the slider), we set it to 99%
 				level = 99;
 			}
 			else
 				gswitch.cmnd = gswitch_sOn;
 		}

```
I will have a deeper look and try to find a clever solution (my C++ skills are old so it may take some time).

**Comment by gizmocuz** [comment]
That is because the command is not SetLevel
You could rebuild it to look like:

```
		else if (
			(switchtype == STYPE_BlindsPercentage)
			|| (switchtype == STYPE_BlindsPercentageInverted)
			|| (switchtype == STYPE_VenetianBlindsUS)
			|| (switchtype == STYPE_VenetianBlindsEU)
			)
		{
			if ((gswitch.cmnd == gswitch_sSetLevel) && (level == 100))
			{
				if (pHardware->HwdType == HTYPE_OpenZWave)
				{
					//For Multilevel switches, 255 (0xFF) means Restore to most recent (non-zero) level,
					//which is perfect for dimmers, but for blinds (and using the slider), we set it to 99%
					level = 99;
				}
				else
					gswitch.cmnd = gswitch_sOn;
			}
			else if (gswitch.cmnd == gswitch_sOn)
			{
				if (pHardware->HwdType == HTYPE_OpenZWave)
				{
					gswitch.cmnd = gswitch_sSetLevel;
					level = 100;
				}
			}
		}

```

**Comment by nonolk** [comment]
It works now, like it should be ;-)

I just had to adapt a bit the code indeed, we don't want a level of 100 so I adapted the code like this:
```
else if (
                                (switchtype == STYPE_BlindsPercentage)
                                || (switchtype == STYPE_BlindsPercentageInverted)
                                || (switchtype == STYPE_VenetianBlindsUS)
                                || (switchtype == STYPE_VenetianBlindsEU)
                                )
                 {
                        if (((gswitch.cmnd == gswitch_sSetLevel) && (level == 100)) || (gswitch.cmnd == gswitch_sOn))
                        {
                                if (pHardware->HwdType == HTYPE_OpenZWave)
                                {
                                        //For Multilevel switches, 255 (0xFF) means Restore to most recent (non-zero) level,
                                        //which is perfect for dimmers, but for blinds (and using the slider), we set it to 99%
                                        level = 99;

                                        if (gswitch.cmnd == gswitch_sOn)
                                        {
                                                gswitch.cmnd = gswitch_sSetLevel;
                                        }
                                }
                                else
                                        gswitch.cmnd = gswitch_sOn;
                        }
                }

```
Like this it just work perfectly.

**Comment by gizmocuz** [comment]
Yes perfectly! Could you make a Pull Request against our active branch (development) ?

**Comment by nonolk** [comment]
Yes I will, just a bit latter.

**Comment by nonolk** [comment]
It seems I'm not allowed to make it ?
Or maybe I'm doing it wrong sorry

**Comment by gizmocuz** [comment]
@nonolk , The make a pull request, follow the following steps:
- Fork this project to your own account (there is a fork button on top of this page)
- Checkout the forked repository from your account
- Make the changes
- Commit the changes
- Push the changes
- Now if you look at the forked repository in your account, at the top you should see a 'green' button that allows you to make a Pull Request

**Comment by nonolk** [comment]
I did it, Sorry for my ignorance ;-)

**Comment by Catfriend1** [comment]
Could this be the same problem as described withy benext door contacts? The signal is well transmitted via zwave and received by domoticz but domoticz does not update the devices from on to off and off to on. From UI, one thinks the new state was just ignored by domoticz after arrival. https://www.domoticz.com/forum/viewtopic.php?t=33505

**Comment by gizmocuz** [comment]
@Catfriend1 , No, this is totally unrelated
@nonolk , thank you for the PR!!

**Comment by Catfriend1** [comment]
Ok, what is the correct way to go and get some help? I thought I'd get help or even debugging joining the thread about the door sensors which worked before the update and are broken now 🤷‍♂️ . They send their signal to the zwave controller and domoticz but the new state doesn't land in the device nor on ui. Just the zwave tables gets a time stamp bump on last seen. Plus, the device blinks one time which means "sent event successfully".

**Comment by gizmocuz** [comment]
@Catfriend1 , You have to use the forum.

**Comment by Catfriend1** [comment]
@gizmocuz 

Ok, ref: https://www.domoticz.com/forum/viewtopic.php?t=33505
