### ISSUE TITLE
Energy counter problem when counter decreases

### ISSUE THREAD

**Issue by CreasolTech** [domoticz/domoticz#4380]
Description: when a counter/meter decreases (e.g. energy meter connected to the grid, and photovoltaic system that produces more than what building consumes => power from the grid goes negative and energy decrements), the counter value displayed and graphed is wrong.

I found the issue in main/WebServer.cpp , that can be solved in this way (see the patch):
--- /tmp/WebServer.cpp	2020-10-06 08:48:39.286925955 +0200
+++ WebServer.cpp	2020-10-06 08:47:22.652680910 +0200
@@ -10812,7 +10812,8 @@
 ```

 							std::vector<std::vector<std::string> > result2;
 							strcpy(szTmp, "0");
-							result2 = m_sql.safe_query("SELECT MIN(Value) FROM Meter WHERE (DeviceRowID='%q' AND Date>='%q')", 
+							//result2 = m_sql.safe_query("SELECT MIN(Value) FROM Meter WHERE (DeviceRowID='%q' AND Date>='%q')", // error if Counter decreases (e.g. Energy meter where power goes negative when photovoltaic produces more than building consumption
+							result2 = m_sql.safe_query("SELECT Value FROM Meter WHERE (DeviceRowID='%q' AND Date>='%q') ORDER BY Date",
 								sd[0].c_str(), szDate);
 							if (!result2.empty())
 							{
```

The problem is that the query select the minimum value of the meter for the current day, while it should chose the first value recorded in the current day.
I don't know why it was chosen the minimum value of the day, but if it does not make sense, please apply the patch to fix this problem.
What happen before the patch: for example 
at midnight the energy consumed is 0
at 8am energy is 1kWh
at 4pm energy is -20kWh (the minimum)
at 11:55pm energy is -12kWh
minimum value of energy in the day is -20
energy at 11.55 pm is -12kWh
Domoticz displays in the graph a value of energy consumed of -12 (total) - (-20) (minimum)=8kWh but this is completely wrong. The right energy that should be displayed is -12kWh !
With the patch above, the energy of the day is calculated as -12 (total) - 0 (first value after midnight)=-12kWh

Then, some other points must be changed because graphing the energy of the hour, day, month is always wrong when counter goes negative.

If you need more information, don't hesitate to contact me.
Please inform me if this patch is applicable or not, so I know if I have to wait for the update or if I have to compile by myself.
Thanks a lot!!
Paolo

**Comment by gizmocuz** [comment]
@CreasolTech , thanks for the patch. Your query returns a lot of values, could you LIMIT it to 1 ?
Could you also post a before/after screenshot ?
It's the easiest if you could create a Pull Request (PR) for us, but if not, I can make the changes by hand of course

**Comment by CreasolTech** [comment]
Hi @gizmocuz , LIMIT 1 is ok for that query.
Unfortunally there are many other things to change to get it working completely:
1. queries to measure the counter value during day and month
2. javascript that displays graph (blue bars), because it never shows negative values

Since I'm new in Domoticz and I'm not a programmer (I use C for MCU, but not C++), before making all these changes I'd like to know if there is a reason why negative counters were not managed by Domoticz.
If it's ok to manage counters that get negative, I'll make all modifications locally and then submit a pull request.
Thanks.

**Comment by gizmocuz** [comment]
@CreasolTech , that is because we have also a 'Counter' (Delivered) 
For example when using a P1 Smart meter you have a counter for usage and one for generated (actually two)
Or people use a meter device that only measures the generated energy, and another of usage
Not one meter that goes up/down ... sure when you generate more then you use, the usage counter stays flat during that period

**Comment by Oleg-Sob** [comment]
I have the same problem, I have an INA 219 sensor between the battery and the inverter, when the battery is charging, it shows negative readings, when it is discharged, it shows positive values and as a result, it sums up negative readings as with a plus sign, but it must be subtracted. How to fix?

![12345](https://user-images.githubusercontent.com/71137109/95355943-c9fcb880-08ce-11eb-92d2-8cb88b2120a6.PNG)

**Comment by CreasolTech** [comment]
Hi. I made changes to main/WebServer.cpp and main/SQLHelper.cpp to fix the problem with usage energy, that can be negative when production energy is bigger then usage energy.
The main problem was that for every hour, day month or year, before Domoticz extracts the usage energy as MAX(Value)-MIN(Value), and this is completely wrong when the counter can be negative. I fixed this calculating the usage energy as LAST value - FIRST value, and now the 
Now, the usage energy is computed correctly. The graph show negative energy when production > usage, so it's possible to see exactly the real value of energy imported from the grid. 
I hope to find a sunny day in the weekend to check everything and show you the results.
Then, should I submit a patch (git diff) or make a pull request?
In case of pull request, please can you explain me how to do that? I have not knowledges about git PR, I've seen forum topic https://domoticz.com/forum/viewtopic.php?t=30189 but I'm a bit confused about "should I make a fork then submit a pull request to my fork? Or can I make a pull request on the main branch of Domoticz repository"?
Thanks for everything.

**Comment by rwaaren** [comment]
> In case of pull request, please can you explain me how to do that? 

See this [Forum post](https://domoticz.com/forum/viewtopic.php?t=30189#p228617)

**Comment by Oleg-Sob** [comment]
I'm wondering why the developers don't want to fix this problem and try it in beta?
I have negative solar readings counting as positive.

**Comment by CreasolTech** [comment]
> > In case of pull request, please can you explain me how to do that?
> 
> See this [Forum post](https://domoticz.com/forum/viewtopic.php?t=30189#p228617)

In the weekend, when weather will be ok to show what I've done, I'll fork the project and submit pull request as you said.
Thanks.
Paolo

**Comment by CreasolTech** [comment]
This is the graph of usage energy during the year. As you can see, after April the energy return raising because Domoticz compute the consumed energy during the day as MAX(Value)-MIN(Value) , but MIN(Value)<Value at midnight if the solar photovoltaic produces.
![immagine](https://user-images.githubusercontent.com/30940100/98365286-7945c000-2032-11eb-851a-9f9f71407502.png)

This is the graph for today using the last firmware (beta):
![immagine](https://user-images.githubusercontent.com/30940100/98366086-b1013780-2033-11eb-85c5-9b44a432f15d.png)

And this is the graph for today using the firmware modified by me:
![immagine](https://user-images.githubusercontent.com/30940100/98366181-d5f5aa80-2033-11eb-9fc8-1e3cf5ccc658.png)

I'll do some other checks, than submit the pull request.

**Comment by Oleg-Sob** [comment]
We are waiting for a new firmware.

**Comment by CreasolTech** [comment]
Pull request submitted. https://github.com/domoticz/domoticz/pull/4454

**Comment by Oleg-Sob** [comment]
Your firmware is working, blue bars show negative values.
![98](https://user-images.githubusercontent.com/71137109/99126732-696c4400-260f-11eb-95e8-68709adf6a28.PNG)

**Comment by Oleg-Sob** [comment]
But the readings today are reset every 5 minutes.
![78](https://user-images.githubusercontent.com/71137109/99126924-c49e3680-260f-11eb-922e-ff855743518d.PNG)

**Comment by CreasolTech** [comment]
> But the readings today are reset every 5 minutes.
> ![78](https://user-images.githubusercontent.com/71137109/99126924-c49e3680-260f-11eb-922e-ff855743518d.PNG)

Fixed !
