### ISSUE TITLE
Harmony Hub - Username and password fields missing

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#4381]
Domoticz build 12451 - Ubuntu x64

I had a Harmony Hub working for some time, but I had to change my Harmony.com password.
Since then the connection from Domoticz to the Hub fails.

I'm trying to find where I can enter the new password in Domoticz. However in the Domoticz Harmony hardware settings, I only have Address and Port. I have no Username and Password fields...

Am'I missing something?

**Comment by rwaaren** [comment]
@Olivier6767 Please use the forum. Enter Harmony Password in the search field and you will see a number of posts referring to the same question.

Bottom line you don't need a username / password to access the Harmony Hub if you are on the right firmware. If you upgraded to a later firmware version it will no longer work. 
Some of the found forum posts give you a detailed description how to downgrade the Harmony firmware.
