### ISSUE TITLE
Update French translation

### ISSUE THREAD

**Issue by nonolk** [domoticz/domoticz#4384]
Hello

There is one issue in the French translation for Energy counter.
It's translated Electricité, but it means Electricity.
So I corrected the translation file with the following value:
Energy : Energie

You can find the updated translation file in attachment to this issue.
[domoticz-fr.json.gz](https://github.com/domoticz/domoticz/files/5346685/domoticz-fr.json.gz)

Best regards,

**Comment by gizmocuz** [comment]
@nonolk , could you make the change on Transifex ?

**Comment by nonolk** [comment]
@gizmocuz, Yes I should be able to do it. Do you have tutorial or something ?

**Comment by gizmocuz** [comment]
https://www.transifex.com/domoticz/domoticz/dashboard/

**Comment by nonolk** [comment]
I did it, I also completed the missing translation and corrected some others.

**Comment by gizmocuz** [comment]
Thank you, I will pull the new translations from transifex and they will be available in the next beta version
