### ISSUE TITLE
Hardware Monitor: Possible code cleanup, detecting Pi hardware

### ISSUE THREAD

**Issue by kiddigital** [domoticz/domoticz#4386]
At the moment, the 'Montherboard Sensors" hardware (HTYPE_system) in case of Pi hardware, is using variables/values populated outside of the hardware module itself.

It depends on the 'CheckForOnboardSensors' function which is a classless method defined in the core code of 'domoticz.cpp'.

Shouldn't this function be moved to the internals of the 'hardwaremonitor' module?

This could cleanup the core code and gets rid of some global variables and defines that are only relevant for this hardwaretype.

Did I miss something in my analysis why this would not be possible?

@gizmocuz , @rwaaren , @akamming , I noticed a PR from a little time ago where some changes has been made in this module and core. Any thought?

If feasible, I will give it a try somewhere in the coming days.

**Comment by gizmocuz** [comment]
@kiddigital , yes you're right, this could be moved to the hardware monitor class, thanks in advance!
