### ISSUE TITLE
Need to configure topic MQTT value to be able to use liveobjetcs

### ISSUE THREAD

**Issue by ezeb75** [domoticz/domoticz#4387]
Hi,

More than an issue i whould ask to add as an option a way to configure the MQTT value in the GUI : it set set to "domoticz/out" as a static value in the file hardware/MQTT.cpp... and must the same for all mqtt targets...
Because for some IOT services the waited value is static too : for example for liveobjects it must be /dev/data.

Many thanks.
Regards.

**Comment by rwaaren** [comment]
@ezeb75 

please use the forum for this suggestion. The  domoticz github issues is for reporting domoticz CODE bugs only.
This suggestion is already on the forum. You can add your comments to that. If it ever gets to the top of the priority list of someone with enough time and skills and a PR gets accepted it will be in a future release.
Thx for your understanding.

[MQTT topic hierarchy suggestion and discussion](https://www.domoticz.com/forum/viewtopic.php?f=31&t=33314)
