### ISSUE TITLE
Dots under floorplan in case multiple floorplans disappeared.

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#4388]
Hi,

After approx. a week, after updating to version 12451, I noticed the issue that the dots has disappeared under the drawings, exept the first. So if you want to select another drawing, you have to go back to another menu item, then to the Floorplan (1st drawing) and then to another one..

See also: https://www.domoticz.com/forum/viewtopic.php?f=8&t=34121

Update history is available, bit was first noticed after 12451

Regards

**Comment by gizmocuz** [comment]
Thanks for reporting. Was caused by the introduction of the new JQuery library.
I updated many more files in a later commit as well
