### ISSUE TITLE
Device "Last seen: " is not translated

### ISSUE THREAD

**Issue by rreuvekamp** [domoticz/domoticz#4390]
This is a minor issue but I'd thought it couldn't hurt to document.

When on the Dashboard, Switches, etc page, the "Last seen" of a device is not translated. Even though it should be according to Transifex.

[Shown in Dutch](https://i.imgur.com/IcGmcHF.png)
[Shown in German](https://i.imgur.com/LQCbclB.png)

Using the latest beta

Version: 2020.2 (build 12467)
Build Hash: 2829993f3-modified
Compile Date: 2020-10-11 11:06:44
dzVents Version: 3.0.14
Python Version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum

No question

* Please use the search feature to see if your issues have been raised or addressed first.

Done

* First try to update to the latest beta version

Done aswell

* Clear your browser cache + AppCache (two different things!!)

Done aswell, even tried another browser on which I haven't used Domoticz before

* Always state your version and hardware platform when reporting code related issues

Version: 2020.2 (build 12467)
Build Hash: 2829993f3-modified
Compile Date: 2020-10-11 11:06:44
dzVents Version: 3.0.14
Python Version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by gizmocuz** [comment]
Yep, the same goes for 'Type'
This is because it's set via CSS, if you know of a way to get this translated (dynamic CSS?) please create a PR

**Comment by rreuvekamp** [comment]
Ahh that explains it, good to hear it was already known!

Unfortunately I lack the specific knowledge, but I saw that someone is rewriting the front-end

**Comment by gizmocuz** [comment]
Not that I am aware of, or you mean a 'theme' ?

**Comment by rreuvekamp** [comment]
I saw pull request #3892 working on rewriting the front-end to use Angular 8

**Comment by rreuvekamp** [comment]
Since this was already known I'll close the issue

Thanks for making Domoticz and all the work you've put in it mate! It's really great!
