### ISSUE TITLE
Found left-over process

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#4391]
Hi,

This a minor issue, but perhaps worthwhile to report.

Since build 1245,1 I see the following in /var/log/daemon.log:

> Oct 11 11:41:18 RPi2 systemd[1]: domoticz.service: Found left-over process 18111 (updatebeta) in control group while starting unit. Ignoring.
> Oct 11 11:41:18 RPi2 systemd[1]: domoticz.service: Found left-over process 18196 (sudo) in control group while starting unit. Ignoring.
> Oct 11 11:41:18 RPi2 systemd[1]: domoticz.service: Found left-over process 18201 (systemctl) in control group while starting unit. Ignoring.

As it happens after build 12451 (12449 was the last one without )it might have to do with the changes in GUI .
As it is ignored, it has no other effects, but I don't thing is should happen.

**Comment by gizmocuz** [comment]
I don't think this can be related to gui changes, build could you perform a reboot and check again when there is a new beta vesion?
