### ISSUE TITLE
Sharing dummy devices via Domotict Remote

### ISSUE THREAD

**Issue by hofikhof** [domoticz/domoticz#4399]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by hofikhof** [comment]
Why is not possible to share dummy device via Domoticz Remote Server. I set sharing devices in user settings (physical device and dummy device) and I don't see on master this dummy device, only physycal device are visible on master server.
Thank you very much.

**Comment by rwaaren** [comment]
Please do not use the domoticz issue list for these type of questions. 
If you have read the issue guidelines you will know where to ask.
Thx
