### ISSUE TITLE
Thermofloor - Thermostat Z-Wave Heatit Z-TRM3fx not working

### ISSUE THREAD

**Issue by chatis** [domoticz/domoticz#4400]
Hello,

I have bought this device to manage temperature on my house : Thermofloor - Thermostat Z-Wave Heatit Z-TRM3fx

But When I want to configure it, I have nothing in the configuration part..

And when I try to send data to the device, the data isn't sended.. I ask the company that sell it and they said this is developper from Domoticz that know where is the problem.

Is someone has any idea how I can fix it ?

Thank you

<img width="1398" alt="Capture d’écran 2020-10-13 à 22 22 30" src="https://user-images.githubusercontent.com/4694026/95912932-ccb24e80-0da3-11eb-8145-a4ef0a1d9c87.png">
<img width="1187" alt="Capture d’écran 2020-10-13 à 22 22 45" src="https://user-images.githubusercontent.com/4694026/95912943-ce7c1200-0da3-11eb-854e-4a2875e0399b.png">
<img width="1192" alt="Capture d’écran 2020-10-13 à 22 32 29" src="https://user-images.githubusercontent.com/4694026/95913069-fe2b1a00-0da3-11eb-9741-51206be9a13a.png">

**Comment by gizmocuz** [comment]
@chatis , when you created this issue, there was a issue guideline presented.
You did not mention for example the Domoticz version you are using...
Since this is a quite new device, you need to be on the beta version

**Comment by chatis** [comment]
Hello,

Sorry I was sure to read carfully the guideline.

My version is 2020.1

How can I update my version ? because when I ask the update, this is updating, but nothing is installed at the end.

Thank you

**Comment by gizmocuz** [comment]
You have to configure Domoticz in the settings page to use the 'Beta' channel as release channel.
Please let me know how everything works out

**Comment by chatis** [comment]
Hello,

I have updated to 2020.2 12481

But still the same problem.. this is not working for my device

**Comment by chatis** [comment]
Not true !! All works well now !! thank you

**Comment by gizmocuz** [comment]
@chatis , thanks for the feedback ! Great it's working!
