### ISSUE TITLE
lost of feedback netatmo thermostatic valve when adding weather station 

### ISSUE THREAD

**Issue by sylar6725** [domoticz/domoticz#4402]
Version :
Version: 2020.2
Build Hash: b63341bc0
Compile Date: 2020-04-26 13:47:55

Hardware platform: raspberry Pi 3 Model B

At the beginning, I only had 7 netatmo thermostatic valves and the netatmo room thermostat. Everything was working perfectly (temperature rise of each valve, set point adjustment, away mode, ...).
I then added a netatmo weather station, and there, the valves stopped working. Only the weather station was reporting information.

I removed the devices, I removed the netatmo "hardware", to restart on something clean. But it doesn't change anything, I can't get the thermostatic valves/thermostat and the weather station to work together. 

I had made captures of the logs when I did my tests (I didn't have time to do create a issue before)

Here are the logs when there are only the valves and the thermostat on my netatmo account (the weather station hasn't been added yet):
![sans station](https://user-images.githubusercontent.com/71662117/96195833-2f474e00-0f4e-11eb-8387-68d54393f573.jpg)

And now, here are the logs when the weather station has been added (clean restart: devices and netatmo hardware has been remove)
![avec station](https://user-images.githubusercontent.com/71662117/96196153-ffe51100-0f4e-11eb-8e02-1ae3d2987825.jpg)

Only the room thermostat is detected, but it did not get the right name.

![2020-10-16_013302](https://user-images.githubusercontent.com/71662117/96197248-c4981180-0f51-11eb-9749-20e44b31471a.jpg)

There are also 2 other problems:
-It detects me that the batteries of the thermostats are empty, when they are not.
-It also detects empty batteries on the weather station Wissembourg, when it's not my station, it's a station bookmarked in netatmo weathermap.  (I receive alerts all the time on my phone for empty batteries with domoticz app)

Searching on the forum, it seems I'm not the only one : [https://www.domoticz.com/forum/viewtopic.php?f=31&t=6846&p=233255&hilit=netatmo#p233255](https://www.domoticz.com/forum/viewtopic.php?f=31&t=6846&p=233255&hilit=netatmo#p233255)

**Comment by olivierberthomme** [comment]
This won't be easy to correct as the Netatmo plugin only allow 1 "m_NetatmoType"
https://github.com/domoticz/domoticz/blob/3596d56635031d6ea6fbbf6014a730d669ab2b84/hardware/Netatmo.cpp#L65

Possible types:
		NETYPE_WEATHER_STATION
		NETYPE_HOMECOACH
		NETYPE_ENERGY

Possible quick workaround: add the m_NetatmoType selectable from hardware page then you should create 2 hardwares, one for weather station, the second one for thermostat.

**Comment by sylar6725** [comment]
Yes, it would be a very good idea to be able to use netatmo account more than once in the hardware page and to have the choice of "m_NetatmoType". It can be a good fix.

There remains a little problem with the NETYPE_WEATHER_STATION, which should normally only display weather station data, but retrieves the information from the thermostat (which is not quite correct because it tells me that the batteries are empty).

The information "Thermostat", "SetPoint Thermostat" and "Away Thermostat" are information data of the thermostat that are retrieved when the weather station is detected by the plugin.

But, we can work around the problem simply by not selecting them in devices.

**Comment by waltervl** [comment]
@sylar6725 @olivierberthomme Similar issue is solved, please check in latest beta if this issue is also solved.

**Comment by sylar6725** [comment]
Hi @waltervl
I just install the last beta and it works, I have access to my valves and thermostat again
Ty to StephaneM60 for the fix.
