### ISSUE TITLE
No sliders on floorplan when using custom icons on dimmers

### ISSUE THREAD

**Issue by xztraz** [domoticz/domoticz#4407]
DOMOTICZ
2020.2 (build 12392) beta

![image](https://user-images.githubusercontent.com/25690871/96592075-48525500-12e8-11eb-9c40-9b84ec5bef87.png)

No sliders when using custom icons on floorplan. also text on icon shows set level:xx% instead of just xx%

older closed topics that are unresolved.
https://github.com/domoticz/domoticz/issues/3555
https://github.com/domoticz/domoticz/issues/872

![image](https://user-images.githubusercontent.com/25690871/96591825-f8738e00-12e7-11eb-9440-acfa88827ac1.png)

Forum topics:
https://www.domoticz.com/forum/viewtopic.php?t=15742
https://www.domoticz.com/forum/viewtopic.php?t=26398

**Comment by StRess691** [comment]
This same issue with my installation, this same version as yours on RaspberryPi3b+. Have you resolved it? I'm only able to get it to work when I'm changing the icons on the server (by removing default and replacing them with mine), which isn't a solution what I'm searching for.

**Comment by gizmocuz** [comment]
Try updating to the latest beta version first

**Comment by xztraz** [comment]
same problem on 2020.2 (build 12705) (latest beta)

**Comment by rrozema** [comment]
Version: 2020.2 (build 12697)
Build Hash: 34c800ea6-modified
Compile Date: 2020-11-22 13:14:05
dzVents Version: 3.0.16
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

The dimmer device in the 'Switches' tab:
![image](https://user-images.githubusercontent.com/1747982/102053524-31ac1400-3de8-11eb-8632-34d172744503.png)

And the same device in the floorplan tab, as you can see the level can not be set from the floorplan:
![image](https://user-images.githubusercontent.com/1747982/102053878-beef6880-3de8-11eb-97bf-cd2b2249158a.png)

However, if the default icon is selected on the same dimmer device, it looks like this, where the level can be set in the floorplan:
![image](https://user-images.githubusercontent.com/1747982/102054061-168dd400-3de9-11eb-9672-c177b93af4f1.png)

**Comment by gryzli133** [comment]
Similar problem I'm facing with the Fan icon and the Blinds Percentage icon. Both are missing slider. This is making domoticz almost unusable for my smart house with 300m2 and hundreds of smart devices. Take a look just at my Switches tab - the only way I can find something is floorplan.

![image](https://user-images.githubusercontent.com/30415928/103284868-be57f400-49dc-11eb-835d-4194663ab10c.png)

**Comment by gizmocuz** [comment]
@gryzli133 , DO NOT CROSSPOST PLEASE!

**Comment by gryzli133** [comment]
Just checked that with Speaker Icon the dimmer slider is working also with Floorplan, but not with Fan Icon for example...

![image](https://user-images.githubusercontent.com/30415928/103665258-82400880-4f73-11eb-9d3a-a86354c84012.png)

**Comment by xztraz** [comment]
Still borken.

**Comment by xztraz** [comment]
Still broken!!

**Comment by xztraz** [comment]
It's a shame this gets no prio since it makes domoticz really hard to use if having many items in your system.
But nobody seem interested in fixing this so closing.

**Comment by gizmocuz** [comment]
Maybe you could make a PR for this ? I'm not using the floorplan. It should not be that hard to fix and you got a whole year to look at this

**Comment by gryzli133** [comment]
I really like Domoticz for it ease of use, but finally I switch to Home Assistant due to its modular built and flexibility. Of course it is much more difficult to get same results as it is out of box in Domoticz, but in the end, I can customize everything as I like it.

**Comment by gizmocuz** [comment]
You still have the same issue , if something needs to be added/changed, it needs to be done.

**Comment by rezzalex** [comment]
Hello @gizmocuz

I won't be able to propose a PR here bu the issue is real and now I am facing it...

**Comment by xztraz** [comment]
> I really like Domoticz for it ease of use, but finally I switch to Home Assistant due to its modular built and flexibility. Of course it is much more difficult to get same results as it is out of box in Domoticz, but in the end, I can customize everything as I like it.

Also migrated to home assistant. Domoticz where great to start with. quite low learning threshold and could be run on simple hw. but when the number of nodes grow, ha is a lot more flexible.
