### ISSUE TITLE
Nanoswitch ZW132 not giving current status in Domoticz

### ISSUE THREAD

**Issue by beninhos** [domoticz/domoticz#4409]
Not sure if this is a hardware issue or a software issue. 

**Summary:**
The device is turning physically turning on/off, only Domoticz thinks it's still in the previous state and turns on other switche. The connection is good, and no lagging in sending/receiving commands. I have no other issues with send/receiving command with other types of switches in this house. 

**System**
> Hardware: RPI3B+ && ZW090 Z-Stick Gen5 EU with Nanoswitch ZW132+
> Version: 2020.2 (build 12467)
> Build Hash: 2829993f3-modified
> Compile Date: 2020-10-11 11:06:44
> dzVents Version: 3.0.14
> 

**Long version of issue description**
I've built an Aeotec NanoSwitch ZW132 dual nanoswitch+ in my espressomachine --> My goal is to let it shut off after 45' after turning it on. To save energy, so the digital switch function has to work 100% to be certain the machine goes off. 

I have an issue with send/receiving current status.
The hardwarepage gives me 3 switches (S1, S2, S3), and they all work. Kind off. When I switch manual on-off (with the physical button), the device does what is should, it shows S1 =on  and when i manual turn of, the S1=off. So that works. 

BUT when i digitally switch the on/off switch, the device turns on/off (like it should), but does not give that specific feedback to Domoticz, like that it is turned on/off. It sends a signal that S2 and/or S3 is on/off of that S1 is still on. Really strange.

I need to switch again, and again until they are all off. The same goes for turning it on, the device goes on after the first attempt, but the software does not tell me it is on.. 

It's a neelde in a haystack. Not sure where to start here.

**Comment by beninhos** [comment]
I found some log's on the open zwave page while controlling the switch, but that's only some packagesloss..  Still a needle in the haystack.  Could this be a config issue or is it something else, because if this is just a user problem i should be adressing this to the forums. The issue is also present on the ozwcp page, so i think domoticz is not to blame?

`2020-12-15 21:27:16.959 Always, 2020-12-15 21:27:17.959 Error, Node020, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Set (Node=20): 0x01, 0x0a, 0x00, 0x13, 0x14, 0x03, 0x25, 0x01, 0x00, 0x25, 0x73, 0x83" 2020-12-15 21:27:17.959 Always, 2020-12-15 21:27:17.959 Always, Dumping queued log messages 2020-12-15 21:27:17.959 Always, 2020-12-15 21:27:17.960 Always, 2020-12-15 21:27:17.960 Always, End of queued log message dump 2020-12-15 21:27:17.960 Always, 2020-12-15 21:27:18.001 Error, Node020, ERROR: ZW_SEND_DATA could not be delivered to Z-Wave stack 2020-12-15 21:27:18.001 Always, 2020-12-15 21:27:18.001 Always, Dumping queued log messages 2020-12-15 21:27:18.001 Always, 2020-12-15 21:27:18.001 Always, 2020-12-15 21:27:18.001 Always, End of queued log message dump 2020-12-15 21:27:18.001 Always, 2020-12-15 21:27:30.725 Error, Node020, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Get (Node=20): 0x01, 0x09, 0x00, 0x13, 0x14, 0x02, 0x25, 0x02, 0x25, 0x83, 0x72" 2020-12-15 21:27:30.726 Always, 2020-12-15 21:27:30.726 Always, Dumping queued log messages 2020-12-15 21:27:30.726 Always, 2020-12-15 21:27:30.726 Always, 2020-12-15 21:27:30.726 Always, End of queued log message dump 2020-12-15 21:27:30.726 Always, `

**Comment by gizmocuz** [comment]
Yes does not look like a Domoticz issue, but could be a issue with the switch
