### ISSUE TITLE
Cache Refresh error on Safari - Solution

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#4410]
Running on Domoticz 12451 on linux

Since some time I have Cache Error messages when opening the Domoticz web page on Safari (both iOS and MacOS).

By using the web developer tools I was able to find the culprit. 
It is linked to 3 references in the file `domoticz/www/html5.appcache`:
- reference to `js/angular-md5-min.js` needs to be changed to `js/angular-md5.min.js`
- reference to `js/ng-grid-flexible-height.js` needs to be removed (the file does not exist)
- reference to `js/ng-grid.min.js` needs to be removed (the file does not exist)

After these changes the web page loads without any cache error.

Could this be corrected for upcoming builds?
Thanks.

**Comment by gizmocuz** [comment]
Done, thanks for reporting!
