### ISSUE TITLE
Phantom records in LightingLog with DeviceRowID of 18446744073709551615 (Hex: 0xFFFFFFFFFFFFFFFF)

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#4411]
I am on Linux raspberry 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux with Domoticz version 2020.2 build 12467
I have 2 systems running with different hardware attached. Both system have the above phantom records. The slave has a lot less phantom records then the other main system.
Looking at the date and time of those records and compare them with the logging I could not find a devices what could be responsible for those records.
I also tried with logging: 
`DAEMON_ARGS="$DAEMON_ARGS -loglevel normal,status,error,debug -debuglevel normal,hardware,received,webserver,eventsyst$
DAEMON_ARGS="$DAEMON_ARGS -loglevel info"`
But there was no SQLH record in the log file that gave a hint to which device might be responsible.
For the main system with approx. 230 active devices I had to set the Short Log Sensors to 1 day, because of the number of phantom records.

Where are they come from, and what can be done about it?

**Comment by SargonofAssyria** [comment]
I found out that it sometimes also happens that some of those "1.84467440737096e+19" records in the LightingLog are duplicates.
Not every record, but in my slave Raspberry Pi about 10%. That should not happen at all?

When I search for "INSERT INTO LightingLog" in the source code I find 4 files.
SQLHelper.cpp but in that file there is some code to prevent duplicate records.
Kodi.cpp, LogitechMediaServer.cpp and PanasonicTV.cpp in all of them there is a remark that the function has to be rebuild.
Only in my Master Raspberry Pi I have disabled KODI hardware by a Broadlink device. But there is no Kodi, Logitech or Panasonic device in my Slave Raspberry Pi, but still I got those records too.

**Comment by rwaaren** [comment]
> For the main system with approx. 230 active devices I had to set the Short Log Sensors to 1 day, because of the number of phantom records.

I have no solution but the entries in LightingLog are not controlled by the setting in Short Log Sensors. The setting that controls the number of days in LightingLog is Light/Switches (on the same tab) 

Can you show some of the Phantom records?

**Comment by SargonofAssyria** [comment]
![2020-10-24_10-32-22](https://user-images.githubusercontent.com/24824113/97077489-7388bd00-15e4-11eb-8b66-dba0cc3cdce7.png)

These are a few from my Master.

![2020-10-24_10-33-28](https://user-images.githubusercontent.com/24824113/97077493-7a173480-15e4-11eb-98f6-a318578d3451.png)

These are from the Slave.

**Comment by rwaaren** [comment]
Do you see any relation between (some) records in the slave and master? 
Do you see anything unexpected when you do a "select id from devicestatus union select id from scenes;" on your databases?

**Comment by SargonofAssyria** [comment]
I did cleanup (with your dbCheck) both databases to get a clean start. Have to wait a bit until they show up.
Previous there was NO relation date wise between the databases with the affected records.
I did not see anything (but for the idx) from your sql command.

**Comment by SargonofAssyria** [comment]
I found a relationship!!!
When I activate On or Off a KlikAanKlikUit switch on my Master then a dzVents script is run which controls 3 lights (Zigbee) and 1 Zwave switch (to be synchronized with the lights).
That KaKu switch can only be recieved by the Slave, because the Slave has 2 RFLinks and a P1 connected as physical hardware.
1 RFLink is for the normal frequency on which the KaKu's are and the other RFLink is on an other frequency for my Somfy rollershutters.
I will disconnect my Somfy RFLink and see what happens.

Edit: That did not give a solution, phantom records are still coming when I active a Master switch into the Slave database.

**Comment by SargonofAssyria** [comment]
Found a small difference between the 'same' KaKu device in Master and Slave Raspberry Pi.
![2020-10-24_13-01-44](https://user-images.githubusercontent.com/24824113/97080078-1b0fea80-15f9-11eb-8ddb-9e28d8c6f5fc.png)
Master, device from RFXcom

![2020-10-24_13-02-23](https://user-images.githubusercontent.com/24824113/97080094-33800500-15f9-11eb-9e5e-6f0b0cde62e3.png)
Slave, device from RFLink
DeviceID on Slave has an extra '0'  and Type and SubType are different.
Any idea's on how to debug this extra phantom record(s)?

**Comment by rwaaren** [comment]
You might want to start in the sourcefiles inserting / updating records in this table.

```
main/SQLHelper.cpp:4678:                                "INSERT INTO LightingLog (DeviceRowID, nValue, sValue, User) "
main/SQLHelper.cpp:7286:        safe_query("UPDATE LightingLog SET DeviceRowID='%q' WHERE (DeviceRowID == '%q')", newidx.c_str(), idx.c_str());
hardware/Kodi.cpp:543:          result = m_sql.safe_query("INSERT INTO LightingLog (DeviceRowID, nValue, sValue, User) VALUES (%d, %d, '%q','%q')", m_ID, int(m_CurrentStatus.Status()), sLogText.c_str(), "Kodi");
hardware/PanasonicTV.cpp:295:           result = m_sql.safe_query("INSERT INTO LightingLog (DeviceRowID, nValue, sValue, User) VALUES (%d, %d, '%q','%q')", m_ID, int(m_CurrentStatus.Status()), sLogText.c_str(), "Panasonic");
hardware/LogitechMediaServer.cpp:184:                                   result = m_sql.safe_query("INSERT INTO LightingLog (DeviceRowID, nValue, sValue, User) VALUES (%d, %d, '%q','%q')", itt->ID, int(nStatus), sLongStatus.c_str(), "Logitech");
 
```

**Comment by SargonofAssyria** [comment]
I know. I deleted my Kodi device and do not have PanasonicTV nor LogitechMediaServer so I can skip those.
Until now I discovered only 1 Kaku device with which I can emulate the insert of phantom records into LightingLog.
The first line is doing the job, but where does that phantom DeviceRowID come from, and where does it get accepted without being checked against a real IDX?

Problem is also that with full debugging on nothing is logged because of this.
`        if (!bDeviceUsed)
            return ulID;    //don't process further as the device is not used
`

**Comment by SargonofAssyria** [comment]
By putting extra Debug loglines in the source of the Slave Raspberry Pi, I found out that the phantom records are being filled with a value of: 18446744073709551615 and that is in hex: FFFFFFFFFFFFFFFF
`2020-10-25 15:24:00.513  [6effe220] Debug: TEST Gang - Boven. HwID:7  DevID:00471562 Type:244  sType:11 nValue:0 sValue:0
2020-10-25 15:24:00.513  [6effe220] Debug: TEST Gang - Boven. DevID:'47' nValue:0 sValue:0 User:
2020-10-25 15:24:01.087  [6effe220] Debug: TEST  HwID:7  DevID:0100CAF2 Type:244  sType:11 nValue:0 sValue:0
2020-10-25 15:24:01.087  [6effe220] Debug: TEST  DevID:'18446744073709551615' nValue:0 sValue:0 User:
`
B.t.w. I do not have a device with a DevID of 0100CAF2
Hopefully does that give someone an idea where to look for.
Could otherwise somebody sent me in the right direction where I could add some extra debug logging.

**Comment by SargonofAssyria** [comment]
I am a little bit closer.
I do not have a device on my Slave with DevID of 0100CAF2, but I have on the Master is a device with the DevID of 100CAF2 ( so without the leading zero) That's an other KaKu device, only on my Master, that is synchronize with the KaKu switch "Overloop - Boven" via a dzVents script with ".checkFirst().silent()" to avoid further triggers. So the KaKu command is not sent over the air.
Still it seems that the command might be received by the Slave and processed.
That should never happen because the Slave does NOT have a device with DevID of 0100CAF2 or 100CAF2.
I am out of options. Anybody any idea how to debug this further?

**Comment by SargonofAssyria** [comment]
Found the problem, at least for my Raspberry Pi's.
In file main/SQLHelper.cpp in function "uint64_t CSQLHelper::UpdateValueInt". When a device does not exists then function "InsertDevice" is called. When AcceptNewHardware if Off then the function returns -1 (line 4404) then function UpdateValueInt (on line 4462-4463) should also return, but it does not!
`        if (ulID < 1)
            return -1;
`
Could someone check this and possibly fix it?

**Comment by kiddigital** [comment]
Hm... makes sense and if I look at the code, this is somewhat of a 'known' issue.

```
uint64_t CSQLHelper::InsertDevice(const int HardwareID, const char* ID, const unsigned char unit, const unsigned char devType, const unsigned char subType, const int switchType, const int nValue, const char* sValue, const std::string& devname, const unsigned char signallevel, const unsigned char batterylevel, const int used)
{
	//TODO: 'unsigned char unit' only allows 256 devices / plugin
	//TODO: return -1 as error code does not make sense for a function returning an unsigned value
	std::vector<std::vector<std::string> > result;
	uint64_t ulID = 0;
	std::string name = devname;

	if (!m_bAcceptNewHardware)
	{
		_log.Debug(DEBUG_NORM, "Device creation failed, Domoticz settings prevent accepting new devices.");
		return -1; //We do not allow new devices
	}
```
So indeed the -1 does not make sense... have to check, but it would return '18,446,744,073,709,551,615' (0xFFFFFFFFFFFFFFFF) I would assume (all bits set). So checking for <1 will not work.

I will create a fix and make it check for this value, so we can still pass -1 and assume it means something is wrong.

So we can now create 1 less device in Domoticz, but still 18 gezillion... :)

**Comment by SargonofAssyria** [comment]
Tnx, would be great finally get rid of those phantom records!

**Comment by kiddigital** [comment]
Create PR #4419 for this issue

**Comment by gizmocuz** [comment]
I think you can compare against -1 via "(uint64_t)-1"

`if (DeviceRowIdx != (uint64_t)-1)`

Maybe there is a place where this is checked incorrectly

**Comment by gizmocuz** [comment]
@kiddigital , you beat me to it ! Thanks!

**Comment by SargonofAssyria** [comment]
Compiled 12501 and the problem is solved! TNX!!!
