### ISSUE TITLE
Wrong action of "Push on Button" on floor plan. if custom icons are used

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#4413]
If you configure "Push on Button(s)" on a floorplan AND you have configured custom (non-default) icons the wrong action will be carried out. Instead of "Switching ON", you will see "Switching OFF.
As this action is not what we want or where a script has been created for, the user will make the remark "It is not working".

You will also see under the icon itself "OFF", instead of "ON"

This could have a relationship with #4407, but I'm not sure about that.

For more info, see https://www.domoticz.com/forum/viewtopic.php?f=6&t=34269

Regards

**Comment by kitopopo** [comment]
I have also verified this problem, when I change the default icon to another icon, from the floor plan the push on button does not work and I get the off action in the domoticz log. With the default icon (cogwheel) everything works fine from the floor plan.

Regards

**Comment by waltervl** [comment]
Tested in 2022.1 and giving correct action and logging

**Comment by kitopopo** [comment]
Dear friend,

Please re-open this issue please, this function doesn't work. The push on buttons added to floorplan must have the default cogwheel icon configured for them to work (default icon). If the push on buttons have any other icon than the default configured, the push on buttons do not perform their action in the floorplan. 
Please solve the problem, i reported this problem to @FireWizard52 the past 21th Oct 2020 and the problem persist.

Default icon in the floor plan --> action push on button --> initiated a switch command (565/Desmontar hdd/**On)**
Another icon in the floor plan --> action push on button --> initiated a switch command (565/Desmontar hdd/**Off)**

If you notice in the domoticz log, the order sent after pressing the push on button is a "off", but it should be "on".
this is the reason for the failure of the push on button in the floor plan. can you solve the problem? 

Thanks in advanced.

**Comment by waltervl** [comment]
Tested again with custom icon and indeed a switch off command is generated.

**Comment by waltervl** [comment]
I checked the code in https://github.com/domoticz/domoticz/blob/development/www/js/domoticzdevices.js where the issue probably origins from but could not find the issue (due to lack of javascript knowledge...)

**Comment by kitopopo** [comment]
> Tested again with custom icon and indeed a switch off command is generated.

Dear friends, i check again now and the problem persist, please, see the atached pictures. The problem is the following:

The **Push On** button is not recognized as Push On button in the floor plan. The **Push on** button Is recognized as **Push Off** button in the floor plan. Please see the log:

![1](https://user-images.githubusercontent.com/51416982/172496251-d32af03a-43bb-4907-b556-deed25a4c164.jpg)

In the log, the push on button is recognized as "OFF" in the domoticz log instead of being recognized as "ON". This is a Push on button. Please see the "switch ugreen setup" 

![2](https://user-images.githubusercontent.com/51416982/172496466-65acbdc0-7701-48a4-afb8-b870f2c6128e.jpg)

I hope the problem can be solved, thanks in advance

**Comment by medassi** [comment]
Hello, I have exactly the same problem. I updated to Version: 2023.2 (build 15640), but nothing new. Have you managed to resolve your problem more than one year later?

**Comment by FireWizard52** [comment]
Hello @medassi 

I just tested it and I'm sorry. It has not been solved
I am not able to make a PR for it. Anyone?

**Comment by gizmocuz** [comment]
This should not be so hard to find/debug/fix... Let me have a look...

**Comment by gizmocuz** [comment]
Should be solved in beta 15642 😁

**Comment by medassi** [comment]
A big thank-you !!! I just tested build 15643 and it works perfectly.
Thanks to you.
