### ISSUE TITLE
Build failure with python 3.9

### ISSUE THREAD

**Issue by kofec** [domoticz/domoticz#4415]
Now we have a issue with python 3.9
https://github.com/domoticz/domoticz/issues/3703

/* _Py_DEC_REFTOTAL macro has been removed from Python 3.9 by:
    https://github.com/python/cpython/commit/49932fec62c616ec88da52642339d83ae719e924 */

So we need to modify:
https://github.com/domoticz/domoticz/pull/3713

**Comment by gizmocuz** [comment]
@kofec , feel free to make a PR

**Comment by kofec** [comment]
The solution is here. Prepared by Fedora team:
https://src.fedoraproject.org/rpms/domoticz/c/0cb4a4b4734638b8b07177713455611746b74185

**Comment by kofec** [comment]
But it still didn't work my case:
```
/home/openwrt/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /home/openwrt/openwrt/tmp/ccHRxNhU.ltrans4.ltrans.o: in function `py3__Py_DECREF(char const*, int, _object*) [clone .isra.13] [clone .lto_priv.3954] [clone .lto_priv.4005]':
<artificial>:(.text+0x1698): undefined reference to `_Py_Dealloc'
collect2: error: ld returned 1 exit status
make[5]: *** [domoticz] Error 1
make[5]: Leaving directory `/home/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/domoticz-805fee10fd609a02182eaa01e99bcb4b1b560426'
make[4]: *** [CMakeFiles/domoticz.dir/all] Error 2
make[4]: Leaving directory `/home/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/domoticz-805fee10fd609a02182eaa01e99bcb4b1b560426'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/domoticz-805fee10fd609a02182eaa01e99bcb4b1b560426'
make[2]: *** [/home/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/domoticz-805fee10fd609a02182eaa01e99bcb4b1b560426/.built] Error 2
make[2]: Leaving directory `/home/openwrt/openwrt/feeds/packages/utils/domoticz'
time: package/feeds/packages/domoticz/compile#171.69#11.61#178.54
make[1]: *** [package/feeds/packages/domoticz/compile] Error 2
make[1]: Leaving directory `/home/amk082/openwrt'
make: *** [package/domoticz/compile] Error 2
```

**Comment by neheb** [comment]
@kofec this is OpenWrt specific and as such should be reported in the packages feed.

Anyway, your issue is that you didn't add the link flags from that patch.

**Comment by kofec** [comment]
@gizmocuz 
I only use domoticz in openwrt so I'm not sure how this will affect regression compilation (python <3.9) as well as Raspbian and other operating systems.
Do you want me to close the issue? Or leave it if someone has the same issue

**Comment by samm-git** [comment]
I can confirm issue with  `_Py_Dealloc' on macos

**Comment by jzapater** [comment]
#4422

**Comment by neheb** [comment]
Look at the patch again.

**Comment by samm-git** [comment]
@neheb thanks, development branch compiles fine for me.

**Comment by svde** [comment]
also compiles for me (fc33 + rawhide)

**Comment by gizmocuz** [comment]
Thanks for the feedback, closing issue!
