### ISSUE TITLE
MacOS Compile Domoticz

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#4421]
Compiling domoticz on MacOS

The version you can download is so outdated (2018) and it uses dynamic libraries which are not on my
system.. they are not statically linked to domoticz so the download is useless for all newer systems (and probably older) which does not have the right versions... (like libusb)

Also the wiki is so outdated, that my own instructions I wrote there and the newer one for high sierra are not working ;-)

So I tried to compile it myself... (again :-)

After 6 hours of trying I got it compiled but not linked

These are my steps (error at the end)

--- 

Versions

MacOS Catalina 10.15.7 
Xcode 12.0
Homebrew 2.5.7
Python 3.9 (from brew)
Domoticz 2020.2.0

---

Install instruction hints used from

https://www.domoticz.com/forum/viewtopic.php?f=6&t=31243&p=235967&hilit=macos&sid=1287a04f66f020cf8c24cc4c7d512eb6#p237071
https://www.domoticz.com/wiki/Mac_OSX

---

First installed Xcode

`xcode-select --install`

Install brew

`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Stupid brew lets you wait forever it adds 20 minutes if you do not use

`export HOMEBREW_NO_AUTO_UPDATE=1`

Install packages

```
brew install git
brew install cmake
brew install boost
brew install libusb
brew install libusb-compat
brew install zlib
brew install openssl
brew link openssl --force
brew install python3
brew install lua
brew install node
brew install sqlite3
brew install curl
brew install luarocks
brew install cereal
luarocks install luasocket
```

---

Unknown if this is needed they are mentioned on the forum and the wiki did install them anyway

X11.app, via XQuartz

```
brew install XQuartz
brew install pyenv
pyenv install 3.9-dev
sudo pip3 install gevent msgpack-python python-miio
```

---

This will be the base folder used for all compilation

```
mkdir ~/Coding
cd ~/Coding
```

---

Z-Wave 

```
git clone https://github.com/OpenZWave/open-zwave.git
ln -s open-zwave open-zwave-read-only
cd open-zwave
make
sudo make install
cd ..
```

---

Download domoticz code

`git clone -b development https://github.com/domoticz/domoticz.git`

---

Z-Wave fix for Node.h and node.h

reference https://github.com/domoticz/domoticz/pull/4206 but its not working...

Copy 
`~/Coding/open-zwave/cpp/src/Node.h`

To
`~/Coding/domoticz/hardware/openzwave/control_panel`

Edit 

`~/Coding/domoticz/hardware/openzwave/control_panel/ozwcp.cpp`

Change <Node.h> to "Node.h"

This will fix zwave compilation

---

```
cd ~/Coding
cd domoticz
```

---

Fix openssl

Fix ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib for architecture x86_64

Either add to cmake

```
-DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl@1.1/lib/libssl.dylib 
-DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl@1.1/lib/libcrypto.dylib 
```

or use with the right version this to correct it... (first option is probably better, but I found out too late)

https://gist.github.com/llbbl/c54f44d028d014514d5d837f64e60bac
https://stackoverflow.com/questions/58446253/xcode-11-ld-error-your-binary-is-not-an-allowed-client-of-usr-lib-libcrypto-dy

cmake

either

`cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DPYTHON_INCLUDE_DIR=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.9/Headers -DPYTHON_LIBRARY=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DUSE_STATIC_BOOST=NO -DINCLUDE_LINUX_I2C=NO -DINCLUDE_SPI=NO -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl@1.1/lib/libssl.dylib -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl@1.1/lib/libcrypto.dylib CMakeLists.txt`

or for second fix use

`cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DPYTHON_INCLUDE_DIR=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.9/Headers -DPYTHON_LIBRARY=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DUSE_STATIC_BOOST=NO -DINCLUDE_LINUX_I2C=NO -DINCLUDE_SPI=NO -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include CMakeLists.txt`

---

Mosquitto fix (for xcode 12)  apply after cmake
mosquitto fix is currently not in the main branch but in the fixes branch
See: https://github.com/eclipse/mosquitto/issues/1831

```
cd ~/Coding
git clone -b fixes https://github.com/eclipse/mosquitto
```

Copy

` ~/Coding/mosquitto/lib/mosquitto.c`
To 

`~/Coding/domoticz/extern/mosquitto/lib`

---

Python 3.9 

See: https://src.fedoraproject.org/rpms/domoticz/c/0cb4a4b4734638b8b07177713455611746b74185
and also see https://github.com/domoticz/domoticz/issues/4415

Edit

`/Users/tristan/Coding/domoticz/hardware/plugins/DelayedLink.h`

Add this after the all the #include add

```
#ifndef _Py_DEC_REFTOTAL
#  ifdef Py_REF_DEBUG
#    define _Py_DEC_REFTOTAL _Py_RefTotal--
#  else
#    define _Py_DEC_REFTOTAL
#  endif
#endif
```

---

I have no idea if this is needed:

```
export LDFLAGS=-L/usr/local/opt/openssl/lib
export CPPFLAGS=-I/usr/local/opt/openssl/include
```

---

Compile

`make -j 4`

----

AAARRGHHHHH..... so close :-)

Linking error...

```
[ 53%] Linking CXX executable bin/domoticz
Undefined symbols for architecture x86_64:
  "__Py_Dealloc", referenced from:
      Plugins::DomoticzEventsClear(_object*) in EventsPythonModule.cpp.o
      Plugins::PythonEventsProcessPython(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long long, std::__1::map<unsigned long long, CEventSystem::_tDeviceStatus, std::__1::less<unsigned long long>, std::__1::allocator<std::__1::pair<unsigned long long const, CEventSystem::_tDeviceStatus> > >, std::__1::map<unsigned long long, CEventSystem::_tUserVariable, std::__1::less<unsigned long long>, std::__1::allocator<std::__1::pair<unsigned long long const, CEventSystem::_tUserVariable> > >, int, int) in EventsPythonModule.cpp.o
      Plugins::PDevice_dealloc(Plugins::PDevice*) in EventsPythonDevice.cpp.o
      Plugins::PDevice_new(_typeobject*, _object*, _object*) in EventsPythonDevice.cpp.o
      Plugins::PDevice_init(Plugins::PDevice*, _object*, _object*) in EventsPythonDevice.cpp.o
      Plugins::LogPythonException(Plugins::CPlugin*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Plugins.cpp.o
      Plugins::DomoticzClear(_object*) in Plugins.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

So I am probably stuck with the python 3.9, stuff where they removed macros...

Any hints?

**Comment by ghost** [comment]
Going to try fiddling with
 https://src.fedoraproject.org/rpms/domoticz/blob/0cb4a4b4734638b8b07177713455611746b74185/f/domoticz-python.patch

Maybe that works... 6 hours in ;-) First some offline time...

Will update wiki if succeeded.. (yes first clean vmware, testing) nobody should spend 6 hours trying to compile stuff... :-)
Also any hints in statically linking in the dylib files???

TriXWooD

**Comment by kiddigital** [comment]
I see that your linking is looking for 'architecture x86_64' ? Shouldn't that be something Apple specific (not sure)?

And btw.. try with Python 3.7. There are more issues wth Python 3.9. Or even try first without Python (and Z-wave) to get the main thing compiling ok first.

**Comment by ghost** [comment]
Another 2 hours in... downgrading with brew... %$#....  but... Yes! downgrading to 3.8 worked...

```
brew uninstall python3
pyenv install 3.8-dev  
brew install python@3.8   
brew unlink python@3.8 && brew link --force python@3.8
```


```
cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DPYTHON_INCLUDE_DIR=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.8/Headers -DPYTHON_LIBRARY=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.8/lib/libpython3.8.dylib -DUSE_STATIC_BOOST=NO -DINCLUDE_LINUX_I2C=NO -DINCLUDE_SPI=NO -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include CMakeLists.txt
```

Hope you guys fix the python 3.9 macro issues... 

Extra steps...

Downgrade everything to python 3.8
Also remove the /Users/tristan/Coding/domoticz/hardware/plugins/DelayedLink.h added for version 3.9...
Change the cmake to use 3.8 instead of 3.9

This was a horrible experience...

Will update wiki... (update,... aargghh no, can't login to wiki with forum passwords anymore,... post it on the forum)

**Comment by kiddigital** [comment]
Rebase your dev branch.. a fix for Python 3.9 is there now. Hopefully it now works to compile with 3.9

**Comment by kofec** [comment]
Remember also correct the libs:
@jzapater forgot about it
if (!shared_lib_) shared_lib_ = LoadLibrary("python38_d.dll");
add for version 3.9

**Comment by ghost** [comment]
@kofec 

Would it not be more handy to do as referenced in [src.fedoraproject.org patch](https://src.fedoraproject.org/rpms/domoticz/blob/0cb4a4b4734638b8b07177713455611746b74185/f/domoticz-python.patch)


```
Instead of maintaining a list of all Python versions the Python 3
--
  | standard defines that there MUST be a stable ABI and we can always
  | rely on a "python3.dll" or a "libpython3.so" existing.
```



De first two green lines?
+				if (!shared_lib_) shared_lib_ = LoadLibrary("python.dll");
+				if (!shared_lib_) FindLibrary("python3", true);

Ow well, another hour testing is no so bad, and see how it pans out, I now have a virtual machine for testing...
So I can also test it on a virgin system... keep u informed.

**Comment by FredWst** [comment]
Hi,

here what I use to compile last 12665(missing #include <mach/mach_time.h> in mosquito.c), built on Big Sur.

brew install cmake
brew install boost
brew install libusb
brew install libusb-compat
brew install zlib
brew install openssl
brew install python3
brew install lua
brew install node
brew install cereal
brew install sqlite3
brew install mosquitto
brew install curl
brew install ffmpeg

cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DPYTHON_INCLUDE_DIR=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.9/Headers -DPYTHON_LIBRARY=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DUSE_OPENSSL_STATIC=NO -DUSE_STATIC_BOOST=NO -DINCLUDE_LINUX_I2C=NO -DINCLUDE_SPI=NO CMakeLists.txt


Fred
