### ISSUE TITLE
Domoticz behind NGINX reverse proxy doesn't get Real IP 

### ISSUE THREAD

**Issue by sharp004** [domoticz/domoticz#4423]
Hello,

I'm trying to get the client real IP in the log file domoticz.log. 
My domoticz server is behind a NGINX reverse proxy, which is working great. I also have Domoticz-Google-Assistant (dzga) behind this NGINX reverse proxy too.

Dzga receive the real client ip in the log, but Domoticz receive 127.0.0.1 ip address instead. 
My nginx config is :

```
server {
        listen 443 ssl default_server ;
        listen [::]:443 ssl default_server ;
        server_name <MY-SERVER-NAME> ;

        ssl_certificate <MY-FULLCHAIN> ;
        ssl_certificate_key <MY-PRIVKEY>;
        ssl_dhparam <MY-DHPARAM>;

        set_real_ip_from        127.0.0.0/16;
        real_ip_header          X-Real-IP;
        real_ip_recursive       on;
        proxy_set_header        X-Real-IP               $remote_addr;
        proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for; 
        proxy_set_header        X-Forwarded-Proto       $proxy_x_forwarded_proto;
        proxy_set_header        Host                    $host;
        proxy_set_header        X-Scheme                $scheme;

        ssl on;
        ssl_session_cache  builtin:1000  shared:SSL:10m;
        ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
        ssl_prefer_server_ciphers on;

       location /domoticz/ {
               rewrite ^/domoticz/?(.*) /$1 break;
               proxy_http_version               1.1;
               proxy_read_timeout               90;
               proxy_set_header         Connection              $connection_upgrade;
               add_header                                       X-Frame-Options SAMEORIGIN;
               proxy_pass http://localhost:8080;

        }

        location /assistant {
              rewrite ^/assistant/?(.*) /$1 break;
              proxy_pass http://localhost:3030; #local ipno to dzga
              proxy_read_timeout  90;
        }
}
```

In the dzga's log :
`2020-11-02 11:35:16 - ERROR - Failed login from 80.215.X.X`

In the domoticz's log :
`2020-11-02 11:34:04.237  Error: Failed login attempt from 127.0.0.1 for user 'wxcwxcwxc' !`

Any ideas ?

**Comment by sharp004** [comment]
Ho and of course, I have the lastest version of Domoticz (2020.2)

**Comment by gizmocuz** [comment]
@sharp004 , best to ask on the Forum.
There have been success stories using the following information:

https://www.domoticz.com/wiki/WebServer_Proxy

**Comment by kiddigital** [comment]
> Ho and of course, I have the lastest version of Domoticz (2020.2)

I assume you already have a working setup and it is 'just' the log from Domoticz that does not show the real IP?

Without having looked in the code of Domoticz, it could be that Domoticz own webserver does not look (yet) at any 'real-IP' headers and just uses the client IP it sees. Which is the proxy 😁

**Comment by sharp004** [comment]
> @sharp004 , best to ask on the Forum.
> There have been success stories using the following information:
> 
> https://www.domoticz.com/wiki/WebServer_Proxy

Of course I first tried with the wiki informations :)

> Without having looked in the code of Domoticz, it could be that Domoticz own webserver does not look (yet) at any 'real-IP' headers and just uses the client IP it sees. Which is the proxy 😁

Yes I think it's that, because now I use Caddy for my reverse proxy setup, and it's the same result (domoticz sees ::1 or 127.0.0.1, and DZGA sees the real IP address).

**Comment by gizmocuz** [comment]
@sharp004 , No that is not the case. Sure it get's is able to detect the 'real' IP that connects it's webserver (and yes, that is 127.0.0.1), BUT, if you look in the function "**_cWebemRequestHandler::handle_request_**" you could see what's expected

**Comment by sharp004** [comment]
Ok, it works now ! 
In fact, I had to specify the IP of my reverse proxy in the domoticz setting "RemoteProxyIPs:" 

Thanks @gizmocuz for pointing me the related function.

**Comment by kiddigital** [comment]
@sharp004 , _after_ looking at the code (thx @gizmocuz for the pointer) the current code based can already looks for 'X-Real-IP' or 'X-Forwarded-For' (both case-sensitive) BUT it will only do so when you have entered the IP-address(es) of the Proxy Server(s)! See the 'Systems'-tab in the 'Settings'.

**Comment by gizmocuz** [comment]
@sharp004 , Yes sorry about that, previously this was not needed. But I guess that people could 'spoof' a fake header and this was build in

**Comment by gizmocuz** [comment]
I added this information to the wiki page
