### ISSUE TITLE
Handle Hue external state changes like Toon

### ISSUE THREAD

**Issue by arjanwaard** [domoticz/domoticz#443]
Currently external Hue state changes (via Hue app or Toon) do not change internal Domoticz state. This makes it hard to implement a Blocky based on Hue state changes as it is not consistent. Looks like the way of handling state changes in the Toon code would fix this.

**Comment by gizmocuz** [comment]
Please provide a patch

**Comment by arjanwaard** [comment]
I will try to get something running.

**Comment by arjanwaard** [comment]
Fixed with pull https://github.com/domoticz/domoticz/pull/519
