### ISSUE TITLE
New Domoticz Win10 install addition OpenZWave, nothing in OZWCPL 

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#4437]
Hi,

Tried two Win10 installs and added OpenZWave in Hardware page is working, however OZW Control Panel is empty. And taking a look in Domoticz\Config folder no ozwcache_xxxxxxxxxx.xml config file is created. Except for the Controller I tested to include one Node but still no ozwcache-file was created.

![bild](https://user-images.githubusercontent.com/21274628/98388297-e0736c80-2052-11eb-8242-69c956692cae.png)

![bild](https://user-images.githubusercontent.com/21274628/98388550-334d2400-2053-11eb-9eb8-8394a85dd26b.png)

**Comment by gizmocuz** [comment]
@RicardP , what does the Log say ?

**Comment by RicardP** [comment]
@gizmocuz Everything looks fine in Domoticz own Setup page for ZWave Nodes. However when restarting Domoticz ZWave Nodes config is lost (as no cache file is available).

Log created after Domoticz restart... (Node config are lost now)
 
![bild](https://user-images.githubusercontent.com/21274628/98390141-44973000-2055-11eb-8c53-4a867320b07b.png)

After I made a "Refresh Node Info" on the Door sensor it was identified again... 

![bild](https://user-images.githubusercontent.com/21274628/98390461-aeafd500-2055-11eb-98dd-6c4e265e9f97.png)

**Comment by RicardP** [comment]
@gizmocuz If I can do some error tracking at "user level skill" please let me know :)

**Comment by gizmocuz** [comment]
@RicardP , Do you have 1 ZWave node ? Did you upgrade from the stable/old version?

**Comment by RicardP** [comment]
@gizmocuz Hi, it was a new install with latest beta. I did not continue include more Nodes... My home production system, continuously updated, now on latest beta works fine. I will test a clean install with latest stable as well. It seems being a specific issue when createing a new OZW network.

**Comment by RicardP** [comment]
@gizmocuz I found out it is rights related. I started Domoticz installation as Administrator and then also ran Domoticz application as Administrator. Now when adding OZW feature the cache file was created and everything looks normal. So I again removed the OZW feature and restarted Domoticz as default mode, without Administrator rights, adding OZW failed again.

**Comment by gizmocuz** [comment]
Where did you install Domoticz ? Try installing it in your user folder maybe ?

**Comment by RicardP** [comment]
I installed in default folder "Program (x86)". I personally solved the issue by setting the shortcut to "run as administrator". I did not test install option "Run as Service", as I only needed a run on demand temporary installation. 
Hopefully it could be easily solved in coming win builds.
