### ISSUE TITLE
Latest Domoticz versions virus/malware warning

### ISSUE THREAD

**Issue by Olifant1990** [domoticz/domoticz#4443]
I cannot install the latest beta version of Domoticz (DomoticzSetup_2020_2.12607.exe)

Windows defender blocks it as it should contain a virus (PUA:Win32/Caypnamer.A!ml)

Details here: https://www.virustotal.com/gui/file/9081be8f7db3da688f6d64b6a35506b2990ee9a1a4818d4163936a64e4d81d46/detection

**Comment by gizmocuz** [comment]
Sorry but you should know better then this.
It's the NSSM tool that makes Domoticz a service in Windows, it does not contain a virus, yes it can turn a program into a service

https://nssm.cc/

**Comment by Olifant1990** [comment]
I know how it works, but Domoticz have had multiple false positives in its executable file in the past.
Isn't there something to do about to prevent?
Or just wait for the next build and maybe there is no report anymore?
Just I don't have a clue where this is comming from, this report of defender.

**Comment by gizmocuz** [comment]
This file has been used for years. If people will tell those scanners it does not contain a virus, it might remove the false positive
There is also no newer version of NSSM
My Nod32 does not complain
