### ISSUE TITLE
Fibaro FGSD001 CO Sensor is detected as CO2 sensor

### ISSUE THREAD

**Issue by koenkooi** [domoticz/domoticz#4446]
After updating openzwave to 1.6.1520  and domoticz to 2020.2.12594 I finally get a PPM reading from my Fibaro CO sensor:
<img width="826" alt="Schermafbeelding 2020-11-09 om 10 50 01" src="https://user-images.githubusercontent.com/259525/98525872-5fe28500-2279-11eb-86c2-9222773eb2da.png">

Sadly domoticz thinks it's a CO2 sensor:
<img width="701" alt="Schermafbeelding 2020-11-09 om 10 50 55" src="https://user-images.githubusercontent.com/259525/98526179-c1a2ef00-2279-11eb-86a0-e0939e2efb43.png">

The openzwave control panel does list it as carbon monoxide:
<img width="532" alt="Schermafbeelding 2020-11-09 om 10 51 41" src="https://user-images.githubusercontent.com/259525/98526195-c49ddf80-2279-11eb-8bc7-96312f9f95e3.png">

**Comment by gizmocuz** [comment]
Okey... And both are in Ppm ... only the type name is different
But the value is 0 ?

**Comment by koenkooi** [comment]
Yes, the value is 0. If it's non-zero I need to evacuate the house and call in the people who service the CV-ketel.

**Comment by waltervl** [comment]
Still an issue or already solved?
