### ISSUE TITLE
Compile error on Ubuntu 20.04, 20.10 and Raspbian GNU/Linux 10 (buster)

### ISSUE THREAD

**Issue by aldodemi** [domoticz/domoticz#4447]
Compile error on Ubuntu 20.04, 20.10 and Raspbian GNU/Linux 10 (buster):
UBUNTU:
[ 17%] Building CXX object CMakeFiles/domoticz.dir/main/WebServer.cpp.o
/home/domoticz/domoticz/main/WebServer.cpp: In member function ‘void http::server::CWebServer::HandleCommand(const string&, http::server::WebEmSession&, const http::server::request&, Json::Value&)’:
/home/domoticz/domoticz/main/WebServer.cpp:3938:46: error: passing ‘const CGpioPin’ as ‘this’ argument discards qualifiers [-fpermissive]
 3938 |       root["result"][ii]["idx"] = pin.GetPin();
      |                                              ^
In file included from /home/domoticz/domoticz/main/../hardware/Gpio.h:30,
                 from /home/domoticz/domoticz/main/WebServer.cpp:41:
/home/domoticz/domoticz/main/../hardware/GpioPin.h:38:6: note:   in call to ‘int CGpioPin::GetPin()’
   38 |  int GetPin();
      |      ^~~~~~
/home/domoticz/domoticz/main/WebServer.cpp:3939:49: error: passing ‘const CGpioPin’ as ‘this’ argument discards qualifiers [-fpermissive]
 3939 |       root["result"][ii]["Name"] = pin.ToString();
      |                                                 ^
In file included from /home/domoticz/domoticz/main/../hardware/Gpio.h:30,
                 from /home/domoticz/domoticz/main/WebServer.cpp:41:
/home/domoticz/domoticz/main/../hardware/GpioPin.h:47:14: note:   in call to ‘std::string CGpioPin::ToString()’
   47 |  std::string ToString();
      |              ^~~~~~~~
make[2]: *** [CMakeFiles/domoticz.dir/build.make:519: CMakeFiles/domoticz.dir/main/WebServer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:375: CMakeFiles/domoticz.dir/all] Error 2
make: *** [Makefile:172: all] Error 2

Raspbian:
[ 26%] Building CXX object CMakeFiles/domoticz.dir/main/WebServer.cpp.o
/home/pi/domoticz/main/WebServer.cpp: In member function ‘void http::server::CWebServer::HandleCommand(const string&, http::server::WebEmSession&, const http::server::request&, Json::Value&)’:
/home/pi/domoticz/main/WebServer.cpp:3938:46: error: passing ‘const CGpioPin’ as ‘this’ argument discards qualifiers [-fpermissive]
       root["result"][ii]["idx"] = pin.GetPin();
                                              ^
In file included from /home/pi/domoticz/main/../hardware/Gpio.h:30,
                 from /home/pi/domoticz/main/WebServer.cpp:41:
/home/pi/domoticz/main/../hardware/GpioPin.h:38:6: note:   in call to ‘int CGpioPin::GetPin()’
  int GetPin();
      ^~~~~~
/home/pi/domoticz/main/WebServer.cpp:3939:49: error: passing ‘const CGpioPin’ as ‘this’ argument discards qualifiers [-fpermissive]
       root["result"][ii]["Name"] = pin.ToString();
                                                 ^
In file included from /home/pi/domoticz/main/../hardware/Gpio.h:30,
                 from /home/pi/domoticz/main/WebServer.cpp:41:
/home/pi/domoticz/main/../hardware/GpioPin.h:47:14: note:   in call to ‘std::__cxx11::string CGpioPin::ToString()’
  std::string ToString();
              ^~~~~~~~
make[2]: *** [CMakeFiles/domoticz.dir/build.make:516: CMakeFiles/domoticz.dir/main/WebServer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:372: CMakeFiles/domoticz.dir/all] Error 2
make: *** [Makefile:169: all] Error 2

**Comment by gizmocuz** [comment]
Thanks for reporting. Fixed the issue in the latest code
