### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by Tirguy** [domoticz/domoticz#4450]
Hello

Sorry to post my request here, but i did not know where to ask for that...
It looks that is now impossible to register to the forum : https://www.domoticz.com/forum/ucp.php?mode=register

Does gizmocuz or someone else can resolv it ? 
Thank's
Thierry

**Comment by gizmocuz** [comment]
Just talked with someone that registered, what seems to be your issue, what does not work ?
What error message do you get?

**Comment by Tirguy** [comment]
:o( So i do not understand :-(

I always have the same message : "You have incorrectly sorted the items to the correct list of the confirmation question." whereas i try to sort eatch time the word, but none of my trials have been OK 
I use Firefox last version... I try with Edge, Brave, Chrome... none of them give me an access to correct register
I wondering if my email was ever used : it not seen to be because when i ask to receive my password, i do not receive anything in my email box.
![reg](https://user-images.githubusercontent.com/24454798/98687219-c5ae3a00-2369-11eb-9642-7ab162effa49.png)


I have tried to arrange the different items differently, but it never works.
I do not understand what happening ;-(

**Comment by rwaaren** [comment]
Added your userid and send you an Email. You need to confirm your account

**Comment by Tirguy** [comment]
Thank's a lot... It works

**Comment by gizmocuz** [comment]
Looking at the picture above you swapped Correct and Incorrect
@rwaaren , I think it's best if we let users solve the small puzzle instead of adding users

**Comment by rwaaren** [comment]
@gizmocuz I agree. In this case I just wanted to ensure that no other issue was preventing Tirguy to register.

**Comment by Tirguy** [comment]
@gizmocuz 
Yes in this example it is not swapped correct... but i try other solutions...plenty of solutions with this captcha (Nota : it's always the same that appear) and none was agree with solution.  May be another sort of captcha should be better ? 
Thank's again for my register to @rwaaren

**Comment by gizmocuz** [comment]
@Tirguy , you did not solve the 'puzzle' correctly in the above screenshot, I hope you see this ?
