### ISSUE TITLE
temperature graph log not working in machinon theme since the beta 2020.2 ( build 12554)

### ISSUE THREAD

**Issue by kitopopo** [domoticz/domoticz#4453]
Dear friends,

No graphic log of temperature works for me in the machinon theme since the update beta 2020.2 ( build 12554).

I have seen that you have released two new updates without correcting the problem of the temperature graphs of all the sensors. I do not understand how they can leave all users who have updated without being able to use any the graphics log.

I have tried to regress to version 2020.2 (build 12497) and the graphic log works correctly. 

Please would you be so kind to solve the problem ?

@gizmocuz  know that we are all without any graph log?

Thanks in advanced

**Comment by rwaaren** [comment]
@kiopopo 
We are not all without any graph log. 

If you use the external machineon theme you will face this issue but not in any of the internal themes.
This issue was already posted on the machinon github as you are already aware because you commented on that issue and it must be solved there.

**Comment by kitopopo** [comment]
Yes, i understand. But the problem appeared after a domoticz update, since the update beta 2020.2 ( build 12554). 
domoticz is involved with the problem due to the problem had appeared after a domoticz update, i think. anyway thanks, we'll wait patiently. a cordial greeting

**Comment by gizmocuz** [comment]
@kitopopo , as MachineOn is a external developed theme, we have no influence about what is or what is not supported
The recent Gui changes are for the better and maybe when the developer of MachineOn has time, he/she will make some changes

**Comment by kitopopo** [comment]
> @kitopopo , as MachineOn is a external developed theme, we have no influence about what is or what is not supported
> The recent Gui changes are for the better and maybe when the developer of MachineOn has time, he/she will make some changes

Thanks @gizmocuz , you have been very kind with your answer. a cordial greeting and thanks

**Comment by michahagg** [comment]
> > @kitopopo , as MachineOn is a external developed theme, we have no influence about what is or what is not supported
> > The recent Gui changes are for the better and maybe when the developer of MachineOn has time, he/she will make some changes
> 
> Thanks @gizmocuz , you have been very kind with your answer. a cordial greeting and thanks

Hi @kitopopo and @gizmocuz any issues might well be caused by self-closing html tags. If you have the ability to modify the code, replace them with an open and separate closing tag. Otherwise I can have a look at it at some later time.

Regards, Micha

**Comment by michahagg** [comment]
@kitopopo I made a small PR in Machinon. That should make things work again.

**Comment by kitopopo** [comment]
> @kitopopo I made a small PR in Machinon. That should make things work again.

Dear @michahagg , 


I have tried to update machinon but it does not find new updates, I have tried from windows 10 from chrome and firefox and neither of the two browsers shows the graphics, everything appears empty.

Thanks, best regards

**Comment by michahagg** [comment]
Hi, the Pull Request must be merged first before it is available for pulling (updating). Keep an eye on the GitHub repo!

**Comment by kitopopo** [comment]
> Hola, la solicitud de extracción debe fusionarse primero antes de que esté disponible para su extracción (actualización). ¡Esté atento al repositorio de GitHub!

thanks @michahagg . Regards

**Comment by th3sniper86** [comment]
@michahagg Could you maybe do the same trick for the widely used ThinkTheme? 😉

https://github.com/DewGew/Domoticz-ThinkTheme

**Comment by kitopopo** [comment]
Dear @michahagg , 

two days after any update appears and no changes in github, It is normal?

thanks in advanced. Best regards

**Comment by gizmocuz** [comment]
@kitopopo , For raspberry it's a manual process

**Comment by kitopopo** [comment]
> @kitopopo , For raspberry it's a manual process

thanks for your reply @gizmocuz .

and what is this manual process to perform? where is it explained? is there a tutorial? I need to use my graphics. Thanks in advance. Best regards

**Comment by gizmocuz** [comment]
@kitopopo , It means I have to manually build the raspberry (Arm 32/64) updates
They are building at the moment, and should be available within an hour

**Comment by kitopopo** [comment]
> @kitopopo , significa que tengo que construir manualmente las actualizaciones de frambuesa (Arm 32/64) que
> están construyendo en este momento, y deberían estar disponibles en una hora

Ohh yeah @gizmocuz , I understand., 
you calm, do it when you can, there is no rush. Thank you very much, you are the best. Best regards

**Comment by kitopopo** [comment]
Dear friends,

A week later we still cannot use the graphics in domoticz with the machinon theme, any news? no changes in github and some updates in domoticz but the problem is not solved.


thank in advanced

**Comment by gizmocuz** [comment]
@kitopopo , I think you have to create a issue on another github repo (MachineOn)

**Comment by kitopopo** [comment]
@gizmocuz The issue is already created 9 days ago by someone else. nobody solves the problem. thank you anyway. Best regards

**Comment by EdddieN** [comment]
Hello @kitopopo 

I think this theme is no longer developed or supported, as gizmocuz said, the main developers that were maintaining it have moved on. 

This was the original repo: https://github.com/EdddieN/machinon-domoticz_theme wich was moved later one here: https://github.com/domoticz/Machinon but even if it is within the domoticz repo, it is maintained by users when they can or know how to. 

If anyone is interested to work on it, please use this repo: https://github.com/domoticz/Machinon

**Comment by kitopopo** [comment]
Hi @EdddieN . thanks for your reply.  

My question is the following, if this theme is abandoned because the developers have gone ahead, @gizmocuz  and his collaborators could not pick up the theme and include it as another internal theme of domoticz? This theme is used by many users and from my point of view much better than the original. The original is too old and has hardly ever received any updates. I am speaking at all times from my point of view. I would like to make it clear that it is only an idea or suggestion, I am nobody to decide on domoticz. Here the decisions are made by @gizmocuz . He is the creator.  kind regards.

**Comment by kitopopo** [comment]
Dear @EdddieN ,


Thank you very much for the machinon update, now the graphics work again, you have been very kind, I will test them carefully. A cordial greeting
