### ISSUE TITLE
Crash Plugin_ASIO

### ISSUE THREAD

**Issue by jipite** [domoticz/domoticz#4457]
Hello

I have this error in domoticz after few minutes : Error: Domoticz(pid:22807, tid:22838('Plugin_ASIO')) received fatal signal 11 (Segmentation fault).
Can you give a solution please ?

Bye

**Comment by gizmocuz** [comment]
This seems to come from the python plugin system. Are you using python plugins ? Could you check the following:
- Disable all python plugins... does this solve the problem ? Enable them one by one to see if the error stays away or find out which plugin is causing this problem
- Disable the plugin system from the settings page, this should silence the error

When you report a issue here, you where presented with a guideline which you did not follow, please provide at least your Domoticz version

**Comment by jipite** [comment]
Hello

Sorry
My version is 2020.2 12629 (beta version)
I will try your solution
Thanks

Bye

**Comment by jipite** [comment]
Hello

I have found MQTT Client Gateway with LAN interface crashes Domoticz
What i have done wrong ?

Bye

**Comment by gizmocuz** [comment]
Not sure... that's not python related. Maybe it's a device that sends a wrongly message to MQTT ?
(I'm also using MQTT)
