### ISSUE TITLE
Viewing Log graphs for temperature devices

### ISSUE THREAD

**Issue by brucemiranda** [domoticz/domoticz#4459]
When you click the Log button on a temperature device the first chart is called "24 hours", yet there is now a new filter called "3d". However clicking 3d gives you the same information as 1d.
When you use any of the new filters, the Reset button should appear. But it doesn't appear when 3d and 1d are selected.
None of these new filters are displayed in chart view Full screen mode, which is where they are most useful.
Lastly when you choose the menu, Show in full screen and you exit from full screen, the entire menu option is no longer displayed.

**Comment by brucemiranda** [comment]
Could be linked to the PR 

https://github.com/domoticz/domoticz/pull/4382

**Comment by rwaaren** [comment]
> When you click the Log button on a temperature device the first chart is called "24 hours", yet there is now a new filter called "3d". However clicking 3d gives you the same information as 1d.
> When you use any of the new filters, the Reset button should appear. But it doesn't appear when 3d and 1d are selected.
> None of these new filters are displayed in chart view Full screen mode, which is where they are most useful.
> Lastly when you choose the menu, Show in full screen and you exit from full screen, the entire menu option is no longer displayed.

Title of the first chart depends on the setting for Short Log Sensors: (mine is set at 5 days) 
I cannot replicate these issues in build 12626 or build 12639 

![initial](https://user-images.githubusercontent.com/24454798/99117306-c65b0080-25f5-11eb-89e7-e43b4855852d.png)
![1d](https://user-images.githubusercontent.com/24454798/99117313-c824c400-25f5-11eb-9528-17df1a54446e.png)
![3d](https://user-images.githubusercontent.com/24454798/99117321-cb1fb480-25f5-11eb-8a9b-dfeaffd77e41.png)

**Comment by brucemiranda** [comment]
Version: 2020.2 (build 12639) It's still there unfortunately. 

![image](https://user-images.githubusercontent.com/7365852/99131940-6a4fa680-260c-11eb-9d1d-f4dc1fb9015f.png)
![image](https://user-images.githubusercontent.com/7365852/99131978-8bb09280-260c-11eb-9533-e64e3596344f.png)
![image](https://user-images.githubusercontent.com/7365852/99132008-b00c6f00-260c-11eb-873e-0a68adb2eced.png)
![image](https://user-images.githubusercontent.com/7365852/99132055-daf6c300-260c-11eb-9aeb-701c1f21f9d7.png)

**Comment by rwaaren** [comment]
@brucemiranda 
Seems to be related to the available data. Can you set your short log sensors data setting to 3 or 5 days  and wait for this data to fill the short log sensor tables (Temperature, Counter, Percentage, etc..)  ?

**Comment by brucemiranda** [comment]
Encountered another bug in trying to set the Short Sensor to 3 days. It just logs you off and you are presented with a Domoticz login screen, which I have never seen!

**Comment by rwaaren** [comment]
This last issue is not reproducible on my systems. 
Do you see anything in the log?
If you already cleared cache and appcache (different things) it might be worthwhile to check your database.
