### ISSUE TITLE
LUA and DZvents current last update not accessible

### ISSUE THREAD

**Issue by bbrowaros** [domoticz/domoticz#4466]
INFO
Domoticz version: 2020.2 (build 12624) (not sure if previous versions are also affected) 
HW: raspberry pi 3B+
OS: rasbian (PRETTY_NAME="Raspbian GNU/Linux 10 (buster)")
Kerenel version: 5.4.72-v7+

Issue description: 
New added device zigbee2mqtt (door sensor) is updating the device "Last update" field which is visible on device information on page and zigbe2mqtt plugin, however when accessing this value via lua or dzvents the result is previous update time (not current)

**Comment by Bartekn86** [comment]
1. can not enter configuration -> devices
2, there is no ok button when changing names in zigbee2mqtt bookmark ?

**Comment by bbrowaros** [comment]
Not sure if I get your update @Bartekn86. The device is correctly added to domoticz system and is updated correctly. This is just a problem when gathering data via lua or dzevents scripts. The lastupdated.time is showing previous update not the current one. If we open the sensor at 9:20 and then close it at 9:25. The page is showing last update at 9:25 but when you in script request lastupdated.time you get 9:20. I'm further testing this as this caused my script logic to fail. I've needed to implement a user variable to workaround this. Currently I'm looking conditions when the update is happening. Also during the tests I've notice that this device reports On/Off instead Open/Closed. Note I've go a second sensor this type added while ago and all looks good.

**Comment by rwaaren** [comment]
> The lastupdated.time is showing previous update not the current one. If we open the sensor at 9:20 and then close it at 9:25. The page is showing last update at 9:25 but when you in script request lastupdated.time you get 9:20. 

This is as designed 
When the script is triggered by the device update you already know when it is updated (it is updated now) 
The lastupdate value is updated after the script is triggered.

The lastupdate value you see on the device tab is in fact the lastSeen value

**Comment by bbrowaros** [comment]
@rwaaren are you sure about it? Note the script is not updating the sensor. Sensor device is getting updated from Mqtt brooker. So when the sensor is updated at 9:25 and we probe the lastupdate.time at 9:30  via script which time you expect to get 9:20 or 9:25?  Till now all my scripts where using this method to detect last change of sensor state with success, this one is failing.

**Comment by rwaaren** [comment]
> @rwaaren are you sure about it? 

Yes but my comment is true for scripts triggered by the device update. If you use a time based script or a script triggered by a different device and probe for the lastUpdate time  it should report the real lastUpdate time

This is how it should work by design

device A is updated at 09:25
MQTT updates device A at 09:30 -> device A is the trigger of script 1 -> script 1 report lastUpdate of device A as 09:25
Device B is updated at 09:30:02 -> device B is the trigger of script 2 -> script 2 report lastUpdate of device A as 09:30 
At 09:31 a time triggered script 3 is activated -> script 3 report lastUpdate of device A as 09:30

And please note that there can be a difference between lastSeen and lastUpdate

**Comment by Bartekn86** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/69695376/99187931-c247f380-2759-11eb-92d7-3a9ca2dee17d.png)
Dont have "ok" button :-)

**Comment by Bartekn86** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/69695376/99187979-f7ecdc80-2759-11eb-88a7-a3eef073601a.png)
lost list

**Comment by bbrowaros** [comment]
@rwaaren ok but look at this situation: 

I've got device zigbee2mqtt which was update according to screens: 

![screen_okno](https://user-images.githubusercontent.com/24865361/99188093-76497e80-275a-11eb-89bf-735c8ef15627.JPG)
![screen_okno_2](https://user-images.githubusercontent.com/24865361/99188096-777aab80-275a-11eb-9da4-a2bf5328bdce.JPG)

but when I execute following code: 

`return {
    on = {
      timer = {
         'every minute'
      }
    },
    execute = function(domoticz, timer)
      domoticz.log('The rule that triggered the event was: ' .. timer.trigger)
      domoticz.log('Device updated: '..domoticz.devices('sypialnia_okno').lastUpdate.time)
    end
}`

I got this answer: 
`
2020-11-15 15:47:00.177 Status: dzVents: Info: ------ Start internal script: setpoint_test_script:, trigger: "every minute"
2020-11-15 15:47:00.177 Status: dzVents: Info: The rule that triggered the event was: every minute
2020-11-15 15:47:00.197 Status: dzVents: Info: Device updated: 10:11  <----
2020-11-15 15:47:00.198 Status: dzVents: Info: ------ Finished setpoint_test_script
`

And I know that the window was opened at 10:11 and closed at 15:31 :) so I don't think that this is normal as in other sensor this is reported correctly (the same time added prior updates). 
Ether I've got some issue with db or there is some nasty stuff going in background. 


EDITED

Just notice what you mention that I'm looking at last seen field, please close the subject. Did not know that there is actually two fields for this. I'll need to modify my scripts to account this. Sorry

**Comment by rwaaren** [comment]
> Dont have "ok" button :-)

Please use the forum for this type of issues / questions and certainly do not confuse other issues with your problems. 
Have you tried to clear cache and appcache (different things) ?

**Comment by bbrowaros** [comment]
@Bartekn86 

check if you have a "allow new devices" enabled in config page of the domoticz. Had similar same problems initially. Also check this on private mode maybe your web browser is doing some nasty stuff.

**Comment by bbrowaros** [comment]
LAST SEEN != LAST UPDATED

**Comment by rwaaren** [comment]
> domoticz.devices('sypialnia_okno').lastUpdate.time

This syntax is not supported.
You probably want something like 
`domoticz.devices('sypialnia_okno').lastUpdate.rawTime
`

**Comment by Bartekn86** [comment]
> check if you have a "allow new devices" enabled in config page of the domoticz. Had similar same problems initially. Also check this on private mode maybe your web browser is doing some nasty stuff.

i have/haved enable i do not change nothing, after update to beta that do not want to work anymore

**Comment by Bartekn86** [comment]
> Please use the forum for this type of issues / questions and certainly do not confuse other issues with your problems. 
> Have you tried to clear cache and appcache (different things) ?

i cleared cache, even reinstall rasp OS with all things before i wrote that
its seems to update to beta remove button, do not know where to ask to repair/ undo changes made in this release
thank you

edit:
 ./updarelease crash domoticz,  it is not possible to back to previous release 
Could you help please ?

**Comment by bbrowaros** [comment]
@Bartekn86 using script directly from domoticz won't create a copy of currently running instance. It will update the release. I had similar issue so I'm not using the web update method or the script directly but I've created a simple script to backup the directory before issuing updaterelease script from domoticz. 

You can download stable version from here: 
https://github.com/domoticz/domoticz/releases

or perform a git clone and compile the previous version using this instructions: 
https://www.domoticz.com/wiki/Build_Domoticz_from_source

however before you start  changing anything I would recommend to copy current version of domoticz and in different place perform additional  copy the domoticz.db file which holds all your data. 

This issue is not related  and as stated this bug is closed. If you wish I can assist over a private messages or via e-mail however as stated here this is not the correct place to go forward with this. This will confuse only the thread.

**Comment by Bartekn86** [comment]
thanks for explain, ill try myself to build. Meybe its good oportunity to make updater more "human"
