### ISSUE TITLE
Unsigned INT give huge current usage with Envoy

### ISSUE THREAD

**Issue by Tuurtje** [domoticz/domoticz#4469]
Hi there,

When the inverters are in the powering on or powering down state the production wNow is negative in the production.json. Since the code is using a unsigned INT it overflows and gives huge current usage of 2^32 Watt.

I'm not a C++ expert, but changing the flowing code in the EnphaseAPI.cpp should do the trick. I have tested it.

m_p1power.usagecurrent = musage;
to 
m_p1power.usagecurrent = std::max(musage,0);

**Comment by rwaaren** [comment]
Thx for reporting and the tested fix !
