### ISSUE TITLE
Forum issue

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4471]
(Also reported via Slack)

Something seems to be wrong on the forum after the extended outages and SQL issues earlier today. 

I cannot reply with [quote] to public and not at all to private messages. Also some buttons (PM, logout, etc. are missing) 
Tried various browsers and incognito mode but no difference.

Screen when I try to reply using quote

![image](https://user-images.githubusercontent.com/24454798/99301159-d5d48680-284d-11eb-862e-b9d81fd5ceb2.png)

**Comment by gizmocuz** [comment]
Server needed to be upgraded to Ubuntu 20.04 LTS and this went together with all installed packages as well
I just checked the databases used and all are fine
PHP cgi/fpm has been upgraded from 7.2 to 7.4 as well
I probably have to upgrade phpBB now as well.... 
Maybe best to take the board offline until it's all updated and working again...

**Comment by gizmocuz** [comment]
Taken the Forum offline for the moment

**Comment by rwaaren** [comment]
Thx for the update. Sounds like a massive amount of work!

**Comment by rwaaren** [comment]
Forum up and running again. Thx for the quick action !

**Comment by gizmocuz** [comment]
Almost done... needed to upgrade some extensions as well, and patch another.
Need to the style changes again, will do so on 1.5 hours
There is now a functional forum... but not ready yet !
Let you know when it's ready

**Comment by gizmocuz** [comment]
Okey, I think we're back in business, site might be a little bit slower during the next 4 hours as the caching needs to build up

**Comment by RicardP** [comment]
@gizmocuz Could the annoying 3 letter rejection be fixed as well? :)

_"The following words in your search query were ignored because they are too common words: KNX.
You must specify at least one word to search for. Each word must consist of at least 4 characters and must not contain more than 84 characters excluding wildcards."_

**Comment by gizmocuz** [comment]
@RicardP , True, but, imagine all those indexes/data that needs to be created to support 3 letter words
I do understand why you ask...

**Comment by RicardP** [comment]
I cannot see it would be such a big issue today, in a relatively small database, try google three letters... no problem :)

**Comment by gizmocuz** [comment]
@RicardP , the Forum's database and folder is not 'small'

**Comment by RicardP** [comment]
Size is relative… but ok I shall stop nagging about it :) 
The work around I learned is to use google i.e. “Domoticz knx”.

Cheers!

**Comment by RicardP** [comment]
Size is relative… but ok I shall stop nagging about it :) 

 

The work around I learned is to use google i.e. “Domoticz knx”.

 

Cheers!

 

 

Från: gizmocuz <notifications@github.com> 
Skickat: den 17 november 2020 16:06
Till: domoticz/domoticz <domoticz@noreply.github.com>
Kopia: Ricard Petersson <ricard.petersson@antennlaget.se>; Mention <mention@noreply.github.com>
Ämne: Re: [domoticz/domoticz] Forum issue (#4471)

 

@RicardP <https://github.com/RicardP>  , the Forum's database and folder is not 'small'

**Comment by dannybloe** [comment]
I totally agree with Ricard here. The 3-character limit for phpBB boards is archaic and totally unnecessary and the results of terrible indexing architecture choices. So many times I have tried to search something on the forum and had to resort to using Google because some idiot thinks I cannot search for `sql` for instance or `off`. Any modern indexer such as lucene has totally no problem with this.

**Comment by gizmocuz** [comment]
@dannybloe , so do I, but is phpBB/MySQL using lucene ?

**Comment by kiddigital** [comment]
Nope.. just sql % wildcard search as far as I know...

**Comment by gizmocuz** [comment]
Hmmmz then for the time being I leave this at 4...
