### ISSUE TITLE
scenes timers view doesn't work

### ISSUE THREAD

**Issue by danidask** [domoticz/domoticz#4472]
Domoticz Version: 2020.2 (build 12670)
Platform: Raspberry Pi 3B+
Os:  Raspbian 10 (buster)

Clicking a timers button inside any scene or group, leads to this view
![Screenshot](https://user-images.githubusercontent.com/9405129/99430105-2e1c8e80-2909-11eb-9356-42c0ddd0f403.png)

**Comment by rwaaren** [comment]
Please clear browser cache and appcache (different things)  before reporting (you will see the expected screen after having done that) 
And please use the forum for this kind of issues.

![image](https://user-images.githubusercontent.com/24454798/99434615-47c0d480-290f-11eb-9926-6b4f73df80a7.png)

**Comment by gizmocuz** [comment]
@danidask , When you created the issue, you where presented with some issue guidelines where it clearly also stated:

Clear your browser cache + AppCache (two different things!!)
