### ISSUE TITLE
Allow to have a logging value per hardware

### ISSUE THREAD

**Issue by Xorfor** [domoticz/domoticz#4478]
If I take a look at my Domoticz log, I see a lot of log lines from 'standard hardware' which are not relevant for me, eg.:

...
2020-11-20 23:48:27.371 (OpenZWave USB) Usage (P1 - Totaal - Power)
2020-11-20 23:48:27.383 (OpenZWave USB) General/kWh (P1 - Totaal - Energy)
2020-11-20 23:48:27.666 (OpenZWave USB) Usage (P1 - Laag - Power)
2020-11-20 23:48:27.677 (OpenZWave USB) General/kWh (P1 - Laag - Energy)
2020-11-20 23:48:34.382 (OpenZWave USB) Usage (P1 - Totaal - Power)
2020-11-20 23:48:34.392 (OpenZWave USB) General/kWh (P1 - Totaal - Energy)
2020-11-20 23:48:34.677 (OpenZWave USB) Usage (P1 - Laag - Power)
2020-11-20 23:48:34.687 (OpenZWave USB) General/kWh (P1 - Laag - Energy)
2020-11-20 23:48:35.706 (OpenZWave USB) Lux (Motion 1 - Illuminance)
...
, or
...
2020-11-20 23:47:36.522 (De Grote Geert) General/kWh (De Grote Geert - Energy)
2020-11-20 23:47:36.531 (De Grote Geert) General/Percentage (Wind PowerRel)
2020-11-20 23:47:36.538 (De Grote Geert) General/Fan (Wind RPM)
2020-11-20 23:47:36.546 (De Grote Geert) Wind (Wind)
2020-11-20 23:47:36.552 (De Grote Geert) General/Custom Sensor (Wind Diameter)
...
If there are no problems, no log lines should be generated!
A Python plugin gives me the possibility to log the debug information by the Debug setting, which is great! I like to have this for ALL the hardware!
An advantage is that this will keep the log clean (no log lines if required) and gives the end users a better and easier tool to give relevant debug information in case of problems.

**Comment by kiddigital** [comment]
Please post these requests at the forum under 'suggestions'. Currently Domoticz log screen already has separate tabs for this where you can see only the errors, etc.

**Comment by gizmocuz** [comment]
You can "filter" in the log screen, maybe it could be better... but if you use the right words you filter down to see only the messages you want to see
You can also view just the 'status' or the 'errors' in this screen
This should help you 'debug' some issues
Otherwise , when you're using for instance a raspberry pi, just use the commands 'tail -f' and 'awk' and you can make yourself the perfect realtime filter

**Comment by jgaalen** [comment]
I don't agree just filtering with awk / grep / tail whatever is a good solution. Many hardware implementations just swamp the log for no reason and you have no option to just not log it. For example, the P1SmartMeter is insane and I do not want it to fill my logs with info messages. Good idea would be an option in the hardware settings to select if you want to log info messages

**Comment by gizmocuz** [comment]
@jgaalen , the log should also be internal, the reason to output it to disk is only made for debug purposes
once your done with debugging you should disable this

**Comment by jgaalen** [comment]
Then I think I'm missing how to configure it properly. There is a tab 'Log/History', which doesn't makes sense to me (days set to 3, but I can only see the last few minutes in the log in domoticz gui). Then in the 'Other' settings section, there are some specific log settings as well. Disabling all, still gives me logs including debug logs. Can't find a good way to select the log level I want.
But still, the feature requests stay. It's great to have a way to disable logs for specific hardware. The P1SmartMeter is swamping me log for irrelevant data and no way to exclude this. There's a whole lot to improve on the 'logging section' I think. My personal preferred log situation would be:
- Updates of all values (timestamp, device, old -> new value)
- Triggered event (timestamp, event name, with values used)

Not sure how to achieve this with the current options.

**Comment by gizmocuz** [comment]
What is it that you are trying to debug ?

**Comment by jgaalen** [comment]
Nothing in particular, just why you log in general, to analyse after something odd happens. But some (hardware) logs always seem irrelevant, and you want to disable those logs, or set the logs to a different log level (ie errors only).
