### ISSUE TITLE
Strange user in device log

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#4480]
I am using version 2020.2 build 12690 and notice that on a Zigbee device (PIR) the user is Motherboard and my Zwave hardware stick and RemoteDomoticz.
Those device have nothing in common with that Zigbee device.
I think this is a bug.

**Comment by gizmocuz** [comment]
Working on it...

**Comment by gizmocuz** [comment]
I hope beta 12697 will do a much better job, could you verify ?

**Comment by SargonofAssyria** [comment]
Yes, it works! Tnx.
