### ISSUE TITLE
Build 12693 and 12694 give segmentation fault

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4481]
[See forum topic](https://www.domoticz.com/forum/viewtopic.php?p=261566#p261566)

**Comment by gizmocuz** [comment]
whoops, made stupid mistake here.
Fixed (probably, 99% sure), but it's going to take ~1 hour before the new beta versions are available

**Comment by gizmocuz** [comment]
Beta 12697 should solve this issue

**Comment by rwaaren** [comment]
Thx !!
