### ISSUE TITLE
Timers broken in scenes

### ISSUE THREAD

**Issue by nilsher** [domoticz/domoticz#4482]
I couldn't find an issue on this on github so I create the issue here.
Multiple ppl experience the same thing so I guess it should be an issue here. 
Seems to happen with different versions aswell according to forum thread.

platform raspberry pi with razberry
version 2020.2

Reference forum:
https://www.domoticz.com/forum/viewtopic.php?f=6&t=34637&p=261547#p261547
https://www.domoticz.com/forum/viewtopic.php?f=6&t=27723&p=261550#p261550

when setting timers directly on scenes the timers are never being run.
Have tried different timers and changeing from everyday to selected days.

However when doing blockly diagrams the timers works fine.

I can not see anything special in logfile.

**Comment by gizmocuz** [comment]
Is this also with the beta version?

**Comment by rwaaren** [comment]
> Is this also with the beta version?

No, beta is OK. (have not noticed it on stable either but have not been on stable very long)

**Comment by gizmocuz** [comment]
Just checked, on beta no issues
@nilsher , could you very it's working as it should on the beta version ?
I find it strange that it does not work on the stable either

**Comment by nilskivra** [comment]
Closing this,
on my side it was a mistake. I belived that location was picked up from host os timezone.

When setting x,y coords in settings all worked.

Perhaps some error message should be given when trying to use timers when location is not set.

**Comment by nilsher** [comment]
Close this,
on my side it was a mistake. I belived that location was picked up from host os timezone.

When setting x,y coords in settings all worked.

Perhaps some error message should be given when trying to use timers when location is not set.

**Comment by gizmocuz** [comment]
@nilsher , I think when you go to the settings page and change something, and the location is not set, you get a message ?
But it should be one of the first things you should configure

**Comment by gizmocuz** [comment]
(And a password for when connecting remotly)

**Comment by nilsher** [comment]
Well I wouldnt dare expose it without a vpn tunnel :)

So maybe that was the problem that I didn't set a password ;)
