### ISSUE TITLE
adding onview/rstp support

### ISSUE THREAD

**Issue by Bartekn86** [domoticz/domoticz#4483]
hi, 
are any option to integrate support for onview/rstp camera  ?  mjpeg is very old and no so effective than current solutions

**Comment by kiddigital** [comment]
Please ask these questions on the forum. See the suggestions section.

**Comment by Bartekn86** [comment]
thank you

**Comment by gizmocuz** [comment]
We could add RTSP support for just displaying the camera in the webserver.
But not for capturing a thumbnail, or when you login remotely
For this to work, we need a kind of proxy
We do not use mjpeg, we just the snapshot url from the camera to capture a jpeg and display this (at xx frames/second)
Biggest issue, when your camera has IP 192.168.0.10, and you are going to the Domoticz web interface from remote (like you login to 80.81.82.83), then you can not see the (rtsp) stream from 192.168.0.10 as this is on your local network
(hence we need a kind of proxy)
(If you use VPN it will work as you login to your local network)
Still if you want the system to make a snapshot when someone rings your doorbell and email this to you, we need to capture a frame from this h264/h265 rtsp stream
It seems to be able to convert RTSP streams to mjpeg via ffmpeg (https://github.com/eroji/rtsp2mjpg)

**Comment by Bartekn86** [comment]
Hi, 
Thanks for replay, 
The viewing from the camera is what would be cool I think not only for me, nothing else is needed.  So if youre able to add supoort, ill be really grateful
