### ISSUE TITLE
Very large sValue in Preferences

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4484]
Reported on the forum a couple of times,  some records of the preferences table seem vulnerable to corruption. 
After investigation it turned out they contain a very large string in the sValue field causing instabilities / crashes. 
@gizmocuz : I OK with you I could create a PR which adds a check / correction / log message if this large sValue in Preferences is recognized at domoticz startup. 
I am aware that it would not be a solution but it might prevent some user frustration until someone finds a root cause.

forum posts:
https://www.domoticz.com/forum/viewtopic.php?p=261712#p261712

https://www.domoticz.com/forum/viewtopic.php?p=254753#p254753

https://www.domoticz.com/forum/viewtopic.php?p=247369#p247369

**Comment by gizmocuz** [comment]
Yes no problem. But indeed this should not happen.
Is it also only this key ? (HTTPPostContentType), If yes, we better check for the length in SetupController.js as well ?

**Comment by rwaaren** [comment]
> Is it also only this key ? (HTTPPostContentType)? 
No saw it in other keys as well. Will have a look if I can add an extra check in SetupController.js

**Comment by gizmocuz** [comment]
But there must be a reason for this... are those users using another theme maybe ?

**Comment by rwaaren** [comment]
Don't know. Will ask now to these users

**Comment by rwaaren** [comment]
#4488 ready for review

**Comment by rwaaren** [comment]
> But there must be a reason for this... are those users using another theme maybe ?

Confirmed that issue occurred on default theme

**Comment by gizmocuz** [comment]
Very Weird, but good there is a patch now

**Comment by rwaaren** [comment]
Will reopen the issue when / if reports received on the forum will point in the direction of a root cause.

**Comment by alcor93** [comment]
Hello, I just got  Error: Preferences: sValue of Key HTTPPostContentType has an extreme size. Please report on the forum. What to do ? thx

**Comment by rwaaren** [comment]
Please report on the forum. 
When you see this message, domoticz recognized an entry in the settings table ('Preferences') with an unexpected large svalue size in the record with key HTTPPostContentType. The svalue is  automatically emptied to protect domoticz from crashing.
If you have a backup it might help finding a root cause if you could report the size and content of this record.
