### ISSUE TITLE
DSB09104 wrong display

### ISSUE THREAD

**Issue by chatainsim** [domoticz/domoticz#4486]
Hello,
I'm not sure if it's a Domoticz or OpenZwave issue but I have a DSB09104 energy meter from Aeotec.
And in the configuration page, value 1. Country Voltage always stay on 120v.
I've contacted the Aeotec support and give me some hit.

Using Zensys Tools, I was able to change the value to 240.
Using this tool to get parameter 1 value:
```
04:11:12.256: Completed: 030 - COMMAND_CLASS_CONFIGURATION.CONFIGURATION_GET, data: 01
04:11:12.308: Received: 030 - COMMAND_CLASS_CONFIGURATION.CONFIGURATION_REPORT, data: 01 02 00 F0 00 00
```

But in Domoticz it's still on 120.
![image](https://user-images.githubusercontent.com/1167931/100082891-12edd980-2e49-11eb-9818-950c9d4c8761.png)

How can I check if it's related to Domoticz or Open-Zwave ?

Thank you.
Regards,

**Comment by gizmocuz** [comment]
@chatainsim , have a look in the ZWave Control Panel, and you could try to use other software that uses openzwave

**Comment by chatainsim** [comment]
Hi @gizmocuz found the same value in openzwave control panel:
![image](https://user-images.githubusercontent.com/1167931/100113743-f1a0e380-2e70-11eb-91d7-fa6e9780b08f.png)
So the I will check with the openzwave community.
Thank you.
