### ISSUE TITLE
Dimmer control looses level ruler after changing pictogram

### ISSUE THREAD

**Issue by ridderr** [domoticz/domoticz#4489]
I have a virtual devices which is configured as a dimmer (used to control the window foil).

After changing the pictogram to a custom pictogram (blinds) the level ruler is not displayed anymore in the roomplan (see picture). Therefor I'm not able to change the level of the dimmer via the roomplan.

Version: 2020.2 (build 12689)
Build Hash: 13b9181b2-modified
Compile Date: 2020-11-19 11:13:54
dzVents Version: 3.0.16
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

![dimmer-missing-level-control](https://user-images.githubusercontent.com/12719238/100374207-31500280-300c-11eb-8570-ec96af99281a.png)

**Comment by xztraz** [comment]
same as https://github.com/domoticz/domoticz/issues/4407
