### ISSUE TITLE
Screen error in Groups or Scenes in theme Elemental

### ISSUE THREAD

**Issue by differentieel** [domoticz/domoticz#4493]
Version: 2020.2 (build 12705)
Build Hash: d05c1201b-modified
Compile Date: 2020-11-25 09:40:24
dzVents Version: 3.0.17
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

theme: Elemental
language: Dutch
dashboard: Compact

bug in desktop: macOS 10.11.6
browser: Firefox 78.5.0esr 64b NL

![2020-11-28_Screen_Groups](https://user-images.githubusercontent.com/484138/100497301-ca8d2f00-315a-11eb-9ab0-81417eb0e678.png)

**Comment by rwaaren** [comment]
Please follow the issue Guidelines (presented to you when opening this issue) 

 ### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

As already experienced by many forum members before:  For this type of GUI problems the solution is 99 out of 100 times
**Clear your browser cache + AppCache (two different things!!)**

So if that did solution did not work for you  then clearly state in your issue that you already tried it (and also how)
Thx !

**Comment by differentieel** [comment]
excuses for wasting your time
