### ISSUE TITLE
Error with EventHelpers.lua since beta update today (AKA problem with Linux build)

### ISSUE THREAD

**Issue by sd5445fr** [domoticz/domoticz#4494]
I'm on have debian 10 running on a virtual machine on a synolgy nas and have just updated to the lasted beta version.

I have a recurrent error in my log :
 2020-11-28 14:05:00.079 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: error loading module 'EventHelpers' from file '/home/pi/domoticz/dzVents/runtime/EventHelpers.lua':
2020-11-28 14:05:00.079 /home/pi/domoticz/dzVents/runtime/EventHelpers.lua:1101: ')' expected near <eof> 

I checked the file "EventHelpers.lua" and there are lines of code missing at the end of the file. It ends like this: 

	function self.dispatchCustomEventsToScripts(domoticz)
		if (domoticz

When I run the beta update manually, I get this error : 

gzip: stdin: unexpected end of file
dzVents/runtime/TimedCommand.lua
dzVents/runtime/EventHelpers.lua
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Restarting Domoticz... (please standby...)

Regards

**Comment by rwaaren** [comment]
Seems that the Linux tar got corrupted somehow. Until someone fix this you can get the correct file from github with


```
sudo wget "https://raw.githubusercontent.com/domoticz/domoticz/development/dzVents/runtime/EventHelpers.lua"
sudo cp EventHelpers.lua <domoticz dir>/dzVents/runtime/EventHelpers.lua
```

**Comment by rwaaren** [comment]
Forced a rebuild of the tar files by making a very small mod to History.txt 
They are OK now.

@gizmocuz, this issue happened before. Should we add a check to the ./updatebeta and ./updaterelease scripts to prevent that a broken tar file can cause this kind of issue?

**Comment by gizmocuz** [comment]
@rwaaren , It's a manual process... (the updating)
But I made some modifications to the update script that should hopefully detect a broken archive:

https://github.com/domoticz/domoticz/commit/7dfcb3d5c105d851c78cec0d29020a027d8aab49

**Comment by gizmocuz** [comment]
@rwaaren , because it's a manual action (to create the beta's for arm systems), I am 90% sure this is a download issue (maybe server was down, or another issue)

**Comment by rwaaren** [comment]
@gizmocuz 
Could be but I tried a couple of times both manually and via the script and every time the linux tar (12707) was corrupt

**Comment by rwaaren** [comment]
> But I made some modifications to the update script that should hopefully detect a broken archive:

Thx !!

**Comment by rwaaren** [comment]
An Issue seem to be in the gzip part.
When I tried to update from the downloaded (linux) tgz file I encountered the same error as before. Further analysis showed 
```

tar xvfz  domoticz_beta.tgz domoticz
domoticz

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

```

**Comment by gizmocuz** [comment]
No idea how you downloaded the archive, but try using the updatebeta script
No issues here

**Comment by gizmocuz** [comment]
After you used the updatebeta script to get you on the new version (still talking about ARM systems here),
use the updatebeta script again, this is now a new script that checks the integrity as well
Should update you to the same version, but it will verify the archive

**Comment by rwaaren** [comment]
On Intel NUC (Debian) using the linux tgz (There are / were no issues on raspberries)
 

more updatebeta
```
#!/bin/sh

# This script can be used to upgrade to the latest beta version

lowercase(){
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
}

OS=`lowercase \`uname -s\``
MACH=`uname -m`
if [ ${MACH} = "armv6l" ]
then
 MACH="armv7l"
fi

echo "Updating to latest beta version..."
echo "Please Standby..."
wget -4 -O domoticz_beta.tgz --no-check-certificate "https://www.domoticz.com/download.php?channel=beta&type=release&system=${OS}&machine=${MACH}"
echo "Checking file Integrity..."
tar -tzf domoticz_beta.tgz >/dev/null
if [ $? -ne 0 ]
then
 echo "Problem in downloaded Domoticz archive. Stopping update!"
 exit 1
fi
tar xvfz domoticz_beta.tgz
rm domoticz_beta.tgz
echo "Restarting Domoticz... (please standby...)"
sudo service domoticz.sh restart

```

```
./updatebeta
Updating to latest beta version...
Please Standby...
--2020-11-29 13:56:34--  https://www.domoticz.com/download.php?channel=beta&type=release&system=linux&machine=x86_64
Resolving www.domoticz.com (www.domoticz.com)... 172.67.190.40, 104.31.78.142, 104.31.79.142
Connecting to www.domoticz.com (www.domoticz.com)|172.67.190.40|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://releases.domoticz.com/releases/beta/domoticz_linux_x86_64.tgz [following]
--2020-11-29 13:56:34--  https://releases.domoticz.com/releases/beta/domoticz_linux_x86_64.tgz
Resolving releases.domoticz.com (releases.domoticz.com)... 146.185.159.228
Connecting to releases.domoticz.com (releases.domoticz.com)|146.185.159.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16384000 (16M) [application/octet-stream]
Saving to: ‘domoticz_beta.tgz’


domoticz_beta.tgz                                       100%[============================================================================================================================>]  15.62M  26.0MB/s    in 0.6s

2020-11-29 13:56:35 (26.0 MB/s) - ‘domoticz_beta.tgz’ saved [16384000/16384000]

Checking file Integrity...

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Problem in downloaded Domoticz archive. Stopping update!

```
Updating on raspberry was/ is without issues (either initiated via the GUI or using ./updatebeta
 
To check I copied the downloaded tgz file from the NUC to my Raspberry and tried the  tar -tzf domoticz_beta.tgz >/dev/null there.

result:

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

Only thing I can think of is that the tar / zip process creating the tgz for Linux on the build system is  playing tricks

**Comment by gizmocuz** [comment]
Ahh that makes a difference, ARM vs x86/64

Yes it seems the Travis builds have issues:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.6M    0     0  100 15.6M      0  5241k  0:00:03  0:00:03 --:--:-- 5241k
curl: (18) server did not report OK, got 426
100    92    0     0  100    92      0    129 --:--:-- --:--:-- --:--:--   129
100    89    0     0  100    89      0    126 --:--:-- --:--:-- --:--:--   147
100   99k    0     0  100   99k      0   140k --:--:-- --:--:-- --:--:--  495k
curl: (18) server did not report OK, got 426
100   99k    0     0  100   99k      0   140k --:--:-- --:--:-- --:--:--  140k
curl: (18) server did not report OK, got 426
Script failed with status 18

**Comment by gizmocuz** [comment]
Could you maybe check if it's working correctly now ? Made some adjustments

**Comment by gizmocuz** [comment]
@rwaaren , sorry, it's still not building correctly... Let's wait a few days...
AppVeyor is working correctly (doing windows builds at the moment)
Maybe we could use it to build the linux binaries as well

**Comment by rwaaren** [comment]
Users get an empty download when they try to update.

[Forum post ](https://www.domoticz.com/forum/viewtopic.php?p=262327#p262327)

**Comment by gizmocuz** [comment]
I removed the files on the server. I am currently not able to investigate this issue
The remedy for now for linux (non-arm) users is:
https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by waltervl** [comment]
It is already long time possible to download the images again.
