### ISSUE TITLE
Do not install domoticz on pi with 64 bit kernel enabled

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#4496]
Installing and running domoticz with on a raspberry pi

Linux Banana 5.4.72-v8+ #1356 SMP PREEMPT Thu Oct 22 13:58:52 BST 2020 aarch64 GNU/Linux

Clean image but with 64 bit kernel enabled in 

`/boot/config.txt`

Using the option

`arm_64bit=1`

And installing domoticz in the home folder with 

`curl -L https://install.domoticz.com | bash`

Will result in

```
pi@Banana:~/domoticz $ ./domoticz 
-bash: ./domoticz: No such file or directory
```

But all files are there!!! You can run updaterelease, view all files but you can not run domoticz.

Disabling the 64 bit kernel will result in 

```
pi@Banana:~/domoticz $ ./domoticz 
-bash: ./domoticz: cannot execute binary file: Exec format error
```

After removing domoticz and reinstalling it with the 32 bit kernel everything works fine, switching back to the 64 bit kernel it works also ok again. 

So DO NOT INSTALL domoticz with the 64 bit kernel of the raspberry pi enabled.
This is probably a 64 bit kernel bug. But it is a very strange behaviour so I thought I mention it.

**Comment by gizmocuz** [comment]
@Tristan79 , you could try to force a 64 bit or 32 bit version by modifying the "updatebeta" script inside the domoticz folder.
Maybe the script is not detecting the right architecture

**Comment by ghost** [comment]
The two problems are:

That if you enable 64bit support for the kernel on a pi, user land is still 32 bit. The installer script installs the 64 bit version like the kernel, while it is still 32bit user land. 

Is there a check with the installer checking the 32 vs 64 bit and only checking the kernel instead of the user land?

Domoticz is the only app I encountered not installing the right bit version.

And there is something wrong with executing a 64bit version of a program in 32bit user land while having a 64bit kernel...
Strange things happen :-) Like the message above: No such file or directory. That is probably linux/raspbian bug.

I know this is an edge case and I am probably the only one who encountered it. As I said before a very strange behaviour so I thought I mention it.

Keep up the good work.



ps. heb hass en openhab uitgeprobeerd, wat een totale ellende is dat qua support van hardware, installatie en configureren... Mooi dat domoticz bestaat 👍

**Comment by gizmocuz** [comment]
@Tristan79 , Are you able to modify the install/update scripts so it can work correctly ?
If not, I'm closing this very specific issue. In the end it might be better just to install a 64bit distribution on your Pi (like Pi64) or stay on 32 bit
I see no benefit of using both (except for cross compiling which I do)

**Comment by ghost** [comment]
Close the issue, it is a 0.009% edge case. And you can refer it to this
issue how to solve it, if and only if anyone mention it. It not worth the
time. it is not a security bug. It is just the complexity of software
development.
Probably will be fixed in future releases of rasbian when they are done
transitioning, one thing I learned, time fixes everything :-). Almost...

**Comment by sincze** [comment]
Ah could replicate this issue indeed.
I think I need to modify the line in ./updatebeta to force downloading the x32 Domoticz.

```
sudo file /home/pi/domoticz/domoticz

/home/pi/domoticz/domoticz: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=fe8148ac14247f77fc67e5a87198c46cf79e5c8c, not stripped
```

```
sudo uname -a

Linux domoticzups 5.10.52-v8+ #1441 SMP PREEMPT Tue Aug 3 18:14:03 BST 2021 aarch64 GNU/Linux
```

So from **updatebeta**  the following variables should be updated / pre-filled by me for this edge case **OS** and **MACH**

To ensure the correct download via:
`wget -4 -q -O domoticz_beta.tgz --no-check-certificate "https://www.domoticz.com/download.php?channel=beta&type=release&system=${OS}&machine=${MACH}"`

**Comment by gizmocuz** [comment]
@sincze , yes but that is hardcoding the values. If you are on a system that can support 64bit, why would you like want a 32bit Domoticz instead of the 64bit ? Or either choose a fixed x86 or x64 distribution ?
I'm closing the issue as this is indeed the case for 0.009% of the users
