### ISSUE TITLE
Sortable lists

### ISSUE THREAD

**Issue by felix63** [domoticz/domoticz#4497]
It would be quite useful if lists with in Domoticz could be sorted through the UI in a finder like way. If you go to Roomplans for instance you have a list with rooms you have created. Once you select one you'll get a second list. It would be very useful if you could sort these lists by clicking on the columnheader. This would improve usability.

**Comment by gizmocuz** [comment]
Could you post some screenshots ?
How about something like the room plans ? In the editor you can order them ?

**Comment by felix63** [comment]
I have reconsidered :-)
