### ISSUE TITLE
Cache refresh issue

### ISSUE THREAD

**Issue by gaudryc** [domoticz/domoticz#450]
The server can return an HTML response body in a HTTP 304 response while the browser is refreshing its cache by requesting if a javascript has been modified :

![capture d ecran 2016-02-08 a 22 30 46](https://cloud.githubusercontent.com/assets/14302044/12902466/b3e7fc0e-cec1-11e5-8dbd-3238d7a01de3.png)

But a HTTP 304 response MUST NOT contain any body.

**Comment by gizmocuz** [comment]
Patched, thanks
