### ISSUE TITLE
[BETA version: 2020.2 (build 12709)] Local networks requiring credentials

### ISSUE THREAD

**Issue by Geo-Ron** [domoticz/domoticz#4501]
After upgrading tot Domoticz Beta version: 2020.2 (build 12709) Domoticz asks for credentials for clients on defined local networks.

Domoticz running on `raspberry 3 Raspbian GNU/Linux 10 (buster)`

_Local networks was defined as:_
192.168.\*.\*,127.0.0.\*,localhost,::1

_No success after changing to:_
192.168.0.\*,192.168.1\.*,192.168.2.\*,127.0.0.\*,localhost,::1

**Version info:**
Version: 2020.2 (build 12709)
Build Hash: 7dfcb3d5c-modified
Compile Date: 2020-11-29 11:09:03
dzVents Version: 3.0.17
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by gizmocuz** [comment]
You should change it to
`192.168.0.*,192.168.1.*`

**Comment by Geo-Ron** [comment]
> You should change it to
> 192.168.0._,192.168.1._

The booboo was that I used `,` instead of `;`
The settings page says to do so, clearly.

**Comment by gizmocuz** [comment]
Yep that's it! thanks for reporting back
