### ISSUE TITLE
Problem to make from source after last update

### ISSUE THREAD

**Issue by aldodemi** [domoticz/domoticz#4506]
Last update doesn't works (here a pi 3 Raspbian GNU/Linux 10 (buster), but same problem with Ubuntu 20.04.1 LTS on Intel i3):

remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 28 (delta 20), reused 26 (delta 20), pack-reused 0
Unpacking objects: 100% (28/28), done.
Da https://github.com/domoticz/domoticz
   ebd4312af..a82fe999f  development -> origin/development
Aggiornamento di ebd4312af..a82fe999f
Fast-forward
 hardware/EvohomeRadio.cpp                  |  20 ++++++++++++++++----
 hardware/EvohomeSerial.cpp                 |   8 ++++----
 hardware/MochadTCP.cpp                     |   4 ++--
 hardware/OTGWBase.cpp                      |  22 +++++++++++-----------
 hardware/OpenZWave.cpp                     |   1 -
 hardware/PiFace.cpp                        |   4 ++--
 hardware/Rego6XXSerial.cpp                 | 101 ++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------
 hardware/eHouseTCP.cpp                     |   3 +--
 hardware/openzwave/control_panel/ozwcp.cpp |   3 +--
 main/EventSystem.cpp                       |   6 +++---
 main/dzVents.cpp                           |  32 ++++++++++++++++----------------
 notifications/NotificationBase.cpp         |  21 +++------------------
 12 files changed, 109 insertions(+), 116 deletions(-)
-- Submodule update
Da https://github.com/eclipse/mosquitto
   25d5b8cb..122e6ecf  master     -> origin/master
error: Your local changes to the following files would be overwritten by checkout:
        Makefile
        client/Makefile
        lib/Makefile
        man/Makefile
        src/Makefile
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout '122e6ecfd3ec31084a4d25c1412b3d615c617148' in submodule path 'extern/mosquitto'
CMake Error at CMakeLists.txt:119 (message):
  git submodule update --init failed with 1, please checkout submodules

-- Configuring incomplete, errors occurred!
See also "/home/pi/domoticz/CMakeFiles/CMakeOutput.log".
See also "/home/pi/domoticz/CMakeFiles/CMakeError.log".
make: *** [Makefile:7831: cmake_check_build_system] Error 1

**Comment by rwaaren** [comment]
Cannot replicate this on Intel NUC and Raspberry PI 4 (Buster) 

Please try again after removing the source directory and 
refresh from github using 

```
git clone https://github.com/domoticz/domoticz.git dev-domoticz
cd dev-domoticz 
cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt
```

**Comment by kiddigital** [comment]
@aldodemi , this happens when you update your branch and Domoticz wants to update an external (sub)module.

In this case the mosquitto module.

CMake has made some local changes in the module so updating fails as there are uncommitted changes pending.

My solution is just to 'git stash' these changes (see dir 'extern/mosquitto') and than run the CMake release again. Now everything gets updated correctly and you can build again.

Not sure what the real fix should be (haven't investigated) but this way the symptoms are gone 😁

**Comment by gizmocuz** [comment]
My solution:
rm -Rf extern/mosquitto
rm -Rf CMakeFiles
rm CMakeCache.txt

And then build again
