### ISSUE TITLE
Milight plugin does not update hub status in Domoticz

### ISSUE THREAD

**Issue by jellewie** [domoticz/domoticz#4509]
I can not for the life of me find out where to post this, so sorry for when it's wrong, and please help with the correct URL.

.

I have an [ESP8266 Milight-Hub](https://github.com/sidoh/esp8266_milight_hub) setup successfully, and I am using the [Limitless/AppLamp/Mi-Light With LAN/WiFi interface](https://www.domoticz.com/wiki/Limitless/AppLamp_LED) plugin to communicate between Domoticz and the Milight-Hub.

The only downside of this protocol I have found is that **_updates done from the Milight-Hub are not updated in Domoticz_** (the state is not updated (or send) to Domoticz)

## Steps:
1. **Setup**, make sure Milight-Hub and Domoticz are set up and are connected (I use UDP Protocol Version 6)
2. **Toggle light in Domoticz** (this will make the Domoticz and Milight-hub in sync)
3. **Toggle light in [Milight-Hub](http://milight-hub.local/#)**, (This toggles the light, and the status in the Milight-Hub)
Note Domotics did not update its status and is now out of sync.

# Random INFO
## Version
Version: 2020.2 (Currently latest available)
Build Hash: b63341bc0
Compile Date: 2020-04-26 13:47:55
dzVents Version: 3.0.2
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

## Domoticz plugin
[Limitless/AppLamp/Mi-Light With LAN/WiFi interface](https://www.domoticz.com/wiki/Limitless/AppLamp_LED)
![image](https://user-images.githubusercontent.com/1545223/101351943-aedc0400-3891-11eb-8bb8-5338a1b5ae80.png)
![image](https://user-images.githubusercontent.com/1545223/101352815-fa42e200-3892-11eb-92dd-acd1b9bcb10a.png)

## ESP8266 Milight-Hub
[ESP8266 Milight-Hub](https://github.com/sidoh/esp8266_milight_hub) hub that Domoticz plugin is connecting to plugin 
![image](https://user-images.githubusercontent.com/1545223/101352071-d59a3a80-3891-11eb-9576-08fc0fbad0d3.png)
* Note that I use 2 UDP-ports to control 2 groups, not that that matters in this case but it explains the picture a bit better.

**Comment by deennoo** [comment]
As far i remeber, Limitless device (bulb/gateway) never have bi directional communication.

Have some of them, and when i trigger them from reote or app domoticz doesn't know this, the only way i found is to build an RFLINK with 2.4ghz module and snif what's happen to update bulb if not trigger using domoticz

**Comment by gizmocuz** [comment]
That is correct. Best to use only Domoticz
