### ISSUE TITLE
Scenes log page doesn't work with latest version

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz#4516]
Version:
Domoticz version 2020.12732
Theme: Aurora

When I click on logs for any Scene or Group:

![image](https://user-images.githubusercontent.com/14561640/101778914-d2eb4f80-3af4-11eb-94dc-33291d35186d.png)

**Comment by rwaaren** [comment]
From the issue guidelines:

* *** Please use the search feature to see if your issues have been raised or addressed first.**

###  * ***Clear your browser cache + AppCache (two different things!!)*** 

If you already did this then please add this to your reported issue.

![image](https://user-images.githubusercontent.com/24454798/101780892-6d4c9280-3af7-11eb-8d5d-011e73ca1217.png)

**Comment by gizmocuz** [comment]
No issues here (latest beta, default theme)

**Comment by cronyx** [comment]
![Выделение_413](https://user-images.githubusercontent.com/2557102/102392361-02fc8c00-3fe8-11eb-9ddd-451308f867b7.png)

No issues. Press CTRL+R on page.

**Comment by galadril** [comment]
Your right..
