### ISSUE TITLE
Battery readout on recharchable(nimh) battery is incorrect

### ISSUE THREAD

**Issue by beninhos** [domoticz/domoticz#4517]
**Version:** 2020.2 (build 12467)
**Platform:** raspbian
**Plugin/Hardware:** razberry / Danfoss Devolo Home Control Radiator Thermostat (0x0175:0x0005) openzwave
**Description:** Battery status read-out  is wrong. Domoticz reports a percentage. Used the TRV with 0% battery for over a month and still only 50% capacity was used, measured with battery charger.
**solution:** use alkaline battery's, but that's not nice for the environment. 
**expect:** readout of rechargeable battery's like NIMH more accurate. 

I know that a rechargeable battery high a 0.3*(not sure) lower voltage, maby this is way the read-out goes wrong. I'am using a variety on of brands - Eneloops, Panasonic, GP an Duracel NIMH battery ranging 2000 - 2600 mah and all have the same behaviour, domoticz reports 0% while they still have 50-70% capacity. 

We need a accurate read-out because the TRV is used as *active and directs the boiler's fire behaviour.

**Comment by rwaaren** [comment]
If the battery reading in domoticz is the same as what's shown on the Zwave nodes page then there is not much domoticz can do about it. You might have more luck if you report it on [the github of openZwave](https://github.com/OpenZWave/open-zwave)

**Comment by beninhos** [comment]
Hi, thanks. yes, i have check the open zwave page and it it the same. I'll report over there.
