### ISSUE TITLE
All devices in others tab have a star when a room is selected

### ISSUE THREAD

**Issue by rrozema** [domoticz/domoticz#4519]
Domoticz Version: 2020.2 (build 12697)
Build Hash: 34c800ea6-modified
Compile Date: 2020-11-22 13:14:05
dzVents Version: 3.0.16
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
RPi 3B+

In the Others tab ("Overige" in Dutch), when you have a room selected, all devices show a yellow star to indicate they should be included in the summary tab. This appears to be a display-only problem, as a device that gets clicked is still correctly added to/removed from the summary screen, even though the star doesn't change in the "Others" tab. When you have "All" rooms selected, the yellow stars are shown correctly only on the devices selected for the summary tab.

Actuallu it is not only the others tab, the same thing happens in 'Switches'.

**Comment by gizmocuz** [comment]
@rrozema , thanks you for reporting. Issue found and fix on it's way

**Comment by rwaaren** [comment]
@rrozema can you please confirm it is ok now (and close the issue)?
thx!

**Comment by gizmocuz** [comment]
It's solved

**Comment by Eddie-BS** [comment]
As a side-effect of this change, if I select a ROOM in the dashboard tab, all devices MUST have the yellow star to show up.
That causes the "all" room to be very crowded ...
