### ISSUE TITLE
InfluxDB datapush does not allow a dimmmer's level to be pushed

### ISSUE THREAD

**Issue by rrozema** [domoticz/domoticz#4520]
Version: 2020.2 (build 12697)
Build Hash: 34c800ea6-modified
Compile Date: 2020-11-22 13:14:05
dzVents Version: 3.0.16
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

For a dimmer device only the 'State' value (Status in Dutch) can be selected if the device is a Dimmer. The State returns a 0, 1 or 2 value only. A Dimmer's level can however be set from 0 to 100, this is the value that should be pushed. The dimmer device is used for much more than just a light dimmer, for example as the valve opening percentages on the Eurotronic SpiritZ for which it is extremely useful to push the valve opening percentage.

**Comment by gizmocuz** [comment]
Then instead of only a status push we should also have a 'level' as option to push
Are you able to build this in a PR ?

**Comment by rrozema** [comment]
No, I am not. I can read code in many languages, but am not familiar with the tools and don't have a proper build platform.

**Comment by gizmocuz** [comment]
Implemented in beta 12741

**Comment by rrozema** [comment]
Version: 2020.2 (build 12741)
Build Hash: fee1840ed-modified
Compile Date: 2020-12-14 10:35:17
dzVents Version: 3.0.19
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

A dimmer's level can now be pushed and is successfully recorded in my influx db. There is still one problem though: if a dimmer is switched Off, the value in level isn't changed, i.e. level 0 is often not pushed into the fluxdb, even though the dimmer is off. Can you please make it that a level of 0 is pushed when the dimmer is switched Off, regardless of the value in level? In other words, the value pushed for Level should be 0 when the dimmer is Off, or the value of the dimmer's level otherwise.

**Comment by gizmocuz** [comment]
@rrozema , Should be zero now in beta 12743, Not tested, but I expect it to be working.
When the switch state contains the word "Off" (Off, All Off, Group Off), the level is 0

**Comment by rrozema** [comment]
Tested and verified OK
