### ISSUE TITLE
Overflow at P1 smart meter

### ISSUE THREAD

**Issue by gropi75** [domoticz/domoticz#4521]
Version: 4.11786
Build Hash: 16cbfa328
Compile Date: 2020-03-14 19:27:12
dzVents Version: 3.0.1
Python Version: 3.7.5 (default, Oct 17 2019, 12:25:15) [GCC 8.3.0]

I use a dummy sensor with type of P1 smart meter.

As long as I draw power from the power net everything is displayed correctly. 
As soon as I supply power back (negative value), the usage will be displayed as a very high positive number.

![grafik](https://user-images.githubusercontent.com/62841990/102069276-d8e77600-3dfd-11eb-878f-22982da610c9.png)

I checked the raw data over the API the content:
http://your-ip:8080/json.htm?type=devices&rid=YOUR-IDX

The data shows negative (-79) value
"Data": "1091530.2;0;2217.5;0;-79;0",
Usage shows wrong values:
"Usage": "18446744073709551537 Watt",

{
  "ActTime": 1607856670,
  "AstrTwilightEnd": "18:22",
  "AstrTwilightStart": "06:13",
  "CivTwilightEnd": "17:04",
  "CivTwilightStart": "07:32",
  "DayLength": "08:18",
  "NautTwilightEnd": "17:44",
  "NautTwilightStart": "06:51",
  "ServerTime": "2020-12-13 11:51:10",
  "SunAtSouth": "12:18",
  "Sunrise": "08:09",
  "Sunset": "16:27",
  "app_version": "4.11786",
  "result": [
    {
      "AddjMulti": 1.0,
      "AddjMulti2": 1.0,
      "AddjValue": 0.0,
      "AddjValue2": 0.0,
      "BatteryLevel": 255,
      "Counter": "1091.530",
      "CounterDeliv": "2.217",
      "CounterDelivToday": "0.169 kWh",
      "CounterToday": "3.616 kWh",
      "CustomImage": 0,
      "Data": "1091530.2;0;2217.5;0;-79;0",
      "Description": "",
      "Favorite": 1,
      "HardwareID": 2,
      "HardwareName": "Dummy",
      "HardwareType": "Dummy (Does nothing, use for virtual switches only)",
      "HardwareTypeVal": 15,
      "HaveTimeout": false,
      "ID": "14136",
      "LastUpdate": "2020-12-13 11:51:01",
      "Name": "Stromz\u00e4hler",
      "Notifications": "false",
      "PlanID": "14",
      "PlanIDs": [
        14
      ],
      "Protected": false,
      "ShowNotifications": true,
      "SignalLevel": "-",
      "SubType": "Energy",
      "SwitchTypeVal": 0,
      "Timers": "false",
      "Type": "P1 Smart Meter",
      "TypeImg": "counter",
      "Unit": 1,
      "Usage": "18446744073709551537 Watt",
      "UsageDeliv": "0 Watt",
      "Used": 1,
      "XOffset": "371",
      "YOffset": "286",
      "idx": "230"
    }
  ],
  "status": "OK",
  "title": "Devices"
}

I assume this is an overflow topic, because if You add the 2 (positive) numbers You get exactely 2^64.
As I checked in P1MeterBase.cpp, there will be unsigned long for some variables used.

Discussion on the forum:
#https://www.domoticz.com/forum/viewtopic.php?f=14&t=33870

**Comment by gizmocuz** [comment]
@gropi75 , could you update to the latest beta and try this again ?

**Comment by gropi75** [comment]
@gizmocuz 
thanks for the fast response.
I pulled the beta, no change.

This is the version now:
Version: 2020.2 (build 12741)
Build Hash: fee1840ed-modified
Compile Date: 2020-12-14 09:35:17
dzVents Version: 3.0.19
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by gizmocuz** [comment]
@gropi75 , is it possible you can debug the code ? I assume the counters should work normally, maybe it is the usage that goes wrong

**Comment by gropi75** [comment]
@gizmocuz thanks for the fast help.
Seems my meter just provides 1 value as usage. It is positive if You get power from net, and negative if You supply back. However in P1 Meter there 2 two expected variables: PROD and CONS. Both should be positive values. 
I pass now the values from my meter to node-red first, where i check which direction is the energy flow. Depending on that I update PROD and CONS.
Now it works fine.

![grafik](https://user-images.githubusercontent.com/62841990/102204383-14e80d00-3eca-11eb-8d42-89de37ca30f7.png)
