### ISSUE TITLE
blind percentage inverted not publish mqtt if icons are used

### ISSUE THREAD

**Issue by megamarco833** [domoticz/domoticz#4522]
on domoticz Version: 2020.2 (build 12697)
if i create a dummy device as blind percentage inverted like this:
![immagine](https://user-images.githubusercontent.com/44502572/102137145-a91a8b80-3e5a-11eb-8f7b-b5829320ca29.png)
![immagine](https://user-images.githubusercontent.com/44502572/102139170-c1d87080-3e5d-11eb-825d-146bb82b9231.png)

if i use icons (open or close) I can not see the correct publishing on topic `domoticz/out ` about percentage inside "svalue1" 
it happened ONLY using icons. if i use slider the message published is with "svalue1" representing the correct arrival percentage

how to reproduce:
start from a percentage like 77% sliding the pointer at 77%.
click on icon "open" or "close" and i listen to topic domoticz/out:

after clicking on open icon for example you will see:
```
{ "Battery" : 255, "RSSI" : 12, "description" : "{\"topic\": \"tasmota_blind_new\", \"blind\": 1}", "dtype" : "Light/Switch", "hwid" : "6", "id" : "00014117", "idx" : 199, "name" : "tap1_esp8266_new_ip57", "nvalue" : 1, "stype" : "Switch", "svalue1" : "77", "switchType" : "Blinds Percentage Inverted", "unit" : 1 }
```

that it's wrong because `svalue1 = 77%` (where we start in the example) but i clicked "open" icon, so slider is now at 100% (correct) but also `svalue1 inside mqtt message should be = 100` instead we have the starting percentage (77)

if, instead of using icons, you slide the bar, the out message is always correct (moving slider the out mqtt message is always with svalue that contain the arrival percentage)

is it possible to fix that also clicking the icon (open or close) the mqtt message will be send out with final position requested and not started position?

thanks!

**Comment by rwaaren** [comment]
Not sure if it helps you but checking the nValue show open/ close/ level .

nValue = 0 -->> Closed
nValue = 1 -->> Opened
nValue = 15 -->> level = sValue

**Comment by gizmocuz** [comment]
I think this is correct. The command (Open or Close) is represented in the nvalue (0/1) , the percentage was the last used percentage
nvalue will be different when you actually change the percentage
This is the same when you have a light dimmer (zwave for example), your last percentage was 77% ... you turn on the light, it will go to ... 77% yes, when you turn off the light it will go off. When you turn on the light it will go to the last dimmer (percentage) value (77%). You are not changing to 77% (with SetLevel), you are just telling it 'go on' (to the last set percentage value)
So you need to take the nValue in account

**Comment by megamarco833** [comment]
hi and thanks both for very good explanation, so i need also to look at nValue, now it's very clear.
sorry for make this stupid question.
my fault.
just a note, because i select inverted and i make some tests:
nValue = 0 -->> Closed
nValue = 1 -->> Opened

and when need to control percentage:
nValue = 2 -->> level = sValue
not nValue = 15 correct?

Last consideration, it's clear and useful for dimmer light that when you turn off the light it will go off. When you turn on the light it will go to the last dimmer (percentage) value (77% in the example). You are not changing to 77% (with SetLevel), you are just telling it 'go on' (to the last set percentage value)
but this is not used for blind, where there is not possibility to turn on or off, we just manage postion with SetLevel (percentage) and on or off are 100% open or 0%close
but anyway i understand the logic now
thanks!

**Comment by gizmocuz** [comment]
@megamarco833 , yes you are correct, 2 = level = svalue

**Comment by rwaaren** [comment]
I was just curious why I saw nvalue=15 when dimming while @gizmocuz and @megamarco833 did see nvalue=2 

test setup:
TestBlind1 created as virtual switch and converted via switch tab to switch Type Blinds Percentage inverted and set to 45%
TestBlind2 created as virtual RGB switch and converted via switch tab to switch Type Blinds Percentage inverted and set to 45%

In database
```
select id, name, type, subtype, switchType, nvalue,svalue from deviceStatus where id in (744,745);
ID|Name|Type|SubType|SwitchType|nValue|sValue
744|TestBlind1|244|73|16|2|45
745|TestBlind2|241|2|16|15|45

```
GUI:

![image](https://user-images.githubusercontent.com/24454798/102228562-21309200-3eeb-11eb-8f72-73a19fc97972.png)

Conclusion: only switchType is changed but type, subtype does influence nvalue when 'dimming'
