### ISSUE TITLE
Eurotronic SpiritZ thermostat mode should behave like selector switch

### ISSUE THREAD

**Issue by rrozema** [domoticz/domoticz#4525]
Version: 2020.2 (build 12741)
Build Hash: fee1840ed-modified
Compile Date: 2020-12-14 10:35:17
dzVents Version: 3.0.19
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

When including an Eurotronic SpiritZ, a.o. a device called 'Thermostat Mode' gets installed. This device is shown as an icon only, the actual setting is only shown in the title of the device's badge. Consequently the value can not be changed from the devices list. The value can only be changed after clicking 'Aanpassen'. According to #2906 and #3148 the device value and it's options can't be (easily?) accessed from scripts either. Can we have the 'Thermostat Mode' device created for this part of the spirit module behave like other selector switches in Domoticz?

Also, the value shown in the device list isn't the actual mode the device is in: If I change the mode to 'Manufacturer specific', the device still displays 'Heat'.

And furthermore: the type specified for this device type 'Thermostat Mode' isn't supported in Basepush (#4528), so the value for this device can't be pushed and results in an error "Could not determine data push value" logged if a link is defined for this device.

![devices](https://user-images.githubusercontent.com/1747982/102685409-a44e3280-41e0-11eb-8770-cc0a1ea965a9.png)
![aanpassen](https://user-images.githubusercontent.com/1747982/102685435-d069b380-41e0-11eb-85d1-15249c4362c1.png)
![device](https://user-images.githubusercontent.com/1747982/102685459-11fa5e80-41e1-11eb-8911-5782d250f64f.png)
![zwave](https://user-images.githubusercontent.com/1747982/102685481-38b89500-41e1-11eb-87ad-f43a402cd264.png)

**Comment by waltervl** [comment]
As openzwave is deprecated and succeeded by Zwavejs2mqtt this issue will be closed.
