### ISSUE TITLE
adding a button as a slave, popup stays open, button not working

### ISSUE THREAD

**Issue by dpocock** [domoticz/domoticz#4526]
As discussed in this forum thread

https://www.domoticz.com/forum/viewtopic.php?f=11&t=28190

I tried two different remotes:

- Aqara AQ2 button

- Philips Hue dimmer (4 buttons)

I tried the Debian packages, version 4.11020-2~bpo9+1 with domoticz-zigate-plugin package version 4.4.9~beta1-2~bpo9+1

I've now tried building a new package using the 2020.2 release from Github, the problem is the same. The package isn't published yet but it will be soon.

Summarizing the symptoms above, observed in my own testing with both versions of the package:

a) using the remote as a slave:
1) put the Zigate in permit join mode,
2) hold down the join button on the remote/dimmer,
3) go to the Setup->Devices page,
4) look for the new entry in the list, click the green Add Device arrow,
5) select the radio button for Sub/Slave device,
6) from the Device pulldown box, select a light bulb,
7) click the Add Device button, the button becomes disabled (can't click it again) but the popup stays open,
8) close the popup by pressing the Cancel button,
9) go to the Switches tab,
10) look under the Sub/Slave Devices heading, the button is there now but pressing the button does nothing,
11) check the logs, notice it does log something each time the button is pressed:

domoticz[64337]: (zigate0) ReadCluster - ClusterId=0012 - Switch Aqara: EP: 01 Value: 1
domoticz[64337]: (zigate0) UpdateDevice - (zigate0 - lumi.remote.b1acn01_SwitchAQ2-0015xxxxxx-01) 1:00

b) if I go to the Scenes tab, add a Group and add the button in the group, the same button does work

**Comment by waltervl** [comment]
Domoticz Sub/Slave mechanism has no added value for Zigbee devices.
