### ISSUE TITLE
Aqara WXKG02LM double button, both buttons behave like one when controlling group

### ISSUE THREAD

**Issue by dpocock** [domoticz/domoticz#4527]
Tested using the Domoticz Debian packages version 4.11020-2~bpo9+1 and Zigate plugin package 4.4.9~beta1-2~bpo9+1

Tested using the Domoticz Debian package version 2020.2-1 (not released yet) based on 2020.2 tarball.

1) put the Zigate in join mode
2) hold down the left button for 10 seconds until the switch joins
3) look at the Devices list, the device is listed once
4) go to the Scenes tab
5) add or edit a group
6) under the Activation Devices, click Add Device
7) press one of the buttons on the Aqara double switch
8) the switch appears in the Activation Devices list
9) press EITHER of the two buttons and the group is activated

What should happen:

9) only the button pressed at step (7) should activate the group

Logs:

Button 1 press:

```
domoticz[548]: (zigate0) ReadCluster - ClusterId=0012 - Switch Aqara: EP: 01 Value: 1
domoticz[548]: (zigate0) UpdateDevice - (zigate0 - lumi.remote.b286acn01_DButton_3-0015xxxx-02) 1:10
domoticz[548]: Activating Scene/Group: [g0]
domoticz[548]: Activating Scene/Group Device: sitting room ceiling (On)
```

Button 2 press:

```
domoticz[548]: (zigate0) ReadCluster - ClusterId=0012 - Switch Aqara: EP: 02 Value: 1
domoticz[548]: (zigate0) UpdateDevice - (zigate0 - lumi.remote.b286acn01_DButton_3-0015xxxx-02) 4:40
domoticz[548]: Activating Scene/Group: [g0]
domoticz[548]: Activating Scene/Group Device: sitting room ceiling (On)
```

Notice the EP: 01 and EP: 02 values seem to be able to distinguish which button was really pressed but the group is not aware of that.

**Comment by dpocock** [comment]
I tried this again today using firmware 3.1c and plugin version 4.12.087 beta, the problem is the same

**Comment by waltervl** [comment]
This was a Zigate issue and not a Domoticz one...
