### ISSUE TITLE
Please extend error message "BasePush: Could not determine data push value" with details

### ISSUE THREAD

**Issue by rrozema** [domoticz/domoticz#4528]
![basepush error](https://user-images.githubusercontent.com/1747982/102707422-12efc680-429b-11eb-8742-eacf2e757122.png)
Version: 2020.2 (build 12741)
Build Hash: fee1840ed-modified
Compile Date: 2020-12-14 10:35:17
dzVents Version: 3.0.19
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

I have the InfluxDB datapush set up to push 303 of my sensor values into an influxdb database for later analysis. I sometimes however notice some sensors are missing in my data set. At the same time I see the error message  "Error: BasePush: Could not determine data push value" logged many times, sometimes up to 14 messages a minute are logged.

Can we have more information in that error message, like for example name, type and possibly value of the device whose value could not be pushed? This way we can determine what sensors/values we are missing, find what we need to do to fix a problematic sensor and possibly find a pattern why this is happening. Of course, if you can fix the error straight away now that would be even better ;-)

**Comment by gizmocuz** [comment]
@rrozema , a quick search in the code reveals 1 line where this is printed... should not be that hard to make a pull request with additional logging.
Is that the only you see, or is there also a error "BasePush: Problem with conversion!" ?

**Comment by rrozema** [comment]
I see only this one message "Error: BasePush: Could not determine data push value"

**Comment by rrozema** [comment]
I changed CBasePush::DropdownOptionsValue() in push/BasePush.cpp as follows:

```
std::string CBasePush::DropdownOptionsValue(const uint64_t DeviceRowIdxIn, const int pos)
{
	std::string wording = "???";
	int getpos = pos - 1; // 0 pos is always nvalue/status, 1 and higher goes to svalues
	std::vector<std::vector<std::string> > result;

	result = m_sql.safe_query("SELECT Type, SubType FROM DeviceStatus WHERE (ID== %" PRIu64 ")", DeviceRowIdxIn);
	if (!result.empty())
	{
		int dType = atoi(result[0][0].c_str());
		int dSubType = atoi(result[0][1].c_str());

		std::string sOptions = RFX_Type_SubType_Values(dType, dSubType);
		std::vector<std::string> tmpV;
		StringSplit(sOptions, ",", tmpV);
		if (getpos >= 0 && getpos < tmpV.size())
		{
			wording = tmpV[getpos];
		}
		else if (getpos == 0) {
			wording = sOptions;
		}
		else
		{
			_log.Log(LOG_ERROR, "BasePush Idx %" PRIu64 ": Out of range position %d from options [%s].", DeviceRowIdxIn, getpos, sOptions.c_str());
		}
	}
	else
	{
		_log.Log(LOG_ERROR, "BasePush Idx %" PRIu64 ": DeviceStatus not found in db.", DeviceRowIdxIn);
	}
	return wording;
}
```

And I added in CBasePush::ProcessSendValue the following else at the end of the if-else-if list at line 724 to show any missed vType values:
```
		else
		{
			_log.Log(LOG_ERROR, "BasePush: Unknown vType %s.", vType.c_str());
		}
```

This results in a lot of error messages logged. Some of them:
- "BasePush: Unknown vType Thermostat Mode."
- "BasePush Idx 56: Out of range position -1 from options [Status,Level]." followed by "BasePush: Unknown vType ???."
- "BasePush Idx 691: Out of range position 1 from options [Voltage]."  followed by "BasePush: Unknown vType ???."
- "BasePush Idx 301: Out of range position -1 from options [Status,Level]." followed by "BasePush: Unknown vType ???."
- "BasePush Idx 58: Out of range position 1 from options [Lux]." followed by "BasePush: Unknown vType ???.""

and also a longer sequence:
```
2021-01-01 14:10:25.584 Error: BasePush: Could not determine data push value
2021-01-01 14:10:26.752 Error: BasePush Idx 657: Out of range position 2 from options [Instant,Usage].
2021-01-01 14:10:26.752 Error: BasePush: Unknown vType ???.
2021-01-01 14:10:26.752 Error: BasePush: Could not determine data push value
2021-01-01 14:10:26.753 Error: BasePush Idx 657: Out of range position 3 from options [Instant,Usage].
2021-01-01 14:10:26.753 Error: BasePush: Unknown vType ???.
2021-01-01 14:10:26.753 Error: BasePush: Could not determine data push value
2021-01-01 14:10:26.753 Error: BasePush Idx 657: Out of range position 4 from options [Instant,Usage].
2021-01-01 14:10:26.753 Error: BasePush: Unknown vType ???.
2021-01-01 14:10:26.753 Error: BasePush: Could not determine data push value
2021-01-01 14:10:26.753 Error: BasePush Idx 657: Out of range position 5 from options [Instant,Usage].
2021-01-01 14:10:26.754 Error: BasePush: Unknown vType ???.
2021-01-01 14:10:26.754 Error: BasePush: Could not determine data push value
```
I see a.o. a link with #4525 for the "Thermostat Mode" vType. If #4525 behaves like a normal selector switch this will result in this type to disappear and no exception needs to be added here. 

But most of these messages seem to stem from instances where the position specified doesn't match the number of options in sOptions for the device. I don't know yet from where these calls are made.

Device 657 is nothing special. It's a dummy device, type General, subtype 'kWh'. One of a series of 16 similar devices to receive one of my solar panel's power production.
Device 56 is a z-wave motion sensor. type 'Light/Switch', subtype 'Switch'.
Device 691 is a voltage sensor of a z-wave dimmer, type 'General', subtype 'Voltage'.
Device 301 is a z-wave motion sensor, type 'Light/Switch', subtype 'Switch'.
Device 58 is a illuminance sensor of a z-wave motion sensor, type 'Lux', subtype 'Lux'.

Some of the devices giving an error aren't in my list of logged devices:
657 - no logged
56 - logged, but shows no name after 'te versturen waarde'
691 - not logged
301 - logged, but shows no name after 'te versturen waarde'.
58 - logged, shows 'Lux' after 'te versturen waarde'.

Could this be due to the fact that the options are translated? It has dawned to me that it is odd to translate the names of the values in my ifnlux db. I have changed from English to Ducth at some time and as a result my reports in Grafana didn't work anymore: some of the key values had changed from English to Dutch too. At the time I didn't think much of it, but now I think the  key used to log the value in teh influx db should always be in English, regardless of the user interface setting. Otherwise reports will -depending on the user's language setting- have to deal with differently named values too.


So, using the logging I added for this issue I identified 3 issues so far:
1 - vType 'Thermostat Mode'is not supported -> Should be fixed when #4525 gets implemented.
2 - Options keys are translated -> I created a new issue #4556 that should fix this
3 - Some Idx-es are pushed that are not defined on my list of datapushes. I don't know yet what causes this?

**Comment by gizmocuz** [comment]
@rrozema, what you see here is that you used a thermostat device in a pusher, probably the temperature or setpoint.
This device also has a 'mode' field, and this is not implemented to be pushed
That is why you see the error "Could not determine data push value"

I made a patch in the new beta version (12810) that silenced this warning by changing the code to
```
		else if (vType == "Lux")
		{
			sprintf(szData, "%g", std::stof(rawsendValue));
		}
		else
			return;
```

If you would like the themostat mode to be supported you have to add this to the code.
If this solves your issue, please close this issue.

**Comment by rrozema** [comment]
No, this does not solve this issue. This issue asks to add MORE information on errors that occur, not to suppress the symptoms of one particular error that has occured.

My suggestion was to add in CBasePush::ProcessSendValue:
```
else
		{
			_log.Log(LOG_ERROR, "BasePush: Unknown vType %s.", vType.c_str());
		}
```
so that we can see that a particular vType was missed: a push was defined for some value, so the user expects to see it pushed, yet it isn't because the code to do it is missing here. Hence an error should be shown with sufficient details in it to identify what is wrong. 

Edit: After your change I've changed my suggestion to include your correction to suppress more error messages if one was already logged. The last part from line 724 of CBasePush::ProcessSendValue now shows instead of that else below code :
```

		if (szData[0] != 0)
		{
			std::string sendValue(szData);
			if (includeUnit)
			{
				std::string unit = getUnit(delpos, metertypein);
				if (!unit.empty())
				{
					sendValue += " ";
					sendValue += unit;
				}
			}
			return sendValue;
		}
		else
		{
			_log.Log(LOG_ERROR, "BasePush Idx %" PRIu64 "(%d): Could not determine data push value for vType %s.", m_DeviceRowIdx, delpos, vType.c_str());
		}
	}
	catch (...)
	{
		_log.Log(LOG_ERROR, "BasePush Idx %" PRIu64 "(%d): Problem with conversion!", m_DeviceRowIdx, delpos);
	}
	return "";
}

```

Next to that I identified that there are other errors as well when requesting a drop down option value, which go undetected (and causing the baspush error message). To enable us to identify these errors I changed the CBasePush::DropdownOptionsValue() to properly check for valid parameters DeviceRowIdxIn and pos, and log an error -with sufficient detail in it to identify the cause- when incorrect parameters are specified. This is the suggested change:
```
std::string CBasePush::DropdownOptionsValue(const uint64_t DeviceRowIdxIn, const int pos)
{
	std::string wording = "???";
	std::vector<std::vector<std::string> > result;

	result = m_sql.safe_query("SELECT Type, SubType FROM DeviceStatus WHERE (ID== %" PRIu64 ")", DeviceRowIdxIn);
	if (!result.empty())
	{
		int dType = atoi(result[0][0].c_str());
		int dSubType = atoi(result[0][1].c_str());
		
		std::string sOptions = RFX_Type_SubType_Values(dType, dSubType);
		std::vector<std::string> tmpV;
		StringSplit(sOptions, ",", tmpV);
		// 0 pos is always nvalue/status, 1 and higher goes to svalues
		if (pos == 0 and pos < tmpV.size()) {
			wording = tmpV[pos];
		}
		else if (pos > 0 && pos <= tmpV.size())
		{
			wording = tmpV[pos - 1];
		}
		else
		{
			_log.Log(LOG_ERROR, "BasePush Idx %" PRIu64 ": Out of range position %d from options [%s].", DeviceRowIdxIn, pos, sOptions.c_str());
		}
	}
	else
	{
		_log.Log(LOG_ERROR, "BasePush Idx %" PRIu64 "(%d): DeviceStatus not found in db.", DeviceRowIdxIn, pos);
	}
	return wording;
}
```
The error messages listed after this change was made enabled me to identify the 3 different types of errors. One of them being the message you are tryng to mask by suppressing the base push message. Error messages shouldn't be suppressed, their cause should be eliminated.

edit: Fixed a mistake when 0 was specified for pos.

**Comment by rrozema** [comment]
Using above extended error message I found more errors logged:
```
2021-01-02 16:18:56.455 Error: BasePush Idx 521: Out of range position 2 from options [Percentage].
2021-01-02 16:18:56.455 Error: BasePush Idx 521(2): Could not determine data push value for vType ???.
2021-01-02 16:18:56.456 Error: BasePush Idx 521: Out of range position 3 from options [Percentage].
2021-01-02 16:18:56.456 Error: BasePush Idx 521(3): Could not determine data push value for vType ???.
2021-01-02 16:18:56.456 Error: BasePush Idx 521: Out of range position 4 from options [Percentage].
2021-01-02 16:18:56.456 Error: BasePush Idx 521(4): Could not determine data push value for vType ???.
2021-01-02 16:18:56.457 Error: BasePush Idx 521: Out of range position 5 from options [Percentage].
2021-01-02 16:18:56.457 Error: BasePush Idx 521(5): Could not determine data push value for vType ???.
2021-01-02 16:18:56.457 Error: BasePush Idx 521: Out of range position 6 from options [Percentage].
2021-01-02 16:18:56.457 Error: BasePush Idx 521(6): Could not determine data push value for vType ???.
2021-01-02 16:26:57.994 Error: BasePush Idx 690: Out of range position 2 from options [Usage].
2021-01-02 16:26:57.994 Error: BasePush Idx 690(2): Could not determine data push value for vType ???.
2021-01-02 16:34:58.336 Error: BasePush Idx 724: Out of range position 2 from options [Temperature].
2021-01-02 16:34:58.336 Error: BasePush Idx 724(2): Could not determine data push value for vType ???.

```
Idx 521 is dummy, General, Custom Sensor, for which my list of influxdb pushes has no row.
Idx 690 is a zwave device of type Usage, Electric, for which my list of influxdb pushes has no row.
Idx 724 is a zwave device of type Temp, LaCrosse TX3, which IS on my list of influx db pushes.

**Comment by gizmocuz** [comment]
You changes are not 100% correct

`// 0 pos is always nvalue/status, 1 and higher goes to svalues`
Thats not the case, a device could have one option, like a temperature and has nothing to do with nvalue/svalue

`_log.Log(LOG_ERROR, "BasePush Idx %" PRIu64 ": Out of range position %d from options [%s].", DeviceRowIdxIn, pos, sOptions.c_str());
`
This can never happen cause of the way this signal/function is called, position is not relevant in this check

You mention a device that is not in your influxdb push list ? I find that odd as this should have been checked here:

`void CInfluxPush::DoInfluxPush()`

(At the top of the function it checks if it is the list, and if not it should bail out)

Could you make a backup of your database (from the settings), and open this with (for example) SQLite Expert Personal, to see if there is a record ?

**Comment by rrozema** [comment]
That comment is not mine. it is from the original code. I only moved it to a new location because I removed the getpos = pos - 1. I left the comment in because it clarified for me what was going on in this function. Apparently pos == 0 acts like a 'default' and pos == 1 up to size() specifies a specific entry from the options array.

My error log does not agree with your statement that it cannot happen: I do see that error logged several times. This is why we should include assertions like these in the code, to verify that our assumptions are correct.
```
2021-01-03 15:43:02.605 Error: BasePush Idx 374: Out of range position 3 from options [Status,Level].
2021-01-03 15:43:02.606 Error: BasePush Idx 374(3): Could not determine data push value for vType ???.
2021-01-03 15:43:02.606 Error: BasePush Idx 374: Out of range position 4 from options [Status,Level].
2021-01-03 15:43:02.606 Error: BasePush Idx 374(4): Could not determine data push value for vType ???.
2021-01-03 15:43:02.606 Error: BasePush Idx 374: Out of range position 5 from options [Status,Level].
2021-01-03 15:43:02.606 Error: BasePush Idx 374(5): Could not determine data push value for vType ???.
2021-01-03 15:43:02.606 Error: BasePush Idx 374: Out of range position 6 from options [Status,Level].
2021-01-03 15:43:02.606 Error: BasePush Idx 374(6): Could not determine data push value for vType ???.

2021-01-03 16:18:11.084 Error: BasePush Idx 697: Out of range position 2 from options [Percentage].
2021-01-03 16:18:11.084 Error: BasePush Idx 697(2): Could not determine data push value for vType ???.

```
What is odd too, is that sometimes there is a series of messages logged where only the pos parameter varies, like happens above with Idx 374. This pattern does not seem to match any of the calls i could find made to CBasePush::ProcessSendValue(). And I do know the call is made to CBasePush::ProcessSendValue() because every time the 'Out of range ...' message is followed by the '... value for vType ???' message.

I have queried the database using sqlite3 and there is no entry in PushLink for those IDs. 
![image](https://user-images.githubusercontent.com/1747982/103482999-84279180-4de4-11eb-9f27-f8e79b1f515e.png)

So, there are 3 different reasons why the Basepush error message appears:
1 - a device type for which no push method is implemented is added in the list pushes (in my case Thermostat Mode).
2 - somehow an invalid pos-value can be found in the PushLink table. This is -once you know the idx value- easily fixed by opening the entry in the push link list -the dropdown will show with no entry selected-, select an entry and then click 'Aanpassen'.
3 - for unknown reasons sometimes a call to ProcessSendValue() is made for devices that aren't in the PushLink table at all. Sometimes multiple calls are made, one for a series of pos-values.

2 is an example of a good reason to put the Idx value in the error message, using that information the end user can now fix the problem himself.

**Comment by gizmocuz** [comment]
How could a wrong index appear in the database? I do agree that checking if the position is out of range is a good idea of course.
Would have done so myself...
Could you create a PR for that one ?

But what worries me more is that devices are getting through that should have been stopped @ the top of CInfluxPush::DoInfluxPush()

And the only reason I can think of is that this function is not thread-safe, that internally you get two (or more) device updates at lighting speed and 'm_DeviceRowIdx' is overwritten by a new value (that should not been passed) and used downstream
I have a look at this asap, maybe get rid of this member value

**Comment by gizmocuz** [comment]
I removed the dependency of the internal device variable in this patch:

https://github.com/domoticz/domoticz

This should/could solve the problem with the unknown device id's getting through

**Comment by rrozema** [comment]
I'm now building your patch with my CBasePush::DropdownOptionsValue() and improved error messages merged in. If that works I'll make my first PR.... (fingers crossed)

**Comment by rrozema** [comment]
The messages are still there. Actually, it's even worse now. The problem is that CInfluxPush::DoInfluxPush(const uint64_t DeviceRowIdx) determines delpos by splitting the device's sValue at the ';' signs, and using the index into the resulting array as the pos parameter for CBasePush::ProcessSendValue. That last function however expects delpos to be the index into the array created from RFX_Type_SubType_Values(dType, dSubType)'s string value. The both arrays do not map onto the same values. I'll see if I can find some way to map them correctly.

**Comment by gizmocuz** [comment]
@rrozema , I trust the above patch solves the unreferenced devices to be stopped now and you should not see any error anymore ?

**Comment by rrozema** [comment]
No, it doesn't. There were even more messages. In fact the influx link maintenance page doesn't work anymore too. I have fixed the problem, but I have too little experience with git to properly create a pull request. Can you come online in slack and see my messages to you there?

**Comment by gizmocuz** [comment]
My patch had nothing to do with the maintenance page (or what you mentioned in your previous comment that has been removed about index values)
My patch was about correctly blocking devices that are not in the pushlink database table, there have been no other change

**Comment by gizmocuz** [comment]
Sorry, I take that back. I changed more then only this specific check, and forgot a exclamation mark.
This has been corrected and now it should work as intended

**Comment by rrozema** [comment]
Influx pushes work as expected now. No more errors are shown for now. Thanks
