### ISSUE TITLE
Windows 20H2 and plugins

### ISSUE THREAD

**Issue by laoil72** [domoticz/domoticz#4530]
Hello, i have a problem with plugins.

When i try to use it domoticz crash.

I have try different plugins and thid is the same problem.

I dont understand.

![Screenshot_2020-12-22-11-14-55-018_com.android.chrome.jpg](https://user-images.githubusercontent.com/68594459/102877809-a0701980-4447-11eb-8e76-fe22a0ef4612.jpg)

**Comment by gizmocuz** [comment]
Please use the forum! (And you also did not respect the issue guidelines!)
