### ISSUE TITLE
dark-th3me : arrow up and arrow down missing in the Settings / SYSTEM menu

### ISSUE THREAD

**Issue by sd5445fr** [domoticz/domoticz#4537]
[Domoticz Beta 2020.2 (build 12738) on Debian x64 Virtual Machine on Synology Nas using Firefox 84.0 (64 bits) on Manjaro Linux
![dark-th3me_issue](https://user-images.githubusercontent.com/75168525/103087815-08aa3100-45e9-11eb-868e-c899e234f86e.png)
 Cinnamon]

I love the dark-th3me, but I've noticed that the arrow up / down in the Setting / SYSTEM menu are missing. See attached image.

It's just a minor detail. Thanks for the great work you all do. Happy Holidays

**Comment by gizmocuz** [comment]
There are some CSS elements overruled in this theme with the 'important' flag...
like

` font-weight: normal !important;`

and things like:

`font-family: Ubuntu !important;`

will also not work

...

Made some modifications in beta 12760, maybe it's OK now... If not, try using the default theme (which is kinda dark as well)

**Comment by dobber81** [comment]
Arrows are visible in dark-th3me now.

**Comment by gizmocuz** [comment]
Thanks for the feedback! Closing issue
