### ISSUE TITLE
Wrong adress linked to open Z-wave CP

### ISSUE THREAD

**Issue by NiekN** [domoticz/domoticz#4543]
Version: 2020.2 (build 12760)

I have 3x fibaro multi sensors.  two of them are some years and working fine
Now i bought a third one , and that one has issues. Some issues are solved by (https://www.domoticz.com/forum/viewtopic.php?f=24&t=34907&p=264344#p264344). But after that  i still have a issue with the open z-wave  

The two old sensor have the "motion sensor"  linked to 00000A00 and at CP i see also the sensor switch ON/OFF  
But the new one has the motion sensor  linked to 00000F35. the sensor at CP is now always OFF. So i think it is correct linked to 00000F00.

I also removed the node and add it again, as a new one but still  this issue is not solved 
After bug fix at the latest beta version, i still think is still a bug  present at open z-wave

I have a Pi3b with a Z-Wave.Me ZME_UZB1 USB Stick and 3 fibaro multi sesnors

**Comment by kiddigital** [comment]
@NiekN , please check the corresponding Z-Wave xml file that is used to 'define' your sensor in Domoticz. Could well be the case that the XML is different now from the moment that you added the 2 earlier sensors.

You can update the old sensor based on the new XML file using the 'refresh' option.

Beware, in your case that could mean that your old sensors start to behave like the new one. It could mean that the XML file is either not correct (but I would assume the vendor has supplied it) or Domoticz is unable to interpret it correctly.

Let us now how things turn out to debug this.

**Comment by NiekN** [comment]
@kiddigital , sorry im new with that.  Which XML file and where can i file it ?  at /home/pi/domoticz/Config i have some XML files
like manufacturer_specific.xml. And what should i check in the file 

But when i check at CP , i see at current valves of sensors .  i see the 2 old sensors switching, but the new sensor is always OFF 
i will refresh one of the older sensors and check what happons.

**Comment by NiekN** [comment]
running now Version: 2020.2 (build 12763)

I did refresh first the 2 old nodes(at CP refresh node info), but still the same. values are still ok nothing changed
then i  refreshed the the new node and also still the same issue
at old sensors 
00000A00 and 00000A35 are active, when sensor is detecting movement
at new sensor
only  00000F35 is  active, when sensor is detecting movement( but still not 00000F00)

**Comment by gizmocuz** [comment]
@NiekN , xxxxxx35 is a switch ? Why you need it on both devices ?
Is the controller in the same groups as your original 2 motion sensors ? (hardware->zwave->select your nodes and check the groups)
Is it the same hardware revision, are the groups the same ?

**Comment by NiekN** [comment]
when i check the old sensors xxxx35 and xxxx00 are swiching when it detects a movement, why i do not know.
The fibaro multi sensor has 4 sensors , motion, tamper, lux and temperture. But when i check Domoticz (devices) i have 10 Idx numbers for one sensor. Most of them are clear but some i think are double defined.
at CP sensor value i think xxxxx00 is used and now alwasy OFF (even when sensor is detecting a movement)


No they are not at the same group, but they should be. New sensor is not at group 4 and 5
Also the strange think is that the ID is different then the to old ones ( new ID 0X1002,  old ones have ID 0x1001) 

The Hardware revision of the sensors, i do not know where to find. i see Protocol /Application version is different

**Comment by gizmocuz** [comment]
Also make sure they have the same configuration parameters/values
For the index, the first hex code is the node id (in hex) , like 0A is 10, 0F = 15
You have to read the manual, look what those groups are doing, what they are for, and decide if you want (and/or need) the controller in another group then the Lifeline (which is usually group 1)

**Comment by NiekN** [comment]
Group 4 is motion BC
Group 5 is tamper BC

i refreshed all nodes , so parameters are not correct anymore, i will correct them(make them te same). After sometime today they should be also at CP again
then i will add thw new node at the same group

**Comment by NiekN** [comment]
I updated the parameters again en added the new sensor to group  4 en 5 (1 was already added)
and waited for some hours, 
Now it looks like all is working fine, also value of sensor at CP is changed what it should be. Does  adding it to a group 4 and 5 has this effect, it looks like .  

Many thx for helping me and all your good work.

**Comment by gizmocuz** [comment]
Thank you for the feedback. Yes it could be the parameters, but it could also be the groups.
In the manual it will tell you what messages/purpose the different groups have
