### ISSUE TITLE
no new Linux Beta versions since 2020.12.14

### ISSUE THREAD

**Issue by herm42** [domoticz/domoticz#4546]
Hi,

just curious, are there any ongoing Linux build problems?

**Comment by gizmocuz** [comment]
Yes as you can see on travis... problem was an old GCC version, and now a curl upload error...

**Comment by rwaaren** [comment]
Anything we can do to help ?

**Comment by gizmocuz** [comment]
More and more project maintainers seem to have issues with Travis lately.
It's a shame, it worked ... while it worked.
I think we have to move to Github Actions.
If someone could make a start with this, I can add the last deploy part

**Comment by rwaaren** [comment]
Took a peek at this but I don't think I will be able to help here yet. Does anyone know where I could learn this by studying other (similar) projects that already made the move from travis to Github actions? Maybe that will help me understanding.
Until then I will keep compiling domoticz on my own systems.

**Comment by rezzalex** [comment]
I understand the latest beta build are not available...  since a month ?

What can we do to help ?

**Comment by waltervl** [comment]
looks like it is fixed? I see beta 2020.2.2108 2021-01-20

**Comment by rezzalex** [comment]
> 020.2.2108 2021-01-20

where did you see that ?


because here we can see the commits and builds : https://www.domoticz.com/wiki/Domoticz_versions_-_Commits

but there is still an issue. The docker image I am using (thank you @stas-demydiuk ) seems to be builtt automatically based on Domoticz releases, did not work for more than a month: https://github.com/stas-demydiuk/domoticz-docker/issues/15

**Comment by rwaaren** [comment]
The build is fixed but the numbering is still off. Handle with care 😀

**Comment by waltervl** [comment]
> > 020.2.2108 2021-01-20
> 
> where did you see that ?

https://domoticz.com/downloads/ But handle with car, still work in progress.

**Comment by rwaaren** [comment]
In a conversation with @gizmocuz and I tested the download myself

![image](https://user-images.githubusercontent.com/24454798/105218680-c3c8da00-5b55-11eb-931d-54b8d5220244.png)

**Comment by rwaaren** [comment]
Fixed with [commit d85316aa3cd](https://github.com/domoticz/domoticz/commit/d85316aa3cd1d2a772d971e165d585b85f352750)

**Comment by rezzalex** [comment]
Thanks to everyone
