### ISSUE TITLE
Dashboard is not showing all devices in rooms

### ISSUE THREAD

**Issue by isom1266** [domoticz/domoticz#4547]
Version: 2020.2 (build 12772)
Build Hash: e38643616-modified
Compile Date: 2020-12-29 09:33:57
dzVents Version: 3.1.0
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

![1](https://user-images.githubusercontent.com/43316507/103302379-cc6d3b00-4a03-11eb-8699-1c055c76ec74.PNG)
Dashboard is not showing all devices in rooms ...
switching from dashboard to "other" does show the devices ...
if I select a ROOM in the dashboard tab, all devices MUST have the yellow star to show up.
That causes the "all" room to be very crowded ...

**Comment by gryzli133** [comment]
Dashboard is just used for favorite devices. What you are expected there could be eventually a tab, that include all devices - what is not available at the moment. That would make probably sens in some situations. The room filter is always working just for the devices that are specified in current tab. Did you try Floor Plan? This could be the solution you are looking for.

![image](https://user-images.githubusercontent.com/30415928/103334613-56ec8380-4a72-11eb-978d-381c71a2d1ee.png)

**Comment by isom1266** [comment]
The dashboard for all rooms can only show favorites. OK.
Server room dashboard here
showed all devices in the pre-Fix 4519 version
(https://github.com/domoticz/domoticz/issues/4519)
After making the change, you need to add the device to your favorites to see it in the room panel.
This makes the overall dashboard full of all your favorites
![1](https://user-images.githubusercontent.com/43316507/103338685-7b029180-4a7f-11eb-955b-5f36555c7842.PNG)

**Comment by gizmocuz** [comment]
You're correct, when you select a room, it should show you all devices in that room regardless of it is flagged as Favorite.
Fixed in upcoming beta (12778). Seemed to be a issue in the HTML code
Thanks for reporting.

**Comment by Westcott1** [comment]
Thanks, Gizmocuz!
I look forward to 12778.

**Comment by isom1266** [comment]
Thanks, Gizmocuz!!!
You are great
