### ISSUE TITLE
Custom icon upload not working on linux clients/browsers

### ISSUE THREAD

**Issue by tbart** [domoticz/domoticz#4555]
My instance is running 2020.02 on an RPi, but the server side is irrelevant for this issue.
I am trying to upload a custom icon set .zip with both latest firefox on a desktop as well as Chrome on Android.
Both of them produce the same error: "Error uploading Iconset: undefined" after a few seconds.
These issues more or less discuss the same problem:
#4245
The last comment of #2925
#3865
#3316
The forum post at https://www.domoticz.com/forum/viewtopic.php?f=28&t=30754

If I use an evaluation VM of WIN10 as a *client*, the upload works flawlessly with the same server instance, so both permissions on server side as well as the iconset itself can be ruled out.

I dug a little deeper, used firebug, strace'd domoticz, etc.

The temporary file should be put to /tmp/custom_icons.zip as can be seen in CSQLHelper::InsertCustomIconFromZip in main/SQLHelper.cpp

The code however never gets this far.

I tried comparing the requests on IE and firebug and the obvious difference is that there is a response to the POST containing the zip data on Windows whereas there is none on linux/android.

I suspect the issue to be in JS, however I am not a JS pro..

The IE version sets application/x-zip-compressed before the actual zip payload whereas linux sets application/zip. I tried changing this, but it did not seem to work out (by just resending the edited request in firebug, which might not be enough).
Also, Windows sets an absolute path starting with a drive letter, whereas linux sets the filename only. I also tried adding a (fake) drive letter, which also did not change anything.

I think the most important question is if any dev can reproduce this on a non-Windows client/browser.

Most of the issues state it cannot be reproduced, but I never see a mention of what *client* OS/browser got used.

I can provide more debug data if so desired!

Thanks in advance for your continued effort, very much appreciated!

**Comment by gizmocuz** [comment]
The code that handles the upload of the icon is

**CWebServer::Post_UploadCustomIcon**

It expects a field named 'file' , containing the file
This is the actual zip file, not a filename

It also could go wrong here:
**cWebem::CheckForAction**

Maybe you could replicate this by using Postman
(https://stackoverflow.com/questions/39037049/how-to-upload-a-file-and-json-data-in-postman)

I don't know any other tools...

I myself am using Windows (Chrome browser) and have uploaded some icons to my Domoticz instances which run on ARM

**Comment by tbart** [comment]
Dug a lot deeper and captured network traffic to find the actual differences.
It *is* the
Content-Type: application/x-zip-compressed (Windows) vs
Content-Type: application/zip (Linux, most likely also MacOS and other *nixes)
that's present in the payload/form data preceding the actual zip data.

Here is a platform independent test case.
The zip file sent is deliberately empty. -m 2 defines a timeout of 2 seconds. If it is left out, domoticz sends an HTTP OK after several seconds, which is wrong and should be fixed, i.e. a meaningful error message should be sent/displayed.

```
user@host ~ $ curl 'http://domoticz/uploadcustomicon' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: de-AT,en-US;q=0.7,en;q=0.3' --compressed -H 'Content-Type: multipart/form-data; boundary=---------------------------355682961522996338441219645409' -H 'Origin: http://domoticz' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: http://domoticz/' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-binary $'-----------------------------355682961522996338441219645409\r\nContent-Disposition: form-data; name="file"; filename="wan.zip"\r\nContent-Type: application/x-zip-compressed\r\n\r\n-----------------------------355682961522996338441219645409--\r\n' -m 2
{
	"error" : "Error opening zip file",
	"status" : "ERROR",
	"title" : "UploadCustomIcon"
}
```
```
user@host ~ $ curl 'http://domoticz/uploadcustomicon' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: de-AT,en-US;q=0.7,en;q=0.3' --compressed -H 'Content-Type: multipart/form-data; boundary=---------------------------355682961522996338441219645409' -H 'Origin: http://domoticz' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: http://domoticz/' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-binary $'-----------------------------355682961522996338441219645409\r\nContent-Disposition: form-data; name="file"; filename="wan.zip"\r\nContent-Type: application/zip\r\n\r\n-----------------------------355682961522996338441219645409--\r\n' -m 2
curl: (28) Operation timed out after 2003 milliseconds with 0 bytes received
```

I'd be willing to fix this although I am not a real programmer. However, I have a problem finding where to start, as I could not find any mime-type checking code that uses the string application/x-zip-compressed anywhere in the code!

Another "solution" (I'd rather call it hack) would be to override the browser's detected mime-type to the non-standard application/x-zip-compressed. The only valid mime-type assigned by IANA is "application/zip" (https://www.iana.org/assignments/media-types/application/zip) so this should definitely be supported IMHO.

**Comment by tbart** [comment]
Sorry, found it just now, only parts of the string are matched!
```
cWebem.cpp:657 								|| (szContentType.find("application/x-zip") != std::string::npos)
```

**Comment by gizmocuz** [comment]
@tbart , 'find' should give you the position of where the matched string starts... if the string can not be found, it returns std::string::npos
I think we need to check also for "application/zip"

I added a patch in beta version 12812

https://github.com/domoticz/domoticz/commit/3571a43e00246241f16fd6815bade164aeb315ae

Is it possible to check if it is working now ?

**Comment by tbart** [comment]
Sorry, times are pretty busy..

I'm unable to build on my Gentoo desktop as the Makefile does not seem to like my system boost (though it is compiled with all (and more) configure options stated).
Building on my RPi1 is pretty much out of scope.
Are there some ready-made beta builds I could test with?
Other than that I could only try to do a complete local build of all libs etc - which I'd like to avoid if there are easier ways!

**Comment by gizmocuz** [comment]
@tbart, for your raspberry you do not need to build, there are beta releases available
For Ubuntu, you have to follow the same building procedure as the raspberry

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by tbart** [comment]
Alright, found the beta releases at https://releases.domoticz.com/releases/?dir=./beta
now. A link to this location might be useful in the mentioned Wiki article as well.
The RPi is my production system. I have to see how to backup and roll back, then.

**Comment by gizmocuz** [comment]
@tbart, ehmm... 
I hope you installed Domoticz with the sudo command line that is mentioned on the download page here:
https://www.domoticz.com/downloads/

If you want to switch to the beta version, all you have to do is go to the settings page, and set the release channel to 'beta'
After you pressed the save/apply button you can go to Setup->Check for updates

Do note: You can not go back, but that should not be a problem
Of course you can make a full backup of the Domoticz folder and switch back to that if you want, make sure to stop Domoticz first before making the backup

**Comment by waltervl** [comment]
I have no issues in uploading Custom icons on Linux (Ubuntu 20.04 LTS) using 12901

**Comment by gizmocuz** [comment]
Thank you for the feedback. Closing issue

**Comment by tbart** [comment]
Thanks for stepping up, I really meant to finish this by testing as well but these are extremely busy times.

I read that going back after an update would not be possible, that's why I was pretty hesitant on a production system. Thanks for the additional explanation and keep up the good work!
