### ISSUE TITLE
DataPush: Options used as push keys should not be translated

### ISSUE THREAD

**Issue by rrozema** [domoticz/domoticz#4556]
Version: 2020.2 (build 12805)
Build Hash: ca09c4302-modified
Compile Date: 2020-12-31 12:45:30
dzVents Version: 3.1.0
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

This issue was found after I added code to add more logging in basepush (#4528).

The name of the options in push values is currently translated into the language the end user selected for the Domoticz User interface. This has 2 consequences:
1 - if the user decides to change the language the option may change: the link defined for any push on that option will change too. This results in the value in the push link to become invalid (see screen below). It also means the value will no longer be pushed.
![empty push option](https://user-images.githubusercontent.com/1747982/103446166-f3827180-4c7c-11eb-9af3-62591b15f4e5.png)
2 - the option name is used as the key in the external database. The values for one and the same item are suddenly stored under another key: reports and other external programs will no longer find the values under the names they were programmed to look for.

So this is why I state that the option names used in data pushes should not be translated: their English name should be shown and pushed, regardless of the user interface language selected.

**Comment by gizmocuz** [comment]
@rrozema , that is not correct as it is using a number internally (offset), had a look in the pushlink database table
You can also see this in the corresponding HTML/JS code
Maybe some fields are not translated and are displayed blank ?

**Comment by gizmocuz** [comment]
Just verified changing languages, it's working without issues. So what is the English phrase that should be there ?

**Comment by rrozema** [comment]
Looking how to query the sql db for an example ( I don't know what program to use for querying the db). The translation for all existing options is available though, as all of the options are available in the dropdown:
![image](https://user-images.githubusercontent.com/1747982/103454932-d2576a80-4ce8-11eb-9b4b-f16f52d66a07.png)

**Comment by rrozema** [comment]
![image](https://user-images.githubusercontent.com/1747982/103455154-c53b7b00-4cea-11eb-8882-4582944ff51f.png)
244 = pTypeGeneralSwitch,
73 = sSwitchGeneralSwitch
{ pTypeGeneralSwitch, sSwitchGeneralSwitch, "Status,Level" },

So where does that position 5 come from? there are only 2 options. So the only valid positions should be 0 and 1, or 1 and 2 as the position is 1 based (int getpos = pos - 1;)

**Comment by rrozema** [comment]
Sorry for wasting your time. Something _is_ wrong in this area as positions are specified that are out of range for the number of options available, but it's not translations causing this as I suggested. So I'm closing this issue myself.

![image](https://user-images.githubusercontent.com/1747982/103455602-d2f2ff80-4cee-11eb-89f6-06dcaea8de46.png)
![image](https://user-images.githubusercontent.com/1747982/103455154-c53b7b00-4cea-11eb-8882-4582944ff51f.png)
244 = pTypeGeneralSwitch,
73 = sSwitchGeneralSwitch
{ pTypeGeneralSwitch, sSwitchGeneralSwitch, "Status,Level" },

**Comment by gizmocuz** [comment]
You can use (under Windows) the program SQLite Expert Personal edition, you have to look in the database table "PushLink"
