### ISSUE TITLE
Motherboard Sensors on Linux shows wrong disk usage for big partitions

### ISSUE THREAD

**Issue by tofbouf** [domoticz/domoticz#4558]
Hi.

the disk usage computation in HardwareMonitor.cpp returns wrong value for partitions bigger than 2147483647 blocks:

```
toto@tata:/opt/yunohost/domoticz# df -x nfs -x tmpfs -x devtmpfs
Filesystem       1K-blocks       Used  Available Use% Mounted on
/dev/root        115069948    2659756  107694708   3% /
/dev/mmcblk0p1      258095      64613     193483  26% /boot
/dev/sdc2        480321152  158977440  296874976  35% /mnt/shares/volume-2
/dev/sdb2        480321152      74136  455778280   1% /mnt/shares/volume-3
/dev/md127      3363138688 1474835380 1884869088  44% /mnt/shares/volume-1
```
Using the test code from issue #3375:
```
Calculating disk usages...

Disk: /dev/md127, Mount: /mnt/shares/volume-1, Used: 68.6774 %
Disk: /dev/mmcblk0p1, Mount: /boot, Used: 25.0346 %
Disk: /dev/root, Mount: /, Used: 2.31168 %
Disk: /dev/sdb2, Mount: /mnt/shares/volume-3, Used: 0.0154347 %
Disk: /dev/sdc2, Mount: /mnt/shares/volume-2, Used: 33.0982 %
```

With a slighly modified test code, adding read Total and Used blocks in the output:
```
Calculating disk usages...

Disk: /dev/md127, Mount: /mnt/shares/volume-1, Used: 68.6774 %  (TotalB: 2147483647, UsedB: 1474835380)
Disk: /dev/mmcblk0p1, Mount: /boot, Used: 25.0346 %  (TotalB: 258095, UsedB: 64613)
Disk: /dev/root, Mount: /, Used: 2.31169 %  (TotalB: 115069948, UsedB: 2660056)
Disk: /dev/sdb2, Mount: /mnt/shares/volume-3, Used: 0.0154347 %  (TotalB: 480321152, UsedB: 74136)
Disk: /dev/sdc2, Mount: /mnt/shares/volume-2, Used: 33.0982 %  (TotalB: 480321152, UsedB: 158977440)

```
The TotalBlocks reported for /dev/md127 is 2147483647, which is the capped value for signed long (whereas the actual size is  3363138688).

It could be fixed by:

- using unsigned long and %lu in the sscanf format (but it will go up to only ~ 4To partitions)
- using bigger blocks in the df command (16K blocks, for example, to extend correcteness up to 64To partitions).

**Comment by gizmocuz** [comment]
with 4To you mean 4 terabyte ? In that case maybe a solution for larger blocks is better
Could you make the patch/PR ?

**Comment by tofbouf** [comment]
Yes, I meant 4Tb (excuse my french :) ).

it's my very first issue on github, so I'll need to read the guide before doing my very first pull request...
But yes, I think i can make this simple patch (with the larger blocks).

**Comment by gizmocuz** [comment]
Great, thank you ! Else you could use a uint64_t perhaps in the scan function ?

**Comment by tofbouf** [comment]
I've made a quick test with long long variables, and "%lld" format, and results are OK.
I go for this one.

**Comment by gizmocuz** [comment]
Thanks for the PR. It's merged!

**Comment by rwaaren** [comment]
@tofbouf can you please close this issue if all is OK now?

**Comment by tofbouf** [comment]
It's OK. Thanks
