### ISSUE TITLE
Dimmer slider UI glitch

### ISSUE THREAD

**Issue by jhaarden** [domoticz/domoticz#456]
The width calculation of the slider for dimmer switches seems to somewhat incorrect. The rightmost part of the slider is outside of the bounding box. In the picture below, the dimmer has the type "blinds percentage inverted" but the issue is the same if a normal dimmer is used.

![dimmer_slider_glitch](https://cloud.githubusercontent.com/assets/1254179/12919141/ef308070-cf42-11e5-8d7a-6b52a6f4fd4a.png)

I am not very experienced with jQuery and CSS, so it is probably much easier for somebody else to solve this issue.

Domoticz version: 2.4470 (f1ddd03)

Edit:
The screenshot is from the latest version of Google Chrome on Mac OS X. It looks the same in Safari for iOS (iPhone 6) but looks correct in Safari on Mac OS X.

**Comment by nayrnet** [comment]
what theme are you running? do you see this problem with the default theme?

**Comment by jhaarden** [comment]
The screenshot is taken with the default theme, but it's the same with elemental-dark, so I guess the theme has nothing to do with it.

**Comment by nayrnet** [comment]
thats not the default theme, this is:
![screen shot 2016-02-09 at 12 29 38 pm](https://cloud.githubusercontent.com/assets/3732081/12928096/dd3f3132-cf28-11e5-950f-5aae10930b62.png)

wipe out all your caches, including the appcache @ chrome://appcache-internals/

**Comment by jhaarden** [comment]
Maybe I was unclear, but the screenshot was taken when I had selected "default" as theme. However, clearing out the appcache fixed the glitch, so the problem must be in the theme then, right?

On the other hand, having to clear the appcache to get the theme setting to be fully applied seems like another bug to me. Agree?

**Comment by nayrnet** [comment]
problem is with your browser holding onto the cache too long, nothing to do with the theme.. but domoticz is pretty aggressive with caching also, as I think it should be.. having to wipe your caches after changing the styling seems acceptable to me, its not something you should do often and if your developing/debugging a theme there are options to disable caching entirely.

so I disagree, not really a bug.. more of a feature request: add functionality to force all caches to refresh via UI... either way there is a very easy work around, simply flush your caches by hand.. especially when your browser is based off the WebKit engine (Chrome/Safari)

**Comment by jhaarden** [comment]
I'll rephrase myself again. Clearing the appcache fixes the glitch in the sense that the default theme is fully applied, but the glitch is still there if I switch to e.g. elemental-dark again. So, this is still an issue, but not in the default theme.

**Comment by nayrnet** [comment]
well the default theme is the only one thats technically supported.. 

the element-light and element-dark themes are broken for some devices, and have been for a while (since they were introduced IIRC).. I started to fix them and then ran away with it and just created a new theme all together (the elemental one)

Your welcome to submit patches to fix those themes display issues, but only the default theme is going to be maintained by the core developers (and be considered bugs)

I may go back and revisit those themes and try to clean them up, but its not a priority right now. Its alot of work getting a theme to display correctly on all devices with all types of hardware.
