### ISSUE TITLE
Barometer is not displaying the value after sensor update using curl

### ISSUE THREAD

**Issue by ojozef** [domoticz/domoticz#4561]
After using curl to update sensor:

`curl "http://localhost:8080/json.htm?type=command&param=udevice&idx=1&nvalue=0&svalue=1013.00"`

Value and icon are missing under "Weather" tab (see screenshot below). "Log" button does not work (empty screen is displayed).
 
<img width="2506" alt="Screen Shot 2021-01-03 at 4 12 26 PM" src="https://user-images.githubusercontent.com/48872447/103492352-2f354c80-4ddf-11eb-81f3-bd395eb1b4c6.png">

Value is updated correctly in Domoticz, see:

<img width="2506" alt="Screen Shot 2021-01-03 at 4 11 02 PM" src="https://user-images.githubusercontent.com/48872447/103492358-3c523b80-4ddf-11eb-80a5-04aa98b80a46.png">

Repro steps (tested on 2020.2 and on the latest code):

1. Add Dummy Barometer sensor
2. Update this sensor using curl (`curl "http://localhost:8080/json.htm?type=command&param=udevice&idx=1&nvalue=0&svalue=1013.00"`)

Reproduced on Raspberry Pi3 and MacOS (both compiled from source)

Version: 2020.2 (build 12811)
Build Hash: 19c0d8ab0-modified
Compile Date: 2021-01-02 08:03:04
dzVents Version: 3.1.0
Python Version: 3.9.1 (default, Dec 28 2020, 11:25:16) [Clang 12.0.0 (clang-1200.0.32.28)]

Please let me know if you need more details. Thanks!

**Comment by rwaaren** [comment]
Please respect the rules for this issue list (as shown when opening an issue)

**### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* Clear your browser cache + AppCache (two different things!!)**

So please use the forum for these type of questions. 

You also do not use the right svalue Check [Wiki page JSON API](https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Barometer)
