### ISSUE TITLE
MQTT Virtual Sensor triggered but not TASMOTA Device.

### ISSUE THREAD

**Issue by sincze** [domoticz/domoticz#4562]
Domoticz: 2020.2 (build 12741)

I build a flow that with MQTT switches an RFXCOM sensor light without issues On / Off. 
The physical light also goes On / Off 

```
var recipient = parseInt(1134);

if ( msg.payload.nvalue === 1 )
{
msg.payload = { "command": "switchlight", "idx": recipient, "switchcmd": "On" };
}

if ( msg.payload.nvalue === 0 )
{
msg.payload = { "command": "switchlight", "idx": recipient, "switchcmd": "Off" };
}
return msg
```
It is really simplistic 1134 is the IDX of RFXCOM light.

Changing this IDX to a virtual sensor (like tasmota node that is configured for Domoticz and MQTT and working by pressing the domoticz interface on/off), will switch the light icon on/off in the domoticz interface but not the physical light.  

However pressing the virtual sensor icon in the domoticz interface will actually switch the physical light on/off. 

This is or a bug or I'm making a thinking error......
![image](https://user-images.githubusercontent.com/5776333/103562355-39c51400-4ebb-11eb-83cd-11c5da5f66dd.png)

MQTT = Node switched via MQTT however physical light remained off.
Admin = Me pressing the virtual switch in Domoticz and actual light going On/Off
![image](https://user-images.githubusercontent.com/5776333/103562505-7d1f8280-4ebb-11eb-9a82-eedd66dc2a6a.png)

"" = empty is a Tasmota Node I found as a plugin for Node-Red , Don't think it should be necessary to use it but it does work.

**Comment by rwaaren** [comment]
- what is the interface between the virtual switch and Tasmota?
- if the interface is MQTT based; how is your MQTT configured on the domoticz hardware tab? 
- what do you see in the log when pressing the virtual switch?
- what do you see in the log when sending the command via MQTT?
- did you see [this forum post]( https://www.domoticz.com/forum/viewtopic.php?p=263657#p263657)?

**Comment by sincze** [comment]
_What is the interface between the virtual switch and Tasmota?_
I've configured in Tasmota the IDX of the specific virtual device under Domoticz Settings.
I've configured MQTT in Tasmota Device so it works when pressing the virtual interface in Domoticz light goes on/off
It works while pressing the tasmota on/off toggle.... light goes on/off and Domoticz is updated with the new status.
![image](https://user-images.githubusercontent.com/5776333/103648276-e4414380-4f5c-11eb-8b68-385393c2bdf4.png)

_if the interface is MQTT based; how is your MQTT configured on the domoticz hardware tab?_
I've configured it in the following way.
![image](https://user-images.githubusercontent.com/5776333/103648192-beb43a00-4f5c-11eb-800b-3a219af721dd.png)

_what do you see in the log when pressing the virtual switch?_
`2021-01-05 13:51:04.620 Status: User: Admin (IP: 192.***.***.***) initiated a switch command (1848/Lamp_Berging/On)`

_what do you see in the log when sending the command via MQTT?_
`2021-01-05 13:55:55.386 MQTT: Topic: domoticz/in, Message: {"command":"switchlight","idx":1848,"switchcmd":"On"}`

_did you see this forum post?_
 -> Is left at TRUE, so it might be the actual preventing of looping here is that what is suggested ?

**Comment by rwaaren** [comment]
> _did you see this forum post?_
> -> Is left at TRUE, so it might be the actual preventing of looping here is that what is suggested ?

If the command is send via MQTT to domoticz and this setting is set as true, domoticz will not send anything out via MQTT.
So it's at least worth trying..

**Comment by sincze** [comment]
![image](https://user-images.githubusercontent.com/5776333/103687953-677c8c80-4f91-11eb-9349-7477588f26b1.png)

Changing the HARDWARE settings in Domoticz indeed solves the issue. As it states:
_If 'False' this will cause the MQTT message to be echoed back. In most cases this is a bad scenario and should be avoided._

I will leave it like that as in this case it does not start echoinggggggg,  but I can imagine other things can go terribly wrong touching this setting.

So if we consider this as "Works as designed" I'll close the issue.

**Comment by rwaaren** [comment]
Thx  for the feedback. Please go ahead and close the issue

**Comment by sincze** [comment]
After talking to @rwaaren seems to be working as designed.
