### ISSUE TITLE
Download to CSV button not visible on log tab in some of the included themes  

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4563]
As posted on [domoticz Forum](https://www.domoticz.com/forum/viewtopic.php?f=6&t=35100)

Still works on default theme but not on the other included themes.

Not sure yet in which build this happened. In build 12790 it's already gone but I am now checking earlier versions.
I will update this issue when I pinpointed the build where it started

![image](https://user-images.githubusercontent.com/24454798/103763845-b7536600-501a-11eb-87d2-485c956e5643.png)

**Comment by rwaaren** [comment]
Build 12016 was still OK. Issue was introduced in build 12017.

**Comment by michahagg** [comment]
Hi @rwaaren, is this problem still occurring?

**Comment by rwaaren** [comment]
> Build 12016 was still OK. Issue was introduced in build 12017.



> Hi @rwaaren, is this problem still occurring?

@michahagg , 

Thx for reminding me. Issue does no longer occur in build 13311
