### ISSUE TITLE
Z-wave crashing domoticz and auto updates the domoticz/Config folder

### ISSUE THREAD

**Issue by lwalbert** [domoticz/domoticz#4570]
Raspberry pi3
Domoticz 2020.2 (build 12741)

Noticed some strange behavior after 3 crashes yesterday where domoticz suddenly stopped.
OZW_Log indicated "not enough space in stream buffer" 
first crash had only one instance of the error message, the other two had several.
When checking logs and file structure in the Domoticz/Config it looks like I got some new folders and configuration files at the time of first crash. then after restarting even some more files where downloaded to domoticz/Configuration.  
Also the manufactorer_spesific.xml where changed.
compared the manufactorer_spesific.xml with the incremental file .1 and noticed that new hardware devices where present.
Compared it with the manufactorer_spesific.xml here in domoticz github repo. Yup, got new devices.
I have noticed this before build 12741 getting the images folder and it's sub folders in Configuration which doesn't exist in the github repo.

I have not made any scripts doing such kind of upgrades etc.
I normally upgrade by terminal issuing: git pull & make
I did not expect this to happen without actually doing a git pull from domoticz repo on github
Is this a feature or a bug?

so in my opinion zwave or domoticz did a kind of "automatic" update of Configuration folder prior to the first crash.

This happens after restart of domoticz looks like I got the images here:
![image](https://user-images.githubusercontent.com/64552548/103920439-9c175200-5111-11eb-858e-a9be9bfa9ac2.png)

New files located in domoticz/Config:
![image](https://user-images.githubusercontent.com/64552548/103920686-e26cb100-5111-11eb-98f3-f4a31bd4834f.png)

**Comment by lwalbert** [comment]
I think i found the reason.
in file Domoticz/Configuration/options.xml
the following code should be uncommented:
  "!-- Should OZW automatically download new Config File Versions. Default is true "
  **"Option name="AutoUpdateConfigFile" value="false"**

**Comment by lwalbert** [comment]
Option name="AutoUpdateConfigFile" value="false"

**Comment by lwalbert** [comment]
No, didn´t help..
probably need to set this parameter  in open-zwave-read-only folder option.xml file, and compile open-zwave and Domoticz again.

**Comment by gizmocuz** [comment]
@lwalbert , Yes OpenZWave downloads new configuration files by default.
It is also a feature I would like to have disabled, but I can't get it to work.
I committed a patch that sets the '**ZWaveAutoUpdateConfigFile**' to false at startup of the OpenZWave driver initialization
Still, I receive messages like "**User Alert - Manufacturer_specific.xml out of Date**"

In my opinion, when **ZWaveAutoUpdateConfigFile** is set to **false** it should not make any contact to the internet at all.

So for this to be fixed someone needs to check the OZW code (Driver.cpp probably)
(maybe disable all DNS stuff based on the config option)
Maybe it needs a **ZWaveAutoUpdate** option that tells the driver to use any auto update yes or no

**Comment by barts2108** [comment]
[in this compare](https://github.com/domoticz/domoticz/commit/fd6e84898d93690b8cea6b4d9f9397e95629bfa9)

```
line 965 - pDevice = FindDevice(nodeID, instanceID, indexID, ZDTYPE_SENSOR_THERMOSTAT_MODE);
line 942 + pDevice = FindDevice(nodeID, instanceID, ZDTYPE_SENSOR_THERMOSTAT_MODE);

```
By removing the indexID, another FindDevice is called that has a different if statement. without the indexID in the call, the m.second.commandClassId is not taken into account anymore for the if statement inside FindDevice.

In ZWaveBase.cpp the original call was the FindDevice in line 828, after the modification the FindDevice in line 817 is used.

Can that be the problem ?

**Comment by lwalbert** [comment]
Hi @gizmocuz, thanks for feedback:)
was looking at the same part in OpenZWave.cpp as you have fixed. Got the same result "user alert - manufacturer_specific out of date" 
so far no automatic update has occurred yet.

**Comment by gizmocuz** [comment]
@lwalbert , Maybe there have been no new configuration files uploaded to the online openzwave database...
Still the whole code in the Driver.cpp file needs to be discarded if a user does not want this feature
Feel free to close this issue if it's okey for you now

**Comment by lwalbert** [comment]
Hi @gizmocuz, Agree with you. When disabled the driver.cpp should not connect to internet at all.
Looked into the drive.cpp code at least it doesn't start to download new configurations when disabled, it only check revision of manufacturer_specific.xml and inform you that a update is "available" by creating the event user alert - manuf... out of date.
Closing the issue.
