### ISSUE TITLE
Telegram notifications not working properly

### ISSUE THREAD

**Issue by poseidogithub** [domoticz/domoticz#4571]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue..

Hello. 

My telegram notifications dows not work. but sending it as custom HTTP action, they do work (so oes not seem a problem of KEY or chat ID)

I tested it on two separated systems, but to make sure nothing interfered, made a new clean installation of raspbian on a pi zero w, updated and upgraded, and clean installation of domoticz, tried both in stable and in beta.

I get the following error in log, wne trying to send it as Telegram Notification using the TEST button

```
2021-01-07 16:29:06.325 Status: Notification: Domoticz test
2021-01-07 16:29:07.098 Notification sent (telegram) => Failed
2021-01-07 16:29:07.122 Active notification Subsystems: browser, telegram (2/13)
2021-01-07 16:29:07.098 Error: Telegram: {"ok":false,"error_code":404,"description":"Not Found"}
```

If I use custom HTTP, I get the message on telegram, and the logs shows this:

```
 2021-01-08 12:23:57.602 Status: Notification: Domoticz test
2021-01-08 12:24:03.516 Notification sent (http) => Success
2021-01-08 12:24:03.541 Active notification Subsystems: browser, http, telegram (3/13) 
```

Screenshots of config (stable), same config in Beta
![imagen](https://user-images.githubusercontent.com/65620538/104015228-9a529a80-51b4-11eb-9fac-8aecc2d64942.png)
![imagen](https://user-images.githubusercontent.com/65620538/104015243-9e7eb800-51b4-11eb-90a3-6cc5859fe421.png)

**Comment by rwaaren** [comment]
### Issue Guidelines

* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Always state your version and hardware platform when reporting code related issues

> Hello.
> 
> My telegram notifications dows not work. but sending it as custom HTTP action, they do work (so oes not seem a problem of KEY or chat ID)
> 

Please respect the domoticz github guidelines and use he forum for these type of questions!

(and switch API key / chat ID entries in the telegram setting)

**Comment by poseidogithub** [comment]
Sorry I trully believed this was a bug. 
(and I dont see why it's not...) I tried to switch API key / chat ID entries in the telegram setting as you mention and I get a different error)
2021-01-08 15:17:45.521 Status: Notification: Domoticz test
2021-01-08 15:17:46.409 Notification sent (telegram) => Failed
2021-01-08 15:17:46.435 Active notification Subsystems: browser, http, telegram (3/13)
2021-01-08 15:17:46.409 Error: Telegram: {"ok":false,"error_code":403,"description":"Forbidden: bot can't send messages to bots"}

**Comment by jvanderzande** [comment]
> > 2021-01-08 15:17:46.409 Error: Telegram: {"ok":false,"error_code":403,"description":"Forbidden: bot can't send messages to bots"}

This error stems from the fact you are trying to send a message to a BOT from a BOT which simply isn't allowed!
Google is your friend for these kind of issues. ;)

**Comment by poseidogithub** [comment]
> 
> 
> > > 2021-01-08 15:17:46.409 Error: Telegram: {"ok":false,"error_code":403,"description":"Forbidden: bot can't send messages to bots"}
> 
> This error stems from the fact you are trying to send a message to a BOT from a BOT which simply isn't allowed!
> Google is your friend for these kind of issues. ;)

Thanks for your patience on this.

I know it's not working because of a bot can't send messages to a bot, I just wanted to test whay you toldme (switch one for the other) to show you it's not right, so I'm back on square one: as http request it does work, as telegram message it doesnt.

I'm still unsure why are you so convinced it's not a bug. I've tested it in a couple of machines, in a just installed one with the same result.,

**Comment by rwaaren** [comment]
I am quite convinced it's not a bug because I use telegram notifiications on 3 different platforms all on the latest Beta and they do work. 
So please be nice and use the forum

![image](https://user-images.githubusercontent.com/24454798/104044390-8cfdd600-51dd-11eb-8418-f6c5aedb263e.png)

**Comment by poseidogithub** [comment]
> 
> 
> I am quite convinced it's not a bug because I use telegram notifiications on 3 different platforms all on the latest Beta and they do work.
> So please be nice and use the forum
> 
> ![image](https://user-images.githubusercontent.com/24454798/104044390-8cfdd600-51dd-11eb-8418-f6c5aedb263e.png)

Hello. Bugs can happen on certain configurations/networks  etc.
anyhow, many thanks for your time.

I'll get back here when I find what was wrong, just in case something like that happens to someone. 

regards!
