### ISSUE TITLE
Python plugin: slave device do not trigger OnCommand

### ISSUE THREAD

**Issue by darrepac** [domoticz/domoticz#4573]
Hi

Platform: Raspberry Pi (build 12709)

I found a problem with slave/master devices (working on the same Domoticz instance, I am not talking about slave/master domoticz instance).
I have 3 lights
I have 1 dummy device "Roomlight"
I put the Roomlight in the slave area of each 3 lights, so when I turn Roomlight On each 3 lights turn On. It works

But these 3 lights are Shelly lights and they are managed by a plugin (ShellyMQTT).

Problem:
When I trigger the Roomlight, Domoticz turn the 3 lights on but in real the 3 lights stay off (=they are On on Domoticz GUI but in reality the lights are off).
I debug a bit and I saw that the OnCommand function from the plugin never receive any command from Domoticz when I trigger the Roomlight.
It is like if slave/master stuff doesn't trigger OnCommand function...

Known? bug?

**Comment by gizmocuz** [comment]
I think this is by design, when you turn on RoomLight (The Dummy) It just update the status to ON for all masters.
If you really want to turn on all 3 lights, you should create a GROUP, and learn the RoomLight as "Activation Device"

**Comment by darrepac** [comment]
A bit confusing: if the lights were not working through a plugin, I am sure they would have turned on, isn't it.
I will take a look into group stuff, thx

**Comment by gizmocuz** [comment]
No it is not. The slave will never turn on the master. It is just setting the internal state (usage could be a group on/off command)
For your logic, we have Groups/Scenes where you can lean a activation device.

**Comment by waltervl** [comment]
@gizmocuz Sorry to bump an old issue.
Can you please give some feedback what was the original design intent of this Sub/Slave function (in Edit device). What problem did it solve?
I want to document it in the wiki but have an hard time understanding the use case. See also
https://domoticz.com/forum/viewtopic.php?p=275730#p275730
