### ISSUE TITLE
Display problem with long device name

### ISSUE THREAD

**Issue by tygerlord** [domoticz/domoticz#4582]
Hello

I've some display problem with long device name the value of sensors
![Screenshot_2021-01-16 Domoticz](https://user-images.githubusercontent.com/6392685/104819136-ce206680-582b-11eb-835e-bc2ff392922f.png)
 is not clearly show, see screenshot please.

Domoticz 
Version 2020.2 (build 2108)
Build Hash: 7fba2c8-modified
Compile Date 2021-01-10 18:37:10
dzVents Version: 3.1.1
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]

Firefox 
78.16.1esr

**Comment by gizmocuz** [comment]
Please use our forum. And you probably (I hope) know the solution, shorten them!

**Comment by tygerlord** [comment]
Sorry for your stomach trouble, 
You can notice that first part of label is not from me, and the second part  describe witch sensor it is and where it is this way is easy to build script, to see what and where to place them in plans etc A more precise description help user make software more easier to use. 
Sorry I didn't know it was voluntary to have a disgusting display with long name.

**Comment by gizmocuz** [comment]
@tygerlord , surely it is not. You can press the edit button and rename the device.
The long names are caused by a hardware plugin (obviously) zigbee2mqtt.
