### ISSUE TITLE
database backup does not work

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#4583]
### Issue Guidelines
Hello, I have the last beta, today I wanted to make a backup, it doesn't work. When the file is downloaded, the download starts and Domoticz freezes. In the end, nothing is downloaded. it only helps to restart service domoticz.

**Comment by rwaaren** [comment]
I tested the backup button in domoticz on build 12850 and build 12836 on NUC (Debian) and RPI Raspbian (Buster) with chrome browser. Backups are functioning and downloaded to PC.
  
Please respect the issue guidelines:

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.
