### ISSUE TITLE
expand json api for selector switch names

### ISSUE THREAD

**Issue by nayrnet** [domoticz/domoticz#459]
this is an enhancement request to extend the API to include level names, for example the MQTT API publishes the following JSON for a selector switch change that includes the switch name and level, but no indication of what friendly name that level has configured.

`{"Battery":255,"RSSI":12,"dtype":"Light/Switch","id":"000140E0","idx":145,"name":"TV","nvalue":2,"stype":"Selector Switch","svalue1":"40","switchType":"Selector","unit":1}`

Request it to be extended to include an element with levelName, as such:

`{"Battery":255,"RSSI":12,"dtype":"Light/Switch","id":"000140E0","idx":145,"name":"TV","levelName":"Security Cameras","nvalue":2,"stype":"Selector Switch","svalue1":"40","switchType":"Selector","unit":1}`

For example with my Pioneer AVR interface I include the level name in an array so I can have a friendly log name.. with the name exposed via JSON I could simply map that string to the input level and people can change the name alone through the UI.

I imagine custom interfaces using the JSON API would like to know what the level names are instead of a numerical value.

**Comment by gizmocuz** [comment]
Your "Name" field is very unfriendly, how about making this "Friendly" ?

**Comment by gaudryc** [comment]
It seems I have missed something while implementing the Selector switch.
Can someone explain me how MQTT works ?

**Comment by nayrnet** [comment]
MQTT uses the JSON API but instead of using HTTP requests for input and event scripts for return calls it uses a bi-directional PubSub broker so you device updates pushed out in realtime. Its really nice because you dont have to poll domoticz or maintain a bunch of events to keep external integrations in sync.

incoming commands look like: **domoticz/in**
_{"command":"switchlight","idx":145, "switchcmd":"Set Level 40"}_

and all updates come unsolicited like this: **domoticz/out** _{"Battery":255,"RSSI":12,"dtype":"Light/Switch","id":"000140E0","idx":145,"name":"TV","nvalue":2,"stype":"Selector Switch","svalue1":"40","switchType":"Selector","unit":1}_

Its missing the Level Names being exposed like Lua has, so I cant do logic like 
 _if (json.LevelName === 'Security Cameras') doSomeThing();_

Currently I have to match _json.svalue1 === '40'_ and then if I change selector order I have to reconfigure my MQTT software.. I maintain a separate array of level names externally simply so I can have clean logs like, **Changed TV to Security Cameras**, instead of: **Changed TV to Level 40**, Its not very consistent when I get the device name, dtype, stype, and switchType exposed.

@gaudryrc, some unrelated feedback, before the next stable release might reconsider the multiples of 10x for switch levels, a maximum of 10 selections is pretty limiting, I've already hit the limit twice, once for a FM Tuner and again for a PTZ Camera both with more than 10 presets.. I also dont get a Security Camera icon associated with the device however it works great for using Domoticz to make my PTZ do Pseudo AutoTracking, nearly perfect.. I dont need a 100 steps but a few dozen would cover just about everything.. I have 2 PTZ's on opposite corners of the house and they can see every door, window, and gate on my property.

thanks.

**Comment by gaudryc** [comment]
Do I have to send key names as lower case ?

**Comment by nayrnet** [comment]
I dont believe so, Battery, RSSI, and switchType are all mixed case.

**Comment by nayrnet** [comment]
thanks for adding this, I am trying to test it but my build is failing.. I dont think its due to this.
see: https://github.com/domoticz/domoticz/commit/297b11e62c1e285c54a6152bd8f6b7567b70c7a6#commitcomment-16089333

**Comment by gaudryc** [comment]
@gizmocuz ,

Do you think we should send all options ?
Don't you think sending selector actions is not a security leak ?

**Comment by nayrnet** [comment]
ok now I get output with all the LevelNames, I can work with this.. just have to parse through it.
`{"Battery":255,"LevelActions":"|||||","LevelNames":"Off|TV|PS3|PS4|NVR|FM","LevelOffHidden":"false","RSSI":12,"SelectorStyle":"0","dtype":"Light/Switch","id":"000140E0","idx":145,"name":"TV","nvalue":2,"stype":"Selector Switch","svalue1":"10","switchType":"Selector","unit":1}`

I dont think the LevelActions would be useful for MQTT, if you believe they are a security concern you can omit that without issue.. My PTZ Selector's have some HTTP Auth passwords in them.

**Comment by gizmocuz** [comment]
That could be seen as a leak yes

**Comment by gaudryc** [comment]
Ok I will add a filter.
Thank you.
