### ISSUE TITLE
dzVents - JSON:decode fails ungracefully if given very large string to decode

### ISSUE THREAD

**Issue by jefft4** [domoticz/domoticz#4591]
I have a function that checks and emails me device battery levels.  To do this, it has to pull the data from domoticz/json.htm and look for battery levels.  Recently, when the retrieved data is passed to JSON:decode, it fails thus:
`2021-01-24 07:02:01.655  Error: dzVents: Error: (3.1.3) /home/domoticz/domoticz/scripts/lua/JSON.lua:1234: /home/domoticz/domoticz/scripts/lua/JSON.lua:1016: Lua script execution exceeds maximum number of lines`

I added some checks to my event code and found that the string I'm asking it to decode is over 2MB in size(!)

I'm not surprised that it can't handle a string that large; no problem with that, but the error checking in JSON.lua should catch the 'string too large' condition and return gracefully with a failure code.  At present, the way it fails can't be caught and handled by the event; it just terminates the event completely.

Is it possible to improve the boundary checking in the JSON:decode library function?

**Comment by rwaaren** [comment]
The errormessage does come from LuaHandler  / EventSystem.cpp and is generated when the number of processed Lua lines becomes too large. This is a dynamic number because the code cannot forecast this based on the size of the data. The json decoding process does involve recursion and it might be in that part. 

Can you share the JSON string you try to process (via a link in wetransfer or similar)  
That would help me to investigate the issue and potentially to find a root cause.

TIA

**Comment by jefft4** [comment]
Ah, I hadn't looked at the code, but if it's in effect LUA generating LUA, that could be a challenge to trap.

The JSON string is the result of calling /json.htm?type=devices&order=name - because the HTTP API query isn't filtered to just real battery-powered devices, of course it pulls back data for all of the 2292 devices in my system.  The code is adapted from an old forum post; its approach is definitely 'brute force'.  I'll have to take a look at it and see whether I can make it run individual device queries.  It's daft to be blocking the entire event system while it queries 2k+ devices when I only care about 20 or so!

I've copied in the event code below.  Link to the data file coming over shortly.

Aside - I recall that people used this script because we couldn't check battery levels properly directly in dzVents... has that changed?  Maybe this particular nuisance script can be retired and replaced with some nicer dzVents code?

<details>
  <summary>Press key to hide / unhide code</summary>

```
--
-- =========================================
-- Check battery level for all used devices
-- =========================================
--
-- Jeff, 22 Feb 2020
--
-- Script in dzVents, adapted and streamlined from forum posting LUA script
-- Uses JSON data to get battery level as using the dzVents or LUA objects for it doesn't work properly
-- Emails a daily low battery report, if needed, and weekly summary of all battery levels
--

--
-- NB! Every device in domoticz has a BatteryLevel value; most are 255 for non-battery devices
-- It's down to the device whether it reports % or 0-255... so we handle both; check the instructions for which each uses!
--

-- function to check if item is in a list
function findDevice(item, listy)
    for _, x in ipairs(listy) do
        if x.name == item then
            return x.low
        end
    end
    return -1
end

-- main event code
return {
	on = {
		timer = {
		    'at 07:02', 'at 19:02'
		}
	},
	execute = function(domoticz, triggeredItem, info)

        -- Configuration
        BatteryThreshold = 20
        SummaryDay = 7 -- Saturday
        EmailTo = "admin@aaaaaaa.net"
        ReportHour1 = 7
        ReportHour2 = 19
        ReportMinute = 02
        Domoticz = "domoticz.aaaaaaa.net"
        DomoticzPort = "8080"
        Message = ''

        -- List of devices we care to know about; second attribute is battery level range (typically either 100 or 255)
        devicesToCheck = { 
            {name='Lounge rear door', low=10},
		    {name='Dining rear door SW', low=10},
		    {name='Kitchen rear door', low=10},
		    {name='Garage door', low=10},
		    {name='Garage side door', low=10},
		    {name='Kitchen garage door', low=10},
		    {name='Dining room movement', low=10},
		    {name='Coolcam PIR 5 - Kitchen', low=10},
		    {name='Coolcam PIR 4 - Landing', low=10},
		    {name='Hall light level', low=10},
		    {name='Coolcam PIR 2 - Lounge', low=10},
		    {name='Study PIR sensor', low=10},
		    {name='Flood - water pump', low=10},
		    {name='Hank 1 button 1', low=10},
		    {name='Remote 1 button 1', low=10},
		    {name='Remote 2 button 1', low=10},
		    {name='Lounge front TRV mode', low=10},
		    {name='Lounge rear TRV mode', low=10},
		    {name='Myles TRV mode', low=10},
		    {name='Master bedroom TRV mode', low=10},
		    {name='Gym TRV mode', low=10},
            }
        BattToReplace = false
        time = os.date("*t")
        
        -- Get a list of all devices
        json = (loadfile "/home/domoticz/domoticz/scripts/lua/JSON.lua")()
        handle = io.popen("curl 'http://" .. Domoticz .. ":" .. DomoticzPort .. "/json.htm?type=devices&order=name'")
        devicesJson = handle:read('*all')
        handle:close()
        domoticz.log('Battery checker: retrieved JSON data is ' .. string.len(devicesJson) .. ' long.')
        devices = json:decode(devicesJson)

        domoticz.log('Battery Checker: wday = ' .. time.wday)        
        -- Iterate through the device list, checking those we care about (we drive from the JSON list and check vs ours, as that's quicker to do repeatedly)
        for i, dev in ipairs(devices.result) do
            if dev.Used then     -- ignore devices not in use; there are often lots of them!
                batmin = findDevice(dev.Name, devicesToCheck)
                if batmin ~= -1 then
                    bl = dev.BatteryLevel
                    domoticz.log(dev.Name .. ' battery level is ' .. bl .. '% @ ' .. dev.LastUpdate .. ' )')
                    if bl < batmin then
                        Message = Message .. ' **** BATTERY LOW ****  ' .. dev.Name .. ' : ' .. bl .. '% @ ' .. dev.LastUpdate .. '<br>'
                        BattToReplace = true
                    elseif time.wday == SummaryDay then
                        Message = Message .. dev.Name .. ' battery level is ' .. bl .. '% @ ' .. dev.LastUpdate .. '<br>'
                    end
                end
            end
        end
        if BattToReplace or time.wday == SummaryDay then
            domoticz.email('Domoticz battery report', Message, EmailTo)
            domoticz.log('Battery levels email sent')
        end
    end
}

`

</details>

**Comment by rwaaren** [comment]
> I'm not surprised that it can't handle a string that large; no problem with that, but the error checking in JSON.lua should catch the 'string too large' condition and return gracefully with a failure code. At present, the way it fails can't be caught and handled by the event; it just terminates the event completely.
> 

I checked this with your data and I cannot replicate this when I use the proper dzVents methods.
The JSON.Lua does catch the string too large condition and does return gracefully with an error message

```
    -- Get a list of all devices
    handle = io.popen("curl 'http://" .. Domoticz .. ":" .. DomoticzPort .. "/json.htm?type=devices&order=name'")
    devicesJson = handle:read('*all')
    handle:close()
    domoticz.log('Battery checker: retrieved JSON data is ' .. string.len(devicesJson) .. ' long.')
    devices = dz.utils.fromJSON(devicesJson)
	
    if not(devices) then
        domoticz.log('Script continues after the error message', domoticz.LOG_FORCE )
        domoticz.log('Sorry but string could not be converted to a Lua table because of size limit', domoticz.LOG_ERROR)
        return
    end
```

```
2021-01-24 20:19:11.611  Status: dzVents: Info: ------ Start internal script: Script #1: Device: "jsonTrigger (Virtual)", Index: 177
2021-01-24 20:19:11.618  Status: dzVents: Info: Battery checker: retrieved JSON data is 2366889 long.
2021-01-24 20:19:11.998  Error: dzVents: Error: (3.1.3) Error parsing json to LUA table: /opt/domoticz/scripts/dzVents/../lua/JSON.lua:1234: /opt/domoticz/scripts/dzVents/../lua/JSON.lua:1070: Lua script execution exceeds maximum number of lines
2021-01-24 20:19:11.998  Status: dzVents: !Info: Script continues after the error message
2021-01-24 20:19:11.998  Error: dzVents: Error: (3.1.3) Sorry but string could not be converted to a Lua table because of size limit
2021-01-24 20:19:11.998  Status: dzVents: Info: ------ Finished Script #1


```

I understand that this not solve you problem but it is not a domoticz or dzVents code issue.
If you want I am happy to help and solve this using jq  (I did face a similar issue when retrieving very large JSON's for covid 19 reporting and could solve it by using jq filtering  on a linux level ) 
But if you are interested in such a solution, then please move this to the forum.

**Comment by jefft4** [comment]
This is strange!

As you couldn't replicate the problem with that string, I I created a minimal version of the script, in pure Lua and loading the http response from a text file so that it's always the same string.  Most times, I get the same error as from the original code, but sometimes - maybe one in ten - no error (the returned table is then nil, so I guess in these cases, the problem was caught as in your test).

Clearly, JSON.lua can be broken *sometimes*, so there is a problem there.  Where that problem is, I can't say.  The intermittent nature of the problem, even with 100% repeatable input data, suggests that there's something else going on in the system that changes the behaviour of the code. 
Can you think of anything that might have that effect?

Question, aside - there was talk on the forum of fixing the batteryLevel value in dzVents; do you know whether that happened?  That working would make all this JSON manipulation and HTTP querying unnecessary for this particular task.

Test Lua code:
`commandArray = {}

for deviceName,deviceValue in pairs(devicechanged) do
    if deviceName == 'Test switch' then

        print ("JSON decode test event fired");
        -- loop through all the devices

        Domoticz = "domoticz.aaaaa.net"
        --Domoticz = "localhost"
        DomoticzPort = "8080"
    
        -- Get a list of all devices
        json = (loadfile "/home/domoticz/domoticz/scripts/lua/JSON.lua")()
        handle = io.open("/tmp/httpjson.txt", "r")
        --handle = io.open("/tmp/http0.txt", "r")
        devicesJson = handle:read('*all')
        handle:close()
        print('Retrieved JSON data is ' .. string.len(devicesJson) .. ' long.')
        devs = json:decode(devicesJson)
        
        local c=3
        for i, dev in ipairs(devs) do
            print ('Device idx ' .. dev.idx .. ' has name ' .. dev.Name)
            c=c-1
            if c==0 then
                break
            end
        end
    end
end

return commandArray`

Result:
`2021-01-24 20:58:02.498  Status: LUA: JSON decode test event fired
2021-01-24 20:58:02.512  Status: LUA: Retrieved JSON data is 2366889 long.
2021-01-24 20:58:03.105  Error: EventSystem: in TEST decode Lua: /home/domoticz/domoticz/scripts/lua/JSON.lua:1234: /home/domoticz/domoticz/scripts/lua/JSON.lua:1027: Lua script execution exceeds maximum number of lines`

**Comment by rwaaren** [comment]
> Result:
> `2021-01-24 20:58:02.498 Status: LUA: JSON decode test event fired 2021-01-24 20:58:02.512 Status: LUA: Retrieved JSON data is 2366889 long. 2021-01-24 20:58:03.105 Error: EventSystem: in TEST decode Lua: /home/domoticz/domoticz/scripts/lua/JSON.lua:1234: /home/domoticz/domoticz/scripts/lua/JSON.lua:1027: Lua script execution exceeds maximum number of lines`

To really conclude that the code breaks you should add another print in the Lua code after the json:decode step
It now only shows an error message but that does not imply that the error stops the execution of your script.

I can confirm that batterylevels are working and accurate in dzVents in recent builds.

btw. Given the number of unused devices compared to the number of used devices in your system you would limit the size of the JSON to about 450 Kb If you would change the JSON call from

`/json.htm?type=devices&order=name
`

to

`/json.htm?type=devices&order=name&used=true
`

**Comment by jefft4** [comment]
I added an extra print right after the call to JSON:decode.  It was not reached, so that error is terminating (crashing) the script.

Good idea re the used/unused, thanks; the script was filtering that after decoding, but adding it to the query is much better.

So, now we've confirmed that the big lump of JSON sometimes breaks the function.  The error isn't related to the JSON:decode function, it's caused by domoticz when we exceed the maximum number of lines of Lua that can be executed.  I found some references to 100k lines and also some domoticz forum posts (including comments from you and Danny B) that indicate the error is raised by EventSystem.cpp.

If the exception is indeed domoticz saying 'too much Lua!', I guess it would be difficult to have it return nicely to the calling function - as that would require it to execute some more Lua - ?

It's completely reasonable to have the limit to protect domoticz from runaway scripts, unintended loops, etc. , so I think the only solution to this error when it occurs, is to alter the Lua code that's causing it.  It would be helpful to put some notes into the domoticz event system / Lua documentation to tell people that the limit exists, why it's there and what effect it will have if it's exceeded.

On that basis, I'm happy to close this issue as it is something that can't be 'fixed'... it's intended behaviour, just needs increased user awareness.  Do you agree?

I plan to move the event to pure dzVents now, once I've checked how batteryLevel behaves.  Thanks for the update on that and for your other suggestions :-)

**Comment by rwaaren** [comment]
> I added an extra print right after the call to JSON:decode. It was not reached, so that error is terminating (crashing) the script.
> 
> If the exception is indeed domoticz saying 'too much Lua!', I guess it would be difficult to have it return nicely to the calling function - as that would require it to execute some more Lua - ?
> 
> It's completely reasonable to have the limit to protect domoticz from runaway scripts, unintended loops, etc. , so I think the only solution to this error when it occurs, is to alter the Lua code that's causing it. It would be helpful to put some notes into the domoticz event system / Lua documentation to tell people that the limit exists, why it's there and what effect it will have if it's exceeded.
> 

You can use the same standard Lua way of protection that is already used in dzVents 

```
commandArray = {}

    local jsonparser = require("scripts/lua/JSON")
    
    local parse = function(j)
        return jsonParser:decode(j)
    end
        
    print ("JSON decode test event fired");

    -- Get a list of all devices
    handle = io.popen("cat /tmp/httpjson.txt")

    devicesJson = handle:read('*all')
    handle:close()
    print('Retrieved JSON data is ' .. string.len(devicesJson) .. ' long.')
    ok, result = pcall(parse, devicesJson)

    print('Hi there.. Alive and kicking')


return commandArray
```

**Comment by rwaaren** [comment]
Please feel free to re open when you think it is something that needs to be solved in a different way
