### ISSUE TITLE
On windows: Domoticz crashes since v 2020.2.12884 on click Settings

### ISSUE THREAD

**Issue by laplug** [domoticz/domoticz#4593]
On Windows 10: Accessing the Settings page crashes Domoticz v 2020.2.12884 (and 12888)
Windows report:

Source
domoticz.exe

Summary
Stopped working

Date
‎25-‎1-‎2021 11:41

Status
Report sent

Description
Faulting Application Path:	D:\Program Files (x86)\Domoticz\domoticz.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	domoticz.exe
Application Version:	2020.2.0.12884
Application Timestamp:	600d4794
Fault Module Name:	domoticz.exe
Fault Module Version:	2020.2.0.12884
Fault Module Timestamp:	600d4794
Exception Code:	c0000005
Exception Offset:	004c81f3
OS Version:	10.0.19042.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	2beb
Additional Information 2:	2beba6fb4680d73a8c78ca7c24ccdb46
Additional Information 3:	1e06
Additional Information 4:	1e06f0ce5b89fe37e39484f71a2803f2

Extra information about the problem
Bucket ID:	4f0c74a5fe597c1c90d898245b5a3e98 (1213887381495234200)

Windows Log:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="nssm" /> 
  <EventID Qualifiers="49152">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-01-25T10:44:04.8006513Z" /> 
  <EventRecordID>19585</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Nero</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>11644</Data> 
  <Data>Domoticz</Data> 
  <Data>The parameter is incorrect.</Data> 
  </EventData>
  </Event>

**Comment by rwaaren** [comment]
I see the same behavior on Windows. Both locally compiled and downloaded 
Linux version (locally compiled) is OK

**Comment by rwaaren** [comment]
@gizmocuz Tried to debug but need some guidance on how to continue

![image](https://user-images.githubusercontent.com/24454798/105906462-068e2480-6024-11eb-95a3-b928a17cb908.png)

**Comment by gizmocuz** [comment]
If you open the output window (should be there already in the bottom right window where you now have selected the Call Stack window), you should see the error message
The issue is probably because the 'GuiLanguage' array contains 36 items and is declared with 37...
I will have a look as well

**Comment by gizmocuz** [comment]
Yep that was it. When you hover the mouse above the 'first' or 'second' field, it was 0x000000 (null)
The original gui language list was a null terminated array and has been converted to a constexpr std::array by a previous patch
Thank you for looking into this !

**Comment by rwaaren** [comment]
Thx for the quick Fix !

**Comment by laplug** [comment]
Thank you, both!
