### ISSUE TITLE
Device Description (python plugin) is gone when moving device to "Used"

### ISSUE THREAD

**Issue by proditaki** [domoticz/domoticz#4596]
I created a Python plugin. 
When i move one of my devices to "used' the device description is gone.

**Comment by rwaaren** [comment]
> I created a Python plugin. 
> When i move one of my devices to "used' the device description is gone. 


I don't see an issue here. The description field is taken from the select statement an has the right index number.
From experience with below API I know that you have to include the current description to keep it. If you leave it out, the description will become empty.
 
`/json.htm?type=setused&used=true&name=<devicename>&description=<description>&idx=<idx>&switchtype=<switchType>&customimage=<iconNumber>
`

**Comment by proditaki** [comment]
> > I created a Python plugin.
> > When i move one of my devices to "used' the device description is gone.
> 
> I don't see an issue here. The description field is taken from the select statement an has the right index number.
> From experience with below API I know that you have to include the current description to keep it. If you leave it out, the description will become empty.
> 
> `/json.htm?type=setused&used=true&name=<devicename>&description=<description>&idx=<idx>&switchtype=<switchType>&customimage=<iconNumber> `

Ok tnx
I set it to used from the Domoticz web. Not from my plugin. So  maybe the error is there

**Comment by rwaaren** [comment]
If you set it to used from the GUI the API that is send to domoticz is

/json.htm?idx=<idx>&maindeviceidx=&name=<name>&type=setused&used=true

So that is why you loose the description (and the customImage)

**Comment by proditaki** [comment]
Ok thanks.
Does this classify as a bug or ?
Or do i request a feature to add this?

**Comment by rwaaren** [comment]
Why do you set it to unused in the first place?

**Comment by proditaki** [comment]
My plugin uses mqqtt. i add all devices as unused because there are 64 devices.
I store the mqtt topic in the Description field to identify the device to update it.

**Comment by rwaaren** [comment]
Just my 2 cents but if a device is set to unused and you do use it, I am not surprised that you experience some unexpected behavior. Would it possible to set it to used  when creating it?

**Comment by proditaki** [comment]
Yes i can. 
But if i would distribute the plugin and someone would set a device to unused and back to used, the description would be gone. 
So i think i'd have to find another way to store the MQTT topic with the device i'm affraid

**Comment by rwaaren** [comment]
@proditaki,

can you test with 

`/json.htm?type=command&param=setdevused&idx=<device id>&used=<true | false>`
or
`/json.htm?type=command&param=setdevused&idx=<device id>&used=<true | false>&name=<new name>`

This APi calls is available from build 12921 onward and do not clear the description, custom image or other settings when device switches between used=false and used=true

**Comment by proditaki** [comment]
> /json.htm?type=command&param=setdevused&idx=<device id>&used=<true | false>

I tried this on several devices, the Descritiption is saved now.

**Comment by rwaaren** [comment]
Thx for the quick confirmation
