### ISSUE TITLE
MQTT with TLS configuration issue

### ISSUE THREAD

**Issue by FritsdeGroot** [domoticz/domoticz#4597]
### Issue Guidelines

Version 12883
Platform Raspberry pi

I tried to secure my MQTT connection via a self signed server certificate. I followed these instructions:
http://www.steves-internet-guide.com/mosquitto-tls/

With this guide I was able to create a TLS connection between my MQTT server and node red. I verified this by MQTT explorer. In the configuration I was able to switch off "validate certificate"

When connecting to domoticz I get the following error:
<Timestamp>  Error: MQTT: OpenSSL Error[0]: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

I tried to change the openssl conf by toggling the basicConstraints but this had no effect. Is there an option within Domoticz to switch off the certificate validation?

Kind regards
Frits

**Comment by gizmocuz** [comment]
I think you have to also supply the correct CA certificate in the mosquitto configuration
If you google about MQTT and "tls_process_server_certificate:certificate verify failed" you will find a lot of results.
I had this some time ago by using a letsencrypt certificate. It was not enough to provide the cert/key only, but I needed to supply/configure LetsEncrypt's main CA certificate as well

See for example here:
https://stackoverflow.com/questions/58089783/how-to-make-the-tls-work-in-mqtt-via-port-8883

**Comment by FritsdeGroot** [comment]
HI,

Thnx for the reply and the link. I reviewed the link and as far as I know Mosquitto is running fine.
This is the mosquitto.conf I am running
```
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d

#
listener 8883
cafile /etc/mosquitto/ca_certificates/ca.crt
certfile /etc/mosquitto/certs/server.crt
keyfile /etc/mosquitto/certs/server.key
#require_certificate false
tls_version tlsv1 # = tlsv1.0 tlsv1.1 tlsv1.2
```
I am able to connect with Node-red and MQTT explorer via TLS but with the "verify certificate" switched off. But when I configure it within Domoticz I am missing that option
![afbeelding](https://user-images.githubusercontent.com/47210344/106015694-05f69c00-60bf-11eb-94ab-4d0921377442.png)

And when I check the log file it looks like domoticz tries to verify the ca.crt which fails (understandable). Is there an option to turn this verification off in Domoticz?

![afbeelding](https://user-images.githubusercontent.com/47210344/106016078-64bc1580-60bf-11eb-9c53-db96f99187fa.png)

**Comment by gizmocuz** [comment]
Who generated the certificates, you (openssl) or via LetsEncrypt ?

I am not sure if mosquitto (client) has an option to non verify the certificate, if it does have this option, we should maybe use it as default
Do you know of such option ?

**Comment by FritsdeGroot** [comment]
I generated the certs with openssl. 
The Mosquitto client I use which work are nodered
![afbeelding](https://user-images.githubusercontent.com/47210344/106027568-4d832500-60cb-11eb-93a3-f64d93210627.png)

In which I leave the Verify server certificate unchecked.

And I use MQTT explorer
![afbeelding](https://user-images.githubusercontent.com/47210344/106027800-89b68580-60cb-11eb-8f5d-d7083ea3bd6a.png)

Where I also leave the validate certificate unchecked.

**Comment by FritsdeGroot** [comment]
Hi,

On [Mosquitto.org](https://mosquitto.org/man/mosquitto_sub-1.html)  I read the option --insecure. I think that does the trick. 

--insecure

    When using certificate based encryption, this option disables verification of the server hostname in the server certificate. This can be useful when testing initial server configurations but makes it possible for a malicious third party to impersonate your server through DNS spoofing, for example. Use this option in testing only. If you need to resort to using this option in a production environment, your setup is at fault and there is no point using encryption.

**Comment by gizmocuz** [comment]
@FritsdeGroot , thank you for the research. I have a good idea where to look now, but still in your configuration I noticed you are using the mosquitto CA and not the CA that is generated with openssl

So before I make any patches, could you follow this quide:

http://www.steves-internet-guide.com/mosquitto-tls/

That you can disable verification on some clients is nice, but does not say it's a good thing...

**Comment by FritsdeGroot** [comment]
@gizmocuz : I used that specific guide to generate the keys

![afbeelding](https://user-images.githubusercontent.com/47210344/106174278-21cc7180-6195-11eb-9768-0f23d4730290.png)
In step 8 I distributed the ca.crt to the clients (node-red and MQTT explorer) via an upload function. For domoticz I used the reference in the hardware parameter screen. On my raspberry pi I have multiple copies of the CA.crt. So there is a copy of ca.crt in the directory as configured in mosquitto.conf
```
cafile /etc/mosquitto/ca_certificates/ca.crt
certfile /etc/mosquitto/certs/server.crt
keyfile /etc/mosquitto/certs/server.key

```
For Domoticz I left the ca.crt where I created it with openssl and pointed  the `CA filename` attribute towards it.

I agree with you that it is not full secure solution. This is not something you want to expose on the `www`. I also totally agree with the warning of the documentation of Mosquitto.

But I only want the encryption and with this you will be able achieve that.

**Comment by gizmocuz** [comment]
Could you try beta 12913? I disabled the peer verification.

**Comment by FritsdeGroot** [comment]
It looks like it works
![afbeelding](https://user-images.githubusercontent.com/47210344/106727359-aee74e80-660b-11eb-9b12-bb3e9bd864b3.png)

I verified the working and I receive messages via domoticz/out and the instructions via domoticz/in are correctly executed

**Comment by gizmocuz** [comment]
Perfect, thanks for the feedback! Closing issue
