### ISSUE TITLE
Influx DB push rounds 'Total Rain' before sending

### ISSUE THREAD

**Issue by koenkooi** [domoticz/domoticz#4600]
Since a few weeks I've been noticing that the rain graphs in grafana look wrong, I traced it to Domoticz rounding the 'Total Rain' value before sending it. The meter is an Oregon Scientific PCR800.

This is what I see in Domoticz:
<img width="1166" alt="Schermafbeelding 2021-01-29 om 09 22 24" src="https://user-images.githubusercontent.com/259525/106250142-88907000-6213-11eb-9f24-09b42436f767.png">

```
2021-01-29 09:34:34.887 InfluxLink: value Rain-rate,idx=64,name=Regenmeter value=513
2021-01-29 09:34:34.887 InfluxLink: value Total-rain,idx=64,name=Regenmeter value=1.67537e+06
```

This is what I see in influxDB
<img width="407" alt="Schermafbeelding 2021-01-29 om 09 22 58" src="https://user-images.githubusercontent.com/259525/106250193-9a721300-6213-11eb-830b-005f8f688bb3.png">

Scrolling through the influxDB data some more, I only see increments in 10s, e.g. 1675370, 1675380, 1675390. This rounding is clear to see when comparing the graphs:

<img width="1190" alt="Schermafbeelding 2021-01-29 om 09 29 53" src="https://user-images.githubusercontent.com/259525/106250958-a4e0dc80-6214-11eb-8794-939af627038a.png">
<img width="1245" alt="Schermafbeelding 2021-01-29 om 09 32 43" src="https://user-images.githubusercontent.com/259525/106251199-fa1cee00-6214-11eb-9795-73f364b37928.png">

Grafana shows increments in 2.5mm because I have a wide funnel attached to my rain meter that increases the surface area to four times the original size and I have to divide the sensor value by 4. Domoticz not applying the scale factor before pushing is a different bug :)

**Comment by rrozema** [comment]
Could this be caused by [commit 0cd897fe110fb65c2221d5b224f34e4ac9c19d70](https://github.com/domoticz/domoticz/commit/0cd897fe110fb65c2221d5b224f34e4ac9c19d70), where atof() was replaced by std::stof()? atof returns a double, whereas std:stof() returns a float with a smaller range, hence less precision. in BasePush.cpp.

Where the code for rain rate and total rain now reads
`else if (vType == "Rain rate")
		{
			sprintf(szData, "%g", std::stof(rawsendValue));
		}
		else if (vType == "Total rain")
		{
			sprintf(szData, "%g", std::stof(rawsendValue));
		}`

it used to say
`else if (vType == "Rain rate")
	{
		sprintf(szData, "%g", atof(rawsendValue.c_str()));
	}
	else if (vType == "Total rain")
	{
		sprintf(szData, "%g", atof(rawsendValue.c_str()));
	}`

**Comment by gizmocuz** [comment]
@rrozema , I made a small c++ test:

	char szTmp[100];
	sprintf_s(szTmp, "%g", atof(szTotal.c_str()));
	sprintf_s(szTmp, "%g", std::stof(szTotal));


Both do the same thing. (szTmp = "1.67537e+06")

Question is, do we need to use atof/stof at all ? Because they are already strings

I made a patch (available in beta 12936 and up), maybe this solves the problem.

@koenkooi , there is no 'scale factor', the rain rate and total rain is received directly from the RFXCom SDK

**Comment by koenkooi** [comment]
I cherry-picked c61652754bb692a870ba6133f0a43f99afb38cef and can confirm it fixes the issue:

<img width="334" alt="Schermafbeelding 2021-02-11 om 10 46 46" src="https://user-images.githubusercontent.com/259525/107621448-92c05e80-6c56-11eb-9c1a-2a587d67baed.png">

@gizmocuz with scale factor I mean this:
<img width="569" alt="Schermafbeelding 2021-02-11 om 10 47 55" src="https://user-images.githubusercontent.com/259525/107621518-ac61a600-6c56-11eb-9d47-8e2414b323e4.png">

**Comment by rrozema** [comment]
@gizmocuz Your check fails because you're making a classic error: atof returns a double, not a float. Plus, all float arguments to variable argument functions like printf( <format str>, ...) are automatically converted into a double. So your test should have checked
```
char szTmp[100];
sprintf_s(szTmp, "%g", atof(szTotal.c_str()));
sprintf_s(szTmp, "%g", std::stod(szTotal));
```

**Comment by rrozema** [comment]
I am preparing a pr to fix this. It's a mistake made very, very often. in basepush.cpp but also in webserver.cpp. It's a LOT of editting to make it right, so please do merge this one completely when I'm done. ... 

You are right on the fact that it is a string already though. I didn't think of that. I will incorporate that in my PR as well. It will take some more time as it affects many more hardwares than just the rain meter, but I will try to push the PR tonight (after work).

**Comment by gizmocuz** [comment]
@koenkooi , you could be right here... Is it taken into account in the normal web Gui charts ?

**Comment by gizmocuz** [comment]
@rrozema , basically everywhere %g is used and there is no calculation or if/then/else, we can use the rawsendValue

**Comment by rrozema** [comment]
Yes, that's what I meant when I said I didn't think of the fact that it was a string already: I need to remove some of my changes and replace -where possible- with the string value. Not in all places that is possible though: the same problem occurs for voltage, amperage, watts, etc.

**Comment by koenkooi** [comment]
> @koenkooi , you could be right here... Is it taken into account in the normal web Gui charts ?

Yes, in the 'presentation layer' the 0.25x is taking into account. But pushing to influxdb or pulling using another domoticz instance will get the un-multiplied data.
That same happens for offsets, like I have on the pulse counting watermeter, I installed that a year after moving in, so I have to put the offset in the domoticz instance attached to the pulse counter, in the domoticz instance which aggregates everything and finally in grafana. So when I lose pulses due power-failures/reboots/upgrades I need to change that offset in all those places.

**Comment by rrozema** [comment]
ok, so using rawvalue won't do the trick anymore once that gets fixed. If you can wait until tonight, I'll hand you a PR that has std::stod() for all conversions that actually are a double (not a float), plus we will need to agree upon a maximum number of digits and precision for all of the values (so I can include a proper format string).

**Comment by gizmocuz** [comment]
@rrozema , sorry I was already working on this hours ago... I replaced the unneeded string conversions.

@koenkooi , yes there is a difference in some sensors. For example for a temperature sensor the value is adjusted before it is pushed (inside the database, and to everywhere else)
For the rain, I think this is done on the fly when the value is read from the database

The best approach here would be probably to take the adjustment value into account the same way as for a temp sensor (mainworker.cpp, decode_Temp vs decode_Rain)

Now it's (for example) adjusted here: WebServer.cpp line 10253, 15424, 16117
