### ISSUE TITLE
Heiman Siren

### ISSUE THREAD

**Issue by AlexF12004Roma** [domoticz/domoticz#4606]
In OZW seems that Heiman Indoor Siren is in files: https://github.com/OpenZWave/open-zwave/pull/1770

but in Domoticz manufacturer_specific.xml is not present the following row:
`<Product type="8009" id="1000" name="Indoor Siren HS2WD-Z" config="heiman/HS2WD-Z.xml"/>`
I added manually and the devices is correctly show with details.

Only a problem with battery level that is always zero!
Domoticz does not show any battery info but I can find the info back in the hardware, gen5-stick, control panel, device info).

Alessandro.

**Comment by waltervl** [comment]
Is this still an issue with latest stable as config files have been updated (for the last time)...
Also consider migrating to Zwav2Js2MQTT see https://www.domoticz.com/wiki/ZwaveJS2MQTT
