### ISSUE TITLE
DzVents Xiaomi Gateway incorrect device.status 

### ISSUE THREAD

**Issue by sq4bja** [domoticz/domoticz#4607]
Hi,
Domoticz: 2020.2 (build 12896)

After the previous update, DzVents cannot properly read the status of the Xiaomi RGB Gateway device (Xiaomi Gateway plugin).
The existing domoticz.devices (xiaomi) .state == 'On' conditions are not executed properly. Although print (domoticz.devices (xiaomi) .state) shows 'On', the condition is not met:
if domoticz.devices (xiaomi) .state == 'On' then print ('It is on') end

Tom

**Comment by rwaaren** [comment]
> After the previous update, DzVents cannot properly read the status of the Xiaomi RGB Gateway device (Xiaomi Gateway 

I cannot replicatie this with below test script executed in build 12896

```
return 
{
    on =
    { 
        devices = 
        {
            572, 
        },
    },
    
    logging =
    {
        level = domoticz.LOG_DEBUG,
        marker = 'Xiaomi',
    },
    
    execute = function(dz,item)
        dz.log(item.name .. ', state: ' .. item.state ,dz.LOG_DEBUG)
        if item.state == 'On' then 
            dz.log('Device ' .. item.name .. 'type: ' .. item.deviceType, dz.LOG_DEBUG)
            dz.log('Device ' .. item.name .. 'subtype: ' .. item.deviceSubType, dz.LOG_DEBUG)
            dz.log('Device ' .. item.name .. 'hardware: ' .. item.hardwareId .. ', '.. item.hardwareType, dz.LOG_DEBUG)
            
        end
    end
} 
```   


```
2021-02-01 16:18:54.589  Status: dzVents: Info: Xiaomi: ------ Start internal script: Script #1: Device: "Xiaomi RGB Gateway (192.168.192.26) (Xiaomi)", Index: 572
2021-02-01 16:18:54.590  Status: dzVents: Debug: Xiaomi: Xiaomi RGB Gateway (192.168.192.26), state: On
2021-02-01 16:18:54.590  Status: dzVents: Debug: Xiaomi: Device Xiaomi RGB Gateway (192.168.192.26)type: Color Switch
2021-02-01 16:18:54.590  Status: dzVents: Debug: Xiaomi: Device Xiaomi RGB Gateway (192.168.192.26)subtype: RGBW
2021-02-01 16:18:54.590  Status: dzVents: Debug: Xiaomi: Device Xiaomi RGB Gateway (192.168.192.26)hardware: 33, Xiaomi Gateway
2021-02-01 16:18:54.590  Status: dzVents: Info: Xiaomi: ------ Finished Script #1
```

**Comment by sq4bja** [comment]
Ok. I don't know why it stopped working for me:
```
if device.id == OTHER_DEVICE_ID and device.state == 'Off' and domoticz.devices(XIAOMI_GATEWAY).state == 'On' then
     domoticz.devices (XIAOMI_GATEWAY) .switchOff ()
end

```
There were no problems before the update. After removing the condition _domoticz.devices(XIAOMI_GATEWAY).state == 'On'_ everything starts working.

Perhaps my configuration is unique, but I haven't modified this script for several months and the malfunction occurred after the last update.

**Comment by rwaaren** [comment]
Next time something like this happens please post the issue on the forum first and include your complete script and loglines and state the version where it stil worked and current version.
Thanks.
