### ISSUE TITLE
fibaro smart implant fgbs-222 - seperate input/output

### ISSUE THREAD

**Issue by SirStonehill** [domoticz/domoticz#4611]
Domoticz: 2020.2.11995 Stable
OS: Windows 10
Z-wave: Aeotec Z-Stick Gen5

Bug report:
In the node configuration there are parameters 3001 and 3002 to set the Protection Command Class. Setting it to a different value and sending it to the node, does not change this setting in the node. Output still reacts to the input. After reloading the configuration, the 3001 and 3002 settings are back to default. 

When sending the raw Z-wave command to the node (Node-ID, 0x75, 0x01, 0x02, 0x00 for IN1/OUT1), the IN and OUT are disconnected. When reloading the node configuration in Domoticz, the value of parameter 3001 (IN1/OUT1) is set to 'No operation possible'. reading this value from the node works correctly.

Short, sending the command to separate input from output does not work, but reading the setting from the node does.

**Comment by rwaaren** [comment]
> Domoticz: 2020.2.11995 Stable


Please respect below forum rules which are shown to you when opening a new issue

### Issue Guidelines

Before opening a new issue, please review the following:
* First try to update to the latest beta version

**Comment by SirStonehill** [comment]
My apologies for this,
I've got a spare RPI 4, Z-stick and Smart implant to do tests.
Got the latest beta running on RPI 4 and included the Smart implant node.
Same behavior.

Kind regards

**Comment by gizmocuz** [comment]
How do you send the 'raw' z-wave command to the node ?
Did you also try via the control panel ?

**Comment by SirStonehill** [comment]
Hi @gizmocuz , thank you for your reply.

I shutdown the RPI, take out the Z-stick and plug it into my WIN10 PC. Using 'silicon labs Z-wave pc controller 5" [https://www.dropbox.com/s/ru033gbqhqpzv44/ZWavePCController_v5_39.zip](url) I can send the raw command. Got the commands from this link [https://community.athom.com/t/seperate-the-input-from-output-fibaro-smart-implant/28950/31](url) and short instructions from [https://community.home-assistant.io/t/fibaro-smart-implant-fgbs222/147686/22](url).
after plugging the Z-stick back into the RPI and booting, Domoticz shows a different parameter for 3001 and/or 3002.

I remember that I had been in control panel before finding the above. Problem is that parameter 3001 and 3002 are not in the control panel. Those command are not in the fgbs-222.xml file from openzwave.

I'm figuring this all out as I go. I know basic coding and can make some programs (C, C#, XAML, MATLAB,VB, VBA,...) and stuff, but I'm not a pro programmer.

Hope this helps.
Kind regards

**Comment by gizmocuz** [comment]
@SirStonehill , Then you are currently at the wrong address and you need to add these parameters to the configuration file and submit this to OpenZWave
We merge new configuration files from time2time, so it will end up in Domoticz once it's in OpenZWave

**Comment by SirStonehill** [comment]
@gizmocuz , Then where do parameters 3001 and 3002 come from if there not in the xml file. Something or someone must appoint them and give a name, and link the status value to the description name?

Sorry if this is not the appropriate channel to address this issue, just trying to help you guys make a great experience.

Kind regards

**Comment by gizmocuz** [comment]
Probably the Node is telling OZW that these are part of the configuration parameters.
To be able to 'set' them, they need to be defined in the configuration file
