### ISSUE TITLE
Link to domoticz download is dead (404 Not found)

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4613]
First noticed yesterday evening [Forum post](https://www.domoticz.com/forum/viewtopic.php?f=47&t=35429&sid=c23419b5c3bce3c2d5f33223b0b5be2d )

![image](https://user-images.githubusercontent.com/24454798/106851322-4e611b80-66b6-11eb-89fa-8f0038c46d6f.png)

This is also also causing the FTP login within [build script](https://github.com/domoticz/domoticz/runs/1826596482?check_suite_focus=true) to fail.

**Comment by gizmocuz** [comment]
Thanks for reporting! Fixed now
