### ISSUE TITLE
Issue with Custom Icons

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#4617]
Here attached is a small python plugin.

The plugin create a Switch with a custom image "15" Heating device
```
"""
<plugin key="SwitchImage" name="Switch Image" author="pipiche" version="1.0.0">
    <description>
        <h2> Test Switch Image </h2>
    </description>
        <params>
        <param field="Mode6" label="Debug" width="75px">
            <options>
                <option label="True" value="Debug"/>
                <option label="False" value="Normal"  default="true" />
            </options>
        </param>
        </params>
</plugin>
"""
import Domoticz

class BasePlugin:
    enabled = False
    heartbeats = 0

    def __init__(self):
        return

    def onStart(self):
        Domoticz.Debug( 255 )
        myDev = Domoticz.Device(Name="TestSwitch", DeviceID="010203040506", Unit=16, Used=0 , Type= 244, Subtype = 73, Switchtype = 0 , Image = 15)
        myDev.Create()
        Domoticz.Log("Created device: "+Devices[16].Name+ ", myDev also points to the Device: "+myDev.Name+" Image: %s" %myDev.Image)

        return

    def onConnect(self, Connection, Status, Description):
        return

    def onMessage(self, Connection, Data):
        return

    def onDisconnect(self, Connection):
        return

    def onHeartbeat(self):
        return

global _plugin
_plugin = BasePlugin()

def onStart():
    global _plugin
    _plugin.onStart()

def onConnect(Connection, Status, Description):
    global _plugin
    _plugin.onConnect(Connection, Status, Description)

def onMessage(Connection, Data):
    global _plugin
    _plugin.onMessage(Connection, Data)

def onDisconnect(Connection):
    global _plugin
    _plugin.onDisconnect(Connection)

def onHeartbeat():
    global _plugin
    _plugin.onHeartbeat()


```

The device is correctly created in Domoticz when starting the plugin . We can see in the here after screenshot that on the left side the Icon seems Ok
![Screenshot 2021-02-06 at 15 25 24](https://user-images.githubusercontent.com/8291674/107120837-8d969480-688f-11eb-95f8-d1706798aac2.png)

If now, enable the device in order to use it in the Device Section, the Icon is modified to a bulb, see here after
![Screenshot 2021-02-06 at 15 26 41](https://user-images.githubusercontent.com/8291674/107120887-be76c980-688f-11eb-8f34-147ffa08e9ea.png)

Domoticz version  is
2020.2 (Build 12902)

**Comment by pipiche38** [comment]
I have reproduce the problem with a Virtual Switch

1/ create a Virtual device : Switch
2/ Update the Custom Image and put it Heating
3/ Go to the Device List ( we can see that we have the correct image )
4/ Remove the device from the Used List
5/ Update the device to put it to the Used List ( the Icon is changed ) !!!

**Comment by gizmocuz** [comment]
Should be solved now in latest code/beta (12918) version. Is it possible to verify ? (I only tested with the dummy/gui)

**Comment by rwaaren** [comment]
@gizmocuz would it be possible to do the same for the description field? 
(issue #4596)

**Comment by pipiche38** [comment]
Unfortunatly it doesn't compile.

here are the latest lines from the make command

```
In file included from /usr/local/include/boost/system/error_code.hpp:19,
                 from /usr/local/include/boost/asio/detail/throw_error.hpp:19,
                 from /usr/local/include/boost/asio/detail/impl/posix_tss_ptr.ipp:23,
                 from /usr/local/include/boost/asio/detail/posix_tss_ptr.hpp:76,
                 from /usr/local/include/boost/asio/detail/tss_ptr.hpp:27,
                 from /usr/local/include/boost/asio/detail/call_stack.hpp:20,
                 from /usr/local/include/boost/asio/detail/thread_context.hpp:20,
                 from /usr/local/include/boost/asio/detail/recycling_allocator.hpp:20,
                 from /usr/local/include/boost/asio/detail/handler_alloc_helpers.hpp:21,
                 from /usr/local/include/boost/asio/detail/executor_op.hpp:20,
                 from /usr/local/include/boost/asio/impl/system_executor.hpp:18,
                 from /usr/local/include/boost/asio/system_executor.hpp:129,
                 from /usr/local/include/boost/asio/associated_executor.hpp:21,
                 from /usr/local/include/boost/asio.hpp:21,
                 from /usr/share/domoticz/beta-domoticz/main/../webserver/cWebem.h:3,
                 from /usr/share/domoticz/beta-domoticz/main/WebServer.h:4,
                 from /usr/share/domoticz/beta-domoticz/main/WebServer.cpp:2:
/usr/include/c++/10/functional:223:34: note: candidates are: ‘const std::_Placeholder<3> std::placeholders::_3’
  223 |     extern const _Placeholder<3> _3;
      |                                  ^~
In file included from /usr/local/include/boost/bind/bind.hpp:2356,
                 from /usr/local/include/boost/bind.hpp:22,
                 from /usr/local/include/boost/thread/detail/thread.hpp:33,
                 from /usr/local/include/boost/thread/thread_only.hpp:22,
                 from /usr/local/include/boost/thread/thread.hpp:12,
                 from /usr/local/include/boost/thread.hpp:13,
                 from /usr/share/domoticz/beta-domoticz/main/../webserver/cWebem.h:5,
                 from /usr/share/domoticz/beta-domoticz/main/WebServer.h:4,
                 from /usr/share/domoticz/beta-domoticz/main/WebServer.cpp:2:
/usr/local/include/boost/bind/placeholders.hpp:48:38: note:                 ‘constexpr const boost::arg<3> boost::placeholders::_3’
   48 | BOOST_STATIC_CONSTEXPR boost::arg<3> _3;
      |                                      ^~
make[2]: *** [CMakeFiles/domoticz.dir/build.make:519: CMakeFiles/domoticz.dir/main/WebServer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:493: CMakeFiles/domoticz.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
```

**Comment by gizmocuz** [comment]
@pipiche38 , I just compiled new beta's (12920) for Arm, and i suspect github actions will succeed with the Linux x64 build as well.

Could you:
rm -Rf extern
rm -Rf CMakeFiles
rm CMakeCache.txt

and try again, make sure you're on the latest boost as well

**Comment by gizmocuz** [comment]
@rwaaren , I think we need another 'SetUsed(true/false) function ...

**Comment by rwaaren** [comment]
@gizmocuz something like setIdle() and setActive() ?

**Comment by gizmocuz** [comment]
I was thinking about one function with a yes/no as parameter.... Let me see what I can do...

**Comment by gizmocuz** [comment]
I made some changes, new api call (old call was setunsed)

**Enable/Disable a device or sensor**
 /json.htm?type=command&param=setdevused&idx=<device idx>&used=<true/false>&name=<device name>
(device name is a optional parameter)

I am unable to update the wiki at the moment

This might also solve the related issue

**Comment by pipiche38** [comment]
@gizmocuz I do confirm that with Domoticz build 12920 the issue is fixed .

Thanks very much for the fast fix.

let me know if I should leave it open for @rwaaren topic

**Comment by gizmocuz** [comment]
Just made another commit to actually remove it from the event system or reload the current states:

https://github.com/domoticz/domoticz/commit/ef790bae330981427f3dcdce6b0323dd231a245e

Should work even better now

**Comment by aldodemi** [comment]
> @pipiche38 , I just compiled new beta's (12920) for Arm, and i suspect github actions will succeed with the Linux x64 build as well.
> 
> Could you:
> rm -Rf extern
> rm -Rf CMakeFiles
> rm CMakeCache.txt
> 
> and try again, make sure you're on the latest boost as well

@gizmocuz Error in compiling remain in Ubuntu 20.10 groovy and Raspbian GNU/Linux 10 (buster), also when download and compiling from the start. No error on Ubuntu 20.04.2 LTS focal.

**Comment by rwaaren** [comment]
I had the same on Raspberry 4.

solved by:

remove boost 1_72 and install boost 1_75 (maybe 1_74 will also work but not tested), // see instructions on wiki page

```
sudo rm -r dev-domoticz
sudo git clone https://github.com/domoticz/domoticz.git dev-domoticz
cd dev-domoticz
sudo cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt
sudo make -j3
```

**Comment by aldodemi** [comment]
With boost 1_75 it works, thank you.

**Comment by pipiche38** [comment]
thanks
