### ISSUE TITLE
Domoticz 12920 seems break HTTP Listner working (python plugin)

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#4621]
It looks like Domotciz 12920 break something (latest working version was 12917).

In order to reproduce the problem use the simple 'HTTP Listner' plugin

After a while the plugin crash itself

> 
> Feb 07 19:07:25 rasp domoticz[23445]: 2021-02-07 19:07:25.365  (Listner on HTTPS) Processing 'onConnectCallback' message
> Feb 07 19:07:25 rasp domoticz[23445]: 2021-02-07 19:07:25.365  Python Plugin System: (Listner on HTTPS) Calling message handler 'onConnect'.
> Feb 07 19:07:25 rasp domoticz[23445]: 2021-02-07 19:07:25.365  Python Plugin System: (Listner on HTTPS) Connected successfully to: 10.0.0.164:58105
> Feb 07 19:07:25 rasp domoticz[23445]: 2021-02-07 19:07:25.365  Python Plugin System: (Listner on HTTPS) Name: '10.0.0.164:58105', Transport: 'TCP/IP', Protocol: 'HTTPS', Address: '10.0.0.164', Port: '58105', Baud: 0, Bytes: 0, Connected: True, Last Seen: 2021-02-07 19:07:25, Parent: 'Server Connection'
> Feb 07 19:07:25 rasp domoticz[23445]: 2021-02-07 19:07:25.365  (Listner on HTTPS) Processing 'ReadEvent' message
> Feb 07 19:07:25 rasp domoticz[23445]: 2021-02-07 19:07:25.366  Python Plugin System: (Listner on HTTPS) Received 449 bytes of data
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: 2021-02-07 19:07:25.366  Python Plugin System: (Listner on HTTPS)     6f 63 61 6c 4e 65 74 77 6f 72 6b 73 00 66 61 75 59 11 00 00     ocalNetworks.fauY...
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: 2021-02-07 19:07:25.367  Python Plugin System: (Listner on HTTPS)     00 00 00 72 20 00 00 00 72 20 00 00 00 72 20 00 50 00 00 00     ...r....r....r..P...
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [154B blob data]
> Feb 07 19:07:25 rasp domoticz[23445]: [143B blob data]
> Feb 07 19:07:27 rasp domoticz[23445]: 2021-02-07 19:07:27.391  Python Plugin System: (Listner on HTTPS) Pushing 'onHeartbeatCallback' on to queue
> Feb 07 19:07:27 rasp domoticz[23445]: 2021-02-07 19:07:27.423  (Listner on HTTPS) Processing 'onHeartbeatCallback' message
> Feb 07 19:07:27 rasp domoticz[23445]: 2021-02-07 19:07:27.423  Python Plugin System: (Listner on HTTPS) Calling message handler 'onHeartbeat'.
> Feb 07 19:07:27 rasp domoticz[23445]: 2021-02-07 19:07:27.423  Python Plugin System: (Listner on HTTPS) Pushing 'ProtocolDirective' on to queue
> Feb 07 19:07:27 rasp domoticz[23445]: 2021-02-07 19:07:27.423  Python Plugin System: (Listner on HTTPS) Pushing 'ConnectDirective' on to queue
> Feb 07 19:07:27 rasp domoticz[23445]: 2021-02-07 19:07:27.423  (Listner on HTTPS) Processing 'ProtocolDirective' message
> Feb 07 19:07:27 rasp domoticz[23445]: 2021-02-07 19:07:27.424  Python Plugin System: (Listner on HTTPS) Protocol set to: 'HTTPS'.
> Feb 07 19:07:27 rasp domoticz[23445]: 2021-02-07 19:07:27.424  (Listner on HTTPS) Processing 'ConnectDirective' message
> Feb 07 19:07:27 rasp domoticz[23445]: 2021-02-07 19:07:27.424  Python Plugin System: (Listner on HTTPS) Transport set to: 'TCP/IP', 127.0.0.1:8008.
> Feb 07 19:07:27 rasp domoticz[23445]: 2021-02-07 19:07:27.424  Python Plugin System: (Listner on HTTPS) Connect directive received, action initiated successfully.
> Feb 07 19:08:38 rasp domoticz[23445]: 2021-02-07 19:08:38.999  Error: Listner on HTTPS hardware (15) thread seems to have ended unexpectedly
> Feb 07 19:08:53 rasp domoticz[23445]: 2021-02-07 19:08:53.002  Error: Listner on HTTPS hardware (15) thread seems to have ended unexpectedly
> Feb 07 19:09:07 rasp domoticz[23445]: 2021-02-07 19:09:07.006  Error: Listner on HTTPS hardware (15) thread seems to have ended unexpectedly
> Feb 07 19:09:21 rasp domoticz[23445]: 2021-02-07 19:09:21.009  Error: Listner on HTTPS hardware (15) thread seems to have ended unexpectedly
> Feb 07 19:09:35 rasp domoticz[23445]: 2021-02-07 19:09:35.012  Error: Listner on HTTPS hardware (15) thread seems to have ended unexpectedly
> Feb 07 19:09:49 rasp domoticz[23445]: 2021-02-07 19:09:49.016  Error: Listner on HTTPS hardware (15) thread seems to have ended unexpectedly
> Feb 07 19:10:03 rasp domoticz[23445]: 2021-02-07 19:10:03.072  Error: Listner on HTTPS hardware (15) thread seems to have ended unexpectedly
> Feb 07 19:10:17 rasp domoticz[23445]: 2021-02-07 19:10:17.076  Error: Listner on HTTPS hardware (15) thread seems to have ended unexpectedly

**Comment by gizmocuz** [comment]
Looks like the thread is stalled somehow... no idea what is going on from the log. Are other python plugins working ?

**Comment by pipiche38** [comment]
> Looks like the thread is stalled somehow... no idea what is going on from the log. Are other python plugins working ?

@gizmocuz basically the plugin (example HTTP LIstner) doesn't work anymore, and the ZiGate plugin which use the same mecanism ( HTTP listner) as well.

**Comment by pipiche38** [comment]
@gizmocuz  

I'll recompile Domoticz with a revert of 71be7788088b34c6e5da542279bc8a34ebe4f19d  and will let you know the result

**Comment by pipiche38** [comment]
what I did

```
from the 12920 build
git revert 71be7788088b34c6e5da542279bc8a34ebe4f19d
make
```

the plugin behave as expected , so  71be7788088b34c6e5da542279bc8a34ebe4f19d bring a change which break compatibility and either requires changes on the plugin code ( but needs to be understood, especially what the changes do ).

**Comment by pipiche38** [comment]
#4625
