### ISSUE TITLE
Windows Install script does not set log file correctly

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#4622]
When installing the windows version of Domoticz the logfile is not created on the location where you have entered it in the setup script.

So you need to add them manually. 
When running as a service you need to change regkey HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Domoticz\Parameters Add value AppParameters with -log "<Path-to-logfile>"
When running as an app define it in the target field of the properties window. Something like C:\Users\Public\Domoticz\domoticz.exe -www 8080 -sslwww 443 -log "C:\Users\Public\Domoticz\domoticz.log" -loglevel normal,status,error

See also https://www.domoticz.com/forum/viewtopic.php?f=47&t=35433 for more info.

**Comment by waltervl** [comment]
Thank you!

**Comment by gizmocuz** [comment]
@waltervl , Thanks for reporting. Should be fixed in beta 12927 and upwards.
I think it's currently building, but hope it works !

**Comment by waltervl** [comment]
It seems that it is not working https://domoticz.com/forum/viewtopic.php?f=6&t=35766
Edit: additional info: https://domoticz.com/forum/viewtopic.php?f=6&t=35651&p=269843
Reopen this issue or make a new one?

**Comment by gizmocuz** [comment]
Best to continue here... Please have a look in the install script file and try to debug this issue if you are able to

**Comment by laplug** [comment]
@gizmocuz 
Found the culprit: the file path is created in the registry, but without quotes.
So, if the Domoticz log is in a path name with spaces inside, like "Program Files (x86)" nssm.exe wil stumble over the path.
That is most likely the reason why some people (@waaren) experience no problem when installing. Their path doesn't contain spaces.
Apparently the quotes are removed somewhere in the process of writing the registry.

**Comment by gizmocuz** [comment]
I think this is caused by the InnoSetup script, I suspect the in the function 'GetParams', but last time I added quotes, and see them as well in the function:

`Result := Result + ' -log "' + LogConfigPage.Values[0] + '"';`

**Comment by laplug** [comment]
Thank you for checking. I guess InnoSetup is the problem. For the moment I keep installing without -log and inject the correct registry parameter afterwards.

**Comment by laplug** [comment]
@gismocuz
> `Result := Result + ' -log "' + LogConfigPage.Values[0] + '"';`
Shouldn't the quotes be escaped (preceded) by a backslash?
So:
`Result := Result + ' -log \"' + LogConfigPage.Values[0] + '\"';`

**Comment by gizmocuz** [comment]
Well the string is build via single quotes like var a = 'Hello world' , this would mean that you can use var a='Hello "World" !'
If you build your string with double quotes and you need to use a quote, then I would understand the escaping.
But please try it... install innosetup and run the domoticz install script

**Comment by laplug** [comment]
Testing that goes beyond my current knowledge...

**Comment by gizmocuz** [comment]
I think it is installing Innosetup, and use the files from your install folder

**Comment by laplug** [comment]
My install folder contains solely DomoticzSetup_2020_2.13065.exe, history.txt and readme.txt
I'm not a cpp programmer who compiles his own versions...
Maybe some else?

**Comment by gizmocuz** [comment]
The install folder is probably c:\program files (x86)\domoticz ?

**Comment by laplug** [comment]
No, it's not. I always simply download the latest version from the Domoticz download page (Windows version) to my own download location and install from there. Really, I don't want to do things I do not understand and mess up my current installation. 
All I know is that the the quotes are in the iss script, but that they are not in the registry for the log path.
I understand the logic about the single quotes, but apparently Issosetup seems to ignore the double quotes, given what the Event log says (wrong parameter) and the result in the registry.
I thought it might help the developers to bring that to their attention.

**Comment by gizmocuz** [comment]
@laplug , no worries. But are you sure you say you do not know what a installation folder is ? So you are able to use a home automation system, but have no idea how your computer/operating software works ?
I find that odd.... but not impossible *g*

**Comment by laplug** [comment]
No, that is not what I meant - natural language is an imperfect form of communication. :-)
I was referring to the source folder, while you seem to refer to the destination folder.
The iss script uses source folders and files that I do not have, f.e. "Release" and Licence.txt
It would take me many hours, if not days to figure out what to do and what NOT to do. Problem size and problem effort are not balanced for me.
I will patiently wait for someone knowledgeable to test if an escape character is a solution to the -log path quotes problem.
For the moment I have fine workaround by injecting the exported registry entries and restarting the service.

**Comment by laplug** [comment]
@gizmocuz 
Just checked jrsoftware.org, ishelp. [https://jrsoftware.org/ishelp/index.php?topic=params](url) 
Not an escape, but two consecutive double quote characters.
That's why it didn't work before and after inserting the quotes in script.

`The value of a parameter is traditionally surrounded in double quotes (") when it contains a user-defined string, such as a filename. Using quotes is not required, though, but by doing so it makes it possible to embed leading and trailing spaces in the value, as well as semicolons and double-quote characters.

To embed a double-quote character inside a quoted value, use two consecutive double-quote characters. For example:

"This "" contains "" embedded "" quotes"

The compiler would see that as:

This " contains " embedded " quotes

If you want the value of a parameter to be a single double-quote character, use four double-quote characters: """". The outer two are needed to surround the string in quotes; the inner two are used to embed a single double-quote character.`

**Comment by laplug** [comment]
@gizmocuz
It took me several hours, but with succes! 
(I commented out everything in the iss script that I didn't need, and changed the path names)
The registry now shows quotes:
`-www 8080 -sslwww 443 -log "D:\Program Files (x86)\Domoticz\log\domoticz.log"`
And nssm.exe does not complain any longer.
Note the double quotes around the double quote in Line after Result :=
```
function GetParams(Value: string): string;
begin
Result := '-www ' + ConfigPage.Values[0] + ' -sslwww ' + ConfigPage.Values[1];
  if (LogUseLogButton.Checked) then
    begin
      Result := Result + ' -log """' + LogConfigPage.Values[0] + '"""';
    end;
end;'

```

**Comment by gizmocuz** [comment]
Great work !! Thank you for this! I merged your PR !

**Comment by laplug** [comment]
@waltervl  you can close the issue.

**Comment by waltervl** [comment]
Thank you all
