### ISSUE TITLE
EnOcean ESP3: adding profile F6-05-02 (smoke detector)

### ISSUE THREAD

**Issue by alexis-via** [domoticz/domoticz#4623]
I have an Enocean smoke detector Ubiwizz UBILD001-QM which uses the Enocean profile F6-05-02 and an Enocean dongle USB310.

I know that this profile is **not** supported yet by Domoticz, and I'm working on implementing it. I studied the Enocean Serial Protocol 3 and the details of the profile F6-05-02 (a very simple profile !). And I started to dive in domoticz/hardware/EnOceanESP3.cpp

When I press the test button of my smoke detector, it enters the method ParseRadioDatagram https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1117 and I get the following logs :

2021-02-08 21:20:19.110  EnOcean: destination: 0xffffffff RSSI: 30
2021-02-08 21:20:19.110  EnOcean: RPS data: Sender id: 0x058e8fbd Status: 00 Data: 00
2021-02-08 21:20:20.134  Status: EnOcean: 01 (07/07) F6 00 05 8E 8F BD 00 00 FF FF FF FF 4C 00

In this method ParseRadioDatagram, when I look at "case RORG_RPS" https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1680 (the smoke detector uses an RPS telegram), the code doesn't seem to be organized to support several profiles: it seems that it only implements profile F6-02-01 (Rocker switch, 2 Rocker), because it uses variables T21 and NU which are specific to that profile AFAIK. I would need to write code in there to add support for profile F6-05-02, but I feel the code is not ready to support a new profile. On the opposite, when I look at the code of "case RORG_4BS" https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1169 I have the feeling that the code is organized to support several profiles.

How can we implement several profiles in case RORG_RPS ? 
How can we make the distinction in the code between F6-02-01 and F6-05-02 ? I must say that, after studying the Enocean telegram structure for packet type = Radio (0x01) and RORG = RPS, I don't know how we are supposed to differenciate the different profiles.

Thanks in advance for your help!

**Comment by alexis-via** [comment]
In the Enocean equipment profile V3.1 document, section 3.2.1 "RPS Teach-in", they explain that there is not special telegram for teach-in; a normal data telegram is used for teach-in. And they explicitly say that the profile must be configured per-senderID on the controller (i.e. on Domoticz).
But, when I look at the code here https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1711  
when the SELECT on EnoceanSensors returns nothing, there is no code to make an INSERT INTO to create the device (such code exists in RORG_4BS and RORG_UTI). So how are we supposed to create Enocean RPS devices with the current code ?

**Comment by alexis-via** [comment]
On that line of code https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1204 in RORG_4BS, there is a log line that says "_Teach-in data contains no EEP profile. Created generic A5-02-05 profile (0/40°C temp sensor); please adjust by hand using Setup button on EnOcean adapter in Setup/Hardware menu_". I'm surprised by this log message because in the menu Setup/Hardware, there is no "Setup" button on my Enocean USB dongle.
Is this log message still relevant ?
If yes, it could be an idea for RPS devices: users would manually adjust the profile via a configuration in Domoticz.

**Comment by gizmocuz** [comment]
@alexis-via , It has been a very long time since I worked on EnOcean.
I remember I build support for teach-in for switches, if you add a EnOcean switch there is a teach-on option

**Comment by alexis-via** [comment]
Thanks for your answer @gizmocuz 
I don't understand where is the teach-in option you are referring to. When I add a switch, I don't see such an option:

![enocean_manual_add_switch](https://user-images.githubusercontent.com/1157917/107356747-7810ad00-6ad1-11eb-8643-cd63059c89ba.png)

I continued my development on EnOceanESP3.cpp, and I added the INSERT INTO EnoceanSensors when the SELECT doesn't return anything. My EnoceanSensors table now has my smoke detector. In the short term, we could imagine to change the Profile in the SQLite DB via a manual UPDATE request. I'll continue my investigation in the code.

**Comment by alexis-via** [comment]
Another thing I don't understand in the code: in the method ParseRadioDatagram, in the "case RORG_RPS" (= profiles that start with F6), there is a reference to a profile D2-01-XX here https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1716 ; D2 profiles are VLD profiles, so they should match on "case RORG_VLD" here https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1971. Maybe those lines of code are just "lost" in RORG_RPS...

**Comment by xbeaudouin** [comment]
@alexis-via Oh nice there is some guru on EnOceanESP3... Tried to add Tri2sys with EEP profile D2-01-01 but I didn't figured how to make this working.
The product is : http://www.trio2sys.fr/index.php/fr/produits-enocean-sans-fil-sans-pile-interoperable/recepteur-sans-fils-sans-pile-interoperable-enocean?task=files.getfile&file=fiches_techniques_fr/FT_10020093.pdf

**Comment by alexis-via** [comment]
@xbeaudouin I'm not an EnOcean guru... I only own an Enocean smoke detector (I don't have any other Enocean device) and I read the Enocean specs (well, only the RPS part). It's the first time I write C++ code, so I still have to learn that language.

Good news: I continued on the implementation, and I have the first results:
- my Smoke detector device is now automatically added in the Device list on the first Enocean paquet received
- when I create a switch from this device by clicking on the green arrow, then the status of the switch is updated

I'm happy with this first achievement :)

I'll try to make a fire tonight to test the "real" smoke alarm. In fact, when you click on the Test button of the smoke detector, it generate a "Smoke Off" Enocean paquet. From my experience, the only way to make it generate a "Smoke On" Enocean paquet is with a real fire (which is not very convenient !).

Next steps:
1) finalize implementation (requires more C++ learning !)
2) cleanup code
3) create pull request

**Comment by alexis-via** [comment]
BTW, I plan to implement all F6-05 profiles because they are very similar:
- F6-05-00: wind detector
- F6-05-01: water leakage detector
- F6-05-02: smoke detector

**Comment by gizmocuz** [comment]
Great news !!

**Comment by alexis-via** [comment]
I cleaned up my code. I'll do the test tomorrow with a real fire (the problem with this smoke alarm device is that you can't test it at night when the rest of the family is sleeping !!!) to see if it works "in real life", and also check that the switch goes back to off when the smoke ends.

@gizmocuz 2 more questions for you:
1) I noticed that rssi is always set to 12 in Enocean for "tsen.LIGHTING2" and I read in a forum that the value should be between 0 and 10 and 12 means "RSSI disabled". It is because nobody has implemented it yet? If yes, I think it should not be difficult ; I could propose that in another PR.
2) I don't understand how debug logs work. I did "cmake -DCMAKE_BUILD_TYPE=Debug CMakeLists.txt", but I still don't have the logs that are defined inside #ifdef ENOCEAN_BUTTON_DEBUG. On the other hand, when I use _log.Debug(DEBUG_HARDWARE, "xxx") in the code, it works as expected. So I'm planning to use _log.Debug() in my PR... is it ok ? (_log.Debug() is never used in EnOceanESP3.cpp !).


@xbeaudouin I had a look at the code for your profile D2-01-01 (and I invite you to do the same !).
First D2 corresponds to RORG_VLD, so you should have a look at https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1971 (for paquet reception).
Then D2-01 starts on this line: https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L2010
And, as you can see below, D2-01-0C is supported, but not D2-01-01.
It's probably not very difficult to add support for it. D2-01-01 and D2-01-0C are very similar, and D2-01-0C just has a few additional features compared to D2-01-01, but these additional features are probably not implemented in Domoticz, so the code could be common. So I would start by removing the "switch (type)" + "case 0x0c" here https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L2013 and then start to play with the code.

**Comment by gizmocuz** [comment]
@alexis-via , that is correct. When using 12, you do not see a RSSI value in the device list.
If you use a value from 0-11, it will show up (it's how strong the signal is received)

Using the debug log is also perfect.

While you are here, could you change all log functions (_log.Log(xx,"EnOcean: some message") to Log(xx,"some message)

This should have worked (cmake -DCMAKE_BUILD_TYPE=Debug), but I only tested this with Visual Studio (as this is my compile/debug enviroment)

**Comment by alexis-via** [comment]
Here is a demo of my smoke detector in Domoticz: setup and use (with a real fire !) https://www.youtube.com/watch?v=s0fu1bFiu2Y
