### ISSUE TITLE
Error in 1-wire devices

### ISSUE THREAD

**Issue by dwhile** [domoticz/domoticz#4626]
Adding 1-wire devices results in missing devices.

I have 2 1-wire temperature sensors connected to a Raspberry Pi running the latest version of Domoticz.
Version: 2020.2 (build 12926)
Build Hash: 4bb40f8b2-modified
Compile Date: 2021-02-08 07:36:50
dzVents Version: 3.1.4
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

Domoticz is built from source.

Adding the hardware in Domoticz results in only one of the temperature sensors appearing in the list of devices, however the log file shows 2 temperature devices.

Relevant lines from the log file:

2021-02-09 09:39:51.859  Status: Using 1-Wire support (OWFS)...
2021-02-09 09:39:52.040  1-Wire: Lighting 2 (Switch)
2021-02-09 09:39:52.046  1-Wire: Lighting 2 (Switch)
2021-02-09 09:39:52.063  1-Wire: Lighting 2 (Switch)
2021-02-09 09:39:52.069  1-Wire: Lighting 2 (Switch)
2021-02-09 09:39:54.053  1-Wire: Temp (Temperature)
2021-02-09 09:39:54.057  1-Wire: Temp (Temperature)

Screen shot of the relevant devices:
![1-wire](https://user-images.githubusercontent.com/13201004/107345812-e34f8480-6abb-11eb-9371-18f18d57210b.png)

**Comment by gizmocuz** [comment]
Maybe this has to do with the ID's of the sensors... they need to be very unique as it is truncated to 16 bit

**Comment by dwhile** [comment]
Sensor 1 - 28.AAFE4A070000
Sensor 2 - 12.A8903B000000 - This is a temperature/pressure sensor

I think this has something to do with the directory structure.

Sensor 1 is a temperature sensor at /mnt/1wire/28.AAFE4A070000/temperature
Sensor 2 is combined at /mnt/1wire/12.A8903B000000/TAI8570/temperature

Sensor 2 has an extra directory level in it.

**Comment by waltervl** [comment]
What happens if you only attach 1 device (the one without temp device in Domoticz) to your RPi? Is the temperature device created? What does the log file show, perhaps run Domoticz in debug mode?
