### ISSUE TITLE
Deleting 1-wire hardware causes web server to stop

### ISSUE THREAD

**Issue by dwhile** [domoticz/domoticz#4627]
Having added 1-wire hardware and finding that it doesn't find all sensors, i then deleted the hardware. This causes the web server to timeout.

Domoticz is compiled from source.
Version: 2020.2 (build 12926)
Build Hash: 4bb40f8b2-modified
Compile Date: 2021-02-08 07:36:50
dzVents Version: 3.1.4
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

Error from the log file:
2021-02-09 09:51:11.551  Error: WebServer:8080 thread seems to have ended unexpectedly (last update 69.000000 seconds ago)

**Comment by gizmocuz** [comment]
Does it happen all the time ?

**Comment by dwhile** [comment]
It's happened every time I've tried it (about 3/4 times)

**Comment by Rixerx** [comment]
Unfortunately, the same situation occurs for me.

**Comment by waltervl** [comment]
Do you delete the hardware 1-wire from menu setup hardware or delete first the attached devices and then the empty hardware?
