### ISSUE TITLE
Device created bij Darksky api seem to be linked?

### ISSUE THREAD

**Issue by TheReptile** [domoticz/domoticz#4632]
Today I discovered the following.

I use the Darksky api for weather reports.

So I have picked the device with type 'Temp + Humidity + Baro'
This device creates 2 sensors, one in the 'Temperature' and one in the 'Weather' tab.
When I make the sensor on the Temperature tab a favorite, the sensor from the Weather tab is also favorited.

This shouldn't happen, since both sensors have a different idx?

Running on a pi 3b, build 12946

**Comment by TheReptile** [comment]
Hmm, I must have mislooked, both sensors have the same idx. So I guess this is as designed?

**Comment by gizmocuz** [comment]
Yes it is, please use our forum
