### ISSUE TITLE
Local Networks (no username/password) - network IP validation

### ISSUE THREAD

**Issue by kpalczewski** [domoticz/domoticz#4636]
Version: 2020.2
Build Hash: b63341bc0
Compile Date: 2020-04-26 13:47:55
dzVents Version: 3.0.2
Python Version: 3.6.9 (default, Oct 8 2020, 12:12:24) [GCC 8.4.0]
Ubuntu 18.04 kernel 4.15.0-135-generic
Intel CPU - Pentium G4400

When I have in Local Networks (no username/password):
`127.0.0.*`
everything is fine, I open domoticz.exampledomain.com in browser and I have to log in. apache is proxying to apropriate ip:port.

`127.0.0.*;10.8.0.*`
everything is fine, I have to log in.

`127.0.0.*;10.20.0.*`
I don't have to log in. 10.20.0.* is my local network IP address.

My IP address is `5.184.59.32`

**Comment by rwaaren** [comment]
`127.0.0.*;10.20.0.*`
> I don't have to log in. 10.20.0.* is my local network IP address.
> My IP address is `5.184.59.32`

Please respect the rules for this github issues. One of the rules is:

**First try to update to the latest beta version**

What do you see in the domoticz log about this incoming connection? Look for something like

`2021-02-14 08:09:44.666  Status: Incoming connection from: 192.168.192.112
`

**Comment by kpalczewski** [comment]
@rwaaren this seems to be an issue with my apache configuration.

`  ProxyPass / https://domain.com:domoticzport/
  ProxyPassReverse / https://domain.com:domoticzport/
`

makes connection to domoticz from local network. So the validation on domoticz part is correct.

**Comment by gizmocuz** [comment]
@kpalczewski , maybe this helps ?
https://www.domoticz.com/wiki/WebServer_Proxy

**Comment by kpalczewski** [comment]
@gizmocuz yes. I found this today and setting up RemoteProxyIPs resolved the issue.
