### ISSUE TITLE
Unable to set Tado hot water setpoint

### ISSUE THREAD

**Issue by gerard76** [domoticz/domoticz#4641]
Domoticz Version: 2020.2 (build 12947)
I am unable to set my Tado hot water Setpoint.

Enabling hard debug logging I saw the response error I got from Tado: `2021-02-15 21:08:23.667  Debug: Tado: Response: {"errors":[{"code":"unsupportedForZoneType","title":"Operation 'create HEATING overlay' is not supported for zone type HOT_WATER","zoneType":"HOT_WATER"}]}`

Checking the Tado.cpp code I noticed the overlay type is hardcoded to 'HEATING' (https://github.com/domoticz/domoticz/blob/db346f96e289dc20c0d33c3cffefbb6d4065cc76/hardware/Tado.cpp#L150)

Looking at the network traffic in my browser while setting the hot water temperature I can see it uses the type HOT_WATER when calling https://my.tado.com/api/v2/homes/440675/zones/0/overlay

<img width="990" alt="Screenshot 2021-02-15 at 21 17 52" src="https://user-images.githubusercontent.com/765547/107990053-db1fa980-6fd3-11eb-8ae2-7d479ae4cb30.png">

**Comment by waltervl** [comment]
@dotms @LarsenDX (as being the main maintainers of this Tado integration) Can you verify this issue?
@gerard76 is it still an issue?

**Comment by gerard76** [comment]
Yes.

Domoticz Version 2022.1 (build 14190) 
Unable to set Tado hot water temp. The interface and regular log will not show any problems, but you will notice in your Tado app or web interface that the temp is not changed. 

Starting Domoticz with a debug log produces:
```
2022-02-15 12:32:49.349  [72e75200] Debug: Tado: Node 2 = home Thuis zone Hot Water device 2
2022-02-15 12:32:49.858  [72e75200] Debug: Tado: Response: {"errors":[{"code":"unsupportedForZoneType","title":"Operation 'create HEATING overlay' is not supported for zone type HOT_WATER","zoneType":"HOT_WATER"}]}
```

So type HEATING is send when it should be HOT_WATER

**Comment by LarsenDX** [comment]
I am not the original author of Tado.cpp . I've fixed bugs which limited the number of Tado devices (thermostats) Domoticz can handle.
I have no HOT_WATER devices in my house, and as far as I can tell from the code, HOT_WATER devices have not been implemented.

**Comment by dotms** [comment]
@waltervl For the record: I am no longer maintaining this for quite a while now. I have no Tado thermostat anymore so there is no way for me to perform any meaningful development. Looking at the source code a lot of it has changed (for the better) since my initial version.

**Comment by waltervl** [comment]
So waiting for someone with Tardo controlled hot water device and coding skills to make this enhancements.

**Comment by gerard76** [comment]
You can enable hot water features on the Tado by changing your heating device to one that also supports hot water on https://app.tado.com/nl/main/settings/ 'Remeha Celcia 15' for example.

You do not actually *need* the actual device

**Comment by gizmocuz** [comment]
Closing issue as this is a tado issue. Probably the code has already been adopted since 2 years
