### ISSUE TITLE
Presentation of numbers in the web ui

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#4647]
There is small bug in the presentation of numbers in the web ui.
![2021-02-17_09-37-39](https://user-images.githubusercontent.com/24824113/108177874-0ef9ec80-7104-11eb-957b-09ad47a61adb.png)
It should be presented as:    Lux:  4.582 lx   or   Lux: 4,582 lx depending on what decimal system you use.
This is present in more devices if not all.

**Comment by gizmocuz** [comment]
I think this has to be fixed in the initializer of HighCharts. I'm not aware we say which decimal system to use, so it should work automagically I suppose ?
