### ISSUE TITLE
Restarting Hardware viad Json API disable all logs

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#4648]
If you use the json API to restart or update an hardware even if you specify LogLevel to 7, the parameter is not taken in consideration

For example, here is the URL used to Update a particular hardware

`http://rasp.local:8080/json.htm?type=command&param=updatehardware&htype=94&idx=10&name=DIN%20ZiGate&address=0.0.0.0&port=9999&serialport=/dev/serial/by-id/usb-FTDI_ZiGate_AC3JVNBY-if00-port0&Mode1=DIN&Mode2=&Mode3=False&Mode4=9440&Mode5=&Mode6=0&extra=Zigate&enabled=true&datatimeout=0&LogLevel=7`

The LogLevel feature was introduced with #4581

**Comment by rwaaren** [comment]
Can you try again and use loglevel? (lowercase)

**Comment by pipiche38** [comment]
@rwaaren thanks that make it. Sorry for been to fast .
