### ISSUE TITLE
Update documentation for Synology

### ISSUE THREAD

**Issue by babeuloula** [domoticz/domoticz#4652]
Hi,

On your documentation (https://www.domoticz.com/wiki/Synology), Domoticz for synology will no longer be updated by the maintainer. 

How we can install domoticz on Synology ARM without install IPKG ?

Thanks

**Comment by gizmocuz** [comment]
Does your Synology supports docker containers ? If yes, try the official docker.
If not, maybe you or someone else can continue the work of the previous maintainer, or you can switch to a Raspberry Pi (with docker) or any other platform

**Comment by babeuloula** [comment]
Unfortunately no, my Synology does not support Docker

**Comment by markruys** [comment]
@gizmocuz, I've installed Domoticz on a Synology using Docker. Inspired by https://www.domoticz.com/forum/viewtopic.php?t=35639, but it can be done simpler. If you like, I'll update https://www.domoticz.com/wiki/Synology with a Docker how-to.

**Comment by gizmocuz** [comment]
@markruys , yes please go ahead. Do you have a wiki login ?

**Comment by markruys** [comment]
@gizmocuz , I'm afraid I don't have a wiki login.

**Comment by waltervl** [comment]
@markruys if needed I can update the wiki for you but then I would need the text.

**Comment by markruys** [comment]
Something along the lines of:

Install as follows ([inspiration](https://www.domoticz.com/forum/viewtopic.php?t=35639)):

* At the registry tab, download the Domoticz image
* At the Image tab, click on Launch:
  * Container name: Domoticz
  * Execute container using high privilege (to access devices like `/dev/ttyACM0` or `/dev/ttyUSB0`)
  * Advanced settings:
    * Advanced settings: Enable auto-restart
    * Volume: Add Folder:
      * Create Folder 'domoticz', select this folder
      * Mount path: `/opt/domoticz/userdata`
    * Port settings:
      * Local port 7080, container port 80
    * Environment:
      * WWW_PORT: 80
      * SSL_PORT: 0
      * LOG_PATH: `/opt/domoticz/userdata/domoticz.log` *(only for dubugging)*

Settings:

* Websitebeveiliging: username & password

URL=http://www.jadahl.com/iperf-arp-scan/DSM_7.0/geminilake
for module in ch341 cp210x pl2303 ti_usb_3410_5052; do
  if [ -f /lib/modules/$module.ko ]; then
    echo Module $module already exists
  else
    sudo wget $URL/$module.ko -O /lib/modules/$module.ko
  fi
done

sudo tee /usr/local/etc/rc.d/start-usb-drivers.sh <<'HERE'
#!/bin/sh
case $1 in
  start)
    insmod /lib/modules/usbserial.ko > /dev/null 2>&1
    insmod /lib/modules/cdc-acm.ko > /dev/null 2>&1
    insmod /lib/modules/cp210x.ko > /dev/null 2>&1
    insmod /lib/modules/ch341.ko > /dev/null 2>&1
#   insmod /lib/modules/pl2303.ko > /dev/null 2>&1
#   insmod /lib/modules/ti_usb_3410_5052.ko > /dev/null 2>&1
#   insmod /lib/modules/ftdi_sio.ko > /dev/null 2>&1
    ;;
  stop)
    exit 0
    ;;
  *)
    exit 1
    ;;
esac
HERE
chmod a+x /usr/local/etc/rc.d/start-usb-drivers.sh

### Security

* Certificate:
  * Install domoticz.paracas.nl using LetsEncrypt


### Login Portal

* Advanced, Reverse Proxy:
  * Domoticz
    * General: domoticz.paracas.nl, 443, enable HSTS, HTTP, localhost, 7080
    * Custom header: WebSocket

I need to go through it in detail, perhaps add some screen shots and add a note on requirements like which DSM version, etc.

But I think it's better that you let me update the wiki. You can remove my privileges afterwards, if you like.

**Comment by waltervl** [comment]
Yes, it would be better that @gizmocuz creates a wiki account for you. I cannot do that unfortunately.

**Comment by gizmocuz** [comment]
Hi Mark, I send you the details to login into our wiki. Thanks!

**Comment by waltervl** [comment]
Documentation in Wiki has been updated, Thanks @markruys !
