### ISSUE TITLE
Bug introduced as part of commit 71be778

### ISSUE THREAD

**Issue by brucemiranda** [domoticz/domoticz#4654]
I was doing some updates on hardware/EvohomeRadio.cpp and noticed that one line below that I myself had submitted as a PR was missing. 
`RegisterDecoder(cmdDHWSettings, boost::bind(&CEvohomeRadio::DecodeDHWSettings, this, _1));`

I traced the issue back to this commit 71be7788088b34c6e5da542279bc8a34ebe4f19d

You will notice that the commit makes changes to quite a lot of files. So I have no idea how many other files are affected. 

I will fix this in my latest commit.

**Comment by gizmocuz** [comment]
Thank you !

**Comment by brucemiranda** [comment]
Closed via PR https://github.com/domoticz/domoticz/pull/4663
