### ISSUE TITLE
modify updatebeta.sh so it creates a backup of beta or domoticz folder for easy restore

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#4655]
A lot of people just run updatebeta without precautions and run into trouble when the beta has a major failure (shit can happen ;-) ).
As proposed in Forum topic https://domoticz.com/forum/viewtopic.php?f=6&t=34721&p=266798
Modify the updatebeta script to copy the downloaded domoticz_beta.tgz to a save location in case you need to revert to a previous version.

For example:
```
# START OF MOD
# rm domoticz_beta.tgz DEACTIVATED
mv domoticz_beta.tgz ~/domoticz_beta.tgz_$(date +%Y%m%d_%H%M%S)
# keep only the last 2 copies
ls -t ~/domoticz_beta.tgz* | tail -n +3 | xargs -r rm
# END OF MOD
```

Even better solution would be to copy and tar the current domoticz folder to a save location and then update to beta.
eg tar -zcvf ~/domoticz.backup.tar.gz  ./domoticz

**Comment by waltervl** [comment]
If the principle is acceptable I could try to make a pull request for it after testing the scripts on my environment.

**Comment by gizmocuz** [comment]
@waltervl , Not only users run the updatebeta or updaterelease scripts, but also the application itself when you update via the web interface.
You should however 'copy' this file, in the installation folder (so ./ and NOT ~/)
Even better would be to store it in the userdata folder, but that will make it very complex as this is a command line parameter.

But, sometimes there are database patches and you can not revert to a previous version, making things much worse

So best practice is to backup the complete Domoticz folder (or at least the Domoticz executable and the database), or having a second Domoticz installation where you can test the beta, and when OK update your main Domoticz.

the principle/idea is fine of course ! ;)

**Comment by waltervl** [comment]
status update: Script is ready including copy of complete domoticz folder. Manual beta update works. Now I have to check a couple of days to see if it works for update through Domoticz web UI.

**Comment by gizmocuz** [comment]
@waltervl , I would not copy the complete Domoticz folder as this takes 'a lot' of time and we want the update process as quick and smooth as possible.
It is also very easy to do this by hand ?

**Comment by waltervl** [comment]
Live update succeeded for the first time.
The backup process I have configured,  see also the code snippet from the update script:

1. remove the old backup (if existing) to prevent backing up the backup. Name based on installation folder. I do not know if someone decided to install domoticz in another folder than domoticz.
2. process is started from domoticz folder so go 1 step higher
3. backup complete domoticz folder except the database backup folder. This way also changes to existing scripts, plugins, (stupid) changes in sources, themes etc are backed up. Files size should be limited as there is not that much difference with the standard domoticz.beta tar except the database, plugins and scripts. Better safe than sorry I think.
4. move backup into the domoticz folder
```
echo "Updating to latest beta version..."
echo "Creating backup of current install..."
# remove old backup
base=$(basename $PWD)
rm -f $base.backup.tar.gz
cd ..
# create backup in parent folder (mostly home)
tar --exclude $base/backups -czf $base.backup.tar.gz $base
# move backup to domoticz folder
mv $base.backup.tar.gz $base/$base.backup.tar.gz
echo "Backup ready"
cd $base
echo "Downloading and installing new beta..."
```

**Comment by cmesoar** [comment]
Thanks for this!! Saves manual (error prone) effort and I am all about saving keystrokes (and hey - remembering to do it - senior moments are a terrible thing) and making sure there is a safety net.
