### ISSUE TITLE
devices_list (and devices_list_onoff) command does not check if hardware is enabled

### ISSUE THREAD

**Issue by kiddigital** [domoticz/domoticz#4657]
The 'devices_list' command (GetDevicesList) return al devices that are marked as Used but it does not check if these devices might be related to hardware that has been disabled

```
result = m_sql.safe_query("SELECT ID, Name FROM DeviceStatus WHERE (Used == 1) ORDER BY Name");
```

example
![user-devices](https://user-images.githubusercontent.com/12084477/108607418-a9865400-73c0-11eb-97d0-82c5f550a2cd.jpg)

While here only the first devices comes from enabled hardware while the others come from disabled hardware.

Not sure if this is intended or a bug. Maybe @gizmocuz or @rwaaren any ideas?

It is not used a lot other than for the Users and the DataPush services (as far as I can tell now)
```
main/WebServer.cpp:                     RegisterCommandCode("devices_list", [this](auto &&PH1, auto &&PH2, auto &&PH3) { Cmd_GetDevicesList(PH1, PH2, PH3); });
main/WebServer.cpp:                     RegisterCommandCode("devices_list_onoff", [this](auto &&PH1, auto &&PH2, auto &&PH3) { Cmd_GetDevicesListOnOff(PH1, PH2, PH3); });
www/app/DPFibaroController.js:                          url: "json.htm?type=command&param=devices_list",
www/app/DPFibaroController.js:                          url: "json.htm?type=command&param=devices_list_onoff",
www/app/MobileNotificationsController.js:                               url: "json.htm?type=command&param=devices_list",
www/app/UsersController.js:                             url: "json.htm?type=command&param=devices_list",
www/app/DPInfluxController.js:                   url: "json.htm?type=command&param=devices_list",
www/app/DPHttpController.js:                            url: "json.htm?type=command&param=devices_list",
www/app/DPHttpController.js:                            url: "json.htm?type=command&param=devices_list_onoff",
www/app/DPGooglePubSubController.js:                     url: "json.htm?type=command&param=devices_list",
www/app/DPGooglePubSubController.js:                     url: "json.htm?type=command&param=devices_list_onoff",
```

I think one of the questions is what to do when users are 'assigned' to devices and than the hardware modules gets disabled. Do the assignments have to be removed? Or just not shown? And re-appear when.if the hardware modules gets enabled again?

Just stumbled on this when testing some additions to the authorization system I am trying to make. I am happy to fix it if it needs fixing...

**Comment by gizmocuz** [comment]
It is intended. Because you could temporarily disable hardware and won't see the devices or could add/delete the devices

**Comment by waltervl** [comment]
Then I close this with your permission ;-)
