### ISSUE TITLE
Change in commit 66eb37276b causes wait for commandShell processes already ended

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4658]
Found in build 12972 but probably already in the system in 12970 ( commit 66eb37276b )

in SQLHelper.cpp

when triggering an async  domoticz.executeShellCommand the timeout handling is done by 
function ManageExecuteScriptTimeout

triggered by 
T = std::make_shared<std::thread>(&CSQLHelper::ManageExecuteScriptTimeout, this, pid, timeout, &stillRunning, &timeoutOccurred);

with commit 66eb37276b this was changed to
T = std::make_shared<std::thread>([=]() mutable { ManageExecuteScriptTimeout(pid, timeout, &stillRunning, &timeoutOccurred); });

But this change cause the function ManageExecuteScriptTimeout to no longer recognize that the process ended and so it keeps looping until the timeout time passed and then tries to kill the no longer existing processid.

The issue will not break anything but throws an error in the log stating a process is still running and that it's killed now. Not sure what it does for response / performance.

I reverted this change in #4659 and it solves the looping.

**Comment by gizmocuz** [comment]
Thank you for this ! Yes that PR could have been tested a little bit more....
@neheb , I much appreciate your contributions, but is it possible to run the dzVents tests to validate all is still working correctly ?
(folder dzVents\runtime\tests\)
