### ISSUE TITLE
Domoticz core dump while closing application

### ISSUE THREAD

**Issue by gaudryc** [domoticz/domoticz#466]
Hi @gizmocuz,

Please take a look at the attached core dump. You will see some reference to the class AsyncSerial.

Do you think we really close serial ports properly while the application is closing ?
I think not because the AsyncSerial::close is not always called while stopping, please see OpenZWave/ZWaveBase code.

[core.dump.txt](https://github.com/domoticz/domoticz/files/127777/core.dump.txt)

**Comment by gizmocuz** [comment]
Did not known that ZWaveBase had serial code, maybe its the Razberry (which i dont support)
Personally i dont have this close issues here... so maybe its the enocean ?
It happens just after enocean closes

EnOcean: Serial Worker stopped...
2016-02-08 17:33:14.354  Error: Domoticz received fatal signal 11 !...

**Comment by gaudryc** [comment]
OpenZWave extends ZWaveBase. When domoticz stops OpenZWave hardware, it stops ZWaveBase but the ZWaveBase::StopHardware does not stop anything but its own thread.

About EnOcean, I see it also but I don't see anything special in the code to explain that.

Maybe I'm wrong but I'm trying a patch to stop the serial port on OpenZwave when the StopHardware is called.

To be continued ;-)

**Comment by gaudryc** [comment]
Are you aware of a problem in the method below ?
The method always returns before executing "pimpl->io.post(boost::bind(&AsyncSerial::doClose, this));".

```
void AsyncSerial::close()
{
    pimpl->open=false;
    if(!isOpen()) return;

    pimpl->io.post(boost::bind(&AsyncSerial::doClose, this));
    pimpl->backgroundThread.join();
    pimpl->io.reset();
    if(errorStatus())
    {
        throw(boost::system::system_error(boost::system::error_code(),
                "Error while closing the device"));
    }
}
bool AsyncSerial::isOpen() const
{
    return pimpl->open;
}
```

**Comment by gms1** [comment]
in OpenZWave the AsyncSerial is not used; only referenced as a base class, so only the default ctor and dtor are getting called ( because AsyncSerial is boost::noncopyable )

**Comment by gaudryc** [comment]
So we can remove this reference ?

**Comment by gms1** [comment]
only the boost::noncopyable makes sense to me

**Comment by gaudryc** [comment]
COpenZWave is not intended to be a base class, so I've just remove the AsyncSerial class inheritance from COpenZWave (#470). Now I understand that my problem cannot be wtih OpenZWave ;-)

To intend to fix the current issue I've submit a patch (#469) to really close async port when it is needed and free all associated resources.

**Comment by gizmocuz** [comment]
Is this issue solved/detected?

**Comment by gaudryc** [comment]
Since #469 has been merged, you can close it.
Thanks!
