### ISSUE TITLE
Feature Request:  Add hint to search field for dev id on "Devices" page (ZWave)

### ISSUE THREAD

**Issue by sundansx** [domoticz/domoticz#4660]
the problem:
Previously the device listed contained the hexid for each device.  It was easy to search for devices by using that; for instance "0x01".  A main contributor decided that was redundant information;  fair enough. It gets real hard when I am looking for dev id "02" as that appears in every device in my list.
Feature Idea:
Is it possible to use a hit in the search field for users to restrict the data set to something like the device id?  Maybe the feature is something like "dev:48" or a special character like "d48" that would just search the highlighted device id?  Another option is a pulldown next to the search box to select "device" or "ID" that would restrict it to the highlighted deviced id.  Searching the whole ID field would pick up sub ids as well, so that would not be ideal.
thanks for any consideration and the authors hard work on an excellent program.

**Comment by sundansx** [comment]
Possible fix for this by adding back some old code that has been tweaked.  This will add some text "dev." to the Hardware field.  In the search box the user can put "dev.[decimal id]" with [decimal id] being the decimal id of intrest and it only shows that device's functions.  This fixes both problems as both hex and decimal values are only shown once...and the rows are more dense (which is why I suspect the hex id was dropped).
In \Domoticz\www\app\devices\Devices.js, Line 638, function refreshDevices():

> 				    else if (typeof(item.HardwareTypeVal) != 'undefined' && item.HardwareTypeVal == 21) {
> 					var ZWID = item.ID.substr(-4, 2);
> 					if (ZWID == '00') {
  > 						ZWID = item.ID.substr(-2, 2);
> 					}
> 					ZWID = '0x' + ZWID;
> 					var ZWIDdec =  ("00" + parseInt(ZWID)).slice(-3);
> 					item.HardwareName = item.HardwareName + " dev." + ZWIDdec
> 				    }
>

**Comment by sundansx** [comment]
Hmm, this is not considering an autorefresh of the devices page.  If you refresh this page in the browser or push the refresh button, the .dev suffix is appended.  if it auto refreshes the list via a device data change, it drops the suffix.  There is another place that this needs to be added other than the refreshDevice() function.  Please help, devs.

**Comment by gizmocuz** [comment]
I changed the topic as this relates to OpenZWave devices.
For most devices (as you can see in that javascript function) additional 00 are inserted and your hardware has a name
For example if your hardware is called "ZWave" and you are searching for device 2, you can type this in the search field

zwave 0002

Also, you do this probably a very few times to label your devices and add them to the system.

Yes it's maybe annoying now , but it's possible.

In the feature someone might add the devices in the OpenZWave setup page

**Comment by sundansx** [comment]
if I do that on my secondary device I get 28 devices, most unrelated.  with a big list this gets cumbersome:
![image](https://user-images.githubusercontent.com/25075847/108620636-3f7ea680-73e2-11eb-869d-034dfa781d57.png)

**Comment by sundansx** [comment]
this is probably the biggest usability problem with domoticz.  When I started to use it for the first time, I was bewildered by this.  I have several friends that are now using it and they also needed an explanation of how it works...and it was not very easy to explain - I got a lot of 'why?'.  It was not very intuitive like most other things in domoticz.  I think what would be ideal would be a tree view in the hardware screen or a link that would take a person to a filtered device list for that hardware node.  The flow of association is the person includes a node, then they then need to take the node they just added and somehow bridge the association of it to a device function list...it is a leap right now.  I am sure you have bigger fish to fry, but if you have a kernal of an idea of how one could do this, that might be a good starting point for someone to pick up.  I might later, but I don't have time now.

**Comment by gizmocuz** [comment]
@sundansx , I already explained this a lot.
NO, we are NOT going to ADD a specific hardware device ID in a generic device list
Yes it currently sucks, I do agree, and yes, it might cost you a minute to find your device
And YES you do know your node ID (like 2B) so use that as well

This has to be displayed inside the OpenZWave hardware setup page as mentioned before.
My time is limited, so if someone beats me to it, that would be great.
You can also add this and submit a PR
