### ISSUE TITLE
Bug: Inclusion/Exclusion Text on Pairing dialog invisible

### ISSUE THREAD

**Issue by sundansx** [domoticz/domoticz#4661]
On windows domoticz version Version: 2020.2 (build 12972), using Chrome and Firefox, the dialog for "including Zwave Node" and "Excluding Zwave Node" normally prints out the text of what node it included or excluded.  On this build it shows nothing for the device info.  Upon further inspection, It appears the text is printed as white on white and can be highlighted by draging the mouse over the text.

![image](https://user-images.githubusercontent.com/25075847/108613555-eb56d080-73a7-11eb-92f5-7cd1dd458cc3.png)

![image](https://user-images.githubusercontent.com/25075847/108613531-ccf0d500-73a7-11eb-91c1-4f4fb6eb8e9b.png)

**Comment by gizmocuz** [comment]
Are you using the default Domoticz theme ?

**Comment by sundansx** [comment]
yes. on windows.  One thing of interest, this was a upgrade/overinstall from a previous version (Version 4.9700)..so I am not sure if that played a role.

**Comment by sundansx** [comment]
this is not true..sorry it was late here.  I am using elemental theme.  I will select default and see if it changes.

**Comment by sundansx** [comment]
verified this works properly on default theme.  I will switch back to elemental and see if all is well and report back.

**Comment by sundansx** [comment]
Ok, Elemental theme has this bug, default theme does not.  I tried this on rPi linux and Windows and they both act the same on elemental theme

**Comment by gizmocuz** [comment]
@sundansx , If possible fix this and submit a PR, or ask the creator of that theme to solve this.
