### ISSUE TITLE
Bug: Website Protection and Local Networks (no username/password) 

### ISSUE THREAD

**Issue by sundansx** [domoticz/domoticz#4664]
On windows and rPi domoticz version Version: 2020.2 (build 12972), using Chrome and Firefox, domoticz autofills some unknown password into the "Website Protection" password field.  This automatically sets a password for the web interface.  Worse, The "Local Networks" feature does not seem to work anymore.  When I have my local network wildcard in there (192.168.1.*) it still asks for a password.  The real downside is that if I save any settings without going in and clearing out the stuffed password, I get locked out of the web interface until I restart domoticz with -nowwwpwd option.  I did not have this problem with 4.97

**Comment by rwaaren** [comment]
I cannot reproduce this on my systems (Raspberry, NUC and Windows) with build 12972 using the default theme or the elemental theme with chrome browser

**Comment by kiddigital** [comment]
It is not Domoticz that prefills the password, it is the Browser that suggests a password, but you can discard the suggestion leaving the password empty.

(Should we add an enabled switch?)

**Comment by gizmocuz** [comment]
@kiddigital , no empty is the same

**Comment by sundansx** [comment]
in my case it is not the browser, as I have used several browsers and they all do the same.  even edge.  That said if others are not seeing the problem, then it must be something with my setup.  **Did anyone test that the "local networks" feature is working?  or maybe I need to split that into a seperate bug.**

**Comment by rwaaren** [comment]
**Did anyone test that the "local networks" feature is working? or maybe I need to split that into a seperate bug.**

Also working on all my systems

**Comment by gizmocuz** [comment]
Yes using it every day (On different installations)
@sundanx, I suppose you connect directly to it, and not via a VPN/Proxy ?
