### ISSUE TITLE
Replace device keeps the new device

### ISSUE THREAD

**Issue by jmichault** [domoticz/domoticz#4670]
Replacing device keeps the new device, whereas it should keep the old one.
As a result, the device loses its name, and especially the ID is not kept.

**Comment by waltervl** [comment]
I am not sure as the naming in the UI is strange but according manual you should click on edit on the new device, click on replace and select the old device (but replace dialog is saying new device, see screenshot !!). After clicking on OK, the old device is deleted and the logging is taken over by the new device.
![Selection_031](https://user-images.githubusercontent.com/16327072/108894663-da5dc780-7612-11eb-947d-601bf48c53dc.png) So to keep this behavior the text in the Replace dialog needs to be changed from new to old.

But if this PR works as expected and when clicking edit on the old device, replace with new device and the old device is deleted and the logging is taken over by the new device it is more logical.

**Comment by kiddigital** [comment]
Hm... so code and UI are not consistent here...
2 scenario's
1) From the 'old' device -> Replace this old device by the selected new device
2) From the 'new' device -> Let this device replace the selected old device
Depending where the User starts (old or new device) the UI should be different, but the code should/could be the same -> replaceIDX(old, new)

```
		//Will transfer Newest sensor log to OLD sensor,
		//then set the HardwareID/DeviceID/Unit/Name/Type/Subtype/Unit for the OLD sensor to the NEW sensor ID/Type/Subtype/Unit
		//then delete the NEW sensor
		void CWebServer::RType_TransferDevice(WebEmSession & session, const request& req, Json::Value &root)
		{
			std::string sidx = request::findValue(&req, "idx");
			if (sidx.empty())
				return;

			std::string newidx = request::findValue(&req, "newidx");
			if (newidx.empty())
				return;

```
The code comments are clear on the goal. And it receives an old 'idx' an a 'newidx', but then
```
			//Check which device is newer

			time_t now = mytime(nullptr);
			struct tm tm1;
			localtime_r(&now, &tm1);
			struct tm LastUpdateTime_A;
			struct tm LastUpdateTime_B;

			result = m_sql.safe_query(
				"SELECT A.LastUpdate, B.LastUpdate FROM DeviceStatus as A, DeviceStatus as B WHERE (A.ID == '%q') AND (B.ID == '%q')",
				sidx.c_str(), newidx.c_str());
			if (result.empty())
				return;

			std::string sLastUpdate_A = result[0][0];
			std::string sLastUpdate_B = result[0][1];

			time_t timeA, timeB;
			ParseSQLdatetime(timeA, LastUpdateTime_A, sLastUpdate_A, tm1.tm_isdst);
			ParseSQLdatetime(timeB, LastUpdateTime_B, sLastUpdate_B, tm1.tm_isdst);

			if (timeA > timeB)
			{
				//Swap idx with newidx
				sidx.swap(newidx);
			}
```
Here it is _decided_ that even if the User wants to replace A with B (so B should remain and A should be deleted), the code might do the opposite when A has more recent data than B. Resulting in B being replaced with A (and A remaining and B deleted).

The code tries to **merge** the 2 device together, keeping the data of both devices under the assumption that the device with the latest updates is the one that will be getting the new updates (and the other one does not get updates anymore).

So New here actually means the devices with the _Newest_ updates. And therefor the other one becomes the _old_ one.

Maybe the UI should say 'merge devices' instead?

**Comment by waltervl** [comment]
And the wiki manual is not consistant too (but that is no suprise :-) ).
But normally the reason for a new device is changing batteries for RF and Zigbee devices or replacing an old sensor by a new sensor so the New device in normal use case is the one with the most recent logging data. But I would suggest to leave that choice to the user and not to some logic that perhaps takes the wrong conclusion. 

With " merge"  it is difficult to explain to the user what device will stay and what device will go. The user knows exactly what is the old (and to be deleted) and what is the new device.

**Comment by jmichault** [comment]
The actual code choose to merge the logs to the new device and delete the old (although the code comments say the opposite ).
This makes the codes (like events) created with the old device inconsistent, and the customizations made on the old device (name, favorite, ...) are lost.
Keeping the old device therefore seems more logical to me.

I agree that a better term should be found than "replace".

**Comment by waltervl** [comment]
Did you try this with Zwave, zigbee, RF etc devices? As the hardware devices are managed by the hardware plugin (python or build in). That decides that there is a new device created. If you replace that new idx by the old idx the new device will not work I presume. If the code takes over also the link to the hardware plugin it could work.
It could also be that device old is Zwave and device new is zigbee. Can that be managed also with the swap?

**Comment by jmichault** [comment]
You are right.
The code actually don't take care of copying any data from the deleted device to the retained device.
So i agree that keeping the old device is actually bad.

If we want to keep the old device, we must copy technical data from new to old (hardwareid, deviceid, unit, ...), but keep customizations (name, AddjValue, Description, ...).
If we want to keep the new device, we should copy customizations from old to new (name, AddjValue, Description, ...), or give the choice to the user...

**Comment by gizmocuz** [comment]
Not all devices could be replaced... If some types are missing just report them and I can see what can be done.

Now this is how it works:

You can replace your device with a new one. The new one should already be in the system.
It's made for RF hardware where as you replace the battery you get a new ID.
Also when a device is broke (... a zigbee/zwave) and you have a new one and want to keep the logs (temperature sensor for example)
Yes, if you used the device in scripts, you need to modify the scripts as well.
Luckily you're not replacing a lot of devices, and if you reference your device by 'name' in scripts and you keep the same name, it all should work out.

**Comment by waltervl** [comment]
I agree, but what is the best way to do this in the current code implementation? 
Click on Edit-Replace on the New device or on the Old device? 
The dialog assumes you clicked Edit-Replace on the old device,
The manual https://www.domoticz.com/wiki/Managing_Devices#Replace_device says the same (I was incorrect on this, sorry for the confusion)
The only change to be made in the manual seems to be that the old device is automatically deleted.

**Comment by gizmocuz** [comment]
Well that is what 'replace' means ?

**Comment by jmichault** [comment]
Hello,
I propose another pull request.

In this pull request, i have added a checkbox in the "Replace dialog", labelled "Keep old Idx, name, description" 

If this checkbox is unchecked (default), everything is going as usual :  logs of the old device are merged to the new device then old device is removed.

If this checkbox is checked :  logs of the new device are merged to the old device, then all fields except idx,name,description,used,favorites are copied to old device and finally the new device is removed.
This avoids having to re-enter the name, the description, and having to correct the scripts. 

My first tests with RF thermometers worked as desired.
I don't know if this can be used with zigbee or z-wave devices.

**Comment by waltervl** [comment]
Replace in stable 2022.1 now will always move to the old device in order to have less maintenance on scripts.
https://github.com/domoticz/domoticz/commit/b36f2bc650da0c0c1d9ba808d980b1a4015a2512
