### ISSUE TITLE
'Timers' button should only be highlighted if at least one timer is active

### ISSUE THREAD

**Issue by rrozema** [domoticz/domoticz#4685]
If a device has no timers the timers button is shown in blue (in the default color scheme), if it has at least one timer, the button is shown in purple.
![image](https://user-images.githubusercontent.com/1747982/109205932-8df7c080-77a7-11eb-9f73-e24da94d1535.png)
If all timers on the device are disabled, the device behaves exactly like when it has no timers on it. Why does it still show the purple 'Timers' button in this situation even though it is never going to be automatically activated?
![image](https://user-images.githubusercontent.com/1747982/109206425-1fffc900-77a8-11eb-951b-b9ee0da2d3bb.png)

It would make more sense to only show the button as purple if the device can be activated automatically by a timer. i.e. it has at least one active timer. This would need one extra condition " AND Active == true" in CSQLHelper::HasTimers (on both queries).

**Comment by gizmocuz** [comment]
Nope, it should highlight when times are defined (regardless if they are active/inactive)
