### ISSUE TITLE
Please add FGRGBW442 RGBW Controller 2+ to Zwave config.

### ISSUE THREAD

**Issue by uffer** [domoticz/domoticz#4690]
See https://www.domoticz.com/forum/viewtopic.php?f=24&t=31831&p=269758#p269758 and https://www.domoticz.com/forum/viewtopic.php?t=29826#p227691

It seems that the FGRGBW442  can be added to Domoticz but it seems not to work correctly.

Could you please add the controller to the Zwave config in the new version?

![Fibaro](https://user-images.githubusercontent.com/18116064/109385683-ff458980-78f5-11eb-9a3b-3a48422b999a.png)

**Comment by rrozema** [comment]
Domoticz uses the [OpenZwave library](https://github.com/OpenZWave/open-zwave) to support zwave devices. You'll need to add your device to that library and when the device is included there, it will become available in Domoticz too. Instructions how to add a device to OpenZwave can be found in their [wiki: Adding Devices](https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices)

**Comment by rbrouwer** [comment]
The device is added to OpenZwave in this [config file](https://github.com/OpenZWave/open-zwave/blob/master/config/fibaro/fgrgbw442.xml) with [this PR](https://github.com/OpenZWave/open-zwave/pull/2381). The FGRGBW442 RGBW Controller 2 compared to the first is a difficult device to control. The device will not work as RGBWZ device, but as 5/6 dimmer switches. You need to turn on the overall switch (dimmer 2) and then turn on any of the other colors (dimmer 3,4,5,6) to produce any light.

That's not really obvious, but it's how this device seems to work. Some DzVents script can be made to map a virtual RGBWZ device to those 5 dimmers and back.

**Comment by uffer** [comment]
Ok thanks!
