### ISSUE TITLE
An integer overflow when parsing Samsung TV IR codes.

### ISSUE THREAD

**Issue by derrij** [domoticz/domoticz#4691]
https://github.com/domoticz/domoticz/blob/aad65002eea99b8336cefd773e7422f0a7f1873f/hardware/MySensorsBase.cpp#L2081

**Comment by derrij** [comment]
Changed it to `pChild->SetValue(vType, (int)strtoul(payload.c_str(), NULL, 10));` , works fine for me

**Comment by gizmocuz** [comment]
@derrij , do you know what the content/value of the 'payload' string is ?

**Comment by derrij** [comment]
payload was '3772833823'

**Comment by gizmocuz** [comment]
Thanks!

It seems you seem to convert it to a 64bit value, and after that truncating it to a 32bit value **(int)**
Could you also test with

pChild->SetValue(vType, (int)std::stoul(payload.c_str()));

If that works, could you make a PR against the active branch (development)

**Comment by derrij** [comment]
Yes, with `pChild->SetValue(vType, (int)std::stoul(payload.c_str()));` works fine.

`2021-02-28 11:32:32.710 MySensors: NodeID: 3, ChildID: 7, MessageType: 1, Ack: 0, SubType: 33, Payload: 3772833823`
`2021-02-28 11:32:32.738 (usb) Light/Switch (IR Command Volume UP TV)`

**Comment by gizmocuz** [comment]
Thank you for the PR, but you have to make the changes in the active branch , which is the development branch

**Comment by rwaaren** [comment]
@derrij Can you please close the issue when tested and OK ?
