### ISSUE TITLE
MQTT Error converting sValue/sUsage!

### ISSUE THREAD

**Issue by devrosx** [domoticz/domoticz#4701]
Hello, for some this error has sometimes appeared in the log...

im using nodered to convert energy values to domoticz mqqt (updated every 30 seconds):
when is payload for example: "idx":940,"command":"udevice","svalue":"164;0"
**i have this error in log...**

```
2021-03-01 15:34:56.694 MQTT: Topic: domoticz/in, Message: {"idx":940,"command":"udevice","svalue":"164;0"}
2021-03-01 15:35:00.827 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 940, sValue: 'nan', sUsage: '1640', dType: 243, sType: 29)
```

**strange is that the same value works a moment before fine without errors...**
`2021-03-01 15:34:16.694 MQTT: Topic: domoticz/in, Message: {"idx":940,"command":"udevice","svalue":"164;0"}
`
Any idea what could be wrong ?
thank Jan

Update: looks like maybe problem could be if values in payload are the same 2 times in a row...

**Comment by gizmocuz** [comment]
@devrosx , best to search inside the source code where this message is printed
But without this... you already see the problem between ( and ) .... what's the value of sValue ? 'nan', that is not allowed!

**Comment by gizmocuz** [comment]
You also need to mention the domoticz version you are using
