### ISSUE TITLE
Official Docker image: No scripts?

### ISSUE THREAD

**Issue by YOYONL89** [domoticz/domoticz#4708]
Hello,

Today i switched from the Linuxserverio docker image to the official docker image.
Seems to work fine in general but i cant import my scripts folder from the old docker image.

Scripts should be located in `/opt/domoticz/scripts` but that map is empty on the image.
i made an persistent link in the docker config and added my folder with scripts to it.
In the docker image with  `docker exec -it DomoticzMaster ls -l /opt/domoticz/scripts/` i can see my scripts so thats working ok.
Nevertheless domoticz cant see my scripts there in the events window and if i create a new event (Blocky/Lua/Dzvents) i cant see that file being generated anywhere?

Someone who can tell me where to find them?

Cheers,

**Comment by waltervl** [comment]
This is something that should be addressed on the Domoticz forum not on this github.
But scripts will appear in the /opt/domoticz/userdata in folder scripts folder that you have to mount to a local folder on your computer. See also the instructions on https://hub.docker.com/r/domoticz/domoticz

**Comment by YOYONL89** [comment]
Hi Walter,

Sorry for misinterpreting the location as where this should be.
I understand you're part about the mounting and I did just that. 
But the only folder that appears is the Plugin folder, that's why I asked it.

Shall I move this problem to the forum or is it suitable for github?

**Comment by waltervl** [comment]
Yes please, there is a general topic here: https://www.domoticz.com/forum/viewtopic.php?f=4&t=35454
