### ISSUE TITLE
BETA - Blinds T11 ASP not working

### ISSUE THREAD

**Issue by jyboo** [domoticz/domoticz#471]
Hardware: Raspberry Pi 1 model B
OS: Domoticz image
Domoticz branch: Beta
Version number / build hash: 2.4547
Bug/problem or a question: problem
Occurs: since ever
Reproduce: 
on beta version v.2.4547, I am testing the "Blinds T11 ASP"
on RFXMgnr, the id is only 6 characters, for instance 3A A6 24, it is actually detected on "undec on" + "Blinds T1/T2/T3/T4" mode, and the Blinds T11 ASP transmission is actually working from the RFXMngr.
On domoticz, the ID is 7 characters, for instance XX XX XX X.
I have tried to put back the id, 3A A6 24 and then test all the different possibilities for the last characters, but nothing is working.
I guess that basically, it is the ID format that does not fit.

**Comment by gizmocuz** [comment]
Do not cross post, you asked this on the forum as well
Keep using the forum please!
