### ISSUE TITLE
Request: Expose "LogLevel" and "Configuration" to plugin

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#4712]
"LogLevel" and "Configuration" have been recently added to the Hardware table for plugin usage.
However the Python Framework plugin doesn't get access to it, please do add those parameters to the Python Plugin Framework

A PR #4639 was proposed , but rejected as it should be part of a more global refactoring of the framework

**Comment by gizmocuz** [comment]
To be more clear, It was not rejected, but the request was to make it both read and writeable
