### ISSUE TITLE
GLIBC_2.29 not found

### ISSUE THREAD

**Issue by Seidel76** [domoticz/domoticz#4714]
I did a ./updatebate today. but now domoticz don't start anymore, somebody an idea to fix it
domotics.sh status gifs FLIBC2.29 error.
Running Debian Buster

root@debian:/home/pi/domoticz# sudo /etc/init.d/domoticz.sh status
● domoticz.service - LSB: Home Automation System
Loaded: loaded (/etc/init.d/domoticz.sh; generated)
Active: active (exited) since Sun 2021-03-07 19:55:38 CET; 5min ago
Docs: man:systemd-sysv-generator(8)
Process: 13964 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)

Mar 07 19:55:38 debian systemd[1]: Starting LSB: Home Automation System...
Mar 07 19:55:38 debian domoticz.sh[13964]: /home/pi/domoticz/domoticz: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/pi/domoticz/domoticz)
Mar 07 19:55:38 debian systemd[1]: Started LSB: Home Automation System.

*********
root@debian:/home/pi/domoticz# ldd --version
ldd (Debian GLIBC 2.28-10) 2.28

**Comment by waltervl** [comment]
More people having this issue: https://domoticz.com/forum/viewtopic.php?f=6&t=35725&p=270309

**Comment by gizmocuz** [comment]
This is about 64 bit Linux ? This is build by the Travis-CI build environment
How long ago did you update before ?
As alternative you can use the docker image, it's a small migration step but could be interesting in the features

**Comment by SargonofAssyria** [comment]
I have Raspbian Linux domoticz 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
I also have version 2.28 I checked with "sudo apt-get update", but there is no update to 2.29 available.
So I suppose I cannot update Domoticz either.

**Comment by gizmocuz** [comment]
This is the OS of the build system for Arm (32 and 64 bit)

```
pi@rpibuild4:~ $ cat /etc/issue
Raspbian GNU/Linux 10 \n \l
```

Nothing special, just buster.

I just updated a 32bit arm system from version 12824 to 13057 without issues, I don't understand why there should be suddenly a issue ?

what does 'cat /etc/issue' say ?

**Comment by SargonofAssyria** [comment]
My 'cat /etc/issue' states the same 'Raspbian GNU/Linux 10 \n \l'
I did not do an update yet. I only mentioned that I have version 2.28 and there is not an update for version 2.29 where this issue is about.

**Comment by Seidel76** [comment]
For me:
`Debian GNU/Linux 10 \n \l `

and not in a RPi

**Comment by SargonofAssyria** [comment]
I just updated to version 13058 with raspbian 5.10.17-v7l+ on RPi 4B and had no issue with glibc (version 2.28)

**Comment by waltervl** [comment]
According forum thread: Seems to be an issue on the Linux build, not on the Arm 32/64 builds.

**Comment by frenchyyii** [comment]
Hi same problem here.
Debian buster on syno DS918+ VM

Debian GNU/Linux 10 \n \l


No way to solve it by my own

Does anyone has an older beta relase to install ? (maybe 13057)

Regards

**Comment by gizmocuz** [comment]
@frenchyyii , this is of course not a solution and needs to be addressed in the **.travis.yml** build script file

@waltervl , thank you for confirming this ! I got VERY confused by the replies from @SargonofAssyria , please do not do this anymore. You are making this whole thread confused.

So it's a Linux problem, the build is done by AppVeyor, and the build script file is **.travis.yml**
Now we have to ask the question, how can travis have a newer version then your system
Maybe it is 20.04 and 20.10 related ?
Our build script is using the 'focal' environment, according to this page it is 20.04

https://docs.travis-ci.com/user/reference/overview/

Seems to be a duplicate issue

https://www.domoticz.com/forum/viewtopic.php?t=31770

Open for any suggestions

**Comment by gizmocuz** [comment]
My mistake, it is NOT build by Travis but by Github actions...

**Comment by gizmocuz** [comment]
Maybe it is because it is using 20.04.02 ?

https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

**Comment by SargonofAssyria** [comment]
The issue is generic about "GLIBC_2.29 not found" I only commented about where there was NO problem. Generally this helps to narrow down the problem. Statement as "So it's a Linux problem" are NOT accurate. I don't think I make the thread confused, but the reader does.

**Comment by gizmocuz** [comment]
The issue was narrowed down with (my) 3rd reply.

**Comment by frenchyyii** [comment]
New beta available, no change on my side .

**Comment by waltervl** [comment]
Are you/we building in a specific ubuntu version or using 'ubuntu-latest' ? https://github.com/actions/virtual-environments

Ubuntu latest changed from 18 to 20 : https://github.com/actions/virtual-environments/issues/1816

**Comment by gizmocuz** [comment]
Is it possible to test the new beta version / docker ? It is not build currently with Github Actions but on the main build server

**Comment by gizmocuz** [comment]
@waltervl , please see the file in our repository github\workflows\development.yml
(ubuntu-latest)
We use it for quite some time, but not suddenly it requires 2.29 ...

**Comment by ClavosPL** [comment]
yeah.... i post i try last beta 13059 not working witch ubuntu 18.04 LTS this is sad .... lts is lts :)
but when update linux to Ubuntu 20.04.2.0 LTS (Focal Fossa), works fine
but question iss WHY you need https://github.com/domoticz/domoticz/issues/4719 GLIB 2.29 and 2.28 for domoticz

**when you put this in relese version ..... i think 
you will be lynched by LTS users ....** 
better chceck when is end of 18.04 LTS linux version

  | Released | End of Life
-- | -- | --
Ubuntu 16.04 LTS | Apr 2016 | Apr 2021
**Ubuntu 18.04 LTS | Apr 2018 | Apr 2023**
Ubuntu 20.04 LTS | Apr 2020 | Apr 2025
Ubuntu 20.10 | Oct 2020 | Jul 2021

**Comment by gizmocuz** [comment]
@ClavosPL , see a few posts up. Don't think we can specify Github Actions to use 20.04 and not 20.04.2
And for sure no... we don't support 18.04 ... we support the latest LTS version, just update your system or use the docker

**Comment by ClavosPL** [comment]
1. It's really cool that you do all the software.

2. LTS users tend to be long-term. Hence, it was important to consider whether the change that caused the error should be introduced into the release ver. - you will do what you want.

3. If it wasn't for the fact that the LTS update went smoothly, I would probably have restarted openHab

4. This is just a tip, I know you are getting the beta here, and the user has to be aware of possible problems.

5. And so thanks for working on domoticz. :) It's really cool
