### ISSUE TITLE
Ubuntu LTS 18.04 Crash after updatebeta .... GLIBC_2.29, and GLIBC_2.28 not found

### ISSUE THREAD

**Issue by ClavosPL** [domoticz/domoticz#4719]
Yesterday update, crash GLIBC_2.29 and 2.28 not found 
system domoticz is dead
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-136-generic x86_64)

**Comment by ClavosPL** [comment]
i see new beta update, still the same problem domoticz vont start 
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-136-generic x86_64)

./updatebeta 

● domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh; generated)
   Active: active (**exited**) since Tue 2021-03-09 13:59:01 CET; 16s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 29114 ExecStop=/etc/init.d/domoticz.sh stop (code=exited, status=0/SUCCESS)
  Process: 29122 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)

mar 09 13:59:01 HPCompaq systemd[1]: Starting LSB: Home Automation System...
mar 09 13:59:01 HPCompaq domoticz.sh[29122]: /xxxx: /lib/x86_64-linux-gnu/libm.so.6: version `**GLIBC_2.29**' not found (required by /home/l
mar 09 13:59:01 HPCompaq domoticz.sh[29122]: /xxxx: /lib/x86_64-linux-gnu/libc.so.6: version `**GLIBC_2.28'** not found (required by /home/l
mar 09 13:59:01 HPCompaq systemd[1]: Started LSB: Home Automation Syst



**is it possible to go back to another beta build ?**
something like ./updatebeta1299  ???

**Comment by ClavosPL** [comment]
Realease version work's fine, but this wersion don't work with beta database :) ....

**Comment by waltervl** [comment]
Is already identified as an issue: https://github.com/domoticz/domoticz/issues/4714

**Comment by waltervl** [comment]
From what Domoticz version did you update? Stable 2020.2 or were you already running a beta? Do you know when you did the last update of domoticz that was running correctly?

**Comment by ClavosPL** [comment]
Still working on beta and update from beta,
sorry dont know and remember build.. but i think last update was made 1299 something like that and domoticz works

**is it possible to go back to another beta build ?
something like ./updatebeta1299 ???** or change something inside ./updatebeta for that ? and i check that?

**Comment by waltervl** [comment]
@ClavosPL it is not possible to go back to an earlier beta release unless you have made a backup before update or you build the old beta yourself.

**Comment by gizmocuz** [comment]
Why do you continue here as there is already an another issue? As mentioned there is s new beta... You could try this one
