### ISSUE TITLE
Z-wave not working in Domoticz V2020.2 (build 13063)

### ISSUE THREAD

**Issue by darkrain-nl** [domoticz/domoticz#4723]
Hi @gizmocuz,

Z-wave is not longer working with Domoticz V2020.2 (build 13063) 

Is this also related to some C++ optimizations that are going on? (Like RFXCom earlier...)

What can I do to help and fix this?

There is a forum topic about this: https://www.domoticz.com/forum/viewtopic.php?p=270150#p270150

**Comment by darkrain-nl** [comment]
OK, after waiting 20 minutes it started to work again, but I still think something is wrong...
It issued a message like "OpenZWave: A Config File Failed to download" time after time..

**Comment by ridderr** [comment]
Same problem with me. I'm afraid to restart because it will then take another 20 min before Zwave is up and running.

**Comment by jakenl** [comment]
Same here.

lsusb shows the Gen2 Stick (Bus 001 Device 008: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP2102/CP2109 UART Bridge Controller [CP210x family]) but it seems improper loaded in Domoticz.

When I now disable the OpenZwave, Domoticz locks up and is reset by Monit after some time. Afterwards OpenZwave is disabled, but when I enable it again, I only get the following in the log (while filtered on zwave):
2021-03-10 23:34:43.329 Status: OpenZWave: Starting...
2021-03-10 23:34:43.329 Status: OpenZWave: Version: 1.6-1520-g893e076a
2021-03-10 23:35:07.645 Status: OpenZWave: A Config File Failed to download
2021-03-10 23:35:48.384 Status: OpenZWave: A Config File Failed to download
2021-03-10 23:36:23.663 Status: OpenZWave: A Config File Failed to download
2021-03-10 23:36:58.807 Status: OpenZWave: A Config File Failed to download

I have not yet waited the '20 minutes'. It would be weird if also in this case 'time heals all wounds', but it would for sure be nice

EDIT: indeed after 12-15 minutes OpenZwave kicked back to life and all, except one device is reporting again.

**Comment by rwaaren** [comment]
Also reported by some on forum 

[link to recent posts](https://www.domoticz.com/forum/viewtopic.php?p=270591#p270591)

**Comment by gizmocuz** [comment]
Could be the download server of OpenZWave is down ...
Is this for both Arm as AMD64 ?

There have been no optimizations and there have been no recent development for zwave, so that can't be it

The problem is that we currently can not disable the checking/downloading in the OZW library, I might write a patch for this really soon 

There where some configuration file updates, I will update them in our repository, that might help with the startup time

**Comment by ridderr** [comment]
I'm running Arm. But, even after a restore to the previous release I had the same problems. So your diag that it's related to a download server could be correct. I looks like that for each device a download is tried with a specific timeout. After that (~20 min) the devices returns in the HW overview and Domoticz is running again.

**Comment by darkrain-nl** [comment]
I run amd64, so yes it happens on both.

**Comment by Olivier6767** [comment]
Same problem here. Does someone know the URL it tries to download? 
This way we can test and potentially redirect to another place.

**Comment by gizmocuz** [comment]
Patience please... solution is underway

**Comment by gizmocuz** [comment]
The problem is related to the website of OpenZWave (openzwave.com).
I make a patch in the library that is now currently used in the Windows/Arm32/Arm64/AMD64 and docker builds.
If you are using the automatic builds, you can update.

If you are building manually, have a look at the updated build instructions on our wiki page

**Comment by ridderr** [comment]
Looks much better now !! Thanks

**Comment by gizmocuz** [comment]
Great! Thanks for the feedback. If someone could mention this on the Forum that would be great!

**Comment by darkrain-nl** [comment]
Hi @gizmocuz 

I'm building it myself, but "If you are building manually, have a look at the updated build instructions on our wiki page" doesn't lead me to the solution for this, can you be a bit more specific what I should do to fix it?

Thanks!

**Comment by rwaaren** [comment]
@darkrain-nl 

The source is different.


it was: `git clone https://github.com/OpenZWave/open-zwave open-zwave-read-only
`
it is now: `git clone  https://github.com/domoticz/open-zwave open-zwave-read-only`

**Comment by darkrain-nl** [comment]
Thanks, did not notice that ;-)
Trying now.

**Comment by darkrain-nl** [comment]
Yep, works fine now, Thanks!

**Comment by Olifant1990** [comment]
@gizmocuz In Windows (beta) build 13079 this is still an issue. You said it was rolling out in the releases?
I have to wait until Z-Wave is ready with trying to download config files, which are not there.

**Comment by gizmocuz** [comment]
Yes, Windows build is even ahead of the rest, so it seems localhost can not be resolved in your system ?
What happens when you run

ping localhost

**Comment by Olifant1990** [comment]
That is possible, I get a response like "Reply from ::1: time<1ms"
