### ISSUE TITLE
Domoticz seems to add the -modified tag even with no local modifications

### ISSUE THREAD

**Issue by brucemiranda** [domoticz/domoticz#4728]
Of late I have noticed that compiling domoticz from source seems to always add the -modified tag even though I am simply pulling the latest git and compiling it with no local modifications. 
I think it might be related to the sub-system libraries, rather than the actual base Domoticz

**Comment by gizmocuz** [comment]
Do you know how we could avoid this ?

**Comment by gizmocuz** [comment]
This seems to be caused by the submodules. Running the command by hand revealed this
Fixed by ignoring the sub modules

**Comment by brucemiranda** [comment]
How do you ignore the submodules?

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/commit/402ce8ddb3de3f49582f16e629bedd5523464866
