### ISSUE TITLE
ungraceful shutdown of Domoticz on OSX Catalina

### ISSUE THREAD

**Issue by lwalbert** [domoticz/domoticz#4730]
Hi,

commit a2ec619d7c44f25cf6057634307caa0693e9b913
Author: Rob Peters <info@domoticz.com>
Date:   Mon Mar 8 09:13:49 2021 +0100

    Small refactoring

seems to cause Domoticz to stop ungracefully on OSX Catalina when shutting down application.

2021-03-15 10:46:32.613  Status: Mainworker Stopped...
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
....

[terminal.txt](https://github.com/domoticz/domoticz/files/6144285/terminal.txt)

br
lwalbert

**Comment by gizmocuz** [comment]
This should already been solved. It was caused in CNotificationSystem::Unregister
Now it's checked if we can find the notifier to be removed, as it seems this function is called twice
Please test with the latest code/beta

**Comment by lwalbert** [comment]
Hi @gizmocuz, I tested with latest code Domoticz V2020.2 (build 13083)
Still same issue.

**Comment by lwalbert** [comment]
Hi @gizmocuz, just tested with Domoticz V2020.2 (build 13084)
Still same issue.

br 
lwalbert

**Comment by gizmocuz** [comment]
Correct, the change was not about fixing this
Since you are building yourself, could you please build a 'DEBUG' build, maybe it provides more information

cd dev-domoticz
git pull
cmake -DCMAKE_BUILD_TYPE=Debug CMakeLists.txt
make

**Comment by lwalbert** [comment]
Hi @gizmocuz,
Thanks for your feedback.
Tested with a new build in Debug.
Where not able to see any difference.
Domoticz.log file dosent catch the mutex lock fails, it only occurs when started/stopped in terminal.
Attached you'll find Domoticz.log and terminal window dump from last run of debug compiled version.

[domoticz.log](https://github.com/domoticz/domoticz/files/6149089/domoticz.log)
[Terminal_Run.txt](https://github.com/domoticz/domoticz/files/6149090/Terminal_Run.txt)


Yesterday I tested with checking out different build versions and found that the mentioned commit: a2ec619 caused it.
the commit before was OK, no errors when stopping Domoticz.

Hope this helps:)

br 
lwalbert

**Comment by gizmocuz** [comment]
I can't see what goes wrong... maybe you could try to debug the issue ?

The notification system stops correctly:

2021-03-16 13:42:43.694  [0x7000016bc000] Status: NotificationSystem: thread stopped...
2021-03-16 13:42:43.694  [0x70000111b000] Status: PluginSystem: Exited work loop.
2021-03-16 13:42:43.696  [0x115aa8dc0] Status: PluginSystem: Stopped.
2021-03-16 13:42:43.697  [0x700001533000] Status: Mainworker Stopped...

So till here it's OK...

After this you get a lot of

ibc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument


if I google this, it's all OS-X 

I don't have any issues on Windows, ARM and Linux... strange

**Comment by lwalbert** [comment]
Hi @gizmocuz,

Thanks again, also noticed that my raspberry pi didn't complain, so looks like its OSX issue. 
maybe you can see the problem in the attached crash-log.
Im not sure where to start looking, but will give it a try :)

[domoticz_2021-03-16-182132_Lennarts-MacBook-Pro-3.txt](https://github.com/domoticz/domoticz/files/6151211/domoticz_2021-03-16-182132_Lennarts-MacBook-Pro-3.txt)

**Comment by lwalbert** [comment]
Hi @gizmocuz,

I managed to fix it by reinstating the for loop at the end of NotificationSystem.cpp from line 129
OSX Domoticz now stops normally without errors and no crash report :)
Disabled the replacement code at the bottom as it didn't work as intended. tried to fix, but no luck.


<img width="783" alt="image" src="https://user-images.githubusercontent.com/64552548/111390989-f9042b00-86b3-11eb-94dd-d0387ab1b7a6.png">

Attached the modified cpp file.


[NotificationSystem.txt](https://github.com/domoticz/domoticz/files/6152713/NotificationSystem.txt)

Br
lwalbert

**Comment by gizmocuz** [comment]
Great find! Not sure where the issue still is, but could you try changing 

	std::unique_lock<std::mutex> lock(m_mutex);

to

	std::lock_guard<std::mutex> l(m_mutex);

If that works, can you replace

	if (pNotifier == nullptr)
		return false;

with

	if (std::find(m_notifiers.begin(), m_notifiers.end(), pNotifier) == m_notifiers.end())
		return false;

And see if that still works

If that works, could you replace the whole function by

	std::lock_guard<std::mutex> l(m_mutex);
	auto itt = std::find(m_notifiers.begin(), m_notifiers.end(), pNotifier);
	if (itt == m_notifiers.end())
		return false;
	m_notifiers.erase(itt);

And see if that also works ?

I would expect it to work... 

I think that the issue is that CEventSystem::StopEventSystem is called twice

in CEventSystem I think it is best to register/unregister in the constructor/destructor

**Comment by lwalbert** [comment]
Hi @gizmocuz 

Tested with your recommendations and it works:)

This is the working code:
<img width="686" alt="Skjermbilde 2021-03-17 kl  17 05 39" src="https://user-images.githubusercontent.com/64552548/111500369-387a5800-8744-11eb-926b-7715e42ef1dc.png">

Added a return true; at the end as I got a compiler warning.
/Users/lwalbert/dev-domo/main/NotificationSystem.cpp:167:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]

Great work :)

Br
lwalbert

**Comment by gizmocuz** [comment]
Thanks for the feedback !!

**Comment by gizmocuz** [comment]
One more test if possible:

```
bool CNotificationSystem::Unregister(CNotificationObserver *pNotifier)
{
	std::lock_guard<std::mutex> l(m_mutex);
	auto itt = std::find(m_notifiers.begin(), m_notifiers.end(), pNotifier);
	if (itt == m_notifiers.end())
		return false;
	m_notifiers.erase(itt);
	return true;
}

```

**Comment by lwalbert** [comment]
Hi @gizmocuz,

Just re-tested with your latest reply, did not work.
Tested it yesterday too:)

for some reasons the if statement needs to be there.
```
if (std::find(m_notifiers.begin(), m_notifiers.end(), pNotifier) == m_notifiers.end())
                return false;
```

this is the code piece that works:

```
bool CNotificationSystem::Unregister(CNotificationObserver *pNotifier)
{
        if (std::find(m_notifiers.begin(), m_notifiers.end(), pNotifier) == m_notifiers.end())
                return false;

        std::lock_guard<std::mutex> l(m_mutex);
        auto itt = std::find(m_notifiers.begin(), m_notifiers.end(), pNotifier);
        if (itt == m_notifiers.end())
                return false;
        m_notifiers.erase(itt);
                return true;
}
```

br
lwalbert

**Comment by gizmocuz** [comment]
Thank you for checking, I changed the function. Still odd this is happening... but glad it's solved

**Comment by lwalbert** [comment]
Great, thanks :)
