### ISSUE TITLE
Switchlight Commands via MQTT (domoticz/in) do not cause push to tasmota device on action

### ISSUE THREAD

**Issue by K1WIZ** [domoticz/domoticz#4732]
I have version 4.11786 of Domoticz.   The problem that I believe could be a bug is the following:

Attempting to send a switchlight command from MQTT does cause the dummy switch to respond and change state:
domoticz/in -m '{"command": "switchlight", "idx": 20, "switchcmd": "On" }'

But even though the dashboard state changes, the actual device (a tasmota flashed plug) does not change state even though the switch on the dashboard seems to.  If I toggle it directly on the Domoticz dashboard, the device responds and turns on and off.

Using the json interface also causes the device to turn on and off.  

I found (on the wiki) the MQTT syntax (as noted above) for the purpose of allowing an MQTT message to also toggle the device but it just seems to not work.   No errors in the log either and I see this in the log:

2021-03-15 19:21:29.628 MQTT: Topic: domoticz/in, Message: {"command": "switchlight", "idx": 20, "switchcmd": "On" }
2021-03-15 19:21:29.633 (Dummy) Light/Switch (Office Lamp)
2021-03-15 19:21:31.341 MQTT: Topic: domoticz/in, Message: {"command": "switchlight", "idx": 20, "switchcmd": "Off" }
2021-03-15 19:21:31.347 (Dummy) Light/Switch (Office Lamp)
2021-03-15 19:21:32.551 MQTT: Topic: domoticz/in, Message: {"command": "switchlight", "idx": 20, "switchcmd": "On" }

Monitoring the domoticz/out topic on the MQTT broker shows that Domoticz is not sending the actual push to the tasmota device to turn it on/off.   I only see that when calling the json API or directly clicking the dummy switch that triggers the tasmota device.

{
	"Battery" : 255,
	"RSSI" : 12,
	"description" : "",
	"dtype" : "Light/Switch",
	"hwid" : "3",
	"id" : "00014064",
	"idx" : 20,
	"name" : "Office Lamp",
	"nvalue" : 0,
	"stype" : "Switch",
	"svalue1" : "0",
	"switchType" : "On/Off",
	"unit" : 1
}

{
	"Battery" : 255,
	"RSSI" : 12,
	"description" : "",
	"dtype" : "Light/Switch",
	"hwid" : "3",
	"id" : "00014064",
	"idx" : 20,
	"name" : "Office Lamp",
	"nvalue" : 1,
	"stype" : "Switch",
	"svalue1" : "0",
	"switchType" : "On/Off",
	"unit" : 1
}

(above not seen when I attempt to send a switch command via MQTT to domoticz/in)

Bug?

**Comment by sincze** [comment]
Jups reported that before.

Try switching 'prevent loop' to off.
In Domoticz MQTT settings.

Not advised though. :)

**Comment by gizmocuz** [comment]
Also test with the latest Domoticz beta version
