### ISSUE TITLE
V2020.2 : Domoticz crashing when updating 'Energy read: Computed' General Electric sensor

### ISSUE THREAD

**Issue by mvdklip** [domoticz/domoticz#4733]
When creating a General Electric sensor and setting it to either 'Energy read: Computed' (through the web interface) or to 'EnergyMeterMode: 1' (through plugin options) **before sending the first value**, Domoticz will crash when trying to update the device from a plugin sending the number of Watts as the instant value and 0 (dummy value) as the counter value:

    Devices[1].Update(nValue=0, sValue=str(zappi_gen_watt)+";0")

Leaving the device at the default 'From device' setting for one or more updates and then changing it to 'Computed' through the web interface prevents the crash. So it seems the 'Computed' behaviour tries to add the computed value (instant * time) to an uninitialized value if it's the first value/update received.

Tested on the latest stable version (2020.2). I am unable to test this on the latest beta right now.

This seems similar to closed issue #1758.

**Comment by mvdklip** [comment]
Had a quick look at the code and I think it more likely that it crashes because of an uninitialized last update date/time.

**Comment by gizmocuz** [comment]
Could also be a illegal svalue
But to help test the issue, could you post here a small lua/python plugin that does this ?

**Comment by kofec** [comment]
Last time I notice that i have to add in my python plugin below code:
```
            if isinstance(sValue, float):
                sValue = str(float("{0:.1f}".format(sValue))).replace('.', ',')
            Devices[Unit].Update(nValue=nValue, sValue=str(sValue))
            Domoticz.Log("Update " + str(nValue) + ":'" + str(sValue) + "' (" + Devices[Unit].Name + ")")
```

**Comment by mvdklip** [comment]
"""
	<plugin key="crashit" name="chrashit" author="mvdklip" version="1.0.0">
		<description>
			<h2>Crash it!</h2><br/>
		</description>
		<params>
			<param field="Mode3" label="Query interval" width="75px" required="true">
				<options>
					<option label="5 sec" value="1"/>
					<option label="15 sec" value="3"/>
					<option label="30 sec" value="6"/>
					<option label="1 min" value="12" default="true"/>
				</options>
			</param>
		</params>
	</plugin>
	"""

	import Domoticz


	class BasePlugin:
		enabled = False
		lastPolled = 1

		def __init__(self):
			return

		def onStart(self):
			Domoticz.Debug("onStart called")
			Domoticz.Debugging(1)

			if len(Devices) < 1:
				# pass 'EnergyMeterMode' option to enable 'Energy read: Computed' setting
				Domoticz.Device(Name="Electric", Unit=1, Type=243, Subtype=29, Switchtype=0, Options={'EnergyMeterMode':'1'}).Create()

				# or don't pass the option and change the 'Energy read' setting manually before the first update (be quick!)
				#Domoticz.Device(Name="Electric", Unit=1, Type=243, Subtype=29, Switchtype=0).Create()

			DumpConfigToLog()

			Domoticz.Heartbeat(5)

		def onStop(self):
			Domoticz.Debug("onStop called")

		def onHeartbeat(self):
			Domoticz.Debug("onHeartbeat called %d" % self.lastPolled)

			if self.lastPolled == 0:
				Devices[1].Update(nValue=0, sValue="123;0")

			self.lastPolled += 1
			self.lastPolled %= int(Parameters["Mode3"])


	global _plugin
	_plugin = BasePlugin()


	def onStart():
		global _plugin
		_plugin.onStart()


	def onStop():
		global _plugin
		_plugin.onStop()


	def onHeartbeat():
		global _plugin
		_plugin.onHeartbeat()


	# Generic helper functions
	def DumpConfigToLog():
		for x in Parameters:
			if Parameters[x] != "":
				Domoticz.Debug("'" + x + "':'" + str(Parameters[x]) + "'")
		Domoticz.Debug("Device count: " + str(len(Devices)))
		for x in Devices:
			Domoticz.Debug("Device:           " + str(x) + " - " + str(Devices[x]))
			Domoticz.Debug("Device ID:       '" + str(Devices[x].ID) + "'")
			Domoticz.Debug("Device Name:     '" + Devices[x].Name + "'")
			Domoticz.Debug("Device nValue:    " + str(Devices[x].nValue))
			Domoticz.Debug("Device sValue:   '" + Devices[x].sValue + "'")
			Domoticz.Debug("Device LastLevel: " + str(Devices[x].LastLevel))
		return

**Comment by mvdklip** [comment]
Notice the comments in the section where it creates the device. In its current state it creates the device with the option 'EnergyMeterMode' set to '1' so that the device will have the 'Energy read: Computed' setting immediately. My domoticz crashes when the plugin does its first update (after 55 seconds or so).

Alternatively comment the device creation with the Options and uncomment the one without. Domoticz will now **not** crash on first update **unless** you change the 'Energy read' setting to 'Computed' **before** that first update.

**Comment by mvdklip** [comment]
I also noticed that if you want to change the 'Energy read' setting manually that the /Utility web page sometimes already displays the value as 'Computed' although it should be 'From device' (default). Then when you refresh the page and check the setting again it is correctly displayed as 'From device'. Might be related or unrelated to the crash.

**Comment by kofec** [comment]
Is It ok ? sValue="123;0"
Maybe you wants sValue="123,0"

**Comment by gizmocuz** [comment]
@kofec, nope... the sValue has the following meaning for a kWh sensor:

https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s

svalue=POWER;ENERGY

POWER = current power
ENERGY = cumulative energy in Watt-hours (Wh) This is an incrementing counter. (if you choose as type "Energy read : Computed", this is just a "dummy" counter, not updatable because Domoticz will calculate this internallt based on the (previous/current) POWER value)

@mvdklip , thank you for the complete example. Hope to test this very soon!

**Comment by gizmocuz** [comment]
The reason for the crash is that sValue is empty after this log line

2021-03-18 08:20:48.112  (CrashIt - Electric) Updating device from 0:'' to have values 0:'123;0'

But the value 123;0 is correctly parsed from the plugin, and received by:

>	Plugins::CDevice_update(Plugins::CDevice * self, _object * args, _object * kwds) 

In **CSQLHelper::UpdateValueInt** the previous value is checked, which is empty (when the devices was created via python), and that is why it is crashing
(Also in a function where I wrote a comment to the implementer of that piece of code)

Can you also specify the default nValue/sValue when creating the device ? specifying 0;0 for sValue would have solved the problem

**Comment by lwalbert** [comment]
Hi @gizmocuz,

this modification seems to break the actual power reading from the power switch.
Tried to re-pair the device.

faceplate when selected energy read "from device":
<img width="392" alt="Skjermbilde 2021-03-18 kl  11 52 59" src="https://user-images.githubusercontent.com/64552548/111615596-387c6580-87e1-11eb-8211-c619b7dfe341.png">
device when energy read "from device" selected:
<img width="1172" alt="Skjermbilde 2021-03-18 kl  11 52 42" src="https://user-images.githubusercontent.com/64552548/111616365-18997180-87e2-11eb-86a0-deb422e08e3b.png">


faceplate when selected energy read "computed":
<img width="391" alt="Skjermbilde 2021-03-18 kl  11 53 27" src="https://user-images.githubusercontent.com/64552548/111615856-7f6a5b00-87e1-11eb-8f6f-0c750917d471.png">
device when energy read "computed" selected:
<img width="1175" alt="Skjermbilde 2021-03-18 kl  12 05 58" src="https://user-images.githubusercontent.com/64552548/111616661-762dbe00-87e2-11eb-83a9-60db5d574498.png">

actual real power consumption when capturing pictures was 1268 watt
 
before the update, I could read the actual power in top right corner on faceplate when energy read was selected to "computed"


Br
lwalbert

**Comment by gizmocuz** [comment]
Strange, 

Have a look at my changes here:

https://github.com/domoticz/domoticz/commit/eedd56a0fda5e068f5f8212a7c4eb07ccae52ebe

They all seems valid and it is just checking if the array consists of 2 values separated by a semicolon

**Comment by gizmocuz** [comment]
Maybe it is the sValue when something is not right.. one moment

**Comment by lwalbert** [comment]
Hi,
yes, it looks like it takes one of the sVales in the lowest else part of if statement.
tested by setting different vales there.

**Comment by gizmocuz** [comment]
I changed the code and updates should be available

**Comment by lwalbert** [comment]
Hi, tested the new code.

now the faceplate won't change.
Looks like this in booth entry read modes:
<img width="393" alt="Skjermbilde 2021-03-18 kl  13 19 48" src="https://user-images.githubusercontent.com/64552548/111625271-f48f5d80-87ec-11eb-9c6b-83497cfa2c74.png">

**Comment by gizmocuz** [comment]
Faceplate ? So now the code checks if the sValue consists of 2 parts, if not, we don't do anything.. Seems correct... what else could be wrong ?
Is it your sValue ? What is the value in the database ?

**Comment by lwalbert** [comment]
Hi,
yeah, I call the interaction object a faceplate, its just a terminology we uses in my company:)
I´ll check what's stored in my database, but first I need to recover from a crash. Did some tests that went totally wrong :-D

br
lwalbert

**Comment by mvdklip** [comment]
> Can you also specify the default nValue/sValue when creating the device ? specifying 0;0 for sValue would have solved the problem

Doesn't seem so:

    2021-03-18 16:10:05.125 Error: (crashit) 'CDevice_init' failed 'TypeError':''sValue' is an invalid keyword argument for this function'.

However I did find a workaround by creating the device using the 'TypeName' argument instead of the 'Type' and 'SubType' arguments:

    Domoticz.Device(Name="Electric", Unit=1, TypeName='kWh', Options={'EnergyMeterMode':'1'}).Create()

The code in hardware/plugins/PythonObjects.cpp initializes sValue to an empty string by default but when you use the 'TypeName' argument it does some extra initialization of the sValue in the 'maptypename' function. In the case of 'kWh' it initializes the sValue to '0; 0.0' which prevents the crash from happening.

Thanks for the hint towards the workaround! The crash should still not happen ofcourse, so I hope you can fix that too, but it seems you and lwalbert are on it. :-)

**Comment by gizmocuz** [comment]
Great Find!  I can't see anything with the extra checks I added here

https://github.com/domoticz/domoticz/commit/eedd56a0fda5e068f5f8212a7c4eb07ccae52ebe

(the 'else sValue="0;0" is removed)

It seems valid to check if the splitstring results resulted in 2 variables (that was the crash)

**Comment by mvdklip** [comment]
Looks valid to me too, but if Iwalbert reports it doesn't work for him, something might still be broken. Maybe his code was depending on an incomplete sValue being processed? We will only know after he has answered what sValue he is providing to the update call.

**Comment by lwalbert** [comment]
Hi Again,
It looks like the python plugin: "Domoticz-zigbee2mqtt-plugin" for the power switch has been relying on an incomplete sValue, or incorrect type defined.
Ill see I I manage to dig into this, and report it to stas-demydiuk "Domoticz-zigbee2mqtt-plugin" 
my database record contained only one value 79...

kWh readings from zwave devices seems to still work correctly.

only thing I noticed on z-wave kwh meters was that when energy read set to Computed, the "faceplate" toggles between showing nothing:
<img width="400" alt="Skjermbilde 2021-03-18 kl  17 54 19" src="https://user-images.githubusercontent.com/64552548/111665578-29161000-8813-11eb-8a56-71f1946655de.png">
then showing data:
<img width="393" alt="Skjermbilde 2021-03-18 kl  17 54 12" src="https://user-images.githubusercontent.com/64552548/111665468-113e8c00-8813-11eb-81b1-4391c3cab3fd.png">

But I think I might let the system settle down abit, Its been trough a rough day with compiling and start/stops and a recovery :-D

br
lwalbert

**Comment by mvdklip** [comment]
@lwalbert, if you mean that it shows nothing when first created and then starts displaying data once the first update comes in then that might mean that the meter is created without a default sValue so there is nothing to show at first. If however you mean that it constantly changes (toggles) then that's another thing ofcourse.

**Comment by gizmocuz** [comment]
Great, let us know if all is working correctly

**Comment by lwalbert** [comment]
Hi @gizmocuz and @mvdklip 

" If however you mean that it constantly changes (toggles) then that's another thing ofcourse."
Yes, it toggles every time the actual power reading changes value and only when Energy read = Computed is selected.
So look like it initializes every time  a new value/reading arrives. 

For the other issue, I found the failure within the python plugin: "Domoticz-zigbee2mqtt-plugin" and made a workaround so I got the power readings for my power management logics back again.
Ill report the bug found to the maintainer of "Domoticz-zigbee2mqtt-plugin" 
as @mvdklip mentioned, the plugin published only one value instead of two separated by ;.

I mainly uses energy read: from device on z-wave, but had to use Computed on the Zigbee devices, that's how I noticed the toggling. Also tested by setting "computed" on z-wave devices, then they started to toggle too.
But after the workaround I can now also use read from device on booth Zigbee and zwave.
And that works great :)

Br
lwalbert

**Comment by lwalbert** [comment]
Hi,
Here is a video of the toggling.

https://user-images.githubusercontent.com/64552548/111812260-3ba64d00-88d8-11eb-8beb-9bd693e959f0.mov

**Comment by kovainfo** [comment]
Domoticz 2020.2 (build 13058)
<img width="810" alt="Снимок экрана 2021-03-20 в 14 02 28" src="https://user-images.githubusercontent.com/36986231/111867613-41f30280-8986-11eb-8264-dcc126ce56e1.png">

but last beta:
<img width="810" alt="Снимок экрана 2021-03-20 в 14 24 30" src="https://user-images.githubusercontent.com/36986231/111867621-4cad9780-8986-11eb-8f78-c3b90c8e6557.png">

**Comment by FireWizard52** [comment]
When configured as "Computed" these devices are toggling between the expected value and no value.
This gives also side effects, such as negative values in the logging and strange symbols on the floor plan, if the value is missing.

**Comment by lwalbert** [comment]
Hi @gizmocuz,

Did some tests and changed the second if statement to check for 1 instead of 2 part.size.
in main/SQLHelper.cpp line 4763
If I'm thinking correct. If only only one part received it should add the previous to the sValue.
I might be wrong, but at least the change stopped the toggling in my system.

```
 if (parts.size() == 2)
                        {
                                nEnergy = std::stof(parts[0]) * interval / 3600 + std::stof(parts[1]);
                                StringSplit(sValue, ";", parts);
                                _log.Log(LOG_ERROR, "Domoticz:  first wpart if statement");

                                if (parts.size() == 1)
                                {
                                        sprintf(sCompValue, "%s;%.1f", parts[0].c_str(), nEnergy);
                                        sValue = sCompValue;
                                        _log.Log(LOG_ERROR, "Domoticz:  secound wpart if stateme");
                                }
                        }
```

br
lwalbert

**Comment by mvdklip** [comment]
@lwalbert can you find out which sValues are being fed to the updates which cause the toggling? This might very well be a case where Domoticz is supposed to work in one way (sValue *must* be two values) but it has accepted something else in the past (sValue containing single value). That would mean that currently committed code is correct but causes trouble for devices which expect the old behaviour. To find out we need to figure out which sValues are being supplied to cause the toggling.

FWIW I am only involved in this because I reported the original problem of the crash. I'm pretty sure that problem has been solved but I can't really test because I'm using the stable 2020.2 release. I reported another different issue with kWh meters in #4736 which is not directly related to this issue but still people are reporting the 'toggling' there as well.

**Comment by lwalbert** [comment]
Hi,
Realised that it's a nested if, so putting the check value to 1 means it will never reach that state.
This indicates to me that the sValue is combined another place.

But indeed disabling the nested if stopped the toggling.

Also tested reverting the change I did in zigbee2mqtt-plugin to only return one value.
Then Domoticz ignored it as the modification where supposed to do.

meetering Kwh and logs seems to be OK too.

**Comment by gizmocuz** [comment]
Thanks for checking! I changed the code to it checks if it's >=1, the splitstring is maybe not needed if it's always 1

**Comment by 4ae16e** [comment]
> Thanks for checking! I changed the code to it checks if it's >=1, the splitstring is maybe not needed if it's always 1

Hi, I can't mark it as solved.. I yesterday tried upgrade from Last Stable (db version 145) to Last Beta (db version 148) and I had everywhere in power devices two values in sValue (Watt;Wh) but after update, not all, but lot of power devices has only 0 in sValue.. and I can't Edit this devices. I can't change device as Consuption and Computed .. I click on save but nothing happend.. I have still device in interface without value.
Can you look at it again ? I see it as problem in database upgrade.
thanks
