### ISSUE TITLE
not all plug-ins start with the last update

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#4740]
### Issue Guidelines
Version: 2020.2 (build 13102)
Build Hash: eb16e884f-modified
Compile Date: 2021-03-21 10:55:21
dzVents Version: 3.1.6
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

Raspberry Pi
Uptime: 2 Minuten, 10 Sekunden

With the last update, it totally hangs.
Plugins do not start, or do not react and Domoticz freezes.#

PlugIn manager und zigbee2mqtt von Stas.

**Comment by salopette** [comment]
Log

[Neues Textdokument.txt](https://github.com/domoticz/domoticz/files/6177233/Neues.Textdokument.txt)

**Comment by berbergh** [comment]
Same here.
Both my RPI's with domotica freeze after update.

**Comment by salopette** [comment]
it is also not possible to access the event page.

**Comment by veitk** [comment]
i can do one click and that's it .... nothing works anymore

**Comment by svde** [comment]
Same here.

**Comment by veitk** [comment]
@gizmocuz could you revert the commits from today?

**Comment by mojso** [comment]
Same here. domoticz freeze after update.

Version: 2020.2 (build 13102)
Build Hash: eb16e884f-modified
Compile Date: 2021-03-21 10:55:21
dzVents Version: 3.1.6
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by decommentator** [comment]
same here, complete crash after latest beta update
Starting shows these lines and then nothing

> 2021-03-21 16:01:14.026 Status: PluginSystem: Started, Python version '3.7.3'.
> 2021-03-21 16:01:14.027 Status: Philips Hue: Using default poll interval of 10 secs.
> 2021-03-21 16:01:14.034 Status: WebServer(HTTP) started on address: :: with port ****
> 2021-03-21 16:01:14.098 Status: WebServer(SSL) started on address: :: with port ****
> 2021-03-21 16:01:14.100 Status: Camera: settings (re)loaded
> 2021-03-21 16:01:14.101 Status: TCPServer: shared server started...
> 2021-03-21 16:01:14.101 Status: RxQueue: queue worker started...

**Comment by gizmocuz** [comment]
I'm reverting the mutex PR now (build takes one hour) hope thats it, otherwise it could be the std::function patch from today

**Comment by decommentator** [comment]
looks like Domoticz2020.2 (build 13104) fixes the problem (as it is running after the previous mentioned status updates)

**Comment by svde** [comment]
13104 is also working for me.

**Comment by veitk** [comment]
for me as well thx

**Comment by salopette** [comment]
yes everything seems to work again, thanks for that.
