### ISSUE TITLE
Question: Print out which Transport

### ISSUE THREAD

**Issue by flopp999** [domoticz/domoticz#4744]
https://github.com/domoticz/domoticz/blob/d4081b7d660c9a8e19455bf3d4b047621e7bc45b/hardware/plugins/PythonObjects.cpp#L1465

is it correct to write as below if I want to know exactly which Transport that does not exists?

`_log.Log(LOG_ERROR, "%s, disconnection request from '%s' ignored. '%s' does not exist.", __func__, self->pPlugin->m_Name.c_str()), self->pTransport;`

**Comment by gizmocuz** [comment]
No not quite. pTransport is a pointer and can not be used as a string

I think you need self->Protocol ... 

I would write it like

_log.Log(LOG_ERROR, "%s, disconnect request from '%s' ignored. Transport '%s' does not exist.", __func__, self->pPlugin->m_Name.c_str(), self->Protocol);

But best to test

**Comment by flopp999** [comment]
Can I change in the code that I run in my debian or do I need to build a new code with my changes?

**Comment by gizmocuz** [comment]
would be better to build the source by yourself with the changes and thest
a good you can find here

https://www.domoticz.com/wiki/Build_Domoticz_from_source
