### ISSUE TITLE
Memory leak? Out of memory after 4 hours.

### ISSUE THREAD

**Issue by beeepus** [domoticz/domoticz#4747]
Hi,

I did some upgrade on my system and had some python issue on the stable 2020.2 version so i cloned 13091 and now it runs out of memory after 4 hours. I'm running it on a RPI 4 8G. 

Trying to learn how to catch the leak with pmap and libleak but the mapping is blank, empty, anon or unknown and the address is changing raptly for every sample with pmap. I sample every second and upload it to google datastudio to get a graph https://datastudio.google.com/reporting/ac45366a-1cae-4017-9406-83025df8e9b9 where you can see the linier growth. 

I have included the libleak file [libleak.26575.zip](https://github.com/domoticz/domoticz/files/6190790/libleak.26575.zip)

 and also one that summarized the may-leak and the related callstack 
[libleak.26575.sum.txt](https://github.com/domoticz/domoticz/files/6190795/libleak.26575.sum.txt)

Anyone with better knowledge please help me it is much appreciated.

Cheers,
Beppe

**Comment by rwaaren** [comment]
I don 't see this behavior on my systems. Not with 13091 and not with 13108 (latest build as a=of now) 
Can you test without plugins and without scripts? and if OK, activate one plugin at a time?

**Comment by gizmocuz** [comment]
Could you add the motherboard hardware, this will create some additional sensors.
One of them is the Domoticz process memory and another is system memory usage.
Could you tell if it's the Domoticz or System memory
No issues here, indeed test without any plugins and scripts enabled first

**Comment by beeepus** [comment]
HI,

Thanks rwaaren & gizmocuz for fast response and guidelines to test.
My SD cards got corrupted so I'm kind of struggling with a new installation =/

But so far, the hardware plug-ins are stable, no indications of leak there.
It boils down to the python scripts being the issue.
With I have no scripts the memory usage on domoticz process is stable.
When I test to just add an empty file like script_device_none.py it starts to grow slowly.
If I add "import DomoticzEvents as DE" in that file it grows faster. 
I'll try to change to python 3.8.8 from 3.9.2 maybe that will help, i don't know.

I think I will have that done today and tested, if not Murphy shows up again and brick something else.
Cheers,
Beppe

**Comment by beeepus** [comment]
Hi @gizmocuz  @rwaaren,

Any idea why domoticz about page says Python Version: 3.9.2 and cmake 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.8", minimum required is "3.4")
-- Found PythonLibs: /usr/lib64/libpython3.8.so (found suitable version "3.8.8", minimum required is "3.4")
-- Python3 includes found at: /usr/include/python3.8

About Domoticz
Version: 2020.2 (build 13119)
Build Hash: 7d4e73906-modified
Compile Date: 2021-03-26 09:59:00
dzVents Version: 3.1.7
Python Version: 3.9.2 (default, Mar 23 2021, 05:23:39) [GCC 10.2.0]

If i add another module like "import os" and so it leaks even more so my assumption is that every time domoticz executes python it doesn't dispose it and keeps it in memory. That is why I see with pmap/smaps there are new address every seconds that remains there and never frees up.  

::Beppe

**Comment by gizmocuz** [comment]
@beeepus , that's because it found the 3.9.2 library on your system
First the system tries to find python3.9 then python3.8, then python3.7 etc

You seem to have multiple python versions installed

**Comment by beeepus** [comment]
@gizmocuz  ok I see.

So far after setting up my new system after recovering it and im now on build 13119, it's not growing like it did before.
![bild](https://user-images.githubusercontent.com/46396258/112749213-2b216100-8fc1-11eb-8e85-82729f27a517.png)

Approximately 73 MB in 5 hours.
Looking back in Prometheuss logs and stats i can see that it happens before. The graph is over two days.
![bild](https://user-images.githubusercontent.com/46396258/112749496-ded72080-8fc2-11eb-8007-9a1d6488b66f.png)
I restart domoticz every night so i haven notice that impact before. 

::Beppe

**Comment by gizmocuz** [comment]
There should be no need to restart Domoticz everynight.
Okey closing issue, hope your system stays stable now
