### ISSUE TITLE
MySensors: Unhandled sensor (sub-type=21), please report with log!

### ISSUE THREAD

**Issue by jimwildman** [domoticz/domoticz#475]
MySensors: Unhandled sensor (sub-type=21), please report with log!

using 
V_HEATER    21  Mode of header. One of "Off", "HeatOn", "CoolOn", or "AutoChangeOver"
and S_HEATER

**Comment by gizmocuz** [comment]
V_HVAC_FLOW_STATE or V_HEATER (as it seems to be its name now in the 1.6/2.0 development branch) is not (yet) supported in domoticz
Could you add support for it ?
Which sketch are you using ?

**Comment by jimwildman** [comment]
id love to but i dont have the source code. im not the developer..

is there a method to add this?

im using a custom sketch that tracks statistics of my mppt solar charger, and trying to accomodate the charger state, ie on, off, bulk, or floating.

jim wildman

**Comment by jimwildman** [comment]
So browsing through the source code I dont see any clear way to add support for device's.
If anyone can point me in the right direction, I would like to add support for several mysensor devices.
like the state of my mppt charger,
proper implementation of soil moisture meter's,
Pulse width modulation level of any pwm pin on an arduino,
e.t.c.
