### ISSUE TITLE
domoticz framework

### ISSUE THREAD

**Issue by Bartekn86** [domoticz/domoticz#4750]
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/594
Hi,
Any chance to "lift" the limit of 255 devices per plugin?

If you can  see many people reach the limit without any problems. If I copied the problem, please close it and provide a link to the original thread

**Comment by gizmocuz** [comment]
Please search the forum and the github issues first before creating a new issue.
Work is already in progress

**Comment by pipiche38** [comment]
FYI:

#4743

https://www.domoticz.com/forum/viewtopic.php?f=65&t=35452
