### ISSUE TITLE
Domoticz.Configuration() API in Python Framework do not support None value

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#4758]
While Domoticz.Configuration() recently added to the Python Framework to allow the plugin to store their configuration into the Domoticz Database and which is supported Dict data variable makes Domoticz crashing when one of the dictionary key item has its value set to None.

To store a python dictionary to JSON, the None value must be converted to null value.

I'm also wondering if it wouldn't be simple to allow Configuration to get also JSON type and in that case, it can be stored directly to the Db table without any conversion.

here is a short piece of code to be added in a python plugin.py

```
config_item = { '_count': 1 , 'None_Value': None}
Domoticz.Log("config_item: %s" %str(config_item))
Domoticz.Log("Json config_item: %s" %json.dumps(config_item ))
setConfigItem( Value=config_item)
```

**Comment by pipiche38** [comment]
According to 
* https://docs.python.org/3/c-api/none.html
* https://docs.python.org/3/library/json.html#encoders-and-decoders

I tried to add the here after code in `std::string CPluginProtocolJSON::PythontoJSON(PyObject* pObject)` but that doesn't help. 
In addition we will have to upgrade the `PyObject *CPluginProtocolJSON::JSONtoPython(const std::string &sData)`to revert "null" into Py_None 

```
if (pObject == Py_None)
                {
                        sJson += '"' + "null" + '"';
                }
```

My C++ are limited, so leave it to a most competent person

**Comment by pipiche38** [comment]
Other workaround is to simply encode all in base64 and decode when reading. much easier

**Comment by dnpwwo** [comment]
Can you retest this?
Recent changes to the way the framework handles strings should prevent this crash.
If not can you post a code snippet?

**Comment by waltervl** [comment]
@pipiche38 did you test?
