### ISSUE TITLE
Error: Razberry: Invalid data received! / zway 2.2.0 needs login/pass to work

### ISSUE THREAD

**Issue by olebrun** [domoticz/domoticz#476]
Hi,
Since I update zway to 2.2.0, it seems it need a login/pass.
Code in hardware/Razberry.cpp is ok :

```
const std::string CRazberry::GetRunURL(const std::string &cmd)
{
        std::stringstream sUrl;
        if (m_username=="")
                sUrl << "http://" << m_ipaddress << ":" << m_port << "/ZWaveAPI/Run/" << cmd;
        else
                sUrl << "http://"  << m_username << ":" << m_password << "@" << m_ipaddress << ":" << m_port << "/ZWaveAPI/Run/" << cmd;
        return sUrl.str();
}

```

But the web interface doesn't show the login/pass part for "Razberry via LAN Interfce".
It's pretty easy to enable it by enable login/pass part in www/app/HardwareController.js and adding some line.
Can you add it ?
Thank

**Comment by gizmocuz** [comment]
When you start domoticz (when having the razberry added yo your system), you will see a log message like:

**Razberry: Depricated, support will be removed (very!) soon!**

What does this mean ?

**Comment by olebrun** [comment]
Ok ... I know it, thanks ... so this mean for now it is not deprecated and some users use it because using the razberry with openzwave IS NOT reliable in their configuration...
I should probably look for another soft.
Thanks for your answer.

**Comment by gizmocuz** [comment]
with the latest beta you can now enter a username/password, but OZW is very reliable in most cases

**Comment by olebrun** [comment]
Thank you.
For OZW, here is my configuration : 
I'm using domoticz on an ESXi VM and use the razberry (via lan interface), it  works.
I have tried to replace zway with another instance of domoticz (on the raspberry) and use the "Domoticz - remote server" to export zwave devices to my main domoticz (on the ESXI VM). 
In this configuration, with OZW, zwave devices works some seconds an did not respond anymore after.
If you have an idea, I whould be happy to switch to OZW.
