### ISSUE TITLE
Not accessible from China and Los Angeles domoticz.com

### ISSUE THREAD

**Issue by jack9603301** [domoticz/domoticz#4763]
I am now using a proxy to visit from Los Angeles domoticz.com But sometimes I can't visit from China and Los Angeles domoticz.com (even if I use a proxy), the error is as follows:

![图片](https://user-images.githubusercontent.com/9047180/114009277-94dd1d00-9895-11eb-8618-6006436823aa.png)

Is it possible to remove the advanced defense status for users visiting China and Los Angeles?

**Comment by gizmocuz** [comment]
Yes we are very very sorry for this. The problem is that we have many (extreme many) hacking attempts all day from your country.
Please use a service as NordVPN, that will work (or another good VPN client)

**Comment by jack9603301** [comment]
@gizmocuz I have been visiting from Los Angeles. Even if I use a proxy, this error often occurs. If the attack traffic has stopped, I hope to lift the temporary limit

**Comment by jack9603301** [comment]
> Yes we are very very sorry for this. The problem is that we have many (extreme many) hacking attempts all day from your country.
> Please use a service as NordVPN, that will work (or another good VPN client)

I have been visiting from Los Angeles. Even if I use a proxy, this error often occurs. If the attack traffic has stopped, I hope to lift the temporary limit

**Comment by gizmocuz** [comment]
A proxy is different then a VPN...
