### ISSUE TITLE
Power usage in Belgium

### ISSUE THREAD

**Issue by 2Crazy187** [domoticz/domoticz#4771]
HI, 

When setting up my Domoticz for the power usages, i've noticed that you're using T1 as a low consumption & T2 as a high consumption. But here in Belgium is other way. So T1 is high consumption & T2 is low consumption. Low consumption is also from 10pm until 7AM and in the weekends.
Is it possible to change this for the Belgium users? Or does any one know a solution?

**Comment by GravityRZ** [comment]
i know it does not solve your problem but i have a dzVents scripts which splits up the total energy into low and high. 
maybe it is helpfull to you

```
-- Script wat de totale P1 meterstand opsplitst in aparte tellers voor hoog en laag tarief
return {
	on = {
		devices = {
			'Energie'
		}
	},
    logging = {
        --level = domoticz.LOG_DEBUG,    -- Uncomment this line to override the dzVents global logging setting
        -- marker = 'SME '.. ScriptVersion
     },	
	execute = function(domoticz, device)
	    local usage1 = tonumber(device.rawData[1])
		local usage2 = tonumber(device.rawData[2])
		local return1 = tonumber(device.rawData[3])
		local return2= tonumber(device.rawData[4])
		local usage = tonumber(device.rawData[5])
		local usageDelivered = tonumber(device.rawData[6])
        local P1data  = 280                                 -- Electra, P1 Smart Meter device
        local idxu1   = 323                                 -- Meter Usage low, Virtual device, counter
        local idxu2   = 324                                 -- Meter Usage High, Virtual device, counter
        --local idxr1   = 44                                -- Meter Return Low, Virtual device, counter
        --local idxr2   = 45                                -- Meter Return High, Virtual device, counter
        --local idxcons = 74                                -- Meter Actual Usage, Virtual device, counter
        --local idxprod = 75                                -- Meter Actual Production, Virtual device, counter		

        local function updateCounter(idx,value)   
            domoticz.devices(idx).updateCounter(value)
        -- domoticz.log("Set " .. domoticz.devices(idx).name .. " to: ",domoticz.LOG_DEBUG)
        end  
    
        updateCounter(idxu1,usage1)
        updateCounter(idxu2,usage2) 
        --updateCounter(idxr1,return1)
        --updateCounter(idxr2,return2)
        --updateCounter(idcons,usage)
        --updateCounter(idprod,usageDelivered)
    
	   
	end
}
```

**Comment by 2Crazy187** [comment]
HI,

When I use your script it gives the following errors:

021-04-14 08:03:33.912 Error: dzVents: Error: (3.0.2) There is no device with that name or id: 323
2021-04-14 08:03:33.912 Error: dzVents: Error: (3.0.2) An error occurred when calling event handler Scripr verbruik
2021-04-14 08:03:33.912 Error: dzVents: Error: (3.0.2) ...e/pi/domoticz/scripts/dzVents/generated_scripts/Test.lua:28: attempt to index a nil value

**Comment by GravityRZ** [comment]
you need to fill in the id's of your current devices
the id of your energy device goes to the place where it says 280
the 2 other devices you need to create
setup-hardware-create virtual devices choose counter(after creating check if it is set to energy)
those 2 id's you n eed to fill in on the place where it now says 323 and 324

 local P1data  = 280                                 -- Electra, P1 Smart Meter device
        local idxu1   = 323                                 -- Meter Usage low, Virtual device, counter
        local idxu2   = 324                                 -- Meter Usage High, Virtual device, counter

**Comment by waltervl** [comment]
This issue can be closed. Is discussed with TS on the forum. Is also no issue, just filling in the right tariff in the settings. https://www.domoticz.com/forum/viewtopic.php?f=34&t=36022&p=272809#p272809
