### ISSUE TITLE
virtual sensor humidity issue

### ISSUE THREAD

**Issue by empierre** [domoticz/domoticz#478]
widget presented with pressure and a persistant "Unknown" (seems barometer still)
graphs presented with "degree celcius"on an axis
data values of 67% (correct) on the widgetare graphed as 3%

**Comment by gizmocuz** [comment]
Does not seem correct... i will have a look

**Comment by gizmocuz** [comment]
When added from the hardware/dummy setup, it looks good in the devices tab:
![image](https://cloud.githubusercontent.com/assets/2265299/13033359/527b5cde-d314-11e5-810f-55618c731c7e.png)

we continue the search

**Comment by empierre** [comment]
yes I confirm, it is in the widget view it goes weird

**Comment by gizmocuz** [comment]
Can you post a screenshot ?
On my graph (just one value 50%) it looks ok.. the humidity is green, the axis is on the right side of the graph

**Comment by gizmocuz** [comment]
![image](https://cloud.githubusercontent.com/assets/2265299/13033418/e48cf97e-d315-11e5-8ceb-b195e5d2e6dc.png)

**Comment by empierre** [comment]
![capture du 2016-02-14 12-29-25](https://cloud.githubusercontent.com/assets/7287178/13033454/b89f4d8e-d316-11e5-8d0b-b6ce1b735e03.png)
here you can see the big "unknown" and wrong icon

**Comment by empierre** [comment]
degree is on the left

![capture du 2016-02-14 12-29-42](https://cloud.githubusercontent.com/assets/7287178/13033455/be866e76-d316-11e5-9654-2fcf4d18d68d.png)
also see my 61% displayed as 3%

**Comment by empierre** [comment]
![capture du 2016-02-14 12-29-56](https://cloud.githubusercontent.com/assets/7287178/13033456/c61836ba-d316-11e5-8772-95674393b307.png)

**Comment by empierre** [comment]
degree is on the left

**Comment by empierre** [comment]
also see my 61% displayed as 3%

**Comment by gizmocuz** [comment]
![image](https://cloud.githubusercontent.com/assets/2265299/13033453/b884f7fe-d316-11e5-8f0f-0145241d0c8d.png)

Nothing wrong, i think you look on the left side

I just updated my sensor to 67%, maybe it is the script that updates the virtual sensor ?

Plz check you database (Temperature table) it should display like:

![image](https://cloud.githubusercontent.com/assets/2265299/13033459/eebd42c2-d316-11e5-9a5a-612227e0d624.png)

**Comment by gizmocuz** [comment]
Else send me your database and i have a look

**Comment by empierre** [comment]
see above, in table this is good

**Comment by gizmocuz** [comment]
Thanks for the DB, why dont use use the leaf wetness sensor ?

**Comment by gizmocuz** [comment]
And why 30 Dummy hardware enties when you could have used just 1 ?

**Comment by gizmocuz** [comment]
Your database does not look good, the leaf wetness sensor has IDX 243
In the Temperature table (short log), i only see a humidity (of 1%) at 11:25 and 11:30 today
In the Calendar table for idx 243, i see a lot of very low values

![image](https://cloud.githubusercontent.com/assets/2265299/13033517/b20844dc-d319-11e5-9e1a-08dee12b7321.png)

Next to the fact that it misses day values a lot, and what is being plotted IS correct:

![image](https://cloud.githubusercontent.com/assets/2265299/13033520/e192643a-d319-11e5-8ea7-92949f0dedd3.png)

![image](https://cloud.githubusercontent.com/assets/2265299/13033522/eda465e8-d319-11e5-8080-25a1eb9f7e1b.png)

**Comment by gizmocuz** [comment]
But the graph has a title temperature, and i think the left scale should not be there, so there is room for improvement, but the values plotted for humidity are correct

**Comment by empierre** [comment]
I have my own mysensor gateway

**Comment by empierre** [comment]
yes but you saw my widget capture, so the value is not put into the table
no ?

**Comment by empierre** [comment]
another

**Comment by gizmocuz** [comment]
it can take 5 minutes for a value to become into the shortlog

**Comment by gizmocuz** [comment]
your value

![image](https://cloud.githubusercontent.com/assets/2265299/13033564/81fbf3ae-d31b-11e5-9915-f36515a8243c.png)

your graph

![image](https://cloud.githubusercontent.com/assets/2265299/13033565/8bd00438-d31b-11e5-904e-2bbe618ace76.png)

no problem ?

**Comment by gizmocuz** [comment]
Also you have wrong data in the sValue, and this should only a number, representing the humidity status, see the wiki about JSON

**Comment by empierre** [comment]
you are right, I am happy someone took (more) time than I to update the
wiki on this part ;-)

I'll look closer it seems now values are in. I did already test yesterday
and had the same issues.

Thanks for this correction. If you have more time with my DB, can you see
the iussues of transferring the CM180i-1 device to CM1 ?

Thanks,

 Emmanuel

**Comment by gizmocuz** [comment]
Okey, closing this issue
regading the transfer of cm180i-1 to cm1 ? (dont know what cm1 is),
how many sensors are we talking about ? if it is just a few, it is best to do this by hand
use a good application like "SQLite Expert Personal Edition", cant be that hard

**Comment by empierre** [comment]
Hello,

  I have two CM180i where I changed batteries.

  I cannot move from the UI  cm180i-1 to  cm1 and  cm180i-2 to CM2, when I
do so the originalshas no more name in the from down list (so two)

**Comment by gizmocuz** [comment]
try doing it by hand!
