### ISSUE TITLE
Domoticz don't start after last update

### ISSUE THREAD

**Issue by gael1980** [domoticz/domoticz#4782]
### Issue Guidelines

Hi,
After i update my domoticz. 
Domoticz don't start
I have this error : -bash: ./domoticz : impossible d'exécuter le fichier binaire : Erreur de format pour exec()

Gaël

**Comment by madcat-nl** [comment]
same issue here:
domoticz: cannot execute binary file: Exec format error

**Comment by gizmocuz** [comment]
Okey... What OS/platform ... 32 bit or 64 bit...
When you created this issue you where presented with some questions you needed to answer..

**Comment by gael1980** [comment]
I have a rpi 3b+ With debian

**Comment by gizmocuz** [comment]
Okey I am rebuilding the arm 32bit architecture... This will take an hour

**Comment by madcat-nl** [comment]
same here raspbian on armv7l 
the beta will start, but there i do not seen any devices in the list

**Comment by gizmocuz** [comment]
Could you try again? (Run updatebeta or updaterelease from the install folder)

**Comment by gizmocuz** [comment]
Try clearing browser + appcache of your browser

**Comment by iboot700** [comment]
I had the same issue, now it works fine (after clearing cache). Thanks a lot

**Comment by madcat-nl** [comment]
thanks work again!

**Comment by MatthieuF44** [comment]
Hi, 

I have the same issue, could you explain me how do you run updatebeta or updaterelease from the install folder ?

Kind regards.

**Comment by gael1980** [comment]
work again, thanks

**Comment by gizmocuz** [comment]
@mattdevue , if you have a raspberry pi, login to the pi
change to the domoticz folder

cd domoticz

run the updatescript

./updaterelease
