### ISSUE TITLE
sATELiNTEGRA CRASHES DOMORICZ AFTER LAST UPDATES

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#4784]
Last update domoticz broke SatelIntegra:
https://www.domoticz.com/forum/viewtopic.php?p=273042#p273042

Probably:
https://github.com/domoticz/domoticz/commit/4b29bab1ee08a5f67e671ede9894f7ce4446ccca#diff-c32c5196c3a0df73e7242c3fd38a6b8bf2b7615439d8d3d14556aeda38def5d8
OR
https://github.com/domoticz/domoticz/commit/3eb2f5d4779d8cbe04eac8ec0f8812f65c86af3c#diff-c32c5196c3a0df73e7242c3fd38a6b8bf2b7615439d8d3d14556aeda38def5d8

**Comment by gizmocuz** [comment]
So it seems libfmt is causing the issues ? The formatting looks correct... ?

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/pull/4770

**Comment by gizmocuz** [comment]
I just made a commit that removed the libfmt dependency and switches to a easier approach more compatible with printf
Hope this solves the problem.
Beta's are building but that could take two hours from now

**Comment by szczukot** [comment]
problem is not resolved

**Comment by gizmocuz** [comment]
@szczukot , should be, the libfmt changes have been reverted...

**Comment by gmacioso** [comment]
after several minutes Domoticz stops - no data on screens, header & buttons existing and active

build 13204

**Comment by gizmocuz** [comment]
@gmacioso , I just rechecked both commit changes (and this has been reverted as well) and I can't see anything different in the code that could cause this
Did you clear the browsers appcache + browser cache (two different things!) just to be sure ?

What do you mean with Domoticz 'stops' ? Is it crashes, and what do you mean with header & buttons existing and active ? Do you mean the user web interface is still active ? Meaning Domoticz did not stop ?

Did you try to disable all your hardware, and enable just one and see if thats working, and then move to the next ?

**Comment by szczukot** [comment]
Users are still reporting the problem:

https://www.domoticz.com/forum/viewtopic.php?p=273279#p273279

ps. We wrote at the same time ;)

**Comment by gmacioso** [comment]
The symptoms are as follows:
- I activate Satel connection
- for some time all seems to be ok
- suddenly Domoticz slows down, then web interface remains, but all devices vanish while changing page
- I could change page using buttons from web, but tehey're empty - not know for how long, as I disable Satel from command line
- restart Domoticz service w/o Satel and all works fine

Log (attached full log):

2021-04-19 18:08:21.428  Error: Domoticz(pid:16894, tid:12489('Alarm')) received fatal signal 11 (Segmentation fault)
2021-04-19 18:08:21.428  Error: siginfo address=0x41fe, address=0x7ffb0b78a5cb
2021-04-19 18:08:21.463  Error: Failed to start gdb, will use backtrace() for printing stack frame

2021-04-19 18:08:21.465  Error: #0  /home/domoticz/domoticz/domoticz :  + 0x3bad03 [0x55f553269d03]
2021-04-19 18:08:21.465  Error: #1  /home/domoticz/domoticz/domoticz : signal_handler(int, siginfo_t*, void*) + 0x205 [0x55f55326a765]
2021-04-19 18:08:21.465  Error: #2  /lib/x86_64-linux-gnu/libpthread.so.0 :  + 0x12730 [0x7ffb0b78a730]
2021-04-19 18:08:21.465  Error: #3  /lib/x86_64-linux-gnu/libpthread.so.0 : raise + 0x10b [0x7ffb0b78a5cb]
2021-04-19 18:08:21.465  Error: #4  /lib/x86_64-linux-gnu/libpthread.so.0 :  + 0x12730 [0x7ffb0b78a730]
2021-04-19 18:08:21.465  Error: #5  /home/domoticz/domoticz/domoticz : SatelIntegra::UpdateAlarmAndArmName() + 0x130 [0x55f5535a1940]
2021-04-19 18:08:21.465  Error: #6  /home/domoticz/domoticz/domoticz :  + 0x6f4229 [0x55f5535a3229]
2021-04-19 18:08:21.465  Error: #7  /home/domoticz/domoticz/domoticz :  + 0x6f426b [0x55f5535a326b]
2021-04-19 18:08:21.465  Error: #8  /home/domoticz/domoticz/domoticz :  + 0xaceecf [0x55f55397decf]
2021-04-19 18:08:21.465  Error: #9  /lib/x86_64-linux-gnu/libpthread.so.0 :  + 0x7fa3 [0x7ffb0b77ffa3]
2021-04-19 18:08:21.465  Error: #10 /lib/x86_64-linux-gnu/libc.so.6 : clone + 0x3f [0x7ffb0b5024cf]
[domoticz.zip](https://github.com/domoticz/domoticz/files/6341932/domoticz.zip)

**Comment by gizmocuz** [comment]
Maybe the easiest way to solve this is to use a older SatelIntegra source file compile Domoticz with this, if that works, compare the changes

**Comment by turonl** [comment]
Similar issue 
Hi I have  Version: 2021.1 (build 13207) running on RPI B+.
Log: 
2021-04-26 13:06:41.615 Error: Satel Integra 128WRL hardware (15) thread seems to have ended unexpectedly
2021-04-26 13:06:55.624 Error: Satel Integra 128WRL hardware (15) thread seems to have ended unexpectedly
2021-04-26 13:07:09.630 Error: Satel Integra 128WRL hardware (15) thread seems to have ended unexpectedly 

When I attach gdb - there is no plugin thread for satel integra - so it seems it doesn't start or dies immediately.

L.

**Comment by gizmocuz** [comment]
Looks like your hardware got stuck somewhere in **void SatelIntegra::Do_Work()**

**Comment by turonl** [comment]
Sorry - it was my fault - wrong port in config and the communication was not started.
Now I think i've returned to original issue:
2021-04-26 14:02:33.296 Error: Satel Integra 128WRL hardware (15) thread seems to have ended unexpectedly
2021-04-26 14:02:47.305 Error: Satel Integra 128WRL hardware (15) thread seems to have ended unexpectedly 

Memory corruption?

  25   Thread 0xa95f5220 (LWP 8030) "Satel Integra 1" 0xb6e50db4 in ?? () from /usr/lib/arm-linux-gnueabihf/libsqlite3.so.0
(gdb) thread 25
[Switching to thread 25 (Thread 0xa95f5220 (LWP 8030))]
#0  0xb6e50db4 in ?? () from /usr/lib/arm-linux-gnueabihf/libsqlite3.so.0
(gdb) bt
#0  0xb6e50db4 in ?? () from /usr/lib/arm-linux-gnueabihf/libsqlite3.so.0
#1  0xb6e98a34 in ?? () from /usr/lib/arm-linux-gnueabihf/libsqlite3.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by gizmocuz** [comment]
What hardware are you running on ?

**Comment by turonl** [comment]
I have Version: 2021.1 (build 13207) running on RPI B+.
Everything was fine on previous stable release (2020)

**Comment by turonl** [comment]
After a while i stopped randomly and got the following:
(gdb) bt
#0  __lll_lock_wait (futex=futex@entry=0xa30534 <m_sql+212>, private=0) at lowlevellock.c:46
#1  0xb6a96f44 in __GI___pthread_mutex_lock (mutex=0xa30534 <m_sql+212>) at pthread_mutex_lock.c:80
#2  0x00288600 in CSQLHelper::query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#3  0x00288a78 in CSQLHelper::safe_query[abi:cxx11](char const*, ...) ()
#4  0x005b3d44 in SatelIntegra::UpdateAlarmAndArmName() ()
#5  0x005b53c0 in SatelIntegra::Do_Work() [clone .part.317] ()
#6  0x005b5400 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<SatelIntegra::StartHardware()::{lambda()#1}> > >::_M_run() ()
#7  0x008bd91c in execute_native_thread_routine ()
#8  0xb6a94494 in start_thread (arg=0xa95f5220) at pthread_create.c:486
#9  0xb6947578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/

Is it stuck in UpdateAlarmAndArmName or it has been restarted ?

**Comment by gizmocuz** [comment]
Yes it seems so.
I made a small code change, please try beta 13234, if that does not solve it could you:

1 - try to compile in debug mode and maybe you get more information when it crashes
2 - contact me on the forum and supply me with test information (ipaddress, port, usercode, etc..) so I can try to debug this
3 - setup a Visual Studio under Windows 10 (express edition is free), build domoticz in debug mode, set break points and try to debug

I assume your raspberry is using the latest Raspbian , and you installed Domoticz via the sudo command or you are running the docker version.

**Comment by wasilukm** [comment]
For me, SatelIntegra started to work with beta 13234.
Thanks!

**Comment by gizmocuz** [comment]
That's great news! Hope we can close those issue

**Comment by turonl** [comment]
Success - works also on my setup :)
Fortunately I don't need to compile it on my own - my Raspberry Pi still configures CMake for 5 hours ;)

Thanks a lot for quick fix :)
