### ISSUE TITLE
BleBOX crashes Domoticz 2021.01

### ISSUE THREAD

**Issue by gmacioso** [domoticz/domoticz#4785]
Seems to similar issue like Satel case:
https://github.com/domoticz/domoticz/issues/4784

**Comment by PabloBrzoska** [comment]
The same for me
In log file
`Error: Domoticz(pid:4714, tid:4756('BLEBOXY')) received fatal signal 6 (Aborted)`

disabling the plugin in database allow me to run domoticz

**Comment by PabloBrzoska** [comment]
Update,

Betarelease solving the crash domoticz but Blebox devices doesn't work

In log file:
`2021-04-18 21:33:48.233 Error: BLEBOX: Invalid json received!`

On Hardware list all blebox devices with unknown status: type, uptime, hardware, firmware

**Comment by gizmocuz** [comment]
Great it's also solved. Regarding the invalid JSON, that's not related to this issue (and I don't think to the new stable release)
Best to continue this on the Forum

**Comment by PabloBrzoska** [comment]
I'll do that. Thank you
topic: https://www.domoticz.com/forum/viewtopic.php?p=273199#p273199

**Comment by gmacioso** [comment]
after several minutes Domoticz stops - no data on screens, header & buttons existing and active

build 13204
