### ISSUE TITLE
after 5 minutes domoticz crash 2021.1

### ISSUE THREAD

**Issue by marsflow2** [domoticz/domoticz#4786]
hey,

after 5 min the icons disappear on each tab and a lot of slowness, but the logs are good not error.
I went back to the previous version (2020.2)

thank you

**Comment by davidcomtois** [comment]
I'm also having this issue. Raspberry Pi, was installed using wget bash script. An update was offered on the web page and I did it. Now it only runs for five minutes, five seconds according to "about" page before it freezes. 

Version: 2021.1
Build Hash: 8547c5b7e
Compile Date: 2021-04-17 11:29:11
dzVents Version: 3.1.7
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

Uptime: 5 Minutes, 5 Seconds

**Comment by gizmocuz** [comment]
Could also depend on the hardware you are using.
But for now, try updating to the beta
from the install folder issue

./updatebeta

**Comment by davidcomtois** [comment]
Updating to beta didn't fix anything, still crash at exactly 5 minutes after start.
Disk space is not an issue. I suspect a database issue between versions. I'm only using motherboard sensors and a couple of 1wire devices.

**Comment by kiddigital** [comment]
Disable all hardware and turn them one 1 by 1 every more than 5 minutes to see when/which module causes the crash..
