### ISSUE TITLE
Authentication fails on Master Slave connection in version 13196

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#4787]
After upgrade from v 13191 (equals stable) to version 13196 the authentication fails.

> Error: Raspberry Pi 1: Authentication failed for user Domoticz-Master on 192.168.10.51:6144

This has probably been introduced in version 13195, when libfmt dependency has been removed.
See https://github.com/domoticz/domoticz/commit/82043c4d5 (line 86 in  hardware/DomoticzTCP.cpp)

Checking of all the consequences of this change and correcting it goes beyond my knowledge.

See, also https://www.domoticz.com/forum/viewtopic.php?f=6&t=36070&sid=a63f3ce3cf8511ca285752cbc48d2947

**Comment by gizmocuz** [comment]
Found the issue. It was indeed caused this. I regret using that library... But thankfully we have a better alternative now which is compliant with printf.
Beta's should all be ready now (windows setup soon)

**Comment by gizmocuz** [comment]
There still seems to be an issue, working on this

**Comment by felix63** [comment]
For me its fixed now.

**Comment by FireWizard52** [comment]
The same for me.
Everything is working fine now.
Thank you for your quick fix.
