### ISSUE TITLE
Domoticz 2021.1 (build 13196) master slave Authentication failed

### ISSUE THREAD

**Issue by baahver** [domoticz/domoticz#4788]
Today I updated to 2021.1 (build 13196) on both master and slave. 
Master is a RPi3b and Slave RPi4. Before never had an issue with master slave connection. Always working.
Log on Master: 
Error: RPI4: Authentication failed for user domoticz-slave on 192.168.188.63:6144
Log on Slave:
Status: Incoming Domoticz connection from: 192.168.188.80
Not warnings or errors on slave about this. 

I changed the user to default master user of slave and changed it back the user that was working before. 
I re-entered passwords and username on both slave and master. 
Without luck. 
No connection between master and slave domoticz.

Anything else I can post?

**Comment by gizmocuz** [comment]
@baahver, thank you for reporting, noticed this myself an hour ago.
I am debugging this issue at the moment, I think it has to do with the libfmt implementation

**Comment by baahver** [comment]
> @baahver Please mind your language.

I do not understand this? Is this about M-S setup naming?

This is a double post now: 
https://github.com/domoticz/domoticz/issues/4787

**Comment by gizmocuz** [comment]
Found the issue, I am building new beta's as we speak.
Don't mind the github-action bot, sometimes it's wrong ;)

**Comment by baahver** [comment]
Great!

**Comment by gizmocuz** [comment]
There should be a new beta available

**Comment by baahver** [comment]
Both are now: 2021.1 (build 13199)
But still the same error.

**Comment by gizmocuz** [comment]
Noticed, working on it.
Please continue on the other issue as this is indeed a double post

**Comment by FireWizard52** [comment]
@gizmocuz 

Tried beta 13199 right now.

It is still not working:

Still gives:

> 2021-04-19 12:08:27.175 Error: Raspberry Pi 1: Authentication failed for user Domoticz-Master on 192.168.10.51:6144

Compared to version 13196 I see

In the slave: 

> 2021-04-19 12:03:45.948 Status: Incoming Domoticz connection from: 192.168.10.50 (which is the Mater)

On the Master: 

>  2021-04-19 12:10:27.206 Status: Raspberry Pi 1: connected to: 192.168.10.51:6144
2021-04-19 12:10:27.209 Status: Raspberry Pi 1: disconnected from: 192.168.10.51:6144 
 (Which is the Slave)
This happens every 30 seconds.

**Comment by gizmocuz** [comment]
@FireWizard52 , that's what I mentioned in the previous post.

Found the issue... but as the CMake project file has been updated the build process is going to take an hour...

But... It's fixed, and tested. There where two issues

**Comment by baahver** [comment]
updated: 2021.1 (build 13203) as mentioned on Domoticz forum - [https://www.domoticz.com/forum/viewtopic.php?f=6&t=36070&p=273255#p273255](url)
And fixed!
Thanks gizmocuz!

**Comment by gizmocuz** [comment]
Great!, Thanks for the feedback!
