### ISSUE TITLE
Unhandled Meter Type

### ISSUE THREAD

**Issue by felix63** [domoticz/domoticz#4790]
Version: 2021.1 (build 13196)
Platform: Raspberry Pi 3b+ 
Plugin/Hardware: ZWave
Description:

I have a ZWeather+ from Popp & Co for measuring wind speed. Since OpenZwave went from 1.4 to 1.6 I have the errors listed below repeating them selves very regularly. Is there a fix for this?

```
2021-04-19 09:42:19.744 Error: ZWave: OpenZWave: Unhandled Meter type: Electric - Pulses, class: 0x32 (METER), NodeID: 115 (0x73), Index: 3, Instance: 1
2021-04-19 09:42:19.744 Error: ZWave: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 115 (0x73), CommandClass: METER, Label: Electric - Pulses, Instance: 1, Index: 3
```

**Comment by gizmocuz** [comment]
This type of sensor needs to be implemented... What do those pulses do ?

**Comment by gizmocuz** [comment]
I found some more information here

https://z-wave.by/wp-content/uploads/2019/07/z-weather-005206.pdf

Is it possible to enable 'accept new hardware/devices' under settings and update your Domoticz version to beta 13204 or higher ?
(Should be available now)

Hope it's working

**Comment by felix63** [comment]
<img width="1197" alt="Schermafbeelding 2021-04-19 om 17 48 19" src="https://user-images.githubusercontent.com/16501940/115265524-992bf480-a137-11eb-9669-96c0463d3cf3.png">

A new device has been created now. So far no more error messages. Great work. Thank you very much!
