### ISSUE TITLE
Error: Z-WAVE USB: OpenZWave: Invalid counter value received

### ISSUE THREAD

**Issue by RunnicFusion** [domoticz/domoticz#4792]
After installing the latest version of Domoticz today, and including all devices again, the log shows a lot (every 10/15 minutes) errors like:

`2021-04-20 11:17:23.326 Error: Z-WAVE USB: OpenZWave: Invalid counter value received!: (-21474678.000000) Node: 31 (0x1f), CommandClass: METER, Instance: 1, Index: 0, Id: 0x1F4C8012`

Node Id 31 is Neo Coolcam Powerplug: https://www.szneo.com/en/products/index.php?id=41
Before installing the latest release I never saw this kind of errors before.
Node is awake and reporting values.

**Comment by sincze** [comment]
I've noticed this also in the past with NEO plugs running new firmware.
My graphs were not nice and had a lot of negative values as well. (causing spikes). 
As I am running Beta somewhere in the Development process Domoticz caught these values and mentioned it in the log. 
So I see tons of these messages meanwhile my graphs look fine.

Were you running 2020.1 stable before ??
[Url:](https://www.domoticz.com/wiki/Domoticz_version_table_V2020.2)
12826 | 745eb5da7 | 20210107 | OpenZwave | Protect against extreme negative NeoCoolcam power values

**Comment by RunnicFusion** [comment]
> I've noticed this also in the past with NEO plugs running new firmware.
> My graphs were not nice and had a lot of negative values as well. (causing spikes).
> As I am running Beta somewhere in the Development process Domoticz caught these values and mentioned it in the log.
> So I see tons of these messages meanwhile my graphs look fine.
> 
> Were you running 2020.1 stable before ??
> [Url:](https://www.domoticz.com/wiki/Domoticz_version_table_V2020.2)
> 12826 | [745eb5d](https://github.com/domoticz/domoticz/commit/745eb5da7d36edf730939a9db5e34451f842cc64) | 20210107 | OpenZwave | Protect against extreme negative NeoCoolcam power values

Yes I was running 2020.1 before.

**Comment by gizmocuz** [comment]
Yes, this is a message specifically for this hardware! Suddenly a counter value is received that is lower then the previous..
But without this you would see (lots more) spikes
You can disable log messages for OZW if you like

**Comment by markruys** [comment]
It's a bug in the device firmware. OZW refuses (correctly) the counter value the device now and then reports. I've created a PR with a work around, but the OZW project seems not really supported anymore (the PR is open for like half a year now): https://github.com/OpenZWave/open-zwave/pull/2598

**Comment by gizmocuz** [comment]
Thats correct. Please have a look at the latest (beta) MQTT hardware where you can now use the auto discovery protocol for zwavejs2mqtt. OZW will be deprecated

**Comment by RunnicFusion** [comment]
> It's a bug in the device firmware. OZW refuses (correctly) the counter value the device now and then reports. I've created a PR with a work around, but the OZW project seems not really supported anymore (the PR is open for like half a year now): [OpenZWave/open-zwave#2598](https://github.com/OpenZWave/open-zwave/pull/2598)

Sorry for late response. For now i ignored all counter invalid log errors. But wondering, will there be a way to correct those readings? Error is not comming from Domoticz but the hardware is failing as I understand.

**Comment by waltervl** [comment]
Incorrect readings in Domoticz you can delete when in the device log by a shift+left mouseclick on the value in one of the graphs on the device log page.
https://www.domoticz.com/wiki/Managing_Devices#Remove_incorrect_value_from_database

**Comment by RunnicFusion** [comment]
> Incorrect readings in Domoticz you can delete when in the device log by a shift+left mouseclick on the value in one of the graphs on the device log page. https://www.domoticz.com/wiki/Managing_Devices#Remove_incorrect_value_from_database

Thanks for the reply. Beleve that's not the issue right now. Data in stats looks good (except for 1 of my devices showing a peak in 2020, can't delete it from Domoticz charts bebause its longer than 1 year ago...).
Data coming from the devices is incorrect.

```
2022-02-21 11:05:26.106 Error: Z-WAVE USB: Invalid counter value received!: (-21474526.000000) Node: 44 (0x2c), CommandClass: METER, Instance: 1, Index: 0, Id: 0x2C4C8012
2022-02-21 11:06:23.207 Error: Z-WAVE USB: Invalid counter value received!: (-21474688.000000) Node: 32 (0x20), CommandClass: METER, Instance: 1, Index: 0, Id: 0x204C8012
2022-02-21 11:12:15.567 Error: Z-WAVE USB: Invalid counter value received!: (-21474660.000000) Node: 33 (0x21), CommandClass: METER, Instance: 1, Index: 0, Id: 0x214C8012

```

**Comment by waltervl** [comment]
You will have to ignore these errors I suppose. Domoticz is filtering the incorrect values out and gives an error as this is something the device or OpenZwave should have handled. Perhaps switch over to Zwavejs2mqtt as the successor of OpenZwave. See the Domoticz wiki over Zwavejs2mqtt.
