### ISSUE TITLE
After restarting RPI nodes are lost

### ISSUE THREAD

**Issue by RunnicFusion** [domoticz/domoticz#4793]
After restarting the latest version of Domoticz (and version before that) nodes are lost after rebooting.
Need to trigger them manually as if most of them don't awake.

Sometimes when pressing heal or get node info button inside the z-wave settings the Domoticz install crashes. Any idea what I sould do?

**Comment by sincze** [comment]
Please fill the minimum requirements for support. like Domoticz version e.g..
Latest could be latest stable, latest beta. ;-) maybe add a screenshot. 
Did you migrate from version x to y? (so Zwave version 1.4 -> 1.6) this will give us some clues to assist.
