### ISSUE TITLE
When excluding z-wave node, related domoticz devices should be deleted (and are not)

### ISSUE THREAD

**Issue by jefft4** [domoticz/domoticz#4794]
Version: 2021.1 ; Ubuntu 20.04 on Intel.

When excluding a z-wave node from the mesh, the related domoticz devices are not removed from the system.  This leads to zombie devices, potential duplicate device names, etc that cause trouble later if not manually cleaned up.  

As this is a straightforward exclusion, not a 'replace device' or 'replace failed node', I would expect the domoticz devices related to the excluded node to be deleted, along with any DataPush and other records - a full cascading delete.

**Comment by waltervl** [comment]
Consider migrating to ZwaveJS2MQTT but not sure on the behavior when excluding a node.
https://www.domoticz.com/wiki/ZwaveJS2MQTT

**Comment by jefft4** [comment]
Would need to be sure of the behaviour, @waltervl - migrating is a big job, needs to be of some benefit!

**Comment by waltervl** [comment]
As I do not use Zwavejs2mqtt please ask this in the forum. https://www.domoticz.com/forum/viewforum.php?f=82
OpenZwave is deprecated and will not be updated. But do not fix what is not broken :-)

**Comment by gizmocuz** [comment]
@jefft4 , for a simple test you could disable the OZW hardware, install ZWaveJS2MQTT and test it in Domoticz, if everything is working, then perfect. If not, you can delete the MQTT hardware and all created devices will also be deleted.
But if something is not working, please report it (If possible on Slack)
