### ISSUE TITLE
Suggestion to add a possible solution in main/mainworker.cpp on "Error accessing automatic backup directories"

### ISSUE THREAD

**Issue by freekdk** [domoticz/domoticz#4795]
Most likely when this error occurs the directory .../backups does not exist or has the wrong rights.
I would suggest to add to this message the string: "Probably <full_name_of_directory> does not exits of has the wrong rights."

**Comment by gizmocuz** [comment]
maybe ... "... does not exists or has invalid rights!"

Please feel free to make a PR to change this

**Comment by freekdk** [comment]
OK with me, but it should include the name of the missing directory. It took me months to find the right name of the directory.

**Comment by waltervl** [comment]
The location is mentioned in the wiki documentation: https://www.domoticz.com/wiki/Application_Settings#Automatic_Backup

**Comment by freekdk** [comment]
I misread the name as backup where it should have been backups with an s added.
