### ISSUE TITLE
bug: idx of mobile devices

### ISSUE THREAD

**Issue by CherAlban** [domoticz/domoticz#4797]
I am having issues with the idx of mobile devices:

- The idxs of my mobile devices dsiplayed under Setup/More Options/Mobile Devices/ seem to increase slowly after a couple of days 

- In LUA, otherdevices_idx['mobile_device_name'] does not work for mobile devices

![image](https://user-images.githubusercontent.com/29152864/115750543-911ebf80-a398-11eb-9ae2-e113f13cbdcc.png)

**Comment by gizmocuz** [comment]
Do you use an application ? Could you also make create a issue at the application makers side ? (And reference this issue)
It could be that the UUID is not correctly calculated. This should be unique and there is no need to delete/re-create them

The only action that deletes a mobile device is that someone (the application for example) calls the Domoticz API function '**deletemobiledevice**'

In LUA, devices/otherdevices are for actual sensors found in the DeviceTable (in the database)
The "MobileDevices" is (as I have quickly checked) currently not implemented in Lua
Not sure what you want to do with this.
It does seem possible to send notifications to the mobile device

**Comment by CherAlban** [comment]
I am not sure what you mean with "Do you use an application", my only external application that interacts with mobile devices (and that I'm aware of)  is the Android Domoticz app.

Yes, sending notifications to mobile devices from LUA is working, when using the "midx" it is also working for individual devices. As my midxs are incrementing randomly, I thought I could look-up the midx by using the device name.

**Comment by gizmocuz** [comment]
@Cher, yes that is what I meant

**Comment by waltervl** [comment]
As the root cause is the app itself this issue will be closed.
