### ISSUE TITLE
Compile error when using new Log method in LuaHandler.cpp

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4798]
When I try to change the _log method to Log in LuaHandler.cpp I see below error. 
Would it be possible to use the new Log method here?

```
[ 16%] Building CXX object CMakeFiles/domoticz.dir/main/LuaHandler.cpp.o
/usr/local/domotica/git/beta/main/LuaHandler.cpp: In static member function ‘static int CLuaHandler::l_domoticz_updateDevice(lua_State*)’:
/usr/local/domotica/git/beta/main/LuaHandler.cpp:39:5: error: ‘Log’ was not declared in this scope; did you mean ‘log’?
   39 |     Log(LOG_ERROR, "CLuaHandler (updateDevice from LUA) : nvalue and svalue are empty ");

```

**Comment by kiddigital** [comment]
@rwaaren , the new Log method is only for hardware. It is part of the CDomoticzHardwareBase class and therefor available to classes that are based of this base class. Like most classes in the Hardware folder.

Most other parts of Domoticz have classes that are not based of this class and have to rely on the application wide scoped _log function.

Like the LuaHandler (based on LuaCommon).

**Comment by gizmocuz** [comment]
That's correct. All hardware should be derived from CDomoticzHardwareBase , I think there are currently 1 or 2 that have a very over-complicated design that should actually be refactored.

The LuaHandler is part of the EventSystem (If I'm correct?), Should this not always display a log message when a event is triggered (or failed) ? All other messages seems to be 'debug' related

**Comment by rwaaren** [comment]
@kiddigital , @gizmocuz , thanks for clarifying. Will try a different route to suppress messages from LuaHandler.cpp like

2021-04-03 11:26:57.478 CLuaHandler (updateDevice from LUA) : idx=397 nvalue= svalue=1860.0 invalue=0 signallevel=12 batterylevel=255

**Comment by gizmocuz** [comment]
@rwaaren , I think(hope) this is a debug message, please use _log.Debug for this

**Comment by gizmocuz** [comment]
Seen the PR, thanks!
