### ISSUE TITLE
Hrlp to understand something about cover

### ISSUE THREAD

**Issue by tomamplius** [domoticz/domoticz#4801]
### Help to understand something about cover
I have last domoticz release version, i use ZIGBEE2MQTT.
Currently i need to understand how add the device HK-ZCC-A (Sunricher Zigbee Curtain Motor Controller) currently unsupported.
I have create PR https://github.com/Koenkk/zigbee2mqtt.io/pull/714 and https://github.com/Koenkk/zigbee-herdsman-converters/pull/2505

Stack 1 : On device open is position are Zigbee officially expects 'open' to be 0 and 'closed' to be 100.
Stack 2 : On ZIGBEE2MQTT it's invert 'open' to be 100 and 'closed' to be 0.
Stack 3 : On domoticz "Blinds Percentage" is  'open' to be 0 and 'closed' to be 100 and "Blinds Percentage Inverted" is ZIGBEE2MQTT compatible.

All it's ok at this point, i use "Blinds Percentage Inverted"

But i need to create Switch state to up, down and stop.
Stop work but up set device to down and down set device to up.

Case 1 :  Blinds Percentage Inverted + no invert state
position : OK
Open close button on Blinds widget : OK
Switch : KO

Case 2 :  Blinds Percentage Inverted + zigbee-herdsman-converters invert function 
position : OK
Open close button on Blinds widget : KO
Switch : OK

Case 3 : Blinds Percentage  (no invert) + no invert state
position : KO
Open close button on Blinds widget : KO
Switch : KO

Case 4 : Blinds Percentage (no invert)  + no invert state
position : KO
Open close button on Blinds widget : OK
Switch : OK

I'm wrong?

**Comment by gizmocuz** [comment]
I don't understand the "switch" part... in the blinds percentage widget you can up/down
Do you see a stop button ?

It depends on the subtype of the blinds. The following subtypes supports a stop button:

RAEX
A-OK
Hasta
Media Mount
Forest
Chamberlain
Sunpery
Dolat
ASP
Harrison
RFY
ASA
DC106
Confexx

You can find the subtype number source file RFXtrx.h

You can change the subtype in the database

But I also think this needs to be implemented in the python plugin and it might be best to create a issue here:

https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin

**Comment by tomamplius** [comment]
Sorry i have understand i can rename action to invert them and conserve the old action

![image](https://user-images.githubusercontent.com/6951820/115964667-de7c6780-a525-11eb-9d5f-1e121f8fc301.png)

After rename : 

![image](https://user-images.githubusercontent.com/6951820/115964691-f94edc00-a525-11eb-8dc7-69897fe71b31.png)

Thanks for your and sorry for the inconvenience

**Comment by tomamplius** [comment]
Ok, i need to use "update DeviceStatus set SubType = XX where Unit in (12, 16);" where XX = 73 currently
I don't find where subtype are define to change to value RAEX

**Comment by tomamplius** [comment]
I use : "update DeviceStatus set Type = 25, SubType = 4 where Unit in (19, 18);"

to obtain 
![image](https://user-images.githubusercontent.com/6951820/115967411-c95a0580-a532-11eb-8b9c-1adc188199b9.png)

i will check to https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin
