### ISSUE TITLE
Solaredge API  (3-phase) DC / AC L2 conflict

### ISSUE THREAD

**Issue by robk358** [domoticz/domoticz#4803]
within SolarEdgeAPI.cpp in 3-phase configuration there is a conflict between:
"SendVoltageSensor(iInverterNumber, SE_VOLT_DC, 255, dcVoltage, szTmp);"  (line349)
and 
"SendVoltageSensor(iInverterNumber, iPhase, 255, acVoltage, szTmp);" (line 369)

SE_VOLT_DC is defined as 2, DC voltage is overwritten by AC L2 Voltage

**Comment by gizmocuz** [comment]
Thanks for reporting! I increased this number and there should be no conflict anymore. (beta 13227)
Existing users (1-phase) will get a new DC sensor and need to replace the old DC with the new one
