### ISSUE TITLE
No graphs after update to 2021.1

### ISSUE THREAD

**Issue by alexkiddde** [domoticz/domoticz#4805]
I have updated to latest stable 2021.1

Even after clearing browser cache, no graphs are showing for my sensors in latest Chrome. In Domoticz App for Android they are working.

Version: 2021.1
Build Hash: 8547c5b7e
Compile Date: 2021-04-17 17:29:11
dzVents Version: 3.1.7
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
Rasperry Pi 4 B

![image](https://user-images.githubusercontent.com/76263837/116137429-d4986700-a6d3-11eb-9bc1-7676121624a3.png)

**Comment by rwaaren** [comment]
Please use the forum to report these kind of issues and follow the steps described in [this wiki]( https://www.domoticz.com/wiki/Browser_Cache ) page on GUI related problems after an update. 
Thx.
