### ISSUE TITLE
Update, using the GUI, takes to long on slower computer.

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#4806]
When updating to a newer software release, using the GUI a counter, from 0 to 100, start to count (estimated 1 count per second?).
Since 2 releases Domoticz creates a backup tgz file. Perfect, but it takes time.

On a slower computer, e.g. Raspberry Pi 1B, the counter times out before the update has finished. This will give an indication of "network issues" and to try it later again.
Running ./updatebeta completes fine.

The update time on e.g. my Raspberry Pi 2B has increased from approx 20 (counts) to 80, but on an older RPi 1B it has increased from approx 60-70 to >100 and so does not finish the update.

Regards

**Comment by gizmocuz** [comment]
Thanks for reporting! I will decrease the time interval

**Comment by gizmocuz** [comment]
I think it also depends on your database size... my database size in 9 years (with quit a lot of sensors) is 23MB
I also won't recommend a RPI-1 anymore, besides the SD card issues, it's performance is way less then a RPI 3 or 4
The percentage counter was updates at a interval of 600ms, increased it to 1000

**Comment by FireWizard52** [comment]
Thanks for solving it.
> I think it also depends on your database size... my database size in 9 years (with quit a lot of sensors) is 23MB

My database size is only 786KB, as I use it only for test purposes. Only the "Motherboard" sensors are active and one MQTT for monitoring.

> I also won't recommend a RPI-1 anymore, besides the SD card issues, it's performance is way less then a RPI 3 or 4

I know. It is a left-over from years ago and is only used for testing things.

> The percentage counter was updates at a interval of 600ms, increased it to 1000

Let us see, if this is enough.

**Comment by FireWizard52** [comment]
@gizmocuz 

I tested it with the update from build 13240 to 13243, but for a Raspberry Pi 1B the new value of 1000 ms is still not enough.
I think this device will need maybe 2000 ms. I will measure it, when I install the next update. How this will do on a Pi Zero, I don't know. You also may want to decide to leave it as it is, but then it is only possible to upgrade from the command line.

I would even prefer that, as it gives you a lot more info:

Stopping Domoticz...
Making backup of current installation...
Output file: backups/domoticz_backup_20210502_144159.tar.gz
Backup finished...
Downloading latest beta version...
Checking file integrity...
Installing new version...
.......................................
Starting Domoticz... (please standby...)
Done...

**Comment by gizmocuz** [comment]
You do what you want to do..... But 2000 is way to slow! Maybe it's time to update to a RPI3 or 4 as mentioned above
You do have to run 2 updates for the new time to be noticed... one update will set the time to 1000ms for the next update

**Comment by gizmocuz** [comment]
Please feel free to contribute to the project and pipe the output from the update script to the gui if you like.... Not a bad idea

**Comment by FireWizard52** [comment]
@gizmocuz 

> You do what you want to do..... But 2000 is way to slow! Maybe it's time to update to a RPI3 or 4 as mentioned above

I agree a Raspberry Pi 1B has reached already EOL, some years ago. So do not worry about it,
As said, it is a "left-over" and I use it only for testing things.

> You do have to run 2 updates for the new time to be noticed... one update will set the time to 1000ms for the next update

I know, but it was just to inform you about the result of this test.

> Please feel free to contribute to the project and pipe the output from the update script to the gui if you like.... Not a bad idea

Indeed not a bad idea, but I doubt if I'm able to do that, but at least I can have a look.
