### ISSUE TITLE
Xiaomi Aqara switch not recognize 

### ISSUE THREAD

**Issue by yekmen** [domoticz/domoticz#4807]
Tested with 2021.1 & 2020.1

I correctly pair my Gateway V2 with my new switch Aqara but it's not recognized by domoticz, 
I have this msg in log
XiaomiGateway (ID=2): unhandled model: 'remote.b186acn02', name: 'Unknown Xiaomi device'

Any idea ?

**Comment by rwaaren** [comment]
> Tested with 2021.1 & 2020.1
> 
> I correctly pair my Gateway V2 with my new switch Aqara but it's not recognized by domoticz,
> I have this msg in log
> XiaomiGateway (ID=2): unhandled model: 'remote.b186acn02', name: 'Unknown Xiaomi device'
> 
> Any idea ?

Added this device to XiaomiGateway.cpp Will be in the next available beta. Please test and report back. Thx

**Comment by gizmocuz** [comment]
Beta 13240 available for testing

**Comment by yekmen** [comment]
How can I test the fix in the beta version ? 
I used Domoticz with docker. 

thx for your quick fix.

**Comment by gizmocuz** [comment]
In your docker folder issue

docker-compose pull && docker-compose up --force-recreate --build -d && docker image prune -f

This will update the docker to the latest version

**Comment by yekmen** [comment]
ok I was not awear that the beta branch was on the release branch in docker. 

Anyway , the fix is working well, now the switch is recognized !
