### ISSUE TITLE
[Docker] stable tag?

### ISSUE THREAD

**Issue by DAVIZINH0** [domoticz/domoticz#4810]
Hello, 
The docker container y great idea! and a lot of people of my spanish telegram group use.
But the only tag is the "latest" version.
Can you create another tag to "stable" version?

thanks a lot!

**Comment by gizmocuz** [comment]
I think this should be possible, but I have no idea yet how to do this.
Are you familiar with this ?

Currently we use in the buildx command the following

--tag domoticz/domoticz

https://github.com/domoticz/domoticz-docker

**Comment by DAVIZINH0** [comment]
i dont have idea :-(
but i will search more info, give me some days

thanks a lot!!!

edit:
I never create a dockerhub image and maybe i say some stupid advices. sorry

i think this video is all we need? can you see it and tell me if works. 
If not i will search more info!
https://www.youtube.com/watch?v=JYxwfS9Ar8U

thanks @gizmocuz

**Comment by rezzalex** [comment]
Hello,

keeping the "old" Builds of DZ Beta would be great, to be able to roll back to a previous docker beta version in case of bugs.
I know I can keep my own dz docker image... but I would feel safer if I can retrieve any version.
I think @stas-demydiuk used previously had automation to trigger a new docker build when a new DZ release was available, Could you confirmed @stas-demydiuk

**Comment by gbouthenot** [comment]
Not only a [stable] tag should be added, but there should also be tags with version number. Currently, there is none, so, the tag is "latest". And there are some problems with that, see "What's Wrong With The Docker :latest Tag?" : https://vsupalov.com/docker-latest-tag/, "Do Not Run a Container with the :latest Tag" : https://cloudmaniac.net/docker-container-never-use-latest-cicd-pipeline/. There are many more pages about why using latest is not a good practice.
Thank you !

**Comment by gizmocuz** [comment]
I know, but experience lags here... The build script is also in the repository, please make a PR with the needed changes

**Comment by waltervl** [comment]
This is merged but the docker instruction on the hub is not changed. How to use these tags, how to install stable?

**Comment by waltervl** [comment]
should be documented with https://github.com/domoticz/domoticz-docker/pull/8

**Comment by DAVIZINH0** [comment]
i use the latest in domoticz, and when I download the image i can select the tag to deploy.

when you use your docker the first time you can select this. not?

**Comment by waltervl** [comment]
I don't know, I am not a docker user.

**Comment by DAVIZINH0** [comment]
ok, sorry i understand that you need to install the stable docker version and dont know how.
Its easy, use the tag in the compose or select the stable image when you download it in synology. 
For all the people that use docker its easy to select the correct image (beta or stable)

**Comment by gizmocuz** [comment]
Thanks walter for the PR, but i made some changes to make it more clear.

@DAVIZINH0 , please see the updated readme with the new tags

https://github.com/domoticz/domoticz-docker

**Comment by DAVIZINH0** [comment]
Great!! thanks for all!
