### ISSUE TITLE
deviceID from ZWave devices in MQTT messages send from domoticz are not always consistent with JSON/GUI  

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4814]
The JSON apply some c++ magic to the DeviceID string before including it when the device is from ZWave hardware. This is shown in GUI and in the result of /json.htm?type=devices

Seems to be done in WebServer.cpp code starting at line 9531. The same magic is missing in MQTT.cpp so the resulting MQTT message contains a copy of what's in the database for DeviceID, regardless the hardware type.

Background and details in forum topic [forum topic Z-Wave MQTT question](https://www.domoticz.com/forum/viewtopic.php?f=24&t=36211)

**Comment by gizmocuz** [comment]
It depends.... What you see here as 'DeviceID' is the exact value that is inside the database/DeviceStatus table
Some people update a device with MQTT via the 'idx' (rowid), and some people with a combination of hardware_id, device_id, unit
What you see in the json/web Gui, is 90% a hex representation of this value.
Reason for this is that you can see the node_id better (for example with zwave devices)
This is done in WebServer.cpp, line 9430 and up

It is of course possible to use the same display in MQTT, but this will make it extreme difficult for people updating devices with a combination hardware_id/device_id/unit
If we drop support for this (and only allow updating via the idx), I am more then happy to do so

**Comment by rwaaren** [comment]
@gizmocuz. Thx for clarifying. I was not aware of the option to update using the combination of hardware_id, device_id,and unit.
I also have no idea how many users / systems use this method so to drop support seems a shot in the dark.

Would it be an option to add something as hDeviceID to the MQTT message containing the json/web GUI representation of the deviceID?

**Comment by gizmocuz** [comment]
Seems I was totally wrong... the IDX is always needed, all other parameters are queried from the database.
I made a patch that should now display the same DeviceID as in the JSON
(I have not looked at a possible difference for ZWave devices... Looking at the webserver code, it does not alter the "ID" and the ID is set above  ~ line 9430

New beta's have been build, should be solved in beta 13251

**Comment by mgugu10** [comment]
Everyhing is OK now  with build 13251. MQTT reflects JSON output regarding Zwave node Id.
Thank you @gizmocuz  and @rwaaren  for this very quick problem resolution

**Comment by rwaaren** [comment]
@gizmocuz Thx. for the quick fix. 
@mgugu10 Thx for the confirmation.
