### ISSUE TITLE
Domoticz crashes after an update

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#4815]
Hello, after today's update, domoticz crashes immediately after starting.

2021-05-06 17:22:12.753 Error: Domoticz(pid:881, tid:990('Plugin_ASIO')) received fatal signal 11 (Segmentation fault)
2021-05-06 17:22:12.753 Error: siginfo address=0x371, address=(nil)
2021-05-06 17:22:12.758 Error: (Tasmota): Socket Shutdown Error: 107, Transport endpoint is not connected

2021-05-06 17:25:23.910 Error: Domoticz(pid:879, tid:982('Tasmota')) received fatal signal 6 (Aborted)
2021-05-06 17:25:23.910 Error: siginfo address=0x36f, address=(nil)

Wenn ich Shelly und Tasmota PlugIn deaktiviere, funktioniert es wieder.

Debian Buster/ Pi 3b+

Version: 2021.1 (build 13251)
Build Hash: 2c0402c53
Compile Date: 2021-05-06 14:57:41
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

Uptime

**Comment by rwaaren** [comment]
What was the last version you used that was without this crash?

**Comment by salopette** [comment]
I don't know exactly, but it was the one from the day before yesterday yesterday, I check several times a day and if the update is there, I'll do it!

**Comment by salopette** [comment]
2021-05-07 10:48:13.478 Shellys hardware started.
2021-05-07 10:48:13.740 Shellys: (Shellys) New hardware creation enabled
2021-05-07 10:48:13.791 Shellys: (Shellys) Connected to MQTT Server: 192.168.178.37:1883
2021-05-07 10:48:13.477 Status: Shellys: (Shellys) Entering work loop.
2021-05-07 10:48:13.478 Status: Shellys: (Shellys) Started.
2021-05-07 10:48:13.687 Status: Shellys: (Shellys) Initialized version 0.6.0
2021-05-07 10:48:15.180 Error: Domoticz(pid:7682, tid:7840('Shellys')) received fatal signal 6 (Aborted)
2021-05-07 10:48:15.180 Error: siginfo address=0x1e02, address=(nil)
Top

**Comment by gizmocuz** [comment]
@salopette , could this be caused by a python plugin ?
Is it possible to stop your domoticz instance, and install the docker version ?
Some users seem to have a issue with python plugins, but it seems to be working stable when using the docker
(See the domoticz download page for the docker link)

**Comment by salopette** [comment]
I have no idea about Docker.
It runs on pi 3 debian buster for me.
Other plugins that I installed via the plugin manager work.
Z2M continues to work without any problems.

**Comment by salopette** [comment]
everything worked until yesterday, but the update broke it.

**Comment by gizmocuz** [comment]
You can check the commit log of all the changes... I hardly believe it has anything to do with this.
Actually looking at it... can't be related to any recent commits...
If you disable the event system + dzVents + python, does it run ?

**Comment by salopette** [comment]
2021-05-07 13:52:01.040 Status: EventSystem: reset all events...
2021-05-07 13:52:01.044 Status: dzVents: Write file: /home/pi/domoticz/scripts/dzVents/generated_scripts/DB Check.lua
2021-05-07 13:52:01.045 Status: EventSystem: reset all device statuses...
2021-05-07 13:52:01.077 Status: EventSystem - Python: Failed dynamic library load, install the latest libpython3.x library that is available for your platform.
2021-05-07 13:52:01.078 Status: EventSystem: Started

**Comment by salopette** [comment]
here is the full log after the crash

[Neues Textdokument.txt](https://github.com/domoticz/domoticz/files/6441579/Neues.Textdokument.txt)

**Comment by gizmocuz** [comment]
What is the DB Check script doing ? I hope not directly accessing the domoticz database ?

**Comment by salopette** [comment]
> --[[ -- DB check
        
        Will give you a warning when something is wrong with the (domoticz) sqlite database
        requires sqlite3 
            install command on linux:    sudo apt install sqlite3 
            install command on openwrt:  opkg install sqlite3-cli
            install command on synology: sudo /opt/bin/opkg install sqlite3-cli
            
            History:
            20190125: first public release  
            20190228: Include official sqlite3 error messages on failure
            20190808: Include optional trigger of follow up OS command
            20191005: add Telegram as notification option
            20191005: Include optional set of an Alert device with result of check          
            20191019: Include RC message in alert device 
            20200108; Fixed bug(ss) in aftersucces / afterSuccess (case matters and double s also ! )

]]--
return {
            on =    {  
                        timer   =   { 
                                        "at 20:00",             -- change to a time that suits you
                                        "at 07:00",
                                    },            
                    },
    
        logging =   {  
                        level     =   domoticz.LOG_ERROR,       -- change to LOG_ERROR after you tested  the script
                        marker    =   "DB check" 
                    },

    execute = function(dz)
        -- =======================  Settings below this line =================
        local email               = true                        -- set to false if you don't want an Email when something wrong with database
        local notify              = true                        -- set to false if you don't want a notification when something wrong with database
        local afterSuccessCommand = '/bashdir/copyDB.sh'        -- set to full qualified path of your followUp script or false if you don't need a followUp after success
        local afterFailCommand    = false                       -- set to full qualified path of your followUp script or false if you don't need a followUp after fail
     
        local followUpAfterFail   = false                       -- set to false if you don't need a followUpAfterFail
        
        local alert = {
                        active   = false,                             -- set to false if you don't want an Alert device set. 
                        device   = "dbCheck result",                 -- Name of your alert device (only needed when you set active = true )
                        failText = "Problem in database",
                        OKText   = "database OK",    
                      }
                      
        local subject             = "Domoticz database check"   -- Free text
        local emailaddress        = "xxxxxxxx@gmail.com"        -- Your Email address
        local path                = "/home/pi/domoticz/"            -- full qualified path to your database 
        local database            = "domoticz.db"               -- database filename + extension
        -- local database         = "corrupt.db"                -- test database filename + extension
                                                                    -- you can corrupt a test database by just load it in an editor
                                                                    -- and remove a couple of bytes
        local sqlite              = "/usr/bin/sqlite3"          -- location of your sqlite3 tool (use the command 'which sqlite3' to find location)
  
        local myNotificationTable     =     {
                                             -- table with one or more notification systems. 
                                             -- uncomment the notification systems that you want to be used
                                             -- Can be one or more of
                                             
                                             dz.NSS_GOOGLE_CLOUD_MESSAGING, 
                                             -- dz.NSS_HTTP, 
                                             -- dz.NSS_KODI, 
                                             -- dz.NSS_LOGITECH_MEDIASERVER, 
                                             -- dz.NSS_NMA,
                                             -- dz.NSS_PROWL, 
                                             -- dz.NSS_PUSHALOT, 
                                             -- dz.NSS_PUSHBULLET, 
                                             dz.NSS_PUSHOVER, 
                                             -- dz.NSS_PUSHSAFER,
                                             dz.NSS_TELEGRAM,
                                            }
        -- =======================  No modification needed below this line ==================

         local function logWrite(str,level)             -- Support function for shorthand debug log statements
            dz.log(tostring(str),level or dz.LOG_DEBUG)
        end
    
        local space                   = " " 
        local baseCommand             = "sudo" .. space .. sqlite .. space .. path .. database .. space
        local checks                  = {} 
              checks                  = {
                                                  "\'select count(id) from deviceStatus;\'",
                                                   "\'.schema\'",
                                                  "\'pragma integrity_check;\'",
                                                  "\'pragma foreign_key_check;\'",
                                        }

        local function rc2Text(rc)
            local errorMessages =   {
                                          [0] = "database OK",
                                          [1] = "Generic error",
                                          [2] = "Internal logic error in SQLite",
                                          [3] = "Access permission denied",
                                          [4] = "Callback routine requested an abort",
                                          [5] = "The database file is locked",
                                          [6] = "A table in the database is locked",
                                          [7] = "memory allocation failed",
                                          [8] = "Attempt to write a readonly database",
                                          [9] = "Operation terminated by sqlite3_interrupt",
                                         [10] = "Some kind of disk I/O error occurred",
                                         [11] = "The database disk image is malformed",
                                         [12] = "Unknown opcode in sqlite3_file_control",
                                         [13] = "Insertion failed because database is full",
                                         [14] = "Unable to open the database file",
                                         [15] = "Database lock protocol error",
                                         [16] = "Internal use only",
                                         [17] = "The database schema changed",
                                         [18] = "String or BLOB exceeds size limit",
                                         [19] = "Abort due to constraint violation",
                                         [20] = "Data type mismatch",
                                         [21] = "Library used incorrectly",
                                         [22] = "Uses OS features not supported on host",
                                         [23] = "Authorization denied",
                                         [24] = "Not used",
                                         [25] = "2nd parameter to sqlite3_bind out of range",
                                         [26] = "File opened that is not a database file",
                                     }
            return(errorMessages[rc] or "Unknown error")
        end

        local function followUp(cmd)
            os.execute('sudo ' .. cmd ..' &')
        end

        local function osExecute(base,check)
            local fileHandle     = assert(io.popen(base .. check, 'r'))
            local commandOutput  = assert(fileHandle:read('*a'))
            local returnTable    = {fileHandle:close()}
            check = check:gsub("'","") .." result ==>> " ..  ( returnTable[3] ~= 0 and "Failed: " .. rc2Text(returnTable[3]) .. commandOutput .. " (".. returnTable[3] .. ")" or true and "OK" )
            logWrite("Command " .. check )
            return check,returnTable[3]            -- rc[3] contains returnCode
        end

        local function checkDatabase()
            if dz.utils.fileExists(path .. database) then
                if dz.utils.fileExists(sqlite) then
                    for _,check in ipairs (checks) do
                        local result,rc = osExecute(baseCommand,check)
                        if rc ~= 0 then 
                            return rc, result  
                        end
                    end
                else
                    return -1,"sqlite3 not installed"
                end
            else
                return -1,"wrong path to database"
            end
            return 0
        end

        local function updateAlert(rc)
            if alert and alert.active then
                local now = dz.time.rawDate .. ', ' .. dz.time.rawTime .. ': '
                local alertLevel = dz.ALERTLEVEL_RED
                if rc == 0 then  alertLevel = dz.ALERTLEVEL_GREEN end
                dz.devices(alert.device).updateAlertSensor(alertLevel, now .. rc2Text(rc))
            end
        end

        -- main program
        local rc, result = checkDatabase()
        if rc ~= 0 then
            logWrite(result,dz.LOG_ERROR)
            if email then dz.email(subject,result,emailaddress) end
            if notify then 
                dz.notify(subject, result or "Dbase check encountered unknown error", dz.PRIORITY_NORMAL, dz.SOUND_INTERMISSION,"",  myNotificationTable ) 
            end
            if afterFailCommand and ( rc > 0 ) then followUp(afterFailCommand) end
        else
            if afterSuccessCommand then followUp(afterSuccessCommand) end
        end
        updateAlert(rc) 
    end
}

**Comment by salopette** [comment]
I am not the only one!

https://github.com/joba-1/Tasmoticz/issues/22

**Comment by gizmocuz** [comment]
You can not access the Domoticz database when Domoticz is running

**Comment by salopette** [comment]
and now?

**Comment by gizmocuz** [comment]
Sorry, I don't care. You should NOT access the Domoticz database when Domoticz is running. Even if Domoticz is not running I would strongly advise not to touch it! Unless somehow you need to.
I suggest to use the 'backup database' option from the settings page, do this once a month maybe if you like ?
SQLite is not a database that allows multiple connections

**Comment by gizmocuz** [comment]
If you have removed this db plugin, and still have issues, try the docker version as mentioned above

**Comment by salopette** [comment]
It's not a DB plugin, it was just a dZvents script.
I have deactivated it, but it does not result in any success.

![sshot-2](https://user-images.githubusercontent.com/32480002/117530766-43809480-afdf-11eb-8520-e0feda37c975.jpg)

**Comment by gizmocuz** [comment]
Plugin/Script, all the same. You should NOT access the Domoticz database when Domoticz is running.

So the next step would be to try the docker version of Domoticz.
The reason why I ask this is very simple, It's a clean environment, and there have been others where the docker version functions properly.
It's also easy to setup/test. (Just make sure that your current domoticz version is not running otherwise you might have issues with ports being in use, or you could use different ports for your docker)

https://hub.docker.com/r/domoticz/domoticz

**Comment by salopette** [comment]
docker doesn't work for me
I don't know how to do it right?

![sshot-2](https://user-images.githubusercontent.com/32480002/117536456-65881000-affb-11eb-97c8-d2e387cefb56.jpg)

**Comment by gizmocuz** [comment]
The recommended way is to use docker-compose

mkdir /opt/domoticz
cd /opt/domoticz
Inside this folder create a file (docker-compose.yml) with the following contents

docker-compose.yml

```
version: '3.3'

services:
  domoticz:
    image: domoticz/domoticz
    container_name: domoticz
    restart: unless-stopped
    # Pass devices to container
    # devices:
    #   - "/dev/serial/by-id/usb-0658_0200-if00:/dev/ttyACM0"
    ports:
      - "8080:8080"
    volumes:
      - ./config:/opt/domoticz/userdata
    environment:
      - TZ=Europe/Amsterdam
      #- LOG_PATH=/opt/domoticz/userdata/domoticz.log

```
Now you can launch the container by issuing:

docker-compose up -d

In your above screenshot (default docker way, not docker-compose) you are having illegal characters on the first line ( > )

You can also run it with a single line... 

`docker run -d -p 8080:8080 -p 8443:443 -v ./config:/opt/domoticz/userdata -e TZ=Europe/Amsterdam --device=<device_id> --name=domoticz domoticz/domoticz
`

But, would recommend to use the docker-compose way

**Comment by salopette** [comment]
It doesn't seem to work with the docker version either.

https://github.com/enesbcs/Shelly_MQTT/issues/93#issuecomment-835780520

**Comment by svde** [comment]
> It doesn't seem to work with the docker version either.
> 
> [enesbcs/Shelly_MQTT#93 (comment)](https://github.com/enesbcs/Shelly_MQTT/issues/93#issuecomment-835780520)

I'm experiencing the same issue. My hunch is it's somehow related to https://github.com/domoticz/domoticz/commit/c1526b1277f43bbb214b3c74d1a85685ee1056ae. A build based on https://github.com/domoticz/domoticz/commit/1582636a96bd25d5c4d9cc98844ab8a87ddc7026 (13249) worked fine.

**Comment by gizmocuz** [comment]
Don't think this is related , but I made a patch for invalid ID's in the latest beta version

**Comment by salopette** [comment]
It works again!
I tell you that the update was to blame and not my SQL DB !!

**Comment by gizmocuz** [comment]
The update is NOT the issue, the problem is that in your system you have devices with a invalid ID (not numeric)
And you should not access the Domoticz SQLite database when Domoticz is running.
When you do a external query against it, it will lock the database, causing Domoticz to have issues writing in the database

But do note that in the near feature only valid Device ID's will be allowed (numbers).
It is also causing the upstream message system to have problems.

For instance, when you use Zigbee2MQTT python plugin, the device id's is named like "0x00158d0004aadb63_all"
But a normal device_id is 32bit
When you have a main Domoticz controller, and a secondary , and you want to receive that zigbee temperature sensor from the main, it is not possible

Instead, the developer of this python plugin should create a internal database/dictionary and map "0x00158d0004aadb63_all" to a row_id, like 1,2,3,4,5 etc

**Comment by gizmocuz** [comment]
But I hope you have a good experience now with docker-compose as well. It is really easy that all user-data is in one folder, great for making backups

**Comment by rwaaren** [comment]
> When you do a external query against it, it will lock the database, causing Domoticz to have issues writing in the database
> 
According to sqlite.org this is only the case when you write something to the database. Not when you use a select or one of the pragma queries.

**Comment by gizmocuz** [comment]
Guess who is writing to the database....
I have hand on expirience

**Comment by kiddigital** [comment]
> > When you do a external query against it, it will lock the database, causing Domoticz to have issues writing in the database
> 
> > 
> 
> According to sqlite.org this is only the case when you write something to the database. Not when you use a select or one of the pragma queries.
> 
> 

With each user request/action in Domoticz, data is written to the database. For example the session info gets updated. Scripts that 'emulate' a user, even just for reading, causes DB writes.

Accessing the DB other than through the Domoticz code base should be considered dangerous. Only do so when Domoticz is NOT running.

**Comment by pipiche38** [comment]
@gizmocuz could you please clarify your comment on the DeviceID ?
<img width="1164" alt="Screenshot 2021-05-10 at 13 57 49" src="https://user-images.githubusercontent.com/8291674/117655723-bd5b7e00-b197-11eb-8768-ac1aa0ac4c9b.png">

The python plugin framework is presenting this field as a string, which I think is inline with the Db definition ( [DeviceID] VARCHAR(25) NOT NULL). Do you plan to change that ?

**Comment by rwaaren** [comment]
@kiddigital 

> With each user request/action in Domoticz, data is written to the database. For example the session info gets updated. Scripts that 'emulate' a user, even just for reading, causes DB writes.

Sorry but you are misinformed. When you access the domoticz database via sqlite3 or similar tool and only use select statements nothing is written to the database.
If you are convinced it is otherwise please show me where and how this is implemented in domoticz or in sqlite amalgation or how to force this writing to the database with a slect statement.

**Comment by rwaaren** [comment]
> Guess who is writing to the database....
> I have hand on expirience

Happy to learn. Please enlighten me.

**Comment by kiddigital** [comment]
@rwaaren 

> 
> 
> @kiddigital
> 
> > With each user request/action in Domoticz, data is written to the database. For example the session info gets updated. Scripts that 'emulate' a user, even just for reading, causes DB writes.
> 
> Sorry but you are misinformed. When you access the domoticz database via sqlite3 or similar tool and only use select statements nothing is written to the database.
> If you are convinced it is otherwise please show me where and how this is implemented in domoticz or in sqlite amalgation or how to force this writing to the database with a slect statement.

Maybe I wasn't clear enough. When you have Domoticz (the application/process) running, there is frequent interaction with the DB ofcourse depending on how busy your setup is (amount of active hardware modules, sensors being updated, scripts, end-users using the UI, etc.). Sensors updates are writing to the DB (obviously), but also a lot of (UI) interaction are causing DB writes as well just because they update stats, logging, statusses, sessions, etc.

When you use SQlite(3) or simular tools to access the DB **at the same time, meaning with a running Domoticz process,** you definitely run the risk to corrupt the DB or cause other issues as the Domoticz process is likely to want to perform write operations. (see https://sqlite.org/lockingv3.html)

If you stop Domoticz (so no active Domoticz process), it is not a problem to access the DB through other tools if you know what you are doing.

For those that really know what they are doing, it is doable to perform some querying (maybe even using _read_uncommited_) and not cause any harm to the DB. But I would really want to warn users NOT to give it a try (only when Domoticz is NOT running) as it is easy to cause harm and (very) hard to recover.

BTW... I haven't looked into the source code at this detailed level yet with focus on DB connections, writing, commiting, isolation levels, colations, etc. so I might definitely be misinformed on some aspects. Always open to learn from the details provided :)

**Comment by rwaaren** [comment]
@kiddigital 


> When you use SQlite(3) or simular tools to access the DB **at the same time, meaning with a running Domoticz process,** you definitely run the risk to corrupt the DB or cause other issues as the Domoticz process is likely to want to perform write operations. (see https://sqlite.org/lockingv3.html)
> 

Sorry but again no. There is no risk to corrupt the DB when the sqlite3 or similar tools are only used for select - or pragma integrity  / pragma foreign_key_check statements. The locking mechanism in sqlite prevents this by design.
Also:: the domoticz database is set to jpurnal_mode WAL (see [sqlite.org](https://www.sqlite.org/wal.html) where i(amongst other information) it is stated 

**_WAL provides more concurrency as readers do not block writers and a writer does not block readers. Reading and writing can proceed concurrently._**

**Comment by kiddigital** [comment]
@rwaaren , thx. Wasn't aware that Domoticz uses WAL-mode already. Nice (I should have looked at the code 😉).

**Comment by gizmocuz** [comment]
That is also not correct. Even with WAL mode enabled there is database write access (also to the WAL file)
You can easily test this, for example under windows... run Domoticz make sure it is a busy system

Open the Database with SQLite Expert Personal edition, now count how many times you get a dialog popup 'database is locked'
And there is a lot of writing at the moment...
I thought about doing a in memory database for the real-time data and using the actual database for the short/long logs

But if you want to do it anyway, go ahead, just remind that I warned you
If you open the database with a external tool at the time write actions are performed you might end up in a error which is not an error.
Also when you are writing to the database (and locking it) and Domoticz needs to write/flush... data is not written... could be lost
(And it's not meant to be touched anyway while running)

@pipiche38 , the DeviceID was initially meant as a number or (short) hex string. But as it is now used as varchar (25 characters) it is best to keep it this way.
My issue is to 'push' these devices to other systems, for example a Domoticz main/client system (primary and secondary instance)
But that's a different topic and I'm going to solve that soon in another PR to test

**Comment by gizmocuz** [comment]
Do mind that under WIN32 WAL mode is NOT used

**Comment by rwaaren** [comment]
> Do mind that under WIN32 WAL mode is NOT used

Yes, I did see that in the source but according to the comment it is a test?
If not can you help me understand why the difference in journal-mode between Windows and other platforms?
If DELETE is considered the best option for WIN32 can setting the PRAGMA busy_timeout > 0 prevent these "database is locked" situations without causing other issues in domoticz?
It does work in my test system.

**Comment by pipiche38** [comment]
@gizmocuz just ping me if anything around the DeviceID should be tested.
