### ISSUE TITLE
Domoticz "MH-S220 One-Load+" zwave relay not switching

### ISSUE THREAD

**Issue by ruchechnik1** [domoticz/domoticz#4816]
The "MH-S220 One-Load+" does not switch the relay via sw1, well via sw2
However the device's relay is switching sw1 and sw2 in the Open Z-Wave Control panel and  toogle switch

Found this in the logs at startup:
2021-05-07 10:54:17.913 Status: AeonLabUSB: A DNS Error Occurred
2021-05-07 10:54:19.445 Status: AeonLabUSB: SendSwitchIfNotExists: Device '43.instance.1.index.0.commandClasses.38' (Level) with DeviceID '00002B01' matches '43.instance.1.index.0.commandClasses.37' (Switch). Domoticz will use the Dimmer (and hide the Switch).

It looks like the switch device is defined as a dimmer it explains why it is not switching at all.

Version: 2021.1 (build 13243)

![image](https://user-images.githubusercontent.com/83811914/117425915-9563e480-af23-11eb-83fb-79839330b9a8.png)

![image](https://user-images.githubusercontent.com/83811914/117425704-56359380-af23-11eb-9cc5-ff8d291c7c49.png)

**Comment by gizmocuz** [comment]
Are these the only switches you received from this node, or are there other switches as well ?

**Comment by ruchechnik1** [comment]
Only switches:

![image](https://user-images.githubusercontent.com/83811914/117431974-1cb45680-af2a-11eb-93e8-e3015828f3d2.png)

idx 601 work well and idx 600 not

**Comment by gizmocuz** [comment]
Reason for this is because mostly more switches are created (also one that switches both of them)
You have 'accept new hardware' enabled in the settings ? If not, please enable this, then disable the zwave hardware and enable it again.

**Comment by gizmocuz** [comment]
Is this a node that can control two lights ? Because it seems there is only one relay

**Comment by ruchechnik1** [comment]
Until the last update of the last stable release from stable release , everything was working
it only one relay , with 2 inputs: s1 s2  (hotel switch)

**Comment by gizmocuz** [comment]
So from 2020.2 to 2021.1 ... yes there have been lot's of changes
So you can still operate the light via 601 ? What is the issue ? Why do you also want to operate 600 ?

**Comment by waltervl** [comment]
Still an issue on latest Stable? Did you already think of migrating to ZwavJS2MQTT as OpenZwave is out of maintenance?
https://www.domoticz.com/wiki/ZwaveJS2MQTT
