### ISSUE TITLE
Switches with "Unit" = 0 => no "devicechanged" triggered

### ISSUE THREAD

**Issue by rrraf** [domoticz/domoticz#4826]
Hi,

I use a RFlink hardware with Domoticz on a Rasberry Pi3. I have a remote LYCT505 (433Mhz Chacon 54561) with 4 raws (`1-2-3-4`) of on/off buttons in each 4 "chanels/positions" (`i-ii-iii-iv`) + 2 global (`G`) on/off buttons" independent of chanels/positions.
Domoticz in successfully populated devices with the same "ID" according to the protocol and 17 "Units" (0 to 16 = 1+(4x4) = 1+16). 
Everything is working fine with the switches (states, on or off action) except that LUA scripts (or Blockly) do NOT detect/get triggered on "devicechanged" for the device with the Unit = 0 (the G button at the bottom of the remote).
Looking at the database, it looks like Unit = 0 is often used for sensors/status/family_group and Unit > 0 is used for "positions". In this situation, the remote has action buttons on Unit 0. Could you please check it out?
Many thanks.

![CHACON-LYCT-505_02](https://user-images.githubusercontent.com/29224455/118380446-0a997e80-b5e2-11eb-99ce-ee3cf832692e.jpg)

![remote505](https://user-images.githubusercontent.com/29224455/118380670-d030e100-b5e3-11eb-9be4-b0e6e18b4b9f.jpg)

Domoticz Stable Release 2021.1 on Pi3

**Comment by rwaaren** [comment]
> Could you please check it out?

Just checked but cannot replicate the issue. Both Lua and dzVents script are triggered by a device update for RFLink device with unit 0.

Maybe if you activate debug logging you will see something that points in the direction of a cause.

**Comment by waltervl** [comment]
Still an issue?

**Comment by rrraf** [comment]
working now : remote with unit number "0" is triggering LUA script ok 👍
