### ISSUE TITLE
How to use Domoticz rtl_433 via serial number

### ISSUE THREAD

**Issue by mojso** [domoticz/domoticz#4831]
How to use Domoticz rtl_433 via serial number. I tried this command in domoticz -d:1234, but it does not work. this command appears in the log status
-d1231 -p 52 -g 35 -f 434.00e6 -f 433.72e6 -f 433.98e6 -H 90 
missing ( : ) in the command -d:1231

Raspberry pi 3b plus
Domoticz Version: 2021.1 (build 13256)

**Comment by michahagg** [comment]
In Rtl433.cpp, the colon (:) is stripped from the cmdline:

`removeCharsFromString(m_cmdline, ":;/$()``<>|&");`

In the rtl433-README at https://github.com/merbanan/rtl_433 it says the command knows the '-c' option:

`[-c <path>] Read config options from a file`

Could you use that option to read your options (including -d :1231) from a separate file?

**Comment by mojso** [comment]
without success.  I think it reads the file from terminal , but an error occurs on the first character, unknown keyword "-d".

**Comment by michahagg** [comment]
Try a conf-file like https://github.com/merbanan/rtl_433/blob/master/conf/rtl_433.example.conf.

It contains instructions to translate the command-line arguments to option keywords.

**Comment by mojso** [comment]
Thank you Dude, Domoticz rtl_433 works wia serial number
