### ISSUE TITLE
[LUA] Add function otherdevices_nvalue()

### ISSUE THREAD

**Issue by MuadDibVV** [domoticz/domoticz#4832]
Is it possible to add a function otherdevices_nvalue() ?

The goal for me is to simply recover the alert level of an alert device.

It should look like this :

In file main/EventSystem.cpp
In function ExportDeviceStatesToLua :

	luaTable.InitTable(lua_state, "otherdevices_nvalue", (int)m_devicestates.size(), 0);
	for (const auto &state : m_devicestates)
	{
		luaTable.AddNumber(state.second.deviceName,
				   (state.first == item.id && item.reason == REASON_DEVICE) ? item.nValue : state.second.nValue);
	}
	luaTable.Publish();

**Comment by rwaaren** [comment]
> Is it possible to add a function otherdevices_nvalue() ?

Th nvalue can already be found in table **devicechanged_ext**.

**Comment by gizmocuz** [comment]
@MuadDibVV , I also think you should be able to use/control the alert device via dzVents (updateAlertSensor)

**Comment by MuadDibVV** [comment]
Thank you for your quick answer.

I think I can't use "devicechanged_ext" because I want information from a device which has not been modified.

I know that I should rewrite my scripts in dzVents but I haven't found the courage to do it yet

**Comment by rwaaren** [comment]
You could also use the otherdevices  and include a relation table in your Lua script where alertText. (sValue) maps to alertLevel (nValue).

local myAlert =
{
     ['NOTSET'] = 0,
     ['OK'] = 1, 
     ['NOK'] = 4,
}
  
When needed please continue the discussion on the forum
