### ISSUE TITLE
v2021.1 - Devices page is Empty

### ISSUE THREAD

**Issue by Coturex** [domoticz/domoticz#4834]
After updating from v2020.2  →  v2021.1   (using ./updaterelease script )
All devices  seems working fine, however _http://x.x.x.1:8080/#/Devices_  page is empty !

![img1](https://user-images.githubusercontent.com/53934994/119113814-c6fda500-ba25-11eb-9ab1-dc8d62026b6c.png)

![img2](https://user-images.githubusercontent.com/53934994/119114084-1643d580-ba26-11eb-8d63-f3b61ecae3ff.png)

 < Chris

**Comment by rwaaren** [comment]
99% of these type of issues are browser cache / app ache related.
Check the forum.
