### ISSUE TITLE
v2021.1 - MQTT send Scene command

### ISSUE THREAD

**Issue by Coturex** [domoticz/domoticz#4836]
Sending a Mqtt Scene Command like ;
→  {"command": "switchscene", "idx": 24, "switchcmd": "**Toggle**" } 
seems no more implemented. It worked on my v2020.2's domoticz version.

→  {"command": "switchscene", "idx": 24, "switchcmd": "**On**" }
works fine.

**Comment by rwaaren** [comment]
I cannot replicate this is on my systems. Are you sure you send this command to a group and not to a scene?
(a scene cannot Toggle or be switched Off. A scene can only be switched On)

**Comment by Coturex** [comment]
Ok I note that this is not possible on a scene, however I was relying on the  [online documentation](https://www.domoticz.com/wiki/MQTT)

> Sending a Scene Command
>{"command": "switchscene", "idx": 24, "switchcmd": "On" }
>{"command": "switchscene", "idx": 24, "switchcmd": "Toggle" }

 it seemed to me that it worked on the old versions ... but it may be a mistake from me, I'm not sure ;)
I have changed my programs.
Thank you

**Comment by gizmocuz** [comment]
Nope, you can only activate a scene, not toggle it or turn it off. This is because in a Scene you put switches with the wanted state (ON/OFF)

**Comment by rwaaren** [comment]
@Coturex, thx for pointing to the online documentation

I updated [ it ](https://www.domoticz.com/wiki/MQTT) to make it more clear.
