### ISSUE TITLE
Domoticz+openwrt

### ISSUE THREAD

**Issue by spothz** [domoticz/domoticz#4837]
hi i have installed domoticz on openwrt and configured all hardware, after reboot all settings get lost.  It is clear that the settings are saved in the var / lib directory, this is RAM and when you reboot it is reset.  How can I fix this?
I tried to fix it like this but it didn't help
 nano / etc / config / domoticz, open it in the option userdata section, set the path to the example
 option userdata '/ etc / domoticz /'

 Go to
 nano /etc/init.d/domoticz open it in the config_get userdata "$ section" "userdata" section and install instead
 config_get userdata "$ section" "userdata" userdata / var / lib / domoticz write
 config_get userdata "$ section" "userdata" userdata / etc / domoticz it doesn't help domoticz stops working.

**Comment by waltervl** [comment]
Please make a forum topic about this.

**Comment by waltervl** [comment]
@gizmocuz please close. Is solved in https://www.domoticz.com/forum/viewtopic.php?f=6&t=36354&p=275382
