### ISSUE TITLE
[BleBox] Support for wLightBoxS with wLightBox API

### ISSUE THREAD

**Issue by jakubpal** [domoticz/domoticz#4840]
Hello, 
I updated my BleBox wLightBoxS and now I'm unable to control it with my Domoticz. I investigated the issue a little and I think that this is problem with API type support. wLightBoxS had wLightBoxS API (https://technical.blebox.eu/archives/wLightBoxSAPI/), but now it has wLightBox API (https://technical.blebox.eu/openapi_wlightbox/openAPI_wLightBox_20200229.html). There are sample device responses:

GET /api/device/state
```
{
  "device": {
    "deviceName": "My wLightBoxS",
    "type": "wLightBox",
    "product": "wLightBoxS",
    "hv": "s_0.1",
    "fv": "0.1022",
    "universe": 0,
    "apiLevel": "20200229",
    "id": "112233445566",
    "ip": "192.168.1.2",
    "availableFv": null
  }
}
```

GET /api/rgbw/state
```
{
  "rgbw": {
    "desiredColor": "00",
    "currentColor": "00",
    "lastOnColor": "ff",
    "durationsMs": {
      "colorFade": 0,
      "effectFade": 1000,
      "effectStep": 1000
    },
    "effectID": 0,
    "colorMode": 3
  }
}
```

Please consider adding support for updated wLightBoxS.

**Comment by Rebel-111** [comment]
Is any chance that this topic will be solved soon?

**Comment by szczukot** [comment]
@jakubpal  @Rebel-111 is it working or still not?
