### ISSUE TITLE
dzVents: time.matchesRule()

### ISSUE THREAD

**Issue by jcligny** [domoticz/domoticz#4842]
Hello.

time.matchesRule combination does not work since update to 2021.1.

`local plageScript = dz.time.matchesRule('at 08:15-17:30 on mon,tue,wed,thu','08:10-17:00 on fri')` will return `domoticz/dzVents/runtime/Time.lua:616: attempt to index a nil value (upvalue 'gTimes')
`

Solved using a second local variable but before combination worked fine.

**Comment by rwaaren** [comment]
This worked in some builds but was never supported (or documented).
 
Combined rules are now supported (and documented in the wiki) in build 2021.1 - 13223 onwards by using the new 'or' keyword .
So rule must be changed to dz.time.matchesRule('at 08:15-17:30 on mon,tue,wed,thu or at 08:10-17:00 on fri')

**Comment by jcligny** [comment]
Many thanks I'll wait the new release to restore old code.

**Comment by gizmocuz** [comment]
@jcligny , there won't be a new release that works with your old code.
Best to upgrade to the beta version if you need this functionality...
