### ISSUE TITLE
Disable a specific Log Error to be notified? (no solution from Forum)

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#4843]
Hi,

I try here as well, if someone might have a straight forward solution to my question...

https://www.domoticz.com/forum/viewtopic.php?f=28&t=36371

Thanks in advance!

**Comment by kiddigital** [comment]
Not straight forward, but check the latest Beta as their is a change that routes PlugIn logging to the correct PlugIn logs, so maybe now turning plugin logging off gives the desired result.

**Comment by RicardP** [comment]
@kiddigital Thanks, it is easy to try at least :) I will test the latest beta and see if it helps.

**Comment by RicardP** [comment]
@kiddigital It seems promising that build 13300 solved my issue, it was a very straight forward solution in my opinion :)
