### ISSUE TITLE
RTL_433 ID not push to Domoticz for Misol/1

### ISSUE THREAD

**Issue by nips1900** [domoticz/domoticz#4845]
Hi,

i'm using domoticz on a raspberry pi. I have 3 sensors Misol/1. They are visible in Domoticz, but only one at the time because they all have the same ID: 00000000. I know they don't have the same ID because when i run rtl_433 in cmd line, i can see they have different ID. I have many other sensor and i can see they all have their right ID.

could you please help?

Laurent

**Comment by gizmocuz** [comment]
@nips1900 , could you post here some packets (JSON format) of the output of rtl_433 containing the ID ?
Maybe the ID is in a different field and we need to use this for the Misol/1

**Comment by nips1900** [comment]
Hi,
please find the JSON from rtl_433 command line (rtl_433 -F json):

{"time" : "2021-06-03 17:59:32", "model" : "Fineoffset-WH51", "id" : "00de3g", "battery_ok" : 1.000, "battery_mV" : 1600, "moisture" : 48, "boost" : 0, "ad_raw" : 238, "mic" : "CRC"}
{"time" : "2021-06-03 17:59:32", "model" : "Fineoffset-WH51", "id" : "00de3g", "battery_ok" : 1.000, "battery_mV" : 1600, "moisture" : 48, "boost" : 0, "ad_raw" : 238, "mic" : "CRC"}

{"time" : "2021-06-03 18:03:02", "model" : "Fineoffset-WH51", "id" : "00de3g", "battery_ok" : 1.000, "battery_mV" : 1600, "moisture" : 48, "boost" : 0, "ad_raw" : 240, "mic" : "CRC"}

Below is the image of how it is recognized by Domoticz. Domoticz ID is 000000 while in rtl_433 it is 00de3g. It is also written 00de3g on the product itself.

![image](https://user-images.githubusercontent.com/39700275/120718307-1bc60480-c497-11eb-9f08-43b77e62290a.png)

I hope it helps!

**Comment by waltervl** [comment]
Already implemented?
