### ISSUE TITLE
DSC Smoke Detector not recognize in Domoticz

### ISSUE THREAD

**Issue by nips1900** [domoticz/domoticz#4848]
Hi,

do you think you could add this device?

Unhandled sensor reading, please report: ({"time" : "2021-05-31 11:50:07", "model" : "DSC-Security", "id" : 5175788, "closed" : 1, "event" : 0, "tamper" : 0, "battery_ok" : 1, "xactivity" : 0, "xtamper1" : 0, "x tamper 2.0, "exception" : 0, "esn" : "4ef9e7", "status" : 195, "status_hex" : "c3", "mic" : "CRC", "mod" : "ASK", "freq" : 433.902, "rssi" : -0.135, "snr" : 8.524, "noise" : -8.659})

**Comment by gizmocuz** [comment]
Yes that should be no problem. Is this datagram taken when there was a alarm/test ? I see a 'closed' , 'event' and a 'status' field

**Comment by nips1900** [comment]
I think it is a schedule auto test. There is a few per day.

**Comment by gizmocuz** [comment]
Would it be possible to log a datagram when you press the test button ?

**Comment by nips1900** [comment]
Certainly, how do I do that?

**Comment by gizmocuz** [comment]
Please don't directly reply via email to Github as it will include some private parts you don't want too ;)

You can run the RTL_433 command manually (please make sure it outputs JSON), and there should be a test button on the device

**Comment by nips1900** [comment]
Hi,
please find the JSON from rtl_433 command line (rtl_433 -F json):

{"time" : "2021-06-03 18:05:21", "model" : "DSC-Security", "id" : 4504188, "closed" : 1, "event" : 0, "tamper" : 0, "battery_ok" : 1, "xactivity" : 0, "xtamper1" : 0, "xtamper2" : 0, "exception" : 0, "esn" : "44ba77", "status" : 195, "status_hex" : "c3", "mic" : "CRC"}

is it what you need?

thank you for your help!

**Comment by waltervl** [comment]
Already implemented?
