### ISSUE TITLE
Usage Last Month and Usage Last Year in Log file is empty after update to 13311

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#4852]
Hi,

After update to version 13311 from 13300 the graphs in the log for "Usage Last Month" and "Usage Last Year" are empty for P1 Smart Meter, Energy.

It is the case for both the P1 Smart Meter device as the Enphase Production Total.

For screenshots, etc, see forum post at 
https://www.domoticz.com/forum/viewtopic.php?f=6&t=36429

**Comment by laplug** [comment]
The above link to the forum wants to opens a reply window.
Here's the link to the message:
[https://www.domoticz.com/forum/viewtopic.php?f=6&t=36429](url)

**Comment by laplug** [comment]
Here's a direct link to the post (not a reply window): https://www.domoticz.com/forum/viewtopic.php?f=6&t=36429

**Comment by laplug** [comment]
Found one possible clue in the domoticz.log:
`2021-06-03 20:40:43.150  Error: Parameter sensorarea missing with groupby '(null)'`
`2021-06-03 20:40:43.150  Error: Parameter sensorarea missing with groupby '(null)'`

**Comment by moorspatje** [comment]
Hi, 

I have the same problem after updating to 13311. No Month and Year usage available for the P1 Smart Meter.

**Comment by FireWizard52** [comment]
I can confirm the error messages in the log. A lot.
Never seen this before .

**Comment by michahagg** [comment]
I've found the problem! I'm currently compiling and testing the fix. I will make a PR with the fix.

Edit: when PR #4851 is merged, this problem will be fixed.

**Comment by FireWizard52** [comment]
Hello @michahagg 

After upgrade to version 13314 this problem is solved.

Thanks for the fix and the quick response.

Regards

**Comment by jenshenk** [comment]
Hi!
Thanks for the quick update indeed!
However, while this is fixed now the graphs for switches are still empty since the update to 13311.

**Comment by magicwoody** [comment]
Seems to be persistent only on firefox browser. Chrome works fine with 13311, Firefox Chart stays invisible. After upgrading to 13314 colour scheme of the graph is white instead of default. Clearing cache etc no changes. Firefox still no graphs

**Comment by Oleg-Sob** [comment]
Updated to version 13314, the logs in the energy meters disappeared.

![1](https://user-images.githubusercontent.com/71137109/121811876-76691880-cc6e-11eb-8434-dc6ee3d010c1.PNG)

![2](https://user-images.githubusercontent.com/71137109/121811882-7a953600-cc6e-11eb-8fc1-1e7d81bfdf24.PNG)

**Comment by Oleg-Sob** [comment]
> Кажется, сохраняется только в браузере Firefox. Chrome отлично работает с 13311, Firefox Chart остается невидимым. После обновления до 13314 цветовая схема графика вместо цвета по умолчанию белая. Очистка кеша и тд без изменений. Firefox по-прежнему без графиков
The color scheme of the chart is changed by clearing the cache.

**Comment by jenshenk** [comment]
did you try in an incognito/private window? This issue was solved for me after the 13314 update and with cache clearing it was also fixed in the non incognito windows.. however, for switches it is still not solved for me.... my guess is that this is another graph type

![image](https://user-images.githubusercontent.com/83426476/121812222-613cbb80-cc67-11eb-9d5f-6484bb7221f5.png)

![image](https://user-images.githubusercontent.com/83426476/121812251-7580b880-cc67-11eb-96fe-e5537307320c.png)

**Comment by Oleg-Sob** [comment]
Kesh cleaned, opened incognito, the logs in the energy meters are empty.

**Comment by Oleg-Sob** [comment]
When editing the type of meter from energy to water, the graph is shown.

![3](https://user-images.githubusercontent.com/71137109/121813052-1163f180-cc73-11eb-9121-dc2b916df908.PNG)
![4](https://user-images.githubusercontent.com/71137109/121813053-145ee200-cc73-11eb-8754-cb8734820268.PNG)
![5](https://user-images.githubusercontent.com/71137109/121813108-48d29e00-cc73-11eb-8a6a-b1ea0363a1cc.PNG)

Why is that ?

**Comment by Oleg-Sob** [comment]
Rolled back to stable version, all logs appeared. Everything is bad in 13314, logs for 7 days are not displayed.

**Comment by jenshenk** [comment]
Sounds bad indeed.. But interesting you could just roll back to stable! I was also thinking about this since my original idea of running on beta is cool also changed to a bit of breaking stuff which is logical but can also become frustrating... did you loose anything about your setup? events, switches etc.? the last time I did this I had to start completely from scratch again which is why I did not do this again (reason I found out was a change in database structure)

**Comment by Oleg-Sob** [comment]
I have not lost the data. I didn't like that the magazines began to open much longer and there is no data for 1 day and for 7 days, maybe in the future I will install the beta version again, until I like how it works.
