### ISSUE TITLE
[Question] no version information when compiling downloaded source

### ISSUE THREAD

**Issue by hgy59** [domoticz/domoticz#4859]
There are source packages available to download official releases.

But building from such source gives the following output:
```
fatal: not a git repository: './.git'
-- Failed to get ProjectRevision from History.txt, set it to 0
fatal: not a git repository: './.git'
-- Failed to get ProjectHash from git, set it to 0
fatal: not a git repository: './.git'
-- Failed to get ProjectDate from git, set it to 0
fatal: not a git repository: './.git'
```

This results in wrong version informations for the domoticz binary:
```
# ./domoticz --version
2021-06-11 01:25:24.243  Status: Domoticz V2020.2 (c)2012-1970 GizMoCuz
2021-06-11 01:25:24.243  Status: Build Hash: 0, Date: 1970-01-01 01:00:00
2021-06-11 01:25:24.243  Status: Startup Path: /volume1/@appstore/domoticz/bin/
```

It is obvous that building from downloaded sourc is outside a git repository.
I am used that official releases provide official version information. What am I missing? Any hint would be appreciated.

_As some might guess from the `Startup Path` shown above, I am about to build an updated domoticz package for synocommunity to install on synology nas devices._

**Comment by gizmocuz** [comment]
You have to follow this guide:

https://www.domoticz.com/wiki/Build_Domoticz_from_source

**Comment by hgy59** [comment]
@gizmocuz thanks for the link. So you don't support the build from source package, but only form git repository.

**Comment by kiddigital** [comment]
> @gizmocuz thanks for the link. So you don't support the build from source package, but only form git repository.

@hgy59 , why do you ask? What is the reason to want to use the sourcepackage (zip) instead of the git repo? Both have to be compiled anyway.

**Comment by hgy59** [comment]
To build packages for Synoclogy NAS Devices with https://github.com/SynoCommunity/spksrc we do not want to clone and checkout github repositories to build packages. We prefere the source releases.
It is a matter of size too (the domoticz repository currently is about 260 MB, the source is 13.9MB only (Version 2020.2, both compressed as tar.gz).

I'm currently migrating to use git repository to build domoticz, so the sizes above are my latest findings.

But I am disapointed again.
Despite the cloned repository is used without any changes, the About screen of domoticz shows `-modified` as build hash:
```
Version: 2020.2
Build Hash: aad65002e-modified
Compile Date: 2020-04-26 15:49:25
dzVents Version: 3.0.2
```

When I run `git --git-dir ./.git diff-index -m --name-only HEAD` in the domoticz repo, I get no output, i.e. there are no local changes.
So I think the `Gitversion_CHECK_DIRTY` in `getgit.cmake` does not work as expected.

I don't know for what reason the `appversion.default` (fallback without git repo?) was removed, but such a default would avoid a lot of troubles for building domoticz from source.

**Comment by waltervl** [comment]
No action here. Closing this
