### ISSUE TITLE
Accurite 5n1 wind sensor is not corretly detected by RTL_433

### ISSUE THREAD

**Issue by opechunka** [domoticz/domoticz#4864]
Accurite 5n1 sends two kind on messages. The first one includes wind speed and temperature, the sesond one - wind speed and wind direction.  The messages are sent alternately

1. {"time" : "2021-06-21 15:28:41", "model" : "Acurite-5n1", "message_type" : 56, "id" : 115, "channel" : "A", "sequence_num" : 0, "battery_ok" : 1, "wind_avg_km_h" : 8.450, "temperature_F" : 62.800, "humidity" : 86, "mic" : "CHECKSUM"}

2. {"time" : "2021-06-21 15:28:22", "model" : "Acurite-5n1", "message_type" : 49, "id" : 115, "channel" : "A", "sequence_num" : 0, "battery_ok" : 1, "wind_avg_km_h" : 6.795, "wind_dir_deg" : 157.500, "rain_in" : 6.700, "mic" : "CHECKSUM"}

For the first one domoticz assigns subtype#define sTypeWIND4 0x4   //TFA
For the second one subtype is  #define sTypeWINDNoTempNoChill 0x31 // Weather Station

Because of the above, domoticz creates two wind sensors. Then the one is updated with one message, the other one is updated with the other message. That is inconsystent. There should be just one sensor updated by both types of messages. 

I think it makes sense start looking with the next code:

void CDomoticzHardwareBase::SendWind(const int NodeID, const int BatteryLevel, const int WindDir, const float WindSpeed, const float WindGust, const float WindTemp, const float WindChill, const bool bHaveWindTemp, const bool bHaveWindChill, const std::string& defaultname, const int RssiLevel /* =12 */)
{
	RBUF tsen;
	memset(&tsen, 0, sizeof(RBUF));
	tsen.WIND.packetlength = sizeof(tsen.WIND) - 1;
	tsen.WIND.packettype = pTypeWIND;

	if ((!bHaveWindTemp) && (!bHaveWindChill))
		tsen.WIND.subtype = sTypeWINDNoTempNoChill;
	else if (!bHaveWindTemp)
		tsen.WIND.subtype = sTypeWINDNoTemp;
	else
		tsen.WIND.subtype = sTypeWIND4;

**Comment by xztraz** [comment]
accurite 5in1  works well with a rflink so maybe the code from that section can be reused.

I get theese sensors. only thing missing is gust calculations since wind speed is only current speed from sensor
![image](https://user-images.githubusercontent.com/25690871/125209786-9c003680-e29b-11eb-9693-690d67f1aced.png)

**Comment by opechunka** [comment]
> accurite 5in1 works well with a rflink so maybe the code from that section can be reused.

probably rflink manages and splits those accurite messages intenally. So domoticz recives  Temperature and  Wind with direction as separate messages.  By the way, RFLink wind direction is translated not correctly. 
Rtl_433 sends as it recives from accurite. One message with wind and temperature, the next with wind and direction. And direction is correct.

**Comment by xztraz** [comment]
> probably rflink manages and splits those accurite messages intenally. So domoticz recives Temperature and Wind with direction as separate messages. By the way, RFLink wind direction is translated not correctly. Rtl_433 sends as it recives from accurite. One message with wind and temperature, the next with wind and direction. And direction is correct.

This is how the serial comes in from rflink: (2 different packets)

20;F2;Acurite;ID=824f;WINSP=0043;WINDIR=0001;RAIN=3804;BAT=LOW;
....
20;F3;Acurite;ID=824f;TEMP=8034;HUM=99;WINSP=002b;BAT=LOW;

Here is the reverse engineering that i did for the accurite (wind dir pattern is weird from sensor and is decoded correctly by rflink
[all_acurite_debug2.pdf](https://github.com/domoticz/domoticz/files/7641270/all_acurite_debug2.pdf)

we where fighting with domoticz resetting the wind direction every other packet. but the rflinkguy solved it in domoticz so please take  a look at the code there :)

**Comment by xztraz** [comment]
And here is a script to get average and gust data from the accurite (that only gives current wind)
```
return {
	on = { 
	    devices = {'$WindSensor'} --trigger on your wind meter
	},
	data = {
	    windGust = { history = true, maxItems = 30, maxMinutes = 10 }
	},
	
	execute = function(domoticz, device)
		if (device.isDevice) then
		    local windDummy = domoticz.devices("Wind")	--create a dummy device wind with temp and chill and enter name here
		    local tempDevice = domoticz.devices("Outdoor Temp")	--your temperature meter 
		    local windDevice = domoticz.devices("$WindSensor")	--your wind meter
		    
		    domoticz.data.windGust.add(windDevice.speed)		--saves data for history calculations

		    --make some local variables
		    local windAVG = domoticz.utils.round(domoticz.data.windGust.avgSince('00:10:00'),2) --get average wind value from history
		    local windMAX = domoticz.utils.round(domoticz.data.windGust.maxSince('00:10:00'),2)	--get max wind from history
		    local temp = domoticz.utils.round(tempDevice.temperature,2)	--round of and get temperature 

		    local windChill = temp
		    
		    --Calculate wind chill if wind an temp range is ok
		    if ((temp < 10.0) and (windDevice.speed >= 1.4)) then
                        --wind chill calculation
                        windChill = domoticz.utils.round( 13.12 + 0.6215*temp - 11.37*math.pow( windAVG*3.6 , 0.16) + 0.3965*temp*math.pow( windAVG*3.6, 0.16),1) 
                    end

                    windDummy.updateWind(windDevice.direction, windDevice.directionString, windAVG, windMAX, temp, windChill) --save data to dummy sensor

                	--log selection
			--domoticz.log('Device ' .. device.name .. ' was changed', domoticz.LOG_INFO)
	    		--domoticz.log('Speed ' .. windAVG .. ' m/s', domoticz.LOG_INFO)
	    		--domoticz.log('Gust  ' .. windMAX .. ' m/s' , domoticz.LOG_INFO)
	    		--domoticz.log('Dir   ' .. windDevice.direction , domoticz.LOG_INFO)
	    		--domoticz.log('Temp  ' .. temp .. ' c' , domoticz.LOG_INFO)	    	
	    		--domoticz.log('Chill ' .. windChill .. ' c', domoticz.LOG_INFO)

		end
	end
}```

**Comment by gizmocuz** [comment]
Seems to me that RTL_433 should send a combined message that contains all fields instead of splitting it into two messages ?

**Comment by opechunka** [comment]
> Seems to me that RTL_433 should send a combined message that contains all fields instead of splitting it into two messages ?

Why RTL 433 should combine the two messages? RTL_433 just receives the radio message and translates to some text (or other) format, which is read via USB. And as Acurite sends two different radio messages one ofter the other, we get two different messages from RTL_433. 
And yes, RFLink combines them (don't remember the datails). But from my undestanding RFLink is kind of smarter device. But RTL_433 is kind of radio to USB gateway.

**Comment by gizmocuz** [comment]
Why? Because a gateway should provide all the details of a sensor and it should not be up to the final application to do (wierd) cross checking and doing that.
So yes, the RFLink gateway does a good job with that.
Of course when these two messages are received 30 seconds from each other, I blame the wind sensor in the first place.
But as RTL_433 is software (SDR) it could combine it without much trouble.
