### ISSUE TITLE
domoticz on synology

### ISSUE THREAD

**Issue by vespino** [domoticz/domoticz#4865]
I'm running domoticz in [Docker](https://hub.docker.com/r/domoticz/domoticz/) on my Synology NAS and when hitting the settings button, I'm getting an error saying this has failed. Any support on this?

![afbeelding](https://user-images.githubusercontent.com/6991325/122906479-7e057d00-d352-11eb-9a18-f669ff6f01b4.png)

It seems to cause the container to restart.

I'm also looking for a way to run PHP scripts that are on my NAS.

**Comment by waltervl** [comment]
Please, Use the forum for this as this GitHub issues is for changes on Domoticz source code.

**Comment by vespino** [comment]
Ok, then please note the error on saving the settings, apparently I’m not the only one: https://www.domoticz.com/forum/viewtopic.php?f=47&t=35639&p=276602#p276602
