### ISSUE TITLE
Barometr Pressure is not adjusted per Settings parametr

### ISSUE THREAD

**Issue by Scoperius** [domoticz/domoticz#4866]
You have to adjust your Pressure based on your current altitude. I expect that it can be adjusted on card "Edit device" item "Adjustment" which works fine for Temperature sensors. Unfortunately value placed there has no impact on displayed Pressure. 

![image](https://user-images.githubusercontent.com/86469550/123405992-b606fd00-d5aa-11eb-8ede-0b392626a637.png)

**Comment by gizmocuz** [comment]
It could depend on the type of hardware you are using and if this is using the standard way to report the pressure, or if it is storing this directly in the database. It should work

**Comment by waltervl** [comment]
This is an issue with Python plugins. Nowadays the python plugins can make the adjustment. See for example: https://github.com/domoticz/domoticz/pull/2899
https://domoticz.com/forum/viewtopic.php?t=26860
https://www.domoticz.com/forum/viewtopic.php?t=25853

**Comment by waltervl** [comment]
@Scoperius please close this issue if no further action/info is needed.
