### ISSUE TITLE
Custom menu not exist? 

### ISSUE THREAD

**Issue by Scoperius** [domoticz/domoticz#4867]
version: 2021.1 build 13330

Even custom menu is enabled there is no such available. 

![image](https://user-images.githubusercontent.com/86469550/123557721-d85b6f00-d792-11eb-8432-f392ba9bf82c.png)

![image](https://user-images.githubusercontent.com/86469550/123557732-e5785e00-d792-11eb-8506-a6e49ecc16e7.png)

**Comment by gizmocuz** [comment]
@Scoperius , do you have html files inside the templates folder ?

**Comment by Scoperius** [comment]
Thanks to pointing me right way...

**Comment by waltervl** [comment]
I have seen only custom menu's made by Python plugins but there could be of course other ways to create those. https://www.domoticz.com/wiki/Developing_a_Python_plugin#Setup_custom_page_within_plugin
Normally the www/template folder is empty except for the example.

**Comment by waltervl** [comment]
Wiki updated: https://www.domoticz.com/wiki/Application_Settings#Active_Menus

**Comment by waltervl** [comment]
@Scoperius please close this issue if no further action/info is needed.

**Comment by Scoperius** [comment]
Ok thanks, Petr
