### ISSUE TITLE
Blocky Set x after y seconds logic actives after y/2 seconds

### ISSUE THREAD

**Issue by arjanwaard** [domoticz/domoticz#487]
Using this logic block on OS X the actual duration is half of the configured y duration. For example setting the seconds to 1800 results in an action in 900 seconds

**Comment by gizmocuz** [comment]
Thats very odd, did you overclock the system?

```
while (!m_stoprequested)
{
    //sleep 1 second
    sleep_seconds(1);
```

void sleep_seconds(const long seconds)
{
#if (BOOST_VERSION < 105000)
    boost::this_thread::sleep(boost::posix_time::seconds(seconds));
#else
    boost::this_thread::sleep_for(boost::chrono::seconds(seconds));
#endif
}

**Comment by arjanwaard** [comment]
No, it is a standard mac mini core2duo with El Capitan.

**Comment by arjanwaard** [comment]
Seconds times 2 as workaround

**Comment by gizmocuz** [comment]
Well yes, but not such a good one
would be nice if other people can confirm if it works correctly or not

**Comment by arjanwaard** [comment]
No problem, I'll leave the issue open.

**Comment by gizmocuz** [comment]
Could this be the same issue ?
https://www.domoticz.com/forum/viewtopic.php?f=6&t=10609

**Comment by arjanwaard** [comment]
It probably is, after I restarted it seems like the issue went away.

**Comment by gizmocuz** [comment]
Tested under windows...
If switch = on, then set switch off after 10 seconds

it is switches of after 10 seconds

**Comment by arjanwaard** [comment]
Did the same test on OS X and before the restart it switched off in half the set amount. After restart it is working normally.

**Comment by gizmocuz** [comment]
After restart of ? Domoticz ? So the first time its ok, and then not ?

**Comment by arjanwaard** [comment]
No, before restart of domoticz the problem was present. After restart it was gone.

**Comment by gizmocuz** [comment]
? Is the problem still there ? When you now restart again, is the problem still there ?
Else we will close this topic as solved

**Comment by arjanwaard** [comment]
After new restarts the problem did not show up again, so closing this issue is ok.

**Comment by gizmocuz** [comment]
Thanks for the feedback, so it happend one time only ?
