### ISSUE TITLE
Color Status Update is one event behind

### ISSUE THREAD

**Issue by StephaneM60** [domoticz/domoticz#4871]
When color (RGB or White) is changed through the Domoticz UI the status of the update is not passed on immediately but instead after the next event on the device (for instance switch on)

This is a huge problem as for scripting if you ask for the color of a device, it will return the last color of the device before the last event.

In the logs you can see the change color event

2021-07-06 16:26:20.222 Status: setcolbrightnessvalue: ID: 6f5, bri: 100, color: '{m: 3, RGB: fff90f, CWWW: 0000, CT: 0}'

But if you were to do a getColor() in DZVents for instance with a "Device" event with a "Set Color" status, you will never get the FFF90F value.

Even if you were to check 10 seconds after the event takes place, it would still return the old color.

To get the actual applied color of the device, you need to "refresh" the domoticz database by doing something on the device, for instance switching it on, or changing its brightness level.

So for instance in DZVents for every device event with "Set Color" you can issue a "switchOn()" or a "setLevel()" and after this you can in any other script query the color of the device and get the real applied color of the device.

The workaround is sort of working but the extraneous "On" or "Level" command is sometime unwanted, for instance for some reason when you turn off some Philips Hue device, the Hue Hub send a "Set Color" just before "Off" : as a result the device stays "On" (because the "Set Color" issue an extra switchOn that will be executed after the Off.

So it would be nice that the color status reflects at anytime the real color applied on a device.

Also I noticed in the device history that each event is associated with the user that initiated the event : is this information available throught DZVents (or any other scripting method) as it would indeed solve the issue I exposed.

Note : I noticed this because I'm currently writing a script to allow restoring the state of a device. For instance all lights are blue, then with a motion sensor you turn them to bright white, and after the motion you restore the lights to the previous state that is blue. I'm doing this because the native ForSec(XX) only restore the on/off status but nothing else.

**Comment by waltervl** [comment]
On what build are you running?
What happens if you query the status of the device with a http json call? https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Retrieve_status_of_specific_device
This to decide if it is a Domoticz issue or a dzVents issue.

**Comment by StephaneM60** [comment]
I'm running the latest stable : Version 2021.1 (April 17 2021)

This is a domoticz issue, I already tried to get the status with JSON API and it is one event behind. I repeted the test just now : 

2021-07-07 11:39:57.109 Status: setcolbrightnessvalue: ID: 6f5, bri: 100, color: '{m: 3, RGB: **06ff15**, CWWW: 0000, CT: 0}'

2021-07-07 11:39:58.453 Status: dzVents: !Info: SCRIPT #1 : ["Color"]="{"b":45,"cw":0,"g":0,"m":3,**"r":254**,"t":0,"ww":0}"} (this is from the http callback response made after receving device update notification in dzvetns with a 'Set Color' state, for the URI /json.htm?type=devices&rid=xxxx

**Comment by waltervl** [comment]
What if you set color status by json and get status by json?

**Comment by StephaneM60** [comment]
I'm not sur this a useful test : the idea is to query for the color of a device at any moment. So right after a color change whatever the source of the color change is (by script, by scene, by the device itself or its companion app)

In the previous test, the color change was done through domoticz web interface directly on the device (with the color picker). 

However I made the test : by using dzvents setColor, then upon the "Set Color" event, querying the JSON API I get the correct color (dzvent getColor returns the wrong one)

2021-07-07 12:46:25.197 Status: setcolbrightnessvalue: ID: 6f5, bri: 100, color: '{m: 2, RGB: ff0000, CWWW: 0000, CT: 0}'

2021-07-07 12:58:57.433 Status: dzVents: !Info: SCRIPT #1: {["green"]=0, ["blue"]=0, ["saturation"]=0.0, ["brightness"]=0.0, ["r"]=0, ["red"]=0, ["cw"]=191, ["br"]=100, ["value"]=0.0, ["g"]=0, ["isWhite"]=true, ["m"]=2, ["temperature"]=64, ["hue"]=300, ["cold white"]=191, ["warm white"]=64, ["b"]=0, ["t"]=64, ["ww"]=64, ["mode"]=2} **_<= DZVENTS GETCOLOR_**

2021-07-07 12:46:25.791 Status: dzVents: !Info: SCRIPT #1: ["Color"]="{"b":0,"cw":0,"g":0,"m":2,"r":255,"t":0,"ww":0}" **_<= JSON API_**

Another test : I change the color on the Hue Essentials App, I get the right color with the JSON API and the wrong color with DZVENTS (I use hue essentials because it allow a single event to be fired)

Another test : I change the color of the bulb with a scene : incorrect color with DZVENTS and correct color with JSON API.

Though my test are for a bulb on a hue bridge that is not working correctly with domoticz (only works with white, and color is not working correctly, this bulb requires that the hue color is set with the x,y parameters and not the hue / sat etc.. so it may not reflect all devices / situation regarding color change

So this is mainly a DZVENTS issued, and also a Domoticz issue (with the color picker only)

**Comment by waltervl** [comment]
Backbone of Domoticz is the Json API. So if that works, Domoticz works ;-)
All other things could be around this influencing your environment: The Hue hardware plugin, dzVents, Web User interface (javascript) etc. So it is hard to determin what is going wrong exactly.
The main dzVents maintainer (waaren) is currently not available due to personal health issues so if the source of your issue is dzVents it can take some time to solve. I do not think the current beta will solve your issue but you could give it a try (on a test system).

**Comment by waltervl** [comment]
https://domoticz.com/forum/viewtopic.php?f=59&t=36174&p=274076&hilit=getColor#p274076
this seems to be the same issue

**Comment by StephaneM60** [comment]
Yes I already found multiple topics on the forum about this when I stumble upon this issue. This is where I learned that either using the JSON API or forcing an update with a .switchOn() could solve the issue.

I tried both but the JSON API fails with the color picker, and the .switchOn() (or .setLeve()) is not without problems.

I also checked if this is something that only happens with some lights and not others. So I tried Milight and Tuya lights. And it seems that the JSON API here works with them, so it's only with the Hue bulb I'm seeing this (the non working one)

Can you confirm that when we see this Status: setcolbrightnessvalue: ID: 6f5, bri: 100, color: '{m: 3, RGB: 06ff15, CWWW: 0000, CT: 0}' in the logs : it means that domoticz will store the status correctly ?

**Comment by waltervl** [comment]
> Can you confirm that when we see this Status: setcolbrightnessvalue: ID: 6f5, bri: 100, color: '{m: 3, RGB: 06ff15, CWWW: 0000, > CT: 0}' in the logs : it means that domoticz will store the status correctly ?

No, As I do not know where it is coming from. Hue Hardware plugin?
Then probably it will work. If the integration is done by Python, MQTT or scripts not using JSON API calls it is doubtfull.
But you can check/test with the IP:port/json.htm?type=devices&rid=IDX

**Comment by StephaneM60** [comment]
It's coming from domoticz itself I suppose, as I'm seeing this for any kind of color bulbs, whenever I use the color picker in domoticz, or genrally when the color change.

If Domoticz is itself setting the color on a bulb (whatever hardware it is), I suppose that there is a code path that is the same for all bulb and that code path is setting / handling the values used bu domoticz to store the status of the device : state / brightness... then there is multiple different code path / plugin to actually talk to the hardware.

Anyway I'm currently trying to use the JSON API to get the light status to see if it works in all situations (though I will have to make sure to make a synchronous HTTP request to be sure to get the **current** status and not the **next** status. As my goal is to capture the status, then updating the bulb color / state, and later on restore its stored status. Exactly what would do a "FOR XX"

By the way, is it in the plans to make the "FOR XX" work for anything else that "On / Off", as if I understand correctly this is a core domoticz feature (and not a dzvents one)

**Comment by StephaneM60** [comment]
Update : I have now used the JSON API to get the color and sometimes it works, sometimes it doesn't... When it doesn't work the JSON API isn't updating the device status anymore until it starts to work again.

Though I noticed that the history log for the device I'm using for test isn't working anymore, so I may have stressed the domoticz process.

**Comment by vincems** [comment]
In case it's of interest and significant, even virtual switch causes the same issue. The setcolbrightnessvalue comes through correctly in the log, but within the dzevent it is behind by one change.

if one looks at the device data handed to the dzevent script it is time stamped with the previous event. 

In my test:
2021-10-05 13:37:09.109 Status: setcolbrightnessvalue: ID 5... RGB: ff0002

But in the event data structure:

["raw"]="2021-10-05 13:30:26"

This indicates the data is definitely for the previous event.

**Comment by ilexpl01** [comment]
Any update regarding this problem ? Got the same issue witch virtual RGB switch that is controlling the LED strip (based on WLED). To get the light change I have to touch twice the requested colour in domoticz GUI - ridiculous :/

**Comment by waltervl** [comment]
> Any update regarding this problem ? Got the same issue witch virtual RGB switch that is controlling the LED strip (based on WLED). To get the light change I have to touch twice the requested colour in domoticz GUI - ridiculous :/

That does not seems to be the same issue as previous users report that after 1 GUI touch the color changes but is not being able to be requested correctly by API or dzVents. So you have another issue. Please start with the forum to describe your issue. Important is how the connection is done between your LED strip and Domoticz (Python plugin, native integration, MQTT etc)

**Comment by ilexpl01** [comment]
Hi.

IMHO it is that issue.

Below part of my dzvents script:

_return {
	on = { devices = {'Choinka'}},
	logging = {level = domoticz.LOG_DEBUG, marker = 'Choinka',},

	execute = function(domoticz, item)
    
    local xxx = domoticz.devices('Choinka').lastLevel
            
	local wled = domoticz.devices('Choinka')
    local lampBefore = domoticz.devices('Choinka').getColor() -- get the current lamp colours
    local lux = domoticz.utils.round((wled.level*2.55),0)
    
    print ("Choinka jasność w %:         " .. wled.level)
    print ("Choinka jasność w skali 255: " .. lux)
    print ("Choinka typ zmiany:          " .. wled.state)
    print ("Choinka R: " .. lampBefore.r)
    print ("Choinka G: " .. lampBefore.g)
    print ("Choinka B: " .. lampBefore.b)
    
    print ("Choinka zmienna wled01.level: " .. tostring(domoticz.variables('wled01.level').value))
    print ("Choinka last update 2:        " .. wled.icon)
   
    if lux == 0 or wled.state == 'Off' then
        domoticz.openURL('http://wled01/win&T=0') -- wyłączenie
        domoticz.variables('wled01.level').set(0) -- zmiana wartości zmiennej na 0
        
    else
        runcommand = 'curl -X POST "http://wled01/json/state" -d \'{"bri":'..tostring(lux)..',"seg":[{"col":[['..lampBefore.r..','..lampBefore.g..','..lampBefore.b..']]}]}\' -H "Content-Type: application/json"'
        print("Runcommand " .. runcommand);
        
        os.execute(runcommand);
   
        domoticz.variables('wled01.level').set(lux) -- zmiana wartości zmiennej
    
    end
end
}_

With the first GUI touch I see in logs:

![image](https://user-images.githubusercontent.com/67930801/147254234-e7d5bf6a-4506-46f5-b44b-2206423782e8.png)

I touched the green part of GUI (see setcolorbrightnessvalue result) while getColor() function returned 255/65/55 (#FF4137) which was previuos setting.

I hope I make myself clear.

**Comment by waltervl** [comment]
Yes, you have the same issue it seems. So hopefully a developer can look into this. As it is seems a core Domoticz issue we need somebody knowledgeable.

**Comment by waltervl** [comment]
This is how late waaren solved it...

```
--[[ LEDSlaveDemo.lua (tested and working on dzVents 2.4.6) but probably also working on earlier versions
  ]]--
 
return {
    on = { devices = {"LED_strip1" } },
    
    logging =   {       level   =   domoticz.LOG_DEBUG,                  -- switch to LOG_INFO when results are OK 
                        marker  =   "LEDSlaveDemo" },                                           

    data    =   {      setColor         = { initial = true },           -- This is necessary because color does not follow in the first pass
                       dimLevel         = { initial = 50   }, 
                       color            = { initial = {}   }}, 
                       
    execute = function(dz, trigger)
        local slave   = dz.devices("LED_strip2")
        
        dz.log("Master ( name / state / level / color )  ( " .. 
                        trigger.name .. " / " .. 
                        trigger.state .. " / " .. 
                        trigger.level .. " / " .. 
                        trigger.color .. " )",dz.LOG_DEBUG)
        
        colorTable = dz.utils.fromJSON(trigger.color)                       -- convert color (a json string) to a Lua table
        
        if trigger.state ~= "Off" and trigger.level > 0 then                -- State can be "On", "Off" or "set Color" 
            dz.data.dimLevel =  trigger.level
            dz.data.color    =  trigger.color
            slave.setRGB(  colorTable.r, colorTable.g, colorTable.b )  
            slave.dimTo(tonumber(dz.data.dimLevel))
            if dz.data.setColor then                                        -- We need to trigger the script another time as the color 
                dz.data.dimLevel =  trigger.level                           -- does not follow the first pass. Does not seem timing but looks like    
                trigger.dimTo(dz.data.dimLevel)                             -- dzVents is not yet updated with right color values from master
                dz.data.setColor = false                                  
            else
                dz.data.setColor = true
            end 
        else
            slave.switchOff()
        end
    end
}
```
