### ISSUE TITLE
Kodi wrong years in logs...

### ISSUE THREAD

**Issue by devrosx** [domoticz/domoticz#4873]
Hello,
noticed when i was writing script for scraping my logs that in Kodi device log is at end Movie for some reason year (in round brackets). But in almost in all logs is year wrong (dunno why). Can we remove that unnecessary function (just movie name) is enough imho... 

looks like its line 80 in Kodi.cpp

**Comment by waltervl** [comment]
Perhaps try the Kodi Python plugin https://domoticz.com/forum/viewtopic.php?f=65&t=15892
