### ISSUE TITLE
General KWh Computed value is wrong when value is low

### ISSUE THREAD

**Issue by mangoose002** [domoticz/domoticz#4878]
Hi all,

I am facing an issue with 'General KWh' computed energy, the calulcation seems to be wrong as visible in the following image.
![image](https://user-images.githubusercontent.com/5635922/126453037-f443f220-bcd1-4950-b470-5c881eba4a12.png)

Between 8 and 10, the instant value is never below 1.5, but the cumulative value is 1, which seems to be wrong.
Is it the normal behaviour or is there something wrong (that is what I think).

What kind of information do you need to investigate this, if it is not normal.

Regards

**Comment by mangoose002** [comment]
Here are the values in the database:
select * from Meter where DeviceRowID=2290 and date >= '2021-07-19' and date <= '2021-07-20';
2290|3315|0|2021-07-19 00:00:00
2290|3315|0|2021-07-19 00:05:00
2290|3315|0|2021-07-19 00:10:00
2290|3315|0|2021-07-19 00:15:00
2290|3315|0|2021-07-19 00:20:00
2290|3315|0|2021-07-19 00:25:00
2290|3315|0|2021-07-19 00:30:00
2290|3315|0|2021-07-19 00:35:00
2290|3315|0|2021-07-19 00:40:00
2290|3315|0|2021-07-19 00:45:00
2290|3315|0|2021-07-19 00:50:00
2290|3315|0|2021-07-19 00:55:00
2290|3315|0|2021-07-19 01:00:00
2290|3315|0|2021-07-19 01:05:00
2290|3315|0|2021-07-19 01:10:00
2290|3315|0|2021-07-19 01:15:01
2290|3315|0|2021-07-19 01:20:00
2290|3315|0|2021-07-19 01:25:00
2290|3315|0|2021-07-19 01:30:00
2290|3315|0|2021-07-19 01:35:00
2290|3315|0|2021-07-19 01:40:00
2290|3315|0|2021-07-19 01:45:00
2290|3315|0|2021-07-19 01:50:00
2290|3315|0|2021-07-19 01:55:00
2290|3315|0|2021-07-19 02:00:00
2290|3315|0|2021-07-19 02:05:00
2290|3315|0|2021-07-19 02:10:00
2290|3315|0|2021-07-19 02:15:00
2290|3315|0|2021-07-19 02:20:00
2290|3315|0|2021-07-19 02:25:00
2290|3315|0|2021-07-19 02:30:00
2290|3315|0|2021-07-19 02:35:00
2290|3315|0|2021-07-19 02:40:00
2290|3315|0|2021-07-19 02:45:00
2290|3315|0|2021-07-19 02:50:00
2290|3315|0|2021-07-19 02:55:00
2290|3315|0|2021-07-19 03:00:00
2290|3315|0|2021-07-19 03:05:00
2290|3315|0|2021-07-19 03:10:00
2290|3315|0|2021-07-19 03:15:00
2290|3315|0|2021-07-19 03:20:00
2290|3315|0|2021-07-19 03:25:00
2290|3315|0|2021-07-19 03:30:00
2290|3315|0|2021-07-19 03:35:00
2290|3315|0|2021-07-19 03:40:00
2290|3315|0|2021-07-19 03:45:00
2290|3315|0|2021-07-19 03:50:00
2290|3315|0|2021-07-19 03:55:00
2290|3315|0|2021-07-19 04:00:00
2290|3315|0|2021-07-19 04:05:00
2290|3315|0|2021-07-19 04:10:00
2290|3315|0|2021-07-19 04:15:00
2290|3315|0|2021-07-19 04:20:00
2290|3315|0|2021-07-19 04:25:00
2290|3315|0|2021-07-19 04:30:01
2290|3315|0|2021-07-19 04:35:00
2290|3315|0|2021-07-19 04:40:00
2290|3315|0|2021-07-19 04:45:00
2290|3315|0|2021-07-19 04:50:00
2290|3315|0|2021-07-19 04:55:00
2290|3315|0|2021-07-19 05:00:00
2290|3315|0|2021-07-19 05:05:00
2290|3315|0|2021-07-19 05:10:00
2290|3315|0|2021-07-19 05:15:00
2290|3315|0|2021-07-19 05:20:00
2290|3315|0|2021-07-19 05:25:00
2290|3315|0|2021-07-19 05:30:00
2290|3315|0|2021-07-19 05:35:00
2290|3315|0|2021-07-19 05:40:00
2290|3315|0|2021-07-19 05:45:00
2290|3315|0|2021-07-19 05:50:00
2290|3315|0|2021-07-19 05:55:00
2290|3315|0|2021-07-19 06:00:00
2290|3315|0|2021-07-19 06:05:00
2290|3315|0|2021-07-19 06:10:00
2290|3315|0|2021-07-19 06:15:00
2290|3315|0|2021-07-19 06:20:00
2290|3315|3|2021-07-19 06:25:00
2290|3315|3|2021-07-19 06:30:00
2290|3315|4|2021-07-19 06:35:00
2290|3315|5|2021-07-19 06:40:00
2290|3315|6|2021-07-19 06:45:00
2290|3315|7|2021-07-19 06:50:00
2290|3315|9|2021-07-19 06:55:00
2290|3315|11|2021-07-19 07:00:00
2290|3315|12|2021-07-19 07:05:00
2290|3315|14|2021-07-19 07:10:00
2290|3315|14|2021-07-19 07:15:00
2290|3316|19|2021-07-19 07:20:00
2290|3316|20|2021-07-19 07:25:00
2290|3316|22|2021-07-19 07:30:00
2290|3316|24|2021-07-19 07:35:00
2290|3316|25|2021-07-19 07:40:00
2290|3316|26|2021-07-19 07:45:00
2290|3316|26|2021-07-19 07:50:00
2290|3316|26|2021-07-19 07:55:00
2290|3316|26|2021-07-19 08:00:00
2290|3316|25|2021-07-19 08:05:00
2290|3317|24|2021-07-19 08:10:00
2290|3317|23|2021-07-19 08:15:00
2290|3317|20|2021-07-19 08:20:00
2290|3317|19|2021-07-19 08:25:00
2290|3317|20|2021-07-19 08:30:00
2290|3317|20|2021-07-19 08:35:00
2290|3317|20|2021-07-19 08:40:00
2290|3317|20|2021-07-19 08:45:00
2290|3317|20|2021-07-19 08:50:00
2290|3317|20|2021-07-19 08:55:00
2290|3317|18|2021-07-19 09:00:00
2290|3317|20|2021-07-19 09:05:01
2290|3317|19|2021-07-19 09:10:00
2290|3317|20|2021-07-19 09:15:00
2290|3318|20|2021-07-19 09:20:00
2290|3318|19|2021-07-19 09:25:00
2290|3318|19|2021-07-19 09:30:00
2290|3318|20|2021-07-19 09:35:00
2290|3318|19|2021-07-19 09:40:00
2290|3318|20|2021-07-19 09:45:00
2290|3318|20|2021-07-19 09:50:00
2290|3318|20|2021-07-19 09:55:00
2290|3318|22|2021-07-19 10:00:00
2290|3318|22|2021-07-19 10:05:00
2290|3318|24|2021-07-19 10:10:00
2290|3318|24|2021-07-19 10:15:00
2290|3318|24|2021-07-19 10:20:00
2290|3318|27|2021-07-19 10:25:00
2290|3318|27|2021-07-19 10:30:00
2290|3319|29|2021-07-19 10:35:00
2290|3319|30|2021-07-19 10:40:00
2290|3319|32|2021-07-19 10:45:00
2290|3319|35|2021-07-19 10:50:00
2290|3319|36|2021-07-19 10:55:00
2290|3320|41|2021-07-19 11:00:00
2290|3320|43|2021-07-19 11:05:00
2290|3320|47|2021-07-19 11:10:00
2290|3321|52|2021-07-19 11:15:00
2290|3321|54|2021-07-19 11:20:00
2290|3322|55|2021-07-19 11:25:00
2290|3322|54|2021-07-19 11:30:00
2290|3322|55|2021-07-19 11:35:00
2290|3323|57|2021-07-19 11:40:00
2290|3323|59|2021-07-19 11:45:00
2290|3324|62|2021-07-19 11:50:00
2290|3325|65|2021-07-19 11:55:00
2290|3325|65|2021-07-19 12:00:00
2290|3326|67|2021-07-19 12:05:00
2290|3326|72|2021-07-19 12:10:00
2290|3327|73|2021-07-19 12:15:00
2290|3328|77|2021-07-19 12:20:00
2290|3328|80|2021-07-19 12:25:00
2290|3329|85|2021-07-19 12:30:00
2290|3330|92|2021-07-19 12:35:00
2290|3331|102|2021-07-19 12:40:00
2290|3331|79|2021-07-19 12:45:00
2290|3332|31|2021-07-19 12:50:00
2290|3332|45|2021-07-19 12:55:00
2290|3332|63|2021-07-19 13:00:00
2290|3333|95|2021-07-19 13:05:00
2290|3334|54|2021-07-19 13:10:00
2290|3334|62|2021-07-19 13:15:00
2290|3336|150|2021-07-19 13:20:00
2290|3337|153|2021-07-19 13:25:00
2290|3338|88|2021-07-19 13:30:00
2290|3339|42|2021-07-19 13:35:00
2290|3340|80|2021-07-19 13:40:00
2290|3340|160|2021-07-19 13:45:00
2290|3342|42|2021-07-19 13:50:00
2290|3342|0|2021-07-19 13:55:00
2290|3343|123|2021-07-19 14:00:00
2290|3344|163|2021-07-19 14:05:00
2290|3345|43|2021-07-19 14:10:00
2290|3345|43|2021-07-19 14:15:00
2290|3346|124|2021-07-19 14:20:01
2290|3347|165|2021-07-19 14:25:00
2290|3348|160|2021-07-19 14:30:00
2290|3348|122|2021-07-19 14:35:00
2290|3349|42|2021-07-19 14:40:01
2290|3350|38|2021-07-19 14:45:00
2290|3350|157|2021-07-19 14:50:00
2290|3351|74|2021-07-19 14:55:00
2290|3352|109|2021-07-19 15:00:00
2290|3352|73|2021-07-19 15:05:00
2290|3354|82|2021-07-19 15:10:01
2290|3354|42|2021-07-19 15:15:00
2290|3354|41|2021-07-19 15:20:00
2290|3355|40|2021-07-19 15:25:00
2290|3355|0|2021-07-19 15:30:00
2290|3356|40|2021-07-19 15:35:00
2290|3356|83|2021-07-19 15:40:00
2290|3356|0|2021-07-19 15:45:00
2290|3356|77|2021-07-19 15:50:00
2290|3357|0|2021-07-19 15:55:00
2290|3357|0|2021-07-19 16:00:00
2290|3357|40|2021-07-19 16:05:00
2290|3357|50|2021-07-19 16:10:00
2290|3358|41|2021-07-19 16:15:00
2290|3358|0|2021-07-19 16:20:00
2290|3358|0|2021-07-19 16:25:00
2290|3358|110|2021-07-19 16:30:00
2290|3358|0|2021-07-19 16:35:00
2290|3359|37|2021-07-19 16:40:00
2290|3359|0|2021-07-19 16:45:00
2290|3359|10|2021-07-19 16:50:00
2290|3359|47|2021-07-19 16:55:00
2290|3359|73|2021-07-19 17:00:00
2290|3360|0|2021-07-19 17:05:00
2290|3360|62|2021-07-19 17:10:00
2290|3360|35|2021-07-19 17:15:00
2290|3360|36|2021-07-19 17:20:00
2290|3361|0|2021-07-19 17:25:00
2290|3361|36|2021-07-19 17:30:00
2290|3361|58|2021-07-19 17:35:00
2290|3361|18|2021-07-19 17:40:00
2290|3362|31|2021-07-19 17:45:00
2290|3362|54|2021-07-19 17:50:00
2290|3362|60|2021-07-19 17:55:00
2290|3362|12|2021-07-19 18:00:00
2290|3362|32|2021-07-19 18:05:00
2290|3362|22|2021-07-19 18:10:00
2290|3362|18|2021-07-19 18:15:01
2290|3362|30|2021-07-19 18:20:00
2290|3362|25|2021-07-19 18:25:00
2290|3362|28|2021-07-19 18:30:00
2290|3362|33|2021-07-19 18:35:00
2290|3362|18|2021-07-19 18:40:00
2290|3362|11|2021-07-19 18:45:00
2290|3362|19|2021-07-19 18:50:00
2290|3362|22|2021-07-19 18:55:00
2290|3362|15|2021-07-19 19:00:00
2290|3362|22|2021-07-19 19:05:00
2290|3362|9|2021-07-19 19:10:00
2290|3362|14|2021-07-19 19:15:00
2290|3362|18|2021-07-19 19:20:00
2290|3362|25|2021-07-19 19:25:00
2290|3362|24|2021-07-19 19:30:00
2290|3362|22|2021-07-19 19:35:00
2290|3362|21|2021-07-19 19:40:00
2290|3363|15|2021-07-19 19:45:00
2290|3363|16|2021-07-19 19:50:00
2290|3363|23|2021-07-19 19:55:00
2290|3363|28|2021-07-19 20:00:00
2290|3363|22|2021-07-19 20:05:00
2290|3363|22|2021-07-19 20:10:00
2290|3363|19|2021-07-19 20:15:00
2290|3363|13|2021-07-19 20:20:00
2290|3363|20|2021-07-19 20:25:00
2290|3363|20|2021-07-19 20:30:01
2290|3363|18|2021-07-19 20:35:00
2290|3363|19|2021-07-19 20:40:00
2290|3363|18|2021-07-19 20:45:00
2290|3363|16|2021-07-19 20:50:00
2290|3363|13|2021-07-19 20:55:00
2290|3363|12|2021-07-19 21:00:00
2290|3363|10|2021-07-19 21:05:00
2290|3363|8|2021-07-19 21:10:00
2290|3363|7|2021-07-19 21:15:00
2290|3363|4|2021-07-19 21:20:00
2290|3363|0|2021-07-19 21:25:00
2290|3363|0|2021-07-19 21:30:00
2290|3363|0|2021-07-19 21:35:00
2290|3363|0|2021-07-19 21:40:00
2290|3363|0|2021-07-19 21:45:00
2290|3363|0|2021-07-19 21:50:00
2290|3363|0|2021-07-19 21:55:00
2290|3363|0|2021-07-19 22:00:00
2290|3363|0|2021-07-19 22:05:00
2290|3363|0|2021-07-19 22:10:00
2290|3363|0|2021-07-19 22:15:00
2290|3363|0|2021-07-19 22:20:00
2290|3363|0|2021-07-19 22:25:00
2290|3363|0|2021-07-19 22:30:00
2290|3363|0|2021-07-19 22:35:00
2290|3363|0|2021-07-19 22:40:00
2290|3363|0|2021-07-19 22:45:00
2290|3363|0|2021-07-19 22:50:00
2290|3363|0|2021-07-19 22:55:00
2290|3363|0|2021-07-19 23:00:00
2290|3363|0|2021-07-19 23:05:00
2290|3363|0|2021-07-19 23:10:00
2290|3363|0|2021-07-19 23:15:00
2290|3363|0|2021-07-19 23:20:00
2290|3363|0|2021-07-19 23:25:00
2290|3363|0|2021-07-19 23:30:00
2290|3363|0|2021-07-19 23:35:00
2290|3363|0|2021-07-19 23:40:00
2290|3363|0|2021-07-19 23:45:00
2290|3363|0|2021-07-19 23:50:00
2290|3363|0|2021-07-19 23:55:00



Here is the config in Domoticz:
![image](https://user-images.githubusercontent.com/5635922/126461423-9aef5aec-e122-48ed-b719-30fa8f8bad9f.png)

**Comment by michahagg** [comment]
Hi @mangoose002 the wattage is too low for the Wh-counter to accurately keep track.

**Comment by mangoose002** [comment]
Hi,

What could be the type of counter I should used or do I need to multiply the result by 10 or 100 to make sure to keept track?

**Comment by waltervl** [comment]
Did you find a good divider setting for your environment?
