### ISSUE TITLE
Not able to parse json with Name: Children

### ISSUE THREAD

**Issue by AdamWeglarz** [domoticz/domoticz#4879]
Hi,

I am using domoticz stable 2020 and 2021 in two houses and in both I have the same issue.
I am trying to parse json
`
<{
	"id": 0,
	"Text": "Sensor",
	"Children": [{
		"id": 1,
		"Text": "DESKTOP-sss",
		"Children": [{
			"id": 2,
			"Text": "Dell 0K0DNP",
			"Children": [],
			"Min": "",
			"Value": "",
			"Max": "",
			"ImageURL": "images_icon/mainboard.png"
		}, {
			"id": 3,
			"Text": "Intel Core i7-2760QM",
			"Children": [{
				"id": 4,
				"Text": "Clocks",
				"Children": [{
					"id": 5,
					"Text": "Bus Speed",
					"Children": [],
					"Min": "99,8 MHz",
					"Value": "99,8 MHz",
					"Max": "99,8 MHz",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 6,
					"Text": "CPU Core #1",
					"Children": [],
					"Min": "798,1 MHz",
					"Value": "3093,0 MHz",
					"Max": "3492,2 MHz",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 7,
					"Text": "CPU Core #2",
					"Children": [],
					"Min": "798,1 MHz",
					"Value": "3192,7 MHz",
					"Max": "3492,2 MHz",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 8,
					"Text": "CPU Core #3",
					"Children": [],
					"Min": "798,1 MHz",
					"Value": "3093,0 MHz",
					"Max": "3492,3 MHz",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 9,
					"Text": "CPU Core #4",
					"Children": [],
					"Min": "798,1 MHz",
					"Value": "3093,0 MHz",
					"Max": "3492,1 MHz",
					"ImageURL": "images/transparent.png"
				}],
				"Min": "",
				"Value": "",
				"Max": "",
				"ImageURL": "images_icon/clock.png"
			}, {
				"id": 10,
				"Text": "Temperatures",
				"Children": [{
					"id": 11,
					"Text": "CPU Core #1",
					"Children": [],
					"Min": "62,0 °C",
					"Value": "65,0 °C",
					"Max": "99,0 °C",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 12,
					"Text": "CPU Core #2",
					"Children": [],
					"Min": "62,0 °C",
					"Value": "67,0 °C",
					"Max": "99,0 °C",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 13,
					"Text": "CPU Core #3",
					"Children": [],
					"Min": "60,0 °C",
					"Value": "63,0 °C",
					"Max": "99,0 °C",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 14,
					"Text": "CPU Core #4",
					"Children": [],
					"Min": "58,0 °C",
					"Value": "64,0 °C",
					"Max": "100,0 °C",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 15,
					"Text": "CPU Package",
					"Children": [],
					"Min": "63,0 °C",
					"Value": "68,0 °C",
					"Max": "100,0 °C",
					"ImageURL": "images/transparent.png"
				}],
				"Min": "",
				"Value": "",
				"Max": "",
				"ImageURL": "images_icon/temperature.png"
			}, {
				"id": 16,
				"Text": "Load",
				"Children": [{
					"id": 17,
					"Text": "CPU Total",
					"Children": [],
					"Min": "0,0 %",
					"Value": "5,0 %",
					"Max": "100,0 %",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 18,
					"Text": "CPU Core #1",
					"Children": [],
					"Min": "0,0 %",
					"Value": "7,7 %",
					"Max": "100,0 %",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 19,
					"Text": "CPU Core #2",
					"Children": [],
					"Min": "0,0 %",
					"Value": "2,3 %",
					"Max": "100,0 %",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 20,
					"Text": "CPU Core #3",
					"Children": [],
					"Min": "0,0 %",
					"Value": "5,4 %",
					"Max": "100,0 %",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 21,
					"Text": "CPU Core #4",
					"Children": [],
					"Min": "0,0 %",
					"Value": "4,6 %",
					"Max": "100,0 %",
					"ImageURL": "images/transparent.png"
				}],
				"Min": "",
				"Value": "",
				"Max": "",
				"ImageURL": "images_icon/load.png"
			}, {
				"id": 22,
				"Text": "Powers",
				"Children": [{
					"id": 23,
					"Text": "CPU Package",
					"Children": [],
					"Min": "6,6 W",
					"Value": "16,5 W",
					"Max": "56,8 W",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 24,
					"Text": "CPU Cores",
					"Children": [],
					"Min": "2,9 W",
					"Value": "12,9 W",
					"Max": "48,3 W",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 25,
					"Text": "CPU Graphics",
					"Children": [],
					"Min": "0,2 W",
					"Value": "0,3 W",
					"Max": "5,8 W",
					"ImageURL": "images/transparent.png"
				}],
				"Min": "",
				"Value": "",
				"Max": "",
				"ImageURL": "images_icon/power.png"
			}],
			"Min": "",
			"Value": "",
			"Max": "",
			"ImageURL": "images_icon/cpu.png"
		}, {
			"id": 26,
			"Text": "Generic Memory",
			"Children": [{
				"id": 27,
				"Text": "Load",
				"Children": [{
					"id": 28,
					"Text": "Memory",
					"Children": [],
					"Min": "18,4 %",
					"Value": "51,2 %",
					"Max": "100,0 %",
					"ImageURL": "images/transparent.png"
				}],
				"Min": "",
				"Value": "",
				"Max": "",
				"ImageURL": "images_icon/load.png"
			}, {
				"id": 29,
				"Text": "Data",
				"Children": [{
					"id": 30,
					"Text": "Used Memory",
					"Children": [],
					"Min": "1,4 GB",
					"Value": "4,0 GB",
					"Max": "7,9 GB",
					"ImageURL": "images/transparent.png"
				}, {
					"id": 31,
					"Text": "Available Memory",
					"Children": [],
					"Min": "0,0 GB",
					"Value": "3,8 GB",
					"Max": "6,4 GB",
					"ImageURL": "images/transparent.png"
				}],
				"Min": "",
				"Value": "",
				"Max": "",
				"ImageURL": "images_icon/power.png"
			}],
			"Min": "",
			"Value": "",
			"Max": "",
			"ImageURL": "images_icon/ram.png"
		}, {
			"id": 32,
			"Text": "ADATA SU800",
			"Children": [{
				"id": 33,
				"Text": "Temperatures",
				"Children": [{
					"id": 34,
					"Text": "Temperature",
					"Children": [],
					"Min": "52,0 °C",
					"Value": "53,0 °C",
					"Max": "72,0 °C",
					"ImageURL": "images/transparent.png"
				}],
				"Min": "",
				"Value": "",
				"Max": "",
				"ImageURL": "images_icon/temperature.png"
			}, {
				"id": 35,
				"Text": "Load",
				"Children": [{
					"id": 36,
					"Text": "Used Space",
					"Children": [],
					"Min": "63,3 %",
					"Value": "64,5 %",
					"Max": "68,9 %",
					"ImageURL": "images/transparent.png"
				}],
				"Min": "",
				"Value": "",
				"Max": "",
				"ImageURL": "images_icon/load.png"
			}],
			"Min": "",
			"Value": "",
			"Max": "",
			"ImageURL": "images_icon/hdd.png"
		}, {
			"id": 37,
			"Text": "Generic Hard Disk",
			"Children": [{
				"id": 38,
				"Text": "Load",
				"Children": [{
					"id": 39,
					"Text": "Used Space",
					"Children": [],
					"Min": "100,0 %",
					"Value": "100,0 %",
					"Max": "100,0 %",
					"ImageURL": "images/transparent.png"
				}],
				"Min": "",
				"Value": "",
				"Max": "",
				"ImageURL": "images_icon/load.png"
			}],
			"Min": "",
			"Value": "",
			"Max": "",
			"ImageURL": "images_icon/hdd.png"
		}],
		"Min": "",
		"Value": "",
		"Max": "",
		"ImageURL": "images_icon/computer.png"
	}],
	"Min": "Min",
	"Value": "Value",
	"Max": "Max",
	"ImageURL": ""
}`

My simple code 
`local przycisk = 'Włącz pobranie danych'
return {
	on = {
		devices = {przycisk},
		httpResponses = {
			'cputemp' -- must match with the callback passed to the openURL command
		}
	},
	execute = function(domoticz, item)

		if (domoticz.devices(przycisk).changed and domoticz.devices(przycisk).state=='On') then
			print('pobranie strony')
			domoticz.openURL({
				url = 'http://myhost:8085/data.json',
				method = 'GET',
				callback = 'cputemp', -- see httpResponses above.
			})
		end

		if (item.isHTTPResponse) then

			if (item.ok) then
				if (item.isJSON) then
				    print('przetworzenie strony')
				    --local tabela = domoticz.utils.fromJSON(item)
				    --domoticz.utils.dumpTable(item)
				    
				    local wynik = item.json.Children[0].Text
				    print('wynik = '..wynik)
				    
				end
			else
				domoticz.log('There was a problem handling the request', domoticz.LOG_ERROR)
				domoticz.log(item, domoticz.LOG_ERROR)
			end

		end

	end
}
`

and log 
' 2021-07-22 02:25:52.048 Status: dzVents: przetworzenie strony
2021-07-22 02:25:52.049 Status: dzVents: Info: ------ Finished cputemp monitor
2021-07-22 02:25:52.788 Status: dzVents: Info: Handling events for: "Włącz pobranie danych", value: "Off"
2021-07-22 02:25:52.788 Status: dzVents: Info: ------ Start internal script: cputemp monitor: Device: "Włącz pobranie danych (Dummy)", Index: 1096
2021-07-22 02:25:52.788 Status: dzVents: Info: ------ Finished cputemp monitor
2021-07-22 02:25:52.049 Error: dzVents: Error: (3.0.2) An error occurred when calling event handler cputemp monitor
2021-07-22 02:25:52.049 Error: dzVents: Error: (3.0.2) ...cz/scripts/dzVents/generated_scripts/cputemp monitor.lua:28: attempt to index a nil value (field '?')
'

Problem seems that it cannot parse field Children.
With other json's it is working fine especially in stable 2021 release.
Any hints how to fix it?

Adam

**Comment by waltervl** [comment]
The only hint I have is to use the forum for this question. You will have a larger audience to answer it.

**Comment by AdamWeglarz** [comment]
For me it is a defect, because, when I change in purpose name of table local wynik = item.json.Children1[0].Text it returns proper error that Children1 does not exists.

**Comment by dotnetniet** [comment]
Is Children not a reserved word?
Does this work: item.json['Children'][0].Text or item.json.['Children'][0].Text

**Comment by dannybloe** [comment]
It is a Lua issue so it is not a bug. Please use the forum.
