### ISSUE TITLE
Netatmo.cpp : fail to check for valves if user have both Weather Station and Thermostat

### ISSUE THREAD

**Issue by StephaneM60** [domoticz/domoticz#4882]
In hardware/Netatmo.cpp, the only way the code check for radiator valves is if m_NetatmoType is set to NETYPE_ENERGY. And this happens on line 1178 in GetMeterDetails() only if code fails to parse json API response for NETYPE_WEATHER_STATION and NETYPE_HOMECOACH (the same logic applies to setting the type to NETYPE_HOMECOACH)

As a consequence when the code check for thermostat data in the Do_Work() function, the GetThermostatDetails() , check for the m_NetatmoType, and if not set the NETYP_ENERGY, it the use the URI "https://api.netatmo.net/api/getthermostatsdata" which only provides data for the thermostat without the valves (and may be deprecated as no documentation is availabe for this in the Netatmo API), instead of calling https://api.netatmo.net/api/homesdata that does have all the data for the thermostat and the valves.

In my opinion, netatmo products are not exclusive : you can have the weather station, the aircare station and the thermostat range (boiler / valves), there is also security products (camera / smoke alarm / sensors)

BUT the API for the thermotsat (https://api.netatmo.net/api/homesdata and https://api.netatmo.net/api/homstatus) does also carry the data for the weather station (and I presume it does carry the data for the aircare station but I'm not sure as far as the API documentation does not state this is the case, even for the weather station)

So the correct way to handle this should be to rewrite the logical decision in the code , there is four product range in Netamo API : Security / Energy / Weather / Aircare. The "Energy" range can carry data for Weather (and maybe AirCare and Security). Curently only Energy / Weather / Aircare is supported and they should be checked in this order 👍 

1) Energy
2) Weather
3) Aircare

The quick fix would be in the function GetMeterDetails() to put the region "//Check if the user has an Enery device (thermostat)" begining at line 1147 through 1181 out of the condition block if (!ParseNetatmoGetResponse(sResult, m_NetatmoType, false)) begining at line 1107

Also a nice feature to add to this hardware is the ability to set the schedule of the thermostat : in the application you can create different temperatures set by room, so as to adapt the heating to some situations. For instance I use this to turn off heating in summer with a "summer" and a "winter" schedule.

The api https://api.netatmo.com/api/homesdata does allow to retreive the schedules (in the "schedules" array, data of interest is schedule id and schedule name) and  the api https://api.netatmo.com/api/switchhomeschedule allow to switch the schedules (home id and schedule id are required)

Note : as a Netatmo user with both weather station and thermostat with radiator valves, I can confirm that radiator valves are not discovered.

**Comment by gizmocuz** [comment]
@StephaneM60 , It has been quite some time since I have worked on this code.
Would you mind making the changes and test if they are working?
I assume more users would benefit from this.

**Comment by StephaneM60** [comment]
I would love to do this, though I do not have set up a development environment for domoticz. I'm actually on Windows 10 and I'm a C# / VBS / JS (well anything Web) devloper so I'm using Visual Studio. I'm not sure I can easily jump into domoticz compilation, I'll try and let you know.

**Comment by gizmocuz** [comment]
Using Visual Studio myself... best IDE ever ;)

**Comment by StephaneM60** [comment]
So I got a working dev environment and I can succesfully build and run domoticz. So I started changing the code and so far it works. There is something though I'm not sure I understand correctly : when setting devices property with for instance :  SendSetPointSensor(NodeID, ChildID, SensorID.....)

NodeID / ChildID / SensorID are what I'm wondering about. NodeID should be the "ID" I can see in the domoticz devices page,ChildID should be the "UNIT" in the devices page (but no idea for SensorID) and I can't verify that the NodeID is really the ID in the devices page (I can see that it does have something to do with it, but it's not the same)

So before I'm doing wrong things, I better be sure to be doing right (As I will have to change some of the IDs used to be sure there is no funky things happening)

**Comment by StephaneM60** [comment]
So I managed to change the code the way I wanted (and figured the NodeID etc... thing at least for what was needed here, otherwise I suspect that it may be a convoluted story ;-)) and I verified that it works now as it should with both an energy and weather device (I also verified that the code path that was used before in this situation is still working as it should)

Though I have not completely inverted the logic as I cannot test (or guess wiht API doc) what is happening with homecoach + energy device and also with homecoach + weather device (but I have laid some rewrite to go this way)

Do you want me to check in the code or to create a branch (I cloned the default branch, and only edited domoticz\hardware\Netatmo.cpp and domoticz\hardware\Netatmo.h.)

**Comment by waltervl** [comment]
Seems to be related to https://github.com/domoticz/domoticz/issues/4402
Is there some progress on this issue?

**Comment by StephaneM60** [comment]
I made the changes last August and it works well, but I don't know how to submit my code so as it can be checked in later...

**Comment by waltervl** [comment]
Fork the Domoticz source code, make your own branch, make the changes and create a pull request.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests

**Comment by gizmocuz** [comment]
@StephaneM60 , If you are not able to perform the above steps, could you attach the changed files here in a zip ?

**Comment by waltervl** [comment]
@StephaneM60 Can you prepare the change (with PR or ZIP)?

**Comment by StephaneM60** [comment]
I would love to create a branch, but I'm currently not allowed to create a branch. I followed the link you gave me. And it fails to display the link "Create branch: xxxxxx from yyyyyy", so I'm stuck here

**Comment by StephaneM60** [comment]
Note : I made the change and compiled the project with Visual Studio 2019, and actually connected VS with the Git project so I am able to upload the changes directly from VS (and I do have a button there to create a new branch, don't know if it will succeed though, I'm afraid to do a mistake here)

**Comment by kiddigital** [comment]
Hi @StephaneM60 , you first have to 'fork' the Domoticz repo into a copy of your own.

There (in your own copy) you can create a branch and create a PR against the Domoticz repo.

**Comment by StephaneM60** [comment]
I'm not sure I forked, I do have a downloaded a copy of the development branche (It is "Local" for VS as there is a "Distant" tab where I can see the other branchs (origin/maste, origin/oauth2 etc...)

In the solution explorer / git modifications, I have "developement" selected in the drop down, then buttons :  Get / Pull / Send (Push) /  Synchronise (retrieve and push) and a "..." menu where I can find "Create new branch"

I suppose the pull request equivalent in VS is the "synchronise" button...

**Comment by StephaneM60** [comment]
Finally I managed to proceed in another way : a fork, then a push, then a pull request... So your turn now.

Regards.

**Comment by gizmocuz** [comment]
Perfect, yes that is the correct way... Fork-> make changes -> commit -> push and when everything is ready -> make a PR
After a PR when you make changes and commit->push they will show up in the PR
