### ISSUE TITLE
recovery check box

### ISSUE THREAD

**Issue by cronyx** [domoticz/domoticz#4884]
Hello, Recovery check box in notification settings is broken on latest beta.

![recovery](https://user-images.githubusercontent.com/2557102/127317945-eda3e2ed-4489-404b-af1f-cdd24335b48c.png)

**Comment by waltervl** [comment]
Are you sure? Recovery notification is not always visible, it depends on the device type.

**Comment by cronyx** [comment]
Yes, I have checked many devices and there is no checkbox everywhere. You can reproduce by doing a clean install of domoticz, add dummy switch, type on/off.

**Comment by FireWizard52** [comment]
Hi,

And what do you see, if you add a dummy sensor, instead of a dummy switch?

**Comment by waltervl** [comment]
On stable 2021.1 I only see the recovery option in edit - notifications for devices in temperature, weather and utility tab. Not on switches/lights. So it does not seems to be a recent change and more as designed.

**Comment by cronyx** [comment]
Indeed, I checked an older installation and there is no recovery notification on switches there either. On the temperature sensors everything is ok.  Excuse me.
