### ISSUE TITLE
In mobile view a setpoint changes to a temperature reading when value is updated

### ISSUE THREAD

**Issue by akamming** [domoticz/domoticz#4885]
Hi,

there is a small bug in the mobile view. A setpoint is normally shown like this
![image](https://user-images.githubusercontent.com/30364409/127733653-b62bdf0a-be71-4d5e-a612-4ed1692f895e.png)

But when updating this setpoint, e.g. by setting a value
![image](https://user-images.githubusercontent.com/30364409/127733674-26785d4d-5019-40ce-a936-23edc54cae25.png)

It is no longer usable as a setpoint, cause it is shown like a temperature reading:
![image](https://user-images.githubusercontent.com/30364409/127733716-1a109fd7-5a20-4d2d-8c14-456182df6ecf.png)

Workaround is refreshing the page, then it is shown like a setpoint and can be changed again
![image](https://user-images.githubusercontent.com/30364409/127733757-8f6ae93a-0161-4e6e-81d6-59d6cb4aec4b.png)

Expected behaviour is ofcourse that the setpoint remains a setpoint in the mobile view after changing values.

**Comment by gizmocuz** [comment]
Fixed

**Comment by akamming** [comment]
nice... thanx!
