### ISSUE TITLE
(Windows install) Updating from 2017 version to 2021.1 stable missing vcruntime140.dll

### ISSUE THREAD

**Issue by dotnetniet** [domoticz/domoticz#4895]
Version: 2017 -> 2021.1 stable
Platform: Windows 10 Pro
Description: Missing Visual Studio C++ Redistributable Dll's after upgrading to latest stable version 2021.1

Domoticz is running on a clean Windows 10 Pro as service. It's the only active application on that system and has run for more then 5 years without problems with version from 2017.

Did a full backup and run the installer. After that the service started, but status was paused. Stopped the service and started domoticz manually.
Multiple error pop-ups where shown with missing dll's, like vcruntime140.dll and the other VC redistributable ones.

System has the x64 bit versions that come with windows, but it's missing the x86 versions in the syswow64 folder that are used by 32bit applications, like Domoticz.
After installing the x86 version (https://aka.ms/vs/16/release/vc_redist.x86.exe), service started normal.

Suggesting to add this vc_redist_x86.exe into the installer if these dll's are not present on the system.

Is this the correct solution or should all the used dll's in the installer be using a static build?
Seems that the Lua.dll is not statically linked (verified with dependency walker tool).

Looking to add this check into the inno setup, so it's a permanent solution, but do not know if this is the correct action.

**Comment by dotnetniet** [comment]
Added pull request https://github.com/domoticz/domoticz/pull/4897

**Comment by gizmocuz** [comment]
Sorry missed the link to this issue.
It should be statically linked. Or the two missing dll's needs to be shipped with domoticz.
This PR is adding 13MB to the installer ....
It's the first time I hear about this, do you know which file needs this dependency ?

**Comment by dotnetniet** [comment]
There are multiple runtime dll's missing in this situation and it's not recommended to copy these runtime dll's 'manually'. Microsoft recommends the redistributable installer.

I also wanted to use Windows server 2019 and that has even less standard dll's installed., but think
 no normal person  will use  windows server😀

Regarding what dll's are not statically linked, I found that the lua.dll is not static, but did not look at other dll's. Will need to have a look at those.

**Comment by dotnetniet** [comment]
I checked on the clean Windows server 2019 install, my Windows 10 is not clean anymore.

The following dll’s from the application folder need the vcruntime140.dll and MSVCP140.dll files:

lua.dll
libcurl.dll
jsoncpp.dll
libcrypto-1_1.dll
libssl-1_1.dll
zlib1.dll
sqlite3.dll
mosquitto.dll
boost_chrono-vc142-mt-x32-1_75.dll
boost_thread-vc142-mt-x32-1_75.dll
boost_system-vc142-mt-x32-1_75.dll
pthreadVC3.dll

Only OpenZWave.dll seems ok.

Maybe other option is just to include these vcruntime140.dll and MSVCP140.dll in the setup, but again, it's not recommended by Microsoft.

**Comment by dotnetniet** [comment]
So to conclude, we have three options to solve this problem:

1. make all dll's static linked and update all development environments
2. check for vcruntime140.dll version and install vc_redist_x86.exe when needed (suggested in PR)
3. include vcruntime140.dll and MSVCP140.dll files in setup next to other dll's (not recommended by MS)

Option 3 works, but unkown what the drawbacks are.

Like any input how to continue here.

**Comment by gizmocuz** [comment]
Option 3 is no problem as the DLL's are placed in the installation folder of Domoticz. It's also done a lot.
But could you maybe try to install windows 10 via Hyper-V ? (Or virtualbox), I do not expect that the redist is needed.
If it is only needed for Windows Server 2019, then I vote for option 3, or present the user a dialog with a link where to download it from and abort installation. (instead of adding the redist (13MB)

**Comment by dotnetniet** [comment]
I will have a look and try to create a new vm with proxmox for windows 10.
Already checked if there where issues if the two dll's where placed in the installation folder when vc runtime was already installed. I seems to be fine.

Will the two dll's be part of the WindowsLibraries.7z file if all works out?

**Comment by gizmocuz** [comment]
@MarkVeldt , yes please place them in the redist folder

**Comment by dotnetniet** [comment]
I found no problems with a clean Windows 10 Pro.
Added dll files in Redist folder: https://github.com/domoticz/win32-libraries/pull/2

**Comment by MarkVeldt** [comment]
Ok, did find a problem, but don't know why this does not work.
When a new setup is compiled with new dll's in Redist folder, Domoticz does not work anymore and asks for the fmt.dll.
When current 2021.1 setup is used and the two dll's are copied manually to the application folder, all works normal.

Not sure why the new compiled setup does not work....

**Comment by gizmocuz** [comment]
@MarkVeldt , yes that's what I thought... Did you update your Windows Server 2019 ?
Maybe just add a dialog message that the user needs to download/install the 32 bit visual studio 2019 runtime would be better then forcing everyone a larger installer/download
Not many users will use windows server

**Comment by dotnetniet** [comment]
Well, this is only for windows installer, so these extra bytes should not be a problem.
I checked server 2019 before this, that was also no problem.

Think adding only these two dll's is for now the best solution. 
We can add a check for these two dll's if runtime is already installed,  but that seems a bit overkill.

**Comment by dotnetniet** [comment]
This issue can be closed when https://github.com/domoticz/win32-libraries/pull/2 is merged.

**Comment by gizmocuz** [comment]
This is still the first time someone has a issue with this, and until there are more people having this issue, it would not be a good idea to increase the installer size

**Comment by dotnetniet** [comment]
May I ask why you are concerned about the size of the installer for Windows?

Why this problem does not occur that often is because 64bit Windows is not used that many times with Domoticz. And if Windows is used there are probably other 32bit applications installed that install the 32bit runtime dll's.
This problem only occurs on a clean 64bit Windows install.

**Comment by gizmocuz** [comment]
Yes you're right, it doesn't take that much space. I merged the PR, thank you!

**Comment by dotnetniet** [comment]
Thank you.
