### ISSUE TITLE
Protected switch is not protected in groups

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#4903]
A protected switch placed in a group is not protected when a group is activated.
There is no popup or warning when the group is activated.

Version: 2021.1 (build 13360)
Build Hash: eee333c30
Compile Date: 2021-07-04 11:58:11
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

**Comment by gizmocuz** [comment]
Nope, but you can protect the group/scene ?

**Comment by SargonofAssyria** [comment]
But isn't it logical that a protected switch, as part of a group, should be (de)activated when the group gets (de)activated with a popup for the password?

**Comment by gizmocuz** [comment]
Nope, you placed (as admin) this switch in a group, it is up to you to protect the group or not. Maybe the switch should not be operated on itself but should only work as part of a group...
I think it is al fine like this
If you do not want to have this switch 'switched' you should not add it to a group ;)

**Comment by SargonofAssyria** [comment]
Oke, Tnx for the explanation 👍
