### ISSUE TITLE
[Python Plugins Framework] SQL Error during device update

### ISSUE THREAD

**Issue by stas-demydiuk** [domoticz/domoticz#4920]
I'm trying to migrate one of my python plugins to extended version of [python plugins framework](https://www.domoticz.com/wiki/Developing_a_Python_plugin#Extended_Plugin_Framework) and faced with an issue when I'm trying to update text device with json value which contains a single quote:

```
device = Devices[device_id].Units[unit]
device.sValue = json.dumps({"key": "Doesn't work"})
device.Update()
```

I receive the following error
```
Error: SQL Query("UPDATE DeviceStatus SET Name='Device_Name', Description='', Used=0, Type=243, SubType=19, SwitchType=0, nValue=0, sValue='{"key": "Doesn't work"}', CustomImage=0, Color='', SignalLevel=12, BatteryLevel=255, Options='', LastUpdate='2021-08-28 12:41:18' WHERE (HardwareID==2) AND (DeviceID=='api_transport') AND (Unit==255)") : near "t": syntax error
```

Looks like the value isn't properly escaped on a framework side

A similar code works just fine with the legacy plugins framework:
```
device = Devices[unit]
device.Update({
  'nValue': 0,
  'sValue': json.dumps({"key": "Doesn't work"})
})
```

@dnpwwo I wonder if you could take a look

**Comment by dnpwwo** [comment]
Surprised the legacy one works but pushed a fix to the extended one

**Comment by stas-demydiuk** [comment]
Thanks so much!
