### ISSUE TITLE
Better info about the dzVents script that running more then 10 seconds.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#4922]
Running version:
Version: 2021.1 (build 13360)
Build Hash: eee333c30
Compile Date: 2021-07-04 11:58:11
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

I get the following line in domoticz.log
`2021-08-31 19:00:10.814  Error: dzVents script command running longer than specified timeout(10 seconds), cancelling...`

It would be nice to have the name of that script also logged.

**Comment by GravityRZ** [comment]
my personal experience is that it is not so much a specific scipt which is causing the 10 second timeout but more the complete host which is slowing down.

in my case i am running domoticz on a synology nas.

whenever i was moving a lot of files between smb shares i noticed i got this error in domoticz
for me capping the download/upload speed resolved this problem.

so logging the specific name of the script i a good idea but will probably not always pinpoint the cause of the problem

**Comment by SargonofAssyria** [comment]
@gizmocuz It would be nice to know why this was closed.

**Comment by gizmocuz** [comment]
@SargonofAssyria , Sorry thought I pushed the patch, but that was not done yet

https://github.com/domoticz/domoticz/commit/fa5c6c14a2d8fe61b7a7d3b1ceb1c97bf1f299c5

This should tell the command that was executed

**Comment by dannybloe** [comment]
That's interesting.. how can you determine which script that was? From Domoticz' point of view there is only dzVents.lua and that one dispatches to other lua modules.
