### ISSUE TITLE
Different values for Electric (instant+counter) device

### ISSUE THREAD

**Issue by otello86** [domoticz/domoticz#4924]
Hi,

i use Domoticz in version 2021.1 (build 13490) and i have a difference between values of a device (in log and sql) and the values displayed in the comparing use view

Here an example of the sql data in sql for the device 677

677 | 0 | 7336 | 2021-07-01
677 | 0 | 7336 | 2021-07-02
677 | 0 | 7336 | 2021-07-03
677 | 1000 | 7336 | 2021-07-04
677 | 0 | 7336 | 2021-07-05
677 | 0 | 7336 | 2021-07-06
677 | 1000 | 7336 | 2021-07-07
677 | 0 | 7336 | 2021-07-08
677 | 0 | 7336 | 2021-07-09
677 | 3000 | 7336 | 2021-07-10
677 | 2000 | 7336 | 2021-07-11
677 | 1000 | 7336 | 2021-07-12
677 | 2000 | 7336 | 2021-07-13
677 | 1000 | 7336 | 2021-07-14
677 | 0 | 7336 | 2021-07-15
677 | 0 | 7336 | 2021-07-16
677 | 0 | 7336 | 2021-07-17
677 | 0 | 7336 | 2021-07-18
677 | 0 | 8897 | 2021-07-19
677 | 0 | 8897 | 2021-07-20
677 | 1000 | 8897 | 2021-07-21
677 | 1000 | 8897 | 2021-07-22
677 | 0 | 8897 | 2021-07-23
677 | 1000 | 8897 | 2021-07-24
677 | 0 | 8897 | 2021-07-25
677 | 0 | 8897 | 2021-07-26
677 | 0 | 8897 | 2021-07-27
677 | 0 | 8897 | 2021-07-28
677 | 0 | 8897 | 2021-07-29
677 | 0 | 8897 | 2021-07-30
677 | 0 | 8897 | 2021-07-31

The sum of the consumption is 14000(watt) and the report displayed for July : 1,56 kwh

![Capture d’écran du 2021-08-31 23-16-20](https://user-images.githubusercontent.com/57249990/131577459-7e1aead6-ab66-4172-90d2-bac51935a64e.png)

**Comment by GravityRZ** [comment]
not sure  if this really a bug  but you are comparing 14000 Watt to 1,56kWh

You can not compare Watt (without the time unit) with kWh (which does include a time unit)

So if you mean the sums of 1 month is 14000kWh accoording to the DB but it shows 1,56kWh in domoticz as the total for that month then you are right. if not better check and rephrase your question.

just trying to help

**Comment by otello86** [comment]
Yes, the report displays the total for July and it shows 1,56Kwh
But in the database if i sum all the days of july in the table "meter_calendar" i have 14000w so 14kwh and these value match with the value available on the website of my provider

**Comment by otello86** [comment]
Precision, it's the same for all months and not only once

**Comment by michahagg** [comment]
Hi @otello86, I just saw your issue report. It seems that in your case the Counter and the Value are completely out of touch with each other. The week/month/year-charts each display the Value recorded for each day. Where for the comparison-chart, the charted value is computed by summing the differences between each day and the previous day in the month/quarter/year. The reason for this is that I saw in my data that the Value recorded for a particular day could be different from the difference between the Counter value of that day and the previous day. My assumption was that the Counter is always correct; the Counter is what is received from the device and the Value is calculated from it. In your situation it seems to be the other way around.

I can give you the query that is used to calculate the Counter differences for the comparison-chart and see what that gives for your data:

```
select
		 mc0.DeviceRowID,
		 date(mc0.Date) as Date,
		 mc1.Counter as Counter_Previous,
		 mc0.Counter as Counter,
		 case
				when mc1.Counter <= mc0.Counter
				then mc0.Counter - mc1.Counter
				else mc0.Value
		 end as Counter_Difference,
		 mc0.Value,
		 case when 
		 case
				when mc1.Counter <= mc0.Counter
				then mc0.Counter - mc1.Counter
				else mc0.Value
		 end <> mc0.Value then 'Value is different' end as Value_Is_Different
from Meter_Calendar mc0
inner join Meter_Calendar mc1 on mc1.DeviceRowID = mc0.DeviceRowID
		 and mc1.Date = (
				 select max(mcm.Date)
				 from Meter_Calendar mcm
				 where mcm.DeviceRowID = mc0.DeviceRowID and mcm.Date < mc0.Date and mcm.Counter <> 0
		 )
where
		 mc0.DeviceRowID = 677
		 and mc0.Counter <> 0
		 and (select min(Date) from Meter_Calendar where DeviceRowID = 677 and Counter <> 0) <= mc1.Date
		 and mc0.Date <= (select max(Date) from Meter_Calendar where DeviceRowID = 677 and Counter <> 0)
order by mc0.Date DESC
;
;

**Comment by waltervl** [comment]
@otello86 did you manage to find your issue?

**Comment by otello86** [comment]
No i don't find solution to this pb.
Now i migrate to home assistant
