### ISSUE TITLE
Building from source error SQLHelper.cpp:600:16: error: use of undeclared identifier 'sqlite3_prepare_v3'

### ISSUE THREAD

**Issue by Locusi** [domoticz/domoticz#4926]
Lately I get an error trying to build Domoticz from source:
dev-domoticz/main/SQLHelper.cpp:600:16: error: use of
      undeclared identifier 'sqlite3_prepare_v3'
        int iRetVal = sqlite3_prepare_v3(m_DBase, pSQL.c_str(), ...
CMakeFiles/domoticz.dir/build.make:472: recipe for target 'CMakeFiles/domoticz.dir/main/SQLHelper.cpp.o' failed
make[2]: *** [CMakeFiles/domoticz.dir/main/SQLHelper.cpp.o] Error 1

build command: 
cmake-3.19.4-Linux-x86_64/bin/cmake -DBOOST_ROOT=/home/Domoticz/boost_1_77_0 \
-DBOOST_LIBRARYDIR=/home/Domoticz/boost_1_77_0/stage/lib -DBOOST_INCLUDEDIR=/home/Domoticz/boost_1_77_0 \
-DCURL_INCLUDE_DIR=/opt/curl7_75_0/include/curl/ -DCURL_LIBRARIES=/opt/curl7_75_0/lib \
-DCURL_LIBRARY=/opt/curl7_75_0/lib/libcurl.so -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 \
CMakeLists.txt
uname -a:
Linux 4.9.0-16-amd64 #1 SMP Debian 4.9.272-1 (2021-06-21) x86_64 GNU/Linux
lsb_release -a:
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

Any advice beside "upgrade your operating system"?

**Comment by dnpwwo** [comment]
I don't think your OS is the issue, its the version of sqlite3.

If this is a development system I would recommend upgrading it from [https://www.sqlite.org/download.html](url)

**Comment by Locusi** [comment]
Thank You @dnpwwo ! Your advice put me on the right track! I don't have development system so I couldn't just upgrade it, but I've downloaded sqlite-autoconf-3360000.tar.gz, unpacked it, did "./configure && make" and then I've added to cmake:
-DSQLite3_INCLUDE_DIR=/home/Domoticz/sqlite-autoconf-3360000 -DSQLite3_LIBRARIES=/home/Domoticz/sqlite-autoconf-3360000 -DSQLite3_LIBRARY=/home/Domoticz/sqlite-autoconf-3360000/.libs/libsqlite3.so
and error disappeared! So it appears that this problem is solved. Thanks again!
