### ISSUE TITLE
When creating a new sensor history shows up from year 0 to 2020

### ISSUE THREAD

**Issue by rtm-soft** [domoticz/domoticz#4930]
When creating a new dummy P1 smart meter I get history from year 0 to 2020, see picture below. Latest software on multiple different systems. Didn't have this problem before. Thanks Rene

![Screenshot 2021-09-09 at 17-30-55 Domoticz](https://user-images.githubusercontent.com/14265890/132765795-0fc72b9d-9780-46d6-80f1-c964f97498f0.png)

**Comment by rtm-soft** [comment]
After 3 days this issue seems to fix itself. I can confirm this after reading the same issue in one of the issue reports

**Comment by dobber81** [comment]
https://github.com/domoticz/domoticz/issues/4856 and https://github.com/domoticz/domoticz/pull/4830
