### ISSUE TITLE
DomoticzEx associated (selector) switches do not trigger actions

### ISSUE THREAD

**Issue by odelma** [domoticz/domoticz#4931]
Version: 2021.1 (build 13497)
Build Hash: 2c271b6d2
Compile Date: 2021-09-10 16:25:51
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

With zigbee2mqtt: 
plugin: v.3.1.0-beta, zigbee2mqtt: v.1.21.1 (zStack3x0 20210120)

It seems that selector switches that are associated with python plugin framework (DomoticzEx) are not triggering their respective actions anymore. The switches as such seem to work as they should, their state changes and no error on the log. But the associated actions configure behind each level do not trigger. This shows in my setup only with selector switches controlled by zigbee2mqtt plugin which was recently updated to supporting DomoticzEx. I raised an issue about this in zigbee2mqtt project and the conclusion was that this must be something in the plugin framework that causes this. If I revert the zigbee2mqtt plugin to version that is not using DomoticzEx, the selector switches are working again.

I cannot find any relevant info in logs.

From zigbee2mqtt plugin repo:
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/708

https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/687#issuecomment-907814317

Maybe @dnpwwo could take a look and if more info is needed I am happy to provide anything I can 😀

**Comment by royka1** [comment]
Same problem here on Domoticz 13499
When I press a button on a zigbee remote, I can see the state changes on Domoticz, but no action. Even when I click on it, it doesn't execute anything.

**Comment by gizmocuz** [comment]
Can you try with the native MQTT class with auto discovery? Add a new MQTT hardware, empty the domoticz topic in/out, and for discovery topic enter 'homeassistant' and make sure zigbee2mqtt or zwavejs2mqtt are using the homeassistant discovery protocol option

**Comment by royka1** [comment]
> Can you try with the native MQTT class with auto discovery? Add a new MQTT hardware, empty the domoticz topic in/out, and for discovery topic enter 'homeassistant' and make sure zigbee2mqtt or zwavejs2mqtt are using the homeassistant discovery protocol option

After adding the new MQTT hardware with "homeassistant" topic and enabling the homeassistant discovery in zigbee2mqtt, every zigbee device is added except the Ikea remote I've the problem with. Tried to choose Accept new hardware in settings and controlling the remote, but it doesn't show up, nothing to see in the logs either. 
The "old" device added by the plugin still receives the current state of the buttons.
With the device "Selector switch" from the plugin, the log is also empty, even after clicking on the buttons in domoticz.
Another zigbee tripple switch which shows up as 3 separate switches, works as it should.

**Comment by gizmocuz** [comment]
@royka1 , that's correct, you do not need to enable 'accept new hardware'.

Please join us on Slack (mqtt_autodiscovery channel)

https://join.slack.com/t/domoticz/shared_invite/zt-v59e0d7p-WyEFkNwAsIt2u1_FmI53zA

Please describe your issue and please post the 'config' part of this remote (you can see this by using (for example) MQTT Explorer)
And if possible the state message received when pressing a button on the remote

**Comment by waltervl** [comment]
If it worked in the old Zigbee2MQTT plugin it should also work in the new plugin and it is an issue for the Python DomoticzEx framework,
@gizmocuz  Why transfer this issue to MQTT AutoDiscovery? Is MQTT autodiscovery supporting more than 256 devices (the reason DomoticzEx is developped)?

Beside this, the specific Ikea remote is having some special considerations as it does not react as a normal zigbee switch: https://www.zigbee2mqtt.io/devices/E1524_E1810.html

**Comment by odelma** [comment]
> After adding the new MQTT hardware with "homeassistant" topic and enabling the homeassistant discovery in zigbee2mqtt, every zigbee device is added except the Ikea remote I've the problem with. 

It sounds like this issue: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/707

is actually a Domoticz issue and not zigbee2mqtt plugin issue in case also the autodiscovery has problems in creating certain devices 🤔

Although, this user: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/707#issuecomment-921612867 solved it by updating zigbee2mqtt plugin (I already run v.3.0 but continue to have issues with few devices).

**Comment by dnpwwo** [comment]
Hi,

The extended framework does invoke the functionality for On and Off but is optimised to do it when switch value changes (normally the 'nValue' changes).

Maybe that is not the case for selectors.

I can explicitly add selectors to the logic but it will take a day or two because I've made some big changes internally and want to run for a bit to make sure I haven't broken anything major.

**Comment by odelma** [comment]
Sounds great, thanks. Let’s at least try it 👍

**Comment by stas-demydiuk** [comment]
@dnpwwo I guess for selector switches the logic is the following:
`nValue` is 0 if switch is off, otherwise it is always 1, 
so for example if you have switch with states ['Off', 'Level1', 'Level2'] and you switch from 'Level1' to 'Level2', `nValue` won't change and stay 1, only `sValue` will be changed

So I guess it makes sense to check both if `nValue` or `sValue` is changed

**Comment by pipiche38** [comment]
I do not agree with your logic. 

Here is the logic I’m using 
nValue:sValue
0:0
1:10
2:20
3:30
4:40
….


Envoyé de mon iPhone

**Comment by dnpwwo** [comment]
Its clearly a little confusing.

I've gone with:   `if (nValueChanged || (self->SubType == sSwitchTypeSelector))`

Which is effectively 'Switches and Selectors' by my understanding.

I'm going to push the change today (barring anything unexpected)

**Comment by stas-demydiuk** [comment]
@dnpwwo, I guess it could be not only this case, as I see from zigbee2mqtt plugin code, there are some other cases as well:
for example `nValue` for Temperature, Temp+Hum, Pressure and some other sensors are always 0, only `sValue` changes. 

If that's not the proper approach I could update it in the plugin but want to double-check that first

@gizmocuz, wonder if you have any idea what's the desired approach

**Comment by dnpwwo** [comment]
@stas-demydiuk ,  

I based the logic on what can be configured through the Domoticz UI. I didn't see anywhere to add actions for Temperature or Utility sensors. If actions can't be set up I was trying to optimise the code by not looking to trigger them.

Are you setting the actions up in the plugin itself?

**Comment by stas-demydiuk** [comment]
No plugin doesn't set any actions by itself, but I guess you could use any device as a trigger when you are using dzVents scripts

**Comment by dnpwwo** [comment]
I think that the event system is different.

The event system is notified whenever the nValue OR sValue changes and that has always been the case.

I thought the 'actions' referred to in this thread are the On and Off actions that can be defined against switches. Am I wrong?

**Comment by odelma** [comment]
> I thought the 'actions' referred to in this thread are the On and Off actions that can be defined against switches. Am I wrong?

This is correct - actions configured ”behind” the switch (for selectors these are not just on/off) do not trigger, events do trigger.

**Comment by dnpwwo** [comment]
I pushed a fix yesterday, can you retest selectors with that please?

**Comment by odelma** [comment]
Version: 2021.1 (build 13517)
Build Hash: 37d4ad1e8
Compile Date: 2021-09-27 08:45:55
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

Selectors not yet working I’m afraid.

edit: I did not use notifications behind switches so cannot say for sure it was broken in my setup, but I can confirm that DomoticzEx related switches do trigger notifications now, ref: https://github.com/domoticz/domoticz/issues/4941

**Comment by royka1** [comment]
I've also updated to the latest beta and can confirm it's indeed not working yet. In the log I see "2021-09-27 12:18:18.053 Status: User: Admin (IP: 192.168.2.1) initiated a switch command (986/Ikea remote - Right/Set Level)", but no script is executed.

**Comment by odelma** [comment]
In latest commits to dev branch I can see from @dnpwwo only this related to notifications:

![image](https://user-images.githubusercontent.com/10372952/134920867-4fa07f0b-6643-4287-b252-311fc5edef5e.png)
 
Could it be it the fix for this was not merged yet or pushed somewhere else? :)

**Comment by waltervl** [comment]
This fix is implemented in later releases 13624 or higher. Check the download page  domoticz.com/downloads

**Comment by odelma** [comment]
Interesting. So how to update on the latest beta on Raspberry if ./updatebeta does not do it 🤔

**Comment by waltervl** [comment]
If you cannot build yourself you have to wait until the automated build street has compiled it. Normally every day but sometimes it takes longer.

**Comment by odelma** [comment]
Right, of course - so need to wait a bit…😊

**Comment by dnpwwo** [comment]
I've done some more debugging and pushed another fix so you will need to wait a little longer.

Apologies bt I also worked out that selectors were being created incorrectly as well.

**Comment by odelma** [comment]
Updated today to: 

Version: 2021.1 (build 13628)
Build Hash: 24df5e28f
Compile Date: 2021-09-28 15:08:03
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

A strage experience, right after the update I tested one selector and it worked. Then Domoticz crashed right after that and they have not worked since then. Domoticz is now stable though...:)

**Comment by royka1** [comment]
It's working perfecly fine here. 
@odelma maybe you have to re add the selector? because  he worked out that the selectors were not being created correcly before

**Comment by odelma** [comment]
> It's working perfecly fine here. @odelma maybe you have to re add the selector? because he worked out that the selectors were not being created correcly before

Sounds good - with the same version I assume? For me the selectors are quite old (from time well before DomoticzEx) and they were working just fine befor DomoticzEx. I have so many that it will be a big hazzle to re-add them all (could of course test with one). Would be probably just easier to script them than re-add as that involves renaming, placing into rooms etc.

**Comment by royka1** [comment]
Yes with build 13628 indeed. I didn't had to re-add them now after the update, but tried that before. No idea if that matters, but yes you could try with one

**Comment by pipiche38** [comment]
I agree if having to re-add the them, it will them break the compatibility

**Comment by dnpwwo** [comment]
Not sure re-adding is required.

If the selector looks alright when you 'Edit' it then it should work.

**Comment by odelma** [comment]
Yes, after some more testing it looks like the selectors as such do work and trigger the associated actions. But now the problems are in the zigbee2mqtt python plugin - I think. I updated it to the latest version about a week ago and at first it did not give any errors but now after updating Domoticz I see all kinds of error that I assume are related to it.

Here's an overview of errors since updating Domoticz. I have no idea why these errors are manifesting now when Domoticz was updated and not before as they seem to be related to the plugin, right? 

> 2021-09-29 03:32:02.555 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 03:32:02.555 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 03:32:02.555 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 03:32:02.555 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 03:32:07.712 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 03:32:07.712 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 03:32:07.712 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 03:32:07.712 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 04:30:10.208 Error: EventSystem: Warning!, lua script /home/pi/domoticz/scripts/lua/script_time_container.lua has been running for more than 10 seconds
> 2021-09-29 04:32:04.697 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 04:32:04.697 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 04:32:04.697 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 04:32:04.698 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 04:32:09.795 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 04:32:09.795 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 04:32:09.795 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 04:32:09.795 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:02:02.913 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 05:02:02.913 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 05:02:02.913 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:02:02.913 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:02:07.995 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 05:02:07.995 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 05:02:07.995 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:02:07.995 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:10:10.241 Error: EventSystem: Warning!, lua script /home/pi/domoticz/scripts/lua/script_time_container.lua has been running for more than 10 seconds
> 2021-09-29 05:32:04.278 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 05:32:04.278 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 05:32:04.278 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:32:04.278 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:32:09.428 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 05:32:09.428 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 05:32:09.428 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:32:09.428 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 07:55:18.747 Error: AotecZstick: Value_Changed: Tried adding value, not succeeded!. Node: 46 (0x2e), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1
> 2021-09-29 07:55:19.893 Error: AotecZstick: Value_Changed: Tried adding value, not succeeded!. Node: 46 (0x2e), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1
> 2021-09-29 08:10:21.713 Error: AotecZstick: Value_Changed: Tried adding value, not succeeded!. Node: 46 (0x2e), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1
> 2021-09-29 08:10:23.478 Error: AotecZstick: Value_Changed: Tried adding value, not succeeded!. Node: 46 (0x2e), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1
> 2021-09-29 08:11:00.304 Error: AotecZstick: Value_Changed: Tried adding value, not succeeded!. Node: 46 (0x2e), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1
> 2021-09-29 08:12:00.788 Error: AotecZstick: Value_Changed: Tried adding value, not succeeded!. Node: 46 (0x2e), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1
> 2021-09-29 09:32:28.344 Error: SQL Query("SELECT nValue, sValue FROM Preferences WHERE (Key='HideDisabledHardwareSensors')") : no more rows available
> 2021-09-29 09:49:09.665 Error: Zigbee2Mqtt: (Zigbee2Mqtt) A Zigbee publish error occured for device '0xec1bbdfffe85d726' with error message: Publish 'set' 'position' to '0xec1bbdfffe85d726' failed: 'Error: Command 0xec1bbdfffe85d726/1 closuresWindowCovering.goToLiftPercentage({"percentageliftvalue":100}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47566 - 1 - 215 - 258 - 11 after 10000ms)'
> 2021-09-29 09:49:29.128 Error: Zigbee2Mqtt: (Zigbee2Mqtt) A Zigbee publish error occured for device '0x680ae2fffe1ab271' with error message: Publish 'set' 'position' to '0x680ae2fffe1ab271' failed: 'Error: Command 0x680ae2fffe1ab271/1 closuresWindowCovering.goToLiftPercentage({"percentageliftvalue":100}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'
> 2021-09-29 09:49:32.708 Error: Zigbee2Mqtt: (Zigbee2Mqtt) A Zigbee publish error occured for device '0xec1bbdfffe85d726' with error message: Publish 'set' 'state' to '0xec1bbdfffe85d726' failed: 'Error: Command 0xec1bbdfffe85d726/1 closuresWindowCovering.upOpen({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47566 - 1 - 223 - 258 - 11 after 10000ms)'
> 2021-09-29 09:50:04.560 Error: SQL Query("SELECT ID, Name FROM DeviceStatus WHERE (HardwareID=3 AND DeviceID='00082243' AND Unit=1 AND Type=243 AND SubType=31)") : no more rows available
> 2021-09-29 09:50:12.112 Error: Zigbee2Mqtt: (Zigbee2Mqtt) A Zigbee publish error occured for device '0x680ae2fffe1ab271' with error message: Publish 'set' 'state' to '0x680ae2fffe1ab271' failed: 'Error: Command 0x680ae2fffe1ab271/1 closuresWindowCovering.upOpen({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))

**Comment by gizmocuz** [comment]
This is still in beta, but it looks quite stable.
In the latest beta of Domoticz , for the default MQTT you can now enter a auto discovery topic (domoticz or homeassistant) depending on your settings for zwavejs2mqtt or zigbee2mqtt.
This is a native implementation that should have no issues with this

**Comment by odelma** [comment]
Ok - but what to do when one has 200+ devices managed with zigbee2mqtt python plugin, all named, put into proper rooms etc etc. 😄 I don’t feel like doing it all over again, is there any ”shortcut” so that I could keep using the ones that are working? What would be the easiest way to transition to native integration?

**Comment by gizmocuz** [comment]
I am sure you named them correctly in zigbee2mqtt ? Then they will show up with the default MQTT hardware with the same name/deviceID. I would say give it a try before removing the plugin ;)

**Comment by odelma** [comment]
Right, sounds good 👍 
And how about zigbee groups - they are supported as well?

**Comment by odelma** [comment]
> Not sure re-adding is required.
> 
> If the selector looks alright when you 'Edit' it then it should work.

Hi @dnpwwo - I had some more time to test selectors and found out at least one clear issue with triggering the associated commands. It looks like they do not trigger if the selector is already in the same status. In my use case this is critical that it would trigger. I use e.g. "toggle" command in them and expect that it works each time I press the button - even if I would have pressed the same button previously. Also this is problem when having several devices controlling e.g. the same light. You could turn it of from one button and then expect the other button would turn it on again even if it would be in the "on" status already.

Another strange thing is that there is no log history, e.g. here the status had just changed several times:
![image](https://user-images.githubusercontent.com/10372952/136017076-d35be738-41ab-46e9-bf49-aba297649919.png)

For other selectors the history is showing so I suspect it is somehow related to this as well.

edit: I also notice the on/off delay setting does not work with these devices. Even with e.g. 1 sec off delay set, it will remain on the last selected status. With selectors created through other hardare (not supporting DomoticzEx) the on/off delay works wit selectors.

**Comment by odelma** [comment]
> Right, sounds good 👍 And how about zigbee groups - they are supported as well?

Still haven't had the guts to test this as I don't have a separate dev/test environment. I was still thinking about the groups, will they work with the autodiscovery? And also the naming, yes I can have nice friendly name in the bridge, but Domoticz will create up to 10 different devices for one zigbee2mqtt id so probably they will be different from my current logic.

I'm thinking - to safely transition (or at least test) to using auto discovery I would need a way to exclude some of the devices from being created through this feature. Could this be somehow accomplished? Or what happens if I just remove the device created through the auto discovery - will it get created again? If yes, then some sort of blacklist would be very nice feature @gizmocuz 😃

**Comment by gizmocuz** [comment]
@odelma , it's actually quite simpel...
Install domoticz:beta in a docker(compose), fire it up, add the MQTT hardware and test... it will run totally in it's own space
Other way, add a new MQTT hardware, and test, when you delete the new MQTT hardware, also all devices are removed.

**Comment by odelma** [comment]
The underlying problem mentioned in this issue, on/off/selector level actions not triggering is now working as expected. I think the final touch was https://github.com/domoticz/domoticz/commit/5debcc9a3d24c84f8ce2af0b38f2b824a53fcb65 and after this, we can also use push buttons for toggle actions as it now triggers even if the value does not change. Thanks a lot @dnpwwo 😃
