### ISSUE TITLE
Curl missing in latest docker build

### ISSUE THREAD

**Issue by hartenj** [domoticz/domoticz#4932]
Lua scripts report curl not found. Installing curl in the active container temporarily resolves the issue. Please add curl again in the build.

**Comment by gizmocuz** [comment]
@hartenj , strange, as you can see curl is installed (Dockerfile)

curl libcurl4 libcurl4-gnutls-dev

This is also not the place to report it, better to make a issue here:

https://github.com/domoticz/domoticz-docker

But it should be there

**Comment by SylvainPer** [comment]
Problem closed: https://github.com/domoticz/domoticz-docker/pull/7
