### ISSUE TITLE
SQL errors "not enough rows"

### ISSUE THREAD

**Issue by peteralm097** [domoticz/domoticz#4938]
### Issue Guidelines

From the log, started about a month ago;

`2021-09-18 20:40:03.698 Error: SQL Query("SELECT nValue, sValue FROM Preferences WHERE (Key='MeterDividerEnergy')") : no more rows available
2021-09-18 21:04:04.433 Error: SQL Query("SELECT nValue, sValue FROM Preferences WHERE (Key='SecStatus')") : no more rows available
2021-09-18 21:16:01.190 Error: SQL Query("SELECT MIN(Value), MAX(Value) FROM Meter WHERE (DeviceRowID=192 AND Date>='2021-09-18')") : no more rows available
2021-09-19 00:10:23.552 Error: SQL Query("SELECT nValue, sValue FROM Preferences WHERE (Key='SecStatus')") : no more rows available
2021-09-19 00:13:25.082 Error: SQL Query("SELECT nValue, sValue FROM Preferences WHERE (Key='SecStatus')") : no more rows available
2021-09-19 00:20:15.659 Error: SQL Query("SELECT nValue, sValue FROM Preferences WHERE (Key='SecStatus')") : no more rows available`

I am on the latest beta version on a raspberry pi 3 - i use the z-wave, zigbee2mqtt and hive plugins.

Forum gives no insight save for a suggestion that this started about the same time as a zigbee2mqtt update... Happy to dig around some more in my system if that helps, happy to use the database tools if req.

P.

**Comment by gizmocuz** [comment]
If you google for 'no more rows available sqlite' you find some pointers maybe. Could be a wrong index value of a query that is performed by the python plugin. Also worth to check your database if it's not corrupt (via (for example) "SQLite Expert Personal edition"

If you want you can try out the new domoticz beta version's MQTT hardware where you can enter a discovery topic (like homeassistant). If you make sure zigbee2mqtt and zwavejs2mqtt are using the homeassistant mqtt protocol all should hopefully work natively now.
(It's still in early beta).
You can add a new MQTT hardware, clear the domoticz input/output topic settings.
This way if you decide to delete the hardware, it will also delete all assosiated found devices/sensors

**Comment by peteralm097** [comment]
I have had a look at the sqlite documentation and it seems that this can occur when there are no rows to return into an array.
2021-09-22 17:41:48.256 Error: SQL Query("SELECT nValue, sValue FROM Preferences WHERE (Key='ElectricVoltage')") : no more rows available

I am running Zwave using the OpenZwaveUSB plugin that in integrated with Domoticz and the Zigbee2mqtt

I also note that my motion sensors and my RFXMeter Counter have nothing to display in the log - the meter has no graphs, just a blank page and the motion sensors have no entry in the tables. Both Devices work and show values on the dashboard.

I have opened the database and done a check and there are no errors that I can see - I have done a pragma check etc.

I am a bit stumped on this one.

**Comment by gizmocuz** [comment]
Is anything updated in the system ? Could it be a access right to the database file ?

**Comment by arjanvanleent** [comment]
> I have had a look at the sqlite documentation and it seems that this can occur when there are no rows to return into an array.
> 2021-09-22 17:41:48.256 Error: SQL Query("SELECT nValue, sValue FROM Preferences WHERE (Key='ElectricVoltage')") : no more rows available
> 
> I am running Zwave using the OpenZwaveUSB plugin that in integrated with Domoticz and the Zigbee2mqtt
> 
> I also note that my motion sensors and my RFXMeter Counter have nothing to display in the log - the meter has no graphs, just a blank page and the motion sensors have no entry in the tables. Both Devices work and show values on the dashboard.
> 
> I have opened the database and done a check and there are no errors that I can see - I have done a pragma check etc.
> 
> I am a bit stumped on this one.

I had the same issue but after I revert back to an older version of the Zigbee2Mqtt plugin the sql where gone.
The beta version of the plugin give more problems here.

Just waiting till @gizmocuz is ready with the auto discovery like home-assistant this is looking real good atm have it running on a test system.

**Comment by peteralm097** [comment]
It was the SecStatus that was confusing me as i don't think that has anything to do with Zigbee - isn't that the inbuilt security panel? I don't use that but I can see it is there as a device.

2021-09-26 12:08:22.719 Error: SQL Query("SELECT nValue, sValue FROM Preferences WHERE (Key='SecStatus')") : no more rows available

Executing that SQL from a console gives no error. I have checked the database, checked permissions...

**Comment by odelma** [comment]
Hi, I noticed similar errors today on my setup. Seem to be related to zigbee2mqtt and probably somehow tied to also the DomoticzEx framework as the issues in general started around the time this was added. Of course, could be about how it is implemented in the zigbee2mqtt python plugin or in DomoticzEx itself.

Here is a part of the error log:

> 2021-09-29 03:32:02.555 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 03:32:02.555 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 03:32:02.555 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 03:32:02.555 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 03:32:07.712 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 03:32:07.712 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 03:32:07.712 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 03:32:07.712 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 04:30:10.208 Error: EventSystem: Warning!, lua script /home/pi/domoticz/scripts/lua/script_time_container.lua has been running for more than 10 seconds
> 2021-09-29 04:32:04.697 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 04:32:04.697 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 04:32:04.697 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 04:32:04.698 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 04:32:09.795 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 04:32:09.795 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 04:32:09.795 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 04:32:09.795 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:02:02.913 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 05:02:02.913 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 05:02:02.913 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:02:02.913 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:02:07.995 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 05:02:07.995 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 05:02:07.995 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:02:07.995 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:10:10.241 Error: EventSystem: Warning!, lua script /home/pi/domoticz/scripts/lua/script_time_container.lua has been running for more than 10 seconds
> 2021-09-29 05:32:04.278 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 05:32:04.278 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 05:32:04.278 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:32:04.278 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:32:09.428 Error: Zigbee2Mqtt: (Zigbee2Mqtt) 'onCommand' failed 'TypeError':''NoneType' object is not subscriptable'.
> 2021-09-29 05:32:09.428 Error: Zigbee2Mqtt: (Zigbee2Mqtt) Exception traceback:
> 2021-09-29 05:32:09.428 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 302 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 05:32:09.428 Error: Zigbee2Mqtt: (Zigbee2Mqtt) ----> Line 104 in '/home/pi/domoticz/plugins/Zigbee2Mqtt/plugin.py', function onCommand
> 2021-09-29 07:55:18.747 Error: AotecZstick: Value_Changed: Tried adding value, not succeeded!. Node: 46 (0x2e), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1
> 2021-09-29 07:55:19.893 Error: AotecZstick: Value_Changed: Tried adding value, not succeeded!. Node: 46 (0x2e), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1
> 2021-09-29 08:10:21.713 Error: AotecZstick: Value_Changed: Tried adding value, not succeeded!. Node: 46 (0x2e), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1
> 2021-09-29 08:10:23.478 Error: AotecZstick: Value_Changed: Tried adding value, not succeeded!. Node: 46 (0x2e), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1
> 2021-09-29 08:11:00.304 Error: AotecZstick: Value_Changed: Tried adding value, not succeeded!. Node: 46 (0x2e), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1
> 2021-09-29 08:12:00.788 Error: AotecZstick: Value_Changed: Tried adding value, not succeeded!. Node: 46 (0x2e), CommandClass: DOOR LOCK, Label: Locked (Advanced), Instance: 1, Index: 1
> 2021-09-29 09:32:28.344 Error: SQL Query("SELECT nValue, sValue FROM Preferences WHERE (Key='HideDisabledHardwareSensors')") : no more rows available
> 2021-09-29 09:49:09.665 Error: Zigbee2Mqtt: (Zigbee2Mqtt) A Zigbee publish error occured for device '0xec1bbdfffe85d726' with error message: Publish 'set' 'position' to '0xec1bbdfffe85d726' failed: 'Error: Command 0xec1bbdfffe85d726/1 closuresWindowCovering.goToLiftPercentage({"percentageliftvalue":100}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47566 - 1 - 215 - 258 - 11 after 10000ms)'
> 2021-09-29 09:49:29.128 Error: Zigbee2Mqtt: (Zigbee2Mqtt) A Zigbee publish error occured for device '0x680ae2fffe1ab271' with error message: Publish 'set' 'position' to '0x680ae2fffe1ab271' failed: 'Error: Command 0x680ae2fffe1ab271/1 closuresWindowCovering.goToLiftPercentage({"percentageliftvalue":100}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'
> 2021-09-29 09:49:32.708 Error: Zigbee2Mqtt: (Zigbee2Mqtt) A Zigbee publish error occured for device '0xec1bbdfffe85d726' with error message: Publish 'set' 'state' to '0xec1bbdfffe85d726' failed: 'Error: Command 0xec1bbdfffe85d726/1 closuresWindowCovering.upOpen({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47566 - 1 - 223 - 258 - 11 after 10000ms)'
> 2021-09-29 09:50:04.560 Error: SQL Query("SELECT ID, Name FROM DeviceStatus WHERE (HardwareID=3 AND DeviceID='00082243' AND Unit=1 AND Type=243 AND SubType=31)") : no more rows available
> 2021-09-29 09:50:12.112 Error: Zigbee2Mqtt: (Zigbee2Mqtt) A Zigbee publish error occured for device '0x680ae2fffe1ab271' with error message: Publish 'set' 'state' to '0x680ae2fffe1ab271' failed: 'Error: Command 0x680ae2fffe1ab271/1 closuresWindowCovering.upOpen({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))

**Comment by gizmocuz** [comment]
No idea what this error is, but it's not a Domoticz issue.
About zigbee2mqtt or zwavejs2mqtt , please use our normal MQTT plugin and in the auto discovery topic enter 'homeassistant' or the topic that zigbee2mqtt or zwavejs2mqtt are publishing too. There is no need for a extra plugin anymore

**Comment by peteralm097** [comment]
I have stopped using the zigbee2mqtt plugin and started using the MQTT plugin as suggested by @gizmocuz - thanks!
The SQL errors have also stopped on or about the same time. :-)

**Comment by odelma** [comment]
> I have stopped using the zigbee2mqtt plugin and started using the MQTT plugin as suggested by @gizmocuz - thanks! The SQL errors have also stopped on or about the same time. :-)

Any tips for the transtion - did you have many devices?
