### ISSUE TITLE
Autodiscovery creates zigbee device with ID -> 0000

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#4940]
It would be nice if the '0000' ID's would contain also the zigbee address like other devices.
![20 09 2021_14 49 41_REC](https://user-images.githubusercontent.com/24824113/134005273-c937d786-b186-4284-85ed-fb9f83795895.png)
The ?? behind 18866 should be a real unit. (lumen??? or candela???)

A lot of devices are created, but not all. Where can I leave my remarks on not/wrong created devices?
Issue per remark or bundled?

**Comment by gizmocuz** [comment]
This is already solved in the latest code, but a beta version was not yet available.
Should be there now ;) (13501+)

Regarding the 18866 sensor, probably the "config" of this sensor does not contain a measurement unit ?
You can see this using (for example) MQTT Explorer

Please join us on Slack (mqtt_autodiscovery channel)

https://join.slack.com/t/domoticz/shared_invite/zt-v59e0d7p-WyEFkNwAsIt2u1_FmI53zA
