### ISSUE TITLE
Apply Settings button half white - long existing cosmetic bug

### ISSUE THREAD

**Issue by baahver** [domoticz/domoticz#4949]
The save settings, or apply settings button (Bewaar instellingen knop) on the settings page, changes to half white when you hover it. This small cosmetic bug is in there for a very long time. Not a real problem, but maybe someone can inspect this and propose a fix.
![Domoticz-Bewaar-instellingen](https://user-images.githubusercontent.com/49638791/135436461-432a63af-23f2-4e1b-a4c7-38439bdd09e5.png)
![Domoticz-bewaar-instellingen-bug](https://user-images.githubusercontent.com/49638791/135436464-b03a31d5-577e-4dc4-9431-4ab8c6694fde.png)
I tried to inspect this, but this is far beyond my knowledge.

**Comment by rrozema** [comment]
Reported on and more details in [the forum](https://www.domoticz.com/forum/viewtopic.php?f=6&t=37088&sid=6e0170c71ce65c6060da7749a5ade5b8).

**Comment by kiddigital** [comment]
Fix part of PR #4942
