### ISSUE TITLE
Add button missing from Settings/Hardware screen after updating to 2021.1 (rel and beta)

### ISSUE THREAD

**Issue by fwfreak** [domoticz/domoticz#4953]
RasPi4 + Aeotec Gen5+

Version: 2021.1 (build 13669)
Build Hash: f30dc726c
Compile Date: 2021-10-01 09:47:35
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

Following this update, selecting Settings/Hardware shows the usual page for adding hardware, but there is no Add button at the bottom of the work area.  Choosing different types (OpenZWave, Generic sysfs GPIO, etc.) has no effect; Add button is always missing.  Note that Add button is present in Settings/More options/User variables.

This issue presents in both Release and Beta.

**Comment by gizmocuz** [comment]
The 'Add' button is at the bottom of the page ? (Where you also have to fill in the hardware parameters)

**Comment by kiddigital** [comment]
Can be closed, see forum topic.. browser caching issue
