### ISSUE TITLE
No temperature/utility graphs since a day or two.

### ISSUE THREAD

**Issue by dobber81** [domoticz/domoticz#4957]
Running 13682. Graphs are broken since a day or maybe three.
I've tried on my regular setup as well as my test setup. Same result. Both running their own database.
Browser cache cleared and same thing with both firefox and chrome.
No errors in domoticz log.

I think perhaps this change caused it? https://github.com/domoticz/domoticz/pull/4954

**Comment by dobber81** [comment]
My test setup showed graphs after waiting a while. Maybe this is a local issue on my side.

**Comment by dobber81** [comment]
Not sure, but I don't think this is a local issue. As soon as I revert back to 13515 the graphs are back again. same db.
As soon as I go up to 13682 graphs are gone.

**Comment by michahagg** [comment]
That's weird! You did clear your browser cache, what is mostly what fixes the problem. I assume you also did Ctrl-Shift-R to completely refresh the page in the browser.

What does the browser console say? Any errors in the domoticz.log?

**Comment by dobber81** [comment]
They are back now! Updated to 13689 and all is good. On 13682 I tried chrome and firefox and at least in chrome I did clear all cache including ctrl+shift+r and also incognito mode. Nothing worked except returning to older version.
I'm closing this ticket now.
