### ISSUE TITLE
Timers with Led dimmer

### ISSUE THREAD

**Issue by devrosx** [domoticz/domoticz#4959]
Hello, 
im using latest beta version and noticed that my Led dimmer (Color Switch, RGBWW, Dimmer)
Timer works only when is set ON 100% or OFF 0%, when i set percent in level check box nothing happens...
here is log with sheduled commad... (looks like action is triggered but without command)

2021-10-06 23:13:48.308 Status: EventSystem: Script event triggered: /home/pi/domoticz/dzVents/runtime/dzVents.lua
2021-10-06 23:14:01.592 Status: Schedule item started! Name: komoda_pasek, Type: On Time, DevID: 1798, Time: 2021-10-06 23:14:01

thanks Jan

**Comment by waltervl** [comment]
Perhaps also add what kind of hardware is managing the Led dimmer (eg MQTT, Python Plugin, native hardware).
Do you see the same issue with a dummy device? Be aware to have a few minutes left between current time and to be triggered time in order for the eventsystem to set all values correctly.

**Comment by devrosx** [comment]
Thanks for reply tested it and indeed on dummy device it works fine....
My device is Zigbee2MQTT (Zigbee USB Mini LED Controller RGB+CCT)

**Comment by waltervl** [comment]
Then I would suggest to make an issue in the zigbee2mqtt github.
 It also could be a Python Framework issue but that will be decided there.

**Comment by devrosx** [comment]
noticed one more weird thing when testing...
check this video first is dummy device (slider works normally as expected), but with zigbee2mqtt value is not stored (only ON and OFF)
But when i open detailed color wheel it works ok

https://user-images.githubusercontent.com/13789041/136629134-e56acb31-8923-4465-b520-18652ae76bf3.mov

looks like this bug is same as https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/714

**Comment by devrosx** [comment]
update: with latest changes timers with dimmers works again (thanks :), but seccond bug with slider jumping (visible in video  Untitled.mov) i still visible...
