### ISSUE TITLE
Need to add "index.html" to path

### ISSUE THREAD

**Issue by kofec** [domoticz/domoticz#4960]
I'm using domoticz on Openwrt 21_02. Probably after the commit: https://github.com/domoticz/domoticz/commit/07e0c125ac314bec3f62f4c4c290ba7f1c90902c
I have to add "index.html" so the full path is eg:
http://192.168.1.35:8080/index.html#/About
Before it was:
http://192.168.1.35:8080/#/About

If I don't add "index.html" the website is not "interpreted" and I see code like:

```
<!DOCTYPE html>
<html manifest="html5.appcache">
<head>
		<meta charset="utf-8">
		<title>Domoticz</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">

		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="description" content="">
		<meta name="keywords" content="">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="shortcut icon" href="favicon.ico">
		<link rel="apple-touch-icon" href="images/iphone-icon.png">
		<link rel="icon" sizes="196x196" href="images/logo.png">
		<link rel="icon" sizes="192x192" href="images/logo192.png">
...............................
i18n="Logout">Logout</span></a></li>
				</ul>
			</div>
		</div>
	</div>
	<div id="holder">
		<div class="container-fluid">
			<div alertarea></div>
			<div id="notification" style="display: none;"></div>
			<div class="bannercontent">
				<div id="main-view" ng-view></div>
			</div>
			<div id="copyright" style="display: none;" has-User>
				<p>&copy; 2012-{{currentyear}} Domoticz | WWW: <a href="http://domoticz.com/" target="_blank">Domoticz.com</a></p>
			</div>
		</div> <!-- /container -->
	</div>
</body>
</html>
```

The issue is seen on latest version:
About Domoticz
Version: 2021.1 (build 13690)
Build Hash: 96ca6028
Compile Date: 2021-10-06 08:48:51
dzVents Version: 3.1.8
Python Version: 3.9.7 (default, Feb 16 2021, 08:53:24) [GCC 8.4.0]

Uptime: 5 Minutes, 50 Seconds

**Comment by kiddigital** [comment]
@kofec , I think that you are probably right about the issue being caused by the commit you mentioned.

I guess it is _Openwrt_ specific as it seems to work fine on most other OS'es.

The codeline 293 (in webserver/request_handler.cpp)
```
  if ((iStat == 0) && ((sb.st_mode & S_IFDIR) == S_IFDIR))
```
is most likely the culprit somehow.

Either the _stat_ function (on line 292) gives a different result than expected on Openwrt or the mode flags are different.

Are you able to build Domoticz for Openwrt yourself? Otherwise it is not easy to debug this.

**Comment by kiddigital** [comment]
@kofec , scratch the above (probably) as the output is actually the content of the _index.html_ file, so it is correctly found and added when needed.

Seems something with the (Angular)routing not working as expected.

Make sure it is not a cache issue. Run the app with active browser developertools and disabled buffering so everything gets freshly loaded each time.

**Comment by kofec** [comment]
Hi,
Yes, I'm able to build by myself. If you want you can take a look:
http://kofec.no-ip.info:58001/
http://kofec.no-ip.info:58001/index.html#/Dashboard

**Comment by kiddigital** [comment]
Hi @kofec , thanks for the possibility to take a look.

I get the same result as you describe and I also think I found the reason. If you look at the response headers when requesting your page, you get the following headers:

```
HTTP/1.1 200 OK
Last-Modified: Tue, 16 Feb 2021 08:53:24 UTC
Content-Length: 74645
Access-Control-Allow-Origin: *
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Type: ;charset=UTF-8
Connection: Keep-Alive
Keep-Alive: max=20, timeout=20
```

Which looks ok, but 1 vital header is wrong and should be something like: `Content-Type: text/html;charset=UTF-8`

That is why the browser is showing you the content of the _index.html_ file instead of interpreting it (which it should do).

Not sure why the `Content-Type` header is wrong, but that seems to be the issue here. Might it have something to do with the use of 'no-ip.com' tunnel? Can you check locally if the header is present internally when requesting the same from Domoticz?

When I test it with my installation, I do get this header returned correctly as it should.

**Comment by kofec** [comment]
I check this like shown here:
https://java2blog.com/how-to-view-http-headers-google-chrome/
```
Access-Control-Allow-Origin: *
Connection: Keep-Alive
Content-Length: 74645
Content-Type: ;charset=UTF-8
Keep-Alive: max=20, timeout=20
Last-Modified: Tue, 16 Feb 2021 08:53:24 UTC
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
```

**Comment by kiddigital** [comment]
@kofec , thanks. I think it is more clear now as I suspect that the _Openwrt_ version does not support _gzip_ compression output.

When looking at the code, I think there might be an issue for those cases. I will look if I can make a fix and let you know when I have a branch ready for you to test.

**Comment by kofec** [comment]
I remove the change provided by mentioned commit:
```
--- domoticz-96ca60285f94e28c23b9a805453267f810badae0.orig/webserver/request_handler.cpp
+++ domoticz-96ca60285f94e28c23b9a805453267f810badae0/webserver/request_handler.cpp
@@ -289,28 +289,9 @@ void request_handler::handle_request(con
          }
          // maybe it is a folder, lets add the index file
          struct stat sb;
-         int iStat = stat(full_path.c_str(), &sb);
-         if ((iStat == 0) && ((sb.st_mode & S_IFDIR) == S_IFDIR))
+         if (!is.is_open() && stat(full_path.c_str(), &sb) == 0 && (sb.st_mode & S_IFDIR))
          {
-                 // Even a Directory can be 'opened', so close it first before we look for a different file
-                 if (is.is_open())
-                 {
-                       is.close();
-                 }
-
-                 // If path ends in slash (as it is a directory) then add "index.html".
-                 if (request_path[request_path.size() - 1] == '/')
-                 {
-                   full_path = doc_root_ + request_path + "index.html";
-                 }
-                 else
-                 {
-                       // Directory requests should end with a / otherwise the browser will get confused with relative paths
-                       // So we don't add the index.html here but report 400
-                       rep = reply::stock_reply(reply::bad_request);
-                       return;
-                 }
-
+                 full_path = doc_root_ + request_path + "/index.html";
                  if (bHaveGZipSupport) // first try gzip version
                  {
                          full_path += ".gz";
@@ -325,7 +306,7 @@ void request_handler::handle_request(con
                  }
                  else if (bHaveGZipSupport) // try uncompressed version
                  {
-                         full_path = doc_root_ + request_path + "index.html";
+                         full_path = doc_root_ + request_path + "/index.html";
                          is.open(full_path.c_str(), std::ios::in | std::ios::binary);
                  }

```
And now I have without index.html:
404 Not Found

**Comment by kofec** [comment]
So maybe this commit it was:
https://github.com/domoticz/domoticz/commit/567f3491343070e9e9878a74cb9ffce0f1bed26e

**Comment by kofec** [comment]
Here you can find the Makefile for openwrt:
https://github.com/openwrt/packages/blob/master/utils/domoticz/Makefile

**Comment by kofec** [comment]
Do you suspect which commit might be causing the problem?
you mention about compression in openwrt Makefile we have:
```
	# compress static web content
	find $(1)/usr/share/domoticz/www -name "*.css" -exec gzip -9 {} \;
	find $(1)/usr/share/domoticz/www -name "*.js" -exec gzip -9 {} \;
	gzip -9 $(1)/usr/share/domoticz/www/*.html
	gzip -9 $(1)/usr/share/domoticz/www/secpanel/*.html
	find $(1)/usr/share/domoticz/www/views -name "*.html" -exec sh -c 'grep -q "<\!--#embed" {} || gzip -9 {}' \; 
```

**Comment by kiddigital** [comment]
Give it a try with a uncompressed index.html file (so after the make install, manually gunzip the www/index.html file)

So it might even be the other way around :) _Openwrt_ does support compressed output and actually works with compressed input :) Maybe there is an issue with that particular part.

When I have a little more time, I will see if I can test and verify these cases.

**Comment by kiddigital** [comment]
@kofec , I just tested the reverse (zipping the index.html file) and got the same problematic result (missing content-type).

So using a compressed index.html file as input currently does not function as it should.

Will try to fix and refactor parts of the code hopefully over the weekend and prepare a fix and PR.

**Comment by kofec** [comment]
Thanks a lot for your help.
Do you suspect which change in the code introduce this issue/change.
I compile the code once every month or two and it was fine previously

**Comment by kiddigital** [comment]
Quite sure that the changes done by PR #4942 are the reason.

**Comment by waltervl** [comment]
For the docker version there also seems to be an issue with theme processing https://www.domoticz.com/forum/viewtopic.php?p=280535#p280535

**Comment by kofec** [comment]
@kiddigital 
I have generated patch from your "pull request"
https://patch-diff.githubusercontent.com/raw/domoticz/domoticz/pull/4962.patch
And it looks like it is OK. Thanks a lot again
If you would like to take a look to my setup(with your changes) the above links are still active

**Comment by kiddigital** [comment]
@kofec , good to hear! And thx for testing. Also looking at your link, I found a small mistake (charset=UTF-8 is added twice) which is now fixed in the PR

**Comment by kiddigital** [comment]
@kofec , assuming everything (still) works now as expected, can you close this issue?

**Comment by kofec** [comment]
Sure. Thanks
