### ISSUE TITLE
Python 3.10 is not supported.

### ISSUE THREAD

**Issue by mbroek** [domoticz/domoticz#4967]
Python version 3.10 is not supported. 
domoticz: PluginSystem: Failed dynamic library load, install the latest libpython3.x library that is available for your platform.

This was just after the upgrade of Python 3.9 to 3,10 on my system.
Cheating with a link /usr/lib64/libpython3.9.so -> libpython3.10.so.1.0 will produce the following log:

PluginSystem: Invalid Python version '3.10.0' found, '3.4.0' or above required.

OS: Slackware current development version.

**Comment by dnpwwo** [comment]
Hi @mbroek,

I didn't know Python 3.10 was out yet so you are definitely ahead of the curve :)

I can push an pdate to Domoticz so the library will load but that does not mean that it willactually function correctly.  New versions often require a number of tweaks, do you really need to run a version that is only 8 days old?

**Comment by mbroek** [comment]
Hello @dnpwwo

Not really, it is not my production machine for domoticz but a test server. I just happen to run the latest Slackware testbuilds which has a warning about the problems that could arise for some programs. 

If there is an update available I can test if it works, but I doubt if it will be a complete test for all the python functions.

**Comment by svde** [comment]
Same on my system, fedora 35 has python 3.10.

**Comment by svde** [comment]
For fc35 and higher I put this patch into my build:

```
--- domoticz-2021.1.13851/hardware/plugins/PluginManager.cpp.orig       2021-11-06 17:22:08.338441362 +0100
+++ domoticz-2021.1.13851/hardware/plugins/PluginManager.cpp    2021-11-06 17:22:30.115606718 +0100
@@ -31,7 +31,7 @@
 #include "DelayedLink.h"
 #include "../../main/EventsPythonModule.h"

-#define MINIMUM_PYTHON_VERSION "3.4.0"
+#define MINIMUM_PYTHON_VERSION "3.10.0"

 #define ATTRIBUTE_VALUE(pElement, Name, Value) \
        { \
```

As this (in hardware/plugins/PluginManager.cpp) thinks that 3.10.0 is smaller than 3.4.0:

`if (sVersion < MINIMUM_PYTHON_VERSION)`

It'll try to start domoticz but crashes:

```
domoticz[990635]: 2021-11-07 01:18:59.958  Status: PluginSystem: 2 plugins started.
domoticz[990635]: Fatal Python error: Segmentation fault
domoticz[990635]: Current thread 0x00007f51327fc640 (most recent call first):
domoticz[990635]:  <no Python frame>
domoticz[990635]: Extension modules: Domoticz (total: 1)
```

**Comment by dnpwwo** [comment]
Unfortunately it looks like I was correct and we will need to do some more tweaking :(

I will try and find some time to look at this.

**Comment by svde** [comment]
I tried to create a venv with python 3.9.8, but that doesn't work either:

`domoticz[354188]: 2021-11-08 11:43:26.938  Status: EventSystem - Python: Failed dynamic library load, install the latest libpython3.x library that is available for your platform.`

The installed package was built against python 3.10.0, and doesn't see the 3.9.8 version in the venv. I'll try building the package in the context of that user + its venv.

**Comment by svde** [comment]
Updated my test system to fc35, installed a modified domoticz package (with the patch mentioned above) so python 3.10.0 will run. No problems so far. It only crashes when I installed and configured the Shelly_MQTT plugin. When it tries to connect to mqtt it crashes. I think this isolates the crash to the Shelly_MQTT plugin.

**Comment by lolomin** [comment]
Hi,

Using Fedora 35 for now a few days and my domoticz is now unusable since many plugins are not working anymore :/
Does the python 3.10 support will be available soon please ?
Did not succeed to get it working with the patch provided by svde commented on 7 Nov.
Is there something more to do to get it working please ?

Regards,

Laurent

**Comment by svde** [comment]
I'm running domoticz in a docker container now. Problem solved :-)

**Comment by gizmocuz** [comment]
Yep that solves it

**Comment by lolomin** [comment]
Thks for these informations but can't make XiaomiGateway work within Docker :
https://www.domoticz.com/forum/viewtopic.php?f=68&t=36541 so this is a stop for me at the moment as I have a lot of devices under this Gateway :/

**Comment by dnpwwo** [comment]
I did an initial test with Python 3.10.

- Building against Python 3.9.x includes is successful
- Late link load of the library is successful
- Python interpreter creation is successful
- Consistent crash when attempting to create the Python Event module

Next will be to try and build against Python 3.10 includes.  If this solves the issue it will mean that late linking is broken for 3.9 and 3.10

EDIT: Problem still remains even when using the 3.10 headers.  Python is complaining that the GIL (Global InterLock) is not held when creating the module which seems unlikely.  Curently looking at resolving this using the Python [Stable Application Binary Interface](https://docs.python.org/3/c-api/stable.html#stable-abi-list)

**Comment by svde** [comment]
This issue was mentioned here: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/689#issuecomment-998316917

**Comment by waltervl** [comment]
Could be fixed in latest beta with commit https://github.com/domoticz/domoticz/commit/8f01ed77d5831090f34ad59d22ef1f7cd4d740f2 But try out in a beta environment first as it is early beta changes.

Please report issues in https://www.domoticz.com/forum/viewtopic.php?f=6&t=38086

**Comment by waltervl** [comment]
@mbroek Please check latest beta
