### ISSUE TITLE
Device logs missing

### ISSUE THREAD

**Issue by drfranky1** [domoticz/domoticz#4969]
Domoticz version: 2021.1(build 13703)
dzVents version: 3.1.8
python: 3.7.3

Hello I have an issue with the devices log.
I am using zigbee2mqtt and aquara motion and switch sensors and when I click Log on some device I see "No data available in table" but temperature sensors working normal.

I tried everything but nothing help.

![image](https://user-images.githubusercontent.com/92476754/137202794-c0de2724-f7a0-4555-8c3a-2a6ea6d793a6.png)

Can you please help me to solve that issue?

Thank you in advance

**Comment by hughb8on** [comment]
I've noticed the same thing, and not just with motion sensors, my lights and switches also only show a "Text log" like the example you provided.
I'm in the process of moving over to using native Domoticz MQTT for zigbee2mqtt and I see logs are displayed correctly for those devices. This suggests to me that the problem is probably in the plugin, not in Domoticz.

**Comment by drfranky1** [comment]
I will try this evening what will be the result if switch the MQTT and will let you know.
Thanks for the help.

**Comment by drfranky1** [comment]
I forget to tell that I can see the data in the database that's why I think the issue is in Domoticz because can't show it.

**Comment by odelma** [comment]
I can confirm the same issue with Python (DomoticzEx Framework) managed devices. On other device I can see the log still.

**Comment by gizmocuz** [comment]
This will be resolved when using the beta with MQTT and the auto discovery topic, so you can use it natively

**Comment by waltervl** [comment]
> 
> 
> This will be resolved when using the beta with MQTT and the auto discovery topic, so you can use it natively

When other plugin writers  (eg Zigate) decide to use DomoticzEx Framework this should be solved.

**Comment by odelma** [comment]
I think the plugin authors need to update also logging in their plugins when starting to use DomoticzEx. Ref: 

> ”This same logic applies to logging as well.
> 
> Not all device types have logs written the same way in Domoticz so I added 'Log' parameter to the Update function to allow plugin authors to force an entry.”

https://www.domoticz.com/forum/viewtopic.php?p=280998#p280998

**Comment by waltervl** [comment]
duplicate of https://github.com/domoticz/domoticz/issues/5000 and closed
Solved by update in plugin.
