### ISSUE TITLE
MQTT: Domoticz does not publish UserVariable changes.

### ISSUE THREAD

**Issue by nayrnet** [domoticz/domoticz#497]
I would like to interact with Domoticz Scripts via MQTT and UserVariables, but it does not seem that this information is relayed via MQTT.. I can publish a UserVar to domoticz/in but Domoticz its self does not publish them to domoticz/out

obviously, we dont want a subscription in to trigger a publish out, but for all other updates to a UserVar yes.. it would be extremely useful.

example usage: I'd like IPCameras to change from day/night profile based upon a UserVar and not a Virtual Switch.. Or store configuration details for a MQTT App in a UserVar, such as a list of IDX for Specific devices so configuration could be done completely through UI without editing a config file and restarting the external integration.

**Comment by sweetpants** [comment]
I don not exactly understand what you trying to acomplish, but I recently changed MQTT to also publish the description field of the device on domoticz/out. For my switches I put in there the ESP8266 device_id so I can use an universal script to switch on/off switches. I do not have to touch the script again when I add a device to Domoticz, just put in the device_id in the description field

**Comment by gizmocuz** [comment]
@nayrnet , Ryan, is this still an issue/wanted implementation, or can you work with sweetpants method ?

**Comment by gizmocuz** [comment]
No feedback, closing issue
