### ISSUE TITLE
Deleting more then one z-wave device in a row crashes Domoticz

### ISSUE THREAD

**Issue by Sarcas666** [domoticz/domoticz#4970]
2021.1 (build 13703) running on rPi4 Buster

Deleting more then one z-wave device in a row crashes Domoticz. It has been that way for a long time, I assumed it was a known problem.

**Comment by pipiche38** [comment]
+1

**Comment by Dylantje** [comment]
I think this not only the zwave problem. In my opion this is with all the sensors i want to remove

**Comment by gizmocuz** [comment]
That seems correct... could be caused by a database lock

**Comment by waltervl** [comment]
I can delete multiple dummy sensors without crashing. I can delete 10 devices (active and inactive) of an active Python plugin without issues.
All executed on build 14251
