### ISSUE TITLE
Version 13724 crashes on Raspberry Pi,

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#4977]
Yesterday I installed this latest beta. The first update on a Raspberry Pi 1B, with an almost empty database (only motherboard sensors and mqtt installed) went without a problem. The second update on a Raspberry Pi 2B failed and it was impossible to start Domoticz. 

Since then several other users reported the same problem.

Reports and crash logs you will find at: https://www.domoticz.com/forum/viewtopic.php?p=281018#p281018

**Comment by gizmocuz** [comment]
Thank you for reporting this!
I created 4 pull requests, I suspect one of these will testing this issue
Is it possible to check this?

**Comment by Dylantje** [comment]
hi same errors here on the N2 with armbian.. 
what can i test?

Perhaps an idea to set in the wiki how to go back to a previous branche?
 Now a not working system .. waf mad max 🙈🤭🤭🤭

**Comment by kiddigital** [comment]
Please check if you have any python plugins and/or scripts in the scripts directory (even if you don't use them). Just move them outside of the directory and try again. I found similar crashes (already with beta 13682) that seem to happen irregular but quite fast after starting.

Will investigate further when time allows.

**Comment by Dylantje** [comment]
Ok i try.. I have two systems master and slave.. do you know how i can go back to previous branche... Then i can run my master and test with the slave

**Comment by waltervl** [comment]
> Ok i try.. I have two systems master and slave.. do you know how i can go back to previous branche... Then i can run my master and test with the slave

See https://www.domoticz.com/wiki/Raspberry_Pi#Revert_to_backup_after_incorrect_beta_update.

**Comment by dnpwwo** [comment]
@kiddigital,

The crashes in the linked thread are not Python related if you have a look at the crash dumps.

One seems to be in the 'main' thread and the other is in Notification handling.  C++ and Python Plugin hardware can both trigger notifications and I have seen identical crashes from both types (posted in the thread)

**Comment by Dylantje** [comment]
Hi guys..
Is there perhaps a solution?

**Comment by waltervl** [comment]
Short term solution is to go back to the latest working beta. See my comment on your post earlier.

**Comment by peteralm097** [comment]
Interestingly it ran all night and only crashed when someone opened a door first thing (which sends a notification)

**Comment by gizmocuz** [comment]
A new beta is building (17377) this beta reverts the 4 recent c++ changes.
Building could take up to two hours.
Hope this solves the issue

**Comment by Dylantje** [comment]
> A new beta is building (17377) this beta reverts the 4 recent c++ changes. Building could take up to two hours. Hope this solves the issue

Thanks for the great work!!!
Hope this works..

**Comment by gizmocuz** [comment]
Update should now be available

**Comment by Dylantje** [comment]
Updated, running better then yesterday:-) 
![image](https://user-images.githubusercontent.com/5214969/137621638-dc68d920-be56-4575-b7be-e98c78fc685b.png)
Yesterday not run for 1 minute:-)

**Comment by Jake1964** [comment]
Works for me (v13733), no more issues with crashes after issued notifications. Thanks!

**Comment by gizmocuz** [comment]
Thanks for the feedback. Wondering which of these 4 merged PR's are causing the crash..
Choosing issue. If possible mention the new beta on the forum

**Comment by SargonofAssyria** [comment]
Could this also have positive influence on my problem? https://github.com/domoticz/domoticz/issues/4881

**Comment by gizmocuz** [comment]
Could be related. This crash had to do with the most recent merged 4 pull requests... About your ZigBee, please use the in build support (MQTT) but that is unrelated to this issue and should not be discussed here

**Comment by SargonofAssyria** [comment]
Tnx. Ok, too bad.

**Comment by gizmocuz** [comment]
I edited my response after looking at your last message on that thread
