### ISSUE TITLE
Memory leak HTTP(S)

### ISSUE THREAD

**Issue by Rimco** [domoticz/domoticz#498]
I'm at the moment suffering from a memory leak for quite some time. Main problem is that after some time the web interface becomes unreachable, although domoticz is still running (partially).

I suspect I'm one of the few users using Evohome, so I'm suspecting something is wrong in that area.

I've attached a log where you can see the problem starting and in the end monit deciding to restart it.

![memory](https://cloud.githubusercontent.com/assets/3317143/13175647/3adb7cb6-d70c-11e5-91af-76893d63a626.png)
[memory log.txt](https://github.com/domoticz/domoticz/files/137925/memory.log.txt)

Let me know how I can help analyzing this issue, I have some valgrind experience and I can also see what happens when I stop some hardware, but because the system is used daily, I cannot just stop stuff for prolonged periods.

**Comment by gizmocuz** [comment]
Could you stop using evohome for a few days and see if that solves the problem ?

**Comment by Rimco** [comment]
Just stopped evohome and will keep an eye on the graph. I should be able to see quickly if usage is rising or not.

**Comment by Rimco** [comment]
Without Evohome I still see the same increase in memory usage, any other suspects?

![memory2](https://cloud.githubusercontent.com/assets/3317143/13181650/628913b4-d72e-11e5-8e01-6f192abca4a0.png)

**Comment by gizmocuz** [comment]
disable all hardware
if this does not work, then close domoticz
monitor your memory usage via console, as it might not be a domoticz issue

**Comment by Rimco** [comment]
Because disabling all HW would result in quite some impact, I'll disable them selectively.
I know for sure the memory leak must be in domoticz because restarting it actually frees up the memory again.
I'll let you know when I find out more.

**Comment by Rimco** [comment]
I ended up disabling all hardware and cameras, still the memory usage for the domoticz process is increasing according to top. Anything else I can try?

**Comment by gizmocuz** [comment]
And you are still convinced it is a Domoticz issue ?
Disable the event system if you use events
can you monitor the domoticz process with 'top' or 'htop' ? (for memory problems)

**Comment by Rimco** [comment]
I was monitoring domoticz with 'top', also why I could see it was actually domoticz increasing in memory usage. Let me try disabling events, I have blockly and lua events.

**Comment by gizmocuz** [comment]
do you have also external scripts that talk to domoticz ?
What version are you using? Which platform ?
Did valgrind say anything?

**Comment by Rimco** [comment]
There is one external script sometimes updating a device, but this only makes a connection once every couple of hours.
However, I just spotted a previous domoticz instance on another system was still configured to use the current one (with the memory issue) as slave. I also stopped that now to see if that was responsible for the memory increase.
Running beta of last week, V2.4460, hash 0a7b4cd. Running on RPi 2B with Raspbian Jessie.
Valgrind could not start domoticz because it reported it was using an instruction that is not supported.

**Comment by gizmocuz** [comment]
I think with a command parameter you can let valgrind continue

**Comment by gaudryc** [comment]
What you are monitoring is the whole system memory usage, isn't it.
If you are running another process on your system, the graph will show the increase of memory (especially if you make some compilation...). 
To see if you have a memory leak, you should see the memory usage of the domoticz process from a system report (like top under raspberry and watch for resident memory + virtual memory).

About Valgring, under Debian Wheezy, I had the same issue a few month ago (see #176).

**Comment by Rimco** [comment]
Thanks for your input, but I used 'top' to monitor the memory usage of the
domoticz process alone.

**Comment by gizmocuz** [comment]
Looking at the screenshot you posted in your first post, it looks like the memory goes to 75+ percent in 5 minutes each 12 or 24 hours
You mention "an external script  that connects once every couple of hours"
When you stop this script, how is the memory usage ?

(maybe it was easier to just take another system, install domoticz (no configuration/hardware) and monitor this

**Comment by Rimco** [comment]
The external script is not running on this system, but on another system.
This system is clean Raspbian Jessie + Domoticz + monit. Monit I had to install because of this issue.
Here are two screenshots proving it is the domoticz process taking up more memory (2 hours time delta):

![start](https://cloud.githubusercontent.com/assets/3317143/13196993/36cabd88-d7e0-11e5-86eb-1e9038b15873.png)
![end](https://cloud.githubusercontent.com/assets/3317143/13196994/3a435a10-d7e0-11e5-8585-318521bd68a7.png)

This is without the event system, but all hardware enabled again.

**Comment by gizmocuz** [comment]
why ?

okey, if you have a spare system, just install domoticz, and let it run and monitor the memory

**Comment by gizmocuz** [comment]
Sure if the memory goes above 80% each day we would have lots of complaints right ?

**Comment by Rimco** [comment]
Let me check for a bit what happens with a clean database

**Comment by gaudryc** [comment]
Do you use both HTTP and HTTPS ports in domoticz ?

**Comment by Rimco** [comment]
Yes: /home/pi/domoticz/domoticz -daemon -wwwbind 0.0.0.0 -www 8080 -sslwww 443 -sslcert /home/pi/domoticz/combined.key -log /tmp/domoticz.txt

**Comment by gaudryc** [comment]
Do you download files from domoticz ?

**Comment by Rimco** [comment]
No, nothing is currently connecting at all.

**Comment by gaudryc** [comment]
You don't have any "Incoming connection ..." in the domoticz.log but the memory still grows ?

**Comment by Rimco** [comment]
I have one entry from my browser. Currently the clean domoticz instance increased from 1.4% to 1.8% in 20 minutes.
In the clean instance I did add dummy and MB sensor HW.

**Comment by Rimco** [comment]
Could it be related to running HTTPS or the -log option?
I can actually vaguely remember omitting the -deamon option at some point improved the stability.

**Comment by gaudryc** [comment]
I ask you this because I made a refactoring on HTTP(S) reply management last week (more recent than your version V2.4460, 0a7b4cd), and I've seen that the memory was less used.

**Comment by gizmocuz** [comment]
How much memory do you have ?
Domoticz will cache up to 300 log lines, which should not be that much, but you will see a light increase of the memory, and then it should be kind of stable

**Comment by Rimco** [comment]
Total memory is 1GB and for this test I started with a clean install from http://domoticz.sourceforge.net/domoticz_linux_armv7l.tgz. So far: 1.4% to 2.3% in a bit less than 1 hour.

**Comment by Rimco** [comment]
So the memory increased from 1.4% to 2.8%. I now also deleted the 2 hardware devices again, so let's see how this is going to behave.

**Comment by gizmocuz** [comment]
As mentioned above, just install domoticz on another system, do not add hardware (only the motherboard/system hardware) and let it run
(do not install it on the same system)

**Comment by rkluwen** [comment]
By chance are you using MyDomoticz? And if yes, does the problem persist when you disable it?

**Comment by Rimco** [comment]
The current RPi is the only system which is running an Evohome compatible OS. I had it running on FreeBSD before without problems, but it was also no daemon and no Evohome.

However, I can make an image of the RPi SD card and start really from scratch with a clean raspbian install. I don't think broken HW could cause these symptoms.

@rkluwen; I'm not using MyDomoticz at all.

Because memory usage is still increasing without any HW after a clean install I'm going to check the daemon option and/or HTTPS options.

**Comment by Rimco** [comment]
Even after a complete clean install, I still see an increase. To reproduce:
- Use RPi 2B
- Get NOOBS_v1_5_0 and install Raspbian
- Reboot and execute:
- mkdir ~/domoticz
- cd ~/domoticz
- wget http://domoticz.sourceforge.net/domoticz_linux_armv7l.tgz
- tar xvfz domoticz_linux_armv7l.tgz
- rm domoticz_linux_armv7l.tgz
- Put a valid SSL key/cert in the domoticz folder as combined.key
- Execute: ./updatebeta
- Execute: sudo /home/pi/domoticz/domoticz -daemon -wwwbind 0.0.0.0 -www 8080 -sslwww 443 -sslcert /home/pi/domoticz/combined.key -log /tmp/domoticz.txt

Using this, I see an increase of more than 1% per hour.

**Comment by Rimco** [comment]
After removing the https related command line options, the increase is finally gone.
Let me see what happens after I also put back my database...

**Comment by gaudryc** [comment]
Can you try also with an earlier version (last beta for example) ?

**Comment by Rimco** [comment]
I'm currently running f3ad94b, which is the last beta as far as I know. Should I try last stable? I have this problem already for quite some weeks, so it can't be something introduced recently.

**Comment by gaudryc** [comment]
Did you disabled HTTPS only, not both HTTP and HTTPS ?

**Comment by Rimco** [comment]
Only removed sslwww and sslcert option, still running http and connected to it using my browser.

**Comment by gaudryc** [comment]
Are you sure you don't have any connection on HTTPS port ?
If you enable HTTPS again, could you see the result of the command "netstat -an|grep 443" ? How many connections are reported ?

Because last week I saw 98 connections from my box to the HTTPS port of domoticz.
After rebooting my raspberry : 97 connections.
After rebooting my box : 1 connection (from my computer).

**Comment by Rimco** [comment]
If I leave my browser open I can see 1 connection which stays open and is sometimes replaced by a new one. Without my browser open I see no connections at all.

I'll keep it running now without HTTPS and I will double check in the morning what the memory usage did during the night.

**Comment by gizmocuz** [comment]
also make sure monit does not connects to HTTPS then

**Comment by Rimco** [comment]
Monit was not installed on the clean system, but your statement reminded me of another monitor running on another system. This was connecting every minute to domoticz with a GET for /.

During the night, the memory did not increase, so must have been related to HTTPS connections. I just switched this monitor to the HTTP port and at first sight the same is happening.

So it seems to be an issue if GET / is done quite often. Maybe this (webmin) status monitor does not clean up nicely, but at least the TCP connections get closed according to netstat.
I think something on domoticz side is not cleaned up in case the HTTP(S) connection is closed prematurely?

**Comment by Rimco** [comment]
After switching the monitor to get json.htm?type=command&param=getconfig instead of /, the memory usage is stable.

**Comment by gaudryc** [comment]
Could you tell me if the memory is growing if you execute multiple GET requests for / from the command line, using wget for example ?

**Comment by Rimco** [comment]
Requesting / the whole time using curl does not show the problem. I suspect the configuration of the monitor (ignore response, only check connection) was such that it closed the connection before the reply was sent by domoticz.

**Comment by gaudryc** [comment]
Could you please give me the monit configuration supposed to create this issue ? (only the domoticz service part)

**Comment by Rimco** [comment]
The monitor is part of webmin, so not actually monit. See http://doxfer.webmin.com/Webmin/System_and_Server_Status.

It was configured to connect to the HTTPS port, default time-out, no authentication and no regex match. After setting this to the config json URL and enabling regex for "status", the issue disappeared. This is the same configuration I'm using for the local monit service.

I still think there is a domoticz issue, but it seems only to pop-up in very specific cases. At least there is a work-around available, but if we can find out what is going wrong on the domoticz side it can be made more robust.

**Comment by gaudryc** [comment]
@Rimco 

Could you make some new test with at least the revision d7841bb ?

**Comment by Rimco** [comment]
Will try to check during the weekend:)

**Comment by Rimco** [comment]
I checked what happens if I use the old method with the latest beta and at first sight I don't see any memory increase anymore, seems you fixed it. Nice one:)

**Comment by gizmocuz** [comment]
did you have the above configuration enabled again ?
Because you said it was already solved by

"It was configured to connect to the HTTPS port, default time-out, no authentication and no regex match. After setting this to the config json URL and enabling regex for "status", the issue disappeared."

**Comment by Rimco** [comment]
I checked with the old configuration.

**Comment by gizmocuz** [comment]
Thanks, just wanted to make sure

**Comment by Rimco** [comment]
np

**Comment by gaudryc** [comment]
Good news.
Thank you
