### ISSUE TITLE
Thermostat min/max set points setting only available in android app

### ISSUE THREAD

**Issue by user8446** [domoticz/domoticz#4985]
Hello,

After adding a Z-Wave thermostat, the maximum set point available in Domoticz was 30 deg F. After excluding/including multiple times and factory defaulting the thermostat thinking it was a device issue, I stumbled upon the setting in the Domoticz mobile app to adjust the Set point min & max value for Domoticz. 

This setting is completely missing in the web portal and only adjustable from the mobile app.

Thank you.

Domoticz v 2021.1
Mobile version 0.2.320 (8513)

**Comment by gizmocuz** [comment]
There is indeed no limit in the web gui of Domoticz. I think it is also specified in the manual of your thermostat.
Do you want to have this limit removed from the mobile app ?

**Comment by user8446** [comment]
Hi,

Before adding my actual z-wave thermostats I added a dummy virtual sensor "thermostat setpoint" and that was limited to 30 deg as well in the web GUI which would point the issue to Domoticz. 

Only from the mobile app was I able to see the "Set point max value" which was indeed 30 and I was able to change it.

Wouldn't you agree it would make sense to be able to reach this setting from the Web GUI and not just the mobile app?

**Comment by gizmocuz** [comment]
In the gui popup, when you set 20, it goes to 20, and when you set it to 30, it does nothing?

**Comment by user8446** [comment]
No, it does go to 30 but that was the maximum setpoint until I changed and increased it in the mobile app.

**Comment by waltervl** [comment]
> Hi,
> 
> Before adding my actual z-wave thermostats I added a dummy virtual sensor "thermostat setpoint" and that was limited to 30 deg as well in the web GUI which would point the issue to Domoticz.
> 
> Only from the mobile app was I able to see the "Set point max value" which was indeed 30 and I was able to change it.
> 
> Wouldn't you agree it would make sense to be able to reach this setting from the Web GUI and not just the mobile app?

In latest beta I have no problem in setting the setpoint of a dummy thermostat to a temperature of more than 30 degr C 
I did not try it together with the android app

**Comment by waltervl** [comment]
Just did some more tests.
In my production environment 2021.1 stable were I also use the app I have one (native nefit easy integration) thermostat that cannot be set higher than 30 degrees. All other thermostats (dummy, python plugin controlled) can be set higher than 30 degrees from web but not in the app. I did not change the settings in the app.

**Comment by user8446** [comment]
Thank you for helping test. 
Just adding that this is 30deg F in my case. 30deg C would be enough range for most users.

**Comment by waltervl** [comment]
In my test environment I can go to 900+ degr F on a dummy thermostat.

**Comment by gizmocuz** [comment]
Don't you think 30 degrees is extreme hot and should not be able to be specified ?

**Comment by waltervl** [comment]
Depends if you want to use it for a home or for your tropical plants growing room or your terrarium :-)
But 30 degr Fahrenheit is a little bit low for normal use and that is were @user8446 had a problem with. So it seems a C/F issue on Zwave configuration ?

**Comment by gizmocuz** [comment]
Depends, Is Domoticz configured to Farenheit in the webgui/settings ?
I can't find any limiter in Domoticz itself

**Comment by user8446** [comment]
On my device, the high limit was 30deg F, 2 degrees below freezing.

You might be going in the right direction here, it might just be a Celcius / Fahrenheit issue

**Comment by waltervl** [comment]
> 
> 
> Just did some more tests. In my production environment 2021.1 stable were I also use the app I have one (native nefit easy integration) thermostat that cannot be set higher than 30 degrees. All other thermostats (dummy, python plugin controlled) can be set higher than 30 degrees from web but not in the app. I did not change the settings in the app.

Small correction, on my Nefit Easy thermostat I can fill in a value higher the 30 degr C but apperantly the Nefit Thermostat hardware (not Domoticz) has a max 30 degr C limit. So the higher value from Domoticz is ignored.

I have no Zwave devices so cannot test this. Perhaps your Zwave device also has a 30 degr C limit in the Zwave device config?

**Comment by waltervl** [comment]
When I look into a thermostat Zwave config file (for example https://github.com/domoticz/domoticz/blob/development/Config/eurotronic/eur_spiritz.xml ) I see a max 28, min 8 degr C limit.


```
<CommandClass id="67">
    <Instance index="1"/>
    <Value genre="user" index="1" instance="1" label="Heat" max="28" min="8" read_only="false" type="decimal" units="°C" value="20" write_only="false"/>
    <Value genre="user" index="11" instance="1" label="Heat Eco" max="28" min="8" read_only="false" type="decimal" units="°C" value="16" write_only="false"/>
```

**Comment by user8446** [comment]
To add, my dummy thermostat before I added real devices had a 30deg F upper limit in the GUI.

Do you think having the min/max setting available in the GUI and not just the mobile app would be a good idea?

**Comment by waltervl** [comment]
Can you make a screenshot of your Gui? Because I had no limit in setting the setpoint in degrees Celsius and Fahrenheit. Neither I would like to have one.
Do you use the default theme in Domoticz web GUI or a custom theme like Aurora or Machinon?

**Comment by user8446** [comment]
I'm on the default theme in the GUI. How does Domoticz determine C or F? By the location info? This is what it looked like:

![Screenshot 2021-10-25 141445](https://user-images.githubusercontent.com/18019245/138749224-59e78401-6401-4e3d-a0ce-e3c8e6af8876.jpg)
![Screenshot_20211025-140934](https://user-images.githubusercontent.com/18019245/138749647-84f42a9b-c016-4616-8979-1f27dc508d24.png)

**Comment by waltervl** [comment]
Setting C/F is done in menu setup - settings, tab meter/counters. I don't know if there is any additional logic in location.

I can go higher than 30 degrees C for dummy thermostat so it is strange you have this issue.
Perhaps clear your browser cache (or try out in private browser session).

**Comment by gizmocuz** [comment]
You have to set your system to Fahrenheit in the settings and I guess it should work much better
Edit: 30F = -1,1 Celsius, why would you set the thermostat to this ?

**Comment by waltervl** [comment]
>  Edit: 30F = -1,1 Celsius, why would you set the thermostat to this ?

@gizmocuz he does not want to set it to 30 degr F but to an equivalent of 30 degr C being 86 degr F. But it is not possible because somehow it is limited to 30 degr F. by Domoticz web UI. Also for Dummy devices.

@user8446 did you set Domoticz to Fahrenheit in Menu Setup Settings tab meter/counters?
If still issues,  what exact Zwave thermostat device do you use, brand and type? Is there a config file for it in the Config folder?

**Comment by gizmocuz** [comment]
Indeed you can not set it to 30 F, but you can set it to 80F
I tested with a dummy, system=Celsius, set the setpoint to 180 ... works
next I have set the system to Fahrenheit, setting the setpoint to 30 fails (it's -1 C so yeah),
but setting it to 80 works
So I suspect the system is not set to Fahrenheit

**Comment by waltervl** [comment]
Seeing the screenshots he has as it shows F instead of C

**Comment by gizmocuz** [comment]
The screenshot is from the mobile app
Edit: The upper screenshot is indeed F
Did you test with a dummy sensor ?

**Comment by waltervl** [comment]
Yes, I tested with dummy sensor. I cannot reproduce this behavior in stable 2021.1 nor beta.
But it could be related to Zwave device configuration.

**Comment by gizmocuz** [comment]
There is no limiting done by Domoticz, best to debug the function

COpenZWave::SetThermostatSetPoint

**Comment by waltervl** [comment]
Let's see what @user8446 is reporting back.

**Comment by user8446** [comment]
I have 2GIG (private labeled Radio Thermostat) CT100 thermostats. They are in the OZW device database and have a config file. If there is no limiting done in Domoticz, then this clearly lies elsewhere. Do you want me to close this and revisit it in the future if it comes up?

**Comment by waltervl** [comment]
As OZW is no longer maintained you could try to use its succesor ZwavJS2MQTT https://www.domoticz.com/wiki/ZwaveJS2MQTT

**Comment by user8446** [comment]
Thank you. It might be a while until I get around to it as I have some OZW DzVents scripts I need to rewrite

**Comment by waltervl** [comment]
Be aware that IDX and device names will stay the same if you use the device replace function. So perhaps less or no need to modify scripts....
