### ISSUE TITLE
domoticz autodiscovery 	HEIMAN	HS2WD-E

### ISSUE THREAD

**Issue by Bartekn86** [domoticz/domoticz#4996]
Could you look into the code, and check what could be wrong with detection of the sirene ?
using stas, zigbee2mqtt plugin all works correctly, device is avalible in domoticz, also i can  also use it with flood sensors
![2](https://user-images.githubusercontent.com/69695376/139090289-e197c49c-3cac-4406-9f0b-ac374383a5a9.png)
![1](https://user-images.githubusercontent.com/69695376/139090296-f4185568-c71c-44f7-b2b1-6369c6424362.png)

**Comment by gizmocuz** [comment]
Please try beta 13784 and see if that's working for you. Else please join our slack channel

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

**Comment by kovainfo** [comment]
beta 14034 doesn't work either

**Comment by kovainfo** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/5779
> Because the alarm is not a simple on/off switch. You have to define a mode, sound level, duration, etc. 
> You can ofcourse create a switch yourself in HA to send the desired payload

But in Domoticz we can't create MQTT switch by yourself

**Comment by gizmocuz** [comment]
For now there are other workarounds you could explore, like a script that sends the desired payload. Create a dummy switch, as On action specify the script to execute and done

**Comment by gizmocuz** [comment]
Your also replying on a quite old topic. As you may know, we need more information like the MQTT topic/config object, and state topic/payload, things that help us simulate the device/issue.
But if the device is currently correctly detected and the only issue is to send a MQTT payload to activate the switch, try using a bash script for now

Edit: or create a python mqtt switch plugin ?

**Comment by jvanderzande** [comment]
I have a ZIGBEE2MQTT Siren as well (different brand)  and that discovers 4 subdevices fine.
![image](https://user-images.githubusercontent.com/13818504/148757429-3f47b51e-d5ff-4b75-8be7-c774ae216d81.png)

**Comment by Bartekn86** [comment]
what device do you have ?

**Comment by waltervl** [comment]
Still an issue with MQTT Autodiscover?

**Comment by kovainfo** [comment]
it may be necessary to be able to create dummy devices that could execute MQTT messages to turn on / off.
<img width="787" alt="scrsh" src="https://user-images.githubusercontent.com/36986231/153849291-883389d3-1dd1-415a-9f32-f105135d0bea.png">

**Comment by jvanderzande** [comment]
> it may be necessary to be able to create dummy devices that could execute MQTT messages to turn on / off.

Nothing is stopping you from doing that now!  Just create a shellscript for doing this and start that in the indicated fields! ;) 
The shellscript can run the mosquitto_pub command with the appropriate TOPIC and PAYLOADs

**Comment by kovainfo** [comment]
> > it may be necessary to be able to create dummy devices that could execute MQTT messages to turn on / off.
> 
> Nothing is stopping you from doing that now! Just create a shellscript for doing this and start that in the indicated fields! ;) The shellscript can run the mosquitto_pub command with the appropriate TOPIC and PAYLOADs

to do this, you need to use an MQTT client and have separate connections to the MQTT broker (and, of course, be able to write such scripts). At a time when domoticz already has this functionality, it remains to teach him how to send messages directly.
