### ISSUE TITLE
New Coolcam Z-Wave 700 devices not supported

### ISSUE THREAD

**Issue by HB787** [domoticz/domoticz#4999]
Hi Team,

I bought two Coolcam devices with the new Z-Wave 700 chip.
These are on the market now:
nas-pd07z, featuring PIR, lux, Temp and Humidity
nas-ds07z door sensor with Temp and Humidity
Because the Open Z-Wave platform is not updated with these new devices I did some work myself.
Added this to the manufactor xml
<Product config="shenzen_neo/nas-pd07z.xml" id="0720" name="NAS-PD07Z Battery & DC Powered PIR 4 in 1" type="0010"/>
<Product config="shenzen_neo/nas-ds07z.xml" id="0702" name="Door/Window Detector Z-Wave 700 V3 with temp and hum" type="0010"/>

I have uploaded the two xml files, the nas-pd07z.xml was already created by David J
Did the nas-ds07z.xml myself based on the old ds01z.xml.
I believe that it makes sense to add these to Domoticz because a lot of people will buy them as they are not expensive.

Thanks,
Harry

Platform: Raspberry PI4
Controller: Aeotec zw-090 usb stick
Version: 2021.1
Build Hash: 8547c5b7e
Compile Date: 2021-04-17 17:29:11
[new_700_ series_shenzen_neo_xml.zip](https://github.com/domoticz/domoticz/files/7446455/new_700_.series_shenzen_neo_xml.zip)

**Comment by user8446** [comment]
The Aetotec zw-090 is a Gen5 stick. You would need the Z-Stick 7 but there are still a lot of incompatibilities with Gen7:

https://aeotec.com/z-wave-home-automation/development-kit-pcb.html

https://aeotec.com/z-wave-gateways/compatibility.html

https://github.com/OpenZWave/open-zwave/issues/2570

**Comment by HB787** [comment]
These devices are backward compatble (300 and 500 z-wave) so they work on the Aeotec zw090 stick.
Everything is working, also the longer battery usage.
Except for the special 700 chipsets longer range capabilities.

**Comment by user8446** [comment]
I misunderstood, I thought you were buying the gen7 to actually get the get7 capabilities

**Comment by HB787** [comment]
Well I saw that the battery consumption is low and the fact that the PIR combined 4 sensors was already an advantage on the ZW090 Gen 5 stick.

**Comment by waltervl** [comment]
Gen 7 should be supported now by Zwavejs2mqtt that is supported by Domoticz with MQTT Autodiscover hardware. See for example https://github.com/zwave-js/node-zwave-js/issues/1100

**Comment by gizmocuz** [comment]
Please not that configuration files need to be submitted to the OpenZWave team directly as we will sync them from time to time

**Comment by HB787** [comment]
I understand, but I am still using the OpenZwave.
Have no clue about the Zwavejs2mqtt possibilities, from what I read quite complex.

**Comment by gizmocuz** [comment]
Not really, but first time setup could take you some time...

**Comment by HB787** [comment]
I understand, but the OpenZwave team is not active in updating anymore.
Mentioned it around october last year and also another guy did that.

The devices are sold in the meantime, I only have one XML working (Contact DS07z) the other (PD07z) is not accepted by Domoticz somehow.

**Comment by gizmocuz** [comment]
Please do not reply by email because all your details are in there

**Comment by waltervl** [comment]
Please consider migrating to ZwaveJS2MQTT, see https://www.domoticz.com/wiki/ZwaveJS2MQTT
