### ISSUE TITLE
Domoticz does not show the device names correctly in notifications 

### ISSUE THREAD

**Issue by kitopopo** [domoticz/domoticz#5000]
Dear friends,

I would like to explain the problem that happen with zigbee2mqtt and domoticz lastest beta. 

After updating the zigbee2mqtt plugin to the latest version 3.1 several changes are observed, but in all the notifications sent with domoticz (either through telegram or fcm) all notifications arrive with the long zigbee name "0x00125415xxxxxxx_sensor_closed" instead of arriving with the name assigned by domoticz. If I go back to the previous version of the plugin everything works correctly. I have contacted with @stas-demydiuk and he comments that the problem is somewhere in migration to the DomoticzEx framework. I leave the github link below since he does not believe that the problem is in the plugin. I put an example below:

```
plugin with previous versions:
2021-10-03 16:31:54.304 Status: Notification: Sensor1 Salon Closed
2021-10-03 16:31:54.479 Status: dzVents: Info: Handling events for: "Sensor1 Salon", value: "Closed"

with plugin 3.1 updated
2021-10-03 16:42:56.378 Status: Notification: 0x00158d000273b8c6_sensor Open
2021-10-03 16:42:56.489 Status: dzVents: Info: Handling events for: "Sensor1 Salon", value: "Open"
```

Because the problem occurred when updating the zigbee2mqtt plugin to version 3.1 I understood that it was a plugin problem and opened the following issue 28 days ago (https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/724). In this link you can see photos of the problem.

@stas-demydiuk wrote:

```
There are no changes in how the plugin handles the device names, so I guess the issue is somewhere in new Python Plugins Framework or the way how the plugin uses it.

Hopefully, @dnpwoo could take a look at what might cause it
```

```
Yes, it only confirms the assumption that the root cause is somewhere in migration to the DomoticzEx framework. At the moment I have no idea what could cause it, but maybe some of you could find the reason.

https://www.domoticz.com/wiki/Developing_a_Python_plugin

I guess the best action item would be to raise an issue in Domoticz repo with a clear explanation what the issue is and what the expected result and hopefully someone could help
```
I also opened this issue in the domoticz forum but I have not received a response about any solution (https://www.domoticz.com/forum/viewtopic.php?f=6&t=37285)

I hope someone can clarify what is happening, if the problem is somewhere in migration to the DomoticzEx framework or the zigbee2mqtt plugin. Until domoticz implements this plugin natively in its next updates, I believe that this plugin is of vital importance for domoticz and zigbee2mqtt. Maybe @dnpwoo can check this problem? Thank you very much everyone for your dedication and work

**Comment by stas-demydiuk** [comment]
@dnpwwo, it would be great if you could please take a look at why that might be happening. The only change in this area from the plugin side is the switch from Domoticz to DomoticzEx framework.

And what I see from the comments in the original issue: even when after upgrade users downgrade to the previous plugin version (which uses just Domoticz framework) the same devices appear just fine again.

**Comment by dnpwwo** [comment]
Pushed a fix for this, will be in the next beta

**Comment by kitopopo** [comment]
> Pushed a fix for this, will be in the next beta

Thanks dear @dnpwwo , i will inform after next beta update. Thanks in advanced. Best regards

**Comment by kitopopo** [comment]
Dear @dnpwwo ,

the notification name's problem was solved with the lastest beta 13828 but now is impossible to have acces to custom --> zigbee2mqtt, loading message appears, you can see the picture.

![zigbee](https://user-images.githubusercontent.com/51416982/139934019-4baf7ec5-94c7-4cdf-bb3b-3702f1e9521e.jpg)

Thanks in advanced, Best regards

**Comment by kitopopo** [comment]
sorry @dnpwwo . It's a known issue,  #729. Thanks again.

**Comment by kitopopo** [comment]
Dear @dnpwwo,

It is possible that after the last update of domoticzEx framework the individual logs of several zigbee devices are not displayed?

Please se the issue: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/738

I wait news from you.

Thanks in advanced, best regards

**Comment by waltervl** [comment]
Relating issue is closed. Closing this too.
