### ISSUE TITLE
(Re)Start crash of Domoticz caused by the Zigbee plugin.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5001]
Currently at build 13703 with 'old' zigbee2mqtt plugin. Also applies to older Domoticz version.
To (re)start / update Domoticz I HAVE to do the following procedure, otherwise Domoticz will crash at the start.

1. Disable zigbee2mqtt plugin in Hardware
2. Stop Domoticz
3. Stop mosquitto and delete the database
4. Stop the zigbee2mqtt service, with 100+ devices
5. Move all dzVents scripts out of the folder.
6. Start mosquitto
7. Start Domoticz
8. Enable the zigbee2mqtt plugin in Domoticz Hardware
9. Start the zigbee2mqtt service and wait until online in Domoticz
10. I have to actuate a lot of the device, otherwise dzVents gives errors like "There is no device with that name or Id...."
10. Move the dzVents scripts back.

This seems (and I tried a lot of scenarios) the only way to get Domoticz running.
If I do it the normal way, just (re) start, then Domoticz seems not be able to handle everything in proper order.
On none of my normal zigbee messages I have set the retain option, except those I can not control.
It looks to me that Domoticz chokes on all the mqtt messages and having to handle all the dzVents scripts at the same time.
I have some 60+ scripts in the dzVents dir with a lot of triggers on zigbee devices.
I hope that the startup of Domoticz can in some way be more controlled ( one thing after the other ) and perhaps put execution of dzVents scripts on hold until the system is completely up.

**Comment by gizmocuz** [comment]
I think it's a plugin issue and not a Domoticz issue.
The reason why I say this is because we now have native support for zigbee2mqtt and zwavejs2mqtt via the default MQTT hardware. (using MQTT auto discovery protocol)
Maybe you could give this a change?

**Comment by SargonofAssyria** [comment]
I will, but it is production environment I have to plan carefully. My Zwave has to start from scratch.
So your sure that it is not a Domoticz issue? It might be an mqtt issue also what cannot be handled by Domoticz.
I have 2 strange topics. Those will be present if I switch to MQTT Auto discovery.
`zigbee2mqtt/bridge/groups
[
  {
    "friendly_name": "default_bind_group",
    "id": 901,
    "members": [],
    "scenes": []
  }
]`
and
`zigbee2mqtt/bridge/extensions
[]`
Could not that create a problem in Domoticz?

**Comment by gizmocuz** [comment]
Well the auto discovery is also using MQTT and there are loads of messages, also testing with public brokers
You have to enable the homeassistant auto discovery feature in zigbee2mqtt
Groups/Scenes can be done in Domoticz natively, but I need a config to be sure

If you want you can join the autodiscovery channel on slack

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

**Comment by SargonofAssyria** [comment]
I am the same as EddyG ;)

**Comment by SargonofAssyria** [comment]
B.t.w. It is a zigbee thread in Domoticz which is crashing! So you can argue that the zigbee plugin is causing this, but you can also argue that Domoticz is not robust enough to prevent is self from crashing by perhaps a misbehaving plugin. I programmed in the past always for the last, because its easier to blame the other than take measures your self.

**Comment by gizmocuz** [comment]
Domoticz does not have a native zigbee implementation so it must be a plugin
Don't know the reason why you mention all this ?
