### ISSUE TITLE
Issue with Zwave values not updated in dashboard or Zwave command panel

### ISSUE THREAD

**Issue by jerome-python-test** [domoticz/domoticz#5006]
Hello,

Since lastest beta versions, Zwave values (percentage for blinds) are not updated on any dashboard for a new item added (as Qubino for example).
But when click on button to close the blind, actual real value shows up for only a few milliseconds.
It seems that the real state is not updated when last action ended.
Go to Zwave command panel and see the same bug : actual value is not updated automatically. I need to click on "Refresh" button to see the actual "level" value.
Weird, isn't it ?
Please could you fix this ?
Thank you
![pb_zwave](https://user-images.githubusercontent.com/55834054/139723296-45af326d-c3ba-4a9c-979a-b789c4441198.jpg)

**Comment by gizmocuz** [comment]
If it is also not updated in the control panel, I'm afraid it is not received as it's a separate process. (domoticz and the control panel)
Could you read section "groups' in the manual of the node , Status changes are normally send to the life line (first group). Make sure the controller (node 1) is inside this group

**Comment by jerome-python-test** [comment]
I've searched for answers, and I have one, from old bug : new Openzwave 1.6+ . Qubino devices have some problems with new capabilities of actual zwave. Qubino are not ok with 1.1 lifeline group... Must be 1 only. And I can just confirm this fact :(

**Comment by waltervl** [comment]
Closing this as it seems a  Openzwave issue.  Openzwave is not maintained anymore. Perhaps try to migrate to ZwaveJS2MQTT https://www.domoticz.com/wiki/ZwaveJS2MQTT
