### ISSUE TITLE
[Python plugins] Wrong brightness in RGBW* devices

### ISSUE THREAD

**Issue by stas-demydiuk** [domoticz/domoticz#5010]
During the implementation of the Python plugin I noticed a very strange behavior: whenever I try to update the brightness of RGB device, it always reset to zero in the UI. I did try several different ways to update it, but the result is always the same

```
device = Devices[device_id].Units[unit]
device.nValue = 1
device.sValue = '100'
device.Update()
```

![rgbw-device](https://user-images.githubusercontent.com/2734836/139941669-5ebfb8ef-2c9f-443d-8bf7-1788e4f16f00.gif)

As I see from the network request even I set the sValue to `100` the actual `Value` property always comes as zero.

Here is the simple plugin which will allow to reproduce the issue: 
https://gist.github.com/stas-demydiuk/2b509a3219d5bf00a51249bbefd94485

I wonder if someone has any suggestion what is the proper way to set the value so

**Comment by stas-demydiuk** [comment]
@dnpwwo it would be great if you could take a look.

**Comment by stas-demydiuk** [comment]
@dnpwwo any chance you could check the issue?

**Comment by Bartole** [comment]
To add some information that may be of help. I observe the same issue, but with 'regular' dimmers (not (just) rgbw devices) and only zigbee devices (zigbee2mqtt plugin). Other dimmers seem to be ok.

Gr,
Bart

**Comment by dnpwwo** [comment]
No idea why but adding this line
`       
       device.LastLevel = Level`
made it work for me.  Must be some special handling inside the main part of Domoticz

**Comment by Bartole** [comment]
@dnpwwo, may I ask where you added this? In a DZVents script maybe? I am not using DZVents scripts for these devices at the moment, but maybe it can be a workaround.

Gr,
Bart

**Comment by Bartole** [comment]
setting lastLevel to level in a dzvents scripts does not work.

**Comment by dnpwwo** [comment]
I added the line to the sample plugin script linked above.

Basically onCommand needs to look like this:
```
    def onCommand(self, device_id, unit, command, Level, Color):
        device = Devices[device_id].Units[unit]
        device.nValue = 1 if Level > 0 else 0
        device.sValue = str(Level)
        device.LastLevel = Level
        device.Update()
```

**Comment by stas-demydiuk** [comment]
Yes, looks like this workaround works, thank you!
