### ISSUE TITLE
Netatmo assume we have only 1 home

### ISSUE THREAD

**Issue by enpepet** [domoticz/domoticz#5012]
### The current code assume we have only 1 home for now

This is what I found in code searching to add more thermostats. 
I have 3 thermostats each in a different Netatmo home. Only the first is shown at Domoticz.

Please, add all devices from all homes because netatmo creates a new home for each thermostat. 
Otherwise we need to share the home to new user or create more users and duplicate Domoticz hardware.

The code
```` c
bool CNetatmo::ParseHomeData(const std::string &sResult)
{
	Json::Value root;
	bool ret = ParseJSon(sResult, root);
	if ((!ret) || (!root.isObject()))
	{
		Log(LOG_STATUS, "Invalid data received...");
		return false;
	}
	//Check if we have a home id
	if (!root["body"]["homes"].empty())
	{
		//Lets assume we have only 1 home for now
		if ((int)root["body"]["homes"].size() <= m_ActHome)
			return false;
		if (!root["body"]["homes"][m_ActHome]["id"].empty())
		{

````

**Comment by RobMeerwijk** [comment]
Identical to #2700 Recognised as a Domoticz bug in september 2018. See my workaround, clumsy, but it works

**Comment by gizmocuz** [comment]
The current code should put everything in structures together with the HomeID.
If all module and rooms have unique ID's that should not be to hard to change
I am unable to test as I don't have this hardware.
Might be able to have a look if someone gives me access, best to send me a PM on the forum and notify here

**Comment by RobMeerwijk** [comment]
Hi, I just checked all the duplicate (and triplets, etc) setpoints and TX3 temperature sensors that were produced by either domoticz or netatmo and it turns out that they were all produced before 6th of july. Probably the date that I last updated Domoticz! So my problem seems to be solved indeed, thanks!

**Comment by JurgenLB** [comment]
I had a lot of errors in the log but sinds I put the netatmo plugin there are a lot less errors in the log.
@gizmocuz I have a weatherstation and thermostats with radiatorvalves and camera's from netatmo. I can give you access if you want.

**Comment by gizmocuz** [comment]
@JurgenLB , That would be great. Could you send me the remote login details via a private message on the forum ?

**Comment by JurgenLB** [comment]
Dit you recieved the link?

**Comment by JurgenLB** [comment]
apparently Netatmo user account setting are not straith forward, multiple invite and accept necessary.
The scope from domoticz need to be expanded for controlling the light and door-contacts
on the moment I see multiple times per day error message;
- Error: Netatmo: Error connecting to Server...
- Error: Netatmo: cloud data for module
At this moment not clear for me how to debug this

**Comment by waltervl** [comment]
> apparently Netatmo user account setting are not straith forward, multiple invite and accept necessary. The scope from domoticz need to be expanded for controlling the light and door-contacts on the moment I see multiple times per day error message;
> 
> * Error: Netatmo: Error connecting to Server...
> * Error: Netatmo: cloud data for module
>   At this moment not clear for me how to debug this

See https://github.com/domoticz/domoticz/issues/3119

**Comment by waltervl** [comment]
@enpepet @RobMeerwijk Is the issue "The current code assume we have only 1 home for now" solved?
There is also a recent fix for the problem with combination of Weather Station and radiator valve in latest beta https://github.com/domoticz/domoticz/issues/4882

**Comment by RobMeerwijk** [comment]
> Hi, I just checked all the duplicate (and triplets, etc) setpoints and TX3 temperature sensors that were produced by either domoticz or netatmo and it turns out that they were all produced before 6th of july. Probably the date that I last updated Domoticz! So my problem seems to be solved indeed, thanks!

Hi I was already fine last november! Thanks for solving!
