### ISSUE TITLE
Python plugin framework crashes on badly-formed http response

### ISSUE THREAD

**Issue by bloob00k** [domoticz/domoticz#5013]
Version 2021.1 (build 13830)
Raspberry pi

My python plugin calls the Drayton Wiser API.  They recently updated their firmware / API such that it now returns an invalid response; specifically, the response uses chunked encoding, and has *two* terminator chunks.  I.e. it ends like this
0\r\n
\r\n
0\r\n <--- This and the next line should not be here.
\r\n

This causes the framework to crash.  Whilst the bug is clearly in the API rather than domoticz, the framework should nevertheless be more resilient to badly-formed data since it can't control it.  I have a patch to fix this which I will submit as a PR.

**Comment by bloob00k** [comment]
PR #5014

**Comment by waltervl** [comment]
Can be closed as 5014 is implemented with commit https://github.com/domoticz/domoticz/commit/3822d7a21625b4923616f8271a92ef47b7a04215
