### ISSUE TITLE
zwavejs2mqtt kWh is wrong

### ISSUE THREAD

**Issue by arjanvanleent** [domoticz/domoticz#5020]
zwavejs2mqtt kWh is wrong
Zwavejs2mqtt send the correct value but Domoticz handel this as Watts.
Zwavejs2mqtt send 1137.741kWh but Domoticz see this as 1137,741 watts

![image](https://user-images.githubusercontent.com/17556892/141002792-f50fad4b-4b65-4f1a-95ad-765e6279cd36.png)

![image](https://user-images.githubusercontent.com/17556892/141002942-37f61e0d-6cc3-4237-8387-1be25c9fe875.png)
Domoticz only show 0.002kWh and this is running now for 2 days

I use autodiscovery for Zwave know and for Zigbee2mqtt and I love it

![image](https://user-images.githubusercontent.com/17556892/141003384-c6420c17-aa03-4312-8a9c-bc399fbca49c.png)

**Comment by gizmocuz** [comment]
Thank you for reporting. Is it possible you could try beta 13872 to see if this solves the issue ?

**Comment by arjanvanleent** [comment]
This solved it thanks
