### ISSUE TITLE
Power usage graph scale not showing properly

### ISSUE THREAD

**Issue by blackburst67** [domoticz/domoticz#5023]
Hi,

I am monitoring my electricity consumption with a CM180i and since one year roughly, after a big update, the graphic scale does not show properly.
The Y scale with the Wh is set from 0 to 400k and is fixed now. So with my little consumption at 6k Wh maximum, its not showing well at all. I have no view full scale of the "power usage" like the temperature (the precise curve)

I made a gif of my screen to show you the bug :
![Animation](https://user-images.githubusercontent.com/94263635/141663312-ab894dfd-b0f8-4e4b-8b92-f01af47655d8.gif)

I am running the last beta. I was in stable but the last update made this bug appear I think and the beta channel doesn't change the bug.
I am running on firefox but the same bug happend under chrome or edge
Can you take a look ?
Thanks !!

**Comment by michahagg** [comment]
Hi @blackburst67 could you show the configuration of the device? And how did you add this device? I'd like to add one or simulate one on my testdomoticz to try and see if I can reproduce your situation.

**Comment by blackburst67** [comment]
> 
> 
> Hi @blackburst67 could you show the configuration of the device? And how did you add this device? I'd like to add one or simulate one on my testdomoticz to try and see if I can reproduce your situation.

Hi @michahagg ,

![CM180i](https://user-images.githubusercontent.com/94263635/141747807-9aa98141-2ec9-4daa-84d8-083e22977eb2.PNG)
 
I have a Owl CM180i with measurement of one phase. It's emitting in 433Mhz and link with my RFXCom RFXtrx433.
You have the screenshot of the device !
I think the bug has come with the Stable update of 2021.1
Before that, the graph was showing properly with the right scale

**Comment by waltervl** [comment]
It was mentioned before on the forum as a possible bug. https://domoticz.com/forum/viewtopic.php?f=14&t=36767
I did not check properly but I have the same issue (but not hurting me).

**Comment by michahagg** [comment]
Hi @blackburst67 the two scales are kept synchronized, that is they show the same range. That is on purpose as both the Power and Energy should correspond with each other. What I mean by that is the following. When you look at one hour in time, you have an Average Power in Watt and a Total Energy in Wh. And by definition, those two always have exactly the same numerical value. Therefore the scales for both power and usage should show the same range.

As you can see in the following image, the top edge of each blue column corresponds with the average of the yellow line crossing it.
![image](https://user-images.githubusercontent.com/3728489/145602181-c1d321da-00fb-4e68-8782-879fdccbf867.png)

My guess what goes wrong in your situation is that the divider isn't properly set. Could you show me the configuration on Settings > Meters/Counters > RFXMeter/Counter Dividers. Usually the divider for Energy is set to '1000'.

**Comment by blackburst67** [comment]
Hi @michahagg
This is my configuration of the RFXMeter, the divider is 1000.
I tried to change it to 100 or 100000 and indeed it changed the label of the scale but the yellow line doesn't move from the ground and stay flat : 
![Screenshot 2021-12-12 at 01-55-12 Domoticz](https://user-images.githubusercontent.com/94263635/145696504-1612cfe8-42ec-4356-bec9-5730cd37c695.png)
![Screenshot 2021-12-12 at 01-56-05 Domoticz](https://user-images.githubusercontent.com/94263635/145696506-820bfc1b-1918-40d5-ace2-b54182a87c89.png)


![Screenshot 2021-12-12 at 01-34-56 Domoticz](https://user-images.githubusercontent.com/94263635/145696385-8009bfc5-9d47-4fd3-af9f-8c6531e6587c.png)
 
I understand your explanation but it's juste a matter of a bug displaying the scale of power usage (as you can see the 1/2 second of good display on my gif)

**Comment by michahagg** [comment]
I see what you mean. I would like to reproduce this situation on my laptop to be able to try and fix it. I need the data for that.
Could you execute the following queries on the database?

`select * from DeviceStatus where ID = [device-id]`
`select * from Meter where DeviceRowID = [device-id]`

Fill in the index of the device at [device-id].

**Comment by blackburst67** [comment]
[DeviceStatus.csv](https://github.com/domoticz/domoticz/files/7733823/DeviceStatus.csv)
[Meter.csv](https://github.com/domoticz/domoticz/files/7733824/Meter.csv)
 Here is the export of what you have ask. I did it from DB Browser for SQLite
Hope it's the right way !

**Comment by michahagg** [comment]
Hi @blackburst67 I have loaded your data in my test setup and I get the same results as you do. So problem is reproduced! That's the good news.
I have been looking to find the cause of the problem. Unfortunately I haven't found a definitive piece of code that I can declare incorrect.
What I have found though is that when the Values in the Meter table were to be divided by 100, the columns (Energy) in the Day-chart do correspond with the line (Power).
I'll look into it further.

**Comment by michahagg** [comment]
The code, that produces the Wh en W values for the chart, uses a divider to get to the correct values from those that are stored in the database (in the Meter table). It uses the same divider for the Wh and the W values. I believe this is incorrect in this case, namely a device of type pTypeENERGY.  It should divide the Wh values by 100000 and the W values by 1000. When I change the code to accomodate this, the chart looks like this:

![image](https://user-images.githubusercontent.com/3728489/146893693-3e204ce2-87ff-43a2-9b4f-e6157fe184e8.png)

Does this look like what you expect it to?

**Comment by michahagg** [comment]
How does the Comparing Usage chart (the bottom chart) look? Does that one make sense or do you think it has a similar problem?

**Comment by blackburst67** [comment]
> How does the Comparing Usage chart (the bottom chart) look? Does that one make sense or do you think it has a similar problem?

Hi ! Yes it's much better looking, with the peak and the curve following the watt metter instantly. The columm are the addition of 1h of energy and are well displayed with the actual code and the actual divider.
Your solution to have a different divider for the power usage (yellow line) and the energy use (blue colum) semms to be right !
