### ISSUE TITLE
History button in log view

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#5024]
I was faced with a question regarding the history buttons selection in log views.
Example:
![image](https://user-images.githubusercontent.com/12487713/141987200-a618c6da-6e61-4e44-a811-6c265386c656.png)

After discussed in slack, it appears that it's not a good idea to always show "3 days" log when the user set in config less that 3 days of history because in this case the button seems broken.
![image](https://user-images.githubusercontent.com/12487713/141987267-9d6296de-b033-4c6f-a8e2-255474a455f7.png)

But it would be interesting to put on the button the same number of days as the one set in config (or remove this button if there is just one day of history).

**Comment by michahagg** [comment]
Hi @Reivax851 it should be fixed in PR #5047
