### ISSUE TITLE
EnOcean - Change the method generating domoticz device IDs from EnOcean sensor IDs

### ISSUE THREAD

**Issue by stephaneguillard** [domoticz/domoticz#5028]
Issue:
- EnOcean sensors have a 4-byte hardware ID
- domoticz devices have a 2-byte ID
- current EnOcean code in domoticz picks the 2 middle bytes from the 4-byte hardware IDs, and makes this the domoticz device ID

When you purchase a batch of EnOcean sensors from the same manufacturer, their ID's almost always have the same most-significant bytes, and differ only by their least significant byte

So in the current domoticz status, many EnOcean sensors end up having the same domoticz device ID

Example: buy a batch of temperature sensors. They come marked with their hardware ID's like this:
- 50 98 1D 03
- 50 98 1D 04
- 50 98 1D 05
- 50 98 1D 06
- 50 98 1D 07
- 50 98 1D 08

For domoticz, their device ID's are the **middle 2 bytes** of the hardware ID's, so they all end up feeding a single domoticz device with ID 98 1D, which makes them unusable.

If domoticz was rather using the **2 least significant bytes**, they would properly each feed different domoticz devices with ID's 1D 03, 1D 04 etc.

I have successfully built a local fork with this patch in hardware/EnOceanESP3.cpp, and it works flawlessly.

Could the domoticz team make this change?

Best regards,

**Comment by waltervl** [comment]
You are free to create a Pull Request in this repository so it will be reviewed and merged into Domoticz
Please check with @efdeb as he is doing a lot of EnOcean enhancements.

**Comment by efdeb** [comment]
Hi @stephaneguillard 

The problem with current domoticz implementation, is that some "internal" domoticz devices only use 1 or 2 bytes ID when EnOcean uses 4 bytes ID, making it necessary to shorten the EnOcean node ID to fit in available space.

See for instance : 
A5-02-01..30, Temperature sensor using 2 bytes + a trick to add a 3rd one
A5-04-01..04, Temperature and Humidity Sensor using 2 bytes.
A5-06-01, Light Sensor using 1 byte + a trick to add a 2nd one

Using last significant bytes from EnOcean ID might be a good idea. Also possible to calculate a hash value using CRC16 algorithm. Or change/add domoticz internal devices to use 4 bytes IDs...

I'll have a look at it and propose something, with the concern of backward compatibility with existing installations.

Please, feel free to contact me.

**Comment by waltervl** [comment]
Still an issue or already solved with a change?
