### ISSUE TITLE
Problem Saving Settings

### ISSUE THREAD

**Issue by EdwinKort** [domoticz/domoticz#5030]
When applying settings from the settings page, I get an 'problem saving settings' error and domoticz stops working.

With the help of @kiddigital I remedied this by starting domoticz with ./domoticz -sslwww 0 disabling the SSL server. 

Crash-log:
`[New LWP 12217]
[New LWP 12218]
[New LWP 12219]
[New LWP 12220]
[New LWP 12221]
[New LWP 12222]
[New LWP 12223]
[New LWP 12224]
[New LWP 12225]
[New LWP 12226]
[New LWP 12228]
[New LWP 12229]
[New LWP 12230]
[New LWP 12231]
[New LWP 12235]
[New LWP 12237]
[New LWP 12238]
[New LWP 12239]
[New LWP 12240]
[New LWP 12241]
[New LWP 12490]
[New LWP 15229]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
__GI___nanosleep (remaining=0x7ee809f0, requested_time=0x7ee809f0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
28	../sysdeps/unix/sysv/linux/nanosleep.c: No such file or directory.
  Id   Target Id                                       Frame 
* 1    Thread 0x75e99040 (LWP 12216) "domoticz"        __GI___nanosleep (remaining=0x7ee809f0, requested_time=0x7ee809f0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  2    Thread 0x759c0200 (LWP 12217) "Watchdog"        __GI___nanosleep (remaining=0x759bfbb0, requested_time=0x759bfbb0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  3    Thread 0x751bf200 (LWP 12218) "SQLHelper"       syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  4    Thread 0x749be200 (LWP 12219) "PluginMgr"       syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  5    Thread 0x73c11200 (LWP 12220) "InfluxPush"      syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  6    Thread 0x73410200 (LWP 12221) "Webem_ssncleane" 0x768f79c0 in epoll_wait (epfd=<optimized out>, events=0x7340f358, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  7    Thread 0x72c0f200 (LWP 12222) "WebServer_8080"  __waitpid (options=0, stat_loc=0x72c09610, pid=15266) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  8    Thread 0x722ff200 (LWP 12223) "Scheduler"       syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  9    Thread 0x71afe200 (LWP 12224) "TCPServer"       0x768f79c0 in epoll_wait (epfd=<optimized out>, events=0x71afd358, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  10   Thread 0x710ff200 (LWP 12225) "MainWorker"      syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  11   Thread 0x708fe200 (LWP 12226) "MainWorkerRxMsg" futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x708fdb80, expected=0, futex_word=0xa7f37c <m_mainworker+3964>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  12   Thread 0x6fcff200 (LWP 12228) "MainWorker"      0x768f79c0 in epoll_wait (epfd=<optimized out>, events=0x6fcfe340, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  13   Thread 0x6f4fe200 (LWP 12229) "P!"              syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  14   Thread 0x6eaff200 (LWP 12230) "RFXcom"          syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  15   Thread 0x6e2fe200 (LWP 12231) "deCONZ"          syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  16   Thread 0x6d8ff200 (LWP 12235) "RFXcom"          0x768f79c0 in epoll_wait (epfd=<optimized out>, events=0x6d8fe340, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  17   Thread 0x6caae200 (LWP 12237) "OWM"             syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  18   Thread 0x6c2ad200 (LWP 12238) "NotificationSys" futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x6c2acbb0, expected=0, futex_word=0xa7ee58 <m_mainworker+2648>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  19   Thread 0x6baac200 (LWP 12239) "Plugin_ASIO"     0x768f79c0 in epoll_wait (epfd=<optimized out>, events=0x6baab340, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  20   Thread 0x6b26b200 (LWP 12240) "EventSystem"     syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  21   Thread 0x6aa6a200 (LWP 12241) "EventSystemQueu" futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x6aa69ac0, expected=0, futex_word=0xa7e558 <m_mainworker+344>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  22   Thread 0x694ff200 (LWP 12490) "deCONZ"          futex_wait_cancelable (private=0, expected=0, futex_word=0x26f4408) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  23   Thread 0x6a269200 (LWP 15229) "WebServer_8080"  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37

Thread 23 (Thread 0x6a269200 (LWP 15229)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x00727e04 in http::server::CWebsocketHandler::Do_Work() ()
#3  0x008f9ff4 in execute_native_thread_routine ()
#4  0x76a44494 in start_thread (arg=0x6a269200) at pthread_create.c:486
Backtrace stopped: Cannot access memory at address 0x2a1a

Thread 22 (Thread 0x694ff200 (LWP 12490)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x26f4408) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x0, cond=0x26f43e0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x26f43e0, mutex=0x0) at pthread_cond_wait.c:655
#3  0x003d4464 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#4  0x003e950c in boost::asio::detail::posix_thread::func<boost::asio::detail::resolver_service_base::work_scheduler_runner>::run() ()
#5  0x003d0328 in boost_asio_detail_posix_thread_function ()
#6  0x76a44494 in start_thread (arg=0x694ff200) at pthread_create.c:486
#7  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 21 (Thread 0x6aa6a200 (LWP 12241)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x6aa69ac0, expected=0, futex_word=0xa7e558 <m_mainworker+344>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  __pthread_cond_wait_common (abstime=0x6aa69ac0, mutex=0x0, cond=0xa7e530 <m_mainworker+304>) at pthread_cond_wait.c:539
#2  __pthread_cond_timedwait (cond=0xa7e530 <m_mainworker+304>, mutex=0x0, abstime=0x6aa69ac0) at pthread_cond_wait.c:667
#3  0x00211b44 in CEventSystem::EventQueueThread() ()
#4  0x008f9ff4 in execute_native_thread_routine ()
#5  0x76a44494 in start_thread (arg=0x6aa6a200) at pthread_create.c:486
#6  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 20 (Thread 0x6b26b200 (LWP 12240)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x00208b78 in CEventSystem::Do_Work() ()
#3  0x008f9ff4 in execute_native_thread_routine ()
#4  0x76a44494 in start_thread (arg=0x6b26b200) at pthread_create.c:486
#5  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 19 (Thread 0x6baac200 (LWP 12239)):
#0  0x768f79c0 in epoll_wait (epfd=<optimized out>, events=0x6baab340, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x003d2384 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2  0x003d437c in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3  0x00678844 in Plugins::BoostWorkers() ()
#4  0x00770c30 in thread_proxy ()
#5  0x76a44494 in start_thread (arg=0x6baac200) at pthread_create.c:486
#6  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 18 (Thread 0x6c2ad200 (LWP 12238)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x6c2acbb0, expected=0, futex_word=0xa7ee58 <m_mainworker+2648>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  __pthread_cond_wait_common (abstime=0x6c2acbb0, mutex=0x0, cond=0xa7ee30 <m_mainworker+2608>) at pthread_cond_wait.c:539
#2  __pthread_cond_timedwait (cond=0xa7ee30 <m_mainworker+2608>, mutex=0x0, abstime=0x6c2acbb0) at pthread_cond_wait.c:667
#3  0x00275a40 in CNotificationSystem::QueueThread() ()
#4  0x008f9ff4 in execute_native_thread_routine ()
#5  0x76a44494 in start_thread (arg=0x6c2ad200) at pthread_create.c:486
Backtrace stopped: Cannot access memory at address 0x8c

Thread 17 (Thread 0x6caae200 (LWP 12237)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x00541380 in COpenWeatherMap::Do_Work() ()
#3  0x008f9ff4 in execute_native_thread_routine ()
#4  0x76a44494 in start_thread (arg=0x6caae200) at pthread_create.c:486
Backtrace stopped: Cannot access memory at address 0x4

Thread 16 (Thread 0x6d8ff200 (LWP 12235)):
#0  0x768f79c0 in epoll_wait (epfd=<optimized out>, events=0x6d8fe340, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x003d2384 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2  0x003d437c in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3  0x003d6708 in boost::detail::thread_data<AsyncSerial::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, boost::asio::serial_port_base::parity, boost::asio::serial_port_base::character_size, boost::asio::serial_port_base::flow_control, boost::asio::serial_port_base::stop_bits)::{lambda()#2}>::run() ()
#4  0x00770c30 in thread_proxy ()
#5  0x76a44494 in start_thread (arg=0x6d8ff200) at pthread_create.c:486
#6  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 15 (Thread 0x6e2fe200 (LWP 12231)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x00674eb4 in Plugins::CPlugin::Do_Work() ()
#3  0x008f9ff4 in execute_native_thread_routine ()
#4  0x76a44494 in start_thread (arg=0x6e2fe200) at pthread_create.c:486
#5  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 14 (Thread 0x6eaff200 (LWP 12230)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x005d16a8 in RFXComSerial::Do_Work() ()
#3  0x008f9ff4 in execute_native_thread_routine ()
#4  0x76a44494 in start_thread (arg=0x6eaff200) at pthread_create.c:486
#5  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 13 (Thread 0x6f4fe200 (LWP 12229)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x0059c8ac in P1MeterSerial::Do_Work() ()
#3  0x008f9ff4 in execute_native_thread_routine ()
#4  0x76a44494 in start_thread (arg=0x6f4fe200) at pthread_create.c:486
#5  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 12 (Thread 0x6fcff200 (LWP 12228)):
#0  0x768f79c0 in epoll_wait (epfd=<optimized out>, events=0x6fcfe340, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x003d2384 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2  0x003d437c in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3  0x003d6708 in boost::detail::thread_data<AsyncSerial::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, boost::asio::serial_port_base::parity, boost::asio::serial_port_base::character_size, boost::asio::serial_port_base::flow_control, boost::asio::serial_port_base::stop_bits)::{lambda()#2}>::run() ()
#4  0x00770c30 in thread_proxy ()
#5  0x76a44494 in start_thread (arg=0x6fcff200) at pthread_create.c:486
Backtrace stopped: Cannot access memory at address 0x8a

Thread 11 (Thread 0x708fe200 (LWP 12226)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x708fdb80, expected=0, futex_word=0xa7f37c <m_mainworker+3964>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  __pthread_cond_wait_common (abstime=0x708fdb80, mutex=0x0, cond=0xa7f350 <m_mainworker+3920>) at pthread_cond_wait.c:539
#2  __pthread_cond_timedwait (cond=0xa7f350 <m_mainworker+3920>, mutex=0x0, abstime=0x708fdb80) at pthread_cond_wait.c:667
#3  0x00261f38 in MainWorker::Do_Work_On_Rx_Messages() ()
#4  0x008f9ff4 in execute_native_thread_routine ()
#5  0x76a44494 in start_thread (arg=0x708fe200) at pthread_create.c:486
#6  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 10 (Thread 0x710ff200 (LWP 12225)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x0025de08 in MainWorker::Do_Work() ()
#3  0x008f9ff4 in execute_native_thread_routine ()
#4  0x76a44494 in start_thread (arg=0x710ff200) at pthread_create.c:486
#5  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 9 (Thread 0x71afe200 (LWP 12224)):
#0  0x768f79c0 in epoll_wait (epfd=<optimized out>, events=0x71afd358, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x003d2384 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2  0x003d437c in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3  0x006d4d50 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<tcp::server::CTCPServer::StartServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1}> > >::_M_run() ()
#4  0x008f9ff4 in execute_native_thread_routine ()
#5  0x76a44494 in start_thread (arg=0x71afe200) at pthread_create.c:486
#6  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 8 (Thread 0x722ff200 (LWP 12223)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x00286db8 in CScheduler::Do_Work() ()
#3  0x008f9ff4 in execute_native_thread_routine ()
#4  0x76a44494 in start_thread (arg=0x722ff200) at pthread_create.c:486
#5  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 7 (Thread 0x72c0f200 (LWP 12222)):
#0  __waitpid (options=0, stat_loc=0x72c09610, pid=15266) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  __waitpid (pid=15266, stat_loc=0x72c09610, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
#2  0x0028f944 in dumpstack_gdb(bool) ()
#3  0x0028ff10 in signal_handler(int, siginfo_t*, void*) ()
#4  <signal handler called>
#5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
#6  <signal handler called>
#7  0x006f0d38 in http::server::cWebem::ClearUserPasswords() ()
#8  0x0031429c in http::server::CWebServer::LoadUsers() ()
#9  0x0037cbf8 in http::server::CWebServerHelper::LoadUsers() ()
#10 0x002e58d8 in http::server::CWebServer::Cmd_PostSettings(http::server::_tWebEmSession&, http::server::request const&, Json::Value&) ()
#11 0x00331464 in http::server::CWebServer::HandleCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, http::server::_tWebEmSession&, http::server::request const&, Json::Value&) ()
#12 0x00350af0 in http::server::CWebServer::GetJSonPage(http::server::_tWebEmSession&, http::server::request const&, http::server::reply&) ()
#13 0x006f271c in http::server::cWebem::CheckForPageOverride(http::server::_tWebEmSession&, http::server::request&, http::server::reply&) ()
#14 0x006f6994 in http::server::cWebemRequestHandler::handle_request(http::server::request const&, http::server::reply&) ()
#15 0x006e37e4 in http::server::connection::handle_read(boost::system::error_code const&, unsigned int) ()
#16 0x006eaeb8 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned int) ()
#17 0x003d48ec in boost::asio::detail::epoll_reactor::descriptor_state::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned int) ()
#18 0x003d4644 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#19 0x0071fe68 in http::server::server_base::run() ()
#20 0x002d7b80 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<http::server::CWebServer::StartServer(http::server::server_settings&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)::{lambda()#280}> > >::_M_run() ()
#21 0x008f9ff4 in execute_native_thread_routine ()
#22 0x76a44494 in start_thread (arg=0x72c0f200) at pthread_create.c:486
#23 0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 6 (Thread 0x73410200 (LWP 12221)):
#0  0x768f79c0 in epoll_wait (epfd=<optimized out>, events=0x7340f358, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x003d2384 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2  0x003d437c in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3  0x006effe0 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<http::server::cWebem::cWebem(http::server::server_settings const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#2}> > >::_M_run() ()
#4  0x008f9ff4 in execute_native_thread_routine ()
#5  0x76a44494 in start_thread (arg=0x73410200) at pthread_create.c:486
#6  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 5 (Thread 0x73c11200 (LWP 12220)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x003915e8 in CInfluxPush::Do_Work() ()
#3  0x008f9ff4 in execute_native_thread_routine ()
#4  0x76a44494 in start_thread (arg=0x73c11200) at pthread_create.c:486
#5  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 0x749be200 (LWP 12219)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x00679054 in Plugins::CPluginSystem::Do_Work() ()
#3  0x008f9ff4 in execute_native_thread_routine ()
#4  0x76a44494 in start_thread (arg=0x749be200) at pthread_create.c:486
#5  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0x751bf200 (LWP 12218)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x002a6d70 in CSQLHelper::Do_Work() ()
#3  0x008f9ff4 in execute_native_thread_routine ()
#4  0x76a44494 in start_thread (arg=0x751bf200) at pthread_create.c:486
#5  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0x759c0200 (LWP 12217)):
#0  __GI___nanosleep (remaining=0x759bfbb0, requested_time=0x759bfbb0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  __GI___nanosleep (requested_time=0x759bfbb0, remaining=0x759bfbb0) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x00223704 in sleep_milliseconds(long) ()
#3  0x00290078 in Do_Watchdog_Work() ()
#4  0x008f9ff4 in execute_native_thread_routine ()
#5  0x76a44494 in start_thread (arg=0x759c0200) at pthread_create.c:486
#6  0x768f7568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0x75e99040 (LWP 12216)):
#0  __GI___nanosleep (remaining=0x7ee809f0, requested_time=0x7ee809f0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  __GI___nanosleep (requested_time=0x7ee809f0, remaining=0x7ee809f0) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x00223670 in sleep_seconds(long) ()
#3  0x001ae4ac in main ()

Main thread:
#0  __GI___nanosleep (remaining=0x7ee809f0, requested_time=0x7ee809f0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  __GI___nanosleep (requested_time=0x7ee809f0, remaining=0x7ee809f0) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x00223670 in sleep_seconds(long) ()
#3  0x001ae4ac in main ()
[Inferior 1 (process 12216) detached]`

I hope this is enough info.

**Comment by kiddigital** [comment]
See [this](https://www.domoticz.com/forum/viewtopic.php?f=4&t=37403) forum thread.

Seems to be an issue between resetting the settings of both/all webserver threads.

**Comment by waltervl** [comment]
Still an issue or still being worked on?

**Comment by gizmocuz** [comment]
This has been solved in the latest version
