### ISSUE TITLE
domoticz does not show individual logs of zigbee devices

### ISSUE THREAD

**Issue by kitopopo** [domoticz/domoticz#5032]
Hello, everyone,

Since the last update of the zigbee2mqtt plugin to version 3.1 domoticz does not show the individual logs of zigbee devices such as xiaomi opening sensors, xiaomi motion sensors, xiaomi smart plugs, xiaomi vibration sensors , philips hue bulbs...
the temperature graphs if they are displayed correctly from the xiaomi zigbee temperature sensors and xiaomi plugs.

![log](https://user-images.githubusercontent.com/51416982/143764456-696648d9-4a1e-4932-8b4f-de0da57ab803.jpg)

All the individual log data of the aforementioned xiaomi devices appears empty but the rest of the individual logs of virtual switches or shelly devices appear correctly please see atach picture. any update from november 2.

 Dear mr @dnpwwo can you check again domoticzEx framework? or this time if it is a problem with the zigbee2mqtt 3.1 update plugin? or maybe @Koenkk must check zigbee2mqtt?

Here I duplicate an issue that I have open to the creator of the zigbee2mqtt plugin has not issued any response and we do not know if the problem comes from the update of the plugin to zigbee2mqtt 3.1 or really the problem is domoticz. or maybe domoticzEx framework.-

I opened this issue 12 days ago to the @stas-demydiuk but I have not received any response from him

https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/738

I think this is a very important problem, we cannot see the log of almost any device. I'm starting to get tired of zigbee2mqtt, one problem after another problem.

Nobody gets involved with this problem

Most domoticz users already no uses zigbee2mqtt anymore, everyone uses conbeeII. If they don't solve the problem, I'm going to migrate to conbeII. I asked them and no one has any kind of problem and they comment that they have much more stability. I am very happy with zigbee2mqtt but I have seen the latest problems and that they do not solve because we will have to change systems in the short term. I do not know if Mr. @gizmocuz is aware of this problem.

Hopefully someone from all those mentioned above can solve the problem soon. I once again thank all of them for their work and dedication and I thank them very much in advance. a cordial greeting

**Comment by arjanvanleent** [comment]
Best is to stop using the plugin of Zigbee2mqtt
I use now the auto discovery in mqtt.
![image](https://user-images.githubusercontent.com/17556892/143830895-3035e532-8a3e-43e9-a350-231c8373be58.png)

I switched a few weeks ago and this is working perfectly.
Al problems I had with the plugin where gone.

**Comment by Oleg-Sob** [comment]
My logs are not displayed, tried to switch to automatic detection in mqtt did not work. Can someone tell me what needs to be done to display the logs or how to set up automatic detection in mqtt.

**Comment by waltervl** [comment]
See https://www.domoticz.com/wiki/Zigbee2MQTT#Use_Domoticz_MQTT_Autodiscover
You need Domoticz latest Beta.....

**Comment by Oleg-Sob** [comment]
Thanks, it helped. I had a beta version. It was necessary in the configuration.yaml set homeassistant: true

**Comment by kitopopo** [comment]
Hi dear friends,

After a month withoyt beta updates in the last update from yestarday the problem not solved yet. incredible.

**Comment by gizmocuz** [comment]
@kitopopo , and your question is ?
Firstly, people develop open source project in their free time...
Secondly, as mentioned, do you use the new MQTT with auto discovery ?

**Comment by kitopopo** [comment]
Thanks for your answer. I have 50 zigbee devices working with the plugin zigbee2mqtt. No, i don't test the new function mqtt autodiscovery. To be able use de mqtt autidiscovery i need pair again my 50 zigbee devices? Thanks in advanced.

**Comment by gizmocuz** [comment]
No you do not need to 'pair' them... You will get new 50 devices.
I advise to just test it, you can always delete the hardware.... Or better yet, if all works, continue using it.
Yes, it might take you a few hours configuring them all

**Comment by kitopopo** [comment]
> No you do not need to 'pair' them... You will get new 50 devices. I advise to just test it, you can always delete the hardware.... Or better yet, if all works, continue using it. Yes, it might take you a few hours configuring them all

Thanks for your answer dear @gizmocuz , 

After zigbee2mqtt plugin update by @stas-demydiuk  now domoticz shows the device logs correctly. Anyway I will follow your advice and I will test the new mqtt autodiscovery function soon. 
Thank you for everything, thanks again for creating and making domoticz work and for your work and dedication. 

Kind regards
