### ISSUE TITLE
Domoticz logs the wrong path of the missing SSL DH file

### ISSUE THREAD

**Issue by sander1988** [domoticz/domoticz#5033]
Domoticz logs the wrong path of the missing SSL DH file. In this setup the DH file is configured with '-ssldhparam' (https://www.domoticz.com/wiki/Command_line_parameters). The DH file was missing, but the log reports the path of the server crt file.

The wrong variable is passed to the log command: https://github.com/domoticz/domoticz/blob/master/webserver/server.cpp#L267

**Comment by gizmocuz** [comment]
Thank you for reporting. Fixed in upcoming version
