### ISSUE TITLE
Fahrenheit temps get treated as Celsius using ZWaveJS2MQTT

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#5039]
Version: 13872
Platform: Debian 12 Bookworm (note the issue was also on Debian 10 Buster)

I've been working on moving my Domoticz over to the latest version since an alternative to OpenZwave 1.6 is finally available.  At the moment I'm running two Zwave hubs, one for the OpenZwave devices I haven't moved over and another hub for my ZWaveJS2MQTT devices.  Anyway I've moved a couple thermometers and my thermostat over which report temps in Fahrenheit.  It seems that Domoticz thinks they are reporting in Celsius because they show as like 161 degrees Fahrenheit in Domoticz.  If you do the math to convert that number back you can see that is 72 C.  72 in F is room temperature, which is what the thermometer is reporting.  My temp setting is correct (set to F) in the Domoticz settings page.  All the devices I left on OpenZwave still show the correct temps, it's just the ones I've moved to ZWaveJS2MQTT that are wrong.  Also in the ZWaveJS2MQTT control panel the temperatures are displayed correctly so it appears to be something on Domoticz's end.  To get around this I tried to tell some of my devices to report in C, but my thermostat, which is obviously the most important one doesn't have a setting to do that.  Another thing I tried is setting the Domoticz temperature scale to C instead of F.  That just flips the problem, it gets me the correct numbers in Domoticz for ZWaveJS2MQTT, but my OpenZwave devices then show 161 F instead.  Also everything is labeled C instead of F.

**Comment by gizmocuz** [comment]
Is it possible you could post the data payload send by the node(zwavejs2mqtt) from the state topic (or the topic where the temperature is send to)

**Comment by gizmocuz** [comment]
Could you also post the auto discovery payload of the temperature sensor ?

**Comment by Ittiz** [comment]
Here's the discovery for the thermostat it has a thermometer in it.  My simpler thermometer is on battery and only rarely sends updates.

> DEBUG GATEWAY: Publishing discovery: {
> type: 'climate',
> object_id: 'climate',
> discovery_payload: {
> min_temp: 5,
> max_temp: 40,
> temp_step: 0.5,
> modes: [ 'off', 'heat', 'cool', 'auto', 'dry', 'fan_only', [length]: 6 ],
> mode_state_template: `{{ {"0": "off", "1": "heat", "2": "cool", "3": "auto"}[value_json.value] | default('off') }}`,
> current_temperature_topic: 'zwave/Living_Room_Thermostat/49/0/Air_temperature',
> current_temperature_template: '{{ value_json.value }}',
> temperature_state_topic: 'zwave/Living_Room_Thermostat/67/0/setpoint/1',
> temperature_state_template: '{{ value_json.value }}',
> temperature_command_topic: 'zwave/Living_Room_Thermostat/67/0/setpoint/1/set',
> mode_state_topic: 'zwave/Living_Room_Thermostat/64/0/mode',
> mode_command_topic: 'zwave/Living_Room_Thermostat/64/0/mode/set',
> action_topic: 'zwave/Living_Room_Thermostat/66/0/state',
> action_template: `{{ {0: "idle", 1: "heating", 2: "cooling", 3: "fan", 4: "idle", 5: "idle", 6: "fan", 7: "heating", 8: "heating", 9: "cooling", 10: "heating", 11: "heating"}[value_json.value] | default('idle') }}`,
> temperature_unit: 'F',
> precision: 0.1,
> device: {
> identifiers: [ 'zwavejs2mqtt_0xe12ae2cf_node9', [length]: 1 ],
> manufacturer: 'Radio Thermostat Company of America (RTC)',
> model: 'Z-Wave Thermostat (CT100 Plus)',
> name: 'Living Room Thermostat',
> sw_version: '10.7'
> },
> name: 'Living Room Thermostat_climate',
> unique_id: 'zwavejs2mqtt_0xe12ae2cf_Node9_climate'
> },
> values: [
> '49-0-Air temperature',
> '64-0-mode',
> '67-0-setpoint-1',
> '67-0-setpoint-2',
> '67-0-setpoint-11',
> '67-0-setpoint-12',
> '66-0-state',
> [length]: 7
> ],
> mode_map: { off: 0, heat: 1, cool: 2, auto: 3 },
> setpoint_topic: {
> '1': '67-0-setpoint-1',
> '2': '67-0-setpoint-2',
> '11': '67-0-setpoint-11',
> '12': '67-0-setpoint-12'
> },
> default_setpoint: '67-0-setpoint-1',
> action_map: {
> '0': 'idle',
> '1': 'heating',
> '2': 'cooling',
> '3': 'fan',
> '4': 'idle',
> '5': 'idle',
> '6': 'fan',
> '7': 'heating',
> '8': 'heating',
> '9': 'cooling',
> '10': 'heating',
> '11': 'heating'
> },
> discoveryTopic: 'climate/Living_Room_Thermostat/climate/config',
> persistent: false,
> ignoreDiscovery: false
> }
> DEBUG MQTT: Publishing to homeassistant/climate/Living_Room_Thermostat/climate/config: {
> min_temp: 5,
> max_temp: 40,
> temp_step: 0.5,
> modes: [ 'off', 'heat', 'cool', 'auto', 'dry', 'fan_only', [length]: 6 ],
> mode_state_template: `{{ {"0": "off", "1": "heat", "2": "cool", "3": "auto"}[value_json.value] | default('off') }}`,
> current_temperature_topic: 'zwave/Living_Room_Thermostat/49/0/Air_temperature',
> current_temperature_template: '{{ value_json.value }}',
> temperature_state_topic: 'zwave/Living_Room_Thermostat/67/0/setpoint/1',
> temperature_state_template: '{{ value_json.value }}',
> temperature_command_topic: 'zwave/Living_Room_Thermostat/67/0/setpoint/1/set',
> mode_state_topic: 'zwave/Living_Room_Thermostat/64/0/mode',
> mode_command_topic: 'zwave/Living_Room_Thermostat/64/0/mode/set',
> action_topic: 'zwave/Living_Room_Thermostat/66/0/state',
> action_template: `{{ {0: "idle", 1: "heating", 2: "cooling", 3: "fan", 4: "idle", 5: "idle", 6: "fan", 7: "heating", 8: "heating", 9: "cooling", 10: "heating", 11: "heating"}[value_json.value] | default('idle') }}`,
> temperature_unit: 'F',
> precision: 0.1,
> device: {
> identifiers: [ 'zwavejs2mqtt_0xe12ae2cf_node9', [length]: 1 ],
> manufacturer: 'Radio Thermostat Company of America (RTC)',
> model: 'Z-Wave Thermostat (CT100 Plus)',
> name: 'Living Room Thermostat',
> sw_version: '10.7'
> },
> name: 'Living Room Thermostat_climate',
> unique_id: 'zwavejs2mqtt_0xe12ae2cf_Node9_climate'
> } with options { qos: 0, retain: false }
> DEBUG GATEWAY: Publishing discovery: {
> type: 'sensor',
> object_id: 'humidity_air',
> discovery_payload: {
> value_template: '{{ value_json.value }}',
> device_class: 'humidity',
> unit_of_measurement: '%',
> state_topic: 'zwave/Living_Room_Thermostat/49/0/Humidity',
> json_attributes_topic: 'zwave/Living_Room_Thermostat/49/0/Humidity',
> device: {
> identifiers: [ 'zwavejs2mqtt_0xe12ae2cf_node9', [length]: 1 ],
> manufacturer: 'Radio Thermostat Company of America (RTC)',
> model: 'Z-Wave Thermostat (CT100 Plus)',
> name: 'Living Room Thermostat',
> sw_version: '10.7'
> },
> name: 'Living Room Thermostat_humidity_air',
> unique_id: 'zwavejs2mqtt_0xe12ae2cf_9-49-0-Humidity'
> },
> discoveryTopic: 'sensor/Living_Room_Thermostat/humidity_air/config',
> values: [ '49-0-Humidity', [length]: 1 ],
> persistent: false,
> ignoreDiscovery: false
> }
> DEBUG MQTT: Publishing to homeassistant/sensor/Living_Room_Thermostat/humidity_air/config: {
> value_template: '{{ value_json.value }}',
> device_class: 'humidity',
> unit_of_measurement: '%',
> state_topic: 'zwave/Living_Room_Thermostat/49/0/Humidity',
> json_attributes_topic: 'zwave/Living_Room_Thermostat/49/0/Humidity',
> device: {
> identifiers: [ 'zwavejs2mqtt_0xe12ae2cf_node9', [length]: 1 ],
> manufacturer: 'Radio Thermostat Company of America (RTC)',
> model: 'Z-Wave Thermostat (CT100 Plus)',
> name: 'Living Room Thermostat',
> sw_version: '10.7'
> },
> name: 'Living Room Thermostat_humidity_air',
> unique_id: 'zwavejs2mqtt_0xe12ae2cf_9-49-0-Humidity'
> } with options { qos: 0, retain: false }
> DEBUG GATEWAY: Publishing discovery: {
> type: 'sensor',
> object_id: 'battery_level',
> discovery_payload: {
> value_template: '{{ value_json.value }}',
> device_class: 'battery',
> unit_of_measurement: '%',
> state_topic: 'zwave/Living_Room_Thermostat/128/0/level',
> json_attributes_topic: 'zwave/Living_Room_Thermostat/128/0/level',
> device: {
> identifiers: [ 'zwavejs2mqtt_0xe12ae2cf_node9', [length]: 1 ],
> manufacturer: 'Radio Thermostat Company of America (RTC)',
> model: 'Z-Wave Thermostat (CT100 Plus)',
> name: 'Living Room Thermostat',
> sw_version: '10.7'
> },
> name: 'Living Room Thermostat_battery_level',
> unique_id: 'zwavejs2mqtt_0xe12ae2cf_9-128-0-level'
> },
> discoveryTopic: 'sensor/Living_Room_Thermostat/battery_level/config',
> values: [ '128-0-level', [length]: 1 ],
> persistent: false,
> ignoreDiscovery: false
> }
> DEBUG MQTT: Publishing to homeassistant/sensor/Living_Room_Thermostat/battery_level/config: {
> value_template: '{{ value_json.value }}',
> device_class: 'battery',
> unit_of_measurement: '%',
> state_topic: 'zwave/Living_Room_Thermostat/128/0/level',
> json_attributes_topic: 'zwave/Living_Room_Thermostat/128/0/level',
> device: {
> identifiers: [ 'zwavejs2mqtt_0xe12ae2cf_node9', [length]: 1 ],
> manufacturer: 'Radio Thermostat Company of America (RTC)',
> model: 'Z-Wave Thermostat (CT100 Plus)',
> name: 'Living Room Thermostat',
> sw_version: '10.7'
> },
> name: 'Living Room Thermostat_battery_level',
> unique_id: 'zwavejs2mqtt_0xe12ae2cf_9-128-0-level'
> } with options { qos: 0, retain: false }
> DEBUG GATEWAY: Publishing discovery: {
> type: 'binary_sensor',
> object_id: 'battery_islow',
> discovery_payload: {
> payload_on: true,
> payload_off: false,
> value_template: '{{ value_json.value }}',
> device_class: 'battery',
> state_topic: 'zwave/Living_Room_Thermostat/128/0/isLow',
> json_attributes_topic: 'zwave/Living_Room_Thermostat/128/0/isLow',
> device: {
> identifiers: [ 'zwavejs2mqtt_0xe12ae2cf_node9', [length]: 1 ],
> manufacturer: 'Radio Thermostat Company of America (RTC)',
> model: 'Z-Wave Thermostat (CT100 Plus)',
> name: 'Living Room Thermostat',
> sw_version: '10.7'
> },
> name: 'Living Room Thermostat_battery_islow',
> unique_id: 'zwavejs2mqtt_0xe12ae2cf_9-128-0-isLow'
> },
> discoveryTopic: 'binary_sensor/Living_Room_Thermostat/battery_islow/config',
> values: [ '128-0-isLow', [length]: 1 ],
> persistent: false,
> ignoreDiscovery: false
> }
> DEBUG MQTT: Publishing to homeassistant/binary_sensor/Living_Room_Thermostat/battery_islow/config: {
> payload_on: true,
> payload_off: false,
> value_template: '{{ value_json.value }}',
> device_class: 'battery',
> state_topic: 'zwave/Living_Room_Thermostat/128/0/isLow',
> json_attributes_topic: 'zwave/Living_Room_Thermostat/128/0/isLow',
> device: {
> identifiers: [ 'zwavejs2mqtt_0xe12ae2cf_node9', [length]: 1 ],
> manufacturer: 'Radio Thermostat Company of America (RTC)',
> model: 'Z-Wave Thermostat (CT100 Plus)',
> name: 'Living Room Thermostat',
> sw_version: '10.7'
> },
> name: 'Living Room Thermostat_battery_islow',
> unique_id: 'zwavejs2mqtt_0xe12ae2cf_9-128-0-isLow'
> } with options { qos: 0, retain: false }

Here's a temp update from it.  I got it through websockets and a Domoticz plugin I'm making so I'm not sure it looks exactly like the MQTT ones does.

> {"type":"event","event":{"source":"node","event":"value updated","nodeId":9,"args":{"commandClassName":"Multilevel Sensor","commandClass":49,"endpoint":0,"property":"Air temperature","newValue":72.5,"prevValue":72,"propertyName":"Air temperature"}}}

**Comment by gizmocuz** [comment]
@Ittiz, thank you for your config.
Unfortunately I am unable to work with this.
Is it possible you can use the program MQTT Explorer, then go to the config object (homeassistant/climate/Living_Room_Thermostat/climate/config) and copy/paste this here ?
With this we should have valid JSON 

Could you also do the same for the payload messages (please also indicate the full topic)

**Comment by Ittiz** [comment]
You mean this?  The data was in my post above, I just didn't know which part you wanted.  Also how would I find the payload message?

> {"min_temp":5,"max_temp":40,"temp_step":0.5,"modes":["off","heat","cool","auto","dry","fan_only"],"mode_state_template":"{{ {\"0\": \"off\", \"1\": \"heat\", \"2\": \"cool\", \"3\": \"auto\"}[value_json.value] | default('off') }}","current_temperature_topic":"zwave/Living_Room_Thermostat/49/0/Air_temperature","current_temperature_template":"{{ value_json.value }}","temperature_state_topic":"zwave/Living_Room_Thermostat/67/0/setpoint/1","temperature_state_template":"{{ value_json.value }}","temperature_command_topic":"zwave/Living_Room_Thermostat/67/0/setpoint/1/set","mode_state_topic":"zwave/Living_Room_Thermostat/64/0/mode","mode_command_topic":"zwave/Living_Room_Thermostat/64/0/mode/set","action_topic":"zwave/Living_Room_Thermostat/66/0/state","action_template":"{{ {0: \"idle\", 1: \"heating\", 2: \"cooling\", 3: \"fan\", 4: \"idle\", 5: \"idle\", 6: \"fan\", 7: \"heating\", 8: \"heating\", 9: \"cooling\", 10: \"heating\", 11: \"heating\"}[value_json.value] | default('idle') }}","temperature_unit":"F","precision":0.1,"device":{"identifiers":["zwavejs2mqtt_0xe12ae2cf_node9"],"manufacturer":"Radio Thermostat Company of America (RTC)","model":"Z-Wave Thermostat (CT100 Plus)","name":"Living Room Thermostat","sw_version":"10.7"},"name":"Living Room Thermostat_climate","unique_id":"zwavejs2mqtt_0xe12ae2cf_Node9_climate"}

**Comment by gizmocuz** [comment]
Looks better, but it is not valid json it seems
When you use MQTT Explorer, you select the config, at the right (top) you see the payload, copy/paste this please (if it is still not valid json then I have to work around this)
In this json, you see various status/topics, for example 

zwave/Living_Room_Thermostat/49/0/Air_temperature
zwave/Living_Room_Thermostat/67/0/setpoint/1

If you go to them, click on it, on the right you should see the json payload, please copy/paste this here

**Comment by Ittiz** [comment]
hmm I thought that's what I did.  It looks like the issue is the escaping of the ".  So I just did a search and replace of \" with ' and now a validator says it's valid so see if this works:
{
	"min_temp": 5,
	"max_temp": 40,
	"temp_step": 0.5,
	"modes": ["off", "heat", "cool", "auto", "dry", "fan_only"],
	"mode_state_template": "{{ {'0': 'off', '1': 'heat', '2': 'cool', '3': 'auto'}[value_json.value] | default('off') }}",
	"current_temperature_topic": "zwave/Living_Room_Thermostat/49/0/Air_temperature",
	"current_temperature_template": "{{ value_json.value }}",
	"temperature_state_topic": "zwave/Living_Room_Thermostat/67/0/setpoint/1",
	"temperature_state_template": "{{ value_json.value }}",
	"temperature_command_topic": "zwave/Living_Room_Thermostat/67/0/setpoint/1/set",
	"mode_state_topic": "zwave/Living_Room_Thermostat/64/0/mode",
	"mode_command_topic": "zwave/Living_Room_Thermostat/64/0/mode/set",
	"action_topic": "zwave/Living_Room_Thermostat/66/0/state",
	"action_template": "{{ {0: 'idle', 1: 'heating', 2: 'cooling', 3: 'fan', 4: 'idle', 5: 'idle', 6: 'fan', 7: 'heating', 8: 'heating', 9: 'cooling', 10: 'heating', 11: 'heating'}[value_json.value] | default('idle') }}",
	"temperature_unit": "F",
	"precision": 0.1,
	"device": {
		"identifiers": ["zwavejs2mqtt_0xe12ae2cf_node9"],
		"manufacturer": "Radio Thermostat Company of America (RTC)",
		"model": "Z-Wave Thermostat (CT100 Plus)",
		"name": "Living Room Thermostat",
		"sw_version": "10.7"
	},
	"name": "Living Room Thermostat_climate",
	"unique_id": "zwavejs2mqtt_0xe12ae2cf_Node9_climate"
}

Air temp payload:
{"time":1639584676504,"value":72}

There are several set point payloads:
1:
{"time":1639584676504,"value":72}
2:
{"time":1639580244893,"value":78}
11:
{"time":1639580244893,"value":62}
12:
{"time":1639580244894,"value":85}

**Comment by gizmocuz** [comment]
Thank you for the updated config/values.
Please try beta 13996, hopefully this works for you.
The only issue I still suspect is when setting the setpoint temperature, this needs to be converted internally I think. Please let me know

**Comment by Ittiz** [comment]
Yes, I upgraded and the thermometer is fixed but the thermostat set point (which is the important one) is not fixed.

**Comment by gizmocuz** [comment]
Should be working in 14050 now....
