### ISSUE TITLE
UpdateMeter: Error converting sValue/sUsage!   crashed domoticz/ dtaabase/ UI

### ISSUE THREAD

**Issue by empierre** [domoticz/domoticz#5040]
arch armv7l
ubuntu 20.04
domoticz V2021.1 (build 13872)

Seems the updatemeter breaks the software/database/UI randomly, I deactivated a lot of things and had to look to see if this happens and when. 

Seems my most plausible problem lies there, since the issue is not immediate after startup, and from backups seems not to break so fast as the latests devel versions:

```
2021-12-04 17:00:00.232 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 445, sValue: '', sUsage: '0', dType: 113, sType: 0)
2021-12-04 17:00:15.902 Error: WebServer PO exception occurred : 'stoull'
```

**Comment by empierre** [comment]
testing to see if this is the issue:

sqlite> select * from Meter where devicerowid=445;
445|1449|2021-11-28|0
445|1449|2021-11-29|0
445|1449|2021-11-30|0
445|1449|2021-12-01|0
445|1449|2021-12-02|0
445|1449|2021-12-03|0
445|0|2021-12-03 08:50:00|0
445|0|2021-12-03 08:55:00|0
445|0|2021-12-03 09:00:00|0
445|0|2021-12-03 09:05:00|0

**Comment by empierre** [comment]
ok seems this can fix it, but cannot prevent it happening again:
delete from Meter where devicerowid=445;

**Comment by empierre** [comment]
could it be an inconsistent schema ?  Date instead of datetime ? 

qlite> select * from Meter where devicerowid=445;
445|0|2021-12-04 17:35:00|0
sqlite> .schema Meter
CREATE TABLE [Meter] ([DeviceRowID] BIGINT NOT NULL, [Value] BIGINT NOT NULL, [Date] DATETIME DEFAULT (datetime('now','localtime')), [Usage] INTEGER default 0);
CREATE INDEX IX_M_ID_DATE ON Meter(DeviceRowID, Date);
CREATE INDEX m_id_idx        on Meter(DeviceRowID);
CREATE INDEX m_id_date_idx   on Meter(DeviceRowID, Date);

**Comment by empierre** [comment]
quite amazingly lines come back, though both tables have been purged of the data, and no script (to my best knowloedge) is active

**Comment by empierre** [comment]
I even removed the device to stop this.

**Comment by waltervl** [comment]
Please check troubleshooting guide on the wiki https://www.domoticz.com/wiki/Troubleshooting
And continue on the forum.

**Comment by empierre** [comment]
done that... 

but seems the UpdateMeter has an issue:

sqlite> select * from Meter where devicerowid=445;
445|0|2021-12-04 17:35:00|0

**Comment by waltervl** [comment]
How is device 445 updated, by a Python plugin? Is that a Python plugin using legacy or Extended framework?

**Comment by empierre** [comment]
Hello,

  it was an API call, but I added aven a /bin/null and it was still working
internally ...

**Comment by gizmocuz** [comment]
It's being updated wrong. It's not actually a domoticz issue, but a issue from the one generating a wrong value.
But if you know the value that is causing this issue, I could try to debug this.
