### ISSUE TITLE
Problem with multiple svalues in MQTT messages

### ISSUE THREAD

**Issue by Igitigit2** [domoticz/domoticz#5043]
MQTT hardware receives an MQTT message which contains multiple svalue properties (svalue1, svalue2 etc.). These are sent by e.g. zwavejs2mqtt for temp+humidity devices (in my case Aeotec Multisensor 6). MQTT passes these on to the Domoticz notification system as they are, but Domoticz expects something like "svalue":"Val1;Val2;Val3" and produces error messages.
My assumption is that the code for conversion is missing in MQTT.cpp line 304 approximately (Raspi, latest beta code 13872). Unfortunately I don't have a build and test environment.

**Comment by gizmocuz** [comment]
Could you make a build/test enviroment and debug this ? I can't find any relevant code on line 304 related to this issue (in the current code)

**Comment by Igitigit2** [comment]
At first, I thought no, I couldn't, since my Linux skills are very basic and gdb is somewhere still the same as in the late eighties, but then, since it is MQTT, I should be able to have the trial SD card in my Raspi and access Mosquitto from my Windows PC. If I understand MQTT correctly, I should even be able to have two versions of Domoticz (Windows and Raspi) accessing the same Mosquitto server, at least, if the Windows machine is reading only. This is my first practical encounter with MQTT (which makes it more interesting!), so forgive me if I miss something here. 
A bit problematic could be that the relevant code is not really abundant with comments and I haven't found anything like a developer documentation so far, so let me summarize my understanding after reading parts of the code:
The function MQTT::on_message(const struct mosquitto_message *message) should receive messages from MQTT, reformat those if required and send them to the rest of Domoticz in Json format. Domoticz will then update the device status and inform other modules through the notification system. Is that assumption correct?
The Json format used internally by Domoticz expects multiple svalues separated by ';' following the property name "svalue", at least for combined Temp+Hum sensors. It cannot handle the format with multiple svalue names ("svalue" : "..."; "svalue2" : "..." and so on), which is contained in the MQTT message. Correct?
If that is the case, then I believe we need a format conversion at the indicated position. Of course, you cannot find it there yet, because it is missing.
In any case, I will start installing the dev environment on my Windows PC in order to be able to compile domoticz, but before digging deeper into the code, I will wait for your expert comments. Debugging it will take some time anyway since my temporal resources are currently quite limited.

**Comment by gizmocuz** [comment]
The code is so minimum it should not be that hard to read I hope.
To much comments in code will not help as well.
I still do not understand your current problem.
In the latest code, we implemented the auto discovery protocol, and we can use zwavejs2mqtt and zigbee2mqtt without issues.
The temp+humidity is also working.
Could you post a message that this sensor is sending ?

**Comment by Igitigit2** [comment]
[MQTT Temp+Hum Prb.log](https://github.com/domoticz/domoticz/files/7711952/MQTT.Temp%2BHum.Prb.log)

Ok, attached please find a log after restarting Domoticz, maybe it becomes clearer then. The log should also contain the autodiscovery part. I noticed the same problem with other devices as well, e.g. battery reports (see line 804 of the log). The Temp+Hum failed at line 1358, it is the twave device node30. Since I have many of them, you will find similar messages all over the place. 

A few more notes: 
- I simply updated from the last stable release, it is not a clean install. maybe this is part of the problem, but in general I think this is supposed to work.

- mqttexplorer reveals that individual messages are sent for tempereature and humidity, which leaves me a bit puzzled, since the domoticz log shows a combined device. Example message from mqttexplorer:


Topic: zwave/30/49/0/Air_temperature
{"time":1639490433090,"value":24,"nodeName":"Multisense1","nodeLocation":"1OG Bad"}


- I just received the message that a new beta version is released, but the download failed. I will try again later with that version.

Also, it would still be helpfull to have clarification to my assumptions in my last post. I am really lacking an overview for a head start, I am not looking for detailed comments or so. Apart from all this, I am convinced that mqtt is the right way to go for the zwave devices, that is excellent work!

Here still how node 30 is advertised for autodiscovery (copied from mqtt explorer):

Topic: homeassistant/sensor/1OG_BAD-Multisense1/temperature_air/config
{
  "value_template": "{{ value_json.value }}",
  "device_class": "temperature",
  "unit_of_measurement": "°C",
  "state_topic": "zwave/1OG_Bad/30/49/0/Air_temperature",
  "json_attributes_topic": "zwave/1OG_Bad/30/49/0/Air_temperature",
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xf3981245_node30"
    ],
    "manufacturer": "AEON Labs",
    "model": "MultiSensor 6 (ZW100)",
    "name": "1OG Bad-Multisense1",
    "sw_version": "1.8"
  },
  "name": "1OG Bad-Multisense1_temperature_air",
  "unique_id": "zwavejs2mqtt_0xf3981245_30-49-0-Air_temperature"
}

**Comment by Igitigit2** [comment]
Sorry, the mqttexplorer logs are a bit strange. I copied something wrong, will correct that soon.

**Comment by gizmocuz** [comment]
Domoticz should combine the device ... But Above I see the unit_of_measurement is Celcius ...

**Comment by Igitigit2** [comment]
Ok, mqttexplorer logs have been corrected above.

I saw some code already, which combines the devices, but I am not sure if that was the relevant one (MQTT.cpp around line 880) and it uses the svalue, svalue1... notation. That was my initial post in the forum.

**Comment by Igitigit2** [comment]
All right, more findings and surprises. I managed to comopile the latest version on Windows and run it by leaving all the zwave and mqtt stuff on my Raspi and, what should I say, it seems to work! The Temp+Hum sensors show up as expected. Next step is now to get the latest version running on the Raspi too.

One more thing I observed is that my Fibaro RGBW dimmers show up as many individual single channel dimmers, no RGBW dimmer device is discovered (although the automatic namimg in Domoticz calls one *_rgb_dimmer. Is that already known/fixed or a problem on my side?

**Comment by gizmocuz** [comment]
Are you using the new (under development) MQTT with auto discovery support ?
If yes, could you use the program MQTT Explorer and post the config payload of the switch (and the topic) please

**Comment by Igitigit2** [comment]
That’s exactly what I did, see some posts above.

**Comment by gizmocuz** [comment]
Above is the thermostat config not the RGB

**Comment by Igitigit2** [comment]
Sorry, i thought you were still talking about the Temp+Hum sensor. anyway, here is the conf topic for the RGBW dimmer. It only mentions the meters though and not the actual switches/dimmers:
[Fibaro rgbw mqtt conf.txt]

(https://github.com/domoticz/domoticz/files/7719168/Fibaro.rgbw.mqtt.conf.txt)

**Comment by Igitigit2** [comment]
Today the update to the latest beta for the Raspi succeeded, but I am afraid, I am back to square zero. At first there was no difference, Temp+Hum devices showed the error as mentioned. I then resterted Domoticz with a new database and after adding the mqtt hardware it found the Temp+Hum devices, but still printed the errors "Warning: Expected svalue with at least two elements...". Also, the measured values did not show up in the devices it looks as if they flash up briefly but disapear again, too fast to really check them.

Then I double checked with the fresh comopiled Windows version. Here I saw the values properly displayed in the devices, but now also the warnings in the log. A short example taken from Windows:

2021-12-15 16:23:11.808 Zwave2: MQTT received: 1OG Bad-Multisense1_temperature_air (value: 24.300000000000001 Ѓ)
2021-12-15 16:23:11.818 Zwave2: Temp + Humidity/THGN122/123/132, THGR122/228/238/268 (1OG Bad-Multisense1)
2021-12-15 16:23:11.928 Zwave2: MQTT received: 1OG Bad-Multisense1_temperature_air (value: 24.300000000000001 Ѓ)
2021-12-15 16:23:11.938 Zwave2: Temp + Humidity/THGN122/123/132, THGR122/228/238/268 (1OG Bad-Multisense1)
2021-12-15 16:23:11.938 Zwave2: MQTT received: 1OG Bad-Multisense1_temperature_air (value: 24.300000000000001 Ѓ)
2021-12-15 16:23:11.948 Zwave2: Temp + Humidity/THGN122/123/132, THGR122/228/238/268 (1OG Bad-Multisense1)
**2021-12-15 16:23:11.928 Status: Warning: Expecting svalue with at least 2 elements separated by semicolon, 0 elements** received (""), notification not sent (Hardware: 2 - Zwave2, ID: zwavejs2mqtt_0xf3981245_node30, Unit: 1, Type: 52 - Temp + Humidity, SubType: 1 - THGN122/123/132, THGR122/228/238/268)
2021-12-15 16:23:11.938 Status: Warning: Expecting svalue with at least 2 elements separated by semicolon, 0 elements received (""), notification not sent (Hardware: 2 - Zwave2, ID: zwavejs2mqtt_0xf3981245_node30, Unit: 1, Type: 52 - Temp + Humidity, SubType: 1 - THGN122/123/132, THGR122/228/238/268)
2021-12-15 16:23:12.058 Zwave2: MQTT received: 1OG Bad-Multisense1_temperature_air (value: 24.300000000000001 Ѓ)
2021-12-15 16:23:12.068 Zwave2: Temp + Humidity/THGN122/123/132, THGR122/228/238/268 (1OG Bad-Multisense1)
2021-12-15 16:23:12.058 Status: Warning: Expecting svalue with at least 2 elements separated by semicolon, 0 elements received (""), notification not sent (Hardware: 2 - Zwave2, ID: zwavejs2mqtt_0xf3981245_node30, Unit: 1, Type: 52 - Temp + Humidity, SubType: 1 - THGN122/123/132, THGR122/228/238/268)
2021-12-15 16:23:12.078 Status: Warning: Expecting svalue with at least 2 elements separated by semicolon, 0 elements received (""), notification not sent (Hardware: 2 - Zwave2, ID: zwavejs2mqtt_0xf3981245_node30, Unit: 1, Type: 52 - Temp + Humidity, SubType: 1 - THGN122/123/132, THGR122/228/238/268)
2021-12-15 16:23:13.568 Zwave2: MQTT received: 1OG Bad-Multisense1_temperature_air (value: 24.300000000000001 Ѓ)
2021-12-15 16:23:13.578 Zwave2: Temp + Humidity/THGN122/123/132, THGR122/228/238/268 (1OG Bad-Multisense1)
2021-12-15 16:23:13.718 Status: Warning: Expecting svalue with at least 2 elements separated by semicolon, 0 elements received (""), notification not sent (Hardware: 2 - Zwave2, ID: zwavejs2mqtt_0xf3981245_node30, Unit: 1, Type: 52 - Temp + Humidity, SubType: 1 - THGN122/123/132, THGR122/228/238/268)
2021-12-15 16:23:23.603 Zwave2: MQTT received: 1OG Bad-Multisense1_temperature_air (value: 24.300000000000001 Ѓ)
2021-12-15 16:23:23.609 Zwave2: Temp + Humidity/THGN122/123/132, THGR122/228/238/268 (1OG Bad-Multisense1)
2021-12-15 16:23:23.718 Status: Warning: Expecting svalue with at least 2 elements separated by semicolon, 0 elements received (""), notification not sent (Hardware: 2 - Zwave2, ID: zwavejs2mqtt_0xf3981245_node30, Unit: 1, Type: 52 - Temp + Humidity, SubType: 1 - THGN122/123/132, THGR122/228/238/268)
2021-12-15 16:23:26.560 Zwave2: MQTT received: EZ-RBGW1_electricity_power (value: 49.899999999999999 W)
2021-12-15 16:23:26.563 Zwave2: Usage/Electric (EZ-RBGW1_electricity_power)
2021-12-15 16:23:33.599 Zwave2: MQTT received: 1OG Bad-Multisense1_temperature_air (value: 24.300000000000001 Ѓ)

**Comment by Igitigit2** [comment]
I debugged it on Windows and it is pretty obvious what is happening for MQTT and I could probably fix it for that, but I don't know what would happen with other hardware then:

- MQTT::OnMessage receives a mesage with svalue1, svalue2...
- It checks the message, does not find the name svalue and therefore sets the variable svalue to ""
- This empty string is passed on to MainWorker::UpdateDevice(), which detects the correct device type pTypeTEMP_HUM.
- For this device it calls StringSplit(sValue, ";", strarray);, which of course does not find anything, since it is an empty string.
- As a consequence, no svalue will be set and the call to m_notifications.CheckAndHandleNotification(...) much further down will be called with an empty svalue parameter, which finally leads to the error message.

Big question which I cannot answer: Which notation is correct and used by all the other hardware types? Is it svalue[n] or svalue? Right now it is inconsistent. Is there guideline for this (again, I miss a high level description).

**Comment by Igitigit2** [comment]
I fixed this at least for Windows and MQTT only, can't test anything else.  The solution is converting the message notation in MQTT::on_message(...). How shall I proceed from here? How will I get it compiled for my Raspi? Sorry, despite >40 years of programming I never contributed to a github project before...
