### ISSUE TITLE
Submodules need sorting?

### ISSUE THREAD

**Issue by sidepipe** [domoticz/domoticz#5044]
I made the mistake of using "git commit -a" after building in the source tree, which resulted in all of the sub modules being updated in my fork ( and hence the resultant pull request. ) You could argue that this was my naivety in git/github use... however IMHO it's easily done and probably indicates something isn't quite right in the way these are set up ( and the fact that /extern/ is in .gitignore seems to acknowledge that! )

The issue is that building Domoticz also pulls in the latest versions of the sub modules... I don't think this is how it's meant to work really. In theory, you include a module in a repository because you want to make sure that the version of your build is working with a specific version of something else - hence why the modules are tracked. Therefore ( again IMHO ) one of two things should happen:

1) The build process shouldn't update the sub modules, it should work with the ones tracked in the repository. Every now and then, someone needs to test the updated sub modules and commit the changes to update them in Domoticz,

or

2) If we really just want "the latest version of everything," then the sub modules shouldn't be in the Domoticz repository at all, but should just be pulled in from their respective repositories at build time. This can still be in extern/, but "git rm -r --cached extern" needs to be run in the Domoticz git tree and the build process updated to pull directly rather than using the sub module system.

**Comment by gizmocuz** [comment]
Maybe we could add this folder to the ignore file ?

**Comment by sidepipe** [comment]
It's already in the ignore file but since it's also in the history that doesn't actually make any difference.... you'd also need to run the rm command I mentioned to clean it out ( then force push.  ) IMHO that's the best way to deal with this, BUT it would need the build to clone the various modules.

**Comment by gizmocuz** [comment]
Closing the issue as it is meant that Domoticz is pulling the latest version of the submodules.
Building for a long time with this and it works perfect
