### ISSUE TITLE
Changes in global_data not seen in script

### ISSUE THREAD

**Issue by h4wkmoon** [domoticz/domoticz#5049]
Hi, 

I have the following global_data script.
The last changes are the addition of the "duration" and "active" fields.

```
return {
	-- global persistent data
	data = 
	    {
	  my_items =  
	    { 
	      initial = 
            {
                {
                    device="Entrée - Porte",
                    red=255,
                    green=0,
                    blue=0,
                    zecolor="red",
                    message= "porte_entree",
                    always="yes",
                    duration=120,
                    active=true
                },
            {
                    device="Porte WC",
                    red=255,
                    green=0,
                    blue=0,
                    zecolor="red",
                    message= "porte_wc",
                    always="yes",
                    duration=120,
                    active=false
                }
            }
        }
	},
	-- global helper functions
	helpers = {
		myHelperFunction = function(domoticz)
			-- code
		end
	}
}
```

The floowing script does not see the new fields : 
```

   for _, name in pairs(domoticz.globalData.my_items)
    	do
                domoticz.log( name.device )
                domoticz.log(name.duration) -- show nil here
end
```

What am I missing ?

**Comment by h4wkmoon** [comment]
I managed to make it work by removing the file scripts/dzVents/data/__data_global_data.lua
I don't think this is something I'm supposed to do.

**Comment by waltervl** [comment]
I tested this and get good results. So perhaps a hickup in the nightly rebuild of the dzVents scripts from database?
```
 2021-12-13 21:40:00.304 Status: dzVents: Info: template: ------ Start internal script: test1:, trigger: "every minute"
2021-12-13 21:40:00.304 Status: dzVents: Info: template: Timer event was triggered by every minute
2021-12-13 21:40:00.304 Status: dzVents: Info: template: Porte WC
2021-12-13 21:40:00.304 Status: dzVents: Info: template: 120
2021-12-13 21:40:00.304 Status: dzVents: Info: template: Entrée - Porte
2021-12-13 21:40:00.304 Status: dzVents: Info: template: 120
2021-12-13 21:40:00.304 Status: dzVents: Info: template: ------ Finished test1 
```

**Comment by h4wkmoon** [comment]
Good to hear that what I am experiencing is not standard.
I'm running : 

Version: 2021.1
Build Hash: 8547c5b7e
Compile Date: 2021-04-17 17:29:11
dzVents Version: 3.1.7
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

**Comment by waltervl** [comment]
My test was performed on beta 13872. DzVents 3.1.8.

**Comment by h4wkmoon** [comment]
I can confirm that the docker image "stable", with the same build version as mine does not suffer from this issue.

Then, what is going on with my domoticz ? I was think of moving to docker, in order to integrate domoticz into my home kubernetes cluster. This might be a good reason.

**Comment by waltervl** [comment]
Is it still giving this issue, even after deleting file scripts/dzVents/data/__data_global_data.lua

Because dzVents will recreate all dzVents scripts in the database every night in the scripts folder. Perhaps something was wrong there. Also it is not allowed to have a manual created and a database created global_dat.lua file.

**Comment by waltervl** [comment]
Issue still present or can it be closed?

**Comment by h4wkmoon** [comment]
Still present, but only for my domoticz instance. I don't think it is worthy keeping it open. My workaround, as ugly as it is, works. And the bug can't be reproduced.
