### ISSUE TITLE
Z-Wave: Last Seen updated even when node is dead

### ISSUE THREAD

**Issue by bjornreppen** [domoticz/domoticz#506]
On every initialization of Domoticz all Z-Wave nodes appears as they have just been seen.  Even dead nodes get their "Last seen" updated to current time. Using openzwave.  Building from from most recent on git.  This is shown in the Open Z-Wave "Nodes" dialog, shown when clicking Setup button on "OpenZWave USB" hardware page.   Z-Wave controller: Z-WAVE.ME UZB1.

**Comment by gizmocuz** [comment]
That is correct, as we get all new values from openzwave again
It also queries the nodes.
For lights/switches, i think this is good, for temperature or other sensors i think this is not needed

**Comment by bjornreppen** [comment]
Domoticz tries to get values from openzwave but only receives a notification from the controller that the node is dead.  It has failed to get any values from the node and hasn't actually seen the node.  What is the point of "Last seen" if it doesn't actually convey when the node was last seen?  Should it be renamed to "Last polled"?

**Comment by gizmocuz** [comment]
No, we open the openzwave driver
the openzwave driver is going to poll every device, and send an update to domoticz

**Comment by bjornreppen** [comment]
I see.  So the "Last seen" shows that the controller has tried to query the node.  No matter what the outcome is the node's "Last seen" time is updated.  Only way to figure out when a node stopped responding is by searching the OZW log files?  I accept the explanation, but I would have wanted it to behave differently.

**Comment by gizmocuz** [comment]
What you actually should try is start domoticz in command line mode, and look at the openzwave messages
I think (assume) they are actually refreshed, do you also see this for battery nodes ?
