### ISSUE TITLE
Delay when executing scripts 

### ISSUE THREAD

**Issue by Atreiide** [domoticz/domoticz#5062]
Domoticz version : 2020.1

I have a simple dummy switch to control a servo motor with an ON command like this : script:///home/pi/domoticz/scripts/servo_180.sh

The servo motor is on a NodeMCU 

Here is the script, nothing fancy : 

```
#!/bin/bash

/usr/bin/curl -XGET http://192.168.2.2/control?cmd=Servo,1,13,180
```

Command is successfully executed but with a delay of about 15 seconds

If I execute the command from my browser directly , (http://192.168.2.2/control?cmd=Servo,1,13,180) there is no delay

Same behavior when controlling a Sonoff plug under ESPEasy. It certainly works but with a delay each time (ON at 19PM and OFF at 22PM)

As command is executed successfully using my web browser, I think that issue comes from Domoticz.

I don't see any error message in logs

**Comment by Atreiide** [comment]
Update : I deleted ON and OFF action in my dummy switch and used instead a LUA script. This way, no more delay

```
commandArray = {}
if otherdevices['servo'] == 'On'  then
     os.execute('/home/pi/domoticz/scripts/servo_180.sh')
end
return commandArray
```

**Comment by waltervl** [comment]
Did you try to run the bash script as root (like Domoticz is doing) from the command line in a terminal window? Does it react then with or without delay?

**Comment by Atreiide** [comment]
Yes. Same issue : a delay about 5 to 7 seconds. I think this is a general problem as it affects also my Zigbee devices. See the post I made on domoticz forum : https://www.domoticz.com/forum/viewtopic.php?f=6&t=37682&p=284394#p284394

**Comment by waltervl** [comment]
Then please close this issue as it is not related (yet) to Domoticz source code issues. We will continue in your forum topic.

**Comment by Atreiide** [comment]
Ok I close. Thanks
