### ISSUE TITLE
Zwave/MQTT Fibaro RGBW dimmer not autodiscovered as RGBW

### ISSUE THREAD

**Issue by Igitigit2** [domoticz/domoticz#5069]
Domoticz V2021.1 (build 13872)

Autodiscovery does not work for the Fibaro RGBW dimmers (FGRGBW). MQTT::on_auto_discovery_message(...) is missing the code to detect this. Only keywords "color_mode", "supported_color_mode", "rgb" and "color_temp" are checked, but this dimmer sends different ones. Here is the autodiscovery message as received by MQTT.cpp:

homeassistant/light/EZ-RBGW1/rgb_dimmer/config, Message: 

{
	"state_topic": "zwave/EZ/12/38/0/currentValue",
	"command_topic": "zwave/EZ/12/38/0/targetValue/set",
	"on_command_type": "brightness",
	"state_value_template": "{{ \"OFF\" if value_json.value == 0 else \"ON\" }}",
	"brightness_value_template": "{{ value_json.value }}",
	"brightness_scale": 99,
	"rgb_command_template": "{{ {'red': red, 'green': green, 'blue': blue}|to_json }}",
	"rgb_value_template": "{{ value_json.value.red }},{{ value_json.value.green }},{{ value_json.value.blue }}",
	"rgb_state_topic": "zwave/EZ/12/51/0/currentColor",
	"rgb_command_topic": "zwave/EZ/12/51/0/targetColor/set",
	"brightness_state_topic": "zwave/EZ/12/38/0/currentValue",
	"brightness_command_topic": "zwave/EZ/12/38/0/targetValue/set",
	"device": {
		"identifiers": [
			"zwavejs2mqtt_0xf3981245_node12"
		],
		"manufacturer": "Fibargroup",
		"model": "RGBW Controller (FGRGBW)",
		"name": "EZ-RBGW1",
		"sw_version": "25.25"
	},
	"name": "EZ-RBGW1_rgb_dimmer",
	"unique_id": "zwavejs2mqtt_0xf3981245_12-51-0-currentColor"
}

**Comment by gizmocuz** [comment]
Thank you for reporting! Could you also post the value of zwave/EZ/12/51/0/currentColor ?

**Comment by Igitigit2** [comment]
Here we go:

zwave/EZ/12/51/0/currentColor
{
  "time": 1639580828153,
  "value": {
    "warmWhite": 80,
    "red": 235,
    "green": 131,
    "blue": 0
  },
  "nodeName": "RBGW1",
  "nodeLocation": "EZ"
}

Note: The test system is down (I need to swap SD cards for that) and the log was taken from a now disconnected instance of mqtexplorer, which was still open.

**Comment by gizmocuz** [comment]
Thank you for this.
Quick question, do you use this device to control individual lights, or to control a RGB(W) color strip ?
Because this device supports the ZWAVE color command class and I don't know why the developer of zwavejs2mqtt programmed this differently then other RGB(W) nodes

**Comment by Igitigit2** [comment]
I have four of these, two are used in RGBW mode (LED strips) and two as individual dimmers (to control CW and WW LEDs).

**Comment by gizmocuz** [comment]
So you want to see 4x RGB(W) switches and 16 individual dimmer switches ? Or do you control the two individual once with the RGB popup ?

**Comment by Igitigit2** [comment]
I use all in RGBW mode through setcolbrightnessvalue, that's how I do it:

                local url = d.settings['Domoticz url']..'/json.htm?type=command&param=setcolbrightnessvalue&idx='..RGBW_IDX.. '&color={"m":4,"r":' .. rr ..',"g":'.. gg .. ',"b":'..bb..',"ww":'..ww..'}&brightness=' .. Brightness
                d.openURL(url)

**Comment by Igitigit2** [comment]
@gizmocus, you pointed me in a gopod direction. I had a look at the devices supported by zwavejs2mqtt and it looks like it only knows two types of RGBW devices, FRGBW and FRGBW-442, mine is a FRGBWM441 and zwavejs2mqtt advertises it as FRGBW, which has much less features. The definition for the FRGBW-422 looks much better suited! I will have a closer look over the weekend.

**Comment by gizmocuz** [comment]
Thanks, let us know how this works out and if we need to make some changes or maybe zwavejs2mqtt

**Comment by Igitigit2** [comment]
@gizmocus, just a brief update: I read a lot and there is a lot info in the zwavejs as well as zwavejs2mqtt forums. Apparently several users had this problem with homeassistant too. The gist of it as far as I understood it is, that the Fibaro FRGBWM441 is indeed reported as simply FRGBW and contains several flaws. Especially, it does not report the color command classe, since it is kind of implicit (this is against the z-wave spec). In OZW this is cured by some entries in the OZW config file and in zwavejs2mqtt there is the flag preserveRootApplicationCCValueIDs in the device config file, which is supposed to fix this. However, from what I read this doesn't really help, but nevertheless all cases were closed on the zwavejs side, so we are back at finding a solution in Domoticz. Here I debugged it a bit and it seems that the color command class is advertised through the topic, which includes "rgb_dimmer". In the subsequent definitions there are rgb_command_topic, rgb_value_template, rgb_command_template and rgb_state_topic, which should be all information required to properly discover and use the device. The remaining, individual dimmers do not exhibit those properties. Unfortunately, none of the rbg_x values is used by domoticz so far and I am not yet deep enough into the matter to fix it, at least not without further help.

**Comment by Igitigit2** [comment]
I am working on a solution, but it isn't as simple as it seems. Too many things are different with this dimmer.

**Comment by Igitigit2** [comment]
I created PR #5082 for this.

**Comment by gizmocuz** [comment]
Should be folded in PR https://github.com/domoticz/domoticz/pull/5100
