### ISSUE TITLE
std::string::compare method issue

### ISSUE THREAD

**Issue by gaudryc** [domoticz/domoticz#507]
@gizmocuz 

Could you check all call to the std::string::compare method that you introduced in the commit #f6d661aa314955f4e1859c9ad26ff5b87afcb5e3, in the following files ?

hardware/HarmonyHub.cpp
hardware/SBFSpot.cpp
main/EventSystem.cpp
main/SQLHelper.cpp
main/WebServer.cpp
notifications/NotificationHTTP.cpp

[http://www.domoticz.com/forum/viewtopic.php?f=6&t=10677&p=76078#p76078](url)

**Comment by gizmocuz** [comment]
Fixed, thanks for the patch
