### ISSUE TITLE
letsencrypt - defect in the implementation of X9.42 Diffie Hellman encoding

### ISSUE THREAD

**Issue by mealgi** [domoticz/domoticz#5079]
Hello,

1 - Context
Version: 2021.1 (build 13330)
Build Hash: cbacba2c2-modified
Compile Date: 2021-06-18 03:16:02
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

2 - Issue
I have implemented the Diffie Hellman encoding in the SSL certificat generation using Cerbot.
From a functional standpoint the SSL access to domoticz is working properly.
However I get a Domoticz error "missing SSL DH parameters from file ..." each time I reboot domoticz.

I made an assessment of the source code and in server.cpp discovered that domoticz checks the presence of "BEGIN DH PARAMETERS" in the certificat.

In my case the certificate contains "BEGIN X9.42 DH PARAMETERS" instead of "BEGIN DH PARAMETERS" which causes the error at boot time.

Would it be possible to have the defect fixed for the next release of Domoticz allowing both presence of "BEGIN DH PARAMETERS" and "BEGIN X9.42 DH PARAMETERS" in the certificat ?
This applies in the 2 following methods of the sslserver class :,void ssl_server::init_connection() and void ssl_server::reinit_connection() 

Suggestion replace line 260 and 301 in server.cpp:

if (content.find("BEGIN DH PARAMETERS") != std::string::npos) {
by
if ((content.find("BEGIN DH PARAMETERS") != std::string::npos) || (content.find("BEGIN X9.42 DH PARAMETERS") != std::string::npos)) {

3 - Test procedure
Pre requisite : install cerbot application 

On your router redirect port 80 on the pi port  192.168.0.xx 
cd /home/pi/domoticz
sudo service domoticz.sh stop
sudo /etc/init.d/apache2 stop
sudo certbot certonly --standalone --preferred-challenges tls-sni-01,http,dns --duplicate -dMYDOMAINNAME --dry-run
sudo certbot certonly --standalone --preferred-challenges tls-sni-01,http,dns --duplicate -dMYDOMAINNAME
mkdir CertificatTemp 
sudo chmod 777 CertificatTemp
sudo chmod 777 /etc/letsencrypt/live
sudo cat /etc/letsencrypt/live/MYDOMAINNAME/privkey.pem > ~/domoticz/CertificatTemp/cert_domoticz.pem
sudo cat /etc/letsencrypt/live/MYDOMAINNAME/fullchain.pem >> ~/domoticz/CertificatTemp/cert_domoticz.pem
sudo openssl dhparam -dsaparam -out ~/domoticz/CertificatTemp/dhparam.pem 4096
sudo cat ~/domoticz/CertificatTemp/dhparam.pem >> ~/domoticz/CertificatTemp/cert_domoticz.pem
sudo cp CertificatTemp/cert_domoticz.pem ~/domoticz
sudo nano /etc/init.d/domoticz.sh 
Append line : DAEMON_ARGS="$DAEMON_ARGS -sslcert /home/pi/domoticz/cert_domoticz.pem"
sudo systemctl daemon-reload
sudo service domoticz.sh start
sudo /etc/init.d/apache2 start
On your router remove the port 80 redirection
On your router redirect port 443 to pi port 192.168.0.xx
on your browser enter  https://MYDOMAINNAME to get the SSL access to domoticz

Many thanks for the defect fixing
BR

**Comment by kiddigital** [comment]
Hi @mealgi ,

I am not sure if this should be marked as a real issue as the DH params you are generating are not real Diffie Hellman parameters (but DSA parameters).

> -dsaparam
>
>    If this option is used, DSA rather than DH parameters are read or created; they are converted to DH format. Otherwise, "strong" primes (such that (p-1)/2 is also prime) will be used for DH parameter generation.
>
>    DH parameter generation with the -dsaparam option is much faster, and the recommended exponent length is shorter, which makes DH key exchange more efficient. Beware that with such DSA-style DH parameters, a fresh DH key should be created for each use to avoid small-subgroup attacks that may be possible otherwise.

See the [OpenSSL documentation](https://www.openssl.org/docs/man1.1.1/man1/dhparam.html#OPTIONS)

Fact is, that the key header is different when using the `-dsaparam` option.

But I would suggest that you create the certificate using a generated DH param key _without_ using the `-dsaparam` option.

BTW: although everything seems to work, it only works _partly_ as the Diffie Hellman parameter key could not be found, it therefor is also not used meaning that the 'anticipated' stronger protected key-exchange (thx to the DH key) is **NOT** in effect in your scenario. So the messages generated by Domoticz should be taken seriously if you expect the DH key to be used.

**Comment by mealgi** [comment]
Hi kiddigital
I have rebuild the dhparam segment without the option -dsaparam.

sudo openssl dhparam -out ~/domoticz/CertificatTemp/dhparam.pem 4096

and after 3 hours computing regenerated the certificate.

Now the certificate contains "BEGIN DH PARAMETERS" and there is no longer the error at boot time.

Issue is closed. 
BR

**Comment by mealgi** [comment]
Issue is closed. See comments above
