### ISSUE TITLE
Aeotec DoorBell 6 exception error in openzwave.cpp

### ISSUE THREAD

**Issue by VarletNL** [domoticz/domoticz#5080]
For the newer version of the Aeotec indoor Siren 6, the exception in openzwave.cpp is being skipped. This is because the product ID is different for the new devices. Therefore the devices do not work in Domoticz.

Found the possible cause of the issue, but as I am not experienced with editing and compiling Domoticz I am not sure how to test this.
In openzwave.cpp, SwitchLight() there is an explicit, hard coded hack, for Aeotec Doorbell 6 which is limited to one signle product ID while the device has more.

// Aeotec DoorBell 6 only
if ((pDevice->Manufacturer_id == 0x0371) && (pDevice->Product_id == 0x00a2) && (pDevice->Product_type == 0x0003))
{
m_pManager->SetValueListSelection(vID, vStringList[31]); //default tone
pDevice->intvalue = 255;
}

The product ID for the ZW164 Indoor Siren 6+ is 0x00a4 and not 0x00a2 so it is skipping this exception.

As it is the same device I guess the code should be:

// Aeotec DoorBell 6 & Indoor Siren 6 only
if ((pDevice->Manufacturer_id == 0x0371) && ((pDevice->Product_id == 0x00a2)||(pDevice->Product_id == 0x00a4)) && (pDevice->Product_type == 0x0003))
{
m_pManager->SetValueListSelection(vID, vStringList[31]); //default tone
pDevice->intvalue = 255;
}

I would be happy to test a modified file on my Indoor Siren 6, just let me know how to do this.

**Comment by gizmocuz** [comment]
Sorry about the delay. I adjusted the code and a new beta (14016) should now be available. Hopefully all is working now

**Comment by VarletNL** [comment]
@gizmocuz I gave it a try and it works perfect... thank you for your effort on this. You made my day.
I understand the time it took, there are many more folks pulling on you for updates.

**Comment by gizmocuz** [comment]
Great! Thanks for the feedback!
