### ISSUE TITLE
[Feature request] Add mututal ssl authentication for MQTT client gateway

### ISSUE THREAD

**Issue by fariouche** [domoticz/domoticz#5088]
Hello,

I'm currently using mqtt client gateway hardware option with ssl tls v1.2... This works great, but I had to disable client verification in my mqtt broker because Domoticz does not have any option to set a client certificate.
For now I'm not blocked, I have other issues to fix first but when I will have time I will add the option.

**Comment by gizmocuz** [comment]
You should be able to specify a CA certificate in the hardware setup, see below screenshot

![image](https://user-images.githubusercontent.com/2265299/186350692-fd16ae2f-610b-4098-aab8-cb0cb4b84fd6.png)
