### ISSUE TITLE
Zigbee2mqtt/Mqtt Muller Licht controller not detected properly

### ISSUE THREAD

**Issue by fariouche** [domoticz/domoticz#5089]
Hello,

I'm currently using the following remote controller: https://www.zigbee2mqtt.io/devices/MLI-404011.html
I'm using the MQTT native support and domoticz detects some functions incorrectly.
For instance, the CCT buttons are detected as two separate switches instead of a dimmer:
The published mqtt messages are:
```
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon', payload '{"action":"color_temperature_move","action_color_temperature":153,"action_color_temperature_direction":"up","action_group":16388,"action_transition_time":10,"device":{"applicationVersion":1,"dateCode":"20180605-17","friendlyName":"Telecommande Salon","hardwareVersion":1,"ieeeAddr":"0x00158d000356b389","manufacturerID":4635,"manufacturerName":"MLI","model":"MLI-404011","networkAddress":28884,"powerSource":"Battery","softwareBuildID":"2.0","stackVersion":1,"type":"EndDevice","zclVersion":2},"linkquality":87}'
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon', payload '{"action":"","device":{"applicationVersion":1,"dateCode":"20180605-17","friendlyName":"Telecommande Salon","hardwareVersion":1,"ieeeAddr":"0x00158d000356b389","manufacturerID":4635,"manufacturerName":"MLI","model":"MLI-404011","networkAddress":28884,"powerSource":"Battery","softwareBuildID":"2.0","stackVersion":1,"type":"EndDevice","zclVersion":2},"linkquality":87}'
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon/action', payload 'color_temperature_move'
```

Same for the brightness, two switches are created (I pressed the down then the up brightness buttons):
```
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon', payload '{"action":"color_temperature_move","action_color_temperature":200,"action_color_temperature_direction":"down","action_group":16388,"action_transition_time":10,"device":{"applicationVersion":1,"dateCode":"20180605-17","friendlyName":"Telecommande Salon","hardwareVersion":1,"ieeeAddr":"0x00158d000356b389","manufacturerID":4635,"manufacturerName":"MLI","model":"MLI-404011","networkAddress":28884,"powerSource":"Battery","softwareBuildID":"2.0","stackVersion":1,"type":"EndDevice","zclVersion":2},"linkquality":105}'
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon', payload '{"action":"","device":{"applicationVersion":1,"dateCode":"20180605-17","friendlyName":"Telecommande Salon","hardwareVersion":1,"ieeeAddr":"0x00158d000356b389","manufacturerID":4635,"manufacturerName":"MLI","model":"MLI-404011","networkAddress":28884,"powerSource":"Battery","softwareBuildID":"2.0","stackVersion":1,"type":"EndDevice","zclVersion":2},"linkquality":105}'
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon/action', payload 'color_temperature_move'
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon', payload '{"action":"color_temperature_move","action_color_temperature":153,"action_color_temperature_direction":"up","action_group":16388,"action_transition_time":10,"device":{"applicationVersion":1,"dateCode":"20180605-17","friendlyName":"Telecommande Salon","hardwareVersion":1,"ieeeAddr":"0x00158d000356b389","manufacturerID":4635,"manufacturerName":"MLI","model":"MLI-404011","networkAddress":28884,"powerSource":"Battery","softwareBuildID":"2.0","stackVersion":1,"type":"EndDevice","zclVersion":2},"linkquality":105}'
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon', payload '{"action":"","device":{"applicationVersion":1,"dateCode":"20180605-17","friendlyName":"Telecommande Salon","hardwareVersion":1,"ieeeAddr":"0x00158d000356b389","manufacturerID":4635,"manufacturerName":"MLI","model":"MLI-404011","networkAddress":28884,"powerSource":"Battery","softwareBuildID":"2.0","stackVersion":1,"type":"EndDevice","zclVersion":2},"linkquality":105}'
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon/action', payload 'color_temperature_move'
```

And finally, the color wheel is a simple switch with no color reported (but I didn't see any domoticz device that supports colors so maybe a device type is missing in domoticz?)
Anyway, the mqtt message is (see the x and y values depending on where I press in the wheel, but I don't know how to convert that to RGB):
```
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon', payload '{"action":"color_move","action_color":{"x":0.338,"y":0.163},"action_group":16388,"action_transition_time":0,"device":{"applicationVersion":1,"dateCode":"20180605-17","friendlyName":"Telecommande Salon","hardwareVersion":1,"ieeeAddr":"0x00158d000356b389","manufacturerID":4635,"manufacturerName":"MLI","model":"MLI-404011","networkAddress":28884,"powerSource":"Battery","softwareBuildID":"2.0","stackVersion":1,"type":"EndDevice","zclVersion":2},"linkquality":105}'
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon', payload '{"action":"","device":{"applicationVersion":1,"dateCode":"20180605-17","friendlyName":"Telecommande Salon","hardwareVersion":1,"ieeeAddr":"0x00158d000356b389","manufacturerID":4635,"manufacturerName":"MLI","model":"MLI-404011","networkAddress":28884,"powerSource":"Battery","softwareBuildID":"2.0","stackVersion":1,"type":"EndDevice","zclVersion":2},"linkquality":105}'
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon/action', payload 'color_move'
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon', payload '{"action":"color_move","action_color":{"x":0.37,"y":0.175},"action_group":16388,"action_transition_time":0,"device":{"applicationVersion":1,"dateCode":"20180605-17","friendlyName":"Telecommande Salon","hardwareVersion":1,"ieeeAddr":"0x00158d000356b389","manufacturerID":4635,"manufacturerName":"MLI","model":"MLI-404011","networkAddress":28884,"powerSource":"Battery","softwareBuildID":"2.0","stackVersion":1,"type":"EndDevice","zclVersion":2},"linkquality":105}'
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon', payload '{"action":"","device":{"applicationVersion":1,"dateCode":"20180605-17","friendlyName":"Telecommande Salon","hardwareVersion":1,"ieeeAddr":"0x00158d000356b389","manufacturerID":4635,"manufacturerName":"MLI","model":"MLI-404011","networkAddress":28884,"powerSource":"Battery","softwareBuildID":"2.0","stackVersion":1,"type":"EndDevice","zclVersion":2},"linkquality":105}'
MQTT publish: topic 'zigbee2mqtt/Telecommande Salon/action', payload 'color_move'
```

**Comment by gizmocuz** [comment]
Could you post the config topic+payload please

**Comment by fariouche** [comment]
I'm not sure I understand: What is "config topic"? How can I get it?

**Comment by gizmocuz** [comment]
You can make use of a program called 'MQTT Explorer'. When you connect to your MQTT broker, you will see all topics/payloads
You should be able to find your device in the auto discovery topic and it should have a config object containing json

**Comment by fariouche** [comment]
Ok understood. I will check that when possible

**Comment by fariouche** [comment]
I believe this is the config object (I don't see any config object name so I guess it is this one)
```
{"date_code":"20180605-17","definition":{"description":"Tint remote control","exposes":[{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["on","off","toggle","brightness_down_click","brightness_up_click","color_temp","color_wheel","brightness_0_release","brightness_1_release","brightness_0_hold","brightness_1_hold"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"MLI-404011","options":[{"access":2,"description":"Set to false to disable the legacy integration (highly recommended), will change structure of the published payload (default true).","name":"legacy","property":"legacy","type":"binary","value_off":false,"value_on":true}],"supports_ota":false,"vendor":"Müller Licht"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genIdentify","touchlink"],"output":["genGroups","genIdentify","genOnOff","genLevelCtrl","lightingColorCtrl","touchlink","genOta","genBasic"]},"configured_reportings":[],"scenes":[]}},"friendly_name":"Telecommande Salon","ieee_address":"0x00158d000356b389","interview_completed":true,"interviewing":false,"manufacturer":"MLI","model_id":"ZBT-Remote-ALL-RGBW","network_address":28884,"power_source":"Battery","software_build_id":"2.0","supported":true,"type":"EndDevice"}

```

I also see some config topics for this device:
```
homeassistant/sensor/0x00158d000356b389/action/config {"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":
{"identifiers":["zigbee2mqtt_0x00158d000356b389"],"manufacturer":"Müller Licht","model":"Tint remote control (MLI-404011)","name":"Telecommande Salon","sw_version":"2.0"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","name":"Telecommande Salon action","state_topic":"zigbee2mqtt/Telecommande Salon","unique_id":"0x00158d000356b389_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}
homeassistant/sensor/0x00158d000356b389/linkquality/config {"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d000356b389"],"manufacturer":"Müller Licht","model":"Tint remote control (MLI-404011)","name":"Telecommande Salon","sw_version":"2.0"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Telecommande Salon linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Telecommande Salon","unique_id":"0x00158d000356b389_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}

```

**Comment by gizmocuz** [comment]
@fariouche , thank you, these are indeed a few, but you might want to look in the homeassistant/light tree (in MQTT Explorer)
I can't see a light declared in your above config

**Comment by fariouche** [comment]
I didn't include any light topic because this is a remote controller.

Since I opened the ticket, I understand better how domoticz works.... any button of the remote control creates 2 (or more) action devices (switches)
I can now just simulate the brightness + cct when pressing the switches on the remote, but I was expecting a dimmer switch to be created to have access to the temperature value etc...
Same for the color wheel buttons, a switch (on off button type) is created named "action_color_move"

**Comment by gizmocuz** [comment]
Yes that is how it works... and you can use those switches in scripts or activation codes for scenes/groups.

**Comment by fariouche** [comment]
So it does not parse the brightness of color temperature reported by zigbee2mqtt?
Same for the RGB wheel?

**Comment by gizmocuz** [comment]
I currently see no RGB configuration options in your config file. It could be that this is not possible or not implemented
If you look in your first message above and visit the Zigbee2MQTT page for your hardware, you will see what is exposed.
And that are actions and link quality

**Comment by fariouche** [comment]
Actually, a action_color_move switch is created. It's a push On Button type...
I pressed the button, and I see this in mqtt:

 homeassistant/device_automation/0x00158d000356b389/action_color_move/config
>{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x00158d000356b389"],"manufacturer":"Müller Licht","model":"Tint remote control (MLI-404011)","name":"Telecommande Salon","sw_version":"2.0"},"payload":"color_move","subtype":"color_move","topic":"zigbee2mqtt/Telecommande Salon/action","type":"action"}

zigbee2mqtt/bridge/logging
>  {"level":"info","message":"MQTT publish: topic 'zigbee2mqtt/Telecommande Salon/action', payload 'zigbee2mqtt/Telecommande Salon {"action":"color_move","action_color":{"x":0.338,"y":0.163},"action_group":16388,"action_transition_time":0,"device":{"applicationVersion":1,"dateCode":"20180605-17","friendlyName":"Telecommande Salon","hardwareVersion":1,"ieeeAddr":"0x00158d000356b389","manufacturerID":4635,"manufacturerName":"MLI","model":"MLI-404011","networkAddress":28884,"powerSource":"Battery","softwareBuildID":"2.0","stackVersion":1,"type":"EndDevice","zclVersion":2},"linkquality":108}


(I didn't see them before, maybe too many config to replay in mqtt? Anyway, this should be better for you to understand what is missing)
Shouldn't this trigger the creation of an RGB switch in domoticz?

**Comment by gizmocuz** [comment]
Could you tell me what Home Assistant creates ?
Looking at the action config above it contains

```
{
  "automation_type": "trigger",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x00158d000356b389"
    ],
    "manufacturer": "Müller Licht",
    "model": "Tint remote control (MLI-404011)",
    "name": "Telecommande Salon",
    "sw_version": "2.0"
  },
  "payload": "color_move",
  "subtype": "color_move",
  "topic": "zigbee2mqtt/Telecommande Salon/action",
  "type": "action"
}
```

there is no RGB here

**Comment by fariouche** [comment]
unfortunately I don't know, I do not have HA.
The second message contains an RGB (well, an x and an y) but it's an action message not a trigger.

What should contain the message? Maybe there is something missing in zigbee2mqtt that we can add?

**Comment by gizmocuz** [comment]
How is this device working in real-life ? You pair it to a rgb light bulb ? and then you can control it with the remote ?

Looking at this page it seems it detects the same as we do

https://xaviml.github.io/controllerx/controllers/MLI-404011

So at the moment I think detection work and we can close this issue ?
You can use the actions in scripts or as activators for scenes/groups in Domoticz

**Comment by fariouche** [comment]
Hello, I've installed HA, and it seems that they don't care about the input type... They let people parse the input from the remote to retrieve the x,y values from the json payload before using them in an action...
In my case, I do not use it directly paired but let a script handle the inputs.... and I don't see a way to extract the x,y values from the script.

So no solutions exist (at least in the open source world) that can handle the x,y values.
It would have been nice if domoticz was able to create a rgb switch (I don't know the exact name), but maybe it's not that easy. (if this can be done simply by modifying z2m mqtt event, it will be great... if this requires changes in domoticz then I don't know :) )

**Comment by gizmocuz** [comment]
I'm sorry, Those values are not transmitted. You get actions, actions you can use in Domoticz to trigger scenes/groups, use them in scripts etc

**Comment by fariouche** [comment]
Thank you. By the way, I didn't know controllerx, so maybe I can use it :) 
Thanks for your time
