### ISSUE TITLE
When an Evohome Relay device is "On" the device.level property is set to 0 instead of 100 in evohome_device.lua

### ISSUE THREAD

**Issue by andyjbm** [domoticz/domoticz#5093]
An Evohome Relay device has a level property useful for data pushing the proportional value to a 3rd party system via http push for example.

Here: lines 47 thro 51 https://github.com/domoticz/domoticz/blob/774d33586893ff9c73bf9c2bf23f24c6606e47f3/dzVents/runtime/device-adapters/evohome_device.lua#L47-L51

The device._state property is used to set device.state and device.level.
Device._state is usually "Off", "On" or something like "set level {x} %" where {x} is between 1 and 99. x is never 0 or 100. In these extremes _state will be Off or On instead.

The segment first sets the device.state Off or On depending on whether _state is Off or not Off.
Line 49 looks for a % in .state and sets .level to x if a % is found in the string.  Otherwise .level is set to 0. This is fine if .state is Off. We want .level to be 0 if .state is Off. But .level is also set to 0 if .state is "On" which we do not want.

I propose lines 47 thro 51 are changed to:
```
elseif device.deviceSubType == "Relay" then
       device.state = device._state == 'Off' and 'Off' or 'On'
       if device.state == 'Off' then
           device.level = 0
       else
           device.level = device._state:match('%d+') or 100
       end
       device.active = device.state ~= 'Off'
else
```

This mod has been working ok for me now for a few days and correctly data pushing a level of 100 instead of 0 for a Relay device that is "On"

Regards,
Andy.

Edit: to fix code formatting and typo errors...

**Comment by gizmocuz** [comment]
Sounds right! Could you make a PR for this?

**Comment by waltervl** [comment]
@andyjbm can you make a PR for your fix?

**Comment by gizmocuz** [comment]
Applied the PR myself. @andyjbm , thanks for reporting!

**Comment by andyjbm** [comment]
Hi @gizmocuz,

Sorry - got caught up in other things and never got round to it. Not that familiar with Github PR process - One day I'll find the time to get it nailed. Just don't do enough coding these days.

Thought this might be the chance but you beat me to it!

Thanks,

Andy.
