### ISSUE TITLE
Error at latest build 14011 about EnoceanSensors

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5098]
Installed latest build 14011.
Get errors about 
`2022-01-09 14:17:09.270 Error: SQL Query("SELECT ID, HardwareID, DeviceID, Manufacturer, Profile, Type FROM EnoceanSensors") : no such table: EnoceanSensors
2022-01-09 14:17:09.270 Error: SQL Query("DROP TABLE EnoceanSensors") : no such table: EnoceanSensors`

See in the database table EnoceanNodes but not EnoceanSensors

**Comment by gizmocuz** [comment]
Did you revert to a old database/domoticz ?

**Comment by gizmocuz** [comment]
Sorry found the issue, my fault

**Comment by gizmocuz** [comment]
it was a copy/past left over, the error will not display again on your system, was caused by a database migration script
making a new beta an new users won't see this again, thanks for reporting!
