### ISSUE TITLE
Counter RFXMeter Report display issue

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#5101]
On the report page for this counter device:
1. the Unit of measure is not mentioned, 
2. sometimes 3 decimals are added, 
3. and the counter is marked as NaN (not a number).
https://domoticz.com/forum/viewtopic.php?p=282885#p282885

![image](https://user-images.githubusercontent.com/16327072/143473465-41b15abb-bf38-45b9-816a-c3ddfcc2dd69.png)

_Originally posted by @waltervl in https://github.com/domoticz/domoticz/issues/4856#issuecomment-979329160_

**Comment by waltervl** [comment]
Version: 2021.1 (build 14013)
Build Hash: f9f936405
Compile Date: 2022-01-09 14:40:56

Definition of dummy device:
![Screenshot from 2022-01-10 19-57-13](https://user-images.githubusercontent.com/16327072/148823280-d9d51ddc-cbc3-4d3b-84c3-78b148864224.png)
Device widget example"
![Screenshot from 2022-01-10 20-00-11](https://user-images.githubusercontent.com/16327072/148823607-182dd691-fa0d-47aa-b06b-6eb379201560.png)

Report
![Screenshot from 2022-01-10 20-04-19](https://user-images.githubusercontent.com/16327072/148824147-6bf15d77-1946-4ca0-bad2-1a1dede04b30.png)
![Screenshot from 2022-01-10 20-04-52](https://user-images.githubusercontent.com/16327072/148824168-c7b50c3b-6999-4080-b3c9-cfab8dedcfb3.png)

**Comment by waltervl** [comment]
Example database, only this counter device is in it.
[domoticz.zip](https://github.com/domoticz/domoticz/files/7841318/domoticz.zip)

**Comment by waltervl** [comment]
Unit problem is in function getUnit(), only how the get the unit from  (this.Type === 'RFXMeter' && this.SwitchTypeVal === 3) Switchtype 3 is the RFXMeter type Counter. What is the variable? https://github.com/domoticz/domoticz/blob/65bfbac4f8ac2c4cf6345c8b5c2eb62ce0f7cb52/www/app/devices/deviceFactory.js#L117

**Comment by gizmocuz** [comment]
There are some more issues with this counter type. I tested your database a day after you uploaded it.
I did not get any graph in the report.
When I added a value for that day, I did get a graph
Maybe you can upload a database with some more days ? Or send me a copy of your database (with actual data) via email ?

**Comment by waltervl** [comment]
I don't use this counter myself so the only data I can provide is by filling a dummy with some scripting.

**Comment by waltervl** [comment]
New test database with some extra. It seems that I have already a Custom Counter running for some months
[Thuistest.zip](https://github.com/domoticz/domoticz/files/7876834/Thuistest.zip)
Here are the available counters, they are filled with dzVents script so will still be updated when you install this database.
![Selection_163](https://user-images.githubusercontent.com/16327072/149657774-4d3026fa-d108-4e02-9c45-14843f0a0564.png)

**Comment by gizmocuz** [comment]
I was able to partly fix the issue:

![image](https://user-images.githubusercontent.com/2265299/149659650-14eb9671-d71b-4cad-8d81-01d0f0256909.png)

The only issue left is the value behind Counter (NaN).

This is caused by

CounterReport.js
~line 41
counter: month ? source.counter : parseFloat(stats.counter),

**stats.counter = NaN**

No idea how/where this value gets filled. Maybe you could try to debug that ?

Partly fix done in beta 14073

**Comment by waltervl** [comment]
Perhaps @michahagg  has an idea? It should be somewhere in the api as it seems to be called from app\reports/CounterReport.js. 
There is also still the issue of the decimals that are added. For this counter it depends on the divider. divider = 0, no decimals, divider 10 -> 1 decimal, divider 100 -> 2 etc

**Comment by gizmocuz** [comment]
Maybe you could start learning some html 👍

**Comment by waltervl** [comment]
> I was able to partly fix the issue:
> The only issue left is the value behind Counter (NaN).
> 
> This is caused by
> 
> CounterReport.js ~line 41 counter: month ? source.counter : parseFloat(stats.counter),
> 
> **stats.counter = NaN**
> 
> No idea how/where this value gets filled. Maybe you could try to debug that ?
> 
> Partly fix done in beta 14073

So stats.counter is coming from api call /json.htm?type=graph&sensor=counter&idx=IDX&range=year&actyear=YYYY
Result for a Gas counter is
```
{
	"ValueQuantity" : "",
	"ValueUnits" : "",
	"counter" : "14.320",
	"result" : 
	[
etc
```
Results for a Counter RFXMeter is:
```
{
	"ValueQuantity" : "ValQuant",
	"ValueUnits" : "ValUnit",
	"counter" : "",
	"result" : 
	[
etc
```
So the calculated value for counter is not given by API, empty result. Where is the code that processes the API call for type=graph ??? I tried to find but got lost....

**Comment by waltervl** [comment]
Found it: https://github.com/domoticz/domoticz/blob/6e5311f01d6d3c48737fdd5b1ad87da33606fe1d/main/WebServer.cpp#L13451

**Comment by waltervl** [comment]
Story continues: there is no entry like `sprintf(szTmp, "%.3f", AddjValue + (fvalue / divider));` for MTYPE_COUNTER in section https://github.com/domoticz/domoticz/blob/6e5311f01d6d3c48737fdd5b1ad87da33606fe1d/main/WebServer.cpp#L16141

But I think it should be showing an integer if the result is an integer. What is "%.3f" meaning?

**Comment by kiddigital** [comment]
The '%.3f' means showing the float (hence f) with a precision of 3 digits.

**Comment by gizmocuz** [comment]
Did you try with the latest beta ? I made some improvements that maybe also solves this

**Comment by waltervl** [comment]
Just checked, no changes in the NaN issue on report:
![Screenshot_20220213-123525-968](https://user-images.githubusercontent.com/16327072/153751281-ef043569-2a74-4495-9b09-33a5bb1c6a0c.png)

**Comment by gizmocuz** [comment]
Hmmm yes maybe that part has not yet been solved. There where also issues (here) in the main log windows

**Comment by gizmocuz** [comment]
Found the issue... But I am still not happy with the graph, somewhere in the JS code it is using 3 decimals %.3f and I don't like that for counter types... or is it just me ?

**Comment by waltervl** [comment]
No it is not just you. Although 3 digits is the right value if you use a divider of 1000 (default for kWh, Gas and Water) as it is the same as on your physical meter in your home. But for this Counter type it should depend on the divider that is set. 1: Integer, 10: 1 digit, 100: 2 digits etc.

**Comment by gizmocuz** [comment]
But then you set the type to kWh, gas or water and not to counter.
I also found a bug that was causing it to have 3 digits in the day/week/month/year graph, instead of supplying 0 for the amount of decimals, 'undefined' was send (copy/paste error)
Still searching where the amount of decimals for the compare chart has been set

**Comment by gizmocuz** [comment]
Please try beta 14188 ... that should solve this

**Comment by waltervl** [comment]
Yes,  a proper report now, thanks a lot!
