### ISSUE TITLE
Setpoint refresh

### ISSUE THREAD

**Issue by megamarco833** [domoticz/domoticz#5107]
hi, not sure if it's an issue or not, but if you try to change the setpoint value for a dummy device set as setpoint, after you select it from mobile main dashboard it become a fix number and if you want to change it again you have to refresh the web page.
here a picture:
![immagine](https://user-images.githubusercontent.com/44502572/149339347-317392f0-4f4b-453f-9b58-eb22db6834e8.png)

**Comment by waltervl** [comment]
Is same as https://github.com/domoticz/domoticz/issues/4885

**Comment by gizmocuz** [comment]
Fixed, thanks for reporting. Took you more time to make that screenshot above then me fixing the issue ;)
Solved in beta 14052
