### ISSUE TITLE
Mainworker hung after signal 6 - python corrupted list?  (beta 14067)

### ISSUE THREAD

**Issue by jefft4** [domoticz/domoticz#5116]
Early this morning, Mainworker received signal 6 and the domoticz service hung until I realised at 8am that the house was unusually cold!

Version: 2021.1 (build 14067)
Build Hash: b36f2bc65
Compile Date: 2022-01-15 08:41:59
dzVents Version: 3.1.8
Python Version: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]

- Nothing unusual happening at the time; the entries in the log in the few seconds prior to the signal are things that happen every few minutes all day.
- Signal 6 = SIGABRT; nothing in domoticz.log to indicate the cause, but syslog is more talkative:

```

Jan 19 04:15:00 domoticz domoticz[680]: corrupted double-linked list
Jan 19 04:15:00 domoticz domoticz[680]: Fatal Python error: Aborted
Jan 19 04:15:00 domoticz domoticz[680]: Current thread 0x00007f71b1ac0700 (most recent call first):
Jan 19 04:15:00 domoticz domoticz[680]: <no Python frame>
Jan 19 04:15:00 domoticz domoticz[680]: 2022-01-19 04:15:00.745  #033[1;31mError: Domoticz(pid:680, tid:818('MainWorker')) received fatal signal 6 (Aborted)#033[0;0m
Jan 19 04:15:00 domoticz domoticz[680]: 2022-01-19 04:15:00.746  #033[1;31mError: siginfo address=0x3e8000002a8, address=0x7f7
1b71cc24b#033[0;0m


```

The events in the minute or so immediately before the crash don't involve anything that I know to use Python - they all relate to reports from Z-Wave or RFXCom433 sensors and internal dzVents scripts that checked device states then exited without changing anything.

Python plug-ins on the system are Plug-ins Manager and Shelly MQTT.

The signal itself wouldn't have been a problem if Mainworker had recovered gracefully and restarted. Hanging like this really messed up the system.  Unfortunately, monit didn't spot the problem as I'd just rebuilt the system on new hardware at the weekend and hadn't yet set up monit.

Any ideas?  Anything I can do to identify the problem Python code?

**Comment by jefft4** [comment]
Same again, a few days later.  Monit is now in place and checking the Dashboard URL, but didn't see the problem or restart things, so again the system was dead for a couple of hours until a cold human found it :-(

`Jan 21 04:15:00 domoticz domoticz[563367]: malloc(): unsorted double linked list corrupted
Jan 21 04:15:00 domoticz domoticz[563367]: Fatal Python error: Aborted
Jan 21 04:15:00 domoticz domoticz[563367]: Current thread 0x00007f25337fe700 (most recent call first):
Jan 21 04:15:00 domoticz domoticz[563367]: <no Python frame>
Jan 21 04:15:00 domoticz domoticz[563367]: 2022-01-21 04:15:00.019  #033[1;31mError: Domoticz(pid:563367, tid:563384('MainWorker')) received fatal signal 6 (Aborted)#033[0;0m
Jan 21 04:15:00 domoticz domoticz[563367]: 2022-01-21 04:15:00.020  #033[1;31mError: siginfo address=0x3e8000898a7, address=0x7f253d4c124b#033[0;0m`

There's nothing to suggest what is causing the problem, but it's interesting that it's exactly the same time of day, but does not happen every day.  I'll try to find any connection.

**Comment by waltervl** [comment]
Still an issue?

**Comment by jefft4** [comment]
Yes, though a bit less frequent since I removed the zigbee2mqtt plugin and went to the beta channel and MQTT autodiscovery.
Here are the last week or so's crashes:
`2022-02-12 04:15:00.458  Error: Domoticz(pid:1100237, tid:1100248('MainWorker')) received fatal signal 11 (Segmentation fault)
2022-02-12 04:15:00.458  Error: siginfo address=0x3e80010c9cd, address=0x7fa59132624b

2022-02-10 04:13:16.492  Error: Domoticz(pid:313406, tid:313453('OZW-driver')) received fatal signal 6 (Aborted)

2022-02-07 18:49:09.045  Error: Domoticz(pid:673, tid:1265('OZW-driver')) received fatal signal 11 (Segmentation fault)

2022-02-06 04:15:00.156  Error: Domoticz(pid:679, tid:822('MainWorker')) received fatal signal 11 (Segmentation fault)
2022-02-06 04:15:00.156  Error: siginfo address=0x3e8000002a7, address=0x7f69fecff24b
2022-02-06 04:15:10.146  Error: EventSystem: Warning!, lua script /home/domoticz/domoticz/
dzVents/runtime/dzVents.lua has been running for more than 10 seconds`

The OZW driver ones are new - hadn't seen those previously.  I get occasional issues with z-wave commands taking 8~10 seconds to hit the device, but these crashes don't match those times.  The MainWorker crashes are interesting in that they're now SEGFAULTs rather than SIGINFO.

**Comment by gizmocuz** [comment]
Could you try disabling all scripts/hardware (except MQTT) and test if that keeps stable ?
For OZW you could also move to ZWaveJS2MQTT

**Comment by jefft4** [comment]
I plan to test zwavejs2mqtt on a spare machine soon as I get time. Need to check that it understands all my devices before I do the work to replace 100+ nodes and their associated domoticz devices for real.
Unfortunately, disabling all scripts and hardware on the system that's throwing the exceptions isn't an option; it's my live system and it would have to be disabled for several days to prove the point.  The only hardware currently there is RFXCom and Z-Wave; I'd love to have everything on MQTT, isolate hardware handlers completely from the core logic engine.  
I'll see whether I can stand up a test system with a similar configuration but no hardware.

**Comment by waltervl** [comment]
If you are brave enough you can try latest beta, As a backup is made during the update you can revert back quickly: https://www.domoticz.com/wiki/Raspberry_Pi#Revert_to_backup_after_incorrect_beta_update

**Comment by jefft4** [comment]
Tested, migrated.  No problems with the core / mainworker in 10+ days since moving to zwavejs2mqtt (domoticz currently beta 14205).  I guess we conclude that the problem was most likely OZW-related.  Z-Wave performance feels better too.
Removing hardware drivers from the core and putting them at arm's length via MQTT is definitely a good thing IMO.  Happy to close this issue, if future recommendation with domoticz is to avoid OZW and use zwavejs.

**Comment by waltervl** [comment]
OK, thanks for your feedback. I will close this issue as OZW is deprecated and Zwavejs2MQTT is the way to go.
