### ISSUE TITLE
RFXcom values & graph "Spike" bug

### ISSUE THREAD

**Issue by soif** [domoticz/domoticz#5117]
Hi

I'm very happy running Domoticz since over 6 years, with many devices (279 used). _Thanks for your amazing work! 🍺_ 

Up to version v4.11539 (Build Hash: 6c6c27a56, Date: 2019-11-29 09:53:24), all was working well.

Config:
- Platform: linux debian 
- Domoticz running inside an LXC container (Proxmox Host)
- RFXcom 433Mhz USB tranceiver (Firmware v71) connected via USB PassThru (working reliabely since years)

I've recently updated to new beta versions:
- On 29 dec 2021 (cant remeber the exact version)
- then a few others, until:
- latest beta: V2021.1 (build 14082) Build Hash: 5c866dc2b, Date: 2022-01-19 08:34:54

From all of theses versions, all my RFXcom temperature/humidy sensors are showing spikes (at 264.2°C or 212.8°C or 1°C) while the average real temperature is around 19°. (see screenshot below)

I've also noticed some RFXcom errors in the log (I dont know it happened since the same update or not), ie:
`2022-01-20 12:24:23.820  Error: RFX usb: Invalid data received!....`

On the otherhand, all my RFXLink (LAN) type sensors, or Wifi sensors are working fine.

It looks like a bug while reading the serial port data.

- Is this a known issue (I did not find any related issue at Github)?
- If not, are there some test I could perform and report to you to better hunt the culprit? _(I'm confortable with the terminal)_
- BTW Is there a method (API, dzVent) other than manually remove (shift-click in the graph) the wrong datas, or making sql queries in the sqlite database?

HTH

![Screen Shot 2022-01-20 at 12 41 16](https://user-images.githubusercontent.com/101618/150333981-5f5db981-20e5-41cb-ac18-379e1c48d77f.png)

**Comment by gizmocuz** [comment]
I just checked with my two RFXCom transcievers and I have no issue with them.
How are you refferencing your RFXCom ? By USB port number (like ttyUSB1) or by device value-id name ?
Could you switch to the later one as this will always stay the same, maybe you are using the wrong port ?
Did you also perform a system update ? (apt-get update/upgrade) ? Maybe something is wrong with the USB port
Could you connect the RFXCom directly to the USB port and test this for a day (or two)

**Comment by soif** [comment]
Hi gizmocuz, Thank you for your very fast answer! 😎 

> How are you refferencing your RFXCom ? By USB port number (like ttyUSB1) or by device value-id name ?

I'm refering it by port number:  /dev/ttyUSB0

As this a  (LXC)  container, there are no other USB port connected to this container, except this one only. Because, to be available in the "guest" (the LXC container), a USB device connected to the "Host", needs to have a USB Passthru setuped on the container.
FYI : Here are the LXC settings of my Domoticz container for this RFXcom device:
```
lxc.cgroup.devices.allow: c 188:* rwm
lxc.mount.entry: /dev/ttyUSB0 dev/ttyUSB0 none bind,optional,create=file
```
**Those PassThru settings have been working flawlessly since years, for Domoticz/RFXcom !**

Following this bug, I've **even** setuped a udev rules (in the Host):
`SUBSYSTEM=="tty", SUBSYSTEMS=="usb", ENV{ID_MODEL}=="RFXtrx433", SYMLINK+="ttyUSBRFX"`

To ensure that the RFXtrx433 /dev/*  is ALWAYS named `ttyUSBRFX` (from the Host) and thus unique, and then I changed the LXC setting to remap it to the guest as:

```
lxc.cgroup.devices.allow: c 188:* rwm
lxc.mount.entry: /dev/ttyUSBRFX dev/ttyUSB0 none bind,optional,create=file
```
This has been successfull (Domoticz can talk to the device), but this unfortunately did not change anything to this bug.. Spikes are still there...

> Could you switch to the later one as this will always stay the same, maybe you are using the wrong port ?

As I explained just before, the /dev name was unique, and is now better enforced to be unique.
BTW From the domoticz "Guest", i've no access to  /dev/serial/by-id/ . It is only available from the host, and invisible from the guest.

>Did you also perform a system update ?

Sure! APT is up-to-date (Debian Buster)

> Could you connect the RFXCom directly to the USB port and test this for a day (or two)

Obviouly not, as the RFXcom USB device is connected to the host, then passThru to the guest...

-------
BTW, while on this subject , I noticed something that might be related (or not): After heavely searching on the forums about this RFXcom issue, I noticed that some people advised to disable the hadarware, then re-enable it.

I did disable it; but when I've tried to re-enable it, i noticed that there was no-longer any serial port to choose from the form's menu.

To re-enable it, I had to tweak the Javascript (inspired by [this post](https://www.domoticz.com/forum/viewtopic.php?p=202041&sid=977b21093f9e13c483fc6162c9cd752b#p202041)), to  create the /dev/ttyUSB0 option (in the form's menu), as it seems that the [GetSerialPort](https://github.com/domoticz/domoticz/blob/3861cc0e85aa8acdda29bfe77c04c133e310f233/main/Helper.cpp#L211) method from main/Helper.cpp is not detecting it. After rexamining the code, i can't figure why....

Re-assign it this way leaded to get Domoticz to again see and fetch the device datas, but spikes are still there...

This might be related... or not... (I might open a separate issue for that?)

**Comment by GravityRZ** [comment]
i would check for new firmware

current firmware is 1025 so it seems strange that you have version 71

![image](https://user-images.githubusercontent.com/16853535/150400779-138240c2-b014-4af0-a78b-ef472635c8ee.png)

**Comment by GravityRZ** [comment]
and unplugging the device and cleaning out the connectors will probably help also if errors are caused by bad connection(due to lower voltage on the device)

**Comment by gizmocuz** [comment]
It might also be worth trying to connect the transceiver to a physical computer (windows/linux) and install Domoticz there and let it run for a while to see if it has spikes as well
You do not have to modify any code (specially not javascript code). RFXCom has been supported since version 1.0 of Domoticz

**Comment by soif** [comment]
After some time, I've finally found the culprit. 😎 

**Short story**:

RFXcom (may be fixed in a recent firmware) does not filter invalid data, send it asis to domoticz, who do its job to  record it (as spikes), while RFlink (from the SAME sensor) succefully filters invalid data, and thus dont pass it to Dz.

**Long Story**:

-  I have a dozen of Temp/Humidity (with LCD) sensors around the house, shown as "Viking 02035, 02038, TSS320" in RFXcom, and also shown as "WTGR800 / FineOffset" in RFLink. 
- Both RFXcom and RFLink gateways are at the same place, receiving sensors transmissions.
- I've noticed that thoses spike are present ONLY in the FXcom logs, while the RFLink logs does not show any spikes  (for the exact same sensor) .
- The "fun" thing is that even the sensor which is at 1m from both RF gateways, is also showing spikes (in RFXcom logs)
- The sensors batterys were a little low : not that bad, as the sensor's LCD is still displaying values, and Dz still get valid data : 95% of the time for the RFXcom, 100% of the time for the RFLink
- I decided to replace all battery, and after a few days, I can say that **RFXcom logs dont show spikes** any longer !
- also those "RFXcom: Invalid data received" in the logs seems to have disappeared

**Conclusion**
- Battery that are a bit low (far from empty) tends to sometimes  make the RFXcom to receive and send data without any filtering, thus leading to spikes and some "RFXcom: Invalid data received" (I did not studied if those error log appear exactly at each spike time)
- RFLink reception is really more clever as it seems to automatically filter those invalid data
- Domoticz is rock-solid, and simply pass the datas received from the hardware, without any filtering.

So I guess we can close this issue 🍺 
_(and maybe warn RFXcom users about this)_

--------

> You do not have to modify any code (specially not javascript code). RFXCom has been supported since version 1.0 of Domoticz

Unfortunately, this particular problem (/dev/ttyUSB0 NOT being properly listed from the form) needs some fix. I'm gonna open a separate issue for that.

-------
BTW I've attached below a (php) script that can help to remove all spikes (outside of a range) from Domoticz history. Feel free to include it somewhere in the Domoticz repo, or ask me to make a PR for that.


```php
#!/usr/bin/php
<?php
/* 
This script delete sensor data that are outside the min-max range.

(Tested on Linux, should work in OSX, not tested on Windows)

Copyright Francois Dechery 2022
https://github.com/soif/

*/

// Domoticz full URL + port 
//Example:
//$prefs['domoticz_url']="http://login:password@192.168.1.250:8080";

$prefs['domoticz_url']="http://domoticz.lo.lo:8080";



// ####################################################################################################
error_reporting(E_ALL & ~E_NOTICE);

$idx=$argv[1];
$min_temp=$argv[2] or $min_temp=3;
$max_temp=$argv[3] or $max_temp=150;;
$min_hum=$argv[4];
$max_hum=$argv[5];
$script_name=basename($argv[0]);
if(! $idx){
	echo "An (IDx) argument is needed!\nUSAGE: $script_name IDX [min_temp] [max_temp] [min_hum] [max_hum]\n";
	exit(1);
}

//Get Domoticz sensor's datas ----------------------------------------------
$pad1=19;
$pad2=6;
$count=0;
$rows_del=array();

if($rows=CallApi("type=graph&sensor=temp&idx=$idx&range=day")){
	//print_r($rows);exit;
	foreach($rows as $id => $row){
		$error='';
		if($row['te'] < $min_temp){
			$error="Temp < $min_temp";
		}
		elseif($row['te'] > $max_temp){
			$error="Temp > $max_temp";
		}
		elseif($min_hum and $row['hu'] < $min_hum){
			$error="Hum < $min_hum";
		}
		elseif($max_hum and $row['hu'] > $max_hum){
			$error="Hum > $max_hum";
		}
		if($error){
			$count++;
			$rows_del[]=$row['d'];
			echo ' - '.str_pad($row['d'], $pad1); 
			echo str_pad($row['te'], $pad2); 
			echo str_pad($row['hu'], $pad2);
			echo $error;
			echo "\n"; 	
		}		
	}

	// ask to delete if any logs outside of the range ------------------------------------
	if($count){
		echo "Found $count points outside of the $min_temp - $max_temp temperature range.\n";
		echo "Do you want to delete them? ";
		$confirm=_Ask();
		if($confirm=='y'){
			echo "Deleting...\n";
			foreach($rows_del as $date){
				echo ' - '.str_pad($date, $pad1); 
				if(CallApi("type=command&param=deletedatapoint&idx=$idx&date=".str_replace(' ','+',$date).':00', false)){
					echo " OK";
				}
				else{
					echo " Failed";
				}
				echo "\n"; 
				//sleep(7);
			}
		}
		else{
			echo "Delete Canceled!\n";
		}
	}
	else{
		echo "All datas are in the $min_temp - $max_temp temperature range.\n";		
	}
}
else{
	echo "No Data for IDX $idx ! \n";
}



// ----------------------------------------------------------------------------------
function CallApi($query,$debug=false){
	global $prefs;
	$api_url=$prefs['domoticz_url'].'/json.htm?';
	$url="$api_url$query";
	if($debug){
		echo $url;
		return true;
	}
	if($data=file_get_contents($url)){
		$data=json_decode($data,true);
		if($data['status']=='OK'){
			if($data['result']){
				return $data['result'];
			}
			return true;
		}
		//echo "$api_url?$query";
	}
}


// ----------------------------------------------------------------------------------
function _Ask($str_choices='Yes,No', $sep=" ", $eol=" ",$message=""){

	if($str_choices){
		//echo "$str_choices ? ";
		$choices=explode(',',$str_choices);
		$n=count($choices);
		foreach($choices as $k=>$v){
			$n--;
			$choices[$k]=strtolower(substr($v,0,1));
			echo "[".strtoupper($choices[$k])."]".substr($v,1);
			if($n){
				echo "$sep";	//", "
			}
			else{
				echo " $eol";	//"? "
			}
		}
	}


	// Save existing tty configuration
	$term = trim(`stty -g`);
	system("stty -icanon");
	//wait answer
	while ($c = fread(STDIN, 1)) {
		$c=strtolower($c);
		if($choices and !in_array($c,$choices)){
			echo " ";
			continue;
		}
		//echo "\n";
		break;
	}
	// Reset the tty back to the original configuration
	system("stty '" . $term . "'");
	echo "\n";
	return $c;
}
?>


```

**Comment by gizmocuz** [comment]
Thanks for your feedback! Glad it is solved. Maybe the device sends a weaker RF signal if the batteries are lower...
Or it signals that the battery is low (with a 'bit' in the RF packet) and this is interpretated wrongly
If you can update to a newer firmware , and still have the low battery available, a new test would be great, because it might be solved in a newer firmware

**Comment by soif** [comment]
>Thanks for your feedback! 

YOU are (absolutely) welcome !

>Maybe the device sends a weaker RF signal if the batteries are lower...

certainly !

>Or it signals that the battery is low (with a 'bit' in the RF packet) and this is interpretated wrongly

I guess not, as RFXcom still logs good data 95% of the time... 
But maybe, this "Low Battery" bit, is not **always** sent, but rather only **sometimes**,  when we are at the edge of the internal sensor's detection of what his own battery is low, or not ...

_But in any cases, the RFLink firmware seems really more error safe than my current RFXCom firmware._

>If you can update to a newer firmware , 

Sure I will, but trying to do it thru the domoticz interface, always fails . 
_I guess this may be related to the no /dev/ttyUSB0 bug I encounter in the hardware form._

>and still have the low battery available, 

Unfortunately Not, sorry...

>a new test would be great, because it might be solved in a newer firmware

I'gonna sooner-or-later  _(it involve moving the RFXcom, directly to a Windows machine, in order to user their uploader tool)_ update to the latest firmware, and be sure I will report results, once the batteries will be lower.

_BTW while changing batteries in a dozen of those temp/hum sensors (who like to change their hardwareID when you replace their batteries), I really **enjoyed** the  a2916ed7ef0b6b64acfc2bf93fc5ef93e335bed3 (Keep Idx when Replace) commit ! 
A giant tedious work saver !!!!!!! ❤️ **THANK YOU**_

**Comment by GravityRZ** [comment]
well the constructive way would be
1 report it to the makers of RFXCOM
2 mention you get these issues when using the Viking/fineoffset protocol

i do not have these issues with any of my devices but i am not using viking/fineoffset but hideki and rubicson.

regarding Keep Idx when Replace commit.
i made a special battery unit with 2 wires which i hook up before i replace the batteries to avoid all this.

The next time i need to replace batteries i will try it out

**Comment by soif** [comment]
Once I'll update the RFXcom, if the issue still happen, I will for sure report it to RFXcom !

> i made a special battery unit with 2 wires which i hook up before i replace the batteries to avoid all this.

An absolutely brillant workaround! 😎  Well done ! 👏 👏 👏
