### ISSUE TITLE
Possible issue on thread locking for python plugin

### ISSUE THREAD

**Issue by Smanar** [domoticz/domoticz#5119]
Hello, I can't reproduce it on my side, tried on Raspbian and windows, but 

> 
> Vanilla Ubuntu headless server version 20.04.3 LTS
> After upgrading Domoticz from Beta 13949 to Beta 14081 the Domoticz log is flooded with the lines below.
> deCONZ still works in Domoticz, but high cpu.
> When going back to 13949 the log is normal again..
> (Zgateway is my name for deCONZ-bridge)
> 
> 2022-01-18 00:57:31.950 (Zgateway) Releasing lock for 'Zgateway'
> 2022-01-18 00:57:32.000 (Zgateway) Acquiring lock for 'Zgateway'
> 2022-01-18 00:57:32.000 (Zgateway) Releasing lock for 'Zgateway'
> 2022-01-18 00:57:32.050 (Zgateway) Acquiring lock for 'Zgateway'
> 2022-01-18 00:57:32.050 (Zgateway) Releasing lock for 'Zgateway'
> 2022-01-18 00:57:32.100 (Zgateway) Acquiring lock for 'Zgateway'
> 2022-01-18 00:57:32.100 (Zgateway) Releasing lock for 'Zgateway'
> 2022-01-18 00:57:32.151 (Zgateway) Acquiring lock for 'Zgateway'
> 2022-01-18 00:57:32.151 (Zgateway) Releasing lock for 'Zgateway'
> 2022-01-18 00:57:32.201 (Zgateway) Acquiring lock for 'Zgateway'
> 2022-01-18 00:57:32.201 (Zgateway) Releasing lock for 'Zgateway'
> 2022-01-18 00:57:32.251 (Zgateway) Acquiring lock for 'Zgateway'
> 2022-01-18 00:57:32.251 (Zgateway) Releasing lock for 'Zgateway'
> 2022-01-18 00:57:32.301 (Zgateway) Acquiring lock for 'Zgateway'
> 2022-01-18 00:57:32.301 (Zgateway) Releasing lock for 'Zgateway'
> 2022-01-18 00:57:32.351 (Zgateway) Acquiring lock for 'Zgateway'
> 2022-01-18 00:57:32.351 (Zgateway) Releasing lock for 'Zgateway'
> 2022-01-18 00:57:32.402 (Zgateway) Acquiring lock for 'Zgateway'
> 2022-01-18 00:57:32.402 (Zgateway) Releasing lock for 'Zgateway'
> 2022-01-18 00:57:32.452 (Zgateway) Acquiring lock for 'Zgateway'
> 2022-01-18 00:57:32.452 (Zgateway) Releasing lock for 'Zgateway'
> 2022-01-18 00:57:32.502 (Zgateway) Acquiring lock for 'Zgateway'
> 2022-01-18 00:57:32.502 (Zgateway) Releasing lock for 'Zgateway'

The plugin that provoke this issue is https://github.com/Smanar/Domoticz-deCONZ/blob/master/plugin.py
But no idea for why it impact only his version, do you think it can come from his python version ?

He is now on the version 14.093

**Comment by Smanar** [comment]
Ok, so, problem solved.
Sorry.
Was because a double python plugin installation, nothing to see with domoticz code.

**Comment by FilipDem** [comment]
Hi Smanar,
What do you mean with "Was because a double python plugin installation, nothing to see with domoticz code."
I have the same problem, however rather in plugins that are using threading (eg [https://github.com/FilipDem/Domoticz-NEST-plugin](https://github.com/FilipDem/Domoticz-NEST-plugin)).

**Comment by FilipDem** [comment]
Btw: this can easily be simulated by using the Multi-Threading example in domoticz.
This generates continuously these errors (I tested it on a Ubuntu environment).
