### ISSUE TITLE
How to use nvalue of humidity sensor in events?

### ISSUE THREAD

**Issue by Bram81** [domoticz/domoticz#512]
Hi,

I'm running a nodemcu on esp easy with a soil moisture sensor. After making a dummy switch, add a virtual humidity sensor and set up the right idx my virtual sensor get's updated in Domoticz without a problem. The thing is that I can't use the value of the sensor in any event, LUA or Blocky stating that there is being tried to compare a number to a nill value.. 
If I understand correctly the humidity sensor in domoticz can receive a nvalue which is the humidity level and a svalue, which is the state of humidity from dry to wet. 

Is there a way to use the nvalue in the eventsystem? Maybe by updating a custom user variable that gets updated with the nvalue of my sensor?

**Comment by szczukot** [comment]
Do you see any error in log ?
What type and subtype device do you have ?

**Comment by gizmocuz** [comment]
It is because its a dummy sensors, please use our forum, this has been explained a lot
