### ISSUE TITLE
MQTT AD Level names of selector switch are reset, as is the selector style.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5121]
I am on build 14082 in my test environment. In production I have my Zwave devices running met Auto Discovery.
I am in the process of switching my Zigbee devices to production with Auto Discovery too.
The cause of this issue is found here: https://www.domoticz.com/forum/viewtopic.php?p=285428#p285428
I changed the source in a way that optionsMap is only executed once when a device is created.
I did that for handle_auto_discovery_select and handle_auto_discovery_climate
It works perfect for ALL of my selector device created with Auto Discovery.
I strongly believe that in the config message ALL selections for the selector device are present.
So once it is created there is no need to change anything on the optionsMap again.
So please change the source like I did.

The second question on the same kind of devices is that currently the Selector Style is hardcoded to "0"
Please change that to: if more then 5 selections are present the Selector Style should be "1" as default.

**Comment by gizmocuz** [comment]
Please do not cross post here and on the forum
