### ISSUE TITLE
MQTT AD Selector switch level 0 not accessible.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5122]
Using build 14082.
My created (zigbee) selector switch has 18 levels from 0 to 170.
The first level is not accessible in the GUI.
I select the first level in zigbee2mqtt GUI then the last level in selected in Domoticz.
Pictures are from level 2 selected in zigbee2mqtt GUI
![21 01 2022_18 52 56_REC](https://user-images.githubusercontent.com/24824113/150576257-c4c8c3a4-a9df-492f-b7ea-a9cda78ed808.png)
![21 01 2022_18 53 26_REC](https://user-images.githubusercontent.com/24824113/150576273-56252f89-b607-40f6-8e4d-ac618269b7a3.png)

**Comment by SargonofAssyria** [comment]
Oeps, found it deactivate "Hide Off level".
Still this was the default from MQTT AD creation of the device.
So the default should be deactivate "Hide Off level"

**Comment by jvanderzande** [comment]
> Still this was the default from MQTT AD creation of the device. So the default should be deactivate "Hide Off level"

Pretty sure that's already the case:
```
	std::map<std::string, std::string> optionsMap;
	optionsMap["SelectorStyle"] = "0";
	optionsMap["LevelOffHidden"] = "false";
	optionsMap["LevelNames"] = tmpOptionString;

```
.. and just tested it which indeed did set that switch to off.

**Comment by SargonofAssyria** [comment]
Second Oeps, my error.

**Comment by gizmocuz** [comment]
And don't cross post between here and the Forum ! Continue on the Forum first!
You where in discussion about selector switches on Slack before the Forum, why did you not continue this thread on Slack ?
