### ISSUE TITLE
MQTT AD Neo NAS-AB02B0 sirene duration device is missing.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5123]
From this device https://www.zigbee2mqtt.io/devices/NAS-AB02B0.html#neo-nas-ab02b0 is a duration device missing.
This could be a setpoint device, or an other device which has an numeric input from 0 to 1000
Topic: homeassistant/number/0x842e14fffedb82ed/duration/config
Config:
`{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/Sirene/set/duration","device":{"identifiers":["zigbee2mqtt_0x842e14fffedb82ed"],"manufacturer":"Neo","model":"Temperature & humidity sensor and alarm (NAS-AB02B0)","name":"Sirene"},"json_attributes_topic":"zigbee2mqtt/Sirene","max":1000,"min":0,"name":"Sirene duration","state_topic":"zigbee2mqtt/Sirene","unique_id":"0x842e14fffedb82ed_duration_zigbee2mqtt","unit_of_measurement":"second","value_template":"{{ value_json.duration }}"}`
Please add this device.

**Comment by jvanderzande** [comment]
> This could be a setpoint device,

mmm ... At best I think it could be a number sensor, as defined in the TOPIC: homeassistant/**number**/0x842e14fffedb82ed/duration/config
These "number" devices are not supported at this moment.

**Comment by SargonofAssyria** [comment]
No problem with a "number" device.
Hopefully it gets supported soon.
I and probably others use this device to ways.
1. As doorbell with relative short duration and a nice melody
2. As a Sirene to get alarmed with longer duration and an alarming melody.
So I think that those 2 devices are used to most.

**Comment by gizmocuz** [comment]
Can't these number (config) parameters be set in Zigbee2MQTT / ZWaveJS2MQTT ?

Currently there is NO number device in Domoticz, and I doubt we will create one
This is a config parameter and I think (after a new stable) these should be able to set/configured via a 'setup' button , just like currently can be done in the OpenZWave hardware
(and yes you can set those as well via a API call)

**Comment by SargonofAssyria** [comment]
Tnx. I hope the number or setpoint device will become available in the future.
I think that in real life 3 devices will be used interactively (from the GUI)
melody, just to change the doorbell music.
duration, because depending on the doorbell music duration has to be set to 'synchronize' with the length of music.
volume, just because.
For the meantime I set those also from dzVents and duration via API call.

**Comment by gizmocuz** [comment]
I just received my Siren... funny device... lots of melodies that can not be used ;)
All can be set in the Zigbee2MQTT web interface as well.

I can now try to implement the number fields in the Domoticz Web GUI. These are configuration parameters and will need to be accessible via the hardware setup. (Like for instance is possible with OpenZWave, or RFXCom)

If you  want to adjust these values from a script, you still need to call a JSON API, it will probably be easier than to send a MQTT message.

**Comment by waltervl** [comment]
Any progress on this issue? Perhaps already resolved?

**Comment by SargonofAssyria** [comment]
There is (still) no NUMBER device, so not really solved in Domoticz.
I found my way around it by using mosquitto to set / change different setting, so that sirene can be used as doorbell and as alarm sirene. I do that by dzVents. I use 8 seconds for a doorbell and 30 seconds (or more in case of fire (smoke sensor)) for alarm.
I set melody, volume, duration and alarm by mqtt for the different purposes.
Duration is the only device not yet present in Domoticz.

**Comment by gizmocuz** [comment]
There are number devices! Press the setup button in the hardware properties overview

**Comment by SargonofAssyria** [comment]
Nice, but how can that 'device' be accessed by dzVents?

**Comment by gizmocuz** [comment]
Via the json api , use the same calls as the web interface

**Comment by SargonofAssyria** [comment]
Oke, tnx, so basically almost the same as the mosquitto route.

**Comment by gizmocuz** [comment]
Or make switches that call the http api, use these in the scripts

**Comment by gizmocuz** [comment]
And no it’s easier to call the json api and does not depend on mosquito clients or libraries

**Comment by waltervl** [comment]
Now I am confused. That number device, is that a Domoticz device created from a Zigbee2mqtt device? If yes, why would it not be accessible by normal dzvents functionality?

**Comment by SargonofAssyria** [comment]
Your right, but I already have a working system. Tnx, anyway.

**Comment by waltervl** [comment]
I guess you are talking about the zigbee2mqtt Api and not the domoticz api....

**Comment by gizmocuz** [comment]
No the domoticz api … what you see as calls in the browsers network logs
Anyway, I was replying about the mentioning that numbers where not implemented

**Comment by waltervl** [comment]
What Domoticz Api call can be used then? Is it already documented, else I will do that. What type of Domoticz device is created from a mqtt ad number device?
