### ISSUE TITLE
Blinds problem after update 14081

### ISSUE THREAD

**Issue by Mike19700** [domoticz/domoticz#5124]
I use zigbee blinds switches with the Deconz USb stick.
All worked fine until the update 14081

If the blinds are open, the status is: Closed
When I press the close button, the blinds are indeed closing.
After the blinds are closed, the status changes to open.
There is no way I can open the blinds with Domoticz, only with the switch mounted on the wall.
Once the blinds are opened with the wall switch, the status goes to close again.
Then I can close them with Domoticz again.

When I switch from 'blinds inverted' to 'blinds', the status switches to open.
Then I press 'close blinds' in Domoticz, the status immediate turns into closed.
If the blinds are closed, I can not open them with Domoticz.

When I switch from 'blinds' to 'blinds + stop', the status switches to closed.
When I push the slider to 99%, the blinds close.
When I push it to 100%, the blinds open.
When I push the slider to 1%, the blinds open.
When I push the slider to 0%, the blinds close again.

My conclusion is that the open and closed status are inverted somehow.

**Comment by jvanderzande** [comment]
Guess this is relayed to this discussion: https://www.domoticz.com/forum/viewtopic.php?f=6&t=37848 ?

**Comment by Mike19700** [comment]
Yes. This one was also opended by me.

**Comment by jvanderzande** [comment]
Are you sure this behavior changed as this "quirky" behavior has always been there for inverted blinds and really needs to be revisited as elaborately discussed [here](https://github.com/domoticz/domoticz/issues/5017)?
You are using the Deconz plugin ...right?  ... not the HA AD Zigbee2MQTT interface?

**Comment by Mike19700** [comment]
It worked both ways. Inverted and 'normal'.
It used to work until earlier this week with inverted blinds.
I problem started with version 14801.
Yes I use the Deconz plugin.

**Comment by gizmocuz** [comment]
@Mike19700 , could you tell us the version (+/-) you used where everything was working normally for you ? When was the last time you updated ?
Could you try the new MQTT Auto Discovery hardware in combination with Zigbee2MQTT ?

**Comment by Mike19700** [comment]
I constantly update to bèta versions.
I thought is was 14065 that went well.
After that it got wrong.
The version I currently have is: 14092.
I will try the MQTT Auto Discovery hardware.
I'll get back to you.

**Comment by gizmocuz** [comment]
Thank you for the information.

These are the latest changes between 14065 and 14081

```
C11974  V14081 - 24e7b76a0bb76f471117691a5328724516932695 24e7b76a0 - Mon Jan 17 15:17 : MQTT-AD: Better "hs" support
C11973  V14080 - 41e11f829f6c6c57b2c66c5e5ff4d5f6d1405bd8 41e11f829 - Mon Jan 17 13:59 : Fix compile warning (and use internal reader)
C11972  V14079 - 6350f3544dea5f3f748496888f037d17b5ee535c 6350f3544 - Mon Jan 17 13:46 : MQTT-AD: Escaping special characters
C11971  V14078 - b120b0041b88f0abdc363a5ac7f96d119140562f b120b0041 - Mon Jan 17 13:36 : Merge pull request #5113 from guillaumeclair/development
C11970  V14077 - 67c349a22924fcdf00ad8b49d0b63003322a0e3d 67c349a22 - Mon Jan 17 12:58 : Fixed compile warnings under windows
C11969  V14076 - 0f31858e1acd2bc4be74392fe705c8863d7bacb9 0f31858e1 - Mon Jan 17 12:57 : MQTT-AD: making sure correct discovery topic is matched (Fixes #5114)
C11968  V14075 - 7259c5139dde78ab4b228aa211f9f01a14be7e19 7259c5139 - Mon Jan 17 10:38 : Fix a bug in variables name in alertlevel function
C11967  V14074 - f64304efb7c74a7f37f237a06c16c8a5544a14f7 f64304efb - Sun Jan 16 16:48 : Allow hardware to declare manual switches they are able to handle. (#4923)
C11966  V14073 - 4fcda55f3a16609230c6986d006011bd621169e2 4fcda55f3 - Sun Jan 16 13:18 : Partly fix for Meter Counter report
C11965  V14072 - 63e2f7b97af59bb059925257413d9943379c4ddf 63e2f7b97 - Sun Jan 16 08:43 : MQTT/AD: Fixes for Fibaro FGRGBW dimmer (Issue #5069) (#5100)
C11964  V14071 - f47572654ca8a183e51ee9814544d63fb9a91ee0 f47572654 - Sun Jan 16 07:47 : MQTT-AD: Making sure JSON object is not a object
C11963  V14070 - 0bf7a176f8e2aa08deeb50ee145a5e4bec3efe57 0bf7a176f - Sat Jan 15 14:20 : MQTT-AD: putting unknown sensor types back into general type
C11962  V14069 - b2a1ebf50c600997f61e7297d54f96db678b441b b2a1ebf50 - Sat Jan 15 12:48 : MQTT-AD: Added more exception information
C11961  V14068 - 16801a0a494192c86a1038dbef45b7cc5697dbb4 16801a0a4 - Sat Jan 15 12:05 : MQTT-AD: Added detection of CT nodes (needs more work from other pR)
C11960  V14067 - b36f2bc650da0c0c1d9ba808d980b1a4015a2512 b36f2bc65 - Sat Jan 15 09:41 : Replace light/switch now only transfers new HardwareID/DeviceID/Unit to the old device
C11959  V14066 - 13523bbe6e81aa21fd351712b791772db25ae0ab 13523bbe6 - Sat Jan 15 09:38 : Making sure a new sensor is created (could already exist a device with same type/id)
C11958  V14065 - b66a52e1357337afe893958538713a161e92a88f b66a52e13 - Sat Jan 15 06:29 : Updated History

```

Which can also be seen here

https://github.com/domoticz/domoticz/commits/development

There have been no changes in the GUI and code related to the issue you are seeing.
Most (If almost not all) are MQTT-AD related

Did you maybe update the Deconz plugin ?

**Comment by Mike19700** [comment]
I did not update the DeConz plugin.
At the moment I am struggling to get MQTT working.
I see messages from my devices with zigbee2mqqt but I can not see any new devices in Domoticz.
I uninstalled deConz, removed the plugin, and removed the Deconz hardware in Domoticz.
If you have any guide for what I am doing wrong.. I'll be glad to hear them -;)
I have to leave for a couple of hours now.
Be back at the end of the afternoon.
in thanks for the effort so far.

**Comment by gizmocuz** [comment]
There is a quide here

https://www.domoticz.com/wiki/MQTT

"Add hardware "MQTT Auto Discovery Client Gateway"

**Comment by Mike19700** [comment]
Damn... Still no devices in Domoticz.
Working on it.
To be continued.

**Comment by gizmocuz** [comment]
Please tell us what's not working... Did you install docker-compose, did you install a MQTT broker (via docker-compose) and did you install ZWaveJS2MQTT (docker-compose)
I updated the guide a little bit to include links to docker-compose files

https://www.domoticz.com/wiki/ZwaveJS2MQTT

**Comment by Mike19700** [comment]
> Please tell us what's not working... Did you install docker-compose, did you install a MQTT broker (via docker-compose) and did you install ZWaveJS2MQTT (docker-compose) I updated the guide a little bit to include links to docker-compose files
> 
> https://www.domoticz.com/wiki/ZwaveJS2MQTT

It is zigbee, not Zwave.

What I installed:
Domoticz... of course.
Zigbee2MQTT
npm 8.3.1
mosquitto 1.5.7
mqtt 4.3.1
nvm 0.35.3
node.js 16.13.2

I did not use a docker.

When I start zigbee2mqqt with
cd /opt/zigbee2mqtt
npm start
I see 4 devices. Also in the frontend of zigbee2mqtt.
In domoticz I selected 'Accept new hardware'
I use the following settings with MQTT Auto Discovery Client Gateway with LAN Interface
![Zigbee2MqQQT](https://user-images.githubusercontent.com/98214950/150747163-0b690f47-8149-40ed-8a6a-947f95526402.PNG)
No new devices appear in Domoticz, even when I add new devices in Zigbee2MQQT.

**Comment by gizmocuz** [comment]
Why are you not using docker and installing all these packages ?
Anyway, in Zigbee2MQTT (Or ZWaveJS2MQTT) you have to enable the Home Assistant Integration, select the advanced and as topic choose 'homeassistant' and I have the next to checkboxes enabled. And press Submit
That you can see your devices in Zigbee2MQTT is great, but that does not tell that you can connect to your MQTT broker
Please use a program like 'MQTT Explorer' to connect to your MQTT Broker and you should be able to see the autodiscovery topic (homeassistant) and some devices

**Comment by Mike19700** [comment]
It works. Thank you. Perhaps a good idea to add this in the wiki.
I don't use docker because when buster came out for the Rpi I didn't know it existed. I will definitely use that for Bullseye.
Let's solve some other problems before we get started with Bullseye.
I can check tonight what's going wrong with my blinds.
Thanks again for your input.

**Comment by gizmocuz** [comment]
Great it's working! Yes docker exists for quite a long time now, also for buster. I don't use Bullseye
What part was not that clear that needs to be added to the Wiki ?

**Comment by Mike19700** [comment]
Well, it is a bit hard to find but at last I found it.
If was the line 'homeassistant: true' in: /opt/zigbee2mqtt/data/configuration.yaml
I installed al the things I need from [Domoticz MQTT wiki](https://www.domoticz.com/wiki/MQTT)
On that page in the section 'Add hardware "MQTT Auto Discovery Client Gateway"', the wiki refers to: ' Both zwavejs2mqtt and zigbee2mqtt default to 'homeassistant' '.... I did not click on the link on [Domoticz Zigbee2MQTT wiki](https://www.domoticz.com/wiki/Zigbee2MQTT). So I missed that part.
After changing homeassistant: false into homeassistant: true it worked.
I know making a wiki is damn hard to make it fool proof. Says the fool.

**Comment by Smanar** [comment]
Hello, just a question before I update the plugin, you don't project a rollback to keep the compatibility with other plugin that don't use the beta branch ?

**Comment by Mike19700** [comment]
When installing a beta, Domoticz makes a backup in the backup directory.

**Comment by gizmocuz** [comment]
@Mike19700 , That setting can also be set by using the web interface of Zigbee2MQTT ;)

**Comment by Mike19700** [comment]
I've scrolled al the tabs and found it. Thanks.
GUI makes it simpler.

**Comment by waltervl** [comment]
> I've scrolled al the tabs and found it. Thanks. GUI makes it simpler.

Can you make a screenshot of that GUI entry in Zigbee2MQQTT and post it here, than I will update the Zigbee2MQTT wiki page. Official documentation only shows the configuration.yaml way.

**Comment by gizmocuz** [comment]
![image](https://user-images.githubusercontent.com/2265299/151312348-6792a825-57a8-450c-991c-d6b5cc9b216e.png)
![image](https://user-images.githubusercontent.com/2265299/151312381-83975bc4-bd70-4f64-ad00-8176e6f8fa48.png)

**Comment by Mike19700** [comment]
i am busy with upgrading my Pi with docker.
It takes some time to get it work.
To be continued...

**Comment by waltervl** [comment]
Zigbee2mqtt Wiki page has been updated. Thanks.

**Comment by Mike19700** [comment]
Okay. So far I got my system working again with version 14040.
I'am sorry to say it but my blinds are working good at the moment.
I still got the idea that after this version someting went wrong with the blinds of Domoticz.
When I have the docker active I'll try to get the latest version and see if it works.

**Comment by gizmocuz** [comment]
Okey I think blinds are working correctly. Please feel free to re-open this issue after you have installed docker and can test with the latest version
