### ISSUE TITLE
Evohome (Web API) - incorrect mapping when setting EvoTouch state

### ISSUE THREAD

**Issue by mlstolk** [domoticz/domoticz#5125]
Setting the EvoTouch Web status via the Domoticz web frontend or script has an incorrect mapping to the Honeywell online API. It looks like the array indices are shift one state. The Domoticz log shows the right switch, but every state from Day Off With Eco is shifted by one state. Probably because that specific state is missing in a definition/mapping somewhere.

The effects of setting the EvoTouch mode from within Domoticz are as follows (shown as Domoticz Setting -> Effect on EvoHome via Web API):

Normal -> Normal (works OK)
Economy -> Eco/Boost (works OK)
Away -> Away (works OK)
Day Off -> Day Off (works OK)
Day Off With Eco -> Custom (**mismatch**)
Custom -> Heating Off (**mismatch**)
Heating Off -> Unknown (**mismatch**)

The mismatch shows only one way: while _setting_ the state from Domoticz. Periodically Domoticz updates its status by retrieving it from the EvoHome API - those updates are correctly matching the actual state of the device. 

This means, setting EvoTouch to 'Custom' from domoticz, wrongly results in 'Heating Off' on the actual EvoTouch device (and Honeywell online environment). After a minute or so, Domoticz updates its state from the Honeywell API and then also shows 'Heating Off' (while 'Custom' was intended). Switching it to 'Heating Off' will result in the state 'Unknown', which resets to 'Normal' after a minute or two.

- Multiple people have hinted at this behavior (https://www.domoticz.com/forum/viewtopic.php?p=275353). 
- The problem occurs with the ATC928G3000 via Web API plugin. (I did not experience it with the ATC928G2000 with HGI80).
- Present in Domoticz Version: 2021.1 (build 14098) - (Running on a Pi 3B)

**Comment by gordonb3** [comment]
Yes, someone added a new system mode that is not supported by the online method, but instead of appending it he inserted it and caused the index numbers to shift.

**Comment by gizmocuz** [comment]
Oeps... Sorry, you want me to revert this PR ? I thought it had created a new ID for the new sensor ?

**Comment by mlstolk** [comment]
It's about the insertion of the mode 'Day Off With Eco' which seems to miss in the official Honeywell API and has incremented all Domoticz mode IDs from there. I am not sure which PR caused that, but either reverting it or moving that specific mode to the end of the arrays/lists (after 'unknown') should fix it.

**Comment by gordonb3** [comment]
#4634

**Comment by gizmocuz** [comment]
@gordonb3 , do you want me to revert this PR ?

**Comment by gizmocuz** [comment]
Or move 'cmEvoDayOffWithEco' to the bottom of the enum, would that solve the issue ?

**Comment by mlstolk** [comment]
I expect moving cmEvoDayOffWithEco to the end of the enum and also matching the position in CEvohomeBase::m_szWebAPIMode (shifting its position to before the entry 'unknown').

But I have not yet tested this solution myself.

**Comment by gordonb3** [comment]
Doesn't bother me. I don't use this any more. I just received a notification and happened to know the cause. Logical path is to extent the X-translate array that is used to get from GUI select IDs to Evohome specific codes and remap the affected modes. Obviously some code should be added to let the module reject the unsupported system mode but that is regardless of whether you'd want to rearrange the modes in the GUI.

Before you ask, I no longer have a working dev environment for Domoticz.

**Comment by gizmocuz** [comment]
I have reverted the PR. Maybe the author can make a new PR that adds the new field and not causing a ID shift.

@gordonb3 , are you using another system to control separate thermostats or are you not using separate thermostats anymore ?
(Cause I was tempted getting a system like this)

**Comment by gordonb3** [comment]
I don't use Domoticz any more, not anything that still resembles it anyway.
