### ISSUE TITLE
Manual Light/Switch complete domoticz stops working

### ISSUE THREAD

**Issue by mzonneveld** [domoticz/domoticz#5128]
Hi there,
I have updated my domoticz to the latest beta version.
Version: 2021.1 (build 14104)
Build Hash: cc66e49eb
Compile Date: 2022-01-24 17:18:02
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

But when trying to add a switch using the button [Manual Light/Switch], the complete domoticz website stops until I restart the domoticz service through ssh.

https://user-images.githubusercontent.com/52718067/150867631-7568b2d6-a9d7-49f3-9a73-22add5e13ed0.mp4

**Comment by kiddigital** [comment]
Weird.. did the same test but it works fine (same version 14104). But I did have the Dummy hardware module installed and that is shown as the 'Hardware' when pressing the Manual Light/Switch button. In your case, it seems empty. Try adding the Dummy hardware module first.

**Comment by svollebregt** [comment]
The same issue occurs at my side and I do have multiple dummy hardware modules added. I do also get the add manual switch pop-up, but the hardware list is empty and Domoticz freezes until a service restart.

**Comment by mzonneveld** [comment]
I added a dummy hardware device in the dummy-hardware.
That works. But still the button [Manual Light/Switch] crashes the domoticz.
Still don't see what happens, maybe when the popup is retrieving the hardware-list

https://user-images.githubusercontent.com/52718067/150932052-0414e1d8-2967-4b70-aabc-d0fe773e9fbe.mp4

[domoticz_crash.log](https://github.com/domoticz/domoticz/files/7931506/domoticz_crash.log)

**Comment by mzonneveld** [comment]
I've found someone having the same problem also:
https://www.domoticz.com/forum/viewtopic.php?p=285719

**Comment by kiddigital** [comment]
Might be related to PR #4923 , see forum thread for details.

**Comment by jvanderzande** [comment]
Confirm there is a hardcrash when using that button and can be avoided by testing pBaseHardware for being nullptr returned by m_mainworker.GetHardware(ID) in WebServer.cpp. Not sure if that is the real solution  so thought I mention it here.

**Comment by gizmocuz** [comment]
Thanks for reporting! Fixed in beta 14105
This was definitely not tested correctly tested

**Comment by Ashitaka57** [comment]
b 14105 Tested and Ok. Thx a lot.
