### ISSUE TITLE
MQTT auto-discovery - problem with zigbee CCT white bulbs with groups, timers

### ISSUE THREAD

**Issue by jefft4** [domoticz/domoticz#5131]
I'm seeing a lot of errors whenever domoticz tries to command my zigbee (Hue, Innr) tunable white bulbs. The widgets in the UI are correct - colour temperature only, no RGB.

The errors occur at many times, but when I use the UI, the bulbs behave correctly.  If the bulbs are switched as part of a group or a scene, they simply do not work at all.
- scenes and groups cannot switch these bulbs ON -> errors as per log snippet below, bulb state in the UI remains OFF
- groups can switch the bulbs OFF.
- web UI and mobile app both work fine - on, off and CCT changes all okay, UI shows correct state.
- Timers on these lamps individually don't work; same error when the timer executes.
- I get the same errors in the log when creating timers for a lamp.

All these lamps (I have 8) were working fine with the old zigbee2mqtt plugin; the issue is somehow related to how autodiscovery has detected and configured them, I guess, but it's strange that it doesn't affect manual switching via the UI.

Log snippet for switching on a group of bulbs:
`2022-01-22 15:46:00.669 Error: MQTT auto-discovery: Color device unhandled color_temp_value_template (0x0017880108a8eba7_light_zigbee2mqtt/Dining rear lamp)
2022-01-22 15:46:00.721 Error: MQTT auto-discovery: Color device unhandled color_temp_value_template (0x804b50fffe3f41b0_light_zigbee2mqtt/Dining room table lamp)
2022-01-22 15:46:00.772 Error: MQTT auto-discovery: Color device unhandled color_temp_value_template (0x00158d0005076c0c_light_zigbee2mqtt/Dining front lamp)`

Looking at the Z2M log, it appears that no messages were published to the bulbs when the group was switched on; I only see messages setting mode/colour when I manually switch the lamps.  I guess that means no MQTT message was generated by domoticz to instruct Z2M.

Domoticz - beta 14093 (same issue existed in 14065 also)
System - Intel i3 7th gen, Ubuntu 20.04 LTS
Zigbee - Z2M latest version, zzh! USB stick

**Comment by gizmocuz** [comment]
Could you post the 'config' of one of these bulpbs ? You can use a program calles 'MQTT Explorer', in the auto discovery topic (probably homeassistant) there should be a 'light' and underneat it you should be able to find your lights, each light has a config object.
Could you post the complete topic and config of one of your lights ? (homeassistant/light/xx/config)

**Comment by jefft4** [comment]
Hi gizmocuz, and sure!  Here's one, looks like the Hue bulb 'Dining rear lamp' in domoticz:

{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"brightness":true,"brightness_scale":254,"color_mode":true,"command_topic":"zigbee2mqtt/0x0017880108a8eba7/set","device":{"identifiers":["zigbee2mqtt_0x0017880108a8eba7"],"manufacturer":"Philips","model":"Hue white ambiance E27 with Bluetooth (9290022169)","name":"0x0017880108a8eba7","sw_version":"1.53.3_r27175"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"json_attributes_topic":"zigbee2mqtt/0x0017880108a8eba7","max_mireds":500,"min_mireds":150,"name":"0x0017880108a8eba7","schema":"json","state_topic":"zigbee2mqtt/0x0017880108a8eba7","supported_color_modes":["color_temp"],"unique_id":"0x0017880108a8eba7_light_zigbee2mqtt"}

Also - confirmed still an issue in 14105.

**Comment by jefft4** [comment]
Additonal info - dzVents.
In trying to work around the lamps not working with timers, I created a simple dzVents event to switch a lamp on at 10% and increase the level by 10% every minute for 5 minutes.  The lamp switched on at its previous level and stayed there.  No change in level throughout the 5 minutes; no errors in the log.  An even simpler event, simply lamp.setLevel(5), also failed to do anything.

**Comment by gizmocuz** [comment]
Could you try with the latest beta version ?

**Comment by jefft4** [comment]
Same problem remains in 14105.  My updatebeta isn't finding anything newer than that right now.

**Comment by gizmocuz** [comment]
Ahhh your running Linux probably... New build is underway, it will take 30 minutes... (Docker will also be updated then)

**Comment by jefft4** [comment]
I am indeed; Ubuntu.  I guess you build first on Windoze.  Got 14117 now; thanks.

A quick test with a on-bulb scene and timers looks good; lamp is responding as expected and there's nothing adverse in the log.  I'll let you know if anything strange happens when the live scenes run this evening, but first view is, that's fixed it :-)

**Comment by gizmocuz** [comment]
Great, thanks for the feedback!
