### ISSUE TITLE
/dev/ttyUSB0 not listed in the Hardware Form (LXC Container)

### ISSUE THREAD

**Issue by soif** [domoticz/domoticz#5134]
Following comments in #5117

### Configuration
- Domoticz V2021.1 (build 14093) - Status: Build Hash: d7835b751, Date: 2022-01-20 15:15:25
- Debian Buster, amd64 (uptodate)
- Running in an LXC container (guest), from a Proxmox 6.3 (Host)
- Notice that this Container, was migrated from the original OpenVz container of the previous Proxmox version.
- USB port is "mapped" from the host using this  LXC, configuration:  
```
lxc.cgroup.devices.allow: c 188:* rwm
lxc.mount.entry: /dev/ttyUSB0 dev/ttyUSB0 none bind,optional,create=file
```

### Bug Description:
When Editing/Adding a RFXCom in the Hardware page, **the Serial Port (/dev/ttyUSB0) is not listed in the menu** (list is empty).
Despite this fact, The RfxCom device is working fine (receives data).

### Notes

While fighting with #5117, I've once disabled the RFXCom hardware (which leaded to empty the memorised serial port). When trying to re-enable it, I had to hack the javascript (inspired by [this post](https://www.domoticz.com/forum/viewtopic.php?p=202041&#p202041)) responsible of making the menu, in order to get the missing /dev/ttyUSB0 option available in the menu. Once submitted, The RFXCom was again enabled, and working fine (except for firmware upload).

It seems that the [GetSerialPort](https://github.com/domoticz/domoticz/blob/3861cc0e85aa8acdda29bfe77c04c133e310f233/main/Helper.cpp#L211) method from main/Helper.cpp is not detecting it. After rexamining the code, i can't figure why....
Permissions (in the guest) seems fine:

```
root@domo-ct:~/domoticz# ll /dev/
total 0
crw--w---- 1 root tty     136,  9 Jan 21 18:18 console
lrwxrwxrwx 1 root root         11 Jan 21 18:18 core -> /proc/kcore
lrwxrwxrwx 1 root root         13 Jan 21 18:18 fd -> /proc/self/fd
crw-rw-rw- 1 root root      1,  7 Jan 21 18:18 full
drwxr-xr-x 2 root root          0 Jan 21 18:18 hugepages
lrwxrwxrwx 1 root root         12 Jan 21 18:18 initctl -> /run/initctl
lrwxrwxrwx 1 root root         28 Jan 21 18:18 log -> /run/systemd/journal/dev-log
drwxrwxrwt 2 root root         40 Jan 21 18:18 mqueue
crw-rw-rw- 1 root root      1,  3 Jan 21 18:18 null
c--------- 1 root root      5,  2 Jan 27 17:27 ptmx
drwxr-xr-x 2 root root          0 Jan 21 18:18 pts
crw-rw-rw- 1 root root      1,  8 Jan 21 18:18 random
drwxrwxrwt 2 root root         40 Jan 21 18:18 shm
brwx------ 1 root root      0, 25 Jan 21 18:18 simfs
lrwxrwxrwx 1 root root         15 Jan 21 18:18 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 root root         15 Jan 21 18:18 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 root root         15 Jan 21 18:18 stdout -> /proc/self/fd/1
crw-rw-rw- 1 root root      5,  0 Jan 21 18:18 tty
crw--w---- 1 root tty     136,  0 Jan 21 18:18 tty1
crw--w---- 1 root tty     136,  1 Jan 21 18:18 tty2
crw-rw---- 1 root dialout 188,  0 Jan 21 18:18 ttyUSB0
crw-rw-rw- 1 root root      1,  9 Jan 21 18:18 urandom
crw-rw-rw- 1 root root      1,  5 Jan 21 18:18 zero
```

### Screenshot
![Screen Shot 2022-01-27 at 14 48 02](https://user-images.githubusercontent.com/101618/151384311-97dcdec9-e0d3-4acc-963b-42ff0b5cbfc3.png)

**Comment by kiddigital** [comment]
Domoticz process is running as root?

What happens if you add 'o+rw' to the serial port?

**Comment by gizmocuz** [comment]
I'm pretty sure it's a permission issue, this might help:

https://askubuntu.com/questions/133235/how-do-i-allow-non-root-access-to-ttyusb0

Not sure why you are running Domoticz in a LXC container, you might consider running it via docker (compose)?

https://hub.docker.com/r/domoticz/domoticz

**Comment by soif** [comment]
> Domoticz process is running as root?

YEP, in order to not care about any permissions issue

> What happens if you add 'o+rw' to the serial port?

```
root@domo-ct:~# ll /dev/ | grep ttyUSB0
crw-rw---- 1 root dialout 188,  0 Feb  1 13:08 ttyUSB0

root@domo-ct:~# chmod o+rw /dev/ttyUSB0 
root@domo-ct:~# ll /dev/ | grep ttyUSB0
crw-rw-rw- 1 root dialout 188,  0 Feb  1 13:08 ttyUSB0

root@domo-ct:~# l/etc/init.d/domoticz.sh restart
```
---> no change, RFCom Hardware page still miss the SerialPort in the menu

**Comment by soif** [comment]
> I'm pretty sure it's a permission issue, this might help: 
> https://askubuntu.com/questions/133235/how-do-i-allow-non-root-access-to-ttyusb0

As Domoticz is running as root, this should not be related...

> Not sure why you are running Domoticz in a LXC container, you might consider running it via docker (compose)?

Running Domoticz as a Docker instance, would either need another dedicated server, (as this one is running Proxmox) or either  run the docker instance, inside a Proxmox VM or LXC container, but this would just add another  abstraction layer........

**Comment by gizmocuz** [comment]
I am not considering this as a issue or a bug in Domoticz.
Your USB devices should be found , in this case specially via serial-by-id
This issue is LXC related and in the mentioned forum post there seems to be a work around
Probably there are others having this issue too (non Domoticz related) and found a solution
But as mentioned, my solution is just to use standard docker, your LXC should support this
A container in a container should not be a problem, and dockers runs almost natively so no speed decrease
So you use Proxmox and installed a virtual machine, under this you run LXC ?

**Comment by soif** [comment]
> I am not considering this as a issue or a bug in Domoticz. 
>Your USB devices should be found , in this case specially via serial-by-id 
> This issue is LXC related and in the mentioned forum post there seems to be a work around 
>Probably there are others having this issue too (non Domoticz related) and found a solution 

They are plenty ways, to remap a USB port to a LXC container. After reading many "forums posts", I've used the trivial way that seems to work for many users who remap their USBserial devices from the host to the LXC container, while they succefully use OTHERS domotic software than Domoticz (HomeAssistant, Jeedom, etc...)... 

In this issue, I try to understand the correct way to either make Domoticz happy, asis, _or maybe slightly change the GetSerialPort method in order that Domoticz natively recognize a USB tty trivialy mapped into an LXC container._

------

After carrefully read theDomoticz [GetSerialPorts](https://github.com/domoticz/domoticz/blob/3861cc0e85aa8acdda29bfe77c04c133e310f233/main/Helper.cpp#L211) method, I've made some tests that seem to fix part of the issue (ports beeing correctly listed in the Hardware menu), but I would need some help, to choose **the right method to make Domoticz REALLY happy**.

Contexts:

**1) The current (LXC) mapping  redirects [HOST]/dev/ttyUSB0 to [LXC]/dev/ttyUSB0.**
```
root@domo-ct:/dev# ls -l /dev | grep ttyUSB0
crw-rw-rw- 1 root dialout 188,  0 Feb  2 11:37 ttyUSB0
```
---> Dz dont see it ! 😞 

_I guess that because d_type is neither a [DT_CHR, nor a DT_LINK](https://github.com/domoticz/domoticz/blob/3861cc0e85aa8acdda29bfe77c04c133e310f233/main/Helper.cpp#L376), it is NOT listed, despite:_
```
root@domo-ct:/dev# file /dev/ttyUSB0 
/dev/ttyUSB0: character special (188/0)
```
_It seems that /dev/ttyUSB0 is really a "character special" (DT_CHR)... But I certainly miss some knowledge about linux file types (or may be it's a bug)_



I've then tried two things (that results in the device being correctly listed in Hardware Menu) :

**2) Then, making a symbolic link to it as "/dev/ttyUSBrfx"**
```
root@domo-ct: ln -s /dev/ttyUSB0 /dev/ttyUSBrfx
root@domo-ct:/dev# ls -l /dev | grep ttyUSB0
crw-rw-rw- 1 root dialout 188,  0 Feb  2 11:37 ttyUSB0
lrwxrwxrwx 1 root root          7 Feb  2 11:26 ttyUSBrfx -> ttyUSB0
```
---> Dz seet it 😎 

_because [dt_type == DT_LNK](https://github.com/domoticz/domoticz/blob/3861cc0e85aa8acdda29bfe77c04c133e310f233/main/Helper.cpp#L376) AND d_name start with 'ttyUSB', it is listed, but **bUseDirectPath** stays as **false**_


**3) Then, making a symbolic link to it as "/dev/usb/ttyUSB0"**
```
root@domo-ct:/dev# mkdir /dev/usb
root@domo-ct:/dev# cd /dev/usb
root@domo-ct: ln -s /dev/ttyUSB0 ../ttyUSB0
root@domo-ct:/dev# ls -l /dev/usb/
total 0
lrwxrwxrwx 1 root root 10 Feb  2 10:57 ttyUSB0 -> ../ttyUSB0
```
---> Dz seet it 😎 

_because  [we are in '/dev/usb/'](https://github.com/domoticz/domoticz/blob/3861cc0e85aa8acdda29bfe77c04c133e310f233/main/Helper.cpp#L449) AND d_name start with 'ttyUSB', it is listed, but **bUseDirectPath** change to  **true**_

----

SO, both solutions seems to works (shown in menu, at least), but in case 2, **bUseDirectPath** stays false, while in case 3,  it changes to true.

It seems that bUseDirectPath, is only used in the SQLHelper, [here](https://github.com/domoticz/domoticz/blob/3861cc0e85aa8acdda29bfe77c04c133e310f233/main/SQLHelper.cpp#L1460), but I cant figure, what is the right value to use  (true or false)... 

**Please advice ?** 🙏 

----

>So you use Proxmox and installed a virtual machine, under this you run LXC ?

Not sure to understand : I use Proxmox  as the main OS installed on the computer. 
[Proxmox allows me](https://proxmox.com/en/proxmox-ve/features) to host differents Virtual Machines that are, either pure VMs (qemu KVM), or LXC containers.

I thus use  Domoticz directly in a LXC container. ie:
- `Promox -> LXC`
- but NOT: `Promox -> VM -> LXC` (if this is what you meant)
 
**Thanks** for your help! 🍺

**Comment by gizmocuz** [comment]
Thank you for all this reseach!

So you say when you comment out this line

if ((de->d_type == DT_CHR) || (de->d_type == DT_LNK))

It works ?

If it works, could you log the type, I wonder what type/number it is

somwhere at the top of the helper.cpp add (not the first line)

`#include "Logger.h"`

And to log the value

`_log.Log(LOG_STATUS, "d_type: %d", (int)de->d_type);`

**Comment by soif** [comment]
> Thank you for all this reseach!

You're always Welcome! 🍺 

> So you say when you comment out this line
> 
> if ((de->d_type == DT_CHR) || (de->d_type == DT_LNK))
> 
> It works ?

I did not compiled it, I just deduced  from the code, that  an _unexpected_ d_type should be the culprit:
- as it works in case [2],  (in /dev/usb/), because d_type is NOT checked.
- and it works in case [3] (symlink), because:  d_type == DT_LNK
 
> If it works, could you log the type, I wonder what type/number it is
> 
> somwhere at the top of the helper.cpp add (not the first line)
> 
> `#include "Logger.h"`
> 
> And to log the value
> 
> `_log.Log(LOG_STATUS, "d_type: %d", (int)de->d_type);`

Thanks for the code, but unfortunately, as this is my main 'production' Domoticz, I can't afford to compil a full modified domoticz on this same machine. Sorry for that.

On the otherhand, if you would easely compil this debugging version for me (Debian Buster amd64), I would be please to test it for you.

**Comment by gizmocuz** [comment]
Okey so that means that it might not be this peace of code...
I'm sorry I can't make a test compile as I also can't test this in your (unique) situation.
Maybe someone on the forum can do this ?

**Comment by soif** [comment]
> Okey so that means that it might not be this peace of code... 

maybe

>I'm sorry I can't make a test compile as I also can't test this in your (unique) situation. 

I understand;

BTW my situation is really **not unique**:
https://www.domoticz.com/forum/viewtopic.php?t=26266
https://www.domoticz.com/forum/viewtopic.php?t=33512
https://www.domoticz.com/forum/viewtopic.php?t=36320
https://easydomoticz.com/forum/viewtopic.php?t=8309
https://forum.proxmox.com/threads/lxc-passtrough-usb-zwave-stick.56615/
https://forum.proxmox.com/threads/usb-passthrough-to-a-container-lxc.101741/
https://forum.proxmox.com/threads/passthrough-usb-from-host-to-lxc.23856/
https://forum.proxmox.com/threads/unexpected-behaviour-usb-device-apperars-in-all-lxc-machines.88537/

_---> just to list a few users who have the exact same issue with USB devices not properly recognazed in Domoticz, while correctly linked to /Dev/ttyUSB0_

I think that I will use a workaround to rename or symlink the device, so that Dz correctly see it (ie solution 2 or 3 above) 

So would you be intersetd if i'd then create a small information text that would explain How to use USB port in Dz in a LXC config. So that you might be able to re-post it to the Wiki?

HTH

**Comment by gizmocuz** [comment]
Problem can be solved if you can compile and debug the attribute value
