### ISSUE TITLE
domoticz crashs while restore database

### ISSUE THREAD

**Issue by MarkKoshelev** [domoticz/domoticz#5140]
I see crash of domoticz daemon on debian  bullseye while restore database
The reason is in commit in mainworker.cpp 
c06a3b111f5d30c180d9f05797cc7ffad3f52ab5

line 1636 
m_notificationsystem.Start();

The call of m_notificationsystem.Stop() before solves the crash. 
But I don’t know the reason  m_notificationsystem.Start(); call in this place.
the call stack under gdb and debug version:

[crash (3).txt](https://github.com/domoticz/domoticz/files/7977318/crash.3.txt)

**Comment by gizmocuz** [comment]
Thank you for reporting. I think we need to call '**Stop**' at the biginning of the 'Start' function like:

```
void CNotificationSystem::Start()
{
	Stop();
	RequestStart();
	m_pQueueThread = std::make_shared<std::thread>([this] { QueueThread(); });
	SetThreadName(m_pQueueThread->native_handle(), "NotificationSystemQueue");
}
```

Is it possible to test this ? If you want you can make a pull request for this

**Comment by MarkKoshelev** [comment]
> Thank you for reporting. I think we need to call '**Stop**' at the biginning of the 'Start' function like:

It's work. But I'm not a advanced user of github. May you make a pull request or give me brief instruction about pull request? Is it basic git commit - push scenario?

**Comment by gizmocuz** [comment]
I have just pushed the fix in the latest development code. Will be merged in the stable when we create a new release.
Thanks again!
