### ISSUE TITLE
V2022.1 build available but docker container numbering still at 2021-beta

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#5142]
i noticed that V2022.1 build is available
V2021.1 stopped with build 14121
V2022.1 is starting with build 14122

i noticed when downloading a new container it is still numbering with the 2021-beta prefix
perhaps a cosmetic issue or maybe things are more complicated to implement the new V2022.1 tag

![image](https://user-images.githubusercontent.com/16853535/152143605-b1a1b76e-a2ba-4410-bc1b-637f105c4766.png)

**Comment by gizmocuz** [comment]
This is caused by a fixed version tag inside the docker build scripts introduced by PR

https://github.com/domoticz/domoticz-docker/pull/5

I changed the version, but it would a good idea if this version could be derived from appversion.h or by looking in the history

Maybe @RobbITbv could have a lool/try with this?

**Comment by gizmocuz** [comment]
There is now a 2022.1 and a 2022.x beta

**Comment by GravityRZ** [comment]
Nice, thanks

out of interest. what builds are the 2021.1 and 2022.1 (i think they are the stable ones)

i normally check which is the latest beta and then download the one with the latest tag.
This way i can upgrade easilly to newer builds (by only using the latest tag)

![image](https://user-images.githubusercontent.com/16853535/152193245-1232e742-cdb1-4ecc-acfb-18ed1a8932e0.png)

**Comment by gizmocuz** [comment]
2022.1 (and 2021.1) are the latest master branch builds

**Comment by GravityRZ** [comment]
ok. thanks. closing this one

**Comment by GravityRZ** [comment]
oops. not sure if the numbering now advances right so keeping it open just in case

**Comment by gizmocuz** [comment]
For the beta, this year it does... (Maybe we could use the year as tag parameter), but for a new stable this is currently hard coded set to 2022.1

**Comment by GravityRZ** [comment]
works for me. This way you only get stalked once a year with the same question :-)

**Comment by gizmocuz** [comment]
Just made some patches and now the right version tag is taken from the history file

**Comment by GravityRZ** [comment]
looks like the 2021.1 was overwritten by the 2022.1

https://www.domoticz.com/forum/viewtopic.php?t=35454&view=unread&sid=fc2a4f8713d12f6dd8c7152586ad77e7#unread

**Comment by gizmocuz** [comment]
Yes that is what I explained above.... next time it will be alright...

**Comment by GravityRZ** [comment]
ok but since the 2021.1 is static(no more updates) how will this image magically change from 2022.1 to 2021.1
i am not talking about the name but the version you get when you download 2021.1
accoording to this person het now gets version 2022.1 when downloading 2021.1

**Comment by gizmocuz** [comment]
That is correct, I think we should remove the 2021.1 version. And he has to use the 2022.1

**Comment by GravityRZ** [comment]
ok. i do not have problems with that. perhaps tell him that on the forum.
2021.1 is really old 
also he is using docker and with docker you can save the current docker image for backup purposes.
i keep copies of older versions(2 versions back) in case i need to fall back but i am only falling back to previous version in case there is a problem with the newer version.

Also this gives problems with DB version so i do not think you can go back from 2022.1 to 2021.1(stable) without getting a complaint that the db version is not right
