### ISSUE TITLE
2022.1 Snapshot doesn't work any more

### ISSUE THREAD

**Issue by MuadDibVV** [domoticz/domoticz#5146]
Hello,
The snapshot function seems to be ko since the last update in 2022.1 :
Error: Error opening url: http://0.0.0.0:8080///json.htm?type=command&param=emailcamerasnapshot&camidx=1;2&subject=Test

**Comment by gizmocuz** [comment]
Well I think the problem is with your IP address 0.0.0.0 ?
Should this not be a real IP address like 192.168.0.10 maybe ?

**Comment by MuadDibVV** [comment]
I use a docker version (linuxserver.io) so my IP is a 172.XX IP.
I use the standard dzvents fucntion :
domoticz.snapshot('Hik1;Hik2','Test') 
On a 2021.1 version my script had no problem

**Comment by gizmocuz** [comment]
Thats not the official docker, but it should still work
But for sure you can not call the JSON API with 0.0.0.0
What happens when you use the above API call with a real IP address in a browser? Do you get any error ?

**Comment by MuadDibVV** [comment]
Indeed it work perfectly => I can replace my call by an openurl command

**Comment by gizmocuz** [comment]
Great! What did you use before instead of openurl ? And did you try this with a real ip ?

**Comment by MuadDibVV** [comment]
![image](https://user-images.githubusercontent.com/62676693/152694538-5c354b8f-3b1d-41e2-8f4a-2248bc4db676.png)

I use this dzvents command, so I can't put any ip

**Comment by gizmocuz** [comment]
Thank you! Going to debug this. Please use the openurl method for now

**Comment by MuadDibVV** [comment]
Thanks a lot !!

**Comment by gizmocuz** [comment]
I made a small test script that should send a camera snapshot when a switch is operated

```
return {
	on = {
		devices = {
			'MySwitch'
		}
	},
	logging = {
		level = domoticz.LOG_INFO,
	},
	execute = function(domoticz, device)
		domoticz.log('Device ' .. device.name .. ' was changed', domoticz.LOG_INFO)
		domoticz.snapshot('Keuken', 'keuken snapshot!')
	end
}

```

I get a error in the log:

```
2022-02-06 19:10:13.265  Error: dzVents: Error: (3.1.8) There is no camera with that name or id: Keuken
2022-02-06 19:10:13.265  Error: dzVents: Error: (3.1.8) An error occurred when calling event handler TestSnapshot
```

So it seems that it should work

Do you get any error except from the above ?

When I change it to

domoticz.snapshot(1, 'keuken snapshot!')

It is making a snapshot

**Comment by MuadDibVV** [comment]
No other error.
After other test : no problem with the name or the id with one camera
But KO with 2 camera in the same call (name or id)
(KO with string separate by ;, and ko with table)

**Comment by gizmocuz** [comment]
After more testing this works:

- domoticz.snapshot('1', 'keuken snapshot!')
- domoticz.snapshot('1;2', 'Snapshots!')
- domoticz.snapshot('Cam1;Cam2', 'Snapshots!')

So it all seems to work.

Make sure that the camera is enabled and check your log for any errors

dzVents will tell you if it can not find the camera (if it's not enabled)

- Camera snapshots with multiple camera's failed when one camera was having a issue, this has been solved in the latest beta version (14161)
- I added the camera IDX value in the camera overview table, as well as the edit screen

**Comment by MuadDibVV** [comment]
In my side (stable version) :
		domoticz.snapshot({'1'},'Test 1') => ok
		domoticz.snapshot({'2'},'Test 2') => ok
		domoticz.snapshot({'1', '2'},'Test 3')  => ko
But no problem, I am going to use the openurl command :-)

**Comment by gizmocuz** [comment]
`domoticz.snapshot({'1', '2'},'Test 3') => ko`

This I don't know, just use

domoticz.snapshot('1;2','Test 3')

**Comment by MuadDibVV** [comment]
domoticz.snapshot('1;2','Test 3') => ko

It probably comes from my linuxserver.io docker image (I was forced with this version 2022.1 to put a "webroot" parameter to "/" to start the container, it probably has other consequences)

**Comment by gizmocuz** [comment]
Maybe have a go with the official docker then ;)
