### ISSUE TITLE
Dusk Sensor images reversed...again?

### ISSUE THREAD

**Issue by AndeePandee** [domoticz/domoticz#5149]
Version: 2022.1
Build Hash: c9526851b
Compile Date: 2022-01-31 09:34:32
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

In issue #3853, it was mentioned that the icon for dusk sensors was inverted. It seems to be the same thing again? When the dusk sensor are ON, the icon should be a SUN and when it is OFF it should be a MOON. Now it is the opposite.

Changes can be made in www / app / LightsController.js and www / app / DashboardController.js to make it work.

**Comment by gizmocuz** [comment]
Not aware this has been changed recently
What hardware are you using ?

So when it's OFF (no dusk) the icon should be a SUN, then it is ON (dusk -> dark) it should be a moon like this

![image](https://user-images.githubusercontent.com/2265299/152955559-b4ce81ef-2bba-44b0-867d-2d7bdea92692.png)

**Comment by waltervl** [comment]
There was an incorrect specification in the wiki  https://www.domoticz.com/wiki/Dummy_for_virtual_Switches#Switch_Subtypes
I modified it just now.

**Comment by gizmocuz** [comment]
Thanks! Maybe you could add the screenshot ? 
Everything is OK and we can close this Issue ?

**Comment by AndeePandee** [comment]
Yep :) 
I think it's inverted but maybe thats only me :) If its daylight (no dusk) the icon should be a SUN, and when there is no daylight/sun (dusk) the icon should be a moon like this: 
![image](https://user-images.githubusercontent.com/84961904/152988022-f3fc021c-3736-4479-a2bb-acd4df0ce546.png)
![image](https://user-images.githubusercontent.com/84961904/152988375-ff02d1d3-74e1-409f-b296-964c09de8965.png)
On = På
Off = Av
I close this issue. Thanks for the clarification!

**Comment by gizmocuz** [comment]
Maybe it also depends per dusk sensor, mine says it is 'not dusk' = OFF, when when dusk is detected, it goes to 'on'

**Comment by waltervl** [comment]
I added the screenshot. 
@AndeePandee a real Dusk sensor will switch to ON when it is dusk (dark)

**Comment by AndeePandee** [comment]
You are right guys... My dusk sensor seems a bit retarded :)

**Comment by gizmocuz** [comment]
That is why my first question was "What hardware are you using ?" ... I am still curious ;)

**Comment by AndeePandee** [comment]
@gizmocuz I wont answer your question until you fix a DAYLIGHT switch in Domoticz... 
;)

**Comment by gizmocuz** [comment]
You can configure it as a normal on/off switch, and use a custom icon to reverse it if you want
