### ISSUE TITLE
Error: (FindModule) Domoticz/DomoticzEx modules not found in interpreter.  When  using Domoticz Loggin in interruption in python plugin

### ISSUE THREAD

**Issue by Elwinmage** [domoticz/domoticz#5153]
The problem occurs with the last stable version 2022.1. No problem with the previous stable version 2021.

In python plugin, if we use interruption, 
ex:
 GPIO.add_event_detect(gpio, GPIO.FALLING, callback=self.__interruptCall) 

All call to  Domoticz.Log(), Domoitcz().Error, Domoticz.Debug()... and i also suppose to a Domoticz object or function in the callback function  (__interruptCall in my sample) throw a 

"Error: (FindModule) Domoticz/DomoticzEx modules not found in interpreter."

The "import Domoticz" line is the first in the script.

**Comment by waltervl** [comment]
As a reference see also forum topic https://www.domoticz.com/forum/viewtopic.php?t=37043

**Comment by gizmocuz** [comment]
@waltervl , Is this not related to your previous PR ? Should that line not be changed to import DomoticzEvents ?

**Comment by waltervl** [comment]
No, this is an issue in Python plugins, my previous PR was about Python event scripts, 2 different things (I think....)

**Comment by Elwinmage** [comment]
Ok, i add 
"import Domoticz" in the callback interruption function.   
If it solves the problem i close this ticket.
Thank's for your help

**Comment by gizmocuz** [comment]
@Elwinmage , could you also post this on the forum ?

**Comment by Elwinmage** [comment]
yes of course: in the topic [37043](https://www.domoticz.com/forum/viewtopic.php?t=37043)

**Comment by Elwinmage** [comment]
So the error now is:

CPlugin:PyDomoticz_Log, illegal operation, Plugin has not started yet.
CPlugin:PyDomoticz_Debug, illegal operation, Plugin has not started yet.

**Comment by dnpwwo** [comment]
This error is different and normally happens when the plugin attempts call Domoticz before the onStart function has run, hence the 'Plugin has not started yet' message.

Can you post the plugin code?

**Comment by waltervl** [comment]
Plugin code is mentioned in the forum https://www.domoticz.com/forum/viewtopic.php?p=286578#p286578
but here it is a direct link: https://github.com/Elwinmage/MCP23017-Listener

**Comment by Elwinmage** [comment]
I made a workaround, where loggin is stored  and display in heartbeat.
the version without workaround: https://github.com/Elwinmage/MCP23017-Listener/tree/5e4ebeb87c

**Comment by waltervl** [comment]
Should be fixed in latest beta with commit https://github.com/domoticz/domoticz/commit/8f01ed77d5831090f34ad59d22ef1f7cd4d740f2 But try out in a beta environment first as it is early beta changes.

Please report issues in https://www.domoticz.com/forum/viewtopic.php?f=6&t=38086

**Comment by Elwinmage** [comment]
thx
