### ISSUE TITLE
iP Cams aspect ratio parameter in settings menu

### ISSUE THREAD

**Issue by davidKooreman** [domoticz/domoticz#5155]
It doesn't matter if it is per camera or for all cameras, a selection switch 3/4 or 16/9 at the camera settings screen (edit camera) would be perfect...

Now, I have to ssh into the Domoticz installation, go to the: /www/js/domoticz.js file and edit the ShowCameraLiveStream function:
CODE: [SELECT ALL](https://domoticz.com/forum/viewtopic.php?t=37210&p=281207#)

var AspectSource = 4 / 3;
and change: 4 / 3 to 16 / 9, **every time domoticz gets updated**...

but I will try to ask for a feature request on Github, maybe they will look into it...

**Comment by gizmocuz** [comment]
Implemented in beta 14183, will take an hour before it is available
