### ISSUE TITLE
Unsupported z-wave device NAS-PD07Z .xml file created

### ISSUE THREAD

**Issue by Sarcas666** [domoticz/domoticz#5158]
I've created an xml file for the yet unsupported NEO NAS-PD07Z PIR. I've send it to the z-wave alliance maillist, placed it in the domoticz forum and posted it in ozw github, but got no response. So I am offering it here in the hope that one day I do not have to manually change the manufacturer_specific.xml after each update.

Line for manufacturer_specific.xml:
` <Product config="shenzen_neo/nas-pd07z.xml" id="0720" name="NAS-PD07Z Battery and DC Powered PIR Sensor" type="0010"/>`
[nas-pd07z.xml.gz](https://github.com/domoticz/domoticz/files/8055507/nas-pd07z.xml.gz)

It is working fine for me for several months now.

**Comment by waltervl** [comment]
In which issue in ozw github did you offer the device? Can you link it here?

**Comment by gizmocuz** [comment]
I am afraid OZW development has stopped. We now also support zwavejs2mqtt via native mqtt hardware

**Comment by Sarcas666** [comment]
No problem;

"[Contributing XML file for unknown Neo NAS-pd07z multisensor](https://github.com/OpenZWave/open-zwave/issues/2628#issue-1105071652)"

**Comment by Sarcas666** [comment]
> I am afraid OZW development has stopped. We now also support zwavejs2mqtt via native mqtt hardware

Ah, ok. It was to be expected. I’ll start looking for a good ‘how-to-move-your-ozw-stuff-to-zwavejs2mqtt’.

**Comment by waltervl** [comment]
> > I am afraid OZW development has stopped. We now also support zwavejs2mqtt via native mqtt hardware
> 
> Ah, ok. It was to be expected. I’ll start looking for a good ‘how-to-move-your-ozw-stuff-to-zwavejs2mqtt’.

https://www.domoticz.com/wiki/ZwaveJS2MQTT

**Comment by Sarcas666** [comment]
> https://www.domoticz.com/wiki/ZwaveJS2MQTT

Now I have no excuse to procrastinate anymore… Thanks ;)
