### ISSUE TITLE
Not possible to edit Events respectively "My automation scripts" within Chrome

### ISSUE THREAD

**Issue by wewa00** [domoticz/domoticz#5159]
You can see the issue perfectly well in following screen shot.

![image](https://user-images.githubusercontent.com/5518631/153753698-9f75bb14-136f-42df-b547-c245b1be268f.png)

The issue was observed with Google Chrome 98.0.4758.82 (64-Bit) on Windows 10. Domoticz version 2022.1 is used. Also clearing cache did not work.

This issue can not be observed with Microsoft Edge. There the page is working fine.

**Comment by jvanderzande** [comment]
I am 99.99999% sure you have a cache issue when things work in EDGE and not with CHROME. Press **_F12_**, select **_Application_** / **_Storage_** and press **_Clear site data_** ...  and try again.

**Comment by wewa00** [comment]
I tried this already by pressing **F12** and clearing **Local Storage**, **Session Storage**, **Cookies** and **Cache Storage**.
Now I tried as you told me. But still the same, the Event page is not working. But now I also tried the Inkognito mode in CHROME and there the Event page is working.

In normal CHROME mode (not Inkognito) I can see following issues reported.
![image](https://user-images.githubusercontent.com/5518631/153901349-6c00b529-f954-4437-97f5-91e7cbe1152b.png)
In Inkognito Mode only Warnings are reported but no errors.

**Comment by waltervl** [comment]
So definitely browser cache issue. Please follow the instructions of the wiki https://www.domoticz.com/wiki/Browser_Cache
From inside the Chrome browser browse to the following URL: chrome://settings/clearBrowserData
Mark Cached images and Files and press the [Clear Data] button

**Comment by wewa00** [comment]
This solved my issue now. Thank you for your patience.
