### ISSUE TITLE
Counter divider on RFXMETER Counter display issues

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#5162]
When setting a counter divider on RFXMETER type counter gives display issues in reports.
Seems to be js code solvable so will try to fix.

![Screenshot_20220216-235159-840](https://user-images.githubusercontent.com/16327072/154371038-1a4ba797-5868-41fb-8eda-b7b568257bea.png)

**Comment by gizmocuz** [comment]
Do you use a divider ? And what it is set to ?

**Comment by waltervl** [comment]
In this case it was set to 10

**Comment by gizmocuz** [comment]
maybe you could indeed look at dynamic digits, but I was expecting no digits...

**Comment by waltervl** [comment]
Fixed with https://github.com/domoticz/domoticz/commit/fecded4ee21ca226eaadc86a0a8cf5ee69f87456

**Comment by gizmocuz** [comment]
I made some more changes and now the day/week/month/year/previous graphs also have correct digits
