### ISSUE TITLE
Wrong rappresentation of arrows for device temperature

### ISSUE THREAD

**Issue by megamarco833** [domoticz/domoticz#5163]
I'm on latest beta build version 14190 and i discover an issue on mobile visualization that happen only in main panel.
I attach two screenshot, did in same time, where you can see that on main panel all the arrows are red and up pointing.
These same devices in temperature panel has the correct arrows: devices where temp decrease has arrow blue down pointing, and device where temp increase has red arrow up pointing
The devices are dummy device type temperature or type temperature + humidity
![Screenshot_20220217_000825_org mozilla firefox](https://user-images.githubusercontent.com/44502572/154374054-84c5a961-1275-46ab-ad01-0cdc3f9d6527.jpg)
![Screenshot_20220217_000857_org mozilla firefox](https://user-images.githubusercontent.com/44502572/154374068-d3ad8b4d-f048-4669-a819-3ff70309ef1a.jpg)

**Comment by gizmocuz** [comment]
I think they always pointed up... I have to look into this one unless someone beats me to it!

**Comment by megamarco833** [comment]
> I think they always pointed up...

yes, correct, but ONLY in main panel, on the device temperature panel the arrow seams to be correct: look for example at firts device (corridoio) on temperature panel the arrow is blue and pointed down, in main panel, same device, has red arrow that pointing up :)

**Comment by waltervl** [comment]
I suppose in source www/app/dashboardcontroller.js
 `$rootScope.TrendState(2)`
Should be replaced by
`$rootscope.TrendState(item.trend)`

This weekend time to test and make PR if not somebody beats me :-)

**Comment by gizmocuz** [comment]
Thanks!! Yes I left this by accident while debugging because it takes some time before the trend is available ;)

**Comment by gizmocuz** [comment]
Fixed in upcoming beta release
