### ISSUE TITLE
OZW CP button not showing in OZW hardware list with MS Edge

### ISSUE THREAD

**Issue by Huppeltje16** [domoticz/domoticz#5166]
When opening de OZW hardware list of ZWave devices with my Aeotec USB ZWave stick with domoticz version 2022.1 on Raspberry PI (Linux 5.10.63-v7l+ armv7l) and a nated https port number, the node management button doesn't show in MS edge.
When using Google Chrome it does.

**Comment by waltervl** [comment]
Please use the forum for these kind of issues.
Use the instructions in https://www.domoticz.com/wiki/Browser_Cache to remove the browser cache in Edge and the node management button will show.

**Comment by gizmocuz** [comment]
Also please try upgrading to ZWaveJS2MQTT
