### ISSUE TITLE
Error 'dzVents: local netWork not open for dzVents openURL call' for other service on same host - missing port check

### ISSUE THREAD

**Issue by sander1988** [domoticz/domoticz#5172]
There is a small bug in this check: https://github.com/domoticz/domoticz/blob/master/main/dzVents.cpp#L398

It doesn't check the port of the URL being called with the dzVents openURL function. So it fails with 'dzVents: local netWork not open for dzVents openURL call' when I call another service (a different port) on localhost.

Note that the value of setting 'Local Networks (no username/password)' is empty in my setup. Adding localhost here it would be a workaround but is not preferred for security reasons (in this case).

**Comment by waltervl** [comment]
It is specified in the DzVents documentation that you have to set localhost 127.0.0.* in settings Network so perhaps it is intentional.

But if you think it can be fixed please make the change, and create a PR.

**Comment by sander1988** [comment]
> It is specified in the DzVents documentation that you have to set localhost 127.0.0.* in settings Network so perhaps it is intentional.
> 
> But if you think it can be fixed please make the change, and create a PR.

Sure, I will make a PR. It might take some time, I have to setup a build env first.

For now I came up with a workaround... 

I created the record 'myhost' in /etc/hosts which also points to 127.0.0.1 . So when I call openURL with 'myhost' as domain, then it bypasses the check and still works.

**Comment by jvanderzande** [comment]
Not sure whether the Domoticz port is a know value in dzventz, so wondering how that could be checked/fixed in the linked logic.

**Comment by sander1988** [comment]
> Not sure whether the Domoticz port is a know value in dzventz, so wondering how that could be checked/fixed in the linked logic.

The check itself is in C (https://github.com/domoticz/domoticz/blob/master/main/dzVents.cpp#L398) so that would not be an issue I expect.

**Comment by jvanderzande** [comment]
True... :)

**Comment by jvanderzande** [comment]
@sander1988, Just tested adding a test for the http & https ports to the linked code,  so it will only do the check when the url contains either port and that seems indeed to fix the issue. 
Will make a PR unless you are ready to do so ....  just let me know. ;)

**Comment by waltervl** [comment]
DzVents uses OpenURL also for some internal functions. Is that also still working?

Edit: example function device.setDescription(description)

https://github.com/domoticz/domoticz/blob/53758e5b4825d620f47c997a52847bf367848e09/dzVents/runtime/device-adapters/generic_device.lua#L135

**Comment by sander1988** [comment]
> DzVents uses OpenURL also for some internal functions. Is that also still working?
> 
> Edit: example function device.setDescription(description)
> 
> https://github.com/domoticz/domoticz/blob/53758e5b4825d620f47c997a52847bf367848e09/dzVents/runtime/device-adapters/generic_device.lua#L135

Nope, I just checked where openURL was used (on 2020.2 ; I had to downgrade in the meantime looking into another issue) with:
`# grep -R 'Domoticz url' /opt/domoticz/dzVents/runtime/ | egrep -v '/(integration\-)?tests/'`

It shows indeed several cases where the openURL is used. But funny enough I have never hit that problem (and I have really a lot of lua scripts in Domoticz). As far as I see, openURL is only used for methods that are not used quite often.

But it doesn't really matter for this report. My bug is about not being able to call another service on localhost due to the current implementation of the check. It's not about dzVents functioning improperly.

**Comment by sander1988** [comment]
> @sander1988, Just tested adding a test for the http & https ports to the linked code, so it will only do the check when the url contains either port and that seems indeed to fix the issue. Will make a PR unless you are ready to do so .... just let me know. ;)

That would be great! :-) Normally I would to it myself, but I have no running build env for Domoticz atm.

**Comment by waltervl** [comment]
What I meant was that with a fix of your issue we should be sure that the dzvents internal OpenURL functions will stay operational :-)

**Comment by jvanderzande** [comment]
> What I meant was that with a fix of your issue we should be sure that the dzvents internal OpenURL functions will stay operational :-)

My proposed change will simply add a check for both HTTP and HTTPS ports when define searching for ":portnumber", so the only thing that will change is that when you eg have 8080 & 8443 defined for Domoticz, all other OpenUrl() tasks will not trigger that shown error. So I don't see how that could break anything....agree? 

edit: I did remove the 127.0.0.* entry for testing and had no issues running an device or time dzvents script, so where do you think it will go wrong?

**Comment by waltervl** [comment]
I think the check is only really necessary if you have a user/password enabled in Domoticz. Because then you need to set the local IP in network setting.

**Comment by jvanderzande** [comment]
I've lost you now ...   Isn't Userid/Password implicit in Domoticz for all IP Subnets except the ranges defined in "Local Networks"?
Anyway: Did you (like I did) try to remove 127.0.0.* from "Local Networks" and run some dzVents script to see if anything broke other than when you make a API call to 127.0.0.1 ?  
Either way: I will make a PR with my proposal and will open it up for discussion there, so people can review and discuss to ensure it won't break anything. :)

**Comment by waltervl** [comment]
In general to use the /JSON.html Domoticz API and use user/password you have to set the local network setting to prevent to enter the user credentials in the API call.

As DzVents is using this API internally and has no user credentials it will fail when  you use user/password. So if you do not use user/password there is no need to fill the setting local network to use the API (and therefore DzVents).


As a reference quote from the dzvents wiki: 
Also make sure that in the Security section in the settings (Setup > Settings > System > Local Networks (no username/password) you allow 127.0.0.1 (and / or ::1 when using IPv6 ) **to not need a password**. dzVents does use this port to get the location settings and to send certain commands to Domoticz. F

**Comment by jvanderzande** [comment]
That all I understand: So please enlighten me with what exactly is going wrong when you don't add it! ;) 
Either way: This patch will still give that Error when a API call is done to the HTTP/HTTPS ports used by Domoticz.

**Comment by waltervl** [comment]
Nothing goes wrong because I did not test it. I am only triggering you to test the user/password scenario with DzVents before submitting the PR....

**Comment by waltervl** [comment]
Should be solved in latest beta. Please check and close issue.

**Comment by sander1988** [comment]
I have setup a build env now and did built Domoticz from latest source.

The issue itself is fixed now. But I think it never worked as intended.

I used this simple dzVents script to test it (it should fail with "Open Error 'dzVents: local netWork not open for dzVents openURL call'"):
```
return {
	on = {
		timer = {
			'every minute',
		}
	},
	execute = function(domoticz, timer)
		domoticz.devices('Test lamp').setDescription('This is a test for issue #5172')
	end
}
```

But it does fail with a common error (not the one we expect here to see):
```
2022-02-26 13:27:00.155  Error: Error opening url: http://0.0.0.0:8080/json.htm?description=This+is+a+test+for+issue+%235172&idx=303&name=Test+lamp&type=setused&used=true
```

As it uses '0.0.0.0' instead of 'localhost'. 

Do you agree? I can add '0.0.0.0' to the check and create a PR.

**Comment by waltervl** [comment]
I did some test on a previous beta build 14223, before this change.
Same script. 
No user/password, no values in settings network: Error as expected but incorrect as local network is open for dzVents OpenURL: 
       dzVents: local netWork not open for dzVents openURL call
	dzVents: check dzVents wiki (look for 'Using dzVents with Domoticz
Added "127.0.0.*" in network settings: Script executed succesfull, no errors.
Added user/password: Script executed succesfull, no errors.
Removed network settings: Errors as expected and as should be.

Will update now to latest beta and update test results.

**Comment by waltervl** [comment]
Testing in latest beta
Activated User/password without network settings: Error as expected
Activated User/password with network settings: No errors
No User/password with network settings: No errors
No User/password with empty network settings: The Error
     dzVents: local netWork not open for dzVents openURL call
      dzVents: check dzVents wiki (look for 'Using dzVents with Domoticz
In this scenario I can run the URL "http://127.0.0.1:8080/json.htm?description=This+is+a+test+for+issue+%235172&idx=107&name=Test&type=setused&used=true" without issues.

So behavior for me is the same, before and after the change. But not correct.

Also I get 127.0,0.1 in the debug log and not 0.0.0.0

**Comment by sander1988** [comment]
> Testing in latest beta Activated User/password without network settings: Error as expected Activated User/password with network settings: No errors No User/password with network settings: No errors No User/password with empty network settings: The Error dzVents: local netWork not open for dzVents openURL call dzVents: check dzVents wiki (look for 'Using dzVents with Domoticz In this scenario I can run the URL "http://127.0.0.1:8080/json.htm?description=This+is+a+test+for+issue+%235172&idx=107&name=Test&type=setused&used=true" without issues.
> 
> So behavior for me is the same, before and after the change. But not correct.
> 
> Also I get 127.0,0.1 in the debug log and not 0.0.0.0

I did some more tests as I didn't understand why we see different host IPs for those calls. My conclusion: It uses '127.0.0.1' when IPv6 is enabled on the host, it uses '0.0.0.0' when **only** IPv4 is enabled.

The difference is in the dzVents code: https://github.com/domoticz/domoticz/blob/master/dzVents/runtime/EventHelpers.lua#L47

So that's why I think 0.0.0.0 should always be included in the check.

**Comment by waltervl** [comment]
It should check the contents of the values in local network settings with the IP address it is run on (0.0.0.0, 127.0.0.1, localhost etc). But only when a user/password is configured, else the check is not needed and can be skipped.

**Comment by gizmocuz** [comment]
Solved in beta 14231, but do know that one stable and a next beta further, we are going to introduce mandatory username/password, and you need to whitelist 127.0.0.1 explicitly if you need this
Better solution is to support setDescription natively instead of letting it call OpenURL...

**Comment by waltervl** [comment]
@gizmocuz Why mandatory username?? I and certainly my wife will hate this. I have not opened up Domoticz to the outside world.

**Comment by kiddigital** [comment]
@waltervl , you will get the option to turn it off.

'Problem' is that some users do open access from the outside world and forget to secure their setup.

So idea is to start more secure (with user/pass) and have options to either tighten or loosen security depending upon needs.

**Comment by gizmocuz** [comment]
@waltervl , You can still whitelist your IP addresses... but it will be mandatory to login the very first time and change the password

**Comment by waltervl** [comment]
@gizmocuz @kiddigital Hmm, I understand. But then please make also more clear the illegal logins tries from outside more clear in the log file as a try to log Domoticz.

**Comment by gizmocuz** [comment]
All logins are already mentioned in the logs, also failed logins. And you can also use fail2ban (and get a notification)
Anyway, it is a very good idea to always your Domoticz protected from the outside world.
What you do inside is your responsibility.
But coming back to the original issue, this is solved
