### ISSUE TITLE
Block comments shortcut internal ace/dzvents editor creates single square brackets instead of double

### ISSUE THREAD

**Issue by Sarcas666** [domoticz/domoticz#5175]
2022.1 build 14223

Internal Ace editor - dzvents

Block comments shortcut ( SHIFT-CTRL-/ ) creates:

```
--[blabla
blabla
blabla]--
```

instead of 

```
--[[blabla
blabla
blabla]]--
```

Single square brackets obviously causes errors.

**Comment by gizmocuz** [comment]
I just checked with the latest ace, and this seems the default...
Not sure if this is a Domoticz or Ace issue ...

**Comment by Sarcas666** [comment]
Seems an Ace issue indeed. 
I changed 
`this.blockComment={start:"--[",end:"]--"`
to
`this.blockComment={start:"--[[",end:"]]--"`
in my local ~/domoticz/www/js/ace/mode-lua.js and that solves the problem. Until my next update, of course. And assuming the double bracket is correct LUA and not the single bracket.

**Comment by gizmocuz** [comment]
Could you report this issue to ACE and if you like you can make a PR for this file in our repository to fix this

**Comment by Sarcas666** [comment]
I've reported the issue at ACE : https://github.com/ajaxorg/ace/issues/4646

I never did a PR before. I'll look into it. 

Edit: I think I did it...

**Comment by gizmocuz** [comment]
Merged, thank you for this!!
