### ISSUE TITLE
Wrong icon in floorplan

### ISSUE THREAD

**Issue by Argafal** [domoticz/domoticz#5182]
First of all, thanks a lot for all the efforts that go into this beautiful piece of home monitoring! 

I found a minor bug that bugs me quite a bit: Two devices show the wrong icon in the floorplan. 

The icons is correct in the dashboard and the utility tab, wrong in the floorplan. The icon is also wrong in the devices list. I am not bothered by the latter, but mention it to provide a better understanding of the bug.

Hardware type: Dummy
Virtual sensor type: Electric (Instant + Counter), set to type: return (see screenshot)
Icon in floorplan (and device list): current48.png
Icon expected (see utility tab and dashboard): PV48.png

Hardware type: P1 Smart meter
Virtual sensor type: Gas
Icon in floorplan (and device list): Counter48.png
Icon expected (see utility tab and dashboard): Gas48.png

Domoticz running on Raspbian, Domoticz beta version: 2022.1 (build 14251)
Build Hash: 4eb95332c
Compile Date: 2022-03-02 11:50:56

Please let me know if there is any other information I can provide to help understand this issue. Screenshots below.

Floorplan (wrong icons)
![floorplan](https://user-images.githubusercontent.com/715254/156751962-1320f97a-50fd-4cf4-89aa-4ffa51f54b6d.png)
Sensor for solar production
![sensor 1](https://user-images.githubusercontent.com/715254/156751012-33e9ff93-2967-4684-bf4a-e39412c17707.png)
Dashboard (correct icons)
![dashboard](https://user-images.githubusercontent.com/715254/156750998-edc06f54-3552-463b-a891-2e91e06be3dd.png)
Utility tab (correct icons)
![utilitytab](https://user-images.githubusercontent.com/715254/156751014-e6249f3b-5eb3-4e38-9469-c072b6328306.png)
Device list (wrong icons)
![devicelist](https://user-images.githubusercontent.com/715254/156751009-50ada993-6f1e-4f6a-9674-f6c828dbfdd3.png)
.

**Comment by gizmocuz** [comment]
Fixed in beta 14260, thanks for reporting!
