### ISSUE TITLE
Integration Lixee Zlinky_TIC with Zigbee2MQTT plugin in domoticz

### ISSUE THREAD

**Issue by vp53vp53** [domoticz/domoticz#5183]
Hello,
New to the forum, I have just invested in a **Lixee Zlinky_TIC** zigbee key connected to the meter and allowing feedback on my **RPI with a conbee 2** key.
**Zigbee2MQTT** succeeds in pairing and shows me the values
![Zigbee2MQTT - Google Chrome](https://user-images.githubusercontent.com/100952454/156792278-e6185ab1-b807-4f30-a039-4f938eaeaa69.jpg)

On the other hand I am surprised that the information feedback in **domoticz** (via the Zigbee2MQTT plugin) is not done or badly: indeed the plugin works for the other peripherals and for this one, I **only** find the device "connection quality: 255"

![Domoticz 1](https://user-images.githubusercontent.com/100952454/156792389-048cfa78-937a-4c37-8e36-5e565863ce00.jpg)

![Domoticz - Google Chrome](https://user-images.githubusercontent.com/100952454/156791980-5a16d4df-ad44-46da-998e-fe1f3cb46185.jpg)
When I look at the **domoticz logs in debug mode,** I see the information that has been returned despite the errors:
![Domoticz 2](https://user-images.githubusercontent.com/100952454/156792724-6e9fb6bd-c2ef-4aa6-ae3a-9728df125544.jpg)

![Domoticz - 5](https://user-images.githubusercontent.com/100952454/156793375-15ab6737-4df4-4e65-9048-ac61acf88bdb.jpg)

Did I miss something? How to integrate the counters in the dashboard? 
NB: the key has made its OTA upgrade via ZIGBEE2MQTT
![Domoticz 3](https://user-images.githubusercontent.com/100952454/156793536-a798075d-9568-41a3-bc04-9056699f312c.jpg)

Sincerely

**Comment by waltervl** [comment]
For Zigbee2mqtt plugin issues please make an issue in the repository of the plugin as it does not make the correct translation to Domoticz objects 
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin

You can also try to use the MQTT Autodiscover device to replace the plugin. See wiki https://www.domoticz.com/wiki/Zigbee2MQTT

Closing this issue for now. If you have further questions please use the forum www.domoticz.com/forum
