### ISSUE TITLE
MQTT problem, with node-red, tasmota, and other

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#5184]
Hi,,,

After yesterdays updates..
I do have some problem with my mqtt..shelly, tasmota, heishamon, ...
[https://www.domoticz.com/forum/viewtopic.php?f=6&t=38192](url)
Strange thing z2m with mqtt [ zigbee] is working fine?

Perhaps to do with this part of changes?
https://github.com/domoticz/domoticz/commit/c5ebcd957a7819c8876021773d5073714049d21d

**Comment by gizmocuz** [comment]
No I don't see how this could be related. These changes are a addon.
You know you're cross posting ? ;)

**Comment by Dylantje** [comment]
Hi rob
sorry for my cross.. my wife :-(

Only the strange part, is working fine for years....
Now after the update no good working shelly and tasmota any more [ half the house] 
Is there something  else what i can do? or other idea where the problem can be?

ps: nice business suit

**Comment by gizmocuz** [comment]
The only thing added is the support for 'button' types...
When you update domoticz, there should be a backup placed in the backup folder.
When you use the executable from this backup (name it domoticz_previous for instance),
stop domoticz and launch it with this executable to revert a version, does it work ?

**Comment by waltervl** [comment]
We will continue here: https://www.domoticz.com/forum/viewtopic.php?f=6&t=38192

**Comment by Dylantje** [comment]
However is still wanna show the solution:
![ScreenShot098](https://user-images.githubusercontent.com/5214969/157096354-bde31e45-e0ac-4a19-a0a1-1b43a9f3ce0a.png)
![ScreenShot099](https://user-images.githubusercontent.com/5214969/157096356-65ae3799-48b6-4ae5-9b87-759e2fd5fddc.png)

There is "new" hardware [ i did not update a long time ]
There is now a mqtt autodiscovery... :-)
And domoticz did set my "old" mqqt settings to the new auto discovery ... settings.
So i did mis there domotcz/in en domoticz/out
@gizmocuz  hope you understand, otherwise whe speak to email in Dutch :-)

So problem fixt...

**Comment by gizmocuz** [comment]
Yes I understand, but what I do not understand is that there was a SQL database patch that should have migrated your existing hardware to the new hardware. Or... You used both in/out topics and the auto discovery topic in one.
But yes, It's a new hardware option to make it cleaner
Great it is solved! thanks for the feedback

**Comment by Dylantje** [comment]
xxx
