### ISSUE TITLE
MQTT auto-discovery doesn't create thermostat mode device

### ISSUE THREAD

**Issue by jefft4** [domoticz/domoticz#5192]
[Domoticz 14205, Ubuntu 20.04]

Using zwavejs2mqtt with auto-discovery.  My TRVs (Eurotronic) are discovered okay but there is no device created in domoticz for 'mode'.  I've checked the JSON in the zwavejs console and the MQTT discovery message - copied in below - and it is present in both as element 64-0 under climate_thermostat.  OZW previously created a 'mode' device for these TRVs, which worked, so it can be done (and is very much needed!)

Is this a problem that I can fix in the configuration somehow, or is a change needed to domoticz code to correctly create the mode device for climate_thermostat?

MQTT message:
`{"min_temp":8,"max_temp":28,"modes":["off","heat","cool"],"mode_state_topic":"zwave/Gym_TRV/64/0/mode","mode_command_topic":"zwave/Gym_TRV/64/0/mode/set","current_temperature_topic":"zwave/Gym_TRV/49/0/Air_temperature","temp_step":0.5,"current_temperature_template":"{{ value_json.value }}","temperature_state_template":"{{ value_json.value }}","temperature_command_topic":"zwave/Gym_TRV/67/0/setpoint/1/set","mode_state_template":"{{ {0: \"off\", 1: \"heat\", 11: \"cool\"}[value_json.value] | default('off') }}","temperature_state_topic":"zwave/Gym_TRV/67/0/setpoint/1","temperature_unit":"C","precision":0.1,"device":{"identifiers":["zwavejs2mqtt_0xc7625338_node76"],"manufacturer":"Eurotronics","model":"Thermostatic Valve (Spirit)","name":"Gym TRV","sw_version":"0.16"},"name":"Gym TRV_thermostat","unique_id":"zwavejs2mqtt_0xc7625338_Node76_thermostat"}`

One thought on implementation: some TRVs don't expose all their modes when interviewed, or have custom modes, so it would be good to allow the mode device to send any numeric value, not just those listed in the discovery template.

Thanks!

**Comment by gizmocuz** [comment]
Is it possible you can tell us the complete topic where this config is posted ?

**Comment by jefft4** [comment]
Sure!  Looks like it's <discovery_topic>/climate/<device_name>/thermostat/config

zwavedisco/climate/Gym_TRV/thermostat/config in my case.

**Comment by gizmocuz** [comment]
Thank you for the information. I simulated your config and Domoticz creates a Select Switch without issues

![image](https://user-images.githubusercontent.com/2265299/158195898-4a54b3a8-a460-4d62-a8e5-7bceb7314a5b.png)

**Comment by jefft4** [comment]
Hmm. Thanks for checking :-)  That's interesting; I don't have a selector.  However... forcing it to forget and re-discover seems to have created it now!  Just a weird thing, I guess - I'd tried re-sending the discovery message several times and nothing appeared.

The values are interesting; how do domoticz's 0 Off / 10 Heat / 20 Cool get mapped to the 0 Off / 1 Heat / 11 Cool in the zwavejs definition?  And is there any way to send another value?  zwavejs doesn't publish the proper values of the TRV, which has 5 heat-related modes and no 'cool' but sending a zwave/Gym_TRV/64/0/mode/set message can set any mode using its z-wave mode number - e.g., 31 for direct valve control.  To do that from domoticz, or to add it to the selector, would be a great help.

**Comment by gizmocuz** [comment]
Good it's solved.
The mapping is specified in the config json object above

`  "mode_state_template": "{{ {0: \"off\", 1: \"heat\", 11: \"cool\"}[value_json.value] | default('off') }}",
`

**Comment by waltervl** [comment]
So issue can be closed?

**Comment by gizmocuz** [comment]
Yep if the device sends a wrong config file we are unable to solve this
Closing issue
