### ISSUE TITLE
MQTT - Change in behaviour `Energy Report` for Fibaro devices from OpenZwave to ZwaveJS

### ISSUE THREAD

**Issue by Rouzax** [domoticz/domoticz#5193]
```
Version: 2022.1 (build 14277)
Build Hash: 5a1ae7dd1
Compile Date: 2022-03-13 10:47:20
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
```
I am testing with switching from OpenZwave to ZwaveJS2MQTT but see 1 change in behaviour that seems to be in relations to a previous existing workaround in Domoticz regarding Power reports and sensors for Fibaro devices.

With OpenZwave the combined power report that shows `kWh` and `W` is always instantaneously updated (without polling).
![image](https://user-images.githubusercontent.com/4103090/158170061-ed600818-e35b-46df-9d46-c4f5d97d88af.png)

![2022 03 14-10 41 40_Domoticz_-_Utility_—_Mozilla_Firefox_t5RM6yYNTo](https://user-images.githubusercontent.com/4103090/158146390-21829d8f-b788-4dea-b0c0-8afb9f2eb635.gif)

This is not the case when switching to ZwaveJS.
Dimmer 100% = 22 Watt usages
But the Electric Consumption [W] stays on the previous value when it was dimmed.
![image](https://user-images.githubusercontent.com/4103090/157892435-2ce8e24b-c42d-427d-90d7-2d6f70e3f40e.png)

Looking how Zwave2JS is mapped to OpenZwave it looks to be like this:
![image](https://user-images.githubusercontent.com/4103090/158172259-6b38ad66-b12c-44c5-9925-cc1f2b97bbab.png)

Looking at the OpenZwave implementation, it appears that there is some additional magic in place that takes values from different sensors and combines them in Domoticz.
![2022 03 14-11 29 42_Domoticz_-_Devices_—_Mozilla_Firefox_5xlYuqS6Ty](https://user-images.githubusercontent.com/4103090/158154647-b120757c-66fa-484a-a6b9-7c121de0608d.gif)

Have also opened a ticket with ZwaveJS and the dev there is looking for input from the Domoticz team
https://github.com/zwave-js/node-zwave-js/issues/4362

**Comment by gizmocuz** [comment]
The same 'should' happen in the MQTT-AD implementation, when a "W" value is received, it should also try to find the 'kWh' sensor and update the usage here as well.

Some questions:
- 1. When you switch on the dimmer, the Usage/W value is updated in the Gui ?
- 2. Do you have to 'poll' the kWh value ? Or is this updated after some time, maybe after an hour ?
- When '1' is true (it's updated) and you refresh the browser, is the kWh also updated ?

**Comment by Rouzax** [comment]
But the `W` value looks to be a different device, see the first post of this issue https://github.com/zwave-js/node-zwave-js/issues/4362#issue-1168242179

OpenZwave has those same 3 subtypes, but it looks like it is picking the `Usage` -> `Electric` and showing that in the `General` -> `kWh`
See the gif from this issue.

With OpenZwave I don't need to poll the `kWh`, the `W` is updated as you can see in the gif.

If it helps I can create a similar gif with the ZwaveJS implementation.

**Comment by gizmocuz** [comment]
Usage->Electric is very old... this has been General->kWh for quite some time.
Could you answer the 3 questions above please

**Comment by Rouzax** [comment]
This is with ZwaveJS
![2022 03 14-14 41 49_Domoticz_-_Devices_—_Mozilla_Firefox_oZdVue3F0M](https://user-images.githubusercontent.com/4103090/158184412-a810806e-8118-4e87-9b79-f916b2b808b0.gif)

This is with OpenZwave
![2022 03 14-11 29 42_Domoticz_-_Devices_—_Mozilla_Firefox_5xlYuqS6Ty](https://user-images.githubusercontent.com/4103090/158154647-b120757c-66fa-484a-a6b9-7c121de0608d.gif)

As you can see both OpenZwave and ZwaveJS have 3 devices related to power and they seem to map like this.

| OpenZwave | ZwaveJS |
| ------------- | ------------- |
| 0011B01 (Usage Electric) | [27-50-1-value-66049] Electric Consumption [W] |
| 00011B01 (General kWh) | [27-50-1-value-65537] Electric Consumption [kWh] |
| 0011B04 (Usage Electric) | [27-49-1-Power] Power |

In both implementations only the `0011B04 (Usage Electric)` and `[27-49-1-Power] Power` are instantaneously updated but with the OpenZwave also the device `00011B01 (General kWh)` the `W` is updated.

To the questions
 > When you switch on the dimmer, the Usage/W value is updated in the Gui ?

See the 2 gifs in this post.

>Do you have to 'poll' the kWh value ? Or is this updated after some time, maybe after an hour ?

With OpenZwave I do not need to poll the `kWh` value, this is updated based on the config of the dimmer.
![image](https://user-images.githubusercontent.com/4103090/158187778-c65ad224-ec47-4367-bbde-82b520fac1c9.png)

Not sure about the last question.

PS: It is really hard to explain this via text 😄 
If need be I'm happy to do a screen share and call to show and explain.

**Comment by gizmocuz** [comment]
@Rouzax, sorry this is getting to confused. Please stay at the topic, we also do need screenshots or MQTT values (at the moment) from zwavejs topics.

So it is important to answer the following 3 questions in text:

Some questions (all domoticz web GUI related):

1. When you switch on the dimmer, the Usage/W sensor value is updated in the Gui ?
2. Does the kWh sensor update after an a longer period , maybe after an hour ?
(You mentioned 'polling', you have to enable polling in zwavejs ?), this should not be nececery

3. When '1' is true (the Watt sensor is updated) (and the kWh does not), and refresh the browser (F5 or reload the web page) is the kWh now updated with the correct Watt value?

**Comment by Rouzax** [comment]
@gizmocuz 
Just to be sure these questions are related to running with ZwaveJS?

**Comment by gizmocuz** [comment]
Yes, Domoticz in combination with ZWaveJS2MQTT that is where this topic is about right ?

**Comment by Rouzax** [comment]
1. When you switch on the dimmer, the Usage/W sensor value is updated in the Gui ?
Dimmer off Domoticz
![image](https://user-images.githubusercontent.com/4103090/158202531-376028b0-40dd-483c-9877-55c35084dfe4.png)

Dimmer off ZwaveJS2MQTT
![image](https://user-images.githubusercontent.com/4103090/158202660-23b249c1-fa26-48c1-8c2e-8f22c051f35f.png)

Dimmer on Domoticz
![image](https://user-images.githubusercontent.com/4103090/158202753-d01ae547-9b39-4b3f-969d-27c4c95bb88c.png)

Dimmer on ZwaveJS2MQTT
![image](https://user-images.githubusercontent.com/4103090/158202813-f2628b3b-6347-464a-8904-bbad9fd18c1b.png)

2. Does the kWh sensor update after an a longer period , maybe after an hour ?
Yes, after a long time the upper 2 `0 Watt` values will also be updated

3. When '1' is true (the Watt sensor is updated) (and the kWh does not), and refresh the browser (F5 or reload the web page) is the kWh now updated with the correct Watt value?
Refreshing the page does not matter, still shows `0 Watt`

All of this makes perfect sense since those values are also shown in ZwaveJS2MQTT.
This is where we get in the murky waters, since with OpenZwave it somehow is able to get instantaneous updates of the General kWh device and update the `W` usage.

Could you map `[27-49-1-Power] Power` to the General kWh device?

**Comment by AlCalzone** [comment]
@gizmocuz I'm not familiar with Domoticz, but I think I can help answer some of the questions. I have some Fibaro devices myself and they all exhibit the same behavior. Not sure why they chose to do it this way, doesn't seem to make sense IMO.
![grafik](https://user-images.githubusercontent.com/17641229/158208322-298b0525-1a36-4720-bc68-327c308b25fe.png)

The Meter CC exposes two meters, one for kWh, one for W. Z-Wave JS queries them during the interview, which is where the W meter has its original value from. The kWh meter regularly gets updated by the device, the W meter doesn't (at least not for me - last update was in December).
There is also a single Multilevel Sensor (type Power), which continuously gets updated by the device.

**Comment by Rouzax** [comment]
AlCalzone is one of the developers of ZwaveJS

**Comment by gizmocuz** [comment]
@AlCalzone , thanks for joining!
It has been quite some time since I implemented OpenZWave into Domoticz, but I know that meter reports are almost 99% send to the 'lifeline' which is almost allways Group1 (where Node 1, the controller should be placed in)
But some devices report these states on another group (Like Group 4)

Looking in the OZW code implementation, when a kWh value is received, I do see quite some searching for a Watt value.

For Fibaro Wall Plugs I get the "W" value from COMMAND_CLASS_SENSOR_MULTILEVEL

For Other devices I am looking for the 'Power' value, and in the above case this would indeed be taken from 27-49-1-Power
If that is not found, the search continues and the value is taken from the Electric_W value

In the current MQTT-AD implementation I am just checking for the first value that as 'W' as the 'unit_of_measurement'

Of course blocking the Electric_W value from being send will solve this issue, but let's see what we can do about this...

**Comment by gizmocuz** [comment]
@Rouzax , could you please post be the MQTT config object for the Watt (W) value of your dimmer for both 27/50/1 and 27/49/1 ?
You can use (for example) MQTT Explorer for this. You might have to restart ZWaveJS if the config values are not retained

**Comment by Rouzax** [comment]
@gizmocuz, not entirely sure what you mean with this, not fluent yet in MQTT speak 😄
Would these suffice?
https://gist.github.com/Rouzax/a1ff02f93938e920744b8ab416de509a

EDIT:
If this is what you are looking for I can also post it for the Roller Shutter module of Fibaro

**Comment by gizmocuz** [comment]
@Rouzax , did you try launching the MQTT application and browsed your MQTT broker ? Went to the auto discovery topic (probably homeassistant), went to sensors, went to your dimmer 'W' value of xx/50/xx , and clicked on the config topic and you looked at the JSON on the right ? Now... that right part I am interested in (also xx/49/xx)

**Comment by gizmocuz** [comment]
@AlCalzone , do you know if in the config object there is a difference in the 'device_class' or another field, so we can differentiate between 'power' and 'Electric_W ' ? 

For my Greenwave powernodes I am very certain they use 'Electric_W' (COMMAND_CLASS_METER/50) and not COMMAND_CLASS_SENSOR_MULTILEVEL/49

But it's device_class is power

`"device_class": "power"`

I can't seem to find a command_class indication in the config object, is that correct ? The only way is probably splitting the 'state_topic' ?

**Comment by AlCalzone** [comment]
@gizmocuz I guess you're asking about [these MQTT discovery payloads](https://gist.github.com/Rouzax/a1ff02f93938e920744b8ab416de509a#file-fibaro-plug-L1238-L1321)?

I've asked @robertsLando to take a look here, as I'm not involved or familiar with the MQTT part of zwavejs2mqtt.

AFAIK other applications, including HomeAssistant, operate on the "raw" values instead and build their own device discovery on top of that. [These values](https://gist.github.com/Rouzax/a1ff02f93938e920744b8ab416de509a#file-fibaro-plug-L44-L121) indicate that there are different CCs involved.

Edit: I can confirm that my single-port Greenwave plug **only uses Meter CC** for power reporting, not Multilevel Sensor CC.

**Comment by gizmocuz** [comment]
I want to try and avoid building a 'new' integration again as the auto discovery works quite well.
The issue with implementing it nativly is that (again) some applications support this, other that.
I bet under the hood HASS is also having if/then/else checks, or using the COMMAND_CLASS_SENSOR_MULTILEVEL first.
Unfortuanlly I have to hook up a Fibaro multisensor first to be able to test ;)

@Rouzax , could you pleas join us on our Slack channel via:

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

And send me a direct message (same username), I would like to request a remote debug session

**Comment by robertsLando** [comment]
Hi everyone, if your issue is related to MQTT discovery, like I wrote in docs, I have no plans to keep it maintianed. It has been a pain in the past and it has many edge cases and breaking changes. If someone of you would like to help keep it maintained PRs are welcome

**Comment by AlCalzone** [comment]
@gizmocuz the way I understand it, the "discovered" devices in `hassDevices` don't contain anything Z-Wave (or any protocol) specific.
Sensors are modeled after https://www.home-assistant.io/integrations/sensor.mqtt/ and these device classes exist https://www.home-assistant.io/integrations/sensor/#device-class.

Guess your best bet (if you want to stick with MQTT discovery) is to parse the CC out of the state_topic, or the values array (which contains a value ID in the form `cc-endpoint-property[-propertyKey]`.

**Comment by gizmocuz** [comment]
Issue has been solved!

@robertsLando , this problem you will also experience when using the native implementation and is not related to MQTT
But as I said before, it is working 99,9% correct (for devices we encounter at least) so it would be a shame not to use,
and I like the principle of having one standard.
Maybe I could chime in when this new implementation in Domoticz settles a bit...

@AlCalzone , first I also tried to use the state_topic but when a user configured a node Name and Location the state topic expands.
I now used the device unique_id and this is working excellent

Another way to maybe fix this issue for feature products that wants to use ZWaveJS is maybe to block Electric_W of the COMMAND_CLASS_METER from being send at all ? (or providing a attribute to not use it... maybe 'enabled_by_default': false)

Thanks all for helping out!

**Comment by Rouzax** [comment]
Thank you for looking at this!

**Comment by AlCalzone** [comment]
> Another way to maybe fix this issue for feature products that wants to use ZWaveJS is maybe to block Electric_W of the COMMAND_CLASS_METER from being send at all ? (or providing a attribute to not use it... maybe 'enabled_by_default': false)

Put it on my TODO list, this sounds reasonable and likely has a use for other devices too.

**Comment by waltervl** [comment]
> Issue has been solved!
> 
@Rouzax can you confirm in latest beta and close this issue?

**Comment by Rouzax** [comment]
Posted back to gizmocuz on Slack but yes it has been solved for:
- FGWPE/F Wall Plug Gen5+
- FGR223 Roller Shutter Controller 3+
- FGD212 Dimmer 2+
