### ISSUE TITLE
MQTT-AD some device is missing from thermostat TuYa TV02

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5196]
From this device the selector device is missing: https://www.zigbee2mqtt.io/devices/TV02-Zigbee.html#tuya-tv02-zigbee
This is the config message:
`homeassistant/climate/0xb4e3f9fffebd9f7f/climate/config`
`{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"current_temperature_template":"{{ value_json.local_temperature }}","current_temperature_topic":"zigbee2mqtt/BadkamerThermostaat","device":{"identifiers":["zigbee2mqtt_0xb4e3f9fffebd9f7f"],"manufacturer":"TuYa","model":"Thermostat radiator valve (TV02-Zigbee)","name":"BadkamerThermostaat"},"hold_command_topic":"zigbee2mqtt/BadkamerThermostaat/set/preset","hold_modes":["auto","manual","holiday"],"hold_state_template":"{{ value_json.preset }}","hold_state_topic":"zigbee2mqtt/BadkamerThermostaat","json_attributes_topic":"zigbee2mqtt/BadkamerThermostaat","max_temp":"30","min_temp":"0","name":"BadkamerThermostaat","temp_step":0.5,"temperature_command_topic":"zigbee2mqtt/BadkamerThermostaat/set/current_heating_setpoint","temperature_state_template":"{{ value_json.current_heating_setpoint }}","temperature_state_topic":"zigbee2mqtt/BadkamerThermostaat","temperature_unit":"C","unique_id":"0xb4e3f9fffebd9f7f_climate_zigbee2mqtt"}`

**Comment by gizmocuz** [comment]
The reason for this is that the modes are expected in 'modes' and yours is publishing this to 'hold_modes'
Is this a modified config or a default config ?

**Comment by SargonofAssyria** [comment]
This is the default config from a device out of the box.
'auto' follows the internal set on/off time structure
'manual' follows the set current_heating_setpoint
'holiday' follows the holliday_temperature setting.
I use manual with changing setpoints and 'holiday' for vakantie.

**Comment by gizmocuz** [comment]
I think it is the same issue as discussed here

`https://github.com/home-assistant/core/issues/44255`

**Comment by SargonofAssyria** [comment]
It looks that way, but that issue is closed on the 15 of January.
And it does not seems that in Zigbee2mqtt any action is taken, because the output 2 month later is still hold_modes.
I updated Z2M 2 days ago.

**Comment by SargonofAssyria** [comment]
Updated to the latest Z2M today. Problem is still present. So opened a discussion in Z2M to get some clarification about "hold_* topics.

**Comment by waltervl** [comment]
Closing this one as it is a zigbee2mqtt issue.

**Comment by SargonofAssyria** [comment]
Lucky me. I am still on the 'old' Zigbee plugin, and that is working fine, even with the "hold_*" topics.
This way I can never make the switch to MQTT-AD.

**Comment by SargonofAssyria** [comment]
No Problem. Found my solution by adding some lines to the source code.

**Comment by gizmocuz** [comment]
@SargonofAssyria , Could you post the link to the issue that you created on Z2M ? It could be that the issue was solved but was related to another device and this might need to be solved as well.
Did you change the source code of Z2M or Domoticz ? If it's Domoticz could you make a PR ?

**Comment by SargonofAssyria** [comment]
I first started a discussion on Z2M, but no response.
Issue is made https://github.com/Koenkk/zigbee2mqtt/issues/11931
I changed temporarily the code in Domoticz 
Have to wait for an answer from @Koenkk

**Comment by SargonofAssyria** [comment]
Although I am the issue creator, I cannot reopen it???
Did not receive response to the issue created in Z2M, but I looked at the source of Z2M.
Found that it is a valid difference between **mode**_command_topic and **hold**_command_topic and mode_state_topic and hold_state_topic and mode_state_template and hold_state_template.
From the point of view from Domoticz they are the same, e.g. just a selector switch.
So it would be nice (necessary) that those 3 are added to MQTTAutoDiscover.cpp to also get a selector switch on the hold* topics as well.  They cannot be changed in Z2M because in the mode* topics there is validation on the text of the selector switch and in the preset not, and 'holiday' is not valid the the mode* topics.

**Comment by SargonofAssyria** [comment]
See reaction of Koenkk https://github.com/Koenkk/zigbee2mqtt/issues/11931#issuecomment-1105394437
So it should be handled in Domoticz MQTT-AD

**Comment by gizmocuz** [comment]
At the moment this is not yet supported. It is a different mode. Should not be that difficult to implement.
But I asked what you changed, because you mentioned "No Problem. Found my solution by adding some lines to the source code."
So please make a PR

**Comment by SargonofAssyria** [comment]
Hope that someone else who has the skills can do the PR.

**Comment by SargonofAssyria** [comment]
It looks like there is something changed in the config of this device in Z2M.
```
homeassistant/climate/0xb4e3f9fffebd9f7f/climate/config
```
```
{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"current_temperature_template":"{{ value_json.local_temperature }}","current_temperature_topic":"zigbee2mqtt/BadkamerThermostaat","device":{"identifiers":["zigbee2mqtt_0xb4e3f9fffebd9f7f"],"manufacturer":"TuYa","model":"Thermostat radiator valve (TV02-Zigbee)","name":"BadkamerThermostaat"},"json_attributes_topic":"zigbee2mqtt/BadkamerThermostaat","max_temp":"30","min_temp":"0","name":"BadkamerThermostaat","preset_mode_command_topic":"zigbee2mqtt/BadkamerThermostaat/set/preset","preset_mode_state_topic":"zigbee2mqtt/BadkamerThermostaat","preset_mode_value_template":"{{ value_json.preset }}","preset_modes":["auto","manual","holiday"],"temp_step":0.5,"temperature_command_topic":"zigbee2mqtt/BadkamerThermostaat/set/current_heating_setpoint","temperature_state_template":"{{ value_json.current_heating_setpoint }}","temperature_state_topic":"zigbee2mqtt/BadkamerThermostaat","temperature_unit":"C","unique_id":"0xb4e3f9fffebd9f7f_climate_zigbee2mqtt"}
```
Could the 'preset_mode' be added to MQTT-AD?

**Comment by gizmocuz** [comment]
@SargonofAssyria , could you also post some data when you set the modes ?

**zigbee2mqtt/BadkamerThermostaat/set/preset**

and some data when the new preset state is received

**zigbee2mqtt/BadkamerThermostaat**

**Comment by SargonofAssyria** [comment]
I seen device created. So that's good, but when I click holiday the device set 'auto'.
**zigbee2mqtt/BadkamerThermostaat/set/preset**
```
{"preset":"holiday"}
```
**zigbee2mqtt/BadkamerThermostaat**
```
{"battery_low":false,"boost_timeset_countdown":0,"child_lock":"UNLOCK","comfort_temperature":"20.0","current_heating_setpoint":"21.0","eco_temperature":"17.0","fault_alarm":0,"frost_protection":"OFF","heating_stop":"OFF","holiday_start_stop":"start -->   2021 - 01 - 01     01 : 01             stop -->   2021 - 01 - 01     01 : 01","holiday_temperature":"17.0","last_seen":"2022-09-19T10:56:19+02:00","linkquality":54,"local_temperature":"19.1","local_temperature_calibration":"0.0","online":"ON","open_window":"OFF","open_window_temperature":"17.0","preset":"auto","schedule_friday":"  6h:0m 17°C, 12h:0m 21°C, 14h:0m 17°C, 17h:0m 21°C, 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C ","schedule_monday":"  6h:0m 17°C, 12h:0m 21°C, 14h:0m 17°C, 17h:0m 21°C, 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C ","schedule_saturday":"  6h:0m 17°C, 12h:0m 21°C, 14h:0m 17°C, 17h:0m 21°C, 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C ","schedule_sunday":"  6h:0m 17°C, 12h:0m 21°C, 14h:0m 17°C, 17h:0m 21°C, 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C ","schedule_thursday":"  6h:0m 17°C, 12h:0m 21°C, 14h:0m 17°C, 17h:0m 21°C, 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C ","schedule_tuesday":"  6h:0m 17°C, 12h:0m 21°C, 14h:0m 17°C, 17h:0m 21°C, 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C ","schedule_wednesday":"  6h:0m 17°C, 12h:0m 21°C, 14h:0m 17°C, 17h:0m 21°C, 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C , 24h:0m 17°C , 24h:0m 21°C ","update":{"state":"idle"},"update_available":false,"working_day":0}
```

From the Z2M GUI everything works oke, but a 'set/preset' from Domoticz GUI  is send OK, but aways ends up with a end stage of auto.  I see that from Domoticz a {"preset":"holiday"} is send to 'set/preset', should that not just be a 'set'?

**Comment by SargonofAssyria** [comment]
I checked by mosquitto_pub command manually and only the **zigbee2mqtt/BadkamerThermostaat/set** works correctly
```
mosquitto_pub -h 127.0.0.1 -t zigbee2mqtt/BadkamerThermostaat/set -u yyyyy -P xxxxx -m "{\"preset\": \"holiday\"}"
```

**Comment by SargonofAssyria** [comment]
Just to clarify, I have a different thermostat on the attic which works just fine ( a Saswell SEA801-Zigbee/SEA802-Zigbee )
Here are the relevant parts of the config files.
![16 10 2022_14 36 19_REC](https://user-images.githubusercontent.com/24824113/196035893-ba17f928-9891-41a3-aa3c-96bb265cac0e.png)
![16 10 2022_14 40 44_REC](https://user-images.githubusercontent.com/24824113/196035919-fe873e32-f630-489e-bfe2-8466433d84e4.png)

**Comment by gizmocuz** [comment]
@SargonofAssyria , the command topic to set the preset is specified in the config object and is set to\

**"preset_mode_command_topic": "zigbee2mqtt/BadkamerThermostaat/set/preset"**

Your thermostat upstairs works ? Because the above command topic is the same as specified before (set/preset)

there must be something different with the other thermstat, or you mean the thermostat that has the config object with 'system_mode' works, but with 'preset' does not ?

**Comment by gizmocuz** [comment]
Thanks for the zigbee2mqtt/BadkamerThermostaat, this also seems to work in the beta from yesterday
So the only remaining issue is why the command topic is declared wrong in the config

**Comment by SargonofAssyria** [comment]
The Thermostat with the 'preset' does not work from Domoticz, the thermostat with 'system_mode' does work from Domoticz.
They both seem to have the same kind of command topic.
This is the difference in the MQTT 'set' message.
![17 10 2022_09 17 54_REC](https://user-images.githubusercontent.com/24824113/196113118-6f9d661e-4d58-4250-8584-ed695b6a0b73.png)

**Comment by gizmocuz** [comment]
Okey but I can't change the command state topic... if that is not good, please contact the guys from zigbee2mqtt

**Comment by SargonofAssyria** [comment]
I can not see the difference in logic between:
"mode_command_topic": "zigbee2mqtt/ZolderThermostaat/set/system_mode"   and
"preset_mode_command_topic": "zigbee2mqtt/BadkamerThermostaat/set/preset"
Both have a '/set/xxxx' or is the 'preset_' in ''preset_mode_command_topic' the culprit?
What should be changed in your view in zigbee2mqtt?

**Comment by SargonofAssyria** [comment]
This is a Home Assistant picture of the device.
![17 10 2022_13 49 59_REC](https://user-images.githubusercontent.com/24824113/196170001-362fe82f-ba04-4b51-a2e5-fc1fc20c683b.png)
Preset is different from 'System_mode' on HA called Operation.
B.t.w. In my production system and with the 'old' Stas plugin it works ok too for both thermostats.

**Comment by gizmocuz** [comment]
I see.... I devoted a special function in Domoticz to solve this, still it's not OK to solve this by a fix

**MQTTAutoDiscover::FixCommandTopicStateTemplate**

This function was called but I provided a wrong second parameter

Should work now in 14575

**Comment by SargonofAssyria** [comment]
Tnx, It works!!!
