### ISSUE TITLE
Setpoint updates broken by issue 4282

### ISSUE THREAD

**Issue by tarmacalastair** [domoticz/domoticz#5197]
Update 4282 has broken updates to **real** setpoints - see https://www.domoticz.com/forum/viewtopic.php?t=38159

Please revert to previous behaviour - it's driving me mad and is killing the battery on my thermostat as I have to set the wake interval as low as it will go. Others have reported similar issues but no one else seems to have tracked it down to this update.

I managed all last winter by reverting to an older version of Domoticz but this year I decided that I was getting so far behind with the updates....now I'm starting to regret updating because of this... 

Before update 4282 my real thermostat updated fine. I've spent ages trying to track down what caused the updating to break and have documented my findings at the address above.

**Comment by gizmocuz** [comment]
This update was mainly to prevent endless loops in MQTT
... And it has been 2 years since this update

You are talking about ZWave, could you please try ZWaveJS2MQTT with the new MQTT-AD hardware ?
I have no issues setting zwave/zigbee setpoints with this

**Comment by tarmacalastair** [comment]
Indeed, 2 years (actually only 19 months) of frustration! Well, for me it's only been this winter as the change happened during the summer so I was not using the heating. And then last winter I reverted to a backup to work around the problem.

Over the last 19 months I've been gingerly applying the beta updates every so often, hoping that at some point the bug would be ironed out and that the setpoints would start working again but then each time I've had to go back to my working version.

I first reported this in November 2021 but there have been similar reports in the forum for a long time - the earliest I can find is December 2020 (only a few months after the change).

It has been very difficult to pinpoint what exactly caused the problem as I only had one backup of a version that worked to go back to.

At the end of last year I chanced on a forum post (as it happens by the very person who requested issue 4282) with links to a Dropbox account with numerous Domoticz versions and this is what enabled me to spend hours and hours testing until I eventually found the cause of the problem, issue 4282.

Unfortunately I only have the one ZWave thermostat to test and this had worked perfectly with Domoticz since 2016 until this update. Please see my table at https://www.domoticz.com/forum/viewtopic.php?t=38159 which summarises the issue and also points out that the JSON setsetpoint command has never worked properly for my thermostat.

Back in November I did indeed try ZWaveJS2MQTT with the new MQTT-AD with the same results.

I have just disabled OpenZwave and tried ZWaveJS2MQTT again this morning but sadly the results are still the same as before.

I issue 
> http://192.168.0.15:8080/json.htm?type=command&param=udevice&idx=907&nvalue=0&svalue=22 

and the (new "nodeID_7_hrt4-zw") widget just stubbornly sits there displaying the old value of 20 degrees. I then repeat using _setsetpoint_ instead of udevice and still no change.

Then a few minutes later when the thermostat next wakes up, the widget changes.

**Comment by gizmocuz** [comment]
Okey but this means that the setpoint command was send, but the device did not report back the current setpoint value, only when it wakes up
Is it a battery operated device ? So it is not awake for 24/7 , and thus it makes perfect sense then when it wakes up every now and so often, that at this moment it is receiving the command and ackowledge it

**Comment by tarmacalastair** [comment]
Absolutely, yes it is a battery device. 

Up until beta 12260 the widget in Domoticz **always** showed an update as soon as the JSON command or LUA was issued and then this was subsequently followed by the device waking up to receive the change.

Since the change, Domoticz widgets stubbornly remain at their old value. This means the family look at the value in Domoticz and think nothing has happened. It also means that the LUA script I was using is now useless - it was used to increment the temperature up or down by 1 degree at a time, so 2 clicks to go up by 2 degrees, 3 clicks for 3 degrees, etc. Now you have to click once, wait 10 or 15 minutes then click again.....

**Comment by gizmocuz** [comment]
Yes, I think the sollution is to write the value into the database and not wait for response from the actual unit itself

Just to be sure, If you set the setpoint, It might not be updated in the GUI directly, but when the node wakes up, it is received and used ? (And reported back and the GUI updated)
So it works, only not visible directly in the GUI ?

**Comment by tarmacalastair** [comment]
Thanks, that would be brilliant.

Yes, you are right, a _single_ update to the device sends the update to the thermostat but the thermostat only receives the change when it wakes up. Only then does the Domoticz GUI widget get updated. But if trying to increment the temperature value with multiple clicks then only one change is shown when the device wakes up.

In order to save the battery I normally set it to only wake up every 20 - 30 minutes. At the moment it is set to 300 seconds, the shortest time allowed.

**Comment by gizmocuz** [comment]
Could you try beta 14290, I now force a database update so the value set should be directly visible.
Not sure how/if this is related to MQTT, but hope it works
If you switch to ZWaveJS2MQTT it should work... The current native OZW implementation will be removed soon

**Comment by tarmacalastair** [comment]
Wow, that is fantastic, thank you so much.
Using the OpenZwave defaults and now all the updating methods in my table (setsetpoint, udevice, LUA incrementing 1 degree at a time and clicking on the widget icon and scrolling up and down) now work and immediately update the widget.

I'll revert to ZWaveJS2MQTT later today and report back before the end of the day.

Again, thank you.

**Comment by tarmacalastair** [comment]
Well this is interesting. It all seems to work perfectly for my OZW devices and I was really happy....**but**....

I have now disabled OZW and enabled ZWaveJS2MQTT and the behaviour is back to how it was before - all the updates are again only reflected in the GUI widgets next time the Zwave thermostat wakes up.

I would have just assumed everything was fine if you hadn't told me that the native OZW implementation was going to be removed but now I've tested that and it the behaviour doesn't seem to have changed with this beta.

I've just removed the OZW hardware completely, restarted the Domoticz service, cleared the browser cache and retested. Results still the same with the widget only updating when the thermostat wakes up....

Any other ideas? Sorry to be such a nuisance but I was really excited when you got the beta out so quickly!

**Comment by gizmocuz** [comment]
Please update to beta 14292, as MQTT-AD is using a different device_id than most other hardware the internal value was not set correctly.
If all is working correctly now, please also update the forum topic.

**Comment by tarmacalastair** [comment]
Now on beta 14293 as 14292 had already been issued by the time I woke up!

**OpenZwave:**
still working fine as previously reported, including my LUA script as described above.

**ZWaveJS2MQTT:**
Well, it's an improvement. Updating via JSON udevice and setsetpoint now work and can be issued multiple times before the next thermostat wakeup and the GUI widget updates as expected. Also clicking the widget's icon (flame) allows updating the value correctly now.

However, using my LUA script which has been working for 4 years or so, now if I click on my "Up" button the widget changes to 20.9C and pressing the "Down" button sets it to 18.9C, no matter what the value was before. Further presses on the same button do nothing at all but swapping from the up to the down button and back again keeps changing the value to 18.9 (down button) and 20.9 (up).

Is there some different logic needed for MQTT devices or is there still a minor bug to iron out?

The script puts the current value into a variable _tempold_, then creates a new variable for _tempold+1_ and for _tempold-1_. Then when the _Up_ button is pressed, we issue 
`commandArray['UpdateDevice']='1022|0|'..tempup`
where _1022_ is the idx of the MQTT thermostat

Same logic for the _Down_ button, but setting the new value to _tempdown_

Thanks

**Comment by gizmocuz** [comment]
Great it's working... not sure what to do about the lua scripting issues

Maybe the first step would be to use dzVents (if you are not already doing this!), and then make a first script that just logs the value.
Is this value according to what is set in the Gui ?
If yes, continue from there

**Comment by tarmacalastair** [comment]
Hmm OK thanks better start to read up on how to use dzVents as I've never looked at it before.....

Does seem rather odd though that the same LUA script works perfectly for the OZW hardware and gives really bizarre values when using MQTT.....

**Comment by tarmacalastair** [comment]
I'll try a completely fresh Domoticz installation in next couple of days too, just in case something has gone wrong....

**Comment by gizmocuz** [comment]
I don't think it is related to a fresh install. But maybe you could start logging with plain LUA as well. Maybe the new value is not updated to Lua

**Comment by tarmacalastair** [comment]
Ah, might be starting to see a clue to what is going on as I get started with dzVents. 

With the OZW implementation, each thermostat device (room temperature sensor, setpoint) had its own unique name but with MQTT I have 3 devices, all with the same name and the log says:
 `Error: dzVents: Error: (3.1.8) Multiple items found for nodeID_7_hrt4-zw (device). Please make sure your names are unique or use ids instead`

As my LUA script starts by (trying to) query(ing) the value assigned to the setpoint by using 
`tempold = otherdevices_svalues['setpointname']`
where _setpointname_ was unique with OZW but with MQTT could now be any of 3 different values then could this be the cause?

Can I query a device by idx in LUA or do I need to switch to dzVents (as suggested at https://github.com/domoticz/domoticz/pull/4315) in order to be able to query by idx?

Thanks

**Comment by tarmacalastair** [comment]
Well I'm not a scripting person at all and so break from overthinking it was what I needed! 

Whilst out and about away from the computer I realised that I didn't need to worry about using idx's at all - all I had to do to solve the issue without having to learn dvVents was to simply rename my setpoint (which had the same name as the temperature monitor) to something unique and use that name instead in my original LUA script.

All working brilliantly now - many thanks...and the brief use of dzVents was very useful as the log output was what showed me where the problem lay.

**Comment by gizmocuz** [comment]
Great it's working! When you have time you can always rewrite it to dzVents
If you could also mention it's working in the forum that would be great!

**Comment by tarmacalastair** [comment]
Thanks, I will indeed learn dzVents as it looks very flexible.

Forum - updated...

**Comment by tarmacalastair** [comment]
> Could you try beta 14290, I now force a database update so the value set should be directly visible. Not sure how/if this is related to MQTT, but hope it works If you switch to ZWaveJS2MQTT it should work... The current native OZW implementation will be removed soon

Oh dear the ZWaveJS2MQTT really doesn't work well for me (my room temperature widget just doesn't update at all) so hope OZW stays for a while longer....

Found the problem - need to add a polling interval in ZWaveJS2MQTT (see https://zwave-js.github.io/zwavejs2mqtt/#/device-support/polling)

**Comment by gizmocuz** [comment]
You jump a bit to soon to conclusions -;)

What hardware/manufacturer/type are we talking about?
Is there anything in it's manual about the need to poll them ? Or are updates send to a specific group and you need to add the controller (node 1) into this group just like you might have done with OZW ?

Are these the only ZWave nodes you have or do you also have wallsockets/switches and other hardware ?
Those should also work much better

**Comment by tarmacalastair** [comment]
Hmm, jumping too soon to conclusions?? All I know is that OpenZwave worked perfectly for me, with absolutely no additional setup whatsoever. I'm sure you're right that ZWaveJS2MQTT is more reliable in many cases, just not mine.

As you can guess, this is my only Zwave hardware so I'm not in a position to comment on other kit. But also, having had my one thermostat working perfectly for 6 years+, I no longer have the manual and no idea how ZWave works behind the scenes.

But, please don't take any of this as criticism (it's just observation) - I am very grateful to you for all your hard work.

**Comment by gizmocuz** [comment]
I'm not ;-) And reverting a year to a old version is a wanted situation

Maybe you missed this part:

> What hardware/manufacturer/type are we talking about?
> Is there anything in it's manual about the need to poll them ? Or are updates send to a specific group and you need to add the controller (node 1) into this group just like you might have done with OZW ?

Because this could be critical. It is seen often that nodes transmit status updates not online to the lifeline (normally group 1) but to another group. In that case you need to place node 1 (the controller) also in that group to receive updates
