### ISSUE TITLE
Domoticz crash caused by LUA script

### ISSUE THREAD

**Issue by bizziebis** [domoticz/domoticz#5198]
Domoticz version: 2021.1 - build 14193 (2022-02-15)

Domoticz will crash when you use **Set Level** without any arguments on a **Selector** device. 

For example: _commandArray[av.dreamscreen_brightness] = 'Set Level'_

It's a human problem, but it would be nice if it would be catched and trow an error in the Domoticz log instead of crashing.

**Error log**
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #20 /lib/x86_64-linux-gnu/libc.so.6 : clone + 0x3f [0x7f5a7a19f4cf]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #19 /lib/x86_64-linux-gnu/libpthread.so.0 : + 0x7fa3 [0x7f5a7a41afa3]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #18 /home/dietpi/domoticz/domoticz : + 0x8cf2af [0x559df2a472af]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #17 /home/dietpi/domoticz/domoticz : CEventSystem::luaThread(lua_State*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x65 [0x559df24b7745]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #16 /home/dietpi/domoticz/domoticz : CEventSystem::iterateLuaTable(lua_State*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x1d5 [0x559df24b75c5]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #15 /home/dietpi/domoticz/domoticz : CEventSystem::processLuaCommand(lua_State*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x18e0 [0x559df24b7180]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #14 /home/dietpi/domoticz/domoticz : CEventSystem::ScheduleEvent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x14d [0x559df24b4d2d]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #13 /home/dietpi/domoticz/domoticz : + 0x33ba53 [0x559df24b3a53]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #12 /home/dietpi/domoticz/domoticz : std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const + 0x57 [0x559df2b80407]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #11 /home/dietpi/domoticz/domoticz : + 0x2eec93 [0x559df2466c93]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #10 /home/dietpi/domoticz/domoticz : + 0x9ea2d4 [0x559df2b622d4]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #9 /home/dietpi/domoticz/domoticz : + 0x9ea391 [0x559df2b62391]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #8 /home/dietpi/domoticz/domoticz : __cxxabiv1::__terminate(void (*)()) + 0x6 [0x559df2b62356]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #7 /home/dietpi/domoticz/domoticz : + 0x2ef058 [0x559df2467058]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #6 /lib/x86_64-linux-gnu/libc.so.6 : abort + 0x121 [0x7f5a7a0c8535]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #5 /lib/x86_64-linux-gnu/libc.so.6 : gsignal + 0x10b [0x7f5a7a0dd7bb]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #4 /lib/x86_64-linux-gnu/libpthread.so.0 : + 0x12730 [0x7f5a7a425730]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #3 /lib/x86_64-linux-gnu/libpthread.so.0 : raise + 0x10b [0x7f5a7a4255cb]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #2 /lib/x86_64-linux-gnu/libpthread.so.0 : + 0x12730 [0x7f5a7a425730]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #1 /home/dietpi/domoticz/domoticz : signal_handler(int, siginfo_t*, void*) + 0x205 [0x559df254f775]
19-03-2022 21:24:46 Fout DomoticzVM local1 domoticz #0 /home/dietpi/domoticz/domoticz : + 0x3d6d13 [0x559df254ed13]
19-03-2022 21:24:45 Fout DomoticzVM local1 domoticz Failed to start gdb, will use backtrace() for printing stack frame
19-03-2022 21:24:45 Fout DomoticzVM local1 domoticz siginfo address=0x3e8000004c5, address=0x7f5a7a4255cb
19-03-2022 21:24:45 Fout DomoticzVM local1 domoticz Domoticz(pid:1221, tid:27295('luaThread')) received fatal signal 6 (Aborted)

**Comment by gizmocuz** [comment]
@bizziebis , thank you for reporting.
Fixed in upcoming beta version
