### ISSUE TITLE
[Python 3.9.2] From Domoticz import Parameters raises an exception

### ISSUE THREAD

**Issue by RomainQuidet** [domoticz/domoticz#5200]
Hi,

Thanks for developping Domoticz.
I use it (v2022.1) on a raspeberrypi 1 with the latest bullseye raspbian (32bit). I installed all Python 3.9.2 libraries to test plugins dev.
Python seems to be recognized correctly: `Status: PluginSystem: Started, Python version '3.9.2', 2 plugin definitions loaded.`
But I'm facing a strange issue testing my plugin.

In my plugin.py:

`import Domoticz` works fine 
then
`from Domoticz import Parameters` fails with an exception:
`'ImportError':'cannot import name 'Parameters' from 'Domoticz' (unknown location)'.`

I don't get why... I can't get the Parameters dict (neither Images, Devices etc.
I tried to dump Domoticz module from python and log it, I can see this dict. (ie with `Domoticz.Dump(Domoticz)` or in `Domoticz.__dict__`)

Is there a change of the python c API incompatible with the current Domoticz?

Thanks!
Romain

**Comment by RomainQuidet** [comment]
Nevermind, the documentation is incorrect... Just use Parameters directly in python code without any prior import works... strange way to deal with python!
I leave this issue opened if maintainers want to update the doc :)

**Comment by RomainQuidet** [comment]
All is described here: https://www.domoticz.com/forum/viewtopic.php?t=38086

**Comment by gizmocuz** [comment]
If the documentation is incorrect, could you please make a PR for updated documentation, or if it needs to be corrected on the wiki, could you please explain here what is wrong, and how it should be written so we can modify this

**Comment by waltervl** [comment]
I think already the Plugin template is wrong, modified by someone else to add the line 
`from Domoticz import Parameters`
https://github.com/domoticz/domoticz/blob/c9526851b2dbc765e908ff020275edc43374aadc/plugins/examples/BaseTemplate.py#L27

@dnpwwo can you please verify?

**Comment by dnpwwo** [comment]
I can confirm that the original version of the template and sample plugins did not have this line.

From memory it works on some platforms but not others with that statement.  Without it the template works on all platforms

**Comment by waltervl** [comment]
> I can confirm that the original version of the template and sample plugins did not have this line.
> 
> From memory it works on some platforms but not others with that statement. Without it the template works on all platforms

Can you update the templates again back to its original state?

**Comment by kiddigital** [comment]
I think @dnpwwo changed it with commit https://github.com/domoticz/domoticz/commit/e61f1c1389671453f6510acc2f7a2504dccac120

**Comment by waltervl** [comment]
But most of these examples modified by https://github.com/domoticz/domoticz/commit/980f8b9c49783dfd9d9f801d1ac08abecc7e262a are still incorrect.

**Comment by waltervl** [comment]
Solved by https://github.com/domoticz/domoticz/commit/97e50d2aa2504f72b6c0861eb9d6baa8d7151f06
