### ISSUE TITLE
use docker-compose to use mysql database container

### ISSUE THREAD

**Issue by pvklink** [domoticz/domoticz#5207]
### Issue Guidelines

Should be great when you can use an existing mysql container to store domoticz data instead of inside the domoticz docker image, Like joomla or containers where you can define the database(image) to use

**Comment by waltervl** [comment]
Why?
It will only add more complexity, more testing for compatible databases (and versions) etc. So what huge benefit will this give?
What is wrong with sqlite?

**Comment by kiddigital** [comment]
Although I can see benefits in having a separate database (might have it already running for other purposes, easy to access using all kind of standard tools, etc.), it also poses several difficulties.

- For one, as @waltervl  mentioned, the need to support more than one database technology
- A separate database is 'inviting' to directly access and use. From an application perspective this is unwanted as direct use of the application data (through direct access to the database) makes it _harder_ to make changes to the way the application stores and handles this data. (more things will brake as other usages depend on the internal database structure).

By using the integrated SQLite(3) database, direct access to the data is prevented (sort off). This is _not_ an issue as the data can be access through the Domoticz API without the need to know the internal storage structures. Which can be changed freely by the application as long as the API's remain compatible.

From a _Docker_ perspective I can see the need to store the actual data outside of the container, for example on a _volume_. This way the persistent data is stored outside of the container allowing the destruction and re-creating of the Container without loosing the data.

But @pvklink , what would be the benefit you see as reason to ask this question/feature?
