### ISSUE TITLE
Arilux AL-LC0x - Domoticz hangs or crashes when device not connected

### ISSUE THREAD

**Issue by roblomq** [domoticz/domoticz#5208]
I'm running Domoticz on a Raspberry pi.

Version: 2022.1 (build 14299)
Build Hash: d5318fed7
Compile Date: 2022-03-28 14:42:06
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

I've added a magic home device through wifi. When this device is for some reason not connected to the network and then try to switch on or off the device using Domoticz, then Domoticz hangs or even sometimes crashes.

**Comment by kiddigital** [comment]
Please add more details like logging, crash dump information and steps to reproduce this problem.

Otherwise might be better to ask for the support on the forum first. Maybe other users had similar problems and already solved it.
