### ISSUE TITLE
unable to set "off" level name for selector switch for timer

### ISSUE THREAD

**Issue by MarkKoshelev** [domoticz/domoticz#5209]
I have the latest domoticz version builded from source (commit 2fc71c1afb74a9ad99873d37dd83986d73c078a3)
I use MQTT AD for zigbee2mqtt gateway. The problem is with TuYa thermostat.
MQTT AD creates selector switch control with two values - off&heat. The problem is: It is not possible to choose "off" state on the timer setting page. Only "heat" is available
![screen1](https://user-images.githubusercontent.com/50915452/161267082-c492e753-011b-4f51-8964-9aba98acff10.jpg)
![screen2](https://user-images.githubusercontent.com/50915452/161267129-72dfeffb-4f73-434d-91a0-6032f3bb537a.jpg)

**Comment by waltervl** [comment]
Off is just Off in field Command (On/Off).
But perhaps it should be Off (with capital O) instead of off.

**Comment by MarkKoshelev** [comment]
this field is created by MQTT auto dicovery plugin. Values off/heat is annoused by thermothtat throught zigbee2mqtt gateway. it is not good idea to fix z2m converter. 
I think domoticz should recognise this issue,

**Comment by gizmocuz** [comment]
@MarkKoshelev , could you please post the 'config' object of this node ?
You can see this with a MQTT Client like (for example) MQTT Explorer.
Go to the auto discovery topic, in your case open the 'climate' tree item (assuming it is announced as climate), find your node, click on the 'config' object and copy/paste the JSON content.

With this I should be able to replicate your issue and see if something needs to be changed

**Comment by waltervl** [comment]
It is standard behavior of a selector switch to not be able to select the 'Off' value from the level field. So this is basic not a ~~Zwavejs2mqtt~~ Edit: MQTT AD issue.

**Comment by gizmocuz** [comment]
In the timer you can set the command to either OFF or ON, and when you set this to OFF , I suspect the OFF is called ?
And when you select ON, one of the specified level values are set ?

Edit: Just verified, yes it works, It sets level 0
