### ISSUE TITLE
Intergas InComfort LAN2RF Gateway Thermostat device can not be set and does not trigger any event

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#5210]
domoticz version 2022.1.14127 running in docker
plugin Intergas InComfort LAN2RF Gateway
intergas gateway with FW IC3-2-ICN-V1.18 hardwired  to LAN
thermostat device created
![image](https://user-images.githubusercontent.com/16853535/161586745-c48d7403-f9ea-480d-bc48-a12e55c0ebe0.png)

issue detected.
temperature can be selected with +/- but after pressing set it does not stick(setpoint does not change)
when using edit, input temperature and press update the setpoint does change but no triggers are being send out(dzVents does not react on this change). timestamp also does not change
changes on the thermostat device are not send to the gateway. communication seems one way(from gateway to thermostat)
workaround.
create a dummy thermostat and use a dzVents script to update the gateway directly

**Comment by gizmocuz** [comment]
@GravityRZ , how do you update the setpoint via dzVents ?

Did it work before ?

Are you able to debug the code and add a debug log line here to check this function is called when you set the setpoint via the gui:

void CInComfort::SetSetpoint

**Comment by GravityRZ** [comment]
Hi gizmocuz

i am updating the gateway through the gateway gui by calling http
`domoticz.openURL({
			url = 'http://' .. USER .. ':' .. PASSWORD .. '@' .. IPADDRESS .. '/protect/data.json?heater=0&setpoint=' .. SetTemperature .. '&thermostat=0',
			method = 'GET',
			})       `

basically this string 
`http:// admin:xxxxxxxx @192.168.1.80/protect/data.json?heater=0&setpoint=160&thermostat=0`

it never did work before. i enabled accept new hardware, added the gateway in domoticz which created all the devices

i can try to debug the code but please let me know what to put in which file

so updating through gui:Works
updating through domoticz thermostat device:does not work
i know that at a certain time it was neccessary to send username and password along with the string(like it was input when adding the gateway in domoticz)
could it be that the thermostat device is still using the old string(without the credentials) so it can not communicate back to the gateway?

webpage looks like this
![image](https://user-images.githubusercontent.com/16853535/161726236-17d27465-28a1-48e5-839d-a97600965314.png)


i see this code on the webpage of the gui

`<html>
<body>


function update_setpoint(thermostat){
--
  | var d = document.getElementById("setpoint").value;
  | newAJAXCommand('/protect/data.json?heater=0&setpoint='+d+'&thermostat='+thermostat ,updateStatusSetpoint , false);
  | }
  | setTimeout("newAJAXCommand('/protect/data.json?heater=0', updateStatus, true)",500);


</body>
</html>
`

when i inspect the update setpoint1 button i see this code
`utocapitalize: ""
autocomplete: ""
autofocus: false
baseURI: "http://192.168.1.80/protect/roomthermostat.htm?heater=0"
checked: false
childElementCount: 0
childNodes: NodeList []
children: HTMLCollection []
classList: DOMTokenList [value: '']
className: ""
clientHeight: 16
clientLeft: 2
clientTop: 2
clientWidth: 116
contentEditable: "inherit"
dataset: DOMStringMap {}
defaultChecked: false
defaultValue: "Update setpoint 1"
dir: ""
dirName: ""
disabled: false
draggable: false
elementTiming: ""
enterKeyHint: ""
formAction: "http://192.168.1.80/protect/roomthermostat.htm?heater=0"
formEnctype: ""
formMethod: ""
formNoValidate: false
formTarget: ""
height: 0
hidden: false
id: ""
incremental: false
indeterminate: false
innerHTML: ""
innerText: ""
inputMode: ""
isConnected: true
isContentEditable: false`

**Comment by gizmocuz** [comment]
Looking at the code, I do not see any username/password. So I don't think it works with username/password.

Are you on our Slack Channel ? If not not, please use the following link

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

If you can send me a PM/DM, and can share your thermostat over the internet with me (with a username/password) I can have a look if I can add support for username/password

**Comment by waltervl** [comment]
Fixed with https://github.com/domoticz/domoticz/commit/1c4497038ecf62ed0bdc03cee3339f7dcecda827 ?

**Comment by GravityRZ** [comment]
testing with build 14.308.
i can change the temp of the thermostat but it does change NOT on the gateway. i asked gizmocuz where i need to put in the username and password. at the moment it is in the hw config setup but i did not get a popup to put it in somewhere else. please not that the password is not really password anymore but something else.
the thermostat is updated from the gateway to domoticz but not the other way around
![image](https://user-images.githubusercontent.com/16853535/161993372-dafb9217-fe7c-47d3-8329-d9584809542a.png)

**Comment by waltervl** [comment]
When I try to add the gateway I see  Username and password fields.
So please refresh your browser cache.

**Comment by gizmocuz** [comment]
@waltervl , we are working together via Slack. Made some code patches and GravityRZ is going to test soon.

**Comment by GravityRZ** [comment]
after refresch i see indeed the 2 fields. when i fill them in and press update i get an error in the log. somehow it does not connect
now it keeps on logging errors

2022-04-06 18:08:02.075 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:08:02.075 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:08:14.873 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:08:14.873 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:08:44.875 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:08:44.875 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:09:14.878 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:09:14.878 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:09:44.880 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:09:44.880 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:10:14.883 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:10:14.883 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:10:44.885 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:10:44.885 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:11:14.887 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:11:14.888 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:11:44.890 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:11:44.890 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:12:14.892 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:12:14.892 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:12:44.896 Error: Intergas InComfort: Error getting current state!
2022-04-06 18:12:44.896 Error: Intergas InComfort: Error getting current state!

**Comment by GravityRZ** [comment]
![image](https://user-images.githubusercontent.com/16853535/162020180-eac98f47-d7b3-4408-b159-f685607fab5e.png)

**Comment by GravityRZ** [comment]
by changing the remote address to 192.168.1.80/protect/data.json?heater=0  i get rid of the error. however the setting is still not send to the gateway

**Comment by GravityRZ** [comment]
it seemas to be working now. since there was not a lot of time that gizmocuz had to fix this so i was not aware that things needed to be filled in different. you need to fill in username, password and just plain ip addres and port of the gateway
the username and password is not sticky so if you fill it in, update, leave this page and go back the username and password will be blank again
![image](https://user-images.githubusercontent.com/16853535/162049833-b7132f19-0428-437b-9022-0e1bc13b4f28.png)

**Comment by gizmocuz** [comment]
Username/password is now also filled when you select the hardware.
Everything is working regarding the thermostat (was already working yesterday)
Users not using username/password will use the old calls

**Comment by GravityRZ** [comment]
i tested it and can confirm the new functionality including remembering username/password works with build 14311. thanks
