### ISSUE TITLE
wrong mqtt topic for device created by mqtt autodicovery

### ISSUE THREAD

**Issue by MarkKoshelev** [domoticz/domoticz#5211]
This issue is related to https://github.com/domoticz/domoticz/issues/5209. 
while select "off" value in selector switch control as well as the timer state "off" domoticz send mqtt topic like this 
z2m-1/Д1-ThermControl1/set/system_mode with json value {"system_mode":"off"}
But should send z2m-1/Д1-ThermControl1/set with json value {"system_mode":"off"} ( without system_mode in topic}
Tthis is the reason of that the thermostat alwaise  in mode "heat". I didnt recognise this problem while writing the issue 5209

thermostat ha mqtt config is in attachment
[thermconfig.txt](https://github.com/domoticz/domoticz/files/8421264/thermconfig.txt)

**Comment by gizmocuz** [comment]
I think this is a issue with your node, and not with Domoticz

Have a look at the following thermostat config (some parts taken out):

> climate/Zolder_Thermostaat/thermostat/config{
>   "modes": [
>     "off",
>     "heat",
>     "cool"
>   ],
>   "mode_state_topic": "zwavejs2mqtt/Zolder_Thermostaat/64/0/mode",
>   "mode_command_topic": "zwavejs2mqtt/Zolder_Thermostaat/64/0/mode/set",
>   "mode_state_template": "{{ {0: \"off\", 1: \"heat\", 11: \"cool\"}[value_json.value] | default('off') }}",
>   "device": {
>     "manufacturer": "Eurotronics",
>     "model": "Thermostatic Valve (Spirit)",
> }
> 
>

We tested multiple thermostats 

In this case the mode command topic is

**zwavejs2mqtt/Zolder_Thermostaat/64/0/mode**

and the value (JSON) is in 'value' (mode_state_template)

{ "value": "heat" }

Now your thermostat config says: 

command_topic = "z2m-1/Д1-ThermControl1/set/system_mode"

and we should send a value like

{ "system_mode": "heat" }

In your case, the command_topic actually should be "**z2m-1/Д1-ThermControl1/set**"

Which makes sense when you look at the other thermostat above

...

Now I was reading this page

https://community.home-assistant.io/t/avatto-me81h-thermostat/363895/4

I don't know what firmware you have installed, but maybe you can customize the config of this node and correct the mode topic ?

If not, I can try to check in the code to see if the end of the command_topic matches the state_template json field and remove this, but that might give issues to a current implementation
Better to get this fixed in your node

You probably also have a issue with the temperature topic/template

  "temperature_command_topic": "z2m-1/Д1-ThermControl1/set/current_heating_setpoint",
  "temperature_state_template": "{{ value_json.current_heating_setpoint }}",

**Comment by MarkKoshelev** [comment]
The reason is in the wrong command topic
The coorrect is
command_topic = "z2m-1/Д1-ThermControl1/set/system_mode"
I will investigate this issue with z2m.

**Comment by gizmocuz** [comment]
@MarkKoshelev , I made a patch in the code that should remove these wrong command topic endings.
Could you test beta 14307 (or higher) to see if that solves the issue ?

**Comment by gizmocuz** [comment]
(Sorry forgot to press 'send', I made a patch hours ago)

**Comment by MarkKoshelev** [comment]
Hi,
I may do this on holiday (Sunday or Saturday).

**Comment by MarkKoshelev** [comment]
something wrong with setpoint
set topic is z2m-1/Д1-ThermControl1/set with 22
should be  z2m-1/Д1-ThermControl1/set with value {"current_heating_setpoint":"22"}
also the mqtt config has "temp_step": 1 but setpoint control control uses 0.5 step

**Comment by MarkKoshelev** [comment]
Log while join thermostat
2022-04-07 22:17:51.717 Error: Z2M-GW1: Climate device unhandled temperature_state_template (0x8cf681fffebfe565_climate_z2m-1)
2022-04-07 22:17:51.717 Error: Z2M-GW1: Climate device unhandled current_temperature_template (0x8cf681fffebfe565_climate_z2m-1)
2022-04-07 22:17:51.853 Error: Z2M-GW1: Climate device unhandled temperature_state_template (0x8cf681fffebfe565_climate_z2m-1)
2022-04-07 22:17:51.853 Error: Z2M-GW1: Climate device unhandled current_temperature_template (0x8cf681fffebfe565_climate_z2m-1)
2022-04-07 22:17:52.063 Z2M-GW1: Thermostat/SetPoint (Д1-ThermControl1)
2022-04-07 22:17:52.124 Error: Z2M-GW1: Climate device unhandled current_temperature_template (0x8cf681fffebfe565_climate_z2m-1)

**Comment by gizmocuz** [comment]
@MarkKoshelev , our setpoint control works with 0.5 degrees, if you know you can only control it by 1 degree, control it by one degree.
When you set the setpoint with Domoticz, you should be able to see what is being send with the application MQTT Explorer, what does it send, where does it send to (topic) and does it work ?

Could you post the payload of

z2m-1/Д1-ThermControl1

**Comment by MarkKoshelev** [comment]
MQTT Explorer payload:
topic z2m-1/Д1-ThermControl1/set with value 22
should be the same topic z2m-1/Д1-ThermControl1/set but with with value {"current_heating_setpoint":"22"}

**Comment by MarkKoshelev** [comment]
> our setpoint control works with 0.5 degrees, if you know you can only control it by 1 degree, control it by one degree.
I see, but if MQTT config exposes "temp_step": 1, it is good reason to use it.
My be in the future domoticz version.

**Comment by gizmocuz** [comment]
Please feel free to make a PR with the needed changes ;)

I don't understand the 100%, does it send 22, or {"current_heating_setpoint":"22"} ? It should be the later i suppose ? (JSON object)

**Comment by MarkKoshelev** [comment]
> Please feel free to make a PR with the needed changes ;)
> 
> I don't understand the 100%, does it send 22, or {"current_heating_setpoint":"22"} ? It should be the later i suppose ? (JSON object)

It send 22 without json object. 
![screen3](https://user-images.githubusercontent.com/50915452/162456012-59e6a9dc-37ae-401b-b46e-b52a31c54487.jpg)

**Comment by gizmocuz** [comment]
Could you test beta 14312, this should set it in the correct topic

**Comment by MarkKoshelev** [comment]
The setpoint contol works.
I have next issue:


I see that thermostat config has preset field:
"hold_command_topic": "z2m-1/Д1-ThermControl1/set/preset",
  "hold_modes": [
    "hold",
    "program"
  ],
I dont see switch to control "preset" in domoticz.
Also while start domoticz I see something wrong in log,
See in the attachment
[log.txt](https://github.com/domoticz/domoticz/files/8458582/log.txt)

value of bridge/info topic:
[bridge.txt](https://github.com/domoticz/domoticz/files/8458591/bridge.txt)

**Comment by gizmocuz** [comment]
Could you contact me on our Slack channel via

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

**Comment by MarkKoshelev** [comment]
> Could you contact me on our Slack channel via
> 
> https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

Somethings wrong in invitation to Slack. Please send it again

**Comment by MarkKoshelev** [comment]
> 

Done

**Comment by waltervl** [comment]
Closing this. Original issue is solved
