### ISSUE TITLE
DZVENT - Can't get Header authentication to work

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#5213]
Hello,

In my alarm activation DzVent script, I tried to launch the "Motion Eye" container.
I am using Portainer APIs, to depreciate my previous solution, based on SSHPASS to launch a shell command.

It works perfectly from Postman, either with an API key authentication or with the bearer token.
in DZvent, my authentication is never working, with the same parameters as in Postman

Her is my piece of code that does not wok : 

`domoticz.openURL({
                    url = 'https://<my_PORTAINER_URL>/api/endpoints/2/docker/containers/<my_container_ID>/start',
                     method = 'POST',
                     headers = {['X-API-Key'] = '<my_API_Key>'},
                   })`

Here is the response from the portainer's logs : 
`INFO 2022/04/09 12:54:29 http error: A valid authorisation token is missing (err=Unauthorized) (code=401) `

It seems the headers tab is not setting the authentication parameters properly.

thanks a lot

info on versions used : 

Version: 2022.1 (build 14311)
Build Hash: ce05132a3
Compile Date: 2022-04-07 07:48:53
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

**Comment by kiddigital** [comment]
Are you able to verify on the receiving end if the header is indeed missing? (Maybe using wireshark/tcpdump to capture and ascii dump the network traffic)?

**Comment by rezzalex** [comment]
> Are you able to verify on the receiving end if the header is indeed missing? (Maybe using wireshark/tcpdump to capture and ascii dump the network traffic)?

I think the portainer's logs are enought to understand that the authentication part is missing.
Is the whole header is missing ? I don't know and not sure I will be able to use the network mentioned to verify...

**Comment by rezzalex** [comment]
Maybe an important precision :

Postman working requests are coming from a laptop in my lan.

Domoticz openurl dzvent request is coming from a container.

To get the portainer API call working, i am using the external IP address, in order to have the correct SSL certificate domain name association from the portainer point of view.

**Comment by rezzalex** [comment]
if I add a callback in DZvent and try to "intercept" it in the same DzVent script, the DZ logs are showing : 
` 2022-04-10 13:45:36.485  Error: dzVents: Error: (3.1.8) ACTIV_ALARM: HTTP/2 response: 400 ==>> No reason returned!`

**Comment by rezzalex** [comment]
It was a TLS handshake issue while using the HTTPS URL, still don't know how to fix that, but I found a workaround : 
Using the local Portainer http URL in the API call...
