### ISSUE TITLE
MQTT AD humidity is missing from device LCZ030

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5214]
Humidity is missing from device https://www.zigbee2mqtt.io/devices/LCZ030.html#tuya-lcz030
Also in the temp/hum device. I am using:
Version: 2022.1 (build 14312)
Build Hash: c28f4d53a
Compile Date: 2022-04-08 15:53:23
dzVents Version: 3.1.8
Python Version: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]

This is the mqtt config part.
homeassistant/sensor/0xb4e3f9fffe07a12c/humidity/config
{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0xb4e3f9fffe07a12c"],"manufacturer":"TuYa","model":"Temperature & humidity & illuminance sensor with display (LCZ030)","name":"WoonkamerTemperatuur"},"device_class":"humidity","enabled_by_default":true,"json_attributes_topic":"zigbee2mqtt/WoonkamerTemperatuur","name":"WoonkamerTemperatuur humidity","state_class":"measurement","state_topic":"zigbee2mqtt/WoonkamerTemperatuur","unique_id":"0xb4e3f9fffe07a12c_humidity_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.humidity }}"}

If more info is needed, please ask.

**Comment by gizmocuz** [comment]
Could you post the payload of

zigbee2mqtt/WoonkamerTemperatuur

**Comment by SargonofAssyria** [comment]
This is the output of Z2M logging
`info  2022-04-11 11:59:28: MQTT publish: topic 'zigbee2mqtt/WoonkamerTemperatuur', payload '{"alarm_humidity":"off","alarm_humidity_max":90,"alarm_humidity_min":20,"alarm_temperature":"off","alarm_temperature_max":40,"alarm_temperature_min":10,"battery":100,"humidity":44.2,"illuminance":24887,"illuminance_lux":308,"last_seen":"2022-04-11T11:59:28+02:00","linkquality":98,"temperature":20.5,"voltage":3000}'
`
from MQTT Explorer
`{"alarm_humidity":"off","alarm_humidity_max":90,"alarm_humidity_min":20,"alarm_temperature":"off","alarm_temperature_max":40,"alarm_temperature_min":10,"battery":100,"humidity":44.2,"illuminance":24887,"illuminance_lux":308,"last_seen":"2022-04-11T11:59:28+02:00","linkquality":98,"temperature":20.5,"voltage":3000}`

from Domoticz
![11 04 2022_12 03 40_REC](https://user-images.githubusercontent.com/24824113/162715760-186728e9-9dfb-4486-aba0-da339810b152.png)

It is happening on more devices. It looks like that all devices that also have a "humidity_alarm" topic are affected.

**Comment by gizmocuz** [comment]
Could you also post the other config/payload of this sensor ? (the alarm for instance), I will then try to debug this issue..
Aren't you on Slack as well ?

**Comment by SargonofAssyria** [comment]
The complete config set.
[LCZ030.txt](https://github.com/domoticz/domoticz/files/8472331/LCZ030.txt)
. Yes I am on Slack, but there is not much going on, so I created this issue.

**Comment by gizmocuz** [comment]
Thanks, aldo I am not sure what I am looking at.
I need a config topic + payload and the state payload of the humidity_alarm

Maybe for these alarms you can specify 'enabled_by_default' and set this to false? Because you can create those alarms in Domoticz as well.

But maybe with the config topic+payload and the status payload I might be able to make this work

**Comment by SargonofAssyria** [comment]
Enclosed the "alarm_humidity"
[LCZ030_humidity.txt](https://github.com/domoticz/domoticz/files/8474837/LCZ030_humidity.txt)
![12 04 2022_18 32 56_REC](https://user-images.githubusercontent.com/24824113/163010933-0b9f6778-aba9-440e-bded-dea97e03b26f.png)

It is not possible to set the alarms 'enabled_by_default' to false

**Comment by gizmocuz** [comment]
Thanks, but I still miss the 'topics'. Please use MQTT Explorer

'alarm_humidity_max', is this defined as a number object type ? (ha/number...) topic will help

**Comment by SargonofAssyria** [comment]
Enclosed the "alarm_humidity_max" and "alarm_humidity_min" and zigbee2mqtt/WoonkamerTemperatuur
[LCZ030.txt](https://github.com/domoticz/domoticz/files/8488587/LCZ030.txt)
 "unit_of_measurement": "%" and yes they are numeric with boundaries.

**Comment by gizmocuz** [comment]
I need the topics ... without them it is not possible to find a sollution
The config topic is ending with /config, like /zigbee2mqtt/sensor/humidity/0x2799242964/config

**Comment by gizmocuz** [comment]
Once again, aren't you on Slack as well ?

**Comment by SargonofAssyria** [comment]
Like I said above, yes I am on Slack. Continue there?

**Comment by gizmocuz** [comment]
Yes that would be better

**Comment by SargonofAssyria** [comment]
These are the config topics: homeassistant/number/0xcc86ecfffed110f0/alarm_humidity_max  etc....

**Comment by gizmocuz** [comment]
What do you mean 'not much going on' on Slack ? There are MQTT-AD channels, you can PM people

**Comment by SargonofAssyria** [comment]
Last message was from 2 weeks ago, I switched to Slack now.....

**Comment by gizmocuz** [comment]
Yes it's pretty stable

**Comment by SargonofAssyria** [comment]
See Slack: https://domoticz.slack.com/archives/C02DZ8C0ACQ/p1651225979189129?thread_ts=1649934292.064889&cid=C02DZ8C0ACQ

**Comment by gizmocuz** [comment]
I think all is working correct now ? (via slack), if not, please feel free to re-open this issue

**Comment by SargonofAssyria** [comment]
Yes, forgot to check because this unit is a total waist of money and I already removed the device from Zigbee.
The problem with this device is that the temperature delta is 1.1 degree Celsius. And that could not be fixed by a firmware update. So not usable.

**Comment by gizmocuz** [comment]
@SargonofAssyria , sorry to hear that, but you can correct this with domoticz ;)

**Comment by SargonofAssyria** [comment]
No, I mean the delta of the 1.1 degrees is between 2 temperature updates. I only get updates like 22.4 and the next one is 23.5 or 21.3  So really bad and cannot be used my me
