### ISSUE TITLE
blind dummy device type: "blind è stop" no command for stop

### ISSUE THREAD

**Issue by megamarco833** [domoticz/domoticz#5215]
hi, i have create a dummy device and set it as device type: "blind + stop" in this way:
hardware -> dummy device -> switch -> then click modify and i set it as "blind inverted + stop "
but I see that inside the dummy device parameters there is only the ON command (UP) and the OFF command (down), but why there isn't the filed to stop command?
how i can trigger the stop command using the http call ?
![Screenshot 2022-04-11 at 10-34-26 Domoticz](https://user-images.githubusercontent.com/44502572/162697637-46d51f97-f458-4d47-919c-45224400b69e.png)

last thing, i see that with mqtt the stop command is given by nValue = 17 ....why this choise? :)
example when i click stop i see on MQTT `domoticz/out `
`[{ "Battery" : 255, "LastUpdate" : "2022-04-11 10:38:14", "RSSI" : 12, "description" : "", "dtype" : "Light/Switch", "hwid" : "6", "id" : "0001419C", "idx" : 332, "name" : "test", "nvalue" : 17, "stype" : "Switch", "svalue1" : "22", "switchType" : "Blinds Inverted + Stop", "unit" : 1 }]
`

**Comment by gizmocuz** [comment]
There is no stop action. Maybe you can work with a selector switch type ?

**Comment by megamarco833** [comment]
> There is no stop action. Maybe you can work with a selector switch type ?

sorry i didn't understand:
![immagine](https://user-images.githubusercontent.com/44502572/162735781-fa162411-29ee-469f-9569-537a966de8ca.png)

here above there is the stop action....

and if i click on stop button i can see published on topic `domoticz/out `the message:
`[{ "Battery" : 255, "LastUpdate" : "2022-04-11 10:38:14", "RSSI" : 12, "description" : "", "dtype" : "Light/Switch", "hwid" : "6", "id" : "0001419C", "idx" : 332, "name" : "IP57_2", "nvalue" : 17, "stype" : "Switch", "svalue1" : "22", "switchType" : "Blinds Inverted + Stop", "unit" : 1 }] `

that contain nvalue = 17  (every time that stop is pressed)
and svalue1 = the last percentage position

**Comment by waltervl** [comment]
There is no Stop action field programmed in the user  interface for Blinds+Stop. So it also not possible to add a stop action as a user.
So as an alternative you can use a selector switch device instead of a blinds+stop device.
See for example on the forum https://www.domoticz.com/forum/viewtopic.php?t=36640
Note also the up/down/stop symbols this user used in the device configuration.

**Comment by jmcvieira1** [comment]
I use two dummy switches and I created some rules in Blockly to make the stop button work the forum has some examples it's not complicated once you understand the logic, here is the example that i follow https://www.domoticz.com/forum/viewtopic.php?t=24663

**Comment by gizmocuz** [comment]
Solved by using a work-around
