### ISSUE TITLE
MQTT Autodiscovery - need to force rediscovery after restart only for 1 device : Fibaro FGS211

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#5219]
Hello,

all is described here : https://github.com/zwave-js/zwavejs2mqtt/issues/2372
but it seems more related to mqtt autodiscovery rather than Zwavejstomqtt

in Domoticz, after my daily start, I have those logs every 2 min for ... quite a long time, it may be until I force either the full ZwaveJstoMqtt container restart,  or just the Rediscovery of problematic node  (from ZwavejstoMqtt console) : 
`Error: Zwave: disconnected, restarting (rc=19/Unknown error.)`

in the meanwhile, only 1 node is not working... the rest is correctly discovered...

**Comment by waltervl** [comment]
Seems to be better to be discussed on the forum. https://www.domoticz.com/forum/viewforum.php?f=82
Closing this for now until a change for domoticz is needed to solve the issue.
