### ISSUE TITLE
MQTT Auto Disvovery - sensor/node/battery_level messages not recognized

### ISSUE THREAD

**Issue by MichaluxPL** [domoticz/domoticz#5227]
Domoticz build 14318
Platform: Raspberry Pi 4

Looks like battery_level messages are not recognized by Auto Discovery - neither corresponding device is being created in Domoticz., nor any battery status indicator appears with any of corresponding node's devices.
Below is the message, that is stored in MQTT AD topic under AD_TOPIC/sensor part of the MQTT message tree:
{
  "value_template": "{{ value_json.value }}",
  "device_class": "battery",
  "unit_of_measurement": "%",
  "state_topic": "domoticz/in/13/128/0/level",
  "json_attributes_topic": "domoticz/in/13/128/0/level",
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xf3105253_node13"
    ],
    "manufacturer": "Fakro",
    "model": "Roller Shutter (ARZ Z-Wave Solar)",
    "name": "Blind10",
    "sw_version": "1.1"
  },
  "name": "Blind10_battery_level",
  "unique_id": "zwavejs2mqtt_0xf3105253_13-128-0-level"
}

**Comment by CyrilB1531** [comment]
Hello @MichaluxPL I could fix it quite easly be I could not perform good test on it, if you want we could solve it together I fix it and you test it. are you ok with it?

**Comment by MichaluxPL** [comment]
Hi,

Sure, I'll test it :) Let me know if You need any other info.

**Comment by gizmocuz** [comment]
This is done on purpose. When a battery level is send, this value is used to update the actual device battery voltage, and there will not be a stand-alone battery sensor created as this is not needed.
Every device/sensor in Domoticz supports battery level

for example if the JSON contains a battery field this code is executed to the next time when a temperature is received this value is used

```
				if (!root["battery"].empty())
				{
					pSensor->BatteryLevel = root["battery"].asInt();
				}
```

and for any sensor that has 'battery' in it's object name this function is performed

```
	if (
		(pSensor->object_id.find("battery") != std::string::npos)
		&& is_number(pSensor->last_value)
		)
	{
		handle_auto_discovery_battery(pSensor, message);
		return;
	}

```

@MichaluxPL , could you post the complete auto discovery topic of the above config object ?

**Comment by MichaluxPL** [comment]
OK, that's clear now :) I'm testing now blinds MQTT AD patches prepared by @CyrilB1531 and devices created (type Blinds) indeed have battery info available. I'm not sure if that was the case before, when devices were created with type Light/Switch.
I'll look for a complete AD topic and send it later.

**Comment by CyrilB1531** [comment]
Hello,
I haven't change the battery level processing part in your patch. but I am happy the battery level works for you
@gizmocuz I think we could close this issue no?

**Comment by gizmocuz** [comment]
Yes we can close this issue. The battery information is updated once it is received. During auto discovery this is not received yet and hence no battery level initialiy
