### ISSUE TITLE
Solar Radiation Widget value not updated in Mobile UI mode

### ISSUE THREAD

**Issue by IanDury** [domoticz/domoticz#5228]
Solar Radiation device shows no value after the first update when using Mobile UI. See dummy device 'Zonkracht Tuin' in the screenshot:

![image](https://user-images.githubusercontent.com/16663492/167126008-803a5c58-0685-47f3-9eeb-630eec12f6f0.png)

When using Normal UI it works fine.

![image](https://user-images.githubusercontent.com/16663492/167127094-02a514d5-28ff-4e84-8cfb-f4c66a1fc8bb.png)

**Comment by waltervl** [comment]
For me in version 14318 (latest Linux build) Solar Radiation it is working and updating in Mobile UI.
In what version did you test?

**Comment by IanDury** [comment]
I've tested using version 14333 on Debian 11.

**Comment by waltervl** [comment]
Then perhaps your own changes of UVI multiplier are the cause of your issue? As they are introduced later than the version I tested?

**Comment by IanDury** [comment]
Sounds reasonable. I will test your suggestion.

**Comment by IanDury** [comment]
Did a fetch upstream (build 14338), git revert of all my UVI multiplier commits, build and restart domoticz. After clearing the cache on my mobile phone I can see that the multiplier field of the UVI widget is not there anymore but the solar radiation value still does not get updated in mobile UI mode. When refreshing the screen it will show the value but as soon as the value gets updated it doesn't get displayed anymore as you can see in the first screenshot above.

**Comment by waltervl** [comment]
Strange thing is now I tested your scenario again I see the same behavior on dashboard on my test system. For sure I did update before and still had a value visible. But now indeed it is empty until you refresh the page.

Next thing to test if it is present in stable. Will update tomorrow.

**Comment by gizmocuz** [comment]
Thanks for reporting! Found and solved the issue in beta 14381!

**Comment by IanDury** [comment]
Thanks for the fix. Works fine.
