### ISSUE TITLE
MQTT AD issue with ESPHome multiple sensor in one ESPHome node

### ISSUE THREAD

**Issue by enesbcs** [domoticz/domoticz#5232]
When one sensor added to ESPHome it works well with Domoticz MQTT AD, but, when multiple sensors added (on the same ESPHome unit), with distinctive unique ID of course, only one device created on the Domoticz side, as i see based on "dev": {"ids":"","name":""} tags which can not be altered on the ESPHome side - sadly. And all of the ESPHome sensors data arrives to this one Domoticz device: (tested with last stable and last beta Domoticz)

2022-05-08 12:49:01.010 Status: Domoticz V2022.1 (build 14318) (c)2012-2022 GizMoCuz

>ESPHome sends MQTT config:

topic: homeassistant/sensor/blewifirouter1/9de7_battery/config
payload: {"dev_cla":"battery","unit_of_meas":"%","stat_cla":"measurement","name":"9de7_battery","entity_category":"diagnostic","stat_t":"blewifirouter1/sensor/9de7_battery/state","avty_t":"blewifirouter1/status","uniq_id":"ESPsensor9de7_battery","obj_id":"blewifirouter1_9de7_battery","dev":{"ids":"c44f337f7e15","name":"blewifirouter1","sw":"esphome v2022.4.0 May 8 2022, 14:45:24","mdl":"esp32dev","mf":"espressif"}}

topic: homeassistant/sensor/blewifirouter1/9de7_humidity/config
payload: {"dev_cla":"humidity","unit_of_meas":"%","stat_cla":"measurement","name":"9de7_humidity","stat_t":"blewifirouter1/sensor/9de7_humidity/state","avty_t":"blewifirouter1/status","uniq_id":"ESPsensor9de7_humidity","obj_id":"blewifirouter1_9de7_humidity","dev":{"ids":"c44f337f7e15","name":"blewifirouter1","sw":"esphome v2022.4.0 May 8 2022, 14:45:24","mdl":"esp32dev","mf":"espressif"}}

topic: homeassistant/sensor/blewifirouter1/9de7_temperature/config
payload: {"dev_cla":"temperature","unit_of_meas":"°C","stat_cla":"measurement","name":"9de7_temperature","stat_t":"blewifirouter1/sensor/9de7_temperature/state","avty_t":"blewifirouter1/status","uniq_id":"ESPsensor9de7_temperature","obj_id":"blewifirouter1_9de7_temperature","dev":{"ids":"c44f337f7e15","name":"blewifirouter1","sw":"esphome v2022.4.0 May 8 2022, 14:45:24","mdl":"esp32dev","mf":"espressif"}}

topic: homeassistant/sensor/blewifirouter1/eccd_battery/config
payload: {"dev_cla":"battery","unit_of_meas":"%","stat_cla":"measurement","name":"eccd_battery","entity_category":"diagnostic","stat_t":"blewifirouter1/sensor/eccd_battery/state","avty_t":"blewifirouter1/status","uniq_id":"ESPsensoreccd_battery","obj_id":"blewifirouter1_eccd_battery","dev":{"ids":"c44f337f7e15","name":"blewifirouter1","sw":"esphome v2022.4.0 May 8 2022, 14:45:24","mdl":"esp32dev","mf":"espressif"}}

topic: homeassistant/sensor/blewifirouter1/eccd_humidity/config
payload: {"dev_cla":"humidity","unit_of_meas":"%","stat_cla":"measurement","name":"eccd_humidity","stat_t":"blewifirouter1/sensor/eccd_humidity/state","avty_t":"blewifirouter1/status","uniq_id":"ESPsensoreccd_humidity","obj_id":"blewifirouter1_eccd_humidity","dev":{"ids":"c44f337f7e15","name":"blewifirouter1","sw":"esphome v2022.4.0 May 8 2022, 14:45:24","mdl":"esp32dev","mf":"espressif"}}

topic: homeassistant/sensor/blewifirouter1/eccd_temperature/config
payload: {"dev_cla":"temperature","unit_of_meas":"°C","stat_cla":"measurement","name":"eccd_temperature","stat_t":"blewifirouter1/sensor/eccd_temperature/state","avty_t":"blewifirouter1/status","uniq_id":"ESPsensoreccd_temperature","obj_id":"blewifirouter1_eccd_temperature","dev":{"ids":"c44f337f7e15","name":"blewifirouter1","sw":"esphome v2022.4.0 May 8 2022, 14:45:24","mdl":"esp32dev","mf":"espressif"}}

>Domoticz log acknowledge discover

2022-05-08 12:49:26.984 Status: mqttauto: discovered: blewifirouter1/eccd_temperature (unique_id: ESPsensoreccd_temperature)
2022-05-08 12:49:27.085 Status: mqttauto: discovered: blewifirouter1/eccd_humidity (unique_id: ESPsensoreccd_humidity)
2022-05-08 12:49:27.186 Status: mqttauto: discovered: blewifirouter1/eccd_battery (unique_id: ESPsensoreccd_battery)
2022-05-08 12:49:27.287 Status: mqttauto: discovered: blewifirouter1/9de7_temperature (unique_id: ESPsensor9de7_temperature)
2022-05-08 12:49:27.387 Status: mqttauto: discovered: blewifirouter1/9de7_humidity (unique_id: ESPsensor9de7_humidity)
2022-05-08 12:49:27.488 Status: mqttauto: discovered: blewifirouter1/9de7_battery (unique_id: ESPsensor9de7_battery) 

>MQTT data sent by ESPHome:

topic: blewifirouter1/sensor/9de7_battery/state
payload: 88

topic: blewifirouter1/sensor/9de7_humidity/state
payload: 55

topic: blewifirouter1/sensor/9de7_temperature/state
payload: 22.9

>Domoticz log:

2022-05-08 12:49:28.996 mqttauto: Temp + Humidity/THGN122/123/132, THGR122/228/238/268 (blewifirouter1)
2022-05-08 12:49:28.994 Debug: SQLH UpdateValueInt blewifirouter1 HwID:2 DevID:c44f337f7e15 Type:82 sType:1 nValue:0 sValue:22.9;55;1

>MQTT data sent by ESPHome:

topic: blewifirouter1/sensor/eccd_battery/state
payload: 91

topic: blewifirouter1/sensor/eccd_humidity/state
payload: 54

topic: blewifirouter1/sensor/eccd_temperature/state
payload: 22.5

>Domoticz log:

2022-05-08 12:49:29.407 mqttauto: Temp + Humidity/THGN122/123/132, THGR122/228/238/268 (blewifirouter1)
2022-05-08 12:49:29.098 Debug: SQLH UpdateValueInt blewifirouter1 HwID:2 DevID:c44f337f7e15 Type:82 sType:1 nValue:0 sValue:22.5;54;1

**Comment by gizmocuz** [comment]
Yep, that ain't supported as real devices only have one temp+hum. You could try to have a look at the code to see if you can make it working or just use multiple ESP sensors
