### ISSUE TITLE
beta versions are not updated starting from 04/22/2022

### ISSUE THREAD

**Issue by kovainfo** [domoticz/domoticz#5235]
<img width="554" alt="Снимок экрана 2022-05-14 в 17 50 00" src="https://user-images.githubusercontent.com/36986231/168430746-dd45db9b-427e-42a1-8fe9-62fe3f63c0bd.png">

**Comment by kiddigital** [comment]
The Windows beta gets an automated update when new code is added and accepted to the Beta branch.

For the Linux and ARM builds, currently manual work is involved and therefor sometimes it takes some time before the updates are available for direct download and automatic updating on the Beta channel.

You can always build the latest Beta yourself directly from sourcecode.

New Betas will be there soon.
