### ISSUE TITLE
Domoticz crash if Rflink not detected

### ISSUE THREAD

**Issue by hinkma** [domoticz/domoticz#5236]
If Domoticz can't give heartbeat from RFLink Gateway with LAN interfaces Domoticz crash about 1 minute after reboot.
Domoticz version is 2022.1 build 14318.

[domoticz_crash.log](https://github.com/domoticz/domoticz/files/8694717/domoticz_crash.log)

**Comment by gizmocuz** [comment]
To simulate just unplug the USB ?

**Comment by waltervl** [comment]
Closed, no feedback
