### ISSUE TITLE
[Zwave] Add new version of FIBARO FGD212

### ISSUE THREAD

**Issue by MuadDibVV** [domoticz/domoticz#5238]
Is it possible to add the new version of FIBARO FGD212 in the manufacturer_specific.xml : 

`<Product config="fibaro/fgd212.xml" id="1001" name="FGD212 Dimmer 2" type="0102"/>`

Thanks

**Comment by waltervl** [comment]
You can make a PR for this yourself if you are sure adding this line is the solution to get it supported by Domoticz.
I am not sure to what repository though,  domoticz (https://github.com/domoticz/domoticz) or the openzwave ( https://github.com/domoticz/open-zwave ). The original OpenZwave repository ( https://github.com/OpenZWave/open-zwave ) is not updated anymore.

**Comment by kiddigital** [comment]
@MuadDibVV , probably best that you do this update on your local installation.

A PR to the Domoticz fork of open-zwave could be considered but as the original ZWave repo is abandoned, it does not make much sense from a Domoticz perspective to keep updating the fork as there is now a alternative in using ZwaveJS and MQTT Auto Discovery, see

https://www.domoticz.com/wiki/Zwave
https://www.domoticz.com/wiki/ZwaveJS2MQTT

**Comment by MuadDibVV** [comment]
> @MuadDibVV , probably best that you do this update on your local installation.
> 
> A PR to the Domoticz fork of open-zwave could be considered but as the original ZWave repo is abandoned, it does not make much sense from a Domoticz perspective to keep updating the fork as there is now a alternative in using ZwaveJS and MQTT Auto Discovery, see
> 
> https://www.domoticz.com/wiki/Zwave https://www.domoticz.com/wiki/ZwaveJS2MQTT

Ok thank you.
I use ZwaveJS2MQTT to configure this new device but my first test with this solution and domoticz 2022 v1 stable was not a sucess (many freeze) so I came back to the old zwave solution. I will try again with the next stable version.
