### ISSUE TITLE
legacy python framework: Updating a thermostat device creates another sensor

### ISSUE THREAD

**Issue by akamming** [domoticz/domoticz#5241]
This issue is introduced somewhere between latest stable and latest beta (found on beta 14318 on a pi4 buster. Default Domoticz installation)

When i update a setpoint device using the following code (which is claled after i change the value of a setpoint which was created by the plugin):

```
        Debug("onCommand called for Unit " + str(Unit) + ": Parameter '" + str(Command) + "', Level: " + str(Level))
        if Unit in {CURVATURESWITCH,MINBOILERTEMP,MAXBOILERTEMP,BOILERTEMPATMIN10,BOILERTEMPATPLUS20,SWITCHHEATINGOFFAT,
                DAYSETPOINT,NIGHTSETPOINT,FROSTPROTECTIONSETPOINT,REFERENCEROOMCOMPENSATION}:
            if Devices[Unit].sValue=="" or float(Devices[Unit].sValue)!=float(Level):
                Devices[Unit].Update(nValue=int(Level), sValue=str(Level))

```

the result should be that the setpoint is updated with the correct setting and nothing else happens.

However the resulting behaviour is that not only the setpoint device is updated, but a setpoint device is created instantly as well with UnitID 1, having the same updated value:
![image](https://user-images.githubusercontent.com/30364409/169637477-58315f28-388b-4427-bead-8b1fa9780443.png)
 
This has 2 negative side effects:
1. There is garbage in the device list
2. The original device with unitID 1 is no longer usable... (in my case breaking the functionality of the plugin)

fyi: The devices were created using the following code:
```
def CreateSetPoint(SensorName,UnitID,DefaultValue):
    if not (UnitID in Devices):
        Debug("Creating setpoint "+SensorName)
        Domoticz.Device(Name=SensorName, Unit=UnitID, Type=242, Subtype=1, Used=1, Image=15).Create()
        Devices[UnitID].Update(nValue=int(DefaultValue), sValue=str(DefaultValue))

```
the full code can be found [at this link](https://github.com/akamming/Domoticz_Thermostate_Plugin)

**Comment by turin400** [comment]
It's the same thing that happens to me "Problem with device Thermostat SetPoint in plugin #5229"

**Comment by akamming** [comment]
Sorry... did not see that. this is indeed the same issue. Added my findings to #5229   and closing this issue...
