### ISSUE TITLE
Domoticz starts but crashes within seconds

### ISSUE THREAD

**Issue by Adje** [domoticz/domoticz#5243]
i updated today to the latest beta. The interface is starting and for a short period i see all my devices.  Within a minute domoticz crashes totally. In the forum's i see other people mentioning the problem's after updating today.

in de issues i see other problems after updates but they point to ssl3.0. On my pi i still use 1.1. At least that is the response after the command openssl version
[OpenSSL 1.1.1n  15 Mar 2022 ]

[domoticz_craschoud.log](https://github.com/domoticz/domoticz/files/8765101/domoticz_craschoud.log)

**Comment by Bartekn86** [comment]
same problem

**Comment by waltervl** [comment]
Please check forum (the first place to note issues). Similar issues are already noted here:
https://www.domoticz.com/forum/viewtopic.php?f=47&t=38614

Next to that, if you post an issue comply to the rules...
