### ISSUE TITLE
LUA otherdevices['MyDevice'] returns "Toggle" when value is 254

### ISSUE THREAD

**Issue by mealgi** [domoticz/domoticz#5244]
Hello,
Context of the issue :
- Domoticz V2022.1 (beta build from source 14338)
- Python 3.7.3
- running on RPI3B+ 

I found out that when a device temperature nvalue/svalue is 254/25.4 the LUA otherdevices function returns "Toggle" instead of '25.4'.

This causes issues in LUA event scripts using the otherdevices function.

It happens only when the value is 254 and it is relevant to any kind of device type (temperature in my case).

It was not happening in the version 2021.1 13330.

After a short deep dive in the sources I found a difference in the file "RFXNames.cpp" between the 2 versions 13330 and 14338 in the GetLightStatus function.

The version 14338 shows the following piece of code in GetLightStatus where gswitch_sToggle constant value is 0xfe (254):

if (nValue == gswitch_sToggle)
{
lstatus = "Toggle";
return;
}
which is not present in version 13330.

unrespectfully of the device type the GetLightStatus function returns "Toggle" when the nValue is 254. It is the root cause of the issue.

To fix the issue, we should consider the above piece of code to apply only to Lightswitch types devices in the GetLightStatus function.

BR

**Comment by gizmocuz** [comment]
@mealgi , that's correct, 'GetLightStatus' should only be called for lights/switches.

**IsLightOrSwitch(iType, iSubType)** could be used for this

I made a patch to the code and it should be (hopefully) be working correctly now in beta 14348 and up

https://github.com/domoticz/domoticz/commit/4b31d96e003f330079b74eeb6f38d72d042ed155
