### ISSUE TITLE
absolute URLs found

### ISSUE THREAD

**Issue by ldrolez** [domoticz/domoticz#5246]
Domoticz version: 2022.1 (build 14343)

Hi! 

By taking a look at my browser console, I found 2 load erros, related (i think) to absolute URL in the code. My Domoticz is hosted behind a reverse proxy under another path https://myserver.com/domoticz/
So the errors I see are:

- ServiceWorker registration failed:  TypeError: Failed to register a ServiceWorker for scope ('https://myserver.com/') with script ('https://myserver.com/service-worker.js'): A bad HTTP response code (403) was received when fetching the script.
maskable_icon.png:1          
- GET https://myserver.com/images/logo/maskable_icon.png 403 (Forbidden)

=> /domoticz/ should be added after the server name if the URLs were relative.

**Comment by gizmocuz** [comment]
Thank you for spotting this! Should be OK now in version 14347 and up

**Comment by ldrolez** [comment]
I still see this error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://me.com/js/sw-toolbox.js' failed to load. at https://me.com/domoticz/service-worker.js:58:6
