### ISSUE TITLE
P1 counter 

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#5247]
See the new P1 counter  very nice.
@ The same time 3 values devide by the fases, for usage.
Very nice to have and to see. THANKS

Perhaps the same counter possible for delivering back to the net?

**Comment by gizmocuz** [comment]
You mean the sensor with the 3 currents ? Ok, done, should be available in version 14346 and up

**Comment by Dylantje** [comment]
He great work,,,Hi Thanks great work!!!
Other option in the p1 counter, all the fases seperate.
Perhaps also possible.?
3 fase for usage
3 fase for delevering back

If possible love that:-)

**Comment by Dylantje** [comment]
mmm sorry looks they are allready there :-)
