### ISSUE TITLE
Domoticz does not start correctly at power on time

### ISSUE THREAD

**Issue by mealgi** [domoticz/domoticz#5252]
Hello,

Context of the issue :

- Domoticz V2022.1 (beta build from source 14338)
- Python 3.7.3
- running on RPI3B+

Sometimes Domoticz does not restart correctly after a power on.

It generates a signal SIGUSR1 (10) which stops domoticz. 

Consequently I have to launch manually the command "sudo reboot" to restart again Domoticz which is a trouble after a storm caused poweroff.

I discovered the potential root cause of the issue.

In main\SignalHandler.cpp a watchdog thread is created and tests in heartbeat_check() function if the Domoticz  main thread and the mainworker thread are still alive by  checking if the elapsed time from respectively m_LastHeartbeat and  m_mainworker.m_LastHeartbeat have not timed out.

If the watchdog thread is running before the main thread or the mainworker thread have initialized their own  m_LastHeartbeat  data with the actual time then the watchdog thread might raise a SIGUSR1 signal depending on random memory values of these data.

A potential fix for the issue is either for the watchdog thread to:

Option 1 : wait a bit before entering  its working loop : sleep_milliseconds(30000) to let the main thread and mainworker thread initialize the data
Option 2 : to initialize the m_LastHeartbeat and  m_mainworker.m_LastHeartbeat data with the actual time  before entering  its working loop.
	m_mainworker.m_LastHeartbeat = mytime(nullptr);
	m_LastHeartbeat = mytime(nullptr);

BR

**Comment by kiddigital** [comment]
Hi @mealgi , nice find. Feel free to make a PR for it.

**Comment by mealgi** [comment]
Hi kiddigital,
Sorry but I don't know how to do it.
Please could you take over to tackle the issue.
BR

**Comment by mealgi** [comment]
I would prefer the option 2 which is tested successfully on my Domoticz source built version.
BR

**Comment by mealgi** [comment]
Many thanks
BR
