### ISSUE TITLE
Passwords for plugins cannot contain '%' (percent) symbol

### ISSUE THREAD

**Issue by ajarzyn** [domoticz/domoticz#5255]
Version: 2021.1 (build 13949)
System: Docker/Ubuntu

I did not check it with every single plugin there is but I've checked them with few (I think mostly python plugins).
The problem is that password with % in it are not saved into DB.

example password: 3Zg2&oANJ%Tjsv^V

The password after hitting 'add' or 'update' device, seems to be saved and displayed in the password text box.
Unfortunately after changing from Hardware tab to any other and coming back, with highlighting desired device we will see that the password text box is empty.

I've checked with different check boxes and for some others it breaks it to.

Sorry for leaving it here like this but lastly I'm out of energy and time.

**Comment by gizmocuz** [comment]
The reason for this is that we use 'encodeURIComponent' to encode the password before sending this over via the JSON API
I suspect we need to base64 encode/decode this

**Comment by gizmocuz** [comment]
Okey encoding to base64 is also a no go as the username/password can contain UTF8 characters.
That's why we moved to encodeURIComponent some time ago. encode() works, but... seems we can not use this function as it is deprecated?

**Comment by ajarzyn** [comment]
```
$(selector + " #Password").val(): 
"3Zg2&oANJ%Tjsv^V"

encodeURIComponent(($(selector + " #Password").length == 0) ? "" : $(selector + " #Password").val()): 
"3Zg2%26oANJ%25Tjsv%5EV"
```

`&` is translated to `%26`
`%` is translated to `%25`
`^` is translated to `%5E`

I don't see problem with encodeURIComponent.
And the json REST API returns:
```
{
	"status" : "OK",
	"title" : "UpdateHardware"
}
```

Either there is data incorrectly saved to DB or in `Hardware.js:3890`.

`var data = oTable.fnGetData(anSelected[0]);`
returns incorrect data from DB
`data["Password"]: ""`

Is there any easy way to check what's goes into DB?

**Comment by gizmocuz** [comment]
@ajarzyn , you could go to settings, and make a 'backup' of the database and open this with (for example) SQLite Expert Personal edition. Then go to the hardware table and you can see the encoded password that you can decode online

Another option is to set a break point in **CWebServer::Cmd_UpdateHardware** where you can see what the password is coming from the JSON call

I debugged it further... the JSON call is correctly sending the encoded password

Found and corrected the issue. By the GET/POST commands the data was already URL decoded, and in the web server (add/update hardware) it was being decoded again and this caused an issue....

New beta is available

**Comment by ajarzyn** [comment]
Sorry I couldn't help any more but I'm glad you found the problem.

Backuping DB is a cleaver idea I will keep it on my mind.

What IDE are you using with Domoticz that you can set breakpoint in `CWebServer::Cmd_UpdateHardware`?

**Comment by gizmocuz** [comment]
I am using Visual Studio Community Edition
