### ISSUE TITLE
Potentially Vulnerable to Clickjacking

### ISSUE THREAD

**Issue by davidKooreman** [domoticz/domoticz#5259]
Plugin Details
Severity:Medium
ID:85582
Version:$Revision: 1.7 $
Type:remote
Family:Web Servers
Published:August 22, 2015
Modified:May 16, 2017
Risk Information
Risk Factor: Medium
CVSS v2.0 Base Score: 4.3
CVSS v2.0 Vector: CVSS2#AV:N/AC:M/Au:N/C:N/I:P/A:N
Reference Information
CWE:  [693](http://cwe.mitre.org/data/definitions/693)
MEDIUMWeb Application Potentially Vulnerable to Clickjacking
Description
The remote web server does not set an X-Frame-Options response header or a Content-Security-Policy 'frame-ancestors' response header in all content responses. This could potentially expose the site to a clickjacking or UI redress attack, in which an attacker can trick a user into clicking an area of the vulnerable page that is different than what the user perceives the page to be. This can result in a user performing fraudulent or malicious transactions.

X-Frame-Options has been proposed by Microsoft as a way to mitigate clickjacking attacks and is currently supported by all major browser vendors.

Content-Security-Policy (CSP) has been proposed by the W3C Web Application Security Working Group, with increasing support among all major browser vendors, as a way to mitigate clickjacking and other attacks. The 'frame-ancestors' policy directive restricts which sources can embed the protected resource.

Note that while the X-Frame-Options and Content-Security-Policy response headers are not the only mitigations for clickjacking, they are currently the most reliable methods that can be detected through automation. Therefore, this plugin may produce false positives if other mitigation strategies (e.g., frame-busting JavaScript) are deployed or if the page does not perform any security-sensitive transactions.
Solution
Return the X-Frame-Options or Content-Security-Policy (with the 'frame-ancestors' directive) HTTP header with the page's response.
This prevents the page's content from being rendered by another site when using the frame or iframe HTML tags.
See Also
http://www.nessus.org/u?399b1f56
https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet
https://en.wikipedia.org/wiki/Clickjacking
Output
The following pages do not use a clickjacking mitigation response header and contain a clickable event :

  - http://domoticzl/
  - http://domoticz./
  - http://domoticz/secpanel/index.html
  - http://domoticzl/secpanel/index.html

**Comment by kiddigital** [comment]
@davidKooreman , thanks for reporting.

Adding a CSP header seems a good idea. 

Figuring out which policy would be the best/default for Domoticz needs some thought as many/most users run Domoticz within their private networks not exposing the webserver to the internet.

Also for other security related topics (see for example the OAuth2 Pull Request) adding an option to specify a (virtual)hostname is considered. Using such a hostname for the CSP policy is also an option.

**Comment by gizmocuz** [comment]
Please feel free to make a PR for this if needed.

**Comment by kiddigital** [comment]
> Please feel free to make a PR for this if needed.

It is being addresses in PR #4872 so I prefer to leave this issue 'open' for now so it is clear that it is a known possible vulnerability when opening up things to much. And that it could be solved once the security improvements make it into the release.
