### ISSUE TITLE
Can't compile on Windows

### ISSUE THREAD

**Issue by ultrasuperpingu** [domoticz/domoticz#5262]
I follow the instructions on the dedicated page: https://github.com/domoticz/domoticz/blob/development/INSTALL.md but it doesn't work.
I've started to develop on domoticz many years ago. At the time, there was only a 7zip package you had to unzip in the correct directory. Then, vcpkg was introduced in the build process but following the instructions on the build process was working flawlessly. Few monthes ago, I updated my repository and the build process was not working anymore. I had no time to figure out why at the time and I didn't tryied to find out what the problem was. I now changed my computer and I tried to build from scratch but the vcpkg packages are not in the project dependancies and I don't understand why. I'm pretty sure the `vcpkg.exe integrate install` should do the job but it doesn't seem to work for me.
The command seems ok:

```
All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/PathToTheRepo/msbuild/vcpkg/scripts/buildsystems/vcpkg.cmake"

```
But it doesn't find the includes when compiling.

Of course, I could add them manually but I guess there is a problem so here is this issue (a documentation issue?).

I probably just missed something (I'm not familiar to vcpkg, sorry) and if so, I'm really sorry but I tried twice to follow the documentation and failed on both attempt.

Edit: I use Visual Studio 2022 and documentation say I should use Visual Studio 2019, I guess that the problem. Sorry, I'll try and I will close it if it's working.

**Comment by waltervl** [comment]
Perhaps check this forum topic too https://www.domoticz.com/forum/viewtopic.php?p=266121

**Comment by gizmocuz** [comment]
These are the instructions from the INSTALL.md file:

### Windows
- You need Visual Studio 2019 (Community Edition is perfect and is free)
- The project file for Visual Studio can be found inside the "msbuild" folder
- You need to download `WindowsLibraries.7z` from https://github.com/domoticz/win32-libraries	- For the Initial setup, Launch Visual Studio and from the 'Tools' menu choose 'Visual Studio Command Prompt'
  and unpack the archive inside the "msbuild" folder.

**Comment by gizmocuz** [comment]
Visual studio 2022 is now recommended

**Comment by ultrasuperpingu** [comment]
I'm sorry, I didn't had much time to take a closer look at it. As I said, I followed carrefully the instructions in INSTALL.md
I found the issue, and I was pretty stupid with it. It's just that the instructions contains:

`set VCPKG_DEFAULT_TRIPLET=x86-windows`

So you have to compile for x86, not x64 (which is default configuration at least on my setup).
But I can see from the forum that I'm not the only one to had problems with it.

**Comment by ultrasuperpingu** [comment]
Just to know, is x64 build not in the focus of the documentation by design? If you don't want to focus your work on x64, why don't you remove it from the vcproj?

**Comment by gizmocuz** [comment]
@ultrasuperpingu , I think the documentation could use a little help. Domoticz should be able to compile fine for 32 and 64 bit architectures.

We might need to mention to use either x86 or x64 depending on the target

`set VCPKG_DEFAULT_TRIPLET=x64-windows`

I personally have created two batch files to install/remove packages

_doinstall.bat_
vcpkg install --triplet x86-windows %*
vcpkg install --triplet x64-windows %*
vcpkg install --triplet x86-windows-static %*
vcpkg install --triplet x64-windows-static %*

_doremove.bat_
vcpkg remove --recurse --triplet x86-windows %*
vcpkg remove --recurse --triplet x64-windows %*
vcpkg remove --recurse --triplet x86-windows-static %*
vcpkg remove --recurse --triplet x64-windows-static %*

Please feel free to modify the documentation
