### ISSUE TITLE
No Update 'Raspberry's GPIO port hardware' mode out

### ISSUE THREAD

**Issue by moebius911** [domoticz/domoticz#5263]
Hello
I need help on 'Raspberry's GPIO port hardware'.
Following the domoticz wiki, the plugin works very well. However when the pins are configured as output, the module does not update them.
For example during a reboot I set the pins to 0. Domoticz keeps the previous ON state without updating.
Is this a bug on my side or is it a plugin problem?
Thanks in advance
Cordially

**Comment by waltervl** [comment]
That is a plugin issue as when you set GPIO pins to output domoticz will only send data and cannot read it.

I will close this issue as we have a forum for this. So if you want to discuss this more please use the forum (also a bigger audience).
See https://www.domoticz.com/forum/viewforum.php?f=32
