### ISSUE TITLE
After updating beta, Xiaomi Gateway RGB Switch doesn't work

### ISSUE THREAD

**Issue by acaonweb** [domoticz/domoticz#5267]
After updating beta
Version: 2022.1 (build 14369)
Build Hash: 00c5d7861
Compile Date: 2022-06-27 10:39:10
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
Xiaomi gatway RGB switch doesn't works

log says that

<img width="602" alt="Schermata 2022-07-02 alle 19 25 25" src="https://user-images.githubusercontent.com/22882393/177010355-df13cf76-0d24-41f5-8b81-b369e76b4d7b.png">

Clicking on the switch
<img width="618" alt="Schermata 2022-07-02 alle 19 26 18" src="https://user-images.githubusercontent.com/22882393/177010380-4ae7304d-dd14-4c37-9eff-63e35d7fb67b.png">

xiaomi plugin changed, before I had only key field, now i have username and password

<img width="761" alt="Schermata 2022-07-02 alle 19 27 46" src="https://user-images.githubusercontent.com/22882393/177010452-a2ca25cf-2620-4d78-9345-c7423b4e61aa.png">

Switch, body sensors, door sensors works fine

Wha i have to do?
Thanx

**Comment by StKob** [comment]
#5264

**Comment by acaonweb** [comment]
So I need to wait a fix? Or I can do something?

**Comment by StKob** [comment]
You can roll back to release version.

**Comment by acaonweb** [comment]
Ok, but a fix will arrive, right?

**Comment by gizmocuz** [comment]
@acaonweb , the problem was with the OpenSSL code inside this class. It was not 3.0 compatible anymore.
So we tried to rewrite it.... (tried as we could/can not test this as we do not own this hardware)
I did some small rewrite in beta 14370, maybe you could test this ?
Hope it works, else it would be great if the original author of this class could have a look at this

**Comment by gizmocuz** [comment]
@acaonweb , sorry new patch in beta 14372, I think we need to assume the key/payload is always 16 bytes (pad it to 16)
Hope this works!

**Comment by acaonweb** [comment]
Ok, how can I test it?
My skills are poor, I just update beta when Domoticz show me it is available 😄 
But as I have the hardware, tel me how and I'll check it 😄

**Comment by acaonweb** [comment]
I'm updating beta😄

**Comment by acaonweb** [comment]
It works thanks 😄

**Comment by gizmocuz** [comment]
Great!, Thanks for the feedback!
