### ISSUE TITLE
Error when updating sensors using JSON API

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#5269]
Domoticz release: 14369
Platform: Linux x64 / ubuntu focal

Since updating from release 14352 to 14369, I have the following issues when updating some sensors or counters using the JSON API.
These scripts have worked perfectly until now. 
Even though I'm sending the required number of arguments, Domoticz only sees the 1st one, and claims the others are missing.
The counters are therefore not getting updated.
This is happening for 2 counter types:
### Temp + Humidity
Update url: `https://domoticz.redacted.com:443/json.htm?type=command&param=udevice&idx=76&nvalue=0&svalue=26.6;43;1`

Error: Status: `Warning: Expecting svalue with at least 2 elements separated by semicolon, 1 elements received ("26.6"), notification not sent (Hardware: 3 - Virtual, ID: 82075, Unit: 1, Type: 52 - Temp + Humidity, SubType: 1 - THGN122/123/132, THGR122/228/238/268)`

### P1 Smart Meter
Update url: `https://domoticz.redacted.com:443/json.htm?type=command&param=udevice&idx=789&nvalue=0&svalue=13218988;5080219;0;0;0;0`

Error: `Status: Warning: Expecting svalue with at least 5 elements separated by semicolon, 1 elements received ("13218988"), notification not sent (Hardware: 3 - Virtual, ID: 82789, Unit: 1, Type: FA - P1 Smart Meter, SubType: 1 - Energy)`

**Comment by gizmocuz** [comment]
@Olivier6767 , I tested with 14370+ and there is no problem updating the sensors via the JSON API when I copy/paste your URL's directly into a browser.
If you use this via a script, maybe make sure to (or not to) escape the url's
Anyway they should work without issue from the browser to start with

**Comment by Olivier6767** [comment]
@gizmocuz, Thanks for the tip.
I can confirm that the issue is not linked to Domoticz but is linked to an update of the reverse proxy I'm using (**Traefik**).
I modified my scripts to ensure the content of the `svalue` parameter is now escaped. 

[Link to Traefik related issue](https://github.com/traefik/traefik/issues/9164)

This fixes the issue.
