### ISSUE TITLE
Anna thermostat setpoint adjust cooling mode setpoint

### ISSUE THREAD

**Issue by awalsum** [domoticz/domoticz#5277]
I'm running Domoticz 2022.1 (build14352) on Ubuntu and have detected a bug in the Anna (Plugwise) thermostat. I have an Elga heat pump and the Anna has been setup by Plugwise to also communicate with the Elga.

In the settings part of the Plugwise app, under "Heating settings"->"Elga settings"->"Configuration" there is a setting for the cooling mode. Here you can set the temperature for which the thermostat switches the cooling mode on or off.

For some reason, when I set the thermostat for the room temperature from Domoticz, it also adjusts this cooling mode set point. This causes problems because when I set the room thermostat to, say 21°C, it also sets the cooling mode set point to 21°C and if at that moment the outdoor temperature read by the Anna is 22°C, the thermostat automatically goes back to the cooling mode set point.

I have looked in the code to see if I can find where things go wrong, but haven't been able to find it.

**Comment by gizmocuz** [comment]
@awalsum , the setpoint is set here:

CAnnaThermostat::SetSetpoint
