### ISSUE TITLE
mqtt ON/OFF commands seem reversed>

### ISSUE THREAD

**Issue by peteralm097** [domoticz/domoticz#5287]
I am having an is this just me moment...

I updated to latest beta last night on my rpi3. Some very straaaaange things happened in my house. The family were away last night and my normal all off button had lights going on and off all over the place! Quite spooky!

This morning after some more careful inspection the following is true;

zigbee2mqtt dashboard works as expected switching on and off as required. There are no errors in the log.
Domoticz shows a light that is OFF as OFF but on switching it ON zibee2mqtt log shows an OFF command was interpreted and sent to the device.
The app has the same behaviour.

Reverting to a 17th July beta backup fixes the issue. Now I have little skills in  coding compared to you all, but I suspect Pull Request #5284 between 12518 and 12523 as this is related to MQTT autodiscovery and appears to make an ON an OFF and vice versa.

My backup restore was successful, but if you have zigbee2mqtt or in fact any other mqtt this may affect you!

**Comment by kipusoep** [comment]
Yes this is **exactly** what I'm running into at the moment as well!
I thought I was losing it.....
I'm not using a beta version btw, this started happening after my scheduled docker image updates this morning.
So I'm using `domoticz/domoticz:latest` which was updated 21 hours ago.

For now I'm using `2022-beta.14420` until fixed.

**Comment by kiddigital** [comment]
> I'm not using a beta version btw, this started happening after my scheduled docker image updates this morning.
> 
> So I'm using `domoticz/domoticz:latest` which was updated 21 hours ago.
> 
> 
Dockers are on Beta. So 'latest' is latest Beta.

**Comment by kipusoep** [comment]
Thanks for the clarification, I didn't know that. I guess there's no stable alternative at the moment right?

**Comment by gizmocuz** [comment]
you can also checkout a specific version like domoticz/domoticz:14xxxx, all builds have a number

**Comment by gizmocuz** [comment]
Hope to create a new stable soon,  lot of work has been put in the mqtt-ad and also the reversed blinds.
when all is working correctly it's about time

**Comment by gizmocuz** [comment]
Hope to create a new stable soon,  lot of work has been put in the mqtt-ad and also the reversed blinds.
when all is working correctly it's about time

**Comment by gizmocuz** [comment]
Hope to create a new stable soon,  lot of work has been put in the mqtt-ad and recently also the reversed blinds correction

**Comment by gizmocuz** [comment]
Hope to create a new stable soon,  lot of work has been put in the mqtt-ad and also the reversed blinds.
when all is working correctly it's about time

**Comment by gizmocuz** [comment]
Hope to create a new stable soon,  lot of work has been put in the mqtt-ad and recently also the reversed blinds correction

**Comment by gizmocuz** [comment]
A new PR has been merged into beta 14438 that could/should solve this

**Comment by kipusoep** [comment]
@gizmocuz seems to work for me :-)

**Comment by gizmocuz** [comment]
Great! Thanks for the feedback and @CyrilB1531 for his work

**Comment by FredWst** [comment]
Hi

See #5288 for MQTT not working with dummy blinds.

Seems to be a side effect.

Fred

**Comment by gizmocuz** [comment]
As the origin of this issue relates to on/off commands and this issue seems to be solved i am closing this issue
