### ISSUE TITLE
Enhancement - separate 'allow new devices' for MQTT from other hardware

### ISSUE THREAD

**Issue by jefft4** [domoticz/domoticz#5292]
An enhancement request, for usability:
- I need to have 'allow new devices' on as the various MQTT autodiscovery hardware drivers seem to need it at startup and other times;
- this means that it's on permanently, which means that RFXCom keeps finding more 433MHz devices to add to the thousands of my neighbours' devices it's already listed (433 devices are a PITA as they tend to change their IDs whenever batteries are replaced)

The request:
- separate the 'allow new devices' for MQTT autodiscovery from the 'allow new devices' for other hardware.

**Comment by pipiche38** [comment]
Interested to understand why decoupling it

**Comment by jefft4** [comment]
> Interested to understand why decoupling it

For the reason I explained - having 'allow new' on permanently is needed for MQTT but is highly undesirable with other hardware types.

**Comment by gizmocuz** [comment]
That could be said for more hardware and will complicate the user interface. For now, just press 'allow for 5 minutes', and after this, delete the thousands of your neighbors unwanted received devices.
It is for sure not many times a day you add new devices, and if you do, just go to the device tab, make a filer for RFXCom, and select the devices to be removed. It's a quick and easy process

**Comment by gizmocuz** [comment]
Actually MQTT-AD bypasses this and will add all discovered devices anyway. So you can leave this on
