### ISSUE TITLE
Bresser lightning detector support

### ISSUE THREAD

**Issue by AndreyMihaylov85** [domoticz/domoticz#5301]
Hello,

Does anyone decode Bresser Lightning detector 868mhz yet ? 

![e7cba463c6f19be746677f74a6ac6948_c3129a-v0_bresser_01](https://user-images.githubusercontent.com/110809838/183410681-0adfc900-c101-4cab-ae2b-d2f1a13b5efa.png)

here is captured samples:

Test mode active. Reading samples from file: g045_868M_1000k.cu8
baseband_demod_FM: low pass filter for 250000 Hz at cutoff 25000 Hz, 40.0 us
Detected FSK package    @0.088888s
Analyzing pulses...
Total count:   57,  width: 71.66 ms             (17915 S)
Pulse width distribution:
 [ 0] count:    6,  width: 1500 us [1456;1712]  ( 375 S)
 [ 1] count:   47,  width:  484 us [480;492]    ( 121 S)
 [ 2] count:    4,  width:  976 us [972;980]    ( 244 S)
Gap width distribution:
 [ 0] count:   47,  width:  484 us [480;492]    ( 121 S)
 [ 1] count:    4,  width: 1456 us [1456;1460]  ( 364 S)
 [ 2] count:    1,  width: 1936 us [1936;1936]  ( 484 S)
 [ 3] count:    3,  width:  968 us [968;972]    ( 242 S)
 [ 4] count:    1,  width: 2428 us [2428;2428]  ( 607 S)
Pulse period distribution:
 [ 0] count:   10,  width: 2116 us [1944;2432]  ( 529 S)
 [ 1] count:   41,  width:  968 us [968;976]    ( 242 S)
 [ 2] count:    3,  width: 1452 us [1452;1456]  ( 363 S)
 [ 3] count:    2,  width: 2912 us [2908;2916]  ( 728 S)
Pulse timing distribution:
 [ 0] count:   10,  width: 1484 us [1456;1712]  ( 371 S)
 [ 1] count:   94,  width:  484 us [480;492]    ( 121 S)
 [ 2] count:    7,  width:  972 us [968;980]    ( 243 S)
 [ 3] count:    1,  width: 1936 us [1936;1936]  ( 484 S)
 [ 4] count:    1,  width: 2428 us [2428;2428]  ( 607 S)
 [ 5] count:    1,  width: 36060 us [36060;36060]       (9015 S)
Level estimates [high, low]:  15927,    424
RSSI: -0.1 dB SNR: 15.7 dB Noise: -15.9 dB
Frequency offsets [F1, F2]:   22601,   2388     (+86.2 kHz, +9.1 kHz)
Guessing modulation: Pulse Code Modulation (Not Return to Zero)
view at https://triq.org/pdv/#AAB031060105CC01E403CC0790097C8CDC8191919191919191919191919191919191919191919191919091A1819190918091819355+AAB014060105CC01E403CC0790097C8CDCA1A28291919455+AAB01E060105CC01E403CC0790097C8CDC91919192A0919191819191919191919555
Attempting demodulation... short_width: 484, long_width: 484, reset_limit: 495616, sync_width: 0
Use a flex decoder with -X 'n=name,m=FSK_PCM,s=484,l=484,r=495616'
pulse_demod_pcm(): Analyzer Device
bitbuffer:: Number of rows: 1
[00] {222} f5 55 55 55 55 55 51 6e a2 e2 e8 6c e5 41 54 c5 5d 55 50 00 00 00 00 00 00 00 00 00

Flex decoder data: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2022-08-08 18:26:49
model     : test         count     : 1             num_rows  : 1             rows      :
len       : 35           data      : 6ae500000
codes     : {35}6ae500000

https://triq.net/bitbench#c=%5B00%5D%20%7B222%7D%20f5%2055%2055%2055%2055%2055%2051%206e%20a2%20e2%20e8%206c%20e5%2041%2054%20c5%205d%2055%2050%2000%2000%2000%2000%2000%2000%2000%2000%2000&f=hh%20ID%3Ahh%20b%20CH3d%20TEMP_C%3A12d%20HUM%3Ad%20CRC%3A8h%20%7C%208h%2016h%2016h%20&cw=4

Any help how to create decoder will be highly appreciated. 

thank you

**Comment by waltervl** [comment]
This is unfortunately not the right place to discuss this as it has nothing to do with Domoticz source code.
Please try to contact the supplier of your 868 transceiver if your sensor is supported and how it should be connected.
Perhaps you get lucky on the Domoticz sub forum for 433 and 868 transceivers, it also has a bigger audience. https://www.domoticz.com/forum/viewforum.php?f=74

**Comment by gizmocuz** [comment]
@AndreyMihaylov85 , Looks like a interesting device. I have build one detector that uses a open/close contact, this seems nicer!
Maybe you could contact RFXCom to see if they can add/support this in their hardware?
