### ISSUE TITLE
Dimmers are not shown correctly in the Web GUI

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5302]
Updated to 14453 a few days ago and it looks like all my shutters and blinds (RFY and Zigbee) are working fine in the GUI and controlled by dzVents. There is now 1 problem left.
 
![10 08 2022_12 21 48_REC](https://user-images.githubusercontent.com/24824113/183879234-444083bf-f86c-4c77-9548-b0639c750563.png)
The slider of all my dimmer (bulbs) devices always show 100% The devices are working correctly by the GUI and dzVents but the display in the GUI is not.

**Comment by roland821** [comment]
happend to me also. clearing browser cache got it working again

**Comment by SargonofAssyria** [comment]
Browser cache should not be an issue anymore. But to be clear I used Ctrl-F5 and used CCleaner, but that did not bring the solution.

**Comment by SargonofAssyria** [comment]
Upgraded to build 14456 today, but the slider problem still exists.

**Comment by arjanvanleent** [comment]
What z-wave plugin are you using? Have seen this problem too but when I switched to auto discovery is all worked perfectly.

**Comment by SargonofAssyria** [comment]
It is not zwave but zigbee devices from which the slider always showed correctly as they should in the GUI. I use the 'Stanislav Demydiuk' plugin for years now. I updated the plugin and the slider shows correctly and status in the right upper corner too.
