### ISSUE TITLE
icons overlapping on mobile view

### ISSUE THREAD

**Issue by megamarco833** [domoticz/domoticz#5307]
hi, i'm with build 14453 (beta)
in main page of mobile view, the switch icons sometimes (i think it happen with long names) are showed with ON and OFF buttons one above the other instead of having ON and OFF buttons one beside of the other.
looking at the code in /home/pi/domoticz/www/app/DashboardController.js
at line 2348
`										'\t       <td id="status" class="status">' + status + '</td>\n' +`
to avoid this issue adding a `nowrap` in this line will fix it:

`										'\t       <td id="status" class="status" nowrap>' + status + '</td>\n' +`

* example **without** nowrap:
![immagine](https://user-images.githubusercontent.com/44502572/185562546-403c88a7-157c-4a01-b005-565fb537cd33.png)

* example **with** nowrap:
![immagine](https://user-images.githubusercontent.com/44502572/185562430-8fa3393f-16ed-4028-9737-0eb65c5924bb.png)

is it possible to implement this fix in the next build?
what do you think?

thanks a lot

P.S. 
i will copy the part of the code to recognize where to add nowrap to avoid maybe differences between my build and the last one:
(the modification is only adding `nowrap` as explained above)

	```
								else {
										if (
											(item.Status == 'On') ||
											(item.Status == 'Chime') ||
											(item.Status == 'Group On') ||
											(item.Status.indexOf('Down') != -1) ||
											(item.Status.indexOf('Up') != -1) ||
											(item.Status.indexOf('Set ') == 0)
										) {
											status =
												'<button class="btn btn-mini btn-info" type="button" onclick="SwitchLight(' + item.idx + ',\'On\',' + item.Protected + ');">' + $.t("On") + '</button> ' +
												'<button class="btn btn-mini" type="button" onclick="SwitchLight(' + item.idx + ',\'Off\',' + item.Protected + ');">' + $.t("Off") + '</button>';
										}
										else {
											status =
												'<button class="btn btn-mini" type="button" onclick="SwitchLight(' + item.idx + ',\'On\',' + item.Protected + ');">' + $.t("On") + '</button> ' +
												'<button class="btn btn-mini btn-info" type="button" onclick="SwitchLight(' + item.idx + ',\'Off\',' + item.Protected + ');">' + $.t("Off") + '</button>';
										}
									}
									xhtm +=
										'\t       <td id="status" class="status" nowrap>' + status + '</td>\n' +
										'\t    </tr>\n';
									if (item.SwitchType == "Dimmer") {
										xhtm += '<tr>';
										xhtm += '<td colspan="2" style="border:0px solid red; padding-top:10px; padding-bottom:10px;">';
										xhtm += '<div style="margin-top: -11px; margin-left: 24px;" class="dimslider dimslidernorm" id="light_' + item.idx + '_slider" data-idx="' + item.idx + '" data-type="norm" data-maxlevel="' + item.MaxDimLevel + '" data-isprotected="' + item.Protected + '" data-svalue="' + item.LevelInt + '"></div>';
										xhtm += '</td>';
										xhtm += '</tr>';


```

**Comment by gizmocuz** [comment]
@megamarco833 , thank you for spotting and reporting this issue!
Yes this is possible, but there are possibly more locations where this needs to be changed.

Maybe it is better to modify the 'status' CSS style to include the nowrap ? Is it possible to test this?
The only other place where I see that the status class is used is in ScenesController.js, maybe it should not be used there ?

**Comment by megamarco833** [comment]
> @megamarco833 , thank you for spotting and reporting this issue! Yes this is possible, but there are possibly more locations where this needs to be changed.
> 
> Maybe it is better to modify the 'status' CSS style to include the nowrap ? Is it possible to test this? The only other place where I see that the status class is used is in ScenesController.js, maybe it should not be used there ?

hey @gizmocuz thanks for fast feedback.
honestly i don't have the skills to judge the best approach to solve the issue.
what i can say is only that i tested the modification proposed and it works as you can see :)
let's proceed with the way that for you is the best approach :)
please let me know about it

**Comment by gizmocuz** [comment]
I made a small patch in the style sheet that solves this issue.
Beta 14463 should have no issues
Thanks for reporting and your time for the PR!!

**Comment by megamarco833** [comment]
thanks, i tested and it is working!

**Comment by megamarco833** [comment]
@gizmocuz 
hello, I'm on domoticz 14775 and the issue about the icons is come back.
here below you can see the screenshot from my mobile: as you can see the first set of icons has the button overlapped the second set has the correct button location one beside the others.
is it a bit strange because it seams not linked to "long devices name" like it was before the previous fix on beta 14463...because now devices with long names are displayed correctly....but they are blinds, the other (wrong displayed) are lights

![photo_2022-12-19_15-49-13](https://user-images.githubusercontent.com/44502572/208453685-e0bde3c6-f49f-46e7-aa29-64c1d795403c.jpg)


is it possible to fix it?
thanks so much
