### ISSUE TITLE
MQTT hardware setting. Not possible to configure "Prevent Loop" to "False".

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#5308]
If you need "Prevent Loop" setting "False" this setting is not stored. Domoticz keeps the setting as "True".
Tested it with version 14456,
See also the thread starting at 23 Jun 2022, 20:59 in Forum topic: https://www.domoticz.com/forum/viewtopic.php?f=28&t=37052&sid=fad6e23de593382563c18957a45284ce

**Comment by gizmocuz** [comment]
Thanks for reporting!

A quick look at the browsers developers network console revealed the state (true/false) is pushed to the server (mode3)

When checking the database, this is also stored correctly

This means that this parameter is also used in the real hardware, also verified, loop is prevented or not depending on the configured setting

This could mean that the setting is probably not correctly displayed only in the web interface, also verified via the browser developers network console as the hardware parameters are correctly received via the JSON commands

Found the issue, corrected in beta 14461

But the prevention setting worked (except for the display in the gui)

Please report in the forum if it's working

**Comment by FireWizard52** [comment]
Not solved, yet
See latest forum post.

**Comment by gizmocuz** [comment]
@FireWizard52 , now it's fixed in beta 14464

Was checking for a empty string, but == _apparently_ checks for 0 as well , now using === in the javascript code

**Comment by FireWizard52** [comment]
@gizmocuz,

Downloaded the 14464, tested it in my test system and can confirm it works now.
Thanks for your quick response and corresponding action. A number of people will be happy.

Regards
