### ISSUE TITLE
It is not possible to control a door type device directly from a FloorPlan

### ISSUE THREAD

**Issue by mealgi** [domoticz/domoticz#5310]
Context :
Version: 2022.1 (build 14338)
Build Hash: 8d73c42d6-modified
Compile Date: 2022-05-15 19:47:20
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

Issue : It is not possible to control a door type device directly from a plan
When you click on the door icon the command is Off whatever its status Open/Closed

Solution : 
In DomoticzDevices.js 
in function Switch(item) 
replace line 1281
       this.onClick = "SwitchLight(" + this.index + ",'" + ((this.status == "Off") ? "On" : "Off") + "'," + this.protected + ");";
by
		if (this.status == "Off" || this.status == "On" ) {
			this.onClick = "SwitchLight(" + this.index + ",'" + ((this.status == "Off") ? "On" : "Off") + "'," + this.protected + ");";
		} else {
			this.onClick = "SwitchLight(" + this.index + ",'" + ((item.Status == "Closed" || item.Status == "Locked") ? "Off" : "On") + "'," + this.protected + ");";
		}	

and line 1295
        this.onClick = "SwitchLight(" + this.index + ",'" + ((this.status == "Off") ? "On" : "Off") + "'," + this.protected + ");";
by
		if (this.status == "Off" || this.status == "On" ) {
			this.onClick = "SwitchLight(" + this.index + ",'" + ((this.status == "Off") ? "On" : "Off") + "'," + this.protected + ");";
		} else {
			this.onClick = "SwitchLight(" + this.index + ",'" + ((item.Status == "Closed" || item.Status == "Locked") ? "Off" : "On") + "'," + this.protected + ");";
		}	
BR

**Comment by gizmocuz** [comment]
@mealgi , could you tell me what switch type specified for your door?
Could you also add a screenshot?
Could you also test with the latest beta version?

I added a dummy hardware, a switch, changed the type to door-lock, added a room plan, placed the door in this, added a floorplan
When I click on the door icon, I get the Log, it does not switch between open/off

**Comment by mealgi** [comment]
Hello

 

It is a door lock device with custom icon

 

Open



 

Closed



 

 

With the initial version I can only open the door when clicking

 

With the solution implemented when I click I can open/close the door depending on its status.

 

BR

**Comment by mealgi** [comment]
Hello
I did not check with the latest beta.
However I downloaded DomoticzDevices.js from GitHub and checked with my own original version. The 2 files are identical.
BR

**Comment by gizmocuz** [comment]
@mealgi, please do not use email replies directly with GitHub. As you can see in your message above there are no screenshots

Line 1281 is a closing bracket ( **}** )

I found out why it was not possible to click on the door icon, this was caused in the **function Door(item)** the onClick was set wrongly (twice, first cleared, second set to display the log)
Now It is indeed only switching OFF

I am quite sure you don't use the beta or the (default) development branch

**Comment by gizmocuz** [comment]
Fixed using

https://github.com/domoticz/domoticz/commit/d2630407eb96cf671d93381d1faea60165948a3b

Thanks for reporting
