### ISSUE TITLE
User access to devices (traefik reverse proxy)

### ISSUE THREAD

**Issue by dearekaelle** [domoticz/domoticz#5311]
Latest Domoticz Version: 2022.1 (build 14465)
running in a docker image domoticz/domoticz:latest 

Whenever I attempt changing user access to selected devices, it will always only pick one device and ignore all others.
I cannot give access to more than one device. 

I have multiple users that had their access configured in the past and these users have access to multiple devices as per their configuration and all works fine until when I attempt to update their access, it will reset whatever they had configured to just one device!

I have tried multiple browsers - chrome, firefox, clearing cookies, incognito.. etc.. it does behave the same every single time. 

I attempted multiple previous domoticz builds, going as far as 3 months back.. and it is the same.. so I assume something must be wrong with my database..

**Comment by dearekaelle** [comment]
update, have just found some inconsistency.

domoticz is running behind traefik reverse proxy that does ssl termination.. traefik however connects on the backend network over plain http.. 

when I expose the direct web port to the host and connect to that port directly.. I can edit all user permissions and they are all fine and preserved!!! 

whenever I do it through https handled traefik session, I have this problem with user permissions again.. 

having used that for quite some years I never encountered this issue with any other domoticz web settings.. 

some weird UI issue!

**Comment by gizmocuz** [comment]
Best to check your proxy settings…. Should be no difference in handling in domoticz

**Comment by dearekaelle** [comment]
@gizmocuz thanks, it's not the settings though.. 

to whom it might be useful, I have just confirmed that the issue was introduced in traefik v2.7.2; going back to v2.7.1 resolves this compatibility issue for domoticz.

**Comment by dearekaelle** [comment]
I have just found that the bug being a root cause that is affecting domoticz is already documented on traefik's github. 

[https://github.com/traefik/traefik/issues/9164](https://github.com/traefik/traefik/issues/9164)

and indeed, whenever I am updating my user permissions, the device id arguments are being passed with ';'
in my case:

`Request URL: https://domoticz.dworznik.be/json.htm?type=setshareduserdevices&idx=3&devices=492;830;681;62`

but traefik is replacing ';' with '&' and breaking the app.

however according to traefik dev's and this link 

> "it became illegal to use ; as a separator"

[https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#url-encoded-form-data](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#url-encoded-form-data)

I am gonna reference this in traefik's issue; but it might be worthwhile reviewing this code

**Comment by gizmocuz** [comment]
@dearekaelle , we are not using a semicolon ( ; ) as separator for HTML fields, this is of course a & sign.
We are using a semicolon **in** our data field/variable which is perfectly legal

**Comment by dearekaelle** [comment]
@gizmocuz thanks and yes, I get that.. however a pointed out in [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) such delimiter should have been percent-encoded in the URI.

**Comment by kiddigital** [comment]
looking at the code of the `UserController.js`:
```
...
		SaveUserDevices = function () {
			var selecteddevices = $("#usercontent .multiselect option:selected").map(function () { return this.value }).get().join(";");
			$.ajax({
				url: "json.htm?type=setshareduserdevices&idx=" + $.devIdx + "&devices=" + selecteddevices,
...
```

The `selectedDevices` variable should be UrlEncoded before adding it to the URL. That way it is compliant with the mentioned RFC.

**Comment by kiddigital** [comment]
I think using the `encodeURIComponent` function will solve it:
```
url: "json.htm?type=setshareduserdevices&idx=" + $.devIdx + "&devices=" + encodeURIComponent(selecteddevices),
```

**Comment by dearekaelle** [comment]
@kiddigital many thanks, that change indeed properly escapes the ';' delimeter.. and my URI looks good. 
the URL passes the new traefik without breaking the app.

`Request URL: https://domoticz.dworznik.be/json.htm?type=setshareduserdevices&idx=3&devices=742%3B830%3B489%3B681%3B729%3B735%3B455%3B666`

Not sure if such a change would be needed elsewhere in the code where the same syntax is used though!

**Comment by kiddigital** [comment]
@dearekaelle , great. And is the list of devices also properly process and stored by the backend?

Sorry, lacking the time to test it myself atm but if it works fine also from the backend perspective, I can create a small PR for this. But also feel free to create the PR yourself of course :) Always happy to see new contributers!

**Comment by dearekaelle** [comment]
@kiddigital yes, all the list is processed and stored properly. as far as I am concerned this is fixed. 
many thanks ;)
