### ISSUE TITLE
SolarEdge API stopped working

### ISSUE THREAD

**Issue by motor4all** [domoticz/domoticz#5314]
Hi,
After upgrading (or at least that seems to be the trigger) this morning the API stopped working.
With Domoticz in Debug mode the only thing I can find: worker started, but no data is pulled in.
Disabling the current hardware and adding new hardware with the same API key does not give an error, but also no devices are found or created.
I see some network traffic (tcpdump) to monitoringapi.solaredge.com when I change the hardware (and the log shows: worked stopped, worker started) 
When entering an invalid API key also no error is raised.
When I use the urls from the cpp file and paste in my API key and siteID they all get a nice result back.
I am running out of ideas

**Comment by gizmocuz** [comment]
When you created this issue, there where guidelines, one of them was to state your domoticz version

Best to use the forum... Anyway checked with the latest beta version (14474) it's still working correct

![image](https://user-images.githubusercontent.com/2265299/186866131-7973774a-5025-4ac3-a178-ad7747c2f14c.png)
