### ISSUE TITLE
With the last update can't dimto 100% in Dzvents

### ISSUE THREAD

**Issue by arjanvanleent** [domoticz/domoticz#5315]
Running build 144741
Use zwavejstomqtt last version

If I use:
domoticz.devices('Ventilator 0-100%').dimTo(100)

The fans turn on when they where off to the last know possition and when the fans are already running then nothing is happening.

Workaround: domoticz.devices('Ventilator 0-100%').dimTo(99) this works well for now

**Comment by gizmocuz** [comment]
Could you try beta 14474, made some changes that should resolve this

**Comment by arjanvanleent** [comment]
It's working correct now.

**Comment by gizmocuz** [comment]
Perfect thanks for the feedback!
