### ISSUE TITLE
It is not possible to control a security device directly from a FloorPlan

### ISSUE THREAD

**Issue by mealgi** [domoticz/domoticz#5317]
Context :
Version: 2022.1 (build 14338)
Build Hash: https://github.com/domoticz/domoticz/commit/8d73c42d608456448eee4c523173d83c82f094ac-modified
Compile Date: 2022-05-15 19:47:20
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

Issue : It is not possible to control a security device directly from a floorplan. It behaves as a plain switch (on/off) instead of displaying the security panel to proceed to arm home, arm away or disarm

Proposed Solution :

create a new SecurityPanel device in domoticzdevices.js
in domoticzdevices line 981 add:
        case "security": 
            dev = new SecurityPanel(item);
            break;

in domoticzdevices line 1236 add:
function SecurityPanel(item) {
    if (arguments.length != 0) {
        this.parent.constructor(item);
        this.image =  "images/" + item.TypeImg + "48.png";
        this.LogLink = "window.location.href = '#/Devices/" + this.index + "/Log'";
        this.onClick = "window.location.href = 'secpanel/'";
        this.data = '';
        this.smallStatus = this.status;
    }
}
SecurityPanel.inheritsFrom(BinarySensor);

BR

**Comment by gizmocuz** [comment]
@mealgi , thank you for your suggestion. The security panel has it's own page and it should not be allowed to use it as a on/off switch
