### ISSUE TITLE
Multi state switch on/off delays not saving

### ISSUE THREAD

**Issue by cherowley** [domoticz/domoticz#532]
When save is clicked after entering a number in either the on delay of off delay boxes the values are NOT saved.

**Comment by gizmocuz** [comment]
i do not understand... should this not happen ?

**Comment by cherowley** [comment]
Woops! I mean they are NOT saved. It's a blooming shame as the new selector switch is rather nice and makes for a great tidy interface :)

**Comment by gaudryc** [comment]
Sorry for the inconvenient, it will be fixed very soon.

**Comment by cherowley** [comment]
Brilliant! Cheers :)
