### ISSUE TITLE
[BUG] EnergyUsage should be double, not float

### ISSUE THREAD

**Issue by Francis-perso** [domoticz/domoticz#5326]
I suspected a problem with lower values in power usage, but I've also seen a bug during the process.

In SQLHelper.cpp, line 5073 to 5076, all the values are in float, but energyUpToInterval and energyAfterInterval can become big (these are Wh).
I guess I'm not the only one with a value > 10000.000 kWh for a house.

float -> 4 bytes, precision is 7 digits
double -> 8 bytes, precision is 15 digits

For my case, with an Energy counter at 18228934.000 kWh, adding less than 2 Wh in float in 5 seconds means 1400 W ! (2 * 3600/5).

I was questionning why my results from my clamps are more and more different than my "real" bill from my provider, I have found why :-)

**Comment by gizmocuz** [comment]
@Francis-perso , thanks for reporting. Yes using doubles here would make it more precise, have you tested with your change ?
Is the final sValue precise enough when using %.1f ?

**Comment by Francis-perso** [comment]
Hi @gizmocuz, I've compiled my mods just changing to double (with changing the cast also, of cours) :

double powerDuringInterval = static_cast<double>(atof(powerAndEnergyBeforeUpdate[0].c_str()));
double energyUpToInterval = static_cast<double>(atof(powerAndEnergyBeforeUpdate[1].c_str()));
double energyDuringInterval = static_cast<double>(powerDuringInterval * intervalSeconds / 3600);
double energyAfterInterval = static_cast<double>(energyUpToInterval + energyDuringInterval);

and as I said in forums, sValue with %.1f is to restrictive, because with clamps measuring every 5 seconds, we miss everything under 30W, it's to high.

My version is %.4f, and with that, I can track 0.07 W (minimum value to track 100 mW).

sprintf(sValueUpdate, "%s;%.4f", powerUpdate, energyAfterInterval);

It works like a charm :-)

Thanks !

**Comment by gizmocuz** [comment]
I dont know anything about forum because there is no refference to your forum post 😀

But if you want to track 0.07W I guess %.2f or %.3f would be fine as well ?

I made a patch (with %.3f) and hope all works out for you in beta 14491

**Comment by Francis-perso** [comment]
My bad for the forums :-)

https://www.domoticz.com/forum/viewtopic.php?p=292107#p292107
https://www.domoticz.com/forum/viewtopic.php?p=292185#p292185
https://www.domoticz.com/forum/viewtopic.php?p=292208#p292208 (-> wrong place, should be in bugs ...)
or in french :
https://easydomoticz.com/forum/viewtopic.php?f=8&t=12518

Tracking 0.07W during 5 seconds means 0.07 * 5 / 3600 = 0.0001 Wh, and it's that value which is stored in sValue.

double powerDuringInterval = static_cast<double>(atof(powerAndEnergyBeforeUpdate[0].c_str()));
-> powerDuringInterval = 0.07 (W)

[...]
double energyDuringInterval = static_cast<double>(powerDuringInterval * intervalSeconds / 3600);
energyDuringInterval = 0.07 * 5 / 3600 = 0.0001 (Wh)

[...]
double energyAfterInterval = static_cast<double>(energyUpToInterval + energyDuringInterval);
-> here is the need to have double if energyUpToInterval is more than 5 digits ;-)

[...]
sprintf(sValueUpdate, "%s;%.4f", powerUpdate, energyAfterInterval);
-> if I want to get my 0.0001 Wh, I need %.4f

Thanks.

**Comment by gizmocuz** [comment]
Okey in beta 14492 it is %.4 , 0.0001 Wh is ridiculously low 👌

**Comment by Francis-perso** [comment]
Thanks !

**Comment by gizmocuz** [comment]
When all is working OK, is it possible you could update the forum topics as well ? Thanks

**Comment by Francis-perso** [comment]
Done !
