### ISSUE TITLE
Missing blind+stop device

### ISSUE THREAD

**Issue by ab10002** [domoticz/domoticz#5327]
In this swtype list, blind+stop(=with percentage!) is missing.
```
#SubType Name 	
#0  	On/Off 	
#1  	Doorbell 	
#2  	Contact 	
#3  	Blinds 	
#4  	X10 Siren 	
#5  	Smoke Detector 	
#6  	Blinds Inverted 	
#7  	Dimmer 	
#8  	Motion Sensor
#9  	Push On Button 	
#10 	Push Off Button 	
#11 	Door Contact 
#12 	Dusk Sensor 	
#13 	Blinds Percentage 
#14 	Venetian Blinds US 	
#15 	Venetian Blinds EU 	
#16 	Blinds Percentage Inverted 	
#17 	Media Player 	
#18 	Selector 	
#19 	Door Lock 	
#20 	Door Lock Inverted

```
Can this be added, ex. 21 Blind+stop ?

**Comment by gizmocuz** [comment]
Where is this ? You are running the beta version I hope ? If I edit a switch I can change it's type to blinds+stop

**Comment by ab10002** [comment]
yep, in the 14490..

**Comment by gizmocuz** [comment]
@ab10002 , I do not understand your issue, Where do you not see blinds+stop ? It should be there, did you tried adding a dummy switch and change it's type ?

**Comment by ab10002** [comment]
From out the Somfy plugin, adding a new sensor:
`                if (device["deviceURL"].startswith("io://")):
                    if (device["uiClass"] == "Awning"):
                        swtype = 13
                    else:
                        swtype = 16
                elif (device["deviceURL"].startswith("rts://")):
                    swtype = 6

                Domoticz.Device(Name=device["label"], Unit=count, Type=244, Subtype=73, Switchtype=swtype, DeviceID=device["deviceURL"]).Create()
`
I want to add a blind+stop(=with percentage) device. But that one is not in the list:
#SubType Name 	
#0  	On/Off 	
#1  	Doorbell 	
#2  	Contact 	
#3  	Blinds 	
#4  	X10 Siren 	
#5  	Smoke Detector 	
#6  	Blinds Inverted 	
#7  	Dimmer 	
#8  	Motion Sensor
#9  	Push On Button 	
#10 	Push Off Button 	
#11 	Door Contact 
#12 	Dusk Sensor 	
#13 	Blinds Percentage 
#14 	Venetian Blinds US 	
#15 	Venetian Blinds EU 	
#16 	Blinds Percentage Inverted 	
#17 	Media Player 	
#18 	Selector 	
#19 	Door Lock 	
#20 	Door Lock Inverted

**Comment by gizmocuz** [comment]
I updated the wiki, but this could be found in the source code of course

https://www.domoticz.com/wiki/Developing_a_Python_plugin

https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s
