### ISSUE TITLE
Slider to 100% when on

### ISSUE THREAD

**Issue by vespino** [domoticz/domoticz#5329]
Version: 2022.1 (build 14492)
Platform: Docker
Plugin/Hardware: Synology
Description: I have a virtual switch controlling the volume of my Sonos speakers. When it’s off and I turn it on the percentage is turned to 100% which is a bit loud as you can imagine 🤣

**Comment by gizmocuz** [comment]
@vespino , I think this is a GUI issue.... internally the level is still set to your last level.
How are you using this dummy ? Do you have a script? Does this script look for the level ?

**Comment by gizmocuz** [comment]
Thanks for reporting, found the root cause and it should be fixed in beta 14495
