### ISSUE TITLE
How to fix a value in comparing usage chart

### ISSUE THREAD

**Issue by Vianneyminixx** [domoticz/domoticz#5332]
Hello,
I encounter an anomaly on the chart comparing usage.
As can be seen in the chart below:

![2022-09-05 19_31_02-Domoticz](https://user-images.githubusercontent.com/112896194/188496682-9e51993e-74c2-49e4-9376-08cd5953d2ed.png)

I have already tried clearing the browser cache.
The domoticz version is 2022.1 / Compile Date: 2022-01-31 09:34:32

The query select * from Meter_Calendar where DeviceRowID=6 order by Date desc

|DeviceRowID|Value    |Counter      |Date            |
|-------------|--------|-------------|-------------|
|6                  |13 745 |16 525 959 |2022-08-28 |
|6                  |0          |0                 |2022-08-27 |
|6                  |13 966 |16 512 215 |2022-08-27 |

I removed the duplicate line from 2022-08-27 like this

|DeviceRowID|Value    |Counter      |Date            |
|-------------|--------|-------------|-------------|
|6                  |13 745 |16 525 959 |2022-08-28 |
|6                  |13 966 |16 512 215 |2022-08-27 |

Is it a calculated value, or is it a value that I can fix in the database?

Despite this correction, the anomaly is still present. How to do ?

Thanks in advance.
Cordially.

[Meter_Calendar_202209051951_Before.txt](https://github.com/domoticz/domoticz/files/9491546/Meter_Calendar_202209051951_Before.txt)
[Meter_Calendar_202209051951_after.txt](https://github.com/domoticz/domoticz/files/9491547/Meter_Calendar_202209051951_after.txt)

**Comment by gizmocuz** [comment]
You should be able to see this value on your year chart.... first make a database backup from the settings page, then shift-click on this value in the year chart to remove it
Another way is to delete it straight from the database

**Comment by Vianneyminixx** [comment]
Hello,
I don't want to delete it, but modify it.
Can the value 16,960.39 kWh be modified directly in the database or is it calculated?
Thanks.

**Comment by gizmocuz** [comment]
It is calculated from the meter value
Just delete it or change the 0 to the previous value

**Comment by Vianneyminixx** [comment]
Fixed, thank you very much for your help.
