### ISSUE TITLE
[Feature Request] Device rename force from ZwaveJS2MQTT HA Autodiscovery

### ISSUE THREAD

**Issue by Rouzax** [domoticz/domoticz#5342]
It would be nice if we could force a rename of the devices in Domoticz from ZwaveJS2MQTT.
In ZwaveJS there is an option to `Rediscover Node` 
![image](https://user-images.githubusercontent.com/4103090/191490885-62bc1747-1d2a-4af5-9d76-d46599ce0172.png)

This forces all attributes to be resent to Domoticz/Home Assistant, including any new name or location that was set.

Based on the Device ID Domoticz should be capable to pick up these topics and renamed attributes and rename them in Domoticz

**Comment by gizmocuz** [comment]
Can't do this as maybe you already gave it a good name and then this will be overwritten....
But for that single device it is not so difficult to rename it by hand?

**Comment by Rouzax** [comment]
My idea would be that it is an option you could enable in the MQTT discover that would sync device naming based on ZwaveJS. When enabled, it would always rename based on received payloads.

For a single device it is not that hard, but I recently needed to rename all my nodes (50-ish) and then times 3 or 4 with all the individual devices from those nodes.

PS did you see this? https://github.com/zwave-js/node-zwave-js/issues/5095#issuecomment-1254841161
