### ISSUE TITLE
Inverted Blinds - lastLevel not correct for Open/CLose

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#5345]
Domoticz build 14498 on Ubuntu Focal

After testing again all the latest changes related to the Blinds Inverted [(Issue 5288)](https://github.com/domoticz/domoticz/issues/5288), I confirm that it works now with the iOS Home App and its default values (Open=0 and Closed=100).

However I think I found a bug related to the value of the **lastLevel** in dzVents when using Blinds Inverted.
The value of **lastLevel** works correctly for intermediate values (1 to 99) but is not set correctly for 0 and 100 (Open and Closed).

I created a device TEST-BLIND with type **Blinds Percentage Inverted**
I created a dzvents script triggered by this device which displays the **lastLeve**l and **level**.

Here are the results of the tests using the Open / Close buttons and the slider of the TEST-BLIND in the Domoticz GUI:

Click on the **Open** button
`2022-09-27 10:28:36.431 Status: dzVents: Debug: Volets: TEST-BLIND lastLevel = 100`
`2022-09-27 10:28:36.431 Status: dzVents: Debug: Volets: TEST-BLIND level = 0`

Click on the **Open** button
`2022-09-27 10:28:41.501 Status: dzVents: Debug: Volets: TEST-BLIND lastLevel = 100`
`2022-09-27 10:28:41.501 Status: dzVents: Debug: Volets: TEST-BLIND level = 0`

Click on the **Open** button
`2022-09-27 10:28:46.450 Status: dzVents: Debug: Volets: TEST-BLIND lastLevel = 100`
`2022-09-27 10:28:46.451 Status: dzVents: Debug: Volets: TEST-BLIND level = 0`

Move the Slider to 25%
`2022-09-27 10:28:58.867 Status: dzVents: Debug: Volets: TEST-BLIND lastLevel = 100`
`2022-09-27 10:28:58.867 Status: dzVents: Debug: Volets: TEST-BLIND level = 25`

Move the **Slider to 50%**
`2022-09-27 10:29:21.219 Status: dzVents: Debug: Volets: TEST-BLIND lastLevel = 25`
`2022-09-27 10:29:21.219 Status: dzVents: Debug: Volets: TEST-BLIND level = 50`

Move the **Slider to 75%**
`2022-09-27 10:29:29.311 Status: dzVents: Debug: Volets: TEST-BLIND lastLevel = 50`
`2022-09-27 10:29:29.311 Status: dzVents: Debug: Volets: TEST-BLIND level = 75`

Move the **Slider to 100%**
`2022-09-27 10:29:33.347 Status: dzVents: Debug: Volets: TEST-BLIND lastLevel = 75`
`2022-09-27 10:29:33.347 Status: dzVents: Debug: Volets: TEST-BLIND level = 100`

Move the **Slider to 0%**
`2022-09-27 10:29:38.144 Status: dzVents: Debug: Volets: TEST-BLIND lastLevel = 0`
`2022-09-27 10:29:38.144 Status: dzVents: Debug: Volets: TEST-BLIND level = 100`

Click on the **Close** button
`2022-09-27 10:29:48.347 Status: dzVents: Debug: Volets: TEST-BLIND lastLevel = 0`
`2022-09-27 10:29:48.347 Status: dzVents: Debug: Volets: TEST-BLIND level = 100`

Click on the **Close** button
`2022-09-27 10:29:52.019 Status: dzVents: Debug: Volets: TEST-BLIND lastLevel = 0`
`2022-09-27 10:29:52.019 Status: dzVents: Debug: Volets: TEST-BLIND level = 100`

Click on the **Close** button
`2022-09-27 10:29:55.238 Status: dzVents: Debug: Volets: TEST-BLIND lastLevel = 0`
`2022-09-27 10:29:55.238 Status: dzVents: Debug: Volets: TEST-BLIND level = 100`

When pushing the Open button, the new position (level) is set to 0, which is correct.
However when moving the blind to another position, the **lastLevel** value does not reflect the last position (0). Instead it shows 100 (Closed).
However **lastLevel** is correct for positions between 1 and 99.
I guess it is not taking into account the 'Inverted' positions for Open/Closed and uses the regular (non-inverted) values.

I hope this can be corrected as I'm using hte lastLevel and level values in a script to calculate how much the Blind should move (I'm using SOMFY RFY Blinds and emulate a Percentage Blind using a dzVetns script).

**Comment by gizmocuz** [comment]
Found the issue (or actually where to solve this) and this should be solved in beta 14519
Is it possible to verify this? (I tested with both normal/inverted blinds)

**Comment by Olivier6767** [comment]
I tested with normal and inverted blinds and can confirm it works as expected.
Thanks.
