### ISSUE TITLE
Zwave-JS-UI - General, kWh not showing Power Usage anymore

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#5346]
Domoticz build 14498 on Ubuntu Focal

I'm using ZwaveJS2MQTT with Domoticz.
I have several wall plugs that measure power consumption.

This weekend I 'upgraded' to the latest release and new name of Zwave-JS-UI and I also triggered a re-interview of all the nodes.
Since the device IDs contained the prefix **Zwavejs2mqtt**, I had to rename them to **zwave-js-ui** in the domoticz database.

I noticed that my devices (type General, kWh) are not displaying the power usage any more. Thza value is always 0.
I know in Domoticz this was possible by combining the values of 2 zwave counters (consumption and power) into 1 Domoticz device.
I suspect the name of the counters have slightly changed, which could explain why it is not working any more.

Here are the screenshots of the current counter IDs.
It looks like the counter 6-50-0-value-66049 is not updated anymore, need to use the 6-49-0-Power.

Is it possible to adjust it so it combines the 2 values again?

![device](https://user-images.githubusercontent.com/28684355/192484108-2745c802-5710-47fc-a3d7-a1a90bd4ab15.png)

![graph](https://user-images.githubusercontent.com/28684355/192483654-5ec49ce4-47b7-489f-8b69-cc4176813da8.png)

![zwavejsui](https://user-images.githubusercontent.com/28684355/192483672-c9ebfe81-473f-4a0b-bab6-b4d9b8e941ed.png)

![devices](https://user-images.githubusercontent.com/28684355/192483626-e2fe1302-cd23-49ce-88ff-d09b28c67158.png)

**Comment by gizmocuz** [comment]
Could you post the config topic/payload as well as the payload when the watt/kwh is received ?

**Comment by gizmocuz** [comment]
Not sure why you had to rename Zwavejs2mqtt to zwave-js-ui ... it should have been backwards compatible, but you should also not perform this action in the database.... best to not edit anything in the database at all
I assume you made a backup and can revert to this backup
In zwavejs you can set the MQTT topic, if this somehow changed during upgrade to 'zwave-js-ui', try to set it back to 'Zwavejs2mqtt'
I must assume that when updating zwavejs they made it backwards compatible
Also the re-interview was not needed... just updating zwavejs and you should have been good to go

If things are totally messed up now maybe best to make a backup of the database, delete the MQTT-AD hardware and add it again so all devices are working correctly again

**Comment by gizmocuz** [comment]
I have just upgraded one of my systems myself with
docker-compose pull
docker-compose down
docker-compose up

and all kept working correctly, did not need to change anything, also kWh/Watt are updating fine
I guess your issue if caused by modifying the database directly. But I would have assumed you got some new devices

**Comment by Olivier6767** [comment]
The change they made was on the unique ID, not the prefix (which you can set in the control panel).
In the meantime, they reverted this change (went back to using zwavejs2mqtt) but added a environment variable to be able to customize it ([UID_DISCOVERY_PREFIX]).
(https://github.com/zwave-js/zwave-js-ui/commit/93c16af9f2ed6413d1ee11c6ed40f16cdbf31d0c)
[](https://github.com/zwave-js/zwave-js-ui/commit/2fc3850ed9f4edd4ae64563ce18af16693303e85)

I did make a backup of the database...

I tried restoring the backup and use the old UID_DISCOVERY_PREFIX, but the power value still does not show up for these wall plugs.


Here are the config topics and paylods:

**electricity_power**
`
zwave-ad/sensor/Info_Wall_Plug/electricity_power/config
{
  "value_template": "{{ value_json.value }}",
  "device_class": "power",
  "unit_of_measurement": "W",
  "state_topic": "zwave/5/49/0/Power",
  "json_attributes_topic": "zwave/5/49/0/Power",
  "device": {
    "identifiers": [
      "zwave-js-ui_0xfdd95a35_node5"
    ],
    "manufacturer": "Fibargroup",
    "model": "Metered Wall Plug Switch (FGWPE/F-101)",
    "name": "Info Wall Plug",
    "sw_version": "24.24"
  },
  "name": "Info Wall Plug_electricity_power",
  "unique_id": "zwave-js-ui_0xfdd95a35_5-49-0-Power"
}
`
Payload:
`
{"time":1664707900141,"value":242.9,"nodeName":"Info Wall Plug","nodeLocation":"Cave"}
`

**electricity_kwh**
`
zwave-ad/sensor/Info_Wall_Plug/electricity_kwh_value/config
{
  "value_template": "{{ value_json.value }}",
  "device_class": "power",
  "unit_of_measurement": "kWh",
  "state_topic": "zwave/5/50/0/value/65537",
  "json_attributes_topic": "zwave/5/50/0/value/65537",
  "device": {
    "identifiers": [
      "zwave-js-ui_0xfdd95a35_node5"
    ],
    "manufacturer": "Fibargroup",
    "model": "Metered Wall Plug Switch (FGWPE/F-101)",
    "name": "Info Wall Plug",
    "sw_version": "24.24"
  },
  "name": "Info Wall Plug_electric_kwh_value",
  "unique_id": "zwave-js-ui_0xfdd95a35_5-50-0-value-65537"
}
`
Payload:
`
{"time":1664707961209,"value":15705.78,"nodeName":"Info Wall Plug","nodeLocation":"Cave"}
`

**electric_w_value**
`
zwave-ad/sensor/Info_Wall_Plug/electric_w_value/config
{
  "value_template": "{{ value_json.value }}",
  "device_class": "power",
  "unit_of_measurement": "W",
  "state_topic": "zwave/5/50/0/value/66049",
  "json_attributes_topic": "zwave/5/50/0/value/66049",
  "device": {
    "identifiers": [
      "zwave-js-ui_0xfdd95a35_node5"
    ],
    "manufacturer": "Fibargroup",
    "model": "Metered Wall Plug Switch (FGWPE/F-101)",
    "name": "Info Wall Plug",
    "sw_version": "24.24"
  },
  "name": "Info Wall Plug_electric_w_value",
  "unique_id": "zwave-js-ui_0xfdd95a35_5-50-0-value-66049"
}
`
Payload:
`
{"time":1664707639949,"value":236.6,"nodeName":"Info Wall Plug","nodeLocation":"Cave"}
`

**switch**
`
zwave-ad/switch/Info_Wall_Plug/switch/config
{
  "payload_off": false,
  "payload_on": true,
  "value_template": "{{ value_json.value }}",
  "command_topic": "zwave/5/37/0/targetValue/set",
  "state_topic": "zwave/5/37/0/currentValue",
  "device": {
    "identifiers": [
      "zwave-js-ui_0xfdd95a35_node5"
    ],
    "manufacturer": "Fibargroup",
    "model": "Metered Wall Plug Switch (FGWPE/F-101)",
    "name": "Info Wall Plug",
    "sw_version": "24.24"
  },
  "name": "Info Wall Plug_switch",
  "unique_id": "zwave-js-ui_0xfdd95a35_5-37-0-currentValue"
}
`
Payload:
`
{"time":1664707639946,"value":true,"nodeName":"Info Wall Plug","nodeLocation":"Cave"}
`

**Comment by Olivier6767** [comment]
The topic `electric_w_value` is only updated once when starting zwave-js-ui or forcing a config push (auto discovery). It is not updated regularly.
It seems like this is the topic used as the power value in Domoticz for this type of device (FIBARO FGWPE/F-101).

The topic which is updated regularly is `electricity_power`.
Would it be possible to use this one instead?

**Comment by gizmocuz** [comment]
The problem was caused by the syntax of the new unique id, not only the prefix.
The electricity_power is used
Please try beta 14529, this should solve the problem (also when using the new prefix)

**Comment by Olivier6767** [comment]
Just tried to update to the latest beta (precompiled - Linux x64) which mentions version 14532, but when running it the Web UI mentions release 14525...
Is there an issue with the compiled releases version naming?

Since this is prior to the release you mention for the fix (14529), it does not correct the issue with the power counter.
I'll wait for a newer compiled release to test.

**Comment by gizmocuz** [comment]
The latest version at the moment is 14532, the web interface should say the same version, maybe you run two instances ?

**Comment by Olivier6767** [comment]
The issue was on my end.
I'm now running 14532 and the issue with the power counter is fixed.
Thanks!

**Comment by gizmocuz** [comment]
> The issue was on my end. I'm now running 14532 and the issue with the power counter is fixed. Thanks!

I know😂🤣 Great it's working and thanks for the feedback as always !
