### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by chaudron** [domoticz/domoticz#5348]
I was wondering if there is a known memory leak, or if there is an easy way to troubleshoot one with Domoticz.

I'm running domoticz in a docker container and it starts eating memory, after about 18 hours it's at 3.5G and keeps increasing.

```
Version: 2022.1 (build 14512)
Build Hash: 2c16b425c-modified
Compile Date: 2022-09-18 23:02:25
dzVents Version: 3.1.8
Python Version: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
```

Let me know how I can debug this. Nothing odd in the logs, and I did not make any config changes recently.

**Comment by kiddigital** [comment]
Add the _motherboard sensor_ hardware module.

It has a _process memory_ sensor measuring the amount of memory the Domoticz process consumes.

After a while, you could see a graph of it.

Also, disabling Python plugins should be tested as it a known source for memory issues.

Good luck testing.

**Comment by waltervl** [comment]
Especially python scripts (not plugins) suffer from memory leaks
https://github.com/domoticz/domoticz/issues/5091
In some case also plugins: https://github.com/domoticz/domoticz/issues/5234

And I believe on docker there seems to be an extra memory issue but I cannot find it.

**Comment by chaudron** [comment]
Added the graph, will get some stats over the next day. The only python stuff I have running is this #5339. Will try to disable it, and get some more graphs.

**Comment by waltervl** [comment]
For docker see also forum topic https://www.domoticz.com/forum/viewtopic.php?p=279399

**Comment by chaudron** [comment]
So it looks like it's Python related. When installing the memory plugin, I can see my system memory grow over time. However if I disable the script mentioned in https://github.com/domoticz/domoticz/issues/5339, which is the only script I have. Memory usage stays stable.

I'll try adding another simpler device trigger script to see if it increments memory.

Any other things to try, or will this be enough information to further investigate?

**Comment by gizmocuz** [comment]
There is already a issue regarding python and memory problems, please continue there
