### ISSUE TITLE
blind issue in 14498: button commands do not correspond to correct nvalue

### ISSUE THREAD

**Issue by megamarco833** [domoticz/domoticz#5349]
hi, i'm on domoticz beta version 14498
i notice that compared to my previous version now there is an issue with blind (dummy device) set as "normal blind"
![immagine](https://user-images.githubusercontent.com/44502572/193010103-e40353ee-f942-4f7a-8e8c-16113b891788.png)
![immagine](https://user-images.githubusercontent.com/44502572/193010452-e562a65a-b2e7-417e-89b5-18896cd69db0.png)
 
if i use a command like:
`domoticz/in {"svalue": "", "idx": 317, "nvalue": 1 }`
i see that the icon is set to close and my shutter goes down

if i use command:
`domoticz/in {"svalue": "", "idx": 317, "nvalue": 0}`
i see that the icon is set to open and my shutter goes UP

now if i click on the button icons in domoticz, if i click on OPEN
i see as message on domoticz/out
`{ "Battery" : 255, "LastUpdate" : "2022-09-29 12:43:57", "RSSI" : 12, "description" : "", "dtype" : "Light/Switch", "hwid" : "6", "id" : "0001418D", "idx" : 317, "name" : "tapparella portafinestra cucina", "nvalue" : 1, "stype" : "Switch", "svalue1" : "100", "switchType" : "Blinds", "unit" : 1 }`

so nvalue is 1 !!! why!?!? it should be 0 (and in fact my blinds are moving wrongly because i click open and my blind is getting closing)

now if i click on the button icons in domoticz, if i click on CLOSE
i see as message on domoticz/out
`{ "Battery" : 255, "LastUpdate" : "2022-09-29 12:43:57", "RSSI" : 12, "description" : "", "dtype" : "Light/Switch", "hwid" : "6", "id" : "0001418D", "idx" : 317, "name" : "tapparella portafinestra cucina", "nvalue" : 0, "stype" : "Switch", "svalue1" : "100", "switchType" : "Blinds", "unit" : 1 }`
so nvalue is 0 !!! why!?!? it should be 1 (and in fact my blinds are moving wrongly because i click close and my blind is getting open)

**Comment by gizmocuz** [comment]
Just to be sure, you are not using MQTT Auto Discovery ? Just regular blinds ?

**Comment by megamarco833** [comment]
> Just to be sure, you are not using MQTT Auto Discovery ? Just regular blinds ?

yes, correct, for these device i'm using"regular" dummy devices (you can look at my first image where there is "type: light/switch, blinds)

**Comment by gizmocuz** [comment]
I am trying to replicate this with the latest beta version

Added a 'normal' blind (also tried with blinds+stop and blinds percentage) when I click the Open icon (left icon) I receive

"nvalue": 0

When I click the Close icon (right icon) I receive

"nvalue": 1

This seems perfectly fine

**Comment by megamarco833** [comment]
ehmm with normal blind (dummy device) if i click on the button icons in domoticz, if i click on OPEN=UP (open is left icon)
i see as message on domoticz/out
`{ "Battery" : 255, "LastUpdate" : "2022-09-29 12:43:57", "RSSI" : 12, "description" : "", "dtype" : "Light/Switch", "hwid" : "6", "id" : "0001418D", "idx" : 317, "name" : "tapparella portafinestra cucina", "nvalue" : 1, "stype" : "Switch", "svalue1" : "100", "switchType" : "Blinds", "unit" : 1 }`
so "nvalue":1

now if i use a command like:
`domoticz/in {"svalue": "", "idx": 317, "navlue": 1 `}
i see that my shutter goes down=close (i expect that my blind will go up=OPEN  like in the command above were i clicked on left icon)

**Comment by gizmocuz** [comment]
Made a small typo in my previous comment, Open=Left button = nvalue=0, Close=Right button = nvalue =1
If you do not have this behavior, please try to start a clean domoticz system, and use MQTT explorer to watch the value

**Comment by gizmocuz** [comment]
Also make sure nothing is connected to the broker except Domoticz when testing

**Comment by megamarco833** [comment]
ok, i'll for sure double check it.
but just a clarification needed from my side:
with NORMAL BLIND inside the dummy device setting we have:
"on action" and "off action".
to me the "ON action" is when we OPEN=UP the blind 
and "OFF action" is the command to send when we CLOSE=DOWN the blind
is it correct?

**Comment by gizmocuz** [comment]
On action is for close, Off action for open
On action is executed when the blind is closed

**Comment by megamarco833** [comment]
ok maybe we identify the first part of the issue:
it seams that domoticz is working opposite like the "normal logic" and so also opposite than HomaAssistant, Tasmota etc...

i try to summarize this concept above.
accordingly to "all other domotic systems" and also "normal logic" we have:
ON=OPEN=UP=nvalue1
and OFF=CLOSE=DOWN=navalue0
and this to me has a logic behind , because when you switch ON...the blind should open => the light will enter in your room => the blind go up (nvalue should be 1)
when you switch OFF a blind => the light became dark in the room=> the blind should close => so going down and nvalue should be 0
Again, HA, tasmota works also with same logic descrived above...and so also MQTT autodiscovery had the same corect logic.
Also with percentages HA, Tasmota works in this condition....if you have level = 90% it means that your blind is 90% OPEN 

on the opposite in DZ (and again only in domoticz, not Ha and Tasmota) we have
ON=CLOSE=DOWN=navalue1
and OFF=OPEN=UP=nvalue0

to me this:
**ON=OPEN=UP=nvalue1
and OFF=CLOSE=DOWN=navalue0**
 should be the right logic (that is the same logic of HA, Tasmota, ect...) 

to support that, i can also give to you an example with ALEXA.
alexa has an integration with domoticz (supported by official alhu applet www.alhau.com) 
for alexa switches or blind are the same.
so if you say to alexa: "Alexa turn ON kitchen blind " (there is not open/close command, blinds for alexa are switches so sh expects turn on/off commands)
alexa will set command ON,.....and i expect that my blind will be open (on my logic, but also in HA logic, tasmota logic)...but domoticz after say that sentence to Alexa, will close it!
to me **if i want to _OPEN_ my blind it's very very strange to have to say to alexa "turn _OFF_ kitchen blind"** ...!!!

so to me, we have to revert the base logic of the blind...maybe could be the reason behind many issue opening with blinds...
why we (domoticz) choose the opposite way of working than the others (HA,tasmota, alexa etc...)
to me the others are in the right and logic way of working... :-)
can we move to:
ON=OPEN (navalue1)
OFF=CLOSE (navalue0)

**Comment by gizmocuz** [comment]
Please update to the new beta version. When you now edit the switch/blind the labels will be set to either On/Off Action, or Close/Open action

**Comment by gizmocuz** [comment]
It does not matter how Domoticz operates but the Open action is triggered when you open the blinds and the Close action is triggered when you close the blinds
Open=Off=0, Close=On=1

This is how the logic works and has been since the beginning

**Comment by megamarco833** [comment]
> Please update to the new beta version. When you now edit the switch/blind the labels will be set to either On/Off Action, or Close/Open action

![immagine](https://user-images.githubusercontent.com/44502572/193766817-e292eab4-fb06-4767-acd0-417c54f35e65.png)

i did it but still show ON/OFF with blind...
i also try to change language from italian to english but still on/off and not show open/close

**Comment by gizmocuz** [comment]
Please clear your browser cache

**Comment by gizmocuz** [comment]
![image](https://user-images.githubusercontent.com/2265299/193767543-20b6d5dd-0f6a-426e-a82d-fbb0dcc6dbeb.png)

**Comment by megamarco833** [comment]
> It does not matter how Domoticz operates but the Open action is triggered when you open the blinds and the Close action is triggered when you close the blinds Open=Off=0, Close=On=1

i don't agree on that :-)
it's important how to operate domoticz and actually domoticz as you wrote operate with Open=Off=0, Close=On=1
and it means that if i want to open my blind i have to say to alexa: "alexa switch off the blind" ....no sense at all :)
i expect to say: "alexa switch on the blind"  if i want to open :) 
and again home assistant works in the opposite way of domoticz (with HA i say switch on to open the blind that is reasonable :) )


> This is how the logic works and has been since the beginning

i know but to me it doesn't mean that we can not have space to improve and/or be aligned with all the other domotic stuff like alexa, homeassistant, tasmota (both with MQTT AD)....etc... :-)

**Comment by megamarco833** [comment]
> Please clear your browser cache

sorry.
now works 👍

**Comment by gizmocuz** [comment]
Maybe you should say Alexa close the blinds, Alexa open the blinds instead.
You can use the inverted blinds that should invert the operation

**Comment by megamarco833** [comment]
no, alexa "doesn't know the blind" for alexa there are only switches that operates like a blind.
so you can say only on/off not open/close
where open=on (not off like only in domoticz)

using inverted option will revert open/close status in alexa also and it will be a mess

**why we can not think on re-write the logic of the blind and make it accordingly to all the other domotic stuff: home assistant, alexa, google, tasmota....**

can we think about that?

DZ:
Open=Off=0, Close=On=1

all the others:
Open=On=1 , Close=Off=0

note that navlue still be 1 for ON like today, it will be "just a metter" to have open=on
what fdo you think?

**Comment by gizmocuz** [comment]
https://theelectricblindcompany.co.uk/can-alexa-control-my-blinds/

**Comment by gizmocuz** [comment]
And you also might want to look at custom voice commands

**Comment by gizmocuz** [comment]
Seems to be an issue with non MQTT-AD blinds now... caused by another fix... MQTT-AD seems to work ok now

**Comment by megamarco833** [comment]
Rob sorry to get you bored...but i'll try again to show my view (that again, is the view of all other domotic system...and so also connected to MQTT-AD!!!)
if we deicide to re-write the logic of the blind, starting from scratch i think that will be beneficial also for the future.
i know that domoticz has this logic (that is different from all other stuff) and we can introduce a braking change...BUT i'm using domoticz since years and i see that we continue to introduce fix ...then another fix...then another revert back, than another fix :)
nothing against domoticz that is your baby, but to me if you decide to re-write the logic we can have much more compatibility with other domotic stuff and we will be accordingly to "global specs"

HA is working with percentage OPEN 
and Open=On=1 , Close=Off=0

MQTT-AD use same logic of HA

Google use the logic of HA
![immagine](https://user-images.githubusercontent.com/44502572/193818908-f9daae7f-fa71-4cf9-87ad-a7262f392e6a.png)

Alexa is using the same logic of HA
Tasmota is using same logic of HA (percentage is for OPEN and OPEN=ON=1)

our nValue = 1 is already = ON....so we need "just" to set ON = OPEN = 1 = Nvalue1
what do you think??
 :-)

**Comment by gizmocuz** [comment]
There have already been tons of work recently related to blinds (MQTT side) which is indeed more in line with the rest.
There are also many different types of blinds for all kinds of hardware (for example RFY)

I don't think anyone is using the logic of HA, but that HA is compatible like the others

Next to this Domoticz also has a 'inverted' blind (I never understood why people needed this) and I think this can be dropped

I am open for suggestions, are you able to make a PR? But be sure that it won't break existing logic for MQTT-AD

**Comment by megamarco833** [comment]
> There have already been tons of work recently related to blinds (MQTT side) which is indeed more in line with the rest. There are also many different types of blinds for all kinds of hardware (for example RFY)
> 
> I don't think anyone is using the logic of HA, but that HA is compatible like the others

ehmm....i think that all the other world is using the logic of HA :-)
i also refer to HA because originally autodiscovery was thought by Tasmota for HA.
and tasmota and HA has the same logic: ON=OPEN=1 
and they always refer the percentage to open (never to close)

Domoticz do the opposite: refer the percentage to close 
and ON is refer also to CLOSE

> Next to this Domoticz also has a 'inverted' blind (I never understood why people needed this) and I think this can be dropped

i don't think so.
also HA and tasmota has the inverted.
https://www.home-assistant.io/integrations/motion_blinds/

https://tasmota.github.io/docs/Blinds-and-Shutters/
![immagine](https://user-images.githubusercontent.com/44502572/193850395-95faf086-eb78-4653-93c4-1a02efea5e30.png)

the MQTT-AD is created with same logic: ON=OPEN=1
https://www.home-assistant.io/integrations/cover.mqtt/
https://www.home-assistant.io/docs/mqtt/discovery/

so why also we (domoticz) can not use the same logic?

coming back to the concept of _"I don't think anyone is using the logic of HA"_  i can say that also google home use the percentage open.
otherwise using google home to interact with domoticz we have to create an external script to revert the percentage like:
![immagine](https://user-images.githubusercontent.com/44502572/193851649-f0e69711-7b62-4747-a276-e56ea5d9b3c1.png)
for domoticz this above is 100-42 = 58%close
so i need an external script that when i act from ghome it revert the percentage to domoticz:
100-level => sent to domoticz

and also Alexa do the same


> I am open for suggestions, are you able to make a PR? But be sure that it won't break existing logic for MQTT-AD

no, unfortunately i'm totally far from to open a PR :-(
i can only support with my view/brainstorming.... if it is acceptable for you of course
sorry for that

**Comment by gizmocuz** [comment]
Maybe you are more into HA then. Thats perfectly fine, please continue to use this application as it suites your need perfectly fine.
This discussion has been here before
If you use MQTT-AD then the logic is the same as in HA

**Comment by megamarco833** [comment]
> Maybe you are more into HA then. Thats perfectly fine, please continue to use this application as it suites your need perfectly fine. This discussion has been here before If you use MQTT-AD then the logic is the same as in HA

mmm....you made a tough comment... maybe we are not in the same page....just to be clear i'm using only domoticz ... i never used  HA !
and i use domoticz since years (roughly more than 4 years and i'm more that happy) and i don't wont to change :-)

the issue reported here is coming from when i have to connect domoticz to google home or alexa or tasmota (tasmota manage the hardware of ESP32 or ESP8266) with dummy devices

> If you use MQTT-AD then the logic is the same as in HA

yes i'm using also MQTT-AD (with domoticz) and i agree that the logic is the same of HA
so i not understand why with dummy devices (so not AD devices) we can not have the same logic :)

p.s
if you read some messages before i also wrote:  _nothing against domoticz that is your baby_
so my comments had the aim of having an open discussion , not the aim to complain or fight....

**Comment by gizmocuz** [comment]
The reason I started with nValue 0 = open en 1 = close is because Domoticz started (many years ago) with only the P1 meter and support for RFXCom (RFXtrx433)
If you look in the header file rfxtrx.h and go to the definition of (for example):
- pTypeCurtain
- pTypeBlinds

You will see that open = 0 and close = 1

This is why I tried to keep this 'logic' in the software

Now you can imagine that if users start to send nValue = 1 to a sTypeBlindsT0 or to a pTypeCurtain that it going to close
Also, these (some of these) devices are also received, and when I receive a 1, I store this value (nValue) in the database and set the status in the GUI to Close

IF we are going to reverse this logic, it has to be checked/changed for this hardware

For me it is also logical that OFF/Open = 0, just like a dimmer 0=off and when I want to have some light (or close the blind a little bit) I can send a value above 0

I don't want to keep changing this either. It took me already a lot (a lot!!) of time for MQTT-AD, I don't even have blinds that can be controlled.... yet 
For the reverse there is also a 'inverted' type, so if people want to use 1 for open and 0 for closed they should use the inverted type, this way, everybody could be happy

**Comment by megamarco833** [comment]
> The reason I started with nValue 0 = open en 1 = close is because Domoticz started (many years ago) with only the P1 meter and support for RFXCom (RFXtrx433) If you look in the header file rfxtrx.h and go to the definition of (for example):
> 
>     * pTypeCurtain
> 
>     * pTypeBlinds
> 
> 
> You will see that open = 0 and close = 1
> 
> This is why I tried to keep this 'logic' in the software


ok, thanks for explanation.
if i can reply with just an idea from a persona that doesn't have so much skills on coding: i understand that  nValue 0 = open end 1 = close for RFXtrx433 and it is coded in rfxtrx.h
with that siad i have two comments:
1. the main logic should not be in the "core" and not in rfxtrx.h ?
2. if the logic is in rfxtrx.h can not think to have the logic of the blind (that so could be a different logic) in blind.h ?
again if these are stupid questions skip it :-)


 
> Now you can imagine that if users start to send nValue = 1 to a sTypeBlindsT0 or to a pTypeCurtain that it going to close Also, these (some of these) devices are also received, and when I receive a 1, I store this value (nValue) in the database and set the status in the GUI to Close
> 
> IF we are going to reverse this logic, it has to be checked/changed for this hardware


i fully agree that this will be a braking change (i also commented that in one of the previous post)
it "just a matter" of pro/cons that we can achieve introducing a braking change....maybe considering how many person are using this technology, and what's are the efforts for that users that will have to reverse open with close.


> For me it is also logical that OFF/Open = 0, just like a dimmer 0=off and when I want to have some light (or close the blind a little bit) I can send a value above 0

to me is the opposite for a blind.
if you want i can explain why: blind ON to me means that the blind is OPEN/UP so the light come inside the room. And also if i associate the blind to a light/switch: when the switch is ON light is ON and the blind so also will be ON/up/open
:-) 



> I don't want to keep changing this either. It took me already a lot (a lot!!) of time for MQTT-AD, I don't even have blinds that can be controlled.... 

yes i fully understand your efforts and i also see the the huge quantity of PR that you release during these months to have MQTT-AD.
and i appreciate also the works that all of you did to have the MQTT-AD function inside domotiz but also the efforts to maintain/correct it. 
With that said, what i was thinking (maybe wrongly) is that if we think on the others systems like i mention about: google home, alexa, home asistant, openHub, tasmota, and MQTT-AD that use the logic: ON=OPEN=Nvalue1=UP
maybe could be these difference compared to domoticz that can create these issues?

again these are **friendly speaking** only examples to compare "competitors" to us to compare pro/cons **nothing more.**
i reported also the image of google home that show the open percentage
i'm not a technician, you are, so feel free to not consider what i said :)

> yet For the reverse there is also a 'inverted' type, so if people want to use 1 for open and 0 for closed they should use the inverted type, this way, everybody could be happy

this last part could be the "Columbus egg" :-)
but my feeling is that if i select inverted blind i don't obtain ON=OPEN=Nvalue1=UP but only the swap of commands with ON to OFF (i'm pretty sure about that, but not 100% sure) 
do you think that is possible to have when inverted blind selected:
ON=OPEN=Nvalue1=UP
OFF=CLOSE=Nvalue0=DOWN
and very important with inverted also the percentage referred to OPEN =>   level=42  will means that the blind is 42% open from the top.
what do you think??
it could be managed in a "easy" way?

**Comment by gizmocuz** [comment]
the nValue is a state/command that is received or can be send.
It has various meanings as you can see in the mentioned header above
For some defines (not from type 'General') these nValues cannot be changed

We're thinking about making 1 general blind, this blind has two options you can enable/disable
- reverse state (open/close)
- reverse slider (0-100)

With this every possible option should be possible

At the moment we use gswitch_sOff = 0 and gswitch_sOn = 1 for the nValue (0=open and 1 = close)
But it should not matter, maybe we add

- gswitch_sOpen = 0x1c
- gswitch_sClose = 0x1d

It should not matter what nValue is used... In the GUI you will see the correct state and also with the Event system you see the correct state (open/close/level)
Changing the state/level in the EventSystem is done by (pseudo code) blind.open(), blind.close(), blind.setLevel(40)

Also in the JSON api you call Domoticz with a command like 'command=Open' to open the blinds


So your middleware application that converts the action from (Alexa/Google/...) to Domoticz has to use the right calls to perform an action

for JSON something like:

command=Open
command=Close
command=Set Level 40

Because you are using MQTT (not auto discovery) you see the real used nValues/sValues , for BlindsT1 (see rfxtrx.h) or any other hardware, these values have very specific meanings, 0 = not always off/close/open/turn siren on

Regarding the topic of this issue, when the blind 'opens' the open script is called and when you hit 'close', the close script is called
Regardless of a nValue

**Comment by gizmocuz** [comment]
Working on a PR that should correct it all

https://github.com/domoticz/domoticz/pull/5361

Feel free to test when/if possible, after compilation and starting make sure to clear the browser cache as there are changes in the GUI

**Comment by megamarco833** [comment]
thanks for your job!
do you think that you'll make this version available soon (as pre-compiled to avoid to compile it) for raspberry PI3 ?
i'll test asap :-)
p.s. finally still be there the option to have inverted blind with "opposite logic" to still have possibility on choose with logic to be used?

**Comment by gizmocuz** [comment]
Yes please see updated screenshot in the pull request

**Comment by megamarco833** [comment]
now i see it, looks promising, thanks
i'll guess that new beta version that will include it will be **14536**
let me know when it will be available for RPI3 and i'll test
thanks again

**Comment by gizmocuz** [comment]
The PR has been merged and there are no Inverted blinds anymore...
When you edit a switch/blind, you now have the option to reverse the state and/or position via checkboxes
Beta 14536 will be available within the hour for all platforms (lots of changes, lots to build)
Do not forget to clear your browser cache as the change involves some GUI changes/code as well!

**Comment by megamarco833** [comment]
thanks so much!
i'll test it asap.

**Comment by gizmocuz** [comment]
Please try beta 14541 and up (timers are still a thing to clear up... )

**Comment by megamarco833** [comment]
no problem :)
i'll update it as soon as i come back to home

**Comment by megamarco833** [comment]
> Please try beta 14541 and up (timers are still a thing to clear up... )

just to be sure on what i'll test with new domoticz version....

1. with first option if i select "reverse open/close state" active i will have: 
ON=OPEN=Nvalue1=UP
OFF=CLOSE=Nvalue0=DOWN

and without that option still be:
ON=CLOSE=Nvalue1=DOWN
OFF=OPEN=Nvalue0=UP
correct?

2. with the second option "reverse position" active i will have:
100% = all open

without the option reverse position i will have:
100% = all close
correct?

**Comment by gizmocuz** [comment]
Correct. Open = 100 by default (without reverse)
And when using the json API or the event system it will stay that way
Also nvalue = 1 = open zero closed
Some hardware have other values that is why you should use the json api or the event system and use open/close and not on/off
There is no on/off for blinds

**Comment by megamarco833** [comment]
> 

so if i understand correctly we have two functions

1. reverse open/close state
2. reverse position


1a. if **NOT  reverse open/close** state ( so default state)
OPEN=Nvalue1=UP
CLOSE=Nvalue0=DOWN
1b if **reverse open/close** state selected
OPEN=Nvalue0=UP
CLOSE=Nvalue1=DOWN


2a if **NOT reverse position** ( so default position)
Open = 100
close = 0
2b if **reverse position selected**
Open = 0
close = 100

> Some hardware have other values that is why you should use the json api or the event system and use open/close and not on/off
There is no on/off for blinds

my alexa doesn't know open/close but only on/off

**Comment by gizmocuz** [comment]
That’s correct
And no you can learn your own sentence to Alexa and let it perform a action so you can say open this or close that

**Comment by megamarco833** [comment]
i started to test just now.
it works good (but i need to test tomorrow better)

i tested all the combination and i just have only one doubt with "reverse position" flag

look at this example: dummy switch (no MQTT AD) type blind+stop
1st trial **without any flag**, i click to OPEN:
![immagine](https://user-images.githubusercontent.com/44502572/194779827-e11ec4d6-cc75-477c-8119-fea610ed8fb2.png)

`{"Battery":255,"LastUpdate":"2022-10-09 23:15:25","RSSI":12,"ReversePosition":"false","ReverseState":"false","description":"","dtype":"Light/Switch","hwid":"6","id":"000141A1","idx":337,"name":"test","nvalue":1,"stype":"Switch","svalue1":"100","switchType":"Blinds + Stop","unit":1}`

nvalue = 1 = OPEN  => ok
**svalue1 = 100 = OPEN**

2nd trial **now i flag reverse position and click again to OPEN**
![immagine](https://user-images.githubusercontent.com/44502572/194779875-1a79a60c-5021-4f1e-908d-a6862a40d159.png)
`{"Battery":255,"LastUpdate":"2022-10-09 23:16:58","RSSI":12,"ReversePosition":"true","ReverseState":"false","description":"","dtype":"Light/Switch","hwid":"6","id":"000141A1","idx":337,"name":"test","nvalue":1,"stype":"Switch","svalue1":"100","switchType":"Blinds + Stop","unit":1}`

nvalue = 1 = OPEN  => ok
**svalue1 = 100 = OPEN** => ?? why still be 100? it should not be 0 (because i reverse position)?
 the slider on the GUI is correctly on the left  (because i reverse position) and it's opposite to previous default condition, so to me it's ok


>And no you can learn your own sentence to Alexa and let it perform a action so you can say open this or close that

uhmm i think that you are referring to "routine" in alexa...because in alexa i don't see blind as optional device...only light or switch or other stuff but not blind...
with a routine you can do: "when i say OPEN" do that action...and the as action to be performed i have to select a light (that is a blind in domoticz) and so alexa ask me if i want it to ON or to OFF
so action are referred to ON or OFF....isn't it?

**Comment by gizmocuz** [comment]
Maybe actions are on/off, but you can specify what you want to do for this action, when you say 'open' open the blind, or turn a light to 50% anything
Regarding nValue and gui and dzVents.... there is no difference in the Gui, clicking Open will send a JSON command to Domoticz 'Open', and internally this command might be reversed send to the real blind
Same as dzVents, when the blind is 'open' , the status is 'open' in the scripting system, also when using dzVents (or another scripting) and you call blinds.close() it will close the blind... but if you had specified 'reversed state', the command will be reversed before sending it to the actual device.
Hope this part is clear ?

Again regarding nValue, most times 1=open and the percentage for open = 100, that is how it works for all other hardware/software, and now Domoticz does the same
Hope this part is clear ?

Regarding your Alexa, If you need to reverse the state or position (for whatever reason) create a action and send OFF to domoticz (or ON) you decide

**Comment by gizmocuz** [comment]
New beta 14552 available that solves a possible issue for dzVents tested by multiple users and seems to work correct now

**Comment by megamarco833** [comment]
> Again regarding nValue, most times 1=open and the percentage for open = 100, that is how it works for all other hardware/software, and now Domoticz does the same
Hope this part is clear ?

not that much :)
what is crystall  clear is that: 1=open and the percentage for open = 100 
and it is confirmed by this (l without any flag selected) with a dummy device (not MQTT -AD), i click to OPEN:
![immagine](https://user-images.githubusercontent.com/44502572/194860455-d443955f-0bdf-4e44-9bb9-272eeac3362b.png)

`{"Battery":255,"LastUpdate":"2022-10-09 23:15:25","RSSI":12,"ReversePosition":"false","ReverseState":"false","description":"","dtype":"Light/Switch","hwid":"6","id":"000141A1","idx":337,"name":"test","nvalue":1,"stype":"Switch","svalue1":"100","switchType":"Blinds + Stop","unit":1}`
summarizing
nvalue = 1 = OPEN => ok
svalue1 = 100 = OPEN
so all it's fine.

now i flag ONLY reverse position and click again to OPEN
![immagine](https://user-images.githubusercontent.com/44502572/194860652-2e986653-9ab8-47da-a840-7eda7def0ed0.png)
`{"Battery":255,"LastUpdate":"2022-10-09 23:16:58","RSSI":12,"ReversePosition":"true","ReverseState":"false","description":"","dtype":"Light/Switch","hwid":"6","id":"000141A1","idx":337,"name":"test","nvalue":1,"stype":"Switch","svalue1":"100","switchType":"Blinds + Stop","unit":1}`

nvalue = 1 = OPEN => ok
svalue1 = 100 = OPEN =>  why Svalue1 still be 100? it should not be 0 (because i reverse position)?
the slider on the GUI is correctly on the left (because i click on reverse position) and it's opposite to previous default condition, so to me it's ok the visual GUI i not understand the Svalue1 100 and not 0

thanks for your patience.

**Comment by gizmocuz** [comment]
It's a shame the LastLevel value is not in MQTT.... I have to debug this, but maybe you can have a look in the database with (for example) SQLite Expert Personal Edition (DeviceStatus table)

**Comment by gizmocuz** [comment]
I found the reason why 'Level' was not transmitted, this is now added in beta 14558

**Comment by megamarco833** [comment]
ok, i'll test it.
thanks

**Comment by megamarco833** [comment]
> I found the reason why 'Level' was not transmitted, this is now added in beta 14558

hello, i tested the beta **release 14562**
but i still see the issue about level and Svalue1 

summarizing: without any flag selected) with a dummy device (not MQTT -AD), i click to OPEN
nvalue = 1 = OPEN => ok
svalue1 = 100 = OPEN
the slider on the GUI is correctly on the **right**
so all it's fine.
and this is the mqtt message received:
`{"Battery":255,"LastUpdate":"2022-10-11 09:35:09","Level":100,"RSSI":12,"ReversePosition":"false","ReverseState":"false","description":"","dtype":"Light/Switch","hwid":"6","id":"000141A1","idx":337,"name":"test","nvalue":1,"stype":"Switch","svalue1":"100","switchType":"Blinds + Stop","unit":1}`

now with same device i flag ONLY reverse position and click again to OPEN:
nvalue = 1 = OPEN => ok (because i not reverse the state open/close)
svalue1 = 100 = OPEN => **why Svalue1 still be 100? it should not be 0 (because i reverse position)?**
the slider on the GUI is correctly on the **left** (because i click on reverse position) and it's opposite to previous default condition, so to me it's ok the visual GUI i not understand the Svalue1 100 and not 0
here below the mqtt message received
`{"Battery":255,"LastUpdate":"2022-10-11 09:35:24","Level":100,"RSSI":12,"ReversePosition":"true","ReverseState":"false","description":"","dtype":"Light/Switch","hwid":"6","id":"000141A1","idx":337,"name":"test","nvalue":1,"stype":"Switch","svalue1":"100","switchType":"Blinds + Stop","unit":1}`

**Comment by gizmocuz** [comment]
@megamarco833 , the reason for this is that in the system the level is still 100, but when send to the actual hardware (internally) this is reversed.

See for the blind explanation here:
https://github.com/domoticz/domoticz/issues/5359#issuecomment-1274347465

So if you have a physical Fibaro ZWave blind (for example) and have set the reversed position to true

Setting the value to 80% in the Gui will still display 80% in the Gui , send 80% to the event system and MQTT and all others
But the value 20% is transmitted to the physical unit

**Comment by megamarco833** [comment]
very good explanation!
thanks for your job
i think that will be perfect add this to domoticz wiki on a specific chapter for blind

**Comment by gizmocuz** [comment]
Yes it definitely is 🤣

**Comment by ab10002** [comment]
After v14525 i can't get my shutters right using the somfyIO plugin. Also after modding(on/off or open/close) the plugin. I can send curl command direct to localAPI from the tahomabox like this:
```
+-----+ 0% or open or up (shutter =open)
|     |
|     | 20% (shutter = 20% closed)
|     |
|     | 80% (shutter = 80% closed)
|     |
+-----+ 100% or close or down (shutter is closed)
```

But wiki/blinds shows something different..
```
Standard Blinds behave in the following fashion.

0 = Blind Close in GUI/dzvents
100 = Blind Open in GUI/dzvents
90 = Show 90 in the GUI/dzvents, Send 90 to the device (Blind almost fully Open)
10 = Show 10 in the GUI/dzvents, Send 10 to the device (Blind almost fully Closed)
```

**Comment by gizmocuz** [comment]
It could be that the SomfyIO plugin needs to be updated.
You could try to edit your blind and enable the options 'revert state and revert position'

**Comment by ab10002** [comment]
I know all that and mod the plug on every way
There is a big difference in the somfy and domitcz behavior..

**Comment by gizmocuz** [comment]
Not sure what you are saying above, got it working now?
What is the 'localAPI'? the API of Domoticz ? Could you post the curl commands to Open,Close and Set the Level to 40%
The default blind behavior is different and now compliant with other hardware/software. Open=100, Close=0

**Comment by ab10002** [comment]
No, not working. After setting the tahomabox in "Developer Mode", is it possible to send commands locally
The different blind behavior, make's it not simple..

curl commands:
```
curl --location --request POST 'https://{your-pin}.local:8443/enduser-mobile-web/1/enduserAPI/exec/apply' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer 12345678901234567890' \
--data-raw '{"label": "test - Set to 20% - TaHoma","actions": [{"deviceURL": "io://{your-pin}/{device}","commands": [{"name": "setClosure","parameters": [20]}]}]}'

```

**Comment by gizmocuz** [comment]
Okey this seems to be a API for the Tahoma box not Domoticz
Seems there has been a update in the plugin to support the open/close commands

https://github.com/MadPatrick/somfy

It's still unclear what goes wrong when you use the python plugin (not using the direct API)

Does Open/Close work? Does setting a percentage work?
If Open/Close are reversed (I don't think so looking at the latest change in the last commit of the plugin) you can reverse this by editing the blind and check 'reverse state'
If the position seems inverted, you can also edit the blind and check reverse position
But best to not use the reverse options at all and modify the plugin
There is no On/Off anymore , you need to use Open/Close

**Comment by gizmocuz** [comment]
I see a lot of 100-level in the plugin code that could probably be removed as the default blind behavior Domoticz is now like this
And the code could use a little cleanup to remove duplicate code in 'def update_devices_status(self, Updated_devices'
(Settings sValue/LastLevel and Update is the same for both three states when you use str(level) )

Not sure is 'onCommand_legacy' is used, but if it is, also use the same || check as in onCommand (for Open/Close)

**Comment by ab10002** [comment]
> Okey this seems to be a API for the Tahoma box not Domoticz Seems there has been a update in the plugin to support the open/close commands
> 
> https://github.com/MadPatrick/somfy
> 
> It's still unclear what goes wrong when you use the python plugin (not using the direct API)
> 
> Does Open/Close work? Does setting a percentage work? If Open/Close are reversed (I don't think so looking at the latest change in the last commit of the plugin) you can reverse this by editing the blind and check 'reverse state' If the position seems inverted, you can also edit the blind and check reverse position But best to not use the reverse options at all and modify the plugin There is no On/Off anymore , you need to use Open/Close

I know all of this and tried everything else... something in the open/close won't.

But i think i changed to 0% and 100% instead of open/closed to avoid all of this

**Comment by ab10002** [comment]
> I see a lot of 100-level in the plugin code that could probably be removed as the default blind behavior Domoticz is now like this And the code could use a little cleanup to remove duplicate code in 'def update_devices_status(self, Updated_devices' (Settings sValue/LastLevel and Update is the same for both three states when you use str(level) )
> 
> Not sure is 'onCommand_legacy' is used, but if it is, also use the same || check as in onCommand (for Open/Close)

Okay, i don't know. I'll report it.

**Comment by gizmocuz** [comment]
@ab10002 , best to use the forum

https://www.domoticz.com/forum/viewtopic.php?t=28613
