### ISSUE TITLE
Domoticz Evohome Web API stopped working as of August 15

### ISSUE THREAD

**Issue by fwieringen** [domoticz/domoticz#5350]
Hi,

I've set up an Evohome solution at home. I wanted to add the system to Domoticz using the Web API, however it gives authentication errors in the logfile.

- 2022-08-31 10:27:35.952 Status: (Evohome) Worker started... 2022-08-31 10:27:45.961 Status: (Evohome) connect to Evohome server
- 2022-08-31 10:27:47.599 Error: (Evohome) login failed with message: invalid_grant
- 2022-08-31 10:29:47.672 Status: (Evohome) connect to Evohome server
- 2022-08-31 10:29:49.156 Error: (Evohome) login failed with message: invalid_grant`

I posted the topic on the Domoticz Forum (https://www.domoticz.com/forum/viewtopic.php?t=39023). Turns out that more people experience the issue. One user indicates that the devices stopped last reported on 15-08-2022 11:51.

Considering the fact that nothing has changes on the Evohome domoticz files in 8 months, this must me something which has been changed on the Evohome API side.

How can I fix this?

Thanks!
Friso

**Comment by MikeyMan83** [comment]
Still having that error? I'm having some issues with evohome as well.

**Comment by fwieringen** [comment]
Yes, the error is still there. Think Honeywell has changed the logon method or something.

**Comment by MikeyMan83** [comment]
Now i've found the cause and solution to my issue. Might help you.

Seems i've pressed a button too many and added a 'hot water' steering.
Took a while to figure it out. But it was fixed quite simple.

I've deleted the installation from mytotalconnectcomfort.
Somehow at the moment the login is only available in UK and Ireland. But it works.

There i've deleted and re-added the installation. Everything is working fine now.

**Comment by fwieringen** [comment]
Did you het the same error message (invalid_grant) or is this just a different issue?

**Comment by MikeyMan83** [comment]
No differnent issue, but its worth the try to see if there are unused devices. 
And re-adding it is no risk at all tbh.

**Comment by fwieringen** [comment]
Just re-added the location. No difference unfortunately 🙁

**Comment by MarcelBaas** [comment]
Hi, I'm facing the same issue since somewhere june 2022.  All of a sudden my evohome lost connection with the cloud service from honneywell. I managed to restore that by deleting the account an create a new one. However the connection to domomticz is never restored since then. 
I'm wondering if the cloud services changed some security setting that block requests like the ones from domoticz (via the web interface).
Haven't found a solution yet. If anyone has any clue..... would like to know :-)
By the way this is the message " Error: (EvoHome) login failed with message: invalid_grant"

**Comment by aschaake** [comment]
My api works fine except for the status in the dzvents scrits.

Controlling and reading temperatures works fine here.

**Comment by uberdorf** [comment]
invalid_grant -- The provided OAuth 2.0 grant is invalid, expired or has been revoked. May also indicate the redirect_uri parameter doesn't match (for a code grant).

**Comment by MikeyMan83** [comment]
It will deprecate at a certain point. So not surprising that there are some issues.

See:
https://github.com/domoticz/domoticz/pull/1752

**Comment by uberdorf** [comment]
Possible solution posted on the forum

**Comment by MikeyMan83** [comment]
> Possible solution posted on the forum

@uberdorf link would be nice

**Comment by uberdorf** [comment]
It is stated on top of this page.

**Comment by fwieringen** [comment]
That solved the issue, or at least is a good workaround.

Schedule was already off, so basically changing the password to something with only one special character (*) did the trick.

**Comment by uberdorf** [comment]
> That solved the issue, or at least is a good workaround.
> 
> Schedule was already off, so basically changing the password to something with only one special character (*) did the trick.

Great that this has worked for you.  It has something to do with the V1 en V2 API implementation I believe. After the initial connection it should be possible to enable schedule again.

**Comment by MarcelBaas** [comment]
I used this workarround:
https://domoticz.com/forum/viewtopic.php?p=292979
Works for me although it's really a workarround

**Comment by gizmocuz** [comment]
For others that have the above issue, it was solved by

```
1. In your Evohome account, create a new password which meets the password requirements but contains only 1 special character, preferably a *
2. In Domoticz under hardware adjust "Evohome via web API" and disable "show schedule". You can leave "synchronize installation" and "show location" to on.
3. Set "poll interval" to be above 300 seconds.
4. adjust the password to what has been created under 1
5. click update
```
