### ISSUE TITLE
daily switchover is sometimes dropping values of first daily update

### ISSUE THREAD

**Issue by WillemD61** [domoticz/domoticz#5353]
I have 3 counters that are updated with a DZVents script during the day at various moments. The log files show the values of these counters at each run, whether they are updated or not. I can see in the log files all updates during the day increase the counter by the required values, no problems at all. The updates are also visible in the graphs for the devices.

However, when I look at the daily totals in the graphs one or more days later (so after midnight switchover), I see daily totals that SOMETIMES do not fully correspond with all the updates. Most of the time it works fine, but sometimes there are values missing. If there are any values missing then it is ALWAYS the first increase of the previous day that is missing (and the first update can be anytime, also later in the day).

So the daily switchover routine in Domoticz is sometimes dropping the first update of the day when calculating daily totals.

When I inspect the Meter_Calendar table I see the VALUE field showing the incorrect values (so missing the first update, sometimes), however when I look at the increase of the COUNTER field I see the correct totals (so including the missing values). 

So the VALUE field is wrong, the increase in COUNTER is correct (and therefore the COUNTER of the previous day plus the VALUE does not equal the COUNTER of the next day).

As a temporary workaround I am now using a python program to check integrity and update the VALUE to the correct difference between COUNTERs.

domoticz v 2022.1
dzVents 3.1.8

**Comment by gizmocuz** [comment]
This has been solved in the recent beta version

**Comment by WillemD61** [comment]
This is NOT solved in the new release 2022.2

I still have counters where the counter difference between one day and the previous day does not correspond to the value recorded on the day. The value is then lower than the difference between the counters.

I am not sure whether this is still caused by the first update of the day like mentioned in my initial post, but some value is missing for sure. As result the graphs showing daily values are wrong.

This happens on devices in the METER_CALENDAR tables but also on MULTIMETER_CALENDAR devices (such as a P1 meter)
