### ISSUE TITLE
Timer Trigger rules - "on" command not working accross year change

### ISSUE THREAD

**Issue by Krakinou** [domoticz/domoticz#5355]
version : Domoticz 2022.1 build 14453
Python 3.9.2
Raspberry3 w/ Debian 11

Consider this script:
````
return {
    on = {
		timer = {'every minute on 01/09-15/06'},
	},
	execute = function(domoticz, timer)
            domoticz.log('This script works', domoticz.LOG_INFO)
    end
}
````
According to my log, it worked correctly during september then stopped working on first of october.
If I change the timer trigger to `'every minute on 01/10-15/06'` it will work again... until 1st of november when I assume it will stop working.
If I change the timer trigger to `'every minute on 01/09-31/12'`, it will work. So we may use 2 timer trigger rules to make it work (one until 31/12 and one starting 01/01) but it does not seems to be the intended way to use the trigger.

**Comment by gizmocuz** [comment]
What happens when you use 15/06-01/09 ? (Set them in logical order)

**Comment by Krakinou** [comment]
This is working as expected.
Well: my requirement is to have the script running in winter time, so from september to june.
Maybe I misunderstood the syntax, but I don't see any other way to set this time frame?

**Comment by Krakinou** [comment]
OK.
My bad : I rereread the wiki for DzVents and saw this:
````
on -3/4,4/7-',             -- before 3/4 or after 4/7
````
So I guess I should set `'every minute on -15/06,01/09-'` instead of `'every minute on 01/09-15/06'`
Sorry for not having RTFM...
