### ISSUE TITLE
mqtt autodiscovery and tasmota 11 broken in beta upper 14498

### ISSUE THREAD

**Issue by DAVIZINH0** [domoticz/domoticz#5356]
Hello,
I use docker version 14498 with autodiscovery and tasmota 11 devices.
I use tasmota 11, because in tasmota 12 change the autodiscovery and not works.
The topic in mqtt autodiscovery is homeassistant and works perfect in 14498 beta version.
I update today to 14525 and any of my tasmota devices works. its return a error:
2022-10-03 17:43:20.547 Error: MQTT_AutoDiscovery_Tasmota: Switch not found!? (AFC4B0_RL_3/Bu_Regleta_Impresora_Impresora)
I update to 14528 and the problem persist.

I rollback the docker container to 14498, and works again.
Maybe you make some change in MQTT autodiscovery?

thanks a lot!

**Comment by gizmocuz** [comment]
There have been many changes, but it would be best if you post a switch config topic + payload
Are you on Slack?
Double check you have not received another switch

**Comment by DAVIZINH0** [comment]
hi, 

I update today to 14534, and the problem persist. And no new devices.
I launch other docker with a old version.

tomorrow i will enter in slack and coment the problem, and try to provide more information (today is a bad day for me:-( )

**Comment by DAVIZINH0** [comment]
hello @gizmocuz  and thanks, as allways for your reply!!!. its a pleasure report bugs with people like you!
i post this information in slack too, and paste here to track for future problems or if someone have post more information

information in mqtt exploer: topic homeassistant/switch/xxx/xxx/config
{"name":"Bu_Luz_Vitrinas","stat_t":"tele/bu_luz_vitrinas/STATE","avty_t":"tele/bu_luz_vitrinas/LWT","pl_avail":"Online","pl_not_avail":"Offline","cmd_t":"cmnd/bu_luz_vitrinas/POWER","pl_off":"OFF","pl_on":"ON","val_tpl":"{{value_json.POWER}}","uniq_id":"0CB815_RL_1","dev":{"ids":["0CB815"]}}



i push the button in domoticz and apears this error: " Error sending switch command, check device/hardware (idx=771)!

and in log:  2022-10-05 13:24:20.772 Error: MQTT_AutoDiscovery_Tasmota: Switch not found!? (0CB815_RL_1/Bu_Luz_Vitrinas)

**Comment by gizmocuz** [comment]
Could you post your real topic, this is not the real topic "topic homeassistant/switch/xxx/xxx/config"

**Comment by DAVIZINH0** [comment]
wow, maybe i make something wrong :-(
i will try again

maybe is this correct?

{"name":"Bu_Luz_Vitrinas","stat_t":"tele/bu_luz_vitrinas/STATE","avty_t":"tele/bu_luz_vitrinas/LWT","pl_avail":"Online","pl_not_avail":"Offline","cmd_t":"cmnd/bu_luz_vitrinas/POWER","pl_off":"OFF","pl_on":"ON","val_tpl":"{{value_json.POWER}}","uniq_id":"0CB815_RL_1","dev":{"ids":["0CB815"]}}

**Comment by gizmocuz** [comment]
This is the payload of the Topic, I am interested in the topic itself ...
The topic start with homeassistant/

like this:
homeassistant/switch/mydimmer/dinner_table/config

**Comment by DAVIZINH0** [comment]
Solved since beta 14535
thanks @gizmocuz !!!!!
