### ISSUE TITLE
Utility devices custom icons aren't correctly shown in Floorplan

### ISSUE THREAD

**Issue by acaonweb** [domoticz/domoticz#5358]
#Version: 2022.1 (build 14528)
Build Hash: c301cf63b
Compile Date: 2022-10-03 16:01:39
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

Hi, using custom icons in utility devices, in dasboard are't correctly shown
Example 1
![image](https://user-images.githubusercontent.com/22882393/193822144-523215b3-643d-439c-91ac-5b7f9e6f40ff.png)
![image](https://user-images.githubusercontent.com/22882393/193822273-9710a6c3-128c-4e39-8430-e6e3b2048a65.png)
Example 2
![image](https://user-images.githubusercontent.com/22882393/193822552-d45fbfea-7c9c-44ac-8195-b850602528bc.png)
![image](https://user-images.githubusercontent.com/22882393/193822662-79533a73-d933-4c8e-a53c-201aee09feee.png)

Cache cleaned, icons reinstalled, restarted domoticz & rpi

Thanx for your great job :)

Fabrizio

**Comment by gizmocuz** [comment]
Thanks for reporting! Should be solved in beta 14538

**Comment by acaonweb** [comment]
hi, now it's resolved but it has introduced a new bug. I'va all my dummy switch on/off with default icon (a bulb) correctly shown in switch page, but not in dashboard, like those pics
<img width="436" alt="Schermata 2022-10-09 alle 11 00 03" src="https://user-images.githubusercontent.com/22882393/194747864-cabc92a3-1e64-4209-b0c2-527c018c4d1f.png">
<img width="378" alt="Schermata 2022-10-09 alle 11 00 22" src="https://user-images.githubusercontent.com/22882393/194747876-ca60b211-5488-4bbc-9e12-4b065186a808.png">

**Comment by gizmocuz** [comment]
Found and solved the issue in beta 14541
