### ISSUE TITLE
Roller shutters used in scenes are closed complety when set to open 100% and opposite

### ISSUE THREAD

**Issue by pawol** [domoticz/domoticz#5359]
On the latest beta version 2022.1.14534 the roller shutters used in scenes are completly closed when scene sends "set to open 100%" instead of to be fully open. An opposite - when scene sends "set to close 0%" then the roller shutters are fully open instead of to be fully closed. When I set scenes set to 1% or 99% then it works almost as needed but it looks that value of 0% and 100% is reversed.
The sliders of each roller shutter works ok. Previosly (vewrsion 2022.1.14445) the issue was on sliders only and it looks that an issue was fixed not correcly

**Comment by gizmocuz** [comment]
What hardware type are you using? MQTT?

**Comment by pawol** [comment]
tasmota to control roller shutters

**Comment by gizmocuz** [comment]
So you use MQTT Auto discovery ? To what type of hardware (in domoticz) this blind belongs?

**Comment by pawol** [comment]
previosly only slider was reversed on 0% and 100% position. This time slider is okay but in fact shutters are reversed only when 0% or 100% is used. Other values 1-99% works okay. I do not use any auto discovery. I use virtual switches to control tasmota

**Comment by gizmocuz** [comment]
So the type is dummy hardware ?

**Comment by gizmocuz** [comment]
And is it a normal blind or inverted type?
And when used in the gui, do they work correct?

**Comment by pawol** [comment]
The type of rollers is "percentage inverted".
The rollers and their sliders works okay when used in the GUI
Each tasmota is configured as virtual switch. 
Group of rollers is controlled by the scenes.
The problem occurs only when I use group of rollers in the scene. 
Looks that the bug is in the scene support only. 
The scenes have a problem with reversed 0 and 100% only. 
The positions 1-99% triggered by the scenes  works ok.

**Comment by gizmocuz** [comment]
Can you answer the above two remaining questions regarding the type and if it is a normal or inverted blind type you use
'yes' is not the answer to them

**Comment by pawol** [comment]
I edited post above

**Comment by pawol** [comment]
Did you get all necessary pieces of information?

**Comment by waltervl** [comment]
@pawol still exists in latest beta with full open/close?
There seems to be an issue now with partial open/close (1-99%) with scenes, see issue  https://github.com/domoticz/domoticz/issues/5365

**Comment by pawol** [comment]
The scenes do not work at all on today's beta. I was able to open 100% by means of scenes but other combinations (0,25,50,75 %) do not work completly - nothing happened when the scenes were triggered from gui.

**Comment by waltervl** [comment]
So your initial issue is solved but you also have issues with partial? Did you delete your browser cache before trying as some changes are made on the browser side.

**Comment by pawol** [comment]
I cannot say that the initial issue is fixed. The scenes are not testable now at all. I used completly different browser and private mode

**Comment by gizmocuz** [comment]
@pawol ,
Could you try beta 14555, there is now also the option to select Open/Close as command
These changes also involve a change in the GUI, to be sure, clear your browser cache again and you should see the new open/close commands in the scene editor

**Comment by roblomq** [comment]
@gizmocuz is it possible that you have a short summary or point me to the right documentation because I'm a bit blinded in the blinds. It changed, changed back, changed partly changed in mqtt changed in the user interface changed open to close and back again. It seems a complex issue and am convinced the changes are for the good but for now my DzEvents script tries to open a screen that is already open and closes the other screen that needs to be open.

Using a Fibaro wallI rollershutter FGWREU-111
Using Zwave2MQTT
Using Zwave2MQTT auto discovery
Using build 14558

I think the last change is that the inverted option is removed from the ui and through auto discovery there is a switch position 1 and a switch position 2 (so two separate devices). This way you have the possibility to use the switch that matches the real position. But with this Fibaro I have you can reverse this already in the settings so there is no real need for the both switches, I assume this is to keep it more general for situations that you don't have the possibility to toggle this. Is that correct?

There are also created two "Interface Control" and a "hardware status", were are these for?

The main problem is that the new created device "position_2" does nothing and for one blind position 1 and position 2 are both on status open.

**Comment by gizmocuz** [comment]
@roblomq ,
Firstly, all these changes have no effect on the switches created by MQTT-AD and ZWaveJS-UI
I have no idea why you get these two position switches or what they are
When using a Fibaro shutter node, you should at least get a blind, that is the one you have to use
You should also not change the configuration in ZWaveJS-UI (reverse states etc)

In Domoticz a normal Blind is created, not inverted, and when you edit the blind there should also be no reverse option enabled
Now all works by default

The blinds now behave as in other hardware/software
Open = 100%, Close = 0%

In your scripts or with the JSON API, you do not use on/off but you need to use blinds.open() and blinds.close() or send a JSON command Open/Close

When you use the application MQTT Explorer and look in the auto discovery topic, you should see a tree node called 'cover'.
Underneath there should be your blinds

**Comment by gizmocuz** [comment]
@roblomq , I made a nasty mistake in the previous beta, please update to beta 14561 and delete these new devices

**Comment by roblomq** [comment]
No problem, I will update and check again. Can I test something for you or is there no need?

**Comment by gizmocuz** [comment]
Please test beta 14564, this should work fine now with blinds and normal lights/switches again

**Comment by Rouzax** [comment]
To further explain the behaviour now

**Standard Blind**
```
- 0 = Blind Close in GUI/dzvents
- 100 = Blind Open in GUI/dzvents
- 90 = Show 90 in the GUI/dzvents, Send 90 to the device (Blind almost fully Open)
- 10 = Show 10 in the GUI/dzvents, Send 10 to the device (Blind almost fully Closed)
```
2 Checkboxes in the Normal Blind config
- Reverse Open/Close State
- Reverse Position
![image](https://user-images.githubusercontent.com/4103090/195044085-d9edc9fd-dd5f-45ed-bcd0-6ca8919a20a8.png)

You need to edit the device in Domoticz
![image](https://user-images.githubusercontent.com/4103090/195044340-e47977a8-fab2-4f89-98ea-66e31356f518.png)

Then the Toggles are there.
![image](https://user-images.githubusercontent.com/4103090/195044388-c5ee82a9-4ad6-42de-84db-cd5ff8c3ae63.png)

**Reverse Open/Close State: ✔️**  
**Reverse Position: ❌** 
_This will only reverse the State Labels and will leave the Slider position on default behaviour_
```
- 0 = Blind Open in GUI/dzvents
- 100 = Blind Closed in GUI/dzvents
- 90 = Show 90 in the GUI/dzvents, Send 90 to the device
- 10 = Show 10 in the GUI/dzvents, Send 10 to the device
```

**Reverse Open/Close State: ❌**
**Reverse Position: ✔️**
_Only Reverse the Slider position, leave State Labels default_
```
- 0 = Blind Closed in GUI/dzvents
- 100 = Blind Open in GUI/dzvents
- 90 = Show 90 in the GUI/dzvents, Send 10 to the device
- 10 = Show 10 in the GUI/dzvents, Send 90 to the device[/code]
```

**Reverse Open/Close State: ✔️**
**Reverse Position: ✔️**
_This will reverse the State Label, and will reverse the Slider position_
```
- 0 = Blind Open in GUI/dzvents
- 100 = Blind Closed in GUI/dzvents
- 90 = Show 90 in the GUI/dzvents, Send 10 to the device
- 10 = Show 10 in the GUI/dzvents, Send 90 to the device
```

**Comment by roblomq** [comment]
Probably a serious question but I'm on 14558 and when I check for updates I get the message that there are no updates available.

**Comment by roblomq** [comment]
Thanks, this is very clear. Especially the new switches because I completely missed them.

**Comment by gizmocuz** [comment]
@roblomq , all working now? You found the new beta version ?

**Comment by pawol** [comment]
On the latest beta 14565 the scenes seem to work okay without any reconfiguration. I mean I did the upgrade only and and the scenes works as expected

**Comment by gizmocuz** [comment]
Thanks for the feedback!
