### ISSUE TITLE
dzvents scrtipt execute domoticz.log(domoticz.devices('Thuis: EvoTouch').state) returns 0 and previous non beta showed "auto"

### ISSUE THREAD

**Issue by aschaake** [domoticz/domoticz#5360]
I have an EVOHOME thermostat I can control it by dzvents scripts but i use a check before I change the status of my thermostat.
This check is based on domoticz.log(domoticz.devices('Thuis: EvoTouch').state) normaly resulting the current status as shown also in de data of my device. but now the text status is no longer returned. Now a numeric value is returned. Can this be repaired so the text value is returned like it used to do.

The devices shows the right status in the devices page and als on the control pages. 

LAst year my script worked flawless. This year switched to beta because of an earlier issu I reported that was fixed.
I can see it was also a problem in my previous beta.

I run 2022.1 build 14534 on a raspberry PI 4

**Comment by aschaake** [comment]
It seems that in the dzvents scripting a value is shown instead of the text state that is shown in de domoticz html pages. 

Status Auto or Normal seems to be displayed as 0?
Status Away seems to be displayed as a 2? 

This used to be the "text" value like Away or Auto.

Is it possible to repair this so the text value is shown again when using the script call  domoticz.log(domoticz.devices('DEVICE NAME').state)

**Comment by aschaake** [comment]
When using domoticz.log(domoticz.devices('DEVICE NAME').mode) also only numeric values are returned.

**Comment by gizmocuz** [comment]
@aschaake , I have no EvoTouch so it's not easy to replicate.
Could you tell me (from the devices tab) the type/subtype of this device?
Could you show me a screenshot of the create device?

**Comment by aschaake** [comment]
@gizmocuz 
I have a made a few screenprints. I hope this helps.

1.: Evohome device list from the devices tab. The problem is in device 356 which is the main thermostat. The other devices work fine and show the right values in the scripts. I made some examples for the right functioning devices (359 360 and 361).

2: This screen print showes what hardware settings I use to communicate with evohome (Evohome via web api)

3: Her I made a screenprint of my script (left) and the result of the script in the logfile (right). Here you can see that only for the main thermostat 356 the value is shown as a number while in the devices tab the word "Away" is shown. For the other devices 359 360 and 361 the right text value is shown.

I hope this helps. If you need mor information, then I will get it for you.

Best regards,
![Evohome_DEVICES](https://user-images.githubusercontent.com/39566739/196004333-6c8b0d03-3faa-452b-9d6f-1e289b04327e.JPG)
![Evohome_HARDWARE](https://user-images.githubusercontent.com/39566739/196004336-28d0b98a-d3e0-44fe-89f7-0ef73455e177.JPG)
![Evohome_script_and_logfile](https://user-images.githubusercontent.com/39566739/196004335-4b95271d-07fb-4ace-b3bc-8e0bb5b8ad64.png)

best regards,

Arno

**Comment by gizmocuz** [comment]
I am having a bit of a problem getting this type recognized in dzVents but I am prety sure the problem is inside this file

dzVents/runtime/device-adapters/evohome_device.lua

Line 57

`				device.mode = device._state

If you look in the github history for this file, I do not see any changes related to this

Maybe you could try to debug this ?

Not sure if you have to restart Domoticz when making changes into this file

**Comment by aschaake** [comment]
Is there a way to dump the rawdata in the log? I want to know where the current numeric values are coming from. 

When i use https://domoticz_ip_port/json.htm?type=devices&filter=all&used=true&order=Name
I see:
data for devicesubtype - evohome :   "Data" : "Away",

data for devicesubtype = zone:  "Data" : "20.4 C, (12.0 C), Away",

**Comment by gizmocuz** [comment]
@aschaake , hope it's solved now in beta 14573

**Comment by aschaake** [comment]
> @aschaake , hope it's solved now in beta 14573

@gizmocuz Will test it tonight!!

**Comment by aschaake** [comment]
@gizmocuz 

I think you are close! But it might be the other way around or no difference between state and mode. I think the right way is that there is no difference between mode and state for this device subtype. I will try to explain.

The evohome system has 1 central device and several zone-devices (called zones). The central device has only one function and that is switching the whole system and all of its zones between the modes "eco" "auto" "away" and so on. It does not have a temperature setting like the zones have.

The zones show have their mode and their current temperature settings. That is why mode and state are different (example mode= away and state is 12 for the temperature setting) This is functioning the right way!

So I think the rules for mode and state for the subtype "evohome" should be the same.

My suggestion would be to change the current rules :

FROM
if device.deviceType == 'Heating' and device.deviceSubType == 'Evohome' then
device._state = data.data._state
device.mode = tostring(data.data._nValue)

IN

if device.deviceType == 'Heating' and device.deviceSubType == 'Evohome' then
device._state = data.data._state
device.mode =  data._data._state

I made this change in the evohome_device.lua file and now it behaves like I remember and how I think it should be.

**Comment by gizmocuz** [comment]
According to this document (search for Evohome (controller) )

https://www.domoticz.com/wiki/DzVents:_next_generation_Lua_scripting

there should only be a 'mode'

I made them the same as you suggested above in beta 14574, hope it works correct now

**Comment by aschaake** [comment]
@gizmocuz 

Yes it works flawless now! Great work! 

Thank you for the great work and communication!

**Comment by bramvreugd** [comment]
Are you sure it works flawless. In my scripts the state returns always "On" even when in the Domoticz gui is displays "Off"

**Comment by gizmocuz** [comment]
@bramvreugd , you are on the latest beta? yes it should work

**Comment by bramvreugd** [comment]
Yes I am on the latest. My problem seems to be be gone at midnight last
night. I will look into into it more tomorrow. Thanks for all the good work
on domoticz.

Op za 12 nov. 2022 08:15 schreef gizmocuz ***@***.***>:
