### ISSUE TITLE
Blyss blind module no longer work after update to version 14536 

### ISSUE THREAD

**Issue by sebitop** [domoticz/domoticz#5362]
Hi Gizmo

just updated the beta 14536 and I have now an issue with my blinds
the command is no longer correctly sent 

![image](https://user-images.githubusercontent.com/99023778/194706219-be6c9e9e-d5d7-4894-900e-0571c943f3d5.png)

blinds are blyss modules (433 mhz) lighting 6 protocol
all worked well until the update done few minutes ago

I remain available if you need any info that could help solving the issue

thanks !
sebastien

**Comment by gizmocuz** [comment]
Thanks for reporting, sorry about that
Please try beta 14537

**Comment by sebitop** [comment]
brilliant
Just perfect it works again !
thanks for your quick answer and update!

(and don't be sorry you do a so big work with domoticz!)

thanks again !
