### ISSUE TITLE
Blind percentage and Blind percentage + stop full open/close not working

### ISSUE THREAD

**Issue by Xenomes** [domoticz/domoticz#5363]
Hi,
Problem with latest Version: 2022.1 (build 14537).
The buttons with Blind percentage / Blind percentage + stop and dzvents script 100% full open/close not working. 
1 to 99 percentage is working.
I have only Shelly plug in to test. No error in the log.
Thanks, Xenomes

**Comment by gizmocuz** [comment]
Thanks for reporting, we noticed this as well.
No idea about the underlying reason yet but it will be under investigation soon

**Comment by Xenomes** [comment]
Thanks! Then i will rollback to previous version.

**Comment by gizmocuz** [comment]
The issue from 1-99 as well as possible gui slider notation issues have been solved in beta 14541

**Comment by Xenomes** [comment]
Thanks for fixing, test it later this day.

**Comment by Xenomes** [comment]
Problem is not fixed.
Turn Debug on:
```2022-10-09 20:26:38.049 Debug: SQLH UpdateValueInt MQTT Discovery Shelly - shellyswitch25-C45BBE798D4F-temp HwID:26 DevID:shellyswitch25-C45BBE798D4F-temp Type:80 sType:5 nValue:0 sValue:61.76
2022-10-09 20:26:38.126 Debug: MAIN SwitchLight idx:664 cmd:Close lvl:-1
2022-10-09 20:26:38.127 Debug: MAIN SwitchLightInt : switchcmd:Close level:-1 HWid:26 sd:26 shellyswitch25-10521CF992EA-0-pos 1 244 62 21
2022-10-09 20:26:38.127 Debug: MAIN SwitchLightInt : switchcmd=="On" || level < 0, new level:80
```

**Comment by gizmocuz** [comment]
No idea what you are sending… level -1?
First try the GUI next some easy dzVents open close actions 
If you use MQTT please publish command line examples and what you expect them to do
Also explain if you are using the default blind or have enabled a reverse option

**Comment by Xenomes** [comment]
Sorry i did not include that. In the gui the close button.
Using Blinds and reverse open/close is on.

**Comment by gizmocuz** [comment]
Yep that does not set a level
You were talking about setting the level to 0 or 100 is that working?

**Comment by Xenomes** [comment]
0 and 100 % no movement at the blinds, a position between 1-99 the blinds go to position.
Edit: same result in dzvent script.

**Comment by gizmocuz** [comment]
Please make sure you are on the latest version and that the browser cache is cleared

**Comment by Xenomes** [comment]
OK I have the latest version of Domoticz installed (on my test system). build 14558 cache deleted.
Full open and close don't work, slider 1-99 works.

```
2022-10-10 20:28:55.232 Debug: MAIN SwitchLight idx:24 cmd:Close lvl:-1
2022-10-10 20:28:55.232 Debug: MAIN SwitchLightInt : switchcmd:Close level:-1 HWid:2 sd:2 shellyswitch25-10521CF992EA-0-pos 24 244 62 13
2022-10-10 20:28:55.232 Debug: MAIN SwitchLightInt : switchcmd=="On" || level < 0, new level:80
```
![Animatie](https://user-images.githubusercontent.com/11648297/194933024-a8787980-a40c-4ceb-9a5c-0c2ea7168e08.gif)

**Comment by gizmocuz** [comment]
Why is your type a Selector switch? And not a general switch that is set to a Blind?
I also suspect that it could be the script that is doing this

Could you try:
- Add a dummy switch, set this type to Blind Percentage
- Now you should be able to set a position and press open close
- Edit the switch and check reverse state 
- Now you should be able to set a position and press open close

![msedge_6WrBAuJ9X7](https://user-images.githubusercontent.com/2265299/195004034-8e83ebc8-1a76-4dce-8f5d-5b418e1a77ae.gif)

**Comment by Xenomes** [comment]
Hi the device is create by the Shelly plugin, but I think the plugin needs update now the blinds is full redesign.
I will try to change the device to general switch and blinds + stop.
Edit:
Dummy works, hardware device changed to the same Type|SubType|SwitchType but the physical blind won't move with open and close commands.

**Comment by Migines** [comment]
Hello, I am also having the same problem, I have version 14585 of Domoticz-beta and I use Shelly 2.5 for the blinds. It works for me at 1% and 99%, but nothing works at 0% and 100%. The icon buttons are not responding. The slider also does not do it when moving it to the limits 0 and 100

**Comment by gizmocuz** [comment]
@Migines , could you post the 'config' topic and payload ?
You can find this with 'MQTT Explorer', should be something like <discovery topic>/cover/xx/yy/zz/...
(with payload please)

**Comment by Migines** [comment]
> @Migines , could you post the 'config' topic and payload ? You can find this with 'MQTT Explorer', should be something like /cover/xx/yy/zz/... (with payload please)

Well, in the end, the problem is not with Domoticz, but with the Shelly plugin. Thanks to a colleague from the Telegram group "Domoticz a lo Spain" it is already solved. I pass github link for those who want the solution while the plugin author does not correct it. You just have to overwrite the "plugin.py" file. Thank you very much https://github.com/juantecnico/Shelly_MQTT

**Comment by Xenomes** [comment]
Thanks for sharing the fix! I will try it tomorrow on my test system.

**Comment by keesdekraker** [comment]
Same issue here with Zigbee blinds from Zemismart. These are picked up as model 'TS0601_cover' in Domoticz.
Implemented a workaround for the time being, using a simple script and a dummy device.
1-99 works fine! open/close, 0% or 100% produces an error (unable to handle command).

Issue is present on both 2022.1 and 2022.2 stable builds as well as beta versions from 2022.
Using Zigbee2MQTT plugin version : v.3.2.0-beta. And Zigbee2MQTT version 1.28.0.
