### ISSUE TITLE
Counter incremental - incorrect time

### ISSUE THREAD

**Issue by Gert05** [domoticz/domoticz#5366]
Thanks for releasing #5344 as a response to issue 5340. It has also solved most of the problems I described in issue 5270.

What remains is a one-hour offset in Domoticz.
Examples:
Event occurred 09:37 - Domoticz shows it as one event in the 08:00 bucket
Event occurred 13:45 - Domoticz shows it as one event in the 12:00 bucket
Event occurred 16:26 - Domoticz shows it as one event in the 15:00 bucket

Events are sent via MQTT to domoticz/in. Currently on 2022.1 (14534). Raspberry Pi.

**Comment by gizmocuz** [comment]
@Gert05 , did you set the correct timezone in the raspberry pi ?
I can imagine that a event from 09:37 will display between 09:00 and 10:00 not 08:00-09:00
In the database everything is correct? It is just the displaying ?

**Comment by Gert05** [comment]
System time on the dashboard is correct; so is the timezone on the Pi.
The entries in the database look OK, so I guess what remains is the way the graph is calculated/displayed. The other thing I notice it that the database entries are at irregular intervals (sometimes 5 min, often different), but that may be standard behavior for Domoticz.
`219	155	0	2022-10-09 00:00:05`
`219	156	0	2022-10-09 09:40:01`
`219	156	0	2022-10-09 09:45:00`
`219	156	0	2022-10-09 09:50:00`
`219	156	0	2022-10-09 09:55:01`
`219	156	0	2022-10-09 10:00:01`
`219	156	0	2022-10-09 10:05:00`
`219	156	0	2022-10-09 10:10:00`
`219	156	0	2022-10-09 10:15:01`
`219	156	0	2022-10-09 10:20:00`
`219	156	0	2022-10-09 10:25:00`
`219	156	0	2022-10-09 10:30:01`
`219	156	0	2022-10-09 10:35:00`
`219	157	0	2022-10-09 13:50:01`
`219	157	0	2022-10-09 13:55:00`
`219	157	0	2022-10-09 14:00:00`
`219	157	0	2022-10-09 14:05:00`
`219	157	0	2022-10-09 14:10:00`
`219	157	0	2022-10-09 14:15:01`
`219	157	0	2022-10-09 14:20:00`
`219	157	0	2022-10-09 14:25:00`
`219	157	0	2022-10-09 14:30:00`
`219	157	0	2022-10-09 14:35:01`
`219	157	0	2022-10-09 14:40:01`
`219	157	0	2022-10-09 14:45:01`
`219	158	0	2022-10-09 16:30:00`
`219	158	0	2022-10-09 16:35:01`
`219	158	0	2022-10-09 16:40:00`
`219	158	0	2022-10-09 16:45:00`
`219	158	0	2022-10-09 16:50:01`
`219	158	0	2022-10-09 16:55:01`
`219	158	0	2022-10-09 17:00:00`
`219	158	0	2022-10-09 17:05:00`
`219	158	0	2022-10-09 17:10:00`
`219	158	0	2022-10-09 17:15:01`
`219	158	0	2022-10-09 17:20:00`
`219	158	0	2022-10-09 17:25:00`
`219	158	0	2022-10-10 00:00:04`

**Comment by gizmocuz** [comment]
Maybe no update was received ? Are you on Slack ?

**Comment by Gert05** [comment]
Not sure what you mean here & no, I'm not on Slack.

**Comment by gizmocuz** [comment]
https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

Please send me a private message with the link to this issue

**Comment by gizmocuz** [comment]
@Gert05 , could you try beta 14560

**Comment by Gert05** [comment]
First test is not looking good. I've loaded beta 14564 on my testsystem (Docker). I've fired off an MQTT counter increase at 10:12, but it shows as an increase at 0:00. I'll do some further testing today.
![image](https://user-images.githubusercontent.com/12745187/195039547-2d6f0e20-dca0-4266-9517-6f91c18f37e3.png)

**Comment by Gert05** [comment]
Second counter increase at 10:31 works OK, shown in the correct time bracket. So I guess the problem lies with the first event of the day.
![image](https://user-images.githubusercontent.com/12745187/195041277-2791f531-1a4f-4543-8465-220eb7eaae8c.png)

**Comment by gizmocuz** [comment]
okey let me check that....

**Comment by gizmocuz** [comment]
Mine starts at 8.40 and displays correctly at 8, I think there is always a value at 00:00:00 , the last value of the previous day, could you check in your database?
Else contact me on slack please
