### ISSUE TITLE
Dimmer set to 0% when off

### ISSUE THREAD

**Issue by vespino** [domoticz/domoticz#5367]
I have posted this before: https://github.com/domoticz/domoticz/issues/5329

Version: 2022.1 (build 14552)
Platform: Docker
Plugin/Hardware: Synology
Description: Now the issue seems to be reversed. When a dimmer is turned off by a blockly event, the percentage is set to 0%. I use a virtual dimmer for controlling the volume of my Sonos speakers (via a PHP/API) and setting the percentage to 0% results in the speakers being turned all the way down.

**Comment by gizmocuz** [comment]
When you set the volume of a speaker to 0% it results in the speakers to be turned all the way down?
Makes sense to me?

Is this still related to the issue that when you set the volume to 30% and turn it off, and pressing the on button it sets 0%?

**Comment by vespino** [comment]
I use the virtual dimmer to control my speakers (on/off/volume). An analog dimmer (those found on a wall) has 2 options: on/off and value 0-100. When I press it, the on/off status toggles, but the value keeps as set. In this case, the value is set to 0. When I turn on the dimmer again, the value is not restored. Do you understand the difference?

I don't know if this issue is related to the one I posted before, but it does seem similar.

**Comment by gizmocuz** [comment]
Sorry it is still a bit unclear, please explain step by step what you do and what you expect

**Comment by vespino** [comment]
Firstly: a blockly event triggers my virtual switch to "off". Before turning to off, the level is e.g. 5%.

Secondly: the API triggers my virtual switch to "on". It used to keep the 5% setting, but in the current version of Domoticz, it's set to 0%.

More clear?

**Comment by gizmocuz** [comment]
Yep, and If you do this via the GUI ? Directly setting the speaker level to 5%, then off, then on ?

**Comment by vespino** [comment]
It keeps the level setting.

**Comment by gizmocuz** [comment]
Is it a dzVents script, and if so, could you post it here?
What is unclear is that you have a speaker and a virtual switch, how is the percentage of this switch converted to the speaker ?

**Comment by vespino** [comment]
No worries about the speakers, my PHP script reads the setting using the API. I created the virtual dimmer to control my Sonos speakers using Domoticz. Using a dimmer allows me to turn if on/off and also control the volume. When the virtual dimmer is controlled, a PHP script is executed which reads the setting using the API.

I use the built-in events system (settings > more options > events).

**Comment by gizmocuz** [comment]
Yes but in the events you can use blockly/lua or dzVents, if it's dzVents (text based script) could you post your script here ?
It reads the settings... from Domoticz ? Via a HTTP JSON call ? So it knows the current dim level ? And can that script also use the HTTP JSON API to set the requested dim level ? The last dim level should be in the LastLevel field returned from the JSON API
But maybe you use a dzVents script to turn something on/off/setlevel

**Comment by vespino** [comment]
I'm using blockly.

The script gets its data via HTTP JSON, but when the dimmer is turned off, the level is set to 0%, but there's nothing to get. I don't see "LastLevel" in the response btw.

**Comment by gizmocuz** [comment]
I see, yes, but you see 'Level"

http://127.0.0.1:8080/json.htm?type=devices&rid=140

where 140 is the idx of your speaker

```
			"Level" : 66,
			"LevelInt" : 66,
			"MaxDimLevel" : 100,

```
![image](https://user-images.githubusercontent.com/2265299/194890194-15486ab7-3c9e-42f3-b3d0-b605653f58f8.png)

**Comment by vespino** [comment]
Level is there, yes, and it's set to 0 when blockly turns off the dimmer.

**Comment by gizmocuz** [comment]
Okey that's good to know, because it is not when doing this from the web interface on the device itself...

**Comment by vespino** [comment]
Correct. A bug in Blockly then? Have been using this for quite a while now, no issues, but as of recently all my dimmers (not just this virtual one) are set to 0 when turn off by Blockly.

**Comment by gizmocuz** [comment]
Yep seems like it, but should now be solved in beta 14553

**Comment by vespino** [comment]
Haven’t been able to test the full workings, will try tomorrow. Did notice another thing: when turning the dimmer off with the help of a timer, the level turned to 100% which looks like the issue I had before.

**Comment by gizmocuz** [comment]
Please try beta 14559 this should fix that as well

**Comment by vespino** [comment]
Dimmers are now set to 40% when turning them off.

**Comment by gizmocuz** [comment]
@vespino , yes they keep the last level.... so thats good or not ?

**Comment by vespino** [comment]
No because the dimmers in question were set to 10%.

**Comment by gizmocuz** [comment]
thats not possible, try again, set the speaker to 40%, press OFF then ON

**Comment by gizmocuz** [comment]
Next add a dummy TEST_SWITCH switch and create the following dzVents script
(you need to change the id's of the below two devices)

```
local TEST_SWITCH = 7939
local Speaker_Switch = 8254

return {
	on = {
		devices = {
			TEST_SWITCH
		}
	},
	logging = {
		level = domoticz.LOG_DEBUG,
	},
	execute = function(domoticz, item)
            if (domoticz.devices(TEST_SWITCH).state == 'On') then
                domoticz.devices(Speaker_Switch).switchOn()
            else 
                domoticz.devices(Speaker_Switch).switchOff()
            end
	end
}

```

Now when you flip the test switch it should turn on/off the speaker but the level should stay the same

**Comment by gizmocuz** [comment]
And now also tested with blockly

![image](https://user-images.githubusercontent.com/2265299/195017849-3acfe842-7621-4513-9b0e-12f72c1205f2.png)

**Comment by vespino** [comment]
I set one of my dimmers to 6%, turned it off and it moved to 40%. This is using the UI.

![afbeelding](https://user-images.githubusercontent.com/6991325/195017804-aaca2028-82aa-42e0-a4f2-953ef794ddcd.png)

**Comment by gizmocuz** [comment]
The "Level" is relative (0-100%), the LevelInt(6), based on MaxDimLevel (15) is the same

(100/15)*6 = 40

**Comment by gizmocuz** [comment]
And you did not mention how you set the level... not with the GUI I assume now?
What call do you use to set the level ?

**Comment by vespino** [comment]
I did use the GUI in this case. Set the dimmer to 6%, turned off the dimmer and it changed to 40%:

![6procent](https://user-images.githubusercontent.com/6991325/195019017-1d2ae783-f950-457d-94de-8e118359589b.png)

![off](https://user-images.githubusercontent.com/6991325/195019037-b8af9b15-d038-41f2-92fd-a6937d8de453.png)

These are real dimmers, not virtual ones btw. The virtual dimmers keep their setting.

**Comment by gizmocuz** [comment]
Ahhh make sense, okey then maybe it is because I use a dimmer that I created from a dummy switch that has a level from 0-100
Let me debug/test this now

**Comment by gizmocuz** [comment]
Okey this is not right ideed

**Comment by gizmocuz** [comment]
Please try beta 14562, that should solve the issue

**Comment by vespino** [comment]
Thanks, 14564 seems to have solved all my issues.

**Comment by gizmocuz** [comment]
Very good! thanks for the feedback!

**Comment by vespino** [comment]
One more thing: I have a number of smart bulbs that also show this issue. Not all of them, for example Xiaomi doesn't, but Tuya does.

Related?

**Comment by gizmocuz** [comment]
@vespino , if it's not solved, you need to explain your situation down to bit level please...
What hardware, switch type, what are you doing, what do you see, what do you expect .....

**Comment by vespino** [comment]
The smart bulbs basically function like a dimmer (on/off/level). When I set a Xiaomi bulb to 40% and turn it off, it keeps this level. When I do the same with a Tuya bulb, level is set to 0% I'd expect it to also keep its level in the GUI.

Xiaomi:
![xiaomi](https://user-images.githubusercontent.com/6991325/195049793-a33d026e-a876-4f36-94c6-1fb8a8c24bd5.png)

Tuya
![tuya](https://user-images.githubusercontent.com/6991325/195049829-3f3b8a3b-cf29-446a-aceb-db67d98f2188.png)

**Comment by gizmocuz** [comment]
What hardware type in domoticz? Maybe it receives 0 from your hardware?

**Comment by vespino** [comment]
Yeelight and Tuya, is that what you are referring to?

**Comment by gizmocuz** [comment]
How do you get your Tuya in domoticz ?

**Comment by vespino** [comment]
https://github.com/Xenomes/Domoticz-TUYA-Plugin

**Comment by gizmocuz** [comment]
This might be a plugin issue. If a other type of bulb (not this plugin) and dummy light/switches are working fine i would look for some changes in this plugin

**Comment by vespino** [comment]
But the plug-in hasn’t changed, Domoticz changes all the time. Don’t know, I’m not the expert.

**Comment by kiddigital** [comment]
> But the plug-in hasn’t changed, Domoticz changes all the time. Don’t know, I’m not the expert.

That is why there is a Beta channel, so we can have a lot of changes and keep moving forward. 😁

And Stable is called that for a reason 😉

**Comment by gizmocuz** [comment]
If you can't wait, maybe reflash your devices with Tasmota version 11, enable the HA MQTT auto discovery option

**Comment by vespino** [comment]
> If you can't wait, maybe reflash your devices with Tasmota version 11, enable the HA MQTT auto discovery option

I have not idea why I should do this or how to go about this, so I’ll leave it the way it is since the only device that’s “bothering” me I control only via voice commands.
