### ISSUE TITLE
Incorrect comparing month value

### ISSUE THREAD

**Issue by enboer** [domoticz/domoticz#5368]
See the picture, in the comparing graph the value for september is 503kWh. If I look at the data in the database and sum those up it is 881 kWh. Any idea why this is and how I can fix it ?
In the picture you see the data in the database, the sum calculation in Excel and the graph in Domoticz.
I am using 2022.1 on a Raspberry PI and checked on differint webbrowsers.

![ComparingValue](https://user-images.githubusercontent.com/47273942/195119778-fe8a8576-8b2b-484f-84ee-4accab154269.jpg)

**Comment by waltervl** [comment]
How is your counterdata created? scripting, manual, plugin, domoticz integration?
Seems that the data is not correct. In the below screenshot of my database you see that the counter value  in column Counter is rising with the delta in column Value.
In your database Value=Counter and that seems incorrect.
![Selection_169](https://user-images.githubusercontent.com/16327072/195447594-dbe5b3a8-0904-4d7f-9cdb-e3590e89e1be.png)

**Comment by gizmocuz** [comment]
What 'type' of counter is this ? A normal counter, managed counter, counter incremental or another?

**Comment by enboer** [comment]
This is a normal counter. I think the issue is that I read my solar inverter every hour to get the data. However as it is daily data it starts at 0 every day. Looks like that is the issue here. As I also read the total generated energy as well, that is ok, but that stores the value with an increasing counter.
I also tried a managed counter, but I cannot get data into the history. I store this data: 810.0;660.0;2022-10-13 09:55:07 but this does not work. Value are: total;incr;datatime. Any idea what I do wrong here ?

**Comment by waltervl** [comment]
You should only read the total generated energy (per 5 min if necessary) Domoticz will do the daily calculations for you.

What kind of solar inverter do you have as there are a lot of plugins, scripts and integrations already available.

**Comment by enboer** [comment]
It is a Huawei KTL10 inverter. I directly read data via the modbus. So setting the counter daily  to 0 is not supported by the counter?
What about the managed counter, why this does not work?

**Comment by waltervl** [comment]
All counters work with a cumulative counter value. So if the inverter is not giving it you should calculate it based on previous counter value and add the delta.

I personally never got managed counter do what it should do.

There are some scripts for Huawei inverters out there. Unfortunately no plugin or direct integration.

Perhaps sma inverter modbus plugin https://github.com/derenback/Domoticz-SMA-Inverter could give some inspiration.

**Comment by gizmocuz** [comment]
The managed counter is explained in our wiki here:

https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Managed_counter

As you can read there are two options to update the counter
- using date only (once a day)
- using date-time (for the shortlog, like every hour)

Counter values are always increasing

If your 'counter' value is the difference between the last reading and current reading (thus not always incrementing), you could use the counter-incremental type

**Comment by waltervl** [comment]
Closing this issue, no more updates.
