### ISSUE TITLE
On / Off displayed values on planning array are inverted

### ISSUE THREAD

**Issue by bubu26** [domoticz/domoticz#5369]
https://github.com/domoticz/domoticz/blob/b4a83674fd01622af6ed156bd758baf2bbf773af/www/app/timers/components.js#L256

Switch Device => Planning :
On => displayed Off in array "Command" column
Off => displayed On in array "Command" column

I suppose need to replace :
  var txtOn = (vm.isBlind) ? 'Open' : '**Off**';
  var txtOff = (vm.isBlind) ? 'Close' : '**On**';
to : 
  var txtOn = (vm.isBlind) ? 'Open' : '**On**';
  var txtOff = (vm.isBlind) ? 'Close' : '**Off**';

**Comment by bubu26** [comment]
It's because I installed plugin https://github.com/syrhus/domoticz-weekly-planning (strange)

**Comment by bubu26** [comment]
After testing, it's no linked to domoticz-weekly-plugin then reopen ...

**Comment by gizmocuz** [comment]
@bubu26 , thank you for reporting. Fixed in beta 14566
