### ISSUE TITLE
Tuya WiFi blinds do not respond to domoticz switch instruction after update

### ISSUE THREAD

**Issue by MarcelBaas** [domoticz/domoticz#5370]
Goodmorning,

At least since update build 14549 (but probably 2 beta updates earlier) the blinds in the bedroom do not respond at all to the switches in domoticz. Before this was working fine. The inplemented units in the curtains are WiFi types. What i've tried sofar:
- Delete all the tuya blinds switches from domoticz. They come right back into the list with auto discover. Meaning the switch are found by the plugin
- switched on all debugging. Unfortunatly the only message that is logged is the actual switch command when i press one of the switches
![image](https://user-images.githubusercontent.com/52255154/195564936-0194ae3c-01c0-4897-b8de-ec2286fb7385.png)

The switches in Domoticz:
![image](https://user-images.githubusercontent.com/52255154/195565096-c2e013c5-800d-43b0-9635-5949753ca0a5.png)

Any clue what the issue might be?

**Comment by Rouzax** [comment]
What is the version you are right now?
Please make sure you upgrade to the latest beta. There have been many changes to the Blinds device type over the past week.
On the Latest Beta there is no longer an Inverted Blind, but you will have additional options per blind to recreate any behaviour you want.

See https://github.com/domoticz/domoticz/issues/5359#issuecomment-1274347465 for a more detailed explanation

**Comment by MarcelBaas** [comment]
Hi Ruazax. Sorry had to mention that I'm running Version: 2022.1 (build 14566) at the moment. Accoording the update option this should be the latest version. 
There is nothing special to the switches. No investion just open and close. 
I changed one of the switches to the description in the issue you mentioned. Unfortunatly nothing changes. There is zero responds to the switch. Also i see that the slider does not respond to the click-action on the open or close button.

Just a question. You want me to close this issue eand continiue in the [#5359 ](https://github.com/domoticz/domoticz/issues/5359#issuecomment-1274347465)  issue?

**Comment by Rouzax** [comment]
Then I'll leave it to the professional 😄 I would keep it as a separate issue.

What are you using to control the Tuya blinds in Domoticz?

**Comment by gizmocuz** [comment]
@MarcelBaas , I would like to ask for a few parameters/details to be able to debug this
Please make use of MQTT Explorer (or similar)

The MQTT topic of the config object for this blind, and also the payload of the config

Are you able to control the blind outside Domoticz (open/close), so it will send an update to MQTT?
If yes, could you post the position/state topic and also the payload when this happens?
You can find the state/position topic by looking into the config object
I suspect there could be a issue as this blind does not have a position but only a open/close

**Comment by nakamal22** [comment]
Lo,

I have same issue with zigbee blind with all beta versions I have tested for the 8 last days
I succeeded to make it work again by modifying deCONZ plugin

It seems domoticz since more than a week send command "Open" and "Close" when you click on blind in dashboard and lightswitches panels

Before, domoticz sent "On" or "Off" command which is what is waiting deCONZ plugin
I added this workaround to deCONZ plugin.py waiting for domoticz correction : 

line 274 : if Command == 'On' or Command == 'Close':
line 286 : if Command == 'Off' or Command == 'Open':

Probably same workaround can be applied to wifi blind if domoticz uses a plugin for that

**Comment by MarcelBaas** [comment]
@gizmocuz,

Thx for looking into it (u2 btw Rouzax :-) )

I know the MQTT explorer (app and windows version) very usefull tool. Also when one is programming a ESP :-). The capture would be (sadly) empty in this case. I see a lot of info in the explorer. Dahua doorbel, zigbee2mqtt messages, homemade ESP-blind messages, Evohome messages. But nothing that points to tuya.

This is what i sniffered:
Switch used: 
![image](https://user-images.githubusercontent.com/52255154/195841575-cdd6a02d-7dfc-4339-b46f-2bca7506be6c.png)

In the settings we'll find the corresponding Idx: 1541
![image](https://user-images.githubusercontent.com/52255154/195841749-e27cfc60-5485-4197-8ea2-7d7877832d7c.png)

MQTT explorer without filter
![image](https://user-images.githubusercontent.com/52255154/195842485-0098ff47-a8fc-41d0-8939-cfb2714429e9.png)


If i set the filter in the MQTT explorer to 1541 messages that have a matching number somewhere should be shown.
Next step is to "press" a couple of times at the switch... see the result below
![image](https://user-images.githubusercontent.com/52255154/195842623-60de9028-cef1-4d9f-bd49-900385d993f9.png)

To be honest i'm not sure if Tuya is using MQTT. I use a plugin "tuyaha" that connects to the webapi from TUYA.  But ik looks like the connection to the web api fails. 
The messages arive at domoticz. However they are not put through to the plugin?....

@nakamal22,

Thx for the gesture. I'll have a look into the plugin see if i can implemend a look a like workaround. 

Let you all know later if i succeeded

Cheers

**Comment by MarcelBaas** [comment]
> 

Could'nt wait. So i just had a quick check in the plugin.py inside the tuyaha directory. Eureka @nakamal22 thx a lot. That did the trick 🗡️ 

@gizmocuz for your info yes it does something with MQTT :)
![image](https://user-images.githubusercontent.com/52255154/195846266-ad9ee7ef-18e1-4097-b079-14c2d7277077.png)

Hope it helps finding the final solution for this.

**Comment by gizmocuz** [comment]
@MarcelBaas , did you change the plugin to use the Open/Close commands instead of the Off/On commands?
If yes, then this is the solution

In your MQTT broker there should be a auto discovery topic (most times homeassistant), in there I would expect all the config objects (same for zigbee2mqtt).

Bdw, All your Zigbee2MQTT devices are working correctly in Domoticz?

Ps. What I see in your last image above is normal MQTT communication from Domoticz (in/out topic)

**Comment by MarcelBaas** [comment]
> @MarcelBaas , did you change the plugin to use the Open/Close commands instead of the Off/On commands? If yes, then this is the solution
> 
> In your MQTT broker there should be a auto discovery topic (most times homeassistant), in there I would expect all the config objects (same for zigbee2mqtt).
> 
> Bdw, All your Zigbee2MQTT devices are working correctly in Domoticz?
> 
> Ps. What I see in your last image above is normal MQTT communication from Domoticz (in/out topic)

@gizmocuz, I added the Open and Close as suggested by nakamal22. Meaning the on and off are still in the plugin but a "or"statement in the lines are added with a "open"  and a "close" command. 
If this is the solution then that would mean that the tuyaha plugin needs an update since i cannot believe that i'm the only IoT fan that has this issue after the update :).
Would it be an good idea to open a ticket on the tuyaha plugin git and request an update of the plugin there?

Then regarding the Zigbee stuff in the house. They are working fine :)

Last item, to the ps: That is correct however without the change in the plugin code the line fot idx:1541 never occured in the MQTT domoticz/out topic

If you want we can close this issue since everything seems to work again on my side :D

**Comment by gizmocuz** [comment]
Thanks for the feedback! Yes it's best if the plugin could be updated to handle the new 'Open' and 'Close' commands for blinds
