### ISSUE TITLE
Position of blinds icons in UI not logical after recent update

### ISSUE THREAD

**Issue by lokonli** [domoticz/domoticz#5372]
With the recent Domoticz update the blinds behavior changed.
New behavior:
100 = Blind Open in GUI/dzvents
In this case the slider is in the utmost right position.

However, in the UI the left icon is blinds open icon, and the right icon is the blinds close icon.
The behavior is ok, also the correct icon is activated, only the position on the UI is not logical.

It would be more logical if we switch the icons from position.

![image](https://user-images.githubusercontent.com/22852111/196052810-cbb54f8e-2697-4ce2-96ea-442ecab2f5ed.png)

**Comment by gizmocuz** [comment]
Well it has been like this since the beginning, and I find this quite logical.
There are also blinds without percentage and also here I find the icon positions logical
