### ISSUE TITLE
Error sending switch command, with virtual selector and scripts

### ISSUE THREAD

**Issue by ldrolez** [domoticz/domoticz#5378]
DOMOTICZ 2022.1 (build 14578)

I have a virtual selector, with scripts behind: only the action with level 0 is executed, other values cause the error: Error sending switch command, check device/hardware (idx=111) !

Nothing is logged when the error occurs.

Even if I clear the script for level 10, I get the same error, so it's not script related.

![2022-10-27 12_53_49-Domoticz](https://user-images.githubusercontent.com/2277898/198266310-65cd4faf-0147-4340-ae79-ccd9629ed10c.png)

**Comment by waltervl** [comment]
This is not something for github, it should be a forum topic (https://www.domoticz.com/forum/) but what if you remove level 0?

**Comment by ldrolez** [comment]
I've made traces in the code and it's really a bug, not a question :)

**Comment by waltervl** [comment]
Then it would be wise you share your code changes in a PR if it fixes the issue.
Edit: reading back I see I misread traces for changes.

**Comment by waltervl** [comment]
Additional, when quickly checking level 0 is associated with Off and there is also a special option in Edit for show/hide level 0.
So level 0 seems to be special. So please show more definition as it seems you hit a "bug"or an as designed feature you can workaround easily without code changes.....

**Comment by gizmocuz** [comment]
You might want to post your script here as well
GUI works fine?

**Comment by waltervl** [comment]
I could not test with a script but using http jsons works fine on setup like in my screenshot below. Renamed level 0 from Off to test1
![Screenshot_20221027-214941-984](https://user-images.githubusercontent.com/16327072/198385131-04ddbe7a-c032-496b-a4ff-9c722345fddd.png)

**Comment by ldrolez** [comment]
Ok my bad, using a virtual 'selector switch' instead of a switch works better
