### ISSUE TITLE
Off Delay not handled for Selector switch

### ISSUE THREAD

**Issue by gaudryc** [domoticz/domoticz#538]
While testing the patch #537 I saw that Off delay (30s) was taken into account but was fired after 90s that is to say the value of the On Delay.

**Comment by cherowley** [comment]
Cheers :)

**Comment by gaudryc** [comment]
@gizmocuz ,

I'm modifying MainWorker::SwitchLight and CEventSystem::ScheduleEvent methods to handle the switch selector but it seems that other devices don't handle Off delay (these methods add On delay only if the switch command is "On" or something similar.

Am I right ?
