### ISSUE TITLE
P1 Usage last 7 days chart is broken after upgrading to latest beta

### ISSUE THREAD

**Issue by fwieringen** [domoticz/domoticz#5382]
Hi,

Just upgraded to the latest beta. It appears that the Last 7 days chart is not displaying correctly. All data is in the DB, however the chart shows this:

![image](https://user-images.githubusercontent.com/4232879/198865959-69209e3a-1047-4af8-9eb9-6c889ec35212.png)

I think this has somthing to do with the fact that daylight saving occured this night... So perhaps the link with the latest beta is a wrong assumption...

Best regards,
Friso

**Comment by gizmocuz** [comment]
I suppose it is a wrong assumption

**Comment by fwieringen** [comment]
So... shall I create a new issue regarding the daylight saving chart?

**Comment by gizmocuz** [comment]
You could do that, but best to debug the issue and submit a PR to solve this.
As you hover with you mouse int the chart you will see a popup with correct values, if you enable the 'Energy Usage' you will also see this.
So it is probably a rendering issue.
Have you looked at the data returned from the JSON call that the graph is requesting?

**Comment by fwieringen** [comment]
I will check if I can solve it myself, although I'm not very familiar with C++.

**Comment by gizmocuz** [comment]
`http://<ip address>:8080/json.htm?idx=1768&range=day&sensor=counter&type=graph`

I noticed some big values here, will try to debug as well...

**Comment by gizmocuz** [comment]
@fwieringen , Should be solved in beta 14588

**Comment by fwieringen** [comment]
Cool! That was fast 😎 will install when I get home later today.

**Comment by pipiche38** [comment]
looks like I had the same issue at 2am today ( day light saving time)

**Comment by gizmocuz** [comment]
@pipiche38 , probably a lot of people but it's already mentioned here and solved

**Comment by fwieringen** [comment]
Hi! Also noticed the check on the day graph for values >100k. Would it be possible to set it a bit higher?

Example: had a construction dryer in my room in feb. Used about 120 kWh per day...

![image](https://user-images.githubusercontent.com/4232879/198952585-99cfd331-1c4b-422b-b8cc-0bea353f5abb.jpeg)

Thanks 😉

**Comment by gizmocuz** [comment]
@fwieringen , sure no problem to change, but this is for the 'short-log' (5 minute interval), not the day/week/month/year graph
Assuming voltage is 230V, max Watt is 100.000, means a total fuse of 100000/230=435A ... I think 100.000 is a bit on the high side actually but as it was already there, I kept it
