### ISSUE TITLE
Docker Beta tag named 2021-beta.xxxxx instead of 2022-beta.xxxxx

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#5386]
Something happened around 9 October to switch the tag name from 2022-beta.xxxxx to 2021-beta.xxxxx which is incorrect. See screenshot below.

![image](https://user-images.githubusercontent.com/16327072/198967400-e5a150c7-bd49-4ae6-b82b-f20e2c1e2c7a.png)

**Comment by gizmocuz** [comment]
Yes, someone created a invalid PR and I reverted this... going to solve this!
