### ISSUE TITLE
CMake files do not check correct .git directory

### ISSUE THREAD

**Issue by irimitenkan** [domoticz/domoticz#539]
During build CMakeList.txt and getgit.cmake check with `git  rev-list HEAD --count` etc. the recent version of domoticz. If the .git directory is not available the `appversion.default` shall be used.

But in some build environments (e.g. openwrt) it is possible the build process will find a .git directory from a foreign repository.
Hence the complete domoticz version info is wrong (based on foreign repository) since the git call does not use `--git-dir ./.git` option.

**Comment by gizmocuz** [comment]
Please make a pull request

**Comment by irimitenkan** [comment]
Has been fixed with merge #548
