### ISSUE TITLE
remove hardware "GoodWe solar inverter via Web API"

### ISSUE THREAD

**Issue by JanJaapKo** [domoticz/domoticz#5393]
The hardware "GoodWe solar inverter via Web API" isn't working for quite some time. As a replacement I'm maintaining a python plugin "GoodWe solar inverter via SEMS API". So please remove the C-based HW module as it leads to confusion.

**Comment by kiddigital** [comment]
@JanJaapKo , thank you for creating and maintaining a Python plug-in that works well.

Do you know what is wrong with the current C++ version?

Would it be useful to update the build-in module? For people and setup's that do not use/run Python.

I agree that if the current module does not work anymore, we need to take action. Either fix it or remove it.

**Comment by gizmocuz** [comment]
I prefer to have the native hardware fixed as this does not require python,
Maybe you could help solve the issue ?
What seems to be the issue ?

**Comment by gizmocuz** [comment]
I noticed there are multiple GoodWe plugins

https://github.com/remco-k/domoticz-goodwe-modbusudp-plugin/

**Comment by JanJaapKo** [comment]
Well I picked up the Python version from someone else since when I got my panels, there was already a forum saying that the native implementation did not work. So I never investigated what exactly is wrong with the native HW module, mainly due to lack of C knowledge, plus the fact that Python plugins are much easier to debug than C as they do not need a recompile. What I seem to remember is that Goodwe at some point updated their authentication. Later, I added also quite some other data to it plus exception handling.

And yes there are indeed 2 versions: one via the web API provided by Goodwe (which always works as long as you have internet connection) and one that directly accesses the inverter on your LAN (this requires a minimum firmware level which is standard since about early 2021 so older models do not have this and some models are equipped with 4G modems instead of Wifi).

As for updating the native one: I propose to stick to the web based one. Despite the fact that going via the Goodwe server may not be optimal, it works for all inverters.

Forums:
[Goodwe via SEMS API](https://www.domoticz.com/forum/viewtopic.php?t=28983)
[Python plugin for Goodwe - local lan via udp](https://www.domoticz.com/forum/viewtopic.php?t=37886)
Github:
[domoticz-GoodWeSEMS](https://github.com/JanJaapKo/domoticz-GoodWeSEMS)
[domoticz-goodwe-modbusudp-plugin](https://github.com/remco-k/domoticz-goodwe-modbusudp-plugin)

I'd love to help out, but as said: limited C/C++ knowledge. Obviously I understand the basics but I guess there is a bit more than just basic programming in there....

**Comment by gizmocuz** [comment]
I think the code/class itself is extreme minimal and not so hard to make a patch against....
Sometimes python is more complicated than 'c'

**Comment by MikeyMan83** [comment]
Any plans to fix this one?

**Comment by gizmocuz** [comment]
@MikeyMan83 , please try to fix it. I won't do this, I don't have this hardware

@JanJaapKo , not on every hardware platform there is room to install python, or the python installed is extreme old and minimal
A native implementation solves this problem.

**Comment by JanJaapKo** [comment]
Hey @gizmocuz ,

Basically I would say that for all commonly used hardware (like zigbee, zwave, smartmeter etc) there should be a native implementation. For the Goodwe solarpanel inverter, I would say the need is lower. For those interfaces the plugin framework works really well. This is also how for example Home Assistant works. Although I was not aware of the limited python packages on some OS's.

Still the way to make a C/C++ hardware driver is something I'd need to dive into for which I lack the time at the moment. To limit confusion: can the native hardware be disabled from the list somehow?

**Comment by MikeyMan83** [comment]
@JanJaapKo think i agree. Main issue is that there is a plugin in the list. Might be best to delete.
The plugin you created works really well.

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/pull/5634

**Comment by waltervl** [comment]
Closed by https://github.com/domoticz/domoticz/pull/5634
