### ISSUE TITLE
Blind + Stop inconsistancies EnOcean

### ISSUE THREAD

**Issue by didi31** [domoticz/domoticz#5395]
I have enOcean USB (ESP3) hardware which created the "Volet cuisine" device.
domoticz.devices("Volet cuisine").state  = "Open" and domoticz.devices("Volet cuisine").level  = 100
The GUI shows the picture of the device "open" active and the slider is on the left side.
![image](https://user-images.githubusercontent.com/46863073/200346387-8fc1f351-f977-491b-b962-b76282581881.png)

I enter the following code in dzvents
**Problem**
I enter the code below:
`domoticz.devices("Volet cuisine").close()`
The blind is closed but dzVents return the following:

- domoticz.devices("Volet cuisine").state  = "Open"
- domoticz.devices("Volet cuisine").level  = 0

The GUI shows 
- the picture of the device "open" active
- the slider is on the left side
- the state is shown at 0%

If I execute the same code again, all is fine
The GUI shows 
- the picture of the device "Closed" is active
- the slider is on the right side
- the state is "Closed"

Now I execute the following code:
`domoticz.devices("Volet cuisine").open()`
The blind is then opened but the slider is on the right side.
![image](https://user-images.githubusercontent.com/46863073/200346226-4ca73871-7f53-4709-966a-5d64adee5b47.png)

**Comment by didi31** [comment]
From the previous state:
domoticz.devices("Volet cuisine").state = "Open"
domoticz.devices("Volet cuisine").level = 100
domoticz.devices("Volet cuisine").lastLevel = 0

if I click on the "Open" button, the slider move on the left side and dzVents return the following:

domoticz.devices("Volet cuisine").state = "Open"
domoticz.devices("Volet cuisine").level = 100
domoticz.devices("Volet cuisine").lastLevel = **154**

**Comment by walawa75** [comment]
Hi,

Same issue here with Zwave devices. I confirm too that this new stable version is very buggy and unusable. I rolled back to beta (stable and usable)

**Comment by kiddigital** [comment]
> Hi,
> 
> Same issue here with Zwave devices. I confirm too that this new stable version is very buggy and unusable. I rolled back to beta (stable and usable)

Zwave in general or are you referring to Blinds specifically?

Did you look at [this](https://domoticz.com/forum/viewtopic.php?p=293724) forum thread?

Did you read the [wiki](https://www.domoticz.com/wiki/Blinds)?

Does Domoticz crash? Or just behave different than you expected? How does 'buggy' manifest itself?

**Comment by walawa75** [comment]
There is no crash but all is inverted between open/close state specifically with blinds. Commands are also inverted. If i send a close command I get an open one and vice versa. So my scenarios are a joke now !! They close the blinds the morning and open it for the night !!
Panel command shows slider on the left with "closed" attribute and when blinds are closed slide is on the right with "open" attribute.
All is wrong !! The roll back to beta 2022.1 14498  is working perfectly without these issues.

Please correct the bugs.

**Comment by didi31** [comment]
My issue is different.
I activated the 2 new options "Reverse open/close state" and "reverse position" before.
![image](https://user-images.githubusercontent.com/46863073/200375993-928c5809-a2bc-4a1e-8476-25f2824c88a6.png)
@walawa75 did you try this?

**Comment by walawa75** [comment]
> @walawa75 did you try this?

Yes, it is worse :-)

All was working well before without activating some options

**Comment by kiddigital** [comment]
@walawa75 , do you use reversed blinds in your working setup?

**Comment by walawa75** [comment]
@kiddigital . No and I never used it before.

**Comment by didi31** [comment]
@walawa75 There is a big work done on the management of the blinds. You should try to do it :)

**Comment by veitk** [comment]
and i thought i was the only one. since around 6-8 weeks or so my zwave blinds are completely messed up and whatever i select in the settings - it is not working correctly anymore like it did the last 3 years.

**Comment by walawa75** [comment]
> and i thought i was the only one. since around 6-8 weeks or so my zwave blinds are completely messed up and whatever i select in the settings - it is not working correctly anymore like it did the last 3 years.

No, it's just the domoticz team playing with the code (we don't know why anyway)

I feel I will stay under beta 2022.1 14498 for a long time

**Comment by GravityRZ** [comment]
i think the domoticz team opened a can of worms when they started changing this a couple of months ago
i think it started when there was something not correctly detected with MQTT.

The problem is that there and then it was decided what should be right(logical) and what should be wrong(unlogical)
maybe they we should have asked all domoticz users(poll) about their logic and go for the functionality which is experienced as logical by most users.

it is like changing the rules on traffic lights(red=go, green is stop) this makes no sense to people.

even if it makes sense then still you should think about the concequenses
Switching the red light to the bottom and the green light to the top seems much saver because you can always see the bottomlight better so you should think it is a better/saver choice but i can tell you people are going to die when we do this.

I am not choosing sides and i recently discovered that my blinds(RFXCOM/RFY) are affected by this as well)
the sunscreens came down at 20:00(script) instead of going up.
i changed both parameters and now they seem to work again. i do not have/use the slider so that makes things less complicated in my situation

hopefully this will be fixed soon  because it must be eating up a lot of time of the domoticz team.
These people do hard work(mostly unpaid) so they have my eternal respect. sure  they can break something in the process but it is never intentional and somehow they always fix things

**Comment by GravityRZ** [comment]
found this regarding domoticz 2022.2 release

[https://www.domoticz.com/forum/viewtopic.php?t=39291](url)
and this about the blinds
[https://www.domoticz.com/wiki/Blinds](url)

**Comment by didi31** [comment]
You should use the forum.

**Comment by GravityRZ** [comment]
i am trying to help but YOU are telling ME to use the forum!!!

PLEASE READ AGAIN.
I am pointing YOU to the forum

**Comment by didi31** [comment]
The original topic describe a bug in Domoticz.
@GravityRZ As far as I understood the rules, the forum is the dedicated place to discuss on how to solve problems.
If you did not succeed to solve your problem because it is a bug, you go to Github and declare it.
It is what I did.

**Comment by didi31** [comment]
@GravityRZ 
`### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)`

**Comment by walawa75** [comment]
> found this regarding domoticz 2022.2 release
> 
> [https://www.domoticz.com/forum/viewtopic.php?t=39291](url) and this about the blinds [https://www.domoticz.com/wiki/Blinds](url)

First really usefull informations in this post. I will explore that , thank you !!

**Comment by didi31** [comment]
@walawa75 Please follow the rules of github above and create a topic in the forum. However these informations have been already given by @kiddigital 2 days ago.

**Comment by walawa75** [comment]
> @walawa75 Please follow the rules of github above and create a topic in the forum. However these informations have been already given by @kiddigital 2 days ago.

Gloops, sorry.

**Comment by GravityRZ** [comment]
@everybody

please clear all the cache from the browser.(like github is telling you when you file a bug)
initially after upgrade everything was swapped
after cache clear everything was back to normal.

**Comment by didi31** [comment]
> after cache clear everything was back to normal.

I always do it before posting.
I switched back to the beta version build 14713, clear the cache and the bug remain.

The blocking point I see is that LUA code is not able to see if the blind is open or closed.

My work around before the correction is to call the function below:

`local function bugDeviceClosed(myDevice)
          if myDevice.level == 0 and myDevice.state == 'Open' then
               myDevice.close()
          end
end
`

**Comment by waltervl** [comment]
I have removed all zwave blinds issues of this issue as it is solely for EnOceon devices, they are implemented differently and perhaps not taken correctly into the blinds changes implementation. For general questions about changed Blinds behavior please use the forum and look on the wiki https://www.domoticz.com/wiki/Blinds

Further comments only related to Enocean implementation!

**Comment by didi31** [comment]
If it can help, please find below the output of a simple dzVents script with the feedback starting with the blind Open to Closed.

User: Admin (IP: xxx.xxx.xxx.xxx) initiated a switch command (411/Volet Salon/Close)
Handling events for: "Volet Salon", value: "Closed" => **The real state for the Blind is Open**
------ Start internal script: Volets: Device: "Volet Salon (ENOCEAN PI)", Index: 411
Salon lastLevel 0
Salon level 0
Salon state Closed
------ Finished Volets
Handling events for: "Volet Salon", value: "Open"
------ Start internal script: Volets: Device: "Volet Salon (ENOCEAN PI)", Index: 411
Salon lastLevel 0
Salon level 100
Salon state Open
------ Finished Volets
ENOCEAN PI: Lighting 2 (Volet Salon)
Handling events for: "Volet Salon", value: "Open"
------ Start internal script: Volets: Device: "Volet Salon (ENOCEAN PI)", Index: 411
Salon lastLevel 0
Salon level 94
Salon state Open
------ Finished Volets
ENOCEAN PI: Lighting 2 (Volet Salon)
Handling events for: "Volet Salon", value: "Open"
------ Start internal script: Volets: Device: "Volet Salon (ENOCEAN PI)", Index: 411
Salon lastLevel 6
Salon level 80
Salon state Open
------ Finished Volets
ENOCEAN PI: Lighting 2 (Volet Salon)
Handling events for: "Volet Salon", value: "Open"
------ Start internal script: Volets: Device: "Volet Salon (ENOCEAN PI)", Index: 411
Salon lastLevel 20
Salon level 74
Salon state Open
------ Finished Volets
ENOCEAN PI: Lighting 2 (Volet Salon)
Handling events for: "Volet Salon", value: "Open"
------ Start internal script: Volets: Device: "Volet Salon (ENOCEAN PI)", Index: 411
Salon lastLevel 26
Salon level 60
Salon state Open
------ Finished Volets
ENOCEAN PI: Lighting 2 (Volet Salon)
ENOCEAN PI: Lighting 2 (Volet Salon)
Handling events for: "Volet Salon", value: "Open"
------ Start internal script: Volets: Device: "Volet Salon (ENOCEAN PI)", Index: 411
Salon lastLevel 53
Salon level 40
Salon state Open
------ Finished Volets
ENOCEAN PI: Lighting 2 (Volet Salon)
Handling events for: "Volet Salon", value: "Open"
------ Start internal script: Volets: Device: "Volet Salon (ENOCEAN PI)", Index: 411
Salon lastLevel 60
Salon level 27
Salon state Open
------ Finished Volets
ENOCEAN PI: Lighting 2 (Volet Salon)
Handling events for: "Volet Salon", value: "Open"
------ Start internal script: Volets: Device: "Volet Salon (ENOCEAN PI)", Index: 411
Salon lastLevel 73
Salon level 20
Salon state Open
------ Finished Volets
ENOCEAN PI: Lighting 2 (Volet Salon)
Handling events for: "Volet Salon", value: "Open"
------ Start internal script: Volets: Device: "Volet Salon (ENOCEAN PI)", Index: 411
Salon lastLevel 80
Salon level 7
Salon state Open
------ Finished Volets
ENOCEAN PI: Lighting 2 (Volet Salon)
Handling events for: "Volet Salon", value: "Open"=> **The real state for the Blind is Closed**
------ Start internal script: Volets: Device: "Volet Salon (ENOCEAN PI)", Index: 411
Salon lastLevel 93
Salon level 0
Salon state Open
------ Finished Volets

Something strange is that the lastLevel value increase whilst the level value decrease.

**Comment by gizmocuz** [comment]
I hope developers that enhanced the EnOcean class can help here

I suspect the issue is here:

int CEnOceanESP3::getPositionFromCommandLevel(int cmnd, int pos)

**pos = pos * 100 / 15;**

Also the switch type you have is a Lighting2, I would have chosen for a type pTypeGeneralSwitch/sSwitchGeneralSwitch as this (with blinds) also gets you a percentage from 0-100 instead of 0-15 (you have 15 steps now)

I think the rounding issue is caused in the above function

@efdeb , is it maybe possible you could have a look at this?

**Comment by efdeb** [comment]
Hi, OK I will have a look.

I own à Nodon Blind module, but no actual blind to drive with it...

I already saw an issue for blinds in ESP3 code, since there is only one last level value remembered and you can have more than one blind in your house...

**Comment by gizmocuz** [comment]
Great! Thanks!
Maybe also change the blind to use switch type pTypeGeneralSwitch/sSwitchGeneralSwitch so you have a range from 0-100

**Comment by didi31** [comment]
If you tell me what to do, I have 2 blinds available for testing.
You can see also that the lastLevel(n) = 100 - level(n-1)

**Comment by efdeb** [comment]
Not sure I can look at it before next monday.
I'll let you know.

According to EnOcean EEP D2-05-0X documentation, level 0% should correspond to an Open blind and level 100% to a Closed blind.

**Comment by efdeb** [comment]
OK, I worked on it and the result is available from domoticz fork in my repository :
https://github.com/efdeb/domoticz/tree/enoblinds

@didi31 are you able to test it ? If not, you can PM me so I can explain.

@gizmocuz I used switch type pTypeGeneralSwitch/sSwitchGeneralSwitch to control D2-05-0X, but I had to reverse the value as according to EnOcean EEP D2-05-0X documentation, level 0% should correspond to an Open blind and level 100% to a Closed blind. For pTypeGeneralSwitch/sSwitchGeneralSwitch 0% should correspond to Off/Closed and 100% to On/Open.

@didi31 are you able to test it ? If not, you can PM me so I can explain.

An other thing : the Nodon SIN-2-RS-01 Blinds Control module I own, with EEP D2-05-00, doesn't react as described in EnOcean EEP 2.6.8. It is possible to send a blind position and receive a status when the blind has reached it. But the module seems to ignore other commands such as Stop, Query position, and Set parameters.

**Comment by waltervl** [comment]
@efdeb Is the 0-100 meaning not dependent on what the specific blinds device setting is? See wiki https://www.domoticz.com/wiki/Blinds
If EnOcean device inverted the direction, the user (or perhaps with device creation) the Reverse Position switch can be enabled to invert it.

**Comment by efdeb** [comment]
Yes this could also be done like that, but I preferred adjust the EnOcean code so that the blind react as expected when using the general switch without needing to reverse the blind direction. It just implies converting between Domotics internal values and EnOcean ESP3 protocol values.

**Comment by didi31** [comment]
> @didi31 are you able to test it ? If not, you can PM me so I can explain.

How to PM you on Github?

> An other thing : the Nodon SIN-2-RS-01 Blinds Control module I own, with EEP D2-05-00, doesn't react as described in EnOcean EEP 2.6.8. It is possible to send a blind position and receive a status when the blind has reached it. But the module seems to ignore other commands such as Stop, Query position, and Set parameters.

I own an EVOLOGY EnOcean module bought at Leroy Merlin. Nodon confirmed me that there is no difference with the Nodon module.
However the Stop is working for me.

**Comment by waltervl** [comment]
@gizmocuz how to set reverse position enabled on a pTypeGeneralSwitch/sSwitchGeneralSwitch blinds on creation?

**Comment by efdeb** [comment]
Hello @gizmocuz, @waltervl,

Concerning the wiki page https://www.domoticz.com/wiki/Blinds, I would suggest replacing sentences like :

_Slider
0 = Blind **Close** in GUI, dzvents, Lua, http API and Python when using setLevel
100 = Blind **Open** in GUI, dzvents, Lua, http API and Python when using setLevel
90 = Show **90** in the GUI/dzvents, Send 90 to the device (Blind almost fully Open)
10 = Show **10** in the GUI/dzvents, Send 10 to the device (Blind almost fully Closed)_ 

By :

_Slider
0 = Blind **Closed** in GUI, dzvents, Lua, http API and Python when using setLevel, send **Blind fully Open** to the device
100 = Blind **Open** in GUI, dzvents, Lua, http API and Python when using setLevel, send **Blind fully Closed** to the device
90 = Show **90** in the GUI/dzvents, Send Blind **almost fully Open** to the device
10 = Show **10** in the GUI/dzvents, Send Blind **almost fully Closed** to the device_

Indeed, the actual "**value sent to the device**" isn't relevant for the end user, but **depends on the hardware protocol** used to operate the blinds. For instance 0 is an Open blind and 100 is a Closed one for EnOcean ESP3, but it might be different for other protocols (100..0, 0x0..0xF, ...).

I think the better would be that the different hardware protocols implement the standard behaviour (0=Closed, 100=Open) and the blind config options are only used when :

1/ hardware protocol is not currently implementing this, because not updated in that way yet, ex. I had to set Reverse Open/Close state on my Somfy RTS blinds after recent changes in domoticz implementation

2/ a specific device do not react as expected (ex. an EnOcean blind that would Open on 100 and Close on 0)

**Comment by efdeb** [comment]
In addition, I would suggest reversing blind Open/Close icons in GUI blinds control widgets : Close icon on the left and Open icon on the right would be more consistent with the slider position : 0 on the left, 100 on the right.

**Comment by gizmocuz** [comment]
The inversion (if needed) needs to be done in the hardware class/plugin, in this case the EnOcean code
So all works without special inversion tricks for the end user in the Gui

**Comment by efdeb** [comment]
This is what I did. Under test now. Thank's.

**Comment by gizmocuz** [comment]
Great, thanks!!!

**Comment by waltervl** [comment]
This EnOcean blind timers issue is also fixed with these changes? https://github.com/domoticz/domoticz/issues/5417

**Comment by waltervl** [comment]
I do not understand this proposed change in wiki:
> Slider
0 = Blind Closed in GUI, dzvents, Lua, http API and Python when using setLevel, **send Blind fully Open to the device**

Setting to level 0 (with api, Lua, dzvents etc) will close the blind.

**Comment by efdeb** [comment]
My mystake ! Sorry !

=> 0 = Blind Closed in GUI, dzvents, Lua, http API and Python when using setLevel, send Blind **fully Closed**  to the device

The idea was to essentially to remonv Send 90 and Send 10 in the next following lines, because what is sent to the device depends on the hardware protocol.

**Comment by waltervl** [comment]
The behavior on the wiki is for the users and Lua/dzvents script programmers to not the c++ developers.

**Comment by efdeb** [comment]
Send 90 and Send 10 in the next following lines, because what is sent to the device depends on the hardware protocol and has no interrest to the Lua/dzvents script programmers because they manipulate domoticz values and not hardware protocol values.
;^)

**Comment by waltervl** [comment]
No, dzvents/Lua 2etc scripts can also send 10 and 90. Also for feedback when a user sets the level by a remote control the level to almost closed it should be reported to the domoticz device as 10 (but could be level 90 for the hardware)

**Comment by waltervl** [comment]
@efdeb @didi31 How are the tests going on?

**Comment by didi31** [comment]
I tested the latest version from @efdeb this morning.
All is working correctly except when the blind is fully opened and the GUI shows it at xx%
This problem is under review by @efdeb

**Comment by waltervl** [comment]
what is the status? Everything solved now?

**Comment by efdeb** [comment]
For me it is solved, even if some code adjustments shall come with next PR.

**Comment by waltervl** [comment]
Thanks! I will close this issue.
