### ISSUE TITLE
Custom Page is always active (some browsers, not all)

### ISSUE THREAD

**Issue by mojso** [domoticz/domoticz#5396]
When I open Domoticz via mobile, the Custom Page is always active.  
Raspberry pi 3bplus
 Domoticz version 2022.2 (build 14708)

**Comment by kiddigital** [comment]
Cache cleared? Can you provide a screenshot?

**Comment by mojso** [comment]
Yes Cache cleared

![Screenshot_20221107-231525_Chrome](https://user-images.githubusercontent.com/8018149/200486924-af4b5b74-11b7-4c05-a61e-6f55f1aeb2e7.jpg)

**Comment by mojso** [comment]
and always if the Custom menu is active in portrait, the drop-down menu is like in the picture

only on mobile phone screens

![Screenshot_20221108-174448_Chrome](https://user-images.githubusercontent.com/8018149/200626202-522a0ddf-747c-4c78-a369-7f821738746c.jpg)

**Comment by kiddigital** [comment]
@mojso , please check the standard 'admin' user to see if it has all screen enabled (Settings/Users). If not, enable them.

**Comment by mojso** [comment]
admin user all screens are enabled.  custom page is still active.  for all other users, the Custom page is still active, but it is disabled in the menu of each user

> @mojso , please check the standard 'admin' user to see if it has all screen enabled (Settings/Users). If not, enable them.

**Comment by kiddigital** [comment]
> When I open Domoticz via mobile, the Custom Page is always active.  
> 
> Raspberry pi 3bplus
> 
>  Domoticz version 2022.2 (build 14708)
> 
> 
> 
> 
> 
> 

Ok.. maybe I understood the issue incorrectly.

Let me phrase it Gherkin style.

__Given__ the option 'custom' is disabled in the `active menus` list on the setting screen
__When__ I access the UI on a mobile browser in portrait mode
__Then__ the 'custom' tab on the top navigation should NOT be visible

Is this the scenario you expect? And it does not work that way?

Same problem if in Landscape mode?

How about other (non mobile) browsers?

Which scenario does work (if any)?

**Comment by mojso** [comment]
> 
Custom menu is always visible even though it is deactivated in active menus.  this only happens via mobile phone and tablet.  via PC or Raspbery pi doesn't have that problem.  if it is deactivated, the Custom menu is not visible

**Comment by mojso** [comment]
> > When I open Domoticz via mobile, the Custom Page is always active.
> > Raspberry pi 3bplus
> > Domoticz version 2022.2 (build 14708)
> 
> Ok.. maybe I understood the issue incorrectly.
> 
> Let me phrase it Gherkin style.
> 
> **Given** the option 'custom' is disabled in the `active menus` list on the setting screen **When** I access the UI on a mobile browser in portrait mode **Then** the 'custom' tab on the top navigation should NOT be visible
> 
> Is this the scenario you expect? And it does not work that way?
> 
> Same problem if in Landscape mode?
> 
> How about other (non mobile) browsers?
> 
> Which scenario does work (if any)?

first sorry for my bad english.  The problem is, the Custom menu is deactivated in settings - active menus, but it appears even though it is deactivated.  only through Chromium on raspberry pi this option works as it should, on all other devices (tablet, mobile phone, personal computer) the option does not work

**Comment by kiddigital** [comment]
@mojso , thanks for clarifying. As its works on some browsers (you mentioned Chromium and if I test it with FireFox) and does not on some others, it seems to be a compatibility issue.

Can you specify specifically which browsers (and version) on which device (and version) it does not work?

**Comment by waltervl** [comment]
I cannot reproduce this in my test environment. When switching custom menu off from menu setup settings it disappears in all cases, Firefox, google chrome in mobile and desktop.

**Comment by mojso** [comment]
through the users menu I can deactivate the Custom menu but if it is active,  Custom Menu cannot be deactivated in active menu settings.  Before I updated Domoticz I didn't have this problem.  Only chromium in Raspbery pi doesn't have this problem, but it might be because of the granted access without username and password

**Comment by waltervl** [comment]
Please try it in a browser in private mode (to be sure old cache is not causing issues)

**Comment by mojso** [comment]
same in incognito mode same problem.  only if access is guaranteed without username and password active menu options work, they can be deactivated

**Comment by waltervl** [comment]
Can you make any change in menu setup settings with user account enabled? As that seems to be a more common issue in the past.
Do you get errors when pressing on the apply change button?

**Comment by mojso** [comment]
> 

Yes, I can make changes in the settings and I don't get any errors
