### ISSUE TITLE
suddenly domoticz asks for a login - and after entry goes to 1112.net/lastpage.html

### ISSUE THREAD

**Issue by veitk** [domoticz/domoticz#5397]
since the update yesterday domoticz asks for a login, which might me okay, but after i entered the correct passwort it goes to http://www.1112.net/lastpage.html

phone app says i'm logged in, but also says something went wrong.

**Comment by kiddigital** [comment]
Please check the forum first and try to solve it using the info available. GitHub is only for reporting reproducible bugs.
