### ISSUE TITLE
In Dashboard the devices are not in line

### ISSUE THREAD

**Issue by mojso** [domoticz/domoticz#5398]
In mobile view -  portrait
text device , shows the information in one line, and in Dashboard the devices are not in line.  this problem is from previous versions

Domoticz Version: 2022.2 (build 14713)

![Screenshot_20221108-172251_Chrome](https://user-images.githubusercontent.com/8018149/200620680-e1af4c00-ce1c-4b72-8b31-727eae0e8463.jpg)

**Comment by mojso** [comment]
and always if the Custom menu is active in portrait, the drop-down menu is like in the picture

![Uploading Screenshot_20221108-174448_Chrome.jpg…]()

**Comment by mojso** [comment]
and always if the Custom menu is active in portrait, the drop-down menu is like in the picture

![Screenshot_20221108-174448_Chrome](https://user-images.githubusercontent.com/8018149/200625960-45246ceb-0d8d-436c-a67c-b5d28545947d.jpg)

**Comment by waltervl** [comment]
Stupid question but needs to be asked: Did you clear the browser cache (or tried it in private mode)?

**Comment by waltervl** [comment]
I tested it with my test system but have no issues
![Screenshot_20221110-013030-141](https://user-images.githubusercontent.com/16327072/200971202-998533ca-1660-4922-9117-a082abcfded3.png)

**Comment by mojso** [comment]
I have this problem because of the length of the text.  which is shown in the picture

![Uploading Screenshot_20221110-061724_Chrome.jpg…]()

**Comment by mojso** [comment]
I have this problem because of the length of the text.  which is shown in the picture

![Screenshot_20221110-061724_Chrome](https://user-images.githubusercontent.com/8018149/201007608-f57c2a40-b30c-4957-96cb-77fec0ce79da.jpg)

**Comment by waltervl** [comment]
I normally put \r\n statements in the text for new lines to get long texts readable.  See also wiki https://www.domoticz.com/wiki/Dummy_for_virtual_Switches#Text_sensor

**Comment by mojso** [comment]
thank you with this command is better.  but I think that previously this command was not needed, the text went to the second line if it was long

![Screenshot_20221110-213644_Chrome](https://user-images.githubusercontent.com/8018149/201200762-70dd8805-2eeb-4c70-9def-e810adc6d359.jpg)

**Comment by waltervl** [comment]
From your first message I got the impression that this issue was also present in a previous version. I checked the changes from 2022.1 to 2022.2 and cannot find a change that would introduce this issue.

**Comment by mojso** [comment]
> From your first message I got the impression that this issue was also present in a previous version. I checked the changes from 2022.1 to 2022.2 and cannot find a change that would introduce this issue.

maybe there is no change from your side, maybe the change is from web browser (chrome android), and yes the change is from before

**Comment by gizmocuz** [comment]
Thanks for reporting, solved in upcoming beta version. Indeed, if you want to break the lines you have to add <br/> between the text. In the next beta text will be wrapped in the mobile view
