### ISSUE TITLE
Problem to access to Domoticz via Dataplicity

### ISSUE THREAD

**Issue by skom27** [domoticz/domoticz#5401]
After updating Domoticz to the last version (2022.2) I do not have access to Domoticz (https://************.dataplicity.io port 80) via Dataplicity (403 Forbidden). :(

Log form Domoticz:
2022-11-08 15:42:05.994 Error: Webserver: Multiple proxies are used (Or possible spoofing attempt), ignoring client request (remote address: 127.0.0.1)

Version: 2022.2
Platform: Raspberry Pi 4

PS. Previous versions of Domoticz worked with Dataplicity without any problems

**Comment by kiddigital** [comment]
You need to add the local network interface(s) to the  (trusted) `local networks`.

Previous version this was implicit, but also risky and unclear. Now it needs to be set explicitly.

See [this](https://www.domoticz.com/forum/viewtopic.php?t=39312) forum topic for more info.

**Comment by skom27** [comment]
Even in earlier versions of domoticz, I had the local network set (127.0.0.1)
![image](https://user-images.githubusercontent.com/26573032/200822755-b5141a5a-6e3d-412a-900e-30ed57e78099.png)
I have read SECURITY_SETUP.md and unfortunately I do not know how to set "Add clients" (I do not have / "do not see" the "Under 'Setup / More Options / Applications' it is possible to add / modify applications" (Domoticz 2022.2). Please guide me how to share Domoticz for Dataplicity (works under ZeroTier)
