### ISSUE TITLE
Security improvements

### ISSUE THREAD

**Issue by skom27** [domoticz/domoticz#5403]
> After updating Domoticz to the last version (2022.2) I do not have access to Domoticz (https://************.dataplicity.io port 80) via >Dataplicity (403 Forbidden). :(
>Log form Domoticz:
>2022-11-08 15:42:05.994 Error: Webserver: Multiple proxies are used (Or possible spoofing attempt), ignoring client request (remote address: 127.0.0.1)
>Version: 2022.2
>Platform: Raspberry Pi 4
>PS. Previous versions of Domoticz worked with Dataplicity without any problems

>@kiddigital
>You need to add the local network interface(s) to the (trusted) local networks.

>Previous version this was implicit, but also risky and unclear. Now it needs to be set explicitly.

>See [this](https://www.domoticz.com/forum/viewtopic.php?t=39312) forum topic for more info.

Even in earlier versions of domoticz, I had the local network set (127.0.0.1)
![image](https://user-images.githubusercontent.com/26573032/200823505-1375a6fe-d413-4187-a14f-d74e896df6c4.png)
I have read SECURITY_SETUP.md and unfortunately I do not know how to set "Add clients" (I do not have / "do not see" the "Under 'Setup / More Options / Applications' it is possible to add / modify applications" (Domoticz 2022.2). Please guide me how to share Domoticz for Dataplicity (works under ZeroTier)

**Comment by kiddigital** [comment]
@skom27 , if you don't see the 'Applications' menu option than you probably have a cache issue. At least if you are on the latest Beta.

The latest Stable 2022.2 does **NOT** yet have the security improvements mentioned in the forum.

But for this scenario, you do not have to add an 'Application' (Client) as the intended Application (dataplicity.io) does not leverage OAuth2/OIDC to Identity and Authorize itself.

Looking at the errorlog line you reported in issue #5401 the request that comes in has multiple proxy headers (and corresponding addresses) and Domoticz is unable to determine the real origin of the request and therefor unable to verify if it is from a valid origin and how to handle it. For security reasons such requests are now denied.

Can you capture the incoming requests including all the request headers? Looking for the 'X-Forwarded-For' header but also others. With this information we might be able to determine the real origin and add support for 'dataplicity.io'.

**Comment by skom27** [comment]
Can you say me where I have to looking for request headers?

**Comment by kiddigital** [comment]
@skom27 , you need to 'intercept' them by sniffing the network communication. For example use a tool like Wireshark.

Do you have the ability to run test/PR builds on Linux? If so, we could create a testbuild that does the capturing for you.

**Comment by skom27** [comment]
It is a long weekend in Poland now, I will be home only on Sunday afternoon.  
Non-disposable I don't know what is "PR builds"?  
Ps.  I don't know if I'm right but it seems to me that wireshark only intercepts via wifi (I have RPi connected via ethernet cable)

**Comment by skom27** [comment]
@kiddigital
> Do you have the ability to run test/PR builds on Linux? If so, we could create a testbuild that does the capturing for you.

Can you explain the PR builds test to me (I have a mikrotik router that has a torch and a sniffer)

**Comment by skom27** [comment]
Am I the only one who can't connect to Domoticz 2022.2 via Dataplicity?  Maybe someone solved this connection problem?

**Comment by kiddigital** [comment]
> @kiddigital
> 
> > Do you have the ability to run test/PR builds on Linux? If so, we could create a testbuild that does the capturing for you.
> 
> 
> 
> Can you explain the PR builds test to me (I have a mikrotik router that has a torch and a sniffer)

A Test or PR build is a special (Linux only at the moment) build which is created automatically when a PR (Pull Request) is created/updated.

If you look at the 'checks' tab of a PR, you can see if the build and checks where successful or not. If successful, an 'artifact' is created. This artifact can be downloaded (as a Zip file) and contains a Linux tar file holding the new Domoticz Linux binary. If you use this binary in a new/existing Linux Domoticz setup, you can test the new functionality that such a PR build contains.

I could create a PR adding some special debugging lines to capture the header info we need to understand how the proxy headers look like.

**Comment by skom27** [comment]
I'll do what you say :), just to connect via Dataplicity :). Write what should I do!

**Comment by kiddigital** [comment]
> I'll do what you say :), just to connect via Dataplicity :). Write what should I do!

There now is a (draft) Pull Request #5425 which has the current Beta code with some additional debug logging added.

You can download the build artifact, look at the `Checks`-tab and in the right corner you see `Artifacts (1)`.

This download contains the Linux binary for this particular PR build. Setup a Linux Domoticz environment (using Docker for example) and replace the domoticz binary with this version.

Now start this domoticz version with some extra startup flags. For example:
`./domoticz -www 8080 -sslwww 0 -loglevel all -debuglevel webserver,received,auth`
This will start domoticz with only the non-ssl webserver on port 8080 (or any port you prefer) and enable some additional debug logging.

Now try to connect to this domoticz instance through 'dataplicity.io' as you would normally do and look for debug information reporting the 'Request headers'. The information of the request headers should be in the log.

If you could post those here, we can take a look to see how the communication from dataplicity.io reached your Domoticz instance.

**Comment by skom27** [comment]
@kiddigital
Thanks for your answer, but unfortunately I can't do it :(
I installed on my Windows programs:
gh_2.20.2_windows_amd64.msi
GitHubDesktopSetup-x64.exe
Git-2.38.1-64-bit.exe
I tried invoking the command:
`gh pr checkout 5425`
in "CMD" and "GIT cmd".
Unfortunately, in both cases I get the following messages:
"could not determine ba
![screen](https://user-images.githubusercontent.com/26573032/203335327-594f9665-dd68-4184-9266-5603da2f73ac.jpg)
se repo: failed to run git: fatal: not a git repository (or any of the parent directories): .git"

**Comment by kiddigital** [comment]
@skom27 , are you able to test this special Linux PR build with the info provided?

**Comment by skom27** [comment]
I will try to do it in the first moment of more free time. I just have a problem with "understanding" (I don't know how to do it ("Setup a Linux Domoticz environment (using Docker for example) and replace the domoticz binary with this version.") - can I just replace the runtime PR file downloaded from this link ("binary for this particular PR build") with a file that version 2022.2?)

**Comment by kiddigital** [comment]
@skom27 , yes. Just replace the file called `domoticz` in your Linux installation with the PR file (which you can find in the downloaded file after first UNZIPping it and than unpack the tar-file).

**Comment by skom27** [comment]
@kiddigital: I tried to run as you wrote, unfortunately after issuing the command:
`pi@domoticz:~/domoticz $ ./domoticz -www 80 -sslwww 0 -loglevel all -debuglevel webserver,received,auth`
I got an error:
`-bash: ./domoticz: can't start binary: Wrong executable format`

Reply to:
`pi@domoticz:~/domoticz $ cat /etc/os-release](url)`
is:
`PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"`
`NAME="Raspbian GNU/Linux"`
`VERSION_ID="10"`
`VERSION="10 (buster)"`
`VERSION_CODENAME=buster`
`ID=raspbian`
`ID_LIKE=debian`

What can I do now?

**Comment by kiddigital** [comment]
Hi @skom27 , the PR build is intended for a Linux 64-bit X86 environment and not for a 32/64-bit ARM like your raspberry Pi.

If you don't have a PC with Linux (either native or using virtualbox, hyper-v, Docker, etc) than it is not possible to use the PR build.

Let me check to see if I can add some debugging temporarily to the normal Beta's (incl. RPI) that could provide the right information.

**Comment by skom27** [comment]
Of course :).  I am looking forward to your work and thank you very much for your willingness to help!

**Comment by kiddigital** [comment]
@skom27 , in a coming Beta (14800 or higher) the additional debugging is present. So once it is available, please install it on your Pi and run it with the mentioned debugging flags. Hopefully than we can see the different proxy headers and their values and start working from there.

14801 is available.

**Comment by skom27** [comment]
Thank you for your support :)
So how do I download, for example, beta versions 2022.14823 for RPi

![domot](https://user-images.githubusercontent.com/26573032/206295194-e5b6011c-db32-4411-94d9-445351d1ecc0.jpg)

this I have to run on my raspberry by replacing the stable domoticz 2022.2 with the command:
`./domoticz -www 8080 -sslwww 0 -loglevel all -debuglevel webserver,received,auth`
Yes?

**Comment by kiddigital** [comment]
You can switch to the Beta channel. Look in the 'Setup' settings.

Using the UI you can install the latest Beta.

Once it is installed and running, you have to use the command line to stop Domoticz and restart it using the given (debug) parameters.

**Comment by skom27** [comment]
I switched to the beta version of Domoticz. I tried to run domoticz on **www 80**, unfortunately I couldn't:

```
2022-12-10 07:52:06.491 Status: WebServer(HTTP) startup failed on address :: with port: 80: bind: Permission denied [system:13], trying ::
2022-12-10 07:52:06.492 Status: WebServer(HTTP) startup failed on address :: with port: 80: bind: Permission denied [system:13], trying 0.0.0.0
2022-12-10 07:52:06.492 Error: WebServer(HTTP) startup failed on address 0.0.0.0 with port: 80: bind: Permission denied [system:13]
2022-12-10 07:52:06.493 Error: WebServer(HTTP) check privileges for opening ports below 1024
2022-12-10 07:52:06.493 Error: Domoticz(pid:1921, tid:1921('domoticz')) received fatal signal 6 (Aborted)

```

**Comment by kiddigital** [comment]
@skom27 , if you want to run on port 80 you need to start domoticz as root (using the `sudo` command)

**Comment by skom27** [comment]
When I try to connect via dataplicity I get:

```
2022-12-10 12:04:04.469  Debug: [web:80] IP (10.1.1.16) is within Trusted network range!
2022-12-10 12:04:04.469  Debug: [web:80] isPage 1 isAction 0 isUpgrade 0 isAuthenticated 1 (skom)
2022-12-10 12:04:04.470  Debug: CWebServer::GetJSonPage() :udevice :/json.htm?type=command&param=udevice&idx=155&nvalue=0&svalue=10.3 
2022-12-10 12:04:04.481  Status: [web:80] Incoming connection from: 10.1.1.16
2022-12-10 12:04:04.482  Debug: [web:80] generate new session id token 1543fd2fcfe932b648e5fa8a1cbc4c62
2022-12-10 12:04:04.482  Debug: [web:80] generate new authentication token ZWIyMDc5OGEtZDFjMy00YTlhLTllMDUtZjgzZDA1YTM0Nzcx for user skom
2022-12-10 12:04:04.484  Debug: Web ACLF: 10.1.1.16 - - [10/Dec/2022:12:04:04.469 +0100] "GET /json.htm?type=command&param=udevice&idx=155&nvalue=0&svalue=10.3 HTTP/1.1" 200 49 - "got (https://github.com/sindresorhus/got)"
2022-12-10 12:04:06.833  Debug: [web:80] Host:127.0.0.1 Uri:/
2022-12-10 12:04:06.833  Debug: [web:80] Request Headers:
X-Forwarded-For: 78.11.125.14, 130.176.38.124, 10.20.41.5
X-Forwarded-Proto: https
Host: ####-####-####-####.dataplicity.io
Connection: close
X-Forwarded-Port: 443
X-Amzn-Trace-Id: Root=1-639467a6-6190cf7c472809421bd1ae1d
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
X-Amz-Cf-Id: QOJbwCVvFRDPnva-SyiNPJC0Pg-XGTo5JYbdZbGmLv0ecYjvhkSsCw==
Via: 2.0 4ca98b546b8d71c72caf6a3d8f75dc24.cloudfront.net (CloudFront)
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6,nl;q=0.5
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Referer: https://####-####-####-####.dataplicity.io/
Accept-Encoding: gzip, deflate, br
cache-control: max-age=0
sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
upgrade-insecure-requests: 1
service-worker-navigation-preload: true
sec-fetch-site: same-origin
sec-fetch-mode: navigate
sec-fetch-user: ?1
sec-fetch-dest: document
dnt: 1
sec-gpc: 1

2022-12-10 12:04:06.834  Error: [web:80]: Multiple proxies are used (Or possible spoofing attempt), ignoring client request (remote address: 127.0.0.1)
2022-12-10 12:04:06.834  Debug: Web ACLF: 127.0.0.1 - - [10/Dec/2022:12:04:06.833 +0100] "GET / HTTP/1.1" 403 85 "https://####-####-####-####.dataplicity.io/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
2022-12-10 12:04:06.973  Debug: [web:80] Host:10.1.1.52 Uri:/json.htm?type=command&username=c2tvbQ==&password=a2Vpc3l6cks2Mw==&param=udevice&idx=125&nvalue=0&svalue=17.15
2022-12-10 12:04:06.973  Debug: [web:80] Request Headers:
Host: 10.1.1.16
User-Agent: ESP8266HTTPClient
Connection: close
Accept-Encoding: identity;q=1,chunked;q=0.1,*;q=0

2022-12-10 12:04:06.974  Debug: [web:80] IP (10.1.1.52) is within Trusted network range!
2022-12-10 12:04:06.974  Debug: [web:80] isPage 1 isAction 0 isUpgrade 0 isAuthenticated 1 (skom)
2022-12-10 12:04:06.974  Debug: CWebServer::GetJSonPage() :udevice :/json.htm?type=command&username=c2tvbQ==&password=a2Vpc3l6cks2Mw==&param=udevice&idx=125&nvalue=0&svalue=17.15 
2022-12-10 12:04:06.982  Status: [web:80] Incoming connection from: 10.1.1.52
2022-12-10 12:04:06.983  Debug: [web:80] generate new session id token a5772b62b837109ff0c592b4b2d0a616
2022-12-10 12:04:06.983  Debug: [web:80] generate new authentication token Y2QxMjZkMGEtN2ZhNS00OTNkLThiNTQtMjY3NzZmNWFiYjQ5 for user skom
2022-12-10 12:04:06.984  Debug: Web ACLF: 10.1.1.52 - - [10/Dec/2022:12:04:06.973 +0100] "GET /json.htm?type=command&username=c2tvbQ==&password=a2Vpc3l6cks2Mw==&param=udevice&idx=125&nvalue=0&svalue=17.15 HTTP/1.1" 200 49 - "ESP8266HTTPClient"
2022-12-10 12:04:11.271  Debug: [web:80] Host:127.0.0.1 Uri:/service-worker.js
2022-12-10 12:04:11.271  Debug: [web:80] Request Headers:
X-Forwarded-For: 78.11.125.14, 130.176.38.169, 10.20.40.225
X-Forwarded-Proto: https
Host: ####-####-####-####.dataplicity.io
Connection: close
X-Forwarded-Port: 443
X-Amzn-Trace-Id: Root=1-639467aa-388c4b9b2f767b0532065318
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
X-Amz-Cf-Id: 1up2oGsDzdUb-E2IfJA5Il5apWHSByhYztoptH1G1odhx7YsXF18Bg==
Via: 2.0 4ca98b546b8d71c72caf6a3d8f75dc24.cloudfront.net (CloudFront)
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6,nl;q=0.5
Accept: */*
Referer: https://####-####-####-####.dataplicity.io/service-worker.js
Accept-Encoding: gzip, deflate, br
cache-control: max-age=0
service-worker: script
sec-fetch-site: same-origin
sec-fetch-mode: same-origin
sec-fetch-dest: serviceworker

2022-12-10 12:04:11.272  Error: [web:80]: Multiple proxies are used (Or possible spoofing attempt), ignoring client request (remote address: 127.0.0.1)
2022-12-10 12:04:11.272  Debug: Web ACLF: 127.0.0.1 - - [10/Dec/2022:12:04:11.271 +0100] "GET /service-worker.js HTTP/1.1" 403 85 "https://####-####-####-####.dataplicity.io/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
2022-12-10 12:04:15.896  RPi GPIO: Optional connected Master Domoticz now updates its status
2022-12-10 12:04:16.378  Debug: [web:80] Host:10.1.1.16 Uri:/json.htm?type=devices&rid=149
2022-12-10 12:04:16.380  Debug: [web:80] Request Headers:
user-agent: got (https://github.com/sindresorhus/got)
Host: 10.1.1.16
Connection: close
```

**Comment by kiddigital** [comment]
@skom27 , thx... this indeed shows what we need...
```
2022-12-10 12:04:06.833  Debug: [web:80] Host:127.0.0.1 Uri:/
2022-12-10 12:04:06.833  Debug: [web:80] Request Headers:
X-Forwarded-For: 78.11.125.14, 130.176.38.124, 10.20.41.5
...
2022-12-10 12:04:06.834  Error: [web:80]: Multiple proxies are used (Or possible spoofing attempt), ignoring client request (remote address: 127.0.0.1)
2022-12-10 12:04:06.834  Debug: Web ACLF: 127.0.0.1 - - [10/Dec/2022:12:04:06.833 +0100] "GET / HTTP/1.1" 403 85 "https://####-####-####-####.dataplicity.io/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```
This tells us that Domoticz receives a web request (`Uri:/`) coming from `127.0.0.1` (which is the local IP of the machine Domoticz runs on, your Pi).
The request actually originates from somewhere else, which is revealed by the `X-Forwarded-For` header.
Problem is that currently Domoticz is unable to handle that header in a correct way resulting in the Error message `Multiple proxies... ignoring client request...`. As a result, Domoticz returns a `403 Access Denied` HTTP status code (see the ACLF logline _'.. "GET / HTTP/1.1" **403** 85 ...'_)

With Pull Request #5443 , this problem should be gone.

_**Question**: Looking at the information from the X-Forwarder-For header, the real IP address of the client is _78.11.125.14_. Would that be an IP you expect and would trust?_

With correct handling of the header info, this would be the address Domoticz will be using and if that is not from a Trusted network (currently still called 'local network' on the Security-tab), you will end up on the Domoticz login page. 

_Is it correct that you have something installed from dataplicity on your local machine and that is the reason that the request is seen by Domoticz as coming from 127.0.0.1?_

**Comment by skom27** [comment]
The IP address 78.11.125.14 is the external address of the network I am connected to.
I have Dataplicity installed on the same raspberry as domoticz :)

`With Pull Request #5443 , this problem should be gone.`
What should I do with it, because this version is probably not for the RPi?

P.S. Maybe it's not in this topic, but it's related to solving the problem, because yesterday I switched to beta versions and unfortunately today I have these screens:
Setup
![setup](https://user-images.githubusercontent.com/26573032/206885684-3a7f013c-87a6-486a-ad20-3c4e8de0315b.jpg)
Hardware
![hardware](https://user-images.githubusercontent.com/26573032/206885696-38d37663-ce55-4201-bff7-394676f7845f.jpg)
Devices
![devices](https://user-images.githubusercontent.com/26573032/206885715-8f246573-ad4d-4c81-8b14-227f1019f6b3.jpg)
Changing the language to any other does not work - it says that domoticz settings have been saved, but after refreshing the page, it is still the same as in the screenshots

**Comment by kiddigital** [comment]
PR means is work in progress and once finished, it will make its way into the Beta release. Than it becomes available for all platforms incl RPi.

Please update your Beta to the latest (14831) to solve the issue you have.

**Comment by kiddigital** [comment]
@skom27 , please test the latest Beta (14852 or higher) and let us know if things changed.
