### ISSUE TITLE
enhancement request: DZvents command to send opentherm TC command

### ISSUE THREAD

**Issue by WillemD61** [domoticz/domoticz#5405]
Currently the Dzvents updateSetpoint() command results in an Opentherm TT command, which only changes the setpoint until the next change initiated by the thermostat.

I would like to see a Dzvents command (for example updateConstantSetpoint() ?) that sends the TC command instead of the TT command. This does a permanent override until the control is released back to the thermostat.

In the forum a workaround via a switch is suggested but for many people this does not work and the reason is not clear. Would be better to solve in the code directly.

**Comment by waltervl** [comment]
As long as this is not implemented please check my answer in that forum topic for a workaround https://www.domoticz.com/forum/viewtopic.php?p=294283#p294283

**Comment by WillemD61** [comment]
Thanks. I finally found out why the json command was not working for me. I used the "room setpoint" idx instead of the idx of the "opentherm usb device" as listed in the hardware section (8 in the example below)

So the following command in Dzvents is doing what I requested in this enhancement (with setpoint 16)
domoticz.openURL('http://127.0.0.1:8080/json.htm?type=command&param=sendopenthermcommand&idx=8&cmnd=TC=16')

**Comment by gizmocuz** [comment]
Closing issue as this can be done with the above commamd
