### ISSUE TITLE
Chart context menu of switches has wrong z-index

### ISSUE THREAD

**Issue by TomHW** [domoticz/domoticz#5407]
Version 2022.2 shows the chart context menu below the following chart and it isn't readable.
Steps to reproduce:

1. Browse to switches
2. Open switch protocol
3. Click burger button on the top right corner of the first chart
4. Displayed menu is below the second chart

**Comment by gizmocuz** [comment]
I'm running 2022.1 and this is also the case
Probably need a CSS change somewhere

**Comment by gizmocuz** [comment]
A bit of googling, adding 3 lines in the CSS and fixed in upcoming beta version
