### ISSUE TITLE
menu buttons

### ISSUE THREAD

**Issue by mojso** [domoticz/domoticz#5408]
is it possible for the menu buttons to be smaller in mobile view?  because on small screens this problem appears as in the picture

![Screenshot_20221112-234227_Chrome](https://user-images.githubusercontent.com/8018149/201497416-75c2523a-3af2-422c-9c5a-9abd348f753f.jpg)

**Comment by gizmocuz** [comment]
Made some small patches in beta 14723, should display correctly now
