### ISSUE TITLE
Icon Waterflow device widget does not change to chosen icon

### ISSUE THREAD

**Issue by laplug** [domoticz/domoticz#5410]
The widget icon for waterflow does not change after selecting a custom icon.
It keeps showing a fountain icon.
I have no idea where to look to find the cause.

**Comment by gizmocuz** [comment]
What's wrong with my icon?
Anyway, probably in UtilityController.js ....

**Comment by gizmocuz** [comment]
I am pretty sure that you did not do a search in the code for 'Waterflow' .... next time please use the forum or at least try to search a little...

**Comment by laplug** [comment]
Thanks! I did both, but searched in combination with 'icon' and not 'image'.
