### ISSUE TITLE
FGBS222 device in degrees instead of volts

### ISSUE THREAD

**Issue by Jeradam** [domoticz/domoticz#5411]
Hi,
I have little problem, with the volt devices on a FGBS 222, they are in degrees instead of volts.
I have already try to erase the devices and re-add to them on domoticz but they come back in degrees.
They are in volt into zwave JS UI...
Firmware 5.2 of the fbgs, I have an other one with the firmware 5.1 it work without problem. (This one has 2 external temperature devices and the other has only one.)
Is it possible to convert a device from temperature to voltage?!
 I use this value to calculate a level in cm so I would like to have all the decimals to be more precise (0.1v=2cm)
Thanks for your help
Domoticz r2022.2

![Screenshot_20221113-124339__01](https://user-images.githubusercontent.com/45931287/201588305-7f0c4559-9621-4c5e-930a-641abfcc526f.jpg)
![Screenshot_20221113-124246__01](https://user-images.githubusercontent.com/45931287/201588334-9c180e73-5e04-42d3-9716-92dfd83e2ba3.jpg)

**Comment by gizmocuz** [comment]
@Jeradam , you are using the stable version?
Is it possible you can use MQTT Explorer, connect to your MQTT broker and post me the config topic + payload of the voltage sensor and if possible also the payload received with the voltage ?

**Comment by waltervl** [comment]
Fixed with https://github.com/domoticz/domoticz/commit/fbd00ad9b3f89a6444e901d80381e3e0d6066d96 ??

**Comment by gizmocuz** [comment]
Maybe not sure, thats why I need some verification

**Comment by Jeradam** [comment]
Hi!
The MQTT datas : 
```
Niveau_temperature_bassin
status = {"time":1668340855427,"value":true,"status":"Alive","nodeId":106}
49
9
Air_temperature = {"time":1668519322926,"value":10.5}
3
Voltage = {"time":1668553147988,"value":5.64}
4
Voltage = {"time":1668553177996,"value":10.34}
7
Air_temperature = {"time":1668553117993,"value":22.7}
8
Air_temperature = {"time":1668523219928,"value":10.1}
91
0
scene
slowRefresh = {"time":1668340855347}
108
0
ccSupported
91 = {"time":1668340855347,"value":false}
112
0
20 = {"time":1668340855348,"value":4}
47 = {"time":1668340855349,"value":255}
49 = {"time":1668340855350,"value":0}
150 = {"time":1668340855351,"value":10}
152 = {"time":1668340855352,"value":0}
40
21 = {"time":1668340855355,"value":2}
52 = {"time":1668340855356,"value":255}
54 = {"time":1668340855356,"value":0}
151 = {"time":1668340855357,"value":10}
153 = {"time":1668340855357,"value":0}
41
24 = {"time":1668340855360,"value":0}
63 = {"time":1668340855361,"value":1}
64 = {"time":1668340855361,"value":1800}
65 = {"time":1668340855362,"value":2}
66 = {"time":1668340855362,"value":0}
67 = {"time":1668340855363,"value":2}
68 = {"time":1668340855363,"value":0}
154 = {"time":1668340855364,"value":0}
156 = {"time":1668340855364,"value":0}
155 = {"time":1668340855365,"value":0}
157 = {"time":1668340855365,"value":0}
25 = {"time":1668340855366,"value":0}
114
0
manufacturerId = {"time":1668340855366,"value":271}
productType = {"time":1668340855366,"value":1282}
productId = {"time":1668340855367,"value":4096}
134
0
libraryType = {"time":1668340855367,"value":3}
protocolVersion = {"time":1668340855367,"value":"6.2"}
firmwareVersions = {"time":1668340855368,"value":["5.2"]}
hardwareVersion = {"time":1668340855368,"value":2}
113
1
Home_Security
alarmType = {"time":1668340855369}
alarmLevel = {"time":1668340855369}
2
Home_Security
alarmType = {"time":1668340855370}
alarmLevel = {"time":1668340855371}
7
System
alarmType = {"time":1668340855390}
alarmLevel = {"time":1668340855391}
8
System
alarmType = {"time":1668553343241,"value":0}
alarmLevel = {"time":1668553343243,"value":0}
9
System
alarmType = {"time":1668553467121,"value":0}
alarmLevel = {"time":1668553467123,"value":0}
32
3
currentValue = {"time":1668340855371,"value":56}
targetValue = {"time":1668340855372}
duration = {"time":1668340855373,"value":{"unit":"seconds"}}
restorePrevious = {"time":1668340855374}
4
currentValue = {"time":1668340855375}
targetValue = {"time":1668340855375}
duration = {"time":1668340855376,"value":{"unit":"seconds"}}
restorePrevious = {"time":1668340855377}
7
currentValue = {"time":1668340855387,"value":18}
targetValue = {"time":1668340855388}
duration = {"time":1668340855388,"value":{"unit":"seconds"}}
restorePrevious = {"time":1668340855389}
8
currentValue = {"time":1668340855391,"value":0}
targetValue = {"time":1668340855392}
duration = {"time":1668340855392,"value":{"unit":"seconds"}}
restorePrevious = {"time":1668340855393}
9
currentValue = {"time":1668340855395,"value":0}
targetValue = {"time":1668340855395}
duration = {"time":1668340855396,"value":{"unit":"seconds"}}
restorePrevious = {"time":1668340855396}
37
5
currentValue = {"time":1668340855378,"value":true}
targetValue = {"time":1668340855379,"value":true}
duration = {"time":1668165943044,"value":{"unit":"seconds"}}
6
currentValue = {"time":1668340855384,"value":true}
targetValue = {"time":1668340855385,"value":true}
duration = {"time":1668165943045,"value":{"unit":"seconds"}}
117
5
local = {"time":1668340855380,"value":0}
rf = {"time":1668340855381,"value":0}
exclusiveControlNodeId = {"time":1668340855382}
timeout = {"time":1668340855383}
6
local = {"time":1668340855386,"value":0}
rf = {"time":1668340855386,"value":0}
exclusiveControlNodeId = {"time":1668340855387}
timeout = {"time":1668340855387}


```
Same thing by screenshots
![mqtt1](https://user-images.githubusercontent.com/45931287/202044256-8d8f32f6-65a0-4f85-9be1-921b22115328.JPG)
![mqtt2](https://user-images.githubusercontent.com/45931287/202044264-8d2547da-80ea-46f6-bc86-f22a9a89f80a.JPG)
![MQTT3](https://user-images.githubusercontent.com/45931287/202044278-f5538354-76da-44e2-a67b-8b5223000a77.JPG)


I don't know how to know the exact version but bellow a screenshot of the docker version and the domoticz "about" page
![domoticz about](https://user-images.githubusercontent.com/45931287/202044493-a2a8a3b9-37d7-4c97-adf2-f4389e8b30a0.JPG)
![docker version](https://user-images.githubusercontent.com/45931287/202044503-49a275b5-fade-4fe2-a862-8caae84bad9d.JPG)

**Comment by Jeradam** [comment]
I don't understand what is the "payload of the voltage sensor" ?

**Comment by gizmocuz** [comment]
I need the config topic + payload and the actual node status topic + payload

You can find them via the program MQTT Explorer

Depending on your auto discovery topic name, it could be homeassistant/sensor/xx/xx/config

i need the complete topic name (homeassistant/sensor/xx/xx/config)

and also the content (it's json data)

Now if you look at the json data, you should see something like a refference to a 'state' topic, i need this name
and also the payload of this topic (this is where the data like temperature/voltage is send to)

No need for screenshots

I have no idea what the previous data/screenshot was, but that was probable from the zwave topics which is ok

So I need them for the temperature and voltage

**Comment by Jeradam** [comment]
I hope you need this (sorry if not :D ) 

Voltage

`zwave/Niveau_temperature_bassin/49/3/Voltage`


```
{
  "time": 1668618194036,
  "value": 5.64
}
```

Temperature

`zwave/Niveau_temperature_bassin/49/8/Air_temperature`

```
{
  "time": 1668619055944,
  "value": 10.3
}
```

**Comment by Jeradam** [comment]
Good answer now I mean... 😊

domoticz/sensor/Niveau_temperature_bassin/electricity_voltage_3/config

```
{
  "value_template": "{{ value_json.value }}",
  "device_class": "power",
  "unit_of_measurement": "V",
  "state_topic": "zwave/Niveau_temperature_bassin/49/3/Voltage",
  "json_attributes_topic": "zwave/Niveau_temperature_bassin/49/3/Voltage",
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xc116028e_node106"
    ],
    "manufacturer": "Fibargroup",
    "model": "Smart Implant (FGBS222)",
    "name": "Niveau temperature bassin",
    "sw_version": "5.2"
  },
  "name": "Niveau temperature bassin_electricity_voltage_3",
  "unique_id": "zwavejs2mqtt_0xc116028e_106-49-3-Voltage"
}
```

domoticz/sensor/Niveau_temperature_bassin/temperature_air_8/config


```
{
  "value_template": "{{ value_json.value }}",
  "device_class": "temperature",
  "unit_of_measurement": "°C",
  "state_topic": "zwave/Niveau_temperature_bassin/49/8/Air_temperature",
  "json_attributes_topic": "zwave/Niveau_temperature_bassin/49/8/Air_temperature",
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xc116028e_node106"
    ],
    "manufacturer": "Fibargroup",
    "model": "Smart Implant (FGBS222)",
    "name": "Niveau temperature bassin",
    "sw_version": "5.2"
  },
  "name": "Niveau temperature bassin_temperature_air_8",
  "unique_id": "zwavejs2mqtt_0xc116028e_106-49-8-Air_temperature"
}

```

**Comment by waltervl** [comment]
@Jeradam Still an issue?

**Comment by gizmocuz** [comment]
Yep, but just solved it in beta 14975
This was caused because the voltage was send to a topic containing the word temperature.
To fix previous issue where there was no Unit specified it was assumed that all states with this word belonged to a temperature
Moved to the bottom so other types are detected fitst
