### ISSUE TITLE
MQTT Auto discovery Radio Thermostat Company of America (RTC) CT101 Thermostat Fan mode

### ISSUE THREAD

**Issue by cookemmm** [domoticz/domoticz#5416]
Moving from openzwave to zwavejs2mqtt I noticed my thermostat no longer had a fan mode device. Looking in the Z-wave JS UI it appeared to be missing in the device json so I attempted to add it. I believe I finally have the json correct but domoticz does not create a device to control the fan mode. 

I might still be missing something in my json below but I have searched and can't find any information on how this should work. 

{
  "type": "climate",
  "object_id": "climate",
  "discovery_payload": {
    "min_temp": 5,
    "max_temp": 40,
    "temp_step": 0.5,
    "modes": [
      "off",
      "heat",
      "cool",
      "auto"
    ],
    "fan_modes": [
      "Auto low",
      "Low"
    ],
    "mode_state_template": "{{ {0: \"off\", 1: \"heat\", 2: \"cool\", 3: \"auto\"}[value_json.value] | default('off') }}",
    "fan_mode_state_template": "{{ {0: \"Auto low\", 1: \"Low\"} [value_json.value] | default('Auto Low') }}",
    "current_temperature_topic": "zwave/17/49/1/Air_temperature",
    "current_temperature_template": "{{ value_json.value }}",
    "fan_mode_state_topic": "zwave/17/69/0/state",
    "fan_mode_command_topic": "zwave/17/68/0/mode/set",
    "temperature_state_topic": "zwave/17/67/1/setpoint/1",
    "temperature_state_template": "{{ value_json.value }}",
    "temperature_command_topic": "zwave/17/67/1/setpoint/1/set",
    "mode_state_topic": "zwave/17/64/1/mode",
    "mode_command_topic": "zwave/17/64/1/mode/set",
    "action_topic": "zwave/17/66/0/state",
    "action_template": "{{ {0: \"idle\", 1: \"heating\", 2: \"cooling\", 3: \"fan\", 4: \"idle\", 5: \"idle\", 6: \"fan\", 7: \"heating\", 8: \"heating\", 9: \"cooling\", 10: \"heating\", 11: \"heating\"}[value_json.value] | default('idle') }}",
    "temperature_unit": "F",
    "precision": 0.1,
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xcadd9946_node17"
      ],
      "manufacturer": "Radio Thermostat Company of America (RTC)",
      "model": "Z-Wave Thermostat (CT101)",
      "name": "nodeID_17",
      "sw_version": "9.0"
    },
    "name": "nodeID_17_climate",
    "unique_id": "zwavejs2mqtt_0xcadd9946_Node17_climate"
  },
  "values": [
    "49-1-Air temperature",
    "64-1-mode",
    "66-0-state",
    "67-1-setpoint-1",
    "67-1-setpoint-2",
    "67-1-setpoint-1",
    "69-0-state",
    "68-0-mode"
  ],
  "mode_map": {
    "off": 0,
    "heat": 1,
    "cool": 2,
    "auto": 3
  },
  "fan_mode_map": {
    "Auto low": 0,
    "Low": 1
  },
  "setpoint_topic": {
    "1": "67-1-setpoint-1",
    "2": "67-1-setpoint-2",
    "3": "67-1-setpoint-1"
  },
  "default_setpoint": "67-1-setpoint-1",
  "action_map": {
    "0": "idle",
    "1": "heating",
    "2": "cooling",
    "3": "fan",
    "4": "idle",
    "5": "idle",
    "6": "fan",
    "7": "heating",
    "8": "heating",
    "9": "cooling",
    "10": "heating",
    "11": "heating"
  },
  "discoveryTopic": "climate/nodeID_17/climate/config",
  "persistent": true,
  "ignoreDiscovery": false,
  "id": "climate_climate"
}

**Comment by SalmaHassanACS** [comment]
Hi,
I'm using ZXT-120 IR the first time I can't change the fan mode  but I discovered the topics are wrong  you need to change zwave/17 to zwave/{{Location_Name}}/{{Device_Name}} 
Example:

{
  "type": "climate",
  "object_id": "climate",
  "discovery_payload": {
    "min_temp": 10,
    "max_temp": 40,
    "temp_step": 1,
    "modes": [
      "off",
      "heat",
      "cool",
      "auto",
      "fan_only",
      "dry"
    ],
    "fan_modes": [
      "Auto low",
      "Low",
      "Auto high",
      "High",
      "Auto medium",
      "Medium"
    ],
    "mode_state_template": "{{ {0: \"off\", 1: \"heat\", 2: \"cool\", 3: \"auto\", 6: \"fan_only\", 8: \"dry\"}[value_json.value] | default('off') }}",
    "fan_mode_state_template": "{{ {0: \"Auto Low\", 1: \"Low\", 2: \"Auto high\",3:\"High\", 4: \"Auto medium\", 5: \"medium\"}[value_json.value] | default('Auto Low') }}",
    "current_temperature_topic": "zwave/Testing/testing_IR_2/49/0/Air_temperature",
    "current_temperature_template": "{{ value_json.value }}",
    "temperature_state_topic": "zwave/Testing/testing_IR_2/67/0/setpoint/2",
    "temperature_state_template": "{{ value_json.value }}",
    "temperature_command_topic": "zwave/Testing/testing_IR_2/67/0/setpoint/2/set",
    "fan_mode_state_topic": "zwave/Testing/testing_IR_2/69/0/state",
    "fan_mode_command_topic": "zwave/Testing/testing_IR_2/68/0/mode/set",
    "mode_state_topic": "zwave/Testing/testing_IR_2/64/0/mode",
    "mode_command_topic": "zwave/Testing/testing_IR_2/64/0/mode/set",
    "temperature_unit": "C",
    "precision": 0.1,
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xf709ae3c_node17"
      ],
      "manufacturer": "Remotec",
      "model": "AC IR Remote (ZXT-120)",
      "name": "Testing-testing_IR_2",
      "sw_version": "1.20"
    },
    "name": "Testing-testing_IR_2_climate",
    "unique_id": "zwavejs2mqtt_0xf709ae3c_Node17_climate"
  },
  "values": [
    "49-0-Air temperature",
    "64-0-mode",
    "67-0-setpoint-1",
    "67-0-setpoint-2",
    "67-0-setpoint-1",
    "67-0-setpoint-1",
    "67-0-setpoint-1",
    "69-0-state",
    "68-0-mode"
  ],
  "mode_map": {
    "off": 0,
    "heat": 1,
    "cool": 2,
    "auto": 3,
    "resume": 5,
    "fan_only": 6,
    "dry": 8
  },
  "fan_mode_map": {
    "Auto low": 0,
    "Low": 1,
    "Auto high": 2,
    "High": 3,
    "Auto medium": 4,
    "Medium": 5
  },
  "setpoint_topic": {
    "1": "67-0-setpoint-1",
    "2": "67-0-setpoint-2",
    "3": "67-0-setpoint-1",
    "6": "67-0-setpoint-1",
    "8": "67-0-setpoint-1"
  },
  "default_setpoint": "67-0-setpoint-1",
  "discoveryTopic": "climate/Testing-testing_IR_2/climate/config",
  "persistent": true,
  "ignoreDiscovery": false,
  "id": "climate_climate"
}
hope it works with you @cookemmm

**Comment by waltervl** [comment]
Closing this issue. ZwaveJSUI specific issues like device configurations should be discussed on the ZwaveJSUI support channels eg https://github.com/zwave-js/zwave-js-ui/discussions
