### ISSUE TITLE
EnOcean blind timers not working correctly

### ISSUE THREAD

**Issue by didi31** [domoticz/domoticz#5417]
My configuration is an EnOcenan blind + Stop device with both reverse options enabled.
My blind is closed: level = 0 and state = Closed
I set a timer events on time/Open 100%
![image](https://user-images.githubusercontent.com/46863073/202243710-92c9a9b9-a1b3-4022-938e-8c7bffa0bc53.png)

The events occurs on time but the blind opens at 47% only.
Note that a timer events on time/close is working as expected and there is no problem on EnOcean switches.

**Comment by gizmocuz** [comment]
What happens when you time it with 50%? Does it open25%?

**Comment by didi31** [comment]
I'm on beta version 14779 and the bug evolves...
If I Ask for "open 50%" the blind stay closed at -520% 
![Screenshot_2022-11-26-20-27-50-019-edit_com android chrome](https://user-images.githubusercontent.com/46863073/204106103-ef29cf93-8611-47d9-8c01-671b00940927.jpg)

**Comment by gizmocuz** [comment]
Amazing! I think you have to debug the E ocean class
Add a lot of log messages

**Comment by didi31** [comment]
Unfortunatly I'm not a developper but I can do all the tests ;)

**Comment by waltervl** [comment]
There has been a change pushed to Domoticz (only build for windows currently) https://github.com/domoticz/domoticz/pull/5488

Please check beta build 14895 or later

**Comment by didi31** [comment]
I will not be able to test it before next monday.
My domoticz is on a rpi I will compile the source and test them.

**Comment by waltervl** [comment]
Update is now also availabe on all platforms with ./updatebeta (or use webUI)

**Comment by didi31** [comment]
I don't have any enocean dongle to test it on other platform than raspberry pi os. 😏 
I will not use ./updatebeta 😀

**Comment by gizmocuz** [comment]
@didi31 , as mentioned by walter you can update to the latest beta version also for your arm system

**Comment by didi31** [comment]
The problem is solved with the last beta version even if 90% open correspond to 50% in the real World 😉
