### ISSUE TITLE
Multiple reports of P1 Gasmeter not working after update to 2022.2 Stable

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#5418]
See Forum topic
[Gasmeter no longer correctly read after upgrade to 2022.2](https://www.domoticz.com/forum/viewtopic.php?t=39310)

Could be related to P1 Water meter implementation around 29/30 October?

**Comment by gizmocuz** [comment]
Please try to see if beta 14767 solved the issue

**Comment by waltervl** [comment]
According forum topic issue is solved.
