### ISSUE TITLE
V3.4836 HUE lights percentage not displayed

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#542]
Do not know when this happened.

on v4547 the hue lights displayed the percentage they were at(eg 80% or ON for 100%)

now on V3.4836 they just display ON while the lights are not at 100% but at 80% or even lower

HUE bridge v2.0
HUE lights latest type

to clarify
switch light to 50% from switch domoticz: 
webpage: light on
webpage mobile(iphone) light on but slider adjusted to 50%

click switch again, adjust slider to 60%
webpage:percentage appears
webpage mobile(iphone) slider adjusted.

so it looks like when lights are switched on it does not matter what percentage they are at. the switch icon displays on. after adjusting the slider the percentage appears.

so to make it 100% clear. The functionality is there because the mobile wepage updates the slider to the right percentage.
The percentage is however not displayed on the lightswitch icon. only after adjusting the slider from the switch itself(eg click it again and adjust slider)

press switch(notice slider)
press ON button(notice ON is dipslayed and not percentage)
press switch again
adjust slider(instantly percentage appears)

![1](https://cloud.githubusercontent.com/assets/16853535/13553282/74b111e2-e384-11e5-8c24-82b66b478de5.jpg)
![2](https://cloud.githubusercontent.com/assets/16853535/13553284/76f5c8c6-e384-11e5-9be4-26e734eb0a6c.jpg)
![3](https://cloud.githubusercontent.com/assets/16853535/13553285/7a9c5a80-e384-11e5-94d5-636bc7e869e7.jpg)
![4](https://cloud.githubusercontent.com/assets/16853535/13553286/7cd3301c-e384-11e5-8cc7-893eb97340ad.jpg)

**Comment by arjanwaard** [comment]
I will check for this in the Hue code.

**Comment by gizmocuz** [comment]
do note i just made some changes (nothing related to this, but to get a stable scene id)

**Comment by GravityRZ** [comment]
Thanks. Hope you find it.

**Comment by arjanwaard** [comment]
@GravityRZ could you check with the latest beta ?

**Comment by gizmocuz** [comment]
building a new beta for the web update, little moment

**Comment by gizmocuz** [comment]
New beta #4909 available

**Comment by GravityRZ** [comment]
i will ask Jumbotroll to compile one for synology since i am using his builds and am very happy with the complete package.
hopefully he does not mind to help me(and al of us)

**Comment by GravityRZ** [comment]
tested it just now and it seems the percentage is back again.
Thanks.

one remark however(do not know if this is intended)

taking into account that the lights are not set to 100% and follow their last setting

switching a light ON from the Hue hub(call a scene script, press a hue tap)
lights go ON and instantly display percentage

switching a light ON from domoticz or by sending a curl  json toggle command.
lights go ON instantly and display ON instantly
after 7 seconds the ON is replaced by percentage.

i can live with this functionality but again if this is not intended you might want to look into this
