### ISSUE TITLE
Python Plugin Connections returning garbage for websockets.

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#5421]
I'm on version 2022.1 build 14589.  
My operating system is Debian Bookworm
My Python ver is 3.9
It's a DomoticzEx plugin not legacy

I'm trying to build a plugin that uses web-sockets.  In a previous plugin that used websockets I got so many issues I gave up and used the websockets python library instead, which is not ideal.  So for this one I decided to do it the "right way" and use Domoticz connections.  It's been a struggle.  First off you can't send payload data from Domoticz to the websocket server if it's over 125 characters.  My websocket payloads can be up to a thousand.  I managed to work around that, by chopping it up, but I still don't like it.

Anyway the plugin is made to use Detectron2 for object recognition via web cams.  The client sends a list of cameras to the websocket server which then collects the images from each webcam processes them using Detectron2 and it replies with a JSON packet with all the info what each camera sees.  I've separated out the script that does image recognition from the plugin itself because Detectron2 really needs an NVIDIA GPU and my server doesn't have one.  Here's a snippet of client code:

```
def onMessage(self, Connection, Data):
	if "Status" in Data:  # HTTP Message
		if Data["Status"] == "101":
			reqst = '{"request":"interpret","packet":['
			for c in self.cameras:
				reqst = reqst+'{"name":"'+c+'","url":"'+self.cameras.get(c)+'"},'
			reqst = reqst[0:-1]
			reqst = reqst+']}'
			chunks = [reqst[i:i+125] for i in range(0, len(reqst), 125)]#Domoticz doesn't allow for message lengths > 125, so we gotta chop it up. It's always something isn't it?
			for chunk in chunks:
				Connection.Send({'Payload': chunk, 'Mask': secrets.randbits(32)})
			if int(Parameters["Mode6"]) > 2 or int(Parameters["Mode6"]) == -1:
				Domoticz.Log("WebSocket successfully upgraded")
		else:
			DumpWSResponseToLog(Data)
	elif "Operation" in Data:  # WebSocket control message
		if Data["Operation"] == "Ping":
			if int(Parameters["Mode6"]) > 2 or int(Parameters["Mode6"]) == -1:
				Domoticz.Log("Ping Message received")
			Connection.Send({'Operation': 'Pong', 'Payload': 'Pong', 'Mask': secrets.randbits(32)})
		elif Data["Operation"] == "Pong":
			if int(Parameters["Mode6"]) > 2 or int(Parameters["Mode6"]) == -1:
				Domoticz.Log("Pong Message received")
		elif Data["Operation"] == "Close":
			if int(Parameters["Mode6"]) > 2 or int(Parameters["Mode6"]) == -1:
				Domoticz.Log("Close Message received")
		else:
			if int(Parameters["Mode6"]) > 2 or int(Parameters["Mode6"]) == -1:
				DumpWSResponseToLog(Data)
	elif "Payload" in Data:  # WebSocket data message
		Domoticz.Log(Data["Payload"])

```
Very simple, after it connects it sends the request to the server.  If the server replies with something with a payload in it it writes it to the log.  First off when it successfully connects Domoticz seems to think my server's reply is ".MNN-.".  After that for debugging purposes the websocket server always replies with "test response".  However what I end up getting back is this "b'*I-.Q(J-.\xc8\xcf+N\x05\x00'"  I figured it was just my reply UTF-8 byte encoded, but it's not.  And it has those odd characters in addition to the hex.  Now I already know it's not my websocket server's issue because if I use the websocket library on the client side it works fine.  The only thing I can come up with is it's a bug in Domoticz.  Probably related to the masking or something.

**Comment by gizmocuz** [comment]
our websockets work perfect. The default web gui is using it

**Comment by Ittiz** [comment]
It uses the same exact functions as the python plugins?

**Comment by Ittiz** [comment]
OK! so I dug around and they don't seem to use the same functions.  Websockets for plugins are handled by code in this folder: [/hardware/plugins](https://github.com/domoticz/domoticz/tree/1d092b1bd88c883f811efc1f7013cf4e4adb5421/hardware/plugins)  So the websockets the GUI uses probably does work perfectly

**Comment by gizmocuz** [comment]
Not sure what this has to do with domoticz or home automation
Not you can use the json api in domoticz to update things

**Comment by Ittiz** [comment]
Machine vision is highly relevant to home automation (accurate presence detection, car/truck detection, ect...).  

So you mean do all the heavy lifting using outside of domoticz and use the JSON API to update things rather than getting the data back via websockets and using Plugin Devices to update things?  I suppose I could do that but it's a major code rewrite and more complicated.  I guess the easiest ways to get around scripting issues in Domoticz is to not use them?  Don't know why I didn't think of that before  ¯\_(ツ)_/¯

**Comment by gizmocuz** [comment]
From what I read (I could be wrong) is that you need to access your data via websockets. So Python <=> websockets
When you have the data, put them in Domoticz
So the first step is to get your python code working (outside domoticz), and when you have all data, use either the Domoticz python api or the JSON web API to push the data into domoticz

**Comment by Ittiz** [comment]
I already have this all working fully using the websockets and asyncio python libraries (but that's less than ideal for a Domoticz plugin as it causes constant "hardware has stopped working" in the error log).  So the code on websocket server side is working great.  Anyway thanks for the input, it's helped me figure out what direction I need to go in.

**Comment by Smanar** [comment]
I had same issue on older version, the code was so much buggy (never retry on recent version, but I m sure It's easy to find problem ), I have give up for classic REST request (with random error like you and other problem) and use now the python request library, fast enought to don't need async, but I still use the native code for a websocket client since years https://github.com/Smanar/Domoticz-deCONZ/blob/master/plugin.py

I had so much problem like the websocket size limited to 4096 bytes, trunkated json, and need to use a special fonction to parse data, but perhaps this code can help you

**Comment by gizmocuz** [comment]
But is this a Domoticz issue or a python issue?

**Comment by Smanar** [comment]
I'm not sure, but from what I understand, the problem is with his python plugin, and he need a websocket client.

**Comment by gizmocuz** [comment]
Yes that is what I understand. I am closing the issue, please feel free to continue on the Forum
