### ISSUE TITLE
Floorplan visable when button is disable 

### ISSUE THREAD

**Issue by Xenomes** [domoticz/domoticz#5423]
I notice it that the floorplan button was visible on my test system. (normal default install settings)
It is an clean setup that is 14 days old. cache, app cache and incognito modus make no difference. 

Domoticz build 14727

![afbeelding](https://user-images.githubusercontent.com/11648297/202845331-410d4c0e-3ce6-4ece-903f-8d04837116ed.png)

**Comment by gizmocuz** [comment]
go to setup->users and check if its enabled for your user

**Comment by gizmocuz** [comment]
@kiddigital , maybe we should remove the global active menus? And when localnetwork is active, use the first admin user available with its settings? Its a bit confusing now

**Comment by Xenomes** [comment]
Ah yeah, that function is working!
If it is now controlled at the user level, this part of the menu is redundant.
I will check the https://github.com/domoticz/domoticz/commits/development if i found a issue again 😅

**Comment by kiddigital** [comment]
> @kiddigital , maybe we should remove the global active menus? And when localnetwork is active, use the first admin user available with its settings? Its a bit confusing now

Hm.. let me look into that.. should be clear indeed which user is used when no login is required. Which could be the default admin.. 

No need for a global active menu, only at user level makes sense.. I will have a look
