### ISSUE TITLE
blinds working backwards with GoogleHome-Homebridge with 2022-2

### ISSUE THREAD

**Issue by Git-Bruno** [domoticz/domoticz#5424]
My blinds are working backwards with GoogleHome-Homebridge since my updgrade to 2022-2.
The reported states are correct but I have to request the opening to close blinds and vice versa.
After the upgrade I left the new reverse options in the blinds widgets to disable and everything works fine from the widgets or the scripts, runs and states.
The traces show that the orders in homebridge are the same regarless of the Domoticz level but the orders are reversed when they reach the plugin ZigbeeForDomoticz
It looks like something get messed up in Domoticz when a exection request comes to Domoticz via Homebrige/MQTT.
By instance, on a closing requested in GoogleHome I see 'openPercent: 0' in the Homebrigde log resulting in a cmd:On in the Domotics log.

Debug: MAIN SwitchLight idx:29 cmd:On lvl:-1  
Debug: MAIN SwitchLightInt : switchcmd:On level:-1 HWid:2  sd:2 20918a00000f0eae 18 244 73 13  
Debug: MAIN SwitchLightInt : switchcmd=="On" || level < 0, new level:0    
Debug: SQLH HandleOnOffAction: OnAction:

Shouldn't 'openPercent: 0' in Homebrigde give 'cmd:Off' or 'cmd:Close' in Domoticz ?

**Comment by pipiche38** [comment]
I have a similar behaviour with Alhau (Alexa).
It looks like there is a translation in Domoticz -most likely in the python3 framework- where a On is translated to Close, and Off is translated to Close
If I take the all sequence with Alexa:

> "Alexa switch **on** the blind"
>        a command "**Off**" is sent to Domoticz
>                    the "**Off**" command is translated and the plugin receive a "Close"

as from the plugin we cannot know if the command has been sent from the Domoticz device (widget) or from the domoticz/Api, there is no way to catch and hack it.

In addition this make the think even worst with SetLevel, as from Alhua (and I beleive homebridge)  if we say

"Alexa switch to 75% the blind" 
a command "SetLevel" 25% is send to Domoticz and so to the Plugin

The main question is why is the Python framework translating the Off into Close and On into Open ? Why should not leave that to the plugin side, which has the all means to correctly handle it ?
Because one think which is not taken in consideration in domoticz translation from Off -> Close and On -> Open is to not take in consideration the Blind Inverted mode

**Comment by gizmocuz** [comment]
Yes plugins need to be adjusted, some of them are already
It is for this very reason the blinds behavior is not working the same as in other home automation applications (like homeassistant)

**Comment by Git-Bruno** [comment]
Hi,
I confirm that plugin I use ,ZigbeeForDomoticz, has been modified to handle Open/Close commands from Domoticz. This works great with scripts and widgets.

From what I see in the logs : 
1) A request to close a blind translates in the Homebridge logs to 'command": "action.devices.commands.OpenClose' with parameter 'openPercent": 0'.
2) This results in 'cmd:On' in the Domoticz log. I believe this is before the plugin gets involved.

    Debug: MAIN SwitchLight idx:29 cmd:On lvl:-1 
    Debug: MAIN SwitchLightInt : switchcmd:On level:-1 HWid:2  sd:2 20918a00000f0eae 18 244 73 13
    Debug: MAIN SwitchLightInt : switchcmd=="On" || level < 0, new level:0
    Debug: SQLH HandleOnOffAction: OnAction:

This is the change in behaviour I can see : with 2022-1 a 'cmd:on' was issued by Domoticz when a 'command": "action.devices.commands.OpenClose' with parameter 'openPercent": 100' when received from Homebrigde.

So you are saying that, with 2022-2, the 'On' command sent to the plugin should be changed to a Close command by the plugin ?
This means that the plugins should figure out the source of the command in order to decide when to invert and when to leave it as is so widgets and scripts continue to works as they do today.

I am afraid that a change to make GoogleHome requests work would break operations from the widgets or the scripts, or did I miss something ?

**Comment by gizmocuz** [comment]
There are no On/Off commands anymore for blinds. There are Open/Close commands.
You could give zigbee2mqtt a change as a lot of people are using this to great satisfaction

**Comment by waltervl** [comment]
>You could give zigbee2mqtt a change as a lot of people are using this to great satisfaction

I am fully happy with ZigbeeforDomoticz. If the Python framework is not handling the new Open/Close behavior to its full extends we have to fix that. There are more plugins that handle blinds.

**Comment by waltervl** [comment]
@Git-Bruno what method do you use to connect GoogleHome-Homebridge? Is that also by a plugin? Because then it is perhaps an issue in the Domoticz GoogleHome-Homebridge communication.

**Comment by pipiche38** [comment]
Hi,I have the same issue with Alhau ( Alexa -DomoticZ). And my understanding is alhau send a On when the blinds needs to be closed and off when to open.However it looks like DomoticZ translate the on into open and off into close.So on one side I would say the issue is on alhau or home bridge, because they have to send open and close, but how should they do when the user is on dz 2022.1 or prior.For me the shame is the fact that DomoticZ is not providing the backward compatibility and is transforming the On/Off commands while it should be done on the plugin side for python plugin.So in summary there is no means to fix/work around on the plugin and until it is fixed on the home bridge and alhau side Envoyé de mon iPhoneLe 22 nov. 2022 à 12:03, waltervl ***@***.***> a écrit :﻿
@Git-Bruno what method do you use to connect GoogleHome-Homebridg? Is that also by a plugin? Because then it is perhaps an issue in the Domoticz GoogleHome-Homebridge communication.

**Comment by gizmocuz** [comment]
Domoticz does not listen to on/off but top open/close/stop as explained before

**Comment by waltervl** [comment]
So Alhua and Google homebridge (whatever plugin it is) need to be modified to the new situation in Domoticz with open/close instead of on/off

**Comment by pipiche38** [comment]
On one side yes, but why is DomoticZ converting on into open and off into close, it should ether reject the command or make the conversion configurable Envoyé de mon iPhoneLe 22 nov. 2022 à 12:58, waltervl ***@***.***> a écrit :﻿
So Alhua and Google homebridge (whatever plugin it is) need to be modified to the new situation in Domoticz with open/close instead of on/off

**Comment by waltervl** [comment]
You have to be more clear else nobody understands what is happening. How do you come to the conclusion that it is Domoticz that is converting open/close to on/off? It probably is Alhua or GoogleHomebridge that is sending on/off.
Is there a link to the integration?

**Comment by Git-Bruno** [comment]
@walterlv I have no plugin for blinds installed in Homebridge so I guess the request flows down to Domoticz via MQTT which was installed as part of the setup for Homebridge.

Just to be more clear in the description of  my problem. I never saw an On or Off command in Homebridge log. What I do see is 'command": "action.devices.commands.OpenClose' with parameter 'openPercent": 0' (request to close the blind)
or  'openPercent": 100'  (request to open the blind).  I guess this parameter is interpreted as Open/Close further down in Domoticz.  

In fact my point is not about On/Off vs Open/Close being used as at the end of the day this results in an Open or Close command sent by Domoticz to a plugin.
My point is that the result is just the opposite of what is expected  and to what it was in 2022-1. 

As a user I viewed Domoticz as the central place to get everybody happy by restoring the 2022-1 behaviour while supporting the Open/Close commands. This way all plugins  interfacing with Domoticz would continue to work without changes needed to support a new logic, just for compatibility sake. 

Again everything works fine when requests come from a widget or a script. No change needed here.
So may be it would be possible to restore 2022-1 behaviour just for the requests coming from Homebridge and other Alexa-like plugins ?

I have the feeling that this would adress many issues reported in forums about this inversion thing.

For now I need to fall back to 2022-1 as 2022-2 failed the WAF criterai :-)

**Comment by pitchoun38** [comment]
Sure, if you look https://github.com/domoticz/domoticz/issues/5424#issuecomment-1322121004

you can track what is happening in the logs

Domoticz log you get the On, inside the plugin you get an Open

**Comment by Git-Bruno** [comment]
This is a summary of what is in the Homebridge/Domoticz/ZigbeeForDomoticz logs.

Open requested :  HB: openPercent: 100 -> DZ: cmd:Off -> Z4D: Command: Close Level: 0
Close Requested : HB: openPercent: 0   -> DZ: cmd:On  -> Z4D: Command: Open Level: 100 

cmdOn and cmdOff may just be a message and not the actual command which might be Open or Close. @gizmocuz may comment on this.

**Comment by waltervl** [comment]
@pipiche38 @pitchoun38 (you are the same person  ;-) ) What appens if you say "Alexa switch **Open** the blind" ?
How Alexa sends the command to Domoticz? Also by MQTT?

@Git-Bruno What is the MQTT payload for an open/close command? And what application is creating that? Something is sending an On/Off command and it should send an Open/Close command. So if the MQTT payload is wrong the application that sends the payload to Domoticz should change.

**Comment by waltervl** [comment]
If you use the Homebridge-edomoticz plugin see this forum topic https://domoticz.com/forum/viewtopic.php?p=293567#p293567

See also https://github.com/PatchworkBoy/homebridge-edomoticz/issues/250

**Comment by Git-Bruno** [comment]
Thanks Walter for this update. These links sound as good leads. 
I do use the homebridge-edomoticz plugin. I'll search how to install the updated homebridge-edomoticz code.  
Somehow it's good to see that I am not alone in the Titanic :-).

As far as the MQTT payload. I am afraid I don't know where to find the data for the MQTT payload. All I have is the data in JSON format from the Homebridge log. Is this the MQTT payload you are refering to ?
If not, I will do some research and find out.  Help much appreciated here !

**Comment by pipiche38** [comment]
> @pipiche38 @pitchoun38 (you are the same person ;-) ) What appens if you say "Alexa switch **Open** the blind" ? How Alexa sends the command to Domoticz? Also by MQTT?
> 
> @Git-Bruno What is the MQTT payload for an open/close command? And what application is creating that? Something is sending an On/Off command and it should send an Open/Close command. So if the MQTT payload is wrong the application that sends the payload to Domoticz should change.

When saying 'Alexa switch off the blinds'

> Dz log: Nov 22 17:52:12 pi3 domoticz[15325]: 2022-11-22 17:52:12.638  Status: User: Admin (IP: 10.0.0.22) initiated a switch command (1114/Volet Bureau/On)

> Plugin log: onCommand - unit: 80, command: Open, level: 100, color:

What is the principle used to translate **On** into **Open** in Domoticz ?What I'm questioning here even if Alhau has to fix on their side and send the open or close command, Domoticz is making an assumption to translate the On into Open, which should configurable are left to the plugin inside the python framework   to decide

[EDIT] I have reported the same to Alhau forum,

http://alhau.free-bb.fr/sujet-631327-836651-103968-1-Domotocz-New-Blinds-Behaviours-Not-Compatible.html#num0
http://alhau.free-bb.fr/sujet-631328-836310-103968-1-Nouvelle-Gestion-Volets-Dans-Domoticz-Beta.html#num1

**Comment by Git-Bruno** [comment]
I have installed the code from @ksacca for the Homebridge-edomoticz plugin. The blinds are now working as with the legacy blind support set to 1. Thanks Walter.

**Comment by waltervl** [comment]
Great, then we will close this issue. 
I suppose after alhau (Alexa Skill) made its changes to support new Domoticz Blinds behavior this also will work,
