### ISSUE TITLE
Enphase Envoy with firmware D7

### ISSUE THREAD

**Issue by cortobass** [domoticz/domoticz#5427]
I tried the latest beta (build 14775) and the Envoy plugin does not work for me. I have a Envoy S Metered gateway with firmware D7.0.88.
I get this in the log:
2022-11-24 17:31:49.590 Status: Enphase Envoy S Metered: Worker started...
2022-11-24 17:31:54.013 Status: Enphase Envoy S Metered: Connected, serial: 122234543210, software: D7.0.88
2022-11-24 17:31:54.779 Error: Enphase Envoy S Metered: Invalid data received!
2022-11-24 17:32:25.445 Error: Enphase Envoy S Metered: Invalid data received!

The username and password are the ones I use to authenticate on https://enlighten.enphaseenergy.com/

**Comment by gizmocuz** [comment]
Could you install beta 14778

I added more information when invalid data is received

Your username is the master username, not an additional account?

Your password, is this a simple password with letters (upper/lowecase) and numbers, no special characters?
If it contains special characters (so no numbers/letters) could you change this and try again (this can/should then be fixed later)

If it still does not work, could you start Domoticz with hardware debugging on

first make sure Domoticz is stopped

`sudo service domoticz stop`

```
cd domoticz
./domoticz -loglevel all -debuglevel hardware

```
With the above command you can see all data returned by the Envoy unit before you see the error

**Comment by cortobass** [comment]
Yes, it was due to a special character in my password. I replaced it and everything works fine now. Thank you.

**Comment by gizmocuz** [comment]
can you tell me what character this was? I will try to fix this here (urlencode)

**Comment by cortobass** [comment]
The + sign

**Comment by gizmocuz** [comment]
Is it possible you could try beta 14779 with your original password? Hope this works

**Comment by cortobass** [comment]
Yes it works. I tried also a character used in my country (É) and it works too.

**Comment by gizmocuz** [comment]
Great, thanks for the feedback!
