### ISSUE TITLE
Mobile view on dz beta without floorplans

### ISSUE THREAD

**Issue by megamarco833** [domoticz/domoticz#5429]
Hello, withlatest beta release in my  mobile smartphone if i use mobile browsers to see domoticz i see this menu without the floorolans menu and with all menu icons on top that are all placed on the right side. 
Here below a screenshot. 
With old releases i was able to see the menu of floatplanes and all the menu icons was on opposite side (left) 
Thanks 
![Screenshot_20221124_235002](https://user-images.githubusercontent.com/44502572/203871960-5c540f7d-4f00-4fbc-83b4-0168c07f682a.jpg)

**Comment by gizmocuz** [comment]
If you miss your floorplans, check under setup->users, select your user and make sure the floorplan is enabled

**Comment by megamarco833** [comment]
> If you miss your floorplans, check under setup->users, select your user and make sure the floorplan is enabled

You are right.
It was introduced in latest beta? Because i didn't change it recently and before upgrade i was able to see the whole menu :-)

Last question what does it means inside user option the first one: "share option" (allow remote devices sharing with this user)??
Thanks!

**Comment by gizmocuz** [comment]
@megamarco833 , yes, the default admin user that was originally configured in the settings is now translated to a real user.

The share option is when you have a remote domoticz installation and this wants to access sensors on your local domoticz
