### ISSUE TITLE
Compilation error on RPi 1 with Arch Linux ARM

### ISSUE THREAD

**Issue by warptozero** [domoticz/domoticz#543]
I couldn't get it to compile, it gave me the following error:

```
[ 27%] Building CXX object CMakeFiles/domoticz.dir/main/DataPush.cpp.o
[ 28%] Building CXX object CMakeFiles/domoticz.dir/main/domoticz.cpp.o
[ 28%] Building CXX object CMakeFiles/domoticz.dir/main/EventSystem.cpp.o
{standard input}: Assembler messages:
{standard input}:32144: Warning: end of file not at end of a line; newline inserted
{standard input}:32202: Error: unknown pseudo-op: `.l54'
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/archlinuxarm/PKGBUILDs/issues> for instructions.
CMakeFiles/domoticz.dir/build.make:182: recipe for target 'CMakeFiles/domoticz.dir/main/EventSystem.cpp.o' failed
make[2]: *** [CMakeFiles/domoticz.dir/main/EventSystem.cpp.o] Error 4
CMakeFiles/Makefile2:71: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

It is build like this:

```
# Dynamicly link to libopenzwave instead of static link
sed -i 's/find_library(OpenZWave NAMES libopenzwave.a HINTS "..\/open-zwave-read-only" "..\/open-zwave-read-only\/cpp\/build")/find_library(OpenZWave NAMES libopenzwave.so)/' CMakeLists.txt

cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt
```

The complete [log](https://github.com/domoticz/domoticz/files/160569/domoticz_log.txt) and [PKGBUILD](https://github.com/domoticz/domoticz/files/160574/domoticz_PKGBUILD.txt).

**Comment by nayrnet** [comment]
your running out of memory, you'll need to create some swap space to build from source.. 512M is not enough.

**Comment by gizmocuz** [comment]
Found a good website here, but do note it is not recommended to enable a swap file

http://raspberrypi.stackexchange.com/questions/70/how-to-set-up-swap-space

sudo dd if=/dev/zero of=/path/to/swapfile bs=1M count=1024 # For 1GB swap file
sudo mkswap /path/to/swapfile
sudo swapon /path/to/swapfile

for example

sudo swapoff -a
sudo dd if=/dev/zero of=/var/swapfile1GB bs=1M count=1024 # For 1GB swap file
sudo mkswap /var/swapfile1GB
sudo swapon /var/swapfile1GB
