### ISSUE TITLE
Blinds, non case "inverted" under Windows server

### ISSUE THREAD

**Issue by PHIL-IP** [domoticz/domoticz#5431]
Hi, 
yesterday I have put the last version of Domoticz on 2 different servers, 1 under Raspbian and the other under Windows Server.
For the first one I have a checkbox to invert blinds, but in the Windows version this case is missing and all blinds are now inverted in theyre usage.
Is the presence of this checkbox planned in the Windows version to correct this situation ?

**Comment by gizmocuz** [comment]
Please use the forum! (and clear your browser cache)... there is no difference in version
