### ISSUE TITLE
No Setpoint Device for Danfoss Thermostat DRS21

### ISSUE THREAD

**Issue by ftsikogi** [domoticz/domoticz#5432]
[mqtt_ad_record_52.log](https://github.com/domoticz/domoticz/files/10115893/mqtt_ad_record_52.log)

I have recently migrated from OpenZwave to ZwaveJS. I have also enabled MQTT auto discovery and everything works as expected except one thing.
My Danfoss DRS21 Thermostat cannot be operated from Domoticz. I am able to read temperature and set the setpoint from the zwaveJS UI but there is no device created for setting the setpoint from Domoticz. I can read the temperature though.

![danfoss](https://user-images.githubusercontent.com/105057227/204551055-26b1d233-8c4c-4918-97b8-4ce1ced1a06d.JPG)

**Comment by waltervl** [comment]
As discussed here https://www.domoticz.com/forum/viewtopic.php?f=82&t=39456 please add the correct MQTT topics so that developers can reproduce your issue.

**Comment by ftsikogi** [comment]
> As discussed here https://www.domoticz.com/forum/viewtopic.php?f=82&t=39456 please add the correct MQTT topics so that developers can reproduce your issue.

Attached the relevant file. Thanks for your help.

**Comment by gizmocuz** [comment]
I miss the config topic + payload

**Comment by ftsikogi** [comment]
Attached the config topic. How do I capture the payload if it is not already captured?
Thank you!
[mqtt_ad_record_config.log](https://github.com/domoticz/domoticz/files/10120788/mqtt_ad_record_config.log)

**Comment by gizmocuz** [comment]
You should use a application like MQTT explorer

**Comment by waltervl** [comment]
I modified the instruction in https://www.domoticz.com/wiki/MQTT#Debugging_MQTT_AutoDiscover_devices to get config statements in the log. I hope it works....

Step 4 If the device is not discovered correctly in Domoticz please use the Rediscover Node button in Zwave-JS-UI to get all the MQTT info in the log.

**Comment by ftsikogi** [comment]
[payload.txt](https://github.com/domoticz/domoticz/files/10121663/payload.txt)

If it is not in the correct readable format please let me know. Thank you again.

**Comment by gizmocuz** [comment]
@ftsikogi , this is not the config topic and/or payload
Have you used the application MQTT Explorer to connect to your MQTT broker?
Did you find the auto discovery topic? It could start with homeassistant
inside here you see folders, like climate
inside some tree childs down you see a config, the topic is named something like homeassistant/climate/xx/xx/config
I would like to know the complete topic name
If you click on it, you will see it's config object (json format), please copy/paste that here as well

**Comment by ftsikogi** [comment]
@gizmocuz , MQTT explorer is connected to my MQTT broker. I am attaching a snapshot of what the explorer shows. Unfortunately there is no config topic. I am also attaching the relevant setpoint topics that i am able to find. If you want i can give you the whole list of topics regarding the specific node ID.

[setpoint_topics.txt](https://github.com/domoticz/domoticz/files/10145963/setpoint_topics.txt)
![mqtt_explorer_snapshot](https://user-images.githubusercontent.com/105057227/205431544-407d70e8-7b93-4224-8f05-a5ba93fdb156.JPG)

**Comment by gizmocuz** [comment]
There should be config topics underneath the auto discovery prefix (homeassistant for example)
If not, could you stay in MQTT explorer and then restart the MQTT-AD hardware in domoticz (disable/enable) , maybe the config messages are not retained (could be an option in zwavejs UI)

**Comment by gizmocuz** [comment]
Else please join our slack channel and send me a private message, i could debug remotely

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

**Comment by ftsikogi** [comment]
[config_topic.txt](https://github.com/domoticz/domoticz/files/10147468/config_topic.txt)

I had to reboot my Raspberry in order to show config topics. I hope that this is what you were asking for. Thank you!

**Comment by gizmocuz** [comment]
Yes perfect! Yes, rebooting has the same effect as restarting the hardware which was less drastic 😁

Are you sure this are all the config objects for this device? Because I miss the thermostat itself

At the moment you have shared all config objects of type 'sensor'

domoticz/sensor/xx/xx/config

do you also have config object for 'climate' like

domoticz/climate/xx/xx/config

Maybe when you type 'thermostat' in the top search bar in MQTT explorer you find more config objects

If you do not have climate config objects, then this the problem you are facing, but I suspect this config object exists

Did you try to update zwavejs-ui to the latest version?

Did you try (after making sure you have the latest version) to press the include button on the device to let it send the node configuration again?
Or to exclude and include the device again?

I found other users having similar issues here

https://community.home-assistant.io/t/danfoss-roomsensor-014g0160-setpoint-not-showing-in-ha/7431/3

**Comment by ftsikogi** [comment]
Dear @gizmocuz   restarting the hardware does not populate the config topics only the full restart does the job for some reason.  I am running ZwaveJS version 10.3.0. I checked for new updates but there aren't any. I tried to exclude and include again my device but still there are no climate or thermostat config objects. Please note that the new ID of the device is now 55 (old was 52) 

I missed only the below config which is irrelevant though:

Topic:
domoticz/binary_sensor/Danfoss_Room_Thermostat/battery_islow/config

Value:
{"payload_on":true,"payload_off":false,"value_template":"{{ value_json.value }}","device_class":"battery","state_topic":"domoticz/55/128/0/isLow","json_attributes_topic":"domoticz/55/128/0/isLow","device":{"identifiers":["zwavejs2mqtt_0xcaf3032a_node55"],"manufacturer":"Danfoss","model":"Room Thermostat (MT2649 / DRS21)","name":"Danfoss Room Thermostat","sw_version":"1.0"},"name":"Danfoss Room Thermostat_battery_islow","unique_id":"zwavejs2mqtt_0xcaf3032a_55-128-0-isLow"}

**Comment by waltervl** [comment]
This issue seems to be related although it does not use mqtt. 
 https://github.com/home-assistant/core/issues/46643

**Comment by ftsikogi** [comment]
> This issue seems to be related although it does not use mqtt. [home-assistant/core#46643](https://github.com/home-assistant/core/issues/46643)

Indeed seems to be the exact same issue.

**Comment by gizmocuz** [comment]
You could try to ask the guys from ZWaveJS-UI to support the device in MQTT

**Comment by ftsikogi** [comment]
> 

Yes I will. Thanks for your help!
