### ISSUE TITLE
incorrect handling of negative values in counter day graph

### ISSUE THREAD

**Issue by WillemD61** [domoticz/domoticz#5436]
I am using a counter device (RFX meter counter, divider 100) to store costs in Euro. The costs are updated every hour and can increase and decrease. (I don't see other suitable devices for cost tracking. I have tried custom devices but these don't show daily totals, only max,min and avg)

Bug report: The increase/decreases are stored corrrectly in the meter table but are not displayed correctly in the day graph. The day graph shows the countertotal plus counterdecrease, for example at 11:00 it shows 5.09-0.03=5.06 instead of a -0.03.

In the example below the values of 11:00 to 14:00 are incorrectly displayed.

Notes:
* simliar errors might occur in weekly and monthly graphs, but I don't have negative values there yet.
* in below overview only values at 00 minutes are shown, the values in the meter table from 05 to 55 minutes are present in the table but not shown in below overview
* the device has a divider of 100
* the daily total shown in the device icon is correct (i.e. matching the table values)
* the "usage last 24 hour" graph is incorrect, but the "usage last week" is correct (i.e. showing correct daily total for current day)

Below is a table showing the values displayed in the day graph with next to it a column showing the values from the meter table and finally the calculated difference from one meter value to the other.

```
Displayed in graphs (xls download)			value in meter table	(difference to next value)/100
DateTime	Costs			
2022-11-29 18:00:00	0,27					261				0.27
2022-11-29 19:00:00	0,36					288				0.36
2022-11-29 20:00:00	0,25					324				0.25
2022-11-29 21:00:00	0,2					349				0.2
2022-11-29 22:00:00	0,16					369				0.16
2022-11-29 23:00:00	0,05					385				0.05
2022-11-30 00:00:00	0,21					390				0.21
2022-11-30 01:00:00	0,21					411				0.21
2022-11-30 02:00:00	0,04					432				0.04
2022-11-30 03:00:00	0,04					436				0.04
2022-11-30 04:00:00	0,04					440				0.04
2022-11-30 05:00:00	0,04					444				0.04
2022-11-30 06:00:00	0,06					448				0.06
2022-11-30 07:00:00	0,07					454				0.07
2022-11-30 08:00:00	0,21					461				0.21
2022-11-30 09:00:00	0,22					482				0.22
2022-11-30 10:00:00	0,05					504				0.05
2022-11-30 11:00:00	5,06					509				-0.03
2022-11-30 12:00:00	4,95					506				-0.11
2022-11-30 13:00:00	4,9					495				-0.05
2022-11-30 14:00:00	4,88					490				-0.02
2022-11-30 15:00:00	0,03					488				0.03
2022-11-30 16:00:00	0,06					491	


```

**Comment by gizmocuz** [comment]
Correct, this device was not made to handle negative values
Could you post some screenshots of the graphs that go wrong? I think the graph shows the results in blocks/hour?

**Comment by WillemD61** [comment]
I don't know how to post a screenshot here, but I have already included all values of the graph so what is the added value anyway?

The first two columns of the data above show the graph data, download created by pressing the hamburger icon at the top right corner of the graph, a plain download. You can see the incorrect values at 11:00,12:00,13:00 and 14:00.

You can also see the corresponding value in the meter table in the middle column (found via sql on the meter table). The last column was calculated in a spreadsheet.

**Comment by Zuikkis** [comment]
I have the same problem.

It's interesting that kwh counter **does** support negatives. But when you make a custom counter with € units, negatives no longer work. I got some incredibly large integer values in the 24h graph, looks like negative numbers roll over to unsigned integer? 

Even a managed counter with € units does not work. 24h graph doesn't show negatives. In monthly view daily costs are properly viewed, but report page shows incorrect monthly totals.

**Comment by gizmocuz** [comment]
@Zuikkis , yes it looks like a unsigned issue (probably uint64_t)
Could you send me a private message on our slack channel, I would like to debug this with a copy of your database

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

**Comment by gizmocuz** [comment]
@Zuikkis , after receiving your database, first thing I noticed you have multiple values per day in the *_calendar table.
In these tables there should only be one value per day (this table is for day values)
Removing your 0 values between the actual values, solves the report issue

**Comment by Zuikkis** [comment]
Ok thanks!

So @WillemD61 it's possible to get this working using managed counter. Only drawback is that negative values are not shown in 24h graphs.

@gizmocuz it would be much cleaner to have regular counters support negative increments, don't you think?

**Comment by Zuikkis** [comment]
(posted this first to wrong issue, sorry) :)

BTW, here is the issue where min/max is fixed to first/last for the kWh counter:
https://github.com/domoticz/domoticz/issues/4380

I guess you could apply similar patch to other counters as well.

**Comment by waltervl** [comment]
@WillemD61 can you check in latest beta if this issue is solved with https://github.com/domoticz/domoticz/pull/5637

**Comment by waltervl** [comment]
No feedback. Assume the issue is fixed. If not please reply to have it reopened.
