### ISSUE TITLE
value field not consistent with difference between consecutive counter fields (in multimeter_calendar)

### ISSUE THREAD

**Issue by WillemD61** [domoticz/domoticz#5437]
With reference to closed issue 5353.

An Electricity P1 smart meter device is updated with a HTTP poller every minute. I am performing a daily check on the values stored in the value fields in the multimeter_calendar table and am comparing those to the difference between the corresponding counter field of today and the counter field of yesterday. 

**BUG: More often than not value1 is not equal to counter1 minus yesterday's counter1.** The other values and counters (for usage2 and return1 and return2) are correct.

So the values stored in the dbase are inconsistent. The value field should equal the difference between two consecutive counter fields.

For value1 there is almost always a small value missing. I suspect due to the same issue as reported in issue 5353, i.e. the first update of the day is incorrectly handled. (Usage1 is the electricity usage at a low price rate, valid at midnight.)

It could also be the last values of the previous day instead of the first of the new day. Because I have another device that was updated once per day at 23:58 and that was often missing the update (in the meter_calender table, either totally, sometimes only the value but not the counter). After I moved the update to 23:54 the problem has not reoccurred.

**Comment by gizmocuz** [comment]
Please have a look in **CSQLHelper::AddCalendarUpdateMultiMeter**

I can't see where it could go wrong....

The low-price rate starts (here in the Netherlands, so I assume yours as well) from 23.00pm till 07.00am

Data is pushed in the multimeter table every 5 minutes

So, there is a small change indeed that your first value of the day is somewhat higher than reported at your minute interval between 00:00:00 and 00:04:59

Nevertheless, we calculate with counter values in the end. So, in the end for your week/month/year or even the counter values in the report, they should be very accurate

If you want to make the daily value very accurate, you need (in the above-mentioned function), for the P1 meter, maybe perform the exact same action as in **CSQLHelper::AddCalendarUpdateMeter**, or even better take the counter values from the DeviceStatus table and store these as the initial start of the day counter

**Comment by WillemD61** [comment]
I will analyse the code, both for meter and multimeter, but am not very used to the C language so might take some time.

**Comment by WillemD61** [comment]
I found the problem in the query at line 7425 of SQLHelper.cpp

result = safe_query(
			"SELECT MIN(Value1), MAX(Value1), MIN(Value2), MAX(Value2), MIN(Value3), MAX(Value3), MIN(Value4), MAX(Value4), MIN(Value5), MAX(Value5), MIN(Value6), MAX(Value6) FROM MultiMeter WHERE (DeviceRowID='%" PRIu64 "' AND Date>='%q' AND Date<='%q 00:00:00')",
			ID,
			szDateStart,
			szDateEnd
		);

When this is run immediately after midnight (I used the hourly backup 00 to replicate the situation), it uses all records between yesterday 00:05:00 and today 00:00:00. The minimum of value1 is the value1 of yesterday 00:05:00, which is higher than the value1 of yesterday 00:00 as stored in counter1 in the multimeter_calendar table. 

At line 7447 the total_real is calculated as the difference between max and min, so here the increase between 00:00 and 00:05 is missing. This calculated value is later used for value1 in the insert statement at line 7464.

The counter value is correct, since this is the max of value1, i.e. the value of today 00:00 (line 7449). 

This causes the inconsistency in the dbase, since the counter1 values of consecutive days are correct, but the increase of the first 5 minutes of the day is missing in the value1. (if you don't have low electricity rate around midnight or live in a country where you can have solar production at midnight, then the same problem would occur for the other values). 

I can also confirm that in my current case the missing value was 10 for today, which was indeed the increase between 00:00 and 00:05.

I think there is an additional check needed against the multimeter_calendar values of yesterday to obtain correct values.

I also checked the AddCalendarUpdateMeter() function for the same problem but found that for these devices there is a first value in the database at 1 or 2 seconds past midnight (instead of 5 minutes like for the multimeter), so as result there is no difference between yesterday's counter in meter_calendar and the first value in the meter table.

**Comment by waltervl** [comment]
Check also this discussion: https://github.com/domoticz/domoticz/issues/3896

**Comment by WillemD61** [comment]
> Check also this discussion: #3896

Yes, same issue, but analysis going of in the wrong direction with in the end no solution......

Problem could be simply solved by including yesterday's counter1,counter2,counter3,counter4 from the multimeter_calendar table in the calculation of min and max. (or by adding multimeter values to the multimeter table one second after midnight, like is done for devices in the meter table)

A workaround might be to run a consistency check after midnight and update any incorrect values in the xxxxx_calendar tables, assuming the counters are correct. This is what I do currently using a python program.

**Comment by gizmocuz** [comment]
@WillemD61 , your first assumption is wrong

"it uses all records between yesterday 00:05:00 and today 00:00:00."

because it is using all records between yesterday 00:00:00 and today 00:00:00

**Comment by WillemD61** [comment]
No, you are wrong, and it is not an assumption, it is the result of factual analysis. I used the 00:00 backup database for checking the query.

The select statement would indeed select records between yesterday 00:00:00 and today 00:00:00 except for the fact that those records don't exists in the multimeter table at that moment. The earliest record is the record of 00:05:00 yesterday. The 00:00 record has already gone.

And if the query would be run before 00:00 then the 00:00 record of today does not exists, so if you just use the multimeter table there is always 5 minutes missing. (and values can become large if one is charging/discharging batteries at the time)

Anyway, the aim is to calculate the new counter and the new value to insert into the calendar table, so:
1) The new counter is the last value available in the multimeter table (not the min, not the max, but the last). Normally this is the 00:00:00 record unless this is not available, then it is that last one available from earlier in the day.
2) The value change is the difference between that value found at step 1 and the previous counter from the calendar table. Only in the case this counter is not available (for a new device for example) you should take the earliest available value from the multimeter.

Why should you take min and max, instead of first (=calendar) and last? This is probably also the reason why counters can't handle negative values. And probably also why devices that are updated only once per day don't work well. (although I have not analysed those two in detail, since I don't know where to find that in the code)

**Comment by gizmocuz** [comment]
Well I am sure I checked this 100 times as I wrote the code.
First the shortlog is made, then ~1700 seconds later the daily schedule is executed (see MainWorker::Do_Work())

The query is also not executed before 00:00:00 

And this has nothing to do with negative values, as this is a continues incrementing counter

And best to analyze the code first, set breakpoints and do a step-by-step debugging.
You can quickly add a call to 'ScheduleDay()' at the end of the SQLHelper constructor

**Comment by WillemD61** [comment]
As stated, I am not very proficient in C, so am not going to do actual change of code for debugging. I am just trying to read and follow the logic and rund the sql, if you point out where to look as above.

There seems to be some critical timing issue anyway, since today I did NOT see a difference between value and two consecutive counters (for the first time in many days). Therefore I looked in today's backup database of 00:00 and now I see yesterday's  00:00:00 record for the P1 meter. This was not present in the previous 00:00 backup.

So this supports my conclusion, if yesterday's 00:00 record is present like it is today, then it works well (since that value is the same as the previous counter). But if it is not, like it was yesterday, then you get a difference. 

So where and when does the 5 minute update of the (multi)meter table occur? Is that what you call "shortlog" ?

**Comment by gizmocuz** [comment]
You should not use your automatic database backups to do measurements/calculation as this is taken at a different interval (see mainworker DoWork()

Yes, the 5 minutes interval logs we call shortlog

**Comment by WillemD61** [comment]
I have looked into the code further. Hope I am looking at the right place. I searched for "insert into multimeter"and "delete from multimeter".

I see:
1) sqlhelper.h first calling scheduleshortlog and then calling scheduleday, defined in sqlhelper.cpp
2) in sqlhelper.cpp:
      a) in scheduleshortlog there is a call to updatemeter and updatemultimeter (this is adding the new 00:00:00 record?)
      b) and at the end of scheduleshortlog there is a call to cleanupshortlog (this is removing the old 00:00:00 record?)
      c) in scheduleday there is the call to addcalendarupdatemeter and addcalenderupdatemeter (this is calculating and inserting the xxxxx_calendar records)

When a record is inserted I only see the insert of the values, not the timestamp, and I cannot find where this is done. Is that added by the "safe_query" somewhere? Just out of interest.

Most importantly:  the cleanupshortlog seems to remove the 00:00:00 record of yesterday when it is run after 00:00:00 today? Correct? **So that would mean that the scheduleday activities are performed without yesterday's 00:00 record present**, as concluded in my analysis above.

Strange thing is that apparently sometimes, the 00:00:00 record is still present (like it happened today). Could this have something to do with the timing of the commit to the database, i.e. the 00:00:00 removal has not been comitted yet?

The code is in principle clearly structured but clearly not always behaves the same way, therefore I suspect a timing issue caused by the actual data present in the database. If that is not the issue, with the current sequence of steps, I would expect the  current calculation always to result in a difference, which in most cases it does in my experience.

**If the above is correct, then all you have to do to solve this issue is remove the cleanupshortlog out of the scheduleshortlog and move it to a point immediately after the scheduleday activities are finished (or at the end of those activities).**

**Comment by WillemD61** [comment]
Just to add to this further: a workaround could be to extend the shortlog from 1 day to 2 days in the settings. This then also makes sure that yesterday's 00:00 record is still available when running the scheduleday activities.

**Comment by gizmocuz** [comment]
You can even set the shortlog to 7 days in the settings It is already there

**Comment by WillemD61** [comment]
Despite extending the shortlog period to 2 days, the problem reoccurred, so I looked into the database again.

I found that this time there is no yesterdays 00:00:00 record, but there is a 00:00:01 record. So that means that the last record included in the select statement the previous shortlog run was that of 23:55:00. The start counter value for the last day therefore was set to the value of 23:55:00 the day before.

Then running today's shortlog calculation it started with the 00:01:00 value of yesterday and ended with the 00:00:00 value of today. This then determined the new counter and the usage1 value. So in the end the increase from 23:55:00 to 00:00:01 was included in the counter difference but missing in the usage1 value (and this was confirmed by the actual number found).

So this again supports the conclusion:
1) the startpoint of the calculation should be previous counter (and only if it does not exist you should take the first shortlog)
2) the endpoint should be last shortlog
3) point 2 results in the new counter and the difference between point 2 and 1 is the usage value
4) cleanup of the shortlog should be done after the scheduleday activity

**Comment by gizmocuz** [comment]
Maybe another solution is to modify the 'cleanupshortlog' and let it keep the history of xx days + 5 minutes (maybe 10 minutes)
This will result in only 2 extra records

If possible, modify this line

`std::string szQueryFilter = "strftime('%s',datetime('now','localtime')) - strftime('%s',Date) > (SELECT p.nValue * 86400 From Preferences AS p WHERE p.Key='5MinuteHistoryDays')";
`
to

`std::string szQueryFilter = "strftime('%s',datetime('now','localtime')) - strftime('%s',Date) > (SELECT p.nValue * 86400 From Preferences AS p WHERE p.Key='5MinuteHistoryDays') + (10 * 60)";
`

and perform a test to see if that solves your issue

Calling cleanupshortlog after scheduleday will only flush the shortlog once a day resulting in way more records then 1 (2,3,...7) days

**Comment by WillemD61** [comment]
That will not solve it since this results in the same situation as extending the shortlog period to more than 1 day via the settings. The query retrieves the shortlog of the last day, no matter how many records are there before that day. If the earliest record in the query does not match yesterday's counter, then you get the difference.

To address your concern about the number of records, it would be better to continue running cleanupshortlog as today, except when (ltime.tm_hour != m_ScheduleLastHour) since that is when the scheduleday will be run (as specified in mainworker.cpp)

Unfortunately I am unable to perform code changes and testing.

**Comment by WillemD61** [comment]
Just to add another reason to move from min/max selection to first/last selection for the determination of new counter and daychange value:

I tested a counter going from 13 to 20 to 18 to 21 to 18 during one day. This would be a day increase of 5, but with min/max selection this ends up as a day increase of 8.

I know counter graphs get messed up by decreases, but if the daily switchover would be done correctly at least the database would be correct.

**Comment by waltervl** [comment]
@WillemD61 can you check if this issue is solved in latest beta with https://github.com/domoticz/domoticz/pull/5637 ?

**Comment by waltervl** [comment]
No feedback. Assume the issue is fixed. If not please reply to have it reopened.
