### ISSUE TITLE
Replace device - "Unit" stays from the old device 

### ISSUE THREAD

**Issue by eladvez** [domoticz/domoticz#5438]
When replacing a device, the Unit is not replaced.

[Link issue 5102](https://github.com/domoticz/domoticz/issues/5102#issuecomment-1017520165):
> In the next beta the logic is as following
> - The old device (where you pressed 'Edit/Replace Device') will get the following parameters from the new device
>  ** Hardware ID, DeviceID, Unit, Type, SubType
>  ** (not the name)
> - The new device is deleted

But NO - Unit stays from the old device:

![Domoticz1](https://user-images.githubusercontent.com/24221451/205117003-90f65c05-c4df-49ed-a2ec-e93452a1b7fc.png)
![Domoticz2](https://user-images.githubusercontent.com/24221451/205117020-3194f510-bb68-47ae-a915-dd638a6e7e1c.png)
![Domoticz3](https://user-images.githubusercontent.com/24221451/205117023-94c55af9-a0ee-4742-8aec-8ae8aaab71d3.png)
![Domoticz4](https://user-images.githubusercontent.com/24221451/205117027-0c8e15cf-a9d2-47ad-a1d1-da6851f88dad.png)
----
![Domoticz5](https://user-images.githubusercontent.com/24221451/205117597-5aea4650-075c-41bf-939e-07a366aa2f1f.png)

**Comment by gizmocuz** [comment]
The unit should be transfered as well, have a look in '**CWebServer::RType_TransferDevice**'

**Comment by eladvez** [comment]
Exactly!

Select
```m_sql.safe_query("SELECT HardwareID, DeviceID, Unit, Type, SubType FROM DeviceStatus WHERE (ID == '%q')", newidx.c_str());```
taken from a NEW device (which is replaced).

And then we update the OLD device
```m_sql.safe_query("UPDATE DeviceStatus SET HardwareID = %d, DeviceID = '%q', Unit = %d, Type = %d, SubType = %d WHERE ID == '%q'", newHardwareID, newDeviceID .c_str(), newUnit, devType, subType, sidx.c_str());```

But in this case, we update the IDX of the OLD device, and use UNIT from the NEW.
Logically, Unit should also be from the OLD. It was created with this Unit value.

I think that it is impossible to update the Unit value here.

Or I misunderstand Unit?

**Comment by gizmocuz** [comment]
Maybe, imagine you have a old temperature device that gets a new unit when the battery has changed (DeviceID stays the same)

Old:
idx=1
DeviceID=12345
Unit=10

New:
idx=8
DeviceID=1234
Unit=3

We should replace the Unit as well

If you look in the code also the Unit is set to the new device unit

The OLD device is not deleted, it gets the same parameters as the new device, the new device (new idx) will be deleted

**Comment by eladvez** [comment]
Probably I incorrectly expressed my thought.
Here it is difficult to understand which device is NEW, which is OLD )

But my thought is this - if the device moves, then both IDX and Unit should move - these identifiers were originally when the device was CREATED.
I believe that it is the combination of these parameters that is unique.

I am using the **stas-demydiuk/domoticz-zigbee2mqtt-plugin** plugin.
Problem in [plugin function](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/blob/6219f70a1f22c80e4222e7d7471ee2446ed480d5/devices/device.py) 
```python
    def get_device(self, address, alias):
        device_id = address + '_' + alias
        devices = domoticz.get_devices()

        for unit, device in devices.items():
            if device.DeviceID == device_id:
                return device
```
If I do Replace device (pictured above), the function cannot find the device.

But if I then manually replace Unit in the DB, then everything works fine.

**Comment by gizmocuz** [comment]
I think the code is correct, the old device parameters (DeviceID,Unit,Type,Subtype) are set to the new device and the new device (with idx) is deleted.
So next update of the new device will update the old device (as this has the same parameters as the new device)

**Comment by eladvez** [comment]
Thank you very much for your time!

Maybe the problem is that I am using the old Legacy Plugin Framework.
I'll try to convert this plugin to the Extended Plugin Framework.
Maybe this will help solve the problem.

Although I still stand by my opinion.

I take timeout.
Thank you once again!

**Comment by gizmocuz** [comment]
Ahhh now i see, yes this misused the Unit as DeviceID.... that should indeed not be done.
Closing issue

**Comment by eladvez** [comment]
@gizmocuz - I propose a patch:
```diff
--- /var/folders/qx/hj6kfs_16sv064rbk3nqkks80000gn/T/git-blob-LEZxS5/WebServer.cpp
+++ /Volumes/LEB.GIT/domoticz-source/main/WebServer.cpp
@@ -13092,17 +13092,16 @@
 			root["status"] = "OK";
 			root["title"] = "TransferDevice";
 
-			result = m_sql.safe_query("SELECT HardwareID, DeviceID, Unit, Type, SubType FROM DeviceStatus WHERE (ID == '%q')", newidx.c_str());
+			result = m_sql.safe_query("SELECT HardwareID, DeviceID, Type, SubType FROM DeviceStatus WHERE (ID == '%q')", newidx.c_str());
 			if (result.empty())
 				return;
 
 			int newHardwareID = std::stoi(result[0].at(0));
 			std::string newDeviceID = result[0].at(1);
-			int newUnit = std::stoi(result[0].at(2));
-			int devType = std::stoi(result[0].at(3));
-			int subType = std::stoi(result[0].at(4));
-
-			m_sql.safe_query("UPDATE DeviceStatus SET HardwareID = %d, DeviceID = '%q', Unit = %d, Type = %d, SubType = %d WHERE ID == '%q'", newHardwareID, newDeviceID.c_str(), newUnit, devType, subType, sidx.c_str());
+			int devType = std::stoi(result[0].at(2));
+			int subType = std::stoi(result[0].at(3));
+
+			m_sql.safe_query("UPDATE DeviceStatus SET HardwareID = %d, DeviceID = '%q', Type = %d, SubType = %d WHERE ID == '%q'", newHardwareID, newDeviceID.c_str(), devType, subType, sidx.c_str());
 			m_sql.DeleteDevices(newidx);
 
 			m_mainworker.m_scheduler.ReloadSchedules();
```

**Comment by gizmocuz** [comment]
My comment above was about the legacy framework that should not be used anymore, the code inside domoticz is correct.

As example, consider the below:

Old Device
Type=TempDevice
SubType=Temp+Hum
DeviceID=12345
Unit=8

New Device
Type=TempDevice
SubType=Temp+Hum
DeviceID=65432
Unit=2

We have two years of logging for the Old Device, and we just replaced it with a new device

We select the old device and choose to replace it with the new device

We transfer the new device characteristics (type/subtype/deviceid/unit) to the old one, and delete the new device (_otherwise we have two devices in our system with both the same characteristics_)

Now when a new reading is received from the new device it finds the device in our system (our old device but with the new current characteristics) and updates it as it was the old device

Hope this explains it better

**Comment by gizmocuz** [comment]
And please ask the plugin developer to use the new plugin framework

**Comment by eladvez** [comment]
Thanks for the clarification. I understand well what happens when replacing devices.

I switched to the new DomoticzEx plugin. But the problem is not solved.
And still questions remain.

Let's take a look at my case (my screenshots are at the top):
The examples are missing the IDX parameter. Added them.

Old
```properties
Name=MCLH-03(V)
DeviceID=0x00124B0009FE3757_volt
IDX=12
Unit=12
```

New
```properties
Name=Switch Xiaomi 2(V)
DeviceID=0x54EF441000159E79_volt
IDX=218
Unit=56
```

As a result, device is created:
```properties
Name=MCLH-03(V)
DeviceID=0x00124B0009FE3757_volt
IDX=12
Unit=56
```

I understand that the New device (IDX = 218 + Unit = 56) is removed - this is logical :)

And this replacement makes the Domoticz system. **But the plugin does not know what these changes were.** And continues to work with the **old list**.

The device (IDX = 12 + Unit = 56) did not exist before this replacement. Was (IDX = 12 + Unit = 12).
And the plugin can't find it!
As a result, the plugin is created new.

The solution in your case - is to need  update the list of devices as soon as the replacement has been made.
But there is no event from Domotics. I didn't find it.

In my case - if Unit=12 (does not change) - then everything works automatically. In the new DomoticzEx and the old Legacy Plugin Framework. 
It is easier.
This is my logical vision.

[According to the documentation](https://www.domoticz.com/wiki/Developing_a_Python_plugin#Units), all updates are based on Unit:
```python
Devices["myDevice"].Unit[1].nValue = 42
Devices["myDevice"].Unit[1].sValue = "Ultimate answer"
Devices["myDevice"].Unit[1].Update(Log=True)

```
Therefore, **Unit** must always be **up to date**.
But I repeat - until the plugin is restarted - it does not know the new Unit (56). He remember the old Unit (12).

Forgive me for persistence, but I have been waiting for this solution to this displacement problem for a very long time.

**Comment by gizmocuz** [comment]
You do know you have to press edit on the 'old' device and choose to replace it with the 'new' device correct?

So replacing goes like this:

Old device:

```
IDX=12
Name=MCLH-03(V)
DeviceID=0x00124B0009FE3757_volt
Type=...
Sybtype=...
Unit=12
```

New device already received has:
```
IDX=218
Name=Switch Xiaomi 2(V)
DeviceID=0x54EF441000159E79_volt
Type=...
Sybtype=...
Unit=56
```

when you press edit on the old device (idx 12)and replace it with the new device (idx 218) you will get
```
IDX=12
Name=MCLH-03(V)
DeviceID=0x54EF441000159E79_volt
Type=...
Sybtype=...
Unit=56
```

**Comment by eladvez** [comment]
> You do know you have to press edit on the 'old' device and choose to replace it with the 'new' device correct?

Yes

> So replacing goes like this:

In my case, the Type and Sybtype all devices are equal. So everything is equal.
In theory, the devices must be of the same type, otherwise it is impossible to do a replacement.
There are no questions here.

> Old device:

```properties
IDX=12
Name=MCLH-03(V)
DeviceID=0x00124B0009FE3757_volt
Type=General
Sybtype=Voltage
Unit=12
```

> New device already received has:

```properties
IDX=218
Name=Switch Xiaomi 2(V)
DeviceID=0x54EF441000159E79_volt
Type=General
Sybtype=Voltage
Unit=56
```

> when you press edit on the old device (idx 12)and replace it with the new device (idx 218) you will get

```properties
IDX=12
Name=MCLH-03(V)
DeviceID=0x54EF441000159E79_volt
Type=General
Sybtype=Voltage
Unit=56
```

**Comment by eladvez** [comment]
Clarification about my phrase:

>As a result, the plugin is created new.

The MQTT broker constantly sends data updates.
And when data comes from the new device (IDX = 218 + Unit = 56), the plugin cannot find it and then creates another (third) device:
```properties
IDX=245
Name=Switch Xiaomi 2(V)
DeviceID=0x54EF441000159E79_volt
Type=General
Sybtype=Voltage
Unit=5
```

I can attach a screenshot of the result of this action, but I think this will confuse the situation even more.

Therefore, this phrase of mine can be ignored.

**Comment by gizmocuz** [comment]
`And when data comes from the new device (IDX = 218 + Unit = 56), the plugin cannot find it and then creates another (third) device:`

Which plugin does this? It should work with Type/Subtype/DeviceID/Unit and not with idx

To solve all your nightmares, please use Zigbee2MQTT

Topic is closed, logic inside the code is correct, and I can't help it that a plugin does use IDX+Unit instead of Type/Subtype/DeviceID/Unit
