### ISSUE TITLE
MQTT Autodiscovery: Zigbee Moes 2 gang dimmer brightness not set

### ISSUE THREAD

**Issue by Elmervc** [domoticz/domoticz#5440]
Hi,

I have a 2-gang dimmer (Moes MS-105B), which is added automatically in Domoticz, correctly identified as 2 dimmers, using auto discover.
Domoticz (Version: 2022.2 (build 14784)) is able to read the state and brightness correctly, and I can turn the lights on/off. However, it fails to set the brightness , while this works when done from z2mqtt. See [this topic](https://www.domoticz.com/forum/viewtopic.php?p=295291#p295291) on the forum.

The issue is that Domoticz tries to set the brightness using a different path than z2mqtt does.
From the forum:

> below is mqtt log when changing the brightness correctly to 28 via the zigbee2mqtt frontend
```
debug 2022-11-27 20:40:26: Received MQTT message on 'zigbee2mqtt/dimmerWoonkamer/set' with data '{"brightness_l1":28}'
debug 2022-11-27 20:40:26: Publishing 'set' 'brightness' to 'dimmerWoonkamer'
```
>below is mqtt log when changing brightness to 61 from domoticz, which fails.
```
debug 2022-11-27 20:42:37: Received MQTT message on 'zigbee2mqtt/dimmerWoonkamer/l1/set' with data '{"brightness":61,"state":"ON"}'
debug 2022-11-27 20:42:37: Publishing 'set' 'state' to 'dimmerWoonkamer'
```

Not sure which data you need, but here is the device interview json:

```json
{
  "data": {
    "definition": {
      "description": "Smart dimmer module (2 gang)",
      "exposes": [
        {
          "endpoint": "l1",
          "features": [
            {
              "access": 3,
              "description": "On/off state of this light",
              "endpoint": "l1",
              "name": "state",
              "property": "state_l1",
              "type": "binary",
              "value_off": "OFF",
              "value_on": "ON",
              "value_toggle": "TOGGLE"
            },
            {
              "access": 3,
              "description": "Brightness of this light",
              "endpoint": "l1",
              "name": "brightness",
              "property": "brightness_l1",
              "type": "numeric",
              "value_max": 254,
              "value_min": 0
            }
          ],
          "type": "light"
        },
        {
          "endpoint": "l2",
          "features": [
            {
              "access": 3,
              "description": "On/off state of this light",
              "endpoint": "l2",
              "name": "state",
              "property": "state_l2",
              "type": "binary",
              "value_off": "OFF",
              "value_on": "ON",
              "value_toggle": "TOGGLE"
            },
            {
              "access": 3,
              "description": "Brightness of this light",
              "endpoint": "l2",
              "name": "brightness",
              "property": "brightness_l2",
              "type": "numeric",
              "value_max": 254,
              "value_min": 0
            }
          ],
          "type": "light"
        },
        {
          "access": 1,
          "description": "Link quality (signal strength)",
          "name": "linkquality",
          "property": "linkquality",
          "type": "numeric",
          "unit": "lqi",
          "value_max": 255,
          "value_min": 0
        }
      ],
      "model": "MS-105B",
      "options": [],
      "supports_ota": false,
      "vendor": "Moes"
    },
    "friendly_name": "0x84ba20fffe655423",
    "ieee_address": "0x84ba20fffe655423",
    "status": "successful",
    "supported": true
  },
  "type": "device_interview"
}
```

Here's some logging from the mqtt_ad script. If you need more data, let me know.

```
2022-12-02T20:51:47+0100        0       zigbee2mqtt/bridge/event        {"data":{"friendly_name":"0x84ba20fffe655423","ieee_address":"0x84ba20fffe655423"},"type":"device_joined"}
2022-12-02T20:51:47+0100        0       zigbee2mqtt/bridge/logging      {"level":"info","message":"MQTT publish: topic 'homeassistant/light/0x84ba20fffe655423/light_l1/config', payload '{\"availability\":[{\"topic\":\"zigbee2mqtt/bridge
/state\",\"value_template\":\"{{ value_json.state }}\"}],\"brightness\":true,\"brightness_scale\":254,\"command_topic\":\"zigbee2mqtt/0x84ba20fffe655423/l1/set\",\"device\":{\"identifiers\":[\"zigbee2mqtt_0x84ba20fffe655423\"],\"manufac
turer\":\"Moes\",\"model\":\"Smart dimmer module (2 gang) (MS-105B)\",\"name\":\"0x84ba20fffe655423\"},\"name\":\"0x84ba20fffe655423 l1\",\"schema\":\"json\",\"state_topic\":\"zigbee2mqtt/0x84ba20fffe655423/l1\",\"unique_id\":\"0x84ba20
fffe655423_light_l1_zigbee2mqtt\"}'"}
2022-12-02T20:51:47+0100        0       homeassistant/light/0x84ba20fffe655423/light_l1/config  {"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"brightness":true,"brightness_scale":254,"c
ommand_topic":"zigbee2mqtt/0x84ba20fffe655423/l1/set","device":{"identifiers":["zigbee2mqtt_0x84ba20fffe655423"],"manufacturer":"Moes","model":"Smart dimmer module (2 gang) (MS-105B)","name":"0x84ba20fffe655423"},"name":"0x84ba20fffe655
423 l1","schema":"json","state_topic":"zigbee2mqtt/0x84ba20fffe655423/l1","unique_id":"0x84ba20fffe655423_light_l1_zigbee2mqtt"}
2022-12-02T20:51:47+0100        0       zigbee2mqtt/bridge/logging      {"level":"info","message":"MQTT publish: topic 'homeassistant/light/0x84ba20fffe655423/light_l2/config', payload '{\"availability\":[{\"topic\":\"zigbee2mqtt/bridge
/state\",\"value_template\":\"{{ value_json.state }}\"}],\"brightness\":true,\"brightness_scale\":254,\"command_topic\":\"zigbee2mqtt/0x84ba20fffe655423/l2/set\",\"device\":{\"identifiers\":[\"zigbee2mqtt_0x84ba20fffe655423\"],\"manufac
turer\":\"Moes\",\"model\":\"Smart dimmer module (2 gang) (MS-105B)\",\"name\":\"0x84ba20fffe655423\"},\"name\":\"0x84ba20fffe655423 l2\",\"schema\":\"json\",\"state_topic\":\"zigbee2mqtt/0x84ba20fffe655423/l2\",\"unique_id\":\"0x84ba20
fffe655423_light_l2_zigbee2mqtt\"}'"}
2022-12-02T20:51:47+0100        0       homeassistant/light/0x84ba20fffe655423/light_l2/config  {"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"brightness":true,"brightness_scale":254,"c
ommand_topic":"zigbee2mqtt/0x84ba20fffe655423/l2/set","device":{"identifiers":["zigbee2mqtt_0x84ba20fffe655423"],"manufacturer":"Moes","model":"Smart dimmer module (2 gang) (MS-105B)","name":"0x84ba20fffe655423"},"name":"0x84ba20fffe655
423 l2","schema":"json","state_topic":"zigbee2mqtt/0x84ba20fffe655423/l2","unique_id":"0x84ba20fffe655423_light_l2_zigbee2mqtt"}
2022-12-02T20:51:47+0100        0       zigbee2mqtt/bridge/logging      {"level":"info","message":"MQTT publish: topic 'homeassistant/sensor/0x84ba20fffe655423/linkquality/config', payload '{\"availability\":[{\"topic\":\"zigbee2mqtt/br
idge/state\",\"value_template\":\"{{ value_json.state }}\"}],\"device\":{\"identifiers\":[\"zigbee2mqtt_0x84ba20fffe655423\"],\"manufacturer\":\"Moes\",\"model\":\"Smart dimmer module (2 gang) (MS-105B)\",\"name\":\"0x84ba20fffe655423\"
},\"enabled_by_default\":false,\"entity_category\":\"diagnostic\",\"icon\":\"mdi:signal\",\"name\":\"0x84ba20fffe655423 linkquality\",\"state_class\":\"measurement\",\"state_topic\":\"zigbee2mqtt/0x84ba20fffe655423\",\"unique_id\":\"0x8
4ba20fffe655423_linkquality_zigbee2mqtt\",\"unit_of_measurement\":\"lqi\",\"value_template\":\"{{ value_json.linkquality }}\"}'"}
2022-12-02T20:51:47+0100        0       homeassistant/sensor/0x84ba20fffe655423/linkquality/config      {"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mq
tt_0x84ba20fffe655423"],"manufacturer":"Moes","model":"Smart dimmer module (2 gang) (MS-105B)","name":"0x84ba20fffe655423"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0x84ba20fffe655423 linkqua
lity","state_class":"measurement","state_topic":"zigbee2mqtt/0x84ba20fffe655423","unique_id":"0x84ba20fffe655423_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}
```

```
2022-12-02T20:51:48+0100        0       zigbee2mqtt/bridge/logging      {"level":"info","message":"Device '0x84ba20fffe655423' is supported, identified as: Moes Smart dimmer module (2 gang) (MS-105B)"}
2022-12-02T20:51:48+0100        0       zigbee2mqtt/bridge/devices      [{"definition":null,"endpoints":{"1":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"10":{"bindings":[],"clusters":{"inp
ut":[],"output":[]},"configured_reportings":[],"scenes":[]},"11":{"bindings":[],"clusters":{"input":["ssIasAce","genTime"],"output":["ssIasZone","ssIasWd"]},"configured_reportings":[],"scenes":[]},"110":{"bindings":[],"clusters":{"input
":[],"output":[]},"configured_reportings":[],"scenes":[]},"12":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"13":{"bindings":[],"clusters":{"input":["genOta"],"output":[]},"configured_report
ings":[],"scenes":[]},"2":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"242":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"3":{"bindings":[],"cl
usters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"4":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"47":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_
reportings":[],"scenes":[]},"5":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"6":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"8":{"bindings":[]
,"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]}},"friendly_name":"Coordinator","ieee_address":"0x00124b002a1aa19f","interview_completed":true,"interviewing":false,"network_address":0,"supported":false,"type"
:"Coordinator"},{"date_code":"","definition":{"description":"Smart dimmer module (2 gang)","exposes":[{"endpoint":"l1","features":[{"access":3,"description":"On/off state of this light","endpoint":"l1","name":"state","property":"state_l
1","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"},{"access":3,"description":"Brightness of this light","endpoint":"l1","name":"brightness","property":"brightness_l1","type":"numeric","value_max":254,"value_mi
n":0}],"type":"light"},{"endpoint":"l2","features":[{"access":3,"description":"On/off state of this light","endpoint":"l2","name":"state","property":"state_l2","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"},{
"access":3,"description":"Brightness of this light","endpoint":"l2","name":"brightness","property":"brightness_l2","type":"numeric","value_max":254,"value_min":0}],"type":"light"},{"access":1,"description":"Link quality (signal strength
)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"MS-105B","options":[],"supports_ota":false,"vendor":"Moes"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["ge
nBasic","genGroups","genScenes","manuSpecificTuya"],"output":["genOta","genTime"]},"configured_reportings":[],"scenes":[]}},"friendly_name":"0x84ba20fffe655423","ieee_address":"0x84ba20fffe655423","interview_completed":true,"interviewin
g":false,"manufacturer":"_TZE200_e3oitdyu","model_id":"TS0601","network_address":17193,"power_source":"Mains (single phase)","supported":true,"type":"Router"}]
```

**Comment by gizmocuz** [comment]
Could you use MQTT Explorer and send a message to

zigbee2mqtt/dimmerWoonkamer/set

containing:

should work, bus does not:
{"brightness":61,"state":"ON"}'

omitted the state. might work:
{"brightness":61}'

seems to work:
{"brightness_l1":61}

should then also work:
{"brightness_l1":61,"state":"ON"}'

How should Domoticz known it needs to add _l1 or _l2 to the brightness field with the below config:

```
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "brightness": true,
  "brightness_scale": 254,
  "command_topic": "zigbee2mqtt/0x84ba20fffe655423/l1/set",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x84ba20fffe655423"
    ],
    "manufacturer": "Moes",
    "model": "Smart dimmer module (2 gang) (MS-105B)",
    "name": "0x84ba20fffe655423"
  },
  "name": "0x84ba20fffe655 423 l1",
  "schema": "json",
  "state_topic": "zigbee2mqtt/0x84ba20fffe655423/l1",
  "unique_id": "0x84ba20fffe655423_light_l1_zigbee2mqtt"
}
```

**Comment by gizmocuz** [comment]
Could you also test to send the following to 

zigbee2mqtt/dimmerWoonkamer

{"brightness":61,"state":"ON"}'

**Comment by Elmervc** [comment]
I just tested each of the following messages after turning off the light to see if the light `l1` turns on after sending the message:

`zigbee2mqtt/dimmerWoonkamer/l1/set`
```json
{"brightness":61}
```
Turns on the light, level 61


`zigbee2mqtt/dimmerWoonkamer/l1/set`
```json
{"brightness":100, "state":"ON"}
```

turns on the light, but level at old value 61.

`zigbee2mqtt/dimmerWoonkamer/l1/set`
```json
{"brightness":100}
```
Changes level to 100 (and also turns on light when it was in OFF state)


And the results for the messages you asked for:
`zigbee2mqtt/dimmerWoonkamer/set`
```json
{"brightness":61,"state":"ON"}
```
Doesn't do anything, because it's not targeting l1 or l2 I guess

`zigbee2mqtt/dimmerWoonkamer/set`
```json
{"brightness":61}
```
Also nothing (not targetting l1 or l2)

`zigbee2mqtt/dimmerWoonkamer/set`
```json
{"brightness_l1":61}
```
Turns on the light, level 61

`zigbee2mqtt/dimmerWoonkamer/set`
```json
{"brightness_l1":61,"state":"ON"}
```
Does nothing


`zigbee2mqtt/dimmerWoonkamer`
```json
{"brightness":61,"state":"ON"}
```
Not sure why you wanted to test this one without `/set`, but this does nothing.

Conclusions: 
- When sending both "state" and "brightness" to `l1` or `l2`, it will only set the state, and ignores the brightness. The brightness should be send in a separate message.
- `l1` can be addressed by topic `zigbee2mqtt/dimmerWoonkamer/set` with properties `brightness_l1`, `state_l1` or by topic `zigbee2mqtt/dimmerWoonkamer/l1/set` with properties `brightness` and `state`.  Same holds for `l2`

**Comment by gizmocuz** [comment]
Thank you for testing!

I removed sending the state when no brightness template is defined in the config

Tested also here internally and seems to work as well

Should be solved in beta 14796

**Comment by Elmervc** [comment]
Thanks @gizmocuz! I've just updated to the latest beta and can confirm it now works without any issues 👌

**Comment by KjeldFo** [comment]
Thanks @gizmocuz for fixing and @Elmervc for continuing my initial request, I'm impressed how fast this was fixed. Just ordered 2 1 channels dimmers for nothing 😉.

**Comment by waltervl** [comment]
@KjeldFo @Elmervc Please check latest beta due to changes for #5709 that reverted back this change.....

**Comment by Elmervc** [comment]
> @KjeldFo @Elmervc Please check latest beta due to changes for #5709 that reverted back this change.....

Apologies for the late response. The dim level is indeed broken since that update. I can only switch the lights on and off from domoticz.

**Comment by gizmocuz** [comment]
@Elmervc , I have removed the 'state' field in the latest beta version (15614)
Hope it won't cause issues with other users.
As far as I could test, my devices are still working correctly when setting the brightness.

**Comment by Elmervc** [comment]
Thanks @gizmocuz, it's fixed now 👍

**Comment by KjeldFo** [comment]
I'm sorry I don't have the time to check at the moment. I moved to 2 single gang dimmers because those have a min and max level. So I have to connect this dimmer again te use it.

**Comment by pcdiks** [comment]
I just added the Moes ms-105b to a completely new zigbee2mqtt environment. I used the MQTT auto discovery client gateway with LAN to Domoticz. The device is added to Domoticz as 2 dimmers. However, I cannot turn on the lights :(

When I use the zigbee2mqtt dashboard, everything works fine. The following commands are send by zigbee2mqtt:
`
zigbee2mqtt dashboard
topic 'zigbee2mqtt/keuken', payload '{"backlight_mode":null,"brightness_l1":170,"brightness_l2":117,"countdown_l1":null,"countdown_l2":null,"linkquality":94,"min_brightness_l1":0,"min_brightness_l2":0,"power_on_behavior":null,"state_l1":"OFF","state_l2":"ON"}'
topic 'zigbee2mqtt/keuken/l1', payload '{"brightness":170,"countdown":null,"min_brightness":0,"state":"OFF"}'
topic 'zigbee2mqtt/keuken/l2', payload '{"brightness":117,"countdown":null,"min_brightness":0,"state":"ON"}'
topic 'zigbee2mqtt/keuken', payload '{"backlight_mode":null,"brightness_l1":170,"brightness_l2":117,"countdown_l1":null,"countdown_l2":null,"linkquality":98,"min_brightness_l1":0,"min_brightness_l2":0,"power_on_behavior":null,"state_l1":"OFF","state_l2":"ON"}'
topic 'zigbee2mqtt/keuken/l1', payload '{"brightness":170,"countdown":null,"min_brightness":0,"state":"OFF"}'
topic 'zigbee2mqtt/keuken/l2', payload '{"brightness":117,"countdown":null,"min_brightness":0,"state":"ON"}'
topic 'zigbee2mqtt/keuken', payload '{"backlight_mode":null,"brightness_l1":170,"brightness_l2":117,"countdown_l1":null,"countdown_l2":null,"linkquality":94,"min_brightness_l1":0,"min_brightness_l2":0,"power_on_behavior":null,"state_l1":"OFF","state_l2":"ON"}'
topic 'zigbee2mqtt/keuken/l1', payload '{"brightness":170,"countdown":null,"min_brightness":0,"state":"OFF"}'
topic 'zigbee2mqtt/keuken/l2', payload '{"brightness":117,"countdown":null,"min_brightness":0,"state":"ON"}'
`

When I turn the light on in Domoticz I get this in the zigbee logs:
`
topic 'zigbee2mqtt/keuken', payload '{"backlight_mode":null,"brightness_l1":170,"brightness_l2":117,"countdown_l1":null,"countdown_l2":null,"linkquality":98,"min_brightness_l1":0,"min_brightness_l2":0,"power_on_behavior":null,"state_l1":"OFF","state_l2":"OFF"}'
topic 'zigbee2mqtt/keuken/l1', payload '{"brightness":170,"countdown":null,"min_brightness":0,"state":"OFF"}'
topic 'zigbee2mqtt/keuken/l2', payload '{"brightness":117,"countdown":null,"min_brightness":0,"state":"OFF"}'
topic 'zigbee2mqtt/keuken', payload '{"backlight_mode":null,"brightness_l1":170,"brightness_l2":117,"countdown_l1":null,"countdown_l2":null,"linkquality":98,"min_brightness_l1":0,"min_brightness_l2":0,"power_on_behavior":null,"state_l1":"OFF","state_l2":"OFF"}'
topic 'zigbee2mqtt/keuken/l1', payload '{"brightness":170,"countdown":null,"min_brightness":0,"state":"OFF"}'
topic 'zigbee2mqtt/keuken/l2', payload '{"brightness":117,"countdown":null,"min_brightness":0,"state":"OFF"}'
`

I am using Domoticz version 2024.7 and zigbee2mqtt version 2.1.1.

I would love to have this working in Domoticz as well. Hope we can fix this.

**Comment by gizmocuz** [comment]
@pcdiks , I am quite sure domoticz is not sending 'that' payload... it will send a payload to the command topic.
Could you post the config topic + payload of your dimmer?

**Comment by pcdiks** [comment]
Thanks for the quick reply. I think this is the config topic:

`{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"brightness":true,"brightness_scale":254,"command_topic":"zigbee2mqtt/keuken/l1/set","device":{"hw_version":1,"identifiers":["zigbee2mqtt_0xbc026efffe3ebe88"],"manufacturer":"Tuya","model":"2 gang smart dimmer","model_id":"TS0601_dimmer_2","name":"keuken","via_device":"zigbee2mqtt_bridge_0x00124b00259bcb15"},"name":"L1","object_id":"keuken_l1","origin":{"name":"Zigbee2MQTT","sw":"2.1.1","url":"https://www.zigbee2mqtt.io"},"schema":"json","state_topic":"zigbee2mqtt/keuken/l1","unique_id":"0xbc026efffe3ebe88_light_l1_zigbee2mqtt"}
`

```
{
    "availability": [
        {
            "topic": "zigbee2mqtt/bridge/state",
            "value_template": "{{ value_json.state }}"
        }
    ],
    "brightness": true,
    "brightness_scale": 254,
    "command_topic": "zigbee2mqtt/keuken/l2/set",
    "device": {
        "hw_version": 1,
        "identifiers": [
            "zigbee2mqtt_0xbc026efffe3ebe88"
        ],
        "manufacturer": "Tuya",
        "model": "2 gang smart dimmer",
        "model_id": "TS0601_dimmer_2",
        "name": "keuken",
        "via_device": "zigbee2mqtt_bridge_0x00124b00259bcb15"
    },
    "name": "L2",
    "object_id": "keuken_l2",
    "origin": {
        "name": "Zigbee2MQTT",
        "sw": "2.1.1",
        "url": "https://www.zigbee2mqtt.io"
    },
    "schema": "json",
    "state_topic": "zigbee2mqtt/keuken/l2",
    "unique_id": "0xbc026efffe3ebe88_light_l2_zigbee2mqtt"
}

```

Do you need a different payload then what I pasted in my previous message?

**Comment by gizmocuz** [comment]
@pcdiks , before diving into this, did you also try with the beta version? As we made some recent changes regarding brightness

**Comment by pcdiks** [comment]
It is running on a super stable raspberry pi 3 for years and is located at my in-laws home. That makes me hesitant to switch to a beta version... The zigbee network consists of just the MOES dimmer and the raspberry pi with the coordinator on it. For now I automated the on/off by running a script that publishes to the correct topic.
If the light is on, dimming is possible with the GUI.

<img width="904" alt="Image" src="https://github.com/user-attachments/assets/fb684826-5663-45d0-8dcc-36e4a69202e4" />

**Comment by gizmocuz** [comment]
Okey, well I suspect you should have no issues regarding the beta, but why not just make a backup of the domoticz folder before switching?
After the backup, just go to the domoticz folder and issue the below command:

./updatebeta

A stable release is a beta named to stable

**Comment by pcdiks** [comment]
Ok, will try and report back.
