### ISSUE TITLE
Venetian_Blinds_EU Blinds operation reversed in RFXCOM and RFLINK as of 2022.2 domoticz upgrade 

### ISSUE THREAD

**Issue by mealgi** [domoticz/domoticz#5442]
Hello

Context of the issue :
- Domoticz running on RPI3B+
- Actual version used 2022.2 version 14787
- Python 3.7.3
- Somfy Blinds configured as Venetian_Blinds_EU in domoticz application and controlled by RFXCOM Hardware usb stick.
- Somfy Remote controller configured as Venetian_Blinds_EU in domoticz and managed by RFLINK usb stick.
Each Somfy Blind is controlled locally by a Remote Controler supporting UP/STOP/DOWN command.

The domoticz GUI controls a somfy blind via RFXCOM (switch tab or LUA script).
The remote controller controls locally the somfy blind (UP/STOP/DOWN) and send the information to domoticz via RFLINK.
This way domoticz is fully aware of the blind status (UP/STOP/DOWN) whether it is controlled by domoticz GUI or locally by the remote controller.
This process is running successfully in 2022.1 domoticz version.

Description of the issue:
After the upgrade to 2022.2 version the operations on the Venetian EU blinds were reversed
- The command UP activated on the remote controller opens physically the blind and shows a Closed status in domoticz
- The command DOWN activated on the remote controller closes physically the blind and shows a Open status in domoticz
Up to 2022.1 domoticz version for a blind (not inverted):
State = Open with command Off
State = Closed with command On

As of 2022.2 domoticz version for a blind (not inverted)
State = Open with command On
States = Closed with command Off

Proposed solution:

The Somfy blinds are of pTypeRFY type and the Venetian_Blinds_EU are managed using rfy_s2SecUp, rfy_s2SecDown and rfy_sStop commands values as shown in RFXNames.cpp file line 1888.

To control as before the blind from domoticz GUI I suggest to reverse the lstatus as shown below:

case rfy_s2SecUp:
if (switchtype == STYPE_VenetianBlindsEU)
{
lstatus = "On"; //#### up to 2022.1 version : Off ----> as of 2022.2 : On
}
break;
case rfy_s2SecDown:
if (switchtype == STYPE_VenetianBlindsEU)
{
lstatus = "Off"; //#### up to 2022.1 version : On ----> as of 2022.2 : Off
}
break;

The blind controllers are seen as type: pTypeGeneralSwitch , sub type : sSwitchTypeRTS and switch type : Venetian_Blinds_EU
The message received from RFLINK usb stick when parsed refers to a SWITCH type and the command UP, DOWN and STOP.
in RFLinkBase.cpp we have a lookup table linking the command (UP, DOWN, STOP) to the state (blinds_sOpen, blinds_sClose,blinds_sStop)
const _tRFLinkStringIntHelper rfblindcommands[] =
{
{ "UP", blinds_sOpen },
{ "DOWN", blinds_sClose },
{ "STOP", blinds_sStop },
{ "CONFIRM", blinds_sConfirm },
{ "LIMIT", blinds_sLimit },
{ "", -1 }
};

and in RFXTrx.h the link between the state blinds_sOpen,blinds_sClose and the value in the database 0x0, 0x1 Line 885.
#define blinds_sOpen 0x0
#define blinds_sClose 0x1

To receive the information as before from RFLINK I propose to reverse the link between state and value in database as shown below:
#define blinds_sOpen 0x1 //#### up to 2022.1 version : 0x0 ----> as of 2022.2 : 0x1
#define blinds_sClose 0x0 //#### up to 2022.1 version : 0x1 ----> as of 2022.2 : 0x0

I have rebuilt domoticz from sources and proceeded to the tests successfully in version 2022.2 modified without changing the Blind settings in  domoticz application.

This way Somfy Venetian_EU blinds operate directly from domoticz GUI or locally by the remote controllers as before in 2022.1 version.

BR

**Comment by gizmocuz** [comment]
Instead of On and Off (which should not be used anymore for blinds), could you use Close/Open, as is also used for the normal rfy_sUp/rfy_sDown?

Actually, maybe the code can be rewritten to this:

```
			switch (nValue)
			{
			case rfy_sUp:
			case rfy_s05SecUp:
			case rfy_s2SecUp:
				lstatus = "Open";
				break;
			case rfy_sDown:
			case rfy_s05SecDown:
			case rfy_s2SecDown:
				lstatus = "Close";
				break;
			case rfy_sStop:
				lstatus = "Stop";
				break;
				break;
			case rfy_sEnableSunWind:
				lstatus = "SunWindChange";
				break;
			case rfy_sDisableSun:
				lstatus = "SunWindChange";
				break;
			}

```

It is also not possible to make any modifications to the RFXTRX.h file

**Comment by mealgi** [comment]
Hello

I made the changes you suggested in RFXNames.cpp and the Somfy Venetian EU Blinds are controlled successfully with RFXCOM.

Regarding RFLINK the way version 2022.2 operates is the following :

RFLINK driver parses the message received from the usb stick and calls SendSwitchInt to build the cmd  (blinds_sOpen=0, blinds_sClose=1) from the order (UP/DOWN) sent in the message.
Then RFLINKbase calls sDecodeRXMessage with the cmd to be written in the database as nvalue (0 Open and 1 Closed).

Webserver gets the nvalue from the domoticz database (SQL) and calls GetLightStatus in RFXName.cpp (in that case RFLINK is a pTypeGeneralSwitch device) 
with the nvalue (gswitch_sOff=0, gswitch_sOn=1) to build the device state (gswitch_sOff=0->Off->Closed , gswitch_sOn=1->On->Open).

So there is a discrepancy between RFLINK driver and Webserver.

One way to tackle the issue is to change in RFXTrx.h the value of blinds_sOpen=0, blinds_sClose=1 to have blinds_sOpen=1, blinds_sClose=0.
I made the changes, recompiled Domoticz and did the test of the RFLINK controllers successfully. 
However blinds_sOpen and blinds_sClose are also used in DenkoviDevices.cpp, MySensorsBase.cpp, mainworker.cpp, RFXNames.cpp (pTypeBlinds), SQLHelper.cpp
And I have not assessed the impacts of such a change in these software pieces.


The other way to tackle the issue without changing RFXTrx.h is to update the 2 following functions in RFXNames.cpp:
GetLightCommand and GetLightStatus

In GetLightStatus :

	case pTypeGeneralSwitch:
	....
		switch (nValue)
		{
		case gswitch_sOff:
			lstatus = "Off";
			// reverse state for RFLINK blind
			if 	((dSubType==sSwitchTypeRTS) && (switchtype == STYPE_BlindsPercentage || 
				switchtype == STYPE_BlindsPercentageWithStop ||
				switchtype == STYPE_VenetianBlindsUS ||
				switchtype == STYPE_VenetianBlindsEU ||
				switchtype == STYPE_Blinds))
				lstatus = "Open";
			break;
		case gswitch_sOn:
			lstatus = "On";
			// reverse state for RFLINK blind
			if 	((dSubType==sSwitchTypeRTS) && (switchtype == STYPE_BlindsPercentage || 
				switchtype == STYPE_BlindsPercentageWithStop ||
				switchtype == STYPE_VenetianBlindsUS ||
				switchtype == STYPE_VenetianBlindsEU ||
				switchtype == STYPE_Blinds))
				lstatus = "Close";
			break;


In GetLightCommand 
	case pTypeGeneralSwitch:
		.....
		if (switchcmd == "Off")
		{
			cmd = gswitch_sOff;
			// Management of RFLINK blind
			if 	((dSubType==sSwitchTypeRTS) &&
				(switchtype == STYPE_BlindsPercentage || 
				switchtype == STYPE_BlindsPercentageWithStop ||
				switchtype == STYPE_VenetianBlindsUS ||
				switchtype == STYPE_VenetianBlindsEU ||
				switchtype == STYPE_Blinds))
				cmd = blinds_sClose;
			return true;
		}
		if (switchcmd == "On")
		{
			cmd = gswitch_sOn;
			// Management of RFLINK blind
			if 	((dSubType==sSwitchTypeRTS) &&
				(switchtype == STYPE_BlindsPercentage || 
				switchtype == STYPE_BlindsPercentageWithStop ||
				switchtype == STYPE_VenetianBlindsUS ||
				switchtype == STYPE_VenetianBlindsEU ||
				switchtype == STYPE_Blinds))
				cmd = blinds_sOpen;
			return true;
		}
		if (switchcmd == "Open")
		{
			cmd = gswitch_sOpen;
			// Management of RFLINK blind
			if 	((dSubType==sSwitchTypeRTS) &&
				(switchtype == STYPE_BlindsPercentage || 
				switchtype == STYPE_BlindsPercentageWithStop ||
				switchtype == STYPE_VenetianBlindsUS ||
				switchtype == STYPE_VenetianBlindsEU ||
				switchtype == STYPE_Blinds))
				cmd = blinds_sOpen;
			return true;
		}
		if (switchcmd == "Close")
		{
			cmd = gswitch_sClose;
			// Management of RFLINK blind
			if 	((dSubType==sSwitchTypeRTS) &&
				(switchtype == STYPE_BlindsPercentage || 
				switchtype == STYPE_BlindsPercentageWithStop ||
				switchtype == STYPE_VenetianBlindsUS ||
				switchtype == STYPE_VenetianBlindsEU ||
				switchtype == STYPE_Blinds))
				cmd = blinds_sClose;
			return true;
		}

I made the changes, recompiled Domoticz and did the test of the RFLINK controllers successfully. 
This fix does not have a side effect on DenkoviDevices.cpp, MySensorsBase.cpp, mainworker.cpp, RFXNames.cpp (pTypeBlinds), SQLHelper.cpp because RFXtrx.h has not been changed
BR

**Comment by gizmocuz** [comment]
Thank you for the feedback. I have made the patch for RFXCom in the current code and will be available in beta 14823

You cannot change the file RFXTrx.rh, this will be overwritten when a new SDK is available from RFXCom

Also no code has to be changed as all is working correctly, except with RFLink

This means a fix needs to be made in the RFLink class

On/Off should not be used anymore for blinds, but open/close and stop

I think if you change this in the RFLink code then it should work as well

Edit: thus using gswitch_sOpen, and gswitch_sClose and gswitch_sStop

**Comment by mealgi** [comment]
Hello,

I investigated a solution without changing RFXNames.cpp.

Regarding the change suggested above in GetLightCommand function in RFXNames.cpp it is possible to make a change in RFLINKBase.cpp in function GetGeneralRFLinkFromString and GetGeneralRFLinkFromInt to achieve the same result.

Regarding the change suggested above in GetLightStatus function in RFXNames.cpp I do not find a way to address it in RFLINKBase.cpp because GetLightStatus is a global function.
In GetLightStatus switchtype is used many times to address the specificities of the Hardware, the piece of software I suggested is a complement to address RFLINK specificities.

BR

**Comment by gizmocuz** [comment]
I think the issue is that the RFLink code handles the blinds as switches and not as blinds (gswitch_sOpen, and gswitch_sClose and gswitch_sStop)

**Comment by mealgi** [comment]
Hello,

I made the following changes in RFLINKBase.cpp line 140 onward

const _tRFLinkStringIntHelper rfswitchcommands[] =
{
	{ "ON", gswitch_sOn },
	{ "OFF", gswitch_sOff },
	{ "ALLON", gswitch_sGroupOn },
	{ "ALLOFF", gswitch_sGroupOff },
	{ "DIM", gswitch_sDim },
	{ "BRIGHT", gswitch_sBright },
//	{ "UP", blinds_sOpen },
	{ "UP", gswitch_sOpen },
//	{ "DOWN", blinds_sClose },
	{ "DOWN", gswitch_sClose },
	{ "STOP", gswitch_sStop },
	{ "COLOR", gswitch_sColor },
	{ "DISCO+", gswitch_sDiscop },
	{ "DISCO-", gswitch_sDiscom },
	{ "", -1 }
};

and removed the modifications in RFXNames.cpp in GetLightCommand and GetLightStatus

I made the changes, recompiled Domoticz and did the test of the RFLINK controllers successfully.

BR

**Comment by gizmocuz** [comment]
Great! Thank you for testing and your time!
Hope all is OK now in beta 14824

**Comment by kuipers250** [comment]
I am using 14905 and do have problems with my Somfy RTS through RFLINK.
I am running Domoticz on Windows 10.

**Comment by mealgi** [comment]
@kuipers250

Which domoticz version are you running ?

How have been defined the blinds in Domoticz ?

What are the problems encountered with the blinds ?

BR
