### ISSUE TITLE
After last upgrade frontend stop works (when no active admin user in the system)

### ISSUE THREAD

**Issue by acaonweb** [domoticz/domoticz#5445]
![image](https://user-images.githubusercontent.com/22882393/205836542-edc3994b-85c8-4752-93d5-7ae13017fa54.jpeg)

**Comment by acaonweb** [comment]
![image](https://user-images.githubusercontent.com/22882393/205849101-56541cf2-4e4a-4cf7-a26c-2a4e23a826ed.png)

**Comment by acaonweb** [comment]
The same from any device/browser 
Engine is working because my scripts are working

**Comment by acaonweb** [comment]
Build 14821
Raspberry pi 3
Raspbian Buster

**Comment by waltervl** [comment]
Did you clear your browser cache? https://www.domoticz.com/wiki/Browser_Cache
I cannot test this beta version because my test system is on Linux X86 (not yet build)

**Comment by acaonweb** [comment]
yes, in every devices i use, same issue

**Comment by ionspicica** [comment]
i have the same problem after update

**Comment by acaonweb** [comment]
I've reverted to 14795, now everything is ok
Please fix 14821 (Domoticz showing update popup),

**Comment by gizmocuz** [comment]
Just to be sure (as I have no issues here), did you try also in a private browser?

**Comment by gizmocuz** [comment]
Updated multiple systems and have seen no issue at all

**Comment by gizmocuz** [comment]
Could you open the developer console (F12) and open check if there is any error reported?

**Comment by acaonweb** [comment]
> Just to be sure (as I have no issues here), did you try also in a private browser?

No, i haven't but i've used different browser and device (tablet, pc, raspbian, mobile android and ios)

**Comment by acaonweb** [comment]
> Could you open the developer console (F12) and open check if there is any error reported?

well, i've reverted to a working distribution, a could try, where i've to press F12?

**Comment by gizmocuz** [comment]
when you update to the latest beta version and open the browser. In the browser open the developer console with F12, you should see some tabs, like console/network/... , in the console you should hopefully see no error, but when you experience a error it should be mentioned there

**Comment by acaonweb** [comment]
> when you update to the latest beta version and open the browser. In the browser open the developer console with F12, you should see some tabs, like console/network/... , in the console you should hopefully see no error, but when you experience a error it should be mentioned there

ok, i'll try, but just i've only updated Domoticz, anything else to get this error :)

**Comment by acaonweb** [comment]
i have that

![image](https://user-images.githubusercontent.com/22882393/205936917-7f40dff2-be56-4239-8517-8cadeb655d6d.png)

angular.min.js:129 TypeError: $.t is not a function
    at Object.link (app.js:111)
    at angular.min.js:17
    at Ca (angular.min.js:90)
    at p (angular.min.js:74)
    at g (angular.min.js:66)
    at g (angular.min.js:66)
    at p (angular.min.js:74)
    at g (angular.min.js:66)
    at g (angular.min.js:66)
    at g (angular.min.js:66) "<span data-i18n=\"New Device\">"
(anonymous) @ angular.min.js:129
angular.min.js:129 TypeError: $.t is not a function
    at m.$rootScope.SetTimeAndSun (app.js:597)
    at app.js:259
    at m.$broadcast (angular.min.js:159)
    at handleTimeUpdate (livesocket.js:110)
    at $websocket.handleMessage (livesocket.js:60)
    at $websocket.me.$$fireEvent (angular-websocket.js:116)
    at WebSocket.me.$$ws.onmessage (angular-websocket.js:137)
(anonymous) @ angular.min.js:129
3angular.min.js:129 TypeError: $.t is not a function
    at m.$rootScope.SetTimeAndSun (app.js:597)
    at app.js:259
    at m.$broadcast (angular.min.js:159)
    at handleTimeUpdate (livesocket.js:110)
    at $websocket.handleMessage (livesocket.js:60)
    at $websocket.me.$$fireEvent (angular-websocket.js:116)
    at WebSocket.me.$$ws.onmessage (angular-websocket.js:137)
(anonymous) @ angular.min.js:129
(anonymous) @ angular.min.js:100
$broadcast @ angular.min.js:159
handleTimeUpdate @ livesocket.js:110
handleMessage @ livesocket.js:60
me.$$fireEvent @ angular-websocket.js:116
me.$$ws.onmessage @ angular-websocket.js:137
angular.min.js:129 TypeError: $.t is not a function
    at m.$rootScope.SetTimeAndSun (app.js:597)
    at app.js:259
    at m.$broadcast (angular.min.js:159)
    at handleTimeUpdate (livesocket.js:110)
    at $websocket.handleMessage (livesocket.js:75)
    at $websocket.me.$$fireEvent (angular-websocket.js:116)
    at WebSocket.me.$$ws.onmessage (angular-websocket.js:137)
(anonymous) @ angular.min.js:129
(anonymous) @ angular.min.js:100
$broadcast @ angular.min.js:159
handleTimeUpdate @ livesocket.js:110
handleMessage @ livesocket.js:75
me.$$fireEvent @ angular-websocket.js:116
me.$$ws.onmessage @ angular-websocket.js:137
2angular.min.js:129 TypeError: $.t is not a function
    at m.$rootScope.SetTimeAndSun (app.js:597)
    at app.js:259
    at m.$broadcast (angular.min.js:159)
    at handleTimeUpdate (livesocket.js:110)
    at $websocket.handleMessage (livesocket.js:60)
    at $websocket.me.$$fireEvent (angular-websocket.js:116)
    at WebSocket.me.$$ws.onmessage (angular-websocket.js:137)

**Comment by acaonweb** [comment]
same issues with private session

**Comment by waltervl** [comment]
I just updated to latest beta 14822. No issues here. I use a private web browser for connecting to my test system as I have also a production system.
![Screenshot_20221206-162901](https://user-images.githubusercontent.com/16327072/205955284-04f9cfa8-5c9d-4c35-b578-46d04871e1c5.png)

**Comment by acaonweb** [comment]
i'll check tomorrow,  but i dont see 14822

**Comment by gizmocuz** [comment]
14821 is good to test as well.... new fonts in newer beta

**Comment by gizmocuz** [comment]
@acaonweb , do you use the default theme? if not, could you try this?

**Comment by daan-b** [comment]
Domoticz V2022.2 (build 14823)
Build Hash: 02524805f, Date: 2022-12-06 17:47:43

Has the same issue.

**Comment by acaonweb** [comment]
> @acaonweb , do you use the default theme? if not, could you try this?

Yes I'm using default theme, issue persist. 
I'm nota able to update to 14822+ pop up says only 14821
![image](https://user-images.githubusercontent.com/22882393/205995430-1444b4b3-cf12-43a5-bfd1-041262aef481.jpeg)

**Comment by acaonweb** [comment]
I've updated to 14823 cleared cache, used private browser. 
Same issue. 
Back to 14975 everything work

**Comment by waltervl** [comment]
Do you use users? Do you normally need to login into Domoticz? Do you have your Domoticz made available for outside your home network?

**Comment by daan-b** [comment]
Disabled login, default template and only local. No ssl

**Comment by acaonweb** [comment]
> Do you use users? Do you normally need to login into Domoticz? Do you have your Domoticz made available for outside your home network?

No user, no login, not exposed outside my network.

**Comment by acaonweb** [comment]
please consider that 14975 is working greatly...
My domoticz is in a production system, so it's going difficult trying everything.

**Comment by sylar6725** [comment]
I just saw that I had the same mistake.
It worked again after using the updatebeta script in the domoticz folder. I didn't think to check in which version I was before, but my last backup is from 2022/12/05 at 18h40

version now:
Version: 2022.2 (build 14823)
Build Hash: 02524805f
Compile Date: 2022-12-06 17:47:43

**Comment by kiddigital** [comment]
> please consider that 14975 is working greatly... My domoticz is in a production system, so it's going difficult trying everything.

Tested several aspects, versions, browsers, etc. but unable to reproduce the problem. I see that some other testers do not have the problem, but also a few people reporting the same/similar issue. We need to make it reproducible (on different systems) before we know what to fix.

When switching back your back-end to 14975, it is likely that it 'works again' because your front-end(s) might still have an older/matching version of the UI files (javascript and more).

Can you reproduce the problem on your system and make sure you have the 'developer tools' active (F12) and when the error occurs, using the developers look for the Javascript file `app.js` and see if you can find the following piece of code: `userName: "Unknown"` ?

Can you also make a screenshot of the screen with the `Setup`-menu items open showing all sub-menu items?

BTW, which browser (version) are you using? And do you maybe use a proxy or something in between or is the browser directly connected to the back-end?

**Comment by kiddigital** [comment]
@acaonweb , could you also make a screenshot of the User settings of your (first) admin user (under 'Setup/Users' and select the right user)

**Comment by waltervl** [comment]
Did @acaonweb and @ionspicica update by web interface or run `sudo ./updatebeta` from terminal?
If from web interface please try the updatebeta script from terminal. Perhaps the web update blocks something.

**Comment by gizmocuz** [comment]
@waltervl , that's not possible as the web interface calls updatebeta as well

**Comment by acaonweb** [comment]
> 

as i wrote in the beginning, i use ios safari/osx safari, chrome windows, raspbian chrominum same problem

**Comment by acaonweb** [comment]
> @acaonweb , could you also make a screenshot of the User settings of your (first) admin user (under 'Setup/Users' and select the right user)

IN which situation? when error occurs?

**Comment by ionspicica** [comment]
> Did @acaonweb and @ionspicica update by web interface or run `sudo ./updatebeta` from terminal? If from web interface please try the updatebeta script from terminal. Perhaps the web update blocks something.

yes, I updated via terminal ./updatebeta , in a few hours I will send the errors from the console

**Comment by ionspicica** [comment]
![Domoticz - Google Chrome](https://user-images.githubusercontent.com/13585500/206241270-744d4f7d-6a8e-4b59-95cf-143d67da97d7.jpg)
![Domoticz - Google Chrome](https://user-images.githubusercontent.com/13585500/206240624-583cd190-e534-4a21-9d84-bd7117efe164.jpg)

**Comment by kiddigital** [comment]
Please make a printscreen of the menu items shown when pressing the 'Setup' button.

Which language do you have selected? Default theme and English?

**Comment by ionspicica** [comment]
> Please make a printscreen of the menu items shown when pressing the 'Setup' button.
> 
> Which language do you have selected? Default theme and English?

![Settings](https://user-images.githubusercontent.com/13585500/206258002-5fa227f8-b1b0-4e5f-ac24-9a1346fe33ff.jpg)

The language is English, I don't remember exactly if it is the default theme, the settings menu is not available either

**Comment by ionspicica** [comment]
![DB Browser for SQLite - CUsersIon SpicicaDesktopdomoticz db2](https://user-images.githubusercontent.com/13585500/206263661-4597abcf-654e-4e09-9f87-798eec653b5b.jpg)
![DB Browser for SQLite - CUsersIon SpicicaDesktopdomoticz db](https://user-images.githubusercontent.com/13585500/206263671-344c6b05-5c20-43d3-9149-230c7d69af75.jpg)
so I opened the domoticz.db database directly because I couldn't from the settings, to check once again what is the language and theme set, the theme is default and the language is English

**Comment by acaonweb** [comment]
> > Please make a printscreen of the menu items shown when pressing the 'Setup' button.
> 
> > 
> 
> > Which language do you have selected? Default theme and English?
> 
> 
> 
> ![Settings](https://user-images.githubusercontent.com/13585500/206258002-5fa227f8-b1b0-4e5f-ac24-9a1346fe33ff.jpg)
> 
> 
> 
> The language is English, I don't remember exactly if it is the default theme, the settings menu is not available either

Same web page for me when issue occours 
I confirm the same settings

**Comment by acaonweb** [comment]
I've just made an experiment, using a new microsd, installing the last image of rasbian64 bit, installing domoticz from scratch, importing the .db from my actual domoticz, no issues. 
So, there something missing in OS that update wants but doesn't find?

**Comment by gizmocuz** [comment]
Question, is your domoticz running when you see issue?

` ps uax | grep domoticz`

After you installed from scratch, you also updated to the latest beta version?

If it does not start, what is the output when you want to run domoticz by hand with

```
cd domoticz
./domoticz
```

**Comment by acaonweb** [comment]
Yes domoticz is running because all the events are working and all devices (zigbee/ Wi-Fi/ mqtt/ home bridge) are working. 
As I told at the beginning it's only web interface the problem. 
All python plugin are working (mqtt/zigbee2mqtt)

When I've installed from the scratch I've set "beta" in the settings, and updated to 14823

**Comment by gizmocuz** [comment]
Thanks, yes, I was just double checking that it could not be because of a missing system library

Is it possible you could compare the two folders (system not working and system working), I wonder what is different besides the database

**Comment by acaonweb** [comment]
what do you need to compare? .db? entire folder and subfolders? to do that I've to copy  14975 running folder, update to get 14823 not working folder and copy that. what I've to compare, specifically?

**Comment by acaonweb** [comment]
if you want I can send you a wetransfer, with both folders, to compare. replay to my mail acaonweb [at] gmail dot com
let me know

**Comment by gizmocuz** [comment]
Thanks send you an email

**Comment by kiddigital** [comment]
The screenshot from @ionspicica shows an old setup screen as for example the 'MyDomoticz' settings have been removed early March 2022 so are not even in the latest Stable anymore.

I am quite certain that the mentioned issues are caching issues with the different browsers. Make sure you clear everything.

An additional sort of way to make sure items are reloaded, use the Developerconsole of the Browser and check 'Disable cache' (or something along that line, differs per browser). Then force a reload of your domoticz UI (CTRL + F5).

On mobile devices, sometimes it helps to try to load the (cached) page when NOT connected to the network (airplane mode for example, or WiFi off) so the page fails to load. Then when reconnected, try to load the page again and now it will do a full reload of all assets.

**Comment by ionspicica** [comment]
> The screenshot from @ionspicica shows an old setup screen as for example the 'MyDomoticz' settings have been removed early March 2022 so are not even in the latest Stable anymore.

The Settings page does not load correctly, the version that was before the update was also beta. I deleted the cache, I reloaded, I also tried in the private tab, nothing helps

**Comment by ionspicica** [comment]
![DB Browser for SQLite - CUsersIon SpicicaDesktopNew foldefrdomoticz db](https://user-images.githubusercontent.com/13585500/206535192-b8743ffa-6943-4335-905c-723929f13a67.jpg)
so the problem is solved, I compared the .db between a newly installed copy and my .db, the problem was that for me the user did not have the active status, after I changed the `Active ` field from 0 to 1 everything returned to normal

**Comment by acaonweb** [comment]
Ok, this could be a workaround, there will be another way?

**Comment by kiddigital** [comment]
> 
> so the problem is solved, I compared the .db between a newly installed copy and my .db, the problem was that for me the user did not have the active status, after I changed the `Active ` field from 0 to 1 everything returned to normal

That is a very interesting find. Recently there have been changes in automatically loading the first admin user when accessing from a Trusted network. Your finding could be related. I'll try to dig a little deeper to see how your situation could occur.

2 questions:
- Do you have any 'trusted' network set? See 'security'-tab under 'setup'. (DB pref variable 'WebLocalNetworks`)?
- Can you run your Domoticz instance with `--debuglevel auth` (and `--loglevel all`) when the admin user 'active' status is back to 0? Interested to see the debug output.

**Comment by barts2108** [comment]
I am going to put some €0.02 as well. I have 2 Domoticz installations where 1 is working ok and the other is not since this "navbar buttons missing" bug/feature has been introduced

![image](https://user-images.githubusercontent.com/520875/206639443-e3d3ad92-ea43-4d43-bcf0-1506454e47ac.png)

Indeed I do have 2 users on the system with the missing buttons, and now I see that the wrong user has been loaded. This "wrong" user is a slave user with sharing swithced ON, but all active menu's are switched off.

This morning however, nothing really was present in both of them (just top bar and empty screens). I was able to see this `$.t` is not a function inside the developer tools, but I was able to open the pages in my mobile, and got them back to work on the PC as well. 

Whenever I use the "logout (slave1)" button, nothing happens, It does not logout because of the security setting that no username is needed for local networks.

Question: How can you decide which admin user should be loaded for local networks ? If you would like to load a default user, for local networks, then at least you should let us choose which admin user that should be !

**Comment by empierre** [comment]
same issue here, just roll backed

**Comment by jochem25** [comment]
I did had the same problem and indeed it was user related, This morning I updated to the latest beta (build 14825) and then the settings menu looked fine. And as soon as I enabled all the menus for the last user in the user list, everything was working fine.

**Comment by kiddigital** [comment]
ok.. I was able to recreate the problem and the weird looking screen is not a caching problem (really looked like it, but it is not in this case).

It is User related. Everything works fine if there is at least 1 Admin user (with active status) and enabled menus.

Working on a resolution...

**Comment by barts2108** [comment]
@kiddigital Please take into account that I have 2 admin accounts, one with full menu, one without menu.... This change to take the first admin user took the one that has no menu. So not everything works fine if there are more than 1 admin users, because domoticz decides to take the wrong one.

**Comment by gizmocuz** [comment]
@barts2108 , why do you need two admin users? Other admin can screw up the system so bad that the other admin can't login anymore anyway.
@kiddigital , Maybe we should prevent having multiple admin users

**Comment by barts2108** [comment]
One for me, and one for slave usage.

Furhtermore it is quite normal to be able to have multiple admin accounts, as you don't want to share passwords. I guess the only option is to make it in such a way that you can select which admin is the default admin account.

**Comment by gizmocuz** [comment]
Ehm no, in your switch/router you also have one admin account.
Your slave domoticz can use a normal user with shared devices

**Comment by gizmocuz** [comment]
Besides it is another security risk

**Comment by barts2108** [comment]
Ehm yes, my switch/router has multiple user accounts which can be admin or not. (Cisco Catalyst)

**Comment by gizmocuz** [comment]
Yes yes,... Domoticz ain't a Cisco switch. Anyway, it does not make sense and is a security risk, and for remote master/slave you can use a normal user
But let's stick to the topic

**Comment by sylar6725** [comment]
After 2 days without problem in build 14823, it started again. No change was made, no probe added, just consultation.
![image](https://user-images.githubusercontent.com/71662117/206754156-30e84bf1-6dff-4f5e-ab6a-e7393f9ee374.png)
log in console:
![image](https://user-images.githubusercontent.com/71662117/206757917-23714424-5194-4821-b1d4-0e5c180aba64.png)
![image](https://user-images.githubusercontent.com/71662117/206758154-0edddf7c-7f07-4859-a53a-134a6eaf0e88.png)
like the first time, after using the 'updatebeta.sh' script, it works again, but for how long?

**Comment by barts2108** [comment]
Same here, 15 minutes ago I was operating on some heater settings, now 15 minutes later, both my Domoticz are completely empty. Inspect window shows the same thing ... $.t is not a function

![image](https://user-images.githubusercontent.com/520875/206864707-d7b858c7-57bd-4c89-9623-85df26b45637.png)

**Comment by barts2108** [comment]
![image](https://user-images.githubusercontent.com/520875/206865267-08b47a66-3524-4f42-beec-8f7d686e7fcc.png)

Has anything chaned with the update notification ? 

Looks like you have released a new version and the `ShowUpdateNotification` is crashing the entire Domotics frontend

EDIT: 

Manually executing the `updatebeta `script installed build 14828 (on both systems) and both are running again.

Scary that all of a sudden something happens (probably externally with the update notification) that totally nothing works anymore in the web interface.

**Comment by waltervl** [comment]
> Scary that all of a sudden something happens (probably externally with the update notification) that totally nothing works anymore in the web interface.

This is beta build so fully on your own risk. Things like this can happen. If you do not want this to happen stay on the stable release stream and update only 1 or 2 times per year.

**Comment by kiddigital** [comment]
> Same here, 15 minutes ago I was operating on some heater settings, now 15 minutes later, both my Domoticz are completely empty. Inspect window shows the same thing ... $.t is not a function
> 
> ![image](https://user-images.githubusercontent.com/520875/206864707-d7b858c7-57bd-4c89-9623-85df26b45637.png)

Interesting to see that beneath the logout button, it says '(unknown)' which means the domoticz does not know under which User the UI is running. This should not/never be the case, but this shows it is.

Is it correct that you use the UI without the need to login (provide Username and Password) because the UI is coming from within the Trusted (local) network?

Did it occur when you where actively using the UI? or was it just coming back after a while and the UI was still open?

**Comment by kiddigital** [comment]
Beta 14831 contains a fix (revert of a previous change, see PR #5452 ) that most likely solves the issue. Please test and confirm if the problem disappears.

**Comment by barts2108** [comment]
I am fully aware of being on the beta build. With "scary" I meant to say that it looks like beta's are released without testing, and IMHO then it would be an Alpha.

This morning refreshing Domoticz again showed the empty screens. After manually updating again with the `updatebeta` script it works again. 

Definitely somthing wrong with the update code, causing the entire front-end to break. Is there a possibity to test this locally ? e.g. by putting a file in a specific place triggering the update code to execute ?

**Comment by barts2108** [comment]
I have seen your revert. Most of the code only handles for the main user. My systems are setup to not require login for LAN

![image](https://user-images.githubusercontent.com/520875/206893726-00e7da39-4ba1-46ff-ae8a-e50a17dc92e3.png)

Even when I click "Logout" in the menu, My username remains "logged in", but maybe there is no active session for that user anymore ?

I will put one system without the "no require loging for LAN" and keep one with the setting to see if it makes a difference. Can you drop a message reply here when a new beta is released ? Then I can check if there's a difference.

**Comment by gizmocuz** [comment]
New beta has been build

**Comment by barts2108** [comment]
No updates available (yet?) in my 2 systems. Both are on build 14831 since this morning update

**Comment by gizmocuz** [comment]
Yes that is the update with the above PR/Patch

**Comment by barts2108** [comment]
For next update I have changed one system with settings to require login on LAN as well. Then I will be able to check if that makes a difference. As the problem seems to relate to updates being available I can only re-test with next update.

**Comment by kiddigital** [comment]
@barts2108 , most likely it is not update related but User related. If both systems are on 14831, the problem should be gone on both.

Let us know if it re-emerged.

**Comment by mgugu10** [comment]
Problem (Web UI crash) re-emerged today few days after installing 14831.

**Comment by waltervl** [comment]
Same with me, checked yesterday my test environment and it had this issue again 14831.  Not yet updated to latest beta. Going to do that this evening.

**Comment by sylar6725** [comment]
Same yesterday with 14831
-> update to the last beta
re fail today with the 14839

**Comment by gizmocuz** [comment]
Had the same issue, updated to the latest beta and hopefully this is solved now

**Comment by sylar6725** [comment]
Fail too in 14839 build in a Trusted (local) network.

But I could reproduce the problem from this connection.
Just change language setting or theme and the webUI fail again.

**Comment by sylar6725** [comment]
Yes, i confirm
I now in 14855 build, and the WebUI don't fail after switch language or theme 👏

**Comment by jochem25** [comment]
same issue here, upgraded to the last beta, and everything except the switch page is working correctly. Th switch page is empty.

**Comment by gizmocuz** [comment]
Did you clear your browser cache? If yes, try in a private window to make sure it's not cache related

**Comment by jochem25** [comment]
i had cleared the cache. But indeed in a privat window it is working

**Comment by gizmocuz** [comment]
That means your cache is not cleared correctly

**Comment by jochem25** [comment]
understood. It is working now.

**Comment by waltervl** [comment]
Updated 2 hours ago to 14854, seems successfull but failed again after a short time.
Just Updated to 14855, working again, hopefully it holds....

**Comment by barts2108** [comment]
I just on my systems and both fail... Both are on 14831 (5 days ago after the revert to this version) and I did not get any update notifications before today. Still it seems to occur once an update is available, as its the topmost entry in the browser console

![image](https://user-images.githubusercontent.com/520875/208139887-f04a41b6-e7a5-46f0-987c-f09fa39f4b85.png)


Done a manual (from terminal) update through the updatebeta, and then the 14855 version is installed and working on both systems again. Unfortunately I had to restore my trusted network settings as removing it, causes some of my scripts to malfunction (authentication required in openURL, which is not in the scripts). 

In the code I see that some changes done regarding the trusted network as well. If the bug still exists (lets hope not), my prediction is that it will fail once a update is available, and then only on systems that are have trusted network set.

**Comment by waltervl** [comment]
> Done a manual (from terminal) update through the updatebeta, and then the 14855 version is installed and working on both systems again. Unfortunately I had to restore my trusted network settings as removing it, causes some of my scripts to malfunction (authentication required in openURL, which is not in the scripts).


@barts2108 What did you do to restore your trusted network settings or what was wrong after the update as it seems other users have this issue too https://github.com/domoticz/domoticz/issues/5465

**Comment by barts2108** [comment]
Short history... 

- about 5 days ago I reverted to 14831 ([see comment above](https://github.com/domoticz/domoticz/issues/5445#issuecomment-1345494865)), 
- been using both domoticz every day since then
- I had one system removed the trusted network IP addresses from the settings, to allow checking if that influences the problem
- day before yesterday I found my scripts malfunctioning due to the openURL calls not having authentication. So I restored my trusted network settings.
- today approx an hour ago, I opened up my web interface to domoticz and found the interface completely empty ([see comment above](https://github.com/domoticz/domoticz/issues/5445#issuecomment-1345298508))
- opened VNC to the 2 raspberry pi's running domoticz and executed the `./updatebeta` script. This will update the domoticz and then it works again.

Over the last week, it seems to me that this problem occurs everytime an update is present to be downloaded (the green toaster showing up). The browser console also shows me that there is a problem with the `showUpdateNotification`. My educated guess is that the update notification somehow has something related to users, which is broken since the user modifications

The trusted network settings I removed on one system from the domoticz settings ([see comment above](https://github.com/domoticz/domoticz/issues/5445#issuecomment-1345489863)) and put them back yesterday or day before.

**Comment by waltervl** [comment]
From  https://www.domoticz.com/forum/viewtopic.php?t=39505&start=40 seems to be related with new update notification. WebUI is running fine on 14855 until new beta release has been published.

**Comment by jochem25** [comment]
I also remarked that I cannot delete a a user. I had two admin users, so I made one user a normal user (as advised in this topic). But as I don`t use this user anymore now, I tried to delete it. I get the message "can`t delete last admin user".

**Comment by barts2108** [comment]
@waltervl If I did it right, I have changed my settings again yesterday. One system with "trusted network" ON, and one with "trusted network" OFF. However I can only check tonight if there's a difference

**Comment by barts2108** [comment]
@waltervl Back home. Both systems on 14855 failed to load the web interface, as in [see comment above](https://github.com/domoticz/domoticz/issues/5445#issuecomment-1345298508)

One system had local networks (no username/password) set with values `127.0.0.*;192.168.199.*;192.168.169.*` , the other had nothing set in there. 

After a manual update from the command line using `./updatebeta` both are on 14857.

Seems to me more and more related to the update functionality rather than user functionality.

**Comment by gizmocuz** [comment]
Please update to beta 14863

**Comment by waltervl** [comment]
On my system I could update without issues from 14855 to 14863 this morning from web interface.

**Comment by gizmocuz** [comment]
Yes but when the userinterface does not work, you need to update manually

cd domoticz
./updatebeta

**Comment by barts2108** [comment]
Both my systems just updated manually again from 14855 to 14870. Hope that this issue is finally solved now. Will see at next update.

**Comment by gizmocuz** [comment]
Still working correctly here, pretty sure it's solved now

**Comment by barts2108** [comment]
Here it says no update available (both at 14870), will keep an eye on it when an update *is* available.

**Comment by gizmocuz** [comment]
14870 is fine, if you still have a issue clear your browser cache

**Comment by barts2108** [comment]
Just updated both from 14870 to 14874. At first the green toaster was not there, even after some `Ctrl+F5`

In the `Setup` menu pressed `Check for Update` and it said there's an update. I canceled that dialog, and after a `Ctrl+F5` the green toaster showed up again

At least no more broken frontend 👍

**Comment by gizmocuz** [comment]
Yes this issue is closed 2 days ago

**Comment by daafunky** [comment]
Happened again, I was stable few days on 14854, then web frontend stoped working without any reason (mobile app was working correctly).
I had to update manualy in terminal using ./updatebeta
Now stable on 14895.

**Comment by gizmocuz** [comment]
@daafunky , still no issues here
Your issue seems different, and it seems you are experiencing a crash and it's not related to a translation object that is not defined
(Because you should have some tabs still working)
Please check your system resources and also your power supply in case you are using a embedded system.
Happened to me sometimes when using a cheap power adapter that could not deliver enough current
