### ISSUE TITLE
Arilux - Mono light type are added as RGB

### ISSUE THREAD

**Issue by rpeyron** [domoticz/domoticz#5448]
When adding a light in Arilux hardware, even if we select "Mono" as Light Type:

![Domoticz_MagicHome_20221208_162759](https://user-images.githubusercontent.com/3126751/206502617-466920da-392b-45f9-96a0-8a45882bb26d.png)

the device is added as RGB:

![Domoticz_MagicHome_20221208_162914](https://user-images.githubusercontent.com/3126751/206503044-3a93bf2e-96cc-49b2-ae79-a9e568582960.png)

I guess it may be related to the mismatch between the label and the data-i18n element in [Hardware.html](https://github.com/domoticz/domoticz/blob/f64304efb7c74a7f37f237a06c16c8a5544a14f7/www/app/hardware/Hardware.html#L1622):

https://github.com/domoticz/domoticz/blob/f64304efb7c74a7f37f237a06c16c8a5544a14f7/www/app/hardware/Hardware.html#L1622

But still, it would be nice to have all the possibilities offered by ColorSwitch and to be able to add Single Color LED controller without the need to patch the subtype in the database.

**Comment by gizmocuz** [comment]
@rpeyron , is it possible you could make a PR to fix this issue? I don't think it is related to this problem, but for sure this is wrong when there is no translation.
It will take the value 0
Maybe it is wrongly created in the hardware class?

**Comment by rpeyron** [comment]
Sure, here #5451 

There was indeed no translation in the french strings
