### ISSUE TITLE
New Enphase Envoy software with enhanced security

### ISSUE THREAD

**Issue by iamjlm** [domoticz/domoticz#5449]
Hello,
I recently had to replace the Enphase Envoy unit because of a hardware failure.
I didn't pay attention immediately to the domoticz interface, but the day after getting numerous errors in domoticz log, I discover that the envoy unit had a new software (D7.0.88 (5580b1)), with enhanced access security.
In particular the new software is using https and a token (one year duration) to get access.
The description is provided in the pdf attachement.

Questions: did someone already looked at this change ?
Thanks for your help.

[TechBrief-IQ-Gateway-Access-using-Token-EN-US.pdf](https://github.com/domoticz/domoticz/files/10193396/TechBrief-IQ-Gateway-Access-using-Token-EN-US.pdf)

**Comment by gizmocuz** [comment]
Did you try the latest beta? This is already working

**Comment by gizmocuz** [comment]
Also when you create a issue, search in the issues first (like the word 'envoy')

**Comment by iamjlm** [comment]
OK. Thanks
PS: I checked but with "enphase" and not "envoy" !

**Comment by gizmocuz** [comment]
No worries... Hope all now with the new firmware!
