### ISSUE TITLE
Lot of errors compiling any release of Domoticz

### ISSUE THREAD

**Issue by jotakar** [domoticz/domoticz#5454]
MY system is a 32bits machine, with Ubuntu 16.04, gcc 6, openssl 1.1.0, cmake 3.20, clang-6 
When I try to compile Domoticz I get lot of errors. 
The first  (cannot call member function without object ) was fixed installing clang-6  and using cmake
Then, using clang in cmake, a lot of warnings and finally another error about sqlite...
If I try with older version (2020.1)  I get errors like    use of undeclared identifier '_1' ....  I cannot understand the origin of this strange errors.
I don't understand, I'm sure theres is a requirement that I can not see.
Any idea?
Thanks

**Comment by kiddigital** [comment]
Why such an 'old' Ubuntu version? Try 20.04 LTS or 22.04. Newer GCC, libraries, etc.

Should compile fine.

**Comment by gizmocuz** [comment]
Also please follow this guide

https://www.domoticz.com/wiki/Build_Domoticz_from_source

**Comment by jotakar** [comment]
Cannot install Ubuntu 20 in a 32bits machine. I've followed the guide in wiki. The guide doesn't say anything about sqlite and this was my last error when compile.

**Comment by gizmocuz** [comment]
I guess you need to read the guide again letter by letter as if you search on this page for sqlite you will see it mentioned

**Comment by jotakar** [comment]
Sorry, yes it's there. Then I have installed the package. But I have the error :
SQLHelper.cpp:623:16: error: use of undeclared identifier 'sqlite3_prepare_v3'
        int iRetVal = sqlite3_prepare_v3(m_DBase, pSQL.c_str(), pSQL.length(), 0, &m_Statement, &pTail);
        
 I cannot understand why this kind of errors. They looks like basic programming error (and this is not possible), I'm sure there is a problem with versions of compiler or so. I'm very lost.

**Comment by gizmocuz** [comment]
Okey first update your system 18.04 and then you should have the right sqlite version
Now your system is old, has obsolete services and is therefor also very dangerous

From what I understand is that you can install the latest debian on your 32 bit system, so please do this

**Comment by kiddigital** [comment]
@jotakar , instead of Ubuntu you can run Debian.

Domoticz should run fine on 32-bit [Debian Buster](https://www.debian.org/releases/buster/) but also on the latest BullsEye release.
