### ISSUE TITLE
403 on local or remote for all

### ISSUE THREAD

**Issue by peteralm097** [domoticz/domoticz#5455]
I think it may be possible that #5443 could have locked me out of domoticz!

I am getting 403 on local, internet and in incognito mode. Unable to login at the moment.

Could be my config being no longer compatible with the new version - haven't had time to experiment 

P.

**Comment by gizmocuz** [comment]
Thanks for noticing! Fix has been made and if you update your system it should be solved

You can update by using the command line:

cd domoticz
./updatebeta
