### ISSUE TITLE
Impossible to replace a temperature sensor (based on Oregon sensor received by a RF player

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#5456]
Hello,

I can't manage to keep my log history when changing batteries on an Oregon sensor, by using the usual replacement procedure.
The new device is deleted, the old one is not updated anymore.
In my device view, the new one has completely disappeared, and I have this RFplayer plugin error message : 

`2022-12-15 09:47:35.130 Error: Chauffage Central: Device creation failed, Hardware/Unit combination (12:33) already exists in Domoticz.`

**Comment by gizmocuz** [comment]
This is caused because the plugin does not make use of DeviceID/Type/Subtype/Unit , probably because it is using the old plugin api method
You can do this manually in a database editor (SQLite Personal edition for example)

**Comment by rezzalex** [comment]
I have successfully open the database but then I am lost...
I have suppress and recreate a new device, and lost the history.

I would be a glad to have the "historical data copy from database" procedure, but I would perfectly understand that this is not a priority. 

Can be closed.

**Comment by gizmocuz** [comment]
Not sure I understand your problem? For sure you have some database backups correct?
Historical data copy from database?
It should be quite easy and I am quite sure people can help you on the forum, this is not a forum or helpdesk.

If your new device had ID 123 (in the DeviceStatus table (RowID)), and your old sensor had 100, you should be able to find your old history in the temperature/temperature_calendar table.
You then need to execute a SQL query that changes the DeviceRowID in this table from 100 to 123 and done
