### ISSUE TITLE
Weird screen when "unlogin" from the wan, using a reverse proxy

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#5457]
when clicking here  : 

![image](https://user-images.githubusercontent.com/35136439/207836532-7b1b182e-983f-4b7d-9cf6-bb239d666082.png)

next I got this scren : 
![image](https://user-images.githubusercontent.com/35136439/207836312-e6c14e2a-4805-4cc5-a0cb-6f532ca18c92.png)

**Comment by kiddigital** [comment]
2 things
- update to latest Beta
- clear cache

**Comment by rezzalex** [comment]
it was in private navigation mode with DZ version  2022.2 (build 14831)

**Comment by gizmocuz** [comment]
latest beta is 14839

**Comment by gizmocuz** [comment]
Wrong button 🤔🎅

**Comment by rezzalex** [comment]
same thing using 14839

**Comment by gizmocuz** [comment]
does your domoticz run? could really be offline? There is no name underneath the logout button anymore
What happens when you go to the root page https://(<ipaddress>:port

Do you have this issue locally or remotely and do you use a proxy server?

**Comment by rezzalex** [comment]
I am running DZ in a container, which is still running, even after this disconnection.

You are right, now I don't have the user name in the log out button.

ThIs issue happens only when connecting using my external URL, redirected by Reverse Proxy Nginx to the local URL.
When using directly the local URL, I don't have to log, and the logout button does basically nothing

**Comment by kiddigital** [comment]
@rezzalex , did you add the IP address of the local (reverse) proxy to the list of Trusted Networks?

**Comment by rezzalex** [comment]
@kiddigital , I removed it some time ago, because in a previous version, once the reverse proxy address was added, the log screen was not present anymore, and I still wanted some authentication from the WAN.

I have just added it again, I am now still asked to authenticate (from the external address), and we have the very same weird behavior when using the log-out button

**Comment by kiddigital** [comment]
@rezzalex , ok. With your proxy added to the Trusted Network, DZ knows it can trust the Proxy headers it receives. Then it tries to determine the origin of your request (external LAN) and see that the origin IP address **does not** come from a Trusted Network and therefor it asks you for a Login. Which should be the case don't you agree?

If you do not add the Proxy to the list of Trusted Networks, the Proxy headers are ignored (not trusted) and DZ only looks at the connection it receives (your local Proxy IP when coming from external LAN). I would expect that it would still ask you to login because that IP address is not a trusted network IP address.

Can you show what the logging is saying? Maybe run DZ with some debug flags enabled (`-loglevel all -debuglevel auth,webserver,received`).

You do not get any Error message in the Log?

**Comment by kiddigital** [comment]
@rezzalex , could you perform the log-out action with your Browser developer tools active? (Usually by pressing F12 and select the 'network' tab) So we can see what requests are performed AFTER you press the logout button.

**Comment by rezzalex** [comment]
> @rezzalex , ok. With your proxy added to the Trusted Network, DZ knows it can trust the Proxy headers it receives. Then it tries to determine the origin of your request (external LAN) and see that the origin IP address does not come from a Trusted Network and therefore it asks you for a Login. Which should be the case don't you agree?

Not sure it makes sense to me. 
My expected behavior would be to be asked to log in when I am going through the reverse proxy, or even better only when I come from an external network. If we are asked all the time to log-in, what is the benefit of adding the reverse proxy IP address as a trusted network ?

I have tried to do the same test, but from my mobile using 4G network => same behavior in DZ

>You do not get any Error message in the Log?

no error message in the logs


`

**Comment by rezzalex** [comment]
> @rezzalex , could you perform the log-out action with your Browser developer tools active? (Usually by pressing F12 and select the 'network' tab) So we can see what requests are performed AFTER you press the logout button.

Does it helps  :  

![image](https://user-images.githubusercontent.com/35136439/207869184-2bb3beff-ab6b-4861-aac9-fb0480a57103.png)

**Comment by gizmocuz** [comment]
Maybe because proxy's can be spoofed. And this way you know that it is coming from 'your' proxy server?

**Comment by kiddigital** [comment]
Hi @rezzalex , thx and the developer console shows that after the logout (`dologout`) both the 'getAuth' and 'getConfig' calls are denied (HTTP status code 401). That should **NOT** be the case as both request do not require a User authorization.

Can you show the logging from Domoticz after this action (output on the 'Log' screen under Setup)?

**Comment by kiddigital** [comment]
> > @rezzalex , ok. With your proxy added to the Trusted Network, DZ knows it can trust the Proxy headers it receives. Then it tries to determine the origin of your request (external LAN) and see that the origin IP address does not come from a Trusted Network and therefore it asks you for a Login. Which should be the case don't you agree?
> 
> Not sure it makes sense to me. My expected behavior would be to be asked to log in when I am going through the reverse proxy, or even better only when I come from an external network. If we are asked all the time to log-in, what is the benefit of adding the reverse proxy IP address as a trusted network ?
> 

Agree, you should be asked for a login even when going through a Proxy.
_Unless_ the IP address you are coming from is within the Trusted Network.
The _last_ proxy (the one that makes the final connection to Domoticz, in your case the NGiNX (reverse) proxy) should be also in the Trusted Network so we know we can trust any proxy headers coming from there. Otherwise someone could spoof a Proxy Header telling Domoticz that the requests originated from an IP address that might be in the Trusted Network while the actual request comes from an untrusted IP address. That would cause a security flaw.

**Comment by rezzalex** [comment]
with my current logs settings, there is relly nothing concerning this log-out event in the logs.
 I don't know how to change the DZ log level using docker.

Here is my container params : 
![image](https://user-images.githubusercontent.com/35136439/207871914-f1c377f7-c3ed-491b-b09b-23394cfc965c.png)


and also my security settings : 

![image](https://user-images.githubusercontent.com/35136439/207872425-ae7af6ac-12d0-4bb9-aeb3-a0e0c8f85d20.png)


BTW, what would be the right screen to display? : the login prompt page ?

**Comment by gizmocuz** [comment]
You can use the EXTRA_CMD_ARG environment variable in your docker-compose file

https://hub.docker.com/r/domoticz/domoticz

EXTRA_CMD_ARG="-loglevel all -debuglevel auth,webserver,received"

**Comment by rezzalex** [comment]
@kiddigital , is this normal that my remote ip address is not the same as y reverse proxy ? : 

![image](https://user-images.githubusercontent.com/35136439/207873343-55235299-97b6-446e-ac3b-ae94a195c939.png)

**Comment by kiddigital** [comment]
@rezzalex , what is shown on the _Log_ screen of Domoticz itself? (In the UI)

Before logout and after logging in again.

**Comment by kiddigital** [comment]
> @kiddigital , is this normal that my remote ip address is not the same as y reverse proxy ? :
> 

You are browsing through the proxy (as you are requesting the external URL) so it makes sense that you should see the IP address of your machine on which you are browsing.

Look at the details of both the 'Request' and 'Response' Headers to learn more.

I am trying to figure out why you get an access denied (401) after the logout action, while before you were logged-in. Normally you should receive a 200 OK on both requests telling the UI that the Login screen should be shown. But that is somehow not happening in you case.

**Comment by rezzalex** [comment]
before login : 
![image](https://user-images.githubusercontent.com/35136439/207880964-00bbacd7-fae0-4e90-a9c1-74e083851df3.png)

after a successful login, trying to pass the login URL again doesn't do anything, I am staying on my dashboard page

after log out, I can't do anything, pass the login URL again don't do anything, I am staying on the screen 401 already shared. To log again I need to close my browser tab and launch it again

**Comment by rezzalex** [comment]
not very impactful on my side, but interesting to understand

**Comment by kiddigital** [comment]
please share the 'Request Header' and 'Response Headers; as well as the actual 'Response' of the _getAuth_ request that return the 401 HTTP error code.

**Comment by kiddigital** [comment]
@rezzalex , a new Beta is being build.. once it is available, please update your environment to this new version and test if the problem persists (it should be gone)

**Comment by gizmocuz** [comment]
New beta version is available

**Comment by rezzalex** [comment]
> @rezzalex , a new Beta is being build.. once it is available, please update your environment to this new version and test if the problem persists (it should be gone)

Hello @kiddigital, thank you. now it works! I have the login screen when I log out from using the reverse proxy, and it does nothing while using the local address

**Comment by kiddigital** [comment]
Great.. thx for reporting back
