### ISSUE TITLE
Something changed in Domoticz for HTTP-GET Requests in Plugin?

### ISSUE THREAD

**Issue by sincze** [domoticz/domoticz#5459]
Domoticz Version 2021.1 (Build 13738) is able to use a Python Plugin that issues a simple GET request to a webserver (solar inverter). The inverter is a bit slow in its response however the plugin works just fine.

Domoticz Version 2022.2 the creator of the plugin receives a comment the plugin is broken. A Key could not be found and processed. 
That key was indeed a code glitch and should be fixed. However the Key (KeyError: 'Data') so many times something else should be wrong.  It seems the new Domoticz is almost never receives the Key: 'Data' anymore.

I installed both Domoticz versions side by side using a docker. 
And the plugin still works just fine in the old version of Domoticz but not in the new version. 
I asked the plugin expert @dnpwwo for help but he thinks nothing was changed in how Domoticz handles GET requests.

I guess the new version of Domoticz shutsdown the connection before all data has been received and processed. 
Hence the resulting string can not be decoded correctly (KeyError: 'Data', the key is actually missing) the plugin soft fails.

![image](https://user-images.githubusercontent.com/5776333/207918987-b8f74d91-1362-4713-a0b8-efb44ace0c3f.png)

A lot of work has already been done in this thread but can somebody please explain what was changed in Domoticz ?
https://github.com/sincze/Domoticz-Omnik-Local-Web-Plugin/issues/12

If we wget the specific file and have the plugin process the file in domoticz 2022.2 it works just fine. Meaning it has to do something with the slow webserver. We have no control over slow webservers but should have control over Domoticz I guess.

**Comment by gizmocuz** [comment]
I have looked at the plugin, why is there a kWh and a W sensor created, and why is the W value not also passed to the kWh sensor?
You could have only one sensor kWh (counter+current W value)

I am not a python export, not using python scripts.
This script could maybe be rewritten to use dzVents

I am not sure if there is a need for the configuration parameter for HTTPS or HTTP, if HTTPS is working, please use this!
Else if HTTP is always working, just use that

Dnwpro is the Python expert, lots of people use python with HTTP requests, maybe they use another HTTP library?

But, as the plugin code is not quite small, consider rewriting it to dzVents, or c++, or try another HTTP GET method

**Comment by sincze** [comment]
Thank you for your feedback, definitely room for improvement. 
Please keep in mind the plugin with the older versions of Domoticz fulfilled the needs of Domoticz users. 
As indicated by Domoticz docker tests we have an issue in later Domoticz versions with the GET of slower webservices.

To prevent further similar issues in development it would be nice if it could been taken care of.

**Comment by gizmocuz** [comment]
I don’t think anything changed in domoticz as all other get requests work fine 
But if you see a delay in the code please point it to us

**Comment by sincze** [comment]
Maybe nothing changed and other requests work just fine. :)
You have to agree that the evidence clearly indicates behavior is different in the Domoticz versions right ? 

2 versions of Domoticz in a docker.. 2 different results. Same plugin querying a backend (inverter) server. 

If we spoonfeed a static file obtained separately from the webserver to the 2022 Domoticz version the plugin works as designed.

Beats me to be honest.

**Comment by gizmocuz** [comment]
Well complete the two code versions

**Comment by sincze** [comment]
> Well complete the two code versions

I guess you mean compare the two code versions ?

**Comment by gizmocuz** [comment]
Yes of course…. Spelling correction error 😀

**Comment by peter-h-nl** [comment]
May be a little example code helps solving this issue?
This little piece of code works in Version 2021.1 fine.
In Version 2022.2 however  the same code results in an error: KeyError: 'Data'

Code:
 
def onMessage(self, Connection, Data):
        DumpHTTPResponseToLog(Data)
        Status = int(Data["Status"])

        if (Status == 200):
            **strData = Data["Data"].decode("utf-8", "ignore")**

**Comment by sincze** [comment]
> May be a little example code helps solving this issue? This little piece of code works in Version 2021.1 fine. In Version 2022.2 however the same code results in an error: KeyError: 'Data'
> 
> Code:
> 
> def onMessage(self, Connection, Data): DumpHTTPResponseToLog(Data) Status = int(Data["Status"])
> 
> ```
>     if (Status == 200):
>         **strData = Data["Data"].decode("utf-8", "ignore")**
> ```

Tnx. I can explain that one:
That is because the GET request is not completed and the entry is simply missing. 
SImple fix is to check if that entry exists. in 2022.1 the key **always** existed as the GET request was completed successfullyThe finding is not the rootcause of the problem.

**Comment by fjongma** [comment]
Having the same issue reading data from my Omnik Inverter I used the HTTP example to spot the difference between 2022.1 and 2022.2. In 2022.2, the Data key does not exist, in 2022.1 it does. The output from the inverter does not contain the Data key at all; it is just data. So the question is: where does the Data key in the return (Dict) object gets generated? 
It is not in the Plugin code iteslf, because the HTTP.py example shows the same behavior. IMHO, it must be in the framework  that executes between sending the GTE request in onConnect and the callback to onMessage().

with full debugging on, I noticed that onMessage() is being called while data is coming in from the inverter as result of the first get. It seems onMessage()  is called before all data has been received. But that is not under control of the plugin.

**Comment by kiddigital** [comment]
@sincze , you compared the 2 domoticz versions using docker. Is the rest of the tech-stack identical? I mean, which OS versions, Python versions, Python libraries, OS-libraries, etc. are used for this scenario in both instances?

Domoticz heavily (and needs to) depend on underlying systemlibraries and especially the Python plugins depend on even more underlying packages, libs, etc.

If a recall, but it needs to be validated by checking the different commits between the 2 domoticz version, there have been changes in the Python handling within domoticz due to changes in the exposed Python headers/libs used by domoticz. Those changes could seem fully independent of how Get requests are handled, but cause timing/event changes that might explain the 'onMessage()' differences.

Unfortunately,  this is not something easy to figure out so I hope the above gives you some additional pointers in tracking down possibles changes that might cause this. Good look hunting and hopefully you find something we could improve/fix.

**Comment by pipiche38** [comment]
I don't if that could be realted to, but if you do some HTTP GET and they takes a while to respond, you might block the main thread and in such case the behaviour is not expected.
Would it be possible for you to spawn a thread and do the HTTP-GET inside that one ?

**Comment by sincze** [comment]
> I don't if that could be realted to, but if you do some HTTP GET and they takes a while to respond, you might block the main thread and in such case the behaviour is not expected. Would it be possible for you to spawn a thread and do the HTTP-GET inside that one ?

Would that be a suggestion for me ?? I've to look at an example then first ;-)

**Comment by pipiche38** [comment]
Yes
You can use [dnpwwo plugin](https://github.com/dnpwwo/Domoticz-Google-Plugin/tree/master) as example

**Comment by sincze** [comment]
@kiddigital , Thanks to much for your extensive reply.

> @sincze , you compared the 2 domoticz versions using docker. Is the rest of the tech-stack identical? I mean, which OS versions, Python versions, Python libraries, OS-libraries, etc. are used for this scenario in both instances?

The issue was raised by users of the plugin so I can not stand in for their tech stack. I can only conclude it was not working anymore in the newer Domoticz versions. 
Hence on my barebone Pi 4, I launched 2 dockers ;-) one with the old Domoticz version (working) and the other docker with the new (non working Domoticz version using the same plugin) from the official repository. Working from that and with official sources I work with the assumption the stacks are the same. But if necessary I can spin them up and check the individual python versions of the official docker Domoticz releases. 
 
> Domoticz heavily (and needs to) depend on underlying systemlibraries and especially the Python plugins depend on even more underlying packages, libs, etc.

I would like to refer to my answer as mentioned above. 2 dockers running on the same host, from the official Domoticz resource repository. (If necessary i can definitely check)

> If a recall, but it needs to be validated by checking the different commits between the 2 domoticz version, there have been changes in the Python handling within domoticz due to changes in the exposed Python headers/libs used by domoticz. Those changes could seem fully independent of how Get requests are handled, but cause timing/event changes that might explain the 'onMessage()' differences.

Wow that is new for me but could definitely shed some light on the issue
also raised by @pipiche38 .

> Unfortunately, this is not something easy to figure out so I hope the above gives you some additional pointers in tracking down possibles changes that might cause this. Good look hunting and hopefully you find something we could improve/fix.

@pipiche38 give me a hint on threading the request so we could look into that as well. He mentioned a nice example that I may be able to work with. As I am not a Developer myself but try to interpret code from others and adjust it to my idea. How nice would it be for ChatGPT to give a hand with such a creation process.

**Comment by keesberg** [comment]
Having the same issue reading data from my Omnik Inverter I used the HTTP example to spot the difference between 2022.1 and 2022.2. 
I use     https://github.com/XtheOne/Inverter-Data-Logger/blob/master/README.md

Debug info
023-08-02 12:21:17,517 DEBUG Importing output plugin ConsoleOutput
2023-08-02 12:21:20,722 INFO Loggers found  on the network: ['192.168.1.20', '602086444'].
2023-08-02 12:21:20,722 INFO Connecting to logger with IP: 192.168.1.20 and SN 602086444
2023-08-02 12:21:20,723 INFO connecting to 192.168.1.20 port 8899
2023-08-02 12:21:20,725 DEBUG RAW sent Packet (len=16): 68:02:41:b1:2c:1c:e3:23:2c:1c:e3:23:01:00:91:16  hA,#,#
2023-08-02 12:21:23,729 ERROR Timeout connecting to logger with IP: 192.168.1.20 and SN 602086444, trying next logger.

Linux raspberrypihome 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

**Comment by gizmocuz** [comment]
Does not seem a Domoticz issue
