### ISSUE TITLE
Netatmo data refresh period

### ISSUE THREAD

**Issue by dgilbert2** [domoticz/domoticz#5460]
I see that in stable 2022.2 / issue [#3119](https://github.com/domoticz/domoticz/issues/3119) changed the Netatmo data refresh time from 10 to 15 minutes.

15 minutes is out of step with Netatmo itself (refreshing every 10 minutes) and so when using Netatmo temperature data to control devices (eg heaters) it causes more of a control lag which is quite noticeable.

Could a variable be added to the Hardware tab to allow the user to change the refresh time between say 10 and 20 minutes to allow personal preference for control over error messages (which BTW I'm still getting quite a few every day, even at 15 minutes. Seems to be a fact of life with Netatmo!?)

**Comment by gizmocuz** [comment]
The latest developer that worked on the Netatmo code has put a remark in the code

> 				// 03/03/2022 - PP Changing the Weather polling from 600 to 900s. This has reduce the number of server errors, 
> 				// but do not prevennt to have one time to time
> 

So this is not a good idea.

You are free to compile domoticz yourself and change the value 900 to 600 again see:

https://www.domoticz.com/wiki/Build_Domoticz_from_source

**Comment by dgilbert2** [comment]
The idea though is to allow the user to decide on what refresh period they would like, defaulted to 900. I've used Netatmo since 2017 and in all honesty the errors are no less today, but at 900, the control side is much worse due to the extra time lag. Yes I could recompile myself but this idea is for the benefit of all and their application. Please reconsider.

**Comment by gizmocuz** [comment]
No, the idea is that it is working for all mainstream users and that the system is not getting complicated with all kinds of settings that could also be set wrongly

**Comment by gizmocuz** [comment]
And no idea what you want to control with your temperature readings in 10 minutes, but if you need a quicker response, invest in a small zigbee of 433Mhz temperature sensor, even a 1-wire could do
