### ISSUE TITLE
retrieving / updating via http api doesn't work anymore

### ISSUE THREAD

**Issue by svde** [domoticz/domoticz#5461]
Docker image was updated to build 14852, updating T/H sensors or retrieving data from domoticz using curl doesn't work anymore. Authentication is done as described here: https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Format

http://<username:password@>domoticz-ip<:port>/json.htm?api-call

the request returns:
`<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>`

**Comment by kiddigital** [comment]
Can you run Domoticz with some debug flags enabled and then try again?

Use `-loglevel all -debuglevel auth,webserver,received` and post that output here.

Is the IP-address of the system where these calls come from also in the list of Trusted (local) networks?

**Comment by svde** [comment]
2022-12-16 07:39:41.779  Debug: [web:8080] Host:172.19.0.1 Uri:/json.htm?type=devices&rid=51
2022-12-16 07:39:41.779  Debug: [web:8080] Request Headers:
Host: *redacted*
Authorization: Basic *redacted*
User-Agent: curl/7.85.0
Accept: */*
X-Forwarded-For: *redacted*
X-Forwarded-Host: *redacted*
X-Forwarded-Server: *redacted*
Connection: Keep-Alive

2022-12-16 07:39:41.779  Debug: [web:8080] IP (172.19.0.1) is within Trusted network range!
2022-12-16 07:39:41.779  Debug: [Basic] Found a Basic Auth Header (*redacted*)
2022-12-16 07:39:41.779  Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 0 ()
2022-12-16 07:39:41.779  Debug: [web:8080] Did not find suitable Authorization!
2022-12-16 07:39:41.779  Debug: Web ACLF: 172.19.0.1 - - [16/Dec/2022:07:39:41.779 +0100] "GET /json.htm?type=devices&rid=51 HTTP/1.1" 401 91 - "curl/7.85.0"
2022-12-16 07:39:45.079  subtype       = P1 Smart Meter Power

> Is the IP-address of the system where these calls come from also in the list of Trusted (local) networks?

The requests have a username and password, so they should be authenticated. I don't think they need to be in the trusted network list. As I'm running domoticz in docker and behind apache reverse proxy on a dual stack (ipv4/ipv6) network it makes configuring what is trusted or not based on IP-addresses tricky.

**Comment by kiddigital** [comment]
> 2022-12-16 07:39:41.779  Debug: [web:8080] IP (172.19.0.1) is within Trusted network range!
> 
> 2022-12-16 07:39:41.779  Debug: [Basic] Found a Basic Auth Header (*redacted*)
> 
> 2022-12-16 07:39:41.779  Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 0 ()
> 
> 2022-12-16 07:39:41.779  Debug: [web:8080] Did not find suitable Authorization!
> 

Somehow, the provided Username:Password are not accepted. It did see the header but fails to authenticate.

I also see that you are using a Proxy. Is the actual IP address the request comes from in the Trusted Network list?

**Comment by svde** [comment]
172.19.0.1 is the only IP in the Trusted Network list, which is in docker

my home LAN is 192.168.xx.0/24 and I have a IPv6 /64. This specific request was done with curl on the same host where apache + docker is running, querying the domoticz FQDN. 

redacted line from the apache logfile:

IPv6-address - - 2022-12-16 07:39:41+0100 "GET /json.htm?type=devices&rid=51 HTTP/2.0" 401 91 "domoticz-fqdn" "-" "curl/7.85.0" "-"

the IPv6 address is the same address as where domoticz-fqdn resolves to... local on the machine, assigned to enp7s0

**Comment by kiddigital** [comment]
So I would assume that the 'X-Forwarder-For' header contains the same IPv6 address as the one in the Apache logfile?

**Comment by svde** [comment]
Saw [2e6557ae9a1881505729ee4dd9039fb66d0aa76e ](https://github.com/domoticz/domoticz/commit/2e6557ae9a1881505729ee4dd9039fb66d0aa76e) updated the docker image (build 14854), behavior remains the same:

```
2022-12-16 10:00:21.961  Debug: [web:8080] Host:172.19.0.1 Uri:/json.htm?type=devices&rid=51
2022-12-16 10:00:21.961  Debug: [web:8080] Request Headers:
Host: domoticz.*redacted*
Authorization: Basic *redacted*
User-Agent: curl/7.85.0
Accept: */*
X-Forwarded-For: 2001:470:*redacted*::4
X-Forwarded-Host: domoticz.*redacted*
X-Forwarded-Server: domoticz.*redacted*
Connection: Keep-Alive

2022-12-16 10:00:21.961  Debug: [web:8080] IP (172.19.0.1) is within Trusted network range!
2022-12-16 10:00:21.961  Debug: [Basic] Found a Basic Auth Header (*redacted*)
2022-12-16 10:00:21.961  Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 0 ()
2022-12-16 10:00:21.962  Debug: [web:8080] Did not find suitable Authorization!
2022-12-16 10:00:21.962  Debug: Web ACLF: 172.19.0.1 - - [16/Dec/2022:10:00:21.961 +0100] "GET /json.htm?type=devices&rid=51 HTTP/1.1" 401 91 - "curl/7.85.0"
```

**Comment by kiddigital** [comment]
Thx... this is what happens (now with the latest versions):

- The request is received by Domoticz (Network wise coming from 172.19.0.1)
- DZ sees the Proxy headers and because the request from a Trusted Network (172.19.0.1), DZ knows it can trust the final proxy in the chain (only 1 in this instance) and therefor it can trust the Proxy headers
- So DZ now knows that the actual request comes from `2001:470:*redacted*::4`
- Now is looks for proper Authentication and finds the Basic Auth header
- Then it looks for what _page_ are you requesting (`/json.htm`)
- This is a _special_ page as it is the main API entry point
- DZ **only** allow _Basic Authentication_ for this special page **when** it comes from a Trusted Network
- In this case, the request comes from `2001:470:*redacted*::4` (as established earlier)
       _Which is **NOT** in the list of Trusted Networks_
- And therefor DZ denies (401) the request

Your IPv6 network where the real requests come from, should be added to the list of Trusted Network IF you want to allow Basic Auth request to the API endpoint to pass.

_NOTE: with the now added OAuth2 JWT Token support, you could use the 'authorization grant type' or 'password grant_type' to retrieve a JWT Token and use that as a better and safer alternative instead of Basic Auth with user:password in each request_

**Comment by svde** [comment]
> NOTE: with the now added OAuth2 JWT Token support, you could use the 'authorization grant type' or 'password grant_type' to retrieve a JWT Token and use that as a better and safer alternative instead of Basic Auth with user:password in each request

I'd like to try that. Where can I read how to do that?

**Comment by kiddigital** [comment]
@svde , does it work now (with the IPv6 in the Trusted Network) ?
Can this issue be closed?


For more info on the OAuth2/OIDC, see PR #4872 

Read the [SECURITY_SETUP.md](https://github.com/domoticz/domoticz/blob/development/SECURITY_SETUP.md)

And [this](https://www.domoticz.com/wiki/Security) (WIP) Wiki page

**Comment by svde** [comment]
> @svde , does it work now (with the IPv6 in the Trusted Network) ?
Yes, it works, thank you.
