### ISSUE TITLE
Unauthorized errors with username+password in URL

### ISSUE THREAD

**Issue by jgaalen** [domoticz/domoticz#5465]
Since build 14855 or probably a couple before, I'm unable to login using the username + password in the url. Suddenly after upgrading dmomoticz,  my dashticz and locative aren't working anymore, as Domoticz responds with HTTP-401 Unauthorized. I've tried adding a fresh user, put in the base64 encoded username/passwords, doesn't work.
Also tried adding my local network to the allowed list (it wasn't added before), but that also doesn't work. Always getting an HTTP-401. It worked for years, I guess something got broken in recent builds

**Comment by kiddigital** [comment]
Run with debugging flags (auth,webserver,received) and post the info.

Do you use a Proxy in front of Domoticz? Ensure it in Trusted Network.

See resolutions in recent similar issues.

**Comment by sylar6725** [comment]
I just saw that I have the same error on HA-bridge.
```déc. 16 21:07:27 HA-bridge java[548]: 2022-12-16 21:07:27,607 [qtp1662837544-19] WARN  com.bwssystems.HABridge.plugins.http.HTTPHandler - HTTP response code was not an expected successful response of between 200 - 299, the code was: HTTP/1.1 401 Unauthorized with the content of <<<<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>>>>```

No error in HA-bridge before.
It was not in a trusted network, Username and password are in the URL.
But after adding the server IP in the trusted network, it works again

**Comment by jgaalen** [comment]
> I just saw that I have the same error on HA-bridge. `déc. 16 21:07:27 HA-bridge java[548]: 2022-12-16 21:07:27,607 [qtp1662837544-19] WARN com.bwssystems.HABridge.plugins.http.HTTPHandler - HTTP response code was not an expected successful response of between 200 - 299, the code was: HTTP/1.1 401 Unauthorized with the content of <<<<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>>>>`
> 
> No error in HA-bridge before. It was not in a trusted network, Username and password are in the URL. But after adding the server IP in the trusted network, it works again

If I add the ip to the trusted network, it works, but that is a security breach as the authentication isn't necessary at all. I need the authentication

**Comment by jgaalen** [comment]
> Run with debugging flags (auth,webserver,received) and post the info.
> 
> Do you use a Proxy in front of Domoticz? Ensure it in Trusted Network.
> 
> See resolutions in recent similar issues.

If I add the ip-range to "Local Networks (no username/password)" (I guess this is what you mean with trusted network?) then it works. But it also works without username + password and this is not secure. It worked for years until recently.

**Comment by sylar6725** [comment]
I understand you, it has always worked for me too since the beginning, It's just to give additional information.
I am in the same situation as you ;)

**Comment by barts2108** [comment]
If you are able to change the URL in HA, you can do something like this:

https://username@password:domoticz-ip-address:8080/...

Then you have authentication, but because you have to add the password to the url it is still not secure.

**Comment by decommentator** [comment]
same problem herem after update yesterday all http update sensors aren't working.
Network range is in local networks
Localhost is also in local networks and also not working for update ping sensors

**Comment by kiddigital** [comment]
In the latest Beta's security and Proxy handling have been improved and tightened. Anonymous and unsecured access to Domoticz is not possible anymore.

Also using Basic auth (user/passwd in URL) to access the Domoticz API (`/json.htm`) has been limited to access from the Trusted (previously called 'local') network.

Especially setups where a Proxy is used in front off Domoticz, these changes are noticeable. Before, Domoticz did not look at the actual origin IP of the request but merely at the IP address of the Proxy server. Now it does and validates if the real host IP is secure or not. So when behind a Proxy, make sure that both the Proxy IP and the origin IP(s) are in the Trusted Network.

This was not the case in the past and therefor a probable reason that in some setups now 'Access Denied' (401) are appearing.

Access to Domoticz needs to be secure and controlled as more and more people are using it to control more and more things and not only from there privacy of there own homes but from everywhere.

**Comment by jgaalen** [comment]
> In the latest Beta's security and Proxy handling have been improved and tightened. Anonymous and unsecured access to Domoticz is not possible anymore.
> 
> Also using Basic auth (user/passwd in URL) to access the Domoticz API (`/json.htm`) has been limited to access from the Trusted (previously called 'local') network.
> 
> Especially setups where a Proxy is used in front off Domoticz, these changes are noticeable. Before, Domoticz did not look at the actual origin IP of the request but merely at the IP address of the Proxy server. Now it does and validates if the real host IP is secure or not. So when behind a Proxy, make sure that both the Proxy IP and the origin IP(s) are in the Trusted Network.
> 
> This was not the case in the past and therefor a probable reason that in some setups now 'Access Denied' (401) are appearing.
> 
> Access to Domoticz needs to be secure and controlled as more and more people are using it to control more and more things and not only from there privacy of there own homes but from everywhere.

But looks like it is even more insecure, as trusted networks can do whatever it wants without authentication. I don't know how to solve this. Either I add the services that interact with http to the trusted list, but then authentication is practically disabled, or I don't add them to the list and authentication isn't possible at all

**Comment by kiddigital** [comment]
> But looks like it is even more insecure, as trusted networks can do whatever it wants without authentication. I don't know how to solve this. Either I add the services that interact with http to the trusted list, but then authentication is practically disabled, or I don't add them to the list and authentication isn't possible at all

Can you explain why you think it is less secure? Which scenario is now less secure in your opinion?

Access from within the Trusted network does not require Authorization. If no Authorization is provided, Domoticz will use the first User with Admin rights it can find in the list of Users (mostly the default Admin created at installation).

If Authorization is provided with calls in the Trusted network, Domoticz will use that specific User (and not the first Admin).

**Comment by jgaalen** [comment]
> Can you explain why you think it is less secure? Which scenario is now less secure in your opinion?
> 
> Access from within the Trusted network does not require Authorization. If no Authorization is provided, Domoticz will use the first User with Admin rights it can find in the list of Users (mostly the default Admin created at installation).
> 
> If Authorization is provided with calls in the Trusted network, Domoticz will use that specific User (and not the first Admin).

Ok I didn't knew that is how it works, so trusted network will always be 'insecure' (no auth needed). But how can I make it work for IPs not in the trusted list? I need to be able to access it outside my network through a reversed proxy. I use locative to send my location updates. Now it doesn't accept the authentication from outside the range. When I add the reversed proxy to the trusted list it works of course, but then everyone can access domoticz

**Comment by kiddigital** [comment]
> Ok I didn't knew that is how it works, so trusted network will always be 'insecure' (no auth needed). But how can I make it work for IPs not in the trusted list? I need to be able to access it outside my network through a reversed proxy. I use locative to send my location updates. Now it doesn't accept the authentication from outside the range. When I add the reversed proxy to the trusted list it works of course, but then everyone can access domoticz

Yes, Trusted network does not require (but still uses if provided) Authorization.

When a (reverse) Proxy is used, the IP address of the Proxy has to be in the Trusted Network if Domoticz has to _trust_ the Proxy Header information provided by the Proxy. These headers tell Domoticz where the request really comes from (aa Domoticz only 'sees' the Proxy). If Domoticz can trust the Proxy, it will use the real origin IP address as provided by the Proxy headers.

So adding the IP address of the Proxy to the list does **NOT** open up access to everyone. It just tells Domoticz it can trust the provider Headers to find the real origin and process that origin accordingly.

**Comment by kiddigital** [comment]
@jgaalen , looking at your case I see why the current changes cause an issue for your setup.

You depend on Basic Authentication (user/pass in http request) to call the Domoticz API from 'non trusted sources' (understandable).

Currently Basic Auth requests to the API have been restricted to only be accepted when coming from within the Trusted Network as Basic Auth requests are easily intercepted and also easy vulnerable to brute-force attacks.

The alternative is to use OAuth2 and use one of the provide _grant types_ to request a Token and use that token to get access. Valid tokens are accepted when coming from untrusted sources. Maybe you could look into that if OAuth2 flows can be used.




BTW I hope that these requests with Basic Auth are done over SSL secured HTTP?

**Comment by jgaalen** [comment]
But the authorization feature is currently a bit bogus right? You don't need authorization, everyone in the trusted list has full(!) access even without a username+password. The authorization is just to say who you are, but the password feature is completely irrelevant. And from 'untrusted' locations where you want the auth to be there, it won't work, so the trusted list is a mandatory functionality, you can't work without it. Feels like, either nothing, or everything

**Comment by kiddigital** [comment]
> But the authorization feature is currently a bit bogus right? You don't need authorization, everyone in the trusted list has full(!) access even without a username+password. The authorization is just to say who you are, but the password feature is completely irrelevant. And from 'untrusted' locations where you want the auth to be there, it won't work, so the trusted list is a mandatory functionality, you can't work without it. Feels like, either nothing, or everything

It works fine from untrusted locations. You need Authorization to access Domoticz. Either using the Login screen, providing a valid JWT Token, etc.

The trusted network is exactly that, a 'trusted' network which provides valid Authorization.

The current 'issue' is the fact that the Domoticz API entrypoint only allows Basic Auth as authorization method when in a trusted network. It accept other Authorization methods as well which are allowed from outside the trusted network.

But I can see where external services 'only' offer HTTP (and therefor Basic Auth by putting username/pwd in the URL) calls to the Domoticz API and not provide alternative Authorization methods. I will add a configuration switch to the 'Security' settings to allow Basic Auth authorization to the API from outside trusted networks to support such cases. But remember, that is not considered secure anymore nowadays. Thats why better alternatives like OAuth2 have been developed and adopted widely.

**Comment by kiddigital** [comment]
> .. The authorization is just to say who you are, but the password feature is completely irrelevant. ...

When providing Authorization (also in Trusted network) the credentials are validated and if not valid, access is denied. Even when in a Trusted network.

**Comment by pipiche38** [comment]
What is the rational to decide a Trusted or not trusted network ?

**Comment by decommentator** [comment]
> In the latest Beta's security and Proxy handling have been improved and tightened. Anonymous and unsecured access to Domoticz is not possible anymore.
> 
> Also using Basic auth (user/passwd in URL) to access the Domoticz API (`/json.htm`) has been limited to access from the Trusted (previously called 'local') network.
> 
> Especially setups where a Proxy is used in front off Domoticz, these changes are noticeable. Before, Domoticz did not look at the actual origin IP of the request but merely at the IP address of the Proxy server. Now it does and validates if the real host IP is secure or not. So when behind a Proxy, make sure that both the Proxy IP and the origin IP(s) are in the Trusted Network.
> 
> This was not the case in the past and therefor a probable reason that in some setups now 'Access Denied' (401) are appearing.
> 
> Access to Domoticz needs to be secure and controlled as more and more people are using it to control more and more things and not only from there privacy of there own homes but from everywhere.

sure it needs to be more secure. But now it's a non working situation
this call
"http://$usr:$passwd@$domoip:$domoport/json.htm?type=command&param=udevice&idx=$download_idx&nvalue=0&svalue=$download"

from a trusted network doenst work
doesn't matter if it is localhost or remotehost

**Comment by gizmocuz** [comment]
Yes that’s correct. Previously we could use basic authentication without adding the ip to trusted network
It is now indeed bogus because we could use a user with limited rights with basic auth, but if basic auth was not used this ip has admin rights because it was in the trusted network

@kiddigital , we should undo this requirement

**Comment by pipiche38** [comment]
@gizmocuz could you kindly comment what is the Tusted Network ? because if it is about `Local Networks (no username/password):` settings, then it is starting to be confusing, as username/password is not required

**Comment by kiddigital** [comment]
> 
> @kiddigital , we should undo this requirement 

Agree that the current way creates confusion.

I change it.

The 'problematic' issue, from a security perspective, is the use of the relative unsafe Basic Auth method. Limiting its use to the Trusted Network is safe, but also not really useful.

My suggestion is to at least check if a call to the API using Basic Auth is done encrypted via HTTPS. That way the otherwise plain test user/pass is at least SSL encrypted.

And I will add a setting to the Security setup screen to override (drop) this requirement so it can be used even with plain HTTP.

PR will be there asap.

**Comment by kiddigital** [comment]
> @gizmocuz could you kindly comment what is the Tusted Network ? because if it is about `Local Networks (no username/password):` settings, then it is starting to be confusing, as username/password is not required

Yes, what is/was called the 'Local network' will be renamed to the 'Trusted network'.

**Comment by kiddigital** [comment]
> sure it needs to be more secure. But now it's a non working situation
> 
> this call
> 
> "http://$usr:$passwd@$domoip:$domoport/json.htm?type=command&param=udevice&idx=$download_idx&nvalue=0&svalue=$download"
> 
> 
> 
> from a trusted network doenst work
> 
> doesn't matter if it is localhost or remotehost
> 
> 

What error do you get? What does the logging tell you? Do you use a Proxy?

That call should work fine when performed within the trusted network.

**Comment by jgaalen** [comment]
In my case, I have nothing except localhost in the trusted list. I do not trust my local devices. My wifi could be hacked or a device, if that happens, domoticz is fully open with the new setup (no password = full control). Currently I am using username+password with a selected list of devices per user to control. In that way, if a device get hacked, it only has access to that device in domoticz, even for devices/users that come in via reversed proxy.

A good change would be that if domoticz received an X-Forwarder-For header, is checks both the source ip (proxy) and the x-forwarded-for ip to be in the trusted list. But non-trusted IPs, should just be able to use authentication using either basic-auth or in the url. 

Btw, I've tested the basic-auth and username+pass as querystring, none is working when the IP is not in the trusted list with the latest version. I would expect: IP in the trusted list, then no auth is necessary, when not in the list, auth is necessary. As simple as that right?

**Comment by decommentator** [comment]
> > sure it needs to be more secure. But now it's a non working situation
> > this call
> > "http://$usr:$passwd@$domoip:$domoport/json.htm?type=command&param=udevice&idx=$download_idx&nvalue=0&svalue=$download"
> > from a trusted network doenst work
> > doesn't matter if it is localhost or remotehost
> 
> What error do you get? What does the logging tell you? Do you use a Proxy?
> 
> That call should work fine when performed within the trusted network.

`HTTP/1.1 401 Unauthorized
Content-Length: 91
Content-Type: text/html;charset=UTF-8
Access-Control-Allow-Origin: *
Set-Cookie: DMZSID=none; HttpOnly; Expires=Thu, 01 Jan 1970 00:00:00 GMT

<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>HTTP/1.1 401 Unauthorized
Content-Length: 91
Content-Type: text/html;charset=UTF-8
Access-Control-Allow-Origin: *
Set-Cookie: DMZSID=none; HttpOnly; Expires=Thu, 01 Jan 1970 00:00:00 GMT
`




also tried with unsafe admin account credentials in the file
no proxy, just an other curl from a rpi in the trusted networks :
127.0.0.*; 192.168.0.*

**Comment by kiddigital** [comment]
> In my case, I have nothing except localhost in the trusted list. I do not trust my local devices. My wifi could be hacked or a device, if that happens, domoticz is fully open with the new setup (no password = full control). Currently I am using username+password with a selected list of devices per user to control. In that way, if a device get hacked, it only has access to that device in domoticz, even for devices/users that come in via reversed proxy.
> 
> 

Nice. I like that approach and good advice to other Users to think about the risks in your local environment.

> 
> A good change would be that if domoticz received an X-Forwarder-For header, is checks both the source ip (proxy) and the x-forwarded-for ip to be in the trusted list. But non-trusted IPs, should just be able to use authentication using either basic-auth or in the url. 
> 
> 

That is the case with the new Proxy handling except that Basic Auth as an authorization method is not accepted in such scenarios as it is generally regarded as an unsafe method nowadays. Other methodes (like JWT or X509/pki certificates) are accepted.

But I will change it to accept Basic Auth when used over HTTPS so at least the credentials are transmitted encrypted. And an additional setting will be added to even allow it over plain HTTP so the user has a choice to use this less safe way.


> 
> Btw, I've tested the basic-auth and username+pass as querystring, none is working when the IP is not in the trusted list with the latest version. I would expect: IP in the trusted list, then no auth is necessary, when not in the list, auth is necessary. As simple as that right?

That is correct for API calls (`/json.htm`) as it currently only allows Basic Auth from within the trusted network (will change).

And yes, it is that simple. But you can use Basic Auth in the trusted network as well if you want actions to be done by a specific user instead of the default Admin used in a trusted network. If credentials are provided in a trusted network, they will be used (and access denied if not valid).

**Comment by decommentator** [comment]
I know the problem
the text is
`(Separate by a semicolon, For Example: 127.0.0.*;192.168.0.*)`

but since this update the * isn't accepted

**Comment by pipiche38** [comment]
> I know the problem
> 
> the text is
> 
> `(Separate by a semicolon, For Example: 127.0.0.*;192.168.0.*)`
> 
> 
> 
> but since this update the * isn't accepted

This is weird

**Comment by kiddigital** [comment]
@jgaalen , with the latest Beta (14857) you can use Basic Auth again outside the Trusted network. By default only over HTTPS. If you want to use Basic Auth over plain HTTP, than you need to enable that via the Security settings.

Can you confirm things work for your setup?

**Comment by jgaalen** [comment]
Somehow this beta version isn't available for me? Tried updating via gui, 'No update available' (I have 14855). Then tried upgrading via terminal, but still the same version. I'm using beta/linux/x86_64

**Comment by jgaalen** [comment]
@kiddigital any idea why I don't see the new beta?

**Comment by kiddigital** [comment]
@jgaalen , the Linux build (and containers) has not been updated yet. Windows and Arm build are.

See https://domoticz.com/downloads/

**Comment by jgaalen** [comment]
Thanks, but I'm not using either of them. When would the Linux build be available and why is it even lacking behind?

**Comment by gizmocuz** [comment]
@jgaalen , updates are make when they are ready to be made. Not every change needs to trigger a update
If you want to have a bleeding edge version just build by source

**Comment by jgaalen** [comment]
Ok, but I'm not the one who can (practically easy) test and confirm this change. I'll wait for it to be in the Linux version. Thanks for the effort

**Comment by gizmocuz** [comment]
New beta version is available

**Comment by rezzalex** [comment]
Hello @kiddigital  and @gizmocuz , I have installed the latest 14863 build, check the new "AllowPlainBasicAuth" checkbox,

and tried an API call using my external address, using a reverse proxy : 

https://externalURL/domoticz/json.htm?username=_USER_NAME_&password=_PASS_&type=command&param=switchlight&idx=_xxxx_&switchcmd=On

and I have a 401 error

Is it a reverse proxy thing ?

**Comment by gizmocuz** [comment]
Could you add the IP address of the reversed proxy in the Trusted Networks as well?

**Comment by rezzalex** [comment]
> Could you add the IP address of the reversed proxy in the Trusted Networks as well?

I already did, with the "*" for the last IP number, because the reverse proyx ip address is changed at each restart (docker).
I have changed it to the current real address, same "bad " result...

**Comment by kiddigital** [comment]
@rezzalex 

> Hello @kiddigital and @gizmocuz , I have installed the latest 14863 build, check the new "AllowPlainBasicAuth" checkbox,
> 
> and tried an API call using my external address, using a reverse proxy :
> 
> https://externalURL/domoticz/json.htm?username=_USER_NAME_&password=_PASS_&type=command&param=switchlight&idx=_xxxx_&switchcmd=On
> 
> and I have a 401 error
> 
> Is it a reverse proxy thing ?

You need to put the username/password in front of the URL like this : https://username:password@externalURL/domoticz/json.htm?...

No need to put the username & password as URL parameters.

**Comment by rezzalex** [comment]
not working neither

**Comment by kiddigital** [comment]
> not working neither

What debugging information do you get from Domoticz (run with additional flags `-loglevel all -debuglevel auth,webserver,received`) about these requests?

And what does the logging of your Proxy show?

BTW.. how are you testing this? Which 'browser' are you using?

**Comment by rezzalex** [comment]
I was testing using Google Chrome browser, in the same Local Network as DZ.
I have just tested with MacroDroid, on my android Phone, providing a specific user and password field in Macrodoid UI, and ... it works ...
and that is why I wanted to do initially : capture a notification on my phone to trigger a motion sensor in DZ

it seems I don't know how to test it from Google Chrome web browser... :-(

**Comment by kiddigital** [comment]
@rezzalex , see here for more info

https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#access_using_credentials_in_the_url

Basic Auth is already considered not really secure anymore and Chrome _actively removes_ the user/pass from the URL when sending the request.

**Comment by gizmocuz** [comment]
Yes, I experienced this while testing basic auth myself a few days ago.
When I used 'Postman' it was working
Maybe best to switch to token-based API calls in the near feature

**Comment by jotakar** [comment]
I have too a 401 problem when I try to use IFTTT applets. And here I cannot use any IP in trusted network, it has not a fixed value.

**Comment by gizmocuz** [comment]
@jotakar, I think you should be able to use https://username:password@yourip:port/api_call

**Comment by jotakar** [comment]
I can't: I get same error 401 Unauthorized. 
And I think that use username and password as clear text in this context is not a good idea. 
It must be another way,

**Comment by gizmocuz** [comment]
When you perform a https call (not http!! this will not work) before sending, the username/password will be encoded in the request.
It might still be visible in your IFTTT action....

As we want to have Domoticz secure, I can only think of a quick dirty solution for your issue
Install a nginx proxy that forwards your http/s request internally to Domoticz (with docker-compose for example)

**Comment by jotakar** [comment]
By now I abandone IFTTT. 
I'm working in remote commands, that has the same 401 Unauthorized issue.
The user:pass in url, or as paramaters, doesnt't work. (user:pass@example.com was deprecated some time ago).
I've created a php for sending commands via **curl**. This script is in a external server.
I got passed the authentication using **authoritation basic** in **curl header** (as I've read somewhere in domoticz) and setting **Authentication**: to **Basic-Auth** in Domoticz>Setting>Security
Is this a right way to send JSON commands from remote to Domoticz?

**Comment by kiddigital** [comment]
@jotakar , no need to set the 'Authentication' method to 'Basic-Auth', you can leave it at 'Login'. This setting is used for accessing the UI.

The API supports Basic-Auth regardless of this setting. It _only_ allows it over HTTPS **unless** you enable the 'Basic-Auth over Plain HTTP' setting.

**Comment by jotakar** [comment]
@kiddigital, then why  does the php curl script return _401 Unauthorized_ if  Authentication is set  to Login in settings?
This is my curl, it's hosted in a domain outside domoticz site.
```
$service_url = "https://mydomotiz_site.com/json.htm";
$params = array(
  "type"=>"command",
  "idx"=>"1",
  "param" =>"switchlight",
  "switchcmd"=>"On"    
);
  $strParams = http_build_query($params);
  $curl = curl_init($service_url."?".$strParams);
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
  curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
  curl_setopt($curl, CURLOPT_HTTPHEADER, array("Authorization: Basic dXNlcjpwYXNz"));
  $curl_response = curl_exec($curl);
```

**Edited**: $service_url ="https://mydomotiz_site.com"

**Comment by kiddigital** [comment]
@jotakar , just to double check...  the service_url is https://mydomotiz_site.com **/json.htm** ?

The user you are using has to be an user with Admin rights (not Viewer) for this command to be executed.

What is the response body (see developer tools in your Browser) if the request?

If you run Domoticz with debugging enabled, what additional logging do you see?

**Comment by gizmocuz** [comment]
@kiddigital , a normal user without admin rights is also fine, but indeed not a 'viewer' type

**Comment by jotakar** [comment]
Yes, the url is with json.htm, of course.
If I set login to Basic in setting, it works: the body is
{
	"status" : "OK",
	"title" : "SwitchLight"
}
Log
 User: user (IP: ::1) initiated a switch command (1/Enc-1/On)

But if I set Login it does not work
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
There is no  info in log or debug log
And, of course, I use an Admin user.
It looks like the access with header auth needs basic in setting.

**Comment by kiddigital** [comment]
@jotakar , which (Beta) version of Domoticz are you on?

Basic vs Login should not affect API calls (`/json.htm`)

**Comment by jotakar** [comment]
Yes, but it affects. My version es not Beta is stable, 2022.2

**Comment by kiddigital** [comment]
@jotakar , ok. When still on Stable this issue (and the discussion) does not apply to you.

Recent Beta's have a lot of security improvements and changes making it behave better (and in some cases different) from how the current Stable works.

Best to use the forum for your specific issue and don't forget to mention your version.

**Comment by jotakar** [comment]
Ok, then I'll use the forum for this question. 
Thanks
