### ISSUE TITLE
livesearch layout on mobile 

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#5466]
With introduction of livesearch (great addition!) I see a small layout issue when going on mobile and there is a roomplan selector and livesearch field visible
One of this fields could go on the same row as the sunrise/sunset entry

![Screenshot_20221216-164821](https://user-images.githubusercontent.com/16327072/208138003-2a18e627-804c-41f2-8cde-282589416016.png)

When only one of the fields is available it looks OK

![Screenshot_20221216-164952-954](https://user-images.githubusercontent.com/16327072/208138180-6fa9b215-4ffa-4c12-9b97-a3508076d1eb.png)
![Screenshot_20221216-164923-753](https://user-images.githubusercontent.com/16327072/208138217-f27c58c0-30b9-48f2-a189-75afa1f2f9ab.png)

https://github.com/domoticz/domoticz/pull/5433

**Comment by soif** [comment]
is it better with #5474 ?

**Comment by ldrolez** [comment]
![Screenshot_2022-12-22-09-38-32-797_com android chrome](https://user-images.githubusercontent.com/2277898/209093298-a7e85b01-566a-4f3d-bb3f-85486e0eed9b.png)

Lots of space is now wasted on the main mobile screen, since the livesearch update

**Comment by waltervl** [comment]
What browser, device and Domoticz template?

**Comment by gizmocuz** [comment]
This is my mobile screen

Lights tab:

![image](https://user-images.githubusercontent.com/2265299/209175530-c18326ea-9c19-450f-b833-f8a27d4fdabb.png)

Dashboard:
![image](https://user-images.githubusercontent.com/2265299/209175775-601c5639-8bd3-46f1-b5e1-14b088e90189.png)

**Comment by gizmocuz** [comment]
Default theme

It would be nice if for mobiles the clock/sunrise/set could be on the left side of the room selector like before

**Comment by ldrolez** [comment]
> What browser, device and Domoticz template?

Chrome on Android, dark-th3me

**Comment by ldrolez** [comment]
Removing this helps a lot:
https://github.com/domoticz/domoticz/blob/7ae7737f115ecb9a3ee73eec31f4aefb92038558/www/styles/dark-th3me/custom.css#L71

**Comment by gizmocuz** [comment]
@ldrolez , interesting... could you post a screenshot how it looks when this is removed?
If you want, please make a PR to fix this issue, or I am happy to do this for you

**Comment by ldrolez** [comment]
![2023-01-09 11_48_25-Domoticz](https://user-images.githubusercontent.com/2277898/211291322-313d4600-2e2e-45b3-913e-00d7a5289bc3.png)

**Comment by ldrolez** [comment]
The two Span 'tbFilters' and 'tbTimeSun' have a width of 100%, with 50% it's even better: 
![2023-01-09 11_51_50-Domoticz](https://user-images.githubusercontent.com/2277898/211291678-60cc0ebd-54e9-4626-9021-8bcb78961a95.png)

**Comment by gizmocuz** [comment]
Thank you for the screenshots. Yes bottom one looks perfect. How does it look with the default theme?

**Comment by ldrolez** [comment]
Sorry for the late reply. The main problem is with the dark-th3me. With the default theme less space is wasted.

**Comment by gizmocuz** [comment]
Yes, best to tweak it. If you want and are finished, please make a pull request
