### ISSUE TITLE
Remove lenght restriction of variables in function CheckUserVariable

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5467]
Currently there is a 200 char limit on UserVariables. That limit is not on Text devices.
According to https://www.sqlite.org/limits.html#:~:text=Maximum%20length%20of%20a%20string%20or%20BLOB&text=The%20current%20implementation%20will%20only,231%2D1%20or%202147483647.
there is no real limit on string fields, also not if they are defined as VARCHAR(200)
I need a database text storage of more then 300 char. I now am force to use a dummy Text device which I have to hide.
A better solution would be to store the text in a UserVariable in the database.
Please remove the limit.
```
bool CSQLHelper::CheckUserVariable(const _eUsrVariableType eVartype, const std::string& varvalue, std::string& errorMessage)
{
    if (varvalue.size() > 200) {
        errorMessage = "String exceeds maximum size";
        return false;
    }

```

**Comment by gizmocuz** [comment]
Length check is removed from beta 15059 as the size of the text variable is now a TEXT object and not a varchar

**Comment by SargonofAssyria** [comment]
Tnx a lot...
