### ISSUE TITLE
Livesearch, hidden devices are not hidden anymore.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5468]
Nice feature the Livesearch on several tabs.
I found out that hidden devices (e.g. devices with an '$' at the front) are not hidden anymore.
I am just curious why there is not selection of the roomplan on the Weather tab.
Is it a bug or intentional?

**Comment by waltervl** [comment]
Roomplan selection in weather is also not available in current stable and probably not for a long time, if ever available. I suppose the developer of roomplan did not anticipate to use weather devices in a room.

**Comment by gizmocuz** [comment]
Well I did and about the opp question maybe the wrong json call is called
I have a look at this next week

**Comment by kiddigital** [comment]
> Nice feature the Livesearch on several tabs. I found out that hidden devices (e.g. devices with an '$' at the front) are not hidden anymore.

@soif , where you aware of this feature ('$' hides devices) ? Are they excluded in the _Livesearch_ ?

**Comment by soif** [comment]
Live Search only show/hide devices presents (= that have been rendered by the ajax's devices call) on the pages. 

The ajax call was not modified, but if it includes "$" devices, and render them  (I did not check that), they will certainly be revealed/searched by LiveSearch.

**Comment by soif** [comment]
BTW which pages is/are affected by those hidden devices shown?

**Comment by SargonofAssyria** [comment]
At least the "Switches' page, but it can easily be checked by putting a $ sign in front of the name of any device.
B.t.w. several times the lifesearch field is missing, cannot find the reason / trigger, using 14855.

**Comment by soif** [comment]
Cannot reproduce the bug here.

I've just tested on Light/Switches page, adding the "$" to the name, **hides the device**, as expected..
Hidden devices are not shown later, nor by livesearch.

**Comment by SargonofAssyria** [comment]
I just tested it again and even after a Ctrl-F5 the device with the $ is shown with a name without the $
And yes I deleted cache several times. So this will be a strange bug.

**Comment by waltervl** [comment]
I also tested on 14855 and after renaming a device with $ it is hidden and also it stays hidden with livesearch.

**Comment by gizmocuz** [comment]
The json call decides if hidden devices need to be return … if it is not modified than they should not return

**Comment by SargonofAssyria** [comment]
This is my screen of a hidden device in chrome. First the device and second after I click Edit.
![18 12 2022_19 18 02_REC](https://user-images.githubusercontent.com/24824113/208312958-e6ff749c-c563-44f0-b367-c548f1052386.png)
![18 12 2022_19 18 30_REC](https://user-images.githubusercontent.com/24824113/208312960-9e34b27a-8d95-4770-ab73-6a140108c51c.png)

Also found that after a Roomplan selection and then selecting 'All' does not refresh the screen in Chrome.
The same happens in Microsoft Edge.

**Comment by waltervl** [comment]
Also on chrome (mobile) it works, no issues with livesearch with hidden devices.

**Comment by waltervl** [comment]
> Also found that after a Roomplan selection and then selecting 'All' does not refresh the screen in Chrome. The same happens in Microsoft Edge.

Also this I cannot reproduce in Edge and Firefox. I have no Chrome, but Edge has the same engine now.

**Comment by waltervl** [comment]
@SargonofAssyria please check with browser in private mode to be sure no old cached javascripts are used.

**Comment by SargonofAssyria** [comment]
In Incognito mode it is the same, even if I do a refresh with Ctrl-F5
It even get funnier.
First screen is from normal Chrome, second is from Incognito mode.
![19 12 2022_18 37 41_REC](https://user-images.githubusercontent.com/24824113/208486713-eb11218b-0d03-42be-a341-e8792ba350c2.png)
![19 12 2022_18 40 13_REC](https://user-images.githubusercontent.com/24824113/208486790-4b2bd65b-c442-4959-8cb2-b2c4ea214f1f.png)
On the Incognito screen you can see that it is a hidden device (by the $)

A few minutes later I got even this screen, now the '$' is gone, but I did not change the name, the '$' is still in the name present.
![19 12 2022_18 51 33_REC](https://user-images.githubusercontent.com/24824113/208489104-60f57d84-dbef-4b1f-ac6d-0ccf7c8348e2.png)

**Comment by gizmocuz** [comment]
Ehmm as far as I know room plans always showed hidden devices

**Comment by gizmocuz** [comment]
This has nothing to do with the live search feature and is meant to be

**Comment by SargonofAssyria** [comment]
OK, perhaps should be mentioned in the Wiki. Still strange that the $ sign is sometimes shown and sometimes not.
See above pictures.

**Comment by gizmocuz** [comment]
the $ sign should not be presented, maybe you had a cache issue as in incognito mode there is no cache
I tried in edge/chrome, normal mode, cache mode, all behaves the same
