### ISSUE TITLE
rubbish dimmer slides in webinterface

### ISSUE THREAD

**Issue by MarcelBaas** [domoticz/domoticz#5473]
When I open the webinterface of domoticz the "button's" for the dimmers stretch beyond the other side of the screen. First i thought it was just my smartphone but this problem also appears on the PC. It turns out not to be only a problem for the dimmers but for all slides including for blinds. See screencapture attachted

![image](https://user-images.githubusercontent.com/52255154/208296398-8281c843-1bec-44f2-952a-5455f28b1dd1.png)
![image](https://user-images.githubusercontent.com/52255154/208296433-91a48f1f-22d9-4edb-a9c7-e88ef9a0bd28.png)

Could this be a bug?

**Comment by kiddigital** [comment]
Works fine here in several browsers...

Cache issue? Which version of Domoticz? Which browser(s)?

Make sure all caches are cleared as several UI changes have been made in recent Beta's and Browser caches are persistent sometimes (especially on mobile devices).

**Comment by waltervl** [comment]
I do not see this issue on Firefox (mobile) with latest beta 14855.

**Comment by barts2108** [comment]
Seen this once last week. Ctrl+F5 (reload from server, not from cache) seemed to solve it for me.

**Comment by pipiche38** [comment]
What I noticed is that the slider are set to 0 when switching Off a light, while prior to 2022.2 the slider was remaining at his position and the device was just switchin Off

**Comment by waltervl** [comment]
> What I noticed is that the slider are set to 0 when switching Off a light, while prior to 2022.2 the slider was remaining at his position and the device was just switchin Off

That is a different issue and probably  python plugin framework (or plugin) related. So if framework issue then it needs a new issue

**Comment by gizmocuz** [comment]
@MarcelBaas , still having this issue after a refresh?
If yes, what browser are you using?

**Comment by MarcelBaas** [comment]
Looks ok now. The issue disappeared after an update. Apologies for the late responds
