### ISSUE TITLE
Domoticz and Homebridge

### ISSUE THREAD

**Issue by acaonweb** [domoticz/domoticz#5476]
After auth changes, there a strange behaviour with Homebrige that I think is domoticz related.
As i know, now in domoticz is needed an active admin userm forcing enter in domoticz with username and password.
In homebridge, in domoticz-plugin is needed to configure access credentials, using username:password@DOMOTICZ-IP-ADDRESS 

Now the issue: in domoticz, if is used Basich-Auth
![image](https://user-images.githubusercontent.com/22882393/208375327-83942d6f-c4e8-4377-b6a8-8c2520fbe740.png)
everything is ok, but i'm not able to remember username and password: everytime i need to login
If i use Login Page, 
![image](https://user-images.githubusercontent.com/22882393/208375468-7f344c0c-4462-49d4-85de-8d073777aa72.png)
I can flag the login page to remember access, but homebridge domoticz plugin stops to work,
![image](https://user-images.githubusercontent.com/22882393/208375850-8649697d-4668-45bb-84aa-dce46998ef51.png)

What i have to do?
My setup;
![image](https://user-images.githubusercontent.com/22882393/208376172-43b5a78a-5723-4501-b394-ef4dbcb0997b.png)
![image](https://user-images.githubusercontent.com/22882393/208376242-10303317-8d42-42f3-8239-03add8c95697.png)
![image](https://user-images.githubusercontent.com/22882393/208376403-d8e43618-e195-4598-b0e4-900a97be4f91.png)

**Comment by kiddigital** [comment]
If from HomeBridge the Basic Auth is send over plain HTTP (so not HTTPS) to Domoticz, you need to enable the 'AllowPlainBasicAuth' setting.

For the UI, you should set the 'Auth method' to 'Login'.

**Comment by acaonweb** [comment]
OK, it seems work as expected.
Thanx!!!!

**Comment by dvdbosch** [comment]
Perhaps hijacking this topic a bit. After the needed 2023 update on Domoticz side, Homebridge isnt able to connect/authorize anymore.  Any suggestions?

**Comment by gizmocuz** [comment]
@dvdbosch , as you can read above it's working, so please check your settings.
Also update homebridge

**Comment by acaonweb** [comment]
I've resolved using tip written here

**Comment by dvdbosch** [comment]
AllowPlainBasicAuth is activated. What is needed with the last setting? For the UI, you should set the 'Auth method' to 'Login'. Where to find this one?

**Comment by gizmocuz** [comment]
That was an old setting. Login is now always enabled

**Comment by lsp242** [comment]
This topic is closed... system worked after the update --> server settings with password as above..
but since last week.. I got the same error message. Stil settings in homebridge with username and password en internal marked with V

anything else to check.. because no connection and 401 message
