### ISSUE TITLE
documentation for AddDBLogEntry incorrect

### ISSUE THREAD

**Issue by WillemD61** [domoticz/domoticz#5479]
The documentation on page: [https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s](url)

states that the AddDBLogEntry could be added by setting the code field to "AddDBLogEntry:true"

using CODE=JTdCJTIyQWRkREJMb2dFbnRyeSUyMiUzQSslMjJ0cnVlJTIyJTdE  ????

This is not correct. (hence the question marks?)

One should use : "AddDBLogEntry:dHJ1ZQ==" so only the word "true" needs to be encoded, not the total entry. 

And this AddDBLogEntry can be combined with other entries in the options field if separated by a semicolon for example : "ValueQuantity:Q29zdHM=;ValueUnits:RVVSTw==;DisableLogAutoUpdate:dHJ1ZQ==;AddDBLogEntry:dHJ1ZQ=="

Also please note:
1) if the device is edited using the domoticz device screen then this AddDBLogEntry disappears and needs to be added again. (for example using sqlite3 update on the devicestatus table)
2) if using /json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=COUNTER;USAGE;DATE to put data into the history log then both COUNTER and USAGE should be positive. Any negative value will result in 0 instead.

**Comment by waltervl** [comment]
Thanks, I have updatedc the wiki. I started to experiment with it for documentation purposes but it stranded somewhere as you could see.
