### ISSUE TITLE
Virtual Dimmer looks pretty inconsistent

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#5481]
due to some changes in the behaviour of the Dimmer widget, I started to investigate, and I found some strange things.

Create a Virtual Switch and then Edit and make it a Dimmer

![Screenshot 2022-12-19 at 19 30 00](https://user-images.githubusercontent.com/8291674/208495374-87181af3-1ba6-4dfa-b5f5-9e6c5399725c.png)

Now move the slider on the right, it moved from Off to % and   increase a %
![Screenshot 2022-12-19 at 19 30 09](https://user-images.githubusercontent.com/8291674/208495373-df952dec-f00f-4c92-890d-daeb0d2e7a1e.png)

Then you switch it Off. The % move to Off
![Screenshot 2022-12-19 at 19 30 15](https://user-images.githubusercontent.com/8291674/208495370-b2ece607-3cfc-4ebf-9f1b-ff2aac2eb5b8.png)

Then you switch it On. the Off move from Off to ON
![Screenshot 2022-12-19 at 19 30 22](https://user-images.githubusercontent.com/8291674/208495366-22f11828-b555-406e-b2e3-c001e887147e.png)

So some time we have On some other time we have %

The previous behaviour was to have always On or Off, while the % was used only on the Blinds

Domoticz 2022.2 Build 14855

**Comment by gizmocuz** [comment]
I'm pretty sure percentage was also displayed for dimmers.
In your last step (where it displays 'On'), what happens when you refresh the browser?
Does it change to percentage?

**Comment by pipiche38** [comment]
I’ll check it this evening

**Comment by pipiche38** [comment]
@gizmocuz I re-did the test this morning and despite the fact that I reload/refresh the browser the widget remains On and not with the %

**Comment by gizmocuz** [comment]
Sorry, forgot about this one.
From version 15028, the dimmer now restores to it's previous state when you turn it from Off to On.
Meaning, if the previous state was 37%, you turned it OFF, then ON, it will return to 37% (Set Level command)
