### ISSUE TITLE
ENHANCEMENT : Implement a plugin, or directly new native hardware, for EZVIZ Cameras

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#5482]
Hello,

would it be possible to get inspired by this Home Assistant plugin: https://github.com/RenierM26/ha-ezviz
It seems this plugin allows you to fully manage the cams parameters and alerts directly from HA.

Those cameras have a local RTSP stream but use the manufacturer's cloud to wake up the battery cam.
Would be great also to be able to activate a DZ motion sensor based on those Cam integrated PIR.

**Comment by rezzalex** [comment]
as a workaround, I have modified the MQTT.py code of this project, so that I can receive Motion Detection Events in DZ : 

https://github.com/BaQs/pyEzviz/issues/98

I can share the piece of code is someone is interested

The MQTT part of this project could be even more efficient and "complete" : https://github.com/duanemck/ezviz.net

**Comment by waltervl** [comment]
You perhaps also could have used the MQTT Mapper python plugin than can map non Domoticz MQTT messages to Domoticz Virtual devices https://github.com/FlyingDomotic/domoticz-mqttmapper-plugin

**Comment by rezzalex** [comment]
Hello @waltervl ,

thanks for the good idea.
Currently, what I did in https://github.com/BaQs/pyEzviz/issues/98 is transforming a bit a Python program which return a result and is "on top" of the EZVIZ MQTT messages.
Using https://github.com/duanemck/ezviz.net and https://github.com/FlyingDomotic/domoticz-mqttmapper-plugin together could be a perfect solution, because both based on MQTT, withtout any other "layer on top".
but the Ezviz.net solution is not finalized with docker yet.

**Comment by waltervl** [comment]
I will close this issue. If Ezviz.net MQTT makes the messages Autodiscover compatible it would even be an easier intergration.
