### ISSUE TITLE
Label issue with Scenes logs page

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#5483]
![image](https://user-images.githubusercontent.com/35136439/208638298-7feaaa2b-6d51-404d-974a-cb42d00894b8.png)

**Comment by gizmocuz** [comment]
Invalid issue, no version specified, no idea if latest beta was used that should solve browser issues

**Comment by rezzalex** [comment]
indeed, sorry. you are right. solved using private navigation and the latest beta

**Comment by gizmocuz** [comment]
Hope it's also working in normal navigation instead of private, best to check in a day (or two) if it keeps working. If yes, it is solved
