### ISSUE TITLE
disable login

### ISSUE THREAD

**Issue by vespino** [domoticz/domoticz#5486]
Is it possible to disable the login feature instead of only for local networks?

**Comment by kiddigital** [comment]
No! You _could_ define '0.0.0.0/0' (every IPv4 address so the whole Internet) as your local network. But I would advice to **never do that**!

BTW.... please ask these question on our [forum](https://www.domoticz.com/forum/).

**Comment by vespino** [comment]
What could be causing the login screen to return every now and then? That is my main reason for asking this.

**Comment by gizmocuz** [comment]
The only reason I can think of is
- session cookie cleared
- session cookie expired, long time not logged in
- domoticz restarted because of an update
-

**Comment by vespino** [comment]
And being inside my home network with no outside world connection isn't a valid reason to disable it?

**Comment by kiddigital** [comment]
> And being inside my home network with no outside world connection isn't a valid reason to disable it?

If you are _only_ inside the home network, that is exactly the reason to specify it as the local network.

That way if for whatever reason somehow a connection to the outside is created, it does not automatically mean that Domoticz is open to the outside.

You only need to specify it _once_ and you can forget about it. And it prevents you from future unpleasant surprises.

**Comment by vespino** [comment]
Unless: https://github.com/domoticz/domoticz/issues/5486#issuecomment-1360937046

**Comment by gizmocuz** [comment]
@vespino , this is only when you NOT entered your local ip/range in the trusted networks
Anyway, when not updating a lot, the username/password option is in my opinion still the best to use.
Because you might think it is only used internally until someone has access to your local network (via a hacked system, camera, not-up-to-date washing machine/router/operating system etc...)
