### ISSUE TITLE
Empty interface after some time 

### ISSUE THREAD

**Issue by sebitop** [domoticz/domoticz#5487]
Since a few number of minor versions Domoticz shows an empty interface with only the setup button (generaly 1 or 2 days after update)
the setup button displays the menu but nothing works (event restart or logout)

- clearing the cache and history doesn't change the issue
- trying from my phone on another network neither
- rebooting the raspberry neither
- restarting domoticz neither
- upgrading the raspberry neither (update/upgrade, bullseyes version)
- only updating to the next beta works and then the new version appears
- nothing weird up to then on the log
- happened right now on 14857 now moved to 14870 works again until ?

it seems (and I say it seems) that as soon as a new beta is available (as there are quite a lot these days) the issue happens

here is what I see when the issue appears
![image](https://user-images.githubusercontent.com/99023778/208737471-c8fe47b0-03d4-4c5a-9df6-fb97899279b7.png)

is someone facing the same issue ? or maybe something is happening on my side but I'm struggling to find it out.

let me know if you need any additional info to help

thanks !
sebastien

**Comment by gizmocuz** [comment]
Already reported and now fixed in latest beta
Please use the search option here first before reporting a issue

**Comment by sebitop** [comment]
Sincerely sorry for that I went there without finding it and as after several updates I still had the issue I decided to post
but my 100% fault if I missed it !

thanks for your quick answer anyway !

**Comment by gizmocuz** [comment]
No worries! You can search here in github for issues, default the filter is set to 'open', in this case the issue was already closed but continued
