### ISSUE TITLE
Enhancement: Automatically versioning javascripts and css

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#5489]
Would be nice if we could the build system have the js and css files versioned when changed while building.
And adapt Domoticz webserver to be able to load those versioned files.
Then we have a lot less CLEAR BROWSER CACHE issues ;-)

For inspiration see:
http://particletree.com/notebook/automatically-version-your-css-and-javascript-files/

**Comment by gizmocuz** [comment]
We have a service worker that needs to refresh when a new domoticz BuildHash is found (service-worker.js)
This is not working correctly

**Comment by waltervl** [comment]
Not an expert on this topic but should the cachename not be modified on each build?- So instead of
```
`// ce58d8b85 //forces a cache refresh on every new build
const CACHE_NAME = 'offline';`
```

`const CACHE_NAME = 'offline-ce58d8b85';`

**Comment by waltervl** [comment]
Good read: https://gomakethings.com/how-to-update-a-service-worker/

**Comment by gizmocuz** [comment]
What I understand is that when something was changed in the service-worker.js file the cache was cleared/reloaded
That is why I placed a special keywork at the top **#BuildHash** , this will be replaced in realtime when served from Domoticz

If what you say is true, you could easily test this by replacing 

`const CACHE_NAME = 'offline';`

to

`const CACHE_NAME = 'offline-#BuildHash';`

in your installation's www folder and navigate to your Domoticz instance

**Comment by gizmocuz** [comment]
Also check if the service-worker is installed... Because when using https it needs a valid certificate, also navigating to a non-secure site (http) the service worker is not installed
it will be installed when using localhost, but I guess only developers and a few people navigate to localhost
So it could be that in 95% of the cases nobody at the moment is using a service worker, and appcache was removed quite some time ago

**Comment by waltervl** [comment]
Indeed, in my environment (http) no service worker registered.

**Comment by gizmocuz** [comment]
So it is not related to the service worker and we do not have appcache for a long time now

**Comment by waltervl** [comment]
@soif do you have any experience in forcing a webclient using the changed javascripts, preventing a user browser cache refresh action.
Service worker is not really working because it is https only and a lot of users only work on http (internal network only).

**Comment by gizmocuz** [comment]
@waltervl , a javascript can not force a browser refresh.
I just changed some code. Let this be checked by me first?

**Comment by soif** [comment]
> @soif do you have any experience in forcing a webclient using the changed javascripts, preventing a user browser cache refresh action. Service worker is not really working because it is https only and a lot of users only work on http (internal network only).

Yes I do. I use to add a GET parameter to every asset URL. This is a **rock solid** trick!

I wrote about this on your Dz's Slack, but it seems that you missed it, so here it is again:

_BTW: i don't know how you directly serve HTML pages, directly from C code (i'm used with Apache/php) but if you could find an easy way to inject the version_number/build_number directly in the index.html page, you might solve this recurring issue (pretty common), by suffixing all required assets calls (css & js) by something like "?v=BUILD_NUMBER"ie, in index.html:
`<link rel="stylesheet" href="css/bootstrap.css">`
could become:
`<link rel="stylesheet" href="css/bootstrap.css?v=XXXXXXXXXX">`
(where  XXXXXXXXXX  is the build number and/or version number)This way, you can be sure that the web browser will always be uptodate, without having to ask users to clean their cache... -Just my 2 cents :sunglasses:_

**Comment by soif** [comment]
> the use of query parameters in the cache busting pattern is not advised as it does not always work with intermediate caches. But it is probably the easiest and can work for most cases especially in local networks as there are no intermediates.

"intermediate caches"? you mean something like a proxy, or cache server (ie Varnish), right?
- As you said, they are not supposed to exists in most, if not all (home) local networks.
- if they are not specifically setup-ed for that (and it would be a very bad practice), they should not ignore a GET parameter in the URL. 

So the GET parameter trick, should work in most cases. 😎 
 
> But I agree that we need a way to incorporate the version number in the index.html file when referring to assets. Maybe a build time replacer? (CMake?)

You mean something like ? 
In **index.html.template** , assets link would be written like ` <link rel="stylesheet" href="css/bootstrap.css?v=[[BUILD_VERSION]]">` 
Then, during the build, it would create a final **index.html**, where all "[[BUILD_VERSION]]" strings are replaced by the current BUILD_VERSION

right?

> Maybe we could use a shorter/no-store cache strategy for users on the Beta channel and use a longer caching period for users on the Stable channel.

Using only the GET parameter trick, dont rely on any caching period: As the URLs are changed in each new version, the web browser is forced to re-cache all assets, until the version changes....

**Comment by kiddigital** [comment]
Intermediate caches are indeed things like Varnish, caching Proxies like HAProxy, NGiNX, etc. and are often in the path between the source location of a webapp and the clients Browser. Especially when loading your app from CDN's, etc.

We could/should consider the Domoticz UI as an independent 'client' (similar to other clients like iOS/Android apps, Dashticz, etc) that could be served from a different webserver and the Domoticz webserver 'just' as the API service.

So how would the caching strategy be setup if for example we serve the UI from say Apache or Windows IIS? How would the website config look like?

And yes, we need something during the build that replaces such tags in the index.html and so create an updated file that should become part of the distribution package (download and update).

**Comment by gizmocuz** [comment]
Issue is closed and as most of you are aware, I am looking into this.
There is no reason for discussion about this at the moment

For sure I don't want to add version number behind content... that is not a 2023 solution
The ETag approach I am working on should do the trick much better

There is also no reason to separate the GUI in a separate web server.
Aldo it is possible, not desired and will complicate things for normal users.
(Unless they are going to use docker, but even this seems extreme complicated to setup)

A good development strategy is to use angular/typescript/npm to build the gui, still served from Domoticz
This is however not a task that is ready in a few weeks as the current code is based on AngularJS

Biggest issue (besides the cache refresh issue) is that people don't read. When they create a issue here, it is stated to clear the browser cache, same as on the forum.

Anyway, hope cache issues will be solved in the near feature

**Comment by soif** [comment]
BTW, due to my own experience, the Cache Header, ETag approach is not 100% reliable... 

This sometimes doesnt work, and it is very long/tricky to debug (but in my own case I have **thousands** of pages, and assets to manage 🙄 ).

That's why i finally endup with the (maybe not so _2023_, but **rock solid** solution) URL suffix trick, and it is very easy to implement and debug...

**Comment by gizmocuz** [comment]
Yes, but there are two problems with this approach

- cache keeps filling between new versions
- this is not working for images and external libraries that are depending on css/fonts/images/js/...

**Comment by waltervl** [comment]
Those few small files of Domoticz will not do any harm on client cache location, even if there are 80 versions of that file. For stable users updating 1 or 2 times a year the impact is even fully irrelevant.

For images and external libraries I cannot comment. But those files do not change a lot so perhaps there can be an exception in adding URL suffix for those.
Issue main due t changed js and css files. Fonts and images probably will not chgebwithout filename change. A lot of x

**Comment by gizmocuz** [comment]
No thats not correct and for users that do use beta versions it will flood their system and it is not the correct way
There are better alternatives, and that is why all browsers supports ETag's these days
Anyway, we could also say for all js/css/html to not cache, that is the quick and dirty method, but that is not the right way to solve things in live

**Comment by waltervl** [comment]
My current cache for Domoticz is 3.7 MB so less than 1 mp3 file. It will not flood a system. I have seen cliënt web caches of GB's in my work environment.

But let us hope ETag will do the trick, we are just discussing what would be the next option. :-)

**Comment by gizmocuz** [comment]
Sure because you clear it all the time, imagine 100 beta's
Anyway working on it and it's not up for discussion for now
