### ISSUE TITLE
Sending e-mail from Domoticz: smtps should be used when using SSL port 465

### ISSUE THREAD

**Issue by djoele** [domoticz/domoticz#549]
I have setup a Postfix mailserver that can send e-mail over port 465. To test this I used the following command:

curl -v --url "smtps://<host>:465" --ssl-reqd --mail-from "<mail-from>" --mail-rcpt "<mail-rcpt>" --user "<user><pass>" -T <emailfile> --capath <capath>

Then I tried to setup the same through Domoticz. I used the same settings.
Then I found that the Domoticz page was hanging. I found the following in /var/log/mail.log

....
Mar  7 22:25:44 <host>postfix/smtps/smtpd[6805]: SSL_accept:before/accept initialization
Mar  7 22:25:44 <host>postfix/smtps/smtpd[6805]: read from 55D15920 [55D20DF8](11 bytes => -1 %280xFFFFFFFF%29)

I looked into the source and found the following in domoticz/smtpclient/SMTPClient.cpp:
the used protocol is built up as: 

std::stringstream sstr;
sstr << "smtp://" << m_Server << ":" << m_Port;
std::string szURL=sstr.str();//"smtp://"+MailServer;

So, this means that always the protocol smtp is being used, and not smtps which is needed in case of using SSL port 465.

Then, when I tried to use the curl command also with smtp instead of smtps I got the same log lines as when I tried sending e-mail from Domoticz.

So, I think that smtps should be used to build up the options for curl in case of port 465.

Do you think this would be a solution to be able to send e-mail over port 465 from Domoticz?

**Comment by gizmocuz** [comment]
I changed the code so then when port 465 is used (SSL), we now issue "smtps".
New version uploaded (#4920), hope it is working now...

**Comment by djoele** [comment]
thank you for your fast reply!

will check it tonight and will let you know the result.

---

Van: gizmocuz notifications@github.com
Verzonden: dinsdag 8 maart 2016 07:23
Aan: domoticz/domoticz
CC: djoele
Onderwerp: Re: [domoticz] Sending e-mail from Domoticz: smtps should be used when using SSL port 465 (#549)

I changed the code so then when port 465 is used (SSL), we now issue "smtps".
New version uploaded (#4920), hope it is working now...

##

**Comment by djoele** [comment]
Thank you! Sending e-mail from Domoticz by using port 465 now works.

Issue can be closed.

---

Van: gizmocuz notifications@github.com
Verzonden: dinsdag 8 maart 2016 07:23
Aan: domoticz/domoticz
CC: djoele
Onderwerp: Re: [domoticz] Sending e-mail from Domoticz: smtps should be used when using SSL port 465 (#549)

I changed the code so then when port 465 is used (SSL), we now issue "smtps".
New version uploaded (#4920), hope it is working now...

##

**Comment by gizmocuz** [comment]
Thanks for the feedback !
