### ISSUE TITLE
<Enhancement> BLINDS : personalized action for STOP command 

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#5490]
For blinds device type, we have the possibility to add a manual HTTP or a script action for both up and down action,  but not for stop.
Could it be added ?

**Comment by gizmocuz** [comment]
Not sure if I understand, but it is already possible to specify 'Stop' as a action in JSON

https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Open-Close-Stop_Blinds

Also in dzVents

https://www.domoticz.com/wiki/DzVents:_next_generation_Lua_scripting

It is also explained here

https://www.domoticz.com/wiki/Blinds

**Comment by rezzalex** [comment]
Sorry if it was not clear before.

This is indeed possible with API call and dezvent scripts.
I was referring to the UI :


![IMG_20221222_090701.jpg](https://user-images.githubusercontent.com/35136439/209087524-994d749a-690c-44a5-a5ac-f8bfc2e8419f.jpg)

**Comment by gizmocuz** [comment]
This was initially only made for switches that needed to control external scripts
What you want to do is possible with dzVents I suppose?

**Comment by rezzalex** [comment]
> This was initially only made for switches that needed to control external scripts

this is exactly what I would like to do for the stop command.

> What you want to do is possible with dzVents I suppose?

yes, I think so, it would have been easier from the UI

**Comment by gizmocuz** [comment]
Yes that would be easier, but it would require an additional database field for the DeviceStatus table
And I think not many users need this functionality.
Therefore, please use dzVents and execute the HTTP from there
