### ISSUE TITLE
display of graphs stop once log time is reached

### ISSUE THREAD

**Issue by WillemD61** [domoticz/domoticz#5493]
If the short log is set to X days (with X being 2 to 7) in the settings, then the display of the first graph with title "last X days" works fine until the shortlog is filled up with the full X days of data, then it stops.

So when the meter table contains X days of data, the display of data in the top graph stops. Nothing is shown anymore, although all data is still in the meter table.

**Comment by gizmocuz** [comment]
Could you post some screenshots of what you mean? Records older then xx days should be removed only
What happens if you refresh the page?

**Comment by WillemD61** [comment]
I tried refresh and this partially solves the problem.

If I click on the device to see the log, then the page is shown with an empty top graph. If I then refresh the page, the top graph is filled and shown as it should. 

If I then go back to the device overview and then click on "log" again, the same thing happens. Every time the page opens it starts with an empty top graph and only after refresh the top graph is filled with data. The other graphs are already filled on opening.

**Comment by gizmocuz** [comment]
Screenshots please

**Comment by WillemD61** [comment]
and to add further: it only seems to occur for kWh devices so far

**Comment by gizmocuz** [comment]
Please do not use external references to files/images, you can copy/paste images directly into these messages

**Comment by gizmocuz** [comment]
Does this also happens with temperature devices?
So initially it is empty, and you need to refresh to see the correct data?
Do you have to do this always? because all graphs should be populated to xx days by now?

**Comment by gizmocuz** [comment]
If I display the log of my kWh devices the top graph is always filled
You mean if new measurements arrive, they are not added to the graph?

**Comment by WillemD61** [comment]
1) only for kWh devices, not temperature.
2) always empty on opening, only filled after refresh, not related to new data coming in, it even happens if I repeat this seconds apart
3) happened last week, then I changed shortlog time to 1 day and back to 7 days, problem disappeared. Now that data has reached 7 days hsitory again the problem reoccurs.

Screen on opening:
![Screenshot 2022-12-22 173129](https://user-images.githubusercontent.com/96531991/209185323-a513febe-38c7-4305-b3fc-c0b53eb661b4.jpg)
Screen after refresh:
![Screenshot 2022-12-22 173152](https://user-images.githubusercontent.com/96531991/209185408-4fdf9b2f-2559-4633-9aed-52b9ad11777b.jpg)

**Comment by WillemD61** [comment]
Additional test done: only occurs in Microsoft Edge, not in Google Chrome

**Comment by barts2108** [comment]
If you have this happening, can you try just to click to swtich on "Power generated" ? I think I have seen this before on my system, and the graph is drawn when the second option is selected. 

![image](https://user-images.githubusercontent.com/520875/209281912-a572eb40-0582-4512-9fd2-542f84bb67c5.png)

**Comment by WillemD61** [comment]
No, clicking either power generated or energy generated has no effect, the graph remains empty.

**Comment by gizmocuz** [comment]
Do you have any errors in the browsers developer console when this is happening?

**Comment by WillemD61** [comment]
No errors in the log, and also, just trying it now again, the problem seems to have gone. At the moment all graphs are filled immediately on opening.

I could try it again, shorten the shortlog to 5 days, then set it back to 7, and wait to see what happens in 2 days time? Worth investigating?

**Comment by gizmocuz** [comment]
Yes please…. I did experience this some times in the past with temperature graphs

**Comment by WillemD61** [comment]
The problem did not reoccur yet  ..... I don't understand it anymore...

**Comment by gizmocuz** [comment]
Then we leave it to the fact that is was either solved by installing a new beta version or it was a cache issue
thanks for testing!
