### ISSUE TITLE
Scheduling blinds open when reverse position and state is enabled.

### ISSUE THREAD

**Issue by mooky31** [domoticz/domoticz#5496]
Hello,

Since I migrated to zwave-js-ui and domoticz 2022.2 I can't no longer schedule my blinds (they are inverted, so I checked reverse open/close state) to fully open :
- Setting open, lvl 1% opens the blind around 90%
- Setting open, lvl 100% leaves the blind closed

I haven't found a way to set the level to 0%, or set no level at all.
I even tried something like http://domoticz/json.htm?active=true&command=0&days=128&hour=0&idx=16&level=0&min=30&param=updatetimer&randomness=false&timertype=0&type=command or http://domoticz/json.htm?active=true&command=0&days=128&hour=0&idx=16&min=30&param=updatetimer&randomness=false&timertype=0&type=command : it says OK but sets the level to 100%.

Am I doing something wrong ? Or is there a bug and we no longer can schedule a blind open ?

**Comment by waltervl** [comment]
To be sure, please try this in a private browser  session to be sure all browser cache has been deleted.

**Comment by mooky31** [comment]
I tried, but result is the same : I can't set just "open", i have to set a level. And level 0 doesn't exist.

**Comment by waltervl** [comment]
You have reversed setting but Close should close, level is ignored.
To open you have to set Open and level from 1 to 100% (fully open).
How is the blinds controlled, with what hardware gateway? Seems that it is not yet adapted to the new way of working.

**Comment by gizmocuz** [comment]
Can you set a level for your blinds? (0-100) , or can you control them with open/close only?

When you specify 'close', the level is ignored, and your blind should close
When you specify 'open' you can choose the level 1-100, if you only have open/close, specify open with 100%

First try without reversing anything

**Comment by mooky31** [comment]
Yes I can set a level.
Reverse position is (and never was) checked.

Wether "open/close state inverted" is checked or not, setting level at 1% lowers the blind by 16 cm on my window (212 cm overall).

If I set open 100%, the blind is closed.

I miss a setting "open 0%", which would be needed to fully open when open/close state is inverted but position is not.

**Comment by waltervl** [comment]
Open 100 should open blinds fully. See wiki 
https://www.domoticz.com/wiki/Blinds
So first set the switches right with edit button on device widget to get the behavior correct.

**Comment by mooky31** [comment]
OK I get it.
My blinds are cabled inverted, so with my cabling and without checking anything :
- "open" closes the blinds
- "close" opens the blinds
- "set level 10" slightly closes the blinds
- "set level 90" slightly opens the blinds

So I should check both reverse state and position to get the "default behavior" of the wiki.

But checking only reverse state allowed me to keep the old behavior of the slider.
I didn't do it on purpose, but it was a happy mistake since I prefered the old behavior.
The only drawback is that because of the planning system which doesn't allow to send just "open" nor "set level 0", I can't schedule a full opening whith my settings.

So this is not a bug, but I still think it would be nice to allow the user to plan a simple "open" and not "set level 100" instead. It would allow to choose the preferred slider behavior.

**Comment by waltervl** [comment]
The slider behavior can be changed with the reverse position switch. See the wiki.

**Comment by mooky31** [comment]
@waltervl You don't get it.

In timers, there is no way to send "open". You can just send "close", or "set level" from 1 to 100 percent.
It is assumed that "set level 100" will do the same thing as "open". But if position is reversed, this is not the case : "set level 100" equals "closed". 

Therefore there is no way to send "open" from timers when position is reversed.

**Comment by waltervl** [comment]
In both 2022.2 stable and beta there is Open and Close option in timer. See screenshot:
![Screenshot_20221226-204848-101](https://user-images.githubusercontent.com/16327072/209579543-6eaf62e6-2dc0-4bcd-898e-7a07e6076345.png)

**Comment by waltervl** [comment]
And if the switch reverse position (for slider) and/or reverse state Open/Close is enabled, the commands in Domoticz stay the same. So also the timer commands.

**Comment by mooky31** [comment]
As the first timer of your screenshot shows, "open" always has a percentage attached to it. And since there is no option "open 0%", then I have no way to set level to 0, which is fully opened in my case.
"Open 1" to "open 100" sets my blinds from slightly closed to fully closed, "closed" closes them. I can't set them fully opened.

The cleanest way to solve this according to me would be to have 3 commands instead of 2: open, close, or set level. Level would be greyed out if command is not set to "set level", and there would be options from 1 to 99%. The easier but dirtier way would be to add 0% to the actual list.

**Comment by waltervl** [comment]
Open 0% should be closed and therefore command Closed should be used.
Again, what is your hardware gateway controlling this device? As it seems that is is not fully compatible with Domoticz yet.
See again wiki https://www.domoticz.com/wiki/Blinds

**Comment by mooky31** [comment]
My hardware gateway is a razberry, with fibaro modules. As far as I know they are supported, and they worked flawlessly in 2022.1.

You still don't get that wether "reverse position" is checked or not, open 0% can be opened or closed, according to https://www.domoticz.com/wiki/Blinds.

So reading this doc, for the cases where "Reverse Open/Close State" is checked, open 0% is opened.
![image](https://user-images.githubusercontent.com/54031618/209848412-f0691bea-1125-4459-9b4a-e8dab1e2bb67.png)

From the timers menu, I can only send 'open 1' to 'open 100' and 'closed'.
And since I can't select 'open 0%' nor just 'open', I can't fully open.

**Comment by waltervl** [comment]
Yes indeed, with reverse position switch enabled (to switch slider behavior) you cannot send open 0%, just tested it. And you have troubles with it because the Domoticz MQTT AD integration probably has created a device that does not support 1-100 but 1-15 leads 1% being translated to 10%. Or your blinds device is doing a strange translation.

So perhaps adding 0% as general selection option for Open would solve your issue.
As a workaround disable the reverse position would at least solve the issue to open/close the blinds with timers.

**Comment by HeWo82** [comment]
I have the same problem and need at least the function with 0 percent.

**Comment by gizmocuz** [comment]
Did you already try to schedule a close command?

**Comment by waltervl** [comment]
@gizmocuz Close is working. Open is also working, only it needs a level 1-100. When reverse position is enabled Open needs a 0% level to fully open. 
Open 100 is the same as closed in this use case.

**Comment by waltervl** [comment]
Option to open 0% is added to Domoticz in beta build 14929 (thanks @gizmocuz )
 https://github.com/domoticz/domoticz/commit/776a0c02181e0473378ca7c57d1fd7071e8ad5a4
Please check if it solves the issue.

**Comment by gizmocuz** [comment]
But still I would like to know if scheduling a 'Close' solves your problem as well

**Comment by HeWo82** [comment]
I think that normally the percentage (1-100) is only given for the closed function in the timer.  when the functions are inverted, open and close are exchanged, but the percentage settings are not exchanged.
normal:
Open = Open in Timer
Close = Close (1-100) in Timer

inverted:
Open = Open (1-100) in Timer
Close = Close in Timer

That’s the problem in Programming

**Comment by gizmocuz** [comment]
Okey so you can schedule a full open / close? So there was no issue?

**Comment by waltervl** [comment]
Let @mooky31 check please if it is solved now.
@HeWo82 This should onle be an issue when reverse position and state is enabled.
![reverse pos and state](https://user-images.githubusercontent.com/16327072/211499766-2eac7b9c-07bd-4405-9667-ce058a994090.png)

**Comment by mooky31** [comment]
Sorry but I am not a GIT expert.
Since I am following the releases and not the beta, how can I check just this commit ?
And revert back to the release ? 
Will just backup the two files from the commit, replace them by the patched ones, and put back the backups in place do the trick ?

This domoticz controls my whole house, I don't want it to go nuts...

**Comment by gizmocuz** [comment]
@mooky31 , when you update to the beta, a backup is made inside the backup folder.
If for some reason (remember to clear your browser cache!!) things are not working (which I can't believe in the current stage unless you are using external scripts with basic auth, but this you can solve yourself), you can always revert to your backup (it's an archive which you can restore)
In case you are using Domoticz in a docker, you can just shut the instance down, make a copy of the folder, let it checkout the beta and test

**Comment by mooky31** [comment]
I'm very sorry, I missed your follow-up.

I updated to 2023.1 yesterday. A lot of new features, nice to see, thank you !
All my tests are done in private mode to be sure the cache is not messing with me.

Results : 

Schedule Open 0% (or off, show the same in the interface) : the blind is closed
2023-02-17 09:07:01.347 Status: Schedule item started! Name: VRE Entree, Type: On Time, DevID: 1720, Time: 2023-02-17 09:07:01 

Schedule Open 100% : the blind is closed
2023-02-17 09:30:07.811 Status: Schedule item started! Name: VRE Entree, Type: On Time, DevID: 1720, Time: 2023-02-17 09:30:07

So unfortnately, your fix didn't solve the issue.
And due to my delayed response, we missed the release window 😢

**Comment by HeWo82** [comment]
is there a solution now? Programming with 0% did not bring any improvement.

**Comment by gizmocuz** [comment]
I added a dummy switch, changed the type to blinds percentage, enabled inverted position/state
Next I set the slider to 40%
I added a timer (on time) and set the action to close (level 0%)
Waited a minute or two, timer got fired, status of the blind is closed

What goes wrong?

**Comment by HeWo82** [comment]
test it with a zwave (qubino & fibaro) module and the timer does not work in inverted mode as described above. opening only works with 1% and not that the blind is completely open (0% would be open, 100% would be) before switching the inverted mode with the button, everything worked fine.

**Comment by mooky31** [comment]
> I added a dummy switch, changed the type to blinds percentage, enabled inverted position/state Next I set the slider to 40% I added a timer (on time) and set the action to close (level 0%) Waited a minute or two, timer got fired, status of the blind is closed
> 
> What goes wrong?

The problem is that we can't fully open.
Closing works.

**Comment by HeWo82** [comment]
Can we still expect a solution?
as mooky31 writes, closing it is no problem, opening it fully does not work with the timer. only 1%

**Comment by gizmocuz** [comment]
@HeWo82 , did you try the current beta version?

**Comment by mooky31** [comment]
I just installed build 15248.
I set a schedule to Open 0%, it wrotes Open (Off) in the table.

And the blind is fully opened  👍 

Many thanks

**Comment by mooky31** [comment]
On the other hand, the CPU usage has gone way up:
![image](https://github.com/domoticz/domoticz/assets/54031618/e11f2cbf-f168-4788-a2e4-8f26caa72a20)

**Comment by gizmocuz** [comment]
Great it's working! No changes have been made that could cause a high CPU usage. Better check your system/plugins. Disabling them all, check the usage, enabling one-by-one

**Comment by mooky31** [comment]
Indeed, it looks like CPU usage is coming from dzga.
I'll look this way.
