### ISSUE TITLE
Unable to make a room selection under "switches"

### ISSUE THREAD

**Issue by MarcelBaas** [domoticz/domoticz#5498]
Hi,
Since a couple of béta releases the option to filter on a curtain room (area) is not available anymore in the "switches" view. Is there a particular reason for this? 
Since the number of switches is growing in the overview is it very handy to be able to select the living level or the sleeping leve for instance. 
The view "temperature" still has the option. See both included screenshots. I noticed the mobile view. Just checked but it's the same on the PC view 

Releases active : 
Version: 2022.2 (build 14880)
Build Hash: 9135d8a3c
Compile Date: 2022-12-23 12:41:24
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]

![image](https://user-images.githubusercontent.com/52255154/209440752-b880664e-2b86-4abd-803e-1768c553904a.png)
![image](https://user-images.githubusercontent.com/52255154/209440768-74303dbb-7d60-4f7a-b6ff-15d117f61fde.png)

**Comment by gizmocuz** [comment]
@MarcelBaas , that is strange as it is really there. Could you clear your browser cache or try in a private browser?

**Comment by MarcelBaas** [comment]
My bad,

thx now it works again. Needed to empty the cache on chrome and create a new shortcut on the iphone from safari..... problem solved :)

br

**Comment by MarcelBaas** [comment]
My bad,

thx now it works again. Needed to empty the cache on chrome and create a new shortcut on the iphone from safari..... problem solved :)

br
