### ISSUE TITLE
After update the own webpages option gone

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#5500]
After last update i cannot use the buildin webpage options any more.
Did have some pages in the www directory.
And they where vissible in the extra tab.

Hope there is a soltion.

Thanks

**Comment by waltervl** [comment]
Quick solution is to revert back to the backup that is created by the beta update:
https://www.domoticz.com/wiki/Raspberry_Pi#Revert_to_backup_after_incorrect_beta_update

BTW, in my environment Custom pages seems to be working.

**Comment by gizmocuz** [comment]
From which version did you update?
Did you clear the browser cache?
Did you check the user that you used to login to see if the custom pages are enabled?

**Comment by Dylantje** [comment]
> From which version did you update? Did you clear the browser cache? Did you check the user that you used to login to see if the custom pages are enabled?

From early 14... [ beta to beta ]
Yes cleared cache try different browsers

__Did you check the user that you used to login to see if the custom pages are enabled?__:

There was something changed....:-)
When i enable this working like a charm

![ScreenShot300](https://user-images.githubusercontent.com/5214969/209673656-6e9e2724-dea3-4a75-a970-efed512709af.jpg)

THANKS for the great new options!!

**Comment by Dylantje** [comment]
Thanks

**Comment by Dylantje** [comment]
Thanks
