### ISSUE TITLE
HTTP error 401 Unauthorized in API call from IFTTT since last update (14863)

### ISSUE THREAD

**Issue by rcrocus** [domoticz/domoticz#5501]
Hello,

Since my last update in v14863, api call from IFTTT are on error : 401 Unauthorized.
I found a solution by modifying the URL : https://IP:PORT/json.htm?username=userBASE64&password=PWDBASE64&...... by https://user:PWD@IP:PORT/json.htm?......, but user and password are in clear in the URL. I think, it's note very secure...

Could you explain the solution to use (OAuth2 or JWT) with IFTTT ? May be, to update the WIKI pahe on IFTTT : https://www.domoticz.com/wiki/IFTTT_integration_with_Domoticz

Thanks a lot.

Romain

**Comment by jotakar** [comment]
Try to set Authoritation to Basic in Domoticz security settings (it works for me in stable 2022.2 version)
I have the same problem and this setting allow my curls scripts to send JSON commands from remote.
There is another post about auth:
https://github.com/domoticz/domoticz/issues/5465

**Comment by kiddigital** [comment]
Hi @rcrocus

> ...., but user and password are in clear in the URL. I think, it's note very secure...
> 

Sending the User/Pass using Basic-Auth is actually safer as the u/p is not send as is, but (base64) encoded and not as part of the URL but in a separate header. And when done over HTTPS, everything is encrypted once more.

The old way, using URL parameters was much more unsafe as the info ends up in logfiles of webservers and proxies. Although encoded as base64, is is very easy to decode/read.


> 
> 
> Could you explain the solution to use (OAuth2 or JWT) with IFTTT ? ...

I am not familiar with which IAM methods are (not) supported by IFTTT, but in the latest Beta's Domoticz has support for several OAuth2 flows (grant types). Maybe IFTTT can leverage these.

**Comment by Jake1964** [comment]
Same issue here. I have no problem place API calls over the internal network (192.168.178.xxx) (because it is indicated in Domoticz under settings / security that local network addresses are not verifying username/password. From the outside however I get HTML 401 Not Authorized for every call I place.
What I can see is the following: when I logon to the Domoticz GUI, stating the correct username/password and stay in the GUI, I can successfully place my API calls over the external ip-address. As soon as I leave the Domoticz GUI (logout), here ends the acceptance of API calls resulting in HTML 401 codes again. Currently at release 14895.

**Comment by waltervl** [comment]
Did you have **Allow Basic Authentication over plain HTTP** enabled in settings? See wiki https://www.domoticz.com/wiki/Security

**Comment by rcrocus** [comment]
Hello everyone,

Yes, I've enabled **Allow Basic Authentication over plain HTTP**. With this option the API call works from my PC (local network) but doesn't work directly from IFTTT.

**Comment by rezzalex** [comment]
Hello, I don't know if this will help but with build 14863, I have an IFFTT API call working, with both "user" and "login" directly in the URL on 1 side, and with the authentication values encoded in the header on the other side.
I have preferred the second option for better security.

I have a reverse proxy (Ngninx) with its local address added in the local/trusted" network

**Comment by gizmocuz** [comment]
Yes sending the username/password as url parameters, or even as post data, is not ideal!
There is a special basic-auth header that should be used

**Comment by rezzalex** [comment]
Is it the more secure method  : 
![image](https://user-images.githubusercontent.com/35136439/209841507-5adb7410-a3fd-4595-af3d-e2cfa7c2746d.png)
?

I did not see any way to get and then use an Oauth token from IFFTT or from elsewhere

**Comment by kiddigital** [comment]
@rezzalex , Yes this is a more secure method (see [rfc2617](https://datatracker.ietf.org/doc/html/rfc2617)) than passing credentials as part of the URL.

**NOTE**: Often, in most _applications_ where you have to enter a URL and need to provide credentials, it is written in the form `http(s)://<username>:<password>@domain.tld/myurl?params=whatever`. But this is **NOT** how it is send! The application uses this way of defining the request and will transform it into the actual request where it removes the `<username>:<password>@` part from the request itself and uses the information to generate the proper `Authorization: Basic <base64encodeduserpass>` from it.

When you want to call your Domoticz to perform an action from IFTTT, than you need to make sure that you provide credentials as IFTTT does _not_ have a fixed list of IP-addresses you can add to the trusted network list.

But looking at the documentation of the IFTTT Webhook, you can specify [additional headers](https://ifttt.com/maker_webhooks/actions/make_web_request) :) You could add the `Authorization` header there with valid Basic-Auth credentials.

If the calls are **NOT** coming in over a HTTPS secured connection, you need to enable 'Allow Basic-Auth over HTTP' (See 'Security Setup' under 'Settings')

**Comment by kiddigital** [comment]
@rcrocus , if the _integration_ with IFTTT is based on using the IFTTT [webhooks](https://ifttt.com/maker_webhooks), the options are a little limited but using the optional _additional headers_ you could add any security header that Domoticz understands (like `Basic` or `Bearer`).

One could develop a _Domoticz IFTTT service_ that can use a more extensive way of authenticating to your Domoticz instance as IFTTT does support OAuth2/OIDC. But that also has its limitations according the IFTTT documentation.

**Comment by rezzalex** [comment]
> But looking at the documentation of the IFTTT Webhook, you can specify [additional headers](https://ifttt.com/maker_webhooks/actions/make_web_request) :) You could add the `Authorization` header there with valid Basic-Auth credentials.

@kiddigital , this is what I did and what I have described in my first post in this "issue ticket".
I have added the string "_authorization: Basic <encoded_credentials>_" in the IFFTT additional header. Is it already a bit more secure than passing credentials directly in the URL ? Or is it the same (low?) securirty level ?

Would A bearer Token be more secure that the basic auth ? how to generate it for DZ ? how to use it in IFFTT ?

If I understood correctly, using Oauth2 would require an additional specific DZ integration into IFFTT ? right ?

**Comment by kiddigital** [comment]
@rezzalex , using the Authorization header is safer than using the URL as URLs are much easier captured and often logged.

A Bearer token like JWT's are safer as the do not contain credentials. But by default such Tokens have an expiration date so have to be renewed after expiration. And normally a relative short expiration time (like an hour or a few hours) is recommended.

Proper OAuth2/OIDC implementations also offer Refresh token which have a longer lifespan and can be use to obtain a new Token (and Refresh token) so you can have a continuous cycle of refreshing Token without the need to re-Authenticate.

But this would require IFTTT's webhook service to support such Authentication flows. Currently only 'Services' have limited support for these flows.

**Comment by rcrocus** [comment]
@kiddigital, I add the Basic Header instead of user:pwd in the URL and it works. 
I will use it waiting IFTTT's webhook support OAuth2/OIDC implementation.

Thanks to everyone for your time.
May be, it would be useful to expect to update the WIKI with this new method.

**Comment by waltervl** [comment]
I can update the wiki if you can note down here what the steps were you have executed to use Basic Header.

**Comment by DewGew** [comment]
I have same issue with python script.
```
import requests
from requests.auth import HTTPBasicAuth

r = requests.get(
    'http://192.168.1.123:8080/json.htm?type=command&param=addlogmessage&message=Try to connect to domoticz',
    auth=HTTPBasicAuth('user', 'password'), timeout=(2, 5))
    
print(r.status_code)
```
I get response 401

I have enabled Allow Basic Authentication over plain HTTP and using this in a local network

**Comment by kiddigital** [comment]
@DewGew , please run Domoticz with earlier mentioned debug flags to see what Domoticz receives from your request.

(`-loglevel all -debuglevel auth,webserver,received`)

Any proxies in between maybe?

**Comment by DewGew** [comment]
> @DewGew , please run Domoticz with earlier mentioned debug flags to see what Domoticz receives from your request.
> 
> (`-loglevel all -debuglevel auth,webserver,received`)
> 
> Any proxies in between maybe?

No proxies, 
It works if I add to trusted network, but need it to work for a specific user

**Comment by kiddigital** [comment]
@DewGew , what does the Debuglog tell you?

Some API commands can only be executed with Admin rights so could be rejected for that reason (within the Trusted network, automatically the first user with Admin rights is selected and used to perform actions).

**Comment by DewGew** [comment]
> @DewGew , what does the Debuglog tell you?
> 
> Some API commands can only be executed with Admin rights so could be rejected for that reason (within the Trusted network, automatically the first user with Admin rights is selected and used to perform actions).

Got it working like my script above, Just needed to restart domoticz after changing settings. thank you for your help

**Comment by gizmocuz** [comment]
@DewGew , instead of basic auth over HTTP you can change your script to use https instead of http
