### ISSUE TITLE
Access to Domoticz

### ISSUE THREAD

**Issue by jotakar** [domoticz/domoticz#5502]
Hello,
I've observed an strange behaviour of Domoticz access control. 
I set the Auth to Basic (I need it so to send JSON commands from remote).
Then when I try to access  Domoticz, it appears the window asking for user access. It's normal, but if you cancel twice (pushing cancel button) then the login page with the form control in middle  appears, like if the auth were set to Login instead of Basic-Auth.
It happens in local and in remote access.
Why this behaviour?

**Comment by kiddigital** [comment]
In 'local network' (now called Trusted network in latest Beta's) when trying to access the UI, no user/pass is requested.

When not in the local network (as configured), a user/pass is needed. Either using Basic Authentication (handled by the Browser) or using the Login screen (handled by Domoticz) depending on the setting.

After a few failed Basic auth attempts, the Login is the fall back.

UI authentication via Basic Auth might get removed in the future. Basic Auth for accessing the API will remain (and is already improved in the Beta's).

**Comment by jotakar** [comment]
I'll wait until Beta became stable. By now Auth-Basic is the only way I can send JSON commands from remote or IFTTT . (stable version 2022.2).
