### ISSUE TITLE
Missing weather and utility tabs

### ISSUE THREAD

**Issue by harolds** [domoticz/domoticz#5503]
I know that you can enable/disable the buttons/tabs that are shown on the top right per user. But how do I enable/show them again when domoticz is accessed from the local network. So then there is no login needed and thus no user specified.

Is there some config to enable the weather and utility tabs again? They where visuable before they where moved to the user settings

![2022-12-28 21_56_32-Domoticz – Mozilla Firefox](https://user-images.githubusercontent.com/4362052/209871133-670d716a-b0c9-48d8-b4b1-b8e606112711.png)

**Comment by waltervl** [comment]
I believe this is connected to the first admin user.

**Comment by kiddigital** [comment]
> I believe this is connected to the first admin user.

Correct. Within the Trusted network, automatically the first Admin User gets logged in.

You can see who is logged in (Active User) in the 'About' screen

**Comment by harolds** [comment]
Thanks that fixed it. But its a bit difficult because I deleted (as instructed) the default 'admin' user. So the next one in line was not the correct one. I had to delete and recreate some accounts to get it fixed. There is no way to reorder the users.

**Comment by kiddigital** [comment]
@harolds , there is no need to _delete_ the standard admin user (where does it say that?) BUT you are **strongly** advised to change it default password.

**Comment by gizmocuz** [comment]
Another reason to have only one admin user perhaps?

**Comment by harolds** [comment]
Thanks for the advices and indeed I did not have to delete the default admin account.
