### ISSUE TITLE
Build version in Github

### ISSUE THREAD

**Issue by MadPatrick** [domoticz/domoticz#5506]
Hi 
Not really an issue, but more of a question

Where can i find the build version in Github.
I see the build numbers on the Domoticz website https://www.domoticz.com/downloads/
But what is the build version if i download from source from Github and build my own version ?

![image](https://user-images.githubusercontent.com/81873830/209992672-a55cff43-fb10-44e1-a378-faf2b0ee278d.png)

Thanks

**Comment by kiddigital** [comment]
First read here

https://www.domoticz.com/wiki/Domoticz_versions_-_Commits

Second, on GitHub the build actions create 'Artifacts' for Linux. You can download them and run on a Linux machine/container.
