### ISSUE TITLE
Domoticz Version: 2022.2 (build 14895) does not show any Temperature devices anymore

### ISSUE THREAD

**Issue by Rouzax** [domoticz/domoticz#5507]
Just recently upgraded to latest dev version of Domoticz, now running Version: 2022.2 (build 14895) Build Hash: fbac95755 
Not sure what the version was I came from 😄 

Since this version, my `Temperature` Menu shows `No Temperature sensors found or added in the system...`
![image](https://user-images.githubusercontent.com/4103090/210076356-494d2e92-6130-44ec-8666-5da68e03a4f5.png)

They do still show up in my Floorplans
![image](https://user-images.githubusercontent.com/4103090/210076389-74d1f864-3ea9-4193-a0b5-fdbbc70a90ee.png)

**Comment by waltervl** [comment]
I still see my temperature devices in 14895 so it is not a general issue. Browser cache deleted properly?

**Comment by Rouzax** [comment]
So have cleared my cache multiple times but it keeps not showing the temperature devices on my phone
If I open the site through an incognito tab they load.
Not sure what is happening here.
Do see something else weird, if I'm not logged on and refresh the login page, I get a no favorites added page without logging in on my Android.
![Screenshot_20221230_175623_Firefox Nightly](https://user-images.githubusercontent.com/4103090/210094705-3f6f773b-e2a3-4b8a-a42a-7e32c36907e0.jpg)

On my PC I see that page flashing past, but it will revert to the login page
![2022 12 30-17 59 29_Domoticz_—_Mozilla_Firefox_Aco5nnPhJV](https://user-images.githubusercontent.com/4103090/210094953-5f2eebc0-ba15-4cb7-a6c6-d62fc7891fd0.gif)

**Comment by gizmocuz** [comment]
You are displaying the dashboard and not the temperature tab
Do you have any errors in the browser's developers console?

**Comment by Rouzax** [comment]
Clearing my cache on PC it seems to have solved the Temperature device issue.
On my mobile I needed to fully wipe the Firefox cache for the entire app to get it working again.

**Comment by gizmocuz** [comment]
Okey so it was a cache issue and it is solved?

**Comment by Rouzax** [comment]
Yes, I'm embarrassed to say 😨

**Comment by Rouzax** [comment]
But it is weird that this was not enough for Android
![image](https://user-images.githubusercontent.com/4103090/210095675-1b1f9fe2-681b-4b9e-8536-e08751183288.png)
