### ISSUE TITLE
Netatmo Homecoach only fetches values once

### ISSUE THREAD

**Issue by tuinstoelen** [domoticz/domoticz#5508]
Hi all,

I have the same issue as other people have mentioned in this thread on the forum: https://www.domoticz.com/forum/viewtopic.php?t=38968

The Netatmo will fetch values for the Homecoach device only once, and then stop. A restart of Domoticz will again fetch a single set of values.

The issue seems to have been introduced between versions 2022.1 and 2022.2. If I have to guess, it was introduced in PR #5174, in this commit: 1134effeceb1c2781ff655541d437220c2249f82. 

My tracing/debugging shows that In CNetatmo::GetMeterDetails(), on the first run, on line 796 (in head), the homecoach data is fetched. The m_weatherType is then correctly set to NETYPE_HOMECOACH; But this value is subsequently never used. Seems like some kind of oversight.

This patch fixes the issue for me: Change netatmo.cpp line 766 from:
```
	httpUrl = MakeRequestURL(NETYPE_WEATHER_STATION);
```
To:
```
        httpUrl = MakeRequestURL(m_weatherType);
```

Could someone more familiar with the Netatmo code perhaps have a look at what is going wrong? I'm worried that any patch I make might break some of the other Netatmo device types, which I do not have and therefore cannot test. 

Best regs,

Tuinstoelen

**Comment by Cyberjamming** [comment]
Same problem over here after 2022.2

Can u help me with your patch solution, tuinstoelen? [Zou fijn zijn. Heb de meter net drie dagen]

**Comment by tuinstoelen** [comment]
Hi Cyberjamming, 

You'll need to rebuild from source. Instructions for building are here:
https://www.domoticz.com/wiki/Build_Domoticz_from_source

Once you are able to build your own version of Domoticz, you can adjust hardware/Netatmo.cpp line 766 as mentioned above. To test, run ./domoticz from the dev-domoticz folder and add a Netatmo device with your Netatmo credentials. Or copy your production database file, plugins & scripts folders over to dev-domoticz. Once you are sure the fix works for you, you can then use the version you build for production / as a daemon.

**Comment by gizmocuz** [comment]
@tuinstoelen , thank you for this patch. It looks valid as m_weatherType is by default set to NETYPE_WEATHER_STATION.
Only when the data could not be parsed, it is checked if it is a NETYPE_HOMECOACH, and if it is, m_weatherType is set to NETYPE_HOMECOACH

I applied your patch in beta 14901
