### ISSUE TITLE
KILO.Push for notifications

### ISSUE THREAD

**Issue by artlevitan** [domoticz/domoticz#5509]
Hi!
When the [KILO.Push](https://github.com/artlevitan/KILO.Push-API) notification service will be supported?

**Comment by waltervl** [comment]
You should be able to use that with the **Custom HTTP/Action** Notification type. Fill in the correct fields and you should be ready to go.
See Wiki https://www.domoticz.com/wiki/Notifications

**Comment by artlevitan** [comment]
Yes, I do, I would like a separate block.

**Comment by waltervl** [comment]
Then you could program that yourself based on other notification method and make a pull request. This is open source so if you want an enhancement it is better to add it yourself if possible. Else you have to wait on somebody with programming knowledge that can do this. But that could take a while as it it is easy to use it with the custom http notification.
