### ISSUE TITLE
new admin user causes issues after upgrade from 2022.2 to 14895

### ISSUE THREAD

**Issue by akamming** [domoticz/domoticz#5513]
Hi,

running on a pi4b bullseye (fully up-2-date). Found an issue after upgrade to latest beta:

after upgrade, I could no longer see the switches tab.  Somehow the floorplan tab was enabled (which i normally have disabled).

Found the cause of the issue. During the upgrade apparently  a 2nd admin users was added with floorplantab enabled and switches tab disabled on user level.  I could still login with my own password. After deleting the new user all works fine again..

For details see the post I created on the forum:
[https://www.domoticz.com/forum/viewtopic.php?p=296935#p296935](https://www.domoticz.com/forum/viewtopic.php?p=296935#p296935)

**Comment by gizmocuz** [comment]
@kiddigital , maybe there is no check if there was already a admin user and a second admin user is created?

**Comment by kiddigital** [comment]
I will have a look. I thought that there was a check but I will check 😉

**Comment by kiddigital** [comment]
@gizmocuz , just did double check. Only if there is no single user with Admin privileges (regardless the username), the 'admin' user is created and only during the DB upgrade of 157 to 158.

And a new install creates an 'admin' user, but that is mutually exclusive on the above.

**Comment by akamming** [comment]
apparently that check fails.

i no longer have the db in which the issue occured.  But I still do have the output from "select * from users;" on that db (for security reasons i replaced the other usernames and the passwords with <BASE64USER> and <BASE64PW> 

```
2|1|<BASE64USER>|<BASE64PW>|2|126|0
3|1|YWRtaW4=|<BASE64PW>|2|126|0
4|1|<BASE64USER>|<BASE64PW>|1|63|1
5|1|<BASE64USER>|<BASE64PW>|1|127|1
6|1|<BASE64USER>|<BASE64PW>|1|63|1
8|1|<BASE64USER>|<BASE64PW>|1|31|1
9|1|<BASE64USER>|<BASE64PW>|1|0|1
10|1|<BASE64USER>|<BASE64PW>|1|0|1
11|1|YWRtaW4=|<BASE64PW>|2|31|0

```
As you can see record 11 eleven was added after upgrade from 2022.2 to build 14895, containing an extra admin user. But the admin user was already there (record 3)

i solved the issue by manually 
- deleting record 3 (causing me no longer to be able to login as admin)  
- start domoticz with nowwwpwd
- reset the admin password
- restarting domoticz

**Comment by kiddigital** [comment]
@akamming , I did some additional checking and testing. Figured out that there could be a scenario that would cause the above situation.

When coming from an older version that used the old (now removed) 'Website protection' setting and the 'WebUserName' would be the same as a the name of a User in the Users table, the migration of this Website protection variables (when coming from a DB < 157) created a new user based on this information and that would lead to having 2 Users with the same UserName.

Also found some alternative edge case that could create potential weird situations so extra checking has been added for these as well. See PR #5519.

Thanks for the detailed info and reporting this issue. Will save some issues for certain users when upgrading to the next (upcoming) Stable release.

**Comment by akamming** [comment]
tx a lot.!

Based on your explanation i just thought up another scenario. Probably far fetched, but just checking anyway...

i assume the 2022.2 to 14895 upgrade caused the 2nd admin user. because i only noticed it after this upgrade because i was troubleshooting the issue i had. and the issue was fixed once i removed the 2nd admin user.

But alternatively it might  als also be the case the 2nd admin was already there (e.g. in the scenario you describe), but i never noticed  and it only found out after 14895 because of some other behaviour in 14895 which causes issues when you have 2nd admin user...

unfortunately i don't have the db backups anymore to check...
