### ISSUE TITLE
Tasmota energy meters, no decimals

### ISSUE THREAD

**Issue by HB787** [domoticz/domoticz#5514]
Hi Team,

The values, that are presented by Tasmota devices through MQTT don't show any decimals.
In the Tasmota Device Manager I see that the MQTT transmitted values have decimals, so they are rounded or changed somewhere within Domoticz. Within the virtual device there is no setting for this either, I have the right setting in "Settings" (decimals).

Raspberry 4
Domoticz 2022.2 beta build: 14901
Compile Date: 2022-12-31 07:22:16
Python Version: 3.9.2 
AEOTEC Z-Stick Gen5
RFXCom
Mosquito on Synology

**Comment by gizmocuz** [comment]
@HB787 , could you post the right settings from your settings page? 
I have many kWh MQTT sensors (and Watt sensors) and the default setting should not be touched (energy divider should be 1000)
Best to check what data you receive on the MQTT side

**Comment by HB787** [comment]
hi @gizmocuz, first of all the best wishes for 2023
Attached are the screenshots from "Domoticz / settings", "tasmota webUI with Value', TDM manager with the value coming from MQTT (mosquito) and in the end how it is presented in Domotics, it says 2 watt. 
![tasmota_device_manager](https://user-images.githubusercontent.com/58355498/210179457-c0ced805-4b9b-4092-a3ff-a0e2e600c168.jpg)
![domoticz_value](https://user-images.githubusercontent.com/58355498/210179458-60abed4d-e917-4775-9114-3c9eb83bab4d.jpg)
![tasmota_value](https://user-images.githubusercontent.com/58355498/210179459-d812b2fd-a19c-47ef-bbed-10d8383b5149.jpg)
![domoticz-settings](https://user-images.githubusercontent.com/58355498/210179460-0e2a15a8-571e-4db1-afc1-564c4d8a17bc.jpg)
Thanks in advance
Harry

**Comment by HB787** [comment]
The value is somehow changed with Domoticz

**Comment by gizmocuz** [comment]
Is it possible you can use MQTT Explorer and copy paste the config topic+payload and the data topic + payload?
With this we can know for sure what the issue is. Maybe Tasmotta reports with decimals

**Comment by HB787** [comment]
Hi @gizmocuz 

I made a screenshot with MQTT explorer and you see the payload form the device that is presenting 3 watt in domoticz but actually is 3.77 watt within Mosquito
![mqtt_explorer](https://user-images.githubusercontent.com/58355498/210224383-773874e8-0964-4f74-9964-243d7367da35.jpg)

**Comment by HB787** [comment]
This Sonoff device has two channels.

**Comment by gizmocuz** [comment]
Could you post here (with text) the config topic + payload and the device data topic+payload.
With this I can try to replicate it

Here my kWh sensor and Watt sensor are displaying 1 decimal

**Comment by HB787** [comment]
is this what you mean as payload, power 3.73
{"sn":{"Time":"2023-01-02T03:51:18","Switch1":"ON","Switch2":"ON","ENERGY":{"TotalStartTime":"2022-08-27T10:07:35","Total":1.8286,"Yesterday":0.0347,"Today":0.0140,"Power":[3.73,0.00],"ApparentPower":[3799.98,0.00],"ReactivePower":[3799.00,0.00],"Factor":[0.00,0.00],"Voltage":237,"Current":[16.049,0.000],"BL09XX":{"Temperature":30.3}},"ESP32":{"Temperature":50.6,"HallEffect":28},"TempUnit":"C"},"ver":1}

**Comment by gizmocuz** [comment]
Almost this is the payload of the 'sensors' topic I suppose
Could you also provide the payload of the config topic?

Bdw, when you click on the topic (where you can see the payload), on the top right is a 'copy' option to copy the topics, could you post them here as well, saves me some typing

Just to be sure, you are using MQTT Auto Discovery? Or do you use a plugin?

**Comment by gizmocuz** [comment]
https://tasmota.github.io/docs/Home-Assistant/

**Comment by HB787** [comment]
Auto discovery never worked here, I just put the virtual device ID's from Domoticz in the Tasmota WebUI.
Here you go:
{"ip":"192.168.1.62","dn":"Tasmota Sonoff Dual R3 V2 Tuinpaal","fn":["Tuinpaal Camera","Ledbeamers",null,null,null,null,null,null],"hn":"Tasmota-Dual-R3-V2-Tuinpaal","mac":"C4DD57DB68C8","md":"Sonoff Dual R3 v2","ty":0,"if":0,"ofln":"Offline","onln":"Online","state":["OFF","ON","TOGGLE","HOLD"],"sw":"12.3.1.2","t":"tasmota_tuinpaal","ft":"%prefix%/%topic%/","tp":["cmnd","stat","tele"],"rl":[1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"swc":[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],"swn":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"btn":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"so":{"4":0,"11":0,"13":0,"17":0,"20":0,"30":0,"68":0,"73":0,"82":0,"114":0,"117":0},"lk":0,"lt_st":0,"sho":[0,0,0,0],"sht":[[0,0,0],[0,0,0],[0,0,0],[0,0,0]],"ver":1}

**Comment by gizmocuz** [comment]
Okey then this is a issue in Tasmota or your device. Maybe you can change a setting in your device?
It is not something I can help with i'm afraid.

**Comment by HB787** [comment]
Of course the MQTT Client plugin is used see attached
![domoticz-mqtt_client](https://user-images.githubusercontent.com/58355498/210244960-bc24d53d-7ca8-425e-a68e-b0532e8bbe32.jpg)

**Comment by gizmocuz** [comment]
Yes, that is something else then Auto Discovery
So your tasmotta device is updating domoticz with values, and those values are do not contain decimals it seems

**Comment by HB787** [comment]
Yes but in MQTT the value is with decimals, so it is send in the right format.
The only thing that is in between is the MQTT plugin as shown.

**Comment by gizmocuz** [comment]
The screenshot above is from MQTT-Tasmota. Tasmota is probably calling our JSON api to update values and this does not contain decimals

You can also see at the bottom of your screenshot that the output from domoticz (out) does not contain any decimals

**Comment by kofec** [comment]
So maybe you can experiment a little on Tasmota side. Some example of my rules .e.g:
`
Rule
 ON tele-SR04#distance DO publish domoticz/in {"idx":1,"svalue":"%value%"} ENDON
 ON tele-VL53L0X#distance DO publish domoticz/in {"idx":2,"svalue":"%value%"} ENDON

OLD:
 ON tele-VL53L0X#distance DO publish domoticz/in {"idx":2,"svalue":"%value%;1"} ENDON

Rule1 
ON Tele-AS3935#Distance DO publish domoticz/in {"idx":x,"svalue":"%value%"} ENDON 
ON Tele-AS3935#Energy DO publish domoticz/in {"idx":x,"svalue":"%value%"} ENDON

  ON var1#state==0 DO publish domoticz/in {"idx":6,"nvalue":0,"svalue":"0"} ENDON
  ON var1#state==1 DO publish domoticz/in {"idx":6,"nvalue":1,"svalue":"100"} ENDON

`

**Comment by HB787** [comment]
Will try something, the screenshot shows the standard Domoticz MQTT client plugin, I gave it the name starting with Tasmota

**Comment by waltervl** [comment]
If I use the Domoticz json API on an Electricity instant and counter device https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Electricity_.28instant_and_counter.29
eg `/json.htm?type=command&param=udevice&idx=123&nvalue=0&svalue=10.9;3000` I get a valid 10.9 Watt noted in Domoticz
Just for the record: Value 10,9 (so with a comma instead of dot delimeter) is NOT working. 
you could try to publish a MQTT payload to domoticz/in like {"command":"udevice", "idx":123, "svalue":"10.9;3000"} to test.

**Comment by HB787** [comment]
will do some testing, thanks @waltervl

**Comment by waltervl** [comment]
Are you using  a Tasmota Python plugin to communicate with Domoticz? Because then there could be something wrong in Plugin (or perhaps Plugin framework). But if you use a Plugin you have to check with the plugin author.

**Comment by HB787** [comment]
I am using the standard MQTT Client Gateway plugin from Domoticz, it does not have a special relation with Tasmota.
The MQTT Auto discovery plugin is also activated but never picked up any new MQTT device.
I put the Virtual ID's in the Tasmota WebUI to communicate with Domoticz.

**Comment by waltervl** [comment]
So what are the messages in MQTT domoticz/in coming from the tasmota device?
I see in your screenshot in https://github.com/domoticz/domoticz/issues/5514#issuecomment-1368858653 that Tasmota is showing 3.73 and in domoticz/in it is showing svalue=**3**;88382.8 so saying 3 (and not 3.73)!
So in Tasmota (rules?) something is going wrong as it sends values as integers and not decimals.

**Comment by HB787** [comment]
Yes that could be the issue, I did not use a rule to send the value. In MQTT it is 3.73. So from Tasmota to MQTT it is correct.
here are the screenshots that explain how it is configured. First of all Tasmota is connected with Mosquito, and the devices ID are given in the Tasmota / Domoticz settings see screenshots. So we see 3.7 watt in the Tasmota and in the end 3 watt in Domoticz. 

This is a standard setup, I did not do anything special, the MQTT client is the standard one within Domoticz.
Within MQTT the data is also correct with decimals.

![tasmota_webui_value](https://user-images.githubusercontent.com/58355498/210260405-54a75ddd-2373-4f63-8ceb-680b6bc8a314.jpg)
![tasmota-domoticz-settings](https://user-images.githubusercontent.com/58355498/210260426-83b4280e-0e03-4d91-8eba-b92e348c2c35.jpg)
![domoticz-devices](https://user-images.githubusercontent.com/58355498/210260443-c24d99c6-141d-4a33-91f1-e4139208f5ff.jpg)

**Comment by gizmocuz** [comment]
`So from Tasmota to MQTT it is correct`
Well as I mentioned above, there is Tasmota_MQTT and Domoticz_MQTT
Tasmota_MQTT is using the 'tasmota' topic, and Domoticz is using domoticz/in/out
The data send to the Domoticz 'in' seems not to include any decimals, and that is why you see 3, instead of 3.456

If the Tasmota device publishes data to **domoticz/in** it needs to add the decimals

**Comment by HB787** [comment]
I can't set anything, the plugin is the standard MQTT client, MQTT Auto Discovery does not work. 
So I am out of options it seems. I saw screenshots of an MQTT client without domitcz/in etc. 
But I dont' have that in my Domoticz, will look for another plugin.

**Comment by gizmocuz** [comment]
I think you have to ask this on the question Tasmota forum

**Comment by waltervl** [comment]
Check Tasmota documentation page https://tasmota.github.io/docs/Domoticz/#tasmota-configuration
Edit: ignore following: You should use this Tasmota Discovery plugin https://github.com/emontnemery/domoticz_mqtt_discovery which is not the same as Domoticz MQTT Auto Discovery hardware.

Setoption 19 (to enable HA Auto Discover protocol) is disabled in latest firmwares of Tasmota (https://tasmota.github.io/docs/Commands/). So only normal domoticz/in and out is usable.

**Comment by HB787** [comment]
@waltervl thanks I did install that one, until now all the auto discovery plugins did not work.

**Comment by waltervl** [comment]
I am sorry, see the edited comment, that plugin is (or should be) the same as Domoticz Autodiscover, but Tasmota decided to remove HA Autodiscover protocol on latest firmwares (Setoption19). You have to check on Tasmota forums how Tasmota sends the correct values to Domoticz/in and out.

**Comment by HB787** [comment]
It is a pitty the standard MQTT client does not add the decimals. I used a german Auto Discovery plugin that worked, but overflooded my domoticz environment. Also devices with more channels don't work. Tasmota devices are a very good replacement for Z-Wave plugs and relais, they are very reliable and have programming capabilities. I want to use z-wave only for PIR's.

**Comment by HB787** [comment]
I will go into the Tasmota forums

**Comment by kofec** [comment]
@HB787 I check it today. And you have incorrect configuration or you want to test something different than power.
Base on your screenshot, your "Power factor" is 0 or close to 0. In my case is near to 1.
I think that about 5W is a measurement error for Sonoff dual R3
Also on screenshot from discussion about this hardware we can see Power factor is 1 - https://github.com/arendst/Tasmota/discussions/10793
https://templates.blakadder.com/sonoff_DUALR3_v2.html

**Comment by kofec** [comment]
Maybe you should reset your configuration to factory default and upgrade to latest version of Tasmota - there were some fixes for energy

**Comment by HB787** [comment]
Hi @kofec
Know about the factor issue and calibration will help, but this is not the problem.
I have 10 devices with the same issue, (Sonoff, Shelly, Athom) within Domoticz there are no decimals and the values are translated into integers so 3.77 becomes 3 etc.

**Comment by kofec** [comment]
but only for power - right ? 
Can you change debug level for web to "debug" and in console you will see e.g.:
16:00:32.432 MQT: domoticz/in = {"idx":27,"nvalue":0,"svalue":"184;184.6","Battery":100,"RSSI":6}

16:00:32.437 MQT: tele/tasmota_C0F301/SENSOR = {"Time":"2023-01-03T16:00:32","ENERGY":{"TotalStartTime":"2023-01-03T13:49:21","Total":0.185,"Yesterday":0.000,"Today":0.185,"Period":1.90,"Power":184.04,"ApparentPower":184.04,"ReactivePower":0.00,"Factor":1.00,"Voltage":238,"Current":0.772}}

It looks like tasmota is reporting integers

**Comment by kofec** [comment]
OK found solution for you:
base on: https://tasmota.github.io/docs/Rules/#use-of-variables-and-tele-in-domoticz
```
Rule1
  ON tele-energy#power DO var1 %value% ENDON
  ON tele-energy#today DO publish domoticz/in {"idx":27,"svalue":"%var1%;%value%"} ENDON

Rule1 ON
```

and remember to disable reporting this device in "domoticz" section in Tasmota

```
16:11:36.643 CMD: Grp 0, Cmd 'VAR', Idx 1, Len 6, Pld 182, Data '182.40'
16:11:36.650 MQT: stat/tasmota_C0F301/RESULT = {"Var1":"182.40"}
16:11:36.666 RUL: TELE-ENERGY#TODAY performs "publish domoticz/in {"idx":27,"svalue":"182.40;0.226"}"
16:11:36.669 SRC: Rule
16:11:36.671 CMD: Grp 0, Cmd 'PUBLISH', Idx 1, Len 46, Pld -99, Data 'domoticz/in {"idx":27,"svalue":"182.40;0.226"}'
16:11:36.678 MQT: domoticz/in = {"idx":27,"svalue":"182.40;0.226"}
```
![image](https://user-images.githubusercontent.com/18610805/210385489-c04512f6-5389-418a-b526-2f65021a59d1.png)

**Comment by HB787** [comment]
@kofec thank you that looks good I will create that rule!!

**Comment by waltervl** [comment]
OK, good to see! @HB787 please close this issue when it works.

PS. Please discuss these kind of issues the next time on the forum first. If the result is a domoticz bug or enhancement then a github issue could be made.

**Comment by HB787** [comment]
@waltervl  Thanks the solution works, just need to figure out how to get the data from two channel energy meters like the DUAL R3. I did publish this issue in the forum, but nothing came back.
