### ISSUE TITLE
offline error very frequently with a subdomain 

### ISSUE THREAD

**Issue by keesberg** [domoticz/domoticz#5515]
I get the offline error very frequently.
Communication with my Domoticz/Raspberry goes with a subdomain (with SSL) via my Synology NAS.
Here, reverse proxy redirects to the raspberry. This has always worked well with the previous versions.
I have done the redirection with HTTPS (without SSL) and with HTTP. Both regularly give the off-line error.
How can this be solved?

Linux raspberrypy 5.10.103-v7l+ #1529
Domoticz:
Version: 2022.2
Build Hash: eea9db734
Compile Date: 2022-11-05

**Comment by waltervl** [comment]
Did you add the reverse proxy IP in the local networks see Note in  https://www.domoticz.com/wiki/WebServer_Proxy

> For the "X-Forwarded-For" and "X-Real-IP" to be recognized in Domoticz, make sure you enter the IP address of your proxy server (which could be on the same machine like 127.0.0.1) in the main Domoticz setup page underneath "Local Networks" or when you run a old version (<14299) in "RemoteProxyIPs"

**Comment by keesberg** [comment]
Ik heb niet de reverse proxy IP volgens de opmerking in https://www.domoticz.com/wiki/WebServer_Proxy toegevoegd, maar de standaard reverse proxy van de Synology NAS gebruikt. Zie afbeelding.
Het Secundaire (interne) IP adres heb ik ingevuld in de setup pagina onder "Local Networks"
Als ik verbinding maak met mijn smartfone  zie ik in de logfile Incoming connection from: 84.31.xxx.xxx dit is mijn primaire (extern) IP adres.
![Proxy](https://user-images.githubusercontent.com/121854475/210516436-0365f426-98f6-4f58-891c-76d040e0c0bc.jpg)

**Comment by keesberg** [comment]
did not add the reverse proxy IP according to the comment in https://www.domoticz.com/wiki/WebServer_Proxy, but used the default reverse proxy of the Synology NAS. See image.
I entered the Secondary (internal) IP address in the setup page under "Local Networks"
When I connect to my smartphone I see in the log file Incoming connection from: 84.31.xxx.xxx this is my primary (external) IP address.
![Proxy](https://user-images.githubusercontent.com/121854475/210516924-e34b1e9d-4a62-4b64-baf0-b35d7cba5663.jpg)

**Comment by waltervl** [comment]
@kiddigital please advise...

**Comment by kiddigital** [comment]
@keesberg , as you use the build-in Proxy functionality of your Synology NAS, the (Internal) IP address of the NAS should be added to the Trusted Network (Local network in stable).

A quick scan on the Internet seems to reveal that Synology internally used NGiNX under the hood. Domoticz relies on the availability of Proxy Headers to determine valid access. Not sure if/what headers the Synology proxy sends to Domoticz.

You could run Domoticz with debug parameters (at least 'webserver' and 'received') to see in the log what is received by Domoticz.

Maybe somewhere in the Synology (advanced) settings you can specify/select Proxy headers?

**Comment by waltervl** [comment]
> Maybe somewhere in the Synology (advanced) settings you can specify/select Proxy headers?

I just added a Synology screenshot with Header settings to the wiki https://www.domoticz.com/wiki/WebServer_Proxy
Origin is forum topic https://www.domoticz.com/forum/viewtopic.php?p=291722&hilit=synology+proxy#p291722

**Comment by kiddigital** [comment]
@keesberg , btw.. as this is most likely not a bug in Domoticz but a configuration issue (and yes, maybe Domoticz behavior has changed between version. Did you check the changelog before upgrading?), it would be best to ask this question on the forum first.

(As the answer might already be there 😁. Thx @waltervl)

**Comment by keesberg** [comment]
Thanks for the suggested solutions. I'm going to adjust and test this coming weekend. I had gone through the releasenotes and nothing associated with this problem.

**Comment by keesberg** [comment]
I have set up the reverse proxy as in the added screenshot in the wiki.
This solved the problem.
Thanks for the solution.
