### ISSUE TITLE
Error: SolarEdge: Error getting http data (Sites)!

### ISSUE THREAD

**Issue by Scheffie** [domoticz/domoticz#5516]
L.S.

From november '22 on my Solaredge via Web API stopped working with the fault:

Error: SolarEdge: Error getting http data (Sites)!

I've checked my API_Key and this was still correct. The version of domoticz used is: 2022.2 (later switched to build  14905 for testing) (on a raspberry pi)

In hardware/SolarEdgeAPI.cpp:
	sURL << "https://monitoringapi.solaredge.com/sites/list?size=1&api_key=" << m_APIKey << "&format=application/json";

When used in a browser, this returns the site list in XML format. NOT in JSON format as requested by the &format=application/json

When using the url formatted like:
	sURL << "https://monitoringapi.solaredge.com/sites/list.json?size=1&api_key=" << m_APIKey << ;

The output is in json fromat.

Could this be changed (for all urls)? or am I the only one having this problem?

Greetings,
Bart Scheffers

**Comment by gizmocuz** [comment]
According to the documentation it is still /list
I can't find a list.json

https://knowledge-center.solaredge.com/sites/kc/files/se_monitoring_api.pdf

I would expect that we need to send 'application/json' in a header

```
	std::vector<std::string> ExtraHeaders;
	ExtraHeaders.push_back("Accept: application/json");

	if (!HTTPClient::GET(sURL.str(), ExtraHeaders, sResult))

```

is this something you could test?

**Comment by Scheffie** [comment]
In the api guide is states:• URL format Parameter – ...&format=application/json

• Path extension – the name of the API will be followed by the requested format name ../details.json&...

• HTTP header – based on ‘Accept’ header e.g. Accept application/json was referring to the second option.

If tried that one and it worked.

I have to see how I could test the third option.

**Comment by gizmocuz** [comment]
Yep, that is what I meant and stated in the API

HTTP header – based on ‘Accept’ header e.g. Accept application/json

**Comment by gizmocuz** [comment]
Could you please try beta 14909 to see if this solves the issue (forcing .json and a header)

**Comment by Scheffie** [comment]
I tried the 14909 version but still the error appeared

**Comment by gizmocuz** [comment]
Hmm hope you can debug the issue

**Comment by Scheffie** [comment]
Unfortunately I'm not a c-programmer. Could you please assist in how I
could debug this?

I tried sending commands to the api via wget from the raspberry pi command
line. there the responses are as expected.

**Comment by gizmocuz** [comment]
Best to not reply by email but entering a reply manually else you will copy some email headers

I just verified, and it is still working with my changes, so it might be that you entered the API key wrong?

**Comment by Scheffie** [comment]
Unfortunately It still doesn't work on my installation. I changed the api key in the solaredge admin environment and in domoticz to be shure they are equal, but without positive results.

Are there some prerequisits that should be met on my Pi installation before this plugin works?

I'm using the key from within this field:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/122016053/211197536-f36ea677-56d2-4170-97dc-a8985d5db67b.png">

**Comment by gizmocuz** [comment]
I don't have a solaredge and borrowing the API key from a friend. With this I have no issues at all.

**Comment by Scheffie** [comment]
I'll try reinstalling my Domoticz installation from source, maybe something is wrong with the installation.

**Comment by gizmocuz** [comment]
@Scheffie , don't think that will change, but maybe easier to install the windows version and test?

**Comment by Scheffie** [comment]
Another day another update..

I've tried setting up the solaredge api on another domoticz instance on another pi that uses stable 2022.2 version without results.

Then I installed the stable 2022.2 on windows. same fault
Then I upgraded  the windows install to beta build 14941 and it started working.

Hope this makes sense :-S

**Comment by gizmocuz** [comment]
Nope, but please use the beta version as here are the changes in made
So on your other system, make sure you are using the (latest) beta version

**Comment by gizmocuz** [comment]
Hope it's working now on your end. Have no other users reporting this error, and also verified the working of one account
Closing issue, If you still have a problem, feel free to re-open this

**Comment by Scheffie** [comment]
Hello Gizmocuz, 
Sorry for the delay.. But I found the issue..
Ive been testing with the WGET command and it seemed to be working. Something that came to my mind was that it took a relative long time to complete while my Edge browser was much quicker. It seemed that the WGET was having issues resolving the hostname. DNS was configured correctly.. 

One thing I was not aware of is that older PI OS versions have IPV6 disabled by default and the latest PI OS versions have it default enabled. This was causing the DNS in the PI to preferably using IPV6 DNS first (which is not available on my network).

This delay was enough to cause a timeout in the script. And so it returned the error: "Error getting http data (Sites)!"

Now I have the IPV6 properly disabled on the PI and all works great again. 

Maybe it is possible to create a timeout error or something so in future the error of getting http data is more clear?

Thank you for your support anyway!
Bart

**Comment by gizmocuz** [comment]
Thanks for the feedback! And good it's working again!
There should be a timeout, but default this is 30 seconds

**Comment by laszlovandenhoek** [comment]
I had a very similar issue, adding it here for search engines to pick it up: I have Pihole (a DNS-based ad blocker) installed on the same host as Domoticz. Both applications are running in a Docker container. With the default configuration, Domoticz can't access Pihole running in the other container, even if its port is exposed, causing the same error. In this case, it was acceptable to have Domoticz circumvent Pihole and use the Google DNS server directly, by adding this to the end of the Domoticz `docker-compose.yml`:

```yaml
    dns:
      - 8.8.8.8
```
