### ISSUE TITLE
Compress static web content at buildtime

### ISSUE THREAD

**Issue by gaudryc** [domoticz/domoticz#552]
I will submit a change request allowing :
- the web server to always deliver the gzipped version of a js or css file ;
- git to manage the textual version of js or css file, so we could have access to the history and we could make diff on these files.

It consists of modifying the building process to always compress the files with extensions .js, .json and .css, in the www/ folder.

The compression process consists in :
- compressing the file to .js.gz, .json.gz or .css.gz ;
- change the timestamp of the .gz file with the timestamp of the uncompressed file.

Under OSX and Linux, the compression is done with "gzip" and the timestamp change is done with "touch".
Under Windows, the compression is done with "7z.exe" and the timestamp change is done with "touch.exe" (coming from http://stevemiller.net/apps/).

With all these changes, we can do the whole compression at buildtime :
- by modifying the CMakeLists.txt for OSX and linux environment, or any build environment with CMake support.
- by adding a PostBuildEvent in the Visual Studio solution.
  In both cases :
- the compression is done only when the uncompressed file is newer than its compressed version, or when the compressed version does not exist.
- any new .css, .js or .json will be compressed before packaging.

When building using cmake, the "make clean" command only removes compressed files that have been generated using cmake.

What do you think about that ?

**Comment by gizmocuz** [comment]
Great idea!
This is only in 'release' mode ? I mean how can will still edit html/js for development ?

actually this is needed when making the archive/installer (for example in makebeta for the raspberry, or appveyor/trivis)

**Comment by gaudryc** [comment]
In Visual Studio you can define the postbuildevent only in release configuration if you want.
With CMake, there is no Debug/Release choice at this time, so the compression is done each time the "cmake+make" is done (if changes have been made).

At this time, with my solution, whatever the type of build, the uncompressed and compressed file are both present in the www/ before packaging domoticz (with tar or the package project using Visual Studio).

**Comment by gizmocuz** [comment]
Correct, would it be not better for windows that the NSIS build script is doing this ?

**Comment by gaudryc** [comment]
If you make it too late I think you won't be able to debug the "distribute gzip content" feature without packaging and installing first. If you compress at buildtime you can run domoticz from the source and test it directly.

**Comment by gizmocuz** [comment]
I think we only need to debug the making of the .gz files once ... but...
But also on compile time, i want to edit the json/html/css/images everything,
but when releasing/packaging, then it would be great that everything was compressed

**Comment by gaudryc** [comment]
So, for you, it would be done in makerelease, makebeta and DomoticzSetup.iss ?

**Comment by gizmocuz** [comment]
Yes, the compression is only needed in the user environment, not in the developer environment (sure not in development else we can not add changes to the web interface)
Currently the web server supports both, so when i need to work in domoticz.js i unpack the .gz file, and delete the .gz file, and when i am done, i create a new domoticz.js.gz file
... pretty complex indeed...
It would be create if we can deliver compressed output, and it is generated in:
- Windows->NSIS installer
- travis-ci
- CMake (make package)

**Comment by gaudryc** [comment]
But :
- to have compressed files in DEB package I need to make the compression in the make phase ;
- to have compressed files in setup.exe I need to make the compression before calling iscc.exe (because iscc.exe does not take  into account the PreCompile and PostCompile sections).

Besides making packaging scripts (bash and cmd) I do not see how to do things properly and simply. Because at this time there is no script to build and package .deb, no script to build and package .exe (or .zip containing the .exe). And if I do it I would have to clean the compressed files after packing to leave clean the www directory.

You talk about NSIS but there is no configuration file to use NSIS, isn't it ?

**Comment by gizmocuz** [comment]
NSIS correct, and yes, the appveyor does use this to build the windows exe (package)
CMakeList containst package definitions, but we should not use this at the moment i suppose on travis-ci
In travis you see where we make the archive ? Before there we should call a script that compresses everything, maybe making a temporarily www folder ?
or we should extend the command that creates the archive to add for example only www/app/_.gz and www/js/_.gz and so on ?

**Comment by gaudryc** [comment]
If nothing has to be done with "male package" yet, yes I just can add two
scripts (1 bash and one cmd) to compress or clean compress and then modify
both yml files, makerelease and makebeta files.

**Comment by gizmocuz** [comment]
That would be great...

**Comment by gaudryc** [comment]
I see that you didn't say nothing about "because iscc.exe does not take into account the PreCompile and PostCompile sections". Are you aware of that ?

**Comment by gaudryc** [comment]
I will make a pull request this evening to validate my changes on travis and appveyor.

**Comment by gaudryc** [comment]
Test is in progress in #555
