### ISSUE TITLE
Temperature sensors are gone in Temp tab after last beta update

### ISSUE THREAD

**Issue by HB787** [domoticz/domoticz#5520]
After update yesterday to Version: 2022.2 (build 14909) the tab with Temperature sensors is empty.
The devices are still in the system under devices and in the dashboard they are still there.
Rebooted but no change in situation.

Raspberry 4, Bullseye
Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]
Aeotec Z-wave stick ZW090
RFXCOM Transceiver

Screenshots:
Dasboard, Temp Tab

![domoticz_no_temp](https://user-images.githubusercontent.com/58355498/210954267-a1508361-6cf4-432b-b96f-6624c938d554.jpg)
![dashboard](https://user-images.githubusercontent.com/58355498/210954591-c5b21780-a4ae-4adb-87aa-4b03d32bde8b.jpg)

**Comment by waltervl** [comment]
I cannot check my test environment now but did you clear your browser cache? As this is normal practice after beta updates.
See also wiki https://www.domoticz.com/wiki/Browser_Cache for detailed instructions.
As a test you can also start a new private browser session as that does not cache javascript after closing the browser session.

**Comment by gizmocuz** [comment]
Sure he has as this is asked when he filed this issue 😁

I tested here and experience no issues

**Comment by HB787** [comment]
Should have known I needed to Refresh, works now of course forgive me!
