### ISSUE TITLE
Blinds not updated on MQTT autodiscovery message (Zigbee2mqtt)

### ISSUE THREAD

**Issue by ksacca** [domoticz/domoticz#5528]
Hello:

domoticz version: currently on 2022.2 (build 14928) which is the latest docker beta version, but issue also occurs on latest stable.
Hardware: RPI4 

Sorry to create such a long issue for this. I did my best to find the cause of the issue myself, but my coding knowledge is not sufficient to understand the workings of MQTT autodiscovery :). I will do my best to explain what happens and what might cause (even though I'm sure my logic is completely wrong).

I have already asked for help in topic https://www.domoticz.com/forum/viewtopic.php?t=39084 and now there's a similar discussion in https://www.domoticz.com/forum/viewtopic.php?f=82&t=39630. It was also briefly mentioned once in https://github.com/domoticz/domoticz/issues/5330.

Blinds that are created using (native) MQTT autodiscovery with zigbee2mqtt are not updating correctly in some cases. 
Sending commands (open, close or even level) to the blinds is working, but the widget in the user interface immediately reverts to the closed position (or open if you enable reverse position). If you activate the blinds using the buttons on the blinds or with a directly paired remote, the widget in domoticz stays closed and the last update timestamp doesn't change.

So to me it looks like the MQTT status messages are not being processed correctly at all.

I later found out that when I publish a configuration message for autodiscover without the "value_template" the widget updates correctly. In zigbee2mqtt, you can force the removal of the value template by adding "homeassistant: value_template: null" to your configuration.yaml file. The downside is that it is for the entire device, so if it exposes other entities (like battery, voltage, ...), they won't work as there's no value_template for them.

I now enabled debugging, and this is what I get in the logs for a normal blind without any workaround (so one that always shows as being closed in the widget)

topic: `zigbee2mqttAD/cover/0x0c4314fffe3fc90a/cover/config`
config payload: 
```
{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/Gordijn/set","device":{"identifiers":["zigbee2mqtt_0x0c4314fffe3fc90a"],"manufacturer":"IKEA","model":"FYRTUR roller blind (E1757)","name":"Gordijn","sw_version":"2.3.088"},"json_attributes_topic":"zigbee2mqtt/Gordijn","name":"Gordijn","position_template":"{{ value_json.position }}","position_topic":"zigbee2mqtt/Gordijn","set_position_template":"{ \"position\": {{ position }} }","set_position_topic":"zigbee2mqtt/Gordijn/set","state_closed":"CLOSE","state_open":"OPEN","state_topic":"zigbee2mqtt/Gordijn","unique_id":"0x0c4314fffe3fc90a_cover_zigbee2mqtt","value_template":"{{ value_json.state }}"}
```
Domoticz log:
```
//Set level to 99
2023-01-09 13:49:15.942 Debug: zigbee: Topic: zigbee2mqtt/Gordijn, Message: {"battery":63,"linkquality":68,"position":99,"state":"OPEN","update":{"installed_version":-1,"latest_version":-1,"state":"idle"},"update_available":false}
2023-01-09 13:49:15.942 Debug: Query:SELECT ID, Name, nValue, sValue, SubType, SwitchType FROM DeviceStatus WHERE (HardwareID==6) AND (DeviceID=='0x0c4314fffe3fc90a_cover_zigbee2mqtt') AND (Unit==1)
```

This is the log when I remove the value_template from the configuration payload:

topic:  `zigbee2mqttAD/cover/0x0c4314fffe3fc90a/cover/config`
config payload: 
```
{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/Gordijn/set","device":{"identifiers":["zigbee2mqtt_0x0c4314fffe3fc90a"],"manufacturer":"IKEA","model":"FYRTUR roller blind (E1757)","name":"Gordijn","sw_version":"2.3.088"},"json_attributes_topic":"zigbee2mqtt/Gordijn","name":"Gordijn","position_template":"{{ value_json.position }}","position_topic":"zigbee2mqtt/Gordijn","set_position_template":"{ \"position\": {{ position }} }","set_position_topic":"zigbee2mqtt/Gordijn/set","state_closed":"CLOSE","state_open":"OPEN","state_topic":"zigbee2mqtt/Gordijn","unique_id":"0x0c4314fffe3fc90a_cover_zigbee2mqtt"}
```
Domoticz log:
```
//Set level to 99
2023-01-09 13:56:45.265 Debug: zigbee: Topic: zigbee2mqtt/Gordijn, Message: {"battery":63,"linkquality":68,"position":99,"state":"OPEN","update":{"installed_version":-1,"latest_version":-1,"state":"idle"},"update_available":false}
2023-01-09 13:56:45.266 Debug: Query:SELECT ID, Name, nValue, sValue, SubType, SwitchType FROM DeviceStatus WHERE (HardwareID==6) AND (DeviceID=='0x0c4314fffe3fc90a_cover_zigbee2mqtt') AND (Unit==1)

_--> The following is not executed when value_template is present_

2023-01-09 13:56:45.266 Debug: Query:SELECT ID, Name, Used, SwitchType, nValue, sValue, LastUpdate, Options FROM DeviceStatus WHERE (HardwareID=6 AND DeviceID='0x0c4314fffe3fc90a_cover_zigbee2mqtt' AND Unit=1 AND Type=244 AND SubType=73)
2023-01-09 13:56:45.266 Debug: Query:UPDATE DeviceStatus SET SignalLevel=3, BatteryLevel=63, nValue=2, sValue='99', LastUpdate='2023-01-09 13:56:45' WHERE (ID = 68)
2023-01-09 13:56:45.267 Debug: Query:INSERT INTO LightingLog (DeviceRowID, nValue, sValue, User) VALUES ('68', '2', '99', 'zigbee')
2023-01-09 13:56:45.267 Debug: Query:SELECT Name,SwitchType,AddjValue,StrParam1,StrParam2,Options,LastLevel FROM DeviceStatus WHERE (ID = 68)
2023-01-09 13:56:45.267 Debug: Query:UPDATE DeviceStatus SET LastLevel='99' WHERE (ID = 68)
```
As you can see, if the value_template is present in the payload, the second SQL Select clause is not being executed.
This SELECT (ID, Name, Used, SwitchType, nValue, sValue, LastUpdate, Options) comes from line 5081 in CSQLHelper::UpdateValueInt https://github.com/domoticz/domoticz/blob/7888d73a094827eb68c364b568e62a7dde3b2a8a/main/SQLHelper.cpp#L5063 which is called in line 3622 in MQTTAutoDiscover.cpp in the UpdateBlindPosition function.

https://github.com/domoticz/domoticz/blob/2fa4287ab6f906d47e57aa402e4f9a3e89d6fadb/hardware/MQTTAutoDiscover.cpp#L3622

If we go back to MQTTAutoDiscover::handle_auto_discovery_sensor_message we see that if the value template is available, szvalue gets assigned the value template using the GetValueFromTemplate function. In case it's empty, we assign it the value of qMessage.

https://github.com/domoticz/domoticz/blob/2fa4287ab6f906d47e57aa402e4f9a3e89d6fadb/hardware/MQTTAutoDiscover.cpp#L1255-L1270

If we then go to MQTTAutoDiscover::UpdateBlindPosition and we check between line 3504 (which is the SELECT clause that we see in the logs) and 3622 where we call UpdateValueInt (which is not executed):
We see that if last_value is empty we just return the function.
https://github.com/domoticz/domoticz/blob/2fa4287ab6f906d47e57aa402e4f9a3e89d6fadb/hardware/MQTTAutoDiscover.cpp#L3516-L3517

And below we see that last_value = szValue, which is the value template set in line 1257 when it doesn't work, or qMessage when it does work.

https://github.com/domoticz/domoticz/blob/2fa4287ab6f906d47e57aa402e4f9a3e89d6fadb/hardware/MQTTAutoDiscover.cpp#L1276

I'm probably completely wrong and making a fool of myself (I don't know c++), but maybe we could check if the value template is not empty and is not pSensor->component_type == "cover" if this is really the issue.

```
 if (!value_template.empty()) 
 { 
 	szValue = GetValueFromTemplate(root, value_template); 
```

You should be able to reproduce this bug by creating a device with the first config payload (with value_template), and sending the following updates (while change the position or state). If you then send the configuration payload without value_template, you will see the widget is updated correctly.

Topic: `zigbee2mqtt/Gordijn`
Payload: 
```
{"battery":63,"linkquality":68,"position":98,"state":"OPEN","update":{"installed_version":-1,"latest_version":-1,"state":"idle"},"update_available":false}
```

Happy to provide extra info if needed. Thank you for looking at this, and feel free to close if I'm wrong.

**Comment by gizmocuz** [comment]
Thanks for the detailed explanation and the needed information! Which everybody did this 🤣

I'm debugging this issue. It is caused because the state json contains the state field which is set to 'OPEN'

```
{
  "battery": 63,
  "linkquality": 68,
  "position": 98,
  "state": "OPEN",
  "update": {
    "installed_version": -1,
    "latest_version": -1,
    "state": "idle"
  },
  "update_available": false
}
```

Don't think this 'state' should be defined at all as the position is provided

I have a fix here waiting, but I want to verify two things if possible

When you totally open the blind, what is the value of 'position', and when you totally close the blind, what is the value of position?

**Comment by ksacca** [comment]
Thanks for looking into this.

When fully opened, the state is OPEN with position 100:
```
{"battery":62,"linkquality":65,"position":100,"state":"OPEN","update":{"installed_version":587761201,"latest_version":587761201,"state":"idle"},"update_available":false}
```
When fully closed, the state is CLOSE with position 0:
```
{"battery":62,"linkquality":68,"position":0,"state":"CLOSE","update":{"installed_version":587761201,"latest_version":587761201,"state":"idle"},"update_available":false}
```

Just for your information, in zigbee2mqtt the blinds can also be inverted but this is not the case for me. 
Also, in domoticz the blinds position or state is not inverted (but this is not important for this issue).

![z2m-blind](https://user-images.githubusercontent.com/9539267/211752982-25bc465a-d84d-4ff1-b122-fc94560729a6.JPG)

**Comment by gizmocuz** [comment]
Thank for the information!

Could you try beta 14939, this should solve the issue.

**Comment by ksacca** [comment]
Thank you for the very quick fix! The blind updates as expected now. I posted an update on each forum topic to inform the users the workaround is not needed anymore.

**Comment by gizmocuz** [comment]
@ksacca, In the latest beta version I am now ignoring the state_topic/stat_t when a position topic is configured in the config.
Everything 'should' still work... But I'm not able to verify this.
If possible is it possible to check this?
