### ISSUE TITLE
Blind commands and statuses not right and not consistent

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#5531]
DZ latest version, (build 14928) : 

the status of my blinds (ventitian blinds EU, no slider !) are never the right one, regardless of the new available settings and their 3 possible combinations : "_Reverse Open/Close State_"    and "_Reverse Position_"
Those blinds are created by the new [Airsend plugin](https://github.com/FlyingDomotic/domoticz-airsend-plugin)

-   with everything not checked : 
          -   while clicking on "Close", the blind goes down and the status switch to "Open" 
          -   while clicking on "Open", the blind goes up and the status switch to "Close"

-   with  "_Reverse Open/Close State_"  : 
          same as above ! as written inthe Wiki, it seems to have an effect only on the slider (that I don't have here)

-   with  "_Reverse Position_" checked only : 
          -   while clicking on "Close", the blind goes UP and the status switch to "Close" 
          -   while clicking on "Open", the blind goes DOWN and the status switch to "Open"

-   with both of them checked : 
         -   while clicking on "Close", the blind goes UP and the status switch to "Open" 
         -   while clicking on "Open", the blind goes DOWN and the status switch to "Close"

what did I missed ?

**Comment by rezzalex** [comment]
Maybe put that ticket on hold while it may be solved in the plug-in...

**Comment by rezzalex** [comment]
After double-checking,

the plugin works perfectly for the blinds until V 2022.1 and not as expected from V. 2022.2 and all its associated "blind rework".
So the solution shall be in DZ; not in the plugin.

Thank you

**Comment by gizmocuz** [comment]
Nope, so without any reversing the plugin should work normal.
First add a dummy blind to domoticz and see if that is working correctly (should)

In the plugin I see they use a value 0 for open, but that is not correct, it should be 100

https://github.com/FlyingDomotic/domoticz-airsend-plugin/blob/main/plugin.py

![image](https://user-images.githubusercontent.com/2265299/212701458-e09c2a0a-5589-47a6-b41e-c2eb9b9bf238.png)


See

https://www.domoticz.com/wiki/Blinds


Anyway, as we are very certain all is work correctly and have been tested by many users I will close this issue.
Yes it sucks that plugins need to be rewritten, but in the end it is for the better.
The change was not an easy decision and has been discussed and tested internally for quite a long period of time
