### ISSUE TITLE
EnOcean Peha Easyclink since update

### ISSUE THREAD

**Issue by Lesger** [domoticz/domoticz#5535]
Since the update the EnOcean changed. I have EnOcean Peha Easyclick units in Domoticz for years. They worked after teaching the units a dummy EnOcean switch. So I made the dummies and put one unit at a time in teach mode and pressed the dummy switch, exited teach mode and it worked.

Now when I press one of my old dummies it gives the error:

Error sending switch command, check device/hardware (idx=36) !

Log says:

 Error: EnOccean: Node FF99C002 can not be used as a switch

In the new hardware menu I can supposedly add via teach in, but I do not know how Peha Easyclick units can give a signal to be discovered. Any help would be appriciated.

**Comment by Lesger** [comment]
I forgot to add: I use the EnOcean USB (ESP3)

**Comment by waltervl** [comment]
@efdeb please assist?

**Comment by efdeb** [comment]
First, can you please add more precisions :
- what is the domoticz version you are currently using ?
- what are the exact model/reference of the  EnOcean Peha Easyclick units you are using ?
- did you change your EnOcean USB (ESP3) hardware (USB key ou other device) ?

**Comment by Lesger** [comment]
> First, can you please add more precisions :
> 
>     * what is the domoticz version you are currently using ?
> 
>     * what are the exact model/reference of the  EnOcean Peha Easyclick units you are using ?
> 
>     * did you change your EnOcean USB (ESP3) hardware (USB key ou other device) ?

Thanks for your reply!

- Domoticz 2022.2
- Peha Easyclick 451-FU-BEBI and 452-FU-EBI
- No, only did the update of Domoticz. The USB is the same, didn't move it and still sees the use of the switches I also have (type: PTM-210 DB)

**Comment by efdeb** [comment]
OK, these peha units cannot be teached-in to receive direct commands, so you must use dummy switches and teach them to the peha devices.

Did you try to recreate a dummy switch after the upgrade ans re-associate to a peha device ?

**Comment by Lesger** [comment]
Yes, that is exactly how it worked before and how I tried to reinstall it after the update. But it didn't work.

Now before I was to answer you, just now, I tried again just to be sure. And lo and behold it works!
Maybe I did a reboot of the Pi in between and maybe that did the trick... I do not know, but it helped to write my problem here and to troubleshoot with you! 

So thank you!!

**Comment by waltervl** [comment]
Solved! Then I will close this issue.

**Comment by efdeb** [comment]
Good news !!!
