### ISSUE TITLE
Domoticz exposing (status) metrics for monitoring/alerting purposes (for use by Prometheus, Monit, Kubernetes, etc)

### ISSUE THREAD

**Issue by kiddigital** [domoticz/domoticz#5537]
### Enhancement request

Add a '/metrics' route presenting (time-series) metrics on several aspects of how Domoticz is performing.

This route should leverage the HTTP returncodes (normally '200 Ok') to report health status so common health checks (Like [Kubernetes health checks](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) or [Docker Health checks](https://docs.docker.com/engine/reference/builder/#healthcheck)) can determine state by checking the HTTP returncode (and no need the interpret the resulting content).

It should generate metrics following the [Open Metrics specification](https://openmetrics.io/).

Output could look like:
```
# TYPE apiserver_request_seconds summary
# UNIT apiserver_request_seconds seconds
# HELP apiserver_request_seconds Latency from all requests handled by the API
apiserver_request_seconds_sum{path="/json.htm",method="GET"} 9036.32
apiserver_request_seconds_count{path="/json.htm",method="GET"} 807283.0
apiserver_request_seconds_created{path="/json.htm",method="GET"} 1605281325.0
apiserver_request_seconds_sum{path="/json.htm",method="POST"} 479.3
apiserver_request_seconds_count{path="/json.htm",method="POST"} 34.0
apiserver_request_seconds_created{path="/json.htm",method="POST"} 1605281325.0
# TYPE available_devices gauge
# HELP available_devices Number of devices that currently exist in the system (Active and Inactive)
available_devices 69
# TYPE active_devices gauge
# HELP active_devices Number of Active devices in the system
active_devices 42
# TYPE process_cpu_seconds counter
# UNIT process_cpu_seconds seconds
# HELP process_cpu_seconds Total user and system CPU time spent in seconds.
process_cpu_seconds_total 4.20072246e+06
# EOF
```

**Some background info**
With Home Automation, and Domoticz in the center, becoming a vital part of our daily lives, it needs to be working all the time.

Therefor it makes sense to ensure Domoticz is operational and running smoothly. And in case it doesn't, have ways to restart Domoticz and bring it back to a working state, preferably without any human intervention.

Very annoying if someone in the household tries to turn on a light in the middle of the night and finds out that it doesn't. And then you have to get up as well and try to fix it at 4am. Also very bad for the acceptance factor of Home Automation in general.

There are several ways already available and Domoticz does some internal checking as well. Nowadays more tools and methods have become available to make monitoring, including alerting, restarting, etc. much easier. Especially when running things (like Domoticz) in a containerized environment (Docker, Kubernetes, etc.).

If Domoticz could be extended to provide metrics on its performance and state in a standardized way and receives support for common health checks, different standard tools can be leveraged to safeguard proper functioning of Domoticz.

**Comment by waltervl** [comment]
Is there also a general status metric of the domoticz environment?
With monit we monitor a general status metric:
```
  if failed
     url http://127.0.0.1:8080/json.htm?type=command&param=getversion
         and content = '"status" : "OK"'
     for 2 cycles
     then restart
```
I see that we can do the same with Docker HEALTHCHECK ;-)
```
HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://127.0.0.1:8080/json.htm?type=command&param=getversion || exit 1
```

I think we would like to see a 

- process_memory_usage to monitor memory usage
- apiserver_request_seconds_avarage (over 1 day or hour?) to monitor if domoticz is slowing down....

**Comment by gizmocuz** [comment]
@waltervl , when you add the motherboard hardware you have already the CPU/Memory and disk usage you can monitor

**Comment by waltervl** [comment]
I know, but this enhancement is about application monitoring outside Domoticz. CPU and memory usage are important parameters.

**Comment by gizmocuz** [comment]
Yes, so you can get these parameters by calling the JSON API

Also it is extreme easy to send an alarm from within Domoticz if any of the above is getting too high.

Otherwise, if this is about process/system monitoring, it is not a topic that should be discussed here...
There are plenty of websites about this. It could be even as simple as installing a SNMP agent.

**Comment by waltervl** [comment]
Additional metrics:
- database size
- time to do nightly database update.
- time to do automatic database daily/hourly backup if enabled.

**Comment by gizmocuz** [comment]
I state with my above remarks, this is not something for Domoticz but for a monitoring agent (like SNMP)
(And most data is available in Domoticz anyway via the motherboard hardware which you can also query with external monitoring apps)
