### ISSUE TITLE
ZWA024: Temperature fluctuating +/- 4 degrees C every +/- 30 minutes

### ISSUE THREAD

**Issue by duck-wolv** [domoticz/domoticz#5538]
This is might related to #5542 as I found this behavior since then.

Environment:
Docker compose with Domoticz, Z-wave JS UI and Mosquitto 2

**Domoticz**
Version: 2022.2 (build 14957)
Build Hash: af996de5e
Compile Date: 2023-01-12 14:05:51
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]

**Zwave-JS-UI**
zwave-js-ui: 8.6.3.c12b1c6
zwave-js: 10.3.1
home id: 3278051996
home hex: 0xc3631a9c

While started to use beta 14938 (and newer versions) I start to see fluctuating temperatures in a  Aeotec MultiSensor 7 (ZWA024) device which is powered by USB. This device is located on the living room and a temperature fluctuating every 30 minutes with roughly 3 tot 4 degrees Celsius is technically not feasible as the room temperature is quite stable and around 18 degrees. 

I verified that Z-Wave JSUI is holding the correct (or at least the most likely) temperature of around 18 while Domoticz is showing a value around 14.

Following actions I've taken so far to solve the issues but without luck:

- Removing device from Domoticz (and have it back via auto discovery)
- Restarting (down + up) of docker-compose
- Clear retained values for this specific device from ZWAVE-JS-UI
- Removing Mosquitto entire .db file
- Looking up the history of the sensor via MQTT Explorer which does not seem to exist ("History" only shows the last value, which is always around 18).

What else can I try? Which data do I need to upload for verifying or debugging?

![image](https://user-images.githubusercontent.com/1925581/212261591-d6ade54c-b616-464a-ba90-8c719b221232.png)
![image](https://user-images.githubusercontent.com/1925581/212264255-1246e18e-8dad-4422-b2f9-86414afcf409.png)

**Comment by gizmocuz** [comment]
Did you had a look at the changes of that PR?

I do not experience this behavior.

**Comment by gizmocuz** [comment]
I think you are talking about issue #5524

**Comment by gizmocuz** [comment]
And there is no need to create multiple issues

**Comment by duck-wolv** [comment]
> I think you are talking about issue #5524

Yes, my bad! Indeed 5524. Sorry for creating multiple issues.
