### ISSUE TITLE
LiveSearch not fully working in FireFox (Count and reset)

### ISSUE THREAD

**Issue by kiddigital** [domoticz/domoticz#5539]
With PR #5525 great new UI functionality has been added.

It works fine in Edge/Chrome, but not in FireFox (haven't tested Safari yet).

The 'search' works, meaning it nicely filters and shows only the devices according to the seach criteria.

But the count of matched devices is not displayed (as it is in Chrome) and pressing the 'X' does nothing (should reset/remove the search criteria).

![image](https://user-images.githubusercontent.com/12084477/212265157-be292aa7-d703-42e1-927d-ba9c817fff0f.png)

**Comment by waltervl** [comment]
On Firefox mobile (also in desktop mode) it is working although the count font size is a little small...

![Screenshot_20230113-145225-142](https://user-images.githubusercontent.com/16327072/212336077-1768139d-3706-4cb5-b782-cec5b2fb3265.png)

**Comment by gizmocuz** [comment]
Tested here with firefox and it is working here (counter and cross), tried in a private browser?

**Comment by kiddigital** [comment]
Silly me.. cache, cache, cache :(
