### ISSUE TITLE
[MQTT] Handle _EVENT message from zwave-js-ui for Keypad hardware

### ISSUE THREAD

**Issue by max3163** [domoticz/domoticz#5543]
Hello, 

I just switch to the new zwave-js-ui layer with MQTT broker as OpenZWAVE is deprecated ( and no more maintained ). 
So far so good, but I have an issue with my MINI KEYPAD RFID ( Keypad with alarm activation by rfid tag ) from Wintop.
The tag reader have the binary switch from zwave-js never updated ... 
In fact, when I switch home or away in the tag reader an event/notification is fire :

```
2023-01-14T19:58:07.764Z CNTRLR   [Node 006] [Notification]
type:   Access Control
event:  Keypad unlock operation
userId: 4
```
I have activated the send Z-Wave event option ( Enable this to get all zwave events in MQTT on _EVENTS topic ) but no information is handle on domoticz. 

On MQTT log : 
```
2023-01-14T19:58:07: Received PUBLISH from ZWAVE_GATEWAY-zwave-js-ui (d0, q1, r0, m12351, 'domoticz/_EVENTS/ZWAVE_GATEWAY-zwave-js-ui/node/node_value_updated', ... (956 bytes))
2023-01-14T19:58:07: Sending PUBLISH to Domoticz-MQTT-AutoDiscoverd96c4a0c-2a15-40d8-a202-c640693b508011 (d0, q0, r0, m0, 'domoticz/_EVENTS/ZWAVE_GATEWAY-zwave-js-ui/node/node_value_updated', ... (956 bytes))
2023-01-14T19:58:07: Sending PUBACK to ZWAVE_GATEWAY-zwave-js-ui (m12351, rc0)
2023-01-14T19:58:07: Received PUBLISH from ZWAVE_GATEWAY-zwave-js-ui (d0, q1, r0, m12352, 'domoticz/Entrée/Zipato_RFID_Clavier/113/0/Access_Control/Keypad_unlock_operation', ... (43 bytes))
```

Maybe the Access_Control hardware is not handled ? 

So I wonder if it's possible to handle this kind of message on the domoticz side to allow the switch of my tag reader hardware.

Thanks for the help !

**Comment by max3163** [comment]
When I see the complete trace of MQTT i don't know if the problem is on the Z-WAVESJ side or domoticz. 

I don't know if alarmType and Access_Control are not correctly handle in domoticz :

```
domoticz/Entrée/Zipato_RFID_Clavier/113/0/alarmType {"id":"6-113-0-alarmType","nodeId":6,"toUpdate":false,"commandClass":113,"commandClassName":"Notification","endpoint":0,"property":"alarmType","propertyName":"alarmType","type":"number","readable":true,"writeable":false,"label":"Alarm Type","stateless":false,"commandClassVersion":2,"min":0,"max":255,"list":false,"value":0,"lastUpdate":1673776384572}
```
Or 
```
domoticz/Entrée/Zipato_RFID_Clavier/113/0/Access_Control/Keypad_unlock_operation {"time":1673776384575,"value":{"userId":4}}
```

If it's not in domoticz side, I will open an issue on Z-WAVEJS board but I need some explanations.

**Comment by gizmocuz** [comment]
Could be that alarm types are not all implemented. Best to look/debug in the MQTT-AD code.

It might also help if you provide the config topic name and payload

**Comment by max3163** [comment]
Topic name : 

`domoticz/Entrée/Zipato_RFID_Claier/113/0/Access_Control/Keypad_unlock_operation`

Or

`domoticz/Entrée/Zipato_RFID_Claier/113/0/Access_Control/Keypad_lock_operation`

With payload : 

`{"time":1673776384575,"value":{"userId":4}}`

And for alarmType, topic

`domoticz/Entrée/Zipato_RFID_Clavier/113/0/alarmType`

Payload : 

```{"id":"6-113-0-alarmType","nodeId":6,"toUpdate":false,"commandClass":113,"commandClassName":"Notification","endpoint":0,"property":"alarmType","propertyName":"alarmType","type":"number","readable":true,"writeable":false,"label":"Alarm Type","stateless":false,"commandClassVersion":2,"min":0,"max":255,"list":false,"value":0,"lastUpdate":1673776384572}```

**Comment by max3163** [comment]
[debug.txt](https://github.com/domoticz/domoticz/files/10420380/debug.txt)

Full trace

**Comment by gizmocuz** [comment]
Thank you for this information.

It's still a bit unclear

the config topic should end with /config

So I think it is this one:

topic name:
**domoticz/switch/Entrée-Zipato_RFID_Clavier/switch/config**

topic payload:
```
{
  "payload_off": false,
  "payload_on": true,
  "value_template": "{{ value_json.value }}",
  "command_topic": "domoticz/Entrée/Zipato_RFID_Clavier/37/0/targetValue/set",
  "state_topic": "domoticz/Entrée/Zipato_RFID_Clavier/37/0/currentValue",
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xf50a81d1_node6"
    ],
    "manufacturer": "Wintop",
    "model": "Keypad with alarm activation rfid tag (MINI KEYPAD RFID)",
    "name": "Entrée-Zipato RFID Clavier",
    "sw_version": "0.28"
  },
  "name": "Entrée-Zipato RFID Clavier_switch",
  "unique_id": "zwavejs2mqtt_0xf50a81d1_6-37-0-currentValue"
}
```

You have 3 config topics for this node, batery is low, battery level, and this switch

The switch status state_topic is **domoticz/Entrée/Zipato_RFID_Clavier/37/0/currentValue**

So when you set the device to home/away, I would expect a value changing in the above topic

Could you verify this?

I did not find any config topic in your logs that references the text "domoticz/Entrée/Zipato_RFID_Claier"

Maybe it is not inside your log

Could you use the application 'MQTT Explorer', there is a search option where you can enter the above text
You should then see a config topic with payload, please post these two

**Comment by max3163** [comment]
When I use the tag reader the switch is not updated at all.... i just received message on this topic :

` domoticz/Entrée/Zipato_RFID_Clavier/113/0/Access_Control/Keypad_unlock_operation`

Sorry I miss one letter when I copy paste the topic ... claier => Clavier ( keypad in French )

![image](https://user-images.githubusercontent.com/13835366/212553285-35656d13-a541-4c57-9206-7194509bec29.png)

**Comment by gizmocuz** [comment]
Okey and there is no config object mentioning this topic?
If not, I hope you can configure something for the tag reading in zwavejs-ui, else there is nothing we can do

**Comment by max3163** [comment]
No .. just this payload 

{"time":1673800041349,"value":{"userId":4}}

So I need to open an issue on zwavejs-ui to add something?

**Comment by gizmocuz** [comment]
Yes, I think you would expect a switch when armed (or nor armed)

**Comment by max3163** [comment]
I don't understand why domoticz can't just handle this kind of topics and create a switch named Access Control with lock or unlock status ?

**Comment by gizmocuz** [comment]
Well first it might not 'just' be implemented. And secondly, if there is no update for the switch, how on earth should we know?
So, we should receive a config for a 'Access control' switch that changes the state

**Comment by max3163** [comment]
Ok my bad for my last comment, I don't know how it work and this is not the right way to ask something.

May be I can do something on the zwave side by following this documentation ? 

https://github.com/zwave-js/zwave-js-ui/blob/master/docs/homeassistant/homeassistant-mqtt.md#custom-components

**Comment by gizmocuz** [comment]
That could work... I'm no expert in this

But first you need to find out what exactly changes when you lock and unlock

Based on this you could write a implementation

This is no ordinary node like a switch/door sensor

**Comment by max3163** [comment]
I close it 
I opened an issue on zwave-js side : https://github.com/zwave-js/zwave-js-ui/issues/2929

**Comment by max3163** [comment]
I re open the ticket after some discussions on the ZWAVE-JS-UI teams. 
In this comment https://github.com/zwave-js/zwave-js-ui/issues/2929#issuecomment-1415435460 they ask if it's possible on the domoticz side to implement a device corresponding to the MQTT packet received ?

**Comment by gizmocuz** [comment]
@max3163 , you mean you want to see everything that is received by MQTT?
That is possible by enabling the hardware debug level when you launch domoticz
(see the startup script, or add this in the docker compose enviroment)

`-debuglevel hardware`

for example

`./domoticz -debuglevel hardware`

**Comment by gizmocuz** [comment]
@max3163 , There is also another issue with your setup.
In ZWaveJS-UI, your home assistant discovery prefix is set to the same name as your MQTT prefix.
By default the home assistant discovery prefix is set to 'homeassistant' and the MQTT prefix to zwave
When you have them different, the config objects will be in published in the homeassistant topic, and all zwave nodes will publish their state in the zwave topic
Also check if the config objects are persistant
If you do not see any config topics, just disable the MQTT hardware in domoticz and enable it again.
This is causing ZWaveJS-UI to resend the config objects i believe if they are not persistant

**Comment by max3163** [comment]
I'm totaly lost ... I'have activated the debug level for hardware but I still don't see this topic arrived on domoticz 

domoticz/Entrée/Zipato_RFID_Clavier/113/0/Access_Control/Keypad_(un)lock_operation

2023-02-10T12:00:49.956Z - NOTIFICATION 
Arg 0:
113
Arg 1:
└─type: 6
└─event: 5
└─label: Access Control
└─eventLabel: Keypad lock operation
└─parameters
└──userId: 4

I don't think I understand well how ZWAVE-JS/MQTT/Domoticz work in fact... 

I don't have config object for the Access_Control operation ... just un "Event" from ZWAVE-JS ( as notification )

**Comment by max3163** [comment]
I've written a little program in Go to parse the "domoticz/Entrée/Zipato_RFID_Clavier/113/0/Access_Control/Keypad_(un)lock_operation" topics and push on the "domoticz/Entrée/Zipato_RFID_Clavier/37/0/targetValue/set" topic the corresponding state. 
It works, so I will close the issue even if the source of the problem persistent.
