### ISSUE TITLE
MQTT autodiscovery - few additional fixes and feature request for thermostats

### ISSUE THREAD

**Issue by odelma** [domoticz/domoticz#5549]
Hi,

As the previous issue about mqtt-ad + thermostat was closed (and fixed - thanks again 👍 ), I would like to raise two additional items for consideration. Since pairing my thermostat devices (Moes BHT-002, https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html), I've seen these errors in the log:
```
2023-01-16 14:36:01.144 Error: MQTT autodiscovery: Climate device unhandled temperature_state_template (0x84ba20fffe8a0e68_climate_zigbee2mqtt)
2023-01-16 14:36:27.100 Error: MQTT autodiscovery: Climate device unhandled temperature_state_template (0x84ba20fffe8a0e68_climate_zigbee2mqtt)
2023-01-16 14:37:27.047 Error: MQTT autodiscovery: Climate device unhandled temperature_state_template (0x84ba20fffe8a0e68_climate_zigbee2mqtt)
2023-01-16 15:46:54.682 Error: MQTT autodiscovery: Climate device unhandled temperature_state_template (0x50325ffffe401d5d_climate_zigbee2mqtt)
2023-01-16 15:46:57.601 Error: MQTT autodiscovery: Climate device unhandled temperature_state_template (0x50325ffffe401d5d_climate_zigbee2mqtt)
2023-01-16 15:47:57.461 Error: MQTT autodiscovery: Climate device unhandled temperature_state_template (0x50325ffffe401d5d_climate_zigbee2mqtt)
2023-01-16 16:29:54.669 Error: MQTT autodiscovery: Climate device unhandled temperature_state_template (0x84ba20fffe8a0e68_climate_zigbee2mqtt)
2023-01-16 16:30:26.746 Error: MQTT autodiscovery: Climate device unhandled temperature_state_template (0x84ba20fffe8a0e68_climate_zigbee2mqtt)
2023-01-16 16:31:26.559 Error: MQTT autodiscovery: Climate device unhandled temperature_state_template (0x84ba20fffe8a0e68_climate_zigbee2mqtt)

```
Despite the occasional error, the temperature device is working seemingly correct and receiving updates. I have tracked the messages with mqtt explorer and cannot see anything strange. Not sure if this can be somehow related to two sensors onboard (floor + device) or the fact that it also publishes local_temperature_calibration (+ limits) value. The messages that mqtt-ad interpret look like:
```
{
  "child_lock": "UNLOCK",
  "current_heating_setpoint": 18,
  "deadzone_temperature": 1,
  "heat": "OFF",
  "linkquality": 90,
  "local_temperature": 19.5,
  "local_temperature_calibration": -3,
  "max_temperature": 35,
  "max_temperature_limit": 25,
  "min_temperature_limit": 5,
  "preset": "hold",
  "preset_mode": "hold",
  "program": {
    "saturday_p1_hour": 0,
    "saturday_p1_minute": 0,
    "saturday_p1_temperature": 0,
    "saturday_p2_hour": 0,
    "saturday_p2_minute": 0,
    "saturday_p2_temperature": 0,
    "saturday_p3_hour": 0,
    "saturday_p3_minute": 0,
    "saturday_p3_temperature": 0,
    "saturday_p4_hour": 0,
    "saturday_p4_minute": 0,
    "saturday_p4_temperature": 0,
    "sunday_p1_hour": 0,
    "sunday_p1_minute": 0,
    "sunday_p1_temperature": 0,
    "sunday_p2_hour": 0,
    "sunday_p2_minute": 0,
    "sunday_p2_temperature": 0,
    "sunday_p3_hour": 0,
    "sunday_p3_minute": 0,
    "sunday_p3_temperature": 0,
    "sunday_p4_hour": 0,
    "sunday_p4_minute": 0,
    "sunday_p4_temperature": 0,
    "weekdays_p1_hour": 0,
    "weekdays_p1_minute": 0,
    "weekdays_p1_temperature": 0,
    "weekdays_p2_hour": 0,
    "weekdays_p2_minute": 0,
    "weekdays_p2_temperature": 0,
    "weekdays_p3_hour": 0,
    "weekdays_p3_minute": 0,
    "weekdays_p3_temperature": 0,
    "weekdays_p4_hour": 0,
    "weekdays_p4_minute": 0,
    "weekdays_p4_temperature": 0
  },
  "running_state": "idle",
  "sensor": "OU",
  "system_mode": "heat"
}
```

The errors are not coming with each update. 

The config topic is:
```
{
  "action_template": "{% set values = {None:None,'idle':'off','heat':'heating','cool':'cooling','fan_only':'fan'} %}{{ values[value_json.running_state] }}",
  "action_topic": "zigbee2mqtt/Termostaatti makuuhuone",
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state"
    }
  ],
  "current_temperature_template": "{{ value_json.local_temperature }}",
  "current_temperature_topic": "zigbee2mqtt/Termostaatti makuuhuone",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x50325ffffe401d5d"
    ],
    "manufacturer": "Moes",
    "model": "Moes BHT series Thermostat (BHT-002-GCLZB)",
    "name": "Termostaatti makuuhuone"
  },
  "max_temp": "35",
  "min_temp": "5",
  "mode_command_topic": "zigbee2mqtt/Termostaatti makuuhuone/set/system_mode",
  "mode_state_template": "{{ value_json.system_mode }}",
  "mode_state_topic": "zigbee2mqtt/Termostaatti makuuhuone",
  "modes": [
    "off",
    "heat"
  ],
  "name": "Termostaatti makuuhuone",
  "preset_mode_command_topic": "zigbee2mqtt/Termostaatti makuuhuone/set/preset",
  "preset_mode_state_topic": "zigbee2mqtt/Termostaatti makuuhuone",
  "preset_mode_value_template": "{{ value_json.preset }}",
  "preset_modes": [
    "hold",
    "program"
  ],
  "temp_step": 1,
  "temperature_command_topic": "zigbee2mqtt/Termostaatti makuuhuone/set/current_heating_setpoint",
  "temperature_state_template": "{{ value_json.current_heating_setpoint }}",
  "temperature_state_topic": "zigbee2mqtt/Termostaatti makuuhuone",
  "temperature_unit": "C",
  "unique_id": "0x50325ffffe401d5d_climate_zigbee2mqtt"
}
```

This brings me to the feature request, would it be possible to get a switch created for action_template that is updated as running_state? For my device it can be only idle or heating, but looks like for thermostats in general it can be other states as well. I guess the sort of a problem here is that this information is just what the device reports, it cannot be set back to device. So it should be read only. Nonetheless, it would be useful to have this information available to be able to set actions based on the status of the thermostat or just for example to track how long it has been heating.

**Comment by gizmocuz** [comment]
Regarding the switch, it is a status, might be better in a text sensor.
But would this not create a lot of changes during the day, and if we record all these changes for a year, would this not create a very large log in the database?

**Comment by gizmocuz** [comment]
I debugged the above issue, and with the above config object (please next time also include the topic name) and status payload there is no error.
The only time the above error can occur is that the status payload does not contain 'current_heating_setpoint'

Maybe you can log it for some time and check if this happens?

But there is nothing we can do about this

It also does seem no to appear regularly, but still quite often

**Comment by odelma** [comment]
Trying to monitor mqtt to get a confirmation on this hypothesis. 

Yes, text sensor would also work for the running state. It could change many times per day, that is true. For this sensor/switch I would see the primary purpose so that you could setup a dummy counter (eg. ”On minutes”) or electricity sensor that you could update via event system based on the status of the running state. Ie. it would be possible to track consumption. The history of the running state sensor/switch as such is not that interesting so short log (switch) would work for that. On average, there should be a lot less changes than eg. for typical electricity measuring device, temperature sensor, pir sensor - so the amount of logs should not be too big of an issue…🤔

**Comment by gizmocuz** [comment]
Well everytime the temperature drops a little bit, this status is updated
Still don't think it is usefull

**Comment by odelma** [comment]
Here I must agree to disagree 😉 
While I cannot of course speak on behalf of anyone else, I strongly feel that in these times of high energy prices with more and more focus on what different devices consume it would be very useful information to see how much electric floor heating is using energy. It opens up the possibilities to do all kinds of optimization, the very core of why home automation can be useful. If, for example, I know I have 10 different 500W floor heating areas, with this simple and quite inexpensive thermostat I would be able to track the consumption (by checking how many minutes each thermostat is on) of the whole floor heating quite easily. Without this information, it becomes much harder (yeah, I can try derive it from hysteresis, setpoint value and temperature but when the device reports it automatically, why not use it).

I do agree that this is not a "must have" feature to be included but a) the devices exposes this information b) it can be used for valuable purposes (of which one example is provided above) I must admit I don't see why it should not be implemented.

> Well everytime the temperature drops a little bit, this status is updated

Can I ask what you mean with this? There is minimum one degree hysteresis and floor heating takes time to have an effect on temperature so it is not like the status would be constantly changing. I would guess in most applications it would take at least an hour, often much more 🤔

**Comment by gizmocuz** [comment]
Consumption you track with a kWh meter?

Everytime the temperature drops (when the heater is not heating) and it needs to add some heat to get to your desired temperature, the action_topic changes it's state, that can happen a lot of times during the day.

**Comment by odelma** [comment]
> that can happen a lot of times during the day. 

In theory yes, but as I explained, at least with this type of floor heating thermostat with 1C hysteresis it takes hour(s) between warming cycles even in cold weather. And even if it would happen (with some other type of thermostat?) more often, I don’t really see the problem. Many devices like energy meters report many time per minute. It should under no circumstance be that often with thermostat for idle vs. heating. 

> Consumption you track with a kWh meter?

Ideally, I would like to create dummy kWh meters which I would update via event system based on the idle/heating status of these thermostat. At least for me it would provide valuable info ☺️

**Comment by gizmocuz** [comment]
That's incorrect. An energy meter value is logged every 5 minutes, and once a day. The short log can log 100 messages a minute for many days

**Comment by odelma** [comment]
Yeah, true. I was thinking already the suggested custom / text sensor for this.

But again, it should not be that many updates in the end. Definitely not for this kind of floor heating ones.

**Comment by gizmocuz** [comment]
Is there still a issue ?

> I debugged the above issue, and with the above config object (please next time also include the topic name) and status payload there is no error. The only time the above error can occur is that the status payload does not contain 'current_heating_setpoint'
> 
> Maybe you can log it for some time and check if this happens?
> 
> But there is nothing we can do about this
> 
> It also does seem no to appear regularly, but still quite often

**Comment by odelma** [comment]
Yes, unfortuntely it does but I have not been able to record it. There are so may updates coming from these devices that the history of MQTT explorer always runs out. Even now when it last happened few minutes ago:
![image](https://user-images.githubusercontent.com/10372952/215333691-682e7916-7a21-46ff-813d-ff2f0abbd1de.png)
But for some reason, it seem these are coming more seldom than at first.

**Comment by odelma** [comment]
Speak of the devil, not there were additional error right after the ones above and indeed the "current_heating_setpoint" is missing from the ones causing the error.

A few examples:
```
{"child_lock":"UNLOCK","deadzone_temperature":1,"heat":"OFF","linkquality":96,"local_temperature":19,"local_temperature_calibration":-3,"max_temperature":35,"max_temperature_limit":25,"min_temperature_limit":5,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":0,"saturday_p1_minute":0,"saturday_p1_temperature":0,"saturday_p2_hour":0,"saturday_p2_minute":0,"saturday_p2_temperature":0,"saturday_p3_hour":0,"saturday_p3_minute":0,"saturday_p3_temperature":0,"saturday_p4_hour":0,"saturday_p4_minute":0,"saturday_p4_temperature":0,"sunday_p1_hour":0,"sunday_p1_minute":0,"sunday_p1_temperature":0,"sunday_p2_hour":0,"sunday_p2_minute":0,"sunday_p2_temperature":0,"sunday_p3_hour":0,"sunday_p3_minute":0,"sunday_p3_temperature":0,"sunday_p4_hour":0,"sunday_p4_minute":0,"sunday_p4_temperature":0,"weekdays_p1_hour":0,"weekdays_p1_minute":0,"weekdays_p1_temperature":0,"weekdays_p2_hour":0,"weekdays_p2_minute":0,"weekdays_p2_temperature":0,"weekdays_p3_hour":0,"weekdays_p3_minute":0,"weekdays_p3_temperature":0,"weekdays_p4_hour":0,"weekdays_p4_minute":0,"weekdays_p4_temperature":0},"running_state":"idle","sensor":"OU","system_mode":"heat"}
{"child_lock":"UNLOCK","deadzone_temperature":1,"heat":"OFF","linkquality":96,"local_temperature":19,"local_temperature_calibration":-3,"max_temperature":35,"max_temperature_limit":25,"min_temperature_limit":5,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":0,"saturday_p1_minute":0,"saturday_p1_temperature":0,"saturday_p2_hour":0,"saturday_p2_minute":0,"saturday_p2_temperature":0,"saturday_p3_hour":0,"saturday_p3_minute":0,"saturday_p3_temperature":0,"saturday_p4_hour":0,"saturday_p4_minute":0,"saturday_p4_temperature":0,"sunday_p1_hour":0,"sunday_p1_minute":0,"sunday_p1_temperature":0,"sunday_p2_hour":0,"sunday_p2_minute":0,"sunday_p2_temperature":0,"sunday_p3_hour":0,"sunday_p3_minute":0,"sunday_p3_temperature":0,"sunday_p4_hour":0,"sunday_p4_minute":0,"sunday_p4_temperature":0,"weekdays_p1_hour":0,"weekdays_p1_minute":0,"weekdays_p1_temperature":0,"weekdays_p2_hour":0,"weekdays_p2_minute":0,"weekdays_p2_temperature":0,"weekdays_p3_hour":0,"weekdays_p3_minute":0,"weekdays_p3_temperature":0,"weekdays_p4_hour":0,"weekdays_p4_minute":0,"weekdays_p4_temperature":0},"running_state":"idle","sensor":"OU","system_mode":"heat"}
{"child_lock":"UNLOCK","deadzone_temperature":1,"heat":"OFF","linkquality":96,"local_temperature":19,"local_temperature_calibration":-3,"max_temperature":35,"max_temperature_limit":25,"min_temperature_limit":5,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":0,"saturday_p1_minute":0,"saturday_p1_temperature":0,"saturday_p2_hour":0,"saturday_p2_minute":0,"saturday_p2_temperature":0,"saturday_p3_hour":0,"saturday_p3_minute":0,"saturday_p3_temperature":0,"saturday_p4_hour":0,"saturday_p4_minute":0,"saturday_p4_temperature":0,"sunday_p1_hour":0,"sunday_p1_minute":0,"sunday_p1_temperature":0,"sunday_p2_hour":0,"sunday_p2_minute":0,"sunday_p2_temperature":0,"sunday_p3_hour":0,"sunday_p3_minute":0,"sunday_p3_temperature":0,"sunday_p4_hour":0,"sunday_p4_minute":0,"sunday_p4_temperature":0,"weekdays_p1_hour":0,"weekdays_p1_minute":0,"weekdays_p1_temperature":0,"weekdays_p2_hour":0,"weekdays_p2_minute":0,"weekdays_p2_temperature":0,"weekdays_p3_hour":0,"weekdays_p3_minute":0,"weekdays_p3_temperature":0,"weekdays_p4_hour":0,"weekdays_p4_minute":0,"weekdays_p4_temperature":0},"running_state":"idle","sensor":"OU","system_mode":"heat"}

{"child_lock":"UNLOCK","current_heating_setpoint":18,"deadzone_temperature":1,"heat":"OFF","linkquality":96,"local_temperature":19,"local_temperature_calibration":-3,"max_temperature":35,"max_temperature_limit":25,"min_temperature_limit":5,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":0,"saturday_p1_minute":0,"saturday_p1_temperature":0,"saturday_p2_hour":0,"saturday_p2_minute":0,"saturday_p2_temperature":0,"saturday_p3_hour":0,"saturday_p3_minute":0,"saturday_p3_temperature":0,"saturday_p4_hour":0,"saturday_p4_minute":0,"saturday_p4_temperature":0,"sunday_p1_hour":0,"sunday_p1_minute":0,"sunday_p1_temperature":0,"sunday_p2_hour":0,"sunday_p2_minute":0,"sunday_p2_temperature":0,"sunday_p3_hour":0,"sunday_p3_minute":0,"sunday_p3_temperature":0,"sunday_p4_hour":0,"sunday_p4_minute":0,"sunday_p4_temperature":0,"weekdays_p1_hour":0,"weekdays_p1_minute":0,"weekdays_p1_temperature":0,"weekdays_p2_hour":0,"weekdays_p2_minute":0,"weekdays_p2_temperature":0,"weekdays_p3_hour":0,"weekdays_p3_minute":0,"weekdays_p3_temperature":0,"weekdays_p4_hour":0,"weekdays_p4_minute":0,"weekdays_p4_temperature":0},"running_state":"idle","sensor":"OU","system_mode":"heat"}
```

The last one was again including setpoint info as well. Is there anything that can or should be done? I guess the fault is in thermostat firmware..

**Comment by gizmocuz** [comment]
@odelma , yes this error is printed when the 'current_heating_setpoint' is not provided.
Maybe you could ask the developers from zigbee2mqtt if this should have been there, or why it is not in the state object.
I can silence the warning, but there could also be a issue with the template and then we will miss these errors
I would expected it to be always here

**Comment by odelma** [comment]
Sorry for the delay in response. I've now opened an issue in zigbee2mqtt to be able to close this (or if we should reconsider suppressing these errors as "expected"). 

https://github.com/Koenkk/zigbee2mqtt/issues/16854

**Comment by gizmocuz** [comment]
Please report back if you can answer the above question

**Comment by waltervl** [comment]
@odelma please give feedback else topic will be closed.

**Comment by waltervl** [comment]
No feedback
