### ISSUE TITLE
MQTT AD - Add number type sensors

### ISSUE THREAD

**Issue by Tigerstrength** [domoticz/domoticz#5550]
Hi,

I am using the Domoticz MQTT Auto Discovery plugin for communicating with my Nefit Enviline heatpump. In the Enviline there is a EMS-ESP module for handling the CANBus communication. 

I use a Mosquitto MQTT broker and Domoticz 2022.2 as backend. Al runs smooth, but recently I noticed missing some sensors which Home Assistant users did have and I had not. Digging into it I found out that Domoticz does not support the number type mqtt messages. That is why Domoticz users are missing out a lot of usefull sensors when using the EMS-ESP software.

From the domoticz files I see only these sensortypes are supported for MQTT autodiscovery (MQTTAutoDiscover.cpp):
`
(pSensor->component_type == "sensor") || (pSensor->component_type == "binary_sensor") || (pSensor->component_type == "switch") || (pSensor->component_type == "light") || (pSensor->component_type == "lock") || (pSensor->component_type == "select") || (pSensor->component_type == "cover") || (pSensor->component_type == "climate")`

An example of a discovery message which is published to _"Nefit/number/ems-esp/boiler_hphystcool/config"_
`{
  "uniq_id": "boiler_hphystcool",
  "object_id": "boiler_hphystcool",
  "command_topic": "ems-esp/boiler/hphystcool",
  "step": 5,
  "min": 50,
  "max": 1500,
  "stat_t": "ems-esp/boiler_data",
  "name": "On/off hyst cool",
  "val_tpl": "{{value_json.hphystcool}}",
  "unit_of_meas": "K*min",
  "dev": {
    "ids": [
      "ems-esp-boiler"
    ]
  }
}`

Is it possible to add support for these sensors? 

I also made a issue on the EMS-ESP github page, as they claim to be fully compatible with Domoticz. They conclude it is a Domoticz issue :) [https://github.com/emsesp/EMS-ESP32/issues/904]

Thanks in advance.

**Comment by gizmocuz** [comment]
Well the 'number' types are used for configuration as you have seen
Configuration is done in the web interface of Zigbee2MQTT/ZWaveJS-UI and maybe it would be good if this was also supported for your ESP device

It is still on the to-do list, but has very low priority as most can be done via the web page

**Comment by Tigerstrength** [comment]
Can you point me in to the right direction as to where in e.g. ZWaveJS2Mqqt these settings are? I can't find the settings you are refering to? Altough I suspect you mean the "topic type" menu? 

If I know what you do mean then I will discuss it with the EMS-ESP project. Still I think it is a good idea to implement this to be more compliant with mqtt AD and prevent drifting too far from the MQTT AD - HomeAssistant integration.

![afbeelding](https://user-images.githubusercontent.com/73911269/212980211-2c2a47f9-a985-4fd6-b6f3-60a1669f3754.png)

**Comment by gizmocuz** [comment]
How to change a node setting in zigbee2mqtt? Just select your node and go to settings?

**Comment by Tigerstrength** [comment]
Hi Gizmocuz,

Maybe it is a good idea to leave this open for a future milestone? You are right, it is possible to work arround the unsuported number sensors when using Zigbee2mqtt or Zwavejs2mqtt. But it is still not possible when using the EMS ESP node I started this question with. That project did add a workaround on the roadmap, but that doens't take away the request for number sensor type support in Domoticz. 

Up to you, but I still hope Domoticz will support this in a future release to be fully compliant with the autodiscovery plugin.

Thank you so far :)

**Comment by gizmocuz** [comment]
The Auto Discovery hardware in Domoticz was made for Zigbee2MQTT and ZWaveJS2MQTT.
Now everybody wants to use it, fine of course, but things take time to implement.
I will re-open the issue and see what can be done about this

**Comment by gizmocuz** [comment]
In beta **15112** I implemented support for the number (config) types.
In the hardware setup, next to your MQTT hardware name, you should see a 'Setup' button
If you press this, you will see a table with all numbers that have been received and can be changed

When updating a number, this has to be send to the actual node. If it is a powered node, this is almost instantly done.
But if it is a battery node, it could take a while

Most number values are received when the node is started, the configuration however could be persistant
Meaning, some values might be 'unknown', this means, no current value is received yet.
So be careful when you set it to a new value

I have only one device that has numbers, so hope all is working well.

**Comment by Tigerstrength** [comment]
Tested it today and it looks as you expect it to be. 
![numbers_mqtt_test](https://user-images.githubusercontent.com/73911269/222980183-92f90a54-f3f7-414b-9f56-561aad2ec9b2.jpg)

As you can see a lot of numberic sensors are found. Only thing now is to map it to a actual sensor/actuator in Domoticz I guess? Or can that allready be done?

edit: it seems like changing the value and then sending it has no effect. I get no error in the log, but the value is not updated. It is a always online ESP32 device talking trough Mqtt, so no sleeping issues or anything. Tried it with HA to confirm and that still works ok.

**Comment by gizmocuz** [comment]
Could you post a config topic and payload for a number value that is not being updated?
Did you press the refresh button after a few seconds (probably you did, but just asking to be sure)
Is the source code available for the ESP32? Then I could test even better

**Comment by Tigerstrength** [comment]
The source is avaliable here: (https://github.com/emsesp/EMS-ESP32)
And the issue is mentioned there as wel: [https://github.com/emsesp/EMS-ESP32/issues/904]

As an example, here is the autodiscovery topic for the min.outside temparature for silent mode:
```
{
  "uniq_id": "boiler_mintempsilent",
  "object_id": "boiler_mintempsilent",
  "command_topic": "ems-esp/boiler/mintempsilent",
  "step": 1,
  "min": -126,
  "max": 126,
  "ic": "mdi:coolant-temperature",
  "stat_t": "ems-esp/boiler_data",
  "name": "Min. outside temp. for silent mode",
  "val_tpl": "{{value_json.mintempsilent}}",
  "unit_of_meas": "°C",
  "dev": {
    "ids": [
      "ems-esp-boiler"
    ]
  }
}
```

And for On/Off hyst heat:

```
{
  "uniq_id": "boiler_hphystheat",
  "object_id": "boiler_hphystheat",
  "command_topic": "ems-esp/boiler/hphystheat",
  "step": 5,
  "min": 50,
  "max": 1500,
  "stat_t": "ems-esp/boiler_data",
  "name": "On/off hyst heat",
  "val_tpl": "{{value_json.hphystheat}}",
  "unit_of_meas": "K*min",
  "dev": {
    "ids": [
      "ems-esp-boiler"
    ]
  }
}

```
Do you need more info?

**Comment by gizmocuz** [comment]
No thanks, will test with this. Next time please also copy/paste the complete topic name

**Comment by gizmocuz** [comment]
@Tigerstrength , is it possible you can try beta 15119
I used the wrong object id internally.
Now also added min/max/step support

**Comment by Tigerstrength** [comment]
Tried to pull the latest beta docker, but I get beta 15122. Will try again later today.

**Comment by gizmocuz** [comment]
Yea that’s also good, higher numbers are always better 😀

**Comment by Tigerstrength** [comment]
Ah offcourse, my mistake :) 

I tested it again and now the numbers are updating nicely. Nice job!

I do notice some rounding issues: "tempdiffheat": 3.7  -> shows -> 3.7000000000002
![numbers_mqtt_test](https://user-images.githubusercontent.com/73911269/223365008-a0a45bfa-e297-40fa-bac8-efd1d6db3032.jpg)

Edit: Also I notice that the stepsize for entering the new value is always '1'. So 2 -> 3 -> 4, but some numbers suppose to have a step size of 0.1 (e.g. 2.1 -> 2.2 - > 2.3 ... ) or 5 (e.g. 0 -> 5 -> 10 ...) Maybe you can add this information aswel? It is shared in the MQTT config topics.

**Comment by gizmocuz** [comment]
Please try beta 15130, this should solve the decimal issue and it is also possible to increment with a not rounded step size

**Comment by Tigerstrength** [comment]
Once more you fixed it! It works perfect now 👍 

I do see that controlling also allready works using a GET call: http://x.x.x.x:8080/json.htm?type=command&param=mqttupdatenumber&idx=2&name=boiler_tempdiffheat&value=3.6 

The last thing is being able to map it to a sensor/actuator in domoticz. Or is that possible allready and me not knowing it? I use this e.g. for controlling my heatpump's hysterese and silent temperature from DzVents based on outside temperature and other variables. This value then needs to be shown on my dashboard with a numberic device.

**Comment by gizmocuz** [comment]
Not sure what you mean by mapping the sensor/actuator?
Most things are possible via dzVents

**Comment by Tigerstrength** [comment]
Here is what I am looking for. This is currently done using an external Python script calling the API, but now you have implemented the MQTT support I need to make these switches/thermostat etc. controlling the MQTT number commands and reflecting the status which is received from MQTT. Non number sensors turn up as a device on Autodiscovery in Domoticz, but number types not yet.

![numbers_mqtt_test](https://user-images.githubusercontent.com/73911269/223797652-4407c7ac-c375-4d6f-ac86-c3362ac78801.jpg)
![numbers_mqtt_test2](https://user-images.githubusercontent.com/73911269/223797729-c2a8182a-ac0d-42d7-809f-ed34767369a5.jpg)


I can make a workaround by catching these virtual sensor values and sending them by the GET call using DZVents, but that it not the cleanest solution :) 

Just for reference - I am a Domoticz minded user  👍 - here is how HA combines these sensors.

![numbers_mqtt_test3](https://user-images.githubusercontent.com/73911269/223796401-cfaa73a6-899f-4fab-bc40-e19be4d6796c.jpg)

**Comment by gizmocuz** [comment]
Number devices will not become available as sensors in Domoticz. They are meant for configuration.
You can open the developer console to check out the JSON command that is being send to update the value
You can create a room plan and put all the sensors for this node in here.

Closing this issue as I think implementing the number/configuration is complete. 👌👍
