### ISSUE TITLE
MQTT autodiscovery - child_lock dont work

### ISSUE THREAD

**Issue by MarkKoshelev** [domoticz/domoticz#5552]
The property child_lockhas values LOCK UNLOCK.
AD in domoticz creates switch for this property
Switching  to "on" state domotics send MQTT message.
The message from domoticz looks like correct, the termostat goes to locked state
But switch state in domoticz stay in "off" state.
It is impossible to unlock the thermostat after it was locked from domoticz 
termostat vendor: TuYa
model: tuya-x5h-gb-b
AD message
[ad_thermostat_child_lock.txt](https://github.com/domoticz/domoticz/files/10461234/ad_thermostat_child_lock.txt)
state message
[thermostat_child_lock.txt](https://github.com/domoticz/domoticz/files/10461249/thermostat_child_lock.txt)

**Comment by gizmocuz** [comment]
@MarkKoshelev , it seems your devices is not reporting back the new set state.
Is it possible to verify this?
Thank you for the payload of the config/state topic, could you also report the topics complete names?

like for the config payload
`<discovery_prefix>/<component>/[<node_id>/]<object_id>/config`

**Comment by MarkKoshelev** [comment]
> @MarkKoshelev , it seems your devices is not reporting back the new set state. Is it possible to verify this? Thank you for the payload of the config/state topic, could you also report the topics complete names?
> 
> like for the config payload `<discovery_prefix>/<component>/[<node_id>/]<object_id>/config`

I see state topic as attached. It has valid child_lock value. 
"child_lock":"LOCK"
full config topic: z2m-gw1/climate/0xa4c13824a001e548
full state topic: z2m-1/LivingRoom1
All other properties of thist thermostat work correctly.

**Comment by MarkKoshelev** [comment]
I see that switch type for "child_lock" is "on/off", All other switches are "selector" type. 
Could this be a problem?

**Comment by gizmocuz** [comment]
Are you sure there is not also a /switch or /binary topic type?
In MQTT Explorer, when you search for 0xa4c13824a001e548 does it find more configs?
(just to be sure)

**Comment by MarkKoshelev** [comment]
> Are you sure there is not also a /switch or /binary topic type? In MQTT Explorer, when you search for 0xa4c13824a001e548 does it find more configs? (just to be sure)

Almost sure
It is possible to do such experiment: put to domoticz attached config  topic?
I have deleted the thermostat in domoticz, restart z2b bridge,  the new thermostat have been created. MQTT explorer catch only attached config message.

**Comment by gizmocuz** [comment]
If you want to be sure, perform the above action

**Comment by MarkKoshelev** [comment]
Done
topic 
z2m-gw1/lock/0xa4c13824a001e549/child_lock/config
message
{"availability":[{"topic":"z2m-1/bridge/state"}],"command_topic":"z2m-1/D1-LR/set/child_lock","device":{"identifiers":["zigbee2mqtt_0xa4c13824a001e549"],"manufacturer":"TuYa","model":"Wall-mount thermostat (X5H-GB-B)","name":"D1-LR"},"json_attributes_topic":"z2m-1/D1-LR","name":"D1-LR child lock","payload_lock":"LOCK","payload_unlock":"UNLOCK","state_locked":"LOCK","state_topic":"z2m-1/D1-LR","state_unlocked":"UNLOCK","unique_id":"0xa4c13824a001e549_child_lock_z2m-1","value_template":"{{ value_json.child_lock }}"}


creates "on/off" switch

**Comment by gizmocuz** [comment]
Thanks, this information was helping.
I think its now solved it in beta 14993
