### ISSUE TITLE
Netamo password not correctly sent starting with Domoticz V2022.2

### ISSUE THREAD

**Issue by jpcasta** [domoticz/domoticz#5553]
Hello,

Starting with V2022.2, the Netatmo password is no longer sent correctly for authentication.
The error is: Error: Netatmo: No access granted, check username/password...
It works correctly with V2022.1.
Is there a limitation in the characters that have to be used in the password or is it a bug that appeared in the new version?

Thanks.

**Comment by waltervl** [comment]
There are lots of forum topics on this. see for example https://www.domoticz.com/forum/viewtopic.php?p=297544#p297544

**Comment by jpcasta** [comment]
OK, I already read these topics and I understood if I change the password, it could work, but that does not explain me why it worked before and why it does not work with 2022.2. 
It is the reason I opened this issue to try to get an explanation.
That means there is a change that modified the behavior of the authentication and then there is now a limitation of the characters that have to be used?
Thanks

**Comment by waltervl** [comment]
There has nothing really changed on Netatmo on this part from 31 jan to november 2022 (delta of 2022.1 to 2022.2). You can check yourself: https://github.com/domoticz/domoticz/commits/development/hardware/Netatmo.cpp

**Comment by jpcasta** [comment]
OK....but something has changed may be due to another modification in the code because it worked for years and when I install 2022.2 it does not work without any change regarding Netatmo.
And as you wrote before I am not alone getting this issue.
Thanks

**Comment by waltervl** [comment]
Please continue in the forum topic. It seems the issue is solved by resetting your password.
