### ISSUE TITLE
Device delete only works 1 at a time

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#5554]
Domoticz release 14922 on linux AMD64

In the devices tab, when selecting more than 1 device and trying to delete them, they are not deleted.
The delete function works fine if you select only 1 device at a time.
When selecting more than 1 device, the confirmation message (x devices deleted) never shows up and no device is removed.

**Comment by waltervl** [comment]
Did you try this in a private/incognito browser session? Seems a caching issue.

**Comment by waltervl** [comment]
I do not have this issue in 2022 stable and beta (14975).

**Comment by Olivier6767** [comment]
Sorry for the delay for replying.
I tried again on 2 different machines, with Chrome and Edge browser, after clearing the cache,  and also in incognito mode.
I also tried on Safari on iOS.
I confirm the issue happens every single time.

I usually order the device list by Idx, in reverse order (new ones first).
I then select a few 'phantom' devices (Z-Wave) and hit the trashcan icon on top.
I get the message : Are you sure you want to remove.... with the number of select devices in parenthesis.
When I hit ok, I never get the confirmation popup and the devices are still in the list.

**Comment by gizmocuz** [comment]
No issues here, not has this been changed for years.
Are you sure you are doing this with a user with Admin rights?

**Comment by Olivier6767** [comment]
After more testing, it looks like the issue happens when I access Domoticz though my reverse proxy (Traefik).
When accessing Domoticz directly it works as expected.

There is a [known issue](https://github.com/traefik/traefik/issues/9164) with Traefik and Domoticz, related to URL parameters separated by semicolon, where the semicolon is not URLencoded.

**Comment by kiddigital** [comment]
@Olivier6767 , can you check in the Dev tools of your browser how the URL looks like when pressing the button?

Maybe we can properly URL encode the data before sending it in the UI. That would circumvent the Traefik issue.
See earlier #5313 and #5311.

**Comment by Olivier6767** [comment]
Here is the request when selected 2 devices (1105 and 1106)
`http://domoticz.home.com:7080/json.htm?idx=1106;1105&type=deletedevice`

**Comment by gizmocuz** [comment]
The above URL looks perfectly fine. I also tested with sending it encoded

`http://127.0.0.1:8080/json.htm?idx=1106%3B1105&type=deletedevice`

This is also handled correctly inside Domoticz.

The function that is called resides in domoticz_api.js and is called '**removeDevice**'
Which is calling **$httpParamSerializer**
So I don't expect it to be a URL encoding issue

You can enable the debug level for the webserver to see if anything strange is send

`-debuglevel webserver`

You will probably get a lot of logging

**Comment by kiddigital** [comment]
@gizmocuz , the problem for @Olivier6767 is that if the multiple deviceIdx are sent without being URLencoded, Traefik (as proxy) alters the URL parameter leaving only 1 device idx.

The solution for this issue is to URLencode the parameters in the front-end before sending it to the back-end (through the proxy).

I already created a small fix for it, just didn't have the time to make the PR and merge it. Will do asap.

**Comment by gizmocuz** [comment]
I think everything is correctly encoded with $httpParamSerializer

**Comment by Olivier6767** [comment]
@kiddigital, you are correct, the URL must be encoded on the client side before it is sent to the proxy.
Otherwise the proxy will remove the parameters as in 'interprets' the semicolons.

**Comment by gizmocuz** [comment]
@Olivier6767 , did you had a look at the function I mentioned and also the documentation of $httpParamSerializer?
Not only we use this for sending a few device indexes but also we use it to send complete json objects
I tested this also with both Apache and NGINX proxies servers.
Using nginx-proxy myself (via docker-compose)

**Comment by gizmocuz** [comment]
@Olivier6767 , is it possible to make the changes from kiddigital's fix to your local installation to see if this solves the problem?
You might need to clear your browser cache after making the changes.

**Comment by Olivier6767** [comment]
@gizmocuz, sorry but my setup uses pre-compiled binaries, it is not setup for compiling the CPP code, so I'm afraid I can't make this code change on my setup.
Concerning nginx-proxy, I have no doubt that it works fine. The issue with the semicolon in the URL arguments being interpreted is clearly an issue with Traefik only.

**Comment by kiddigital** [comment]
@Olivier6767 , in case you are running Linux you could use the artifact from the PR test build.

**Comment by Olivier6767** [comment]
I'm on linux (docker), however I'm not familiar with how to retrieve the build from the PR test... Can you provide some guidance?

**Comment by kiddigital** [comment]
Look at the PR on github. Go to 'checks' and look for 'artifacts' button/link.

This provides a download of a zip file containing a Linux tar-file in which the binary and www-folder can be found.

**Comment by gizmocuz** [comment]
Is it possible to test beta 15045 to see if this solves the problem?

**Comment by Olivier6767** [comment]
@gizmocuz 
I tested beta 15045 and the issue still persists...
The request url is:
`https://domoticz.<my proxied domain>.com/json.htm?idx=1106;1105&type=deletedevice`

The response is:
```
{
	"status" : "ERR"
}
```

After clearing the browser cache and trying again, the delete works for the 2 devices!
Request:
`https://domoticz.<my proxied domain>.com/json.htm?idx=1106%3B1105&type=deletedevice`
Response:
```
{
	"status" : "OK",
	"title" : "DeleteDevice"
}
```

Thanks!

**Comment by Olivier6767** [comment]
@kiddigital
I struggle to test the PR using the artifcats. I'm running a Ubuntu docker and I have some issues with the binary release form the 'artifcats'.

**Comment by kiddigital** [comment]
> @kiddigital
> 
> I struggle to test the PR using the artifcats. I'm running a Ubuntu docker and I have some issues with the binary release form the 'artifcats'.

What is the exact problem? You should be able to use the binary by just replacing it (and make sure it is executable).

But no need to test the PR build anymore as the PR has been merged into the Beta.

Just test the latest Beta and let us know if the problem is solved (make sure to clear the browser cache).

**Comment by Olivier6767** [comment]
@kiddigital
I tested Beta 15045 and confirm the delete now works fine with multiple IDs (after cache clear) through the Traefik reverse proxy.
See above response to @gizmocuz with URL Request and Response.
