### ISSUE TITLE
small fan icon not found.

### ISSUE THREAD

**Issue by cgrijs** [domoticz/domoticz#5556]
### Issue Guidelines

I have a westinghouse type fan that shows up fine in the 'Switches' tab, but shows a broken icon in the Floorplan-dashboard view. The link is to '/images/fan48_On.png' (lowercase 'f') while the actual file is named '/images/Fan48_On.png' (uppercase 'F').

I am running domoticz on a RPi with raspbian buster,
Domoticz Version: 2022.2 (build 14980)
Build Hash: c9dfee64c
Compile Date: 2023-01-21 07:39:22
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]

**Comment by gizmocuz** [comment]
Thanks for noticing. I think it's because the image in the images folder had a capital letter F.
Hope it's solved in beta 14982

**Comment by barts2108** [comment]
Just updated to build 15005 .. many icons look missing, but according to the debug console there seems only one missing: **undefined48_On.png**

![image](https://user-images.githubusercontent.com/520875/214385939-7c5cd38b-1528-49c3-ae28-1b159baa0846.png)


![image](https://user-images.githubusercontent.com/520875/214386124-df8b0ce1-3edf-4535-9dbd-eb403bb4241d.png)


EDIT: All my heater thermostat valve opening has now a light bulb as icon (it must be a default). 
![image](https://user-images.githubusercontent.com/520875/214387021-3c82c1dc-a2df-42af-98a5-9d423bfe9c55.png)

Editing the heater valve opening first shows this:
![image](https://user-images.githubusercontent.com/520875/214387180-1b9653c1-4ac5-4256-8ef6-5ed1ac73e37a.png)

Where I expected this
![image](https://user-images.githubusercontent.com/520875/214387279-fa91a6e4-e042-4bf1-9bc1-2738654a8ba6.png)

Hoever when I change it (save it after setting the round default icon) nothting changes, and the icon remains at light bulb.

Everything in the browser has been reloaded multiple times with Crtl+F5 and even Disable Cache in the developer tools

**Comment by gizmocuz** [comment]
Solved in beta 15006
