### ISSUE TITLE
Switches Missing and can't add new ones ONLY with webui   item.Image error 

### ISSUE THREAD

**Issue by frenchyyii** [domoticz/domoticz#5558]
Hi,
Last and older Beta various tested. Cache and appcache cleared 
Pbm only with chrome/Firefox even on MobilePhone
No Pbm with DZ on Android App

Many of my switches are missing and each time I add one it doesn't appear on web ui (but ok on DZ premium android app)
Switches are existing and working on device list.

In consoles (chrome/firefox), seems to have a problem with js, in LightsController.js  line 1007

item.Image = item.Image.charAt(0).toUpperCase() + item.Image.slice(1);

May easily be my fault !!!  (and I've tryed to fix by myself and maybe with mistakes)

As I'm french and not informatician...please try to be simple and apologise by advance
Thanks
Eric 
![Capture d’écran 2023-01-22 183056](https://user-images.githubusercontent.com/73781793/213931269-20527ada-6d37-4b59-8801-9538fa316bca.jpg)
![Capture d’écran 2023-01-22 183613](https://user-images.githubusercontent.com/73781793/213931271-0c2232b0-862b-4c25-9f7c-3875e7e74781.jpg)

**Comment by gizmocuz** [comment]
What do you mean by "may easily be my fault'? Did you called some JSON functions or was experimenting with the database?
It looks like item.Image is not defined.
What happens when you comment out this line by placing to slashes in front of it ( // )
Of course this is not a solution but maybe it is just this dimmer switch

**Comment by frenchyyii** [comment]
Thanx for your reactivity.
If I comment only the 1007 line switches I had a message concerning "undefine" were coming, I created a False "undefined" custom icon and it helps. Switches back and I could add and see them again !! Very Good
The problem seemed to com from Dimmers (And RGBW+RGBWW ) as they do not have Logo, but even with this comment they were active.
Uncommenting back make switches disappearing again...

I got troubles with Icons but can't find the way to solve it.
I have also tried to check and repair database but no difference... could it be broken somewhere ?

Here are the messages with and the without comments   (**u**ndefined custom icon present)

If necessary I can give you an access to the database or even a teamviewer .
Thanks for your help

![Capture d’écran 2023-01-23 171741](https://user-images.githubusercontent.com/73781793/214092661-2f2c77a5-0517-4e8f-9108-4434894c690b.jpg)
![Capture d’écran 2023-01-23 171851](https://user-images.githubusercontent.com/73781793/214092665-0abc7e78-033c-4626-82c4-473d1eb4e746.jpg)

**Comment by gizmocuz** [comment]
Could you contant me on our Slack channel (send me a private message)
Please send me a backup from your database (settings->backup)

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

**Comment by gizmocuz** [comment]
Somehow the CustomImage was set to a ID that did not exists.
Made a fix that checks against this in the cpp/js code

**Comment by erkikoiv** [comment]
Hello,
I have an issue with my Domoticz (v 2023.1). For some time I cannot add any new switches. They are visible under Devices but not under Switches page. Any suggestions, what might be wrong and how to fix it?

**Comment by gizmocuz** [comment]
@erkikoiv , no reason to create two issues on github, let's continue there
