### ISSUE TITLE
python code suddenly not working

### ISSUE THREAD

**Issue by lambertmular** [domoticz/domoticz#5559]
The problem was previously reported here [https://www.domoticz.com/forum/viewtopic.php?p=298198#p298198](url)

The following simple python code gives me an error

```
import DomoticzEvents as DE
import re

es=list(map(float,re.findall("(\d+\.?\d+);(\d+);(\d+)",DE.Devices['Temp Chambre'].s_value)[0]))
DE.Log("Python:"+str(es))

def data_meteo(name):
    return list(map(float,re.findall("(\d+\.?\d+);(\d+);(\d+)",DE.Devices[name].s_value)[0]))
    
dat=data_meteo('Temp Chambre')

DE.Log("Python:"+str(dat))
```

gives me the following error (regex) at the output

`2023-01-08 15:28:23.348 Python:[17.7, 75.0, 3.0]
2023-01-08 15:28:23.350 Error: Traceback (most recent call last):
2023-01-08 15:28:23.351 Error: File "Script #1", line 10, in <module>
2023-01-08 15:28:23.351 Error: File "Script #1", line 8, in data_meteo
2023-01-08 15:28:23.351 Error: NameError: name 're' is not defined `

I checked the code in my pi using python and it works. Only in domoticz it does not work. It seems like a bug. I buy a new SD card and reinstalled everything but the problem is still present.

**Comment by gizmocuz** [comment]
Please use the forum

**Comment by lambertmular** [comment]
it has already been raised on the forum and no solution was found. The problems seems to be within domoticz itself.
I also did a full rebuild to solve it and nothing worked. Please consider this, this is a real bug.

**Comment by pipiche38** [comment]
you need to make sure that the re module is installed under root

sudo python3 -m pip install re --upgrade

**Comment by soinipe** [comment]
Can be reproduced with python code:
```
def make_handler_name(s):
    # A few special characters replaced
    s = s.replace(',', '_')
    s = s.replace('-', '_')
    s = s.replace('ä', 'a')
    s = s.replace('Ä', 'A')
    s = s.replace('ö', 'o')
    s = s.replace('Ö', 'O')

    # Remove invalid characters
    import re # Needed due problem https://domoticz.com/forum/viewtopic.php?t=39713 and https://github.com/domoticz/domoticz/issues/5559
    s = re.sub('[^0-9a-zA-Z_]', '', s)

    # Remove leading characters until we find a letter or underscore
    s = re.sub('^[^a-zA-Z_]+', '', s)

    # Add prefix, no need to care about Python reserved words
    return "handler_" + s
```
The above code works but stops working if extra `import re` is removed.

Tested with 
```
commit 9e8fe8ee4abc5ee647b4c08720ea11f3e0c9de5a (HEAD -> development, origin/development, origin/HEAD)
Author: Rob Peters <Info@Domoticz.com>
Date:   Sat Oct 28 16:13:25 2023 +0200
```
Ubuntu 22.04, Python 3.10.12 

The same code was working with ancient Domoticz V4.10276
```
commit 7245e9b25c085c949b1e2643821f33c10f53c353 (HEAD -> development, origin/development, origin/HEAD)
Author: Rob Peters <info@domoticz.com>
Date:   Fri Dec 14 08:38:51 2018 +0100
```

**Comment by gizmocuz** [comment]
@soinipe , please use our forum
