### ISSUE TITLE
hardware: i2c: reference to read_reg array is lost when calling ioctl() in ReadInt(), WriteInt()

### ISSUE THREAD

**Issue by nicogrx** [domoticz/domoticz#556]
Hello guys, I found an issue (and corresponding Fix ;) in hardware/I2C.cpp file:

In both ReadInt(), WriteInt() methods, "read_reg" array is declared inside a local block.
So the reference is lost when calling the ioctl() which then returns -1 with errno = 22 (since argument is invalid).

Attached the patch with the fix. With my best regards. Jean-Nicolas.

[0001-hardware-i2c-Fix-weird-declaration-of-read_reg-array.patch.txt](https://github.com/domoticz/domoticz/files/168260/0001-hardware-i2c-Fix-weird-declaration-of-read_reg-array.patch.txt)

**Comment by gizmocuz** [comment]
Thanks, i hope i patched the file correctly.
If possible, could you make a git pull request in the feature ?
(it looked the file was patches locally, but git did not see any changes, had to do some strange things to the file to get it accepted, it looks ok in the repository now)

**Comment by nicogrx** [comment]
Hello, Sorry for using the 'issue' tab.
Sure I will consider 'git pull' in the future provided I am something to pull ;).
When I will have some time free, I will fetch the head and rebuild & check it works fine with my banana pi + BMP180 sensor.

Thanks!

**Comment by nicogrx** [comment]
Hello!
As promised, I took current HEAD (387254e), rebuilt & did a quick test on my hardware setup.
BMP180 is working fine. Of course I cannot test the "HTU21D" alternative.
Regards. JN.

**Comment by gizmocuz** [comment]
Thanks!

**Comment by nicogrx** [comment]
You are welcome ;)
