### ISSUE TITLE
no zwave mqtt updates after build 14964

### ISSUE THREAD

**Issue by herm42** [domoticz/domoticz#5561]
Hi,

after upgrading to the latest dev version (from build 14964) i do not receive node updates anymore. any idea what could be wrong here? after switching back to 14964 everything is o.k. again.

zwave-js-ui 8.7.0/10.3.1 <--> mosquitto <--> domoticz

**Comment by gizmocuz** [comment]
I just setup a system from scratch. (Latest Domoticz beta 14983)
zwavejs-ui version: 8.6.3

Both via docker compose

I have no issues, all is working perfectly fine

But, make sure the automatic discovery prefix/topic (aka homeassistant or domoticz or something else) is DIFFERENT than your MQTT prefix/name
They are two different things (and settings)

**Comment by herm42** [comment]
thx for the prefix hint ... changed the mqtt prefix and it worked again on the newest builds ...

thx!
herm
