### ISSUE TITLE
Domoticz Error log shows message, every 5 minutes, when OTGW+MQTT is in use

### ISSUE THREAD

**Issue by 0crap** [domoticz/domoticz#5562]
I'm running Domoticz 2022.2 stable on a Raspberry Pi 3.
I configured with "Setup->Hardware"  a "MQTT Auto Discovery Client Gateway with LAN interface"
The Auto Discovery Prefix is "homeassistant" (Sorry for that.) ;-)
This connects to my MQTT broker just fine. (Works already for ages.)

Recently I added an [OTGW](https://www.nodo-shop.nl/nl/ons-assortiment/211-opentherm-gateway.html) to my boiler. (Hardware V2.8 + PIC version 6.4)
Basically an OpenTherm sniffer.
On the OTGW I configured the MQTT client and use the Auto Discovery Prefix "homeassistant".
All fine, the OTGW is found by Domoticz (via MQTT) and all sensors are shown, perfect.

Problem is that with the OTGW addition I now receive, every 5 minutes, a message in my Error log, coming from the  "MQTT Auto Discovery Client Gateway with LAN interface".
![Errors](https://user-images.githubusercontent.com/31951195/214131494-28ca5c49-226d-4ffd-89ab-e8fe3da5fe50.png)

I discussed this already with the OTGW developer and we came to the conclusion the Error message should not appear in Domoticz.
The OTGW is sending at the moment the error is seen (every 5 minutes), the following to the MQTT broker:

/*
Publish state information of PIC firmware version information to MQTT broker.
*/
void sendMQTTstateinformation(){
  sendMQTTData(F("otgw-pic/boiler_connected"), CCONOFF(bOTGWboilerstate)); 
  sendMQTTData(F("otgw-pic/thermostat_connected"), CCONOFF(bOTGWthermostatstate));
  sendMQTTData(F("otgw-pic/gateway_mode"), CCONOFF(bOTGWgatewaystate));
  sendMQTTData(F("otgw-pic/otgw_connected"), CCONOFF(bOTGWonline));
  sendMQTT(CSTR(MQTTPubNamespace), CONLINEOFFLINE(bOTGWonline));
}

Quote from the OTGW dev:

"The last line of this is actually updating the status of the ESP8266, that way the Home Assistant knows about the status. It sends online or offline status, so that Home Assistant can determine the status of the ESP8266 (device).

Now having said this, it seems that Domoticz seems to want `ON` or `OFF` and not `online` or `offline`. If that is the case, then Domoticz is not implementing the keywords correctly.

Now I have no way of validating this myself... Hmmm, wonder how we could test this assumption from my end that this is the explanation."

I hope this gives enough info to take a stab at this issue.
If anything more is needed, please let me know.

Thx!

**Comment by gizmocuz** [comment]
It all depends on the config of this node

Could you use MQTT Explorer and post here the (all) config topics (name) and the payload (json)
Also the full topic (name) of the payload and it's contents

It seems the OTGW is using different topics for its states so it will be a lot of copy/paste

**Comment by 0crap** [comment]
Thx for responding.
I think I understand what you are asking for.

With MQTT explorer I focused on the timestamp and the 5 minute repetition from the errors on the Domoticz Error log.
The below screenshot shows possible offenders. They are all at the exact same timestamp and repeat every 5 minutes.
I can't better differentiate between them, because of the exact same timestamp. 
Let me know if this helps.

![MQTT_explorer](https://user-images.githubusercontent.com/31951195/214285193-2dbcf656-4153-4253-80ba-7e868a368194.png)

**Comment by gizmocuz** [comment]
Thanks for the screenshot but this does not help 😁
I need the information that I requested above

So, inside MQTT explorer, highlight the config topic (you might have multiple), from the right press the 'copy' icon, and past that here
Next also paste the contents (value) of the config topics and post that here
Then do the same for the otgw-pic, copt the topic, post it here, and the value as well

If you have a debian/linux system, you can also run the mqtt_ad_record.sh script which you can find in the scripts/support/mqtt_ad folder

And you could run domoticz with a command line option to enable hardware debugging that also provides logging

**Comment by 0crap** [comment]
OK, you got to love questions like this. :-)
Lot of copy and paste indeed, but here are the config topics.
https://pastebin.com/q7mCRiD2

Let me start on the second part...
And here you go.
https://pastebin.com/zdcP5sJF

Hope this is what you asked for.

**Comment by gizmocuz** [comment]
Yes perfect! Thanks! I have a look soon, but with this we can replicate your OTGW (MQTT)

**Comment by gizmocuz** [comment]
I found the issue.

The reason is that this devices is using templates that Domoticz does not support like:

"action_template": "{% if value == 'ON' %}heating{% else %}idle{% endif %}",

"mode_stat_tpl": "{% if value == 'ON' %}heat{% else %}off{% endif %}",

Not sure why this device needs it and does not just send 'heat' or 'off' to the mode state value

Some optimizations could also be made when it was using json values (one object with all values)

I will have a look to try if I can support these templates

Can you also operate this device by TCP? (connecting to a port), because domoticz does support the OTGW natively by serial/tcp

if it is the same device (or uses the same protocol) as

http://otgw.tclcode.com/firmware.html#operation

**Comment by 0crap** [comment]
Awesome find!
What I believe to be true is that initially the OTGW MQTT implementation was designed in combination with HomeAssistant.
My guess is that is why you see these templates.
I'll point the OTGW dev to this issue so he can read along and maybe shed some light on it.

And yes, I have tested the OTGW with the native Domoticz serial/tcp interface.
This works, but this native interface sends a PS=1 to the OTGW (legacy stuff) and that cripples other functionality.
IMHO Domoticz should redesign (abandon) this legacy serial interface, but that is a different discussion.
So MQTT is the best way to go at the moment.

(And yes, that link you provided is the PIC firmware currently running on the OTGW.)

**Comment by rvdbreemen** [comment]
@gizmocuz that a good find, never realized that this might be the cause of the issue. The "template" that is being send is indeed needed to the integration into Home Assistant. The whole point of this OTWG ESP firmware was the integration with Home Assistant indeed, as @0crap suggests, and the focus had long been on making sure that works well.

The simple answer here for Domiticz integration, you can just remove those lined from the configuration file that comes with this ESP firmware. That way they will never be send, and thus do not need implementation for Domoticz. #dirtyfix

The function was added for SAT (a standalone automatic thermostate) device that has been build in Home Assistant based on top of the MQTT integration.

The whole point is to provide a richt MQTT based integration, you can always fallback to the 'native' serial interface integration, and as pointed out the PS=1 kills of some realtime functions for the ESP firmware. I could add an emulation function of the PS=1 function, but I am not sure if I want to go that route.

I have to think about this, any thought on this issue, please here... or join the Discord community to discuss it.

**Comment by 0crap** [comment]
Thx for your comment!

At least we can test the # dirtyfix to see if that solves the issue.
On the OTGW filesystem I retrieved the mqttha.cfg file and pasted it here: https://pastebin.com/90q2eXmw
I hope it doesn't mangle any formatting, if any.
I'm not sure what needs to be edited. Any help is appreciated.

Ohh, I would not go the legacy PS=1 route, a waste of time IMHO and using it breaks nice OTGW functionality.
I'm not going back to that anyway.

**Comment by gizmocuz** [comment]
@0crap , I have been using the OTGW for years and years with the native domoticz implementation.
You can all the statistics and you can control the thermostat.
What else do you need to do with this?
And yes, you can also control the CV with any opentherm supported thermostat at the same time.
With domoticz you can also feed it your outside temperature, a functionality you do not have with MQTT

**Comment by 0crap** [comment]
Fair enough.

True on the outside temp.
I use a cron shell script that feeds in the outside temp by sending it to the OTGW directly.
Only thing that I can't get to work is set an override on the room temp.
Domoticz MQTT sends the temp as a plain number instead of the expected `TT=<temp>` for the OTGW.

**Comment by gizmocuz** [comment]
Yep, so the question is, why is the current Domoticz implementation not working for you?
You have all stats, can control everything with domoticz, and can even connect a smart thermostat

@rvdbreemen , If it is possible to use the actual values (heat/off) instead of sending ON/OFF and translating this via a template back to heat/off, I am quite sure HASS can also work with this
And I myself would rebuild it to use json so you have one state topic with all information if that is possible

**Comment by 0crap** [comment]
> Yep, so the question is, why is the current Domoticz implementation not working for you? You have all stats, can control everything with domoticz, and can even connect a smart thermostat
> 

For example all the logging and statistics stop in [Opentherm Monitor](https://otgw.tclcode.com/download.html#sources).
Which is quite handy when you just start with this project.
Also the otgw.local homepage stays empty and MQTT does not work anymore iirc.
It's just not what I prefer at the moment.

**Comment by gizmocuz** [comment]
Okey because there is no reason to use the opentherm monitor anymore as you get all details with domoticz and with some great history as well
I see what I can do with the templates, but for now easiest solution is to
- use the native implementation (it's what people use for years and years now)
- adjust the configs so it uses ON/OFF instead of the template to convert it
- adjust the code is esp to use heat/off instead of on/off so the template conversion does not need to take place

I am also not sure if all counters are working correctly with MQTT, I hope to test very soon

**Comment by 0crap** [comment]
An advantage of MQTT is also you receive more OTGW sensors (64 total on my setup) into Domoticz.
Like for example all counters. (e.g. pump starts, pump hours...)
There is more received using MQTT, but I have not checked all of them to see if it's added value.

Anyway, the native implementation is not a solution for this issue.
The other two items suggested are fixes needed on the OTGW part.

So can we conclude to close this issue on the Domoticz side of it?

**Comment by IanDury** [comment]
For what it's worth I'm using a slightly modified version of the plugin https://github.com/proditaki/OTGW-Domoticz-MQTT-Client because I wanted to  be able to use the Opentherm Monitor in daemon mode in parallel with Domoticz so I can look at the graph through a web server (see image below). I first tried using MQTT-AD about a month ago but had some issues like not being able to set the thermostat and IIRC some device types were not recognized correctly (water pressure?). Would be great if MQTT-AD would work with the ESP8266 OTGW firmware.


![Screenshot from 2023-01-25 17-07-00](https://user-images.githubusercontent.com/16663492/214615802-be2facc0-3fed-4575-9897-c2e40426750e.png)

**Comment by 0crap** [comment]
Thx for pointing to that script.

Exactly my point to avoid the native Domoticz implementation.
FYI Auto Discovery works fine with the OTGW and Domoticz.
On the OTGW go to advanced->settings and the field `MQTT Home Assistant prefix` is what you are looking for.
The field label is a bit misleading but this is in fact the MQTT Auto Discovery prefix.

**Comment by IanDury** [comment]
I used that field with prefix "otgwauto" and matched this in the Domoticz MQTT-AD settings. But if you say it works fine for you now I will try it again one of these days.

**Comment by 0crap** [comment]
> Okey because there is no reason to use the opentherm monitor anymore as you get all details with domoticz and with some great history as well I see what I can do with the templates, but for now easiest solution is to
> 
> * adjust the configs so it uses ON/OFF instead of the template to convert it
> * adjust the code is esp to use heat/off instead of on/off so the template conversion does not need to take place
> 
> I am also not sure if all counters are working correctly with MQTT, I hope to test very soon

OK, let's close this one.
Thanks gizmocuz for steering us in the right direction.

I think it's fair to say that the OTGW MQTT implementation is tailored to HA and should be adjusted to at least not throw any errors on other home automation software.
The above suggested points are good leads to achieving that.

Thx all!

**Comment by rvdbreemen** [comment]
I agree with making sure the MQTT message do not cause issues with other Home Automation projects, like Domoticz. So I will go and see what I can do in the next release of my project.

**Comment by gizmocuz** [comment]
@rvdbreemen , is it possible to emulate it so I could help with this? (Domoticz side)
Which sketch do have have to upload to the ESP?

**Comment by IanDury** [comment]
https://github.com/rvdbreemen/OTGW-firmware/blob/main/MQTTstuff.ino

**Comment by gizmocuz** [comment]
Don't think this will load on a ESP8266

**Comment by rvdbreemen** [comment]
No it won't. It's not a single sketch. Just download the binary here:

https://github.com/rvdbreemen/OTGW-firmware/releases

When you flash this to a wemos or nodemcu, you will have a working firmware that will transmit information over mqtt that will cause trouble to Domoticz. 

Hope this does help,
Robert

**Comment by gizmocuz** [comment]
@rvdbreemen , Having issues with this. Never upload a binary.
Tryed two software applications (ESP8266 Flash Download Tool and NodeMCU flasher)
After a restart the led is blinking, so it seems it does still contain my blink test sketch

Does the above mentioned binary produce random data to test with?

**Comment by gizmocuz** [comment]
I received access to someone's MQTT broker, thanks for this!
With this I was able to add initial support for raw (non-json) state templates with if/else/endif

This should be solved in beta 15046

**Comment by gizmocuz** [comment]
I do miss some thermostat setpoint (climate) devices to set the temperature of the domestic hot water, return water etc etc
Are they going to be implemented?

**Comment by 0crap** [comment]
Thx for diving into this, I hope @rvdbreemen can help you with the questions.
