### ISSUE TITLE
Event is not triggered when a zigbee device is manually on the device it self activated.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5563]
Using: Version: 2022.2 (build 14993)
Build Hash: 31cfeefdc
Compile Date: 2023-01-24 08:36:19
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]

I have several devices which I auto shutoff after some time or below certain power consumption by a dzVents script.
The script is working fine for years now.
BUT when I actuate a zigbee device manually on the device it self then Domoticz sets the device to activated, so that seems to work good, but a trigger is not send to the script. That trigger is also not present in the logging.
So the script presumes that the device is still off, so it will never turn of the device.
When I activate the same device in Domoticz the trigger is send and dzVents turns off the device below a certain power or after some time, so the script then works as it should.

**Comment by gizmocuz** [comment]
Before digging into the issue, can I assume you are using zigbee2mqtt?

**Comment by SargonofAssyria** [comment]
Yes, I am. The strange part is that I a used the example device.lua with this device and that one works.
So triggers are received by manual activating but not by my script, but if I activate in Domoticz this script is working as it should.
I am using this script: https://www.domoticz.com/forum/viewtopic.php?p=160725#p160725
And when I manually activate the widget in Domoticz shows the right state.

**Comment by gizmocuz** [comment]
If it's a simple on/off switch, could you make a Blockly event and test this? 
Make sure each device has a unique name (important!)

Not sure what event you are using as I see multiple. If it's about kWh monitoring (Watt), i can tell you that this is 100% working as I use this myself for the dryer and washing machine.
If you want I can post my script in the forum post. It's also using zigbee and two power plugs (they are always on)
When the washing or dryer is finished I send a notification and turn a virtual switch (have 2!) on/off. This triggers again a script (a bash script that announces its ready state trough certain Alexa speakers)

**Comment by SargonofAssyria** [comment]
The device name is unique, I am sure. Please post your script on the forum, then I could compare. But never the less the script works with 7 devices and the same 7 kWh devices. And it works flawless for years now.
With the last device added, which I often activate manually, the Domoticz does not send a trigger to dzVents.
I could test with your script.

**Comment by SargonofAssyria** [comment]
Sorry that I bothered you, but there was a small logic error in my script that caused 1 trigger before an other that caused manual activation of the switch not to be properly trigger the next trigger. I corrected that and it now looks like it function normally.

**Comment by SargonofAssyria** [comment]
There seems to be a difference on the 'on' section in the order of almost the same named devices e.g.
NO trigger
```
            'Handdoek verwarming kWh Meter',
            'Handdoek verwarming',
```
and a trigger
```
            'Handdoek verwarming',
            'Handdoek verwarming kWh Meter',
```
I solved it by changing the order of these kind of devices in the latter.
