### ISSUE TITLE
[Enhancement] Influx push failing - error message needs to be informative enough to find the problem

### ISSUE THREAD

**Issue by jefft4** [domoticz/domoticz#5564]
[Enhancement]
For reasons best known to itself, the InfluxDB push on my system is throwing quite a few of this error:
`2023-01-24` 16:25:02.266 Error: BasePush: Could not determine data push value`

It's not the most helpful of errors ;-) It doesn't tell us which device or value caused the problem.  I see no complaints from domoticz itself about bad values in MQTT messages, so it's unclear what's upsetting the data push code.  I have close to 100 values being pushed to Influx, so going through them one by one to remove/re-add items in order to narrow down the cause, especially when it may be several devices at fault, isn't a fun idea.

Can this error message be altered to add the idx of the device and the name of the attribute that's failing the operation, please?

**Comment by gizmocuz** [comment]
@jefft4 , did you search in the code for 'Could not determine data push value'?

This was very easy to add yourself and create a PR!

Anyway, you can update to beta 15005 and you should see more information.

Please share what goes wrong so we can maybe support it to be pushed (or make a PR to add support for this)

**Comment by jefft4** [comment]
I'll take a look at the beta, thanks. Thought I was already running the latest but...

As for fixing it, I'd love to help but a recent PC rebuild means that my IDE and build chain is broken and I haven't had time to fix it 😟. I hoped it might be a 5-minute job to roll in while making other changes!

**Comment by waltervl** [comment]
You cannot use a prebuilt or docker version Beta version?

**Comment by gizmocuz** [comment]
Closing issue, if the added information is not enough, let us know and reopen this issue

**Comment by jefft4** [comment]
Sorry for delayed response, had some random database weirdness that crashed the system so had to hold off any updates for a few days.

This is funny... I can't tell whether or not the beta improved the reporting of that error, as it seems to have eliminated the error!
