### ISSUE TITLE
Allmost all icons on the Utility page went missing in beta 15005

### ISSUE THREAD

**Issue by IanDury** [domoticz/domoticz#5565]
And I did refresh my browser cache.

![Screenshot from 2023-01-24 20-56-45](https://user-images.githubusercontent.com/16663492/214395660-a969536f-6a06-41f5-8d72-42171fc198b0.png)

With beta 14980 the Utility icons were still there:

![Screenshot from 2023-01-24 21-02-17](https://user-images.githubusercontent.com/16663492/214396754-da071a85-0f15-4204-bace-aee9ca28adeb.png)

**Comment by barts2108** [comment]
#5556 may be related

**Comment by mojso** [comment]
I also have missing icons 

Domoticz version 2022.2 (build 15005)

**Comment by gizmocuz** [comment]
Will be solved very quickly

**Comment by gizmocuz** [comment]
This was caused by a previous fix (forgot to set the CustomImage value in case there was no custom image)
Solved in beta 15006

**Comment by NvBgm** [comment]
Also here missing default icons

**Comment by gizmocuz** [comment]
@NvBgm , did you update?

**Comment by NvBgm** [comment]
Sorry i was working with 15005 but now every thing is oke  on 15006

**Comment by gizmocuz** [comment]
Yes, that's why I found your comment a bit strange after I reported a fix 4 hours ago

**Comment by gizmocuz** [comment]
Great its working again!
