### ISSUE TITLE
MQTT autodiscovery - TS0601: humidity value alwaise zero

### ISSUE THREAD

**Issue by MarkKoshelev** [domoticz/domoticz#5566]
Temperature is normal
Humidity is alwaise zero

Device: TS0601
bridge: z2m
temp config topic: z2m-gw1/sensor/0xa4c1385e14c8e063/temperature/config
json:
{"availability":[{"topic":"z2m-1/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0xa4c1385e14c8e063"],"manufacturer":"Nous","model":"Temperature and humidity sensor with clock (SZ-T04)","name":"D1-LivingRoom(TS0601)"},"device_class":"temperature","enabled_by_default":true,"json_attributes_topic":"z2m-1/D1-LivingRoom(TS0601)","name":"D1-LivingRoom(TS0601) temperature","state_class":"measurement","state_topic":"z2m-1/D1-LivingRoom(TS0601)","unique_id":"0xa4c1385e14c8e063_temperature_z2m-1","unit_of_measurement":"°C","value_template":"{{ value_json.temperature }}"}

hum config topic: z2m-gw1/sensor/0xa4c1385e14c8e063/humidity/config
json: 
{"availability":[{"topic":"z2m-1/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0xa4c1385e14c8e063"],"manufacturer":"Nous","model":"Temperature and humidity sensor with clock (SZ-T04)","name":"D1-LivingRoom(TS0601)"},"device_class":"humidity","enabled_by_default":true,"json_attributes_topic":"z2m-1/D1-LivingRoom(TS0601)","name":"D1-LivingRoom(TS0601) humidity","state_class":"measurement","state_topic":"z2m-1/D1-LivingRoom(TS0601)","unique_id":"0xa4c1385e14c8e063_humidity_z2m-1","unit_of_measurement":"%","value_template":"{{ value_json.humidity }}"}

state topic: z2m-1/D1-LivingRoom(TS0601)
json: 
{"battery":41,"humidity":27,"humidity_alarm":null,"humidity_report_interval":120,"humidity_sensitivity":6,"linkquality":200,"max_humidity":60,"max_temperature":39,"min_humidity":20,"min_temperature":0,"temperature":26.4,"temperature_alarm":"canceled","temperature_report_interval":120,"temperature_sensitivity":0.6,"temperature_unit_convert":"celsius"}

**Comment by gizmocuz** [comment]
I have no issue using the above config/payload.
Maybe this is caused by something else? (A script?)
Maybe there are more configs for this device that can cause this issue?
Are you looking at the correct temp+hum device?

![image](https://user-images.githubusercontent.com/2265299/214498802-fab87095-d749-44f8-a639-19c11a08802d.png)

2023-01-25 07:50:01.627  MQTT-AD: MQTT received: D1-LivingRoom(TS0601) humidity (value: 27 %)
2023-01-25 07:50:01.629  MQTT-AD: MQTT received: D1-LivingRoom(TS0601) temperature (value: 26.399999999999999 ░C)

**Comment by MarkKoshelev** [comment]
Really, manually created sensor works good (I have changed id an name)
Also   I see somthing starnge in  gomoticz log (attached)
[log_TSO601.txt](https://github.com/domoticz/domoticz/files/10502640/log_TSO601.txt)
Most of descovery messages logged twice
Also config topics have complex structure:
![image](https://user-images.githubusercontent.com/50915452/214703544-8fe3b8c9-c97b-4f52-b2ae-3c41e525b6c8.png)


Also manually (from mqtt explorer) created sensor 
D1-LivingRoom(TS0601) temperature unit convert has "text" type
But descovered from z2m has "on/off" switch type.

topic: z2m-gw1/sensor/0xa4c1385e14c8e063/temperature_unit_convert/config
jsoh:
{"availability":[{"topic":"z2m-1/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0xa4c1385e14c8e063"],"manufacturer":"Nous","model":"Temperature and humidity sensor with clock (SZ-T04)","name":"D1-LivingRoom(TS0601)"},"enabled_by_default":false,"json_attributes_topic":"z2m-1/D1-LivingRoom(TS0601)","name":"D1-LivingRoom(TS0601) temperature unit convert","state_topic":"z2m-1/D1-LivingRoom(TS0601)","unique_id":"0xa4c1385e14c8e063_temperature_unit_convert_z2m-1","value_template":"{{ value_json.temperature_unit_convert }}"}

I dont have any idea how to reproduce the issue.
Is it possible to connect to you mqtt brocker?

**Comment by MarkKoshelev** [comment]
Also it is very starnge that created only 3 devices
![image](https://user-images.githubusercontent.com/50915452/214661280-41b83f1b-1e78-4b29-a8fe-0565d3ad1206.png)

**Comment by MarkKoshelev** [comment]
If I delete Temp/Hum sendor and create it manually from MQTT explorer , the humidity of the sensor dont work
I can send you database backup
![image](https://user-images.githubusercontent.com/50915452/214667169-cdd35ac2-61ee-4de8-b5af-d3e1b461abfe.png)

**Comment by MarkKoshelev** [comment]
One more note
while receiving next logged messages I see on very small time the norml humidity value. 27%, It blinked and return to 0%
2023-01-25 22:44:27.562 Z2M-GW1: Temp + Humidity/THGN122/123/132, THGR122/228/238/268 (D1-LivingRoom(TS0601))
2023-01-25 22:44:27.624 Z2M-GW1: General/Text (D1-LivingRoom(TS0601) temperature alarm)

Also if I delete all D1-LivingRoom devices, They appeare after receive status message (without discovery)
Is somting wrong with database?

**Comment by gizmocuz** [comment]
I think there are more config topics for this sensor, could you post them all?
Or run Domoticz with debug hardware enabled and send the logs?
The later is interesting if you see it blinking, then we have some more payload

**Comment by MarkKoshelev** [comment]
To create debug log should I run domoticz with the te next flags?
./domoticz -www 8080 -sslwww 443 -log "/var/log/domoticz.log" -loglevel all -debuglevel debug,hardware

**Comment by gizmocuz** [comment]
@MarkKoshelev , yes if you do this, you should see all messages coming into MQTT-AD
I don't think you have to use the -loglevel all

**Comment by MarkKoshelev** [comment]
Two logs file. AD while join TS0601
[TS0601_log-1.txt](https://github.com/domoticz/domoticz/files/10513129/TS0601_log-1.txt)
[TS0601_log.txt](https://github.com/domoticz/domoticz/files/10513052/TS0601_log.txt)

**Comment by gizmocuz** [comment]
Thank you for the logs! It was quite a few copy/paste actions to debug this issue ;)

Solved in beta 15012

It is correct you only get a few devices because all the other stuff is configuration stuff which you already can see/configure via the web interface of zigbee2mqtt
