### ISSUE TITLE
Zigbee2MQTT Rollershutter not working

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#5568]
Latest beta,
Odroid N2
Latest Zigbee2Mqqt

I have a rollershutter form zemismart zm25tq supported and working in z2m.
The device is comming into domoticz as a rollershutter, only i cannot use the shutter, because it is not working.
Type in z2m:
Zigbee model
    TS0601
Zigbee Fabrikant
    _TZE200_fzo2pocs

![ScreenShot339](https://user-images.githubusercontent.com/5214969/214675666-689deb6b-c973-493f-863a-c0d6a7ea574c.png)

![ScreenShot340](https://user-images.githubusercontent.com/5214969/214675889-8df7e582-0e69-4027-a90a-2e15e093e7fe.png)

**Comment by waltervl** [comment]
Can you activate it from Zigbee2MQTT?
If yes please supply the config and state topics from MQTT. Use MQTT explorer for this to copy paste the text info. No screenshots.
Needed is 
- the config topic name/directory and the payload
- the state topic name/directory and the payload when switching the device Open/Close and percentage when using Zigbee2MQTT

**Comment by Dylantje** [comment]
hope this are the good ones:
`{"linkquality":142,"position":12,"running":false,"state":"OPEN"}`

`{"linkquality":83,"position":82,"running":false,"state":"OPEN"}`

`{"linkquality":131,"position":0,"running":false,"state":"CLOSE"}`


`{"linkquality":160,"position":100,"running":false,"state":"OPEN"}`

`{"linkquality":163,"position":0,"running":false,"state":"CLOSE"}`

`invert_cover
Inverts the cover position, false: open=100,close=0, true: open=0,close=100 (default false).
`
Hope these are good..

**Comment by gizmocuz** [comment]
Could you also post the config topic name and payload
Also the state topic name (you already posted the payload)

If you search with/in MQTT Explorer for 'cover' you should be able to find the config topic/payload

**Comment by Dylantje** [comment]
`{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/BM Ryan/set","device":{"identifiers":["zigbee2mqtt_0x1c34f1fffe039085"],"manufacturer":"Zemismart","model":"Tubular motor (ZM25TQ)","name":"BM Ryan"},"json_attributes_topic":"zigbee2mqtt/BM Ryan","name":"BM Ryan","position_template":"{{ value_json.position }}","position_topic":"zigbee2mqtt/BM Ryan","set_position_template":"{ \"position\": {{ position }} }","set_position_topic":"zigbee2mqtt/BM Ryan/set","state_closed":"CLOSE","state_open":"OPEN","state_topic":"zigbee2mqtt/BM Ryan","unique_id":"0x1c34f1fffe039085_cover_zigbee2mqtt","value_template":"{{ value_json.state }}"}`

Hope this?
Otherwise...:-( Please help
Dombo71 here windoows noob

**Comment by gizmocuz** [comment]
Thanks for the info. This is what we call 'payload' (in this case the config payload), and the payload was send to a topic, and this topic has a name
And we need this name as well
The topic name of the actual data is 'zigbee2mqtt/BM Ryan' which you can see in the config payload

**Comment by gizmocuz** [comment]
And I do not think it is a TS0601 model ... that seems to be a radiator thermostat

**Comment by waltervl** [comment]
> And I do not think it is a TS0601 model ... that seems to be a radiator thermostat

Tuya zigbee uses strange model type identification. The identification here should be the manufacturer code _TZE200_xxxxxx

**Comment by gizmocuz** [comment]
Hmmm according the config above it is Zemismart (ZM25TQ)

**Comment by waltervl** [comment]
Zemismart is white label of Tuya https://www.zigbee2mqtt.io/devices/TS0601_cover.html

**Comment by Dylantje** [comment]
sorry hard work some times.
Think this os wrong only cannot undersstand wat Giz says...
![ScreenShot342](https://user-images.githubusercontent.com/5214969/215261598-0900020c-d921-4e60-9e2c-f605cf6d0e71.png)

The type is:
[https://www.zigbee2mqtt.io/devices/ZM25TQ.html#zemismart-zm25tq](url)
![ScreenShot343](https://user-images.githubusercontent.com/5214969/215261716-343d74d1-58c3-41df-aa40-ae285379dece.png)

**Comment by gizmocuz** [comment]
> Can you activate it from Zigbee2MQTT? 

Derik, are you able to operate the blinds from within zigbee2mqtt?

When you do so, what is send to:

zigbee2mqtt/BM Ryan/set

maybe close it then log the above about, and open it and log the above output

With your status logs from a few post up, I noticed that domoticz update the status in the blind widget in the web interface perfectly without issues

At the moment when you specify 31% in domoticz, it sends

{
  "position": 31
}

to zigbee2mqtt/BM Ryan/set

This seems OK according the configuration

**Comment by gizmocuz** [comment]
User has also issues getting the rollershutter to work outside domoticz via the original remote. (start and end point) so this is probably not related.
Time is also a issue.
Please feel free to re-open if this is a Domoticz issue
