### ISSUE TITLE
Notification HTTP

### ISSUE THREAD

**Issue by dav76df** [domoticz/domoticz#5571]
hello,

I can't add two http for notification

This feature would make it possible to no longer have to add a script and would simplify the management of access rights

**Comment by gizmocuz** [comment]
Hi, sorry, could you maybe explain a bit more in depth what you mean?
The HTTP Notifications are not working anymore? (Sure you enabled this?)
And what is the relation of a notification to management of access rights?

Are you talking about a notification from domoticz to a external system,
or are you talking about a external system that wants to call a JSON API function from domoticz?
If you are calling a JSON API function from Domoticz and you need to authenticate with basic-auth
make sure you are using HTTPS and not HTTP

You also did not specified your Domoticz version!

**Comment by dav76df** [comment]
I use HTPP notification for send SMS (with API free)

I mean send the notification at two users, for realize this i must creat a
sh script, but i have probleme for give good right at the script on the
raspberry

for resolve my problem, i want put two http request in the url/action targer

for exemple :
https://smsapi.free-mobile.fr/sendmsg?user=#FIELD1&pass=#FIELD2&msg=#MESSAGE
https://smsapi.free-mobile.fr/sendmsg?user=#FIELD3&pass=#FIELD4&msg=#MESSAGE

but if i put this, i have an error

My version is 2022.2

PS: sorry for my english

**Comment by kiddigital** [comment]
Hi @dav76df , you are using the Beta version I assume and the Beta does not accept Username/Password in the URL anymore.

You need to either run the script from within the Trusted network or use proper Basic-Auth header authentication.

**Comment by gizmocuz** [comment]
No problem.

So you want two http Nofications. That is not possible.

If it is for a switch, when you edit the switch you have the option to execute a script with the on/off action

When you created a script, and this script is places in the folder /home/pi make sure it has execution rights.

chmod +x /home/pi/myscript.sh

(In this case the script name is myscript.sh)

Also test this script by issuing

/home/script/myscript.sh

In the switch for 'On Action' you can now enter

script:///home/pi/myscript.sh

If it is for another device, then I would suggest to have a look at dzVents
Because with dzVents it is possible to call url's when you test agains a value

**Comment by dav76df** [comment]
thanks,

i use this method but i create the script in the folder /home/pi/domoticz/scripts and when i want use the script i have an error 512

I will try your method after

**Comment by dav76df** [comment]
I just tested the method, i have an error 512 with the script

my version of raspbian is "Raspbian GNU/Linux 11 (bullseye)"

**Comment by gizmocuz** [comment]
Is it a python script?

https://www.domoticz.com/forum/viewtopic.php?t=25488

**Comment by dav76df** [comment]
The sricpt is a bash script
envsms.sh
#!/bin/sh
curl -s -i -k "https://smsapi.free-mobile.fr/sendmsg?user=$1&pass=$2&msg=$5”
curl -s -i -k "https://smsapi.free-mobile.fr/sendmsg?user=$3&pass=$4&msg=$5

**Comment by waltervl** [comment]
check https://www.domoticz.com/forum/viewtopic.php?t=26504

**Comment by dav76df** [comment]
i add "sudo -H -u pi " before the curl but the error is the same (error 512)

the result of ls -l is :
-rwxr-xr-x  1 pi pi   194 Jan 29 20:35 envsms.sh

**Comment by waltervl** [comment]
Better continue this on the forum as it is not a Domoticz bug. You can continue on topic https://www.domoticz.com/forum/viewtopic.php?t=26504

Please check, as indicated on the forum topic to run the script with sudo and perhaps check curl location on your system. Closing this issue here.
