### ISSUE TITLE
MQTT AD - Rename Device

### ISSUE THREAD

**Issue by MarkKoshelev** [domoticz/domoticz#5572]
Z2M gateway has usefull feature - rename Friendly Name:
![image](https://user-images.githubusercontent.com/50915452/215163440-339cda0c-062c-47bc-a059-a405d053a732.png)

 Is it possible to support the renaming in domoticz?

I see that z2m bridge send config topic with the changed name
{"availability":[{"topic":"z2m-1/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0xa4c1385e14c8e063"],"manufacturer":"Nous","model":"Temperature and humidity sensor with clock (SZ-T04)","name":"D1-LivingRoom1"},"device_class":"temperature","enabled_by_default":true,"json_attributes_topic":"z2m-1/D1-LivingRoom1","name":"D1-LivingRoom1 temperature","state_class":"measurement","state_topic":"z2m-1/D1-LivingRoom1","unique_id":"0xa4c1385e14c8e063_temperature_z2m-1","unit_of_measurement":"°C","value_template":"{{ value_json.temperature }}"}

**Comment by gizmocuz** [comment]
No as the device id contains the id and if you have set a custom name you do not want this to be renamed everytime the config object is received
