### ISSUE TITLE
Can't log to Netatmo serveur, French.

### ISSUE THREAD

**Issue by jpbara** [domoticz/domoticz#5573]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by jpbara** [comment]
Hello,
No Way to log server: Error: Station1: No access granted, check username/password... since last Netatmo down server.
Météo station and relay thermo valve.
Of course: User and Pwd check many time.
Other soft works fine MacOS and IOS.
Version: 2022.2 (build 15006)
Build Hash: 96834bbf1
Compile Date: 2023-01-25 07:44:11
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]

Thank's

**Comment by didi31** [comment]
Hi
Did you tried to update your password ? It solved this issue on a previous build.
It works fine on build 15012.

**Comment by jpbara** [comment]
Yes, no way. thank's.

**Comment by didi31** [comment]
Is it a new install or did it worked before?

**Comment by jpbara** [comment]
It worked before but I broken domoticz definitively when I reinstall from scratch. No more access to domoticz on port 8080.

**Comment by waltervl** [comment]
Better move this to the forum. For Netatmo there is already a topic. https://www.domoticz.com/forum/viewtopic.php?p=297544#p297544
For new install  check for errors in the log and use the troubleshooting wiki page https://www.domoticz.com/wiki/Troubleshooting
As you use Beta also be aware of the security changes in Beta.
