### ISSUE TITLE
SolarMain (Today's kWh) does not update frequently (PVOutput - import)

### ISSUE THREAD

**Issue by mvizzini** [domoticz/domoticz#5577]
Version: 2022.2
Build Hash: eea9db734
Compile Date: 2022-11-05 13:05:35

- Every 5 minutes an update of the Efficiency and Power appears in the Domoticz. So this works fine.
- The Todays kWh 'yields' on the other hand only updates once in a while. It takes sometimes up to 2.25 hrs between the updates) even if the upadetes are available on PVOutput.

I uploaded two images and marked it with 'works fine' in green and the issue in red.
I uploaded a part of PVOutput (live data) and marked in yellow the values at 17:00 LT

![Schermafbeelding 2023-01-30 175052](https://user-images.githubusercontent.com/25082644/215541953-e516c54f-9ab2-49c7-b4a2-ca2c5836547a.png)
![Knipsel](https://user-images.githubusercontent.com/25082644/215542011-3c100859-c046-4bf9-83d8-36e0cd30959f.PNG)

**Comment by waltervl** [comment]
By which Hardware gateway are these devices controlled? If it is a Python plugin please report/discuss this on the forum or on the plugin repository. This github issue list is only for software bugs.

**Comment by gizmocuz** [comment]
Closing issue as there is no feedback.
Feel free to re-open when you answer the above question (which hardware)

**Comment by mvizzini** [comment]
[Domoticz] [Setup] [Hardware] and then chooce "PVOutput Import"

**Comment by gizmocuz** [comment]
The logic in the code of hardware/PVOutput_input.cpp seems OK
Can you check if the timestamp of the kWh sensor in Domoticz is updating?

There seems to be 2 kWh sensors (original names SolarMain and if you have consumption also SolarConsumed)

**Comment by mvizzini** [comment]
Hi,

I tried to explain the issue in the first mail but I think I wasn't clear
enough. I hope my next explanation is a little better :-)

I made tree samples during the time period 12:00 - 12:20. The samples from
domoticz are shown in the below figures.

[image: image.png]

[image: image.png]
[image: image.png]
As shown in the figure above, the connector updates every 5 minutes,
The solar Efficiency and (live) Power updates regularly

The value "Today used kWh" does not update. Sometimes it costs more than
2,5 hrs before it updates again.

My logfile from pv output (timestamp 12:15)  shows that the 0.092 kWh value
was reached at 10:15, but at 12:15 still shows the value 0.092 kWh.

[image: image.png]

I hope this will explain the issue and hope you can solve it.

with regard,

maurits

Op do 9 feb. 2023 om 08:15 schreef gizmocuz ***@***.***>:

**Comment by waltervl** [comment]
@mvizzini  Still an issue? Did you already update to 2023.1 Stable?

**Comment by luzpaz** [comment]
@mvizzini can you login to Github and drag drop the images in the previous message? (also have you tested with latest stable)

**Comment by waltervl** [comment]
Closing this due to lack of feedback.
