### ISSUE TITLE
MQTT Gas meter no floating point in log view

### ISSUE THREAD

**Issue by herm42** [domoticz/domoticz#5578]
Since switching from ozw to zwave-js mqtt there are no floating values in logview anymore
 
![image](https://user-images.githubusercontent.com/6725469/215772273-60bcfbc0-459c-4994-978b-4e9429beb01d.png)

![image](https://user-images.githubusercontent.com/6725469/215772860-05e9111a-8c6b-4970-a645-1c67f5ee8024.png)

as the value is stored with three decimal places it would be great to see them also in the log.

herm

**Comment by waltervl** [comment]
First impression it seems that zwaveJS is not sending the correct values. Did you check that with MQTT explorer and in your log files?
As this is a issue list for confirmed and reproducable issue I suggest you check further and request for help on the forum if needed: https://www.domoticz.com/forum/viewforum.php?f=82 
Closing this issue for now.

**Comment by herm42** [comment]
according to what I see in domoticzs (latest beta), zwave-hs-mqtt send the value as float ... 
![image](https://user-images.githubusercontent.com/6725469/215831653-058dc342-09b7-44fd-9314-03043b11d970.png)
  
@waltervl : are you ableto reopen this ticket?
thx,
herm

**Comment by waltervl** [comment]
Please open topic on forum. If this is normal behavior more people would have the same issue. So better discuss this first on the forum.
