### ISSUE TITLE
Symlinks to /dev/ttyUSBx devices are ignored

### ISSUE THREAD

**Issue by trusnak** [domoticz/domoticz#558]
Hi
As you have multiple USB devices connected to system, it's good idea to use udev to assign same name in /dev tree for it everytime it's reconnected. If you want to use 'cool' name for the device, domoticz have hardcoded names for the devices set in the code, for example:

```
# cat /etc/udev/rules.d/02-tty.rules
# ttyUSB3
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="0001", SYMLINK+="openzwave"
```

```
$ ls -la /dev/opentherm
lrwxrwxrwx    1 root     root             7 Mar 11 14:22 /dev/opentherm -> ttyUSB3
```

Finally it's not possible to choose /dev/opentherm in the dropdown list in web interface.

The question is how to detect that? My only idea here is to check all symlinks if it is pointing to USB device:

```
# file /dev/opentherm
/dev/opentherm: symbolic link to `ttyUSB3'
# file /dev/ttyUSB3
/dev/ttyUSB3: character special
```

Any better idea how to do so?

**Comment by gizmocuz** [comment]
As this is a one time action, and one time configuration (most times), i suggest we keep it with normal names ?

**Comment by trusnak** [comment]
Ok, you can use this:

```
# cat /etc/udev/rules.d/02-tty.rules
# ttyUSB3
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="0001", SYMLINK+="openzwave" NAME="ttyUSB3"
```

But you are still unable to use any 'customized' device names. Right?

**Comment by gizmocuz** [comment]
Correct, no 'exotic names'
this is how we specify it on our wiki
https://www.domoticz.com/wiki/PersistentUSBDevices

**Comment by trusnak** [comment]
Ok, thanks. I missed that wiki. Close this issue, please.
