### ISSUE TITLE
Dashboard favorite only shows power delivery, no power usage

### ISSUE THREAD

**Issue by JapieG** [domoticz/domoticz#5580]
Hello!

I am not sure if this is a bug or a feature somehow. Tried to search but i could'nt find anything. If i am wrong and this is already asked a thousand times, please delete this issue right away...

When i check my P1 meter sensor on the utility sensor page i can see actual power FROMthe grid, and actual power TO the grid in the top bar. (2 phases are delivering, and one is importing from the grid).

When i check the same sensor on my dashboard page i can only see delivery. Is this normal behaviour?

If yes, feature request: Is it possible to maybe show only net (netto) delivery or importing of power.

![dmtx_dash](https://user-images.githubusercontent.com/10058522/216074397-5ce7bda3-ba32-4794-8aab-fa486a373ffa.png)
![dmtx_utility](https://user-images.githubusercontent.com/10058522/216074400-79e70264-617d-47bc-bdca-77d5548b21d7.png)

Version:
Multiple versions, never saw it otherwise...

**Comment by waltervl** [comment]
Better to put this kind of discussions on the forum. I do not think you are completey right. You probably have a 3 phase installation and on dashboard you see nett usage or delivery. On utility screen you see nett usage by 1 or more phases (685) and nett delivery by one or more phases. 
If you would have looked at the same to the dashboard widget as the utility widget you would have seen 685-540=184 Watt (delivery) on the dashboard.
If you have only small usage on the phase where your solar panels are connected to you see a lot of delivery.

**Comment by JapieG** [comment]
I wish you were right, but unfortunately you are not. Only raw delivery is shown in dashboard. Not the net usage or delivery. Thats more or less why i consider this a bug.

**Comment by JapieG** [comment]
I made a screenshot in 2 browser windows to make this absolutely clear. Dashboard and utility page at the same time.

<img width="788" alt="dmtx_utility_and_dash" src="https://user-images.githubusercontent.com/10058522/216292903-f57da049-4248-4b17-94d0-475fbb3750b3.png">

I would rather see both also in dashboard view, or net usage/delivery in dashboard. Sounds still like a bug to me :-)

**Comment by waltervl** [comment]
Yes I agree.

**Comment by waltervl** [comment]
What does it show in Mobile mode?
The source is https://github.com/domoticz/domoticz/blob/development/www/app/DashboardController.js. 
It is javascript so no need to build something yourself, just edit the file on your system (after making a copy) and Ctrl-F5 refresh the page or reload in a private browser window to get the changes visible.

**Comment by gizmocuz** [comment]
Seems indeed like a bug..... I'll have a look at this

**Comment by gizmocuz** [comment]
Could you try beta 15020?

I think there were two issues:
- when you initially went to the dashboard the delivery value was also not present
- when a new value is received it was incorrectly rendered (only the delivery value)

**Comment by JapieG** [comment]
Thank you so much for your effort. In Beta15020 the issue is gone on the desktop, but not on the mobile layout. 

First desktop:
<img width="988" alt="Scherm­afbeelding 2023-02-03 om 15 15 25" src="https://user-images.githubusercontent.com/10058522/216626055-1f196b76-fa73-4df9-8b4e-5e9a7db5f6e9.png">
This is working now!

Mobile mode, i see power usage for one second and then it disappears and only showing delivery again.

Thanks so far!

**Comment by gizmocuz** [comment]
Yep, I did not make any changes to the mobile view
Could you test beta 15021, this should also solve it

**Comment by JapieG** [comment]
Again thanks for your effort.

I tried running 15021, but unfortunately still the same behavior on the dashboard page. I see Both power importing and exporting for a second and then on the next refresh the power import disappears and this is all what is left:

![IMG_3426](https://user-images.githubusercontent.com/10058522/216636400-cd618987-4890-4c25-9486-f627217f2861.jpg)

Actual should be good if this is a net value, but as far as I can see it is only delivery shown as actual value

**Comment by gizmocuz** [comment]
Mine is all with small text (U:, R: A: ... seems there is another one with full names)

I made another patch in beta 15022

**Comment by JapieG** [comment]
> Mine is all with small text (U:, R: A: ... seems there is another one with full names)
> 
> I made another patch in beta 15022

Haha indeed there are two layouts! I will check tomorrow, no solar feed anymore at this time :-)

thanks!!

**Comment by JapieG** [comment]
Tested 15022. Seems a bit more difficult than it looks :-) But it is actually working now, but now there are some layout problems in the mobile dashboards.

**Desktop layout NORMAL & COMPACT**
Everything works fine, but there is no comma and space (, &nbsp) between actual power and actual return like it has now in the stable release utility sensor page.

desktop normal
<img width="410" alt="Scherm­afbeelding 2023-02-04 om 10 31 52" src="https://user-images.githubusercontent.com/10058522/216759967-b67d409f-ad0a-4c63-afe5-3ab0ac409a3c.png">

desktop compact
<img width="297" alt="Scherm­afbeelding 2023-02-04 om 10 32 08" src="https://user-images.githubusercontent.com/10058522/216759980-34cf4768-adb4-4327-8e29-5b19531d9828.png">

 
**Mobile dashboard layout NORMAL:**
- In case there is no actual power delivery, only power usage
- Actual power is shown twice, should be zero for actual return to not shown at all
![IMG_3432](https://user-images.githubusercontent.com/10058522/216759119-14ccb05b-fb8c-452c-8f3e-f8016eb43424.jpg)

**Mobile dashboard layout NORMAL:**
- In case there is actual power delivery AND usage
- Usage total and return total are shown beneath each other
- Actual power usage and actual power delivery are shown next to each other where delivery has no title
![IMG_3433](https://user-images.githubusercontent.com/10058522/216759220-9cb3153c-3745-42a3-bbe7-fdbeaa82e84b.jpg)


**Mobile dashboard layout COMPACT:**
- In case there is no actual power delivery, only power usage
- U: as usage title, next to it are total and actual, looks okay (maybe better beneath each other
- R: as return title, next to it are total return, and no actual value (maybe better actual zero, but not really a problem like this)
![IMG_3435](https://user-images.githubusercontent.com/10058522/216759351-c580d347-98a2-4f42-9020-af5636241294.jpg)

**Mobile dashboard layout COMPACT:**
- In case there is actual power delivery AND usage
- layout is messed up :-)
- U: Total is okay, then next line is return total, then actual usage, then actual return without a title, alle next to each other in one line.
![IMG_3436](https://user-images.githubusercontent.com/10058522/216759426-21f1b7a8-e5f2-41c8-8b6b-7d0a39b5158d.jpg)

**Comment by gizmocuz** [comment]
Okey I will totally redesign it ;)

**Comment by gizmocuz** [comment]
Will be tomorrow, mobile few is ready, but the rest needs attention as well.

**Comment by JapieG** [comment]
> Will be tomorrow, mobile few is ready, but the rest needs attention as well.

Great! Just let me know when i have to test a beta👍🏼

**Comment by gizmocuz** [comment]
Please try beta 15023

**Comment by JapieG** [comment]
Checked, every situation as above, and all okay now! No errors found anymore!

Thanks! Now I have to wait until this is integrated in the stable release, as my 'live' domotiz site is stable release haha :-D

Many thanks, a 4 year old frustration is fixed now :-)

**Comment by gizmocuz** [comment]
Thanks for the feedback! You can consider this beta stable. Planning to create a stable from in in the upcoming hours/days anyway.
Unless you think something is not stable?

**Comment by JapieG** [comment]
> Thanks for the feedback! You can consider this beta stable. Planning to create a stable from in in the upcoming hours/days anyway.
> Unless you think something is not stable?

I will do, I saw something new in the login part. Just have to check consequences before updating live site. Again many thanks! Just for the completeness some screenshots:

Compact mobile dashboard with and without actual power delivery on less then all phases
![IMG_3450](https://user-images.githubusercontent.com/10058522/216810638-307d2391-c97e-416f-9b4b-65a5d39fb68c.jpg)

![IMG_3451](https://user-images.githubusercontent.com/10058522/216810643-4a13d7b2-9d62-4a0b-97ae-610ec1f76ffe.jpg)

Normal mobile dashboard with and without actual power delivery on less then all phases
![IMG_3453](https://user-images.githubusercontent.com/10058522/216810648-4dfe9fcc-12ea-4bed-8e7b-6f8c589fca83.jpg)

![IMG_3452](https://user-images.githubusercontent.com/10058522/216810653-4a2605b5-c137-430a-9084-932f5b1ab1e2.jpg)

Also the desktop layout is okay again, including the , and the space :-D 
 
<img width="418" alt="Scherm­afbeelding 2023-02-05 om 10 11 40" src="https://user-images.githubusercontent.com/10058522/216810810-370c2b8b-4986-416b-87a4-8a24d8f45db4.png">
