### ISSUE TITLE
Inconsistency between GUI and dzVents and API for Push Off Button (and others)

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5582]
Version: 2022.2 (build 15006)
Build Hash: 96834bbf1
Compile Date: 2023-01-25 07:44:11
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]

In the Domoticz GUI a click on the button of a Push Off Button device ends with a event and always the status Off.
If you activate the device with On, Off or Toggle in dzVents or an API call the device has always the status of the action in dzVents or the API call. This is problematic in dzga environment, because dzga first checks the status of the device and answers that the device is already on with no other action and of course no following event.
The same applies for Push On Button and other same functioning buttons. 
All action, independent of there origin, should have the same outcome.
In this case the Domoticz GUI has the right function.

**Comment by gizmocuz** [comment]
For these devices you should only use OFF in dzVents, same for Push ON, you need to use only ON

**Comment by SargonofAssyria** [comment]
That should then be in the Wiki.
I solved my problem with dzga with a device.switchOff().silent() function immediately after the dzVents script is triggered.

**Comment by gizmocuz** [comment]
Is it possible that you can update the Wiki about this?

**Comment by SargonofAssyria** [comment]
I leave that up to @waltervl

**Comment by waltervl** [comment]
@gizmocuz the Dzvents wiki is/was managed and published by GitHub somehow. Is that still working or can I change the wiki directly?

**Comment by gizmocuz** [comment]
Good question! I have no idea, I think it is a combination. The file README.wiki seems the raw context of the wiki.
If that is correct we also need to update this file, or update this file first and copy/paste it to the Wiki
