### ISSUE TITLE
sensor without unit in autodiscovery

### ISSUE THREAD

**Issue by akamming** [domoticz/domoticz#5584]
Hi,

found another (small) incorrect behaviour in domoticz (compared to home assistant).

An autodiscovery message like:
```
{
  "value_template": "{{ value_json.value }}",
  "unit_of_measurement": "",
  "state_topic": "domesphelper/sensor/Faultcode/state",
  "json_attributes_topic": "domesphelper/sensor/Faultcode/state",
  "name": "Faultcode",
  "unique_id": "domesphelper_Faultcode"
}
```
in a topic like "homeassistant/sensor/domesphelper/Faultcode/config" 

should introduce a sensor without unit.  In home assistant this works fine (so message apparently ok):
![image](https://user-images.githubusercontent.com/30364409/216761173-a1b5ff4f-edb7-4d5e-ba12-e20e4e027fb1.png)

However in domoticz the unit of measurement becomes "??"...:
![image](https://user-images.githubusercontent.com/30364409/216761204-272b0577-df10-4e4e-ad63-b682744caf5b.png)

Expected behaviour is that also in domoticz there is no unit of measurement...

**Comment by gizmocuz** [comment]
Everything should have a unit, if not, it is indeed ?? .... Edit the sensor and set the unit to 'Faults' if you like

**Comment by akamming** [comment]
This is the actual faultcode. So it doesn’t have  unit. Autodiscovery supports this (in sensortype none, unit is specifiied as optional in the documentation for that type) Anyway if domoticz itself does not support sensors without  units, it’s a limitatiation i have to live with…

**Comment by gizmocuz** [comment]
Everything is 'something', so set it to 'Faultcode' and give your device a good name. (Like Washing machine, if this is a faultcode for the washing machine)
It is not a limitation, I hope you understand the logic that everything is 'something' (put something in your hand and say it's nothing!)

**Comment by akamming** [comment]
From a Scientific point of view The jury os stil out in your statement (i can recommend the YouTube video “what is Nothing” from Sabine hossenfelder). 

But let’s make this one more practical on home automation use cases.

The Only other use case  besides a statuscode i can think of is that if you want a sensor which measures a ratio , but that almost never happens

currently i actually solved it already using your suggestion. So to me it is just a cosmetic glitch with an easy workaround. The reason i reported is because it’s an offspec from the ha discovery protocol which states for sensor none type the unit is optional. It is supported in ha. It’s up to you if you want to support in domoticz or not

**Comment by gizmocuz** [comment]
It's not a cosmic glitch. Step 1, name your sensor correct (like drome), and second pick a good unit label (faults)
This way you have 'Drome'->6 faults

**Comment by gizmocuz** [comment]
@akamming , watched the video 🤣But it already starts wrong... with a box... that is something so this proves my point *g*

**Comment by akamming** [comment]
Haha
