### ISSUE TITLE
Evohome device.state and device.level in dzVents has broken because....

### ISSUE THREAD

**Issue by andyjbm** [domoticz/domoticz#5594]
Hi,

**Overview:**
So I've got domoticz on a Raspberry PI using a RF hat to sniff the packets from an evohome system. I have an eventscript that pushes Temps and Relay values to emoncms so I can make pretty graphs. After solving this: #5093 domoticz has been working great for the last 13 months or so doing its funky thing.

**What happened.**
While doing mantenance on the PI (well its been 13 months) I pressed the "update" button in the domoticz gui. Silly me.
After the update I noticed all my graphs were overshooting.

**The problem**
So in the file ~/domoticz/dzVents/runtime/device-adapters/evohome_device.lua there is a stansa of code that sets device.state and device.level based on the value of device._state (note the underscore).

https://github.com/domoticz/domoticz/blob/eea9db7349bd31a6c80b791a98a044158d0384e6/dzVents/runtime/device-adapters/evohome_device.lua#L49-L56

Now device._state **used** to take the values "Off", "On" or a number from 1 to 99 for the condition of the Relay. These are picked up by my event script that pushes to emoncms.

What I found is that after the update I did yesterday device._state now takes the values 0 to 200 (and never "On" or "Off" so device.state is always set to "On" and device.level is now double the value it used to be before the update.

**The fix**
I'm working on it. Shouldn't be too hard. I'll be back with an update once I'm happy I have it working.

Andy.

**Comment by andyjbm** [comment]
Hi,

So I'm trying this as a fix replacing lines 49 thro 57 with:
```
                elseif device.deviceSubType == "Relay" then
                        device.state = device._state == 0 and 'Off' or 'On'
                        device.level = device._state / 2
                        device.active = device.state ~= 'Off'
                else
```

I'll give it a few days to see if it fixes the graphs.

Andy.

**Comment by gizmocuz** [comment]
Do you know why it changed from 0-100 to 0-200? is this a percentage value and should the range be from 0-100?

**Comment by andyjbm** [comment]
> Do you know why it changed from 0-100 to 0-200? is this a percentage value and should the range be from 0-100?

Hi, for me the update caused the change. The old version used 0-100 and the new version uses 0-200. Something upstream must have changed between versions.

Btw the fix appears to be working so far.

Andy.

**Comment by gizmocuz** [comment]
Thanks for the feedback, should work correctly in beta 15153, is it possible to test this?

**Comment by andyjbm** [comment]
Ok thanks, running the beta now.

Will report back in a day or two when I have graphs to compare.

Andy.

**Comment by andyjbm** [comment]
Hi @gizmocuz,

Had a quick glance at the graphs looks good so far. I also had a quick look at the beta and noticed you'd included my suggested fix in the evohome_device.lua file. Not had chance to diff yours with mine but from memory it looks the same so all should be good. 

I'll a/b them next time I have my laptop open.

Curious to know why this was needed. Have you an idea of why the value being presented by device._state has changed?

Andy.

**Comment by ChristianJHJose** [comment]
Thank you @andyjbm @gizmocuz build `15153` fixes the same issue that I have been having ever since update to 2022.2 back on 9th December.

**Comment by gizmocuz** [comment]
Thanks all for the feedback! Closing issue as solved!
