### ISSUE TITLE
MQTT AD and battery property

### ISSUE THREAD

**Issue by enesbcs** [domoticz/domoticz#5595]
Shelly H&T Plus reports its battery through MQTT with this JSON:

{"id": 0,"battery":{"V":5.21, "percent":65},"external":{"present":false}}

I tried to fed it with Domoticz AD with the following HA config:

Topic:
homeassistant/sensor/shellyplusht-a1032abcf510/battery/config

Payload:
{"dev_cla": "battery","enabled_by_default":true,"entity_category":"diagnostic","~": "shellyplusht-a1032abcf510/","json_attributes_topic":"~status/devicepower:0","name": "shellyplusht-a1032abcf510 Battery","state_class":"measurement","state_topic":"~status/devicepower:0","unique_id":"shellyplusht-a1032abcf510-battery","unit_of_measurement":"%","value_template":"{{ value_json['battery'].percent }}"}

But does not matter what i try to achieve, Domoticz always tries to read "battery" as Int and dropping this error:

Exception (on_message): Value is not convertible to Int.! (topic: shellyplusht-a1032abcf510/status/devicepower:0/message: {"id": 0,"battery":{"V":5.21, "percent":65},"external":{"present":false}}
2023-02-11 14:59:51.146 ) 

I think "battery" is hardwired as integer in MQTTAutoDiscover.cpp regardless of its content:

if (!root["battery"].empty())
{
 pSensor->BatteryLevel = root["battery"].asInt();
}

In fact, processing of JSON is stopped at this point, as i am unable to use value_json['external'].present value even if i do not define battery device.

**Comment by gizmocuz** [comment]
First time I have seen the battery level this was but your config is correct and we should check the value template as we are doing elsewhere in the code

**Comment by gizmocuz** [comment]
Could you try beta 15073? This should solve the problem

**Comment by enesbcs** [comment]
Thank you for this quick fix, i will try 15073 today when i arrive home!

**Comment by enesbcs** [comment]
> Could you try beta 15073? This should solve the problem

Tried with 15079 and i can confirm that the battery property is working fine now! Thank you!

Shelly H&T Plus battery support added to https://github.com/enesbcs/shellyteacher4domo script

**Comment by gizmocuz** [comment]
Thank you for testing!
Great plugin you've made... Would be great if you could implement this in the native code
I have one shelly device and had not the time to test it yet.

**Comment by enesbcs** [comment]
Thanks!
I am not so experienced in C++ language, mainly using python. Although if you can show me an existing native hardware source which listens on multiple different MQTT topics (1 needed for Gen1 and +2 for Gen2 Shelly device detection) and able to publish to custom MQTT topic, i can try to use it as a base. 
(Otherwise this script has to be used only once, while it creates AD configs with retain flags, and the script can be stopped as the rest of the work done by the MQTT AD hardware.)

**Comment by gizmocuz** [comment]
I think you should (just) extend the MQTTAutoDiscovery class 😁

**Comment by enesbcs** [comment]
> I think you should (just) extend the MQTTAutoDiscovery class grin

I see your point, a new ShellyMQTTAutoDiscovery can be made based on MQTTAutoDiscovery. 

But the config templates in the script needs heavy testing, currently not suggested to average end-users nor for any production systems.
