### ISSUE TITLE
Thermostat device planning not working

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#5596]
Current Version : Version: 2022.2 (build 15071)

When changing the target temperature on the DZ Thermostat virtual device, the target temp did not change : 

![image](https://user-images.githubusercontent.com/35136439/218417526-d1d8428c-c36c-46bd-b56d-3eb7e427b20c.png)

![image](https://user-images.githubusercontent.com/35136439/218418392-b900a5a8-63c8-4879-bab1-415db1aab37f.png)

**Comment by rezzalex** [comment]
seems to work finally.

**Comment by gizmocuz** [comment]
@rezzalex , please note we are not a helpdesk.
Use the forum next time
