### ISSUE TITLE
Switch selector Grid planning / "levels" are displaied, not "names"

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#5597]
Current Version : Version: 2022.2 (build 15071)
![image](https://user-images.githubusercontent.com/35136439/218424318-9460fa15-4ae2-4a4a-973c-fa5aacf89805.png)

![image](https://user-images.githubusercontent.com/35136439/218424038-6384e705-ea67-425c-bb64-45640c4dfcfa.png)

![image](https://user-images.githubusercontent.com/35136439/218424075-8b8b9dd8-666d-4e1c-8190-c65ef3f58bfe.png)

**Comment by MuadDibVV** [comment]
Hello,
The problem seems to be corrected with the 2023.1 stable version.

![image](https://user-images.githubusercontent.com/62676693/230681514-29dfd203-bb38-47a1-85a7-5f20a5a63db1.png)

**Comment by gizmocuz** [comment]
Thanks for reporting. Closing issue as there is no feedback from topic starter
