### ISSUE TITLE
CSS problem in dark-th3me

### ISSUE THREAD

**Issue by ikino** [domoticz/domoticz#5606]
Texts in line with class options overflows
![Screenshot at 2023-02-16 17-52-48](https://user-images.githubusercontent.com/43843741/219434027-b9105c58-22c5-48cc-9529-80954e2d3c78.png)

Just add to custom.css in dark-th3me:
```
td.options {
  white-space: nowrap;
  text-overflow: ellipsis;
}
```

After that change:
![Screenshot at 2023-02-16 17-56-26](https://user-images.githubusercontent.com/43843741/219434518-b0b59e8c-f580-428c-a521-11c7ff525af6.png)

**Comment by gizmocuz** [comment]
How does this look in the default theme? And do you know what if the difference? (the nowrap or the size?)

**Comment by ikino** [comment]
> How does this look in the default theme? And do you know what if the difference? (the nowrap or the size?)

I made this change only in dark-th3me theme. My change is maybe no better solution, but in my case is enough. I know what is nowrap, it's nicer in one row but two rows.

My change in simple blue theme:
![Screenshot at 2023-02-22 07-43-35](https://user-images.githubusercontent.com/43843741/220543768-d7aed9f9-2404-4f97-9210-fd8767e75cc9.png)

**Comment by gizmocuz** [comment]
I am trying to solve this in style.css

I added the following block and am testing with Czech language

table td.options {
  white-space: nowrap;
  overflow-x: hidden;
}

Unfortunally the horitzontal scrollbar stays visible

![image](https://user-images.githubusercontent.com/2265299/220556375-4e9643b7-b848-4061-9184-5dd80fe69773.png)

**Comment by gizmocuz** [comment]
Seems solved by using

overflow-x: hidden !important;

**Comment by gizmocuz** [comment]
Fixed in beta 15093
