### ISSUE TITLE
Floorplan : Error security48

### ISSUE THREAD

**Issue by MuadDibVV** [domoticz/domoticz#5607]
Hello,

  The Floorplan can't present an icon for the build in security element. Here is the error :
Failed to load resource: the server responded with a status of 404 (security48_On.png)

NB : I am on the stable 2023.1 version but the issue was present on the older version too

**Comment by gizmocuz** [comment]
Could you post a screenshot here? (copy/paste)
What type of hardware/device is this?

**Comment by MuadDibVV** [comment]
Type : Security, Security Panel, Security 
![Security](https://user-images.githubusercontent.com/62676693/219724070-006403ce-53cf-4762-bcdd-4f82bb23e436.png)
![Security 2](https://user-images.githubusercontent.com/62676693/219724554-0f55556e-512f-4e1f-a31a-496894479d76.png)

**Comment by gizmocuz** [comment]
I don't think this is allowed on the floor plan. This is to arm/disarm your system via the special webpage for this

**Comment by MuadDibVV** [comment]
I use it to present the status of my alarm on my floorplan.

**Comment by FireWizard52** [comment]
This has been asked before.
See: #5317

**Comment by MuadDibVV** [comment]
For my needs we just have to copy the security48.png on a new security48_On.png in the images folder

**Comment by gizmocuz** [comment]
@MuadDibVV , that is not the 'fix' ... it needs to be supported by the Floorplan, meaning some JS code needs to be changed for this.
The logic is probably already inside the lights and dashboard page

**Comment by MuadDibVV** [comment]
Indeed, it's a quick win to avoid the html error (and my only use is display :-)). 
To be complete it's necessary to open the /secpanel url when clicking on it.

**Comment by gizmocuz** [comment]
If you have time please implement it the correct way

**Comment by MuadDibVV** [comment]
Pull request created #5616
(Test ok on my side)

**Comment by gizmocuz** [comment]
Thanks for the PR. Implemented in beta 15097

**Comment by FireWizard52** [comment]
It's working for me. 
Thanks and regards
