### ISSUE TITLE
every kWh device is reset to 0 at 00:00

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#5608]
version 15082.

it seems that every kWh device(Zwave, Shelly) level is set to 0 at 00:00
So the devices are on, kWh devices have a certain level and at 00:00 it is temporarily reset to 0

The Watt devices do not experience this

previous version 15006 did not have this problem

Watt device
![image](https://user-images.githubusercontent.com/16853535/219942220-0a4d9ec9-0bad-45d5-8949-c39a29b04914.png)

kWh device
![image](https://user-images.githubusercontent.com/16853535/219942246-42db0754-2e6f-4070-9963-81e5b6d7b6ee.png)

![image](https://user-images.githubusercontent.com/16853535/219942294-bc8c6b98-5bad-4a1d-88f1-1a59325d73b2.png)

![image](https://user-images.githubusercontent.com/16853535/219942312-27d32973-24ad-4d02-8a67-3d20598f44a8.png)

**Comment by gizmocuz** [comment]
Can you see which commit/change could have caused this issue?

**Comment by gizmocuz** [comment]
I don't think it is a database value but a graph render issue

**Comment by gizmocuz** [comment]
Okey value is inside the database

**Comment by GravityRZ** [comment]
maybe this fix caused it


15015 | 20230131 | Graphs | Fixed possible wrong first start value in certain charts (Fixes #5569)

**Comment by gizmocuz** [comment]
Nope as the value is inside the database
I suspect the error to be in here

`CSQLHelper::AddCalendarUpdateMeter()`

**Comment by GravityRZ** [comment]
ok. it happened somewhere between 15006 and 15082 so lots of changes since then

**Comment by gizmocuz** [comment]
On second thought (looking at the timestamps (it is not rounded) the problem could be here

CSQLHelper::UpdateCalendarMeter

**Comment by gizmocuz** [comment]
15006 was released on 25th January. Could not be that many changes.
Are you sure it was not before 15006?

**Comment by gizmocuz** [comment]
Not many changes in SQLHelper I'm afraid

https://github.com/domoticz/domoticz/commits/development/main/SQLHelper.cpp

**Comment by GravityRZ** [comment]
my version before that was 14880 so it could be between 14880-15006 as well.

**Comment by gizmocuz** [comment]
Okey 😁This was released 23 December 2022

**Comment by gizmocuz** [comment]
Not many changes since 23 December I'm afraid

https://github.com/domoticz/domoticz/commits/development/main/SQLHelper.cpp

Are you sure it was not before 14880?

**Comment by GravityRZ** [comment]
not 100% sure but this dip was easily spotted. so you say the 0 is is the database so rolling back to  a previous version will not work.

**Comment by GravityRZ** [comment]
does 15082 uses the same database version as 15006. if so i can do  arollback and see if it happens again tonight.

**Comment by gizmocuz** [comment]
Yes, But maybe you can check your database backups with SQLite Expert Personal edition (or another program)
It's inside the meter table (you can filter on the IDX)

Yes this 0 value is inside the database

![image](https://user-images.githubusercontent.com/2265299/219949988-3e0dea58-2e62-48e6-bdba-5ca5517b49ec.png)

**Comment by GravityRZ** [comment]
ok. will give that a try first.

**Comment by GravityRZ** [comment]
i just checked previous versions.
problem is i have a 2 day history and these lights only stay on after 00:00 in the weekend.
as far as i can see i have no entries in the DB which have a history with dates in the weekend

**Comment by gizmocuz** [comment]
I don’t think it is related to the weekend

**Comment by GravityRZ** [comment]
no but when that kWh device is not on after 00:00 i can not see if it jumps to 0 or not because it is already 0
so in my case i only notice the bug with devices which stay on after 00:00 and that only occurs in the weekend. weekdays everything shuts of after 23:15

**Comment by GravityRZ** [comment]
i will see if i can find a backup made in the weekend

**Comment by GravityRZ** [comment]
ok i can confirm the problem is also in build 14880 and build 14599
i can spot it because it creates a double entry one at 00:00 and a second one at 00:01

problem is when going back before that i can only do so on a monthly base and 1-11-22 and 1-12-22 were not in the weekend.

1-10-22 was in the weekend and it looks like it is not in that version
that version was lower than 14311 DB version 155
so probably between 14298 and 14599 this happened

are these likely suspects

14560 | 20221011 | Counter | Fixing counter incremental 1 hour offset (Fixes #5366)
14492 | 20220901 | Energy | Making the Energy Usage more precise
14491 | 20220901 | Energy | Fixing EnergyUsage precision (Fixes #5326)



how can i see the domoticz version in the database
the database from 1-11-22 does not havre the problem

**Comment by gizmocuz** [comment]
The Domoticz version is not in the database (only a database version)
This is now added in the next beta version

1-11 is 1 November or 11 January 2022 ?

**Comment by GravityRZ** [comment]
1 november 2022. so definately bug was introduced between 14298(because DB without bug is V155) and 14599

**Comment by gizmocuz** [comment]
No the precision had nothing to do with this
Also please do not refference github issues, but rather the commit itself, which you could get from

https://github.com/domoticz/domoticz/commits/development/main/SQLHelper.cpp

This problem has been there for a long time... 

Can you build Domoticz yourself to test a patch?
Maybe the problem is in the code block underneath the following comment in SQLHelper.cpp

`//Insert the last (max) counter value into the meter table to get the "today" value correct.`

Eureka... I think I found it! As here only the counter value is set and not the usage, the usage was 0

**Comment by gizmocuz** [comment]
Please update to beta version 15087 and if possible, report tomorrow if it is solved.

**Comment by GravityRZ** [comment]
ok. i will test and report back.

**Comment by gizmocuz** [comment]
I tested as well and it seems solved.... Hope you got the same conclusion

**Comment by GravityRZ** [comment]
yes. looks like it is gone

thanks

strange that nobody noticed this bug
must be that most people switch their lights of before 00:00 :-)

**Comment by GravityRZ** [comment]
i noticed however that there is still a second entry logged with the same time stamp(or one with a 1 second diference). is that gonna be a problem?

213	118581	51	2023-02-20 00:00:01
213	118581	51	2023-02-20 00:00:01

**Comment by gizmocuz** [comment]
No that is needed. Thanks for the feedback!
