### ISSUE TITLE
P1 smartmeter gas usage 24h, shown hour later and other visualisation oddities

### ISSUE THREAD

**Issue by bijwaard** [domoticz/domoticz#5609]
Dear P1 smartmeter developers,

I observed some strange behavior with the gas usage 24h display (using domoticz 2023.1 on raspberryPi, firefox browser on Ubuntu Linux). Just after 10:00, I observed the following usage (note the different shades at 10:00):
![image](https://user-images.githubusercontent.com/6523124/219941393-a20823c0-2aee-4f67-a311-067252d7a1d1.png)
Just after 11:00 it looks like this (note that part of the 10:00 block usage now shifted to 11:00, and actual usage in past hour is not shown, while total usage over the day does account for gas usage reported around 11:00):
![image](https://user-images.githubusercontent.com/6523124/219941534-79f7d295-7e5c-4fd0-8480-808f674a8f15.png)
20 minutes later (11:20) I see the different shades as well after 11:00, the brightest shade appears to be the measurement for 11:00, the other the measurement for 10:00.
![image](https://user-images.githubusercontent.com/6523124/219942250-af8322c4-a83e-49ba-93c6-f3379aaf8800.png)

When I display the data exported to influxdb in grafana, showing the difference in gas counts in previous hour, I see the following (note that usage is shown one hour earlier than in domoticz, which is correct compared to the wall-clock):
![image](https://user-images.githubusercontent.com/6523124/219941882-4f732d33-190b-4c23-be3d-336585f4baf2.png)

Kind regards,
Dennis

**Comment by GravityRZ** [comment]
i noticed the same.
when my CV start at 8:00 i see one hour later usage on 08:00(from 08:00-09:00)
now it indeed starts at 09:00(does this mean total usage at 09:00 or usage from 09:00-10:00)

maybe it has something to do with a recent change regarding the definition of  when usage starts

<html>
<body>


15015 | 20230131 | Graphs | Fixed possible wrong first start value in certain charts (Fixes #5569)
-- | -- | -- | --



</body>
</html>

**Comment by bijwaard** [comment]
Thanks for mentioning that graph fix, however that fix seems only related to midnight hour rollover. This issue happens during the day when an hour has passed.

**Comment by arjendekorte** [comment]
@bijwaard It looks like you need to refresh your browser cache, as the markers for days of the week have changed with the latest update (they are now in the middle of the bar). That doesn't fix the odd notation of the gas usage though, I see the same here where the last hour has two different shades.
![Screenshot_20230220_102413](https://user-images.githubusercontent.com/14976386/220065350-3345990d-7c3b-4208-a8c3-d92d5649087e.png)

**Comment by bijwaard** [comment]
Hi Arjen, 

Thanks for your reaction. I've updated the browser cache, indeed the days in the week graph are now in the middle of the measurement, nothing seems to have changed to the 24 hours graph.

Kind regards,
Dennis

**Comment by arjendekorte** [comment]
There is clearly overlapping data in the last bar (excerpt of last four bars in todays graph):
```
<rect x="515" y="67" width="20" height="116" fill="rgba(3,190,252,0.8)" stroke="#ffffff" stroke-width="0" opacity="1" class="highcharts-point"></rect>
<rect x="540" y="176" width="20" height="7" fill="rgba(3,190,252,0.8)" stroke="#ffffff" stroke-width="0" opacity="1" class="highcharts-point"></rect>
<rect x="564" y="172" width="20" height="11" fill="rgba(3,190,252,0.8)" stroke="#ffffff" stroke-width="0" opacity="1" class="highcharts-point"></rect>
<rect x="564" y="158" width="20" height="25" fill="rgba(3,190,252,0.8)" stroke="#ffffff" stroke-width="0" opacity="1" class="highcharts-point"></rect>
```
Note the duplicate X-coordinate for the last two entries. This smells like an off-by-one error, but so far I have not figured out how this graph is generated in the first place.

**Comment by gizmocuz** [comment]
Best to open the browsers development console, go to the network tab , refresh the page, find the link that loads the daily values, copy this, open this in another browser, and check the data

**Comment by arjendekorte** [comment]
I'm not really good at this, I'm afraid. The only thing I can find is that whats inside the following (`json.htm?idx=11&range=day&sensor=counter&type=graph`), contains the wrong data:
```
{
	"CostEnergy" : 1896,
	"CostEnergyR1" : 537,
	"CostEnergyR2" : 537,
	"CostEnergyT2" : 2018,
	"CostGas" : 6837,
	"CostWater" : 9100,
	"Divider" : 1000.0,
	"DividerEnergy" : 1000.0,
	"DividerWater" : 100.0,
	"ValueQuantity" : "",
	"ValueUnits" : "",
	"result" : 
	[
		{
			"d" : "2023-02-20 12:00",
			"mu" : "3.190",
			"v" : "0.225"
		},
		{
			"d" : "2023-02-20 13:00",
			"mu" : "3.500",
			"v" : "0.310"
		},
		{
			"d" : "2023-02-20 14:00",
			"mu" : "3.526",
			"v" : "0.026"
		},
		{
			"d" : "2023-02-20 15:00",
			"mu" : "3.612",
			"v" : "0.086"
		},
		{
			"d" : "2023-02-20 16:00",
			"mu" : "3.612",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-20 17:00",
			"mu" : "3.754",
			"v" : "0.142"
		},
		{
			"d" : "2023-02-20 18:00",
			"mu" : "3.948",
			"v" : "0.194"
		},
		{
			"d" : "2023-02-20 19:00",
			"mu" : "4.011",
			"v" : "0.063"
		},
		{
			"d" : "2023-02-20 20:00",
			"mu" : "5.110",
			"v" : "1.099"
		},
		{
			"d" : "2023-02-20 21:00",
			"mu" : "5.475",
			"v" : "0.365"
		},
		{
			"d" : "2023-02-20 22:00",
			"mu" : "5.741",
			"v" : "0.266"
		},
		{
			"d" : "2023-02-20 23:00",
			"mu" : "5.753",
			"v" : "0.012"
		},
		{
			"d" : "2023-02-21 00:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 01:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 02:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 03:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 04:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 05:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 06:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 07:00",
			"mu" : "0.476",
			"v" : "0.476"
		},
		{
			"d" : "2023-02-21 08:00",
			"mu" : "1.428",
			"v" : "0.952"
		},
		{
			"d" : "2023-02-21 09:00",
			"mu" : "1.487",
			"v" : "0.059"
		},
		{
			"d" : "2023-02-21 10:00",
			"mu" : "1.575",
			"v" : "0.088"
		},
		{
			"d" : "2023-02-21 11:00",
			"mu" : "2.011",
			"v" : "0.436"
		},
		{
			"d" : "2023-02-21 11:00",
			"mu" : "2.011",
			"v" : "0.000"
		}
	],
	"status" : "OK",
	"title" : "Graph counter day"
}
```
But I can't find `json.htm` anywhere so I have no idea where to look. It is clear from the above, that the times of these values are one hour off, except for the last entry.

**Comment by gizmocuz** [comment]
Thanks for the log. Seems the last record is added twice (see 2023-02-21 11:00)

**Comment by gizmocuz** [comment]
Reason is probably because the current (last) value is added to the list, this should either be not the case (but then you have no 100% accurate graph as you could miss a counter value from the last 5 minutes) or the previous should be removed.
I will opt for removing rthe extra value

**Comment by arjendekorte** [comment]
No, it isn't. Note that the values (I assume the "v" ) is different. So actually all values listed are correct (and in the correct order), but for all except the last, the timestamp is one hour late.

**Comment by gizmocuz** [comment]
That last value is added in the function that generates this graph data.
I will have a look at this.
That last value is probably from the DeviceStatus table.

**Comment by gizmocuz** [comment]
this is my output:

> 		{
> 			"d" : "2023-02-21 11:00",
> 			"mu" : "2.748",
> 			"v" : "0.556"
> 		},
> 		{
> 			"d" : "2023-02-21 11:00",
> 			"mu" : "2.875",
> 			"v" : "0.127"
> 		}
>

**Comment by arjendekorte** [comment]
Just a couple of minutes later:
```
{
	"CostEnergy" : 1896,
	"CostEnergyR1" : 537,
	"CostEnergyR2" : 537,
	"CostEnergyT2" : 2018,
	"CostGas" : 6837,
	"CostWater" : 9100,
	"Divider" : 1000.0,
	"DividerEnergy" : 1000.0,
	"DividerWater" : 100.0,
	"ValueQuantity" : "",
	"ValueUnits" : "",
	"result" : 
	[
		{
			"d" : "2023-02-20 12:00",
			"mu" : "3.190",
			"v" : "0.170"
		},
		{
			"d" : "2023-02-20 13:00",
			"mu" : "3.500",
			"v" : "0.310"
		},
		{
			"d" : "2023-02-20 14:00",
			"mu" : "3.526",
			"v" : "0.026"
		},
		{
			"d" : "2023-02-20 15:00",
			"mu" : "3.612",
			"v" : "0.086"
		},
		{
			"d" : "2023-02-20 16:00",
			"mu" : "3.612",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-20 17:00",
			"mu" : "3.754",
			"v" : "0.142"
		},
		{
			"d" : "2023-02-20 18:00",
			"mu" : "3.948",
			"v" : "0.194"
		},
		{
			"d" : "2023-02-20 19:00",
			"mu" : "4.011",
			"v" : "0.063"
		},
		{
			"d" : "2023-02-20 20:00",
			"mu" : "5.110",
			"v" : "1.099"
		},
		{
			"d" : "2023-02-20 21:00",
			"mu" : "5.475",
			"v" : "0.365"
		},
		{
			"d" : "2023-02-20 22:00",
			"mu" : "5.741",
			"v" : "0.266"
		},
		{
			"d" : "2023-02-20 23:00",
			"mu" : "5.753",
			"v" : "0.012"
		},
		{
			"d" : "2023-02-21 00:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 01:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 02:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 03:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 04:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 05:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 06:00",
			"mu" : "0.000",
			"v" : "0.000"
		},
		{
			"d" : "2023-02-21 07:00",
			"mu" : "0.476",
			"v" : "0.476"
		},
		{
			"d" : "2023-02-21 08:00",
			"mu" : "1.428",
			"v" : "0.952"
		},
		{
			"d" : "2023-02-21 09:00",
			"mu" : "1.487",
			"v" : "0.059"
		},
		{
			"d" : "2023-02-21 10:00",
			"mu" : "1.575",
			"v" : "0.088"
		},
		{
			"d" : "2023-02-21 11:00",
			"mu" : "2.011",
			"v" : "0.436"
		},
		{
			"d" : "2023-02-21 11:00",
			"mu" : "2.060",
			"v" : "0.049"
		}
	],
	"status" : "OK",
	"title" : "Graph counter day"
}
```
So we have two entries for "2023-02-21 11:00". The latter is still increasing (which is correct, we're between 11:00 and 12:00 local time), but the first should have been for "2023-02-21 10:00".

**Comment by arjendekorte** [comment]
It's not only the overlapping bars that are the problem here, it's also that all bars are one hour off (too late).

**Comment by arjendekorte** [comment]
```
		{
			"d" : "2023-02-21 06:00",
			"mu" : "0.000",
			"v" : "0.000"
		},

```
This is can' t be correct, as the central heating starts somewhere between 06:00 and 07:00 on working days, so there must be some usage during that time. My guess is that if this one hour offset for historic data is corrected, everything will be back to normal.

In earlier (pre-2023.1 versions) this used to be correct.

**Comment by GravityRZ** [comment]
i do not know if definitions have changed.
if i see usage at 08:00 that means usage from 07:00-08:00 right.(if not this is wrong because i have usage from 07:00-08:00)

if this is the case then this is the situation at 

14:57

		{
			"d" : "2023-02-21 14:00",
			"mu" : "3.634",
			"v" : "0.304"
		},
		{
			"d" : "2023-02-21 14:00",
			"mu" : "3.918",
			"v" : "0.284"
		}

situation at 

15:01

{			"d" : "2023-02-21 15:00",
			"mu" : "3.973",
			"v" : "0.339"
		},
		{
			"d" : "2023-02-21 15:00",
			"mu" : "3.973",
			"v" : "0.000"
		}


this means that at 14:57 you see
14:00 usage (from 13:00-14:00)
15:00 usage plotted over the 14:00 usage

this means that at 15:01 you see
14:00 usage (from 13:00-14:00)
15:00 usage(from 14:00-15:00)
16:00 usage plotted over the 15:00)


so if somebody can confirm the definition of the usage bars have changed from hour+next hour to previous hour-current hour

we only need to plot the newest data 1 hour ahead instead of the current hour

i think we changed the definition but not the plotting engine

if definitions were not changed (eg bar at 08:00 means usage from 08:00-09:00) then it means that the complete usage for the day has to shift to 1 hour  earlier. current plotting engine is correct

**Comment by arjendekorte** [comment]
That makes no sense to me at all. For people with dynamic tariffs, this means that there would be an offset between the displayed value and the tariff. The gas usage between 23:00 and 00:00 would be displayed with the next day, but tariff will be for the previous day. In honesty, that makes no sense at all.

**Comment by gizmocuz** [comment]
@arjendekorte , Please read my comment above (and again.... maybe again?)
So the last value gets added additionally, and this should not, or at least with another timecode. (1 hour ahead, as this will be the usage for within the next hour as GravityRZ also mentioned)

Now please be patient, we will look into this issue

**Comment by GravityRZ** [comment]
agreed
we need to look why this changed
was it deliberately changed(because somebody thought this was more logical) or is it indeed a bug

00:00-00:59 usage from  0-1
07:00-07:59 usage from 7-8 
08:00-08:59 usage from 8-9

when looking at my situation gas usage started with a bar at 08:00 but reality is there was usage between 07:00-08:00 so it should show at 07:00 like it was before


> That makes no sense to me at all. For people with dynamic tariffs, this means that there would be an offset between the displayed value and the tariff. The gas usage between 23:00 and 00:00 would be displayed with the next day, but tariff will be for the previous day. In honesty, that makes no sense at all.

**Comment by gizmocuz** [comment]
Maybe first have a look at the code that generates this before making assumptions?

**Comment by gizmocuz** [comment]
I think it went wrong with the implementation of the 'Usage' feature...

**Comment by arjendekorte** [comment]
> @arjendekorte , Please read my comment above (and again.... maybe again?) So the last value gets added additionally, and this should not, or at least with another timecode. (1 hour ahead, as this will be the usage for within the next hour as GravityRZ also mentioned)
> 
> Now please be patient, we will look into this issue

@gizmocuz I was responding to the suggestion that the usage bars have changed from hour+next hour to previous hour-current hour. That makes no sense to me at all. I was under the assumption that the fix might be to add the last value with an offset of one hour, so there would be no more overlap, keeping the shift in time. Maybe (possibly) I should just wait and see where this goes.

**Comment by gizmocuz** [comment]
I have a patch/PR waiting to be merged.

Two things have changed in relation to hourly counter graphs (this graph for instance)

values between 14.00-15.00 will be plot at the bar from 14.00
values between 23.00-24.00 will be plot at the bar from 23.00

The Energy graph option is also corrected.

https://github.com/domoticz/domoticz/pull/5615/files

I think this is the desired behaviour?

**Comment by GravityRZ** [comment]
maybe not important but please check(this is were most time sensitive code goes wrong)

do you mean
values between 14.00-14.59 will be plot at the bar from 14.00
values between 23.00-23.59 will be plot at the bar from 23.00

**Comment by arjendekorte** [comment]
Indeed it is, thanks!
![Screenshot_20230221_165230](https://user-images.githubusercontent.com/14976386/220394511-4840c217-c76c-4c2e-a97b-f6c6bf9c9753.png)

**Comment by gizmocuz** [comment]
Perfect! I am merging the PR and building new beta's (15092), should be ready in ~15 minutes

**Comment by GravityRZ** [comment]
Nice. will check as soon as the docker build is available.
Good work

**Comment by gizmocuz** [comment]
Should be ready now

**Comment by GravityRZ** [comment]
first check looks good

old
![image](https://user-images.githubusercontent.com/16853535/220401088-1a6aae42-50ff-4c68-aa6f-997f55741474.png)


new 15092 build
![image](https://user-images.githubusercontent.com/16853535/220401154-48c04f66-f607-4d62-9411-c43153df3dcf.png)

**Comment by gizmocuz** [comment]
Great, thanks for the feedback! Closing issue

**Comment by bijwaard** [comment]
Thanks everybody for the discussion and help to get this fixed!

**Comment by SteffenAL** [comment]
Also a big thanks from me.
