### ISSUE TITLE
Dimmer scripts stopped woking

### ISSUE THREAD

**Issue by devrosx** [domoticz/domoticz#5610]
Hello after this update 
(https://github.com/domoticz/domoticz/commit/ceae5a6f420c4ffeaa2e990e3bb3c4fcce3a8edc)
scripts to control dimmer scripts stoped working (in my case dzvents)
looks like value of dimmer is not updatet (only on or off state)

```
return {
    active = true,
    on = {
        devices = {
            ['cidlo_patro'] = { 'between 19:00 and 07:30' }
        }
    },
    execute = function(domoticz, switch)
        local chodbalight = domoticz.devices(1798)
        local chodbalightlux = domoticz.devices(1838)
        local maxLux = 27

        if chodbalightlux.lux < maxLux and switch.state == 'On' then
            domoticz.log('Device ' .. switch.name .. ' ZAP' .. switch.state, domoticz.LOG_FORCE)
            -- domoticz.log('Device ' .. switch.name .. ' ZAP' .. switch.state)
            chodbalight.switchOn()
            chodbalight.dimTo(65)

        else
            chodbalight.switchOff().afterSec(33)
            domoticz.log('Device ' .. switch.name .. ' VYP' .. switch.state, domoticz.LOG_FORCE)
        end
    end
}
```

also these guys with i think same or similar problem 
(https://www.domoticz.com/forum/viewtopic.php?t=25420)
(https://www.domoticz.com/forum/viewtopic.php?p=299494#p299494)

thanks

**Comment by Onshuis** [comment]
Yes scripts not working, as devrosx is pointing out. When reverting back to prior beta, dimming works again.
Thanks.

**Comment by gizmocuz** [comment]
First forum link is from 2019... 
I thought I already replied to this issue somewhere... pretty sure about it

I added two switches to a dummy hardware and created the following working script:

```
return {
	on = {
		devices = {
			'Test Switch'
		}
	},
	logging = {
		level = domoticz.LOG_INFO,
	},
	execute = function(domoticz, device)
	    local mydimmer = domoticz.devices(8343)
	    
        if device.state == 'On' then
            domoticz.log('Device ' .. device.name .. ' is ON! Level:' .. device.level, domoticz.LOG_INFO)
            mydimmer.setLevel(65)
        else 
            domoticz.log('Device ' .. device.name .. ' is OFF!', domoticz.LOG_INFO)
            mydimmer.switchOff()
        end	    
	end
}

```

**Comment by gizmocuz** [comment]
With the above script, when I press the 'Test Switch' the 'Test Dimmer' will go to 65%, and when I turn off the 'Test Switch' the 'Test Dimmer' will go Off

**Comment by devrosx** [comment]
thanks, about first forum link, his repply is at the bottom with info thats not working with current beta....
Will try to isolate problem with simple script.


BTW
Noticed that in dimmer log are percent values displayed in graph log at the bottom and not in text log (here is only On of Off)

**Comment by Onshuis** [comment]
hmm, well probably the simplest thing to adjust the exsisting script, but it seems it is not for me.
Will try to adjust when i have time, which i dont have now. Thanks though.

**Comment by devrosx** [comment]
ok after testing with script dimmer value ON/OFF is updated OK but not setLevel (percentage), 
noticed that my device is RGBWW, color switch, maybe thats the problem....

found workaround
instead of setlevel
use 
domoticz.openURL({url = 'http://XXXXX/json.htm?type=command&param=setcolbrightnessvalue&idx=1798&hue=261&brightness=30&iswhite=false'})
with json command light works

**Comment by gizmocuz** [comment]
I added a dummy RGBW switch and used this in the above script.
The SetLevel command seems to work correctly (also debugged this in the code)

What happens when you use the above script? Does your RGBW goes to 65?
Does your RGBWW support brightness or can it only be set to a color (or white/warm white)

What type of hardware is your RGBWW switch?

**Comment by Onshuis** [comment]
Could someone help me to change my script, so it is usable again with the new update.
I've been trying to change some things, but i cant get it to work. I probably do not know what i am doing.
Pointing me in the right direction perhaps i could find out myself ?

This is the script i use for my lights:
`commandArray = {}

local BASHSCRIPT = "/home/someuser/Domotica/domoticz/scripts/lua/mochad_dim.sh "  --keep the space at the end!

local X10Address
local bashcall
local intdata

dimmers = {}
-- Dimmer names must be strictly identical to the dimmer labels
dimmers["Lamp TV"]="H1"
dimmers["Lamp Keuken Raam"]="J2"
dimmers["Lamp Aanrecht"]="J3"
dimmers["Lamp Kamer"]="J4"
dimmers["Lamp Eettafel"]="J5"
dimmers["Lamp Banklamp"]="J16"
dimmers["Lamp Kast Buis"]="J11"
dimmers["Lamp Tuin 1"]="J6"
dimmers["Zwembadpomp"]="K2"
dimmers["KerstKeuken1"]="J7"

for deviceName,deviceValue in pairs(devicechanged) do
	--Find the X10 Address 
	X10Address=dimmers[deviceName]
	--If a registered Dimmer
	if X10Address ~= nil then
		-- Create appropriate way to call the BASH script
		print ("Device based event fired on '"..deviceName.."', value '"..tostring(deviceValue).."'");
		if deviceValue == "On" then
			bashcall=BASHSCRIPT ..X10Address.." ".. "On"
       		elseif deviceValue == "Off" then
			bashcall=BASHSCRIPT ..X10Address.." ".. "Off"
		else
			intdata=(tostring(math.floor(tonumber(string.sub(deviceValue,-5,-2))*0.63)))

			bashcall=BASHSCRIPT..X10Address.." "..intdata
		end
		--Call the Bash script
		os.execute(bashcall)
	end
end

return commandArray`

Please ?

**Comment by Onshuis** [comment]
Ah ok, i thought the question was for the other person.
You are right ofcourse, I understand you delete my comment.
I did used the forum, sorry for asking here.
Still my problem exsists but hey.
And thanks for all your free time.
