### ISSUE TITLE
New Alecto SA-30 smoke detector not learned by domoticz

### ISSUE THREAD

**Issue by FirelightLokeren** [domoticz/domoticz#5611]
Hi, I have some Alecto SA-30 smoke detecrors that are working. I have replaced one and I'm not able to connect the new one.
When I check with RFXmgr the not working one is seen with id1-3: 157E00
This are the id1-3's from the woking ones 788A00, 1BBC00, 01C100 and 0B5100

**Comment by gizmocuz** [comment]
Could you post a receive telegram/log of the RFXMngr application?
You have enabled 'accept new hardware' in the settings?

**Comment by FirelightLokeren** [comment]
This one is not seen by domoticz
Packettype = Security1
subtype = SA30 smoke detector
Sequence nbr = 1
id1-3 = 157E00 decimal:1408512
status = Panic
Signal level = 7 -64dBm

This one is seen by domoticz
Packettype = Security1
subtype = SA30 smoke detector
Sequence nbr = 0
id1-3 = 877A00 decimal:8878592
status = Panic
Signal level = 7 -64dBm

Accept new hardware is on

**Comment by gizmocuz** [comment]
Thanks for this. There are no Hex Bytes at the top of the message?
Like a timestamp and then some hex bytes

------------------------------------------------
2/20/2023 08:25:01:192= 1234567890C00000165BD69
Packettype    = RAIN
subtype       = RAIN3 - TFA

Also make sure you have the latest firmware fo the RFXtrx installed

**Comment by FirelightLokeren** [comment]
For the moment I'm not able to connect the rfxcom antenna to my laptop. Next week I will send the complete hex string.

Kind regards
Koen

**Comment by gizmocuz** [comment]
Thanks!

**Comment by gizmocuz** [comment]
@FirelightLokeren , is this still a problem?

**Comment by FirelightLokeren** [comment]
I finaly arived to get the string.

This is what I recieve in RFXMGR


3/03/2023 07:22:23:440= 08200900157E000670
Packettype    = Security1
subtype       = SA30 smoke detector
Sequence nbr  = 0
id1-3         = 157E00 decimal:1408512
status        = Panic
Signal level  = 7  -64dBm

**Comment by gizmocuz** [comment]
Thanks for the log.
Please make sure 'accept new hardware' is enabled in the settings

there is no issue with the latest beta and this device

![image](https://user-images.githubusercontent.com/2265299/227500920-9d25a741-52ea-42c1-863d-9ff8698572fa.png)
