### ISSUE TITLE
Beste Version is older then Stable

### ISSUE THREAD

**Issue by MadPatrick** [domoticz/domoticz#5614]
Hi,

It looks like the stable version is newer then Beta (or vice versa)

![image](https://user-images.githubusercontent.com/81873830/220167075-6e5b93ac-802c-4b37-a334-49f9eebcc6b8.png)

Is the Beta a bit behind in commits from Stable?

**Comment by kiddigital** [comment]
That can happen sometimes as a few commits could be needed when creating the Stable.

These commits are not in the Beta, so beta starts a little behind.

No worries 😁

**Comment by MadPatrick** [comment]
No Problem.
Just a bit confusing

Thanks

**Comment by gizmocuz** [comment]
Yep, will be fixed by itself.
