### ISSUE TITLE
LUA setvalue % is now ON

### ISSUE THREAD

**Issue by Onshuis** [domoticz/domoticz#5618]
There seems to be a bug, but for me, it is not certain.

When I update from beta 14992 to beta 15092, my virtual dimmer devices controlling a lua script do not update the setvalue to their percentage, but only setvalue to 'On'.

I revert back to 14992 then i dim to 50% the light goes to 50% and this is in log:
`
Status: User: admin (IP: xxx.xxx.xxx.xxx) initiated a switch command (172/Lamp Aanrecht/Set Level)
LUA: Device based event fired on 'Lamp Aanrecht', value 'Set Level: 50 %' `

And now with 15092 i dim the light to 50%  i get this:
`
Status: User: admin (IP: xxx.xxx.xxx.xxx) initiated a switch command (172/Lamp Aanrecht/Set Level)
Status: LUA: Device based event fired on 'Lamp Aanrecht', value 'On'`

I have been in conversation on the forum: https://www.domoticz.com/forum/viewtopic.php?p=299691#p299691
Where i was told to better make a new issue. I am sorry for the previous issue that is closed, this seemed to be something different.
Thanks for all your free and spare time. I hope i can make the issue understandable enough so you can do something with it.

**Comment by waltervl** [comment]
So when using in Lua
`for deviceName,deviceValue in pairs(devicechanged) do`
It appears for dimmers that deviceValue is only reporting On/Off and not string 'Set Level: xx%' even when you only change the level from WebGUI when the device is already On.

**Comment by devrosx** [comment]
thanks for reporting that was also problem with my closed bugreport... (probably poorly described...)

**Comment by gizmocuz** [comment]
Yes, I think this has indeed changed. But it is either On or Off and with On (when you have a dimmer) it could also be On on a certain level

**Comment by gizmocuz** [comment]
Is this a big issue?

**Comment by waltervl** [comment]
If you look at the forum topic it is needed to control dimmers that are not fully controlled by RFX. So I think if somehow the dimvalue could be added together with the state One/Off it would be nice. Eg 'On, set level 45%'

**Comment by gizmocuz** [comment]
I have a look at the forum, but i think it is easy to check after it's on, to check it's level

**Comment by waltervl** [comment]
I see that the level is also not reported in the event system device overview anymore, for blinds it still does.

**Comment by gizmocuz** [comment]
I extended the devicechanged_ext with name and state (state is nValueWording)
It is available now in beta 15095

I modified the script, and the below is working.
Please pay attention to the multiply of 0.63, no idea what the maximum dim level can be for X10, maybe 63
As you can see I print the bash script, not execute it, so modify the script to your liking.
If this is working, please also update the forum post

```
commandArray = {}

local BASHSCRIPT = "/home/pi/domoticz/scripts/lua/mochad_dim.sh "  --keep the space at the end!

local bashcall = ""
dimmers = {}

-- Dimmer names must be strictly identical to the dimmer labels
dimmers["Lumiere Salon"]="o4"
dimmers["Lumiere Salle a Manger"]="o6"
dimmers["Lumiere Chambre 1"]="o8"
dimmers["TestDimmer"]="o10"
dimmers["TestSwitch"]="o11"
dimmers["Lumiere Bureau"]="o12"
dimmers["Lumiere Chambre 3"]="o13"

for name,value in pairs(devicechanged_ext) do
	if (name == "name") then
		local X10Address=dimmers[value]
		--If a registered Dimmer
		if X10Address ~= nil then
			-- Create appropriate way to call the BASH script
			local state = devicechanged_ext["state"];
			local level = tonumber(devicechanged_ext["svalue"]);

			print ("idx: "..devicechanged_ext["idx"]..", name: "..devicechanged_ext["name"]..", state: "..state..", svalue: "..tostring(level)..", nvalue: "..devicechanged_ext["nvalue"]);

			if state == "Off" then
				bashcall=BASHSCRIPT ..X10Address.." ".. "Off"
			elseif state == "On" then
				if (level == 0) then
					bashcall=BASHSCRIPT ..X10Address.." ".. "On"
				else
					local intdata=(tostring(math.floor(level*0.63)))
					bashcall=BASHSCRIPT..X10Address.." "..intdata    	    
				end
			end
			--Call the Bash script
			--os.execute(bashcall)		        
			print(bashcall);
		end
	end
end

return commandArray
```

@waltervl , your issue is a different issue and should not be mixed here please

Please note that the best way is to modify the MochadTCP class inside domoticz to support dimming.
It needs to be re-written as the code is old and 'not so good'.

Another option, replace your X10 with Zigbee when it stops because of old age

**Comment by waltervl** [comment]
I think you wanted to mention @devrosx as I do not have a problem (not using lua and RFX), only helped them to troubleshoot the issue they had.

**Comment by gizmocuz** [comment]
@waltervl , no, I was replying to your comment:

`I see that the level is also not reported in the event system device overview anymore, for blinds it still does.`

**Comment by Onshuis** [comment]
Thank you for the changes in the beta and for the changes in the script. It is working, i do get an error, but i have asked this in the forum.

(I wish i could change to zigbee but in my case, there is no zigbee hardware that fits the 5 holes in my wall.)
And again, thanks for all your time.
