### ISSUE TITLE
Wrong year displayed for past/previous years value

### ISSUE THREAD

**Issue by f5bcb** [domoticz/domoticz#5619]
In the Energy (KWh) usage window for the past month, for a given day the year is displayed incorrectly.

Refer to picture here enclosed.

Release 2023.1 running on Raspberry PI Debian.

![21 février_2023](https://user-images.githubusercontent.com/36066477/220754592-4dc9e225-2518-4181-ae06-3d85a18281d3.JPG)
![21 février_2022](https://user-images.githubusercontent.com/36066477/220754593-278e3d39-9039-46e2-8e8f-42fc51e2fb67.JPG)

**Comment by gizmocuz** [comment]
Yes this was a hack to get them in the same graph. It has been like this for many years

**Comment by waltervl** [comment]
Closing this issue as it is as designed/hacked....
