### ISSUE TITLE
MQTT-AD Qubino roller shutter return state not working

### ISSUE THREAD

**Issue by nonolk** [domoticz/domoticz#5620]
Platform Rpi 3B+
Domoticz version 2023.1
zwave-js: 10.10.0 (offcial docker image)

Since the update to latest Domoticz version (2023.1) if my blinds are operated outside domoticz, the return state is not updated in domoticz.

The current state in ZwaveJSui is good, but not in domoticz, operating the blind in domoticz works fine, and status is the correct one.

Status in ZwaveJSui (correct) : 
<img width="1741" alt="Screenshot 2023-02-23 at 17 39 16" src="https://user-images.githubusercontent.com/26922736/220972145-6fdfd311-0212-45f9-88aa-b3ed61e3f620.png">

Status in Domoticz (wrong):
<img width="512" alt="Screenshot 2023-02-23 at 17 41 03" src="https://user-images.githubusercontent.com/26922736/220972490-6ab46ab8-d61c-4135-8e12-c5be7cba828c.png">

Here is the payload in mqtt explorer:
on the mqtt-ad topic:
_{"command_topic":"Zwave/55/38/0/targetValue/set","position_topic":"Zwave/55/38/0/currentValue","set_position_topic":"Zwave/55/38/0/targetValue/set","position_template":"{{ (value_json.value / 99 * 100) | round(0) }}","position_open":99,"position_closed":0,"payload_open":"99","payload_close":"0","device":{"identifiers":["zwavejs2mqtt_0xe8564963_node55"],"manufacturer":"Qubino","model":"Flush Shutter (ZMNHCD)","name":"nodeID_55","sw_version":"71.0"},"name":"nodeID_55_position","unique_id":"zwavejs2mqtt_0xe8564963_Node55_position"}_

on the mqtt topic it self:
_Zwave/55/38/0/currentValue
{"time":1677170619328,"value":90,"nodeName":"","nodeLocation":""}_

This was working perfectly fine in Domoticz 2022.1.

**Comment by gizmocuz** [comment]
Not sure what changed in your ZWaveJS-UI setup, but templates with functions/code are not supported in domoticz

"position_template":"{{ (value_json.value / 99 * 100) | round(0) }}"

this is supported

"position_template":"{{ (value_json.value }}"

Maybe you can change this somewhere

It also does not make any sense to have such a template as the min/max positions are defined in your config

"position_open":99
"position_closed":0

**Comment by gizmocuz** [comment]
In beta 15098 I stripped more calculation stuff from templates. This probably also solves your issue.

**Comment by nonolk** [comment]
Hello @gizmocuz you were totally right. Thanks to you, I found a way to adapt the discovery payload from zwaveJsUi interface, and now it's working perfectly.
I'm just wondering why it happened as I changed nothing, I've just updated the docker container.

Anyway this solved now, thank you for your support.

**Comment by averni59** [comment]
Hello,

I've the same issue. Since I've migrated from OpenZwave to ZwaveJSui shutters' return states are not updated in Domoticz. Templates in my situation also contains functions.
@nonolk Can you please detail what did you adapat in ZwaveJSui to make it works ?

Thank you,

**Comment by gizmocuz** [comment]
@averni59 , could you post your template details? Also make sure you're on the latest beta (or within a beta of 2 weeks)

**Comment by averni59** [comment]
Hello @gizmocuz ,

Here is my payload. Position template is the same as @nonolk :  "position_template": "{{ (value_json.value / 99 * 100) | round(0) }}",

{
  "type": "cover",
  "object_id": "position",
  "values": [
    "38-0-currentValue",
    "38-0-targetValue"
  ],
  "discovery_payload": {
    "command_topic": "zwave/Shutter_Jardin/38/0/targetValue/set",
    "position_topic": "zwave/Shutter_Jardin/38/0/currentValue",
    "set_position_topic": "zwave/Shutter_Jardin/38/0/targetValue/set",
    "position_template": "{{ (value_json.value / 99 * 100) | round(0) }}",
    "position_open": 99,
    "position_closed": 0,
    "payload_open": "99",
    "payload_close": "0",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xc370e642_node5"
      ],
      "manufacturer": "Fibargroup",
      "model": "Roller Shutter 2 (FGR222)",
      "name": "Shutter_Jardin",
      "sw_version": "25.25"
    },
    "name": "Shutter_Jardin_position",
    "unique_id": "zwavejs2mqtt_0xc370e642_Node5_position"
  },
  "discoveryTopic": "cover/Shutter_Jardin/position/config",
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "cover_position"
}

I can't easily try last beta because I use linuxserver docker image which only build with Domoticz stable versions : https://registry.hub.docker.com/r/linuxserver/domoticz/tags

I will try to install last beta from Domoticz official docker registry and let you know : 
https://registry.hub.docker.com/r/domoticz/domoticz/tags

Thank you,

**Comment by gizmocuz** [comment]
@averni59 , and you are using the latest beta where I stripped more from the template?
I just tested and am very positive this has already been solved

**Comment by gizmocuz** [comment]
Ahhh okey then use the official domoticz docker?

**Comment by averni59** [comment]
@gizmocuz i try last beta from offical domoticz docker and I do confirm it works !

Thank you for your help and your awesome job on this projet !

**Comment by gizmocuz** [comment]
@averni59 , In the latest beta version I am now ignoring the state_topic/stat_t when a position topic is configured in the config.
Everything 'should' still work... But I'm not able to verify this.
If possible is it possible to check this?

**Comment by averni59** [comment]
@gizmocuz . I've upgraded to docker version 2024-beta.15841 and I do confirm it's still working.
Thank you.

**Comment by gizmocuz** [comment]
@averni59 , Great!!! Thanks for the feedback!!
