### ISSUE TITLE
RFXtrx433E Invalid data received (Byron SX)

### ISSUE THREAD

**Issue by aj-way** [domoticz/domoticz#5621]
Platform: Raspberry Pi 3B v1.2 (Raspbian)

Since updating to 2023.1 (from 2022.2) a few days ago my 1ByOne PIR sensor and Door bell button no longer work. They had been working reliably for many years. The 433MHz signals are received by a USB RFXCOM RFXtrx433E with the latest firmware (Ext2/1028). All other devices are received OK an transmissions still work. The 1ByOne devices use the Byron SX mode. The devices are listed as 

Type: Chime
SubType: SelectPlus

When the devices transmitted Domoticz reports the following error...
**2023-02-25 12:35:25.711 Error: RFXtrx433E: Invalid data received!....**

**Comment by gizmocuz** [comment]
Thanks for reporting.
It looks there might be a difference in the firmware packet structure between a RFXtrx433E and the XL.
We are investigating this.

**Comment by nigels0** [comment]
Yes, can confirm same issue with Byron SX devices using RFXTX433E

**Comment by sheriffy77** [comment]
I am having the same error message, but i have the RFXtrx433 Type 1 with firmware 1028, so not only the RFXtrx433E seems affected.
The device that gives the error is Siemens JSJS-106 PIR sensor. (detected as Byron SX Chime)

**Comment by gizmocuz** [comment]
Beta version 15099 now accepts both lengths and solves the issue.
Thanks for reporting!

**Comment by aj-way** [comment]
Tested and I confirm this works. Thank you so very much. Beer token sent yesterday in appreciation of your super work.

**Comment by sheriffy77** [comment]
Thanks, all back to normal with the RFXtrx433.

**Comment by LordDarkneo** [comment]
I am interested in a way to debug this error in the RFXcom. Mine has suddenly encountered this error, but I did not add any devices, nor allow new ones... thus I'd like to know why I am havin suddenly this issue in 2022.2)...

**Comment by gizmocuz** [comment]
@LordDarkneo , No idea, but best to update your RFXtrx to the latest firmware, and also use the latest Domoticz version (that might be the beta)
