### ISSUE TITLE
Github - Add built releases as assets in github versions

### ISSUE THREAD

**Issue by Krakinou** [domoticz/domoticz#5622]
Hello,
It's not really a bug but I don't see where to make this request otherwise : 
Would it be possible to add the built tgz released files (downloadable from the [Domoticz Release page](https://www.domoticz.com/releases/?dir=./release) ) as asset in the assets available for each version in the [github versions](https://github.com/domoticz/domoticz/releases)?
Or alternatively, to keep those previous version for a while in the [Domoticz Releases page](https://www.domoticz.com/releases/?dir=./release)?

The reason why I'm asking this is that I have packaged domoticz for [Yunohost](https://github.com/YunoHost/yunohost) and not being able to control the version installed (as only the last stable one is available at any moment in time) causes me quite some problems.
Also, it would allow people to install a previous version should they need it for whatever reason.
Thanks!

**Comment by kiddigital** [comment]
Hi @Krakinou , the build services (both Windows and Linux) create downloadable artifacts so you can download the different Beta's and even the PR builds.

**Comment by waltervl** [comment]
Those artifacts expire after 14 days.

**Comment by kiddigital** [comment]
Older releases can be found (and downloaded) at https://github.com/domoticz/domoticz/releases

**Comment by waltervl** [comment]
Those are only the sources, not the build files.
Best guess would be the docker environment, perhaps you can extract the built files from there. Only for example 2022.2  stable became by accident the same as 2023.1 stable. So next best option would be to build the sources yourself. Or create your own archive of stable releases.

**Comment by Krakinou** [comment]
Hi!
Thanks for your answers! As stated by @waltervl, only the source files are available on the github repo, and having to build the binaries locally on each install may be quite a challenge on small hardware (like old Rasp), not even talking about all the dependencies issues to get to build them on different OS/version/images/etc...
My idea was just to have a way to download the previous build files, not only the current ones, so either:
- by having it as assets in the github version (tbh, I don't have the faintest idea of the amount of work required to do that, but I can see that a lot of github project seems to be doing it, for example [UMS](https://github.com/UniversalMediaServer/UniversalMediaServer/releases)
- or just by keeping the previous release on the domoticz release page, just by changing the file name for each release (eg : domoticz_linux_aarch64_20231.tgz instead of just domoticz_linux_aarch64.tgz ).

 Again, I don't know the amount of work involved for any of these options...
As for creating my own archive... why not... but how the hell do I do that?? :)

**Comment by gizmocuz** [comment]
> (as only the last stable one is available at any moment in time) causes me quite some problems)

Why is this?

**Comment by Krakinou** [comment]
Yunohost aims at integrating application into an easy-to-run self-hosted server: It comes with a lot of  features such as sso, nginx, failtoban and so on that are automagically installed and set up for each application. 
In order to achieve that, the app should have a known behavior. If I don't know which version is installed, I don't know which behavior will have the app : for example in the 2023.1, a user is now created by default and I have to take that into account.

**Comment by gizmocuz** [comment]
Correct, but these this change took years. For the rest it's internal changes.
You can download the binary from our website already (see the command line install script)

**Comment by gizmocuz** [comment]
PR merged, closing issue! Thank you!
