### ISSUE TITLE
Api call : Did not find suitable Authorization 

### ISSUE THREAD

**Issue by PsyOhm23** [domoticz/domoticz#5624]
Hi,

Since the last 2023.1 version, the authorization header is not detected.

Here is my request from logs : 

```
2023-03-02 22:12:17.337  [72b7b200] Debug: [web:8080] Host:127.0.0.1 Uri:/json.htm?type=devices&used=true&displayhidden=1
2023-03-02 22:12:17.337  [72b7b200] Debug: [web:8080] Request Headers:
Host: mydomain.com
X-Real-IP: xx.xx.xx.xx
X-Scheme: https
Connection: close
Authorization: Basic xxxxxxxxxxxxxxxxxxxxxx==
User-Agent: PostmanRuntime/7.31.1
Accept: */*
Cache-Control: no-cache
Accept-Encoding: gzip, deflate, br

2023-03-02 22:12:17.338  [72b7b200] Debug: [web:8080] Did not find suitable Authorization!
2023-03-02 22:12:17.338  [72b7b200] Debug: Web ACLF: 127.0.0.1 - - [02/Mar/2023:22:12:17.337 +0100] "GET /json.htm?type=devices&used=true&displayhidden=1 HTTP/1" 401 91 - "PostmanRuntime/7.31.1"
```

I've checked [the code from where the `Basic` header is read](https://github.com/domoticz/domoticz/blob/3e50bcbb3f63fe83197b663ad995dda899d59db6/webserver/cWebem.cpp#LL1436C31-L1436C31) 

I should have the log written by the following line no? :
`_log.Debug(DEBUG_AUTH, "[Basic] Found a Basic Auth Header (%s)", ah->user.c_str());`

Instead of that, I have the `Did not find suitable Authorization!` log 

Could you tell me what's wrong ?

Thanks in advance

**Comment by kiddigital** [comment]
I see a Proxy is used.

Is the IP address of the proxy in the Trusted Network?

**Comment by PsyOhm23** [comment]
The local IP address of my proxy is 192.168.1.1 and my trusted network list is 192.168.*

If we can see the Authentication header in the log, I don't understand why the header is not interpreted by Domoticz  ?

Thank you for your time

**Comment by kiddigital** [comment]
Try to add the 'auth' debug flag as well and see what additional info is logged.

**Comment by kiddigital** [comment]
> The local IP address of my proxy is 192.168.1.1 and my trusted network list is 192.168.*
> 
> 
Looking at the incoming request, Domoticz reports 127.0.0.1 as the origin of the IP connection.

This is not in the Trusted Network, so the Proxy data is not used.

Are you sure that the credentials are correct? Can you login with these credentials through the UI?

**Comment by PsyOhm23** [comment]
Yes, the credentials are correct, I have successfully login with it outside the trusted network (from my domain).

For info, I have enable the "auth" debug log and I can see that le Authentication header is finally read : 

```
2023-03-03 23:52:37.446  [72b4c200] Debug: [Basic] Found a Basic Auth Header (admin)
2023-03-03 23:52:37.446  [72b4c200] Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 0 ()
2023-03-03 23:52:37.446  [72b4c200] Debug: [web:8080] Did not find suitable Authorization!
```

As we can see, the "admin" user is well decoded from the header but it seems that the [CheckUserAuthorization](https://github.com/domoticz/domoticz/blob/3e50bcbb3f63fe83197b663ad995dda899d59db6/webserver/cWebem.cpp#L1370) returns false !

Unfortunately, there are no more loggers in this method to help me understand what happens.

By the way, I have tested more configurations and one of them let me think there is a security breach when using a proxy like me (maybe I've done something wrong in my nginx or domoticz config) : 
I have updated my trusted network by adding  the 127.0.0.* subnet and domoticz tells now that I am in a trusted network !!

```
2023-03-04 00:13:18.597  [72b4c200] Debug: [web:8080] Host:127.0.0.1 Uri:/json.htm?type=devices&used=true&displayhidden=1
2023-03-04 00:13:18.598  [72b4c200] Debug: [web:8080] Request Headers:
Host: mydomain
X-Real-IP: mypublicip
...
2023-03-04 00:13:18.604  [72b4c200] Debug: [web:8080] IP (127.0.0.1) is within Trusted network range!
2023-03-04 00:13:18.604  [72b4c200] Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 1 (admin)
```

It's probably due to the fact that the detected host is `Host:127.0.0.1`. 
I don't really understand why the detected host is my loopback address. 

So, do you have any idea why the `CheckUserAuthorization` method returns false ?
and could you explain my issue with the trusted loopback address ?

Thanks in advance

**Comment by kiddigital** [comment]
What does the 'Web ACL' logline report? It should state the IP address that is actually used. (So I would expect the IP address given by X-Real-IP)

As Domoticz sees 127.0.0.1 now as a Trusted Network address,
it will look for Proxy headers (as the address of the Proxy can be trusted) and should use the 'X-Real-IP' address as the actual source.

Btw.. try to change to password to something else and see if it works then. Maybe you use some special character, to create a strong password which is good, that somehow is not encoded/decoded properly? Long shot, but just to exclude this scenario.

**Comment by kiddigital** [comment]
I don't think the message means that there is a security breach 😁 It just means the address can be trusted and so in this case the Proxy header info can be trusted and used.

Am I correct in the assumption that you are running NginX on the same machine as Domoticz? That would explain that the loopback interface is used internally on the machine to communicate between Domoticz and NginX.

You can bind Domoticz to a specific interface if you want using commandline options. And tell NginX to forward traffic to that interface. But that is not needed perse as it is fine to use the loopback interface for a setup like this where Domoticz and the Proxy are on the same machine.

**Comment by kiddigital** [comment]
Other question, how does your 'Users' table look like? Many users? Maybe a second 'admin' user? Or disabled admin?

**Comment by PsyOhm23** [comment]
As you suggest, I added a new user  (pi) with a very simple password, then I made some calls :

Without the 127.0.0.1 in the trusted network

    2023-03-04 14:36:54.369  [72b37200] Debug: [web:8080] Host:::1 Uri:/json.htm?type=devices&used=true&displayhidden=1
    2023-03-04 14:36:54.369  [72b37200] Debug: [web:8080] Request Headers:
    Host: mydomain
    X-Real-IP: publicip
    X-Forwarded-For: publicip
    Authorization: Basic xxx
    ...
    2023-03-04 14:36:54.369  [72b37200] Debug: [Basic] Found a Basic Auth Header (pi)
    2023-03-04 14:36:54.369  [72b37200] Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 0 ()
    2023-03-04 14:36:54.370  [72b37200] Debug: [web:8080] Did not find suitable Authorization!
    2023-03-04 14:36:54.370  [72b37200] Debug: Web ACLF: ::1 - - [04/Mar/2023:14:36:54.369 +0100] "GET /json.htm?type=devices&used=true&displayhidden=1 HTTP/1" 401 91 - "PostmanRuntime/7.31.1"

With the 127.0.0.1 in the trusted network

    2023-03-04 14:41:31.687  [72b37200] Debug: [web:8080] Host:::1 Uri:/json.htm?type=devices&used=true&displayhidden=1
    2023-03-04 14:41:31.688  [72b37200] Debug: [web:8080] Request Headers:
    Host: mydomain
    X-Real-IP: publicip
    X-Forwarded-For: publicip
    Authorization: Basic xxxxxx
    ....
    2023-03-04 14:41:31.688  [72b37200] Debug: [Basic] Found a Basic Auth Header (pi)
    2023-03-04 14:41:31.688  [72b37200] Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 0 ()
    2023-03-04 14:41:31.688  [72b37200] Debug: [web:8080] Did not find suitable Authorization!
    2023-03-04 14:41:31.688  [72b37200] Debug: Web ACLF: ::1 - - [04/Mar/2023:14:41:31.687 +0100] "GET /json.htm?type=devices&used=true&displayhidden=1 HTTP/1" 401 91 - "PostmanRuntime/7.31.1"

    
With the 127.0.0.1 in the trusted network and **adding 127.0.0.1 to X-Forwarded-For header**
I made two successives calls :

    2023-03-04 14:52:31.785  [72b37200] Debug: [web:8080] Host:::1 Uri:/json.htm?type=devices&used=true&displayhidden=1
    2023-03-04 14:52:31.785  [72b37200] Debug: [web:8080] Request Headers:
    Host: mydomain
    X-Real-IP: publicip
    X-Forwarded-For: 127.0.0.1, publicip
    Authorization: Basic xxxx
    ....
    2023-03-04 14:52:31.785  [72b37200] Debug: [Basic] Found a Basic Auth Header (pi)
    2023-03-04 14:52:31.786  [72b37200] Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 0 ()
    2023-03-04 14:52:31.786  [72b37200] Debug: [web:8080] Did not find suitable Authorization!
    2023-03-04 14:52:31.786  [72b37200] Debug: Web ACLF: ::1 - - [04/Mar/2023:14:52:31.785 +0100] "GET /json.htm?type=devices&used=true&displayhidden=1 HTTP/1" 401 91 - "PostmanRuntime/7.31.1"
    ...
    2023-03-04 14:52:33.222  [72b37200] Debug: [web:8080] Host:127.0.0.1 Uri:/json.htm?type=devices&used=true&displayhidden=1
    2023-03-04 14:52:33.223  [72b37200] Debug: [web:8080] Request Headers:
    Host: mydomain
    X-Real-IP: publicip
    X-Forwarded-For: 127.0.0.1, publicip
    Authorization: Basic xxxx
    ...
    2023-03-04 14:52:33.223  [72b37200] Debug: [web:8080] IP (127.0.0.1) is within Trusted network range!
    2023-03-04 14:52:33.223  [72b37200] Debug: [web:8080] IP (127.0.0.1) is within Trusted network range!
    2023-03-04 14:52:33.223  [72b37200] Debug: [Basic] Found a Basic Auth Header (pi)
    2023-03-04 14:52:33.223  [72b37200] Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 1 (admin)
    2023-03-04 14:52:33.265  [72b37200] Debug: Web ACLF: 127.0.0.1 - - [04/Mar/2023:14:52:33.222 +0100] "GET /json.htm?type=devices&used=true&displayhidden=1 HTTP/1" 200 2659 - "PostmanRuntime/7.31.1"

When I told you there might be a security breach, it's in this particular case where I make two successives calls with the 127.0.0.1 value in the X-Forwarded-For header.
It seems this is handle by Domoticz to in a different way in the second call :
- We can see the duplicate lines `Debug: [web:8080] IP (127.0.0.1) is within Trusted network range!`
- And we can see `isAuthenticated 1 (admin)` which it not the case on the first call and where the `admin` user is used for an unknown reason (the basic auth is made with **pi** user)
- The Web ACLF line is different from the first call : `Web ACLF: ::1 - -` vs `Web ACLF: 127.0.0.1 - -`
  
For info, I made my tests from different internet connection including 4g shared connection

> Am I correct in the assumption that you are running NginX on the same machine as Domoticz? That would explain that the loopback interface is used internally on the machine to communicate between Domoticz and NginX.

Yes it's correct and I understand that the loopback interface is used between Domoticz and NginX

> Other question, how does your 'Users' table look like? Many users? Maybe a second 'admin' user? Or disabled admin?

Until now, I had only one user, but for the tests, I added a new **pi** user with a simple password

| Activé | Nom   | Droits         | Partage | Dispositifs                |
|--------|-------|----------------|---------|----------------------------|
| Oui    | admin | Administrateur | Non     | Paramétrer les dispositifs |
| Oui    | pi    | Administrateur | Non     | Paramétrer les dispositifs |
|        |       |                |         |                            |

Thank you again for your time 😉

**Comment by kiddigital** [comment]
> As you suggest, I added a new user (pi) with a very simple password, then I made some calls :
> 
> Without the 127.0.0.1 in the trusted network
> 
> ```
> 2023-03-04 14:36:54.369  [72b37200] Debug: [web:8080] Host:::1 Uri:/json.htm?type=devices&used=true&displayhidden=1
> 2023-03-04 14:36:54.369  [72b37200] Debug: [web:8080] Request Headers:
> Host: mydomain
> X-Real-IP: publicip
> X-Forwarded-For: publicip
> Authorization: Basic xxx
> ...
> 2023-03-04 14:36:54.369  [72b37200] Debug: [Basic] Found a Basic Auth Header (pi)
> 2023-03-04 14:36:54.369  [72b37200] Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 0 ()
> 2023-03-04 14:36:54.370  [72b37200] Debug: [web:8080] Did not find suitable Authorization!
> 2023-03-04 14:36:54.370  [72b37200] Debug: Web ACLF: ::1 - - [04/Mar/2023:14:36:54.369 +0100] "GET /json.htm?type=devices&used=true&displayhidden=1 HTTP/1" 401 91 - "PostmanRuntime/7.31.1"
> ```
> 

The test is not working as the request here is handled by an IPv6 interface (::1 = IPv6 localhost). Check the first logline with 'Host' saying on which IP address of the interface Domoticz receives the request. And check the 'Web ACLF' logline to see which IP address has been used to process the request, which could be different from the incoming in case of the use of a trusted Proxy server.

> With the 127.0.0.1 in the trusted network
> 
> ```
> 2023-03-04 14:41:31.687  [72b37200] Debug: [web:8080] Host:::1 Uri:/json.htm?type=devices&used=true&displayhidden=1
> 2023-03-04 14:41:31.688  [72b37200] Debug: [web:8080] Request Headers:
> Host: mydomain
> X-Real-IP: publicip
> X-Forwarded-For: publicip
> Authorization: Basic xxxxxx
> ....
> 2023-03-04 14:41:31.688  [72b37200] Debug: [Basic] Found a Basic Auth Header (pi)
> 2023-03-04 14:41:31.688  [72b37200] Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 0 ()
> 2023-03-04 14:41:31.688  [72b37200] Debug: [web:8080] Did not find suitable Authorization!
> 2023-03-04 14:41:31.688  [72b37200] Debug: Web ACLF: ::1 - - [04/Mar/2023:14:41:31.687 +0100] "GET /json.htm?type=devices&used=true&displayhidden=1 HTTP/1" 401 91 - "PostmanRuntime/7.31.1"
> ```
> 

Here the IPv6 interface is used, so the Trusted network is not used either.

> With the 127.0.0.1 in the trusted network and **adding 127.0.0.1 to X-Forwarded-For header** I made two successives calls :
> 
> ```
> 2023-03-04 14:52:31.785  [72b37200] Debug: [web:8080] Host:::1 Uri:/json.htm?type=devices&used=true&displayhidden=1
> 2023-03-04 14:52:31.785  [72b37200] Debug: [web:8080] Request Headers:
> Host: mydomain
> X-Real-IP: publicip
> X-Forwarded-For: 127.0.0.1, publicip
> Authorization: Basic xxxx
> ....
> 2023-03-04 14:52:31.785  [72b37200] Debug: [Basic] Found a Basic Auth Header (pi)
> 2023-03-04 14:52:31.786  [72b37200] Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 0 ()
> 2023-03-04 14:52:31.786  [72b37200] Debug: [web:8080] Did not find suitable Authorization!
> 2023-03-04 14:52:31.786  [72b37200] Debug: Web ACLF: ::1 - - [04/Mar/2023:14:52:31.785 +0100] "GET /json.htm?type=devices&used=true&displayhidden=1 HTTP/1" 401 91 - "PostmanRuntime/7.31.1"
> ...
> 2023-03-04 14:52:33.222  [72b37200] Debug: [web:8080] Host:127.0.0.1 Uri:/json.htm?type=devices&used=true&displayhidden=1
> 2023-03-04 14:52:33.223  [72b37200] Debug: [web:8080] Request Headers:
> Host: mydomain
> X-Real-IP: publicip
> X-Forwarded-For: 127.0.0.1, publicip
> Authorization: Basic xxxx
> ...
> 2023-03-04 14:52:33.223  [72b37200] Debug: [web:8080] IP (127.0.0.1) is within Trusted network range!
> 2023-03-04 14:52:33.223  [72b37200] Debug: [web:8080] IP (127.0.0.1) is within Trusted network range!
> 2023-03-04 14:52:33.223  [72b37200] Debug: [Basic] Found a Basic Auth Header (pi)
> 2023-03-04 14:52:33.223  [72b37200] Debug: [web:8080] isPage 1 isAction 0 isUpgrade 0 needsAuthentication 1 isAuthenticated 1 (admin)
> 2023-03-04 14:52:33.265  [72b37200] Debug: Web ACLF: 127.0.0.1 - - [04/Mar/2023:14:52:33.222 +0100] "GET /json.htm?type=devices&used=true&displayhidden=1 HTTP/1" 200 2659 - "PostmanRuntime/7.31.1"
> ```
> 

This test is succesfull as the used IP address is within the Trusted network range and then Domoticz selects the first User with admin privileges to use.

What 'worries' me (looking into the code now) is that it seems to ignore the provided credentials (Basic auth header). Either the PI user should be used if the credentials check-out, or if not I would think it should give an Access Denied (401) instead of _falling back_ on the default user because we are in the Trusted Network.


> When I told you there might be a security breach, it's in this particular case where I make two successives calls with the 127.0.0.1 value in the X-Forwarded-For header. It seems this is handle by Domoticz to in a different way in the second call :
> 
>     * We can see the duplicate lines `Debug: [web:8080] IP (127.0.0.1) is within Trusted network range!`
> 
>     * And we can see `isAuthenticated 1 (admin)` which it not the case on the first call and where the `admin` user is used for an unknown reason (the basic auth is made with **pi** user)
> 
>     * The Web ACLF line is different from the first call : `Web ACLF: ::1 - -` vs `Web ACLF: 127.0.0.1 - -`
> 
> 
> For info, I made my tests from different internet connection including 4g shared connection
> 
> > Am I correct in the assumption that you are running NginX on the same machine as Domoticz? That would explain that the loopback interface is used internally on the machine to communicate between Domoticz and NginX.
> 
> Yes it's correct and I understand that the loopback interface is used between Domoticz and NginX
> 
> > Other question, how does your 'Users' table look like? Many users? Maybe a second 'admin' user? Or disabled admin?
> 
> Until now, I had only one user, but for the tests, I added a new **pi** user with a simple password
> Activé 	Nom 	Droits 	Partage 	Dispositifs
> Oui 	admin 	Administrateur 	Non 	Paramétrer les dispositifs
> Oui 	pi 	Administrateur 	Non 	Paramétrer les dispositifs
> 				
> 
> Thank you again for your time 😉

Good to test with the 2 different users, maybe even better if you give the 'pi' user just 'User' privileges (instead of 'admin') so the difference in privileges also is testable.

Please run some more tests and be very conscious on where the requests are coming from and which interface/IP-address is used by Domoticz to handle the request. Make sure to add the `auth` debugflag as well as some important debug information is not revealed in your output!

Maybe it is a good idea to bind Domoticz to a specific interface/IP-address by using the `-wwwbind` commandline option so it is clear on how Domoticz is reached.

**Comment by kiddigital** [comment]
Hi @PsyOhm23 , did you enable 'Allow Basic Auth over HTTP' in the security settings? It looks like you are testing over HTTP and not HTTPS and therefor the Basic auth credentials are ignored!

**Comment by PsyOhm23** [comment]
My bad @kiddigital ! With the enabled *Allow Basic Auth over HTTP* settings, It now works 😃 

I have also removed the 127.0.0.* trusted network to prevent the fallback issue and it works as expected

Anyway, Thank you agin for your time and glad to see that you have fixed the issue regarding the Basic authentication 👍
