### ISSUE TITLE
Error converting meter values leads to subsequent "PO Exception 'stoull'" and sometimes, crashes.

### ISSUE THREAD

**Issue by jefft4** [domoticz/domoticz#5626]
Platform: Ubuntu 22.04
Domoticz: Build Hash: f9b9ac774, Date: 2023-02-14 14:06:40

I think I've finally traced the cause of the several unexplained crashing and failure to restart that I experienced over the last 6 months.  Not sure where the problem lies; will try to have a look closer.  I think it should be possible to replicate this on a test system if more info is needed.

**Situation:**
- 2 dummy devices, used to hold the status codes of solar inverter and battery.
- these are updated via MQTT from a NodeRed flow that interrogates the solar API.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/14252625/222958309-63021087-7e51-4719-b2fe-718f9d2b850e.png">

**Sequence of events leading to the problem:**
- Solar API is busy or unavailable.  NR flow didn't catch the error properly (now fixed!) and pushed empty data (sValue) to domoticz for those two devices.
- This causes domoticz to log some errors:
```
2023-03-04 12:55:00.532  Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 16069, sValue: 'undefined', sUsage: '0', dType: 113, sType: 0)
2023-03-04 12:55:00.532  Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 16070, sValue: 'undefined', sUsage: '0', dType: 113, sType: 0)
2023-03-04 12:55:02.855  Error: [web:8080] PO exception occurred : 'stoull'
2023-03-04 12:56:27.729  Error: [web:8080] PO exception occurred : 'stoull'
2023-03-04 12:56:32.847  Error: [web:8080] PO exception occurred : 'stoull'
2023-03-04 12:56:37.668  Error: [web:8080] PO exception occurred : 'stoull'
2023-03-04 12:56:42.671  Error: [web:8080] PO exception occurred : 'stoull'
2023-03-04 12:56:47.671  Error: [web:8080] PO exception occurred : 'stoull'
<< PO exception error repeats, lots>>

```
- Dashticz, trying to display a dashboard that includes those two devices, also causes the 'PO exception' error every time it attempts to load the page.
- If I restart domoticz at this point, it will crash on restart every time - log attached.

[log_crash_20230304.log](https://github.com/domoticz/domoticz/files/10891719/log_crash_20230304.log)

**Workaround:**
- I deleted the rows for those two devices from 'Meter' and domoticz was happy once more, did not crash on restart.

**Diagnosis:**
- When domoticz is unable to handle the data for the device updates and reports the conversion error, it nonetheless writes something to the 'Meter' table.  This appears to be the cause of the subsequent problems; presumably whatever it stores in 'Meter' isn't valid and causes the later exceptions when Dashticz tries to retrieve the device values.
The data in 'Meter' looks like this:
```
16069|0|0|2023-03-04 13:00:00
16070|0|0|2023-03-04 13:00:00
```
... doesn't appear to be very troublesome! ;-)

Probably, domoticz should not attempt to write to the database when the incoming data is invalid, and/or there's some error trapping needed for invalid data when responding to requests for device values.

I'm happy to help with further diagnosis if needed - as this is just MQTT and the database, I will spin up a domoticz instance in a VM to play with and check that I can replicate the problem.

**Comment by gizmocuz** [comment]
> Probably, domoticz should not attempt to write to the database when the incoming data is invalid, and/or there's some error trapping needed for invalid data when responding to requests for device values.

Okey, so you inject invalid data and expect the application to continue happily? 🤣

I also think Domoticz logs the error just fine

```
Error converting sValue/sUsage! (IDX: 16070, sValue: 'undefined', sUsage: '0', dType: 113, sType: 0)
Error: [web:8080] PO exception occurred : 'stoull'
```

It even tells you the device that is causing the issue

If we did not tell you, you would not have found your issue

**Comment by jefft4** [comment]
Rob, I think you're being a bit unnecessarily defensive there.  It's a pretty standard tenet of design that an application should defend itself against invalid data.  Never trust outside inputs - they're potentially created by buggy code!  So yes, if you put it that way, I absolutely do expect to inject invalid data and the application to continue happily - by rejecting the bad input.  What would you want it to do?
My big concern is that domoticz appears to either reject or handle the bad data but really it writes something to the database that later causes the application to raise further errors and ultimately to crash out.  That's like taking a gun away from someone and then shooting yourself in the foot!

**Comment by gizmocuz** [comment]
Ehmm we do catch the error and we do not crash. We also explain what's wrong.
What more do you want it to do? Make it crash? Silence the error you created?

**Comment by jefft4** [comment]
I think we're not quite understanding one another here.  I'm glad that it caught the bad data; I said that's exactly what it should do.  The problem is what happens after that.  If you read what I wrote, in sequence:

1. bad data is caught and logged
2. something is written to the database
3. when anything tries to query the device state later, it causes errors 'PO exception...'
4. when the dz service is then restarted, it core dumps and won't restart at all - until #2 is undone manually.

#1 is good.  #2 is a design choice.  #3 and #4 are problems... That is why I raised this; there is something in this sequence of events that causes a crash and I offered to help with tracking it down.  You seem to think I'm trying to be a pain; I'm not, I don't write full issue descriptions and post log files for kicks; I'm trying to help!

**Comment by gizmocuz** [comment]
I'm getting you don't worry.... the fix was also very hard to find/solve.

- Search the Domoticz code for 'Error converting sValue/sUsage!'
- Found out that this was on a single place.
- Had a look at the code, and noticed your point '2' ...
- Solved it by adding a 'continue' in the exception handler

Still, this is caused by an external operation. You also talk about a 'crash', from what I see above the exception is handled.

Fix is in beta 15115

**Comment by jefft4** [comment]
The crash was when I restarted the service with those records still in the database.  I attached the domoticz.log to the original post, if you want to see the details...  Preventing the data writing to the db should hopefully remove the need to deal with that, I guess - I'll get my test VM online and load that beta.

**Comment by gizmocuz** [comment]
Thanks please report back your findings

**Comment by jefft4** [comment]
Running 15122 as that's what docker picked up when I created the test system...  Should include the 15115 changes, right?

Unfortunately, I'm still seeing the same behaviour in 15122.

If I send a simple counter an empty string svalue (""), the UI widget shows zero and we get this in the log:
`2023-03-07 09:12:04.403  Error: MainWorker::UpdateDevice exception occurred : 'stoull'
2023-03-07 09:12:04.403  Error: mozzie: Problem updating sensor (check idx, hardware enabled)`

A few minutes after the invalid data, when I return to the utility page of the dashboard, we have no devices displayed and this in the log:
```
2023-03-07 09:20:00.903  Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 1, sValue: '', sUsage: '0', dType: 113, sType: 0)
2023-03-07 09:20:15.636  Error: [web:8080] PO exception occurred : 'stoull'
```
<and repeat each time I go to that page or something tries to retrieve the device state>

If I delete * from Meter and refresh the UI page, all is well once again.  Same fix as previously.  This is a puzzle - the data it writes, looks reasonable; after all, a meter could read zero.  But we get exceptions and no result whenever something tries to retrieve that data.

DeviceStatus looks like this:
`1|3|82001|1|counter1|1|113|0|0|0|12|255|0||2023-03-07 09:12:04|1|0.0|1.0|0.0|1.0|||0|0|0|||
2|3|82002|1|counter2|1|243|28|0|0|12|255|2|10|2023-03-07 09:13:29|2|0.0|1.0|0.0|1.0|||0|0|0|||`
Looks like the empty svalue has resulted in an empty string svalue in DeviceStatus (I checked; its "" rather than null).

Records written to 'Meter':
`1|0|0|2023-03-07 09:10:00
2|0|0|2023-03-07 09:10:00
2|10|0|2023-03-07 09:15:00
2|10|0|2023-03-07 09:20:00`
Interesting that there are no records for idx 1 after 09:10 - looks like there's a process that summarises data for 'Meter' every 5 minutes?  Maybe that's where the first exception is coming from?
Also, I sent an empty string svalue to idx 2 around the same time; that has survived.  idx 1 is a simple counter, idx 2 is an incremental counter, so the difference between the handling of those two sub-types seems to be related to the problem.

I also messed about with a percentage, a THB and a dimmer switch; all survived being sent empty or bad svalues - the widgets either went to zero or went blank, no exceptions or errors.  None of those devices touch the Meter table.

Looking at the handling of inserts/updates to Meter and what causes that exception, I suspect that the problem is with one of the stoull conversions in CSQLHelper::UpdateMultiMeter() being passed an empty string to convert.  I've not had time yet to unpick the code further but will look again later.  I'm also unclear why the RFXMeter type (the failing one) is not mentioned in CSQLHelper::UpdateCalendarMeter while the generic/incremental type and most others are.

**Comment by gizmocuz** [comment]
`Running 15122 as that's what docker picked up when I created the test system... Should include the 15115 changes, right?`
Sure

My patch was made for ::UpdateMeter

Now also made one for multimeter, but that was not what your issue was about

Anyway, if you search for

**UpdateMeter: Error converting sValue/sUsage**

You will find:

```
			catch (const std::exception&)
			{
				_log.Log(LOG_ERROR, "UpdateMeter: Error converting sValue/sUsage! (IDX: %s, sValue: '%s', sUsage: '%s', dType: %d, sType: %d)", sd[0].c_str(), sValue.c_str(), sUsage.c_str(), dType, dSubType);
				continue;
			}
```

And as you can see no values are written to the database

Regarding your invalid percentage data, this does not have any relation to the meter table, it's not a meter type

**Comment by jefft4** [comment]
15128... 
If I send an invalid (empty) sValue, nothing is written to Meter and the log shows exceptions being caught every 5 minutes when the system tries to update Meter.  I guess that's why deleting the records from Meter fixed the problem in testing - if there is no record for the time period, it doesn't try to update it.

However, the UI part of the problem is still with us.  When the invalid data is the last value of the counter, the utility page of the UI doesn't load any widgets. If I then send a valid svalue for the counter, the UI page will load normally after a refresh.

This feels to me like an issue with something in the UI / HTTP handlers not handling the empty sValue in DeviceStatus.

Working through WebServer.cpp, I think that the exception is coming from CWebServer::GetJSonDevices.  The stoull(sValue) at line 10033 in the 'else if dType == pTypeRFXMeter' block has no exception handler. That stoull will raise an exception if sValue isn't a valid numeric string.
I guess an exception from that stoull would escalate and could cause the whole function to fail and thus the UI not to load anything on the utility page?  Does that sound correct?

If that is the cause of the UI not being able to handle the empty sValue, would fixing that function also resolve the issue with Dashticz not loading when svalue isn't numeric, or is Dashticz calling another method?

I guess it's also worth thinking about what other device types might assume they have a numeric sValue and could be tripped up like this...  
The solution is either to catch all exceptions around all string conversion functions, or perhaps to avoid the problem earlier by converting any invalid svalues to zero when they're first received and written to DeviceStatus.  The "write zero" option isn't exactly valid data, but it might avoid other problems - for example, I've not tested it, but I could see potential that non-numeric svalues might cause trouble in data push.

**Comment by gizmocuz** [comment]
`If I send an invalid (empty) sValue, nothing is written to Meter and the log shows exceptions being caught every 5 minutes when the system tries to update Meter. I guess that's why deleting the records from Meter fixed the problem in testing - if there is no record for the time period, it doesn't try to update it.`

This is the correct and intended behavior.

```
CWebServer::GetJSonDevices
I guess an exception from that stoull would escalate and could cause the whole function to fail and thus the UI not to load anything on the utility page? Does that sound correct?
```
Yes, that seems the case. Of course there should be no illegal values in the first place.
I added an exception handler in this function, when this now happens, only this sensor should not be displayed.
(beta 15132)

It is not possible to detect wrongly sValue values as they have different meaning for different type of devices.
And I stick with my original comment. It is up to the (plugin) developer to put valid values inside.

**Comment by waltervl** [comment]
@jefft4 Can you check the UI part issue fixed in beta 15132 as mentioned before?

**Comment by jefft4** [comment]
Yes, fixed, thanks :-)  Just the one sensor that was fed the rotten data goes AWOL, while the rest display as normal.
