### ISSUE TITLE
Domoticz -> Zigbee2mqtt rgbw led lamp not functioning from domoticz

### ISSUE THREAD

**Issue by peteralm097** [domoticz/domoticz#5627]
Hi

I have several of these lamps and they used to work well from Domoticz, however recently they have stopped being able to be controlled by domoticz. There is an occasional flash when setting to 100% however nothing in domoticz seems to control these lights.

It seems to be linked to the on/off command. Once switched on from zigbe2mqtt dashboard they can then be controlled from domoticz - They can also be switched off from domoticz.
I think the issue stems from recent changes to resume level when switch on in domoticz - as when given an "on" from the colour change they work, but not from the app, or floorplan.

They work correctly when controlled from the zigbee2mqtt dashboard, on/off level and colour all work as expected.

Zigbee Model
ZB-CL01
Zigbee Manufacturer
eWeLight
Description
Zigbee 3.0 LED-bulb, RGBW LED
Support status
Supported

{
    "brightness": 253,
    "color": {
        "x": 0.6923,
        "y": 0.3
    },
    "color_mode": "xy",
    "color_temp": 250,
    "linkquality": 105,
    "state": "ON",
    "power_on_behavior": null
}

### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by waltervl** [comment]
Clear your browser cache if the behavior is different from various domoticz pages (floorplan, Dashboard, switches and app).
If using MQTT Autodiscover please check with MQTT explorer if the MQTT messages are still correct.

If you use the Zigbee2mqtt python plugin check the plugin repository for similar issues.

**Comment by gizmocuz** [comment]
No feedback, closing issue.
