### ISSUE TITLE
After upgrade to 2023.1, ESP Easy can't send data to domoticz

### ISSUE THREAD

**Issue by artur5236** [domoticz/domoticz#5628]
Hello,
I have a few ESP with ESP Easy mega software and after upgrade domoticz to 2023.1, ESP can't send data to domoticz. 
This works only when I add my subnet to Local Networks (no username/password) in domoticz, then all it works but I don't want to add my subnet.
I have ESP with configuration to using credentials and it works until I did upgrade domoticz.
![image](https://user-images.githubusercontent.com/19570333/223057661-3799971f-987b-4859-ba6d-5a2a5a9e32de.png)

**Comment by gizmocuz** [comment]
In 'Protocol' above, can you set this to HTTPS? Does this solve the issue?
If not did you try to enable 'Allow Basic Auth over HTTP' in the security settings?

**Comment by artur5236** [comment]
Thank you.
Enabling  'Allow Basic Auth over HTTP' in the security settings helped.

**Comment by gizmocuz** [comment]
Yes, the Domoticz security policy has changed. But there is no option to connect via HTTPS?
It's much more secure and you do not have to enable Baic Auth over HTTP

**Comment by artur5236** [comment]
![image](https://user-images.githubusercontent.com/19570333/223184202-8aef12eb-9eb9-4dda-a056-41bde7ffd3c1.png)

**Comment by gizmocuz** [comment]
Thanks for the screenshot. Yes, I think it's HTTP only
