### ISSUE TITLE
Blockly is not working anymore after update

### ISSUE THREAD

**Issue by bertoost** [domoticz/domoticz#563]
Hi there,

I have setupped several events with Blockly which is working fine before. But after an update to the latest/current stable or even latest beta, it's not working anymore.
LUA events are working fine (as far I tested it).

How can I debug Blockly? Or how can I reset the Blockly events or something?

Thanks.

**Comment by gizmocuz** [comment]
Did you clean the browsers app-cache, and your browser cache?
If you did not re-save the old blockly, then nothing should be changed,
if you did, could you check the database tables 'EventMaster' and 'EventRules'
with this you can debug
I needed to make a lot f changes because of the implementation of the latest blockly (which was needed!), also a blockly screenshot of what you are trying to do would be great
If possible, make a simple blockly that has the problem

**Comment by bertoost** [comment]
I did see the EM en ER tables.. They looked fine to me. The rules where created properly I think. But the events just did not fire at all. 

![2016-03-15_13-28-57](https://cloud.githubusercontent.com/assets/398492/13777702/f4b14216-eab1-11e5-8eed-3c87846f8c1c.png)

This is most simple example, sending a notification. Which is working via LUA.

[edit]
And I did clear caches (my browser doesn't cache at all, since I am a developer too ;-) hehe)

**Comment by gizmocuz** [comment]
This is an invalid blockly, you are testing G-L iPhone Werk with nothing ?

IF A (... is something) then

**Comment by bertoost** [comment]
Sorry.. that was a quick re-create of the event.. This is how it should be, I know.. still not working.

![2016-03-15_13-28-57](https://cloud.githubusercontent.com/assets/398492/13779022/45463694-eab9-11e5-8d9d-37acf67624ca.png)

The "iphone" switches are dummy ones and triggered by an app when I reach my work or home. Work is on at the moment and no messages appearing. Also no logging if I add a "write to log" block.

**Comment by gizmocuz** [comment]
Okey, a few things to double check:
- Is the event system enabled in the settings
- Is the event you created also active ?

I just tested here with this blockly:
![image](https://cloud.githubusercontent.com/assets/2265299/13784326/1e5c6998-eacf-11e5-8678-bed12b2ff6ba.png)

As you can see i write a log message, and i send an email, both things that can be checked if they work.
- open the log, you should see this message
- in the email setup, pressing the 'test' button should send you an email

**Comment by bertoost** [comment]
Yes the system is enabled. Since LUA is working fine.
Of course is the event active too.

And as said, no message or anything happens with a blockly event. LUA is working fine.

**Comment by gizmocuz** [comment]
Try replicating my event

**Comment by bertoost** [comment]
I did...

![image](https://cloud.githubusercontent.com/assets/398492/13858781/6d833fd0-ec80-11e5-8a53-cfb19c679d70.png)

Nothing happend. See;

![image](https://cloud.githubusercontent.com/assets/398492/13858792/8151617c-ec80-11e5-9fd9-e590ee4ef1c5.png)

And no email too...

**Comment by gizmocuz** [comment]
Is it possible someone else can verify this ? As it is working here

@bertoost , could you install the windows version an try ?

**Comment by bertoost** [comment]
I have installed it on een Raspberry Pi. And it worked before. After some updates it stopped working.

**Comment by bertoost** [comment]
Seems that after the last beta update Blockly is working again.. I am getting test messages now from the Blockly event

**Comment by gizmocuz** [comment]
there have been no changes in the last update regarding... but great that it is working now!

**Comment by bertoost** [comment]
Its weird.. My test blockly worked but my disbaled ones, aftelt I enabled them, are not working.
Will try tomorrow whats happening after recreating the events from scratch again.

**Comment by gizmocuz** [comment]
Very wierd indeed

**Comment by gerritv** [comment]
Can you compare the generated  test script with the re-enabled ones?

**Comment by bertoost** [comment]
Blockly events refused from working anyhow.. Very weird, don't know what to do next; still using LUA script "in production" ;-)

**Comment by ghost** [comment]
Hi gizmocuz, the following problem i have today in the last stable version and on the beta (i ve done an update to beta in the hope it works) 
Blocky isn't usable anymore, the only thinks i ve changed was adding a line in the manufactures.xml and added two xml for devices wich aren't in the stable version.

![pic](https://cloud.githubusercontent.com/assets/20950886/17557462/99b90e86-5f17-11e6-93dd-43200c694004.png)

Any idea? browser cache already cleared

**Comment by nesalkiN** [comment]
I have several Lua-scripts saved directly in the web gui and they all worked (**no** scripts saved as .lua in domoticz scripts dir, all entered from the web gui, some disabled). When I added a new event yesterday made using blocks, it just refused to trigger. Googled for hours, tried to use debug logging in Domoticz, looking for errors, grasping at straws. The last thing I tried was to open all saved events, one by one and just pressing "Save". Like magic, the blockly event started to work as it supposed to. :)

Running beta v3.5510 on RPi 2 installed from image (jessie).

**Comment by adrianmihalko** [comment]
I have this problem too.

I am trying to setup a simple event to turn off lamp at a specific time:

http://hopp.mihalko.eu/2bEFvqj

Log:
2016-08-26 22:58:15.357 EventSystem: reset all events...

no new info is added, when event should be triggered.

**Comment by gizmocuz** [comment]
CHRPIE:
Open your chrome browser, enable the development console (F12 under windows)
Go to the network tab, refresh the page, on one of the items in the network tab, press right mouse, from the popup menu choose 'clear browser cache'
(or just clear the appcache and browser cache)

**Comment by Philtass** [comment]
Hello there ! I have same issue with domoticz installed on a RSPI 3B with some blocky and LUA scripts. they where all working but since about 1 month, all blocky scripts don't trigger any more. I've changed nothing at all in scripts bodies. I tried all that's said above: scripts are active, events and dzvents are activated, I refresh cache numerous times, I've edited scripts and save: does nothing. I repeat, all script worked perfectly during few months. Now only LUA scripts are working. Seem problem appeared since last domoticz version update (not beta)
About domoticz infos:
Version: 4.10717
Build Hash: b38b49e5
Compile Date: 2019-05-09 13:04:08
dzVents Version: 2.4.19
Python Version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
Uptime: 20 Heures, 46 Minutes, 10 Secondes 

NB: I've another issue with time triggered LUA scripts that don't trigger anymore. Pb appeared at the same time pb on blocky.

**Comment by rwaaren** [comment]
@Philtass,

you comment on an Issue that was closed 3 years ago. You will probably have a higher chance of a meaningful response if you post this question on the domoticz forum and include what type of hardware and OS you use. Don't forget to mention what you already tried to solve it and any relevant logs.

**Comment by Philtass** [comment]
Ok. Domoticz forum (on domoticz.com) seems to be asleep.How can I open a new stream on github, I'm a newby on github.

**Comment by rwaaren** [comment]
Not sure what you mean by "asleep". Forum is used extensively and most questions receive answers there (also from developers). This github is meant for domoticz code bugs only. As many other domoticz users with the same version do not experience the same as you, I don't expect this to be a code bug. Anyway the forum is the right place; github is not.

**Comment by Philtass** [comment]
Ok. Asleep means no answers to similar question exept trivial "refresh cache"... But i'll try.

**Comment by Philtass** [comment]
Thank for your help anyway
