### ISSUE TITLE
Error messages in new plugin system when calling Update

### ISSUE THREAD

**Issue by Krzysztof1234534** [domoticz/domoticz#5630]
I've added question on forum:
https://www.domoticz.com/forum/viewtopic.php?t=40037
But without response. I suspect that there is a bug, so I'm creating issue here. 
From forum description:

Hi, I'm creating new python plugin, I've decided to use new DomoticzEx interface. Sometimes it seems that in logs there is such message:
Error: WMBus: Update to 'UnitEx' failed to update any DeviceStatus records for key 32/RFM69Temperature/1
I'm using 2022.2 version.
I've decided to write multithread plugin, I've seen that no it is possible and there was examples for that. I need async, because I'm using spidev and RPi.GPIO.
But I'm not sure if it is save to call Unit.Update() function from another thread (not onHeartbeat), documentations says nothing about this. I thought that this is possible, because multiple plugins has now running on different threads, so probably Domoticz is not single thread.

I've search the code and it seams that this message is logged in PythonObjectEx when m_sql.execute_sql returns 0 rows. But I think that bug is in SQLHelper, because there are 2 statements:
sqlStatement.Execute();
result = m_sql.safe_query("SELECT changes();");
There are no lock and no transaction, so between this first and second command some another thread can execute own query.

**Comment by gizmocuz** [comment]
Are you calling/using database queries in your plugin or doing everything via the python script?
(Not that I can help you with the python part, but directly using the database is not a good idea!)

**Comment by Krzysztof1234534** [comment]
Of course not, I'm calling DomoticzEx api, more less something like this:
```
deviceUnit.sValue = total_m3
deviceUnit.Update()
```
I've search code what doing this update method, and this is probably in PythonObjectEx.cpp (CUnitEx_update function).
There is:
```
if (!iRows)
{
    pModState->pPlugin->Log(LOG_ERROR, "Update to 'UnitEx' failed to update any DeviceStatus records for key %d/%s/%d", pModState->pPlugin->m_HwdID, sDeviceID.c_str(), self->Unit);
    Py_RETURN_NONE;
}
```

This is the error I can see in logs. 
Do you need to repeat this or this explanation is enough? My plugin using hardware, so it will not work for you, but I can try to create simplified version of plugin. I have a lot of devices (max idx is 258), probably this will not occur in clean database, because it looks like race condition (I only observing this error 1-2 times per day).

**Comment by Krzysztof1234534** [comment]
I've analysed SQLHelper.cpp and it seams that a lot of functions with executing sqlite3_ functions has such code:
`std::lock_guard<std::mutex> l(m_sqlQueryMutex);`
For example query, queryBlob, DeleteDevices, etc.
But execute_sql does not (this was probably by mistake, because execute_sql does not sqlite3_ has inside directly, it using CSQLStatement, and this class using sqlite3_)

Here I've prepared list of all functions without mutex:
```
safe_UpdateBlobInTableWithID
ScheduleShortlog
ScheduleDay
RestoreDatabase
BackupDatabase
InsertCustomIconFromZipFile
execute_sql
```
What do you think, can this cause such problems?

**Comment by gizmocuz** [comment]
Thanks for checking. That could partly be an issue

**CSQLHelper::safe_UpdateBlobInTableWithID**
**BackupDatabase**

is using a mutex in the top of the function

maybe we should add a mutex in **safe_query**

But have to tripple check if there is no mutex lock after a lock to make sure we have do deadlock

**Comment by gizmocuz** [comment]
Is this still a issue as there is no feedback anymore?

**Comment by Krzysztof1234534** [comment]
I'm still not seeing mutex in execute_sql, so suspect that nothing changed, or do you expect some actions from me?

**Comment by gizmocuz** [comment]
Well I was kind of hoping that you looked into this, changed some code, done some testing and if all was working out maybe make a PR (pull request) 😂

**Comment by Krzysztof1234534** [comment]
I didn't try to fix it, because I have RPi zero, so it is dificult to compile it. But when I find some time I can look at this. If you have some instruction how to cross compile Domoticz on Debian, please send me info on priv

**Comment by gizmocuz** [comment]
you can also compile on your normal pc (debian/windows)

**Comment by Krzysztof1234534** [comment]
I finally have working version without this problems with locks. Do I need some special permissions to pull code to a branch (git push -u origin morelocks), because I've try this and it says permission denied:
fatal: unable to access 'https://github.com/domoticz/domoticz.git/': The requested URL returned error: 403

**Comment by gizmocuz** [comment]
@Krzysztof1234534 , here are the steps to make a PR with the changes

From our github Domoticz repository press the 'Fork' button and form this repository to your own.
Next checkout 'your' Domoticz forked version
Apply the changes
Then commit and push
Now when you look at your domoticz repository on github you should see that yours is one commit ahead, and you can click on this and you should see the option to create a Pull Request (green button)
Sometimes you do not need to click on this and you directly see the Pull Request button (make a browser refresh)
