### ISSUE TITLE
No MQTT message published on action to a selector switch.

### ISSUE THREAD

**Issue by Git-Bruno** [domoticz/domoticz#5632]
Hi
I see no MQTT message published on action to a selector switch for which at least one selector action is defined, in my case a script.
MQTT messages are published if no action is defined in the selector switch.
For On/Off switches a MQTT message is published upon action to a switch regardless an 'On action' of 'Off action' script is defined.

I have not found any doc about a restriction for selector switch and MQTT.
Is there a way to get a MQTT message sent and a script triggered upon a action to a selector switch or is this mutually exclusive ?
Is there a reason for this difference in behavior between On/off switched and selector switch ?

This is with Domoticz Version: 2023.1 Build Hash: f9b9ac774
Thanks

**Comment by gizmocuz** [comment]
@Git-Bruno , please use the forum. Github is used for code related issues.
Also there is no problem with MQTT, I just tested this myself with a dummy selector, 4 actions, 2 http and 2 scripts and a application MQTT Explorer.
Messages are send. Switch level is inside the sValue
