### ISSUE TITLE
Decimal numbers on certain plugin (Mysensors, MQTT Autodiscovery)

### ISSUE THREAD

**Issue by diegoflyer** [domoticz/domoticz#5633]
Most of the devices/plugin runs correctly and transfer decimal points from source data to devices.
This is not true for Mysensors and Zigbee2MQTT, especially on temperature sensor where decimals are rounded to first decimal.
For sure we know that measuring temperature with higher precision than 0.1°C is many times not necessary.
But in other case is a key to have regulation running correctly.
Is there a way to fix it?
Domoticz Version 2023.1 on raspberry pi3b+

**Comment by gizmocuz** [comment]
No, this won't be 'fixed'. Firstly your temperature sensor has probably a accuracy of 1 degress (maybe if your lucky 0.5, if very lucky 0.1, but for sure not 0.05)
And internally we work with 1 decimal

**Comment by diegoflyer** [comment]
Hey this is not true:
![image](https://user-images.githubusercontent.com/46562259/224288055-9edc08f8-3e33-4691-bcb2-0141f7604efb.png)

so also for this we need to remove the second decimal!
And also think that precision and accuracy are 2 different things.
So when you say "Firstly your temperature sensor has probably a accuracy of
1 degrees" you are talking about precision.
Accuracy is a different story, a cheap sensor can have accuracy of 0.01°
and it is ok and must be usable.
And believe me, my sensor has precision and accuracy better than 0.1°.
It is clear that some theory is missing on this approach.
Probably domoticz is not for precise control, I will use something else...
Thanks anyway.

**Comment by gizmocuz** [comment]
Sorry I was not clear. This has been asked before, and no this is not going to be supported as it does not make sense.
Good luck!

**Comment by diegoflyer** [comment]
So you have to fix sensors that current support 0.01 accuracy! ;)

**Comment by gizmocuz** [comment]
I have to do nothing I don't want to 😁 But please feel free to make a PR for this.

Can't be that complicated as some temp sensors (like dummies) already support 2 digits

![image](https://user-images.githubusercontent.com/2265299/224338367-34403ba8-bd3b-4055-8070-b799acebbb68.png)

**Comment by gizmocuz** [comment]
To support two decimals in MQTT-AD was not a big issue, you can try with beta 15139

**Comment by diegoflyer** [comment]
![image](https://user-images.githubusercontent.com/46562259/224469924-b71edeed-55a2-4f63-9200-5887f99da445.png)

Thanks, sorry but my "you have to" was only to explain that is a pity and confusing that dummy sensors support something and the other does not.
With dummy as per image and 0.01 supported diagram are also nicer"view" and with 0.01 data is possible to calculate derivative data (example to build temperature PID control).

What you mean that I can test beta 15139? Did you add something?
I will try but I am not a software specialist, I can write some script but not more than that....

**Comment by gizmocuz** [comment]
Yes, if you are using MQTT-AD (like for zigbee/zwave) you can try the new beta version. There is now support for 2 digits for temperature sensors

Still if you look at (for example) the below temperature sensors (specs at the bottom of the page)

https://www.aqara.com/us/temperature_humidity_sensor.html

it has a precision of 0.3 , this means the value is bogus +/- 0.3 degrees ... 

https://www.mathsisfun.com/accuracy-precision.html
