### ISSUE TITLE
Rfxcom lan selects wrong protocol

### ISSUE THREAD

**Issue by heggink** [domoticz/domoticz#5635]
I just got an rfxcom-868-wifi. Selecting fineoffset results in Davis US being selected instead of fineoffset so looks like a mapping issue. When selecting thru rfxtra manager, services are working fine so only a protocol selection issue...

**Comment by gizmocuz** [comment]
Yes this needs to be corrected, lot's have been changed since the first 868 prototype.
Will do so later, for now, just use the RFXmngr application

**Comment by gizmocuz** [comment]
Will do so shortly as I want to have this corrected for the WiFi versions as well

**Comment by heggink** [comment]
Bert mentioned that much 😁. Thx!

**Comment by heggink** [comment]
Kan je orcon ook vanuit domoticz bedienen? Vraag anders Rob dat ook toe te voegen.  Bert

**Comment by heggink** [comment]
Just noticed that a restart causes domoticz to reinitialise the device again using the wrong settings so every reboot requires starting rfxmgr and resetting the protocol :-(. Any update on this?

**Comment by gizmocuz** [comment]
Ehmm no, we do not set the protocol on start/restart. Did you save it in the RFXMngr application?
When you connect it to your PC and use the RFXMngr application you should still see the protocol you selected (when you saved it)

**Comment by gizmocuz** [comment]
(So test with RFXMngr first, and also take out the cable a few seconds)

**Comment by heggink** [comment]
That's unexpected. Doing power maintenance and my UPS bloody failing on me (shitty APC), everything restarted causing the protocol to be forgotten. Must be the adapter then. Apologies for insinuating domoticz 😩. Will do more digging.

**Comment by gizmocuz** [comment]
No worries, make sure you pressed 'Save' in the RFXMngr application

**Comment by heggink** [comment]
> No worries, make sure you pressed 'Save' in the RFXMngr application

Yeah, that made a diffference indeed. Thanks for hinting.

**Comment by waltervl** [comment]
So Issue solved? Please Close it then.

**Comment by heggink** [comment]
Nope. Issue still open. Workaroudn worked tho :-).

**Comment by gizmocuz** [comment]
Closing issue as the protocol is not selected by Domoticz, not is it set at startup.
This has to be done with the RFXMngr application.
I would also not suggest to change the protocols in Domoticz. They change frequently and you better do this with RFXMngr for the 868 Mhz
