### ISSUE TITLE
Onkyo plugin zone3 selector bug

### ISSUE THREAD

**Issue by albebert** [domoticz/domoticz#5640]
Hi,

i've a bug with Onkyo plugin. 

when i use the onkyo-eiscp command to discover the zone3 selector (with a `onkyo zone3.selector:query` ) domoticz catch the selector but for zone 4.

The command return the right thing : 

`root@domoticz:~# onkyo zone3.selector:query`

`TX-NR818: selector = source`

i'm sure because i don't have a zone 4 and command return N/A 

`root@domoticz:~# onkyo zone4.selector:query`

`TX-NR818: selector = N/A
`

domoticz logs : 

`2023-03-14 07:14:53.335  onkyo: Packet received: 6 SL380
2023-03-14 07:14:53.335  Error: onkyo: Options from 'SelectorStyle:1;LevelNames:Off;LevelOffHidden:true;LevelActions:00': 'LevelActions:MDA=;LevelNames:T2Zm;LevelOffHidden:dHJ1ZQ==;SelectorStyle:MQ=='

2023-03-14 07:14:53.337  onkyo: Light/Switch (Zone 4 selector)
`

Domoticz version 2023.1 on a raspbian 11.6 same issue on a 2022.2
onkyo-eiscp      1.2.7
Onkyo tx-nr818

feel free to ask if you need more stuff

thanks in advance

**Comment by gizmocuz** [comment]
Thanks for pointing out. As you probably have guessed not many users are using a Onkio receiver.
Are you able to make the changes? (And submit a pull request?)

**Comment by albebert** [comment]
Sorry but no :( 

and i don't have the receiver anymore (had just for test).

**Comment by gizmocuz** [comment]
No worries
