### ISSUE TITLE
espEasy values not updating

### ISSUE THREAD

**Issue by CherAlban** [domoticz/domoticz#5645]
Since I upgraded to 1.15163 (Windows11, run as service) none of my espEasy values get updated anymore, problem persists with 1.15165, going back to 1.15091 all good again.

**Comment by waltervl** [comment]
Too little information to work on....
What method do you use to get espEasy to domoticz (MQTT, http ApI calls, plugin?), what does the Domoticz log file say.
Also better to use the bugs and problems forum if you do not know exactly what is going on. https://www.domoticz.com/forum/viewforum.php?f=6

**Comment by CherAlban** [comment]
I am using the espEasy build in "Domoticz Controller" http function, which has been working flawlessly for years:

![image](https://user-images.githubusercontent.com/29152864/225952396-8a47756b-b025-47ad-a369-b4ba3dfbd49d.png)

Domoticz log file does not show anything abnormal.

Sorry for creating an issue for this, I assumed it to be the correct place to report breaking changes.

**Comment by waltervl** [comment]
So you went from current stable 2023.1 to latest beta.
It seems espeasy uses the API way to update sensors. There should be entries in the domoticz logs about incoming connections  from the espeasy device and failures. 
Did you check the security settings? 
Did you change something on User settings? Did the Domoticz IP change?
check also the security related changes. https://www.domoticz.com/wiki/Domoticz_versions_-_Commits

**Comment by Grooenestijnm** [comment]
i'm having the same issue. In the Domoticz log i see "Incoming Domoticz connection from: x"  sourcing from the ESP but the sensor values are not updated.

**Comment by waltervl** [comment]
> i'm having the same issue. In the Domoticz log i see "Incoming Domoticz connection from: x" sourcing from the ESP but the sensor values are not updated.

On current stable 2023.1 or latest beta? And on what beta version did you update from? If on current stable check the Domoticz security settings. See wiki for more info.

**Comment by CherAlban** [comment]
I came from "something between 2023.1 and 1.15163" and updated to 1.15163, noticed the next day that both espEasy were not reporting.

-> no setting or IPs were changed, I verified it is not an updated Windows firewall preventing connections
-> checked the build comments, but could not find anything obviously related
-> tried with the latest 1.15165 beta but with no success
-> reverted to 2023.1

I don't see any "Incoming Domoticz connection from: x" in the logs

**Comment by kiddigital** [comment]
Check Security settings and enable 'Allow Basic Auth over HTTP'. You could add the API address of the ESP to the Trusted Network, but that is not recommended. Read the changelog for security related changes.

Currently in your printscreen you do NOT use 'extended credentials', so most likely because you where in the 'implicit' local network before 2023.1, but you should. Create a separate User for EspEasy that will be used to update Domoticz (instead of implicit Admin user when in Trusted Network). That way, you do NOT need to put the EspEasy in the Trusted Network.

**Comment by CherAlban** [comment]
I always had the local network (192.168.0.*) in the list of trusted networks. 'Allow Basic-Auth over plain HTTP' is disabled. Using theses settings it works in 2023.1, but not in 1.15163

**Comment by gizmocuz** [comment]
@CherAlban , Kiddigital asked to enable this setting

**Comment by CherAlban** [comment]
Sorry for asking twice, I am trying to grasp the changes. If I understand that setting correctly, it will allow the espEasy to authenticate, if I first create user credentials for it. It will also mean, that my local clients will have to use credentials, when enabled. Am I understanding this correctly? If yes, I would prefer to rather just consider my local network and clients as trusted, if possible.  Will the option be deprecated in future versions?

**Comment by gizmocuz** [comment]
When using authentication, ESP-Easy is using HTTP and not HTTPS. We now consider HTTP basic authentication bad practice.
Hopefully in the near feature ESP-Easy will use HTTPS as well.
If you don't use encryption you can whitelist the IP address of this ESP-Easy node.
Are you sure domoticz has IP address 192.168.0.1 ? Sounds like a router address to me.

**Comment by CherAlban** [comment]
> Are you sure domoticz has IP address 192.168.0.1 ? Sounds like a router address to me.

Yes, domoticz has IP address 192.168.0.1:8080


> If you don't use encryption you can whitelist the IP address of this ESP-Easy node.

I thought this is to whitelist  the whole sub-net (espGas IP is 192.168.0.48), and what worked like this for years. 
![image](https://user-images.githubusercontent.com/29152864/226335347-c0103087-1a07-4862-a692-16ddf21c419d.png)
What I do not understand (when reading the updated security info) is why the trusted networks behavior should have changed "around" build 1.15163, hence if this is future intended or unintended behavior.

Many thanks for all of your work and support!

**Comment by waltervl** [comment]
What response do you get if you use the following link (change IDX to an existing device IDX):
`http://192.168.0.1:8080/json.htm?type=devices&rid=IDX`
If setting Allow Basic Auth over HTTP is switched on it should show all the properties of that device. If setting is switched off (default) it should give an authorisation error.

**Comment by CherAlban** [comment]
For testing I updated to the latest build 1.15170

>What response do you get if you use the following link (change IDX to an existing device IDX):
> `http://192.168.0.1:8080/json.htm?type=devices&rid=IDX`

I get the full JSON response on localhost as well as on other machines within the 192.168.0.0/24 network, for both 'Allow Basic Auth over HTTP' enabled and disabled.

espEasy clients don't update for neither 'Allow Basic Auth over HTTP' enabled or disabled

**Comment by waltervl** [comment]
Then espeasy updates also should work. Can you get the update url that espeasy uses to update the device somehere? Does it have logging?

**Comment by CherAlban** [comment]
This is what I see in Wireshark:

`[Full request URI: http://192.168.0.1:8080/json.htm?type=command&param=udevice&idx=1243&nvalue=0&svalue=27&rssi=6]`

**Comment by waltervl** [comment]
So what if you copy that url in a browser? What kind of device is 1243 and is svalue 27 a valid value for this device?

**Comment by CherAlban** [comment]
Using a browser, the device updates OK. 1243 is an incremental counter for electricity, so 27 should represent the number of pulses counted. Now what could be the difference to espEasy?

**Comment by CherAlban** [comment]
I updated all espEasys to the latest firmware [mega-20230306](https://github.com/letscontrolit/ESPEasy/releases/tag/mega-20230306), and now all of them are working OK with 1.15170.

Sorry for bothering you all and many thanks for your support.

**Comment by waltervl** [comment]
OK, closing this.
