### ISSUE TITLE
zwave error Tried adding value, not succeeded!

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#5647]
running build 15092
i know that zwave is going to be phased out.

every once in a while i get this error for a long time now, nothing serious, everything still works

is there an easy way to suppress this error or perhaps avoid it by editing the ozw cache file
as far as i can tell this module does not have a multilevel sensor but accoording to the cachefile it has

the device is a qubino ZMNHADX

`2023-03-19 16:14:43.576 Error: Aeonlabs Z-wave stick Gen5: Value_Changed: Tried adding value, not succeeded!. Node: 11 (0x0b), CommandClass: SENSOR MULTILEVEL, Label: Time, Instance: 1, Index: 33`

**Comment by gizmocuz** [comment]
Yep, time to make the switch!
