### ISSUE TITLE
Change Temperature Units without changing values

### ISSUE THREAD

**Issue by Humanoid-XXX** [domoticz/domoticz#5648]
Hello!

We are sending temperatures from ESPEasy devices to Domoticz  that are in degrees Fahrenheit.
We cannot change this.

Is there a way to simply change the Units in Domoticz without also converting the values?
When I select the Fahrenheit option in the domoticz settings page, it changes the Units from C to F but it also applies the Celsius to Fahrenheit conversion to our already Fahrenheit values. We want to just change C to F in all the graphs and dashboard screens.

Version: 2023.1
Build Hash: f9b9ac774
Compile Date: 2023-02-14 06:06:40
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by kiddigital** [comment]
> Hello!
> 
> We are sending temperatures from ESPEasy devices to Domoticz that are in degrees Fahrenheit. We cannot change this.

Why can this not be changed? You flash/run ESPeasy on the device.

> 
> Is there a way to simply change the Units in Domoticz without also converting the values? When I select the Fahrenheit option in the domoticz settings page, it changes the Units from C to F but it also applies the Celsius to Fahrenheit conversion to our already Fahrenheit values. We want to just change C to F in all the graphs and dashboard screens.
> 
> Version: 2023.1 Build Hash: [f9b9ac7](https://github.com/domoticz/domoticz/commit/f9b9ac7748d3133f68ff3d16b5aaa4d981cda93c) Compile Date: 2023-02-14 06:06:40 dzVents Version: 3.1.8 Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

Domoticz internally works with Celsius and assumes all temperature values are in Celsius. The setting is only to change the way it displayed (and do the math conversion so correct values are shown).

We need something that converts the received Fahrenheit values directly into Celsius either upon reception or before transmitting and store these values as Celsius in the DB. Maybe it is an option to specify the Unit (Celsius or Fahrenheit) upon sending the data to Domoticz, so Domoticz knows what Unit it received and perform the conversion directly if needed.

**Comment by gizmocuz** [comment]
This should be performed by ESPEasy
