### ISSUE TITLE
Requesting Custom Setpoint Device

### ISSUE THREAD

**Issue by Humanoid-XXX** [domoticz/domoticz#5649]
It would be very useful to Have a Custom Setpoint device in which you can select the Unit and Range.
From this we could build any set point device.
For example we could make a Humidistat that can control %RH Relative Humidity from 0-100%.
Or perhaps control Fan Speed from 0-3000 RPM
the possibilities are endless. 

Currently we are using the thermostat setpoint device and just pretending its humidity but that is not very professional. 

Thanks!

**Comment by jgaalen** [comment]
This would be a great feature. I also had a case where I needed a setpoint feature for a custom device which value van be set between 64 and 255. If you can create a custom setpoint to configure something like:
- Min
- Max
- Decimals steps  (either 1, 0.5, etc)

**Comment by gizmocuz** [comment]
This is all already working for MQTT auto discovery and should not be that hard to implement for the rest

**Comment by gizmocuz** [comment]
Actually, working on this at the moment.
Internally it is a 'thermostat setpoint', and I am rebuilding it to a 'general setpoint'.
By default, it will have a temperature unit and a step size of 0.5 and a min=-200 and a max of 200

**Comment by jgaalen** [comment]
Great!

As suggested in my post before, how I see it, such 'setpoint' should have variables such as:

- Min value
- Max value
- Step value
- Unit type (Celsius, Voltage, RPM, Custom whatever)

**Comment by gizmocuz** [comment]
@jgaalen , isn't that exactly what I wrote above?

**Comment by jgaalen** [comment]
Sorry you are right, we're at the same level. Sure you'll make something wonderful

**Comment by waltervl** [comment]
@jgaalen it is now in latest beta I just noticed, so please try it out!

**Comment by waltervl** [comment]
For python plugins you can use options to set the values on device create. Example 
`Options={'ValueStep':'0.5';' ValueMin':'-200';'ValueMax':'200';'ValueUnit':'°C';} `

**Comment by gizmocuz** [comment]
Closing issue as it's implemented now

**Comment by sincze** [comment]
Checked it today and works flawless tnx!

Plugin documentation was also nicely updated.

![image](https://github.com/domoticz/domoticz/assets/5776333/12753b93-a69e-40ac-990c-b89f02092048)
