### ISSUE TITLE
CHttpPoller::WriteToHardware is not implemented

### ISSUE THREAD

**Issue by DeKnep** [domoticz/domoticz#5650]
Domoticz version: 2023.1 build 15163.

Please see https://www.domoticz.com/forum/viewtopic.php?t=40110 including the post in there with my analysis: https://www.domoticz.com/forum/viewtopic.php?p=301077#p301077

That forum topic describes a valid scenario for having a virtual switch device as a child of HTTP/HTTPS poller hardware.
However, that doesn't work because CHttpPoller::WriteToHardware is not implemented.
It looks like this can be fixed by reusing the implementation from CDummy::WriteToHardware.

**Comment by gizmocuz** [comment]
Yes, or just return true

**Comment by gizmocuz** [comment]
@DeKnep , kiddigital made a PR that has been merged into beta 15177. Could you check this version?

**Comment by DeKnep** [comment]
> @DeKnep , kiddigital made a PR that has been merged into beta 15177. Could you check this version?

Tested it and it works as expected.
@kiddigital & @gizmocuz: thanks!
