### ISSUE TITLE
Restore from 2020.2 (on DS215+) to 2023.1 (on DS718+) :  Error opening serial port !

### ISSUE THREAD

**Issue by boggiz** [domoticz/domoticz#5651]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by waltervl** [comment]
From the Title: This is not a Domoticz code bug but a configuration issue. So this will be closed. Use the forum for community assistance as mentioned in the Issue guidelines you posted.... 
So please make a topic on https://www.domoticz.com/forum

**Comment by boggiz** [comment]
Hello, when I restore my DB on my new NAS DS718+ I have this error: 'Error sending switch command, check device/hardware (idx=1) !' may be the 'Error opening serial port is the cause'. But why  ? /dev/ttyUSB0 is  done for the RFXcom. Thank's for your help

**Comment by gizmocuz** [comment]
Please use our forum

**Comment by boggiz** [comment]
OK. Excuse me
