### ISSUE TITLE
Improvement for the PVOUTPUT Input

### ISSUE THREAD

**Issue by CvvtLo** [domoticz/domoticz#5655]
I would like to propose an improvement for the PVOUTPUT Import hardware:
--> Add retries in the connect to PVOUTPUT.org, since I sporadically receive error login notifications :

I changed the pvoutput_input.cpp  , GetMeterDetails() method , please review code  , I could not build it (search for connectTries )

 
void CPVOutputInput::GetMeterDetails()
{
	if (m_SID.empty())
		return;
	if (m_KEY.empty())
		return;

	bool success ;
	int connectTries = 5;

	std::string sResult;

	std::stringstream sstr;
	sstr << "https://pvoutput.org/service/r2/getstatus.jsp?sid=" << m_SID << "&key=" << m_KEY;

	for (size_t i = 0, success = false; i < connectTries; i++)
	{
		if (!HTTPClient::GET(sstr.str(), sResult))
		{
			sleep_milliseconds(400);
		}
		else
		{
			success = true;
			break;
		}

	}

	if (!success)
	{
		Log(LOG_ERROR, "Error login after multiple retries!");
		return;
	}

	std::vector<std::string> splitresult;
	StringSplit(sResult, ",", splitresult);
	if (splitresult.size() < 9)
	{
		Log(LOG_ERROR, "Invalid Data received!");
		return;
	}
	/*
		0-Date	yyyymmdd	date	20100830	r1
		1-Time	hh : mm	time	14 : 10	r1
		2-Energy Generation	number	watt hours	12936	r1
		3-Power Generation	number	watt	202	r1
		4-Energy Consumption	number	watt hours	19832	r1
		5-Power Consumption	number	watt	459	r1
		6-Normalised Output	number	kW / kW	0.083	r1
		7-Temperature	decimal	celsius	15.3	r2
		8-Voltage
	*/

	double Usage = 0;
	if (splitresult[3] != "NaN")
	{
		Usage = atof(splitresult[3].c_str());
	}
	if (Usage < 0)
		Usage = 0;

	double Consumption = 0;
	if (splitresult[5] != "NaN")
	{
		Consumption = atof(splitresult[5].c_str());
		if (Consumption < 0)
			Consumption = 0;
		m_bHadConsumption = true;
	}

	if (splitresult[6] != "NaN")
	{
		double Efficiency = atof(splitresult[6].c_str()) * 100.0;
		if (Efficiency > 100.0)
			Efficiency = 100.0;
		SendPercentageSensor(1, 0, 255, float(Efficiency), "Efficiency");
	}
	if (splitresult[7] != "NaN")
	{
		double Temperature = atof(splitresult[7].c_str());
		SendTempSensor(1, 255, float(Temperature), "Temperature");
	}
	if (splitresult[8] != "NaN")
	{
		double Voltage = atof(splitresult[8].c_str());
		if (Voltage >= 0)
			SendVoltageSensor(0, 1, 255, float(Voltage), "Voltage");
	}

	sstr.clear();
	sstr.str("");

	sstr << "https://pvoutput.org/service/r2/getstatistic.jsp?sid=" << m_SID << "&key=" << m_KEY << "&c=1&df=19700101&dt=26000101";

	for (size_t i = 0,success = false; i < connectTries; i++)
	{
		if (!HTTPClient::GET(sstr.str(), sResult))
		{
			sleep_milliseconds(400);
		}
		else
		{
			success = true;
			break;
		}

	}

	if (!success)
	{
		Log(LOG_ERROR, "Error login after multiple retries!");
		return;
	}

	StringSplit(sResult, ",", splitresult);
	if (splitresult.size() < 11)
	{
		Log(LOG_ERROR, "Invalid Data received!");
		return;
	}
/*
	0-Energy Generated	number	watt hours	246800
	1-Energy Exported	number	watt hours	246800
	2-Average Generation	number	watt hours	8226
	3-Minimum Generation	number	watt hours	2000
	4-Maximum Generation	number	watt hours	11400
	5-Average Efficiency	number	kWh/kW	3.358
	6-Outputs	number	-	27
	7-Actual Date From	yyyymmdd	date	20100901
	8-Actual Date To	yyyymmdd	date	20100927
	9-Record Efficiency	number	kWh/kW	4.653
	10-Record Date	yyyymmdd	date	20100916
	11-Energy Consumed	number	watt hours	10800
	12-Peak Energy Import	number	watt hours	5000
	13-Off Peak Energy Import	number	watt hours	1000
	14-Shoulder Energy Import	number	watt hours	4000
	15-High Shoulder Energy Import	number	watt hours	800
	16-Average Consumption	number	watt hours	1392
	17-Minimum Consumption	number	watt hours	10
	18-Maximum Consumption	number	watt hours	2890
	19-Credit Amount	decimal	currency	37.29
	20-Debit Amount	decimal	currency	40.81
*/
	double kWhCounterUsage = 0;
	if (splitresult[0] != "NaN")
	{
		kWhCounterUsage = atof(splitresult[0].c_str());
	}
	SendKwhMeter(0, 1, 255, Usage, kWhCounterUsage / 1000.0, "SolarMain");

	if (m_bHadConsumption)
	{
		if (splitresult.size() > 11)
		{
			double kWhCounterConsumed = 0;
			if (splitresult[11] != "NaN")
			{
				kWhCounterConsumed = atof(splitresult[11].c_str());
			}
			
			if (kWhCounterConsumed != 0)
			{
				SendKwhMeter(0, 2, 255, Consumption, kWhCounterConsumed / 1000.0, "SolarConsumed");
			}
		}
	}
}

**Comment by gizmocuz** [comment]
What kind of network/internet connection do you have? Do you connected Domoticz via a TCP/IP cable?
This is the first time I hear this, and it seems to be a connection issue on your side...

Please define 'sporadically' .... if it happens you miss 5 minutes of data

Does it need to be 5 times?

**Comment by CvvtLo** [comment]
Domoticz is running on a RPI connected via tcp/ip cable on the rj45 connector.
I do get email notifications once or twice a day that login failed.
Perhaps it has something to do with another system in my network that sends the solar data to pvoutput and uses the same external IP address.

I created a fork , will test it on a VM with Vagrant, compiling and building on the RPI takes to long.

**Comment by CvvtLo** [comment]
Hi Gizmocuz,

I added  this to the code of   **domoticz/hardware/PVOutput_Input.cpp**

	_success = false;

	for (size_t i = 0; i < connectTries; i++)
	{
		if (!HTTPClient::GET(sstr.str(), sResult))
		{
			sleep_milliseconds(400);
			Log(LOG_ERROR, "PVOutPut service GETSTATUS failed : %s" , sResult.c_str());

		}
		else
		{
			success = true;
			Log(LOG_STATUS, "PVOutPut service GETSTATUS connected after %li retries" , i);
			break;
		}

	}

	if (!success)
	{
		Log(LOG_ERROR, "PVOutPut service GETSTATUS: Error login after multiple retries!");
		return;
	}_

In the Domoticz Log : 

2023-05-08 15:27:40.057 Error: pvoutput pel5: PVOutPut service GETSTATUS failed : Forbidden 403: Exceeded 60 requests per hour
2023-05-08 15:27:41.194 Error: pvoutput pel5: PVOutPut service GETSTATUS failed : Forbidden 403: Exceeded 60 requests per hour
2023-05-08 15:27:42.332 Error: pvoutput pel5: PVOutPut service GETSTATUS failed : Forbidden 403: Exceeded 60 requests per hour
2023-05-08 15:27:43.483 Error: pvoutput pel5: PVOutPut service GETSTATUS failed : Forbidden 403: Exceeded 60 requests per hour
2023-05-08 15:27:44.643 Error: pvoutput pel5: PVOutPut service GETSTATUS failed : Forbidden 403: Exceeded 60 requests per hour
2023-05-08 15:27:44.643 Error: pvoutput pel5: PVOutPut service GETSTATUS: Error login after multiple retries!


So the real cause of the so called "Login Failed"  is a Forbidden 403 error, caused by the PVOUTPUT limitation of 60 requests per hour.
As you can see also, adding retries does not make sense in this case.

So the only improvement i would suggest is to replace the original 2 logs 
		Log(LOG_ERROR, "Error login!");
by

		Log(LOG_ERROR, "PVOutPut service GETSTATUS failed : %s" , sResult.c_str());
and
                Log(LOG_ERROR, "PVOutPut service GETSTATISTIC failed : %s" , sResult.c_str());

**Comment by gizmocuz** [comment]
I modified the code and added the error reason and retry.
The poll interval is set to 5 minutes, how can you get that exceeded error? That should be 12 requests in an hour.

Implemented in beta 15234

**Comment by CvvtLo** [comment]
Thanks.
I forced it to 1 minute for testing.
In real live , I have another application uploading data to PVOUTPUT which uses the same account and so uses a part of the 60 requests quota

**Comment by gizmocuz** [comment]
The update interval is 5 minutes, so uploading every 5 minutes (12 calls) sound ideal.
