### ISSUE TITLE
DZGA cannot connect anymore above version Version: 2023.1 (build 15178)

### ISSUE THREAD

**Issue by davidKooreman** [domoticz/domoticz#5656]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by gizmocuz** [comment]
Could you please explain what you mean with DZGA?

**Comment by rezzalex** [comment]
Domoticz Google Assistant.
Another project.
https://github.com/DewGew/Domoticz-Google-Assistant
It has always worked for me, even with the latest versions.

**Comment by gizmocuz** [comment]
Okey, please create a issue on their github
