### ISSUE TITLE
2023.1 - Error messages around 23:00hr

### ISSUE THREAD

**Issue by 0crap** [domoticz/domoticz#5657]
Since updating to Domoticz 2023.1 I often see an Error about my Envoy-S logged, always around the same time.

I don't use the native Envoy script, but the one from [H4nsie](https://github.com/H4nsie/EnphaseEnvoy).
![Envoy-S](https://user-images.githubusercontent.com/31951195/228282877-65b9772b-244a-492a-9240-0e24f649e291.png)

Nothing has changed on the script, nor anything on my Envoy.
Only thing that I have updated is Domoticz to the latest stable. (2023.1)

Is there anything special about the timestamp below in combination with Domoticz 2023.1 that might explain this?
The previous version of Domoticz has never seen this issue.

_2023-03-18 23:01:00.926 Error: Envoy-S hardware (6) thread seems to have ended unexpectedly
2023-03-19 23:01:03.852 Error: Envoy-S hardware (6) thread seems to have ended unexpectedly
2023-03-21 23:00:43.114 Error: Envoy-S hardware (6) thread seems to have ended unexpectedly
2023-03-22 23:00:51.224 Error: Envoy-S hardware (6) thread seems to have ended unexpectedly
2023-03-22 23:01:05.227 Error: Envoy-S hardware (6) thread seems to have ended unexpectedly
2023-03-23 23:00:31.748 Error: Envoy-S hardware (6) thread seems to have ended unexpectedly
2023-03-24 23:00:33.150 Error: Envoy-S hardware (6) thread seems to have ended unexpectedly
2023-03-25 23:00:25.601 Error: Envoy-S hardware (6) thread seems to have ended unexpectedly_

**Comment by kiddigital** [comment]
Are you sure your time on your machine is up-to-date/in sync?

Check the changelog to see if anything related to the Envoy-S hardware has changed.

Often when something happens at a specific time, there is some other process/program being executed that interferes with Domoticz in this case and the Ensoy-S hardware thread in particular. It is the internal Domoticz watch-dog that signals that the Envoy-S hardware thread did not update its heartbeat and therefor is restarted.

**Comment by rezzalex** [comment]
Hello, I use the "standard"  "Enphase Envoy with LAN (HTTP) interface Version: D7.0.88" plugin.
I always have the very same error at the same time, but it seems to have gone aways since... ? The latest version of the plugin ? not really sure...

@0crap , what are the différences between the [H4nsie envoy plugin ](https://github.com/H4nsie/EnphaseEnvoy) and the DZ embedded (Enphase Envoy with LAN (HTTP) interface Version: D7.0.88) ?

**Comment by 0crap** [comment]
> Are you sure your time on your machine is up-to-date/in sync?
_Yes, running on my Raspberry Pi3. No time sync problem there._
> 
> Check the changelog to see if anything related to the Envoy-S hardware has changed.
_Nothing has changed. Software version is the same for ages now._
> 
> Often when something happens at a specific time, there is some other process/program being executed that interferes with Domoticz in this case and the Ensoy-S hardware thread in particular. It is the internal Domoticz watch-dog that signals that the Envoy-S hardware thread did not update its heartbeat and therefor is restarted.

_Yeah, I think you're right on this one. Hard to tell what the trigger is...._

**Comment by 0crap** [comment]
> Hello, I use the "standard" "Enphase Envoy with LAN (HTTP) interface Version: D7.0.88" plugin. I always have the very same error at the same time, but it seems to have gone aways since... ? The latest version of the plugin ? not really sure...
> 
> @0crap , what are the différences between the [H4nsie envoy plugin ](https://github.com/H4nsie/EnphaseEnvoy) and the DZ embedded (Enphase Envoy with LAN (HTTP) interface Version: D7.0.88) ?

Interesting you have seen the same on the native implementation.
I have looked at the differences a bit more _[here](https://github.com/H4nsie/EnphaseEnvoy/issues/5)_.
The differences are mostly personal preference and of course if one switches you lose all your history.

**Comment by waltervl** [comment]
> The differences are mostly personal preference and of course if one switches you lose all your history.

If the devices are the same you can use the replace function (in device widget  Edit) to replace to the old by the new with keeping the history of the old device in the new device.

**Comment by 0crap** [comment]
> > The differences are mostly personal preference and of course if one switches you lose all your history.
> 
> If the devices are the same you can use the replace function (in device widget Edit) to replace to the old by the new with keeping the history of the old device in the new device.

Good tip. 💯 
That will probably work for the individual inverters, because they are both Type: General, kWh.
However the "Total counter" is different. Script uses Type: P1 Smart Meter, Energy and native uses Type: General, kWh.

**Comment by waltervl** [comment]
Closing this issue as it is not yet related to a domoticz code bug (could be the python plugin or another process that stops the python plugin). Please continue on the Domoticz forum. https://www.domoticz.com/forum
If it in the end related a some Domoticz bug/code issue then a new issue can be opened.
