### ISSUE TITLE
Dashboard timer not updating automatically

### ISSUE THREAD

**Issue by bertoost** [domoticz/domoticz#5658]
Hi there,

I just installed a fresh setup on my RaspberryPi 4 and did not configure any devices yet. I saw the time on the dashboard is standing still. I tried updating using `./updaterelease` and `./updatebeta` but both are not working.

Can you help me out?

Regards, Bert

**Comment by waltervl** [comment]
This is not the place to discuss this. Please use the forum: https://www.domoticz.com/forum/
One hint: Did you clear your browser cache as it solves most UI issues.
Closing this issue now, so also please do not continue in this topic.
