### ISSUE TITLE
Enphase plugin does create Envoy devices

### ISSUE THREAD

**Issue by Refhi** [domoticz/domoticz#5659]
So on my docker domoticz install which runs at home (with almost a hundred devices) : 
- I try to add an enphase Harware => it works, and adds the Inverters in the devices if enabled, but not "Enphase kWh Production", "Enphase total-consumption" or "Enphase net-consumption"

On a fresh docker install with the exact same id/setup/ip/version etc. : 
- it adds everything properly and works perfectly, including the 3 "Enphase [...]" devices

The Enphase Hardware is on software: D7.0.88 version and it just got installed a few days ago.

I tried getting interesting log, but the only thing I spot is the no-creation of the "Enphase [...]" devices after adding the hardware.

I'm guessing it have to do with a problem in my database.

Is there more data I could provide to help fix the issue ?

**Comment by reinos** [comment]
~~Same issue here. I created a new hardware as documented here https://www.domoticz.com/wiki/Enphase ) no token is asked. The hardware is created successfully but no device is added.~~

~~The log says:~~

```
2023-03-30 08:22:59.669 Status: Enphase: Worker started...
2023-03-30 08:23:03.750 Status: Enphase: Connected, serial: 122241010935, software: D7.6.168
```

~~I also can see that the token has been generated in the user variable section~~

~~Currently it is after sunrise, my panels a producing energy, so it should work as documented.~~

~~Running Domoticz in Docker with image `domoticz/domoticz:2023.1`~~

~~Not sure if this is also related to https://github.com/domoticz/domoticz/issues/5590? Should we upgrade to the latest `beta` version?~~

**UPDATE**
It seems my devices are created but they where not set as used.

![Screenshot 2023-03-30 at 09 25 14](https://user-images.githubusercontent.com/633730/228761203-533ccf7d-4b45-4faa-8361-f1d102fa08fc.png)

**Comment by waltervl** [comment]
Closing this issue as its seems configuration issue. Please use the forum for this as it reaches much more audience. https://www.domoticz.com/forum

**Comment by Refhi** [comment]
Hi,

Thanks for your attention in this issue, but I think my issue was a different from reinos' (I reproduced a different behaviour in two separate installs) :-/

Thanks

[edit] :
Ok, last word on this :
- the Inverters devices are created no matter your settings
- but the Envoy devices are created only if "allow new devices" is set in the settings.
thanks for the pointers @waltervl

**Comment by waltervl** [comment]
I know but because it works in a new install it should also work in an existing install. So perhaps something in your current install is blocking. Therefore please use the forum.
