### ISSUE TITLE
Domoticz seems case sensitive when checking X-Real-IP and X-Forwarded-For

### ISSUE THREAD

**Issue by dobber81** [domoticz/domoticz#5661]
I am having a problem with pfsense, haproxy and domoticz.

Domoticz would always show the pfsense internal ip, not the external ip of the connected client in the log. 

I have found that haproxy rewrites X-Real-IP and X-Forwarded-For to all lower case.
This also affects security since I had my internal pfsense ip whitelisted since merge of proxy and client whitelist.

I did some wiresharking and found this:
haproxy:
    x-real-ip: 83.185.83.xxx\r\n
    x-forwarded-for: 83.185.83.xxx\r\n

Synology/nginx:
    X-Real-IP: 83.185.83.xxx\r\n
    X-Forwarded-For: 83.185.83.xxx\r\n

When domoticz searches for X-Real-IP it finds nothing when client is connected through haproxy. In my case leaving my domoticz installation wide open to the internet without password protection.

I would like to request that the search is non-case-sensitive and that proxy ips has its own box again. It is really dangerous to combine it with client whitelist, requiring no password if proxy is not configured properly.

For others with the same issue there is a temporary fix in haproxy until servers get up to spec with RFC7230 and HTTP/2:
https://cbonte.github.io/haproxy-dconv/2.2/configuration.html#h1-case-adjust

**Comment by kiddigital** [comment]
Hi @dobber81 , good catch. I agree that the headers should be case-insensitive as per RFC7230. I will create a PR for that.

**Comment by dobber81** [comment]
@gizmocuz How do you feel about proxy ips having its own box again? It is really dangerous to combine it with client whitelist, requiring no password if proxy is not configured properly. If a proxy update/config goes wrong domoticz is wide open from the internet with no password protection. This could become quite a security issue.

**Comment by gizmocuz** [comment]
I don't mind two separate boxes... it would also make it a lot clearer for end users who have no idea what a proxy is
