### ISSUE TITLE
MQTT AD Two separate (zigbee) actions creating and triggering just one Domoticz device 

### ISSUE THREAD

**Issue by d-EScape** [domoticz/domoticz#5664]
**EDIT:** To safe you some time reading... The problem is that MQTT AD in Domoticz generates UnitID's based on the CRC of the (zigbee) action names. It turnes out these are not necessarily unique within the same device. 
E.g. "brightness_move_down_2" has the same crc as "brightness_move_up_4", so they can not both be added to the Domoticz device. 

_You can read my journey to this conclusion below..._

The "ROB_200-007-0" 8-button wall transmitter generates 5 actions per pair of buttons. Domoticz does not create a separate switch device for all of them. An issue that seems to be causes by the way Domoticz assigns UnitID's.

Each on/off pair (row) of buttons generates actions like these for row 4:
on_4 (=press left)
brightness_move_up_4 (=hold left)
off_4 (=press right)
brightness_move_down_4 (=hold right)
brightness_stop_4 (=release either)

Domoticz creates switches for most of these actions, but somehow confuses a few of them.
"brightness_move_up_4" and "brightness_move_down_2" are treated as one and the same button and only one switch will be created in Domoticz. It will get the name of the first button pressed and then the other button will simply trigger the same Domoticz device. The same goes for "brightness_move_down_4" and "brightness_move_up_2".

I have checked all I could find in the MQTT messages/autodiscovery (content below) and the actions seem to be correct.
Removing and repairing in zigbee2mqtt did not make a difference. Neither did a complete recreate of the mosquitto database.
Removing the devices from Domoticz and recreating them showed that the fist button pressed was the name Domoticz would use for the single device, so Domoticz is seeing the correct action names.

It also revealed that Domoticz is always assigning the same unit numbers to the actions of the wall transmitter (after removing and recreating).
187 is always ...action_on_2
150 is always 	...action_brightness_move_down_3
etc.
167 is alway ...action_brightness_move_up_4 OR ...brightness_move_down_2, depending on what button was first pushed after removing all previous created devices. 

These unit numbers are nowhere to be found in the MQTT messages, so I think Domoticz is generating them. With my limited coding skills I could not find what they are based on, but it looks like the numbers chosen are causing the conflict. 

I suspect (but do not know, because I don't fully understand the code!) it has something to do with line 2993 of MQTTAutoDiscover.cpp. The if statement around it will probably lead to this calculation for (I think?) a UnitID, because the action is not just "brightness_down", but has a row number attached like "brightness_down_4"
The calculation is "pSensor->devUnit = Crc8(0, (uint8_t*)pSensor->last_value.c_str(), pSensor->last_value.size());"

Tested with latest stable and beta 2023.1-15178 on dockerized Debian:buster, zigbee2mqtt 1.30.3 and mosquitto.
I noticed the same kind of behavior with some buttons on a Aqara Opple wall transmitter (WXCJKG13LM), but dit not investigate that one.

Looking at the MQTT content I couldn't find any possible cause for conflict and no source for the chosen UnitID's, so the information below is probably not needed, but included to support my findings. 

Hopefully someone with more knowledge of the inner workings of Domoticz can take this diagnoses further of even solve the problem.

MQTT state when holding off button on 2nd row:
```
zigbee2mqtt/Push8bee
{
  "action": "brightness_move_down_2",
  "action_group": 10257,
  "action_rate": 50,
  "battery": 100,
  "last_seen": "2023-04-07T05:40:17.354Z",
  "linkquality": 61
}
```
MQTT state when holding on button on 4th row:
```
zigbee2mqtt/Push8bee
{
  "action": "brightness_move_up_4",
  "action_group": 10289,
  "action_rate": 50,
  "battery": 100,
  "last_seen": "2023-04-07T07:02:48.108Z",
  "linkquality": 102
}
```
A look at the auto discovery topics did not turn up anything suspicious either.
```
discover_zigbee/sensor/0x04cd15fffe8e0656/action/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x04cd15fffe8e0656"
    ],
    "manufacturer": "ROBB",
    "model": "Zigbee 8 button wall switch (ROB_200-007-0)",
    "name": "Push8bee",
    "sw_version": "2.7.6_r25"
  },
  "enabled_by_default": true,
  "icon": "mdi:gesture-double-tap",
  "json_attributes_topic": "zigbee2mqtt/Push8bee",
  "name": "Push8bee action",
  "state_topic": "zigbee2mqtt/Push8bee",
  "unique_id": "0x04cd15fffe8e0656_action_zigbee2mqtt",
  "value_template": "{{ value_json.action }}"
}


discover_zigbee/device_automation/0x04cd15fffe8e0656/action_brightness_move_up_4/config
{
  "automation_type": "trigger",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x04cd15fffe8e0656"
    ],
    "manufacturer": "ROBB",
    "model": "Zigbee 8 button wall switch (ROB_200-007-0)",
    "name": "Push8bee",
    "sw_version": "2.7.6_r25"
  },
  "payload": "brightness_move_up_4",
  "subtype": "brightness_move_up_4",
  "topic": "zigbee2mqtt/Push8bee/action",
  "type": "action"
}


discover_zigbee/device_automation/0x04cd15fffe8e0656/action_brightness_move_down_2/config
{
  "automation_type": "trigger",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x04cd15fffe8e0656"
    ],
    "manufacturer": "ROBB",
    "model": "Zigbee 8 button wall switch (ROB_200-007-0)",
    "name": "Push8bee",
    "sw_version": "2.7.6_r25"
  },
  "payload": "brightness_move_down_2",
  "subtype": "brightness_move_down_2",
  "topic": "zigbee2mqtt/Push8bee/action",
  "type": "action"
}
```

**Comment by d-EScape** [comment]
Ok... pretty sure I was on the right track. The conflicting actions do get the same crc. 

I frankencoded some pieces of the Domoticz MQTT-AD and helper source into a little program that only generated the crc values from the action strings. The numbers match perfectly with the UnitID's in Domoticz, so I'm pretty sure it is working.

"brightness_move_down_2" and "brightness_move_up_4" both both get a crc of 167. 
"brightness_move_down_4" and "brightness_move_up_2" both result in a crc of 1.

While this was a nice C++ exercise I dare not touch the actual Domoticz code. Can someone with more knowledge pick this up please? 

It look like another approach for UnitID calculation is needed, but it might not be that simple. Getting a maximum of 255 numbers out of varying action strings will most likely always leave a risk of not unique values. 

Another possibility might be to recognize there is a number behind the action string and create a separate device for each number. Or (not very elegantly) create a separate device for any action that is not recognized. 

```
brightness_move_down_1 CRC = 244
brightness_move_down_2 CRC = 167
brightness_move_down_3 CRC = 150
brightness_move_down_4 CRC = 1
brightness_move_up_1 CRC = 82
brightness_move_up_2 CRC = 1
brightness_move_up_3 CRC = 48
brightness_move_up_4 CRC = 167
brightness_stop_1 CRC = 25
brightness_stop_2 CRC = 74
brightness_stop_3 CRC = 123
brightness_stop_4 CRC = 236
off_1 CRC = 97
off_2 CRC = 50
off_3 CRC = 3
off_4 CRC = 148
on_1 CRC = 232
on_2 CRC = 187
on_3 CRC = 138
on_4 CRC = 29
```

**Comment by d-EScape** [comment]
I can now confirm that the Aqara Apple wall switch has the same problem. 

"button_1_release" and "button_6_triple" have the same CRC. As do "button_2_single" and "button_3_hold".
In this case there is no number suffix or prefix, so my previous suggestion would not work for this device. 
Creating separate Domoticz devices for every action seems to be the safest way.

This must be a problem for every (switch) device with a lot of actions. I cannot think of a way to reduce an almost infinite number of possible action strings  to 255 possible numbers. 

Adding every known action string as a predefined number might also work, but requires a lot of maintenance. Not quite what AD stands for.

**Comment by gizmocuz** [comment]
Please post a config and some state topics + payload as there is no CRC or it should work

**Comment by gizmocuz** [comment]
This could indeed be a problem for every sensor/scene device.
Maybe we should add the action name behind the device id... but I will see if I can change the CRC calculation
Scanning for a number would not work as it has up/down/brightness etc

**Comment by gizmocuz** [comment]
I made a better crc8 calculation:

```
uint8_t Crc8_strMQ(uint8_t crc, const uint8_t* buf, size_t size)
{
	crc = 0xff;
	if (buf == NULL)
		return crc;
	while (size--)
		crc += *buf++;
	return crc;
}
```

I made a test application that compares all strings you mentioned and all are unique

First value is original crc, second value new crc:

```
brightness_move_down_2 = 167, >= 246
brightness_move_up_4 = 167, >= 37
brightness_move_down_1 = 244, >= 245
brightness_move_down_3 = 150, >= 247
brightness_move_down_4 = 1, >= 248
brightness_move_up_1 = 82, >= 34
brightness_move_up_2 = 1, >= 35
brightness_move_up_3 = 48, >= 36
brightness_stop_1 = 25, >= 237
brightness_stop_2 = 74, >= 238
brightness_stop_3 = 123, >= 239
brightness_stop_4 = 236, >= 240
off_1 = 97, >= 202
off_2 = 50, >= 203
off_3 = 3, >= 204
off_4 = 148, >= 205
on_1 = 232, >= 108
on_2 = 187, >= 109
on_3 = 138, >= 110
on_4 = 29, >= 111
button_1_release = 102, >= 107
button_6_triple = 102, >= 31
button_2_single = 52, >= 13
button_3_hold = 52, >= 51
action_single = 224, >= 94
action_double = 174, >= 87
action_hold = 252, >= 131
```
[test_crc.zip](https://github.com/domoticz/domoticz/files/11300483/test_crc.zip)

attached the test program

**Comment by gizmocuz** [comment]
Downside is, everyone currently using scene devices will get new devices... but it's for the better

**Comment by gizmocuz** [comment]
Could you check beta 15198? Make you you have set 'accept new devices' in settings

**Comment by d-EScape** [comment]
Thanks for looking into this!

It will be a breaking change, but I agree it's for the better.

Since new devices/units are going to be created anyway it might be safer to just create separate devices for each action. Even the most brilliant way to calculate a 8-bit unitid from action strings will still be limited to 255 possible outcomes. Chances are there will be some other strings that result in the same number.

**Comment by gizmocuz** [comment]
Chances are very low, and no node has 255 possibilities

**Comment by gizmocuz** [comment]
And you do get separate devices for each action

**Comment by d-EScape** [comment]
I will gladly test the beta. 

Maybe I misunderstand how this works(?)

As I understand the crc is calculated from the action string and that crc is used as the unit. The unit can be between 1 and 255.

A Domoticz device has an ID and a Unit and that combination has to be unique. The ID is the same for al buttons on the scene-controller, in my case "0x04cd15fffe8e0656_action_zigbee2mqtt" (which I interpreted as a "Device"). So every action needs a unique unit within that "Device".

My remark about 255 possibilities was not about the number of actions one physical device can have, but about the virtually infinite number of possible strings that could exists in all current, future and diy physical devices together. (Without doing the math) it seems very likely that there are a lot of possible actionstrings that would result in the same 8-bit crc. Even if the ones where now testing are unique.

I'm just trying to understand how this works and possibly trying to prevent two braking changes in a row. Really appreciate your help on this issue.

**Comment by gizmocuz** [comment]
I don't think there will be an issue now

**Comment by d-EScape** [comment]
Oke.. Running beta 15198 now and all buttons are (re)created with unique unit numbers. Thanks!
