### ISSUE TITLE
Domoticz and Homebridge (same as #5476)

### ISSUE THREAD

**Issue by lsp242** [domoticz/domoticz#5667]
Its back again..

Unauthorized: 401 Unauthorized
 There was a problem connecting to Domoticz. (HTTP Status code 401)

now 2 messages

[homebridge-edomoticz] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[Domoticz] There was a problem connecting to Domoticz. (HTTP Status code 401)

in config I added

`"server":` "username:password@"internal ip domoticz"
and than "username" and `"password"`

that worked until last week

**Comment by waltervl** [comment]
This forum topic you started will do for now https://www.domoticz.com/forum/viewtopic.php?t=39338
So closing this issue as long as it is not a reproducable bug.
