### ISSUE TITLE
Add support for Device Triggers / Hue Dimmer Switch via MQTT AD

### ISSUE THREAD

**Issue by bendamat** [domoticz/domoticz#5668]
Currently there is no support for device triggers via MQTT Autodiscovery, which includes the popular Hue Dimmer Switch. Would be great to be able to include it!

**Comment by waltervl** [comment]
There is need to post this here in a github issue if there is no information on the config and state info (mqtt messages) of that dimmer switch. Also as they are Zigbee devices it could be that they even are not sending that information to the Zigbee Coordinator but only within the Zigbee group.

Do you see MQTT messages if you press the desired dimmer buttons? If not it is a Zigbee2MQTT issue and not a Domoticz issue. 

Will close this issue if there are no MQTT  config (to discover) and state (to change state) messages posted in this issue.

**Comment by bendamat** [comment]
The device is correctly recognised by Zigbee2MQTT and messages show up. The limitation is on Domoticz side, which currently does not support devices of type `device_automation`. 

Here is an example of a config message for one of the buttons : `zigbee2mqtt-ad/device_automation/0x0017880104f544b0/action_on_press/config`

```json
{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x0017880104f544b0"],"manufacturer":"Philips","model":"Hue dimmer switch (324131092621)","name":"Dimmer Switch","sw_version":"6.1.1.28573"},"payload":"on_press","subtype":"on_press","topic":"zigbee2mqtt/Dimmer Switch/action","type":"action"}
```

And an example of a state message related to that button: 

```json
{"action":"on_press_release","action_duration":null,"battery":100,"linkquality":244,"update":{"installed_version":1107324829,"latest_version":1107324829,"state":"idle"},"update_available":null}
```

**Comment by waltervl** [comment]
I do not know if this is enough information to be able to support this function in Domoticz. They will need all possible options...

**Comment by gizmocuz** [comment]
Could you post some more actions? Like the actual 'press' or double press if that's possible with this node

**Comment by gizmocuz** [comment]
@bendamat , still an issue or did you solve it in another way?

**Comment by bendamat** [comment]
Sorry for the delay, didn't get round to updating you with more details.
But this sill is a limitation. Hope I'm able give an update on a couple of
days.

**Comment by gizmocuz** [comment]
I find this a strange 'config' object, do you use the latest zigbee2mqtt, and is this message generated by zigbee2mqtt?
There is no state_topic, but a 'topic', there is no value_template, how should be know it has to use the 'action' value?

I found some zwave device_automation configs and they all have a value_template, this is needed!

{"value_template":"{{ value_json.value }}","subtype":"button_1","payload":"1-button_short_press","device":{"model":"","configuration_url":"http:\/\/10.102.27.105\/app\/settings\/devices\/list#device-142","hw_version":"Z-Wave type 3; Z-Wave version 4.24","sw_version":"Fibargroup 3.4","suggested_area":"33","name":"142","manufacturer":"Fibargroup","identifiers":"hc3-142"},"topic":"homeassistant\/sensor\/144\/events\/DevicePropertyUpdatedEvent\/1-pressed","type":"button_short_press","automation_type":"trigger"}

Is this the only config you get from this device, or do you also get a 'switch' or 'button' type next to the device_automation?

**Comment by bendamat** [comment]
I'm using zigbee2mqtt 1.30.3 (latest) and yes, the message is generated by zigbee2mqtt.
Don't have any zwave device_automation configs to compare to, but I'm trying to give you some more details about the topics and config messages for this device. 

So I find my device in both `sensor` and `device_automation`. Sensor seem to be the only ones recognised by Domoticz (I get one device for `action_duration` with its battery status that you'll find in the following config messages. 

* **zigbee2mqtt-ad/sensor/0x0017880104f544b0/battery/config**
      ```
      {"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x0017880104f544b0"],"manufacturer":"Philips","model":"Hue dimmer switch (324131092621)","name":"Dimmer Switch","sw_version":"6.1.1.28573"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","name":"Dimmer Switch battery","state_class":"measurement","state_topic":"zigbee2mqtt/Dimmer Switch","unique_id":"0x0017880104f544b0_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}
      ```
* **zigbee2mqtt-ad/sensor/0x0017880104f544b0/action_duration/config**
      ```
      {"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x0017880104f544b0"],"manufacturer":"Philips","model":"Hue dimmer switch (324131092621)","name":"Dimmer Switch","sw_version":"6.1.1.28573"},"enabled_by_default":true,"name":"Dimmer Switch action duration","state_topic":"zigbee2mqtt/Dimmer Switch","unique_id":"0x0017880104f544b0_action_duration_zigbee2mqtt","unit_of_measurement":"second","value_template":"{{ value_json.action_duration }}"}
      ```

* **zigbee2mqtt-ad/sensor/0x0017880104f544b0/linkquality/config**
      ```
      {"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x0017880104f544b0"],"manufacturer":"Philips","model":"Hue dimmer switch (324131092621)","name":"Dimmer Switch","sw_version":"6.1.1.28573"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Dimmer Switch linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Dimmer Switch","unique_id":"0x0017880104f544b0_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}
      ```
* **zigbee2mqtt-ad/sensor/0x0017880104f544b0/update_state/config**
      ```
      {"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x0017880104f544b0"],"manufacturer":"Philips","model":"Hue dimmer switch (324131092621)","name":"Dimmer Switch","sw_version":"6.1.1.28573"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:update","name":"Dimmer Switch update state","state_topic":"zigbee2mqtt/Dimmer Switch","unique_id":"0x0017880104f544b0_update_state_zigbee2mqtt","value_template":"{{ value_json['update']['state'] }}"}
      ```

Now for the `device_automation`, I have the following topics: 

* **zigbee2mqtt-ad/device_automation/0x0017880104f544b0/action_on_press/config**
      ```
      {"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x0017880104f544b0"],"manufacturer":"Philips","model":"Hue dimmer switch (324131092621)","name":"Dimmer Switch","sw_version":"6.1.1.28573"},"payload":"on_press","subtype":"on_press","topic":"zigbee2mqtt/Dimmer Switch/action","type":"action"}
      ```

* **zigbee2mqtt-ad/device_automation/0x0017880104f544b0/action_on_press_release/config**
      ```
      {"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x0017880104f544b0"],"manufacturer":"Philips","model":"Hue dimmer switch (324131092621)","name":"Dimmer Switch","sw_version":"6.1.1.28573"},"payload":"on_press_release","subtype":"on_press_release","topic":"zigbee2mqtt/Dimmer Switch/action","type":"action"}
      ```

* **zigbee2mqtt-ad/device_automation/0x0017880104f544b0/action_off_press/config**
      ```
      {"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x0017880104f544b0"],"manufacturer":"Philips","model":"Hue dimmer switch (324131092621)","name":"Dimmer Switch","sw_version":"6.1.1.28573"},"payload":"off_press","subtype":"off_press","topic":"zigbee2mqtt/Dimmer Switch/action","type":"action"}
      ```

* **zigbee2mqtt-ad/device_automation/0x0017880104f544b0/action_off_press_release/config**
      ```
      {"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x0017880104f544b0"],"manufacturer":"Philips","model":"Hue dimmer switch (324131092621)","name":"Dimmer Switch","sw_version":"6.1.1.28573"},"payload":"off_press_release","subtype":"off_press_release","topic":"zigbee2mqtt/Dimmer Switch/action","type":"action"}
      ```

* **zigbee2mqtt-ad/device_automation/0x0017880104f544b0/action_on_hold/config**
      ```
      {"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x0017880104f544b0"],"manufacturer":"Philips","model":"Hue dimmer switch (324131092621)","name":"Dimmer Switch","sw_version":"6.1.1.28573"},"payload":"on_hold","subtype":"on_hold","topic":"zigbee2mqtt/Dimmer Switch/action","type":"action"}
      ```

* **zigbee2mqtt-ad/device_automation/0x0017880104f544b0/action_on_hold_release/config**
      ```
      {"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x0017880104f544b0"],"manufacturer":"Philips","model":"Hue dimmer switch (324131092621)","name":"Dimmer Switch","sw_version":"6.1.1.28573"},"payload":"on_hold_release","subtype":"on_hold_release","topic":"zigbee2mqtt/Dimmer Switch/action","type":"action"}
      ```

I'm not including the details for the following because they are all similar to the ones above: 
* **action_up_press**
* **action_up_press_release**
* **action_up_hold**
* **action_up_hold_release**
* **action_down_press**
* **action_down_hold**
* **action_down_hold_release**
* **action_down_press_release**

**Comment by gizmocuz** [comment]
Don't you have a **<autodiscovery_topic>/sensor/deviceid/action/config** topic ?

All my switches have them, also working on another user issue where also he/she has this

In MQTT Explorer you can use the search box and search for **action/config**

**Comment by gizmocuz** [comment]
According to this page it should support 'action'

https://www.zigbee2mqtt.io/devices/324131092621.html

Also please update to the latest Domoticz beta, and make sure 'accept new devices' is enabled. There have been a recent change today

**Comment by gizmocuz** [comment]
Okey, I bought this dimmer from the received donation money.
I can confirm the device is working correctly.

![image](https://user-images.githubusercontent.com/2265299/233784161-250e6d49-76cb-47ad-8140-336007fdd016.png)

There is absolutely no need to support the device_automation object type at this moment.

**Comment by bendamat** [comment]
OK, thanks for testing this for me. I recon there is an issue on the zigbee2mqtt side then. I'll see what I can find out there.

**Comment by gizmocuz** [comment]
Just update to the new beta
