### ISSUE TITLE
Visual Crossing small issues

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#5670]
@Olifant1990 
Thanks for the PR to implement Visual Crossing as alternative for Darksky. As it is implemented now in latest beta we saw some small isues. See also Forum topic https://www.domoticz.com/forum/viewtopic.php?p=302113

- Wind device and Visibility device got the name Unknown"
- The mixture of barometer device with temp/humi device (and the naming THB)
- Forecast is still going to old Darksky (forecast.io) and so still giving an error

Is it also possible to use the location of setup - settings as default? eg by leaving the location field empty or fill in a 0 (zero)

**Comment by Olifant1990** [comment]
See https://github.com/domoticz/domoticz/pull/5669
I fixed the default names of wind and visibility devices

What is wrong with "mixture of barometer with tem/humi device"?
This is intended. You get 1 device, splitted in two views. One temperature and one barometer view.
THB stands for Temp+Hum+Barometer. You can change this yourseld.

The forecast button on weather tap is not depending on weather lookup hardware as far as I know. In the Visual Crossing hardware code is no reference to forecast.io

**Comment by Olifant1990** [comment]
Will have a look if I can fetch system location somewhere later this week maybe

**Comment by waltervl** [comment]
Thanks for looking in to this. For a new user THB is perhaps a little bit short name. TempHumBaro is then better (and also used in for example Buienradar).

**Comment by kiddigital** [comment]
> @Olifant1990 Thanks for the PR ....
> 
>     * Forecast is still going to old Darksky (forecast.io) and so still giving an error

This is hardcoded in the UI at the moment (`www/app/ForecastController.js`) as a fallback. If weather hardware modules support it (like OpenWeatherMap and Buienradar at the moment), the UI requests `getforecastconfig` to get alternative forecast configuration info. If none is given, it falls back to 'forecast.io'.

If Visual Crossing offers a good forecast alternative, this could be implemented by supporting it in the hardware module, the `Cmd_GetForecastConfig` command and the UI.
 
> 
> Is it also possible to use the location of setup - settings as default? eg by leaving the location field empty or fill in a 0 (zero)

Good suggestion. Some other modules do that as well.

@waltervl , should we consider creating a 'Weather' Wiki page (we already have a 'Category' for it) to list all Weather options?

**Comment by waltervl** [comment]
@kiddigital indeed a weather wiki will be a good thing. I will set that up soon.
Just another issue is that Buienradar does not set the forecast link. But unrelated to Visual Crossing ofcourse.

**Comment by gizmocuz** [comment]
I was just working on this yesterday and have a commit ready (but will wait with this)

I changed the hardcoding to

```
					//var fallbackurl = "//forecast.io/embed/#lat=" + data.Latitude + "&lon=" + data.Longitude + "&units=ca&color=#00aaff";
					var fallbackurl = "//www.visualcrossing.com/weather-history/" + data.Latitude + "," + data.Longitude + "/metric/next7days";
					//var fallbackhtml = '<iframe style="background: #fff; height:245px;" class="cIFrame" id="IMain" src="' + fallbackurl + '"></iframe>';
					var fallbackhtml = '<iframe style="background: #fff; height:85%;" class="cIFrame" id="IMain" src="' + fallbackurl + '"></iframe>';

```

But I was still playing with the height of the IFrame.

Indeed best to implement **getforecastconfig**

**Comment by Olifant1990** [comment]
@gizmocuz 

The VisualCrossing.cpp has already a function named GetForecastURL.
See https://github.com/domoticz/domoticz/blob/development/hardware/VisualCrossing.cpp r116.

I copied most parts from DarkSky, but is this method wrong?

Can we reopen this issue for a short time again?
Still work to do :)

**Comment by gizmocuz** [comment]
@Olifant1990 , I have not yet tested it... I was checking yesterday the forcast button from the weather tab and noticed "forecast.io" was not working 
I will test latest today with the new VisualCrossing as well

**Comment by kiddigital** [comment]
> @gizmocuz
> 
> The VisualCrossing.cpp has already a function named GetForecastURL. See https://github.com/domoticz/domoticz/blob/development/hardware/VisualCrossing.cpp r116.
> 
> I copied most parts from DarkSky, but is this method wrong?
> 
> Can we reopen this issue for a short time again? Still work to do :)

Re-opened. The method in VisualCrossing is ok. It is just not supported (yet) in `Cmd_GetForecastConfig` (main/WebServer.cpp r2778).

**Comment by waltervl** [comment]
> @kiddigital indeed a weather wiki will be a good thing. I will set that up soon. Just another issue is that Buienradar does not set the forecast link. But unrelated to Visual Crossing ofcourse.
wiki pages created:
https://www.domoticz.com/wiki/Visual_Crossing_weather_lookup
https://www.domoticz.com/wiki/Weather  (work in progress)

**Comment by waltervl** [comment]
So in latest beta of today the forecast is also solved. If someone wants to make a separate barometer and TempHum device.  There is a script on the wiki that implements this. Link is in the Visual Crossing wiki. Thanks all for your help!

**Comment by gizmocuz** [comment]
@waltervl , why would you want to create a separate temp and humidity device? This is always combined when possible

**Comment by waltervl** [comment]
> @waltervl , why would you want to create a separate temp and humidity device? This is always combined when possible

Because Domoticz then shows from the combined device a Barometer device in the weather section that is called the name you gave for the combined device (eg TempHumBaro Outside). This shows a strange. See also the forum topic mentioned in my first message.

**Comment by gizmocuz** [comment]
That is correct and has always been like this.
When you have a temp+hum+baro device, in the temperature tab you see temp+hum+baro (and when you click the log you see the details from temp+hum)
And on the weather tab you see the baro details, and also with the log

This is a wanted situation, has been since the beginning of Domoticz, so I do not see the problem suddenly.
