### ISSUE TITLE
Multiple instances of same Python plugin stop access to serial devices / overload TCP devices.

### ISSUE THREAD

**Issue by simat-git** [domoticz/domoticz#5671]
Hi,

Since upgrading from 2021.1 to 2022 and now 2023.1 it looks like Python plugsin are now run in parallel, when multiple instances of the same plugin try to talk to the same serial device (/dev/ttyUSB0) etc the follow error occurs.

2023-03-30 19:48:40.073 Error: SDM120M-ID7: File "/home/pi/domoticz/plugins/SDM120Modbus/plugin.py", line 134, in onHeartbeat
2023-03-30 19:48:40.073 Error: SDM120M-ID7: _plugin.onHeartbeat()
2023-03-30 19:48:40.073 Error: SDM120M-ID7: File "/home/pi/domoticz/plugins/SDM120Modbus/plugin.py", line 85, in onHeartbeat
2023-03-30 19:48:40.073 Error: SDM120M-ID7: Total_System_Power = self.rs485.read_float(12, functioncode=4, numberOfRegisters=2)
2023-03-30 19:48:40.073 Error: SDM120M-ID7: File "/home/pi/domoticz/plugins/SDM120Modbus/minimalmodbus.py", line 392, in read_float
2023-03-30 19:48:40.073 Error: SDM120M-ID7: return self._genericCommand(functioncode, registeraddress, numberOfRegisters=numberOfRegisters, payloadformat='float')
2023-03-30 19:48:40.073 Error: SDM120M-ID7: File "/home/pi/domoticz/plugins/SDM120Modbus/minimalmodbus.py", line 697, in _genericCommand
2023-03-30 19:48:40.073 Error: SDM120M-ID7: payloadFromSlave = self._performCommand(functioncode, payloadToSlave)
2023-03-30 19:48:40.073 Error: SDM120M-ID7: File "/home/pi/domoticz/plugins/SDM120Modbus/minimalmodbus.py", line 795, in _performCommand
2023-03-30 19:48:40.073 Error: SDM120M-ID7: response = self._communicate(request, number_of_bytes_to_read)
2023-03-30 19:48:40.073 Error: SDM120M-ID7: File "/home/pi/domoticz/plugins/SDM120Modbus/minimalmodbus.py", line 857, in _communicate
2023-03-30 19:48:40.073 Error: SDM120M-ID7: self.serial.open()
2023-03-30 19:48:40.073 Error: SDM120M-ID7: File "/home/pi/domoticz/plugins/SDM120Modbus/serial/serialposix.py", line 261, in open
2023-03-30 19:48:40.073 Error: SDM120M-ID7: raise SerialException("Port is already open.")
2023-03-30 19:48:40.073 Error: SDM120M-ID7: serial.serialutil.SerialException: Port is already open.

This issue was raised on the forum under [https://www.domoticz.com/forum/viewtopic.php?p=294049#p294049](url) in November 2022
and recently under [https://www.domoticz.com/forum/viewtopic.php?p=301766#p301766](url) after I'd done extensive testing to try and narrow down the problem.

The workaround at the moment is to disable all of the instances of the plugin within Hardware and then re-enable them one at a time, with them being started several seconds apart.  May be an option can be added to load plugins a few seconds apart upon initialisation.

I have tested on Raspbian Lite Buster and Bullseye 32/64 bit versions, several Python versions but find Domoticz 2023.1 to be the issue.  Plugin works fine on 2021.1 32bit Bullseye with Python 3.9.2

The plugin is available at [https://github.com/remcovanvugt/SDM120Modbus-Domoticz-plugin](url)

Best regards

Simon.

**Comment by pipiche38** [comment]
I would be interesting to understand to have several readers on the same serial line 
What is the main purpose of the multiple instance ?

**Comment by simat-git** [comment]
Its to read multibus MODBUS meters - mainly Eastron SDM120M using a single USB to RS485 adapter on /dev/ttyUSB0.  Each modbus slave device has an ID on the bus and is read by the master (domoticz plugin)

Another complaint I've come across is multiple connections with a similar plugin to a MODBUS over TCP programmable logic controller, the multiple requests for info from the PLC all at the same time caused an overload situation, staggering the plugin instances startup within hardware resolved until the next reboot.

**Comment by simat-git** [comment]
![image](https://user-images.githubusercontent.com/96069401/232779274-c089aff7-a015-486e-b7ac-823beafe8ccf.png)

**Comment by Domoberry** [comment]
Some more details: 
The same problem has been seen with 2 modbus libraries: https://github.com/pymodbus-dev/pymodbus and https://github.com/pyhys/minimalmodbus. The respective Domoticz plugins https://github.com/DomoticX/domoticz-modbus and https://github.com/MFxMF/SDM630-Modbus use them and both show the same problem when multiple instances of the same Domoticz plugin are used. 
The DomoticX plugin is more flexible, but reads only one Modbus register per OnHeartbeat to the plugin, hence the need to run multiple plugins if data from more registers is needed. This worked ok in Domoticz 2022.1. 
The SDM630 plugin reads multiple Modbus registers in one OnHeartbeat. If these users want to read multiple Modbus devices, they would use additional instances of the same plugin, yielding the same problem since Domoticz 2022.1. Buster or Bullseye does not change this,

**Comment by gizmocuz** [comment]
Well yes you can not re-use a serial port. Once it is open (in use) by a hardware plugin, it can not be used by another

One thing you could (maybe) do is use ser2net

**Comment by Domoberry** [comment]
That is most likely the root of the problem. However, it worked OK in an earlier Domoticz release.
Edit: I mean that since Domoticz 2022.1  the various Modbus plugins are started so close after each other that it is likely that the next one attempts to open the serial port before the previous one has released it.

**Comment by simat-git** [comment]
The plugin closes the port after the code is executed until the next call

minimalmodbus.CLOSE_PORT_AFTER_EACH_CALL=True

Has the plugin run order / process been changed since 2021.1 ?

**Comment by simat-git** [comment]
> Well yes you can not re-use a serial port. Once it is open (in use) by a hardware plugin, it can not be used by another
> 
> One thing you could (maybe) do is use ser2net

Remember, 2023.1 does in fact work, but you have to disable all of the instances of the plugin within Hardware and then re-enable them one at a time, with them being started several seconds apart.

So that proves that the plugin doesn't keep the port open.   

We just need an option to start the plugins 2 seconds apart.

If you don't want to include this in the main distro, please can you just let me know what loads the plugins and i'll add my own delay in there so for own build.  Is it plugins.cpp ?

Thanks

**Comment by simat-git** [comment]
After i wee bit a fiddling around, i've found a bodge maybe.  On my own build of 2023.1 i've added a 1 second delay in CPlugin::StartHardware()  within Plugins.cpp

`
bool CPlugin::StartHardware()
	{
		if (m_bIsStarted)
			StopHardware();

		RequestStart();

		// Flush the message queue (should already be empty)
		{
			std::lock_guard<std::mutex> l(m_QueueMutex);
			while (!m_MessageQueue.empty())
			{
				m_MessageQueue.pop_front();
			}
		}

		// Start worker thread
		try
		{
			std::lock_guard<std::mutex> l(m_QueueMutex);

			sleep_milliseconds(1000);	//  ** LOAD PLUGINS 1sec APART **

			m_thread = std::make_shared<std::thread>(&CPlugin::Do_Work, this);
			if (!m_thread)
			{
				Log(LOG_ERROR, "Failed start interface worker thread.");
			}
			else
			{
				SetThreadName(m_thread->native_handle(), m_Name.c_str());
				Log(LOG_NORM, "Worker thread started.");
			}
		}
`

**Comment by dnpwwo** [comment]
Wouldn't probably be better to change the plugins to handle the error and retry in onHeartbeat?

**Comment by simat-git** [comment]
I agree, that would be the better option.  The MODBUS plugins aren't maintained anymore and I can't find any examples of how to use onHeartbeat.

I was considering using a lock file and just waiting in the plugin until the lock file was gone before opening the RS485 port, but I don't know the blocking side effects of this.

**Comment by pipiche38** [comment]
I think that the issue, blocking in the main thread is not good.

**Comment by simat-git** [comment]
After some thought, i think starting the plugins a second or two apart is the better solution.  

A plugin that uses the serial device could be altered to retry if the port was busy, but a plugin that issues TCP calls to a PLC would have no way of performing flow / connection control.

What changed between versions 2021.1 and 2022.1 / 2023.1 in respect of plugin timing ?

**Comment by waltervl** [comment]
The issue that multiple python plugin instances try to open the same serial port is being discussed on the forum: https://www.domoticz.com/forum/viewtopic.php?t=40275

**Comment by simat-git** [comment]
Updated and tested plugin now available on

https://github.com/simat-git/SDM120-Modbus

Works with Domoticz 2023.1, now just takes a few minutes to initially allocate each instance to its own timeslot, will also recover from bus disconnection and re-time itself. The previous plugin would error until manual intervention / reset.
