### ISSUE TITLE
Install script selects incompatible arch on Raspbian aarch64 with 32-bit userland

### ISSUE THREAD

**Issue by pharring** [domoticz/domoticz#5679]
Reported by several users at https://www.domoticz.com/forum/viewtopic.php?t=40198

The installer script uses `uname -m` to determine the OS architecture:
```
MACH=`uname -m`
```

However, this returns the architecture of the kernel and it's possible to have a different architecture for userland binaries. Because of this, the installer script downloads the wrong binaries. For me, this resulted in a broken state when upgrading to the 2023 builds.

You can detect the userland architecture with `dpkg --print-architecture`.

For example, on my RPi 4:
```
pi@raspberrypi:~ $ uname -m
aarch64
pi@raspberrypi:~ $ dpkg --print-architecture
armhf
```

The fix would need to be in the installer script.
I'm not enough of a Linux expert to know how to map all the possible outputs of `dpkg --print-architecture` to the relevant binaries.
For example, it's clear for my case that "armhf" should map to the "armv7l" download. But what other architectures are possible?

Perhaps there's a better way to figure out the pointer width (32bit versus 64bit) of user-land binaries from a shell script.

**Comment by gizmocuz** [comment]
You could use the docker version

**Comment by gizmocuz** [comment]
Have you configured your system for both 32 and 64 bits? 0.001% of the users do this, so that's why I would recommend to use the docker.

If you want to know all architectures and make a mapping of what is supported (arm 32 bit, arm 64 bit and x86_64, you can issue

dpkg-architecture --list-known

**Comment by pharring** [comment]
> Have you configured your system for both 32 and 64 bits?

I did not intentionally do that, no. I didn't ever realize it (mixed bitness) was possible until I updated domoticz and ended up in this situation.

Having researched a little, I think I have an idea of what happened:

- I setup up my RPi with domoticz several years ago. At that time, Raspbian was 32-bit only, so that's what was installed. Docker wasn't an option.
- The 64-bit version of Raspbian was released in February 2022: https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/
- In January 2023, I was playing with some new audio software on my Pi. I was struggling to get it working, so I tried updating everything (apt-get update, etc.). I also ran the "raspi-config" and I think there was an option to update the OS and that, I think, is where I got upgraded to a 64-bit kernel -- without me realizing it. Apps continued to work because they were still 32-bit.
- A few months later, I needed to make some changes to my home automation, so I went into domoticz. I decided to update to the latest version and ended up in a broken state.

> 0.001% of the users do this

4 or 5 users on that forum thread hit this independently. It's worth remembering that none of them _intentionally_ did it. It's just how their systems ended up after an upgrade.

> dpkg-architecture --list-known

That's quite a list! I propose we stick to just the known case I've described (detect `armhf` and select the 32-bit downloader)
An alternative I researched is to use `getconf LONGBIT` to detect bitness. On my system it's 32. I presume it's 64 on aarch64 systems.

**Comment by Ewoud86** [comment]
@pharring I had the same issue recently. It looks like they switched to the 64-bit kernel intentionally for the Pi 4 with an update in March. Even when the installed version is 32-bit.
See also: https://github.com/raspberrypi/firmware/issues/1795
And for more info: https://forums.raspberrypi.com/viewtopic.php?p=2088935#p2088935

> 0.001% of the users do this

So I think more users will have this issue after updating the OS, and than try to update Domoticz to the latest beta/stable version.

For now I fixed it by adding `arm_64bit=0` to confix.txt in the /boot/ directory.

**Comment by gizmocuz** [comment]
This means if you would install domoticz again you would get the 64bits version?

**Comment by Ewoud86** [comment]
Yes, indeed. I did a `./updatebeta` at that time, and that downloaded the 64-bit version. After that it doesn't work anymore. Than I downloaded the 32-bit version by hand, and replaced the domoticz file in the domoticz folder, that did the trick. 
Because `uname -m` will detect aarch64 instead of armv7l.

**Comment by gizmocuz** [comment]
Strange as it's not 64bit....
Anyway, I think the latest raspbian is 64 bit, better install this and you should get the 64 bit domoticz

**Comment by Ewoud86** [comment]
Actually it (partly) is, because it uses the 64-bit kernel (it loads kernel8.img). And apparently `uname -m` checks the kernel (I am not an expert, so not sure). 
It will take a lot of time to change to 64-bit, it has a lot of other applications installed on the Raspberry Pi.
For now adding `arm_64bit=0` fixed it, because this will load the 32-bit kernel. Than the `uname -m` check in the install script will work without an issue. 
But I think change the check to `dpkg --print-architecture` will help other people also, who will otherwise run into the same issue.

**Comment by gizmocuz** [comment]
Sooner or later you will probably update your system with a new fresh install.
Running lots of applications might also have some impact on domoticz.
If you run all your applications via docker-compose, migrating to a new raspbian should not be to much work

**Comment by pharring** [comment]
@gizmocuz, would you accept a PR to address this?

**Comment by gizmocuz** [comment]
Sure ;)

**Comment by pharring** [comment]
OK. Assign this issue to me. I'll work on it this weekend.
