### ISSUE TITLE
False Low Battery Notification

### ISSUE THREAD

**Issue by nwcatalyst** [domoticz/domoticz#568]
Hi,

I have an Aeotec HEM G1 and Domoticz Version: 3.4964 Build Hash: 976cb17 sends me emails every few hours telling me the batteries are low (they are not even in it, it is hard wired).

**Comment by gizmocuz** [comment]
Could you go to the OZW control panel, and tell what is reported for battery level there ?

**Comment by nwcatalyst** [comment]
Zero (0)

**Comment by gizmocuz** [comment]
That looks pretty low....
It could be related to setup parameter 101
One option is to not accept values of '0' in Domoticz....

**Comment by nwcatalyst** [comment]
Hmm, ok, perhaps not the right place for this, but I found a description here: https://www.domoticz.com/forum/viewtopic.php?t=10659

Can you point me in the right direction to not accept 0 values?

**Comment by gizmocuz** [comment]
Try the new commit/beta 4978

**Comment by nwcatalyst** [comment]
Hmm I just compiled on my NAS box two days ago... when was that commit? It takes like 3+ days to build on my device so I'd really like to avoid having my entire system down for that long. If theres a workaround I'd be happy to just do that for now.

**Comment by gizmocuz** [comment]
It is committed an hour ago
3 days ? That is a lot... Maybe try a raspberry pi 2 or 3 ?

**Comment by nwcatalyst** [comment]
Ok thanks. 

Yeah I have a GoFlex Home, super underpowered by today's standards but it runs domo, btsync and a few other services very well, plus has all my storage on the 2TB partition. I am not looking to piece together a new system right now. Thanks for the help.

**Comment by gizmocuz** [comment]
$35+ investment for a raspberry... that seems like 1000% faster then your current setup ?
Cant believe you need 3 days to compile... compiling domoticz on my commodore 64 would be faster

**Comment by nwcatalyst** [comment]
Form factor also plays a role - I don't want an open board sitting around with more wires to connect the HDD. Yes, I could buy a case, etc, but then we're talking $50+ and there is nothing wrong with this little setup right now. I updated firmware on the HEM and seemed to fix the issue just FYI - thanks again for help.

**Comment by gizmocuz** [comment]
Okey so I can revert my patch?

**Comment by nwcatalyst** [comment]
I think so yes.
