### ISSUE TITLE
Add support for Python 3.11

### ISSUE THREAD

**Issue by barts2108** [domoticz/domoticz#5680]
Python 3.11 is out and is installed by default on Ubuntu 23.04.

Can this be added to Domoticz with a little urge ?

**Comment by gizmocuz** [comment]
You can try beta 15217 to see if that's working out for you.
But next time please make a PR and test yourself....

Or just use the docker-compose version of Domoticz so you won't have this issue

**Comment by barts2108** [comment]
For what I can test on windows this works

**Comment by gizmocuz** [comment]
Great! Thanks for testing!
