### ISSUE TITLE
Selector Switch disappears if editted in Switches Tab

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#5681]
If you create a virtual (On/Off) Switch it will be shown in the  "Switches" tab.
If you later try to edit that On/Off switch and you change it to a "Selector", the device disappears from the "Switches" tab.

You might wonder, why you do that, as there is a "Selector Switch" in the hardware available, but as long as it is there, it should work i.m.o.

See discussion on Forum: https://www.domoticz.com/forum/viewtopic.php?f=6&t=40150&sid=71ae1f0bf3f843638c19c95dd0405e4f

Regards

**Comment by gizmocuz** [comment]
I agree, so we should change it's type/subtype? Could you make a PR for this?

**Comment by FireWizard52** [comment]
@gizmocuz 

Sorry, I wished, that I could do that. 
Unfortunately I'm not familiar with C++ and the Domoticz internals.

So maybe someone else?

Regards

**Comment by gizmocuz** [comment]
I don't think it is related to a subtype change, but I did find an issue with the livesearch.
Made some changes in beta 15223, could you check if this solved the issue?

**Comment by FireWizard52** [comment]
Hello @gizmocuz 

I tested the latest version 15223 and it looks okay

![Screenshot_Selector Switch test](https://user-images.githubusercontent.com/46283323/235347094-f1a74bdb-f1e0-40ad-a521-4b2ca3beaaac.png)

At the left side you see a Switch that has been added  as an On/Off switch and edited later to replace it for a Selector Switch.

After changing it to a Selector Switch, it does not disappear anymore, but it comes up with the status "undefined" and the button "Off" is not highlighted. As soon as you click on "Off" the button is highlighted  and the status changed to "Off". For comparison, you see at the right side a Selector Swich, that has been added as a virtual device.

It is a small detail, but I suggest you do the same in case the "On/Off" switch has been edited and changed to a "Selector Switch".

Your opinion?

Regards

**Comment by gizmocuz** [comment]
Yes, that is because the selector switch status is unknown at the moment of changing
It is not good practice to swap between a normal switch and a selector switch, better create a new one.

Thanks for testing, I consider the bug fixed and will close the issue.

**Comment by FireWizard52** [comment]
@gizmocuz 

Agree, and I never used it, but saw that it was an issue in the forum.
Closed it, as fixed
