### ISSUE TITLE
Dashboard - You do not have permission to do that!

### ISSUE THREAD

**Issue by sincze** [domoticz/domoticz#5684]
FEATURE REQUEST / BUG?

Running: Domoticz 2023.1 (build 15182) on UBUNTU.

As response to:
https://www.domoticz.com/forum/viewtopic.php?p=302685#p302685

I have some people that I want to give access to my Domoticz enviromnent.
I've created a separate user for them under Setup -> Users (tried with role viewer and user) and I assigned the devices they need to have access to.

This works quite nicely.
They have a limited Domoticz screen without any configuration stuff so all that is good.

But now they want to mark 3 or 4 devices out of the 10 with the 'star' icon to have them appear on their DASHBOARD (they do not need to control these devices).

However if they click the 'star' icon they receive the message: "You do not have permission to do that."

Is this a bug or just never implemented?

![image](https://user-images.githubusercontent.com/5776333/235851283-25aebe37-2d50-41e1-9830-1a2ab8712c33.png)

**Comment by gizmocuz** [comment]
There are no 'user' favorites. So only admins can add/remove them as favorite

**Comment by sincze** [comment]
I get your point, this is however what I see:
![image](https://user-images.githubusercontent.com/5776333/236140605-ddde2a99-507b-41ec-86f3-b68cfa64f70a.png)

**Comment by sincze** [comment]
It seems I might have a clue.
2 VIEWERs.

a. 1 viewer has assigned the devices to him that he needs to see.
b. the other viewer has no devices assigned specificly to him

a. Viewer 1 has an empty dashboard. Not even showing the devices that are marked by the admin
b. Viewer 2 sees the dashboard as created by the admin.

I would expect a Viewer 1 to see at least the devices he has been added to instead of nothing. Does this make sense ?

![image](https://user-images.githubusercontent.com/5776333/236143947-90859bab-af2e-4842-abe7-671b9e946770.png)

**Comment by gizmocuz** [comment]
@sincze , you're totally right here. When users have 'shared' devices, they can be set as favorite.
Users with rights 'User or Admin' should also be able to do so.
I modified the code, and it should now work in beta 15227

Next to this, I think if we add a 'Order' column to the SharedDevices table, it should be possible to let them rearrange them as well.
