### ISSUE TITLE
Selector Switch blocks other switches from being shown on Dashboard

### ISSUE THREAD

**Issue by sincze** [domoticz/domoticz#5686]
Running Domoticz 2023.1

I created a Switch and changed the type to a Selector Switch. After that the switch was not visible anymore on the dashboard and subsequent created virtual switches were also not shown on the dashboard but were visible under Setup-Devices

Steps to reproduce: 
Setup:
- Setup - Hardware
- Create Virtual Sensor
- Create a Switch (give it a name)
- Switch will show up under switches. (Works as designed)

Switches tab
- Press Edit on the above created switch.
- Change Switch Type to Selector.
- Press Save

The switch is no longer seen on the Switches dashboard and any other created virtual switch after that one is not being shown on the dashboard either.

The switch is stored (Setup-Devices) as Light/Switch - Switch
I would expect it to be shown here as:  Light/Switch | Selector Switch

You need to remove this offending switch from the DB (can be done by pressing the trashcan) to have the switches that were created after this one to show up again.

**Comment by gizmocuz** [comment]
Please update to the latest beta version and try again

**Comment by sincze** [comment]
Used docker image: Domoticz 2023.1 (build 15223)
<img width="312" alt="image" src="https://user-images.githubusercontent.com/5776333/236410263-8f957590-4bef-4d25-9396-5d629418a958.png">

Issue not in this version anymore. Many thanks!

**Comment by gizmocuz** [comment]
Docker image uses the beta as default, so yet it should be solved.
