### ISSUE TITLE
Scene title in floorplan

### ISSUE THREAD

**Issue by olivierberthomme** [domoticz/domoticz#5687]
I have scenes in my from floorplans panel but I cannot get the title of scene displayed.
On the setup page #tabfloorplan, I have the opportunity to enable the FloorplanShowSceneNames checkbox ; unfortunately, that checkbox is not saved when I click save button.
I can enable FloorplanShowSwitchValues checkbox and that also enable the FloorplanShowScene names checkbox ; like if the 2 checkbox are linked to same value in the Domoticz config file. When I enable the 2 checkboxes, my floorplan display switches **and** scenes names (but I no not like it ; not human readable).

Is any chance to display the scenes names but not switches names from floorplan panel? It was possible in release 2022.2.

```
Version: 2023.1
Build Hash: f9b9ac774
Compile Date: 2023-02-14 15:06:40
dzVents Version: 3.1.8
Python Version: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
```

**Comment by gizmocuz** [comment]
Thanks for reporting! This was caused by setting the wrong setting internally.
Fixed in beta 15231
