### ISSUE TITLE
Domoticz crash every other day.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5689]
Version: 2023.1 (build 15223)
Build Hash: 8e441bce6
Compile Date: 2023-04-30 11:17:18
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]

My Domoticz crashes every other days or sometimes every day.
Enclosed part of the domoticz_crash.log

I have 2 'signal handler called' 1 on thread 2 and 1 on thread 35, both on SQLHelper.
There are a lot (growing) number of threads on SQLHelper and it looks like a lock_wait_private problem.
Google did not help me much to isolate the problem.
Also include part of the Domoticz log which lead to the crash.
The SolarEdge.py script is a script which fetches data from the SolarEdge website.

Anybody any idea?

[domoticz.log](https://github.com/domoticz/domoticz/files/11414869/domoticz.log)

[domoticz_crash.log](https://github.com/domoticz/domoticz/files/11414874/domoticz_crash.log)

**Comment by gizmocuz** [comment]
First step, disable the event system/dzvents see if thats working.
(That also includes your python script)

Why do you need to use a python script for your solaredge? I know for a fact that the default hardware in Domoticz works for the solaredge (web api)

**Comment by gizmocuz** [comment]
Seems you are calling your (not needed) python script from dzVents? Could you add your complete script here for reference so we can try to simulate things?
Maybe your script never returns?

**Comment by SargonofAssyria** [comment]
I think I use this setup from day 1 I use Domoticz (2015) Could it be that there was not SolarEdge hardware at that moment?
Strange that I get 4 responses about 10 sec. timeout (it is 8 sec. in the script) and multiple SolarEdge line with all zero's
In the crash log there almost 100 lines about SQLHelper.
Enclosed the dzVents script and python script. Python script is not mine.
Initially I had that python script running from cron, but changed that to this setup a few years ago, and was running fine.
I will look into the hardware SolarEdge
[solaredge.lua.txt](https://github.com/domoticz/domoticz/files/11415583/solaredge.lua.txt)
[SolarEdge.py.txt](https://github.com/domoticz/domoticz/files/11415584/SolarEdge.py.txt)

**Comment by gizmocuz** [comment]
There have been solaredge support for a long time... First we did a man in the middle and later via the api

**Comment by SargonofAssyria** [comment]
I will try starting today to use the script via cron again. These crashes are from the last weeks, and should to happen even in my setup, because that was working for a long time at least for the last year.
Disabling the event system/dzVents is not an option, because it could take a day or more before the crash happens. 
More then 110 dzVents scripts are running to control the house, you can imagine that's not an option.

**Comment by gizmocuz** [comment]
110 scripts sound also way to much... Most things should be possible via blockly or activation devices for scenes/groups
Solaredge can be used natively for years and years, no idea why you have a special script for this
Just disable that script, add the native support, use it, and replace your old devices with the new found once

**Comment by SargonofAssyria** [comment]
I did removed that script and used the Python script via cron for more then 2 days now.
System did not have a crash any more. So calling a Python script via dzVents (I would like to have all script centralized) seems to be problematic and leads to a crash. I will switch to native SolarEdge in a few days.
I like to have my house and other stuff as much as possible automated as possible, hence the number of scripts.
I take into account: weather, sun, holidays, ambient light (inside and outside), movement detection, an a lot of combinations, etc..... -> 110 scripts
