### ISSUE TITLE
How to debug RFXCom issue?

### ISSUE THREAD

**Issue by LordDarkneo** [domoticz/domoticz#5691]
Hello there,

More than a bug, I wanted to know if there is a way in domoticz to debug data received by the RFXCom.

I am facing the error : "Error: RFXCOM: Invalid data received!...." for few days now, and I cannot fix it... 
I have tried with the lastest beta, I have the exact same message (from the 2022.2, 2023.1 and beta 15234). As I am using docker on DSM, I dont know if it is the last version... I have also updated the firmware to 1048 on the RFXCom, without any changes.

What I'd like to do is to see why Domoticz falls in error. When plugging the RFXCom to my computer, data seems to be well received by the device when monitoring with RFXMgr. Moreover, the error has appeared for "no reason", meaning, everything was working fine, and suddenly I started to see latency in my temperature sensors updates, with the error message Error: RFXCOM: Invalid data received!.... in the logs.

Any help on a way to debug this behavior would be very much appreciated (it happened once quite a while ago, and I resolved it by simply unplugging the RFXCom, but this time everything I tried didnt fix the problem...)

EDIT: When updating the RFXCom hardware in domoticz, the logs are:

> 2023-05-09 14:58:07.307 Status: RFXCOM: Worker stopped...
> 2023-05-09 14:58:08.961
> 2023-05-09 14:58:08.961 subtype = Interface Response
> 2023-05-09 14:58:08.961 Sequence nbr = 2
> 2023-05-09 14:58:08.961 response on cmnd = Get Status
> 2023-05-09 14:58:08.961 Transceiver type = 433.92MHz
> 2023-05-09 14:58:08.961 Firmware version = 1048
> 2023-05-09 14:58:08.961 Firmware type = Pro XL1
> 2023-05-09 14:58:08.961 Noise Level: 71
> 2023-05-09 14:58:08.961 Hardware version = 3.0
> 2023-05-09 14:58:08.961 Undec off
> 2023-05-09 14:58:08.961 X10 enabled
> 2023-05-09 14:58:08.961 ARC enabled
> 2023-05-09 14:58:08.961 AC enabled
> 2023-05-09 14:58:08.961 HomeEasy EU enabled
> 2023-05-09 14:58:08.961 Meiantech/Atlantic enabled
> 2023-05-09 14:58:08.961 Oregon Scientific enabled
> 2023-05-09 14:58:08.961 ATI/Cartelectronic disabled
> 2023-05-09 14:58:08.961 Visonic disabled
> 2023-05-09 14:58:08.961 Mertik disabled
> 2023-05-09 14:58:08.961 AD disabled
> 2023-05-09 14:58:08.961 Hideki disabled
> 2023-05-09 14:58:08.961 La Crosse enabled
> 2023-05-09 14:58:08.961 Legrand disabled
> 2023-05-09 14:58:08.961 MSG4Reserved5 disabled
> 2023-05-09 14:58:08.961 BlindsT0 disabled
> 2023-05-09 14:58:08.961 BlindsT1 disabled
> 2023-05-09 14:58:08.961 AE disabled
> 2023-05-09 14:58:08.961 RUBiCSON enabled
> 2023-05-09 14:58:08.961 FineOffset disabled
> 2023-05-09 14:58:08.961 Lighting4 enabled
> 2023-05-09 14:58:08.961 Conrad RSL disabled
> 2023-05-09 14:58:08.961 ByronSX disabled
> 2023-05-09 14:58:08.961 IMAGINTRONIX disabled
> 2023-05-09 14:58:08.961 KEELOQ disabled
> 2023-05-09 14:58:08.961 Home Confort disabled
> 2023-05-09 14:59:12.196 Error: RFXCOM: Invalid data received!....
> 2023-05-09 14:59:43.434 Error: RFXCOM: Invalid data received!....

**Comment by gizmocuz** [comment]
Firstly, please update to the latest RFXCom firmware with the tool from RFXCom (RFXflash) (you have already done so, so not via Domoticz)
Next, try the RFXMngr application to see if you can find a problem

There can be multiple issues:
- you receive garbage (could be a temperature sensor that malfunctions... remove the batteries from all sensors to be sure)
- it could be the device is incorrectly handled in the function 'CheckValidRFXData'

RFXBase.cpp
`bool CRFXBase::CheckValidRFXData(const uint8_t *pData)`

**Comment by LordDarkneo** [comment]
> Firstly, please update to the latest RFXCom firmware with the tool from RFXCom (RFXflash) (you have already done so, so not via Domoticz) Next, try the RFXMngr application to see if you can find a problem
> 
> There can be multiple issues:
> 
> * you receive garbage (could be a temperature sensor that malfunctions... remove the batteries from all sensors to be sure)
> * it could be the device is incorrectly handled in the function 'CheckValidRFXData'
> 
> RFXBase.cpp `bool CRFXBase::CheckValidRFXData(const uint8_t *pData)`

Thanks for your reply. As said, I already tried to debug the device itself using RFXMngr (I miswrote the name in my initial post). But nothing seems to be crashing the RFXCom. And yes, I did the 1048 update through the rfxflash tool (not through Domoticz).
For instance, here's what I get after few minutes on my computer:

[RFRXCOM Desktop.log](https://github.com/domoticz/domoticz/files/11434839/RFRXCOM.Desktop.log)

So once again for me (and even for Bert) it's not an hardware issue... But I dont know how to debug on Domoticz side.... And when I check the source code, I should normally (from what I have in RFXMngr) return pLen = 0x0A (even if I don't know what drive me to an error on Domoticz side...). Even the message in the logs cannot be found with the char "!" followed by "...."

**Comment by gizmocuz** [comment]
Thanks for the log. I have tested with your log and don't see any issues.
All temp+hum devices are working well.

Can you install Domoticz also on your Windows system and test?

You continuously get this message, no valid sensors are being read/processed in the system?

How did you map your serial port in docker?

Did you use the 'serial/by-id' so no serial ports are mixed up? Like:

/dev/serial/by-id/usb-RFXCOM_RFXtrx433_XXXXXXXL-if00-port0

As you probably know, RFXCom transceivers are supported from day one, many users are using them (including me), running the latest versions myself, so i'm sure it is not a problem within Domoticz.

Now looking at your 'enabled' protocols in domoticz (Hardware->rfxcom->setup button), these are way to many!
If you only have temp+hum devices, start with disabling all of them! And enable Alecto and FineOffset
Strange thing is, that Viking temp sensor should only be received when 'FineOffset' is enabled but it seems you have this on disabled?

Anyway, I am curious to see what the Domoticz Windows version will see... (just to ourrule serial port issues)

**Comment by LordDarkneo** [comment]
> Can you install Domoticz also on your Windows system and test?

OK, I did the test, and everything seem to be fine...
[RFXCom - Windows Logs.txt](https://github.com/domoticz/domoticz/files/11439519/RFXCom.-.Windows.Logs.txt)
Even with all protocols activated...

> You continuously get this message, no valid sensors are being read/processed in the system?

Yes... This error appeared out of nowhere (everything was working fine and since this error appeared, I cannot remove it and fix my sensors communications...)

> How did you map your serial port in docker?
> Did you use the 'serial/by-id' so no serial ports are mixed up? Like:
> /dev/serial/by-id/usb-RFXCOM_RFXtrx433_XXXXXXXL-if00-port0

That's a very good question I do not think I made a particular configuration for USB (neither for the Network). But I am almost sure I did not set anything on docker for the USB configuration (I did it previsouly on my RPI, but not on Docker)
 
> Now looking at your 'enabled' protocols in domoticz (Hardware->rfxcom->setup button), these are way to many! If you only have temp+hum devices, start with disabling all of them! And enable Alecto and FineOffset Strange thing is, that Viking temp sensor should only be received when 'FineOffset' is enabled but it seems you have this on disabled?

OK, I'll clear it, But I am also using the RFX for some other devices ("opened-door" detector, Somfy blinds, etc...) And on a previous version, my Alecto devices were only compatible when LaCrosse was activated... (to be honest, other are tests I did not clear up... :/ )

So the best way is to delete the device and recreate it on my docker? or modify my USB configuration (any tutorial would really help :) ) ?

**Comment by gizmocuz** [comment]
What serial devices do you see in Domoticz from the hardware setup page?
Do you have more serial devices connected to your NAS?

I am no DSM expert at all but maybe this helps:
https://mariushosting.com/synology-how-to-add-usb-support-on-dsm-7/

Best if to ask these questions on the forum

And disable all protocols, enable only Alecto, start with this to see if this solves your issue

**Comment by LordDarkneo** [comment]
> What serial devices do you see in Domoticz from the hardware setup page? Do you have more serial devices connected to your NAS?

I see /dev/ttyACM0 and /dev/ttyUSB0 in Domoticz.
![image](https://github.com/domoticz/domoticz/assets/40838306/273626d0-e487-424d-8ba2-6f4997991c8a)
But in Docker, with bash commands, I see serial ports directly 
![image](https://github.com/domoticz/domoticz/assets/40838306/358037bc-5bf8-4036-9145-8d01b26337a3)

> I am no DSM expert at all but maybe this helps: https://mariushosting.com/synology-how-to-add-usb-support-on-dsm-7/

In fact, not really. This issue (with USB devices) is known since DSM 7.x (the Synology OS). That's why I am still on DSM 6, that did not have this issue (and this fix is not working as I am thus missing function in the kernel)

I'll update the protocols to keep only the necessary one and see how it goes.

EDIT: still the same issue....

> 2023-05-11 15:41:28.420 subtype = Interface Command
2023-05-11 15:41:28.420 Sequence nbr = 8
2023-05-11 15:41:28.420 set configuration of the interface
2023-05-11 15:41:28.645 subtype = Interface Response
2023-05-11 15:41:28.645 Sequence nbr = 8
2023-05-11 15:41:28.645 response on cmnd = Set Mode
2023-05-11 15:41:28.645 Transceiver type = 433.92MHz
2023-05-11 15:41:28.645 Firmware version = 1048
2023-05-11 15:41:28.645 Firmware type = Pro XL1
2023-05-11 15:41:28.645 Noise Level: 70
2023-05-11 15:41:28.645 Hardware version = 3.0
2023-05-11 15:41:28.645 Undec off
2023-05-11 15:41:28.645 X10 disabled
2023-05-11 15:41:28.645 ARC disabled
2023-05-11 15:41:28.645 AC disabled
2023-05-11 15:41:28.645 HomeEasy EU disabled
2023-05-11 15:41:28.645 Meiantech/Atlantic disabled
2023-05-11 15:41:28.645 Oregon Scientific disabled
2023-05-11 15:41:28.645 ATI/Cartelectronic disabled
2023-05-11 15:41:28.645 Visonic disabled
2023-05-11 15:41:28.645 Mertik disabled
2023-05-11 15:41:28.645 AD disabled
2023-05-11 15:41:28.645 Hideki disabled
2023-05-11 15:41:28.645 La Crosse enabled
2023-05-11 15:41:28.645 Legrand disabled
2023-05-11 15:41:28.645 MSG4Reserved5 disabled
2023-05-11 15:41:28.645 BlindsT0 disabled
2023-05-11 15:41:28.645 BlindsT1 disabled
2023-05-11 15:41:28.645 AE disabled
2023-05-11 15:41:28.645 RUBiCSON enabled
2023-05-11 15:41:28.645 FineOffset enabled
2023-05-11 15:41:28.645 Lighting4 disabled
2023-05-11 15:41:28.645 Conrad RSL disabled
2023-05-11 15:41:28.645 ByronSX disabled
2023-05-11 15:41:28.645 IMAGINTRONIX disabled
2023-05-11 15:41:28.645 KEELOQ disabled
2023-05-11 15:41:28.645 Home Confort disabled
2023-05-11 15:41:28.645 subtype = Interface Response
2023-05-11 15:41:28.645 Sequence nbr = 9
2023-05-11 15:41:28.645 response on cmnd = Save
2023-05-11 15:41:28.495 Status: RFXCOM: Async Disabled
2023-05-11 15:42:44.381 Dongle Zwave: Temp (Temperature Bureau)
2023-05-11 15:42:47.803 RFXCOM: RFY (Garage)
2023-05-11 15:42:48.642 Error: RFXCOM: Invalid data received!....

EDIT2: I gave a try with a new fresh install, with only adding the new hardware RFXCom (and not restoring my backups). And.... Issue is still. So I guess there is something wrong somewhere somehow between docker and DSM. I'll try to change the USB cable, just in case.... > Done bu issue is still.... :(

**Comment by gizmocuz** [comment]
I think you do, but to double check, you are using ttyUSB0 ?

Edit: You do not receive any device? Because you say 'latancy' ... sometimes you do receive them?

I would not want to stay on DSM6 ... for security reasons..

**Comment by LordDarkneo** [comment]
Sure, as shown in my printscreen I'm USB0 :)

and yes that's the point. Seems like the RFXcom is crashing but somtimes it received data (but as i performed many tests / db restore, I don"t have example to share... )

**Comment by gizmocuz** [comment]
Looks like a lot of 'garbage' is received, and sometimes a valid command passes through.
I have to experience with Synology <> Domoticz. I suspect that you have to search in this area.
Domoticz is having no issues with RFXCom hardware, using it myself, and many many users use this
Under windows you see no issues, so the device itself is functioning correctly.

**Comment by LordDarkneo** [comment]
OMFG.... "When in doubt, reboot"... I tried everything ths morning (including a brand fresh new install + restore on a RPI) and everything was working just fine... And my last idea was to reboot the Synology itself.... And everything's back just fine.... Arg...... 
I'll keep this in a part of my mind... Good thing is I am now on the latest release.... 
Thanks for your help @gizmocuz

**Comment by gizmocuz** [comment]
No worries, great it works again!

https://youtu.be/rksCTVFtjM4?t=37

**Comment by LordDarkneo** [comment]
What's frustrating is that I still do not know why it crashed... Anyhow yep, seems to be back correctly with only necesaary protocols activated (my "opened door" is Meiantech one). 

Once again thanks for your time and help!
