### ISSUE TITLE
Watermeter Flowis

### ISSUE THREAD

**Issue by Graffi18** [domoticz/domoticz#5693]
Hi.

How can I deal with such a water meter?

2023-05-17 15:26:53.028 Status: rtl?: Unhandled sensor reading, please report: ({"time" : "2023-05-17 15:26:52", "model" : "Flowis", "id" : 240259236, "type" : 1, "volume_m3" : 759.420, "device_time" : "2055-05-17T15:19:32", "alarm" : 0, "backflow" : 64, "mic" : "CRC", "mod" : "FSK", "freq1" : 867.960, "freq2" : 868.050, "rssi" : -0.129, "snr" : 26.218, "noise" : -26.346})

**Comment by gizmocuz** [comment]
We have to add support for this in the RTL hardware class...

Could you post a few more when you tap some water?

Do you have a link to the meter?

**Comment by gizmocuz** [comment]
Added support for this in beta 15243, thanks for reporting!

**Comment by Graffi18** [comment]
Hi gizmocus

Thanks for the help with the counter.

I updated domiticz to version 15243.
In the logs it gets the following value:
2023-05-20 12:09:17.320 sdr: RFXMeter (Flowis)
2023-05-20 12:10:12.400 sdr: RFXMeter (Flowis)
2023-05-20 12:14:23.702 sdr: RFXMeter (Flowis)
My guess is that the rtl device is working and the counter is decoding.
I can't find any instructions on how to add such counters to domoticz anywhere.
In settings, I enable accept new hardware, but no device is added.
There's a description of this somewhere, I can't find it anywhere.

**Comment by gizmocuz** [comment]
First, make sure you have 'accept new hardware devices' enabled in the settings
Now when you receive the water meter a new meter device should have been created, you should be able to see this under 'devices' where you can add them to the system
You might want to change the type (when you press edit on the device in the utility tab) to water

**Comment by Graffi18** [comment]
![image](https://github.com/domoticz/domoticz/assets/116602300/b6c96269-1192-4803-bb49-93338272da77)
I have "accept new hardware devices" turned on and I'm sure of it.
However, the devices still don't add up for me.
What other conditions must be met?

**Comment by gizmocuz** [comment]
None, and you don't see a new device in the devices table?

**Comment by Graffi18** [comment]
Unfortunately. I do not see.

**Comment by gizmocuz** [comment]
Okey, I debugged step by step, and I do get a new device

![image](https://github.com/domoticz/domoticz/assets/2265299/43171172-4223-41a0-8240-082d747836e5)

(Still in kWh here, but if you change the type to Water you will see it in m3)

Setup->Devices , maybe filter for rfxmeter ?

**Comment by Graffi18** [comment]
OK. I see. I believe it works for you.
Am I missing some permissions or is something blocked?

**Comment by gizmocuz** [comment]
No, if you have 'accept new hardware' enabled, it should just work... seems enabled so there is nothing more you can do.
Added quite a few supported types for RTL433 in Domoticz, should just work.

**Comment by gizmocuz** [comment]
It even logs correct with the correct name, so internally it finds the newly created devices as well.
If you want, please make a database backup from the settings page, and send me a PM on slack with the backup

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

**Comment by Graffi18** [comment]
In the evening I will install a new version of debian with a clean domoticz installation.
I will check again if it works.

Gizmocus, thank you for your help. I'll let you know when I run a clean version.

**Comment by gizmocuz** [comment]
Don't think a clean version will change it... but you can try. Else drop me your backup and I can check if it is really not there

**Comment by gizmocuz** [comment]
After a slack session it was because the admin user had devices assigned to his account missing this device.
But there was also a error that the devices page only displayed the (admin) users devices, but should have displayed all
