### ISSUE TITLE
Blinds timer bug fix

### ISSUE THREAD

**Issue by Andreotti100** [domoticz/domoticz#5695]
The timer for reversed blinds always results in 100% with my sunscreen. No matter what I dial in at the timer settings. Only a percentage value between 1 and 99 % worked, but never fully open or close.

I debugged, changed and compiled the code with my fix, and now it is working as it should. This is my change in Scheduler.cpp: 

 /*** 18-05-2023 A.S.: Fix voor blinds timer ***/
//  else if (
//    (switchtype == STYPE_BlindsPercentage)
//    || (switchtype == STYPE_BlindsPercentageWithStop)
//    )
//  {
//    if (item.timerCmd == TCMD_ON)
//    {
//      switchcmd = "Set Level";
//      float fLevel = (maxDimLevel / 100.0F) * item.Level;
//      if (fLevel > 100)
//        fLevel = 100;
//      ilevel = int(fLevel);
//    }
//    else if (item.timerCmd == TCMD_OFF)
//    {
//      switchcmd = "Close";
//      ilevel = 0;
//    }
//  }
    else if (
      (switchtype == STYPE_BlindsPercentage)
      || (switchtype == STYPE_BlindsPercentageWithStop)
      )
    {
      if (item.Level > 0 && item.Level < maxLevel) // set position to value between 1 and 99 %
      {
        switchcmd = "Set Level";
        float fLevel = (maxDimLevel / 100.0F) * item.Level;
        if (fLevel > 100)
          fLevel = 100;
        ilevel = int(fLevel);
      }
      else if (item.timerCmd == TCMD_ON) // no percentage set (0 or 100)
      {
        switchcmd = "Open";
        ilevel = 100;
      }
      else if (item.timerCmd == TCMD_OFF) // no percentage set (0 or 100)
      {
        switchcmd = "Close";
        ilevel = 0;
      }
    }
    /*** End fix blinds timer */

**Comment by gizmocuz** [comment]
Great find!! Could you make a pull request (PR) for this? If you fork this project , then clone your fork, make the change, commit and push it, you should see a button 'make pull request'

**Comment by Andreotti100** [comment]
Thanks buddy!
I made the pull request. Never done that before so I hope it was successful.

**Comment by gizmocuz** [comment]
Looking great! I merged it and will be available later today in a new beta version!
I am going to modify it a little bit ... instead of casting it to a integer, i'm going to round it to the nearest integer.
And if (for some strange reason!) the level is higher than the maximum allowed level, none of the IF statements are being called

**Comment by gizmocuz** [comment]
I think the code should be:

```
								if (item.Level > 0)
								{
									// set position to value between 1 and 99 %
									switchcmd = "Set Level";
									float fLevel = (maxDimLevel / 100.0F) * item.Level;
									if (fLevel > maxDimLevel)
										fLevel = maxDimLevel;
									ilevel = round(fLevel);
								}


```

**Comment by gizmocuz** [comment]
Should be working in beta 15241, thank you again!

**Comment by Andreotti100** [comment]
No problem, but it is not solved now.
< maxDimLevel has to be part of comparison. Like this: if (item.Level > 0 && item.Level < maxDimLevel)
With the reversed blinds 0% timer setting will be 100% when reversed. So the sunscreen is still going to full extent when I want it to close by the timer. Setting the timer at Open and 100% also does not do the trick.

**Comment by gizmocuz** [comment]
Okey, I am just testing right now with a manual added dummy blind (Add manual light from the lights/switches page) with type AC. The AC has 15 steps
The timer programmed is to set it at 34%, so the final value should be

level = (15 / 100) * 34 = 4

But, because of the item.Level (34) < macDimLevel (15), the new code is never called, so I think it has to be item.Level < 100

**Comment by gizmocuz** [comment]
Should be corrected now in beta 15246

**Comment by Andreotti100** [comment]
Yes, excellent!
Thanks very much Gizmocuz for your quick action, now it is perfect 👍

**Comment by gizmocuz** [comment]
Well you did 99% of the job! Great it works now!
