### ISSUE TITLE
RFLink wrong switch type on Manual Learn : Blinds instead of On/Off

### ISSUE THREAD

**Issue by Di-Ny** [domoticz/domoticz#5698]
Hi, 

### Issue
When creating a new Manual Switch for the RFLink, the wrong type is assigned automatically to "Blinds". This may be related to the issue #5442 

### Reproduce
- Go to Switches
- Click Manual Light/Switch 
- Select Hardware = RFLink, Switch Type = On/Off, Type = EV1527, ID = random, Unit code = 1.
- Click Add Device 
- Check the newly created device : it show Type : Blinds, with the Light bulb icon.

![Capture d'écran 2023-05-24 163412](https://github.com/domoticz/domoticz/assets/17185396/b9c839d1-db35-42ff-8e8e-03d686bfd987)

![Capture d'écran 2023-05-24 163502](https://github.com/domoticz/domoticz/assets/17185396/18cc401c-d473-4e0d-b91d-83c3a1550f13)

![Capture d'écran 2023-05-24 163558](https://github.com/domoticz/domoticz/assets/17185396/2e833f56-b9ce-4ffe-9b8e-b9418f33c8ff)

### Version 
Domoticz 2023.1
RFLink Gateway USB

I remembered this fonctionnality working well maybe 1 or 2 yeras ago, haven't tried downgrade or beta versions since I am not so confident on how I may break the system. 
Probably not a cache issue since I juste tested on a new computer / browser.

**Comment by gizmocuz** [comment]
Question, why do you need to add a manual RFLink switch? Is it a dummy switch? Then add a dummy hardware (if you have not done so before), and add the switch here (from within the hardware setup page)

The issue you report is the same when adding this type to other hardware then RFLink

Do you need a EV1527, or is a general switch ok?

**Comment by gizmocuz** [comment]
Latest beta version should solve the creation of this type

**Comment by Di-Ny** [comment]
Hi, I need it to pair a 433 Mhz smart plug. I set it in pairing mode by pressing the button, then it listens to a 433 MHz signal as a new paired switch. This signal is emitted by the RFLink, and only EV1527 or Eurodomest are supported by the plug. 

Thanks for beta patch :) Not sure how to try this safely, I'll maybe add a dev environment. 

Kind reagrds, 
Nico

**Comment by gizmocuz** [comment]
@Nico, just update to the latest beta?
