### ISSUE TITLE
Timers for RFY2 blinds not working

### ISSUE THREAD

**Issue by Bimnomercy** [domoticz/domoticz#5699]
Version: 2023.1 (build 15248)
Build Hash: cbeebf26a
Platform : Docker on Synology NAS

Hello, I have just updated my version of DomoticZ and I noticed that the timers of my blinds typed RFY2 does not work.
I can control my shutters with the buttons, they work without problems, but the timers does not work.

![b1](https://github.com/domoticz/domoticz/assets/4503249/6c506566-5489-4d64-839a-ca2b9e71930f)

The control works perfectly in the 'Switches' tab...

![b2](https://github.com/domoticz/domoticz/assets/4503249/99af1c8f-4e24-4892-8722-aa6e7e828d35)

But the timer does not work. It was working on 2022.1 version.

There is no error in logs.

I want to specify on the other side that Lightning 2 switches timer works perfectly.

**Comment by Bimnomercy** [comment]
I did several test, and I found that notification are not working too for this type of switches when you configure to send an email when you click on open or close button.

I also tried to delete a switch and recreate it (Somfy RTX), and I noticed that the brand new switch did not work at all like before. I presume that the command sent is wrong. Luckily I had made a backup and was able to revert to the old version.

**Comment by Bimnomercy** [comment]
Bad news, today, none timers are firing anymore... I am demoralised.

**Comment by gizmocuz** [comment]
3 messages in 12 hours.... okey .....

There have been a recent change related in blind timers, I will have a look at this

In the meantime, you know you can revert a version? When you update, a backup is made in the backup folder
Or if you are using docker, you can checkout a specific version

If you cannot wait, you can have a look in the code itself to see what's wrong and submit a PR

**Comment by Bimnomercy** [comment]
Thank you for you answer. I've looked for the previous version, but I didn't find it on docker. I know that the database version is 155 and I think that the build is 14298, but it seems to does not longer exist on Docker.

**Comment by gizmocuz** [comment]
https://hub.docker.com/r/domoticz/domoticz/tags

**Comment by gizmocuz** [comment]
in your docker compose file checkout the specific build number you want (like from 16 days ago)

**Comment by Bimnomercy** [comment]
Unfortunately, version 14298 could not be found. No worry about that, I will wait for a fix, and I am available to provide any help needed.

**Comment by Bimnomercy** [comment]
I continue to investigate, and with a dummy switch :

![test](https://github.com/domoticz/domoticz/assets/4503249/9e91bef8-7a73-43e9-ac8e-5d3d6bd85df4)

 I could see that the operation of the timer works randomly.

By programming an on and off schedule, I could see that the programmed events are sometimes launched, and the next time not.

**Comment by waltervl** [comment]
Be aware that for testing you need to set a trigger time > 2 minutes from current time...

**Comment by Bimnomercy** [comment]
Thank you for the precision, but I've just declare at 10:28 an ON event at 10h31 and an OFF event at 10h32.
The ON event fired correctly, but not the off event.

And the blind trigger are ramdomly fired like the dummy switch.

**Comment by gizmocuz** [comment]
I just tested the timers on the RFY blinds.
There seems to be nothing wrong. Schedule a Open (0%) or Close (0%) will open or close the blinds at the correct time
As walter mentioned, make sure you schedule a timer at least 2 minutes in advance.

If you have randomness with lights/switches, check your system time/ntp client

But, I noticed something strange for RFY2 (which you seem to have)
What was your previous version?

Did it ever worked?

Because when I time a open/close I get a new device (a type RFY)

I already have a fix internally for this

The RFY2 is used with a RFXtrx433?

**Comment by Bimnomercy** [comment]
The previous version was the build 14298, and everything was working perfectly.

Here is my hardware list :

![Capture d’écran 2023-05-25 140154](https://github.com/domoticz/domoticz/assets/4503249/56f68478-a505-4c40-a6dd-e458fcf0c65f)

**Comment by gizmocuz** [comment]
So 950 versions earlier... hmmmm

Could you try beta 15249

**Comment by Bimnomercy** [comment]
Yes, download in progress...

**Comment by Bimnomercy** [comment]
This version seems to work. I just did an open and close with 1 minutes delay, and my blind did them.
I schedule an blind close tonight, 10 minutes after sunset and an open tomorrow morning, I will inform you about th success.

Thank you for your fantastic work !!!

**Comment by gizmocuz** [comment]
Great!

Could it be that it did not 'look' like to be working, but the blind commands where send out? (But the status in Domoticz was not updated correctly)?

The reason for this is that I fixed a GUI display issue.

But in the mean time there have also been other blind timer patches

**Comment by Bimnomercy** [comment]
I've just realize that there is no python embedded in 15249 version, is it right ?

**Comment by gizmocuz** [comment]
no, that has not changed at all

**Comment by Bimnomercy** [comment]
Sorry, it was because I forgot to install python dependencies for ZigBeeforDomoticZ for this new version.

**Comment by gizmocuz** [comment]
While you are using docker (docker compose i hope) you might consider using zigbee2mqtt and in domoticz use the MQTT Auto Discovery hardware

**Comment by Bimnomercy** [comment]
I'm not enought user friendly with Docker (On a Synology NAS) to configure it like you say.

**Comment by Bimnomercy** [comment]
A quick message to say that everything worked out well. Both for closing the blinds last night and opening them this morning.

Thanks again for your responsiveness.

**Comment by gizmocuz** [comment]
Thanks for the feedback! Great it's working!
