### ISSUE TITLE
shortlog selectable interval

### ISSUE THREAD

**Issue by delchrys** [domoticz/domoticz#570]
Hello Coders,
is it possible to change SQLHelper.cpp so you can make the interval of the readings selectable.
I have a very small domoticz interface, with about 10 sensors so i have a small database.
I would like to select a interval of 1 minute for my shortlog. I have done it already by changing some lines in the sqlhelper.cpp  file and it works. But every update i do on the program, the changed cpp file is overwritten. I would like to have the possibility to change it in the settings menu (with warning of growing database size) so i do not need to recompile the cpp file again.
with kind regards Bert

**Comment by mledoujet** [comment]
good idea. I was looking for same thing

**Comment by gizmocuz** [comment]
Why is this ?
In your database, in the preferences when you have a field ShortLogInterval, and set this to 1 (or what ever value), this should not be overwritten by the next update ?

```
    if (!GetPreferencesVar("ShortLogInterval", nValue))
    {
        nValue = 5;
        UpdatePreferencesVar("ShortLogInterval", nValue);
    }
    if (nValue < 1)
        nValue = 5;
    m_ShortLogInterval = nValue;

```

Unless you patched the code in the wrong way... you do not need to patch the code,
only change it in the database

**Comment by gizmocuz** [comment]
... and there is actually a setting in the html... which is hidden

**Comment by gizmocuz** [comment]
but imagine what impact it has for users with 300 devices (like me)... thats why it is an advanced setting

**Comment by delchrys** [comment]
I will look in to my previously editted file, maybe something gone  wrong. 
So how can I get to the secret setting In the html code? 
I know it has a large impact when someone has lots of sensors, but that is not my case, and a use at own risk will be a good warning.
