### ISSUE TITLE
[Enphase] Microinverter widgets turn red after sunset

### ISSUE THREAD

**Issue by 0crap** [domoticz/domoticz#5701]
Setup:
- Domoticz 2023.1 running on a Pi 3
- Enphase Envoy-S D7.0.88

After sunset all the microinverters and the total production counter turn red.
![Screenshot_20230526_025043_Chrome](https://github.com/domoticz/domoticz/assets/31951195/fb35287f-fef0-4dec-a9a5-a3a8503e62c2)

Because it's normal they don't update when it's dark outside, they should stay the normal grey color.
Not red, indicating there is a problem.

Is it possible to change the icons to what is shown below?
Would be nice if that can be the default.
![PV_icon](https://github.com/domoticz/domoticz/assets/31951195/979d299a-d997-4329-ab66-85478ebd606b)

**Comment by kiddigital** [comment]
How can Domoticz know if it does not receive any data, if that is ok (as expected) or indicates a problem?

If the inverters would sent 0 , which is the case when it is dark, then it is clear for Domoticz that things are working and the correct information is received.

**Comment by 0crap** [comment]
Exactly like you say, if they send a 0 when it's dark there is no problem.
So why turn red?

It might have to do with the icon or something?
All I know is that the previous plugin I used did not have this issue and used the "solar/connector" icon.
With the native Enphase implementation I get the "lightning" icon...

**Comment by gizmocuz** [comment]
It has nothing to do with the icon, but just by the fact that internally we use a method that it does not poll during sunset en sunrise (+ 1 hour)
Solution is to update the LastUpdate field and it would be solved

**Comment by 0crap** [comment]
OK, is that something I can do as a user?

**Comment by gizmocuz** [comment]
Yes, you could edit the code and make a patch/PR that we can merge.
But I already did that for you.
New beta in an hour (15255), this should solve the problem.
Is it possible to verify this?

**Comment by 0crap** [comment]
Sure! Thanks for the quick fix.
I'll enable Beta under "Setup"->"Settings" and see if it pops up.

Last question:
I got the total production screenshot form the wiki.
Any idea why I get these "lightning" icons and not the "solar/connector" icons as shown?

**Comment by gizmocuz** [comment]
You have to press edit on the widget and change it to consumption... (this might also solve the issue bdw!)

**Comment by 0crap** [comment]
> You have to press edit on the widget and change it to consumption... (this might also solve the issue bdw!)

Yes! That did the trick, much nicer icon for a PV system. (Make that the default please.)
I'll first try if this fixes the turning red issue.
If not, I'll test the beta.

Will report back.

**Comment by gizmocuz** [comment]
Thanks for testing! And no, you have to change the type yourself...

**Comment by 0crap** [comment]
No problem, happy to test.
And changing the icon was easy.
![Screenshot_20230526_124636_Chrome](https://github.com/domoticz/domoticz/assets/31951195/c21a99d6-5a00-47dd-a26f-29830d076aeb)

**IF** this fixes the initial issue, it would be a nice solution to make it the default.
But let's wait and see before jumping to conclusions.

I tried if I could update the wiki with the information on how to change the icon, but I can't login.
Seems a good idea to add how to change it.

**Comment by 0crap** [comment]
@gizmocuz Setting `Type: Return` fixed the icon but keeps giving a red widget after sunset.
(Would have been a really clever solution if that also fixed the red widget.)
![Screenshot_20230526_235545_Chrome](https://github.com/domoticz/domoticz/assets/31951195/536923f5-cb3b-4b3d-ad28-2c0171cfa08f)
~~Anyway, I've enabled Beta under "Setup"->"Settings" and see if a beta pops up.~~
Installed a second Domoticz so I don't have to set my production Domoticz into beta.
![beta](https://github.com/domoticz/domoticz/assets/31951195/adf5fe1a-08c4-47f2-b2ca-a8dbc2eeb7ec)
I'll report back. 👍

**Comment by 0crap** [comment]
Fix confirmed, no more red.
Thx!
![Fix](https://github.com/domoticz/domoticz/assets/31951195/dbdcac02-881c-4b76-8ee5-3467ae479040)
