### ISSUE TITLE
[Enphase] Default widget type

### ISSUE THREAD

**Issue by 0crap** [domoticz/domoticz#5702]
If you add your Enphase PV system to Domoticz, by adding Hardware "Enphase Envoy with LAN (HTTP) interface" the inverters and total counter are created.
![Default](https://github.com/domoticz/domoticz/assets/31951195/571ba8a4-3032-42ac-9c2f-3149d8ddb249)

However the Widget type is by default "Usage".
![Type](https://github.com/domoticz/domoticz/assets/31951195/eeb8ed14-9d06-4c4c-a361-c4e7bf3f39cb)

Could the default Type be changed to "Return"?
This is more logical for a PV system and matches with the [Wiki](https://www.domoticz.com/wiki/Enphase). (Icon is different for type "Return".)

**Comment by gizmocuz** [comment]
It's not that hard to change it yourself? But please feel free to make a PR for this.

**Comment by 0crap** [comment]
> It's not that hard to change it yourself? But please feel free to make a PR for this.

Sure, already changed it manually myself, but that is not the point.
I logged this issue because it can improve the out of the box experience for first time users.
I'm not a coder, so no PR from my side, but always willing to test if needed.

**Comment by anno006** [comment]
> It's not that hard to change it yourself? But please feel free to make a PR for this.

Sure it is not, but when you have 30+ solar panels it takes about 4 hours to change everything including the sensor type.

**Comment by gizmocuz** [comment]
@anno006 , I am expecting a PR from you to change this.

**Comment by gizmocuz** [comment]
Since you probably rename them as well, you can change the type too.
Surely it does not take more then 10-20 seconds per panel.
Have not seen a PR, closing issue
