### ISSUE TITLE
Several AutoDiscovery Issues

### ISSUE THREAD

**Issue by sincze** [domoticz/domoticz#5704]
Domoticz 2023.1 15163

Noticed the following issues with Domoticz & Autodiscovery (zwave-js-ui). 
But unsure if I need to create an issue for each item.

1. My (Ampere) meters from OpenZwave *CM113, Electrisave) are now created in autodiscovery as: Type (General) Current.
Hence it seems I am unable to replace the old with the new.. (Net items are not shown in the list). V, kWh, W are easily replaced.
![image](https://github.com/domoticz/domoticz/assets/5776333/46e2a9b0-f0a6-418f-a693-0649b0763285)

2. Second thing I noticed is while replacing a lot of devices the webserver becomes unusable.
`Error: WebServer:8080 thread seems to have ended unexpectedly (last update 62.000000 seconds ago)`

3. Replace Switch.
While replacing a switch on the switch tab after pressing ok it jumps back to the DASHBOARD in stead of staying on the SWITCH tab.
Replacing a utility on the utility tab keeps you on the utility tab.

4. NEO Coolcam sensor negative value.
I unfortunately have some NEO Powerplugs known for their negative or positive values.
![image](https://github.com/domoticz/domoticz/assets/5776333/530be45f-adcf-4716-b960-e1531a8024b4)

https://github.com/zwave-js/node-zwave-js/issues/2692
CODE: [SELECT ALL](https://www.domoticz.com/forum/viewtopic.php?t=39292&start=200#)

This device is buggy and sends large negative Meter Reports from time to time.
In OpenZwave time Domoticz used to IGNORE these messages, https://github.com/domoticz/domoticz/issues/4277,
But it seems with the MQTT solution these negative numbers are back in town.

**Comment by sincze** [comment]
Would it be possible to solve issue #4. NEO Coolcam sensor negative value, on accepting the MQTT message?

**Comment by gizmocuz** [comment]
@sincze , could you test beta 15384 to see if this solves this issue? But I also think this is better handled on the zwavejs side?

**Comment by sincze** [comment]
> @sincze , could you test beta 15384 to see if this solves this issue? But I also think this is better handled on the zwavejs side?

Allow me to update my docker ;-). -> Time: 11:12 Deployed beta 15384, let's wait.

Regarding your idea to fix it on the zwavejs side I found the following remark:
https://github.com/zwave-js/node-zwave-js/issues/2692#issuecomment-1012907609
-> Seems like a 'No-Fix' & 'Do Not Buy' to me. Downside is people already got tricked into buying.

**Comment by sincze** [comment]
@gizmocuz  mmm. This is not what I should have expected right ? It shoots to both ends positive and negative.

![image](https://github.com/domoticz/domoticz/assets/5776333/5cf80994-99ed-4e1d-8894-b441d5e845c2)

**Comment by gizmocuz** [comment]
Ehm nope, but where these values correct before today? If not, you have to wait until tomorrow (or delete the sensor)

**Comment by gizmocuz** [comment]
> Regarding your idea to fix it on the zwavejs side I found the following remark: [zwave-js/node-zwave-js#2692 (comment)](https://github.com/zwave-js/node-zwave-js/issues/2692#issuecomment-1012907609) -> Seems like a 'No-Fix' & 'Do Not Buy' to me. Downside is people already got tricked into buying.

Hmmm okey It's not only Domoticz that will have this issue I suppose, also HASS?

**Comment by sincze** [comment]
> > Regarding your idea to fix it on the zwavejs side I found the following remark: [zwave-js/node-zwave-js#2692 (comment)](https://github.com/zwave-js/node-zwave-js/issues/2692#issuecomment-1012907609) -> Seems like a 'No-Fix' & 'Do Not Buy' to me. Downside is people already got tricked into buying.
> 
> Hmmm okey It's not only Domoticz that will have this issue I suppose, also HASS?

Yes sir: multiple posts indeed
https://community.home-assistant.io/t/energy-consumption-for-neo-coolcam-plug/219844/5

**Comment by gizmocuz** [comment]
Try to make a patch in zwavejs to not accept these crazy counter values, anyway, you have not said yet if you had correct values today or not.
If not, let's see tomorrow (and days after) to see if it's solved in Domoticz

**Comment by sincze** [comment]
> Try to make a patch in zwavejs to not accept these crazy counter values, anyway, you have not said yet if you had correct values today or not. If not, let's see tomorrow (and days after) to see if it's solved in Domoticz

Let's test our patience and wait for tomorrow. 
This will eliminate any MQTT residue left in the system. 
I spun up a new Domoticz with new MQTT Autodiscovery plugin and we have seen the results in the screenshot.  Best to wait for the day to end.

For now the latest BETA looks like ;-) :
![image](https://github.com/domoticz/domoticz/assets/5776333/40c68363-8cb8-4dac-a874-2cbf56830a81)

**Comment by gizmocuz** [comment]
That would mean my patch ain't working correctly...
Okey checked it again, and noticed that when receiving the kWh value I was checking against the power (Watt) value
This has been corrected in beta 15387

**Comment by sincze** [comment]
![image](https://github.com/domoticz/domoticz/assets/5776333/4f83fe17-8ede-440a-91af-08b07b7d1b0f)

Hold your horses ;-) I could not resist. This looks better, but let me update to 15387


19:52: So indeed the 15384 is now showing this.
![image](https://github.com/domoticz/domoticz/assets/5776333/d667427a-27b2-43e0-871b-3b0d3a506db2)

19:54 the 15387 is showing this.
![image](https://github.com/domoticz/domoticz/assets/5776333/906a3efc-d8cf-4b16-9320-5f94f805db2d)

**Comment by gizmocuz** [comment]
Nice! let's hope it keeps this way, please monitor it for a few days (not sure how often you get those strange values from NeoCool)

**Comment by sincze** [comment]
![image](https://github.com/domoticz/domoticz/assets/5776333/e9774295-f5d2-48f5-b284-b734e32f8395)

Currently my test setup. It seems your first patch does not work.
Second patch is holding on ;-) by not allowing the values to reach Domoticz DB.
And the dzEvents script is correcting the received values.

I'll continue to monitor the situation.

```
2023-07-10 11:19:01.665 Status: dzVents: Info: NEO Coolcam kWh Fix: ------ Start internal script: NEO Correction: Device: "NEO_Desk_Saskia (kWh) (Zwave-JS-UI)", Index: 726
2023-07-10 11:19:01.677 Status: dzVents: Debug: NEO Coolcam kWh Fix: device[NEO_Desk_Saskia (kWh)] was changed to [38.530;554350.000]
2023-07-10 11:19:01.677 Status: dzVents: Debug: NEO Coolcam kWh Fix: total is 554350.0, usage=38.53
2023-07-10 11:19:01.677 Status: dzVents: Debug: NEO Coolcam kWh Fix: adding to history
2023-07-10 11:19:01.703 Status: dzVents: Info: NEO Coolcam kWh Fix: ------ Finished NEO Correction

```

**Comment by sincze** [comment]
Best fix (also graph cosmetics) seems to be your fix @gizmocuz 
![image](https://github.com/domoticz/domoticz/assets/5776333/6691738e-b562-42d2-954f-c52723a2de64)

**Comment by gizmocuz** [comment]
Great! Glad it's working out for you, hope ZWaveJS-UI will make a patch themselfs so all applications using it will benefit from it.
Thanks for testign! Closing issue
