### ISSUE TITLE
Unable to save new events on latest beta

### ISSUE THREAD

**Issue by jfalmeida** [domoticz/domoticz#5706]
![image](https://github.com/domoticz/domoticz/assets/2064092/bb4d06ae-8d4f-40ae-bea7-719edc03c7ae)

I've compiled a clean version from scratch and I'm having the error in the picture attached. 

Let me know if you need any other information.

**Comment by gizmocuz** [comment]
Thanks for reporting. A code patch have been submitted that should solve this issue.
It was caused by a large PR to cleanup the webserver code.
Beta's are being build but could take quite some time, but if you are compiling, you should have no issue

**Comment by Dylantje** [comment]
Please a update for the normal beta channel possible?
Or how can i fix this problem?

**Comment by kiddigital** [comment]
Make sure you have the latest Beta.

**Comment by Dylantje** [comment]
> Make sure you have the latest Beta.

15330 is here

**Comment by jfalmeida** [comment]
Hey, I've just compiled the latestest version and it seems that I have a different error now
![image](https://github.com/domoticz/domoticz/assets/2064092/152e11d5-5c49-4435-914d-0b5f381395dc)

**Comment by gizmocuz** [comment]
@jfalmeida , we can't understand from a picture what goes wrong

**Comment by jfalmeida** [comment]
Any way to add more information? Is this something reproducible on your end?

I did a clean install to test it.

**Comment by gizmocuz** [comment]
If you want me to help on my free Sunday, you could at least describe your problem instead of posting a image.
It seems the event is created, you can see this when you refresh your browser.
The reason why there is a error message is not yet clear

**Comment by gizmocuz** [comment]
hopefully beta 15331 has solved the issue (there was also a issue with deleting a event)

**Comment by jfalmeida** [comment]
Hey gizmocuz,

I'm sorry if I didn't made myself clear. I am trying to create a new event (Lua script, dz script..) and when I hit the save button the event is not added to the list on the right (this is how it works on stable release afaik). Let me do what you have suggested, hit save and the refresh the page and check if the event appears on the list.

**Comment by gizmocuz** [comment]
Should be solved now in beta 15331

**Comment by jfalmeida** [comment]
Just retested it and it is now working! Thank you!

**Comment by gizmocuz** [comment]
Thanks for testing!
