### ISSUE TITLE
Domoticz  takes >10 minutes to reconnect esp8266 after ESP powercycle why ?

### ISSUE THREAD

**Issue by fscoelho** [domoticz/domoticz#571]
Dear all, 

I am using ESP8266 with arduino IDE 1.6.5 and my sensors.
After making a power cycle on ESP8266 Domoticz takes more than 10 minutes to reconnect.
Note: data timeout is disable.
if in domoticz i disable and re-enable the connecion is then immediate the communication.
Why domoticz can not detect the connection failure  ? and how to solve the problem it is a bug ?
It seems domoticz it is monitoring the connection correctly ?

Many thanks
FCoelho

**Comment by gizmocuz** [comment]
That is how TCP/IP works, you dont close the connection gracefully, so the other party (domoticz) does not know it is down....and just listens for data
What domoticz version do you use ? As i build in a handshake some time ago (is also build in the latest stable version)
Do you use MySensors 2.0 (or higher) ? Try using this

**Comment by gizmocuz** [comment]
Also please use our forum, we have 6000+ people who could answe
