### ISSUE TITLE
API timers not working

### ISSUE THREAD

**Issue by vespino** [domoticz/domoticz#5710]
I'm running the latest version of Domoticz in Docker (Version: 2023.1 (build 15331)) and since a few updates the timers API has stopped working. If have always made calls to URLs like these:

`https://<fqdn>/json.htm?type=timers&idx=<idx>`

This now results in "status" : "ERR"

This is also the case when using the following URL:

`https://<user>:<pass>@<fqdn>/json.htm?type=timers&idx=<idx>`

/json.htm?type=schedules&filter=scene also gives the same result.

**Comment by kiddigital** [comment]
Please check [this](https://www.domoticz.com/forum/viewtopic.php?p=303581#p303581) forum topic for more details. There have been some changes to the API in the latest Beta's

**Comment by vespino** [comment]
@kiddigital I don't understand what this means. The specific endpoint was removed? The wiki still shows the ones I'm referring to: https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Get_all_schedules.28timers.29_for_one_Device

**Comment by kiddigital** [comment]
> @kiddigital I don't understand what this means. The specific endpoint was removed? The wiki still shows the ones I'm referring to: https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Get_all_schedules.28timers.29_for_one_Device

@vespino ,  The endpoint in that specific syntax has been replaced by an updated syntax:
```
https://<fqdn>/json.htm?type=command&param=gettimers&idx=<idx>
```

The Wiki is still valid as it is about the Stable release. The updated syntax is on the current Beta's.

**Comment by vespino** [comment]
Cheers.

**Comment by vespino** [comment]
One more thing: I have made changes to all places I can think of using the API, but every 15 minutes I'm still getting 32 of these logs:

` Status: [WebServer] Depricated RType (devices) for API request. Please use correct API Command!`

How can I locate where these are coming from?

**Comment by kiddigital** [comment]
@vespino , you could run domoticz with several debug flags and if you enable webserver (` -debuglevel webserver`) you will see each incoming request and where it comes from.

You should not see these messages if you are just using the domoticz UI. If you do, your browser cache has to be cleared because you are using the old javascript files and not the updated ones.

**Comment by vespino** [comment]
@kiddigital I’m looking at the logfile, so how can this be cache related I’m wondering? Further more: I’m probably running the most simplified setup on Docker.

Will try changing the debuglevel if I can figure out how.

**Comment by vespino** [comment]
It's the following calls (and similar) causing the logs:

```
Debug: CWebServer::GetJSonPage(rtype) :devices :/json.htm?type=devices&rid=65
Debug: [web:8444] Host:10.0.0.6 Uri:/json.htm?type=devices&used=true&order=Name&plan=6
Debug: CWebServer::GetJSonPage(rtype) :devices :/json.htm?type=devices&used=true&order=Name&plan=6
```

This is however a process that is beyond my control. These calls also don't result in ERR, but in the original response.

**Comment by vespino** [comment]
Think I found the cause. I'm using homebridge for controlling my smarthome via Google Home. The plugin is probably still using the old(er) API version. I will inform them of the changed needed.
