### ISSUE TITLE
MQTT AD: Cover device set_pos_tpl partially supported

### ISSUE THREAD

**Issue by enesbcs** [domoticz/domoticz#5711]
In the following configuration line, there is a set_pos_tpl template for a Shelly2PM cover device.

Topic: homeassistant/cover/shellyplus2pm-a8032abcf5f0-roller-0/config

Payload:
`{"name": "shellyplus2pm-a8032abcf5f0 Roller 0", "enabled_by_default": false, "cmd_t": "~rpc", "pl_open": "{\"id\":0,\"src\":\"domoticz\",\"method\":\"Cover.Open\",\"params\":{\"id\":0}}", "pl_cls": "{\"id\":0,\"src\":\"domoticz\",\"method\":\"Cover.Close\",\"params\":{\"id\":0}}", "pl_stop": "{\"id\":0,\"src\":\"domoticz\",\"method\":\"Cover.Stop\",\"params\":{\"id\":0}}", "stat_t": "~status/cover:0", "value_template": "{{ value_json.state }}","state_closing": "closing","state_opening": "opening","state_open": "open","state_stopped": "stopped","state_closed": "closed","pos_t": "~status/cover:0", "pos_tpl": "{{ value_json.current_pos }}","pos_open": 100, "pos_clsd": 0, "set_pos_t": "~rpc","set_pos_tpl": "{\"id\":0,\"src\":\"domoticz\",\"method\":\"Cover.GoToPosition\",\"params\":{\"id\":0,\"pos\": {{ position }} }}", "uniq_id": "shellyplus2pm-a8032abcf5f0-roller-0", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "qos": 1, "~": "shellyplus2pm-a8032abcf5f0/"}`

Unfortunately the MQTTAD seems omitting "set_pos_tpl" {{ position }} tag ( https://www.home-assistant.io/integrations/cover.mqtt/#set_position_template ) instead just cleaning up every JSON structure element {"} and appending the position to the end of the string, for example this is the expected payload when a user clicks on the Cover position:
```
{
"id":0,"src":"domoticz","method":"Cover.GoToPosition","params":{"id":0,"pos": 100}
}
```

but Domoticz generates this command instead:
```
{
  "id:0,src:domoticz,method:Cover.GoToPosition,params:id:0,pos:  position": 100
}
```

**Comment by gizmocuz** [comment]
We do not support funky templates. Should also not be necessary as other hardware (zigbee/zwave) is working correctly without it
If possible have a look how they implement positions/covers/brightness and try to use the same method

**Comment by enesbcs** [comment]
> We do not support funky templates. Should also not be necessary as other hardware (zigbee/zwave) is working correctly without it If possible have a look how they implement positions/covers/brightness and try to use the same method

Unfortunately i do not know other methods to position a Gen2 Shelly Cover device through MQTT except the one i posted. 
In the meantime i have created a fix on the device side, which interprets the invalid JSON which Domoticz sends:
```
{
  "id:0,src:domoticz,method:Cover.GoToPosition,params:id:0,pos:  position": 100
}
```
https://github.com/enesbcs/shelly-script-examples/blob/main/shelly2p-domo-coverfix.js

Maybe @Mircho, @lpetrov or @kzyapkov has a better idea for MQTT integration.

**Comment by enesbcs** [comment]
I found another possibility for controlling a Gen2 cover in Docs:
https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/Cover#mqtt-control

topic:
`<topic_prefix>/command/cover:<id>`
payload:
`pos,number`

This structure is simpler, i think it may work with Domoticz.

**Comment by enesbcs** [comment]
> I found another possibility for controlling a Gen2 cover in Docs: https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/Cover#mqtt-control
> 
> topic: `<topic_prefix>/command/cover:<id>` payload: `pos,number`
> 
> This structure is simpler, i think it may work with Domoticz.

Still not good.

Config object ver2:

Topic:
homeassistant/cover/shellyplus2pm-ID-roller-pos-c/config
Payload:
`{"name": "shellyplus2pm-ID Roller Pos Control", "enabled_by_default": false, "cmd_t": "~command/cover:0", "pl_open": "open", "pl_cls": "close", "pl_stop": "stop", "stat_t": "~status/cover:0", "value_template": "{{ value_json.state }}","state_closing": "closing","state_opening": "opening","state_open": "open","state_stopped": "stopped","state_closed": "closed","pos_t": "~status/cover:0", "pos_tpl": "{{ value_json.current_pos }}","pos_open": 100, "pos_clsd": 0, "set_pos_t": "~command/cover:0","set_pos_tpl": "pos,", "uniq_id": "shellyplus2pm-ID-roller-pos-c", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "~": "shellyplus2pm-ID/"}`

When Domoticz cover position changed on GUI Domoticz sends the following command:

```
topic: ~command/cover:0
payload: {"pos,": 50}
```

Expected payload to set position:

```
topic: ~command/cover:0
payload: pos,50
```

**Comment by gizmocuz** [comment]
That won't work

what happens when you send

{ "current_pos": 50 }

or

{ "position": 50 }

or

{ "pos": 50 }

But I guess it doesn't work.... Why are they sending thate state in JSON and when setting a position it has to be plain text with a keyword?

And why current_pos and pos, and not just 'position' ?

I would vote for { "position": 50 }

Maybe you can send 'm an email? They might make a new firmware release 😎

I will see if I can support

`"set_pos_tpl": "pos, %d"`

**Comment by enesbcs** [comment]
> what happens when you send
> 
> { "current_pos": 50 }
> 
> or
> 
> { "position": 50 }
> 
> or
> 
> { "pos": 50 }
> 
> But I guess it doesn't work.... 

Sorry i havent got any Gen2 devices, except a single Shelly Plus 1, so i can not test ShellyPlus2PM dimmer mode.
But i can tell you, that ShellyPlus1 does not react any command, except the ones listed on the Shelly docs, so i think its 99% sure, that the above wont work.

> Why are they sending thate state in JSON and when setting a position it has to be plain text with a keyword? And why current_pos and pos, and not just 'position' ?
> 
> I would vote for { "position": 50 }
> 
> Maybe you can send 'm an email? They might make a new firmware release 😎

I tried to involve @Mircho, @lpetrov and @kzyapkov  to this discussion, but i failed.

The JSON reply in ~status/cover:0 is the original method (named 'RPC') which responds to the RPC command in the original config object in my first post
`"set_pos_tpl": "{\"id\":0,\"src\":\"domoticz\",\"method\":\"Cover.GoToPosition\",\"params\":{\"id\":0,\"pos\": {{ position }} }}"`

The plain text 'pos,50' method (named 'MQTT Control') appeared only in previous stable v0.14 firmware, i thought it may be easier to use, this is why i tried it. According the docs, the status/cover:0 will also advertise status changes made by 'pos,50' method.

> I will see if I can support
> 
> `"set_pos_tpl": "pos, %d"`

It will be nice to the endusers, as they currently have to add a local script to the dimmer device manually, to correct incoming JSON position commands from Domoticz. (fortunately Gen2 devices has the ability for local scripting)
If 'pos, %d' can be supported it will be 'plug&play' them.

**Comment by gizmocuz** [comment]
I wish the device sticked to JSON for both status and commands
Now it's a mix of JSON and plain text
(and one variable name ... position)

We now support the below template:

`"set_pos_tpl": "pos, %d"`

Is there anything we need to do or is all working correctly now (and without scripting) ?

**Comment by enesbcs** [comment]
> We now support the below template:
> 
> `"set_pos_tpl": "pos, %d"`
> 
> Is there anything we need to do or is all working correctly now (and without scripting) ?

Thank you, i've tested the modified config object against available status updates and seems that the command format now fits to Shelly docs using this %d method.
We can close this issue now.

**Comment by gizmocuz** [comment]
@enesbcs , In the latest beta version I am now ignoring the state_topic/stat_t when a position topic is configured in the config.
Everything 'should' still work... But I'm not able to verify this.
If possible is it possible to check this?

**Comment by enesbcs** [comment]
> @enesbcs , In the latest beta version I am now ignoring the state_topic/stat_t when a position topic is configured in the config. Everything 'should' still work... But I'm not able to verify this. If possible is it possible to check this?

If "stat_t" is ignored, position will not be updated in Domoticz when cover started by an external button. I do not have a cover with physical button, so i am unable to try it, but it will be a problem.

**Comment by gizmocuz** [comment]
@enesbcs , I think it's no problem as we do not handle the states at the moment

 "state_closing": "-1",
  "state_opening": "1",
  "state_stopped": "

There is maybe a problem for blinds that do not use the positioning .... but have not encountered them yes

Thanks for the feedback!
