### ISSUE TITLE
API/JSON call getversion spills information

### ISSUE THREAD

**Issue by koensch** [domoticz/domoticz#5713]
The JSON call 'getversion' does not require username/password. 

In my case (and maybe others too) i have domoticz exposed to the public internet via a 'reverse proxy'. I have experienced that the 'getversion' returns some data to anyone that knows the URL. As far as i know there is no way i can configure that this information is not spilled.

I realise that 'getversion' is also used by monitoring applications to check if a domoticz server is 'online'. For what i know, only a reply on the 'getversion' query satisfies the monitoring detection as 'live'.

I would like to suggest two possible solutions:
- change the 'getversion'  (and any other api call) to require authentification. Incase a unauthorized user issues a 'getversion'  query, domoticz responds not with a full message (as present), but only with a JSON response "Unauthorized".  This way a valid JSON transaction is completed, but no information is spilled to unautorized users. In case a valid username/password was passed, the existing response can be returned.
- create a json command 'ping' that always returns a "OK", possibly with a option to disable/enable a anonymous ping. Monitoring applications should migrate from 'getversion' to 'ping' in the future.

**Comment by gizmocuz** [comment]
Thanks for reporting.
I don't think it was of much harm to report a python version as you still need to access shell before doing anything with it.
The reason the version was reported was that (mobile) applications know which API calls to use.
In the past there was a big change in authentication, even just recently quite a few API calls where modified.
Let's see if we get some feedback about this.
