### ISSUE TITLE
Feature request on "Temp" devices

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5718]
Currently outside temperatures and inside temperatures are over 25 C degrees.
So my whole Temperature Tab with all the widgets are red or dark-red.
It would be nice if on the edit widget next to adjustment could be 2 fields with minimum and maximum temperature which set the point for the icon turn from green slowly to dark-red.
I saw in the source that there are 6 levels next to the ice.png
This way I can set the temperature device of my NAS and there hard-drives to some other values.
30 C degrees is for a hard-drive is really cool, so should be green.

**Comment by gizmocuz** [comment]
You mean the sunny red , not a timeout widget red?
Yes, this is just an icon status, and no this cannot be changed.
It would be to much configuring and the idea is to keep it simple
