### ISSUE TITLE
Connect to domoticz using internet not working with router and IP forwarding 

### ISSUE THREAD

**Issue by fscoelho** [domoticz/domoticz#572]
Dear all, 

I tried several times to connect to domoticz using IP forwarding in the  router from the internet and always fails, never reaches the port (8080) even i change the port in the service. Locally works.
I have other software using IP forwarding making  the same kind of configuration and there is no problem.

Where can be the problem ? what is the particularity of domoticz?

**Comment by gizmocuz** [comment]
Please use our forum
