### ISSUE TITLE
Change fan setting causes password pop-up instead of chooser

### ISSUE THREAD

**Issue by cgrijs** [domoticz/domoticz#5722]
I have a Westinghouse fan controlled via RFXtrx433. Controlling via dzVents works fine. When I want to change it via the 'Switches' tab, I get a 'Please enter Password:' pop-up, instead of the 'lo|med|hi' chooser that I expect. (N.B. the switch item is not 'protected')

Version: 2023.1 (build 15368)
Build Hash: 875d38981
Compile Date: 2023-06-21 07:39:53
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]
Active User: admin

**Comment by kiddigital** [comment]
Did you ask on the forum for support?

Open the Developers tools of your Browser (F12) and check under the 'network'-tab what is happening in the background.

Probably there is a network call to some/several endpoints and one or more return a 401 - Acces Denied.

Looks like some kind of authentication and/or authorization issue.

**Comment by gizmocuz** [comment]
I can replicate the issue. Same for my Itho ... going to have a look

Edit, seems after entering the password it displays the popup... now investigating why it threats it as a protected switch

**Comment by gizmocuz** [comment]
Not sure how this got broken, but fixed in beta #15369, thanks for reporting.

**Comment by cgrijs** [comment]
That looks a lot better, thanx!!
