### ISSUE TITLE
Osram RGB colors doesn't work Mqtt Auto Discovery 

### ISSUE THREAD

**Issue by blooesky** [domoticz/domoticz#5724]
Hi,

I have Osram Smart+ gardenpole mini RGBW zigbee device and Domoticz 2023.1(beta 13572)+sonoff dongle plus and i use it with Mqtt auto discovery client gateway with lan interface. 

The all colors works from zigbee2mqtt dashboard, but in domoticz works only WW(for Osram), if i will select any rgb color is not working **he changes to neutral color**, in logs all is fine no errors..but the color is not changed. I tested with ikea rgb bulb and all is fine.
 I tried with json command and the same result. 
What i seen in zigbee2mqtt dashboard is a difference for the color mode, Osram using HS and Ikea XY.
Looks like domoticz is sending wrong command to zigbee2mqtt for RGB colors.

Thank you!
![garden](https://github.com/domoticz/domoticz/assets/7414312/da0669ae-433c-4ff2-abdf-661c4e57af92)

**Comment by gizmocuz** [comment]
Thanks for reporting!

Is it possible to post the configuration topic + payload here so we can replicate this?

You can find this by using the application 'MQTT Explorer', have a look in your auto discovery topic --> light
Please pose the complete topic name (like ha/lights/0x94573753/light/config
as well as the json payload

**Comment by blooesky** [comment]
> Thanks for reporting!
> 
> Is it possible to post the configuration topic + payload here so we can replicate this?
> 
> You can find this by using the application 'MQTT Explorer', have a look in your auto discovery topic --> light Please pose the complete topic name (like ha/lights/0x94573753/light/config as well as the json payload

Hi, 

Action from Zigbee2mqtt dashboard

MQTT publish: topic 'zigbee2mqtt/0x7cb03eaa00ae8c9a', payload '{"brightness":254,"color":{"h":240,"hue":240,"s":100,"saturation":100,"x":0.1355,"y":0.0399},"color_mode":"xy","color_temp":370,"level_config":{"on_level":"previous"},"linkquality":21,"state":"OFF","update":{"installed_version":16909584,"latest_version":16909584,"state":"idle"},"update_available":false}'


Action from Domoticz

MQTT publish: topic 'zigbee2mqtt/0x7cb03eaa00ae8c9a', payload '{"brightness":254,"color":{"h":0.6653594970703125,"hue":0.6653594970703125,"s":1,"saturation":1,"x":0.3239,"y":0.3289},"color_mode":"hs","color_temp":169,"level_config":{"on_level":"previous"},"linkquality":21,"state":"ON","update":{"installed_version":16909584,"latest_version":16909584,"state":"idle"},"update_available":false}'

Let me know if what I sent you is correct!

**Comment by gizmocuz** [comment]
Thanks for this. But I also would like to have the 'config' object

Maybe it is under homeassistant/lights/0x7cb03eaa00ae8c9a/light/config

**Comment by blooesky** [comment]
> Thanks for this. But I also would like to have the 'config' object
> 
> Maybe it is under homeassistant/lights/0x7cb03eaa00ae8c9a/light/config

hi

Config object from homeassistant/lights/0x7cb03eaa00ae8c9a/light/config  : 

{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"brightness":true,"brightness_scale":254,"color_mode":true,"command_topic":"zigbee2mqtt/0x7cb03eaa00ae8c9a/set","device":{"identifiers":["zigbee2mqtt_0x7cb03eaa00ae8c9a"],"manufacturer":"OSRAM","model":"Smart+ mini gardenpole RGBW (AC0363900NJ)","name":"0x7cb03eaa00ae8c9a","sw_version":"V1.05.10"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"json_attributes_topic":"zigbee2mqtt/0x7cb03eaa00ae8c9a","max_mireds":370,"min_mireds":153,"name":"0x7cb03eaa00ae8c9a","schema":"json","state_topic":"zigbee2mqtt/0x7cb03eaa00ae8c9a","supported_color_modes":["hs","color_temp"],"unique_id":"0x7cb03eaa00ae8c9a_light_zigbee2mqtt"}

**Comment by gizmocuz** [comment]
Is it possible you could try beta 15385 (or higher)
Maybe all we missed is a multiply for Hue/Sat (360 and 100)

If that does not work, I will give the color_temp priority over HS

**Comment by blooesky** [comment]
> Is it possible you could try beta 15385 (or higher) Maybe all we missed is a multiply for Hue/Sat (360 and 100)
> 
> If that does not work, I will give the color_temp priority over HS

Yes it works. Thank you!

**Comment by blooesky** [comment]
![Screenshot_20230712_213125](https://github.com/domoticz/domoticz/assets/7414312/1dfcf753-f5f5-480b-8af6-c4403b7168c8)
Only this Rgb level switch  doesn t work, Everything else works perfectly

**Comment by gizmocuz** [comment]
Could you show the difference of setting the brightness with zigbee2mqtt and domoticz (mqtt details)

**Comment by blooesky** [comment]
Hi, i think this level switch is for temperature color or maybe it needs to be disabled because Everything else works.
For WW works, only in RGB in not working this level.

Color temperature of this light from zigbee2mqtt
{"brightness":254,"color":{"h":240,"hue":240,"s":100,"saturation":100,"x":0.1355,"y":0.0399},"color_mode":"xy","color_temp":370,"linkquality":0,"state":"ON","update":{"installed_version":16909584,"latest_version":16909584,"state":"idle"},"update_available":false}


Temp color(this level switch) from domoticz 
{"brightness":254,"color":{"h":1.1764705181121826,"hue":1.1764705181121826,"s":40,"saturation":40,"x":0.3871,"y":0.3252},"color_mode":"hs","color_temp":299,"linkquality":0,"state":"ON","update":{"installed_version":16909584,"latest_version":16909584,"state":"idle"},"update_available":false}

Let me know if you need more infos. Thanks

**Comment by gizmocuz** [comment]
This slider is for brightness

**Comment by gizmocuz** [comment]
Do you have a brightness slider/option in zigbee2mqtt? It should change this value

`"brightness":254`

**Comment by blooesky** [comment]
> Do you have a brightness slider/option in zigbee2mqtt? It should change this value
> 
> `"brightness":254`

Yes , 2 sliders...the one for brightness and another one for the color temperature

**Comment by gizmocuz** [comment]
Okey and if you change te brightness , what does it send?

**Comment by blooesky** [comment]
Now this level doesn't work

**Comment by gizmocuz** [comment]
Sorry this topic is already 1.5 months old.

If I understand correct, you are now able to control the RGB, but the brightness level does not work, is that correct?

Could you post the payload of MQTT when you set the brightness with Zigbee2MQTT to 50%, and the payload when you set it to 70% and 90%

Thanks!

**Comment by blooesky** [comment]
yes, I've been busy lately and couldn't test. Only level from the popup doesn't work, the other works. Rgb control works very well

**Comment by gizmocuz** [comment]
No worries... hope you can post the information from the question above

**Comment by blooesky** [comment]
in zigbee2mqtt max brightness is 253(like 100% in domoticz) we have:

MQTT publish: topic 'zigbee2mqtt/0x7cb03eaa00ae8c9a', payload '{"brightness":253,"color":{"h":193.18966674804688,"hue":193.18966674804688,"s":90.98039245605469,"saturation":90.98039245605469,"x":0.1729,"y":0.3044},"color_mode":"hs","color_temp":153,"last_seen":"2023-09-16T18:21:20+03:00","level_config":{"on_level":"previous"},"linkquality":40,"state":"ON","update":{"installed_version":16909584,"latest_version":16909584,"state":"idle"},"update_available":false}'

for 127 brightness(like 50%)

MQTT publish: topic 'zigbee2mqtt/0x7cb03eaa00ae8c9a', payload '{"brightness":127,"color":{"h":193.18966674804688,"hue":193.18966674804688,"s":90.98039245605469,"saturation":90.98039245605469,"x":0.1729,"y":0.3044},"color_mode":"hs","color_temp":153,"last_seen":"2023-09-16T18:28:47+03:00","level_config":{"on_level":"previous"},"linkquality":43,"state":"ON","update":{"installed_version":16909584,"latest_version":16909584,"state":"idle"},"update_available":false}'

for 181(like 70%)
MQTT publish: topic 'zigbee2mqtt/0x7cb03eaa00ae8c9a', payload '{"brightness":178,"color":{"h":193.18966674804688,"hue":193.18966674804688,"s":90.98039245605469,"saturation":90.98039245605469,"x":0.1729,"y":0.3044},"color_mode":"hs","color_temp":153,"last_seen":"2023-09-16T18:30:19+03:00","level_config":{"on_level":"previous"},"linkquality":40,"state":"ON","update":{"installed_version":16909584,"latest_version":16909584,"state":"idle"},"update_available":false}'

**Comment by gizmocuz** [comment]
@blooesky , thank you for this! Could you also post the payload/output from

zigbee2mqtt/0x7cb03eaa00ae8c9a/set

when you set the brightness?

**Comment by blooesky** [comment]
100%
{"brightness":254,"color":{"h":193.18966674804688,"hue":193.18966674804688,"s":90.98039245605469,"saturation":90.98039245605469,"x":0.1729,"y":0.3044},"color_mode":"hs","color_temp":153,"last_seen":"2023-10-02T20:39:14+03:00","level_config":{"on_level":"previous"},"linkquality":18,"state":"ON","update":{"installed_version":16909584,"latest_version":16909584,"state":"idle"},"update_available":false} 

50%
{"brightness":127,"color":{"h":193.18966674804688,"hue":193.18966674804688,"s":90.98039245605469,"saturation":90.98039245605469,"x":0.1729,"y":0.3044},"color_mode":"hs","color_temp":153,"last_seen":"2023-10-02T20:41:43+03:00","level_config":{"on_level":"previous"},"linkquality":18,"state":"ON","update":{"installed_version":16909584,"latest_version":16909584,"state":"idle"},"update_available":false}

**Comment by blooesky** [comment]
And this is the payload from the domoticz popup level(image 2 from the picture) when I change the brightness, the color also changes, becoming a neutral one, it does not keep the original color.

{"brightness":254,"color":{"h":1.2903213500976562,"hue":1.2903213500976562,"s":36.47058868408203,"saturation":36.47058868408203,"x":0.3795,"y":0.3258},"color_mode":"hs","color_temp":279,"last_seen":"2023-10-02T20:43:26+03:00","level_config":{"on_level":"previous"},"linkquality":18,"state":"ON","update":{"installed_version":16909584,"latest_version":16909584,"state":"idle"},"update_available":false}

![OSRAM](https://github.com/domoticz/domoticz/assets/7414312/4e1a7449-aaae-4d10-a765-966ebbabdb2f)

**Comment by gizmocuz** [comment]
Is it possible to try the latest beta version?

**Comment by blooesky** [comment]
same

**Comment by gizmocuz** [comment]
@blooesky , same? What do you mean with 'same' , did you try the latest beta?

**Comment by blooesky** [comment]
Hi,

i have beta 2023.2 build 15636.

The same problem because the color becoming a neutral, it does not keep the original color. Is not very important for me this level but I wanted you to know

**Comment by gizmocuz** [comment]
So when you select a red color, the light does not turn red?

**Comment by blooesky** [comment]
The colors works very well, but if i using the popup brightness (the image 2 above) the color becoming a neutral, for the widget brightness(image 1) also it works correctly. I will attach a video.

**Comment by gizmocuz** [comment]
Okey, just to be sure ... You select a color (like red), then adjust the brightness on the right, and the color becomes neutral (white) , the brightness is working, but only with a white color instead of the selected one

**Comment by blooesky** [comment]
something like that. I will be back with a video this evening

**Comment by blooesky** [comment]
Hi man, i tested now and all it is working. Thank you for your support!

**Comment by gizmocuz** [comment]
@blooesky ? Did you not use the latest beta version? What changed with a few days ago?
