### ISSUE TITLE
New switches not visible on Switches page

### ISSUE THREAD

**Issue by erkikoiv** [domoticz/domoticz#5728]
Hello,
I have an issue with my Domoticz (v 2023.1). For some time I cannot add any new switches. They are visible under Devices but not under Switches page. Tried adding virtual switch, the same. Any suggestions, what might be wrong and how to fix it?

**Comment by gizmocuz** [comment]
It could be you assigned specific devices for the User that you login with. (Setup->Users>Devices)

**Comment by erkikoiv** [comment]
No, nothing is selected. User is admin.

Kontakt gizmocuz ***@***.***>) kirjutas kuupäeval T, 4.
juuli 2023 kell 08:36:

**Comment by xbeaudouin** [comment]
I confirm I have aslo this issue... I have to add the new switch to admin rights....

**Comment by erkikoiv** [comment]
HI tried to add all switches, but no effect.

Kontakt Xavier Beaudouin ***@***.***>) kirjutas kuupäeval T,
4. juuli 2023 kell 16:44:

**Comment by gizmocuz** [comment]
No issues here.... 

First make sure you are on the latest beta version
Then clear your browser cache
From the hardware page, make sure a dummy hardware is enabled and add a switch
It should show up on the switches page

if not, go to setup->Users, check all your users and make sure there are no specific devices selected for them

**Comment by dterweij** [comment]
Hello, What happened with the Switches and Temperature pages? It does not show anything after a update. I only have the Dashboard showing  some blocks. I checked the new devices thing and removed the few selected items so it is none selected.
This is not a nice update, how do i get all the switches and temperature pages back ?

**Comment by gizmocuz** [comment]
@dterweij , please us our forum... And also check under 'Users' that you have not specified selected devices to be displayed only
Do you need to have selected devices?

**Comment by waltervl** [comment]
Closing this issue as it seems configuration and/or caching issues. Use the support forum for this.

**Comment by MarcVJ** [comment]
Hello, thank you, i had the same problem and this answer helped me :
"go to setup->Users, check all your users and make sure there are no specific devices selected for them"
The implicit rule "all devices are selected unless at least one device is selected" was not clear for me. 
The same rule applies for hardware devices, for example in "MQTT Client Gateway with LAN interface " configuration.
