### ISSUE TITLE
Unable to recover from missing netatmo weather station details

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#573]
I'm facing an issue where I'm losing data on the netatmo device.

For some reasons, the netatmo servers have an issue and the sensors data returned by the "getstationsdata" API call are empty, then domoticz displays "No Weather Station devices" in CNetatmo::ParseNetatmoGetResponse, and finally m_bPollWeatherData is set to false for the rest of the life of the process and the only solution is to restart the server.

I'm wondering if the solution is not to simply avoid setting m_bPollWeatherData to false and still continue to poll the netatmo API.
In case of error, we just avoid storing data points and that's it !

I can work in this issue

**Comment by gizmocuz** [comment]
I made a new commit
But you could also have set the hardware sensor timeout to 20 minutes, so it was restarted

**Comment by gizmocuz** [comment]
Thanks for your feedback!
