### ISSUE TITLE
Memory leak since build 15370,15371 or 15372

### ISSUE THREAD

**Issue by jgaalen** [domoticz/domoticz#5730]
Since I've upgraded domoticz from build 15369 to 15372 there is a clear memory leak. I've verified what other changes I've done but couldn't find one. To me it looks like there is a memory leak creeped into either beta build 15370, 15371 or 15372.

Perhaps others can verify this. 

I've added a screenshot to show the memory usage of version 15369 (and before that, memory was always stable.

![domoticz_memory_leak](https://github.com/domoticz/domoticz/assets/10229665/0e16ef60-9c29-4019-899f-ab776a5e88fa)

**Comment by kiddigital** [comment]
@jgaalen , what is the list of active hardware? Can you try to disable them one-by-one to see if it is one of the hardware modules or the core of domoticz?

**Comment by kiddigital** [comment]
@jgaalen , did you have a look at the changes between these versions? Check the [wiki](https://www.domoticz.com/wiki/Domoticz_versions_-_Commits) or the commits on Github.

I don't see anything there that might cause your issue? Did you run updates on the OS (which one?) as well?

**Comment by jgaalen** [comment]
> @jgaalen , did you have a look at the changes between these versions? Check the [wiki](https://www.domoticz.com/wiki/Domoticz_versions_-_Commits) or the commits on Github.
> 
> I don't see anything there that might cause your issue? Did you run updates on the OS (which one?) as well?

Yeah I've looked at the content of the changes (as far as I could match them with the builds) but none of the changes in between look like a candidate for a memory leak.

But still, I've done some tests and only changed the docker version. Quite obvious that any version up to 15369 is fine and starting from 15372 there show this increasing memory behaviour.

I have a list of 25 hardware items I use (I don't use evohome, but 2 commits were related to that). It's a bit weird what causes this. No one else sees this increasing memory pattern? Some background:

Ubuntu 22.04 OS, running docker container with manually added this to the Dockerfile:
```
FROM domoticz/domoticz:2023-beta.15372

RUN apt update && apt install -y apcupsd nodejs npm jq

RUN pip install --no-cache-dir --upgrade pip
RUN pip install pybotvac heospy chardet
RUN pip install requests==2.23.0 charset-normalizer==3.0.1
RUN npm i @tuyapi/cli -g
```

. 25 hardware devices as a couple which have heavy usage: deconz, p1, many python plugins, heishamon mqtt. I've disabled couple of some but didn't stopped the ever increase of committed memory.

![domoticz_memory_leak2](https://github.com/domoticz/domoticz/assets/10229665/25ccc9d5-afcb-4d50-bf89-5261e9bf5fd4)

**Comment by jgaalen** [comment]
Still a bit frustrated on what is going on. The problem is really there and it is in that docker version since domoticz/domoticz:2023-beta.15372

It's hard to believe it is related to the changed docker code when looking at what has changed. Perhaps something related in debian:bullseye-slim itself which could have been updated along the way?

**Comment by jgaalen** [comment]
I've made some effort on analysing the memory leak. I've done a couple of memory dumps and looked at the part of memory that increased the most. What I've found is that it looks like it leaks only values that are updated via a custom plugins. So I update every second via the P1 monitor, nothing in it. But I have a deconz plugin and a mqtt plugin which updates a lot of values every 5 seconds. All these 'strings' keep on piling up in the memory. Values that are not updated are nog kept in memory.

Is this helpful?

**Comment by kiddigital** [comment]
So if you disable the Python plugins, the memory leak is gone? (So we can be sure in which direction to look).

**Comment by pipiche38** [comment]
There is for sure some memory leak in the Python Framework.
Some improvement have been done alreday, but still. 
So on my side restart of domoticz every 24 hours

**Comment by gizmocuz** [comment]
Seems 'a' solution to this problem could be to use zigee2mqtt and the native MQTT-Auto Discovery implementation.
This way you do not need python for at least that part.

Another approach would be to use Visual Studio to compile/debug and use the memory profiler to see which functions are causing these memory losses/pikes.
(Under Linux, if you compile under debug mode, you could Valgrind for this)

**Comment by gizmocuz** [comment]
Also remember, there is also a thing under linux called memory cache ... this will get flushed when needed.

**Comment by jgaalen** [comment]
> Seems 'a' solution to this problem could be to use zigee2mqtt and the native MQTT-Auto Discovery implementation. This way you do not need python for at least that part.
> 
> Another approach would be to use Visual Studio to compile/debug and use the memory profiler to see which functions are causing these memory losses/pikes. (Under Linux, if you compile under debug mode, you could Valgrind for this)

This is not a solution, the Heishamon MQTT plugin is much more than simply updating the mqtt devices so this is not replaceable with the mqtt-auto discovery (I use that one as well for other mqtt devices).

It is not a problem with the python plugins itself. I see that EVERY plugin that does any update, leave it's data behind. It is since docker version domoticz/domoticz:2023-beta.15372
It doesn't necessary has to be related to the changed between 15369 and 15372,  but could also be a different debian/python behaviour.

I think the leak is somewhere behind this code: `Devices[Unit].Update(nValue, str(sValue))`
Because every time that is used, data is left behind in memory. 
If I grep a specific device on the dump like `strings domoticz_mem.dump | grep <deviceX>` and deviceX is a device that was updates just 3 times since the restart, I see that value appear 3 times. Some other devices that keeps being updates every poll action, it there every poll so hunderds of them piling up.

I can pause the plugins temporarily but many events are based on deconz do I don't want to pause it for too long, or else my house is crippled :)

**Comment by gizmocuz** [comment]
No idea what the Heishamon MQTT is or does, but I do know that if you are using Zigbee, Zigbee2MQTT together with MQTT-AD works perfect.

I searched the project for 'Devices[Unit].Update(nValue, str(sValue))' and 'Update(nValue, str(sValue))' but I could not find any line with this
Maybe it's a Python function that calls another function internally.
Are you able to make a small test plugin that calls this, lets say, 100 times every second?

With this I might be able to do some memory profiling

(Yep, I am a python dummy.... don't use it myself)

**Comment by jgaalen** [comment]
> No idea what the Heishamon MQTT is or does, but I do know that if you are using Zigbee, Zigbee2MQTT together with MQTT-AD works perfect.
> 
> I searched the project for 'Devices[Unit].Update(nValue, str(sValue))' and 'Update(nValue, str(sValue))' but I could not find any line with this Maybe it's a Python function that calls another function internally. Are you able to make a small test plugin that calls this, lets say, 100 times every second?
> 
> With this I might be able to do some memory profiling
> 
> (Yep, I am a python dummy.... don't use it myself)

Ok, I've created this simple memory-test python plugin and I was able to reproduce it:


```#!/usr/bin/env python
"""
Domoticz memory profiling test
"""
"""
<plugin key="memprofiling" name="Memory test" version="0.1" author="jgaalen">
    <params>
        <param field="Mode1" label="Interval" width="40px" required="true" default="1" />
        <param field="Mode2" label="Updates per interval" width="200px" required="true" default="100"/>
        <param field="Mode3" label="Device count" width="200px" required="true" default="100"/>
    </params>
</plugin>
"""

import Domoticz
import random

def onStart():
    Domoticz.Log("Domoticz Memory Tester")
    deviceCount = int(Parameters["Mode3"])

    if len(Devices) != deviceCount:
        for i in range(1, deviceCount+1):
            Domoticz.Device(Name=f'Device{i}', Unit=i, TypeName='Temperature', Used=1).Create()

    Domoticz.Heartbeat(int(Parameters["Mode1"]))

def onHeartbeat():
    deviceCount = int(Parameters["Mode3"])
    try:
        for _ in range(int(Parameters["Mode2"])):
            for i in range(1, deviceCount+1):
                Devices[i].Update(0, str(round(random.uniform(18.0, 25.0), 1)))
    except Exception as err:
        Domoticz.Error("Heartbeat error: " + str(err))```

**Comment by gizmocuz** [comment]
Thank you for the nice and quick python script!
Made a folder under the plugins folder and put it in a file plugin.py and restarted Domoticz

 It's running at the moment under visual studio (30 updates on 10 devices)
memory seems quite stable, except when I login to Domoticz itself it has some peaks

memory is now 12.1 MB, lets keep it running with some testing the upcoming days

I do have to say, when you have 300 devices being updated every second and you have a memory increase with 'a' certain python script that does that, pffff
I imagine that a python plugin that polls an extern website every 30 seconds and updates a device or two, won't cause any harm
While typing memory decreased to 11.9 MB .... few minutes later 12.0 MB

to be continued

If someone could also test this with valgrind or a similar profiler under Linux that would be great

Aldo we might find out is and where the problem is, we still need a fix

**Comment by jgaalen** [comment]
Then it is probably related to the docker version (so that debian or python inside the base container). I've ran a test with domoticz/domoticz:2023-beta.15372 image, and memory kept increasing, about 28MB/minute and never stops. This is about 45 bytes per update.
Tried domoticz/domoticz:2023-beta.15369 and the memory was stable at 30MB, never increasing, but still doing 10,000 updates per second.

Next thing I want to try is to build my own docker container with older debian containers.
... tried it, also very old debian bullseye slim version, no change, still exists. It's not easy to try an older domoticz version as the tgz file is not available (right?).

**Comment by jgaalen** [comment]
So tried running it in a docker container on a mac m1 (arm) and with the exact same docker stuff, it didn't happened! So got me thinking it was my ubuntu server which runs docker. Then installed a fresh VM (x86) with docker, ran the latest domoticz docker version, then it was reproducible again.

Then installed it on a ubuntu arm vm on AWS. Didn't reproduced it, memory was flat
Then installed it on a ubuntu x86 vm on AWS. I did reproduced it, memory kept increasing fast. Switch back to version 2023-beta.15369, and the memory leak didn't occurred.
Then installed domoticz native on the x86 ubuntu vm, with python3.10. Wasn't able to reproduce it.

So I narrowed it down to the x86 docker version.

**Comment by gizmocuz** [comment]
Thanks for testing. The docker is using the x86 binary version of Domoticz.
As it is not happing when installed natively, we can conclude it is not in Domoticz.

But could it be a 'cache' issue? Is it possible to run the test with docker and see if it actually is running out of memory, or that the system cleans the memory cache when needed and it never runs out of memory?

**Comment by jgaalen** [comment]
Interesting, so I've set a memory limit to 80 MB to the container. When running this plane domoticz container with the memory tester plugin, it quickly increases to 77 MB and then it doesn't increase and stays at about 77 MB. So indeed some cache. So doesn't look like a real memory leak which keeps allocating memory it cannot ditch and no risk (as far as I've tested) on a crashing domoticz due to OOM.

Although still weird that according to the graphs it actually looks like the memory of the domoticz process has this increasing allocated memory. 
As a work around I could limit the memory of the container to 512MB to avoid it keeps going on for forever (and screwing with the metrics), but for sure some behaviour has changed

**Comment by gizmocuz** [comment]
Yeah, we noticed (and mentioned) this years ago. It's a general behavior under Linux.
Maybe we have to mention this on our wiki.
One option is to not provide a memory graph for Unix users ... 😂😎
But the graphs you display here are from the docker container.

Glad it is sorted out, closing issue...

**Comment by jgaalen** [comment]
I know this topic is closed, but for me it is still open ;) I've limited the memory to 512MB to avoid it is ballooning and eats all the memory. It ran fine for a week at this peak mem, but ran into a OOM.

So I'm testing even further. I've tried a couple of things. 
- I've copied the domoticz binary from the 15372 docker version and overwritten it in the 15369 docker image. The memory problem is still there
- Copied the 15369 binary inside the 15372 docker image, problem is not there.

So looks like the memory issue is actually inside the binary and the debian image and related python is not the cause. Maybe when it compiled the 15369 version is used different/older cmake/boost/ubuntu/gcc versions ?

What also isn't really consistent, is that the binary is compiled with the latest ubuntu docker image, but the domoticz docker image is build on a debian bullseye slim variant.

I wonder if other linux x86_64 / docker users experiences the same memory issue that I have? Maybe this issue comes more to the surface on my end because I use a couple of python libraries with a large number of updates

**Comment by gizmocuz** [comment]
The reason for the dockers base image is the OpenSSL version but that’s totally unrelated to this image

**Comment by pipiche38** [comment]
Not using Docker and memory leaks shown with valgrind (with Legacy or Extended )

Issue reported in 

- Plugins::CDevice_refresh(Plugins::CDevice*) for Legacy
- Plugins::CUnitEx_refresh(Plugins::CUnitEx*)  for Extented

see https://github.com/domoticz/domoticz/issues/5881
