### ISSUE TITLE
Error Compiling Alfen Eve Charge

### ISSUE THREAD

**Issue by MadPatrick** [domoticz/domoticz#5732]
Hi

I'm getting the following error during compiling

[ 29%] Building CXX object CMakeFiles/domoticz.dir/hardware/AlfenEve.cpp.o In file included from /builddir/build/BUILD/domoticz-15384/hardware/AlfenEve.cpp:15: /builddir/build/BUILD/domoticz-15384/hardware/AlfenEve.cpp: In member function 'bool AlfenEve::DoLogin()': /builddir/build/BUILD/domoticz-15384/hardware/AlfenEve.cpp:218:27: error: 'CURLOPT_DEFAULT_PROTOCOL' was not declared in this scope; did you mean 'CURLOPT_REDIR_P                        ROTOCOLS'? 218 |  curl_easy_setopt(m_curl, CURLOPT_DEFAULT_PROTOCOL, "https"); |                           ^~~~~~~~~~~~~~~~~~~~~~~~ make[2]: *** [CMakeFiles/domoticz.dir/build.make:819: CMakeFiles/domoticz.dir/hardware/AlfenEve.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:238: CMakeFiles/domoticz.dir/all] Error 2 make: *** [Makefile:172: all] Error 2 error: Bad exit status from /var/tmp/rpm-tmp.e2lcdO (%build)

**Comment by gizmocuz** [comment]
Thank for reporting.

CURLOPT_DEFAULT_PROTOCOL was added in curl 7.45.0

But we do not need this option as we are providing the scheme ourselves (https)

Patch committed, if you update the source files it should work again

**Comment by MadPatrick** [comment]
Compiling was  now succesfull.
Thanks for the quick fix !

**Comment by PatrBal** [comment]
Hi, I am also getting an AlfenEve error when compiling release 2023.2
```
[ 32%] Building CXX object CMakeFiles/domoticz.dir/hardware/AlfenEve.cpp.o
/Applications/Domoticz/hardware/AlfenEve.cpp:301:6: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
        if (!res == CURLE_OK)
            ^    ~~
/Applications/Domoticz/hardware/AlfenEve.cpp:301:6: note: add parentheses after the '!' to evaluate the comparison first
        if (!res == CURLE_OK)
            ^
             (              )
/Applications/Domoticz/hardware/AlfenEve.cpp:301:6: note: add parentheses around left hand side expression to silence this warning
        if (!res == CURLE_OK)
            ^
            (   )
/Applications/Domoticz/hardware/AlfenEve.cpp:353:6: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
        if (!res == CURLE_OK)
            ^    ~~
/Applications/Domoticz/hardware/AlfenEve.cpp:353:6: note: add parentheses after the '!' to evaluate the comparison first
        if (!res == CURLE_OK)
            ^
             (              )
/Applications/Domoticz/hardware/AlfenEve.cpp:353:6: note: add parentheses around left hand side expression to silence this warning
        if (!res == CURLE_OK)
            ^
            (   )
/Applications/Domoticz/hardware/AlfenEve.cpp:1092:49: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                        curl_easy_setopt(m_curl, CURLOPT_POSTFIELDS, send_data);
                                                                     ^
2 warnings and 1 error generated.
make[2]: *** [CMakeFiles/domoticz.dir/hardware/AlfenEve.cpp.o] Error 1
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
make: *** [all] Error 2
```

Any idea?

**Comment by gizmocuz** [comment]
Yes, there is something wrong with this line, thanks for reporting. Unfortunately visual studio and my GCC did not noticed this
Still the code seems to work here
I will fix this today in the beta and master branch

**Comment by PatrBal** [comment]
Compilation now successful. Thanks!
