### ISSUE TITLE
No more info from enphase Build 15396

### ISSUE THREAD

**Issue by arjanvanleent** [domoticz/domoticz#5733]
After the update to build 15396 the data is not more collected from the enphase
I only see in the log : Error: Enphase: Error getting http data! (info)
Have tried to set Site ID but without result.

Note I'm still using version 5.0.62.
Don't see any software update on my Gateway

![image](https://github.com/domoticz/domoticz/assets/17556892/6d093c38-370b-4f22-bf37-fb073d3d6d17)

**Comment by gizmocuz** [comment]
SiteId and controlling the power generation only works in 7.x
Don’t use that
Or upgrade to 7?

**Comment by arjanvanleent** [comment]
If I don't setup the siteID I get the same error and no info from the gateway
I can't update to version 7 don't see any option to do that

![image](https://github.com/domoticz/domoticz/assets/17556892/fe77ef83-1f81-4206-aae4-2846050d6024)
![image](https://github.com/domoticz/domoticz/assets/17556892/d83f5ced-b7b9-46b0-8174-f2ad93084fd3)

**Comment by gizmocuz** [comment]
You can ask your installer or use the toolkit application or else Enphase 
What was the last version that was working (domoticz)
Strange you can’t get the info data for the version and serial number
Could you disable the hardware, go to the user variables and delete the one with the token and start the hardware again?

**Comment by arjanvanleent** [comment]
The last working version was from 10 july so the commits of yesterday works fine

**Comment by arjanvanleent** [comment]
Did get a new token but no data

**Comment by gizmocuz** [comment]
Maybe because I changed all calls to https …. Would not expect that this could be a problem

**Comment by arjanvanleent** [comment]
this is not working
https://envoy.local/api/v1/production/inverters
Just http give good results

**Comment by gizmocuz** [comment]
Thank you for testing, and yep, I expected this....
Could you try beta 15397 (or higher)
I left all other calls HTTPS, for example

`https://{ip}/production.json?details=1`

The reason for this is that inside the code, for old firmwares (V5 like yours) to het the inverter details, this was also done via https, so I assume everything else should support https

But.... I could be wrong, and I can easily change this back for V5 firmwares

I just updated mine this morning to D7.6.172 this morning via the install tookit application on my mobile.
The process was a bit vague as it did not work on my tabled.
Process it as follows: Stay connected to the internet first, then go to settings, there it would download the latest firmware, then when done, connect to the Envoy AP. It would now send the new firmware to the Envoy and it would update the firmware. Whole process took about 20 minutes.

Hope it works again!

**Comment by arjanvanleent** [comment]
https://{ip}/production.json?details=1 this need also be http just tested it

**Comment by gizmocuz** [comment]
Thank you for testing.

New beta (15399)

But how about this call:

`https://envoy:{last six digest of the gateway serial}@{ip}/api/v1/production/inverters`

`https://envoy:123456@127.0.0.1/api/v1/production/inverters`

This function is the same for quite a long time and uses the https scheme

**Comment by arjanvanleent** [comment]
Alle https calls are not working tested all call possible
https://gathering.tweakers.net/forum/list_messages/2075922

The only way to get the inverter data is if I use:
DATA=`wget --user installer --password ******* -q -O - $enphase_IP/api/v1/production/inverters`

BTW verion 5.x don't use the serial number to get data only the installer password
Is also in the post on Tweaker

btw tha last build gives: 2023-07-12 08:31:03.733 Error: Enphase: Error getting http data! (invalid token!)

**Comment by gizmocuz** [comment]
so this is not working

https://envoy:123456@127.0.0.1/api/v1/production/inverters

but this is

https://installer:123456@127.0.0.1/api/v1/production/inverters

or

https://installer:password@127.0.0.1/api/v1/production/inverters

Anyway, with the latest beta 15399 all is working again? As it now used http calls for V5 firmware and https for V7 (except the info call, that is HTTP for both)

**Comment by gizmocuz** [comment]
Found it (token issue), hold on... building a new beta (15400) should not take long

**Comment by arjanvanleent** [comment]
http://installer:password@127.0.0.1/api/v1/production/inverters only this 1 is working

**Comment by arjanvanleent** [comment]
2023-07-12 08:42:17.060 Error: Enphase: Invalid data received! (inverter details)

This is with build 15400

**Comment by gizmocuz** [comment]
The one hacked this into the Enphase code was using V5.
First it tried with envoy:serial6 and then installer... 
I changed this to using the installer:password only

New beta available (15401)

Did you every had inverter details before with the Enphase hardware in Domoticz?

So now we issue

szURL = "https://installer:" + m_szInstallerPassword + "@" + m_szIPAddress + "/api/v1/production/inverters";

Normal production details are working correctly?

**Comment by arjanvanleent** [comment]
In build 15401 I still get : Enphase: Invalid data received! (inverter details)
The https is still the problem this need to be http

Production data is oke now

Inverter data:
![image](https://github.com/domoticz/domoticz/assets/17556892/e0378ebd-78c5-4504-8d7f-58f53ff55f73)

**Comment by gizmocuz** [comment]
Ahhh missed the https in this call.. new beta is building... and done (15402)

When all this is working you can now safely update to the V7 firmware 🤣😂

**Comment by arjanvanleent** [comment]
Yep everything is working fine now THANKS
Yesterday I send my installer an e-mail for the update because I have no luck with updating the gateway

**Comment by gizmocuz** [comment]
Great all is working again for V5! Thanks for the help! Yeah there are a few ways, one is to register yourself as a installer (with another email), and in enlighten (with your normal account) add the email of the second installer (your other email)
The you are installer
Or as mentioned above use the installer toolkit application mentioned above (press the AP button the envoy, connect to it with your mobile, password is last 6 digits of your envoy serial number)
Closing this issue 😎👍
