### ISSUE TITLE
Enphase : Problem with site ID parameter entered in latest beta

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#5736]
Hello, 

in build 15403, I have just added the site ID in the Enphase plugin and now I have this essor message , only when adding the Site ID :

> Error : Error getting http data! (check_jwt)
> Error getting http data! (power)

what is the site ID needed for exactly ?
is it useful in V7 firmware ?

thank you

**Comment by gizmocuz** [comment]
What did you enter as Site ID? It is not the number, it is the name of your site as displayed in Enlighten
You also have to use a username/password with Installer rights

If you use the SiteID (Wiki will get updated soon by Walter (thanks again!!)), you get a switch that enables you to turn on/off production.
For example when your electricity company charges you -60 cent, you can disable production
(Do note that it could take a few minutes before this is taken into account as there will be send a message to each inverter to tell it to stop producing)

**Comment by rezzalex** [comment]
OK, thank you for the precisions.

I don't think I will need this new feature, because my electrical compagny prices are not changing over time and because I have batteries. but thanks a lot anyway.

Just need to have the installer ID now, probably it will be precised in the Wiki ?

**Comment by gizmocuz** [comment]
Yep and in the Gui as well
