### ISSUE TITLE
[Hardware: P1 Smart meter USB] default rate limit

### ISSUE THREAD

**Issue by H4nsie** [domoticz/domoticz#5738]
hardware/P1MeterSerial.h

The default rate limit (amount of meter updates) is not set. This causes 700+ sensor updates a minute, which chokes the MQTT message bus (my ESP-sensors, listening on the MQTT where reconnecting every 20s because the TCP windows were full). And the Domoticz process used 15% - 20% cpu time on my Raspberry 4.

Changing the rate limit to 5 secs, solved all. No more reconnecting ESP's and CPU usage for Domoticz is now 2% - 6%.

I think it will help a lot of users by adding a default value instead of null.

**Comment by gizmocuz** [comment]
I will rewrite the code and make it like this:

- when no rate limit is specified (or 0), it will use a default rate limit of 5 seconds
- when the hardware is initially selected from the dropdown, a default of 5 seconds is filled in as rate limit

Regarding your ESP devices, not sure what you programmed them to do, but you could have a look at implementing the MQTT Auto Discovery protocol (or even better use ESPHome to program the ESP's as it supports MQTT-AD)
This way the MQTT traffic will be minimal... and you could also debug/update your sensors over the air

Above issue is solved when using beta 15415
