### ISSUE TITLE
libssl1.1

### ISSUE THREAD

**Issue by Dylantje** [domoticz/domoticz#5747]
Hope there is a option.. for install libssl1.1

Drive me cray.

I run: Odroid N2 with Armbian.

___ _ _ _ _ _ ____
/ _ \ __| |_ __ ___ (_) __| | | \ | |___ \
| | | |/ _` | '__/ _ \| |/ _` | | \| | __) |
| |_| | (_| | | | (_) | | (_| | | |\ |/ __/
\___/ \__,_|_| \___/|_|\__,_| |_| \_|_____|
Welcome to Armbian 23.05.1 Bookworm with Linux 6.1.30-meson64

System load: 2% Up time: 31 min
Memory usage: 9% of 3.69G IP: 192.168.5.70
CPU temp: 34°C Usage of /: 9% of 57G
RX today: 499.3 MiB
For Domoticz, in need, libssl1.1

Still get an error when run:

pi@Domoticz:~$ cd domoticz
pi@Domoticz:~/domoticz$ ./domoticz
./domoticz: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
pi@Domoticz:~/domoticz$
Where i google and try to find solutions.. No option to install libssl1.1 on my ondroid. [ also not with jammy ]
I find here some solutions, only they are not working,
https://github.com/domoticz/domoticz/issues/5233
https://www.domoticz.com/forum/viewtopic.php?t=40008

No where a solution? Find something that i need to run Domoticz in docker,.... after more then 10 years running on armbian..:-(

Hope there is a other solution.

Help please......

THANKS!!!

**Comment by gizmocuz** [comment]
Use the docker (compose) version

**Comment by Dylantje** [comment]
please is this the only solution?
I do not understand anything about docker. In the wiki there is not a lot to find to run the whole set..domoticz, z2m,grafana, influx etc


Please make a notifaction in the install wiki..

**Comment by gizmocuz** [comment]
Time to spend an hour on this I would say

Installing docker compose is extreme easy, specially when you can get armbian installed

Step by step instructions are here

https://www.domoticz.com/wiki/Docker

I suggest starting with domoticz and later look at using grafana with docker compose

Another option is to use a armbian version that does work with domoticz?

Using armbian myself

**Comment by gizmocuz** [comment]
You can also compile domoticz yourself on your system
(There is also a wiki page for this)

No need to create two issues about this

**Comment by Dylantje** [comment]
mmm i did try last noght :-) .. Only where and how do i start domoticz in docker, that part i am al stuck...

Is there in the future no support of armbian and Domoticz?

**Comment by Dylantje** [comment]
> You can also compile domoticz yourself on your system (There is also a wiki page for this)
> 
> No need to create two issues about this

Compile is also not working i tryed..

**Comment by gizmocuz** [comment]
Our arm build systems run armbian, so yes it is working

what error did you get? Created a swap file, read the wiki very close

docker compose works with a folder, in this folder you create a file with the name docker-compose.yml and configure your service in it

A tutorial can be found here

https://riptutorial.com/docker-compose

Start a docker with

docker compose up

Or add -d to run it in the background

Stop with

docker compose stop

Quit easy right?
