### ISSUE TITLE
Domoticz 2023.2 - affects existing switches after update onto 2023.2

### ISSUE THREAD

**Issue by pawol** [domoticz/domoticz#5756]
Domoticz 2023.2 - affects existing switches after update onto 2023.2

- On 2023.1 stable everything is configured and working well
- On 2023.2 stable some switches has changed functionality and description
- Adding new virtual switches does not work. New switch is visible in the "devices" tab with new idx but that switch is not visible on "switches" tab
- web browser cashe clearing does not help
- restored 2023.1 works again

**Comment by gizmocuz** [comment]
Can you please describe more? Some … changed … and description?? And yes, 100% sure adding a switch via dummy hardware works 
You probably have to go to your user settings and check if you selected specific devices for this user so others won’t show up
We have a forum for these questions

**Comment by pawol** [comment]
Nothing changed, nothing new, Just stable 2023.1 working since the beginning of 2023. The update onto 2023.2 was performed today by GUI and via cli also and every time I get damaged 2023.2 at the end. Like I said simple virtual switch adding does not work. The switch is on setup/devices list but that new switch is not available on main switches tab. Also previosly existing and working switches disappeared. I saw this behaviour 1 month ago on some beta. This time it is on stable release. So, I am back on 2023.1 because 2023.2 is unusable in this form for me. Luck for me I had the backup of domoticz folder.

**Comment by gizmocuz** [comment]
2023.3 is not released yet
One month ago was a perfect opportunity to notify us
Anyway did you go to the user settings and checked if you selected any devices ?

**Comment by pawol** [comment]
My bad. Number is corrected now. we are talking about previous and current stable release 2023.1 and 2023.2

**Comment by pawol** [comment]
I see that some devices are not joined to my account but it worked before the latest update. I shall stry to join ones

**Comment by gizmocuz** [comment]
Ore remove them from your user settings
This will also solve your virtual switch issue
This has been mentioned before on GitHub and the forum
Please feel free to ask questions on our forum
Like to keep these issues for developers

**Comment by pawol** [comment]
Ok. now switches are available in the main switches tab. But in the room plans I see mixed/messed switches. In domoticz mobile app I see in "plans" some switches not configured at all in that plan (I look by webui). I think that same idx for scenes and switches can be a problem eg idx 5 for the scene and for the switch.

**Comment by pawol** [comment]
the situation on 2023.2
yellowed devices as we see should not be in the plan "rolety"

We see also doubled "roleta lewa (salon)"  and "roleta prawa (salon)"   !!!!!

![Capture](https://github.com/domoticz/domoticz/assets/13277626/870c8f9a-38cb-4614-84b9-ab69cde86dde)
![Capture1](https://github.com/domoticz/domoticz/assets/13277626/319a68b3-63d7-453f-9a59-200a50b0d34f)


yellowed devices as we see should not be in the plan "rolety"

**Comment by pawol** [comment]
On 2023.1 it works ok. 

![Capture2](https://github.com/domoticz/domoticz/assets/13277626/66581d03-60bb-4c09-b987-458f3a214835)
![Capture3](https://github.com/domoticz/domoticz/assets/13277626/78c5ed94-f850-461f-9cdd-9dc50096ff63)
