### ISSUE TITLE
After recent update 80% of my devices are gone from the Dashboard and floor plans

### ISSUE THREAD

**Issue by Jvsjvs** [domoticz/domoticz#5757]
Just today I did the update as it was announced by the Domoticz application. After the update 80% of my devices (out of the approximately 250 devices) are gone in the Dashboard and in the switches tab, temperature tab, weather tab and utility tab. Note that on every tab some devices have remained present.

Domoticz is running on a Raspberry Pi

If I click on changing the floor plan it also shows a red circle with an exclamation mark:
![image](https://github.com/domoticz/domoticz/assets/5230522/7b90a261-4258-4287-98e3-2a20ffaf9304)

If I look in the room plans then all the devices are listed their (but do not show up on the floor plans).

If I try to add devices to the floor plan then the drop down box marked with plan is empty:
![image](https://github.com/domoticz/domoticz/assets/5230522/33589bb0-591e-471e-bbd2-42eb981a7924)

So I can't put back my devices now, please help.

I guess that the upgrade made an inconsistent change in my database (I did make a backup).

Restoring a backup (from just before the update) does not fix the problem.

**Comment by kiddigital** [comment]
From which version did you upgrade?

Please check the 'allowed' devices for the user you login with.

If all devices are allowed for that user, make sure no single device is selected.

**Comment by Jvsjvs** [comment]
Hi, Thanks for helping. 

I have upgraded from the previous stable version, I was up-to-date.What do you mean with: “allowed devices”? I only have one user account and all devices in the past were created by this single user. All the devices are listed when I click on Setup and then Devices. I can’t select any of them in the floor / room plans though. Does that give you some background to see what could go wrong? 

Thanks, John.

**Comment by kiddigital** [comment]
@Jvsjvs , did you check the [forum](https://www.domoticz.com/forum/viewtopic.php?p=302817) ?

**Comment by pawol** [comment]
go to user settings and add all switches (or remove all of them)

**Comment by Jvsjvs** [comment]
I used: 
-->Setup --> Users and then clicking on the small button: “Devices” allowed me to again enable the missing devices. 

Thanks.

**Comment by Jvsjvs** [comment]
Setup -> Users and then clicking on the small button: “Devices” allowed me to again enable the missing devices. Thanks.  Sent from Mail for Windows From: KidDigitalSent: Monday, 24 July 2023 19:10To: domoticz/domoticzCc: Jvsjvs; MentionSubject: Re: [domoticz/domoticz] After recent update 80% of my devices are gone from the Dashboard and floor plans (Issue ***@***.*** , did you check the forum ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
