### ISSUE TITLE
mess/difference between room plans on 2023.2 stable

### ISSUE THREAD

**Issue by pawol** [domoticz/domoticz#5758]
the situation on 2023.2
yellowed devices as we see should not be in the plan "rolety"

We see also doubled "roleta lewa (salon)" and "roleta prawa (salon)" !!!!!

![Capture](https://github.com/domoticz/domoticz/assets/13277626/c6227e01-ff0f-4f62-8ac1-5625e52b0ba0)
![Capture1](https://github.com/domoticz/domoticz/assets/13277626/8d49bed9-7f41-4c6a-8a0f-63e78da6651e)

**Comment by pawol** [comment]
On 2023.1 it works ok.
![Capture2](https://github.com/domoticz/domoticz/assets/13277626/cae35dca-a28f-4ce3-9245-2590151697cb)
![Capture3](https://github.com/domoticz/domoticz/assets/13277626/63a2ab30-50bc-4133-a14a-2b7ae304b9ff)

**Comment by gizmocuz** [comment]
Did you already switched between all and this roomplan?

Did you specify devices for this user? See the user setup

**Comment by pawol** [comment]
Tried with switches in the user settings added and removed. Nothing helps.

**Comment by pawol** [comment]
unwanted devices I see in the plan in android app also

**Comment by gizmocuz** [comment]
Is it possible you can send me a database backup on our slack channel and mention this GitHub issue?

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

**Comment by pawol** [comment]
.db sent as you requested

**Comment by gizmocuz** [comment]
I replied on slack, let's continue the discussion there until it's clear/solved

**Comment by pawol** [comment]
The issue was probably made by web browser issue
