### ISSUE TITLE
Events API fallback is missing

### ISSUE THREAD

**Issue by user8446** [domoticz/domoticz#5759]
Hi @kiddigital I noticed that with the new API calls that for some reason the Events type does not have a fallback like other calls and errors with:

`2023-07-23 09:55:40.183 Status: [WebServer] Deprecated RType (events) for API request. Call ignored, please use correct API Command!`

Thank you

**Comment by kiddigital** [comment]
@user8446 , that is correct.

As the 'type=events' call also uses the 'param=...' for its additional parameters, the structure had to change for this particular call.

It is now `type=command&param=events&evparam=<someeventparam>`. Wasn't as simple fallback as the others. Hence it is unfortunately not backwards compatible.

**Comment by user8446** [comment]
Thank you for the explanation and understand it's a can't fix. It's unfortunate though since not everyone will upgrade at the exact same time so it's a breaking change.

**Comment by pizzulicchio** [comment]
Ok but.. Let me understand better... I'm using Android Domoticz payed app, and it's no more possible to enable/disable events from the app???

**Comment by user8446** [comment]
Not yet if you upgraded to the latest Domoticz v2023.2 stable which has the breaking change that causes this. You can stay on v2023.1 in the meantime if the events toggle is an important feature for you.
