### ISSUE TITLE
EcoDevice - Retrieve data from Base Plan also

### ISSUE THREAD

**Issue by spawnrider** [domoticz/domoticz#576]
Hi,

I having an Basic (and not Peak/Off-Peak hours) subscription. 
Data from the Ecodevice must be retrieve from Base index as you can see in this sample from my EcoDevice API : 

```
{
product: "Eco-devices",
T1_PTEC: "TH..",
T1_PAPP: 345,
T1_BASE: 3195030,
T2_PTEC: "----",
T2_PAPP: 0,
T2_BASE: 0,
INDEX_C1: 0,
INDEX_C2: 0
}
```

**Comment by gizmocuz** [comment]
Great!, can you make a pull request with the needed patches ?

**Comment by gizmocuz** [comment]
closing topic, no reply

**Comment by DebugBill** [comment]
To SpawnRider

It should work not, as of Beta V3.6765

**Comment by spawnrider** [comment]
Thanks a lot, I will try it. 
For now, I use Node-RED in order to rewrite the output of my EcoDevice API call :)
