### ISSUE TITLE
(fe80::6:5605:b4d9:dfe9%eth0) is not a valid Ipv4 or IPv6 address!

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#5760]
> 2023-07-24 18:55:54.056 Status: [web:8080] Given host (fe80::6:5605:b4d9:dfe9%eth0) is not a valid Ipv4 or IPv6 address! Unable to check if in Trusted Network!

As described in the forum
https://www.domoticz.com/forum/viewtopic.php?t=40576

**Comment by gizmocuz** [comment]
What’s with the %eth0 part?

**Comment by kiddigital** [comment]
Looking at some documentation ([here](https://en.wikipedia.org/wiki/IPv6_address#zone_index) and [here](https://en.wikipedia.org/wiki/Link-local_address#IPv6)), that seems to be legit. In link-local IPv6 interfaces (fe80::), machines with multiple network interface could have the same IPv6 link-local address for all these interface and the '%\<interface\>' is added to indicate the interface used for the communication.

So I am preparing a small PR that strips the '%\<interface\>' part if present during checking of valid addresses.

**Comment by gizmocuz** [comment]
I see… so why not enter the ip adres only?

**Comment by xbeaudouin** [comment]
On IPv6 link local addresses are bound to interfaces names... you make have several link local addresses with same IP but with %en0 / %eth0 whatever...

**Comment by kiddigital** [comment]
> I see… so why not enter the ip adres only?

This is done on the sender-side by the OS itself and send as part of the TCP/IP packets and therefor received automagically by the receiving party, domoticz in this case. Not something the user has any involvement in (other than having a machine with multiple network interfaces ;) )

We just have to be able to handle it nicely, hence the PR :)
