### ISSUE TITLE
[BUG] Current v2023.2 stable broken on Windows

### ISSUE THREAD

**Issue by user8446** [domoticz/domoticz#5765]
Hi,

The current v2023.2 stable (v2023.2.15453) build on https://www.domoticz.com/downloads/ is broken and errors with:

`The code execution cannot proceed because libcrypto-3.dll was not
found. Reinstalling the program may fix the problem.`

`The code execution cannot proceed because libssl-3.dll was not
found. Reinstalling the program may fix the problem.`

Users are downgrading or switching to beta builds - see: https://www.domoticz.com/forum/viewtopic.php?t=40563

FYI I did try adding those libraries manually but it didn't work.

**Comment by gizmocuz** [comment]
Created and uploaded a new windows stable
Should solve the problem

**Comment by gizmocuz** [comment]
New stable uploaded just now to fix json dll error
