### ISSUE TITLE
Unable to save large dzVents scripts

### ISSUE THREAD

**Issue by didi31** [domoticz/domoticz#5767]
Hi
All my scripts with more than about 120 lines cannot be saved any more with the version 2023.2 build 15474.

I have script, that can be saved, which begin like below .

```
local macAdress = '00:aa:00:11:00:00'   -- Adresse MAC de ma station météo
local modExtIdx = 111 -- Index module extérieur
local nivSonIdx = 112 -- Index Niveau sonore du module intérieur
local pilesModExtIdx = 113 -- Index niveau batterie du module extérieur
local qualiteIdx = 114 -- Index Qualité de l'air du module intérieur
local modIntIdx = 115 -- Index module intérieur

-- https://dev.netatmo.com/apidocumentation/weather#getstationsdata

return {
    active = true,
	logging = {
		marker = 'Netatmo maMétéo V1.0'
	},
	on = {
		timer = { 'every 1 minutes' },	
		httpResponses = { 'maMeteoNetatmo' }
	},
	data = {
	    dist = { initial = 0 },
	    message = { initial = "" }
	    },
	  ...
```
if I add the following lines for the logging section, it cannot be saved any more.
```
  -- level	 =   domoticz.LOG_DEBUG, -- Seulement un niveau peut être actif; commenter les autres
  -- level	=   domoticz.LOG_INFO, 
  -- level	=   domoticz.LOG_ERROR,											
  -- level	=   domoticz.LOG_DEBUG,
  -- level	=   domoticz.LOG_MODULE_EXEC_INFO,

```
I though that it depend on the number of character of the script: 7181 is ok whlist 7182 is KO
but a script with 10000 characters with comments only can be saved...

[script KO.txt](https://github.com/domoticz/domoticz/files/12228839/script.KO.txt)

[script OK.txt](https://github.com/domoticz/domoticz/files/12228848/script.OK.txt)

**Comment by didi31** [comment]
I found the reason!
My raspberry used wifi and I plugged the RJ45 AT the same Time.
The raspberry has than 2 IP.
If I access to domoticz via the wifi IP or via reverse proxi, I have this limitation. If I use the other IP, I can save normally.

**Comment by SargonofAssyria** [comment]
The fact that your raspberry has 2 ip addresses should not be a problem as long as the metric of the 2 interfaces are different.
Look at the output of "ip route". At the end of every interface line there should be a different metric number.

**Comment by martin-g-it** [comment]
I have the same and noticed it has something todo with the way you access the Domoticz UI
- Via direct IP address, no issues occur while saving the script (mine worked until 140 lines or so)
- Via (nginx) Proxy server, the script update does not get saved and in the Domoticz log a line appears:

`Status: ::ffff:<ip of Proxy host> -> handle abandoned timeout (status=4)`

**Comment by SargonofAssyria** [comment]
In case of nginx you should 'bind' your proxy (by a listen directive) to one of the interfaces (eth0 or wlan0)

**Comment by lwalbert** [comment]
If you use Nginx reverse proxy, You'll have to increase the setting:` large_client_header_buffers 2 8k;` in Nginx.conf
In my case 8k was enough (previously used 4k), you might need more depending of the size of your script.
http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers

After changing the setting, remember to restart the Nginx service

**Comment by martin-g-it** [comment]
>In my case 8k was enough (previously used 4k), 

Thanks! 8k appears to be the default... I put 32k to be sure and now it works again! Kind of strange though that this issue pops up after the upgrade (never had this issue earlier and I'm using large scripts..)

**Comment by didi31** [comment]
Do you know how to do that on a Synology NAS?

**Comment by BabaIsYou** [comment]
Did you try that post ? https://community.synology.com/enu/forum/1/post/129245

**Comment by didi31** [comment]
I saw it but I don't know what to write inside a file...
I created a conf file with this parameter only but it generate an error.
In fact, I don't know where to write it.
An example should be welcome.

**Comment by lwalbert** [comment]
Check if you can locate the parameter inside one of these files:
/usr/syno/share/nginx/WWWService.mustache
/usr/syno/share/nginx/nginx.mustache
/volume1/@appstore/WebStation/misc/nginx_default_server.mustache
Edit the setting there with **sudo** rights using your favourite editor vi, pico etc. like this:
`sudo pico /usr/syno/share/nginx/WWWService.mustache`

example part of the nginx configuration file where you should find the parameter:
```
http {
    charset                utf-8;
    sendfile               on;
    tcp_nopush             on;
    tcp_nodelay            on;
    server_tokens          off;
    types_hash_max_size    2048;
    types_hash_bucket_size 64;
    client_body_buffer_size  4k;
    client_header_buffer_size 4k;
    large_client_header_buffers 2 8k;
    client_max_body_size 2M;
}
```
Adjust the setting and save.
test configuration with `sudo nginx -t`
Restart nginx service

**Comment by didi31** [comment]
@lwalbert 
The parameter is not in these files 😔
I will still use the ip address...
Maybe the developers will find how they have introduced that.

**Comment by BabaIsYou** [comment]
Do you mean that you don’t have any
```
http {
}
```

section in any of these files where you can try to put this parameter ?

**Comment by martin-g-it** [comment]
> The parameter is not in these files 😔

Same here, but you can add it anyways (don't forget to put ; at the end)

Ps; I had to set it to 64k for my largest script

**Comment by didi31** [comment]
Is there a file where it will not be overwrite when the service will restart or update ?

**Comment by Krakinou** [comment]
I have the same issue.
Increasing the large_client_header_buffers settings did not solve the issue.
I have following issue in firefox:
````
Un service worker a communiqué un objet « promise » à FetchEvent.respondWith() qui a été rejeté avec la raison « TypeError: NetworkError when attempting to fetch resource. ».
````
And 
````
TypeError: a is undefined
    F https://mydomain/domoticz/js/i18next-1.8.0.min.js:5
    E https://mydomain/domoticz/js/i18next-1.8.0.min.js:5
    B https://mydomain/domoticz/js/i18next-1.8.0.min.js:5
    alert https://mydomain/domoticz/app/app.js:160
    Angular 13
    jQuery 2
 Possibly unhandled rejection: {}
````

**Comment by lwalbert** [comment]
Hi @gizmocuz,
could you please have a look into this modification  https://github.com/domoticz/domoticz/commit/c91461ca002d8c0d1b5f9b5c5808553e40e57cf2 "Corrected create/update event" 
When updating dzvent scripts trough  reverse proxy server, the server returns  "414 URI too long"

Had a look in to the modified code, and it looks like the request header method has changed from "POST" to "GET" 
causing Nginx to deny the request.

**Comment by MuadDibVV** [comment]
I confirm : Ko through native synology reverse proxy, but ok with direct IP.

**Comment by gizmocuz** [comment]
> Hi @gizmocuz, could you please have a look into this modification [c91461c](https://github.com/domoticz/domoticz/commit/c91461ca002d8c0d1b5f9b5c5808553e40e57cf2) "Corrected create/update event" When updating dzvent scripts trough reverse proxy server, the server returns "414 URI too long"
> 
> Had a look in to the modified code, and it looks like the request header method has changed from "POST" to "GET" causing Nginx to deny the request.

Yep, going to have a look at this 'very' soon!

**Comment by gizmocuz** [comment]
Please try beta 15503, the GET is converted to a POST

**Comment by Krakinou** [comment]
I can confirm that beta 15503 solved the issue.
Thanks!

**Comment by MuadDibVV** [comment]
Thanks for the correction.
Is it possible to integrate it in a new 2023.2 prod release to limite the impact ?

**Comment by gizmocuz** [comment]
> Thanks for the correction. Is it possible to integrate it in a new 2023.2 prod release to limite the impact ?

Why? There have been made some other fixes and enhancements as well.
We could make a 2023.3 release, but it's a bit to soon.
Just update to the beta version.
(And if you are still on OpenZWave after more then a year of a notice ahead that the project is deprecated and you need to move to ZWaveJS-UI, than I advise you again to do so asap)

**Comment by MuadDibVV** [comment]
Ok thanks.
Currently, I use only stable release. I'll see if I can switch to the beta versions without too much impact.
(Fortunately I switched to ZwaveJS. :-))

**Comment by didi31** [comment]
The problem to use beta is that the Android version is not allways up-to-date.
This is currently the case with this beta version.
I don't how it can be done to test more but, for me, the "Stable" versions never completely works.

**Comment by gizmocuz** [comment]
Can't see why? Stable has been released some time ago. No pending API changes have been made.
It seems some android applications needs to be updated.
(Or you can use the web interface on your mobile/tablets)

**Comment by didi31** [comment]
The problem is not relative to the stable version.
As soon as a stable version is published I'm very often obliged to switch to the beta to make my installation work.
I subscribed to the official Android app long time ago.
It was working well with the stable version but currently , with the beta, I cannot see the picture of the camera and some item of the menu desappear when I'm outside...
I don't know the origin of the problem but it is.
Yes of course there is always a work arround.

**Comment by gizmocuz** [comment]
Best to contact the android application developer
