### ISSUE TITLE
URLEncode of password should not be done, causes login failure.

### ISSUE THREAD

**Issue by WillemD61** [domoticz/domoticz#5768]
On line 65 on AlfenEve.cpp in the hardware folder it shows:
m_szPassword(CURLEncode::URLEncode(szPassword))

If the szPassword (as provided in the Domoticz hardware setup page) contains any special characters, then the login fails as result of this URLencode.

If the owner password of the charger is changed so it does not contain any special characters and therefore the URLEncode has no effect, then the login to the charger is succesfull, devices are created, data is retrieved.

So the URLEncode should be removed.

Workaround for now is to use a owner password for the charger without special characters.

**Comment by gizmocuz** [comment]
Thanks for spotting! I always assumed it was necessary….
Could you make a PR to correct this?

**Comment by WillemD61** [comment]
PR created. My first, I hope I did it in the right way.

**Comment by WillemD61** [comment]
Seems, I corrected it in the wrong way since the build failed. Someone with more knowlegde of C help please?
Just need to remove the URLEncode.

**Comment by gizmocuz** [comment]
Thank you for spotting this... I have removed the URLEncode in the class constructor
