### ISSUE TITLE
Cannot enable custom menu's to be displayed in Setting 

### ISSUE THREAD

**Issue by Bertels999** [domoticz/domoticz#5769]
Hi, I put some html files in domoticz/www/templates to be displayed as costom menu's. However, they do not appear (in both edge and google chrome). I should enable custom menu's in the Settings page, but that setting is nowhere to be found.

I am running the latest stable veriosn 2023.2 on a raspberry pi.

Bert

**Comment by waltervl** [comment]
This is something for the support forum https://www.domoticz.com/forum/index.php . But I will give you a hint to solve. Go to menu Setup -> Users and enable the custom tab for the user you are using...

**Comment by Bertels999** [comment]
solved ;) thanks

**Comment by Bertels999** [comment]
However, on second thought, the documentation is outdated. But I see that you already updated it. Nice!
