### ISSUE TITLE
Autodiscovery wrong for Nuki Lock

### ISSUE THREAD

**Issue by heggink** [domoticz/domoticz#5771]
Nuki lock 3.0 supports autodiscovery with MQTT. It sends a lock config as follows:
{"~":"nuki/2FFF94F4","avty_t":"~/connected","pl_avail":"true", "pl_not_avail":"false","dev":{"ids":"[2FFF94F4]","mf":"Nuki","name":"VD","mdl":"Smart Lock 3.0 Pro"},"name":"VD","uniq_id":"2FFF94F4_lock","cmd_t":"~/lockAction","pl_lock":"2","pl_unlk":"1","pl_open":"3","stat_t":"~/state","stat_locked":"1","stat_locking":"4","stat_unlocked":"3","stat_unlocking":"2","stat_jam":"254","val_tpl":"{% if value in (\"5\",\"6\",\"7\") %}3{% else %}{{value}}{% endif %}"}
This should be a door lock with functions lock, unlock and open (opens door).
Domoticz creates a light switch with set level 3%.
Events for this lock are sent to:
nuki/2FFF94F4/lockActionEvent e.g.
1,0,3431645,0,0 (unlock)
2,0,3431645,0,0 (lock)

The door sensor is currently a normal swithc and should be a contact:
{"~":"nuki/2FFF94F4","avty_t":"~/connected","pl_avail":"true", "pl_not_avail":"false","dev":{"ids":"[2FFF94F4]","mf":"Nuki","name":"VD","mdl":"Smart Lock 3.0 Pro"},"name":"VD Door sensor","uniq_id":"2FFF94F4_door_sensor","dev_cla":"door","stat_t":"~/doorsensorState","pl_off":"2","pl_on":"3"}

Can this be changed?
If I manually change the light switch to an inverted door lock then it reports fine but it does not respond to any clicks from domoticz (does not lock/unlock). Reason being that it sends the inverted state ie 1 for lock instead of 2 as per the template.

**Comment by heggink** [comment]
more detailed assessment of all the states and what goes wrong below. Looks like a lot nearly works but a few minor issues:

homeassistant/lock/nuki_2FFF94F4_lock/config
`{"~":"nuki/2FFF94F4","avty_t":"~/connected","pl_avail":"true", "pl_not_avail":"false","dev":{"ids":"[2FFF94F4]","mf":"Nuki","name":"VD","mdl":"Smart Lock 3.0 Pro"},"name":"VD","uniq_id":"2FFF94F4_lock","cmd_t":"~/lockAction","pl_lock":"2","pl_unlk":"1","pl_open":"3","stat_t":"~/state","stat_locked":"1","stat_locking":"4","stat_unlocked":"3","stat_unlocking":"2","stat_jam":"254","val_tpl":"{% if value in (\"5\",\"6\",\"7\") %}3{% else %}{{value}}{% endif %}"}`
State 
	1 for locked
	2 unlocking (ignore)
	3 unlocked
	4 locking (ignore)
Domoticz thinks 2 for locked and 1 for unlocked 	

LockAction:
	1 unlock
	2 lock
	3 open
Also does not work correctly
Ideally, the device should be a regular lock (not inverted)

homeassistant/binary_sensor/nuki_2FFF94F4_lock_battery_critical/config
`{"~":"nuki/2FFF94F4","avty_t":"~/connected","pl_avail":"true", "pl_not_avail":"false","dev":{"ids":"[2FFF94F4]","mf":"Nuki","name":"VD","mdl":"Smart Lock 3.0 Pro"},"name":"VD Battery critical","uniq_id":"2FFF94F4_lock_battery_critical","dev_cla":"battery","ent_cat":"diagnostic","stat_t":"~/batteryCritical","pl_off":"false","pl_on":"true"}`

exists and should work

homeassistant/binary_sensor/nuki_2FFF94F4_battery_charging/config
`{"~":"nuki/2FFF94F4","avty_t":"~/connected","pl_avail":"true", "pl_not_avail":"false","dev":{"ids":"[2FFF94F4]","mf":"Nuki","name":"VD","mdl":"Smart Lock 3.0 Pro"},"name":"VD Battery charging","uniq_id":"2FFF94F4_battery_charging","dev_cla":"battery_charging","ent_cat":"diagnostic","stat_t":"~/batteryCharging","pl_off":"false","pl_on":"true"}`
exists and should work

homeassistant/binary_sensor/nuki_2FFF94F4_door_sensor/config
`{"~":"nuki/2FFF94F4","avty_t":"~/connected","pl_avail":"true", "pl_not_avail":"false","dev":{"ids":"[2FFF94F4]","mf":"Nuki","name":"VD","mdl":"Smart Lock 3.0 Pro"},"name":"VD Door sensor","uniq_id":"2FFF94F4_door_sensor","dev_cla":"door","stat_t":"~/doorsensorState","pl_off":"2","pl_on":"3"}
Works **but shows as a normal switch instead of a door contact**


homeassistant/binary_sensor/nuki_2FFF94F4_door_sensor_battery_critical/config
`{"~":"nuki/2FFF94F4","avty_t":"~/connected","pl_avail":"true", "pl_not_avail":"false","dev":{"ids":"[2FFF94F4]","mf":"Nuki","name":"VD","mdl":"Smart Lock 3.0 Pro"},"name":"VD Door sensor battery critical","uniq_id":"2FFF94F4_door_sensor_battery_critical","dev_cla":"battery","ent_cat":"diagnostic","stat_t":"~/doorsensorBatteryCritical","pl_off":"false","pl_on":"true"}`
exists and should work

homeassistant/binary_sensor/nuki_2FFF94F4_keypad_battery_critical/config
`{"~":"nuki/2FFF94F4","avty_t":"~/connected","pl_avail":"true", "pl_not_avail":"false","dev":{"ids":"[2FFF94F4]","mf":"Nuki","name":"VD","mdl":"Smart Lock 3.0 Pro"},"name":"VD Keypad battery critical","uniq_id":"2FFF94F4_keypad_battery_critical","dev_cla":"battery","ent_cat":"diagnostic","stat_t":"~/keypadBatteryCritical","pl_off":"false","pl_on":"true"}`
exists and should work

homeassistant/sensor/nuki_2FFF94F4_battery_percent/config
`{"~":"nuki/2FFF94F4","avty_t":"~/connected","pl_avail":"true", "pl_not_avail":"false","dev":{"ids":"[2FFF94F4]","mf":"Nuki","name":"VD","mdl":"Smart Lock 3.0 Pro"},"name":"VD Battery","uniq_id":"2FFF94F4_lock_battery_percent","dev_cla":"battery","ent_cat":"diagnostic","stat_t":"~/batteryChargeState","stat_cla":"measurement","unit_of_meas":"%"}`
exists and should work

homeassistant/button/nuki_2FFF94F4_unlatch_button/config
`{"~":"nuki/2FFF94F4","avty_t":"~/connected","pl_avail":"true", "pl_not_avail":"false","dev":{"ids":"[2FFF94F4]","mf":"Nuki","name":"VD","mdl":"Smart Lock 3.0 Pro"},"name":"VD Unlatch","uniq_id":"2FFF94F4_unlatch_button","cmd_t":"~/lockAction","pl_prs":"3"}`
**exists but sends ON or OFF instead of 3**

homeassistant/button/nuki_2FFF94F4_lockngo_button/config
`{"~":"nuki/2FFF94F4","avty_t":"~/connected","pl_avail":"true", "pl_not_avail":"false","dev":{"ids":"[2FFF94F4]","mf":"Nuki","name":"VD","mdl":"Smart Lock 3.0 Pro"},"name":"VD Lock 'n' Go","uniq_id":"2FFF94F4_lock_n_go_button","cmd_t":"~/lockAction","pl_prs":"4"}`
**exists but sends ON or OFF instead of 4**

homeassistant/button/nuki_2FFF94F4_lock_n_go_unlatch/config
`{"~":"nuki/2FFF94F4","avty_t":"~/connected","pl_avail":"true", "pl_not_avail":"false","dev":{"ids":"[2FFF94F4]","mf":"Nuki","name":"VD","mdl":"Smart Lock 3.0 Pro"},"name":"VD Lock 'n' Go with unlatch","uniq_id":"2FFF94F4_lock_n_go_unlatch_button","cmd_t":"~/lockAction","pl_prs":"5"}`
**exists but sends ON or OFF instead of 5**

**Comment by gizmocuz** [comment]
Thank you for all details! Surely we can do something with this.
It will take some time before I can work on this, if you like you can help by making a PR
'pl_prs' is not implemented yet
When the battery level is received it will update the devices when a new state is received

**Comment by heggink** [comment]
PR created. Should be OK now. pl_prs implemented as well as some fixes for discovering locks and door sensors
