### ISSUE TITLE
Managed counter not updating history

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5772]
I am now on:
Version: 2023.2 (build 15474)
Build Hash: 8ed086f0f
Compile Date: 2023-07-31 11:10:02
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jun 29 2023, 18:03:57) [GCC 8.3.0]

Everyday at 17:00 I get future prices from the Internet and put them in a Dummy Managed Counter.
![image](https://github.com/domoticz/domoticz/assets/24824113/c2c6f7a1-e090-408e-b64c-4c24945f968d)
This worked fine for a long time. Now I noticed that (I did an update on 20-07-2023) it does not update history anymore.
![image](https://github.com/domoticz/domoticz/assets/24824113/fac9b859-10c3-4712-951e-f369cbdcedeb)
As you can see by the "Usage last 3 days" my update script works fine, but after those 3 days there is no update to the history anymore.
Last history is from 19-07, the day before the Domoticz update.

Sorry forgot to mention that the data is NOT present in the "Meter_Calendar" table.

**Comment by gizmocuz** [comment]
Can you use the new Enever hardware?
Also try updating to the latest beta version as there have been some changes related to managed counters

**Comment by SargonofAssyria** [comment]
As you can see above I was already on Build Hash: https://github.com/domoticz/domoticz/commit/8ed086f0fcceb7d5483c6478fd732ddc52a9f419
But I now updated to Build Hash: 26ebe6e36 See what happens, but don't think that there will be any change.
Edit: I setup Enever hardware on my test system, see what happens.

**Comment by SargonofAssyria** [comment]
I tested Enever hardware, and that is working fine.
I am now on build 15477, but the custom Managed Counter still does NOT work.
Updates are fine, I now got my prices for Monday in, but the history is not getting filled, as seen above in the picture.

**Comment by waltervl** [comment]
what command string are you using to enter the prices that should go to the _calendar table only?

**Comment by SargonofAssyria** [comment]
I don't see what that has to do with the problem, but here it is:
dz.devices('Toekomstige kWh prijzen').updateHistory(currentDateTime,historystring)
The update of the Managed Counter, I let Domoticz update the history.
As you can see the first 3 days are always filled. The daily update to 'Usage last Week' does not work, and that worked until last month, after I updated. See picture below. Negative price are not shown, but that is a problem in the custom Managed Counter.
![image](https://github.com/domoticz/domoticz/assets/24824113/cc22b214-cb18-407b-90e8-b7030b8ffa12)

**Comment by SargonofAssyria** [comment]
I checked with my Enever in test env. that the Type, Subtype and SwitchType are to same as I use in Production.
Only the sValue is different, I got the date/time added in the database.

**Comment by waltervl** [comment]
It could be a dzvents issue, so what happens if you do the same with an API call. I do this monthly for my old fashioned rotation electricity meter and that works fine. Meter_calender table gets updatde (in stable 2023.2)

**Comment by SargonofAssyria** [comment]
dzVents did not change for a long time. It ALWAYS worked until recently, I did not change the script to update the counter. I let Domoticz handle the history update, and the history is where the problem is. On the picture above you can see the "Usage last 3 days" is updated correctly as always. It is only the update of the history by Domoticz that is NOT working. I am not working with stable, but with the latest beta as suggested by @gizmocuz

**Comment by waltervl** [comment]
I am just trying to help you and gizmocuz to find the root cause of your issue.... If it works with the API it should also work with dzvents. With API it is easier to debug.

**Comment by SargonofAssyria** [comment]
The problem with the API is that it needs "svalue=COUNTER;USAGE;DATE" and I don't have COUNTER
dzVents just needs "date, sValues" as parameters.
The Managed Counter from Enever hardware does work as intended, but mine did also but not anymore.

**Comment by waltervl** [comment]
Could be that dzvents is failing now because of stricter API rules, or changed SQL command behind the api. If the api needs a counter value it is strange that dzvents does not need it. Or it fills in an empty value eg 0. What is the nvalue and svalue in your meter_calender table?

**Comment by SargonofAssyria** [comment]
It looks like I found the commit which might cause this e.g. commit db774fc
Have to look into it.

**Comment by gizmocuz** [comment]
Ahhh see there is the problem. Your counter is managed, and this also means it should not automatically add things to the table
And yes there have been made recent changes to dzVents, so it's fair to ask this.
If you don't have a COUNTER then just use the usage twice or enter 0...  You do need to follow the JSON documentation and need to supply all fields.

As Enever is working, have a look at it's code, or keep using that

**Comment by SargonofAssyria** [comment]
It looks to me that on 15 July a correction is made to NOT update the history of Managed Counter. That same correction is not present in the Managed Counter of the Enever hardware.
@gizmocuz I hope that that commit could be reverted.

Edit: Sorry did not see your answer above. (did not refresh the screen.) Will look into that.

**Comment by gizmocuz** [comment]
That's correct. Managed counters should be managed externally.

But it seems you now are talking about two things

- a different svalue string that is documented  in the JSON API
- you want managed counters to have a non-managed/automatic daily value

sValues should comply with the JSON API documentation on our wiki
For managed counters you have the option to set the date/time (short log) or you can specify a date (daily values)

Next to this, there seems to be a 'DisableLogAutoUpdate' option value, speaks for itself that the system should not auto update the log when this is set to true?

**Comment by SargonofAssyria** [comment]
I adapted my dzVents script to accommodate the changed Managed Counter.
Am I right that the correction of the above commit was a correction to an error that was always there and that the error was working in my favor?
Have to wait until 17:00 to see if that worked.

**Comment by gizmocuz** [comment]
Yes, there was a problem causing double entries to be made.
For instance, you had a managed counter and publisched a day value, at midnight there was some some magic, resulted in 2 day values.
So now, managed counters should be managed, and when specified 'DisableLogAutoUpdate' also no magic is done at midnight

**Comment by SargonofAssyria** [comment]
I check it with my dzVents script with todays values and that worked.
Now I have to wait for 17:00 with the values of tomorrow, but I suppose that will work too.
Tnx, solved.

**Comment by SargonofAssyria** [comment]
@gizmocuz  B.t.w. My problem with Enever is that I get my Electricity from Tibber an Gas from Mijndomein
And that is (until now) not possible with Enever hardware. Feature request?

**Comment by gizmocuz** [comment]
Tiber is supported

**Comment by SargonofAssyria** [comment]
But not Tibber and Mijndomein in 1 hardware, I have to make 2 hardware, so 2 requests to Enever.
It would be nice if the hardware could be split in Electical and Gas. I think more people has different suppliers for those.

**Comment by gizmocuz** [comment]
Nope, I don't think there are many users that use different dynamic providers for gas/electricity.

But sure, we can make an option to specify this quite easily... done so in beta 15482

**Comment by SargonofAssyria** [comment]
@gizmocuz Tnx, that is working.
