### ISSUE TITLE
Enever pricing hardware

### ISSUE THREAD

**Issue by enboer** [domoticz/domoticz#5774]
I use the Enever hardware. But as there is now a variable that stores the whole json string, the variable overview becomes hard to read and very big.
As you specify the provider, would it be better just to store the choosen provider values. Maybe add a ‘provider’ in the hardware setup window to store all values. This gives freedom for those whole want all the values.

**Comment by gizmocuz** [comment]
Maybe we should limit the display
Variables (as the name says) is a good place to store variables
And you are not often in this overview correct?

**Comment by enboer** [comment]
Correct, limiting the display length would be ok. If the value is long (eg > 40 characters) just show ...
If you select the variable in Edit Variable section the whole value should be displayed then.

**Comment by gizmocuz** [comment]
Done, limited to 150 characters in beta 15480
