### ISSUE TITLE
Enever plugin fails

### ISSUE THREAD

**Issue by enboer** [domoticz/domoticz#5779]
The Enever hardware plugin does not get updates, at least the user variable with the electricity prices is not updated.
The gas price variable is correctly updated.
The gas and electricity devices are updated correctly, so the actual prices are ok.
In the log I see  the message: 
2023-08-08 15:01:10.737 Error: ETarieven hardware (10) thread seems to have ended unexpectedly
2023-08-08 19:00:56.030 Error: ETarieven hardware (10) thread seems to have ended unexpectedly
2023-08-08 21:01:05.759 Error: ETarieven hardware (10) thread seems to have ended unexpectedly
2023-08-09 07:01:18.358 Error: ETarieven hardware (10) thread seems to have ended unexpectedly 
If I stop the hardware, eg remove the variable. then enable it the variable is created together with a correct value.

As I want to use this variable to check for negative prices I would like use process the variable with the electricity prices.

**Comment by gizmocuz** [comment]
The user variable does not need to be updated, this happens once or twice a day or at the start (when there is old data)
It seems you have a network connection issue

**Comment by enboer** [comment]
If I look at the values for electricity these are from yesterday. the gas variable has price for today.
But the devices have correct values so where does these get the correct data from ?
Looks like it gets the data, but fails to store it in the user variable.

**Comment by gizmocuz** [comment]
At startup and 15/16pm for electricity and 6/7am for Gas new values are requested.
First, we check in the uservariable if it is needed.

I did not touch my system for 3 weeks and all runs perfectly.
I will now update to the latest beta code, there have been some changes made to check if the token is valid.
Maybe there is a issue with this...
This fix has been applied a week ago, but it should be all right

**Comment by gizmocuz** [comment]
Ohhh and also, there is a internal variable with electricity data for tomorrow, if that has data from today, it is used.
(We can only query Enever a few times a day!)

So to recap this, the widgets are correctly displayed in Domoticz?

**Comment by enboer** [comment]
added a new hardware for this enever. the variables get created with correct values. Only 1 time the electricity variable was updated just after midnight. After that the value never get updated.
yes the widgets (devices) get updated correctly.

**Comment by gizmocuz** [comment]
Found the reason, when we get the prices for tomorrow, we can also store this in the user variable

But as long as the widgets get updated correctly all seems fine

Will be corrected in a upcoming beta

**Comment by waltervl** [comment]
Fixed with https://github.com/domoticz/domoticz/commit/9154599b1689f168260663c75b113aed1ab10c98 ?

**Comment by gizmocuz** [comment]
Yes this should be solved by now

**Comment by waltervl** [comment]
then we close it...
