### ISSUE TITLE
[Enphase] Suddenly large negative value on Today kWh Production counter

### ISSUE THREAD

**Issue by 0crap** [domoticz/domoticz#5782]
![Screenshot 2023-08-12 144824](https://github.com/domoticz/domoticz/assets/31951195/1015e309-8d8c-43ed-9bbf-beb5b59f89fb)

![Screenshot 2023-08-12 144836](https://github.com/domoticz/domoticz/assets/31951195/0cc35063-36bb-4b19-8f6f-681edbc74928)

Running Domoticz v2023.2 on a Pi3.
Using "Enphase Envoy with LAN (HTTP) interface".

Working fine for quite some time, but today I noticed a large negative number on the daily counter which mess up the Generated Last Week/Month/Year and Comparing Generated graphs.

The weird thing is that the Generated Last 3 Days graph is fine.
So I can't shift/left click to delete a wrong value because it all looks fine.

Any clue how this can happen?
And how can I fix this?
Shift/left click on Generated Last Week Saturday does not work.

**Comment by gizmocuz** [comment]
The counter has been reset in your Envoy. There is already a discussion about this, and therefor no need to create another one.
You can shift-click on a Month value

https://github.com/domoticz/domoticz/issues/5734

**Comment by 0crap** [comment]
Ahhh, thx. I did search but didn't recognize that one by title.
So it is the shitty Enphase Envoy update.
I few weeks ago I noticed my gateway is now running `D7.6.175`.
On `D7.0.88` never been a issue.

Deleting the day in question worked on the "Generated Last Month" graph.

Hope this will be fixed soon.
It's messing up everything in Domoticz. :-(

**Comment by psinke1974** [comment]
I have the same issue sometimes. I usually update the record in the domoticz database but it requires some SQL skills :-)
Hope there comes a fix.

**Comment by gizmocuz** [comment]
@psinke1974 , what's your Domoticz version? You should be on 15649 or up
I now added a fallback, so when the Envoy resets the counter to 0, we keep on counting. (can happen when you power off the envoy... did that happen to you?)

**Comment by psinke1974** [comment]
> @psinke1974 , what's your Domoticz version? You should be on 15649 or up I now added a fallback, so when the Envoy resets the counter to 0, we keep on counting. (can happen when you power off the envoy... did that happen to you?)

version:%202023.2%0ABuild%20Hash%3A%2019efd039c%0ACompile%20Date%3A%202023-07-21%2017%3A23%3A44%0AdzVents%20Version%3A%203.1.8
i was not aware the envoy was powered off. It sometimes just happens. Is that version a beta channel?

**Comment by gizmocuz** [comment]
Yes, it's the beta version. When you use docker/compose, just use the latest image tag, or if you installed domoticz natively, in the settings, set the release channel to 'beta'
Do know that in the current beta support for OpenZWave is removed and you have to use ZWaveJS-UI (MQTT Auto Discovery) if you are using zwave
