### ISSUE TITLE
[Enphase V4] No more info from enphase Build 15396

### ISSUE THREAD

**Issue by rowemime** [domoticz/domoticz#5786]
I have exactly the same issue's with Enphase hardware as mentioned in issue #5733. @gizmocuz fixed this in issue #5733 for V5, but my system still works on V4 (R4.10.35), is it possible to fix it also for V4?

**Comment by gizmocuz** [comment]
Maybe it's time to update your firmware?

**Comment by rowemime** [comment]
That is completely true of course, I have already contacted my installer about this. But I thought maybe something in Domoticz could also be adjusted for this?

**Comment by rowemime** [comment]
Enphase is quick ;-), they upgraded the Envoy to V7 yesterday and after generating a token and insert it in the user variable everything works fine. But this morning there were errors: " Error: Envoy: Invalid data received! (no session_id)". I had to generate a new Access token to make it work again, any idea what caused this?

**Comment by gizmocuz** [comment]
You should not need to put the accesss token in the uservariable. Domoticz will do this for you.
So in the hardware setup, enter the correct details, username/password and if you have installer rights, the SiteID

**Comment by rowemime** [comment]
Thanks gizmocuz, i think that it works! The mistake i made was that i was using the user "installer" in the hardware setup, but i had to use my enlighten account and password. Now the uservariable was automaticly filled by Domoticz. If everything is still working tomorrow i will close this issue. Many thanks for your help :-)

**Comment by rowemime** [comment]
Still working :-), issue closed.
