### ISSUE TITLE
Strange numbers graphed with virtual 'ampere 3 phases'

### ISSUE THREAD

**Issue by ldrolez** [domoticz/domoticz#5788]
Version: 2023.2 (build 15503)

When I add data to this kind of energy meter the numbers on the utility view is correct, but not the numbers in the graph view.

For example, if I have:
- 82 watt, 93watt, 0 watt on the summary view
- I see 69 watt, 92 watt on the graph ?!
No idea why?
![image](https://github.com/domoticz/domoticz/assets/2277898/489c5b3f-5efe-4bbb-af13-c4b09efeaf2d)

**Comment by ldrolez** [comment]
![image](https://github.com/domoticz/domoticz/assets/2277898/b213f92b-319e-492d-8daf-702543130acb)

**Comment by ldrolez** [comment]
I think there is a rounding error on intermediate calculations

**Comment by gizmocuz** [comment]
The top chart, this is from the actual day? These values are stored to the database every 5 minutes.
In the widget you see the current values.
Could that be the reason?

**Comment by ldrolez** [comment]
yes, there is a rounding error here is what I see in the DB with 82 watt and 93 watt:

 select * from MultiMeter where DeviceRowID=1223;
DeviceRowID|Value1|Value2|Value3|Value4|Value5|Value6|Date
1223|3|4|0|0|0|0|2023-08-19 17:05:01
1223|3|4|0|0|0|0|2023-08-19 17:10:00
1223|3|4|0|0|0|0|2023-08-19 17:15:01

if it's stored as amps, I don't understand the values 3 and 4 :)

**Comment by ldrolez** [comment]
Ok I see BIGINTs in the DB, so amps are multiplied by 10 and stored as int.
Why not storing watts?

**Comment by gizmocuz** [comment]
Because you can display it in Amps or Watts (you can choose this in the settings)
There you can also specify your voltage ... and hence, you might get a small rounding error because P = U * I

**Comment by ldrolez** [comment]
Unfortunately that's not a small rounding error for low powers.

**Comment by gizmocuz** [comment]
Do you need this type of device? Can't you use pTypeGeneral/sTypeCurrent ?

**Comment by ldrolez** [comment]
there is only one phase with this one?

**Comment by gizmocuz** [comment]
Yes, so you can create two

**Comment by gizmocuz** [comment]
Anyway, when you look on the widget (not in the graph) are the values correct?

**Comment by ldrolez** [comment]
yes the widget is correct, but the graph is more important in my case, and it's one of the few graphs where I can see 3 values at once

**Comment by gizmocuz** [comment]
Okey, but as I said before, the graph (day chart) displays samples from every 5 minutes, not the current value

**Comment by ldrolez** [comment]
yes I understand, but the graph is wrong because of the rounding in amperes

**Comment by ldrolez** [comment]
so my current workaround is to multiply the values by 1000 to have less rouding error...

**Comment by waltervl** [comment]
Closing this issue being stale (and perhaps also not being a real issue)

**Comment by ldrolez** [comment]
;(
