### ISSUE TITLE
EVOHome controler still not showing in on the dashboard

### ISSUE THREAD

**Issue by MarcelBaas** [domoticz/domoticz#5790]
Hi,

Today i was "playing" with my EVOhome system again since we added some new heatings and therefore new EVOhome thermostates. Then i notices again that it is possible to add the thermostats (or zones) to the dashboard within domoticz, however not the controller itself. The controller itself is located under switches and the zones under temperatures, which is fine by me. However setting the button to display the controller on the dashboard does not make it visible on the dashboard :(

Looking through the tickets i found the following: [https://github.com/domoticz/domoticz/issues/1739]
This is exactly my issue. Since the issue has been retired in 2017, my question..... are there any plans on making the controller visible on the dashboard?

Cheers
HSH

**Comment by gizmocuz** [comment]
Sorry to say 'again', but this is an opensource project.
Please feel free to make a PR with a fix

**Comment by gizmocuz** [comment]
Hope you will add it someday
