### ISSUE TITLE
Solaredge API (3-phase) acCurrent L1/L2/L3 overwriting device

### ISSUE THREAD

**Issue by robk358** [domoticz/domoticz#5791]
within SolarEdgeAPI.cpp in 3-phase configuration the acCurrent Sensor data for each phase is written to the same device:

SE_AC_FREQ is defined as 24 (line 17)
Line 419: "SendCustomSensor(iInverterNumber, SE_AC_FREQ, 255, acCurrent, szTmp, "A");"

this function should include iPhase

**Comment by gizmocuz** [comment]
Yep, seems like an issue here. To make sure that the current 1-phase users will keep their device, we should rewrite it to

SendCustomSensor(iInverterNumber, SE_AC_FREQ + ii, 255, acCurrent, szTmp, "A");

Are you able to test this?

**Comment by robk358** [comment]
sorry, i dont have a development/build environment setup at the moment. 
but i'm able to test a beta ...

about the fix: I think there will be another conflict with this solution: see line 17 and 18: 
#define SE_AC_FREQ 24
#define SE_DATE 25
probably phase 2 will overwrite the "date device"

**Comment by gizmocuz** [comment]
Nope, the device type of SE_DATE is a Text sensor and this is a custom sensor

**Comment by gizmocuz** [comment]
Is it possible you could test the current beta version? (15509)

**Comment by robk358** [comment]
tested, 2 new acCurrent devices were added with the correct data. thanks for the fast response/handling

**Comment by gizmocuz** [comment]
Great! Thanks for the feedback and testing!
