### ISSUE TITLE
Unable to use highCharts csv data in 2023-2 www/templates 

### ISSUE THREAD

**Issue by domcars0** [domoticz/domoticz#5792]
Hi,
After an upgrade from 2023-1 to 2023-2 my custom templates which use highcharts (with csv/csvUrl data) does not work anymore ?
Here  is a simple sample which is OK with 2023-1 release, but does not display data with the 2023-2 ? 

```
============= www/templates/minibaro.html   ================
 <style>
#container {
    min-width: 310px;
    height: 400px;
    margin: 0 auto;
}
</style>

<body>
<pre id="csv" style="display:none">Heure;hPa
24;1016,1
21;1017,6
18;1018,2
15;1018,5
12;1019,4
9;1019,0
6;1017,9
5;1017,5
4;1017,2
3;1016,7
2;1016,5
1;1016,6
0;1017,0</pre>

<div id="container"></div>
</body>

<script>
Highcharts.chart('container', {
  chart: {
    backgroundColor: '#000',
    type: 'column',
    color: '#666'
  },
  title: {
    text: 'Baromètre'
  },
  xAxis: {
    type: 'category',
  }, 
  data: {
     csv: document.getElementById('csv').innerHTML,
     itemDelimiter: ';',
     decimalPoint: ','
  },
  plotOptions: {
    series: {
      threshold: null
    }
  },
  series: [{
    groupPadding: 0, 
    color: '#666',
  }],
});
</script>
==============================================================
```

**Comment by gizmocuz** [comment]
Did you had a look in the new template/angular example? This contains a highchart chart

**Comment by domcars0** [comment]
Hi gizmocuz, thank for your answer. Unfortunately the angular sample does not use csv data :-( So it does not solve the problem.

**Comment by gizmocuz** [comment]
No, but you can see that the graph is working, so you should be able to get it to work with this maybe?
You could also try to convert it 2 json?

This is their cvs example:

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/data/csv/

**Comment by gizmocuz** [comment]
Angular way is also cleaner

**Comment by domcars0** [comment]
I know that highcharts is working (even in domoticz-2013.2 www/templates), what is not working is the highCharts **csv/csvUrl data** in domoticz-2013.2 templates (and it worked in domoticz-2023.1) . I'm not looking for a "turn around the bug" solution, I just declare a bug. Thanks.

**Comment by gizmocuz** [comment]
... must be a language.... Sure, you wanted some help with this?

Either you have previously added the data module yourself, or since the recent version the data (import) module is a separate module now.
I added the data module and it should work again in beta 15509, is it possible to verify this?

**Comment by domcars0** [comment]
It works! Thank you very much. I coded my templates long time ago, so it's not impossible that I added this line in the www/index.html, but I don't remember it (I'm 65 years old, sorry ;-)  ).
Thank again.

**Comment by domcars0** [comment]
After verified my backup, I can say that I've added the data.js in the index.html. Sorry.

**Comment by gizmocuz** [comment]
No worries, but now it's added by default ;)
