### ISSUE TITLE
1wire - disconnected sensor still being reported as a live

### ISSUE THREAD

**Issue by blmpl** [domoticz/domoticz#5795]
Hello,

Regardless of "Error: 1-wire: 1-Wire system : error reading value from /sys/bus/w1/devices/28-xxxxx" error, the last correct reading is constantly send back to the core  which makes you thing that the sensor is still working (see the 
![Screenshot 2023-08-23 at 15 47 56](https://github.com/domoticz/domoticz/assets/10145557/672b6ef6-3d12-4697-8c3c-4208c68baa7e)
graph)

This is happening on the project build from the latest develop branch (last commit 30041b1ee0aff12d1731c5d8fc643173917e9963) using kernel 1wire support

**Comment by gizmocuz** [comment]
That is true. We take the last value received and use this in the short log

**Comment by blmpl** [comment]
I'm not really concerted about the graph, but the last value is send over and over to the core and reported by mqtt. Also sensor is NOT marked as "HaveTimeout" on api and doesn't change its color to red in the gui.

Maybe not a big issue... unless this is a boiler temperature read by PLC (mqtt) that starts 4.5kW 3phase water heater based on it.

my findings are that in 1WireByKernel.cpp => ReadStates, should have some ``device->m_Temperature = -1000.0F;`` in OneWireReadErrorException

**Comment by gizmocuz** [comment]
If you have time and could make a patch/PR that would be great!

**Comment by blmpl** [comment]
can you take a look? it seams to be working

**Comment by gizmocuz** [comment]
Are you compiling Domoticz yourself? How about changing the function 

**C1WireByKernel::ThreadReadRawDataHighPrecisionDigitalThermometer**

At the bottom, instead of throwing an exceptionreturn -1000.0F?

Another option, add a 'valid' boolean to the device object, and at the start of the reading set this to 'false'.
When the reading is correct, set it to true
(Do this everywhere, not only for the kernel method)

In all report methods, check if the device is valid, if not, don't report

I think that is a better method?

**Comment by gizmocuz** [comment]
Thank you for your PR. I had a small comment about checking if a device needs to be created.
This is not needed at this is run at startup and you can be very sure this is not created yet 😊
At the moment you fixed it for 1wire-kernel, if you use OWFS this needs to be done as well?

**Comment by blmpl** [comment]
> Are you compiling Domoticz yourself? 

Yes :)

>  How about changing the function
> **C1WireByKernel::ThreadReadRawDataHighPrecisionDigitalThermometer**
> 
> At the bottom, instead of throwing an exceptionreturn -1000.0F?

this code uses exceptions in similar functions and IMO - it is "exceptional case" so probably(?) should be handled that way for consistency.  

> Another option, add a 'valid' boolean to the device object, and at the start of the reading set this to 'false'. When the reading is correct, set it to true (Do this everywhere, not only for the kernel method)
> 
> In all report methods, check if the device is valid, if not, don't report
> 
> I think that is a better method?

I couldn't agree more - of course it would be much better :) 
Passing -1000.0 through the code is quite surprising when you first see that, but also that would need much more changes and time.

This extra "if" is a leftover from my attempt to do rediscovery of sensors during runtime. (removed)

regarding OWFS - I'm not using it so can't judge, but seams there is no throw/catch there and it just pass -1000.0 on error  so maybe it's immune for that problem.

**Comment by gizmocuz** [comment]
Thank you for the PR! It's merged!

**Comment by blmpl** [comment]
thank you :)
