### ISSUE TITLE
python includes in hardware/plugins/Include

### ISSUE THREAD

**Issue by xbeaudouin** [domoticz/domoticz#5797]
I am maintainer of domoticz port on FreeBSD. I was trying to figure why there is some segfault on domoticz, and after long research I figure the main reason was threads + python.
Working on debug plan, I finaly figure that it should have issue somewhere on the python ABI used with domoticz.
So after discussion I saw that python Includes files are included in hardware/plugins/Include.
Well after doing 2 weeks of test on my production domoticz the regular segfault because of python finished to happends after I rm -rf hardware/plugins/Include when building domoticz.
Is this any good reason to include maybe not really up to date includes there?  Or even worse includes that doesn't reflect how python has been compiled by the OS?
Kind regards

**Comment by gizmocuz** [comment]
I guess this is to make sure it can be compiled.
But a more include files could be a good option. 
Include files seems to be from python 3.5.1

Now I tried to replace them with 3.10.8, but now I get the following errors when compiling under windows:

 error C2065: '_Py_DEC_REFTOTAL': undeclared identifier (DelayedLink.h)

So I added this patch:

```
#ifndef _Py_DEC_REFTOTAL
  /* _Py_DEC_REFTOTAL macro has been removed from Python 3.9 by:
    https://github.com/python/cpython/commit/49932fec62c616ec88da52642339d83ae719e924 */
#  ifdef Py_REF_DEBUG
#    define _Py_DEC_REFTOTAL _Py_RefTotal--
#  else
#    define _Py_DEC_REFTOTAL
#  endif
#endif
```

But not sure how this will go on systems running python 3.7 for instance

But, I suspect this is more for windows, and the python libraries should be found in the CMakeList.txt via

```
IF(USE_PYTHON)
  find_package(Python3 3.4 COMPONENTS Development)
  IF(Python3_Development_FOUND)
    MESSAGE(STATUS "Python3 version ${Python3_VERSION} includes found at: ${Python3_INCLUDE_DIRS}")
    INCLUDE_DIRECTORIES(${Python3_INCLUDE_DIRS})
    add_definitions(-DENABLE_PYTHON)
  ELSE(Python3_Development_FOUND)
    MESSAGE(FATAL_ERROR "Python3 not found on your system, use USE_PYTHON=NO or sudo apt-get install python3-dev)")
  ENDIF(Python3_Development_FOUND)
ENDIF(USE_PYTHON)
```

I can't see (when compiling with non-windows) where the hardware/plugins/include folder is included, but I might oversee something.

**Comment by xbeaudouin** [comment]
This is strange on Windows, there is no includes has been found by CMake...
My production environment is with python 3.9 and clang.
I know that FreeBSD is quite a little more picky. But having python 3.5 include may give some inconstancy according was I learn loooong time ago with compilers.
Well I can still do the rm on my ports. But this is maybe a good indication of some bug reports there about python that segfault domoticz.
So that's why I asked about the real usage of this, since it should provided uppon compilation by CMake :D
Kind regards

**Comment by dnpwwo** [comment]
The ABI is (by definition) stable and therefore compiling against any version that contains all the required functions should be sufficient regardless of the platform or the version that Python is up to, the included version satisfies that criteria.  The whole point of the ABI is to insulate consumers of Python like Domoticz from the changes that the Python team make between versions.

If Free BSD has a segfault can you post the crash dump so that we can understand the issue?

**Comment by xbeaudouin** [comment]
Well, I don't have not any crashdump since 2 weeks, when... I just rm -rf the given headers when compiling domoticz. Otherwise the segfault was every 3 days (sometime less).
This is not an memory issue, domoticz has lot of memory in this dedicated hardware. I suspect the generated headers used on this includes doesn't fix FreeBSD way of compiling python.
Well nextime I will send the crashdump and the core... but for now the system is stable.

**Comment by gizmocuz** [comment]
@dnpwwo , these headers (hardware/plugins/Include), how are they included via CMake? I am unable to find this.
Could we not let this be found on the system and if found use these? (In that case probably a more modern version of what is distributed with Domoticz)

**Comment by gizmocuz** [comment]
@xbeaudouin , could you test build 15676 ? I replaced the includes with the one from Python 3.12
I am still not sure how the hardware/plugins/include is found (via cmake) so I can't make a real patch ... as we might still need the file for windows compilation

**Comment by gizmocuz** [comment]
@xbeaudouin , sorry, I can't compile under x86 anymore, I had to revert the new include files

@dnpwwo , If you have time, could you please update the hardware/python/includes to 3.12, or maybe remove them?
I was facing a '_py_dealloc' issue

**Comment by dnpwwo** [comment]
Since the Python frameworks use the Python ABI the header files **never need to be updated** because the compiled code will run against any version of Python 3.x greater than 3.5.  The DelayedLink header file is configured to work with those.

For consistency I would recommend that all platforms build against the supplied headers (hardware/plugins/include) rather than whatever random version is on the build machine.  This is important because if you compile against a particular version normally Python will resolve a lot of symbols to macros rather functions, with the ABI it does not. 

@gizmocuz Is Visual Studio including the correct files in your setup?
![Untitled](https://github.com/domoticz/domoticz/assets/6850332/db666c27-be71-4a74-b919-6ac146c567cc)

@xbeaudouin what version of Python are you running against on FreeBSD?

**Comment by gizmocuz** [comment]
@dnpwwo , yes visual studio is using this folder. But I don't know how CMake uses this folder, I don't see a refference to it.
Maybe we could update the include files to the once from Python 3.11 or 3.12 ?

**Comment by xbeaudouin** [comment]
> @xbeaudouin , could you test build 15676 ? I replaced the includes with the one from Python 3.12 I am still not sure how the hardware/plugins/include is found (via cmake) so I can't make a real patch ... as we might still need the file for windows compilation

I have tried, but have same result... Mostly because DelayedLink that miss _Py_Dealloc() because of deprecation of this on Python 3.9+

**Comment by xbeaudouin** [comment]
> @xbeaudouin what version of Python are you running against on FreeBSD?

I use python39-3.9.18

About headers files and DelayedLink.
I can undestand the idea to not use the "systems" includes, BUT I really think other bug #5476 and #5831 are mostly an emerged iceberg.

Does Domoticz use the same way Scripting -> Events -> Python AND python plugins?

Or it does try to use DelayedLink for Python's Events and pluging are not handled the same way?

We definitively have something unstable... and I really don't know how to stabilize it... (at one point... I would like to make all my plugins from python to C++ for stability reasons... or use something else).

Also notice my domoticz are build using poudriere to have "clean" environnement and reproductible code. So really I don't need DelayedLink...

**Comment by xbeaudouin** [comment]
@gizmocuz  Maybe PR #5915 will help you to push back the header you tried to push on build 15676.
OT: if you want some FreeBSD building and test, we may setup this on my servers (I got a 32 cores server for package building)... I dunno how to make the link between github and my server....

**Comment by gizmocuz** [comment]
Hmmmm thats a bit tricky as it could very well mean when you have python 3.10 or up, that you defined _Py_Dealloc, but it does nothing. So this could introduct more memory leaks.
Best to call the 'new' function that replaced it

**Comment by xbeaudouin** [comment]
Well there is no "new function", and historically this was to catch up the time when this "function" is called.
Well this is on production at home AFAIK.

**Comment by gizmocuz** [comment]
I still think you will have a memory leak. It only solves the compiling for python 3.10+
it is like you use the 'malloc' function, and define a 'free' function that does nothing.
Sure, it compiles and runs, but nothing will be freed.
I can't imagine that there is no alternative way to malloc/free things now with version 3.10,  maybe two new function where introduced that needs to be used now

**Comment by gizmocuz** [comment]
@dnpwwo , is it possible you could update these includes to the once delivered with python 3.9/3.10?

**Comment by gizmocuz** [comment]
@xbeaudouin , can we close this issue?
