### ISSUE TITLE
json api endpoint ERR status

### ISSUE THREAD

**Issue by RunnicFusion** [domoticz/domoticz#5799]
When calling some api methods an ERR status is returned when calling in browser. I'am logged in to Domoticz as admin to create a session.
Domoticz version: 2023.1

For example: json.htm?type=command¶m=getdevices&plan=0&filter=all&used=true
`returns: 
{
	"status" : "ERR"
}`

Can't find and logging releted to this call. Some other calls are working/
Working: /json.htm?type=command&param=devices_list
Faulty: /json.htm?param=getsettings&type=command

**Comment by gizmocuz** [comment]
if this is the actual command you are sending, then there is a typo

this

`json.htm?type=command¶m=getdevices&plan=0&filter=all&used=true`

should be

`json.htm?type=command=getdevices&plan=0&filter=all&used=true`

(you have ¶m after command, this should be removed)

And this is valid

`/json.htm?param=devices_list&type=command`

as well as

`/json.htm?type=command&param=getsettings`

It depends if you have admin rights of course

**Comment by RunnicFusion** [comment]
Hi @gizmocuz ,

Yes saw that. This command was comming from Domoticz Google Assistent log file.
When replacing the '¶' the api endpoint also produces a 200 status ok contain ing Status: ERR as json body.

So correct url: http://[myip]:8080/json.htm?type=command=getdevices&plan=0&filter=all&used=true
![image](https://github.com/domoticz/domoticz/assets/11329216/91a04ef2-a51a-46cb-9afd-4f474c3f6ff6)


Some other endpoint are running fine (devices_list command for example)

**Comment by gizmocuz** [comment]
Is the machine where you perform the query from appear in the trusted network settings?
So it get's admin rights? Otherwise you are not allowed to get the settings
Also, try with the latest beta version
I tested the above queries on my system and I know they work (getsettings)

**Comment by RunnicFusion** [comment]
hi!
- yes, it's on trusted network settings + Basic-Auth authenticate is switched to 'on'
- it was working previously, my quess was some sort of strange devices caused issues. Domoticz devices are comming from zigbee2MQTT and z-Wave JS. But can't find strange devices/names
- i'm on latest release version (docker image)
- uses is my admin user, also tried creating new user; same result

**Comment by RunnicFusion** [comment]
Closing issue. Issue was:

my Domoticz installation was running on 2023.1 instead of 2023.2.
DZGA 1.23.10 needs Domoticz 2023.2 because of API changes for endpoinhts like json.htm?type=command=getdevices&plan=0&filter=all&used=true
Issue was; my docker image wasn't update correctly and using older (23023.1) version... :( Sorry for not noticing version difference until now.

Right now the new endpoints seems to work as expected so DZGA can fetch my devices and also connect to Google Home app. 


**Note**: Endpoint just was not implemented in 2023.1 I guess. It returned status ok with message error; maybe returning 'not implemented' as message by default for non-routed endpoints would be better?

**Logging**:
`2023-08-25 10:13:25.510 [WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command! (172.17.0.1)`
Right now seeing some fallback / depricated calls in my logs. Is this bad? Not exactly sure what is triggering them.


for reference: [#339](https://github.com/DewGew/Domoticz-Google-Assistant/issues/339)
