### ISSUE TITLE
Creation ManagedCounter failed

### ISSUE THREAD

**Issue by MuadDibVV** [domoticz/domoticz#5800]
Hello,

  I have an error when trying to create a new managedCounter on a dummy hardware :
![image](https://github.com/domoticz/domoticz/assets/62676693/e843206c-30bf-4ab2-88c3-690928c36dbf)

![image](https://github.com/domoticz/domoticz/assets/62676693/1b4ae8e3-da8c-462f-ae44-2c33e94a5907)

![image](https://github.com/domoticz/domoticz/assets/62676693/faf59323-fe77-46db-aab4-3bb6380766ac)

The device is nevertheless created

![image](https://github.com/domoticz/domoticz/assets/62676693/4f814100-c504-4684-89e2-78bb5c4e47b5)

But not available (acces with dzvents with id or name (function updateHistory))

![image](https://github.com/domoticz/domoticz/assets/62676693/99798734-802d-426b-a22f-3965446f4abc)

For information :
Version: 2023.2
Build Hash: "19efd039c"
Compile Date: 2023-07-21 17:23:44
dzVents Version: 3.1.8

No problem when creating other types of devices

**Comment by kiddigital** [comment]
Hi @MuadDibVV , I am unable to re-create the problem as it works fine with the latest beta.

Please try again with the Browsers developertools active (F12) on the Network-tab. Look for a (XHR) request that looks like
`/json.htm?type=command&param=createdevice&idx=<someid>&sensorname=<yourname>&sensormappedtype=0xF321`
Now find the _response_, there should be some JSON response normally. How does your response look like?

Also, try running your domoticz instance with some debugflags enabled like `-debuglevel all` and look for the debuginformation when doing your request.

**Comment by MuadDibVV** [comment]
Thank you @kiddigital for your answer.
The response is :
{
	"status" : "ERR"
}

I use a docker version (linuxserver) so I don't know how I can add the debugflag

**Comment by MuadDibVV** [comment]
I migrated a copy to the official docker instance (stable tag) and have the same problem.
I try with the latest tag and... the problem disappear.

I need to migrate my production instance

Thanks for your support
