### ISSUE TITLE
New RFXCOM protocole DDxxxx for Dooya motors

### ISSUE THREAD

**Issue by tcellerier** [domoticz/domoticz#5804]
Hello,

Could I ask you to add the protocol DDxxxx that was released with the firmware RF433 2022, to the list of manual switches?

See the documentation page 52: http://www.rfxcom.com/WebRoot/StoreNL2/Shops/78165469/MediaGallery/Downloads/RFXtrx_User_Guide.pdf

The hex command structure that can be used in Home Assistant:
0C 31 00 00 11 22 33 44 00 00 00 00 00
============================ always 00
========================== angle can be hex 00 to B4
======================= percent can be hex 00 to 64
===================== command
=================== unit code 00 to 10
================ ID4 00 to FF (ID 00000001 to FFFFFFFF)
============== ID3 00 to FF
=========== ID2 00 to FF
========= ID1 00 to FF
======= always 00
==== always 00
== always 31 
always OC

**Command**:
Up 0x00
Down 0x01
Stop 0x02
P2 (pair) 0x03
Percent 0x04
Angle 0x05
Percent+Angle 0x06

**Unit code:**
00 unit 1
01 02 03 04 05 06 07 08 09 0A 0B OC OD OE
OF unit 16
10 Group command, all units with the same ID.

**Example**, ID 11 22 33 44, unit 1, P2 (pair) command.
The hex command line without spaces to be used is:
0C310000112233440003000000

Thank you very much
Thomas

**Comment by gizmocuz** [comment]
If you use the RFXMngr application, can you control the blind? Which blind type is this? Blind Type 6?
If it is 6, could you try a manual Blinds T6 DC106 ?

**Comment by tcellerier** [comment]
Yes it works with the RFXMngr application. 
First I paired the controller with the existing remote and I can now move up and down the blind. There is a specific new module in the application for it called DDxxxx.
 I tried to use Blind T6 DC106 in Domoticz but didn’t work. I think it’s a completely different protocol as it’s in a separate section in the RFXCOM documentation and application, although it looks to be part of the same family « Dooya and compatible » 
Thanks for your help

**Comment by gizmocuz** [comment]
Can you try beta 15520? You have to pair it for now with RFXMngr (the first ID has to be in range of 1..3)
Then you can manually add it (Brell DDxxxx type)
You should then be able to open/close/stop and percentage it

**Comment by tcellerier** [comment]
It's functioning perfectly for both my blinds: one being a single blind and the other a group of blinds.
From my perspective, it's totally fine having to do the pairing with RFXMngr as it has to be done only once.

Thank you immensely for making this work so quickly.
We can close this feature request

**Comment by gizmocuz** [comment]
There might be a change in the SDK regarding the Unit ID ... currently 16 means ALL and Unit starts from 0 till 15.
It's a bit inconsistent in relation to other implementations where 0 = ALL and unit ID start  from 1 till 15

Once (if) there is a new firmware, I will modify Domoticz to remove the +1 and -1 for the Unit ID in MainWorker::SwitchLightInt

Great it's working!

**Comment by tcellerier** [comment]
Two last comments if you could take a look:
- The favorite button doesn't seem to add this new type of switch to the main dashboard
- The log menu doesn't show anything
Thanks again!

**Comment by gizmocuz** [comment]
I will check this but the favourite seems odd

**Comment by gizmocuz** [comment]
Found the issue. Could you test with beta 15523 and also with the latest RFXCom firmware 2024.
The unit id has been adjusted, if using firmware 2024 and 15523 you should experience no issue controlling your blind, and the log/favorite should work again

**Comment by tcellerier** [comment]
I confirm everything is ok now after the 2 updates. 
Thanks again!
