### ISSUE TITLE
OpenZwave type of device (for Aeotec USB Stick) disapeared from list after upgrade to latest Beta (15518)

### ISSUE THREAD

**Issue by woddou** [domoticz/domoticz#5805]
Hello,

After upgrading to latest Beta veresion (15518from yesterday) I discover that on Hardware my Aeotec Zwave USB stick was "Unknown", looking at the list of type of devices I'm not able to find "OpenZwave" one which was previously the one used for this device.
My Zwave network looks to work properly by I don't have anymoe access to Zave network configuration which can be an issue.
Any idea what happend ? Thanks.

**Comment by woddou** [comment]
Looks like there was already a thread about it, any other alternative than migration, it will take forever...

**Comment by gizmocuz** [comment]
You might want to read the release notes now/then on the Forum.
One year ago we mentioned that support for OpenZWave will be dropped as the project is stopped.
Last stable we mentioned this again, and now in the current beta we removed it.
You have to use ZWaveJS-UI with MQTT Auto discovery
Visit the forum/wiki for more information
Yes it might take an hour or so

**Comment by woddou** [comment]
Just tried to install ZWaveJS-UI following the WIKI after installing Docker and Mosquito but it failed at the installation step using the following command line: docker run --rm -it -p 8091:8091 -p 3000:3000 -e TZ=Europe/Paris --device=/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave --mount source=zwave-js-ui,target=/usr/src/app/store zwavejs/zwave-js-ui:latest.
So I'm stuck. 
MQTT Auto discovery is already available on the latest Domoticz Beta.

**Comment by gizmocuz** [comment]
Maybe you should switch to docker compose, but please use the forum!
