### ISSUE TITLE
Mqtt auto discovery Last Seen updates issue

### ISSUE THREAD

**Issue by blooesky** [domoticz/domoticz#5807]
Hi,

I noticed that last seen only works if the value or status of the device changes. When the device is checked to see if it is connected, the last seen is not displayed in domoticz. In z2m dashboard all is fine and all devices are checked frequently.

Domoticz [2023.2 (build 15512)
MQTT Auto Discovery Client Gateway with LAN interface -> Zigbee2Mqtt

Thank you!

**Comment by gizmocuz** [comment]
You mean when domoticz/zigbee2mqtt is restarted?
That is done on purpose. Imagine we update the last-seen, this would also trigger a event for scripts
You will get a timeout when a temperature sensor is not updated in an hour, but not for switches

**Comment by blooesky** [comment]
The last seen is updated when zigbee2mqtt is restarted and when the devices changes data/status. 
Maybe you are right, but in certain situations it would be useful to see the last communication with the device for example when you using domoticz api for an external integration. Before I used Zigate with domoticz and it did this.

Thanks for the reply!

**Comment by gizmocuz** [comment]
You will see the last update change when there is a new value received.
I don't think you will get a update from a switch when nobody using the switch

**Comment by waltervl** [comment]
The zigate/Zigbe4Domoticz plugin process is polling the zigbee switches on the background (so outside domoticz) if they are still alive. If not answered for x time it will put the device to timedout in Domoticz, giving a red highlight on the domoticz device widget.

I do not know if Zigbee2MQTT can do the same polling and send a specific MQTT message if it finds the zigbee device offline. If so Domoticz can pick it up and do the same. But first Zigbee2MQTT should send the message.

**Comment by waltervl** [comment]
Addition: It seems so if device availability is configured: https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-friendly-name-availability

**Comment by waltervl** [comment]
@blooesky did you check the Zigbee2MQTT device availability function?

**Comment by blooesky** [comment]
Yes, my all devices which is not used and which have not changed their status for several days it was "last seen" yesterday in domoticz.  I don't know why yesterday(at the same time 12:09-12:10) and if there it is a time interval at which domoticz checks.  In z2m the devices is checked every 15 minutes and few hours for sensors.

**Comment by rezzalex** [comment]
Hello, I am very interested in such feature (but for ZwaveJS-UI).
How Domoticz works for marked a device "in red" (Timedout ) ? what are the criteria ? is it possible to be notified on such event ?

**Comment by waltervl** [comment]
> Yes, my all devices which is not used and which have not changed their status for several days it was "last seen" yesterday in domoticz. I don't know why yesterday(at the same time 12:09-12:10) and if there it is a time interval at which domoticz checks. In z2m the devices is checked every 15 minutes and few hours for sensors.

I asked to check the availabilty in Z2M eg MQTT topic zigbee2mqtt/FRIENDLY_NAME/availability
Does it switch it status? Check with MQTT explorer.

But perhaps you are request something we do not understand yet...
>Maybe you are right, but in certain situations it would be useful to see the last communication with the device for example when you using domoticz api for an external integration. Before I used Zigate with domoticz and it did this.

What did you use to check with Domoticz API? Zigate plugin also only updates the lastseen if it really modified the data. So then I do not understand what you want to achieve....

**Comment by waltervl** [comment]
> Hello, I am very interested in such feature (but for ZwaveJS-UI). How Domoticz works for marked a device "in red" (Timedout ) ? what are the criteria ? is it possible to be notified on such event ?

https://www.domoticz.com/wiki/Application_Settings#Sensor_Timeout 
Better discuss this on the forum.

**Comment by gizmocuz** [comment]
We never updated the last seen on switches when the state does not change for switches 
Only on other devices and it’s state should turn red after one hour
This is the same for RF devices
