### ISSUE TITLE
Evohome: set temperatures via events

### ISSUE THREAD

**Issue by bertoost** [domoticz/domoticz#581]
Is this something on the roadmap or is there a reason why this is not yet possible?

I'm using some evohome client scripts to sync evohome data with Domoticz. But I can't see the controllers via the events interface.
Would be nice to turn my heating system on when I leave my work automatically :-)

**Comment by gordonb3** [comment]
You mean you want to be able to change individual zones via events? The main controller (evotouch) is available as a switch, so you should be able to use events to change mode from HeatingOff or Away to either Normal or Custom.

**Comment by bertoost** [comment]
I indeed mean to set the individual zones.. 

Maybe I can make a workaround for now with the EvoTouch, eq. enable or disable the schedule.

**Comment by StanDH** [comment]
I set my zones using Blockly, Virtual switches and Jason. The controller can also be set this way. From the Evohome Wiki:- 

**Updating a setpoint using the JSON API**
/json.htm?type=setused&idx=<idx>&setpoint=<setpoint>&mode=<mode>&used=true
**<idx>** id number of the evohome zone device in Domoticz
**<setpoint>** set point in degrees (will be ignored for Auto)
**<mode>** Auto,TemporaryOverride,PermanentOverride
**used** must be true

**Comment by gizmocuz** [comment]
Please use our forum for non-c++ code related issues

**Comment by bertoost** [comment]
I also post on the forum, but the response time is very very bad
I am not able to set a zone via Blockly or LUA scripts (the zones are not available) and I'm also not able to use "set mode" of the EvoTouch via LUA; see http://www.domoticz.com/forum/viewtopic.php?t=11402
