### ISSUE TITLE
Please add build numbers to commits

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#5810]
apparently build numbers are not published anymore for 2023 version like this way

https://www.domoticz.com/wiki/Domoticz_version_table_V2022.2

there is no way to tell what build has what fix or commit.

would it be possible to mention the build numbers somewhere so we can see what version gets installed with what fixes?

thanks

**Comment by kiddigital** [comment]
Look at

https://www.domoticz.com/wiki/Domoticz_versions_-_Commits

You can relate the buildnr to the commits in the repository (development branch). That tells you which commits are in your version (or not).

**Comment by GravityRZ** [comment]
but that is exactly the problem i am describing.

your answer is correct for 
2020.1
2020.2
2021.1
2021.2
2022.1
2022.2

these are all clickable links and show exactly the build and the commits in them.

from 2023 build this is not clickable anymore, there is no page which shows you all the 2023 build and their commits.

so if this is shown anywhere else or i am mistaken please point me in the right direction to find the info which was previously shown on 1 page.

**Comment by waltervl** [comment]
The github commit list is the list of implemented changes: https://github.com/domoticz/domoticz/commits/development
https://www.domoticz.com/wiki/Domoticz_versions_-_Commits describes this and also how the buildnumber is calculated.

**Comment by GravityRZ** [comment]
yes but it is still not that clear to me.
i can calculate the latest build but everything below is blurry.

since the build number is total commits+2107 why not make an extra field to show it instantly

i now see a hex number with commit details, why not add the build number here.
should be easy to put this number at the end of each commit
anyway, do not make a big deal about it but for us"noobs" it would make life easier

![image](https://github.com/domoticz/domoticz/assets/16853535/b8768885-b1a5-430a-b629-68695774ffdb)

**Comment by waltervl** [comment]
It is not possible unfortunately in GitHub to add this column.

**Comment by GravityRZ** [comment]
ok, clear
