### ISSUE TITLE
Enphase 

### ISSUE THREAD

**Issue by IW2FAG-11** [domoticz/domoticz#5811]
Upgrading Domoticz from 2023.1 to 2023.2
Whats happen on data from mine Enphase inverter production (Item ID 63  )?
I do upgrade at about 8.00.

63 | 594809 | 470 | 2023-09-05 07:55:00
63 | 594822 | 660 | 2023-09-05 08:05:00
63 | 5364722 | 930 | 2023-09-05 08:10:00
63 | 5364729 | 1130 | 2023-09-05 08:15:01

Data looks having a big step........... and now all mine two year statistic are falling...........

**Comment by gizmocuz** [comment]
Do you have a metered envoy gateway? We are now using the metered data
There is already a explanation/discussion about this

Two years ago we for sure did not had a native Enphase implementation, I guess around november 2023
How about waiting a day and see how it looks tomorrow

Or use the Github issue search option to find the other issue about this

**Comment by IW2FAG-11** [comment]
Good morning, yes I have an Enphase gateway.
Okay instead of collecting and storing a certain type of data, with the new release you have modified the collected data.
 Enphase Envoy-S Metered™ ENV-S-WM-230 connected with 8 microinverters.
Unfortunately everything was fine via custom script, until June they remotely upgraded from version 5 to 7 without even notifying me. So they introduced a very tedious procedure of unnecessary certifications, since 99.99% of the time I block the gateway connection with firewall blocking the output to the network. Since June, i'm using embedded plugin to collect data, from enphase, then I elaborate collected from plugin to send to mine other script.
By contacting them they "warned" me that if the gateway does not communicate with their "enphase" servers for more than a year, the 10-year warranty is void. In pratice if I do not let them take MY data that they pass and store on AMAZON AWS servers, they do not guarantee their product for 10 years. Privacy..... may be.

**Comment by gizmocuz** [comment]
Well now you have it in Domoticz ;) Just wait a day and see how it goes tomorrow with the values...
There seems to be a jump, but that's because they use different counters for unknown reasons

**Comment by waltervl** [comment]
@IW2FAG-11 how is it going now?

**Comment by IW2FAG-11** [comment]
This ia the effect on data stored after upgrading to 2023.2.
Changin data collected make a giant disontinuity that destroy all database omogenity.
![Clipboard01](https://github.com/domoticz/domoticz/assets/69007986/9c5b21bc-4333-4fe8-9961-de04435b2616)

**Comment by waltervl** [comment]
You can delete that large value by clicking on it in the month graph with shift key pressed. A popup will be shown to delete it.

**Comment by IW2FAG-11** [comment]
63 | 594809 | 470 | 2023-09-05 07:55:00
63 | 594822 | 660 | 2023-09-05 08:05:00
63 | 5364722 | 930 | 2023-09-05 08:10:00
63 | 5364729 | 1130 | 2023-09-05 08:15:01
As You can see, ther is a big step on data that couse the discontinuity.
The bigger bar is not DELETABLE. 
That discontinuity is caused from update from 2023.1 to 2023.2

**Comment by waltervl** [comment]
You are looking in the meter table, you should look in the meter_calender table.

But indeed a sudden big delta in counter value is not easy to fix. Could also be related to different value that Enphase is sending.

**Comment by gizmocuz** [comment]
A new patch have been made friday that should handle the sudden counter reset by enphase.
Please update to the latest beta version
If you want to remove a spike, shift click on it in the month graph

**Comment by IW2FAG-11** [comment]
Thanks. I'll try sooners.

**Comment by IW2FAG-11** [comment]
Look working, thanks

**Comment by gizmocuz** [comment]
Great, thanks for the feedback!
