### ISSUE TITLE
MQTT AD kWh sensor support enhancement

### ISSUE THREAD

**Issue by enesbcs** [domoticz/domoticz#5812]
Most Shelly devices has a weird choice to return energy usage by watt-minute or watt-hour.. in HA it can be changed in realtime with the following templates in the configuration payload:

watt-minute (Wm):
`"unit_of_meas": "kWh", "val_tpl": "{{(value|float/60000)|round(3)}}"
`
watt-hour (Wh):
`"unit_of_meas": "kWh", "val_tpl": "{{(value|float/1000)|round(3)}}"`

But as Domoticz has no inline template support, i have another suggestion below.

I guess kWh type is managed at line 1672 in MQTTAutoDiscover.cpp
https://github.com/domoticz/domoticz/blob/development/hardware/MQTTAutoDiscover.cpp#L1672

```
else if (szUnit == "kwh")
{
	devType = pTypeGeneral;
	subType = sTypeKwh;
	float fUsage = 0;
	float fkWh = static_cast<float>(atof(pSensor->last_value.c_str())) * 1000.0F;

```	
What is the function of the above multiplication by 1000?
Is it possible to add here type "Wh" and "Wm" units (after kwh) in the else-if structure with the same "sTypeKwh" type and a simple division? It may solve 1/3 of the current Shelly issues with Domoticz MQTT AD.

**Comment by gizmocuz** [comment]
Looking in the config above, both have 'unit_of_meas' as kwh, so we cannot detect wh
Why is a shelly not reporting the value as kWh when it says the unit is kWh?
No idea why it is reporting in Wm or Wh and use a template? Maybe you could ask them not to do so?

If you can post the complete config object here, I can have a look if I can do something with the detection of /60000 or /1000
But best to get reported what needs to be reported and that is kWh

Domoticz does not support Wh and Wm

**Comment by enesbcs** [comment]
> Looking in the config above, both have 'unit_of_meas' as kwh, so we cannot detect wh 

These were only examples. If "unit_of_meas": "Wh" (and Wm) will be supported in Domoticz, than the division (and templates) is not necessary for this config object.

> Why is a shelly not reporting the value as kWh when it says the unit is kWh? No idea why it is reporting in Wm or Wh and use a template? Maybe you could ask them not to do so?

The unit which shelly reports is actually not kWh, but watt-minute or watt-hour, we need to translate it to kWh, as it is the standard Domoticz device for energy reporting, i think.

> If you can post the complete config object here, I can have a look if I can do something with the detection of /60000 or /1000 But best to get reported what needs to be reported and that is kWh

-Example1:
Shelly1 PM reports an incrementing energy counter in Watt-minute.

Example data:
```
topic: shellies/shelly1pm-ID/relay/0/energy
payload: 465
```

This config will create a Custom sensor, as Wm (watt-minute) unit is not supported directly by Domoticz:

```
topic: homeassistant/sensor/shelly1pm-ID-0/energy/config
payload={"name": "shelly1pm-ID Energy 0", "~": "shellies/shelly1pm-ID/", "stat_t": "~relay/0/energy", "uniq_id": "shelly1pm-ID-energy-0", "qos": 0, "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wm"}
```

This config will create a pTypeGeneral/sTypeKwh sensor, but incoming values needs to be divided by 60000:

```
topic: homeassistant/sensor/shelly1pm-ID-0/energy/config
payload={"name": "shelly1pm-ID Energy 0", "~": "shellies/shelly1pm-ID/", "stat_t": "~relay/0/energy", "uniq_id": "shelly1pm-ID-relay-energy-0",  "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "kWh", "val_tpl": "{{ value |float/60000 }}"}
```

**-Example2:**

ShellyPro 3EM returns total energy as "Wh" as per the documentation:
_a_total_act_energy: [number] Total active energy on phase A, Wh_

Example data:
```
topic: shellypro3em-ID/status/emdata:0
payload: {"id":0,"a_total_act_energy":22293.56,"a_total_act_ret_energy":17.92,"b_total_act_energy":2.76,"b_total_act_ret_energy":0.00,"c_total_act_energy":443743.43,"c_total_act_ret_energy":286.07,"total_act":466039.75, "total_act_ret":304.00}
```

This is the default config:
```
topic: homeassistant/sensor/shellypro3em-ID-A/energy/config
payload: {"name": "shellypro3em-ID Phase A Total Active Energy", "~": "shellypro3em-ID/", "stat_t": "~status/emdata:0", "uniq_id": "shellypro3em-ID-A-energy", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{ value_json.a_total_act_energy }}"}
```

But as "Wh" unit is not supported by Domoticz, a pTypeGeneral/sTypeCustom device is created which is not exactly what the users expects:
https://github.com/enesbcs/shellyteacher4domo/issues/21

Instead they want to see a nice pTypeGeneral/sTypeKwh device, with every value divided by 1000:

```
topic: homeassistant/sensor/shellypro3em-ID-A/energy/config
payload: {"name": "shellypro3em-ID Phase A Total Active Energy", "~": "shellypro3em-ID/", "stat_t": "~status/emdata:0", "uniq_id": "shellypro3em-ID-A-energy", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "kWh", "val_tpl": "{{ value_json.a_total_act_energy |float/1000 }}"}
```

"|float/1000" is the standard HA terminology for division by 1000 with floating point result, i've seen that HA MQTT autodiscovery users uses the above config objects for their Shelly devices.

**Comment by gizmocuz** [comment]
Sorry, did not know you had a github project converting the shelly to mqtt-ad

Sure,Domoticz can support Wh and/or Wm, I see no problem with this

We just translate it back to our kWh sensor, no need for an additional sensor at all

Edit:
Is there also a Watt ("w") sensor reported? And if so, can you also post the discovery topic+payload?

**Comment by gizmocuz** [comment]
@enesbcs , is it possible for you to try beta 15526 ? Domoticz should now support Wh and Wm directly...

**Comment by gizmocuz** [comment]
@enesbcs , I am trying your script (new version) from

https://github.com/enesbcs/shellyteacher4domo

Maybe it's a good idea to specify you need to install the mqtt library in the readme.md

I tested with a Shelly EM and it seems to work out of the box, there is no need to use a val_tpl anymore
The total/total_returned/energy the Shelly reports in Wh, I see here a template with a /60

 "val_tpl": "{{(value|float/60)|round(2)}}"

which is not needed

There is another value you could add, the Power Factor (pf) which can be from -1.0 till 1.0, maybe a custom sensor?

**Comment by gizmocuz** [comment]
For the relay, could you change the binary_switch to 'switch' type? As also normal power plugs have?

**Comment by enesbcs** [comment]
Thank you i will test it ASAP!

I will alter templates to use Wm and Wh after the test.
Sure, i can add Power factor also, a simple custom sensor will be fine.

Yes, i am trying to add Shellies to Autodiscovery, originally i added my own shellies to Domoticz AD manually but then i've created a script with a user editable template file to make it easier. 

In the readme there is a "pip3 install paho-mqtt" command which installs mqtt library on Linux. Which library do you use? In the windows binary release, the mqtt library is included inside.

**Comment by enesbcs** [comment]
> Edit: Is there also a Watt ("w") sensor reported? And if so, can you also post the discovery topic+payload?

Yes, i created the following config for the Watt sensor:

```
topic: homeassistant/sensor/shellypro3em-ID-A/power/config
payload: {"name": "shellypro3em-ID Phase A Active Power", "stat_t": "~status/em:0", "uniq_id": "shellypro3em-ID-A-power", "~": "shellypro3em-ID/", "dev_cla": "power", "stat_cla": "measurement", "unit_of_meas": "W", "val_tpl": "{{ value_json.a_act_power }}"}
```

Example data:
```
topic: shellypro3em-ID/status/em:0
payload: {"id": 0, "a_act_power": 20.0, "a_aprt_power": 20.5, "a_current": 0.144, "a_pf": 1.0, "a_voltage": 238.6}
```

**Comment by enesbcs** [comment]
Thank you, i've downloaded latest beta Domoticz and Wh and Wm also creates a kWh device!
Now i will review the two template file and change units of measurement and/or template where needed in shellyteacher4domo.

**Comment by enesbcs** [comment]
> I tested with a Shelly EM and it seems to work out of the box, there is no need to use a val_tpl anymore The total/total_returned/energy the Shelly reports in Wh, I see here a template with a /60
> 
> "val_tpl": "{{(value|float/60)|round(2)}}"
> 
> which is not needed
> 
> There is another value you could add, the Power Factor (pf) which can be from -1.0 till 1.0, maybe a custom sensor?

I updated the mqtt_templates.txt, removed unnecessary divisions and added Power Factor to Gen1 Shelly EM. 
Thank you again for supporting these!

**Comment by enesbcs** [comment]
I checked the MQTTAutoDiscover.cpp and i see this conversion:

```
		float multiply = 1000.0F; //kWh
		if (szUnit == "wh")
			multiply = 1.0F;
		else if (szUnit == "wm")
			multiply = 1.0F / 60000.0F;
```

I guess the kWh Domoticz device internally stores the value as Wh... the "wm" shouldn't be /60 instead of /60000 ?

60000 Wm = 1000 Wh = 1kWh
60 Wm = 1 Wh

**Comment by gizmocuz** [comment]
> 60000 Wm = 1000 Wh = 1kWh
> 60 Wm = 1 Wh
> 

Yep your right here, changed in beta 15530

**Comment by enesbcs** [comment]
I think we can close this issue now, as it is solved! Thanks!

**Comment by gizmocuz** [comment]
Great thanks for testing!
