### ISSUE TITLE
Missing devices after upgrade to  2023.2 (build 15528)

### ISSUE THREAD

**Issue by ayasystems** [domoticz/domoticz#5813]
### Issue Guidelines

Version: 2023.2 (build 15528)
Build Hash: 954e217e2
Compile Date: 2023-09-07 10:19:26
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

After upgrade domoticz from Version: 2023.1 (build 15223) to 2023.2 (build 15528) and some devices are not showed in dashboard, for example "Garaje2"

![image](https://github.com/domoticz/domoticz/assets/7864168/1f889ee9-9349-494a-bbcf-b78babfecd8d)

Getting devices list with http://192.168.3.241/json.htm?type=command&param=getdevices

[getdevices.zip](https://github.com/domoticz/domoticz/files/12549908/getdevices.zip)

![image](https://github.com/domoticz/domoticz/assets/7864168/dc2261e5-c9c9-44df-978d-9d56616ef87f)

Iota-* Devices is not showed also... I lost 20 or 30 devices 

I check with private mode and the same result

**Comment by gizmocuz** [comment]
This has been reported before and also on the forum.
Check Settings->Users to see if you have multiple admin accounts, if yes, delete all except one.
Also select the admin or user you are logging in with and check if you have specified specific devices

**Comment by ayasystems** [comment]
I'm sorry for duplicate the issue

You are right, I've two admin users, i don't know why....

After fix it all is working fine.... Thanks!!!
