### ISSUE TITLE
updateCurrent not triggering onCommand in python plugin

### ISSUE THREAD

**Issue by jgaalen** [domoticz/domoticz#5814]
When in dzVents the .updateCurrent() is executed, it doesn't trigger the onCommand function in a python plugin. I have tried the latest version (8 sep 2023) but still nothing.

So I have a 'Current (Single)' TypeName device. I expect the onCommand function to be triggered when a dzVents scripts tried to update the device with the .updateCurrent(10). The function updates the device, that works perfectly, but if the plugin doesn't get a trigger I cannot send the new value to the physical device.

**Comment by waltervl** [comment]
If you update the current with a JSON API call will it trigger the onCommand?

Is your plugin legacy (Domoticz) or new framework (DomoticzEx)?

**Comment by jgaalen** [comment]
I've tried tie JSON API like this: /json.htm?type=command&param=udevice&idx=28&nvalue=0&svalue=8   it didn't triggered the onCommand
I've tried .setState(8) with dzVents and it did trigger the onCommand

I'm not aware of the DomoticzEx so I guess I'm using the legacy ;)

**Comment by waltervl** [comment]
It seems a little strange to update a sensor like a current sensor from dzvents that is managed by a plugin. Normally the plugin does the updating. Only commands that come from the user interface like switching On/Off, set color, brightness etc should be triggering the plugin to parse it through to the hardware. 

As the Dzvents documentation states that setState() is used for switch like devices, a current sensor is not a switch. 

Perhaps explain the use case in the forum instead of this bug fixing issue list....

**Comment by jgaalen** [comment]
So its not a sensor, but the current/amp setting for a car charger. The .updateCurrent() seem to be the method to change the current.

so from domoticz via a dzvents script I like to update the current/amp value, so the plugin can send the new current value to the physical device.
How would you recon to do this?

I am writing a plugin for a tesla wall charger so I can modify the current to increase/lower the watts put into the car

**Comment by gizmocuz** [comment]
So from one script system you want to trigger another script system?
I don’t think this is possible as you could create a infinite loop

**Comment by jgaalen** [comment]
A dzvents scripts triggers another script all the time isnt it? I’m confused, i have tons of dzvents which triggers commands in python plugins. How else would you trigger a command and interact natively with external devices which is interfaced by a plugin?

for sure it is possible, right now i am using the .setState() method which is a bit hacky. The updateCurrent() is specifically made to update such value

**Comment by gizmocuz** [comment]
Normally real hardware gets updated and you catch the update in a event system (dzvents/python)
I never tested a update via dzvents that triggered again the event system
Imagine you catch a update on a current sensor and in this event you set it to another value that will again trigger that event setting another value that would again trigger the event that ….

**Comment by jgaalen** [comment]
Again, its not a sensor but a setting.

tell me how you would send the wanted current to the device, as all the logic to interface with the device is in the plugin

look at it as it is a setpoint value

**Comment by waltervl** [comment]
You can use a selector switch with prefixed settings eg 2,4,6,8,16,32 for this or (mis)use a thermostat device. There is currently no other set device available.

There is an enhancement request for creating a custom set device (like a thermostat). https://github.com/domoticz/domoticz/issues/5649

**Comment by waltervl** [comment]
Closing this question as expected functionality is already in an enhancement request.
