### ISSUE TITLE
enphase envoy with lan interface to low watt limit

### ISSUE THREAD

**Issue by anno006** [domoticz/domoticz#5816]
What is the problem, the discription is really simple

For some uninderstandable reason is there a limit for the production solar energie, the limit is 6000W above this and the Enphase kWh Production and Enphase net-consumption stop working wit hthe error in log, "Error: Enphase: Power usage to high/low! Usage: 15000 Watt. Max Usage configured: 6000. (NodeID: ...)

Why is there a limit for production solar energie in the plugin. And can it get higher, say 20000 watt or even more?!

**Comment by gizmocuz** [comment]
@anno006 , not sure what your problem is, but did you check the Meter settings? You can change the limit in here.
Setup->Settings->Meters/Counter, Max. Power

**Comment by anno006** [comment]
O_O!!!!!!!! the first time in al those years that i needid to change this setting!!!!!! Never ever did i came up that this setting 
had to do with with the enphase sensors. And indeed it was 6000 watt, now it is 40000 watt!

**Comment by gizmocuz** [comment]
Glad it's working for you!
