### ISSUE TITLE
2023.2 Stable image for Linux (X86_64) does not create Config folder

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#5819]
When installing stable domoticz with sudo bash -c "$(curl -sSfL https://install.domoticz.com)" the image does not install the domoticz/Config folder giving issues with for example OpenZwave

On https://www.domoticz.com/downloads/  it is also changed on 8 august 2023 which seems strange.
When downloading with command below there is no Config folder in the tar.
`wget -O domoticz_release.tgz "https://www.domoticz.com/download.php?channel=release&type=release&system=linux&machine=x86_64"`

When downloding  the aarch64 image the tar contains the data for Config folder.

See also forum discussion https://www.domoticz.com/forum/viewtopic.php?t=40761

**Comment by waltervl** [comment]
@gizmocuz download date modified today. Seems to be resolved?

**Comment by gizmocuz** [comment]
@waltervl , sorry I forgot to mention here that I corrected it! In the build script the copy action of the config folder was missing

**Comment by Olifant1990** [comment]
Config can be removed right?
OpenZwave has been removed?

**Comment by waltervl** [comment]
Not in 2023.2 stable.
