### ISSUE TITLE
Managed counter acts weird in 2023.2

### ISSUE THREAD

**Issue by jeroen-80** [domoticz/domoticz#5820]
I'm using managed counters for cumulative prices. So I add hourly costs, the dashboard shows the total.

Since my update to 2023.2 something weird is happening. The widget (in dashboard and utility) doesn't show the **total** value but the **last added** value. However the data in utility -> log is correct, both last 24h and historical.

Another thing that changed (I don't mind but perhaps related?): the bars for last 24h are small spikes instead of bars. But as mentioned, the values are correct.

Any clues about what's going on?
![managed-counter](https://github.com/domoticz/domoticz/assets/1997125/73ead80e-2de1-4c94-8de5-bac6b5fba186)

**Comment by jeroen-80** [comment]
Maybe related?

Setup -> hardware -> create virtual sensor -> name:<whatever>, sensor type:"managed counter" = "Problem creating Sensor!"

However the device **is** created. No error messages for other sensor types.

More weirdness: after this action managed counter "Total today" shows the correct total value, other managed counter "Electric totday (raw)" shows the latest value instead of total. Huh? The issue moved from one managed counter to another, after adding a new managed counter that generated an error message. Off by one error somewhere?
![domoticz2](https://github.com/domoticz/domoticz/assets/1997125/ee3be46a-10b3-4f3d-89ca-456d2ac52fd8)

**Comment by waltervl** [comment]
Please check on latest beta as some managed counter issues are repaired there.
Also it could be you did not clear your browser cache after the update, so better try that first (or open Domoticz User interface in a private/incognito browser session)

**Comment by jeroen-80** [comment]
Cache was not the issue. Beta 2023.2.15535 fixed the problem. Thanks for the quick help! And looking forward to a stable release with this fix :)
