### ISSUE TITLE
Switch with same ID as a scene shown on selected room in dashboard

### ISSUE THREAD

**Issue by megamisan** [domoticz/domoticz#5821]
Version: 2023.2 (build 15535)
Build Hash: 101b52605
Compile Date: 2023-09-11 13:18:12
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
Using docker image on x64.

----

I have a LightSwitch with id `n`. I also have a scenario which also got id `n`. I created a room entry and added the scenario to it. Its entry is correctly prefixed with "[Scene]".
When displaying dashboard and selecting the room, both lightswitch and scenario are shown. Only the scenario is expected.

----

Here what I got, with non relevant data blurred. On last screen "Son salon" should not be displayed.
![Device list](https://github.com/domoticz/domoticz/assets/12088094/54765103-674a-450c-81ce-be3931062253)
![Room](https://github.com/domoticz/domoticz/assets/12088094/cabe8b7e-fd11-434b-8785-f2b37f3d0fad)
![Dashboard with room selected](https://github.com/domoticz/domoticz/assets/12088094/fb41cb6e-6069-4737-be98-b4a68145fe64)

**Comment by gizmocuz** [comment]
I am unable to reproduct this

This is the SQL query that is being used for the devices, you need to change the planid with the correct number
You can use SQLite Expert Personal edition as editor

SELECT A.ID, A.DeviceID, A.Unit, A.Name, A.Used,
						 A.Type, A.SubType, A.SignalLevel, A.BatteryLevel,
						 A.nValue, A.sValue, A.LastUpdate, A.Favorite,
						 A.SwitchType, A.HardwareID, A.AddjValue,
						 A.AddjMulti, A.AddjValue2, A.AddjMulti2,
						 A.LastLevel, A.CustomImage, A.StrParam1,
						 A.StrParam2, A.Protected, B.XOffset, B.YOffset,
						 B.PlanID, A.Description,
						 A.Options, A.Color 
						FROM DeviceStatus as A, DeviceToPlansMap as B 
						WHERE (B.PlanID==28) AND (B.DeviceRowID==a.ID)
						 AND (B.DevSceneType==0) ORDER BY B.[Order]

**Comment by gizmocuz** [comment]
No feedback, closing issue
