### ISSUE TITLE
Semi colon makes lua scripts saved partially

### ISSUE THREAD

**Issue by Adi3000** [domoticz/domoticz#5823]
h2. Actual version : 

Dockerized version on docker hub as below
```
Version: 2023.2 (build 15457)
Build Hash: 25624ca14
Compile Date: 2023-07-22 10:39:06
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

Hello, 

I've updated my 2022.2 Domoticz with preloaded scripts. I loaded them through docker since my last upgrade 
Here my docker script : 
```
docker run \
        --rm --name $DOMOTICZ_SERVICE \
        -v /home/domoticz/domoticz/userdata:/opt/domoticz/userdata:rw \
        -v /home/domoticz/domoticz/data:/opt/domoticz/data:rw  \
        -e "HOME=/opt/domoticz/data" \
        -p $DOMOTICZ_PORT:8080 domoticz/domoticz:2023.2 \
        /opt/domoticz/domoticz -noupdates -sslwww 0 -dbase /opt/domoticz/data/domoticz.db
```

So script are in `/opt/domoticz/userdata/scripts/dzVents/generated_scripts/`

All scripts were fine until I made a change in one of them : 
here my script : https://github.com/Adi3000/my-scripts/blob/8eef39cd9baf4c455940cac833f90ae464c882da/domoticz/dzVents/generated_scripts/IPX800%20Sync.lua#L4

When I made the change, file was cut at line 4.
Then I removed the `;` and now it stuck at line 43 
```
    		local s = split(device.sValue, ';')
```

It seems that there may be an interpretation of semi-colon in the lua script loading.

**Comment by Adi3000** [comment]
For now i changed all my delimiter with comma, and it works but it my be a security failure.  I may be able to take in charge this issue (maybe during hacktoberfest Event : https://hacktoberfest.com if your repository will be eligible)

**Comment by gizmocuz** [comment]
@Adi3000 , thank you for your report. Sure you may make changes when you have time.
Unfortunately I do not 100% what/where it goes wrong...

You have a semicolon in the filename?
Sure a semicolon can be used inside script.... so that's not what you mean....

**Comment by Adi3000** [comment]
I don't understand why this is happening here my scenario : 
I was in Domoticz 2022.2 (maybe 2022.1) last time I touched this script
Then, I migrated lastly in docker environment using the 2023.2 (build 15457) from your domoticz docker
Last week I had to change something in the script, then when I saved it/updated it, it was truncated after `;` (as I suppressed the first `;`, then it was erased after a second `;`)
My first guess is that it may be due to a cache of script content (in database or in memory cache). Is there something like that ? Something which read the file and try to write somewhere and then break will writing ?

**Comment by Adi3000** [comment]
Sorry : to answer the question my file was `IPX800 Sync.lua` which I renamed `IPX800_Sync.lua` (with no effects)

**Comment by gizmocuz** [comment]
We changed the script saving to a HTTP Post recently.
Could you clear your browser cache and try again with the latest beta version?

**Comment by Adi3000** [comment]
Indeed it works with : 
```
Version: 2023.2 (build 15563)
Build Hash: aefbcf6a8
```

**Comment by gizmocuz** [comment]
Great! Yes, that is why when you created the issue and have read the guidelines it mentioned:

"First try to update to the latest beta version"

👌😎
