### ISSUE TITLE
MQTT AD: light device brightness

### ISSUE THREAD

**Issue by enesbcs** [domoticz/domoticz#5824]
I've tested with the latest beta, but i think the light device brightness capability has a little problem.

Configuration

```
homeassistant/light/ShellyVintage-1E121D-0/config

{
  "name": "ShellyVintage-1E121D Light 0",
  "cmd_t": "~light/0/set",
  "stat_t": "~light/0/status",
  "payload_on": "{\"turn\":\"on\"}",
  "payload_off": "{\"turn\":\"off\"}",
  "stat_val_tpl": "{{value_json.ison}}",
  "val_tpl": "{{value_json.ison}}",
  "brightness_command_topic": "~light/0/set",
  "brightness_state_topic": "~light/0/status",
  "bri_val_tpl": "{{value_json.brightness}}",
  "brightness": true,
  "color_mode": true,
  "supported_color_modes": [
    "brightness"
  ],
  "brightness_scale": 100,
  "uniq_id": "ShellyVintage-1E121D-light-0",
  "~": "shellies/ShellyVintage-1E121D/"
}
```
Switching On and Off are working, also when changing the Dimmer percentage in Domoticz it sends proper json (for ex {"brightness": 38}) commands to the device, and it works.
But when the brightness changes on the device itself and reports itself to the Domoticz, percentage doesn't updated.

Example status report from device:

```
shellies/ShellyVintage-1E121D/light/0/status

{
  "ison": true,
  "source": "http",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "brightness": 38,
  "transition": 0
}
```

I think the "brightness_value_template" alias "bri_val_tpl" is not working, although its declared in 
https://github.com/domoticz/domoticz/blob/development/hardware/MQTTAutoDiscover.cpp

To check my assumption i've simulated manually the following input:
```
topic: shellies/ShellyVintage-1E121D/light/0/status
payload: 38
```
And the Domoticz dimmer percentage changed to 38%. But Shellies reports data in JSON...

**Comment by gizmocuz** [comment]
Thanks for reporting!
I think I found the problem, but just to be sure, could you also send the status update when the light is turned on and off
This because the payload_on value = **"{\"turn\":\"on\"}"** and payload_off = **"{\"turn\":\"off\"}"**
I find that a bit strange as in the status there is a boolean for "ison"
I would have expected something like payload_on value = **"true"** 

Then again, because the brightness is checked it will be automatically set correct

brightness = 0 = off, brightness = 100 = on, else set_level

**Comment by enesbcs** [comment]
Thanks for your answer! 
I altered payloads because turn:on is the standard command for turning on a Shelly Gen2 device. For some reason the result is ison:false/true... :D

I did some tests with the Dimmer teached with the config object above. I tried it in multiple scenarios.

I/ Driving dimmer device from its own webGUI
--------------------------------------------
The ON and OFF state has been sensed by the Domoticz, but the brightness was not.

Changing brightness to 44% on the device itself, arrived status:

```
shellies/ShellyVintage-1E121D/light/0/status
{
  "ison": true,
  "source": "http",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "brightness": 44,
  "transition": 0
}

shellies/ShellyVintage-1E121D/light/0
on
```
**RESULT:**
Domoticz device "Light 0" state changed to ON, brightness is undefined.

In the same time i see this in the Domoticz log:

```
Debug: mqttad: topic: shellies/ShellyVintage-1E121D/light/0/status, message: {"ison":true,"source":"http","has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"brightness":44, "transition":0}
Debug: Query:SELECT ID, Name, nValue, sValue, Color, SubType, SwitchType FROM DeviceStatus WHERE (HardwareID==2) AND (DeviceID=='ShellyVintage-1E121D-light-0') AND (Unit==1)
Debug: Query:SELECT ID, Name, Used, SwitchType, nValue, sValue, LastUpdate, Options FROM DeviceStatus WHERE (HardwareID=2 AND DeviceID='ShellyVintage-1E121D-light-0' AND Unit=1 AND Type=241 AND SubType=2)
Debug: Query:UPDATE DeviceStatus SET SignalLevel=12, BatteryLevel=255, nValue=1, sValue='0', LastUpdate='2023-10-04 17:09:12' WHERE (ID = 1)
Debug: Query:INSERT INTO LightingLog (DeviceRowID, nValue, sValue, User) VALUES ('1', '1', '0', 'mqttad')
```

Switching Vintage Bulb to off at the device side, mqtt status messages:

```
shellies/ShellyVintage-1E121D/light/0/status
{
  "ison": false,
  "source": "http",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "brightness": 44,
  "transition": 0
}

shellies/ShellyVintage-1E121D/light/0
off
```

**RESULT:**
Domoticz device "Light 0" state changed to OFF, brightness is still undefined.

```
Debug: mqttad: topic: shellies/ShellyVintage-1E121D/light/0/status, message: {"ison":false,"source":"http","has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"brightness":44, "transition":0}
Debug: Query:SELECT ID, Name, nValue, sValue, Color, SubType, SwitchType FROM DeviceStatus WHERE (HardwareID==2) AND (DeviceID=='ShellyVintage-1E121D-light-0') AND (Unit==1)
Debug: Query:SELECT ID, Name, Used, SwitchType, nValue, sValue, LastUpdate, Options FROM DeviceStatus WHERE (HardwareID=2 AND DeviceID='ShellyVintage-1E121D-light-0' AND Unit=1 AND Type=241 AND SubType=2)
Debug: Query:UPDATE DeviceStatus SET SignalLevel=12, BatteryLevel=255, nValue=0, sValue='0', LastUpdate='2023-10-04 17:17:17' WHERE (ID = 1)
Debug: Query:INSERT INTO LightingLog (DeviceRowID, nValue, sValue, User) VALUES ('1', '0', '0', 'mqttad')
```

II/ Driving dimmer device from Domoticz GUI
------------------------------------------

When i press simple ON in Domoticz, it sends the correct command:

```
shellies/ShellyVintage-1E121D/light/0/set
{
  "turn": "on"
}

```
The status messages arrived was:

```
shellies/ShellyVintage-1E121D/light/0/status
{
  "ison": true,
  "source": "mqtt",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "brightness": 91,
  "transition": 0
}

shellies/ShellyVintage-1E121D/light/0
on

```
When i set it OFF in Domoticz, it also sends the correct command:

```
shellies/ShellyVintage-1E121D/light/0/set
{
  "turn": "off"
}
```

The status arrived is:

```
shellies/ShellyVintage-1E121D/light/0/status  
{
  "ison": false,
  "source": "mqtt",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "brightness": 91,
  "transition": 0
}

shellies/ShellyVintage-1E121D/light/0
off
```

When i am using the Domoticz dimmer bar to change brightness, (when it is in ON state previously), than it is working OK:

```
shellies/ShellyVintage-1E121D/light/0/set
{
  "brightness": 29
}

shellies/ShellyVintage-1E121D/light/0/status
{
  "ison": true,
  "source": "mqtt",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "brightness": 29,
  "transition": 0
}
```

When i choose 31% at Domoticz when it is in OFF state it sends out this command:

```
shellies/ShellyVintage-1E121D/light/0/set
{
  "brightness": 31
}
```

The status arrived as:
```
shellies/ShellyVintage-1E121D/light/0/status
{
  "ison": false,
  "source": "mqtt",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "brightness": 31,
  "transition": 0
}
```

It is still in OFF state physically, as without the "turn": "on" command, the Shelly never turn on itself, does not matter what is the brightness value.

III/ Manual mqtt commands
-------------------------

When i am sending this command MANUALLY through mqtt to ShellyVintage:
```
shellies/ShellyVintage-1E121D/light/0/set
{
  "turn": "on",
  "brightness": 21
}

```
Then it is turning on, setting brightness to 21 and sending this status message:
```
{
  "ison": true,
  "source": "mqtt",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "brightness": 21,
  "transition": 0
}

shellies/ShellyVintage-1E121D/light/0
on

```

**Comment by gizmocuz** [comment]
Is it possible to try beta 15564, it should be solved in this version

**Comment by enesbcs** [comment]
@gizmocuz : I tested it with Domoticz V2023.2 (build 15577) 
Now the "Light 0" device in Domoticz actualizes the Dimmer brightness in Domoticz, but unable to interpret the ON/OFF state anymore. Its not so good, as if the User switches off the "Light 0" in Domoticz, it will turn off, but will never turn on again, as the state in Domoticz leaves turned on logically....

Domoticz log after changing state to ON:
```
Debug: mqttad: topic: shellies/ShellyVintage-1E121D/light/0/status, message: {"ison":true,"source":"http","has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"brightness":34, "transition":0}
Debug: Query:SELECT ID, Name, nValue, sValue, Color, SubType, SwitchType FROM DeviceStatus WHERE (HardwareID==2) AND (DeviceID=='ShellyVintage-1E121D-light-0') AND (Unit==1)
Debug: Query:UPDATE DeviceStatus SET SubType=2 , LastUpdate='2023-10-05 15:23:39' WHERE (ID == 5 )
Debug: Query:SELECT HardwareID, Name From DeviceStatus WHERE (ID == 5 )
Debug: Query:SELECT ID FROM LightSubDevices WHERE (DeviceRowID=='5')
Debug: Query:SELECT ID, Name, Used, SwitchType, nValue, sValue, LastUpdate, Options FROM DeviceStatus WHERE (HardwareID=2 AND DeviceID='ShellyVintage-1E121D-light-0' AND Unit=1 AND Type=244 AND SubType=2)
Debug: Query:UPDATE DeviceStatus SET SignalLevel=12, BatteryLevel=255, nValue=2, sValue='34', LastUpdate='2023-10-05 15:23:39' WHERE (ID = 6)
Debug: Query:SELECT ID FROM DeviceStatus WHERE (HardwareID=2 AND DeviceID='ShellyVintage-1E121D-light-0' AND Unit=1 AND Type=244 AND SubType=2)
```

Domoticz log after changing state to OFF:
```
Debug: mqttad: topic: shellies/ShellyVintage-1E121D/light/0/status, message: {"ison":false,"source":"http","has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"brightness":34, "transition":0}
Debug: Query:SELECT ID, Name, nValue, sValue, Color, SubType, SwitchType FROM DeviceStatus WHERE (HardwareID==2) AND (DeviceID=='ShellyVintage-1E121D-light-0') AND (Unit==1)
Debug: Query:UPDATE DeviceStatus SET SubType=2 , LastUpdate='2023-10-05 15:28:47' WHERE (ID == 5 )

Debug: Query:SELECT ID, Name, Used, SwitchType, nValue, sValue, LastUpdate, Options FROM DeviceStatus WHERE (HardwareID=2 AND DeviceID='ShellyVintage-1E121D-light-0' AND Unit=1 AND Type=244 AND SubType=2)
Debug: Query:UPDATE DeviceStatus SET SignalLevel=12, BatteryLevel=255, nValue=2, sValue='34', LastUpdate='2023-10-05 15:28:47' WHERE (ID = 6)
Debug: Query:UPDATE DeviceStatus SET LastLevel=34 , LastUpdate='2023-10-05 15:28:47' WHERE (ID == 5 )
```

As i see nvalue is 2, in either ON or OFF state, but before the changes it detected 0/1 state at least. 
Cant we achieve brightness and state detection somehow at the same time?

**Comment by gizmocuz** [comment]
I don't see the problem?

If the brightness has a value of 0, it is OFF, if it is 100 it is ON else the status is Set Level

**Comment by gizmocuz** [comment]
From what I understand, this is just a light bulb. You cannot turn this on/off externally. (or can you tap the bulb perhaps?)

When you send a OFF from within Domoticz (or the Shelly Wifi web interface), what is the status json payload?
Is the brightness set to 0?
If yes, then the state in Domoticz should go to OFF

**Comment by enesbcs** [comment]
> From what I understand, this is just a light bulb. You cannot turn this on/off externally. (or can you tap the bulb perhaps?)

I can, as every shelly has a webui on its port 80 and it can be switched on off on it, but this is for testing only. There are also Shelly Dimmer devices which has manual inputs for on-off-brightness. The payloads are the same for all shelly dimmer devices, so i chose a bulb.

> When you send a OFF from within Domoticz (or the Shelly Wifi web interface), what is the status json payload? Is the brightness set to 0? If yes, then the state in Domoticz should go to OFF

As i wrote in https://github.com/domoticz/domoticz/issues/5824#issuecomment-1747342250

When i send OFF from Domoticz, which sends out the correct MQTT command:
```

shellies/ShellyVintage-1E121D/light/0/set
{
  "turn": "off"
}
```

Then this is the status update from the bulb:

```
shellies/ShellyVintage-1E121D/light/0/status  
{
  "ison": false,
  "source": "mqtt",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "brightness": 91,
  "transition": 0
}
```
As you see the brightness is untouched only the "ison" state is changed.

**Comment by enesbcs** [comment]
> I don't see the problem?

The problem is that Domoticz does not sensing the status after this fix.
 
> If the brightness has a value of 0, it is OFF, if it is 100 it is ON else the status is Set Level

As i see the brightness will never be 0 at the Shelly side. Tried to set it to 0%, but i am unable to set it below 1%, Brightness and On/Off Status are totally independent .

Another problem after commit
https://github.com/domoticz/domoticz/commit/051b6ca5d0ec0f45362be9c03ce42faa00db86e6
Domoticz tries to send "brightness": value command to turn on a shelly dimmer from OFF state... which will never work, as "turn":"on" is the only command which can do that, this is the reason why i wrote that into payload_on

**Comment by enesbcs** [comment]
I've created another config object, using the legacy way to switch on/off the device. (And using json only for brightness.)

```
homeassistant/light/ShellyVintage-1E121D-1/config
{
  "name": "ShellyVintage-1E121D Light 1",
  "cmd_t": "~light/0/command",
  "stat_t": "~light/0",
  "payload_on": "on",
  "payload_off": "off",
  "brightness_command_topic": "~light/0/set",
  "brightness_state_topic": "~light/0/status",
  "brightness": true,
  "color_mode": true,
  "supported_color_modes": [
    "onoff",
    "brightness"
  ],
  "brightness_scale": 100,
  "bri_val_tpl": "{{value_json.brightness}}",
  "avty_t": "~online",
  "pl_avail": "true",
  "pl_not_avail": "false",
  "uniq_id": "ShellyVintage-1E121D-light-1",
  "qos": 0,
  "~": "shellies/ShellyVintage-1E121D/"
}
```

It partially works, but internal Domoticz state always goes back to ON after arrival of a status update, as brightness is never 0. 
If ON/OFF state and brightness can work independently this method may work.

OFF state example status report:

```
topic: shellies/ShellyVintage-1E121D/light/0
payload: off

topic: shellies/ShellyVintage-1E121D/light/0/status  
payload: {
  "ison": false,
  "source": "mqtt",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "brightness": 91,
  "transition": 0
}
```

ON state example status report:
```
topic: shellies/ShellyVintage-1E121D/light/0
payload: on

topic: shellies/ShellyVintage-1E121D/light/0/status  
payload: {
  "ison": true,
  "source": "mqtt",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "brightness": 91,
  "transition": 0
}
```

**Comment by gizmocuz** [comment]
In you last config object there is no reference to ison (state template) so the state would never work
The state is in ison
Can you also send true/false instead of on/off as command payload?

**Comment by enesbcs** [comment]
> In you last config object there is no reference to ison (state template) so the state would never work The state is in ison Can you also send true/false instead of on/off as command payload?

Sorry for confusion, i let go "turn":"on" versus "ison":"true" completely as i am afraid it will not work without "funny" templates. If you have a viable idea about it, i am curious, but i am out of ideas.
"shellies/ShellyVintage-1E121D/light/0/status" returns a complete JSON which include "brightness", but as you see my last config object not uses "ison" anymore. As there are another source of current state.

https://shelly-api-docs.shelly.cloud/gen1/#shelly-vintage-mqtt

In my last config object i used instead topic "shellies/ShellyVintage-1E121D/light/0" which returns "on" when in ON state and "off" when in OFF state. And as i wrote, it is working, Domoticz is able to detect state changes, but incoming "brightness" overwrites Domoticz OFF state constantly with ON, which is not good.

Command topic also changed to "shellies/ShellyVintage-1E121D/light/0/command" which accepts simple "on" and "off".
In the meantime brightness topic remains "shellies/ShellyVintage-1E121D/light/0/status" which returns a JSON with brightness value only, and they are working independently.

**Comment by gizmocuz** [comment]
Yep, this is not going to work, as you receive a on/off on shellies/ShellyVintage-1E121D/light/0 'And' a json status update and this will overwrite the simple on/off
So, you really have to use the 'ison' field to determine that it's On or Off
I think we need to use a status template...
I will try to have a good look at this, else we need to drop brightness receiving support as it's more important to have the on/off state correct, and you do not fiddle with the brightness all the time ..

**Comment by enesbcs** [comment]
I get your point, so i slightly modified the first config object:

```
homeassistant/light/ShellyVintage-1E121D-0/config
{
  "name": "ShellyVintage-1E121D Light 0",
  "cmd_t": "~light/0/set",
  "payload_on": "{\"turn\":\"on\"}",
  "payload_off": "{\"turn\":\"off\"}",
  "stat_t": "~light/0/status",
  "stat_val_tpl": "{{value_json.ison}}",
  "val_tpl": "{{value_json.ison}}",
  "state_on": "true",
  "state_off": "false",
  "brightness_command_topic": "~light/0/set",
  "brightness_state_topic": "~light/0/status",
  "bri_val_tpl": "{{value_json.brightness}}",
  "brightness": true,
  "color_mode": true,
  "supported_color_modes": [
    "onoff",
    "brightness"
  ],
  "brightness_scale": 100,
  "avty_t": "~online",
  "pl_avail": "true",
  "pl_not_avail": "false",
  "uniq_id": "ShellyVintage-1E121D-light-0",
  "~": "shellies/ShellyVintage-1E121D/"
}
```

I have added the "state_on" and "state_off" properties, as in theory the "val_tpl" informs Domoticz that the state value is in value_json.ison and the "state_on" and "state_off" represents the ON and OFF value of the status from the status_topic. 

Tried the above, but the Dimmer device in Domoticz still never gone to OFF mode.

**Comment by gizmocuz** [comment]
This is very interesting (state_on/state_off), I never seen this before, but I will implement this!
Report back asap!

**Comment by gizmocuz** [comment]
Yes, that's working! Please try beta 15586 with your last template

**Comment by enesbcs** [comment]
Yes, the Domoticz now detects the Dimmer on/off state!
But somehow its unable to turn on the device anymore... turning off and setting brightness is working. 
But when i press ON button for the Dimmer device in Domoticz, it sends out "brightness" command, which will never turn on a Shelly from OFF state.

**Comment by gizmocuz** [comment]
Hmm, could you test one more thing

could you send to ~light/0/set

to turn on:

```
{
  "ison": true
}
```
to turn off:

```
{
  "ison": false
}
```
and to turn on with a specific brightness

```
{
  "ison": true,
  "brightness": 25,
}
```

If it does not work, you still to configure payload_on="on" and payload_off="off"
and the logic would be

to turn on:

```
{
  "turn": "on"
}
```
to turn off:

```
{
  "turn": "off"
}
```
and to turn on with a specific brightness

```
{
  "turn": "on",
  "brightness": 25,
}
```

and the value_template needs to be

`"val_tpl": "{{ value_json.turn }}"`

So **val_tpl** is used when setting a state and **stat_val_tpl** is used when receiving a state

Would this make sense?

But I do have lot's of temperature sensors that do not contain a stat_val_tpl but only a val_tpl and we need to use the val_tpl

**Comment by enesbcs** [comment]
> Hmm, could you test one more thing
> 
> could you send to ~light/0/set
> 
> to turn on:
> 
> ```
> {
>   "ison": true
> }
> ```
Tried, and not doing anything on the Shelly side.

 
> to turn off:
> 
> ```
> {
>   "ison": false
> }
> ```

Tried and also not doing anything, which is as expected, as "ison" is for reporting only.

I can do more tests if needed but first please answer a question:
Why Domoticz sends out  {"turn":"on"} when pressing ON for the very first time after the Light device creation - when brightness has no value - and why sends out {"brightness" : 31} when pressing ON after getting brightness status? I expect to send payload_on every time when pressing the ON button, and to send brightness only when clicking to the dimmer.
When pressing OFF, Domoticz sends out {"turn":"off"} so the "payload_off" works fine currently.

Is it managed somewhere near line 3412?
https://github.com/domoticz/domoticz/blob/development/hardware/MQTTAutoDiscover.cpp#L3412
(I think maybe line 3427 does this funny thing?)

Or maybe the FGRGBW hack at line 3752?
https://github.com/domoticz/domoticz/blob/development/hardware/MQTTAutoDiscover.cpp#L3752

> and the value_template needs to be
> 
> `"val_tpl": "{{ value_json.turn }}"`
> 
> So **val_tpl** is used when setting a state and **stat_val_tpl** is used when receiving a state
> 
> Would this make sense?

According to HA docs, "value_template" is only for the state_topic and not for the command_topic:

"Defines a template to extract device’s state from the state_topic. To determine the switches’s state result of this template will be compared to state_on and state_off."

When pressing an ON from Domoticz, its expected to write "payload_on" to the "command_topic" directly, without any template.

"state_on" used when value that represents on state in the state_topic is different from value that should be sent to the command_topic to turn the device on.

**Comment by gizmocuz** [comment]
> I can do more tests if needed but first please answer a question:
> Why Domoticz sends out {"turn":"on"} when pressing ON for the very first time after the Light device creation - when brightness has no value - and why sends out {"brightness" : 31} when pressing ON after getting brightness status? I expect to send payload_on every time when pressing the ON button, and to send brightness only when clicking to the dimmer.
> When pressing OFF, Domoticz sends out {"turn":"off"} so the "payload_off" works fine currently.

The reason for this is, that for all other lights we had/have received before, sending the brightness automatically also turned the light on.
Makes also kinda sense... you tell a light, set your brightness to 80%, sure it should know it should turn itself on.

Now, with the payload containing a json value (as a string) and you have brightness, going both to the same command topic, we have a small issue
So when the payload was just on/off, and we have a template, we could send both status (on/off) and the brightness value

I assume this works correctly:

```
{
  "turn": "on",
  "brightness": 25,
}
```

The above turns on the light with the specified brightness?

Whats the difference between **stat_val_tpl** and **val_tpl**  ?

**Comment by enesbcs** [comment]
> The reason for this is, that for all other lights we had/have received before, sending the brightness automatically also turned the light on. Makes also kinda sense... you tell a light, set your brightness to 80%, sure it should know it should turn itself on.

Its a bit strange for me as the only purpose of "payload_on" is to turn a device on, but i believe there are some devices which turn itself on when a brightness command arrives.

I've found an "on_command_type" property in the HA docs

*on_command_type*

Defines when on the payload_on is sent. Using "last" (the default) will send any style (brightness, color, etc) topics first and then a payload_on to the command_topic. Using "first" will send the payload_on and then any style topics. Using "brightness" will only send brightness commands instead of the payload_on to turn the light on.

So i guess currently the Domoticz MQTT AD works exactly like we set "on_command_type": "brightness" on HA. But shellies need the "first" method.

> Now, with the payload containing a json value (as a string) and you have brightness, going both to the same command topic, we have a small issue So when the payload was just on/off, and we have a template, we could send both status (on/off) and the brightness value

It sounds good!

If we are looking for templates for the command topic, there are two of them:
command_on_template, command_off_template

Maybe something like this may work: 
```
"command_on_template": "{\"turn\":\"on\",\"brightness\": {{brightness}}}",
"command_off_template": "{\"turn\":\"off\"}"
```
> I assume this works correctly:
> 
> ```
> {
>   "turn": "on",
>   "brightness": 25,
> }
> ```
> 
> The above turns on the light with the specified brightness?

Yes, you are correct, this payload turns on the shelly dimmer device at 25% percent.
 
> Whats the difference between **stat_val_tpl** and **val_tpl** ?

I think val_tpl is now obsolote and they just renamed to stat_val_tpl:

https://github.com/Koenkk/zigbee2mqtt/issues/11201

**Comment by gizmocuz** [comment]
> > Now, with the payload containing a json value (as a string) and you have brightness, going both to the same command topic, we have a small issue So when the payload was just on/off, and we have a template, we could send both status (on/off) and the brightness value
> 
> It sounds good!

No this does not sound good at all ;) We need to create one json object and send it

I have an idea...

**Comment by gizmocuz** [comment]
Please try beta 15597

When the command-topic and brightness-topic are the same, and the payload_on contains json like:

```
"payload_on": "{\"turn\":\"on\"}"
"payload_on": "{'turn':'on'}"
"payload_on": "\"turn\":\"on\""
"payload_on": "'turn':'on'"
"payload_on": "turn:on"
```

We also add the payload_on to the final to send json object

The problem with this Shelly device is the usage of 'turn' and 'ison'
If they had called it 'state' like almost everyone else, there was no issue or complication

**Comment by enesbcs** [comment]
Thank you for your hard work, the Shelly dimmer device now seems fully operational under Domoticz! :)
Status is updated, and on/off commands works fine, also the dimmer bar in Domoticz works!

[off]
Indeed, the Shelly devices has strange keywords at some places! The RGBW support will be an even harder challenge, pagocs tried to add some support for there, but he is stucked. At least the Dimmers are working now!
[/off]

**Comment by enesbcs** [comment]
Although Dual mode shelly devices like Shelly RGB and 4 channel Shelly RGBW2 needs an extra "mode":"white" to its payload additionally to turn:on.

This is for generic shelly dimmers:
`"payload_on": "{\"turn\":\"on\"}"`

This is for dual mode dimmers:
`"payload_on": "{\"turn\":\"on\",\"mode\":\"white\"}"`

**Comment by enesbcs** [comment]
@gizmocuz i am not so experienced at C++ but based on your patch i tried to add support to mode:white also at 
https://github.com/domoticz/domoticz/blob/d6b835e20c23cf12766dd690ad28265c12927d14/hardware/MQTTAutoDiscover.cpp#L3767

```
					if (pSensor->command_topic == pSensor->brightness_command_topic)
					{
                                           std::string szOnPayload = pSensor->payload_on;
					   CleanValueTemplate(szOnPayload);
					   if (szOnPayload.find(":") != std::string::npos) {
					     if (szOnPayload.find(",") != std::string::npos) {

						std::vector<std::string> strarray1;
						std::vector<std::string> strarray2;
						StringSplit(szOnPayload, ",", strarray1);
						if (strarray1.size() == 2)
						{
						  for (const auto itt : strarray1)
						  {
						    StringSplit(itt, ":", strarray2);
						    if (strarray2.size() == 2)
						    {
							root[strarray2[0]] = strarray2[1];
  						    }
						  }
						}
					      } else {
						std::vector<std::string> strarray;
						StringSplit(szOnPayload, ":", strarray);
						if (strarray.size() == 2)
						{
							root[strarray[0]] = strarray[1];
						}
                                             }
                                           }
					}	
```

**Comment by gizmocuz** [comment]
```
This is for dual mode dimmers:
"payload_on": "{\"turn\":\"on\",\"mode\":\"white\"}"
```

Well that is because I was expecting only one json payload!

Could you please send me a complete config + payload ?

Should not be that hard to implement

**Comment by gizmocuz** [comment]
Please check beta 15600, hope that works ;)

**Comment by enesbcs** [comment]
> ```
> This is for dual mode dimmers:
> "payload_on": "{\"turn\":\"on\",\"mode\":\"white\"}"
> ```
> 
> Well that is because I was expecting only one json payload!

Sorry, my fault, i completely forgot about dual mode dimmers. :(

> Could you please send me a complete config + payload ?

I can, but its working perfectly now! :)

**Comment by enesbcs** [comment]
> Please check beta 15600, hope that works ;)

Thanks, tested beta 15601, normal Shelly dimmers and dual mode dimmers also works perfectly now!

**Comment by Jacobsentertainment** [comment]
Hi all,
Currently running beta 15620 and the feedback of the device to domoticz that on/off state isn't working, the device reacts on all commands from domoticz ecept the actual off state is not.

https://www.domoticz.com/forum/viewtopic.php?p=308262#p308262

Keep up the good work.

**Comment by gizmocuz** [comment]
@Jacobsentertainment ,

just to be sure, controlling the device/bulb/dimmer from Domoticz is working, On/Off/Brightness

But when operating the device by hand, turning it off, the status in Domoticz stays ON
When the device is OFF in Domoticz, and you turn it on by hand, does it go ON or also stays OFF?

Could you post here your config topic+payload, you can get this information by using MQTT Explorer
The config object is in json format, it should contain a state topic
When you turn the device on/off by hand, could you maybe also post here the content of the state json object?

**Comment by Jacobsentertainment** [comment]
The device is fully functional from domoticz, all functions respond as intended with the exception of displaying "off" in domoticz. 
If i set the level in an shelly device the level changes in domoticz and vise-versa. 
(This counts for all shelly dimmable device like shelly buld, dimmer and dimmer2)

I hope I have the correct payload json, 
Shelly Dimmer2
`{"ison":true,"source":"http","has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"mode":"white","brightness":45}`
Shelly bulb 
`{"ison":false,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"brightness":100,"white":35,"temp":4030}`


In domoticz the device is constantly "on" while the device is actually off

**Comment by gizmocuz** [comment]
@Jacobsentertainment , thank you for the information!
Could you also send the payload of

homeassistant/light/xxxxx/config

**Comment by enesbcs** [comment]
> @Jacobsentertainment , thank you for the information! Could you also send the payload of
> 
> homeassistant/light/xxxxx/config

I think he used an older ShellyTeacher script and "state_on" and "state_off" is missing from this config object...

**Comment by gizmocuz** [comment]
I have not seen a config object yet... But @Jacobsentertainment , please try to download the latest ShellyTeacher script and test with that version

**Comment by Jacobsentertainment** [comment]
> I have not seen a config object yet... But @Jacobsentertainment , please try to download the latest ShellyTeacher script and test with that version

I will do so,
`{"name": "shellydimmer2-485519D90A49 Light 0", "cmd_t": "~light/0/set", "stat_t": "~light/0/status","payload_on": "{\"turn\":\"on\"}","payload_off": "{\"turn\":\"off\"}", "value_template": "{{value_json.ison}}","stat_tpl": "{%if value_json.ison==true%}ON{%else%}OFF{%endif%}","brightness_command_topic":"~light/0/set","brightness_state_topic":"~light/0/status","brightness": true,"color_mode": true,"supported_color_modes": ["brightness"], "brightness_scale":100, "bri_val_tpl":"{{value_json.brightness}}", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "uniq_id": "shellydimmer2-485519D90A49-light-0", "qos": 0, "~": "shellies/shellydimmer2-485519D90A49/"}`

**Comment by enesbcs** [comment]
> > I have not seen a config object yet... But @Jacobsentertainment , please try to download the latest ShellyTeacher script and test with that version
> 
> I will do so, `{"name": "shellydimmer2-485519D90A49 Light 0", "cmd_t": "~light/0/set", "stat_t": "~light/0/status","payload_on": "{\"turn\":\"on\"}","payload_off": "{\"turn\":\"off\"}", "value_template": "{{value_json.ison}}","stat_tpl": "{%if value_json.ison==true%}ON{%else%}OFF{%endif%}","brightness_command_topic":"~light/0/set","brightness_state_topic":"~light/0/status","brightness": true,"color_mode": true,"supported_color_modes": ["brightness"], "brightness_scale":100, "bri_val_tpl":"{{value_json.brightness}}", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "uniq_id": "shellydimmer2-485519D90A49-light-0", "qos": 0, "~": "shellies/shellydimmer2-485519D90A49/"}`

Sorry, this is still an older config object. 
Please try to download mqt_templates.txt directly into your actual folder:

https://raw.githubusercontent.com/enesbcs/shellyteacher4domo/main/mqtt_templates.txt

I've published a new binary release with current templates.txt also:
https://github.com/enesbcs/shellyteacher4domo/releases/tag/0.05

**Comment by Jacobsentertainment** [comment]
@enesbcs 
Just updated to latest, isn't that enough? If not ill copy the config no problem. 

Next step will be deleting all those dimmer devices and ad the to domoticz again, correct?
Sheers for the help

**Comment by enesbcs** [comment]
> @enesbcs Just updated to latest, isn't that enough? If not ill copy the config no problem.
> 
> Next step will be deleting all those dimmer devices and ad the to domoticz again, correct? Sheers for the help

If you are downloaded v0.4 binary release, it contains an earlier .TXT. If you do not find "state_on" and "state_off" in mqtt_templates.txt you are using an old one, and it will produce the same old config object, until you download an actual template file.

**Comment by Jacobsentertainment** [comment]
I updated to 0.5 
Ill delete the dimmers and teach them again, ill get back to this topic.

**Comment by Jacobsentertainment** [comment]
Cheers, that did the trick!
I was assuming that it wouldn't matter as teacher isn't running while devices are already added to domoticz, same as for an update. But now it makes sense, I got about 24 devices to delete, add and change all the dzvent script that have those numbers in there scripts pfffffff there goes my evening :-)

**Comment by enesbcs** [comment]
> Cheers, that did the trick! I was assuming that it wouldn't matter as teacher isn't running while devices are already added to domoticz, same as for an update.

You are right: generally teacher does not have to run after the teaching process _unless_ the config object was changed in the meantime, as in this case.

Sorry, it was inevitable, as Domoticz MQTT AD implementation changed to support Allterco engineers weird naming schemes, see "turn" vs "ison", to make the state and brightness work in the same time.

Why dont you use Device names instead of IDX in dzvent scripts?
