### ISSUE TITLE
Aeotec Siren 6 No siren switches Domoticz

### ISSUE THREAD

**Issue by rap27** [domoticz/domoticz#5826]
I asked my question on the domoticz forum, they referred me to Zwave JS
there they indicate that HA also had the same problem and they solved it. They refer me back to Domoticz and that is why I am trying to get solved the problem here.

Before I received the last answer in the topic by zwave js, I also submitted it to MQTT, which I closed. I will provide the links to all topics here for clarity.

I apologize in advance if my question does not belong here, but I am looking for a solution

domotic sets topic (they referred me to zwave js)
https://www.domoticz.com/forum/viewtopic.php?p=307028#p307028

github zwavejs ui  (they referred me to domoticz)
https://github.com/zwave-js/zwave-js-ui/issues/3298

I work with Domoticz everything works in docker-compose and works well
domoticz. Version 2023.2 build 15457
MQTT. Version 2.0.18
szwen js ui. zwave-js-ui: 8.26.0.08e6a7e
zwave-js: 11.14.3
homebridge.

now it wants the device to not wake up Aeotec Siren 6 in Domticz in HA, they can get around it and get it working through adjustments.

my and other Domoticz users cannot get this siren to work in the domoticz environment in combination with zwavejs ui and mosquitto MQTT
in the outdated environment with openzwave it worked.

now I get 8 devices with volume and 8 devices with status
this is 2 devices per sound

the device volume is a dimmer function and I can of course slide it to, for example, 40% but then nothing happens, and in the log you can see that this has been set
Status: User: x (IP: x.x.x.x.) initiated a switch command (1419/siren aeotec 6_volume_dimmer_1/Set Level)
and that's it .

Now in a different way, I go to Zwavejs Ui and select a sound and you will see the status turn on in Domoticz. so that works.

I hope you know a solution to get this device working.

thank you very much in advance for your efforts

**Comment by rap27** [comment]
https://github.com/domoticz/domoticz/issues/5826

**Comment by rap27** [comment]
it is now in the hands of Domoticz, I hope they can help me there. thank you all for the explanation and effort

**Comment by rap27** [comment]
As a beginner, I just dived into Node Red and that's how I got the siren on. so in the mqtt and zwave js the problem is not when it comes to getting the siren on and off.

what matters is that things cannot be controlled from domoticz
Or if you look at it another way, the fields of this siren do not come across to domoticz.

I keep looking for where I need to be now
domoticz
or
zwave js ui

Since device x is programmed somewhere, you have to transfer those things to domoticz
and in this case we are missing the most important part of a siren, turning it on and off.

I am anything but a developer and therefore look at it somewhat as a layman.

Perhaps there is someone who can help me with how I can tell the zwave js ui device script to also transfer the sound fields to domoticz because those are the activations for sound from that thing.
this is the node red mqtt code

zwaveNW/sirene_aeotec_6/121/1/toneId/set

zwavanNW is the mqtt in domoticz
sirene_aeotec_6 is the name in zwave js ui
121/1 is the field under the node zwave js ui where the last 1 stands for the first sound of the 8

but I just hope that someone knows where I can put this so that I and all Domoticz users can use this device in a correct and normal way.

**Comment by gizmocuz** [comment]
Could you post 'all' config topics with payload here? In the forum I only see the volume config+payload topics correct?

**Comment by rap27** [comment]
> Could you post 'all' config topics with payload here? In the forum I only see the volume config+payload topics correct?

hello gizmocu

Of course
here the volume
zwaveNW/sirene_aeotec_6/121/1/defaultVolume/set
and
zwaveNW/sirene_aeotec_6/121/1/toneId/set

I used these 2 node red if you choose a number at toneid, for example 1, then the siren starts playing that on the siren with volume sound louder softer

So you still have a lot of options with this siren, but if these 2 options would work in Domoticz then I would be very happy because you can then continue working with scripts and go in all directions.

**Comment by gizmocuz** [comment]
@rap27 , could you join our slack channel and send me a private message including the link to this page?

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

**Comment by rap27** [comment]
Hello gizmocuz, I sent you a pm message with the information.
 
for the rest, here's an update.
I deleted the mqtt in domoticz and created it again.
Now you see that in the mqtt explorer there are 2 values for the zwave mqtt from domoticz, namely "defaul volume" which is set to 0 and "volume" which responds to the dimmer button in domoticz. When I look in the explorer at the mqtt of Zwave JS, I see that the volume does not change at 121-1. When I look in the browser at Zwave JS, I see a rotating icon at volume. If I want to adjust this manually in Zwave Js, I get an error message: "Value update failed: sound switch: "volume" is not a supported property (zw0322).

I had it running with node red, but had the sound linked to the default volume value.

it seems that the dimmer button is linked to a volume field that gives an error message, by the way, you get that error with all 8 fields in zwave js

**Comment by rap27** [comment]
I just got this answer back from Zwave JS

"Yes, it's [hard-coded](https://github.com/zwave-js/zwave-js-ui/blob/a13d26f5869acf76fdfd15d2986ca58eb47d8380/lib/Gateway.ts#L1283-L1292) as a dimmer with volume property, which is incorrect. To support this siren properly would require implementing the MQTT siren (you would need to ask Domiticz if they support it) as I've mentioned in https://github.com/zwave-js/zwave-js-ui/issues/3298#issuecomment-1734028978 and https://github.com/zwave-js/zwave-js-ui/issues/3298#issuecomment-1739522082, or a shortcut would be to create an on/off switch (not dimmer) that sets toneId (not volume) to on and off https://github.com/zwave-js/zwave-js-ui/issues/3298#issuecomment-1742140366."

**Comment by gizmocuz** [comment]
As it is currently not implemented as a auto discovery type 'Siren' , it is not possible to implement this without some test data
As you are able to control it via Node-Red, and also by creating buttons as mentions by the zwave-js issue, you can work around this issue,

And also because of this comment:

> This is still a bug in ZUI since it is creating incorrect MQTT discovery information, it would be better to do nothing at all.
> 
> It's also a bug in the driver because Volume is a writable property but setting it is an error. I created https://github.com/zwave-js/node-zwave-js/issues/6320 earlier for that.
> 

I also think leaving it like this for now

**Comment by rap27** [comment]
okay, too bad I had hoped for a definitive solution, I have posted a solution on the  fourm, but it is not pretty as you have to install the MQTT client in the original docker from domoticz, perhaps that is an option to include that in the original docker image . but thank you for your efforts, here is the link to this solution for the enthusiast

[domoticz forum](https://www.domoticz.com/forum/viewtopic.php?t=40030&start=40)

**Comment by AlCalzone** [comment]
FWIW, the next release of `node-zwave-js` will fix the linked issue by supporting writing to `volume`: https://github.com/zwave-js/node-zwave-js/pull/6450

However it is not going to be possible to make the siren play a sound by setting the volume. This will simply set the volume used when setting `toneId` to play a sound.

**Comment by rap27** [comment]
> FWIW, the next release of `node-zwave-js` will fix the linked issue by supporting writing to `volume`: [zwave-js/node-zwave-js#6450](https://github.com/zwave-js/node-zwave-js/pull/6450)
> 
> However it is not going to be possible to make the siren play a sound by setting the volume. This will simply set the volume used when setting `toneId` to play a sound.

thank you, Very nice to hear that a solution is on its way.
