### ISSUE TITLE
The field "Axis label" is missing in the pop in "create Virtual Sensor" of a custom sensor

### ISSUE THREAD

**Issue by jmleglise** [domoticz/domoticz#583]
V3.4951

Small bug : Create a Virtual sensor of type : "custom sensor". When you create again a virtual sensor just behind,  you will get this form : 

![bug custom](https://cloud.githubusercontent.com/assets/1726314/14062924/e695ba32-f3b1-11e5-950a-eaba0fb344b0.JPG)

The field Axis label is missing.

**Comment by gizmocuz** [comment]
Thanks for reporting, will be fixed in a next beta.
Since you post this issue on github, if possible, next time make a pull request with the fix, else post on our forum
