### ISSUE TITLE
door contact remains open

### ISSUE THREAD

**Issue by dearekaelle** [domoticz/domoticz#5833]
Domoticz with MQTT Autodiscovery for node-zwave-js/zwave-js-ui

Since build 15564 door contact remains open for all of my door/window sensors regardless of make/model. 

Once the door contact becomes open it will stay open in Domoticz after closing. 

door/window sensor shows proper state in zwavejs.

**Comment by gizmocuz** [comment]
Sorry about that, did you also tried with the latest beta?

Is it possible that you could post here the MQTT config topic of the door contact and it's json payload?
(You can use MQTT Explorer for this)

And also the status topic and payload when you open and close the contact

I will try to replicate this asap as well

**Comment by dearekaelle** [comment]
yes, this bug is also present in latest beta, reverting to build 15563 solves this issue.

topic: zwave/Bathroom_Upstairs_Window_Sensor/113/0/Access_Control/Door_state

closed
{"time":1696686551471,"value":23,"nodeName":"Bathroom Upstairs Window Sensor","nodeLocation":"Bathroom Upstairs"}

open
{"time":1696686424072,"value":22,"nodeName":"Bathroom Upstairs Window Sensor","nodeLocation":"Bathroom Upstairs"}

**Comment by gizmocuz** [comment]
Thanks, could you alsof post toe config topic land payload?

**Comment by dearekaelle** [comment]
do you mean this one?

topic: homeassistant/binary_sensor/Bathroom_Upstairs_Window_Sensor/door_state/config

{"payload_on":22,"payload_off":23,"value_template":"{{ value_json.value }}","state_topic":"zwave/Bathroom_Upstairs_Window_Sensor/113/0/Access_Control/Door_state","json_attributes_topic":"zwave/Bathroom_Upstairs_Window_Sensor/113/0/Access_Control/Door_state","device":{"identifiers":["zwave-js-ui_0xe8368f41_node71"],"manufacturer":"Aeotec Ltd.","model":"Door/Window Sensor 7 (ZWA008)","name":"Bathroom Upstairs Window Sensor","sw_version":"1.1.0"},"name":"Bathroom Upstairs Window Sensor_door_state","unique_id":"zwave-js-ui_0xe8368f41_71-113-0-Access_Control-Door_state"}

**Comment by gizmocuz** [comment]
Yes perfect, thank you!
I found the issue, it was caused by the number value as status, it was internally threaded as a brightness value.
Fix is underway, just a short moment, I will mention when a new beta is available

**Comment by dearekaelle** [comment]
perfect, many thanks ;)

**Comment by gizmocuz** [comment]
Please try beta 15588

**Comment by dobber81** [comment]
My fibaro zwave magnet contacts work again after this fix. Thank you!

**Comment by dearekaelle** [comment]
All good here after upgrading.. thanks once again 👍

**Comment by dave21w** [comment]
All working now for me on beta 15594

Many Thanks
