### ISSUE TITLE
Using IIS as Reverse Proxy

### ISSUE THREAD

**Issue by arjannv** [domoticz/domoticz#5836]
By default, IIS adds the port in the "X-Forwarded-For" header. For example it sends: `X-Forwarded-For: 1.2.3.4:5678`
When this is enabled, Domoticz blocks the attempt with: "Unable to determine origin due to improper proxy header(s)".

I've solved this by modifying the IIS ARR configuration file: C:\Windows\System32\inetsrv\config\schema\arr_schema.xml by setting this: 
`<attribute name="includePortInXForwardedFor" type="bool" defaultValue="false"/>`

Can Domoticz be configured to ignore the port in the "X-Forwarded-For" header?

**Comment by gizmocuz** [comment]
Did you specify '1.2.3.4:5678' yourself? I think it should only contain '1.2.3.4'

**Comment by arjannv** [comment]
Thanks for the quick reply! 
No, this is done by IIS ARR by default. If I specify it manually in the proxy rules, the proxy sends both the default value and the manual value: `X-Forwarded-For: 1.2.3.4, 1.2.3.4:5678`
If I point the proxy to a little PHP script to check what headers are send, I get this: 

It seems that IIS combines X-Real-Ip with X-Real-Port for X-Forwarded-For.
```
Array
(
    [X-Arr-Log-Id] => 58948b40-16ad-44e1-9a75-0abc7f2ae41c
    [X-Arr-Ssl] => 2048|256|C=US, O=Let's Encrypt, CN=R3|CN=****
    [X-Forwarded-For] => 10.0.0.254:56655
    [X-Original-Url] => /getheaders.php
    [Sec-Fetch-Dest] => document
    [Sec-Fetch-User] => ?1
    [Sec-Fetch-Mode] => navigate
    [Sec-Fetch-Site] => none
    [Service-Worker-Navigation-Preload] => true
    [Upgrade-Insecure-Requests] => 1
    [Sec-Ch-Ua-Platform] => "Windows"
    [Sec-Ch-Ua-Mobile] => ?0
    [Sec-Ch-Ua] => "Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
    [User-Agent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
    [Max-Forwards] => 10
    [Accept-Language] => en-US,en;q=0.9
    [Accept-Encoding] => gzip, deflate, br
    [Accept] => text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
    [Pragma] => no-cache
    [Cache-Control] => no-cache
    [Connection] => close
    [Host] => ****
    [X-Real-Port] => 56655
    [X-Port] => 80
    [X-Real-Ip] => 10.0.0.254
    [X-Forwarded-By] => 10.0.0.7
    [Content-Length] => 
    [Content-Type] => 
)
```

I agree that it should only report the IP but it doesn't do that by default. Unfortunately, adding the "Forwarded" header is pointless because Domoticz only looks at the first of "X-Forwarded-for, X-Real-Ip or Forwarded" so, currently there is only the solution to manually edit the configuration file of IIS.

**Comment by xbeaudouin** [comment]
> Did you specify '1.2.3.4:5678' yourself? I think it should only contain '1.2.3.4'

Adding the source port is a good practice on reverse proxies to handle CGNAT, see https://www.rfc-editor.org/rfc/rfc7239.txt

**Comment by gizmocuz** [comment]
Okey, but I just did some debugging and it indeed the port is the issue.
It is internally recognized as a IPv6, which is wrong of course, it sees a invalid IPv6 address and stops and gives this error.

Made a change in beta 15595, should now work correctly.

@kiddigital , is it maybe possible you can have a peek at my patch? I think it's fine but just to be sure....

https://github.com/domoticz/domoticz/commit/882e5506d1acd83052feaf0bf5f7d3a7f17e2d90

**Comment by arjannv** [comment]
Greatt, thank you for the quick patch!
I'll give it a try once I'm able to update to 15595

**Comment by arjannv** [comment]
Just updated to 15597. I can confirm the patch is working with an IP and Port in X-Forwarded-For. 
For anyone's info: Using IIS as a reverse proxy for Domoticz does not require any configuration and will work out-of-the-box (when using version 15595 or higher).
