### ISSUE TITLE
P1 Meter - Voltage swell and sag devices are not created unless there are swells or lags

### ISSUE THREAD

**Issue by robk358** [domoticz/domoticz#5841]
[2023.2] (build 15603)
"P1 Smart meter" swell and sag devices are created only if there are swells or lags (and device discovery is on).
A zero value of a swell or sag is also a valid value..

Tests for sag/swell values in P1MeterBase::MatchLine() should compare with "-1" instead of "> 0"

**Comment by gizmocuz** [comment]
Thanks for your PR!

It was indeed my idea to not add them if there was no data... But happy to accept this patch if you think it's better

**Comment by robk358** [comment]
i think it's better to add them: if you want to trigger an alert, the device(s) needs to be present. (and if you don't want to use the devices, you can disable them)

**Comment by gizmocuz** [comment]
Okey will do! Thanks!
