### ISSUE TITLE
Motherboard Core/V3D/Arm clock speeds on Raspberry Pi not updating

### ISSUE THREAD

**Issue by robk358** [domoticz/domoticz#5845]
Domoticz V2023.2 (build 15607) 
Motherboard: System: ODroid/Raspberry
Motherboard: Hardware Monitor: Started (OStype Linux) 

Motherboard Core/V3D/Arm clock speeds on Raspberry Pi not updating (ID's: 00000001,00000002,00000003) 

other motherboard sensors are updating their values

issue occurs since Commit on Oct 14, 2023 [Removed vcgencmd dependency]

**Comment by gizmocuz** [comment]
That is correct, they have been removed.

CPU speed should still work?

**Comment by robk358** [comment]
only CPU Usage (%) is available, no CPU Speed
![motherboard sensors](https://github.com/domoticz/domoticz/assets/83170918/87d6acc2-6dac-47bd-a3ea-ed5b30d04d76)

**Comment by gizmocuz** [comment]
That is correct. Why do you need it? Do you always look at it? Same as voltage, do you frequently look at it?
CPU Usage is the important one, same as memory, temperature, and disk
You can have a look at the core speeds from the command line
Are they changing a lot?

**Comment by robk358** [comment]
i don't need them... it was just an observation ... 
didn't see information about sensor removal (only "Removed vcgencmd dependency")

**Comment by gizmocuz** [comment]
Yep, that's it.
