### ISSUE TITLE
Confusing behavior in case of MQTT TLS configuration error

### ISSUE THREAD

**Issue by jpalus** [domoticz/domoticz#5846]
I've hit a strange situation when trying to configure secure MQTT connection. All seemed fine on `domoticz` side:
```console
Status: zigbee2mqtt: Connecting to tls://mqtt:8883
Status: zigbee2mqtt: enabled TLS mode
Error: zigbee2mqtt: disconnected, restarting (rc=7/The connection was lost.)
```

`mosquitto` wasn't quite happy though, with error not being very clear and directing troubleshooting in the wrong direction:
```console
OpenSSL Error[0]: error:0A00010B:SSL routines::wrong version number
Client <unknown> disconnected: Protocol error.
```

After some debugging it turned out CA file wasn't readable by user running `domoticz`. While the method setting CA failed, `domoticz` ignores most return codes for mosquitto TLS parameters configuration:
https://github.com/domoticz/domoticz/blob/3a03efa60c2d1c84d831e4fb32c3cb2024abf193/hardware/MQTT.cpp#L614-L631

The end effect was `domoticz` making "clear-text" connection on secure port in `mosquitto`.

**Comment by gizmocuz** [comment]
Thank you for your PR!
I merged this, and will make a slight modification to it as the certificate file could also be set via the commandline (-sslcert option)
