### ISSUE TITLE
server_cert.pem domoticz 

### ISSUE THREAD

**Issue by smarticz** [domoticz/domoticz#5848]
Why do you always restore the old ssl file when updating?

remove server_cert.pem from update

**Comment by gizmocuz** [comment]
You are free to use the supplied certificate or you can create your own and specify this with a startup parameter (-sslcert)

**Comment by smarticz** [comment]
Yes, but u still remove it when update domoticz - every time when updating.

@gizmocuz

**Comment by gizmocuz** [comment]
Why is that? We don't remove anything...
Are you using docker, or the native method?

**Comment by waltervl** [comment]
If you create your own certificate you should not name it exactly the same as the Domoticz server_cert.pem but for example  letsencrypt_server_cert.pem then it wil not be overwritten.
