### ISSUE TITLE
MQTT Auto Discovery adds new devices even when 'Accept new Hardware Devices' is off

### ISSUE THREAD

**Issue by wdonker** [domoticz/domoticz#5850]
AD adds new devices even when 'Accept new Hardware Devices' is off.

I would expect it not to do so but looking at the code of MQTTAutoDiscover.cpp it does not seem to check the mentioned setting when adding a new device to the database.
This is especially annoying when using auto discovery with RF devices (through OpenMQTTGeteway in my  case). Lots of devices in my neigbourhood are added to Domoticz even when I do not own them.

Tested with stable 2023.1 and beta 2023.2 on Raspberry Pi. Both gave the same results.

**Comment by gizmocuz** [comment]
Yes, in your case it makes sense to not add them.
But for a default user that adds another piece of hardware to (for example) it's zigbee stack, they should first enable 'Accept new Hardware'
Actually the 'Accept new Hardware' option was build to stop the annoyance of RF devices that are discovered (and by possible RF noise)
I added this because I use RF (with RFXCom hardware)

What hardware are you using that outputs MQTT-AD?

**Comment by wdonker** [comment]
I am using OpenMQTTGateway (OMG)  with a RTL433 sensor to catch RF-devices.

I found out that it is possible to disable discovery in OMG and then it will no longer generate discovery messages (config) for HomeAssistant (or Domoticz in my case). But since config-messages are published with the retain-flag set they are still kept by the broker. And as soon as Domoticz (or the plugin) is restarted it will receive those older config messages again.
For now, the only way to prevent this is to delete the retained messages for devices I do not own (using MQTT-explorer).

So I have a work around if you decide not to change this behaviour. But I also use Zigbee-devices and I would not find it strange if I had to enable 'Accept new Hardware' when I add new devices. As it is now, the function of the setting is a little confusing.

**Comment by gizmocuz** [comment]
I think in the latest version it will not add new devices if you have this disabled

**Comment by wdonker** [comment]
Ok, I tested with the new version and now it works as expected!

**Comment by gizmocuz** [comment]
Thanks for the feedback!
