### ISSUE TITLE
Power generated calculations wrong

### ISSUE THREAD

**Issue by ldrolez** [domoticz/domoticz#5851]
Version: Version: 2023.1 (build 15427) Build Hash: 3c8e06c73

I have some solar panels connected to micro-inverters, and also a Zwave energy counter which logs energy generated on Domoticz.
Yesterday, I noticed that the reported energy generated for the day, was different for Domoticz and for the micro-inverter (direct reading via AHOY DTU):
- Domoticz: 500Wh
- Inverters: 850Wh

Visually you can quickly see that something is wrong.
![2023-10-24 09_27_13-Domoticz](https://github.com/domoticz/domoticz/assets/2277898/de841ffb-781c-4411-b00f-0e1c1662b00d)

So I downloaded the .csv data, made the calculation by hand and got 804Wh for the day.

I conclude that something is wrong in the energy generated calculation. Here is a screenshot and the exported data for the day (check november 23 for evidence)

**Comment by ldrolez** [comment]
Raw data: [chart bug solar.csv](https://github.com/domoticz/domoticz/files/13111895/chart.bug.solar.csv)

**Comment by waltervl** [comment]
Normally the Energy Generated is based on a running counter value (total energy) coming from the Zwave device. If that is not available Domoticz can calculate the Energy Generated based on the Power Generated but that is way less accurate.
If you click on the Edit button on the device widget, what is the setting Energy Read: Compute (=inaccurate) or from Device (=accurate)

See https://www.domoticz.com/wiki/Dummy_for_virtual_Switches#Electricity_.28instant_and_counter.29 for a screenshot of the edit page of the device.

**Comment by ldrolez** [comment]
Ok so my zwave meter might be wrong (Qubino brand)... I switch to computed!

**Comment by waltervl** [comment]
Are you using ZwaveJSUI? Because then you can check the messages with MQTT Explorer to see what data is going over. Could be that there is a misconfiguration somewhere.

**Comment by gizmocuz** [comment]
Are we talking about a daily value or a real-time peak value?
Do note that in the top chart (5 minute interval) there is no total value, and these values are sampled every 5 minutes
We do you the real counter values to calculate the real (and correct) day value, that you should see in the chart below the top one

**Comment by ldrolez** [comment]
Anyway it's a zwave device problem, it sends the total usage when it wants... So I switch to 'computed'

**Comment by waltervl** [comment]
Not necessarily. If it sends the real total usage it would be the best solution. But check the Zwave-JS-UI log or MQTT messages to be sure.
