### ISSUE TITLE
Timers not working

### ISSUE THREAD

**Issue by ilsicca** [domoticz/domoticz#5855]
Hi! 
I have a problem with the timers. The timers until 2023.1, it's working fine but I upgrade to the last stasble version and the timers stopped working.

Domoticz on Docker
Version: 2023.2 (build 15620)
Compile Date: 2023-10-26 03:27:29

I configured the timer but it not working. Also, I created a timer plan but not worked.

![image](https://github.com/domoticz/domoticz/assets/46833657/c14f1252-f685-4f2d-9027-490021a8936c)
![image](https://github.com/domoticz/domoticz/assets/46833657/d28f55de-05a6-4f7f-8adc-33245229ba66)

Can I help me with this problem?

**Comment by gizmocuz** [comment]
How about with the beta version?
When you create a dummy switch with a timer does that work?
Is the timerplan active ?

**Comment by ilsicca** [comment]
With the 2023.1 works fine but when I upgraded to 2023.2 the timers doesn't work.
I dont' have a timerplan.
When I create a new dummy switch with a timer doesn't work.

**Comment by gizmocuz** [comment]
@ilsicca , okey but you mentioned "I created a timer plan"
When you create a new timer for testing, make sure that you define it a few minutes earlier. Don't add a timer for 16:43 when it is 16:42
Timers are definitely working otherwise we would have noticed this as well.
Please update to the beta version and try as well

Also create a dummy switch (normal switch, don't change the type), and a timer on this and test this

**Comment by waltervl** [comment]
For me timers in 2023.2 stable is just working fine. Even on a push on switch. I just tried. I have seen reports of users that had events scripts (lua, dzvents etc) that had an error in it. If that happens the Event systems of Domoticz gets stuck resulting also in blocking timers.

Edit: in 2023 some security improvements have been made so perhaps one of your scripts is running into a security issue now. Check your Domoticz log file for errors

**Comment by ilsicca** [comment]
Hi! Thanks @gizmocuz @waltervl . The timer already working in this moment. I set the timer time in 15:00 hs and not in 15:15 or 9:26 and work it fine.
