### ISSUE TITLE
Domoticz with MQTT Zwave JS generates wrong 'off' code for a ZWave 'KeyPressed' event

### ISSUE THREAD

**Issue by bvhoesel** [domoticz/domoticz#5856]
Version: 2023.2 (build 15621) Beta
Platform: Ubuntu x64
Plugin/Hardware: MQTT Auto Discovery Client Gateway with LAN interface + ZWave JS UI

Current and some previous beta's generate a Domoticz 'Off' code when a key is pressed on a ZWave controller or remote. The ZWave JS UI shows the event 'KeyPressed'. Which is translated differently in 15555 (On) and 15621 (Off).

The issue is completely reproducible by running both versions at the same time. Version 15555 shows an 'On' code and 15621 shows an 'Off' code.

Easiest way to see this is to create a scene and add the key press device to it.

Using the latest version 9.3.0 of ZWave JS UI. But issue also occurred in previous versions of ZWave JS UI. First Domoticz beta I noticed this issue was 15607. Since I did not use beta's (if any) between 15555 and 15607 I do not know exactly which beta broke the On - Off code translation.

Some discussion on the forum also: [https://www.domoticz.com/forum/viewtopic.php?p=308399](https://www.domoticz.com/forum/viewtopic.php?p=308399)

Extra MQTT message info:

```
mosquitto_sub -h myhost -t "zwave/vrij/CTL_Hank_button_2/91/0/scene/001"
{"time":1698486427692}
{"time":1698586085435,"value":0}
{"time":1698586086436}
{"time":1698586088649,"value":2}
{"time":1698586089554,"value":1}
{"time":1698586090555}

```
```
$ mosquitto_sub -h myhost -t "zwave/werkkamer/CTL_Werk_Oomi_1_B7/91/0/scene/003"
{"time":1698486427768}
{"time":1698586217636,"value":0}
{"time":1698586218636}
{"time":1698586220776,"value":2}
{"time":1698586220839,"value":2}
{"time":1698586220975,"value":2}
{"time":1698586221122,"value":1}
{"time":1698586222123}

```
Above "value" meanings:

0: short press
2: long press
1: release after long press

So it seems "value":0 is interpreted as On in 15555 and Off in 15607 and later.

**Comment by bvhoesel** [comment]
Not any acknowledgement if this is either a bug or a new feature?

To extra illustrate the problem two screenshots after adding an activation device to a scene. First is from the 15555 build that works as expected up to now.

![image](https://github.com/domoticz/domoticz/assets/3183695/a1eb0ad0-9d20-400e-b5a3-7ce9954e14ee)

This second is from the most recent build 15643 (as of this writing) that shows the changed and unexpected functionality.

![image](https://github.com/domoticz/domoticz/assets/3183695/2df1a7cf-77a9-4e85-8a23-492cb828eb6f)

Effect from this is that scenes and scripts which expect an 'On' code on a key-press do not work anymore.

Just a reminder on the configuration. Both Domoticz versions are running simultaneously and thus receive the same messages from MQTT.

**Comment by gizmocuz** [comment]
I really don't understand the issue here, maybe you can join our slack channel and send me a PM

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

A scene device can only activate something, so they are (should be) created as push_on buttons

Next, I see some data without any value... why is this? Maybe this is causing the issue

Could you post the MQTT config topic + json payload, without this I am unable to debug

**Comment by bvhoesel** [comment]
@gizmocuz Can't quite follow you're remarks about scene activation and empty data. First I'll try another description of the issue.

I've got a (even several but they all behave the same in this respect) zwave remote 'button' devices. If I press a button on such device in the older builds this generates an 'On' code (or state) for that device in Domoticz. The same physical button press in the newer builds generates an 'Off' code in Domoticz. This changed behavior (from 'On' to 'Off') breaks all the current scenes and dzVents scripts controlled by such device that depends on the configured 'On' code of the 'button' device. The examples for the scene above I'll tried to show that I have an activation device that acts on a 'On' code (in 15555). But in the newer build the same physical action of pressing the (same) button on the zwave device generates an 'Off' code. As an effect the scene will not activate because an 'Off' code is 'seen' instead of the previous configured (and expected) 'On' code.

For dzVents scripts holds the same. An example line for one of my scripts:

    `if myDevice.state == "On" then`

'myDevice' is the zwave button. The script checks for the 'On' state to execute the rest of the program code. That works in 15555 because the 'On' state is set. Nut in newer build the 'On' state is never received because now the 'Off' code is received. As a result the designated program code will never be executed.

I do can solve this issue for dzVents by replacing all myDevice.state == "On" with myDevice.state == "Off" and for scenes deleting all de 'On' codes and adding activating the key press again with 'Off' codes. Then everything works again. But it is counter intuitive that pressing a physical button generates an 'Off' code or state. The previously generated 'On' code or state is definitely what is intuitively expected.

The MQTT messages and info in a previous comment shows the basic  MQTT message content when operating two zwave button devices with explanation what physical action was performed for each 'value' received.
As a recap: It seems MQTT message "value":0 is interpreted as 'On' code or state in 15555 and 'Off' in newer.

I will try to get the requested "MQTT config topic + json payload". First have to figure out what you mean with "MQTT config topic". The json payload is clear (I think).

**Comment by gizmocuz** [comment]
Yes, there have been some recent changes in the switch handling.
But I need the config topic + payload

To find them (and copy them) you can use a program like MQTT Explorer, connect to your broker, open the auto discovery tree (probably named homeassistant), find your button (probably under binary or lights), and you will see that the topic ends with 'config' ... please post the complete topic name like homeassistant/light/xx/yy/config
And also the contents of it (the json payload)

**Comment by bvhoesel** [comment]
Send more info via Slack PM.

**Comment by gizmocuz** [comment]
Issue has been found and solved in the latest beta version
