### ISSUE TITLE
Device from remote server is updated by 2 devices

### ISSUE THREAD

**Issue by RBL-Hormann-ALK** [domoticz/domoticz#5857]
For years I use 2 Domoticz instances (both Raspberry Pi and both running version 2023.2 build 15621) and one is the master and one the slave. This is done by the "Domoticz - Remote Server" hardware. Today I discovered that one device on the master is updated by two devices on the slave. They are both temperature devices. 
So the two devices in the screenshot are updating the single device in the other screenshot. 
What stands out is that the type and id of the two devices are the same, but there are more devices with the 0001 as id.

![Screenshot_20231031_000121_com android chrome_edit_152542811062660](https://github.com/domoticz/domoticz/assets/139784074/defa2079-e642-4126-9e28-85d4203bcbc8)
![Screenshot_20231031_000215](https://github.com/domoticz/domoticz/assets/139784074/b072ec2a-e39f-49d2-b789-8615a260ecb7)
I tried deleting the devices (made a db backup before that) they are all recreated and then the problem also.
How is this possible and how can I solve this?

**Comment by waltervl** [comment]
Seems related to https://github.com/domoticz/domoticz/issues/3560 and a known issue.

**Comment by gizmocuz** [comment]
Please check beta 15790 ... Both client/server need to run on this beta... quite some things have changed.
You probably will get new devices, so make sure 'Accept new hardware/devices' is enabled in the settings

**Comment by roblomq** [comment]
Can I just use the "Replace" function to merge the newly created and old devices?

**Comment by gizmocuz** [comment]
Yes you can. Just make a backup before from the settings page. But all should work smoothly

**Comment by roblomq** [comment]
What happens if you "Replace" an active device with another active device? Doesn't it end up with the same problem as above (like one device is updated by 2 devices)? And how can you check this and undo/change this?

**Comment by gizmocuz** [comment]
Ehhh sure....

Anyway, a 'device' unique combination is HardwareID/OrgHardwareID/DeviceID/Unit/Type/Subtype
It should not be possible that two devices have this combination... impossible!
Sure, when you create your own ESP device and use the exact parameters this could be possible... still very strange

**Comment by roblomq** [comment]
Let's say I have a temperature device A that has a RFXcom as hardware and I have another temperature device B that has a 1-wire as a hardware that is coming from a remote server. Then what if I replace device A with B and both hardware updates with new data?

**Comment by gizmocuz** [comment]
That are two different devices as the OrgHardwareID is the HardwareID of the remote server. So they are different...
Do you experience a issue at the moment with this?

**Comment by roblomq** [comment]
Yes they are different but I can replace A with B, is that correct?
I'm not 100% sure if I have this right now but I think I replaced one with the wrong device.

**Comment by roblomq** [comment]
Above the one on the "master" below on the "slave". The problem is where is the extra "dip" coming from, I'm not able to check this. That's why I asked the question if it's possible to "merge" two active devices into 1 using the replace function.
![2024-01-24_17h49_32](https://github.com/domoticz/domoticz/assets/59142034/6224a097-6a76-4b9f-be53-57ebcc2f1634)
![2024-01-24_17h49_17](https://github.com/domoticz/domoticz/assets/59142034/fbfa7da4-e3ad-4309-b8ba-512d360b2de4)

**Comment by gizmocuz** [comment]
Seems the same indeed. Remember Domoticz makes a short log at a 5 minute interval. Maybe it just missed it?
But they are clearly the same.
And if the 'old' device is still being updated, you should get a new device in the device overview. If there is only one device, that you are good.
And for replacing, press edit on the OLD device than replace, you want to replace a OLD device with a NEW one ... Not the other way arround

**Comment by roblomq** [comment]
Is there an easy way to recreate a new device on the slave device? Just to make sure it isn't updated by two devices.

**Comment by gizmocuz** [comment]
Yes, you can delete it on the client (the one that connects to the master/server at port 6144).
It should be automatically being created once the master sends this to the client

**Comment by roblomq** [comment]
The logs of the master and slave of several devices show differences. I also get on the slave several "Invalid data received!" messages. So I think this is related but I have no clue on what can cause it. So I hope you can help.

**Comment by roblomq** [comment]
Huh, what's the problem with my language?

**Comment by gizmocuz** [comment]
Maybe master/client? I don't know

**Comment by roblomq** [comment]
Do you know a way to find out where the invalid data from from?

**Comment by gizmocuz** [comment]
No, unfortunately not.
Could you try disabling the remote hardware in the client (the one that connects to the master)
Enable 'Accept new devices' under settings
Then add a new 'Domoticz Remote' hardware
