### ISSUE TITLE
Events not always sent

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5858]
Version: 2023.2 (build 15607)
Build Hash: 3a03efa60
Compile Date: 2023-10-20 09:07:12
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 11 2023, 09:51:27) [GCC 8.3.0]

If I send a voice command by dzga, the command is executed, but events are NOT generated, so my dzVents script is not triggered.
Situation: I have 2 zigbee devices in my bathroom to switch 2 heating devices. This works 100% correct with all the scripts I use.
But when I speak a voice command via Google and dzga ("Hey Google zet de verwarming in de badkamer aan."), the command is executed, but no event is generated.
This in the logging of domoticz.
```
2023-11-01 11:25:16.979  Status: User: YYY (IP: 192.168.xxx.xxx) initiated a switch command (1388/Badkamer verwarming/On)
2023-11-01 11:25:17.668  Status: User: YYY (IP: 192.168.xxx.xxx) initiated a switch command (1684/Handdoek verwarming/On)
```

If I turn them on individually by voice and Google or in the domoticz GUI, everything works as it should.
Is it a problem for Domoticz if 2 commands are executed within 1 second?

**Comment by waltervl** [comment]
Dzga is a python plugin? Perhaps better to ask it there.

**Comment by SargonofAssyria** [comment]
No, Dzga is not a plugin. It is written in Python and installed as a Linux service. It interacts with Domoticz via API.
The above logging shows the 2 commands to active 2 switches (Zigbee) and those action like On and Off works perfectly.
The only thing is when those commands are send by Dzga, Domoticz does NOT generate events.
EVERYTHING works as it should except for the events which are not generated.
After a lot of testing I found out that after I manually (via GUI) once activate and deactivate those switches the Dzga commands works and generate events.
Just to mention if that might be the cause: for logrotate reasons I do a domoticz reload just after midnight every day.

**Comment by waltervl** [comment]
What is the api command used by dzga to switch the switches?

**Comment by SargonofAssyria** [comment]
Domoticz even with logging in the GUI set to debug does not show the API command.
Is it really important to have the API command, because it works. 
Every day the events are not generated, but after manually activating the switches the events are working too, until the next day.
I will look in the source if I can find the API of dzga.

**Comment by waltervl** [comment]
Then we can reproduce it. You can also try to reproduce it to sent the api url 2 times manually.

**Comment by SargonofAssyria** [comment]
Found it:
```
                url = DOMOTICZ_URL + '/json.htm?type=command&param=switchlight&idx=' + self.state.id + '&switchcmd='
                if params['on'] is True and state == 'Off':
                    url += 'On'
                elif params['on'] is False and state != 'Off':
                    url += 'Off'
```

**Comment by SargonofAssyria** [comment]
And this is the same command as in the Wiki.
```
/json.htm?type=command&param=switchlight&idx=99&switchcmd=<On|Off|Toggle|Stop>
```
From my first post: Is this possibly a problem?
```
Is it a problem for Domoticz if 2 commands are executed within 1 second?
```

**Comment by gizmocuz** [comment]
> Is it a problem for Domoticz if 2 commands are executed within 1 second?

No that is no problem they will both be handled

**Comment by gizmocuz** [comment]
Can you post your dzVents script, maybe it is not listening correctly for 1388 and 1684... BDW, you HAVE to use different names for dzVents, no device can have the same name

**Comment by SargonofAssyria** [comment]
No problem, enclosed the dzVents script.
But again the script functions correct, The names of the devices are different, as you can see from the above log part.
e.g. Badkamer verwarming and Handdoek verwarming
The dzVents script listens correctly to 1388 and 1684 because if I once manually active/deactive those devices in the GUI or one by one via dzga the script works correct until the next day.
[Auto-Off-V3.lua.txt](https://github.com/domoticz/domoticz/files/13250644/Auto-Off-V3.lua.txt)

**Comment by waltervl** [comment]
To test if an event script can be triggered 2 times within a second please try this script that only logs if the device is triggered.  If this runs it could be because of your other logic in your script causing a delay. Probably better to disable your original script while testing this. I did not test it so there could be a typing error...

```
return {
        active = true,
--      active = false,
        on =
       devices = {
                        'Badkamer verwarming',
                        'Handdoek verwarming',
                },
        },
        logging =
        {       marker = 'TESTAutoOff',
                level = domoticz.LOG_INFO,
--              level = domoticz.LOG_DEBUG,
        },
    execute = function(dz, item)
               if item.isDevice then
                        -- Log trigger
                        if item.active then
                                dz.log(item.name..': '..item.state..' was triggered ', dz.LOG_INFO)
                        else
                                dz.log(item.name..': '..item.state..' was triggered ', dz.LOG_INFO)
                        end
                end
        end
}

```

**Comment by SargonofAssyria** [comment]
@waltervl  gizmocuz already mentioned that events can be within the second. The above script is just a stripped copy of mine.
I even simplified the script to:
```
    execute = function(dz, item)
            dz.log(item.name..': '..item.state..' was triggered ', dz.LOG_INFO)
        end
```
My problem is that the first and/or second time every **new** day my script is NOT triggered, but after that every multi trigger is always correct.
So the script can handle multiple triggers within a second. My script works correctly.
My guess is that every day some housekeeping is done by Domoticz and that messes up something,
or my every day reload of Domoticz (needed for logrotate) messes things up.
Even if I have my own script active and the above simplified script together, both gets triggered and logged.

**Comment by waltervl** [comment]
Ok, then I will close this issue.

**Comment by SargonofAssyria** [comment]
What is that??? The problem still exists, so why close it?

**Comment by waltervl** [comment]
I can reopen it but with your description and guesses and usage of restarting it will be hard to find the root cause of your problem and solve it with a source code change.

**Comment by SargonofAssyria** [comment]
Your right. The fact that it is a problem, but hard to solve is a valid reason to close. Tnx.

**Comment by waltervl** [comment]
You could try to stop the log rotate restart and see if that fixes your issue.

**Comment by gizmocuz** [comment]
@SargonofAssyria , So you say that multiple scripts in a second are executed, this was also expected
Next you say you restart Domoticz everyday for a log rotate?  (you should send a SIGHUP for this, no need to restart)
But how about you stop doing this for some days and monitor if this solves the issue
Could you point me to the repository of dzga so I could try to reproduce it?
No idea 'how' dzga communicates with Domoticz, but it seems a issue with dzga and not a internal domoticz issue, and therefore we can conclude that this topic can be closed and is invalid.

But i could have a look into dzga to see what goes wrong.
I assume you are using the latest  beta version? as some python related stuff has improved in here

**Comment by SargonofAssyria** [comment]
I did not state that I restart domoticz every day, but i **reload** domoticz every day via /etc/init.d/domoticz.sh and that is indeed a SIGHUP. I will stop logrotating and reloading domoticz for some days, I have to relocate the log file, because my /var/log ramdisk is not that big. the repo of dzga is at: https://github.com/DewGew/Domoticz-Google-Assistant
From some post above I mentioned that dzga is using the latest API to communicate with Domoticz.
In the meantime I found out that it is also the first click of the day in the GUI that does not send an event.
I switched from build 15607 in the first post to currently build 15626 and will switch to 15650 today.
Most important is that once the events are coming in, everything is working normal, and that from the start dzga **always** activates the switches, but only the first (few) events are missing every day, the switch **activation** from dzga is **not** missing.

**Comment by gizmocuz** [comment]
What do you mean the first event of the day? Are you using a tablet that is online 24/7?
Is that continuing updating? (For example the temperature sensors are not older than a few minutes)
If that is the case, the websocket connection is still working. Else that could be the reason and it needs to reconnect

**Comment by gizmocuz** [comment]
It seems dzga is a wrapper around the web-gui of Domoticz. How about you try the following:
- disable the logging, so no need to sighub
- use the default domoticz web interface/theme

**Comment by SargonofAssyria** [comment]
With the first event of the day I mean: After 00:00 an activation of the switch by the GUI or dzga, in this case my bathroom heating, normally engaged by a voice Google command, processed by dzga by an API call to Domoticz and execute by Domoticz. All this is working well, except for the event that should have taken place when the heater was turned ON (See my initial post). This also is (not) happening when I use my PC with the Domoticz GUI, which I just started up before the button was clicked.

I relocated my domoticz.log file and skipped the logrotation e.g. did NOT execute the reload of Domoticz, so no kill -SIGHUP of Domoticz. The voice command was executed, Domoticz switched on the heating, AND the dzVents (Auto-Off-V3.lua) executed as it should. This was my first test, will see how it runs tomorrow.
B.t.w. I am using Domoticz with the out of the box GUI (default), never used an other.

**Comment by SargonofAssyria** [comment]
2023-11-16 Today the problem (no event) is back again, with **no** restart or reload of Domoticz in between.
I will try with an on my system compiled version (build 15650).
2023-11-17 With NO kill -SIGHUP I used on my system compiled version (still build 15650) the first event on both heaters where NOT fired, although heaters where turned on by dzga on Domoticz.
2023-11-18 Problem still exists. This time only after the second activation of the switch the event was send to dzVents.

**Comment by gizmocuz** [comment]
I can't see anywhere where it could possibly go wrong.
Could you disable all events/scripts, create a single event that sends you a (pushover) notification on a state change
That should get fired first thing the next day/morning

**Comment by SargonofAssyria** [comment]
I did everything what I possibly could think of, but the bug remains.
Solved it now by a dzVents script which runs every early morning (before wakeup) which actives and deactivates the switches a few times.
This is still a strange way of solving a bug.
I will look at your suggestion, but that involves a lot of changes, because it is in a live system with a lot of scripts running during 24 hours.

**Comment by gizmocuz** [comment]
Can't you create another Domoticz (docker-compose) instance for the test?

**Comment by SargonofAssyria** [comment]
I am setting up my test system to do some more testing.
I also compared the domoticz.log files from 3 Raspberry Pi systems.
I found 1 difference in my Production system.
Around midnight all system start with calculating new sunsets etc... _and reset all events..._
But my production system has a few seconds later _Status: EventSystem: reset all device statuses..._
and that multiple times directly after each other. And that is not present in the other systems.
What causes those lines? Could that be prevented?

**Comment by gizmocuz** [comment]
This message is logged when **CEventSystem::GetCurrentStates()** is called

Now this is called on multiple locations

- when the event system is started (at startup)
- when a device is created (CSQLHelper::CreateDevice)
- when you enable the eventsystem from the settings
- when you set/change device parameters (setused json api)
- when you add a manual switch

**Comment by SargonofAssyria** [comment]
Test and production system are the same, except for a lot of dzVents scripts running at production and only a few on test system.
Test system is running fine and ALL events are triggered. On Prod. system I have still have the same problem that the first 1 or 2 events are not processed by dzVents.
Have to investigate further.
