### ISSUE TITLE
Zigbee2MQTT bridge/config message not handled

### ISSUE THREAD

**Issue by niawag** [domoticz/domoticz#5859]
Hi, I'm using Zigbee2MQTT with the "MQTT Auto Discovery Client Gateway with LAN interface" hardware plugin (Domoticz, Z2M and Mosqitto in separate dockers). Everything is working great but I always have an error when Domoticz or Z2M is restarted:
```
2023-11-02 12:37:35.882 Error: Zigbee2MQTT: MQTT_Discovery: Invalid/Unhandled data received! (topic: zigbee2mqtt/bridge/config, message: {"commit":"9996c93","coordinator":{"meta":{"maintrel":0,"majorrel":38,"minorrel":120,"product":0,"revision":"0x26780700","transportrev":0},"type":"ConBee2/RaspBee2"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":false,"version":"1.33.2"})
```
It looks like it's the announce of Z2M that MQTT_AD does not handle. I'm not sure it contains anything usefull for Domoticz but the error is annoying. Should it be ignored by MQTT_AD ? Is there a way to prevent this message from appearing in the logs (but keeping other error related messages) ?

**Comment by gizmocuz** [comment]
In Zigbee2MQTT and in Domoticz you have configured the MQTT Auto Discovery topic to be something like 'domoticz' or have kept the default 'homeassistant'?
It looks you have both publish and auto discovery topic set to 'zigbee2mqtt'
Go to Settings, Advanced, and go to Home Assistant integration, and change the discovery topic (and afterwards also in Domoticz)
Or if this settings is correct, change it in domoticz

**Comment by niawag** [comment]
Thanks, that was the problem indeed, I setup "zigbee2mqtt" as the discovery topic without knowing it was also used as the base topic which mixed up both type of messages.
