### ISSUE TITLE
daylight saving change breaks french teleinfo power meter

### ISSUE THREAD

**Issue by jfzw42** [domoticz/domoticz#586]
Hello

We switched to summer time here during the saturday-sunday night (hour++). The weekly report for electricity power consumption is broken : sunday stats are added to saturday stats (4 values instead of 2 values for the same day).

![teleinfo-daylightsaving-bug](https://cloud.githubusercontent.com/assets/11590540/14077845/636be72c-f4f0-11e5-93c2-06ce2d8f5ac8.PNG)

**Comment by gizmocuz** [comment]
Use our forum, there is a search option, and also an answer
Look specifically under bugs/problems (first or second post)

**Comment by jfzw42** [comment]
Apologies for that, I will remember that for next time.
Regards
Jf
