### ISSUE TITLE
Current Graph not displayed when activated from a Floorplan

### ISSUE THREAD

**Issue by mealgi** [domoticz/domoticz#5860]
Hello,

Issue : Current Graph not displayed when activated from a Floorplan whereas it is correctly displayed when activated from the utility dashboard.

Context:

-Hardware : RPI3B+
-Version: 2023.2 (build 15607)
-Build Hash: 3a03efa60-modified
-Compile Date: 2023-10-20 09:07:12
-dzVents Version: 3.1.8
-Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]

I found out the root cause of the issue in Current function in domoticzdevices.js source 

1 - Version from GitHub

function Current(item) {
    if (arguments.length != 0) {
        this.parent.constructor(item);
        this.status = '';
        if (typeof item.Usage != 'undefined') {
            this.status = (item.Usage != this.data) ? item.Usage : '';
        }
        if (typeof item.CounterToday != 'undefined') {
            this.status += ' ' + $.t("Today") + ': ' + item.CounterToday;
        }
        if (typeof item.CounterDeliv != 'undefined') {
            if (item.CounterDeliv != 0) {
                if (item.UsageDeliv.charAt(0) != 0) {
                    this.status += '-' + item.UsageDeliv;
                }
                this.status += ', ' + $.t("Return") + ': ' + item.CounterDelivToday;
            }
        }
        switch (this.type) {
            case "Energy":
                this.LogLink = this.onClick = "window.location.href = '#/Devices/" + this.index + "/Log'";
                this.smallStatus = this.data;
                break;
            case "Usage":
                this.LogLink = this.onClick = "window.location.href = '#/Devices/" + this.index + "/Log'";
                break;
            case "General":
                switch (this.subtype) {
                    case "kWh":
                        this.LogLink = this.onClick = "window.location.href = '#/Devices/" + this.index + "/Log'";
                        this.smallStatus = this.data;
                        break;
                    case "Voltage":
                        this.LogLink = this.onClick = "window.location.href = '#/Devices/" + this.index + "/Log'";
                        this.smallStatus = this.data;
                        break;
                    default:
                        this.LogLink = this.onClick = "ShowCurrentLog('#" + Device.contentTag + "','" + Device.backFunction + "','" + this.index + "','" + this.name + "', '" + this.switchTypeVal + "');";
                        break;
                }
                break;
            default:
                this.LogLink = this.onClick = "ShowCurrentLog('#" + Device.contentTag + "','" + Device.backFunction + "','" + this.index + "','" + this.name + "', '" + this.switchTypeVal + "');";
                break;
        }
        this.smallStatus = this.smallStatus.split(', ')[0];
    }
}
Current.inheritsFrom(UtilitySensor);

2 - Proposed solution to fix the issue : Add the following lines in function Current(item)
                    case "Current":		// Current Graph Log added
                        this.LogLink = this.onClick = "window.location.href = '#/Devices/" + this.index + "/Log'";
                        this.smallStatus = this.data;
                        break;
as shown below:

function Current(item) {
    if (arguments.length != 0) {
        this.parent.constructor(item);
        this.status = '';
        if (typeof item.Usage != 'undefined') {
            this.status = (item.Usage != this.data) ? item.Usage : '';
        }
        if (typeof item.CounterToday != 'undefined') {
            this.status += ' ' + $.t("Today") + ': ' + item.CounterToday;
        }
        if (typeof item.CounterDeliv != 'undefined') {
            if (item.CounterDeliv != 0) {
                if (item.UsageDeliv.charAt(0) != 0) {
                    this.status += '-' + item.UsageDeliv;
                }
                this.status += ', ' + $.t("Return") + ': ' + item.CounterDelivToday;
            }
        }
        switch (this.type) {
            case "Energy":
                this.LogLink = this.onClick = "window.location.href = '#/Devices/" + this.index + "/Log'";
                this.smallStatus = this.data;
                break;
            case "Usage":
                this.LogLink = this.onClick = "window.location.href = '#/Devices/" + this.index + "/Log'";
                break;
            case "General":
                switch (this.subtype) {
                    case "kWh":
                        this.LogLink = this.onClick = "window.location.href = '#/Devices/" + this.index + "/Log'";
                        this.smallStatus = this.data;
                        break;
                    case "Voltage":
                        this.LogLink = this.onClick = "window.location.href = '#/Devices/" + this.index + "/Log'";
                        this.smallStatus = this.data;
                        break;
                    case "Current":		// Current Graph Log added
                        this.LogLink = this.onClick = "window.location.href = '#/Devices/" + this.index + "/Log'";
                        this.smallStatus = this.data;
                        break;
                    default:
                        this.LogLink = this.onClick = "ShowCurrentLog('#" + Device.contentTag + "','" + Device.backFunction + "','" + this.index + "','" + this.name + "', '" + this.switchTypeVal + "');";
                        break;
                }
                break;
            default:
                this.LogLink = this.onClick = "ShowCurrentLog('#" + Device.contentTag + "','" + Device.backFunction + "','" + this.index + "','" + this.name + "', '" + this.switchTypeVal + "');";
                break;
        }
        this.smallStatus = this.smallStatus.split(', ')[0];
    }
}
Current.inheritsFrom(UtilitySensor);

This has been tested succesfully

BR

**Comment by gizmocuz** [comment]
Thanks for the issue/solution. Coudl you make a pull request (PR) for this?

Steps to perform:

Fork the domoticz project
checkout your forked project
make the changes, commit and push
On your forked projects page you should see a option to create a PR

**Comment by mealgi** [comment]
Done,

**Comment by gizmocuz** [comment]
Thank you , but I do not see the PR?

**Comment by mealgi** [comment]
Could you check now ?

**Comment by mealgi** [comment]
Hello

 

Could you check now ?

 

BR

 

De : gizmocuz ***@***.***> 
Envoyé : jeudi 2 novembre 2023 17:08
À : domoticz/domoticz ***@***.***>
Cc : mealgi ***@***.***>; Author ***@***.***>
Objet : Re: [domoticz/domoticz] Current Graph not displayed when activated from a Floorplan (Issue #5860)

 

Thank you , but I do not see the PR?

**Comment by gizmocuz** [comment]
Thanks, found it, looks good!
Please do NOT reply by email to github messages but go directly to Github, you are exposing sensitive information like your email address and all kinds of data that should not be here.
I Edited your comments

**Comment by gizmocuz** [comment]
PR is merged, thank you!
