### ISSUE TITLE
Water Meter Graph not displayed when activated from a Floorplan 

### ISSUE THREAD

**Issue by mealgi** [domoticz/domoticz#5863]
Hello,

Issue : Water Meter Graph not displayed when activated from a Floorplan whereas it is correctly displayed when activated from the utility dashboard.

Context:

-Hardware : RPI3B+
-Version: 2023.2 (build 15607)
-Build Hash: https://github.com/domoticz/domoticz/commit/3a03efa60c2d1c84d831e4fb32c3cb2024abf193-modified
-Compile Date: 2023-10-20 09:07:12
-dzVents Version: 3.1.8
-Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]

Proposed Solution :

I found out the root cause of the issue in Sensor(item) function in domoticzdevices.js source

line 1216:
Replace		this.LogLink = this.onClick = "Show" + sensorType + "Log('#" + Device.contentTag + "','" + Device.backFunction + "','" + this.index + "','" + this.name + "', '" + this.switchTypeVal + "');";
        
by 
		        if (sensorType === 'RFXMeter')	
					this.LogLink = this.onClick = "window.location.href = '#/Devices/" + this.index + "/Log'";
			else
					this.LogLink = this.onClick = "Show" + sensorType + "Log('#" + Device.contentTag + "','" + Device.backFunction + "','" + this.index + "','" + this.name + "', '" + this.switchTypeVal + "');";
        
Solution to fix the issue has been tested successfully.
I created a PR accordingly.
BR

**Comment by gizmocuz** [comment]
Thanks for the PR, it is merged!
