### ISSUE TITLE
mainworker seems to have ended or hung unexpectedly

### ISSUE THREAD

**Issue by ilexpl01** [domoticz/domoticz#5866]
I am running domoticz newest version:

Version: 2023.2 (build 15621)
Build Hash: c3bf9d365
Compile Date: 2023-10-26 14:26:38
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

Based on Synology RS820+ DSM7.1. 

Once a week or moreDomoticz does restart on its own.  Below some log lines:

023/11/05 06:10:00	stdout	2023-11-05 06:09:56.969  Status: : Create instance
2023/11/05 06:09:56	stdout	2023-11-05 06:09:56.969  Status: PluginSystem: Started, Python version '3.9.2', 13 plugin definitions loaded.
2023/11/05 06:09:54	stdout	2023-11-05 06:09:53.788  Astronomical twilight start: 04:48:00 Astronomical twilight end: 18:03:00
2023/11/05 06:09:54	stdout	2023-11-05 06:09:53.788  Nautical twilight start: 05:27:00 Nautical twilight end: 17:24:00
2023/11/05 06:09:54	stdout	2023-11-05 06:09:53.788  Civil twilight start: 06:07:00 Civil twilight end: 16:44:00
2023/11/05 06:09:54	stdout	2023-11-05 06:09:53.788  Day length: 09:25:00 Sun at south: 11:25:00
2023/11/05 06:09:54	stdout	2023-11-05 06:09:53.788  Sunrise: 06:43:00 SunSet: 16:08:00
2023/11/05 06:09:54	stdout	2023-11-05 06:09:52.253  Status: Startup Path: /opt/domoticz/
2023/11/05 06:09:52	stdout	2023-11-05 06:09:52.253  Status: Build Hash: c3bf9d365, Date: 2023-10-26 14:26:38
2023/11/05 06:09:52	stdout	2023-11-05 06:09:52.253  Status: Domoticz V2023.2 (build 15621) (c)2012-2023 GizMoCuz
2023/11/05 06:07:19	stdout	2023-11-05 06:07:18.258  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 441.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:17.386  Status: Mainworker Stopped...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:17.257  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 440.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.324  Status: PluginSystem: Stopped.
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.314  Status: PluginSystem: Exited work loop.
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.312  Status: NotificationSystem: thread stopped...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.312  Status: EventSystem - Python stopped...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.308  Status: EventSystem: Stopped...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.308  Status: EventSystem: Queue thread stopped...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.308  Status: Scheduler stopped...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.308  Status: Alarm Integra: Destroy instance
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.307  Status: Alarm Integra: worker stopped
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.296  Status: MQTT WAN: Worker stopped...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.296  Status: Yamaha: Stopped.
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.296  Status: Yamaha: Stopping threads.
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.257  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 439.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.216  Status: Yamaha: Exiting work loop.
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.196  [1;31mError: Yamaha: Stop: Device 'Yamaha - Straight Mode' Reference Count not correct, expected 1 found 2.[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.196  [1;31mError: Yamaha: Stop: Device 'Yamaha - Scene Main' Reference Count not correct, expected 1 found 2.[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.196  [1;31mError: Yamaha: Stop: Device 'Yamaha - DSP Program' Reference Count not correct, expected 1 found 2.[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.196  [1;31mError: Yamaha: Stop: Device 'Yamaha - Input Main' Reference Count not correct, expected 1 found 2.[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.196  [1;31mError: Yamaha: Stop: Device 'Yamaha - Volume Main' Reference Count not correct, expected 1 found 2.[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.196  [1;31mError: Yamaha: Stop: Device 'Yamaha - Main' Reference Count not correct, expected 1 found 2.[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.196  Yamaha: onStop called
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.196  Status: Yamaha: Stop directive received.
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.196  Status: PPMs: Stopped.
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.196  Status: PPMs: Stopping threads.
2023/11/05 06:07:19	stdout	2023-11-05 06:07:16.124  Status: PPMs: Exiting work loop.
2023/11/05 06:07:19	stdout	2023-11-05 06:07:15.975  [1;31mError: PPMs: Stop: Device 'PPMs - PP Manager API Transport' Reference Count not correct, expected 1 found 2.[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:15.975  PPMs: Uninstalling plugin custom page completed.
2023/11/05 06:07:19	stdout	2023-11-05 06:07:15.652  PPMs: Uninstalling plugin custom page...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:15.257  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 438.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:14.995  Status: PPMs: Stop directive received.
2023/11/05 06:07:19	stdout	2023-11-05 06:07:14.985  Status: MQTT LAN: Worker stopped...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:14.984  Status: Fritzbox: Worker stopped...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:14.983  Status: Monitoring urządzeń ping: Worker stopped...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:14.257  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 437.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:13.257  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 436.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:12.256  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 435.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:11.798  Status: Stopping all hardware...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:11.798  Status: TCPServer: shared server stopped
2023/11/05 06:07:19	stdout	2023-11-05 06:07:11.796  Status: WebServer(SSL) stopped
2023/11/05 06:07:19	stdout	2023-11-05 06:07:11.679  [1;31mError: MQTT LAN: disconnected, restarting (rc=7/The connection was lost.)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:11.296  Status: WebServer(HTTP) stopped
2023/11/05 06:07:19	stdout	2023-11-05 06:07:11.256  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 434.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:10.789  Status: RxQueue: queue worker stopped...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:10.780  Status: Ending automatic database backup procedure...
2023/11/05 06:07:19	stdout	2023-11-05 06:07:10.256  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 433.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:09.255  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 432.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:08.255  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 431.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:07.255  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 430.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:06.255  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 429.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:05.254  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 428.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:04.254  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 427.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:03.254  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 426.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:02.254  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 425.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:01.253  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 424.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:07:00.253  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 423.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:59.253  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 422.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:58.253  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 421.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:57.252  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 420.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:56.252  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 419.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:55.252  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 418.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:54.252  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 417.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:51.710  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 414.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:50.709  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 413.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:49.709  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 412.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:48.709  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 411.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:47.709  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 410.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:46.708  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 409.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:45.708  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 408.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:44.708  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 407.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:43.707  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 406.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:42.707  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 405.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:41.707  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 404.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:40.707  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 403.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:39.706  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 402.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:38.706  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 401.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:37.706  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 400.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:36.706  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 399.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:35.705  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 398.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:34.705  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 397.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:33.705  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 396.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:32.704  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 395.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:31.704  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 394.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:30.704  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 393.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:29.703  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 392.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:28.703  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 391.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:27.703  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 390.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:26.702  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 389.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:25.702  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 388.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:24.702  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 387.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:23.702  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 386.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:22.702  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 385.000000 seconds ago)[0;0m
2023/11/05 06:07:19	stdout	2023-11-05 06:06:21.701  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 384.000000 seconds ago)[0;0m
2023/11/05 06:06:20	stdout	2023-11-05 06:06:20.701  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 383.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:19.701  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 382.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:18.701  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 381.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:17.700  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 380.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:16.700  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 379.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:15.700  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 378.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:14.699  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 377.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:13.699  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 376.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:12.631  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 375.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:11.631  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 374.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:10.631  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 373.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:09.631  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 372.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:08.630  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 371.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:07.630  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 370.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:06.630  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 369.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:05.630  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 368.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:04.629  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 367.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:03.629  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 366.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:02.629  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 365.000000 seconds ago)[0;0m
2023/11/05 06:06:19	stdout	2023-11-05 06:06:01.628  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 364.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:06:00.628  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 363.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:59.628  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 362.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:58.627  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 361.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:57.627  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 360.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:56.627  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 359.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:55.627  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 358.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:54.626  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 357.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:53.626  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 356.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:52.626  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 355.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:51.626  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 354.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:50.625  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 353.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:49.625  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 352.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:48.625  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 351.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:47.624  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 350.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:46.624  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 349.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:45.624  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 348.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:44.624  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 347.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:43.623  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 346.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:42.623  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 345.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:41.623  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 344.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:40.622  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 343.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:39.622  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 342.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:38.622  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 341.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:37.622  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 340.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:36.621  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 339.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:32.457  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 335.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:31.456  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 334.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:30.456  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 333.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:29.456  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 332.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:28.456  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 331.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:27.455  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 330.000000 seconds ago)[0;0m
2023/11/05 06:06:00	stdout	2023-11-05 06:05:26.455  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 329.000000 seconds ago)[0;0m
2023/11/05 06:05:25	stdout	2023-11-05 06:05:25.455  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 328.000000 seconds ago)[0;0m
2023/11/05 06:05:24	stdout	2023-11-05 06:05:24.455  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 327.000000 seconds ago)[0;0m
2023/11/05 06:05:24	stdout	2023-11-05 06:05:23.454  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 326.000000 seconds ago)[0;0m
2023/11/05 06:05:24	stdout	2023-11-05 06:05:22.454  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 325.000000 seconds ago)[0;0m
2023/11/05 06:05:24	stdout	2023-11-05 06:05:21.453  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 324.000000 seconds ago)[0;0m
2023/11/05 06:05:24	stdout	2023-11-05 06:05:20.453  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 323.000000 seconds ago)[0;0m
2023/11/05 06:05:24	stdout	2023-11-05 06:05:19.453  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 322.000000 seconds ago)[0;0m
2023/11/05 06:05:24	stdout	2023-11-05 06:05:18.453  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 321.000000 seconds ago)[0;0m
2023/11/05 06:05:24	stdout	2023-11-05 06:05:17.452  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 320.000000 seconds ago)[0;0m
2023/11/05 06:05:24	stdout	2023-11-05 06:05:16.452  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 319.000000 seconds ago)[0;0m
2023/11/05 06:05:24	stdout	2023-11-05 06:05:15.452  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 318.000000 seconds ago)[0;0m
2023/11/05 06:05:24	stdout	2023-11-05 06:05:10.030  Status: Stopping worker...
2023/11/05 06:05:24	stdout	2023-11-05 06:05:10.030  Status: Closing application!...
2023/11/05 06:05:24	stdout	[0;0m
2023/11/05 06:05:24	stdout	2023-11-05 06:05:09.451  [1;31mError: Failed to start gdb, will use backtrace() for printing stack frame
2023/11/05 06:05:05	stdout	2023-11-05 06:05:05.048  [1;31mError: Domoticz(1) is exiting due to watchdog triggered...[0;0m
2023/11/05 06:04:58	stdout	2023-11-05 06:04:58.829  [1;31mError: mainworker seems to have ended or hung unexpectedly (last update 301.000000 seconds ago)[0;0m
2023/11/05 06:00:26	stdout	2023-11-05 06:00:26.737  Status: Starting automatic database backup procedure...
2023/11/05 05:59:47	stdout	2023-11-05 05:59:11.028  [1;31mError: dzVents: Error: (3.1.8) lastSeen: ------ Finished Nadzór czujników after >11 seconds. (using 0.371 seconds CPU time !)[0;0m
2023/11/05 05:59:10	stdout	2023-11-05 05:59:10.395  [1;31mError: EventSystem: Warning!, lua script /opt/domoticz/dzVents/runtime/dzVents.lua has been running for more than 10 seconds[0;0m
2023/11/05 05:59:00	stdout	2023-11-05 05:58:59.914  Status: [web:8080] Incoming connection from: 172.17.0.1

Two weeks ago I moved domoticz container from DS720 to current rs820. 

I used to have the same issue before that as well.

Any hint ?

**Comment by gizmocuz** [comment]
Best to ask this on our Forum.
Disable the Event System and Python in the settings and see if that solves the problem.
(I expect it will)
Next try to find out which script is blocking or causing the error

**Comment by ilexpl01** [comment]
Hi.

Recently, almost every day at midnight, Domoticz restarted with an error message.

I turned off the built-in backup function 3 days ago and... the problem disappeared!

Of course, I make copies using Synology tools.

I am currently using Domoticz version 2024.1 (build 15792), database size: 90MB

Any hint ?

**Comment by gizmocuz** [comment]
That is a very large database!
Better open it in SQLite Expert Personal edition and check what it is making so extreme large.
As first domoticz used my db size is less than a third with quite a few devices.

Making a backup that way is also dangerous and I would not do this

Once in a while I make a backup from the settings page

And please use our forum
