### ISSUE TITLE
MQTT Auto Discovery generates 3 temp/temp&hum sensors but updates are send wrongly to 1 sensor only

### ISSUE THREAD

**Issue by Waakvlam** [domoticz/domoticz#5867]
I have a Froggit GW2000 weatherstation (PWS). It is connected via Ecowitt2MQTT to a Mosquitto server and with the "MQTT Auto Discovery from LAN" connected to Domoticz. When (re-starting) the MQTT AD it generates all sensors correctly. All is working fine except the 2 sensors "Temp Binnen" and "GW2000 Binnen".
When I restart the MQTT AD from LAN (press update on the hardware page) the temperature (tempin) and humidity (humidityin) values from the GW2000 gateway are correctly send to the right sensors "Temp Binnen" and "GW2000 Binnen". But all it's values thereafter are wrongly send to the sensor "GW2000 Buiten". Straight thereafter "GW2000 Buiten" receives it's correct values (temp & humidity), so "GW2000 Buiten" is then correct again. But "Temp Binnen" and "GW2000 Binnen" are not updated anymore, it looks like they are not receiving data anymore.

After pressing Update journalctl shows (info edited):

Oct 24 11:36:06 domoticz domoticz[352019]: 2023-10-24 11:36:06.881 Status: Ecowitt2mqtt: discovered: GW2000/runtime (unique_id: BDAFCCBA2F5CA4FDC76E19C8A869845A_runtime)
Oct 24 11:36:06 domoticz ecowitt2mqtt[347134]: 2023-10-24 11:36:06,990 | INFO | Published to Home Assistant MQTT Discovery
Oct 24 11:36:07 domoticz domoticz[352019]: 2023-10-24 11:36:07.198 Ecowitt2mqtt: General/Custom Sensor (runtime)
Oct 24 11:36:07 domoticz domoticz[352019]: 2023-10-24 11:36:07.302 **Status: Ecowitt2mqtt: discovered: GW2000/tempin (unique_id: BDAFCCBA2F5CA4FDC76E19C8A869845A_tempin)**
Oct 24 11:36:07 domoticz domoticz[352019]: 2023-10-24 11:36:07.608 **Ecowitt2mqtt: Temp/THR128/138, THC138 (Temp Binnen)**
Oct 24 11:36:07 domoticz domoticz[352019]: 2023-10-24 11:36:07.711 **Status: Ecowitt2mqtt: discovered: GW2000/humidityin (unique_id: BDAFCCBA2F5CA4FDC76E19C8A869845A_humidityin)**
Oct 24 11:36:08 domoticz domoticz[352019]: 2023-10-24 11:36:08.026 **Ecowitt2mqtt: Temp + Humidity/THGN122/123/132, THGR122/228/238/268 (GW2000 Binnen)**
Oct 24 11:36:08 domoticz domoticz[352019]: 2023-10-24 11:36:08.130 Status: Ecowitt2mqtt: discovered: GW2000/baromrel (unique_id: BDAFCCBA2F5CA4FDC76E19C8A869845A_baromrel)
Oct 24 11:36:08 domoticz domoticz[352019]: 2023-10-24 11:36:08.436 Ecowitt2mqtt: Temp + Humidity + Baro/Weather Station (GW2000 Buiten)
Oct 24 11:36:08 domoticz domoticz[352019]: 2023-10-24 11:36:08.540 Status: Ecowitt2mqtt: discovered: GW2000/baromabs (unique_id: BDAFCCBA2F5CA4FDC76E19C8A869845A_baromabs)
Oct 24 11:36:08 domoticz domoticz[352019]: 2023-10-24 11:36:08.880 **Ecowitt2mqtt: Temp + Humidity + Baro/Weather Station (GW2000 Buiten)**
Oct 24 11:36:09 domoticz domoticz[352019]: 2023-10-24 11:36:09.009 Status: **Ecowitt2mqtt: discovered: GW2000/temp (unique_id: BDAFCCBA2F5CA4FDC76E19C8A869845A_temp)**
Oct 24 11:36:09 domoticz domoticz[352019]: 2023-10-24 11:36:09.314 **Ecowitt2mqtt: Temp + Humidity + Baro/Weather Station (GW2000 Buiten)**
Oct 24 11:36:09 domoticz domoticz[352019]: 2023-10-24 11:36:09.418 Status: **Ecowitt2mqtt: discovered: GW2000/humidity (unique_id: BDAFCCBA2F5CA4FDC76E19C8A869845A_humidity)**
Oct 24 11:36:09 domoticz domoticz[352019]: 2023-10-24 11:36:09.723 Ecowitt2mqtt: Temp + Humidity + Baro/Weather Station (GW2000 Buiten)

Then one minute later it receives an update:

Oct 24 11:37:08 domoticz domoticz[352019]: 2023-10-24 11:37:08.412 Status: Ecowitt2mqtt: discovered: GW2000/tempin (unique_id: BDAFCCBA2F5CA4FDC76E19C8A869845A_**tempin**)
Oct 24 11:37:08 domoticz domoticz[352019]: 2023-10-24 11:37:08.755 Ecowitt2mqtt: Temp + Humidity + Baro/Weather Station (**GW2000 Buiten**)
Oct 24 11:37:08 domoticz domoticz[352019]: 2023-10-24 11:37:08.868 Status: Ecowitt2mqtt: discovered: GW2000/humidityin (unique_id: BDAFCCBA2F5CA4FDC76E19C8A869845A_**humidityin**)
Oct 24 11:37:09 domoticz domoticz[352019]: 2023-10-24 11:37:09.184 Ecowitt2mqtt: Temp + Humidity + Baro/Weather Station (**GW2000 Buiten)**

Oct 24 11:37:10 domoticz domoticz[352019]: 2023-10-24 11:37:10.060 Ecowitt2mqtt: Temp + Humidity + Baro/Weather Station (GW2000 Buiten)
Oct 24 11:37:10 domoticz domoticz[352019]: 2023-10-24 11:37:10.165 Status: Ecowitt2mqtt: discovered: GW2000/temp (unique_id: BDAFCCBA2F5CA4FDC76E19C8A869845A_**temp)**
Oct 24 11:37:10 domoticz domoticz[352019]: 2023-10-24 11:37:10.505 Ecowitt2mqtt: Temp + Humidity + Baro/Weather Station (**GW2000 Buiten**)
Oct 24 11:37:10 domoticz domoticz[352019]: 2023-10-24 11:37:10.610 Status: Ecowitt2mqtt: discovered: GW2000/humidity (unique_id: BDAFCCBA2F5CA4FDC76E19C8A869845A_**humidity**)
Oct 24 11:37:10 domoticz domoticz[352019]: 2023-10-24 11:37:10.915 Ecowitt2mqtt: Temp + Humidity + Baro/Weather Station (**GW2000 Buiten**)

The command _mosquitto_sub -t \ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/tempin/state_ gives the correct values and so does the command for humidityin.

From mqtt-explorer:

> {"availability_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/tempin/availability", "device": {"identifiers": ["BDAFCCBA2F5CA4FDC76E19C8A869845A"], "manufacturer": "Ecowitt", "model": "GW2000A", "name": "GW2000", "sw_version": "GW2000A_V3.0.8"}, "json_attributes_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/tempin/attributes", "name": "tempin", "qos": 1, "retain": false, "state_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/tempin/state", "unique_id": "BDAFCCBA2F5CA4FDC76E19C8A869845A_tempin", "unit_of_measurement": "\u00b0C", "device_class": "temperature", "state_class": "measurement"}

> {"availability_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/humidityin/availability", "device": {"identifiers": ["BDAFCCBA2F5CA4FDC76E19C8A869845A"], "manufacturer": "Ecowitt", "model": "GW2000A", "name": "GW2000", "sw_version": "GW2000A_V3.0.8"}, "json_attributes_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/humidityin/attributes", "name": "humidityin", "qos": 1, "retain": false, "state_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/humidityin/state", "unique_id": "BDAFCCBA2F5CA4FDC76E19C8A869845A_humidityin", "unit_of_measurement": "%", "device_class": "humidity", "state_class": "measurement"}

> {"availability_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/temp/availability", "device": {"identifiers": ["BDAFCCBA2F5CA4FDC76E19C8A869845A"], "manufacturer": "Ecowitt", "model": "GW2000A", "name": "GW2000", "sw_version": "GW2000A_V3.0.8"}, "json_attributes_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/temp/attributes", "name": "temp", "qos": 1, "retain": false, "state_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/temp/state", "unique_id": "BDAFCCBA2F5CA4FDC76E19C8A869845A_temp", "unit_of_measurement": "\u00b0C", "device_class": "temperature", "state_class": "measurement"}

> {"availability_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/humidity/availability", "device": {"identifiers": ["BDAFCCBA2F5CA4FDC76E19C8A869845A"], "manufacturer": "Ecowitt", "model": "GW2000A", "name": "GW2000", "sw_version": "GW2000A_V3.0.8"}, "json_attributes_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/humidity/attributes", "name": "humidity", "qos": 1, "retain": false, "state_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/humidity/state", "unique_id": "BDAFCCBA2F5CA4FDC76E19C8A869845A_humidity", "unit_of_measurement": "%", "device_class": "humidity", "state_class": "measurement"}

I was wondering what could be done to get the tempin & humidityin values to the right sensors? Is more info needed or is this too much already? I have asked this question already on the forum but there was no solution yet except to create an issue here.

Configuration:
Platform: Linux, Debian 12
Weather Station: Froggit GW-2000 + WS-90
Ecowitt2MQTT version 2023.08.0
Mosquitto version 2.0.11
Domoticz Version: 2023.2 (build 15636)
Build Hash: aee946b65
Compile Date: 2023-11-04 09:53:42
dzVents Version: 3.1.8
Python Version: 3.11.2

**Comment by gizmocuz** [comment]
This is not possible.
There is no way how we should know which sensors belong to each other.
What 'Ecowitt2MQTT' could/should do is to use make two separate sensors.
Right now, I think all values are con figured in one sensor?

You should be able to see this when using MQTT Explorer:

topic:
homeassistant/sensor/xxxxxxxx/yyyy/config

I miss the topic names of your config objects in your previous post

But I think you have to run two instances of 'ecowitt2mqtt', one for each hardware with a different port, and configure the device to use the right ecowitt2mqtt

So you do get two devices/sensors

**Comment by Waakvlam** [comment]
Thanks for the quick reply!

> There is no way how we should know which sensors belong to each other.
What 'Ecowitt2MQTT' could/should do is to use make two separate sensors.

 I think I did not explain myself correctly or I misunderstand what ecowitt2MQTT should do. The sensors should not belong to each other, they should be separated. I would like to see the temp**in** to be send to "Temp Binnen", humidity**in** to "GW2000 Binnen" and temp & humidity (without _in) to "GW2000 Buiten" (the latter one happens correctly now). There are 3 sensors created, also when I delete all 3 of them and then restart MQTT AD and the values are correct. But only for one update, thereafter the info of temp**in** is send to (GW2000 Buiten), which is not expected behaviour (I see the sensor "GW2000 Buiten" on the page flickering with the value of tempin and within a second changing to temp).

> I miss the topic names of your config objects in your previous post 

Sorry, I am not a specialist in mqtt-messages but I will do me best to get the correct info here asap..

**Comment by gizmocuz** [comment]
When there is a Temp + Humidity device, Domoticz is creating a Temp+Hum device
Again, in your current setup, you have 1 node (lets call it sensor) when two temps and two hums, and there is no way to know which should belong to which

So you should probably launch two different **ecowitt2MQTT** scripts, one for each of your hardware
You can use different ports and different hass-entity-id-prefix

**Comment by Waakvlam** [comment]
Thanks for keeping this issue open, I pressed the wrong button. The GW2000 in one station (with one IP-address) with 2 different sensors for Temp+Hum, one is in the house and one outside. I am not sure if it is possible to send the different sensors to a different port and hasss-entity-id-prefix. The sensors do have different eg. "availability_topic" or"unique_id" 's. Like I said, I do not understand much of MQTT. What I also don't understand is why, in Domoticz, the info is send correctly after pressing the update button of the "MQTT Autodiscovery Client Gateway with LAN" but not after consequent updates (in this case every minute).

> You should be able to see this when using MQTT Explorer:

> topic:

> homeassistant/sensor/xxxxxxxx/yyyy/config

Still struggling with it, I do my best..

**Comment by gizmocuz** [comment]
It could be the inside temp+hum sensor is more often updated then the outside sensor

Could you also post here the config topic names?

homeassistant/sensor/xxxxxxxx/yyyy/config

All temp+hum seem to have the same identifier (BDAFCCBA2F5CA4FDC76E19C8A869845A), but there are actually two different temp+hum sensors

**Comment by Waakvlam** [comment]
In MQTT-explorer I see the following:
ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/**tempin/config:**
_{
"availability_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/tempin/availability",
"device": 
{
"identifiers": ["BDAFCCBA2F5CA4FDC76E19C8A869845A"], 
"manufacturer": "Ecowitt",
"model": "GW2000A",
"name": "GW2000",
"sw_version": "GW2000A_V3.0.8"
},
"json_attributes_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/tempin/attributes",
"name": "tempin",
"qos": 1,
"retain": false,
"state_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/tempin/state",
"unique_id": "BDAFCCBA2F5CA4FDC76E19C8A869845A_tempin",
"unit_of_measurement": "\u00b0C",
"device_class": "temperature",
"state_class": "measurement"
}_

ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/**humidityin/config:**
_{
"availability_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/humidityin/availability",
"device": {
"identifiers": ["BDAFCCBA2F5CA4FDC76E19C8A869845A"],
"manufacturer": "Ecowitt",
"model": "GW2000A",
"name": "GW2000",
"sw_version": "GW2000A_V3.0.8"
},
"json_attributes_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/humidityin/attributes",
"name": "humidityin",
"qos": 1,
"retain": false,
"state_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/humidityin/state",
"unique_id": "BDAFCCBA2F5CA4FDC76E19C8A869845A_humidityin",
"unit_of_measurement": "%",
"device_class": "humidity",
"state_class": "measurement"
}_

ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/**temp/config:**
_{
"availability_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/temp/availability",
"device": {
"identifiers": ["BDAFCCBA2F5CA4FDC76E19C8A869845A"],
"manufacturer": "Ecowitt",
"model": "GW2000A",
"name": "GW2000",
"sw_version": "GW2000A_V3.0.8"
},
"json_attributes_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/temp/attributes",
"name": "temp",
"qos": 1,
"retain": false,
"state_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/temp/state",
"unique_id": "BDAFCCBA2F5CA4FDC76E19C8A869845A_temp",
"unit_of_measurement": "\u00b0C",
"device_class": "temperature",
"state_class": "measurement"
}_

ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/**humidity/config:**
_{
"availability_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/humidity/availability",
"device": {
"identifiers": ["BDAFCCBA2F5CA4FDC76E19C8A869845A"],
"manufacturer": "Ecowitt",
"model": "GW2000A",
"name": "GW2000",
"sw_version": "GW2000A_V3.0.8"
},
"json_attributes_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/humidity/attributes",
"name": "humidity",
"qos": 1,
"retain": false,
"state_topic": "ecowitt2mqtt/sensor/BDAFCCBA2F5CA4FDC76E19C8A869845A/humidity/state",
"unique_id": "BDAFCCBA2F5CA4FDC76E19C8A869845A_humidity",
"unit_of_measurement": "%", 
"device_class": "humidity",
"state_class": "measurement"
}_

All devices are being updated once a minute ( a couple of seconds after each other and the tempin before temp). They do have all the same identifier indeed.

**Comment by gizmocuz** [comment]
I'm sorry, but all 4 sensors share the save identifiers (BDAFCCBA2F5CA4FDC76E19C8A869845A)
If the other two had a different identifier it could be matched

**Comment by gizmocuz** [comment]
We now detect if there are multiple temp/hum or baro sensors are being reported for 1 device, and in this case, we threat all sensors separate

Should be solved in beta 15643

**Comment by Waakvlam** [comment]
> Should be solved in beta 15643

And it is! Thanks a lot for such a quick response and for this great product!
