### ISSUE TITLE
Error parsing json to LUA table: (invalid json string) 

### ISSUE THREAD

**Issue by TomMalfrere** [domoticz/domoticz#5868]
platform: raspberry pi
OS: Raspbian GNU/Linux 11 (bullseye)
Domoticz:
Version: 2023.2
Build Hash: 19efd039c
Compile Date: 2023-07-21 17:23:44
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]

Hi,

I have a webhook that posts meter readings to a server on the internet (energyid.eu).

On the callback I always get the following error twice in the logs:

Error: dzVents: Error: (3.1.8) Gasmeter and watermeter EnergyId webhook: Error parsing json to LUA table: (invalid json string) "OK"

Why do I get this error? 
I know the response is not JSON. Hence the commented out code.
I do want to check the HTTPResponse statuscode.

[2023-11-09 webhook.txt](https://github.com/domoticz/domoticz/files/13306667/2023-11-09.webhook.txt)
[2023-11-09 log.txt](https://github.com/domoticz/domoticz/files/13306668/2023-11-09.log.txt)

**Comment by gizmocuz** [comment]
I don't think this error is from not having the return result as JSON, but it is a problem in your main script
You also have two 'end' keywords at the bottom
Please double check your main script ... this should return a json object (see the return above)
Maybe start with a small example script and rebuilt your script step by step

**Comment by waltervl** [comment]
I am closing this issue as it seems a dzvents programming issue and should be discussed on the Dzvents subforum. If in the end it is a Domoticz issue it can be reopened.
