### ISSUE TITLE
VisualCrossing hardware does not work after upgrade to debian bullseye

### ISSUE THREAD

**Issue by elxsi** [domoticz/domoticz#5869]
Hi,

I've updated my domoticz system yesterday from Debian Buster to Debian Bullseye. Today I noticed, that my weather graphs which are using the VisualCrossing hardware did not update since yesterday. The domoticz.log always showed:

Nov  9 07:42:24 domoticz domoticz: VisualCrossing: Error getting http data!.
Nov  9 07:47:24 domoticz domoticz: VisualCrossing: Error getting http data!.
Nov  9 07:52:25 domoticz domoticz: VisualCrossing: Error getting http data!.

I manually verified, that I can retrieve the data from `https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/<mylocation>?key=<myapikey>&unitGroup=metric&include=current` using curl on the same system.

After this, I checked the code (hardware/VisualCrossing.cpp) around the error message:

```
void CVisualCrossing::GetMeterDetails()
{
        std::string sResult;
#ifdef DEBUG_VisualCrossingR
        sResult = ReadFile("E:\\VisualCrossing.json");
#else
        std::stringstream sURL;
        std::string szLoc = m_Location;
        sURL << "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/" << szLoc << "?key=" << m_APIKey << "&unitGroup=metric&include=current";
        try
        {
                if (!HTTPClient::GET(sURL.str(), sResult))
                {
                        Log(LOG_ERROR, "Error getting http data!.");
                        return;
                }
        }
        catch (...)
        {
                Log(LOG_ERROR, "Error getting http data!");
                return;
        }

```

Adding some debug output and further checking the HTTPClient::GET and HTTPClient::GETBinary functions showed, that the URL (sURL in VisualCrossing.cpp) does not seem to get urlencoded. According to the domoticz webinterface, you can add a StationID or Latitude, Longitude. I've configured the parameter to use Latitude and Longitude in the past:

49.132723, 13.121340 (I've changed this for privacy reasons)

This has worked without any problems in the past but stopped working after my upgrade from Debian Buster to Debian Bullseye. Changing the value for Latitude/Longitude to a urlencoded format in the domoticz web ui from

49.132723, 13.121340 to 49.132723%2C%2013.121340

did fix this issue. I don't know the reason why this did work before (maybe the old libcurl did automatically urlencode this?), but I think the real fix is to change the  CVisualCrossing::GetMeterDetails() function in line 129 to

```
std::string szLoc = CURLEncode::URLEncode(m_Location);

like already been used in the CVisualCrossing::GetForecastURL() function.

```
Thank you!

**Comment by gizmocuz** [comment]
Thanks for reporting. In the forecast function above it is also urlencoded and I think you could be right!
Beta 15641 should solve the issue
