### ISSUE TITLE
The SetColor event provides not current but previous one of RGB values, from RGB, RGBW RGBWW switches

### ISSUE THREAD

**Issue by csipeter** [domoticz/domoticz#5871]
Platform: Intel 12th gen i3 16GB RAM bare metal (not virtualized)
OS: Debian GNU Linux 12, kernel: Linux 6.1.0-13-amd64 on x86_64
Domoticz Version: 2023.2 (build 15643)
Compile Date: 2023-11-10 14:20:56
dzVents Version: 3.1.8
Python Version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0

Issue reproduction:
1. edit switch and set RGB color to FFFFFF
2. switch off the light
3. power off the light
4. systemctl stop domoticz
5. systemctl start domoticz
6. power on the light (it will lighting)
7. switch off the light
8. power on the light on "Switches" tab
9. select RGB circle of the switch on "Switches" tab
10. pick a color (ex.: kind of BLUE)
11. ERROR: in "Set Color" event invoked device.getColor() method and got colormode (m) value as 2 wich means "White with color temperature"
12. when pick a light value from level selector at right side I got m value as 3 and the picked blue RGB value wich was chosen earlier
13. from this point of test when I pick any color from picker the getColor() returns previous one RGB levels (against current picked value), and only when I pick any value from level-picker can get the correct RGB values by getColor() method.

The DZVents script what I wrote for SONOFF RGB Bulb with DIYmode here:
https://pastebin.com/1DDjKnuN

**Comment by gizmocuz** [comment]
Is this with Yeelight, Zigbee, zwave, rflink or other hardware?

**Comment by csipeter** [comment]
> Is this with Yeelight, Zigbee, zwave, rflink or other hardware?

This is Sonoff B05-BL-A60 Smart RGB bulb in DIY mode.
But I think it is independent from hardware. It is a Virtual RGBWW switch from DUMMY device in Domoticz. 
Seeming the color picker gives wrong values.

**Comment by gizmocuz** [comment]
Don't have this issue with MQTT-AD (zigbee/zwave)
But it is a bit hard to test... can't power off a dummy
And who is updating the dummy?
If you update the dummy via the JSON code does it reflect the changes when you open the popup ?
Maybe you can let the Sonoff try to talk MQTT-AD or let the device use ESPHome?

**Comment by csipeter** [comment]
I think You misunderstood my process, cose I wasn't exact enough.
I power off **the phisical Sonoff** device (resetting it).
It is just a simple bulb... not has any remote control or any other controller.
I communicate with it by HTTP API using Domoticz. The main goal is synchronize the color between the bulb and Domoticz.
But I found that the color picker component behaves erratically in Domoticz (one step late).

**Comment by csipeter** [comment]
The relationship betwen the bulb and Domoticz is not equal. The bulb **_must_** do what Domoticz commands.
The users can handle the bulb trough Domoticz only.

**Comment by gizmocuz** [comment]
No I think we are talking about the same.
So you use the Domoticz HTTP/JSON API to send the state/colour to Domoticz correct?
Or do you use a third party library for this?
If you are sending the updated yourself via the JSON API, do you get the same behaviour when you have added a dummy RGB switch and update this?
Did you also try to refresh the browser before you use the color picker again?

**Comment by csipeter** [comment]
No. I don't use any third party library neither the Domoticz's HTTP/JSON API for sending data _to_ Domoticz.

I wrote a DZVents script what I have been linked in original post . In that script I read color _from_ Dummy RGBWW switch by getColor method.

So if you make a simple Dummy RGBWW switch and starting that name as OkosIzzo and use my script but comment out the communication lines (openURL). You will see in the log the effect what I speak. I think the issue is independent from communication. It is a bug somwhere around color picker itself.

**Comment by gizmocuz** [comment]
Okey, so when you make a dummy RGB switch and a Dummy selector switch with 4 states, one dzVents script that handles the change action for the selector switch, and for each of the states you set the dummy RGB switch either to on/off/red/blue, you experience a wrong color in the domoticz userinterface?

**Comment by csipeter** [comment]
:-) No.
There is a DUMMY (Does nothing use for virtual switches only) hardware.
I added a RGBWW virtual switch used that DUMMY hardware named "**OkosIzzo Apa**"
I wrote the script (link in starting post)
I clicked **Okosizzo Apa** switch on Switches tab (a small modal apear) and switched on.
![screenshot– 2023-11-12 11-27-31](https://github.com/domoticz/domoticz/assets/36097293/83120499-4155-46ce-92a6-7a4c9d538c2e)
The bulb lights up as it was set when turned off before. (that's OK) For example 80% warm white.
I pick a color eg. RED, by ColorSelector of **Okosizzo Apa** (on the small modal)... AND NOTHING HAPENS.
![screenshot– 2023-11-12 11-28-42](https://github.com/domoticz/domoticz/assets/36097293/e03ce357-b743-47c1-8e25-e01ed3e90e6f)

I pick another color eg. BLUE, and the bulb gets RED (chosen one step before).
That is how it works.

I investigated, that in DZVent **_device.getColor()_** method gives wrong result.
I think the getColor() method gives wrong result independently even if there is no any communication with bulb.

**Comment by gizmocuz** [comment]
Okey, I did what you did
Added a dummy RGB switch
Switched that one OFF
Switched it On
then selected a blue color

This is what I see in the log (status message)

2023-11-12 13:52:21.364  Status: setcolbrightnessvalue: ID: 2225, bri: 84, color: '{m: 3, RGB: 1b45ff, CWWW: 0000, CT: 0}'
2023-11-12 13:52:21.365  Status: Dummy: Received null operation for Color Switch
2023-11-12 13:52:21.370  Dummy: Color Switch (MyDummyColor)

So it is not doing NOTHING... 

When I now refresh the browser and go to the color wheel, I see that blue is selected

**Comment by gizmocuz** [comment]
Okey, I am a step further... I had to make myself a script... And as I'm not a scripter I hoped you could make one...
But now that I got one, the status in Domoticz is correct indeed, but the status in dzVents is behind!
So you're right here!
Let's see if this can be changed somewhere

**Comment by gizmocuz** [comment]
Think the problem is inside 'MainWorker::decode_ColorSwitch', it first updates the status and later set the color...
Need some more time to debug this

**Comment by csipeter** [comment]
Yes, You're right.
The Domoticz's log shows correct values for color. But DZVents device.getColor() gives old value, not currently set.
Thank You for investigating this bug!

**Comment by gizmocuz** [comment]
Yep, that was the case... I am still not 100% happy about that piece of code there... But it works correctly at least 😊
Could you test beta 15647 (available now), this should solve the issue.
Thanks for spotting!

**Comment by csipeter** [comment]
Tested.
Works.

You are the greatest my Lord!
Thank You very much!

**Comment by gizmocuz** [comment]
Wha... not the best.. 😊 ... just fixed a bug I introduced today (Enphase/Mitsubishi) .... Glad it's working!
(That new beta is available now as well)
