### ISSUE TITLE
Custom icon for RFXMeter counter shows up erroneous on Floorplan view

### ISSUE THREAD

**Issue by martin-g-it** [domoticz/domoticz#5872]
Version: Version: 2023.2 (build 15457) stable + Version: 2023.2 (build 15649) beta
Platform: Linux (Debian GNU/Linux 11 (bullseye))
Plugin/Hardware: n/a
Description: When a Custom icon is assigned to a RFXMeter counter (type Custom) it seems corrupted on the Floorplan 'view'

I've got a Custom RFXMeter counter (Heat usage); type Custom with:
Aslabel = Heat (GJ)
Unit: GJ

Values are shown correctly on normal dashboard; however when switched to floorplan, the icon seems corrupted and also the counter contains the meter reading instead of daily usage.

Observed with with latest stable and also tested with latest beta.

See screenshots.

![Domoticz bug - floorplan](https://github.com/domoticz/domoticz/assets/53882051/7105f3d6-c66e-48c1-9481-1bcfe453a451)

**Comment by gizmocuz** [comment]
I have the behaviour of your first screenshot with the latest beta version.
The floowplan is not displaying the custom icon, but the default icon

**Comment by gizmocuz** [comment]
I think I now implemented custom icons for meter devices in beta 15650
Is it possible to check this?
I did not modify any labels... only the icons.
If labels are wrong/swapped, it needs to be changed in www/js/domoticzdevices.js

**Comment by martin-g-it** [comment]
The icon is now working; the counter however (still) shows the meter reading instead of todays usage.

**Comment by gizmocuz** [comment]
Want to have a look in www/js/domoticzdevices.js to see if you can fix that?

**Comment by martin-g-it** [comment]
In the `function Counter(item) {` (line 1416) of the domoticzdevices.js, I have put a `console.log('item.CounterToday:', item.CounterToday);`.

With the '**default**' icon assigned to the device I do get output on the console with todays counter. 
With a '**custom**' icon assigned to the device, there is **no** output as if the logic is not being called anymore..

Checking further, it seems like the `function Sensor(item)` is called 8 times for the device regardless the icon assigned. The `function UtilitySensor` and `function Counter ` however are only called when the **default** icon is assigned...

Update:
by adding some code from `function Counter(item)` at the end of `function Sensor(item)`, I was able to fix it.
![image](https://github.com/domoticz/domoticz/assets/53882051/7aee68fb-c578-4cf5-acd3-6862866f839a)


		if (typeof item.CounterToday != 'undefined') {
            this.status = ' ' + $.t("Today") + ': ' + item.CounterToday;
            this.smallStatus = item.CounterToday;
        }
        if (typeof item.CounterDeliv != 'undefined') {
            if (item.CounterDeliv != 0) {
                if (item.UsageDeliv.charAt(0) != 0) {
                    this.status += '-' + item.UsageDeliv;
                }
                this.status += ', ' + $.t("Return") + ': ' + item.CounterDelivToday;
            }
        }

![image](https://github.com/domoticz/domoticz/assets/53882051/645d0767-a204-4ff6-8362-62e738718765)

Also to avoid the sensor text having 3 times the same text included with todays usage, I had to change one line in `function Counter(item)` from:
`this.status += ' ' + $.t("Today") + ': ' + item.CounterToday;
`to
this.status = ' ' + $.t("Today") + ': ' + item.CounterToday; 

![image](https://github.com/domoticz/domoticz/assets/53882051/63807dbe-07ec-4501-8b97-7b1072c38f53)
![image](https://github.com/domoticz/domoticz/assets/53882051/b24241dd-3069-4f5c-986c-11cee233bb2f)

But all together, these changes doesn't seem the appropriate solution to me as the root cause is the `function Counter(item)` not being called anymore once the 'default' icon is changed into a 'custom' one.

**Comment by martin-g-it** [comment]
Update 2; it looks the root cause is in `Device.create = function (item) {` where the RFXMeter type only results in a             dev = new Counter(item); based on the `type = item.Image.toLowerCase();`

Added item type RFXMeter being a Counter device which fixed the issue.

When updated (and reversed the change in the post above), it all worked OK except for the icon which appeared blurry on the floorplan (the 16px image was taken instead of 48px)
This I fixed by updating the image reference to the 48_On variant

![image](https://github.com/domoticz/domoticz/assets/53882051/94a5b718-ecb0-41dd-88df-29142d558790)

[Pull request](https://github.com/domoticz/domoticz/pull/5873) created

**Comment by gizmocuz** [comment]
Yes! Thank you very much for your research/PR!

**Comment by gizmocuz** [comment]
Could you also make a PR for the CounterToday issue?

**Comment by martin-g-it** [comment]
What CounterToday issue? The icon was initially fixed by you on the same www/js/domoticzdevices.js..  
Or do you refer to [this](https://www.domoticz.com/forum/viewtopic.php?p=308689&sid=a536eef7e53b95a9c6f996d1ce294d21#p308689) issue?

**Comment by gizmocuz** [comment]
Sorry wrong thread... I thought there was a textual display error as well
