### ISSUE TITLE
ESPSomfy MQTT-AD blinds not closing because of minus in value

### ISSUE THREAD

**Issue by xvisor16** [domoticz/domoticz#5875]
Hi,

I am using ESPSomfy to control our blinds for some time now. Recently I asked them on Github if they could add MQTT-AD according to spec from HA. They did that and now I have the blinds in Domoticz which is nice. Although there does seem to be an issue.

I can open and stop/favorite the blinds that all works well. Only closing doesn't work. When I look at the MQTT messages Domoticz sends a -100 message to close the blinds. But according to the spec a value of (+)100 should be send over MQTT to close the blinds. I have opened an issue with the developer of ESPSomfy-RTS and it seems that Domoticz is at fault here. If I send a an MQTT message without the minus sign the blinds close immediately.

Version: Stable (2023.2) and Beta (build 15650)
Running on: Raspberry Pi4B+ (4GB) with Raspbian 11
Using: MQTT with Auto Discovery
I used MQTT-Explorer to find out that Domoticz sends the "-100" to MQTT.

Beste regards,
Peter

**Comment by gizmocuz** [comment]
No idea who is to blame but it’s working fine for other blinds

Without the config topic + json payload we can’t help you

could you use MQTT explorer to copy/paste them here?

**Comment by xvisor16** [comment]
Hi @gizmocuz,

Sorry, could have done that right away of course!

Config topic:

```
{
  "~": "espsomfy/shades/1",
  "device": {
    "hw_version": "v2.2.1",
    "name": "ESPSomfyRTS",
    "mf": "rstrouse",
    "identifiers": [
      "mqtt_espsomfyrts_AD3F1C"
    ],
    "via_device": "mqtt_espsomfyrts_AD3F1C",
    "model": "ESPSomfy-RTS MQTT"
  },
  "availability_topic": "espsomfy/status",
  "payload_available": "online",
  "payload_not_available": "offline",
  "name": "Slaapkamer",
  "unique_id": "mqtt_AD3F1C_shade1",
  "device_class": "shutter",
  "payload_close": "1",
  "payload_open": "-1",
  "position_open": 0,
  "position_closed": 100,
  "state_closing": "1",
  "state_opening": "-1",
  "command_topic": "~/direction/set",
  "position_topic": "~/position",
  "set_position_topic": "~/target/set",
  "state_topic": "~/direction",
  "payload_stop": "0",
  "state_stopped": "0",
  "enabled_by_default": true
}
```

This is what I see in MQTT-Explorer when trying to close the blinds and nothing happens:
![image](https://github.com/domoticz/domoticz/assets/12544669/b00e0cd9-6e0d-407b-ac58-d02284a7c55b)

The topic "espsomfy/shades/1/target/set" receives -100 from domoticz when I press the close button. If I manually publish 100 to that same target from MQTT-Explorer is immediately closes.

I you need more just let me know.

**Comment by gizmocuz** [comment]
Thank you for this.. I will have a look at this shortly but payload_open and close are those correct?

**Comment by xvisor16** [comment]
I don't know for sure, I was hoping you did ;) I'm not that knowledgeable on MQTT. It seems logical to me if 0 = open and 100 = closed the payload to close should in steps of +1 and to open should be in steps of -1. So my brain logic tells me that if I sent 0 as a target/set it would open and if I sent 100 it would close... So I don't get why the -100 would be send by Domoticz. This also occurs when sliding the slider, if I set the slider to 60% it sends -60 and nothing happens. When I manually send 60 to target/set via MQTT-Explorer it closes or opens to 60%.

I hope this helps in any way. I could also try to bring you in contact with the rstrouse the developer of ESPSomfy if this cloud help.

**Comment by gizmocuz** [comment]
Ahhh well this is incorrent

```
"position_open": 0,
"position_closed": 100,

```

it should be

```
"position_open": 100,
"position_closed": 0,
```

Which is also the default

https://www.domoticz.com/wiki/Blinds

**Comment by xvisor16** [comment]
Thnx, I will pass this through.

**Comment by xvisor16** [comment]
Apparently there is a difference in opinion here... The developer of ESPSomfy referred to this article:
https://github.com/rstrouse/ESPSomfy-RTS/wiki/Configuring-the-Software#invert-position
After doing this it kind of works in Domoticz, at least opening and closing works now. I'm not the expert in this stuff and don't want to get caught in the middle of a discussion about what's right or wrong. So since it seems to work for now. I think we can close this issue.

**Comment by gizmocuz** [comment]
I have no different opinion. Have a look at the defaults here

https://www.home-assistant.io/integrations/cover.mqtt/

Inverting is done in the application (domoticz)

Glad it's working!
