### ISSUE TITLE
No more Temperature /  OWL  / DI.O sensors detected since last beta

### ISSUE THREAD

**Issue by sebitop** [domoticz/domoticz#5877]
Hi, I'm experiencing issues during the last 2 consecutive beta updates the past days and today

Started to see some weird behaviors today and tried to update beta this evening

now i'm running on the last beta 2023.2 15654 on raspberry + rfxcom (tuned on rfxlan)

- no more temperature sensors (alecto or thgh 122) in the logs, no temperature updates
- tried to allow new sensors and force one sending date, no detection
- no more OWL values update (sensor blinks but nothing appears on domoticz)
- no more DI-o detection ( a chacon module sendin ON/OFF comand to domoticz via 433mhz)

Domoticz still sends commands to devides like plug sockets, blinds module etc but seems not receving anymore data.

Tried to move back to last relase : domoticz failed to login (connection refused)

For info i did apt-get update and upgrade.

any idea if the issue comes from the beta release or from my side ?

I remain available for any info to help solving this issue.

Thanks for your precious help !
cheers
sebastien

**Comment by kiddigital** [comment]
Best to ask this question on the forum first. Once you have established this issue is due to a bug in the code, you can raise it here on GitHub.

**Comment by sebitop** [comment]
thanks for your answer and ok if it's the right process

for info (could be useful for others)

I managed to isolate each 433 device this morning (remove batteries), restarted and after half an hour got step by step the devices back into domoticz and then they appeared again in the logs

very weird but maybe some noise was generated by one of the device on which the battery was low, I don't know.

It finally seems that the problem came from my side and not from the beta

sorry for the inconvenience I try to provide useful feedback when I detect something as I always update to the last beta but obvisouly i'm not always 100% right :)

I close the thread
thanks for your help and support to the team !

Cheers
sebastien
