### ISSUE TITLE
Feature Request: Addition of $text Variable for Custom Message Notifications of  Alert sensors

### ISSUE THREAD

**Issue by bierdok** [domoticz/domoticz#5879]
**In fact for the sensor alert, the $value injection is not good. We should have the reason (text) of the alert instead. We don't care about having the level number, since we can correspond to a level in the notification settings.**

### References

https://github.com/domoticz/domoticz/blob/dcded44e5787e6b25eb2a4c605275473125d7853/notifications/NotificationHelper.cpp#L234-L240

https://github.com/domoticz/domoticz/blob/dcded44e5787e6b25eb2a4c605275473125d7853/notifications/NotificationHelper.cpp#L465-L466

### Issue
_The custom message notification feature allows the injection of variables like $name and $value. However, for more versatile and detailed alerts, it would greatly enhance functionality to introduce a new variable, $text, which could be utilized in notifications for alert sensors and similar widgets._

### Proposal
_The addition of the $text variable would enable users to create more informative and context-rich custom messages, allowing for better communication of sensor alerts._

### Use Case
_For instance, when an alert sensor is triggered, having access to a $text variable would enable users to include specific details or additional context related to the alert in their custom notification messages. This could significantly improve the usefulness and relevance of notifications, aiding users in taking prompt and appropriate actions based on the received information._

**Comment by bierdok** [comment]
https://github.com/domoticz/domoticz/blob/dcded44e5787e6b25eb2a4c605275473125d7853/notifications/NotificationHelper.cpp#L466C103-L466C103

**Comment by waltervl** [comment]
What would be the storage location of that $text? On the device? As a user variable? I do not see the use case here with an extra variable.

And if you want to give extra context to a device notification you just create the text in the device notification custom message field. Eg

> Device $name has value $value so too high. Please go home and do a visual confirmation

If you really want to have flexibility use the Dzvents notification function in a dzvents script.

**Comment by bierdok** [comment]
`Device Boiler has value 3 so too high` but for this level of alert I have 10+ differents reason.

So tell me what is the real advantage of the parameter `text` in the method `device.updateAlertSensor(level, text)` if we cannot include the related reason in the custom message of the notification?

**Comment by bierdok** [comment]
In fact for the sensor alert, the $value injection is not good.  We should have the reason (text) of the alert instead. We don't care about having the level number, since we can correspond to a level in the notification settings.

**Comment by waltervl** [comment]
Ok, so this request is specific for the alert sensor that has a text value (the only one...) So this makes sense.

**Comment by waltervl** [comment]
@bierdok Looks like you have already some C++ knowledge. Perhaps you can add this functionality as a PR?

**Comment by bierdok** [comment]
@waltervl , I have an issue when I test my changes:
```
➜  domoticz git:(development) docker-compose -f ./build/docker-compose.yml build
➜  domoticz git:(development) build/build cmake
./build-helper.sh: line 173: syntax error near unexpected token `fi'
./build-helper.sh: line 173: `    fi'
```

**Comment by waltervl** [comment]
I am sorry, I cannot help you here. Perhaps @gizmocuz ?

**Comment by bierdok** [comment]
This PR fixes the script syntax: https://github.com/domoticz/domoticz/pull/5900
This PR fixes the submodule permission: https://github.com/domoticz/domoticz/pull/5901

**Comment by gizmocuz** [comment]
Both are merged. Thank you!

**Comment by waltervl** [comment]
I don think the PR's are fixing this enhancement request, they are only fixing build problems to be able to test the proposed change....
