### ISSUE TITLE
Duplicate value in rain_calendar

### ISSUE THREAD

**Issue by VincentCama** [domoticz/domoticz#588]
Hi,

I found duplicate value in rain_calendar table. Strange ?
Version: 2.3530
Build Hash: 9eef872

![snip_20160331110854](https://cloud.githubusercontent.com/assets/17099804/14171062/39279a5e-f731-11e5-825e-6c895d64f02a.png)
![snip_20160331110816](https://cloud.githubusercontent.com/assets/17099804/14171065/3c403138-f731-11e5-964b-cb6a5b6b6452.png)

**Comment by gizmocuz** [comment]
Update to the latest beta version and it is solved,
problem was/is DST changes
It has been reported many times on our forum, best to use our forum!

**Comment by VincentCama** [comment]
Thank's and sorry :(
