### ISSUE TITLE
Sensor : sending switch commands for switch type 'binary_sensor' is not supported

### ISSUE THREAD

**Issue by zoll38** [domoticz/domoticz#5880]
Hello,

I have domoticz latest official build with MQTT Auto Discovery running on a Ubuntu box together with Zigbee2mqtt and mosquito. I recently updated my zigbee2mqtt install to the latest version in order to get more supported devices from the herdsman converters, and since then, one type of the zigbee sensors that I am using, model _TZ3000_6ygjfyll, is throwing this error message when detecting a movement:

Error: MQTT General Zigbee: sending switch commands for switch type 'binary_sensor' is not supported (yet...)

It seems that Domoticz is trying to send a zigbee command to the device. Not sure why and not sure what I can do to avoid this error. I searched in the forum and in GitHub but didn't find any interesting information so far.

I didn't get this error prior to update zigbee2mqtt and I don't have this issue on other motion sensors.

Is this a known bug and is there a workaround?

Thanks

**Comment by gizmocuz** [comment]
Is this a motion sensor? You cannot/should not switch these ...
Did you add a auto off delay? Or are you manually switching them?

**Comment by zoll38** [comment]
Yes, it is motion sensor. I don't switch anything, Domoticz does send a command apparently even if  the device is set as motion sensor.
Yes, I set it up with auto off delay set to 30s using the zigbee2mqtt interface, not with Domonitcz. I don't manually switch it off.

**Comment by gizmocuz** [comment]
Then Domoticz should not send a switch command. (Only when you have edited the motion sensor switch and specified the off delay here)

Could you post the MQTT configuration topic and json payload?
You can find these when using a application like MQTT Explorer

it should be somewhere like: homeassistant/binary/xx/yy/zz/config (complete topic name place) and when you click on it, please also post the JSON payload

**Comment by zoll38** [comment]
Here is the topic located in

**homeassistant/binary_sensor/0xa4c138f58f45a35f/occupancy/config**

`{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/Motion Sensor Kitchen/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0xa4c138f58f45a35f"],"manufacturer":"TuYa","model":"Motion sensor (IH012-RT01)","name":"Motion Sensor Kitchen"},"device_class":"motion","json_attributes_topic":"zigbee2mqtt/Motion Sensor Kitchen","object_id":"motion_sensor_kitchen_occupancy","origin":{"name":"Zigbee2MQTT","sw":"1.33.2","url":"https://www.zigbee2mqtt.io"},"payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/Motion Sensor Kitchen","unique_id":"0xa4c138f58f45a35f_occupancy_zigbee2mqtt","value_template":"{{ value_json.occupancy }}"}
`

**Comment by gizmocuz** [comment]
Thank you for this.

I have tested this, and it works without issues.

There 'must' be something that sends a switch command (from domoticz) to this motion sensor

Double check if you have not specified a off delay in domoticz for this motion sensor
Also check this motion sensor is not used anywhere, not in a script, not in a group , scene , event etc

**Comment by zoll38** [comment]
Thanks a lot. You are right, I had a off delay in domoticz for this motion sensor. My bad. Didn't think about this. Thanks again.
