### ISSUE TITLE
Memory leak in Python Framework (Extended and Legacy)

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#5881]
As describe in the forum https://www.domoticz.com/forum/viewtopic.php?p=308984#p308984, there is a suspicion of memory leak within the domoticz framework.
As it is visible with the Extended and the Legacy framework, that seems to be deeper in the code.

In all case, here is the plugin to reproduce the problem.

The plugin is starting to create 99 units (domoticz widgets) and wll every second use the Touch() api to touch the 99 units.

Using htop, shows the VIRT and RES size increasing over the time , while the plugin itself is not allocating any `memory.`

How to duplicate

1) create a folder under plugins/
2) restart domoticz
3) add hardware Memory Leak

monitor memory

By default the plugin use the Domoticz extended , but you can also turn to Legacy one by changing those 4 lines of code

```
import DomoticzEx as Domoticz
DOMOTICZ_EXTENDED_API = True
# import Domoticz
# DOMOTICZ_EXTENDED_API = False
```

by 

```
#import DomoticzEx as Domoticz
#DOMOTICZ_EXTENDED_API = True
import Domoticz
DOMOTICZ_EXTENDED_API = False
```

```
"""
<plugin key="MemoryLeak" name="Memory Leak on iTouch" author="pipiche" version="0.1" externallink="">
    <params>
        <param field="Mode6" label="Debugging" width="150px"  default="None" required="true">
            <description><br/><h3>Plugin debug</h3>This debugging option has been moved to the WebUI > Tools > Debug<br/></description>
                <options>
                    <option label="None" value="0"  default="true" />
                    <option label="Python Only" value="2"/>
                    <option label="Basic Debugging" value="62"/>
                    <option label="Basic+Messages" value="126"/>
                    <option label="Connections Only" value="16"/>
                    <option label="Connections+Queue" value="144"/>
                    <option label="All" value="-1"/>
                </options>
        </param>
    </params>
</plugin>
"""

HEARTBEAT_FEQ = 1
NUMBER_UNIT = 100


import DomoticzEx as Domoticz
DOMOTICZ_EXTENDED_API = True
# import Domoticz
# DOMOTICZ_EXTENDED_API = False


class BasePlugin:

    def __init__(self):
        self.plugin_ready = False
        return

    def onStart(self):
        Domoticz.Log('onStart called %s' % DOMOTICZ_EXTENDED_API)

        for unit in range(1, NUMBER_UNIT):
            device_create_unit(self, Devices, "MemoryLeak", "MemoryLeak %s" % unit, unit)

        # Set plugin heartbeat to 1s
        Domoticz.Heartbeat(HEARTBEAT_FEQ)

    def onHeartbeat(self):
        Domoticz.Log('onHeartbeat called')

        if DOMOTICZ_EXTENDED_API:
            for deviceId in Devices:
                for unit in Devices[ deviceId ].Units:
                    device_touch_api(self, Devices, deviceId, unit)
        else:
            for unit in Devices:
                device_touch_api(self, Devices, "MemoryLeak", unit)

    def onCommand(self, Unit, Command, Level, Hue):
        Domoticz.Debug('onCommand called')

    def onStop(self):
        Domoticz.Debug('onStop called')


def device_create_unit(self, Devices, deviceId, Name, unit):

    if DOMOTICZ_EXTENDED_API:
        if deviceId in Devices and unit in Devices[deviceId].Units:
            return
    elif not DOMOTICZ_EXTENDED_API and unit in Devices:
        return
    
    Domoticz.Log('device_create_unit %s/%s' % (deviceId ,unit))
    domoticz_device_api_class = Domoticz.Unit if DOMOTICZ_EXTENDED_API else Domoticz.Device

    myDev = domoticz_device_api_class(DeviceID=deviceId, Name=Name, Unit=unit, Type=244, Subtype=73, )
    myDev.Create()


def device_touch_api(self, Devices, deviceId, unit):
    
    if DOMOTICZ_EXTENDED_API:
        if "MemoryLeak" not in Devices:
            return
        Domoticz.Log('device_touch_api %s/%s' % (deviceId ,unit))
        Devices[ deviceId ].Units[ unit ].Touch()
        return
    else:
        # Legacy
        Domoticz.Log('device_touch_api %s' % unit)
        Devices[unit].Touch()
    
global _plugin
_plugin = BasePlugin()


def onStart():
    global _plugin
    _plugin.onStart()


def onStop():
    global _plugin
    _plugin.onStop()


def onHeartbeat():
    global _plugin
    _plugin.onHeartbeat()


def onCommand(Unit, Command, Level, Hue):
    global _plugin
    _plugin.onCommand(Unit, Command, Level, Hue)

```

**Comment by pipiche38** [comment]
Attaching here a valgrind report run

It has been run on the DomoticzEx

`sudo valgrind --leak-check=full --show-leak-kinds=all /usr/share/domoticz/beta-domoticz/bin/domoticz -noupdates -www 8080 -wwwroot /var/lib/domoticz/www -dbase /var/lib/domoticz/domoticz.db -userdata /var/lib/domoticz/ -debuglevel normal -loglevel normal,status,error -log /var/tmp/domoticz.log > /tmp/valgrind-report.log 2>&1`

[valgrind-report.log](https://github.com/domoticz/domoticz/files/13400716/valgrind-report.log)


The source code for CDevice_refresh() is here https://github.com/domoticz/domoticz/blob/f06f29b2d53e5b9fa545d7d6a82e06adc6035740/hardware/plugins/PythonObjects.cpp#L671

**Comment by pipiche38** [comment]
Attching here a valigrind report run

It has been run on the Domoticz (Legacy)

[valgrind-report.log](https://github.com/domoticz/domoticz/files/13400749/valgrind-report.log)

**Comment by pipiche38** [comment]
If I understand PyDict_Clear() does not deallocate the memory associated with the dictionary itself. It only removes all items from the dictionary, making it empty. The memory allocated for the dictionary object is not released by this function.

However there are pKeyDict and pValueDict which are doing via malloc due to PyUnicode_FromString() and are never release ! as we clear the dictionary.

**Comment by gizmocuz** [comment]
And what happens when you let this run for a few hours/days?
Because here I can see a memory increase, and then it stabilizes and there is no more memory increase.
And I would expect the same on your system, it will flush it's resources

Edit: using Python '3.12.0'

**Comment by pipiche38** [comment]
it always increase, there is no flush. Users are reporting that  only a restart of domoticz free the memory, otherwise it is just growing

**Comment by gizmocuz** [comment]
That's fine, but I have not seen any reports that the system freezes because of a memory issue.
And I can also not reproduce this

**Comment by pipiche38** [comment]
and you found those valgrind output not an issue ?

```
==8269== 273,700 bytes in 7,820 blocks are definitely lost in loss record 2,308 of 2,310
==8269==    at 0x48648D0: malloc (vg_replace_malloc.c:381)
==8269==    by 0x5D4D0CF: PyObject_Malloc (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D4DA37: PyUnicode_New (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D4E277: ??? (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D5140B: PyUnicode_FromString (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0xCC298F: Plugins::CDevice_refresh(Plugins::CDevice*) (PythonObjects.cpp:690)
==8269==    by 0xCC5873: Plugins::CDevice_touch(Plugins::CDevice*) (PythonObjects.cpp:1145)
==8269==    by 0x5D743DB: ??? (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D6291B: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D60D83: ??? (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D71FE7: _PyFunction_Vectorcall (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D624B7: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.10.so.1.0)
==8269==
==8269== 343,992 bytes in 7,818 blocks are definitely lost in loss record 2,309 of 2,310
==8269==    at 0x48648D0: malloc (vg_replace_malloc.c:381)
==8269==    by 0x5D4D0CF: PyObject_Malloc (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D4DA37: PyUnicode_New (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D4E277: ??? (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D5140B: PyUnicode_FromString (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0xCC2B2F: Plugins::CDevice_refresh(Plugins::CDevice*) (PythonObjects.cpp:699)
==8269==    by 0xCC5873: Plugins::CDevice_touch(Plugins::CDevice*) (PythonObjects.cpp:1145)
==8269==    by 0x5D743DB: ??? (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D6291B: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D60D83: ??? (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D71FE7: _PyFunction_Vectorcall (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D624B7: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.10.so.1.0)
==8269==
==8269== 484,067 bytes in 7,819 blocks are definitely lost in loss record 2,310 of 2,310
==8269==    at 0x48648D0: malloc (vg_replace_malloc.c:381)
==8269==    by 0x5D4D0CF: PyObject_Malloc (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D4DA37: PyUnicode_New (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D4E277: ??? (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D5140B: PyUnicode_FromString (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0xCC28BF: Plugins::CDevice_refresh(Plugins::CDevice*) (PythonObjects.cpp:685)
==8269==    by 0xCC5873: Plugins::CDevice_touch(Plugins::CDevice*) (PythonObjects.cpp:1145)
==8269==    by 0x5D743DB: ??? (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D6291B: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D60D83: ??? (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D71FE7: _PyFunction_Vectorcall (in /usr/lib/libpython3.10.so.1.0)
==8269==    by 0x5D624B7: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.10.so.1.0)
```

**Comment by gizmocuz** [comment]
I don't see them here with Visual Studio and the memory profiler.
Memory is also not increasing after a few minutes and keep steady.
Maybe memory allocation if different between Win32 and Unix?

This is the 50th issue about it? Maybe you could try to free the memory before clearing the dictionary to see if that helps?

Looking at the code arroung line 685 where PyUnicode_FromString is used, it is preceded with calls to 'Py_DECREF' which should free the string if it was used?
Maybe try py_Clear as well

googling on PyUnicode_FromString and memory leak returns tons of results

**Comment by domoticauser** [comment]
> That's fine, but I have not seen any reports that the system freezes because of a memory issue. And I can also not reproduce this

I am sure that i have freeze's because of a full memory. I can see my memory in proxmox. I have asked Pipiche if it was a plugin problem. No scripts running. After that Pipiche did some testing.  Problem is since domoticz 2023.2
![afbeelding](https://github.com/domoticz/domoticz/assets/11601535/feba0a63-4efa-4de2-8a08-6cbedb969933)

**Comment by gizmocuz** [comment]
We have reports of a memory leak for years. Except for support for python 3.11 there have been minor changes so I don't think that this is the issue.
What plugin are you using that is causing such dramatic memory increases??

**Comment by domoticauser** [comment]
I have asked pipiche if it was possible that zigbee for domoticz is the problem. On the day that I did an update to domoticz 2023.3 the memory problems did start.  I also did that day an update for the zigbee plugin.
I don't know what it causes this problem. After that Pipiche did some testing. 
If the memory above 95% it freezes domoticz. 

Screenshot memory:
Update was 28 August.
![afbeelding](https://github.com/domoticz/domoticz/assets/11601535/262819c4-dce1-456c-b116-ef79ccfc269c)

**Comment by gizmocuz** [comment]
There is no 2023.3 (yet)
So, you updated both Domoticz and the Plugin, and are now not sure what is causing the problem.

You can also click on one of the python framework files in our git repository and press the history button.
This will list all changes made.
2023.2 was released on 21 July.
Make sure to switch to the master branch before, or use the below link as starting point:

https://github.com/domoticz/domoticz/tree/master/hardware/plugins

A quick fix for your issue, not for the (possible) python issue, is to use Zigbee2MQTT in combination with MQTT Auto discovery in Domoticz.
You might even get some firmware updates for your nodes as well.
I recommend installing this via docker compose, there is a Domoticz wiki page about this here:

https://www.domoticz.com/wiki/Zigbee2MQTT

**Comment by gizmocuz** [comment]
Another thing to try is to upgrade python. As mentioned before, I am using 3.12... Worth a try

**Comment by domoticauser** [comment]
Sorry. I mean 2023.2 version of domoticz.

**Comment by pipiche38** [comment]
@gizmocuz you might not like the Zigbee for Domoticz plugin and that is fine, but the matter of fact, it is a simple plugin for the end user which doesn't require to have heavy customization and having a middleware in between which is what MQQT requires
Edit: only the middleware python and some library dependencies...

**Comment by pipiche38** [comment]
valgrind here after several hours of work with the simple plugin provided. The CDevice_touch() is indeed the most consuming allocation of memory which are never released.
And if you do the test with the Extended framework that is the same,

**Comment by gizmocuz** [comment]
@pipiche38 , I am not saying that I like Zigbee2MQTT more then zigbee4domoticz, it is just a quick fix for his issue.

The problem is not inside CDevice_touch, it is in the function that is calling it CDevice_refresh, hence the line above and my comment about PyUnicode_FromString

**Comment by domoticauser** [comment]
Hi, 
Python 3.9.2 version.  Should i update? What is the best way.
I am not planning to go to  Zigbee2MQTT. I hope that there will be another solution. 
Unfortunately I don't have the expertise to look into the code, I'll leave that to you experts.

I hope for a solution....

**Comment by gizmocuz** [comment]
Maybe I mentioned before that this is being reported for years
So, for the same reason I am still using windows 95 and hope for a update, let’s wait for a update from the experts

**Comment by pipiche38** [comment]
PyDict_Clear() will remove the items from the dictionary, but it won't necessarily release the memory associated with the objects stored in the dictionary.

If you have objects created with PyUnicode_FromString() inside the dictionary and you want to ensure that the memory is properly released, you need to handle that explicitly before clearing the dictionary. You should decrement the reference counts of the objects stored in the dictionary using Py_XDECREF() or Py_DECREF() as needed.

and from what I see they are some pKeyDict and pValueDict which are allocated via PyUnicode_FromString()

I don't know how to do it in C++, but before the PyDict_Clear(self->Options), all allocated elements in this dictiionnary but be Py_XDECREF

**Comment by gizmocuz** [comment]
Did you have a look in the function **CDevice_refresh**? It is using **Py_XDECREF**
The 'Touch' call in the above script will call the above function as well.

So I suggest a simple test first, remark all lines with PyUnicode_FromString/PyDict_SetItemString/PyDict_SetItem in CDevice_refresh
Then perform the memory/script test again to see if this solves the issue

**Comment by pipiche38** [comment]
Did test with python3.12 (on Fedora 39) and still Memory is just growing.

I'm not sure I understand what you are suggesting. If for instance you are commenting PyUnicode_FromString/PyDict_SetItemString/PyDict_SetItem , this will for sure impact the code behaviour as this is done on purpose. 

As mentioned I'm not a C++ man, so better than someone who master it do it, this is also why I have provided the plugin.py to easily reproduce the issue

maybe @dnpwwo could help us here

**Comment by gizmocuz** [comment]
Reason was that you also mentioned above it could be related to 'PyUnicode_FromString()' , so not calling these functions would not allocate memory. But it seems that the problem is not related to this...

**Comment by pipiche38** [comment]
What I understood from the documentation is PyUnicode_FromString() does a malloc, so before updating with PyUnicode_FromString(), you should call 'Py_DECREF'  before to release the previous value.

Now what I understood is that PyDict_Clear(self->Options) clean the self->Options dictionnary, but do not release any allocated memory if any.

**Comment by pipiche38** [comment]
> Reason was that you also mentioned above it could be related to 'PyUnicode_FromString()' , so not calling these functions would not allocate memory. But it seems that the problem is not related to this...

So I did put in comment all of then in CDevice_refresh and the memory allocation remains stable (no leak).

I have reported the issue in the python discussion forum https://discuss.python.org/t/memory-leak-with-pyunicode-fromstring-and-pydict-clear/39218/1

Let see if those guys can provide any hints.

At least at that time we know where the issue is coming from

In paralell I used chatGPT and here is what I've got, no idea what is it about !

> Avoid Raw Pointers:
> 
>     Instead of using raw pointers, consider using smart pointers like std::unique_ptr or std::shared_ptr for managing dynamic memory. This can help in automatic memory management and reduce the chance of memory leaks.

**Comment by gizmocuz** [comment]
I'm afraid smart pointers are not the solution here as PyUnicode_FromString generates something for python not c++
While in this function... this is probably a bad idea 'but' worth a try
Above the 'PyUnicode_FromString' calls, you also see a line with '**Py_XDECREF**'
This 'supposed' to free the string, before calling 'PyUnicode_FromString' again.
It looks like this ain't doing much causing the memory leak

If it is using malloc, could you use 'free' to free the memory, so changing this

```
					Py_XDECREF(self->Name);
					self->Name = PyUnicode_FromString(sd[2].c_str());
```

to

```
					PyMem_Free(self->Name);
					self->Name = PyUnicode_FromString(sd[2].c_str());
```

or

```
					if (self->Name != nullptr)
					     free(self->Name);
					self->Name = PyUnicode_FromString(sd[2].c_str());
```

**Comment by gizmocuz** [comment]
I also notice two methods for setting a string

```
					Py_XDECREF(self->Name);
					self->Name = PyUnicode_FromString(sd[2].c_str());
```

and

`							PyDict_SetItemString(self->Options, "Custom", PyUnicode_FromString(sd[13].c_str()));
`

Maybe change them all to **PyDict_SetItemString**?

`					PyDict_SetItemString(self->Name, "Custom", PyUnicode_FromString(sd[0].c_str()));
`
Edit: (Maybe with a call to PyDict_Clear before that..)

**Comment by dnpwwo** [comment]
I've never managed to track down this leak (I run 10 plugins with zero leaks for months at a time) so I don't have any quick answer but I can respond to some comments:

1. PyDict_Clear not managing memory.  Python respects it's own rules when managing memory, a PyDict_Clear will release a reference count to the dictionary members.  If you manually decrement the counters on dictionary elements you will get crashes.
2. PyDict_SetItemString only works on Dictionaries, you can't use it for general string assignment.
3. Py_XDECREF 'supposed' to free the string.  No.  Python uses reference counting to manage memory, Py_XDECREF removes a reference and nothing else, memory should be cleaned up by the garbage collector if there are no references to a bit of memory.  Py_XDECREF is used all over the framework (see smart pointer destructor) so if it didn't work memory would be exhausted very quickly.
4. New and Free can't be used for memory being used by Python.

In the interest of troubleshooting I would suggest calling  Unit.Refresh() rather than Unit.Touch() to see if the same leak is present.

![Untitled](https://github.com/domoticz/domoticz/assets/6850332/00b99622-2909-461a-8644-2f5b5615b98f)

**Comment by pipiche38** [comment]
Thanks for jumping in @dnpwwo , Yes Unit.Refresh() test is producing the same leakage

Also I simply wonder if the Garbage collector is enabled. But I'm not able to add a call to one of those function, as I get compiler errors and/or linker.

Any advice on what should be done to be able to use those call would be helpfull

Py_ssize_t PyGC_Collect(void)
int PyGC_Enable(void)
int PyGC_IsEnabled(void)

**Comment by dnpwwo** [comment]
The garbage collector is enabled by default, if it wasn't running then memory would always skyrocket.  To prove it just set a break point on CUnitEx_dealloc and comment out the 'Create()' call in Python so the object goes out of scope. 

    myDev = domoticz_device_api_class(DeviceID=deviceId, Name=Name, Unit=unit, Type=244, Subtype=73, )
    #myDev.Create()

The reference count on myDev will drop to zero at the end of the function and the garbage collector will clean up by telling the object to 'dealloc' itself.

Another problem is that int PyGC_Enable(void) and int PyGC_IsEnabled(void) are only in the Stable ABI from Python 3.10 so are not usable for people on older version (I'm still on 3.7.3)

**Comment by pipiche38** [comment]
I tested on 3.12 and now run 3.11, this is why I suspect something on our side rather than a leak in the librairies. 
That is why I suspect the GC.

As mentioned I'm not good on C++ so challenging for me, even to do what you call the break point.

As a sanity check @dnpwwo do you see the same behaviour with the plugin.py code I provided ?

**Comment by pipiche38** [comment]
for now I'm suggesting #5890 and the same as to be done for DomoticzEx ... but this has NO. impact to the current problem on Touch() and Refresh()

As I'm not able to test the GC especially checking if it is enabled or not ... I cannot do more

**Comment by pipiche38** [comment]
@gizmocuz  can you give me some hints on how to achieve that ? https://github.com/domoticz/domoticz/issues/5881#issuecomment-1820381948

With that, I would be able to play around the gargabe collector and see if there is impact or not.

**Comment by pipiche38** [comment]
@dnpwwo and @gizmocuz let me answer your comment https://github.com/domoticz/domoticz/pull/5890#issuecomment-1825152866 here, as I do consider the PR ready.

To answer your question, I'm just running domoticz with the given plugin and monitor the memory usage with htop

The VIRT (Virtual memory) and RES (Resident Set Size) are just growing with the time without going done.

This is done on PI4 with Fedora39 on aarch64

>  2023-11-24 14:22:17.996 Status: Domoticz V2023.2 (build 15666) (c)2012-2023 GizMoCuz
> 2023-11-24 14:22:17.998 Status: Build Hash: 9ff9ea70f-modified, Date: 2023-11-22 09:15:13
> 2023-11-24 14:22:18.310 Status: PluginSystem: Started, Python version '3.11.6',


<img width="1221" alt="Screenshot 2023-11-24 at 15 51 17" src="https://github.com/domoticz/domoticz/assets/8291674/50519066-f71b-4f77-b5b7-06240e2d2453">

<img width="576" alt="Screenshot 2023-11-24 at 15 51 44" src="https://github.com/domoticz/domoticz/assets/8291674/d91083ba-8ed0-4084-8a25-3b043d38f40f">

**Comment by pipiche38** [comment]
valgrind ... reporting the most important

```
==7925== 515,576 bytes in 7,582 blocks are definitely lost in loss record 172 of 173
==7925==    at 0x48C0860: malloc (vg_replace_malloc.c:442)
==7925==    by 0x740762B: UnknownInlinedFun (obmalloc.c:101)
==7925==    by 0x740762B: UnknownInlinedFun (obmalloc.c:586)
==7925==    by 0x740762B: UnknownInlinedFun (obmalloc.c:2003)
==7925==    by 0x740762B: UnknownInlinedFun (obmalloc.c:1996)
==7925==    by 0x740762B: PyObject_Malloc (obmalloc.c:712)
==7925==    by 0x7408EAF: PyUnicode_New (unicodeobject.c:1425)
==7925==    by 0x74081AF: unicode_decode_utf8 (unicodeobject.c:5117)
==7925==    by 0xA4C79F: Plugins::CDevice_refresh(Plugins::CDevice*) (in /home/domoticz/dev-domoticz/domoticz)
==7925==    by 0x742E12F: _PyEval_EvalFrameDefault (ceval.c:5284)
==7925==    by 0x7421757: UnknownInlinedFun (pycore_ceval.h:73)
==7925==    by 0x7421757: _PyEval_Vector (ceval.c:6425)
==7925==    by 0x74180A3: _PyObject_VectorcallTstate.lto_priv.3 (pycore_call.h:92)
==7925==    by 0xA137E7: Plugins::CPlugin::Callback(Plugins::PyBorrowedRef&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, _object*) (in /home/domoticz/dev-domoticz/domoticz)
==7925==    by 0x5E2AD3: Plugins::CPluginMessageBase::Process(Plugins::CPlugin*) (in /home/domoticz/dev-domoticz/domoticz)
==7925==    by 0xA19C6F: Plugins::CPlugin::Do_Work() (in /home/domoticz/dev-domoticz/domoticz)
==7925==    by 0xBC975F: execute_native_thread_routine (in /home/domoticz/dev-domoticz/domoticz)
==7925==
==7925== 580,513 bytes in 7,581 blocks are definitely lost in loss record 173 of 173
==7925==    at 0x48C0860: malloc (vg_replace_malloc.c:442)
==7925==    by 0x740762B: UnknownInlinedFun (obmalloc.c:101)
==7925==    by 0x740762B: UnknownInlinedFun (obmalloc.c:586)
==7925==    by 0x740762B: UnknownInlinedFun (obmalloc.c:2003)
==7925==    by 0x740762B: UnknownInlinedFun (obmalloc.c:1996)
==7925==    by 0x740762B: PyObject_Malloc (obmalloc.c:712)
==7925==    by 0x7408EAF: PyUnicode_New (unicodeobject.c:1425)
==7925==    by 0x74081AF: unicode_decode_utf8 (unicodeobject.c:5117)
==7925==    by 0xA4C65B: Plugins::CDevice_refresh(Plugins::CDevice*) (in /home/domoticz/dev-domoticz/domoticz)
==7925==    by 0x742E12F: _PyEval_EvalFrameDefault (ceval.c:5284)
==7925==    by 0x7421757: UnknownInlinedFun (pycore_ceval.h:73)
==7925==    by 0x7421757: _PyEval_Vector (ceval.c:6425)
==7925==    by 0x74180A3: _PyObject_VectorcallTstate.lto_priv.3 (pycore_call.h:92)
==7925==    by 0xA137E7: Plugins::CPlugin::Callback(Plugins::PyBorrowedRef&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, _object*) (in /home/domoticz/dev-domoticz/domoticz)
==7925==    by 0x5E2AD3: Plugins::CPluginMessageBase::Process(Plugins::CPlugin*) (in /home/domoticz/dev-domoticz/domoticz)
==7925==    by 0xA19C6F: Plugins::CPlugin::Do_Work() (in /home/domoticz/dev-domoticz/domoticz)
==7925==    by 0xBC975F: execute_native_thread_routine (in /home/domoticz/dev-domoticz/domoticz)
```

**Comment by pipiche38** [comment]
I have updated CDevice_refresh() to a minimum and I'm still able to see the growing RES and VIRT memory 

`
        PyObject* CDevice_refresh(CDevice* self)
        {
                        Py_RETURN_NONE;
        }
`

**Comment by gizmocuz** [comment]
Quick test, just to rule something out....
In the settings, disable dzVents, just to rule out a leak in here
If the leak is still happening, please try to disable some more functions (with { Py_RETURN_NONE; })

**Comment by pipiche38** [comment]
This is too many on somthing I don't master. So anyone feel free to work on that one.

https://discuss.python.org/t/memory-leak-with-pyunicode-fromstring-and-pydict-clear/39218/21?u=pipiche38

**Comment by xbeaudouin** [comment]
I passed on FreeBSD 14.0 and some patches of ZFS.
Will valgrind that here... and use clang fuzzing stuff to have some more informations.

**Comment by thertp** [comment]
I'm going to do more test on my local 2023.1 and python 3.9 but memory issues pointed here are real. I've noticed it on my domoticz install too (domiticz-zigate use too). Some fixed by @pipiche38 PR and by commit 80fdfaa3ac4901f3b379707adfe82f62c809c944 but some remained, like the ``CDevice_refresh()``.

Ran valgrind and got them too in the logs (btw, from what I understand, to use valgrind and python, one must export ``PYTHONMALLOC=malloc`` otherwise ``pymalloc`` may get in valgrind's way).
Finally found time to look at the issue and after trying to understand what was going on, found this little gem:
```
#ifdef WIN32  
#	define	_Py_Dealloc				pythonLib->_Py_Dealloc		// Builds against a low Python version
#elif PY_VERSION_HEX < 0x03090000
#	define	_Py_Dealloc				pythonLib->_Py_Dealloc
#else
#	ifndef _Py_DEC_REFTOTAL
	/* _Py_DEC_REFTOTAL macro has been removed from Python 3.9 by: https://github.com/python/cpython/commit/49932fec62c616ec88da52642339d83ae719e924 */
#		ifdef Py_REF_DEBUG
#			define _Py_DEC_REFTOTAL _Py_RefTotal--
#		else
#			define _Py_DEC_REFTOTAL
#			define _Py_Dealloc
#		endif
#	endif
#endif
```
If we're on windows or other OS with python < 3.9, ``_Py_Dealloc`` is defined as ``pythonLib->_Py_Dealloc``. In other cases, ``_Py_Dealloc`` is defined as:
```
#			define _Py_Dealloc
```
No wonder it's leaking. Why undefining the function ? it's still defined in current python (https://github.com/python/cpython/blob/4b3cb082da82da744f5db0b7315aa80558c51557/Include/object.h#L750).

A quick fix is (warning: cut&paste space damage):
```
Index: domoticz-2023.1/hardware/plugins/DelayedLink.h
===================================================================
--- domoticz-2023.1.orig/hardware/plugins/DelayedLink.h
+++ domoticz-2023.1/hardware/plugins/DelayedLink.h
@@ -502,22 +502,17 @@ extern    SharedLibraryProxy* pythonLib;
 #define        Py_CompileString                pythonLib->Py_CompileString
 #define        PyEval_EvalCode                 pythonLib->PyEval_EvalCode
 #define        PyType_GetFlags                 pythonLib->PyType_GetFlags
-#ifdef WIN32  
-#      define  _Py_Dealloc                             pythonLib->_Py_Dealloc          // Builds against a low Python version
-#elif PY_VERSION_HEX < 0x03090000
-#      define  _Py_Dealloc                             pythonLib->_Py_Dealloc
-#else
+#define        _Py_Dealloc                     pythonLib->_Py_Dealloc
+#if PY_VERSION_HEX >= 0x03090000
 #      ifndef _Py_DEC_REFTOTAL
        /* _Py_DEC_REFTOTAL macro has been removed from Python 3.9 by: https://github.com/python/cpython/commit/49932fec62c616ec88da52642339d83ae719e924 */
 #              ifdef Py_REF_DEBUG
 #                      define _Py_DEC_REFTOTAL _Py_RefTotal--
 #              else
 #                      define _Py_DEC_REFTOTAL
-#                      define _Py_Dealloc
 #              endif
 #      endif
 #endif
-
 #if PY_VERSION_HEX >= 0x030800f0
 static inline void py3__Py_INCREF(PyObject* op)
 {
```
Obviously, I can submit a PR later if asked.
After that, valgrind seems to see more leaks but it's clearly smaller than without this change.
[side note: it would be interesting to run tests with python compiled with --with-pydebug to get python refcount checks]

**Comment by gizmocuz** [comment]
@thertp , thanks for looking at this as well! Would be great if you can submit a PR.
Are you also able to test against python 3.10 and up? (3.12), maybe via a docker enviroment?

**Comment by thertp** [comment]
@gizmocuz Will try to find some time next week to do that. I should be able to easily test on 3.11, no promise about 3.12.

**Comment by xbeaudouin** [comment]
I did a quick patch as @thertp show last week...
The good point: not too much mem leak (so...).
The bad point... it segfault every 4 or 5hours... (well it has less time to have mem leak since it segfault).
I can give some core or backtrace...

**Comment by jgaalen** [comment]
Not sure if something has been fixed in the meantime, but I've updated domoticz yesterday and it looks like the memory leak is fixed for me! Thanks for the effort looking into this @thertp 
Before, the memory increased with about 350 MB per day. Now after 24 hours of running, memory is still around 210MB which is like the old days!

**Comment by gizmocuz** [comment]
That's indeed great news!

How about 'crashes' that Xbeaudouin sees... do you experience them as well?
It could be very well a problem with his script

**Comment by jgaalen** [comment]
I haven't had any crashes so far, we'll see.

**Comment by domoticauser** [comment]
Good to read that this has been resolved. I'm currently running on the latest stable version. When will this be included in the stable version? I prefer not to use the beta version.

**Comment by jgaalen** [comment]
![domoticz_mem](https://github.com/domoticz/domoticz/assets/10229665/e76d2b86-81bc-49bc-b81e-447be4df14a5)

This is the memory graph of the domoticz container. As you see, since 26 december, when I've updated domoticz, the memory leak/problem is gone. Stable at around 200 MB. No crashed and I run a lot of hardware/devices and custom python plugins with tons of updates every second

**Comment by gizmocuz** [comment]
@marktn , when we rename the beta to stable it's available as the stable.... hence, you should try the beta

**Comment by pipiche38** [comment]
I do confirm that using the latest source code from today. (build 15781) and using the plugin.py in this Issue leave the VIRT, RES memory at that same size .

So at least I do consider this issue solved.

**Comment by gizmocuz** [comment]
@xbeaudouin, as you can hear... it seems OK, so maybe the issue is indeed in your python code...
I will make a new stable asap
