### ISSUE TITLE
TADO Authentication changes.

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#5882]
Hello @gizmocuz 

TADO is sending an email that says the following:

> We have noticed that you are using the unofficial tado° REST API with an old authentication method. That is, you are making requests similar to https://my.tado.com/api/v2/me?username=myUsername&password=myPassword where username and password are supplied as query parameters with each request.
> 
> We will discontinue the support for this type of authentication and only support OAuth 2 in the future (you can find more information at https://datatracker.ietf.org/doc/html/rfc6749).
> 
> We plan to turn off the authentication on December 4th 2023.
> Important: We will stop synchronizing passwords for this legacy authentication. If you reset your password, the legacy authentication might stop working even before the above date, so please try to switch to the new type of authentication as quickly as possible.

I do not use Tado and I do not know if the Domoticz hardware uses the above mentioned way of authentication.
It is just to inform you, that this email is send to users. Source: https://discourse.nodered.org/t/tado-are-changing-their-authentication-help-needed-please/82991

Regards

**Comment by gizmocuz** [comment]
Maybe someone that used Tado can have a look at this.
As far as I can see in the code, it is already working with tokens
