### ISSUE TITLE
Unexpected behaviour regarding persistent historical data

### ISSUE THREAD

**Issue by elxsi** [domoticz/domoticz#5885]
Hi!

Recently I've added a new LUA script and I was in the need to save persistent historical data:

`
return {
       ...
        data = {
                history = {
                        initial = 0,
                        history = true,
                        maxHours = 8760,
                },
        },
       ...
}
`

Later on, I've checked the historical data in the corresponding __data_handleHistory.lua file and to my surprise, the data was always limited to 100 values. Checking the domoticz source, I saw that the HistoricalStorage function in dzVents/runtime/HistoricalStorage.lua assigns maxItems = MAXLIMIT (with MAXLIMIT=100) and therefore my code does not work as expected. 

The documentation (https://www.domoticz.com/wiki/DzVents:_next_generation_Lua_scripting) does not mention this limit, it only says, that the maxItems has precedence over maxHours and maxMinutes.

So if maxItems is not specified in the data section of a LUA script, maxItems is always set to MAXLIMIT (100) and the corresponding maxHours/maxMinutes functions do not work as expected. 

So I think the HistoricalStorage must be changed:

- only set the MAXLIMIT if maxItems and maxHours and maxMinutes is null (line 64)
- change if query (count < maxItems) in line 92 to
`
if ( (maxItems and (count < maxItems)) or maxMinutes) then
...
end
`
 - change function self.add (line 177):

`
function self.add(data)
  if( (maxItems and self.size == maxItems) or maxMinutes) then
     -- Add additional logic the check if the timestamp of the last element is older than maxMinutes or if maxItems is reached - if so remove last element
   end
`

Thank you!

**Comment by gizmocuz** [comment]
What are you trying to accomplish with the data? is InfluxDB not a better option to use?
I think the initial idea was to limit the return result regardless of type

**Comment by elxsi** [comment]
I need this data only for calculation of an average value of the last 6 days (I don't really need the specific values, only the resulting average value). This could of course be done via influx or via some other calculation method. But I think the main problem here is, that the documentation does not explain this behaviour. A simple fix for my problem was to set maxItems to a higher value. 

Maybe another solution would be to set maxItems to math.huge if maxItems was not defined (but maxHours or maxMinutes were defined), this would simplify the code. The disadvantage is of course that storing a high number of values may slow things down or may even lead to domoticz crashes. So in case maxItems is not defined (but maxHours or maxMinutes), we could issue a warning message when setting maxItems to math.huge (or some other high number) via dz.log?

**Comment by gizmocuz** [comment]
Feel free to make a PR, but we have to set a limit, and for sure not math.huge
Can't you work with the day values? if you are doing an average anyway?

**Comment by elxsi** [comment]
Well, I can't use something like counterToday, because the device I'm using is not a counter (or did you mean something else with "day values"?).

So I would propose to keep the current behaviour but:

- Set MAXLIMIT to something more reasonable (maybe 1000 or 10000)
- Add a info to https://www.domoticz.com/wiki/DzVents:_next_generation_Lua_scripting that maxItems (please specify the default value) is always a hard limit - regardless of the specified maxHours or maxMinutes values and - if a higher maxItems value is required - that it can be overriden by manually setting a higher value).

Would this be ok?

Thank you for your help!

**Comment by gizmocuz** [comment]
If you use a custom sensor, per day it will store the min/max/average in the database. You can retrieve these values and do a average

**Comment by elxsi** [comment]
Thank you, I did not know this. Nevertheless, I think it would still be good to apply to proposed change, at least to update to documentation.

Thank you! :)

**Comment by gizmocuz** [comment]
Not sure if I understand your above code example

`return { ... data = { history = { initial = 0, history = true, maxHours = 8760, }, }, ... }`

I see no 'initial' declared in the wiki, nor in the dzVents code

I do see a 'maxItems' variable you can use, which you can use, and you can set this to a number higher then 100 as you can read in the dzVents runtime

```
	maxItems = MAXLIMIT
	end
	-- maybe we should make a limit anyhow in the number of items
```

There is no need to adjust the wiki nor the code.
