### ISSUE TITLE
MQTT-AD Thermostat setpoint does not get refreshed.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5886]
Version: 2023.2 (build 15658)
Build Hash: 44658f942
Compile Date: 2023-11-19 16:38:42
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

The setpoint of a Thermostat in MQTT-AD is working almost correctly now.
The only thing that is missing is the refresh, so that the end effect after some hours is that the thermostat is displayed in red.
![20 11 2023_18 41 54_REC](https://github.com/domoticz/domoticz/assets/24824113/7dc41f62-3155-4bfd-9f35-462c5aa38dcf)
The left thermostat is changed in setpoint, but the right one is not changed.
Status messages with setpoints in it are coming in regularly that should be reflected in the widget.
Now the thermostat look dead.

**Comment by gizmocuz** [comment]
No issues here, and I was working on a Node Red MQTT-AD project with a setpoint....
As you might now by now, to debug this issue we need the config topic+payload
In this payload you can also see there where the Setpoint expects it's update
You can also try to use mosquitto_pub to publish a value here to see if it is updating.
If not, please post the config payload here so we can debug

**Comment by SargonofAssyria** [comment]
The config data from the device topic homeassistant/climate/0xb4e3f9fffebd9f7f/climate/config
```
{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/BadkamerThermostaat/availability"}],"availability_mode":"all","current_temperature_template":"{{ value_json.local_temperature }}","current_temperature_topic":"zigbee2mqtt/BadkamerThermostaat","device":{"identifiers":["zigbee2mqtt_0xb4e3f9fffebd9f7f"],"manufacturer":"TuYa","model":"Thermostat radiator valve (TV02-Zigbee)","name":"BadkamerThermostaat"},"json_attributes_topic":"zigbee2mqtt/BadkamerThermostaat","max_temp":"30","min_temp":"5","mode_command_topic":"zigbee2mqtt/BadkamerThermostaat/set/system_mode","mode_state_template":"{{ value_json.system_mode }}","mode_state_topic":"zigbee2mqtt/BadkamerThermostaat","modes":["off","heat"],"name":null,"object_id":"badkamerthermostaat","origin":{"name":"Zigbee2MQTT","sw":"1.33.1-dev","url":"https://www.zigbee2mqtt.io"},"preset_mode_command_topic":"zigbee2mqtt/BadkamerThermostaat/set/preset","preset_mode_state_topic":"zigbee2mqtt/BadkamerThermostaat","preset_mode_value_template":"{{ value_json.preset }}","preset_modes":["auto","manual","holiday"],"temp_step":0.5,"temperature_command_topic":"zigbee2mqtt/BadkamerThermostaat/set/current_heating_setpoint","temperature_state_template":"{{ value_json.current_heating_setpoint }}","temperature_state_topic":"zigbee2mqtt/BadkamerThermostaat","temperature_unit":"C","unique_id":"0xb4e3f9fffebd9f7f_climate_zigbee2mqtt"}
```
The data from topic zigbee2mqtt/BadkamerThermostaat
```
{"battery_low":false,"boost_timeset_countdown":0,"child_lock":"UNLOCK","comfort_temperature":20,"current_heating_setpoint":22,"eco_temperature":17,"error_status":0,"fault_alarm":0,"frost_protection":"OFF","heating_stop":"OFF","holiday_start_stop":"2021/01/01 01:01 | 2021/01/01 01:01","holiday_temperature":15,"last_seen":"2023-11-21T08:59:51+01:00","linkquality":51,"local_temperature":18.4,"local_temperature_calibration":"0.0","online":"ON","open_window":"OFF","open_window_temperature":17,"preset":"manual","schedule_friday":"06:00/17 12:00/21 14:00/17 17:00/21 24:00/17","schedule_monday":"06:00/17 12:00/21 14:00/17 17:00/21 24:00/17","schedule_saturday":"06:00/17 12:00/21 14:00/17 17:00/21 24:00/17","schedule_sunday":"06:00/17 12:00/21 14:00/17 17:00/21 24:00/17","schedule_thursday":"06:00/17 12:00/21 14:00/17 17:00/21 24:00/17","schedule_tuesday":"06:00/17 12:00/21 14:00/17 17:00/21 24:00/17","schedule_wednesday":"06:00/17 12:00/21 14:00/17 17:00/21 24:00/17","system_mode":"heat","update":{"installed_version":-1,"latest_version":-1,"state":"idle"},"update_available":false,"working_day":"mon_sun"}
```
The current_heating_setpoint is the one which should update the widget and is always present in the message.

**Comment by gizmocuz** [comment]
All working fine here
Please try to use MQTT Explorer and push the data in by hand, setpoint updates correctly

**Comment by SargonofAssyria** [comment]
Temperature is updated when it is the same, but setpoint has NO last_seen when the device send data on the topic. It only updates when the setpoint has changed from the current setpoint in Domoticz. You can see the red and last_seen in the above widget. And the complete data is send every 5-30 minutes, depends on changes in the thermostat.

**Comment by waltervl** [comment]
I am not sure but looking at the code last_seen is not used to update a domoticz device. So only updating the Domoticz device by sending a value by Zigbee2MQTT should update the last seen in Domoticz. 

But perhaps the Zigbee2MQTT availability topic zigbee2mqtt/BadkamerThermostaat/availability is triggered? Or do you have the setting switch "Add newly received only to the log" activated on menu setup - settings, tab log?

**Comment by gizmocuz** [comment]
Please try to use MQTT explorer to update the device....

First time discovery

![image](https://github.com/domoticz/domoticz/assets/2265299/dece4900-b5d6-46d9-a578-a82dcd50771d)

Now sending the below to topic **zigbee2mqtt/BadkamerThermostaat**

{
  "current_heating_setpoint": 23.5
}

Results in:

![image](https://github.com/domoticz/domoticz/assets/2265299/c11aecbd-9702-449d-b41f-0dec47a53f06)

**Comment by gizmocuz** [comment]
As you can see above, it is working correctly. Also note that thermostats are widely used amongst other users

**Comment by waltervl** [comment]
So the behavior @SargonofAssyria is that after x hours the widget will be colored red (timed out) when the thermostat setpoint is not changed during this time. Setting/updating setpoint is not an issue.

**Comment by gizmocuz** [comment]
Sorry, I needed a few times reading it...
Setpoint devices should indeed not have a timeout as it is acting like a switch
Solved in beta 15664

**Comment by SargonofAssyria** [comment]
In my point of view it would be better that "Last Seen" would be updated instead of just ignoring that the device has a timeout.
This way you cannot check (visually by the color red) on the device that there is no more data coming for a while.

**Comment by gizmocuz** [comment]
Yes, I was doubting this as well and that was the reason in the patch, I added this functionality but commented it out.
Will be updated from beta 15667

**Comment by SargonofAssyria** [comment]
I just updated to 15667, and it works. TNX.
