### ISSUE TITLE
cannot run two System Alive Checker (Ping) in one domoticz setup

### ISSUE THREAD

**Issue by WillemD61** [domoticz/domoticz#5887]
When I run two hardware instances of type System Alive Checker (Ping), even though each checks a different set of IP addresses, I get unreliable results. Devices are reported on when they are not, for example, and status bounces on and off, even though actual status is not changing.

When I combine the IP addresses into one hardware instance, everything works as expected.

I suggest to update the wiki documentation to specifically mention that a domoticz installation can only run one instance of this hardware type (or to solve the issue, but that's probably not easy to do ?...)

**Comment by gizmocuz** [comment]
Well, the reason is that you get a UDP broadcast back, so that makes sense.
You should indeed not do this 😊
Wiki is updated, thanks for mentioning
