### ISSUE TITLE
Not a bug, but may be an enhancement?

### ISSUE THREAD

**Issue by Phil353556** [domoticz/domoticz#5892]
Hi,
My goal is to test the beta, because I'm a Netatmo user and I saw it should be ok with the latest one.

During install, as pi is no more the default username on a raspberry pi,  It may be useful to modify the script:   domoticz.sh

- the script must be first edited before the first run to include the real username where domoticz is installed
OR
- the script may take the user as a parameter

Thank you for all the job done.

![Capture d’écran du 2023-11-23 20-01-19](https://github.com/domoticz/domoticz/assets/64729485/d6a13c16-baed-4fdb-9450-dfd5479592e4)

**Comment by gizmocuz** [comment]
The install script is using the current user. So when you setup Domoticz when logged in as 'phil', it will create a startup script for this user
You probably moved over your installation/(startup)scripts

**Comment by Phil353556** [comment]
Ah ok, sorry.
Yes, I download the tarball,  copy in /home/domoticz,  unzip untar
then ./updatebeta
then sh ./domotic.sh

**Comment by gizmocuz** [comment]
The preferred way (and most easiest) is to use the command line install you can see on our download page

https://www.domoticz.com/downloads/

**Comment by Phil353556** [comment]
right, however when the install is done this way, you already do not know  yet that ./updatebeta exists.

**Comment by gizmocuz** [comment]
You should set the release channel to 'beta' in the settings, and use the web interface to update

**Comment by Phil353556** [comment]
Thank you !
