### ISSUE TITLE
Not a bug, merrily a request

### ISSUE THREAD

**Issue by MichelRabozee** [domoticz/domoticz#5893]
Hi everyone,

I have a domain name (and a Letsencrypt certificate for it), and I host several small web-based tools, each of them behind a different port.

Is it possible to have a startup parameter to disable the header "Strict-Transport-Security" ? The reason is that almost all of my tools can be put in https, only 2 of them cannot (e.g. WeeWX) because they have no - easy - way to configure a certificate to be taken into account by their internal web server.

Without this parameter, if I use Domoticz in HTTPS, as HSTS is enforced on a domain basis (with no difference is other ports are used for other sites), all the tools I have must be in HTTPS as well :-(

Hoping this is possible,

Thank you !

**Comment by gizmocuz** [comment]
I'm not sure if we should disable sending this header:

`HTTP Strict Transport Security (HSTS) is a simple and widely supported standard to protect visitors by ensuring that their browsers always connect to a website over HTTPS.
`

On our wiki there is documentation on how to setup a reverse http proxy with NGINX or Apache.
You can use these methods. There is even a nice docker (compose) version if you google for "jwilder/nginx-proxy"
This one includes letsencrypt as well

**Comment by kiddigital** [comment]
You can run your domoticz on a different subdomain than the others tools.

I think that this way the scope of the HSTS is limited to the subdomain.

**Comment by MichelRabozee** [comment]
OK, thank you. I spent some time last night and found a way to enable https on the 2 remaining tools, so I close this request.
