### ISSUE TITLE
setpoints including dummy all multiply entered temperature

### ISSUE THREAD

**Issue by feelingwalnut** [domoticz/domoticz#5894]
build 2023.2 (15650)
all setpoint devices on system in fahrenheit will multiply entered number as if the input was expected to be celsius. including dummy devices.

make a dummy device on system with a meter/counter setting set to F, enter a desired temperature (70) and temperature now displayed will be 158F (70*1.800000+32= 158)
as for function, internally it seems to respect the entered value as 70 and thermostats will switch on and off at desired 70, but will not display that it is 70.

duplicatable with SVT plugin or generic dummy setpoint device attached to nothing.

**Comment by gizmocuz** [comment]
I don't experience this.
I changed the system to use F
Next created a dummy setpoint, set the setpoint to 70, and it stays 70

![image](https://github.com/domoticz/domoticz/assets/2265299/06c00de8-6430-4c34-98bf-c4b4a6eeb9ec)

Changed it to 60

![image](https://github.com/domoticz/domoticz/assets/2265299/4ddd0170-b7c1-4521-b2cb-85ced4fa5209)

**Comment by feelingwalnut** [comment]
ah, compiled again, same issue. changed .db file to .dbOLD, setup new bare minimum system and changed to F. no issues.
so it is something local to my domoticz.db file, sorry about that.

**Comment by feelingwalnut** [comment]
not sure exactly how i've resolved it for dummy devices but is localized to SVT plugin setpoints now.
maybe recreating those will resolve it entirely.

i was comparing existing .db to a blank slate and made minor changes.

**Comment by gizmocuz** [comment]
No worries, hope you get it sorted!
