### ISSUE TITLE
Bug - Excited PIR sensor locks on active state when Domoticz restarted

### ISSUE THREAD

**Issue by pawol** [domoticz/domoticz#5897]
Excited PIR sensor locks on active state when Domoticz restarted.

15pieces of PIR sensors configured as below
- virtual switch type 
- selected PIR type
- off delay set to 8s
 When some PIR is excited and in that time Domoticz is restarted then PIR stays locked on active state.
The only one method to fix it it to change sensor type via web onto eg. on/off type and then select PIR again.

I use the latest stable linux Domoticz version: 2023.2 (build 15457)

**Comment by gizmocuz** [comment]
So you are saying that it would be a good idea for switch types configured as 'Motion Sensor' and use a 'auto off delay' that at startup we set the status to 'Off' for them?

**Comment by pawol** [comment]
I do not understand what you mean

**Comment by gizmocuz** [comment]
I think that this would be a sollution?

**Comment by pawol** [comment]
could be a solution to force off state (after eg. 3 seconds) on each motion detector sensors when domoticz starts.

**Comment by pawol** [comment]
I suspect the same wrong behaviour when other sensors configured eg. smoke, water, etc.

**Comment by gizmocuz** [comment]
So basically, every switch with an off delay we set to 'off' at startup...

**Comment by gizmocuz** [comment]
Downside, when the PIR is not off, and you have a off script , this won't be called....
So maybe all switches with a off delay on no script, we turn off at startup

**Comment by pawol** [comment]
EverythnierobieCITbokawa1!Ut3pa5s#1be1Ut3pa5s#1be1Ut3pa5s#1be1nierobieCITbokawa1!nierobieCITbokawa1!nierobieCITbokawa1!Ut3pa5s#1be1j

**Comment by gizmocuz** [comment]
Sorry, google detects knows many language exect this one ;)

**Comment by waltervl** [comment]
Normally these PIR devices are sending its off states back to Domoticz so no need to set an off delay. Is your PIR device able to send the status back to Domoticz?

**Comment by gizmocuz** [comment]
@waltervl , there are quite a lot of PIR's that do not send an OFF signal... I think it is safe to say after a restart to set all switches to off when a off delay has been configured... because that delay ain't going to happen

**Comment by waltervl** [comment]
OK, then I am lucky ;-)

**Comment by pawol** [comment]
My PIRs send only ON state by rf433MHz

**Comment by gizmocuz** [comment]
Should be solved in beta 15684
