### ISSUE TITLE
Translation 'Comparing' missing in NL / Label for 'Comparing' chart seems fixed to 'Counter' (Teller)

### ISSUE THREAD

**Issue by martin-g-it** [domoticz/domoticz#5899]
Translations for 'Corparing' in counter logs 

![image](https://github.com/domoticz/domoticz/assets/53882051/0a61c3e3-4c2c-4989-92e7-395ffea32625)

Can be fixed by adding translation: `"Comparing": "Vergelijking"` in domoticz-nl.json (included in /domoticz/www/i18n/domoticz-nl.json.gz)
![image](https://github.com/domoticz/domoticz/assets/53882051/6ad40377-773a-4829-beab-8c30a1b8692b)

Result:
![image](https://github.com/domoticz/domoticz/assets/53882051/0a6d821f-5bc3-42f1-9a64-1d8aee861b76)

For Counters with type = 'Custom', the label of the chart seems fixed to 'Counter' (Teller in Dutch). 

Eg. Water counter has this label:
![image](https://github.com/domoticz/domoticz/assets/53882051/842726d0-4a96-464c-b244-dfc98a10d04f)

Custom counter (name = ie. Heat) gets this label:
![image](https://github.com/domoticz/domoticz/assets/53882051/901621c4-b544-4e64-8230-5c6caa9aa5ba)
In English:
![image](https://github.com/domoticz/domoticz/assets/53882051/3ce160b1-a8b5-47e2-a600-a111ed9502c6)

Settings for custom counter type:
![image](https://github.com/domoticz/domoticz/assets/53882051/fd269323-7727-453b-a42b-86d0847f86d0)

Ideally, the unit should not be needed in the Axis label.

**Comment by gizmocuz** [comment]
Thanks for reporting. The "Comparing" needed to be added to the main language resource file (English).
Once added, other translators could start translating. (I just did the Dutch language, set it to 'Vergelijken')

I don't have your issue that a Custom counter displays 'Counter', it is correctly translated here (latest stable/beta)
You did not mention your Domoticz version number

**Comment by martin-g-it** [comment]
Its on the bottom graph; just updated to latest beta and issue stil persists:

![image](https://github.com/domoticz/domoticz/assets/53882051/923cce34-b154-44aa-aea7-bd1896c0d5bb)

**Comment by gizmocuz** [comment]
![image](https://github.com/domoticz/domoticz/assets/2265299/a0b781ce-36dd-43e9-bae5-7c7f13842e83)

![image](https://github.com/domoticz/domoticz/assets/2265299/c99d3661-0f32-4542-9aea-a8176fc24ae5)

**Comment by gizmocuz** [comment]
You have to select another language to see it translated...?

**Comment by martin-g-it** [comment]
There are actually 2 issues.
1. The translation --> fixed in i18n files
2. The label (Y axis) of the 'Comparing' chart (bottom one for counter sensor type)

**Comment by gizmocuz** [comment]
Now I understand your issue. There is a incorrect Y-Axis label displayed

**Comment by gizmocuz** [comment]
Should be solved in beta 15828

**Comment by martin-g-it** [comment]
Confirmed! 👍
