### ISSUE TITLE
Migrate from Enphase Envoy Plugin to default Domoticz Enphase hardware

### ISSUE THREAD

**Issue by Xavier82** [domoticz/domoticz#5902]
Migrate from Enphase Envoy Plugin to default Domoticz Enphase hardware:

Would be nice to have a way to "migrate" (use of Replace function) from created devices of the Enphase Envoy plugin ([https://github.com/H4nsie/EnphaseEnvoy]) to the default Domoticz hardware Enphase.

I'm not possible to "Replace" hardware device P1 (as created with Enphase Envoy plugin of H4nsie) since the hardware device of the default Domoticz hardware Enhpase is of type "General kWh".

Before opening a new issue, please review the following:

* Please use the search feature to see if your issues have been raised or addressed first.: Done, not found same issue.
* First try to update to the latest beta version: Done, no solution
* Clear your browser cache + AppCache (two different things!!): Done, no solution
* Always state your version and hardware platform when reporting code related issues:
Using on production: 2023.2
Using on test: 2023.2 build 15679
* Often we will require Log Files and Screenshots to help diagnose the issue.:
Forum topic with screenshots:
[https://www.domoticz.com/forum/viewtopic.php?f=28&t=41093]

**Comment by gizmocuz** [comment]
Yeah, can't change this... should never have been a P1 meter in the external plugin.
You might be able to do some queries with "SQLite Expert Personal Edition" when you export the database from the settings page and import it again after some modifications
