### ISSUE TITLE
Update to latest Beta (15686) failed

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#5907]
Update to Beta (15686) failed and system non responding On a Linux X86 system.
Also reported on the forum by an RPi user
https://www.domoticz.com/forum/viewtopic.php?p=309442

While using webupdate I get error: 
Error while downloading Update, check your internet....

I have now no time to investigate further what is happening, just wanted to warn.

For the people having the same issue: this is the way to revert back to the previous installation (when not using Docker)
https://www.domoticz.com/wiki/Raspberry_Pi#Revert_to_backup_after_incorrect_beta_update

**Comment by Eddie-BS** [comment]
Same here, RPI4 running buster complains about

./domoticz: /lib/arm-linux-gnueabihf/libpthread.so.0: version `GLIBC_2.30' not found (required by ./domoticz)
./domoticz: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by ./domoticz)

**Comment by gizmocuz** [comment]
I configured a new build server .... It runs on Debian bullseye.
The reason for this was that it still uses openssl 1.1, but it seems it used a new glibc 

Best to upgrade to bullseye....or use docker compose for domoticz

Monday I will have a look to see if I can build with docker and a old Debian version.

Or we upgrade the build servers to bookworm and  it will use openssl 3

Complicated stuff those Linux distributions and backwards compatibility...

**Comment by Eddie-BS** [comment]
sure it should be upgraded but I am afraid that all extra stuff that runs on my rpi needs to be recompiled to ...
(node-red/mqttbroker/zigbee2mqtt/solaredge plugins/and such)

**Comment by gizmocuz** [comment]
But all that you run via docker compose I hope?

**Comment by Eddie-BS** [comment]
If that is asked to me, NO, I don't run docker.

**Comment by gizmocuz** [comment]
Docker compose .... Okey , maybe worth to use this next time as it's independent of the operating system and very easy to backup/restore
(Same with domoticz .... Runs easy via docker compose ...)

**Comment by Eddie-BS** [comment]
Sorry, this domoticz runs for years and I really don't want to learn docker for this ...

**Comment by gizmocuz** [comment]
docker compose .... And not much to learn

**Comment by Eddie-BS** [comment]
Sorry, I appreciate your efforts, I am glad I can update my domoticz thru the webinterface. 
I really don't want to  do anything on the command prompt if not absolutely neccesary ...
And docker is one of that in my opinion

**Comment by gizmocuz** [comment]
Text file with 10 lines to install each of your packages
Data folder in compose folder...done
Anyway, eventually we need to update to bookworm and openssl 3

**Comment by Eddie-BS** [comment]
sounds great, never done that, no idea where to start ...

**Comment by gizmocuz** [comment]
Google? Maybe go to the domoticz download page and follows the docker link or check our wiki for docker installation

**Comment by SargonofAssyria** [comment]
I have a test system running in docker, and that is running and updating fine.
My problem with docker is that I run a few dzVents scripts that are calling bash scripts which is using some programs that are not in the image. So I have to make my own image.

**Comment by gizmocuz** [comment]
@SargonofAssyria , that is why we have a customstart.sh that is executed on startup that can install various packages

**Comment by waltervl** [comment]
@SargonofAssyria see https://www.domoticz.com/wiki/Docker#custom_startup_script_for_the_container

**Comment by SargonofAssyria** [comment]
Oke, nice, did not know that. Tnx.

**Comment by gizmocuz** [comment]
Build server is now using debian "buster" again, and you should be able to update to 15697 without issues now

**Comment by Eddie-BS** [comment]
looks fine, just did an updatebeta and I  am running build 15697 now, thanks

**Comment by gizmocuz** [comment]
Thanks for confirming!!!
After a new stable release the build servers are going to update to bookworm and will be using OpenSSL 3

**Comment by mcmellow** [comment]
updatebeta went OK. no errors or odd things so far. Thanks.


> After a new stable release the build servers are going to update to bookworm and will be using OpenSSL 3

So I have to update to bookworm sooner or later.  I hope this works OK on a RPi 3B+ Otherwise I have migrate to newer hardware as well.  You know this is a fact with computers, new OS and/or new HW every few years.

**Comment by waltervl** [comment]
On my X86 system update also went fine (as expected as it had no problem before).
Closing this issue

**Comment by fwieringen** [comment]
Hi, just did an updatebeta on Bullseye which resulted in a non-starting domoticz. Reverted to the backup for now. Will have to look into it to see if there are any error messages.

**Comment by gizmocuz** [comment]
@fwieringen , can you provide some more details? Like what hardware, arm6 , arm7, x86? is your buster up2date? (apt update / upgrade)

**Comment by fwieringen** [comment]
Sure. Running on a RPi Zero W. All updates and upgrades done. Noticed that I already run Bullseye :-)

**pi@raspberrypi:~/domoticz $ cat /proc/cpuinfo**
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 997.08
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : 000000007be46d80
Model           : Raspberry Pi Zero W Rev 1.1

**pi@raspberrypi:~/domoticz $ cat /etc/os-release**
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by gizmocuz** [comment]
@fwieringen , this is also a Armv6 issue... 
If someone can point me to a working command line to get schroot / debootstrap working for an armv6 architecture I can have a look to get this working again.
Else best to compile yourself for armv6, stick to 2023.2, or invest in a armv7 system

**Comment by gizmocuz** [comment]
Seems we have to use 'armel' ... question is if we still need to keep supporting this... 

The only thing is that I'm stuck in compiling CMake in the schroot environment.

**Comment by fwieringen** [comment]
Hmm. didn't know it would make this much of a difference. Perhaps this is the good time for me to purchase a RPi 4. I noticed they are available again. Also a good moment to start learning how to use Docker Compose, which probably will not run on a RPi Zero either :-)

**Comment by gizmocuz** [comment]
Then I would suggest a RPI-5 (if you do not need hardware video decoding/encoding) or a oDroid HC-4

**Comment by fwieringen** [comment]
I just ordered an 8GB RPi4. But my expectations are quite low :-) I only want to run Domoticz, perhaps a Unifi Controller (I now have a CloudKey for that), Node-RED and that's basically it. Considering the fact I am coming from a RPi Zero W, the improvement will probably be huge.

**Comment by fwieringen** [comment]
Quick update and final closing comment. Got a RPi4 with bookworm. Decided to take the docker compose approach for Domoticz, Mosquitto, NodeRED and (less relevant) Unifi Network Application. I was quite new to docker, but I am amazed with the clarity and flexibility. Thanks for pointing me in that direction @gizmocuz :-)

Only thing I struggled a bit with is the trusted network area in Domoticz, because I now needed to add the Docker networks of mosquitto and nodered as well, which have dynamic IP's. At the end of the day I just trusted 192.168.\*.\* and 172.\*.\*.\*.

**Comment by gizmocuz** [comment]
@fwieringen , great you got it working! I hope you used docker compose for all of them and use volumes starting with ./ so it will be stored inside the folder you created for each of them.
Yeah it is super flexible and quite easy to setup once you get the hang of it... And making a backup is not easy as well!

About the IP addresses... It is possible to assign a fixed IP address for a docker compose container, but I decided to use the network_mode: "host" option instead of mapping the ports.

```
    network_mode: "host"
      #ports:
      #- "4333:443"
      #- "8080:8080"
```

The reason for this is that I also use WOL (Wakeup on Lan).

For connecting to other dockers this is quite simple, if you have a docker for MQTT, you named the docker (first line under services like **mqtt**), instead of specifying a ip address in domoticz, you type **mqtt**

**Comment by fwieringen** [comment]
Yes, that's exactly how I approached it. Five separate dockers (unifi has one for the app and one for the mongo-db), volumes mounted to paths starting with ./. Backing up is quite easy (I'm sure that's what you meant as well)

Regarding IP-addresses, I now assigned fixed IP's to the various containers. Still in bridge mode though. 

Perhaps a small feature request. Would be nice to have an update notification whenever a new version is available. I noticed this option to be gone in the docker build.

**Comment by Eddie-BS** [comment]
@fwieringen Friso can you help me setting up the docker stuff ?

**Comment by fwieringen** [comment]
> ###
> **[Eddie-BS](/Eddie-BS) ** commented [Dec 13, 2023](#issuecomment-1853658687)

Sure, it's Friso by the way. It's pretty straight forward.
- Install Docker Compose (no need for the Desktop). https://docs.docker.com/compose/install/linux/#install-using-the-repository
- Create a new folder /opt/domoticz
- Create a file in that folder named docker-compose.yml with the contents found at https://hub.docker.com/r/domoticz/domoticz
- Create a folder /opt/domoticz/config (this will include all data to be preserved, like database, scripts, etc)
- Make sure the line in the volumes section in the yml file also references to ./config
- Run **docker compose up -d** which will start up the container, download the latest image from the docker repository, install the image.
- You can now access your Domoticz docker instance at http://<ip>:8080. 

If this runs well, you can take the container down using **docker compose down**. You can copy your current database file in the config folder and start the container again. 

You can do the same for mosquitto and nodered. These have prebuild docker images available at hub.docker.com.

**Comment by Eddie-BS** [comment]
Sorry for the name ;-)

which mosquito and nodered did you get ?

**Comment by gizmocuz** [comment]
@Eddie-BS , best to start here:

https://www.domoticz.com/wiki/Docker

Also different docker compose install instructions which I preffer
Google is your friend, just google for 'nodred docker compose' ?

It's as easy as this:

```
version: "3.7"
services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/London
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
```

**Comment by fwieringen** [comment]
I used the following images:

- eclipse-mosquitto:1.6.15
- nodered/node-red:latest
- domoticz/domoticz:beta

Specific tag voor mosquitto because the 2.0 version appears to have some issues in some cases. Found that out here: https://github.com/eclipse/mosquitto/issues/2040

**Comment by fwieringen** [comment]
> @Eddie-BS , best to start here:
> 
> https://www.domoticz.com/wiki/Docker
> 
> Also different docker compose install instructions which I preffer Google is your friend, just google for 'nodred docker compose' ?
> 
> It's as easy as this:
> 
> ```
> version: "3.7"
> services:
>   node-red:
>     image: nodered/node-red:latest
>     container_name: node-red
>     environment:
>       - TZ=Europe/London
>     ports:
>       - "1880:1880"
>     volumes:
>       - ./data:/data
> ```

The only thing I di not yet understand is why I need to launch containers with 'docker compose up', while 'docker-compose up' gives a file not found. But as far as I understand the functional differences between the two are pretty minimal.

**Comment by gizmocuz** [comment]
"docker compose up" is the same as "docker-compose up", the new method is without the dash

**Comment by SargonofAssyria** [comment]
Just a tip. Why you are adding containers start with this container: https://hub.docker.com/r/portainer/portainer-ce
You can then manage all your containers via Portainer in a nice GUI.

**Comment by gizmocuz** [comment]
@SargonofAssyria , also docker compose containers?
It's also very easy to write a bash script to update a docker compose container in a folder

`docker compose pull && docker compose up --force-recreate --build -d && docker image prune -f`

And if you are using portainer-ce with compose, where are your volume files stored? Inside the compose folder?

**Comment by fwieringen** [comment]
This topic is becoming a Docker Compose discussion platform :-) Since I am only running 4 containers, having an additional container with extensive container management seems to be a bit over the top.

Another things which doesn't work for me yet. I uncommented the log file line in the docker-compose.yml:

    volumes:
      - ./config:/opt/domoticz/userdata
    environment:
      - TZ=Europe/Amsterdam
      - LOG_PATH=/opt/domoticz/userdata/domoticz.log

However, no logfile is visible after launching the container. I would assume it to be at /opt/domoticz/config/domoticz.log op my RPi.

**Comment by SargonofAssyria** [comment]
Sorry for the hijack of the topic, it was just a tip.
My config in portainer is:
```
    volumes:
    #  - ./config:/opt/domoticz/userdata
      - /mnt/dietpi_userdata/docker-data/volumes/domoticz-data:/opt/domoticz/userdata
    environment:
      - TZ=Europe/Amsterdam
      - EXTRA_CMD_ARG= -nocache -nowwwpwd
      - LOG_PATH=/opt/domoticz/userdata/domoticz.log
  ```
And that works. Could be a (write) permission problem.

**Comment by Eddie-BS** [comment]
in the mean time I've been fighting with docker ...
succes varies 
it would be nice if there would be a complete docker-compose file to get things running.
for now I run seperate instances for all needed apps ...
I also run "portainer", "dozzle" and "watchtower" for maintenance

**Comment by fwieringen** [comment]
Isn't the whole idea you have separate containers for everything? I have a separate container for nodered, domoticz, unifi, mosquitto. Works together quite well. If there's an update, just update that container. The rest remains up and running.

Happy to share my docker-compose files with you @Eddie-BS .

**Comment by gizmocuz** [comment]
Yes that's the idea... maybe a combination for Grafana/InfluxDB but for the rest separate

**Comment by fwieringen** [comment]
True. My Unifi container also has two images combined. One for the Unifi Network Application and one for the MongoDB (image set to version 4.4.26).
