### ISSUE TITLE
Thermostat dummy device not recognised by Homebridge and Homekit

### ISSUE THREAD

**Issue by Bertels999** [domoticz/domoticz#5920]
### Issue Guidelines

In the current version of domoticz, both Homebridge and Homekit do not recognise a thermostat anymore. I think this is caused by a change in dummy.cpp. To be more precise: in line 102 the type was changed from pTypeThermostat into pTypeSetPoint.

**Comment by gizmocuz** [comment]
It was renamed …. It’s not a new type
But maybe there was a change for evohome but likely

**Comment by Bertels999** [comment]
Sorry, I was too quick in pointing towards domoticz. 

After some more testing I found out that the latest eDomoticz plugin (2.1.47) of Homebridge is the culprit. Downgrading to the previous version (2.1.46) solved it. I will contact them. 

Thanks anyway.

**Comment by Bertels999** [comment]
We are still not good. It is more complex than I thought. 

When I create a virtual thermostat (with the dummy hardware device) in release 2023.2,  the device type is: SetPoint, SetPoint (indicate in the device box on the web page). Then Homebridge does not recognize it as a thermostat,
 
![image](https://github.com/domoticz/domoticz/assets/122987321/f51c0926-1254-461a-864e-438bc065f6e5)

However, when I create a virtual thermostat in 2023.1 and upgrade to 2023.2, then the device type is: Thermostat, SetPoint and the device is recognized by Homebridge.

PS Sorry for the cluttered picture. It shows the device created in 2023.1 upgraded to 2023.2.

**Comment by Bertels999** [comment]
The error starts to occur in the version of 2 oktober 2023. The version of 18 september does not exhibit this error.

**Comment by gizmocuz** [comment]
> When I create a virtual thermostat (with the dummy hardware device) in release 2023.2, the device type is: SetPoint, SetPoint

The device type is Thermostat/Setpoint

I don't know Homebridge/Homekit, but if they scan for a textual type/subtype, it could indeed very well be that it should be changed. It is more logic now naming it Thermostat/Setpoint

**Comment by gizmocuz** [comment]
Please do not create a duplicate issue

**Comment by Bertels999** [comment]
Sorry, I did that because this entry was closed. ;)

I thought my production environment was 2023.2, but is wasn't. I updated it in the past a few times with a beta version (bad habit). That causes some confusion. 

Having analysed the issue into more detail, using the backups created in the production environment (the *.tar.gz files in the backups folder of my raspberry pi), I was able to pin point the issue more precisely:
- as you said : 2023.2 works correctly
- the beta introduced around  October 2nd 2023 (backup date) introduced the error so that Homebridge and HomeKit do not recognize the thermostats anymore. 

I do not know the internal working of Homebridge and Homekit either, but indeed I suspect that they work with a string for identifying the device type.

I compared the backup of 18 September with the 2 October backup on my production system and found out that the Thermostat type was changed into SetPoint. 

About 13 files in the backup were changed: 6 js files, 4 lua files and 3 html files.

**Comment by Bertels999** [comment]
This is a json call to a thermostat (996 is the IDX) and the response. It is the Type value that is set as "SetPoint". eDomoticz (a plugin for Homebridge) and Homekit expect: "Thermostat". (it is a zwave thermostat connected with domoticz through ZWaveJSUI and MQTT).

http://192.168.2.11:8080/json.htm?type=command&param=getdevices&rid=996

{
    "ActTime": 1701977390,
    "AstrTwilightEnd": "18:36",
    "AstrTwilightStart": "06:31",
    "CivTwilightEnd": "17:11",
    "CivTwilightStart": "07:56",
    "DayLength": "07:55",
    "NautTwilightEnd": "17:54",
    "NautTwilightStart": "07:12",
    "ServerTime": "2023-12-07 20:29:50",
    "SunAtSouth": "12:33",
    "Sunrise": "08:36",
    "Sunset": "16:31",
    "app_version": "2023.2 (build 15563)",
    "result": [
        {
            "AddjMulti": 1,
            "AddjMulti2": 1,
            "AddjValue": 0,
            "AddjValue2": 0,
            "BatteryLevel": 47,
            "CustomImage": 0,
            "Data": "22.0",
            "Description": "",
            "Favorite": 0,
            "HardwareDisabled": false,
            "HardwareID": 18,
            "HardwareName": "MQTT Auto Discovery",
            "HardwareType": "MQTT Auto Discovery Client Gateway with LAN interface",
            "HardwareTypeVal": 125,
            "HaveTimeout": false,
            "ID": "zwavejs2mqtt_0xe358ade5_Node6_climate",
            "LastUpdate": "2023-12-07 20:25:40",
            "Name": "Woonkamer Thermostaat Voor",
            "Notifications": "false",
            "PlanID": "0",
            "PlanIDs": [
                0
            ],
            "Protected": false,
            "SetPoint": "22.0",
            "ShowNotifications": true,
            "SignalLevel": "-",
            "SubType": "SetPoint",
            "Timers": "false",
            "Type": "Setpoint",
            "TypeImg": "override_mini",
            "Unit": 1,
            "Used": 1,
            "XOffset": "0",
            "YOffset": "0",
            "idx": "996",
            "max": 200,
            "min": -200,
            "step": 0.5,
            "vunit": "°C"
        }
    ],
    "status": "OK",
    "title": "Devices"
}

**Comment by gizmocuz** [comment]
Okey but that needs to be changed upstream (by the plugins). It is more logical to call it a setpoint as it was internally as well.
There have been made some recent changes to setpoints, it is now also possible to specify the min/max, step size and unit.
So it can also be used for other things then temperature.
Maybe the plugins could also implement this (min/max/step size and unit)

**Comment by Bertels999** [comment]
Yes, that is a way to go. Thanks.

I submitted a change request to eDomoticz: https://github.com/PatchworkBoy/homebridge-edomoticz/issues/276

**Comment by waltervl** [comment]
@Bertels999 So this issue can be closed I presume?

**Comment by Bertels999** [comment]
Yes it can. It has been resolved in eDomoticz.
