### ISSUE TITLE
Googles notification FCM Legacy HTTP protocol gets deprecated after 6/21/2024

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz#5921]
![image](https://github.com/domoticz/domoticz/assets/14561640/24526c61-4d65-41c1-afae-1522f47d9ad7)

We're using the FCM Legacy HTTP protocol for sending notifications from domoticz to the mobile apps.
https://firebase.google.com/support/faq#fcm-23-deprecation

Next to that we're using Server keys to authenticate that call, which is going to be decommissioned.
![image](https://github.com/domoticz/domoticz/assets/14561640/d0b7abd6-7a90-40a4-9b17-d31b2a08d9cb)
![image](https://github.com/domoticz/domoticz/assets/14561640/bda4b962-7536-4161-beb1-0865270e1caf)

The actions to update this call looks pretty straight forward btw
https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by gizmocuz** [comment]
@galadril , thanks for notifying!
I looked at the code, and there also seems some duplicate code that could be simplified (CNotificationFCM::SendMessageImplementation)
I don't think there is a difference between sending messages to Android or iOS

About the change, could you send me a PM on slack?

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

**Comment by galadril** [comment]
looks like my slack account is disabled on your workspace

_"You recently tried to sign in to Domoticz, but it looks like your account for that workspace is deactivated. We're sorry about that!
If you think this was a mistake, please contact a Workspace Administrator to reactivate the account. "_

**Comment by gizmocuz** [comment]
Sorry about that, no idea how that happened.!
It's activated again

**Comment by galadril** [comment]
Reminder on the deadline 

![image](https://github.com/domoticz/domoticz/assets/14561640/0c308dc4-b693-4f18-a454-1282040c7ce7)

**Comment by galadril** [comment]
@kiddigital Could you maybe assist on this to implement the migration to FCM Api v1 ?
https://firebase.google.com/docs/cloud-messaging/migrate-v1
