### ISSUE TITLE
Thermostat dummy device not recognised by Homebridge and Homekit (reopened)

### ISSUE THREAD

**Issue by Bertels999** [domoticz/domoticz#5922]
_Originally posted by @Bertels999 in https://github.com/domoticz/domoticz/issues/5920#issuecomment-1843782425_
            
This error starts to occur in the version of 2 oktober 2023. The version of 18 september does not exhibit this error.
![image](https://user-images.githubusercontent.com/122987321/288566070-a026b5fc-e889-45b5-a7fb-798df501992d.png)

**Comment by gizmocuz** [comment]
Duplicate
