### ISSUE TITLE
temperature_command_template for Climate AD

### ISSUE THREAD

**Issue by Turbox35** [domoticz/domoticz#5924]
Hello,

I try to create a climate device using MQTT Auto Discovery.
I have an issue using the "temperature_command_template".
Indeed I need so publish on a topic using as example:
 "temperature_command_template":"{{ 'S710='+ (value| string) }}".

When I set a new temperture with the climate device under domoticz it publish :

{ "'S710='+ (value| string)": 19.5 }

instead of what is expected :

S710=19.5

This temperature command template comes from Home Assistant.

This template is not implemented into domoticz or I do something wrong?

**Comment by enesbcs** [comment]
There are no template support in Domoticz currently. You have to find a workaround to use the simplest values possible.

**Comment by Turbox35** [comment]
Ok thanks. Is it planned or definitely not?

**Comment by gizmocuz** [comment]
Not supported and no intention to support this. A normal device should just output a normal number
