### ISSUE TITLE
Add log compare graph to temperatures

### ISSUE THREAD

**Issue by Superpjeter** [domoticz/domoticz#5925]
Is it possible to add a compare graph over the logged years for temperatures (and may be other units)  like it is done in the P1 smart meter log compare graph?

**Comment by gizmocuz** [comment]
You mean the chart you see when you click on 'report' in the top right?

**Comment by Superpjeter** [comment]
I mean the chart at the bottom of the logging page like it is done for the P1 smart meter

![2023-12-24 at 13 58](https://github.com/domoticz/domoticz/assets/44780987/24e36d14-16d8-4475-9c61-b50f7519fb2e)

**Comment by gizmocuz** [comment]
@Superpjeter , could you test beta 15770? I implemented this chart for the temperature (average at the moment) and various other charts from the utility tab.
For the temperature we maybe need a selection what to compare, min/max/average.

**Comment by Superpjeter** [comment]
Very nice, thank you

**Comment by waltervl** [comment]
Looking great, lots of sensor types now have a compare graph! Thanks a lot!
