### ISSUE TITLE
ID column not filled when creating unit in extended framework

### ISSUE THREAD

**Issue by JanJaapKo** [domoticz/domoticz#5926]
Hi, since about a week and some days, I think there is an issue in creating new units in a device in the extended framework. I'm curious if other people have the same issue or something is corrupt on my side.

What happens is that the DomoticzEx.Unit().Create() method executes successful (no error reported) and there is an entry in the DeviceStatus table. However, when checking the content of the table using sqlite, the ID column (first column) is not filled (export from DeviceStatus table, first 3 correct, last 4 not correct):
```
413|19|deviceURL|2|"label orientation"|0|244|73|15|0|12|255|0|""|"2023-11-10 20:41:32"|413|0.0|1.0|0.0|1.0|""|""|0|0|0|""|""|""
414|19|deviceURL|1|"Unit 1"|0|244|73|15|0|12|255|0|""|"2023-11-10 20:44:31"|414|0.0|1.0|0.0|1.0|""|""|0|0|0|""|""|""
415|19|deviceURL|3|"Unit 3"|0|244|73|15|0|12|255|0|""|"2023-11-10 20:44:31"|415|0.0|1.0|0.0|1.0|""|""|0|0|0|""|""|""
|20|54200DSN196R0358|14|Inverter input 1 power (SN: 54200DSN196R0358)||243|29|0||12|255|0|  0.0;      0.00||||||||||||||
|20|54200DSN196R0358|7|Inverter input 2 voltage (SN: 54200DSN196R0358)||243|8|0||12|255|0|0V||||||||||||||
|20|54200DSN196R0358|8|Inverter input 2 Current (SN: 54200DSN196R0358)||243|23|0||12|255|0|0A||||||||||||||
|20|54200DSN196R0358|15|Inverter input 2 power (SN: 54200DSN196R0358)||243|29|0||12|255|0|  0.0;      0.00||||||||||||||
```

This than leads to errors when trying to update. Also, the devices are not shown on the devices tab in Domoticz.

Running (now) on build 15718, started a more than a week back (not sure which build but it should be a relatively new one as I update regularly). Running RPi 3B on BullsEye. Ran:
sudo apt-get update
sudo apt-get upgrade

Did sudo reboot.

You can reproduce it by creating a small plugin that adds 1 unit to a device, for example with this [plugin](https://github.com/JanJaapKo/domoticz-test-plugin)

**Comment by dnpwwo** [comment]
@JanJaapKo,

From memory, that column is supposed to be auto assigned by the database (its an auto-incrementing primary key) which makes me wonder if you have an issue with your database?

I had a look at your test plugin and you should know that line 70 doesn't do anything (creates an instance of a Device object that briefly exists but goes out of scope immediately) and is not required.  The supporting Device object ("deviceURL") will be created by the framework automatically when line 71 is executed.

If you are playing around with the extended framework I'd suggest you have look at [Domoticz-DenonEx-plugin](https://github.com/dnpwwo/Domoticz-DenonEx-Plugin/blob/main/plugin.py).  The 'Ex' framework was designed to make it easier to maintain/extend the code through encapsulation and polymorphism and that plugin shows how to use those.

**Comment by JanJaapKo** [comment]
@dnpwwo tnx for the feedback. I ran an integrity check on the database, the result was OK. Anything else I can check? The auto incrementing of the primary key, is there something I can check? Is the current value persisted in the DB as well (or is this incrementing handled in the DB itself and not the application)?

For me the key advantage of the extended framework is being able to connect multiple units to a device (and have multiple of those devices in a plugin). I'll check out the example, although I'm not sure if I'll find use for these more elaborate uses. Further, I assumed the legacy framework might be deprecated at some point so making any new plugin should be done on the Ex framework.

**Comment by JanJaapKo** [comment]
I did some more investigation. When I dump the database into an SQL file, I notice that the DeviceStatus table is not created with a primary key (in contrast to other tables). Is this correct? Can I fix this manually?

```
CREATE TABLE IF NOT EXISTS "DeviceStatus"(
  "ID" TEXT,
  "HardwareID" TEXT,
  "DeviceID" TEXT,
  "Unit" TEXT,
  "Name" TEXT,
  "Used" TEXT,
  "Type" TEXT,
  "SubType" TEXT,
  "SwitchType" TEXT,
  "Favorite" TEXT,
  "SignalLevel" TEXT,
  "BatteryLevel" TEXT,
  "nValue" TEXT,
  "sValue" TEXT,
  "LastUpdate" TEXT,
  "Order" TEXT,
  "AddjValue" TEXT,
  "AddjMulti" TEXT,
  "AddjValue2" TEXT,
  "AddjMulti2" TEXT,
  "StrParam1" TEXT,
  "StrParam2" TEXT,
  "LastLevel" TEXT,
  "Protected" TEXT,
  "CustomImage" TEXT,
  "Description" TEXT,
  "Options" TEXT,
  "Color" TEXT
);
```

In fact all other CREATE TABLE statements look quite different, more like this:

```
CREATE TABLE Hardware (
    ID            INTEGER       PRIMARY KEY,
    Name          VARCHAR (200) NOT NULL,
    Enabled       INTEGER       DEFAULT 1,
    Type          INTEGER       NOT NULL,
    LogLevel      INTEGER       DEFAULT 7,
    Address       VARCHAR (200),
    Port          INTEGER,
    SerialPort    TEXT          DEFAULT (''),
    Username      VARCHAR (100),
    Password      VARCHAR (100),
    Extra         TEXT          DEFAULT (''),
    Mode1         CHAR          DEFAULT 0,
    Mode2         CHAR          DEFAULT 0,
    Mode3         CHAR          DEFAULT 0,
    Mode4         CHAR          DEFAULT 0,
    Mode5         CHAR          DEFAULT 0,
    Mode6         CHAR          DEFAULT 0,
    DataTimeout   INTEGER       DEFAULT 0,
    Configuration TEXT          DEFAULT ('') 
);

Anyone can post how this should look like?
```

**Comment by dnpwwo** [comment]
If you are using the sqlite3 browser app you can right click the table on the Database Structure tab and select Modify Table and you should see this:
![Untitled](https://github.com/domoticz/domoticz/assets/6850332/44cf03c4-681e-44c9-8e78-938bdaf666d4)
Strangely although the PK column is checked the text below does not show it as a primary key.  Also the auto-increment is not checked but sqlite3 documentation states that it will auto-increment [(A column declared INTEGER PRIMARY KEY will autoincrement)](https://www.sqlite.org/faq.html#q1).

Have you tried creating DeviceStatus entries from native hardware?  I suspect the result will be the same

**Comment by JanJaapKo** [comment]
I found a relatively old backup showing the same table structure. Obviously in my SQL dump, the actual values of DeviceStatus are now also strings. So simply updating the CREATE TABLE is not going to be enough. Or can I import the SQL file with only the create table and no data? Or will that loose the connection to the stored device data (guess so...).

So guess I will have to convert the data to insert to the correct data type.... Tnx for the support. Will close issue (as no domoticz issue, it is likely my playing around....). Any tips welcome, gonna do the conversion tomorrow.

**Comment by JanJaapKo** [comment]
Well obviously I could have corrected the device statusses by hand but writing a conversion script was, if not faster, at least less boring ;) works like a charm again.

Lesson learned: do not mess with the DB.......
