### ISSUE TITLE
use domoticz for automatic testing within travis

### ISSUE THREAD

**Issue by empierre** [domoticz/domoticz#593]
Hello,

  The current build raises this fixed version although only 1.48 is available within travis-ci

domoticz/domoticz: error while loading shared libraries: libboost_thread.so.1.55.0: cannot open shared object file: No such file or directory

**Comment by gizmocuz** [comment]
I do not understand your question/comment, the build system does not display an error
https://travis-ci.org/domoticz/domoticz

**Comment by gizmocuz** [comment]
The build system does not compile boost statically, we might need to change this, as you see in your message, you might need boost 1.55

**Comment by gizmocuz** [comment]
I am testing with a branch to see if it can be statically linked
Seems someone has put this option in the cmake configuration file default 'NO', and it should have been 'YES'

**Comment by empierre** [comment]
great ! sorry I'm just back.

I try to launch domoticz within travis-ci to go further in automatic testing of MyDomoAtHome, so I need to start it to launch all the tests that require activating a specific device, for I propagate back the error if this is not possible.

**Comment by gizmocuz** [comment]
sorry, no idea what your talking about, travis works fine, closing issue until you can explain better what you are trying to archive

**Comment by empierre** [comment]
I am trying to test the Imperihome gateway toward domoticz on Travis.
details here: https://github.com/empierre/MyDomoAtHome/blob/nodejs/.travis.yml

so I download x64 binaries and I start domoticz with my test database.
from this I launch  grunt tests that will verify there is no regression in my code.

still failing samerror

**Comment by empierre** [comment]
hello, is my explanation better for you now ?
