### ISSUE TITLE
MQTT-AD error on Moes AM43-0.45/40-ES-EB devices

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5930]
Version: 2023.2 (build 15721)
Build Hash: 82d2a8d66-modified
Compile Date: 2023-12-10 12:01:55
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

I have these errors on Moes AM43-0.45/40-ES-EB devices
```
2023-12-12 09:17:25.281 Error: MQTT-AD: Select device (RolgordijnOverloop (Set upper limit)) doesn't have the option for received STATE "true")
2023-12-12 09:34:45.173 Error: MQTT-AD: Select device (RolgordijnRechts (Set bottom limit)) doesn't have the option for received STATE "true")
2023-12-12 09:37:20.623 Error: MQTT-AD: Select device (RolgordijnRechts (Set bottom limit)) doesn't have the option for received STATE "true")
```
On Domoticz a 'SET' device is created for the 'Set upper/bottom limit' devices.
The device is never triggered by anything in Domoticz so no idea what triggers the error.
This is the config topic:
```
homeassistant/sensor/0xcc86ecfffebd2d04/set_upper_limit/config
```
and this is the value:
```
{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/RolgordijnLinks/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0xcc86ecfffebd2d04"],"manufacturer":"Moes","model":"Roller blind/shades drive motor (AM43-0.45/40-ES-EB)","name":"RolgordijnLinks"},"enabled_by_default":false,"json_attributes_topic":"zigbee2mqtt/RolgordijnLinks","name":"Set upper limit","object_id":"rolgordijnlinks_set_upper_limit","origin":{"name":"Zigbee2MQTT","sw":"1.34.0-dev","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/RolgordijnLinks","unique_id":"0xcc86ecfffebd2d04_set_upper_limit_zigbee2mqtt","value_template":"{{ value_json.set_upper_limit }}"}
```

**Comment by gizmocuz** [comment]
With the above config I have no error yet... And I am very sure this is for a 'select' type, not for a 'sensor' type

**Comment by SargonofAssyria** [comment]
This is send by zigbee2mqtt at the moment this error occurs.
```
info  2023-12-12 14:50:24: MQTT publish: topic 'zigbee2mqtt/RolgordijnOverloop', payload '{"factory_reset":false,"last_seen":"2023-12-12T14:50:24+01:00","linkquality":112,"motor_direction":"normal","motor_speed":40,"opening_mode":"lift","position":70,"running":false,"set_bottom_limit":null,"set_upper_limit":true,"state":"STOP"}'
```
And this is the display in GUI from zigbee2mqtt
![12 12 2023_14 53 33_REC](https://github.com/domoticz/domoticz/assets/24824113/6cd243af-3cc3-49d3-a7a7-cc55cc0f2033)

**Comment by gizmocuz** [comment]
Okey, but it seems you have also a 'homeassistant/select' type ... in your above config nothing refers to zigbee2mqtt/RolgordijnOverloop

**Comment by SargonofAssyria** [comment]
I have 3 of those devices, they all act the same and have the same type of config. Could be that I mix devices.

**Comment by gizmocuz** [comment]
does not matter, this message is send when something looks wrong for a select type, you have not provided that here so not possible to help without this

**Comment by SargonofAssyria** [comment]
Topic
```
homeassistant/select/0x0c4314fffe5fe910/set_upper_limit/config
```
Value
```
{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/RolgordijnOverloop/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/RolgordijnOverloop/set/set_upper_limit","device":{"identifiers":["zigbee2mqtt_0x0c4314fffe5fe910"],"manufacturer":"Moes","model":"Roller blind/shades drive motor (AM43-0.45/40-ES-EB)","name":"RolgordijnOverloop"},"json_attributes_topic":"zigbee2mqtt/RolgordijnOverloop","name":"Set upper limit","object_id":"rolgordijnoverloop_set_upper_limit","options":["SET"],"origin":{"name":"Zigbee2MQTT","sw":"1.34.0-dev","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/RolgordijnOverloop","unique_id":"0x0c4314fffe5fe910_set_upper_limit_zigbee2mqtt","value_template":"{{ value_json.set_upper_limit }}"}
```
Topic:
```
homeassistant/select/0x0c4314fffe5fe910/set_bottom_limit/config
```
Value:
```
{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/RolgordijnOverloop/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/RolgordijnOverloop/set/set_bottom_limit","device":{"identifiers":["zigbee2mqtt_0x0c4314fffe5fe910"],"manufacturer":"Moes","model":"Roller blind/shades drive motor (AM43-0.45/40-ES-EB)","name":"RolgordijnOverloop"},"json_attributes_topic":"zigbee2mqtt/RolgordijnOverloop","name":"Set bottom limit","object_id":"rolgordijnoverloop_set_bottom_limit","options":["SET"],"origin":{"name":"Zigbee2MQTT","sw":"1.34.0-dev","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/RolgordijnOverloop","unique_id":"0x0c4314fffe5fe910_set_bottom_limit_zigbee2mqtt","value_template":"{{ value_json.set_bottom_limit }}"}
```

**Comment by SargonofAssyria** [comment]
This is the message that comes in:
```
zigbee2mqtt/RolgordijnOverloop
```
with Value:
```
{"factory_reset":false,"last_seen":"2023-12-12T16:21:33+01:00","linkquality":116,"motor_direction":"normal","motor_speed":40,"opening_mode":"lift","position":70,"running":false,"set_bottom_limit":null,"set_upper_limit":true,"state":"STOP"}
```
Might the **"set_upper_limit":true** be the problematic part?
I have 3 devices 1 of them has the bottom and upper still with value null, and that one does not give an error.

**Comment by gizmocuz** [comment]
Thank you for providing the select configuration.
This seems to be a problem with the zigbee2mqtt configuration.

As you can also see from the web interface from Zigbee2MQTT you see that for the 'select' types, you only have one button (SET), and there are no other options.
Normally you would expect that you have more options for a 'select' type, but it's valid.

The value that is send is actually '**true**'  and it is not one of the options (SET), so therefore we display this error.
And it is quite valid to display this

It seems the 'select' is used as a push button, and I would not have choosen this, but rather a sensor/action type maybe

As this select has only one option, I made a patch and assume this option is always send... 

Beta 15724 should solve this, but it's more of a hack...

Either the value that send should be null, or 'SET' and not something else like 'true'

**Comment by SargonofAssyria** [comment]
Tnx, it works, no more errors.
