### ISSUE TITLE
MQTT-AD support for mitsubishi2MQTT

### ISSUE THREAD

**Issue by nonolk** [domoticz/domoticz#5931]
Hello,

Could you please add support for [mitsubishi2MQTT](https://github.com/gysmo38/mitsubishi2MQTT), it supports Mqtt-ad in Homeassistant but not at all in Domoticz even in the latest beta (It creates some devices, but none are usable/updating).

In the logs of the latest, beta have the following error: 
> 2023-12-13 15:40:21.360 Error: Mitsubishi: Climate device unhandled temperature_state_template (32d792)

One of the created devices looks like this:
<img width="602" alt="Screenshot 2023-12-13 at 15 46 06" src="https://github.com/domoticz/domoticz/assets/26922736/b2b06d1a-1f98-499f-96d2-58d211252071">

Where I think it should have at least this levels: "heat_cool","cool","dry","heat","fan_only","off"

There is no fan devices created and no temperature sensors.

When trying to switch off the device, I get the following message:
<img width="584" alt="Screenshot 2023-12-13 at 15 46 18" src="https://github.com/domoticz/domoticz/assets/26922736/40b4947c-5b43-4bba-8ba0-8561afbb8c36">

And in the log I see this:

> 2023-12-13 15:50:18.236 Error: Mitsubishi: climate device unhandled mode_state_template (32d792/clim_lea (32d792))

Here is the log coming from mqtt_ad_record.sh

[mqtt_ad_record_mistubishi.log](https://github.com/domoticz/domoticz/files/13661846/mqtt_ad_record_mistubishi.log)

Thank you in advance

**Comment by gizmocuz** [comment]
The reason for this is that this plugin is using all kinds of funky templates which we do not support.
(And probably will not support)
We expect correct values, not a template with ... if this... then this, add this, else this and so on

Domoticz is also supporting the Mitsubishi directly via wifi
