### ISSUE TITLE
MQTT Pusher Error

### ISSUE THREAD

**Issue by MuadDibVV** [domoticz/domoticz#5932]
Hello,
 Since the last version I have an error : Error: MQTTPush: Failed to start, return code: 15/Lookup error. (Check IP/Port).
Even if the pusher is active or not, every 30s
I tried to configure the pusher to avoid the problem but with no success
And after desactiving the parameter I have still the error and this lis too : Status: MQTTPush: Connecting to :1883

**Comment by differentieel** [comment]
I have over 700 push notifications **every second** with all the same message:

`Error: MQTTPush: Failed to start, return code: 15/Lookup error. (Check IP/Port)`

**Comment by gizmocuz** [comment]
I think we are mixing two different MQTT systems here.

First of all, a new beta is available that solves the MQTT Pusher. It was always started, even if it was not enabled and had no settings....
My mistake! :mrgreen: Since the moment I started developing this it was enabled...

There are actually 3 different MQTT systems in Domoticz now

- Old MQTT hardware, by default it pushes all received devices to a output topic.
New since the last few beta's, there is now a setup button you can click, and you can specify the devices to push (instead of pushing everything)

- MQTT-AD, Auto Discovery system, used by Zigbee2MQTT and ZWaveJS-UI and various other hardware

- MQTT-Pusher (new), like the InfluxDB pusher, but for MQTT. You can now specify which devices and which data you want to push to MQTT as text/string or JSON.

Beta 15727 solves the MQTT Pushers issue

**Comment by MuadDibVV** [comment]
Thank you @gizmocuz 
No more errors, I will test tonight the new MQTT-Pusher
I am also interested by an other MQTT method : a DZVents function
At this time I use my own function with :
domoticz.executeShellCommand("mosquitto_pub -h MyMQTTIPPort -m \"MyJSON\" -t 'MyTopic")
It could be interesting to use a native function : 
domoticz.mqtt(MyMQTTIPPort, MyTopic, MyJSON)
or
domoticz.mqtt(MyTopic, MyJSON) with a global parameter for MyMQTTIPPort

**Comment by MuadDibVV** [comment]
@gizmocuz I have an error with global parameters of MQTT-Pusher : I have the message "MQTT link settings saved" when updated and activated, but the parameters are not saved and are still empty.

**Comment by MuadDibVV** [comment]
> @gizmocuz I have an error with global parameters of MQTT-Pusher : I have the message "MQTT link settings saved" when updated and activated, but the parameters are not saved and are still empty.

@gizmocuz : I still have the problem

**Comment by gizmocuz** [comment]
I can't replicate this... What type of sensor do you want to add? Can you post some screenshots?

**Comment by MuadDibVV** [comment]
![image](https://github.com/domoticz/domoticz/assets/62676693/043afb00-30ac-43cc-b8a5-ea1086a7cdc9)
I try to complete address information and activate the pusher :
![image](https://github.com/domoticz/domoticz/assets/62676693/29d82bc5-39e7-4b42-b5eb-655a76d25f47)
![image](https://github.com/domoticz/domoticz/assets/62676693/c278640a-3edc-4ae1-8829-86f7e89ed6ca)
When I close and come back :
![image](https://github.com/domoticz/domoticz/assets/62676693/3c43ad8d-7a46-41b0-969a-5fcbeafb87be)

**Comment by MuadDibVV** [comment]
@gizmocuz : after studying the code I have found the problem : you force to have a login and password. Is it possible to remove that ?

`if ((linkactive.empty()) || (ipaddress.empty()) || (port.empty()) || (username.empty()) || (password.empty()) || (topic_out.empty()) || (tls_version.empty()))
				return;`

=>


`if ((linkactive.empty()) || (ipaddress.empty()) || (port.empty()) || (topic_out.empty()) || (tls_version.empty()))
				return;`

**Comment by gizmocuz** [comment]
@MuadDibVV , I'm sorry, I can't read anything in the screenshot 🤣

Good find! Yes, your right! I always assumed people protect their systems ;)

From beta 15749 you can now also connect anonymously...

**Comment by MuadDibVV** [comment]
> @MuadDibVV , I'm sorry, I can't read anything in the screenshot 🤣
> 
> Good find! Yes, your right! I always assumed people protect their systems ;)
> 
> From beta 15749 you can now also connect anonymously...

Thank you @gizmocuz 

Yes I will protect my MQTT server quickly (It's not accessible from outside my domoticz docker lan so it was not my priority when I start with MQTT, and then... I left it hanging)

**Comment by MuadDibVV** [comment]
@gizmocuz : the mqtt pusher seems to work the first time :

> 2023-12-22 10:35:38.162 Status: MQTTPush: Connecting to MQTT:1883
> 2023-12-22 10:35:38.365 Status: MQTTPush: connected to: MQTT:1883

But if desactivated and activated, the connexion is not complete (and don't work)

> 2023-12-22 10:37:10.633 Status: MQTTPush: Worker stopped...
> 2023-12-22 10:35:38.162 Status: MQTTPush: Connecting to MQTT:1883

(no "connected"  step)

nb : my MQTT is now secured :-)

**Comment by gizmocuz** [comment]
@MuadDibVV , found the cause! Please try beta 15764, this should solve the problem

**Comment by MuadDibVV** [comment]
@gizmocuz, Thank you. It's corrected.
