### ISSUE TITLE
 Error: Elektra Meter: Power usage to high/low! 

### ISSUE THREAD

**Issue by differentieel** [domoticz/domoticz#5933]
after updating to:

Version: 2023.2 (build 15727)
Build Hash: e4b171fff
Compile Date: 2023-12-15 08:05:33
dzVents Version: 3.1.8
Python Version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

` Error: Elektra Meter: Power usage to high/low! Usage: 7190 Watt. Max Usage configured: 6000. (NodeID: 0x0000, ChildID: 0x0007, SID: Actual Usage (L1 + L2 + L3))`

every time the value is over 6000

**Comment by waltervl** [comment]
This is no bug but a feature. For the next time please use the forum https://www.domoticz.com/forum/index.php

You can adjust the max power setting in menu setup - settings, tab Meters/Counters 
https://www.domoticz.com/wiki/Application_Settings#RFXMeter_.2F_Counter_Dividers

**Comment by differentieel** [comment]
thank youOp 15 dec 2023 om 17:06 heeft waltervl ***@***.***> het volgende geschreven:﻿
Closed #5933 as completed.
