### ISSUE TITLE
With latest beta 2023.2 (build 15747), Tuya temperature & humidity sensors are now in 2 separate devices 

### ISSUE THREAD

**Issue by DGA45** [domoticz/domoticz#5939]
After upgrading from the latest release to beta 2023.2 (build 15747), my Tuya temperature & humidity sensors (TS0601) are no longer refreshed on my dashboard.
I noticed that now instead of having 1 device combining temperature and humidity per sensor, I got 2 new devices : one for temperature and one for humidity:
![tempsnip](https://github.com/domoticz/domoticz/assets/59612603/70607f60-17f8-4559-ba91-62ad286b896c)

This only happened for the Tuya sensors. I also have Xiaomi Mijia Temp&Humidity sensors (lumi.sensor_ht) and they have not been impacted.

**Comment by gizmocuz** [comment]
Does the Tuya has more then one temperature sensor? Like also an 'internal' temperature sensor?
In this case domoticz does not know which one to take and threat them separate.
You can easily use dzVents to make a combination sensor from the right temperature+hum device

**Comment by DGA45** [comment]
Only one temperature information. Here are the exposed data from the Tuya:
{
    "battery": 100,
    "humidity": 53,
    "humidity_calibration": 0,
    "linkquality": 102,
    "temperature": 20.2,
    "temperature_calibration": 0,
    "temperature_unit": "celsius"
}

and the exposed data from the Xiaomi:
{
    "battery": 100,
    "humidity": 61.09,
    "linkquality": 142,
    "power_outage_count": 37078,
    "temperature": 19.83,
    "voltage": 3045
}

Maybe it's related to the "calibration" data ?

**Comment by gizmocuz** [comment]
Could you send me the topic/config payload?

**Comment by DGA45** [comment]
Here are the extracts from the zigbee2mqtt log:
[zigbee config.txt](https://github.com/domoticz/domoticz/files/13740831/zigbee.config.txt)
[zigbee payload.txt](https://github.com/domoticz/domoticz/files/13740832/zigbee.payload.txt)

**Comment by gizmocuz** [comment]
Thank you for this!

Yes, why is there a 'sensor' type for calibration? This should be a 'number' field only.... or at least, you should expect a number field only

This is with the latest zigbee2mqtt?

**Comment by DGA45** [comment]
Yes, this is the latest. Versions are the following:
Version de Zigbee2MQTT: [1.34.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.34.0) commit: [56589dcc](https://github.com/Koenkk/zigbee2mqtt/commit/56589dcc)
Type de coordinateur
: zStack3x0
Révision du coordinateur
: 20221226
Version de l'interface
: 0.6.147
Zigbee-herdsman-converters version
: 15.130.1
Zigbee-herdsman version: 0.25.0

**Comment by gizmocuz** [comment]
Hmmm... could you test beta 15754?
I am now ignoring calibration "sensors" and when searching for unique temp+hum sensors I also ignore 'number' components

**Comment by DGA45** [comment]
Just tested and seems OK now :)
Thanks for the very fast solution.

**Comment by gizmocuz** [comment]
Great! Thanks for the feedback. Still puzzles mee why it is also announced as a 'sensor' component...
