### ISSUE TITLE
New comparing graph is not showing correctly for General/Distance widget.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5948]
Version: 2023.2 (build 15773)
Build Hash: 061750e27
Compile Date: 2023-12-27 14:10:30
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 11 2023, 09:51:27) [GCC 8.3.0]

I am using the General/Distance widget for display the waterlevel of Dutch rivers in centimeters.
That is working correctly.
But it looks that the new added "Comparing" graph is showing cumulative figures of the month.
I think it would be better to show an average of the heights.

**Comment by gizmocuz** [comment]
It is a average but the value needed to be divided by 10. Will be solved...
Thanks for reporting!
