### ISSUE TITLE
MySensor Interface bug found

### ISSUE THREAD

**Issue by ernorv** [domoticz/domoticz#595]
While trying to use the MySensor interface to convert data from HomeWizard to Domoticz, I stumbled upon an issue. Having inserted two sensors, the devices tab did not show any of the devices anymore. Adapting the DevicesController.js I discovered there was an parse error in the produced JSON. 

In the end it was a 'NaN' i managed to get into Domoticz (who doesn't seem to care, nice: robust) but the JSON looks like:

--- -paste

 {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "Barometer" : nan,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "nan hPa",
         "Description" : "",
         "Favorite" : 0,
         "Forecast" : 5,
...
 --- end paste

The nan is now found at the "Barometer" : nan. As there is no guarantee on the input data, is it maybe possible to prevent a 'nan' (as value that is) to be produced in the JSON?

Regards
Erno

**Comment by gizmocuz** [comment]
This means you parsed the wrong data in domoticz
edit the database, remove the device, or better, correct the device sValue, see the wiki (json topic)
