### ISSUE TITLE
Thermostat shouldn't have a timeout

### ISSUE THREAD

**Issue by dwhile** [domoticz/domoticz#5950]
I have set up my heating to be controlled by Domoticz (using z-wave).
To do this I have a boiler control unit and a temperature sensor.

I created a virtual device as a thermostat so that different temperatures could be set at different times.

Everything works OK except that the domoticz dashboard shows the thermostat as having timed out after the time out period( 1 hour).

I am not sure that a thermostat should have a timeout associated with it as it is likely to change infrequently ( overnight from 9 - 6 mine doesn't change).

Not sure whether a physical thermostat which has a temperature sensor in it should have a timeout.

Maybe a solution could be to allow it to be a configurable parameter for thermostats?

**Comment by gizmocuz** [comment]
Do you mean with thermostat device a setpoint device?
Because a setpoint sensor indeed does not have a timeout
At least not in the latest stable/beta, you have not mentioned your version

**Comment by dwhile** [comment]
Hi 

I have version 2023.2 - I am trying to build the latest code but I am on Fedora so am hitting a few problems with missing packages.

**Comment by gizmocuz** [comment]
And are you indeed talking about a Setpoint device? If yes, then it should be solved.

You can also use Domoticz in a docker (compose) container so you do not have to build

**Comment by dwhile** [comment]
Hi
Sorry - yes I selected the thermostat device which I believe has type 242 and subtype of setpoint.

Ah yes I will try the docker route

**Comment by gizmocuz** [comment]
Best to add the thermostat setpoint from the Domoticz hardware page (when you added 1 dummy hardware)

**Comment by waltervl** [comment]
This has been solved in stable 2024.1 If you still see the issue in 2024.1 then please comment to reopen this issue.
