### ISSUE TITLE
Units in new Alfen devices in 2024.1 are incorrect: degrees Celcius

### ISSUE THREAD

**Issue by WillemD61** [domoticz/domoticz#5951]
The new Alfen devices in 2024.1 "Max Charge Current", "Solar Green Share" and "Solar Comfort Level Watt" all show degrees Celcius as unit, probably because those are implemented as setpoint devices.

It is a minor inconvenience since it can easily be changed by using the edit button on the widget, but it would be better to set them correctly right from the start, if possible.

**Comment by gizmocuz** [comment]
You need to set them manually. 
But if you want, please make a PR that will set the right options the first time the sensor is created.
