### ISSUE TITLE
Aqara H1 switches do not update status or allow control since 2024.1

### ISSUE THREAD

**Issue by daserra23** [domoticz/domoticz#5953]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version
* Clear your browser cache + AppCache (two different things!!)
* Always state your version and hardware platform when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by daserra23** [comment]
As mentioned in title, since 2024.1 using zigbee2mqtt all my Aqara H1 switches have lost functionality. They work correctly in the zigbee2mqtt webui. No new devices have been created and if I set the devices page to show most recent changes there are no device changes when I manually toggle the switches although the energy use through the switches is correctly reported.
I cleared the webcache etc and tried in Chrome and also Firefox.

**Comment by daserra23** [comment]
These are WS-EUK04 and WS-EUK03 switches and worked fine for a few years beforehand.

**Comment by gizmocuz** [comment]
And you upgraded from which Domoticz version? And you used Zigbee2MQTT in combination with Domoticz years beforehand?

To be able to analyze this issue we need more information that you can obtain by using an application like MQTT Explorer to connect to your broker.

We need the config topic and payload, as well as some messages when you flip the switch.

config topic is something like homeassistant/xx/yy/xx/config

As this is a gang switch, I suspect you get some push-on switches in Domoticz that you can use as activator in scenes/groups in Domoticz

**Comment by daserra23** [comment]
Hi Gizmocuz. I upgraded from the previous stable, 2023.2 and yes, I used zigbee2mqtt for years beforehand but did not upgrade at the same time. It is version 1.34.0 commit: aae7312.

From MQTT Explorer:

Here is data from the previous stable;

The config for the switch endpoint is ;

`{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/Lounge Light Switch/left/set","device":{"identifiers":["zigbee2mqtt_0x54ef4410003b6026"],"manufacturer":"Xiaomi","model":"Aqara smart wall switch H1 EU (with neutral, double rocker) (WS-EUK04)","name":"Lounge Light Switch"},"name":"Left","object_id":"lounge_light_switch_left","origin":{"name":"Zigbee2MQTT","sw":"1.34.0","url":"https://www.zigbee2mqtt.io"},"payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/Lounge Light Switch","unique_id":"0x54ef4410003b6026_switch_left_zigbee2mqtt","value_template":"{{ value_json.state_left }}"}`

When I flip the switch from within Domoticz I get these messages;

`Topic=zigbee2mqtt/Lounge Light Switch/right/set
Value=OFF`

Here is the full version of the message published;

`{"action":null,"consumption":36.03,"current":0,"device_temperature":31,"energy":36.03,"flip_indicator_light":"OFF","led_disabled_night":false,"linkquality":78,"operation_mode_left":"control_relay","operation_mode_right":"control_relay","power":0,"power_outage_count":29,"power_outage_memory":true,"state":"OFF","state_left":"OFF","state_right":"OFF","voltage":241.45}`

When I flip the switch manually I get this message published;

`{"action":null,"consumption":36.03,"current":0,"device_temperature":31,"energy":36.03,"flip_indicator_light":"OFF","led_disabled_night":false,"linkquality":42,"operation_mode_left":"control_relay","operation_mode_right":"control_relay","power":0,"power_outage_count":29,"power_outage_memory":true,"state":"OFF","state_left":"OFF","state_right":"OFF","voltage":242.9}`

It appears the same.

You are correct that the device also supports button "actions"  but I rarely use these as they cannot be used without flipping the switch status. I just use them in scripts to let me know if switches were flipped manually or not.

I kept the upgraded install on another SSD so I will boot that up and get the same messages from there.

**Comment by gizmocuz** [comment]
Thank you for the payloads. Is it possible to modify your previous comment and also add the complete topic names, like homeassistant/button/xx/yy/config

**Comment by daserra23** [comment]
So using the upgraded installation;

I can switch on the switch from Domoticz and the published message is;

`{"action":null,"consumption":36.026023864746094,"current":0,"device_temperature":31,"energy":36.03,"flip_indicator_light":"OFF","led_disabled_night":false,"linkquality":81,"operation_mode_left":"control_relay","operation_mode_right":"control_relay","power":18.98,"power_outage_count":29,"power_outage_memory":true,"state":"OFF","state_left":"OFF","state_right":"ON","voltage":240.3679931640625}`

But the status isn't updated in Domoticz and if I click it again in Domoticz the same message is sent, and not "state_right":"OFF".

If I flip the switch directly or in zigbee2mqtt the message gets updated correctly but these changes aren't reflected in Domoticz.

It appears the new update can correctly publish but not "read" messages from this device endpoint. Domoticz was able to "read" changes to other topics on this device, for example "zigbee2mqtt/select/0x54ef4410003b6026/operation_mode_left"

**Comment by daserra23** [comment]
> Thank you for the payloads. Is it possible to modify your previous comment and also add the complete topic names, like homeassistant/button/xx/yy/config

Thanks for your swift response.

The whole topic name is;

`zigbee2mqtt/switch/0x54ef4410003b6026/switch_right/config`

**Comment by daserra23** [comment]
This may not be a Domoticz issue.

[https://github.com/Koenkk/zigbee2mqtt/issues/20480](url)

**Comment by daserra23** [comment]
There are lots of reports of Aqara switch issues on zigbee2mqtt 1.34 and 1.35 with lots of attempts at fixing but it doesn't seem to be resolved yet. I think anyone with these switches would be wise to not update from 1.33.

**Comment by gizmocuz** [comment]
In order to have a look into this, please provide me with the config topic + payload and some examples when you toggle the switches with the latest version of zigbee2mqtt

**Comment by gizmocuz** [comment]
And you have another issue, the auto discovery topic should not be the same as the MQTT base topic
You should leave the auto discovery topic to 'homeassistant' or 'domoticz' and leave the MQTT base topic to zigbee2mqtt

**Comment by gizmocuz** [comment]
You provided a config for 'state_left', but your examples contain a ON value for state_right?

**Comment by daserra23** [comment]
> You provided a config for 'state_left', but your examples contain a ON value for state_right?

These were just example payloads, I was switching both switches alternately.

**Comment by gizmocuz** [comment]
Okey, well first get your auto discovery and MQTT base topic correct.
Next please update to the latest zigbee2mqtt
And please provide real topics/payloads otherwise I cannot test/help

**Comment by daserra23** [comment]
> And you have another issue, the auto discovery topic should not be the same as the MQTT base topic You should leave the auto discovery topic to 'homeassistant' or 'domoticz' and leave the MQTT base topic to zigbee2mqtt

The "base topic" is set in zigbee2mqtt settings correct ? And the AD topic is set in the Domoticz hardware tab ? This has worked fine for a few years now, I would like to be certain before I change anything.

**Comment by gizmocuz** [comment]
Well they should be different. If it is working, ok, but they should be named differently
all zigbee2mqtt related data (status) is normally published to the topic zigbee2mqtt (see settings->MQTT)
and the MQTT Auto Discovery topic was by default set to homeassistant, you could have left it as is, or named it domoticz if you like

**Comment by daserra23** [comment]
I guess if I change my AD topic to "domoticz" I also have to change it under "Home Assistant Integration" in zigbee2mqtt ? I am currently doing a system snapshot before I try the upgrade again so this will take quite a while.

**Comment by gizmocuz** [comment]
That is correct, you can set the discovery topic under "Home Assistant Integration" , this topic needs to be the same in the Domoticz MQTT AD hardware

**Comment by daserra23** [comment]
I am posting details for my left lounge light switch ( I will not be touching the right switch) from MQTT Explorer.
My broker is eclipse-mosquitto
My base topic is zigbee2mqtt and my AD topic is zigbeeAD

First I will post with the previous stable Domoticz (2023.2) and the previous zigbee2mqtt (1.34)
This all functions as I would expect.

Here is the AD config for the switch

`zigbeeAD/switch/0x54ef4410003b6026/switch_left
{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/Lounge Light Switch/left/set","device":{"identifiers":["zigbee2mqtt_0x54ef4410003b6026"],"manufacturer":"Xiaomi","model":"Aqara smart wall switch H1 EU (with neutral, double rocker) (WS-EUK04)","name":"Lounge Light Switch"},"name":"Left","object_id":"lounge_light_switch_left","origin":{"name":"Zigbee2MQTT","sw":"1.34.0","url":"https://www.zigbee2mqtt.io"},"payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/Lounge Light Switch","unique_id":"0x54ef4410003b6026_switch_left_zigbee2mqtt","value_template":"{{ value_json.state_left }}"}`

This is the payload when I turn it on in Domoticz

`zigbee2mqtt/Lounge Light Switch/left
set=ON`

This is the "status" of "zigbee2mqtt/Lounge Light Switch" afterwards

`{"action":null,"consumption":36.33,"current":0.15,"device_temperature":30,"energy":36.33,"flip_indicator_light":"OFF","led_disabled_night":false,"linkquality":39,"operation_mode_left":"control_relay","operation_mode_right":"control_relay","power":36.77,"power_outage_count":29,"power_outage_memory":true,"state":"ON","state_left":"ON","state_right":"ON","voltage":238.92}`

When I turn it off manually I get

`zigbee2mqtt/Lounge Light Switch/action
action = single left`

and the "status" of zigbee2mqtt/Lounge Light Switch changes to

`{"action":null,"consumption":36.33,"current":0.15,"device_temperature":30,"energy":36.33,"flip_indicator_light":"OFF","led_disabled_night":false,"linkquality":21,"operation_mode_left":"control_relay","operation_mode_right":"control_relay","power":19.08,"power_outage_count":29,"power_outage_memory":true,"state":"ON","state_left":"OFF","state_right":"ON","voltage":238.92}`

The light turns on and off at the switch and in Domoticz and the status is also shown correctly.

Next I update to 2024.1 but stay on Zigbee2mqtt 1.34. I clear my browser.

Once again I turn on the left switch in Domoticz. I also note that the right switch is now displaying "Off" despite being "On" in reality.
The left light turns on and in MQTT Explorer I see

`zigbee2mqtt/Lounge Light Switch/left/set
set = On`

and the "status" of zigbee2mqtt/Lounge Light Switch changes to

`{"action":null,"consumption":36.33,"current":0.08,"device_temperature":30,"energy":36.33,"flip_indicator_light":"OFF","led_disabled_night":false,"linkquality":39,"operation_mode_left":"control_relay","operation_mode_right":"control_relay","power":37.84,"power_outage_count":29,"power_outage_memory":true,"state":"OFF","state_left":"ON","state_right":"ON","voltage":240.01}`

However in Domoticz the left light still shows as "Off"

If I click it again in Domoticz it sends the same message as before

`zigbee2mqtt/Lounge Light Switch/left/set
set = On`

Obviously this does nothing as the switch is already on.

After about 5 minutes the status finally changes in Domoticz and I am then able to turn it off again in Domoticz, however this status is not updated in Domoticz and the switch still shows as "On"

This action appears in MQTT Explorer as

`zigbee2mqtt/Lounge Light Switch/left/set
set = OFF`

The status in MQTT Explorer at this point is

`zigbee2mqtt/Lounge Light Switch
{"action":null,"consumption":36.34,"current":0.15,"device_temperature":30,"energy":36.34,"flip_indicator_light":"OFF","led_disabled_night":false,"linkquality":42,"operation_mode_left":"control_relay","operation_mode_right":"control_relay","power":17.62,"power_outage_count":29,"power_outage_memory":true,"state":"ON","state_left":"OFF","state_right":"ON","voltage":227.7}
`

Refreshing the switch status in the zigbee2mqtt webUI does not help.

After another 5 minutes BOTH switches appear in Domoticz as "Off" despite the right switch still being "On".

Once again if I click the right switch this time nothing happens as the device is already "On" so set = ON does nothing.

At this point the device status in MQTT Explorer is still

`zigbee2mqtt/Lounge Light Switch
{"action":null,"consumption":36.34,"current":0.08,"device_temperature":30,"energy":36.34,"flip_indicator_light":"OFF","led_disabled_night":false,"linkquality":42,"operation_mode_left":"control_relay","operation_mode_right":"control_relay","power":19.19,"power_outage_count":29,"power_outage_memory":true,"state":"OFF","state_left":"OFF","state_right":"ON","voltage":231.32}`

After waiting 10 minutes both switches still show as "Off" despite the right switch being "On". I am able to turn on the left switch but the change is not reflected in Domoticz again.

I then update to zigbee2mqtt 1.35 (Latest 1/1/24)

The AD config topic is

`zigbeeAD/switch/0x54ef4410003b6026/switch_left/config
{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/Lounge Light Switch/left/set","device":{"identifiers":["zigbee2mqtt_0x54ef4410003b6026"],"manufacturer":"Xiaomi","model":"Aqara smart wall switch H1 EU (with neutral, double rocker) (WS-EUK04)","name":"Lounge Light Switch","via_device":"zigbee2mqtt_bridge_0x00124b002298908f"},"name":"Left","object_id":"lounge_light_switch_left","origin":{"name":"Zigbee2MQTT","sw":"1.35.0","url":"https://www.zigbee2mqtt.io"},"payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/Lounge Light Switch","unique_id":"0x54ef4410003b6026_switch_left_zigbee2mqtt","value_template":"{{ value_json.state_left }}"}`

The result is no change, switch changes made manually or in zigbee2mqtt are not reflected in Domoticz although sometimes after a few minutes an "On". The changes are reflected in Mqtt Explorer here

`zigbee2mqtt/Lounge Light Switch
{"action":null,"consumption":36.34,"current":0.08,"device_temperature":30,"energy":36.34,"flip_indicator_light":"OFF","led_disabled_night":false,"linkquality":42,"operation_mode_left":"control_relay","operation_mode_right":"control_relay","power":19.19,"power_outage_count":29,"power_outage_memory":true,"state":"OFF","state_left":"OFF","state_right":"ON","voltage":231.32}`

but not here

`zigbee2mqtt/Lounge Light Switch/left/set
set = OFF`

I have now reverted back to 2023.2 and 1.34 and all is working again.

**Comment by daserra23** [comment]
I should add that Domoticz runs on bare Buster/Raspberry pi3b and mosquitto and zigbee2mqtt are in dockers.

**Comment by dave21w** [comment]
I have the same problem although now I am unsure where the issue actually lies, the reason being this. 
I did a fresh install of bookworm x64 on my home system, Domoticz ver 2024.1, mosquitto ver 2.011 and zigbee2mqtt ver 1.34, previously to this I was on buster x32, mosquitto ver 2.011 and zigbee2mqtt 1.33. 
On my old install everthing worked as it should, on the new install I have the same problem as daserra23. Toggling the switch in z2m changes its state as expected however in Domoticz providing the physical switch is off either pressing the widget or sending a command will turn the physical switch on but in domoticz it remains off so any further presses of the widget still sends an On becuase it thinks it's off. 
Toggling the state of the switch in z2m or pressing the actual switch button does not change the Domoticz state. Given that I read of Aqara H1 switch issues in z2m 1.34 (after I had installed) which were supposed to be resolved in the beta I waited for 1.35 to be released and updated to this but no different. I also have a test system at work which is the same as my new install at home except it runs the Domoticz beta so is currently on 2024.1 (15801), this morning I took one of my spare Aqara switches to work and added it to z2m, it appeared in Domoticz and I could toggle it's state in Domoticz so I updated my home system to 2024.1 (15801) but no change, the problem is still present. In my test system if I flip the switch indicator light (in z2m) so the led in the switch is on when the switch is off the light in the physical switch changes but it's indicator for this state in Domoticz doesn't change however the Domoticz indicator for this function mimics the switch state instead as well.
Unlike daserra23 my systems have always had zigbee2mqtt as the base z2m topic with homeassistant as the HA discovery topic in both. I find it very strange that as far as I can tell both installs are identical even down to the coordinator type and yet they are displaying different symptoms, the work test system isn't an issue obviously however the "wife approval factor" at home is rapidly diminishing !
MQTT explorer seems to show the switch state being broadcast correctly so why my work install is responding and my home one isn't I have no idea.

**Comment by dave21w** [comment]
Posted a response here as well 
https://github.com/domoticz/domoticz/issues/5961
And yes Aqara H1 issue resolved for me 
Thanks

**Comment by daserra23** [comment]
> Posted a response here as well #5961 And yes Aqara H1 issue resolved for me Thanks

Thanks for that. I believe there is an imminent  new stable so I will wait till then.

**Comment by gizmocuz** [comment]
Thanks for the feedback. Closing issue.
@daserra23 , best to upgrade to the beta so you will also not have surprises in the feature
But as there is a possible issue now with other switches we need to get this sorted/resolved before a new release
