### ISSUE TITLE
Temperature is being converted from Fahrenheit incorrectly

### ISSUE THREAD

**Issue by nahall** [domoticz/domoticz#5956]
Running the latest beta build 15797.

I have a ZSE44 Zooz Temperature/Humidity sensor.

The sensor is configured to report temperature in Fahrenheit, which is its default. Domoticz is also configured to display temperature in Fahrenheit.

Z-Wave JS UI displays the correct temperature in Fahrenheit, however, Domoticz is displaying the wrong temperature because it is assuming that the temperature is in Celsius and then converting it to Fahrenheit.

Here is an example, the sensor is reading 75.5 Fahrenheit, and this value is showing correctly in Z-Wave JS UI. Domoticz is configured to display temperatures in Fahrenheit but it is showing as 167.9F, which is the same as 75.5 _Celsius_ converted to Fahrenheit. If I change Domoticz to display temperatures in Celsius, it then displays 75.5C.

Here are the lines from the debug log:

> 2024-01-02 16:46:58.495  Debug: Z-Wave JS UI: topic: homeassistant/sensor/Master_Bath_Temp-Hum/temperature_air/config, message: {"value_template":"{{ value_json.value }}","unit_of_measurement":"°F","state_class":"measurement","device_class":"temperature","state_topic":"zwave/Master_Bath_Temp/Hum/sensor_multilevel/endpoint_0/Air_temperature","json_attributes_topic":"zwave/Master_Bath_Temp/Hum/sensor_multilevel/endpoint_0/Air_temperature","device":{"identifiers":["zwavejs2mqtt_0xe32a7dab_node2"],"manufacturer":"Zooz","model":"Temperature Humidity XS Sensor (ZSE44)","name":"Master Bath Temp/Hum","sw_version":"1.20.1"},"name":"Master Bath Temp/Hum_temperature_air","unique_id":"zwavejs2mqtt_0xe32a7dab_2-49-0-Air_temperature"}
> 2024-01-02 16:46:58.496  Status: Z-Wave JS UI: discovered: Master Bath Temp/Hum (Master Bath Temp/Hum_temperature_air)/Master Bath Temp/Hum (Master Bath Temp/Hum_temperature_air) (unique_id: zwavejs2mqtt_0xe32a7dab_2-49-0-Air_temperature)
> 2024-01-02 16:46:58.597  Debug: Z-Wave JS UI: topic: homeassistant/sensor/Master_Bath_Temp-Hum/humidity_air/config, message: {"value_template":"{{ value_json.value }}","unit_of_measurement":"%","state_class":"measurement","device_class":"humidity","state_topic":"zwave/Master_Bath_Temp/Hum/sensor_multilevel/endpoint_0/Humidity","json_attributes_topic":"zwave/Master_Bath_Temp/Hum/sensor_multilevel/endpoint_0/Humidity","device":{"identifiers":["zwavejs2mqtt_0xe32a7dab_node2"],"manufacturer":"Zooz","model":"Temperature Humidity XS Sensor (ZSE44)","name":"Master Bath Temp/Hum","sw_version":"1.20.1"},"name":"Master Bath Temp/Hum_humidity_air","unique_id":"zwavejs2mqtt_0xe32a7dab_2-49-0-Humidity"}
> 2024-01-02 16:46:58.599  Status: Z-Wave JS UI: discovered: Master Bath Temp/Hum (Master Bath Temp/Hum_humidity_air)/Master Bath Temp/Hum (Master Bath Temp/Hum_humidity_air) (unique_id: zwavejs2mqtt_0xe32a7dab_2-49-0-Humidity)
> 
> 
> 2024-01-02 16:47:39.910  Debug: Z-Wave JS UI: topic: zwave/Master_Bath_Temp/Hum/sensor_multilevel/endpoint_0/Air_temperature, message: {"time":1704234787054,"value":75.5,"nodeName":"Master Bath Temp/Hum","nodeLocation":"Master Bathroom"}

I did also verify that the temperature in the SQLite Temperature table is 75.5 in this case.

I'm not familiar with the Domoticz code base, but after a quick look it looks like MQTTAutoDiscover::GuessSensorTypeValue is detecting if it is Fahrenheit and then converting the temperature to Celsius and then saving the result to pSensor->sValue, however, when MQTTAutoDiscover::handle_auto_discovery_sensor gets the data it has some different logic depending on if the sensor has temperature, humidity, and/or barometric capabilities. 

If this were just a temperature sensor, it would do the correct thing by using pSensor->sValue:
```
 		else
 		{
 			//No combination found, use original device parameters
 			devType = pSensor->devType;
 			subType = pSensor->subType;
 			szDeviceID = pSensor->unique_id;
 			sDeviceName = pSensor->name;
 
 			nValue = pSensor->nValue;
 			sValue = pSensor->sValue;
 		}
```

However in my case this is a combination temperature/humidity sensor so it uses this logic:
```
		else if (pTempSensor && pHumSensor)
		{
			//Temp + Hum
			if (
				(pTempSensor->last_received == 0)
				|| (pHumSensor->last_received == 0)
				)
				return; // not all 2 received yet
			devType = pTypeTEMP_HUM;
			subType = sTypeTH1;

			sValue = std_format("%.2f;%d;%d", temp, humidity, Get_Humidity_Level(humidity));
		}
```

And temp here was previous set as:
`temp = static_cast<float>(atof(pTempSensor->last_value.c_str()));`

So it is fetching pTempSensor->last_value, which wasn't converted to Celsius by MQTTAutoDiscover::GuessSensorTypeValue. I think it should probably be fetching pSensor->sValue or having MQTTAutoDiscover::GuessSensorTypeValue save the converted temperature back into pSensor->last_value.

I could be wrong here, though, as this is the first time I've investigated anything in this code and haven't spent enough time to really understand how these MQTT messages flow from Z-Wave to Domoticz.

**Comment by gizmocuz** [comment]
There is no "unit_of_measurement" specified in the config, so Domoticz does not know if it is Fahrenheit or Celsius.
For example, my temp sensors specifes:

"unit_of_measurement": "°C"

Domoticz converts to Fahrenheit on the fly, meaning all values are stored in Celsius in the system, and when being presented it will convert it

Are you able to add this in ZWaveJS for your sensor?

**Comment by gizmocuz** [comment]
Can you configure the sensor in ZWaveJS-UI between Celsius and Fahrenheit, does it send another value if you change this?

**Comment by nahall** [comment]
The unit_of_measurement is passed from Z-Wave JS UI as "unit_of_measurement":"°F"

2024-01-02 16:46:58.495 Debug: Z-Wave JS UI: topic: homeassistant/sensor/Master_Bath_Temp-Hum/temperature_air/config, message: {"value_template":"{{ value_json.value }}",**"unit_of_measurement":"°F"**,"state_class":"measurement","device_class":"temperature","state_topic":"zwave/Master_Bath_Temp/Hum/sensor_multilevel/endpoint_0/Air_temperature","json_attributes_topic":"zwave/Master_Bath_Temp/Hum/sensor_multilevel/endpoint_0/Air_temperature","device":{"identifiers":["zwavejs2mqtt_0xe32a7dab_node2"],"manufacturer":"Zooz","model":"Temperature Humidity XS Sensor (ZSE44)","name":"Master Bath Temp/Hum","sw_version":"1.20.1"},"name":"Master Bath Temp/Hum_temperature_air","unique_id":"zwavejs2mqtt_0xe32a7dab_2-49-0-Air_temperature"}

The sensor apparently always sends the temperature in Fahrenheit.

**Comment by gizmocuz** [comment]
Sorry about this, I was expecting this at the bottom of the config (for some strange reason....) (today my mind is more alphabetically 😁)

Testing with the above config and payload when Domoticz is still in Celscius mode results in

![image](https://github.com/domoticz/domoticz/assets/2265299/3b08dd36-d3c4-4df2-a0d6-be5b0fdb0be5)

When I configure Domoticz to Celsius the widget directly displays

![image](https://github.com/domoticz/domoticz/assets/2265299/32c54bd2-bb56-446d-840e-2864b35a154b)

When I send a new temperature (one degree higher), I get:

![image](https://github.com/domoticz/domoticz/assets/2265299/71a6ad1e-e28b-4cf2-aa4f-d39053b2a3c3)

**Comment by nahall** [comment]
Hmm, I don't really know enough about Domoticz's communications with Z-Wave JS UI to have a good guess why it is different for you. Are the messages you are manually sending still coming through the same MQTTAutoDiscover.cpp code path as if they were from Z-Wave JS UI?

Here are screenshots from my current system.

Z-Wave JS UI:
![Screenshot_20240103_102647](https://github.com/domoticz/domoticz/assets/1083916/8eb90ca7-cc20-4c13-8a85-44c4df48729b)

Domoticz:
![Screenshot_20240103_102704](https://github.com/domoticz/domoticz/assets/1083916/663e9f16-c187-4e2c-bfe2-55b5403bb141)

**Comment by nahall** [comment]
OK, scratch that, I think I see what is going on now. My sensor is showing as combination temperature/humidity, yours is only showing as a temperature. Those go through different code paths as I had in my original comment.

Here is a complete dump of the MQTT messages since yesterday, try that, I bet it works now if it shows up as the combo temperature/humidity sensor:

[master.log](https://github.com/domoticz/domoticz/files/13821321/master.log)

**Comment by gizmocuz** [comment]
Thank you for the extended logs! Found the issue and found the solution.
Should be solved in beta 15810

**Comment by nahall** [comment]
That fixed it, thanks!
