### ISSUE TITLE
After updating to 2024.1 master device makes new devices of slave sysfs GPIO switches constantly .

### ISSUE THREAD

**Issue by Mike19700** [domoticz/domoticz#5957]
Since 2024.1 I got the problem that the master device RPI-130 makes a new device after renaming or replacing an old device.
Eg. The master Raspberry pi got a new device from a slave Rpi With ID 0000001 and unit number 26 and gives it the Idx number 1791. See attached picture.

However when I rename the device into 'Pomp vloerverwarming' and change the Icon, the device is not usable anymore. I can not activate it by hand or with a LUA-script. At first I used the switches switches with a password. I disabled the password but that also did not work.

When I turn the switch on on the slave Rpi, a new device is made at the master Rpi with the same ID and Unit number of the previous device. Except (naturally), the Idx, that got a different number 1794.  To use it in my LUA-script, I have to rename it but then it can not be used anymore.

The switches I use are relays controlled by SYSFS GPIO and have always worked until now.
I think it is a SYSFS GPIO problem. I also have a switch attached as an input to a GPIO port and it gives the same problems when I change the name. Other devices do not have that issue.

![Schermafbeelding 2024-01-03 155251](https://github.com/domoticz/domoticz/assets/98214950/6581afce-6e3e-46f4-8af7-595649c1b5aa)

**Comment by gizmocuz** [comment]
Did you update to the latest beta version on both instances?

**Comment by Mike19700** [comment]
Yes on both Rpi's I'll run the latest beta version

**Comment by ilkaskim** [comment]
I have the exact same problem.

**Comment by gizmocuz** [comment]
Are both systems running the same beta or the same stable?

**Comment by ilkaskim** [comment]
Both have the latest beta version installed
 Version: 2024.1 (build 15801)

**Comment by gizmocuz** [comment]
The terminology master/server/slave/client is confusing. 
The server is where the real actual hardware is, and the client (another domoticz instance) is connecting to this.
The server/master does not receive a devices, it sends them to the client downstream

@ilkaskim , you also use SysFS GPIO?

It is very strange the exact new device is created with another IDX... that is not possible.

I also think (hope) that only one time this new device is created, when you flip the switch on the server/master (maybe we should use server in these days), the device on the client should update, it should NOT create another instance.
Is this correct? (Do not rename or do anything else)

Now when you add this new device to your client system (call it switch_new), and flip the switch, does it actually go on on the server instance? (It should be)

You do know that you get all new devices with the beta?
You have to press 'edit' on the old light, and press replace, and select 'switch_new'

**Comment by ilkaskim** [comment]
I'm also using SysFS GPIO, 

I have a script running on the master that is supposed to open my door at 05:49. 

Script runs through and a new switch is created at the master with the idx 690.

The right one is idx 250

After the update, I replaced all switches on the master coming from slave because it didn't work. 

It works like normal even after replacement, only that it doesn't work with the script anymore. 

I didn't do renaming either.
![20240105_170454.jpg](https://github.com/domoticz/domoticz/assets/16821599/baebe004-6b8d-4a66-befc-ef9ee43344f2)

![20240105_170559.jpg](https://github.com/domoticz/domoticz/assets/16821599/4dd3f5e7-e7b5-4f78-bcbe-56d66cbf1322)

![Screenshot_20240105_061117_Chrome.jpg](https://github.com/domoticz/domoticz/assets/16821599/05a7b4bb-b9a5-430f-bba4-b8e8ad42fc4d)

In the log I also get error message.
Error: Werkstatt: Invalid data received!

Werkstatt Is my slave

**Comment by gizmocuz** [comment]
"Invalid data received" you can also get when you do not have the latest beta version on both systems

"Werkstatt" is that the Domoticz Remote hardware in Domoticz? If yes, see above line

And as mentioned above, you do get new devices! You have to press edit on the old device and choose Replace and select the new one.
From this time it will be OK
This has been mentioned on the forum news post

**Comment by ilkaskim** [comment]
> "Invalid data received" you can also get when you do not have the latest beta version on both systems
> 
> "Werkstatt" is that the Domoticz Remote hardware in Domoticz? If yes, see above line
> 
> And as mentioned above, you do get new devices! You have to press edit on the old device and choose Replace and select the new one.
> From this time it will be OK
> This has been mentioned on the forum news post


Master
![Screenshot_20240106_132316_Chrome.jpg](https://github.com/domoticz/domoticz/assets/16821599/b24d654b-3e5e-4f23-9f94-091faa60da9d)

Slave Werkstatt/Remote
![Screenshot_20240106_132332_Chrome.jpg](https://github.com/domoticz/domoticz/assets/16821599/30e6cd9b-eccd-4ab0-a70a-1babceb34f09)

Werkstatt Is slave or remote

Again, after the update to 2024, the switches/devices have doesn't work. 
I've replaced it with the new one
I can switch all devices without a problem. 
Problem only starts when Blockly or dzvents is supposed to switch.

**Comment by Mike19700** [comment]
> I also think (hope) that only one time this new device is created, when you flip the switch on the server/master (maybe we should use server in these days), the device on the client should update, it should NOT create another instance. Is this correct? (Do not rename or do anything else)
> 
> Now when you add this new device to your client system (call it switch_new), and flip the switch, does it actually go on on the server instance? (It should be)
> 
> You do know that you get all new devices with the beta? You have to press 'edit' on the old light, and press replace, and select 'switch_new'

Sorry for the confusion of server and client. Did not realise it.
I performed the above as you described.

1. pushed a button on the server.
2. It was newly created on the client.
3. When I flip the switch on the client, it flips also on the server. But I have to refresh both browsers on the client and the server to see if it really flipped. 
4. I renamed the device on the client as new.
5. I edited the old switch and replaced the new switch with the old one.
6. Now it works. Both, server and client are running the latest beta version.15805.

Sometimes when I edit the old switch on the client and replace the new one with the old one and press 'OK', it takes a lot of time until the replace screen dissapears. Then I got a push message that the domoticz version of the client is restarted. As result, both switches are still available so the replacement did not go well.

Triggered about the above 'problems' I searched a bit more.
I think it is a problem with rights, users and trusted networks.
Both devices are in the same network.
When I push a switch on the server, after a while it appears on the client device.
Then I rename the device into new.
From the devices tab I add the new device as a new device.
At the users tab, I add the device to me. Strange because I already logged into domoticz with my name and the new devices are visible.
Back to the devices tab, I can control the switch on the server with my OLD switch but not with the NEW one.
The I go to the Switches tab and edit the old switch.
I click on 'Replace' and replace the new switch.
Now domoticz is not responding for a time but on the client pi 'sudo service domoticz status' gives a running state. But the browser is not responding at all.
After a minute or so, the client screen is responding again.
Both switches, the new and old one are still there but with both I can NOT flip the one ont the server.
When I press the switcg on the server, a new switch appears on the client.
So now I have 3 switches on my client.
Only with the last added switch on the client I can toggle the switch on the server.
But after pressing the switch on the client I have to refresh the browser to see that the state has changed.
I removed the first new switch because that does not do a thing anymore.
Again, Domoticz does not respond for a long time.
Getting the Domoticz Active state on the client gives me a Inactive dead messeage.
So monit kicks in and restarts Domoticz.
Still having 3 devices.
That is it for the moment.
If you want me to do someting, do not hasitate to ask -;)

**Comment by ilkaskim** [comment]
I uploaded a screen recording to Youtube. 
Maybe it will be a little more understandable. 
My English is not so good for long explanations sorry 😁


https://www.youtube.com/watch?v=4FiEodGDXQE

**Comment by gizmocuz** [comment]
Thanks for the explanation/video and hint about the eventsystem.
You're right!!! It was indeed not working from here!! Whoeps... (it was a big patch)
Please find a new beta version (15808) that should solve the issue!

**Comment by Mike19700** [comment]
Seems the problem has been solved here.
Thanks for the good work.
Keep it up.

**Comment by Mike19700** [comment]
Closing the issue.
