### ISSUE TITLE
Segmentation fault with 2024.1 on Raspberry 1B

### ISSUE THREAD

**Issue by RonMeiburg** [domoticz/domoticz#5958]
My Raspberry 1B, which has been running domoticz for years, runs into a 'segmentation fault' after updating to 2024.1. I backed up the the db and the scripts, wrote the latest bullseye image to the SD and installed domoticz with default settings.
Without even pulling the db and the scripts back, running domoticz again immediately returns a segmentation fault. This does not happen however with 2024.1 on a 3B that I use for testing purposes.

I then ran domoticz' updatebeta script on the 1B to see if that would fix things, but this time it crashed immediately with an 'illegal instruction'

**Comment by Tigerstrength** [comment]
Armv6 is not supported anymore, so the rpi 1B can not run Domoticz. Time to switch it with the test rpi 3B+ I am afraid.

**Comment by RonMeiburg** [comment]
I can accept that, but a little warning would have been nice to avoid a lot of hassle and wasted time.

**Comment by kofec** [comment]
You can always use Openwrt. There you can use any architecture

**Comment by Tigerstrength** [comment]
It is mentioned in the change log, but I agree that I also would prefer a software check with warning before the update was offered. Maybe a enhancement for the future?

[topic on Domoticz forum](https://www.domoticz.com/forum/viewtopic.php?t=41239)

**Comment by gizmocuz** [comment]
There was a BIG warning in the changelog on our forum. Always check the forum release notes before updating

**Comment by RonMeiburg** [comment]
Can I suggest the wiki on https://www.domoticz.com/wiki/Raspberry_Pi is also updated, I quote:
**Prerequisites**

The following things are needed to install Domoticz and your chosen operating system successfully.
    Raspberry Pi 4, Pi 3 Model B (Raspberry Pi 1 Model B(+) and 2 model B are supported as well)

It might just be a source of reference for other ignorantia like me.

**Comment by gizmocuz** [comment]
That’s not correct you can compile yourself
