### ISSUE TITLE
AD number type discovery shows wrong device description

### ISSUE THREAD

**Issue by Tigerstrength** [domoticz/domoticz#5959]
Hi,

Using Domoticz stable 2024.1.

When auto discovering number type devices all works well except the device description which shows wrongly. 

This discovery topic should produce the device description `Nefit Boiler` from `"name":"Nefit Boiler"` :

`{"uniq_id":"boiler_selected_flow_temperature","obj_id":"boiler_selected_flow_temperature","cmd_t":"Nefit/boiler/selflowtemp","mode":"box","step":1,"min":0,"max":90,"ic":"mdi:coolant-temperature","stat_t":"Nefit/boiler_data","name":"Selected flow temperature","unit_of_meas":"°C","val_tpl":"{{value_json.selflowtemp if value_json.selflowtemp is defined else 0}}","dev":{"ids":["Nefit-boiler"],"name":"Nefit Boiler","mf":"Buderus","mdl":"Enviline/Compress 6000AW/Hybrid 3000-7000iAW/SupraEco/Geo 5xx/WLW196i/WSW196i","via_device":"ems-esp"},"avty":[{"t":"Nefit/status","val_tpl":"{{'online' if value == 'online' else 'offline'}}"},{"t":"Nefit/boiler_data","val_tpl":"{{'online' if value_json.selflowtemp is defined else 'offline'}}"}],"avty_mode":"all"}`

But it ends up with this name: `Nefit Boiler (Silent mode)`
Somehow Silent mode gets added to each device description. The name is correct though. 

![afbeelding](https://github.com/domoticz/domoticz/assets/73911269/9e134389-39e4-48c7-9ef8-7347637ea849)

**Comment by gizmocuz** [comment]
Could you add a few more number configs here?
It seems correct, the name is a combination from dev->Name and the Name value itself

"name": "Selected flow temperature"
dev-> Name: "Nefit Boiler"

I don't get silent mode with the above config object

**Comment by Tigerstrength** [comment]
Hi Gizmocuz, 

Strange that you don't get the "silent mode" addition om the device name. I'll add all the dicovery messages used to get the specific number devices. As a test I completly removed the MQTT hardware in Domoticz and readded it. Again the names are including the wrong "silent mode" addition. So behaviour is consequent, also with my test Domoticz environment (2024.1 stable and beta 15840)

**Nefit_autodiscovery/number/Nefit/boiler_selflowtemp/config**
`{"uniq_id":"boiler_selected_flow_temperature","obj_id":"boiler_selected_flow_temperature","cmd_t":"Nefit/boiler/selflowtemp","mode":"box","step":1,"min":0,"max":90,"ic":"mdi:coolant-temperature","stat_t":"Nefit/boiler_data","name":"Selected flow temperature","unit_of_meas":"°C","val_tpl":"{{value_json.selflowtemp if value_json.selflowtemp is defined else 0}}","dev":{"ids":["Nefit-boiler"],"name":"Nefit Boiler","mf":"Buderus","mdl":"Enviline/Compress 6000AW/Hybrid 3000-7000iAW/SupraEco/Geo 5xx/WLW196i/WSW196i","via_device":"Nefit"},"avty":[{"t":"Nefit/status","val_tpl":"{{'online' if value == 'online' else 'offline'}}"}]}`

**Nefit_autodiscovery/number/Nefit/boiler_hphystheat/config**
`{"uniq_id":"boiler_on/off_hyst_heat","obj_id":"boiler_on/off_hyst_heat","cmd_t":"Nefit/boiler/hphystheat","mode":"box","step":5,"min":50,"max":1500,"stat_t":"Nefit/boiler_data","name":"On/off hyst heat","unit_of_meas":"K*min","val_tpl":"{{value_json.hphystheat if value_json.hphystheat is defined else 50}}","dev":{"ids":["Nefit-boiler"],"name":"Nefit Boiler"},"avty":[{"t":"Nefit/status","val_tpl":"{{'online' if value == 'online' else 'offline'}}"}]}`

**Nefit_autodiscovery/number/Nefit/boiler_hphystcool/config**
`{"uniq_id":"boiler_on/off_hyst_cool","obj_id":"boiler_on/off_hyst_cool","cmd_t":"Nefit/boiler/hphystcool","mode":"box","step":5,"min":50,"max":1500,"stat_t":"Nefit/boiler_data","name":"On/off hyst cool","unit_of_meas":"K*min","val_tpl":"{{value_json.hphystcool if value_json.hphystcool is defined else 50}}","dev":{"ids":["Nefit-boiler"],"name":"Nefit Boiler"},"avty":[{"t":"Nefit/status","val_tpl":"{{'online' if value == 'online' else 'offline'}}"}]}`

**Nefit_autodiscovery/number/Nefit/boiler_mintempsilent/config**
`{"uniq_id":"boiler_min_outside_temp_for_silent_mode","obj_id":"boiler_min_outside_temp_for_silent_mode","cmd_t":"Nefit/boiler/mintempsilent","mode":"box","step":1,"min":-126,"max":126,"ic":"mdi:coolant-temperature","stat_t":"Nefit/boiler_data","name":"Min outside temp for silent mode","unit_of_meas":"°C","val_tpl":"{{value_json.mintempsilent if value_json.mintempsilent is defined else -126}}","dev":{"ids":["Nefit-boiler"],"name":"Nefit Boiler"},"avty":[{"t":"Nefit/status","val_tpl":"{{'online' if value == 'online' else 'offline'}}"}]}`

**Nefit_autodiscovery/number/Nefit/boiler_tempdiffheat/config**
`{"uniq_id":"boiler_temp_diff_tc3/tc0_heat","obj_id":"boiler_temp_diff_tc3/tc0_heat","cmd_t":"Nefit/boiler/tempdiffheat","mode":"box","step":0.1,"min":2,"max":10,"ic":"mdi:coolant-temperature","stat_t":"Nefit/boiler_data","name":"Temp diff TC3/TC0 heat","unit_of_meas":"K","val_tpl":"{{value_json.tempdiffheat if value_json.tempdiffheat is defined else 2}}","dev":{"ids":["Nefit-boiler"],"name":"Nefit Boiler"},"avty":[{"t":"Nefit/status","val_tpl":"{{'online' if value == 'online' else 'offline'}}"}]}`

**Nefit_autodiscovery/number/Nefit/boiler_tempdiffcool/config**
`{"uniq_id":"boiler_temp_diff_tc3/tc0_cool","obj_id":"boiler_temp_diff_tc3/tc0_cool","cmd_t":"Nefit/boiler/tempdiffcool","mode":"box","step":0.1,"min":2,"max":10,"ic":"mdi:coolant-temperature","stat_t":"Nefit/boiler_data","name":"Temp diff TC3/TC0 cool","unit_of_meas":"K","val_tpl":"{{value_json.tempdiffcool if value_json.tempdiffcool is defined else 2}}","dev":{"ids":["Nefit-boiler"],"name":"Nefit Boiler"},"avty":[{"t":"Nefit/status","val_tpl":"{{'online' if value == 'online' else 'offline'}}"}]}`

**Nefit_autodiscovery/number/Nefit/boiler_wwseltemp/config**
`{"uniq_id":"boiler_dhw_selected_temperature","obj_id":"boiler_dhw_selected_temperature","cmd_t":"Nefit/boiler/wwseltemp","mode":"box","step":1,"min":0,"max":254,"ic":"mdi:coolant-temperature","stat_t":"Nefit/boiler_data_ww","name":"dhw Selected temperature","unit_of_meas":"°C","val_tpl":"{{value_json.wwseltemp if value_json.wwseltemp is defined else 0}}","dev":{"ids":["Nefit-boiler"],"name":"Nefit Boiler"},"avty":[{"t":"Nefit/status","val_tpl":"{{'online' if value == 'online' else 'offline'}}"}]}`

**Nefit_autodiscovery/number/Nefit/thermostat_hc1_seltemp/config**
`{"uniq_id":"thermostat_hc1_selected_room_temperature","obj_id":"thermostat_hc1_selected_room_temperature","cmd_t":"Nefit/thermostat/hc1/seltemp","mode":"box","step":0.5,"min":0,"max":30,"ic":"mdi:coolant-temperature","stat_t":"Nefit/thermostat_data","name":"hc1 Selected room temperature","unit_of_meas":"°C","val_tpl":"{{value_json.hc1.seltemp if value_json.hc1 is defined and value_json.hc1.seltemp is defined else 0}}","dev":{"ids":["Nefit-thermostat"],"name":"Nefit Thermostat"},"avty":[{"t":"Nefit/status","val_tpl":"{{'online' if value == 'online' else 'offline'}}"}]}`

**Comment by gizmocuz** [comment]
Thank you for all the config objects, could you edit your post above and also add the complete topic names, like
homeassistant/xx/yy/{zz}/config

**Comment by Tigerstrength** [comment]
Added the topics to the post above, as requested.

**Comment by gizmocuz** [comment]
Solved in upcoming beta version released later today

![image](https://github.com/domoticz/domoticz/assets/2265299/745936c4-0cde-4002-860c-987352551a02)

**Comment by Tigerstrength** [comment]
Confirmed working now, thanks again for your outstanding work!

**Comment by Tigerstrength** [comment]
Fixed in latest Beta.
