### ISSUE TITLE
After updating (Stable and Beta) ZWave device no longer available

### ISSUE THREAD

**Issue by Shaddyr75** [domoticz/domoticz#5960]
2024.1 build 15801

After updating device for Zwave (Aeotec Zwave USB)  becomes 'unknown'
All zwave devices under domoticz therefor no longer work.

![Zwave Device](https://github.com/domoticz/domoticz/assets/40523947/deafe5bd-eb5e-4901-9c47-d44f7dcf2a58)

Any ideas how to fix are appreciated

**Comment by daserra23** [comment]
This is because Openzwave , which you appear to use, is no longer supported. Your options are roll back to your back up, compile your own Domoticz with Openzwave included or move your Zwave devices to the much better "zwave-js-ui".

Openzwave has been abandoned for 2 or more years.

**Comment by gizmocuz** [comment]
Please use the forum!
