### ISSUE TITLE
2024.1 Domoticz does not reflect 2-gang MQTT switch state

### ISSUE THREAD

**Issue by choyrack** [domoticz/domoticz#5961]
Domoticz version: 2024.1
Device type: MQTT Auto Discovery Client Gateway with LAN interface
Mosquitto version: 2.0.18

Problem description:
Domotocz does not update 2-gang switch state on dashboard for MQTT devices.
When I click device on Domoticz dashboard then MQTT command is sent to MQTT and the switch state is changing from OFF to ON but the state on Domoticz dashboard is showing OFF.
When I click the switch physcaly it send command to MQTT but Domoticz does not reflect this state on it's dashboard.

I tested that with two ZigBee devices:
ZigBee eWeLink ZB-SW02
ZigBee TuYa TS0002

**Comment by choyrack** [comment]
In ZigBee2MQTT all is working fine (swtich state is updated correctly). Before upgrade to 2024.1 it was working in Domoticz fine too.



Domoticz -> MQTT (click switch to power it on)
Topic: zigbee2mqtt/LAZIENKA-TYL/l1/set
Value: ON

Switch state changed to ON but Domoticz still shows OFF.

After a sec Zigbee2MQTT responds:
Topic: zigbee2mqtt/LAZIENKA-TYL
Value: {"last_seen":"2024-01-04T22:24:55+01:00","linkquality":58,"power_on_behavior_l1":"off","state":"OFF","state_l1":"ON","state_l2":"OFF"}

When I click the switch physicaly Zigbee2MQTT send (power switch off):
Topic: zigbee2mqtt/LAZIENKA-TYL
Value: {"last_seen":"2024-01-04T22:27:02+01:00","linkquality":112,"power_on_behavior_l1":"off","state":"OFF","state_l1":"OFF","state_l2":"OFF"}

**Comment by choyrack** [comment]
Seems similar to https://github.com/domoticz/domoticz/issues/5953 but I use another devices.

**Comment by gizmocuz** [comment]
In both your state messages I see OFF not ON?

**Comment by choyrack** [comment]
> In both your state messages I see OFF not ON?

Initial state of the switch is: L1=OFF; L2=OFF (this is 2-gang switch)
When I switch ON L1 in Domoticz it is change left button to ON on the switch and Zigbee2MQTT respond has "state_l1":"ON". But Domoticz still shows it as OFF.
When I push left button on the switch physicaly (after the attempt to turn it on in Domoticz) then Zigbee2MQTT renspnd has "state_l1":"OFF".

It is the same for L2

**Comment by gizmocuz** [comment]
Could you post the config topic+payload of this switch?

**Comment by gizmocuz** [comment]
I need the config object else I cannot debug the issue

But

> When I push left button on the switch physicaly (after the attempt to turn it on in Domoticz) then Zigbee2MQTT renspnd has "state_l1":"OFF".

I assume it looks like "OFF" because you released the button maybe?
If zigbee2mqtt is reporting OFF we can not assume it's ON

**Comment by choyrack** [comment]
What do you mean by "config object"?

Switch state is correctly reflected in Zigbee2MQTT, Domotidcz does not show current state.

**Comment by gizmocuz** [comment]
Please use MQTT Explorer to connect to your MQTT broker.
If configured using the default settings, your MQTT Auto Discovery topic should still be 'homeassistant'
Search the config object of this switch/light, it is something like homeassistant/light/xx/yy/config or homeassistent/switch/xx/yy/config

Please post the complete name (like homeassistant/light/xx/yy/config)
And also the contents of the config object (JSON)

**Comment by choyrack** [comment]
Here you go.

1st switch (eWeLink ZB-SW02)
Topic: `zigbeeauto/switch/0x00124b00226b0143/switch_left/config`
Value: `{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/LAZIENKA/left/set","device":{"identifiers":["zigbee2mqtt_0x00124b00226b0143"],"manufacturer":"eWeLink","model":"Smart light switch/2 gang relay (ZB-SW02)","name":"LAZIENKA","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00124b0014da31c2"},"json_attributes_topic":"zigbee2mqtt/LAZIENKA","name":"Left","object_id":"lazienka_left","origin":{"name":"Zigbee2MQTT","sw":"1.35.0","url":"https://www.zigbee2mqtt.io"},"payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/LAZIENKA","unique_id":"0x00124b00226b0143_switch_left_zigbee2mqtt","value_template":"{{ value_json.state_left }}"}`

Topic: `zigbeeauto/switch/0x00124b00226b0143/switch_right/config`
Value: `{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/LAZIENKA/right/set","device":{"identifiers":["zigbee2mqtt_0x00124b00226b0143"],"manufacturer":"eWeLink","model":"Smart light switch/2 gang relay (ZB-SW02)","name":"LAZIENKA","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00124b0014da31c2"},"json_attributes_topic":"zigbee2mqtt/LAZIENKA","name":"Right","object_id":"lazienka_right","origin":{"name":"Zigbee2MQTT","sw":"1.35.0","url":"https://www.zigbee2mqtt.io"},"payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/LAZIENKA","unique_id":"0x00124b00226b0143_switch_right_zigbee2mqtt","value_template":"{{ value_json.state_right }}"}`

2nd switch (TuYa TS0002):
Topic: `zigbeeauto/switch/0xcc86ecfffebb3f81/switch_l1/config`
Value: `{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/LAZIENKA-TYL/l1/set","device":{"identifiers":["zigbee2mqtt_0xcc86ecfffebb3f81"],"manufacturer":"TuYa","model":"2 gang switch (TS0002)","name":"LAZIENKA-TYL","via_device":"zigbee2mqtt_bridge_0x00124b0014da31c2"},"json_attributes_topic":"zigbee2mqtt/LAZIENKA-TYL","name":"L1","object_id":"lazienka-tyl_l1","origin":{"name":"Zigbee2MQTT","sw":"1.35.0","url":"https://www.zigbee2mqtt.io"},"payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/LAZIENKA-TYL","unique_id":"0xcc86ecfffebb3f81_switch_l1_zigbee2mqtt","value_template":"{{ value_json.state_l1 }}"}`

Topis: `zigbeeauto/switch/0xcc86ecfffebb3f81/switch_l2/config`
Value: `{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/LAZIENKA-TYL/l2/set","device":{"identifiers":["zigbee2mqtt_0xcc86ecfffebb3f81"],"manufacturer":"TuYa","model":"2 gang switch (TS0002)","name":"LAZIENKA-TYL","via_device":"zigbee2mqtt_bridge_0x00124b0014da31c2"},"json_attributes_topic":"zigbee2mqtt/LAZIENKA-TYL","name":"L2","object_id":"lazienka-tyl_l2","origin":{"name":"Zigbee2MQTT","sw":"1.35.0","url":"https://www.zigbee2mqtt.io"},"payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/LAZIENKA-TYL","unique_id":"0xcc86ecfffebb3f81_switch_l2_zigbee2mqtt","value_template":"{{ value_json.state_l2 }}"}`

**Comment by gizmocuz** [comment]
Found the reason this is happening.
It's because the status object also contains a "state" field which is set to OFF
I think I found a way to ignore this, but do you know what this field represents? Or why it is here?

**Comment by gizmocuz** [comment]
Please check beta 15817 to see if this solves your issue... And if possible also check other switches/binary sensors as well...

**Comment by choyrack** [comment]
> Found the reason this is happening. It's because the status object also contains a "state" field which is set to OFF I think I found a way to ignore this, but do you know what this field represents? Or why it is here?

When I change "state" it chagne state_l1 too.
topis: zigbee2mqtt/LAZIENKA-TYL/set
value: on

`{"last_seen":"2024-01-09T17:12:02+01:00","linkquality":116,"power_on_behavior_l1":"off","state":"ON","state_l1":"ON","state_l2":"OFF"}
`
Then "state" and "state_l1" change to "on" and Domoticz shows both buttons (l1 and l2) as "on".

I don't know what is the usage of "state", based on the information [here](https://www.zigbee2mqtt.io/devices/TS0002.html) it can be timed off control.

**Comment by gizmocuz** [comment]
Is it working with the beta?

**Comment by choyrack** [comment]
> Is it working with the beta?

It works now. Thank you.
All other switches that I use also work. I will look that in the few incomming days and will let you know once something is wrong.

**Comment by gizmocuz** [comment]
Thank you for testing!
We might received an issue with this patch here, but let's see if that is the case

https://github.com/domoticz/domoticz/issues/5971

**Comment by dave21w** [comment]
This beta update has also fixed the issue with my Aqara H1 switches not correctly responding as well - many thanks.
