### ISSUE TITLE
2024.1 Removed Rpi Clock Speed (info not on release doc)

### ISSUE THREAD

**Issue by IW2FAG-11** [domoticz/domoticz#5963]
Thanking first of all for the good work observed so far, I am here to ask why features are being taken away.
In particular i am referring to the clock speeds of the Rpi's.
I have been collecting them for years to monitor the progress of activities.
I have seen that they have been purposely removed from MB devices.
HardwareMonitor.h and HardwareMonitor.cpp now no longer contain the data collection.
At the moment the rest in my deployment is all working, I have not noticed any problems whatsoever.
Device, script and bgbot (Telegramm mangment) still ok.

Thanks for info.

**Comment by gizmocuz** [comment]
This is done on purpose.
There is no use monitoring them as well as the v3d speed.
I am quite certain that you don't look at them... I added them 'years' ago as it was fun.
This is also mentioned on the forum.
You can write a bash script to read-out these values and push them into Domoticz if you like

**Comment by IW2FAG-11** [comment]
Yes, for me they are activity monitors so I can always tell if there is something wrong, since my system is enclosed in a box on a din rail and ventilated to keep the LiIoN battery contained for backup from getting too hot.
Instead of collecting from the panel I will collect from the monitor script and write to the panel.
Thanks for the info, I hadn't noticed anything on the forum.

Mark solved thank you.

**Comment by gizmocuz** [comment]
Temperature is working, CPU speed is working.. why do you need a almost fixed clock speed? This is not telling you anything about the stress of the system?

**Comment by akamming** [comment]
i also just noticed them gone indeed. I was the one who made the original PR to include them. My use case it that clock speed is just not enough to see if you system is running OK. If the pi is throttling, you will see a high cpu load on low clock speed...

alternative would be to add a sensor to detect throttling...

**Comment by gizmocuz** [comment]
When CPU usage is to high, the CPU is probably throttled.
You can set a alarm if this happens (if CPU > xx% then yy)

**Comment by IW2FAG-11** [comment]
Thanks.
I'd just do something like that.



Il giorno ven 12 gen 2024 alle 10:50 gizmocuz ***@***.***> ha
scritto:

**Comment by akamming** [comment]
Throttling Only happens if there is not enough cooling.  So then the warming would Only need to take place when clock speed is low

anyway not a very important use case. Just wanted to mention that it was not just fun. There is a reason to monitor this (although actually measuring if the system is throttled would be better)…

**Comment by gizmocuz** [comment]
Indeed, so better perform this check with the temperature.
Anyway, enough options to check if the system is still health

**Comment by akamming** [comment]
for anyone in here who misses the clock speed sensors (like me): I reimplemented them in a [python plugin](https://github.com/akamming/Domoticz_pi_Clockspeeds_Plugin)

and in the process i also added checking the throttlingbits (which was actually the main reason why i wanted to monitor the clock speed) to see if the pi is still healthy
