### ISSUE TITLE
Python plugin unable to create new units (devices) in 2024.1 because of OrgHardwareID field in DeviceStatus table cannot be NULL

### ISSUE THREAD

**Issue by d-EScape** [domoticz/domoticz#5964]
Looking at the source it seems that the python plugin framework does not supply a value for OrgHardwareID, but the field cannot be NULL in a database created by version 2024.1. I am able to create devices in an older database that has been migrates to 2024.1 because that does not have the NOTNULL flag set for this field.

Here's an example of the error in the log:
```
2024-01-05 12:17:58.159 Error: SQL Query("INSERT INTO DeviceStatus (HardwareID, DeviceID, Unit, Type, SubType, SwitchType, Used, SignalLevel, BatteryLevel, Name, nValue, sValue, CustomImage, Description, Color, Options, LastUpdate) VALUES (3,'deviceA',1,244,73,0,1,12,255,'First Device',0,'',0,'','','','2024-01-05 12:17:58')") : NOT NULL constraint failed: DeviceStatus.OrgHardwareID
```

Neither the legacy (Domoticz) nor the extended (DomoticzEx) has included OrgHardwareID in the sql insert statements. Example from PythonObjectEx.cpp below.

```
						m_sql.safe_query("INSERT INTO DeviceStatus "
							"(HardwareID, DeviceID, Unit, Type, SubType, SwitchType, Used, SignalLevel, BatteryLevel, Name, nValue, sValue, CustomImage, Description, Color, Options, LastUpdate) "
							"VALUES (%d,'%q',%d,%d,%d,%d,%d,%d,%d,'%q',%d,'%q',%d,'%q','%q','%q','%q')",
							pModState->pPlugin->m_HwdID,
							sDeviceID.c_str(),
							self->Unit,
							self->Type,
							self->SubType,
							self->SwitchType,
							self->Used,
							self->SignalLevel,
							self->BatteryLevel,
							sName.c_str(),
							self->nValue,
							sValue.c_str(),
							self->Image,
							sDescription.c_str(),
							sColor.c_str(),
							sOptionValue.c_str(),
							TimeToString(nullptr, TF_DateTime).c_str());
```

**Comment by gizmocuz** [comment]
Okey, but it is set default to 0, what is the problem?

**Comment by gizmocuz** [comment]
Ahh ... Yes it should have been default 0

**Comment by gizmocuz** [comment]
Fixed in latest beta commit, new beta's are coming soon

**Comment by d-EScape** [comment]
You found it quicker than I could reply with the tables schema ;-) Thanks!

**Comment by gizmocuz** [comment]
But it was a big mistake to make it NOT NULL .... should have been 0... 
And while testing I did not add new hardware, so it was overseen... 
Hope all works now!
