### ISSUE TITLE
Remove 'update button' from the update notification.

### ISSUE THREAD

**Issue by Xenomes** [domoticz/domoticz#5965]
Hi,

Due to the recent events, in order to protect users from accidental updates or those who might forget to backup, it might be wise to remove 'update' from the update notification. This way, updates would always need to be performed through the CLI interface, and the new update release script will automatically create a backup.

Just a thought,

Xenomes

**Comment by gizmocuz** [comment]
Is that for a reason

**Comment by gizmocuz** [comment]
Disable updates on the settings and it’s gone

**Comment by Xenomes** [comment]
Yes, that is true. It was an idea to protect you guys from a load of commits when an update is released. But I understand, you can't protect them all! 🤣

**Comment by gizmocuz** [comment]
Most people do not know how to update via SSH... 
Even so, if they know there is a update, they will still issue the update command without reading the notes
