### ISSUE TITLE
Error when building domoticz from source if openzwave is not present

### ISSUE THREAD

**Issue by mealgi** [domoticz/domoticz#5966]
Hello

1 - Context:
Hardware : RPI3B+
Version: 2024.1 (build 15801)
Build Hash: 4d18f2dbf
Compile Date: 2024-01-03 12:12:37
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]

Openzwave is not installed as I switched successfully from OZW to ZWaveJS2MQTT  when installing domoticz version 2023.2 Beta with better performance.

2 - Issue

When building domoticz version 2024.1 from source I get the following error when compiling zwavebase.cpp:

/home/pi/TEST/dev-domoticz/hardware/ZWaveBase.cpp: In member function ‘void ZWaveBase::SendDevice2Domoticz(ZWaveBase::_tZWaveDevice*)’:
/home/pi/TEST/dev-domoticz/hardware/ZWaveBase.cpp:751:21: error: ‘sTypeZWaveThermostatMode’ was not declared in this scope
  751 |   gDevice.subtype = sTypeZWaveThermostatMode;
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/TEST/dev-domoticz/hardware/ZWaveBase.cpp:760:21: error: ‘sTypeZWaveThermostatFanMode’ was not declared in this scope; did you mean ‘SetThermostatFanMode’?
  760 |   gDevice.subtype = sTypeZWaveThermostatFanMode;
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     SetThermostatFanMode
/home/pi/TEST/dev-domoticz/hardware/ZWaveBase.cpp:769:21: error: ‘sTypeZWaveThermostatOperatingState’ was not declared in this scope
  769 |   gDevice.subtype = sTypeZWaveThermostatOperatingState;
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/TEST/dev-domoticz/hardware/ZWaveBase.cpp:778:21: error: ‘sTypeZWaveAlarm’ was not declared in this scope; did you mean ‘sTypeWaveman’?
  778 |   gDevice.subtype = sTypeZWaveAlarm;
      |                     ^~~~~~~~~~~~~~~
      |                     sTypeWaveman
/home/pi/TEST/dev-domoticz/hardware/ZWaveBase.cpp: In member function ‘virtual bool ZWaveBase::WriteToHardware(const char*, unsigned char)’:
/home/pi/TEST/dev-domoticz/hardware/ZWaveBase.cpp:916:50: error: ‘sTypeZWaveThermostatMode’ was not declared in this scope
  916 |  if ((packettype == pTypeGeneral) && (subtype == sTypeZWaveThermostatMode))
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/TEST/dev-domoticz/hardware/ZWaveBase.cpp:938:50: error: ‘sTypeZWaveThermostatFanMode’ was not declared in this scope; did you mean ‘SetThermostatFanMode’?
  938 |  if ((packettype == pTypeGeneral) && (subtype == sTypeZWaveThermostatFanMode))
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  SetThermostatFanMode
make[2]: *** [CMakeFiles/domoticz.dir/build.make:3389 : CMakeFiles/domoticz.dir/hardware/ZWaveBase.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:384 : CMakeFiles/domoticz.dir/all] Erreur 2
make: *** [Makefile:156 : all] Erreur 2

**Comment by gizmocuz** [comment]
The master branch (2024.1) does not have any ZWave/OpenZWave code
To build from the master branch, also make sure you remove any openzwave traces from your system (also delete it's folder)

I think you are trying to compile the development branch?
I just made a commit skip all zwave code if openzwave is not found..

This should compile now...

**Comment by mealgi** [comment]
Many thanks
BR
