### ISSUE TITLE
Philio PAT02-B report incorrect temperature after ZWAVE JS UI migration

### ISSUE THREAD

**Issue by akamming** [domoticz/domoticz#5967]
Hi,

i noticed that after ZWAVE JS UI migration my 3 PAT02-B (temphum) sensors reported a too high temperature:

![image](https://github.com/domoticz/domoticz/assets/30364409/ca94ecc7-f155-469f-9ea4-fb0e71cc0eae)
(migration was done on Jan 4th). 

Cause is that ZWAVE JS UI reports the temperature of these devices now in Fahrenheit, but domoticz interprets as Celcius:

Here's the discovery message (note the unit_of_measurement tag):
`{"value_template":"{{ value_json.value }}","unit_of_measurement":"°F","state_class":"measurement","device_class":"temperature","state_topic":"zwave/Garage/Temphum/49/0/Air_temperature","json_attributes_topic":"zwave/Garage/Temphum/49/0/Air_temperature","device":{"identifiers":["zwavejs2mqtt_0xec017be9_node85"],"manufacturer":"Philio Technology Corp","model":"Z-Wave Room Sensor (PAT02-B)","name":"Garage-Temphum","sw_version":"1.14"},"name":"Garage-Temphum_temperature_air","unique_id":"zwavejs2mqtt_0xec017be9_85-49-0-Air_temperature"}
`

And here is a sample message in the state topic ("zwave/Garage/Temphum/49/0/Air_temperature" in this example)
```
{
  "time": 1704530508210,
  "value": 63.1
}

```
Expected behaviour for me would be that if domoticz is set to Celcius, but the sensor reports in fahrenheit that domoticz would convert the fahrenheit to celcius.. (just like openzwave apparently did...)

**Comment by akamming** [comment]
Might be related to https://github.com/domoticz/domoticz/issues/5956

**Comment by gizmocuz** [comment]
Thanks for reporting! Yes, I think it's the same issue.
Solved in beta 15810

**Comment by akamming** [comment]
tx!!!

just updated, it looks fixed (but need some more time to confirm. i need to wait for
- the sensors to send new values
- then force rediscovery
- and then wait for another update of value of the temp sensor

**Comment by akamming** [comment]
Yes! Fixed indeed. Tx a lot!
