### ISSUE TITLE
Error when building domoticz from source if openzwave is not present - TCPServer.cpp compilation error

### ISSUE THREAD

**Issue by mealgi** [domoticz/domoticz#5968]
Hello

1 - Context:
Hardware : RPI3B+
Version: 2024.1 (build 15807)
Build Hash: 70f3a48eb
Compile Date: 2024-01-06 09:30:33
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]

Openzwave is not installed as I switched successfully from OZW to ZWaveJS2MQTT when installing domoticz version 2023.2 Beta with better performance.

2 - Issue

When building domoticz version 2024.1 from source I get the following error when compiling tcpserver.cpp

/home/pi/DEV20231220/dev-domoticz/tcpserver/TCPServer.cpp: In member function ‘void tcp::server::CTCPServer::DoDecodeMessage(const tcp::server::CTCPClientBase*, const uint8_t*, size_t)’:
/home/pi/DEV20231220/dev-domoticz/tcpserver/TCPServer.cpp:446:18: error: ‘class MainWorker’ has no member named ‘SetZWaveThermostatMode’
  446 |     m_mainworker.SetZWaveThermostatMode(szIdx, tMode);
      |                  ^~~~~~~~~~~~~~~~~~~~~~
/home/pi/DEV20231220/dev-domoticz/tcpserver/TCPServer.cpp:451:18: error: ‘class MainWorker’ has no member named ‘SetZWaveThermostatFanMode’
  451 |     m_mainworker.SetZWaveThermostatFanMode(szIdx, fMode);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/domoticz.dir/build.make:3789 : CMakeFiles/domoticz.dir/tcpserver/TCPServer.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:384 : CMakeFiles/domoticz.dir/all] Erreur 2
make: *** [Makefile:156 : all] Erreur 2

**Comment by aldodemi** [comment]
Same here:
Hardware: Intel i3
OS: Ubuntu 23.10 (Mantic Minotaur)
Last build: Domoticz 2024.1 (build 15801)

/home/domoticz/domoticz/tcpserver/TCPServer.cpp: In member function ‘void tcp::server::CTCPServer::DoDecodeMessage(const tcp::server::CTCPClientBase*, const uint8_t*, size_t)’:
/home/domoticz/domoticz/tcpserver/TCPServer.cpp:446:46: error: ‘class MainWorker’ has no member named ‘SetZWaveThermostatMode’
  446 |                                 m_mainworker.SetZWaveThermostatMode(szIdx, tMode);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~
/home/domoticz/domoticz/tcpserver/TCPServer.cpp:451:46: error: ‘class MainWorker’ has no member named ‘SetZWaveThermostatFanMode’
  451 |                                 m_mainworker.SetZWaveThermostatFanMode(szIdx, fMode);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/domoticz.dir/build.make:3789: CMakeFiles/domoticz.dir/tcpserver/TCPServer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:384: CMakeFiles/domoticz.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by gizmocuz** [comment]
Thanks for reporting! Solved in latest code commit
