### ISSUE TITLE
[2024-beta.15817] Problem with MQTT-AD devices

### ISSUE THREAD

**Issue by MuadDibVV** [domoticz/domoticz#5971]
Hello,

  On beta 15817 I have a problem with MQTT-AD devices (ZwaveJSUI in my case).
Dimmer never returns to off position but to an unstable 0% position.

I detect other strange behavior, but I reverted to [2024-beta.15810] and all my problems disappear.

**Comment by gizmocuz** [comment]
Thanks for reporting.

Could you please follow this wiki page and report back here the results?

**Comment by gizmocuz** [comment]
https://www.domoticz.com/wiki/MQTT_AD_Report_Problems

**Comment by Filnet53** [comment]
Hello, same problem here with 15817.

**Comment by MuadDibVV** [comment]
@gizmocuz I need to configure a new test environment in order to compare 15810 and 15817 in MQTT => I will try to do that next WE.

**Comment by xvisor16** [comment]
Same problem here! 15810 no problems, 15817 problems. All my Zwave (MQTT-AD) dimmers won't function as expected. LUA scripts don't work anymore because they think the lights are on even after turning them off and the other way around. Pushing on/off switch in domoticz doesn't work anymore. Only way of using my dimmers is by clicking a percentage. Other switches and RGB lights do seem to work as expected.

**Comment by Filnet53** [comment]
if I can help, I notice so than informations send to Homebridge are false.

**Comment by gizmocuz** [comment]
Please follow this wiki and post the requested information here:

https://www.domoticz.com/wiki/MQTT_AD_Report_Problems

**Comment by gizmocuz** [comment]
Okey, I tested a dimmer (RGBW) and this works correctly.
Turning on/off setting the level, all works correctly.

If no further details are received here (see above link), I am going to assume all is fine and will close this issue

**Comment by xvisor16** [comment]
Problems still exist in the latest beta. Tomorrow I will get you the requested info!

Op 12 jan 2024 16:15, om 16:15, gizmocuz ***@***.***> schreef:

**Comment by gizmocuz** [comment]
Great thanks! I would like to make a new stable asap...

**Comment by Filnet53** [comment]
I confirm: probleme still exist.
The button is always on. When you press the button, it stays on. The MQTT message for Homebridge is always ON and stays ON.

**Comment by gizmocuz** [comment]
@Filnet53 , I don't know anything about homebridge. If you operate from Domoticz is all working correctly?

**Comment by gizmocuz** [comment]
(I don't mind setting up homebridge, but I need to replicate this issue to be able to see what is going wrong)

**Comment by Filnet53** [comment]
It's the domoticz command that doesn't work. Particularly, the button. The slider works well. The button remains permanently lit and is inoperative and domoticz sends false MQTT information (always On).

**Comment by gizmocuz** [comment]
The recent change is at the 'reception' state... not the sending. It could be that the reception of the new state is not correct for your device, but the sending part has not changed and should still be correct. So setting the switch to ON of Off should still work

For my RGBW dimmer when clicking the On/Off button works correctly from the popup

**Comment by Filnet53** [comment]
Since 15817, If I press the button, the pop-up says "Commutation Off" but the button does not turn off.
If I put the slider on 0%, the button is Off. If I press the button, the pop-up says "Commutation ON" but the button stays off

**Comment by gizmocuz** [comment]
Okey, let's wait for the requested information, without this it is impossible to debug the issue

**Comment by MuadDibVV** [comment]
I tested two instance connected on the same time on MQTT AD (ZWAVEJSUI).
One 15817
One 15810

Switch On : (same MQTT message from 15810 or 15817)
![image](https://github.com/domoticz/domoticz/assets/62676693/5e6c720f-c4fc-46da-8a06-6b0b6085779f)

All is ok, both devices switch to "On" 100%

When switching off from 15810 :
![image](https://github.com/domoticz/domoticz/assets/62676693/08e97ace-4b72-40a5-862d-a15099e76e2a)

On 15810 :
![image](https://github.com/domoticz/domoticz/assets/62676693/7f6986e2-f6bd-4962-b1db-402d421c424f)

On 15817 : 
![image](https://github.com/domoticz/domoticz/assets/62676693/015d7aed-be96-453f-b738-5aa676ac4cac)

I wanted to test Switching off from 15817, but I realised that after the first time I switch off from the 15810 the devices stayed on this unstable 0% state even after beginning the device from 15810 or manually...

**Comment by MuadDibVV** [comment]
Config :

{
  "command_topic": "zwave/63/38/1/targetValue/set",
  "state_topic": "zwave/63/38/1/currentValue",
  "state_value_template": "{{ \"OFF\" if value_json.value == 0 else \"ON\" }}",
  "brightness_command_topic": "zwave/63/38/1/targetValue/set",
  "brightness_scale": 99,
  "brightness_state_topic": "zwave/63/38/1/currentValue",
  "brightness_value_template": "{{ value_json.value }}",
  "on_command_type": "brightness",
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xdf041442_node63"
    ],
    "manufacturer": "Fibargroup",
    "model": "Dimmer 2 (FGD212)",
    "name": "LampeCuisine",
    "sw_version": "3.5"
  },
  "name": "LampeCuisine_dimmer_1",
  "unique_id": "zwavejs2mqtt_0xdf041442_63-38-1-currentValue"
}

**Comment by gizmocuz** [comment]
@MuadDibVV , thank you for the config payload.
It would help if the topic was also copy/pasted as I now have to manually type one.
The two state values in your previous post where also nice to have textual (payload) together with the complete topic name

Please let me know if I have to adjust the wiki page to make things more clearer for feature users

**Comment by gizmocuz** [comment]
When setting the command (on/off) via ZWaveJS-UI or Domoticz, the value is posted here

zwave/63/38/1/targetValue/set

could you post some payloads from this as well when you switch On/Off from ZWaveJS-UI

Is there a difference when switching from Domoticz?

The result (current state) is read here:

zwave/63/38/1/currentValue

Setting the brightness need to be done on 

zwave/63/38/1/targetValue/set

Could you post what is send here when you operate via ZWaveJS the on/off/brightness

I think I found something in the code that does not seem right 100%

**Comment by gizmocuz** [comment]
I wonder when switching on/off it sends On/Off to

zwave/63/38/1/targetValue/set

For example
zwave/63/38/1/targetValue
set=ON

And when setting the dimmer to 50% it sends
zwave/63/38/1/targetValue
set=50

or that is send

zwave/63/38/1/targetValue/set
value=50

or

value=OFF

or

zwave/63/38/1/targetValue/set
{ "value": 50 }

**Comment by arjanvanleent** [comment]
My 0-10Volt dimmer is also not working correct

My config is:
{
  "type": "switch",
  "object_id": "switch",
  "discovery_payload": {
    "payload_off": false,
    "payload_on": true,
    "value_template": "{{ value_json.value }}",
    "command_topic": "zwave/Ventilator/37/0/targetValue/set",
    "state_topic": "zwave/Ventilator/37/0/currentValue",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xcabcf262_node5"
      ],
      "manufacturer": "Qubino",
      "model": "Flush Dimmer 0-10V (ZMNHVD)",
      "name": "Ventilator",
      "sw_version": "2.4"
    },
    "name": "Ventilator_switch",
    "unique_id": "zwavejs2mqtt_0xcabcf262_5-37-0-currentValue"
  },
  "discoveryTopic": "switch/Ventilator/switch/config",
  "values": [
    "37-0-currentValue",
    "37-0-targetValue"
  ],
  "persistent": true,
  "ignoreDiscovery": false,
  "id": "switch_switch"
}

**Comment by arjanvanleent** [comment]
Maybe this will help
![image](https://github.com/domoticz/domoticz/assets/17556892/5454e376-9672-4cda-923c-117e358de4b7)

I only use 38 and set it to 0 for off and 1-99 for on
Never use the switch 37 to turn off

Also Domoticz is not showing the current state
![image](https://github.com/domoticz/domoticz/assets/17556892/a2c014b0-3833-4d3d-af04-e4769096a6c0)
![image](https://github.com/domoticz/domoticz/assets/17556892/432390bd-35f0-431f-8b60-33bdce2fd26e)

**Comment by gizmocuz** [comment]
With MQTT-AD we have default payloads for ON/OFF (ON and OFF) unless overruled in the config object (payload_on and payload_off fields)

In the config object from @MuadDibVV , this is not defined, but there is an additional field "on_command_type"

In the config from @arjanvanleent , the payload for on = true and off = false (as defined in the config object)

@arjanvanleent , is this config object taken from the auto discovery topic with MQTT Explorer?

**Comment by gizmocuz** [comment]
Anyway, I would like to also see the information requested below (what is send and received with topic names and state payloads)
Hope to sort this soon

**Comment by xvisor16** [comment]
Hi @gizmocuz ,
Here is one of my lights that's not working correctly:

It's a Fibaro Dimmer which also has an endpoint_2 btw, don't know if you need info about that too? The switch I control in domoticz is the endpoint_1 as far as I know.

{
"command_topic":"zwavejs/Lampen_Woonkamer/switch_multilevel/endpoint_1/targetValue/set",
"state_topic":"zwavejs/Lampen_Woonkamer/switch_multilevel/endpoint_1/currentValue",
"state_value_template":"{{ \"OFF\" if value_json.value == 0 else \"ON\" }}",
"brightness_command_topic":"zwavejs/Lampen_Woonkamer/switch_multilevel/endpoint_1/targetValue/set",
"brightness_scale":99,
"brightness_state_topic":"zwavejs/Lampen_Woonkamer/switch_multilevel/endpoint_1/currentValue",
"brightness_value_template":"{{ value_json.value }}",
"on_command_type":"brightness",
"device":
    {
    "identifiers":["zwavejs2mqtt_0xdcbf687d_node3"],
    "manufacturer":"Fibargroup",
    "model":"Dimmer 2 (FGD212)",
    "name":"Lampen Woonkamer",
    "sw_version":"3.5"
    },
"name":"Lampen Woonkamer_dimmer_1",
"unique_id":"zwavejs2mqtt_0xdcbf687d_3-38-1-currentValue"
}

zwavejs/Lampen_Woonkamer/switch_multilevel/endpoint_1/currentValue:
{"time":1705146293823,"value":0,"nodeName":"Lampen Woonkamer","nodeLocation":""}
zwavejs/Lampen_Woonkamer/switch_multilevel/endpoint_1/On:
{"time":1705047397702,"value":false,"nodeName":"Lampen Woonkamer","nodeLocation":""}
zwavejs/Lampen_Woonkamer/switch_multilevel/endpoint_1/Off:
{"time":1705047397703,"value":true,"nodeName":"Lampen Woonkamer","nodeLocation":""}
zwavejs/Lampen_Woonkamer/switch_multilevel/endpoint_1/targetValue:
{"time":1705146293741,"value":0,"nodeName":"Lampen Woonkamer","nodeLocation":""}
zwavejs/Lampen_Woonkamer/switch_multilevel/endpoint_1/duration:
{"time":1705047397704,"value":{"unit":"seconds"},"nodeName":"Lampen Woonkamer","nodeLocation":""}
zwavejs/Lampen_Woonkamer/switch_multilevel/endpoint_1/restorePrevious:
{"time":1705047397704,"nodeName":"Lampen Woonkamer","nodeLocation":""}

Photo of light which is turned of a just before, domoticz still shows On but percentage went to 0. Also the timestamp doesn't change after switching!:
![issue domoticz](https://github.com/domoticz/domoticz/assets/12544669/98f163d1-cad3-4241-b733-6e7d7f6b8ca8)

Video of what happens with the actual light in the image. So the light reacts to being turned off but domoticz does not reflect that! Eventually after an MQTT update the percentage does go down to 0 like in the picture above but domoticz doesn't update the timestamp nor the power state:
https://github.com/domoticz/domoticz/assets/12544669/28144ced-57be-419f-91c2-b64b49d2a3fd

This is what history on currentValue tells me after turning it to 45% and off again.
Before turning on again + the turning on (2 messages):
![image](https://github.com/domoticz/domoticz/assets/12544669/da5f9c6b-c8cd-4524-b702-2aa68cf3153f)
After turning off again (2 messages):
![image](https://github.com/domoticz/domoticz/assets/12544669/23eaa1ab-a9d9-4860-ba7f-307a6d44caad)

Values on the targetValue/set:
![image](https://github.com/domoticz/domoticz/assets/12544669/14c01fc4-e06c-459b-a415-302b12a1c9b0)

Hope this is enough, please let me know if you need more?

**Comment by gizmocuz** [comment]
@xvisor16 , thank you for all the info!!! 
Just a question, when using ZWaveJS-UI and you turn OFF the light, it sends "value": 0 to targetValue/set correct?
And when pressing ON, does it send the last known dimmer value?

Could you send to 'targetValue/set'

{ "value": 10 }

It should turn to 10%

{ "value": 80 }

It should turn to 80%

{ "value": 0 }

It should turn off the lights

**Comment by xvisor16** [comment]
@gizmocuz ,

If I publish 20 (10 is not enough for the lights to turn on) with MQTT Explorer to targetValue/set it turns it to 20%, with 80 to 80% and with 0 it turns off. But domoticz does not reflect any of these things!
See here:
![image](https://github.com/domoticz/domoticz/assets/12544669/5daed607-e247-4888-a375-97907b2a6dcf)

![image](https://github.com/domoticz/domoticz/assets/12544669/fa7d1807-7202-4047-9c3a-9ccf4c769e56)

![image](https://github.com/domoticz/domoticz/assets/12544669/56d3848c-3461-47ae-9bf4-300adb5f5be1)

So the lights work fine, it's just that domoticz doesn't receive back the status updates anymore...

**Comment by xvisor16** [comment]
Ow and to add to that, if I drag the bar to 0%, domoticz displays it as off:
![image](https://github.com/domoticz/domoticz/assets/12544669/728aa065-c64f-43c6-a36b-2e2924eb4729)

But if I refresh the page they show like this again:
![image](https://github.com/domoticz/domoticz/assets/12544669/c45017ac-4bd3-468e-8b9e-2de68980b743)

Scripts also keep thinking the lights are on.

And to add another thing if I set any percentage in Domoticz the target gets a value that's 1 lower. So if I set 74 percent in Domoticz, domoticz sends a targetValue of 73... This is only the case when setting the dimmer to 51 percent or higher... so when setting it to 100% in Domoticz it only sends out 99 to MQTT... but when sending anyting from 0-50 is sends out the correct value.

**Comment by arjanvanleent** [comment]
The config I showed is from Zwave-JS. This config is used for Homeassistant.
From Mtqq-explore:
{"command_topic":"zwave/Ventilator/38/0/targetValue/set","state_topic":"zwave/Ventilator/38/0/currentValue","state_value_template":"{{ \"OFF\" if value_json.value == 0 else \"ON\" }}","brightness_command_topic":"zwave/Ventilator/38/0/targetValue/set","brightness_scale":99,"brightness_state_topic":"zwave/Ventilator/38/0/currentValue","brightness_value_template":"{{ value_json.value }}","on_command_type":"brightness","device":{"identifiers":["zwavejs2mqtt_0xcabcf262_node5"],"manufacturer":"Qubino","model":"Flush Dimmer 0-10V (ZMNHVD)","name":"Ventilator","sw_version":"2.4"},"name":"Ventilator_dimmer","unique_id":"zwavejs2mqtt_0xcabcf262_5-38-0-currentValue"}

From MTTQ expplore the zwave topics:
![image](https://github.com/domoticz/domoticz/assets/17556892/e8835e5c-69c6-4dd7-b390-c8881c5e654c)

**Comment by arjanvanleent** [comment]
Payload for the switch from MQTT explore
{"payload_off":false,"payload_on":true,"value_template":"{{ value_json.value }}","command_topic":"zwave/Ventilator/37/0/targetValue/set","state_topic":"zwave/Ventilator/37/0/currentValue","device":{"identifiers":["zwavejs2mqtt_0xcabcf262_node5"],"manufacturer":"Qubino","model":"Flush Dimmer 0-10V (ZMNHVD)","name":"Ventilator","sw_version":"2.4"},"name":"Ventilator_switch","unique_id":"zwavejs2mqtt_0xcabcf262_5-37-0-currentValue"}

**Comment by gizmocuz** [comment]
Thanks everyone, think I found the issue.

Is it possible to try beta 15836 ?

The issue was related to the state_value_template ... I'm still going to look into this a bit more...
Seems ZWaveJS-UI handles dimmers differently then Zigbee2MQTT

There is also a line in the code that basically says when sending a brightness value, do not use the 'value' key but just send the value as is.

For example (maybe someone could test this), sending

```
zwave/63/38/1/targetValue/set
{ "value": 40 }
```
if the same as

```
zwave/63/38/1/targetValue/set
40
```

But since the **brightness_value_template** equals "{{ value_json.value }}", I would say we should use the first option.

**Comment by xvisor16** [comment]
@gizmocuz 
Sending { "value": 40 } to set doesn't work! Sending just 40 works perfectly.
Just updated to 15836. This fixed it for me!!

**Comment by gizmocuz** [comment]
Thanks for the feedback! And yahooo ! 😂😎

**Comment by xvisor16** [comment]
BTW as a bonus I can also confirm what happens when sending the different styles to targetValue/set:
Zigbee2MQTT:
Sending { value: value }: Works
Sending just the value: Does not work

ZwaveJS UI MQTT:
Sending { value: value }: Does not work
Sending just the value: Works

Ow and one small other question, is this supposed to be like this?:

And to add another thing if I set any percentage in Domoticz the target gets a value that's 1 lower. So if I set 74 percent in Domoticz, domoticz sends a targetValue of 73... This is only the case when setting the dimmer to 51 percent or higher... so when setting it to 100% in Domoticz it only sends out 99 to MQTT... but when sending anyting from 0-50 is sends out the correct value. It seems to me like somewhere a scale of 101 is used where somewhere else in the code a scale of 100 is used.

Or should I create a new issue for this?

**Comment by gizmocuz** [comment]
I guess it's just the difference between the two platforms

The reason why it is 'sometimes' 1 less, is because Domoticz works with 0-100 and zwave from 0-99. so internally we convert to 99
Some switches that use MQTT-AD (ESP or other platforms) have 0-15, here we convert 0-100 to 0-15

**Comment by Filnet53** [comment]
All is OK for me.
Thank you to gizmocuz and to the others guys who speaks english better than me.

**Comment by arjanvanleent** [comment]
Top it's working correct now

**Comment by MuadDibVV** [comment]
Yes, perfect, Thank you
