### ISSUE TITLE
Invalid data received! 

### ISSUE THREAD

**Issue by ilkaskim** [domoticz/domoticz#5972]
Hello, I wrote somewhere else that I get an error message on the Master domoticz installation with Werkstatt: Invalid data received!  If the "starting automatic database backup procedure" begins on the slave, the master installation does not respond until the procedure on the slave is finished. This happens every hour and the error message appears every time.

Have a nice evening

**Comment by gizmocuz** [comment]
@ilkaskim , Did you install the same (beta) version on both master/client?
I don't advise to use the automatic database backup, when needed (like once in a month or so), just go to settings and select backup database.
I run Domoticz (as first user) for a long time now, and don't use this

**Comment by ilkaskim** [comment]
Hello, I have installed the current beta on both.
Yesterday I deactivated the automatic backup function.  I have a total of 3x domoticz in different locations and make automatic backups to my nas server and sometimes access them.  

What bothers me, however, is the error message Invalid data received.  How can I search for this more precisely?  

Thank you for the feedback and have a nice day.

**Comment by gizmocuz** [comment]
You can download the source code and search in the source folder
You still receive this when all instances are on the latest beta?

**Comment by ilkaskim** [comment]
Both have the same beta installed. 
![Screenshot_20240111_163646_Chrome.jpg](https://github.com/domoticz/domoticz/assets/16821599/965bf1e3-9e85-4057-a1ac-20cab4633806)

The error message does not change. It's always the same. ![Screenshot_20240111_163629_Chrome.jpg](https://github.com/domoticz/domoticz/assets/16821599/474c6042-2391-45a0-ae25-9738df842634)

Can you please tell me which file it is exactly (source code)?

**Comment by gizmocuz** [comment]
Seems you have some more errors....

It could be coming from DomoticzTCP.cpp, but best to search yourself

**Comment by gizmocuz** [comment]
It's logged on two places.
Should not happen, unless you have systems not running the same version

**Comment by ilkaskim** [comment]
> Seems you have some more errors....
> 
> It could be coming from DomoticzTCP.cpp, but best to search yourself

I tried to find this error on the internet. Unfortunately, I have not had any success in fixing it. This bug has existed for a long time in both same beta versions. 
I also looked in the logs without success. 
As long as the running system doesn't cause any problems, it doesn't really bother me.

**Comment by gizmocuz** [comment]
`This bug has existed for a long time in both same beta versions.`

Do you mean that this also happened before the 2024.1 beta's?
In this case I know I have to look somewhere else than in the new master/client code

To be sure, 'Werkstatt' is the hardware named "Domoticz - Remote Server" correct?

**Comment by ilkaskim** [comment]
> `This bug has existed for a long time in both same beta versions.`
> 
> Do you mean that this also happened before the 2024.1 beta's?
> In this case I know I have to look somewhere else than in the new master/client code
> 
> To be sure, 'Werkstatt' is the hardware named "Domoticz - Remote Server" correct?

This bug/problem has been going on for over a year "Error: Error parsing http request address: ::ffff:172.104.11.51" 


Since 2024.1 update, This message is new and I don't see it in the logs what the error is.  "Error: Werkstatt: Invalid data received!"

Yes, "Werkstatt" is "Domoticz - Remote Server" 

On both Domoticz installations I always have the same beta versions installed.

**Comment by gizmocuz** [comment]
Found the issue! It was because the TCP receive buffer was 1024 bytes which was to short.
Please update to the latest beta and it's solved

**Comment by waltervl** [comment]
Issue seems not to be solved for everyone https://www.domoticz.com/forum/viewtopic.php?p=312037#p312037
