### ISSUE TITLE
Problem segmentation fault after upgrade domoticz

### ISSUE THREAD

**Issue by vlugtj** [domoticz/domoticz#5973]
### Issue Guidelines
I have an raspberry PI  1 b+ V1.2 wich has now the latest version of domoticz installed but after upgrade domoticz show segmentation fault. Domoticz was working for several years now.
I even tried new sd card and totally new installation but also the same problem.
searched the internet but no useful information found.
Please help me if possible

**Comment by JurgenLB** [comment]
Please use the search function;
See #5958 
https://github.com/domoticz/domoticz/issues/5958#issuecomment-1876724739
