### ISSUE TITLE
Energy indicator block from Tasmoticz.

### ISSUE THREAD

**Issue by Daro1003** [domoticz/domoticz#5974]
Energy indicator block from Tasmoticz.

I read on the forum that you are working on the next version. Can you do something with the electricity block from Tasmoticz?
Because in dashticz two blocks are shown but their name and order cannot be changed, only both blocks are under the same name because in domoticz there is one block. This block shows the total energy and the energy of yesterday. In the previous version there were two separate blocks in domoticz energy yesterday and total energy.
Please update the plugin.
![Energia całkowita11](https://github.com/domoticz/domoticz/assets/53434098/0930e124-5a7e-4748-8de9-2d1c5dae0692)
![DomoticzWtyczka](https://github.com/domoticz/domoticz/assets/53434098/4681ea03-1d51-46a7-a22a-b928379300b7)
Because it is transferred to the dashboard in two separate blocks in which it is not possible to change the name or set them on the desktop. It is better if Total Energy and Yesterday Energy are two separate blocks in Domoticz
![Dashticertrerz](https://github.com/domoticz/domoticz/assets/53434098/fdf2b22a-11f9-4a57-88a2-59eb07593553)
This has been the case since the beginning, when you wrote the new version of the plugin, I wrote about it on the forum. The graphs are ok nice but there are just two readings in one block device.
See, in Domoticz there is one block and in Dashticz there are two blocks whose position cannot be set or a different name cannot be set and it is not known what is going on.
Can you change something? Or where to report a problem?
Dashticz:
![Wtyczkaaa](https://github.com/domoticz/domoticz/assets/53434098/fdb85d49-90b2-40c3-a26d-1363f43f72d3)
I didn't do anything to put it together. This just happened after your plugin update a few months ago. I wrote about it on the forum right away.
The thing is that earlier in the plugin it was stated that the total energy and the energy yesterday were two devices in domoticz and two in dashticz.

And now the total energy and yesterday's energy are one device in domoticz and two in dashticz which cannot edit the name and settings.

Sorry, I'm Polish and I translate into English using Google Translator.

Can I go back to the previous version??

Dashticz is a Domoticz screen, it is a part of Domoticz.
The problem was also reported to my colleague @joba1, but nine may understand what I mean.
https://github.com/joba-1/Tasmoticz/issues/44

On January 1, I wanted to reset the energy indications with the command EnergyTotal1 0 EnergyTotal2 0 EnergyTotal3 0 and the reset of the indications went very well - the indications were 0.0, but unfortunately, in order for the Tasmota indications to appear in Domoticz, you have to remove the device in Domoticz. When they remove a device in domoticz, its idx changes and then the pointer in daschticz does not work and the next change in daschticz works. When I have several counters, there is some work with changes.

**Comment by waltervl** [comment]
Dashticz is not part of Domoticz, it is an add on, maintained by a user. So please use the Dashticz subforum for your questions.
https://www.domoticz.com/forum/viewforum.php?f=67

Also Tasmoticz is a plugin so if you have questions about this use the forum or the github repository of Tasmoticz.

This github list is only for bugs. I am closing this issue here.
