### ISSUE TITLE
Shelly blinds buttons not working properly.

### ISSUE THREAD

**Issue by Daro1003** [domoticz/domoticz#5975]
Shelly blinds.
The stop button doesn't work.
The up button works but it is not possible to stop the roller blind because the stop does not work and when you press the up button the roller blind stops and moves up.
The down button works, but there is no way to stop the roller blind because the stop does not work and when you press the down button, the roller blind stops and moves down.
Dashticz:
![Rolety](https://github.com/domoticz/domoticz/assets/53434098/cd3f401d-34bb-4583-b60c-d348bbf28d9d)

If it is not possible to stop in this block, please make the up/down buttons work so that when the blind is moving, pressing it again stops it.

**Comment by waltervl** [comment]
If this is dashticz specific please close this issue and make topic in the dashticz forum https://www.domoticz.com/forum/viewforum.php?f=67
If this is related to the ShellyTeacher application make a remark there.

**Comment by waltervl** [comment]
I am closing this issue, please use the forum.
