### ISSUE TITLE
Device won't turn off when using blocky

### ISSUE THREAD

**Issue by anno006** [domoticz/domoticz#5977]
Can't give a lot.

On 2024.1  a blocky script for turning on or off a device with a button. Will not work when turning device off. What does work is a group. This is working great. I did remember that some years ago the same problem occurred for some time.

I can't give any logs because there are no logs. it just doesn't work period without giving.

It does not  help but here are the specs:
Nuc with esxi
A vm with Ubuntu 20.04
Domoticz 2024.1. 15817

**Comment by gizmocuz** [comment]
Could you post a screenshot of your blockly? And the button, is that a Push On button? Maybe a screenshot of the button and device from the device manager or GUI as well

**Comment by anno006** [comment]
not needid. the blocky is without errors, and did work befor the 2024.1 for years! button is normal on/off button and also before the 2024.1 working great. Also my dimmer scripts are givving problems now also, same here did work before the 2024.1 update.
example of this code, Lua:

```
commandArray = {}

DomDevice = 'DummyDimmer';

if devicechanged[DomDevice] then
    if(devicechanged[DomDevice]=='Off') then
        DomValue = 0;
    else
        DomValue = otherdevices_svalues[DomDevice];
        CalcValue = (DomValue-1) * 33;
        round = (CalcValue)
    end
    if CalcValue==nil then
        CalcValue=0
    end
    print("PWM value= "..CalcValue);
end
return commandArray

```
And i already did share the blocky,
[https://www.domoticz.com/forum/viewtopic.php?t=41322&sid=38a94894e20a682705c82763edaa00a1](url)

**Comment by gizmocuz** [comment]
@anno006 , thanks for the link to the forum.
I will try to replicate this issue

**Comment by gizmocuz** [comment]
So, I changed your lua script a little bit to just print the value

I added a dummy switch, and changed it to a dimmer.

When I use the percentage slider, I see the PWM value change. When I turn off the dimmer, it is set to 0, when I turn it on, it goes to to the last set percentage value.
All works correctly.

**Comment by anno006** [comment]
Great and all, but i have the same code here, and here it is not working on 2024.1!!!!!!!

**Comment by gizmocuz** [comment]
Are you on the latest beta version as I am?

**Comment by anno006** [comment]
Not jet, i am on 2024.1 15831. I see that there is a new one today, 15838, i am updating now

On version 15838 it is working better, i do see more of this log entry:
2024-01-13 22:14:16.341 Status: User: admin (IP: xx.xx.xx.xx) initiated a switch command (222/Buiten BM 10/Off)
2024-01-13 22:14:16.491 Status: LUA: PWM value= 2805.0

jet not all the command do work. some are lacking "2024-01-13 22:14:16.491 Status: LUA: PWM value= 2805.0"

update 00:39 just walked my dog, non of the lights came on until later, some of them came on. Also the group method did not work on another light that has a motion detection as activator.

**Comment by gizmocuz** [comment]
Is it possible to update to the latest beta, add a NEW dummy switch, change it's type to a slider, and create a new lua script that just prints the PWM value like with the script below:

```
commandArray = {}

DomDevice = 'DummyDimmer';

if devicechanged[DomDevice] then
    if(devicechanged[DomDevice]=='Off') then
        DomValue = 0;
    else
        DomValue = otherdevices_svalues[DomDevice];
        CalcValue = (DomValue-1) * 33;
        round = (CalcValue)
    end
    if CalcValue==nil then
        CalcValue=0
    end
    print("PWM value= "..CalcValue);
end
return commandArray
```

Please do note that all devices have to have a UNIQUE name... it is not possible to have triggers or control devices with a same name. (also do not use a switch and a watt sensor with the same name for example in a script)

**Comment by anno006** [comment]
i do not use names on more that one device, are you saing that i lie!!!????

Also, i already know that i need a dummy dimmer slider for thes script. It is only the version of domoticz that has changed, every onther did RUN GREAT BEFOR THE UPDATE!!!!!!!!!!!!!!!!!!!!

ALSO,

This script will not work, it does have no commands to espeasy. So there will never be a light on or off with this script you gave:

commandArray = {}

DomDevice = 'DummyDimmer';

if devicechanged[DomDevice] then
    if(devicechanged[DomDevice]=='Off') then
        DomValue = 0;
    else
        DomValue = otherdevices_svalues[DomDevice];
        CalcValue = (DomValue-1) * 33;
        round = (CalcValue)
    end
    if CalcValue==nil then
        CalcValue=0
    end
    print("PWM value= "..CalcValue);
end
return commandArray

**Comment by gizmocuz** [comment]
No, I did not mention you lied, just that you have to take care of this

**Comment by gizmocuz** [comment]
Does my above script work 'internally' so with the dummy device?
The above LUA script seems to run OK?

No idea you are talking about ESPEasy ... you did not mention this before at all.

And no need to shout here...

No idea how this ESPEasy fits in in the above lua script, are you sending the PWM value? (CalcValue)
I don't see how you send it..
I just see a calculation and a print, and the print does change when you move the slider

**Comment by gizmocuz** [comment]
Does it work when you create a dzVents script to control it?

**Comment by anno006** [comment]
> not needid. the blocky is without errors, and did work befor the 2024.1 for years! button is normal on/off button and also before the 2024.1 working great. Also my dimmer scripts are givving problems now also, same here did work before the 2024.1 update. example of this code, Lua:
> 
> ```
> commandArray = {}
> 
> DomDevice = 'DummyDimmer';
> 
> if devicechanged[DomDevice] then
>     if(devicechanged[DomDevice]=='Off') then
>         DomValue = 0;
>     else
>         DomValue = otherdevices_svalues[DomDevice];
>         CalcValue = (DomValue-1) * 33;
>         round = (CalcValue)
>     end
>     if CalcValue==nil then
>         CalcValue=0
>     end
>     print("PWM value= "..CalcValue);
> end
> return commandArray
> ```
> 
> And i already did share the blocky, [https://www.domoticz.com/forum/viewtopic.php?t=41322&sid=38a94894e20a682705c82763edaa00a1](url)

Ik begrijp niet wat jullie doen. Ik had hierboven dus problemen mee punt. ik werd door jullie ondoordachte "stabiele" 2024.1 update om heel veel opnieuw te doen omdat heel veel volledig door elkaar gehaald was en of niet (meer) volledig werkte. Hierdoor werdt ik gedwongen mijn oplossing van meerder domoticzen te gebruiken om om de vele fouten die tot op de dag van vandaag nog in domoticz zitten te omzeilen. Maar door de andere manier van verbinding met domotcizen, wat misschien wel een vooruit gang is, maar als het daardoor volledig door elkaar raakt i.v.m. vele, niet alle devices een nieuw exemplaar van heb en dat ook nog zonder enige waarschuwing en of uitleg. Maar goed de code hierboven. Deze werk niet tot heel erg slecht als de dimmer op dezelfde domoticz zit als de code. Als ik de dimmer (virtual) op domoticz 1 heb en op de 2de een andere dimmer met de code dan werkt HET VLEKKELOOS!!!!!!! Allemaal BEDANKT voor NIETS!!!!! lekker dagen 24 uur per dag jullie PUINHOOP te omzeilen en zoeken naar een weg die (nog) wel werkt voor zolang dat duurt! TD van espeasy doet het wel fatsoenlijk, geeft iniedergeval BIJ ELKE UPDATE een volledig overzicht van de veranderingen. Ik ga nu weer verder met de omzeilingen door te voeren!

**Comment by gizmocuz** [comment]
On our forum we publish the latest changes with each release.
We also mention to make a complete backup before doing so.
If you don't take the time to read or create a backup, don't update regularly, you might get into troubles.
Anyway, your reaction is childish.
You also do not understand what open-source software is. And you don't care that we develop this in our sparse free time.
I think it is best if you stop using this software as this requires a certain level of intelligence.
From your reaction I understand you clearly do not have such skills.
