### ISSUE TITLE
MQTT Auto Discovery Client - unable to set QOS

### ISSUE THREAD

**Issue by alessandroBalliniGPA** [domoticz/domoticz#5978]
Domoticz Beta 2023.2 build 15758.
Cannot set QOS level for MQTT.

Default seems zero, should be at least 1.

**Comment by gizmocuz** [comment]
Default is indeed zero and is fine

**Comment by alessandroBalliniGPA** [comment]
Zero is fine for playing at home when you don't care of messages lost.

In a real usage scenario 1 is the the best solution, so the settings should at least be exposed in hardware config.

https://www.youtube.com/watch?v=vTbkMUjPQ5o

**Comment by gizmocuz** [comment]
Sorry, Domoticz is using QoS 1 when publishing messages

**Comment by gizmocuz** [comment]
You should be able to see this when using MQTT Explorer
Subscribing is done with 0 (I can change this)

**Comment by gizmocuz** [comment]
Beta 15831 now as the default QoS set to 1
But I am unable to verify this. Even publishing messages with MQTT Explorer with QoS 1 shows up as 0 here

**Comment by alessandroBalliniGPA** [comment]
In MQTT Explorer in Connection window -> Advanced, you can set QOS settings of each topic. You can try and see if you see any diff

**Comment by gizmocuz** [comment]
That did the trick! Thanks!
