### ISSUE TITLE
Retrospective sensor update through JSON API

### ISSUE THREAD

**Issue by dynasticorpheus** [domoticz/domoticz#598]
Would be nice to be able to (optionally) specify an alternative date/time stamp when doing a sensor update through the JSON API. This would allow better interaction with devices which are not doing regular updates. Withings scale sending it's (every 5 min) air quality data only once or twice a day to an online server to save batteries is a nice example. 

I understand these kind of devices have limited usage in the _automation_ part of Domoticz but the information itself can still be relevant. 

Unfortunately I am a python (only) guy so can't contribute from coding perspective I am afraid.

**Comment by gizmocuz** [comment]
i dont understand why....
If your sensor sends once or twice a day, then thats fine! And when it is received in domoticz, it gets a timestamp

**Comment by dynasticorpheus** [comment]
Let me clarify a bit more. The scale I am using as an example executes temperature and CO2 measurements every five minutes but pushes the collected data only once or twice a day to the cloud solution (Withings website) from which I am pulling the data. If I can't specify date/time stamps during the data push to Domoticz all measurements will get more or less the same date/time stamp assigned. Direct connection to the scale is not possible as it is push only.

**Comment by gizmocuz** [comment]
Then if you know at what time it is pushed, you make a crontab script that pulls the data, and push it in domoticz with the json API
It is not 100% accurate, but close enough

**Comment by dynasticorpheus** [comment]
Using my example (TEMP + CO2) I would still end up having 288 (12hrs / 5min \* 2) measurements pushed into Domoticz with more or less the same date/time stamp (the time it get's pushed via json). Instead I would like to provide the system also the date/time stamp when the measurement was actually recorded. This way Domoticz can (retrospectively) show a nice graph from the last 12 hours or whatever has been provided in regards of data. 

Once can also just write the values directly to the DB but needless to say this is far from ideal and should be avoided at all times.

**Comment by gizmocuz** [comment]
Well those 288 measurements is not a real/big issue.... and its whats happening
But there is an idea to only log the short values on state changes, and that is what you suggest above as well

**Comment by dynasticorpheus** [comment]
Any place where I can follow this discussion or dev only talk?

**Comment by gizmocuz** [comment]
probably here ? Else on the forum ? If your a developer, please start a thread in the developers section on the forum
