### ISSUE TITLE
mail notifications with attached Pictures fails

### ISSUE THREAD

**Issue by herm42** [domoticz/domoticz#5980]
With the latest Beta versions my mailserver does not accept notification mails (only  with attached camera pictures) anymore.

Linux x64 v2024.1.15831

Error Message:
 rejected after DATA: maximum allowed line length is 998 octets, got 639934

**Comment by gizmocuz** [comment]
Thanks for reporting. Should work fine with beta 15835.
Is it possible to test this?

**Comment by herm42** [comment]
confirmed ... mais are working again!

thx for the quick fix
