### ISSUE TITLE
Blockly "Set Setpoint to" stopped working for ZWave-JS UI Thermostats

### ISSUE THREAD

**Issue by herm42** [domoticz/domoticz#5981]
when changing Setpoints of my zwave thermostats via Blockly scripts nothing happens.... it does not even generate log entries. This behaviour starts somewhen between jan 1st and now.

Changing the temp via Webfrontend Utility -> Device works fine 

linux X64 on domoticz  2024.1 (build 15831)

**Comment by gizmocuz** [comment]
@herm42 , and you are using ZWaveJS-UI or OpenZWave? Could you post your blockly screenshot?

**Comment by gizmocuz** [comment]
Can you confirm it is working correctly with a dummy Setpoint? This one is working correctly here

![image](https://github.com/domoticz/domoticz/assets/2265299/2e540b83-eda9-4fe2-8fb2-85f47e366b55)

**Comment by leopoldwang** [comment]
lua SetSetpoint method has stopped working as well since 15817. I have had to use JSON api instead. And that's targeting netatmo thermostat.

**Comment by herm42** [comment]
yes i'm using zwave-js-ui ... but i'm on 9.6.2 since a while

created this one ... 
![Screenshot_20240113_133025](https://github.com/domoticz/domoticz/assets/6725469/efd30c85-9fbd-4f2e-9d94-1b7ee808b909)

does not work here ... thermostat setpoint does not change to 0°C after the event has been triggered

2024-01-13T13:33:26.989258+01:00 ha domoticz: dummy-switches: Light/Switch (dummy-normaltemperatur)
2024-01-13T13:33:26.998331+01:00 ha domoticz: EventSystem: Event triggered: normaltemperatur_1
2024-01-13T13:33:26.998447+01:00 ha domoticz: EventSystem: Event triggered: test_1

**Comment by gizmocuz** [comment]
@herm42 , you are on one of the latest beta versions? You have a normal dummy on/off switch and a dummy setpoint, both created from the hardware page with the dummy setup button, using the webgui, and the dummy setpoint does not go to 0 when you turn ON the dummy switch?
Your blockly is enabled and the dummy hardware as well?

Coz, it's working just fine here... also with 0 degrees

**Comment by herm42** [comment]
to answer your questions ...
2024-01-13T13:49:15.214835+01:00 ha domoticz: dummy-switches: Light/Switch (dummy-normaltemperatur)
2024-01-13T13:49:15.223922+01:00 ha domoticz: EventSystem: Event triggered: normaltemperatur_1
2024-01-13T13:49:15.224037+01:00 ha domoticz: EventSystem: Event triggered: test_1
2024-01-13T13:49:15.255548+01:00 ha domoticz: dummy-switches: Light/Switch (dummy-wohnzimmer-temp)

in this case two blockly scripts are triggered ...
in script "normaltemperatur" it changes the dummy-wohnzimmer-temp to off  (the last log entry).
the script "test" has been triggered, but no further log entries 

both events are enabled

**Comment by herm42** [comment]
![Screenshot_20240113_135617](https://github.com/domoticz/domoticz/assets/6725469/454939ec-e19f-43eb-9584-86cae9dbc45b)
i receive the notification mail after the event has been triggered

**Comment by gizmocuz** [comment]
Thanks, but it did not quite answer my question and making me even more confused as we are now talking about two scripts.

1. Are you on the latest beta, if not, plz try this...
2. From the hardware/dummy setup, you have created a normal dummy on/off switch
3. From the hardware/dummy setup, you have created a setpoint
4. If you make a simple blockly like I did above and turning ON the dummy switch, does it sets the Dummy Setpoint correctly?

**Comment by herm42** [comment]
1. see answer 1 build 15831
2. yes (answer 5)
3. yes (answer 5)
4. script in answer 5 & 8

just saw there is the new build ... one minute please

**Comment by herm42** [comment]
just updated to 15835 ...

created again a new blockly script as mentioned ...

![blockly](https://github.com/domoticz/domoticz/assets/6725469/2423104a-ea09-4c88-8cf5-7e090fc7f13c)

what should i say .... dummytherm does not get the new value after the event is triggered :-(

2024-01-13T14:53:05.698542+01:00 ha domoticz: dummy-switches: Light/Switch (dswitch)
2024-01-13T14:53:05.707795+01:00 ha domoticz: EventSystem: Event triggered: test_1

**Comment by herm42** [comment]
there are two different "Setpoint" variants available when creating a virtual device .... "Setpoint" and "Thermostat Setpoint"... i tried setting them both in blockly, but it's always the same ... nothing happens

**Comment by gizmocuz** [comment]
There are indeed. Both create the same type (Setpoint)
Quite strange It is working here as it should....

Just to make sure (needless to ask... but I do it anyway)
The dswitch has to be ON, it won't react to OFF
In the settings, the EventSystem has to be enabled

This is on the same system, not a master/client setup?

More I cannot think of

![image](https://github.com/domoticz/domoticz/assets/2265299/3f9f90ab-77f7-4b27-9301-69b50c8dcdc8)

![image](https://github.com/domoticz/domoticz/assets/2265299/dad0dba3-c46f-4e08-b20f-2d092b3fcc28)

![image](https://github.com/domoticz/domoticz/assets/2265299/32ba1d79-e7ca-4319-8f33-63bcb0ef67d0)

**Comment by herm42** [comment]
hmm ... just reviewd everything again ...
all my blockly scripts are working fine, except setting new setpoint values :-( seems something in my setup is screwed up. will sneak around and try to find something

**Comment by herm42** [comment]
restored now a backup from three weeks ago (Version: 2023.2 (build 15760)) ... there everything works. when i update then to the latest beta the setpoint is dead again :-(

**Comment by gizmocuz** [comment]
So strange... And when you stop domoticz, rename the database, start domoticz (system is clean now),
then add a dummy, a switch, a setpoint, and a blockly does it work then?

**Comment by herm42** [comment]
hmm ... even more weird.
1. moved the db away
2. tried to create the dummy devices ... here i got the first error 
  
![shot2](https://github.com/domoticz/domoticz/assets/6725469/2d0d7170-5848-4d0b-bbc6-0469e93ce02c)

3. both devices have been created ... but are not activated automatically
![shot3](https://github.com/domoticz/domoticz/assets/6725469/9cf4d7fb-78a9-44a3-8f11-23d484094460)

4. added them manually
![shot4](https://github.com/domoticz/domoticz/assets/6725469/ae4ca957-a2fe-4b92-a287-9f4071619fc2)

5. created new blockly script
![shot5](https://github.com/domoticz/domoticz/assets/6725469/4d440a56-cce7-4b52-82ab-a72087f56779)

6. triggered the new event
then i got a NEW device!!
![shot6](https://github.com/domoticz/domoticz/assets/6725469/9ee9b60e-aab4-4b9c-a4ac-6952e391df26)


tried the same with a completely new setup again ... same result

using debian bookworm Python 3.11.2 ... maybe this causes the problems?

**Comment by herm42** [comment]
... changed now all setPoint related blockly scripts to dzvents ... fixed it for me

**Comment by gizmocuz** [comment]
@herm42 , thank you for reporting!!! There was indeed a problem with a new database.
The new DeviceStatus table field 'OrgHardwareID' did not have a type assigned (should have been integer),
the database upgrade script did add the correct state.
This was causing a issue further down with creating new devices.
Fixed in beta 15839 !

Is it possible to still try to see if the new beta solves the issue for you in Blockly as it should work on both systems (blockly/lua/dzVents/python)

**Comment by herm42** [comment]
updated the system to 15839

created a new dummysetpoint device and a simple blockly script to set a new setpoint value .... but again the update is failing :-( ... doing the same via dzvents works

**Comment by gizmocuz** [comment]
@herm42, but no more 'error creating a dummy device' error I hope
Still puzzles me why the blockly does not work on your end, but glad it's working via dzVents

**Comment by herm42** [comment]
confirmed, there is no error when creating a dummy device anymore.
regarding blockly issue.... for sure something trivial at the end :-)

**Comment by gizmocuz** [comment]
Please also check the latest beta as there was a  bug in the setpoint code related to blockly/lua

**Comment by herm42** [comment]
confirmed ... new beta fixed the issue!

thx for your work!
