### ISSUE TITLE
My shades always report as closed after activity stops

### ISSUE THREAD

**Issue by xvisor16** [domoticz/domoticz#5982]
Hi,

I have shades connected to my Domoticz through MQTT-AD connected to ESPSomfy RTS.
I have some issues in the past but have all been resolved but one. The shades in domoticz always show it's closed. When opening or closing. I see the percentage running to where it should but when it's done. The status in Domoticz changes to Closed. When checking MQTT the position value is correct and shows the right percentage. So it seems that Domoticz is not correctly reading the position it's in after when idle.
After looking into it with MQTT Explorer it seems that last update send to MQTT is direction=0 (this is the state_topic accoring to the config values) I have the feeling domoticz might be using the state_topic to display it's current state while the state_topic display's only if it's idle, opening or closing (0, 1 or -1) and always returns to 0 when the action stops. The position_topic in MQTT still displays the correct position. I would think the position_topic is the value used to display the state when idle so you always now what the position of you shade actually is.

Config topic:
`{
"~":"espsomfy/shades/1",
"device":
{
"hw_version":"v2.3.1",
"name":"ESPSomfyRTS",
"mf":"rstrouse",
"identifiers":["mqtt_espsomfyrts_AD3F1C"],
"via_device":"mqtt_espsomfyrts_AD3F1C",
"model":"ESPSomfy-RTS MQTT"
},
"availability_topic":"espsomfy/status",
"payload_available":"online",
"payload_not_available":"offline",
"name":"Slaapkamer",
"unique_id":"mqtt_AD3F1C_shade1",
"device_class":"shutter",
"payload_close":"-1",
"payload_open":"1",
"position_open":100,
"position_closed":0,
"state_closing":"-1",
"state_opening":"1",
"command_topic":"~/direction/set",
"position_topic":"~/position",
"set_position_topic":"~/target/set",
"state_topic":"~/direction",
"payload_stop":"0",
"state_stopped":"0",
"enabled_by_default":true
}`

value of the position_topic is 60 for example.
Domoticz shows it as closed. When setting is to 10 domoticz start counting the percentage down to 10 and almost immediately after that shows it's closed instead of staying on the 10 of the position_topic

![image](https://github.com/domoticz/domoticz/assets/12544669/3fa0214a-b820-4f3c-8463-9a042b0de4a1)

![image](https://github.com/domoticz/domoticz/assets/12544669/976c2c88-b086-4123-b1c0-0feaf8bba9dd)

Could this be fixed in Domoticz or is the problem somewhere else?

**Comment by gizmocuz** [comment]
Could you send some state topics + payload to debug this issue?

~/direction
~/position

Could you also post the complete config topic, this way we can see if it is of type 'cover' and saves us typing in a fake one

**Comment by xvisor16** [comment]
@gizmocuz,

The config topic is called:
espsomfy/cover/1/config

Closed:
![image](https://github.com/domoticz/domoticz/assets/12544669/c6445164-3727-4200-8dfe-68760067bab4)

While opening:
![image](https://github.com/domoticz/domoticz/assets/12544669/3469d056-3d58-482b-b110-066225ebcd35)

Opened:
![image](https://github.com/domoticz/domoticz/assets/12544669/6b12fee1-b05f-4acd-b8f5-99dc4a9743b8)

**Comment by gizmocuz** [comment]
The problem was with the state topic being used indeed.

Could you try beta 15838

Hope this works, and there are no issues with other users with blinds as I disabled the listening to the state topic when a position topic is configured

**Comment by xvisor16** [comment]
Yup, all working perfectly now!
