### ISSUE TITLE
Domoticz Remote server invalid data recieverd

### ISSUE THREAD

**Issue by anno006** [domoticz/domoticz#5983]
The remote server on 2024.1>= gives a error:

Master version 2024.1 (15838)
Status: D10: connected to: xx.xx.xx.xx:xx
Status: D10: disconnected from: xx.xx.xx.xx:xx
Error: D10: Invalid data received!

I think it has to do with the new possiblety of sensing other devices as KWH meters to another domoticz. This was before the 2024.1 update not possible. In this example the slave domoticz has only KWh sensors. So non of those sensors are receiving on the master domoticz.

And the error on the slave domoticz Error: 

Slave version 2024.1 (15838)
Error parsing http request address: ::ffff:xx.xx.xx.xx

**Comment by gizmocuz** [comment]
@anno006, As mentioned in the release note of 2024.1 and also another sticky note on the forum regarding the beta version,
you need to run the same Domoticz version on both master and client.
(Or one of the latest beta versions)
You are now mixing a client (2024.1 master i suppose...) with one of the recent beta versions.
You should update them both to the same beta version and this problem should be gone

**Comment by anno006** [comment]
> The remote server on 2024.1>= gives a error:
> 
> Master version 2024.1 (15838) Status: D10: connected to: xx.xx.xx.xx:xx Status: D10: disconnected from: xx.xx.xx.xx:xx Error: D10: Invalid data received!
> 
> I think it has to do with the new possiblety of sensing other devices as KWH meters to another domoticz. This was before the 2024.1 update not possible. In this example the slave domoticz has only KWh sensors. So non of those sensors are receiving on the master domoticz.
> 
> And the error on the slave domoticz Error:
> 
> Slave version 2024.1 (15838) Error parsing http request address: ::ffff:xx.xx.xx.xx

**Master version 2024.1 (15838)** is this another version than the slave, or do i reed something wrong!!!

**Comment by gizmocuz** [comment]
No, seems you are all fine here.
The machine that displays this error is the machine that connects to the other Domoticz correct?
I myself have some General/kWh sensors being received from a remote location without issues.

It is type: General, subtype: kWh , that is giving issues?

**Comment by anno006** [comment]
![2 dom](https://github.com/domoticz/domoticz/assets/5137113/121f078c-1a25-477b-a51d-a4fe150ce333)

**Comment by gizmocuz** [comment]
There is one place where there is an exception and when this occurs this "Invalid data received!" message also occurs.

One of the reasons could be that the password you are using is incorrect.

You mention the remote site only has kWh sensors, so until now you have not received anything yet?

Could you double check the correct username/password?
Needless to say (but I do it anyway), on the remote site->Setup Users-> you have to create a user/password and these values have to be used on the machine that is connecting to it

**Comment by gizmocuz** [comment]
These are a few of the devices I received from a remote Domoticz

![image](https://github.com/domoticz/domoticz/assets/2265299/ccf94b93-11b0-40c4-86fd-ffcfc7728a07)

**Comment by anno006** [comment]
plenty retype the password in boath domoticz. The same error. 

The sensors are the next types:
Voltage
Cm113 electrisave
Electric watt
Custom sensor
kwh
current
etc.

Did some digging,and more trying i do get the sensor now, only still the errors:
2024-01-14 16:53:20.130 Error: D9: Invalid data received!
2024-01-14 16:53:20.160 Error: D9: Invalid data received!
2024-01-14 16:53:20.196 Error: D9: Invalid data received!
2024-01-14 16:53:20.244 Error: D9: Invalid data received!

**Comment by gizmocuz** [comment]
Could you update to the latest beta to see if you get 'Exception' errors?

Your answers are a bit difficult to understand.

In your initial post you are talking about kWh sensors, about D10 and this is D9?

How many remote Domoticz instances do you have? 10?
Is it not more logical to give them a real name, like 'meterroom', 'location 2' ?

**Comment by gizmocuz** [comment]
Finally found the issue!!!

It was because the TCP receive buffer was 1024 bytes which was to short.
Please update to the latest beta and it's solved
