### ISSUE TITLE
Sudden rise in memory usage with build 15801

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5984]
Version: 2024.1 (build 15801)
Build Hash: 4d18f2dbf
Compile Date: 2024-01-03 12:12:37
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 11 2023, 09:51:27) [GCC 8.3.0]

In my minimalistic Slave system with NO plugins there is a sudden rise in Process Usage after my last update.
On 3 Jan. I updated Domoticz from build 15773 to 15801 because of the new master/slave setup. I also update the Master to the same build.
![14 01 2024_11 03 56_REC](https://github.com/domoticz/domoticz/assets/24824113/9932fec8-2a88-4b09-a7ed-411b3ad4b227)
Before the update the Process Usage was very stable between 30 and 40 Mb for a long time. The Process Usage on the Master is very stable.

**Comment by gizmocuz** [comment]
Did you specify which devices the client should receive, or is it all devices?
If it's all, I can imagine a slight increase depending on the amount of devices.
My memory is pretty stable looking at the last year so I am also confident to say it's probably not domoticz related

How about the process memory?

**Comment by SargonofAssyria** [comment]
Only 7 devices:  2 P1 (Elec. and Gas) 2 Rfxcom Temp devices and 3 Motherboard devices (Int. Temp, CPU and Memory Usage) are transferred to the Master. These are for years the same devices. On the Slave side nothing has changed. Only the update of Domoticz to 15801 because of the new device transfer methode, because I updated the master. That is the **only** change in the slave, no system update or anything else, so it has to be Domoticz related. This slave is running for more then 8 years now, mainly to get the P1 data transfered. This the graph of Process Memory in my case called Process Usage. RPi memory has the same kind of graph.
![14 01 2024_16 44 57_REC](https://github.com/domoticz/domoticz/assets/24824113/c38c8f9b-186e-45a9-85c2-a48360f7a813)
The last update of the system was on 11-12-2023, just a few packages.
Only 6 dzVents scripts are running and those have not been changed since 18 June 2023

**Comment by SargonofAssyria** [comment]
The raspberry was up for 77 days. I now rebooted the Raspberry and will see what happens.

**Comment by gizmocuz** [comment]
Did your memory got stable after a (few) day(s)

**Comment by SargonofAssyria** [comment]
This is the current graph.
![18 01 2024_10 02 07_REC](https://github.com/domoticz/domoticz/assets/24824113/26ab969e-b525-445e-895d-36c11c2e2249)
After the 'initial' reboot of the system it looked ok, but I had to upgrade to 15858 just 1 day ago. I made the system as clean as possible. It still looks ok now but have to wait now for a few more days, because there is still an increase. So come back here in a few more days.

**Comment by SargonofAssyria** [comment]
It will take a bit longer, because yesterday I tried to find memory leaks with a prog called memleax.
Domoticz did not like the program and its intervention, so Domoticz halted and I had to restart Domoticz.
I am now only using pmap to find the leak, but that will consume time. And try valgrind on my test system.

**Comment by gizmocuz** [comment]
Still think there is no leak! But I am interesested at your findings

**Comment by SargonofAssyria** [comment]
Got some more pictures from build 15866
![29 01 2024_09 49 47_REC](https://github.com/domoticz/domoticz/assets/24824113/bfdd2588-4813-4843-8f8a-8e8ee633b960)
The rise in memory consumption is still there, although a little bit less steep.

Starting at 23-01-2024 I took every hour a memory map of the Domoticz process.
This is a compare between 23-01-2024 11:00 and 29-01-2024 09:00
![29 01 2024_09 48 58_REC](https://github.com/domoticz/domoticz/assets/24824113/e4c6c3ee-7ab7-451d-819d-c11a08b872f8)
On the right site there is a growth visible from memory 0x63500000 to 0x67100000
That memory is never released, and grows by the day.
1 part of the memory I dumped to a file and see a lot of references to my Domoticz slave devices which are setup to be transfered to my master system, like all my Motherboard sensors and P1 smart meter data.

Further more I see a few malloc and free statements is the source that are not completely aligned. I mean not every malloc has his free statement. But that could be due to my incomplete knowledge of C++

**Comment by gizmocuz** [comment]
Very interesting find about master/client

That got me thinking... and I think I now found the place where this could happened.
First I thought that it had to do with boost::asio, but it was one step before this

Could you check with beta 15882 ?

Ps. Every 'malloc' should have a free, as well as every 'new' and 'strdup' for instance

If you see places where this is possibly not happening, better report them (can also be done on our slack channel)

**Comment by SargonofAssyria** [comment]
Upgrade to 15882, will have to wait a few days.

**Comment by SargonofAssyria** [comment]
My slave looks stable now.
![30 01 2024_09 41 41_REC](https://github.com/domoticz/domoticz/assets/24824113/4bd1d904-a23e-47d3-b8c0-82554e13f148)
But know I have a more sincere problem with my master.
In less then 1 day from 100Mb usage to  more then 200Mb usage. This is even more secious.
![30 01 2024_09 42 10_REC](https://github.com/domoticz/domoticz/assets/24824113/c5405d43-f0db-4a75-8c3c-18f7ebef5678)

**Comment by gizmocuz** [comment]
Please define slave.... is this the remote domoticz instance where you connect to?

**Comment by SargonofAssyria** [comment]
Yes, the one the the lowest memory consumption and almost no hardware and devices.
I will reboot the master, because I saw that the memory rise took place just before the update.

**Comment by gizmocuz** [comment]
Good, this means the memory leak has been solved.
I already made a new stable release that contains this fix.
Why your master has such a huge peak I don't know... 
But do note there will always be some memory increase as we keep things stored internally (like the last 300 log lines per state, some temp sensors etc)
But it should be stable at one point

**Comment by SargonofAssyria** [comment]
I know, I will keep an eye on it.
