### ISSUE TITLE
New install on Raspberry Bookwork won't run

### ISSUE THREAD

**Issue by robpl1** [domoticz/domoticz#5985]
Created a new install on a Raspberry Pi 4 of Bookworm, then installed Domoticz using 
sudo bash -c "$(curl -sSfL https://install.domoticz.com)"  

Used my Browser to connect to ipaddr 192.168.1.xxx:8080 - connection refused.
I'm using WinSCP so opened an SSH terminal to the Pi. Ran 
sudo service domoticz start  
no messages so ran
sudo service domoticz status 
and initially received the "/home/pi/domoticz/domoticz directory can't be found" error.  I opened domotics.sh in /etc/init.d and noticed that the path to the .sh file read 
DAEMON=/home/pi/domoticz/$NAME
where $NAME = domoticz,  so removed the domoticz reference both in the /etc/init.d  folder and in /home/pi/domoticz
and rebooted since the reload command apparently had no effect.
Now, while I don't get the directory error Domoticz still won't start. the error message now is
domoticz.sh[841]: start-stop-daemon: unable to start /home/pi/domoticz (Permission denied)
I've checked the permissions on /home/pi and all sub-directories are for the user pi and have  rwxr-xr-x rights (octal 755) and in /etc/init.d  we've got the same settings #755 with user root.

The only other thing that might be related is  /run/systemd/generator.late/domoticz.service that doesn't have the eXecute setting.

Can anyone help here?

**Comment by gizmocuz** [comment]
This is a known issue and also has a problem with OpenSSL3
As the majority of users still uses Buster the next stable release will be for this system.
After this we need to switch to OpenSSL3

You can compile domoticz yourself, please see our wiki/forum
