### ISSUE TITLE
email sending problem after upgrade to 2024.1 and 2024.2

### ISSUE THREAD

**Issue by WillemD61** [domoticz/domoticz#5989]
After upgrade to 2024.1 and 2024.2 a domoticz email notifcation results in the following error messages:

2024-01-16 10:55:01.039 Error: SMTP Mailer: Error sending Email to: <xxxxxxxx@upcmail.nl> !
2024-01-16 10:55:01.039 Error: libcurl: (56)
2024-01-16 10:55:01.039 Error: Failure when receiving data from the peer
2024-01-16 10:55:01.039
2024-01-16 10:55:01.039 Error: Failed to send Email notification!

This was tested with this script:
return {
	on = {
		timer = { 'every minute'},
        },
	execute = function(domoticz, triggeredItem)
	    domoticz.notify('this is a test',domoticz.LOG_INFO)
	end
}

The problem also occurs when testing from the settings page.
Email configuration is correct and was not changed from previous versions.

Problem also reported by other users

**Comment by gizmocuz** [comment]
I was going to ask to use the forum.....

But by accident I found out you already posted on the forum... better to mention that here next time plz.

[https://www.domoticz.com/forum/viewtopic.php?f=6&t=41336](https://www.domoticz.com/forum/viewtopic.php?f=6&t=41336)

So you where able to email before?

**Comment by WillemD61** [comment]
Yes, previous stable  versions no problem.
I already raised an issue because it was reported by other users as well, here and on tweakers

**Comment by gizmocuz** [comment]
There has been a change for attachments in SMTPClient.cpp, but that should have no impact on the test email.

**Comment by WillemD61** [comment]
I just started up my fresh compiled 2023.2 version and this now has the same problem.
Maybe something changed at ziggo side at the same time as domoticz upgrade, although no info on their website.
I called them and according to to them, nothing has changed.
I will test via another system I have that uses smtp email directly.

**Comment by WillemD61** [comment]
My other smtp email sending on other systems also show problems.
I switched from ziggo to gmail and that works without problems.
Issue can be closed. Not caused by domoticz.
