### ISSUE TITLE
critical security report

### ISSUE THREAD

**Issue by Kontiduo** [domoticz/domoticz#5990]
Hi,

I made security scan by trivy and received 433 vulnerabilities. A lot!
Please find them attached.
Could you fixed them in next version?

Regards,
Marek
[security.txt](https://github.com/domoticz/domoticz/files/13954738/security.txt)

**Comment by gizmocuz** [comment]
This is not related to Domoticz, it's your system! (apt, git, bash, curl)
Stop reporting these messages as it takes us time to review

**Comment by Kontiduo** [comment]
Thank you for prompt answer, but this is not my system but docker image taken from official domoticz site. Regards, Marek

**Comment by gizmocuz** [comment]
Okey that is fine since it runs in it's own private space

Soon we upgrade to the latest Debian release which is also using OpenSSL3
