### ISSUE TITLE
set setpoint in Lua not working

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#5991]
In latest beta 2024.2 and stable 2024 a setpoint device can not be set by Lua script. In Dzvents it is working.

For details and example scripts see forum topic.
https://www.domoticz.com/forum/viewtopic.php?p=311954#p311954

**Comment by gizmocuz** [comment]
I found the issue! 🫢😳

The issue was inside the internal task scheduler that was checking for a fixed SetPoint device ID....

Fixed in beta 15864

**Comment by waltervl** [comment]
Thanks, confirmed indeed in latest beta.
