### ISSUE TITLE
LUA - option "FOR" and "REPEAT" don't work for my blind RFXCOM Brell DDxxxx type 

### ISSUE THREAD

**Issue by tcellerier** [domoticz/domoticz#5995]
Hello,

I have an issue with my blind RFXCOM (FW release 2024) and the LUA features "FOR' and 'REPEAT'
My model of the blind is Brell DDxxxx type (same as this one https://github.com/domoticz/domoticz/issues/5804 )

I tried all of the following commands:
- commandArray['Store Cuisine'] = 'Close'  => works
- commandArray['Store Cuisine'] = 'Open' => works
- commandArray['Store Cuisine'] = 'Open FOR 3 SECONDS'  => works
- **commandArray['Store Cuisine'] = 'Close FOR 3 SECONDS'  => does not work and sends another weird signal to the store (down 1 second and then up)**
- **commandArray['Store Cuisine'] = 'Open REPEAT 5 INTERVAL 5' => doesn't work, nothing happens**
- **commandArray['Store Cuisine'] = 'Close REPEAT 5 INTERVAL 5' => doesn't work, nothing happens**

Would you mind taking a look?

Thanks
Thomas

**Comment by gizmocuz** [comment]
Does the widget in domoticz have a stop button that works?
"Open FOR 3 SECONDS" sends a 'open' and after 3 seconds a stop?

No idea what open repeat 5 interval 5 does... 

Did you already asked on the forum ?
Did you try with dzVents as well?

**Comment by tcellerier** [comment]
> Does the widget in domoticz have a stop button that works?
Yes the button in domoticz UI work perfectly fine.

> "Open FOR 3 SECONDS" sends a 'open' and after 3 seconds a stop?
No it sends the signal during 3 seconds and that's it, no "stop" signal

> No idea what open repeat 5 interval 5 does...
According to the documentation https://www.domoticz.com/wiki/LUA_commands , the command will be repeated 5 times with 5 seconds interval

> Did you already asked on the forum ?
No

> Did you try with dzVents as well?
No

**Comment by gizmocuz** [comment]
Maybe you could try dzVents first, then ask the forum, and if you have no luck we could try here.
This is for code related bugs, and we don't know if it is a code related bug yet

**Comment by waltervl** [comment]
Forum topic https://www.domoticz.com/forum/viewtopic.php?t=41409
