### ISSUE TITLE
MQTT Error for Moes BHT-002-GCLZB device

### ISSUE THREAD

**Issue by scottydj2** [domoticz/domoticz#5996]
Hi,

Running beta build 15845 on an rpi4.

I've just added a Moes BHT-002-GCLZB thermostat [device](https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html) to my system running underfloor heating via zigbee2mqtt. Most parts have been autodetected correctly, by my domoticz log is regularly showing the following error:

**2024-01-22 17:45:37.814 Error: Zigbee2mqtt Gateway: Climate device unhandled temperature_state_template (0x9035eafffe2a8a1e_climate_zigbee2mqtt)**

I *think* this is the config from MQTT Explorer which is relevant:

{
  "action_template": "{% set values = {None:None,'idle':'off','heat':'heating','cool':'cooling','fan_only':'fan'} %}{{ values[value_json.running_state] }}",
  "action_topic": "zigbee2mqtt/Bathroom 2 Floor",
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state"
    }
  ],
  "current_temperature_template": "{{ value_json.local_temperature }}",
  "current_temperature_topic": "zigbee2mqtt/Bathroom 2 Floor",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x9035eafffe2a8a1e"
    ],
    "manufacturer": "Moes",
    "model": "Moes BHT series Thermostat (BHT-002-GCLZB)",
    "name": "Bathroom 2 Floor"
  },
  "json_attributes_topic": "zigbee2mqtt/Bathroom 2 Floor",
  "max_temp": "35",
  "min_temp": "5",
  "mode_command_topic": "zigbee2mqtt/Bathroom 2 Floor/set/system_mode",
  "mode_state_template": "{{ value_json.system_mode }}",
  "mode_state_topic": "zigbee2mqtt/Bathroom 2 Floor",
  "modes": [
    "off",
    "heat"
  ],
  "name": "Bathroom 2 Floor",
  "preset_mode_command_topic": "zigbee2mqtt/Bathroom 2 Floor/set/preset",
  "preset_mode_state_topic": "zigbee2mqtt/Bathroom 2 Floor",
  "preset_mode_value_template": "{{ value_json.preset }}",
  "preset_modes": [
    "hold",
    "program"
  ],
  "temp_step": 1,
  "temperature_command_topic": "zigbee2mqtt/Bathroom 2 Floor/set/current_heating_setpoint",
  "temperature_state_template": "{{ value_json.current_heating_setpoint }}",
  "temperature_state_topic": "zigbee2mqtt/Bathroom 2 Floor",
  "temperature_unit": "C",
  "unique_id": "0x9035eafffe2a8a1e_climate_zigbee2mqtt"
}

homeassistant/climate/0x9035eafffe2a8a1e/climate/config

And these are the devices created: 

![image](https://github.com/domoticz/domoticz/assets/8860627/27082aa2-31e3-4aca-b01f-9ff172183511)

Anyone identify what the problem is?

Thanks,

Scott

**Comment by gizmocuz** [comment]
I suspect that the state published in "zigbee2mqtt/Bathroom 2 Floor" does not always contain the "current_heating_setpoint" value
It might be not there, or null

Maybe we need to silence this warning, everything is working correctly?

**Comment by scottydj2** [comment]
Yes, as far as I can tell everything is working correctly.

**Comment by gizmocuz** [comment]
Thanks for reporting. I removed this error line and it will be available in a new beta release today
