### ISSUE TITLE
Unable to login: invalid user/password From app (and only form app)

### ISSUE THREAD

**Issue by Ippephyx** [domoticz/domoticz#5998]
Hi,
The original admin user can login form web and app, no problem. But any new user or admin I create will have "Unable to login: invalid user/password" when trying to connect from the app, but no problem whatsoever to login from webpage.

Version: 2024.2
Build Hash: 73d655383
Compile Date: 2024-01-15 16:48:07
dzVents Version: 3.1.8
Python Version: None

I've tried from both apps : the new "only app" and the previously bought (and older) premium app.

**Comment by waltervl** [comment]
This would be an issue on the app repository as the app is maintained seperately https://github.com/domoticz/domoticz-android

**Comment by gizmocuz** [comment]
@Ippephyx , also please use our Forum next time
