### ISSUE TITLE
New Temperature Comparison Chart Not Fahrenheit.

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#6001]
Ver: 2024.2 (Build 15864)
Operating System: Debian Bookworm

I'm in the US so my temp units are set to Fahrenheit. The new Comparison chart says "Fahrenheit" but the actual values are clearly in Celsius.  See attached pic.  On a side note the other temp charts are fine.
![domotempbug8bit](https://github.com/domoticz/domoticz/assets/24983850/fb788724-b2f2-4566-93fd-26fd7571b765)

**Comment by gizmocuz** [comment]
Thanks for spotting! Fixed in beta 15872
