### ISSUE TITLE
Update doesn't start domoticz under systemd

### ISSUE THREAD

**Issue by lennardk** [domoticz/domoticz#6002]
Since 7767b8482b3b089a0c8cc7d266531506388c708d, domoticz doesn't start itself during the update process when running under systemd. I think it doesn't even get to actually updating.

My thinking is the reason for this is that under systemd, when you stop the service (which `sudo service domoticz.sh start` does), systemd will stop all processes running under the service, which includes the update script itself. It'll then never actually get to the updating and the `sudo service domoticz.sh start` line.

NB: this only applies when updating domoticz through the UI button, not when using the script from a shell.

**Comment by gizmocuz** [comment]
As you can see the changes here are to exclude a Armv6 system to update.
This has (i my idea) nothing todo with systemd

Also when you look in the c++ code (WebServerCmds.cpp), Line 2257, you will see that this script is executed in the background detached from the main process

**Comment by lennardk** [comment]
The commit may be intended for Armv6, but it changes `updaterelease` quite a bit. Notably for this, it replaces the `sudo service domoticz.sh restart` at then end by a 'stop, update, start' cycle.

In systemd, by default, all services are run in such a way that processes are tracked. Even though the script is detached from the main domoticz process, systemd still knows it belongs to the domoticz service. When stopping the service, it then also stops the update script.

I'm not sure what the best way to address this would be. Detecting wether you're running in systemd would be a possibility, although it is a bit complicated. Changing the release script to accept some environment variable to indicate it is running in systemd might be easier.

**Comment by gizmocuz** [comment]
This release script is now almost identical to the beta script which has been in use for years!
So, it is not a script issue. 

Even in the previous version we also ended with this line

sudo service domoticz.sh restart

So, it has nothing to do with the change

Autodetect is the way to go if you want to modify the script.

Has to be tested really good on both systems

**Comment by lennardk** [comment]
My point is, since the change, the script *doesn't* end with `sudo service domoticz.sh restart` any longer. It first stops, then it starts later. I'm not sure if there was more in the commit then intended or something.
Either way, I will try to make some time to set up a test system to confirm or disprove my analysis and test autodetect methods.

**Comment by gizmocuz** [comment]
Thanks! And for the record, you did not use the install script from our website? Because for years I do not hear about this problem from users using the beta version
