### ISSUE TITLE
MQTT AD - Configuration properties

### ISSUE THREAD

**Issue by MuadDibVV** [domoticz/domoticz#6003]
Hello,

   Since version 9.8.0, zwave-js-ui expose configuration properties throught MQTT (https://github.com/zwave-js/zwave-js-ui/commit/3048fede52d4cd5ac3c32f7064712266f3bedcfc).
  Devices linked to switch part seems to be created, but not number part

```
  	config_switch: {
		type: 'switch',
		object_id: 'config_switch',
		discovery_payload: {
			payload_off: '0',
			payload_on: '1',
			value_template: '{{ value_json.value }}',
			command_topic: true,
			enabled_by_default: false,
			entity_category: 'config',
		},
	},

	// https://www.home-assistant.io/integrations/number.mqtt
	config_number: {
		type: 'number',
		object_id: 'config_number',
		discovery_payload: {
			value_template: '{{ value_json.value }}',
			command_topic: true,
			enabled_by_default: false,
			entity_category: 'config',
		},
	},
```
Is it possible to correct that ?

Thanks

**Comment by gizmocuz** [comment]
Could you follow this wiki and publish some number config topics here?

https://www.domoticz.com/wiki/MQTT_AD_Report_Problems

**Comment by waltervl** [comment]
@MuadDibVV Did you check the Device list behind the MQTT AD Setup button. As that should show these number devices: https://www.domoticz.com/wiki/MQTT#MQTT_Autodiscovery_Setup

**Comment by MuadDibVV** [comment]
> @MuadDibVV Did you check the Device list behind the MQTT AD Setup button. As that should show these number devices: https://www.domoticz.com/wiki/MQTT#MQTT_Autodiscovery_Setup

Hello @waltervl
Yes there is 356 devices in this list

![image](https://github.com/domoticz/domoticz/assets/62676693/0e33c2d4-d15a-40cc-b478-78b7d467f969)

**Comment by MuadDibVV** [comment]
> Could you follow this wiki and publish some number config topics here?
> 
> https://www.domoticz.com/wiki/MQTT_AD_Report_Problems

Hello @gizmocuz 
Here is an exemple
{
  "value_template": "{{ value_json.value }}",
  "command_topic": "zwave/12/112/0/1/set",
  "enabled_by_default": false,
  "entity_category": "config",
  "min": 0,
  "max": 65535,
  "state_topic": "zwave/12/112/0/1",
  "availability": [
    {
      "payload_available": "true",
      "payload_not_available": "false",
      "topic": "zwave/12/status",
      "value_template": "{{'true' if value_json.value else 'false'}}"
    },
    {
      "topic": "zwave/_CLIENTS/ZWAVE_GATEWAY-Zwavejs2Mqtt/status",
      "value_template": "{{'online' if value_json.value else 'offline'}}"
    },
    {
      "payload_available": "true",
      "payload_not_available": "false",
      "topic": "zwave/driver/status"
    }
  ],
  "availability_mode": "all",
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xdf041442_node12"
    ],
    "manufacturer": "Shenzhen Neo Electronics Co., Ltd.",
    "model": "Door/Window Sensor (NAS-DS01Z)",
    "name": "DetectOuvGarage",
    "sw_version": "3.80"
  },
  "name": "DetectOuvGarage_config_number_1",
  "unique_id": "zwavejs2mqtt_0xdf041442_12-112-0-1"
}

zwaveMQTTAD/number/DetectOuvGarage/config_number_1/config

**Comment by MuadDibVV** [comment]
But I think I have more than 600 config devices, I am not sure that it's a good idea to keep them... Is there a risk of performance issues with all this mqtt AD devices ?
Of course if I don't want them, my problem is on the ZwavejsUI side because I cannot automaticaly filter config entity...

**Comment by waltervl** [comment]
If they dont change there is no worry for performance. 

They only store a config value and in Domoticz this list can be used to change that value from Domoticz. If you don't do this then no messages sent. 

But first you complain they are not created, and now you find out they are created and it is not good??

**Comment by MuadDibVV** [comment]
300 was created and 300 was not created.
My wish is mostly to have a stable and complete situation

**Comment by waltervl** [comment]
I agree to have a clear and stable creation of those config (=number) devices. But it was not clear from your first message.
To be sure: The problem data in https://github.com/domoticz/domoticz/issues/6003#issuecomment-1919966285 is from a number device that is not in the list?

Edit: I already see that the config device "DetectOuvGarage_config_number_1" is in your list..... So this one is working.

**Comment by gizmocuz** [comment]
The name for this config is very strange 'DetectOuvGarage_config_number_1', is this the default name?

The config (number object) has successfully been detected.

Not quite clear what the problem is you are having?

When the value is actually published (in this case to zwave/12/112/0/1) it is also displayed:

![image](https://github.com/domoticz/domoticz/assets/2265299/1757f38a-f2a3-4c4c-8fc2-9f0fae544d0b)

And when you set the value, it is also published to MQTT

![image](https://github.com/domoticz/domoticz/assets/2265299/c36b80d2-a891-4360-9e01-b5d32b9dc89c)

What is the issue you are having?

**Comment by MuadDibVV** [comment]
Well, on my side, the device is not created... I imagine that it's because I have an unknown value by default.
(yes, xxx_config_number_1 is default name)

NB : on ZWaveJSUI they advise to not create by default device with "enabled_by_default" to false

**Comment by waltervl** [comment]
Yes, it is created but not in the standard device list but in the configuration menu as a configuration device.

**Comment by gizmocuz** [comment]
Exactly, number devices show up when you press the 'setup' button next to the hardware in the hardware list.
There are also setup items.
Closing issue as there is no issue
