### ISSUE TITLE
Message 'Error: Cannot set options on device 0' in log on creation device

### ISSUE THREAD

**Issue by Xenomes** [domoticz/domoticz#6006]
No impact issue.

When creating a selection or thermostat device in a Python plugin using the DomoticzEx calling framework, the log shows the message 'Error: Cannot set options on device 0.' However, the device is created with the specified options and functions correctly. I have searched but could not find a solution for the Selector switch, and I have also included the new thermostat options in the plugin code. 

I have simplified the creation process in the plugin. Perhaps there is a change that is not documented in the wiki?
```
mode = ['off','1','2','3','4','5']
options = {}
options['LevelOffHidden'] = 'true'
options['LevelActions'] = ''
options['LevelNames'] = '|'.join(mode)
options['SelectorStyle'] = '0'
Domoticz.Unit(Name='Test', DeviceID='123', Unit=1, Type=244, Subtype=62, Switchtype=18, Options=options, Used=1).Create()
```

**Comment by gizmocuz** [comment]
@Xenomes , could you make a minimal plugin so I could test/debug this?

**Comment by Xenomes** [comment]
No problem!

**Comment by Xenomes** [comment]
@gizmocuz the test is create on: https://github.com/Xenomes/Test

**Comment by gizmocuz** [comment]
Thanks! Hope to look at this later this afternoon or early morning...
There is also a small error in the code as this log message "Cannot set options on device" appears twice in SQLHelper.cpp, once for **CSQLHelper::GetDeviceOptions** (should be another log message!) and once for **CSQLHelper::SetDeviceOptions**

This also does not make sense

	if (idx.empty()) {
		_log.Log(LOG_ERROR, "Cannot get options on device %s", idx.c_str());
		return optionsMap;
	}

this wil log an empty device of course....

Anyway, going to have a look at this !

**Comment by Xenomes** [comment]
Perfect! As mentioned, there's no hurry, and it does not affect the workflow.

**Comment by Xenomes** [comment]
Thanks for fixing! The test latest beta and the message is gone! Removed the test plugin.
