### ISSUE TITLE
OpenZWave stats request returns 200 OK but empty doc

### ISSUE THREAD

**Issue by travellingkiwi** [domoticz/domoticz#601]
Code to request and return stats has been commented out...

**Comment by gizmocuz** [comment]
Where... Maybe pull request?... Did you try when it when it was not commented out?

**Comment by travellingkiwi** [comment]
I've cloned the repo. The code is in hardware/OpenZWave.cpp line 5177 

`void CWebServer::ZWaveCPGetStats(WebEmSession & session, const request& req, reply & rep))
`

The comment says

`//Crashes at OpenZWave::GetNodeStatistics::_data->m_sentTS = m_sentTS.GetAsString();
`

and the rest of the function is commented out.

I haven't managed to uncomment it yet as the setup instructions on the wiki don't result in a usable openzwave installation (i.e. openzwave installs but domoticz can't find it. I'm just debugging that now).

H

**Comment by travellingkiwi** [comment]
OpenZWave...

https://www.domoticz.com/forum/viewtopic.php?t=6310

Won't ask why...

**Comment by gizmocuz** [comment]
I think it is pretty well explained in the wiki (at least in building for raspbery, which is the same as building for ubuntu and others)
Commended it out... lets see what happens...

Crashes here at:
string TimeStampImpl::GetAsString

**Comment by gizmocuz** [comment]
Found the crash, m_stamp was not parsed as a pointer, will make a git pull request

**Comment by travellingkiwi** [comment]
The function COpenZWave::GetCPStats doesn't exist... Maybe someone started it and got bored.

**Comment by gizmocuz** [comment]
I never get bored 😀

**Comment by gizmocuz** [comment]
Made a pull request to OpenZWave, if they merge the fix, i will enable this

**Comment by travellingkiwi** [comment]
The OpenZWave fix comment would appear to indicate the issue was only with Windows? Any chance we could enable it for Linux immediately?

**Comment by gizmocuz** [comment]
Is the patch accepted ?

**Comment by gizmocuz** [comment]
Will be in the upcoming beta version (both windows/linux)

**Comment by travellingkiwi** [comment]
Works in current git commits.

**Comment by gizmocuz** [comment]
When you do this... and then go in domoticz to the group/network, how does that look?
Could you post a screenshot ?
