### ISSUE TITLE
Error: EvoHome: Login failed with message: invalid_grant

### ISSUE THREAD

**Issue by yellyfish1** [domoticz/domoticz#6011]
Since last week Evohome doesn't sync anymore. An error is logged: Error: EvoHome: Login failed with message: invalid_grant

I'm using version 2024.4 of domoticz

Using the same credentials to login on international.mytotalconnectcomfort.com does work properly. Is there anyone with the same problem?

**Comment by gizmocuz** [comment]
Please use the forum

**Comment by yellyfish1** [comment]
For others with the same problem. This solves the problem: https://github.com/domoticz/domoticz/issues/5350
1. In your Evohome account, create a new password which meets the password requirements but contains only 1 special character, preferably a *
2. In Domoticz under hardware adjust "Evohome via web API" and disable "show schedule". You can leave "synchronize installation" and "show location" to on.
3. Set "poll interval" to be above 300 seconds.
4. adjust the password to what has been created under 1
5. click update
