### ISSUE TITLE
GPIO pinnumber for raspberry Pi 5

### ISSUE THREAD

**Issue by ericstaal** [domoticz/domoticz#6014]
The raspbery Pi 5 has a complete new pin nummering.

GPIO 26 (pin 37) on the Pi4 is mapped to pin nummer GPIO 425 on the pi5
(See file /sys/kernel/debug/gpio)

The GPIO hardware limits thist number:
```
#define GPIO_PIN_MIN		0
#define GPIO_PIN_MAX		31
```

Max on the Pi5 is 511.
Can this number be increased to 511?

**Comment by gizmocuz** [comment]
I'm afraid that won't work.
The reason is that the current code is using this 'number' as unit.

```
			result = m_sql.safe_query("SELECT nValue FROM DeviceStatus WHERE (HardwareID==%d) AND (Unit==%d)",
				m_HwdID, gpio_pin);
```

The unit can range from 1 to 255, not higher

What you could try is to try to find only the PIN items, and use the number beging the PIN as unit?

 gpio-460 (PIN3                )
 gpio-461 (PIN5                )
 gpio-462 (PIN7                )
 gpio-463 (PIN29               )
 gpio-464 (PIN31               )
 gpio-465 (PIN26               )
 gpio-466 (PIN24               )
 gpio-467 (PIN21               )
 gpio-468 (PIN19               )
 gpio-469 (PIN23               )
 gpio-470 (PIN32               )
 gpio-471 (PIN33               )
 gpio-472 (PIN8                )
 gpio-473 (PIN10               )
 gpio-474 (PIN36               )
 gpio-475 (PIN11               )
 gpio-476 (PIN12               )

But they are named differently on a RPI4 (and probably below)

 gpio-16  (GPIO16              )
 gpio-17  (GPIO17              )
 gpio-18  (GPIO18              )
 gpio-19  (GPIO19              )
 gpio-20  (GPIO20              )

But what hardware have you connected to the GPIO?
Could you use SysFS ? (https://www.domoticz.com/forum/viewtopic.php?t=22501)

Or if they are switches/buttons/lights, move to zigbee2mqtt?

**Comment by ericstaal** [comment]
PIN number can still be used, bit still it will prevent access all available IO. RPI5 exposed quite a lot (which can be very nice ;) )

I connected a doorbell (12 vac) to some gpio.
sysfs is deprecated in bookworm: https://forums.raspberrypi.com/viewtopic.php?t=343514 It is migrated to libgpiod
switching to zigbee/zave is a bit difficult since the electrical scheme has to be adjusted.
 
I currently solved it used an external script using libgpiod and used the http api of domoticz to enable a dummy switch. Which is workable.

Best solution is to switch to gpiod but this will take more time. 
Temporary workaround is to create a mapping form gpio pin to unit.

**Comment by gizmocuz** [comment]
If you could create a mapping in the current code that would be great!
Else I'm afraid this PR can't be used.

There are more options for a doorbell, Eufi/Ring/KlikAanKlik uit

**Comment by ericstaal** [comment]
I can write the code, but I am bit limited in my test environment, so I don't know when I got this finished.
Changing is to libgpiod will result in problems with non bookwork releases. This should be in the future

**Comment by gizmocuz** [comment]
Maybe for now, connect to a pin that is compatible with the current implementation? Else switch to a new doorbell system 😁
I'm closing the PR but leave this one open! Thanks for the PR!

**Comment by ericstaal** [comment]
I changed the mapping from pin number to unit. upgrading should not cause any issues. migrating to different hardware might have problems since mapping from [0-512] to [0-255] without duplicates is impossible

**Comment by gizmocuz** [comment]
Okey, I think we are not talking about the same thing here.

I find it very difficult to read your code change ... pin -> unit, the unit is the pin number right?

Anyway, below the output from a RPI4

**sudo cat /sys/kernel/debug/gpio | grep '(GPIO'**

 gpio-4   (GPIO_GCLK           )
 gpio-5   (GPIO5               )
 gpio-6   (GPIO6               )
 gpio-12  (GPIO12              )
 gpio-13  (GPIO13              )
 gpio-16  (GPIO16              )
 gpio-17  (GPIO17              )
 gpio-18  (GPIO18              )
 gpio-19  (GPIO19              )
 gpio-20  (GPIO20              )
 gpio-21  (GPIO21              )
 gpio-22  (GPIO22              )
 gpio-23  (GPIO23              )
 gpio-24  (GPIO24              )
 gpio-25  (GPIO25              )
 gpio-26  (GPIO26              )
 gpio-27  (GPIO27              )

And here the output from a RPI5:

**cat /sys/kernel/debug/gpio | grep '(PIN'**
 gpio-460 (PIN3                )
 gpio-461 (PIN5                )
 gpio-462 (PIN7                )
 gpio-463 (PIN29               )
 gpio-464 (PIN31               )
 gpio-465 (PIN26               )
 gpio-466 (PIN24               )
 gpio-467 (PIN21               )
 gpio-468 (PIN19               )
 gpio-469 (PIN23               )
 gpio-470 (PIN32               )
 gpio-471 (PIN33               )
 gpio-472 (PIN8                )
 gpio-473 (PIN10               )
 gpio-474 (PIN36               )
 gpio-475 (PIN11               )
 gpio-476 (PIN12               )
 gpio-477 (PIN35               )
 gpio-478 (PIN38               )
 gpio-479 (PIN40               )
 gpio-480 (PIN15               )
 gpio-481 (PIN16               )
 gpio-482 (PIN18               )
 gpio-483 (PIN22               )
 gpio-484 (PIN37               )
 gpio-485 (PIN13               )

These are the actual pins you can use right?

Now if you do a string search, and detect either '(GPIO' or '(PIN', you can use the number behind here as the 'pin' (the unit in SQL)

**Comment by gizmocuz** [comment]
But maybe (I don't use GPIO) I am wrong about the pin numbers here

**Comment by ericstaal** [comment]
So GPIO pin number is platform specific

in PI1-4 these are as you mentions, resulting in GPIO numbers [4-27], same as pinnumbers. in the sysfs hardware the variable used for this is mapping to Unit. All are in the range of [0-255] so valid.

Sysfs is mapped to/sys/class/gpio/gpioXXX, where XXX is the GPIO number (not the pin number). If I want to use the pin numbers I have to perform explicit linux command to get these numbers, which limits the GPIO which can be used (eg the pi5 has for example also gpio for leds etc). Using the pin numbering as unit will create a good mapping to 'unit' but is not as efficient and only for PI 5

The 'unit' is an internal Domoticz thing and as long as it is unique per hardware device it is sufficient, which is currently the case. The advantage of using a modulo it that it will work on all platforms and is an efficient robust solution.
Pi5 has a different mapping. the gpio number used for the external gpio header are in the range [400-426].

I don;t see the benefit using pin numbers, it will make the code more complex and less robust. Sysfs is deprecated and should be removed in the future and replaced by libgpio, until this is not the case this PR will allow to make use of the GPIO without any upgrading issues.

The raspberry can use different IO for a physical pin: https://www.elektronik-kompendium.de/sites/raspberry-pi/bilder/raspberry-pi-gpio.png

So mapping gpio nr to pin is not always the same. For pi5 these numbers have changed since a kernel update. So it is not as stable as we would like

**Comment by gizmocuz** [comment]
I think using GPIO in Domoticz is quite deprecated... they are way better alternatives.
Anyway, before I can merge this PR, I just need to be 100% that previous users don't get new Units...
If that is the case, I will merge this of course

**Comment by ericstaal** [comment]
Well currently only gpios from 0 till 255 can be used and those remain the same. There are no migration issues

The change allow gpio > 255 also to be used.
