### ISSUE TITLE
Domoticz Remote server invalid data recieverd 2024.4

### ISSUE THREAD

**Issue by Roel6** [domoticz/domoticz#6017]
After updating from last stable to present 2024.4 my remote server connection does not work any more.
Both DOMOTICZ systems are running the same stable 2024.4
I check the password
Only once I receved a error "invalid data recieverd"
No error are shown in the logs after that even aster a reboot

Any surgestions?
Thanks

**Comment by gizmocuz** [comment]
Please use the forum. Make sure accept new devices is enabled as you will get new devices. You can press edit/replace on your old device to transfer everything to the new device
