### ISSUE TITLE
Since version 2024.4 beta Build 15899 : blinds, Venetian blinds icons are not displayed correctly on a Floorplan.

### ISSUE THREAD

**Issue by mealgi** [domoticz/domoticz#6018]
Hello

1 - Context:
Hardware : RPI3B+
Version: 2024.4 (build 15899)
Build Hash: https://github.com/domoticz/domoticz/commit/4d18f2dbf55c75cb4637d606869400834868f6c7
Compile Date: 2024-01-03 12:12:37
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]

2 - Issue
Since version 2024.4 blinds, Venetian blinds icons are not displayed correctly on a Floorplan.
They are replaced by a lightbulb.

Findings in domoticzdevices.js:
- line 855 the type is forced to "light" when it refers to a device type "Light/Switch"
- line 890 in case of a type "light" a new Lightbulb is created instead of a Blinds item.

BR

**Comment by gizmocuz** [comment]
Can you make a PR to solve this?
(And I assume this is happening in the beta and not in the 2024.4 stable release? You might want to change the issue topic)

**Comment by mealgi** [comment]
@gizmocuz,

The thing is i don't know what was the objective of the latest changes in domoticzdevice.js  regarding the light type devices.

I am not able to fix the issue.

I reverted to the previous domoticzdevice.js file as a workaround.

BR

**Comment by gizmocuz** [comment]
Yes, that's not a solution.....

Could you try beta 15901? This should now work again....

**Comment by jibenito** [comment]
In the last beta 15901 all icons dissapear...

**Comment by gizmocuz** [comment]
hmmm

**Comment by gizmocuz** [comment]
Beta 15902 should solve that

**Comment by jibenito** [comment]
Great!!! The best and fastest solution ever!!!
