### ISSUE TITLE
Add zwave device Manufacturer id="0115" name="Z-Wave.Me" Product type="1000" id="0300" name="ZME_RC2"

### ISSUE THREAD

**Issue by Ramon00** [domoticz/domoticz#602]
Please add support for the zwave device attached in the zip file.
Manufacturer id="0115" name="Z-Wave.Me" Product type="1000" id="0300" name="ZME_RC2"

Thank you

[zme_RC2.zip](https://github.com/domoticz/domoticz/files/211280/zme_RC2.zip)

**Comment by gizmocuz** [comment]
Thanks, but you have to request this on the openzwave github/forum

**Comment by Ramon00** [comment]
ok will do
