### ISSUE TITLE
Inovelli Multi-Color Bulb (LZW42) Fails auto discovery

### ISSUE THREAD

**Issue by catstitan** [domoticz/domoticz#6022]
Ubuntu 22.04.3 LTS (GNU/Linux 6.5.0-15-generic x86_64)
Domoticz Version: 2023.2 (build 15604)
zwave-js-ui: 9.2.2.aeedd90
zwave-js: 12.2.0

After adding the bulb I see this error:
24-02-08 08:06:30.775 Error: MQTT Z-Wave: MQTT_Discovery (on_auto_discovery_message): Error: Value is not convertible to float.! (topic: homeassistant/light/iBulb1/rgbw_bulb/config, message: {"state_topic":"zwave/30/38/0/currentValue","command_topic":"zwave/30/38/0/targetValue/set","on_command_type":"brightness","brightness_state_topic":"zwave/30/38/0/currentValue","brightness_command_topic":"zwave/30/38/0/targetValue/set","state_value_template":"{{ \"on\" if value_json.value|int > 0 else \"0\" }}","brightness_value_template":"{{ (value_json.value|int) | round(0) }}","brightness_scale":"99","color_temp_state_topic":"zwave/30/51/0/currentColor","color_temp_command_template":"{{ {'warmWhite': ((0.7349 * (value - 153))|round(0)), 'coldWhite': (255 - (0.7349 * (value - 153))|round(0)), 'red': 255, 'green': 255, 'blue': 255}|to_json }}","color_temp_command_topic":"zwave/30/51/0/targetColor/set","color_temp_value_template":"{{ '%03d%03d' | format((value_json.value.warmWhite), (value_json.value.coldWhite)) }}","rgb_command_template":"{{ {'warmWhite': 0, 'coldWhite': 0, 'red': red, 'green': green, 'blue': blue}|to_json }}","rgb_command_topic":"zwave/30/51/0/targetColor/set","rgb_state_topic":"zwave/30/51/0/currentColor","rgb_value_template":"{{ value_json.value.red }},{{ value_json.value.green }},{{ value_json.value.blue }}","min_mireds":153,"max_mireds":500,"payload_on":"on","payload_off":"0","device":{"identifiers":["zwavejs2mqtt_0xc6284104_node30"],"manufacturer":"Inovelli","model":"Multi-Color Bulb (LZW42)","name":"iBulb1","sw_version":"2.31"},"name":"iBulb1_rgbw_bulb","unique_id":"zwavejs2mqtt_0xc6284104_Node30_rgbw_bulb"}

**Comment by catstitan** [comment]
Here's the above message formatted:

**homeassistant/light/iBulb1/rgbw_bulb/config**

```
{
	"state_topic": "zwave/32/38/0/currentValue",
	"command_topic": "zwave/32/38/0/targetValue/set",
	"on_command_type": "brightness",
	"brightness_state_topic": "zwave/32/38/0/currentValue",
	"brightness_command_topic": "zwave/32/38/0/targetValue/set",
	"state_value_template": "{{ \"on\" if value_json.value|int > 0 else \"0\" }}",
	"brightness_value_template": "{{ (value_json.value|int) | round(0) }}",
	"brightness_scale": "99",
	"color_temp_state_topic": "zwave/32/51/0/currentColor",
	"color_temp_command_template": "{{ {'warmWhite': ((0.7349 * (value - 153))|round(0)), 'coldWhite': (255 - (0.7349 * (value - 153))|round(0)), 'red': 255, 'green': 255, 'blue': 255}|to_json }}",
	"color_temp_command_topic": "zwave/32/51/0/targetColor/set",
	"color_temp_value_template": "{{ '%03d%03d' | format((value_json.value.warmWhite), (value_json.value.coldWhite)) }}",
	"rgb_command_template": "{{ {'warmWhite': 0, 'coldWhite': 0, 'red': red, 'green': green, 'blue': blue}|to_json }}",
	"rgb_command_topic": "zwave/32/51/0/targetColor/set",
	"rgb_state_topic": "zwave/32/51/0/currentColor",
	"rgb_value_template": "{{ value_json.value.red }},{{ value_json.value.green }},{{ value_json.value.blue }}",
	"min_mireds": 153,
	"max_mireds": 500,
	"payload_on": "on",
	"payload_off": "0",
	"device": {
		"identifiers": [
			"zwavejs2mqtt_0xc6284104_node32"
		],
		"manufacturer": "Inovelli",
		"model": "Multi-Color Bulb (LZW42)",
		"name": "iBulb3",
		"sw_version": "2.31"
	},
	"name": "iBulb3_rgbw_bulb",
	"unique_id": "zwavejs2mqtt_0xc6284104_Node32_rgbw_bulb"
}
```

**Comment by gizmocuz** [comment]
@catstitan , thank you for reporting.
I will have a look into this, but could you please follow this guide as well:

https://www.domoticz.com/wiki/MQTT_AD_Report_Problems

(mention the config topic, and possible state topic and values)

Thanks for formatting, I edited your post to also add the config topic.

**Comment by gizmocuz** [comment]
Found the issue, the "brightness_scale" is a string instead of a number....

Could you try beta 15905? Maybe there is also a update for zwavejs-ui
(You are using an old Domoticz version... why so?)

**Comment by catstitan** [comment]
Great, thank you!

The only reason I'm using an older version is that's what was current at the time I did a `docker pull domoticz/domoticz:stable
` and I haven't had any issues until I tried to add the Inovelli bulb. 

I did update to the latest zwavejs-ui but still had the same issue with the bulb.
I pulled `domoticz/domoticz:beta` and it's now working as expected! YAY!

Thanks again.
