### ISSUE TITLE
SBFSpot email flood

### ISSUE THREAD

**Issue by Zuikkis** [domoticz/domoticz#6023]
I have an SMA solar inverter which I have connected with Domoticz using the SBFSpot interface. It has been working fairly well. 

However if there is any active warning or error in the inverter, Domoticz send me an email every five minutes:

2024-02-10 11:10:21.079 Error: Inverter: Invalid field [28] should be OK!

This line is found in hardware/SBFSpot.cpp.

In my opinion the check should be removed completely. At winter time when the solar plant is under snow, it's very common it tries to start but then fails with "unstable operation" which then generates a warning or even error. I have asked SMA and they say this is normal situation. But I get unnecessary email every 5 minutes. :)

If you insist on monitoring the status field, it should be a separate Domoticz device with three states (OK, Warning, Fault).. Then you could easily add email trigger if the state changes.

**Comment by gizmocuz** [comment]
Thanks for reporting. Made a patch, and it is removed in beta 15907
