### ISSUE TITLE
Domoticz Extended create duplicate entry in DeviceStatrus when updating Type, SubType, SwitchType

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#6027]
As described in the forum https://www.domoticz.com/forum/viewtopic.php?p=313962#p313962 there is an issue with the Domoticz Extended framework which doesn't exist with the legacy.

If the plugin try to update Type, SwitchType, SubType, it looks like the Extended framework create a new entry in the DeviceStatus table !

CC: @

Here is the plugin to duplicate the problem

[plugin.py.zip](https://github.com/domoticz/domoticz/files/14270410/plugin.py.zip)

cc: @dnpwwo

**Comment by pipiche38** [comment]
What I found is that Legacy use m_sql.UpdateDeviceValue() while Extended use m_sql.UpdateValue()

**Comment by pipiche38** [comment]
From the source code, looks like there is some comment

```
#ifdef ENABLE_PYTHON
		//TODO: Plugins should perhaps be blocked from implicitly adding a device by update? It's most likely a bug due to updating a removed device..
		if (pHardware != nullptr && pHardware->HwdType == HTYPE_PythonPlugin)
		{
			_log.Debug(DEBUG_NORM, "CSQLHelper::UpdateValueInt: Notifying plugin %u about creation of device %u", HardwareID, unit);
			Plugins::CPlugin* pPlugin = (Plugins::CPlugin*)pHardware;
			pPlugin->DeviceAdded(ID, unit);
		}
#endif

```

**Comment by pipiche38** [comment]
As you can see with the plugin , the problem occurs only when changing the (Type, SubType, SwitchType) to a new value, the plugin is updating back and forth every 30 seconds, in the 2nd round there is no more device added.

So it looks like the DomoticzEx stack beleive that is a new device because the (Type, SubType, SwitchType) has changed to a non existing one !!! Which is not the case when using the Legacy Framework

And I guess when using the native Virtual Devices, we can change Type, Subtype ... without creating a new device !!!

**Comment by gizmocuz** [comment]
Okey, but why change the type/subtype? This should never happen in code by an update, only by a create
And when you created something with a wrong type/subtype, delete the device, so it get's created with the right type/subtype the next time the plugin in launched?

**Comment by pipiche38** [comment]
The use case is linked to native zigbee groups, which depending on the devices attached to the group could change.

Like you get a WWRGB Color device on the group, you then have the corresponding RGB widget. But you add some WW Color bulb to that group. In such case you need to change to WW only.

This was working correctly with the legacy. This is something you can do with device as well by editing , you change a switch in plug , ....

[EDIT] @gizmocuz, deleting and then re-creating a switch for example is making loosing all history. Then if you have some dzVents and other scripting relying on the IDX, they won't work anymore, so it is not a solution, and then that is bringing regression from the legacy version

**Comment by gizmocuz** [comment]
Then you should look at this implementation, as this should not ha eto be done
No issues with MQTT-AD
Domoticz also has its own scene/group functionality that can be used

**Comment by pipiche38** [comment]
I know that Domoticz has own scene/group, but what I'm talking here here is a Zigbee native group. So the Domotciz groups doesn't make sense in that context.

**Comment by gizmocuz** [comment]
There are always more roads to Rome that the one... And what is not possible with the Domoticz scene/groups what is possible with the native zigbee groups?
Sure you can learn a device as activator and control devices from within the scene/group

**Comment by waltervl** [comment]
Native Zigbee groups are far better responsive then Domoticz groups. Also when you have RGB lights you can have color control on the Zigbee group (all lights have the same Color and level) controlled by the Domoticz RGB device representing the native Zigbee group. 
A Domoticz Group can only be switched On/Off (as far as I have experienced). You have to use Domoticz scenes to set lights to a preset c olor/level. So way less flexible then native Zigbee groups.

**Comment by gizmocuz** [comment]
You are able to set the colours…. And even different colors fir different lights
Anyway, its strange to change types and subtypes, and as mentioned not supported
You can use the domoticz groups feature. And for real… how often do you change these?

**Comment by pipiche38** [comment]
why not supported ? We can do it with any virtual device created . 
If this is about not supported by the Python Framework, it worked with the legacy and not the extended framework. So that would be one regression.

As mentioned by @waltervl the Domoticz Group is not Native Zigbee Group. Like you can have 100 Bulb/Led associated to one Zigbee group. When you switch On/Off, change Color ... all Bulbs/Led react at the same time.

**Comment by gizmocuz** [comment]
I think this is now possible thanks to @badzz his PR

**Comment by pipiche38** [comment]
thanks @badzz
