### ISSUE TITLE
Z-Wave MQTT Eurotronics Spirit Thermostatic Valve

### ISSUE THREAD

**Issue by TomHW** [domoticz/domoticz#6029]
Domoticz Version 2024.4 (January 30th 2024)

I'm missing a setpoint for the thermostatic valve. There are two setpoints (cool, heat):
`zwave/Wohnzimmer-Thermostat/thermostat_setpoint/endpoint_0/setpoint/1` bears the heat value.
`zwave/Wohnzimmer-Thermostat/thermostat_setpoint/endpoint_0/setpoint/11` bears the cool value.

`homeassistant/climate/Wohnzimmer-Thermostat/thermostat/config`: MQTT AD seems to use only the cool topic and ignores the heat topic.
`{"min_temp":8,"max_temp":28,"modes":["off","heat","cool"],"mode_state_topic":"zwave/Wohnzimmer-Thermostat/thermostat_mode/endpoint_0/mode","mode_command_topic":"zwave/Wohnzimmer-Thermostat/thermostat_mode/endpoint_0/mode/set","current_temperature_topic":"zwave/Wohnzimmer-Thermostat/sensor_multilevel/endpoint_0/Air_temperature","temp_step":0.5,"current_temperature_template":"{{ value_json.value }}","temperature_state_template":"{{ value_json.value }}","temperature_command_topic":"zwave/Wohnzimmer-Thermostat/thermostat_setpoint/endpoint_0/setpoint/11/set","mode_state_template":"{{ {0: \"off\", 1: \"heat\", 11: \"cool\"}[value_json.value] | default('off') }}","temperature_state_topic":"zwave/Wohnzimmer-Thermostat/thermostat_setpoint/endpoint_0/setpoint/11","temperature_unit":"C","precision":0.1,"device":{"identifiers":["zwavejs2mqtt_0xaaaaaaaa_node9"],"manufacturer":"Eurotronics","model":"Thermostatic Valve (Spirit)","name":"Wohnzimmer-Thermostat","sw_version":"0.16"},"availability":[{"payload_available":"true","payload_not_available":"false","topic":"zwave/Wohnzimmer-Thermostat/status","value_template":"{{'true' if value_json.value else 'false'}}"},{"topic":"zwave/_CLIENTS/ZWAVE_GATEWAY-zwave-js-ui/status","value_template":"{{'online' if value_json.value else 'offline'}}"},{"payload_available":"true","payload_not_available":"false","topic":"zwave/driver/status"}],"availability_mode":"all","name":"Wohnzimmer-Thermostat_thermostat","unique_id":"zwavejs2mqtt_0xaaaaaaaa_Node9_thermostat"}`

**Comment by waltervl** [comment]
This seems to be a ZwaveJSUI issue then? Nothing Domoticz can do about this.....
Did you update to the latest version of Zwave-JS-UI?

**Comment by TomHW** [comment]
In the meantime I'm more experienced with Z-Wave-JS and I detected that the current active Setpoint is mapped to Domoticz. With OpenZwave I was able to change the Setpoints without activating them. But I can live with that behavior, especially because the frame integration means that the Setpoints can also be changed directly in Z-Wave-JS.

**Comment by waltervl** [comment]
Good! For the next time, please use the Domoticz forum first to discuss possible issues. https://www.domoticz.com/forum/index.php

**Comment by TomHW** [comment]
Okay, but I followed the hints from https://www.domoticz.com/wiki/MQTT_AD_Report_Problems. It would be better to place the forum link there.
