### ISSUE TITLE
Javascript JSON API authentication issue

### ISSUE THREAD

**Issue by sjorsjes** [domoticz/domoticz#603]
Hi,

I'm trying to connect to my domoticz using the JSON API. When using the api url in the browser I do get a json result. Unfortunately I am not able to retrieve data from the api using javascript. First I got a CORS errors which can be resolved with using the 'no-cors' mode, but then I get a 401 Unauthorized.

Needles to say I changed the ip and authentication string.

Code example:

```
fetch('http://xx.xxx.xx.xx:xxxx/json.htm?type=devices&filter=all&used=true&order=Name', {
    mode: 'no-cors',
    headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        Authorization: 'Basic xxx'
    }
}).then(function (response) {
    return response.json();
}).then(function (data) {
    console.log(data);
}).catch(function () {
    console.log('error');
});
```

Something seem to be wrong with the API or atleast for using it with JS.

**Comment by gizmocuz** [comment]
Please use our forum

**Comment by sjorsjes** [comment]
Pretty sure it's a bug, but I will give it a go.

**Comment by empierre** [comment]
I'm interrested in the output too as this is quite standard approch

**Comment by sjorsjes** [comment]
Link to the post on the forum: https://www.domoticz.com/forum/viewtopic.php?f=6&t=11516
