### ISSUE TITLE
Issue status switch for Neo TS0601 siren

### ISSUE THREAD

**Issue by blooesky** [domoticz/domoticz#6031]
HI,

I noticed that the NEO TS0601 status does not change in Domoticz for: alarm switch, temperature alarm switch, battery low alarm switch and humidity alarm switch. The buttons works but only to switch ON but cant to switch off because the status doesn"t change in domoticz.

Payload form zigbee2mqtt:
MQTT publish: topic 'zigbee2mqtt/0x842e14fffee55b9c', payload '{"alarm":true,"battery_low":false,"duration":null,"humidity":49,"humidity_alarm":false,"humidity_max":75,"humidity_min":30,"last_seen":"2024-02-17T14:15:13+02:00","linkquality":120,"melody":10,"power_type":"usb","temperature":22,"temperature_alarm":false,"temperature_max":35,"temperature_min":10,"volume":"low"}'

I use domoticz beta 2024.4(build 15910).

Thank you!

**Comment by waltervl** [comment]
What is the config topic for this device?

**Comment by blooesky** [comment]
Hi, I hope I understood what you asked me.. I using domoticz beta 2024.4(build 15910) with MQTT Auto Discovery Client Gateway with LAN interface + zigbee2mqtt 1.35 version + sonoff zigbee 3.0 dongle plus dongle. In zigbee2mqtt dashboard all is fine. Let me know if you need more infos.

**Comment by waltervl** [comment]
This is the way to report MQTT Auto Discovery issues: https://www.domoticz.com/wiki/MQTT_AD_Report_Problems
For MQTT AD the developers need State and Config topics to reproduce your issue. You now only published an incomplete state topic (no topic name).

**Comment by blooesky** [comment]
Switch humidity alarm:

{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/Sirena interior/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/Sirena interior/set/humidity_alarm","device":{"identifiers":["zigbee2mqtt_0x842e14fffee55b9c"],"manufacturer":"Neo","model":"Temperature & humidity sensor and alarm (NAS-AB02B0)","name":"Sirena interior","via_device":"zigbee2mqtt_bridge_0x00124b00256c488c"},"json_attributes_topic":"zigbee2mqtt/Sirena interior","name":"Humidity alarm","object_id":"sirena_interior_humidity_alarm","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"payload_off":"false","payload_on":"true","state_topic":"zigbee2mqtt/Sirena interior","unique_id":"0x842e14fffee55b9c_switch_humidity_alarm_zigbee2mqtt","value_template":"{% if value_json.humidity_alarm %} true {% else %} false {% endif %}"}

Switch temperature alarm:

{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/Sirena interior/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/Sirena interior/set/temperature_alarm","device":{"identifiers":["zigbee2mqtt_0x842e14fffee55b9c"],"manufacturer":"Neo","model":"Temperature & humidity sensor and alarm (NAS-AB02B0)","name":"Sirena interior","via_device":"zigbee2mqtt_bridge_0x00124b00256c488c"},"json_attributes_topic":"zigbee2mqtt/Sirena interior","name":"Temperature alarm","object_id":"sirena_interior_temperature_alarm","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"payload_off":"false","payload_on":"true","state_topic":"zigbee2mqtt/Sirena interior","unique_id":"0x842e14fffee55b9c_switch_temperature_alarm_zigbee2mqtt","value_template":"{% if value_json.temperature_alarm %} true {% else %} false {% endif %}"}

Switch alarm

{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/Sirena interior/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/Sirena interior/set/alarm","device":{"identifiers":["zigbee2mqtt_0x842e14fffee55b9c"],"manufacturer":"Neo","model":"Temperature & humidity sensor and alarm (NAS-AB02B0)","name":"Sirena interior","via_device":"zigbee2mqtt_bridge_0x00124b00256c488c"},"json_attributes_topic":"zigbee2mqtt/Sirena interior","name":"Alarm","object_id":"sirena_interior_alarm","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"payload_off":"false","payload_on":"true","state_topic":"zigbee2mqtt/Sirena interior","unique_id":"0x842e14fffee55b9c_switch_alarm_zigbee2mqtt","value_template":"{% if value_json.alarm %} true {% else %} false {% endif %}"}

**Comment by gizmocuz** [comment]
Cant you edit the switch and enable the auto off function?

**Comment by blooesky** [comment]
I have an option in zigbee2mqtt to set duration(seconds) of alarm, but ideal would be to be able to turn it on and off from domoticz to be able to use events.
