### ISSUE TITLE
update 15889 fail

### ISSUE THREAD

**Issue by JavierIglesias** [domoticz/domoticz#6034]
I have tried this update (15889) multiple times.
The error:

"Error while downloading the Update,
Check your internet connection or try again later!..."

My internet connection is correct.

**Comment by waltervl** [comment]
To test the connection: Are you able to download it from your Domoticz server from here: https://www.domoticz.com/downloads/
What hardware are you using as Rpi armv6 (eg RPi 1 and Zero) is not supported anymore with prebuild versions.

**Comment by JavierIglesias** [comment]
Hello. 

My hardware is "ARMv7 Processor rev 3 (v7l)"

My connection seems to be fine:

root@raspberrypi:~# ping  www.domoticz.com
PING www.domoticz.com (188.114.96.5) 56(84) bytes of data.
64 bytes from 188.114.96.5 (188.114.96.5): icmp_seq=1 ttl=57 time=3.50 ms
64 bytes from 188.114.96.5 (188.114.96.5): icmp_seq=2 ttl=57 time=4.95 ms
64 bytes from 188.114.96.5 (188.114.96.5): icmp_seq=3 ttl=57 time=3.55 ms
....

**Comment by gizmocuz** [comment]
Try issuing the following commands

cd domoticz
./updatebeta

**Comment by JavierIglesias** [comment]
I just did.
Thank you very much!

root@raspberrypi:/home/pi/domoticz# ./updaterelease
Stopping Domoticz...
Making backup of current installation...
ls: no se puede acceder a 'backups/domoticz_backup_*': No existe el fichero o el directorio
Output file: backups/domoticz_backup_20240229_082227.tar.gz
Backup finished...
Downloading latest release version...
Checking file integrity...
Installing new version...
..................................
Starting Domoticz... (please standby...)
Done...

**Comment by waltervl** [comment]
Good, so I close this.
