### ISSUE TITLE
System Alive Checker: Read only sensor when adding delay on device tile

### ISSUE THREAD

**Issue by wvries** [domoticz/domoticz#6037]
Hi,
Current result:
When using the System Alive Checker, it adds a new device (as expected).
When you add a delay in the device tile of than newly created device (for Off delay), the scripts creates errors when a device goes online again (after switched off-line by the script) within the timeframe of the delay.

Note:
Not tested for On delay in device tile and switching device off by script. expecting same issue.

<img width="509" alt="Screenshot 2024-03-10 at 11 40 14" src="https://github.com/domoticz/domoticz/assets/28735118/eb1ce184-d3e4-4cd9-ba93-ce9d71efb14f">
<img width="318" alt="Screenshot 2024-03-10 at 11 41 58" src="https://github.com/domoticz/domoticz/assets/28735118/02719b7e-7947-4f5a-8db2-32d34671d8ca">

Expected result:
When script switches device on (when ping received positive), device switched on without error. 

Environment:
Happens both on stand-alone Domoticz install (Linux Domoticz-Server 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux) as well as on a Docker instance (Docker 25.0.3 on Ubuntu 23.10).
Domoticz stable as well as beta give the same result.

The issue is reproducible in both environments.

**Comment by Olifant1990** [comment]
You don't have to change those settings, let them stay on 0 seconds delay.
If you want to change some timeout settings, go to hardware and press the setup button from the "System Alive Checker".
There select "Wilbert Phone" and change the timeout as you want.

**Comment by waltervl** [comment]
Closing this issue (should be a forum topic in the first place). See also the wiki for instructions on using the System Alive Checker https://www.domoticz.com/wiki/System_Alive_Checker_(Ping)
