### ISSUE TITLE
Python Plugin Signal Strength

### ISSUE THREAD

**Issue by DerekGn** [domoticz/domoticz#6039]
I have implemented a plugin for a set of custom wireless sensors the source code is located here https://github.com/DerekGn/rfmusb-mihome-fsk-plugin

The wireless receiver publishes the RSSI value for the last packet received. The RSSI value have a possible ranges from 0 to -115. 

I am currently running  version [2024.4](https://github.com/domoticz/domoticz/releases/tag/2024.4) on linux SBC
`Linux rock-4se 5.10.110-1-rockchip #0a544b8c7 SMP Sun Mar 12 14:04:06 UTC 2023 aarch64 GNU/Linux`

However in the latest release the signal level has stopped updating in the UI. 

![image](https://github.com/domoticz/domoticz/assets/4487837/456ebd0f-5ca7-49ac-b316-1fb5f57b593d)

The last release that I know the signal strength updates worked was [2023.2](https://github.com/domoticz/domoticz/releases/tag/2023.2)

I checked the values stored in the database and I can see that they are updating, there looks like there is some casting going on from signed to unsigned.

![image](https://github.com/domoticz/domoticz/assets/4487837/a2718537-11bf-41d5-8b03-b93ec762f949)

I also tested hard coding a value for the RSSI -100, 0, 100 but the values are not displayed.

Let me know if I can provide any additional information.

**Comment by waltervl** [comment]
The best way to be supported is to write a very simple plugin that just creates and updates a Domoticz device. A developer can install and test it.

You are using the DomoticzEx plugin framework so that is good.

**Comment by DerekGn** [comment]
I created a simple plugin https://github.com/DerekGn/TestSignalPlugin It sets the signal level to the level on the slider. It also sets the battery level. As one can see from the screen shot the signal level is not displaying.

![image](https://github.com/domoticz/domoticz/assets/4487837/d7a70d20-1354-42c0-8c83-cf203036a587)

**Comment by gizmocuz** [comment]
Could you try a signal level from 1-11, where 12 disables it

**Comment by DerekGn** [comment]
Yep that works. So basically I have to normalize the RSSI value to a 1-11 range. However I am confused as to why it worked before in the older release.

**Comment by gizmocuz** [comment]
Not sure, but I know internally it always worked with 1-11 and 12 disables it. Different for batterij level

**Comment by DerekGn** [comment]
One down sided from the normalization is that its nicer feature to have the real RSSI value, as its easier to determine weaker transmitter etc.

**Comment by DerekGn** [comment]
Version 2023.2 works with RSSI negative values

![image](https://github.com/domoticz/domoticz/assets/4487837/0b123c40-cba6-4c02-b463-e4e0be31965a)

Not working in 2024.4

So was it working in 2023.2 because its a bug and it should not have worked or is it now not working in 2024 as a bug was introduced?

**Comment by gizmocuz** [comment]
I don't think there where any changes to this. But you should be able to find them in the source.

**Comment by DerekGn** [comment]
any pointers on where to start looking?

**Comment by gizmocuz** [comment]
@DerekGn , yeah, in the code... Are you a c++ developer?
