### ISSUE TITLE
libssl.so.1.1 error on bookworm after sudo apt update && sudo apt upgrade -y

### ISSUE THREAD

**Issue by akamming** [domoticz/domoticz#6042]
Hmmm... 

just did another sudo apt update && sudo apt upgrade -y  on my rpi4b.  After it, domoticz no longer started due to this error:

`mrt 22 14:11:56 domoticz domoticz[3833]: /home/domoticz/domoticz/domoticz: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

The info in [this thread](https://www.domoticz.com/forum/viewtopic.php?t=40906) solved it: by manually installing the lib it worked again.  These were the commands to fix it :
```
wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.1n-0+deb11u5_arm64.deb
sudo dpkg -i libssl1.1_1.1.1n-0+deb11u5_arm64.deb

```
However domoticz should work natively on bookworm ofcourse, and since i did not find a reported issue, i decided to create this issue for it...

BTW: if i understand the thread above correctly i have been lucky it worked for this long, and this issue als occurs on armhf

**Comment by gizmocuz** [comment]
I think we will need to force all users to upgrade their system soon.... 

You won't have this issue when using domoticz via docker compose...

**Comment by akamming** [comment]
> I think we will need to force all users to upgrade their system soon....

don't exactly know what you mean by this...
 
> You won't have this issue when using domoticz via docker compose...


yeah probably, but in docker you cannot use gpio unless you run privileged, but that's not what you want in docker.  (although gpio also now also does not work on bookworm, see the other issue i created)

**Comment by gizmocuz** [comment]
Our build systems need to use either libssl 1 or 3

**Comment by waltervl** [comment]
So to summarize: 

1. Our build system can only support libssl 1 or 3
2. The Operating systems that the Domoticz users are using support either libssl 1 or 3 (Out-of-the-Box).
3. It is possible for a user to install libssl1 on a newer OS so it can use Domoticz built with libssl1
4. It is possible to use the Docker install on a newer OS so you do not have the libssl issue.
5. If Domoticz builds are using libssl3 all the users on older OS have to update to the latest OS or install libssl3 (if possible) when they update Domoticz. As the installed base with older OS is still way bigger then the new installations on newer OS it is chosen to sill build with libssl1. There will be a time libssl3 will be used but that has a huge impact on a lot of existing users.

**Comment by akamming** [comment]
But then shoudn’t the domoticz install script be changed to install libssl1? 

Now it doesnt work out of the box on a new raspberry pi

**Comment by waltervl** [comment]
As indicated, use docker. 

But you can also create a PR to update the install script. First check if it needs to be installed and then install it.

**Comment by akamming** [comment]
created the PR: https://github.com/domoticz/domoticz/pull/6049

and pls repoen the issue, it is not fixed.

**Comment by gizmocuz** [comment]
Thanks! PR merged!
