### ISSUE TITLE
Please remove fonts.GoogleApi.com

### ISSUE THREAD

**Issue by Fab8573** [domoticz/domoticz#6043]
Please remove fonts.GoogleApi.com :
1) It's violate GDPR
https://cookie-script.com/blog/google-fonts-and-gdpr
2) Can be slow because need online connection

**Comment by gizmocuz** [comment]
Why is this slow? If you are not online the request will notice very quickly.
Everywhere you browse, there is probably a google font used.
You are more then welcome to make it offline and create a PR for this

**Comment by Fab8573** [comment]
More outside links you have and slower it is. Pure logic....

What is more : 
https://www.webnots.com/fix-slow-page-loading-waiting-fonts-googleapis-com/

**Comment by gizmocuz** [comment]
And then your browser knows this and uses another font
And when the font was already downloaded it should use the cached version

**Comment by Fab8573** [comment]
And it's take time to do it. Say like you want fonts.GoogleApi.com slow page rendering. Read the links I provided.

But the main problem it's violate GDPR. 
"Google also collects the font usage data when a browser initiates an API call to fonts.googlepis.com, googleusercontent.com, or gstatic.com. Each CSS request and font file download is logged by Google and used in the [Google Fonts Analytics](https://fonts.google.com/analytics) site. Google also will find which sites are using their fonts with Google web crawl and uses the data to build a database of sites using Google fonts. So, if you do not want Google to use your site data then disable Google fonts and use generic fonts."
https://www.webnots.com/fix-slow-page-loading-waiting-fonts-googleapis-com/
https://cookie-script.com/blog/google-fonts-and-gdpr

**Comment by gizmocuz** [comment]
I guess you don't use google as search engine?

**Comment by waltervl** [comment]
See also the following closed issue where the usage of Google fonts was discussed. https://github.com/domoticz/domoticz/issues/4320

**Comment by gizmocuz** [comment]
So where is this google font used? As mentioned in my first reply feel free to make a PR

**Comment by waltervl** [comment]
My comment was ment for @Fab8573 to show this topic was discussed before without changes. According @gizmocuz comments in the other issue the Google fonts are used in the high charts library and in the custom frontpage example (that normally is switched off).

**Comment by gizmocuz** [comment]
No reaction received to my previous version, closing issue!
