### ISSUE TITLE
Impossible to disable password protection on a setpoint

### ISSUE THREAD

**Issue by andreapx** [domoticz/domoticz#6047]
I have a setpoint that has the "protected" switch enabled; I can turn off the protection switch and click on update, but when I go back it's still enabled (and it still asks me the password to change the setpoint).
I've tried clearing cache and AppCache, I've even tried on a different browser, but the problem persists.
When I try to disable the protection I don't see anything in the logs (in the UI -> All).

_Version: 2024.4
Build Hash: 731719420
Compile Date: 2024-01-30 09:16:34
dzVents Version: 3.1.8
Python Version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]_

**Comment by gizmocuz** [comment]
Don't have this issue here. Please update to the beta version and test if this is solved

**Comment by waltervl** [comment]
Related forum topic: https://www.domoticz.com/forum/viewtopic.php?t=42178 
Issue seems to be on 1 specific setpoint... The rest is working fine.

**Comment by gizmocuz** [comment]
Seems to be solved magically by itself.... Closing issue
