### ISSUE TITLE
Domoticz main web site access issue

### ISSUE THREAD

**Issue by rajtan** [domoticz/domoticz#6050]
It's not really a code issue. For the lack of access to support page, I am writing here 

For the last few days I am unable to access main web site of domoticz.com from several locations in India.

As it appears that site is using cloudflare services, which inform that there is some issue with the wen server response and it is resulting in error code 520 implying that origin we server is not sending a response (or improper response)

Webmasters may please look into the issues.

**Comment by JurgenLB** [comment]
Duplicate from #6013 and #6026 
They receive a lot off spam so the site is blocked from some countries

**Comment by rajtan** [comment]
Ok, understood. But blocking an entire country does not sound logical. Anyways, thanks for clarification.

**Comment by rajtan** [comment]
Spam is a menace in our digital lives

**Comment by gizmocuz** [comment]
And blocking 100's of IP addresses and maintaining them is a lot more intensive that just blocking a country.... for now...
