### ISSUE TITLE
Virtual thermostat problem

### ISSUE THREAD

**Issue by dwhile** [domoticz/domoticz#6051]
I have a dummy hardware device (for virtual sensors).
I click on create virtual sensor and select Thermostat setpoint.
The sensor is created but then there is no ability to edit it to set temperatures etc. Also the current setpoint is not displayed.
Also clicking on the star to make it favourite it doesn't appear on the dashboard.

Previous version of this worked.

Version: 2024.4 (build 15926)
Build Hash: 8649922fb
Compile Date: 2024-03-29 13:49:10
dzVents Version: 3.1.8
Python Version: 3.12.2 (main, Feb 21 2024, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]

**Comment by gizmocuz** [comment]
It should be available on the utility page.
I just checked, nothing wrong here.
Are you logged in as Administrator? And you have 'no' devices assigned to this account? (Settings->Users->Admin devices)

**Comment by dwhile** [comment]
Ok I did a clean build on a Debian 12 system and all is working as it should so please close this.
I don't know what exactly was wrong but guess it was the build environment got corrupted somehow.
