### ISSUE TITLE
MQTT-AD and sensor index: Usage electric on General kWh

### ISSUE THREAD

**Issue by pikassent** [domoticz/domoticz#6054]
Hello,

**Domoticz:**
Version: 2024.4
Build Hash: 731719420-modified
Compile Date: 2024-01-30 09:16:34
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Mar 23 2024, 16:12:05) [GCC 8.3.0]

**Device:**
[Shelly EM](https://kb.shelly.cloud/knowledge-base/shelly-em) flashed with [Tasmota 11.1.0](https://templates.blakadder.com/shelly_EM.html) added to domoticz using [ShellyTeacher](https://github.com/enesbcs/shellyteacher4domo)   

**Issue:**
Energy usage (power) is not properly updated in Electric (Instant+Counter) device (type 243 - Subtype 29) when channel 2 (index1).
Power usage in channel 1 (index 0) updates both General-kWh devices:

![metro3_cocina](https://github.com/domoticz/domoticz/assets/129661513/b69f3a26-dc39-47cb-a3d9-94036409023a)

![metro3_horn](https://github.com/domoticz/domoticz/assets/129661513/dbf8b46d-965d-4236-b7ef-beff36735146)

**Config Topics and payloads:**

```
_homeassistant/sensor/FCD79D_ENERGY_Total_1/config_
{
  "name": "metro3 ENERGY Total 1",
  "stat_t": "tele/metro3/SENSOR",
  "avty_t": "tele/metro3/LWT",
  "pl_avail": "Online",
  "pl_not_avail": "Offline",
  "uniq_id": "FCD79D_ENERGY_Total_1",
  "dev": {
    "ids": [
      "FCD79D"
    ]
  },
  "unit_of_meas": "kWh",
  "dev_cla": "energy",
  "stat_cla": "total_increasing",
  "frc_upd": true,
  "val_tpl": "{{value_json['ENERGY']['Total'][0]}}"
}

_homeassistant/sensor/FCD79D_ENERGY_Total_2/config_
{
  "name": "metro3 ENERGY Total 2",
  "stat_t": "tele/metro3/SENSOR",
  "avty_t": "tele/metro3/LWT",
  "pl_avail": "Online",
  "pl_not_avail": "Offline",
  "uniq_id": "FCD79D_ENERGY_Total_2",
  "dev": {
    "ids": [
      "FCD79D"
    ]
  },
  "unit_of_meas": "kWh",
  "dev_cla": "energy",
  "stat_cla": "total_increasing",
  "frc_upd": true,
  "val_tpl": "{{value_json['ENERGY']['Total'][1]}}"
}
```

**State topic and payload:**

```
_tele/metro3/SENSOR_
{
  "Time": "2024-04-06T18:59:27",
  "ENERGY": {
    "TotalStartTime": "2023-02-10T18:05:07",
    "Total": [
      40.357,
      124.458
    ],
    "Yesterday": [
      1.142,
      0.445
    ],
    "Today": [
      0,
      0.121
    ],
    "Period": [
      0,
      0
    ],
    "Power": [
      0,
      3
    ],
    "ApparentPower": [
      0,
      7
    ],
    "ReactivePower": [
      0,
      5
    ],
    "Factor": [
      0,
      0.37
    ],
    "Frequency": 50,
    "Voltage": 234,
    "Current": [
      0,
      0.03
    ]
  }
}
```

related with [MQTTAutoDiscover.cpp:1769](https://github.com/domoticz/domoticz/blob/1c8f754985dc0f9055e78f0ce502ed2312c78e05/hardware/MQTTAutoDiscover.cpp#L1769) ?

additional questions are welcome.

**Comment by gizmocuz** [comment]
Could you also post the power configs?

**Comment by pikassent** [comment]
Sure, here you are:

**Channel1:**
```
_homeassistant/sensor/FCD79D_ENERGY_Power_1/config_
{
  "name": "metro3 ENERGY Power 1",
  "stat_t": "tele/metro3/SENSOR",
  "avty_t": "tele/metro3/LWT",
  "pl_avail": "Online",
  "pl_not_avail": "Offline",
  "uniq_id": "FCD79D_ENERGY_Power_1",
  "dev": {
    "ids": [
      "FCD79D"
    ]
  },
  "unit_of_meas": "W",
  "dev_cla": "power",
  "frc_upd": true,
  "val_tpl": "{{value_json['ENERGY']['Power'][0]}}"
}
```
**Channel2:**
```
_homeassistant/sensor/FCD79D_ENERGY_Power_2/config_
{
  "name": "metro3 ENERGY Power 2",
  "stat_t": "tele/metro3/SENSOR",
  "avty_t": "tele/metro3/LWT",
  "pl_avail": "Online",
  "pl_not_avail": "Offline",
  "uniq_id": "FCD79D_ENERGY_Power_2",
  "dev": {
    "ids": [
      "FCD79D"
    ]
  },
  "unit_of_meas": "W",
  "dev_cla": "power",
  "frc_upd": true,
  "val_tpl": "{{value_json['ENERGY']['Power'][1]}}"
}
```
![devices](https://github.com/domoticz/domoticz/assets/129661513/de39187d-c7cd-49ff-9b80-33fdf0438b75)

**Comment by gizmocuz** [comment]
Thanks for the config objects!

Found the issue. The issue is duo the naming of the uniq_id fields

If it is changed like below, it works

"uniq_id": "FCD79D_ENERGY_Total_1" ----> "uniq_id": "FCD79D_ENERGY_1_Total",
"uniq_id": "FCD79D_ENERGY_Total_2" ----> "uniq_id": "FCD79D_ENERGY_2_Total"
"uniq_id": "FCD79D_ENERGY_Power_1" ----> "uniq_id": "FCD79D_ENERGY_1_Power",
"uniq_id": "FCD79D_ENERGY_Power_2" ----> "uniq_id": "FCD79D_ENERGY_2_Power",

(Notice the swap of the number and type)

If you could ask the ShellyTeacher developer to change this and run the script again, it should work

![image](https://github.com/domoticz/domoticz/assets/2265299/8cf43e2e-e910-4643-a52c-2a10225ba96c)

I changed the two power values above from 0->123 and 3->456 for the test

**Comment by waltervl** [comment]
As this will be solved in Shelly Teacher application this can be closed.
