### ISSUE TITLE
Zigbee2MQTT button no longer working

### ISSUE THREAD

**Issue by peteralm097** [domoticz/domoticz#6055]
Since recently the buttons no longer update or get discovered by Domoticz

Buttons Sonof SNZB-01, E1743(Ikea) and E1743(Ikea)

These seem to now be type device_automation with an action attribute

```
{
    "battery": 73,
    "device": {
        "applicationVersion": 5,
        "dateCode": "20201026",
        "friendlyName": "Cave Button",
        "hardwareVersion": 0,
        "ieeeAddr": "0x00124b0022658d1c",
        "manufacturerID": 0,
        "manufacturerName": "eWeLink",
        "model": "SNZB-01",
        "networkAddress": 2848,
        "powerSource": "Battery",
        "type": "EndDevice",
        "zclVersion": 0
    },
    "linkquality": 91,
    "voltage": 2900
}
```

However only the battery attribute is discovered

2024-04-07 12:00:36.164 Status: Zigbee2MQTT: discovered: Cave Button/Cave Button (unique_id: 0x00124b0022658d1c_battery_zigbee2mqtt)

However this is not shown in Domoticz

Previously this was seperated into switches with the action names, now this is not discovered at all. I have lost all functionality with the switches in Domoticz. They still show in zigbee2MQTT UI and I can see them in the AutoDiscovery

zigbee2mqtt-AD/device_automation/0x00124b0022658d1c/action_single/config

```
{
  "automation_type": "trigger",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x00124b0022658d1c"
    ],
    "manufacturer": "SONOFF",
    "model": "Wireless button (SNZB-01)",
    "name": "Cave Button",
    "via_device": "zigbee2mqtt_bridge_0x00124b0024bc2424"
  },
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.36.1",
    "url": "https://www.zigbee2mqtt.io"
  },
  "payload": "single",
  "subtype": "single",
  "topic": "zigbee2mqtt/Cave Button/action",
  "type": "action"
}

```

On latest Domoticz beta

**Comment by gizmocuz** [comment]
Okey, so you updated zigbee2mqtt and now everything is reported as 'device_automation' ?
Why is this? When you go back a version of zigbee2mqtt all is working again?
Did you ask in their forum why this has suddenly changed?
You did not do any configuring?

**Comment by peteralm097** [comment]
Hi

I have been working on this for nearly a week now, trawling through logs - re-pairing, checking their forum, issues and commits but not found anything.
I have moved zigbee2mqtt to a docker and this brought the newer version - I have been experiencing other issues with autodiscovery so this problem was hidden - other domoticz users have been losing connectivity to devices that require a re-publish of homeassistant data to re-associate the device again so this has stopped it being a clear link to 1 change.

Either way my buttons dont work.

I was looking for some guidance on the settings to use in zigbee2mqtt to verify my settings are correct (there are settings for legacy homeassistant api and the like) but I cant find these either,

Please be assured that I didnt just whack this up with little or no thought.

**Comment by gizmocuz** [comment]
In the Domoticz code, the 'device_automation' is explicitly ignored.

I use Zigbee2MQTT in a docker compose container as well, version:

1.36.0-dev commit: [1a9e05e]

The reason it is working here, is that I probably received the configuration as a switch...

Let me work on this one...

**Comment by gizmocuz** [comment]
Could you post here the payload of the following topic when you press a button

zigbee2mqtt/Cave Button/action

**Comment by gizmocuz** [comment]
Maybe it's working already in beta 15933, but some payload to test against would be great

**Comment by peteralm097** [comment]
For zigbee2mqtt/Cave Button
{"action":"single","battery":74,"device":{"applicationVersion":5,"dateCode":"20201026","friendlyName":"Cave Button","hardwareVersion":0,"ieeeAddr":"0x00124b0022658d1c","manufacturerID":0,"manufacturerName":"eWeLink","model":"SNZB-01","networkAddress":2848,"powerSource":"Battery","type":"EndDevice","zclVersion":0},"linkquality":32,"voltage":2900}


For zigbee2mqtt/Cave Button/action

action=single

I have just tried the latest beta - and pressed the button a few times to get it to discover actions...

2024-04-08 18:12:13.349 Status: Zigbee2MQTT: discovered: Cave Button/Cave Button (unique_id: 0x00124b0022658d1c_battery_zigbee2mqtt)
2024-04-08 18:12:13.451 Status: Zigbee2MQTT: discovered: Cave Button/Cave Button (unique_id: 0x00124b0022658d1c_voltage_zigbee2mqtt)
2024-04-08 18:12:13.655 Status: Zigbee2MQTT: discovered: Cave Button (91d6ee68-8791-4dc4-8ab6-312d60cf5afe)/Cave Button (91d6ee68-8791-4dc4-8ab6-312d60cf5afe) (unique_id: 91d6ee68-8791-4dc4-8ab6-312d60cf5afe)
2024-04-08 18:12:13.757 Status: Zigbee2MQTT: discovered: Cave Button (bb7db939-3bed-41d5-b190-2caac35b4ac6)/Cave Button (bb7db939-3bed-41d5-b190-2caac35b4ac6) (unique_id: bb7db939-3bed-41d5-b190-2caac35b4ac6)
2024-04-08 18:12:13.861 Status: Zigbee2MQTT: discovered: Cave Button (0a68b618-1ea4-4a6d-be59-ad5795a1f3a5)/Cave Button (0a68b618-1ea4-4a6d-be59-ad5795a1f3a5) (unique_id: 0a68b618-1ea4-4a6d-be59-ad5795a1f3a5)
2024-04-08 18:13:18.301 Zigbee2MQTT: General/Voltage (Cave Button voltage)
2024-04-08 18:13:18.441 Zigbee2MQTT: Light/Switch/Switch (Cave Button (0a68b618-1ea4-4a6d-be59-ad5795a1f3a5)_single)
2024-04-08 18:13:18.488 Zigbee2MQTT: Light/Switch/Switch (Cave Button (91d6ee68-8791-4dc4-8ab6-312d60cf5afe)_single)
2024-04-08 18:13:18.553 Zigbee2MQTT: Light/Switch/Switch (Cave Button (bb7db939-3bed-41d5-b190-2caac35b4ac6)_single)
2024-04-08 18:13:21.736 Zigbee2MQTT: General/Voltage (Cave Button voltage)
2024-04-08 18:13:21.918 Zigbee2MQTT: Light/Switch/Switch (Cave Button (0a68b618-1ea4-4a6d-be59-ad5795a1f3a5)_double)
2024-04-08 18:13:22.041 Zigbee2MQTT: Light/Switch/Switch (Cave Button (91d6ee68-8791-4dc4-8ab6-312d60cf5afe)_double)
2024-04-08 18:13:22.136 Zigbee2MQTT: Light/Switch/Switch (Cave Button (bb7db939-3bed-41d5-b190-2caac35b4ac6)_double)
2024-04-08 18:13:26.657 Zigbee2MQTT: General/Voltage (Cave Button voltage)
2024-04-08 18:13:26.794 Zigbee2MQTT: Light/Switch/Switch (Cave Button (0a68b618-1ea4-4a6d-be59-ad5795a1f3a5)_long)
2024-04-08 18:13:26.833 Zigbee2MQTT: Light/Switch/Switch (Cave Button (91d6ee68-8791-4dc4-8ab6-312d60cf5afe)_long)
2024-04-08 18:13:26.875 Zigbee2MQTT: Light/Switch/Switch (Cave Button (bb7db939-3bed-41d5-b190-2caac35b4ac6)_long)

**Comment by peteralm097** [comment]
Thank you! 

I have given the latest beta a test and aside from the discovery issue that others seem to  be having that is probably a separate issue, I can now control things with the buttons again!

As you can see from the logs above it looks to create duplicate devices in domoticz.

I really appreciate your help. I will be able to restore functionality to Mrs peteralm097

**Comment by gizmocuz** [comment]
I'm working on a update, as it's not working correctly.
Please stand by....

**Comment by gizmocuz** [comment]
I was able to debug this for some time with JSON and raw payload and think it should work correctly now in beta 15934
You will get new devices for your push buttons, so please remove the old devices created with the previous beta

Please let me know if all is working out for you

**Comment by gizmocuz** [comment]
@peteralm097 , is all working with the latest beta version?

Regarding the non-working/discovered devices, I myself had one, turned out, in MQTT Explorer I was not seeing this device.
So when it's not there, Domoticz does not see it, It's not a Domoticz issue.

But... In Zigbee2MQTT, when you click on the device, and go to settings, I noticed for MQTT QoS it was empty.
I entered 1, and at the bottom I hit submit, and it turned up in MQTT Explorer/Domoticz
Maybe thats the problem?

**Comment by peteralm097** [comment]
Thanks again.

I removed the devices and set QoS which has never been set on my devices.
The following new devices were created
		4180	Zigbee2MQTT	bdd60396-4500-4dd7-88e8-c2958e149458	2	Laser Extraction Button_off	Light/Switch	Switch	Off	-	-	   	2024-04-13 12:52:14
		4178	Zigbee2MQTT	f4a92797-aed8-452a-b09e-f999b6537c51	1	Laser Extraction Button_on	Light/Switch	Switch	On	-	-	   	2024-04-13 12:52:11
		4181	Zigbee2MQTT	f57eac03-190b-46bc-996a-016007cb3d7c	1	Laser Extraction Button	Light/Switch	Switch	On	-	-	   	2024-04-13 12:50:24
		4179	Zigbee2MQTT	614c5da8-2f6e-4c10-b464-899c66ef6037	1	Laser Extraction Button	Light/Switch	Switch	On	-	-	   	2024-04-13 12:50:15

However the id is different to all my other devices (not necessarily a problem) and also the above was taken with the switch in the off state - there seems to be some duplication going on.

The QoS thing may be linked to the other autodiscovery issue being discussed on the forum, where things are not discovered until *any* change is made in Zigbee2mqtt.

I will keep exploring and investigating

**Comment by azsystem** [comment]
> @peteralm097 , is all working with the latest beta version?
> 
> Regarding the non-working/discovered devices, I myself had one, turned out, in MQTT Explorer I was not seeing this device. So when it's not there, Domoticz does not see it, It's not a Domoticz issue.
> 
> But... In Zigbee2MQTT, when you click on the device, and go to settings, I noticed for MQTT QoS it was empty. I entered 1, and at the bottom I hit submit, and it turned up in MQTT Explorer/Domoticz Maybe thats the problem?

Could you try to repeat that, but instead of changing the QoS, change the name of the device?

**Comment by gizmocuz** [comment]
The most important thing is, when you launch MQTT Explorer, you should see your device config object.
If this is not there, of course Domoticz and all other clients won't see it

Back to the original issue 'here', yes you get new id's... that is correct, but they should stay the same.
So each time you press, or double press a button, this button should be updated (see the last seen timestamp) and no new button/switch should be created in domoticz

**Comment by Claude2666** [comment]
I am running Version: 2024.4 (build 15937) Build Hash: cad975ce1.
I have noticed that since this change, Domoticz keeps creating new devices with a different ID. I am trying to find out the sequence which triggers it.  I am currently compiling the latest one. 
E.g Attached a screenshot of a zigbee vibration sensor:

![image](https://github.com/domoticz/domoticz/assets/43413877/6e02a8f8-7664-4108-8bb4-e3dbcca27bf4)
![image](https://github.com/domoticz/domoticz/assets/43413877/905d21fa-76fc-4751-a939-7ee91ad74f3a)


ZigbeeDiscovery/sensor/0x00158d0002c48bbf
## discovery topic
ZigbeeDiscovery/sensor/0x00158d0002c48bbf/action/config1
{"availability":[{"topic":"zigbee2mqtt2/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0002c48bbf"],"manufacturer":"Aqara","model":"Vibration sensor (DJT11LM)","name":"Tilt1","sw_version":"3000-0001","via_device":"zigbee2mqtt_bridge_0x00124b0021cbef09"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","json_attributes_topic":"zigbee2mqtt2/Tilt1","name":"Action","object_id":"tilt1_action","origin":{"name":"Zigbee2MQTT","sw":"1.36.0-dev","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt2/Tilt1","unique_id":"0x00158d0002c48bbf_action_zigbee2mqtt2","value_template":"{{ value_json.action }}"}

## value topic
zigbee2mqtt2/Tilt1
{"action":null,"angle":5,"angle_x":-1,"angle_x_absolute":91,"angle_y":76,"angle_y_absolute":14,"angle_z":14,"battery":90,"device_temperature":25,"linkquality":116,"sensitivity":null,"strength":8,"vibration":false,"voltage":2985,"x_axis":-15,"y_axis":1065,"z_axis":275} 


Update:  It seems that after every restart of Domoticz, new devices are created. 
From the log after startup:
2024-04-19 12:54:03.594 Status: MQTT-ad-Zigbee: Discovered: Tilt1/Tilt1 (unique_id: 0x00158d0002c48bbf_vibration_zigbee2mqtt2)
2024-04-19 12:56:16.729 MQTT-ad-Zigbee: Light/Switch/Switch (Tilt1 action_vibration)
2024-04-19 12:56:17.063 MQTT-ad-Zigbee: Light/Switch/Switch (Tilt1_vibration)
2024-04-19 12:57:46.755 MQTT-ad-Zigbee: Light/Switch/Switch (Tilt1 vibration)


This tilt device is actually a sensor, so it should not be created as a switch.

**Comment by gizmocuz** [comment]
Recent changes have been made for 'device_automation' in this PR and are not related to 'sensor' types (or should not be)
As there are different actions for your sensor, each action should create a new devices/switch, and they should be of type switch (you can/should make it a push-on type, if this was not already the case!)
Then you can use this switch to trigger a scene or group or event

**Comment by Claude2666** [comment]
I understand that, but every time Domoticz is restarted, a new device is created for the same sensor. And only the last created sensor works.

**Comment by gizmocuz** [comment]
Thats not good... This is also a bit strange device
I can totally imagine that you get new values for all the angles (x/y/z)

But the Vibration (on/off) should stay the same like you see in your log:

2024-04-19 12:56:17.063 MQTT-ad-Zigbee: Light/Switch/Switch (Tilt1_vibration)
2024-04-19 12:57:46.755 MQTT-ad-Zigbee: Light/Switch/Switch (Tilt1 vibration)

And the actions might also create different sensors (vibration/tilt/drop)

Are these the only button devices you have? Are those working fine?

Could you use MQTT Explorer and select the node 'zigbee2mqtt2/Tilt1'

When you operate the device, you should see MQTT Explorer logging the values, could you add some more json outputs from this topic?
At the moment you have 'action'=null, and vibration=false

Are there more config objects for this device?

Edit: I ordered this sensor from the Donation money, but it will take a week before it is delivered

**Comment by Claude2666** [comment]
This actually happens to several devices, like Aqara switch (WXKG11LM), cube ([MFKZQ01LM], vibration sensor ([DJT11LM]. I just showed the tilt sensor as an example..
These were the state topics captured in MQTT explorer. (The action null came only 90sec later.)

{"action":"vibration","angle":7,"angle_x":-1,"angle_x_absolute":91,"angle_y":76,"angle_y_absolute":14,"angle_z":14,"battery":90,"device_temperature":26,"linkquality":87,"sensitivity":null,"strength":7,"vibration":true,"voltage":2985,"x_axis":-15,"y_axis":1067,"z_axis":274}

{"action":"","angle":7,"angle_x":-1,"angle_x_absolute":91,"angle_y":76,"angle_y_absolute":14,"angle_z":14,"battery":90,"device_temperature":26,"linkquality":87,"sensitivity":null,"strength":7,"vibration":true,"voltage":2985,"x_axis":-15,"y_axis":1067,"z_axis":274}

{"action":null,"angle":7,"angle_x":-1,"angle_x_absolute":91,"angle_y":76,"angle_y_absolute":14,"angle_z":14,"battery":90,"device_temperature":26,"linkquality":87,"sensitivity":null,"strength":7,"vibration":false,"voltage":2985,"x_axis":-15,"y_axis":1067,"z_axis":274}

{"action":null,"angle":7,"angle_x":-1,"angle_x_absolute":91,"angle_y":76,"angle_y_absolute":14,"angle_z":14,"battery":90,"device_temperature":26,"linkquality":87,"sensitivity":null,"strength":13,"vibration":false,"voltage":2985,"x_axis":-15,"y_axis":1067,"z_axis":274}

{"action":null,"angle":7,"angle_x":-1,"angle_x_absolute":91,"angle_y":76,"angle_y_absolute":14,"angle_z":14,"battery":90,"device_temperature":26,"linkquality":87,"sensitivity":null,"strength":13,"vibration":false,"voltage":2985,"x_axis":-15,"y_axis":1067,"z_axis":274}

This is from the zigbee2mqtt log, with timestamps might be clearer.

info  2024-04-20 11:36:03: MQTT publish: topic 'zigbee2mqtt2/Tilt1', payload '{"action":"vibration","angle":7,"angle_x":-1,"angle_x_absolute":91,"angle_y":76,"angle_y_absolute":14,"angle_z":14,"battery":90,"device_temperature":26,"linkquality":87,"sensitivity":null,"strength":7,"vibration":true,"voltage":2985,"x_axis":-15,"y_axis":1067,"z_axis":274}'
info  2024-04-20 11:36:03: MQTT publish: topic 'zigbee2mqtt2/Tilt1', payload '{"action":"","angle":7,"angle_x":-1,"angle_x_absolute":91,"angle_y":76,"angle_y_absolute":14,"angle_z":14,"battery":90,"device_temperature":26,"linkquality":87,"sensitivity":null,"strength":7,"vibration":true,"voltage":2985,"x_axis":-15,"y_axis":1067,"z_axis":274}'
info  2024-04-20 11:36:03: MQTT publish: topic 'zigbee2mqtt2/Tilt1/action', payload 'vibration'
info  2024-04-20 11:37:33: MQTT publish: topic 'zigbee2mqtt2/Tilt1', payload '{"action":null,"angle":7,"angle_x":-1,"angle_x_absolute":91,"angle_y":76,"angle_y_absolute":14,"angle_z":14,"battery":90,"device_temperature":26,"linkquality":87,"sensitivity":null,"strength":7,"vibration":false,"voltage":2985,"x_axis":-15,"y_axis":1067,"z_axis":274}'
info  2024-04-20 11:40:04: MQTT publish: topic 'zigbee2mqtt2/Tilt1', payload '{"action":null,"angle":7,"angle_x":-1,"angle_x_absolute":91,"angle_y":76,"angle_y_absolute":14,"angle_z":14,"battery":90,"device_temperature":26,"linkquality":87,"sensitivity":null,"strength":13,"vibration":false,"voltage":2985,"x_axis":-15,"y_axis":1067,"z_axis":274}'
cvle@Zigbee2MQTT:/opt/zigbee2mqtt/data/log/2024-04-19.09-50-07$

**Comment by gizmocuz** [comment]
Thank you. I will look into this shortly!

Is it possible to also give me the config and payload (press/release) for the WXKG11LM ?

**Comment by Claude2666** [comment]
Thank you for looking into this. 

Here is the requested info:
Discovery topics of one of my Aqara WXKG11LM switches

ZigbeeDiscovery/sensor/0x00158d000204b2ca/click/config
{"availability":[{"topic":"zigbee2mqtt2/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d000204b2ca"],"manufacturer":"Aqara","model":"Wireless mini switch (WXKG11LM)","name":"SwitchSlaapkamer","sw_version":"3000-0001","via_device":"zigbee2mqtt_bridge_0x00124b0021cbef09"},"icon":"mdi:toggle-switch","json_attributes_topic":"zigbee2mqtt2/SwitchSlaapkamer","name":"Click","object_id":"switchslaapkamer_click","origin":{"name":"Zigbee2MQTT","sw":"1.36.0-dev","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt2/SwitchSlaapkamer","unique_id":"0x00158d000204b2ca_click_zigbee2mqtt2","value_template":"{{ value_json.click }}"}

ZigbeeDiscovery/sensor/0x00158d000204b2ca/action/config
{"availability":[{"topic":"zigbee2mqtt2/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d000204b2ca"],"manufacturer":"Aqara","model":"Wireless mini switch (WXKG11LM)","name":"SwitchSlaapkamer","sw_version":"3000-0001","via_device":"zigbee2mqtt_bridge_0x00124b0021cbef09"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","json_attributes_topic":"zigbee2mqtt2/SwitchSlaapkamer","name":"Action","object_id":"switchslaapkamer_action","origin":{"name":"Zigbee2MQTT","sw":"1.36.0-dev","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt2/SwitchSlaapkamer","unique_id":"0x00158d000204b2ca_action_zigbee2mqtt2","value_template":"{{ value_json.action }}"}

State topic 

zigbee2mqtt2/SwitchSlaapkamer

{"action":"single","battery":100,"click":"single","linkquality":58,"voltage":3045}
{"action":"","battery":100,"click":null,"linkquality":58,"voltage":3045}
{"action":null,"battery":100,"click":"","linkquality":58,"voltage":3045}

From zigbee2mqtt logs

info  2024-04-20 12:09:33: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer', payload '{"action":"single","battery":100,"click":"single","linkquality":58,"voltage":3045}'
info  2024-04-20 12:09:33: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer', payload '{"action":"","battery":100,"click":null,"linkquality":58,"voltage":3045}'
info  2024-04-20 12:09:33: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer', payload '{"action":null,"battery":100,"click":"","linkquality":58,"voltage":3045}'
info  2024-04-20 12:09:33: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer/action', payload 'single'
info  2024-04-20 12:09:33: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer/click', payload 'single'

**Comment by gizmocuz** [comment]
Thanks for all the info, one more request if possible, could you also log a double click, or a long click?

**Comment by Claude2666** [comment]
Long click is not supported but double and triple click are. I have noticed the same issue for my TuYa switch. If needed, I can provide also the info. 
State topic 

zigbee2mqtt2/SwitchSlaapkamer

## double click

{"action":"double","battery":100,"click":"double","linkquality":72,"voltage":3045}
{"action":"","battery":100,"click":null,"linkquality":72,"voltage":3045}
{"action":null,"battery":100,"click":"","linkquality":72,"voltage":3045}

info  2024-04-20 14:24:29: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer', payload '{"action":"double","battery":100,"click":"double","linkquality":72,"voltage":3045}'
info  2024-04-20 14:24:29: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer', payload '{"action":"","battery":100,"click":null,"linkquality":72,"voltage":3045}'
info  2024-04-20 14:24:29: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer', payload '{"action":null,"battery":100,"click":"","linkquality":72,"voltage":3045}'
info  2024-04-20 14:24:29: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer/action', payload 'double'
info  2024-04-20 14:24:29: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer/click', payload 'double'


## triple click
{"action":"triple","battery":100,"click":"triple","linkquality":65,"voltage":3045}
{"action":"","battery":100,"click":null,"linkquality":65,"voltage":3045}
{"action":null,"battery":100,"click":"","linkquality":65,"voltage":3045}

info  2024-04-20 14:27:00: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer', payload '{"action":"triple","battery":100,"click":"triple","linkquality":65,"voltage":3045}'
info  2024-04-20 14:27:00: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer', payload '{"action":"","battery":100,"click":null,"linkquality":65,"voltage":3045}'
info  2024-04-20 14:27:00: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer', payload '{"action":null,"battery":100,"click":"","linkquality":65,"voltage":3045}'
info  2024-04-20 14:27:00: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer/action', payload 'triple'
info  2024-04-20 14:27:00: MQTT publish: topic 'zigbee2mqtt2/SwitchSlaapkamer/click', payload 'triple'

**Comment by gizmocuz** [comment]
@Claude2666 , thanks for this!

Okey with the above switch config and the single,double,trippe payload I do get 3 switches and they update correctly

![image](https://github.com/domoticz/domoticz/assets/2265299/7b5ec5eb-686a-4dc9-bac5-df9f8e3e4a9f)

After a restart en sending the payload, these 3 will stay and update so this is as designed.

Could it be that you also have 

ZigbeeDiscovery/device_automation/xxx/yyy

for these switches?

Ddevice Automation was not implemented (by design) but because of this PR I added support for this.
Maybe because there are both a  device_automation and a sensor type that things get mixed and act crazy

Also please make sure you are on the latest beta version (as of writing this is version 15942 in a few minutes but a version from a few days ago is fine as well)

**Comment by Claude2666** [comment]
@gizmocuz  I am running the latest version 15942.  You are correct, I also have ZigbeeDiscovery/device_automation/xxx/yyy

I upgraded my zigbee2mqtt recently, and I guess it came with that recent release and the recent Domoticz version.  I have several of these device automation entries:


![image](https://github.com/domoticz/domoticz/assets/43413877/cfe86470-4256-459b-884d-44bc513a127b)

So there must be some interworking with device_automation

**Comment by gizmocuz** [comment]
I am thinking about disabling the device_automation again, but just to verify, could you send me the device automation config for

0x00158d000204b2ca

for the action_single, click_single, action_double and click_double

I will then test with these as well

**Comment by Claude2666** [comment]
Here is the requested info 

ZigbeeDiscovery/device_automation/0x00158d000204b2ca/action_single/config
{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x00158d000204b2ca"],"manufacturer":"Xiaomi","model":"Aqara wireless switch (WXKG11LM)","name":"SwitchSlaapkamer","sw_version":"3000-0001"},"payload":"single","subtype":"single","topic":"zigbee2mqtt2/SwitchSlaapkamer/action","type":"action"}

ZigbeeDiscovery/device_automation/0x00158d000204b2ca/click_single/config
{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x00158d000204b2ca"],"manufacturer":"Xiaomi","model":"Aqara wireless switch (WXKG11LM)","name":"SwitchSlaapkamer","sw_version":"3000-0001"},"payload":"single","subtype":"single","topic":"zigbee2mqtt2/SwitchSlaapkamer/click","type":"click"}

ZigbeeDiscovery/device_automation/0x00158d000204b2ca/action_double
{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x00158d000204b2ca"],"manufacturer":"Xiaomi","model":"Aqara wireless switch (WXKG11LM)","name":"SwitchSlaapkamer","sw_version":"3000-0001"},"payload":"double","subtype":"double","topic":"zigbee2mqtt2/SwitchSlaapkamer/action","type":"action"}

ZigbeeDiscovery/device_automation/0x00158d000204b2ca/click_double/config
{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x00158d000204b2ca"],"manufacturer":"Xiaomi","model":"Aqara wireless switch (WXKG11LM)","name":"SwitchSlaapkamer","sw_version":"3000-0001"},"payload":"double","subtype":"double","topic":"zigbee2mqtt2/SwitchSlaapkamer/click","type":"click"}

**Comment by gizmocuz** [comment]
Thanks again!

Yes, I found the issue of the random ID generation. A device_automation has no unique_id field.
This is now generated differently

But... I don't think we need the device_automation at all, and I have disabled this again in beta 15945

Is it possible to test with this version?

The switch generation should now be stable, you can remove these strange random id devices, they should be easy to spot when you look in the 'devices overview' and in the ID. If it does not contain 0x or zigbee2mqtt then it's one of them
(And also check the last update timestamp)

**Comment by gizmocuz** [comment]
@peteralm097, I found the issue with the random ID generation. But I have now disabled the device_automation component again
It should not be needed.
You should have a sensor component or switch/light component as well, and this one should be used
With MQTT Explorer at the top you find a search box, when you enter '124b0022658d1c' you should see multiple config objects and other then device_automation as well

**Comment by Claude2666** [comment]
I just compiled version 15945 and indeed no more extra devices created.  I was already using switch/light component before in scenes as trigger devices, and never had an issue, it keeps working.  
About device_automation, I agree that it is not needed.. After some searching on the internet, it seems that home assistant uses device_automation in their automations.  (to describe what actions/triggers can be expected from the device?) 

Thanks.

**Comment by gizmocuz** [comment]
Thanks for the feedback, and great it's working!!
