### ISSUE TITLE
OpenWeatherMap doesn't add new devices

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#6056]
I add OWM, but i don't see any new devices on the list.

![image](https://github.com/domoticz/domoticz/assets/10205661/c4247264-da3e-451a-a3e2-72e0c272a40f)

**Comment by Stolowka** [comment]
Devices added after "allow for 5 minutes"

**Comment by szczukot** [comment]
Devices added after "allow for 5 minutes"

**Comment by gizmocuz** [comment]
Yes of course, this is with all hardware. Could you please use the forum. This is for code related issues
