### ISSUE TITLE
Custom icons have stoped working for python plugins.

### ISSUE THREAD

**Issue by Smanar** [domoticz/domoticz#6057]
Hello, ATM on version 15937, Images have stopped working on python plugin. Haven't see information about a change on domoticz.
```
            #Custom icon files for battery level
            #https://github.com/999LV/BatteryLevel
            icons = {"batterylevelfull": "icons/batterylevelfull_icons.zip",
                     "batterylevelok": "icons/batterylevelok_icons.zip",
                     "batterylevellow": "icons/batterylevellow_icons.zip",
                     "batterylevelempty": "icons/batterylevelempty_icons.zip"}

            # load custom battery images
            for key, value in icons.items():
                if key not in Images:
                    Domoticz.Image(value).Create()
                    Domoticz.Status("Added icon: " + key + " from file " + value)
            Domoticz.Status("Number of icons loaded = " + str(len(Images)))
            for image in Images:
                Domoticz.Log("Icon Used by the plugin : " + str(Images[image].ID) + ">" + Images[image].Name)
```

On first run.

>  2024-04-17 18:42:32.867 Status: Deconz: Added icon: batterylevelfull from file icons/batterylevelfull_icons.zip
> 2024-04-17 18:42:32.871 Status: Deconz: Added icon: batterylevelok from file icons/batterylevelok_icons.zip
> 2024-04-17 18:42:32.880 Status: Deconz: Added icon: batterylevellow from file icons/batterylevellow_icons.zip
> 2024-04-17 18:42:32.888 Status: Deconz: Added icon: batterylevelempty from file icons/batterylevelempty_icons.zip
> 2024-04-17 18:42:32.888 Status: Deconz: Number of icons loaded = 4 

And all is working on code, but on next restart

>  2024-04-17 18:43:15.427 Status: Deconz: Added icon: batterylevelfull from file icons/batterylevelfull_icons.zip
> 2024-04-17 18:43:15.431 Status: Deconz: Added icon: batterylevelok from file icons/batterylevelok_icons.zip
> 2024-04-17 18:43:15.435 Status: Deconz: Added icon: batterylevellow from file icons/batterylevellow_icons.zip
> 2024-04-17 18:43:15.435 Status: Deconz: Number of icons loaded = 1 

And the code is broken because it can't found icons.
They are still visible if we go in domoticz/more settings/Custom icons, but not possible to see them in pyhon plugin.

**Comment by gizmocuz** [comment]
Please use the forum. There have indeed been no changes related to this

**Comment by Smanar** [comment]
Minimal code to test

```
"""
<plugin key="test_icons" name="test_icons" author="gizmocuz" version="1.0.0" wikilink="http://www.domoticz.com/wiki/plugins/plugin.html" externallink="https://www.google.com/">
    <description>
    </description>
    <params>
    </params>
</plugin>
"""
import Domoticz

class BasePlugin:
    enabled = False
    def __init__(self):
        return

    def onStart(self):
        icons = {"batterylevelfull": "icons/batterylevelfull_icons.zip",
                 "batterylevelok": "icons/batterylevelok_icons.zip",
                 "batterylevellow": "icons/batterylevellow_icons.zip",
                 "batterylevelempty": "icons/batterylevelempty_icons.zip"}

        # load custom battery images
        for key, value in icons.items():
            if key not in Images:
                Domoticz.Image(value).Create()
                Domoticz.Status("Added icon: " + key + " from file " + value)
        Domoticz.Status("Number of icons loaded = " + str(len(Images)))
        for image in Images:
            Domoticz.Status("Icon " + str(Images[image].ID) + " " + Images[image].Name)

global _plugin
_plugin = BasePlugin()

def onStart():
    global _plugin
    _plugin.onStart()
```

For icons can use this folder https://github.com/Smanar/Domoticz-deCONZ/tree/master/icons

Logs on first run, (or if you delete custom icons on domoticz settings)
```
 2024-04-22 18:42:25.248 Status: testtt: Added icon: batterylevellow from file icons/batterylevellow_icons.zip
2024-04-22 18:42:25.250 Status: testtt: Added icon: batterylevelok from file icons/batterylevelok_icons.zip
2024-04-22 18:42:25.251 Status: testtt: Added icon: batterylevelfull from file icons/batterylevelfull_icons.zip
2024-04-22 18:42:25.259 Status: testtt: Added icon: batterylevelempty from file icons/batterylevelempty_icons.zip
2024-04-22 18:42:25.259 Status: testtt: Number of icons loaded = 4
2024-04-22 18:42:25.260 Status: testtt: Icon 102 batterylevelok
2024-04-22 18:42:25.260 Status: testtt: Icon 101 batterylevellow
2024-04-22 18:42:25.260 Status: testtt: Icon 103 batterylevelfull
2024-04-22 18:42:25.260 Status: testtt: Icon 104 batterylevelempty 
```

Logs on second run
```
 2024-04-22 18:42:32.760 Status: testtt: Added icon: batterylevellow from file icons/batterylevellow_icons.zip
2024-04-22 18:42:32.762 Status: testtt: Added icon: batterylevelok from file icons/batterylevelok_icons.zip
2024-04-22 18:42:32.765 Status: testtt: Added icon: batterylevelfull from file icons/batterylevelfull_icons.zip
2024-04-22 18:42:32.765 Status: testtt: Number of icons loaded = 1
2024-04-22 18:42:32.765 Status: testtt: Icon 104 batterylevelempty 
```

**Comment by gizmocuz** [comment]
Thanks for the example! I know where it goes wrong.
(Don't think anyone modified the code in a long time!)

The problem is in PytjonObjects.cpp, line 181 and on...
This only works when the icons where not already there before.

Maybe current python plugin developers removed their icons first... 

But I will rebuild some code, so m_sql.InsertCustomIconFromZipFile will return the ID of the added/updated database entry

**Comment by gizmocuz** [comment]
And why is the returned "Image ID" a value 100 higher then the real ID in the database?

**Comment by gizmocuz** [comment]
And this piece of code in Plugins.cpp looks strange as well

Line 1475

```
			// load associated custom images to make them available to python
			result = m_sql.safe_query("SELECT ID, Base, Name, Description FROM CustomImages WHERE Base LIKE '%q%%' ORDER BY ID ASC", m_PluginKey.c_str());

```

Anyway, I found out why the +100 (and later -100) is hacked in like this... 
(Plugins.cpp, GetCustomIcon)
I would have done this differently but ok...

Should be solved in beta 15949, is it possible to verify this?

**Comment by Smanar** [comment]
It's realy a specific bug, It can't impact lot of users.
I m using buggy code, and have never see it.

>Should be solved in beta 15949, is it possible to verify this?

It's fine ^^, I have just tested the version 15952, no issues.
Thx again.
