### ISSUE TITLE
SetPoint : Device Limits and enhancement

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#6072]
Hello,

Would it be possible to prevent the setpoint modifications that are set as out of range ?
Currently, it is possible to enter manually 80 celsius degrees or -10 and click on the "set" button.
The current verifications when clicking on the arrows are not enough from my point of view.
I think it is equally open/non-protected when coming from Python plugin modifications and probably DZVents...

Even best, would it be possible to have a UI as it looks on google Home (only the circle)?

![image](https://github.com/domoticz/domoticz/assets/35136439/c66b3a02-94a9-4bf1-8f96-c69ba026decb)

Last point, it is more an actionable device than a sensor from my point of view. is there a reason why is it in the "Utility" tab and not in the "switches" tab?

**Comment by gizmocuz** [comment]
It's not a switch and that is why it in the Utility tab.

I just made a commit that now also checks the limits upon setting it via the web gui (beta 15992)

Programming wise, I think this is up to the developer.

Regarding the UI, this will take a lot of room. You can create your own HTML templates for Domoticz

**Comment by rezzalex** [comment]
@gizmocuz , Thanks for the very fast Commit !

for the UI, It could replace the current and be equal size :  
![image](https://github.com/domoticz/domoticz/assets/35136439/1d00f7a6-584e-4d8b-9fdb-870238eb62fa)

but maybe there is technical feasibility contraints ?

**Comment by gizmocuz** [comment]
You can make a PR for this.... I find entering a number quite fast as well ;)
