### ISSUE TITLE
Humidity

### ISSUE THREAD

**Issue by mojso** [domoticz/domoticz#6073]
my proposal is to have a comparison of air humidity between months in years.  as it is for temperature.
![Screenshot_20240507_163030_Chrome](https://github.com/domoticz/domoticz/assets/8018149/d55e0d3f-557a-451f-b85a-950f5ac716d4)

**Comment by gizmocuz** [comment]
Is this a humidity only device? Mine displays a compare chart at the bottom

**Comment by mojso** [comment]
> Is this a humidity only device? Mine displays a compare chart at the bottom
this is a device that shows temperature and humidity, but there is a comparison only for temperature.  it would be good to have such a comparison for humidity as it is for temperature.  as pictured above

**Comment by mojso** [comment]
this is a device that shows temperature and humidity, but there is a comparison only for temperature.  it would be good to have such a comparison for humidity as it is for temperature.  as pictured above


> Is this a humidity only device? Mine displays a compare chart at the bottom

**Comment by gizmocuz** [comment]
Ahh okey, yes this is possible to create and not that complex at all.
Maybe you could make a pull request for this? (And test this!!!)
There is no min/max Humidity, but only the AVG Humidity

In www/app/log/chart-compare-temp.html add a option like

`<option data-i18n="Humidity" value="Humidity">Humidity</option>`

Now you will see the humidity compare chart, but the tooltip unit needs to be changed as well , and also the chart Y axis name

**Comment by mojso** [comment]
I tried like this but I couldn't find anywhere where the table appears

> <div class="chart noselect">
    <div class="chart-title-center">
        <div class="chart-title-container" ng-class="{clickable: chartTitleToggling}">
            <h2 ng-bind-html="chartTitle"></h2>
        </div>
    </div>
    <div class="chartarea">
        <div class="zoom-buttons-container">
            <option data-i18n="Humidity" value="Humidity">Humidity</option>
            <button class="zoom-button" ng-click="groupBy('year')" ng-bind="groupByLabel('y')"></button>
            <button class="zoom-button" ng-click="groupBy('quarter')" ng-bind="groupByLabel('q')"></button>
            <button class="zoom-button" ng-click="groupBy('month')" ng-bind="groupByLabel('m')"></button>
        </div>
        <div class="chartcontainer"></div>
    </div>
</div>

**Comment by gizmocuz** [comment]
Maybe sure you are on the latest beta version / code

**Comment by mojso** [comment]
i have version 15990

> Maybe sure you are on the latest beta version / code

**Comment by gizmocuz** [comment]
That's not the latest version.
