### ISSUE TITLE
MQTT message changes unauthorized device

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#6076]
I have 4 devices that are modified by MQTT. By accident, I only had 3 added to the authorized ones.
But I see that all 4 are changing their value even though one of them is not authorized.

![1](https://github.com/domoticz/domoticz/assets/10205661/f1606f4b-485c-4b66-9600-bd8f304b1dcc)
![2](https://github.com/domoticz/domoticz/assets/10205661/66119b9d-434f-4392-b4b2-aae4e4c90dd0)

**Comment by szczukot** [comment]
I see, that this filter works only for get info about devices. But this is not works for update device.
Was that the intention?
Anyone who has access to the mqtt server can update any device.

For example, when I want change device state by api (json.htm), i need to have this device in the authorized list for the user (exactly this same type of list like on mqtt configuration)

**Comment by gizmocuz** [comment]
Please use our forum. And yes, anyone who has access to your MQTT broker can control anything.
That is why you have secured it and are using TLS of course!

**Comment by szczukot** [comment]
Then at least a description of what the list is would be useful "that it is only for reading data"
And there is no way to turn off reading/sharing. When the list is empty, all devices can be read.

**Comment by gizmocuz** [comment]
There are no unauthorized devices when it comes to external updating (for example via MQTT, Python, Node-Red or API, or even hardware setup)
I have no idea what screen you posted in the first message, but maybe it is the User Device configuration?
This you can use to specify what devices a user may 'see' and/or operate, it has nothing to do with external updating

**Comment by szczukot** [comment]
This screen is from Hardware->MQTT row->Setup
The identical screen is for the user. That's the only place he has access to. And here it means something else. Very inconsistent.

**Comment by gizmocuz** [comment]
Okey, but this list is for devices you want to publish to MQTT, not for reception
So on 1 Domoticz instance you can let it publish 3 temp sensors, and on another you can receive them

**Comment by gizmocuz** [comment]
These days I would suggest using MQTT Auto Discovery is that is possible
