### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by marsys** [domoticz/domoticz#608]
I get a compile error:

/domoticz/hardware/PiFace.cpp: In memberfunctie ‘void CPiFace::AutoCreate_piface_config()’:
/domoticz/hardware/PiFace.cpp:541:5: error: variable-sized object ‘explanation’ may not be initialized
/domoticz/hardware/PiFace.cpp:604:134: let op: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 6 has type ‘int’ [-Wformat]
make[2]: **\* [CMakeFiles/domoticz.dir/hardware/PiFace.cpp.o] Error 1
make[1]: **\* [CMakeFiles/domoticz.dir/all] Error 2
make: **\* [all] Erro 2
Compile failed!

How to resolve this issue?
Regards,
Harry

**Comment by gizmocuz** [comment]
Try a git pull, i think the error is solved now

**Comment by marsys** [comment]
Thanks, everything works OK
