### ISSUE TITLE
Enever: option for plain stock prices

### ISSUE THREAD

**Issue by Nateonas** [domoticz/domoticz#6080]
Stable version: 2024.4 (Raspberry Pi 3)

I am using this plugin to decide whether to locally store, use or deliver electricity. Enever also provides _plain_ stock prices:
... {"datum":"2024-05-12 00:00:00",**"prijs":"0.063000"**,"prijsAA":"0.229080", ...

Choosing this option seems missing in Hardware.html:
\<option value="">Stock prices</option\>

The following conditions may be useful for local electricity storage or usage when using solar panels:
1. negative stock prices: store surplus energy (keeping usage minus solar yield close to zero)
2. negative supplier prices: maximize storage and usage
3. All others: maximize (solar) delivery

It seems not yet possible to trigger on the first condition.

(Also, user variable Enever_Electricity_nn should doesn't seem to be update to Enever_Electricity_tomorrow_nn when updating new prices at 15:00. But, this already seems to be fixed in beta, right?)

**Comment by gizmocuz** [comment]
The uservariable is indeed solved for quite some time in the beta

I am still not sure why you need to have the 'Beursprijs' ?
Firstly, you have a provider, let's assume it is a dynamic contract, else you won't be here at all (enever is all about dynamic contracts)
Also if you do not have a dynamic contract you won't have a negative price

Now, let's assume you have 'Tibber', when the price reported is below 0, it is really below zero

I also can advice to do all this via dzVents

You also know how much your provider adds to the beursprijs, so you can subtract this if needed

**Comment by Nateonas** [comment]
I started working on a dzVents script, but the whole idea of plugins is not needing to use dzVents scripts, especially for novice users, right? And the spotprices are available in the Enever response, so why not provide it? 

But, anyway if you need reasons: the supplier prices are only suitable for Dutch users. Any other users still need the plain spot prices, to calculate their own supplier prices. But even for Dutch users, the supplier prices from enever don't always match. I use Nextenergy and the procurement costs in my contract differ from the current enever prices, so even I cannot use the Nextenergy supplier prices from Enever.

So I think providing the clean spot prices would be an easy and great enhancement. 

If you want to go even further then you could also provide settings for (energytaxes + procurement costs) and VAT for both electricity and gas. My Nexenergy settings would be:

* Electricity: EPEX + energytaxes 2024 + procurement costs + VAT = (EPEX + 0.1088 + 0.01818) * (1 + 21%) €/kWh
* Gas: EGSI + energytaxes 2024 + procurement costs   + VAT = (EGSI + 0.58301 + 0.10628) * (1 + 21%) €/m3
* VAT: 21% (applied on the sum of spot prices, energytaxes and procurement costs)

I invite you to the take a look at the Toon rooted Spotenergy plugin. It retrieves the electricity spot prices directly from entsoe (no request limitations).

https://github.com/ToonSoftwareCollective/spotenergy/blob/main/SpotenergyApp.qml (line 218)

**Comment by gizmocuz** [comment]
@Nateonas , as you maybe can see from the commit history in Domoticz, I was a bit busy lately with other things.
Regarding of stock prices, or prices from 'another' dynamic provider, the 'trend' (up/down) is the same.
It maybe difference by a cent...
And for a battery/charger, it does not matter if the prices are from 'a' provider, as you work with a difference between hour prices anyway.
And yes, we know all about formulas to get to final price that maybe matches your provider.

And again yes, I am also looking/working at Entsoe (as a backup for Enever)

As toon is Dutch, Dutch users can use the Enever as it is.

Anyway, I am a bit busy with other things. It is not that hard to make a PR with the needed changes to support the stock price.
But then the formula is another thing. But please if you have time, by all means, make the changes and make a PR.

And if you are Dutch (which it seems as you also work with 21% tax), there is no need for you to use the raw stock price as the current Enever hardware contains all the dynamic providers

**Comment by Nateonas** [comment]
Hey relax, we're not debating effort here, I don't pay you. :-)
I'm just trying to help identifying a possible enhancement.

**Comment by gizmocuz** [comment]
Just saying, you needed to add 4 lines of code (done in beta 16072)

And for Dutch users there is no need to use the stock options as all providers are already available.

Could you post your entsoe script? I might have a look at this.
Still it could be complicated for end-users to setup as you need a API key and you need to enter your country strings
The Toon implementation is fixed for Dutch users and uses a fixed API key (which could be an issue when entsoe revokes the key, or the owner of this key creates a new key)

**Comment by gizmocuz** [comment]
For reference, these where the changes needed

https://github.com/domoticz/domoticz/commit/23a1c7f72af95ef57573181246aa020e4808096f
