### ISSUE TITLE
LightSwitch/Contact is clickable in floorplan.

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#6081]
On the floorplan, I can click (try cahnge state) for LightSwitch / Switch / Contact.

On tab with switches it is non-clickable (correct)

**Comment by waltervl** [comment]
Please use the forum for these kind of questions or experiences.
In the Tab Lights/Switches you can also click on the device Icon to switch the state (On/Off).
Check if you have any browser cache left of an old Domoticz version.

**Comment by szczukot** [comment]
Hmmm, I don't understand. 
I'm talking about switch type = contact
This is bug. Contact type switch should not be clickable.

**Comment by waltervl** [comment]
You can try to fix function Contact(item) in https://github.com/domoticz/domoticz/blob/development/www/js/domoticzdevices.js
It seems different from function DoorContact(item)

**Comment by szczukot** [comment]
I see this is a bigger problem. 
When I use the default icon, I can't click it. 
When I change the icon, for example to heating, I can click it.

**Comment by waltervl** [comment]
Doorcontact has a special entry for custom icon so perhaps use that part of the code also for normal contact.

**Comment by gizmocuz** [comment]
This is correct, you should not be able to click on a 'contact' type, in the floorplan it displays the log
I changed this in a recent commit, so this won't display the log, and you can hover your mouse over the item to display the popup and select 'log' from here
