### ISSUE TITLE
Error message : " UDP Listen Exception: 'bind: Address already in use"

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#6082]
error message when my alarm is armed : 

`Plugin: UDP Listen Exception: 'bind: Address already in use [system:98 at /usr/local/include/boost/asio/detail/reactive_socket_service.hpp:161 in function 'bind']' connecting to '[239.255.250.250:9131](http://239.255.250.250:9131/)'`

**Comment by waltervl** [comment]
Why is this a Domoticz bug?

**Comment by rezzalex** [comment]
Why wouldn't it be ?

**Comment by waltervl** [comment]
Only report this if you are sure it is a Domoticz bug. Else use the forum to discuss your specific situation.

**Comment by dnpwwo** [comment]
This is not a Domoticz bug @rezzalex, something else on your system is already listening on that broadcast UDP port.

If you are using linux try `sudo netstat -ulp | grep 9131`, that should show you what it is.

**Comment by rezzalex** [comment]
Thanks @dnpwwo , I have indeed 1 DZ plugin (your plugin : Denon) listening to that port, and probably when activating my alarm system, something else prevents it to do so....
I think I need to set "discovery" to false into the plugin conf

sorry for the non bug and thank you and to @waltervl as well
