### ISSUE TITLE
Error in logg "Error: GetJSonDevices: exception occurred : 'stoll'"

### ISSUE THREAD

**Issue by Xavier82** [domoticz/domoticz#6083]
Since the upgrade to beta 2024.4 Build 15992 I get this error:
"Error: GetJSonDevices: exception occurred : 'stoll' in the logging.
The error appears when I press the refresh button in the Setup/Devices tab.

Anyone else with this issue?

**Comment by waltervl** [comment]
I cannot reproduce this on my test environment running  2024.4 Build 15992

**Comment by Xavier82** [comment]
mzzz, ok, will investigate this further.

**Comment by gizmocuz** [comment]
You probably have a device with an invalid svalue

**Comment by gizmocuz** [comment]
The only devices that are using stoll in this function is sTypeCounterIncremental and pTypeRFXMeter.
But I think you already found that out a month ago

**Comment by eekhoorn** [comment]
I have the issue (running 2024.4 build 16081
`2024-07-05 15:06:40.539 Error: GetJSonDevices: exception occurred : 'stoll'
2024-07-05 15:06:40.540 Error: GetJSonDevices: exception occurred : 'stoll'`

BTW. I have these messages when I activate the Hyundai Kia connect plugin.

**Comment by gizmocuz** [comment]
You have an illegal sValue somehow. Probably because you update devices yourself or a plugin.
Above info should be sufficient

**Comment by FilipDem** [comment]
Hi all,
I have the same issue after moving from a 2023 version to the 2024.7 on a raspberry pi.
```
Version: 2024.7
Build Hash: b317cfab1
Compile Date: 2024-07-13 16:59:31
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]
```

The error happens een when the device is created and without any update that happened.
The device creation: 
`Domoticz.Device(Unit=_UNIT_MILEAGE_COUNTER, Name='Mileage (Day)', Type=113, Subtype=0, Switchtype=3, Options={'ValueUnits': 'km'}, Image=Images[_IMAGE].ID, Used=1).Create()`
Wouldn't there be a problem with the initialisation? 

I try to reproduce it on a Ubuntu PC, but there it works... I would assume that the python version would not play a role here.

```
Version: 2024.7
Build Hash: b317cfab1
Compile Date: 2024-07-13 16:59:31
dzVents Version: 3.1.8
Python Version: 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
```

Kr,
F
