### ISSUE TITLE
Week chart disappeard

### ISSUE THREAD

**Issue by guillaumezin** [domoticz/domoticz#6089]
Hello,

I see in this commit:

https://github.com/domoticz/domoticz/commit/8e8f3a58d0600e8b1caddab28e17809f0ad637df

That you removed the week chart. Some users (https://github.com/guillaumezin/DomoticzLinky/issues/238 in french) found this chart quite handy to watch precisely their energy consumption, because it shows the off-peak hours  with colors (see https://github.com/guillaumezin/DomoticzLinky/blob/master/assets/devicelogfr.jpg for instance) and you don't have this details in month view. Could we reintroduce week view? Or add colors detail in month view?

Thank you.

**Comment by gizmocuz** [comment]
Yes this is by design. On the month chart you can press the '1W' option and you have the week view again

**Comment by guillaumezin** [comment]
I understand, but my point is that there is not anymore the usage1/usage2/return1/return2.

**Comment by gizmocuz** [comment]
Ehhhh but you have the same in the month view?

![image](https://github.com/domoticz/domoticz/assets/2265299/caa7116f-c3ca-4b8f-ab5e-9c06719d215a)

**Comment by guillaumezin** [comment]
Agreed, but you can't see usage and return, but cumulative, I mean you can't see anymore which part is usage 1 and usage 2 (off peak hours) for instance using different colors and giving the values when the contextual menu. I can see if I can implement it.

**Comment by gizmocuz** [comment]
Ok, yes it is added together. And it OK like this.

If a user really wants to know how much usage_1 or usage_2, or return_1 or return_2 ... this is very specific, and we have a perfect report for this, press the 'report' button on the top right.

We display what is most important:
- how much we used
- how much we delivered

(And we can now also display the total costs)

There is no need to add anything, usage/delivery is all we need

**Comment by guillaumezin** [comment]
Okay, if this is the way ;-)

**Comment by gizmocuz** [comment]
This is the 'new' way indeed...
Hope it makes sense?
Like whom cares about the difference between return_1 or return_2?
In this case it is weekend or weekdays... there is no return in the night... 
Okey, even when using rain panels, it does not make sense to separate them
If you want to do a deep investigation about how much electricity you use at night (usage_1), it is best to export the report to excel and do the math
For all other 99,999999% of the cases, you really want to know how much you used and how much is returned
