### ISSUE TITLE
Help how to migrate to HTTP v1 from  fcmUrl: https://fcm.googleapis.com/fcm/send

### ISSUE THREAD

**Issue by Feiks** [domoticz/domoticz#6091]
Hi , i got message that Sending messages (including upstream messages) with the FCM XMPP and HTTP legacy APIs was deprecated on June 20, 2023, and will be removed in June 2024. If you are using the legacy FCM send APIs, we strongly recommend that you [migrate to the HTTP v1 API](https://firebase.google.com/docs/cloud-messaging/migrate-v1) or consider using the [Admin SDK](https://firebase.google.com/docs/cloud-messaging/server#choosing-a-server-option) to build send requests.

please help how to migrate , we are using Java Spring Boot application

**Comment by waltervl** [comment]
Already worked on https://github.com/domoticz/domoticz/issues/5921
