### ISSUE TITLE
Session error Enphase / token storing

### ISSUE THREAD

**Issue by fefed22** [domoticz/domoticz#6092]
Hello team, 

i've an issue when i'm trying to login in this URL : https://enlighten.enphaseenergy.com/login/login.json?user%5Bemail%5D=EMAIL&user%5Bpassword%5D=MYPASS
i've an error with : {"message":"Too many active sessions.."}

But no error when i'm generating new token here : https://entrez.enphaseenergy.com/

i'm trying to read file for Enphase Hardware, and i don't understand why we need to do this method : GetOwnerToken ?
https://github.com/domoticz/domoticz/blob/305fec76c244c77ba7a14292cabc4356276bbaeb/hardware/EnphaseAPI.cpp#L765C9-L765C22

The token retrieve from this URL (https://enlighten.enphaseenergy.com) is store in database as : EnphaseToken_XXX

Moreover in wiki we need to generate a token from this URL : https://entrez.enphaseenergy.com/

Why not allowing to save token in hardware form on Domoticz ?
and replace those fields :

**Username:**	
**Password:**

By :

**Your token:**

What do you think about that ?

Best regards.

**Comment by gizmocuz** [comment]
I don't think a message 'too many active sessions' has anything to do with using a token... but I could be wrong...

We have users using firmware version <7 and users using the latest firmware. Both have to work.

When Domoticz retrieved the token, it is storing this internally.
Also, with a restart of the hardware, this token is retrieved internally
Only when the token does not work anymore, a new token is retrieved.

It will also complicate things... users do know their username and password... they don't know about where to generate a token.

**Comment by fefed22** [comment]
Hello, 

the problem is fixed by making a support ticket with enphase.

As i already say in forum : 
`i've explain the problem and a ticket was opened.
So it's a security issue, when we use a third party to make remote call.
After Enphase ticket, they made a small change on my account to allow infinite call.`

Best regards

**Comment by gizmocuz** [comment]
Thanks for the feedback. What is your current poll interval? (30s should work fine without any action from Enphase)

**Comment by fefed22** [comment]
Hello,

yes i've keep 30s.

best regards
