### ISSUE TITLE
Dynamic P1 price expected refresh rate

### ISSUE THREAD

**Issue by fwieringen** [domoticz/domoticz#6094]
Hi,

Have been working with the latest betas the past days. First of all, kudos for the Energy Dashboard. Very cool. Also kudos for the ability to assign a device to the price for electricity and gas. Quite a coincidence that I just implemented two new devices two weeks ago which hold both the electricity and the gas price.

One question: could it be that when using a device as source for prices, you need to have that device updated at least every hour? I have a NodeRed flow which updates both the energy and gas price every day at midnight. When I look at the Energy Dashboard, I now see the total cost of energy this day of 0,08 Euro. This is almost exactly the usage of the time between 0:00 and 1:00.

![image](https://github.com/domoticz/domoticz/assets/4232879/1e2c610a-9f7e-42de-9374-9aa797d10202)

Please let me know how I can help. 

Cheers, Friso

**Comment by gizmocuz** [comment]
Hi Friso, yes that is correct. Where do you get your prices from?
And are they dynamic, do they change every day? (Only) once a day?

In your node red flow, you can put your price in the flows global variable, flow.last_gas_price
Then just make a timer that send the price ever hour to domoticz (or half our), and when you fetch the new price

If you look at the bottom of mainworker.cpp at the function **MainWorker::HandleHourPrice**, you will see that I check if the sensor has no timeout.

**Comment by fwieringen** [comment]
I get them from a local CSV file on my Raspberry Pi where I keep the historic and future rates :-) So no dynamic rates for me. I just wanted to have them in Domoticz so I could have an historical view of the rates.

The rates are already in a global context variable in NodeRed because they are used by other flows as well. I will create a node to push it to Domoticz every 30 mins. Thanks for confirming.

**Comment by gizmocuz** [comment]
Are these prices dynamic? If not, you can also enter them in Domoticz in Setup->Meter

**Comment by fwieringen** [comment]
Nope, no dynamic prices. Next price change will be on September 1st. So that's already added to that CSV file. I just wanted to have that historic view, hence the two added devices in Domoticz. And now I don't have to bother changing the rates on September 1st in Domoticz. This is done automatically :-)

And perhaps in the future I will have a dynamic pricing contract. I just need to change my NodeRed flow then to pull the rates from another source.

**Comment by fwieringen** [comment]
Hmm. Prices are updated every 30 mins as of 11 AM but the Energy Dashboard still remains unchanged.

**Comment by gizmocuz** [comment]
Thanks! Maybe at that time you could use the Enever hardware ;)
Closing this issue
