### ISSUE TITLE
Consumption of electricity and the price of the consumed electricity in the same graph does not look good

### ISSUE THREAD

**Issue by mojso** [domoticz/domoticz#6097]
In my case, the consumption of electricity and the cost of the consumed electricity in the same graph does not look good, because the cost is put in my currency, 1 euro is 61,4 denars.  if the bill is 50 euros in denars, it is 3070 denars.  in the same chart, the cost is very high and the consumed energy is not visible

Perhaps it would be better to have the cost of electricity consumed in a separate graph

![Screenshot_20240616_194338_Chrome](https://github.com/domoticz/domoticz/assets/8018149/4b2147f1-c686-4e84-a6a3-30e168edfe55)
Domoticz Version: 2024.4 (build 16074)

**Comment by gizmocuz** [comment]
@mojso , it is intentional to not see the cost series (spline) in the graph, only on mouse-over.
We can always add it in the same graph at a later stage

Regarding the Euro sign, did you specify your currency symbol in the settings? (Under localisation)

**Comment by waltervl** [comment]
Perhaps have the cost graph be optional (like Trendline and Past Usage)

**Comment by gizmocuz** [comment]
Don't see why this is needed at the moment

**Comment by gizmocuz** [comment]
In the current beta it is now optional, but it does not have it's own Y-Axis yet

**Comment by mojso** [comment]
as shown in the picture.   for example if the cost is 3000 and the consumed energy in Kw is 700kw.  the Kw graph is not visible I have to zoom in to see the energy consumed.   My currency MKD is not in the list.  But I don't think that will change anything in the display in the graph.   the difference in my case is that the cost is in thousand and the consumed energy in KW is in hundred.   For now, this option is turned off for me.

**Comment by gizmocuz** [comment]
That is why it needs its own y-axis

**Comment by gizmocuz** [comment]
New beta 16083 now has its own Y-Axis (on the right)

Is your currentcy symbol 'дени' ? or do you have a one letter symbol ?

**Comment by mojso** [comment]
we do not have a leter symbol for the currency, the abbreviation for the currency is MKD
and the name of the currency is denars ( денари), only the smallest coin is deni ( дени)

**Comment by gizmocuz** [comment]
I added MKD to the list of currencies, and it should be available soon in an upcoming beta

Is this issue solved?

**Comment by mojso** [comment]
i think it's ok now.  the cost and the consumed energy are well shown in the 
graph
maybe just two decimal places would look better in the cost

![Screenshot_20240618_162113_Chrome](https://github.com/domoticz/domoticz/assets/8018149/4120c32e-76b6-40ce-afdb-ab7d28fbe07b)


Thanks, I think the issue is solved

**Comment by gizmocuz** [comment]
I like it to be fore as my provider works with 4 digits... In the report overview I used two digits
Thanks for the feedback, closing issue!
