### ISSUE TITLE
Setpoint device managed correctly, but not updated in the UI

### ISSUE THREAD

**Issue by CreasolTech** [domoticz/domoticz#6098]
Latest Beta version.
If I change the value of a Setpoint device (I've tried with a virtual device and also with a device created/managed by a python plugin), the value changed correctly but the web UI does not. I have to refresh the page to find the new Setpoint value.

To reproduce the bug: create a virtual device, type Setpoint, then from the Utility panel change it's value: the shown value is the same.
Refresh the page, and the setpoint value will be the new one.

Thanks a lot!!

**Comment by gizmocuz** [comment]
Before making an issue, please update to the latest beta version.
Does it still happen in the latest beta version? (also please mention your version)

**Comment by CreasolTech** [comment]
Perfect, with the last version it works like a charme!!!!
