### ISSUE TITLE
Earnings and previous year production mixed up in latest beta

### ISSUE THREAD

**Issue by fwieringen** [domoticz/domoticz#6099]
The latest beta shows the previous year solar production as earnings:

![image](https://github.com/domoticz/domoticz/assets/4232879/d4324886-5e6e-4ada-a83a-fe5f754a4791)

**Comment by gizmocuz** [comment]
Show me the mouse popup... seems strange

**Comment by gizmocuz** [comment]
Also state your version as 'latest beta' is probably not the latest... did you update to the latest? (from this morning? )

**Comment by fwieringen** [comment]
Yes, the latest latest 😉

Version: 2024.4 (build 16078)

![image](https://github.com/domoticz/domoticz/assets/4232879/06ca02e0-cc81-439f-b0c1-502c69f86246)

**Comment by gizmocuz** [comment]
Okey, but does this device already has a previous year? I don't see the previous here ... I just see the Total Generated and pricing

**Comment by fwieringen** [comment]
It has almost three years of history 😉 and that 15.582 euro is the kwh value of 10-06-2023.

**Comment by gizmocuz** [comment]
Hmm that does not seem right... what type of device is this? general/kWh ?

**Comment by fwieringen** [comment]
Correct. A General kWh device. If you want I can share the latest database.

**Comment by gizmocuz** [comment]
Thanks! Should be solved in beta 16079

**Comment by fwieringen** [comment]
![image](https://github.com/domoticz/domoticz/assets/4232879/55f0a17e-6c5b-4955-bce6-d62d791da46d)

Confirmed. Thanks!

**Comment by fwieringen** [comment]
Hmm... now the week stata are gone...

![image](https://github.com/domoticz/domoticz/assets/4232879/fcf13c64-17f9-4b3c-aa25-f46e04f32e8b)
