### ISSUE TITLE
Graph data missing

### ISSUE THREAD

**Issue by hansvanlin** [domoticz/domoticz#6100]
versions:
Version: 2024.4 (build 16074)
Build Hash: fdae03407
Compile Date: 2024-06-16 17:41:27
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]

Graph data missing, probable since price is added to the graph.
![image](https://github.com/domoticz/domoticz/assets/108009649/944990fb-7af9-45e0-82ce-78de616ff9e5)

But not on all data:
![image](https://github.com/domoticz/domoticz/assets/108009649/b45da449-29f5-47da-afdb-fa8a29181677)

**Comment by gizmocuz** [comment]
Did you try the latest beta? (from today)

**Comment by hansvanlin** [comment]
just did and indeed no problem. Did you remove the price from this graph?

Sorry for the inconvenience , please close the issue, it seems not a bug :)
