### ISSUE TITLE
Short term custom graph only shows the last 24 hours

### ISSUE THREAD

**Issue by vinibali** [domoticz/domoticz#6103]
Custom graph with the type of short term (5 minute values) are not showing anything other than the last 24 hours data. Even if I select anything other than the last 24 hours.
* Arch Linux ARM
* Marvell ARMv7 Cortex A9
* Binary build 2024.4 from Github

![Képernyőkép_2024-06-25_06-46-58](https://github.com/domoticz/domoticz/assets/13108545/e250f9c0-9909-4258-b012-6571d12162a2)

**Comment by gizmocuz** [comment]
Please use the forum

**Comment by vinibali** [comment]
Thank you for the hint!
>  Use [setup] [system] [Log History] [Short Log Sensors] to choose 1 - 7 days worth of data in short term log.
[Detailed temperature data for more than 24 hours](https://www.domoticz.com/forum/viewtopic.php?p=209495#p209495)
