### ISSUE TITLE
JSON create device but Switchtype and Options are ignored

### ISSUE THREAD

**Issue by lemassykoi** [domoticz/domoticz#6104]
Hi,

Domoticz 2024.4
Raspberry Pi 3

I'm trying to create some devices with a Python script, with API.

When creating a Dummy Electric Instant + Counter, `devicetype 243` and `subtype 29`, no problem

But I would like to create a Return Device with Energy Read Computed, so I added `Switchtype=4` and Options :

`http://192.168.0.10/json.htm?type=command&param=createdevice&idx=11&sensorname=Extension2&devicetype=243&devicesubtype=29&Switchtype=4&Options={"EnergyMeterMode": "1"}`

but the dummy device is created with Type : Usage instead of Return
And the Energy Read is still From Device.

Any idea ? Thanks.

**Comment by gizmocuz** [comment]
You can use a virtual P1 meter.
But please use the forum. This is not the place to ask questions

https://www.domoticz.com/forum

**Comment by lemassykoi** [comment]
That was not a 'question', but asking for something wich is supposedly working, and which is not, actually.

![image](https://github.com/domoticz/domoticz/assets/16377344/4f73e768-5171-42de-8c4e-3221af60fad4)

from https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's#Create_a_virtual_sensor and 
https://www.domoticz.com/wiki/Developing_a_Python_plugin

I found :
From Stable 2023.2: /json.htm?type=command&param=setused&idx=DEVICE_IDX&name=SENSORNAME&switchtype=SUBTYPE_VALUE&used=true

but no solution for computed

**Comment by gizmocuz** [comment]
Sorry, that was not clear for me...

**Comment by gizmocuz** [comment]
If you open the developer console of your browser and setting the correct parameters for this sensor in the web gui, you should have the exact 'setused' command

**Comment by lemassykoi** [comment]
Fantastic, thank you so much

![image](https://github.com/domoticz/domoticz/assets/16377344/988fd205-3e20-443a-8134-67b753506416)

I can't login to wiki to edit the page

**Comment by gizmocuz** [comment]
If you have a link to the page I can update it

**Comment by gizmocuz** [comment]
I think you can omit the used/customimage fields

**Comment by lemassykoi** [comment]
> If you have a link to the page I can update it

https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's#Create_a_virtual_sensor

end of section :

For Energy Read, if you need Computed, you can update your sensor with :

`/json.htm?type=command&param=setused&idx=DEVICE_IDX&name=SENSORNAME&switchtype=SUBTYPE_VALUE&used=true&EnergyMeterMode=1`

**Comment by gizmocuz** [comment]
Is this also working?

/json.htm?type=command&param=setused&idx=DEVICE_IDX&name=SENSORNAME&switchtype=SUBTYPE_VALUE&EnergyMeterMode=1

But don't you want to see the URL to be working in your first post?

**Comment by lemassykoi** [comment]
To achieve what I want to do, I need 2 steps :

- create sensor : http://192.168.20.100/json.htm?type=command&param=createdevice&idx=11&sensorname=TESTS&devicetype=243&devicesubtype=29

- update sensor : http://192.168.20.100/json.htm?type=command&param=setused&idx=232&name=TESTS&switchtype=4&EnergyMeterMode=1&used=true

I tried without 'used=true' but it produces an error
