### ISSUE TITLE
Domoticz doesn't work with the new raspberry pi camera library

### ISSUE THREAD

**Issue by Growlfy** [domoticz/domoticz#6106]
Domoticz used the old raspberry pi camera library (raspistill, raspivid).

Can you update the code to take into account this new library : https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/camera/rpicam_apps_intro.adoc

Thanks for the job, 
Best Regards

**Comment by gizmocuz** [comment]
Are those two tools not present anymore in bookworm?
When we migrate to bookwork this might need to be done

Only raspistill is used

**Comment by Growlfy** [comment]
As far as i know the raspistill command is not supported yet on raspberry pi OS 64 bits:
https://downloads.raspberrypi.com/raspios_arm64/release_notes.txt
2021-10-30:
* New camera demo applications (libcamera-still and libcamera-vid) have replaced raspistill and raspivid
* 
If only raspistill is used i think we can replace this command by libcamera-still or rpicam-still

Best Regards.

**Comment by gizmocuz** [comment]
Is it possible you could check if this command argument (still) works

libcamera-still -w 800 -h 600 -t 1

Very weird that they call/start an application with the name 'lib'

**Comment by Growlfy** [comment]
The following command works :
licamera-still --width 800 --height 600 -t 1000

libcamera-still -h
Valid options are:
  ...
  --width arg (=0)                      Set the output image width (0 = use default value)
  --height arg (=0)                     Set the output image height (0 = use default value)
  -t [ --timeout ] arg (=5sec)          Time for which program runs. If no units are provided default to ms.
  ...

**Comment by gizmocuz** [comment]
Thanks for testing! Is there also a --output option to export the image to a jpeg?

How about 'rpicam-still' ? is this application natively installed?

https://www.raspberrypi.com/documentation/computers/camera_software.html

**Comment by Growlfy** [comment]
'rpicam-still' is natively installed on pi OS (as it is mention here https://www.raspberrypi.com/documentation/computers/camera_software.html : "Raspberry Pi OS Bookworm renamed the camera capture applications from libcamera-* to rpicam-*. Symbolic links allow users to use the old names for now. Adopt the new application names as soon as possible.")
https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit

I tested those commands this morning, and they work with -o test.jpg

Here are all the options for rpicam-still :
Valid options are:
  -h [ --help ] [=arg(=1)] (=0)         Print this help message
  --version [=arg(=1)] (=0)             Displays the build version number
  --list-cameras [=arg(=1)] (=0)        Lists the available cameras attached to                                      the system.
  --camera arg (=0)                     Chooses the camera to use. To list the a                                     vailable indexes, use the
                                        --list-cameras option.
  -v [ --verbose ] [=arg(=2)] (=1)      Set verbosity level. Level 0 is no outpu                                     t, 1 is default, 2 is verbose.
  -c [ --config ] [=arg(=config.txt)]   Read the options from a file. If no file                                     name is specified, default to
                                        config.txt. In case of duplicate options                                     , the ones provided on the command line
                                        will be used. Note that the config file                                      must only contain the long form
                                        options.
  --info-text arg (=#%frame (%fps fps) exp %exp ag %ag dg %dg)
                                        Sets the information string on the title                                     bar. Available values:
                                        %frame (frame number)
                                        %fps (framerate)
                                        %exp (shutter speed)
                                        %ag (analogue gain)
                                        %dg (digital gain)
                                        %rg (red colour gain)
                                        %bg (blue colour gain)
                                        %focus (focus FoM value)
                                        %aelock (AE locked status)
                                        %lp (lens position, if known)
                                        %afstate (AF state, if supported)
  --width arg (=0)                      Set the output image width (0 = use defa                                     ult value)
  --height arg (=0)                     Set the output image height (0 = use def                                     ault value)
  -t [ --timeout ] arg (=5sec)          Time for which program runs. If no units                                      are provided default to ms.
  -o [ --output ] arg                   Set the output file name
  --post-process-file arg               Set the file name for configuring the po                                     st-processing
  --post-process-libs arg               Set a custom location for the post-proce                                     ssing library .so files
  -n [ --nopreview ] [=arg(=1)] (=0)    Do not show a preview window
  -p [ --preview ] arg (=0,0,0,0)       Set the preview window dimensions, given                                      as x,y,width,height e.g. 0,0,640,480
  -f [ --fullscreen ] [=arg(=1)] (=0)   Use a fullscreen preview window
  --qt-preview [=arg(=1)] (=0)          Use Qt-based preview window (WARNING: ca                                     uses heavy CPU load, fullscreen not
                                        supported)
  --hflip [=arg(=1)] (=0)               Request a horizontal flip transform
  --vflip [=arg(=1)] (=0)               Request a vertical flip transform
  --rotation arg (=0)                   Request an image rotation, 0 or 180
  --roi arg (=0,0,0,0)                  Set region of interest (digital zoom) e.                                     g. 0.25,0.25,0.5,0.5
  --shutter arg (=0)                    Set a fixed shutter speed. If no units a                                     re provided default to us
  --analoggain arg (=0)                 Set a fixed gain value (synonym for 'gai                                     n' option)
  --gain arg                            Set a fixed gain value
  --metering arg (=centre)              Set the metering mode (centre, spot, ave                                     rage, custom)
  --exposure arg (=normal)              Set the exposure mode (normal, sport)
  --ev arg (=0)                         Set the EV exposure compensation, where                                      0 = no change
  --awb arg (=auto)                     Set the AWB mode (auto, incandescent, tu                                     ngsten, fluorescent, indoor, daylight,
                                        cloudy, custom)
  --awbgains arg (=0,0)                 Set explict red and blue gains (disable                                      the automatic AWB algorithm)
  --flush [=arg(=1)] (=0)               Flush output data as soon as possible
  --wrap arg (=0)                       When writing multiple output files, rese                                     t the counter when it reaches this
                                        number
  --brightness arg (=0)                 Adjust the brightness of the output imag                                     es, in the range -1.0 to 1.0
  --contrast arg (=1)                   Adjust the contrast of the output image,                                      where 1.0 = normal contrast
  --saturation arg (=1)                 Adjust the colour saturation of the outp                                     ut, where 1.0 = normal and 0.0 =
                                        greyscale
  --sharpness arg (=1)                  Adjust the sharpness of the output image                                     , where 1.0 = normal sharpening
  --framerate arg (=-1)                 Set the fixed framerate for preview and                                      video modes
  --denoise arg (=auto)                 Sets the Denoise operating mode: auto, o                                     ff, cdn_off, cdn_fast, cdn_hq
  --viewfinder-width arg (=0)           Width of viewfinder frames from the came                                     ra (distinct from the preview window
                                        size
  --viewfinder-height arg (=0)          Height of viewfinder frames from the cam                                     era (distinct from the preview window
                                        size)
  --tuning-file arg (=-)                Name of camera tuning file to use, omit                                      this option for libcamera default
                                        behaviour
  --lores-width arg (=0)                Width of low resolution frames (use 0 to                                      omit low resolution stream
  --lores-height arg (=0)               Height of low resolution frames (use 0 t                                     o omit low resolution stream
  --mode arg                            Camera mode as W:H:bit-depth:packing, wh                                     ere packing is P (packed) or U
                                        (unpacked)
  --viewfinder-mode arg                 Camera mode for preview as W:H:bit-depth                                     :packing, where packing is P (packed)
                                        or U (unpacked)
  --buffer-count arg (=0)               Number of in-flight requests (and buffer                                     s) configured for video, raw, and
                                        still.
  --viewfinder-buffer-count arg (=0)    Number of in-flight requests (and buffer                                     s) configured for preview window.
  --no-raw [=arg(=1)] (=0)              Disable requesting of a RAW stream. Will                                      override any manual mode reqest the
                                        mode choice when setting framerate.
  --autofocus-mode arg (=default)       Control to set the mode of the AF (autof                                     ocus) algorithm.(manual, auto,
                                        continuous)
  --autofocus-range arg (=normal)       Set the range of focus distances that is                                      scanned.(normal, macro, full)
  --autofocus-speed arg (=normal)       Control that determines whether the AF a                                     lgorithm is to move the lens as quickly
                                        as possible or more steadily.(normal, fa                                     st)
  --autofocus-window arg (=0,0,0,0)     Sets AfMetering to  AfMeteringWindows an                                      set region used, e.g.
                                        0.25,0.25,0.5,0.5
  --lens-position arg                   Set the lens to a particular focus posit                                     ion, expressed as a reciprocal distance
                                        (0 moves the lens to infinity), or "defa                                     ult" for the hyperfocal distance
  --hdr [=arg(=auto)] (=off)            Enable High Dynamic Range, where support                                     ed. Available values are "off", "auto",
                                        "sensor" for sensor HDR (e.g. for Camera                                      Module 3), "single-exp" for PiSP based
                                        single exposure multiframe HDR
  --metadata arg                        Save captured image metadata to a file o                                     r "-" for stdout
  --metadata-format arg (=json)         Format to save the metadata in, either t                                     xt or json (requires --metadata)
  --flicker-period arg (=0s)            Manual flicker correction period
                                        Set to 10000us to cancel 50Hz flicker.
                                        Set to 8333us to cancel 60Hz flicker.

  -q [ --quality ] arg (=93)            Set the JPEG quality parameter
  -x [ --exif ] arg                     Add these extra EXIF tags to the output                                      file
  --timelapse arg (=0ms)                Time interval between timelapse captures                                     . If no units are provided default to
                                        ms.
  --framestart arg (=0)                 Initial frame counter value for timelaps                                     e captures
  --datetime [=arg(=1)] (=0)            Use date format for output file names
  --timestamp [=arg(=1)] (=0)           Use system timestamps for output file na                                     mes
  --restart arg (=0)                    Set JPEG restart interval
  -k [ --keypress ] [=arg(=1)] (=0)     Perform capture when ENTER pressed
  -s [ --signal ] [=arg(=1)] (=0)       Perform capture when signal received
  --thumb arg (=320:240:70)             Set thumbnail parameters as width:height                                     :quality, or none
  -e [ --encoding ] arg (=jpg)          Set the desired output encoding, either                                      jpg, png, rgb/rgb24, rgb48, bmp or
                                        yuv420
  -r [ --raw ] [=arg(=1)] (=0)          Also save raw file in DNG format
  --latest arg                          Create a symbolic link with this name to                                      most recent saved file
  --immediate [=arg(=1)] (=0)           Perform first capture immediately, with                                      no preview phase
  --autofocus-on-capture [=arg(=1)] (=0)
                                        Switch to AfModeAuto and trigger a scan                                      just before capturing a still
  --zsl [=arg(=1)] (=0)                 Switch to AfModeAuto and trigger a scan                                      just before capturing a still

**Comment by gizmocuz** [comment]
Thanks for the output. 'rpicam-still' it was we need
Too bad they changed the timing and width/height parameters, than it would just a a simple replacement

**Comment by waltervl** [comment]
Solved with https://github.com/domoticz/domoticz/commit/671804ea56db4cddfa3c6913597c4f2e8cd06061 or still work in progress?

**Comment by kiddigital** [comment]
@waltervl , seems resolved as the code is already available in the current Beta.

Maybe @Growlfy can test, confirm and close this issue?

**Comment by Growlfy** [comment]
@kiddigital @waltervl @gizmocuz: I'm sorry, but I'm not able to compile Domoticz to check it. By the way, the code probably solves the issue.

**Comment by waltervl** [comment]
@Growlfy for a RPi you can update to latest beta with 
sudo ./updatebeta 
in a terminal window.
Or in menu setup - settings switch to beta channel, save settings and update from menu setup -check for update

**Comment by Growlfy** [comment]
Ok update is done : 2024.4 beta (build 16115).
If it's the good beta build i still can't access to the raspberry camera from domoticz.
Nevertheless this command : "rpicam-still --width 800 --height 600 -t 1000 -o test.jpg" works fine in my terminal.

**Comment by gizmocuz** [comment]
@Growlfy , what have you entered under Setup->Other->Raspberry Pi Camera Parameters ?
This should be --width 800 --height 600 -t 1000

**Comment by Growlfy** [comment]
@gizmocuz I'm already using these settings : --width 800 --height 600 -t 1000 in Setup->Other->Raspberry Pi Camera Parameters.
Edit : the camera work with this fix, but  i can't see video streaming in the edit menu of the camera.
Does domoticz use the raspivid command to stream the camera video?

**Comment by gizmocuz** [comment]
If your capture url is ending with 'raspberry.cgi' it should work...
If it is ending with 'uvccapture.cgi' it is using another command (uvccapture)

**Comment by Growlfy** [comment]
Only  video streaming in the camera edit menu is not working

**Comment by Growlfy** [comment]
![cam](https://github.com/domoticz/domoticz/assets/82908753/df26dca1-26bf-4c7c-b23d-94cdccb43831)
raspicam is working fine as you can see in the image but i can't access to the test image in the config menu.

**Comment by gizmocuz** [comment]
Is it possible to open your browsers developers console (function key F12), dock this to the bottom for a better view, and select the network tab. If you press the test button, do you see if it tries to call Domoticz and what address/url is being called for the cam image?

**Comment by Growlfy** [comment]
Here is the answer :  NS_ERROR_CONNECTION_REFUSED

await fetch("http://localhost/raspberry.cgi", {
    "credentials": "omit",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0",
        "Accept": "image/avif,image/webp,*/*",
        "Accept-Language": "fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3",
        "Sec-Fetch-Dest": "image",
        "Sec-Fetch-Mode": "no-cors",
        "Sec-Fetch-Site": "cross-site",
        "Sec-GPC": "1",
        "Priority": "u=1"
    },
    "referrer": "http://192.168.1.73:8080/",
    "method": "GET",
    "mode": "cors"
});

attr
[http://192.168.1.73:8080/js/jquery-3.6.0.min.js:2:65761](http://192.168.1.73:8080/js/jquery-3.6.0.min.js)
$
[http://192.168.1.73:8080/js/jquery-3.6.0.min.js:2:32508](http://192.168.1.73:8080/js/jquery-3.6.0.min.js)
attr
[http://192.168.1.73:8080/js/jquery-3.6.0.min.js:2:65332](http://192.168.1.73:8080/js/jquery-3.6.0.min.js)
TestCamFeed
[http://192.168.1.73:8080/:181:41](http://192.168.1.73:8080/#/Cam%20line%202%20%3E%20injectedScript)
onclick
[http://192.168.1.73:8080/:1:1](http://192.168.1.73:8080/#/Cam)

**Comment by gizmocuz** [comment]
okey, maybe the url that works is

http://192.168.1.73:8080/raspberry.cgi

You need to add a port number?

**Comment by Growlfy** [comment]
I have tried out different patterns with or without port (80, 8080, empty), ip as localhost, 192.168.1.73, with or without id, password finally the most simple things works (i probably forget something during my first try) : 
HTTP
192.168.1.73
8080
my id
my password
raspberry.cgi

Issue Solved
Thanks @gizmocuz 

PS : i saw some missing french translations in that file domoticz-fr.json.gz, so i can help to translate but i don't know how to do it. I already edit the domoticz-fr.json file to update missing french how can i send it to github?

**Comment by gizmocuz** [comment]
Great it's working!
We work with Transifex for translation

https://app.transifex.com/domoticz/domoticz/dashboard/
