### ISSUE TITLE
EnergyDashboard is not centered and hard to read on mobile browser

### ISSUE THREAD

**Issue by hansvanlin** [domoticz/domoticz#6107]
On my mobile I see that the dashboard is shifted to the right.
And is it hard to read. There is still some room to display it a bit bigger.
See the attached images:
![image_2024-06-30_120332763](https://github.com/domoticz/domoticz/assets/108009649/2dddeea5-438e-49c8-b597-88900d1a7092)
![image_2024-06-30_120401690](https://github.com/domoticz/domoticz/assets/108009649/a4db2db6-b5ef-4d77-833b-797319573b0b)

**Comment by gizmocuz** [comment]
You can tilt your screen and use your fingers to zoom
This is not a screen for a mobile device
