### ISSUE TITLE
Pilot wire device Legrand

### ISSUE THREAD

**Issue by JoParisFR** [domoticz/domoticz#6109]
I have a system with 30 devices.
11 devices are some Fip device for electric radiators.
From 2021, i was on an old Domoticz version, on a RPI3, and a Zigate.
The whole system worked very very very well.
Gradualy, I replace the Fip Schnedeir (EER 50000), with cable outlet Legrand.
The system worked very well, until the 7th Legrand.
Few days after installing the 7th Legrand, all the radiators swicth device went red, the Legrand and the Scneider devices.
I thought the version was too old.
I change for a RPI4, docker, Domoticz, Sonoff key, Zigbee2mqtt and mosquitto.
Then I put the 30 devices back.
After two weeks, when I try to activate the radiators by Comfort or Eco, or any other, the response is "Error sending switch command, check device/hardware (idx=87) !"
When I activate the radiator directly via Zigbee2Mqtt it works.
I understand that the problem I encountered on the old version reoccurs on this version.
Have you an idea ?

**Comment by waltervl** [comment]
Please use the forum as it is not sure this is a Domoticz software error. Could be a lot of other things going wrong here.
