### ISSUE TITLE
Shelly Motion 2

### ISSUE THREAD

**Issue by Linky13860** [domoticz/domoticz#6112]
Raspberry
Domoticz Version: 2024.4
Build Hash: 731719420
Compile Date: 2024-01-30 09:16:34
dzVents Version: 3.1.8
ShellyTeacher 4 Domoticz latest commit february

I installed a shelly motion 2 under _MQTT auto discovery client gateway with lan interface_ and **it works**....
But (the famous but) except for the battery device.

Another DIY device uses _MQTT client gateway with lan interface_ and I see that Shelly motion battery appear in the device list. Selected or not, no values are transmitted to the battery domoticz device

We can see MQTT Explorer values 

shellies/shellymotion2-588E81A42833

{"wifi_sta":{"connected":true,"ssid":"wata_2013_2GEXT","ip":"192.168.2.57","rssi":-71},"cloud":{"enabled":true,"connected":true},"mqtt":{"connected":true},"time":"16:43","unixtime":1720449781,"serial":375,"has_update":false,"mac":"588E81A42833","cfg_changed_cnt":5,"actions_stats":{"skipped":0},"sleep_time":0,"lux":{"value":21671,"illumination":"bright","is_valid":true},"tmp":{"value":37.9,"units":"C","is_valid":true},"sensor":{"vibration":false,"motion":false,"timestamp":1720437261,"active":true,"is_valid":true},"bat":{"value":97,"voltage":3.833},"charger":false,"update":{"status":"unknown","has_update":false,"new_version":"20240619-130804/v2.2.4@ee290818","old_version":"20240619-130804/v2.2.4@ee290818","beta_version":null},"ram_total":97280,"ram_free":22208,"fs_size":65536,"fs_free":59468,"uptime":669701,"fw_info":{"device":"shellymotion2-588E81A42833","fw":"20240619-130804/v2.2.4@ee290818"},"ps_mode":0,"dbg_flags":0}

A idea ?

Philippe

**Comment by waltervl** [comment]
Please check it with the ShellyTeacher 4 Domoticz team. This is not a Domoticz issue.
