### ISSUE TITLE
Z-Wave JS UI:  AEON Water Sensor not working properly

### ISSUE THREAD

**Issue by sundansx** [domoticz/domoticz#6113]
Domoticz
- Version: 2024.4 (build 16092)
- Build Hash: 5abc02285
- Compile Date: 2024-06-20 02:44:18

zwave-js-ui: 9.14.2
- zwave-js: 12.11.2
- home id: 3546616848
- home hex: 0xd3651410

device:  
- AEON Labs  Water Sensor DSB45

On Zwave JSUI the water sensor presents a "[72-32-0-currentValue] Current value".  I also see this in the Mosquitto interface as shown.  On this sensor when water is present that value goes from 0 to 255.  No other values change.  Domoticz  presents a bunch of config devices and an "any" and "battery_is_low" devices, but no "Current value".  How would one fix this?  Is this a domoticz bug?

searching for _72:
![image](https://github.com/domoticz/domoticz/assets/25075847/0685b500-e625-4492-9049-986ca45ac5d4)

showing values while in water in zwaveJSUI:
![image](https://github.com/domoticz/domoticz/assets/25075847/663f1414-4276-4f29-989f-d46216c5ce40)

in mqtt explorer:
![image](https://github.com/domoticz/domoticz/assets/25075847/15b733be-e067-4fbe-89d3-8515f0cc8932)

**Comment by gizmocuz** [comment]
Okey, this is a simple water leak sensor. It has no real value, it detects a water leak or not.
I do see a switch that is 'On' in the devices tab, that is not the switch that turns on when a water leak is detected and tuns off when it is not detected anymore?
If there is no switch with this indication, could you please follow this guide and post the requested information here:

https://www.domoticz.com/wiki/MQTT_AD_Report_Problems

**Comment by sundansx** [comment]
Hmm, I think I see the problem.  ZwaveJSUI is not publishing that sensor value under the "Homeassistant"->"binary sensor" value?  So Domodictz does not add that device?

**Comment by gizmocuz** [comment]
Incorrect, we handle binary sensors so please follow the above guide if you don't see a switch that represents the detection state

**Comment by sundansx** [comment]
Correct, that "On" value does not change when a leak is detected.  That is a config setting for this:
![image](https://github.com/domoticz/domoticz/assets/25075847/2f8d62c5-9c88-4bef-8154-e2bd61682cac)

**Comment by gizmocuz** [comment]
What's with the 'HouseWaterHeteaterOLD' device? This seems the one?

Anyway, please follow the above guide (post the config topic+payload for the correct binary sensor), as well as the state topic+payload then there is water detected and when not. With this we should be able to reproduce it

**Comment by sundansx** [comment]
that is some the sensor state as per zwavejsui, but does not change with water present.  Am getting payloads now...

**Comment by sundansx** [comment]
![image](https://github.com/domoticz/domoticz/assets/25075847/49893a29-b2e9-42c4-8638-0cfe796ed287)

there are many topics...which one or all?

**Comment by sundansx** [comment]
there is no topic in the domoWebserver/HomeAssistant (I made my one topic) for the "currentValue" with payload.

**Comment by sundansx** [comment]
Ah, here may be the root of the problem:

![image](https://github.com/domoticz/domoticz/assets/25075847/4af1f803-21d1-43cf-ae44-014bbb9d74d5)

**Comment by gizmocuz** [comment]
Only the one representing the leakage state please.

You should be able to find this in the manual of the device, maybe it is 72-48-0 ? which represents the switch you renamed to OLD i mentioned before...
Which is under 'binary_sensor'

**Comment by gizmocuz** [comment]
Also remember that all your configs need to be persistent (which is the default behaviour)

**Comment by sundansx** [comment]
found the manual, Aeon manuals suck.  no info about leak state device numbering or anything about what registers do what.
I renamed that to OLD, as I was trying to get it to auto add the "current value" after tripping the water switch a few times.  did not happen, and I don't expect it to as it is not in the list of autodiscover topics on ZwaveJSUI.  This is looking like a ZwaveJSUI bug...

**Comment by sundansx** [comment]
here is the 72-48-0 payload in case it is useful:
`{"payload_on":true,"payload_off":false,"value_template":"{{ value_json.value }}","state_topic":"zwaveW/72/48/0/Any","availability":[{"payload_available":"true","payload_not_available":"false","topic":"zwaveW/72/status","value_template":"{{'true' if value_json.value else 'false'}}"},{"topic":"zwaveW/_CLIENTS/ZWAVE_GATEWAY-zwave-js-ui/status","value_template":"{{'online' if value_json.value else 'offline'}}"},{"payload_available":"true","payload_not_available":"false","topic":"zwaveW/driver/status"}],"availability_mode":"all","json_attributes_topic":"zwaveW/72/48/0/Any","device":{"identifiers":["zwavejs2mqtt_0xd3651410_node72"],"manufacturer":"AEON Labs","model":"Water Sensor (DSB45)","name":"nodeID_72","sw_version":"1.5"},"name":"nodeID_72_any","unique_id":"zwavejs2mqtt_0xd3651410_72-48-0-Any"}`

**Comment by sundansx** [comment]
Update:
I changed this value in the ZwaveJSUI interface to "enable"
![image](https://github.com/domoticz/domoticz/assets/25075847/1cae300f-98a3-45f0-a66d-ae641c16af98)
 and the "Any" value ([72-48-0-Any] Sensor state) started changing with the water detection.  That rippled up to domoticz and is now working.  I think I learned a bunch about how the whole flow from device to domoticz works on the new zwave stack.  Thanks for your help, gizmocuz.  have a good day.

**Comment by sundansx** [comment]
Fixed with setting in ZwaveJSUI.

**Comment by sundansx** [comment]
Fixed with setting in ZwaveJSUI.

**Comment by gizmocuz** [comment]
Yeah! Great it's working!
