### ISSUE TITLE
Typo in the dzVents documentation

### ISSUE THREAD

**Issue by roblomq** [domoticz/domoticz#6123]
I think I can edit it somehow myself but i'm not sure how to do that so I post it here.

In the wiki documentation of dzVents (original is [here](https://github.com/domoticz/domoticz/blob/development/dzVents/documentation/README.md)) there is stated

`switchSelector(<[level]|[levelname] >) : Function. Switches a selector switch to a specific level ( levelname or level(numeric) required ) levelname must be exact, for level the closest fit will be picked. See the edit page in Domoticz for such a switch to get a list of the values). Levelname is only supported when level 0 (“Off”) is not removed Supports [command options](https://www.domoticz.com/wiki/DzVents:_next_generation_Lua_scripting#Command_options_.28delay.2C_duration.2C_event_triggering.29).`

It would be better if the "switchSelector(<[level]|[levelname] " is changed to "switchSelector(<[level]|[levelName] ", it might save some others time to solve the issue I had. I copy paste the "levelname" which should be "levelName".

**Comment by waltervl** [comment]
Why change? The meaning of this statement is that you can switch the selector with yourdevice.switchSelector(20) or yourdevice.switchSelector('yourlevelname'). So it does not matter how it is called into DzVents documentation.

If you want to get the current levelname the selector switch is in use yourdevice.levelName which gives the levelname.....
If you want a list (table) of all the possible level names of the switch use yourdevice.levelNames

**Comment by roblomq** [comment]
I think that I mixedup the first and second thing you said... Thanks for your explanation.

**Comment by waltervl** [comment]
No problem.
I will close this issue.
