### ISSUE TITLE
Suggestion: add notification for "General, Text" sensors

### ISSUE THREAD

**Issue by JannemanDev** [domoticz/domoticz#6124]
I have a sensor type  "General, Text" that shows the current status of the PV system, possible values are for example "Normal", "Offline", "Error" etc.
I want a notification when Text is not equal to "Normal". Currently "Notifications' button for sensors are only available/possible when it has a numeric value like a sensor for "Temperature".

![image](https://github.com/user-attachments/assets/b966f83e-d11d-459f-9303-ed7d3ca4f57b)

**Comment by gizmocuz** [comment]
You can use dzVents for this

**Comment by waltervl** [comment]
@JannemanDev I use the GoodweSEMS python plugin https://github.com/janjaapko/domoticz-GoodWeSEMS where the inverter state is a selector switch. So you can be notified on that with standard notify options. Perhaps you can also change this to a selector switch in your integration.

**Comment by JannemanDev** [comment]
> @JannemanDev I use the GoodweSEMS python plugin https://github.com/janjaapko/domoticz-GoodWeSEMS where the inverter state is a selector switch. So you can be notified on that with standard notify options. Perhaps you can also change this to a selector switch in your integration.

thanks for your reply. I personally prefer more the other plugin that directly reads the inverter (locally within my LAN), without relying on external sems portal api and its rate limit and potential availability issues.

**Comment by waltervl** [comment]
I understand. You can ask the plugin author to change the status device from text to a selector switch. Or do it yourself....

**Comment by JannemanDev** [comment]
> I understand. You can ask the plugin author to change the status device from text to a selector switch. Or do it yourself....

already done it myself: https://github.com/remco-k/domoticz-goodwe-modbusudp-plugin/pull/10#issue-2405790868

**Comment by waltervl** [comment]
I personally would not have made it a Custom Sensor. A selector switch would have been better.
