### ISSUE TITLE
Switch status issue for Lumi relay

### ISSUE THREAD

**Issue by blooesky** [domoticz/domoticz#6130]
Hi,
I run Domoticz 2024.7 beta version and i noticed that switch status(ONLY INTERLOCK SWITCH AND POWER_OUTAGE_MEMORY) dont changing on action for Lumi Relay LLKZMK11LM.

From zigbee2Mqtt:

Command interlock on and power_outage_memory off:
{"consumption":0.008124999701976776,"current":0.01,"device_temperature":53,"energy":0.01,"interlock":true,"last_seen":"2024-07-28T18:58:16+03:00","linkquality":58,"power":0.05,"power_outage_count":184,"power_outage_memory":false,"state_l1":"OFF","state_l2":"OFF","update":{"installed_version":35,"latest_version":47,"state":"available"},"update_available":true,"voltage":204.77}

Command interlock on and power_outage_memory off:
{"consumption":0.008124999701976776,"current":0.01,"device_temperature":52,"energy":0.01,"interlock":false,"last_seen":"2024-07-28T19:26:33+03:00","linkquality":58,"power":0.01,"power_outage_count":184,"power_outage_memory":true,"state_l1":"OFF","state_l2":"OFF","update":{"installed_version":35,"latest_version":47,"state":"available"},"update_available":true,"voltage":210.11}

Interlock config:

{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/Releu rulou/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/Releu rulou/set/interlock","device":{"identifiers":["zigbee2mqtt_0x00158d000419c3b1"],"manufacturer":"Aqara","model":"Dual relay module (LLKZMK11LM)","name":"Releu rulou","via_device":"zigbee2mqtt_bridge_0x00124b00256c488c"},"json_attributes_topic":"zigbee2mqtt/Releu rulou","name":"Interlock","object_id":"releu_rulou_interlock","origin":{"name":"Zigbee2MQTT","sw":"1.39.0","url":"https://www.zigbee2mqtt.io"},"payload_off":"false","payload_on":"true","state_topic":"zigbee2mqtt/Releu rulou","unique_id":"0x00158d000419c3b1_switch_interlock_zigbee2mqtt","value_template":"{% if value_json.interlock %} true {% else %} false {% endif %}"}

Power_outage_memory config:

{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/Releu rulou/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/Releu rulou/set/power_outage_memory","device":{"identifiers":["zigbee2mqtt_0x00158d000419c3b1"],"manufacturer":"Aqara","model":"Dual relay module (LLKZMK11LM)","name":"Releu rulou","via_device":"zigbee2mqtt_bridge_0x00124b00256c488c"},"entity_category":"config","icon":"mdi:memory","json_attributes_topic":"zigbee2mqtt/Releu rulou","name":"Power outage memory","object_id":"releu_rulou_power_outage_memory","origin":{"name":"Zigbee2MQTT","sw":"1.39.0","url":"https://www.zigbee2mqtt.io"},"payload_off":"false","payload_on":"true","state_topic":"zigbee2mqtt/Releu rulou","unique_id":"0x00158d000419c3b1_switch_power_outage_memory_zigbee2mqtt","value_template":"{% if value_json.power_outage_memory %} true {% else %} false {% endif %}"}

Thank you!

**Comment by waltervl** [comment]
I am not sure but a value template like "{% if value_json.interlock %} true {% else %} false {% endif %}"  with if statements is not supported in Domoticz.

**Comment by blooesky** [comment]
But it worked good until recently.
Now he sends the command(only to off) but the status does not change.

**Comment by waltervl** [comment]
That is new information. You did not mention that before. Did you update Domoticz? If yes, in what version did it work?
Did you udate Zigbee2MQTT recently?

**Comment by gizmocuz** [comment]
We never supported this template

**Comment by blooesky** [comment]
> That is new information. You did not mention that before. Did you update Domoticz? If yes, in what version did it work? Did you udate Zigbee2MQTT recently?

I dont know what version of domoticz, but i think a few months ago when i paired this lumi switch with zigbee2mqtt.
I haven't updated the zigbee2mqtt or maybe once .
I know for sure that it worked at one point, but I don't know what version.
