### ISSUE TITLE
Field for battery type and battery replacement date

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#6131]
Feature request.
A lot, if not the most, of my devices are battery powered.
I now place the battery type and replacement date in the description field.
It would be nice if they both get there own field.
![02 08 2024_15 13 22_REC](https://github.com/user-attachments/assets/49dc1d7f-753a-48c6-93ab-713a247afe9d)

**Comment by gizmocuz** [comment]
How about you specify these in a google sheet? Or even better, use the google calendar so you get a notification?

**Comment by SargonofAssyria** [comment]
That is ofcourse no problem. But my idea was to keep it all together in 1 Domoticz and use dzVents on the database to get Notified by Domoticz it self. I can do that on the description itself, but I use the description also for other uses like DZGA, so it a little bit harder to filter out. So that triggered my idea of seperate fields. But I can live with my current solution.

**Comment by gizmocuz** [comment]
Seems complicated if you can also get notified by a calendar ;) ...
