### ISSUE TITLE
Update and Delete buttons on the hardware page are not really disabled, but just gray in case no device is selected.

### ISSUE THREAD

**Issue by LoukKamp** [domoticz/domoticz#6138]
While working on the new authorization process for Netatmo devices, I found that the Delete and Update buttons on the hardware page are nor really disabled, but just colored gray: When you click one of these buttons, the procedure behind the button is activated, even when the button is gray and should not cause any action.

I tried to add the "Disable" attribute to the buttons from JS, using the prop-function, but this doesn't seem to work for some reason and needs some more research.

I'm willing to solve this issue, and make a patch for this, but as this is an issue that is more common than just the interface for the Netatmo devices, I thought that I should handle this as a separate issue and PR.

**Comment by LoukKamp** [comment]
More details: The buttons turned out not to be real buttons, but just a link object (<a>) with a href attribute. Converting those buttons to real buttons didn't help much and takes quite a lot of changes. 

The most simple solution (in my opinion) , is to remove the href attribute when the buttons should be disabled (together with changing the class from "btnstyle3" to "btnstyle3-dis").

@gizmocuz: I want to create new fork and PR to apply this patch to avoid mixing up with my changes for the Netatmo login process; is this OK?

**Comment by kiddigital** [comment]
@LoukKamp , yes please provide different changes in separate PR branches.

This makes it easier to review a PR and in case of serious issues, allows for easier reverting.

**Comment by LoukKamp** [comment]
OK, I will do so asap...
________________________________
Van: KidDigital ***@***.***>
Verzonden: zondag 18 augustus 2024 16:53
Aan: domoticz/domoticz ***@***.***>
CC: Louk ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [domoticz/domoticz] Update and Delete buttons on the hardware page are not really disabled, but just gray in case no device is selected. (Issue #6138)


@LoukKamp<https://github.com/LoukKamp> , yes please provide different changes in separate PR branches.

This makes it easier to review a PR and in case of serious issues, allows for easier reverting.

**Comment by LoukKamp** [comment]
When editing the file /www/app/hardware/Hardware.js, I found some code that is simular to the buttons I was refering to, slightly different:

```
		RefreshLMSNodeTable = function () {
			$('#modal').show();
			$('#updelclr #nodeupdate').attr("class", "btnstyle3-dis");
			$('#updelclr #nodedelete').attr("class", "btnstyle3-dis");
			$("#hardwarecontent #lmsnodeparamstable #nodename").val("");
			$("#hardwarecontent #lmsnodeparamstable #nodeip").val("");
			$("#hardwarecontent #lmsnodeparamstable #nodeport").val("9000");

			var oTable = $('#lmsnodestable').dataTable();
			oTable.fnClearTable();

			$.ajax({
				url: "json.htm?type=command&param=lmsgetnodes&idx=" + $.devIdx,
				async: false,
				dataType: 'json',

```
However, I think that this is dead code: The buttons are not defined in the corresponding HTML file and the section of the input elements don't even exists.

**Can somebody here check if my suspisions are correct, and if so, what should I do with it?**

**Comment by gizmocuz** [comment]
**RefreshLMSNodeTable** is being called by various functions in Hardware.js so I don't think the code is not in use
But I can't find any html items with the name **lmsnodeparamstable**

There is a section for LMS in Hardware.html, it appears to be a kind of Notification system (Logitech media Server)

I did not implement this, and I would think that this would be configured under 'Settings'

But I see you can also add them from the hardware tab. I suspect that the setup for this hardware had it's own settings in the past, but is not using the global/default remote address/port fields

Maybe for now don't touch it but only add a few functions (DisableUpdateDelete, EnableUpdateDelete), and call these when a item is selected from the table, or the refresh/update/delete button is pressed
Or just add the needed code to fix the issue like in your PR (I just noticed you already made a PR)

Logitech Media Server has been renamed to 'Lyrion Music Server', I'm not even sure if the current implementation in Domoticz is compatible with it, but if it does, we could rename it throughout the application

**Comment by kiddigital** [comment]
@LoukKamp , can this one be closed?

**Comment by LoukKamp** [comment]
Yes; just did this
