### ISSUE TITLE
New hardware : HTTP/HTTPS client

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#614]
Goal : Have the ability to query an HTTP/HTTPS server, parse the returned data with some internal parsers and store the parsed data in some devices

Hardware architecture : A new hardware type is introduced and is based on a HTTP/HTTPS client
This hardware will have some parameters :
- URL
- Credentials (if needed)
- Parser file (in LUA format, see below)
- Period (polling period)
- Timeout (in case of error)

Parsers : In order to have the ability to parse all kinds of data, lua script can be used to parse the data and since domoticz already have these methods, there is nothing to add. Format can be xml, json or raw text.

Steps :
1. The data is polled by the http/https client
2. The lua script associated to the hardware is called and the queries data is passed to the script
3. The lua script is parsing the data and may use domoticz_applyJsonPath & domoticz_applyXPath LUA function if needed
4 . The lua script is calling domoticz_updateDevice to insert the data

I can work on it

**Comment by gizmocuz** [comment]
Sounds great ! But since you have to write a script (LUA) to do the parsing, what would be the difference if you make an .php / python or bash script for the same goal, and use the system's crontab ?
How about the other way, let's say you query a HTTP switch, can you also change it's state from within Domoticz ?

**Comment by sbouchex** [comment]
Yes, I was thinking about using an external script but I though it was not the right way becaue:
- that's not integrated and difficult to maintain
- Windows does not have a crontab :-)
- It's cross platform
  But a user can already do it with a dummy device and some curl call I agree

About switching a HTTP switch, I think it's already doable by specifying a URL ?

**Comment by sbouchex** [comment]
@gizmocuz ok for you ? May I start doing it ? Thanks

**Comment by rkluwen** [comment]
Just a small comment: If I am not mistaken, in Domoticz we use several different http client services (CURL, HTTPClient.cpp, and maybe more).
Maybe it's a good idea to unify this at the same time?

**Comment by sbouchex** [comment]
@rkluwen HTTPClient.cpp is based on curl, that's just a C++ wrapper (sort of)

**Comment by rkluwen** [comment]
Ah, I see. Just an idea that I have is to make a boost based client that in a later stage can be enhanced with a websocket client.
Curl is nice, but we don't really need it. So it will at the same time eliminate an extra external dependancy.
Also I know there's several different urlencode helpers (curl based and c-code).

**Comment by sbouchex** [comment]
@rkluwen Yep, removing curl would be nice as well. My approach is to use HTTPClient and if someday, somebody wants to remove the curl client, it would be easier.
AFAK, only HTTPClient & SMTPclient classes are using curl code but boost does not include a SMTP client :-(

**Comment by rkluwen** [comment]
SMTP in boost is just as easy (or maybe easier) than HTTP in boost. Examples are available if you Google around a bit.
Anyway, I think I am posting off-topic. Maybe you meant to do something different than I had in mind. Sorry about that.

**Comment by sbouchex** [comment]
No problem, I was planning to use the HTTPClient class. If you want (plan) to get ride of curl and use boost, just send a PR :-)

**Comment by gizmocuz** [comment]
we should get rid of boost actually and start with c++11/14
Nothing wrong with curl, and it is very good/stable
Please continue using the HTTPClient class
