### ISSUE TITLE
Battery levels of Netatmo modules are displayed incorrectly (much too wide)

### ISSUE THREAD

**Issue by LoukKamp** [domoticz/domoticz#6144]
The battery levels of additional Netatmo inside modules are displayed much too wide:

![afbeelding](https://github.com/user-attachments/assets/fa8fae8a-7e4f-4256-a7fd-83fa17536be6)

The levels of other parameters with battery levels include are displayed well.

Side issue: It seems that these values are only updated at the first connection, but this may not be a problem of Domoticz (not sure yet)

**Comment by JurgenLB** [comment]
In my code I have solved this issue. it is a value that is too big for the standard battery level.
If you give me some time I can update my code to meet your changed from the authentication

**Comment by LoukKamp** [comment]
No problem, take your time...
________________________________
Van: JurgenLB ***@***.***>
Verzonden: zaterdag 24 augustus 2024 00:42
Aan: domoticz/domoticz ***@***.***>
CC: Louk ***@***.***>; Author ***@***.***>
Onderwerp: Re: [domoticz/domoticz] Battery levels of Netatmo modules are displayed incorrectly (much too wide) (Issue #6144)


In my code I have solved this issue. it is a value that is too big for the standard battery level.
If you give me some time I can update my code to meet your changed from the authentication

**Comment by JurgenLB** [comment]
updated Netatmo API  resolves the RF and Battery -Levels
see #6149
