### ISSUE TITLE
Http Custom Script Notifications considered insecure with 'os' embedded in name

### ISSUE THREAD

**Issue by msven** [domoticz/domoticz#6146]
Hello! I recently updated to domoticz version 2024.7 (from a very old version from 2019).

After upgrading, my Custom HTTP notifications started failing with the following message in the logs `Error: Script: Insecure script command!`

My configuration is shown below

![image](https://github.com/user-attachments/assets/4cc061d7-c97e-484b-b103-6be99a41507c)

I traced the code to hitting this set of validations https://github.com/domoticz/domoticz/blob/2024.7/main/Helper.cpp#L1315

It appears that this code will consider any command insecure that contains the characters `os`.  So my command was failing this validation due to p**os**tT**oS**lack.sh containing these two characters.

Expectation:  Having the characters `os` embedded in a script name would not trigger the script to be considered insecure.

I've been able to work around this for now by renaming my script.  So alternatively, some documentation around this limitation may also address this issue.

Thanks for the great work!

**Comment by gizmocuz** [comment]
That's indeed a big jump!

I added a warning on our wiki page

https://www.domoticz.com/wiki/Notifications#Configuring_Custom_HTTP.2FAction

Thanks for reporting!
