### ISSUE TITLE
bug in "login page" can not login with a correct username and password and everytime back on login page

### ISSUE THREAD

**Issue by feredy2011** [domoticz/domoticz#6156]
Hi
before , i am used domoticz v3.5877. now i switch to version 2024.4 . in v3.5877 when i want actived login page with a username and password , if i choose "basic-auth" every things was ok . but if I select "login page" soooooo after deys , when i am logout and i want login and enter correct username and password , i am back i login page auto again(can not enter to dashboard page or switchs page).every time i enter username and password and enter login button without any login , i am back in login page and i can not login to dashboard or switches.... (with unplug and plug raspberry's power and clean the history of chorme and firefox and appcashe, this problem dont solve.this problem is not related my browser because i test several devices(mobile,tablet,laptop) 
now in version 2024 i have same problem (because login page is default and there is not a "basic-auth" )
even i test with : http://username:password@ip:port , again open login page and request username and password.

`In short, I can't get past the login page. for 0.5 second dashboard will open but back to login page quickly`

note : this problem is just when i want use mobile phone or laptop and other deviced for login to domoticz (chorme or firefox and ....)with raspberry pi's ip in a local network. but when I enter to raspberry pi desktop(with vncserver) and open domoticz with ip 127.0.0.1:8080 and enter username and password , this is true and successful login (trust network is empty and 127.0.0.1 is not in trust network) 
note2: when i am login with 127.0.0.1 , so i test with mobile or laptop , i can not enter but in "domoticz log" i see this messages:
for mobile :
`2024-07-26 03:21:41.903 Status: Login successful from 192.168.1.6 for user 'admin'`
`2024-07-26 03:21:41.904 Status: [web:8080] Incoming connection from: 192.168.1.6`

for loptop:
`2024-07-26 03:23:11.569 Status: Login successful from 192.168.1.247 for user 'admin'`
`2024-07-26 03:23:11.569 Status: [web:8080] Incoming connection from: 192.168.1.247`

means login is successful but can not open dashboard page and back to login page again.
I think this is a bug . can you help me to resolve this issue or can i help to change "login page" to "basic-auth" model .

**Comment by gizmocuz** [comment]
When you use the login page, you have the option 'Remember me', this should send a cookie that allows you to access Domoticz for a longer time without asking for the username/password again all the time.
This time will be extended when you use Domoticz
Make sure your browser supports cookies, and that you keep the cookie and not delete it!

When in your local network/house, you can assign your machine/mobiles a fixed IP address.
In Domoticz settings/local networks, you can add these IP addresses, and this will cause to not display the login screen

Basic Auth should still work for HTTPS, but it is not advised to use it because of its very week security algoritm

**Comment by feredy2011** [comment]
hi dear , thank you for answer
I think you didn't understand what I meant , sorry i am weak in english.
cookie is ok and this problem is not related to my devices and my browsers.because i test with new mobile and...
i send a short video from this problem.
I don't want to use fixed ip and trust network , i want resolved this problem , and i think this is related to domoticz or RPI. several days this was true and worked well . 
after some plug/unplug power supply of RPI this problem is show. see my video.
I emphasize again this problem is when i want enter with my mobile,laptop and... but with RPI desktop and ip 127.0.0.1:8080 (this is not in trust network and trust network is empty) i enter username and password and login without any problem .

[https://uupload.ir/view/inshot_20240906_131027487_ij5n.mp4/](url)


https://github.com/user-attachments/assets/394a22cc-ceb5-42a1-8b96-ae9594f29515

**Comment by kiddigital** [comment]
Make sure your caches of your devices are cleared when accessing your updated domoticz.

**Comment by gizmocuz** [comment]
And it could very well be that after a restart of Domoticz it clears it's internal cookies... that's find too

**Comment by feredy2011** [comment]
i don't update domoticz every time.I selected a stable version (2024.4) and I like work with this version for a long time.there is this problem without any update( i think this is related to unplug/plug power supply) .
I cleared cache (firefox and also chorme ) , also clear data and cache "app" in setting mobile . also I removed firefox app and install again , also I test in a new mobile (domoticz had never been run on this mobile before and this was the first time) but this problem dont resolve. 
According to these issues, is the problem with my browser and devices or with Domoticz? Or am I wrong in clearing the cache and data? ( i do it According to the photo for example in chorme )
If the problem was from the cache, I should not have this problem on a new device(mobile). is this true ? But I tested this problem with every device and only when I log in with the raspberry browser itself with IP 127.0.0.1, this problem does not exist and I enter the dashboard page easily.
If I need to clear the data or cache from Domoticz itself, please guide me how to do it.
![Untitlennnd](https://github.com/user-attachments/assets/02b624ca-659b-4af5-9a27-a7fed6e55080)

**Comment by gizmocuz** [comment]
You do not need to clear the cache and data anymore since quite some (stable) versions
If you restart Domoticz (unplug/plug power supply... and you should NOT do this!!), it's OK to need to login again
If you login, and select 'remember me', and do not restart Domoticz, then next time you should be able to login without it asking for a username/password. That is, if you login in one month

**Comment by feredy2011** [comment]
This problem (stuck in the login page) happened after disconnecting and connecting the raspberry socket once or twice (due to not connecting the power plug firmly), I did not have this problem before this problem. Now I can't enter the dashboard and like the video I sent, I'm stuck on the login page and can't enter. All I did was to solve this problem, but it was not solved and I still can't log in

**Comment by feredy2011** [comment]
Please watch the video again carefully. Every time I enter my username and password and hit the login button (whether the remember tick is activated or not), I enter the dashboard and very quickly return to the login page automatically.

**Comment by feredy2011** [comment]
my dear friend You did not understand my problem. Pay attention to the video. Every time I enter the username and password and hit the login button, the login page does not skip and asks me again for the username and password. I do it thousands of times and enter the username and password and it does not exit the login page and the dashboard does not open and again and again request username and password from me.

**Comment by kiddigital** [comment]
Make sure the time on your pi is accurate as well

**Comment by gizmocuz** [comment]
Does your browser store the cookie? (As mentioned in my first reply), this is important else it won't work
Let's assume we have quite a few users using the login screen (including myself), it's not a bug from Domoticz, so please try to find the solution on your site.
If that seems impossible, use the local network option in Domoticz to add the fixed IP addresses of your mobile/desktop devices so you do not need to login
I know it's a work-around, but that should work

**Comment by feredy2011** [comment]
> Make sure the time on your pi is accurate as well

thaaaaaank you. this is true. this was related to rpi's time and I didn't know that time affects the login.

**Comment by gizmocuz** [comment]
Glad you found it! Yes, as you can read in the first reply, the cookie is valid for a month. This gets extended each time you login

**Comment by feredy2011** [comment]
> Glad you found it! Yes, as you can read in the first reply, the cookie is valid for a month. This gets extended each time you login

thank you
