### ISSUE TITLE
MQTT "total_increasing" energy counter goes backwards.

### ISSUE THREAD

**Issue by dwmw2** [domoticz/domoticz#6160]
I have a power meter device running ESPHome: https://devices.esphome.io/devices/Tongou-TO-Q-SY1-JWT

It reports its power usage (kWh sensor) as `"stat_cla": "total_increasing"`:
```
${mqtt_prefix}/homeassistant/sensor/power-lights-upstairs/upstairs_light_circuit_energy/config 
{
   "avty_t" : "power-lights-upstairs/status",
   "dev" : {
      "cns" : [
         [
            "mac",
            "18de50e14433"
         ]
      ],
      "ids" : "18de50e14433",
      "mdl" : "cbu",
      "mf" : "Beken",
      "name" : "power-lights-upstairs",
      "sw" : "2024.9.0-dev (Sep  9 2024, 14:39:50)"
   },
   "dev_cla" : "energy",
   "name" : "Upstairs light circuit Energy",
   "obj_id" : "power-lights-upstairs_upstairs_light_circuit_energy",
   "stat_cla" : "total_increasing",
   "stat_t" : "power-lights-upstairs/sensor/upstairs_light_circuit_energy/state",
   "uniq_id" : "18de50e14433-sensor-96f75e13",
   "unit_of_meas" : "kWh"
}
```
See documentation for `total_increasing` in https://developers.home-assistant.io/docs/core/entity/sensor/ :

> Similar to total, with the restriction that the state represents a monotonically increasing positive total which periodically restarts counting from 0, e.g. a daily amount of consumed gas, weekly water consumption or lifetime energy consumption. Statistics of the accumulated growth of the sensor's value since it was first added is updated every 5 minutes. A decreasing value is interpreted as the start of a new meter cycle or the replacement of the meter.

When Domoticz auto-discovers this device, it should probably set it up as an RFXMeter Counter device? It doesn't, and when the unit power cycles and goes back to zero, I see a massive negative energy usage.
![Screenshot from 2024-09-10 22-51-52](https://github.com/user-attachments/assets/ef0fd76c-8578-4bef-a5cd-1be02eb062d2)

**Comment by dwmw2** [comment]
Perhaps not RFXMeter counter; I don't think there is a device type which works out of the box for incremental counters like this, is there? Which is why I once had to do it like this: https://www.domoticz.com/wiki/Lua_-_Electric_meter_pulse_counter

**Comment by gizmocuz** [comment]
Would be better if the counter was not reset.

I see in the MQTTAutoDiscovery.cpp code that there is some code remarked that checks for the 'total_increasing' state class.

We do have a 

			devType = pTypeGeneral;
			subType = sTypeCounterIncremental;

Are you able to test patch in **MQTTAutoDiscover::GuessSensorTypeValue**, that maybe checks at the top if the state class is 'total_increasing', so it will create a **sTypeCounterIncremental** type? (and return true)

Bdw, I have looked at these switches but decided against it... I don't trust them for that price and if you catch fire, you have a big issue.
Don't think your insurance will cover if they found out you are using a cheap (Chinese) switch.
Then you are better off with a Shelly device, or a good brand modbus device... 

Why is the counter reset? Is it because of a limitation of the data type holding the counter?

**Comment by dwmw2** [comment]
The counter was reset because I powered down the house to 'liberate' a couple more of the units with ESPHome :)

**Comment by gizmocuz** [comment]
Ahhh, so when this does not happen, the created kWh sensor is working like it should (And I hope you have some realtime Watt reporting too)
In some Domoticz internal hardware I make use of a 'CounterHelper' class (see the EnphaseAPI.cpp file for an example), this has the option to detect a reset and keeps on counting.
This might be something we could introduce in MQTT

**Comment by dwmw2** [comment]
> Ahhh, so when this does not happen, the created kWh sensor is working like it should (And I hope you have some realtime Watt reporting too)

Yes, the cute hack in MQTTAutoDiscovery.cpp to match up of the Watt / kWh sensors works nicely. You can't see it in the above screenshot because the negative spike hides it all
![Screenshot from 2024-09-11 09-53-59](https://github.com/user-attachments/assets/e0981fd7-7c05-49e6-8f3c-00a96be22365)

>  In some Domoticz internal hardware I make use of a 'CounterHelper' class (see the EnphaseAPI.cpp file for an example), this has the option to detect a reset and keeps on counting.

Aha, nice. I'd been looking at it and wondering *where* to store the previous counter value, to detect resets. I'd been thinking that I might need to invent a completely new Meter type and add it as another semi-colon separated field in the sValue.... but the CounterHelper seems to do it in a UserVariable just like that lua script I had in 2016, which looks much simpler.

**Comment by dwmw2** [comment]
I think the CounterHelper class probably needs to be able to look at the previous total value of the parent device, not just its own `m_nLastCounterValue` from hardware. Otherwise I think it'll fail to advance after a complete power failure? 

Let's say the `m_CounterOffset` stored in the UserVariable is 100. Values come in from MQTT, so "5 kWh" leads to a reading of 105kWh, etc...

Now there's a power cut. Everything restarts, including Domoticz. The last value of the meter in the *database* is 105kWh but the CounterValue class doesn't know that, so `m_CounterOffset` never gets advanced. A new reading over MQTT of "1kWh" will result in the "total" going backwards to 101kWh?

I think it needs to look at the total it calculates, see that it's lower than the previous sValue from the database (105kWh), and use *that* as the trigger for resetting m_CounterOffset? Which is how my lua script did it.

(This is purely from code inspection; I haven't tested it yet).

**Comment by gizmocuz** [comment]
Why? The last value is reloaded on restart, see the Enphase class

**Comment by dwmw2** [comment]
I'm looking at the code in Enphase.cpp. It invokes the CounterHelper in precisely two places. It calls `CounterHelper::init()` and `CounterHelper::SendKwhMeter()`. 

It looks like it'll cope with *either* Domoticz restarting, *or* the readings from the "hardware" resetting to zero, but not if they *both* happen at the same time.

Let's say the 'offset' in the UserVariable and in m_CounterOffset is 100 kWh. The hardware submits a reading of 50kWh, so `CounterHelper::SendKwhMeter()` makes that into a total of 150kWh which is actually what gets recorded. 

Now, Domoticz restarts. The Enphase class calls `CounterHelper::init()` which reloads the offset (100kWh) from the UserVariable. The CounterHelper's `m_nLastCounterValue` is zero. No readings are received yet.

Now a reading comes in. If the "hardware" hadn't been reset, this reading would be >50 and everything would be fine. But let's say the hardware *has* been reset too, and started counting from zero. We get a reading of 5 kWh.

As far as I can tell, CounterHelper::SendKwhMeter() will happily accept that 5kWh as the *first* reading that the newly-restarted Domoticz sees, add it up to 105kWh, and cause the total to go backwards from 150kWh to 105Kwh.

Am I missing something?

**Comment by dwmw2** [comment]
I didn't use CounterHelper in https://github.com/domoticz/domoticz/pull/6163 in the end.

CounterHelper does precisely two things, *neither* of which we actually want.

Firstly it curates a UserVariable to store the 'epoch' of the raw counter, which is messy; I put it in `StrParam1` of the MQTTAD device instead.

Secondly it monitors for the raw counter going backwards, but has the bug described above. We actually need to compare the *total* against the previously recorded sValue of the device. Which may be in the database, if it's the first reading in a newly-started Domoticz. And extracting it from the semicolon-separated fields in the sValue is a device-specific task, as each type of device handles sValue differently. So teaching CounterHelper to do that would be non-trivial.

And in fact the MQTTAD kWh sensor handling *already* queries the database for the previous sValue, to handle zero readings.So it's really simple just to fetch `StrValue1` into `pSensor->epoch` at the same time, without trying to overengineer a fix for CounterHelper.
