### ISSUE TITLE
Allow Float on MQTT Gas meter

### ISSUE THREAD

**Issue by herm42** [domoticz/domoticz#6186]
In have a zwave gasmeter in my setup which is included to domoticz since years. There is only a small bug ...
if you look at the device ...
 
![image](https://github.com/user-attachments/assets/73cac0bf-d1fb-41c0-b5ef-a9182c849918)

and on the utility page ...
![image](https://github.com/user-attachments/assets/48d0b8c3-8c0f-4869-8246-7f560b14a5d3)

![image](https://github.com/user-attachments/assets/8a7297ee-bfb2-4533-8637-7d481f04115c)

you can see that the m³ value is truncated ... is there a way to allow float here?

**Comment by gizmocuz** [comment]
I think your divider in the settings is not correct... did you use 3 m3?

This is mine:
![image](https://github.com/user-attachments/assets/e081182f-fec4-416f-98cf-b5c986cdebc3)

**Comment by herm42** [comment]
if i change the counter divider from 1 to 1000 nothing changes ...
![image](https://github.com/user-attachments/assets/a0a15eaa-21eb-45dc-a944-a8dd3840fb61)

weird

**Comment by herm42** [comment]
fyi .. i'm on the latest beta

**Comment by herm42** [comment]
![image](https://github.com/user-attachments/assets/781e91e3-6b14-47fc-beef-7ccdc04f7128)

i do not understand what this counter divider is used for ... in my case the meter is correct ... 15125.520m³ is the value stored at the zwave meter. So counter divider 1 should be the right one ?

... yes I used 4m³ today

**Comment by gizmocuz** [comment]
Could you perform the steps here at "Debugging MQTT' and post here the complete config topic name and payload, as well as the data name and payload?

https://www.domoticz.com/wiki/MQTT#Debugging_MQTT

With this I should be able to simulate your gas meter and see why floats are not handled

Did you use 15124.410 m3 gas? This value is correct? (including the 410 part?)

**Comment by herm42** [comment]
will provide the mqtt explorer data somewhen at the weekend.
correct-> 15124.410 is the exact overall consumption

**Comment by herm42** [comment]
{
  "type": "sensor",
  "object_id": "gas_cubic_meters_value",
  "discovery_payload": {
    "value_template": "{{ value_json.value }}",
    "unit_of_measurement": "Cubic meters",
    "icon": "mdi:thought-bubble",
    "device_class": "gas",
    "state_topic": "zwave-mqtt/87/50/0/value/131073",
    "availability": [
      {
        "payload_available": "true",
        "payload_not_available": "false",
        "topic": "zwave-mqtt/87/status",
        "value_template": "{{'true' if value_json.value else 'false'}}"
      },
      {
        "topic": "zwave-mqtt/_CLIENTS/ZWAVE_GATEWAY-zwave-js-ui/status",
        "value_template": "{{'online' if value_json.value else 'offline'}}"
      },
      {
        "payload_available": "true",
        "payload_not_available": "false",
        "topic": "zwave-mqtt/driver/status"
      }
    ],
    "availability_mode": "all",
    "json_attributes_topic": "zwave-mqtt/87/50/0/value/131073",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xe9a1d9f4_node87"
      ],
      "manufacturer": "NorthQ",
      "model": "NorthQ Gas Meter (NQ-9121)",
      "name": "Erdgas",
      "sw_version": "3.30"
    },
    "name": "Erdgas_gas_cubic_meters_value",
    "unique_id": "zwavejs2mqtt_0xe9a1d9f4_87-50-0-value-131073"
  },
  "discoveryTopic": "sensor/Erdgas/gas_cubic_meters_value/config",
  "values": [
    "50-0-value-131073"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_gas_cubic_meters_value"
}

**Comment by herm42** [comment]
{"time":1729768277055,"value":15128.89,"nodeName":"Erdgas","nodeLocation":"Heizraum"}

![image](https://github.com/user-attachments/assets/68e03739-bba8-4f29-b626-c0ff79674cf2)

**Comment by gizmocuz** [comment]
Thank you, I do miss the config topic, you provided only the payload
might be something like homeassistet/sensor/xxx/.../config

**Comment by herm42** [comment]
{"value_template":"{{ value_json.value }}","unit_of_measurement":"Cubic meters","icon":"mdi:thought-bubble","device_class":"gas","state_topic":"zwave-mqtt/87/50/0/value/131073","availability":[{"payload_available":"true","payload_not_available":"false","topic":"zwave-mqtt/87/status","value_template":"{{'true' if value_json.value else 'false'}}"},{"topic":"zwave-mqtt/_CLIENTS/ZWAVE_GATEWAY-zwave-js-ui/status","value_template":"{{'online' if value_json.value else 'offline'}}"},{"payload_available":"true","payload_not_available":"false","topic":"zwave-mqtt/driver/status"}],"availability_mode":"all","json_attributes_topic":"zwave-mqtt/87/50/0/value/131073","device":{"identifiers":["zwavejs2mqtt_0xe9a1d9f4_node87"],"manufacturer":"NorthQ","model":"NorthQ Gas Meter (NQ-9121)","name":"Erdgas","sw_version":"3.30"},"name":"Erdgas_gas_cubic_meters_value","unique_id":"zwavejs2mqtt_0xe9a1d9f4_87-50-0-value-131073"}

**Comment by gizmocuz** [comment]
I think you have to re-read the above page, specially

Debugging MQTT
Use MQTT Explorer tool

It mentions the icons to copy the topic and payload

**Comment by gizmocuz** [comment]
for instance, your payload topic is

wave-mqtt/87/50/0/value/131073

I managed to create the config topic myself, so hold on... going to debug the issue.

**Comment by gizmocuz** [comment]
Could you try beta 16291?
You should also get a normal 'Gas' device instead of a RFXMeter

**Comment by herm42** [comment]
thx for the fast fix!
new "P1 smart meter, Gas" has been detected. :-) Is there a way to migrate the old data to this new device (replace function does not find any destination device)?

**Comment by gizmocuz** [comment]
Could you send me a message on Slack and send me a backup of your database?

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

I think it should be possible. The gas meter stores it's values in Meter_Calendar, and I think the RFXMeter device as well
If both have the same values (of course your gas meter could be some m3 ahead now), you could also perform a SQL query to set the DeviceRowID of the old meter to the new GAS meter DeviceRowID
(First make a backup of your database!!! Twice!!)

Like

UPDATE Meter_Calender SET DeviceRowID=456 WHERE (DeviceRowID=123)

**Comment by herm42** [comment]
thx for the info. was able to change the device id and correct the values/counter because of the new counter divider.
everything is fixed now!

**Comment by gizmocuz** [comment]
Great!

**Comment by waltervl** [comment]
So issue can be closed?

**Comment by herm42** [comment]
everything is fine now ...
thx for your work!
