### ISSUE TITLE
JSON for Virtual Rain device incomplete

### ISSUE THREAD

**Issue by empierre** [domoticz/domoticz#619]
parameters Rain and Rainrate are missing

 {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0, 0;",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Virtuel switch",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "ID" : "14072",
         "LastUpdate" : "2016-04-20 10:00:04",
         "Name" : "Pluie sous 24H",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "TFA",
         "Timers" : "false",
         "Type" : "Rain",
         "TypeImg" : "rain",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "35"
      },

**Comment by gizmocuz** [comment]
There is no difference between the virtual or real rain sensor
And there is nothing missing in my real rain sensors

**Comment by empierre** [comment]
Hello,

  Here Rain and Rainrate are missing, is that a database corruption for the reporting user ?

**Comment by ArjenWols** [comment]
On Domoticz v3.5382 are the graphics missing on the virtual created device.
If more info is needed, please tell me how te generated the requested information and i will provide it to you.
