### ISSUE TITLE
Tado plugin fails

### ISSUE THREAD

**Issue by guido2200** [domoticz/domoticz#6196]
Recently the Tado plugin stopped working on my domoticz instance (2024-4 Windows). The log shows the error: `Error: tado: Failed to retrieve API environment from https://my.tado.com/webapp/env.js`

After some investigation is looks like the hard-coded API-url (in hardware/tado.ccp)  is not correct anymore.

When opening the url in the browser, it redirects to  `https://app.tado.com/env.js` and serves the env.json with the required information. However, I think Domoticz domoticz cannot handle the redirect.

**Comment by gizmocuz** [comment]
Could you try changing it in the code and see if that solves the problem? (Building Domoticz yourself)
Domoticz should be able to handle redirects

**Comment by guido2200** [comment]
That will be completely new to me but i'll give it a try!

**Comment by rikva** [comment]
Not just on Windows, the plugin has been broken for me for several weeks (I estimate about 2 months) now. Running on Linux.

```2024-11-13 17:07:21.311 Error: Tado: Failed to retrieve API environment from https://my.tado.com/webapp/env.js```

**Comment by guido2200** [comment]
On my other instance it is still working. But i guess as long as domoticz is running, it doen't need to retrieve the API environment. Upon a restart it needs to retrieve it again and which fails.

**Comment by waltervl** [comment]
Closed with PR #6219
