### ISSUE TITLE
hourly costs calculation on dynamic tariff not correct

### ISSUE THREAD

**Issue by infoedkok** [domoticz/domoticz#6197]
I 've noticed  in my believe ;-) some inconsistency in the hourly price calculation (dynamic) of the P1 device. 

In # 6181 there's this observation: 
"Although the hourly cost calculation in the P1 graph Usage/Hour (and its Excel export) **seems** correct (..)"

Indeed,  the hourly values/costs are calculated with my energy provider (Tibber) . 

But, imo, the calculation in the elect. device graph of P1 is not correct: 
- it takes the hourly "consumption-delivery" of T(hour)-1 hour (that;'s fine!), 
- but it takes the hourly price of T (hour) of my provider, (imo, that's is wrong?)

This example, "hot of the press":
The API hourly graph has reported the "v" and "r" of 19:00 till 20:00:
"d": "2024-10-29 20:00",
"p": "0.2644",
"r": "0",
"v": "830"
So it has calculated  "p" with a price per hour 0,83 / 0,2644 = 0,319 euro /kWh. 
But that was the Tibber price per hour of 20:00-21:00!

The hour price of Tibber between 19:00 and 20:00 of that date was 0,3916.
So, in my opinion, "p" calculation of the hour 19:00- 20:00 should be : 0,830 * 0,3916 = 0,325 euro

May be somebody else can check this ?
Am I right? And if so, could this be fixed?

Using Version: 2024.7 stable on Docker NAS.

**Comment by gizmocuz** [comment]
There are 4 tables in your database that stores metering information with prices.
2 of them are from the shortlog (Meter, MultiMeter) and 2 of them are for the daily logs (Meter_Calendar, Multimeter_Calendar)
When the daily price is calculated, the price is calculated from the values stored in the tabled Meter and Multimeter.

As probably mentioned in # 6181 this is done with the functions

`CSQLHelper::CalcMeterPrice` and `CSQLHelper::CalcMultiMeterPrice`

By default, each 5 minutes there is an entry added to Meter, Multimeter

**Comment by infoedkok** [comment]
Thank you for pointing to this code. Could not find the code for the JSON/API hour call.
Analysis showed that's the place to look/ bug fix.

I read that  the API /SJON I'm using ("../json.htm?type=graph&sensor=counter&range=hour&idx=..") is based on the short term tables.

So then my observation is correct:
- the data is correct
- the api call "hour" is doing it's calculation of "p" based on the wrong hourly price

So  I would like to put a bug req for this API call.

Analysis:

Have a look at these part of the multimeter table from my electr.device:
4	316900	121170	1239	101	195556	171143	5-11-2024 10:00	0.2815
4	316900	121170	1204	122	195460	171143	5-11-2024 09:55	0.2965
4	316900	121170	1015	90	195371	171143	5-11-2024 09:50	0.2965
4	316900	121170	182	151	195308	171143	5-11-2024 09:45	0.2965
4	316900	121170	870	108	195285	171143	5-11-2024 09:40	0.2965
4	316900	121170	2587	151	195191	171143	5-11-2024 09:35	0.2965
4	316900	121170	1271	99	195087	171143	5-11-2024 09:30	0.2965
4	316900	121170	1204	97	194990	171143	5-11-2024 09:25	0.2965
4	316900	121170	1186	113	194901	171143	5-11-2024 09:20	0.2965
4	316900	121170	1268	68	194794	171143	5-11-2024 09:15	0.2965
4	316900	121170	1382	28	194685	171143	5-11-2024 09:10	0.2965
4	316900	121170	1151	36	194588	171143	5-11-2024 09:05	0.2965
4	316900	121170	1518	27	194473	171143	5-11-2024 09:00	0.2965

The result of the API call for that hour is:
  "d": "2024-11-05 10:00",
            "p": "0.3049",
            "r": "0",
            "v": "1083"
My interpretation is that the total consumption (v) between 2024-11-05 9:00 and 10:00 is 1083
That is the difference of the counters at 9:00 and 10:00 , and that is also in the table.
So that part of the data is the same as in the API result

But that the total price of that hour is 0,3049.
If you do 0,3049/1083 *1000 you get the used hour price : 0,2815.

Notice the record of 10:00 with price of 0.2815 and the other prices (between 9:00-9:55) of 0.2965

As you can see the API hourly call is using the wrong hourly price , stored in the 10:00 recor.

But it should use the hourly price of one of the 9:00 / 9:55 records, e.g the 9:00 record is fine.

**Comment by gizmocuz** [comment]
This is the SQL query that the Hour API call is using

SELECT strftime('%Y-%m-%d %H:00:00', Date) as ymd, MIN(Value1) as u1, MIN(Value5) as u2, MIN(Value2) as d1, MIN(Value6) as d2, Price FROM MultiMeter WHERE (DeviceRowID==123) GROUP BY ymd

you have to replace the 123 with your ID of the P1 Electra price

**Comment by infoedkok** [comment]
Thank you! I turned out to be a simple (as always when you know it :) ) solution: I used a price device serving me with wrong pricing info. I changed it to the right one and now it's 100% ok.

Issue closed.

**Comment by JapieG** [comment]
I have the same issue bit cannot find how to solve this. I have correct prices on correct houts, but calculations based on one hour later

**Comment by infoedkok** [comment]
@JapieG , First, I solved this by adding a custom sensor to store the price of the last hour: simply run a script at **:55 or so to store the current price in and use this "price last hour" as your electricity device (settings). 

But, if you're using the correct custom sensor, the calculations are correct (just checked here ;-) )
Remember that the graphic for the hourly price in Domoticz shows the price of the past hour. 
Example: the price calculation is on 18-3-2026 on 11:00, then the price sensor shows the price in the graphic at 10:00 (this is the price from 10:00 till 11:00).

**Comment by JapieG** [comment]
This workaround seems to work well, but it still feels like a bug.

For example, when I check Reports → March → Today, I expect to see the correct price for each hour. However, the values appear to be shifted: the hourly calculations are using the price of the next hour instead of the actual current (previous) hour.
I use these figures for energy trading with a battery storage system, so this is not just a small display issue. The deviations from reality can become quite substantial and directly affect how useful the reported data is.

The issue is closed here. Am i missing something? Will report this again as a bug. If I se thing wrong, please explain and close new issue

**Comment by JapieG** [comment]
Ok, I'm stupid. Nevermind, I just looked wrong, there is actually no issue in my case. Thanks @infoedkok, you cleared up my brain fog
