### ISSUE TITLE
Issue with thousands-separator 

### ISSUE THREAD

**Issue by fleinze** [domoticz/domoticz#6198]
There is currently a bug with the decimal an thousands separators in the device log page.
If the locale has space as a thousands separator, than domoticz defaults to comma (",") as thousands separator. This means that both the thousands separator and the decimal separator will be the same symbol.

![grafik](https://github.com/user-attachments/assets/ddcc7303-33ce-4781-b3ab-b6cdd6026431)

The bug is in app.js line 412+413
`const decimalPoint = formattedNumber[5] === '.' || formattedNumber[5] === ',' ? formattedNumber[5] : '.';`
`const thousandsSep = formattedNumber[1] === ',' || formattedNumber[1] === '.' ? formattedNumber[1] : ',';`

If the decimalPoint or the thousandsSep are anything else than point or comma it defaults to english locale.

**Comment by fleinze** [comment]
I fixed it by skipping the check in the code:

`const decimalPoint = formattedNumber[5];`
`const thousandsSep = formattedNumber[1];`

I don't know if the check is strictly necessary. If it is, the code could be adjusted like this:
`const thousandsSep = formattedNumber[1] === ',' || formattedNumber[1] === '.' || formattedNumber[1] === '\u00A0' ? formattedNumber[1] : ',';`

**Comment by gizmocuz** [comment]
Thanks for reporting. Changed the line to:

`const thousandsSep = formattedNumber[1] === ',' || formattedNumber[1] === '.' || formattedNumber[1] === '\u00A0' ? formattedNumber[1] : ',';
`

Fix is in beta 16323

**Comment by fleinze** [comment]
Thanks, I installed the beta and it works!
