### ISSUE TITLE
P1 meter graph not correct for Gas meter

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#6199]
I am on holliday now. Before I left I shutoff all gas consumption.
Domoticz still gets P1 meter updates, also for gas but those are ofcourse zero.
The graphs are showing nothing any more, I think it should be zeros.

![01 11 2024_09 54 03_REC](https://github.com/user-attachments/assets/3828d26f-47a5-4785-9178-fa64bd4fa500)

**Comment by gizmocuz** [comment]
No, I don't think the P1 hardware class is updating Gas values and therefor it is empty
Have a great holiday!

**Comment by SargonofAssyria** [comment]
I have a second P1 meter via a splitter on the same physical meter.
That second P1 meter is an ESP8266 which spits out MQTT messages.
I can see that the message, with the same telegram value gets send by the physical meter.
I checked the sources of my ESP8266, so I am 100% sure that the telegram and (same) gas value is send.
I also checked that in Node-red with a debug node.
Those MQTT message are send to an other P1 gas device on Domoticz, which shows the same kind of graphic.

**Comment by SargonofAssyria** [comment]
Is not the problem in line 574?
```
if ((m_gas.gasusage > 0) && ((m_gas.gasusage != m_lastgasusage) || (difftime(atime, m_lastSharedSendGas) >= 300)))
```

**Comment by gizmocuz** [comment]
Yeah, but check your settings->Log History, by default the option 'Only add newly received values to the log'
This saves quite some disk space/calls.
And as you did not had any updated because the gas was off, it sounds correct what is happening

**Comment by SargonofAssyria** [comment]
I changed that setting. Will see if those zero values are added now.
I don't care about my database size, its only 41 Mb, for SQL thats small and I have an Rasp 4B, so it won't hurt.

**Comment by SargonofAssyria** [comment]
So I set that setting to 'red'  But the result stays the same.
I still think that this should be changed.
```
if ((m_gas.gasusage > 0)
```

**Comment by gizmocuz** [comment]
I don't think so as this holds the meter value.  If you export your database, do you see entries in the Meter table for this gas device?
Could be that the graph does not display zero values.

**Comment by SargonofAssyria** [comment]
In the database are all zeros now, but they are not displayed.
There is a differance between nothing and zero
So that is the bug?

**Comment by gizmocuz** [comment]
See my previous comment. But what seems to be the problem? You don't have gas usage, so it won't be displayed.
