### ISSUE TITLE
MQTT_AD energy counter has incorrect power

### ISSUE THREAD

**Issue by lverti** [domoticz/domoticz#6200]
Hello,

I have a SPM02v2 zigbee Smart energy monitor for 3P+N system. It products power, power_a, power_b, power_c, energy, and produced_energy measurements. The Domoticz made counters for energy and produced_energy, but connected "power_a" for them , not "power".

Version: 2024.7

### Power_a:
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "enabled_by_default": true,
  "name": "Power a",
  "object_id": "betáp_power_a",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_power_a_zigbee2mqtt",
  "unit_of_measurement": "W",
  "value_template": "{{ value_json.power_a }}"
}

### Power:
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "device_class": "power",
  "enabled_by_default": true,
  "entity_category": "diagnostic",
  "object_id": "betáp_power",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_class": "measurement",
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_power_zigbee2mqtt",
  "unit_of_measurement": "W",
  "value_template": "{{ value_json.power }}"
}

### Energy:
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "device_class": "energy",
  "enabled_by_default": true,
  "object_id": "betáp_energy",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_class": "total_increasing",
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_energy_zigbee2mqtt",
  "unit_of_measurement": "kWh",
  "value_template": "{{ value_json.energy }}"
}
 ### Produced_energy:
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "device_class": "energy",
  "enabled_by_default": true,
  "object_id": "betáp_produced_energy",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_class": "total_increasing",
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_produced_energy_zigbee2mqtt",
  "unit_of_measurement": "kWh",
  "value_template": "{{ value_json.produced_energy }}"
}

**Comment by gizmocuz** [comment]
Thank you for your issue. Could you edit the above issue and add the complete config topics names as well ?

**Comment by gizmocuz** [comment]
Apparently there is Power_A , Power_B, Power_C, could you post the config topic names/payload of b/c as well ?

Voltage a/b/c are working fine?

The device sounded interesting, but apparently not the best device... V3 when it is released could be better.
Edit: There is a V3, maybe it is a matter of firmware upgrade

https://github.com/Koenkk/zigbee2mqtt/issues/22236

**Comment by lverti** [comment]
Thank you for your answer. The measured values are correct. The problem is, that the counters show the power_a instead the power. Sorry for the confusion.
![kép](https://github.com/user-attachments/assets/3909db71-eb64-4867-bbfa-5a1e2dec4ef5)

**Comment by gizmocuz** [comment]
Yes, I think it takes the first power sensor found.
I can try to reproduce the issue if you post all topics names/config payloads, without this I can't help.
Another option is to use dzVents and update a dummy kWh sensor with the correct sensors

**Comment by lverti** [comment]
homeassistant/sensor/0x90395efffe185436/voltage_a/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "enabled_by_default": true,
  "name": "Voltage a",
  "object_id": "betáp_voltage_a",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_voltage_a_zigbee2mqtt",
  "unit_of_measurement": "V",
  "value_template": "{{ value_json.voltage_a }}"
}
homeassistant/sensor/0x90395efffe185436/voltage_b/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "enabled_by_default": true,
  "name": "Voltage b",
  "object_id": "betáp_voltage_b",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_voltage_b_zigbee2mqtt",
  "unit_of_measurement": "V",
  "value_template": "{{ value_json.voltage_b }}"
}
homeassistant/sensor/0x90395efffe185436/voltage_c/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "enabled_by_default": true,
  "name": "Voltage c",
  "object_id": "betáp_voltage_c",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_voltage_c_zigbee2mqtt",
  "unit_of_measurement": "V",
  "value_template": "{{ value_json.voltage_c }}"
}
homeassistant/sensor/0x90395efffe185436/power_a/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "enabled_by_default": true,
  "name": "Power a",
  "object_id": "betáp_power_a",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_power_a_zigbee2mqtt",
  "unit_of_measurement": "W",
  "value_template": "{{ value_json.power_a }}"
}
homeassistant/sensor/0x90395efffe185436/power_b/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "enabled_by_default": true,
  "name": "Power b",
  "object_id": "betáp_power_b",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_power_b_zigbee2mqtt",
  "unit_of_measurement": "W",
  "value_template": "{{ value_json.power_b }}"
}
homeassistant/sensor/0x90395efffe185436/power_c/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "enabled_by_default": true,
  "name": "Power c",
  "object_id": "betáp_power_c",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_power_c_zigbee2mqtt",
  "unit_of_measurement": "W",
  "value_template": "{{ value_json.power_c }}"
}
homeassistant/sensor/0x90395efffe185436/current_a/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "enabled_by_default": true,
  "name": "Current a",
  "object_id": "betáp_current_a",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_current_a_zigbee2mqtt",
  "unit_of_measurement": "A",
  "value_template": "{{ value_json.current_a }}"
}
homeassistant/sensor/0x90395efffe185436/current_b/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "enabled_by_default": true,
  "name": "Current b",
  "object_id": "betáp_current_b",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_current_b_zigbee2mqtt",
  "unit_of_measurement": "A",
  "value_template": "{{ value_json.current_b }}"
}
homeassistant/sensor/0x90395efffe185436/current_c/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "enabled_by_default": true,
  "name": "Current c",
  "object_id": "betáp_current_c",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_current_c_zigbee2mqtt",
  "unit_of_measurement": "A",
  "value_template": "{{ value_json.current_c }}"
}
homeassistant/sensor/0x90395efffe185436/energy/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "device_class": "energy",
  "enabled_by_default": true,
  "object_id": "betáp_energy",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_class": "total_increasing",
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_energy_zigbee2mqtt",
  "unit_of_measurement": "kWh",
  "value_template": "{{ value_json.energy }}"
}
homeassistant/sensor/0x90395efffe185436/produced_energy/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "device_class": "energy",
  "enabled_by_default": true,
  "object_id": "betáp_produced_energy",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_class": "total_increasing",
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_produced_energy_zigbee2mqtt",
  "unit_of_measurement": "kWh",
  "value_template": "{{ value_json.produced_energy }}"
}
homeassistant/sensor/0x90395efffe185436/power_factor/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "device_class": "power_factor",
  "enabled_by_default": false,
  "entity_category": "diagnostic",
  "object_id": "betáp_power_factor",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_class": "measurement",
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_power_factor_zigbee2mqtt",
  "unit_of_measurement": "%",
  "value_template": "{{ value_json.power_factor }}"
}
homeassistant/sensor/0x90395efffe185436/power/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "device_class": "power",
  "enabled_by_default": true,
  "entity_category": "diagnostic",
  "object_id": "betáp_power",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_class": "measurement",
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_power_zigbee2mqtt",
  "unit_of_measurement": "W",
  "value_template": "{{ value_json.power }}"
}
homeassistant/sensor/0x90395efffe185436/ac_frequency/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "device_class": "frequency",
  "enabled_by_default": false,
  "entity_category": "diagnostic",
  "object_id": "betáp_ac_frequency",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_class": "measurement",
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_ac_frequency_zigbee2mqtt",
  "unit_of_measurement": "Hz",
  "value_template": "{{ value_json.ac_frequency }}"
}
homeassistant/sensor/0x90395efffe185436/linkquality/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "enabled_by_default": false,
  "entity_category": "diagnostic",
  "icon": "mdi:signal",
  "name": "Linkquality",
  "object_id": "betáp_linkquality",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_class": "measurement",
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_linkquality_zigbee2mqtt",
  "unit_of_measurement": "lqi",
  "value_template": "{{ value_json.linkquality }}"
}
homeassistant/sensor/0x90395efffe185436/last_seen/config
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x90395efffe185436"
    ],
    "manufacturer": "Tuya",
    "model": "Smart energy monitor for 3P+N system (SPM02V2)",
    "name": "Betáp",
    "via_device": "zigbee2mqtt_bridge_0x00124b002a2e42ae"
  },
  "device_class": "timestamp",
  "enabled_by_default": false,
  "entity_category": "diagnostic",
  "icon": "mdi:clock",
  "name": "Last seen",
  "object_id": "betáp_last_seen",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.41.0",
    "url": "https://www.zigbee2mqtt.io"
  },
  "state_topic": "zigbee2mqtt/Betáp",
  "unique_id": "0x90395efffe185436_last_seen_zigbee2mqtt",
  "value_template": "{{ value_json.last_seen }}"
}

**Comment by gizmocuz** [comment]
Thank you for this!

**Comment by gizmocuz** [comment]
Could you try beta 16325, this should solve the issue. It's a bit of a hack, but if other zwave/zigbee devices use the same topic names it should work for them as well.

As it seems you are on the stable version, if you are using the native Domoticz install (via the bash install script), in Settings you can specify the beta as release channel. Then apply and go to setup->check for updates.

Or from your install folder issue:

`./updatebeta`

If you are using docker, just use the latest image

**Comment by lverti** [comment]
I tried it and it works perfectly. Thanks for the quick fix!
