### ISSUE TITLE
Suggestion for EnergyDashboard

### ISSUE THREAD

**Issue by erwann2000** [domoticz/domoticz#6202]
During night periods, my solar management system consumes 11w. (-11w of production)
The dashboard displays the absolute value of negative production and keeps in production mode with the wire animation from solar to house instead of grid to solar.

I want to know if is it possible to display negative values for solar production and animate the wire form grid to solar instead of from solar to house.

**Comment by gizmocuz** [comment]
@erwann2000 , it's strange that it reports the negative power... but you got a point here, it should display it correctly.
(I never imagined that this could be like that)
Going to work on this

**Comment by gizmocuz** [comment]
I think i got it fixed, but before something is messed up, how do you measure this?
Because that -11w is taken from your grid, it should be only visible there.
If your house does not use anything, and your solar uses -11W, then your grid meters power usage should display 11W.
(For instance your P1 should display 11Watt)

So, when thinking about this, what you see there is not correct, it should display zero for your solar, and 11 Watt on your grid meter!

**Comment by erwann2000** [comment]
Home electrical schematic it little bit different than the energy display dashboard.
Dashboard has 2 yellow wires (and it's great). In my home, I only have one wire for solar connection.

I have a clamp meter on grid connection and another on solar panel system (include inverter, gateway,...).


> If your house does not use anything, and your solar uses -11W, then your grid meters power usage should display 11W.
> (For instance your P1 should display 11Watt)

exactly


If I understand right:
P1/grid is the difference of blue wire and left yellow wire.

For example in my case during the night:

Home consumption 100w
Solar production -11w

I want something like this
P1 display: 111w
Blue wire: 100w
Left yellow wire: 11w with animation from grid to solar

Do you see my point of view?

**Comment by gizmocuz** [comment]
No, that is incorrect..  P1 should display 111W, and it probably already does so. (You can't change that!)
And your Solar should display 0 as it is not producing. Sure, it takes some power (you probably have Enphase)
I have a clamp around it as well, but (the Shelly) has a energy/power sensor for both up/down, I only use the producing values.
You also already know by now it takes 11 Watt to power the inverters, that won't change
If you gave wall plugs in your house, they also take 0.5/1Watt, nice to know, not needed to be displayed.
Same goes for chargers, tv, stb's, CV, etc etc

**Comment by erwann2000** [comment]
Yes in my example P1 display 111w.

You've right, I have Enphase in provider closed solution. 
And Shelly em (with Tasmota) for measurements.

Thanks for your time

**Comment by gizmocuz** [comment]
Why did you flash Tasmota? The shelly supports MQTT, and with a few simple config topics/payloads you can use the MQTT Auto Discovery hardware

If you want I can post them here

**Comment by erwann2000** [comment]
I prefer opensource firmware. It's not the simple way, but I can do what I want (python help a lot).
