### ISSUE TITLE
issue Reading Enever variable

### ISSUE THREAD

**Issue by enboer** [domoticz/domoticz#6205]
### Issue Guidelines

I am running the lastest domoticz 2024.7. From a LUA script I am reading the Enever pricing. But I get an old value. In the variable list in Domoticz GUI I see the data 2024-11-11, but when reading the variable I get a string with 2024-11-06. What am I doing wrong, I use the uservarable command the read the variable.
If I select the variable in the GUI and click Update, then I get the new correct value in the Lua script. Looks like the Enever pluging does not correct assigning the variable?

**Comment by enboer** [comment]
I have tested it with the same script, but then in the Events section of the GUI. Then the value is ok.

**Comment by gizmocuz** [comment]
Please upgrade your scripts to dzVents

There are two devices created for Electra/gas. You are using the one that says 'current price' and not the one that includes 24 hours from today/tomorrow?

**Comment by enboer** [comment]
I am reading the variable Enever_Electricity_24 with all the prices

**Comment by gizmocuz** [comment]
Try the other one? And also try with dzVents

**Comment by waltervl** [comment]
If still not able to read a user variable through Lua or dzvents use the forum https://forum.domoticz.com/ to get an answer. Github Domoticz is only for source code related issues.
