### ISSUE TITLE
Temperature Device shown a wrong prediction

### ISSUE THREAD

**Issue by acaonweb** [domoticz/domoticz#6210]
I have a zigbee device, from zigbee2mqtt that sends this values
<img width="352" alt="image" src="https://github.com/user-attachments/assets/2a3f5473-70a6-44b6-96ef-403647b8fb0f">

All the values are correctly received by domotcz using zigbee2mqtt plugin
It has worked for years correctly, but lastly (I can't understand when this issue is appeared) the demotics device shows a wrong prediction, and shows "heavy Snow" ever.

<img width="401" alt="image" src="https://github.com/user-attachments/assets/cfccaa51-297b-4033-8d76-43a44208b935">

Domoticz
Version: 2024.7 (build 16328)
Build Hash: f1c040fcb
Compile Date: 2024-11-12 12:23:13
dzVents Version: 3.1.8

**Comment by waltervl** [comment]
Are you using the Python plugin (https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin) or the Domoticz MQTT Autodiscover gateway? https://wiki.domoticz.com/MQTT#Add_hardware_%22MQTT_Auto_Discovery_Client_Gateway%22 

If python plugin then it is a problem in the forecast calculation by the plugin.
