### ISSUE TITLE
Zwave-JS-UI - General, kWh not showing Power Usage anymore

### ISSUE THREAD

**Issue by felixcharvin** [domoticz/domoticz#6216]
Hi,
My issue seems to be related to ticket #5346.

I'm using Zwave JS MQTT with Domoticz (2024.7) on Raspberry pi4.
I have multiple devices HKZW-SO05 to get power consumption and some of them are not displaying/updating the power usage anymore in "General, kWh" even if the device with only power consumption is up to date.
![image](https://github.com/user-attachments/assets/fc7aee79-7a17-4826-8bc4-a0f5545d3cdc)

I don't know why but I think the value key to read power has changed from 5-50-0-value-66048 to 5-50-0-value-66049 and Domoticz continue to try reading 66048 (for General, kWh).

![image](https://github.com/user-attachments/assets/2fb83561-32f4-4ae2-a36b-e16551b92c1e)
![image](https://github.com/user-attachments/assets/a2875f85-b49b-496f-aab8-74fc6e7bfc59)

I tried to reboot, delete/add device, update node, clear data node but without success.
How can I fix this?
Thanks

**Comment by waltervl** [comment]
More likely a discussion for the forum. But it seems you need to remove the retained mqtt config topics for the old devices, see for instructions: https://wiki.domoticz.com/MQTT#Delete_retained_topic

**Comment by felixcharvin** [comment]
Ok, thanks I cleared all retained message in zwave js ui, restart domoticz and it did the job!
