### ISSUE TITLE
[Feature Request] Support for LimeSDR hardware as universal radio receiver and transmitter?

### ISSUE THREAD

**Issue by Hedda** [domoticz/domoticz#622]
Maybe a few days early to to ask this, but do you think that Domoticz can and will support different wireless protocols via LimeSDR?

http://limesdr.org

LimeSDR is (or rather will be) a new open source low-cost software defined radio through which apps can be programmed to support any type of wireless standard, e.g. WiFi, UMTS, GSM, LTE (4G/5G), LoRa (LoRaWAN), Bluetooth, Zigbee, Z-Wave RFID, DVB Digital Broadcasting, FM/AM Radio, etc.

This means that you will not need a new hardware dongle for each wireless protocol, but one hardware dongle will support multiple wireless protocols and each protocol can be updated via via software just as apps on a smart phone, and new protocols can be added replacing hardware, (though you might want to add new antennas for optimal lengths)..

Additional info here about this Canonical/Ubuntu-backed LimeSDR (LimeSDR.org) project which aims to announce a crowd-sourcing campaign for their app-enabled SDR (Software-Defined Radio) open source programmable hardware in the end of april of this year:

http://insights.ubuntu.com/2016/02/26/mobile-world-congress-2016-day-4-recap/
http://insights.ubuntu.com/2016/03/23/mwc-2016-our-biggest-show-yet/
http://insights.ubuntu.com/2016/04/07/when-a-projector-and-app-enabled-software-defined-radio-cross-paths/

According to the LimeSDR.org project hope to crowd-source their first app-enabled SDR (Software-Defined Radio) hardware manufacturerd by Lime Microsystems any day now or either Kickstarter or IndieGoGo:

http://www.limemicro.com/blog-2/limesdr-available-soon-crowd-sourcing-campaign/

https://www.crowdsupply.com/lime-micro/limesdr

LimeSDR.org have already pre-announced this crown-sourcing effort on Twitter

https://twitter.com/LimeSDR_org

**Comment by gizmocuz** [comment]
Looks nice, but we have support for some good transceivers, and there is no need for more...
