### ISSUE TITLE
[Feature Request] Have official Domoticz client apps for Android and iOS

### ISSUE THREAD

**Issue by Hedda** [domoticz/domoticz#625]
I would prefer not to have to rely on client "remote control" apps from third-parties for controlling Domoticz.

Would you please consider making official Domoticz client apps for both Android and iOS? 

Recommend that you make it relativly easy on yourself by forking and porting existing open source apps that already does the same or similar.

I guess that like to suggest that simplest may be to fork and port the Android client app and iOS client app for OpenHAB:

https://github.com/openhab/openhab.android

https://github.com/openhab/openhab.ios

By forking and porting existingng apps from an active upstream project you will also benitites from their future commits.

**Comment by gizmocuz** [comment]
have you looked at our git repo ? i think there is an domoticz android app in there?
Also please use our forum
