### ISSUE TITLE
ZWave Device ID's have inconsistent leading 0's in device list

### ISSUE THREAD

**Issue by travellingkiwi** [domoticz/domoticz#629]
In current Beta (April 23rd 2016) on Raspberry Pi (Consistent between binary .img and tarball install).

The device ID"s seem a bit messy. e.g. for a device reported in OZW log as Node009, I get ID's of

0901
0000901
00000901

e.g.

```
    89  RaZBerry    00000901    1   Office Main Percentage  General Percentage  0.86%   -   -   Set UnusedRename Device Log 2016-04-23 17:32:02
    87  RaZBerry    00000901    1   Office Main Voltage General Voltage 225.100 V   -   -   Set UnusedRename Device Log 2016-04-23 17:32:01
    88  RaZBerry    0901    0   Office Main Current Current CM113, Electrisave  207 Watt    -   -   Set UnusedRename Device Log 2016-04-23 17:32:01
    85  RaZBerry    0000901 2   Office Main Unknown Usage   Electric    170.2 Watt  -   -   Set UnusedRename Device Log 2016-04-23 17:32:00
    93  RaZBerry    00000901    1   Office Main kWh Meter   General kWh 0.030 kWh

```

The ID 00000901 seems much more common. The rest just seem to appear once or so per node). The OZW log reports them ALL consistently as Node009.

**Comment by gizmocuz** [comment]
that is depending on the device type, it has always been like this ?

**Comment by travellingkiwi** [comment]
Yes It's aways been like this. For both release and beta.

**Comment by gizmocuz** [comment]
It is not a bug then
