### ISSUE TITLE
Report Status of switches locally switched

### ISSUE THREAD

**Issue by jotakar** [domoticz/domoticz#630]
Hello
I see that in ZWave there is not an instant report status for switches, so when you turn it ON/OFF locally (by hand) Domoticz doesn't report it's new status. It just report the status of and event in Group 1. In double relays this means that one relay has changed (1 or 2) but it doesn't say the relay switched.
There is an script that takes advantage of this and makes a refresh of the controller so the status of relays switched appears in controller. (thanks the author, Egregius, it's a good work).
Even more, there is associations with groups that must reflect the switch change status for every relay (not the status but it's change). Does controller software use it?

So I think that the software of controller could do that: refresh controller and show status of every  relay when locally switched, as it does when switched by program (from gui or any script).

I sent this issue to OpenZwave in github 
https://github.com/OpenZWave/open-zwave/issues/862#issuecomment-214993061

I do not know exactly how OZwave or Domoticz works, but I'm sure that there is a way to solve this issue.
Thanks

**Comment by gizmocuz** [comment]
Okey, what needs to be changed ? Can you make a pull request?

**Comment by jotakar** [comment]
Hello

Thank you for your answer.

I repeat that I don’t know exactly how Domoticz-Zwave work so I just can say what I want.

Now, the process followed when a switched is locally switched is:

Device sends an event to the controller .

The double relay receive and update the status of the double relay  

As status of double relay is updated a script is launched. This script does as if I click button reset of device in OZW control panel.

Then status of relay switched is read and Domoticz shows the new status.

So what I ask is that Domoticz does what this script does: it could do a refresh of the double relay module when locally (manually) switched.

I have open a pull request, I thonk I’ve do it well, as it’s not an easy work.

Thanks and have a nice day.

jotakar

De: gizmocuz [mailto:notifications@github.com] 
Enviado el: martes, 03 de mayo de 2016 6:23
Para: domoticz/domoticz
CC: jotakar; Author
Asunto: Re: [domoticz/domoticz] Report Status of switches locally switched (#630)

Okey, what needs to be changed ? Can you make a pull request?

**Comment by gizmocuz** [comment]
Something went very wrong with your pull request... did you see that you changed 238 files ?
That can not be true _lol_, please recheck the pull request, as i can not see what is changed now

**Comment by jotakar** [comment]
Eh???

Then I dont’ know how to open a pull request. I’m sorry, it’s too difficult. So I close the pull request. 

Github is a very complicated platform for me: I just want to make a suggestion, just a suggestion, I don’t’ want to create a new project or a new repository or a new branch or …. This platform seems a good platform for a MIT engineering ;)

Thanks

De: gizmocuz [mailto:notifications@github.com] 
Enviado el: martes, 03 de mayo de 2016 18:30
Para: domoticz/domoticz
CC: jotakar; Author
Asunto: Re: [domoticz/domoticz] Report Status of switches locally switched (#630)

Something went very wrong with your pull request... did you see that you changed 238 files ?
That can not be true lol, please recheck the pull request, as i can not see what is changed now

**Comment by gizmocuz** [comment]
Git is pretty easy and cool once you know how to use it

For example:
- fork this project on your own git account
- check this project out from your git account
- make the modifications
- commit and push your local changes to your git account

now on your git account page (at the forked projected), you should see a green button, make pull request
Pressing this button makes a pull request

Under windows i use 'tortuisegit' for all my git related handling

Otherwise, you could also write here what you changed (or is needed to change)

**Comment by jotakar** [comment]
Hello

Yes, perhaps. But I don’t know how to modificate the source code for getting what I ask for. So it’s no sense to make a pull request, is it?

And, well, I sent you what I want in this case. 

Thanks for your help.

De: gizmocuz [mailto:notifications@github.com] 
Enviado el: miércoles, 04 de mayo de 2016 2:22
Para: domoticz/domoticz
CC: jotakar; Author
Asunto: Re: [domoticz/domoticz] Report Status of switches locally switched (#630)

Git is pretty easy and cool once you know how to use it

For example:
-   fork this project on your own git account
-   check this project out from your git account
-   make the modifications
-   commit and push your local changes to your git account

now on your git account page (at the forked projected), you should see a green button, make pull request
Pressing this button makes a pull request

Under windows i use 'tortuisegit' for all my git related handling

Otherwise, you could also write here what you changed (or is needed to change)

**Comment by jotakar** [comment]
Hello

About this suggestion I have news from OZWave. Thye send me a new config file and now Domoticz shows fine the relays status .

I’ve published a post

https://www.domoticz.com/forum/viewtopic.php?f=17 https://www.domoticz.com/forum/viewtopic.php?f=17&t=7043&start=60#p85037 &t=7043&start=60#p85037

Now I wonder if it works with others devices like Philio PAN04. I have to try it  (TODO)

Thanks

De: gizmocuz [mailto:notifications@github.com] 
Enviado el: miércoles, 04 de mayo de 2016 3:14
Para: domoticz/domoticz
CC: jotakar; Author
Asunto: Re: [domoticz/domoticz] Report Status of switches locally switched (#630)

Closed #630 https://github.com/domoticz/domoticz/issues/630 .

**Comment by gizmocuz** [comment]
I read it works, and then does not work.... if you have an outcome please report

**Comment by jotakar** [comment]
Hello

I’ve  installed the new config file and it is working now.

If I’ve any news I will write in the post of github

Thanks

**Comment by jotakar** [comment]
I used the same modification to config file of a Philio PAN04 (doublé relay) and now when I switch manually I get status in the UI without any script or polling. So It could be a good idea test if this change is good indeed and it could be included in config files. I set a post with this idea in Open-ZWave Github.

> ```
>     <CommandClass id="37"> 
>             <TriggerRefreshValue Genre="user" Index="0" Instance="1">   
>                     <RefreshClassValue CommandClass="37" RequestFlags="0" Index="0" Instance="2" /> 
>                     <RefreshClassValue CommandClass="37" RequestFlags="0" Index="0" Instance="3" /> 
>             </TriggerRefreshValue>
>     </CommandClass>
> ```

**Comment by gizmocuz** [comment]
Can we close this issue ?

**Comment by jotakar** [comment]
There is more info about this in

https://github.com/OpenZWave/open-zwave/issues/880
https://github.com/OpenZWave/open-zwave/issues/862

So I add this comment and close the post.
Thanks.

**Comment by jonferreira** [comment]
I've tested the above code last week and while it "works" it dragged my Z-Wave network to a crawl. As far as I can see it essentially polls the node every 1 second which generates lots of Z-Wave traffic.

There's a possible fix in the latest OpenZwave version but that would require domoticz to update OpenZwave as well - https://github.com/OpenZWave/open-zwave/issues/880

@gizmocuz any chance next Beta can use the latest OpenZwave version?

**Comment by jotakar** [comment]
Of course, a report every second is a lot of ZWave traffic, in this case (Philio PAN04-1, old, not ZWave+)  this traffic is doubled because report are not unsolicited (there is a GET and then an answer).
 But in I think it is the only option (for this module at least). Or the script, that reports power when light is on and when it's off, and the total (I used it in my Domoticz), without instant readings.
Qubino's reports are unsolicited.
Any chance, the traffic depends on the interval of report set in config.

**Comment by jonferreira** [comment]
for me it was completely impossible to use, the whole network went down after a couple of minutes...
there appears to be some development on OPZ in an effort to get this one working, lets see how it goes.
on top of all this there's different behaviours for different Qubino  fw versions (mines S3) so it's a shot in the dark

**Comment by jotakar** [comment]
Don't use this refresh option for Qubino. 
In my net I get power reports and status reports  using associations (I published it another post in OpenZwave Github, there is a link some post above). I associate Qubino to a node 1.1 (multiinstance) and now every endpoind (~relay) send its data without any problem. I use S4 versión and I've read S3 had some issue with power report, but I don know about it. 
It's supposed that ZWave plus can be are updated on the air, Qubino doesn't gie any utility but perhaps you can get this update. Qubino has a good client support (it's just my experience).

**Comment by jonferreira** [comment]
yeah I tried that but something isn't right, I go to Hardware - groups and network and add 1.1 for each group on the Qubino line but after hours and days of waiting nothing shows up under group 2-8, i have no idea if it's saved.
Good idea about updating the firmware though, doubt it can be done without some specific Qubino controller or whatever but worth the shot

**Comment by jotakar** [comment]
Qubino is not battery powered, so changes in association or config are instantaneous, so if you don't see changes in groups&network after you change association then something is wrong.
Ah, the controller i'm using is Aeotec ZStick GEN 5
