### ISSUE TITLE
Custom Sensor with Average line on graphs

### ISSUE THREAD

**Issue by jonferreira** [domoticz/domoticz#632]
Hey,
Any chance we can get Average line added to a Custom Sensor device? 
Right now there's only Max and Min available.

**Comment by gizmocuz** [comment]
Please send me a PM on the forum with a download link to a database containing a custom sensor, that has data for more then 7 days plz

**Comment by jonferreira** [comment]
not a problem @gizmocuz, can you just give me a hand pointing out what "sensitive data" i should delete first?
or maybe just send the table you need instead of the whole DB - suppose you need whatever table that holds the historical data?
thanks for looking into this

**Comment by gizmocuz** [comment]
I think the most sensitive is the time when you turn on the bedroom Lights ;)
... i would empty the preferences table

**Comment by jonferreira** [comment]
done, thanks

**Comment by gizmocuz** [comment]
I have not received a PM on our forum from you...

**Comment by jonferreira** [comment]
strange, i've sent it again

**Comment by gizmocuz** [comment]
Strange, also received no email... my nickname on the forum is gizmocuz ;)

**Comment by jonferreira** [comment]
yeah...something is amiss, I send the PM, shows as sent but then if I refresh the page nothing shows up ...bizarre!
I've sent it twice already, no point on a third time I'd say...email?

**Comment by gizmocuz** [comment]
Could you try sending it again ?

**Comment by jonferreira** [comment]
I've sent it already but it doesn't show up on the Sent page so my guess is something's wrong...maybe it's cuz I'm sending a link?
Tried with multiple share sites already and this last time it was a Google Drive link...

**Comment by gizmocuz** [comment]
Just send me a PM on the forum with your email address and i will send ya an email

**Comment by jonferreira** [comment]
done, if you don't get it send a PM to SchattenMann

**Comment by gizmocuz** [comment]
Did not receive it, send you a PM, hope you receive it...

**Comment by jonferreira** [comment]
yeah I received your PM, no idea what's going on. replied it and now my message is shown as sent so you should have received it.
will send an email as well just in case

**Comment by gizmocuz** [comment]
Working, thanks i have a look at your dB

**Comment by jonferreira** [comment]
thanks, no idea why I couldn't send the first PM then!
oh well, thanks for looking into this and have a great weekend!

**Comment by gizmocuz** [comment]
Could you try beta #5163, there is now a average line being displayed

**Comment by jonferreira** [comment]
hmm seems to have crashed my domo instalation, I've completely lost access to the UI.
not home right now but will check what's going on in an hour

**Comment by gizmocuz** [comment]
thanks...

**Comment by jonferreira** [comment]
all up and running, looks great thanks!
min/max would "look" better as a range IMO but that's just my opinion.
cheers!

**Comment by jonferreira** [comment]
PS: just read your PM and replied
