### ISSUE TITLE
OTGW: PS=0 after PS=1

### ISSUE THREAD

**Issue by zuidwijk** [domoticz/domoticz#634]
Is it possible to not use PS=1 in Domoticz? Or send a PS=0 after sending PS=1?

> void OTGWBase::GetGatewayDetails()
> {
>   char szCmd[30];
>   strcpy(szCmd, "PR=G\r\n");
>   WriteInt((const unsigned char_)&szCmd, (const unsigned char)strlen(szCmd));
>   strcpy(szCmd, "PR=I\r\n");
>   WriteInt((const unsigned char_)&szCmd, (const unsigned char)strlen(szCmd));
>   strcpy(szCmd, "PR=O\r\n");
>   WriteInt((const unsigned char_)&szCmd, (const unsigned char)strlen(szCmd));
>   strcpy(szCmd, "PS=1\r\n");
>   WriteInt((const unsigned char_)&szCmd, (const unsigned char)strlen(szCmd));
>   **strcpy(szCmd, "PS=0\r\n");**
>   **WriteInt((const unsigned char*)&szCmd, (const unsigned char)strlen(szCmd));**
> }

I'm running Domoticz on a Rpi 3 and using it to control my lights and thermostat vi homebridge (working perfect). Yet I want to gather more information on what my boiler is doing. Therefore I like to use [Grafana](http://static.tweakers.net/ext/f/7XgbrwAtZiQ8ngKVbxiDd8oN/full.png)
Grafana is collecting information from otmonitor. Otmonitor stops working/collecting data when Domoticz send the PS=1 command.

I've tried manually to [add a PS=0](https://dl.dropboxusercontent.com/u/3577366/OTGW/Screen%20Shot%202016-05-01%20at%2016.03.09.png) after each PS=1 command and [that is working](https://dl.dropboxusercontent.com/u/3577366/OTGW/Screen%20Shot%202016-05-01%20at%2016.18.42.png).

Please let me know if this is possible, I'd like to have more insight information.

**Comment by zuidwijk** [comment]
https://github.com/domoticz/domoticz/blob/master/hardware/OTGWBase.cpp#L250

**Comment by gizmocuz** [comment]
Don't cross post... (both forum and github, also plz use github for developer issues)
You can use MQTT to grafana if you want to
