### ISSUE TITLE
Evohome radiator sensors flatlined since 3.5076

### ISSUE THREAD

**Issue by stuiow** [domoticz/domoticz#635]
Ever since updating to beta 3.5076 (to try and rid of a DST issue), all my Evohome radiator valve temperature sensors have flat-lined.
Set points are still being updated. 
I'm using a hgi80 to interface with my Evohome.
Updating to beta 3.5096 has made no impact.

**Comment by jonferreira** [comment]
i'm having no problems so far, v3.5104

**Comment by stuiow** [comment]
Ok, just updated to 3.5104 and it appears to be grabbing the temperatures fine again. 
I've only run it for 5 mins, enough time to grab temps from each zone, so so far, something has been fixed, also noting some more functionality with Evohome too.
Big thanks!
I'll close later, i'll give it a few hours first.
