### ISSUE TITLE
Add possibility to merge Energy/Temperature graphs

### ISSUE THREAD

**Issue by Cliff-R-K** [domoticz/domoticz#639]
Please add the possibility to be able to create custom graphs with both temp sensors and energy-meter.

**Comment by gizmocuz** [comment]
We should create a good custom graph, the current one created by user ?? could be improved big time
Any volunteers ?

**Comment by travellingkiwi** [comment]
How about you put all the data into rrd's (i.e. rrdtool) instead of trying to manage it yourself. 

Advantages
 Automatically handles data in a Round Robin fashion.
 Consolidates according to rules
 Easy to produce graphs
 Never grows. The DB is created to hold the data as described.

**Comment by gizmocuz** [comment]
I already explained on the forum/wiki somewhere how to store all data in influxdb and use it with grafana
but a native implementation of the both would be nice
Even using grafana to plot the graphs of the already existing data in the database would be nice
(Maybe via the plugin system)
Time is not on my side for this unfortunately
