### ISSUE TITLE
Unable to add more then one SWITCH in Dummy Sensor

### ISSUE THREAD

**Issue by hfbilly** [domoticz/domoticz#642]
Build 3.5113
Unable to add more than one virtual switch of type SWITCH. When trying to add the second one it renames the current one.

Have tried to add multiple virtual temperature sensors which does appear work

**Comment by hfbilly** [comment]
Build 3.5033 OKAY <- On Rasperberry Pi
Build 3.5070 NOT OKAY <- On Synology DS415
Build 3.5070 OKAY <- On Synology DS215 ( different from one below )
Build 3.5113 NOT OKAY <- On Synology DS215

**Comment by hfbilly** [comment]
Restart of domoticz resolved the issue.

**Comment by gizmocuz** [comment]
Next time, use the forum please!
