### ISSUE TITLE
Add user column to switch/sensor log

### ISSUE THREAD

**Issue by joopmartens** [domoticz/domoticz#643]
Currently the switch/sensor log only provides 2 columns.
1. The Date column with the date and time of the status change
2. The Data column contain the status of the switch/sensor

It would be nice to add a user column that contains the username of the user that initiated the status change. (In case the status change is initiated by a logged on user)

**Comment by gizmocuz** [comment]
This turned out rather hard/complex ...

**Comment by joopmartens** [comment]
That's too bad!
Anyway I appreciate the attempt.

Does this mean that it won't be implemented at all or will you keep it in the backlog?

**Comment by gizmocuz** [comment]
I keep it in the backlog... i just hoped to be finished ;)

**Comment by DewGew** [comment]
Is it possible to fetch user that switched a device? Its useful if I need to know who armed or disarmed the alarm and send a notification for instance...

**Comment by gizmocuz** [comment]
@DewGew , at the moment this is only logged in the normal log
The topic is about adding an extra field to the switch database table that logs which user operated it
After that it might be possible to also use this in the notification

**Comment by joopmartens** [comment]
It looks like this feature has been implemented in the latest stable release. My switch logs now include a user column that contains the username of the user that has operated the switch.

@gizmocuz , Many thanks for implementing this feature.  For me the ticket can be closed.

**Comment by gizmocuz** [comment]
Thanks for the feedback!
