### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by deece** [domoticz/domoticz#644]
Files seem to be checked in with a mix of (hard) CRLF and LF endings.

To fix this, add the attached file as .gitattributes, then (on a *nix machine):
`find . -name '*.cpp' -o -name '*.h' -o -name '*.html' -o -name '*.css' -o -name '*.svg' | xargs dos2unix`

You can verify the the fix with:
`find . -name '*.cpp' -o -name '*.h' -o -name '*.html' -o -name '*.css' -o -name '*.svg' | xargs file | grep CRLF`

[dot-gitattributes.txt](https://github.com/domoticz/domoticz/files/259059/dot-gitattributes.txt)

**Comment by gizmocuz** [comment]
I added the file, checked out the repo in a new folder, but the README.md file for example is still crlf
Did i do something wrong ?

**Comment by deece** [comment]
I missed adding that one in the attributes file - I did include the source code though. I'll add that now...

If you are on Windows, the files will still have CRLFs, but on other OSes, they should come out as just LF.

You'll also have to convert the files once as mentioned above, I can send a pull request if you would prefer that.

**Comment by gizmocuz** [comment]
I have added many more, and it should have worked, but also the source files are still containing CRLF when i check this out on the raspberry in a new folder

**Comment by deece** [comment]
Try https://github.com/InfernoEmbedded/domoticz/tree/line-endings

This is what I did:

```
git add .gitattributes

for ext in `cat .gitattributes  | grep -e 'text$' | sed 's/\*\.//; s/ text//'`; do find . -name '*.'$ext | xargs -n 1 dos2unix ; done

for ext in `cat .gitattributes  | grep -e 'text$' | sed 's/\*\.//; s/ text//'`; do find . -name '*.'$ext | xargs git add; done
```

I think that the files have been checked in with CR-LF from a unix machine at some point, so the CRs are hard-embedded in the files and git is unaware they are there, which is why they have to be stripped manually.

**Comment by gizmocuz** [comment]
I am unable to execute the above commands, maybe it is because of the message formatting in github
could you make a http://pastebin.com/ ?

**Comment by deece** [comment]
Ack, sorry, I didn't escape it properly, I've updated the comment now.

**Comment by gizmocuz** [comment]
Done... (new commit) hope all is ok now ?

**Comment by deece** [comment]
Looks good, thanks
