### ISSUE TITLE
Forecast.io feature request: Adding devices for future predictions

### ISSUE THREAD

**Issue by jaimevisser** [domoticz/domoticz#645]
Forecast of (at least) next day's temperature would be very handy to cool down my house a bit more during the night (using mechanical ventilation and a lower thermostat setting) so it won't be as warm during midday.

**Comment by sbouchex** [comment]
Why don't you use the HTTP/XML/XPATH parser and use the openweathermap.org data ? 
- Just declare a HTTP/HTTPS poller hardware with a url like http://api.openweathermap.org/data/2.5/weather?q=Paris,FR&mode=xml&APPID=xxx&units=metric where "xxx" is your API key and "q" your city
- Create a virtual device
- Add a script like https://github.com/domoticz/domoticz/blob/master/scripts/lua_parsers/example_owm.lua

And that's it !
