### ISSUE TITLE
Qubino ZMNHBD1

### ISSUE THREAD

**Issue by jotakar** [domoticz/domoticz#646]
Hi,
I've observed that this device send all reports for power reading to instance 1, althoug this readings come from two diferents relays. So it send a total power, power from realy1 and power fro relay2. Three values but all from the same nodeID.
I've read that this is a way for send multiinstance values: the module is asociated to three instances of controller and so the controller  can know who is who in the reports. At least, that is what I've understood. I'm not an expert in zwave, but a newbie.
So, is there a way in Domoticz for Reading the power consumtion of each relay and send this reading to the proper widget?
Thanks

**Comment by gizmocuz** [comment]
Are you able to debug/compile domoticz with visual studio 2015 community edition under windows ?
Then you can easily debug / test

**Comment by jotakar** [comment]
Oh, you think I'm a great programmer, thanks ;-)
Well, the frist: I would study and learn: 
- How ZWave Works (now a have an idea, a Little idea).
- Then how OpenZwave Works
- Then how Domoticz Works
- Then try to make litle modifications or so.
- An then, perhaps, I would be able to do what masters (as you) does. :-)

Perhaps I get this level, I believe utopias are posible!!!!

In this case, the first is that I don't know is the modification must be done ein controller firmware, zwae library or host software. But I'm afraid it's a question about controller, isn't it?
Thanks for your work.
