### ISSUE TITLE
auto-backup feature request

### ISSUE THREAD

**Issue by JoshyuNL** [domoticz/domoticz#647]
I was thinking of a way to add an auto-backup capability.
Could it be possible to store the database file either on a remote (FTP?) location or maybe even send it via email every X days?
I'm no coder so I have no idea about the specifics, but the total database should normally not get that big right? (<10mb) That could easily fit in to a modern email inbox.

**Comment by gizmocuz** [comment]
There is already an auto backup in domoticz
You can use for example rsync or a bash script to 'move'/'transfer' the backups to another location, or even mount an NFS volume as backup path
please use the forum
