### ISSUE TITLE
SPI bus speed

### ISSUE THREAD

**Issue by rtm-soft** [domoticz/domoticz#65]
Hello, I am not really familiar with GitHub so hopefully this info will get to you. There seems to be an issue with the spi bus speed and the Raspberry Pi 2. I have recompiled the file with modifying the bus speed to a lower value and now it will detect the PiFace. Before it was intermittent. Is it possible to set the spi bus speed from 4 Mhz to 500 kHz or so? Or maybe 1 Mhz? Thx Rene

**Comment by gizmocuz** [comment]
Hi Rene,

Which file did you recompile, and do you have a line number where you changed the code ?

You can also use our forum

**Comment by gizmocuz** [comment]
No feedback, closing issue
