### ISSUE TITLE
Support for the Thread protocol though code from upstream OpenThread project?

### ISSUE THREAD

**Issue by Hedda** [domoticz/domoticz#650]
Now that The Thread Group Alliance have released "OpenThread" as the official open-source implementation of the Thread networking protocol, would it be best to switch to their library and use as upstream dependency?

https://github.com/openthread/openthread

The BSD licensed C++ source code includes supports for End Device, Router, Leader & Border Router roles, and  can be found on Github. The implementation is said to be OS and platform agnostic with a radio abstraction layer, have a small footprint, and implement all Thread networking layers, namely IPv6, 6LoWPAN, IEEE 802.15.4 with MAC security, Mesh Link Establishment, and Mesh Routing. To quickly get started you can may to read the Examples README which explains how to build the code, start two nodes, and ping them.

Read more: http://www.cnx-software.com/2016/05/12/openthread-is-an-open-source-implementation-of-thread-iot-networking-protocol/#ixzz48Xioys2T

https://github.com/openthread/openthread/blob/master/examples/cli/README.md

http://www.threadgroup.org/

**Comment by gizmocuz** [comment]
If you like you can add support for this

**Comment by Hedda** [comment]
Another related idea could be for Domoticz to start a crowd-sourcing campign to get enough money to join the The Thread Group Alliance group:

http://www.threadgroup.org/joinus

**Comment by gizmocuz** [comment]
Sure, or the other way arround

**Comment by Hedda** [comment]
You could also just ask if Domoticz could The Thread Group Alliance group for free if the project can be classified as non-profit. I'm sure that the Thread Group Alliance group have no intentive of themself reasing out to make first contact with Domoticz. Domoticz is just too small. But if Domoticz reach out first then they might be open. Doesn't hurt to ask nice.

**Comment by gizmocuz** [comment]
True, but i do not see a benefit.
We can also use/make LoRa devices (based on MySensors), lorawan, the things network... all is already possible
