### ISSUE TITLE
OZWCP: Control Panel

### ISSUE THREAD

**Issue by jotakar** [domoticz/domoticz#651]
I'll tried to make a association using ozwp and I get an error in log
`Error: Webserver: File '/ozwcp/grouppost.html': No such file or directory (2)`

Looking for it I see in cp.js there are others HTML files lost. Where are they?
I tried to use Ozwcp for getting multichannel association.

**Comment by gizmocuz** [comment]
They are virtual
You can do this from the groups/network setup, if your node is 2, you can use 2.1 or 2.2

**Comment by jotakar** [comment]
Ok, so ... the error of page not found? doesn't mattter if i can use GUI.
I associate a Fibaro multisensor (group 1) to a relay of a Fibaro (node 4) or a Qubino (6) and itwork fine. In OZWCP I see the association.
But I tried to associate the same Fibaro to a relay of one relay of Fibaro (4.1) or a Qubino (6.2), and It doesn't work. In OZWCP I don't see the association. Fibaro supports Multichannel Association.

**Comment by gizmocuz** [comment]
Let me implement the missing control panel function

**Comment by gizmocuz** [comment]
Should be working now
