### ISSUE TITLE
Inconsistencies in i18n files

### ISSUE THREAD

**Issue by deece** [domoticz/domoticz#652]
I've added a tool to pull request #648 to help identify the missing/unused translations.

Example output:
No translation for 'evohome Devices', used in www/app/DashboardController.js, missing in 'i18n/domoticz-en.json'
Unused translation for '(filtered from _MAX_ total entries)', defined in 'i18n/domoticz-en.json'

**Comment by gizmocuz** [comment]
See my comment, no need to cross post plz
