### ISSUE TITLE
[MySensors] ACK timeout needs to be configurable

### ISSUE THREAD

**Issue by fallberg** [domoticz/domoticz#663]
When signing is used, the time for an ACK to be progressed can vary, and sometimes extend the current timeout in Domoticz. This also varies depending on network topology, so it would be good if the ACK timeout can be configurable for each node.

**Comment by gizmocuz** [comment]
Currently the ACK is handled in
**SendNodeSetCommand**
And it is blocking

If we increase the ACK to 10 seconds, domoticz will block up to 10 seconds

Is it possible to create me a sketch that will not ACK in 1 out of 3 times for example, so i can test?

Or maybe you would like to add a better ACK support yourself ?

I also think when no ack is received in the specified period (lets say 10 seconds), domoticz should send it again ?

**Comment by fallberg** [comment]
The simplest "fix" I would believe is to store a value together with the ACK flag for each node. If the default value is not working one then gets the ability to increase the timeout (just for that node). That way, it is possible to tune in all delays without affecting overall domoticz response times too badly. That is, the page where you to inform domoticz to wait for ACK, also let you specify the delay for it. It could be prefilled with whatever delay domoticz prefer to use. The actual delay needed can vary per node so it is difficult and potentially devastating or overall response times to treat all nodes with the same timeout if it is blocking.

**Comment by gizmocuz** [comment]
What could be expected as a maximum timeout ?

**Comment by fallberg** [comment]
That is a good question. It is difficult to say, as it depends on a set of variables. Chiefly, the number of hops in the network. 10s should cover any use case I can imagine. But if 10s would be the fixed timeout, and domoticz would be unresponsive during the wait, many people will start scratching their heads I think :) but then again, domoticz should only wait until the ACK is received which ought to be much sooner so the noneresponsiveness should only show when nodes are offline.

**Comment by gizmocuz** [comment]
New beta available (#5162), could you test if all is working ?

**Comment by fallberg** [comment]
Cool stuff! Yes, on my small test rig, it seem to work now. Thanks for that. Excellent!

**Comment by gizmocuz** [comment]
Thanks for the feedback, closing issue
