### ISSUE TITLE
Switch selector do (not?) working

### ISSUE THREAD

**Issue by endro** [domoticz/domoticz#670]
I created switch selector on Dummy hardware but can't configure (and error in console).

![ss1](https://cloud.githubusercontent.com/assets/6293998/15474082/69ca43cc-2103-11e6-9aa4-1580a884cbfd.png)

But working after modify this line:

```
LightsController.js:1469
$.bIsSelectorSwitch = (switchtype === 18); //devsubtype === "Selector Switch");
// ^^ switch selector devsubtype was "Switch"
```

![ss2](https://cloud.githubusercontent.com/assets/6293998/15474167/e65fd9d8-2103-11e6-9700-99c03b61d657.png)

This it a bug or am I doing something wrong?

**Comment by gizmocuz** [comment]
dont have this issue here (5169), could you update, clear appcache, browser cache, and try again?

**Comment by endro** [comment]
I just installed Domoticz. Latest version from Git, yesterday compiled.
1. Go to Hardware and create dummy
2. On dummy click "create virtual device" and select **Switch**
3. Go to switches and edit created switch
4. Change type to **Selector**
5. Save and try edit

If you select in 2. **Selector switch** instead **Switch** then working fine.

**Comment by gizmocuz** [comment]
You should select selector switch as type when creating the virtual sensor

**Comment by visser** [comment]
Hi @gizmocuz, can you make this more clear either via a notice or mention on the wiki as I ran into this too modifying an existing virtual switch and after some time searching this is the first mention I see to use the "Selector" type from the Hardware screen. Thanks @gizmocuz :)

**Comment by gizmocuz** [comment]
You could use the forum to ask those questions... If something is not clear please adjust the wiki
