### ISSUE TITLE
SwitchType: Dimmer, Type: SelectorSwitch

### ISSUE THREAD

**Issue by Lyr3x** [domoticz/domoticz#671]
If you add an SwitchType: Dimmer, Type: SelectorSwitch for Dummy Hardware, its impossibile to delete or edit this switch

**Comment by gizmocuz** [comment]
If i add a selector switch on a dummy hardware sensor in version 5169, then goto edit, then press the remove button, the switch is deleted
could you try updating domoticz, clear your browser's appcache and normal cache and try again?

**Comment by Lyr3x** [comment]
Yes but you need to add an Switch with:
SwitchType: Dimmer
Type: Selector Switch

I tried it again with same result. Running latest Beta

gizmocuz notifications@github.com schrieb am Mi., 25. Mai 2016, 10:52:

**Comment by gizmocuz** [comment]
I have a dummy hardware device
on the hardware setup page, next to the dummy hardware is a button 'create virtual sensor'
there i select the 'selector' type switch, and press add
It is now visible in the switches tab, and i am able to delete it

**Comment by Lyr3x** [comment]
This makes it a lot easier...<img width="451" alt="screen shot 2016-05-25 at 11 39 09" src="https://cloud.githubusercontent.com/assets/6078365/15535391/69244830-226d-11e6-869b-b353370862f7.png">

If i will press add i will get a dimmer switch which is uneditable/deleteable

**Comment by gizmocuz** [comment]
Try adding it the way i said/explained above

**Comment by Lyr3x** [comment]
Maybe i should explain what i want to do: My plan is to create da Volume slider as a Selector Switch dimmer. I added the sensor as you said and changed the type via edit to dimmer, now it is uneditable again.

**Comment by gizmocuz** [comment]
You are creating a 'selector' switch, and then you do not want a 'selector' switch but a 'dimmer'
Thats not possible
If you create a 'selector' switch, it is a 'selector' switch

**Comment by gizmocuz** [comment]
but i see its a bug

**Comment by Lyr3x** [comment]
allright. Have you an advise for my volume slider problem?

**Comment by gizmocuz** [comment]
Sorry i do not have this. You can add a normal dimmer ? or multiple devices ?
