### ISSUE TITLE
Monthly report empty for some types of values

### ISSUE THREAD

**Issue by lcupial** [domoticz/domoticz#674]
I've updated to version 3.5176 a few days ago and i can't see noe more monthly report. It's empty : 
![image](https://cloud.githubusercontent.com/assets/19619134/15625841/098716dc-24b6-11e6-913d-baaaa6be7c7c.png)
The data comes from a MySensor sensor and is of type V_VOLTAGE. Its IDX is 81.
Looking at the database i see that values for this is written in the Meter table : 
![image](https://cloud.githubusercontent.com/assets/19619134/15625863/804bdef6-24b6-11e6-9cae-3efad38dddf1.png)
But in the Meter_calendar table i don't see nothing about this value : 
![image](https://cloud.githubusercontent.com/assets/19619134/15625870/a2b3000a-24b6-11e6-8eda-cba0f155af6b.png)
Instead i found calendar data for this sensor in the Multimeter_calendar table : 
![image](https://cloud.githubusercontent.com/assets/19619134/15625881/cc0d06da-24b6-11e6-9a67-444eebc2154e.png)
The type V_VOLTAGE is not the only type of data for what i see that. Same issue with Forecast IO provider with the visibility and solar radiation : 
![image](https://cloud.githubusercontent.com/assets/19619134/15625908/69b31ce4-24b7-11e6-8e35-c4ef4e40d7d4.png)
![image](https://cloud.githubusercontent.com/assets/19619134/15625910/768aee74-24b7-11e6-85d5-a3dc99110d42.png)
I can see the same issues in database for them.

**Comment by gizmocuz** [comment]
Are you cross posting ?
https://www.domoticz.com/forum/viewtopic.php?p=87222#p87222

**Comment by lcupial** [comment]
No in anyway. I thought that I had to open an issue about that and did'nt saw the post in the forum.
All my apologies. I close the issue. And thank you for all your great work.

**Comment by gizmocuz** [comment]
I am working on a fix, and let you know on both places
Turned out... i have an voltage sensor from the motherboard

**Comment by gizmocuz** [comment]
Solved in #5177

**Comment by lcupial** [comment]
I confirm that all monthly reports come back. Thank you !
