### ISSUE TITLE
Add GPIO support for the Raspberry Compute Module

### ISSUE THREAD

**Issue by bierdok** [domoticz/domoticz#679]
The Compute Module is supported by wiringPi and can offer 46 pins (IN/OUT). 👍 

File to update : https://github.com/domoticz/domoticz/blob/master/hardware/Gpio.cpp
More info : http://pi4j.com/pins/model-cm-rev1.html
Output format : http://wiringpi.com/wiringpi-and-the-raspberry-pi-compute-board/
Update example : https://www.domoticz.com/forum/viewtopic.php?t=10694#p76401

**Comment by gizmocuz** [comment]
did you know there is also a filesystem that would work on many more systems and does not depend on wiringpi ?
It is called sysfs

maybe you could implement this ?

**Comment by bierdok** [comment]
Indeed, implement this interface could be awesome.
http://falsinsoft.blogspot.fr/2012/11/access-gpio-from-linux-user-space.html

But sorry I am not a C++ programmer.
