### ISSUE TITLE
Add Google Cloud Pub/Sub data export

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#680]
The idea is, as HTTP and FibaroLink,to give the ability to export the data to Google Cloud Pub/Sub service (see https://cloud.google.com/pubsub/)

I can work on it

**Comment by gizmocuz** [comment]
Looking good !
Maybe we should make a new base class for:
- Domoticz Remote push
- HTTP
- Fibaro Link
- Google Cloud

?

**Comment by sbouchex** [comment]
Yep, I wil try to factorize as much code as possible

**Comment by gizmocuz** [comment]
+1

**Comment by gizmocuz** [comment]
Did you made some progress ?

**Comment by sbouchex** [comment]
No but mostly due to a lack of time but I will have time soon.

I'm planning to use the google C++ API (see http://google.github.io/google-api-cpp-client/latest/) but it is only available on linux and not on Windows.
The library will be detected by domoticz's cmake in a folder "google-api-cpp-client" located outside domoticz folder like openzwave.

**Comment by gizmocuz** [comment]
I think (hope) the library is cross platform, so that would be great!

**Comment by sbouchex** [comment]
I saw some messages on the portability to Raspberry Pi but for sure, it's not working on Windows.

If we have it on linux at least, it will be great

**Comment by sbouchex** [comment]
Well... This library seems to be outdated and in maintenance mode, so let's avoid it

Next plan : Use Google Python PubSub API and plug it into domoticz

**Comment by gizmocuz** [comment]
Not all platforms run python, but... it could be a first step
Or maybe implement IFTTT ?

**Comment by sbouchex** [comment]
Other option : java : the jvm is loaded into domoticz (with jni) and comes
with a jar in charge of sending data to pubsub.

Java is cross platform and may bring new ideas

About ifttt, i think it's already possible to do it by using the 'maker'
from ifttt ( https://ifttt.com/maker)

Seb

**Comment by gizmocuz** [comment]
No, java is even worse... dont want to install a JRE when not needed ;)

**Comment by sbouchex** [comment]
Could be optional...

Anyway, let's try with python and we'll see.

**Comment by gizmocuz** [comment]
Thanks, it's included now!
