### ISSUE TITLE
Selector Switch HTTP requests not working in latest version 

### ISSUE THREAD

**Issue by gvanrekum** [domoticz/domoticz#683]
Since the latest version (V3.4834), the HTTP requests @ selector switches are not working anymore.
I reinstalled Domoticz (fresh install). Before updating to the latest version HTTP requests are working, after update not anymore.
The request is working when I put the link directly in my browser.
![naamloos](https://cloud.githubusercontent.com/assets/19725295/15771470/44633e98-296b-11e6-8248-000fa1bc7b20.png)

**Comment by gvanrekum** [comment]
Hi. Anyone an idea about this issue? I can't use my roller shutters the normal way right now, very irritating with this hot weather...

Thanks! :-)

**Comment by gizmocuz** [comment]
Please use our forum!
