### ISSUE TITLE
Bug with the New Custom Sensor

### ISSUE THREAD

**Issue by Merangle** [domoticz/domoticz#687]
Hello with the Beta branch 
Version: 3.5193
Build Hash: 4cf0106-modified
Compile Date: 2016-06-01 15:20:21

using a Synology DS212

I've created a Custom sensor to follow a 'minutes' delay sensor.

I'm unabled to use the edit button. I click and nothing appens. So I'm unable to delete the device. 
Notification and Log buttons work well.

Thanks for your help

**Comment by gizmocuz** [comment]
Please use our forum!
