### ISSUE TITLE
VS Project File Configuration

### ISSUE THREAD

**Issue by jrich523** [domoticz/domoticz#688]
@gerritv Thought i would post this as a separate issue rather than hijack the other one.

Recap:
Upon building (debug/release) VS is unable to successfully run domoticz because it doesnt have the references to the content it needs.

Cant the checked in project file have that in it? At least the www part

-wwwroot $(projectdir)..\www

I wasnt able to find any reference (in the manual or wiki) to the userdata switch, what should that point at? 
Which folders are content? Based on thing I've seen so far, Config, Scripts and json folders also need to be accessible?

With the dbase if i dont specify it, that will just end up in the build folder?

**Comment by gerritv** [comment]
I will do some experimenting tonight. I had it working but then blew the directory away so now going by aged memory :-)
I agree that the parameter should be set in the Github checked in files. At least for the Debug builds. Once we figure it out we can create a Pull request.

domotics.cpp has the command line parameters

**Comment by jrich523** [comment]
I did some searching and found that for the most part userdata is used to store log files and the such.
There is a szStartupFolder which is referenced in OpenZWave.cpp to set where the config folder. Then I searched for "Scripts" and found that its built each time for script usage (mostly in webServer.cpp) and its combined with szUserDataFolder, which can be set by the param.

This bring up another point, Since OpenZWave is a rather large part of this, it seems like that should be incorporated as well with a subrepo, however this is likely another issue :)

I had considered using a build script to move the content files/folders, which it seems might still  need to be done for the Config folder at the very least

**Comment by jrich523** [comment]
I did a little more digging and I've found that it seems like the code is designed to handle debugging situations. If you take a look at domoticz.cpp lines 503-520 you'll see there is a _debug definition. however I tossed a BP on it and it doesnt seem to trigger with the default debug configuration. 

According to 
https://msdn.microsoft.com/en-us/library/0b98s6w8.aspx
you'd have to enable /MTd or /MDd

which off hand i dont know how to do, or more importantly, what impact this has.

Also in looking at that code im uncertain if this would actually work correctly to set szStartupFolder to the root of the project.

I dont have enough knowledge in this area to know what the right way to approach this would be.

Thoughts?

**Comment by jrich523** [comment]
I found that if i set the working directory to $(projectDir).. it uses the root of the project as the working directory and seems function correctly (web pages load)

Im not sure what impact this has since I assume it uses the root of the project to create user content (DB etc?)

Perhaps use this with a user data location configuration? would just need to verify what ends up where so it doesnt make a mess or so that project files arent inadvertently modified by debugging the application

**Comment by gerritv** [comment]
Sorry for delay, had to deal with some side effects of an update to VS and its effect on a few of my other projects.
(And thank you for reminding me that this is the setting I changed, something we should propagate to Github after the discussion)

One of the great features of VS is Intellisense, it shows what code is being complied based on your various #defines throughout the code. So when your Configuration is set to Debug, the code highlighting automatically applies to things inside #ifdef _debug etc.

In Project/Properties/C/C++/Preprocessor, _DEBUG is defined automagically when you set the Configuration to Debug. /MDd is also set (you can see this in Command Line section of the same C/C++ properties area). The only thing missing is/was the $(ProjectDir).. in Debugging/Working Directory.

The usual location for the db is in C:\ProgramData\Domoticz. If you want to debug using this then I would copy that db file to the $(projectdir).. location. This way you use your usual configuration but any changes are isolated to your testing/modifications. The directories used when in Debug with $(ProjectDir).. set are those at the www, Config etc level. The domoticz.db file is created (if not already present) at the same level. In essence you are running in your own little world, all with the correct context. Anything you modify in that tree will be reflected in what is running when you start debugging.

**Comment by gerritv** [comment]
> Perhaps use this with a user data location configuration? would just need to verify what ends up where so it doesn't make a mess or so that project files aren't inadvertently modified by debugging the application

You don't need to set anything except that one missing parameter. You want all the files related to what you are testing/modifying/enhancing to be in the one context. Any code or other changes you make should be reflected in the exe once you recompile. VS will remind you that you need to compile if there are changes not reflected in the exe.
If you are going to push the changes into Git then you need to be sure not to add any created files, e.g. domoticz.db, by accident. It takes an explicit action to add them to Git so mistakes are avoided.

**Comment by gizmocuz** [comment]
See solution in "other" post

**Comment by jrich523** [comment]
Is someone doing a PR for this?

**Comment by gizmocuz** [comment]
Why ? See other post for the fix (startup folder ..)

**Comment by jrich523** [comment]
Yeah I got mine working but shouldnt that be configured in the repo so that if someone attempts to compile this they dont have to waste time figuring this out? It would be foolish to expect someone to read and fix something based on such an easy fix that could be incorporated in to the project file

**Comment by gizmocuz** [comment]
Its a user setting, not a project setting, that is why it is not in the git repo
(... well that was my experience)

**Comment by gerritv** [comment]
Adding:
    `<LocalDebuggerWorkingDirectory>$(ProjectDir)..</LocalDebuggerWorkingDirectory>
`after line 43 in domoticz.vcxproj makes it both Git checkin friendly (no .user files needed/wanted) and persistent.

I will create a pull in the next few days.
