### ISSUE TITLE
Wrong value set in user variable with blockly

### ISSUE THREAD

**Issue by Zorglupy** [domoticz/domoticz#689]
In a blockly script with a block "set x = "y" after z seconds" if x is a user variable (string) then the result is set with the string "y"" (a " is added at end of string)
Domoticz v3.4384

**Comment by gizmocuz** [comment]
Fixed in beta #5498 (commit https://github.com/domoticz/domoticz/commit/e5cf1921dcc4ef12fd6458c88418620724bdc2c2)
