### ISSUE TITLE
Blinds T12 (Confexx)

### ISSUE THREAD

**Issue by Shorty1983** [domoticz/domoticz#690]
Hi all,

I was so excited to see the latest beta (3.5228) implements "RFXCom Blinds T12 (Confexx)". But, it is not shown in the drop-down 'Type' menu when manually adding a switch. Looks like an issue there.

Very best regards,

**Comment by gizmocuz** [comment]
It should be availabe (Blinds T12), try updating to the latest beta, and clear your browser cache, and/or appcache
