### ISSUE TITLE
Add HTTP POST notification

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#692]
HTTP notification is only a HTTP "GET" implementation.

Slack.io (for example) is only supporting HTTP "POST"

The idea is to have some fields to set some parameters, data and some HTTP headers (could be usefull for authentication for example)

I can work on it

**Comment by gizmocuz** [comment]
That would be great, please make it 100% backwards compatible

**Comment by sbouchex** [comment]
Question: Should we add it to the "Custom HTTP/Action" section or should I make a new section ? New fields will be : A checkbox to enable POST and a text field for the content type. The other fields are the already existing one.

**Comment by gizmocuz** [comment]
I think a checkbox would be great indeed ! (And text box)

**Comment by sbouchex** [comment]
With the new fields activated when clicked ?

**Comment by sbouchex** [comment]
I forgot the most important field : The POST data :-)

**Comment by gizmocuz** [comment]
Yes, thats sounds perfect... Or just a Textbox for the POST data, when empty, issue a GET, else issue a POST? Maybe simpler?

**Comment by sbouchex** [comment]
Sounds good but I will add the "content type" as well. I may be mandatory for some vendors (slack for example)

**Comment by dynasticorpheus** [comment]
@sbouchex @gizmocuz Would HTTPS support also be possible? Telegram for example does not support HTTP with their API.

**Comment by gizmocuz** [comment]
I think you can enter https, and it should work ... can you test this ?
https://www.somedomain.com/aaa

**Comment by dynasticorpheus** [comment]
@gizmocuz Got it working now, tnx!

**Comment by dynasticorpheus** [comment]
@gizmocuz got HTTPS working now but it seems you can not use #FIELD1 etc in "POST Data" like the case for "URL/Action" Or at least doesn't seem to work for me? Telegram needs this to get it working.

Telegram "POST Data" example:

chat_id=#FIELD1&text=#MESSAGE

(chat_id you could hardcode but the text part ofcourse not)

**Comment by sbouchex** [comment]
OK, will do a fix soon
