### ISSUE TITLE
Kodi issue

### ISSUE THREAD

**Issue by MrBlue90** [domoticz/domoticz#693]
Hi folks,

This issue is based on the following topic:
https://www.domoticz.com/forum/viewtopic.php?f=23&t=12296

It seems that I'm unable to send multiple commands to Kodi from the same lua script.
Only the last command gets executed.

Tried the legacy Domoticz commands and used dzVents commands, but get the same result.

Hope you're able to find the root cause. Help is really appreciated!

**Comment by dnpwwo** [comment]
Responded with http://www.domoticz.com/forum/viewtopic.php?f=23&t=12296&p=88510#p88510, this is a feature of the event system not the Kodi plugin.

**Comment by dannybloe** [comment]
I agree that for commands that change the actual state of the device this is the best way to go. However, this fails with the 'execute script' command. That is a different beast and you should be able to just send a dozen of those and all of them should be executed. It's like the openURL command or sendNotification (with whatever syntax that is). They have to be queued and executed one by one. So yeah, for pause and play it doesn't make sense to have them execute all, just the last one.

**Comment by MrBlue90** [comment]
Why has this been closed?
The issue has not been solved yet.
