### ISSUE TITLE
Add some logging in case of errors when posting a notification

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#695]
When sending a notification (HTTP at least), any error is absorbed and nothing is logged

Adding some logging will be nice

I can work on it

**Comment by gizmocuz** [comment]
Only when compiling in debug mode
Or when there are errors please

**Comment by sbouchex** [comment]
That's just in case of errors because the remote error may throw an error some some reason and it's impossible to detect it.

**Comment by sbouchex** [comment]
see #696
