### ISSUE TITLE
Domoticz on Windows run as a service and notifications on Kodi

### ISSUE THREAD

**Issue by marcelmah** [domoticz/domoticz#698]
As already discussed on the Domoticz forum Kodi does NOT receive a notification from Domoticz when Domoticz is run as a service. When Domoticz runs as a normal program it does work.

In my case Domoticz and Kodi run on the same system.

Link to forum: https://www.domoticz.com/forum/viewtopic.php?f=23&t=3134&start=60

PS. In Domoticz settings: edited the Kodi IP to the actual IP and not the broadcast number, that did not work at all.

**Comment by gizmocuz** [comment]
Please provide a patch!

**Comment by marcelmah** [comment]
If I could I would... can't program myself unfortunately :-(
