### ISSUE TITLE
MQTT GetDeviceInfo does not work with scenes / no "getsceneinfo"

### ISSUE THREAD

**Issue by dcnoren** [domoticz/domoticz#700]
Domoticz API is well-documented and well thought out. For example, there is the "switchlight" and "switchscene" commands. There is mirrored functionality in MQTT, with "switchlight" and "switchscene" commands.

MQTT also has a command called "getdeviceinfo" which seems to not translate well to the HTTP API, as the HTTP API equivalent is simply /json.htm?type=devices and HTTP API for getting all scenes is /json.htm?type=scenes. However, there is no equivalent of "getsceneinfo" or "getscenesinfo" for MQTT.

Need a "getsceneinfo" function added for MQTT.

**Comment by gizmocuz** [comment]
Will be available in beta 5246 which should be available within the next hour.
Could not test it, but you should be able to call 'getsceneinfo' with the idx of the scene now
Plz let me know if its working

**Comment by dcnoren** [comment]
Wonderful, thank you! Works perfectly!

**Comment by legovaer** [comment]
I'm really sorry to open an issue which has closed over a year ago, but from what I see there's still something not implemented correctly.

When I send the following package via MQTT;
`{ "command" : "getsceneinfo", "idx": 3 }` I do get feedback via the topic `domoticz/out` but when I have a look in the domoticz logs, I see;

```
2017-08-16 14:45:31.429 MQTT: Topic: domoticz/in, Message: { "command" : "getsceneinfo", "idx" : 3 }
2017-08-16 14:45:31.430 Error: MQTT: Invalid data received!
```

It's a bit confusing that Domoticz is telling me that invalid data has been sent while it clearly answers with the correct & relevant information:

```
{
   "LastUpdate" : "2017-08-15 14:20:44",
   "Name" : "Watching TV",
   "Status" : "On",
   "Timers" : "false",
   "Type" : "Group",
   "idx" : "3"
}
```

**Comment by gizmocuz** [comment]
Good catch, with this request (only this request) after a success, it did not return, and instead logged an error message.
This has now been fixed, new beta version available within the hour
