### ISSUE TITLE
Blind vs Light/Switch Type

### ISSUE THREAD

**Issue by bxlouis** [domoticz/domoticz#701]
Would it be possible to add a "blind" type ?
For now, even when we set a switch as "blind" or "inverted blind", the type remains "Light/Switch".

It causes an issue with Homebridge, since it is therefore impossible to tell Siri "Open/Close my blind". We have to ask "Turn on/off my blind" which does not make sense !

Is there a chance that this type is added ?

**Comment by gizmocuz** [comment]
You can add blinds by manually already.
Also if Homebridge uses the 'Switchtype', it knows its a on/off, doorbell, or blind
