### ISSUE TITLE
Blinds T12 Unit Code

### ISSUE THREAD

**Issue by Shorty1983** [domoticz/domoticz#704]
In RFXmngr I have to enter an ID (e.g. in my case "33 02") and a 'Unit Code' (in my case 1 until 5) to select the different blinds to Open, Stop or Close. Domoticz does not include the 'Unit Code' option with Blinds T12, so I cannot get it to work.

I have tried 'ID 33 02 01' or combinations thereof, but no luck.

**Comment by Shorty1983** [comment]
Thanks for adding the unit code in the latest beta! It all works perfect now!

**Comment by gizmocuz** [comment]
Great!, Sorry forgot to tell you ;)
