### ISSUE TITLE
Add Kafka capability

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#706]
Apache Kafka is a high-throughput distributed messaging system (http://kafka.apache.org/)

First idea : Like for MQTT, give the ability to consume message on a kafka topic.
The message can be the same format as for MQTT.

Second idea : Add Kafka push (like HTTP/Fibaro) to export data over Kafka

We may use the librdkafka library from https://github.com/edenhill/librdkafka but having on Windows may be more difficult as the build requires more work

**Comment by gizmocuz** [comment]
why don't install the bridge software ? to bridge between the two systems ?
MQTT is more then enough for now...

**Comment by sbouchex** [comment]
Kafka is starting to be wide-spreaded since it integrates well with big data libraries (like Apache Spark). Kafka has also great capabilities in term of load balacing/failover accross brokers.

Regarding the data input, some devices may also want to push the metrics on a Kafka topic as well...

**Comment by gizmocuz** [comment]
you can install a simple bridge software to bridge between MQTT and Kafka
