### ISSUE TITLE
Openzwave and domoticz with poly-control

### ISSUE THREAD

**Issue by guigui79** [domoticz/domoticz#709]
Hello.
I fail to operate a Polypad with domoticz.
I domoticz v3.5254 on raspberrypi2.
I have a usb dongle z-wave aeonlabs Gen5.
I openzwave in v1.4-232-g4f7da52.
I managed to include Polypad on usb z-wave aeonlabs and everything is ok.
But domoticz it is "Unknown". with a status ! red.
This keyboard Polypad is compatible with domoticz ?
In advance, thank you for your answer.

**Comment by gizmocuz** [comment]
Best to use our forum for this.
Do you know if there is a configuration file in openzwave for the polypad ?
If not, this needs to be created first, tested, and supplied to openzwave

**Comment by guigui79** [comment]
Thank you for your answer.
I go on the forum and I found the solution.
It had to include in secure mode.
