### ISSUE TITLE
Kwikset deadbolt not working

### ISSUE THREAD

**Issue by jrich523** [domoticz/domoticz#710]
There is a forum post here

https://www.domoticz.com/forum/viewtopic.php?f=6&t=12325&p=88971#p88971

the short of it is that when you attempt to lock/unlock it cant detect that COMMAND_CLASS_DOOR_LOCK is available, it sends COMMAND_CLASS_ALARM to the switchlight function 
File: \Devices\ZWave\OpenZWave\OPenZWave.cpp
line: 1199
Function: SwitchLight

**Comment by gizmocuz** [comment]
Seems to be working on the forum, closing issue
