### ISSUE TITLE
RGBW Group can't be turned on

### ISSUE THREAD

**Issue by OliverHi** [domoticz/domoticz#712]
I have several RGBW controller running mysensors connected to a domoticz (on a pi) via a serial controller. I can control these quite well one by one.
I do want to be able to control them all together too though, so I created a group and added all 3 of them. Using the off button I can turn them all off no problem. Using the on button doesn't work though. The individual RGBW lights switch to on in the domoticz overview but they don't get turned on in "reality".
Why is that?

**Comment by gizmocuz** [comment]
No idea, best to debug with a mysensor node in serial mode and log what is happening
But please use our forum for these questions, also post your sketch in the forum post
