### ISSUE TITLE
Blocky involving time doesnt work

### ISSUE THREAD

**Issue by micml75** [domoticz/domoticz#714]
Whenever I set up a blocky using time it doesnt work (domoticz time, raspberry pi and modem time all show correct time)

**Comment by gizmocuz** [comment]
Please use our forum!

**Comment by micml75** [comment]
I did, more people run into the same issue and no solution is provided. Seems like a bug

**Comment by gizmocuz** [comment]
Please post a link here to the forum post then

**Comment by micml75** [comment]
https://www.domoticz.com/forum/viewtopic.php?p=89497&sid=5c0b0e150752b3480e0c33b034193a7d#p89497

**Comment by gizmocuz** [comment]
Okey thanks, but i see also a bad blockly as screenshot.
Anyway, give me 1 blockly that should work, and does not work, and i will try to replicate it
For instance, i have blockly's with time and they do work (if switch = on and time < 22:00, then ...)
