### ISSUE TITLE
Broadlink RM Mini 3 WiFi IR Blaster for Home Automation

### ISSUE THREAD

**Issue by Hedda** [domoticz/domoticz#715]
Please add support for Broadlink RM Mini 3 WiFi IR Blaster for Home Automation

http://www.cnx-software.com/2016/06/28/broadlink-rm-mini-3-is-a-10-wifi-ir-blaster-for-home-automation

Broadlink supposedly provide API documentation if asked by reputable developers.

Broadlink RM Mini 3 WiFi IR Blaster is similar but much cheaper than the Xiaomi Mi Smart Remote Center and unlike the Xiaomi device, the device from Broadlink is available in English

http://www.cnx-software.com/2015/10/07/xiaomi-mi-smart-remote-center-review/

**Comment by JZacharie** [comment]
To do the same with cheap price and open source.

https://github.com/JZacharie/nodeMCU_IrBlaster

**Comment by chatainsim** [comment]
@Hedda Yu can use the Broadlink Mini with this python script:
https://github.com/davorf/BlackBeanControl
Use a virtual switch.
