### ISSUE TITLE
Webroot without ending slash should auto redirect

### ISSUE THREAD

**Issue by l-t-k** [domoticz/domoticz#719]
Running Ubuntu Server 14.04 with domoticz and tried on several browsers:
1. http://myip:port/domoticz  --> error
2. http://myip:port/domoticz/ --> ok

Domoticz should auto redirect if option 1 to 2.

Used option:
DAEMON_ARGS="$DAEMON_ARGS -webroot /domoticz"

**Comment by gizmocuz** [comment]
This is not a bug, you are requesting a file "domoticz"
My synology nas does the same, i also have to enter a slash at the end to go to the folder
