### ISSUE TITLE
lost temps

### ISSUE THREAD

**Issue by jfzw42** [domoticz/domoticz#72]
Hi there,

With the latest build, I lost all temperature graphs (current temperature is available for all sensors on the dashboard though). The report sheet displays 'NaN' instead of any value but all months are displayed like if data are available but cant be displayed.

EDF Teleinfo history is OK.
Let me know how I can debug things for you.

Cheers

JF

**Comment by gizmocuz** [comment]
Should be solved now

**Comment by jfzw42** [comment]
confirmed ! big thanks !

i take this opportunity to thank you a lot for the great job.
