### ISSUE TITLE
HTTP Service is hanging from time to time

### ISSUE THREAD

**Issue by d00616** [domoticz/domoticz#720]
I'm using domoticz commit 711a11889d09d42efeca5b97b21712a5ae5dc8a8 (Fri Jul 1 20:10:34 2016 +0200) with openzwave a379e3a799719fa5d7c9958d2a16d98482e8d015 (Tue Jun 28 23:40:28 2016 +0800).

From time to time the HTTP service doesn’t respond. When i run strace, the running process reports a endless loop with nanosleep:

```
# strace -p 21006
Process 21006 attached
nanosleep({1, 0}, NULL)                 = 0
nanosleep({1, 0}, NULL)                 = 0
nanosleep({1, 0}, NULL)                 = 0
```

A lot of STREAMs are reported by netstat:

```
# netstat -anp | grep 21006 | grep STREAM | wc -l
997
```

Lsof reports 15986 open sockets.

**Comment by gizmocuz** [comment]
No idea what to do with this... i can not reproduce it.
Can you debug the issue and make a possible pull request?

**Comment by d00616** [comment]
Thank you for testing. I try to debug it.

**Comment by d00616** [comment]
I thin this is a problem with a socketpair opened every 30 seconds in MQTT/net_mosq.c When no mqtt service is available this socket pair is not closed.

I think the problem is in _mosquitto_connect_init, but i have no Idea how to fix it.

**Comment by gizmocuz** [comment]
Could you post this on the mosquito forum?

**Comment by d00616** [comment]
I have searched in bugzilla. It looks this bug is already fixed.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=484692

 _mosquitto_connect_init looks different at https://github.com/eclipse/mosquitto/blob/master/lib/mosquitto.c#L392

**Comment by gizmocuz** [comment]
Great find!
Could you make a git pull request for domoticz ?

**Comment by gizmocuz** [comment]
Is this issue solved?

**Comment by d00616** [comment]
Yes it is. I have tested it before i created the pull request.

**Comment by gizmocuz** [comment]
Thanks for the feedback, and issue closing
