### ISSUE TITLE
Add digest access authentication camera

### ISSUE THREAD

**Issue by dynasticorpheus** [domoticz/domoticz#721]
Some camera's do not allow basic authentication and need digest. If I am correctly assuming that libcurl is currently pulling the images it might even be as simple as adding the **_CURLAUTH_DIGEST_** parameter?

Below works when run from command line
`curl --digest -u username:password -O http://192.168.1.10/cgi-bin/img-0.cgi`

**Comment by dynasticorpheus** [comment]
Created my first pull request ever to try and solve this :)

**Comment by gizmocuz** [comment]
Thanks looking good !

**Comment by dynasticorpheus** [comment]
Confirmed, camera requiring digest auth now working as expected.
