### ISSUE TITLE
Wrong cost and usage counter in Utility report when counter is 0

### ISSUE THREAD

**Issue by trusnak** [domoticz/domoticz#729]
Hello

Last week I found strange output in Utility report. It's from z-wave based Aeotec Micro Smart Energy Switch G2 connected to Aeotec Z-Stick S2.

Counter = 0
Usage = 571.929
Costs = 2201.93

It looks like it was zeroed from previous day:

2   Saturday    571.905 0.018   0.07  
3   Sunday  0.000   571.929 2201.93 

Is it a bug in algorithm how the Usage and Cost is counted?

**Comment by gizmocuz** [comment]
Please show us the total report

**Comment by trusnak** [comment]
<img width="1271" alt="screen shot 2016-07-09 at 22 25 39" src="https://cloud.githubusercontent.com/assets/504905/16710108/341cf8d2-4624-11e6-8668-a3541cefa36d.png">

**Comment by gizmocuz** [comment]
Thanks!
Looks like your counter value went into loop?

**Comment by trusnak** [comment]
I have no idea what happened. At the Sunday nobody was at home. Power consumption should be ~0kWh.
Total usage is not only one which is wrong. The same behaviour, the counter reset to 0 at Sunday, I can see at power consumption for each phase. I have 3-phase power. The current and voltage counters are not affected.

**Comment by gordonb3** [comment]
I'm experiencing similar read outs. The underlying cause in my case is that domoticz has started to randomly crash for no apparent reason and more than a day may pass before I can restart it if I was away. The result is that I have no measurements for that day (or days) and these are registered as counter value 0. This is where the usage calculations go wrong.

**Comment by gizmocuz** [comment]
This can be caused by a power outage indeed

**Comment by gordonb3** [comment]
Ah... Well. It looks like I'm a victim of the crash on bad P1 message bug. I disconnected the cable and Domoticz has now been running the whole of the weekend. Of course now my usage report is through the roof. While there is no solution for this issue, is there a way that I can inject fake values in the database to fix the totals?

**Comment by rkluwen** [comment]
You could open the domoticz.db file in any sqlite editor to hack it.

**Comment by gizmocuz** [comment]
Most of the times it is solved the next day.. unless you had a really bad counter value.
Then you can shift-click on the wrong point in the month/year graph

**Comment by gordonb3** [comment]
@gizmocuz 
Well, the point here is that it appears to insert a zero value if it can't find one for a specific day. Next thing is that it does not add the drop from 1.500 (I have quite a new meter) to zero as a negative value, but it does add the increment from the auto-inserted zero back to 1.500 when domoticz/P1 functionality is restored. The result is that for every missed (non-consecutive) day I get a +3.000 (T1+T2) on my usage report.

Shift-click does work to remove the bad points. Thanks for that hint. It makes the graphs readable again.

**Comment by gizmocuz** [comment]
Thats not the case as i had days without readings before
