### ISSUE TITLE
Request: Add user column to sensor log

### ISSUE THREAD

**Issue by joopmartens** [domoticz/domoticz#736]
Currently the switch/sensor log provides 2 columns: Date and Data.
For logging purposes I would love to have an extra column that shows the user that has initiated the sensor state change.

In case the state change has not been triggered by an authenticated user this value could simply contain "unknown"  or left empty.

For an even better enhancement this field could also log the subsystem that triggered the sensor state change in case it has been triggered by e.g. Events, LUA or a timer.

Anyway many thanks for providing this great software!

**Comment by gizmocuz** [comment]
I think you already requested this in #643

**Comment by joopmartens** [comment]
Whoops, totally forgotten that.
My apologies for the inconvenience.
