### ISSUE TITLE
Domoticz doesn't trigger python script on events

### ISSUE THREAD

**Issue by atharvai** [domoticz/domoticz#737]
Hi I have Domoticz running on RPi B1. 

```
Version: 3.4834
Build Hash: 8398125
Compile Date: 2016-03-02 07:43:51
```

under the domoticz directory I see `scripts/python` directory with `domoticz.py` and `reloader.py`. Does this mean Python support is enabled? If so, the sample script `script_device_PIRsmarter.py` which is also in that directory doesn't get triggered. I added a log line as the first action line. 

Any advice on how I can get python scripts to be triggered on events?

**Comment by sbouchex** [comment]
python must be enabled at build time. To check if so, just do : ldd <path of the domoticz binary> | grep python

If something comes out, it's enabled
If nothing, I'll advice you to build domoticz by your self and enable python at build time
