### ISSUE TITLE
VirtualDevice creation adds a dummy value which is making graph invalid

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#742]
When creating a virtual device (from the createvirtualsensor webserver command), a dummy value is added to the database : For example, for a sound device, the value is 65dB

This data insertion makes graph false as it's not a real data coming from a device.

Solutions :
- Do not insert a data to avoid this but the drawback is that the device is not visile in the device list
- Insert a data to make the device visible but flag the data as invalid to avoid any computation

**Comment by gizmocuz** [comment]
Or you shift-click on the data point to remove it?

**Comment by sbouchex** [comment]
yes, but the user must think of it. Why not adding this dummy point ? Is it necessary ?

**Comment by gizmocuz** [comment]
For the easy user experience 
That is why advanced users know how to delete a data point
