### ISSUE TITLE
Serial Port closed

### ISSUE THREAD

**Issue by rkluwen** [domoticz/domoticz#746]
2016-07-21 09:37:35.714  Error: Serial Port closed!... Error: End of file

Since one or two days, I am getting the above error on the built-in serial port of my Raspberry Pi (/dev/ttyAMA0).

It is connected to my P1 smart meter and never had problems with it before.

Restarting Domoticz seems to solve the issue, for one minute or so and then I get the error again.

**Comment by gizmocuz** [comment]
I've seen another user reporting this on the forum.. But I can not remember any code changes to the serial class.... Strange....
Could it be an OS update?

**Comment by rkluwen** [comment]
Yes, an OS update is very well possible. I will try to debug after I'm done with the current MyDomoticz server changes,

**Comment by rkluwen** [comment]
I found out what the problem was. I was using the built-in Raspberry serial port. But the same port was also still in use as a login-console. I had forgotten to disable that in /etc/inittab.
