### ISSUE TITLE
Filter values for openzwave sensors

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#748]
I do have   "Qubino ZMNHAA2 Flush 1" Relay zwave device but the temperature pin is not connected to a sensor. So the returned value is -999.9 °C which does not make sense.
However, this valus is stored anyway.

I have the same "Qubino ZMNHBA2 Flush 2 Relays" where the power consumption is reported as "-214748364.800 kWh" :-) (probably because this relay has never been connected to the power)

If one day, I add a temperature sensor, the average value will be wrong and I will have to delete/add the sensor again.

Why not adding some filtering (hardcoded or not) to avoid emitting dummy values into the rest of the server ?

**Comment by gizmocuz** [comment]
It would have been better if openzwave or the quibino itself did this...
But yes... Your right... Could you make the request?
I wonder what the hex value is of the meter, or the unit... Maybe we can check on this...

**Comment by sbouchex** [comment]
I can work in it. I have contacted Qubino to have more details

**Comment by sbouchex** [comment]
still waiting for Qubino response (Summer period...)

**Comment by sbouchex** [comment]
OK, got an answer from Qubino:
- For the -999.9°C : That's an hardcoded value to say that the temperature sensor is not connected.
- For the 214748364..., it was a device issue.

I'll propose to filter out the values based on the vendor id and eventually, the product id as well, the sensor value will not be emitted if the value is filtered out.

**Comment by gizmocuz** [comment]
Thats OK, could you make a patch that when a temp value of -999.99 is received we do not send it ?
(just return in the update value function)

**Comment by sbouchex** [comment]
yes, that's the plan and I will try to make a generic function in order to filter other potential values in the future
