### ISSUE TITLE
Compilation error - FreeBSD 10.2

### ISSUE THREAD

**Issue by leodesigner** [domoticz/domoticz#75]
Hi,
I am trying to compile domoticz under FreeBSD 10.2,
following instructions https://www.domoticz.com/wiki/FreeNAS
Here is the error I am received:

```
make -j 2

[ 14%] Building C object MQTT/CMakeFiles/mqtt.dir/thread_mosq.c.o
[ 15%] Building C object lua/src/CMakeFiles/lua.dir/lctype.c.o
[ 16%] Building C object lua/src/CMakeFiles/lua.dir/ldebug.c.o
[ 16%] Building C object MQTT/CMakeFiles/mqtt.dir/time_mosq.c.o
[ 17%] Building C object MQTT/CMakeFiles/mqtt.dir/tls_mosq.c.o
[ 17%] Building C object lua/src/CMakeFiles/lua.dir/ldo.c.o
/home/domoticz/domoticz/MQTT/tls_mosq.c:147:22: error: use of undeclared identifier 'AF_INET6'
        ipv6_ok = inet_pton(AF_INET6, hostname, &ipv6_addr);
                            ^
/home/domoticz/domoticz/MQTT/tls_mosq.c:148:22: error: use of undeclared identifier 'AF_INET'
        ipv4_ok = inet_pton(AF_INET, hostname, &ipv4_addr);
                            ^
2 errors generated.
--- MQTT/CMakeFiles/mqtt.dir/tls_mosq.c.o ---
*** [MQTT/CMakeFiles/mqtt.dir/tls_mosq.c.o] Error code 1

make[2]: stopped in /usr/home/domoticz/domoticz
1 error

make[2]: stopped in /usr/home/domoticz/domoticz
--- MQTT/CMakeFiles/mqtt.dir/all ---
*** [MQTT/CMakeFiles/mqtt.dir/all] Error code 2

make[1]: stopped in /usr/home/domoticz/domoticz
A failure has been detected in another branch of the parallel make

make[2]: stopped in /usr/home/domoticz/domoticz
--- lua/src/CMakeFiles/lua.dir/all ---
*** [lua/src/CMakeFiles/lua.dir/all] Error code 2

make[1]: stopped in /usr/home/domoticz/domoticz
2 errors

make[1]: stopped in /usr/home/domoticz/domoticz
*** [all] Error code 2

make: stopped in /usr/home/domoticz/domoticz
1 error

make: stopped in /usr/home/domoticz/domoticz
```

Something is missing...

**Comment by gizmocuz** [comment]
if you google (this is a search engine) for "tls_mosq.c error use of undeclared identifier AF_INET6"

you will find:

http://www.domoticz.com/forum/viewtopic.php?f=6&p=50034

Please propose a patch

**Comment by leodesigner** [comment]
Adding the following includes to domoticz/MQTT/tls_mosq.c
 is solving the compilation problem under FreeBSD.

```
#include <sys/types.h> 
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
```

However, I am not sure about other platforms.
Should we put there some kind of conditional ifdef FREEBSD ?

**Comment by gizmocuz** [comment]
From the forum i see than only

#include <sys/socket.h>

should be added, is that also working ?

**Comment by leodesigner** [comment]
I just followed man inet_pton and took includes from it.
Yes, adding just #include < sys/socket.h > is working too.
But I have another error:

```
/home/domoticz/domoticz/hardware/serial/serial.cpp:6:11: fatal error: 'alloca.h' file not found
# include <alloca.h>
          ^
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/domoticz/domoticz
*** Error code 1

Stop.
make[1]: stopped in /usr/home/domoticz/domoticz
*** Error code 1

Stop.
make: stopped in /usr/home/domoticz/domoticz
```

**Comment by gizmocuz** [comment]
if you can make a patch, please do (#if #else)

**Comment by rubenverhoef** [comment]
I get this error (FreeNAS 9.3):

[ 30%] Building CXX object CMakeFiles/domoticz.dir/main/Camera.cpp.o
CC: unrecognized option '-static-libstdc++'
CC: unrecognized option '-static-libstdc++'
CC: unrecognized option '-static-libstdc++'
[ 31%] Building CXX object CMakeFiles/domoticz.dir/main/domoticz.cpp.o
CC: unrecognized option '-static-libstdc++'
[ 31%] Building CXX object CMakeFiles/domoticz.dir/main/EventSystem.cpp.o
CC: unrecognized option '-static-libstdc++'

The build is done after that but when i start it with ./domoticz i get: 
2015-09-27 13:24:01.604  Domoticz V2.3187 (c)2012-2015 GizMoCuz
2015-09-27 13:24:01.604  Build Hash: 1916eb3, Date: 2015-09-27 09:25:27
2015-09-27 13:24:01.604  Startup Path: /usr/home/domoticz/domoticz/
2015-09-27 13:24:01.630  Active notification subsystems: http (1/9)
2015-09-27 13:24:01.630  Webserver started on port: 8080
2015-09-27 13:24:01.631  Hardware Monitor: Started
2015-09-27 13:24:01.631  Started shared server on: ::

but when i go to IP:8080 it does not respond..
any ideas?

**Comment by gizmocuz** [comment]
Update boost, gcc, or the whole system

**Comment by rubenverhoef** [comment]
i already did that, but when i compile domoticz inside a finch jail it works! (but i get the same error about -static-libstdc++) but well it works !
