### ISSUE TITLE
Selector type broken V3.5143

### ISSUE THREAD

**Issue by VincentGijsen** [domoticz/domoticz#750]
Hi Guys,

the selector type seems broken in this beta V3.5143. 

Reproduce:
- Edit ligtswitch type
- Set _switchs-type_ to _Selector_
- The _switch icon_ selector is broken afterwards.

This regresses into the 'saving' of the item. Appart from that, when first selecting other type, saving, and set it to selector. Seems to fix it partly (at least the GUI). However when adding items to the last later on. they don't appear in the final item.

**Comment by gizmocuz** [comment]
Is this also the case when you add the switch via the create virtual sensor at the dummy hardware?

**Comment by VincentGijsen** [comment]
Well it seems to work better, although I encountered another bug:
1. If added the virtual selector dev.
2. Remove all the selector items (I somehow managed te remove ALL if the items, including the 0 (off item)
3. Change icon to alarm (not sure if it is relevant, but)
4. save the changes.

result:
now you can nolonger edit the device (probably due a split on the null obj):

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Uncaught TypeError: Cannot read property 'split' of undefined
XHR finished loading: GET "http://192.168.88.165:8080/json.htm?type=devices&filter=light&used=true&order=Name&lastupdate=1469699830&plan=0".
XHR finished loading: GET "http://192.168.88.165:8080/json.htm?type=devices&filter=light&used=true&order=Name&lastupdate=1469699830&plan=0".
```

To get back to your original question, it works better, but
