### ISSUE TITLE
Blinds percentage broken

### ISSUE THREAD

**Issue by TheGuv** [domoticz/domoticz#753]
Selecting switch-type 'Blinds Percentage' gives a percentage bar that is not movable and also obscures the Log, Edit, etc. areas as shown in the image. This makes it unusable and appears to be the case both in Firefox 47.0 and Chrome  51.0.2704.106 (64-bit).

![domoticz-blind](https://cloud.githubusercontent.com/assets/1945094/17085091/7503296c-51c7-11e6-86a3-1ed46cb06607.jpg)

**Comment by hansworst24** [comment]
I'm on 3.5298 and created 2 virtual blinds for testing. 
- One is of Type : Light/Switch, Subtype : Switch, SwitchType : Blinds Percentage. This one works properly
- Other is of Type : Lighting 1, Subtype : X10, SwitchType : Blinds Percentage. This one shows the same behavior as you

Each is created in a different way : The X10 one is created when selecting "Manual Light/Switch", the other one was created by going to your virtual hardware, and adding a switch from there. This one works. 

So you may want to try recreating the Blinds Percentage a different way, to see if that sorts the issue !

**Comment by TheGuv** [comment]
Thanks hansworst24. I'm on 3.5290.

I can add that creating dummy X10 device (Type:SubType: General Percentage) seems to have a working percentage widget. My ESP8266 based blind node which I let present itself and then enabled in the Devices list (shows as Blinds RollerTrol, Hasta new) does not.
