### ISSUE TITLE
Enchancement, read HTTP output from Meteohub

### ISSUE THREAD

**Issue by stuiow** [domoticz/domoticz#756]
Hi, 
Instead of relying on weatherunderground, i would like to take data straight off my meteohub locally.

Can someone find this easy to implement, either as a device, or some kind of script?

Please see this forum for more information on the subject.

http://www.domoticz.com/forum/viewtopic.php?f=31&t=8892&p=90120#p90120

I will help by giving access to a HTTP feed to my meteohub if required.

Cheers

**Comment by sbouchex** [comment]
Why not using the HTTP/HTTPS hardware to poll a http feed ?

**Comment by gizmocuz** [comment]
Please use our forum
