### ISSUE TITLE
Segfault on AMD64 with V3.5382

### ISSUE THREAD

**Issue by sjoerdmulder** [domoticz/domoticz#761]
'Build Hash: <b>7071bfc-modified</b><br>Build Date: 2016-07-26 14:06:52'

segfault at 2720 ip 000000000091f0f4 sp 00007fad94b9a920 error 4 in domoticz[400000+920000]

**Comment by gizmocuz** [comment]
did this every worked before ?

**Comment by sjoerdmulder** [comment]
It only crashes after 45 seconds or so. But it seemed that it worked before that. I think it was after configuring ZWave devices

**Comment by gizmocuz** [comment]
Running arch64 myself here without issues, what did you 'configure' ?

**Comment by sjoerdmulder** [comment]
As hardware i  added a ZWave USB device (that itself has 2 light switches). For now i have switched back to the stable release. If there is anything i can do to get more information about this crash let me know, i can easily fire up the 'beta' version again

**Comment by gizmocuz** [comment]
You mean you still have this problem ? You are running version 3.5498 or higher ?
And you are using the installation file from:
http://www.domoticz.com/download.html

**Comment by sjoerdmulder** [comment]
I will retest with the latest version

**Comment by gizmocuz** [comment]
Could you also answer the above second question

**Comment by sjoerdmulder** [comment]
No, i'm not using the installation file from the download page. 

This specific problem happened with a docker-image that used the latest master to build. I have now created a docker image to setup the specific version, so will retry with this build version.

https://github.com/sjoerdmulder/docker-domoticz/blob/beta/Dockerfile

**Comment by gizmocuz** [comment]
maybe you could also try this:

mkdir ~/domoticz
cd ~/domoticz
wget http://releases.domoticz.com/releases/beta/domoticz_linux_aarch64.tgz
tar domoticz_linux_aarch64.tgz
rm domoticz_linux_aarch64.tgz

next start domoticz by hand

./domoticz

now check if the crash happens...

**Comment by gizmocuz** [comment]
You docker image should also NOT use the Config from openzwave, the source/binary has it's own config
For x86/armv6/7/aarch64 i would recommend to use the binary, also no need to compile openzwave

**Comment by sjoerdmulder** [comment]
Ok, so basicly https://www.domoticz.com/wiki/Install.txt#OpenZWave is outdated?

**Comment by gizmocuz** [comment]
Best to follow our wiki guide (raspberry uses the same procedure as a normal linux system)
But i would first try the above manual download/test, so you know if that works

**Comment by gizmocuz** [comment]
https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by sjoerdmulder** [comment]
Ok, followed the steps and it seems to work now... no crash experienced yet (after 10 minutes)

**Comment by gizmocuz** [comment]
Which step did you do, how do you run domoticz, binary, docker ?

**Comment by sjoerdmulder** [comment]
I'm running now with: https://github.com/sjoerdmulder/docker-domoticz/blob/beta/Dockerfile

Had to switch from debian:wheezy to ubuntu:14.04 though. Issues with libssl1.0.0 not being available (only libssl1.0.2) and getting linking issues.
