### ISSUE TITLE
No DNS resolving for RFLink Gateway with LAN interface

### ISSUE THREAD

**Issue by Whizzzer** [domoticz/domoticz#769]
The RFLink Gateway with LAN interface does allow you to fill in an hostname at the "Remote Address" field. But it is not able to resolve this hostname to an IP address. The following error is given:

2016-08-04 13:11:00.824 Hardware Monitor: Fetching data (System sensors)
2016-08-04 13:11:01.151 RFLink: trying to connect to rpi-garage.home.intra:10000
2016-08-04 13:11:01.166 Error: RFLink: Error: std::exception
2016-08-04 13:11:01.170 Error: TCP: Exception: Invalid argument

The "P1 Smart Meter with LAN interface" is capable of name resolving.

**Comment by gizmocuz** [comment]
i am sure (i hope) you have configured a static ip address for this ?
I suspect 90% of the hardware will not resolve dns names

**Comment by Whizzzer** [comment]
Yep, the Raspberry Pi which has the RFLink attached to it and the other Raspberry Pi connected to the Smart Meter are both configured with static IP addresses.

But I prefer to use hostnames instead of IP adresses when possible. Not only for the Domoticz Server, but also in my mail client, etc. Otherwise, why is there DNS? ;-) And may I disagree your statement 90% of the hardware does not do name resolving? I would rather state 95% of the network enabled hardware is capable of DNS resolving (via it's operating system). Even the ESP8266 with ESP Easy is capable of doing this.

The Domoticz server is running on Ubuntu and is absolutely capable of this.

Though I'm not a programmer (just a simple network guy), I think the code of doing nameresolving within the "P1 Smart Meter with LAN interface" starts in P1MeterTCP.cpp line 40.

**Comment by gizmocuz** [comment]
Sorry, i was talking of course about the DNS resolving for the Domoticz hardware support, not for other hardware

I know how to resolve the dns to an ip address, i will see what i can do...

**Comment by gizmocuz** [comment]
Is it possible to test beta # 5432, it should work now

**Comment by Whizzzer** [comment]
Thanks!

2016-08-07 12:48:08.462 RFLink: TCP/IP Worker stopped...
2016-08-07 12:48:09.463 RFLink: trying to connect to rpi-garage.home.intra:10000
2016-08-07 12:48:10.464 RFLink: connected to: rpi-garage.home.intra:10000
2016-08-07 12:48:10.464 RFLink: Controller Initialized!...
2016-08-07 12:48:11.464 RFLink Detected, Version: 1.1 Revision: 42 Build: 0
2016-08-07 12:48:12.464 (RFLink 433Mhz Garage) Temp + Humidity (Weerstation Binnen 1)

Since you named it "Possible fix for the RFLink TCP reconnect issue", could it be that issue #770 is also fixed?

**Comment by gizmocuz** [comment]
These where two different issues... could you test #770?

**Comment by Whizzzer** [comment]
#770 tested.. No positive result unfortunately with build 5436. Will share the details in that issue..

**Comment by gizmocuz** [comment]
I suspect this issue is solved, as i see you can connect via this (connected to: ....) closing issue
