### ISSUE TITLE
Error 404 : /images/evohome/Inv.png missing

### ISSUE THREAD

**Issue by narfight** [domoticz/domoticz#771]
Hello,

When I go to Temp tabs, I have this error :
`2016-08-05 08:12:21.463 Error: Webserver: File '/images/evohome/Inv.png': No such file or directory (2)`

I running on Domoticz V3.5406 with evohome script

Best regards,
Narfight

**Comment by jonferreira** [comment]
same here

can't figure out why it's trying to load Inv.png as that file doesn't exists at all...it should be TemporaryOverrideInv.png at best

Also unsure how we can choose between TemporaryOverrideInv and TemporaryOverride?

**Comment by gizmocuz** [comment]
could you clear the browser cache, and appcache, and see if this solves the problem ?

**Comment by jonferreira** [comment]
nop, I just did that before posting...
to me this is happening on one of the TRVs I've override the setpoint so the correct image should have been TemporaryOverride.png I reckon

**Comment by gizmocuz** [comment]
I am not able to easily / debug check this
Is it possible to send me a copy of your database backup, i should then have the same message, and should be able to pinpoint where this is coming from

**Comment by jonferreira** [comment]
mailed you the DB gizmocuz

**Comment by szczukot** [comment]
https://github.com/domoticz/domoticz/blob/master/www/app/TemperatureController.js#L590
is status undefined ?

**Comment by gizmocuz** [comment]
I think it is OK now

**Comment by jonferreira** [comment]
yeah it's fixed in #5440, great work from Rob!

**Comment by gizmocuz** [comment]
Thanks for the feedback, closing issue
