### ISSUE TITLE
can't get domoticz_updateDevice working

### ISSUE THREAD

**Issue by Kolia56** [domoticz/domoticz#773]
`domoticz_updateDevice(266,0,tensionAC)`
doesn't fire the update of the related idx device. Domoticz log reports as expected:
`2016-08-05 08:18:25.194 CLuaHandler (updateDevice from LUA) : idx=266 nvalue=0 svalue=228.4 invalue=0 signallevel=12 batterylevel=255`
if the device is of type "Usage" (subtype Electric) we may use the ID instead of the Idx and the device will be updated.
However if the device is of type"General" (subtype Voltage), the ID has three leading 000 (ie: 0008255) and we can't even use the ID to get it work.
Seems to me this is a bug of domoticz_updateDevice. Could we have confirmation and hopefully a fix?
Thank you

**Comment by gizmocuz** [comment]
Please use our forum

**Comment by Kolia56** [comment]
I did, this is why I reported here [https://www.domoticz.com/forum/viewtopic.php?f=23&t=12893](url)
Will continue on the forum, sorry for that.
