### ISSUE TITLE
Bug on Level for switch

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#778]
I don't understand level for switch
Is it may be in the values of 0-15 ?
If so, here it is a bug : 
https://github.com/domoticz/domoticz/blob/master/hardware/DomoticzHardware.cpp#L520
?
should be 
double rlevel = (15.0 / 100.0)*Level;

Now, when i sent level = 100, i see on percentage (blind) 106%

Fantom

**Comment by szczukot** [comment]
Does it a bug or not ?
We wrote about this a few days ago:
https://github.com/domoticz/domoticz/pull/785

**Comment by gizmocuz** [comment]
No, it is an implementation issue where possible some hardware classes have a problem with, and as far as those that i can test (kaku,zwave) i see no problems
