### ISSUE TITLE
Blocky not working anymore

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#784]
Hi gizmocuz, the following problem i have today in the last stable version and on the beta (i ve done an update to beta in the hope it works) 
Blocky isn't usable anymore, the only thinks i ve changed was adding a line in the manufactures.xml and added two xml for devices wich aren't in the stable version.

![pic](https://cloud.githubusercontent.com/assets/20950886/17557773/c77be748-5f18-11e6-8918-917106dff4c6.png)

Any idea? browser cache already cleared

**Comment by ghost** [comment]
Safari Problem

**Comment by gizmocuz** [comment]
Please use the forum next time
