### ISSUE TITLE
Wrong SwitchTypeVal when adding more than 1 Movement sensor

### ISSUE THREAD

**Issue by chrispazz** [domoticz/domoticz#788]
Adding an MS13 and a DS90 will generate this bug.

The first (whichever is) is always with correct SwitchTypeVal but the second will always have SwitchTypeVal=0

First:

{
   "ActTime" : 1470942825,
   "ServerTime" : "2016-08-11 21:13:45",
   "Sunrise" : "06:16",
   "Sunset" : "20:31",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "X10",
         "HardwareType" : "Mochad CM15Pro/CM19A bridge with LAN interface",
         "HardwareTypeVal" : 37,
         "HaveDimmer" : false,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "65",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-08-11 21:09:03",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "AL_Movimento Sala",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 0,
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "X10",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Lighting 1",
         "TypeImg" : "motion",
         "Unit" : 5,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "87"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

Second:

{
   "ActTime" : 1470942879,
   "ServerTime" : "2016-08-11 21:14:39",
   "Sunrise" : "06:16",
   "Sunset" : "20:31",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "No Motion",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "X10",
         "HardwareType" : "Mochad CM15Pro/CM19A bridge with LAN interface",
         "HardwareTypeVal" : 37,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "AF4080",
         "LastUpdate" : "2016-08-11 20:16:51",
         "MaxDimLevel" : 0,
         "Name" : "AL_Movimento Camera",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "No Motion",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "X10 security motion",
         "SwitchType" : "Security",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Security",
         "TypeImg" : "security",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "88"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by gizmocuz** [comment]
There are two different sensors, could you show how they look in domoticz?
The first is a normal motion sensor, the second a security sensor ?

**Comment by chrispazz** [comment]
Yes, the first is a normal X10 Marmitek MS13 motion sensor.
the second is a Security X10 Marmitek DS90 motion sensor.
They are like the image attached.
![motion sensors](https://cloud.githubusercontent.com/assets/982153/17615299/9f827382-606d-11e6-9a18-fcc9b1ef0e38.jpg)

**Comment by gizmocuz** [comment]
The MS13 is a PIR (Motion Sensor), but is the DS90 not a door/window sensor?

**Comment by chrispazz** [comment]
Ops sorry, it is an MS90 and not DS90.

**Comment by gizmocuz** [comment]
The problem (that i have) with the MS90 or DS90, it has more values than on/off (motion/no motion), like:

ms90:
motion
no motion
motion+tamper
no motion+tamper

ds90:
alarm
alarm+tamper
alarm+delayed
alarm+delayed+tamper
normal
normal+tamper
normal+delayed
normal+delayed+tamper

Maybe it is an idea for the ms90/ds90 to group the status, and use it as a normal on/off switch (for the icon)
- everything with motion or alarm (and tamper/delayed) is On image
- everything with no motion or normal (and delayed) is Off image

This would not be an easy job...

**Comment by chrispazz** [comment]
But if I delete the MS13 and add only the MS90 for me is ok. It has the correct SwitchTypeVal and offers the correct status (Motion or No Motion).
So the problem is not related to how domoticz manage the MS90 but that the second device added as 2nd motion sensor will always get a SwitchTypeVal = 0 (whichever the second device is, MS90 or MS13).

**Comment by gizmocuz** [comment]
That i can not explain. (looking also at the code), i also experience your behavior myself when adding this kind of sensor..

**Comment by gizmocuz** [comment]
Should already been solved, if not, please open this ticket again
