### ISSUE TITLE
Synology armada compile error I2C.cpp

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#791]
line 501 lux = ch0 \* (0.0304 - 0.062 \* ((ch1/ch0)*_1.4));
If I remove \* compile is ok.
line 501 lux = ch0 \* (0.0304 - 0.062 \* ((ch1/ch0)_1.4));

**Comment by gizmocuz** [comment]
that does not look OK ;)

**Comment by Jumbotroll** [comment]
[ 49%] Building CXX object CMakeFiles/domoticz.dir/hardware/HarmonyHub.cpp.o
[ 49%] Building CXX object CMakeFiles/domoticz.dir/hardware/I2C.cpp.o
/home/dahl/spksrc-master/spk/domoticz/work-armadaxp-5.2/domoticz-r5491/hardware/I2C.cpp: In member function 'void I2C::TSL2561_ReadSensorDetails()':
/home/dahl/spksrc-master/spk/domoticz/work-armadaxp-5.2/domoticz-r5491/hardware/I2C.cpp:501:46: error: invalid type argument of unary '_' (have 'double')
make[5]: *_\* [CMakeFiles/domoticz.dir/hardware/I2C.cpp.o] Error 1
make[5]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-armadaxp-5.2/domoticz-r5491'
make[4]: **\* [CMakeFiles/domoticz.dir/all] Error 2

**Comment by gizmocuz** [comment]
I think i see the problem, there are two \* (multiply) on that line
need to remove 1

**Comment by gizmocuz** [comment]
Pushed a fix, could you check ?

**Comment by Jumbotroll** [comment]
You did it again gizmocuz :-)
The compilation went well. Problem solved!

**Comment by gizmocuz** [comment]
Thanks for reporting!... well yeah... it took me two commits (solved an error, and made a new error in the first ;)

**Comment by Jumbotroll** [comment]
:-)

**Comment by ldrolez** [comment]
Oops sorry! I Since I did not have the time to setup a complete arm build environment, I compile under x86, and because of the ifdefs, that code was not compiled. I see that I have to replace a**b by pow(a,b) !

**Comment by ldrolez** [comment]
Should be: `lux = ch0 * (0.0304 - 0.062 * (pow(ch1 / ch0, 1.4)));`

**Comment by gizmocuz** [comment]
Thanks, it's corrected in the branch now
