### ISSUE TITLE
Add "Zon op Toon"-device for solar power data

### ISSUE THREAD

**Issue by StudyRemy** [domoticz/domoticz#792]
"Zon op Toon" is a solar panel Khw-meter which is connected to Toon.

The net usage or production is available through Toon through the P1-meter, but not the gross production of the solar panels.

My feature request is making the "Zon op Toon" readout-data available in Domoticz to see solar panel production.

**Comment by gizmocuz** [comment]
Can you provide a toon readout ? If not, send me a PM on the forum

**Comment by StudyRemy** [comment]
I'd like to, but I'm not sure how to do that.
SSH to my domoticz-box and using curl or something?

Shall I PM you?

**Comment by gizmocuz** [comment]
Yes plz

**Comment by gizmocuz** [comment]
Implemented

**Comment by stephanvdplas** [comment]
> Implemented

Can you please explain how? There is no device "solar revenue" or whatsoever.
