### ISSUE TITLE
Dummy dimmer problem with last level value

### ISSUE THREAD

**Issue by daniarv** [domoticz/domoticz#795]
Hi,

I believe there is some problem when using a dummy dimmer switch.
If I turn off the dim switch when the dimlevel is set it won't go back to that level when the lamp is turned on.

Example:
If I change level to 40%, this value is stored in the database in svalue and LastLevel.
When I turn off the switch by pressing the lamp icon, the values are svalue=0 LastLevel=40.
But when I turn on the switch by pressing the lamp icon the svalue is still 0 but the dim slider still shows 40.

Is this a bug?
After I turn on the lamp by pressing the lamp icon the idea is to run a command based on the svalue which in this case I believe should be 40 (fromlastlevel).

Dimlevel Set:
![dim_level_set](https://cloud.githubusercontent.com/assets/18097443/17698687/c733292e-63bc-11e6-8fe9-b60794348e91.PNG)
Dimmer turned off:
![dim_off](https://cloud.githubusercontent.com/assets/18097443/17698686/c732a3fa-63bc-11e6-8556-98dea8de1a1c.PNG)
Dimmer turned on:
![dim_on](https://cloud.githubusercontent.com/assets/18097443/17698688/c736019e-63bc-11e6-9f17-c021c976aa1b.PNG)

See attached images.

**Comment by daniarv** [comment]
Here are also the json output for the same scenario:

[dim_level_set_json.txt](https://github.com/domoticz/domoticz/files/420237/dim_level_set_json.txt)
[dim_off_json.txt](https://github.com/domoticz/domoticz/files/420235/dim_off_json.txt)
[dim_on_json.txt](https://github.com/domoticz/domoticz/files/420236/dim_on_json.txt)

**Comment by gizmocuz** [comment]
Thanks for the report, but what type of hardware are you controlling (the switch)
433Mhz or ZWave, or other

**Comment by daniarv** [comment]
With this dimmer I execute some batch scripts that controls my 433mhz device/devices.

**Comment by gizmocuz** [comment]
Live will be easier if you get an RFXtrx433-e or RFLink
