### ISSUE TITLE
Support for LM75

### ISSUE THREAD

**Issue by sylvainar** [domoticz/domoticz#796]
Hello guys !

I've seen in the available hardware that you got support for different temperature sensors but you don't have LM75 (I2C). Is there any workaround to make it work ? I'm running it on a Raspberry Pi.

Thanks !

**Comment by gizmocuz** [comment]
No, not at the moment, this has to be build
Better use MySensors.org for the moment/feature

**Comment by gizmocuz** [comment]
(Else we would expand this class again and again for each hardware type, and mysensors has already support for most sensors that exists)

**Comment by sylvainar** [comment]
Well mySensors seems to be for Arduino only. 

Actually I ended up buying a BMP085, which is supported by Domoticz. Thanks for your answers anyway !

**Comment by gizmocuz** [comment]
Correct (or ESP), but this you can connect to Domoticz via the serial or Ethernet bridge, a really nice platform bdw, specially when you want to have multiple sensors
