### ISSUE TITLE
Satel Encryption (GuardX Key)

### ISSUE THREAD

**Issue by rwytrwal** [domoticz/domoticz#799]
In Satel Integra via LAN interface has password for user that is user code existing on Integra system but we need to disable encripted transmission. It's security system and it needs  to be encrypted. We have GuardX Key for that but it's not implemented. OpenHAB has that option and I found some info on polish forum   [http://www.elektroda.pl/rtvforum/topic2091518.html](url)  . Mabe someone can implement this ?

**Comment by gizmocuz** [comment]
Sorry, guess nobody wants this/implement this, closing issue

**Comment by szczukot** [comment]
Maybe I .... ;)
But i don't know when ..... :(

Fantom
