### ISSUE TITLE
Installation on Mac OS X - brew formulae for domoticz

### ISSUE THREAD

**Issue by l00mi** [domoticz/domoticz#800]
The install could probably made much easier for OS X users by creating an own formuale for domoticz.

**Comment by gizmocuz** [comment]
We already have a binary install available that is always up to date
http://www.domoticz.com/download.html

**Comment by l00mi** [comment]
Perfect, then only the formulae need to be written?

**Comment by gizmocuz** [comment]
You mean the wiki ?

**Comment by l00mi** [comment]
https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md

**Comment by JohnnyMa** [comment]
update the latest url: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md
