### ISSUE TITLE
Z-Wave network *down* after updating to last beta

### ISSUE THREAD

**Issue by jonferreira** [domoticz/domoticz#802]
Hi,

After updating to last beta my Qubinos ZMNHDD1 Flush Dimmer Plus are being polled every second (looking at OZW Panel last Hear is updated every second) dragging the Z-Wave network down to a stall, completely impossible to do anything with it.

I take something changed on the OZW side?

**Comment by gizmocuz** [comment]
Please use our forum, also in domoticz disable polling is this is turned on.
If its still sends data every second, repower the flush dimmer, or check the configuration settings

**Comment by jonferreira** [comment]
Morning gizmocuz,

Just to let you know I've finally managed to track it down...for some reason (unsure if it's related with the upgrade but it did happened immediately after it) both Qubino Parameter settings seem to have gone crazy and I take it was reporting power consumption every 1 second.
After the good part of an hour trying to save Parameters again the spamming finally stopped and everything is back to normal.

thanks

**Comment by gizmocuz** [comment]
Great it's solved... i dont think this had something todo with a configuration file update...

**Comment by jonferreira** [comment]
yeah it could be a coincidence, not sure TBH
