### ISSUE TITLE
Duplicate logging via ESPeasy switches. Log overload unreadable logs

### ISSUE THREAD

**Issue by mvroosmalen** [domoticz/domoticz#806]
After upgrading with ESP R120 my switches send a status each minute and lead to an overflow of the logs in Domoticz. Duplicate writing of entries is the cause. Solution would be to omit writing duplicate entries and only when a difference in status is reported the log entry is written.

**Comment by gizmocuz** [comment]
Yeah.... and you should do that in our ESP ?
If it is a door/motion sensor, and you had set the type also as 'door sensor' in domoticz, you wont see these duplicates

**Comment by mvroosmalen** [comment]
Hi Gizmocuz, changing to door sensor keeps recording each event:
2016-08-21 21:11:32 Off
2016-08-21 21:10:32 Off

Where can I find the logging in the code? Change of ESP could be an option but now it reports actual status, which is nice in case something happened and not reported back.. Happens in some cases.

Thanks for the suggestion though

**Comment by gizmocuz** [comment]
Sorry.. Change it to a contact type

**Comment by mvroosmalen** [comment]
Did it... Though indeed it prevent logging, it also gives this error:
2016-08-22 22:20:45.276 Error: MQTT: Error sending switch command!
sorry for the inconvenience
