### ISSUE TITLE
Merten Move Push Button Support Z Wave

### ISSUE THREAD

**Issue by psavva** [domoticz/domoticz#807]
I have the Merten Move push button switch in my Z wave network.

Domoticz seems that it does not recognise it correctly, and seems the push button doesn't trigger an event in domoticz. I created a simple lua script to detect the button being pressed by logging all devices and their status.  Nothing happens when activating the push button in the lua log...

Please help debug, and resolve.

**Comment by gizmocuz** [comment]
Please use our forum
