### ISSUE TITLE
No support for different usage/return costs for electricity

### ISSUE THREAD

**Issue by koenkooi** [domoticz/domoticz#808]
Domoticz does support different costs for T1/T2, but not for return. In my case, Essent/Stedin, P1 smart meter in the Netherlands, T1 = €0,18, T2=€0,21 and R1=R2=€0,08. This makes the 'Report' page a bit too optimistic :)

```
Version: 3.5516
Build Hash: 2c6c836-modified
Compile Date: 2016-08-17 13:14:24
```

**Comment by Jackvg** [comment]
I have the same issue. I really would like this "problem" to be solved. I know many people will need this function.

**Comment by gizmocuz** [comment]
Just impemented, beta is building (could take up to 1 hour), Is there someone who wants to have a quick test? I suspect it is working correctly

A good site for dutch people to find there costs could be this one:
https://www.energieleveranciers.nl/zonnepanelen/terugleververgoeding-zonnepanelen

**Comment by koenkooi** [comment]
I built 7c3d6f42d98f7b86c56244359b174d872a40070c (3.7223) and it seems to be working correctly:

<img width="1209" alt="schermafbeelding 2017-04-02 om 08 50 21" src="https://cloud.githubusercontent.com/assets/259525/24585058/7a9cab84-1781-11e7-8e58-b3e68d41b24a.png">

**Comment by gizmocuz** [comment]
Great, thanks for the feedback, we can finally close this issue ;)
