### ISSUE TITLE
mac address based security

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#809]
A new setting to only allow connections to the web server from some mac addresses (a list of addresses)

If the address is not allowed, a 403 http error can be returned

I can work on it

**Comment by rkluwen** [comment]
I don't want to discourage people that want to develop on Domoticz.
But this feature will only work on the local LAN. And in that case, you can set up ipv6 based access control which is a lot easier to configure and is already implemented.
In fact your local ipv6 address is already based on the mac address.

**Comment by sbouchex** [comment]
IPv6 is not enabled everywhere and it may not be possible.

I agree that this feature is LAN only but in some cases (home automation for instance), mac address filtering may be enough.

**Comment by ldrolez** [comment]
IMHO, It should be done by the OS, using iptables for example.

**Comment by gizmocuz** [comment]
aggree, use iptables
