### ISSUE TITLE
domoticz remote server - termostat

### ISSUE THREAD

**Issue by tomasss1024** [domoticz/domoticz#811]
Hello, 
thanks for domoticz, very good application for automation on raspberry :)
I have problem to set termostat as shared device on master server. 
Switches work well, but termostat doesn't set new value.
I tried to find some communication specification on port 6144 but without success :/.
thanks
Tomas

Domoticz 3.5114 on Windows 7

**Comment by gizmocuz** [comment]
we have a json interface for this. Plz see the wiki, and use our forum
