### ISSUE TITLE
Motherboard sensors: RPi temp lost when adding new local partitions

### ISSUE THREAD

**Issue by ldrolez** [domoticz/domoticz#812]
On the latest Beta, after adding 2 local partitions, the RPi internal temperature stopped being updated.
Removing/adding the "Motherboard sensors" hardware didn't solve the problem.
Of course, /sys/devices/virtual/thermal/thermal_zone0/temp is still readable.

**Comment by ldrolez** [comment]
Found the problem: ld.so.cache corrupted, so vcgencmd did not work anymore...

**Comment by gizmocuz** [comment]
Plz use our forum next time
