### ISSUE TITLE
Add protocol option to camera

### ISSUE THREAD

**Issue by benjR** [domoticz/domoticz#813]
Hi,

Would it be possible to add the protocol choice when adding a camera ? It's forced to http by default.
I have one that is using ftp, https, I know that some others are using rmtp and so on...

Thanks

**Comment by sbouchex** [comment]
@gizmocuz ok to do it ? I can work on it

I will add a popup menu with HTTP, HTTPS for now, will see later for other type of camera

**Comment by gizmocuz** [comment]
Dont know if that will work... ftp ? also rtsp/rtmp, i do not think mailing a screenshot will work ? (taking a screenshot)
Most camera's (90+ percent) have a url for a image snapshot, this is what we use at the moment

**Comment by sbouchex** [comment]
I agree with you but the @benjR's point was just to have the ability to use HTTPS but CCameraHandler::GetCameraURL current implementation is forcing HTTP (it's hardcoded) and I was proposing to add a field to specify the protocol.

**Comment by gizmocuz** [comment]
If it is an internal camera, then HTTP is not supported?

**Comment by sbouchex** [comment]
Why not offering both ?

**Comment by gizmocuz** [comment]
Can't your camera offer HTTP ?

**Comment by sbouchex** [comment]
I have one where it's either HTTP or HTTPS... and noweverdays, HTTPS is mostly recommanded

**Comment by gizmocuz** [comment]
not for internal use, so you can handle HTTP, also is less cpu overhead

**Comment by sbouchex** [comment]
Domoticz is not only for internal use (you don't know what users are doing with it) and sometimes SSL is just mandatory (knowing that it's more CPU intensive). My PR was to be more open, if you don't like it (throw it away)

**Comment by gizmocuz** [comment]
I hope you can agree that the camera interface in domoticz, will still connect only internally to your camera, even if you connect to domoticz via https
So there is really no need for HTTPS camera support... there is however support needed for AVC/H264 camera's, that mostly work via rtsp, but thats another PR, and we should find a method of creating a snapshot if these as well

**Comment by sbouchex** [comment]
Do what you want

**Comment by gizmocuz** [comment]
Sure, it's a pull 'request', but as you can access your camera internally by http as well, there is no issue, or reason, to rebuild things, giving another user option.
It's getting more and more complicated each day by all the wishes.

**Comment by meaninglessvanity** [comment]
A workaround for photo hosting that domoticz doesn't support would be to mirror the camera's feed in http on the local server.
