### ISSUE TITLE
Nest On/Off switch not working

### ISSUE THREAD

**Issue by dpui7736** [domoticz/domoticz#825]
On/Off Nest device switch doesn't work. Away mode switch works perfect.

Error: Error sending switch command, check device/hardware !

Log: 2016-08-26 05:51:07.988 Error: Nest: Error getting current state! 

![image](https://cloud.githubusercontent.com/assets/21259318/18001264/33222816-6b82-11e6-8d7f-b34778ce97ee.png)

![image](https://cloud.githubusercontent.com/assets/21259318/18001277/471d4134-6b82-11e6-93c1-c3aa2be107a9.png)

**Comment by chrisella** [comment]
AFAIK the Nest api doesn't allow you to directly turn it on/off.
This was about a year or 2 ago I was looking at the API though, so take that with a pinch of salt.
