### ISSUE TITLE
Blinds timer

### ISSUE THREAD

**Issue by confucius78** [domoticz/domoticz#837]
Timer 'command' for blinds only shows on and off, this does not match the actions on the widget (open, close, stop).

**Comment by gizmocuz** [comment]
On/Off are Open/Close, there is no need to add a stop in a timer
I agree that it should read open/close

**Comment by morilm** [comment]
Hi.

I think it will be very useful to have the stop and timer on the blinds.   This will allow to open/close them for 5-10 secs instead off full open/close status.

Even the best solution, but complex would be to set the % to time duration (on while 10 sec and them stop).

I know newer devices (Fibaro) can set the %, but the old ones doesn't, so a On - Stop command is needed to stop in the middile (or Off - Stop)

Thansk
Miguel

**Comment by inzuno** [comment]
Hello,

I totally agree with morilm and confucius78. Personally I need the stop function to adjust darkness in my room.
@gizmocuz why do you say there is no need of stop in a timer? Is there another way to open partially the blinds?

Thx

**Comment by gizmocuz** [comment]
Sorry, this is a very (extremely) old thread... 
If you install Fibaro blind controllers than of course there is no need
If you do not have them... then maybe you can make an option where you can 'long click' on a blind open/close and specify a (predefined) duration ? (like 5, 10 , 15, 20, 25,.. seconds)
If that is what you mean...

**Comment by inzuno** [comment]
Hello,
Thanks for the reply! 
I don't have Fibaro blind, I have Dooya RF shutters controlled by RFlink. I can't tell what's the difference...
I can see the stop function when I select venetian blind EU but only in the Switches tab, they do not appear in the timer settings or in the floorplan tab. The "STOP" option also appears when you create scene from this shutters.
I think I will manage it this way...
Thanks !
