### ISSUE TITLE
Aeotec Smart 6 switch state is not correctly displayed: seems as if it switches back again

### ISSUE THREAD

**Issue by basrieter** [domoticz/domoticz#844]
I think this commit:

https://github.com/domoticz/domoticz/commit/dcc09b1b0779ca1f1a88dce96947dab7093a89a4

broke some stuff for the Aeotec Smart 6 switch? If I switch now, the devices switches correctly, Domoticz also registers a switch, but then immediately registers a switch back to the initial state, although the devices does not switch?

**Comment by basrieter** [comment]
The Z-Wave control panel (ozwcp/cp.html) does report the correct states

**Comment by RicardP** [comment]
I Notice exactly  the same behavior with my Philio PAN04-01 swithes since some beta versions back.

**Comment by gizmocuz** [comment]
@basrieter, first, you say it totally broke your system, next you say it is switching correctly, only the status update does not work correctly. Pfffff
Did you add the correct switch, in the devices tab, the switch ID should end with 01, subtype switch, not the RGBW one
Also make sure that your controller (node 1) is in group 1 of the node.
The removed part that you commented on, it handled correctly by the change in the 'if' statement following it, because for ON/OFF, (value 0 or 255), we are using the BINARY class.
Even if it was set as a dimmer, we now first check if there is a binary class, and use this when switching ON/OFF
And i also tested it with my smart switch

@RichardP, some beta versions back... how many days ?

**Comment by RicardP** [comment]
@gizmocuz, Edit: maybe my issue is really not "exactly the same" as I wrote first, I assumed it was the same casue though. 

Sorry I don't feel sure about what point it appeared, could be a week ago. However I ignored it because actual switching seemed stable working and I did not have time to dig into it. Example, If I click-switch on the Utebelysning Kväll, then Utebelysning Natt indicates On as well, but physical switch "Natt" does not swith on...  Now running Beta 3.5565 on Windows.

![klipp](https://cloud.githubusercontent.com/assets/21274628/18229801/384bafe6-7286-11e6-8ce8-b3426cc18d29.JPG)

**Comment by gizmocuz** [comment]
@RicardP, thats an old beta, so the change from yesterday is not in there, and is therefor not related to this issue

**Comment by basrieter** [comment]
I said the switch is useless, as I can't switch it anymore. All my other Zwave devices work fine. So I am still very happy with Domoticz.

I update very regularly, actually whenever there is a beta update, and noticed this started yesterday evening after updating. So that triggered me. 

Both my switches have this issue. They are both in group 1  and if I look at the Open Z-Wave control panel it shows the correct information.  It just seems that after switching Domoticz appears to think they were immediately switched back.

Your about the Dimmer triggered me: after the update one of the two switches would show 50% if I tried to switch it on? I fixed that by going into the Open Zwave control panel and change the value to 99. And I now see that the control panel is showing me a Dim option for these switches. Perhaps that Domoticz sees the as a Switched off dimmer at 99%? And this is causing Domoticz to show it as On again?

**Comment by basrieter** [comment]
![image](https://cloud.githubusercontent.com/assets/1310443/18229943/4437c456-728c-11e6-879c-1f9f573c2811.png) here is a screenshot of the control panel. The switches appear as dimmer now.

**Comment by RicardP** [comment]
@gizmocuz, ok its some old but I did not notice changes since my beta version that seemed to relay to my issue that's why I brought it up. So I will now update to latest and come back with the result.

**Comment by RicardP** [comment]
@gizmocuz , Just updated to .5604, still issue with switches influences each other (at least all four PAN 04-01 behaves the same), however, I see the same switch states changing inside OZW CPL. But I don't know from were the mixup happens, inside Domoticz pushing it to OZW or the opposite direction.

**Comment by basrieter** [comment]
I excluded one of the switches and included it again. But the same result.

**Comment by gizmocuz** [comment]
@RicardP, be aware that one of the switches is an ALL On/Off

**Comment by gizmocuz** [comment]
@basrieter , both processes are independent... so if they both behave the same, its probably an aeotec issue
I do not have this issue...
I also do not use/switch/touch the dimmer
You could be right at the 99% = On, but still initially the state is off, with 99% 'when' is should be turned on.
But do not use the dimmer
My dimmer value is: 50%, try setting it on 50%

You can also build domoticz yourself, and add back the 'if' statement

**Comment by basrieter** [comment]
![controlpanel](https://cloud.githubusercontent.com/assets/1310443/18230782/3f4581b2-72a6-11e6-89cf-9231f66c7015.PNG)
![domoticz](https://cloud.githubusercontent.com/assets/1310443/18230785/3f4af21e-72a6-11e6-92d2-175b68337367.PNG)
![switch](https://cloud.githubusercontent.com/assets/1310443/18230784/3f4a8540-72a6-11e6-946f-0d09c6df0151.PNG)

Here are 3 screenshots after Switching the switch off. As you can see, the control panel shows it as off, the domoticz log logs 2x lines 'off' and the Domoticz GUI shows it as 'on'. So there really is something weird. I will try to compile things. But was never succesfull in my rPi1.

**Comment by basrieter** [comment]
Would it be possible to mail me a the BETA from 1-9 or 2-9? Compiling isn't really advancing here :(

**Comment by basrieter** [comment]
Ok, tried something else now: created a new Domoticz stable SD Card. With that all works as expected, as in, I can actually switch from the Domoticz interface and the correct states are shown. 

Then updated to the latest beta and wound up with the same issue. From Domoticz I can't change state, from the Open Z-Wave control panel (opened from domticz hardware setup) I can. And with the beta version, the switches are again show as dimmer (50%) instead of a switch with on-off.

**Comment by gizmocuz** [comment]
Please try beta #5605
I added the smart switch patch again (which should NOT be necessary as it is handled anyway, or my eyes don't show me correctly)
Could you test with this version ?
Are you 100% that with the version from last week, it was working correctly ?

**Comment by basrieter** [comment]
I will give it a try in about 15 minutes. And yes, I am 100% sure it was working last week, as I usually have to switch of my IP cam after it switches on by schedule at 1:00 AM because I tend to go to bed too late :D

**Comment by basrieter** [comment]
I just tried and this solved my problem. So apparently there is something more to this change?

**Comment by gizmocuz** [comment]
... Okey, i keep this in ;)

**Comment by basrieter** [comment]
Thanks for the fast service. I really want to stick with the beta updates so I can help keeping Domoticz working for all people. And I am happy to see that my feedback is put to good use. 

I really like Domoticz, so if there was any point during the past day that you thought I was the next guy bitching on open source software (I have an open source project too, and run into these people often), than I apologize, as it was never my intention.

**Comment by gizmocuz** [comment]
Thank you for your patience ;) i will review the difference tomorrow, but having special lines for sensors is not a good thing to have ;)

**Comment by basrieter** [comment]
I agree. Let me know if I need to do some more testing. This time I will make a backup first.
