### ISSUE TITLE
Switchs : the opposite way

### ISSUE THREAD

**Issue by sylvainar** [domoticz/domoticz#846]
Hey guys !

I'm running Domoticz on a Raspberry pi, and I've seen that my relays are working on the opposite way that it is displayed. Where the relay is on, the switch on my panel and on the mobile app are off, and when off, they're on. 
Is there a way to say to Domoticz that this particular GPIO is working the opposite way ?

Thanks !

**Comment by gizmocuz** [comment]
Switch the relays, so NC will become NO or visa versa

**Comment by sylvainar** [comment]
Yes I could do that, but it means that if my raspberry pi shuts down for no reason, all the heaters of my house will power on... You're sure there's no way to modify it in the software ?

**Comment by gizmocuz** [comment]
If you turn a switch ON... it should close the contact, should turn on a light for instance

**Comment by sylvainar** [comment]
You're right, if you turn the switch on, it should close the contact, meaning that if you turn the switch on you got a 3.3V on the GPIO pin.

However, the relays I've bought are not working this way : the contact closes when I set their input to 0V, and opens when I put it in 5V, that means that they are working in the "reverse" mode.

I could switch the contacts (that's what I'm actually doing right now), but I'd like to invert this from the software, because if the raspberry pi turns off or reboot or whatever, all my devices will suddenly turn on, which is really not good.

I can see that, for Blinds, you got Blinds and Blinds inverted. Why not putting it for every device ? Is it not possible to put a checkbox for switchs if we want to invert it ? It could have other uses, for example for a door lock, this way you can be able to select between safe and secure if the power of your house goes down.

Hope you will take this in consideration.

**Comment by jrich523** [comment]
why not just a checkbox to invert. I have this issue with locks and agree
it would be all around useful

**Comment by gizmocuz** [comment]
Its not 'just' a checkbox, everywhere the logic should be inverted.
Best to buy the good relay
As for blinds, if you connect them opposite, you have the same issue
But again, its not just a checkbox

**Comment by jrich523** [comment]
I meant it should be implemented as a checkbox, rather than one off
'inverted' versions of hardware (much like the inverted blinds)

**Comment by sylvainar** [comment]
Well, if it's that hard to set up, is it possible just to create the inverted On / Off ?

**Comment by gizmocuz** [comment]
Same problem, better to get yourself correct relays
