### ISSUE TITLE
device value logging cannot be disabled

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#852]
I do have a 1wire device and at each poll, i do see:
 2016-09-07 22:30:36.847 (owfs) MyTemp (Sleeping Room)

This log comes from MainWorker::ProcessRXMessage because pHardware->m_bOutputLog is true

But I cannot set m_bOutputLog to false because the value is always false (as it's the default value)

Why not having an option to enable/disable value logging PER hardware ?

Adding a new column in the database would be required

**Comment by gizmocuz** [comment]
Whats wrong with logging ? You only watch the log when you are kind of debugging, and from the log display, you can even set a filter

**Comment by sbouchex** [comment]
I don't see the point of logging x entry just to say that an data as been acquired especially when the acquisition was good.

Other point : This logging is inconsistent : It's enabled except for : DenkoviSmartdenLan, ETH8020, HardwareMonitor & Sterbox, why ?

**Comment by gizmocuz** [comment]
they are logged, when a new switch value is received, that is handled not in that class

**Comment by sbouchex** [comment]
For a new switch, that's make sense but for regular polling, I doubt

Anyway, that's minor

**Comment by gizmocuz** [comment]
No it also logs if a switch is received of course

**Comment by gizmocuz** [comment]
In case of denkovi, only is send when a state of the relais has changed
