### ISSUE TITLE
deadlock when closing app

### ISSUE THREAD

**Issue by sawik-PL** [domoticz/domoticz#856]
deadlock occurs when clossing app:
- MainWorker::StopDomoticzHardware() locks m_devicemutex and waits for devices to stop
- eg. MQTT got message in meantime and waits for lock on m_devicemutex in MQTT::on_message -> MainWorker::UpdateDevice -> MainWorker::GetHardware

added another mutex which is locked on app closing and checked before trying to lock m_devicemutex

patch provided

[0001-FIX-possible-deadlock-when-closing-app.patch.txt](https://github.com/domoticz/domoticz/files/461822/0001-FIX-possible-deadlock-when-closing-app.patch.txt)

**Comment by gizmocuz** [comment]
Thanks!! It's it possible to make a git pull request?

**Comment by sawik-PL** [comment]
Just making…
