### ISSUE TITLE
New hardware : File reader/writer

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#861]
The idea is to give the ability to read/write to a file with the ability to parse the output of the file before feeding sensors or switches.

Why ? Some relays are USB pluggable with a FDTI interface, so the data are accessible from a /dev devices

A lua script can be used to:
- Describe the sensors/switches
- Parse a command and format it to the device (sometimes, relay do have a simple binary buffer)
- Read the device buffer and parse it before feeding the sensors/switches.

Can be also a simple /proc file to read some system data

**Comment by gizmocuz** [comment]
i think you can also do this via python/scripts correct?

**Comment by sbouchex** [comment]
yep (even if I hate scripting :-)
