### ISSUE TITLE
Calcul costs using log

### ISSUE THREAD

**Issue by sylvainar** [domoticz/domoticz#862]
Hey !

Thanks to logs, we know when a device is on or off. Is it possible to define the mean power of the device (like 80W for a lamp, 2000W for a heater...) and then monitoring the power consumption from the utility panel, by multiplying the time of usage by the power ?

Not really useful but could be nice. Thanks !

**Comment by gizmocuz** [comment]
Seems there is not enough amino to support this feature. You can install a zwave plug that measures this
