### ISSUE TITLE
Switch type Blind, mode Inverted does not also invert the percentage scale.

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#865]
If selecting blinds inverted to get Open / Close icons showing correct does not effect percentage scale...

0 % should be fully winded up blinds and 100% should be maximum blinds effect, Please I cant stand it! :-)

**Comment by gizmocuz** [comment]
Please use our forum

**Comment by RicardP** [comment]
Sure had, been there, tried that... without any result that's why it ended up here. Seems my issue isn't sexy enough :-)

**Comment by gizmocuz** [comment]
Maybe a link to the forum post ? I might take a look ;)

**Comment by RicardP** [comment]
:) 

https://www.domoticz.com/forum/viewtopic.php?f=6&t=9883&p=69283&hilit=PERCENTAGE+SCALE#p69283
