### ISSUE TITLE
Weather Underground stopped working on RPI

### ISSUE THREAD

**Issue by SeaTea1** [domoticz/domoticz#866]
I noticed that my weather stations which I get from Weather Underground stopped updating from around september 4, 2016. As I have the Raspberry-PI image it is updated via a pop-up question when you login, it is updated regularly, so I don't know exactly since what update this happened. The only thing I noticed is a straight line in the graphs of the virtual weather stations from Weather Underground since sept 4.

After some debugging the log, I found that the Weather Underground client did not work properly and indicated "Wunderground: Error getting http data!". When checking my api status at wunderground, I found that between september 4 and september 10, there were no API calls from me, while on a normal day there were more than 200. So API calls stopped probably after I upgraded. Tried to upgrade Domoticz, but there were no upgrades available according Domotics, while the download page shows that there were a few newer versions available in the meantime.

I tried to further debug, and tested my connection from my raspberry to weather underground (via SSH login on my RPI), but this seems normally. But when I tried with curl, I noticed a long waiting time before something happened. After about 30 to 40 seconds, curl showed output from external web pages. After some google searches I found [this page](https://www.raspberrypi.org/forums/viewtopic.php?t=128269&p=860481) which describes a similar problem with curl. It describes that when IPv6 is enabled, the DNS resolver can take a very long time because it is first trying to resolve a IPv6 address, even if IPv6 is not used. It also depends how a URL is called, as I understand. 

IPv6 was enabled in my RPI, but it is not used and my RPI has no working IPv6 address. So I disabled IPv6 as described in the mentioned page (see below). After that the curl-testing via SSH on my RPI had no delay anymore and also the Weather Underground data worked again. Also my RPI found the updates it did not notice before, so maybe the update process has the same 'problem' as the weather underground data fetching problem.

After checking the Domoticz Github page, I found that hardware/Wunderground.cpp was changed at august 29 together with some other files. Maybe the timeout issue and 'Error getting http data!" are related to this change, as I did not have these problems before. (I am not a programmer, so don't know what was changed and if this could be the cause).

So if you have the same issues, try to disable IPv6 on your RPI if you do not use it. It is not enough to disable IPv6 in '/etc/sysctl.conf', you need to blacklist the ipv6 driver in '/etc/modprobe.d/fbdev-blacklist.conf'. In fact this is the only thing I changed. I did not change anything in other files and did not remove the modprobe ipv6 module as advised on the mentioned page.

(Also [posted](https://www.domoticz.com/forum/viewtopic.php?f=6&t=13295) this on the Domoticz forum).  Btw I updated RPI Jessy to latest (apt-get update/upgrade) before above tests.

**Comment by gizmocuz** [comment]
Don;t cross post
