### ISSUE TITLE
Can't read alarm values for Zwave Door Lock

### ISSUE THREAD

**Issue by jraynes** [domoticz/domoticz#867]
I have a Kwikset 910 ZWave door lock. Its paired and I'm able to control it via the Domoticz Web UI. But I can't seem to detect if the lock is manually operated from anywhere in Domoticz. I did some research on the device and it looks like it reports manual control of the lock via the ZWave Alarm class. And I can see this when tailing OZW_Log.txt and locking the door manually:

2016-09-11 17:37:32.428 Info, Node005, Received Alarm report: type=21, level=1

(According to the documentation [here](http://s7d5.scene7.com/is/content/BDHHI/ApplicationNote-UsingASCII-Z-Wave-Locks) on page 8, alarm type 21 means that the lock was secured manually. )

When I go to the Devices tab in Domoticz I see two alarm devices with IDs 00000533 and 00000532. However the data for each of these devices is always set to "on", rather than the actual value that the OpenZWave stack is reporting. I was hoping to be able to read the actual value from the Zwave stack so I can tie such events to other actions/scenes.

**Comment by gizmocuz** [comment]
I wonder if there are more messages here.... 
you do not have an additional switch sensor for this node ? (with unit type 21 ?)

**Comment by gizmocuz** [comment]
No feedback, please use our forum
