### ISSUE TITLE
Costs column in monthly overview empty for counter T2 

### ISSUE THREAD

**Issue by gordonb3** [domoticz/domoticz#868]
I've located the corresponding code in domoticz.js.gz and it appears that the column is loaded with data, yet it shows empty on my screen. Anyone got a clue?

![monthview](https://cloud.githubusercontent.com/assets/10542844/18435663/e5cd1b4a-78f4-11e6-89cf-4f7ca412f513.jpg)

**Comment by gizmocuz** [comment]
Thanks for spotting, will be solved in the next beta.
Was caused by hiding the wrong columns
