### ISSUE TITLE
Sen.se integration

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#870]
Sen.se comes with a REST API (https://sen.se/developers/documentation/)

Lets's see what we can do with these sensors...

**Comment by gizmocuz** [comment]
_lol_ ... okey ;)
Personally i think you can get much better sensors (also white...) that operate at 433Mhz, for less money

**Comment by sbouchex** [comment]
The initial target would be the "thermopeanut" (https://sen.se/store/thermopeanut/) which is a temperature Bluetooth sensor.
