### ISSUE TITLE
cannot change: "P1 Smart meter" baud-rate

### ISSUE THREAD

**Issue by SSoaker** [domoticz/domoticz#871]
v3.5640 (running on raspberry pi B)
When i click 'setup' 'hardware' 'P1 Smart meter [setup]'
I can choose between 9600 and 11500 baud.
After selecting i click 'Set Mode' but nothing happens.

The log file shows this error:
Error: Webserver: File '/setp1usbtype.webem': No such file or directory (2)

**Comment by gizmocuz** [comment]
there should be no p1 smart meter setup button anymore.
All is done in the main settings like this:

![image](https://cloud.githubusercontent.com/assets/2265299/18491012/c6589d0a-7a04-11e6-81ba-c2c23037694b.png)

Please clear your browser cache and try again

**Comment by SSoaker** [comment]
I'm using chrome, cleared browser cache after update. Cleared again and still the same.
Then tried firefox and now i get the same result as your screenshot.
So the problem is not related to Domoticz.

**Comment by gizmocuz** [comment]
You might need to clear your appcache as well... see the manual
