### ISSUE TITLE
BUG: Dimmer Shows No Real Data on Floorplan w/ Custom Icon

### ISSUE THREAD

**Issue by mysteryan** [domoticz/domoticz#872]
When using a custom icon for dimmer devices, only "Set Level" without any other significant data is displayed on the floorplan.  When changing the dimmer back to the default "Light/Switch" image, the problem disappears and it correctly reflects the dimmer's percentage value on the floorplan. 

I suspect that the same code to parse the percentage levels for the dimmer doesn't exist when the function "CustomImage !== 0" returns true and passes down the call to the CustomImage controller. (I'm not a programmer, so not sure.  Just trying to understand the code so I can more states other than the two that are available).

Using Domoticz v3.5637 on rPi 2

**Comment by gizmocuz** [comment]
Are you able to debug/test and provide a patch if needed?

**Comment by gizmocuz** [comment]
No feedback, closing topic, use the forum next time!
