### ISSUE TITLE
Unsupported MySensors 2.0 Device Types / Variables

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#873]
Hello,

Getting this in the log : 

2016-09-15 21:14:55.022 Error: MySensors: Unknown/Invalid sensor type (46)
2016-09-15 21:14:55.279 Error: MySensors: Unhandled sensor (sub-type=22), please report with log!
2016-09-15 21:15:02.908 Error: MySensors: Unhandled sensor (sub-type=21), please report with log!

Looks like the HVAC stuff from MySensors 2.0 is not yet fully implemented.
Code present in this repo confirms it's not supported yet.

Could you please implement it when you got some time?

Keep up the good work !

Kindest regards,

JFH

**Comment by gizmocuz** [comment]
Since I control the hvac with the Ir class, could you implement this?

**Comment by ghost** [comment]
Mmmmh ... IR is a solution yeah, but I was planning on doing some more elaborate stuff ... using the HVAC part of MySensors to control my IR transmitter inside arduino script to send custom commands to my HVAC ...

U plan on implementing these HVAC MySensors variables and stuff or would you really advise going into another direction ? I could as well use LUA to do the job but it's not as nice :)

**Comment by gizmocuz** [comment]
Maybe you could add support for them ?
I can not test nor debug, so i leave this to someone else to implement
