### ISSUE TITLE
Data points in the future for temperature sensors (2017 and 2018)

### ISSUE THREAD

**Issue by tcellerier** [domoticz/domoticz#879]
Hello,

I have 4 temperature sensors from Oregon and 3 of them have now data points in the future in 2018.
Some of them could be deleted with a shift click but others couldn't even though I confirmed their removal in the confirmation pop up.

How can I delete them ? And how data points in the future were logged ? It seems that there is a hitch somewhere.
NB: Data points appear at 2018-12-25 11:59:00 or 2017-12-25 11:59:00

![image](https://cloud.githubusercontent.com/assets/17517740/18636356/c5eab8ac-7e88-11e6-9e7b-771678de7995.png)
![image](https://cloud.githubusercontent.com/assets/17517740/18636382/d9de867c-7e88-11e6-8f41-09b806ac3a79.png)

Thanks

**Comment by sbouchex** [comment]
Is your clock in-sync on the server ? Could you provide a database backup ?

**Comment by gizmocuz** [comment]
You can delete the datapoints when you export the database (from the settings page) and open this with an editor like 'SQLite Expert Personal Edition'
After the changes, you can restore the database (also from the settings page)

Yes, it looks like your clock is not correct !

**Comment by gizmocuz** [comment]
Please use our forum
