### ISSUE TITLE
Selector Switch not working

### ISSUE THREAD

**Issue by apazga** [domoticz/domoticz#884]
Hi!

I'm trying to create a manual switch using "Selector" type but something is not working as it should.
Steps to reproduce it:
1. Switches > Manual Light/Switch
2. Switch Type: Selector. Click Add
3. Edit Selector switch
4. No levels config, so changed to on/off, and then to Selector again and they appear
5. You can't add levels & actions.

It also seems that UI elements are not like before (a few months ago) when trying to edit/create a Selector switch, they are... moved:

![selector switch not working](https://cloud.githubusercontent.com/assets/6894350/18760069/b3678808-80ff-11e6-8b79-7b29425c29ba.png)

Some errors in JavaScript console:
- First one appears when clicking on "Edit" in the Selector switch
- Second one appears each time you add a level

```
LightsController.js:1668 Uncaught TypeError: Cannot read property 'join' of undefined
    EditLightDevice @ LightsController.js:1668
    onclick @ VM364 LightSwitches:1

LightsController.js:1413 Uncaught TypeError: Cannot read property 'split' of undefined
    AddSelectorAction @ LightsController.js:1413
    AddSelectorLevel @ LightsController.js:1302
    onclick @ VM364 LightSwitches:1
```

Best regards!

**Comment by apazga** [comment]
Ok, my fault. Didn't know about "Selector Switch" type when you create it.
If you create it as other different than "selector switch" (the dummy one), errors above appear.

**Comment by gizmocuz** [comment]
Thank you for the feedback, great it is working
