### ISSUE TITLE
Philips Hue White group shows as RGBW

### ISSUE THREAD

**Issue by Abadede** [domoticz/domoticz#887]
I have Philips Hue white lamps. Seperately they appear as dimmer switches (Type: Lighting 2, AC, Dimmer). As a group they appear as a RGBW dimmer switch (Type: Lighting Limitless/Applamp, RGBW, Dimmer).

Using Domoticz 3.5691 on a Raspberry Pi.

**Comment by gizmocuz** [comment]
Is it working ?

**Comment by Abadede** [comment]
Well the on and off buttons and the slide bar are working, but it's not very convenient to have the RGB controls in front of the way where you could have a simple dimmer switch.

**Comment by gizmocuz** [comment]
is it possible to post the output of the API call for the white bulb ?

http://{ipaddress}:{port}/api/{username}

**Comment by Abadede** [comment]
A group of white lamps appears as:

```
{
    "name": "White lamps",
    "lights": [
        "1",
        "2",
        "3"
    ],
    "type": "LightGroup",
    "state": {
        "all_on": false,
        "any_on": false
    },
    "recycle": false,
    "action": {
        "on": false,
        "bri": 252,
        "alert": "none"
    }
}
```

A group of color lamps has additional informations:

```
{
    "name": "Color lamps",
    "lights": [
        "4",
        "5"
    ],
    "type": "LightGroup",
    "state": {
        "all_on": false,
        "any_on": false
    },
    "recycle": false,
    "action": {
        "on": false,
        "bri": 254,
        "hue": 14910,
        "sat": 144,
        "effect": "none",
        "xy": [
            0.4596,
            0.4105
        ],
        "ct": 369,
        "alert": "none",
        "colormode": "ct"
    }
}
```

**Comment by Abadede** [comment]
Single white bulb:

```
{
    "state": {
        "on": false,
        "bri": 254,
        "alert": "none",
        "reachable": true
    },
    "type": "Dimmable light",
    "name": "Hue white lamp 1",
    "modelid": "LWB006",
    "manufacturername": "Philips",
    "uniqueid": "00:17:88:01:10:4c:d4:e6-0b",
    "swversion": "5.38.1.15095"
}
```

Is it what you were asking for?

**Comment by mikefranken** [comment]
and for ambiance white:
     {
      "state": {
        "on": true,
        "bri": 153,
        "ct": 447,
        "alert": "select",
        "colormode": "ct",
        "reachable": true
      },
      "type": "Color temperature light",
      "name": "Staande lamp",
      "modelid": "LTW001",
      "manufacturername": "Philips",
      "uniqueid": "00:17:88:01:10:2e:d4:32-0b",
      "swversion": "5.50.1.16698"
    },

**Comment by gizmocuz** [comment]
Sorry for the delay, was in down-under for some weeks

Yes this is what i was looking for, and very strange, because a bulb is only flagged as RGB(W) if there is a 'sat' and 'hue' field

See line 608 of PhilipsHue.cpp:

`if ((!light["state"]["sat"].empty()) && (!light["state"]["hue"].empty()))`

Others should be added to the system as a basic lighting2 device

**Comment by Abadede** [comment]
I think that part is for individual lights, it is working as intended: there's a LType variable which can be HLTYPE_DIM or HLTYPE_RGBW.

But in the Groups part of the code, starting at line 641, it seems all groups are added as RGBW.
Line 691:
`InsertUpdateSwitch(1000 + gID, HLTYPE_RGBW, tstate.on, tstate.level, tstate.sat, tstate.hue, Name, "");`

**Comment by gizmocuz** [comment]
Ahhh that needs changing
can someone post a group containing RGB(W) lights ? We might have to do the same for groups

**Comment by Abadede** [comment]
Do you mean a group from the Philips API?

**Comment by gizmocuz** [comment]
yes like above

**Comment by Abadede** [comment]
White:

```
{
    "name": "White lamps",
    "lights": [
        "1",
        "2",
        "3"
    ],
    "type": "LightGroup",
    "state": {
        "all_on": false,
        "any_on": false
    },
    "recycle": false,
    "action": {
        "on": false,
        "bri": 252,
        "alert": "none"
    }
}
```

Color:

```
{
    "name": "Color lamps",
    "lights": [
        "4",
        "5"
    ],
    "type": "LightGroup",
    "state": {
        "all_on": false,
        "any_on": false
    },
    "recycle": false,
    "action": {
        "on": false,
        "bri": 254,
        "hue": 14910,
        "sat": 144,
        "effect": "none",
        "xy": [
            0.4596,
            0.4105
        ],
        "ct": 369,
        "alert": "none",
        "colormode": "ct"
    }
}
```

**Comment by gizmocuz** [comment]
Thanks !

**Comment by gizmocuz** [comment]
I pushed some code changes, and a new beta should be available within 30 minutes.
Hope it is working correctly now.
You (might) need to delete your group switches, and after detection, they should now be normal or RGBW types

**Comment by Abadede** [comment]
Thank you, I'll check the beta ASAP.

**Comment by Abadede** [comment]
I just checked the beta, there are a few problems:

Groups of white lamps are now showing as Lighting 2, AC, On/Off, it should be Lighting 2, AC, Dimmer.

The on/off button for white lamps groups in domoticz isn't working, log gives this error:
`Error: Philips Hue: Error received: resource, /lights/239/state, not available`

I think it's because white lamps groups LType = HLTYPE_NORMAL in PhilipsHue.cpp, if you check line 602, LType = HLTYPE_DIM when lamps have bri control.

**Comment by gizmocuz** [comment]
You can edit the light, and set it to dimmer right ?
Could you check it if you make the code patch for the HLTYPE_DIM ? This because i can not test this

**Comment by Abadede** [comment]
Yes I can set the group to dimmer, but on/off button and slider control don't work and I get the same error in domoticz log.

**Comment by Abadede** [comment]
I tried to edit the code with HLTYPE_DIM and got the same error. Group controls are only working correctly if group LType = HLTYPE_RGBW.

**Comment by gizmocuz** [comment]
maybe we should revert this patch as now it is not possible to control the groups ?

**Comment by Abadede** [comment]
Yes it would be better.

**Comment by gizmocuz** [comment]
Reverted, hope someone would like to continue this....

**Comment by Sneezydevil** [comment]
I made a patch around the same time gizmocuz did, and it would have resulted in the same problem.

I think I know what the problem is. ID4 is used to pass the NodeID, but I think ID4 has a max value of 255. Is that correct? Since the code expects all groups to have a NodeID >= 1000 it will allways try the wrong api call.

If my assumption is correct would it be bad to abuse for example ID3 for group or not?

I hope this makes any sense at all.

**Comment by bierre** [comment]
I don't know if it's related to these changes but I've added a new hue bridge to domoticz and all hue color lights only show up as AC and not as RGBW type.

Any clue if it's related?

**Comment by gizmocuz** [comment]
That should not be the case... could you check with the latest beta version (5744)
Checked it here, and i see them all as RGBW

**Comment by bierre** [comment]
Thanx for the quick reply the update did the fix!

**Comment by ksya** [comment]
I just installed the beta, Version: 3.6328, but I still have this issue. The groups (and scenes) still all show as RGBW, even after deleting them and restarting Domoticz.

**Comment by gielie** [comment]
Same problem here, running latest beta. 
Individual white light bulbs are correct but the group shows as rgbw. 

Any idea how to solve this.
