### ISSUE TITLE
Support distro and bins for ARMv8/AArch64 hardware like Marvell ESPRESSOBin Board?

### ISSUE THREAD

**Issue by Hedda** [domoticz/domoticz#889]
Any plans to support distro and binaries for cheap ARMv8/AArch64 hardware like Marvell ESPRESSOBin Board?

http://www.cnx-software.com/2016/09/23/marvell-espressobin-board-with-gigabit-ethernet-sata-pcie-and-usb-3-0-to-launch-for-39-and-up-crowdfunding/

http://www.kickstarter.com/projects/874883570/244313729?token=6a67e544#

**Comment by gizmocuz** [comment]
There is already an aarch64 binary, this one should work already ?

**Comment by gizmocuz** [comment]
Please use our forum
