### ISSUE TITLE
Save Button for parameter not work

### ISSUE THREAD

**Issue by PooLP** [domoticz/domoticz#891]
Hi,

On last Beta, the save Button for parameters do not work. tested on Chrome and IE11.

Bye,
Richard

**Comment by jrich523** [comment]
Which settings?
Are you doing it from the Setup of a zwave controller or in the OpenZWave Control panel?
What version number is listed?
Have you checked the OZW log?

Im having a similar problem on V3.5196 (shouldnt be beta) and it happens in both the hardware setup and the OZWCP. It will say its pushing the setting and then it fails. I had kind of thought I was having an issue with my controller (Aeon z-stick gen 5) but now that you're saying this as well I might have to dig deeper to see whats up

**Comment by gizmocuz** [comment]
Please use our forum

**Comment by PooLP** [comment]
Hi,
Hardware : RPI / RFX433 / ZWAVE
Version : Beta v3.5733
Setup page : Setup / Settings / System (first page of parameter).

I try to change the password of Website Protection (or another parameters), but after click on Apply settings, the console of Google Chrome print this error : Failed to load resource: the server responded with a status of 413 (Request Entity Too Large).

6 months ago everything worked perfectly, I have the problem since the last 2 Beta.

@gizmocuz: Github is not done to report bugs? Usually, yes!

**Comment by gizmocuz** [comment]
Non-coders, should use our forum, i would like to keep this issue thing here for code discussion.
But it looks everyone is posting also here, and sometimes also cross posting in the forum.
I might disable this issue thing here soon

**Comment by gizmocuz** [comment]
So, are you able to debug this in combination with the code ?

**Comment by PooLP** [comment]
Ok, this is the problem of using multiple platform to communicate, it's a real problem for large projects.

For debug, I have to look, I don't know much Angular. I have a backup of my plateform for compare. Thanks for your response ;)

**Comment by PooLP** [comment]
Hi,

i have NGINX server for domain/security. I have added this `client_max_body_size 128M;` to `/etc/nginx/nginx.conf`

http://cnedelcu.blogspot.fr/2013/09/nginx-error-413-request-entity-too-large.html

Thanks,
Richard

ps : it's not a bug, please close it ;)

**Comment by gizmocuz** [comment]
Thanks for the feedback!

**Comment by gizmocuz** [comment]
It was already closed on 5th of october
