### ISSUE TITLE
Open 'More Options' menu not possible with a touchscreen device

### ISSUE THREAD

**Issue by RaymondNg2** [domoticz/domoticz#892]
When opening the Settings menu and selecting the 'More Options' the whole menu collapses.
This behaviour makes it impossible for touchscreen devices to access the 'More Options' menu.

Proposal
When selecting/pressing the 'More Options' option don't collapse the Settings menu.

**Comment by gizmocuz** [comment]
We could hide the settings menu for small devices...
It is something you want to do on a normal desktop sized pc anyway
Or maybe there is a HTML genius here that can make it scroll when the height is to small ?

**Comment by RaymondNg2** [comment]
The problem is not that menu is too long.
You should have a smartphone available.

Try to access the Events page.
What happens if I try it.
Press on Setup menu icon -> Menu opens
Press on More Options -> Menu closes

The More Options menu only shows on mouseover.
With a touchscreen you don't have a mouseover.

**Comment by gizmocuz** [comment]
As mentioned, please provide a patch if possible

**Comment by RaymondNg2** [comment]
I didn't know you were referring to me when you mentioned a HTML genius. 

My bad. 

I will give it a try and come with a pullrequest when I have managed to do it.

**Comment by gizmocuz** [comment]
That would be great ! You or Any ;) _lol_

**Comment by jrich523** [comment]
Its basically the menu system. I havent dug in to what you're using, but i assume it isnt home grown?

Also as a work around if you hold the button (more options) it will pop out that menu, and end up selecting text... kind of a pain but it does work.

My HTML blows so i cant really help there, but there is a guy who was redoing the UI in a cleaner way with Angular. There is a ticket some place, he did the Weather page i think? It might be worth asking him since he seems to have some really solid web dev skills

guy found: @gaeljw :)

**Comment by gaeljw** [comment]
Looks like dropdown submenus were deprecated in Bootstrap 3 because of this very behavior on mobiles.

Nevertheless, I think following JS code could make it work : 

```
$('a#cMoreOptions').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    $('a#cMoreOptions').trigger('mouseenter');
});
```

I only tried it in Chrome dev console, please test it a bit more ;)

**Comment by RaymondNg2** [comment]
@gaeljw Your solution works for me on Chrome and on Windows 10 Mobile Edge.
I have added the code to index.html.

When is the new ui available? Is it still usefull to create a pullrequest for this when it will not be relevant in the near future?

**Comment by gizmocuz** [comment]
I like the dropdown menu... what is the alternative ?
Yes, a pull request will do... is this patch working correct for mobile and non-mobile?

**Comment by gaeljw** [comment]
@RaymondNg2 if by "new ui" you mean the Angular refactoring I started, I don't expect it to be finished any time soon because I don't have a lot of time currently. But my goal is not to do any change to the ui, only improve the code, so feel free to do any pull request :)
