### ISSUE TITLE
Bad values reported for RFXMeter

### ISSUE THREAD

**Issue by mangoose002** [domoticz/domoticz#893]
Hi,

I have built a Tank level sensor that send dataas RFXMeter with RF433 device to a connected RFLINK ( version 1_1_43). Unfortunately the values reported in Domoticz seem incorrect.

If I send a value of 2303 (for instance), the RFLINK displays 2303 (as digital), but Domoticz reports 8963, as if it assumed that the value reported by RFLINK was hex instead of dec and the converted it.

If I am unclear, please tell me.

-Pierre-

**Comment by gizmocuz** [comment]
Please use our forum
