### ISSUE TITLE
Re-implement Harmony Hub as selector

### ISSUE THREAD

**Issue by rozza-m** [domoticz/domoticz#898]
Logitech Harmony Hub has been natively supported since 1.1956.
It's chief function is switching between "activities" that are mutually exclusive - and each one is shown as a separate switch.

Selector switch was added on 6th January.

A great improvement would be to consolidate the switches so that they are displayed natively as a selector when the harmony hub is added. Thanks!

**Comment by gizmocuz** [comment]
Please use our forum

**Comment by rozza-m** [comment]
Could you elaborate please?

**Comment by gizmocuz** [comment]
We have many forum users, and surely you will find someone to discuss with, or maybe program with

**Comment by rozza-m** [comment]
Ok, so I take this to mean "yes this might be a good idea, no I don't plan to do it because of priorities (or whatever), the project is open source so you are welcome to do it yourself"

Fair enough.

**Comment by gizmocuz** [comment]
Correct... ;) And yes, i like the idea
