### ISSUE TITLE
Support request for new switch type Siemens SF01 in the RFXCOM device

### ISSUE THREAD

**Issue by swl2861** [domoticz/domoticz#899]
It seems like Domoticz doesn't support the Siemens extractor hood with SF01 remote control RFXCOM device type  :(

Is it possible to add this hardware support? :)
## I have some dumpscreens, the command line have different variables: 

+
Learn
Light
Timer

And this is the output I get from RFXCOM:
# Fan command

Packettype = Fan
subtype = Siemens SF01
Sequence nbr = 42
ID = 0D1D
Command = -
## Signal level = 0 -120dBm

---

Packettype = Receiver/Transmitter Message
subtype = Transmitter Response
Sequence nbr = 42
response = ACK, data correct transmitted

**Comment by gizmocuz** [comment]
I am not into fans, but what can you do with the fan in combination with RFXCom (what would you like to do ?)

**Comment by swl2861** [comment]
Hi Gizmocuz, 

I like it to do all the functions that are available in the remote controller and RFXCOM.
These are: 
"Timer" - this is to start the ventilator for a xx time
"-" - to speed down and then turn off the fan  
"Learn" - to learn a manual programmed event
"+" - to start or speed up the fan
"Confirm" - to send a new remote recognition signal to the Siemens extractor hood
"Light" - to turn the light on or off

I have heard from RFXCOM support that Domoticz allready has all the information about the Siemens SF01, if you need more, let me know! :)

**Comment by swl2861** [comment]
does someone know how to get a request fulfilled? i really like to have this feature, it's the only thing i have bought the RFXCOM for...

**Comment by swl2861** [comment]
I'm looking into the developing new hardware wiki and going through the files mentioned. I found traces of the Siemens sf01 already in some code. What more i noticed is that the types of RFXCOM hardware that is showing are only the general types. The Siemens sf01 is a fan type... So if i change the siemens from fan type to general type i can select the siemens?!!

**Comment by swl2861** [comment]
I tried to understand the code but i failed :( - hope someone can pick this up :)
