### ISSUE TITLE
Trnaslation

### ISSUE THREAD

**Issue by jotakar** [domoticz/domoticz#900]
I have a Qubino thermostat and when you edit the temperature for switching ON/OFF Domoticz shows a window with two arrows (UP/DOWN) and a button to apply the value of temperature. Thats OK. But in spanish the button label says "**conjunto**" (the meaning of this word is a group of things) a better translation would be "**aplicar**" 
Thanks

**Comment by gizmocuz** [comment]
You have to request this on our transifex page:
https://www.transifex.com/domoticz/domoticz/dashboard/

Please keep these kind of questions on our forum, in the right (translation) section
