### ISSUE TITLE
Compiling requires huge amount of RAM

### ISSUE THREAD

**Issue by src386** [domoticz/domoticz#902]
Hello,

Steps to reproduce : 

```
cmake -DCMAKE_BUILD_TYPE=Release .
make
```

**htop** shows memory usage up to 600MB, potentially x2 if using -j2 option : 

![](https://framapic.org/QV3wfkbcL8uv/69dqaf4EJSaj)

**Comment by xbeaudouin** [comment]
This C++... Not an issue about domoticz itself.

**Comment by gizmocuz** [comment]
True, but i also find it a bit high... and slow... 
No idea if or how this can be adjusted ;)

**Comment by xbeaudouin** [comment]
Using Clang (OS X / FreeBSD) take a bit less RAM (had a max usage about ~ 450M on a x64 machine).
One way to use less RAM is using system library (and prebuilt libs) like lua, sqlite, ... :p 
But unfortunately C++ is a complex language that use ram to make optimization on the code generated.
Way to reduce memory footprint : 
- use less optimization on the compiler flags, but this can raise slower code OR more memory usage upon run
- use another compiler (there is some C++ that uses less memory)
- rewrite domoticz in other language (but really this is not an option...).

IMHO I rather like to have long compilation and memory usage,  and have a really optimized code after that, than getting a slow domoticz.

I think you can complains on GCC/G++ developers but we have not too much way to handle that.

Maybe try to optimize the C++ code but I don't think we will get a significant improvement while compiling.
