### ISSUE TITLE
Angular map file in appcache not found

### ISSUE THREAD

**Issue by rkluwen** [domoticz/domoticz#905]
After the latest update, the appcache refresh fails.
I get the following error in my logs:

2016-10-08 21:14:41.310 Error: Webserver: File '/angular.min.js.map': No such file or directory (2)

**Comment by gizmocuz** [comment]
Some javascript files reference a map file at the bottom.
In all cases, i remove this line, as is also the case with the angular.min.js file.
It should not ask for this file.

it is also not asking for it here (chrome browser)

**Comment by gizmocuz** [comment]
Can we close this issue ?
