### ISSUE TITLE
[setcolbrightnessvalue] RGB Saturation

### ISSUE THREAD

**Issue by rswilem** [domoticz/domoticz#909]
Heya,

Would love to have a way to update "saturation" through the API.
For me it seems there's never a way to fully update a colour through the API for now.

I have sniffed the Domoticz Web UI and it seems that not even the Web UI is able to update the saturation.

Here's the API url the Web UI sends:

```
http://localhost:8081/json.htm?type=command&param=setcolbrightnessvalue&idx=10&hue=205&brightness=100&iswhite=false
```

As you can see, `&saturation=10` is missing here.

Any thoughts on this one?

PS. I just saw that there's a `&hex=F08040` parameter for the same call, would that one update the saturation perhaps?

Thanks in advance!

**Comment by gizmocuz** [comment]
with the hex call use should be able to set all possible RGB(W) values

**Comment by rswilem** [comment]
Have to bring this one up again, I have just checked with `&hex=` instead of `&hue=`, `&brightness=` and `&iswhite=`.

I'm sorry to say but the result is exactly the same. Colour changing works, but as soon as one starts messing with the saturation (more whitey~ish), the lamp color does not change at all.

For example, I can get a full red (e.g. `FF0000`) colour from my hue lamp, but cannot seem to get a white-pink (e.g. `FF7777`) colour out of it.

Have tried with the hue api itself, this works as designed.

Any clues? 🤔

**Comment by gizmocuz** [comment]
I think some code needs to be changed

**Comment by C-Duv** [comment]
Any update on saturation for RGBW lamps?
