### ISSUE TITLE
OTGW - Use PS=0 messages or give PS=1 after PS=0

### ISSUE THREAD

**Issue by rhannink** [domoticz/domoticz#913]
Hello,

Besides Domoticz, I have also 2 other devices reading messages from the OTGW. Both other devices (Homey and the Opentherm Gateway monitor) need the PS=0 messages to operate.

Is it possible to have Domoticz also reading the continues PS=0 messages or issue a PS=0 command after domticz has send the PS=1 command?

Gr. Remco

**Comment by gizmocuz** [comment]
nope... i would advise you to stop reading with either of the 3 if you want to do testing

**Comment by gizmocuz** [comment]
Unfortunately not a domoticz issue
