### ISSUE TITLE
Door Locks are backwards

### ISSUE THREAD

**Issue by jrich523** [domoticz/domoticz#916]
I've played around with this enough now to know that its a bug.

If you look in OZW CP it shows the state as "On" when the door is locked (This seems correct)
![OZW CP](https://snag.gy/2iMrJj.jpg)

If you look at the Device List you can see that it shows it as "Open". Which for most other things On = Open, however in the case of a lock this is backwards.

![Device List](https://snag.gy/Oad85q.jpg)

Im going to try to start digging in to this myself but if someone can provide some info on where abouts I should look for this, or perhaps a method to solving this, that would be greatly appreciated.

**Comment by gizmocuz** [comment]
Okey, this means we need an inverted door type ? Or a new lock type ? Which on do you prever

**Comment by RicardP** [comment]
A door lock not having any influence "like not there" is Off or "Unlocked". In this case OZW = On (Locked), it should then say "Locked" in Domoticz. So it is strongly suggested to also change the term from Open/Closed to Locked/ Unlocked. Same as blinds fully winded up is off (window is not covered) should say Up, or Down with following percentage of blinding.

**Comment by gizmocuz** [comment]
Thats not what i asked.
Blinds bdw say open/close in the gui, still internally it is on/off , 0 or 1, whatever

So you want a lock ? that says locked/unlocked ? Ok... i see what i can do

**Comment by jrich523** [comment]
Yes exactly @gizmocuz, the 'Door Lock' option should be Locked (on) and Unlocked (off)

Again I'd be willing to help if you could at least point me in the right direction.

**Comment by simonrb2000** [comment]
Any update on this? Would be handy as mine are On is Closed and Off is Open

**Comment by gizmocuz** [comment]
We are not going to talk about Closed/Open anymore for door locks... going to be Locked/Unlocked
Working on this as we speak
First beta update will have a renamed switch type: 'Door Lock' is renamed to 'Door Contact'

**Comment by gizmocuz** [comment]
Implemented in beta # 6623, building as we speak, could take 1.5 hours

Is it possible to test this ?
- update to the latest beta
- Clear the appcache + browser cache
- edit the switch, which should now be on 'door contact', and make it a 'door lock' type

Fingers crossed

**Comment by jrich523** [comment]
I was able to update to the buid and change to "door lock" vs door contact but its not working correctly. It doesnt update the state at all and it wont change the state either. Im traveling for work at the moment so I havent been able to test much, but so far its not looking good :(

i'll get more info when i get some free time but i think my time is allocated until march, just wanted to provide a quick update, Thanks!

**Comment by gizmocuz** [comment]
Okey, please test if you have time... as i do not know what to make of

"It doesnt update the state at all" and "it wont change the state either"

**Comment by jrich523** [comment]
sorry, by state i mean physical position either changing it from locked or unlocked via the UI or if i physically change the lock the state of the GUI doesnt update. basically it is no  way working correctly other than it shows the icon correctly in relation to what the system thinks is the state of the lock (Which is usually wrong)

**Comment by gizmocuz** [comment]
Okey....

A short recap:
a) the display in the gui is correct
b) the commands 'send' when you click the lock/unlock / icon are reversed ?

c) 'b' is not working at all ?

**Comment by gizmocuz** [comment]
no feedback, probably all working then ?

**Comment by claudiudia** [comment]
FWIW, this works for me now, with a vision zm1701 lock. The state shows correctly and I can open/close as expected. Thanks for fixing this.

Now if someone could figure out a way to set the user codes for this lock with openzwavw/domoticz... :-)

**Comment by gherik** [comment]
Just letting you know that with Domoticz version 3.7649 the "Popp Electric Strike Lock Control - 012501" is working correctly with Switch Type "Door Lock". The Door is now default "Locked" :-)

**Comment by gizmocuz** [comment]
Thanks for the feedback !! Great it's working !

**Comment by jannnfe** [comment]
Hello
sorry for revisiting this problem. I have the latest version of Domoticz installed (I get the message in the web interface my software is up to date) but the device "Door Lock" is default "Unlocked" in my starting position. How can I get it, that the device is "Locked" by default, but I still can open and close my door with this device?
Thanks for your help!

**Comment by gizmocuz** [comment]
@jannnfe , what hardware are you using for the lock ? Is it a lock or a contact? In the later case you should use the 'door contact' type

**Comment by jannnfe** [comment]
I use a sonoff that gives a closing contact to activate the door opener on my door. While the Sonoff is "ON" you can open the door, if it is "OFF" the door is locked. So it is not a door contact but a door opener you should also control via Domoticz, which already works only the representation in the web interface of Domoticz is reversed.

**Comment by gizmocuz** [comment]
So you can turn it both on and off ? Then i would use a On/Off type (default) and make a custom icon ?

**Comment by jannnfe** [comment]
Hello,
new issue. I need a Door Contact Inverted :(
The problem is that I can not just take an ON/OFF type and just change the icon, because I need to get the type Door Lock for the homebidge-edomoticz plugin. Homekit, or homebidge-edomoticz plugin, also represents the door sensor as a door only with the type is Door Lock.
It would be great if that could be implemented.
I use a sonoff basic with a reed sensor as switchmode 2 and switchtopic.
Thanks Jan!

**Comment by gizmocuz** [comment]
How do you mean "switchmode 2 and switchtopic" ?
The Door Contact sensor is used by many hardware, out of the box door contact sensors.
Why should a self build contact sensor be inverted ? Is there something you can change in the sonoff device ?
