### ISSUE TITLE
increase maximum Short Log Sensors

### ISSUE THREAD

**Issue by mledoujet** [domoticz/domoticz#920]
Hi,

Would it be possible to increase max value for the "short log sensors" (for temp and utility)
Actually, i use 7 days, but i'd like to set the value to 30 or more if possible.

In fact, i am wondering wich are the impacts on the db. More data would be stored?
Are the data cleaned and averaged once the "short log sensors" delay is over ?

regards,

**Comment by gizmocuz** [comment]
More data will be stored, system will get slower

**Comment by gizmocuz** [comment]
Please use our forum
