### ISSUE TITLE
function domoticz_updateDevice doesn't work

### ISSUE THREAD

**Issue by FrBoulli** [domoticz/domoticz#924]
Hi ,

The function domoticz_updateDevice doesn't work when used in a lua_parser script.
There is a issue in the source code file /domoticz/main/LuaHandler.cpp

To solve this i've replaced this line (line 227 in app version 5687)
`result = m_sql.safe_query("SELECT HardwareID, DeviceID, Unit, Type, SubType FROM DeviceStatus WHERE (**DeviceID**==%d)", ideviceId);`
with this one 
`result = m_sql.safe_query("SELECT HardwareID, DeviceID, Unit, Type, SubType FROM DeviceStatus WHERE (**ID**==%d)", ideviceId);`

Now the function works fine !

**Comment by jrich523** [comment]
There is another similar issue with the OZW CP, Im kinda curious how far this problem goes... should probably do some testing to see where configs can and cant be set correctly.

**Comment by gizmocuz** [comment]
@FrBoulli, thanks, i corrected the code
@jrich523, i am not aware of this, and this has nothing to do with Lua ;) also not everything is supported in the OZW CP, some things you have to do directly in domoticz.

**Comment by jrich523** [comment]
yeah @gizmocuz, I kinda of figured this was unlikely related, but there was an issue (maybe forum post) that someone had mentioned that configs werent being pushed to devices. I am having some similar issues but I dont feel my environment is in a clean enough state to do testing on this. might be time for me to clean out and reset to your code base..
