### ISSUE TITLE
Modbus Hardware Support

### ISSUE THREAD

**Issue by tominagaf** [domoticz/domoticz#926]
Is there any plan to include Modbus hardware support? 
I am trying to connect a centralized air conditioner controller made by EVCO. It has both Modbus RTU and Modbus TCP interfaces.

**Comment by gizmocuz** [comment]
One thing you should not do... actually 2
Dont use this issue page for non-code related issues, and second, do not cross post on the forum and here

**Comment by tominagaf** [comment]
I'm really sorry. I did not know where to post requests for new features.I apologize. Thank you for your time.

**Comment by gizmocuz** [comment]
You posted it on the correct place (the forum), only you have to wait until a developer will implement this
