### ISSUE TITLE
Support LuaRocks

### ISSUE THREAD

**Issue by dantman** [domoticz/domoticz#931]
I think it would be a good idea to support modules installed via LuaRocks when luarocks is installed.

---

The current situation of library usage in Lua seems to be well demonstrated with this wiki page, which seems to be the expected way of getting access to a JSON parsing library.
https://www.domoticz.com/wiki/Lua_-_json.lua

The problems with this approach:
- The code is out of date (wiki:20141223.14, current:20160916.19)
- Of the many json implementations in lua, there are others with less bugs encoding/decoding mistakes (http://lua-users.org/wiki/JsonModules; dkjson or lua-cjson appear to be the preferred JSON libraries)
- Exact paths specific to the installation/OS/etc are used; so this technique doesn't work well for Smart Lua Scripts wanting JSON

Instead of telling users to download a file each time, it would probably be better let Smart Lua Scripts `require` the ones needed and tell the user how to install the necessary modules from luarocks.

---

The primary change needed seems to be making sure that when luarocks is installed Domoticz gets the right LUA_PATH to execute scripts with so that `require` knows where to look.

But as an extra, it would also be nice if the prebuilt Raspberry PI image came with the `luarocks` deb package pre-installed.

**Comment by gizmocuz** [comment]
Hmmm the wiki might be out of date, but it is also meant as an example.
Please feel free to update the wiki.

About JSON, we use 'jf-JSON' and this is a good library, also in your list.

Time it always a problem, but we're trying to include 'dzEvents' in the native domoticz distribution.
Did you had a look at this ?

Editing a path file in a script is not that hard, but i agree, not so nice, but you have to edit the file anyway.

It also keeps all 'required' files in place, a user can just make a copy of the scripts folder, and restore later

**Comment by gizmocuz** [comment]
Forgot to tell, the file we distribute now (since yesterday) is up 2 date, i will adjust the wiki

**Comment by dantman** [comment]
jf-JSON works, but other libraries handle things like mixed tables and 'sparse' arrays better.

The library was updated 5 times without any updates to the wiki; which only got updated now because I pointed it out. That's not going to scale, it's better to just make use of the standard package manager for the language which will always have the current version.

Also, having to edit the file anyways is not a given. Many of the smart Lua scripts run without any edits or configuration needed.
https://www.domoticz.com/wiki/Smart_Lua_Scripts
You just install it (ie: drop the script in your scripts folder) and follow a certain pattern of naming instead of editing the script.
So for a script that doesn't need customization, being able to require a package would be better than making the user edit the script to use the correct path.

LuaRocks _can_ be made to install into a specific tree:
http://leafo.net/guides/customizing-the-luarocks-tree.html

So it might make the instructions to install a package more difficult, but instead of the global tree we 'could' use something else where lua packages from LuaRocks are placed somewhere relative to `./scripts` but not directly in the `./scripts/lua` folder.

And I suppose if we did that then Domoticz could be smarter about it. Domoticz would know where to look for the packages so I suppose the web interface could also list installed LuaRocks packages and let you instead them from there. That would make database based lua scripts easier as well.

**Comment by gizmocuz** [comment]
I am not saying it is a bad idea.... maybe it got your intention because i included the lua json parser yesterday evening
The installation of the package manager under windows seems a bit more complex then for Linux.
But i like the idea.

**Comment by sbouchex** [comment]
If some json parsing is needed, the domoticz_applyJsonPath LUA function may be used as well to parse some data. There is an example under scripts\lua_parsers\example_json.lua, it uses the domoticz server JSON parser.

**Comment by RicardP** [comment]
(I am not into coding but I believe it would be highly appreciated from most users to point the code direction towards a graphic based app/plugin section in Domoticz, that I think would drive Domoticz to a much smarter system... Easy and more fun for developers to announce their new plugins and describe it functions and a new world would open up. I am using Qnap nas and their appcenter is a really good idea)

**Comment by gizmocuz** [comment]
We got some ideas about this indeed, not related to the OP topic
