### ISSUE TITLE
logrotate compatibility

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#932]
Current server implementation does not allow logrotate to rotate de domoticz log.
What needs to be done:
- Provide a log rotate.d script to will rotate the file
- Modify the startup script to have a "reload" action which will do a kkill -HUP to domoticz

I can work on it

**Comment by gizmocuz** [comment]
You can for a log rotate by sending a SIGHUP to an application, also for domoticz (non win32 only)

**Comment by sbouchex** [comment]
Yup but the "reload" action is missing to do a kill, a simple pkill -HUP domoticz will do the job, I plan to provide a logrotate.d as well.

**Comment by gizmocuz** [comment]
Okey ;) perfect

**Comment by sbouchex** [comment]
Any suggestion to locate the logrotate.d file ? under script ? elsewhere ?

**Comment by gizmocuz** [comment]
scripts sound like a nice location for this
