### ISSUE TITLE
Qubino thermostat setpoints not setting

### ISSUE THREAD

**Issue by stuiow** [domoticz/domoticz#934]
Recently had a ZMNHIDx die. Received a replacement today and nothing is working as it used to.

I set a set-point of 45 or 60. I cant input anything over 33, when i do, it defaults to 23.
I have managed to get the setpoint to 50 by inputting 32.9 in Domoticz and in OZW, it come up as 50.

Also, the wording on the Thermostat mode has been noted as changed from Auto/off to Heat/off.
Maybe related in someway?
Forum thread 
[http://www.domoticz.com/forum/viewtopic.php?f=24&t=13858&p=100552#p100552](url)

I'm on 3.5187 but unsure when changes were made due to being without a thermostat relay while the other one was replaced, (been without for roughly 10 days)

In regards to setting up, there are some settings that will not get saved.
11. Set point L1 - Wont change from 1.
43. Hysteresis On: 0  (default is 132) nothing is accepted in this box, tried putting to default, reverts to 0.

There maybe more, but that's all i am aware of.
Another user, also using latest beta also has similar issues.

**Comment by matok64** [comment]
I have similar problem.
My old qubino thermostat works fine. New qubino thermostat is different. In manual, for example, Hysterresis On says:
0-127  =  0.0°C ... 12.7°C
1001-1127 = -0.1°C ... -12.7°C
Default value:  1005 (-0.5°C)

I founded, that exists two config files: ZMNHIDxS1.xml  and  ZMNHIDxS2.xml
But manual for new version of thermostat add  Parameter no. 59 - Thermostat mode - Heat or Cool mode - for Cool mode -  When Cooling mode selected, the function of Hysteresis On and Hysteresis Off is inverted!

I don't know, how it set it, I am totally new in Zwave and Domoticz (1 week used), but probably qubino changed som params and Domoticz don't modified it.

And yes, I have similar problem with setting  set-point. Whatever I set, it back changed to 23.

**Comment by matok64** [comment]
Next thing, default my thermostat is probably in Cooling state, but I don't know, how change parameter no. 59, or parameter no. 13 - I3 functionality selection - this can change the mode of thermostat between Heat and Cool.  This setting is in manual for my new qubino thermostat, but domoticz load ZMNHIDxS1.xml and this setting is in ZMNHIDxS2.xml
How can I make domoticz load for ZMNHIDxS2.xml config for my new qubino?

**Comment by Pulcik** [comment]
I have exactly same issues like you. Domoticz thinks it is S1 version, but according the device, it is S2 version.
So, can anybody tell us how to force to use correct config?

**Comment by stuiow** [comment]
read the comments on this link from Github Openzwave.
https://github.com/OpenZWave/open-zwave/commit/83919e36719967c83a4d2b5b9520a8a9b463f820

**Comment by Pulcik** [comment]
Thanks, now it is working.

**Comment by stuiow** [comment]
Its working as it should (setpoints settings correctly etc...)?

**Comment by Pulcik** [comment]
Yes, it seems like that. The Setpoint setting now work like others.

I just change the config/manufacturer_specific.xml to force to grab the S2 config, then delete zwcfg_0x$$$$$$$$.xml file. With new start of domoticz, new Device - Setpoit appeared in list. Delete the old one and start using a new functional one.

**Comment by stuiow** [comment]
Still not working.
