### ISSUE TITLE
[MQTT] Switchcmd setcolbrightnessvalue

### ISSUE THREAD

**Issue by rswilem** [domoticz/domoticz#936]
Heya!

Currently, there is no way to update `setcolbrightnessvalue` through MQTT.
Example payload:

```
{"command": "switchlight", "idx": 2450, "switchcmd": "setcolbrightnessvalue", "hex": "FF0000" }
```

I recon that is because of [line 260 in domoticz/MQTT.cpp](https://github.com/domoticz/domoticz/blob/3741a530c2260cea2f337a095aa9477847fc00cb/hardware/MQTT.cpp#L260).

Not sure if it is much work to implement, or if it is just a "redirect" to the generic `setcolbrightnessvalue` function, but in any case this function is missing.

Thanks in advance for adding!

**Comment by gizmocuz** [comment]
Could you compile domoticz yourself (see our wiki page), and try this ?

**Comment by jonferreira** [comment]
Given that a setcolbrightnessvalue HTTP request looks like 

http://192.168.1.2:8080/json.htm?type=command&param=setcolbrightnessvalue&idx=57&hue=129&brightness=60&iswhite=false

I reckon that we'd need to specifically add support for the setcolbrightnessvalue function on MQTT.cpp

```
else if (szCommand == "setcolbrightnessvalue")
	{
		if (root["switchcmd"].empty())
			goto mqttinvaliddata;
		if (!root["switchcmd"].isString())
			goto mqttinvaliddata;
			
		int brightness = 0;
		if (!root["brightness"].empty())
		{
			if (root["brightness"].isString())
				brightness = atoi(root["brightness"].asString().c_str());
			else
				brightness = root["brightness"].asInt();
		}
		
		int hue = 0;
		if (!root["hue"].empty())
		{
			if (root["hue"].isString())
				hue = atoi(root["hue"].asString().c_str());
			else
				hue = root["hue"].asInt();
		}
		
		var isWhite = false;
		if (!root["isWhite"].empty())
		{
			if (root["isWhite"].isString())
				isWhite = atoi(root["isWhite"].asString().c_str());
			else
				isWhite = root["isWhite"].asInt();
		}
		
		if (!m_mainworker.SetColValue(idx, hue, brightness, isWhite) == true)
		{
			_log.Log(LOG_ERROR, "MQTT: Error sending switch command!");
		}
		return;
}
```

The above *may* work but unfortunately I'm not used to compile domoticz myself so I'm unable to test it :-(

**Comment by rswilem** [comment]
THANKS A BUNCH! ❤️

https://github.com/domoticz/domoticz/pull/1061
