### ISSUE TITLE
Enhance/Improve timer options

### ISSUE THREAD

**Issue by tom87** [domoticz/domoticz#944]
"Weekends" and "Weekdays" are nice options but what would really be helpful is "work day" and "non work day" (you could also call it "day type A" and "day type B"). And then some sort of calendar function where I can mark days type A or type B.
Cause most of my timers are dependent on wether I am home that day or not and with public holidays and vacation days it's a huge pain to always manually change all timers.

**Comment by stuiow** [comment]
I'm a shift worker (earlies and lates), maybe add a bi-weekly schedule if improvements were to be made?!

**Comment by gizmocuz** [comment]
At the moment we have to timer plans. Normal and Holiday, which you can choose from the settings.
I could rather easy extend this, so you can make your own timers plans.
When you switch a timer plan, you can/must totally create your timers.
I could add a copy/past from one timer to another
Is this an option ?

**Comment by stuiow** [comment]
Been thinking about this for a few days and I think this may be a good solution, especially the copy and paste between timers too.

**Comment by tom87** [comment]
Didn't even realize there already was such a thing as a timer plan. That's pretty hidden.
When editing/adding a timer an option to select for which timer plan the timer is would be nice, so I don't have to switch back and forth in the settings.
If possible a way to pre-select timer plans in a calendar or something like this would be perfect.
If not, is it possible to switch timer plans via API?

**Comment by gizmocuz** [comment]
Yes, if we can switch it from the web interface, we can switch it with the 'api'
But i can only start with this probably next week

**Comment by ai3xbe** [comment]
It would be really great if you could add extra boolean logic to the timer interface as well. Maybe an option to make the timer dependant on a variable or switch?

Context: I'm really in to presence detection, it would be great to be able to trip a timer only if a person is set to home. Currently I'm doing this via LUA but it would be great (and a lot clearer) to do it natively. 

ps. let me know if I should add this is a separate issue.

**Comment by gizmocuz** [comment]
Added the timer editor:
https://github.com/domoticz/domoticz/commit/d0e3244e53690dc40662d6dfa309ffced5def097

new beta version should be available within the hour, hope all is working well

**Comment by gizmocuz** [comment]
Implemented, closing issue

**Comment by benganellison** [comment]
Did you ever implement the copy function. i can't find any such

**Comment by gizmocuz** [comment]
Yes under settings -> more options -> plans -> timer plans

**Comment by benganellison** [comment]
Can I really copy a plan there? I only found create and rename

**Comment by inzuno** [comment]
Hello
Is this function implemented in the stable release?
I can create many timer plans but there is no option to copy one. Can you help me?
![image](https://user-images.githubusercontent.com/20598242/45942021-09565600-bfe1-11e8-9556-d8c1c401eed3.png)
Thanks

**Comment by gizmocuz** [comment]
@inzuno , no this was not implemented yet.
But... please try beta 10009, i added support for it here
