### ISSUE TITLE
Blockly save action causes 414 Request-URI Too Large

### ISSUE THREAD

**Issue by w1ll14m** [domoticz/domoticz#948]
Hi,

I have an issue with saving blockly events, it triggers an "414 Request-URI Too Large"

My system/situation:
Domoticz V3.5841 is running behind apache2.
Apache has an hardcoded 8190 bytes limit on LimitRequestLine and thus if a request is larger than 8190 bytes it triggers the 414. There is no message that it failed saving so if you close the browser your blockly isn't saved.

Possible solution:
Change the way how blockly saves the event to a do http post instead of a request.

View the request that caused a 414 below.

Thanks for the great work!

Best regards,
William

`https://domoticz/json.htm?type=events^&param=create^&name=AutoVerlichting^&interpreter=Blockly^&eventtype=All^&xml=^%^3Cxml^%^20xmlns^%^3D^%^22http^%^3A^%^2F^%^2Fwww.w3.org^%^2F1999^%^2Fxhtml^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22domoticzcontrols_ifelseif^%^22^%^20id^%^3D^%^22o^%^3DyXG^%^2CVWOXazt^%^2Cyo^%^60yhC^%^22^%^20x^%^3D^%^229^%^22^%^20y^%^3D^%^2288^%^22^%^3E^%^3Cmutation^%^20elseif^%^3D^%^226^%^22^%^3E^%^3C^%^2Fmutation^%^3E^%^3Cvalue^%^20name^%^3D^%^22IF0^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_compare^%^22^%^20id^%^3D^%^22tsk^%^3BP^%^40^%^23xo^!Q9~(bk^%^5B~^%^7C^%^5B^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22OP^%^22^%^3EGT^%^3C^%^2Ffield^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22utilityvariables^%^22^%^20id^%^3D^%^221icK7yTo0DR^%^3Arrme1QEW^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Utility^%^22^%^3E102^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22math_number^%^22^%^20id^%^3D^%^22^%^25I5)ZSj^%^25c-aF_)Nz^%^3A5^%^3DW^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E400^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cstatement^%^20name^%^3D^%^22DO0^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22^%^3B2xSfea^%^5B6cDt.U7^%^3F^%^7BZT^%^2B^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesAF^%^22^%^20id^%^3D^%^223PsJPIX((9vySuBVh^%^40.C^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E114^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_states^%^22^%^20id^%^3D^%^22i^%^25Qw9m~A9tELawxd0C_V^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22State^%^22^%^3EOff^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cnext^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22B^%^60ugKaM3b^%^3BNrnj5-ty^%^7BZ^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesSZ^%^22^%^20id^%^3D^%^22tM^%^3DueK1^%^5DhV^%^7BP*dc^!^%^3Fu_V^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E117^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_states^%^22^%^20id^%^3D^%^226b5ni9MY^!qahjr^%^2BEj^%^259l^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22State^%^22^%^3EOff^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fnext^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fstatement^%^3E^%^3Cvalue^%^20name^%^3D^%^22IF1^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_compare^%^22^%^20id^%^3D^%^22*j0wU~C_mDA4T^%^3Dr^%^2B*XVI^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22OP^%^22^%^3ELT^%^3C^%^2Ffield^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22utilityvariables^%^22^%^20id^%^3D^%^22^%^3AR^%^3BAt~^%^5DATRBl^%^3BTQIt.0w^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Utility^%^22^%^3E102^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22math_number^%^22^%^20id^%^3D^%^229g0R^%^3BwlGP.X~rx^%^2B^%^5EBdw7^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E400^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cstatement^%^20name^%^3D^%^22DO1^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22^!Pvaq^%^5B^!yld5U8FLE^%^3Fdoh^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesAF^%^22^%^20id^%^3D^%^22ToS^%^3FN56^%^609YTN3r8KUkqm^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E114^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_setlevel^%^22^%^20id^%^3D^%^22^%^7DcKazX^%^408O626dDInRt)c^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E75^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cnext^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22P^%^3BgV-u^%^7Drj1T^%^5D^%^25^!^%^7DxjW^%^2B^%^60^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesSZ^%^22^%^20id^%^3D^%^22Tq^%^5D^%^5DqE0FJ*^%^60C-Vt^%^2BVa7^%^7B^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E117^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_setlevel^%^22^%^20id^%^3D^%^22qszU^%^2BwXDo^%^7CQD_cncaspo^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E75^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fnext^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fstatement^%^3E^%^3Cvalue^%^20name^%^3D^%^22IF2^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_compare^%^22^%^20id^%^3D^%^22^%^2B^%^25NJuKc)ni^%^5B75f^%^60A^%^3B-9)^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22OP^%^22^%^3ELT^%^3C^%^2Ffield^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22utilityvariables^%^22^%^20id^%^3D^%^22^%^23dSe(ArWX6^%^60B^%^5Bf4^%^5ELtk^%^60^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Utility^%^22^%^3E102^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22math_number^%^22^%^20id^%^3D^%^22qaF4lg1itK^%^5DB^%^5Bgr*^%^60^%^2Fa^%^2F^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E300^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cstatement^%^20name^%^3D^%^22DO2^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22oPf.^%^2C^%^3F^%^3A^%^3D6KRpj^%^3BVsrt^%^3DB^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesAF^%^22^%^20id^%^3D^%^22(Y6Rxm.DTCo86zhu^!7^%^3D^%^3B^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E114^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_setlevel^%^22^%^20id^%^3D^%^22A)E^%^7D^%^7BlCI-r.Y^%^5E6SVW^%^25(^%^5D^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E50^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cnext^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22st^%^3F8S~89^!FcPCTMLWTR^%^5D^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesSZ^%^22^%^20id^%^3D^%^22pY)^%^2F^%^40-Y8nq^!^%^3Bzz^%^5DFW6Rm^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E117^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_setlevel^%^22^%^20id^%^3D^%^22pe^%^60uwB~Ofcj^%^5DJ^%^25qs^%^5Ef^%^40^%^2F^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E50^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fnext^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fstatement^%^3E^%^3Cvalue^%^20name^%^3D^%^22IF3^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_compare^%^22^%^20id^%^3D^%^22*8^%^237Xz9ynd4^!kOGt^%^6007-^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22OP^%^22^%^3ELT^%^3C^%^2Ffield^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22utilityvariables^%^22^%^20id^%^3D^%^22^%^5BFtITgDuhoVN9JP9^%^2F^%^3B)8^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Utility^%^22^%^3E102^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22math_number^%^22^%^20id^%^3D^%^22^%^3DUF)^%^7C^%^3DxG^%^40~jc9bw6^%^3A2~q^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E200^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cstatement^%^20name^%^3D^%^22DO3^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22te^%^5DW^%^5EX^%^5EHkeb3^%^259tT^!H^%^7CX^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesAF^%^22^%^20id^%^3D^%^22B)*.AYz^%^7CC1fVE^%^7C2TT^%^7D6C^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E114^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_setlevel^%^22^%^20id^%^3D^%^22T(^!^%^23VSeU~6(^%^3FEftFZYjV^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E40^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cnext^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^221Y~6))YQvX~8T(LFe7**^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesSZ^%^22^%^20id^%^3D^%^22SyP8W2~^%^3A8n^%^60J1^%^2Fz^!cKvy^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E117^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_setlevel^%^22^%^20id^%^3D^%^22^%^60^%^2BS^%^5DQPt2^%^7D^%^5DvkSo^%^7D8PNKZ^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E40^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fnext^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fstatement^%^3E^%^3Cvalue^%^20name^%^3D^%^22IF4^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_compare^%^22^%^20id^%^3D^%^22^%^2CuseMsL^%^2Fkpm0O2^%^5BEyeer^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22OP^%^22^%^3ELT^%^3C^%^2Ffield^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22utilityvariables^%^22^%^20id^%^3D^%^22TNz^%^5DSoLN^%^23^%^7B2UQBFoWgAi^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Utility^%^22^%^3E102^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22math_number^%^22^%^20id^%^3D^%^22^%^23^%^5DgK3qq(Z1*Xy6()^%^2Bb2Z^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E100^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cstatement^%^20name^%^3D^%^22DO4^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22_48L^%^3D*4^%^2CrjsCu1ma_1A^%^3A^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesAF^%^22^%^20id^%^3D^%^22wr0mZ^%^23-M8WV^%^607P-y^%^7DjbE^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E114^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_setlevel^%^22^%^20id^%^3D^%^22GUw.)^%^239^%^25(^%^3Fa9a^%^7C^%^7B-V2d^%^5B^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E30^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cnext^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22*1Fiki^%^7BziU^%^2Bc^%^3A8o^%^2BoT-x^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesSZ^%^22^%^20id^%^3D^%^22i^!Der^%^3DUoo^%^3B.3Zr.R^%^2BBwY^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E117^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_setlevel^%^22^%^20id^%^3D^%^22Rgc)6Mo63^%^23hMe^!B^%^7D_*6N^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E30^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fnext^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fstatement^%^3E^%^3Cvalue^%^20name^%^3D^%^22IF5^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_compare^%^22^%^20id^%^3D^%^22DCjut_^%^601^%^7B2D^%^2FZb2dM^%^2CKc^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22OP^%^22^%^3ELT^%^3C^%^2Ffield^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22utilityvariables^%^22^%^20id^%^3D^%^22UHx*nc^%^3AI*vP3fO^%^5De^%^7C^%^60y1^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Utility^%^22^%^3E102^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22math_number^%^22^%^20id^%^3D^%^22cNCRo7(s7^%^2CV^%^5BYBG3yrET^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E50^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cstatement^%^20name^%^3D^%^22DO5^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22uOqdZpM8d^%^5DzK^%^3DbZcml_^%^5E^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesAF^%^22^%^20id^%^3D^%^22aCHqPJU^%^7C69(^%^5B1v0G^%^23^%^7BJG^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E114^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_setlevel^%^22^%^20id^%^3D^%^22-77OT2(^%^7Df6O^%^7B^%^25Rx2ZUV.^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E20^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cnext^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22Kr7^%^7BqcB^%^3BSbL^%^23T^%^2FO5i_^%^25r^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesSZ^%^22^%^20id^%^3D^%^22SBz^%^255W_^%^5Do*v^%^7C^%^7Ds)^%^2FGo2R^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E117^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_setlevel^%^22^%^20id^%^3D^%^2263y_fEhE^%^7C^%^2B_4^%^3Bgn.ttCW^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E20^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fnext^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fstatement^%^3E^%^3Cvalue^%^20name^%^3D^%^22IF6^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_compare^%^22^%^20id^%^3D^%^227JZmWUJ^%^3F-^%^25ta^%^2BsUTfjRv^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22OP^%^22^%^3ELT^%^3C^%^2Ffield^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22utilityvariables^%^22^%^20id^%^3D^%^22K^%^5B5jxo3gck^%^3Fi1gGl^%^5BBuk^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Utility^%^22^%^3E102^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22math_number^%^22^%^20id^%^3D^%^22^!0TddSzl_IxM^%^7B~V^%^2CEc^%^60C^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E5^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cstatement^%^20name^%^3D^%^22DO6^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22^%^7B^%^2Bi^%^5B6bR^%^23^%^2C88^%^60^%^7BLf^%^2FPHmM^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesAF^%^22^%^20id^%^3D^%^22dPTSHq^%^7CS..Wp*QF1PC2^%^3F^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E114^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_setlevel^%^22^%^20id^%^3D^%^22Mn_6i^%^23^%^5Bx)gvS^%^2CjAMY3KW^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E8^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cnext^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_set^%^22^%^20id^%^3D^%^22^%^3F7u4BhKwh)XyEK4b^%^25Jv^!^%^22^%^3E^%^3Cvalue^%^20name^%^3D^%^22A^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22switchvariablesSZ^%^22^%^20id^%^3D^%^22VjgED^%^3Bl^%^2C-0-CsD^%^3FwsI^%^7Bs^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22Switch^%^22^%^3E117^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3Cvalue^%^20name^%^3D^%^22B^%^22^%^3E^%^3Cblock^%^20type^%^3D^%^22logic_setlevel^%^22^%^20id^%^3D^%^22^%^7D^%^2F5V^%^3F^%^60(TkjkNp^%^3F^%^3FPg)l4^%^22^%^3E^%^3Cfield^%^20name^%^3D^%^22NUM^%^22^%^3E8^%^3C^%^2Ffield^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fvalue^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fnext^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fstatement^%^3E^%^3C^%^2Fblock^%^3E^%^3C^%^2Fxml^%^3E^&logicarray=^%^7B^%^22eventlogic^%^22^%^3A^%^5B^%^7B^%^22conditions^%^22^%^3A^%^22utilitydevice^%^5B102^%^5D^%^20^%^3E^%^20400^%^22^%^2C^%^22actions^%^22^%^3A^%^22commandArray^%^5B114^%^5D^%^3D^%^5C^%^22Off^%^5C^%^22^%^2CcommandArray^%^5B117^%^5D^%^3D^%^5C^%^22Off^%^5C^%^22^%^22^%^7D^%^2C^%^7B^%^22conditions^%^22^%^3A^%^22utilitydevice^%^5B102^%^5D^%^20^%^3C^%^20400^%^22^%^2C^%^22actions^%^22^%^3A^%^22commandArray^%^5B114^%^5D^%^3D^%^5C^%^22Set^%^20Level^%^2075^%^5C^%^22^%^2CcommandArray^%^5B117^%^5D^%^3D^%^5C^%^22Set^%^20Level^%^2075^%^5C^%^22^%^22^%^7D^%^2C^%^7B^%^22conditions^%^22^%^3A^%^22utilitydevice^%^5B102^%^5D^%^20^%^3C^%^20300^%^22^%^2C^%^22actions^%^22^%^3A^%^22commandArray^%^5B114^%^5D^%^3D^%^5C^%^22Set^%^20Level^%^2050^%^5C^%^22^%^2CcommandArray^%^5B117^%^5D^%^3D^%^5C^%^22Set^%^20Level^%^2050^%^5C^%^22^%^22^%^7D^%^2C^%^7B^%^22conditions^%^22^%^3A^%^22utilitydevice^%^5B102^%^5D^%^20^%^3C^%^20200^%^22^%^2C^%^22actions^%^22^%^3A^%^22commandArray^%^5B114^%^5D^%^3D^%^5C^%^22Set^%^20Level^%^2040^%^5C^%^22^%^2CcommandArray^%^5B117^%^5D^%^3D^%^5C^%^22Set^%^20Level^%^2040^%^5C^%^22^%^22^%^7D^%^2C^%^7B^%^22conditions^%^22^%^3A^%^22utilitydevice^%^5B102^%^5D^%^20^%^3C^%^20100^%^22^%^2C^%^22actions^%^22^%^3A^%^22commandArray^%^5B114^%^5D^%^3D^%^5C^%^22Set^%^20Level^%^2030^%^5C^%^22^%^2CcommandArray^%^5B117^%^5D^%^3D^%^5C^%^22Set^%^20Level^%^2030^%^5C^%^22^%^22^%^7D^%^2C^%^7B^%^22conditions^%^22^%^3A^%^22utilitydevice^%^5B102^%^5D^%^20^%^3C^%^2050^%^22^%^2C^%^22actions^%^22^%^3A^%^22commandArray^%^5B114^%^5D^%^3D^%^5C^%^22Set^%^20Level^%^2020^%^5C^%^22^%^2CcommandArray^%^5B117^%^5D^%^3D^%^5C^%^22Set^%^20Level^%^2020^%^5C^%^22^%^22^%^7D^%^2C^%^7B^%^22conditions^%^22^%^3A^%^22utilitydevice^%^5B102^%^5D^%^20^%^3C^%^205^%^22^%^2C^%^22actions^%^22^%^3A^%^22commandArray^%^5B114^%^5D^%^3D^%^5C^%^22Set^%^20Level^%^208^%^5C^%^22^%^2CcommandArray^%^5B117^%^5D^%^3D^%^5C^%^22Set^%^20Level^%^208^%^5C^%^22^%^22^%^7D^%^5D^%^7D^&eventid=5^&eventstatus=1`

**Comment by gizmocuz** [comment]
Maybe you can shorten the blockly ?

**Comment by w1ll14m** [comment]
Sure, that would work! However the blockly has to be ridiculously small, even a single action already requires 2KB, my blockly isn't even that big, it has 7 conditions with an action. The current implementation is full xml in a request, this causes large request URIs.

**Comment by gizmocuz** [comment]
i would expect that it was also gzipped before sending

**Comment by w1ll14m** [comment]
I Agree but I think that apache decompresses the request to make sure the rewrite rules are processed, apache is configured as a reverse proxy/frontend for Domoticz in my case. At the moment I'm not really stuck on anything and I plan to convert my scripts later on to lua anyway but I think that changing the blockly saving behavior to do a http post in the near future might not be a bad thing.

**Comment by gizmocuz** [comment]
Could you try beta #5849, i converted it into a POST request now

**Comment by w1ll14m** [comment]
Hi gizmocuz,

Thanks, that was fast! Beta #5849 works a treat!

Regards,
William
