### ISSUE TITLE
Qubino crashes my domoticz :  problem node configuration

### ISSUE THREAD

**Issue by perretju** [domoticz/domoticz#952]
Hello,

ZMNHDD1 : input 2 switch type can't be changed (in bistable mode)
ZMNHSD1 : rail din , In switch mode, domoticz crashes.

domoticz version : build 5837,5840,5844...

Best regards,

Perretju

**Comment by gizmocuz** [comment]
Please use our forum:
https://www.domoticz.com/forum/viewtopic.php?f=6&t=14007
