### ISSUE TITLE
Sending a notification through Lua causes 100% cpu

### ISSUE THREAD

**Issue by ppx17** [domoticz/domoticz#953]
Since 77cafc4102351cf15676cfe28ff7e7347a4dce57 I've noticed a problem when sending notifications through Lua. 

Every time it sends a notification the CPU jumps to 100% usage and stays there until Domoticz is restarted.

To test, simply run this Lua with the time trigger:
``` Lua
commandArray = {}

commandArray['SendNotification'] = "Test!#This is a test notification "

return commandArray
```

I've disabled all notification providers, but that doesn't help so it doesn't seem tied to a specific provider.

**Comment by gizmocuz** [comment]
Please use our forum !
And which version ?

**Comment by ppx17** [comment]
I'm sorry, I didn't notice there was also a bug tracking section on the forum. I've had this issue with every version since the mentioned commit. Currently I'm running `V3.5853 Build Hash: 52efef9 Build Date: 2016-11-02 15:27:28`

**Comment by gizmocuz** [comment]
This should be solved in the latest beta release, could you test this ?

**Comment by ppx17** [comment]
I've just built the latest beta and tested again. The good thing: the cpu loop is gone! The bad thing: The scripts doesn't seem to send out any notifications.

I did receive notifications from a blocky and from notifications configured directly on the switches.

**Comment by jackfagner** [comment]
I'm having some problems with LUA scripts (*.lua files) as well. They don't seem to run (nothing in the log) from (some) device events. Got this behavior after updating to latest stable..

**Comment by gizmocuz** [comment]
@Jack, sure if we talk about a fix in the latest BETA, you should try this ... and not report something about a stable, and for sure not something not related to the OP topic. Please use the forum

**Comment by keptenkurk** [comment]
v.35858 solved the (near) 100% cpu load on my Pi2

**Comment by ppx17** [comment]
Just updated to `V3.5874 Build Hash: 9211e41 Build Date: 2016-11-07 08:41:16`. All problems seem to be fixed now.
