### ISSUE TITLE
appversion.default is not up to date

### ISSUE THREAD

**Issue by ffontaine** [domoticz/domoticz#957]
appversion.default has not been updated in the last two releases. This is not major issue but perhaps the values in this file should be checked in makerelase or makebeta (if these scripts are used to make the release)?

**Comment by gizmocuz** [comment]
makerelease could/should make the release version
but i was totally forgotten about this file, because we normally use the automatically created version file
could you make a patch that with makebeta/release this file gets created?
In fact, the content is the same as the automatic created file...
Why did we need this file again? And why can we not use the automatically created file ?
Any build system should be able to create this file.
I remember now... And should be able to go online as well, we live in 2016 almost 2017, sure we can trust a github request ?

**Comment by gizmocuz** [comment]
When we upload the latest code before a release, we have no idea what the build number will become, therefor we can not pre-patch this file

**Comment by ffontaine** [comment]
The issue is that some buildsystems retrieve the archive from https://github.com/domoticz/domoticz/archive/3.5837.tar.gz instead of using a git clone. One of the advantages is that a sha256 can be computed for this archive to check for man-in-the-middle attacks. The issue is that this archive does not contain appversion.h as it is built with the assumption that the user has made a git clone. Concerning the makerelease, it seems that this script is used only for sourceforge. So, I would suggest to close the issue as there is no easy way to automatically update appversion.default.

**Comment by gizmocuz** [comment]
but if the build system, is downloading 3.5837.tar.gz, it knows the version number
the script 'makerelease' has no actual server parameters in it, but the real build script is the same by logic
Okey, so we remove the appversion.default ? are you not using it ?

**Comment by ffontaine** [comment]
The issue is not just about the buildsystem, these variables (APPVERSION, APPHASH and APPDATE) are also used in the code (main/domoticz.cpp). If they are not defined especially APPHASH which is expected to be a string, the compilation will crash. You're right, the buildsystem can know the version but not the hash or the date.

If appversion.default is removed instead of having an "outdated" version number, it will be set to 0 by cmake. I think it's best to have this outdated version number and try to update this file the next time but I have no strong opinion on this subject.

**Comment by gizmocuz** [comment]
Yep, when the build system can not check if there is a new version to build, it will stop (no update)
If it find out that it has to build a new version (... it is online yes), it will build a new version
this generates these fields, which are in turn compiled inside the code, and also uploaded to the server to see that there is a new version
