### ISSUE TITLE
Graph not updated when no data

### ISSUE THREAD

**Issue by buxol** [domoticz/domoticz#958]
In this example the gas consumption graph is not updated this morning while having no consumption last night. When I consume the graph is updated correctly, but in the screenshot I am 'missing' the 4-5 hours of zero consumption at 7.13u
I've created this issue as requested in this topic: http://www.domoticz.com/forum/viewtopic.php?f=6&t=14054

Kind regards,
Roel

![img_0553](https://cloud.githubusercontent.com/assets/23262090/20008966/e832d29e-a2a2-11e6-986e-162cf3fbbb82.PNG)

**Comment by gizmocuz** [comment]
Thanks for reporting!

**Comment by gizmocuz** [comment]
fixed in #1033
