### ISSUE TITLE
Neo CoolCam PIR sensor incomplete Config

### ISSUE THREAD

**Issue by fozzyg** [domoticz/domoticz#960]
For the CoolCam PIR  type 1083 is a config setting 10, for setting the LED On/Off

<Product type="0003" id="1083" name="Battery Powered PIR Sensor 1083" config="shenzen_neo/nas-pd01z.xml"/>

I made local a shenzen_neo/nas-pd02z.xml
<Product type="0003" id="1083" name="Battery Powered PIR Sensor 1083" config="shenzen_neo/nas-pd02z.xml"/>
 
and added the LED  config line ,
 
I do not know how to update the reposotory

    <Value type="byte" genre="config" instance="1" index="10" label="Led Blink Enable" value="1" size="1">
      <Help>This parameter enable or disable the PIR led blinking function. </Help>
      <Item label="Disable" value="0" />
      <Item label="Enable" value="1" />
     </Value>
 maybe somebody can update this 
[nas-pd02z.zip](https://github.com/domoticz/domoticz/files/572543/nas-pd02z.zip)

**Comment by gizmocuz** [comment]
Thank you for this.
But you have to provide OZW configuration files to the OZW team.
Could you post it there ?
When it is in their system, let us know and we update the configuration files of domoticz

**Comment by fozzyg** [comment]
Hello,

The OZW updated the        open-zwave/config/shenzen_neo/nas-pd01z.xml

Can you please update the configuration of domoticz

**Comment by gizmocuz** [comment]
When was this? Do you have a commit url?
Did you verify if it is not in our repo already?

**Comment by fozzyg** [comment]
I did not get a commit URL , but checking the OZW site  I found an updated file on 
https://github.com/OpenZWave/open-zwave/tree/master/config/shenzen_neo/nas-pd01z.xml  
, updated 4 days ago . In this version are the corrected  parameters added. 

The version in your repo is 3 months old

**Comment by gizmocuz** [comment]
Thanks, it's updated in our repo with some other configuration updates.
Beta's available in 30 minutes
