### ISSUE TITLE
Milight red color #ff0000

### ISSUE THREAD

**Issue by Teunissm** [domoticz/domoticz#962]
I saw this problem before on the board but it looks like it isn't solved yet.
The problem is when selecting THE color red (ff0000) THE color turend out purple (looks like ff00c0).
When i send THE hex code ff9900 THE light turns out red (don't not know for sure If this is perfect red?).

Is here probably a solution for?

**Comment by gizmocuz** [comment]
Not yet, please feel free to provide one
