### ISSUE TITLE
No daily electrical consumption

### ISSUE THREAD

**Issue by SeafireGit** [domoticz/domoticz#968]
Since last version upgrade (to 3.5837), I got no electrical consumption for the last 24h. All other graph (last week/month/year) are working for electrical consumption, and all graph are working for temperature.
I use domoticz on a raspberry 3, electrical probe CM 180 via RFXtrx433.

**Comment by SeafireGit** [comment]
Problem reported here multiple times : http://www.domoticz.com/forum/viewtopic.php?f=6&t=14012

**Comment by gizmocuz** [comment]
No cross posting please,i send a private message to two posters there to debug

**Comment by SeafireGit** [comment]
Could I get a message to debug also please ? Is that bug solved ???

**Comment by gizmocuz** [comment]
No, i asked for a database backup, please send me a PM on the forum so i can reply with my email address
