### ISSUE TITLE
Compilation error - Ubuntu 12.04

### ISSUE THREAD

**Issue by marsys** [domoticz/domoticz#97]
Hi,
 I am trying to compile domoticz under Ubuntu 12.04,
 Till my last update (Sep 21, 2015) everything was OK.

 Today (Sept 25, 201) I get errors.
 Here is the error I am received:

[ 46%] Building CXX object CMakeFiles/domoticz.dir/hardware/Kodi.cpp.o
/home/harry/domoticz/hardware/Kodi.cpp: In memberfunctie ‘void CKodi::Do_Work()’:
/home/harry/domoticz/hardware/Kodi.cpp:745:14: fout: ‘class boost::asio::io_service’ has no member named ‘stopped’
/home/harry/domoticz/hardware/Kodi.cpp: In memberfunctie ‘void CKodi::UnloadNodes()’:
/home/harry/domoticz/hardware/Kodi.cpp:922:40: fout: ‘class boost::asio::io_service’ has no member named ‘stopped’
make[2]: **\* [CMakeFiles/domoticz.dir/hardware/Kodi.cpp.o] Fout 1
make[1]: **\* [CMakeFiles/domoticz.dir/all] Fout 2
make: **\* [all] Fout 2
Compile failed!

**Comment by gizmocuz** [comment]
i think this has to do with the latest kodi changes.

Could you update your boost library and try again ?

**Comment by marsys** [comment]
Great, no more compiler errors after updating the boost library.
Thanks

**Comment by dodgecle** [comment]
To what version should i update? now i have 1.48 and still the same error

**Comment by gizmocuz** [comment]
1.59, 1.56 should also work
