### ISSUE TITLE
Evohome TPI values aren't exported via HttpLink

### ISSUE THREAD

**Issue by jdp80** [domoticz/domoticz#972]
I have a comprehensive Evohome installation with HGI80.

I am successfully exporting the sensor details to InfluxDB via HttpLink, however for any 'TPI' based switches (radiator valves, DHW, boiler control) only the "Status" field is available for export. 

This just gives a boolean for On/Off, not the % value reflecting the current TPI value. 

The Evohome sensor is 'On/Off' type, changing to 'Dimmer' didn't make any difference.

![sitting2](https://cloud.githubusercontent.com/assets/23378755/20174120/4db4828a-a734-11e6-9d84-afacc87dfc26.png)
![sitting1](https://cloud.githubusercontent.com/assets/23378755/20174134/5bb31888-a734-11e6-8db5-0cc74ed9e6fd.png)
![sitting3](https://cloud.githubusercontent.com/assets/23378755/20174121/4dc06b72-a734-11e6-99c0-10c9b47affe6.png)

**Comment by sbouchex** [comment]
According to the code (RFXNames.cpp) , pTypeEvohomeRelay/sTypeEvohomeRelay sensor type is only exporting a "Status".

@gizmocuz any comment ?

**Comment by gizmocuz** [comment]
Nope, i did not implement this hardware, and have also no idea how this works, also do not own this hardware
You might have to contact the original author, you should be able to find it by browsing the commit log/history

**Comment by sbouchex** [comment]
@Evsdd, As you are the author of this part, any comment ?

**Comment by Evsdd** [comment]
@sbouchex. Thanks for flagging this request.  I'll take a look and see if I can extend the Evohome TPI device definition to allow the level information to be exported by Httplink without it breaking other functions.  

As @jdp has mentioned, the implementation is based on a dimmer switch, but all switch devices appear to only report their status field via HttpLink so there isn't an obvious template to follow for this one so it'll likely take me some time to solve.

**Comment by sbouchex** [comment]
All starts from the method RFX_Type_SubType_Values which exports the level information to be exported to all "Pushers" but you may break Cmd_GetDevicesListOnOff to adding more level in the string constant.

**Comment by Evsdd** [comment]
My really dumb starting point is trying { pTypeEvohomeRelay, sTypeEvohomeRelay, "Status, Value" }, and then trying to discover what it produces and breaks and then learn all the implications of this data structure.  I'm not thinking of redefining the contents of Status to include the level value as this will definitely impact many other features.

**Comment by sbouchex** [comment]
That's an option but in order to keep Cmd_GetDevicesListOnOff  working, you will have to split the string to check if "Status" is contained in the returned string. For the rest, I let you discover ;-)

**Comment by Evsdd** [comment]
@sbouchex thanks for all your pointers.

**Comment by Evsdd** [comment]
@jdp80 I think I have a working solution which is ready for testing.  Are you able to compile Domoticz from source to see if the fix solves your issue?

**Comment by sbouchex** [comment]
@Evsdd I don't have the right hardware however since I'm the author of the Httplink featuee, I may have a look at your code.

Why don't you just clone the domoticz repository and do a branch ?

**Comment by Evsdd** [comment]
@sbouchex Thanks very much.  I've got a couple of other updates to complete at the moment and then I'll post the update to my Github branch.
