### ISSUE TITLE
Set setpoint does not handle Until value correctly

### ISSUE THREAD

**Issue by gordonb3** [domoticz/domoticz#986]
That is: on Windows. Both with Firefox and IE the `Until` value is not filled with the give value but shows the (past) midnight time of the current day. Additional issue with Firefox is that there is a very rapid refresh of the input field that makes typing into it very troublesome - you're essentially forced to use the slider in the popup date selector.

The `Until` value is loaded correctly in Linux (also Firefox).

**Comment by gizmocuz** [comment]
Not sure what you mean... but maybe you could make a pull request?

**Comment by gordonb3** [comment]
I have no clue where the issue could be.

The thing is: I use an alternate script for evohome that fills the `Until` value with the next scheduled set point so I have this value for each zone regardless of whether there is a previous timed override active. This value is supposed to be copied to the set setpoint dialog but there appears to be some other datetime value override in action. At present I'm unsure if this override simply does not work on Linux, or if this override does not properly detect on Windows that there is a valid `Until` time already.

In any case, if you have such a device you should be able to replay it by setting a setpoint with an `Until` value and then try to set it again. On Windows I get the current date with time 00:00:00. On Linux it shows me the known value, like it should.

**Comment by gordonb3** [comment]
As a note, I have not used this function since previous winter. I do remember that at the time when I altered the normal update script to include the schedule the `Until` field used to be empty by default, resulting in overrides being permanent. This must therefore be a fairly recent update to this behaviour, say seven months max. There wouldn't be any such change that pops into your mind right now, would there?

**Comment by gizmocuz** [comment]
can you point me to the device page ?

**Comment by gordonb3** [comment]
See images:

Edit Set Point on Linux:
![Edit Set Point on Linux](http://i63.tinypic.com/e7xun9.jpg)

Edit Set Point on Windows:
![Edit Set Point on Windows](http://i64.tinypic.com/2mfis1k.jpg)

**Comment by gordonb3** [comment]
Identified: commit 6333ac5 is what caused the issue

And the problem occurs on Linux as well. For some reason the local cache of the javascript that became faulty after this commit did not get updated on my machine.

**Comment by gizmocuz** [comment]
So you need to clear your browser cache and app-cache and it is working again?

**Comment by gordonb3** [comment]
No. It is actually a bug. For some reason this particular system missed out on receiving the update that had the problem in it. It was after I did a full install of the 6136 build that I got the same fault that I previously got on Windows.

**Comment by gizmocuz** [comment]
I think you solved this now with a pull request

**Comment by gordonb3** [comment]
Correct. The screen is back to how it used to be and shows an empty field for `Until` again instead of a time in the past. The rapid overwrite of whatever you try to type directly in the field is now also gone.

Issue closed.
