### ISSUE TITLE
I have a fix for intermittent issue with NefitEasy crashing domoticz, how to submit?

### ISSUE THREAD

**Issue by philippe72** [domoticz/domoticz#987]
Well, I guess the title says it all :-)

I have fixed an issue causing domoticz to crash every few days while communicating with the Nefit server. I would like to submit this fix for review/adding.

Unfortunately I am unfamiliar with the world of git(hub), so could you please point me to the instructions for how to submit my fix?

(And if this is not the correct place to ask this question, I apologize)

**Comment by gizmocuz** [comment]
-1 goto our github page and fork the project to your own account (top right)
-2 patch the code
-3 commit your code
-4 goto your github repository (the forked one from domoticz)
You will see a green button, create pull request
press this button
-5 you should now see it in our main repo under pull requests
-6 wait till someone reviews/comments/merges your pull request

**Comment by philippe72** [comment]
Great, will do. Running an endurance test right now. I expect to commit my fix for review this weekend

**Comment by gizmocuz** [comment]
Closing this, please create a pull request if you have a patch, thanks in advance
