### ISSUE TITLE
unable to build on fedora

### ISSUE THREAD

**Issue by prysme01** [domoticz/domoticz#990]
Hello all

I'm trying to build domoticz on fedora but unfortunetaly I'm missing dependancies
Could not find the following static Boost libraries:

          boost_thread
          boost_date_time
          boost_system

Do you know how to install them ?
cheers.

**Comment by prysme01** [comment]
I reply to myself
dnf install libstdc++-static

fix the issue

**Comment by gizmocuz** [comment]
http://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI
