### ISSUE TITLE
Logitech Hub doesn't login anymore

### ISSUE THREAD

**Issue by Calimerorulez** [domoticz/domoticz#992]
Since a couple of days I'm seeing the following error in the log:

Error: Harmony Hub: Logitech web service login failed.

I checked my username/password and they are correct. Is there a way I can provide/see more debugging so I can try to solve it?

**Comment by gizmocuz** [comment]
Please use our forum, it has already been reported there.
Seems a problem on Logitechs side... android/iphone app are still working, maybe working with a stored token
You can always try to debug by looking at the code
