### ISSUE TITLE
Average values in History of some seems to be off

### ISSUE THREAD

**Issue by ernorv** [domoticz/domoticz#995]
I noticed that some average values as present in the database are sometimes completely wrong. I also tracked down the origin of this. As usual it has to do with more than just a single thing.
- when having data that is only forwarded to Domoticz on change, the short log database is not completely filled with data for every data point
- this implies that one can not do a simple avg, as e.g. done for the Percentage case, SQLHelper.cpp line 5488:
```
result=safe_query("SELECT MIN(Percentage), MAX(Percentage), AVG(Percentage) FROM Percentage WHERE (DeviceRowID='%" PRIu64 "' AND Date>='%q' AND Date<'%q')",
			ID,
			szDateStart,
			szDateEnd
			);
```

Because one can now not rely on the fact that all values are to be 'weighted' the same (in mathematical terms that is). Unfortunately given the structure of the database (at least I looked at the Percentage case) there is no easy way of calculating the right average percentage over a day by the SQL means, as one now needs to do something like: sum over (duration in minutes of a certain setting) * setting / (duration over whole day), which implies taking the difference between the current date in the database and the last date of the same sensor before the current point.

Maybe this is something that requires some explicit calculation in Domoticz by simply getting all the values for a given day?

Regards ernorv

**Comment by gizmocuz** [comment]
Okey, before, we only used the highest value, then we took the highest and lowest value, and now we are averaging all the values.
Sure this is correct, a good sensor transmits lets say every 5 minutes, why is the average of all values not the average ?
Indeed, when you make your own sensor, and this only does send an update on change, yes, then it is of course a different story, especially if you only send on very big differences
So best to send it every 5 minutes then right ?

**Comment by ernorv** [comment]
This actually depends on the type of sensor I guess. One can always store sensor information, even it is duplicate indeed, but this could lead to having to resort to make intermediate points which actually has to resend the information, again depends on the sensor that starts the transmission in the first place. 

E.g. how would one determine the average percentage a door/window has been open during a day where a sensor only tells the open and close event?

but in my specific case I guess I'll just change the transmission such that it is repeated as I like the average :)

**Comment by gizmocuz** [comment]
If you only log when there is a change, there is no need for an average anyway, as this does not make sense indeed
