### ISSUE TITLE
kVAh openzwave meter are reported as kWh meter

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#996]
Qubino Smart Meter ZMNHTDx openzwave device  are reporting a new kind of meter : kVAh
When added, it is reported as a kWh meter because it's a energy meter and because the unit is not checked.

I was planning to do it.

Proposal :
- Add a new pTypeGeneral called sTypeKvah = 0x20
- Store a single value when the value is reported

Other option is pTypeENERGY

**Comment by gizmocuz** [comment]
Or you can convert it to kwh ? A new sensor type for this is maybe the best option if that is not desired...

**Comment by sbouchex** [comment]
To convert to kW, the rule is P(kW) =  S(kVA) × PF and PF is the Power Factor (also part of the sensors and reported).
The main problem is that the unit is not correct whereas it's fine in the ozw control panel.

**Comment by gizmocuz** [comment]
i think you can search for the powerfactor sensor in the list of existing sensors for this node ?

**Comment by sbouchex** [comment]
I can do it but I don't see the point of converting to values to kWh as the same sensor already exists. See the control-panel output:

![qubino](https://cloud.githubusercontent.com/assets/2684878/20465872/f559a78c-af67-11e6-94fa-2c3b4bd4b59a.png)

If one day, somebody requires real kVAh, you will not ask him to device the kWh by the power factore...

**Comment by gizmocuz** [comment]
Then maybe ignore the kVAh, or create a new sensor type.
Is a display in kVAh useful ? compared to kWh ?

**Comment by sbouchex** [comment]
kVAh may be useful when monitoring none-resistive load (like motors, engines...) because the Power Factor is not equal 1000, it's more industry oriented.
kVAh sensors may be hidden for now and someday, it may come back :-)

Last option (which was my initial proposal) is to create a new sensor type.

**Comment by gizmocuz** [comment]
Yes, so it is not something really for home automation then ?

**Comment by sbouchex** [comment]
I don't think so, but Qubino is selling its Smart Meter ZMNHTDx for home usage.

**Comment by octavianrusu** [comment]
I have the same issue in Domoticz (in fact it is much bad - I have only readings for kVA and not for kWh), it is not possible to calculate the total Energy (kVAh) using samples of Energy (kWh) and power factor. The result is totally wrong, I tried to calculate but no good results. In fact both values are quite useful to see how much power you have on reactive devices (and there are a lot - all motors in the house).
Thank you!

**Comment by gizmocuz** [comment]
@octavianrusu , did you update to the latest beta version ? kVAh should be working now
